### ISSUE TITLE
The vertical position of the value of a TextInput is different if it starts with a defaultValue

### ISSUE THREAD

**Issue by jpamarohorta** [facebook/react-native#23660] opened 2019-02-26 18:43 UTC
## 🐛 Bug Report
The vertical position of the value of a `TextInput` is different if it starts with a `defaultValue` or not.

It seems that it's caused by the `lineHeight` style attribute, given that removing this attribute, fixes the problem.

## To Reproduce
1. Create two `TextInput` components, one with a `defaultValue` and the other without.
2. Set the same styling (including `lineHeight` for both).
3. You will notice that the vertical positioning of the values in the two `TextInput` are different.

## Expected Behavior
It would be expected for the height of the value in a `TextInput` to be the same regardless of the presence of a default value.

## Code Example
https://snack.expo.io/BkWzv-7UN

## Screenshot Example

![ep5ulxxl](https://user-images.githubusercontent.com/165856/53441648-1b875680-39bc-11e9-9b63-204b53952ec1.png)

https://i.imgur.com/Ep5uLXX.png

## Environment
```
React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (4) x64 Intel(R) Core(TM) i5-5675R CPU @ 3.10GHz
      Memory: 96.34 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.9.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.3, 28.0.0, 28.0.3
        System Images: android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-25 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.58.3 => 0.58.3
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

**Comment by hramos** [comment] 2019-02-26 19:27
I ran your Snack on my device and it's not immediately obvious to me what's wrong. Could you include an annotated screenshot in your issue? What would the correct layout look like?

**Comment by jpamarohorta** [comment] 2019-02-26 19:35
> I ran your Snack on my device and it's not immediately obvious to me what's wrong. Could you include an annotated screenshot in your issue? What would the correct layout look like?

I've edited the post and added a link to a screenshot. The issue can be noticed in the distance between the red border and the text.

**Comment by hramos** [comment] 2019-02-26 19:45
Great! Thanks for the additional info.

**Comment by dulmandakh** [comment] 2019-03-19 17:36
I couldn't reproduce the issue on React Native 0.59.

Hello there 👋 this issue has been reported for an old version of React Native. Ideally we'd like everyone to be using 0.59 (see the [awesome changes](https://facebook.github.io/react-native/blog/2019/03/12/releasing-react-native-059) it brought) but we know updating can be a pain. We are going to close this issue because it's from a version before 0.57, which is really old.

But please, if it's actually still an issue with 0.59 please comment below and we can reopen it. Even better, please send us a pull request with a fix 😊

**Comment by zhongwuzw** [comment] 2019-05-14 15:43
@jpamarohorta Hi :) can you check the latest master branch, we fixes some bug for text input component, is it still reproducible? I checked it, seems looks the same.
<img width="367" alt="image" src="https://user-images.githubusercontent.com/5061845/57711789-001a1680-76a2-11e9-8610-f292958cb6bc.png">

**Comment by zhongwuzw** [comment] 2019-05-18 15:04
@jpamarohorta Hi :), thanks for reporting, I'll close this issue because I can't reproduce in latest master branch, seems it's already fixed. Feel free to comment if you still met the issue.

**Closed by zhongwuzw** 2019-05-18 15:04 UTC
Labels: Bug, Component: TextInput, Platform: iOS

**Comment by RageOfJustice** [comment] 2020-02-06 09:34
Hello! Here [example](https://snack.expo.io/@justice/9c63af). Behaves differently and wrong on both platforms
I use bare project with react-native 0.61.5
