### ISSUE TITLE
App not installed with unsigned release apk

### ISSUE THREAD

**Issue by mocanSergiu666** [facebook/react-native#14321] opened 2017-06-05 10:22 UTC
I cannot install an application on a real device from unsigned release apk.
But when I try to install debug apk, it installs sucessfully, but the application doesn't work properly, it shows the red screen with the error "Could not connect to developmenet server".
What's the problem?

react native 0.44
android 4.4.2 real device

**Comment by pavitran** [comment] 2017-06-05 11:30
if you have android studio installed, run
`react-native bundle --platform android --dev false --entry-file index.android.js   --bundle-output android/app/src/main/assets/index.android.bundle   --assets-dest android/app/src/main/res/`
and then import to android studio and run as normal app.

I'm getting the same error with and 4.4.2, the issue is `adb reverse tcp:8081 tcp:8081` failing.

**Comment by hramos** [comment] 2017-06-05 20:52
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-05 20:52 UTC
