### ISSUE TITLE
Error after upgrading to React Native v0.43.3 :Expected array with count 16, but count is 3

### ISSUE THREAD

**Issue by fengjr-tech** [facebook/react-native#13458] opened 2017-04-12 01:33 UTC
Error after upgrading to React Native v0.43.3 
Error setting property 'transform' of RCTView with tag #9: Expected array with count 16, but count is 3: (
        {
        scale = 1;
    },
        {
        translateX = 0;
    },
        {
        translateY = 0;
    }
)
![simulator screen shot 2017 4 12 9 32 27](https://cloud.githubusercontent.com/assets/26806455/24937395/0abe793e-1f63-11e7-884d-93f436254b8c.png)

**Comment by hramos** [comment] 2017-04-14 22:40
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-04-14 22:40 UTC
