### ISSUE TITLE
'RCTAppDelegate.h' file not found

### ISSUE THREAD

**Issue by NitinSinghElegant** [facebook/react-native#38137] opened 2023-06-30 06:25 UTC
### Description

I am using Mac with m2 chip. I am unable to build app. It is giving me **'RCTAppDelegate.h' file not found** error while I am using **@react-native-firebase/app@17.4.2**. Tried every possible way not working. Please help in.
<img width="1440" alt="Screenshot 2023-06-30 at 11 46 49 AM" src="https://github.com/facebook/react-native/assets/130339696/b13f9077-6670-43ce-b7c2-6befaf702a91">
<img width="1440" alt="Screenshot 2023-06-30 at 11 49 41 AM" src="https://github.com/facebook/react-native/assets/130339696/774771b6-ece4-44de-8278-d0baef873144">

### React Native Version

0.71.6

### Output of `npx react-native info`

<img width="1440" alt="Screenshot 2023-06-30 at 11 52 12 AM" src="https://github.com/facebook/react-native/assets/130339696/86aa30f8-4d47-4622-9bbc-a3a98e7aa80f">

### Steps to reproduce

follow the below steps:-
1. https://rnfirebase.io/ open link and follow the installation  and implementation  guide.
2.  run your app by executing yarn run ios or npx react-native-run-ios

### Snack, code example, screenshot, or link to a repository

<img width="1440" alt="Screenshot 2023-06-30 at 11 54 59 AM" src="https://github.com/facebook/react-native/assets/130339696/cc2dfd00-cd97-48a5-af49-70e1692459c7">

**Comment by NitinSinghElegant** [comment] 2023-06-30 08:33
This issue still persist after upgrading to latest version as recommended -0.71.11
<img width="1440" alt="Screenshot 2023-06-30 at 2 02 19 PM" src="https://github.com/facebook/react-native/assets/130339696/da083860-24eb-4175-9fb1-a8af2a9c9fe1">

**Comment by NitinSinghElegant** [comment] 2023-06-30 08:34
This issue still persist after upgrading to latest version as recommended -0.71.11
<img width="1440" alt="Screenshot 2023-06-30 at 2 02 19 PM" src="https://github.com/facebook/react-native/assets/130339696/da083860-24eb-4175-9fb1-a8af2a9c9fe1">

**Comment by cipolleschi** [comment] 2023-06-30 09:19
Can you please share your Podfile? 
Firebase works only with `use_frameworks` turned on and set to static.

Typical troubleshooting steps:

1. make sure to run `yarn` and `bundle exec pod install` after updating. Verify in Xcode that you actually have a pod called `React-RCTAppDelegate` which contains the `RCTAppDelegate.h`
2. make sure that the call to `use_framework! :linkage => :static` in the `Podfile` happens before the `use_react_native_pods!` function 
3. If all of the above fails, open your `AppDelegate.h` and try to change the import from:
    ```diff
    - #import <RCTAppDelegate.h>
    + #import <React_RCTAppDelegate/RCTAppDelegate.h>
    ```
If `<React_RCTAppDelegate/` does not work, try with `<React-RCTAppDelegate/` I don't remember which of the two is the right one... 😅

**Comment by MrLibya** [comment] 2023-07-05 12:37
Same issue here, when I build the app from Xcode I got the 'RCTAppDelegate.h' file not found, same thing with:
```
#import <React_RCTAppDelegate/RCTAppDelegate.h>
#import <React-RCTAppDelegate/RCTAppDelegate.h>
``` 

However when I build from react native `npx react-native run-ios` it dose build and run but metro is never connected:

![‏لقطة الشاشة 2023-07-05 في 2 36 18 م](https://github.com/facebook/react-native/assets/22921411/0d0cb04b-fc00-41fd-9d83-c348473413ba)


podfile:
```
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'boursaRN' do
  config = use_native_modules!

#   pod 'Firebase', :modular_headers => true
#   pod 'FirebaseCore', :modular_headers => true
#   pod 'GoogleUtilities', :modular_headers => true
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # :flipper_configuration => flipper_config,
    :flipper_configuration => FlipperConfiguration.disabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'boursaRNTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
```

**Comment by MrLibya** [comment] 2023-07-05 20:32
-- update --
As my previous comment I though that the bug related to rn or rn firebase, the error was actually from the react native splash screen

[solution](https://github.com/crazycodeboy/react-native-splash-screen/issues/610#issuecomment-1498654605)

**Comment by cipolleschi** [comment] 2023-07-06 09:54
I noticed that this is a duplicate of #36611 so please, redirect all the questions to that one.

**Closed by cipolleschi** 2023-07-06 09:54 UTC
Labels: Needs: Triage :mag:, Needs: Author Feedback, Type: New Architecture

**Comment by NitinSinghElegant** [comment] 2023-07-06 09:58
I resolved it making a new branch from the main. can be closed

**Comment by Fawaz441** [comment] 2024-04-20 11:53
This issue still persists

**Comment by nandowastaken** [comment] 2024-07-04 14:58
The issue for me was that I was opening the "projectName".xcodeproj in XCode, instead of the "projectName".xworkspace. When I opened the .xworkspace, it worked fine.

**Comment by iamcc30** [comment] 2025-01-04 15:53
> The issue for me was that I was opening the "projectName".xcodeproj in XCode, instead of the "projectName".xworkspace. When I opened the .xworkspace, it worked fine.

nice!!! it's work for me too!!!

**Comment by supriyoMondal** [comment] 2025-05-30 06:08
<img width="913" alt="Image" src="https://github.com/user-attachments/assets/0bf74c48-d77f-493b-80cb-48bd9d0094be" /> this solved my issues after rn upgrade.

**Comment by yogendrajs** [comment] 2025-08-06 12:29
issue still persists

**Comment by MuhammadAnwaar9** [comment] 2025-09-25 08:58
@yogendrajs  try this https://github.com/facebook/react-native/issues/36611#issuecomment-3332957164
