### ISSUE TITLE
'react-native init MyApp --template demo' is not work

### ISSUE THREAD

**Issue by MarnoDev** [facebook/react-native#13130] opened 2017-03-24 09:13 UTC
`react-native init MyApp --template navigation` is OK for me , but why `react-native init MyApp --template demo`  is not.

**Comment by hramos** [comment] 2017-03-24 17:35
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-03-24 17:35 UTC
