### ISSUE TITLE
Upgrate 

### ISSUE THREAD

**Issue by sm2017** [facebook/react-native#15185] opened 2017-07-25 05:17 UTC
Please don't close issue immediately you reply 

I open https://github.com/facebook/react-native/issues/15105 and https://github.com/facebook/react-native/issues/15153 before for this issue , I send PR #15046 and fix a websocket bug , In my local repository I don't know how can I use bug fixed version

> react-native-git-upgrade doesn't support arbitrary commits. you should run it on the latest release before that commit, then update the version in package.json again to the commit you want. a PR to support this is welcome, if you don't want to work on that then please create a feature request on http://react-native.canny.io/

In this case , I have last released native codes version (With websocket bug) and specific commit of js codes

1- How can I upgrade both native and js codes to specific commit?
2- Can you release new version that includes https://github.com/facebook/react-native/commit/7e29b1fc7711a285765f021be3e83a981b066435 ?

**Comment by hramos** [comment] 2017-07-25 17:13
Hey, thanks for opening the issue. I want to kindly direct you to the issue template that is displayed when you open a new issue. Specifically, there is a note there stating that issues that do not adhere to the template will be closed. We're dealing with a large number of open issues at the time and we kindly ask everyone to work with us and do a bit of work ahead of time in order to make sure issues are actionable. Thanks for your understanding.

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-07-25 17:13 UTC
