### ISSUE TITLE
docs: Search not working

### ISSUE THREAD

**Issue by malashkevich** [facebook/react-native#17375] opened 2017-12-28 08:57 UTC
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment
  Environment:
  OS:  macOS Sierra 10.13.2

### Steps to Reproduce

(Write your steps here:)

1. Open http://facebook.github.io/react-native/
2. Try to search something

### Expected Behavior

Search should perform 
(Write what you thought would happen.)

### Actual Behavior
Search not working

**Comment by s-pace** [comment] 2018-01-25 13:52
Hi there,

React Native features [DocSearch](https://community.algolia.com/docsearch/).

👋  @hramos (@vjeux)

It look like the `master` pages aren't using the right tag (The latest version is hardcoded instead of `master`).

I have made a [quick fix in order to don't stop the search in production](https://github.com/algolia/docsearch-configs/commit/dd8bd78c306e0929f2285409bdfaff5af9544c77) but please update [your tag from your DocSearch snippet](https://github.com/s-pace/react-native/commit/4bf072ad4e93152c88fceeedc1ee633cecbc6499). I can't do a PR on the `gh-pages` according to your Contributing Guide.

It is not [the first time this issue happen](https://twitter.com/yrezgui/status/946530587451576332). 

Feel free to ask us for any other point, we would be happy to help.

**Comment by hramos** [comment] 2018-01-25 18:08
Thanks for the insight @s-pace! @malashkevich and @s-pace: the website is not hosted in this repo, please see https://github.com/facebook/react-native-website

I'm going to close this as a duplicate of https://github.com/facebook/react-native-website/issues/61

**Closed by hramos** 2018-01-25 18:08 UTC
