### ISSUE TITLE
Android: ScrollView doesn't scroll when content size is less than outside view's size

### ISSUE THREAD

**Issue by vasiliy-sarzhynskyi** [facebook/react-native#11156] opened 2016-11-27 14:40 UTC
On Android, ScrollView scrolls only in case when outside view's size less than ScrollView content's size (in this case onScroll doesn't invoked).  If content size becomes more than view's size, onScroll invokes fine.
This feature is critically needed when handling scroll up and scroll down behavior (on scroll up I need to add new items to ListView).

in first screenshot onScroll works, and in second it doesn't work.
![scroll works](https://cloud.githubusercontent.com/assets/22271138/20649062/25a44bfc-b4bf-11e6-88c9-01db6121a8bc.png) ![scroll not works](https://cloud.githubusercontent.com/assets/22271138/20649065/2adfb7b4-b4bf-11e6-930a-195e698f11a4.png)

On iOS onScroll works fine in both cases (for screenshot 1 and 2).

Please check the following snippet:
```
render() {
        return (
            <View>
                <ScrollView
                    contentContainerStyle={styles.container}
                    onScroll={e => this.onScroll(e)}
                    scrollEventThrottle={0}>
                        <ListView
                            contentContainerStyle={styles.list}
                            dataSource={this.state.dataSource}
                            enableEmptySections
                            renderRow={this.renderRow}
                        />
                </ScrollView>
            </View>
        )
    }
```
styles:
```
container: {
        flexDirection: 'row',
        paddingHorizontal: 3
    },
    list: {
        flex: 1,
        flexDirection: 'column',
        flexWrap: 'wrap',
        alignItems: 'stretch',
        paddingVertical: 5,
        paddingHorizontal: 3
    }
```

Does exist any workaround for this issue? 
it seems like a bug.
any ideas?

### Additional Information

* React Native version: 0.37.0
* Platform: Android
* tested on real device: Nexus 5X

**Comment by nihgwu** [comment] 2016-11-28 01:37
That's not a bug, `ScrollView` doesn't support scroll over bounce effect on Android, it's Apple's patent

**Comment by mkonicek** [comment] 2016-11-28 01:40
I don't understand the description. What is the outside view? Can you provide a minimal amount of code to reproduce this on [rnplay.org](https://rnplay.org/)? This is necessary for people to be able to see and debug the issue being reported.

Closing this issue as it is not actionable. Please open a new one with an rnplay link (preferred), or link to a GitHub repo with clear instructions how to repro.

**Closed by mkonicek** 2016-11-28 01:40 UTC
