### ISSUE TITLE
Over 40% js execution time increase in RN71.7. Actual production app launch to render time increased by 500% (3s->15s)

### ISSUE THREAD

**Issue by smith-chris** [facebook/react-native#37335] opened 2023-05-09 13:48 UTC
### New Version

0.71.7

### Old Version

0.69.10

### Build Target(s)

Samsung A53 Android release build, iPhone 10 & 12 release build

### Output of `react-native info`

No need for react-native info. All three example projects: (Albeit 0.69.10 & 0.71.7 is enough) are here: https://github.com/smith-chris/rn717-perf-issues

### Issue and Reproduction Steps

As you can see on the video, in the example app I provided the perceived launch time jumped from around 5/5.1s to 7.3s (69.10 vs 71.7). It's a fresh react native app installed with `react-native init YourProjectName --version X.Y.Z` plus a theme processor we use run 5 times to test the performance. 
The reason I started investigating it is that our actual production app launch->render time jumped from 3s to 15s on android (on ios 1.8s->4.5s), code for which I naturally cannot share.

Although that surely that production app can and will be improved - it still leaves 0.71.7 much less performant than some previous releases. I hope that with the given helps address that issue as we seem to be not the only one having perf downgrades in recent RN releases.

https://github.com/facebook/react-native/assets/17379615/c0826b50-2b59-4a9a-b156-9c8a0829f017

Some other issues i found:
https://github.com/facebook/react-native/issues/36296
https://github.com/facebook/react-native/issues/36123

For some people 71.7 seemed to solve the performance issue but not for us. At the moment we are probably gonna downgrade to 0.69.10 and wait until React Native gets back in shape.

**Comment by smith-chris** [comment] 2023-05-10 10:47
Just tested on simulator & the prod version has even bigger 200% js execution time increase. Added RN 70.9 project to the git linked in the post and the regression is present there so it happened somewhere between RN 69.10 and RN 70.9.

**Comment by cortinico** [comment] 2023-05-10 11:00
Thanks for reporting this @smith-chris and thanks for sharing the video.
Just to clarify, are you testing the release version and not the debug version right?

**Comment by smith-chris** [comment] 2023-05-10 11:18
Yes, I'm using `react-native run-android --variant release` command ('android:release' in package.json in the github repo I linked). 
I just tested RN 70.0 and the 200% js execution time increase is also present there regardless of hermesEnabled = true or false. I'm gonna be downgrade the app to 0.69.10 and keep it until the issue is solved.

**Comment by deggertsen** [comment] 2023-05-11 01:52
We're having significant performance issues as well. Still trying to nail down exactly what the root cause is, but it's certainly concerning to see quite a few people reporting performance issues with these recent versions.

**Comment by smith-chris** [comment] 2023-05-12 09:42
Seems like multiple people have been affected and if my measurements are correct this is a significant and important regression. 
@cortinico have you or any other RN maintainer looked into this?

**Comment by ThePlatinum** [comment] 2023-05-12 15:25
Same here, app performance really slow, similar to [#36123](https://github.com/facebook/react-native/issues/36123)

**Comment by rlueder** [comment] 2023-05-12 15:56
Just wanted to add to the list, we upgraded from `0.68.6` to `0.71.6` and then to `0.71.7` and our stability scores on Bugsnag for releases since the upgrade have tanked. We're also getting multiple user reports about general app slowness and crashes.

**Comment by andreasasprou** [comment] 2023-05-15 12:05
We're experience the same issue. It would be good to have clarity on how this is being prioritised by the RN team.

**Comment by kelset** [comment] 2023-05-15 13:31
Closing as duplicate of https://github.com/facebook/react-native/issues/36296 and https://github.com/facebook/react-native/issues/36123

please add comments there, opening new issue does more harm than good

**Closed by kelset** 2023-05-15 13:31 UTC
Labels: Needs: Triage :mag:, Type: Upgrade Issue

**Comment by smith-chris** [comment] 2023-05-15 14:07
@kelset Closing this issue does more harm than good. It would be beneficial to keep this and other similar issues visible on the RN issues page, so they can be addressed promptly. I noticed that the linked issues from 3 months ago are still unresolved. This is important regression to fix as it affects many production apps as seen in this thread and related threads. I'd like to emphasize, this is 50%-200% performance reproducible from in the linked repo and up to 500% regression in a code I cannot share.

Does the React Native team still prioritize performance? Performance has always been a key selling point of RN, but it seems to have taken a backseat lately. It would be reassuring if someone in the thread could confirm that this issue will be addressed in the near future.

I'd like to point out that the fixes released in versions 0.71.7 & 0.70.9 that were indicated as solutions for https://github.com/facebook/react-native/issues/36296 and https://github.com/facebook/react-native/issues/36123 did not resolve the problem demonstrated by the repo linked in this issue: https://github.com/smith-chris/rn717-perf-issues. This is another reason why this issue should stay open.

**Comment by tj-mc** [comment] 2023-05-15 23:04
The maintainers are actively working on this, as you can see by the attempts to fix it. Since the issue has already been identified as a duplicate, keeping the conversation going on an single thread is the simplest way to get closer to a solution. Of course they care about performance. This is a hugely complex open source project and we will collaborate to fix these issues.

**Comment by cortinico** [comment] 2023-05-17 17:13
> Does the React Native team still prioritize performance? Performance has always been a key selling point of RN, but it seems to have taken a backseat lately when it comes to addressing regressions. It would be reassuring if someone in the thread could confirm that this issue will be addressed in the near future.

Nicola here from the React Native core team.

To bring clarity to this issue: we're currently investigating this and other regression that gets reported by users on the repository. We're doing that on a regular basis (the Samsung ANR investigation and fix was one of those instance)>

As you can see by the number of open issue, we can't fix all the bugs. 

Therefore we try to prioritize the one that are affecting the biggest group of users. This is one of them, as @kelset mentioned other users reported this or similar same issue (https://github.com/facebook/react-native/issues/36296 and https://github.com/facebook/react-native/issues/36123).

I don't have an ETA at this stage, but I'm happy to update as soon as we have more concrete results at hand.

In the meantime, we're more than happy to collaborate with member of the community in investigating this issue and try to understand where the regression comes from.

**Comment by shohelahamad** [comment] 2024-01-09 11:41
Any solutions!! Still having the issue with version 0.72.7. Especially with Android even a simple rendering is taking too long to load.
