### ISSUE TITLE
Picker children do not accept {false}

### ISSUE THREAD

**Issue by windhamwong** [facebook/react-native#13317] opened 2017-04-05 11:18 UTC
**Problem:**
When I try to implement dynamic item in `<Picker>`, the app returns

> Cannot read property 'props' of null

I did some quick test (actually not quick to spot the issue...), it seems to be an issue when the `children` is `false`. This might be related to #12829

**Prove of Concept (PoC):**

I use `{false}` here to represent no data in the dynamic variable.

`<View>{false}<View>`

View is working fine with `false` here.

`<Picker>{false}<Pick>`

But picker do not allow you to put `false `here. You can put `null` here instead.

**Comment by hramos** [comment] 2017-04-06 00:35
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-04-06 00:35 UTC
