### ISSUE TITLE
[Text][Android] weird line break

### ISSUE THREAD

**Issue by smartdevth** [facebook/react-native#14493] opened 2017-06-13 16:36 UTC
`<Text></Text>` on Android line break is acting weird but on iOS is fine, for example:
`longsomethingname (code:20016998)`

on iOS it will break like this:
**longsomethingname (code:
 20016998)**

But on Android:
**longsomethingname 
(code:20016998)**

It looks like that android line break is counting on breaking-space but not on iOS.

### Additional Information
* React Native version: 0.43
* Platform: Android

**Comment by hramos** [comment] 2017-06-13 16:45
Hey, thanks for reporting this issue! It looks like you're not using the latest stable release.

Your description is also missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-13 16:45 UTC
