### ISSUE TITLE
APK size got increased almost double after upgrading to RN 0.66.0

### ISSUE THREAD

**Issue by ursnj** [facebook/react-native#32463] opened 2021-10-22 18:00 UTC
### Description

APK Size got increased almost double after upgrading to React Native 0.66.0

OLD APK Size: 18Mb
NEW APK Size: 41Mb

### Version

0.66.0

### Output of `react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 33.75 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 7.16.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK: Not Found
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29, 30
      Build Tools: 23.0.1, 25.0.3, 26.0.1, 28.0.2, 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-26 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_201 - /usr/bin/javac
    Python: 3.8.5 - /Users/nj/opt/anaconda3/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.0 => 0.66.0 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Upgrade to react native latest version

Build APK.

### Snack, code example, screenshot, or link to a repository

![Screenshot 2021-10-22 at 11 25 43 PM](https://user-images.githubusercontent.com/28749151/138501662-b54bc45d-04d3-4cad-b92d-625a9b996f69.png)

**Comment by cortinico** [comment] 2021-11-09 14:17
What's your `minSdkVersion`? By any chance have you bumped from 21 to 23?

**Comment by Smiche** [comment] 2021-11-09 14:26
minSdkVersion 24 and have not changed it while upgrading react-native.

**Comment by shubhamdeol** [comment] 2021-11-11 07:40
I am also facing similar issue. App size on Playstore increased from 12 mb to 25 mb.

**Comment by shubhamdeol** [comment] 2021-11-12 03:20
@cortinico can it be due to all libraries staring to support api 30 from 29 ?

**Comment by cortinico** [comment] 2021-11-12 08:24
So what could have happened is that in your bump, the minSdk version got moved from 21 to 23 (or above).
The change could have been imposed by one of the transitive dependency in your project.

React Native is specifying minSdkVersion 21, but if any of your library or your project is specifying a higher number, that will prevail.

Specifically with api lvl 23, the native libraries are uncompressed in the APK, resulting in the an apparent bigger size of the APK (see here https://stackoverflow.com/a/63417612).

The best to investigate this is if someone could create a reproduce on Github, adding a base commit on RN 0.64 and a subsequent commit with the bump to 0.66. That would greatly help investigate what happened.

**Comment by anirudhagarwal1** [comment] 2022-01-05 18:11
To help better debug, attaching the screenshot of the diff in the size increase of libs. 

<img width="975" alt="Screenshot 2022-01-05 at 11 40 07 PM" src="https://user-images.githubusercontent.com/85726789/148267402-c24f27e8-de2b-4cfb-9a33-a2d2f18a8aa1.png">

**Comment by cortinico** [comment] 2022-01-06 15:17
> To help better debug, attaching the screenshot of the diff in the size increase of libs.
> 
> <img alt="Screenshot 2022-01-05 at 11 40 07 PM" width="975" src="https://user-images.githubusercontent.com/85726789/148267402-c24f27e8-de2b-4cfb-9a33-a2d2f18a8aa1.png">

From which version are you migrating from @anirudhagarwal1

**Comment by anirudhagarwal1** [comment] 2022-01-06 15:28
> > To help better debug, attaching the screenshot of the diff in the size increase of libs.
> > <img alt="Screenshot 2022-01-05 at 11 40 07 PM" width="975" src="https://user-images.githubusercontent.com/85726789/148267402-c24f27e8-de2b-4cfb-9a33-a2d2f18a8aa1.png">
> 
> From which version are you migrating from @anirudhagarwal1

I am upgrading from 0.63.4.

Also one more question. The above screenshot is of a release build, then why do I see some debug .so files(for ex: libhermes-executor-common-debug.so)? Is that expected?

**Comment by liamjones** [comment] 2022-01-06 15:53
This is also what we experienced upgrading from 0.63.4 to 0.66.3 too - about 6MB of new libs (including hermes/debug ones in non-Hermes release builds).

**Comment by cortinico** [comment] 2022-01-06 15:55
> The above screenshot is of a release build, then why do I see some debug .so files(for ex: libhermes-executor-common-debug.so)? Is that expected?

Nope is not. The `react.gradle` script has a specific section for removing the .so that are not relevant to your build. Specifically:

https://github.com/facebook/react-native/blob/a03bd2f13ed9d20f4c82ae1e73a4afa281fe2e9a/react.gradle#L360-L379

The best would be to try on an empty project on RN 0.66.0 and verify if it's working correctly or not.

**Comment by liamjones** [comment] 2022-01-06 16:38
Yep, doesn't look like it's working:

```
 ~/code  npx react-native init RNReleaseTest                                                                                                                                                                                                                    ∞
Need to install the following packages:
  react-native
Ok to proceed? (y) y
[snip]
 ~/code  cd RNReleaseTest                                                                                                                                                                                                                                           ∞
 ~/code/RNReleaseTest  cd android                                                                                                                                                                                                                                   ∞
 ~/code/RNReleaseTest/android  ./gradlew assembleRelease                                                                                                                                                                                                            ∞
Starting a Gradle Daemon (subsequent builds will be faster)
[snip]
BUILD SUCCESSFUL in 1m 6s
38 actionable tasks: 38 executed
 ~/code/RNReleaseTest/android  grep "enableHermes:" app/build.gradle                                                                                                                                                                                                ∞
    enableHermes: false,  // clean and rebuild if changing
 ~/code/RNReleaseTest/android  zip -sf app/build/outputs/apk/release/app-release.apk | grep libhermes                                                                                                                                                               ∞
  lib/arm64-v8a/libhermes-executor-common-debug.so
  lib/arm64-v8a/libhermes-executor-common-release.so
  lib/arm64-v8a/libhermes-executor-debug.so
  lib/arm64-v8a/libhermes-executor-release.so
  lib/arm64-v8a/libhermes-inspector.so
  lib/armeabi-v7a/libhermes-executor-common-debug.so
  lib/armeabi-v7a/libhermes-executor-common-release.so
  lib/armeabi-v7a/libhermes-executor-debug.so
  lib/armeabi-v7a/libhermes-executor-release.so
  lib/armeabi-v7a/libhermes-inspector.so
  lib/x86/libhermes-executor-common-debug.so
  lib/x86/libhermes-executor-common-release.so
  lib/x86/libhermes-executor-debug.so
  lib/x86/libhermes-executor-release.so
  lib/x86/libhermes-inspector.so
  lib/x86_64/libhermes-executor-common-debug.so
  lib/x86_64/libhermes-executor-common-release.so
  lib/x86_64/libhermes-executor-debug.so
  lib/x86_64/libhermes-executor-release.so
  lib/x86_64/libhermes-inspector.so
 ~/code/RNReleaseTest/android  zip -sf app/build/outputs/apk/release/app-release.apk | grep libjscexecutor                                                                                                                                                          ∞
  lib/arm64-v8a/libjscexecutor.so
  lib/armeabi-v7a/libjscexecutor.so
  lib/x86/libjscexecutor.so
  lib/x86_64/libjscexecutor.so
```

**Comment by anirudhagarwal1** [comment] 2022-01-06 20:28
@cortinico Do you need anything else from my end to help you debug the issue?

**Comment by cortinico** [comment] 2022-01-07 11:36
> @cortinico Do you need anything else from my end to help you debug the issue?

Nope thanks for the input. I was able to reproduce and the bug is effectively there on `0.66.0`. I've also tested on `0.67.0-rc.6` and the regression got already fixed.

From @liamjones command, running on 0.67:

```
$ zip -sf android/app/build/outputs/apk/release/app-release.apk | grep libhermes
  lib/arm64-v8a/libhermes-executor-common-release.so
  lib/arm64-v8a/libhermes-executor-release.so
  lib/arm64-v8a/libhermes.so
  lib/armeabi-v7a/libhermes-executor-common-release.so
  lib/armeabi-v7a/libhermes-executor-release.so
  lib/armeabi-v7a/libhermes.so
  lib/x86/libhermes-executor-common-release.so
  lib/x86/libhermes-executor-release.so
  lib/x86/libhermes.so
  lib/x86_64/libhermes-executor-common-release.so
  lib/x86_64/libhermes-executor-release.so
  lib/x86_64/libhermes.so
```

The fix is most likely this https://github.com/facebook/react-native/pull/32257 which haven't been included in 0.66.0. Given that 0.67 is really close to be released, I think we should be good to go with that.

Should there be blockers for 0.67.0, we can consider backporting #32257 to a point release for 0.66.x

Closing as this was essentially resolved. Feel free to re-open or comment if needed 👍

**Closed by cortinico** 2022-01-07 11:36 UTC
Labels: Needs: Author Feedback, Needs: Repro, Shared with React Native Team

**Comment by ursnj** [comment] 2022-02-12 19:39
This issue not resolved in 0.67 also, im seeing same bundle size with newer version also.

**Comment by weihangChen** [comment] 2022-02-15 08:53
after upgrading from 0.66 to 0.67 it went down for 30MB, but there is still a 40MB up compared to previous version

**Comment by mokshmodi96** [comment] 2022-06-06 06:46
I bumped my minSdkVersion to 23 from 21 and apk size doubled but i found a workaround-ish on stackoverflow linked below [](https://stackoverflow.com/a/68219448/8526633)
