### ISSUE TITLE
Print: Entry, ":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by stief510** [facebook/react-native#7786] opened 2016-05-26 17:56 UTC
I am running `react-native run-ios` and this is the error I am getting. Doing `sudo` beforehand does not fix the problem. Same with setting the permissions on the folder.

```
=== BUILD TARGET mobileTests OF PROJECT mobile WITH CONFIGURATION Release ===

Check dependencies

** BUILD SUCCEEDED **

Installing build/Build/Products/Debug-iphonesimulator/mobile.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
/Users/astiefel/workspace/bosspayments/mobile/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/mobile.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:470:13)
    at Object.execFileSync (child_process.js:490:13)
    at _runIOS (runIOS.js:91:34)
    at runIOS.js:24:5
    at tryCallTwo (/Users/astiefel/workspace/bosspayments/mobile/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/astiefel/workspace/bosspayments/mobile/node_modules/promise/lib/core.js:200:13)
    at new Promise (/Users/astiefel/workspace/bosspayments/mobile/node_modules/promise/lib/core.js:66:3)
    at Array.runIOS (runIOS.js:23:10)
    at Object.run (/Users/astiefel/workspace/bosspayments/mobile/node_modules/react-native/local-cli/cli.js:86:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:88:7)
```

**Comment by ms88privat** [comment] 2016-05-26 19:39
have a look at this, maybe there is a solution for you
https://github.com/facebook/react-native/issues/7308

**Comment by stief510** [comment] 2016-05-26 19:42
@ms88privat Those solutions there haven't helped. I tried them

**Comment by rjain15** [comment] 2016-05-28 02:41
Same here, doesn't work with the same error message. Node 6.2.0

**Comment by rjain15** [comment] 2016-05-28 03:29
Worked after upgrading XCode to 7.3.1

**Comment by gvlamadrid** [comment] 2016-06-26 23:50
Strange.
If your run 
/usr/libexec/PlistBuddy -c Print:CFBundleIdentifier ios/build/Build/Products/Debug-iphonesimulator/AwesomeProject.app/Info.plist
>  Print: Entry, ":CFBundleIdentifier", Does Not Exist

But if you run 
/usr/libexec/PlistBuddy -c Print:CFBundleIdentifier ios/build/Products/Debug-iphonesimulator/AwesomeProject.app/Info.plist 
(one build on path)
> org.reactjs.native.example.AwesomeProject

Is not exist /build/Build on my AwesomeProject IOS. 
Any help?
Txs!

node v6.2.2
react-native-cli: 1.0.0
react-native: 0.29.0-rc.0
xcode 7.3.1
OSX 10.11.4

**Comment by gvlamadrid** [comment] 2016-06-27 01:46
I fixed with https://github.com/facebook/react-native/issues/7308#issuecomment-228638046

**Comment by nimzco** [comment] 2016-07-15 09:04
I fixed it with https://github.com/facebook/react-native/issues/7308#issuecomment-219597774

**Comment by mkonicek** [comment] 2016-10-27 22:15
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/print-entry-cfbundleidentifier-does-not-exist

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Closed by mkonicek** 2016-10-27 22:15 UTC
Labels: Icebox

**Comment by abuammar** [comment] 2016-11-09 16:04
i tried all the above solutions nothing worked 

The following build commands failed:
	CompileC /Users/ws1/Library/Developer/Xcode/DerivedData/build/Build/Intermediates/WS1.com.build/Debug-iphonesimulator/WS1.comTests.build/Objects-normal/x86_64/WS1.comTests.o WS1.comTests/WS1.comTests.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Installing build/Build/Products/Debug-iphonesimulator/WS1.com.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/WS1.com.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by darrenchiu** [comment] 2017-03-30 03:36
+1 same error as @abuammar

**Comment by OscarGodson** [comment] 2017-04-28 19:51
Yea same error. Ive upgraded everything I can think of from my OS to XCode. I'm not on the latest macOS and XCode. Same error as everyone else

**Comment by samchanye** [comment] 2017-05-10 09:17
i tried all the above solutions nothing worked too, so sad

**Comment by florismettey** [comment] 2017-06-13 14:00
I had the error:

> Failed to install the requested application
> An application bundle was not found at the provided path.
> Provide a valid path to the desired application bundle.
> Print: Entry, ":CFBundleIdentifier", Does Not Exist

I found the issue: do NOT use space in your project path!

**Comment by huynhquocthai** [comment] 2017-06-30 08:09
Xcode 8.2 still same error. Three lines bellow fixed it for me :)
Downgrade react(16.0.0-alpha.12 -> 16.0.0-alpha.6) & react-native(0.45.0 -> 0.44.0)
rm -rf node_modules/react
npm i react@16.0.0-alpha.6 -S
npm i react-native@0.44.0 -S
Then run react-native run-ios

**Comment by samchanye** [comment] 2017-07-01 01:36
@huynhquocthai  thx😁

**Comment by aliv1** [comment] 2017-07-06 20:43
@huynhquocthai u da man! Thx!

**Comment by Gargam** [comment] 2017-07-10 08:19
As @florismettey said, I was using a space in my product name.
To fix it without affecting the Display name (bellow the app):

Open your project and select your target.
Go to Build Settings, search "product name" and remove any space in it.

It should work after that.

**Comment by youmyyou** [comment] 2017-08-03 07:02
Just open your Xcode

**Comment by hramos** [comment] 2017-08-04 06:57
Duplicate of #14423

**Comment by amerdiglisic** [comment] 2017-08-04 18:03
After I have spent a whole day trying to follow every possible suggestion, I took a detailed look on my terminal finally ! :)

So here is what was my problem:

Above **:CFBundleIdentifier", Does Not Exist** error i had another one  that stated that **lRCTBEEPickerManager module was not able to install**, so I open my **Xcode project => Build phases= > Link Binary with Libraries**

I removed the stated module (lRCTBEEPickerManager) and error was gone.

Hope this will help someone.
