### ISSUE TITLE
TextInput with ScrollView, touch events not firing

### ISSUE THREAD

**Issue by ErkanSen14** [facebook/react-native#7488] opened 2016-05-10 16:03 UTC
Hey there, I'm having an issue where after I input something into a TextInput, I have to press twice to press something else

The hierarchy for my code is 
```   
     <View>
        <ScrollView>
             <View>
                  <View>
                        <TextInput>
```

I have buttons in the same View as the TextInput, and I cannot click on any of them without first hiding the keyboard
I've seen the other closed issue, however that does not solve the issue.

**Comment by damusnet** [comment] 2016-05-10 16:14
Hi @ErkanSen14, how is your issue different from #4087?

**Comment by ErkanSen14** [comment] 2016-05-10 16:22
I only saw the other closed solution and not this one; marcshilling and hufeng's solutions solve it for me. Thank you!

**Comment by damusnet** [comment] 2016-05-10 16:36
@facebook-github-bot duplicate #4087

**Comment by facebook-github-bot-2** [comment] 2016-05-10 16:37
@damusnet tells me this issue is a duplicate of #4087. Let's discuss there, closing this one.

**Closed by facebook-github-bot-2** 2016-05-10 16:37 UTC
Labels: Ran Commands
