### ISSUE TITLE
NavigatorIOS crash while navigating between components

### ISSUE THREAD

**Issue by nigelmanson** [facebook/react-native#1236] opened 2015-05-11 16:39 UTC
Hi guys,

Really liking the hard work and thought going into React Native and thought i'd share any bugs I find while testing.

This happened while navigating between components using NavigatorIOS. Not really much more to say... 

return UIApplicationMain(argc, argv, nil, NSStringFromClass([AppDelegate class]));

react-native/React/Views/RCTNavigator.m:387
2015-05-11 17:32:45.555 fitnessApp[1884:73204] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Cannot change subviews from JS without first locking.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010e9b2c65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010de24bb7 objc_exception_throw + 45
	2   CoreFoundation                      0x000000010e9b2aca +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x000000010da39a57 -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 169
	4   fitnessApp                          0x000000010d69e06c -[RCTNavigator insertReactSubview:atIndex:] + 684
	5   fitnessApp                          0x000000010d6b6bff -[RCTUIManager _manageChildren:moveFromIndices:moveToIndices:addChildReactTags:addAtIndices:removeAtIndices:registry:] + 2703
	6   fitnessApp                          0x000000010d6b5f79 __108-[RCTUIManager manageChildren:moveFromIndices:moveToIndices:addChildReactTags:addAtIndices:removeAtIndices:]_block_invoke + 153
	7   fitnessApp                          0x000000010d6b03a3 __27-[RCTUIManager addUIBlock:]_block_invoke + 131
	8   fitnessApp                          0x000000010d6b92a0 __29-[RCTUIManager flushUIBlocks]_block_invoke + 352
	9   libdispatch.dylib                   0x00000001117dc186 _dispatch_call_block_and_release + 12
	10  libdispatch.dylib                   0x00000001117fb614 _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x00000001117e3a1c _dispatch_main_queue_callback_4CF + 1664
	12  CoreFoundation                      0x000000010e91a1f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	13  CoreFoundation                      0x000000010e8dbdcb __CFRunLoopRun + 2043
	14  CoreFoundation                      0x000000010e8db366 CFRunLoopRunSpecific + 470
	15  GraphicsServices                    0x000000011250ca3e GSEventRunModal + 161
	16  UIKit                               0x0000000110413900 UIApplicationMain + 1282
	17  fitnessApp                          0x000000010d629c3f main + 111
	18  libdyld.dylib                       0x000000011182f145 start + 1
	19  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by pwmckenna** [comment] 2015-05-11 17:45
which navigation caused this? push/pop/replace/etc?

**Comment by pwmckenna** [comment] 2015-05-11 17:51
There are some less disastrous issues with NavigatorIOS that I believe are tied to the locking (or lack thereof) of several functions. I'm going to try to address this issue: https://github.com/facebook/react-native/issues/476#issuecomment-99501667. if you can repro your issue I'd love to see if it is solved by the same thing.

**Comment by jaredly** [comment] 2015-05-20 20:55
Yeah replace & friends (that modify the stack in-place) are fairly broken at the moment :/ but I'm looking into fixing them.

Let me know if you can reproduce this, preferably by modifying the UIExplorer example in `Examples/UIExplorer/Navigator`

**Comment by brentvatne** [comment] 2015-05-29 21:39
Closing because no follow-up about reproducing.

**Closed by brentvatne** 2015-05-29 21:39 UTC
