### ISSUE TITLE
[0.66.1] Can't make an android build 

### ISSUE THREAD

**Issue by realtril** [facebook/react-native#32460] opened 2021-10-22 14:07 UTC
### Description

This is what I'm getting after running `npm run android`

<img width="1391" alt="Screen Shot 2021-10-22 at 4 54 54 PM" src="https://user-images.githubusercontent.com/53015418/138466317-7360f3d1-6eca-44bb-b662-923f388a6bd8.png">
<img width="1390" alt="Screen Shot 2021-10-22 at 4 55 03 PM" src="https://user-images.githubusercontent.com/53015418/138466334-6c88976f-2ea6-49c6-8b70-5b4ec9adf541.png">

I have managed to update a react native almost without any issues. Builds were fine, but now for some having these kind of issues.

this is what i have in package json
```
  {name:'xxx',
"scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "reset": "rm -rf node_modules/ && npm install && rm -rf ios/Pods ios/Podfile.lock && cd ios/ && pod install && cd ..",
    "cc-start": "npx react-native start --reset-cache",
    "jest": "node_modules/.bin/jest",
    "lint": "eslint --fix --ext .js,.jsx .",
    "prestart": "node ./scripts"
  },
  "dependencies": {
    "@expo/vector-icons": "^10.0.0",
    "@react-native-community/cli-platform-ios": "^4.13.0",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/netinfo": "5.9.6",
    "@react-navigation/bottom-tabs": "5.2.5",
    "@react-navigation/native": "5.4.0",
    "@react-navigation/stack": "5.2.10",
    "autobind-decorator": "2.1.0",
    "axios": "^0.23.0",
    "create-react-class": "15.6.3",
    "crypto-js": "3.1.9-1",
    "expo": "^39.0.5",
    "expo-asset": "^8.3.3",
    "expo-blur": "^9.0.3",
    "expo-constants": "^11.0.1",
    "expo-font": "^9.2.1",
    "expo-local-authentication": "^11.1.1",
    "expo-permissions": "^12.1.1",
    "expo-secure-store": "^10.2.0",
    "expo-web-browser": "^9.2.0",
    "finalhandler": "^1.1.2",
    "i18n-js": "3.3.0",
    "install": "^0.13.0",
    "js-base64": "2.5.1",
    "jsencrypt": "3.0.0-rc.1",
    "jwt-decode": "^2.2.0",
    "lodash": "^4.17.20",
    "moment": "2.23.0",
    "native-base": "2.15.2",
    "npm-force-resolutions": "0.0.10",
    "prop-types": "15.6.2",
    "qs": "^6.9.4",
    "react": "^17.0.2",
    "react-native-animatable": "^1.3.3",
    "react-native-appearance": "~0.3.3",
    "react-native-draggable-flatlist": "2.3.2",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-iphone-x-helper": "1.2.0",
    "react-native-localize": "1.3.1",
    "react-native-reanimated": "~1.13.0",
    "react-native-safe-area-context": "3.1.4",
    "react-native-screens": "~2.10.1",
    "react-native-splash-screen": "3.2.0",
    "react-native-svg": "12.1.0",
    "react-native-svg-charts": "5.2.0",
    "react-redux": "^7.2.2",
    "redux": "4.0.1",
    "redux-thunk": "2.3.0",
    "reset": "^0.1.0",
    "ucs-core": "git+ssh://git@bitbucket-eng-sjc1.cisco.com:7999/ucu/ucs-core.git#master",
    "utils-merge": "^1.0.1",
    "uuid": "3.3.2",
    "whatwg-fetch": "2.0.4"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/plugin-proposal-decorators": "7.0.0",
    "@babel/plugin-transform-react-jsx-source": "7.5.0",
    "@babel/preset-flow": "7.0.0",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@wdio/appium-service": "5.11.0",
    "@wdio/cli": "5.11.0",
    "@wdio/dot-reporter": "5.12.1",
    "@wdio/local-runner": "5.11.0",
    "@wdio/mocha-framework": "5.11.0",
    "@wdio/sync": "5.12.1",
    "appium": "1.14.0",
    "babel-eslint": "^10.1.0",
    "babel-jest": "^26.6.3",
    "babel-plugin-module-resolver": "^4.0.0",
    "babel-plugin-transform-decorators-legacy": "1.3.5",
    "babel-preset-expo": "^8.3.0",
    "chai": "4.2.0",
    "chai-webdriverio": "1.0.0",
    "concurrently": "4.1.0",
    "enzyme": "3.11.0",
    "enzyme-adapter-react-16": "^1.15.2",
    "eslint": "^7.14.0",
    "eslint-config-airbnb": "^18.1.0",
    "eslint-import-resolver-babel-module": "^5.1.2",
    "eslint-plugin-import": "^2.21.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.19.0",
    "fs-extra": "^8.0.1",
    "jest": "^26.6.3",
    "jetifier": "1.6.5",
    "metro-react-native-babel-preset": "^0.66.2",
    "mocha": "^6.1.4",
    "onchange": "^5.2.0",
    "react-native": "^0.66.1",
    "react-native-console-time-polyfill": "1.0.0",
    "react-native-unimodules": "^0.14.8",
    "react-test-renderer": "^17.0.2",
    "redux-immutable-state-invariant": "2.1.0",
    "webdriverio": "5.11.0"
  },
  "resolutions": {
    "node-fetch": "2.6.2",
    "css-what": "5.0.1",
    "connect": "3.7.0",
    "expo-asset": "^8.2.2",
    "xmldom": "@xmldom/xmldom@0.7.4"
  },
  "jest": {
    "preset": "react-native",
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?(@react-native|react-native)|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|sentry-expo|native-base)"
    ],
    "setupFiles": [
      "<rootDir>/jest/jestSetup.js"
    ],
    "collectCoverage": true,
    "collectCoverageFrom": [
      "**/*.{js,jsx}",
      "!**/coverage/**",
      "!**/node_modules/**",
      "!**/babel.config.js",
      "!**/jest/jestSetup.js",
      "!**/test/**"
    ]
  },
  "private": true
}
```

this is android manifest 
```
<manifest package="xxx" xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools">

    <supports-screens
      android:largeScreens="true"
      android:normalScreens="true"
      android:smallScreens="false"
      android:xlargeScreens="false"
      tools:replace="android:smallScreens, android:xlargeScreens"
    />

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.USE_FINGERPRINT" />
    <uses-permission android:name="android.permission.VIBRATE" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme"
      android:usesCleartextTraffic="true">
      <activity
        android:name=".MainActivity"
        android:launchMode="singleTask"
        android:label="@string/app_name"
        android:screenOrientation="portrait"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:windowSoftInputMode="adjustResize"
        >
        <intent-filter>
            <action android:name="android.intent.action.VIEW"/>
            <category android:name="android.intent.category.DEFAULT"/>
            <category android:name="android.intent.category.BROWSABLE"/>
            <data
              android:scheme="exp9b966dcb1eab481a9964dfa5d29daf65"
              android:host="xxx"/>
        </intent-filter>
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
    </application>

</manifest>
```

this  is android/gradle
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        supportLibVersion = "29.0.0"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenCentral()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}
```

### Version

0.66.1

### Output of `react-native info`

<img width="1031" alt="Screen Shot 2021-10-22 at 4 59 33 PM" src="https://user-images.githubusercontent.com/53015418/138466933-a940d915-2ddb-4256-bd3a-f72b47cea71f.png">

### Steps to reproduce

npm start --reset-cache
npm run android

**Comment by cortinico** [comment] 2021-10-31 15:49
A couple of things from the error message:
* You have autolinking disabled. That might be one of the cause of this issue: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#platform-android
* The error message is telling you what to do to solve the issue: add a `tools:replace` to your manifest to fix this issue.

What is happening is that the Manifest merger is failign [as this attributed](https://github.com/expo/expo/blob/9cd697533d64cdee216c641b792fda7952d1afcf/packages/expo-modules-core/android/src/main/AndroidManifest.xml#L4-L8) is included twice. Once from the `expo-modules-core` and once from `unimodules-react-native-adapter`.

You should be fine by adding a:

```
<manifest>
    <application>
        ...
        <meta-data
            android:name="org.unimodules.core.AppLoader#react-native-headless"
            android:value="expo.modules.adapters.react.apploader.RNHeadlessAppLoader"
            tools:replace="android:value" />
    </application>
</manifest>
```
or removing one of the two package if you're not using it.

More on this here https://stackoverflow.com/a/31793227/3765748

Also for the future, please don't use images but copy paste your error message as it's making maintainers life harder :) Thank you

**Comment by malikhautumn** [comment] 2021-10-31 20:06
Facing same issue with Android after upgrading to react native version 0.66.1

**Comment by realtril** [comment] 2021-10-31 20:22
@malikhautumn yeah, I am good now. What is your expo version?

**Comment by malikhautumn** [comment] 2021-10-31 20:37
I am not using expo but cli @realtril . However how did you resolve your issue ?

**Comment by realtril** [comment] 2021-10-31 20:38
I could resolve my issue only after upgrade expo to 43v

**Comment by cortinico** [comment] 2021-11-01 17:26
> I could resolve my issue only after upgrade expo from 39 to 43 version, after that I could do fine rn upgrade

Closing as this is resolved

**Closed by cortinico** 2021-11-01 17:26 UTC
Labels: Platform: Android, Needs: Attention

**Comment by ratz6** [comment] 2021-11-25 06:43
@realtril @malikhautumn Any tricks on react-native-cli ?
