### ISSUE TITLE
 Unable to resolve module `prop-types`

### ISSUE THREAD

**Issue by chandanGr** [facebook/react-native#14360] opened 2017-06-07 10:31 UTC
error: bundling: UnableToResolveError: Unable to resolve module `prop-types` from `C:\Users\suhas\Documents\FacebookTest\node_modules\react-native-fbsdk\js\FBLikeView.js`: Module does not exist in the module map or in these directories:
  C:\Users\suhas\Documents\FacebookTest\node_modules
,   C:\Users\suhas\node_modules

**Comment by hramos** [comment] 2017-06-07 17:45
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-07 17:45 UTC
