### ISSUE TITLE
Cannot resolve method "setJSMainModuleName("index.android")" while creating ReactInstanceManager, which was working fine yesterday no change in code

### ISSUE THREAD

**Issue by ManishPatiyal** [facebook/react-native#19263] opened 2018-05-15 09:05 UTC
Today morning I build the code and started getting this issue when running the application. Also following method is giving error.
   @Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }  

I am using
implementation 'com.facebook.react:react-native:+'

**Comment by kelset** [comment] 2018-05-15 09:15
Probably a duplicate of https://github.com/facebook/react-native/issues/19259, I'll close this until new details show otherwise.

**Closed by kelset** 2018-05-15 09:15 UTC
Labels: :clipboard:No Template, :large_blue_diamond:Android

**Comment by ManishPatiyal** [comment] 2018-05-15 11:19
This commit breaks code at my end. Please suggest what need to be done on my end.
Breaking - remove unused registration of JS modules

Summary: It's now unnecessary to declare which JS modules you want to expose on your package. To upgrade, remove all overrides of `createJSModules` and keeping calling your JS modules as before.

Reviewed By: AaaChiuuu

Differential Revision: D5229259

fbshipit-source-id: 1160826c951433722f1fe0421c1200883ba1a348

**Comment by joshuapinter** [comment] 2018-05-15 16:05
@ManishPatiyal You'll have to adjust your React Native dependency to be: 

```
compile ("com.facebook.react:react-native:0.52.0") { force = true }
```

_(Replacing `0.52.0` with the react native version that is in your `package.json` file.)_

See https://stackoverflow.com/a/50354510/293280 as well.
