### ISSUE TITLE
Build failed, cannot find CFBundleIdentifier

### ISSUE THREAD

**Issue by tyhopp** [facebook/react-native#14740] opened 2017-06-27 08:43 UTC
I ran into an error loading my React Native app - the build failed because it did not find the CFBundleIdentifier. I tried both project initialization processes (create-react-native-app & react-native init MyProj), and this error occurs ultimately in both. 

I went through all the proposed solutions in #7308 but I still cannot find a solution. Please help!

**Specifics:**
macOS Sierra, Version 10.12.5
node v8.1.2
npm v5.0.3
yarn v0.24.6
react-native-cli v2.0.1
react-native v0.45.1
react v16.0.0-alpha.13
watchman v4.7.0

**Tried alternates:**

node v6.11.0
npm v3.10.10

With these versions, the create-react-native-app initialization process succeeded where it didn't above, but ultimately still resulted in the “CFBundleIdentifier” does not exist bug.

——————————————————

**Bug**

React native app will not open in iOS simulator upon calling "react-native run-ios" from the CLI or from within Xcode. 

**Returned issue:** 

```
** BUILD FAILED **


The following build commands failed:

	PhaseScriptExecution Install\ Third\ Party /Users/tyhopp/Dropbox/flyright/frontend/Flyright/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/double-conversion.build/Script-190EE32F1E6A43DE00A8543A.sh
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/Flyright.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/Flyright.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

```

**Comment by devSC** [comment] 2017-06-27 09:15
+1

**Comment by hramos** [comment] 2017-06-27 16:04
Duplicate of #14461, there's already several issues about this so let's avoid opening new ones.

**Closed by hramos** 2017-06-27 16:04 UTC

**Comment by dongsx** [comment] 2017-07-16 08:33
+1

**Comment by tyhopp** [comment] 2017-07-17 00:49
I ended up reverting back to React Native v0.43 and Xcode + CLI tools v8.3.2 and it works for me now. Must be something to do with the particular React v0.45 and Xcode v8.3.3 builds working together. Haven't tried the new React Native v0.46 though. 

Wrote a [set of bash scripts](https://github.com/tyhopp/rn-local) to help setup if it can help!

**Comment by hramos** [comment] 2017-08-04 06:47
Duplicate of #14423
