### ISSUE TITLE
Vertical align is wrong when text includes english and chinese

### ISSUE THREAD

**Issue by musicode** [facebook/react-native#21357] opened 2018-09-27 04:56 UTC
## Environment

 [skip envinfo]

ios: IOS
react native: 0.57.0

## Description

when text includes english and chinese, vertical align is wrong

![image](https://user-images.githubusercontent.com/2732303/46124096-9bb26000-c254-11e8-9efc-5c79cb829ea3.png)

## Reproducible Demo

```
<Text>
 中文 english 中文
</Text>
```

**Comment by ikesyo** [comment] 2018-09-27 10:58
Is this a duplicate of #19193?

**Closed** 2018-10-05 00:05 UTC
Labels: :clipboard:No Environment Info, :large_orange_diamond:Components, Ran Commands
