### ISSUE TITLE
npx react-native init AwesomeProject fails

### ISSUE THREAD

**Issue by princefishthrower** [facebook/react-native#34968] opened 2022-10-13 11:06 UTC
### Description

As the title states, I can't issue `npx react-native init AwesomeProject`, here's my console output:

```shell
npx react-native init AwesomeProject


Need to install the following packages:
  react-native@0.70.3
Ok to proceed? (y) y
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react-native@0.68.2
npm ERR! node_modules/react-native
npm ERR!   peer react-native@"*" from @react-native-community/cli@7.0.3
npm ERR!   node_modules/@react-native-community/cli
npm ERR!     @react-native-community/cli@"^7.0.3" from react-native@0.68.2
npm ERR!   react-native@"0.70.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! react-native@"0.70.3" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@18.1.0
npm ERR! node_modules/react
npm ERR!   peer react@"18.1.0" from react-native@0.70.3
npm ERR!   node_modules/react-native
npm ERR!     react-native@"0.70.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/chris/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chris/.npm/_logs/2022-10-13T11_03_12_994Z-debug-0.log
```

### Version

70.3

### Output of `npx react-native info`

Can't even issue this one either:

```shell
npx react-native info
Need to install the following packages:
  react-native@0.70.3
Ok to proceed? (y) y
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react-native@0.68.2
npm ERR! node_modules/react-native
npm ERR!   peer react-native@"*" from @react-native-community/cli@7.0.3
npm ERR!   node_modules/@react-native-community/cli
npm ERR!     @react-native-community/cli@"^7.0.3" from react-native@0.68.2
npm ERR!   react-native@"0.70.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! react-native@"0.70.3" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@18.1.0
npm ERR! node_modules/react
npm ERR!   peer react@"18.1.0" from react-native@0.70.3
npm ERR!   node_modules/react-native
npm ERR!     react-native@"0.70.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/chris/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chris/.npm/_logs/2022-10-13T11_03_39_253Z-debug-0.log
```

### Steps to reproduce

1. Issue `npx react-native info` or `npx react-native init AwesomeProject` in a terminal

### Snack, code example, screenshot, or link to a repository

Not applicable to a snack since it s a CLI tool, so here's the screenshot of my terminal output:

<img width="632" alt="Screen Shot 2022-10-13 at 13 04 43" src="https://user-images.githubusercontent.com/11366744/195580671-f6c98231-c430-4739-b38a-c77fd40eeb24.png">

**Comment by josephk96** [comment] 2022-10-13 16:27
Hi @princefishthrower , I ran into a similar issue just a few hours ago. Can you try the following and see if it works?

`npm uninstall -g react-native-cli && npm install -g react-native-cli && npm install -g react-native && npx react-native init AwesomeProject`

I found this SO thread - https://stackoverflow.com/questions/72768245/typeerror-cli-init-is-not-a-function-for-react-native and it worked for me

**Comment by cortinico** [comment] 2022-10-14 19:09
This is a duplicate of https://github.com/facebook/react-native/issues/34051 which is already solved

**Closed by cortinico** 2022-10-14 19:09 UTC
Labels: Needs: Triage :mag:
