### ISSUE TITLE
React native run-android not working because of incorrect sdk path

### ISSUE THREAD

**Issue by saurabhvyas** [facebook/react-native#8547] opened 2016-07-03 21:15 UTC
- [ ] Provide a **minimal code snippet** / [rnplay](https://rnplay.org/) example that reproduces the bug.
- [ ] Provide **screenshots** where appropriate

![image](https://cloud.githubusercontent.com/assets/6899784/16547594/5815244a-4191-11e6-9e9e-0fbef566566a.png)

Building and installing the app on the device (cd android && gradlew.bat installDebug...
Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.
java.lang.RuntimeException: The SDK directory 'C:\react-native\myproj\android\C:UserssaurabhorangeAppDataLocalAndroidsdk' does not exist.

you can observed the path is definitely incorrect , I dont know why its using relative path when I specified absolute path in properties file
- [ ] What's the **version** of React Native you're using?
  0.28
- [ ] Does this occur on iOS, Android or both?
  Android, havnt tried IOS
- [ ] Are you using Mac, Linux or Windows?
  Windows 10 64 bit

**Comment by satya164** [comment] 2016-07-03 21:20
Can you share what you've set in your `local.properties`?

**Comment by saurabhvyas** [comment] 2016-07-04 01:22
sdk.dir = C:\Users\saurabhorange\AppData\Local\Android\sdk

**Comment by mixophrygian** [comment] 2016-07-23 17:00
Try opening Android Studio and setting the path of my SDK to Android/sdk (I had to create both folders).  That changed the build fail error to: `failed to find target with hash string 'android-23' in /Users/mixophrygian/Library/Android/sdk`

So in Android Studio -> Preferences -> System Settings -> Android SDK -> Launch Standalone SDK Manager, install Android 6.0 (API 23).  Don't forget to install the build tools, as well.

**Comment by saurabhvyas** [comment] 2016-07-23 18:08
Tried that , It still cannot identify sdk :(,

**Comment by lenichols** [comment] 2016-07-24 23:27
+1 because im having the same issue... tried everything but it will not read the SDK location.

**Comment by Razzeee** [comment] 2016-08-31 23:06
Try `sdk.dir = C:\\Users\\USERNAME\\AppData\\Local\\Android\\sdk` if your on windows

**Comment by lacker** [comment] 2016-11-30 00:23
I think this has been stuck in "needs more information" for a while - perhaps the last comment even solves it - so I am going to close this issue. If you continue to have problems with a reproducible setup then feel free to open a new issue.

**Closed by lacker** 2016-11-30 00:23 UTC
Labels: Android, Needs more information

**Comment by mayurbaldha** [comment] 2017-05-18 06:53
I have SDK installed on D:\Tools\Android on windows machine
Trying sdk.dir = D:\Tools\Android,

but no luck.

**Comment by Razzeee** [comment] 2017-05-18 08:34
Try `\\` instead of `\`

**Comment by sesm** [comment] 2017-07-12 13:51
Try updating SDK path in `<PROJECT_DIR>/android/local.properites`

**Comment by faizantechizer** [comment] 2018-04-11 05:30
Razzeee's answer worked for me.

**Comment by mewanmadusha** [comment] 2018-07-08 21:31
https://i.stack.imgur.com/dAbCd.png

do this change sdk path to currnt using sdk version
