### ISSUE TITLE
TouchableOpacity in listview only shows first item

### ISSUE THREAD

**Issue by jackuhan** [facebook/react-native#12970] opened 2017-03-16 10:10 UTC
RN0.41
TouchableOpacity in listview only shows first item.
在listview中用TouchableOpacity，只显示第一行的item，后面的item不显示。
TouchableWithoutFeedback is ok.

` renderRow: function (item) {`
`    return <TouchableWithoutFeedback>`
`<View/>`
 `</TouchableOpacity>`

**Comment by hramos** [comment] 2017-03-16 18:19
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-03-16 18:19 UTC
