### ISSUE TITLE
'RCTWebSocketProxy.h' file not found

### ISSUE THREAD

**Issue by tingxinCY** [facebook/react-native#5980] opened 2016-02-17 14:05 UTC
there is a error when i run example.

react-native/React/Modules/RCTDevMenu.m:22:9: 'RCTWebSocketProxy.h' file not found

**Comment by satya164** [comment] 2016-02-18 00:03
Should be fixed in f9e81d9bccc2960be28e4583120dba28deab6276

**Comment by asmega** [comment] 2016-02-19 00:09
can confirm it was a bug and can confirm it is now fixed in master :)

**Comment by tingxinCY** [comment] 2016-02-19 03:02
The bug has been Fixed! 

Thank you very much！

**Comment by JakeRuth** [comment] 2016-03-12 16:41
Just used npm to download 0.22.0-rc and went to rebuild my xcode project and I am getting this error which is failing my build.  I looked at the commit referenced by @satya164  above and my RCTDevMenu.m file contains the change introduced in that commit.

**Comment by davidgruebl** [comment] 2016-03-15 23:34
experiencing the very same as @JakeRuth for both, 0.22.0-rc and also the current master

**Comment by Elyx0** [comment] 2016-03-18 19:42
Was the case for me too as of today with 0.22.0-rc

**Comment by alanzanattadev** [comment] 2016-03-19 17:29
Any workaround ?

**Comment by Elyx0** [comment] 2016-03-21 13:41
Made it work with latest npm / node without forgetting the `react-native upgrade`

**Comment by satya164** [comment] 2016-03-22 00:55
Closing since this seems to be fixed by `react-native upgrade`.

**Comment by lelandrichardson** [comment] 2016-03-23 21:18
@satya164 I am having this problem as well, and i'm on 0.22.2. I've confirmed I have the referenced commit as well. Any suggestions on where to go from here?

(reopening for now)

**Comment by lelandrichardson** [comment] 2016-03-23 21:29
Note: I'm not using `react-native upgrade` because we aren't using the app template here :/

**Comment by satya164** [comment] 2016-03-23 22:08
@lelandrichardson Does it happen in a brand new project?

**Comment by lelandrichardson** [comment] 2016-03-23 23:54
No. Apologies, this was an issue with my understanding of cocoapods, not react native :(  closing again.

**Closed by lelandrichardson** 2016-03-23 23:54 UTC

**Comment by aaronschachter** [comment] 2016-04-01 18:01
Also ran into this upon running `npm install --save react-native@0.22`

Builds work again after running a `pod install`:

![screen shot 2016-04-01 at 10 59 11 am](https://cloud.githubusercontent.com/assets/1236811/14215610/dbb330cc-f7f8-11e5-95bf-2eeb3ce924ac.png)

**Comment by nicholasstephan** [comment] 2017-09-12 18:39
I'm getting this with a brand new React Native app with react-native-firebase to build. Following the steps from:

    react-native init MyApp

then in the `ios` directory I `pod init` with the pod file:

    # Uncomment the next line to define a global platform for your project
    platform :ios, '9.0'

    target 'MyApp' do
      # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
      # use_frameworks!

      # Required by RNFirebase
      pod 'Firebase/Core'
      pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

      # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
      pod 'Firebase/Analytics'
      pod 'Firebase/Auth'
      pod 'Firebase/Database'
      pod 'Firebase/Messaging'

      pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
      pod 'React', :path => '../node_modules/react-native', :subspecs => [
        'BatchedBridge', # Required For React Native 0.45.0+
        'Core',
        # Add any other subspecs you want to use in your project
      ]

      target 'MyAppTests' do
        inherit! :search_paths
        # Pods for testing
      end

    end

    target 'MyApp-tvOS' do
      # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
      # use_frameworks!

      # Pods for MyApp-tvOS

      target 'MyApp-tvOSTests' do
        inherit! :search_paths
        # Pods for testing
      end

    end

After running `pod install`, opening `MyApp.xcworkspace`, and building gives me the error:

> /Users/nicholasstephan/code/MyApp/node_modules/react-native/React/Base/RCTTVRemoteHandler.m:25:9: 'RCTDevMenu.h' file not found

I'm using Xcode 8.3.3 and React Native 0.48.3.
