### ISSUE TITLE
Enable Hot Reloading - Requiring unknown module "./node_modules\react-transform-hmr\lib\index.js".

### ISSUE THREAD

**Issue by sengkin** [facebook/react-native#6954] opened 2016-04-13 10:31 UTC
Hi there,

I am trying to run the reactive native on my window machine.

When I enable the hot reloading, the Emulator will show an error message - Requiring unknown module "./node_modules\react-transform-hmr\lib\index.js".

And, please take note that index.js is available on "TestReact\node_modules\react-transform-hmr\lib" (note: TestReact is the project name)

Please find attached for the screenshot. Thanks!
![enablehotreloading](https://cloud.githubusercontent.com/assets/1788030/14490508/d59fab14-01a5-11e6-8d8d-9e1489672c21.png)
![rederror](https://cloud.githubusercontent.com/assets/1788030/14490509/d5c5297a-01a5-11e6-80e0-f6598bacaabd.png)
![thejsfile](https://cloud.githubusercontent.com/assets/1788030/14490510/d62f60ce-01a5-11e6-9045-284f029f9851.png)

**Comment by dsibiski** [comment] 2016-04-13 10:47
Looks like a problem with the slashes in the path.

/cc @martinbigio

**Comment by MobileAppVault** [comment] 2016-04-13 12:31
I have the same problem on windows. 

Is there a way to fix it?

**Comment by MobileAppVault** [comment] 2016-04-13 12:57
I've tried to implement these fix but the files and variable names seems to be changed

https://gist.github.com/davidgilbertson/9bee68548037fe00f2a8#fix-double-slash-issues-with-windows

```
function defineModuleCode(moduleName, code, verboseName = '') {
  verboseName = verboseName.replace(/\\\\/g,'\\');
  moduleName = moduleName.replace(/\\\\/g,'\\');
  return [
    `__d(`,
    `${JSON.stringify(moduleName)} /* ${verboseName} */, `,
    `function(global, require, module, exports) {`,
      `${code}`,
    '\n});',
  ].join('');
}
```

But this is not working...

**Comment by chanpod** [comment] 2016-04-13 14:13
I, also, am having this issue after upgrading to 0.23

**Comment by martinbigio** [comment] 2016-04-13 15:00
Yeah, the problem is the `./`. Is there an equivalent thing on windows? 

This is the line we'd need to change: https://github.com/facebook/react-native/blob/master/babel-preset/configs/hmr.js#L19

**Comment by MobileAppVault** [comment] 2016-04-13 16:36
Found this:

https://github.com/facebook/react-native/commit/c61100d0ceb4b71c86f01f35d7464d2d8a02b342#diff-9f63115ac33a0f474f9ea9ba9cab2fec

Will let you know if it works

**Comment by ide** [comment] 2016-04-13 18:18
That patch has been pulled into 0.24.0-rc5 (react-native@next). 0.24.0 will go out next Monday. Closing this out.

**Closed by ide** 2016-04-13 18:18 UTC
Labels: Windows

**Comment by martinbigio** [comment] 2016-04-14 00:37
@ide no need to pull it into the RC. The preset is a separate npm module. We need to publish it to npm :)

**Comment by ide** [comment] 2016-04-14 01:17
There were some changes to the packager in that commit, too. It was early in the RC window so I cherry picked the patch anyway and figured people would appreciate it.

**Comment by martinbigio** [comment] 2016-04-14 02:19
Oh right, didn't see them. Thanks for doing that!. We'd still need to release a new version of the preset.

**Comment by sengkin** [comment] 2016-04-14 02:41
@ide and @martinbigio thanks. please advise when will you publish to npm?

**Comment by malinthe** [comment] 2016-04-19 09:33
Is this on 0.24 now? Updated to 0.24 today but still seeing the issue.

**Comment by n9** [comment] 2016-04-19 13:55
@malinthe It should be in 0.24.0 (https://github.com/facebook/react-native/commit/d457a187666ec3211e8d17bf51c2b07d049cd5bf), but I am getting this error too:
![screenshot_2016-04-19-15-29-34-message](https://cloud.githubusercontent.com/assets/1651867/14640899/07d26ab6-0644-11e6-9f9f-170247bd8e9c.png)

It seems to me that the fix is also contained in [`babel-preset-react-native`](https://www.npmjs.com/package/babel-preset-react-native), which has not been released yet.

According to npm, the current version (1.5.6) was published by @martinbigio 3 weeks ago.

@ide When `babel-preset-react-native` will be released?
