### ISSUE TITLE
DrawerNavigator  No gesture

### ISSUE THREAD

**Issue by sunyardTime** [facebook/react-native#15521] opened 2017-08-17 01:29 UTC
when i use DrawerNavigator,i want No gesture to open or close.how can i use it?

**Comment by hramos** [comment] 2017-08-17 05:13
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-08-17 05:13 UTC
