### ISSUE TITLE
Rn debug error on Android  java.lang.NumberFormatException at BundleDeltaClient

### ISSUE THREAD

**Issue by AsiamCn** [facebook/react-native#22806] opened 2018-12-27 02:03 UTC
- [ 1] Review the documentation: https://facebook.github.io/react-native
  - [1 ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [1 ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.

  React Native Environment Info:
    System:
      OS: Windows 7
      CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
      Memory: 6.57 GB / 15.88 GB
    Binaries:
      Yarn: 1.10.1 - C:\Users\myname\AppData\Roaming\npm\yarn.CMD
      npm: 5.6.0 - D:\Program Files\nodejs\npm.CMD

## Description
Describe your issue in detail. Include screenshots if needed. If this is a regression, let us know.
I found there is a very big number (20771272033) in bundle,  it works well when I pass bundle to my mobile and load it normally.  But when I want to debug on my device, my app crashed.

Exception is :
```
 java.lang.NumberFormatException: 20771272033
        at android.util.JsonReader.nextInt(JsonReader.java:522)
        at com.facebook.react.devsupport.BundleDeltaClient.patchDelta(BundleDeltaClient.java:104)
        at com.facebook.react.devsupport.BundleDeltaClient.storeDeltaInFile(BundleDeltaClient.java:54)
        at com.facebook.react.devsupport.BundleDownloader.processBundleResult(BundleDownloader.java:281)
        at com.facebook.react.devsupport.BundleDownloader.access$200(BundleDownloader.java:35)
        at com.facebook.react.devsupport.BundleDownloader$1.onResponse(BundleDownloader.java:153)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```
I have found the number 20771272033 in my bundle:
![image](https://user-images.githubusercontent.com/10176630/50461931-ee6af780-09bc-11e9-8b7a-f09b92c722c8.png)

![image](https://user-images.githubusercontent.com/10176630/50461939-fe82d700-09bc-11e9-9f64-00abfc4ddbba.png)

also,  I found it parse this number as integer: 
https://github.com/facebook/react-native/blob/e81adb99f318582f5cd877e9c20614c1cec577ed/ReactAndroid/src/main/java/com/facebook/react/devsupport/BundleDeltaClient.java#L157

![image](https://user-images.githubusercontent.com/10176630/50462098-f8d9c100-09bd-11e9-84b2-549311a9221e.png)

Is this a bug or I generated my bundle in a wrong way? 

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, share a project, or     share an app that reproduces the issue using https://snack.expo.io/. Please follow the guidelines for providing a MCVE: https://stackoverflow.com/help/mcve

**Comment by bartolkaruza** [comment] 2018-12-29 10:12
Looks like a module id is generated outside of the Java int allowed range. Are you able to consistently reproduce this issue?

**Comment by AsiamCn** [comment] 2018-12-30 01:59
> Looks like a module id is generated outside of the Java int allowed range. Are you able to consistently reproduce this issue?

@bartolkaruza Yes, my app crashed every time when I want to debug. I also found a id outside of java int in my release bundle, but it works well in release mode.

**Comment by bartolkaruza** [comment] 2019-03-20 00:29
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗

**Closed by bartolkaruza** 2019-03-20 00:29 UTC
Labels: Platform: Android, Type: Bug Report, 📦Bundler
