### ISSUE TITLE
Fetch : talk about response.headers.map in the doc + iterator exception

### ISSUE THREAD

**Issue by Rewieer** [facebook/react-native#13450] opened 2017-04-11 18:13 UTC
I'm using Fetch in my project and i've come to realise that when using standard developer mode, I cannot use Iterator to loop through the entries of the Header object, but a "map" object is provided in the header. When i'm starting the JS Debugger with Chrome suddenly the entries iterator works. Maybe the fetch API relies on Chrome when Debugging and Native when it's not, but it's been weird to track the Iterator exception because my first feeling was that no matter the context (Chrome or Native) the fetch API is the same. 

The error I get when trying to make a for...of is : "**TypeError : undefined is not a function (evaluating '_iterator\[typeof Symbol === 'function' ? Symbol.iterator : '\@\@iterator']()')**.

**Comment by hramos** [comment] 2017-05-31 20:37
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-05-31 20:37 UTC
