### ISSUE TITLE
Changing the name of the iOS configuration prevents cmd + r and debug menu from working

### ISSUE THREAD

**Issue by chrisbianca** [facebook/react-native#6011] opened 2016-02-18 17:43 UTC
I've spent today setting up a number of different configurations for my RN 0.20.0 iOS project, and have noticed something strange.

When renaming the 'Debug' configuration to 'Local', or any other name for that matter,  I am no longer able to:

- Cmd + r to reload
- Cmd + shift + z to show the development menu

No other configuration settings have changed, and renaming 'Local' back to 'Debug' allows these commands to work correctly.

My assumption is that there's something in the iOS code looking at the configuration?  Though this would be surprising as I'd expect the DEBUG preprocessor to be what drives the debug code in RN?

**Comment by mkonicek** [comment] 2016-02-18 20:11
Hey @chrisbianca, I unfortunately don't know the answer to this one but have a meta question:

I've added the [Issue template](https://github.com/facebook/react-native/blob/master/ISSUE_TEMPLATE.md) and hoping it would make it clear it's best to ask on StackOverflow first before filing a bug on GitHub.

I'd like to ask: is that description clear enough? What did you think when you saw it? Was it too long for example?

**Comment by chrisbianca** [comment] 2016-02-18 20:36
Hi @mkonicek, I did see the issue template.  While it is quite long and not necessarily a template as GitHub probably intended it to be, I felt it was clear in the message it is trying to get across.

However, in this instance I elected to raise a bug on GitHub as having spent 2-3 hours trying to battle with this and identity the cause of the problem, I felt that this is a bug to be raised and not a question to be asked.  Sorry if that wasn't clear in my description of the problem.

Ultimately there is some hidden behaviour that is unexplained and does not work how it should do.  Asking this first on StackOverflow before ultimately having to raise a bug seems like an unnecessary step.

**Comment by mkonicek** [comment] 2016-02-18 21:53
Thank you very much for taking time to write the explanation @chrisbianca, this is very helpful!

When reloading using `Cmd + R`, do you see anything in the logs?

I suspect there is indeed something in Obj-C code that checks this. If you search for 'debug' in all Obj-C files, there are a few occurrences: https://github.com/facebook/react-native/search?l=objective-c&q=debug&type=Code&utf8=%E2%9C%93

Can you see which one would cause this? Can you put a breakpoint somewhere in the code and see why the dev menu is not being shown and why? I only know the Android codebase but did a quick search for "DevMenu" (purely guessing) in the Obj-C code and found: https://github.com/facebook/react-native/blob/f9e81d9bccc2960be28e4583120dba28deab6276/React/Modules/RCTDevMenu.m#L486

Can see if the right code is getting called and why?

**Comment by mkonicek** [comment] 2016-02-18 22:27
> Ultimately there is some hidden behaviour that is unexplained and does not work how it should do. Asking this first on StackOverflow before ultimately having to raise a bug seems like an unnecessary step.

Completely agree. Maybe I should change the wording to explain that asking on StackOverflow is in many cases sufficient. It might turn out what looks like a bug is an unsupported feature or expected behavior.

**Comment by chrisbianca** [comment] 2016-02-19 08:57
I popped a breakpoint in the code for DevMenu before both conditionals controlling the DevMenu functionality.  Neither are called when the configuration name is set to 'Local' but are called when the configuration name is set to 'Debug'.  It's almost as if the file isn't included at all when the configuration name is not 'Debug'.

It seems that the configuration name is case sensitive, so 'debug' and 'DEBUG' don't show the menu/debug options either.  Doing a case-sensitive search for 'Debug' only referenced the name of configurations in project.pbxproj and one conditional statement:

> shellScript = "if [[ \"$CONFIGURATION\" == \"Debug\" ]] && [[ -d \"/tmp/RCTJSCProfiler\" ]]; then\n   find \"${CONFIGURATION_BUILD_DIR}\" -name '*.app' | xargs -I{} sh -c 'cp -r /tmp/RCTJSCProfiler \"$1\"' -- {}\nfi";
> showEnvVarsInLog = 0;

I tried changing 'Debug' to 'Local' here but there was still no difference.

I have also manually added RCT_DEBUG=1, RCT_DEV=1 and RCT_NS_ASSERT=1 to the preprocessor macros without any luck.

Unfortunately my knowledge of iOS development is limited so I'm not sure where else to go beyond this.  It seems to me that the project is inheriting some behaviour reliant on the configuration being called 'Debug' but I'm out of ideas as to where else this could be coming from.

**Comment by chrisbianca** [comment] 2016-02-19 09:01
It looks like this has been mentioned previously: https://github.com/facebook/react-native/issues/5122

Sorry, when I searched yesterday this didn't come up.

**Comment by mkonicek** [comment] 2016-02-21 22:36
Wow thank for all the debugging! I have very limited knowledge of iOS development too. Thanks for finding the related issue. Looks like several people already hit that one, I'll ask Nick there.

**Comment by mkonicek** [comment] 2016-02-21 22:36
Let's close this one and discuss in #5122.

**Closed by mkonicek** 2016-02-21 22:36 UTC
Labels: Contains Potential Question Keywords

**Comment by jeffbowen** [comment] 2016-05-05 15:39
Check out my [comment on issue 2246](https://github.com/facebook/react-native/issues/2246#issuecomment-217187621).
