### ISSUE TITLE
react-native 0.57.0 : Module 'Accessibility Info' does not exist in the Haste Module Map

### ISSUE THREAD

**Issue by rottenoats** [facebook/react-native#21215] opened 2018-09-20 07:34 UTC
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment

```
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 2.29 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.10.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 23.0.1, 23.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3
        API Levels: 23, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4670197
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.0 => 0.57.0

```
## Description

Recently had a macos update ( I dread updates ) and to my (not) suprise running my app on my ios emulator failed.

I then proceeded to update my react-native version and my project. That failed so I decided to start a fresh project to see if it would work.

And it didn't. It threw the following errors 

> ":CFBundleIdentifier", Does Not Exist

Which some solutions were proposed in #7308 and I did react-native-git-upgrade and I now get the following errors :

> Module `AccessibilityInfo` does not exist in the Haste module map

No solutions were found in #19953 and said a fix was to occur in 0.57.0 react-native

## Reproducible Demo

```
react-native init SomeProject
react-native run-ios //error ":CFBundleIdentifier"
react-native-git-upgrade
react-native run-ios //error: Module 'Accessibility Info' does not exist in the Haste Module Map 
```

**Comment by magrinj** [comment] 2018-09-20 12:28
After trying to upgrade from `0.55.4` to `0.57.0` same error for me...

**Comment by magrinj** [comment] 2018-09-20 13:06
After reseting all my files, and start again a new `react-native-git-upgrade` the error disappear, seams to be an error added in Xcode file during the fail of the last `react-native-git-upgrade`

**Comment by hramos** [comment] 2018-09-24 22:47
Reiterating what Marc said in #14423 at the start of the year. This error plainly indicates the project failed to compile or link. You'll need to look further up in your output for a hint of the root cause. I've opened #21303 in order to help people who run into this issue, and will lock this thread to avoid causing more confusion.

Duplicate of #21303

**Closed by hramos** 2018-09-24 22:47 UTC
