### ISSUE TITLE
WebSocket connection to debugger failed

### ISSUE THREAD

**Issue by LuckyLuky** [facebook/react-native#7413] opened 2016-05-05 19:20 UTC
Hi, 
I've sudenly started getting this strange error when trying to start debugger in Chrome. This is the full message: 
`WebSocket connection to 'ws://localhost:8081/debugger-proxy?role=debugger&name=Chrome' failed: One or more reserved bits are on: reserved1 = 0, reserved2 = 1, reserved3 = 1` 
The status on debugger page also changes to this:
`Status: Disconnected from proxy. Attempting reconnection. Is node server running?`

Everything worked fine until today. I've even tried to clear all node module and reinstall them, while updating React Native version to the latest. I've also tried running packager with parameter `--reset-cache`. None of these helped.

_Edit_: I should add that I'm running Windows 10.

**Comment by damusnet** [comment] 2016-05-05 21:34
@facebook-github-bot duplicate #6627

**Comment by facebook-github-bot-2** [comment] 2016-05-05 21:37
@damusnet tells me this issue is a duplicate of #6627. Let's discuss there, closing this one.

**Closed by facebook-github-bot-2** 2016-05-05 21:37 UTC
Labels: Ran Commands

**Comment by LuckyLuky** [comment] 2016-05-05 21:40
I've started new a issue because the other one says `Invalid frame header`, nothing about reserved bits, so I wasn't sure if it is the same error.

**Comment by damusnet** [comment] 2016-05-05 21:44
Seems close enough to me, and with > 500 issues, it feels right to try and group them whenever possible.

**Comment by Yuyi** [comment] 2016-05-06 08:33
After I have uninstalled the ESET Smart Security, it looks like the problem is fixed. :p

**Comment by LuckyLuky** [comment] 2016-05-06 10:28
@Yuyi Wow, thanks a lot, you're absolutely right! Haven't even crossed my mind since I had the program for quite a while and the problems started just yesterday. Uninstalling solved the problem.

@damusnet Should we add a mention about this potential problem to docs?

Btw. Removing ESET Smart Security is the worst, the program just wouldn't uninstall from Control Panels, I had to follow these instructions: **http://support.eset.com/kb2289/#Windows10**
Just in case someone else would have problems getting rid of the program.

**Comment by damusnet** [comment] 2016-05-06 11:25
@LuckyLuky I guess you could to a PR to the [debugging page](https://facebook.github.io/react-native/docs/debugging.html#content) though it seems like a classic "check your firewalls and antivirus" to me. At least this error and the solution now live here for others to find.

**Comment by bestofsong** [comment] 2016-07-03 05:35
same issue  +1

**Comment by 3LP** [comment] 2016-07-09 13:49
+1
