### ISSUE TITLE
Having a SafeAreaView inside ScrollView breaks scrolling

### ISSUE THREAD

**Issue by WesleydeSouza** [facebook/react-native#19658] opened 2018-06-11 17:07 UTC
## Environment
```
Scanning folders for symlinks in /Users/wesley/Sites/do-app/node_modules (15ms)

Environment:
  OS: macOS High Sierra 10.13.5
  Node: 10.3.0
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: ~0.55.2 => 0.55.4
```

## Description
`SafeAreaView` is dynamic, if the first element on a screen is a `ScrollView`, and has children `SafeAreaView`s, when the user scrolls down, the `SafeAreaView` reduces in height because it's not touching the safe area anymore, which in contrast scrolls the content back up.

## Steps to Reproduce
Create an example such as

```jsx
const App = () => (
  <ScrollView>
    <SafeAreaView>
      {longVerticalContent}
    </SafeAreaView>
  </ScrollView>
);
```

## Expected Behavior
Content should scroll normally.

## Actual Behavior
When you scroll slowly, the scrolling stutters and the content moves back up. If you scroll fast enough you don't see such a bad effect.

Video:
![Bug reproduction video](https://user-images.githubusercontent.com/126160/41246084-f1142e16-6d77-11e8-9306-1576caa871a4.gif)

I'd love to be able to get that information from a different source, such as `Dimensions.get`, so I could apply it here manually.

**Comment by hramos** [comment] 2018-06-11 22:28
Why is your SafeAreaView inside a ScrollView? SAV should wrap your top level view.

**Comment by WesleydeSouza** [comment] 2018-06-11 22:41
@hramos yes, that would work better, but won't have the expected visuals. The contents wouldn't overflow behind the notification bar, like the first item background.

**Comment by brunolemos** [comment] 2018-06-12 17:45
Duplicated of #16997 that should not have been closed

**Comment by hramos** [comment] 2018-06-12 18:19
Duplicate of #16997 (needs write access to successfully mark as a dupe).

**Closed by hramos** 2018-06-12 18:19 UTC
Labels: :large_blue_diamond:iOS

**Comment by ceciliaschiebel** [comment] 2018-09-23 12:49
I had the same situation, and contentInsetAdjustmentBehavior worked for me
```
<ScrollView contentInsetAdjustmentBehavior="automatic">
      <SafeAreaView>
            {/* long content here */}
      </SafeAreaView>
</ScrollView>
```

from react-native repo, ScrollView code says:
```
/**
   * This property specifies how the safe area insets are used to modify the
   * content area of the scroll view. The default value of this property is
   * "never". Available on iOS 11 and later.
   * @platform ios
   */
  contentInsetAdjustmentBehavior?: ?(
    | 'automatic'
    | 'scrollableAxes'
    | 'never'
    | 'always'
  ),
```
