### ISSUE TITLE
NativeEventEmitter cannot be null on IOS 

### ISSUE THREAD

**Issue by oflarcade** [facebook/react-native#27901] opened 2020-01-30 02:06 UTC
Description:

I am trying to communicate between two components in react native with NativeEventEmitter 
 but I am faced with Native module cannot be null error on IOS; It works as expected in IOS; 

in the node_modules/react-native/Libraries/EventEmiiter/NativeEventEmitter.js clearly you can see that in the constructor :

```constructor(nativeModule: ?NativeModule) {
    super(RCTDeviceEventEmitter.sharedSubscriber);
    if (Platform.OS === 'ios') {
      invariant(nativeModule, 'Native module cannot be null.'); <== Here
      this._nativeModule = nativeModule;
    }
  }
``` 
![Simulator Screen Shot - iPhone 6s Plus - 2020-01-30 at 02 44 16](https://user-images.githubusercontent.com/18123840/73414172-45ed3c80-430e-11ea-9d44-be7239ef620e.png)

React Native version:
```
    System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz
    Memory: 878.18 MB / 10.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.13.0 - /usr/local/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 25.0.1, 25.0.3, 26.0.0, 26.0.3, 27.0.3, 28.0.2, 28.0.3, 29.0.2
      System Images: android-23 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.9.0 => 16.9.0 
    react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
```

## Steps To Reproduce

1.Emit event from component A;
2. Listen to event from component B;

## Expected Results

 Component A emit the custom event;
 Component B Listen to that custom event;

## Snack, code example, screenshot, or link to a repository:

   > Snack reproducing the error on IOS:

https://snack.expo.io/@git/github.com/oflarcade/customEventsExpo

**Comment by hramos** [comment] 2020-01-30 05:42
This doesn't seem like the intended use of NativeEventEmitter, which is to [handle events sent from a Native Module](https://facebook.github.io/react-native/docs/native-modules-ios#sending-events-to-javascript), but it looks like you're trying to send events between two JavaScript Components. There's no Native Module in that case.

**Comment by oflarcade** [comment] 2020-01-30 10:23
@hramos As stated in the React documentation:


For communication between two components that don't have a parent-child relationship, you can set up your own global event system. Subscribe to events in componentDidMount(), unsubscribe in componentWillUnmount(), and call setState() when you receive an event.

That is why I am relying on events, a detailed description can be found [here](https://stackoverflow.com/questions/59977264/react-native-0-61-4-event-emitter-causing-crash-on-ios) .

I couldn't find any packages that handle components triggered events in react-native, but if you know anything, can you please point me to that direction.

Thanks.

**Comment by dulmandakh** [comment] 2020-01-31 17:40
You can use parent component's state or other means to make communication between two children. It's not a bug or issue, so closing this.

**Closed by dulmandakh** 2020-01-31 17:40 UTC
Labels: Needs: Author Feedback
