### ISSUE TITLE
Upgrade throws version number error

### ISSUE THREAD

**Issue by scazzy** [facebook/react-native#11334] opened 2016-12-07 07:03 UTC
The upgrade didn't work. Throws "The specified version of React Native 0.38.0 doesn't exist". Tried with and without version number.
Currently on 0.37.0.

![image](https://cloud.githubusercontent.com/assets/1681586/20958014/43f413e6-bc79-11e6-8e49-cf8deb574394.png)

**Comment by ncuillery** [comment] 2016-12-07 07:18
@scazzy can you confirm that you use NPM 2 (run `npm --version`).

If so, it's a duplicate of #11330

**Comment by scazzy** [comment] 2016-12-07 10:28
@ncuillery v3.7.5

**Comment by scazzy** [comment] 2016-12-08 06:01
@ncuillery thanks for giving a hint. Worked well after upgrading `npm` cli. guess you can add it in documentation / readme
@n3tr

**Closed** 2016-12-09 15:59 UTC
