### ISSUE TITLE
Multiple errors after switching to 0.8.0-rc

### ISSUE THREAD

**Issue by dvine-multimedia** [facebook/react-native#1952] opened 2015-07-11 04:45 UTC
After switching to 0.8.0-rc I getting a bunch of errors. For those I don't even really now where to start investigating.

Error: Invariant Violation: EventPluginHub: More than one plugin attempted to publish the same registration name, `onLoadStart`.
 stack: 
  publishRegistrationName                              index.ios.bundle:14552
  publishEventForPlugin                                index.ios.bundle:14533
  recomputePluginOrdering                              index.ios.bundle:14489
  Object.EventPluginRegistry.injectEventPluginsByName  index.ios.bundle:14640
  Object.inject                                        index.ios.bundle:6865
  <unknown>                                            index.ios.bundle:1747
  require                                              index.ios.bundle:254
  <unknown>                                            index.ios.bundle:1715
  require                                              index.ios.bundle:254
 URL: undefined
 line: undefined
 message: Invariant Violation: EventPluginHub: More than one plugin attempted to publish the same registration name, `onLoadStart`.handleException @ index.ios.bundle:10201

index.ios.bundle:10201 Error: Invariant Violation: ReactUpdates: must inject a reconcile transaction class and batching strategy
 stack: 
  ensureInjected                 index.ios.bundle:5085
  Object.batchedUpdates          index.ios.bundle:5162
  <unknown>                      index.ios.bundle:7226
  guard                          index.ios.bundle:7183
  MessageQueue.processBatch      index.ios.bundle:7225
  messageHandlers.executeJSCall  debugger-ui:55
  WebSocket.ws.onmessage         debugger-ui:81
 URL: undefined
 line: undefined
 message: Invariant Violation: ReactUpdates: must inject a reconcile transaction class and batching strategyhandleException @ index.ios.bundle:10201

ExceptionsManager.js:62 Error: Requiring module "React" which threw an exception
 stack: 
  require                                 index.ios.bundle:200
  <unknown>                               <anonymous>:49
  <unknown>                               <anonymous>:256
  Object.InjectedScript._evaluateOn       <anonymous>:895
  Object.InjectedScript._evaluateAndWrap  <anonymous>:828
  Object.InjectedScript.evaluate          <anonymous>:694
 URL: undefined
 line: undefined
 message: Requiring module "React" which threw an exceptionhandleException @ ExceptionsManager.js:62handleError @ InitializeJavaScriptAppEngine.js:40ErrorUtils.reportFatalError @ error-guard.js:28require @ require.js:197(anonymous function) @ VM85:49(anonymous function) @ VM85:256InjectedScript._evaluateOn @ VM78:895InjectedScript._evaluateAndWrap @ VM78:828InjectedScript.evaluate @ VM78:694

ExceptionsManager.js:62 Error: Requiring unknown module "react". If you are sure the module is there, try restarting the packager.
 stack: 
  require                                 index.ios.bundle:200
  <unknown>                               <anonymous>:50
  <unknown>                               <anonymous>:256
  Object.InjectedScript._evaluateOn       <anonymous>:895
  Object.InjectedScript._evaluateAndWrap  <anonymous>:828
  Object.InjectedScript.evaluate          <anonymous>:694
 URL: undefined
 line: undefined
 message: Requiring unknown module "react". If you are sure the module is there, try restarting the packager.

**Comment by jaysnanavati** [comment] 2015-07-12 15:35
@dvine-multimedia  I get this too, when working with react-native-video, did you find any resolution?

**Comment by jaysnanavati** [comment] 2015-07-12 15:41
@dvine-multimedia  was able to resolve this by removing 
    RNVideoEventLoading: @{
      @"registrationName": @"onLoadStart"
    },

in RCTVideoManager.m as it appears that RCTNetworkImageViewManager.m is also registering with the same name and that seems to be the root cause of this exception..

**Comment by brentvatne** [comment] 2015-07-15 15:14
Fixed in react-native-video 0.4.11 :smile:

**Closed by brentvatne** 2015-07-15 15:14 UTC

**Comment by dvine-multimedia** [comment] 2015-07-15 15:52
Thanks a lot!
