### ISSUE TITLE
RCTUITextView.m implementing unavailable method

### ISSUE THREAD

**Issue by muresanandrei** [facebook/react-native#18678] opened 2018-04-03 19:26 UTC
## **Environment**
OS: macOS High Sierra 10.13.4
Xcode: Xcode 9.3 Build version 9E145

Packages: (wanted => installed)
react: 16.3.0-alpha.0 => 16.3.0
react-native: 0.55.0 => 0.55.0

**Steps to Reproduce**
In xcode when I try to build I get the following error:
  'RCTUITextView.m implementing unavailable method' and it refers to this function in swift 

```
(void)setText:(NSString *)text
{
  [super setText:text];
  [self textDidChange];
}
```

path for file  project/node_modules/react-native/Libraries/Text/TextInput/Multiline/RCTUITextView.m

**Comment by muresanandrei** [comment] 2018-04-03 19:32
It contains everything necessary

**Comment by frmrgr** [comment] 2018-04-03 20:49
@muresanandrei Did it happen to you after you upgraded to 55?

**Comment by perteraul** [comment] 2018-04-03 21:12
@frmrgr Yes. He also has Xcode 9.3.

**Comment by frmrgr** [comment] 2018-04-03 21:30
For me the project also got wrecked after I switched to 55, nothing compiled with random errors. I did 2 things, don't known which one helped:
1) Product -> clean.
2) Drag&drop libReact.a from Linked frameworks and libraries section of project config into Frameworks folder under my app in the left panel of xcode.

**Comment by muresanandrei** [comment] 2018-04-03 21:39
Still not working forgot to tell I use cocoapods

**Comment by muresanandrei** [comment] 2018-04-03 21:44
Even new react project has this error.

**Comment by jeremyblalock** [comment] 2018-04-04 00:54
I have noticed similar issues with XCode 9.3 (auto-updated yesterday).

It seems like for some reason [Categories](https://developer.apple.com/library/content/documentation/General/Conceptual/DevPedia-CocoaCore/Category.html) may not being included properly.

My error is:

```
No visible @interface for 'RCTBaseTextShadowView' declares the selector 'clearLayout'
```

and `clearLayout` is defined in `<React/RCTShadowView+Layout.h>`

**Comment by muresanandrei** [comment] 2018-04-04 01:04
I think the error may be because of swift 4.1 and the RCTUITextView.m must be updated and the rest of swift files if necessary.

**Comment by InderKumarRathore** [comment] 2018-04-05 08:45
Today is my first day of using RN, but after updating the project settings of all the xcode projects in the RN project I get the same error. Using Xcode 9.3

**Comment by guoze-292** [comment] 2018-04-05 16:39
@InderKumarRathore same here:(

**Comment by jeremyblalock** [comment] 2018-04-05 16:50
See this article for how to install old versions of Swift in XCode: https://m.pardel.net/using-old-versions-of-swift-in-xcode-4dd46644a257

This worked for me with version 4.0.3

**Comment by swcisel** [comment] 2018-04-05 17:25
I can also confirm that 4.0.3 fixes the issue.

**Comment by alexfigliolia** [comment] 2018-04-06 00:35
Swift 4.0.3 is unfortunately not doing the trick for me

**Comment by jeremyblalock** [comment] 2018-04-06 00:42
If it doesn’t work (because of caching)

1. Close Xcode
2. Delete node_modules and reinstall fresh
3. Try again

**Comment by jm-above** [comment] 2018-04-09 13:14
Varningar vid "yarn" installation:

```
warning "workspace-aggregator-e85021a1-766f-43d5-a153-3f3e11dbc19a > Memories > react-native@0.54.3" has incorrect peer dependency "react@^16.3.0-alpha.1".
warning "workspace-aggregator-e85021a1-766f-43d5-a153-3f3e11dbc19a > Memories > react-native-firebase@3.3.1" has unmet peer dependency "fbjs@*".
warning "workspace-aggregator-e85021a1-766f-43d5-a153-3f3e11dbc19a > Memories > react-native-fs@2.9.11" has incorrect peer dependency "react-native@^0.51.0".
warning "workspace-aggregator-e85021a1-766f-43d5-a153-3f3e11dbc19a > Memories > react-native-fs@2.9.11" has incorrect peer dependency "prop-types@15.6.0".
warning "workspace-aggregator-e85021a1-766f-43d5-a153-3f3e11dbc19a > Memories > react-native-fs@2.9.11" has unmet peer dependency "create-react-class@^15.6.2".
warning "workspace-aggregator-e85021a1-766f-43d5-a153-3f3e11dbc19a > Memories > @storybook/addon-actions@3.3.15" has unmet peer dependency "@storybook/addons@^3.3.0".
warning "workspace-aggregator-e85021a1-766f-43d5-a153-3f3e11dbc19a > Memories > @storybook/addon-knobs@3.3.15" has unmet peer dependency "@storybook/addons@^3.3.0".
warning "workspace-aggregator-e85021a1-766f-43d5-a153-3f3e11dbc19a > Memories > @storybook/addon-links@3.3.15" has unmet peer dependency "@storybook/addons@^3.3.0".
warning "workspace-aggregator-e85021a1-766f-43d5-a153-3f3e11dbc19a > Memories > @storybook/react-native@3.3.15" has unmet peer dependency "babel-core@^6.26.0 || ^7.0.0-0".
warning "workspace-aggregator-e85021a1-766f-43d5-a153-3f3e11dbc19a > @pandora/codegenerator > babel-jest@23.0.0-alpha.1" has unmet peer dependency "babel-core@^6.0.0 || ^7.0.0-0".
warning "workspace-aggregator-e85021a1-766f-43d5-a153-3f3e11dbc19a > Memories > @storybook/react-native > babel-loader@7.1.4" has unmet peer dependency "babel-core@6".
warning "workspace-aggregator-e85021a1-766f-43d5-a153-3f3e11dbc19a > @pandora/servermock > firebase-admin > @firebase/database@0.2.1" has unmet peer dependency "@firebase/app-types@^0.1.0".
warning "workspace-aggregator-e85021a1-766f-43d5-a153-3f3e11dbc19a > tdrcodereader > @shoutem/ui > @shoutem/animation@0.12.2" has incorrect peer dependency "react@16.0.0".
warning "workspace-aggregator-e85021a1-766f-43d5-a153-3f3e11dbc19a > Memories > react-native > metro > @babel/plugin-check-constants@7.0.0-beta.38" has incorrect peer dependency "@babel/core@7.0.0-beta.38".
warning "workspace-aggregator-e85021a1-766f-43d5-a153-3f3e11dbc19a > @pandora/servermock > firebase-admin > @firebase/database > @firebase/database-types@0.2.0" has unmet peer dependency "@firebase/app-types@^0.1.0".
```

**Comment by flymeow** [comment] 2018-04-10 14:40
has the same error with XCode 9.3

**Comment by coderdave** [comment] 2018-04-11 01:49
Switching to Swift 4.0.3, closing Xcode, deleting node_modules reinstalling node_modules, didn't work for me. Is there a way to fix this code manually?

**Comment by alexfigliolia** [comment] 2018-04-11 18:00
Is everyone aware that utilizing the swift 4.0.3 toolchain means not being able to release to the app store?

**Comment by coderdave** [comment] 2018-04-11 18:44
Hopefully this issue is escalated if what @alexfigliolia says is true? Is there a manual code fix for the offending code in `RCTUITextView.m`?

**Comment by alexfigliolia** [comment] 2018-04-11 21:11
This problem has been solved. Im not sure how or why, but as of today my build succeeds using the default xcode toolchain.

**Comment by therealaldo** [comment] 2018-04-13 05:30
Weird, had the same issue and reverting to the 4.0.3 toolchain didn't do it for me. Weirdly enough, mine is also working now with the default toolchain.

**Comment by viethaca** [comment] 2018-04-15 15:42
remove xcode 9.3 and install xcode 9.2

**Comment by Anccerson** [comment] 2018-04-16 07:26
This issue occurs after I update to the recommended settings, and I fix it by reverting all warning options of the RCTText project build settings. Option "Overriding Deprecated Objective-C Methods" may be the key but I'm not sure.

**Comment by izikandrw** [comment] 2018-04-17 20:47
comment above by @jeremyblalock very useful--try this first before doing a bunch of downgrading/reverting to old stuff

**Closed** 2018-04-25 00:00 UTC
Labels: :clipboard:No Template, :grey_question:Needs More Information, Ran Commands

**Comment by timomeara** [comment] 2018-04-25 18:07
i had the same problem. @Anccerson is correct.
set 'Overriding Deprecated Objective-C Methods' to 'no' in the RCTText proj 
<img width="597" alt="screen shot 2018-04-25 at 1 05 33 pm" src="https://user-images.githubusercontent.com/5084668/39264108-a601966a-4889-11e8-85a7-920757d980da.png">

**Comment by alex-nishikawa** [comment] 2018-07-05 05:59
A bigger screenshot to the answer from @timomeara 
![screen shot 2018-07-05 at 12 56 00 am](https://user-images.githubusercontent.com/3360238/42304996-8ec0a1f2-7fee-11e8-9afb-f7da841f7c59.jpg)

**Comment by mayognaise** [comment] 2018-08-18 18:27
@Anccerson @timomeara @alex-nishikawa  on Xcode 9.4.1, there is no more section which says `Overriding Deprecated Objective-C Methods`.

![image](https://user-images.githubusercontent.com/588874/44302232-599f1180-a2d9-11e8-8b77-77228c87f4e4.png)

Does anyone know where to set the warnings?

**Comment by pechar** [comment] 2018-08-30 07:11
I can confirm this also happens when you "Update to recommended settings" (see attached) the RCT projects within XCode. The only way I managed to fix this was as @jeremyblalock suggested.
Basically, after updating to recommended settings the projects start showing strict warnings caused by outdated code. Good old native development. I wasted lots of time on this.

<img width="328" alt="screen shot 2018-08-30 at 09 09 22" src="https://user-images.githubusercontent.com/592348/44835433-766e0a00-ac34-11e8-8240-8d4a78053490.png">

**Comment by ramsy1980** [comment] 2018-09-22 16:58
Disabled Overriding Deprecated Objective-C Methods seemed to solve the issue for Version 10.0 beta 4 (10L213o)

**Comment by Young-Je** [comment] 2018-11-08 06:43
Overriding Deprecated Objective-C Methods set to NO

**Comment by jerodgers1** [comment] 2019-01-18 16:19
Any other suggestions? I have tried the following
* clean and rebuild
* quiting xcode then reopening
* removed node_modules and then reinstalled them.
* Overriding Deprecated Object-C methods - NO
* switching toolchains to swift 4.0.3

I am using Xcode 10.1
