### ISSUE TITLE
React Native v0.43 ViewPagerAndroid  work not well when detached then attach 

### ISSUE THREAD

**Issue by liuzhibopp** [facebook/react-native#13463] opened 2017-04-12 08:43 UTC
# Description
Integration With Existing Apps 
on 0.42  ViewPagerAndroid  work well when  **detached then attach** , after upgrading to React Native v0.43 when i slide one page to other page ，no smooth scroll and stop in middle ,i compared two version of react native.

#  Reproduction Steps and Sample Code
0.42 when i slide viewpager following codes will work and 0.43 there no **updateLayout** for ViewPagerAndroid :
`  java.lang.Thread.State: RUNNABLE
	  at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1705)
	  at android.view.View.layout(View.java:16980)
	  at android.view.ViewGroup.layout(ViewGroup.java:5550)
	  at com.facebook.react.uimanager.NativeViewHierarchyManager.updateLayout(NativeViewHierarchyManager.java:199)
	  at com.facebook.react.uimanager.NativeViewHierarchyManager.updateLayout(NativeViewHierarchyManager.java:184)
	  at com.facebook.react.uimanager.UIViewOperationQueue$UpdateLayoutOperation.execute(UIViewOperationQueue.java:124)
	  at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:784)
	  at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:831)
	  - locked <0x1e9d> (a java.lang.Object)
	  at com.facebook.react.uimanager.UIViewOperationQueue.access$1500(UIViewOperationQueue.java:45)
	  at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:870)
	  at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
	  at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:131)
	  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:925)
	  at android.view.Choreographer.doCallbacks(Choreographer.java:718)
	  at android.view.Choreographer.doFrame(Choreographer.java:650)
	  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
	  at android.os.Handler.handleCallback(Handler.java:739)
	  at android.os.Handler.dispatchMessage(Handler.java:95)
	  at android.os.Looper.loop(Looper.java:148)
	  at android.app.ActivityThread.main(ActivityThread.java:5660)
	  at java.lang.reflect.Method.invoke(Method.java:-1)
	  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

# Solution
I don‘t know whether there is a relationship with the following changes ： 
- Only call onLayout when layout has actually changed ([15429e3](https://github.com/facebook/react-native/commit/15429e333f8fd80c4778f222058dbb16278cf625))  

how to fix ?
thanks in advance!

**Comment by henrytao-me** [comment] 2017-04-23 06:48
Hi @liuzhibopp ,

I ended up writing this custom component to wrap `ViewPagerAndroid`. It works on my side. Please check. 

## ViewPagerAndroidContainer

```javascript
import React, { PureComponent } from 'react'
import { View } from 'react-native'

class ViewPagerAndroidContainer extends PureComponent {

  state = {
    width: 0,
    height: 0
  }

  render() {
    return (
      <View style={[this.props.style]} onLayout={this._onLayoutChange}>
        <View style={{ width: this.state.width, height: this.state.height }}>{this.props.children}</View>
      </View>
    )
  }

  _onLayoutChange = (e) => {
    const { width, height } = e.nativeEvent.layout
    this.setState({ width: width, height: height })
  }
}

export default ViewPagerAndroidContainer
```

## Usage
```javascript
<ViewPagerAndroidContainer style={{ flex: 1 }}>
  <ViewPagerAndroid ref='viewPager' style={{ flex: 1 }} initialPage={selectedIndex} onPageSelected={this._onPageSelected}>
    ...
  </ViewPagerAndroid>
</ViewPagerAndroidContainer>
```

**Comment by liuzhibopp** [comment] 2017-04-24 03:18
hi @henrytao-me,
     Sorry for so long to reply to you，I test just now and it does not work for me. I try to extended ViewPager modifies the **mFirstlayout** property by reflection，it works for me.
I hope to have a better way for the issue，Thanks for your answer.

**Comment by satya164** [comment] 2017-05-10 04:46
This issue seems to provide some insight to the bug https://github.com/expo/ex-navigation/issues/415#issue-207683159

**Comment by sibelius** [comment] 2017-05-11 14:40
I can confirm this

**Comment by bood** [comment] 2017-05-22 03:38
Met similar issue when adding pages to `ViewPagerAndroid` dynamically
Problem does seems to point to 15429e3 @astreet , `layout` of `ReactViewPager` is no longer invoked after the change in this case. However, newly added `ReactViewGroup` children of `ReactViewPager` requires the `layout` to be called to be properly layout-ed.

A temp working fix is to by-pass the optimization for `ReactViewPager` in `dispatchUpdates` (by comparing `mViewClassName`). You can try it out too.

I'll open a separate issue if needed.

**Comment by astreet** [comment] 2017-05-22 15:37
Yeah, we're not handling layout correctly here: the view should be given the ability to lay itself out (and its children) if it so requests. However, we're able to bypass a lot of extra work since the majority of views don't use this ability.

My first thought it to try to solve this by giving the view manager the ability to request the UIManager to layout the corresponding view in the next dispatchUpdates (e.g. exposing a new command on UIManager)

**Comment by Jackoder** [comment] 2017-06-05 03:26
I met the similar issue when migrated version from 0.29.2 to 0.44.0, haven't found a way to resovle it.

**Comment by itinance** [comment] 2017-06-25 11:06
The workaround from @henrytao-me didn't work for us, but we could fix the issue on RN 0.45.1 with the following workaround: for those cases, when we want to replace the already existing ViewPager with new children, we enforce a re-render while passing a id-property:

const id= ...something to create an id that reflacts the state of the pages and will change every time when pages will change

```
        <IndicatorViewPager
          id={id}
          ref={(c) => this.setViewPagerRef(c, id)}
          style={{width: DEVICE_WIDTH, height: slideHeight}}
          pagerStyle={{width: DEVICE_WIDTH, height: slideHeight}}
          initialPage={0}
          indicator={this.renderDotIndicator(slideCount)}
          onPageSelected={this.handlePageSelected}
          >
          {slides}
        </IndicatorViewPager>

```

**Comment by cbjs** [comment] 2017-07-19 09:26
+1

**Comment by WickedDogg** [comment] 2017-09-17 12:05
@henrytao-me you answer works for me, but there is more work to do.
If you nest `viewPagerAndroid` in a `TabNavigator`, you need to set `swipeEnabled` and `animationEnabled`, at least one of them. If they're both `false `, then viewPagerAndroid will work very slowly, and get stuck in the between pages.

**Comment by liuzhibopp** [comment] 2017-11-17 08:16
New work not using RN for a long time, so forget to care this issue，I've already put forward a method  that modifies the # mFirstlayout property by reflection to slove the  issue ，like @Jackoder ，I hope this problem has been solved in an elegant way.

**Comment by Noitidart** [comment] 2017-11-30 23:54
I copied pasted the docs example of `ViewPagerAndroid` but it doesnt work for me. It doesnt render, its mind boggling:

```
            <View style={styles.main}>
                <ViewPagerAndroid initialPage={0}>
                    <View style={styles.pageStyle}>
                        <Text>First page</Text>
                    </View>
                    <View style={styles.pageStyle}>
                        <Text>Second page</Text>
                    </View>
                </ViewPagerAndroid>
            </View>
```

```
    main: {
        flex: 1
    },
    viewPager: {

    },
    pageStyle: {
        alignItems: 'center',
        padding: 20,
        width: 100,
        height: 100,
        backgroundColor: 'green',
        flex: 1
    }
```

Anyone have any ideas?

**Comment by Noitidart** [comment] 2017-12-01 02:44
Wow @henrytao-me thanks for `ViewPagerAndroidContainer` it makes it work. So weird.

**Comment by danilobuerger** [comment] 2017-12-24 16:20
There is a fix here: https://github.com/facebook/react-native/pull/14867 
A shame that nobody seems to care to get this merged.

**Comment by satya164** [comment] 2017-12-24 18:02
> @danilobuerger

You can see that I asked for a test plan, but the author didn't respond. I can't merge things without having a way to test it if it actually works and doesn't break anything. I don't see how nobody cares to get this merged.

**Comment by danilobuerger** [comment] 2017-12-24 18:05
@satya164 So if the original author disappeared, we just wait for a test plan forever?

**Comment by satya164** [comment] 2017-12-24 23:06
Someone else can send a PR. What do want me to do? Merge without testing?

**Comment by danilobuerger** [comment] 2017-12-28 08:18
@satya164 I didn't ask you to do anything. But since you are responding, and since you submitted a similar PR, wouldn't it make sense for you to write a test? If it's just about having a project where you can see that the PR actually works, I can supply you with one.

**Comment by danilobuerger** [comment] 2017-12-28 09:43
For anybody else running into this issue: I have created a fork here: https://github.com/feastr/react-native and will be maintaining this (and porting to new versions whenever released) until the issue is fixed upstream. To use, just replace the react-native dependency in your package.json with:
```
"dependencies": {
  "react-native": "feastr/react-native#0.51-stable"
}
```

**Comment by satya164** [comment] 2017-12-28 15:03
I don't need a written test, just a way to test if the change actually works. If you have one, please send a PR with a minimal example where I can check if it's actually fixed.

I could write a test, but I don't have a lot of free time. And since someone sent a PR, they probably already have a test plan.

**Comment by danilobuerger** [comment] 2017-12-28 17:04
@satya164 I will use the already existing PR #14867 and comment a test plan there.

**Comment by satya164** [comment] 2017-12-28 17:07
@danilobuerger sounds good

**Comment by bood** [comment] 2018-01-04 02:42
@satya164 @danilobuerger But the fix does not seems to solve the problem of dynamic adding a page to ViewPager, code sample below:

```
import React, { Component } from 'react';
import { View, Text, ViewPagerAndroid } from 'react-native';

export default class DebugViewPager extends Component {
  constructor(props) {
    super(props);
    this.state = {
      npage: 2,
    };
  }
  render() {
    let pages = []
    for (var i = 1; i <= this.state.npage; i++) {
      let bg = (i % 2 == 0) ? 'blue' : 'yellow';
      pages.push(
        <View style={[styles.pageStyle], [{backgroundColor: bg}]} key={i}>
          <Text>Page {i}</Text>
        </View>
      )
    }
    viewPager = (<ViewPagerAndroid
             style={styles.viewPager}
             initialPage={0}>
      {pages}
    </ViewPagerAndroid>);
    return (
      <View style={styles.viewPager}>
        {viewPager}
        <Text style={styles.add} onPress={()=>{
            this.setState({npage: this.state.npage + 1})
        }}>
          Add Page
        </Text>
      </View>
    )
  }
}

var styles = {
  viewPager: {
    flex: 1,
    backgroundColor: 'white',
  },
  pageStyle: {
    alignItems: 'center',
    padding: 20,
  },
  add: {
    height: 100,
    width: 100,
    backgroundColor: 'red'
  }
}
```

**Comment by satya164** [comment] 2018-01-04 02:59
Thanks for the comment. Can you copy/paste the comment on the linked PR too?

**Comment by bood** [comment] 2018-01-04 03:02
Done

**Comment by hramos** [comment] 2018-05-17 17:55
#14867 merged.

**Closed by hramos** 2018-05-17 17:55 UTC
Labels: :clock1:PR Pending
