### ISSUE TITLE
How to change the port 8081?

### ISSUE THREAD

**Issue by codepandy** [facebook/react-native#10715] opened 2016-11-03 07:25 UTC
Hi,

Because of the port is used by McAfee in my company,it's difficult to develop every time.

whether can the port be changed to another one?

how to do?

**Comment by ltwaia** [comment] 2016-11-03 08:06
There are two files needed to be modified about port 8081:
1. react-native/local-cli/server/server.js  - default 
2.react-native/React/React.xcodeproj/project.pbxproj -  replace all 8081
above two, it's ok;

**Comment by ummahusla** [comment] 2016-11-03 10:11
What about `react-native start --port 9988` ?

**Comment by hramos** [comment] 2016-11-03 14:16
You'll need to start the packager on a different port using the `--port` flag, and also modify any files in the iOS/Android project that use the 8081 port. See #9145 for an on-going discussion. I'll go ahead and close this as duplicate.

**Closed by hramos** 2016-11-03 14:16 UTC

**Comment by codepandy** [comment] 2016-11-04 02:37
1. node_modules/react-native/local-cli/server/server.js
2.node_modules/react-native/React/React.xcodeproj/project.pbxproj
3.node_modules/react-native/React/Base/RCTBundleURLProvider.m
4.node_modules/react-native/Libraries/WebSocket/RCTWebSocketExecutor.m
5.node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/modules/systeminfo/AndroidInfoHelpers.java
6.react-native/packager/react-packager/src/Server/__tests__/Server-test.js
7.react-native/local-cli/util/isPackagerRunning.js
8.react-native/Libraries/Image/__tests__/resolveAssetSource-test.js

I modified all of the files listed above,the packager could be started,but when I ran the command "react-native android",it didn't still worked.
there was a error:

**`Could not run adb reverse:Command failed: C:\users\jack\AppData\Local\Android\sdk/platform-tools/adb -s 029ds34d reverse tcp:8081 tcp:8081`**

**Comment by Aaronius** [comment] 2017-01-14 05:11
@codepandy I replaced **EVERY** 8081 I could find in my project with 8088 which seemed to work.

**Comment by liuxinhu** [comment] 2017-02-15 11:15
My 8081 port is also occupied by McAfee. Combining the answer of @ltwaia and @Aaronius, it finally worked for me!

**Comment by falbertp** [comment] 2017-03-09 08:43
Got the same problem here on Genymotion, android studio emulator and real devices. Isn't there any elegant alternative rather than need to change every files to another port other than 8081?

**Comment by themnd** [comment] 2017-05-10 07:30
our server component bind on port 8081, running the react-native client on the same machine is cumbersome...

**Comment by JeremyGranger** [comment] 2017-07-06 20:24
Changed EVERY instance of port from `8081` to something else... then deleted the `.babelrc` file at the root of the app directory... ran again and it works. That was way too difficult. This crap needs to be fixed. Just spent 4 hours trying to figure out a solution.

**Comment by hramos** [comment] 2017-07-21 18:04
Duplicate of #9145

**Comment by juliantellez** [comment] 2017-09-20 21:41
@codepandy @liuxh0  I just ran into the same problem, thanks McAfee 👎 
this is how I stopped the macmn process

```
sudo lsof -n -i4TCP:8081 # get the process' PID
sudo launchctl list | grep 5693 # find the launchd endpoint
sudo launchctl remove com.mcafee.agent.macmn 
```

**Comment by Qvatra** [comment] 2017-10-17 15:16
same problem here.

**Comment by swap7206** [comment] 2017-11-02 15:27
Same problem , trying it on windows

**Comment by aelshamy** [comment] 2017-11-15 20:12
npm start -- --port=8080 worked for me

**Comment by pranavdixit** [comment] 2017-11-16 10:17
Two Steps which worked for me:
1. node_modules/react-native/local-cli/server/server.js
change "default: 8081, " to "default: 1234,"
2.  On android emulator press cmd +m(for mac) 
Dev Settings > Debug server host & port for device >"10.0.2.2:1234"

**Comment by noumantahir** [comment] 2018-01-23 07:38
These are the files where I had to tweak port number to make it work on a different port

> 1. node_modules/react-native/local-cli/server/server.js
> 2. XCode -> [App]/Libraries/React.xcodeproj/React/Base/RCTBundleURLProvider.m
> 3. XCode -> [App]/Libraries/React.xcodeproj/React/Base/RCTBridgeDelegate.m
> 4. XCode -> [App]/Libraries/React.xcodeproj/React/DevSupport/RCTInspectorDevServerHelper.mm
> 5. XCode -> [App]/Libraries/RCTWebSocket.xcodeproj/RCTWebSocketExecutor.m

Afterwards, running simple `react-native run-ios` without specifying any extra argument ran the package and app on my selected port. I am using `"react-native": "0.52.0"`

**Comment by amarnathpatel** [comment] 2018-02-19 12:41
Two Steps which worked for me:

node_modules/react-native/local-cli/server/server.js
change "default: 8081, " to "default: 8088,"
On android emulator press cmd +m(for mac)
Dev Settings > Debug server host & port for device >"10.0.2.2:8088"

**Comment by amarnathpatel** [comment] 2018-02-19 12:45
For debugging(Windows) , open the react native debugger -
http://localhost:8088/debugger-ui

Then press Ctrl +Shift + J

**Comment by Louies89** [comment] 2018-02-19 14:02
Hi All,
I found the same issue while running in windows environment and simulating using android simulator.
After doing some trial & error, I found the solution as below:

1>> Change the port in "\node_modules\react-native\local-cli\server\server.js" from default: 

> process.env.RCT_METRO_PORT || 8081

to 

> default: process.env.RCT_METRO_PORT || 9088

if the port is blocked or issued to some other application.
**Note**: You can choose any port number, I have chosen 9088
2>> Run the command react-native run-android --port 9088 (Put your port number here). This port shall be sent to adb running, so that both server and adb shall be in same port.
3>> Now in Android studio simulator, press Ctrl+m, to go for "**Dev Setting**", then select **Debug Server port & host for Device**, set "**localhost:9088**".

Now it will start loading the changes you make in your application.

Enjoy coding now :)

**Comment by Arshiamidos** [comment] 2018-03-09 20:44
#304

**Comment by schillerGao** [comment] 2018-04-21 01:45
8081端口被占用，我是用这种方式实现的
1.  react-native/local-cli/server/server.js - default
2. react-native/React/React.xcodeproj/project.pbxproj - replace all "port" 8081 ,not fileref
3. above two, it still cannot run .  So you should search global in you native project  in  Xcode ,change all 

4. @ltwaia
