### ISSUE TITLE
View setting opacity to components even using position absolute

### ISSUE THREAD

**Issue by MateusAndrade** [facebook/react-native#22654] opened 2018-12-14 19:51 UTC
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
    System:
      OS: Linux 4.18 Ubuntu 18.10 (Cosmic Cuttlefish)
      CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
      Memory: 610.19 MB / 7.70 GB
      Shell: 5.5.1 - /usr/bin/zsh
    Binaries:
      Node: 11.4.0 - /usr/bin/node
      Yarn: 1.12.3 - /usr/bin/yarn
      npm: 6.4.1 - /usr/bin/npm
    SDKs:
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.2, 28.0.3
        System Images: android-24 | Android TV Intel x86 Atom, android-24 | ARM 64 v8a, android-24 | ARM EABI v7a, android-24 | Intel x86 Atom, android-24 | Intel x86 Atom_64, android-24 | Google APIs ARM 64 v8a, android-24 | Google APIs ARM EABI v7a, android-24 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-26 | Intel x86 Atom, android-26 | Intel x86 Atom_64, android-27 | Android TV Intel x86 Atom, android-27 | Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom
    npmPackages:
      react: 16.6.1 => 16.6.1 
      react-native: 0.57.7 => 0.57.7 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-rename: 2.4.0

## Description
Describe your issue in detail. Include screenshots if needed. If this is a regression, let us know.
Hello, when im trying to add a View, and then using a position absolute to position my button, like the following pic. By some reason, the component positioned with abosulte, that is NOT a children on the view with opacity gets the opacity of the view positioned above.

## Screenshot

[https://imgur.com/a/kZUf6uh](url)

On this screen, when i set my button container to opacity 0.5 and sets the button to stays together with this view, i get the button with a opacity of 0.5. Even setting zIndex the problem persists.

How can i manage this bug? Applying a rgba on backgroundColor?

**Comment by patrickkempff** [comment] 2019-02-14 19:52
@MateusAndrade Thank you for reaching out. 
I am not sure if I understand your question correctly, so let me try to verify your problem:
```
<View>  <---- this component has a style with opacity: 0.5
   <Button />   <---- this component is also rendered with opacity: 0.5?
</View>
```
The button is rendered with opacity 0.5 despite having position set to absolute? If this is the case, I can verify the bevihaviour is as espected. Setting the opacity will also affect its children. If you only want make the background see trough you can use `backgroundColor: 'rgba(0,0,0,0.5)'`.

Can you verify this is the case?

To increase the probability of this issue getting resolved, please make sure you describe the problem as clearly as possible.

**Comment by patrickkempff** [comment] 2019-03-16 14:15
I'm closing this issue because it does not seem like a bug or regression. If you don't agree, please feel free to file a new issue report. Make sure to include steps to reproduce the behavior.

**Closed by patrickkempff** 2019-03-16 14:15 UTC
Labels: Platform: Linux, Type: Bug Report
