### ISSUE TITLE
Does not seem to support flow's strict_call_arity

### ISSUE THREAD

**Issue by Jpunt** [facebook/react-native#14832] opened 2017-07-05 11:59 UTC
### Is this a bug report?

Yes

### Have you read the Bugs section of the Contributing to React Native Guide?

Yes

### Environment

1. `react-native -v`: react-native-cli: 2.0.1 | react-native: 0.45.1
2. `node -v`: v6.9.2
3. `npm -v`: 3.10.9
4. `yarn --version` (if you use Yarn): 0.21.3

1. Target Platform (e.g. iOS, Android): iOS
2. Development Operating System (e.g. macOS Sierra, Windows 10): macOS Sierra
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): Xcode 

### Steps to Reproduce

1. `> react-native init TmpProject`
2. `> cd TmpProject`
3. `> yarn add -D flow-bin`
4. edit .flowconfig to use flow-version >= 0.47
5. `> ./node_modules/.bin/flow`

```
node_modules/react-native/Libraries/Experimental/WindowedListView.js:493
493:           {this.props.renderWindowBoundaryIndicator(showIndicator)}
                                                         ^^^^^^^^^^^^^ unused function argument
   76:   renderWindowBoundaryIndicator?: () => ?React.Element<any>,
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^ function type expects no arguments

... more errors like these...

Found 41 errors
```

### Expected Behavior

No errors on a newly created project.

### Actual Behavior

A lot of error on a newly created project.

### Reproducible Demo

https://github.com/Jpunt/react-native-flow-bug

See [this post on flow.org](https://flow.org/blog/2017/05/07/Strict-Function-Call-Arity/) for more information about these kind of errors.

**Comment by gabelevi** [comment] 2017-07-05 12:12
This was fixed in master back in May (https://github.com/facebook/react-native/commit/3ddc7d47d5d7f043810a55227bf60bec823e7b02).

Looking at the [0.45-stable branch](https://github.com/facebook/react-native/commits/0.45-stable), I don't see that commit. But I do see it in [0.46-stable](https://github.com/facebook/react-native/commits/0.46-stable). Not sure when that's scheduled for release.

**Comment by hramos** [comment] 2017-09-21 15:09
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Closed by hramos** 2017-09-21 15:09 UTC
Labels: Icebox
