### ISSUE TITLE
Build RN 0.60-rc ios error

### ISSUE THREAD

**Issue by kida7** [facebook/react-native#25252] opened 2019-06-13 09:49 UTC
## React Native version:

System:
    OS: macOS High Sierra 10.13.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
    Memory: 1.16 GB / 12.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    Android SDK:
      API Levels: 19, 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.2, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
      System Images: android-24 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.5429.30.34.5452501
    Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.0-rc.1 => 0.60.0-rc.1
## Steps To Reproduce

1. react-native init project_name --version react-native@next
2. open ios/project_name.xcworkspace and build

### Got error: 
.../node_modules/react-native/Libraries/LinkingIOS/RCTLinkingManager.h:10:9: 'UIKit/UIUserActivity.h' file not found

**Comment by kelset** [comment] 2019-06-18 09:18
👋sorry, I'm just seeing this.

I can't reproduce this issue, could it be that it's because you haven't run pod install in the ios folder / that you don't have cocoapods installed? 🤔

**Comment by kelset** [comment] 2019-07-01 08:26
👋 I just tested this again and I can't repro your issue - and given that there has been no replies for almost 2 weeks now, I'll close this.

**Closed by kelset** 2019-07-01 08:26 UTC
Labels: Bug, Platform: iOS
