### ISSUE TITLE
Expand on `accessibilityComponentType`

### ISSUE THREAD

**Issue by dantman** [facebook/react-native#13740] opened 2017-05-02 17:10 UTC
Currently for Android we have `accessibilityComponentType` which can be one of `button`, `radiobutton_checked`, or `radiobutton_unchecked` to give the view the behaviour of a native element so accessibility tools work correctly.

Currently this seems limited to buttons and radio boxes (`android.widget.RadioButton`), other input types do not get accessibility types to behave properly. This should probably be expanded to cover other types that have some sort of native accessibility behaviour.

The important ones are probably `android.widget.CheckBox` and `android.widget.Switch` which also have the key checked/unchecked accessibility attribute but are not radio buttons.

**Comment by hramos** [comment] 2017-07-20 22:28
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/expand-on-accessibilitycomponenttype

**Comment by backwardok** [comment] 2017-11-28 23:07
@hramos can this get reopened? Still appears to be a problem, and the [Android component types](https://facebook.github.io/react-native/docs/accessibility.html#accessibilitycomponenttype-android) pales in comparison to the [iOS accessibility traits](https://facebook.github.io/react-native/docs/accessibility.html#accessibilitytraits-ios) or even the [information provided in the custom view handling for Android](https://developer.android.com/guide/topics/ui/accessibility/custom-views.html)

cc @lelandrichardson @gpeal

**Comment by backwardok** [comment] 2018-01-29 18:40
@haitaoli @lelandrichardson something to add to the core repo?

**Comment by haitaoli** [comment] 2018-01-29 23:13
@backwardok It's on my todo list. Unfortunately this PR triggered an React Native bug that I described here: https://github.com/facebook/react-native/commit/b27c54174473ea52f8818b5fd40fc518434d0ced. I had a fix for that issue and merged into our fork: https://github.com/airbnb/react-native/pull/49. There is no reliable local repro so I'll verify it with our next Android release, then submit both PRs.

**Comment by Applecustomerservice** [comment] 2018-04-16 22:57
The issue is not activated because a lot of people is not affecting and the stability of the issue is no further running. It is fixed in a recent time, and an issue is not occurring sometimes.[https://appletechsupportnumber.net/](url)

**Comment by elucaswork** [comment] 2019-03-18 20:16
The feature suggestion was discussed and approved here: https://github.com/react-native-community/discussions-and-proposals/pull/54, with checkbox and switch there.

Now it's a matter of having it implemented 🤞 (btw I've started working on `switch` role).

@cpojer @hramos I wonder if it's the case of closing this issue, once the discussion was made in a different repo.

**Comment by hramos** [comment] 2019-03-19 05:12
Thanks @elucaswork, I think this can be closed considering there's an existing proposal in the discussions repositoru.

**Closed by hramos** 2019-03-19 05:12 UTC
Labels: Help Wanted :octocat:, Type: Discussion
