### ISSUE TITLE
a crash in RCTImageLoader caused by nil response

### ISSUE THREAD

**Issue by Robert-Qiu** [facebook/react-native#6952] opened 2016-04-13 08:03 UTC
the crash info is below and I find a similar issue at #1850

```
Thread 45 Crashed:
0   CoreFoundation                      CFRetain + 176
1   CFNetwork                           __CFCachedURLResponse::__CFCachedURLResponse(_CFURLResponse*, __CFData const*, void const*, CFURLCacheStoragePolicy) + 80
2   CFNetwork                           CFCachedURLResponseCreateWithUserInfo + 124
3   CFNetwork                           -[NSCachedURLResponse initWithResponse:data:userInfo:storagePolicy:] + 308
4   imeituan                            __93-[RCTImageLoader loadImageOrDataWithTag:size:scale:resizeMode:progressBlock:completionBlock:]_block_invoke_2178 (RCTImageLoader.m:324)
```

**Comment by hufeng** [comment] 2016-04-15 15:12
upgrade react-native 0.20+

**Comment by satya164** [comment] 2016-04-16 20:52
Can you post the code which causes this error? Also try updating to the latest react-native version and see if it fixes the issue.

**Comment by Robert-Qiu** [comment] 2016-04-19 09:50
my crash is in 0.19.0
but the problem seems not fixed yet, the code below is copied from development branch
`
      dispatch_async(_URLCacheQueue, ^{

        // Cache the response
        // TODO: move URL cache out of RCTImageLoader into its own module
        BOOL isHTTPRequest = [request.URL.scheme hasPrefix:@"http"];
        [strongSelf->_URLCache storeCachedResponse:
         [[NSCachedURLResponse alloc] initWithResponse:response
                                                  data:data
                                              userInfo:nil
                                         storagePolicy:isHTTPRequest ? NSURLCacheStorageAllowed: NSURLCacheStorageAllowedInMemoryOnly]
                                        forRequest:request];
        // Process image data
        processResponse(response, data, nil);

        //clean up
        [weakSelf dequeueTasks];
`

**Comment by grabbou** [comment] 2016-04-20 21:26
Hey, would you mind clarifying a bit?

> my crash is in 0.19.0 & but the problem seems not fixed yet

If you could try 0.24, that'd help! (as per @hufeng suggestion)

> the code below is copied from development branch

We don't have development branch in react-native, did you mean your local repo?

**Comment by Robert-Qiu** [comment] 2016-04-21 03:38
sorry，the code is copied from master branch.
we have upgraded to 0.23 but the app have not uploaded to appstore.
I'm afraid that the issue will be occured again. so I post this issue here.

**Comment by Robert-Qiu** [comment] 2016-04-27 08:38
any more response?

**Comment by rainer-liao** [comment] 2016-07-01 12:40
crash mant times

**Comment by tomauty** [comment] 2016-08-02 17:05
I've received a number of separate crash reports from this file. Could this be the issue? 

```
RCTImageLoader.m line 458 in __100-RCTImageLoader loadImageOrDataWithURLRequest:size:scale:resizeMode:progressBlock:completionBlock:_block_invoke.242
```

```
RCTImageLoader.m line 467 in __100-RCTImageLoader loadImageOrDataWithURLRequest:size:scale:resizeMode:progressBlock:completionBlock:_block_invoke.249
```

```
RCTImageLoader.m line 426 in __100-RCTImageLoader loadImageOrDataWithURLRequest:size:scale:resizeMode:progressBlock:completionBlock:_block_invoke.214
```

**Comment by conover** [comment] 2016-08-08 16:46
We are also experiencing this crash intermittently. Under what exact set of circumstances is unclear.

We've attempted to mitigate using this patch (mentioned higher in this issue): https://github.com/fadils/react-native/commit/de215d119da29c171a83f696eafa591689c8923d but we are still receiving crash reports.

Here is the stack trace:
`
Crashed: NSOperationQueue 0x175d3ce0 :: NSOperation 0x18888730 (QOS: USER_INITIATED)
0  libobjc.A.dylib                0x2375868a objc_retain + 9
1  Curse                          0x45011b __100-[RCTImageLoader loadImageOrDataWithURLRequest:size:scale:resizeMode:progressBlock:completionBlock:]_block_invoke.216 + 4317467
2  Curse                          0x456555 -[RCTNetworkTask URLRequest:didCompleteWithError:] + 4343125
3  Curse                          0x456dbb __50-[RCTFileRequestHandler sendRequest:withDelegate:]_block_invoke + 4345275
4  Foundation                     0x2479684d __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 8
5  Foundation                     0x246f787f -[NSBlockOperation main] + 146
6  Foundation                     0x246e9f8f -[__NSOperationInternal _start:] + 774
7  Foundation                     0x24798b0d __NSOQSchedule_f + 192
8  libdispatch.dylib              0x23b1de7f _dispatch_queue_drain + 1762
9  libdispatch.dylib              0x23b16e17 _dispatch_queue_invoke + 282
10 libdispatch.dylib              0x23b1f20d _dispatch_root_queue_drain + 400
11 libdispatch.dylib              0x23b1f07b _dispatch_worker_thread3 + 94
12 libsystem_pthread.dylib        0x23cb2e0d _pthread_wqthread + 1024
13 libsystem_pthread.dylib        0x23cb29fc start_wqthread + 8
`

**Comment by basketofsoftkittens** [comment] 2016-08-16 19:06
same issue as @conover

**Comment by pavlelekic** [comment] 2016-09-06 11:48
I'm using RN 0.32 and I get these crashes all the time. It's so annoying, and because of this bug I cannot push this app into production. This is so unreliable.

**Comment by lacker** [comment] 2016-10-25 01:36
It looks like this issue has become a bunch of related but not identical bugs, and at least some of them are fixed, ie https://github.com/facebook/react-native/pull/1852 . So I'm not sure how to make progress on this, and I think I should close this issue. If someone can reproduce this sort of crash on a small sample app then I do think we could make progress on it and in that case it would be great if people open a new issue with the information needed to reproduce.

**Closed by lacker** 2016-10-25 01:36 UTC
Labels: iOS, Needs more information, Needs Response from Author
