### ISSUE TITLE
Unable to add a source with url `https://cdn.cocoapods.org/` named `trunk`

### ISSUE THREAD

**Issue by sytolk** [facebook/react-native#30002] opened 2020-09-22 08:19 UTC
## Description
Init ios project failed on pod install

## React Native version:
"react-native": "0.63.2"

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

**1.**
`react-native init AwesomeProject`
error Error: Failed to install CocoaPods dependencies for iOS project, which is required by this template.
Please try again manually: "cd ./AwesomeProject/ios && pod install".
cd ./AwesomeProject/ios && pod install

**2.**
```
Stanimirs-Mac-mini:ios sytolk$ `pod install`
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Cloning spec repo `trunk` from `https://cdn.cocoapods.org/`
[!] Unable to add a source with url `https://cdn.cocoapods.org/` named `trunk`.
You can try adding it manually in `/Users/sytolk/.cocoapods/repos` or via `pod repo add`.
```

**Comment by sytolk** [comment] 2020-09-22 08:21
If I try to open in browser https://cdn.cocoapods.org/ its have:
```
Fastly error: unknown domain: cdn.cocoapods.org. Please check that this domain has been added to a service.

Details: cache-fra19180-FRA
```

**Comment by sytolk** [comment] 2020-09-22 08:36
I have add: `pod repo add-cdn trunk 'https://cdn.cocoapods.org'`
now its have:
```
/Users/sytolk/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/cdn_source.rb:342: warning: URI.escape is obsolete
[!] CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/CocoaPods-version.yml Response: 500 
<html>
<head>
<title>Fastly error: unknown domain cdn.cocoapods.org</title>
</head>
<body>
<p>Fastly error: unknown domain: cdn.cocoapods.org. Please check that this domain has been added to a service.</p>
<p>Details: cache-hhn4079-HHN</p></body></html>
```

**Comment by sytolk** [comment] 2020-09-22 08:45
I have downgrade `Successfully uninstalled cocoapods-1.9.3` to `gem install cocoapods -v 1.8` like fix in this issue https://github.com/CocoaPods/CocoaPods/issues/9595
 but the problem exist too..
```
/Users/sytolk/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.8.0/lib/cocoapods-core/cdn_source.rb:326: warning: URI.escape is obsolete
[!] CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/CocoaPods-version.yml Response: 500

```

**Comment by DanielZanchi** [comment] 2020-09-22 08:47
I have the same problem. Tried with 1.8 and with the new 1.9.3 but I can't install any pods :(

**Comment by DanielZanchi** [comment] 2020-09-22 08:55
99% there's a CDN issue. 
The temporary workaround is to insert into the podfile this:
```
source 'https://github.com/CocoaPods/Specs.git'
# source 'https://cdn.cocoapods.org/'
```

Once the CDN issue is solved just leave :
`source 'https://cdn.cocoapods.org/'`

**Comment by atiernan** [comment] 2020-09-22 09:00
This is not a react native specific issue, but is due to [CocoaPods CDN being down](https://github.com/CocoaPods/CocoaPods/issues/10078)

**Comment by atlascoder** [comment] 2020-09-22 09:36
> 99% there's a CDN issue.
> The temporary workaround is to insert into the podfile this:
> 
> ```
> source 'https://github.com/CocoaPods/Specs.git'
> # source 'https://cdn.cocoapods.org/'
> ```
> 
> Once the CDN issue is solved just leave :
> `source 'https://cdn.cocoapods.org/'`

Sorry, @DanielZanchi - what Podfile to fix?

I added `source 'https://github.com/CocoaPods/Specs.git'` to `ios/Podfile` - doesn't help

**Comment by DanielZanchi** [comment] 2020-09-22 09:38
Can you show me your podfile?

**Comment by atlascoder** [comment] 2020-09-22 09:41
```
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

def add_flipper_pods!(versions = {})
  versions['Flipper'] ||= '~> 0.33.1'
  versions['DoubleConversion'] ||= '1.1.7'
  versions['Flipper-Folly'] ||= '~> 2.1'
  versions['Flipper-Glog'] ||= '0.3.6'
  versions['Flipper-PeerTalk'] ||= '~> 0.0.4'
  versions['Flipper-RSocket'] ||= '~> 1.0'

  pod 'FlipperKit', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitLayoutPlugin', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/SKIOSNetworkPlugin', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitUserDefaultsPlugin', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitReactPlugin', versions['Flipper'], :configuration => 'Debug'

  # List all transitive dependencies for FlipperKit pods
  # to avoid them being linked in Release builds
  pod 'Flipper', versions['Flipper'], :configuration => 'Debug'
  pod 'Flipper-DoubleConversion', versions['DoubleConversion'], :configuration => 'Debug'
  pod 'Flipper-Folly', versions['Flipper-Folly'], :configuration => 'Debug'
  pod 'Flipper-Glog', versions['Flipper-Glog'], :configuration => 'Debug'
  pod 'Flipper-PeerTalk', versions['Flipper-PeerTalk'], :configuration => 'Debug'
  pod 'Flipper-RSocket', versions['Flipper-RSocket'], :configuration => 'Debug'
  pod 'FlipperKit/Core', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/CppBridge', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FBCxxFollyDynamicConvert', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FBDefines', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FKPortForwarding', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitHighlightOverlay', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitLayoutTextSearchable', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitNetworkPlugin', versions['Flipper'], :configuration => 'Debug'
end

# Post Install processing for Flipper
def flipper_post_install(installer)
  installer.pods_project.targets.each do |target|
    if target.name == 'YogaKit'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.1'
      end
    end
  end
end

target 'AProj' do
  # Pods for AProj
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/callinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga', :modular_headers => true

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  target 'AProjTests' do
    inherit! :complete
    # Pods for testing
  end

  use_native_modules!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  add_flipper_pods!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'AProj-tvOS' do
  # Pods for AProj-tvOS

  target 'AProj-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

**Comment by DanielZanchi** [comment] 2020-09-22 09:44
> @DanielZanchi
> 
> ```
> platform :ios, '9.0'
> require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
> 
> def add_flipper_pods!(versions = {})
>   versions['Flipper'] ||= '~> 0.33.1'
>   versions['DoubleConversion'] ||= '1.1.7'
>   versions['Flipper-Folly'] ||= '~> 2.1'
>   versions['Flipper-Glog'] ||= '0.3.6'
>   versions['Flipper-PeerTalk'] ||= '~> 0.0.4'
>   versions['Flipper-RSocket'] ||= '~> 1.0'
> 
>   pod 'FlipperKit', versions['Flipper'], :configuration => 'Debug'
>   pod 'FlipperKit/FlipperKitLayoutPlugin', versions['Flipper'], :configuration => 'Debug'
>   pod 'FlipperKit/SKIOSNetworkPlugin', versions['Flipper'], :configuration => 'Debug'
>   pod 'FlipperKit/FlipperKitUserDefaultsPlugin', versions['Flipper'], :configuration => 'Debug'
>   pod 'FlipperKit/FlipperKitReactPlugin', versions['Flipper'], :configuration => 'Debug'
> 
>   # List all transitive dependencies for FlipperKit pods
>   # to avoid them being linked in Release builds
>   pod 'Flipper', versions['Flipper'], :configuration => 'Debug'
>   pod 'Flipper-DoubleConversion', versions['DoubleConversion'], :configuration => 'Debug'
>   pod 'Flipper-Folly', versions['Flipper-Folly'], :configuration => 'Debug'
>   pod 'Flipper-Glog', versions['Flipper-Glog'], :configuration => 'Debug'
>   pod 'Flipper-PeerTalk', versions['Flipper-PeerTalk'], :configuration => 'Debug'
>   pod 'Flipper-RSocket', versions['Flipper-RSocket'], :configuration => 'Debug'
>   pod 'FlipperKit/Core', versions['Flipper'], :configuration => 'Debug'
>   pod 'FlipperKit/CppBridge', versions['Flipper'], :configuration => 'Debug'
>   pod 'FlipperKit/FBCxxFollyDynamicConvert', versions['Flipper'], :configuration => 'Debug'
>   pod 'FlipperKit/FBDefines', versions['Flipper'], :configuration => 'Debug'
>   pod 'FlipperKit/FKPortForwarding', versions['Flipper'], :configuration => 'Debug'
>   pod 'FlipperKit/FlipperKitHighlightOverlay', versions['Flipper'], :configuration => 'Debug'
>   pod 'FlipperKit/FlipperKitLayoutTextSearchable', versions['Flipper'], :configuration => 'Debug'
>   pod 'FlipperKit/FlipperKitNetworkPlugin', versions['Flipper'], :configuration => 'Debug'
> end
> 
> # Post Install processing for Flipper
> def flipper_post_install(installer)
>   installer.pods_project.targets.each do |target|
>     if target.name == 'YogaKit'
>       target.build_configurations.each do |config|
>         config.build_settings['SWIFT_VERSION'] = '4.1'
>       end
>     end
>   end
> end
> 
> target 'AProj' do
>   # Pods for AProj
>   pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
>   pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
>   pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
>   pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
>   pod 'React', :path => '../node_modules/react-native/'
>   pod 'React-Core', :path => '../node_modules/react-native/'
>   pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
>   pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
>   pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
>   pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
>   pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
>   pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
>   pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
>   pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
>   pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
>   pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
>   pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
>   pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'
> 
>   pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
>   pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
>   pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
>   pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
>   pod 'ReactCommon/callinvoker', :path => "../node_modules/react-native/ReactCommon"
>   pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
>   pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga', :modular_headers => true
> 
>   pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
>   pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
>   pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
> 
>   target 'AProjTests' do
>     inherit! :complete
>     # Pods for testing
>   end
> 
>   use_native_modules!
> 
>   # Enables Flipper.
>   #
>   # Note that if you have use_frameworks! enabled, Flipper will not work and
>   # you should disable these next few lines.
>   add_flipper_pods!
>   post_install do |installer|
>     flipper_post_install(installer)
>   end
> end
> 
> target 'AProj-tvOS' do
>   # Pods for AProj-tvOS
> 
>   target 'AProj-tvOSTests' do
>     inherit! :search_paths
>     # Pods for testing
>   end
> end
> ```

I can't see where you added that but. 
add
`source 'https://github.com/CocoaPods/Specs.git'
`after 
`platform :ios, '9.0'
`

**Comment by atlascoder** [comment] 2020-09-22 09:46
@DanielZanchi 
I did:
```
anton.titkov@antimac ios % cat Podfile
platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
...
```

The same result:
```
anton.titkov@antimac ios % pod install
Auto-linking React Native modules for target `Leviosa`: RNAWSCognito, RNCAsyncStorage, RNCClipboard, RNCMaskedView, RNDeviceInfo, RNGestureHandler, RNReanimated, RNScreens, react-native-netinfo, react-native-safe-area-context, react-native-simple-crypto, react-native-slider, react-native-tcp-socket, react-native-udp, react-native-uuid-generator, and react-native-viewpager
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
[!] CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/CocoaPods-version.yml Response: 500 
<html>
<head>
<title>Fastly error: unknown domain cdn.cocoapods.org</title>
</head>
<body>
<p>Fastly error: unknown domain: cdn.cocoapods.org. Please check that this domain has been added to a service.</p>
<p>Details: cache-hhn4075-HHN</p></body></html>
```

Pod 1.9.3 - maybe this is my trouble?

**Comment by hannojg** [comment] 2020-09-22 09:47
Same for me!

**Comment by DanielZanchi** [comment] 2020-09-22 09:50
Try deleting the "Pods" and the podfile.lock.
Run again 'pod install'
If the problem persist, I don't know how to help.

**Comment by atlascoder** [comment] 2020-09-22 09:51
> Try deleting the "Pods" and the podfile.lock.
> Run again 'pod install'
> If the problem persist, I don't know how to help.

OK, thank you!

**Comment by ghasemikasra39** [comment] 2020-09-22 09:57
I am getting the same issue:
```
[!] CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/CocoaPods-version.yml Response: 500
<html>
<head>
<title>Fastly error: unknown domain cdn.cocoapods.org</title>
</head>
<body>
<p>Fastly error: unknown domain: cdn.cocoapods.org. Please check that this domain has been added to a service.</p>
<p>Details: cache-hhn4061-HHN</p></body></html>
```

```
cocoapods-1.9.3
"react-native": "0.62.2"
```

**Comment by ghasemikasra39** [comment] 2020-09-22 09:59
> 99% there's a CDN issue.
> The temporary workaround is to insert into the podfile this:
> 
> ```
> source 'https://github.com/CocoaPods/Specs.git'
> # source 'https://cdn.cocoapods.org/'
> ```
> 
> Once the CDN issue is solved just leave :
> `source 'https://cdn.cocoapods.org/'`

Where should I put it exactly?

**Comment by ghasemikasra39** [comment] 2020-09-22 10:01
> Try deleting the "Pods" and the podfile.lock.
> Run again 'pod install'
> If the problem persist, I don't know how to help.

Same for me. I tried `rm node_modules && rm yarn.lock && cd ios && rm Pods && rm podfile.lock && cd .. && yarn install && cd ios && pod install `

**Comment by raimonkh** [comment] 2020-09-22 10:03
I concur with the problem.
So far trying `source 'https://github.com/CocoaPods/Specs.git'` instead of cdn didn't help

**Comment by ByungJun25** [comment] 2020-09-22 10:23
Hi, 

I found a same issue from cocoapod repository.
If someone want workaround, please refer https://github.com/CocoaPods/CocoaPods/issues/10078#issuecomment-696481185

**Comment by ghasemikasra39** [comment] 2020-09-22 10:27
> Hi,
> 
> I found a same issue from cocoapod repository.
> If someone want workaround, please refer [CocoaPods/CocoaPods#10078 (comment)](https://github.com/CocoaPods/CocoaPods/issues/10078#issuecomment-696481185)

Where should I put it exactly in `Podfile`?

**Comment by ByungJun25** [comment] 2020-09-22 10:29
@ghasemikasra39 Please refer @DanielZanchi https://github.com/facebook/react-native/issues/30002#issuecomment-696617123

after `platform :ios, '9.0'`

**Comment by JoaoMartins1930** [comment] 2020-09-22 10:41
There's a good workaround util this is fixed! 
https://github.com/CocoaPods/CocoaPods/issues/10078#issuecomment-696481185

**Comment by ghasemikasra39** [comment] 2020-09-22 10:44
> Hi, @ghasemikasra39
> 
> Please refer @DanielZanchi [#30002 (comment)](https://github.com/facebook/react-native/issues/30002#issuecomment-696617123)
> 
> Please Add the code after `platform :ios, '9.0'`

It stucks at `Cloning spec repo cocoapods from https://github.com/CocoaPods/Specs.git`. Is it expected to take a long time?

**Comment by DanielZanchi** [comment] 2020-09-22 10:45
> > Hi, @ghasemikasra39
> 
> > 
> 
> > Please refer @DanielZanchi [#30002 (comment)](https://github.com/facebook/react-native/issues/30002#issuecomment-696617123)
> 
> > 
> 
> > Please Add the code after `platform :ios, '9.0'`
> 
> 
> 
> It stucks at `Cloning spec repo cocoapods from https://github.com/CocoaPods/Specs.git`. Is it expected to take a long time?

Yes, it takes a while depending on your connection.

**Comment by ghasemikasra39** [comment] 2020-09-22 10:56
> > > Hi, @ghasemikasra39
> > 
> > 
> > > 
> > 
> > 
> > > Please refer @DanielZanchi [#30002 (comment)](https://github.com/facebook/react-native/issues/30002#issuecomment-696617123)
> > 
> > 
> > > 
> > 
> > 
> > > Please Add the code after `platform :ios, '9.0'`
> > 
> > 
> > It stucks at `Cloning spec repo cocoapods from https://github.com/CocoaPods/Specs.git`. Is it expected to take a long time?
> 
> Yes, it takes a while depending on your connection.

![Screenshot 2020-09-22 at 12 55 18](https://user-images.githubusercontent.com/24314029/93873956-e562a380-fcd2-11ea-837e-6e1d0bc5b944.png)

Not sure if it's an internet connection issue, because my connection is fast here. It stucks for more than 15 minutes

**Comment by DanielZanchi** [comment] 2020-09-22 11:04
I have a faster connection and it took 10 minutes. Don't know what to say

**Comment by bjoern-from-kopply** [comment] 2020-09-22 11:27
I can confirm that cloning the repo takes time. Had to wait around 20 min.

**Comment by bjoern-from-kopply** [comment] 2020-09-22 11:28
> I have a faster connection and it took 10 minutes. Don't know what to say

I can confirm that cloning the repo takes time. Had to wait 20 min until my terminal printed a new line :(

**Comment by dooleyb1** [comment] 2020-09-22 11:29
> 99% there's a CDN issue.
> The temporary workaround is to insert into the podfile this:
> 
> ```
> source 'https://github.com/CocoaPods/Specs.git'
> # source 'https://cdn.cocoapods.org/'
> ```
> 
> Once the CDN issue is solved just leave :
> `source 'https://cdn.cocoapods.org/'`

Worked for me thank you - cloning the repo also took upwards of 10+ minutes for me.

**Comment by nasmuris** [comment] 2020-09-22 12:18
in case adding `source 'https://github.com/CocoaPods/Specs.git'` doesnt work for you, try to erase trunk from cocoapods repos `rm -rf ~/.cocoapods/repos/trunk`

**Comment by zaksparo** [comment] 2020-09-22 13:14
Some news on this current issue ?

**Comment by vanfigueiredo** [comment] 2020-09-22 13:25
this issue is already solved

**Comment by alloy** [comment] 2020-09-22 14:26
Going to close this issue for issue tracker hygiene reasons. For updates please follow the aforementioned upstream issue https://github.com/CocoaPods/CocoaPods/issues/10078

**Closed by alloy** 2020-09-22 14:26 UTC
Labels: Needs: Triage :mag:, 🌐Networking

**Comment by imceZZ** [comment] 2020-09-22 15:43
any news regards this?

**Comment by benkissi** [comment] 2020-09-22 16:34
> this issue is already solved
> [CocoaPods/CocoaPods#10078](https://github.com/CocoaPods/CocoaPods/issues/10078)

This is not fixed

**Comment by ivanstnsk** [comment] 2020-09-22 19:28
@imceZZ it's better to follow cocoapods news https://status.cocoapods.org/

**Comment by raimonkh** [comment] 2020-09-23 05:40
I should have been fixed (new netlify app).

BTW; did some people experience weird build/link problems during the time we got this cdn issue? We experienced those weird issues (but after cdn was fixed they went away). I would have expected either cocoapods to not download anything or to download the right things... I can't explain why did we saw the behaviour.

**Comment by Chamsswitch** [comment] 2020-09-24 03:07
this not fixed yet

**Comment by kirkryan** [comment] 2020-12-22 20:40
> > 99% there's a CDN issue.
> > The temporary workaround is to insert into the podfile this:
> > ```
> > source 'https://github.com/CocoaPods/Specs.git'
> > # source 'https://cdn.cocoapods.org/'
> > ```
> > 
> > 
> > Once the CDN issue is solved just leave :
> > `source 'https://cdn.cocoapods.org/'`
> 
> Worked for me thank you - cloning the repo also took upwards of 10+ minutes for me.

Also working for me as of Dec 2020 on a Windows 10 box.

**Comment by clearloop** [comment] 2021-02-02 17:13
https://github.com/CocoaPods/CocoaPods/issues/10078#issuecomment-696481185
