### ISSUE TITLE
Comments in-line with JSX elements cause Invariant Violation error

### ISSUE THREAD

**Issue by kernel-sanders** [facebook/react-native#22120] opened 2018-11-04 22:07 UTC
- [ X ] Review the documentation: https://facebook.github.io/react-native
  - [ X ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ X ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
```
    System:
      OS: macOS 10.14.1
      CPU: x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
      Memory: 3.58 GB / 32.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.7.0 - /usr/local/bin/node
      npm: 6.4.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728
      react-native: 0.57.4 => 0.57.4
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-vector-icons: 4.6.0
```

## Description
In line comments break react-native 56+, as shown in the code and repo below. Removing "This comment breaks the app" allows the app to run. Comments on lines by themselves seem to be ok.

```JSX
export default class App extends Component<Props> {
  render() {
    return (
      <View style={styles.container}>
        {/* This comment is ok */}
        <Text style={styles.welcome}>Welcome to React Native!</Text> {/* This comment breaks the app */}
        <Text style={styles.instructions}>To get started, edit App.js</Text>
        <Text style={styles.instructions}>{instructions}</Text>
      </View>
    );
  }
}
```

![](https://raw.githubusercontent.com/kernel-sanders/ReactNative56TextBug/master/screenshot.png)

Possibly linked to:  #20084

## Reproducible Demo
https://github.com/kernel-sanders/ReactNative56TextBug

**Comment by radex** [comment] 2018-11-06 16:27
This is most likely a Babel bug. See how the compiled JS looks like

**Comment by JKCooper2** [comment] 2018-11-11 06:19
Repro: https://snack.expo.io/@jkcooper/rn-afterline-comments

**Comment by satya164** [comment] 2019-05-30 16:41
This happens because of the whitespace before the comment:

```
</Text> {/*
```

The whitespace is recognized as a string as per JSX's parsing rules which causes an error in RN due to being outside `Text`.

If you remove this whitespace, it works:

```
</Text>{/*
```

Closing since this is the expected behaviour.

**Closed by satya164** 2019-05-30 16:41 UTC
Labels: Bug
