### ISSUE TITLE
[WebView] WebView cannot response phoneNumber click

### ISSUE THREAD

**Issue by yuyongmao** [facebook/react-native#13634] opened 2017-04-24 01:19 UTC
React native version 0.43

when i click the phone number in  webview,i got the error 'Error code :101  Description:The URL can't be shown'

how can i solve this problem?

**Comment by hramos** [comment] 2017-05-31 20:47
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-05-31 20:47 UTC
