### ISSUE TITLE
[Regression] Jest no longer works out of the box

### ISSUE THREAD

**Issue by deecewan** [facebook/react-native#20683] opened 2018-08-16 04:18 UTC
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.1
      CPU: x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Memory: 69.45 MB / 16.00 GB
      Shell: 5.4.2 - /usr/local/bin/zsh
    Binaries:
      Node: 8.11.1 - ~/.nvm/versions/node/v8.11.1/bin/node
      Yarn: 1.9.2 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.2, macOS 10.13, tvOS 11.2, watchOS 4.2
      Android SDK:
        Build Tools: 23.0.1, 23.0.3, 25.0.1, 25.0.3, 26.0.1, 26.0.2, 27.0.3
        API Levels: 23, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0
```

## Description
After upgrading to React Native v0.56.0, `jest` no longer works.
It is missing a `babel-core` bridge and the `@babel/core` dependency.
Once these are added, previously working tests no longer work if the source contains code that requires transpilation.

To confirm, my tests ran fine under v0.55.4 - after the upgrade, they started to fail. I was able to reproduce a minimal demo using `react-native init`

## Reproducible Demo

**Edit: I've [created a repo](https://github.com/deecewan/react-native-jest-regression) that has the project set up the exact same with 0.55.4 and 0.56.0.**

- run `react-native init <any name>`
- add a dependency on `react-native-vector-icons` (the same issue also happens with `react-native-pie-chart`, but only one is required)
  - `yarn add react-native-vector-icons && yarn react-native link react-native-vector-icons`
- in `App.js`, add `import Icon from 'react-native-vector-icons/MaterialIcons';`
- `echo "import App from './App';" > App.test.js`
  - You technically need to have at least one test in this file, but it will never get past the parse stage.
- `yarn test`

This will result in an error due to incorrect `babel` versions:

![image](https://user-images.githubusercontent.com/4755785/44186825-fbe6ba00-a15e-11e8-8ac0-4c088f55d9f4.png)

This one is pretty easily resolved with `yarn add -D babel-core@7.0.0-bridge.0`.

Running the `yarn test` again will result in the following errors:

![image](https://user-images.githubusercontent.com/4755785/44186854-2769a480-a15f-11e8-92d8-32fc18e84932.png)

**Comment by deecewan** [comment] 2018-08-16 04:29
I've just [created a repo](https://github.com/deecewan/react-native-jest-regression) to demonstrate this regression. Doing the exact same steps as I've listed above (short of upgrading the `babel-core` version) in `0.55.4` results in a successful test.

**Comment by ferdicus** [comment] 2018-08-16 12:11
duplicate? https://github.com/facebook/react-native/issues/19859

**Comment by hramos** [comment] 2018-08-16 23:41
Duplicate of #19859

**Closed by hramos** 2018-08-16 23:41 UTC
Labels: :warning:Regression

**Comment by evanjmg** [comment] 2018-10-05 22:48
I'm getting this with 0.57.2, but it works fine with 0.57.1```
 console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:115
    Warning: AppComponent(...): No `render` method found on the returned component instance: you may have forgotten to define `render`.

  console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6884
    The above error occurred in the <AppComponent> component:
        in AppComponent (created by Connect(AppComponent))
        in Connect(AppComponent)
        in Provider
    
    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
``` see https://github.com/facebook/react/issues/13399
