### ISSUE TITLE
Switch does not save state when swipe gesture is used

### ISSUE THREAD

**Issue by KirillTarasenko** [facebook/react-native#15632] opened 2017-08-24 10:36 UTC
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

Then, specify:

- Target Platform:  22

- Development Operating System: Windows

- Build tools: "23.0.1"

(edits by @hramos)
Environment

react-native -v:
![image](https://user-images.githubusercontent.com/18124381/29715328-98f7a5a2-89af-11e7-909d-4b6864558bc7.png)

node -v:
![image](https://user-images.githubusercontent.com/18124381/29715340-a9382eb4-89af-11e7-918c-5fb4e807e71c.png)

npm -v:
![image](https://user-images.githubusercontent.com/18124381/29715352-b567db94-89af-11e7-871b-4bcac5e68ee6.png)

yarn --version:
![image](https://user-images.githubusercontent.com/18124381/29715364-c0689308-89af-11e7-8774-a2b7a3ade1c6.png)

### Steps to Reproduce

(Write your steps here:)

1. Create wrapper component for Switch

```

//@flow
import React, { PureComponent } from "react";
import { Switch } from "react-native";
import PropTypes from "prop-types";

export default class Switcher extends PureComponent {
  static propTypes = {
    value: PropTypes.bool.isRequired,
    onToggle: PropTypes.func.isRequired
  };

  render() {
    const { onToggle, value } = this.props;
    return (
      <Switch
        onValueChange={onToggle}
        value={value}
        tintColor="#dadada"
        thumbTintColor={value ? "#2287e1" : "#ffffff"}
        onTintColor="#a7cff3"
      />
    );
  }
}

```
2. Create component
```
class MyData extends PureComponent {
 constructor(props) {
    super(props);
    this.state = { switchValue: false };
  }
 toggleSwitch = value => {
    this.setState({ switchValue: value });
    console.log(`Switch 1 is: ${value}`);
  };
...
render(){
...
 <Switcher
                  value={this.state.switchValue}
                  onToggle={this.toggleSwitch}
                />
...}
}
```

3. Run project
4. Make as shown in gif

### Expected Behavior

Save start state into Switch

(Write what you thought would happen.)

### Actual Behavior

Crash when pulling
![](https://media.giphy.com/media/xUPJUDH0Y1BdnyvDm8/giphy.gif)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by hramos** [comment] 2017-08-24 17:06
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, specifically I do not see any mention of the React Native version you are using. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

**Comment by KirillTarasenko** [comment] 2017-08-25 13:09
Environment

react-native -v:
![image](https://user-images.githubusercontent.com/18124381/29715328-98f7a5a2-89af-11e7-909d-4b6864558bc7.png)

node -v:
![image](https://user-images.githubusercontent.com/18124381/29715340-a9382eb4-89af-11e7-918c-5fb4e807e71c.png)

npm -v:
![image](https://user-images.githubusercontent.com/18124381/29715352-b567db94-89af-11e7-871b-4bcac5e68ee6.png)

yarn --version:
![image](https://user-images.githubusercontent.com/18124381/29715364-c0689308-89af-11e7-8774-a2b7a3ade1c6.png)

**Comment by hramos** [comment] 2017-08-25 17:06
Thanks, I added them to your original post.

**Comment by zibs** [comment] 2017-08-28 23:33
@KirillTarasenko I've made a snack for you here: https://snack.expo.io/r1mGumMt-

It works, and I've just copy and pasted your code. I'm not sure if you can provide any other details for your issue? Maybe double-check your code and make sure it's not something else you've misspelt or something.

**Comment by rhagigi** [comment] 2017-08-28 23:45
@zibs Are you A) on android and B) pulling the switch using a a swipe motion to the left rather than a tap? The bug is on https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/switchview/ReactSwitch.java#L32 -- what happens is that for some reason `SwitchCompat` calls `setChecked` with `true` -- but since our internal state is already `checked===true`, we set `mAllowChange` to false, no event is fired to the JS, and we never get called again with `setOn` to reset `mAllowChange`.

**Comment by zibs** [comment] 2017-08-28 23:53
@rhagigi Here is a snack with Android: https://snack.expo.io/HyIohQzKW - It seems to be working fine here as well. I'm able to drag my cursor (not a replacement for the thumb, I realize.) as well as click to make it switch.

Let me know if you see anything else awry here...

**Comment by rhagigi** [comment] 2017-08-29 00:01
@zibs I'm able to recreate on that snack using Expo on my google pixel. You might need to drag around a few times and make sure you really get that quick drag "swipe" action in there.

**Comment by hramos** [comment] 2017-08-29 16:23
Thanks @rhagigi for investigating. I've marked this as a good first task given that a potential fix has been [suggested above](https://github.com/facebook/react-native/issues/15632#issuecomment-325513572).

**Comment by cmdshepard** [comment] 2017-09-11 01:56
Unable to replicate on the emulator using RN 0.48.2 - is this still a problem?

**Comment by rhagigi** [comment] 2017-09-11 03:02
Last I checked, like 2 weeks ago, yes. How are you replicating the swipe gesture on an emulator? You really have to swing the mouse to the left while dragging the switch to recreate it on the emulator. Seems to be easier to recreate if the switch is off and then you swipe to the left

**Comment by cmdshepard** [comment] 2017-09-11 16:29
@rhagigi 

![out](https://user-images.githubusercontent.com/16440838/30285664-9877c612-96d3-11e7-86b9-4ea25d4089b1.gif)

**Comment by rhagigi** [comment] 2017-09-11 22:13
Not sure about emulator but with the above linked Snack, latest version of Expo, and my up-to-date Pixel on Oreo, the issue still recreates with a quick swipe to the left easily. Try turning the switch *off* and then swiping to the left, not necessarily dragging the handle. Keep in mind that finger swipes don't necessarily drag on the handle itself.

**Comment by KirillTarasenko** [comment] 2017-09-12 16:52
Hi. I want to clarify a problem. The component expecting to change flag (true -> false or false -> true), but if you save position of point after move from the edge to the edge this reproduce problem.

Start with flag "true":
![start switch off position](https://media.giphy.com/media/3ov9k3A1qoIjgEarni/giphy.gif)

Start with flag "false":
![start switch on position](https://media.giphy.com/media/l1J9s2c1YNfQ9KljO/giphy.gif)

**Comment by MichaelDanielTom** [comment] 2017-10-12 22:50
The surefire way to reproduce this bug is to start dragging, and then return to the state you started with (by letting go at some point before the half way point). The bug occurs when started from both true and false states.

That being said, I'm still seeing it on Android with RN-0.48.0

**Comment by meggamind** [comment] 2018-02-09 23:53
Is this still an Issue ? If so, Can I pick this up ?

**Comment by ArthurAttout** [comment] 2018-03-10 15:38
Yes, the issue still remains on react-native: 0.53.0, using a Google nexus API 26 using simply 
```
 return (
     <View style={styles.container}>
        <Switch>
        </Switch>
    </View>
);
```

**Comment by aaronhma** [comment] 2018-06-11 21:50
I am using React Native CLI: 2.0.1
React Native: 0.55.4
And still, the <Switch /> component doesn't work for me.

**Comment by aaronhma** [comment] 2018-06-11 21:57
@zibs Even though I copied and pasted it, it still doesn't work on iOS or Android.

**Comment by saxs4x** [comment] 2018-06-22 12:41
Doesn't work for me too, the value is changed yes, but the UI component keeps turnin false, or true in both ways.

react-native-cli: 2.0.1
react-native: 0.55.4

**Comment by aaronhma** [comment] 2018-06-30 15:55
I fixed it by adding a state in the React Native App.

**Comment by nabeelpkl** [comment] 2018-07-16 01:53
@aaronhma can u share the code ?

**Comment by KirillTarasenko** [comment] 2018-07-16 11:16
Hi all. It has not reproduce in RN 0.55.1. That way the issue have solution - update RN.

**Comment by radko93** [comment] 2018-09-19 19:08
Seems fine then, ping me to if something goes wrong here.

**Closed by radko93** 2018-09-19 19:08 UTC
Labels: Good first issue, Help Wanted :octocat:
