### ISSUE TITLE
> Text must not be null or empty

### ISSUE THREAD

**Issue by yjqz86** [facebook/react-native#25479] opened 2019-07-03 17:50 UTC
When I execute react-native run-android. I have the following:

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\zenz\programs\test_app\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 182

* What went wrong:
A problem occurred evaluating settings 'test_app'.
> Text must not be null or empty

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

After I try to make in  file 'node_modules@react-native-community\cli-platform-android\native_modules.gradle: 

def command = "node ./node_modules/.bin/react-native config"
to
def command = "./node_modules/.bin/react-native config"

It does not work for me. I need help

**Comment by yjqz86** [comment] 2019-07-03 19:18
I hope this capture can help

![bugReactive](https://user-images.githubusercontent.com/8808566/60619085-d9c14f00-9da5-11e9-8110-e6055d5ad4ed.png)

**Comment by yjqz86** [comment] 2019-07-03 19:20
I hope this capture can help

![bugReactive](https://user-images.githubusercontent.com/8808566/60619177-14c38280-9da6-11e9-846d-ea596416f650.png)

**Comment by ryohlan** [comment] 2019-07-04 02:21
I found the cause.

This is issue for react-native-community/cli-platform-android. See below 

https://github.com/react-native-community/cli/blob/master/packages/platform-android/native_modules.gradle#L170

Update to `def command = "../node_modules/.bin/react-native config"`.

It works for me.

**Comment by kidandcat** [comment] 2019-07-04 09:05
I confirm it works with `def command = "../node_modules/.bin/react-native config"`.

**Comment by ryohlan** [comment] 2019-07-04 09:21
My solution is not correct.

This is auto linkikg issue. 

Read this comment. https://github.com/react-native-community/cli/issues/468#issuecomment-508340294

**Comment by kidandcat** [comment] 2019-07-04 09:28
It worker for me after a clean reinstall of JDK, react-native and my project node_modules (I'm using jdk11)

**Comment by kidandcat** [comment] 2019-07-04 09:30
No, it doesn't work without the change you proposed. I saw that issue, but my project is a clean install with react-native init, I haven't a different structure.

**Comment by thymikee** [comment] 2019-07-04 09:41
@kidandcat in default template, there's no `../node_modules/.bin/react-native`, it's `./node_modules/.bin/react-native`. Are you sure you didn't modify it/cache it somewhow?

**Comment by kidandcat** [comment] 2019-07-04 09:49
Yeah, in default template is `node ./node_modules/.bin/react-native` and it fails with `Text must not be null or empty`, I modified it to `../node_modules/.bin/react-native`

**Comment by thymikee** [comment] 2019-07-04 09:56
@kidandcat we recently released a fix for that. Please init once again and verify

**Comment by leejh1117** [comment] 2019-07-04 09:59
I was solved after install @react-native-community/cli

**Comment by kidandcat** [comment] 2019-07-04 10:01
Wow, that was very recently, I initialized it yesterday. Thanks @thymikee its working now!

**Comment by thymikee** [comment] 2019-07-04 10:12
Closing as resolved then :)

**Closed by thymikee** 2019-07-04 10:12 UTC
Labels: Bug, Ran Commands, Resolution: Needs More Information

**Comment by alindima** [comment] 2019-07-04 15:24
I have the same issue. What do you mean by "init once again"?

**Comment by thymikee** [comment] 2019-07-04 15:44
I referred to the fact that the faulty project was created through init yesterday, before a fix in the cli was published. What you can do in existing codebase is make sure @react-native-community/cli is at 2.0.2 version (check the lock file, remove the cli entry and reinstall packages so the newest version is fetched)

**Comment by acro5piano** [comment] 2019-07-06 03:00
For thoese who are working "standard" monorepo structure, like

```
packages/
  |- app1/
  |  |- package.json
  `- app2/
     |- package.json
```

```java
// app1/android/settings.gradle
apply from: file("../../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle");
applyNativeModulesSettingsGradle(settings, "../../../packages/app1");
```

```java
// app1/android/app/build.gradle
apply from: file("../../../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle");
applyNativeModulesAppBuildGradle(project, "../../../packages/app1");
```

I tried settings described [here](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#custom-root-monorepos-1) , then another error showed up:

```
A problem occurred evaluating settings 'Example'.
> Cannot get property 'packageName' on null object
```

Also, I checked `node_modules/@react-native-community/cli-platform-android/native_modules.gradle` and found config is wrong:

```
    this.packageName = json["project"]["android"]["packageName"]
```

```
{
  "root": "/path/to/myapp",
  "reactNativePath": "/path/to/myapp/node_modules/react-native",
  "dependencies": {},
  "commands": [],
  "assets": [],
  "platforms": {},
  "haste": {
    "providesModuleNodeModules": [],
    "platforms": []
  },
  "project": {}
}
```

So I came up to the solution.

**Comment by olistic** [comment] 2019-07-08 14:18
@acro5piano I'm on the same situation than you, but it's not clear to me from you message what is the solution that worked for you. Could you please give more details? Thanks :)

**Comment by acro5piano** [comment] 2019-07-08 15:39
@olistic I updated my comment above. I made it a little bit clear and fix some typos.

In short, 

- `applyNativeModulesSettingsGradle` will look up the output of `node ./node_modules/react-native/cli.js config`
- In monorepo projects, the output of the command is different from single package projects, because `cli.js` will always look up `../../` as project root

https://github.com/react-native-community/cli/blob/master/packages/platform-android/native_modules.gradle#L177

**Comment by olistic** [comment] 2019-07-08 16:08
@acro5piano Thank you! So basically what's different between what's explained [here](https://github.com/react-native-community/cli/blob/6df50eb42cb22d5992d0d7c79923b7f989719d17/docs/autolinking.md#custom-root-monorepos-1) and what ended up working for you is:

```patch
// app1/android/settings.gradle
-applyNativeModulesSettingsGradle(settings, "../../..")
+applyNativeModulesSettingsGradle(settings, "../../../packages/app1")
```

(and the analogous for `applyNativeModulesAppBuildGradle`)

For some reason that is not working for me. In my case, my monorepo structure doesn't have a `packages` directory, it's just:

```
.
├── node_modules  <- where `react-native` is installed.
├── api
├── native  <- the React Native app
├── web
├── lerna.json
└── package.json
```

When I was using 0.59, I followed [this tutorial](https://dev.to/brunolemos/tutorial-100-code-sharing-between-ios-android--web-using-react-native-web-andmonorepo-4pej) which worked fine. With 0.60 and the new CLI 2.0 I was trying to apply those same steps plus some variations I found necessary, but I'm stuck at this point. I will keep researching.

**Comment by acro5piano** [comment] 2019-07-08 16:29
@olistic 
You're welcome! 

> Thank you! So basically what's different between what's explained here and what ended up working for you is:

Yes.
I think `applyNativeModulesSettingsGradle(settings, "../../../native")` will work, but React Native projects tend to be subjected to our "versions".
Actually I had another problem after I updated from 0.57.7 to 0.60.0 and clouldn't solve, so I finally dicided to update to 0.59.10.
I will wait enough information for upgrading to 0.60.0 as the version is still quite a new release.

Thank you for your researching. Good luck.

**Comment by thymikee** [comment] 2019-07-08 17:20
@acro5piano @olistic I've updated the autolinking guide to provide some more information about how it's set up currently in the default template and when having custom root: https://github.com/react-native-community/cli/pull/505. Hope that clears some confusions. If you have ideas on how to make it more approachable, I'd be glad to include them :)

**Comment by mattijsf** [comment] 2019-07-17 08:36
I also got the `Cannot get property 'packageName' on null object`.

We have two separate repo for Android / iOS with each a submodule pointing towards the shared `react-native` git submodule.

This the structure on the Android project:

```shell
root/
  |- app/
    |- build.gradle
  |- setting.gradle
  |- react-native/ (git submodule)
    |- node_modules/
    |- package.json
```


Given the above structure, this is how I defined my gradle files:

`settings.gradle`:
```groovy
apply from: file("react-native/node_modules/@react-native-community/cli-platform-android/native_modules.gradle")
applyNativeModulesSettingsGradle(settings, "react-native/")
```

`build.gradle`:
```groovy
apply from: file("../react-native/node_modules/@react-native-community/cli-platform-android/native_modules.gradle")
applyNativeModulesAppBuildGradle(project, "react-native/")
```

I believe the paths above are correct for that project structure because otherwise I get the `Text must not be null or empty` message.

Any help is welcome 👍

**Comment by thymikee** [comment] 2019-07-17 08:59
@mattijsf your project structure is not quite common. CLI can't figure out where you android project is. Try running `yarn react-native config` and see the output, the `project` needs to be populated. You should find this docs helpful in adjusting the `project` config: https://github.com/react-native-community/cli/blob/master/docs/projects.md.

**Comment by DylanVann** [comment] 2019-07-21 01:42
I still can't make the `packages/Project` setup work.

I made a repo trying to do it. Here is the commit modifying `build.gradle` and `settings.gradle` - https://github.com/DylanVann/react-native-monorepo-example/commit/e4bea7801dee2d19a17a29f93ce48725aaf3fee8

With this setup I still get:

```
A problem occurred evaluating settings 'DemoProject'.
> Text must not be null or empty
```

![image](https://user-images.githubusercontent.com/1537615/61585967-31e2aa00-ab37-11e9-8436-404bc5f5d7a1.png)

**Comment by ldco2016** [comment] 2019-07-31 19:02
Okay I just read everything above and I find it clear as mud. Sorry, perhaps someone can provide clarity.

I have this error in my Jenkins build only:

```
13:18:22 FAILURE: Build failed with an exception.
13:18:22 
13:18:22 * Where:
13:18:22 Script '/Users/nfib/Jenkins/Jenkins-Workspaces/ENGA/ENGAL/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 190
13:18:22 
13:18:22 * What went wrong:
13:18:22 A problem occurred evaluating settings 'NFIBEngage'.
13:18:22 > Text must not be null or empty
```

Others mentioned something about `app/build.gradle`, here is the relevant part of mine:

```
// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
```

Mention was also made of `android/settings.gradle`, this one is mine:

```
rootProject.name = 'NFIBEngage'
include ':react-native-device-info'
project(':react-native-device-info').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-device-info/android')
include ':appcenter-crashes'
project(':appcenter-crashes').projectDir = new File(rootProject.projectDir, '../node_modules/appcenter-crashes/android')
include ':appcenter-analytics'
project(':appcenter-analytics').projectDir = new File(rootProject.projectDir, '../node_modules/appcenter-analytics/android')
include ':appcenter'
project(':appcenter').projectDir = new File(rootProject.projectDir, '../node_modules/appcenter/android')
include ':react-native-webview'
project(':react-native-webview').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-webview/android')
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'
```

So what exactly is wrong here and how do I fix it?

**Comment by implsoftware** [comment] 2019-08-03 19:45
Still able to reproduce the issue with v2.8.3. Should this be re-opened since there are still a few folks experiencing the issue - @thymikee ?

**Comment by thymikee** [comment] 2019-08-04 16:30
I'm not gonna reopen this. People face this issue for different reasons. Please create a new issue with a detailed description and a repro we can download and investigate.

**Comment by implsoftware** [comment] 2019-08-04 17:52
Will do, thx

**Comment by ldco2016** [comment] 2019-08-07 02:25
> I referred to the fact that the faulty project was created through init yesterday, before a fix in the cli was published. What you can do in existing codebase is make sure @react-native-community/cli is at 2.0.2 version (check the lock file, remove the cli entry and reinstall packages so the newest version is fetched)

I tried this and the newest version is not fetched, it continues to fetch version `^2.0.1`.

**Comment by conor909** [comment] 2019-09-30 20:08
@mattijsf did you get any further? I'm also getting
`Cannot get property 'packageName' on null object` now.

My structure is a more usual yarn workspaces setup:
```
root
  |-  package.json
  |-  node_modules
  |-  packages
      |-  mobile
          |-  android
          |-  ios
      |- web
      |-  shared-components
```

So my fixes were:
`/settings.gradle`
```
apply from: file("../../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle");
applyNativeModulesSettingsGradle(settings, '../../../')
```
`app/build.gradle`
```
apply from "../../../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle";
applyNativeModulesAppBuildGradle(project, '../../')
```

**Comment by peterng014** [comment] 2019-10-03 04:39
I confirm it works with def command = "../node_modules/.bin/react-native config"
react-native: 0.61.2

**Comment by runny2018** [comment] 2019-10-13 08:50
> I found the cause.
> 
> This is issue for react-native-community/cli-platform-android. See below
> 
> https://github.com/react-native-community/cli/blob/master/packages/platform-android/native_modules.gradle#L170
> 
> Update to `def command = "../node_modules/.bin/react-native config"`.
> 
> It works for me.

Where do we put this 'def command' line??

**Comment by sumudu-dewasurendra** [comment] 2019-10-16 13:17
@runny2018 edit **native_modules.gradle** file located at _..\node_modules\@react-native-community\cli-platform-android_

**Comment by thymikee** [comment] 2019-10-16 13:30
Instead of mangling in node_modules, please [update the `@react-native-community/cli`](https://github.com/react-native-community/cli#updating-the-cli) to the latest version. We've recently improved the way we handle running configuration from native modules, which likely fixes your issues.

**Comment by sgeier** [comment] 2019-10-16 21:38
Unfortunately upgrading the cli doesn't fix the problem. 

I am including in the settings.gradle at the bottom: 
`apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)`

The error message produced is: 
`org.gradle.internal.exceptions.LocationAwareException: Script '/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 182`

```
Caused by: java.lang.IllegalArgumentException: Text must not be null or empty
	at ReactNativeModules.getReactNativeConfig(/Users/geier/Projects/react-native-tabby2/node_modules/@react-native-community/cli-platform-android/native_modules.gradle:182)
```

Line 182 boils down to:
` def json = new JsonSlurper().parseText(reactNativeConfigOutput)`

I verified I had the latest version:
```
 UNMET PEER DEPENDENCY react-native@0.61.2
  └── @react-native-community/cli@3.0.0-alpha.7
```
Any help appreciated.

**Comment by thymikee** [comment] 2019-10-17 07:33
@sgeier please create a new issue in https://github.com/react-native-community/cli/ repo, with a minimal reproduction of your project structure. Otherwise we can't help.

**Comment by sgeier** [comment] 2019-10-17 12:32
In another thread grabbou wrote that this error comes up when "project.android" is not properly set or something. Can you point me to where this config is read out?
Thanks

**Comment by borapop** [comment] 2019-10-22 13:23
@thymikee double check that there is no `react-native-cli` in `package.json`. If there is, remove it.

**Comment by lucasfjportela** [comment] 2019-10-25 18:07
@borapop thank you so much!!

**Comment by laogui** [comment] 2019-11-05 12:06
It happened in `cli-platform-android@3.0.0-alpha.7`.

I create a new project with older version.
 `react-native init NewNativeProject --version 0.60.0`
then copyed file `cli-platform-android\native_modules.gradle` to my project.

It worked for me.

**Comment by Keurdange** [comment] 2019-12-31 11:49
> I was solved after install @react-native-community/cli
This works for me
