### ISSUE TITLE
Print: Entry, ":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by 2ez4salt** [facebook/react-native#21270] opened 2018-09-22 23:46 UTC
- [ ] Review the documentation: https://facebook.github.io/react-native
  - [ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
      Memory: 40.32 MB / 8.00 GB
      Shell: 3.2.57 - /bin/sh
    Binaries:
      Node: 10.10.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.3.0 => 16.3.0 
      react-native: ^0.57.1 => 0.57.1 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1

## Description
 developing app with RN,i can see my app on expo, it builds well , but when i want publish my app i need my "appname.xcodeproj" and its giving me  on compiling 1600 errors. when used "react-native run-ios" thats giving me :

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier Build/Products/Debug-iphonesimulator/"appname".app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by 2ez4salt** [comment] 2018-09-23 00:15
## Update
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
      Memory: 822.98 MB / 8.00 GB
      Shell: 3.2.57 - /bin/sh
    Binaries:
      Node: 10.10.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.3.0 => 16.3.0 
      react-native: ^0.57.1 => 0.57.1 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1

## Description

i updated my development enviroment

and now 
`Talha-MacBook-Pro:TusTTS talhasalt$ sudo react-native run-ios
03:12:29: Starting packager...
03:12:38: Starting simulator...`

he stucks there

**Comment by 2ez4salt** [comment] 2018-09-23 00:54
## Update

I updated my react-native package to last version.

if i write 
`sudo react-native run-ios`
it says
`03:43:31: Starting packager...
03:43:41: Starting simulator...` 

and its stucks here


and if i write firstly
`Talha-MacBook-Pro:TusTTS talhasalt$ sudo react-native eject'
<img width="1428" alt="adsiz" src="https://user-images.githubusercontent.com/29352794/45923064-543e7380-bee4-11e8-84ce-d14ce1fae99f.png">

**Comment by alexandrius** [comment] 2018-09-23 13:03
This may sound super weird but the issue resolved after I removed react-native-maps and then installing it again. Might be coincidence

**Comment by arifrhkim** [comment] 2018-09-24 01:58
I've got the same error here, is this issue come from the version of xcode ?

**Comment by 2ez4salt** [comment] 2018-09-24 08:40
> I've got the same error here, is this issue come from the version of xcode ?

i dont think so cus i had this issue on old xcode

**Comment by ChrisXu** [comment] 2018-09-24 14:43
@2ez4salt , Are you able to open the project in Xcode? It seems like the project setting is damaged

**Comment by rottenoats** [comment] 2018-09-24 16:20
I created a fresh project and have the exact same thing occuring.
```
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 182.57 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 23.0.1, 23.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3
        API Levels: 23, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4670197
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.1 => 0.57.1
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

**Comment by georgelovegrove** [comment] 2018-09-24 17:13
Just my two cents on this, i've tried every idea from multiple issues on the XCode 10 update but none worked.

My work around for the meantime was to delete XCode 10, re-download 9.4.1 from https://developer.apple.com/download/more/ install and restart. Make sure to double check the command line tool is 9.4.1 in XCode => Preferences => Locations => Command line tools.

My project still didn't work after doing that so I tried downloading another copy of my project from github, npm installed and added env files and then this did build. Doubled checked the original project folder again and this still didn't work. XCode 10 may have changed the XCode file itself which for the meantime is broken (at least I couldn't find a solution for now).

**Comment by hramos** [comment] 2018-09-24 22:17
The _Print: Entry, ":CFBundleIdentifier", Does Not Exist_ message is sort of a red herring. This line of text will always print out whenever the project fails to launch for _whatever_ reason. This is very confusing as developers tend to bundle "CFBundleIdentifier" failures into one, which makes it hard to find actual workarounds.

For anyone who ends up here because of a "CFBundleIdentifier" error, please look back through your logs as the actual failure most likely happened earlier in the build process.

**Comment by hramos** [comment] 2018-09-24 22:46
Duplicate of #21303

**Closed by hramos** 2018-09-24 22:46 UTC
Labels: 📦Bundler
