### ISSUE TITLE
Android 'elevation' style property causes YellowBox to render behind elements with elevation > 0

### ISSUE THREAD

**Issue by cailenmusselman** [facebook/react-native#11778] opened 2017-01-08 18:54 UTC
### Description

Android 'elevation' style property effects the z-index of components. Therefore, even if the YellowBox component is rendered last, it is still hidden by other components with a elevation > 0.  I noticed this when trying to render a persistent bottom bar in my app. The worst part is that the bottom bar displays above the 'dismiss' / 'dismiss all' buttons of the yellow box inspector.

### Reproduction

```
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

export default class AwesomeProject extends Component {
  render() {
    console.warn('row 1');
    console.warn('row 2');
    console.warn('row 3');
    console.warn('row 4');
    return (
      <View style={styles.container}>
        <Text style={styles.push}>
            Push next view to bottom
        </Text>
        <Text style={styles.hideYellowBox}>
            I hide a yellow box row (and the dismiss button once the yellowbox inspector is opened)
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1
  },
  push: {
    flex: 1
  },
  hideYellowBox: {
    flex: 0,
    elevation: 5,
    padding: 10,
    backgroundColor: 'green'
  },
});

AppRegistry.registerComponent('AwesomeProject', () => AwesomeProject);
```

### Solution

https://github.com/facebook/react-native/pull/11777

Give the YellowBox the maximum possible elevation.

### Additional Information

* React Native version: 0.39
* Platform: Android
* Operating System: Windows

**Comment by ericvicenti** [comment] 2017-01-09 10:23
Ok I've landed the fix. Please re-open if the issue isn't fully resolved!

**Closed by ericvicenti** 2017-01-09 10:23 UTC
