### ISSUE TITLE
* Where: Script 'C:\Users\stars\Desktop\okbosstasker\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 426  * What went wrong: A problem occurred evaluating script. > Calling `[node, C:\Users\stars\Desktop\okbosstasker\node_modules\@react-native-community\cli\build\bin.js, config]` finished with an exception. Error message: groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object

### ISSUE THREAD

**Issue by vengat180497** [facebook/react-native#38465] opened 2023-07-17 11:13 UTC
### Description

When I am Run the react-native run-android comment while I am getting below error

BUILD FAILED in 5s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\stars\Desktop\okbosstasker\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 426

* What went wrong:
A problem occurred evaluating script.
> Calling `[node, C:\Users\stars\Desktop\okbosstasker\node_modules\@react-native-community\cli\build\bin.js, config]` finished with an exception. Error message: groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object

  The current character read is 'i' with an int value of 105
  Unable to determine the current character, it is not a string, number, array, or object
  line number 1
  index number 0
  info Run CLI with --verbose flag for more details.
  ^. Output: info Run CLI with --verbose flag for more details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

    at makeError (C:\Users\stars\Desktop\okbosstasker\node_modules\react-native\node_modules\execa\index.js:174:9)
    at C:\Users\stars\Desktop\okbosstasker\node_modules\react-native\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (C:\Users\stars\Desktop\okbosstasker\node_modules\react-native\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (C:\Users\stars\Desktop\okbosstasker\node_modules\@react-native-community\cli\build\index.js:142:9)
info Run CLI with --verbose flag for more details.

### React Native Version

react-native": "0.70.6"

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
    Memory: 1.17 GB / 7.91 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 9.1.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 18.0.2.1
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.6 => 0.70.6
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

I tried cd android && ./gradle clean and deleted node_modules and install Those are not working

### Snack, code example, screenshot, or link to a repository

![Screenshot 2023-07-17 164128](https://github.com/facebook/react-native/assets/97938641/3bad86d4-bd14-49ef-be66-ab6e2c433a00)
![Screenshot 2023-07-17 164230](https://github.com/facebook/react-native/assets/97938641/51098820-213d-4d8b-9a73-96324a084a93)
![Screenshot 2023-07-17 164255](https://github.com/facebook/react-native/assets/97938641/d30926fa-249f-482c-be48-3cd473e2807e)

**Comment by cortinico** [comment] 2023-07-17 12:56
Duplicate of:
https://github.com/react-native-community/cli/issues/1981#issuecomment-1637890468

**Closed by cortinico** 2023-07-17 12:56 UTC
Labels: Platform: Android, Needs: Triage :mag:, Newer Patch Available
