### ISSUE TITLE
RN android sdk throw JSApplicationIllegalArgumentException then crashed randomly

### ISSUE THREAD

**Issue by fred-ye** [facebook/react-native#33400] opened 2022-03-09 11:24 UTC
### Description

com.facebook.react.bridge.JSApplicationIllegalArgumentException: Animated node with tag 431 does not exists
at com.facebook.react.animated.NativeAnimatedNodesManager.connectAnimatedNodes(NativeAnimatedNodesManager.java:322)
com.facebook.react.animated.NativeAnimatedModule$15.execute(NativeAnimatedModule.java:681)
com.facebook.react.animated.NativeAnimatedModule.executeAllOperations(NativeAnimatedModule.java:258)
com.facebook.react.animated.NativeAnimatedModule.access$400(NativeAnimatedModule.java:85)
com.facebook.react.animated.NativeAnimatedModule$3.execute(NativeAnimatedModule.java:287)
com.facebook.react.uimanager.UIViewOperationQueue$UIBlockOperation.execute(UIViewOperationQueue.java:573)
com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:908)
com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1019)
com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1079)
com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)

### Version

0.64.2

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 11.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 35.73 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.4 - ~/.nvm/versions/node/v12.18.4/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.18.4/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.4/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /Users/caimingchao/.rvm/rubies/ruby-2.7.2/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 24, 25, 26, 28, 29, 30, 31
      Build Tools: 23.0.3, 26.0.0, 28.0.2, 28.0.3, 29.0.2, 29.0.3, 30.0.3
      System Images: android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_181 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.2 => 0.64.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

App crashes randomly in Android, can not reproduce manually

I found this kind crash seems only happed on android 12, level 31

### Snack, code example, screenshot, or link to a repository

no

**Comment by zhuanghongji** [comment] 2022-03-11 01:20
I check all kind of this crash log, and confirm that it only happen on android 12, level 31

**Comment by mayankyadav-zepto** [comment] 2022-03-18 17:57
Looked at Sentry logs of my RN app on production.

Here are the list of device models on which this crash is happening.

`[
    'SM-G970F', 'SM-N970F', 'SM-F700F', 'SM-G990E', 'SM-G988B', 'SM-S908E',
    'SM-G991B', 'SM-G780F', 'SM-A725F', 'SM-G996B', 'SM-G975F', 'SM-G980F', 'SM-G770F', 'SM-N770F',
    'SM-G973F', 'SM-G985F', 'SM-N975F', 'SM-N980F', 'SM-A528B', 'SM-A525F', 'SM-F711B', 'SM-G998B',
    'SM-G781B', 'SM-N986B'
  ]`

Hope this helps. For now disabling animation on these devices.

**Comment by yanxlg** [comment] 2022-03-25 02:32
Has anyone tried react-native@0.63.4? I found that some people said it would be OK to reduce from 64 to 63.

**Comment by rachitmishra** [comment] 2022-05-26 10:19
Issue is reproducible on RN 0.63.4 too.

**Comment by herbertfuchs** [comment] 2022-05-30 13:27
having the same issue here, all of them on android 12

**Comment by cortinico** [comment] 2022-06-16 21:18
This is a duplicate of #33375 Closing it so we have all the information on the same issue

**Closed by cortinico** 2022-06-16 21:18 UTC
Labels: Platform: Android, Needs: Triage :mag:
