### ISSUE TITLE
The name of the given podspec 'glog' doesn't match the expected one 'GLog'

### ISSUE THREAD

**Issue by ahmetilhann** [facebook/react-native#18618] opened 2018-03-29 12:46 UTC
- [ ] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [ ] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
OS: macOS High Sierra 10.13.3
Node: 9.2.1
Yarn: Not Found
npm: 5.6.0
Watchman: 4.9.0
Xcode: Xcode 9.2 Build version 9C40b
Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.0-rc.0 => 16.3.0-rc.0
  react-native: ^0.54.3 => 0.54.3

## Steps to Reproduce
1- I created new project `react-native init appName`
2- `cd ios && pod init`
3- `pod install`
4- Then this error occurs ``[!] The name of the given podspec `glog` doesn't match the expected one `GLog` `` 

## Expected Behavior

I have worked npm cache clean --force many times. I have worked npm install many times. it was the same error.

## Actual Behavior
My Podfile: 

````
platform :ios, '8.0'

target 'appName' do
  
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    
  ]
 
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'GLog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

end
````

After `pod install`
<img width="871" alt="ekran resmi 2018-03-29 15 37 00" src="https://user-images.githubusercontent.com/5680957/38089443-19ed12de-3368-11e8-83aa-e42d32d1366b.png">

**Comment by hramos** [comment] 2018-03-29 16:20
This is fixed in master.

Duplicate of #16181

**Closed by hramos** 2018-03-29 16:20 UTC
Labels: :small_blue_diamond:macOS
