### ISSUE TITLE
Curated list of open source React Native apps in docs

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#6887] opened 2016-04-08 20:54 UTC
Something like the showcase but only for open source apps -- doesn't require them to be published to app store or anything. Feel free to implement if you are interested!

Idea via @jordwalke - https://twitter.com/jordwalke/status/718541198122569728

**Comment by geirman** [comment] 2016-04-08 22:04
I've been bookmarking examples I come across, so this might be a good starting point...

1. https://github.com/asamiller/den
2. https://github.com/facebook/react-native/tree/master/Examples/UIExplorer
3. https://github.com/christopherdro
4. https://github.com/brentvatne/react-native-login
5. https://github.com/tylermcginnis/react-native-gh-notetaker
6. https://github.com/jordanbyron/house_control
7. https://github.com/iSimar/HackerNews-React-Native
8. https://github.com/race604/ZhiHuDaily-React-Native
9. https://github.com/bgryszko/react-native-example
10. https://github.com/kenwheeler/reactive2015
11. https://github.com/browniefed/rncontest
12. https://github.com/dzannotti/reactive2015
13. https://github.com/Kureev/Reactive2015
14. https://github.com/brainattica/react-native-movies-app
15. http://www.reactnative.com/ioss-stock-app-clone-written-in-react-native-for-demo-purpose/
16. http://tech.taskrabbit.com/blog/2015/09/21/react-native-example-app/
17. https://github.com/HugoDF/beercalculatorapp
18. https://github.com/fraserxu/soundredux-native#app-example
19. https://github.com/benoitvallon/react-native-nw-react-calculator
20. https://github.com/realtime-framework/RCTRealtimeNews
21. https://github.com/DimitriMikadze/react-native-game
22. https://github.com/browniefed/flexboxfroggy
23. https://github.com/sonnylazuardi/ziliun-react-native
24. https://github.com/chentsulin/react-native-counter-ios-android
25. https://github.com/jsdf/ReactNativeHackerNews
26. https://github.com/akveo/react-native-reddit-reader
27. https://github.com/ennioma/react-native-premier-league
28. https://github.com/jondot/awesome-react-native#examples
29. https://github.com/hharnisc/react-native-meteor
30. https://github.com/tgoldenberg/meteor-react-native-chat-example
31. https://github.com/taskrabbit/ReactNativeSampleApp
32. https://github.com/hharnisc/react-native-meteor-websocket-polyfill
33. https://github.com/oney/iTunesConnect
34. https://github.com/reindexio/reindex-examples/tree/master/react-native-gallery
35. https://github.com/buildreactnative/assemblies

**Comment by jordwalke** [comment] 2016-04-08 22:45
That's great @geirman ! Thank you.

**Comment by brentvatne** [comment] 2016-04-08 23:25
A few more for you @geirman:

https://github.com/exponentjs/fluxpybird
https://github.com/exponentjs/react-native-for-curious-people
https://github.com/exponentjs/pomodoroexp

**Comment by dsibiski** [comment] 2016-04-09 11:00
Don't forget:

https://github.com/rnplay/rnplay-native

...and this one is a really nice example:

https://github.com/wwayne/react-native-nba-app

...and maybe even:

https://github.com/bartonhammond/snowflake

**Comment by geirman** [comment] 2016-04-10 09:09
@dsibiski good adds, especially the nba app which is a very rare non-trivial example... high quality too! I see snowflake as a different breed, which I generally think of as boilerplate or scaffolding. I've a few examples of those (in addition to snowflake) as well if they'd help...

1. https://github.com/jhabdas/react-native-webpack-starter-kit/blob/master/README.md
2. https://github.com/infinitered/react_native_base
3. https://github.com/rodrigopivi/playapp

**Comment by DanielMSchmidt** [comment] 2016-04-10 09:35
Is anyone currently building this page? If not I would be interested and build a new section to the showcase page.

**Comment by dsibiski** [comment] 2016-04-10 18:00
@DanielMSchmidt I don't think anyone has claimed it yet, take it away! :+1:

**Comment by DanielMSchmidt** [comment] 2016-04-10 19:20
I just opened a PR for this. I traversed all mentioned projects, but only found a few of them published to an app store so that I could get the App Icon. I think we should find another place and another format for the other examples; it was hard not to include the NBA App or Den. Maybe a link to https://github.com/jondot/awesome-react-native#examples in the showcase would be enough, but I learned a whole lot from looking at examples, so a more prominent place may be better suited.

**Comment by filipmares** [comment] 2016-04-14 16:39
The Facebook F8 app is open source: https://github.com/fbsamples/f8app

The perf is amazing. Great example.

**Comment by DanielMSchmidt** [comment] 2016-04-14 21:27
@brentvatne @jordwalke @dsibiski  Could one of you give me a hint what would need to happen to have this PR shipped? :) I am just not sure what to do and need some guidance.

**Comment by alwx** [comment] 2016-05-26 00:39
https://github.com/alwx/luno-react-native
Probably the only complete ClojureScript-based example.

**Comment by geirman** [comment] 2016-07-08 13:44
# An Idea for Discussion 

What if we used the [react native showcase ](http://facebook.github.io/react-native/showcase.html) for this list as well? To do this, we'd need to add a `githubLink` definition to the [showcase definition file](https://github.com/facebook/react-native/blob/master/website/src/react-native/showcase.js), then we could link directly to the source code of each app coded in the open. Something like this perhaps (note the github link)...

![image](https://cloud.githubusercontent.com/assets/1640318/16689169/71870f36-44d6-11e6-8af5-bf25a4882a09.png)


I know we're trying to focus the showcase on premium, high-quality apps now, which makes sense. But why not do that while also being the single reference point for all apps? We can add a `bestOf` or `premiumApp` or similar designator to the file as well, which would allow us to float those apps to the top, placing them front and center. Then we could add a link to the bottom to view the exhaustive list of all apps...

Then, if we added a filter to the top similar to the one we have on the getting started page, users could quickly get to the content they're after (though it would be nice if they could view any app that is all three, iOS, Android, and Github)...

![image](https://cloud.githubusercontent.com/assets/1640318/16689304/30403894-44d7-11e6-9306-6eba7e6b5f57.png)

Thoughts?

**Comment by geirman** [comment] 2016-07-13 13:57
Here's another list...
https://github.com/maxenceC/open-source-react-native-apps

**Comment by DanielMSchmidt** [comment] 2016-07-13 14:04
@geirman I tried to build this in #6904 but it is quite hard to do so if there is not enough feedback, simply because due to many changes to the showcase it is almost always outdated in your branch.
In addition, please bear in mind that there are many excellent examples of React Native Applications which are not in the app store and therefore have no logo.

Nevertheless, I still think it would be nice to have such a list, especially with the filter. Maybe we could have a dedicated section with the open source apps without logo, which in only a list or link to a list of those for additional examples

**Comment by geirman** [comment] 2016-07-13 14:19
@DanielMSchmidt I agree, a filter(able) list without logo would be great. If we wanted to use the same JSON file, then it's probably okay if only the top-n apps with icons are given premier placement (with icon) at the top... then perhaps link to "more" or "all" for a simple list. 

Rather than spelling out "iOS" and "Android", it would be better scannable if we used each platform's recognizable icons don't you think? Something like this (though obviously not so large! ha!).

![image](https://cloud.githubusercontent.com/assets/1640318/16806543/bfaeb960-48c9-11e6-92d5-e5186db272de.png)

A dedicated section would definitely work too. Just though maybe it would be easier to maintain (and find) if they were all in one place, but maybe not.

**Comment by GantMan** [comment] 2016-10-07 13:56
Is this still on the table @DanielMSchmidt _et al._?   If so, I'd love to PR this task.

**Comment by geirman** [comment] 2016-10-07 15:27
@gantman AFAIK, this is just waiting for a champion to take lead.

**Comment by DanielMSchmidt** [comment] 2016-10-07 15:45
If you assign me someone who is willing to have a look at it as soon as it's done I would be willing to do it, but the problem last time was, that holding a PR open in this ever-changing region of the code requires a lot of work and is very error prone. I would love to do the work once and get the PR quickly merged ;)

**Comment by lacker** [comment] 2016-10-25 01:41
So we have been updating the "showcase" area a bunch, "we" meaning @hramos really. I think the way it is set up right now is pretty good, with the recent changes to have some top tier apps on the home page and some larger list on the "showcase". It's kind of a cesspit for arguments about "what app is showcaseworthy" and we have converged on something maintainable as is so I think a better outlet for this would be some list that is independent of the main RN website that someone just maintains themselves. A la one of those "Awesome X" repos. So, I'm going to close this issue roughly as "working as intended" but I encourage people to make independent lists and share and so on.

**Closed by lacker** 2016-10-25 01:41 UTC
Labels: Community Responsibility, Good First Task, Help Wanted

**Comment by geirman** [comment] 2016-10-25 06:42
I'm disappointed, but I get it. This has lingered long enough. However, @DanielMSchmidt had offered to do the work, but not if the PR would linger unreviewed. He reasonably asked that someone pay attention if he made the effort. Seems fair.

**Comment by lacker** [comment] 2016-10-26 00:42
Yeah, I really appreciate everyone's willingness to put in some effort here. I just think that at this point, we do not need additional curated lists of apps on the React Native website, and the setup with a list on the homepage and another list on the showcase is enough. I think a great thing to do with extra lists would be to put them on places that aren't the React Native website.

**Comment by hramos** [comment] 2016-10-26 00:58
The folks at Deco are running a separate showcase that aims to list every app in production. While it doesn't currently list non-production sample apps, it's still worth mentioning: https://www.decosoftware.com/showcase

**Comment by geirman** [comment] 2016-10-26 02:04
Thanks, @hramos! I wasn't aware of their list. For their showcase, I'd really just want to see apps that were built with their IDE, but maybe that's just me :)

**Comment by GantMan** [comment] 2016-10-29 02:03
Chatting with Deco software to see if we can get a community driven showcase that's managed by community:  React Native Newsletter is being transferred here, so it makes sense.

https://github.com/ReactNativeNews

**Comment by geirman** [comment] 2016-10-29 02:18
Awesome! The ReactNativeNews might be a great place for an Awesome React Native list too :)

**Comment by dabit3** [comment] 2016-11-04 19:07
Ok, after talking with @GantMan we set this up here https://github.com/ReactNativeNews/React-Native-Apps

**Comment by geirman** [comment] 2016-11-04 19:17
@dabit3 that'll work. Does it make sense to add a link added on the [react native showcase](http://facebook.github.io/react-native/showcase.html) page to make it more easily discoverable?

**Comment by GantMan** [comment] 2016-11-04 19:19
@dabit3 did an awesome job!  I'm sure we'll be getting more feedback.   

@geirman - That sounds good!  You going to do that PR?

**Comment by geirman** [comment] 2016-11-04 19:38
@GantMan sure, since you agree... I'll submit the PR
