### ISSUE TITLE
M1 iOS16 new Date = NaN

### ISSUE THREAD

**Issue by 13387564366** [facebook/react-native#34984] opened 2022-10-14 09:30 UTC
### Description

console.log('--2022-07-08---', new Date('2022-07-08'))
console.log('--2022/07/08---', new Date('2022/07/08'))
 LOG  --2022-07-08--- 2022-07-08T00:00:00.000Z
 LOG  --2022/07/08--- Date { NaN }

### Version

0.70.3

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 540.56 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
    Watchman: 2022.10.03.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 31, 33
      Build Tools: 30.0.3, 31.0.0, 33.0.0
      System Images: android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_342 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.3 => 0.70.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

console.log('--2022-07-08---', new Date('2022-07-08'))
console.log('--2022/07/08---', new Date('2022/07/08'))
 LOG  --2022-07-08--- 2022-07-08T00:00:00.000Z
 LOG  --2022/07/08--- Date { NaN }

### Snack, code example, screenshot, or link to a repository

console.log('--2022-07-08---', new Date('2022-07-08'))
console.log('--2022/07/08---', new Date('2022/07/08'))
 LOG  --2022-07-08--- 2022-07-08T00:00:00.000Z
 LOG  --2022/07/08--- Date { NaN }

**Comment by cortinico** [comment] 2022-10-14 18:57
Closing as the issue is incomplete. Please spend some time describing what's the expected behaviour vs the actual and reopen the issue. Thank you 👍

**Closed by cortinico** 2022-10-14 18:57 UTC
Labels: Platform: iOS, Needs: Triage :mag:
