### ISSUE TITLE
react-native build failed: Xcode 7.2.1, react-native cli v : 2.0.1 (MacOSX 10.10.5)

### ISSUE THREAD

**Issue by illianyh** [facebook/react-native#12734] opened 2017-03-06 07:29 UTC
I'm new to react native. Initialised a new project by running react-native init project-name and then running it on Xcode but the build was failed....again and again. 

By looking at solutions posted by other users, I commented out this line of code : 

**//    case UIUserInterfaceIdiomCarPlay:
//      return @"carplay";**

That's one issue solved, but then when I tried to build the project it gave me another error:

![error screenshot](https://cloud.githubusercontent.com/assets/7670470/23600425/7bd9f96c-0281-11e7-9e91-0dcc6022e5e6.png)

Please can someone help me out. I have no idea what went wrong.

**Comment by hramos** [comment] 2017-03-06 18:21
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-03-06 18:21 UTC

**Comment by illianyh** [comment] 2017-03-07 00:53
This is the worst help ever. At least let me provide details before closing the freaking issue. Wow.

**Comment by hramos** [comment] 2017-03-07 01:15
The template is visible when you open a new issue. Feel free to open a new issue, just make sure to follow instructions so we can better help you. Thanks.
