### ISSUE TITLE
ViewPagerAndroid native prop error

### ISSUE THREAD

**Issue by Ehesp** [facebook/react-native#10519] opened 2016-10-24 08:34 UTC
### Issue Description

Using ViewPagerAndroid throws an error:

![image](https://cloud.githubusercontent.com/assets/842078/19638652/c8b15c1c-99cc-11e6-98ce-fc5522ae7769.png)

### Steps to Reproduce / Code Snippets

```javascript
return (
    <ViewPagerAndroid
      initialPage={0}
    >
      <View>
        <Text>First page</Text>
      </View>
      <View>
        <Text>Second page</Text>
      </View>
    </ViewPagerAndroid>
  );
```

### Additional Information

* React Native version: 0.35.0
* React Version: 15.3.2
* Platform(s) (iOS, Android, or both?): Android
* Operating System (macOS, Linux, or Windows?): MacOS

**Comment by leeight** [comment] 2016-10-24 10:15
Restart the packager server?

**Comment by lacker** [comment] 2016-10-24 23:35
It looks like your versions of native code and JS code are out of sync. I would try restarting everything, including the packager server. The litmus test is whether you can reproduce this on rnplay.org - if you can, there's a real bug. If you can't, then it's probably something awry on your local machine, so try blowing away everything and rerunning. I'm going to close this issue but feel free to open a new one if you can indeed repro this.

**Closed by lacker** 2016-10-24 23:35 UTC

**Comment by Ehesp** [comment] 2016-10-27 18:28
@lacker I've removed node_modules, uninstalled the app, restarted installer and reinstalled the app... Same issue!

I just get a white screen on rnplay (https://rnplay.org/apps/7tsKaA) with a very basic example, not sure if thats related or I'm being stupid.

**Comment by Ehesp** [comment] 2016-10-27 18:50
I've restarted my mac, cleared watchman cache, npm cache, tried Android APIs 23 & 24. Same issue.

**Comment by ide** [comment] 2016-10-27 19:18
Did you try deleting your app's data (this is different than uninstalling your app on some phones), uninstalling your app, and reinstalling? I agree with @lacker I think there is most likely some bad state on your computer/devices, maybe in your code base, but I haven't seen signs the issue is with RN itself.

**Comment by Ehesp** [comment] 2016-10-27 19:44
Okay so I managed to get it working... I had to delete my android directory and running `react-native android`, then linking back up my other libs. Seems something funky happened, probably when I upgraded to the latest build!

Cheers guys

**Comment by Ehesp** [comment] 2016-11-02 14:49
@ide I just installed a new package (with yarn). When I restarted the packager and reinstalled the app I got this error again.

If I remove my `android` directory and run `react-native android`, restart everything it works. However, I now add the "ACCESS_NETWORK_STATE" to AndroidManifest, restart and get this exact error again.

Why would such a simple change cause this?

**Comment by Salakar** [comment] 2016-11-02 15:19
@Ehesp @ide @lacker I'm also experiencing this exact issue,

This happens every time after installing a new module to package.json I've tried the following:

 - Restarted Packager.
 - Deleted `.gradle`, `build`, and `app/build` directories.
 - Deleted `$HOME/.gradle` directory.
 - watchman del
 - Wiped emulator 'user data'
 - Fresh new emulator
 - `-- --reset-cache` on bundler/packager start script.
 - Deleting android directory and running `react-native android` to rebuild the directory.

None of those have worked. Only way I can get it to work each time is `react-native init` to make a new project and then move all my files over... =/

Any ideas?
