### ISSUE TITLE
React Native 0.67~0.69.    Could not create service of type FileHasher using BuildSessionServices.createFileHasher().

### ISSUE THREAD

**Issue by wangyupeng993** [facebook/react-native#34257] opened 2022-07-23 18:13 UTC
### Description

* What went wrong:
Gradle could not start your build.
> Could not create service of type FileHasher using BuildSessionServices.createFileHasher().
   > Timeout waiting to lock file hash cache (/Volumes/HPP500/project/ReactNative/Cmpanda/android/.gradle/7.3.3/fileHashes). It is currently in use by this Gradle process.Owner Operation: unknown
     Our operation: 
     Lock file: /Volumes/HPP500/project/ReactNative/Cmpanda/android/.gradle/7.3.3/fileHashes/fileHashes.lock

### Version

ex. 0.69.2

### Output of `npx react-native info`

System:
    OS: macOS 12.4
    CPU: (8) x64 Intel(R) Core(TM) i7-8557U CPU @ 1.70GHz
    Memory: 56.42 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.1.2 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

npm run android

### Snack, code example, screenshot, or link to a repository

<img width="881" alt="image" src="https://user-images.githubusercontent.com/39769538/180617708-17005523-39d6-4a97-9e1f-a38eb27bdfad.png">
<img width="930" alt="image" src="https://user-images.githubusercontent.com/39769538/180617746-2c3afd7a-6782-4432-895a-f9f5df310661.png">

**Comment by cortinico** [comment] 2022-07-29 16:30
Essentially a duplicate of #34258 

Consider deleting the mentioned file by Gradle and build again

**Closed by cortinico** 2022-07-29 16:30 UTC
Labels: Needs: Triage :mag:

**Comment by hemanthAppmaker** [comment] 2023-05-05 11:20
Gradle could not start your build.
> Could not create service of type FileHasher using BuildSessionServices.createFileHasher().
   > Cannot lock file hash cache (/Users/eps95-hemanth/Desktop/mobileapps/epixel-commerce/android/.gradle/6.7/fileHashes) as it has already been locked by this process.


FIX:
stop the gradle

`./gradlew --stop`
Stopping Daemon(s)
1 Daemon stopped
