### ISSUE TITLE
TypeError: undefined is not a function (evaluating 'instance.render()')

### ISSUE THREAD

**Issue by jerinho** [facebook/react-native#22378] opened 2018-11-22 06:06 UTC
## Environment
- OS: Windows 10
- Node: 8.11.4
- Yarn: 1.9.4
- npm: 6.4.1
- react-native-cli: 2.0.1
- react-native: 0.57.5

## Description
TypeError: undefined is not a function (evaluating 'instance.render()')
This error is located at: in AppContainer (at renderApplication.js:33)

## Reproducible Demo

--- package.json ---

```
{
  "name": "test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "@babel/core": "^7.1.6",
    "babel-core": "^6.26.3",
    "react": "16.6.1",
    "react-native": "0.57.5"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.49.2",
    "react-test-renderer": "16.6.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

very simple. just "react-native run-android" and tada !!

**Comment by jerinho** [comment] 2018-11-22 10:14
> Can you run `react-native info` and edit your issue to include these results under the **Environment** section?
> 
> If you believe this information is irrelevant to the reported issue, you may write `[skip envinfo]` under **Environment** to let us know.

i hope you're really a real bot so i have good reason to not edit the required details you've asked. because i don't think any other info included from `react-native info` is needed to solve this issue

**Comment by anehkumar** [comment] 2018-11-26 18:43
Hi, Have you found any solution to this problem? I am facing the same problem

**Comment by jerinho** [comment] 2018-11-27 09:40
> Hi, Have you found any solution to this problem? I am facing the same problem

sadly no. i'd revert to RN 0.55.2

**Comment by Khalid-Nowaf** [comment] 2018-12-07 19:18
I have the same issue, using RN 0.57.7

**Comment by jerinho** [comment] 2018-12-10 23:08
finally i've found the solution. at least it works for me. i've moved to [here](https://flutter.io). it even teaches you how to migrate from here 😆

**Comment by duchunter** [comment] 2018-12-11 10:17
i dunno how but yarn add @babel/runtime or npm i -s @babel/runtime works for me

**Comment by abdulsalam90** [comment] 2018-12-31 12:32
same here, ` "react": "16.7.0",
    "react-native": "^0.57.8",`

**Comment by huytran123** [comment] 2019-01-02 08:02
The same issue when i init project on Window 10 with:
react: 16.6.3,
react-native: 0.57.8.
 I can not found solution it, please resolve it

**Comment by rosebless** [comment] 2019-01-09 17:45
any idea? i can't solve this problem. i try all comment but not work, and don't want to change react-native to flutter

**Comment by rosebless** [comment] 2019-01-09 17:48
any one know the cause of problem?

**Comment by bmwertman** [comment] 2019-01-10 20:06
I get;
 `TypeError: instance.render is not a function. (In 'instance.render()', 'instance.render' is undefined)`
`This error is located at: in AppContainer (at renderApplication.js:33)`

 running the versions @huytran123 provided.

**Comment by AgingChan** [comment] 2019-01-16 03:17
I have encountered the same error. Also tried to re-generate the ios/android code using `react-native eject` but no good.

Here is the output of `react-native info`

```
  React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
      Memory: 884.87 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.4 - ~/.nvm/versions/node/v8.11.4/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.11.4/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 26, 27, 28
        Build Tools: 26.0.2, 26.0.3, 27.0.3, 28.0.2
        System Images: android-23 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.57.08 => 0.57.8
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-asset: 1.1.2
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

**Comment by cassianomon** [comment] 2019-01-23 19:15
Using render as:
`render = () => {`

solved for me, but is it necessary? Even if I just return:

```
render() {
	return <View />
}
```

it returns me this error...

**Comment by bosz** [comment] 2019-01-24 03:46
My own error was coming up because i had no `render()` method in the class component. 

Maybe you add a render method and see if it works.

**Comment by liaopen123** [comment] 2019-02-22 07:38
I solved it .with:
* watchman watch-del-all
* rm -rf node_modules/.cache
* react-native start --resetCache

**Comment by friederbluemle** [comment] 2019-03-03 11:50
Geez, I just wasted about an hour until I figured out that the solution (at least for my problem), was:

    react-native start --resetCache

**Comment by marcelkalveram** [comment] 2019-03-06 21:06
@cassianomon suggestion to use the class field double arrow solved it for me as well:
`render = () => {` instead of `render() {`

**Comment by ferrannp** [comment] 2019-03-19 15:03
Hello there 👋 this issue has been reported for an old version of React Native. Ideally we'd like everyone to be using 0.59 (see the [awesome changes](https://facebook.github.io/react-native/blog/2019/03/12/releasing-react-native-059) it brought) but we know updating can be a pain. We are going to close this issue because it's from a version before 0.57, which is really old.

But please, if it's actually still an issue with 0.59 please comment below and we can reopen it 😊

**Closed by ferrannp** 2019-03-19 15:03 UTC
Labels: Type: Bug Report

**Comment by ptmt** [comment] 2019-04-14 17:46
Observing this after upgrading to `0.59.4` and removing all possible caches. It seems that I have to keep digging. replacing `render = () => {}` solves the problem, interesting why.

**Comment by ptmt** [comment] 2019-04-14 18:04
My issue was related to babel. Make sure you correctly upgraded babel, double check your root files (babel.config.js, package.json) by making `react-native init something` into separate folder if react-native-upgrade failed you.

**Comment by i6mi6** [comment] 2019-05-07 17:23
For react native 0.59 I ran `react-native init` inside a new folder, copied all babel dependencies, `.babelrc` and `babel.config.js` and updated those inside my project, then it worked like charm.

**Comment by budleigh** [comment] 2019-05-14 04:13
Seeing this with 0.59. I've tried 14 different babel presets, from just `preset-env` to `babel-preset-react-native` and the default `module:metro-react-native-babel-preset`. In all cases, replacing render with an arrow function fixes the issue, but fails otherwise.
