### ISSUE TITLE
Error when start without debug

### ISSUE THREAD

**Issue by IgorZh** [facebook/react-native#12477] opened 2017-02-20 15:31 UTC
Hello, I have a bug just after application started by command `react-native run-android`. Error appears when I switch off remote debug. With debugger all works correct.

### Description

```
Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `View`.
traverseAllChildrenImpl
    traverseAllChildren.js:183
traverseAllChildrenImpl
    traverseAllChildren.js:102
traverseAllChildren
    traverseAllChildren.js:218
instantiateChildren
    ReactChildReconciler.js:86
_reconcilerInstantiateChildren
    ReactMultiChild.js:179
mountChildren
    ReactMultiChild.js:249
initializeChildren
    ReactNativeBaseComponent.js:74
mountComponent
    ReactNativeBaseComponent.js:211
mountComponent
    ReactReconciler.js:61
performInitialMount
    ReactCompositeComponent.js:495
mountComponent
    ReactCompositeComponent.js:346
mountComponent
    ReactReconciler.js:61
performInitialMount
    ReactCompositeComponent.js:495
mountComponent
    ReactCompositeComponent.js:346
mountComponent
    ReactReconciler.js:61
performInitialMount
    ReactCompositeComponent.js:495
mountComponent
    ReactCompositeComponent.js:346
mountComponent
    ReactReconciler.js:61
mountComponentIntoNode
    ReactNativeMount.js:54
perform
    Transaction.js:149
batchedMountComponentIntoNode
    ReactNativeMount.js:77
perform
    Transaction.js:149
batchedUpdates
    ReactDefaultBatchingStrategy.js:65
batchedUpdates
    ReactUpdates.js:111
renderComponent
    ReactNativeMount.js:141
render
    ReactNative.js:31
renderApplication
    renderApplication.js:33
run
    AppRegistry.js:76
runApplication
    AppRegistry.js:105
__callFunction
    MessageQueue.js:236
<unknown>
    MessageQueue.js:108
guard
    MessageQueue.js:46
callFunctionReturnFlushedQueue
    MessageQueue.js:107
```

versions of libs

```
    "react-dom": "~15.3.2",
    "react-native": "^0.39.2",
```

**Comment by hramos** [comment] 2017-02-21 21:31
Did you address this warning?:

   Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `View`.

Also, see if this still happens on the most recent version.

**Comment by IgorZh** [comment] 2017-02-22 17:34
I think that error happend somewhere in library `redux-store`, because if I replace my root component in `index.android.js` by simple `View`, error still happend. By when I commet using of `redux-loop`, error disappears.

**Comment by hramos** [comment] 2017-02-22 19:30
Can you go back and make sure all the fields in the template are filled out? Right now, there is not sufficient information here for someone to reproduce what you're encountering, which greatly reduces the chances you will be able to get some help here.

Ideally, a GitHub issue would clearly outline a problem in React Native. Are you certain this is something that needs to be addressed in RN as opposed to another library you may be using in your project?

**Comment by brentvatne** [comment] 2017-02-22 22:59
As per @hramos' comment I think this is a problem with one of those libraries. If you can share the code it would be possible to verify that.

**Comment by hramos** [comment] 2017-02-22 23:37
I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-02-22 23:37 UTC

**Comment by hugomosh** [comment] 2017-08-22 00:04
@IgorZh did you manage to solve it?
I have the same error and just identify that it is indeed in the store or in the reducers.

**Comment by IgorZh** [comment] 2017-08-22 05:00
@hugomosh. Sorry, I can't help you. As I remember I found out that the error depends on some third-party lib, but I didn't solve it.

**Comment by hugomosh** [comment] 2017-08-27 06:42
We figure it out, for our case it turn down to be an *import*:  ```import
'babel-polyfill';```, to be precise, that made the error (it was part of
the example of some library). We remove it and it all went find.

**Comment by hugows** [comment] 2018-04-26 14:03
In my case turns out it was this import in my reducers file:

`import { Promise } from 'core-js';`

App only ran on debugging mode.
