### ISSUE TITLE
[Android][WebSocket] IllegalStateException: Listener failed to call close on message payload

### ISSUE THREAD

**Issue by Sh3rawi** [facebook/react-native#6370] opened 2016-03-08 22:58 UTC
This error, as we noticed, is crashing the app on a fair amount of devices on production. Almost all Sony and HTC devices with Lollipop face this crash very very frequently (we still don't know why).
But what we figured out is that we can reproduce this same exception if we open the app (and the socket by default) while applying an edge case of slow and lousy internet connection. 

Fatal Exception: java.lang.IllegalStateException: Listener failed to call close on message payload.
       at com.squareup.okhttp.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:222)
       at com.squareup.okhttp.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
       at com.squareup.okhttp.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:95)
       at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:171)
       at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:42)
       at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:102)
       at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:168)
       at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:856)

**Comment by grabbou** [comment] 2016-03-09 09:14
Looks like okhttp exception, have you tried filling in a bug report in their repo? https://github.com/square/okhttp

**Comment by Sh3rawi** [comment] 2016-03-09 10:44
I've seen that issue on their repo, but i don't  think that its from their side only.
Im no java expert, but if you see the solution proposed in the issue, its something added to the websocket object.
Also, after digging a bit into the code, there is something wrong that happens in the onMessage method of the react-native websocket listener, that causes this after returning : 
    messageClosed = false;
    frameCallback.onMessage(Okio.buffer(framedMessageSource), type);
    if (!messageClosed) {
      throw new IllegalStateException("Listener failed to call close on message payload.");
    }
And i couldn't figure out if this is a pure okhttp bug or something in the implementation here (the solution in the issue proposes the latter as i concluded).
What do you think ?

**Comment by gunters63** [comment] 2016-03-14 21:58
Is that not the error which will be fixed in 0.22rc?:

https://github.com/facebook/react-native/commit/a6a89fe4e08b6cf834df35cb176feac077234025

**Comment by Sh3rawi** [comment] 2016-03-16 11:48
No its not, the fix is for when sending a msg through a socket, not when reading from the socket.
The difference is that the code that handles writing has the try-catch in the RN implementation, while in the reading code, the check that happens before throwing the exception is done inside okhttp. 
If you look closely at the read code, you'll see that okhttp assumes the messageClosed var is changed inside the websocket that is listening, which is not happening in RN and thus throws the exception and the app crashes.

**Comment by mkonicek** [comment] 2016-07-29 23:11
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/androidwebsocket-illegalstateexception-listener-failed-to-call-close-on-message-payload

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Closed by mkonicek** 2016-07-29 23:11 UTC
Labels: Android, Icebox

**Comment by antoinerousseau** [comment] 2016-08-02 01:36
Any update on this? Still happening to me from time to time on my LG G3

```
Fatal Exception: java.lang.IllegalStateException: Listener failed to call close on message payload.
       at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:244)
       at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:108)
       at okhttp3.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
       at okhttp3.ws.WebSocketCall.createWebSocket(WebSocketCall.java:152)
       at okhttp3.ws.WebSocketCall.access$000(WebSocketCall.java:41)
       at okhttp3.ws.WebSocketCall$1.onResponse(WebSocketCall.java:97)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by Sh3rawi** [comment] 2016-08-02 13:58
@antoinerousseau what i did eventually was to suppress the crash => in the uncaught exception handler in android i check against this crash. If it IS this crash just suppress and do nothing, as the websocket will keep trying and will connect normally if you suppress it.

**Comment by antoinerousseau** [comment] 2016-08-02 15:38
@Sh3rawi but that means editing java code in the react native library (or okhttp3), right?

**Comment by Sh3rawi** [comment] 2016-08-02 16:47
@antoinerousseau  no, just put this in your Application's onCreate method 

```
mDefaultUEH = Thread.getDefaultUncaughtExceptionHandler();
    Thread.setDefaultUncaughtExceptionHandler(new Thread.UncaughtExceptionHandler() {
        @Override
        public void uncaughtException(Thread paramThread, Throwable paramThrowable) {
            if (paramThrowable.getMessage().equals("Listener failed to call close on message payload.")) {
                //Do Nothing. Until Prince Debugging comes and solves this.
            } else {
                //Exit the app; this acts as normal crash
                mDefaultUEH.uncaughtException(paramThread, paramThrowable);
            }
        }
    });
```

But i recommend you check this => if your suppress the crash then the socket will try and reconnect and things get going normally.
Also, what we did to reproduce this crash is to manipulate the internet connection to be as bad as it could be and eventually this crash will pop up your face.

**Comment by antoinerousseau** [comment] 2016-08-02 16:58
I see, thanks!

**Comment by leo7r** [comment] 2016-10-26 17:01
@Sh3rawi @antoinerousseau where can I find Application's onCreate method? I look up in MainActivity.java and MainApplication.java but there isn't an onCreate method. Thanks

**Comment by antoinerousseau** [comment] 2016-10-28 13:33
`MainApplication` extends `ReactApplication` where `onCreate` is already defined.
If you want to override it to add stuff, just add some java:

```java
public class MainApplication extends Application implements ReactApplication {

  @Override
  public void onCreate() {
    super.onCreate();
    // your code here
  }

  // rest of the code already there

}
```

**Comment by silverspace** [comment] 2016-11-07 21:22
Does anyone have any thoughts on whether this issue could be caused by the WebSocketListener in WebSocketModule not calling close() on the BufferedSource when there are exceptions? 

In other words, could wrapping the close() in a finally block fix the issue? 
https://github.com/silverspace/react-native/commit/578166c21568116aed55bafa963d9e9d61e92e6a

Note that this is completely untested code (I haven't even verified that it compiles).

**Comment by echo8795** [comment] 2017-11-13 12:26
I am facing the same issue on a lot of devices with production app, I am using react .47. Can anyone shed some light on the causes of this issue and possible how to fix, i dont have any experience in java. Thanks
