### ISSUE TITLE
I'm sorry to bother you,Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.

### ISSUE THREAD

**Issue by pencilso** [facebook/react-native#13437] opened 2017-04-11 06:39 UTC
In the existing Android project, the introduction of RN.
compile "com.facebook.react:react-native:+" // From node_modules.
 maven {
            // All of React Native (JS, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
Then run the project in Android Studio, throw an exception.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/LICENSE
	File1: D:\Github\LovePets\app\libs\httpcore-4.4.4.jar
	File2: C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-core\2.2.3\1a0113da2cab5f4c216b4e5e7c1dbfaa67087e14\jackson-core-2.2.3.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

It's normal when I remove the RN reference.
Could not find the reason for the exception, I need help.

**Comment by hramos** [comment] 2017-04-11 17:25
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-04-11 17:25 UTC
