### ISSUE TITLE
undefined is not a constructor (evaluating 'new window.WebSocket('ws://' + hostname+':'+port+'/devtools')')

### ISSUE THREAD

**Issue by konstantin-mohin** [facebook/react-native#12947] opened 2017-03-15 09:53 UTC
Hey, 

I'm using RN 0.39.0 and it was working fine, but yesterday I started getting this error: "undefined is not a constructor (evaluating 'new window.WebSocket('ws://' + hostname+':'+port+'/devtools')')" , it points to the setupDevtools.js:25 file. 

Im using a real android device and if I turn on Debug JS Remotely option the issue disappears.

**Comment by mrova** [comment] 2017-03-15 11:23
Try..catch around and see if you get more info in caught error.
I had similar problem - new URL(url) was throwing error like yours only with Debug JS Remotely turned off. Well, URL() doesn't exist if remote debugging is off.

**Comment by hramos** [comment] 2017-03-15 17:48
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-03-15 17:48 UTC

**Comment by aaronhma** [comment] 2017-07-30 18:15
Closing this issue.

**Comment by xudeheng** [comment] 2018-05-16 10:38
I meet the same issue at react-native 0.49.5
