### ISSUE TITLE
Putting a comment on the same line as an element in JSX, separated by a space, causes: Raw text cannot be used outside of a <Text> tag. Not rendering string: ' '

### ISSUE THREAD

**Issue by ExplodingCabbage** [facebook/react-native#4332] opened 2015-11-24 20:46 UTC
The following render function, using roughly the JSX commenting style [suggested in the React docs](https://facebook.github.io/react/docs/jsx-in-depth.html), blows up React Native:

```
render: function () {
  return (
    <View>
      <View></View> { /* some comment */ }
    </View>
  );
}
```

React Native is seeing the space between the `</View>` tag and `{ /* some comment */ }` as a space and throwing this error:

```
Raw text cannot be used outside of a <Text> tag. Not rendering string: ' '
```

Even if it's right that React Native sees the space as text, it should at least give a more reasonable error message! It's quite difficult to track down the cause of this error as a user.

**Comment by chirag04** [comment] 2015-11-24 22:12
I can confirm this on rn 0.15. 

@ExplodingCabbage If you have a fix for this please send a PR.

**Comment by mihirsoni** [comment] 2015-11-25 17:39
@chirag04 It seems ,  babel is not transpiling  the comments of JSX. I tried on babel REPL (goo.gl/otEcBh) as well as with cli.
```
 <Text style={styles.welcome}>
          Welcome to React Native!
 </Text> {/*child comment, put {} around*/}
```

The above JSX got compiled with 

```React.createElement(Text,{style:styles.welcome},'Welcome to React Native!'),' '```

  @sebmck  any idea on this ?

**Comment by mkonicek** [comment] 2016-04-10 16:42
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/putting-a-comment-on-the-same-line-as-an-element-in-jsx-separated-by-a-space-causes-raw-text-cannot-be-used-outside-of-a-text-tag-not-rendering-string-

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Closed by mkonicek** 2016-04-10 16:42 UTC
Labels: Icebox
