### ISSUE TITLE
[Bug] Fetch won't go further.

### ISSUE THREAD

**Issue by cablegunmaster** [facebook/react-native#8152] opened 2016-06-16 13:03 UTC
- Fetch won't go further until clicked somewhere  again.

**Situation:**
- Request data from the server.
- Server takes some time (1 - 2 secs max) to gather up the data, but never thinks its complete.
the user clicks at the same link again. Debug fires one link away, and leaves 1 in queue (for no appearant reason). So 2 clicks and 1 link returns. 

I am wondering does it keep a open connection?
`
        fetch('http://uri', {
            method: 'GET',
            headers: {
                 'Cache-Control': 'no-cache'
            }
        })
        //RESPONSE from API.
            .then((response) => response.text())
            .then((responseText) => {
`
Also happening With and without debugging! no difference.

**How did I verify?**
I loaded the whole function around it with console.log prints and it only returned above the fetch, and never inside the fetch or inside the responseText block. Until clicked on it again (not even clicking on screen helped).

I am seriously wondering if there is a await call or some async which doesn't get fired away.

**Related to :** " 'Cache-Control': 'no-cache'"

  "dependencies": {
    "babel-preset-react-native": "^1.8.0",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "babel-jest": "^9.0.0",
    "jest": "12.1.1",
    "jest-cli": "12.1.1",
    "react": "15.1.0",
    "react-addons-test-utils": "15.0.2",
    "react-native": "0.27.2",
    "react-native-chart": "^0.1.14",
    "react-native-vector-icons": "^2.0.2",
    "react-redux": "4.4.5",
    "redux": "3.1.7",
    "redux-logger": "^2.5.2",
    "redux-thunk": "1.0.3"

**Comment by cablegunmaster** [comment] 2016-06-20 13:35
It worked after removing :     
     ` 
'Cache-Control': 'no-cache'
`
Which feels weird is this supposed to work like this?  Cache vs no Cache issue.

**Comment by cablegunmaster** [comment] 2016-07-04 11:31
This bug reoccurred again in 0.28.0 and in 0.27.2

**Comment by satya164** [comment] 2016-07-04 21:27
Duplicate of https://github.com/facebook/react-native/issues/6679

**Closed by satya164** 2016-07-04 21:27 UTC
