### ISSUE TITLE
App has crashed : java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so

### ISSUE THREAD

**Issue by Abhi007** [facebook/react-native#35419] opened 2022-11-21 11:18 UTC
### Description

I did the same steps which is mentioned in this link (link is : https://medium.com/@jyubinpatel/make-reactnative-module-as-a-library-and-how-its-used-into-android-native-application-35b13f65ac7c) to make index.android.bundle file from react native project then putting it into a fresh native app to create a .aar file of it then we can use this in another needed native application where we exactly want to integrate this as library. Please let me know if any solution is available for this below error or related to this task which i have explained above.

I am getting this error while calling the react native application library (.aar file) in native android application, so when I run it I am calling the below code on which i am getting this error is as follows : 

MainActivity class
------------------------------------------------------------------------------------------
import android.content.Intent
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.widget.TextView

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        var textView: TextView = findViewById(R.id.txt_hello)
        textView.setOnClickListener {
            startActivity(Intent(this@MainActivity, ReactNativeActivity::class.java))
        }
    }
}

ReactNativeActivity class 
-----------------------------------------------------
import android.app.Application;

import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;

import java.util.Arrays;
import java.util.List;

public class ReactNativeActivity extends BaseActivity {

    @Override
    protected String getMainComponentName() {
        return "react_native_app_name";
    }

    @Override
    protected ReactNativeHost createReactNativeHost(Application app) {
        return new ReactNativeHost(app) {
            @Override
            public boolean getUseDeveloperSupport() {
                return false;
            }

            @Override
            protected List<ReactPackage> getPackages() {
                return Arrays.asList(new MainReactPackage());
            }

            @Override
            protected String getBundleAssetName() {
                return "index.android.bundle";
            }
        };
    }
}

BaseActivity class
----------------------------------------------------------------------------------------------------
import android.app.Application;
import android.os.Bundle;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactNativeHost;

public abstract class BaseActivity extends ReactActivity {

    private ReactNativeHost reactNativeHost;

    /**
     * Returns the name of the main component registered from JavaScript. This is used to schedule
     * rendering of the component.
     */
    @Override
    protected abstract String getMainComponentName();

    protected abstract ReactNativeHost createReactNativeHost(Application app);

    protected ReactActivityDelegate createReactActivityDelegate(){
        return new ReactActivityDelegate(this, getMainComponentName()){
            @Override
            protected ReactNativeHost getReactNativeHost(){
                if(reactNativeHost==null){
                    reactNativeHost = createReactNativeHost(getApplication());
                }
                return reactNativeHost;
            }
        };
    }
}

**Error :** 

App has crashed
                                                                                                    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so
                                                                                                    	SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/#####.##.###/lib-main flags = 1]
                                                                                                    	SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/~~vccykcNnSseE2lbdU59CjA==/#####.##.###-tIZ_hFLpxg-OPnnpZ2yerg==/lib/arm64 flags = 0]
                                                                                                    	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
                                                                                                    	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
                                                                                                    	Native lib dir: /data/app/~~vccykcNnSseE2lbdU59CjA==/###-tIZ_hFLpxg-OPnnpZ2yerg==/lib/arm64
                                                                                                     result: 0

### Version

0.70.1

### Output of `npx react-native info`

abhi@abhi-Latitude-3480:~/workspace/react-native/###-mobile-app/android$ npx react-native --version
6.1.0
abhi@abhi-Latitude-3480:~/workspace/react-native/###-mobile-app/android$ npx react-native info
info Fetching system and libraries information...
System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 1.36 GB / 11.40 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.19 - ~/workspace/react-native/###-mobile-app/node_modules/.bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Actually doing this below link steps to run the React Native Library in Native Android Application 

link is : https://medium.com/@jyubinpatel/make-reactnative-module-as-a-library-and-how-its-used-into-android-native-application-35b13f65ac7c

### Snack, code example, screenshot, or link to a repository

Error :   E  App has crashed
                                                                                                    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so
                                                                                                    	SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/###/lib-main flags = 1]
                                                                                                    	SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/~~vccykcNnSseE2lbdU59CjA==/###-tIZ_hFLpxg-OPnnpZ2yerg==/lib/arm64 flags = 0]
                                                                                                    	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
                                                                                                    	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
                                                                                                    	Native lib dir: /data/app/~~vccykcNnSseE2lbdU59CjA==/###-tIZ_hFLpxg-OPnnpZ2yerg==/lib/arm64
                                                                                                     result: 0

**Comment by daveosterjr** [comment] 2022-11-22 01:05
Same issue here and have tried multiple different things to no avail.

**Comment by gowravl** [comment] 2022-11-22 13:08
Can anyone share the source code of the completed framework and sample application. It would help me greatly.

**Comment by cortinico** [comment] 2022-11-23 19:06
Can you share your `build.gradle` file? Also are you using variants?

**Comment by Abhi007** [comment] 2022-11-25 05:46
> Can you share your `build.gradle` file? Also are you using variants?

Yes I am using product flavours and release build variant, should i do some changes in gradle related to it

**Comment by cortinico** [comment] 2022-11-25 12:04
Can you share your build.gradle file?

**Comment by DaniShalash** [comment] 2023-01-09 11:27
I had the same experience when I upgraded from 0.67.5 to 0.70.6 and was able to solve it after struggling for some time.

In my case, the app crashes only when hermes is enabled.
And in fact, turned out `libhermes.so` is actually missing from my APK.

You can open the APK using Android Studio and look under `lib` directory
(Or you can also check under `android/app/build/intermediates/merged_native_libs/debug/out/arm64-v8a/` and look for `libhermes.so`. Faster than opening the APK everytime using Android Studio).

After some digging, I found out that the following script `./node_modules/react-native/react.gradle` is receiving `enableHermes` value as false, even though it's set to true in my `app/build.gradle`, and there's also a new cleanup task in that script which removes unneeded libraries from the final package, and thus, removing `libhermes.so`

Check [here](https://github.com/facebook/react-native/blob/v0.70.6/react.gradle#L421)

Turned out the problem was that I'm applying `react.gradle` script in my `app/build.gradle` **BEFORE** setting react config!

So I moved the `react.gradle` statement after `project.ext.react`, cleaned the project, ran a new build and problem solved.

Like this:
```
project.ext.react = [
    enableHermes: true, // Clean and Rebuild if Changed
    bundleInDebug: false,
    bundleInRelease: true,
    extraPackagerArgs: []
]

/**
 * The script "react.gradle" is using properties defined in the exported "project.react" object.
 * So please always make sure it's applied after "project.react" is defined.
*/
apply from: "../../node_modules/react-native/react.gradle"
```

Don't forget to run `./gradlew clean` before building again.

**Comment by cortinico** [comment] 2023-01-19 10:14
> I had the same experience when I upgraded from 0.67.5 to 0.70.6 and was able to solve it after struggling for some time.

We resolved this and all the "couldn't find DSO to load" crashes in version 0.71 of React Native. The issues were caused by a too aggressive cleanup logic which was attempting to remove too many libraries.

I'm closing this issue as the resolution is available for public usage in 0.71

**Closed by cortinico** 2023-01-19 10:14 UTC
Labels: Needs: Triage :mag:

**Comment by raldred** [comment] 2023-02-06 10:44
@cortinico, we seeing this on all our customers with devices running Android 10, we can't move to 0.71 yet due to depending on a few modules from Expo, any chance of a patch to 0.70?

**Comment by cortinico** [comment] 2023-02-08 19:28
> any chance there's a way to patch this for 0.70

Sadly not as this required a significant rework of the internals. If the issue persists on 0.71, we can keep a look at it and fix it furhter
