### ISSUE TITLE
0.56 regression: jest.mock only works when defined in jestSetup.js, not in individual Snapshots tests

### ISSUE THREAD

**Issue by farhanmannan** [facebook/react-native#20508] opened 2018-08-02 16:46 UTC
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
React Native Environment Info:
   System:
     OS: macOS High Sierra 10.13.2
     CPU: x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
     Memory: 69.35 MB / 8.00 GB
     Shell: 3.2.57 - /bin/bash
   Binaries:
     Node: 8.11.2 - /usr/local/bin/node
     Yarn: 1.7.0 - /usr/local/bin/yarn
     npm: 5.6.0 - /usr/local/bin/npm
     Watchman: 4.9.0 - /usr/local/bin/watchman
   SDKs:
     iOS SDK:
       Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
     Android SDK:
       Build Tools: 23.0.1, 23.0.3, 25.0.2, 25.0.3, 26.0.1, 27.0.3
       API Levels: 23, 25, 26, 27
   IDEs:
     Android Studio: 3.1 AI-173.4819257
     Xcode: 9.4/9F1027a - /usr/bin/xcodebuild
   npmPackages:
     react: 16.4.1 => 16.4.1
     react-native: 0.56.0 => 0.56.0
   npmGlobalPackages:
     create-react-native-app: 1.0.0
     react-native-cli: 2.0.1
```

## Description
Hi there, thanks for taking the time to read this and thanks for the many fixes in the 0.56 upgrade. Sadly I believe this is a regression. This was working fine on 0.55. I cannot afford the technical debt of not upgrading to the latest RN version as the upgrade procedure is too time-expensive.

I have jest mocks (mocked functions, modules and components) in my `jestSetup.js` file (pointed to from `package.json`), and I also have mocks in individual test files, including unit tests and snapshot tests. 

In my individual snapshot tests, the mocks do not work anymore - the mocks exist (I can console.log them) but when the snapshot tests are run, the mocked functions are not called - instead the "real" functions are called. This is NOT the case for mocks defined the SAME way but placed in `jestSetup.js` - the snapshots call the mocked functions as expected when they are defined in `jestSetup.js`.

I have moved as many mocks as possible to jestSetup.js but unfortunately some tests require the functions to be unmocked (e.g. unit tests) so this cannot fix all my new errors caused by upgrading to 
0.56.

Please let me know if there is a workaround and if a fix is on the horizon.

## Reproducible Demo
Example snapshot test with mock that doesn't work unless moved into `jestSetup.js`
```
import 'react-native';
import renderer from 'react-test-renderer';
import React from 'react';
import sinon from 'sinon';

jest.mock(
  '../../src/components/common/ProfilePicture/StarredPicture/StarredPicture',
  () => () => { return ''; },
);

test('renders correctly', () => {
  const stub = sinon.stub(console, 'error');
  const tree = renderer.create(<Profile />).toJSON();
  const tree = renderer
    .create(<Profile />)
    .toJSON();
  expect(tree).toMatchSnapshot();
  // call count is one to reflect one required proptypes.
  expect(stub.callCount).toEqual(1); 
```

package.json
```
"jest": {
    "automock": false,
    "preset": "react-native",
    "setupFiles": [
      "./src/jestSetup",
    ],
    "transform": {
      "^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"
    },
    "transformIgnorePatterns": [
      "node_modules/(?!@expo)/"
    ],
    "collectCoverageFrom": [
      "src/**/*.js"
    ]
  }
```

**Comment by shyaniv7** [comment] 2018-08-02 22:57
We are experiencing the same issue after uplifting to RN 0.56 from 0.55.4

**Comment by StevenLambion** [comment] 2018-08-03 14:51
I ran into this issue after getting the tests working in 0.56.0. It looks like the React Native transformer doesn't include the jest-hoist babel plugin. This plugin is required for mocks to work correctly.

To fix it for now I added jest-hoist to my own .babelrc file.

```
{
  "presets": ["react-native", "@babel/flow"],
  "plugins": ["jest-hoist"],
  "sourceMaps": true,
  "retainLines": true
}
```

**Comment by shyaniv7** [comment] 2018-08-03 15:55
@StevenLambion according to the doc on `jest-hoist`

>This plugin is automatically included when using babel-jest.

since react-native is using babel-jest im not sure how adding it would make a difference.
I could be wrong here because i dont understand it very well but adding it in babelrc did not fix the issue for us

**Comment by kelset** [comment] 2018-08-03 16:20
Looks to me like a duplicate of https://github.com/facebook/react-native/issues/19859

**Comment by TomJamesDuffy** [comment] 2018-08-03 16:32
Followed the advice of @StevenLambion and combined it with adding the below packages to yarn (as per the link kindly provided by @kelset). I then deleted node modules (paranoia) and yarn installed. This made all the tests pass.

+    "@babel/core": "^7.0.0-beta.47",
+    "babel-core": "^7.0.0-beta.47",
+    "babel-jest": "^23.2.0",
+    "babel-plugin-jest-hoist": "^23.2.0",

**Comment by kelset** [comment] 2018-08-03 16:37
Good, I'll close this for now, and reopen if I have strong evidences it's actually something else.

**Closed by kelset** 2018-08-03 16:37 UTC
Labels: :nut_and_bolt:Tests, :warning:Regression

**Comment by putuyoga** [comment] 2018-10-16 15:59
thanks a lot @StevenLambion @TomJamesDuffy, this issue really made me pull my hairs out.

**Comment by jamespearson** [comment] 2018-12-06 11:47
@StevenLambion @TomJamesDuffy - You guys just saved me at least a day of trying to figure this out. Thanks for your contribution.
