### ISSUE TITLE
ReactNative Custom Port support 

### ISSUE THREAD

**Issue by sachin1** [facebook/react-native#5096] opened 2016-01-03 17:17 UTC
Hi,

I am trying to configure react native for windows for android app development but I am unable to use port 8081 as it is used by McAfee agent on my laptop.
I am able to start node js server on different port (8090) but when  i am running command: 
reactnative run-android - i am unable to specify port option. Looks to be that it is hardcoded with 8081.
Is there  anyway i can start reactnative run-android for 8090 port on windows?

**Comment by brentvatne** [comment] 2016-01-04 02:26
Duplicate of #1429 -- you can upvote here: https://productpains.com/post/react-native/allow-packager-port-to-be-configurable-change-from-8081/ :)

**Closed by brentvatne** 2016-01-04 02:26 UTC

**Comment by sachin1** [comment] 2016-01-04 06:58
Is there any hack available to make it work on windows for different port number for android development? any pointers on this are appreciated..
