### ISSUE TITLE
[WebView, iOS] Can't reload after connection renderError

### ISSUE THREAD

**Issue by stereodenis** [facebook/react-native#8239] opened 2016-06-20 10:27 UTC
1. I have no Internet connection and try to render WebView
2. Got error view with renderError implementation
3. Turn on Internet connection and try to reload component (@refs.webview.reload())
4. Nothing happened

**Comment by 281330** [comment] 2016-06-20 13:47
Do you have any sample code?

**Comment by charpeni** [comment] 2016-06-20 13:55
@facebook-github-bot label iOS

**Comment by charpeni** [comment] 2016-06-20 14:04
My guess is this is caused by the `viewState`, after you triggered the `reload` method the viewState has an error into the viewState.

These lines could block the reloading : 

- https://github.com/facebook/react-native/blob/master/Libraries/Components/WebView/WebView.ios.js#L291
- https://github.com/facebook/react-native/blob/master/Libraries/Components/WebView/WebView.ios.js#L271

Are you up for some testing and a pull request ?

Maybe with this into reload it could work :

```javascript
this.setState({viewState: WebViewState.LOADING});
```

**Comment by stereodenis** [comment] 2016-06-20 14:12
@charpeni I will try

**Comment by stereodenis** [comment] 2016-06-20 15:18
@charpeni done!

**Comment by charpeni** [comment] 2016-06-21 13:48
I'll close this issue since it was fixed by my guess, thank you @stereodenis.

**Comment by charpeni** [comment] 2016-06-21 13:48
@facebook-github-bot close

**Comment by facebook-github-bot-1** [comment] 2016-06-21 13:48
@charpeni tells me to close this issue. If you think it should still be opened let us know why.

**Comment by stereodenis** [comment] 2016-07-06 11:59
@charpeni 
0.29.0 — not working

**Comment by stereodenis** [comment] 2016-07-06 11:59
@facebook-github-bot open

**Comment by charpeni** [comment] 2016-07-06 13:25
Your fix has landed into `0.30.0-rc.0` not `0.29.0`.

**Comment by stereodenis** [comment] 2016-07-06 13:57
@charpeni not working on 0.30.0-rc.0

**Comment by charpeni** [comment] 2016-07-06 14:02
That's bad, but it works well when you test your PR?

**Comment by charpeni** [comment] 2016-07-06 14:03
@facebook-github-bot reopen

**Comment by facebook-github-bot-7** [comment] 2016-07-06 14:05
Okay, reopening this issue.

**Comment by stereodenis** [comment] 2016-07-08 13:22
@charpeni it's hard to debug, cause there is no internet connection to render Error
Could someone from your Facebook team help in this case?

**Comment by stereodenis** [comment] 2016-07-08 15:31
@nicklockwood, @janicduplessis, @javache maybe you can help?

**Comment by mkonicek** [comment] 2016-10-27 22:11
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/webview-ios-cant-reload-after-connection-rendererror

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Closed by mkonicek** 2016-10-27 22:11 UTC
Labels: Icebox, iOS, Ran Commands
