### ISSUE TITLE
`measure()` no longer reports sizes outside of the parent view

### ISSUE THREAD

**Issue by tume** [facebook/react-native#10603] opened 2016-10-28 06:48 UTC
There seems to be some change related to measuring layout which broke react-native-collapsible component. According to the author: 

> Unfortunately this is because of a breaking change (not sure if intended or not) in the native implementation of measure() which will no longer report sizes outside of the parent view.

Would be nice at least to have some clarification what this change was and if there are any workarounds to get same results as with the old one. Could not find anything related to this in the changelog either.

Related issue in react-native-collapsible: 
https://github.com/oblador/react-native-collapsible/issues/51

**Comment by lacker** [comment] 2016-11-02 21:10
I am not aware of any breaking change like this. Unfortunately, that doesn't mean there wasn't one. Do you know which diff introduced it?

**Comment by mkonicek** [comment] 2016-11-02 22:02
There was a small change which was listed in the release notes I think. cc @emilsjolander

**Comment by calebmer** [comment] 2016-11-03 20:28
@lacker in https://github.com/oblador/react-native-collapsible/issues/51 @zoharlevin guesses the change was https://github.com/facebook/react-native/commit/0a9b6bedb312eba22c5bc11498b1cc41363e5f27. Here’s the quote:

> not 100% sure, but i think this is the commit 0a9b6be
> it's mentioned in the breaking changes for 0.36
> [(source)](https://github.com/oblador/react-native-collapsible/issues/51#issuecomment-258153771)

**Comment by lacker** [comment] 2016-11-03 20:52
OK - so if we mentioned it in the breaking changes then, well, that's our current process for breaking changes so we at least followed it. It's definitely not ideal though. @mkonicek had some ideas around 1/ making `react-native upgrade` intelligently tell you what went wrong, and also 2/ having an officially supported way to create & publish react native modules, which we could then also make upgrades work with sanely. I think we should close this issue since the proximate question is answered but also keep reminding @mkonicek how valuable working on the stability of this stuff will be ;-)

**Comment by oblador** [comment] 2016-11-06 15:07
@lacker The release notes say nothing about `measure()` nor iOS being affected. Also if this change is not intended (which is still unclear to me after reading the commit message and your comment) then this issue is still valid no?

**Comment by lacker** [comment] 2016-11-07 18:23
If there is a bug then I think we should fix the bug but then it would be better to have an issue stating "fix bug x" rather than "the release notes are missing x".

**Comment by emilsjolander** [comment] 2016-11-09 18:59
I'm not really sure what is 'wrong' here or what is meant by 'no longer report sizes outside of the parent view'? Is measure not called for certain cases? Because if so that is to be expected, measure has always had this property. Measure is only called when the size of a node is not known.

The referenced commit fixes a bug with the measure and layout code so it is expected that `measure()` will be called with different parameters than before for the same layout. The API for the function did not change though.

@oblador The commit does not mention either android or iOS as it effects all platforms. If the release notes just mention android then that's just a mistake in the release notes 👍

**Comment by mkonicek** [comment] 2016-11-09 19:01
@oblador Which release broke this? 0.36?

**Comment by oblador** [comment] 2016-11-09 19:19
@mkonicek: Yes 0.36. 

@emilsjolander: Given a parent with `height: 100, overflow: 'hidden'` and a child with `height: 200`, `measure()` of the child would for 0.35 return `200`, and 0.36 `100`. 

The notes mention only `flex*` properties and not `overflow` or `measure()` behaviour, which leads me to think it might perhaps be a regression. If `measure()` behaviour was wrong up till 0.36 and it's really a bug getting fixed, then that's good – and I need to use a different approach.

**Comment by emilsjolander** [comment] 2016-11-09 19:22
@oblador I don't write the release notes, commit message does mention overflow 👍 Could you please provide a full example I can run?

**Comment by oblador** [comment] 2016-11-09 19:28
@emilsjolander: Yes, this is foremost a communication problem. You can run the example project of mentioned library: https://github.com/oblador/react-native-collapsible/tree/master/Example

**Comment by emilsjolander** [comment] 2016-11-09 19:33
@oblador Do you have smaller example showing only the problem you are referring to? Not really sure what view in the sample is the issue

**Comment by oblador** [comment] 2016-11-09 19:37
I don't sorry, although the relevant parts are in this component: https://github.com/oblador/react-native-collapsible/blob/master/Collapsible.js#L90 There, `onLayout` reports height to be 0.

**Comment by emilsjolander** [comment] 2016-11-09 19:40
`onLayout` is very different from the native `measure()` function call. Seems like the problem is probably with the style of the content in `app.js` remove `flex:1` from `style.content` or replace it with `flexGrow:1`.

**Comment by oblador** [comment] 2016-11-09 22:31
@emilsjolander: I first discovered it in a project I'm working on that was using `measure()`; `onLayout` reported same data so assumed it was linked. However I dug a bit deeper into it and can now determine that `measure()` does actually work correctly! 👏 The change/breaking behaviour was really with the wrapping `View` that didn't have fixed sizing. `flexGrow: 1` doesn't seem to make a difference in this case, the following example renders like this:

![namnlost-1](https://cloud.githubusercontent.com/assets/378279/20157289/80aca6dc-a6d4-11e6-875b-1802b304df41.png)


```js
class App extends Component {
  state = {
    outerHeight: '?',
    innerHeight: '?'
  };

  measureRef(ref, key) {
    requestAnimationFrame(() => {
      ref.measure((ox, oy, width, height, px, py) => {
        this.setState({ [key]: height });
      });
    });
  }

  handleOuterRef = (ref) => this.measureRef(ref, 'outerHeight');

  handleInnerRef = (ref) => this.measureRef(ref, 'innerHeight');

  render() {
    return (
      <View style={styles.container}>
        <View ref={this.handleOuterRef} style={styles.outer}>
          <View ref={this.handleInnerRef} style={styles.inner}>
            <Text>Outer height: {this.state.outerHeight}</Text>
            <Text>Inner height: {this.state.innerHeight}</Text>
          </View>
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    marginTop: 50,
    alignSelf: 'center',
    height: 150,
    width: 150,
  },
  outer: {
    backgroundColor: '#0009',
  },
  inner: {
    width: 200,
    height: 200,
    backgroundColor: '#f009',
  }
});
```

**Comment by emilsjolander** [comment] 2016-11-09 22:53
@oblador thanks! I now have a good small repro. Specifically 
```html
<div style="height: 100px; width: 100px;">
  <div>
    <div style="height: 200px; width: 200px;"></div>
  </div>
</div>
```
Does not layout the same in webkit and css-layout. Working on a fix.

**Comment by emilsjolander** [comment] 2016-11-10 02:22
Diff is up internally. Fixing this is in itself a breaking change though so could take a while to get into master. Thanks for making us aware of this!

**Comment by oblador** [comment] 2016-11-10 09:15
Thanks for the quick fix!

**Comment by oblador** [comment] 2016-11-16 10:29
@emilsjolander It seems your fix was reverted? https://github.com/facebook/css-layout/commit/204aba80b9818db0e9b6f6f74d9a2fd2580ede1c

**Comment by yezongyang** [comment] 2016-11-16 10:36
But i found that it is plan to fix in 0.39, https://github.com/facebook/react-native/wiki/Breaking-Changes

**Comment by emilsjolander** [comment] 2016-11-16 11:03
@oblador yup, it broke something unexpected. No ETA on relanding.

**Comment by oblador** [comment] 2016-12-06 22:50
@emilsjolander Any chance of this making it into 0.40?

**Comment by emilsjolander** [comment] 2016-12-06 22:53
No it won't. I have not had time to fix the issues caused by the fix yet.

**Comment by mlabrum** [comment] 2016-12-21 22:19
Is there any ETA on when this will be released, if it's not making it into 0.40

**Comment by mlabrum** [comment] 2017-01-09 23:05
Is there any status update on this? as this does seem to be effecting quite a few users

**Comment by oblador** [comment] 2017-01-20 09:32
@emilsjolander: Judging by your yoga commit is this issue now fixed? 🙏

**Comment by sibelius** [comment] 2017-03-04 22:23
@oblador https://github.com/oblador/react-native-collapsible is working fine on RN42

**Comment by hramos** [comment] 2017-07-20 22:36
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/measure-no-longer-reports-sizes-outside-of-the-parent-view

**Closed by hramos** 2017-07-20 22:36 UTC
Labels: Icebox

**Comment by kamleshnarola** [comment] 2018-02-08 04:55
@oblador Thanks! that solution help me .
