### ISSUE TITLE
OkHttpClientProvider for Android 4 does not support TLSv1

### ISSUE THREAD

**Issue by PaulVanStaden** [facebook/react-native#14244] opened 2017-05-29 18:17 UTC
#### Correctly functioning behaviour.
In Android v5 and upwards when using the standard OkHttpClientProvider it uses OkHttpClient.Builder() to determine the connectionSpecs. This returns a default
```
DEFAULT_CONNECTION_SPECS = Util.immutableList(
      ConnectionSpec.MODERN_TLS, ConnectionSpec.COMPATIBLE_TLS, ConnectionSpec.CLEARTEXT);
```
#### Inconsistent behaviour 
For Android SDK `Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN && Build.VERSION.SDK_INT <= Build.VERSION_CODES.KITKAT` it goes into a custom `enableTls12OnPreLollipop` codeblock that specifically only implements `ConnectionSpec.MODERN_TLS`

This results that connections using TLSv1 will not work on Android 4. 

### Reproduction Steps and Sample Code

0. Run an emulator on API 16. 
0. Try a SSL network request to a SSL server only accepting TLSv1
0. Fail network request due to the following error
```
javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb9561090: Failure in SSL library, usually a protocol error
error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol (external/openssl/ssl/s23_clnt.c:714 0x9e0fd925:0x00000000)
```

### Solution

Will Add pull request. 
Added #14245

in com.facebook.react.modules.network.TLSSocketFactory replace 
```
private Socket enableTLSOnSocket(Socket socket) {
        if(socket != null && (socket instanceof SSLSocket)) {
            ((SSLSocket)socket).setEnabledProtocols(new String[] {"TLSv1.1", "TLSv1.2"});
        }
        return socket;
    }
```
with 
```
private Socket enableTLSOnSocket(Socket socket) {
        if(socket != null && (socket instanceof SSLSocket)) {
            ((SSLSocket)socket).setEnabledProtocols(new String[] {"TLSv1","TLSv1.1", "TLSv1.2"});
        }
        return socket;
    }
```
### Additional Information

* React Native version: v0.45.0-rc.2
* Platform: Android
* Development Operating System: OSX and Windows
* Dev tools: Android Studio version, Android SDK 25

**Comment by hramos** [comment] 2017-07-31 21:54
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by 8of** [comment] 2018-07-24 19:48
Reoccured on React Native `0.56.0`

**Comment by sijad** [comment] 2018-09-10 05:11
any news on this one? we can't use cloudflare CDN because of this bug.

**Comment by sijad** [comment] 2018-12-09 12:15
I think this should kept open

**Comment by lahed** [comment] 2018-12-12 05:42
Some solution, the same thing happens to me, since 0.56.0 it stopped working

**Comment by ThaJay** [comment] 2019-02-28 12:13
This is the original pull request
https://github.com/facebook/react-native/pull/9840

**Comment by dulmandakh** [comment] 2019-03-19 14:33
we fixed the issue in the master, and will be included in future releases. https://github.com/facebook/react-native/commit/75af15ede44135110e40de75a649d5b15430c590

**Closed by dulmandakh** 2019-03-19 14:33 UTC
Labels: Platform: Android, Type: Bug Report

**Comment by dulmandakh** [comment] 2019-03-19 14:37
please see https://github.com/facebook/react-native/pull/23984 for workarounds
