### ISSUE TITLE
can't import npm package

### ISSUE THREAD

**Issue by Elvenisboy** [facebook/react-native#11159] opened 2016-11-27 16:55 UTC
### Description
When I use react native 0.38.0 to init a new project. I find that I can't use npm to install some packages, such as react-native-drawer.
After import react-native-drawer. It will show unnamed module react-native-drawer

### Additional Information

* React Native version: 0.38
* Platform: [Android]
* Operating System: [ Windows10]

**Comment by mkonicek** [comment] 2016-11-28 01:34
Hey, thanks for reporting this issue!

What's the exact error? How exactly (what command) did you install packages?

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but we can reopen if additional information is provided. Thanks!

**Closed by mkonicek** 2016-11-28 01:34 UTC
