### ISSUE TITLE
[FlatList] MapView is not working in ListHeaderComponent Of Flatlist Component in react-native

### ISSUE THREAD

**Issue by nimish-gupta** [facebook/react-native#14006] opened 2017-05-17 00:02 UTC
MapView is not working as the component passed into the ListHeaderComponent,
You can check the code at https://snack.expo.io/r1NKzMFg-
Or run the below code to reproduce the bug:-
`import React, { Component } from 'react';
import { Text, View, FlatList } from 'react-native';
import {  Components } from 'expo';

export default class App extends Component {
  render() {
    const ListHeaderComponent = () =>{
    return (
        <Components.MapView
      style={{ flex: 1 }}
      initialRegion={{
        latitude: 37.78825,
        longitude: -122.4324,
        latitudeDelta: 0.0141,
        longitudeDelta: 0.0121,
      }}
    >
    </Components.MapView>
      )
  }
    const posts=[{id:1,name:"Nimish"},{id:2,name:"Gupta"}]
  return (
    <View style={{ flex: 1 }}>
      <FlatList
        ListHeaderComponent={ListHeaderComponent}
        data={posts}
        numColumns={3}
        onEndReached={() => console.log('yyooo end reached')} // TODO: Implement pagination
        onEndReachedThreshold={0.5}
        keyExtractor={item => item.id}
        // The item property is passed by FlatList
        //   for each item in the data array
        renderItem={({ item }) => (
          <Text>{item.name}</Text>
        )}
      />
    </View>
  );
  }
}
`

**Comment by hramos** [comment] 2017-06-02 17:04
Hey, thanks for reporting this issue!

Can you fix the formatting in your post? It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-02 17:04 UTC
