### ISSUE TITLE
iOS Wrapping react-native into dynamic library caused Fabric components not displayed

### ISSUE THREAD

**Issue by nanatlantica** [facebook/react-native#43354] opened 2024-03-06 18:02 UTC
### Description

I wrapped libPods-ReactNativeSDK.a into a dynamic library for the app to depend on it, but my custom Fabric component cannot display (init method not called), and there is no error message.

### Steps to reproduce

1.Create dynamic library xcode project
2.install react native by Pod install
3.compile this project into .framework file
4.My app embeded the .framework file
5.Run DYSanae

### React Native Version

0.72.5

### Affected Platforms

Runtime - iOS

### Areas

Fabric - The New Renderer

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.2.1
  CPU: (8) arm64 Apple M1 Pro
  Memory: 288.92 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.5.1
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.21
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.8.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.01.15.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.11.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 20.0.1
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: true
```

### Stacktrace or Logs

```text
no exception logs captured
```

### Reproducer

https://github.com/nanatlantica/RNDynamic

### Screenshots and Videos

https://github.com/facebook/react-native/assets/6023483/a1d54656-e546-4153-b87b-adf375269421

**Comment by cortinico** [comment] 2024-03-06 18:11
Closing as duplicate of https://github.com/facebook/react-native/issues/43343
@cipolleschi already answered you over there

**Closed by cortinico** 2024-03-06 18:11 UTC
Labels: Platform: iOS, Needs: Triage :mag:, Newer Patch Available, Type: New Architecture

**Comment by nanatlantica** [comment] 2024-03-06 18:14
So you meaning that I should link react-native as a static library, not a dynamic library?

**Comment by cipolleschi** [comment] 2024-04-03 13:55
Static libraries and dynamic libraries work with React Native.
What is not supported is wrapping react native in a single piece and drag-and-dropping it around as an XCFramework. We use cocoapods to set up several build flags and build settings that you need in order to make it work properly. If you wrap React Native in a framework and you move it around, you lose those settings. 
That setup is not supported and we don't have capacity to support you in the investigation.
