### ISSUE TITLE
Could not find com.facebook.react:react-native-gradle-plugin:.

### ISSUE THREAD

**Issue by mehdi-developer** [facebook/react-native#34407] opened 2022-08-14 01:16 UTC
### Description

Can't run android when executing ```react-native run-android```

```
info Installing the app...

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-community_slider'.
> Could not resolve all artifacts for configuration ':react-native-community_slider:classpath'.
   > Could not find com.facebook.react:react-native-gradle-plugin:.
     Required by:
         project :react-native-community_slider

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
```

package.json 
```
  "dependencies": {
    "@haskkor/react-native-pincode": "^1.22.6",
    "@metrixorg/react-native-plugin": "^1.1.7",
    "@react-native-async-storage/async-storage": "^1.15.9",
    "@react-native-community/slider": "^4.3.0",
    "@react-native-firebase/analytics": "^14.3.0",
    "@react-native-firebase/app": "^14.3.0",
    "@react-native-firebase/messaging": "^14.3.0",
    "@react-native-masked-view/masked-view": "^0.2.6",
    "@react-native-picker/picker": "^2.1.0",
    "@react-navigation/bottom-tabs": "^6.0.9",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/native-stack": "^6.2.5",
    "awesome-phonenumber": "^2.66.0",
    "axios": "^0.23.0",
    "country-data": "0.0.31",
    "d3": "^7.3.0",
    "d3-axis": "^3.0.0",
    "d3-scale": "^3.1.0",
    "d3-selection": "^3.0.0",
    "d3-shape": "^3.1.0",
    "formik": "^2.2.9",
    "jwt-decode": "^3.1.2",
    "lodash": "^4.17.21",
    "lottie-ios": "^3.2.3",
    "lottie-react-native": "^5.1.2",
    "mathjs": "^5.8.0",
    "moment": "^2.29.1",
    "moment-jalaali": "^0.9.4",
    "native-base": "^2.15.2",
    "numbro": "^2.3.6",
    "prop-types": "^15.8.1",
    "query-string": "^7.1.0",
    "react": "17.0.2",
    "react-localization": "^0.1.10",
    "react-native": "0.66.1",
    "react-native-bootsplash": "^3.2.6",
    "react-native-collapsible": "^1.6.0",
    "react-native-confirmation-code-field": "^7.1.0",
    "react-native-curved-bottom-bar": "^1.7.2",
    "react-native-date-picker": "^4.2.2",
    "react-native-document-picker": "^7.1.3",
    "react-native-drawer": "^2.5.1",
    "react-native-dropdown-picker": "^5.2.3",
    "react-native-exit-app": "^1.1.0",
    "react-native-gradle-plugin": "^0.70.2",
    "react-native-image-crop-picker": "^0.37.3",
    "react-native-keychain": "^8.0.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-modal": "^13.0.1",
    "react-native-pager-view": "^5.4.11",
    "react-native-permissions": "^3.1.0",
    "react-native-persian-calendar-picker": "^3.1.1",
    "react-native-phone-call": "^1.0.9",
    "react-native-progress": "^5.0.0",
    "react-native-push-notification": "^8.1.1",
    "react-native-qr-generator": "^1.0.4",
    "react-native-qrcode-svg": "^6.1.2",
    "react-native-reanimated": "^2.4.1",
    "react-native-recaptcha-that-works": "^1.2.0",
    "react-native-restart": "0.0.23",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "^3.8.0",
    "react-native-skeleton-placeholder": "^5.0.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-svg": "^12.1.0",
    "react-native-switch": "^1.5.1",
    "react-native-touch-id": "^4.4.1",
    "react-native-webview": "^11.17.2",
    "react-redux": "^6.0.1",
    "redux": "^4.1.2",
    "redux-form": "^8.1.0",
    "redux-persist": "^4.10.2",
    "redux-promise-middleware": "^6.1.2",
    "redux-thunk": "^2.4.1",
    "reselect": "^4.1.5",
    "socket.io-client": "^2.2.0",
    "validator": "^13.7.0",
    "yup": "^0.32.11"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.17.8",
    "@react-native-community/eslint-config": "^2.0.0",
    "@types/jest": "^27.4.0",
    "@types/react": "^17.0.38",
    "@types/react-native": "^0.66.17",
    "@types/react-native-drawer": "^2.5.5",
    "@types/react-redux": "^7.1.24",
    "@types/react-test-renderer": "^17.0.1",
    "babel-jest": "^26.6.3",
    "eslint": "7.14.0",
    "jest": "^26.6.3",
    "jetifier": "^2.0.0",
    "metro-react-native-babel-preset": "^0.66.2",
    "react-test-renderer": "17.0.2",
    "reactotron-react-native": "^5.0.1",
    "typescript": "^4.5.4"
  },
```

### Version

0.66.1

### Output of `npx react-native info`

System:
    OS: macOS 11.5.2
    CPU: (8) x64 Apple M1
    Memory: 30.92 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.12 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0
      System Images: android-29 | Google APIs ARM 64 v8a, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.1 => 0.66.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

npm install
npm run android 

### Snack, code example, screenshot, or link to a repository

<img width="720" alt="Screen Shot 1401-05-23 at 05 45 52" src="https://user-images.githubusercontent.com/63982703/184518514-d39b0ccd-aa9a-4dc5-8b30-10c7c5eca204.png">

**Comment by Quintis1212** [comment] 2022-08-16 13:10
Hi, try to decrease version of @react-native-community/slider and  run build again. It seems the gradle settings for  "react-native": "0.66.1" not compatible with  last version of @react-native-community/slide

**Comment by cortinico** [comment] 2022-08-16 13:47
> > Could not find com.facebook.react:react-native-gradle-plugin:.
>      Required by:
>          project :react-native-community_slider

I would suggest opening an issue against `@react-native-community/slider`:
https://github.com/callstack/react-native-slider

**Comment by cortinico** [comment] 2022-08-16 13:48
Closing as I believe this is not a bug inside React Native Core. Feel free to re-open if folks on Slider send you back here 👍 Thank you

**Closed by cortinico** 2022-08-16 13:48 UTC
Labels: Needs: Triage :mag:

**Comment by Sunbreak** [comment] 2022-08-18 06:05
> Hi, try to decrease version of @react-native-community/slider and run build again. It seems the gradle settings for "react-native": "0.66.1" not compatible with last version of @react-native-community/slide

Try https://github.com/lottie-react-native/lottie-react-native/pull/924

**Comment by johhansantana** [comment] 2023-03-21 20:08
did you ever found a solution for this?

**Comment by devjs1000** [comment] 2023-05-03 06:41
> I have resolved this with simple solution

**just do** `rm -rf node_modules`
**then do** `yarn install`
**after that** it will work
