### ISSUE TITLE
cookie wrong --by ios

### ISSUE THREAD

**Issue by shuobeige11** [facebook/react-native#13026] opened 2017-03-20 10:03 UTC
RN IOS write cookie reported the following error, is there a solution
![image](https://cloud.githubusercontent.com/assets/15864570/24095301/6f4f2110-0d97-11e7-918b-29942b4dcd72.png)

**Comment by hramos** [comment] 2017-03-20 16:30
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-03-20 16:30 UTC
