### ISSUE TITLE
- `React/BatchedBridge (from `../node_modules/react-native`)` required by `Podfile`

### ISSUE THREAD

**Issue by wei63w** [facebook/react-native#15010] opened 2017-07-14 02:44 UTC
```
[!] Unable to satisfy the following requirements:

- `React/BatchedBridge (from `../node_modules/react-native`)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `React/BatchedBridge (from `../node_modules/react-native`)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

and my podfile 
```
# You Podfile should look similar to this file. React Native currently does not support use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

# Change 'AirMapsExplorer' to match the target in your Xcode project.
target 'genilexubi' do

  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'React', path: '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'BatchedBridge'
  ]

  pod 'GoogleMaps'  # <~~ remove this line if you do not want to support GoogleMaps on iOS
pod 'react-native-maps', :path => '../node_modules/react-native-maps'
pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'

end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "react-native-google-maps"
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
  end
end

```
I want to add google map in my project . so 
is missing some support with me ?

**Comment by hramos** [comment] 2017-07-14 18:41
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-07-14 18:42 UTC

**Comment by wei63w** [comment] 2017-07-17 01:26
@hramos    the podfile isn't enough detail?   this is my package.json  and need i open a new issue ?

```
{
  "name": "genilexubi",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.1",
    "react-native-amap-location": "0.0.4",
    "react-native-google-maps": "^1.0.0",
    "react-native-maps": "^0.15.3"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "2.1.0",
    "jest": "20.0.4",
    "react-test-renderer": "16.0.0-alpha.6"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

**Comment by hramos** [comment] 2017-07-17 17:29
You can either open a new issue, or ping me once you've updated the original post here using the Edit feature. You'll need to fill out every field in the new issue template.

**Comment by bcitdaltond** [comment] 2017-07-20 19:43
+1 Having the same issue.
