### ISSUE TITLE
Following instructions from https://facebook.github.io/react-native/docs/getting-started.html on a brand new laptop gave me error code 500

### ISSUE THREAD

**Issue by snandar** [facebook/react-native#21743] opened 2018-10-12 03:49 UTC
- [ ] Review the documentation: https://facebook.github.io/react-native
  - [ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment

  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz
      Memory: 746.89 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.11.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    SDKs:
      Android SDK:
        Build Tools: 26.0.3, 27.0.3
        API Levels: 26, 27
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.0 => 0.57.2 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
![screen shot ](https://user-images.githubusercontent.com/38772142/46846864-9e15cd80-cdaf-11e8-8030-d270db268b9f.png)

I followed the instructions given word for word and I received this error. I have tried the suggestions from others on the discussion page but it didn't work. I think the installation shouldn't be this hard, especially since I am following word for word from the site. 

I have tried the solutions from ;
https://github.com/react-community/create-react-native-app/issues/401
https://github.com/react-community/create-react-native-app/issues/401

## Reproducible Demo

**Comment by rodrigoelp** [comment] 2018-10-12 03:51
This is a duplicate of #21741

**Comment by rodrigoelp** [comment] 2018-10-12 03:54
Hi @snandar, I've had a similar issue... can you try killing the metro bundler and run this

```sh
react-native start --reset-cache
```

Then run again your android project.

**Comment by snandar** [comment] 2018-10-12 04:04
Thank you! It worked after following your post on #21741

**Closed** 2018-10-12 04:05 UTC
Labels: :globe_with_meridians:Networking

**Comment by rodrigoelp** [comment] 2018-10-13 02:39
Good to know it helped :)
