### ISSUE TITLE
PanResponder inside scrollView issue 

### ISSUE THREAD

**Issue by RD1991** [facebook/react-native#7444] opened 2016-05-08 04:32 UTC
Hi There,

Im having trouble with PanResponder into ScrollView. 
Defining my issue - I have a view which can be dragged into anywhere in the screen. This , my draggable view, is inside a scroll view. When I drag my view scroll view gets dragged. 

Is there any solution for this ? Im thinking that this is an [open issue](https://github.com/facebook/react-native/issues/1046) Not so sure about it. Sorry for spamming message, but can anyone out there get rid of this and provide a temporary solution ?

**Comment by damusnet** [comment] 2016-05-08 09:30
@facebook-github-bot duplicate #1046

**Comment by facebook-github-bot-8** [comment] 2016-05-08 09:40
@damusnet tells me this issue is a duplicate of #1046. Let's discuss there, closing this one.

**Closed by facebook-github-bot-8** 2016-05-08 09:40 UTC
Labels: Ran Commands
