### ISSUE TITLE
[0.54] Commits to cherry-pick into stable release

### ISSUE THREAD

**Issue by hramos** [facebook/react-native#18128] opened 2018-02-27 20:09 UTC
The thread containing issues that are blocking the 0.54 release and need to be addressed.

Please keep this list to critical bug fixes that are new in 0.54 and ideally have been merged into master -- post commit hashes rather than issue/PR numbers unless the issue/PR in question targets a problem specific to 0.54. The intent of these cherry-pick threads is not to solicit features but to fix things that make 0.54 substantially more launch-blocked than 0.53.

**Comment by hramos** [comment] 2018-02-27 20:10
- b60a727adbcfa785e3d1b13bf069b766216e60f8 has been proposed by @joshyhargreaves

**Comment by grabbou** [comment] 2018-03-01 16:59
Closing as the release is hitting npm soon. Hector, thank you for opening the issue.

**Closed by grabbou** 2018-03-01 16:59 UTC

**Comment by fungilation** [comment] 2018-03-02 22:53
Changelog still missing? https://github.com/facebook/react-native/releases

**Comment by hramos** [comment] 2018-03-03 00:33
See https://twitter.com/grabbou/status/969284993859117056 -- it's coming

**Comment by fungilation** [comment] 2018-03-05 17:01
"Draft complete; needs review" now, but still missing on where it matters publicly

**Comment by grabbou** [comment] 2018-03-05 17:36
Will be up in 2 hours.

**Comment by grabbou** [comment] 2018-03-05 17:39
I've also updated the release description to contain our current draft before I make it public. We are at the final step reviewing last commits.

For the next release, I'll make sure to update the release description a bit earlier and also, do a Twitter announcement from our account (React Native)

**Comment by grabbou** [comment] 2018-03-15 16:02
Cherry-picked

**Comment by andrew-wagner89** [comment] 2018-03-16 14:37
https://github.com/facebook/react-native/commit/b02b1670d65118c333d3e0b83ddc99d2dc39dbed to fix #18179

**Comment by itchingpixels** [comment] 2018-03-18 13:41
A new patch version would be much appreciated!
It'd fix both: https://github.com/facebook/react-native/issues/18179 & https://github.com/facebook/react-native/issues/18128, which is currently blocking quite a few people from using 0.54

**Comment by grabbou** [comment] 2018-03-19 06:22
Let me look at it first thing this morning and I'll release new versions
where needed.

Mike

**Comment by eliperkins** [comment] 2018-03-19 21:44
https://github.com/facebook/react-native/commit/a534672e132136e7bbd17c94a7f4e67149bcc67a to fix #18258 since it's a regression

**Comment by grabbou** [comment] 2018-03-20 21:04
I am waiting for one more fix to hit master and will chery-pick them all. Please follow the status here: https://github.com/react-native-community/react-native-releases/issues/8

**Comment by grabbou** [comment] 2018-03-21 19:12
Please report any additional requests / issues with this release over here: https://github.com/react-native-community/react-native-releases/issues/10
