### ISSUE TITLE
Getting a babel runtime error

### ISSUE THREAD

**Issue by iremlopsum** [facebook/react-native#13139] opened 2017-03-24 20:03 UTC
### Description

Hand an issue with modules, did a rimraf and reinstalled everything, after this I keep getting the following error

```
Error: Unknown named module: 'babel-runtime/core-js/object/entries' (http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:48)

_require@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:48:22
http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:971:42
global code@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:1014:3
```

Any ideas?

* React Native version: 0.42
* Platform: Android
* Development Operating System: Windoes
* Dev tools: Android Studio version 2.3

**Comment by hramos** [comment] 2017-03-28 18:49
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-03-28 18:49 UTC
