### ISSUE TITLE
immediatelyResetRouteStack does not reset stack RN 26

### ISSUE THREAD

**Issue by latusaki** [facebook/react-native#7805] opened 2016-05-27 16:08 UTC
My code has the following lines
```
navigator.immediatelyResetRouteStack(action.replaceStack);
navigator.push(action.route);
```
replaceStack looks like this: 

```
[
      Routes.Home(),
      Routes.Timesheet(),
      Routes.WeekView(date),
      Routes.DayView(date)
]
```

And individual routes look like this:

```
  Home() {
    return {
      id: 'home-view',
      title: 'Home',
      component: Routes.HomeView,
    };
  },
```

On RN 25 and before this worked fine.
On RN 26, the push happens, but no the Reset stack. Going back takes you to the source View
To test it I used exactly the same codebase, with the different react versions. There are no errors or warnings in the console. Will try to put together a playground example asap.

*Update*

Code Breaks on this line [847](https://github.com/facebook/react-native/blob/8975bb8e70948ea4b5938913ab12f1857cc4cb43/Libraries/CustomComponents/Navigator/Navigator.js#L847) of Navigator.js 

> ExceptionsManager.js:61 Cannot read property 'animationInterpolators' of undefined

To fix the issue I had to wrap `navigator.push(action.route)` in a setTimeout(fn, 5)

**Comment by lacker** [comment] 2016-10-21 07:29
I think we need a small sample app that reproduces this problem to make progress here. Since this issue is kind of old I am going to close it but feel free to reopen it if you have a rnplay.org link that is reproducing a bug here.

**Closed by lacker** 2016-10-21 07:29 UTC
