### ISSUE TITLE
[Accessibility] [iOS] Pressable with accessibilityRole="radio" or "checkbox " no longer focusable with keyboard on iOS

### ISSUE THREAD

**Issue by WebOnField** [facebook/react-native#45326] opened 2024-07-08 14:55 UTC
### Description

I'm discovering a new behavior when upgrading to iOS 17.5.1.

My radio button and checkbox components, using Pressable with, among others, accessibilityRole="radio" or accessibilityRole="checkbox", are no longer reachable in keyboard navigation.

### Steps to reproduce

1. Enable Bluetooth and turn on your Bluetooth keyboard
2. Connect your keyboard to your mobile
3. In order to allow control of the terminal by an external keyboard, it is necessary to activate the “Full keyboard access” option. To do this, go to Settings > Accessibility > Keyboards > Full keyboard access and activate “Full keyboard access”
4. Try to navigate and activate a pressable element with accessibilityRole="radio" or accessibilityRole="checkbox"

### React Native Version

0.72

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
-
```

### Stacktrace or Logs

```text
-
```

### Reproducer

https://snack.expo.dev/@pierre-a11y/pressable-with-accessibilityrole-not-focusable-with-keyboard

**Comment by cortinico** [comment] 2024-07-09 09:10
Closing as this is a duplicate of:
- https://github.com/facebook/react-native/issues/43266
- https://github.com/facebook/react-native/issues/45096

**Closed by cortinico** 2024-07-09 09:10 UTC
Labels: Platform: iOS, API: Keyboard, Needs: Author Feedback, Needs: Version Info

**Comment by WebOnField** [comment] 2024-07-09 09:54
@cortinico  Just to be sure, the reported anomaly is not a problem in a screen reader context but only in keyboard navigation.
For our part we are in 0.72 and the roles are well vocalized. On the other hand, my only problem is the fact that we don't focus these elements in keyboard navigation.

**Comment by cortinico** [comment] 2024-07-09 13:28
> @cortinico Just to be sure, the reported anomaly is not a problem in a screen reader context but only in keyboard navigation. For our part we are in 0.72 and the roles are well vocalized. On the other hand, my only problem is the fact that we don't focus these elements in keyboard navigation.

Understand, however I suspect the underlying cause is the same.

Also to set expectations: we're currently hyperfocused on New Architecture only bugs. As this is not the case, we can't currently prioritize it. We're happy to receive a PR from the community that would fix it though
