### ISSUE TITLE
[!] Unable to find a specification for `Yoga (= 0.42.3.React)` depended upon by `React/Core`

### ISSUE THREAD

**Issue by BaoBaoJianqiang** [facebook/react-native#13046] opened 2017-03-21 08:00 UTC
When I use RN 0.42 in my old iOS project, I define a pod file as follows:

project 'RN3.xcodeproj'

target 'RN3' do

pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'RCTImage',
  'RCTNetwork',
  'RCTText',
  'RCTWebSocket',
]

end

When I exec pod install in command line, there is an error message:
[!] Unable to find a specification for `Yoga (= 0.42.3.React)` depended upon by `React/Core`.

I check the React.podspec, I think there is something wrong in this file, is anybody meet the same issue?

**Comment by toureek** [comment] 2017-03-21 09:50
Add this line in your Podfile. Have a try.
pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

**Comment by BaoBaoJianqiang** [comment] 2017-03-21 11:34
Yoga works now. but anther issue occurs:

platform :ios, '10.2'
project 'RN4.xcodeproj'

target 'RN4' do

pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'RCTImage',
  'RCTNetwork',
  'RCTText',
  'RCTWebSocket',
]

end

In the workspace, #include <folly/dynamic.h>, Xcode says "dynamic.h file not found".

**Comment by hramos** [comment] 2017-03-21 18:35
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-03-21 18:35 UTC

**Comment by flyingxu** [comment] 2017-12-10 03:49
[!] Unable to find a specification for `yoga (= 0.51.0.React)` depended upon by `React/Core`

I had a similar problem today and I fixed it by adding to my Podfile:
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

`'yoga'` is in lowercase.
