### ISSUE TITLE
Connection with remote debugger is greatest slow 

### ISSUE THREAD

**Issue by sunnynegi** [facebook/react-native#16043] opened 2017-09-21 06:37 UTC
Hi React native development,

While using react native remote js debugging app is slow or sometime it's take near about 15 to 30 minutes then app is start and after crash.
I am using react native framework for my app development but it's really hard to develop app in this framework.

Or Team if you have alternative way to debug the app then plz let me know.

**Comment by hramos** [comment] 2017-09-21 15:21
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue that meets the requirements set forth in the template. Thanks!

**Closed by hramos** 2017-09-21 15:21 UTC
