### ISSUE TITLE
[bug]Touchable* & ScrollView & TextInput can't work together.

### ISSUE THREAD

**Issue by sulinixl** [facebook/react-native#7432] opened 2016-05-07 03:21 UTC
---
Example(rnplay): [TouchableBug](https://rnplay.org/apps/b-hrpA)
Version: **0.24**
Occur: **both(iOS & Android) on Mac.**

---

When `TextInput`and`ScrollView`put together, any `Touchable*` in the `ScrollView` can't receive its onPress event immediately.

In short, the structure of `Touchable* & ScrollView & TextInput` like this:

* TextInput
* ScrollView
  * Touchable*
  * Touchable*

It seems like that the **first touch event** was eaten by `ScrollView`, after that the `ScrollView` is focus and the `TextInput` is blur, but `Touchable*` can't get pressed.
The `Touchable*` can only capture the **second touch event**.

BTW: when I use `View` replace the `ScrollView`, everything will be properly.

You can find my example code in the [TouchableBug](https://rnplay.org/apps/b-hrpA).

**Comment by damusnet** [comment] 2016-05-07 19:24
Hi @sulinixl could this be the same issue as #7031?

**Comment by sulinixl** [comment] 2016-05-08 01:26
@damusnet I think you are right.
It is same, both caused by `ScrollView` and `TextInput`.

**Comment by damusnet** [comment] 2016-05-08 09:26
@facebook-github-bot duplicate #7031

**Comment by facebook-github-bot-3** [comment] 2016-05-08 09:27
@damusnet tells me this issue is a duplicate of #7031. Let's discuss there, closing this one.

**Closed by facebook-github-bot-3** 2016-05-08 09:27 UTC
Labels: Ran Commands
