### ISSUE TITLE
Inconsistent image bundling in Android

### ISSUE THREAD

**Issue by wildQueequeg** [facebook/react-native#13200] opened 2017-03-29 14:06 UTC
I'm using "react-native": "0.41.2", but have been having this issue since well before this release.

Sometimes when I bundle and build my android project, some of the images won't show up. The number, and which images are inconsistent as well. If I bundle again, some other images might show up, but others will disappear. If I bundle and check all of them a few times, they might all show up at some point... Any ideas?

**Comment by hramos** [comment] 2017-03-29 17:22
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-03-29 17:22 UTC
