### ISSUE TITLE
When dragged in TabBar application is crashing.

### ISSUE THREAD

**Issue by jasonkoirala** [facebook/react-native#16944] opened 2017-11-23 10:05 UTC
### Is this a bug report?

Yes

### Environment

Environment:
  OS: Windows 10
  Node: 8.9.0
  Yarn: Not Found
  npm: 4.6.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  2.3.0.0 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.3 => 0.50.3

  Target Platform: Android 

 I am developing an app which contains TabBar. Clicking on each Tab makes me go the page of the tab but whenever I drag any of the Tab I get error : Unsupported top level event type "topScrollBeginDrag" dispatched.

### Expected Behavior
App shouldn't crash.
 Whenever we drag on element it shouldn't throw any exception. However, TabBar is throwing this unusual error.

### Actual Behavior

  Here is the how my TabBar is laid on my application. The ripple effect in below screenshot is when I drag my finger on it. As soon as I drag I get red screen error below this image.
![screenshot_1511430971](https://user-images.githubusercontent.com/33828344/33167191-d425a9a2-d064-11e7-9075-f2638f56b00b.png)

![screenshot_1511430852](https://user-images.githubusercontent.com/33828344/33167075-84f9e032-d064-11e7-8d3c-cda0f7c7a89c.png)

### Reproducible Demo

 Here is the link to my repo: [TabBarIssue](https://github.com/jasonkoirala/TabBarIssue)

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by CarlosRodrigues** [comment] 2018-01-15 23:38
This seems react-native related. Have a look here (https://github.com/facebook/react-native/issues/16522). People are saying that downgrading to 0.49.5 solves it, but I'm missing the 'react-native-gesture-handler' after downgrading.

**Comment by hramos** [comment] 2018-03-20 19:17
Duplicate of #16522

**Closed by hramos** 2018-03-20 19:17 UTC
