### ISSUE TITLE
unable to resolve module 'react/lib/ReactDebugCurrentFrame'

### ISSUE THREAD

**Issue by ShanthiSenguttuvan** [facebook/react-native#14252] opened 2017-05-30 11:07 UTC
i have update the react-native version to 0.44.2. then i got error ,
error: bundling: UnableToResolveError: Unable to resolve module `react/lib/ReactDebugCurrentFrame` from `Somepath/node_modules/react-native/Libraries/Renderer/src/renderers/shared/fiber/ReactFiberContext.js`: Module does not exist in the module map or in these directories:
  Somepath/node_modules/react-native/node_modules/react/lib

**Comment by hramos** [comment] 2017-05-30 18:02
Hey @ShanthiSenguttuvan  thanks for reporting this issue!

As it happens, without sufficient repro steps, we can't really act on this issue.  It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-05-30 18:02 UTC
