### ISSUE TITLE
Crash  in JSCExecutor.cpp when reloading JS on error (iOS)

### ISSUE THREAD

**Issue by VinDeng** [facebook/react-native#15716] opened 2017-08-31 03:22 UTC
Using commas + R or click reload when in the red error message screen has chance to make it crash.

Code due to crash:
path: /#rootpath/react-native/third-party/glog-0.3.4/src/logging.cc 

```
static void logging_fail() {
#if defined(_DEBUG) && defined(_MSC_VER)
  // When debugging on windows, avoid the obnoxious dialog and make
  // it possible to continue past a LOG(FATAL) in the debugger
  _asm int 3
#else
  abort();
#endif
}
```

Since I build In Debug Environment,  I guess the problem is I did not use VS IDE.

Xcode: 8.3.3
Simulator: iPhone 7 Plus - iOS 10.3
React Native: 0.47.2

**Comment by hramos** [comment] 2017-08-31 16:37
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-08-31 16:37 UTC
