### ISSUE TITLE
run-android is not working

### ISSUE THREAD

**Issue by dinyrepo** [facebook/react-native#20308] opened 2018-07-20 04:18 UTC
![screenshot_1532059848](https://user-images.githubusercontent.com/15281160/42983108-7974a184-8c02-11e8-9fcb-813309453b86.png)
## Environment React Native Environment Info:
   System:
     OS: Windows 10
     CPU: x64 Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz
     Memory: 812.65 MB / 7.88 GB
   Binaries:
     Yarn: 1.7.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
     npm: 6.1.0 - C:\Program Files\nodejs\npm.CMD
   IDEs:
     Android Studio: Version  3.0.0.0 AI-171.4443003

## Description
I am using react-native version 0.56, i have created the android project using the command
` react-native init helloworld --package=com.helloworld`
when i am running my android project using the command `react-native run-android` my application is getting launched but i am getting 'index.android.bundle' error. Please find the attached screenshot for reference.

## Reproducible Demo
this can be reproduced by using windows 10 machine with the above environment details and with react-native version 0.56.

**Comment by amitanand2406** [comment] 2018-07-20 10:52
Just add adb path in environment variables in user variables

**Comment by dinyrepo** [comment] 2018-07-23 04:20
@amitanand2406  i have my adb path in environment variables.

**Comment by dinyrepo** [comment] 2018-07-23 04:22
@marla-singer  i have followed that commands it is working for one time, but it is not working for the next time and it takes most the time, since i am running this command every time after i make the changes.

**Comment by kelset** [comment] 2018-07-23 09:36
Probably duplicate of https://github.com/facebook/react-native/issues/19953?

**Comment by dinyrepo** [comment] 2018-07-23 10:00
@kelset  yes i am getting the same issue, So do we need to wait till 0.56.1 is getting released?

**Comment by kelset** [comment] 2018-07-23 10:02
Ok since it's a duplicate I'm going to close this in favour of that in order to reduce duplication.

I've just posted a comment there about what's going to happen, sadly it has been really complex to find a solution :(

**Closed by kelset** 2018-07-23 10:02 UTC
Labels: :grey_question:Needs More Information, :large_blue_diamond:Android
