### ISSUE TITLE
ScrollView/FlatList scrolls sometime in the wrong direction

### ISSUE THREAD

**Issue by kabus202** [facebook/react-native#22859] opened 2019-01-03 17:57 UTC
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment

 React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 37.48 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.12.0 - /usr/local/bin/node
      Yarn: 1.12.1 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 22, 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.57.8 => 0.57.8 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-rename: 2.4.0

## Description
ScrollView/FlatList scrolls sometimes to opposite direction during scroll with one hand. 

Same code works flawless with expo. Whats the difference between ScrollView   

[see video:](https://streamable.com/chrik)

[stackoverflow issue](https://stackoverflow.com/questions/54098876/react-native-scrollview-scrolls-sometimes-in-wrong-direction?noredirect=1#comment95039173_54098876)

## Reproducible Demo

Just use a blank project with a flatlist or scrollview

**Comment by kabus202** [comment] 2019-01-07 05:03
I also made a demo on expo 

[example demo](https://snack.expo.io/SJ__p8gz4)

**Comment by esmatptr** [comment] 2019-01-10 07:36
I have the same issue on Android 9 devices.

react-native: 0.54.0

**Comment by kabus202** [comment] 2019-01-10 07:58
related #22938 ?

**Comment by gsunsnackv** [comment] 2019-01-18 07:22
@kabus202 @esmatptr  When I have a few images the scroll is extremely choppy (ScrollView or FlatList), are you experiencing this? Also Android 9.0 only #22744

**Comment by esmatptr** [comment] 2019-01-19 17:20
I updated the react native version to 0.57.8 and the scroll is working as expected now

**Comment by rickhanlonii** [comment] 2019-03-19 16:17
Looks like a dupe of #22938, thanks @kabus202

**Closed by rickhanlonii** 2019-03-19 16:17 UTC
Labels: Component: FlatList, Component: ScrollView, Type: Bug Report

**Comment by kabus202** [comment] 2019-05-30 12:51
@rickhanlonii  I don't think it's related to #22938 
I'm using android 8 and this issue still exist in v0.59.8 

I did some research, i tried to use the exact same code in version react-native v56.1 and it's working fine without any problems.

Can you re-open this ticket?

**Comment by rickhanlonii** [comment] 2019-05-31 12:42
@kabus202 why do you think it's unrelated to #22938?

**Comment by kabus202** [comment] 2019-06-01 12:19
@rickhanlonii because im using android 8 and #22938 is related to android 9. 

In react-native version 56.1 it's working flawless without any problems.

**Comment by fangasvsass** [comment] 2019-07-15 08:46
same issue react native version 0.59.9
