### ISSUE TITLE
[ScrollView] Keyboard doesn't hide after focusing on TextInput

### ISSUE THREAD

**Issue by skoob13** [facebook/react-native#2150] opened 2015-07-28 16:48 UTC
There are two TextInput elements.
<img width="311" alt="2015-07-28 21 17 47" src="https://cloud.githubusercontent.com/assets/13541795/8936857/32839fa2-356e-11e5-9746-292f9ceb1684.png">
When I touch the first one, then the second one and finally the ScrollView which contains both of them, the keyboard doesn't hide. But I touch the second again and voila - the ScrollView hides my keyboard.
If I touch only one of those and then the ScrollView, it hides as normal as it should be.
Moving from one TextInput to another, the onBlur event doesn't appear to happen. Do you have any ideas why my keyboard doesn't hide?

**Comment by javierM84** [comment] 2015-07-30 09:25
I am having the same issue with ScrollView with version 0.7 (maybe this is fixed in 0.8rc)  apparently the issue is with the prop keyboardShouldPersistTaps it doesn't work properly if you try to do the next:

 - Type something in the first TextInput long enough, let's say 20 characters or more.

 - Then type again something in the second TextInput, the same number of characters more or less again.

- If you tap somewhere in the ScrollView it should dismiss the keyboard but it doesn't it is still there

Sometimes the prop keyboardShouldPersistTaps works if you don't type a long text or if you type a long text but you don't jump to another text input (you have to type in 2 text inputs)

**Comment by alinz** [comment] 2015-10-01 15:35
@skoob13, @javierM84
Here's the solution for this. First of if you are using 0.11.x you have to explicitly pass `keyboardShouldPersistTaps={false}` to your `ScrollView` or `ListView`. Second, if you have multiple text field and you want to make sure you can dismiss the keyboard if the user touch on `ScrollView`, you have to explicitly call `focus()` on each onFocus.

Here's a code for that

https://rnplay.org/apps/y0oAuQ

@brentvatne any thought on this?

**Comment by chirag04** [comment] 2015-10-01 15:40
@alinz @brentvatne docs say ``false`` is the default behaviour for ``keyboardShouldPersistTaps``. Seems like a bug?

FYI, I can produce this on master as well.

**Comment by chirag04** [comment] 2015-10-01 15:42
@alinz Just sure you pull request on this. https://github.com/facebook/react-native/pull/3178. That clears everything. thanks.

**Comment by despairblue** [comment] 2015-10-18 19:46
@alinz this is a workaround for the tap issue, but the onFocus event is dispatched too late, e.g. if you have a Touchable around the TextInput the Touchable's onPress event is dispatched before the TextInput can be focussed. This breaks the underline animation of the [Material Design TextFields](https://github.com/xinthink/react-native-material-kit/issues/42)

The problem is that https://github.com/facebook/react-native/blob/master/Libraries/Components/TextInput/TextInputState.js#L40 isn't called when the second TextInput is tapped. That is because in https://github.com/facebook/react/blob/master/src/renderers/shared/event/EventPluginUtils.js#L187 there is a different dispatchListender listening to the TextInputs depending on which TextInput is focused first.

The first dispatchListender is https://github.com/facebook/react-native/blob/master/Libraries/Components/Touchable/Touchable.js#L356 and works.
But the second is https://github.com/facebook/react-native/blob/master/Libraries/Components/ScrollResponder.js#L264 and doesn't.

That means the second TextInput is never marked as focused.

**Comment by niftylettuce** [comment] 2015-11-01 16:56
Still not working for me - when I click off a text input with a scroll view that's behind it, it doesn't blur.

**Comment by niftylettuce** [comment] 2015-11-01 17:11
I have to explicity declare `keyboardShouldPersistTaps={false}`, it's like the default isn't working or something?

**Comment by Taakn** [comment] 2016-02-09 10:49
+1 I am also having issues with events in ScrollView.

**Comment by shtefanntz** [comment] 2016-02-12 21:35
+1 I'm having issues with this as well :(

side question: why would only ScrollView handle taps in a way that TextInputs lose focus and Views don't?

**Comment by everfire130** [comment] 2016-04-13 12:35
+1 I'm having issues.Any solutions?

**Comment by ninjz** [comment] 2016-05-31 08:02
+1

**Comment by someok** [comment] 2016-05-31 10:33
Wrap the container with TouchableWithoutFeedback

onPress: TextInput.State.blurTextInput(TextInput.State.currentlyFocusedField
());

**Comment by mkonicek** [comment] 2016-10-27 21:48
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/scrollview-keyboard-doesnt-hide-after-focusing-on-textinput

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Closed by mkonicek** 2016-10-27 21:48 UTC
Labels: Icebox
