### ISSUE TITLE
Print: Entry, ":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by thiagovictorino** [facebook/react-native#14447] opened 2017-06-10 18:28 UTC
I am trying to run a new react-native project but I have an error

My setup
* xCode 8.3.3
* Node v6.11.0
* npm v3.10.10
* react-native v0.45.1

```
** BUILD FAILED **


The following build commands failed:

	CompileC /Volumes/300GB/react-native/jlledm/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/third-party.build/Objects-normal/x86_64/MallocImpl.o /Volumes/300GB/react-native/jlledm/node_modules/react-native/third-party/folly-2016.09.26.00/folly/detail/MallocImpl.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/jlledm.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/jlledm.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

I tried everything that others similar issues say:

* Change the File->Project Settings->Advanced->Custom changing to  "build/Build/Products"
* Upgrade and update everything
* lsof -n -i4TCP:8081 to kill a process that was running
* react-native upgrade
* Delete node_modules/, clear the cache and install again
* Doubleclick on the RCTWebSocket project in your navigator and remove the flags under build settings > custom compiler flags
* Setting manually the Bundle Identifier
* Run npm start -- --reset-cache
* rm -rf ios/build and run-ios again...

If I try to compile in xcode, I had this problem

![screen shot 2017-06-10 at 15 11 16](https://user-images.githubusercontent.com/443991/27005165-2bb51476-4def-11e7-9955-6e62fabc98ed.png)

And I just run the react-native init projectName and react-native run-ios the get this error

Have anyone a modern (2017) solution for this problem?

**Comment by Mikael491** [comment] 2017-06-10 23:40
@thiagovictorino I was able to fix by doing 'npm start' or 'npm run ios' instead... there seems to have been changes in version 0.45

**Comment by nebtrx** [comment] 2017-06-11 06:20
Having the same issue here. However, doing `npm start` or `npm run ios` didn't fixed the issue

**Comment by thiagovictorino** [comment] 2017-06-11 19:29
Thank you @Mikael491, but it didn't works =(

**Comment by Mikael491** [comment] 2017-06-11 19:44
@thiagovictorino It looks like you just created the project, try doing 'npm install -g create-react-native-app' and then creating the project with 'create-react-native-app <Project-Name>' like in the docs...this is how I began my solution

**Comment by thiagovictorino** [comment] 2017-06-11 20:10
Hi @Mikael491! This open the new project, but in a very different folder structure (very lean) and with 0.44 react-native version. It could be a partial solution and I am grateful for your help. But I really to to work with "old way" like a official document says.

**Comment by RooneyJung** [comment] 2017-06-12 02:16
I have the same issue.
Using 'create-react-native-app' and 'npm run eject' is fine. (RN version is 0.44)
But 'react-native init ...' has the problem. (it's RN version is 0.45)

-> 'react-native init ...'
-> remove 'node_modules'
-> change RN version to 0.44 and react version 16.0.0-alpha6 in package.js
-> 'npm install'
is FINE...

But I have really serious problem.
My project that created a month before (it's RN version 0.44.2) has same issue;;
Only few days ago (when RN version 0.44 at RN homepage), the project was fine...

**Comment by hramos** [comment] 2017-06-12 20:54
Can you confirm that 0.45.1 is being used here? The issue you're describing was present in 0.45 but should have been fixed.

**Comment by thiagovictorino** [comment] 2017-06-13 14:49
Hello @hramos, yes it is

```
"dependencies": {
                "react": "16.0.0-alpha.12",
                "react-native": "0.45.1"
        },
```

**Comment by phuwasit** [comment] 2017-06-14 11:36
react-native 0.45.1
i try to solve this problem by running shell script in react-native package manually

1. open terminal
`node_modules/react-native/ios-install-third-party.sh`
2. after downloading finished, set pemission to .rncache folder
`sudo chown -R $(whoami) ~/.rncache`
3. run
`react-native run-ios`

**Comment by thiagovictorino** [comment] 2017-06-14 12:06
When I run ios-install-third-party.sh got this error

```
folly-2016.09.26.00/folly/fibers/test/FibersTest.cpp: (Empty error message)
tar: Error exit delayed from previous errors.
```

Finally running react-native run-ios again I got the same error:

```
Installing build/Build/Products/Debug-iphonesimulator/jlledm.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/jlledm.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

**Comment by radko93** [comment] 2017-06-14 15:44
@phuwasit your solution doesn't help me.

**Comment by phuwasit** [comment] 2017-06-15 05:49
@radko93 @thiagovictorino 
Try this
1. Download 4 zip files
https://github.com/google/glog/archive/v0.3.4.tar.gz
https://github.com/google/double-conversion/archive/v1.1.5.tar.gz
https://github.com/react-native-community/boost-for-react-native/releases/download/v1.63.0-0/boost_1_63_0.tar.gz
https://github.com/facebook/folly/archive/v2016.09.26.00.tar.gz

2. unzip
- boost_1_63_0
- double-conversion-1.1.5
- folly-2016.09.26.00
- glog-0.3.4

3. copy 4 folders to **node_modules/react-native/third-party**
4 run
`sudo react-native run-ios`

**Comment by tuneZola** [comment] 2017-06-16 05:17
Having the same issue.

**Comment by tuneZola** [comment] 2017-06-16 06:03
+1

**Comment by afshinm** [comment] 2017-06-17 19:10
I have the same problem and provided solutions didn't work for me. Xcode 8.0, React native 0.45.1

**Comment by henrydeclety** [comment] 2017-06-21 00:29
same problem with react native 0.45.1

**Comment by SamMatthewsIsACommonName** [comment] 2017-06-22 18:36
This is one of seemingly many factors but at the very least make sure your project folder or any of the folders it's within from ~/ down don't have spaces in them

**Comment by suhaotian** [comment] 2017-06-28 02:44
Same here and no space in path!

**Comment by RyanWan** [comment] 2017-07-02 00:11
My RN project works fine locally. When I push it to git and then pull it down. npm install and link all libraries. I cannot run the project because of CFBundleIdentifier does not exist.
All the approaches don't work for me.Then error message is 
`
library not found -lRCTBEEPickerManager.a
`
Then I go to Build Phase=> link binary with libraries and delete a file called libRCTBEEPickerManager.a
This at least allow me to build from xcode. But I still cannot build from command line.

**Comment by yozef** [comment] 2017-07-12 15:07
Devs keep ignoring this issue, and keep closing them. My Faith in RN is loosing momentum.

**Comment by thiagovictorino** [comment] 2017-07-12 17:36
As you can see at my question @SamMatthewsIsACommonName I have no space in my path
```
/Volumes/300GB/react-native/jlledm/ 

```

**Comment by DiegoZen** [comment] 2017-07-12 23:24
I had the same problem and it turned out to be a matter of updates. I had a pending update of macOS Sierra to version 10.12.5, I did it and now it works.

**Comment by yozef** [comment] 2017-07-13 00:06
react-native-cli: 2.0.1
react-native: 0.46.1
npm: 4.2.0
node -v: 6.9.1
watchman: 4.7.0
xcode: 8.3.3
Mac 10.12.5

Still not working

**Comment by wei63w** [comment] 2017-07-13 01:34
@RooneyJung  My project same to your's

**Comment by whg1412** [comment] 2017-07-24 09:05
@thiagovictorino Check your node_modules/react-native/third-party file,normal size is 160M.For some reason,this file can't download full version can cause this problem.I copy this file from others,replace,problem solved.

**Comment by wei63w** [comment] 2017-07-24 10:01
e  first , check your permission of manager sudo chmod -R 777 yourdirname . 
and then  if also has error  you can lower you react-native version to 42.0, you can try it.

**Comment by gopaldevra** [comment] 2017-07-24 13:27
Same error after downgrading the react native version on my system but on the another system working properly, what the issue, I can't figure out, Is this going to fix or not?

**Comment by isuhendro** [comment] 2017-07-26 04:55
@whg1412 my `third party` folder is 32M (1265 items). Where could we get the full version of it?

**Comment by whg1412** [comment] 2017-07-26 06:49
@isuhendro You can get it here https://github.com/whg1412/ThirdParty.I copy it from others,solve my problem.

**Comment by GabrielLidenor** [comment] 2017-08-01 16:49
I had this issue today and I figured I was using an old version of Node JS. Try upgrading it.

**Comment by dgurns** [comment] 2017-08-02 18:50
I am having this issue now: 
React Native 0.47.1
MacOS Sierra 10.12.6
XCode 8.3.3

None of the solutions I've seen (removing spaces in path; changing relative build location) have worked.

**Comment by GabrielLidenor** [comment] 2017-08-02 18:58
@dgurns I added the third part files manually and it worked.

**Comment by dgurns** [comment] 2017-08-02 19:03
@GabrielLidenor you manually upgraded Node JS? 

Could you explain the steps for how to do that please?

**Comment by dgurns** [comment] 2017-08-02 19:31
@GabrielLidenor what versions of React Native, MacOS, Node, and XCode are you running?

I tried adding the third-party files manually but it didn't work. What steps did you follow?

**Comment by GabrielLidenor** [comment] 2017-08-02 22:39
@dgurns Well, first of all I updated my Node JS to the latest version available. After that I created a new project using the latest version of React-Native and then, finally I replaced the third-party folder. 
Then I run: react-native run-ios.

**Comment by hramos** [comment] 2017-08-03 17:30
Duplicate of #14447

**Comment by hramos** [comment] 2017-08-03 17:31
Closed the wrong issue - let's leave this one open as the master issue.

**Comment by hramos** [comment] 2017-08-03 17:45
I just merged several related issue. Let's avoid opening new issues for the same error message for now. It seems like the preferred workaround at this time is to do the following:

```
rm -rf ~/.rncache
react-native run-ios
```

Wait for the last command to finish in its entirety. You should see several messages that follow this format: `curl: Saved to filename 'glog-0.3.4.tar.gz'`.  Do not press CTRL+C to kill the process.

Thanks to @jjerryhan for arriving at the above list of steps (see [Handling third party build error on React Native](https://medium.com/@jjerryhan/handling-third-party-build-error-on-react-native-0-46x-445f867e7a2b) for an explanation behind why some people may end up in this state).

I believe I saw some PRs land recently that may deal with this particular issue, but I'm not 100% sure. I'll come back and update this issue with my findings.

**Comment by hramos** [comment] 2017-08-03 17:56
It looks like @mhorowitz has looked at this before (see a555551aaf1de1aff2a58f7aa09e970bcd003f7f and his [comment](https://github.com/facebook/react-native/issues/14423#issuecomment-316872764) on #14423).

If you see the following message, "Unpacking 'SOME_FILENAME_HERE' failed.  Debug info:", when running `react-native run-ios`, please comment here with the output following the "Debug info:" phrase.

Since Marc has already commented over at #14423, I'll mark that as the canonical issue and point all other issues there. Sorry for the churn.

**Comment by hramos** [comment] 2017-08-03 17:57
Duplicate of #14423

**Closed by hramos** 2017-08-03 17:57 UTC

**Comment by rodmba** [comment] 2017-08-07 16:07
I replaced the third-party folder with this https://github.com/whg1412/ThirdParty as @GabrielLidenor sad and it worked for me too.

**Comment by FacuAcosta** [comment] 2017-08-17 08:43
Having this issue again, none of the above worked.

react: 16.0.0-alpha.12
react-native: 0.47.1
npm: 5.3.0
node -v: 6.10.0
watchman: 4.7.0
xcode: 8.3.3
Mac 10.12.6

I have another project using react-native 0.44.0 and perfectly works, but when I tried to create a fresh one I'm having this issue.

**Comment by noasquare** [comment] 2017-08-20 01:11
downgrade method can't work either, after trying all these so called solution, i finally decide to use my ultimate method that is to "wait", these stuff is too time consuming.

**Comment by sky0014** [comment] 2017-08-22 13:51
1. make sure your four tar.gz is completely downloaded in ~/.rncache
2. remove node_modules/react-native/third-party
3. react-native run-ios again

this works for me.

**Comment by hramos** [comment] 2017-08-24 19:34
What @sky0014 mentions is already covered in #14423, the master task tracking this issue.
