### ISSUE TITLE
The docs have rendering issue with Chromium

### ISSUE THREAD

**Issue by oren** [facebook/react-native#10634] opened 2016-10-30 22:54 UTC
### Description

There is a bug with react-native docs and chromium browser - some pages are not readable.
Here is a screenshot:

![doc](https://cloud.githubusercontent.com/assets/6517/19840677/b695ae48-9eb8-11e6-8ab0-2e5fb96035ce.png)
### Additional Information
- Chromium Version 53.0.2785.143 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

**Comment by ide** [comment] 2016-10-31 02:13
cc @hramos @lacker

**Comment by brentvatne** [comment] 2016-10-31 11:06
Seems to be a problem with iframes and https://github.com/dabbott/react-native-web-player cc @dabbott

**Comment by hramos** [comment] 2016-10-31 15:31
I was not able to repro on Chromium 56.0.2906.0 (64-bit) on macOS Sierra. @oren can you try building a newer version of Chromium and let us know if it is still an issue on Ubuntu?

**Comment by dabbott** [comment] 2016-10-31 23:25
Good find... I will see if I can repro as well

**Comment by dabbott** [comment] 2016-10-31 23:49
Easy to reproduce for me. Happens on Ubuntu 16.04 (64-bit) Version 50.0.2661.102 as well.

The `display: flex` is stripped from every single element. Could be a problem with the inline-style prefixing library I'm using: https://github.com/rofrischmann/inline-style-prefixer/issues/78. I'm going to try updating the library and see if that solves.

![ubuntu_64-bit_16_04](https://cloud.githubusercontent.com/assets/1198882/19875085/2c4c517c-9f87-11e6-9646-95fa2ad54c08.png)

**Comment by dabbott** [comment] 2016-11-01 01:25
Fixed with https://github.com/facebook/react-native/pull/10667

You can also test by hitting the iframe directly at: https://cdn.rawgit.com/dabbott/react-native-web-player/gh-v1.2.6/index.html

**Comment by hramos** [comment] 2016-11-01 17:59
Thanks for the PR @dabbott !

**Closed** 2017-03-10 19:47 UTC
Labels: Documentation
