### ISSUE TITLE
URGENT :Unable to build 

### ISSUE THREAD

**Issue by gg3519** [facebook/react-native#25301] opened 2019-06-18 16:02 UTC
While compiling the source code of reactnative we are getting following error:

Task :app:processDebugManifest FAILED
/Users/travash/Rayudu/Projects/NewNCC/android/app/src/main/AndroidManifest.xml:22:18-86 Error:
        Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86
        is also present at [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:26:5-77:19 to override.

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

FAILURE: Build failed with an exception.

Please assist in solving this issue.

**Comment by rhamretskyi** [comment] 2019-06-18 16:19
I have also. Previously the project worked fine. I cleared cache and reinstall all packages and it didn't help.

>   React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 1.83 GB / 16.00 GB
      Shell: 3.0.2 - /usr/local/bin/fish
    Binaries:
      Node: 12.4.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.6 => 16.8.6
      react-native: 0.59.8 => 0.59.8
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by brunoluigi** [comment] 2019-06-18 16:58
Since yesterday I've been have this issue, I bet that it has something to do with AndroidX and the new support library versioning scheme. Can't make it work yet, though.

**Comment by rhamretskyi** [comment] 2019-06-18 17:11
I found a solution for my case. This was due to update [Google Play Services and Firebase](https://developers.google.com/android/guides/releases#june_17_2019) I changed versions to previous and it works:
`googlePlayServicesVersion = "16.1.0"`
`firebaseVersion = "17.6.0"`

**Comment by bfernandes94** [comment] 2019-06-18 18:22
rhamretskyi,

I didn't find googlePlayServicesVersion and firebaseVersion in my project. 

How can I update this?

**Comment by Poyser1911** [comment] 2019-06-18 18:28
For me it was around:
1. cd into android and run  `./gradlew app:dependencies`
2. Override any denpendencies with under `androidx` under it with the previous version
example:
In the app/build.gradle:
```
configurations.all {
    resolutionStrategy.force 'com.google.android.gms:play-services-base:16.1.0', 'com.google.android.gms:play-services-basement:16.2.0', 'com.google.android.gms:play-services-stats:16.0.1'
}
```
This line alone fixed it in my case.

**Comment by AndyShi12** [comment] 2019-06-18 19:04
> I found a solution for my case. This was due to update [Google Play Services and Firebase](https://developers.google.com/android/guides/releases#june_17_2019) I changed versions to previous and it works:
> `googlePlayServicesVersion = "16.1.0"`
> `firebaseVersion = "17.6.0"`

Yep this finally resolved my issue also! For those looking, add the following to your `gradle.properties` then clean/rebuild
```
googlePlayServicesVersion=16.1.0
firebaseVersion=17.6.0
```

**Comment by smaris** [comment] 2019-06-18 19:34
Tried with several gradle versions (android/build.gradle):
```
buildscript {
    dependencies {
        //classpath 'com.android.tools.build:gradle:3.2.1'
        //classpath 'com.android.tools.build:gradle:3.3.0'
        classpath 'com.android.tools.build:gradle:3.3.1'
        //classpath 'com.android.tools.build:gradle:3.4.1'
        //classpath 'com.android.tools.build:gradle:4.3.0'
     }
}
ext {
    buildToolsVersion = "28.0.3"
    minSdkVersion = 24
    compileSdkVersion = 28
    targetSdkVersion = 26
    supportLibVersion = "28.0.0"
}
```

But keep getting issues with `react-navigation` sub dependency `react-native-gesture-handler`

```Caused by: org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':react-native-gesture-handler:compileReleaseJavaWithJavac'.```

**Comment by mhkhung** [comment] 2019-06-18 20:08
After 2 full days.. I got my RN 0.55.2 project to work by:
android/app/build.gradle:
```
    implementation "com.google.android.gms:play-services-auth:16.0.1"
    implementation "com.google.android.gms:play-services-base:16.0.1"
    implementation(project(":react-native-device-info"),  {
      exclude group: "com.google.android.gms"
    })
    implementation "com.google.android.gms:play-services-gcm:16.0.0"
    implementation(project(":react-native-push-notification"),  {
        exclude group: "com.google.android.gms"
        exclude group: "com.google.firebase"
    })
    implementation(project(":react-native-google-analytics-bridge"),  {
      exclude group: "com.google.android.gms"
    })
    implementation(project(":react-native-google-signin"),  {
      exclude group: "com.google.android.gms"
    })
    implementation "com.google.android.gms:play-services-analytics:16.0.8"
```

and to  android/build.gradle:
```
buildscript {
    ext {
        googlePlayServicesVersion = "16.+"
        firebaseVersion = "17.3.4"
    }
```
```
        resolutionStrategy {
            force "com.google.android.gms:play-services-basement:16.0.1"
            force "com.google.android.gms:play-services-base:16.0.1"
            force "com.google.android.gms:play-services-stats:16.0.1"
            force "com.google.android.gms:play-services-gcm:16.0.0"
        }
```

**Comment by brunoluigi** [comment] 2019-06-18 20:33
Adding these 2 lines to the project level build.gradle saved my life:

```
buildscript {
    ext {
        ...
        googlePlayServicesVersion = "16.+"
        firebaseVersion = "17.3.4"
    }
```

Thanks @mhkhung.

**Comment by hramos** [comment] 2019-06-18 21:19
Duplicate of #25173

**Closed by hramos** 2019-06-18 21:19 UTC
Labels: Bug, Ran Commands, Resolution: Needs More Information

**Comment by mhkhung** [comment] 2019-06-18 22:09
I am sure 100s of teams world-wide are burning out last 2 days from this Google problem. #25173 has the right directions but not the full solution. Essentially you will need to keep doing 
```./gradlew cleanBuildCache && ./gradlew clean && ./gradlew app:dependencies``` 
until you get rid of all the androidx in the dependencies output.

Good luck!

**Comment by sekhuat** [comment] 2019-06-19 02:17
> I found a solution for my case. This was due to update [Google Play Services and Firebase](https://developers.google.com/android/guides/releases#june_17_2019) I changed versions to previous and it works:
> `googlePlayServicesVersion = "16.1.0"`
> `firebaseVersion = "17.6.0"`

This solved my issue :)

**Comment by cryptodude2000** [comment] 2019-06-19 04:36
> I found a solution for my case. This was due to update [Google Play Services and Firebase](https://developers.google.com/android/guides/releases#june_17_2019) I changed versions to previous and it works:
> `googlePlayServicesVersion = "16.1.0"`
> `firebaseVersion = "17.6.0"`

I had to add it to the before-plugins.grade

dependencies {    

    project.ext {
        googlePlayServicesVersion = "16.1.0"    
        firebaseVersion = "17.6.0"
    }
    configurations.all {
        
        compile 'com.google.firebase:firebase-crash:9.4.0'        
        .
.
.
.
.

**Comment by letronghieu4897** [comment] 2019-06-19 09:00
> I found a solution for my case. This was due to update [Google Play Services and Firebase](https://developers.google.com/android/guides/releases#june_17_2019) I changed versions to previous and it works:
> `googlePlayServicesVersion = "16.1.0"`
> `firebaseVersion = "17.6.0"`

Thanks. You save my life  👍 . 
========= ========= ========= ========= ========= 
Put it into build.gradle
========= ========= ========= ========= ========= 
buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
        **googlePlayServicesVersion = "16.+"
        firebaseVersion = "17.6.0"**
    }
}
========= ========= ========= ========= =========

**Comment by horaciomoreno10** [comment] 2019-06-19 15:33
thanks a lot guys, you are the best!

**Comment by JosephMulder** [comment] 2019-06-20 14:03
I was using the node module react-native-device-info, just had to change my dependency in build.gradle

    implementation(project(":react-native-device-info"),  {
      exclude group: "com.google.android.gms"
    })

**Comment by turpana** [comment] 2019-06-23 17:06
Anybody get this working with `react-native-google-analytics-bridge`?

**Comment by devshankerdhand** [comment] 2019-06-25 10:10
> Adding these 2 lines to the project level build.gradle saved my life:
> 
> ```
> buildscript {
>     ext {
>         ...
>         googlePlayServicesVersion = "16.+"
>         firebaseVersion = "17.3.4"
>     }
> ```
> 
> Thanks @mhkhung.
> 
> I didn't figured out the big picture here but my guess is that some plugin in my project has an infamous "+" Firebase version as dependency that screwed up everything...

Absolute Working :)

**Comment by lennycodes** [comment] 2019-07-23 08:54
Thank's @rhamretskyi! You just saved my life! It works like a charm :D
