### ISSUE TITLE
Print: Entry, ":CFBundleIdentifier", Does Not Exist 

### ISSUE THREAD

**Issue by ray0324** [facebook/react-native#14452] opened 2017-06-11 06:36 UTC
node --version
v8.0.0
npm --version
5.0.3
react-native --version
react-native-cli: 2.0.1
react-native: 0.45.1

xcodebuild -version
Xcode 8.3.3
Build version 8E3004b
yarn --version
0.24.6
---------------------------------------
The steps i create my project:
react-native init Tst
...
cd Tst
react-native run-ios

the simulator boots normally,but build failed with errors

--------------------------------------------------------------------------------
** BUILD FAILED **

The following build commands failed:

	PhaseScriptExecution Install\ Third\ Party /Users/ray/Work/React/native/Tst/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/double-conversion.build/Script-190EE32F1E6A43DE00A8543A.sh
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/Tst.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/Tst.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by mikenk2010** [comment] 2017-06-11 10:29
Hmmm, it still works from my site. There is my package.json. I think you should clean or reinstall again.

```
node -v
v6.10.1

npm -v
4.2.0

react-native -v
react-native-cli: 2.0.1
react-native: 0.45.1

Launching iPhone 6 (iOS 10.3)
```

```
{
	"name": "testlatest_version",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	},
	"dependencies": {
		"react": "16.0.0-alpha.12",
		"react-native": "0.45.1"
	},
	"devDependencies": {
		"babel-jest": "20.0.3",
		"babel-preset-react-native": "1.9.2",
		"jest": "20.0.4",
		"react-test-renderer": "16.0.0-alpha.12"
	},
	"jest": {
		"preset": "react-native"
	}
}
```

**Comment by hramos** [comment] 2017-06-12 20:55
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-12 20:55 UTC

**Comment by GregYeo** [comment] 2017-06-13 10:26
I have exactly same problem.
```
node --version
v8.0.0
npm --version
5.0.3
react-native --version
react-native-cli: 2.0.1
react-native: 0.45.1
```

I tried re-install xcode(because i already used to use latest) and put leak of library(boost/config/user.hpp)  but it did not worked and xcode could build ios except for react-native.

Node version wasn't matter of me. I tested it both of below
```
v6.11.0
v8.1.0
```



I finally found solution which downs version of react native
https://github.com/facebook/react-native/issues/14368
```
 react-native@0.44.0
 react@16.0.0.alpha.6
```

This is my current JSON
```json
{
	"name": "YOUR_PROJECT",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	},
	"dependencies": {
		"react": "^16.0.0-alpha.12",
		"react-native": "^0.44.0"
	},
	"devDependencies": {
		"babel-jest": "20.0.3",
		"babel-preset-react-native": "1.9.2",
		"eslint": "^4.0.0",
		"eslint-config-standard": "^10.2.1",
		"eslint-plugin-import": "^2.3.0",
		"eslint-plugin-node": "^5.0.0",
		"eslint-plugin-promise": "^3.5.0",
		"eslint-plugin-react-native": "^2.3.2",
		"eslint-plugin-standard": "^3.0.1",
		"react-test-renderer": "16.0.0-alpha.13"
	},
	"jest": {
		"preset": "react-native"
	}
}

```


It seems like v0.45.x has dependency problem of ios because android is working well.

If someone trying to keep up with latest version of react-native and meeting ios building problem, Just stay at v0.44.x for a while.

**Comment by hramos** [comment] 2017-08-04 06:51
Duplicate of #14423
