### ISSUE TITLE
React Native Changes Not Loading

### ISSUE THREAD

**Issue by AdeptLearner123** [facebook/react-native#15095] opened 2017-07-19 02:57 UTC
Hi all,

I am using React-Native 0.46.4 on Mac OS for Android development. I have made changes to the index.android.js but the changes are not being reflected when I load it on the device. The packager is running on port 8080 since port 8081 is taken. I have looked at the other issues such as uninstalling watchman and restarting the packager, but none seem to be working.

### Environment

McAfee Virus Protection on port 8081
All steps followed in Getting Started on React Native website for Mac OS Android.
Watchman 4.7.0
npm 5.0.3
React Native 0.46.4
Packager running on port 8080

- Target Platform: Android 6

- Development Operating System:  Mac OS Sierra

**Comment by hramos** [comment] 2017-07-19 19:40
Is the device connected to the packager? You'll also need to update the app to connect to port 8080, since it will by default look for the packager in port 8081.

**Comment by zibs** [comment] 2017-07-21 16:14
@AdeptLearner123  Not sure if these docs are still relevant but take a look here: https://github.com/facebook/react-native/blob/master/docs/Troubleshooting.md

Issue is further discussed: https://github.com/facebook/react-native/issues/10715 and https://github.com/facebook/react-native/issues/9145

**Comment by hramos** [comment] 2017-07-21 18:04
Duplicate of #9145

**Closed by hramos** 2017-07-21 18:04 UTC
