### ISSUE TITLE
FlatList scrollToIndex() dont work without specifying the getItemLayout prop

### ISSUE THREAD

**Issue by MichaelPintos** [facebook/react-native#15138] opened 2017-07-21 13:51 UTC
#React native version 0.46.4

![quickmemo _2017-07-20-15-17-23](https://user-images.githubusercontent.com/26886974/28466139-b84df272-6e01-11e7-9d2e-69af62db3597.png)

`
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  FlatList,
  View
} from 'react-native';

export default class FlatListError extends Component {
  constructor(props){
    super(props);
    this.state = {
      data: [],
    }
  }
  componentDidMount(){
    let dataL = [];
    for (var i = 0; i < 100; i++) {
      let obj = { key: `Element ${i}`, content: 'Nullam ac dictum elit. Morbi sollicitudin dignissim dolor at egestas. Fusce dignissim metus in augue blandit suscipit. Nam dapibus nulla' };
      dataL.push(obj);
    }
    this.setState({data: dataL});
  }
  _scrollToIndex = () => {
    /*
      HOW FIX THIS BUG
        set initialNumToRender = data.length
        and max scrollToIndex initialNumToRender -2
        
    */
    
    console.warn(this.state.data.length); //100
    let index = 100;
    if(index > this.state.data.length -2){
      this.flatlist.scrollToEnd({animated: true});
    }else{
      this.flatlist.scrollToIndex({animated:true , index: this.state.data.length -2, viewPosition: 0}) // Go to element 98 
    }
    
  }
  _renderList = ({item}) => (
    <View style={{backgroundColor:'blue', margin:10,}}>
      <Text style={{color: 'white'}}>{item.key}</Text>
      <Text style={{fontSize: 30,}}>{item.content}</Text>
    </View>
  );
  render() {
    return (
      <View style={styles.container}>
        <Text>
          Welcome to React Native!
        </Text>
        <View style={styles.flatContainer}>
          <FlatList
            ref={(ref) => this.flatlist = ref}
            onLayout={() => this._scrollToIndex()}
            initialNumToRender={this.state.data.length}
            data={this.state.data}
            renderItem={this._renderList}
          />
        </View>
        
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  flatContainer:{
    flex:1,
    width:'100%',
    alignItems:'center',
  }
});

AppRegistry.registerComponent('FlatListError', () => FlatListError);

`
@hramos Gracias por la pronta respuesta

HOW FIX THIS BUG
set initialNumToRender = data.length
and max scrollToIndex initialNumToRender -2 || max scrollToIndex  data length -2

**Comment by hramos** [comment] 2017-07-21 15:39
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-07-21 15:39 UTC

**Comment by HaswinVidanage** [comment] 2018-03-18 06:53
@hramos can't you label the bug as need more information or something rather than closing an open bug ?
