### ISSUE TITLE
AlertIOS.prompt scroll the view

### ISSUE THREAD

**Issue by luco** [facebook/react-native#15744] opened 2017-09-01 15:00 UTC
My issue is when I prompt user with AlertIOS, the scroll behind gets scrolled to the top.
I'm using the sample code provided:

```
AlertIOS.prompt(
		  'Enter password',
		  'Enter your password to claim your $1.5B in lottery winnings',
		  [
		    {text: 'Cancel', onPress: () => console.log('Cancel Pressed'), style: 'cancel'},
		    {text: 'OK', onPress: password => console.log('OK Pressed, password: ' + password)},
		  ],
		  'secure-text'
		);
```

The expected behavior is to not scroll, as you can see on many apps, such as AppStore.

**Comment by hramos** [comment] 2017-09-01 16:33
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue that meets the requirements set forth in the template. Thanks!

**Closed by hramos** 2017-09-01 16:33 UTC
