### ISSUE TITLE
Touchable with Fragment as child prevents the onPress event

### ISSUE THREAD

**Issue by mloureiro** [facebook/react-native#22812] opened 2018-12-27 11:12 UTC
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment

[skip envinfo]
This is reproducible in [expo playground](https://snack.expo.io/SyBgJ4zZE).

## Description

Since [TouchableWithoutFeedback](https://facebook.github.io/react-native/docs/touchablewithoutfeedback.html) doesn't allow multiple children (maybe this is a bug also) using a [Fragment](https://reactjs.org/docs/fragments.html) will "remove" the touchable area, if Fragment is replaced with View then it works.

## Reproducible Demo

Expo: https://snack.expo.io/SyBgJ4zZE

**Comment by bartolkaruza** [comment] 2018-12-29 09:39
`Touchable`'s rely on a single child node on which explicit listeners are set. The reason it does not render a `View` or similar internally is that you might want to control which specific `View` the touch listeners are set to. A Fragment is *not* a node, but a way to group multiple items. Its only use case is grouping multiple nodes in JSX and there is no reason for a `Fragment` with a single child.

Since multiple children are not allowed inside a `Touchable` and the single child `Fragment` case does not make sense, this is not really a real world issue.

@kelset close

**Comment by mloureiro** [comment] 2018-12-29 10:35
I'm wondering if this should throw an exception instead of silently fail.

My point here is, if we do:

```html
<Touchable>
  <Text>a</Text>
  <Text>b</Text>
</Touchable>
```

We get an error on the build (mentioning that it doesn't allow multiple children), this way it is clear that it doesn't work. I would rather have the same behavior with `Fragment`, we would have the info right away.

What do you think?

**Comment by bartolkaruza** [comment] 2018-12-29 11:15
I think we should leave that up to https://reactjs.org/docs/react-api.html#reactchildrenonly

Maybe @gaearon can pitch in on whether `React.Children.only` should accept a `Fragment` at all?

**Comment by kelset** [comment] 2019-01-04 16:16
(closing since this is not a bug per se, but feel free to continue the conversation 🤗)

**Closed by kelset** 2019-01-04 16:16 UTC
