### ISSUE TITLE
TextInput with secureTextEntry loses value

### ISSUE THREAD

**Issue by stenrap** [facebook/react-native#9148] opened 2016-08-01 20:44 UTC
I'm developing an app with React Native 0.29.1 and React 15.2.1 in Mac OS X El Capitan 10.11.5. I've noticed that a TextInput with `secureTextEntry` set to true will lose its value if you:
1. Type some characters into the input.
2. Blur the input (give focus to something else).
3. Focus the input.
4. Type another character.

I've reproduced the issue here:

https://rnplay.org/apps/Xpn4uw

**Comment by vonovak** [comment] 2016-08-02 07:25
what you probably want to do is store the values in your state object, i.e. call setState on changing input text and set the TextInput's `value` prop.

**Comment by stenrap** [comment] 2016-08-02 07:53
I actually tried that, but it doesn't fix the problem (should have mentioned it in my original post).

**Comment by vonovak** [comment] 2016-08-02 08:22
hmm, quite interesting indeed. Looking at it closer, I found out that is actually the intended behavior on ios. Try launching the RN play demo, and go to settings -> icloud and try your procedure

**Comment by alexHlebnikov** [comment] 2016-08-03 10:28
I've got the same problem after updating from 0.27.0 to 0.29.0.30.0.
Saving query in state doesn't works. Feels like a TextInput component bug.

**Comment by RD1991** [comment] 2016-08-13 09:39
This is default behaviour. This works same in iOS native development.

**Comment by gabriel** [comment] 2016-10-11 18:49
It would be nice to support not clearing the password on iOS. There are some workarounds here:
https://stackoverflow.com/questions/7305538/uitextfield-with-secure-entry-always-getting-cleared-before-editing
https://stackoverflow.com/questions/28441300/uitextfield-secureentry-doesnt-respect-clearsonbeginediting-property

**Comment by lacker** [comment] 2017-02-09 22:28
I'm going to close this issue as "works as intended". In general if something works a particular way in iOS native development it seems reasonable to consider it out of scope for RN to fix it.

**Closed by lacker** 2017-02-09 22:28 UTC
