### ISSUE TITLE
Attempted to invoke `3` (method ID) on `UIManager` (NativeModule name) with an invalid bridge.

### ISSUE THREAD

**Issue by nihp** [facebook/react-native#24148] opened 2019-03-26 09:01 UTC
**🐛 Bug Report**

 I am facing lot of warnings which not allowing me to make any event in the app. 
Attempted to invoke `3` (method ID) on `UIManager` (NativeModule name) with an invalid bridge. Refer the attached image

 **To Reproduce**

  I am facing this issue in latest version of  "react-navigation": "^3.2.3" (v3)

 **Expected Behavior**

Need to remove all the warnings (Attempted to invoke `3` (method ID) on `UIManager` (NativeModule name) with an invalid bridge.)

**Environment**

 **npmPackages:**
      react: 16.8.1 => 16.8.1 
      react-native: ^0.58.4 => 0.58.6 
    **npmGlobalPackages:**
      react-native-cli: 2.0.1

![Screenshot 2019-03-26 at 2 23 42 PM](https://user-images.githubusercontent.com/36992338/54983969-da429080-4fd3-11e9-9f67-3b9806ef2a68.png)

**Comment by nihp** [comment] 2019-03-26 09:13
I have added the environment details for react-native.

**Comment by kelset** [comment] 2019-03-26 11:30
👋

This issue seems to be related to how you use react-navigation, so I'd recommend you open an issue there - also, it would help incredibly if you could add a repro to your code.

That said, this seems to be also only warnings, that suggest this being related to your code, and you are on an old RN version.

Because of all these reasons, I'll close this. Please LMK if this happens on a clean react-native project (without react-navigation) by submitting a repro - in that case we can reopen this and investigate further.

**Closed by kelset** 2019-03-26 11:30 UTC
Labels: Resolution: Missing Environment Info, Type: Bug Report

**Comment by rjruizes** [comment] 2019-04-03 00:55
I found this issue while trying to debug an error message `Unable to find module for UIManager`. Randomly, I also got the multiple warning screen that @nihp posted, e.g. `Attempted to invoke `6` (method ID) on `UIManager` (NativeModule name) with an invalid bridge.  I'm using RN 0.59.3. I'll try to undo some commits to see if I can get rid of it.

**Comment by RoderickJDunn** [comment] 2019-04-20 21:33
I'm just upgraded to RN 0.59.5 and see "Unable to find module for UIManager" every time I reload the bundle. This was definitely not present in RN 0.57.7. FWIW the error is logged and then the code is reloaded anyway without any apparent issues other than this error log.

I will update if I find the cause.

**Comment by SwordElucidator** [comment] 2019-10-24 13:54
@RoderickJDunn 
Hey, did you find the cause?

**Comment by RoderickJDunn** [comment] 2019-10-24 14:02
@SwordElucidator I never found out what was causing this specifically, but after I updated to RN 0.61 the error/warnings are gone.
