### ISSUE TITLE
`ProxyComponent` has no propType for native prop `RCTMap.followUserLocation` of native type `BOOL`

### ISSUE THREAD

**Issue by JakeRawr** [facebook/react-native#6613] opened 2016-03-23 20:59 UTC
I recently upgraded RN from v0.19 to v0.22. 

When I run the simulator, this error popped up.

<img width="319" alt="screen shot 2016-03-23 at 1 37 52 pm" src="https://cloud.githubusercontent.com/assets/7199499/14000485/aa4b6c44-f0fe-11e5-8396-e238727a03e3.png">

Error log that shows in the xcode:
```
2016-03-23 13:54:20.818 [error][tid:com.facebook.React.JavaScript] `ProxyComponent` has no propType for native prop `RCTMap.followUserLocation` of native type `BOOL`
If you haven't changed this prop yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away.
2016-03-23 13:54:20.819 [fatal][tid:com.facebook.React.RCTExceptionsManagerQueue] Unhandled JS Exception: `ProxyComponent` has no propType for native prop `RCTMap.followUserLocation` of native type `BOOL`
If you haven't changed this prop yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away.
2016-03-23 13:54:20.845 [info][tid:com.facebook.React.JavaScript] Running application "________" with appParams: {"rootTag":1,"initialProps":{}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
2016-03-23 13:54:20.847 [error][tid:com.facebook.React.JavaScript] Application ________ has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent.
2016-03-23 13:54:20.848 [fatal][tid:com.facebook.React.RCTExceptionsManagerQueue] Unhandled JS Exception: Application IOS_99GAMERS has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent.
```
I've removed the node_modules and reinstall v0.22.
Same error occurred. 

I've been looking for a fix to this issue (thought I'm not the only one). But I couldn't find reported bug that's related to this issue. 

I'm currently running on:
React Native v0.22,
xcode ios simulator,
Mac

If you need more detail, i'll reply within minutes. Thanks

**Comment by charpeni** [comment] 2016-03-23 23:57
@facebook-github-bot ios

**Comment by charpeni** [comment] 2016-03-23 23:58
I can take a look at this tomorrow.

**Comment by charpeni** [comment] 2016-03-23 23:58
@facebook-github-bot label ios

**Comment by JakeRawr** [comment] 2016-03-24 00:05
Thank you, 

Update:
I changed the code
from
```
var React = require('react-native');
var {
  ...
  MapView,
  ...
} = React;
```
to
```
import React, {
  ...
  MapView,
  ...
} from 'react-native';
```
seems to make the problem go away. I do not have an explanation tho.

**Comment by BrianJoyce** [comment] 2016-03-24 00:59
Similar issue here. 
<img width="369" alt="screen shot 2016-03-24 at 00 58 20" src="https://cloud.githubusercontent.com/assets/442814/14005482/a63bedc4-f15b-11e5-939c-78de08ccda21.png">

**Comment by charpeni** [comment] 2016-03-24 01:11
@BrianJoyce do you have Hot Reloading enabled ?

**Comment by BrianJoyce** [comment] 2016-03-24 01:36
No I don't.
<img width="369" alt="screen shot 2016-03-24 at 01 35 27" src="https://cloud.githubusercontent.com/assets/442814/14006024/c39069f4-f160-11e5-847c-b72512c8085e.png">

**Comment by nikolasburk** [comment] 2016-03-24 11:18
I have the exact same issue as @BrianJoyce after starting a new project this morning. Could it have to do with the recent Xcode update?

**Comment by BrianJoyce** [comment] 2016-03-24 11:21
@nikolasburk yeah it's possible i guess, or something to do with react 0.22 and lastest xcode. Will check out a few 0.21 projects later to see if it's an issue with 0.21

**Comment by nikolasburk** [comment] 2016-03-24 11:36
I was using `"react-native": "^0.21.0"` in my `package.json`. I now updated to 0.22, deleted all npm modules, reran `npm install` and then restarted the app with `npm start -- -- reset-cache` and this actually solved the issue for me.

**Comment by BrianJoyce** [comment] 2016-03-24 12:45
@nikolasburk thanks!  Did that, then uninstalled and re-installed watchman and it seems to have done the trick.  Thanks again.

**Comment by charpeni** [comment] 2016-03-24 13:22
Since it seems resolved and caused by bad sync between js bundle and the app, I'll close it.

If you think this is a persistent bug, just reflag it.

**Comment by charpeni** [comment] 2016-03-24 13:22
@facebook-github-bot close

**Closed** 2016-03-24 13:24 UTC
Labels: iOS, Ran Commands

**Comment by chrisnojima** [comment] 2016-03-25 19:54
Clearing the cache seems to have no affect for me. Turning off hot reloading does fix it. Using 0.22.2 and xcode Version 7.3 (7D175)

**Comment by gopidon** [comment] 2016-04-16 07:58
npm start -- -- reset-cache worked for me. XCode 7.3, RN - 0.23.1

**Comment by Antsanirina** [comment] 2016-06-02 13:14
same issues here.. any of your solutions is working . :/ (android studio 2.1.1)

**Comment by masterkrang** [comment] 2016-07-21 22:31
This won't be a solution for everybody, but the "constructor has no proptype for native prop X.X" is a common issue when running new projects. Make sure to close out all of your projects, and reset the cache in the simulator, try again. This usually works for me.

**Comment by dcurletti** [comment] 2016-10-01 22:13
I also currently having this issue.

**Comment by my2dieer** [comment] 2017-03-22 06:29
i have met the same issue. but i found the problem was that i had ran another project early. when i reload the terminal ,it works.

**Comment by budiga** [comment] 2017-04-22 11:11
reload the terminal,works for me!thanks! @my2dieer

**Comment by durgarao150** [comment] 2018-05-15 12:59
what is the solution for this issue?
