### ISSUE TITLE
init build failure with ANY new react-native project halp

### ISSUE THREAD

**Issue by RBazelais** [facebook/react-native#11265] opened 2016-12-02 07:05 UTC
```
** BUILD FAILED **


The following build commands failed:

	CompileC /Users/Rachel/TestRN/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTPlatform.o Base/RCTPlatform.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/TestRN.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/TestRN.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```
--- Please use this template, and delete everything above this line before submitting your issue --- 

### Description
My react-native init Build failure with ANY new project. I made a new project called TestRN which seemed to go fine until i tried to build it and get the typical welcome to react native screen.
On: react-native run-ios I got the error above. I uninstalled and reinstalled react native, node, watchman and killed all processes on port 8081.

Please help me fix and understand what is going wrong.

### Reproduction

https://github.com/RBazelais/TestRN.git

### Solution

I have no idea

### Additional Information

* react-native-cli: 1.3.0
* react-native: 0.39.0
* watchman --v 4.7.0
* xCode: 7.2

* Platform: IOS
* Operating System: MacOSX Yosemite 10.10.5

**Comment by eugenehp** [comment] 2016-12-02 23:35
@RBazelais could you try to run it from Xcode directly?

**Comment by muellermichel** [comment] 2016-12-03 13:12
Same xCode, same OS, installed node/npm/react native just today, same error.

**Comment by muellermichel** [comment] 2016-12-03 13:50
Alright, I got it to work. Simply patch it by removing lines 26 and 27 from node_modules/react-native/React/Base/RCTPlatform.m:26. Then try and build again. No idea why that enum value was not defined, according to [Apple](https://developer.apple.com/reference/uikit/uiuserinterfaceidiom/uiuserinterfaceidiomcarplay) it's SDK 9.0 which should be supported on XCode 7.2. I also tried changing the project build target to 9.2, but that didn't help.

**Comment by carlosvillu** [comment] 2016-12-04 18:11
Same error and same solution. :)

**Comment by liuguanyu** [comment] 2016-12-07 10:57
@muellermichel 
I resolved it with the same solution. But the simulator seems be Pad, coz the program goto the default branch. so I modified it:

```
    default:
      //  return @"unknown";
      return @"phone";
```

**Comment by muellermichel** [comment] 2016-12-08 02:38
@liuguanyu 
I don't quite get why that would be needed. If you look at [the source file here](https://github.com/facebook/react-native/blob/master/React/Base/RCTPlatform.m), it looks like the `UIUserInterfaceIdiomPad` case is still defined, my patch only removes `UIUserInterfaceIdiomCarPlay`. Are you sure you removed the correct lines in the correct file?

**Comment by liuguanyu** [comment] 2016-12-08 03:24
@muellermichel 

Yes,  We removed same lines. In XCode 7.2,  the removed lines causes compile  errors.

I guess this may be a  bug of rn.

**Comment by muellermichel** [comment] 2016-12-08 04:49
@liuguanyu 
It seems we have a slightly different setups. What's the compile error you get after the patch?

**Comment by liuguanyu** [comment] 2016-12-08 06:28
@muellermichel

After removed these lines, I can compile the code. 
but, the simulator window is so big. 

so I edit it like following

```
static NSString *interfaceIdiom(UIUserInterfaceIdiom idiom) {
  switch(idiom) {
    case UIUserInterfaceIdiomPhone:
      return @"phone";
    case UIUserInterfaceIdiomPad:
      return @"pad";
    case UIUserInterfaceIdiomTV:
      return @"tv";
//    case UIUserInterfaceIdiomCarPlay:
//      return @"carplay";
    default:
//      return @"unknown";
      return @"phone";
  }
}
```

**Comment by muellermichel** [comment] 2016-12-09 08:28
Curious. So it looks like "idiom" is something other than these three provided ones. I'm thinking it depends on the device selection. What does it show there for you?

react native developers would probably be interested in what integer "idiom" is set to for you - setting a breakpoint in front of the switch and running the project should show you the state of "idiom" in the locals.

<img width="195" alt="screen shot 2016-12-09 at 17 26 22" src="https://cloud.githubusercontent.com/assets/3378634/21042443/9c6ae4b6-be34-11e6-964c-99268e043344.png">

**Comment by jiawang1** [comment] 2016-12-15 01:25
hi
Same issue to me. But after I upgrade to Xcode 8.2., everything is OK

**Comment by zhoulinxiang** [comment] 2016-12-16 09:23
@muellermichel same error in xcode7,https://github.com/facebook/react-native/issues/11508

**Comment by lacker** [comment] 2016-12-16 23:50
Is anyone seeing this problem on Xcode 8.2 or does this problem only exist with older Xcodes?

**Comment by zhoulinxiang** [comment] 2016-12-17 07:46
@lacker Xcode 8.2 is fine,just in older Xcodes

**Comment by lacker** [comment] 2016-12-19 18:43
OK so maybe the solution here is to make it clear that React Native requires a modern release of Xcode? (For some definition of modern)

**Comment by zhoulinxiang** [comment] 2016-12-20 02:20
@lacker  yeah

**Comment by kylebebak** [comment] 2016-12-20 22:40
@lacker @zhoulinxiang 

Thanks a lot guys, I suspected this was the case but didn't want to upgrade. I just installed Xcode 8.2 and the problem vanished

**Comment by lacker** [comment] 2016-12-20 22:47
OK since it's pretty clear what the solution is I am going to close this issue.

**Closed by lacker** 2016-12-20 22:47 UTC

**Comment by muellermichel** [comment] 2016-12-21 02:45
@lacker IMO it's still at least an open documentation issue - AFAIK react native doesn't yet document a minimum supported XCode version.

**Comment by lacker** [comment] 2016-12-21 19:35
Yeah, I am somewhat worried about that because I don't know how to keep it up to date. I suspect that Xcode versions older than Facebook uses will kind of randomly break at some point so the best advice is just to use a new one when you get weird Xcodey problems. But it doesn't seem useful to just tell people "use a real new Xcode".

**Comment by muellermichel** [comment] 2016-12-22 00:58
How about just documenting whatever XCode version is being used internally at Facebook and say something "your experience may vary with other versions"? Then at least people don't have to wander in the dark and can keep their setup in sync with what's used internally.

**Comment by lacker** [comment] 2016-12-22 01:26
The thing is that gets updated all the time and I don't have a great automated way to hook things into the RN docs about it.

**Comment by vincentaudebert** [comment] 2017-03-05 23:31
I agree with mentioning what XCode version should be used with each version of react-native. Couldn't find the information anywhere while facing the bug on this issue. Updating my macOS + Xcode now...

**Comment by vampire2610** [comment] 2017-06-11 15:45
same problem when i use space in folder name

**Comment by cjam** [comment] 2017-06-30 02:05
Not sure if anyone is still having this problem, just ran into as I was trying to clean up my ios xcodeworkspace.  After quite a bit of debugging, trial and error I ended up changing my workspace derrived data settings to be:  

![screen shot 2017-06-29 at 6 44 01 pm](https://user-images.githubusercontent.com/1000288/27717583-0f94314e-5cfb-11e7-81c1-3535f16dde7a.png)

And in the *Advanced...*

![screen shot 2017-06-29 at 6 43 50 pm](https://user-images.githubusercontent.com/1000288/27717623-43a4e6c2-5cfb-11e7-920d-49cf8f0929f7.png)


which seems to have fixed things.  I think where I went wrong was that I had changed the XCode application preference for the derrived data folders and it was messing things up.  I still can't seem to build from xcode, however fixed my react-native cli build.

**Comment by DarjiDhanrajD** [comment] 2017-07-25 12:10
I have created one demo app in react native but facing issue  `** BUILD FAILED **


The following build commands failed:
	CompileC /Users/sevenstarinfotech/sample/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/third-party.build/Objects-normal/x86_64/Conv.o /Users/sevenstarinfotech/sample/node_modules/react-native/third-party/folly-2016.09.26.00/folly/Conv.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/sample.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/sample.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist`


i have tried all solution which is available on github as well as staroverflow

**Comment by hramos** [comment] 2017-08-04 06:55
Duplicate of #14423

**Comment by 18871401911** [comment] 2018-04-09 09:34
Has your problem been solved?
