### ISSUE TITLE
[Border] overflow: 'hidden' not taking borderRadius into account?

### ISSUE THREAD

**Issue by dhrrgn** [facebook/react-native#1235] opened 2015-05-11 14:34 UTC
Somewhere between 0.4.1 and 0.4.2 using `overflow: 'hidden'` in conjunction with `borderRadius` stopped clipping the contents of the View with the `borderRadius` specified.

Here is a component which demonstrates the issue: https://gist.github.com/dhrrgn/1fbc0c3aa0b6d3abdc39

Here is what it looks like:

![](http://f.cl.ly/items/0P2u21343z2d470v192z/Image%202015-05-11%20at%2010.33.03%20AM.png)

In 0.4.1, the inner Views were clipped.

**Comment by brentvatne** [comment] 2015-05-11 20:49
Thanks @dhrrgn, this does seem to be a regression.

I took your gist above and turned it into a runnable example here:
http://rnplay.org/plays/UrrwRg

cc @vjeux

**Comment by nicklockwood** [comment] 2015-05-12 01:05
It's because of the new border implementation. Previously we were relying on iOS's border rendering, which doesn't support variable width/color borders. We're now using a custom implementation which more closely mimics CSS behavior, however that includes the CSS behavior of clipping to the rectangular bounds instead of the curved corner.

We've not fully decided how to deal with this yet, as there's a very high performance cost to implementing non-rectangular clipping. For now I suggest applying a separate corner radius to your inner views instead of relying on the parent view to clip them.

**Comment by dhrrgn** [comment] 2015-05-12 01:31
@nicklockwood That is not possible if you look at the example code above.  Unless something has changed, you cannot do things like `border-top-left-radius`.

**Comment by nicklockwood** [comment] 2015-05-12 01:40
@dhrrgn ah, sorry. That *has* changed, but it hasn't shipped yet. Hopefully that will be available later this week.

I'm not actually sure why this broke between 0.4.1 and 0.4.2 then. As far as I know the border implementation didn't change between those two releases - the only recent change I know of is the one that hasn't shipped yet.

This may be an accidental regression after all.

**Comment by dhrrgn** [comment] 2015-05-12 01:47
@nicklockwood Ok, thanks. That will solve our issue then.  As for how/why that broke, I assume it is in this commit, but there is a lot going on, so I cannot be sure (unless this is what you are talking about): https://github.com/facebook/react-native/commit/826b56a41be62ab8a558a2a31b161ecc7577e1fe

**Comment by nicklockwood** [comment] 2015-05-15 02:06
@dhrrgn the support for variable border radii that I mentioned has now landed in 0.4.3. Let me know if that solves your issue.

Seperately, it looks like the fact that clipping no longer works may actually be a bug, but if so the fix won't be coming for at least a few days, so if you can work around it using corner radii, that's probably a faster solution.

**Comment by jessepollak** [comment] 2015-05-22 19:05
Just a +1 that borderRadius stopped working as expected somewhere between 0.4.1 and 0.4.4 with the overflow property. Anything I can do to help debug?

**Comment by brentvatne** [comment] 2015-05-28 04:33
Looks like this fix should land soon, see here: https://github.com/tadeuzagallo/react-native/commit/81401064e5bc0e50de5d77ec9e2384a70e43e2f4

**Comment by nicklockwood** [comment] 2015-05-28 09:02
Yeah, @a2's fix for this is in the latest release. There's still an outstanding bug where borders are drawn behind the content when overflow = hidden, but I'm working on that now.

**Comment by nicklockwood** [comment] 2015-05-29 21:48
You may wish to keep this open due to the bug I mentioned (clipping to the outside of border rather than inside).

**Comment by aleclarson** [comment] 2015-08-03 05:42
I have the 81401064e5bc0e50de5d77ec9e2384a70e43e2f4 commit and the ff49d86aedc3afbed5c109d60d2b6c02230cb5d4 commit, but the border is being clipped instead of being rounded properly.

I also created #2210 for this reason.

Any ideas?

**Comment by brentvatne** [comment] 2016-01-02 02:17
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/border-overflow-hidden-not-taking-borderradius-into-account

**Closed by brentvatne** 2016-01-02 02:17 UTC
Labels: Icebox
