### ISSUE TITLE
React Native site down!

### ISSUE THREAD

**Issue by cwahlfeldt** [facebook/react-native#11069] opened 2016-11-22 15:28 UTC
The React native site is down :)

https://facebook.github.io/react-native/

![screen shot 2016-11-22 at 9 19 51 am](https://cloud.githubusercontent.com/assets/4119720/20529425/b1b20414-b095-11e6-98df-01f459615a72.png)

**Comment by ayberkanilatsiz** [comment] 2016-11-22 15:30
👍 We should find Doc!

**Comment by laynemoseley** [comment] 2016-11-22 15:31
Yep, just noticed this as well.

**Comment by hramos** [comment] 2016-11-22 15:32
We're looking into it.

**Comment by mkonicek** [comment] 2016-11-22 15:58
Seems to be back now. Will close this as it's not a bug in RN but thanks for noticing it! 👍 

http://facebook.github.io/react-native/docs/getting-started.html

**Comment by mkonicek** [comment] 2016-11-22 15:58
![screenshot 2016-11-22 15 39 57](https://cloud.githubusercontent.com/assets/346214/20530807/7d9f1978-b0cc-11e6-9f06-85f8f6343e82.png)

**Comment by mkonicek** [comment] 2016-11-22 15:58
Screenshot taken just now:

![screenshot 2016-11-22 15 58 32](https://cloud.githubusercontent.com/assets/346214/20530822/8b61dc80-b0cc-11e6-87f3-47dd8b22ab17.png)

**Closed by mkonicek** 2016-11-22 15:58 UTC
