### ISSUE TITLE
MaxLength doesn't work with AutoCompletion and MarkedRange

### ISSUE THREAD

**Issue by hubertwang** [facebook/react-native#9082] opened 2016-07-29 06:46 UTC
Current implementation of maxLength has two issues of AutoCompletion and MarkedRange.

**AutoCompletion**
The maxLength check is not working on AutoCompletion. The reason is that textField:shouldChangeCharactersInRange:replacementString: will not be called when we type by the word suggested by system. So we need to check in UIControlEventEditingChanged.
![auto-completion-breaks-max-length](https://cloud.githubusercontent.com/assets/1281311/17239949/a39fbeb2-559a-11e6-8d1c-582aca2cf53e.gif)

**MarkedRange**
In some language, such as Chinese and Japanese, a word may composed by multiple key strokes. If the maxLength check does not exclude strings that are marked, then we will not be able to complete the input.
![marked-text-should-not-be-limited-by-max-length](https://cloud.githubusercontent.com/assets/1281311/17239957/b46fdaf6-559a-11e6-83f6-5e7ca756d681.gif)

https://github.com/facebook/react-native/pull/8705

**Comment by lacker** [comment] 2016-10-28 20:13
Since you have reproduced all this information in the pull request at https://github.com/facebook/react-native/pull/8705 I think we can close this issue. Thank you very much for submitting a pull request with the bug report, by the way!

**Closed by lacker** 2016-10-28 20:13 UTC
