### ISSUE TITLE
Animated.event with useNativeDriver disregards interpolations/etc when re-rendering

### ISSUE THREAD

**Issue by scarlac** [facebook/react-native#12543] opened 2017-02-23 13:48 UTC
The initial interpolated animation value of an `Animated.event` with `useNativeDriver` is calculated correctly, but once it gets re-rendered then the interpolation is ignored. But when it re-renders again, then the interpolated value is again correct. So:
1st render: Correct value
2nd render: Incorrect (0)
3rd render: Correct.
4th...*: Correct.

This also applies to `Animated.add` nodes as well. 
I simulate re-rendering with a timer that calls `this.forceUpdate()`. 
[Here is a boiled-down code sample.](https://rnplay.org/apps/cyeXqg)
[Here is a video of the code sample running (RNPlay won't work for this)](https://dl.dropboxusercontent.com/u/4361479/animated-event-resets.mov)

I don't know how to work around this. Using `setValue` in `componentWillMount` doesn't make a difference.

### Additional Information

* React Native version: 0.41.2
* Platform: iOS
* Operating System: macOS 10.12.3

**Comment by willdawsonme** [comment] 2017-03-27 04:56
Also running into this on React Native 0.43.0-rc.4. The animated value or interpolation is treated as though it's undefined on the second render. If the animated value is only added to the Animated Component on the second render, it seems fine.

**Comment by janicduplessis** [comment] 2017-03-27 06:46
@scarlac @willdawsonme Could you try master see if the issue is still there? I think https://github.com/facebook/react-native/commit/9c3e6ae9f0f246e5fd8cdc3599801c37d1c11690 might have fixed it.

**Comment by willdawsonme** [comment] 2017-03-28 00:41
Unfortunately that doesn't seem to help! My `Animated.ScrollView` that controls the native event isn't actually being re-rendered, just a sibling component that relies on the native value. It doesn't seem to happen on every reload either, but somewhat intermittently.

**Comment by janicduplessis** [comment] 2017-03-28 00:45
Thanks for trying that out, I'll see if I can figure out the cause with @scarlac repro.

**Comment by f0rr0** [comment] 2017-03-31 15:10
@janicduplessis running into the same issue on the latest master

**Comment by f0rr0** [comment] 2017-03-31 15:22
@janicduplessis further more i think the incorrect value is always the upper limit of the output range.

**Comment by f0rr0** [comment] 2017-03-31 15:34
@janicduplessis also this issue is iOS specific finely, works fine on android

**Comment by janicduplessis** [comment] 2017-03-31 20:11
Just tested on master and I it works properly with @scarlac's repro. Might be fixed by c9fae2fb935c7b7b619b246f42b3fb9d3c14c9ac which landed 3 days ago. If someone is still running into a similar issue could you please provide a new repro so I can try it out?

**Comment by willdawsonme** [comment] 2017-04-03 03:45
No luck here, but here's a repro! https://snack.expo.io/SyQd4Bkal It doesn't actually need interpolated values, just an Animated.Value.

In the repro, the ScrollView starts at an arbitrary x offset. After 3 seconds, the Header is re-rendered with a state update, which causes it to ignore the animated translateX value on the header until you re-scroll the main view.

Let me know if you need any more info! Thanks

**Comment by aferrerallu** [comment] 2017-06-08 21:06
I had this problem with RN 0.33, 0.34 and now with 0.35. Any solution at the moment?

Thanks!

**Comment by hramos** [comment] 2017-08-16 03:12
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Closed by hramos** 2017-08-16 03:12 UTC
Labels: Icebox
