### ISSUE TITLE
React-native link seem to be broken

### ISSUE THREAD

**Issue by hustlercoder** [facebook/react-native#25399] opened 2019-06-26 06:50 UTC
Hi,
Everything works fine for me, but for those libraries that need to be linked to the project ,
when I execute the command react-native link the process runs in a sort of loop. If I try to execute the application of course everything seems to be linked correctly but the linking process always remains in the loop  until I force it to close manually. Its difficult to prove it with a snack so i put only this for now.Maybe it can be a bug only for me idk....

**Comment by HarshitMadhav** [comment] 2019-06-29 04:24
@hustlercoder did you try this https://stackoverflow.com/questions/54998640/getting-error-while-doing-react-native-link

**Comment by hustlercoder** [comment] 2019-07-01 06:44
@HarshitMadhav  but ii don't get any error. The command is executed but remains in a continuous loop trying to resolve the dependencies. If I open another terminal at the same time and execute react-native run-android everything works, even the new libraries I just installed and I'm trying to link, but the linking process always remains in loop until I give the command ctrl c.

**Comment by kelset** [comment] 2019-07-01 08:06
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Also, since this is caused by the CLI, I'd suggest that once you have a way to repro this you submit an issue to the dedicated repo: https://github.com/react-native-community/cli

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗

**Closed by kelset** 2019-07-01 08:06 UTC
Labels: Bug, Ran Commands, Resolution: Needs More Information, 💻CLI

**Comment by HarshitMadhav** [comment] 2019-07-03 07:22
@hustlercoder  can you post a video link of what's happening?
