### ISSUE TITLE
react-native init fails with syntax error

### ISSUE THREAD

**Issue by vitaminwater** [facebook/react-native#5806] opened 2016-02-08 00:28 UTC
node: v5.5.0
npm: 3.3.12
react-native-cli: 0.1.10

```
/Users/stant/Documents/trackrecord/trackrecord/node_modules/react-native/local-cli/bundle/buildBundle.js:17
function buildBundle(args, config, output = outputBundle) {
                                          ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at loader (/Users/stant/Documents/trackrecord/trackrecord/node_modules/babel-register/lib/node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/stant/Documents/trackrecord/trackrecord/node_modules/babel-register/lib/node.js:140:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (bundle.js:11:21)
    at Module._compile (module.js:413:34)
```

**Comment by dannolan** [comment] 2016-02-08 00:30
Hahahah I was just about to lodge this issue. It's to do with babel version 6.5 which dropped TODAY it seems. RN's packages.json file tracks whatever the latest babel is and this appears to have broken it?

**Comment by jeffchienzabinet** [comment] 2016-02-08 01:04
I was pulling my hair out thinking that I did something wrong until I checked it on a different machine. This affects all `react-native` commands, not just init

**Comment by dannolan** [comment] 2016-02-08 01:11
Yes, it's the version of babel which released yesterday which is 6.5.0 is being tracked it seems, if you jump back to babel-core of 6.4.5 in your project then you should see the restoration of react commands. This however means react-native-cli is b0rked currently.

**Comment by thessem** [comment] 2016-02-08 01:13
+1

@dannolan is correct, downgrading babel-core fixes react-native commands, but `react-native init` doesn't work since it pulls in babel-core 6.5.0 then crashes before the iOS project is created, which I cannot create by command line after downgrading (android is possible with `react-native android`)

**Comment by ramaboo** [comment] 2016-02-08 01:35
Having the same issue :(

**Comment by kittens** [comment] 2016-02-08 01:39
Looking into it.

**Comment by thessem** [comment] 2016-02-08 01:41
A workaround for the initial init is to `react-native init AwesomeProject` as normal. When it fails `cd` into the project directory, run `npm install babel-core@6.4.5` to downgrade babel, then `react-native upgrade ` to finish the project init. Downgrading babel should fix all other problems related to this issue too

**Comment by kittens** [comment] 2016-02-08 01:44
`react-native` specifies `~6.4.5` **but** RN also uses `babel-register` which while it's also specified with the range `~6.4.3`, it has the dependency of `^6.whatever` so it's getting the very latest version. The use of tilde dependencies means that `react-native` is going to pull in more than one copy of `babel-core`.

**Comment by bartek** [comment] 2016-02-08 01:54
Ah, this is it! I was about to log this same issue, hah.

I just spent an hour trying to get the dreaded Red Box removed from my React-Native bundle, and many of the solutions were to just restart to clear the cache. I did that, re-installed npm modules, and now have this. It makes sense that it shows up, since the babel cache was cleared.

Downgrading by running `npm install babel@6.4.5`, I was able to compile the application now, but I am still stuck with the dreaded red box (another issue :) )

**Comment by kittens** [comment] 2016-02-08 02:08
Found the cause. Pushing a hot fix.

**Comment by ffxsam** [comment] 2016-02-08 02:16
+1 to @thessem for the workaround.

**Comment by ffxsam** [comment] 2016-02-08 02:19
Oops, spoke too soon. `react-native upgrade` does not properly finish the project scaffold. `index.ios.js` and `index.android.js` are missing (and maybe other files?)

**Comment by kittens** [comment] 2016-02-08 02:20
Pushed `babel` 6.5.1 which should fix this, can someone please confirm? Regression introduced via babel/babel@bc2f84f3712a4bcf5619161955c5597298db5c5b which added an additional parameter but didn't update the usage in `babel-register` which resulted in the file being transformed with no options.

**Comment by thessem** [comment] 2016-02-08 02:24
@kittens that fixes it for me, thanks

**Comment by kittens** [comment] 2016-02-08 02:25
Great, thanks for confirming @thessem! I'll close this as it should be resolved. Please ping this issue if it isn't. We've started doing Babel prereleases and will need to configure it to integrate with the RN development process somehow.

**Closed by kittens** 2016-02-08 02:25 UTC

**Comment by kittens** [comment] 2016-02-08 02:32
[Babel 6.5.1 release notes](https://github.com/babel/babel/releases/tag/v6.5.1).

**Comment by himb2001** [comment] 2017-07-12 09:21
facing the same issue, how it can be closed if people who are start using it is also facing the same issue again and again.

react-native init project is not able to create all files required .

**Comment by wilkerlucio** [comment] 2017-07-15 20:43
I'm having the same issue too, is there a workaround for it?

**Comment by himb2001** [comment] 2017-07-15 20:50
@wilkerlucio.       Install yarn and then try to run 'react-native init project'
I am able to run it after installing yarn

**Comment by wilkerlucio** [comment] 2017-07-15 21:00
@himb2001 thanks, in the end I realized my issue was the node version, was using 4.x, upgrading to 6.11.1 solved the issue
