### ISSUE TITLE
Apple rejects React Native build with "ITMS-90338: Non-public API usage"

### ISSUE THREAD

**Issue by Tak-As** [facebook/react-native#33789] opened 2022-05-09 09:35 UTC
### Description

Submitting a React Native app build to the Apple App Store results in a rejection email regarding "Non-public API usage".

```
Dear Developer,

We identified one or more issues with a recent delivery for your app, "AppName" 1.0.0 (1.2.0). Please correct the following issues, then upload again.

ITMS-90338: Non-public API usage - The app references non-public selectors in AppName: centerY, hide:, isPassthrough, onSuccess:, permissionType, removeValuesForKeys:completion:, setLabelText:, show:, valueOffset, viewManager. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

Best regards,

The App Store Team
```

### Version

0.68.1

### Output of `npx react-native info`

System:
    OS: macOS 11.6.4
    CPU: (8) arm64 Apple M1
    Memory: 148.92 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.0.0 - ~/.nvm/versions/node/v16.0.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.0.0/bin/yarn
    npm: 7.10.0 - ~/.nvm/versions/node/v16.0.0/bin/npm
    Watchman: 2022.02.28.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.1 => 0.68.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1:Archive App(Release scheme)
2:Upload the resulting .ipa file to App Store Connect via Transporter (available on the Apple App Store)
3:Receive an email from apple that the build was rejected.

### Snack, code example, screenshot, or link to a repository

<img width="840" alt="image" src="https://user-images.githubusercontent.com/62008432/167382760-bd31cbe8-a897-4510-a238-e6cf661b9b22.png">

**Comment by cortinico** [comment] 2022-05-09 09:37
Which engine are you using?

**Comment by Tak-As** [comment] 2022-05-09 10:02
> Which engine are you using?

How can I find out?

**Comment by Tak-As** [comment] 2022-05-09 10:47
> > Which engine are you using?
> 
> How can I find out?

I'm using 'jsc' engine. not hermes.

```
{
  "expo.jsEngine": "jsc"
}
```

**Comment by Tak-As** [comment] 2022-05-10 11:05
I upgraded the OS to Monterey12.3.1, but there is no change.
However, in Xcode 13.3.1, the Validate App fails. (No error if Xcode 13.2.1)
<img width="751" alt="image" src="https://user-images.githubusercontent.com/62008432/167614761-3104fb38-f998-4d10-a67e-67e812bf7b63.png">

**Comment by fortmarek** [comment] 2022-05-16 11:59
Hey, there is a [PR](https://github.com/facebook/react-native/pull/33153) trying to address a similar thing - can you confirm you are trying to upload an app in debug mode? Any additional information about the issue would be helpful here @Tak-As @Andressaray

**Comment by brentvatne** [comment] 2022-05-16 16:55
Hi there! Are you using `expo-dev-client`? Also, can you make sure you are using the latest version of the `expo` package - the latest as of writing is 45.0.4.

**Comment by Tak-As** [comment] 2022-05-17 07:32
> Hey, there is a [PR](https://github.com/facebook/react-native/pull/33153) trying to address a similar thing - can you confirm you are trying to upload an app in debug mode? Any additional information about the issue would be helpful here @Tak-As @Andressaray

Thanks for reply.
In my environment ("react-native": "0.68.2") the result is the same in debug mode and release mode.
I can expect that my problem will be solved if the PR is merged.



> Hi there! Are you using `expo-dev-client`? Also, can you make sure you are using the latest version of the `expo` package - the latest as of writing is 45.0.4.

Thanks for reply.
Yes, I was install "expo-dev-client". but my project is rejected expo.(bare workflow)
Build fails when upgrading to expo 45.0.4 & expo-dev-client 0.9.5. (Command PhaseScriptExecution failed with a nonzero exit code)

**Comment by Kudo** [comment] 2022-05-17 15:08
@Tak-As please let me clarify whether the app you submit the app store had `expo-dev-client` installed or not?

**Comment by Tak-As** [comment] 2022-05-18 00:33
> @Tak-As please let me clarify whether the app you submit the app store had `expo-dev-client` installed or not?

It is installed.


Part of package.json
``` 
"dependencies": {
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-navigation/bottom-tabs": "^6.0.9",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/native-stack": "^6.2.5",
    "expo": "~45.0.4",
    "expo-dev-client": "~0.9.5",
    "native-base": "3.3.11",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "react-native-base64": "^0.2.1",
    "react-native-safe-area-context": "4.2.4",
    "react-native-screens": "~3.11.1",
    "react-native-step-indicator": "^1.0.3",
    "react-native-storage": "^1.0.1",
    "react-native-svg": "12.3.0",
    "redux": "^4.1.2"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@types/react": "~17.0.21",
    "@types/react-native": "~0.67.6",
    "@types/react-native-base64": "^0.2.0",
    "@typescript-eslint/eslint-plugin": "^5.9.1",
    "@typescript-eslint/parser": "^5.9.1",
    "eslint": "^8.6.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin": "^1.0.1",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-react": "^7.28.0",
    "eslint-plugin-unused-imports": "^2.0.0",
    "expo-cli": "^5.4.4",
    "prettier": "^2.5.1",
    "react-redux": "^8.0.1",
    "typescript": "4.6.4"
  },
```

**Comment by brentvatne** [comment] 2022-05-18 06:15
what version of `expo-modules-autolinking` is installed? can you share the output of `npm why expo-modules-autolinking` or `yarn why expo-modules-autolinking`?

**Comment by Tak-As** [comment] 2022-05-18 06:37
> what version of `expo-modules-autolinking` is installed? can you share the output of `npm why expo-modules-autolinking` or `yarn why expo-modules-autolinking`?


```
yarn why v1.22.17
[1/4] 🤔  Why do we have the module "expo-modules-autolinking"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "expo-modules-autolinking@0.7.1"
info Has been hoisted to "expo-modules-autolinking"
info Reasons this module exists
   - Hoisted from "expo-cli#@expo#prebuild-config#expo-modules-autolinking"
   - Hoisted from "expo#@expo#cli#@expo#prebuild-config#expo-modules-autolinking"
info Disk size without dependencies: "944KB"
info Disk size with unique dependencies: "1.97MB"
info Disk size with transitive dependencies: "7.21MB"
info Number of shared dependencies: 40
=> Found "expo#expo-modules-autolinking@0.8.1"
info This module exists because "expo" depends on it.
info Disk size without dependencies: "432KB"
info Disk size with unique dependencies: "1.47MB"
info Disk size with transitive dependencies: "6.71MB"
info Number of shared dependencies: 40
✨  Done in 0.48s.
```

**Comment by Kudo** [comment] 2022-05-19 08:21
@Tak-As could you use patch-package or modify node_modules/react-native locally for #33153 change and try to submit to app store again? because your private apis `centerY, hide:, isPassthrough, onSuccess:, permissionType, removeValuesForKeys:completion:, setLabelText:, show:, valueOffset, viewManager` do not have the private key events where the pr addressed. i am wondering #33153 may not able to fix your problem. at the same time, i also feel curious where the private apis coming from.

**Comment by gabriellend** [comment] 2022-06-03 00:35
![Screen Shot 2022-06-02 at 5 39 31 PM](https://user-images.githubusercontent.com/81834841/171761817-a7f419be-6f38-44ce-8b4d-3765bdf275d0.png)
Hello! My team is deadlocked at the same issue. We aren't using expo. Changing the names does work but I can't change all the names because some are only in binary files (found using grep). Issue #33153 seems like it might fix the problem but it looks like it might not be merged until 0.70, which we don't have time to wait for (need to submit a feature by June 30 or Apple will remove our app from the store). Has anyone found a fix for this? Here are my specs in case it helps. I appreciate anyone's help, thank you!:

OS: macOS 12.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 505.74 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.19.1 - ~/.nvm/versions/node/v12.19.1/bin/node
    Yarn: Not Found
    npm: 6.14.15 - ~/.nvm/versions/node/v12.19.1/bin/npm
    Watchman: 2022.02.14.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 30, 31
      Build Tools: 30.0.2, 30.0.3, 31.0.0
      System Images: android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.1 => 0.65.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by douglasjunior** [comment] 2022-06-06 20:27
Today we received this message:

> Dear Developer,
> 
> We identified one or more issues with a recent submission for TestFlight review for your app, "Move App Staging" 2.8.0 (44). Please correct the > following issues, then upload again.
> 
> ITMS-90338: Non-public API usage - The app references non-public selectors in ventasStaging: **estimatedProgress, initWithFrame:configuration:, > isMainFrame, isPassthrough, navigationType, onSuccess:, relativeSize, removeValuesForKeys:completion:, setIsEnabled:, setNavigationDelegate:, > setProcessPool:, spanArray, spanArray_Count, underline, updateSettings:, userContentController, viewManager, websiteDataStore**. If method names in your > source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. > In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. > For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/
> 
> Best regards,
> 
> The App Store Team

The weirdest thing is that nothing has been installed or updated in the app, only JS code has been modified since the last build.

React Native versions:

```json
    "react": "17.0.2",
    "react-native": "0.66.2",
```

Expo versions:

```json
    "expo": "43.0.4",
    "expo-camera": "12.0.3",
    "expo-document-picker": "10.1.0",
    "expo-file-system": "13.0.3",
    "expo-image-manipulator": "10.1.2",
    "expo-keep-awake": "10.0.1",
    "expo-screen-orientation": "4.0.3",
    "expo-sharing": "10.0.3",
```

yarn why expo-modules-autolinking

```
=> Found "expo-modules-autolinking@0.3.4"
info Reasons this module exists
   - "expo" depends on it
   - Hoisted from "expo#expo-modules-autolinking"
info Disk size without dependencies: "836KB"
info Disk size with unique dependencies: "1.58MB"
info Disk size with transitive dependencies: "2.99MB"
info Number of shared dependencies: 30
```

**Comment by diegogurpegui** [comment] 2022-06-06 20:43
Same issue here. We just got this error from Apple after building and submitting a new app.
The weird thing is, we just submitted an app 2 days ago, and the only change is a couple of JS lines.

**Comment by gabrieldonadel** [comment] 2022-06-06 20:51
I'm facing the same problem here as well

**Comment by beisert1** [comment] 2022-06-06 20:54
Same issue here affecting our apps this afternoon, seems to be related to the outage they had earlier today.

**Comment by msantang78** [comment] 2022-06-06 21:11
we are facing the same issue as well

**Comment by pedrovmc** [comment] 2022-06-06 21:14
Same on Flutter

**Comment by niraj-khatiwada** [comment] 2022-06-06 21:21
Same issue here:
Was working 3 days ago:
<img width="808" alt="image" src="https://user-images.githubusercontent.com/51436631/172251379-d8b20c4f-cae0-46ac-bc69-a7ba303ab531.png">

**Comment by emmarq** [comment] 2022-06-06 21:25
Apple, what did you do? 

For a brief moment it gives me hope

<img width="1011" alt="Screen Shot 2022-06-06 at 4 06 18 PM" src="https://user-images.githubusercontent.com/2946454/172251741-3b037984-74d7-4586-9f99-53484e33cc39.png">

But then, that email

> Dear Developer, 

> We identified one or more issues with a recent delivery for your app, "xxxx" 0.1.4 (7). Please correct the following issues, then upload again.

> ITMS-90338: Non-public API usage - The app references non-public selectors in LeahMobile: estimatedProgress, initWithFrame:configuration:, initWithURL:configuration:, initWithURL:entersReaderIfAvailable:, isMainFrame, isPassthrough, navigationType, newSocketQueueForConnectionFromAddress:onSocket:, onSuccess:, removeValuesForKeys:completion:, setNavigationDelegate:, setProcessPool:, socket:didAcceptNewSocket:, socket:didConnectToHost:port:, socket:didConnectToUrl:, socket:didReadData:withTag:, socket:didReadPartialDataOfLength:tag:, socket:didReceiveTrust:completionHandler:, socket:didWriteDataWithTag:, socket:didWritePartialDataOfLength:tag:, socket:shouldTimeoutReadWithTag:elapsed:bytesDone:, socket:shouldTimeoutWriteWithTag:elapsed:bytesDone:, socketDidCloseReadStream:, socketDidDisconnect:withError:, socketDidSecure:, targetFrame, userContentController, websiteDataStore. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

**Comment by ikeller96** [comment] 2022-06-06 21:38
Same issues here
<img width="729" alt="Screen Shot 2022-06-06 at 2 37 58 PM" src="https://user-images.githubusercontent.com/39099047/172253544-65d599b3-c8ce-4ac2-9ba4-3d8bb374f2e9.png">

**Comment by mcrvaz** [comment] 2022-06-06 21:42
What MacOS and XCode version are you guys using?

**Comment by ikeller96** [comment] 2022-06-06 21:45
Xcode Version 13.4.1
MacOS Monterey Version 12.4

I don't know if this helps but I am using Expo and EAS Build and Submit to submit builds to the app store. This is just the first spot I've been able to find where someone else is having the same issues as me.

**Comment by diegogurpegui** [comment] 2022-06-06 21:49
Just to provide more info (although this seems to be an Apple issue), we are not using Expo. Also we didn't update/upgrade any package.

**Comment by jwoo92** [comment] 2022-06-06 21:53
I'm also seeing this from Apple after a few lines of JS code changes. 

Only notable change since last release is I've updated Xcode (I was on latest until new update).

MacOS Monterey Version 12.4 (21F79)
Xcode Version 13.4 (13F17a)

```json
"react": "17.0.1",
"react-native": "0.64.3",
"expo": "^44.0.0",
"expo-dev-client": "~0.8.5",
"expo-app-loading": "~1.3.0",
"expo-apple-authentication": "~4.1.0",
"expo-application": "~4.0.1",
"expo-asset": "~8.4.6",
"expo-av": "~10.2.0",
"expo-blur": "~11.0.0",
"expo-camera": "~12.1.2",
"expo-cellular": "~4.1.0",
"expo-constants": "~13.0.1",
"expo-device": "~4.1.0",
"expo-facebook": "~12.1.0",
"expo-file-system": "~13.1.2",
"expo-font": "~10.0.4",
"expo-google-sign-in": "~10.1.0",
"expo-haptics": "~11.1.0",
"expo-image-manipulator": "~10.2.0",
"expo-image-picker": "~12.0.1",
"expo-keep-awake": "~10.0.1",
"expo-linear-gradient": "~11.0.0",
"expo-linking": "~3.0.0",
"expo-media-library": "~14.0.0",
"expo-navigation-bar": "~1.1.1",
"expo-network": "~4.1.0",
"expo-permissions": "~13.1.0",
"expo-secure-store": "~11.1.0",
"expo-splash-screen": "~0.14.1",
"expo-status-bar": "~1.2.0",
"expo-store-review": "~5.1.0",
"expo-system-ui": "~1.1.0",
"expo-updates": "~0.11.7",
"expo-web-browser": "~10.1.0",
```

yarn why expo-modules-autolinking

```shell
=> Found "expo-modules-autolinking@0.5.5"
info Reasons this module exists
   - "expo" depends on it
   - Hoisted from "expo#expo-modules-autolinking"
   - Hoisted from "expo-splash-screen#@expo#prebuild-config#expo-modules-autolinking"
info Disk size without dependencies: "948KB"
info Disk size with unique dependencies: "1.74MB"
info Disk size with transitive dependencies: "3.14MB"
info Number of shared dependencies: 30
```

**Comment by MasoudJB** [comment] 2022-06-06 23:28
Same issue here, I was able to build and submit yesterday without any issue and we only have some minor changes.

**Comment by jwoo92** [comment] 2022-06-06 23:39
> I'm also seeing this from Apple after a few lines of JS code changes. 
> 
> 
> 
> Only notable change since last release is I've updated Xcode (I was on latest until new update).
> 
> 
> 
> MacOS Monterey Version 12.4 (21F79)
> 
> Xcode Version 13.4 (13F17a)
> 
> 
> 
> ```json
> 
> "react": "17.0.1",
> 
> "react-native": "0.64.3",
> 
> "expo": "^44.0.0",
> 
> "expo-dev-client": "~0.8.5",
> 
> "expo-app-loading": "~1.3.0",
> 
> "expo-apple-authentication": "~4.1.0",
> 
> "expo-application": "~4.0.1",
> 
> "expo-asset": "~8.4.6",
> 
> "expo-av": "~10.2.0",
> 
> "expo-blur": "~11.0.0",
> 
> "expo-camera": "~12.1.2",
> 
> "expo-cellular": "~4.1.0",
> 
> "expo-constants": "~13.0.1",
> 
> "expo-device": "~4.1.0",
> 
> "expo-facebook": "~12.1.0",
> 
> "expo-file-system": "~13.1.2",
> 
> "expo-font": "~10.0.4",
> 
> "expo-google-sign-in": "~10.1.0",
> 
> "expo-haptics": "~11.1.0",
> 
> "expo-image-manipulator": "~10.2.0",
> 
> "expo-image-picker": "~12.0.1",
> 
> "expo-keep-awake": "~10.0.1",
> 
> "expo-linear-gradient": "~11.0.0",
> 
> "expo-linking": "~3.0.0",
> 
> "expo-media-library": "~14.0.0",
> 
> "expo-navigation-bar": "~1.1.1",
> 
> "expo-network": "~4.1.0",
> 
> "expo-permissions": "~13.1.0",
> 
> "expo-secure-store": "~11.1.0",
> 
> "expo-splash-screen": "~0.14.1",
> 
> "expo-status-bar": "~1.2.0",
> 
> "expo-store-review": "~5.1.0",
> 
> "expo-system-ui": "~1.1.0",
> 
> "expo-updates": "~0.11.7",
> 
> "expo-web-browser": "~10.1.0",
> 
> ```
> 
> 
> 
> yarn why expo-modules-autolinking
> 
> 
> 
> ```shell
> 
> => Found "expo-modules-autolinking@0.5.5"
> 
> info Reasons this module exists
> 
>    - "expo" depends on it
> 
>    - Hoisted from "expo#expo-modules-autolinking"
> 
>    - Hoisted from "expo-splash-screen#@expo#prebuild-config#expo-modules-autolinking"
> 
> info Disk size without dependencies: "948KB"
> 
> info Disk size with unique dependencies: "1.74MB"
> 
> info Disk size with transitive dependencies: "3.14MB"
> 
> info Number of shared dependencies: 30
> 
> ```

Just tried again after updating Xcode to 13.4.1... no luck, same outcome.

**Comment by RSchneider94** [comment] 2022-06-07 00:22
Same here, just changed one line in my TS code and it is not working anymore, no Xcode updates, nothing!

**Comment by gabriellend** [comment] 2022-06-07 01:54
As many others, the same thing is happening to us. No packages updated, just some minor javascript changes. Not using expo. We resolved the issue in debug mode by changing a few variable names but in release mode we are getting a notification about different ones and there are way more, doesn't seem feasible to manually change them all. Glad to find this thread, at least we're not alone! Seems like an Apple issue.

**Comment by thomaskbird** [comment] 2022-06-07 03:23
Experiencing the same with React Native and everything was working as of yesterday for us.

**Comment by jwaldrip** [comment] 2022-06-07 03:44
Same here, builds are not rolling out...

**Comment by ikeller96** [comment] 2022-06-07 05:20
This may be due to apple updating their policy. Saw a comment that suggested needing to log in to your apple developer account (separate from app store connect) and agree to the updated policy. Apparently submissions will work after this? I'm testing this now.

**Comment by BennSandoval** [comment] 2022-06-07 05:34
"The issue has been resolved on the app validation backend. Please try resubmitting. Sorry for the trouble."
by Developer Tools Engineer https://developer.apple.com/forums/thread/127678?page=6

**Comment by paulocoutinhox** [comment] 2022-06-07 05:55
Hi,

Message from Apple: "The issue has been resolved on the app validation backend. Please try resubmitting. Sorry for the trouble."

Thanks.

**Comment by stuckj** [comment] 2022-06-07 13:53
I can verify that we're able to submit now (with the same code).

**Comment by diegogurpegui** [comment] 2022-06-07 14:03
I can confirm too that the issue was resolved by Apple.

**Comment by jwoo92** [comment] 2022-06-07 14:45
> "The issue has been resolved on the app validation backend. Please try resubmitting. Sorry for the trouble." by Developer Tools Engineer https://developer.apple.com/forums/thread/127678?page=6

Thanks for the callout, @BennSandoval.

Tried uploading again and found success.

**Comment by Tak-As** [comment] 2022-06-29 06:38
I solved it once, but the problem occurred again.
Is it just my problem?

**Comment by paulocoutinhox** [comment] 2022-06-29 14:27
> I solved it once, but the problem occurred again. Is it just my problem?

Update the macOS to Mojave and Xcode to latest version.

**Comment by Tak-As** [comment] 2022-07-19 08:57
This issue has not yet been resolved.
Many people seem to be able to fix it by changing the schema to a release, but it doesn't seem to work in my environment.
Is there any workaround for the issue where the release build doesn't work?
thank you.

**Comment by airowe** [comment] 2022-08-05 20:47
Seeing the same issue as @Tak-As. Building a release scheme. Debug mode works just fine.

**Comment by abazudosen** [comment] 2022-09-03 20:39
> I can confirm too that the issue was resolved by Apple.

how did you solve it

**Comment by diegogurpegui** [comment] 2022-09-03 20:52
> > I can confirm too that the issue was resolved by Apple.
> 
> how did you solve it

I didn't. It was an Apple issue, after a day it was sorted out and, without doing anything different, it worked.

**Comment by mvniekerk** [comment] 2022-09-17 20:47
Still an issue.
Even with blank new ejected Expo app.
I've logged a report here https://github.com/facebook/react-native/issues/34716

**Comment by saad9624-tribalScale** [comment] 2022-10-11 07:31
> https://developer.apple.com/forums/thread/127678?page=6

Still getting the same issue in October

**Comment by prakarti-shush** [comment] 2022-10-18 10:26
getting the same issue with newer version of Xcode 14

**Comment by kelset** [comment] 2022-10-18 11:51
This issue has gone in many different directions (in some cases it's Apple's backend, in some it's Expo-related, etc etc) and there's no clear repro that pinpoints how this is a specific issue caused by react-native core itself.

I am closing this so if **anyone** has this issue with the **latest** version of react-native 0.70 (NOT EXPO) they can open a new issue with a clear, usable repro so that it can be investigated further.

**Closed by kelset** 2022-10-18 11:51 UTC
Labels: Platform: iOS, Priority: Mid, Impact: App Rejected, Needs: Attention, Type: New Architecture, Tech: React Native Core
