### ISSUE TITLE
[Android] [TextInput] Placeholder font doesn't match TextInput styling

### ISSUE THREAD

**Issue by AdamGorkoz** [facebook/react-native#4600] opened 2015-12-06 15:26 UTC
Hi , Is it possible to set the font style of the placeholder of a text component on android ? as far as the docs go you can only change the text.

**Comment by txix** [comment] 2015-12-22 12:54
I'm also having an issue with the placeholder text on Android. It does not apply the fontFamily which I have set in the styles. When I focus the TextInput the right fontFamily does get applied.

**Comment by satya164** [comment] 2015-12-22 23:04
Can confirm this.

**Comment by ramneekhanda** [comment] 2016-02-25 18:34
+1

**Comment by sabashBlaze** [comment] 2016-02-29 05:21
Hi,
 I am also having this issue. Placeholder text fontFamily not applied, when I type to TextInput fontFamily applied

**Comment by eric1iu** [comment] 2016-03-04 23:52
the default fontFamily not the same when set secureTextEntry={true}. looks weird.

**Comment by brunobar79** [comment] 2016-05-17 19:32
I think this can be closed since it was fixed here:  https://github.com/facebook/react-native/pull/6564 and will be released on 0.26

**Comment by charpeni** [comment] 2016-05-20 13:59
@facebook-github-bot close

**Comment by facebook-github-bot-1** [comment] 2016-05-20 14:11
@charpeni tells me to close this issue. If you think it should still be opened let us know why.

**Comment by drpiou** [comment] 2016-05-24 11:35
I don't know why it was closed, placeholder font style doesn't match TextInput style on Android with ReactNative 0.26.1 (iOS works fine, fontFamily is applied for placeholder as expected).

**Comment by satya164** [comment] 2016-05-24 14:12
I can repro this successfully. Placeholder still has the default font. The mentioned PR applies the style to the value text, but not the placeholder text.

**Comment by peterhn** [comment] 2016-05-24 21:42
I can confirm this as well. My placeholder text font family doesn't match textinput font family.

**Comment by SudoPlz** [comment] 2016-06-21 07:22
I can confirm as well! Product pain opened here https://productpains.com/post/react-native/textinput-allow-us-to-customize-the-style-font-family-etc-of-the-placeholder-text

**Comment by luisfuertes** [comment] 2016-06-27 09:17
I have "react-native": "^0.25.1" and when i put `secureTextEntry={true}` fontsFamily break.. how can fix it?

**Comment by julien-rodrigues** [comment] 2016-07-13 14:57
I use the `0.29` and I have the issue too

**Comment by aakashsigdel** [comment] 2016-07-17 11:29
Placeholder shown middle of the text input if a larger height is given on android. In ios it is on the top. Isn't there a way of defining where to place the placeholder? rn0.28.0

<img width="438" alt="screen shot 2016-07-17 at 5 12 45 pm" src="https://cloud.githubusercontent.com/assets/4772643/16900329/dd825d5e-4c41-11e6-95c1-2e1b0c8a78f5.png">

**Comment by Arwiz** [comment] 2016-07-22 07:25
I am facing the same issue (aakashsigdel ) is there any workaround you get  ?

**Comment by aakashsigdel** [comment] 2016-07-22 12:00
@Arwiz 
Well, it was in the documentation. I somehow missed it. 
Here is how to do it:
textAlignVertical ReactPropTypes.oneOf( ['auto' /*default*/, 'top', 'bottom', 'center'] )
https://facebook.github.io/react-native/docs/text.html#style

**Comment by magrinj** [comment] 2016-07-22 12:58
Same issue, my placeholder style doesn't match with the input style, I got this bug only on android phones.

**Comment by CapitanRedBeard** [comment] 2016-09-20 21:21
My TextInput text in general isn't applying the correct font family. Placeholder AND entered text. Only on Android and I'm on v0.31

**Comment by you-fail-me** [comment] 2016-09-23 14:03
I can also confirm this issue. React native v0.31, unable to change placeholder fontFamily on android

**Comment by MrCeleryman** [comment] 2016-09-28 06:27
Yea same here on v0.31 for Placeholder and entered text in TextInput but is fine on Buttons

**Comment by NazarYablonskiy** [comment] 2016-10-04 16:12
The same, if I'm trying to use custom font.

**Comment by mradionov** [comment] 2016-10-11 17:10
Temporary solution might be adding an absolutely position Text on top of TextInput and hiding/showing it when TextInput is focused/blurred respectively.

**Comment by valetarton** [comment] 2016-10-25 17:52
@mradionov seems like the only solution in the interim

**Comment by teodors** [comment] 2016-12-10 13:16
What is the progress on this one?

@mradionov This is similar to what I currently have, but instead of hiding/showing on focus/blur I am hiding/showing on text input. Problem however is that you can see typed text before you can hide placeholder. So for 2-4ms you still see the placeholder behind the text before new state renders. Is anyone else have this problem?

**Comment by omegatiger** [comment] 2016-12-14 19:55
I can also confirm this issue. React native **v0.38,** unable to change placeholder fontFamily on android.

**Comment by sdlovecraft** [comment] 2016-12-14 22:20
can also confirm this issue on react native v0.38

**Comment by MrCeleryman** [comment] 2016-12-14 23:53
Upgraded to v0.39 and can confirm this is still an issue

**Comment by alisonkohl** [comment] 2016-12-21 00:45
+1, still experiencing this as well

**Comment by ag7** [comment] 2016-12-27 10:01
+1

**Comment by goncalomarques** [comment] 2017-01-04 17:14
+1

**Comment by bennygenel** [comment] 2017-01-10 15:58
+1 v0.39

**Comment by fabien-h** [comment] 2017-01-12 12:44
still there on 0.40

**Comment by satya164** [comment] 2017-01-12 13:03
Please don't reply with `+1` or saying that you still have the issue. This issue is still open because it's a known issue and hasn't been fixed yet. Commenting only spams everyone without doing anything to fix it.

Feel free to send a PR if you are willing to fix this.

**Comment by SandroMachado** [comment] 2017-01-23 12:10
Refs: https://github.com/facebook/react-native/pull/12000

**Comment by JosephMoralesGE** [comment] 2017-01-23 21:22
Can we have an eta on a fix for this issue?

**Comment by ide** [comment] 2017-01-23 22:36
@janicduplessis has a PR out. I expect this to go out with RN 0.42 (Feb 1 RC, Mar 1 final release).

**Closed** 2017-01-24 19:29 UTC
Labels: Android, Ran Commands
