### ISSUE TITLE
IOS - zIndex ignored with nested views

### ISSUE THREAD

**Issue by sodik82** [facebook/react-native#8970] opened 2016-07-22 12:27 UTC
Following code does not work as expected on IOS simulator with RN 0.30.0. On android it seems to work correctly.

``` javascript
import React, { Component } from 'react';
import { StyleSheet, Text, View } from 'react-native';

export default class Demo extends Component {
  render() {
    return (
      <View style={styles.container}>
        <View>
          <View style={[styles.blueItem, {zIndex: 100}]}>
            <Text>zIndex: 100</Text>
          </View>
        </View>
        <View style={[styles.greenItem, styles.absolute, {zIndex: 2}]}>
          <Text>zIndex: 2</Text>
        </View>
      </View>
    );
  }

}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 20,
  },
  blueItem: {
    backgroundColor: 'blue',
    height: 50,
  },
  greenItem: {
    backgroundColor: 'green',
    height: 50,
    width: 50,
    position: 'absolute',
    top: 45,
    left: 0,
  },
});
```

I would expect that blue item with zIndex 100 will be over green box (with zIndex 2). 

![image](https://cloud.githubusercontent.com/assets/6132259/17057101/47e87712-5018-11e6-9cbd-cec2b3aa5941.png)

Note that if I remove the "outer view" (around blue box), zIndex works fine.

**Comment by JohnyDays** [comment] 2016-07-25 15:10
This is how zindex works, every new view creates a zIndex stacking context.
https://philipwalton.com/articles/what-no-one-told-you-about-z-index/

**Comment by sodik82** [comment] 2016-07-25 18:38
hm... it is trickier than I expected :) 
I have tried following example in Chrome and it seems to work as I would expect (D is over C): http://codepen.io/anon/pen/JKvZxX

**Comment by JohnyDays** [comment] 2016-07-25 22:07
Also every item starts at zIndex: 0 I believe, basically that means that stacking contexts as defined in WC3 isn't really implemented to spec (for performance and complexity reasons). 
What you get with this new zIndex system is resolving sibling view display order independent of their order in code. I'm not sure it's much more than that, though I might be wrong, would be good to get some opinion from a core member.

Tagging @vjeux because I know he cares about web spec compatibility,

**Comment by sodik82** [comment] 2016-07-26 07:22
thanks for insights. more clarification about intended behaviour will be good anyway.
compatibility between platforms (ios/android) is still the problem - one platform does not behave as expected.

**Comment by singno** [comment] 2016-08-09 09:17
The behavior of zIndex is strange. Is possible  behave as browser's zIndex?

**Comment by JohnyDays** [comment] 2016-08-09 11:07
The browser makes some performance tradeoffs, and has significant added layout complexity in every other part of the layout system, in order to be able to implement z-index to spec. I'm not sure this is something react-native wants/needs, especially since most problems related to z-index can be solved in another way.

**Comment by fab1an** [comment] 2016-08-20 13:52
I don't think using `zIndex` is a good idea on react-native. It only works when `View`s are siblings of each other, which can change, when RN is collapsing views for performance reasons.

**Comment by lacker** [comment] 2016-11-30 00:18
It sounds like this is at least "working as intended" if not "working according to spec" so I am going to close this issue.

**Closed by lacker** 2016-11-30 00:18 UTC

**Comment by sodik82** [comment] 2016-11-30 07:17
@lacker - does it mean that Android it is not "working as intended" then? should I open issue for that android and IOS zIndex is working differently?

**Comment by lacker** [comment] 2016-11-30 18:58
Ehh, hmm that is weird. It does seem like it should work the same across iOS and Android. Yeah, could you open a new issue for that? Ideal would be a rnplay.org link that shows different behavior in iOS + Android.

**Comment by sodik82** [comment] 2016-12-01 09:19
for those interested demo is here - https://rnplay.org/apps/gLwHvg
however it seems that the difference is caused by android view removal and can be "fixed" by `collapsable={false}`

**Comment by lacker** [comment] 2016-12-01 16:41
I'm glad there's a workaround, at least.

**Comment by Kalyani518** [comment] 2017-03-08 15:41
zIndex not working in IOS but its working in Android "https://rnplay.org/apps/Ji5rSQ",
Can you please help
