### ISSUE TITLE
'glog/logging.h' file not found

### ISSUE THREAD

**Issue by MohamadKh75** [facebook/react-native#22703] opened 2018-12-19 07:23 UTC
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i7-2620M CPU @ 2.70GHz
      Memory: 6.74 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.58.0-rc.1 => 0.58.0-rc.1
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

## Description
I just tried to create a new project using `react-native init --version=react-native@0.58.0-rc.1` for testings about [this issue](https://github.com/facebook/react-native/issues/22267) but i face this problem! I guess this is a regression!

## Reproducible Demo
1. `react-native init MyTestingProject --version=react-native@0.58.0-rc.1`
2. `cd MyTestingProject/ios`
3. open `MyTestingProject.xcodeproj`
4. File / Project Settings... / Build System => Legacy Build System / Done
5. Product / Clean
6. Product / Clean Build Folder
7. Build

**Comment by EdwardDrapkin** [comment] 2018-12-19 09:46
Did you try the ole `rm -rf ~/.rncache node_modules/react-native/third-party/*`?

**Comment by MohamadKh75** [comment] 2018-12-19 11:14
> Did you try the ole `rm -rf ~/.rncache node_modules/react-native/third-party/*`?

Yep but no result!

**Comment by MohamadKh75** [comment] 2019-01-27 14:19
I can confirm that this issue is resolved in Xcode 10.1 but exist in Xcode 10

**Comment by kelset** [comment] 2019-01-28 08:47
thanks for reporting, I feel that we can close this then.

**Closed by kelset** 2019-01-28 08:47 UTC
Labels: Bug Report, Platform: iOS

**Comment by thecodecafe** [comment] 2019-01-31 14:19
@MohamadKh75  Using Xcode 10.1 and experiencing this.

**Comment by MohamadKh75** [comment] 2019-01-31 21:18
🤔🤔🤔
So maybe we should reopen this, @kelset?

**Comment by kelset** [comment] 2019-02-01 15:04
I'd prefer to have some repro steps before reopening.

**Comment by guruparan** [comment] 2019-02-20 07:40
i'm getting the same error in xcode 10.1, i'm trying to upgrade a project from version 57 to 58.5, did anyone fix this ?

**Comment by guruparan** [comment] 2019-02-20 11:44
I fixed it by deleting the podlock file, sharing here so that it might help someone

**Comment by sagargondaliya** [comment] 2019-03-26 10:05
> Well, i know this is a weird solution but it works!
> 
> I edited `../node_modules/react-native/scripts/ios-install-third-party.sh` and deleted these lines:
> 
> ```
> fetch_and_unpack glog-0.3.5.tar.gz https://github.com/google/glog/archive/v0.3.5.tar.gz 61067502c5f9769d111ea1ee3f74e6ddf0a5f9cc "\"$SCRIPTDIR/ios-configure-glog.sh\""
> fetch_and_unpack double-conversion-1.1.6.tar.gz https://github.com/google/double-conversion/archive/v1.1.6.tar.gz 1c7d88afde3aaeb97bb652776c627b49e132e8e0
> fetch_and_unpack boost_1_63_0.tar.gz https://github.com/react-native-community/boost-for-react-native/releases/download/v1.63.0-0/boost_1_63_0.tar.gz c3f57e1d22a995e608983effbb752b54b6eab741
> fetch_and_unpack folly-2016.10.31.00.tar.gz https://github.com/facebook/folly/archive/v2016.10.31.00.tar.gz fb8cdf8962d8c9d0c20a150b6ec3b75d1fa50696
> ```
> then i copied the whole `third-party` folder from another project which is `"react-native": "0.57.7"` and its working!
> 
> Please consider that i ran `./configure` and `make` in the project of `"react-native": "0.57.7"` too!
> 
> I guess there's a problem in the GitHub files!
> 
> @hramos (BTW, Happy New Year 😁 🎉 )

You saved my day!!! Thanks

**Comment by rainytooo** [comment] 2019-05-24 06:52
I have solved this problem today 
https://github.com/facebook/react-native/issues/24990#issuecomment-495493250

**Comment by KushalDesai1** [comment] 2019-07-03 12:14
I have tried all the above solutions.

config.h & loggin.h files are also generated.

But when I run 'react-native run-ios' in the terminal OR when I build the project from Xcode 10.1, config.h file, logging.h file are somehow deleted.

I don't know what's going on.

How are you guys able to solve everything? I am trying every solution that I possible could since many months.

Please help.

**Comment by alouiseq** [comment] 2019-07-07 07:38
@KushalDesai1 I've also encountered this issue and could not get any of the proposed solutions to work. However, I did find one that did. I copied ios-configure-glog.sh from the react-native@0.57.7 project to my current project react-native@0.59. It turns out that in my case it wasn't a corrupted install of glog or double-conversion. The issue was with the following code in the script:

```
# Prepare exported header include
EXPORTED_INCLUDE_DIR="exported/glog"
mkdir -p exported/glog
cp -f src/glog/log_severity.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/raw_logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/stl_logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/vlog_is_on.h "$EXPORTED_INCLUDE_DIR/"
```
Try removing that if it exists in your current project. Hopefully that works for you.

**Comment by RafikiTiki** [comment] 2019-07-10 11:41
Same issue happened to me after cancelling build in xcode and running it again (xcode v10.2.1, rn 0.59.10). I used `Product->Clean Build Folder` and puff, it fixed the problem.

**Comment by cinder92** [comment] 2019-08-17 02:24
same issue with RN 0.60.5 and Xcode 3 any update?

**Comment by madeinquant** [comment] 2019-08-22 06:51
Hope this help.

info Fetching system and libraries information...
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Memory: 680.81 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.8.1 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
    react-native-macos-cli: 2.0.1

=====================================    
1. rm -rf node_modules/ && yarn cache clean && yarn install
2. rm -rf ~/.rncache
3. cd node_modules/react-native/scripts
4. ./ios-install-third-party.sh (install folly-2016.10.31.00 double-conversion glog)
5. cd <Your-Project-Folder>/node_modules/react-native/third-party/glog*
6. ./configure
7. Xcode clean (Cmd + Shift + K) and build (react-native run-ios).

**Comment by hungdev** [comment] 2019-08-24 04:02
thanks @guruparan it works for me.
just delete  the podlock file, and run pod install

**Comment by thisisablock** [comment] 2019-09-02 19:58
fix here https://github.com/facebook/react-native/pull/26300

if you get 'glog/logging.h' the third party libraries are failed to install.
the podspec script launch is not throwing any error.

if you are on appcenter you need to update the pods on pre-build
https://gist.github.com/thisisablock/b57185cc3657d4e0252960a0bd7cf0a9

**Comment by AlexArtisan** [comment] 2019-09-04 16:33
Just run "ios-configure-glog.sh" from glog dir.

After comment all 4 last lines - `fetch_and_unpack ...` in "ios-install-third-party.sh"

And run in XCode or rn cli.

**Comment by thisisablock** [comment] 2019-09-04 17:34
@AlexArtisan yep it’s workaround but it didn’t fix the origin. The issue is that the ios-install fails to install glog because it’s calling the the installer from a wrong workdir. On pod install it not throwing any error because cocoapods sadly is not able to throw an exception here.

But it’s not safe because on every fresh npm install  (for example on appcenter) the dependencies are not downloaded and will not be included inside pod install.

**Comment by marcin-modestowicz** [comment] 2019-09-24 14:12
In my case the root cause was the space in "Xcode 10.1" app name. Maybe it will help someone.

**Comment by artechventure** [comment] 2019-10-13 06:41
@marcin-modestowicz Could you tell what space you mean exactly? And how did you fix it?

**Comment by marcin-modestowicz** [comment] 2019-10-14 08:35
@artechventure I installed Xcode in Applications under `XCode 10.1` directory (with space) and it broke compilation process. Renaming to `XCode10.1` fixed the issue.

**Comment by artechventure** [comment] 2019-10-14 08:49
@marcin-modestowicz thanks. saved my time

**Comment by annieneedscoffee** [comment] 2019-12-03 04:36
I had the same issue. I copied MyProjectName/node_modules/react-native/third-party/glog-0.3.5 from a different working project and replaced the version of glog-0.3.5 in the non-working project and now it seems to be ok.
