### ISSUE TITLE
TabBarIOS doesn't rotate correctly

### ISSUE THREAD

**Issue by sandwichfeet** [facebook/react-native#809] opened 2015-04-11 04:33 UTC
When a TabBar is being used the app doesn't resize the screen correctly.  I don't think this has ever worked.

![screen shot 2015-04-11 at 05 28 53](https://cloud.githubusercontent.com/assets/6278512/7100229/f39aa0ea-e00b-11e4-975d-2151af3ae84b.png)

![screen shot 2015-04-11 at 05 31 19](https://cloud.githubusercontent.com/assets/6278512/7100231/0257c310-e00c-11e4-9a1b-b68ef0da269d.png)

**Comment by ericvicenti** [comment] 2015-04-13 21:07
I have a feeling this is a general issue with resizing TabBarIOS, and is not specifically related to the device rotation.

**Comment by timfpark** [comment] 2015-05-18 05:15
I had an issue like this and it seems to be fixed as of 0.4.4.

**Comment by joewood** [comment] 2015-05-23 19:12
I still this issue in 0.4.4.  I don't see onLayout firing for device orientation changes.
Saying that, I **don't** see this issue in UIExplorer using the same build and I can't see what UIExplorer is doing differently.

**Comment by brentvatne** [comment] 2015-05-30 20:37
@joewood - if you still see the issue, can you reproduce in a public repo or on [rnplay.org](rnplay.org)?

**Closed by brentvatne** 2015-05-30 20:37 UTC
