### ISSUE TITLE
Error code: 500

### ISSUE THREAD

**Issue by phantomsan** [facebook/react-native#24172] opened 2019-03-27 20:33 UTC
## 🐛 Bug Report

  After I run the command "react-native run-android" the emulator shows a red screen returning Error code 500, then "Error: Unable to resolve module `./index` from `C:\Users\ricar\Desktop\PrimeiroProjeto\node_modules\react-native\scripts/.`: The module `./index` could not be found from `C:\Users\ricar\Desktop\PrimeiroProjeto\node_modules\react-native\scripts" and severals of others.

## To Reproduce

  on prompt, run the commands:
react-native run-android

## Expected Behavior

  Open the first application without any issues.

## Code Example

  The development server returned response error code: 500

URL: http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false

Body:
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: Unable to resolve module `./index` from `C:\Users\ricar\Desktop\PrimeiroProjeto\node_modules\react-native\scripts/.`: The module `./index` could not be found from `C:\Users\ricar\Desktop\PrimeiroProjeto\node_modules\react-native\scripts/.`. Indeed, none of these files exist:<br> &nbsp;* `C:\Users\ricar\Desktop\PrimeiroProjeto\node_modules\react-native\scripts\index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`<br> &nbsp;* `C:\Users\ricar\Desktop\PrimeiroProjeto\node_modules\react-native\scripts\index\index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`<br> &nbsp; &nbsp;at ModuleResolver.resolveDependency (C:\Users\ricar\Desktop\PrimeiroProjeto\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)<br> &nbsp; &nbsp;at ResolutionRequest.resolveDependency (C:\Users\ricar\Desktop\PrimeiroProjeto\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)<br> &nbsp; &nbsp;at DependencyGraph.resolveDependency (C:\Users\ricar\Desktop\PrimeiroProjeto\node_modules\metro\src\node-haste\DependencyGraph.js:283:16)<br> &nbsp; &nbsp;at C:\Users\ricar\Desktop\PrimeiroProjeto\node_modules\metro\src\lib\transformHelpers.js:261:42<br> &nbsp; &nbsp;at Server.&lt;anonymous&gt; (C:\Users\ricar\Desktop\PrimeiroProjeto\node_modules\metro\src\Server.js:1038:41)<br> &nbsp; &nbsp;at Generator.next (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at asyncGeneratorStep (C:\Users\ricar\Desktop\PrimeiroProjeto\node_modules\metro\src\Server.js:99:24)<br> &nbsp; &nbsp;at _next (C:\Users\ricar\Desktop\PrimeiroProjeto\node_modules\metro\src\Server.js:119:9)</pre>
</body>
</html>

processBundleResult
    BundleDownloader.java:296
access$200
    BundleDownloader.java:37
onResponse
    BundleDownloader.java:174
execute
    RealCall.java:206
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1113
run
    ThreadPoolExecutor.java:588
run
    Thread.java:818

## Environment

  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
      Memory: 4.25 GB / 7.91 GB
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842
![Capture](https://user-images.githubusercontent.com/37161281/55110271-75139b80-50b6-11e9-8448-655b85863329.PNG)

**Comment by samad324** [comment] 2019-03-28 09:11
Yes, I have the same issue, I've just init a new project and just hit `react-native run-android` and got the same error.

**Comment by samad324** [comment] 2019-03-28 09:12
but my old projects are working fine!

**Comment by samad324** [comment] 2019-03-28 10:33
my issue was resolved my downgrade `react` and `react-native` version to:
***js
 "react": "16.6.3",
 "react-native": "0.58.4"
***

**Comment by ssaar** [comment] 2019-03-28 17:16
I have the same issue, it happens with both iOS and Android. It can be gotten around by killing the metro bundler then running `react-native start`. This happened after upgrade from .58 to .59.1

`react-native info`
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 1.03 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 27, 28
        Build Tools: 28.0.3
        System Images: android-25 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.59.1 => 0.59.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by kelset** [comment] 2019-03-28 17:39
Duplicate of https://github.com/facebook/react-native/issues/24112

**Closed by kelset** 2019-03-28 17:39 UTC
Labels: Type: Bug Report
