### ISSUE TITLE
PermissionsAndroid.request never resolves

### ISSUE THREAD

**Issue by jgfidelis** [facebook/react-native#17985] opened 2018-02-14 19:01 UTC
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes.

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 9.4.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.0 => 0.53.0

Edit: according to @MateRyze, it still happens on react-native 0.55.4.

  Target Platform: Android 6.0.1

### Steps to Reproduce

We have a Camera component and it should check for the Camera permission before mounting.

In my app's AndroidManifest.xml I have the line, along with many other permissions:
```
<uses-permission android:name="android.permission.CAMERA"/>
```

In our component's `componentDidMount()` we call a function that should return `true` if we have permission and `false` if we do not have, here is the relevant snippet of the function:
```
if (Platform.OS === 'android') {
const isGranted = await PermissionsAndroid.check(PermissionsAndroid.PERMISSIONS.CAMERA);
      if (isGranted) {
        return true;
      }
      try {
        console.log('before request');
        const granted = await PermissionsAndroid.request(
          PermissionsAndroid.PERMISSIONS.CAMERA,
          {
            title: 'Dialog Title',
            message: 'Dialog Message',
          }
        );
        console.log('after request');
        return granted === PermissionsAndroid.RESULTS.GRANTED;
      } catch (err) {
        console.log('error');
        console.log(err);
      }
}
```

### Expected Behavior

A dialog with my title and message should appear, if the user clicks on "Allow", the promise should resolve and my component should render as expected.

### Actual Behavior

A dialog with a different message and title appears. I click on "Allow" and the promise is never resolved or rejected.

In my logs, only the "before request" log appears. Neither`console.log('after request')` or `console.log('error')` is logged, so I presume the code is stuck in the await.

I am following this [doc](https://facebook.github.io/react-native/docs/0.53/permissionsandroid.html).

**Comment by jgfidelis** [comment] 2018-02-25 20:19
up :(

**Comment by jgfidelis** [comment] 2018-04-18 17:01
Up again. This error happens in one of our apps in production, we tried to make a workaround for it multiple times but nothing works. Even if we ask for the permission when the app starts, it still hangs and never resolves.

@aryo, will try to confirm what you said, thanks

Would love any follow up

**Comment by SchmidmajerReka** [comment] 2018-05-10 12:27
The alert asking for permission is shown as expected, but sometimes in case of denial the promise do not resolves and because of this the app flow stops. If the permission is granted the flow goes as expected, the promise resolves.

**Comment by jslz** [comment] 2018-05-10 20:50
This is happening to us, appears to most reliably happen on one of our testers' Nexus 6; doesn't repro on some other Android devices. For us no matter if the permission is granted or denied, it can lead to the unresolving promise it seems.
react-native-cli: 2.0.1
react-native: 0.51.0
platform: android
builds: at least release builds

**Comment by SchmidmajerReka** [comment] 2018-05-11 11:56
It happens with different android versions and different devices for us. 
First we hoped it would be because of the old react native version 0.38 it is, but i don't think this is the case after your comment jslz.
We tried different build tool versions and target/compile versions. The issue still remains the same.

**Comment by MateRyze** [comment] 2018-05-17 18:18
I have a similar problem with PERMISSIONS.ACCESS_FINE_LOCATION: the dialog doesn't appear and the promise is also not resolved. 
react-native version: 0.55.4

**Comment by jslz** [comment] 2018-05-17 18:27
@MateRyze as an aside & by the by, apparently some Android permissions are not considered "dangerous" and so I guess those ones do not put up an extra dialog box from Android OS itself? 

https://stackoverflow.com/questions/34808769/android-6-0-what-is-the-difference-between-dangerous-and-special-permissions

(That's separate from the promise-never-resolving issue.)

**Comment by rcidt** [comment] 2018-05-24 19:31
@jgfidelis Are you using `react-native-navigation`?

I have the same issue you have, and I think it is because the `onRequestPermissionsResult` method in the `MainActivity` never get's called due to `NavigationActivity`.

**Comment by jslz** [comment] 2018-05-24 19:37
@rcidt, yes fwiw we are using wix rnn.

**Comment by rcidt** [comment] 2018-05-24 19:46
@jslz I am 99% sure that is the reason the promise never resolves. I am opening a ticket with them, maybe they can help.

**Comment by rcidt** [comment] 2018-05-24 19:55
I found this PR https://github.com/wix/react-native-navigation/pull/470 there are some important details at the end of the thread

**Comment by MateRyze** [comment] 2018-05-24 20:03
@jslz but the location permission is dangerous. Moreover it doesn't resolve :(

**Comment by jslz** [comment] 2018-05-24 20:10
@MateRyze oh dang. Thanks for pointing that out.

**Comment by SchmidmajerReka** [comment] 2018-05-24 20:56
We have the "not resolving" issue in a project without any navigation
library.

jslz <notifications@github.com> ezt írta (időpont: 2018. máj. 24., Cs
22:12):

**Comment by jgfidelis** [comment] 2018-05-25 13:40
@rcidt No, we do not use `react-native-navigation` on the app we have this issue.

**Comment by rcorrie** [comment] 2018-05-25 17:30
I am seeing this happen 90% of the time. A few times the promise actually resolves, but that's like 10% of the time.

This issue is making our android app basically unusable :(

**Comment by rcorrie** [comment] 2018-05-29 12:19
Updated RN to 0.55 and I have no more issues with PermissionsAndroid

**Comment by meylor** [comment] 2018-06-11 18:07
Confirmed, upgrading to the following versions fixes the issue:
```
    "react": "16.4.0",
    "react-native": "0.55.4",
```

**Comment by meylor** [comment] 2018-06-11 20:31
@MateRyze before you installed:
```
"react": "16.4.0",
"react-native": "0.55.4",
```
did you also do a `rm -rf ./node_modules package-lock.json`?

The only difference might be that I'm using the "promise/then" syntax in lieu of "async/await", ex:
```
    requestAndroidPermissions() {
        if (Platform.OS === 'android') {
            var permissions = [
                PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
                PermissionsAndroid.PERMISSIONS.ACCESS_COARSE_LOCATION
            ];

            try {
                PermissionsAndroid.requestMultiple(permissions).then(granted => {
                    // Object.entries(granted).map(([key, value]) => {
                    // });
                    this.nextAction();
                });
            } catch (err) {
                console.warn(err);
            }
        } else if (Platform.OS === 'ios') {
            this.nextAction();
        }
    }
```
which _shouldn't_ matter, but perhaps it does.

**Comment by meylor** [comment] 2018-06-11 22:53
@MateRyze also using 
```
PermissionsAndroid.requestMultiple()
```

**Comment by jgfidelis** [comment] 2018-06-12 15:37
@MateRyze this is a long shot, but can you try changing your code to use `then` rather then awai/async just to see if the bug still happens? I don't think it will make any difference, but lets try anything...

**Comment by jgfidelis** [comment] 2018-06-26 20:32
We fixed it by requesting the permission on app startup.

**Comment by Asleepace** [comment] 2018-08-22 03:39
I just wrapped it in another promise, seems to work well for me.
```javascript
getPermissions() {
  return new Promise(async(resolve, reject) => {
    const permissions = await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE);
    if (permissions === PermissionsAndroid.RESULTS.GRANTED) resolve(true);
    else reject(false);
  });
}
```

**Comment by kanekotic** [comment] 2018-08-22 10:14
@Asleepace so `PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE)` works because the `rationale` is `undefined`. 
What happens if you pass `rationale` as the second parameters?

**Comment by Asleepace** [comment] 2018-08-22 19:35
@kanekotic still works with the rationale as well
```javascript
    getPermissions() {
      return new Promise(async(resolve) => {
        const permissions = await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE,{
          'title': __('Local Storage Permissions'),
        'message': __('Needed for uploading files with the share extension.')
        });
        if (permissions === PermissionsAndroid.RESULTS.GRANTED) resolve(true);
        else resolve(false);
      });
    }
```

**Comment by luisfuertes** [comment] 2018-09-10 08:40
This code: 

```
import React, { PureComponent } from 'react'
import { View, Text, Image, Platform, TouchableOpacity, PermissionsAndroid } from 'react-native'
import styles from './styles'
import i18n from '../../../../assets/i18n/'

export default class extends PureComponent {
  componentDidMount() {
    this.checkLocationPermissions()
  }

  async checkLocationPermissions() {
    try {
      const granted = await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION, {
        title: i18n.t('locationRequest.title'),
        message: i18n.t('locationRequest.message')
      })
      console.log('checkLocationPermissions granted: ', granted)
      if (granted === PermissionsAndroid.RESULTS.GRANTED) {
        console.log('checkLocationPermissions granted ')
      } else {
        console.log('checkLocationPermissions denied')
      }
    } catch (err) {
      console.log('checkLocationPermissions err: ', err)
    }
  }

  render() {
    return <View style={{ flex: 1, backgroundColor: 'blue' }} />
  }
}
```

With:
```
    "react": "16.4.1",
    "react-native": "0.56.0",
```

In Xiaomi Mi Mix 2 (Android 8 with MIUI) and Motorola Moto G (Android 6): 
![captura de pantalla 2018-09-10 a las 10 38 43](https://user-images.githubusercontent.com/18212615/45286298-bca15400-b4e5-11e8-8f74-f94e6d0d6bd8.png)
 (granted == 'never_ask_again')

**Comment by thamarai199** [comment] 2018-10-09 07:29
still the issue persists. I'm using RN v0.53. Any workaround, as I don't want to upgrade my RN version

**Comment by RajShahitechnotion** [comment] 2018-11-26 11:02
anyone can tell me how to use permissionandroid in reactantive webview ?

**Comment by sfuqua** [comment] 2019-01-04 21:56
In our case this was happening because our main activity does not extend `ReactActivity`. 

ReactActivity has some glue that handles notifying React Native that a permissions request is finished via `PermissionListener`. We had to roll this ourselves - when React calls `requestPermissions` on the activity, save off the provided `PermissionListener`, and then later call `listener.onRequestPermissionsResult` when your activity's `onRequestPermissionsResult` is invoked.

**Comment by Hamzehn** [comment] 2019-02-05 22:09
I am running into this problem with PermissionsAndroid.requestMultiple() when permissions are not already granted. If permissions are not already granted when requestMultiple() is called and the dialog has to be shown to the user, the promise never gets fulfilled.

**Comment by moahmed123** [comment] 2019-02-17 19:48
_requestLocationPermission(){ 
return new Promise(async() => {
            const permissions = await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION);
            if (permissions === PermissionsAndroid.RESULTS.GRANTED){
               alert('access true');
            }
            else{
                alert('access false');
            }
        });
}

**Comment by mateuspiresl** [comment] 2019-03-01 17:02
Happening on RN 0.58.3.

**Comment by ferrannp** [comment] 2019-03-19 14:47
Hello there 👋 this issue has been reported for an old version of React Native. Ideally we'd like everyone to be using 0.59 (see the [awesome changes](https://facebook.github.io/react-native/blog/2019/03/12/releasing-react-native-059) it brought) but we know updating can be a pain. We are going to close this issue because it's from a version before 0.57, which is really old.

But please, if it's actually still an issue with 0.59 please comment below and we can reopen it 😊

**Closed by ferrannp** 2019-03-19 14:47 UTC
Labels: Resolution: Old Version, Type: Bug Report

**Comment by antt001** [comment] 2019-04-21 11:34
still does not resolves using 0.59 (the same behavior as in 0.57)

**Comment by 777uday** [comment] 2019-06-13 13:03
Any way to provide rationale to .multipleRequest()?. I want to give the user more insight into why I need the permission for respective request. In short, Customized title and message with multiple requests.

**Comment by luisaverza** [comment] 2019-09-25 15:17
#### I'm using:
```
"react": "16.8.3",
"react-native": "0.59.9",
```

#### Relevant snippet:
```
  const askCameraPermission = async () => {
    try {
      const granted = await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.CAMERA);
      console.log(granted)
    } catch {
      (e) => console.log(e)
    };
  };
```

#### App info's permissions `after -> before` run method
`pending -> granted` **BUT** promise is not resolved, console.log doesn't show. 👎 
`granted -> don't ask for permission` because is already granted **AND** promise is resolved, console.log show 'granted' 👍

**Comment by NayakShreyas** [comment] 2019-12-13 00:39
Issue still persists in RN .60

**Comment by BoatingZeng** [comment] 2019-12-20 08:12
> I have upgraded my project from 0.57 to 0.61 . But the issue still exists. However if I try to create a new project with react-native 0.61 this issue is not there. I am stuck here. Please some one help me

Maybe you Override `onRequestPermissionsResult` in `MainActivity extends ReactActivity` but forget to call `super.onRequestPermissionsResult`.
