### ISSUE TITLE
Android TextInput font family incorrect after switching `secureTextEntry`

### ISSUE THREAD

**Issue by timomeara** [facebook/react-native#30123] opened 2020-10-07 16:17 UTC
This appears to be an old issue, but i'm seeing it now in 0.63.3
it's not occurring in IOS

#6149, #5710

## Description
When  secureTextEntry={true} for TextInput, the font-family for placeholder is ignored:

## React Native version:
System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 596.29 MB / 32.00 GB
    Shell: 5.8 - /usr/local/bin/zsh
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /Users/timo/.rvm/rubies/ruby-2.4.1/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 23.0.2, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.2, 28.0.3, 29.0.2
      System Images: a...google_apis | Google APIs Intel x86 Atom Sys..., a...-23 | Intel x86 Atom, a... | Intel x86 Atom_64, a...google_apis | Google APIs Intel x86 Atom Sys..., a...gle_apis | Google APIs Intel x86 Atom_64 ..., a...google_apis | Google APIs Intel x86 Atom Sys..., a...google_apis | Google APIs Intel x86 Atom Sys..., a...s_playstore | Google Play Intel x86 Atom Sys..., a...google_apis | Google APIs Intel x86 Atom Sys..., a...gle_apis | Google APIs Intel x86 Atom_64 ..., a...s_playstore | Google Play Intel x86 Atom Sys...
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  Languages:
    Python: 3.8.5 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
```
<TextInput
  id={'email'}
  placeholder={'Email'}
  secureTextEntry={false}
  style={{fontFamily: 'Helvetica', fontSize: 14, fontWeight: '400' }}
/>

<TextInput
  id={'password'}
  placeholder={'Password'}
  secureTextEntry={true}
  style={{fontFamily: 'Helvetica', fontSize: 14, fontWeight: '400' }}
/>


```

## Expected Results
i expect the style rules to be applied

## Snack, code example, screenshot, or link to a repository:
![Screen Shot 2020-10-07 at 11 13 42 AM](https://user-images.githubusercontent.com/5084668/95358018-32777580-088e-11eb-9e8a-fa80a988d849.jpg)

**Comment by chrislarson** [comment] 2020-10-08 22:25
I'm also facing this issue after upgrading from 0.62.2 to 0.63.3

**Comment by emilsbee** [comment] 2020-10-09 07:20
Having the same issue after upgrading, any progress resolving this?

**Comment by Harikasai999** [comment] 2020-10-09 12:47
I'm also facing same issue in **"react-native": "0.63.3"**.

**Comment by timomeara** [comment] 2020-10-09 14:50
i'sorry to hear you'all are having the same issue, but glad to know i'm not crazy or doing something silly.

i ended up doing something like this:
[https://stackoverflow.com/questions/2711858/is-it-possible-to-set-a-custom-font-for-entire-of-application/16883281#16883281](url)

this overrides one of the system fonts so that when RN fails to render the font in the style, the system font it does render is actually the same font.
not a great solution but it fixed it for now

**Comment by hank121314** [comment] 2020-10-13 03:53
Hi @timomeara .
I have made a pr to fix this issue!
Can you help me to test whether it works? Thanks!

**Comment by AndreasA** [comment] 2020-10-13 04:34
I have the same issue regarding font family with placeholders. It also is an issue (for me) if I change secure text entry with  `onFocus` and `onBlur` (and remove and add the placeholder text).
`onBlur` results in the wrong font again without some tricks regarding style property but I hope your PR fixes that too.

**Comment by emilsbee** [comment] 2020-10-13 06:07
Unfortunately, the original problem still persists for me.

**Comment by hank121314** [comment] 2020-10-13 06:09
> Unfortunately, the original problem still persists for me.

Do you try with [Building from source](https://github.com/facebook/react-native/wiki/Building-from-source)?

**Comment by AndreasA** [comment] 2020-10-13 16:51
I  mentioned this in the PR. I can't be 100% certain though but:

> I am using expo SDK 39.0.2 and I also encounter the font family issue with password fields but from the code your fix should not help. Interestingly, in the emulator it works fine but once it is on a real device it fails to correctly style the placeholder.

> in that version setInputType looks like this:

```java

  @Override
  public void setInputType(int type) {
    Typeface tf = super.getTypeface();
    super.setInputType(type);
    mStagedInputType = type;
    // Input type password defaults to monospace font, so we need to re-apply the font
    super.setTypeface(tf);

    /**
     * If set forces multiline on input, because of a restriction on Android source that enables
     * multiline only for inputs of type Text and Multiline on method {@link
     * android.widget.TextView#isMultilineInputType(int)}} Source: {@Link <a
     * href='https://android.googlesource.com/platform/frameworks/base/+/jb-release/core/java/android/widget/TextView.java'>TextView.java</a>}
     */
    if (isMultiline()) {
      setSingleLine(false);
    }

    // We override the KeyListener so that all keys on the soft input keyboard as well as hardware
    // keyboards work. Some KeyListeners like DigitsKeyListener will display the keyboard but not
    // accept all input from it
    mKeyListener.setInputType(type);
    setKeyListener(mKeyListener);
  }
```

**Comment by hank121314** [comment] 2020-10-14 01:55
Hi @AndreasA !
expo SDK 39.0.2(with react-native 0.63.2) should not have this issue.
I think your issue might be a different issue 😞 .
I have tested on my real device and did not get that issue.
So this might be a bug on specific device?

**Comment by AndreasA** [comment] 2020-10-14 05:28
My teammates and I tested it on two Android 10 devices.
We created a separate `TextInputField` component that does the styling and adds a field label und such stuff but mostly styling. 

It is a functional component which does not do use any `useEffect`, `useState` stuff. It looks basically like this:
```
            <TextInput
                selectionColor={color}
                style={[inputStyle, styles]}
                placeholderTextColor={placeholderColor}
                darkColor={Colors.dark.textOnDark}
                lightColor={Colors.light.textOnDark}
                {...otherProps}
            />
```

We used that component multiple times in the same form. All fields have the correct placeholder styling, except the one with `secureTextEntry`.

and in the form we used it like this:
```
                    <TextInputField
                        label={'E-Mail address'}
                        placeholder={'E-Mail address'}
                        textContentType="emailAddress"
                        keyboardType="email-address"
                        autoCapitalize="none"
                        value={email}
                        onChangeText={(text): void => {
                            setEmail(text.trim());
                        }}
                    />
                    <TextInputField
                        label={'Password'}
                        placeholder={'Password'}
                        textContentType="newPassword"
                        secureTextEntry={true}
                        keyboardType={'default'}
                        autoCapitalize="none"
                        value={password}
                        onChangeText={(text): void => {
                            setPassword(text.trim());
                        }}
                    />
```

And in the `package.json` I have the following: 
`"react-native": "https://github.com/expo/react-native/archive/sdk-39.0.2.tar.gz",`

And as mentioned it happend on two devices so I doubt it is device specific.

**Comment by AndreasA** [comment] 2020-10-14 06:52
Adding the following to the  `TextInputField` component I mentioned above fixes the issue:
```
    const [reapplyInputFontFamilyStyle, setReapplyInputFontFamilyStyle] = React.useState<TextStyle | null>(null);
    React.useEffect(() => {
        setReapplyInputFontFamilyStyle(styles.inputFontFamily);

        /*
         * Re-applying styles in setTimeout for updates to the secure text entry flag,
         * as otherwise the style might be wrong afterwards. Not necessary if only changing the flag on component mount.
         */
        setTimeout(() => {
            setReapplyInputFontFamilyStyle(null);
            setReapplyInputFontFamilyStyle(styles.inputFontFamily);
        }, 0);
    }, [secureTextEntry]);
```

**Comment by timomeara** [comment] 2020-10-14 14:32
> Hi @timomeara .
> I have made a pr to fix this issue!
> Can you help me to test whether it works? Thanks!

wow, that was quick.
unfortunately, my clients schedule is really aggressive and doesn't leave me much time to circle back on things
hopefully some of the others here can test for you

**Comment by helder9991** [comment] 2020-10-17 20:29
I fixed this setting font family by ref in TextInput using useEffect and useRef.

So, i think is better create a your Input component with this code to get easier to use.

![Screenshot from 2020-10-17 17-04-21](https://user-images.githubusercontent.com/50815185/96352615-e05aff00-109a-11eb-9f51-0daac9876173.png)

**Comment by hoangnv98** [comment] 2020-10-27 10:37
> I fixed this setting font family by ref in TextInput using useEffect and useRef.
> 
> So, i think is better create your Input component with this code to get easier to use.
> 
> ![Screenshot from 2020-10-17 17-04-21](https://user-images.githubusercontent.com/50815185/96352615-e05aff00-109a-11eb-9f51-0daac9876173.png)

setNativeprops isn't function

**Comment by helder9991** [comment] 2020-10-29 00:54
> setNativeprops isn't function

Did you put inputElementRef inside ref props in TextInput ?  Or do you wrote 'setNativeprops' instead of 'setNativeProps' with P in lowercase?

**Comment by DracotMolver** [comment] 2020-10-30 14:51
I'm facing the same issue. I'd be ideal not to add extra code to something that should work natively :/

**Comment by abhilashdhone** [comment] 2020-11-04 11:08
> I fixed this setting font family by ref in TextInput using useEffect and useRef.
> 
> So, i think is better create your Input component with this code to get easier to use.
> 
> ![Screenshot from 2020-10-17 17-04-21](https://user-images.githubusercontent.com/50815185/96352615-e05aff00-109a-11eb-9f51-0daac9876173.png)

I am trying this in a class component and its not working, it says "this.ref_12.current.setNativeProps" is null

**Comment by thgh** [comment] 2020-11-04 14:40
@DracotMolver Thanks, just what I needed! I had a password field that rendered conditionally and used this:

```ts
function Example () {
  const passwordInput = useRef<TextInput>(null)
  useEffect(() => {
    passwordInput.current?.setNativeProps({ style: theme.input })
  }, [condition])
  return condition ? ... : <TextInput styles={theme.input} secureTextEntry ref={passwordInput} />
}
```

**Closed** 2020-11-06 20:26 UTC
Labels: Component: Switch, Component: TextInput, Needs: Triage :mag:, Platform: Android

**Comment by serp1412** [comment] 2020-11-25 15:08
If you see a crash on iOS here's how I fixed it.
```
useEffect(() => {
      ref.current.setNativeProps({
        style: { fontFamily: Platform.OS === "android" ? "roboto-regular" : undefined }
      });
  }, []);
```

**Comment by mostafero** [comment] 2020-11-25 20:10
Had same issue too (RN 0.63.3), In a class based component, and fortunately, I fixed it by applying the font of the ```ref``` in **componentDidMount** using **setNativeProps** as @helder9991 mentioned.
(note: in my case am creating a component  based on TextInput)

```javascript
export default class CustomTextInput extends Component {

    inputRef: any;

    componentDidMount() {
        **this.inputRef.setNativeProps({
            style: {
                fontFamily: APP_FONT,
            },
        });**
    }
    render() {

        return (
            <TextInput
                **ref={(ref) => (this.inputRef = ref)}**
                selectionColor={PRI_COLOR_OP1}
                placeholderTextColor={PRI_COLOR_OP1}
                value={value}
                placeholder={placeHolder}
                onChangeText={(text) => this.onTxtChange(text)}
                autoCapitalize={'none'}
                autoCorrect={false}
                autoFocus={false}
                textAlignVertical={'center'}
                {...props}
            />
        );
    }
```

**Comment by AhmadMazaal** [comment] 2020-11-30 08:57
@mostafero Thank you! your solution works for me

**Comment by cliid** [comment] 2020-12-09 00:21
Setting `fontWeight` to `normal` worked for me.

**Comment by luisfuertes** [comment] 2021-03-02 12:28
If you add button to change secureTextEntry to true/false a few ms after change state, input appear with incorrect font xd
```
  const inputRef = React.useRef(null)
  const [showPassword, setShowPassword] = React.useState(false)

  React.useEffect(() => {
    inputRef.current.setNativeProps({
      style: { fontFamily: Platform.OS === 'android' ? 'roboto-regular' : undefined },
    })
  }, [showPassword])
```

**Comment by JavierLaguna** [comment] 2021-03-04 09:41
Works fine for me with 0.63.4 version

**Comment by intitec** [comment] 2021-03-06 03:16
Hey guys,

Seems to be a bug.

I resolved that bug based on previous comments.

`
    ...

    const ref = useRef(null)
    const [ secured, setSecured ] = useState<boolean>(true)

    ...

    useEffect(() => {
        ref.current.setNativeProps({
            style: {
                fontFamily: 'SofiaProLight'
            }
        })
    }, [ secured ])

    ...


    return (
        <Input
            ref={(_ref:any) => {
                ref.current = _ref;
            }}

    ...

`

**Comment by ivan-khr85** [comment] 2021-03-19 09:04
Bug reproduced with v0.64.0...

**Comment by Bardiamist** [comment] 2021-03-19 09:59
I can confirm that bug is back in v0.64.0

**Comment by kelset** [comment] 2021-03-19 11:57
yeah looks like the commit with the fix landed on master after the 0.64 branch was cut so it's not there - I've added a reference to the commit in the 0.64.1 issue, thanks folks for reporting 👍

**Comment by everthon-carniel** [comment] 2021-04-07 18:33
The problem continues to happen in React Native 0.64. It's not necessary to use useRef or useEffect to change the fontFamily. You can do this directly in the component reference. As below:

`
<TextInput ref={ref => ref && ref.setNativeProps({ style: { fontFamily: 'FONT_NAME' } })} />
`

**Comment by usmansbk** [comment] 2021-04-10 10:12
`fontWeight: 'normal'` worked for me

**Comment by goraug** [comment] 2021-04-10 22:16
@everthon-carniel Thanks a lot, you saved my time, it works!

**Comment by ncesar** [comment] 2021-04-15 02:57
> The problem continues to happen in React Native 0.64. It's not necessary to use useRef or useEffect to change the fontFamily. You can do this directly in the component reference. As below:
> 
> `<TextInput ref={ref => ref && ref.setNativeProps({ style: { fontFamily: 'FONT_NAME' } })} />`

the real answer!! thanks

**Comment by melero2000** [comment] 2021-04-17 15:40
> The problem continues to happen in React Native 0.64. It's not necessary to use useRef or useEffect to change the fontFamily. You can do this directly in the component reference. As below:
> 
> `<TextInput ref={ref => ref && ref.setNativeProps({ style: { fontFamily: 'FONT_NAME' } })} />`

It seems to work, the font does not change it and it is a good sign, but it does not write anything
![input](https://user-images.githubusercontent.com/45013053/115118517-d9f30480-9fa3-11eb-8d6b-8f3e8aa5adcd.gif)

My code: 
`<TextInput
        ref={ref =>
          ref && ref.setNativeProps({style: {fontFamily: 'Krub-Medium'}})
        }
        style={styles.input}
        placeholder="Introduce tu contraseña"
        placeholderTextColor="grey"
        secureTextEntry={showPassword}
      />`

**Comment by goraug** [comment] 2021-04-21 11:09
@melero2000 check if you provide a `value` property to your input and `onChangeText` one as well

**Comment by YoucefAcheuk** [comment] 2021-04-24 12:57
> The problem continues to happen in React Native 0.64. It's not necessary to use useRef or useEffect to change the fontFamily. You can do this directly in the component reference. As below:
> 
> `<TextInput ref={ref => ref && ref.setNativeProps({ style: { fontFamily: 'FONT_NAME' } })} />`

Helped me a lot, thanks :)

**Comment by QuetzalTiago** [comment] 2021-05-12 15:27
> The problem continues to happen in React Native 0.64. It's not necessary to use useRef or useEffect to change the fontFamily. You can do this directly in the component reference. As below:
> 
> `<TextInput ref={ref => ref && ref.setNativeProps({ style: { fontFamily: 'FONT_NAME' } })} />`
THANK YOU! THIS IS THE WAY!

**Comment by QuetzalTiago** [comment] 2021-05-12 15:28
> The problem continues to happen in React Native 0.64. It's not necessary to use useRef or useEffect to change the fontFamily. You can do this directly in the component reference. As below:
> 
> `<TextInput ref={ref => ref && ref.setNativeProps({ style: { fontFamily: 'FONT_NAME' } })} />`

This works, thank you, i was about to go crazy lol

**Comment by sanduluca** [comment] 2021-05-13 09:34
Bug reproduced with v0.64.1
```
$ npm list react-native
App@2.0.0 C:\Projects\mercado-app
`-- react-native@0.64.1
```

**Comment by dawidchyrzynski** [comment] 2021-05-24 20:45
Hi guys,

I'm getting the same result as @melero2000. Any idea how to fix this?

**Comment by helder9991** [comment] 2021-05-24 21:41
> Hi guys,
> 
> I'm getting the same result as @melero2000 with RN 0.64.1. Any idea how to fix this?

The function 'setNativeProps' is overwriting the property 'text' to empty string. You can see this setting:
``` setNativeProps({ text: "some text" } )```

You can fix this problem using 'useState' from react library.

```
import React, { useState } from 'react';
import { TextInput } from 'react-native';

export default function App() {
  const [inputValue, setInputValue] = useState('');
  return (
    <TextInput 
      placeholder="some text" 
      value={inputValue}
      onChangeText={(text) => setInputValue(text)} 
      ref={ref => ref && ref.setNativeProps({ style: { fontFamily: 'sans-serif' } })}
      />
  ); 
}
```

**Comment by appasaheb4** [comment] 2021-05-28 07:43
customs font adding after text not center showing any idea?

**Comment by JainBhavesh** [comment] 2021-06-01 10:37
> > The problem continues to happen in React Native 0.64. It's not necessary to use useRef or useEffect to change the fontFamily. You can do this directly in the component reference. As below:
> > `<TextInput ref={ref => ref && ref.setNativeProps({ style: { fontFamily: 'FONT_NAME' } })} />`
> 
> It seems to work, the font does not change it and it is a good sign, but it does not write anything
> ![input](https://user-images.githubusercontent.com/45013053/115118517-d9f30480-9fa3-11eb-8d6b-8f3e8aa5adcd.gif)
> 
> My code:
> `<TextInput ref={ref => ref && ref.setNativeProps({style: {fontFamily: 'Krub-Medium'}}) } style={styles.input} placeholder="Introduce tu contraseña" placeholderTextColor="grey" secureTextEntry={showPassword} />`

please add value prop issue will solve

**Comment by hodangnamtien** [comment] 2021-06-29 17:06
<TextInput ref={ref => ref && ref.setNativeProps({ style: { fontFamily: 'FONT_NAME' } })} /> working  v0.64.1

**Comment by leolusoli** [comment] 2021-07-07 15:27
This is Issue isn't closed and not resolved in 0.64.2 so please re-open it!

**Comment by rbary** [comment] 2021-07-22 07:37
Still have the bug in 0.63.3.... and @everthon-carniel fix works.

**Comment by prakashkrsingh0** [comment] 2021-08-19 09:22
> The problem continues to happen in React Native 0.64. It's not necessary to use useRef or useEffect to change the fontFamily. You can do this directly in the component reference. As below:
> 
> `<TextInput ref={ref => ref && ref.setNativeProps({ style: { fontFamily: 'FONT_NAME' } })} />`

thank you so much .. this resolves my problem also.

**Comment by adityamohta** [comment] 2021-09-11 06:06
###  This is working perfectly for me: 
 
 The refs can be both defined or undefined when the component is being mounted.

Add the following to your component:
```javascript
  const _inputRef = useRef(null);
  const setRef = useCallback((node) => {
    if (_inputRef.current) {
      // Make sure to cleanup any events/references added to the last instance
    }
    if (node) {
      // Check if a node is actually passed. Otherwise node would be null.
      // You can now do what you need to, setNativeProps, addEventListeners, measure, etc.
      // Important Tip: you can also hide (not unmount) the component till this part
      node.setNativeProps({
        style: { fontFamily: "Quicksand-Medium" },
      });
    }
    // Save a reference to the node
    _inputRef.current = node;
  }, []);
```
Make sure your TextInput has this ref assigned:
```javascript
    <TextInput ref={setRef} ... />
```
