### ISSUE TITLE
TextInput blinking cursor color is not correct when using selectionColor. not able to change cursor color while using any of given props

### ISSUE THREAD

**Issue by thakurdivendra** [facebook/react-native#29627] opened 2020-08-12 14:01 UTC
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Not able to change blinking text input cursor color using any of given props or with style

## React Native version:
System:
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz

Binaries:
    Node: 10.19.0 - /usr/bin/node
    Yarn: Not Found
    npm: 6.14.4 - /usr/bin/npm
    Watchman: Not Found

  SDKs:
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.0
  
 
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
  npmPackages:
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 

## Steps To Reproduce
<TextInput 
    style={{color:'#fff'}}
    selectionColor='red'
    />

## Expected Results
expected to be cursor color white

**Comment by riadhriadh** [comment] 2020-08-12 14:40
#22762

**Comment by chrisglein** [comment] 2020-08-12 17:24
Yep, looks like a duplicate of #22762

**Closed by chrisglein** 2020-08-12 17:24 UTC
Labels: API: Linking, Component: TextInput, Needs: Triage :mag:, Platform: Linux

**Comment by chrisglein** [comment] 2020-08-12 17:34
[Maybe fixed in 63?](https://github.com/facebook/react-native/issues/22762#issuecomment-622235721)

Also [created a Snack](https://snack.expo.io/@chrisglein/repro29627). Text color and selection color seem to work on Android in this Snack.
