### ISSUE TITLE
[ListView] Extra space at the top.

### ISSUE THREAD

**Issue by clanofnoobs** [facebook/react-native#721] opened 2015-04-07 16:15 UTC
I don't know if this is a styling issue, but there is some extra space (they're not rows because they're not selectable) at the top of the ListView. Is there any workaround this? And was this issue fixed within the last week?

![screen shot 2015-04-07 at 12 09 52 pm](https://cloud.githubusercontent.com/assets/6325187/7027771/7aba2aea-dd1f-11e4-8676-f7ab14d618cc.png)

**Comment by frantic** [comment] 2015-04-07 18:52
I guess `automaticallyAdjustContentInsets` strikes again. Try

```jsx
<ListView automaticallyAdjustContentInsets={false} ... />
```

**Comment by clanofnoobs** [comment] 2015-04-09 18:06
That worked, thanks a bunch!

**Comment by LeezQ** [comment] 2015-04-10 03:00
I have the same problem, mark this.

**Comment by umhan35** [comment] 2015-05-01 04:42
Is this a bug or not?

**Comment by joewood** [comment] 2015-05-05 02:55
Is `automaticallyAdjustContentInsets` documented anywhere? Why it's necessary etc...

**Comment by rxb** [comment] 2015-05-13 18:35
Seems like automaticallyAdjustContentInsets compensates for statusBarIOS and tabBarIOS (so that things can scroll properly and not be blocked by those fixed items) but it gets complicated if the scrollview isn't the first or last component.

**Comment by jedt** [comment] 2015-05-22 15:29
I was able to replicate this whenever I have a ScrollView (or ListView) with TabBarIOS at the bottom. If I put automaticallyAdjustContentInsets={false} the extra space at the top disappears but the scrollview doesn't scroll up all the way hiding the bottom contents of the ScrollView below the TabBarIOS

**Comment by ide** [comment] 2015-05-22 19:26
@jedt, give the scroll view a contentInset of {bottom:49} or however tall your tab bar is, and the scrolling behavior should be fixed.

**Comment by jedt** [comment] 2015-05-22 23:36
Thanks @ide! it works perfectly :)

here is the code:
```
<ScrollView
  contentInset={{bottom:49}}
  automaticallyAdjustContentInsets={false}
>
```

**Comment by joeyyang** [comment] 2015-06-22 00:01
Has the team considered making `automaticallyAdjustContentInsets={false}` the default behavior of this component?

**Comment by brentvatne** [comment] 2015-06-23 23:56
@frantic - curious what you think about @joeyyang's suggestion above

**Comment by wub** [comment] 2015-07-05 01:41
@jedt @ide Also, if you *still* can't see everything after doing that, make sure the container has `flex: 1` - I forgot to do that I couldn't scroll more than (64 + 49)px!

**Comment by admmasters** [comment] 2015-07-13 13:52
FWIW - you lose the translucency when scrolling content under the navigation bar - which makes sense when you think of how automaticallyAdjustContentInsets works.

**Comment by broonage** [comment] 2015-08-03 14:13
This should definitely be explained in the ListView docs at least. I.e. If using a tab bar with a list view etc...

**Comment by RWOverdijk** [comment] 2015-08-14 15:25
:+1: for the answer in this issue. :-1: for this being magic to users.

**Comment by christopherdro** [comment] 2015-09-13 23:22
Related: #1779 #2151 

@brentvatne @ide

**Closed** 2015-09-14 00:04 UTC

**Comment by peridotlib15** [comment] 2016-07-14 08:48
I have a horizontal scroll view and getting extra bottom space.
I changed height in style and contentContainerStyle but not work
Anybody experienced same thing?

**Comment by hustshawn** [comment] 2016-11-04 02:52
The feature is good enough and somewhat necessary in most of the cases that ListView just placed under the Navigator, but the problem is the lack of documentation [here](https://facebook.github.io/react-native/docs/listview.html) .

**Comment by Skylonatron** [comment] 2017-11-14 06:39
Thanks so much i was messing with this for way too long
