### ISSUE TITLE
I used version not the node_modules android version

### ISSUE THREAD

**Issue by a1018875550** [facebook/react-native#19288] opened 2018-05-16 09:42 UTC
in the external libraries list show my react-native version is "0.55.3", but I didn't do any update react-native action, and my node_modules /react-native/android only have '0.42.3' folder

![image](https://user-images.githubusercontent.com/8246218/40109635-618a1be4-5930-11e8-86d7-c8fcfe7711a5.png)

![image](https://user-images.githubusercontent.com/8246218/40109611-5408e5e0-5930-11e8-9c2c-ff9cc27d7676.png)

**Comment by kelset** [comment] 2018-05-16 10:04
Closing as duplicate of #19259

**Closed by kelset** 2018-05-16 10:04 UTC
Labels: :clipboard:No Template, :large_blue_diamond:Android
