### ISSUE TITLE
Illegal node ID set as an input for Animated.DiffClamp node

### ISSUE THREAD

**Issue by arsenghazaryan** [facebook/react-native#12732] opened 2017-03-06 04:00 UTC
If I try to unmount the view it will throw an error "Illegal node ID set as an input for Animated.DiffClamp node".
Only if the view is controlled by the Animated value (nativeDriver = true). If I set nativeDriver=false then it is fine.

Same thing is hapening on RN 0.41, 0.42, 0.43.rc

Here is the code snippet:
```
  constructor(props) {
    super(props);

    this.state = {
      showHeader: true,
      scrollY: new Animated.Value(0)
    };
  }

  componentDidMount() {
    setTimeout(() => {
      this.setState({
        showHeader: false
      });
    }, 1000);
  }

  render() {
    const translateY = Animated.diffClamp(this.state.scrollY, 0, HEADER_HEIGHT);
    const headerStyles = [styles.header, { transform: [{ translateY }] }];

    const header = !this.state.showHeader ? null : (
      <Animated.View style={headerStyles}></Animated.View>
    );
    return (
      <View style={styles.container}>
        {header}
        <Animated.ScrollView
          scrollEventThrottle={1}
          onScroll={Animated.event(
            [{ nativeEvent: { contentOffset: { y: this.state.scrollY } } }],
            { useNativeDriver: true }
          )}>
          <Text>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
          </Text>
        </Animated.ScrollView>
      </View>
    );
  }
```

![simulator screen shot mar 5 2017 7 40 36 pm](https://cloud.githubusercontent.com/assets/3446647/23596036/adba9cbc-01db-11e7-8451-308851ab896d.png)

**Comment by nihgwu** [comment] 2017-03-06 04:08
#11317

**Comment by ericvicenti** [comment] 2017-03-06 06:31
Closing as dupe of #11317

**Closed by ericvicenti** 2017-03-06 06:31 UTC
