### ISSUE TITLE
[Image] If use a gif url, it will take more than 300m memory

### ISSUE THREAD

**Issue by soliury** [facebook/react-native#1968] opened 2015-07-13 03:07 UTC
I found the bug in the [noder](https://github.com/soliury/noder-react-native), if this is a bug ? 

Ps: the gif size is about 1.8M

**Comment by brentvatne** [comment] 2015-07-20 19:44
What is the memory usage on the app on the exact same screen without the gif? And with? (interested in the differential here).

**Comment by soliury** [comment] 2015-07-21 03:49
If without gif, it only takes about 130m. But used the gif it takes 300-400m

**Comment by brentvatne** [comment] 2015-07-22 03:58
I don't believe that anybody at Facebook is too concerned about gifs at the moment so this will need to be a community effort. Do you have any time to dig into this and try to find the cause @soliury? :smile:

**Comment by soliury** [comment] 2015-07-22 04:11
ok, I have a try.

**Comment by nicklockwood** [comment] 2015-07-28 10:38
It's not a bug, it's a limitation of the implementation:

Gif is a compressed format, and can't be displayed on screen directly without decompressing it. When we load a gif, we decompress all the frames and create a keyframe animation. That's why the memory consumption is so huge - every decompressed frame of the gif will take up width*height*4 bytes, regardless of it's compressed size, so if it has a lot of frames it will be huge.

What you really want here is something like a *streaming* gif implementation, where frames are only decompressed as they are about to be played, rather than all in advance.

Realistically though, that's a lot of work for us to implement, since it would mean replacing the Core Animation keyframes with our own animation system based on CADisplayLink.

If possible, you'd be better off using a video instead of a gif for a long animation like this.

**Comment by spicyj** [comment] 2015-08-03 00:51
Probably easiest to just use https://github.com/Flipboard/FLAnimatedImage (which Facebook uses in some of its apps).

**Comment by soliury** [comment] 2015-08-03 04:13
@nicklockwood @spicyj ok, I see. I'll have a try

**Comment by aleclarson** [comment] 2015-08-18 01:11
What's the status on this? I'd really like a performant GIF implementation. :grin:

**Comment by miduga** [comment] 2015-09-06 20:49
+1

**Comment by ide** [comment] 2015-09-06 21:38
There's a good chance that Facebook doesn't have a need for animated GIFs especially if they transcode to a movie format on the server. As @spicyj suggested, making a module that uses FLAnimatedImage is probably easiest and best if you need GIF support.

**Comment by cosmith** [comment] 2016-03-09 22:38
I think gifs work fine now. Trying the bot :wink:

**Comment by cosmith** [comment] 2016-03-09 22:38
@facebook-github-bot close

**Comment by nicklockwood** [comment] 2016-03-10 16:05
We've not changed the GIF implementation, so I doubt this situation has improved. Small GIFs work fine (as they always have), large GIFs will probably still cause an OOM.

**Comment by cosmith** [comment] 2016-03-11 09:27
@facebook-github-bot reopen

**Comment by oblador** [comment] 2016-03-11 13:45
@nicklockwood: Would you accept a PR using FLAnimatedImage?

**Comment by mkonicek** [comment] 2016-03-13 23:38
@oblador I don't think we want to add a dependency on https://github.com/Flipboard/FLAnimatedImage. Also all of the RN source code is published to npm and don't think we have any way to specify dependencies like we do on Android.

Can you release that as a separate RN module?

**Comment by oblador** [comment] 2016-03-14 00:04
@mkonicek: Yeah maybe it makes sense to release it as a community module and that's been my approach so far, only downside is that I'd have to do a semi-fragile extension sniff on url in JS instead of inspecting file headers and lots of code duplication from core. But performance is really several magnitudes better though, so it would still be nice to have something better in core since the current implementation is almost unusable for anything large or non-trivial. 

FLAnimatedImage dependency could be included via a submodule and then strip out anything but the good stuff via `npmignore`. But that's not ideal ofc and cocoapods I assume is not an option.

**Comment by nihgwu** [comment] 2016-07-07 13:01
any news about this? the force-close problem caused by large gif file is really frustrating me

**Comment by nihgwu** [comment] 2016-09-14 15:12
I've published a `FLAnimatedImage` wrapper to npm `https://github.com/nihgwu/react-native-flanimatedimage`
I've been using it in production for quite a long time.

**Comment by lacker** [comment] 2016-12-15 00:49
^ That seems like a good solution, if you need large gifs then FLAnimatedImage rather than adding this to the built-in image seems like the way to go. I'm going to close this issue, thanks everyone for helping out!

**Closed by lacker** 2016-12-15 00:49 UTC
Labels: Community Responsibility, Ran Commands
