### ISSUE TITLE
Button not responding as should.  handleStartPress() handles that functionality.

### ISSUE THREAD

**Issue by dennisobel** [facebook/react-native#13453] opened 2017-04-11 19:18 UTC
var formatTime = require('minutes-seconds-milliseconds');
import React, { Component } from 'react';
import { AppRegistry,
    Text ,
    StyleSheet,
    View,
    TouchableHighlight,
    } from 'react-native';

class AwesomeProject extends Component {

  constructor(props){
	super(props);
	this.state={timeElapsed:null, running: false};
	
	}  

  render() {
    return (
	
    <View style={styles.container}>
        <View style={[styles.header]}>
            <View style={[styles.timerWrapper]}>
                <Text style={styles.timer}>
                    {formatTime(this.state.timeElapsed)}
                </Text>
            </View>
            <View style={[styles.buttonWrapper]}>
                {this.startStopButton()}
                {this.lapButton()}
            </View>
        </View>
        <View style={[styles.footer]}>
            <Text>
                List of laps
            </Text>
        </View>
    </View>
	
    );
  }

  startStopButton(){
    return (
        <TouchableHighlight
        underlayColor="grey"
        onPress={()=>{this.handleStartPress()}}
	style =  {[styles.button, styles.startButton]}>
            <Text>
               Start
            </Text>
        </TouchableHighlight>
    );
  }

  lapButton(){
    return (
        <View style={styles.button}>
            <Text>
                Lap
            </Text>
        </View>
    );
  }

  handleStartPress(){

    if(this.state.running){
    	clearInterval(this.interval);
	this.setState({running: false});
    	return
	}

    var startTime = new Date();

    this.interval = setInterval(() => {
    this.setState({
        timeElapsed: new Date() - startTime,
	running: true
    });
  }, 30);
  }

  
  }

  var styles = StyleSheet.create({
    container : {
        flex: 1, //Fill the entire screen
        alignItems: 'stretch'
    },

    header:{//yellow
        flex: 1
    },

    footer:{//blue
        flex: 1
    },

    timerWrapper:{
        flex: 5,
        justifyContent: 'center',
        alignItems: 'center'
    },

    buttonWrapper:{
        flex: 3,
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center'
    },

    timer:{
	fontSize : 60
    },

    button:{
	borderWidth: 2,
	height: 80,
	width: 80,
	borderRadius: 50,
	justifyContent: 'center',
	alignItems: 'center'
    },

    startButton:{
	borderColor:'green'
    }
  });

AppRegistry.registerComponent('AwesomeProject', () => AwesomeProject);

**Comment by hramos** [comment] 2017-04-14 22:41
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-04-14 22:41 UTC
