### ISSUE TITLE
prepend AND append in ListView

### ISSUE THREAD

**Issue by jinqkim1** [facebook/react-native#10683] opened 2016-11-01 18:03 UTC
Hi, I've been working really hard to solve this problem for a long time now.

I've looked at StackOverflow AND other issues for a solution but I couldn't find a clear one.

I know that I can prepend WITH full re-render, but I don't know how I can prepend WITHOUT full re-render.

I think I can achieve this with non index key when I upload data into ListView, but I don't know exactly how  or where to assign non index key. (non-index meaning the keys ListView uses to compare old rows and new rows DO NOT depend on just the index of the array of datasource)

So these are my questions.

1. How do I assign non-index key?

2. If I DO succeed in assigning non-index keys, then would I be able to make BOTH prependable AND appendable ListView that DOES NOT re-render all rows in both cases?

3. If not, then how are you solving this problem?? Because this seems like a very common issue and I am very surprised that ListView does not have this functionality yet.

*Also, I've looked at PrependableListView on GitHub, but it seems like an exact copy of ListViewDataSource.. Am I missing something? If there is something that I missed in PrependableListView, then can somebody please point out where?

**Comment by Ehesp** [comment] 2016-11-01 22:17
When you say prepend, do you mean prepend a component to individual rows in the list view?

**Comment by jinqkim1** [comment] 2016-11-02 04:31
@Ehesp  hmm, so what I mean is that I sometimes need to add a row to the datasource array AT THE BEGINNING(unshift) of the array on RefreshControl(pull-to-refresh) and other times I need to add a row to the datasource array AT THE END(push).

To help understand my problem, below is the test code I'm using.

```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  ListView,
  RefreshControl,
  View
} from 'react-native';

export default class Test1 extends Component {
  constructor(props){
    super(props);
    const arr = [];
    this.state = {
          dataSource: new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2}),
          refreshing: false,
        };
  }

  componentWillMount(){
    this.arr = [];
    for(let i = 0; i < 16; i++){
        this.arr.push({keyy: i, data: "row " + i});
    }

    this.setState({
        dataSource: this.state.dataSource.cloneWithRows(this.arr),
    });
  }

  _onRefresh() {
    this.setState({refreshing: true});
    let i = this.arr.length;
    let arr1 = [];
    arr1.unshift({keyy: i, data: "row " + i});
    for(var index = 0; index < this.arr.length; index++){
        arr1.push(this.arr[index]);
    }
//    console.log(this.arr);
//    console.log("arr1  :  " + arr1.length);
    this.setState({
       dataSource: this.state.dataSource.cloneWithRows(arr1),
       refreshing: false,
    });
  }

  _renderRow(rowData: string, sectionID: number, rowID: number){
//    console.log(rowData.data + "   :   " + sectionID + "   :   " + rowID);
    return(
        <Text style={{fontSize: 50}}>{rowData.data}</Text>
    );
  }

  _onEndReached(){
    let i = this.arr.length;
    let arr1 = [];
    for(var index = 0; index < this.arr.length; index++){
        arr1.push(this.arr[index]);
    }
    arr1.push({keyy: i, data: "row " + i});

    this.setState({
        dataSource: this.state.dataSource.cloneWithRows(arr1),
    });
  }

  render() {
    return (
      <ListView
            dataSource={this.state.dataSource}
            renderRow={this._renderRow.bind(this)}
            refreshControl={
              <RefreshControl
                refreshing={this.state.refreshing}
                onRefresh={this._onRefresh.bind(this)}
              />
            }
            onEndReachedThreshold={0}
            onEndReached={this._onEndReached.bind(this)}
      />
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('Test1', () => Test1);
```

As you can see in the code, I'm 'unshifting' a row in _onRefresh function, and 'pushing' a row in _onEndReached function. Mind you that this WILL work, but with a full re-render on _onRefresh. What I need is ONLY re-rendering the row I'm unshifting or pushing.

**Comment by Ehesp** [comment] 2016-11-02 07:27
Whatever you do with setState will cause a full rerender. Is it because you're having performance issues? 

As the data blob is an array of objects, your row has changed checker will always return true at the moment. Try:

rowHasChanged: (r1, r2) => JSON.stringify(r1) !== JSON.stringify(r2)

On my phone at the moment, but the above should help.

**Comment by jinqkim1** [comment] 2016-11-02 10:22
@Ehesp  How would that help?

The problem here is when I compare two dataBlobs as below..
      old                     new
[0,1,2,3,4,5]        [6,0,1,2,3,4,5]

default checker in ListView.DataSource will assign keys (or RowIDs) as the indices of dataBlob array by default.  (newsource.rowIdentities.push(Object.keys(dataBlob[sectionID]))
Which means in the case shown above, new dataBlob will have [0,1,2,3,4,5,6] as keys, then compare newDataBlob[sectionID][0] with oldDataBlob[sectionID][0] --> 6 != 0  --> re-render
newDataBlob[sectionID][1] with oldDataBlob[sectionID][1] --> 0 != 1  --> re-render
newDataBlob[sectionID][2] with oldDataBlob[sectionID][2] --> 1 != 2  --> re-render
newDataBlob[sectionID][3] with oldDataBlob[sectionID][3] --> 2 != 3  --> re-render
newDataBlob[sectionID][4] with oldDataBlob[sectionID][4] --> 3 != 4  --> re-render
newDataBlob[sectionID][5] with oldDataBlob[sectionID][5] --> 4 != 5  --> re-render
newDataBlob[sectionID][6] with oldDataBlob[sectionID][6] --> oldDataBlob[sectionID][6] undefined  --> re-render

So my question was how to use non-index keys to prevent full re-render in BOTH append AND prepend cases. Please shed some light on the THREE questions I asked above.

Oh and thank you @Ehesp  for helping out, I've also tried your solution and it didn't work for me.

**Comment by hramos** [comment] 2017-03-31 18:35
Closing as ListView is deprecated in 0.43. Use FlatList.

**Closed by hramos** 2017-03-31 18:35 UTC

**Comment by jinqkim1** [comment] 2017-04-03 07:52
thank you. i will try flatlist.

**Comment by harshq** [comment] 2017-04-17 05:04
Hi @jinqkim1. Were you able to find a solution for this ?

**Comment by vnhnhm** [comment] 2017-04-17 13:45
Were you @harshq?

**Comment by m-vdb** [comment] 2017-05-11 01:22
don't think it's resolved at all with FlatList...

**Comment by Ashoat** [comment] 2017-05-27 01:23
I have gotten this sort-of working with `FlatList`. The hack I am using is a `scrollToOffset` call in `componentWillUpdate`. I calculate the height of the new items being added to the `FlatList`, and use that to calculate the new scroll position that corresponds to where the user previously was.

Unfortunately, there are a lot of quirks. The issue is that it's hard to time the call correctly. There's no way to set the offset via a prop, and consequently the change in list contents (which happens via a prop change) needs to be timed with the `scrollToOffset` call (which happens within `componentWillUpdate`).

Several possible fixes I could imagine:
1. If it were possible to update the offset of `ScrollView` via a prop, it would be easier to time with the list content change.
2. If `ScrollView` supported starting a list from a negative index, it would be possible to have negative indexes in `FlatList`, and thus avoid having to re-index the contents and recalculate the scroll position on a prepend event.
3. `FlatList` could have a mechanism to queue up a scroll position change that will occur the next time the list content changes. Something like `scrollToOffsetAtNextListDataChange` :)

If anybody is curious, the concrete timing issues are that:
1. On iOS, sometimes calling `scrollToOffset` immediately in `componentWillUpdate` isn't fast enough, and the intermediate frame (with the contents updated but the offset not) will be displayed to the user for a split-second.
2. On Android, for some reason I'm seeing an issue with just the very first prepend event, where calling `scrollToOffset` immediately in `componentWillUpdate` is too fast, and results in the scroll event starting to fire before the contents change, and then suddenly getting arrested once the contents change. I get around this by calling `scrollToOffset` in a `setTimeout(callback, 0)`.
