### ISSUE TITLE
Debug JS Remotely wait for clicking in IOS simulator.

### ISSUE THREAD

**Issue by lazyhoneyant** [facebook/react-native#14545] opened 2017-06-16 03:40 UTC
‘ Debug JS Remotely ‘ wait for clicking in IOSsimulator.

To debug I turned on the Debug JS Remotely.
After that, simulator wait for clicking on the response of HTTP request.
For example when request login to a server, server response immediately to the client, But iOS simulator wait for my clicking. After clicking anywhere on the screen, It goes next. It's like a breakpoint.

Android is OK, Real Device is OK 
It occurred Only in IOS Simulator.
Using React Developer Tools Instead of default, It works normally. 

Is this a bug ? or Am I Missing something?

React Native version : 0.45.1
Platform: iOS
Development OS: macOS
Simulator: Version 10.0
Xcode: 8.3.3

**Comment by dannycochran** [comment] 2017-06-16 04:40
Noticed this on my Android emulator as well, using RN 0.45.1

**Comment by hramos** [comment] 2017-06-16 20:19
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-16 20:19 UTC

**Comment by giulianok** [comment] 2017-07-16 00:51
Having the same problem here (I commented in https://github.com/facebook/react-native/issues/2603)

When I'm debugging with Chrome, for each request, I have to click on the app (simulator) to be able to make each request. Without debugging I works fine :(

**Comment by moalamin** [comment] 2017-07-26 20:50
I am having the same issue, here is my code:

Same here, "react-native": "0.46.4".

redditActions.js:
```
import thunk from 'redux-thunk';

export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_COMPLETE = 'FETCH_POSTS_COMPLETE';

export function fetchPosts(dispatch) {
  return (dispatch) => {
    window.fetch('https://www.reddit.com/.json')
    .then( resp => resp.json() )
    .then( data => {
      dispatch(fetchPostsComplete(data.data.children))
    })
  }
}

export function fetchPostsComplete (posts) {
    return {
      type: FETCH_POSTS_COMPLETE,
      payload: posts
    }
}
```

reducers.js:
```
import {FETCH_POSTS, FETCH_POSTS_COMPLETE} from './redditActions';

const initialState = { posts: [] }
export const redditReducer = (state=initialState, action) => {
  switch (action.type) {
    case FETCH_POSTS_COMPLETE: {
      const newState = Object.assign({}, state, {posts: action.payload})
      return newState;
    }
    default: {
      return state;
    }
  }
}
```

Reddit.js:
```
class Reddit extends Component {
  constructor(props) {
    super(props)
    console.log(this.props)
  }
  componentWillMount() {
    this.props.actions.fetchPosts()
  }
  render() {
    return (
      <View>
        <Text>Reddit</Text>
        {
          this.props.posts.map( post => <Text key={post.data.id}>{post.data.title}</Text>)
        }
      </View>
    )
  }
}

function mapStateToProps(state) {
  return {
    posts: state.posts
  }
}

function mapDispatchToProps(dispatch) {
  return { actions: bindActionCreators(redditActions, dispatch) }
}

export default connect(mapStateToProps, mapDispatchToProps)(Reddit)
```

When I reload the application, the screen on the IOS simulator is blank until I click on it, then the state seems to get updated and a render happens. Not sure if I'm handling async actions wrong, or if it's react-native (new to react and redux).
