### ISSUE TITLE
[FlatList] Flatlist explain how the methods work?

### ISSUE THREAD

**Issue by MrChe** [facebook/react-native#13735] opened 2017-05-02 11:28 UTC
Explain how the methods work : 
 1 - `scrollToEnd`
 2 - `scrollToIndex`
 3 - `scrollToItem`
 4 - `scrollToOffset` - analogue `scrollTo` in `ScrollView` ?
 5 - `recordInteraction`

I will be very grateful to the practical examples, since it is not clear from the documentation what the given functions take.

**Comment by joshyhargreaves** [comment] 2017-05-02 14:52
There's a example usage of `scrollToIndex` in the FlatList [example](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/FlatListExample.js#L79). You can also see what args the functions take in the [src](https://github.com/facebook/react-native/blob/master/Libraries/Lists/VirtualizedList.js#L188). 

It however does look like the arguments to these methods are not documented in the docs, so we should update them to reflect the arguments [link to current](https://facebook.github.io/react-native/releases/next/docs/flatlist.html#scrolltoindex).

**Comment by MrChe** [comment] 2017-05-02 15:58
`scrollToItem(params: {animated?: ?boolean, item: Item, viewPosition?: number})`
what is `Item` ?
```
scrollToOffset(params: {animated?: ?boolean, offset: number}) {
    const {animated, offset} = params;
    this._scrollRef.scrollTo(
      this.props.horizontal ? {x: offset, animated} : {y: offset, animated}
    );
  }
```
its anologue - `scrollTo` {x: Number, y:Number, animated: Boolean} ?

`recordInteraction` - example pls

**Comment by joshyhargreaves** [comment] 2017-05-02 16:18
`Item` is just an item from the array of `items` you pass the `data` prop in FlatList. 

`scrollToItem` compares by reference [here](https://github.com/facebook/react-native/blob/master/Libraries/Lists/VirtualizedList.js#L217) to check the `item` you pass it is equal one of the items you provided via `data`.

**Comment by MrChe** [comment] 2017-05-02 16:21
Could you give a practical example? I will be grateful to you!

**Comment by joshyhargreaves** [comment] 2017-05-02 18:43
@MrChe: here you go: https://snack.expo.io/B16VX8U1Z

**Comment by MrChe** [comment] 2017-05-02 18:50
1 - What is version react-native ?
 i use 0.43 and Flatlist not include `initialScrollIndex`, `initialNumToRender`
2 - 
Why do you call the data in the container? Why not in the component itself?
Example 
```
return 
<ScrollToExample
data = {getData (100)}
/>
```

**Comment by joshyhargreaves** [comment] 2017-05-02 19:00
1. FlatList is included in 0.43 but `initialScrollIndex`will be in `0.45` as it only was added last week. 
If you want to use `initialScrollIndex` from FlatList in master branch of `RN` in your project without upgrading `react-native` you can copy FlatList.js & VirtualizedList.js from maser into your project and use a local include.
2. It's more of a personal preference. The motivation to doing it this way is that ScrollToExample is kept 'more pure'. Strictly speaking it's not pure as it uses the COLOR constants.

**Comment by MrChe** [comment] 2017-05-02 19:04
Okay, but you still have not answered about `scrollToItem`

**Comment by joshyhargreaves** [comment] 2017-05-02 19:16
I updated with a `scrollToItem` example.

**Comment by MrChe** [comment] 2017-05-02 19:22
nope, nothing change!

**Comment by joshyhargreaves** [comment] 2017-05-02 19:24
Line 43.

**Comment by joshyhargreaves** [comment] 2017-05-02 19:26
https://snack.expo.io/HJcgiI8kb

**Comment by MrChe** [comment] 2017-05-02 19:26
http://take.ms/hvDbb

**Comment by MrChe** [comment] 2017-05-02 19:28
Yep, thk! Maybe you help with this problem https://github.com/facebook/react-native/issues/13736  ?

**Comment by MrChe** [comment] 2017-05-02 19:57
this video-problem http://take.ms/DHdyO

**Comment by joshyhargreaves** [comment] 2017-05-02 21:09
@MrChe it's quite hard from how you've described this issue you're having to understand what you're trying to do :/.

**Comment by MrChe** [comment] 2017-05-02 21:13
In fact, everything is simple. On the video, I showed everything I wanted. When I move from portrait mode to дфтвысфзу mode, I have a displacement, and only after tap the offset disappears!

**Comment by sahrens** [comment] 2017-05-03 15:14
@hramos / @ericvicenti: any plans to improve our doc autogen for the method case? would be nice to show the actual type for the params instead of just `scrollToIndex(params: object)`.

**Comment by grundmanise** [comment] 2017-05-25 20:34
@sahrens Could you please tell more about `recordInteraction` prop? Why should we call it in `componentDidUpdate`?

**Comment by sahrens** [comment] 2017-05-25 21:29
`recordInteraction` is only needed for subtle correctness issues in some impression logging implementations.

**Comment by grundmanise** [comment] 2017-05-25 22:36
So, if my `renderItem` has a `TouchableOpacity/TouchableHighlight/Tuchable...` wrapper, then I should call `recordInteraction` on each `itemPress` and it will help with responsiveness (i.e. UI feedback - opacity change if it is `TouchableOpacity`)?

**Comment by sahrens** [comment] 2017-05-26 04:38
No, it has nothing to do with responsiveness or perf, it's just to make sure the viewability callbacks fire for impression logging.

**Comment by hramos** [comment] 2017-08-16 03:09
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Closed by hramos** 2017-08-16 03:09 UTC
Labels: Documentation, Icebox

**Comment by ajkhatibi** [comment] 2017-10-15 04:13
Having the same issue here? I think documentation on this is not clear. What does scrollToEnd(params?: object) even mean? are params optional? am I passing a parameter and an object?

**Comment by hramos** [comment] 2017-10-16 16:36
`?` indicates it's an optional parameter, of type `object`. These are Flow type annotations.

**Comment by marceloHashzen** [comment] 2018-03-06 14:40
Is it possible to use `scrollToOffset` with animated flatlist?
An animated flatlist created using:
`const AnimatedFlatList= Animated.createAnimatedComponent(FlatList);`

The refs is allways undefined when I try to call this function with onPress event...

**Comment by sahrens** [comment] 2018-03-06 20:15
all Animated components expose the getNode method on the ref so you can get the underlying component: https://github.com/facebook/react-native/blob/26684cf3adf4094eb6c405d345a75bf8c7c0bf88/Libraries/Animated/src/createAnimatedComponent.js#L175

**Comment by marceloHashzen** [comment] 2018-03-07 00:06
Hi @sahrens, thank you for your help!
I've made a little research here about getNode, since I never worked with it, but I still haven't managed to make the scroll to work. Now when I press the button my app seems to freeze...

Here is my code:

Home.js:
```javascript
handleScrollTopPress = () => {
    console.tron.log(this.listRef.getNode());
}

<AnimatedFlatList
    ref={ref => this.listRef = ref}
    ...
/>

<ScrollButton press={this.handleScrollTopPress} />
```

ScrollButton.js:
```javascript
const ScrollButton = ({ press }) => (
  <TouchableWithoutFeedback onPress={() => press()}>
    <View style={styles.container}>
      <Icon name="chevron-up" style={styles.icon} />
    </View>
  </TouchableWithoutFeedback>
);
```

I'm using reactotron for the log, but when I click the button, nothing is shown in the log, and I can't click in any other button or link in the app.
