### ISSUE TITLE
(1) UNHANDLED JS EXCEPTION: MINIFIED REACT ERROR #143   (2) On update app behaviour change

### ISSUE THREAD

**Issue by krishbhattacharyya** [facebook/react-native#13372] opened 2017-04-07 06:07 UTC
### Description

**(1) UNHANDLED JS EXCEPTION: MINIFIED REACT ERROR #143 ( Getting in the crash report )** 
 
Since long days I am facing this issue. After long days on opening react native app the app is going crash. 

**(2) On update app behaviour change** 

 Suppose I update the app in logged in state then the app is crashed ( save the logged in state in AsyncStorage ). Then I have to reinstall the app.

### Additional Information

In the android it is working properly ( App is using large images ). 

* React Native version: "0.37.0"
* Platform: IOS
* Development Operating System: MacOS
* Dev tools:  Xcode 8.3

**Comment by hramos** [comment] 2017-04-07 17:41
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-04-07 17:41 UTC
