### ISSUE TITLE
bundling failed: Error: Unable to resolve module `./../react-transform-hmr/lib/index.js`

### ISSUE THREAD

**Issue by yldrmzffr** [facebook/react-native#21510] opened 2018-10-05 08:43 UTC
## Description

```
react-native init test
cd test
react-native run-android

```

I made the first Installation. I get an error when I run the  "run-android " command.
### Error

```
error: bundling failed: Error: Unable to resolve module `./../react-transform-hmr/lib/index.js` from `/home/muzo/reactnative/test/App.js`: The module `./../react-transform-hmr/lib/index.js` could not be found from `/home/muzo/reactnative/test/App.js`. Indeed, none of these files exist:

  * `/home/muzo/reactnative/react-transform-hmr/lib/index.js(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
  * `/home/muzo/reactnative/react-transform-hmr/lib/index.js/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
    at ModuleResolver.resolveDependency (/home/muzo/reactnative/test/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:209:697)
    at ResolutionRequest.resolveDependency (/home/muzo/reactnative/test/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:83:16)
    at DependencyGraph.resolveDependency (/home/muzo/reactnative/test/node_modules/metro/src/node-haste/DependencyGraph.js:222:485)
    at Object.resolve (/home/muzo/reactnative/test/node_modules/metro/src/lib/transformHelpers.js:149:25)
    at dependencies.map.result (/home/muzo/reactnative/test/node_modules/metro/src/DeltaBundler/traverseDependencies.js:316:29)
    at Array.map (<anonymous>)
    at resolveDependencies (/home/muzo/reactnative/test/node_modules/metro/src/DeltaBundler/traverseDependencies.js:312:16)
    at /home/muzo/reactnative/test/node_modules/metro/src/DeltaBundler/traverseDependencies.js:169:33
    at Generator.next (<anonymous>)
    at step (/home/muzo/reactnative/test/node_modules/metro/src/DeltaBundler/traverseDependencies.js:271:307)
    
 BUNDLE  [android, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.
``` 

### Operating system
Linux Mint 18.03

**Comment by kelset** [comment] 2018-10-05 08:45
Duplicate of https://github.com/facebook/react-native/issues/21490

**Closed by kelset** 2018-10-05 08:45 UTC

**Comment by Durrellgemuh** [comment] 2019-08-12 23:36
I first noticed this error when I installed yarn package so I uninstalled it and well my environment works perfectly though a little slow, slowly but surely so try and uninstalling yarn and see if it works for you
