### ISSUE TITLE
Fresco build issue when upgrading from 0.61.4 to 0.63.1

### ISSUE THREAD

**Issue by billouboq** [facebook/react-native#29392] opened 2020-07-16 06:12 UTC
## Description
Since fresco has downsampling issues when linked with React-Native (see: https://github.com/facebook/fresco/issues/2397), I had to use a forked Fresco's version and build it manually. It worked well in react-native 0.61.4 but when I tried to update to react-native 0.63.1 I have this error :

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:multiDexListDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Error while merging dex archives: 
     Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
     Program type already present: com.facebook.drawee.backends.pipeline.BuildConfig
```

It seems that react-native includes fresco now and it conflict with the builded fresco version.

I tried things like this :

```
dependencies {
		implementation("com.facebook.react:react-native:+") {
			exclude group: 'com.facebook.fresco'
    }
```

But it didn't worked very well.

If I comment the part where I build my forked fresco library it work very well. But then I will have issues with downsampling...

Is there a way to exclude fresco and only keep my own fresco build ?

Here is my gradle code :

```
apply plugin: "com.android.application"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"]
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    enableHermes: false,  // clean and rebuild if changing
]

apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = true

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = true

/**
 * The preferred build flavor of JavaScriptCore.
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US.  Note that
 * this variant is about 6MiB larger per architecture than default.
 */
def jscFlavor = 'org.webkit:android-jsc:+'
/**
 * Whether to enable the Hermes VM.
 *
 * This should be set on project.ext.react and mirrored here.  If it is not set
 * on project.ext.react, JavaScript will not be compiled to Hermes Bytecode
 * and the benefits of using Hermes will therefore be sharply reduced.
 */
def enableHermes = project.ext.react.get("enableHermes", false);

android {
	compileSdkVersion 28

	compileOptions {
			sourceCompatibility JavaVersion.VERSION_1_8
			targetCompatibility JavaVersion.VERSION_1_8
	}

	defaultConfig {
			applicationId "___REMOVED___"
			minSdkVersion 19
			targetSdkVersion 28
			versionCode 1776
			versionName "10.0.556"
			renderscriptTargetApi 23
			renderscriptSupportModeEnabled true
			multiDexEnabled true
			vectorDrawables.useSupportLibrary = true
			missingDimensionStrategy 'react-native-camera', 'general'
	}

	splits {
			abi {
					reset()
					enable enableSeparateBuildPerCPUArchitecture
					universalApk false  // If true, also generate a universal APK
					include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
			}
	}
	dexOptions {
			jumboMode = true
	}
	buildTypes {
			release {
					minifyEnabled enableProguardInReleaseBuilds
					proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
          signingConfig signingConfigs.release
			}
	}


	// applicationVariants are e.g. debug, release
	applicationVariants.all { variant ->
			variant.outputs.each { output ->
					// For each separate APK per architecture, set a unique version code as described here:
					// http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
					def versionCodes = ["armeabi-v7a":1, "x86":2, "arm64-v8a": 3, "x86_64": 4]
					def abi = output.getFilter(OutputFile.ABI)
					if (abi != null) {  // null for the universal-debug, universal-release variants
							output.versionCodeOverride =
											versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
					}
			}
	}

  packagingOptions {
		pickFirst '**/*.so'
  }
}


dependencies {
		implementation("com.facebook.react:react-native:+")
		implementation 'com.facebook.fresco:animated-gif:2.1.0'
		implementation project(':react-native-safe-area-context')
    implementation project(':react-native-pdf')
    implementation project(':react-native-image-crop-picker')
    implementation project(':react-native-ffmpeg')
    implementation project(':react-native-fcm')
    implementation project(':react-native-static-server')
    implementation project(':react-native-sound')
    implementation project(':lottie-react-native')
    implementation project(':react-native-code-push')
    implementation project(':react-native-reanimated')
    implementation project(':react-native-webview')
    implementation project(':react-native-screens')
		implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"
    compile project(':react-native-gesture-handler')

    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.fbjni'
    }
    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }
    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }

    if (enableHermes) {
      def hermesPath = "../../node_modules/hermes-engine/android/";
      debugImplementation files(hermesPath + "hermes-debug.aar")
      releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
      implementation jscFlavor
    }

    compile project(':react-native-zip-archive')
    implementation project(':rn-fetch-blob')
    implementation project(':react-native-community-netinfo')
    compile project(':react-native-camera')
    compile project(':react-native-photo-view-ex')
    compile project(':react-native-video')
    compile project(':react-native-svg')
    compile project(':react-native-orientation-locker')
    compile project(':react-native-keychain')
    compile project(':react-native-youtube')
    compile project(':react-native-linear-gradient')
    compile project(':react-native-spinkit')
    compile project(':react-native-background-upload')
    compile project(':react-native-keep-awake')
    compile project(':react-native-track-player')
    implementation project(':react-native-permissions')
    implementation project(':react-native-localize')
    implementation project(':react-native-sqlite-storage')
    implementation project(':react-native-scratch')
    implementation project(':@react-native-community_async-storage')
    implementation 'com.google.firebase:firebase-core:15.0.2'
    implementation 'com.google.firebase:firebase-messaging:15.0.2'
    implementation 'com.google.android.gms:play-services-auth:15.0.1'
    implementation "androidx.multidex:multidex:2.0.1"
    implementation 'androidx.appcompat:appcompat:1.0.0'
    implementation('org.conscrypt:conscrypt-android:2.0.0')
    compile project(':RNMail')
    implementation project(':react-native-google-signin')
		implementation project(':react-native-datetimepicker')
		compile fileTree(include: ['*.jar'], dir: 'libs')
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply plugin: 'com.google.gms.google-services'
// Work around
com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
```

## React Native version:
Run `react-native info` in your terminal and copy the results here.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Follow the steps right here: https://github.com/clytras/react-native-fresco
2. Build android

## Expected Results
Expect my android code to compile correctly

**Comment by dulmandakh** [comment] 2020-09-01 21:20
Closing the issue because this issue tracker is intended to track React Native issues, but your case is caused by your custom configuration. I suspect that Fresco version is bumped between 0.61.4 and 0.63.1, therefore you might need to upgrade your custom Fresco build too.

**Closed by dulmandakh** 2020-09-01 21:20 UTC
Labels: Needs: Triage :mag:

**Comment by clytras** [comment] 2020-09-15 17:11
@billouboq there is a binary lib conflict with `com.facebook.flipper:flipper-fresco-plugin`.  I'll try to find some time and upgrade the Fresco template for 0.63 but in the meantime, you can disable Flipper if you want to compile Fresco and disable imagepipeline downsampling for RN 0.63.

**Comment by billouboq** [comment] 2020-09-21 13:04
@clytras Thank you very much, you are a savior !
