### ISSUE TITLE
AccessbilityInfo error from react-native 0.56

### ISSUE THREAD

**Issue by JayricMok** [facebook/react-native#20204] opened 2018-07-14 06:28 UTC
## Environment
React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Memory: 6.59 GB / 11.91 GB
    Binaries:
      Yarn: yarn install v0.27.5
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.64s. - C:\Users\Jayric Mok\AppData\Roaming\npm\yarn.CMD
      npm: 6.1.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4720617

## Description
I tried to create a new react native project v 0.56, but stuck at this error when metro bundle starting.

Loading dependency graph, done.
error: bundling failed: Error: Unable to resolve module `AccessibilityInfo` from `C:\RN\TESTProject\node_modules\react-native\Libraries\react-native\react-native-implementation.js`: Module `AccessibilityInfo` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (C:\RN\TESTProject\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:167:1306)
    at ResolutionRequest.resolveDependency (C:\RN\TESTProject\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:80:16)
    at DependencyGraph.resolveDependency (C:\RN\TESTProject\node_modules\metro\src\node-haste\DependencyGraph.js:237:485)
    at Object.resolve (C:\RN\TESTProject\node_modules\metro\src\lib\transformHelpers.js:116:25)
    at dependencies.map.result (C:\RN\TESTProject\node_modules\metro\src\DeltaBundler\traverseDependencies.js:298:29)
    at Array.map (<anonymous>)
    at resolveDependencies (C:\RN\TESTProject\node_modules\metro\src\DeltaBundler\traverseDependencies.js:294:16)
    at C:\RN\TESTProject\node_modules\metro\src\DeltaBundler\traverseDependencies.js:159:33
    at Generator.next (<anonymous>)
    at step (C:\RN\TESTProject\node_modules\metro\src\DeltaBundler\traverseDependencies.js:239:307)
 BUNDLE  [android, dev] ..\..\../index.js ░░░░░░░░░░░░░░░░ 1.1% (2/19), failed.

## react-native version
react-native-cli: 2.0.1
react-native: 0.56.0

## Package

	{
	  "name": "TESTProject",
	  "version": "0.0.1",
	  "private": true,
	  "scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	  },
	  "dependencies": {
		"react": "16.4.1",
		"react-native": "0.56.0"
	  },
	  "devDependencies": {
		"babel-jest": "23.4.0",
		"babel-preset-react-native": "5",
		"jest": "23.4.1",
		"react-test-renderer": "16.4.1"
	  },
	  "jest": {
		"preset": "react-native"
	  }
    }

**Comment by bhram** [comment] 2018-07-14 09:46
same here

**Comment by ZLGong** [comment] 2018-07-14 11:39
Me too

**Comment by kelset** [comment] 2018-07-14 11:48
Duplicate of #19953

**Closed by kelset** 2018-07-14 11:48 UTC

**Comment by YY007H** [comment] 2018-07-17 06:49
me too

**Comment by naiduprakash** [comment] 2018-07-17 07:08
same here would anybody find the solution for it?

**Comment by YY007H** [comment] 2018-07-17 07:13
I found a way.   "react-native": "^0.56.0"  =>  "react-native": "^0.55.4" in package.json
