### ISSUE TITLE
[Android] App crash on android search assistant opening

### ISSUE THREAD

**Issue by sooth-sayer** [facebook/react-native#13201] opened 2017-03-29 14:12 UTC
### Description
App crashes on opening android search assistant when modal is visible

### Crash log
03-29 17:43:44.600 18602 18602 E AndroidRuntime: FATAL EXCEPTION: main
03-29 17:43:44.600 18602 18602 E AndroidRuntime: Process: com.modalcrash, PID: 18602
03-29 17:43:44.600 18602 18602 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.dispatchProvideStructure(android.view.ViewStructure)' on a null object reference
03-29 17:43:44.600 18602 18602 E AndroidRuntime: 	at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3080)
03-29 17:43:44.600 18602 18602 E AndroidRuntime: 	at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3080)
03-29 17:43:44.600 18602 18602 E AndroidRuntime: 	at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3080)
03-29 17:43:44.600 18602 18602 E AndroidRuntime: 	at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3080)
03-29 17:43:44.600 18602 18602 E AndroidRuntime: 	at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3080)
03-29 17:43:44.600 18602 18602 E AndroidRuntime: 	at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3080)
03-29 17:43:44.600 18602 18602 E AndroidRuntime: 	at android.app.assist.AssistStructure$WindowNode.<init>(AssistStructure.java:422)
03-29 17:43:44.600 18602 18602 E AndroidRuntime: 	at android.app.assist.AssistStructure.<init>(AssistStructure.java:1335)
03-29 17:43:44.600 18602 18602 E AndroidRuntime: 	at android.app.ActivityThread.handleRequestAssistContextExtras(ActivityThread.java:2833)
03-29 17:43:44.600 18602 18602 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1667)
03-29 17:43:44.600 18602 18602 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-29 17:43:44.600 18602 18602 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:179)
03-29 17:43:44.600 18602 18602 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6101)
03-29 17:43:44.600 18602 18602 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-29 17:43:44.600 18602 18602 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
03-29 17:43:44.600 18602 18602 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

### Reproduction Steps and Sample Code
Simple app that can help to reproduce 
https://github.com/sooth-sayer/RNModalCrash

### Additional Information
* React Native version: 0.42.3
* Platform: Android

**Comment by niztal** [comment] 2017-05-14 08:41
+1

We need an urgent for fix for this bug

**Comment by dannycochran** [comment] 2017-06-21 22:38
Happening for me using 0.45.1

**Comment by hramos** [comment] 2017-08-24 20:42
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Closed by hramos** 2017-08-24 20:42 UTC
Labels: Icebox

**Comment by LironErman** [comment] 2017-08-30 11:17
Happening for me using 0.47.1

**Comment by Dmytro96** [comment] 2017-09-13 14:34
Please, reopen the issue, because trouble still exist.

**Comment by sooth-sayer** [comment] 2017-09-13 14:51
@Dmytro96, new issue here https://github.com/facebook/react-native/issues/15932
