### ISSUE TITLE
IOS build takes too long and never finishes for 0.75.2 version

### ISSUE THREAD

**Issue by SergenSiyli** [facebook/react-native#46380] opened 2024-09-07 19:50 UTC
### Description

I m trying to run npx react-native run-ios command. But I'm waiting too long time for build. I m still waiting 1 hours. 
I think the latest version of react native has problems for ios. 
I've been waiting for hours for the app to open in the simulator. I tried many option. I deleted simulator ,reset macbook and created new project. but still same ı think has problem for ios build this version 0.75.2.
⠼ Building the app.........

### Steps to reproduce

npx @react-native-community/cli@latest init AwesomeProject
npx react-native run-ios

### React Native Version

0.75.2

### Affected Platforms

Runtime - iOS, Build - MacOS

### Output of `npx react-native info`

```text
npx react-native info
info Fetching system and libraries information...
System:
  OS: macOS 14.6.1
  CPU: (8) arm64 Apple M2
  Memory: 2.95 GB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.9.0
    path: /usr/local/bin/node
  Yarn: Not Found
  npm:
    version: 10.1.0
    path: /usr/local/bin/npm
  Watchman:
    version: 2024.03.18.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK:
    API Levels:
      - "33"
      - "34"
    Build Tools:
      - 30.0.3
      - 33.0.0
      - 33.0.1
      - 34.0.0
    System Images:
      - android-34 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.11090377
  Xcode:
    version: 15.0/15A240d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 21.0.3
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.2
    wanted: 0.75.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
⠼ Building the app.........
```

### Reproducer

https://github.com/SergenSiyli

### Screenshots and Videos

![Screenshot 2024-09-07 at 22 48 03](https://github.com/user-attachments/assets/24896684-c0c4-44c2-b298-5b0b35de92b9)

**Comment by cipolleschi** [comment] 2024-09-09 11:14
@SergenSiyli sorry to hear that the build time is taking too long.

Can you check a couple of things for me?
1. Can you try to build from Xcode and see if the build numbers increases or not?
<img width="985" alt="Screenshot 2024-09-09 at 12 11 10" src="https://github.com/user-attachments/assets/0fdb0bd2-e765-4abb-bb2f-815eecda6594">

2. Can you run `bundle exec pod deintegrate` and then reinstall pods? What I'm looking for is to understand whether you are using a prebuild version of Hermes or if you are trying to build hermes from source, as it is usually one of the pieces that takes most time (and that's why we are distributing prebuilds)
<img width="1245" alt="Screenshot 2024-09-09 at 12 14 08" src="https://github.com/user-attachments/assets/726431d5-8e93-475c-b338-ca520e5ad5b7">
See the yellow line in the screenshot

**Comment by SergenSiyli** [comment] 2024-09-09 16:12
> @SergenSiyli sorry to hear that the build time is taking too long.
> 
> Can you check a couple of things for me?
> 
> 1. Can you try to build from Xcode and see if the build numbers increases or not?
> 
> <img alt="Screenshot 2024-09-09 at 12 11 10" width="985" src="https://private-user-images.githubusercontent.com/11162307/365626863-0fdb0bd2-e765-4abb-bb2f-815eecda6594.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4OTc5OTgsIm5iZiI6MTcyNTg5NzY5OCwicGF0aCI6Ii8xMTE2MjMwNy8zNjU2MjY4NjMtMGZkYjBiZDItZTc2NS00YWJiLWJiMmYtODE1ZWVjZGE2NTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDE2MDEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMDY1NzNiYTMyNWU5NThhMTBjOTFkMTMxODcxZGQ0NDQxMTg0NWNhM2YzMzcxOGU1ODJjNWU4NTYzN2ZkMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uRENxIXV2P_MJ0wBTNrT2qAubAdVc9aZaeKiUD4aPX0">
> 2. Can you run `bundle exec pod deintegrate` and then reinstall pods? What I'm looking for is to understand whether you are using a prebuild version of Hermes or if you are trying to build hermes from source, as it is usually one of the pieces that takes most time (and that's why we are distributing prebuilds)
> 
> <img alt="Screenshot 2024-09-09 at 12 14 08" width="1245" src="https://private-user-images.githubusercontent.com/11162307/365627757-726431d5-8e93-475c-b338-ca520e5ad5b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4OTc5OTgsIm5iZiI6MTcyNTg5NzY5OCwicGF0aCI6Ii8xMTE2MjMwNy8zNjU2Mjc3NTctNzI2NDMxZDUtOGU5My00NzVjLWIzMzgtY2E1MjBlNWFkNWI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDE2MDEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwMzk2ZDc0Y2MyYzg1M2Q0NGUyN2I5M2ZkMWZmY2RiNjVlNDg1ZDJjOGNmZGY1MGZlNWI5YWY3YzdhYTAxZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JrlOpU1kdDELfMnQI7j5ljg0e6Hyc2BNQ73E66XVTy8"> See the yellow line in the screenshot

1-) IOS Build Result: 
<img width="362" alt="Screenshot 2024-09-09 at 19 06 51" src="https://github.com/user-attachments/assets/db3a52f2-ab3c-4482-8643-224f9789bd3d">

<img width="859" alt="Screenshot 2024-09-09 at 19 08 11" src="https://github.com/user-attachments/assets/6b56b7bc-0e56-4716-b319-b93672b5cea9">

2-) My pod install result:

<img width="1292" alt="Screenshot 2024-09-09 at 19 10 32" src="https://github.com/user-attachments/assets/ec825688-fbc7-4c90-b7c2-adab42c8341c">

**Comment by cipolleschi** [comment] 2024-09-10 10:44
@SergenSiyli That error is because you are not running Metro.

in a separate terminal window, please run:
```
1. cd <path-to-your-project>
2. yarn start
```
Then relaunch the app or press the Reload button in the tab bar of the Red screen.

Build was successful if you ended up in that screen.

**Comment by SergenSiyli** [comment] 2024-09-11 17:13
> @SergenSiyli That error is because you are not running Metro.
> 
> in a separate terminal window, please run:
> 
> ```
> 1. cd <path-to-your-project>
> 2. yarn start
> ```
> 
> Then relaunch the app or press the Reload button in the tab bar of the Red screen.
> 
> Build was successful if you ended up in that screen.

I solved the problem in the first item. I got a successful build on xcode. But the application still does not build with the npx react-native run-ios command. What can I do?

**Comment by EzioLi01** [comment] 2024-09-12 09:44
Same system (Apple M2), same issue.

**Comment by cipolleschi** [comment] 2024-09-12 13:58
duplicate of #46352, please focus all the comments on the previous issue.
We will work on this soon. Until then, please use Xcode to build if you are facing the issue.

Also, we use the same command on CI to build a sample project called hello world and I tested that `yarn ios` worked for me in a new project with 0.75.2. There might be something going on with your system configuration.

**Closed by cipolleschi** 2024-09-12 13:58 UTC
Labels: Platform: iOS, Needs: Repro, Needs: Attention
