### ISSUE TITLE
SAMSUNG s6 keyboard without decimal point

### ISSUE THREAD

**Issue by my-love** [facebook/react-native#12977] opened 2017-03-16 13:33 UTC
### Description

[FILL THIS OUT: Explain what you did, what you expected to happen, and what actually happens.]
with SAMSUNG s6 TextInput and keyboardType is numeric the decimal point don't see in the keyboard

### Additional Information

* React Native version: 0.38
* Platform: Android SAMSUNG S6
* Operating System: MacOS
* Dev tools: [FILL THIS OUT: MacOS

**Comment by hramos** [comment] 2017-03-16 18:09
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-03-16 18:09 UTC
