### ISSUE TITLE
[TextInput] secureTextEntry={true} causes text to flicker

### ISSUE THREAD

**Issue by MiLeung** [facebook/react-native#8142] opened 2016-06-16 05:09 UTC
version 0.27.2

[https://www.youtube.com/watch?v=9QwZQUVPTl4&feature=youtu.be](https://www.youtube.com/watch?v=9QwZQUVPTl4&feature=youtu.be)

**Comment by ryankask** [comment] 2016-06-16 12:47
I have the same issue. I believe this started happening in 0.26:

![securetextentry1](https://cloud.githubusercontent.com/assets/81891/16117081/30ac6f48-33c8-11e6-8308-f52ccde6dbcf.gif)

**Comment by alekhurst** [comment] 2016-06-16 17:28
Same issue here since updating RN version to 0.27.1. Looks identical to above example

**Comment by alphasp** [comment] 2016-06-17 13:04
same issue happening here on 0.26

**Comment by ryankask** [comment] 2016-06-17 22:49
This is a duplicate of https://github.com/facebook/react-native/issues/7936.

@MiLeung Should this be closed so all attention can be focused on that issue?

**Comment by MiLeung** [comment] 2016-06-18 16:35
@ryankask I think #7936 is a slightly different issue.  This issue shows the characters for a fraction of a second before obscuring it.  #7936 immediately obscures the text.

**Comment by ryankask** [comment] 2016-06-19 16:23
Good point. They seem very similar. The example code the other user posted
is using setTimeout and I'm not sure if that's making it seem different.

**Comment by sesm** [comment] 2016-06-28 11:23
@ryankask Indeed, #7936 used setTimeout, because the issue wasn't reproducible on rnplay.org without setTimeout.

In my codebase saving the value to component state and reading it back was not enough to cause the flicker, while using Redux store and action was enough. 

One of the comments in #7936 is
> I've been having this issue too, even just in setting the state of the current component and reading it back into the input.

So, it seems that this issue involves some race condition, and is not always reproducible when delay between user input and updating TextInput 'value' property is small.

**Comment by jakpaw** [comment] 2016-06-30 14:13
The workaround for me was using the `TextInput` `defaultValue` property instead of `value`. This way the input is populated at the beginning with a value from redux state, you can still trigger state changes in `onChangeText` event, everything behaves as expected and the error doesn't appear.

**Comment by KishPatel1996** [comment] 2016-06-30 15:34
can confirm @jakpaw 's workaround works.

**Comment by MiLeung** [comment] 2016-06-30 15:45
@jakpaw No flicker, but the text still jumps slightly down for me
![](https://media.giphy.com/media/26BRxLuBuj1vW0Ks0/giphy.gif)

**Comment by KishPatel1996** [comment] 2016-06-30 21:10
@MiLeung same with me, but this is the best solution i've seen so far besides introducing a custom component.

**Comment by jakpaw** [comment] 2016-07-01 08:01
@MiLeung It does, but I'd say it's an unrelated issue. It occurs already on RN 0.20: https://rnplay.org/apps/eSCk_Q

**Comment by mkonicek** [comment] 2016-10-27 22:13
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/textinput-securetextentrytrue-causes-text-to-flicker

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Closed by mkonicek** 2016-10-27 22:13 UTC
Labels: Icebox

**Comment by jamessawyer** [comment] 2018-06-25 07:09
Same issue on iOS 9.3.5. Tried @jakpaw 's solution, but with no luck! iOS devices above 10 work fine
