### ISSUE TITLE
[Android] Using a Double as lineHeight throws TypeError

### ISSUE THREAD

**Issue by mikefowler** [facebook/react-native#3589] opened 2015-10-22 02:00 UTC
I have this code in a StyleSheet, being applied to a `<Text />` element. As written below, the code throws an error when running on Android. Changing `24.2` to any integer fixes the issue. Works fine in either situation on iOS.

```js
itemTitle: {
  fontSize: 22,
  lineHeight: 24.2
}
```

<img width="475" alt="screen shot 2015-10-21 at 6 49 37 pm" src="https://cloud.githubusercontent.com/assets/744542/10654946/e9e98bf4-7824-11e5-98b9-0af462cbd6fe.png">

**Comment by AlexErofeev** [comment] 2015-10-28 15:19
Duplicate of https://github.com/facebook/react-native/issues/3715

**Comment by ide** [comment] 2015-10-28 18:40
This should be fixed in master.

**Closed by ide** 2015-10-28 18:40 UTC
