### ISSUE TITLE
[Android] undefined is not an object(evaluating 'NativeModules.AndroidConstants.ServerHost.split')

### ISSUE THREAD

**Issue by devhyunjae** [facebook/react-native#9557] opened 2016-08-24 02:05 UTC
<img width="371" alt="screen shot 2016-08-24 at 10 57 28 am" src="https://cloud.githubusercontent.com/assets/12890257/17915940/950d2afc-69e9-11e6-9dc9-7cba6566eaee.png">

I can assume the error happens in here,

https://github.com/facebook/react-native/blob/master/Libraries/Devtools/setupDevtools.js#L22

I don't have a clue what to do with this one. Do I need to fork the react-native and comment this line and just assign `'localhost'`???

**Comment by samerce** [comment] 2016-08-26 16:23
also just ran into this problem while trying to get Android working for a React Native project where iOS is already working

**Comment by ladingwu** [comment] 2016-09-07 03:07
did you fix this now?

**Comment by raghunandan-dev** [comment] 2016-09-08 08:23
Ran into the same issue any one know how to fix this ? 
dependencies {
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.facebook.react:react-native:0.19+"
    compile 'com.android.support:design:23.3.0'
    compile 'com.github.bumptech.glide:okhttp3-integration:1.4.0@aar'
    compile 'com.squareup.okhttp3:okhttp:3.2.0'
}

**Comment by satya164** [comment] 2016-09-08 08:55
@raghunandan-dev you're using RN 0.19 which is not officially supported. Please update to latest version.

**Comment by satya164** [comment] 2016-09-08 08:57
@devhyunjae what's your React Native version? Can you post your dependencies in `build.gradle`?

**Comment by raghunandan-dev** [comment] 2016-09-08 09:07
@satya164 Even its coming for below version
compile "com.facebook.react:react-native:0.20.1".

**Comment by satya164** [comment] 2016-09-08 09:09
@raghunandan-dev Latest version is 0.32. Clearly your version in package.json is out of sync with version in your gradle. Run `react-native upgrade` to upgrade your files and check the release notes for any breaking changes or migration path.

**Comment by raghunandan-dev** [comment] 2016-09-08 09:27
@satya164  Yes but when I used "com.facebook.react:react-native:0.32.0" in my app build.gradle file its showing error as "failed to resolve com.facebook.react-native:0.32.0 in android studio ". And I have upgraded my react native into latest version 0.32 in node-modules.

**Comment by YanYanLun** [comment] 2016-09-13 07:09
I also encountered the same problem, but in accordance with the above mentioned have not been resolved, it should be how to do?

**Comment by obromios** [comment] 2016-09-24 07:43
I have an app with react-native version 0.33.0 , and done ```react-native upgrade``` and am seeing this issue.

**Comment by Gagege** [comment] 2016-09-27 19:52
react-native 0.34.0, still seeing a similar issue. Getting "undefined is not an object" on Android when using map, filter, or find. These all work on iOS.

**Comment by JBerendes** [comment] 2016-09-29 13:47
I'm getting the same error when I try either 0.32 or 0.33

There could also be a correlation with another error #5658, although in my case I'm getting `com.facebook.react.bridge.NativeArgumentsParseException: RCTNetworking.sendRequest got 8 arguments, expected 7` 

It may also be worth mentioning that attempting to put react-native into an existing Android app.

**Comment by JBerendes** [comment] 2016-09-29 14:47
Dug deeper...  AndroidConstants for me is `AndroidConstants: { Version: 21 }`  Which tells me that because I'm using AndroidSDK 21 with my app I'm not getting expected constants that might be in a later(more recent) version of the AndroidSDK.

To reproduce my findings and discover what your AndroidConstants is:

1.  open the file node_modules/react-native/Libraries/Devtools/setupDevtools.js
2. goto line 22
3. put in a log `console.log('Show me NativeModules.AndroidConstants /////// ',NativeModules.AndroidConstants);
    //hostname = NativeModules.AndroidConstants.ServerHost.split(':')[0];`

Please report what you find.

**Comment by obromios** [comment] 2016-10-04 09:17
Hi JBerendes, I would like to trying the logging message you suggest, but when I go to the branch where I was seeing the problem, a fatal error is occuring before I reach this point. Have  no idea why yet.  Assuming your insight is correct, how do you fix the problem?

**Comment by yanbober** [comment] 2016-10-23 02:53
`Exception in native call from JS
                                                                 com.facebook.react.bridge.NativeArgumentsParseException: RCTNetworking.sendRequest got 8 arguments, expected 7
                                                                     at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:227)
                                                                     at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:158)
                                                                     at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:58)
                                                                     at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.call(CatalystInstanceImpl.java:428)
                                                                     at com.facebook.react.bridge.queue.NativeRunnableDeprecated.run(Native Method)
                                                                     at android.os.Handler.handleCallback(Handler.java:815)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                     at android.os.Looper.loop(Looper.java:207)
                                                                     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:184)
                                                                     at java.lang.Thread.run(Thread.java:818)`

this same error, how to fix it? combine with an existing android project.

**Comment by lacker** [comment] 2016-12-17 01:05
It seems like this thread has become a bunch of related issues and the original bug had some unanswered followup questions, so I think we should close this issue as needs-more-info. If people have similar errors then please feel free to open new issues to report them!

**Closed by lacker** 2016-12-17 01:05 UTC
