### ISSUE TITLE
JavaScript not work in webview

### ISSUE THREAD

**Issue by imlooke** [facebook/react-native#8996] opened 2016-07-24 19:34 UTC
When I use the webview in my project，JavaScript not work in the HTML file，Here my code:
``
`  

        import React, { Component } from 'react';
        import {
          StyleSheet,
          Text,
          View,
          WebView,
        } from 'react-native';

        export default class NoteEditor extends Component {
          render() {
          	return (
              <WebView 
                style={styles.container} 
                source={require('./editor.html')}
                injectedJavaScript={'function myfunc() { alert(123) };myfunc();'}
                javaScriptEnabled={true}
                startInLoadingState={true}
              />
              
          	);
          }
        };

        const styles = StyleSheet.create({
          container: {
            flex: 1,
          },
        });

`

-I use RN 0.29.2
-in RN 0.27 is ok
**what should I do?  thanks**

**Comment by Kureev** [comment] 2016-07-25 08:17
iOS / Android?

**Comment by ChinaGoodProgrammer** [comment] 2016-07-25 08:31
me too！

**Comment by Kureev** [comment] 2016-07-25 08:37
Just tried on the fresh project:

<details>
![image](https://cloud.githubusercontent.com/assets/2273613/17095219/aa43067e-5253-11e6-9ff6-cb2455686765.png)
</details>

Corresponding code:

<details>
```jsx
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  WebView,
  View
} from 'react-native';

class example extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.ios.js
        </Text>
				<WebView
          automaticallyAdjustContentInsets={false}
          style={{height: 350, width: 300}}
          source={require('./test.html')}
          javaScriptEnabled={true}
          domStorageEnabled={true}
          decelerationRate="normal"
          startInLoadingState={true}
          scalesPageToFit={true}
        />
        <Text style={styles.instructions}>
          Press Cmd+R to reload,{'\n'}
          Cmd+D or shake for dev menu
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('example', () => example);
```
</details>

**Comment by Kureev** [comment] 2016-07-25 08:40
I think you have a problem with styling. Try fixed dimensions and/or adjust your layout. Let me know if it helps.

**Comment by Kureev** [comment] 2016-07-25 08:43
Your example with `alert` also works:
<details>
![image](https://cloud.githubusercontent.com/assets/2273613/17095416/9b72310a-5254-11e6-846f-f143612330c6.png)
</details>

**Comment by ChinaGoodProgrammer** [comment] 2016-07-25 08:46
Offline package does not work！

**Comment by ChinaGoodProgrammer** [comment] 2016-07-25 08:47
in iOS。

**Comment by ChinaGoodProgrammer** [comment] 2016-07-25 08:50
The injection of js code doesn't work in the release environment。

**Comment by ChinaGoodProgrammer** [comment] 2016-07-25 08:50
@Kureev

**Comment by ChinaGoodProgrammer** [comment] 2016-07-25 08:51
@Kureev 
Please help me thank you！

**Comment by imlooke** [comment] 2016-07-25 10:58
@Kureev，Android,
I test your code as same, but not work all the time
And I try to update RN to 0.30,not work, too
I even test this in three phones ,dose not work....
android6.0,5.1,4.4,
but in RN 0.27 is work..

**Comment by Kureev** [comment] 2016-07-25 11:43
I think the problem is in the release mode. Probably, something is broken in the packager.

**Comment by imlooke** [comment] 2016-07-25 11:48
what should I do for this time?back to RN 0.27?,or init a new project?
thanks for your help

**Comment by imlooke** [comment] 2016-07-25 12:11
@Kureev,it must be.now I back to 0.27 is not work,too.
**something is broken in the packager.**what should I do to solve this?

**Comment by grabbou** [comment] 2016-07-28 11:48
@Kureev shouldn't this issue be converted to StackOverflow?

**Comment by Kureev** [comment] 2016-07-28 15:02
@grabbou not sure. Probably, this issue can be reworded to "WebView doesn't work in Release mode".

**Comment by skatpgusskat** [comment] 2016-07-31 13:29
I installed 0.30 with cli command ```react-native init AwesomeProject```, and webview works pretty well even on release offline bundle mode.

I found that on ios, the ```AppDelegate.m``` has changed against the previous version, a little bit. could it be a point of this problem?

**Comment by Kureev** [comment] 2016-07-31 20:55
Then I'm about to close this one as far as its fixed in 0.30.

**Comment by Kureev** [comment] 2016-07-31 20:55
@facebook-github-bot close

**Comment by facebook-github-bot-5** [comment] 2016-07-31 20:58
@Kureev tells me to close this issue. If you think it should still be opened let us know why.

**Closed by facebook-github-bot-5** 2016-07-31 20:58 UTC
Labels: Ran Commands

**Comment by tapradhan** [comment] 2018-02-21 18:35
Javascript in webview is not working in ios after release.but works in debugging mode

**Comment by Arshiamidos** [comment] 2018-04-24 10:57
#16133 
hey guys check my answer  
it work with RN >=0.54
