### ISSUE TITLE
[Android][Animated]Animated ListView resets scroll position when re-rendered

### ISSUE THREAD

**Issue by ramilushev** [facebook/react-native#13580] opened 2017-04-19 12:24 UTC
### Description

I am trying to attach an `Animated.event` with `useNativeDriver: true` to a ListView, while also using the `onEndReached` callback. While the animation does work, once the callback is called and new items are added to the `dataSource`, the ListView resets and scrolls to top.

### Reproduction Steps and Sample Code

[Snack](https://snack.expo.io/SJWNLkHRx)

### Solution

The cause is any kind of re-render. In my case - the state change with the new `dataSource`.
Keeping the `ListView` animated, but omitting the `Animated.event` works. I have no idea how to fix it.

### Additional Information

* React Native version: 0.43.3
* Platform: Android
* Development Operating System: MacOS

**Comment by ramilushev** [comment] 2017-04-19 13:35
The problem was that `const AnimatedListView = Animated.createAnimatedComponent(ListView)` was in the `render` method. Moving it outside seems to fix the issue.

This can be closed if that is the expected behaviour.

**Comment by nihgwu** [comment] 2017-04-19 13:42
It is expected behavior, why should you define `AnimatedListView` inside `render`, you should don't make any time consuming operation in `render`

**Comment by ramilushev** [comment] 2017-04-19 13:47
@nihgwu Of course, you are correct. Thanks for the input!

**Comment by janicduplessis** [comment] 2017-04-19 18:09
Thanks @nihgwu, closing since it seems resolved.

**Closed by janicduplessis** 2017-04-19 18:09 UTC
