### ISSUE TITLE
Issue with memory usage when sending large data via the native bridge (RN 0.24)

### ISSUE THREAD

**Issue by maximilianhurl** [facebook/react-native#7554] opened 2016-05-13 16:05 UTC
I'am downloading a number of large JSON files (~3-15MB x 8) then using https://github.com/johanneslumpe/react-native-fs to save to disk which is causing my app to crash due to memory usage (>1GB on iOS and crashing on Android).

After testing it appears to be caused by passing a large amount of data over the react bridge and not related to the native code. I was just wondering if this is expected or for any suggestions on handling large data over the react bridge.

**Comment by christopherdro** [comment] 2016-05-13 18:01
@facebook-github-bot expected

**Comment by facebook-github-bot-7** [comment] 2016-05-13 18:06
The comment above tells me this is expected behavior. Closing this as we'd like to use the GitHub issue tracker for bugs. If you'd like to change how this feature works please post a feature request on [Product Pains](https://productpains.com/product/react-native/) so that other people can vote on it.

**Closed by facebook-github-bot-7** 2016-05-13 18:06 UTC
Labels: Ran Commands

**Comment by maximilianhurl** [comment] 2016-05-13 19:27
Does that mean you expect the bridge to cause large memory usage?

**Comment by ide** [comment] 2016-05-13 20:28
The bridge shouldn't crash but it's also not designed for large amounts of data. The bridge is intended to transfer small commands at a very fast rate with low latency, not data with high throughput.

**Comment by maximilianhurl** [comment] 2016-05-13 20:54
@ide okay well thanks for explaining that. We'll try breaking it down into smaller chunks or downloading natively instead then.
