### ISSUE TITLE
GLOBAL.Text error when upgrading to 0.16

### ISSUE THREAD

**Issue by maraujop** [facebook/react-native#4862] opened 2015-12-18 13:28 UTC
Hi,

After upgrading to RN 0.16 we had some nasty red boxes like this one, in iOS and Android.

![zbrhi](https://cloud.githubusercontent.com/assets/252257/11897741/77186dc0-a592-11e5-834a-18e9fb399f61.png)

```
TypeError: undefined is not an object (evaluating 'GLOBAL.Text={get DefaultProps(){throw getInvalidGlobalUseError('Text')}}') (line 1195 in the generated bundle)
```

Apparently there are more people having this issue and asking for help online. We didn't know how to fix it, so we created a new app and starting moving chunks of code trying to find the culprit. However, we ended up moving all the code without issues and everything was working and compiling. This looked like a cache bug, we continued working with this new project and after downloading the JS bundle for several times, we hit this red screen again.

Then we discovered that the `.babelrc` file we had in the root of our project was causing at least part of the issue. We renamed this file and then we launched the packager with `--reset-cache`. All of a sudden everything was working again. is this an expected behavior? can this be a packager cache bug?

Thanks, cheers
Miguel

**Comment by cancan101** [comment] 2015-12-19 02:33
Duplicate of #4811.

**Comment by cancan101** [comment] 2015-12-22 02:53
FWIW I am seeing this issue on 0.17 as well.

**Comment by cancan101** [comment] 2015-12-22 02:58
[These polyfills](https://github.com/facebook/react-native/blob/62e8ddc20561a39c3c839ab9f83c95493df117c0/Libraries/JavaScriptAppEngine/polyfills/document.js) seem to be transpiled as:
```js
(function(GLOBAL){
function getInvalidGlobalUseError(name){
return new Error(
'You are trying to render the global '+name+' variable as a '+
'React element. You probably forgot to require '+name+'.');}

GLOBAL.Text={
get defaultProps(){
throw getInvalidGlobalUseError('Text');}};

GLOBAL.Image={
get defaultProps(){
throw getInvalidGlobalUseError('Image');}};

if(GLOBAL.document){
GLOBAL.document.createElement=null;}

GLOBAL.MutationObserver=undefined;})(undefined);
```

**Comment by matteodem** [comment] 2015-12-29 18:07
Experiencing the same error locally.

**Comment by stenrap** [comment] 2016-01-02 21:06
I started experiencing this cryptic error today, with literally zero code changes on my part. All I did was stop the iOS simulator, which was successfully running my project as "iPad Air 2", change the simulator to "iPhone 6s Plus", then try to run it again—something I had done a dozen times in the last few hours with no problems. Now I can't run any iOS simulator—they all give me this error.

I tried the "extends" suggestion from https://github.com/facebook/react-native/issues/4811, but that didn't work. I then removed my `.babelrc` file, but that didn't work either. How do I clear my babel cache? Have I missed anything else?

**Comment by jeremy-hunter** [comment] 2016-01-03 20:29
I believe this command clears the cache (https://github.com/facebook/react-native/issues/1924)
node_modules/react-native/packager/packager.sh reset-cache

**Comment by kirillplatonov** [comment] 2016-01-04 13:18
@jeremy-hunter `react-native start --clear-cache` should do the same. But it doesn't helps =(

**Comment by kirillplatonov** [comment] 2016-01-04 15:52
As @jayli already mentioned in #4811 the solution is [here](http://stackoverflow.com/a/34298846/2621808).

**Closed** 2016-03-09 15:54 UTC
