### ISSUE TITLE
The demo xcode project initialized from (react-native init AwesomeProject) failed to build.

### ISSUE THREAD

**Issue by likai057187** [facebook/react-native#23056] opened 2019-01-17 23:03 UTC
## Environment
React Native Environment Info:
   System:
     OS: macOS High Sierra 10.13.6
     CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
     Memory: 589.20 MB / 8.00 GB
     Shell: 3.2.57 - /bin/bash
   Binaries:
     Node: 11.6.0 - /usr/local/bin/node
     npm: 6.5.0 - /usr/local/bin/npm
     Watchman: 4.9.0 - /usr/local/bin/watchman
   SDKs:
     iOS SDK:
       Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
   IDEs:
     Xcode: 10.1/10B61 - /usr/bin/xcodebuild
   npmPackages:
     react: 16.6.3 => 16.6.3
     react-native: 0.57.8 => 0.57.8
   npmGlobalPackages:
     react-native-cli: 2.0.1

## Description
I followed the steps from (https://facebook.github.io/react-native/docs/getting-started). Development OS is macOS. Target OS is iOS. 
The failure seems pretty popular, "React/xxxxx.h" not found in all project except React project itself. 
I've tried tried the same steps on the other macbook and it ended up with the same error. 
I've tried run the build through command/Xcode GUI, legacy/new build system, and also tried pretty much technologies posted over the internet about "React/xxxxx.h not found" issue but without any luck.

## Reproducible Demo
It's the official sample demo project, created by: react-native init AwesomeProject

**Comment by c623700** [comment] 2019-01-22 02:16
I have the same setup trying the same awesome project and when I get to the step to open the project in xCode - using the .xcworkpace file the project failed to build and I get an error: 
clang: error: linker command failed with exit code 1

**Comment by hramos** [comment] 2019-01-23 00:34
Hey @c623700, can you include what's the latest list of concrete steps to reproduce this failure? Sorry to ask, we want to make sure people can reproduce this - docs can change over time, so we'd prefer all the steps are listed in the issue itself.

**Comment by hramos** [comment] 2019-01-29 20:53
Closing due to no follow up.

**Closed by hramos** 2019-01-29 20:53 UTC
Labels: Bug Report, Resolution: Needs More Information
