### ISSUE TITLE
cmd + m and rr is not working in the android emulator

### ISSUE THREAD

**Issue by sarath-rp** [facebook/react-native#18515] opened 2018-03-23 06:01 UTC
- [ ] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.9.4
  Yarn: 1.5.1
  npm: 4.6.1
  Watchman: Not Found
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: ^0.54.2 => 0.54.2
## Expected Behavior
cmd + m want to show a menu and rr to refresh

## Actual Behavior
nothing happened

**Comment by scriptum** [comment] 2018-03-24 20:02
Same thing on Linux. I'm afraid that this is emulator bug.

**Comment by RodrigoWP** [comment] 2018-07-08 18:42
I had the same problem.
Recently I've installed **VMWare** and as it creates your virtual host, so what's happing is when I start npm start it uses the virtual host instead of the normal internet connection. So basically they are using different networks thus rn server(or expo) can't connect to the app.
One solution that I did was to disable another network adapters, so I just restart the server and it back works out well again

**Comment by laidlow** [comment] 2018-07-10 05:11
Had the same problem the last few days - RR just randomly stopped refreshing the app in the emulator. Seems like an emulator bug, I recreated the AVD instance and the problem was resolved.

**Comment by BenQoder** [comment] 2018-07-17 18:15
I Fixed This By Clear The Expo App Data From Android Settings, And Making Sure The App Is In Development
<img width="641" alt="Expo Debug Menu" src="https://user-images.githubusercontent.com/24754078/42837320-ae6a5730-89f5-11e8-8fe5-06d28eec5158.png">
 Mode

**Comment by Hypothesis-github** [comment] 2018-09-11 22:46
This issue still exists

**Comment by Oscarteg** [comment] 2018-11-02 10:51
Same issue here @johnroest

**Comment by sryze** [comment] 2018-11-03 09:31
Same problem

```
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 11.0.0
  Yarn: 1.12.1
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.2 AI-181.5540.7.32.5056338

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4
```

**Comment by michalchudziak** [comment] 2019-03-19 16:40
Hello there 👋 by using the repro / the list of steps to reproduce, we can't actually see the reported bug on RN 0.59 so we'll close this issue. It may have something to do with your local setup, please double check that you are using the correct version of Android Studio / XCode / Android NDK / Yarn / etc.

**Closed by michalchudziak** 2019-03-19 16:40 UTC
Labels: Platform: Android, Type: Bug Report

**Comment by souhaiebtar** [comment] 2019-04-05 10:21
for me, to resolve it, i uninstalled the expo app from the android emulator and run the app again

**Comment by AndrewMorsillo** [comment] 2019-06-03 19:48
This is happening to me on MacOS. Uninstalling and reinstalling the app didn't help. Rebooting the emulator didn't help. Clearing emulator data didn't help. Cold booting emulator didn't help. Not really sure what to do from here, I can't debug Android!

**Comment by JacobTBralish** [comment] 2019-10-11 06:14
I am currently running into this same issue running RN 0.60.4

**Comment by mstosio** [comment] 2019-10-23 10:15
If you are using Expo, make sure you are not using Production Mode.

**Comment by JacobTBralish** [comment] 2019-11-09 21:25
> If you are using Expo, make sure you are not using Production Mode.

I'm not using Expo. Just the cli.

**Comment by raldred** [comment] 2020-01-08 18:01
Same using 0.61. Not using expo but am using react-native-webview which does appear to steal focus when pressing R

**Comment by lucasR23** [comment] 2020-01-31 10:35
Same error here i am not using expo i am only using the cli

**Comment by raldred** [comment] 2020-01-31 11:00
Make sure you're not building a release version, the shortcuts are only
available in a debug build
