### ISSUE TITLE
Android Picker Not Consistently Firing onValueChange

### ISSUE THREAD

**Issue by ghost** [facebook/react-native#15556] opened 2017-08-18 18:43 UTC
### Is this a bug report?

Yes. I have also seen this issue on [stackoverflow](https://stackoverflow.com/questions/45292719/picker-onvaluechange-not-being-called-on-every-selection).

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: 2.0.1
2. `node -v`: v8.0.0
3. `npm -v`: 5.0.0
4. `yarn --version`: 0.24.5

- Target Platform: Android
- Development Operating System: macOS
- Build tools: N/A

### Steps to Reproduce

Using the Picker component in Android, the first `onValueChange` fires, but the next one does not. The one after does...this continues and results in about 33% of the time `onValueChange` does not fire.

I created a [snack](https://snack.expo.io/BJI5J2Edb) with a basic example.

### Expected Behavior

I expected `onValueChange` to fire if the Picker item selected is different from the current selection.

### Actual Behavior

About 33% of the time `onValueChange` will not fire, but the text on the Picker does change, which is confusing to the user. The other times, everything works as expected.

### Reproducible Demo

I created a [snack](https://snack.expo.io/BJI5J2Edb) with a basic example. Select one option, then another and, in my experience, it will not consistently log to console.

**Comment by mell0kat** [comment] 2017-09-06 21:30
I am currently experiencing this error too, with about the same 33% statistic.

**Comment by dragos-panaitescu** [comment] 2017-09-28 15:10
I also have exactly the same problem. Any solutions / workarounds?

**Comment by daniel-coman** [comment] 2017-10-12 14:25
Unfortunately I have the same problem. Has anyone found any solution to resolve this behavior? Or at least an workaround.

**Comment by connercms** [comment] 2017-10-12 17:55
+1 encountering this bug in two separate applications. happens about every other selection

**Comment by aligfl** [comment] 2017-10-16 03:52
+1 seeing the exact same thing :(. any resolutions to this problem?

**Comment by akavy** [comment] 2017-10-24 13:37
+1 Unbelievable that this error occurs. Do I have to try and rewrite my app not using the Picker just so that it will reliable? Crazy world. Any workarounds would be appreciated.

**Comment by jorgetolentinog** [comment] 2017-11-02 21:56
did you try adding a state? demo: https://snack.expo.io/r1JfNfKRZ

**Comment by laurent22** [comment] 2017-11-03 17:39
Still happening in 0.49. Honestly this Picker component should be removed from the doc or marked as "alpha", as it simply doesn't work and shouldn't be relied on. If I had known from the start that it was broken, I could have used a third party picker or make my own.

**Comment by tombailey** [comment] 2017-11-06 09:11
Can anyone point to a related commit that might have broken this? I can probably look at this if someone can point me in the right directions

**Comment by sandropoluan** [comment] 2017-11-11 10:16
+1
Same problem... in RN 0.48.1

**Comment by sandropoluan** [comment] 2017-11-11 10:26
Adding setState inside the function seems solved my problem...
```
<Picker  mode='dropdown' onValueChange={ (itemValue,itemIndex)=>{
                this.setState({
                	random:Math.random(),
                });
                //do your stuff here
}}>
```

**Comment by tombailey** [comment] 2017-11-13 15:28
FYI: tested on 'left hand'/'right hand' example above and this appears to be fixed on master; no idea which commit actually fixed it

**Comment by vbhv19** [comment] 2017-11-22 06:03
+1 any workaround for this?

**Comment by YJ1007** [comment] 2017-11-22 06:04
+1 Any temporary workaround around this problem ??

**Comment by sandropoluan** [comment] 2017-11-22 21:59
I just notice that this issue happen where there is **no setState** inside the callback.

issue happen with these typical code
```
onValueChange={value => {
               console.log(value)
              //and go on but without setState
 }}
```
OR
```
onValueChange={value => {
               run_some_function(value)
 }}
```

my workaround is added a setState

```
onValueChange={value => {
              this.setState({
                  random:Math.Random()
               });
               console.log(value)
              
 }}
```

OR

```
onValueChange={value => {
              this.setState({
                  random:Math.Random()
               });
               run_some_function(value)
 }}
```

**Comment by ThaJay** [comment] 2017-11-27 15:19
@tombailey any chance you are able to figure out what the commit was so it can be proposed for the next release?

adding `setState` to `onValueChange` does not work because `onValueChange` is not called half of the times.

**Comment by tombailey** [comment] 2017-11-27 16:00
@ThaJay I have looked but I have no idea which commit resolved this. I didn't do an upgrade on my project, I just created a new one with the example above and pointed at the latest version of RN. Can someone else verify it works for them too?

**Comment by ThaJay** [comment] 2017-11-27 17:14
I just made a test project and was unable to reproduce:
https://github.com/ThaJay/react-native-picker-test
It worked in the same version I have this problem with in the app.
Not a clue what went wrong yet.

**Comment by ThaJay** [comment] 2017-11-28 13:06
Further testing learns that the behavior does not change on the latest version (v0.50.4)
I just updated my project and the picker fires `onValueChange` exactly half the time, while the view element actually updates (but it should not because onValueChange sets the state it depends on).

As stated above I was unable to reproduce this in an empty project but I'm still stunned as of how this can happen and it's a blocking bug for the next release that's waiting to be approved.

**Comment by ThaJay** [comment] 2017-11-28 13:43
I added redux to the test repo and was still unable to reproduce
https://github.com/ThaJay/react-native-picker-test

**Comment by tombailey** [comment] 2017-11-28 14:22
@ThaJay given that this is Android specific and seems to happen 50% of the time, I am inclined to blame https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/picker/ReactPicker.java#L133

mSuppressNextEvent in particular

I don't have the time to look at this properly so if anyone else does that would be great.

**Comment by ThaJay** [comment] 2017-11-28 16:46
Thank you for the insight.
I'm trying to compile react-native to try what happens without `mSuppressNextEvent` but I'm stuck at this error: (never done this before)
```
/android/app/src/main/java/com/chipta/MainApplication.java:5: error: package com.facebook.react does not exist
import com.facebook.react.ReactApplication;
```

**Comment by ThaJay** [comment] 2017-11-29 12:15
If I disable `mSuppressNextEvent` in ReactPicker it does seem to work.
It also works if I use state and no redux in our app (but adding redux did not reproduce in the test app).

So there must be something going wron with the re-render

**Comment by ThaJay** [comment] 2017-11-29 14:57
I have found the folowing workaround using `componentDidUpdate`:
```js
  constructor (props) {
    super(props)
    this.state = {value:this.props.eventId}
  }

  componentDidUpdate () {
    if (this.props.eventId !== this.state.value) {
      this.props.chooseEvent(this.state.value)
    }
  }

  onValueChange = value => {
    this.setState({value})
  }
```
with
```js
          <Picker
            selectedValue={this.state.value}
            onValueChange={this.onValueChange}
          >
```

**Comment by sandropoluan** [comment] 2018-01-14 22:43
This issue still happening until this days... unbelievable!

**Comment by diegolaciar** [comment] 2018-01-22 16:21
+1 fix for this. The same issue with Android Picker.

**Comment by tombailey** [comment] 2018-01-24 09:45
For anyone still having issues with this, you might be interested in https://github.com/tombailey/react-native-fixed-android-picker as a work around

**Comment by diegolaciar** [comment] 2018-01-24 16:00
I found a solution. I my case i was using redux-form. 
Looks like this component must use state and setState.

something like..

Note this lines: 
  **this.setState({ itemValue });**
  onChange(itemValue);

```javascript
constructor(props) {
    super(props);
    this.state = { itemValue: this.prop.initialSelectedValue };
  }
render () {
const {
      input: { value, onChange, ...inputProps },
    } = this.props;
return (
       <Picker
          selectedValue={this.state.itemValue}
          onValueChange={itemValue => {
            this.setState({ itemValue });
            onChange(itemValue);
          }}
          {...inputProps}
        >
);
}
```

Cheers

**Comment by toussa** [comment] 2018-01-25 11:26
I struggled with this problem during several hours and @diegolaciar 's workaround works !

It may be related how the Picker handles the render process, and in which order it updates its internal selected value.
Indeed, it looks like the internal selected value is updated before the check to know if the value has changed or not.

Well, at least we have a workaround now :) Thanks again diego

**Comment by AliZeynalov** [comment] 2018-01-28 18:30
add width property of style to picker and it will work.

**Comment by leoskyrocker** [comment] 2018-01-29 10:06
@diegolaciar's workaround works!!!!! (We're using redux-form too.)
THANKS. I thought it's the end of the world.

**Comment by lincoln00** [comment] 2018-02-18 21:27
I was having the same problem, even using setState on onValueChange and selectedValue with state, like this:

onValueChange={(itemValue, itemIndex) => this.setState({city: itemValue})}
selectedValue={this.state.city}

I just reversed the order in the code for this:

selectedValue={this.state.city}
onValueChange={(itemValue, itemIndex) => this.setState({city: itemValue})}

now working (don't ask why)

**Closed** 2018-02-24 03:27 UTC
Labels: Ran Commands

**Comment by sandropoluan** [comment] 2018-02-27 01:47
This problem still exist on 0.53.x. Somebody please reopen this issue.

**Comment by leoskyrocker** [comment] 2018-02-27 02:21
It seems that the instruction says to open a new issue.

**Comment by henninghall** [comment] 2018-02-27 13:18
Can confirm that this bug still exists in 0.53.0

**Comment by laurent22** [comment] 2018-02-27 13:23
Since this is still happening could the issue be re-opened? Creating a new issue is not ideal since they tend to be auto-closed quickly as less people are watching them.

**Comment by ThaJay** [comment] 2018-02-27 15:02
yes indeed my unwieldy workaround is still in place.

**Comment by jtovarnak** [comment] 2018-03-05 18:07
for those still experiencing this issue as we are, you can check [https://github.com/sleighdogs/react-native-android-native-picker](https://github.com/sleighdogs/react-native-android-native-picker) for a quick workaround.

The base is same as [tombailey's solution](https://github.com/facebook/react-native/issues/15556#issuecomment-359478181) but we needed to be able to set dialog title and have flexibility with what is displayed as picker component.

**Comment by baba43** [comment] 2018-03-24 13:14
I would really appreciate if someone might try to fix this issue. 

We have a workaround, but it is not good. For it is not working as soon as the component should be able to receive updates from Redux.

**Comment by AliaMYH** [comment] 2018-03-25 11:20
@diegolaciar I don't understand what the difference between your solution and the normal implementation of Picker, to be honest. Is it the onChange() ? or is that related to redux-form? Because the standard Picker also uses setState(). Not sure what i'm missing.

**Comment by ThaJay** [comment] 2018-03-28 10:08
@AliaMYH Take a look at my example too, both this.state and this.setState are needed to make it work. Anything else does not work. Props do not work.

**Comment by nhohb07** [comment] 2018-04-08 09:02
I working on React Native v0.54.0, this bug still appeared, the action onValueChange on Android does not fire when the user selected the first item on the picker.

**Comment by ThaJay** [comment] 2018-04-10 12:40
I'm on react-native 0.55.0 and the issue is back even with my workaround. What do I do now? :/

**Comment by tombailey** [comment] 2018-04-10 13:24
@ThaJay until the root cause is determined and fixed, you probably want to try https://github.com/facebook/react-native/issues/15556#issuecomment-360076047

**Comment by ThaJay** [comment] 2018-04-11 09:11
@tombailey I had a similar workaround in place. https://github.com/facebook/react-native/issues/15556#issuecomment-347885494
It stopped working.
So I decided I am done with this picker component and built my own. Easy peasy, some stuff with a 
TouchableOpacity and a Modal with a list.

**Comment by tombailey** [comment] 2018-04-11 11:53
@ThaJay the solution I posted isn't a "workaround" in the same way your's was. It does actually what you propose "TouchableOpacity and a Modal with a list".

**Comment by ThaJay** [comment] 2018-04-11 15:28
@tombailey Oh sorry, I thought you meant @diegolaciar's post below yours. That contains the same workaround.

Your repo is indeed similar to what I built yesterday. It's nice to have control over styling, isn't it? Finally my picker dialog is dark in night mode. :+1:

**Comment by sandropoluan** [comment] 2018-04-12 02:39
@hramos , can you reopen this issue?

**Comment by hungtranvupycogroup** [comment] 2018-04-12 16:39
I find this line https://github.com/facebook/react-native/blob/5001b9f39eb9c81ba9dc38ed00972954c7d325e4/Libraries/Components/Picker/PickerAndroid.android.js#L73
Can we start with selectedIndex = -1 ?

**Comment by jnadeauNn** [comment] 2018-05-28 14:41
I have the same issues.  I think this issues should be reopen. Thank you very much

**Comment by hafizalfaza** [comment] 2018-06-07 16:28
I use setTimeout to achieve it, it's a bit tricky but it works

`onValueChange={(itemValue, itemIndex) => { setTimeout(() => {this.onValueChange(itemValue, itemIndex)}, 10)}}`

**Comment by kigawas** [comment] 2018-09-27 08:19
Folks, I think it should be [used with state](https://github.com/facebook/react-native/issues/15556#issuecomment-360181487) instead of props like `this.props.value` in redux-form.

**Comment by akashanand708** [comment] 2018-11-27 03:44
> I use setTimeout to achieve it, it's a bit tricky but it works
> 
> `onValueChange={(itemValue, itemIndex) => { setTimeout(() => {this.onValueChange(itemValue, itemIndex)}, 10)}}`

It helped, thanks.

**Comment by tobibello001** [comment] 2019-01-08 20:10
@hafizalfaza Youu solution worked although i just needed to use:
`onValueChange={(itemValue, itemIndex) => { setTimeout(() => {this.onValueChange(itemValue, itemIndex)}, 0)}}`

I really don't understand how this works fine but the picker doesn't work well. my react-native version i s 0.57

**Comment by AdamZaczek** [comment] 2019-01-13 16:33
For people revisiting, @hafizalfaza 's solution is the way to go. Picker's onValueChange needs setTimeout or some other way of adding to event loop to work correctly

**Comment by 54vanya** [comment] 2019-01-16 10:21
Why is this even closed? Issue is still exist, @hafizalfaza 's solutions isn't that I really want to use in my life

**Comment by ThaJay** [comment] 2019-01-17 15:16
Then don't use it. I have had another Picker component in my app for ages. This is not likely to get fixed any time soon.

**Comment by AdamZaczek** [comment] 2019-01-17 23:45
What do you recommend @ThaJay ?

**Comment by ThaJay** [comment] 2019-01-18 15:09
I made my own. I think there was someone in this thread who made his own and published it as a module, but I just made a gist out of my code as an example of houw this could be done.
https://gist.github.com/ThaJay/80ee8647940e0cb753a9da67f55b14df

**Comment by NelGarbuzova** [comment] 2019-03-12 09:37
This issue still reproduces. Picker does not trigger `onValueChange` for first item when there is not selected value. Even if we set `selectedValue={-1}` or `selectedValue={null}` it does not trigger `onValueChange` for first item. So how we can define Picker without any pre-selected value?

**Comment by NelGarbuzova** [comment] 2019-03-12 10:32
Guys, I solved this problem with unselectable first item by setting fake unselectable item with value = -1. Then when user pick valid item,fake item with value = -1 dissapears.

```
<Picker
    selectedValue={this.state.selectedIndex}
    onValueChange={(value, index) => { this.setState({selectedIndex: index}) }}
>
    // first fake item
    if(Platform.OS === 'android' && this.state.selectedIndex === -1) {
        <PickerIOS label={'CANCEL'} value={-1} />
    }

    <Picker.Item label={'First'} value={1} />
    <Picker.Item label={'Second'} value={2} />
    <Picker.Item label={'Third'} value={3} />
</Picker>
```

**Comment by Rana-Muhammad-Amir** [comment] 2019-12-23 16:54
following code working fine on android but in "onValueChange" this.changeCityArray() not calling on IOS platform please help.....

<Select 
                  iosText={this.state.nok_state}
                  iosTouchStyle={styles.iosPickerStyle} 
                  onPress={() => showActionSheetState()} 
                  onValueChange={(itemValue, itemIndex) => ( this.changeCityArray(itemIndex), this.setState({nok_state: itemValue, key: itemIndex}) )} 
                  render={this.stateOptions} selectedValue={this.state.nok_state} style={styles.pickerStyle} 
                />

**Comment by bjmiao** [comment] 2020-05-17 07:28
> 
> 
> I use setTimeout to achieve it, it's a bit tricky but it works
> 
> `onValueChange={(itemValue, itemIndex) => { setTimeout(() => {this.onValueChange(itemValue, itemIndex)}, 10)}}`

Great! A little bit tricky but it works xd
Can someone explain why it works?
