### ISSUE TITLE
FlatList scrollToIndex() dont work without specifying the getItemLayout prop

### ISSUE THREAD

**Issue by MichaelPintos** [facebook/react-native#15124] opened 2017-07-20 19:24 UTC
# React native version 0.45.1

![quickmemo _2017-07-20-15-17-23](https://user-images.githubusercontent.com/26886974/28435008-cd691aa0-6d67-11e7-8d74-3bb7120650df.png)

**Comment by hramos** [comment] 2017-07-20 20:27
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-07-20 20:27 UTC

**Comment by MichaelPintos** [comment] 2017-07-21 12:21
No problem I will reproduce the error in a clean project. Thank you
