### ISSUE TITLE
Unable to run my first demo app shows me fatal error

### ISSUE THREAD

**Issue by vnanaware** [facebook/react-native#25709] opened 2019-07-18 10:55 UTC
when I run my app on mac for ios

#import <React/RCTBridgeDelegate.h>

Fatal error: 'React/RCTBridgeDelegate.h' file not found

Please help how to resolve this?

Using versions
React Native version 0.60
Xcode: 10.2
<img width="909" alt="Screen Shot 2019-07-18 at 4 24 13 PM" src="https://user-images.githubusercontent.com/16416191/61452088-960b3f80-a978-11e9-94e1-1f895fb12ecc.png">

**Comment by rszalski** [comment] 2019-07-18 18:42
@vnanaware Please close this issue as it’s a direct duplicate of https://github.com/facebook/react-native/issues/25707

**Comment by vnanaware** [comment] 2019-07-19 04:38
IBSs-iMac:AwesomeProject ibs$ react-native info
info Fetching system and libraries information...
System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
    Memory: 1.93 GB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
  IDEs:
    Xcode: 10.2/10E125 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.3 => 0.60.3 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1

**Comment by slavikdenis** [comment] 2019-07-19 12:26
Duplicate of https://github.com/facebook/react-native/issues/25707

**Closed** 2019-07-31 11:46 UTC
Labels: Bug, Ran Commands, Resolution: Missing Environment Info
