### ISSUE TITLE
Module `AccessibilityInfo` does not exist in  the Haste module map

### ISSUE THREAD

**Issue by anothercoder2** [facebook/react-native#20331] opened 2018-07-21 18:50 UTC
- [ ] Review the documentation: https://facebook.github.io/react-native
  - [ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.

## Description
Describe your issue in detail. Include screenshots if needed. If this is a regression, let us know.

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, share a project, or     share an app that reproduces the issue using https://snack.expo.io/. Please follow the guidelines for providing a MCVE: https://stackoverflow.com/help/mcve

**Comment by anothercoder2** [comment] 2018-07-21 18:59
Created new react app  with react-native init julyapp02
Did npm install 
On running the app using react-native run-android I get the following issue

Module `AccessibilityInfo` does not exist in the Haste module map


My react native info:

C:\JS\react\nativetest\julyapp02>react-native info
Scanning folders for symlinks in C:\JS\react\nativetest\julyapp02\node_modules (28ms)

  React Native Environment Info:
    System:
      OS: Windows 8.1
      CPU: x64 Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz
      Memory: 4.66 GB / 11.88 GB
    Binaries:
      Yarn: 1.6.0 - C:\Users\Milind\AppData\Roaming\npm\yarn.CMD
      npm: 6.1.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4697961

Environment info

C:\JS\react\nativetest\julyapp02>node -v
v8.11.1

C:\JS\react\nativetest\julyapp02>react-native -v
react-native-cli: 2.0.1
react-native: 0.56.0

C:\JS\react\nativetest\julyapp02>npm -v
6.1.0

**Comment by leo-tavares** [comment] 2018-07-23 03:20
Hello anothercoder2!

react-native 0.56.0 is broken in Windows plataform, please use 0.55.4

comand -> `react-native init myApp --version 0.55.4`

**Comment by leo-tavares** [comment] 2018-07-23 03:22
I also had this problem! We have to wait for the next update, probably version 0.56.1 should correct this problem

**Comment by zmerchant17** [comment] 2018-07-23 04:52
@leo-tavares has the correct solution, you can also try downgrading babel if that doesn't work. Agreed, hopefully 56.1 solves the issue as I'm having the same problem.

**Comment by kelset** [comment] 2018-07-23 09:35
Duplicate of https://github.com/facebook/react-native/issues/19953

**Closed by kelset** 2018-07-23 09:35 UTC

**Comment by dzilva** [comment] 2018-07-26 19:17
@leo-tavares great! you make my day buddy. I have same issue and now it's fixed!

**Comment by nnabueze** [comment] 2018-07-28 21:45
@leo-tavares great! 0.56.0 is broken..react-native init myApp --version 0.55.4 worked
