### ISSUE TITLE
[0.75] Broken border with specific border radius on TextInput

### ISSUE THREAD

**Issue by Titozzz** [facebook/react-native#47156] opened 2024-10-22 12:57 UTC
### Description

When applying specific borderRadius on <TextInput>, for example bottomRight, the actual affected corner will be the one next counter clockwise (top right instead of bottom right; top left instead of top right, etc...)

This is a regression from 0.74 and it is fixed in 0.76 so there is already a fix somewhere, it would just need to be found and backported to 0.75.

This happens on both architectures.

### Steps to reproduce

Run the android app for the reproducer

### React Native Version

0.75.4

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.5
  CPU: (10) arm64 Apple M2 Pro
  Memory: 92.78 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.12.2
    path: /usr/local/bin/node
  Yarn:
    version: 3.6.4
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.5.0
    path: /usr/local/bin/npm
  Watchman:
    version: 2024.10.07.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/thibault/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.15989.150.2411.11948838
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 3.1.2
    path: /Users/thibault/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: true
```
```


### Stacktrace or Logs

```text
Irrelevant
```

### Reproducer

https://github.com/Titozzz/textinputborderradius

**Comment by Titozzz** [comment] 2024-10-23 12:47
I'm on old arch and haven't noticed any issue with iOS. Also in our app we do not apply borders to Text directly so we haven't noticed the bug but I would not be surprised that it's broken too

**Comment by delphinebugner** [comment] 2024-10-23 13:07
Tested on 0.76.0-rc.6 + New Arch, it's both okay 🙂 

<img width="758" alt="image" src="https://github.com/user-attachments/assets/72215873-64b2-4531-a48d-3b17dd5f5e9b">

- Text present on iOS
- Radius at expected position on Android

**Comment by NickGerleman** [comment] 2024-10-23 16:59
We rebuilt a lot of the infrastructure for Android backgrounds and clipping in 0.76, but the whole set of changes would unfortunately be hard to back port.

**Comment by cortinico** [comment] 2024-10-23 18:19
> This is a regression from 0.74 and it is fixed in 0.76 so there is already a fix somewhere, it would just need to be found and backported to 0.75.

Closing as per @NickGerleman comment

**Closed by cortinico** 2024-10-23 18:19 UTC
Labels: Issue: Author Provided Repro, Component: TextInput

**Comment by 1880akshay** [comment] 2024-11-07 10:02
@cortinico , can we release a patch version for 0.75.x considering this is a critical bug? We have a production app and upgrading to RN76 is not possible at the moment.

**Comment by cortinico** [comment] 2024-11-07 15:06
> @cortinico , can we release a patch version for 0.75.x considering this is a critical bug? We have a production app and upgrading to RN76 is not possible at the moment.

As @NickGerleman already pointed out, this is not easy to backport. You'll have to upgrade to 0.76 to have this fixed

**Comment by NickGerleman** [comment] 2024-11-08 00:26
There might end up being a simple fix here, depending on the issue. All the changes from 0.76 cannot be back ported though. I did a quick scan of changes in ReactEditText and uimanager to see if I could spot relevant change, and didn’t see it though.

I would recommend bisecting nightly builds, to find where the regression started. A revert of that commit could maybe be picked depending on the root cause.
