### ISSUE TITLE
Creating or upgrading to React Native v0.70.0 is broken - unresolved dependancy, and duplicates

### ISSUE THREAD

**Issue by SuperRoach** [facebook/react-native#34602] opened 2022-09-06 06:53 UTC
### Description

It's not possible to init a project with v0.70.0 currently. There is an error starting it with npx react-native init. 

When the request to download react-native@0.70.0 happens, it will then fail.

### Version

0.70.0

### Output of `npx react-native info`

npx react-native info also fails with the same error, after it asks to install v.070.
However, it is a MacOS 12.5.1, Intel machine, Node 16.13.2, zsh shell,
Node 16.13.2 - /Users/brett/.nvm/versions/node/v16.13.2/bin/node
Yarn - 1.22.19

### Steps to reproduce

After following the steps to install paths and java etc, create a new folder, then run:
`npx react-native init test`

Output will be:

```
Need to install the following packages:
  react-native@0.70.0
Ok to proceed? (y) y
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react-native@0.66.4


```

### Snack, code example, screenshot, or link to a repository

Full example of output:

```
brett@Bretts-MBP testfolder% npx react-native init rntest
Need to install the following packages:
  react-native@0.70.0
Ok to proceed? (y) y
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react-native@0.66.4
npm ERR! node_modules/react-native
npm ERR!   peer react-native@"*" from @react-native-community/cli@6.2.0
npm ERR!   node_modules/@react-native-community/cli
npm ERR!     @react-native-community/cli@"^6.0.0" from react-native@0.66.4
npm ERR!   react-native@"0.70.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! react-native@"0.70.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@18.1.0
npm ERR! node_modules/react
npm ERR!   peer react@"18.1.0" from react-native@0.70.0
npm ERR!   node_modules/react-native
npm ERR!     react-native@"0.70.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/brett/.npm/eresolve-report.txt for a full report.
```

The full report follows:
```

# npm resolution error report

2022-09-06T06:55:05.111Z

While resolving: undefined@undefined
Found: react-native@0.66.4
node_modules/react-native
  peer react-native@"*" from @react-native-community/cli@6.2.0
  node_modules/@react-native-community/cli
    @react-native-community/cli@"^6.0.0" from react-native@0.66.4
  react-native@"0.70.0" from the root project

Could not resolve dependency:
react-native@"0.70.0" from the root project

Conflicting peer dependency: react@18.1.0
node_modules/react
  peer react@"18.1.0" from react-native@0.70.0
  node_modules/react-native
    react-native@"0.70.0" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

Raw JSON explanation object:

{
  "code": "ERESOLVE",
  "edge": {
    "type": "prod",
    "name": "react-native",
    "spec": "0.70.0",
    "error": "INVALID",
    "from": {
      "location": "/Users/brett/.npm/_npx/7930a8670f922cdb"
    }
  },
  "dep": {
    "name": "react-native",
    "version": "0.70.0",
    "whileInstalling": {
      "path": "/Users/brett/.npm/_npx/7930a8670f922cdb"
    },
    "location": "node_modules/react-native",
    "isWorkspace": false,
    "dependents": [
      {
        "type": "prod",
        "name": "react-native",
        "spec": "0.70.0",
        "error": "INVALID",
        "from": {
          "location": "/Users/brett/.npm/_npx/7930a8670f922cdb"
        }
      }
    ]
  },
  "current": {
    "name": "react-native",
    "version": "0.66.4",
    "location": "node_modules/react-native",
    "isWorkspace": false,
    "dependents": [
      {
        "type": "peer",
        "name": "react-native",
        "spec": "*",
        "from": {
          "name": "@react-native-community/cli",
          "version": "6.2.0",
          "location": "node_modules/@react-native-community/cli",
          "isWorkspace": false,
          "dependents": [
            {
              "type": "prod",
              "name": "@react-native-community/cli",
              "spec": "^6.0.0",
              "from": {
                "name": "react-native",
                "version": "0.66.4"
              }
            }
          ]
        }
      },
      {
        "type": "prod",
        "name": "react-native",
        "spec": "0.70.0",
        "error": "INVALID",
        "from": {
          "location": "/Users/brett/.npm/_npx/7930a8670f922cdb"
        }
      }
    ]
  },
  "peerConflict": {
    "current": {
      "name": "react",
      "version": "17.0.2",
      "location": "node_modules/react",
      "isWorkspace": false,
      "dependents": [
        {
          "type": "peer",
          "name": "react",
          "spec": "17.0.2",
          "from": {
            "name": "react-native",
            "version": "0.66.4",
            "location": "node_modules/react-native",
            "isWorkspace": false,
            "dependents": [
              {
                "type": "peer",
                "name": "react-native",
                "spec": "*",
                "from": {
                  "name": "@react-native-community/cli",
                  "version": "6.2.0",
                  "location": "node_modules/@react-native-community/cli",
                  "isWorkspace": false,
                  "dependents": [
                    {
                      "type": "prod",
                      "name": "@react-native-community/cli",
                      "spec": "^6.0.0",
                      "from": {
                        "name": "react-native",
                        "version": "0.66.4"
                      }
                    }
                  ]
                }
              },
              {
                "type": "prod",
                "name": "react-native",
                "spec": "0.70.0",
                "error": "INVALID",
                "from": {
                  "location": "/Users/brett/.npm/_npx/7930a8670f922cdb"
                }
              }
            ]
          }
        },
        {
          "type": "peer",
          "name": "react",
          "spec": "^16.8.0 || ^17.0.0",
          "from": {
            "name": "use-subscription",
            "version": "1.5.1",
            "location": "node_modules/use-subscription",
            "isWorkspace": false,
            "dependents": [
              {
                "type": "prod",
                "name": "use-subscription",
                "spec": "^1.0.0",
                "from": {
                  "name": "react-native",
                  "version": "0.66.4",
                  "location": "node_modules/react-native",
                  "isWorkspace": false,
                  "dependents": [
                    {
                      "type": "peer",
                      "name": "react-native",
                      "spec": "*",
                      "from": {
                        "name": "@react-native-community/cli",
                        "version": "6.2.0",
                        "location": "node_modules/@react-native-community/cli",
                        "isWorkspace": false,
                        "dependents": [
                          {
                            "type": "prod",
                            "name": "@react-native-community/cli",
                            "spec": "^6.0.0",
                            "from": {
                              "name": "react-native",
                              "version": "0.66.4"
                            }
                          }
                        ]
                      }
                    },
                    {
                      "type": "prod",
                      "name": "react-native",
                      "spec": "0.70.0",
                      "error": "INVALID",
                      "from": {
                        "location": "/Users/brett/.npm/_npx/7930a8670f922cdb"
                      }
                    }
                  ]
                }
              }
            ]
          }
        }
      ]
    },
    "peer": {
      "name": "react",
      "version": "18.1.0",
      "whileInstalling": {
        "path": "/Users/brett/.npm/_npx/7930a8670f922cdb"
      },
      "location": "node_modules/react",
      "isWorkspace": false,
      "dependents": [
        {
          "type": "peer",
          "name": "react",
          "spec": "18.1.0",
          "from": {
            "name": "react-native",
            "version": "0.70.0",
            "whileInstalling": {
              "path": "/Users/brett/.npm/_npx/7930a8670f922cdb"
            },
            "location": "node_modules/react-native",
            "isWorkspace": false,
            "dependents": [
              {
                "type": "prod",
                "name": "react-native",
                "spec": "0.70.0",
                "error": "INVALID",
                "from": {
                  "location": "/Users/brett/.npm/_npx/7930a8670f922cdb"
                }
              }
            ]
          }
        }
      ]
    }
  },
  "strictPeerDeps": false,
  "force": false,
  "isMine": true
}
```

**Comment by Parkjunwu** [comment] 2022-09-06 19:04
I also have same problem!
Command "npx react-native init ProjectName" doesn't work.

**Comment by ishrodeveloper** [comment] 2022-09-09 07:59
Update your npm to latest then create your project.
`npm update -g`

**Comment by RifqiSubchan02** [comment] 2022-09-11 12:02
Try `npm config set legacy-peer-deps true`

**Comment by cortinico** [comment] 2022-09-16 13:26
Closing as a duplicate of https://github.com/facebook/react-native/issues/34051 which is already answered

**Closed by cortinico** 2022-09-16 13:26 UTC
Labels: Needs: Triage :mag:

**Comment by tankhang1** [comment] 2023-01-10 03:31
![image](https://user-images.githubusercontent.com/74121720/211455670-1d838437-2b7d-4ddd-a250-c9e0347907c9.png)
I have a problem when using react-native version 0.70.6. I have tried all the solution above but it isn't working for me. I'm using windown 11

**Comment by tankhang1** [comment] 2023-01-10 03:38
> ![image](https://user-images.githubusercontent.com/74121720/211455670-1d838437-2b7d-4ddd-a250-c9e0347907c9.png) I have a problem when using react-native version 0.70.6. I have tried all the solution above but it isn't working for me. I'm using windown 11

I have solved this problem by deleting all folder in C:\Users\Doan Tan Khang\AppData\Roaming\npm\node_modules
