### ISSUE TITLE
[0.64.0-rc.1] - KeyboardAvoidingView freezes ios app when wrapped around a scrollview

### ISSUE THREAD

**Issue by owinter86** [facebook/react-native#30495] opened 2020-11-29 20:11 UTC
## Description

When a KeyboardAvoidingView is wrapped around a ScrollView with `behavior="height"` and the scrollview has contents that has a scrollable height > device height, focussing a text input will freeze app on ios, I cannot test on android at the moment so can only confirm the issue on iOS.

## React Native version:
```
System:
    OS: macOS 11.0.1
    CPU: (8) x64 VirtualApple @ 2.50GHz processor
    Memory: 119.02 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.1 - /var/folders/wr/9smsws7s7fz53bs2905q080h0000gn/T/yarn--1606680389084-0.9742257659131075/node
    Yarn: 1.22.10 - /var/folders/wr/9smsws7s7fz53bs2905q080h0000gn/T/yarn--1606680389084-0.9742257659131075/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /Users/oliverwinter/.rvm/gems/ruby-2.6.1/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.0-rc.0 => 0.64.0-rc.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce

The following snippet can be used to replicate the issue.

```
import React from 'react';
import {
  KeyboardAvoidingView,
  SafeAreaView,
  ScrollView,
  TextInput,
  View,
} from 'react-native';

const App = () => {
  return (
    <SafeAreaView>
      <KeyboardAvoidingView behavior="height">
        <ScrollView>
          <TextInput
            placeholder="Placeholder text"
            style={{height: 50, fontSize: 20}}
          />
          <View style={{height: 2000, backgroundColor: 'red'}} />
        </ScrollView>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
};

export default App;
```

**Comment by alloy** [comment] 2020-12-07 15:34
@owinter86 Have you learned more about this issue by now, by any chance?

**Comment by owinter86** [comment] 2020-12-07 15:52
Hey @alloy, but its related to some infinite callback loop generated on the native side, and is specific to `<KeyboardAvoidingView behavior="height">` as passing and position behaviour works fine. 

```
Please report: Excessive number of pending callbacks: 501. Some pending callbacks that might have leaked by never being called from native code: {"148":{"module":"UIManager","method":"configureNextLayoutAnimation"},"150"......
```

**Comment by owinter86** [comment] 2020-12-07 16:06
@alloy I do have some time now to look a bit more into it and find the commit that causes the issue, but at the moment this is what is causing the infinite loop in the Component

https://github.com/facebook/react-native/blob/b08fff6f869e00c20c0dcdf7aca71284c2f276f0/Libraries/Components/Keyboard/KeyboardAvoidingView.js#L109-L133

**Comment by owinter86** [comment] 2020-12-07 16:35
@alloy the issue was introduced in this commit https://github.com/facebook/react-native/commit/b08fff6f869e00c20c0dcdf7aca71284c2f276f0,

The issue is that onLayout event is fired multiple times and the `layout.y` value for the native event is different each time, which then flows into the setState for height getting updated multiple times, with different values, which then trigger the onLayout again..... infinite loop.

So the issue seems to stem from the onLayout events, and I am not sure if we can revert this commit in 64 due to the `Fabric has different order of events` comment in the commit message.

**Comment by alloy** [comment] 2020-12-07 19:24
Thanks so much! We'll discuss what to do about this 👍

**Comment by Ashoat** [comment] 2020-12-10 18:23
What's confusing me about b08fff6f869e00c20c0dcdf7aca71284c2f276f0 is this line:

> In Fabric, `keyboardWillChangeFrame` event is fired before `onLayout`, but in Paper it is the other way around.

From my experimenting, the order of these events in React Native 0.63 is:

1. First `onLayout` is triggered, before any `TextInput` is pressed
2. After the `TextInput` is pressed a keyboard event is triggered. This keyboard event results in a `setState` call
3. The `setState` call results in a re-render of `KeyboardAvoidingView`, which results in `onLayout` being called again

(The issue we're seeing both here and in #30532 comes from the fact that there is now a `setState` call in `onLayout`, which triggers another layout, which triggers another `setState`, etc.)

But back to this quote:

> In Fabric, `keyboardWillChangeFrame` event is fired before `onLayout`, but in Paper it is the other way around.

My main question here is: after the first layout, assuming the parent component doesn't rerender, shouldn't a keyboard event always precede the `onLayout`? In what circumstances does a `onLayout` precede a keyboard event? The `onLayout` can't happen before the `setState`, right? If an `onLayout` occurs without a preceding keyboard event, can't we conclude that it has nothing to do with the keyboard, and instead must be in response to a ***parent component resizing***?

If b08fff6f869e00c20c0dcdf7aca71284c2f276f0 was indeed related to parent components resizing, I think I might have a solution.

I have a [customized `KeyboardAvoidingView`](https://github.com/Ashoat/squadcal/blob/master/native/components/keyboard-avoiding-view.react.js) in my project that has to deal with the edge case of a parent component resizing. We need to be able to differentiate between an `onLayout` that occurs in response to our own `setState` (in which case we should not change our calculations), and an `onLayout` that occurs in response to a parent resize (in which case the calculations need to be updated). The way we handle this is simply to ignore all `onLayout` calls that occurs while the keyboard is up (eg. after a "keyboard show" event occurs, but before a "keyboard hide" event occurs).

I think that sort of approach would work here, but it's hard to say without understanding the issue that b08fff6f869e00c20c0dcdf7aca71284c2f276f0 is addressing better.

**Comment by kelset** [comment] 2020-12-14 11:00
Let's cc in the author of the commit, maybe they'll be able to give more context: @sammy-SC

**Comment by sammy-SC** [comment] 2020-12-14 11:16
Hello @kelset, the fix is waiting for a review. 


Hello @Ashoat 

> First onLayout is triggered, before any TextInput is pressed

This is true unless TextInput has autofocus enabled. With autofocus enabled the order of events is different in Paper (old React native renderer) vs [Fabric](https://github.com/react-native-community/discussions-and-proposals/issues/4).

I hope this makes sense as I believe all of your other questions stem from the assumption that TextInput is tapped.


Apologies for the trouble.

**Comment by kelset** [comment] 2020-12-14 11:28
>  the fix is waiting for a review.

hey @sammy-SC, that's great to hear! I imagine it's an internal fix so there's no PR we can subscribe for updates to; can you post here the link to the commit on master after it lands? 🤗

**Comment by sammy-SC** [comment] 2020-12-14 12:10
@kelset yes, it is an internal fix. I will post the link here as soon as it is in master.

**Comment by Ashoat** [comment] 2020-12-14 16:14
Thanks for the explanation @sammy-SC!

I actually spent a good amount of time last month specifically looking into `autoFocus`/`KeyboardAvoidingView` behavior. Figured I'd share my notes here in case it's useful.

## My (contrasting) experience

I think my experience with React Native 0.63 (using Paper) is a little different. I've found that `TextInput` with `autoFocus={true}` will sometimes fire the keyboard event before the `onLayout` event. The result is that the `onLayout` gets the wrong value for `_initialFrameHeight` (since it's already adjusted for the keyboard).

## My "fix" (hack)

My fix has been simply to [avoid `autoFocus`](https://github.com/Ashoat/squadcal/blob/master/native/utils/timers.js#L17-L30) in these scenarios. In fact I've found that immediately calling `focus()` in a ref can also have the same issue. I've been able to avoid the issue with `requestAnimationFrame` (see experiment results below).

A separate issue I've had with `autoFocus={true}` when interacting with a keyboard has to do with the `Animated` library. I've found that it can lead to [fatal errors](https://github.com/facebook/react-native/issues/29768#issuecomment-728224490). In particular I've experienced this issue with React Navigation modals.

Last month I did some experimenting to see what the best approach would be for "autofocusing `TextInput` inside React Navigation modal". Figured I'd share my results here:

## Experiment results

**Notes:**
- the `Animated` issue (native exception) only repros in dev mode. I wasn’t able to reproduce it in prod mode
- emulator: Android 10, Pixel 3
- device: very old Android 4.4, Motorola Droid ULTRA (2013)
- ms values are time from ref being set to when focus is called

| method | avoids exception? | emulator try #1 | emulator try #2 | emulator try #3 | device try #1 | device try #2 | device try #3 |
| -- | -- | -- | -- | -- | -- | -- | -- |
| `autoFocus` | ❌ | N/A | N/A | N/A | N/A | N/A | N/A |
| focus in ref | ❌ |	0 | 0 | 0 | 0 | 0 | 0 |
| `setTimeout(50)` | ✅ | 462ms | 409ms | 540ms | 777ms | 2445ms | 1054ms |
| `setTimeout(0)` | ✅ |	236ms | 317ms | 304ms | 694ms | 702ms | 714ms |
| `waitForInteractions` | ✅ | 536ms | 487ms | 539ms | 2670ms | 2131ms | 2252ms |
| `requestAnimationFrame` | ✅ | 287ms | 258ms | 534ms | 728ms | 831ms | 733ms |
| `useEffect` equivalent | ✅ | 405ms | 240ms | 267ms | 623ms | 664ms | 694ms |

### Experiment analysis

Based on test results, the three leading candidates are `setTimeout(0)`, `requestAnimationFrame`, and `useEffect`. Some thoughts:

1. All three take about the same time to call.
2. I don't quite understand what causes this bug to occur, so it's hard to say which (if any) of these approaches are guaranteed to work on all devices.
3. The exception is related to React Native's `Animated` library. This makes me lean a little towards `requestAnimationFrame`, which the [React Native docs](https://reactnative.dev/docs/timers) say "will fire after all the frame has flushed".

## Long-term fix

If the [issue in `Animated`](https://github.com/facebook/react-native/issues/29768#issuecomment-728224490) is addressed, and we have a consistent order of events for `autoFocus={true}`, I think we could update `KeyboardAvoidingView` to handle this use case.

The thinking would be that if a keyboard event fires before an `onLayout`, then when setting `_initialFrameHeight` on the initial `onLayout`, we would adjust it based on the measurements in the keyboard event.

Not sure if this is what the aforementioned internal fix does.

**Closed** 2020-12-15 20:04 UTC
Labels: API: Keyboard, Component: KeyboardAvoidingView, Component: ScrollView, Needs: Triage :mag:, Platform: iOS

**Comment by sammy-SC** [comment] 2020-12-15 20:18
Here is the fix: https://github.com/facebook/react-native/commit/67309277fe588c4dd64fe0c680d1d00d2f3fb2b6

@Ashoat that's amazing! Thank you, that's definitely useful.
