### ISSUE TITLE
Will the old native modules work after enabling new architecture?

### ISSUE THREAD

**Issue by TheTushar2696** [facebook/react-native#35270] opened 2022-11-09 06:39 UTC
### Description

We are migrating to the new architecture, But happen to find that the NativeModules is coming as null, Is it expected?

### Version

0.70.2

### Output of `npx react-native info`

NA

### Steps to reproduce

NA

### Snack, code example, screenshot, or link to a repository

NA

**Comment by cortinico** [comment] 2022-11-25 14:47
> We are migrating to the new architecture, But happen to find that the NativeModules is coming as null, Is it expected?

Following up here, as question is really too generic.
Old NativeModules will keep on working. If you're getting null is most likely because you're accessing them in the wrong way.

**Comment by TheTushar2696** [comment] 2022-11-26 22:45
> > We are migrating to the new architecture, But happen to find that the NativeModules is coming as null, Is it expected?
> 
> Following up here, as question is really too generic. Old NativeModules will keep on working. If you're getting null is most likely because you're accessing them in the wrong way.

@cortinico 
Just FYI as I mentioned we are migrating from old architecture, NativeModules was working as expected in the old architecture but after making all the changes as per the documentation the build is successful but getting NativeModules as null, please throw some light here

Thanks in advance!

**Comment by TheTushar2696** [comment] 2022-11-28 07:54
@cortinico  Just a follow up on the above

**Comment by cortinico** [comment] 2022-11-28 11:05
> Just FYI as I mentioned we are migrating from old architecture, NativeModules was working as expected in the old architecture but after making all the changes as per the documentation the build is successful but getting NativeModules as null, please throw some light here

Please create a small reproducer explaining which API is returning you null. It's impossible to help you without any code.

**Comment by TheTushar2696** [comment] 2022-11-30 11:46
Hi @cortinico 
Ive created a [reproducer](https://github.com/TheTushar2696/NativeModulesReproducer) 

The above repository has a fresh react-native project (version: 0.70.6)
- Added a bridge to access some native methods via NativeModules

Repro steps:
- Set newArchEnabled false in gradle.properties
  Output: You will be able to access the method ABC imported from CustomModule.js 
- Set newArchEnabled true in gradle.properties
   Output: You will get an error 'TypeError: Cannot read property 'show' of null'

**Comment by cortinico** [comment] 2022-12-02 09:33
Hi @TheTushar2696 
Thanks for the reproducer.

From a first look, it seems like the problem you're facing is caused by you not having your package implements the `TurboReactPackage`. That is necessary in order to retain backward compatibility.

Specifically I invite you to take a look at our sample repo:
https://github.com/react-native-community/RNNewArchitectureLibraries

The file I mention is this one:
https://github.com/react-native-community/RNNewArchitectureLibraries/blob/feat/back-turbomodule/example-library/android/src/main/java/com/rnnewarchitecturelibrary/CalculatorPackage.java

By adapting your package, you'll be able to use your NativeModules seamelessly on either the new or old architecture.

**Comment by TheTushar2696** [comment] 2023-01-23 10:36
Hi @cortinico ,

I checked the repo shared and also the wrote one module, One question, Is it mandatory to create a separate package for turboModules, Because what I noticed is the package has its own package.json which defines codegenConfig, Lets say we have written 7,8 bridges which is getting read via NativeModules then we will have to create 7,8 different packages

**Comment by cortinico** [comment] 2023-01-23 11:46
Closing as this was answered

> I checked the repo shared and also the wrote one module, One question, Is it mandatory to create a separate package for turboModules, Because what I noticed is the package has its own package.json which defines codegenConfig, Lets say we have written 7,8 bridges which is getting read via NativeModules then we will have to create 7,8 different packages

Nope you can create a single package to return multiple Turbo Native Modules.

**Closed by cortinico** 2023-01-23 11:46 UTC
Labels: Type: Question, Type: New Architecture
