### ISSUE TITLE
Short lived TextView causing error "Trying to set local data for view with unknown tag: 4" on Android in RN 0.50.3

### ISSUE THREAD

**Issue by meros** [facebook/react-native#16821] opened 2017-11-14 15:03 UTC
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes
### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.3.0
  Yarn: 1.1.0
  npm: 5.4.2
  Watchman: 4.9.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: 3.0 AI-171.4408382

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.3 => 0.50.3

### Steps to Reproduce

1.
Create a view with a TextInput, make sure this view is showing when app is loaded but hidden quickly after (due to asynchronous event). 
2.
Let this app load in the android emulator
3.
Once in a while you get error "Trying to set local data for view with unknown tag: 4"

### Expected Behavior

I expect removing the TextInput shortly after app loading to work every time on Android without any errors

### Actual Behavior

There seems to be a race condition when starting up the app causing the error
![screenshot_1510671656](https://user-images.githubusercontent.com/450310/32786720-0612658e-c955-11e7-8150-96d3ecdca0d1.png)

### Reproducible Demo

Run this demo in the simulator. I have not  been able to reproduce this on a device

https://github.com/FranklyDev/react-native-0_50_3-android-bug-testcase

**Comment by meros** [comment] 2017-11-14 15:06
Please note that I can reproduce the error only maybe once/10 reloads or so.

**Comment by matthamil** [comment] 2017-11-14 20:50
I'm also experiencing this and probably for a similar reason but I can't easily reproduce it.

**Comment by wangghon** [comment] 2017-11-14 21:48
There is a change in 0.51.0-rc.1, no exception anymore.
https://github.com/facebook/react-native/commit/f2c6877b91963878f36ec42f5f865427bc69488c#diff-e40bcf61507821200dcf1f573eb717e3

**Comment by matthamil** [comment] 2017-11-14 22:00
That change isn't published to npm yet is it? Is the solution to compile RN from source? @wangghon

**Comment by wangghon** [comment] 2017-11-14 23:15
0.51.0-rc.1 is not published to npm yet. I think it would be soon. and I am also trying to change the java code on 0.50.3, but it seems the change does not take effects.  looking into the reason.

**Comment by arashmilani** [comment] 2017-11-15 16:21
Is there any other workaround other than compiling RN from source

**Comment by yaohongkok** [comment] 2017-11-20 14:15
@wangghon I am wondering when will '0.51.0-rc.1' be available officially on NPM?

**Comment by wangghon** [comment] 2017-11-20 21:37
@yaohongkok I am waiting for the release as well. Hope it can be released soon.

**Comment by thphu** [comment] 2017-11-29 12:57
I faced this problem when upgrade to react-native 0.50 :( but a little bit ( ... tag: 20) not sure it's relative but stacktrace is the same

**Comment by GitHubTracey** [comment] 2017-11-30 22:15
working with RN 0.50.4 and experiencing the same issue.

**Comment by ociata** [comment] 2017-12-02 15:23
Any workaround at least until it is merged?

**Comment by Jerameel** [comment] 2017-12-03 00:03
Having this issue on 50.4 using windows, error occured on both emulator and actual device

**Comment by arashmilani** [comment] 2017-12-03 00:08
I'm developing a redux-react-native app and as a workaround I just delay the rendering by some milliseconds between two states changes using a simple `setTimeout` while dispatching the next action.

**Comment by Jerameel** [comment] 2017-12-03 00:12
how would you know where to add the delay? I'm on redux now

**Comment by arashmilani** [comment] 2017-12-03 00:15
in my case it just happens in some particular action and specific scenario
 so I just delay dispatching that specific action.

**Comment by Tennen** [comment] 2017-12-03 03:02
I prevent updating the component after the action (in my case submit action) which may cause the component unmount

**Comment by Jerameel** [comment] 2017-12-03 03:26
setTimeout actually does the thing for me, so the issue is with the initial component immedietly invoking an action that triggers conditional rendering. Kudos to arasmilani for pointing that out

**Comment by ociata** [comment] 2017-12-03 09:47
If not using redux, how we could fix it? I tried conditionally rendering TextInput with timeout, without success - once inserting the TextInput(after 3 sec) it again fails:
```  
render() {

    let render = this.state.shouldRender ?
    <TextInput
      style={styles.search_text}
      placeholder="Type here to search!"
      onChangeText={(text) => this._onTextChanged(text)}
    /> :
    <View/>

    return <View style={styles.main_view}>
       <View style={styles.search_holder}>
         {render}
       </View>
       <View style={{flex:1}}>
         <ListView
           dataSource={this.state.dataSource}
           renderRow={this._renderListRow.bind(this)}/>
       </View>
     </View>
  }

  componentDidMount(){
    setTimeout(() => {

      this.setState({
        shouldRender: true
      })

    }, 3000)

  }
```

**Comment by GitHubTracey** [comment] 2017-12-07 22:27
latest release!
https://github.com/facebook/react-native/releases/tag/v0.51.0

**Comment by munkhorgil** [comment] 2017-12-17 15:01
I just got this error in Android react-native 0.50.0, Still no solution?

**Comment by GitHubTracey** [comment] 2017-12-17 17:40
@munkhorgil - I am at the latest release, 0.51.0, and no longer have this issue. The fix mentioned above has been included in the release. Happy Coding!

**Comment by munkhorgil** [comment] 2017-12-17 17:40
@GitHubTracey Thanks for notify!

**Comment by munkhorgil** [comment] 2017-12-18 06:49
I updated to latest release as 0.51, and no longer crash on device. But it re-renders current component and logs in Android Studio as **ReactNative: Attempt to set local data for view with unknown tag** my textinput as follows
```
<TextInput
  ref={name}
  blurOnSubmit={false}
  autoCorrect={false}
  style={styles.inputStyle}
  underlineColorAndroid="transparent"
  onSubmitEditing={() =>
  this.updateField({
     ref: ref, 
     key: key ? key : name, 
     name: name,
      label: label
  })
}
  onChangeText={value => this.setState({[name]: value})}
 value={this.state[name]}
/>
```

**Comment by challme28** [comment] 2018-02-19 13:07
At react native 0.53 it no longer shows me the `Trying to set local data for view with unknown tag: X` message

**Closed** 2018-02-24 03:24 UTC
Labels: Ran Commands

**Comment by kartiikeyabaleneni** [comment] 2018-03-22 04:59
In RN 0.53 . The issue still exists.

**Comment by GregorHorvatH** [comment] 2018-04-02 09:48
"react-native": "0.54.4"   - fixed

**Comment by joshuapinter** [comment] 2018-06-19 00:08
✅ Confirmed. Fixed in React Native 0.54.4.

**Comment by ashishalgo** [comment] 2018-07-16 11:32
we are using react version 0.50.4 version and facing the same issue and we can not update the react version because we are using Salesforce sdk in which 0.50.4 react version is used. 

Is there any resolution for same version to fix this issue?

**Comment by tal987** [comment] 2019-02-11 11:44
@ashishalgo Did you find solution?
