### ISSUE TITLE
Font is not being loaded

### ISSUE THREAD

**Issue by faogustavo** [facebook/react-native#13919] opened 2017-05-11 13:29 UTC
### Description
My application fails to load the text font. No extra font is used to the text, only for the icons.

### Reproduction Steps and Sample Code
This picture was send from a client having this problem.
![](http://image.prntscr.com/image/9bc6f0f3d70e444dbb7b8f1f1c72b3b5.jpeg)

### Additional Information
* React Native version: 0.40.0
* Platform: Android 4.4.4
* Phone Name: SMJ100M - Samsung J1
* Development Operating System: MacOS
* Scenario: Production version downloaded from Play Store

**Comment by jaygarcia** [comment] 2017-05-11 15:46
Are you including the font in your project appropriately?

**Comment by faogustavo** [comment] 2017-05-11 16:39
@jaygarcia yes, many devices work, but on this it happens

**Comment by hramos** [comment] 2017-05-15 18:58
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-05-15 18:58 UTC
