### ISSUE TITLE
No such property: sdkHandler for class: com.android.build.gradle.LibraryPlugin

### ISSUE THREAD

**Issue by RyanRong** [facebook/react-native#13120] opened 2017-03-23 15:13 UTC
I download react-native-master and import project

 No such property: sdkHandler for class: com.android.build.gradle.LibraryPlugin
<a href="openFile:/Users/Ryan/Downloads/react-native-master/ReactAndroid/build.gradle">Open File</a>

**Comment by hramos** [comment] 2017-03-23 17:24
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-03-23 17:24 UTC

**Comment by SudoPlz** [comment] 2017-07-03 15:54
I'm seeing that error too, did you find a solution @RyanRong ?

I'm just trying to build from source by following the steps exactly as they show up here: 
https://facebook.github.io/react-native/docs/android-building-from-source.html

The error get's thrown on [this line](https://github.com/facebook/react-native/blob/master/ReactAndroid/build.gradle#L172). 

Keep in mind that I'm now using 
`compile project(':ReactAndroid')`

instead of 
`compile 'com.facebook.react:react-native:+'`

as suggested on the guide.

Any ideas @hramos ?

**Comment by RyanRong** [comment] 2017-07-03 16:01
@SudoPlz 
downgrading gradle 2.3 to 2.2.3

**Comment by SudoPlz** [comment] 2017-07-03 16:21
Ahh thanks..

After posting that message, I found this (https://github.com/Microsoft/react-native-code-push/issues/858#issuecomment-306621054).

After deleting `package-lock.json` and reinstalling react-native from source everything was fixed.
