### ISSUE TITLE
0.59 -> 0.71.4  RtcMyView can not  dealloc

### ISSUE THREAD

**Issue by sunhongda** [facebook/react-native#37826] opened 2023-06-12 12:12 UTC
### Description

After upgrading to the 0.71.4 SDK, develop the RN project on the native APP of the iOS platform. If you exit the RN page, the custom rtcxxxview cannot be released and the dealloc function will not be called

### React Native Version

0.71.4

### Output of `npx react-native info`

System:
    OS: macOS 13.3.1
    CPU: (8) x64 Apple M1
    Memory: 21.08 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.17.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.3 - /usr/local/bin/npm
    Watchman: 2023.03.06.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /Users/jenkins/.rvm/gems/ruby-3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Flamingo 2022.2.1 Flamingo 2022.2.1
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

https://github.com/OrrHsiao/ReactNativeDemo
You can use this example to reproduce the problem
Repeat step

Open demo and run iOS programs.
Click the "push" button to jump to the RN page.
Click "jump hello word" to go to the Page1 component page.
Click on the navigation bar return arrow "<" Close the RN page. Observe that XATestView does not execute the dealloc function.

### Snack, code example, screenshot, or link to a repository

https://github.com/OrrHsiao/ReactNativeDemo

**Comment by sunhongda** [comment] 2023-07-10 02:17
Still exist

**Comment by cortinico** [comment] 2023-07-10 10:20
Closing as duplicate of #38238

**Closed by cortinico** 2023-07-10 10:20 UTC
Labels: Needs: Triage :mag:, Newer Patch Available
