### ISSUE TITLE
Flow throws errors with RN 0.45 and React alpha 16

### ISSUE THREAD

**Issue by scerelli** [facebook/react-native#14424] opened 2017-06-09 15:33 UTC
It seems that `flow 0.47` doesn't work well with `RN 0.45`. I managed to get flow working only using flow `0.42`, RN `0.45` and react `16.alpha.6`. 

This is something you can check by just creating a new `RN` project and than run flow inside it.

**Comment by hramos** [comment] 2017-06-09 17:03
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-09 17:03 UTC
