### ISSUE TITLE
FlatList doesn't work with full width items

### ISSUE THREAD

**Issue by tomasfrancisco** [facebook/react-native#14243] opened 2017-05-29 17:30 UTC
I'm getting the following behavior when my items are settled to the full width of the column:

![screen shot 2017-05-29 at 18 29 34](https://cloud.githubusercontent.com/assets/4301103/26557932/e448ac2a-449c-11e7-9a6e-ca80e880e063.png)

### Additional Information

* React Native version: 0.44.2
* Platform: iOS
* Development Operating System: macOS

# Update

My items were settled to `flex: 0` in order to fix some kind of bug that I found somewhere else, setting to `flex: 1` solve the problem.

**Comment by tomasfrancisco** [comment] 2017-05-29 17:49
On the first render the list render with weird aspect as the screenshot above, when something updates, the render is ok. Something weird is happening with the first render.

**Comment by hramos** [comment] 2017-05-30 18:06
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-05-30 18:06 UTC
