### ISSUE TITLE
React Native - ScrollView is not working with TabNavigator

### ISSUE THREAD

**Issue by dungle1811** [facebook/react-native#15877] opened 2017-09-09 13:22 UTC
Hello guys,
I have a problem with **ScrollView**. I have used **ScrollView** which wrapped a **TabNavigator** (react-navigation). But when I did that, the content of each tab is hidden. I have tried to set **"flexGrow: 1"**, also **"flex: 1"** inside **contentContainerStyle** of **ScrollView**, the content of tag is showed, but **ScrollView** is not working. So if those content is long, I cannot see full of content.
Does anyone has the same problem like me?
I need help!

**Comment by hramos** [comment] 2017-09-11 14:27
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue that meets the requirements set forth in the template. Thanks!

**Closed by hramos** 2017-09-11 14:27 UTC
