### ISSUE TITLE
npx react-native info and npx react-native init fails with error

### ISSUE THREAD

**Issue by rjatin007** [facebook/react-native#34441] opened 2022-08-17 18:24 UTC
### Description

npx react-native fails with error : - **Failed to load configuration of your project.**

### Version

not known, trying the latest

### Output of `npx react-native info`

error Failed to load configuration of your project.

### Steps to reproduce

npx react-native info

### Snack, code example, screenshot, or link to a repository

<img width="1664" alt="Screenshot 2022-08-17 at 11 52 50 PM" src="https://user-images.githubusercontent.com/30732342/185214490-e5dddf48-29ba-4ab5-a8df-77a8cfd178c8.png">
<img width="1662" alt="Screenshot 2022-08-17 at 11 53 28 PM" src="https://user-images.githubusercontent.com/30732342/185214594-ad994949-d780-4c24-9ffa-3608b48d6498.png">

**Comment by rjatin007** [comment] 2022-08-17 18:27
npx react-native init - also fails with same error

**Comment by cortinico** [comment] 2022-08-18 12:35
You're most likely having some globally installed version of `react-native` or the CLI that you'll have to remove. Instructions on how to do them are here:

https://github.com/facebook/react-native/issues/34055#issuecomment-1165887713

**Comment by rjatin007** [comment] 2022-08-18 13:28
@cortinico nopes, this one's different
 
<img width="1680" alt="Screenshot 2022-08-18 at 6 57 32 PM" src="https://user-images.githubusercontent.com/30732342/185406659-d80ac158-cecd-4d41-8975-acffe7486132.png">

**Comment by cortinico** [comment] 2022-08-18 13:38
It might be this then: https://github.com/react-native-community/cli/pull/1655
Could you run again with `--verbose` as suggested?

**Comment by rjatin007** [comment] 2022-08-18 13:50
@cortinico is this what you are asking for?
<img width="1680" alt="Screenshot 2022-08-18 at 7 20 32 PM" src="https://user-images.githubusercontent.com/30732342/185411559-c40f3b69-8d83-45f4-81fb-d74707ac32fe.png">

**Comment by cortinico** [comment] 2022-08-18 13:57
> @cortinico is this what you are asking for?

Yes but it sadly doesn't help. This is definitely an issue with the CLI (which might be fixed by https://github.com/react-native-community/cli/pull/1655)

Please open an issue on https://github.com/react-native-community/cli/issues as folks there can help you better than us.

**Closed by cortinico** 2022-08-18 13:57 UTC
Labels: 💻CLI, Needs: Attention

**Comment by thanhnvpk01168** [comment] 2022-09-02 18:10
Hi @rjatin007 
did you know the cause?
I also have the same problem

**Comment by rjatin007** [comment] 2022-09-02 18:30
@thanhnvpk01168  Nope, its open here https://github.com/react-native-community/cli/issues/1681

**Comment by rjatin007** [comment] 2022-09-02 18:30
please comment there

**Comment by wedhaka** [comment] 2022-10-08 20:57
First, remove the locally installed react-native

`npm uninstall -g  react-native` or `npm uninstall  react-native`

then retry it again

`npx react-native init AwesomProject`

**Comment by friederbluemle** [comment] 2022-10-11 19:41
I also ran into this (very nondescript) error message, and for me it was simply caused by accidentally running the npx  command **inside a directory that already contained a `package.json` file**.

**Comment by miguelarnalot** [comment] 2022-10-20 23:14
Check if you have npm installed

run `npm install`

**Comment by muhammad-gul-dm** [comment] 2022-10-31 04:45
> First, remove the locally installed react-native
> 
> `npm uninstall -g react-native` or `npm uninstall react-native`
> 
> then retry it again
> 
> `npx react-native init AwesomProject`

This worked for me. Thanks @wedhaka

**Comment by hktom** [comment] 2022-12-03 06:47
> First, remove the locally installed react-native
> 
> `npm uninstall -g react-native` or `npm uninstall react-native`
> 
> then retry it again
> 
> `npx react-native init AwesomProject`

Thanks, it worked

**Comment by msriaz** [comment] 2022-12-28 20:48
Surprisingly none of above worked for me other than: 
```
yarn remove react-native -g
yarn remove react-native-cli -g
```
Please also make sure you've correct version of ruby
React Native uses [this version](https://github.com/facebook/react-native/blob/main/template/_ruby-version) of Ruby. You can also find which version your specific project needs in the .ruby-version file at root of your RN project

**Comment by shahnawazhussain125** [comment] 2023-01-07 16:42
Goto, you the .npm folder delete _npx folder 
In my case (macOS)

Users/(username)/.npm

Or 

To delete the _npx folder on macOS, follow these steps:

Open the terminal.
Navigate to the .npm folder by using the cd command: cd ~/.npm
Delete the _npx folder by using the rm command: rm -r _npx
Note: Make sure you are in the correct directory before deleting the folder. Use the pwd command to check your current working directory.

**Comment by wasurocks** [comment] 2023-01-21 18:57
> First, remove the locally installed react-native
> 
> `npm uninstall -g react-native` or `npm uninstall react-native`
> 
> then retry it again
> 
> `npx react-native init AwesomProject`

Thank you!!

**Comment by rjatin007** [comment] 2023-01-21 19:25
@wasurocks https://github.com/react-native-community/cli/issues/1681

**Comment by rjatin007** [comment] 2023-01-21 19:26
@msriaz @shahnawazhussain125 already did those , issue is  still open here https://github.com/react-native-community/cli/issues/1681

**Comment by BeratOz01** [comment] 2023-01-22 18:54
> I also ran into this (very nondescript) error message, and for me it was simply caused by accidentally running the npx command **inside a directory that already contained a `package.json` file**.

Worked for me!

**Comment by kabundege** [comment] 2023-06-22 17:29
> I also ran into this (very nondescript) error message, and for me it was simply caused by accidentally running the npx command **inside a directory that already contained a `package.json` file**.

this also worked for me, even though the `package.json` was not directly in the fire I was creating the app line, but rather on a global level `i.e Documents` & `Documents/Apps/Mobile`

**Comment by tomaAlex** [comment] 2023-06-27 07:14
> > I also ran into this (very nondescript) error message, and for me it was simply caused by accidentally running the npx command **inside a directory that already contained a `package.json` file**.
> 
> this also worked for me, even though the `package.json` was not directly in the file I was creating the app line, but rather on a global level `i.e Documents` & `Documents/Apps/Mobile`

Thank you, had the same issue, had a package.json in the root folder :face_exhaling:

**Comment by TheoSoko** [comment] 2023-06-29 15:55
> > > I also ran into this (very nondescript) error message, and for me it was simply caused by accidentally running the npx command **inside a directory that already contained a `package.json` file**.
> > 
> > 
> > this also worked for me, even though the `package.json` was not directly in the file I was creating the app line, but rather on a global level `i.e Documents` & `Documents/Apps/Mobile`
> 
> Thank you, had the same issue, had a package.json in the root folder 😮‍💨

Same, incredible. 😮‍
