### ISSUE TITLE
Component layout size calculation errors

### ISSUE THREAD

**Issue by meftunca** [facebook/react-native#47420] opened 2024-11-05 12:39 UTC
# Report
I am using react-navigation and react-native-paper in my react native project. After switching between pages in my project, the appearance of react-native and react-native-paper components is broken. I am sharing 2 images below. 1. the corrupted version of the image and 2. the expected version
- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

![simulator_screenshot_C8D756D1-CE57-4C8D-AFA4-F49F11DEAA93](https://github.com/user-attachments/assets/acc256d2-1c06-4c85-9952-bdf52950fd97)

![simulator_screenshot_1998387D-4894-47DA-BE3B-CB8987295EF7](https://github.com/user-attachments/assets/204af5db-981a-4e07-95fb-30249fdcef4d)

## react-native info
```bash
System:
  OS: macOS 15.0.1
  CPU: (12) arm64 Apple M2 Max
  Memory: 127.89 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 23.1.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.9.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.10.28.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/mapletechnologies/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.23339.11.2421.12483815
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.13
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/mapletechnologies/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.1
    wanted: 0.76.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: true
````

**Comment by cortinico** [comment] 2024-11-05 22:38
Looks like a duplicate of 
- https://github.com/facebook/react-native/issues/47410

**Comment by Chenjiujiu** [comment] 2024-11-18 05:44
> ⚠️ 	缺少可重复的示例
> ℹ️ 	我们无法在您的问题报告中检测到可重现的示例。 请提供：
> 
>     * 如果您的错误与 UI 相关： [小吃 ](https://snack.expo.dev)
> 
>     * 如果您的错误与构建/更新相关：使用我们的 [Re Producer Template ](https://github.com/react-native-community/reproducer-react-native/generate) 。   复制者需要位于您的用户名下的 GitHub 存储库中。

https://snack.expo.dev/@saddhu/tab-style-abnormal?platform=ios 

https://github.com/callstack/react-native-pager-view/issues/914

**Comment by Chenjiujiu** [comment] 2024-11-18 05:45
> > 我个人认为这很大程度上是一个 React Native 新的 Arch 核心风格处理问题。我正在缩小问题范围，我怀疑以下内容： 
> > 
> > * 它与 borderTopLeftRadius、borderTopRightRadius、borderBottomLeftRadius、borderBottomRightRadius 样式属性的使用有关。如果我不再使用这些道具，那么问题就会消失。
> > * 在重新安装/重新渲染时，边框半径似乎被替换回错误的样式道具，可能是 paddingLeft、paddingRight 或类似的东西，因为我看到图像的部分在半径处被切掉了相同的量。
> > * 它与在不同的屏幕（而不仅仅是任何屏幕）中显示相似的内容有关，也许当您显示类似的 FlatList 或类似的 ListItems / 键控列表项时？项目样式是否由新拱门中的列表项目键缓存？
> 
> 我们可以通过本机反应以最小的重现来隔离这个问题吗？没有第三方库。

https://snack.expo.dev/@saddhu/tab-style-abnormal?platform=ios

**Comment by niki-bri** [comment] 2024-11-30 14:24
Any updates on this? I am experiencing the same issue with 0.76.3, new arch, and expo sdk 52.

**Closed** 2024-12-25 09:24 UTC
Labels: Needs: Author Feedback, Needs: Repro

**Comment by dlindenkreuz** [comment] 2024-12-25 09:49
@meftunca what was the solution?

@Chenjiujiu i’d appreciate a translation, this isn’t helpful for english speakers

**Comment by meftunca** [comment] 2024-12-25 09:59
@dlindenkreuz It was a problem caused by the “react-native-pager-view” library. I forgot to close the issue and when I was notified by the bot, I wanted to close it. I share the related pager-view issue below.

https://github.com/callstack/react-native-pager-view/issues/902

**Comment by meftunca** [comment] 2024-12-25 10:00
@dlindenkreuz I can open the issue back if the problem persists for you

**Comment by dlindenkreuz** [comment] 2024-12-25 11:53
thanks for clarifying! I'll bump this thread if anything comes up.

**Comment by julian-gargicevich** [comment] 2025-11-04 22:52
@dlindenkreuz sorry for the revival but I'm having a very similar issue with the new arch and I'm not using that library. Very hard to debug, but I'm assuming it's related to recylcing views? What would be a good way to debug it? Changing the key and hot refreshing fixes the issue.

<img width="1290" height="2796" alt="Image" src="https://github.com/user-attachments/assets/d349b23d-3851-4022-a770-3ce13084c7cd" />
<img width="984" height="2002" alt="Image" src="https://github.com/user-attachments/assets/ec5b681a-2372-4b1a-b41f-4219ef28b4fa" />
![Image](https://github.com/user-attachments/assets/726f84e0-53d5-4e11-9a87-f7d9744bfd34)

**Comment by dlindenkreuz** [comment] 2025-11-05 19:46
Oof, no idea. I did not experience the issue ever since. Maybe post your react-native / expo / other related library versions so that it’s easier for someone from the community to help you.

**Comment by julian-gargicevich** [comment] 2025-11-05 20:17
> Oof, no idea. I did not experience the issue ever since. Maybe post your react-native / expo / other related library versions so that it’s easier for someone from the community to help you.

Thanks for replying, issue ended up being the the new expo/ui library in case anyone is having the same problem.
