### ISSUE TITLE
ReactContext: currentActivity is null when onActivityResult is called

### ISSUE THREAD

**Issue by fab1an** [facebook/react-native#8694] opened 2016-07-11 13:21 UTC
I use `addActivityEventListener` to listen for the result of an Intent.

1. when I start the Intent RN calls `onHostPause` and releases the reference `mCurrentActivity` in `ReactContext.java`.
2. my `onActivityResult` fires, but there is no `currentActivity` set yet, because `onHostResume` is called afterwards.

0.29 / Android / Mac

**Comment by charpeni** [comment] 2016-07-11 13:29
Can you provide some code?

**Comment by fab1an** [comment] 2016-07-11 13:33
Yes, but it's in Kotlin, do you mind?

**Comment by charpeni** [comment] 2016-07-11 13:40
I'm not familiar with Kotlin, but for other people who will check this that will be better than nothing I guess.

**Comment by charpeni** [comment] 2016-07-11 13:40
@facebook-github-bot label Android

**Comment by fab1an** [comment] 2016-07-11 13:43
Stripped version:

```kotlin
package at.feibra.mobileqm

class ControllerModule(ctx: ReactApplicationContext) : ReactContextBaseJavaModule(ctx) {

    // ~ Constructors ----------------------------------------------------------------------------------

    init {
        /* forward activity event to controller */
        ctx.addActivityEventListener { requestCode, resultCode, data ->
            L.info("activity result: requestCode: {}, resultCode: {}, data: {}", requestCode, resultCode, data);
        }

        /* forward resume, pause, destroy to controller */
        ctx.addLifecycleEventListener(object : LifecycleEventListener {
            override fun onHostResume() {
                L.info("host resumed")
            }

            override fun onHostPause() {
                L.info("host paused")
            }

            override fun onHostDestroy() {
            }
        })
    }
}
```

**Comment by fab1an** [comment] 2016-07-11 14:04
This line: https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/bridge/ReactContext.java#L157

is called AFTER this: https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/bridge/ReactContext.java#L208

**Comment by satya164** [comment] 2016-07-13 03:32
I can confirm this that I've run into this issue.

cc @foghina

**Comment by foghina** [comment] 2016-07-13 09:28
Yeah, this is how Android works, unfortunately. If you have a plain `Activity` you will see the same thing: `onActivityResult` is called before `onResume`. We're not going to make hacks to work around this at the platform level (since we want to mimic Android as much as possible), but feel free to work around it yourself by e.g. storing the result and dealing with it in `onHostResume`. Even better, you can handle both cases easily, like this:

```java
@Override
public void onHostResume() {
  if (mActivityResult != null) {
    // getCurrentActivity() will never return null here
    handleActivityResult(getCurrentActivity(), mActivityResult);
    mActivityResult = null;
  }
}

@Override
public void onActivityResult(int requestCode, int resultCode, Intent data) {
  final Activity activity = getCurrentActivity();
  if (activity != null) {
    handleActivityResult(activity, data);
  } else {
    mActivityResult = data;
  }
}

private void handleActivityResult(Activity activity, Intent result) {
  // insert business logic
}
```

I'd write this in Kotlin but I'm pretty rusty 🙃

**Comment by fab1an** [comment] 2016-07-13 09:34
I've worked around it like that already.

I still think this needs fixing: Usually, without RN, people would override [`onActivityResult`](https://developer.android.com/reference/android/app/Activity.html#onActivityResult(int, int, android.content.Intent) and have their activity around using `this`.

**Comment by fab1an** [comment] 2016-07-22 14:26
@foghina Please reopen this issue. You said RN `wants to mimic Android as much as possible`. In a regular Android application you have access to your Activity on  `onActivityResult`. In RN you don't…

**Comment by foghina** [comment] 2016-07-22 14:31
Fine. Feel free to send a PR that e.g. adds an `Activity` arg to `onActivityResult()`.

**Comment by fab1an** [comment] 2016-07-22 14:36
@foghina Awesome thanks. I can do that, but I noticed another problem which might be related. I worked around like you said by storing the result and waiting for the Activity to return.

Now I tested my app for low-memory using "Don't keep activities". When using that second "onActivityResult" is actually never called, because apparently the Host is destroyed?

**Comment by foghina** [comment] 2016-07-22 14:46
Ah yes, the problem there is the `ReactInstanceManager` gets destroyed when the `Activity` is destroyed. I might fix that soon anyway as part of a different thing I'm working on.

**Comment by fab1an** [comment] 2016-07-23 08:43
@foghina Ok. I would help, but I don't know what the "structural plan" is. One `ReactInstanceManager`  and one `ReactNativeHost` per Android Application, is that right? The `ReactRootView` is destroyed and recreated along with Activities?

Is the actual JS structure (the component-tree, the callbacks) tied to the `ReactRootView` too or can it be reused across Activities?

**Comment by fab1an** [comment] 2016-08-06 09:43
Has this be changed with 0.31? Thanks!

**Comment by fab1an** [comment] 2016-08-11 15:25
Any idea when this will be fixed?

**Comment by foghina** [comment] 2016-08-11 16:34
This should be fixed by 3c4fd4.

However, note that if the activity returning a result is also a RN activity, it will be returned by `getCurrentReactActivity()` during `onActivityResult()`, instead of the activity receiving the result.

If the activity returning the result is not RN (e.g. camera app), current activity will be correct.

Also, running with don't keep activities is probably still broken.

Working on a fix for these two issues.

**Closed** 2016-08-15 11:04 UTC
Labels: Android, Ran Commands

**Comment by fab1an** [comment] 2016-08-15 11:20
@foghina So does this work now when not keeping activities?

**Comment by foghina** [comment] 2016-08-15 13:49
It should work, I've tested a bunch of scenarios but not `onActivityResult` specifically. Feel free to try it out (e.g. using master) and open a new bugreport if it still doesn't work (and cc me).

**Comment by fab1an** [comment] 2016-08-16 10:38
@foghina I'll test it when it's released (in 0.32?)

**Comment by foghina** [comment] 2016-08-16 10:48
Probably `0.33-rc` and then `0.33`, not sure though. @bestander?

**Comment by bestander** [comment] 2016-08-16 10:53
0.33-rc.0 next Monday unless this is critical to get as a patch into 0.32.0.

**Comment by fab1an** [comment] 2016-08-16 12:08
@bestander It is not critical to me, but, since Android is allowed to kill Activities any time, this can lead to spurious bugs for inexperienced users, which in turn creates new issues for this already overwhelmed project…

**Comment by bestander** [comment] 2016-08-16 23:24
@fab1an, 0.32 becomes stable early next week and 0.33-rc is released.
This issue has been there for a while so I don't think we should rush and risk 0.32 stable and release it without a good 2 weeks of release-candidate testing.
But thanks for caring and feel free to discuss more.

**Comment by conover** [comment] 2016-08-26 22:50
This is actually a big deal. This patch seems to fix a whole class of issues for us. We will be testing .33-rc over the weekend.

**Comment by fab1an** [comment] 2016-09-10 09:44
@conover Did it fix your issues?

**Comment by fab1an** [comment] 2016-09-26 12:12
I can confirm this fixed as of version 0.34, I did not try 0.33.

**Comment by droidwolf** [comment] 2017-03-01 05:44
I hava the same issues. version 0.36
when i used getCurrentActivity in ReactContextBaseJavaModule some times return null.
I create ReactInstanceManager not in onCreate method，But in the onCreate after a period of time。
So there is no onHostResume method is called, passing the current activity to ReactContext.
My solution is to create a ReactInstanceManager called after ReactInstanceManager.onHostResume.
