### ISSUE TITLE
UNMET PEER DEPENDENCY react@15.1.0

### ISSUE THREAD

**Issue by devekoperiOS** [facebook/react-native#7803] opened 2016-05-27 15:04 UTC
I am running following command.
npm install react --save

── UNMET PEER DEPENDENCY react@15.1.0

npm WARN EPEERINVALID react-dom@0.14.8 requires a peer of react@^0.14.8 but none was installed.
npm WARN EPEERINVALID react-native@0.26.2 requires a peer of react@15.0.2 but none was installed.
npm ERR! code 1
It gives me following error and also in simulator my app is not working. Please help.

**Comment by charpeni** [comment] 2016-05-27 17:58
change the version to "react": "~15.0.2", and run npm install. https://github.com/facebook/react-native/issues/7777#issuecomment-221864750

**Comment by charpeni** [comment] 2016-05-27 17:58
@facebook-github-bot close

**Comment by facebook-github-bot-2** [comment] 2016-05-27 18:01
@charpeni tells me to close this issue. If you think it should still be opened let us know why.

**Closed by facebook-github-bot-2** 2016-05-27 18:01 UTC
Labels: Ran Commands

**Comment by shubhsin** [comment] 2016-05-31 11:46
The issue still remains

**Comment by charpeni** [comment] 2016-05-31 23:04
And after this https://github.com/facebook/react-native/issues/7777#issuecomment-222266177 ?

**Comment by shubhsin** [comment] 2016-06-01 07:12
Okay so I downgraded to 15.0.2 and my Mapbox-GL now works. You can close the issue now since the issue is with Mapbox

**Comment by joekrump** [comment] 2016-06-24 22:22
@facebook-github-bot close
