### ISSUE TITLE
Link fails

### ISSUE THREAD

**Issue by stilllife00** [facebook/react-native#12216] opened 2017-02-05 12:36 UTC
### Description

Trying to link libraries (after adding react-native-config and after a full upgrade)

### Reproduction

       react-native link

Result

      rnpm-install ERR! ERRPACKAGEJSON No package found. Are you sure it's a React Native project?  
      Cannot read property 'replace' of undefined

### Solution

The package.json is there so the link should work

### Additional Information

* React Native version: "react-native": "^0.41.1",
* Platform: Android (but I guess is irrelevant)
* Operating System: Linux Ubuntu 16.10

**Comment by j2kun** [comment] 2017-02-22 18:07
I'm experiencing a similar issue with `react-native-config`:

```
$ react-native link react-native-config
rnpm-install info Android module react-native-config is already linked 
rnpm-install info Linking react-native-config ios dependency 
rnpm-install ERR! It seems something went wrong while linking. Error: str.replace is not a function 
Please file an issue here: https://github.com/facebook/react-native/issues 

str.replace is not a function

```

**Comment by SandroMachado** [comment] 2017-03-20 11:31
I am experiencing the same issue with `react-native-snackbar`. Any fix for this?

**Comment by j2kun** [comment] 2017-03-20 16:25
@SandroMachado My fix was to manually link

**Comment by SandroMachado** [comment] 2017-03-20 16:41
I did the same :(

**Comment by j2kun** [comment] 2017-03-20 16:53
@SandroMachado It's sad that the more I work with react native, the more problems I find with the tooling.

**Comment by tminard** [comment] 2017-04-11 12:47
Same issue. What is going on?

react-native-cli: 2.0.1
react-native: 0.43.3

**Comment by tminard** [comment] 2017-04-11 12:58
@stilllife00 I think I may have found it. My issue was due to a missing package name in my debug AndroidManifest.xml file. Ensure your manifests have a valid  package="com.<packagenamespace>" attribute:

`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.<package>">

...

</manifest>`

**Comment by stilllife00** [comment] 2017-04-18 21:53
@tminard That actually did the trick. I was entirely missing the `package` attribute from the `src/debug/AndroidManifest.xml`

**Comment by fabriziomoscon** [comment] 2017-05-12 08:59
I had the same issue. Adding package to all `AndroidManifest.xml` files fixed it.

This issue can be closed

**Comment by hramos** [comment] 2017-07-25 22:59
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Closed by hramos** 2017-07-25 22:59 UTC
Labels: Icebox

**Comment by bjacog** [comment] 2017-10-18 11:48
I was experiencing the same issue. Turns out the developer had commented out the whole manifest and wrote the new manifest in the same file with the old version commented out at the bottom causing the same issue. I guess it is because of the package="com.<package>" string being present more than once in the file.

**Comment by dancherb** [comment] 2018-04-04 19:53
Cheers @bjacog, happened for me because I had something commented out at the bottom of my manifest (though not to do with package).
