### ISSUE TITLE
Getting a issue of refs.scrollView.scrollTo

### ISSUE THREAD

**Issue by Msspl-PrashenjeetRoy** [facebook/react-native#12685] opened 2017-03-03 13:36 UTC
I have used `refs.scrollView.scrollTo` in many components in my app and we are using r`eact-native-fcm` and `react-native-image-picker`. 

After few minutes using app I am getting app crashes and in report i got this below issue:

```
com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'e.refs.scrollView.scrollTo'), stack:
value@605:5795
<unknown>@605:6752
<unknown>@60:549
callTimer@55:626
callTimers@55:1031
value@53:2818
<unknown>@53:1053
d@53:127
value@53:1025

	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:97)
	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:81)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
	at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
	at android.os.Looper.loop(Looper.java:148)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by hramos** [comment] 2017-03-03 18:22
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-03-03 18:22 UTC

**Comment by Msspl-PrashenjeetRoy** [comment] 2017-03-03 18:29
Why closing wait for my reply. I have posted it today. I have big code in
my project so can't share all here. Main issue arises when i am using
scrollto in any component app crashes after some time. When i removed these
codes app is not crashing.

**Comment by hramos** [comment] 2017-03-03 18:34
You can open a new issue, just make sure it fills out everything in https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by Msspl-PrashenjeetRoy** [comment] 2017-03-03 18:38
Ok

**Comment by philjoseph** [comment] 2017-03-14 08:55
@Msspl-PrashenjeetRoy - Did you reported your issue ? we have something similar and prefer not to create duplicates report
