### ISSUE TITLE
Encoding Error caused by XMLHttpRequest.

### ISSUE THREAD

**Issue by wzl002** [facebook/react-native#9104] opened 2016-07-30 12:59 UTC
env : Mac 10.11.6 , iOS 9.3 , RN 0.29,  Loopback on linux as rest api server.

When use the XMLHttpRequest with Chinese response, the encoding would be error randomly.

my example code:

```
var request = new XMLHttpRequest();
    request.onreadystatechange = (e) => {
        if (request.readyState !== 4) {
            return;
        }

        if (request.status === 200) {
            console.log('success',  JSON.parse(request.responseText)[0].chnlName);
        } else {
            console.warn('error');
        }
    };

    request.open('GET', 'http://localhost:3008/api/v1/Chnls?filter=%7B%22where%22%3A%7B%22limit%22%3A%2210%22%2C%20%22staffId%22%3A%20%2287850%22%7D%7D');
    request.send();
```

 
Run several times at a stretch :
```
2016-07-30 20:41:57.610 [info][tid:com.facebook.react.JavaScript] 'success', '昆明江管理本部'
2016-07-30 20:41:57.612 [info][tid:com.facebook.react.JavaScript] 'success', '昆明江管理本部'
2016-07-30 20:41:57.661 [info][tid:com.facebook.react.JavaScript] 'success', '第三中学小卖部2G便利店'
2016-07-30 20:41:57.928 [info][tid:com.facebook.react.JavaScript] 'success', 'ж�†ж�ЋжЌ·дїЎйЂљжЂ’ж±џз®Ўзђ†жњ¬йѓЁ'
2016-07-30 20:42:07.368 [info][tid:com.facebook.react.JavaScript] 'success', 'жµљеЋїеЌ«иґ¤й•‡зєўжіўйЂљи®Їдё“иђҐеє—'
2016-07-30 20:42:07.370 [info][tid:com.facebook.react.JavaScript] 'success', '昆明江管理本部'
2016-07-30 20:42:07.372 [info][tid:com.facebook.react.JavaScript] 'success', '四平市移数通电讯电话'
2016-07-30 20:42:07.375 [info][tid:com.facebook.react.JavaScript] 'success', '四平市移数通电讯电话'
```

What is the encoding of 'ж�†ж�ЋжЌ·дїЎйЂљжЂ’ж±џз®Ўзђ†жњ¬йѓЁ' ? 

I tried request data with 'fetch' function and loopback explorer in chrome, the response is all right, so it's not a problem caused by api server.

Is this a issue or is there any way to solve this?

Thanks

**Comment by lacker** [comment] 2016-10-28 20:28
I think we would need a better repro to figure out specifically what the problem is here. My guess is https://github.com/facebook/react-native/pull/10110 so I am going to close this issue.

**Closed by lacker** 2016-10-28 20:28 UTC

**Comment by candicom** [comment] 2016-12-14 01:40
Android is not fixed.
