### ISSUE TITLE
[Android] View bounds incorrect after rotate transform

### ISSUE THREAD

**Issue by marcshilling** [facebook/react-native#6734] opened 2016-03-30 18:08 UTC
Android only...works on iOS...React Native 0.22...

Check out this screenshot:

<img src="http://i.imgur.com/Mmb3PZG.png" height="700">

I've applied a `transform: [{rotate: '-45deg'}]` style to the green view. As you can see, the rotation is rendered correctly, but upon using the inspector you can see the bounds are incorrect. I noticed this after rotating some `Touchable` views and being unable to tap on parts of the view afterwards, so the issue is not isolated to the inspector.

Seems like a bug, but does anyone know of a workaround?

**Comment by charpeni** [comment] 2016-03-30 19:33
@facebook-github-bot label android

**Comment by charpeni** [comment] 2016-03-30 20:15
@facebook-github-bot label android

**Comment by marcshilling** [comment] 2016-04-29 14:47
Now seeing this on certain iOS devices as well...
Oddly, just a 6s and a 6s Plus are having this issue.

**Comment by lacker** [comment] 2016-10-21 04:45
I'm not sure how to reproduce this based on just this screen shot - I think a sample on rnplay.org would be ideal. Since it's been a while I'm just going to close this issue, but feel free to open a new one if you have a small repro app.

**Closed by lacker** 2016-10-21 04:45 UTC
Labels: Android, Contains Potential Question Keywords, Ran Commands
