### ISSUE TITLE
Inline image does not accept resizeMode as well as positioning

### ISSUE THREAD

**Issue by undef1ned** [facebook/react-native#10998] opened 2016-11-17 19:49 UTC
My app implements Chat functionality with emoticons support. Images are intended to be drawn as child elements of the **Text** containers. However I can not apply any positioning to **Image** (to align images vertically) as well as resizeMode - they are skipped for images with parent element of **Text**

```
<Text>
     <Text>This is message with emoticon at the end</Text>
     <Image resizeMode='contain' style={{resizeMode: 'contain', top: ... }} src=.../>
</Text>
```
Seems it only accepts **width** and **height** attributes

Probably there are some workarounds. I tried to use **View** parent element with flexDirection: row and flexWrap: wrap, but it does not wrap long text messages. Seems the only possible solution for Chat messages is to put everything into **Text** parent only

Any help is appreciated, thanks

* React Native version: 0.37
* Platform: Android
* Operating System: MacOS

**Comment by mkonicek** [comment] 2016-11-28 01:54
Can you provide a minimal amount of code to reproduce this on [rnplay.org](https://rnplay.org/)? This is necessary for people to be able to see and debug the issue being reported.

Closing this issue as it is not actionable. Please open a new one with an rnplay link (preferred), or link to a GitHub repo with clear instructions how to repro.

**Comment by mkonicek** [comment] 2016-11-28 01:55
This might indeed not be supported.

**Comment by hramos** [comment] 2017-05-25 20:36
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Closed by hramos** 2017-05-25 20:36 UTC
