### ISSUE TITLE
Ability to configure transformTimeoutInterval for react-native server from outside.

### ISSUE THREAD

**Issue by Gonzih** [facebook/react-native#2795] opened 2015-09-17 07:30 UTC
Hello,

I just noticed that with big javascript (>1mb) files react-native often times out. I found constant that corresponds to 60 seconds timetout time and changed it, but would be nice to configure it from outside.
Is there any standart way in current react-native-cli implementation that allows to set things like that via for example env variable? 

Thanks a lot!

**Comment by cmrcmr** [comment] 2015-09-23 13:59
Hi @Gonzih 

Where did you set the transformTimeoutInterval constant ? I'm getting the same error

**Comment by Gonzih** [comment] 2015-09-23 16:32
./node_modules/react-native/packager/react-packager/src/JSTransformer/index.js

line:

const DEFAULT_MAX_CALL_TIME = 60000;

**Comment by tomprogers** [comment] 2016-02-16 06:10
I'm getting this same error, but not after waiting for 301 seconds. I have a very large module (2.7MB, exports a single array with several hundred thousand items), and I'm sure this is somehow the problem. But the transformer dies after less than 5 seconds, saying that the transformation took more than 301 seconds.

I'm going to change the module signature, but I think the transformer is either not honoring `transformTimeoutInterval`, or is mis-reporting a failure of a different type. I'll dig into this more tomorrow.

**Comment by tomprogers** [comment] 2016-02-17 02:21
It looks like what's happening is that the packager chokes after 301s the first time, and then caches that failure so that subsequent builds triggered by the watcher don't each take another 5 minutes before failing.

I'm surprised this is such a problem: 2.7MB is a large file, but it's nothing remarkable in the modern world of webpacked/browserified webapps, which can easily run to 8MB in total. And it's my understanding that the React-Native team chose to implement their own packager rather than use webpack precisely for speed purposes.

In any case, I think I'm going to have to figure out another way to get this data into the app.

**Comment by jsierles** [comment] 2016-03-20 17:05
@tomprogers Hey, thanks for opening this issue!

Since the original issue was a feature request, and seems unrelated to the possibly buggy behavior mentioned in your last comment, I'm closing it out.

If this is still an issue, feel free to reopen as a bug, and if possible, include a github repo with steps we can reproduce.

**Closed by jsierles** 2016-03-20 17:05 UTC
Labels: Packager, Triage - In Progress
