### ISSUE TITLE
Generating the release APK fails with error: UNKNOWN: unknown error, open 'C:\Users\truon\.babel.json'

### ISSUE THREAD

**Issue by phaptq** [facebook/react-native#12723] opened 2017-03-05 16:06 UTC
My version:
"react": "15.4.2",
"react-native": "0.41.2"

that is erro has fired:
`fs.js:558
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: UNKNOWN: unknown error, open 'C:\Users\truon\.babel.json'
    at Object.fs.openSync (fs.js:558:18)
    at Object.fs.writeFileSync (fs.js:1223:33)
    at process.save (E:\Mobile\phongtotapp\node_modules\babel-register\lib\cache.js:48:16)
    at emitOne (events.js:96:13)
    at process.emit (events.js:189:7)
:app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'cmd'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED`

**Comment by ericvicenti** [comment] 2017-03-06 07:42
This may be a duplicate of https://github.com/facebook/react-native/issues/8678, please make sure the file permissions are set correctly for the `.babel.json` files

**Closed by ericvicenti** 2017-03-06 07:42 UTC
