### ISSUE TITLE
Unexpected Token / No Stack Error Android Emulator

### ISSUE THREAD

**Issue by JatB01** [facebook/react-native#34312] opened 2022-07-30 14:42 UTC
### Description

Hi all,

I have a frustrating issue that popped up recently and can't seem to find a solution. If I run my expo app on my local Android Studio Emulator, I get the following error randomly (sometimes it works fine, then other times it gives this error). This has to be the emulator because when I run Expo Go on my physical device, it runs fine whilst giving the same error on the Emulator. 

![image](https://user-images.githubusercontent.com/38192190/181917439-4cb075e4-0afe-4b6a-829e-8aa90e0b1cef.png)

I tried [this solution ](https://github.com/babel/babel/issues/14139#issuecomment-1011836916) by updating my babel.config.js as so:

> module.exports = function(api) {
>   api.cache(true);
>   return {
>     presets: [['babel-preset-expo', {
>       unstable_disableES6Transforms: true
>     }]],
>     plugins: [
>       ["module:react-native-dotenv"]
>     ]
>   };
> };

but this did not solve my issue. Any help would be appreciated.

### Version

0.68.2

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 AMD FX(tm)-8350 Eight-Core Processor
    Memory: 4.64 GB / 15.90 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7784292
    Visual Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.2 => 0.68.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

N/A

### Snack, code example, screenshot, or link to a repository

N/A

**Comment by pjsandwich** [comment] 2022-10-14 16:45
Is there any update on this issue? I'm also experiencing this mildly infuriating issue

**Comment by cortinico** [comment] 2022-10-14 18:41
> Unexpected Token ')'

This error is generally related to you using a older Node version (sometimes you have older Global version installed) or more simply, a `)` that you left around in the code.

Without reproducer, there is not much we can do here.

**Comment by pjsandwich** [comment] 2022-10-14 21:14
It seems to have resolved after two system reboots, including wiping data of emulator

**Comment by cortinico** [comment] 2022-10-17 12:46
> It seems to have resolved after two system reboots, including wiping data of emulator

Closing due to this

**Closed by cortinico** 2022-10-17 12:46 UTC
Labels: Platform: Android, Needs: Triage :mag:, Needs: Author Feedback, Needs: Repro

**Comment by 2208anujsoni** [comment] 2023-02-18 14:15
> It seems to have resolved after two system reboots, including wiping data of emulator

not working

**Comment by jhonny1525** [comment] 2023-09-07 12:11
Also facing the same issue

**Comment by ShamiGondal** [comment] 2024-05-01 17:57
I am also facing this issue here is my repo plz help me to get out of this furastating issue.
https://github.com/ShamiGondal/IStreaming
