### ISSUE TITLE
DatePickerIOS is not displaying since upgrading to 0.29

### ISSUE THREAD

**Issue by dmendis** [facebook/react-native#8730] opened 2016-07-13 05:36 UTC
Undoing this commit makes the date picker work.

https://github.com/facebook/react-native/commit/002024cc456246761421f6e5c354466baa819843

Specifically, adding back a width value. 

Is there a way to style the `<DatePickerIOS>` control that makes the `RCTDatePicker` appear correctly?

**Comment by dmendis** [comment] 2016-07-13 05:48
I have found that putting any `style` attribute to DatePickerIOS will make it stop displaying. The fact that DatePickerIOS inheriting all properties of View would imply all style elements are applicable. I got my DatePickerIOS showing up by removing all styles applied to it. I had a flex-end and height added to it.

**Comment by sorenburon** [comment] 2016-07-13 10:39
I got no styles added to it, and it won't show

**Comment by grabbou** [comment] 2016-07-16 15:55
I've just added `flex: 1` and it's displaying properly, mind providing an rn-play example showing an issue?

**Comment by Jaikant** [comment] 2016-08-09 03:42
I am new to react native and I have spent many many hours endlessly trying to debug this. Thanks so much, for your work to find the cause of it.

**Comment by alongubkin** [comment] 2016-08-30 23:27
This happened to me when the DatePickerIOS was under a View with `position: absolute` and some flexbox props

**Comment by purnomoeko** [comment] 2016-09-05 09:42
Remove all flex box attributes on parent node such as AlignItems or JustifyContent.

**Comment by techpanga** [comment] 2016-09-15 10:52
RN 0.32, DatePickerIOS  not displayed. Is there any solution?

**Comment by jjshammas** [comment] 2016-11-28 19:31
I know this issue is old but I ran into this today on RN 0.37.

I needed to apply `flex: 1` to my `DatePickerIOS`. I believe the issue is that the element by default has a 0 width/height, so it needs to either inherit these attributes from its parent (via `flex: 1`), or an explicit height and width must be set.

An explicit height used to be all that was necessary—now it seems the width also defaults to 0.

**Comment by coderdave** [comment] 2016-12-19 01:50
I had to change the `DatePickerIOS` style from `alignSelf: 'center'` to `justifyContent: 'center'` for it to show up. :shrug:

**Comment by ShogunPanda** [comment] 2017-04-14 15:53
I had similar issue.
In my case apparently the height was fine but width was not. I resolved by setting:

```
style={{width: Dimensions.get("window").width}}
```

**Comment by hramos** [comment] 2017-07-20 21:16
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/datepickerios-is-not-displaying-since-upgrading-to-029

**Closed by hramos** 2017-07-20 21:16 UTC
Labels: Icebox

**Comment by dawidsawa** [comment] 2017-07-22 15:14
The issue is still present with react-native 0.45.1 and is demonstrable with the following code https://snack.expo.io/By9RqDx8b Just like it was already mentioned by some people, the elements of the picker become invisible when the parent element uses style with `alignItems: 'center'`.

**Comment by SSTPIERRE2** [comment] 2017-11-16 16:13
Following up here, using RN 0.50.3, like many have stated, if you want to center your DatePickerIOS component, it appears you must use ```flex: 1, justifyContent: 'center'``` for the parent's style, but you cannot use ```alignItems: 'center'``` or else the date picker will not render.

Luckily, the date picker is already centered on the secondary axis :)
