### ISSUE TITLE
How to change RefreshControl swiping down height in ScrollView

### ISSUE THREAD

**Issue by MonarthS** [facebook/react-native#28125] opened 2020-02-19 13:55 UTC
#### Description:

I want to change the `swipe down` length for RefreshControl in ScrollView, but there is no option to change `swipe down` length.

![rsz_screenshot_2020-02-19_at_70538_pm](https://user-images.githubusercontent.com/40236229/74840159-80198f00-534c-11ea-922f-1e59acbdc028.png)

Currently I have to Swipe down too much.

#### React Native version:

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 22.70 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.17.0 - /usr/local/opt/node@8/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/opt/node@8/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.1 AI-173.4697961
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-log-ios: 1.0.1
```

## Expected Results

minimum swipe down for RefreshControl.

## Snack, code example, screenshot, or link to a repository:

```
<ScrollView style={{scrollY: 0}} contentContainerStyle={{ flex: 1 , scrollY:30}} showsVerticalScrollIndicator={false} refreshControl={
          <RefreshControl title={'refreshing'} tintColor={'red'} onRefresh={this.onRefresh.bind(this)} refreshing={this.state.refreshing} />
        }>
</ScrollView>
```

**Comment by hramos** [comment] 2020-02-19 20:18
Closing as this is not a bug.

**Closed by hramos** 2020-02-19 20:18 UTC
Labels: Type: Question
