### ISSUE TITLE
With maxWidth set on container view some wrapping text gets clipped and not visible.

### ISSUE THREAD

**Issue by joonhocho** [facebook/react-native#10892] opened 2016-11-12 09:40 UTC
### Description

With maxWidth set on container view some wrapping text gets clipped and not visible.

![screen shot 2016-11-12 at 1 41 21 am](https://cloud.githubusercontent.com/assets/930795/20236908/31cefffa-a879-11e6-976b-dcadc2aeceba.png)

Note that message should be "You haven't sent or received any messages yet.", but only "You haven't sent or received any" is visible. Next wrapping line is cut off and not visible. 

### Reproduction

```javascript
const styles = StyleSheet.create({
  inner: {
    maxWidth: 225,
  },
  title: {
    fontSize: 16,
    lineHeight: Math.floor(16 * 1.3),
    color: colors.emptySectionTitle,
    textAlign: 'center',
  },
  message: {
    fontSize: 14,
    lineHeight: Math.floor(14 * 1.3),
    color: colors.emptySectionMessage,
    textAlign: 'center',
    marginTop: 5,
  },
});

const Error = ({title, message}) =>
<View style={styles.box}>
    <View style={styles.inner}>
      {title &&
      <Text style={styles.title}>{title}</Text>}
      {message &&
      <Text style={styles.message}>{message}</Text>}
    </View>
  </View>;

<Error title="No Messages Yet"
          message="You haven't sent or received any messages yet."
/>

```

Using width instead of maxWidth resolves the issue.

### Additional Information

* React Native version: 0.35
* Platform: iOS
* Operating System: MacOS

**Comment by yuriyvl** [comment] 2016-11-12 14:49
I experienced the same problem.  My React Native version is 0.37.  I reproduced it on both iOS and Android.

**Comment by jevakallio** [comment] 2016-11-13 17:42
I can also reproduce this. A workaround is to apply `flex: 1` to the text element (which of course has other ramifications to the layout, so it's not a drop-in fix).

Seems like a duplicate of https://github.com/facebook/react-native/issues/9293

**Comment by hramos** [comment] 2017-05-25 20:36
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Closed by hramos** 2017-05-25 20:36 UTC
