### ISSUE TITLE
Long Text doesn't render correctly when in ScrollView 

### ISSUE THREAD

**Issue by zuccha** [facebook/react-native#22713] opened 2018-12-19 15:50 UTC
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
      Memory: 1.82 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.11.0 - ~/.nvm/versions/node/v10.11.0/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.11.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 25, 26, 27, 28
        Build Tools: 26.0.3, 27.0.3, 28.0.2
        System Images: android-26 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.57.8 => 0.57.8
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
When placing a `Text` component into a `ScrollView` on iOS, if `Text` contains too many characters, then no text is rendered, however the `Text` component occupies the correct amount of space (_i.e._, the view scrolls). The number of characters for breaking the `Text` component varies depending on the device, but it is usually around 25,000.

__N.B.: The bug is not present if we replace `ScrollView` with `View`.__

This bug is not present on Android.

Wrong behaviour (no text, but the view scrolls):
<img width="539" alt="wrong" src="https://user-images.githubusercontent.com/19038023/50230510-15b63900-03ad-11e9-96c0-0bb32c5abce0.png">

Correct behaviour (text and the view scrolls):
<img width="539" alt="correct" src="https://user-images.githubusercontent.com/19038023/50230563-2e265380-03ad-11e9-82ca-54e8f7d0b6ea.png">

## Reproducible Demo
To reproduce the bug, run the following code on iOS
```
import React from 'react';
import { Text, ScrollView } from 'react-native';

export default () => (
  <ScrollView>
    <Text>{'a'.repeat(25000)}</Text>
  </ScrollView>
);
```

**Comment by simformsolutions** [comment] 2019-01-01 07:34
<ScrollView contentContainerStyle={{ flex: 1 }}>

**Comment by triplea24** [comment] 2019-01-07 17:19
Hi @zuccha, You should add some style to the ScrollView's container so it can stretch and completely fit in the screen.

Just replace it with this snippet:
```
export default () => (
  <ScrollView contentContainerStyle={{ flex: 1}}>
    <Text style={{ flex: 1}}>{'a'.repeat(25000)}</Text>
  </ScrollView>
);
```

**Comment by zuccha** [comment] 2019-01-12 15:59
Hi @triplea24 thank for your help. I tried with `flex: 1`, but that way the `ScrollView` is not scrollable anymore. It is easy to see by putting two long texts one after the other
```
import React from 'react';
import { Text, ScrollView } from 'react-native';

export default () => (
  <ScrollView contentContainerStyle={{flex:1}}>
    <Text>{'a'.repeat(25000)}</Text>
    <Text>{'b'.repeat(25000)}</Text>
  </ScrollView>
);
```
The texts should have the same length, but I can't scroll through the 'b's. However, if I remove the `flex: 1`, the text disappears (but the view has the correct size). I don't think it's a problem of size (again, the view has the correct size).

**Comment by LucasMonteiro1** [comment] 2019-01-17 02:00
Same problem

**Comment by danilobuerger** [comment] 2019-02-05 15:19
The bug seems to be related to the height of the content. So with a smaller font size, more text can be displayed.

**Comment by alangumer** [comment] 2019-03-01 15:21
Same problem here, agreed with @zuccha seems like the issue is with the Text component, the View size is correct.

**Comment by ericlewis** [comment] 2019-03-01 15:24
I did some investigation in to this bug, and it appears to be related to Yoga, or the way we calculate heights using NSTextStorage. I wasn’t able to dig in much further.

**Comment by CatapultJesse** [comment] 2019-03-02 07:33
Snack reproducing: https://snack.expo.io/@jkcooper/rn22713-long-text-in-scrollview

**Comment by CatapultJesse** [comment] 2019-03-02 07:36
Related Issue: https://github.com/faceabook/react-native/issues/19453

**Comment by ericlewis** [comment] 2019-03-04 23:46
Interesting update: I can confirm this only occurs in simulator. Running on devices doesn't appear to have this issue. I think it is a simulator issue.

**Comment by rickhanlonii** [comment] 2019-03-19 16:29
Dupe of https://github.com/facebook/react-native/issues/19453 👌

**Closed by rickhanlonii** 2019-03-19 16:29 UTC
Labels: Component: ScrollView, Component: Text, Type: Bug Report

**Comment by KaviduAloka** [comment] 2020-02-10 07:51
`<Text style={{ **flexShrink: 1** }}></Text>`

**Comment by KaviduAloka** [comment] 2020-02-10 07:52
Add **flexShrink: 1**

<Text style={{ flexShrink: 1 }}></Text>
