### ISSUE TITLE
RN 0.42.0 can't make bundle file manually(both Android and iOS)

### ISSUE THREAD

**Issue by BaoBaoJianqiang** [facebook/react-native#13119] opened 2017-03-23 15:12 UTC
The script is:

react-native bundle --entry-file index.android.js --bundle-output ./bundle_android/index.android.jsbundle --platform android --assets-dest ./bundle_android/ --dev false

iOS can't make bundle file manually either.

I also check RN 0.38.0, I find it works.

**Comment by hramos** [comment] 2017-03-23 17:24
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-03-23 17:24 UTC
