### ISSUE TITLE
App collapse when reloading on android

### ISSUE THREAD

**Issue by narychen** [facebook/react-native#6687] opened 2016-03-28 06:35 UTC
It does not always happen but often happens when you reload the js bundles

```
26357-27166/com.eggf W/unknown:React: Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
03-28 14:24:44.154 26357-27166/com.eggf W/MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {42b9f710} sending message to a Handler on a dead thread
                                                        java.lang.RuntimeException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {42b9f710} sending message to a Handler on a dead thread
                                                            at android.os.MessageQueue.enqueueMessage(MessageQueue.java:309)
                                                            at android.os.Handler.enqueueMessage(Handler.java:623)
                                                            at android.os.Handler.sendMessageAtTime(Handler.java:592)
                                                            at android.os.Handler.sendMessageDelayed(Handler.java:563)
                                                            at android.os.Handler.post(Handler.java:323)
                                                            at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:60)
                                                            at com.facebook.react.bridge.ReactBridge.callFunction(Native Method)
                                                            at com.facebook.react.bridge.CatalystInstanceImpl$3.run(CatalystInstanceImpl.java:199)
                                                            at android.os.Handler.handleCallback(Handler.java:730)
                                                            at android.os.Handler.dispatchMessage(Handler.java:92)
                                                            at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                            at android.os.Looper.loop(Looper.java:137)
                                                            at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:184)
                                                            at java.lang.Thread.run(Thread.java:841)

```

The logcat also print the libc error  after the exception throw out from android java, 

```
03-28 14:24:44.844 26357-27573/com.eggf A/libc: Fatal signal 11 (SIGSEGV) at 0xbbadbeef (code=1), thread 27573 (mqt_js)
```

The same libc error I have reported before, but not the same situation. https://github.com/facebook/react-native/issues/6562#issuecomment-200079276

**Comment by christopherdro** [comment] 2016-09-12 15:46
@narychen Is this still an issue?

**Comment by narychen** [comment] 2016-09-13 01:56
@christopherdro I didn't pay further more attention to it. So let's close it.

**Comment by hyelong** [comment] 2016-09-16 17:24
I had the same exception after I called reactActivity.finish(). (reactActivity is an instance of ReactActivity)

**Comment by QuinnStephens** [comment] 2017-02-01 17:45
I have this same exception when I reload the JS after opening a SocketChannel in native Android code. Is there any way to avoid this?

**Comment by narychen** [comment] 2017-02-01 23:48
Which version did you use ?

**Comment by QuinnStephens** [comment] 2017-02-07 21:21
We're using 0.40.

**Comment by ignivahermenpreet** [comment] 2018-02-08 07:00
hello any updates? I am facing this error

**Comment by SudoPlz** [comment] 2018-03-16 12:00
This error is still an issue and the reason is that the `UIManager` creates a `ShadowNodeRegistry` that uses a `SingleThreadAsserter`.

https://github.com/facebook/react-native/blob/26684cf3adf4094eb6c405d345a75bf8c7c0bf88/ReactAndroid/src/main/java/com/facebook/react/common/SingleThreadAsserter.java#L23

The `SingleThreadAsserter` locks to the thread it was created with, but when the app reloads, that thread dies.
After the app has reloaded, all further calls to uiManager methods will result in that error.

Not sure what we can do about this, I've been struggling with that issue, and I can't find any way to replace that thread. This issue should be re-opened.

**Comment by SudoPlz** [comment] 2018-03-16 12:07
I opened a new issue here https://github.com/facebook/react-native/issues/18413

**Comment by hramos** [comment] 2018-03-20 19:56
Tracking in #18413

Duplicate of #18413

**Closed by hramos** 2018-03-20 19:56 UTC
Labels: :large_blue_diamond:Android, Ran Commands
