### ISSUE TITLE
Shake to open Dev Menu only work once in 0.36

### ISSUE THREAD

**Issue by albinhubsch** [facebook/react-native#10588] opened 2016-10-27 09:03 UTC
--- Please use this template, and delete everything above this line before submitting your issue --- 
### Description

In version 0.36 shake to open dev menu has stopped working as expected. It is possible to open dev menu by shaking device one time but doing it again will not open dev menu.
### Reproduction

The problem can easily be reproduced both on ios simulator and ios device. Shake to open dev menu. Cancel (or any other action), shake again to open dev menu does not work. Nothing will happen. To fix the app has to be closed and reopened. On simulator use hardware->shake gesture to simulate same behaviour.
### Additional Information
- React Native version: 0.36.0
- Platform: iOS
- Operating System: MacOS

**Comment by bganicky** [comment] 2016-10-27 14:25
Possibly duplicate of https://github.com/facebook/react-native/issues/10485?

**Comment by brentvatne** [comment] 2016-10-31 11:45
cc @frantic as @bganicky references fd554c31c7bcb2aae5c7d6a64e5bef9bedf56ebb as possibly being related

**Comment by frantic** [comment] 2016-11-08 00:50
@albinhubsch is it iPad or iPhone? Don't have time to look at this right now, but you can help by reverting https://github.com/facebook/react-native/commit/fd554c31c7bcb2aae5c7d6a64e5bef9bedf56ebb locally and checking if that fixes the issue.

**Comment by albinhubsch** [comment] 2016-11-08 07:32
@frantic don't know about iPad, but I experience this on iPhone 6 simulator and iPhone 5c device. I'll try that commit as soon as 0.37 lands.

**Comment by VojtechBartos** [comment] 2016-11-10 12:05
@frantic @albinhubsch both iPad and iPhone has been affected and it's been already fixed [here](https://github.com/facebook/react-native/issues/10676), but waiting for response from FB member

**Comment by VojtechBartos** [comment] 2016-11-30 08:01
@frantic @albinhubsch fix has been merged to master, so i believe it's going to be out with 0.40.0 release

**Closed** 2017-05-20 04:18 UTC
Labels: iOS
