### ISSUE TITLE
hot update issue.

### ISSUE THREAD

**Issue by chinaxiezhong** [facebook/react-native#14207] opened 2017-05-26 13:46 UTC
Hot updating will work fine If i create a class extends from React.Component directly.
But i got two issues about hot updating when debugging at local without extends from React.Component directly.
1. hot updating will not execute if i extends from React.PureComponent. And even it will throw an exception of  'Maximum call stack size exceeded'. Screen also would not made any change.
2. hot updating will not execute if i extends from self-defined Class that extends from React.Component. It will give same error like above.
I am not sure whether it is related the mechanism of hot updating? or anything else ?

**Comment by perfmlin** [comment] 2017-05-26 13:50
mark

**Comment by hramos** [comment] 2017-05-26 21:58
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-05-26 21:58 UTC
