### ISSUE TITLE
Only the original thread that created a view hierarchy can touch its views.

### ISSUE THREAD

**Issue by AkilLis** [facebook/react-native#16042] opened 2017-09-21 03:54 UTC
This "Only the original thread that created a view hierarchy can touch its views" error given after react native version upgrade 44.2 to 47.2. 

  Environment:
    OS:  ubuntu 16.04
    Node:  6.10.0
    npm:  3.10.10
    Watchman:  4.7.0
    Android Studio:  2.3 AI-162.4069837

  Packages: (wanted => installed)
    react-native: 0.44.2 => 0.47.2
    react: 16.0.0-alpha.12 => 16.0.0-alpha.12

  Target Platform: Android (6.0.0)

**Comment by hramos** [comment] 2017-09-21 15:21
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue that meets the requirements set forth in the template. Thanks!

**Closed by hramos** 2017-09-21 15:21 UTC

**Comment by jhalborg** [comment] 2017-10-17 10:06
I second this. Using Expo SDK 21 along with TypeScript 2.5, and getting consistent crashes on recompilation each time on Android.

I found my issue by viewing the stacktrace I could send to the dev (through the Android report bug feature). It was due to the following call:

abi21_0_0.com.facebook.react.devsupport.DebugOverlayController.setFpsDebugViewVisible(DebugOverlayConroller.java:49)

By turning off the Inspector module (for FPS perf etc), Expo stopped crashing.

**Comment by ThaJay** [comment] 2017-10-19 11:46
It happens on every reload from the dev server for me.
```
"react-native": "^0.48.4",
"react": "^16.0.0",
```
```
E/AndroidRuntime(17714): FATAL EXCEPTION: main
E/AndroidRuntime(17714): Process: com.chipta, PID: 17714
E/AndroidRuntime(17714): android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
E/AndroidRuntime(17714): 	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7093)
E/AndroidRuntime(17714): 	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1076)
E/AndroidRuntime(17714): 	at android.view.View.requestLayout(View.java:17416)
E/AndroidRuntime(17714): 	at android.view.ViewGroup.removeAllViews(ViewGroup.java:4198)
E/AndroidRuntime(17714): 	at com.facebook.react.devsupport.DebugOverlayController.setFpsDebugViewVisible(DebugOverlayController.java:49)
E/AndroidRuntime(17714): 	at com.facebook.react.devsupport.DevSupportManagerImpl.resetCurrentContext(DevSupportManagerImpl.java:610)
E/AndroidRuntime(17714): 	at com.facebook.react.devsupport.DevSupportManagerImpl.onReactInstanceDestroyed(DevSupportManagerImpl.java:516)
E/AndroidRuntime(17714): 	at com.facebook.react.ReactInstanceManager.tearDownReactContext(ReactInstanceManager.java:941)
E/AndroidRuntime(17714): 	at com.facebook.react.ReactInstanceManager.runCreateReactContextOnNewThread(ReactInstanceManager.java:793)
E/AndroidRuntime(17714): 	at com.facebook.react.ReactInstanceManager.recreateReactContextInBackground(ReactInstanceManager.java:782)
E/AndroidRuntime(17714): 	at com.facebook.react.ReactInstanceManager.onReloadWithJSDebugger(ReactInstanceManager.java:754)
E/AndroidRuntime(17714): 	at com.facebook.react.ReactInstanceManager.access$000(ReactInstanceManager.java:109)
E/AndroidRuntime(17714): 	at com.facebook.react.ReactInstanceManager$1.onReloadWithJSDebugger(ReactInstanceManager.java:157)
E/AndroidRuntime(17714): 	at com.facebook.react.devsupport.DevSupportManagerImpl.reloadJSInProxyMode(DevSupportManagerImpl.java:805)
E/AndroidRuntime(17714): 	at com.facebook.react.devsupport.DevSupportManagerImpl.handleReloadJS(DevSupportManagerImpl.java:650)
E/AndroidRuntime(17714): 	at com.facebook.react.devsupport.DevSupportManagerImpl$5.onOptionSelected(DevSupportManagerImpl.java:372)
E/AndroidRuntime(17714): 	at com.facebook.react.devsupport.DevSupportManagerImpl$15.onClick(DevSupportManagerImpl.java:470)
E/AndroidRuntime(17714): 	at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1017)
E/AndroidRuntime(17714): 	at android.widget.AdapterView.performItemClick(AdapterView.java:308)
E/AndroidRuntime(17714): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1510)
E/AndroidRuntime(17714): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3472)
E/AndroidRuntime(17714): 	at android.widget.AbsListView$3.run(AbsListView.java:4835)
E/AndroidRuntime(17714): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(17714): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(17714): 	at android.os.Looper.loop(Looper.java:146)
E/AndroidRuntime(17714): 	at android.app.ActivityThread.main(ActivityThread.java:5653)
E/AndroidRuntime(17714): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(17714): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(17714): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
E/AndroidRuntime(17714): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
E/AndroidRuntime(17714): 	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by ephor** [comment] 2017-11-13 12:43
Also have this error on React-native 0.50.3 and android 8

**Comment by ThaJay** [comment] 2017-11-14 13:31
@hramos reopen?

**Comment by 98ki** [comment] 2017-11-22 10:46
@hramos
same question,
I quick repeat click one button on Android, it will show my toast repeat,  in a minute,  crash.
`ndroid.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
                                                                                at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7361)
                                                                                at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1156)
                                                                                at android.view.View.requestLayout(View.java:19841)
                                                                                at android.view.View.requestLayout(View.java:19841)
                                                                                at android.widget.TextView.checkForRelayout(TextView.java:7688)
                                                                                at android.widget.TextView.setText(TextView.java:4585)
                                                                                at android.widget.TextView.setText(TextView.java:4442)
                                                                                at android.widget.TextView.setText(TextView.java:4417)
                                                                                at com.xsl.kit.utils.ToastWrapper.updateToast(ToastWrapper.java:61)`

**Comment by Venryx** [comment] 2017-12-07 14:36
I also have this issue, with Android 7, and:
```
"react": "^16.2.0",
"react-native": "^0.51.0",
```

It is fixed when I disable the performance-monitor overlay.

**Comment by CodingJbz** [comment] 2017-12-25 03:59
thanks for @Venryx , it's works to me

**Comment by amosyuen** [comment] 2018-01-16 02:49
@Venryx How do you disable the performance monitor overlay? Is it by shaking the phone and clicking the "Hider Perf Monitor"? I already did that, but still running into this error.

**Comment by Venryx** [comment] 2018-01-16 04:12
Yes, that's what fixed it for me. Must be another root-cause in your case.

**Comment by MariusMeiners** [comment] 2018-02-20 10:59
I think the combination that breakes the System is having JS Dev Mode deactivated and Show performance Monitor true. Either one on its own seems to be working fine...

**Comment by mirsujat** [comment] 2018-03-03 11:31
Only the original thread that created a view hierarchy can touch its views.
checkThread
    ViewRootImpl.java:6357
requestLayout
    ViewRootImpl.java:874
requestLayout
    View.java:17476
removeAllViews
    ViewGroup.java:4345
setFpsDebugViewVisible
    DebugOverlayController.java:115
resetCurrentContext
    DevSupportManagerImpl.java:599
onNewReactContextCreated
    DevSupportManagerImpl.java:523
setupReactContext
    ReactInstanceManager.java:995
access$1300
    ReactInstanceManager.java:113
run
    ReactInstanceManager.java:965
handleCallback
    Handler.java:739
dispatchMessage
    Handler.java:95
dispatchMessage
    MessageQueueThreadHandler.java:31
loop
    Looper.java:135
run
    MessageQueueThreadImpl.java:194
run
    Thread.java:818

**Comment by mirsujat** [comment] 2018-03-03 11:32
{
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "dependencies": {
    "expo": "^25.0.0",
    "react": "16.2.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz",
    "react-navigation": "^1.3.2"
  }
}

**Comment by jasonh9** [comment] 2018-03-22 01:51
Show performance monitor = true caused this issue for me.

**Comment by macloving** [comment] 2018-04-22 19:43
I am sorry, but how you click on the "Hider Perf Monitor"?
I have android 7.0 version. I cannot do it. Please, help me.

> @Venryx How do you disable the performance monitor overlay? Is it by shaking the phone and clicking the "Hider Perf Monitor"? I already did that, but still running into this error.

**Comment by guilhermemauro** [comment] 2018-04-30 13:29
Hide Perf Monitor works for me.

**Comment by dapperAuteur** [comment] 2018-05-29 19:57
I got the same issue. I shut down the server and restarted it and the issue went away.

**Comment by joshuapinter** [comment] 2018-06-17 23:19
Toggling the "Perf Monitor" off solved the issue for me.

To do this you can use the following `adb` command to bring up the menu (or shake your device):

```bash
adb shell input keyevent KEYCODE_MENU
```
Then you'll see "Hide Perf Monitor". Press that to hide it.

![2018-06-16_23-29-15](https://user-images.githubusercontent.com/180819/41513042-8f01d04a-7252-11e8-8fff-0debba493c8a.png)

**Comment by ricardobeat** [comment] 2018-08-20 14:29
Having the same issue. So Performance Monitor cannot be used along Live Reload? :(

**Comment by tereshchenkoartyom94** [comment] 2018-09-05 11:15
Same issue? Are you going to fix it?

**Comment by andretf** [comment] 2018-09-08 17:55
It seems it has been solved in https://github.com/facebook/react-native/pull/17544, in version 0.57.
