### ISSUE TITLE
The Text component can not flat wrap.

### ISSUE THREAD

**Issue by ATShiTou** [facebook/react-native#22888] opened 2019-01-07 10:43 UTC
## Environment
[skip envinfo]

## Description

I tried to show a URL by the Text component. But it wraps with huge blank on the right of the component. I have read all the doc but can not find any props to configure it.

![2019-01-07 5 42 32](https://user-images.githubusercontent.com/38748693/50763882-aa70d000-12a3-11e9-853a-4c1fcf0a923f.png)

## Reproducible Demo
It does not need any reproducible demos.

**Comment by kelset** [comment] 2019-03-19 12:46
Duplicate of #1438

**Closed by kelset** 2019-03-19 12:46 UTC
Labels: Type: Bug Report

**Comment by tanqq1** [comment] 2020-01-15 06:38
I have the same problem, so how to solve it？
