### ISSUE TITLE
adb server version (32) doesn't match this client (36); killing...

### ISSUE THREAD

**Issue by Rebaiahmed** [facebook/react-native#13018] opened 2017-03-19 11:05 UTC
hi i get this error 
![capt](https://cloud.githubusercontent.com/assets/13053759/24080292/46f90d6c-0c9c-11e7-9487-8f390f27be1d.png)

**Comment by rmevans9** [comment] 2017-03-20 00:14
Are you using Genymotion per chance?

**Comment by hramos** [comment] 2017-03-20 16:32
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-03-20 16:32 UTC
