### ISSUE TITLE
[TextInput Android] duplicated input

### ISSUE THREAD

**Issue by Yadro** [facebook/react-native#12715] opened 2017-03-05 07:22 UTC
When I enter text in textinput, he duplicated in the console and Enter only sends to the console.

![](https://dl.dropboxusercontent.com/s/apphgbxmrepez52/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202017-03-05%2010.06.20.png?dl=0)

### Additional Information

* React Native version: 0.42
* Platform: Android, Genymotion Emulator
* Operating System: Windows

**Comment by ericvicenti** [comment] 2017-03-06 02:00
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by ericvicenti** 2017-03-06 02:00 UTC
