### ISSUE TITLE
iOS build fails if path of a project path includes a space

### ISSUE THREAD

**Issue by owinter86** [facebook/react-native#22354] opened 2018-11-20 13:06 UTC
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
    System:
      OS: macOS 10.14.1
      CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
      Memory: 317.20 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 26, 27, 28
        Build Tools: 26.0.3, 27.0.3, 28.0.2, 28.0.3
        System Images: android-26 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1
      react-native: 0.57.5 => 0.57.5
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
## Description
If any folder within your project directory contains a space the build will fail, a new react native project was created in folder `untitled` and built with no issues, and another created in folder `untitled folder` and failed to find a file within the directory.

`../Documents/untitled folder/test/node_modules/react-native/scripts/ios-install-third-party.sh: line 56: /ios-configure-glog.sh: No such file or directory`

## Reproducible Demo
This is reproducible if you create a new RN project in a folder with a space.

**Comment by radko93** [comment] 2018-11-21 17:58
@owinter86 can you try `react-native init projectname --version react-native@0.57.4` and let me know if this also happens?

**Comment by owinter86** [comment] 2018-11-22 10:13
@radko93 I can confirm that this issue was introduced in 0.57.5 and this does not occur on 0.57.4.

**Comment by radko93** [comment] 2018-11-22 11:17
@kelset I think it's a regression from the Xcode fix

**Comment by kelset** [comment] 2018-11-22 11:30
uhm yeah it looks like it :/

But i can't really understand why 🤔

cc @mmccartney

**Comment by radko93** [comment] 2018-11-22 11:36
I also couldn't really get why but that's the only change that's related.
@kelset it's not about the project name, it's about the path.

**Comment by kelset** [comment] 2018-11-22 11:47
Probably related / could give context: https://github.com/wix/detox/issues/894

**Comment by radko93** [comment] 2018-11-22 13:15
@kelset probably not related as we don't use node for running script.
Running:
```
cd node_modules/react-native && scripts/ios-install-third-party.sh && cd third-party && cd glog-0.3.5 && ./configure && cd ../../../../
```
works with any path so it has to be something with how xcode runs the script.
It might be [here](https://github.com/facebook/react-native/commit/277c19c93eacf3e3ce63f71236fd399214d6e6d0#diff-883359f85083d00b7266ec2acebcca9fR4145) but maybe @mmccartney will know more about it

**Comment by thymikee** [comment] 2019-03-19 15:03
Hello there 👋 by using the repro / the list of steps to reproduce, we can't actually see the reported bug on RN 0.59 so we'll close this issue. It may have something to do with your local setup, please double check that you are using the correct version of Android Studio / XCode / Android NDK / Yarn / etc.

**Closed by thymikee** 2019-03-19 15:03 UTC
Labels: Impact: Regression, Low-Pri, Platform: iOS, Type: Bug Report, 📮Known Issues

**Comment by canpoyrazoglu** [comment] 2019-05-15 16:47
Same issue here. Lost about 5 hours because of this bug. I've removed the space from my project's path and everything worked perfectly.

**Comment by Bersaelor** [comment] 2019-06-25 13:29
Just wasted another 2h on this exact same issue. 
`"react-native": "0.59.5",`, Xcode 10.2.1

**Comment by thymikee** [comment] 2019-06-25 13:44
@Bersaelor @canpoyrazoglu I think I stated clearly that I couldn't reproduce the issue. If you still face it, it's likely because of some environmental differences. Without that information, I'm unable to help more. Please provide clear reproduction steps (repo, env info etc) on a smallest possible example and if you're sure it's a bug somewhere in RN or CLI, file a new issue accordingly. Otherwise it's not actionable.
