### ISSUE TITLE
gradle.bat (access is denied) when running react-native run-android

### ISSUE THREAD

**Issue by vdcautomation** [facebook/react-native#17904] opened 2018-02-08 08:04 UTC
I'm hitting error after running react-native run-android, it hits the error after unzipping gradle file.

C:\projects\myapp>react-native run-android
Scanning folders for symlinks in C:\projects\myapp\node_modules (62ms)
JS server already running.
Building and installing the app on the device (cd android && gradlew.bat installDebug)...
Deleting directory C:\Users\hoich\.gradle\wrapper\dists\gradle-4.1-all\38gmb0xnu6gupohgu61ilzbig\gradle-4.1
Unzipping C:\Users\hoich\.gradle\wrapper\dists\gradle-4.1-all\38gmb0xnu6gupohgu61ilzbig\gradle-4.1-all.zip to C:\Users\hoich\.gradle\wrapper\dists\gradle-4.1-all\38gmb0xnu6gupohgu61ilzbig
Exception in thread "main" java.io.FileNotFoundException: C:\Users\hoich\.gradle\wrapper\dists\gradle-4.1-all\38gmb0xnu6gupohgu61ilzbig\gradle-4.1\bin\gradle.bat (Access is denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at org.gradle.wrapper.Install.unzip(Install.java:172)
        at org.gradle.wrapper.Install.access$500(Install.java:26)
        at org.gradle.wrapper.Install$1.call(Install.java:69)
        at org.gradle.wrapper.Install$1.call(Install.java:46)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:46)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by vdcautomation** [comment] 2018-02-08 08:11
![image](https://user-images.githubusercontent.com/36259119/35961989-abbc52aa-0cea-11e8-90b8-d0ca9657302d.png)

**Comment by vdcautomation** [comment] 2018-02-09 02:35
sorry but would like to ask does anyone helping me to look on the issue?

**Comment by hramos** [comment] 2018-02-09 20:41
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue that meets the requirements set forth in the template. Thanks!

**Closed by hramos** 2018-02-09 20:41 UTC
Labels: Failed Commands
