### ISSUE TITLE
buildReactNdkLib error while building from source post react-native@0.55.0

### ISSUE THREAD

**Issue by karthikpala** [facebook/react-native#18833] opened 2018-04-12 23:29 UTC
- [Yes followed instructions @ https://facebook.github.io/react-native/docs/building-from-source.html#building-the-source ] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [ Yes ] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [  Using 0.55.0 stable release] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

As I made some changes in ReactAndroid code, I am building from the source from version 0.52.0
Recently I have upgraded to @latest release 0.55.0, the build from source is failing in :react-native-android:buildReactNdkLib step of the compilation.

Here is the error from console

```
[armeabi-v7a] Compile++ thumb: fb <= jni_helpers.cpp
[armeabi-v7a] Compile++ thumb: fb <= LocalString.cpp
[armeabi-v7a] Compile++ thumb: fb <= OnLoad.cpp
[armeabi-v7a] Compile++ thumb: fb <= References.cpp
[armeabi-v7a] Compile++ thumb: fb <= WeakReference.cpp
[armeabi-v7a] Compile++ thumb: fb <= log.cpp
[armeabi-v7a] Compile++ thumb: fb <= lyra.cpp
[armeabi-v7a] Compile++ thumb: fb <= onload.cpp
[armeabi-v7a] Compile++ thumb: yogacore <= Utils.cpp
[armeabi-v7a] Compile++ thumb: yogacore <= YGEnums.cpp
[armeabi-v7a] Compile++ thumb: yogacore <= YGLayout.cpp
[armeabi-v7a] Compile++ thumb: yogacore <= YGNode.cpp

C:/Users/palakart/WorkSpace/RNDemo-master/RNApp/node_modules/react-native/ReactAndroid/../ReactCommon/yoga/yoga/YGEnums.cpp:226:1: 
fatal error: opening dependency file C:\Users\palakart\WorkSpace\RNDemo-master\RNApp\node_modules\react-native\ReactAndroid\build\tmp\buildReactNdkLib/local/armeabi-v7
a/objs/yogacore/C_/Users/palakart/WorkSpace/RNDemo-master/RNApp/node_modules/react-native/ReactAndroid/__/ReactCommon/yoga/yoga/YGEnums.o.d: No such file or directory}
compilation terminated.
[armeabi-v7a] Compile++ thumb: yogacore <= YGNodePrint.cpp


C:/Users/palakart/WorkSpace/RNDemo-master/RNApp/node_modules/react-native/ReactAndroid/../ReactCommon/yoga/yoga/Utils.cpp:51:1: 
fatal error: opening dependency file 
C:\Users\palakart\WorkSpace\RN-Demo-master\RNApp\node_modules\react-native\ReactAndroid\build\tmp\buildReactNdkLib/local/armeabi-v7a/objs/yogacore/C_/Users/palakart/WorkSpace/RN-Demo-master/RNApp/node_modules/react-native/ReactAndroid/__/ReactCommon/yoga/yoga/Utils.o.d: No such file or directory
 }
 ^

```

When I try to downgrade to 0.52.0 it is working fine.
The yogacore folder is never seen in the build\tmp\buildReactNdkLib/local/armeabi-v7a/objs/yogacore folder. Please suggest.

## Environment
Environment:
  OS: Windows 10
  Node:
  Yarn: Not Found
  npm:
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.0 => 16.3.0
  react-native: ^0.55.0 => 0.55.0

## Steps to Reproduce
Change react-native version to 0.55.0 (or) 0.54.0 and try to build from source

**Comment by karthikpala** [comment] 2018-04-27 10:50
@hramos Can you let me know if anyone of the contributors can look into this. Thanks

**Comment by woshi82** [comment] 2018-07-02 06:39
+1
I have upgrade react-native 0.50.0 to 0.55.0, and the build from source is failing in :react-native-android:buildReactNdkLib step of the compilation.

Build from source in  0.50.0 is fine.
Here is the error from console
```
25>E:/My_project_path/node_modules/react-native/ReactAndroid/../ReactCommon/yoga/yoga/YGEnums.cpp:226:1: fatal error: opening dependency file E:\My_project_path2\ReactAndroid\tmp\buildReactNdkLib/local/armeabi-v7a/objs/yogacore/E_/My_project_path/node_modules/react-native/ReactAndroid/__/ReactCommon/yoga/yoga/YGEnums.o.d: No such file or directory
25> }
25> ^
25>compilation terminated.
25>make.exe: *** [E:\My_project_path2\ReactAndroid\tmp\buildReactNdkLib/local/armeabi-v7a/objs/yogacore/E_/My_project_path/node_modules/react-native/ReactAndroid/__/ReactCommon/yoga/yoga/YGEnums.o] Error 1
25>make.exe: *** Waiting for unfinished jobs....
25>E:/My_project_path/node_modules/react-native/ReactAndroid/../ReactCommon/yoga/yoga/Utils.cpp:51:1: fatal error: opening dependency file E:\My_project_path2\ReactAndroid\tmp\buildReactNdkLib/local/armeabi-v7a/objs/yogacore/E_/My_project_path/node_modules/react-native/ReactAndroid/__/ReactCommon/yoga/yoga/Utils.o.d: No such file or directory
25> }
25> ^
25>compilation terminated.
25>make.exe: *** [E:\My_project_path2\ReactAndroid\tmp\buildReactNdkLib/local/armeabi-v7a/objs/yogacore/E_/My_project_path/node_modules/react-native/ReactAndroid/__/ReactCommon/yoga/yoga/Utils.o] Error 1
25>make.exe: Leaving directory `E:/My_project_path/node_modules/react-native/ReactAndroid/src/main/jni/react/jni'
25>:ReactAndroid:buildReactNdkLib FAILED
25>
25>FAILURE: Build failed with an exception.
25>
25>* What went wrong:
25>Execution failed for task ':ReactAndroid:buildReactNdkLib'.
25>> Process 'command 'C:\ProgramData\Microsoft\AndroidNDK64\android-ndk-r10e\ndk-build.cmd'' finished with non-zero exit value 2
25>
```

**Comment by woshi82** [comment] 2018-07-02 09:16
I have try 0.52.0 ,is OK. 0.53.0

**Comment by karthikpala** [comment] 2018-07-03 15:03
@woshi82 Yes even I'm stuck at 0.52.0 and no other latest build is working. From that error I understand that an ndk folder is missing from the source code. I hope react native core team is aware of this issue 😢 
Let me know if you can find any alternative solution for this.

**Comment by ej3** [comment] 2018-07-06 22:21
This is an issue with the windows [MAX_PATH](https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file#maximum-path-length-limitation).  Even if you [enable long paths](https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/) in Windows 10, the `android-ndk-r10e` will not interpret the paths correctly.  This is not an issue with `react-native`, it's an issue with the NDK.  There have been efforts to fix the issue in portions of the toolchain (android-ndk/ndk/issues/478).  I don't really comprehend the stack over there, and I can't immediately invest the time to figure out what needs to be changed.  I can confirm it has been fixed in some of the tools even in `android-ndk-10e` (`llvm-3.6/prebuilt/windows-x86_64/bin/clang++.exe` seems to work for me!), but not enough of them to work in this context.

I put more yammering into my [stackoverflow response](https://stackoverflow.com/a/51218163/622128) to the same issue, which is where this problem fits more naturally, I even recommend several ways to work around the issue effectively.

This issue should probably be closed here.

**Comment by woshi82** [comment] 2018-07-11 08:16
Yeah, it's work for me. Thank you.
I am in window 10.
Just set the `buildDir` ' s value in `build.gradle` of my android root project more near to the root dir.
```
// build.gradle

allprojects {
    repositories {
        ....
    }
   buildDir = "../../../../../../../../BuildOutput/${rootProject.name}/${project.name}"
}

```

**Comment by kelset** [comment] 2018-07-11 09:15
Closing since @ej3 provided the valid solution, thanks Evan.

**Closed by kelset** 2018-07-11 09:15 UTC
Labels: :large_blue_diamond:Android
