### ISSUE TITLE
Yarn android

### ISSUE THREAD

**Issue by Zarinia** [facebook/react-native#44205] opened 2024-04-23 09:57 UTC
### Description

first create clean project by:
npx react-native@latest init test
then run:
yarn
yarn start
run ios very well but when run android fails on line:
Task :app:checkDebugAarMetadata

### Steps to reproduce

npx react-native@latest init test
yarn
yarn start

### React Native Version

0.74

### Affected Platforms

Runtime - Android, Build - MacOS

### Areas

Other (please specify)

### Output of `npx react-native info`

```text
...
System:
  OS: macOS 14.5
  CPU: (12) arm64 Apple M2 Max
  Memory: 98.33 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.7.3
    path: ~/.nvm/versions/node/v21.7.3/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v21.7.3/bin/yarn
  npm:
    version: 10.5.0
    path: ~/.nvm/versions/node/v21.7.3/bin/npm
  Watchman:
    version: 2024.03.25.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK:
    API Levels:
      - "31"
      - "33"
      - "34"
    Build Tools:
      - 23.0.3
      - 30.0.3
      - 33.0.1
      - 34.0.0
      - 35.0.0
    System Images:
      - android-31 | ARM 64 v8a
      - android-34 | ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.8
    path: /Users/ar.zarinia/.sdkman/candidates/java/current/bin/javac
  Ruby:
    version: 3.3.0
    path: /opt/homebrew/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.0
    wanted: 0.74.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
...
```

### Stacktrace or Logs

```text
> Task :gradle-plugin:checkKotlinGradlePluginConfigurationErrors
> Task :gradle-plugin:pluginDescriptors
> Task :gradle-plugin:processResources
> Task :gradle-plugin:compileKotlin
> Task :gradle-plugin:compileJava NO-SOURCE
> Task :gradle-plugin:classes
> Task :gradle-plugin:jar
> Task :app:checkKotlinGradlePluginConfigurationErrors
> Task :app:generateCodegenSchemaFromJavaScript SKIPPED
> Task :app:generateCodegenArtifactsFromSchema SKIPPED
> Task :app:generatePackageList
> Task :app:preBuild
> Task :app:preDebugBuild
> Task :app:generateDebugBuildConfig
> Task :app:checkDebugAarMetadata
```

### Reproducer

---

**Comment by cortinico** [comment] 2024-04-23 09:58
Closing as you provided no information on which failure you had.
I believe this is a duplicate of https://github.com/facebook/react-native/issues/44177

**Closed by cortinico** 2024-04-23 09:58 UTC
Labels: Platform: Android, Needs: Author Feedback, Needs: Repro, Type: New Architecture, Needs: Version Info
