### ISSUE TITLE
Bundling failed: Error: unable to resolve module 'accessbilityInfo' 

### ISSUE THREAD

**Issue by karthikgk** [facebook/react-native#20241] opened 2018-07-17 05:25 UTC
This might be related to https://github.com/facebook/react-native/issues/4968 
To resolve 
  - [x] Clear watchman watches: 'watchman watch-del-all'
  - [x] delete the 'node_modules' folder: 'rm -rf node_modules && npm install'
  - [x] Reset metro blunder cache

## Environment
 react-native-cli: 2.0.1
 react-native: 0.56.0
 node : v8.11.2
 npm : 5.6.0
 Windows : 10 

## Description
    I am new to React native. i just follow the steps given in the following URL https://habiletechnologies.com/blog/getting-started-react-native-complete-setup-guide/.
 
   When i was trying to navigate one page to another page, i got the above issue. I couldn't overcome this for the past two days. Please help me to solve the issue 
 
Package.Json

{
  "name": "TestApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.4.1",
    "react-native": "0.56.0"
  },
  "devDependencies": {
    "babel-jest": "23.4.0",
    "babel-preset-react-native": "5.0.2",
    "jest": "23.4.1",
    "react-test-renderer": "16.4.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by kelset** [comment] 2018-07-19 10:58
Duplicate of #19953

**Closed by kelset** 2018-07-19 10:58 UTC
Labels: :clipboard:No Environment Info
