### ISSUE TITLE
This error happens all the time on 0.59.0+ versions

### ISSUE THREAD

**Issue by xlbeat** [facebook/react-native#24201] opened 2019-03-29 13:06 UTC
![erro android](https://user-images.githubusercontent.com/48661247/55234588-64ccff00-5223-11e9-8675-91e41b0c35aa.jpg)
Hi everybody.
I'm kind of new to react-native but I already did some small projects to learn from it.
However, in the last versions of react-native I am getting this error.
So, from 0.59.0+ I'm always getting this error. This is a new computer, so I am assuming no conflicts of software exist in here as this PC was specifically built to build react-native apps and seems to be fine on versions below 0.59.0.
I'm posting this here because I'm preety sure someone else might be facing this issue. And I'm getting this error to NEW projects. So I really think this is related to react-native dependencies.
Thanks for your help.
PS: I'm new to github, so I'm sorry if I'm not posting this on the right spot.
windows 10 64bits. JDK: 1.8.0_201

**Comment by kelset** [comment] 2019-03-29 16:52
Duplicate of https://github.com/facebook/react-native/issues/24112

**Closed by kelset** 2019-03-29 16:52 UTC
Labels: Ran Commands, Resolution: Needs More Information, Type: Bug Report
