### ISSUE TITLE
RefreshControl gesture conflicts with vertical inner ScrollView gesture when there is another Scrollview outter

### ISSUE THREAD

**Issue by walkerXiong** [facebook/react-native#13636] opened 2017-04-24 07:35 UTC
just like this: 
`<ScrollView refreshControl={}>`
`<ScrollView>`
`</ScrollView>`
`</ScrollView>`

when pull down the inner ScrollView , the inner ScrollView will not scroll as it should, but trigger the refreshControl. 

thanks!

**Comment by hramos** [comment] 2017-04-24 12:54
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-04-24 12:54 UTC
