### ISSUE TITLE
I am frist use react native ,I have a problem ,Cannot find entry file index.android.js in any of the roots

### ISSUE THREAD

**Issue by hahai23456789** [facebook/react-native#14960] opened 2017-07-12 00:20 UTC
{"message":"Cannot find entry file index.android.js in any of the roots: [\"D:\\\\OK\"]","name":"NotFoundError","type":"NotFoundError","status":404,"errors":[{}]}

I use win7 ,

![image](https://user-images.githubusercontent.com/23414297/28096641-f99938e4-66dc-11e7-8af5-7fb4a431dc08.png)

**Comment by hramos** [comment] 2017-07-12 07:10
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-07-12 07:10 UTC
