### ISSUE TITLE
Question about invalidate in RCTRootContentView

### ISSUE THREAD

**Issue by PuffLady** [facebook/react-native#35511] opened 2022-11-30 02:03 UTC
### Description

Why do you write this code, what problem is it to solve, can you tell me, thank you very much

`- (void)invalidate
{
  if (self.userInteractionEnabled) { // this line 
    self.userInteractionEnabled = NO; // this line 
    [(RCTRootView *)self.superview contentViewInvalidated]; //  and this line 

    [_bridge enqueueJSCall:@"AppRegistry"
                    method:@"unmountApplicationComponentAtRootTag"
                      args:@[ self.reactTag ]
                completion:NULL];
  }
}`

### Version

0.71.0

### Output of `npx react-native info`

none

### Steps to reproduce

none

### Snack, code example, screenshot, or link to a repository

none

**Comment by cortinico** [comment] 2022-11-30 07:19
Also a duplicate of https://github.com/facebook/react-native-website/issues/3443

**Closed** 2022-11-30 07:19 UTC
Labels: Type: Question, Needs: Triage :mag:
