### ISSUE TITLE
Crash SIGSEGV in libjsc.so on Android

### ISSUE THREAD

**Issue by jocoders** [facebook/react-native#31274] opened 2021-03-30 10:14 UTC
## Description
Crash report from firebase crashlytics in the production mode on Android 10 with Huawei and Xiaomi devices

> Crashed: Thread :  SIGSEGV  0x0000000000000010
#00 pc 0x73121a9748 libjsc.so 
#01 pc 0x73121f5fe8 libjsc.so 
#02 pc 0x7407046ba8 libc.so 

## React Native version:
react-native 0.63.2

## Steps To Reproduce
I have just a crash report from firebase crashlytics in the production mode. In the develop mode it is not possible to catch it. No steps! 

## Expected Results
The app does not crash.

<img width="419" alt="Screenshot 2021-03-30 at 13 14 18" src="https://user-images.githubusercontent.com/41040813/112973315-da913b80-9159-11eb-91d2-77d22c7627df.png">

**Comment by mikehardy** [comment] 2021-03-31 12:59
The JSC is the javascript engine. I think you would need the actual javascript that caused the crash reproducibly, posted as a minimal reproducible example, on the JSC project's bug tracker?

**Comment by rolfb** [comment] 2021-08-11 07:58
This is the most frequent crash on my apps, but haven't been able to reproduce it locally. Is there any way to log the crash better?

**Comment by balwinders** [comment] 2022-01-31 05:53
Same issue, any update?

**Comment by RajeshRRathod** [comment] 2022-03-09 13:40
same crash in my app and i m not able to reproduce.

**Comment by rolfb** [comment] 2022-03-09 13:56
not exactly a fix, but we switched to use Hermes instead of JSC which prevents this.

**Comment by cortinico** [comment] 2022-03-10 12:23
> I think you would need the actual javascript that caused the crash reproducibly, posted as a minimal reproducible example, on the JSC project's bug tracker?

Thanks for pointing this out @mikehardy That's the correct solution.
Given that using Hermes here fixes the problem, I'm going to close this issue. Please move to the JSC issue tracker or reopen an issue here if it's affecting both engines.

**Closed by cortinico** 2022-03-10 12:23 UTC
Labels: Needs: Triage :mag:

**Comment by ahtokca** [comment] 2022-10-05 20:19
Looks lite the issue is back
have a crash on Galaxy S20 5G/Note10 Lite/A22 5G/Galaxy A53 5G/Galaxy S10+/Galaxy S22/Galaxy A52s 5G/Galaxy S21 Ultra 5G/Galaxy S21 Ultra 5G/Pretty much all samsungs, android 12 and react 0.63.4

```
Crashed: Thread :  SIGSEGV  0x0000000000000040
#00 pc 0x646bbc libjsc.so 
#01 pc 0x71ef7c85cc  
#02 pc 0xf540 libart.so 
#03 pc 0xf540 libart.so
```

**Comment by mikehardy** [comment] 2022-10-05 20:49
> 0.63.4

I don't believe this version is supportable at all - please see if you can reproduce on current https://github.com/facebook/react-native/releases
