### ISSUE TITLE
onLongPress for Text is not working

### ISSUE THREAD

**Issue by chppeng** [facebook/react-native#24081] opened 2019-03-21 07:44 UTC
## 🐛 Bug Report
After upgrading from React Native 0.58.6 t0 0.59.0 or 0.59.1, onLongPress for Text is not working. I tested in IOS, it is not working. But it works well with 0.58.6

## To Reproduce
Use Text with onLongPress in React Native 0.59.0 or 0.59.1 app, 

## Code Example
` <Text style={styles.welcome} onLongPress={()=>{alert('TestA')}}>Welcome to React Native!</Text>
`

## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 24.48 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 26, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-24 | Google APIs Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.1 => 0.59.1

**Comment by danilobuerger** [comment] 2019-03-21 12:17
Duplicate of #24001 ?

**Comment by Salakar** [comment] 2019-03-21 13:04
Hey @chppeng 👋 - thanks for reporting. As @danilobuerger mentioned; this is a duplicate of #24001 (Text internally consumes Touchable). I will close this issue now - please follow up on the other issue.

**Closed** 2019-03-21 13:04 UTC
Labels: Component: Text, Component: TouchableWithoutFeedback, Resolution: Duplicate, Type: Bug Report
