### ISSUE TITLE
TextInput crashes an app if Samsung Keyboard uses Predictive Text & Suggest text corrections

### ISSUE THREAD

**Issue by BohdanSol** [facebook/react-native#33139] opened 2022-02-18 08:42 UTC
### Description

Main issue: Generated release .apk TextInput crash the app on Samsung when Predictive Text & Suggest text corrections is activated.
React-native versions checked: 0.63.3, 0.67.2
Phones produced the issue: Samsung S20 Ultra, Samsung Galaxy S21 Plus
**Another possible issue:** For all the crashes captured some parts of the text were underlined green or red, maybe the issue is with that suggestions...
It was first produced by the production project based on 0.63.3v, then I created bare 0.67.2v project and added simple TextInput, and the issue still exists. Attaching a video so everybody can replicate.

![Screenshot_20220216-094239_Samsung_Keyboard](https://user-images.githubusercontent.com/48454610/154644510-a89b851f-2152-4c4c-8451-1f0ecaee54bd.jpeg)

https://user-images.githubusercontent.com/48454610/154644390-61bdd58c-e647-422d-b69b-c26dda88e721.mp4
 

### Version

0.63.3, 0.67.2

### Output of `npx react-native info`

System:
    OS: macOS 12.2.1
    CPU: (8) arm64 Apple M1
    Memory: 439.56 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.2.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
    Watchman: 2021.12.13.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 29, 30, 32
      Build Tools: 28.0.3, 29.0.2, 30.0.0, 30.0.2, 32.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-32 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.2 => 0.67.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Get my repo: https://github.com/BohdanSol/projectTwo
2. `yarn install`
3. Generate keystore, put it inside `android>app`. Change values regarding keystore inside `gradlew.properties`
4. From root cd `android && ./gradlew assembleRelease`
5. Test generated apk in real device

### Snack, code example, screenshot, or link to a repository

https://github.com/BohdanSol/projectTwo

**Comment by suyogshiftcare** [comment] 2022-02-21 01:48
Having the same issue. 
For me, it's mostly happening with SM-G998B and SM-G998B on Android 12

**Comment by tarouboy** [comment] 2022-02-21 04:55
Not sure is it related but received app crash when typing.
here's the log from Sentry
```
java.lang.IllegalStateException: Drag shadow dimensions must be positive
    at android.view.View.startDragAndDrop(View.java:26740)
    at android.widget.Editor.startDragAndDrop(Editor.java:1393)
    at android.widget.Editor.performLongClick(Editor.java:1432)
    at android.widget.TextView.performLongClick(TextView.java:12405)
```

**Comment by BohdanSol** [comment] 2022-02-21 07:54
@tarouboy  For me it's:
```
android.text.SpannableStringInternal in getSpanFlags at line 331
android.text.SpannableString in getSpanFlags at line 24
android.text.SpannableStringInternal in getSpans at line 389
android.text.SpannableString in getSpans at line 24
android.text.SpannableStringBuilder in change at line 431
android.text.SpannableStringBuilder in replace at line 560
android.text.SpannableStringBuilder in replace at line 518
android.text.SpannableStringBuilder in replace at line 39
android.view.inputmethod.BaseInputConnection in replaceText at line 945
android.view.inputmethod.BaseInputConnection in commitText at line 219
com.android.internal.widget.EditableInputConnection in commitText at line 204
com.android.internal.view.IInputConnectionWrapper in executeMessage at line 561
com.android.internal.view.IInputConnectionWrapper$MyHandler in handleMessage at line 118
android.os.Handler in dispatchMessage at line 106
android.os.Looper in loopOnce at line 226
android.os.Looper in loop at line 313
android.app.ActivityThread in main at line 8582
java.lang.reflect.Method in invoke
com.android.internal.os.RuntimeInit$MethodAndArgsCaller in run at line 563
com.android.internal.os.ZygoteInit in main at line 1133
```

**Comment by BohdanSol** [comment] 2022-02-21 11:07
@JoshuaGross , @RSNara , @mdvacca , sorry for mentioning you all straight, but It's seems very important issue for me. Maybe somebody can take at least a quick look at the repo I attached and give this higher priority status.

**Comment by rakefetWorkiz** [comment] 2022-02-23 15:04
we having the exact same issue. 
this is real show stopper 🤦‍♀️

**Comment by efstathiosntonas** [comment] 2022-03-10 19:33
Any updates regarding this issue? It’s happening on both Android 11 & 12, we get lot’s of crashes every day. It also lags a lot if a user enters a big block of text and it leads to ANR.

**Comment by BohdanSol** [comment] 2022-03-17 17:20
@JuanAlejandro working as expected as workaround for this kind of issue. Thank you very much!

**Comment by systemride** [comment] 2022-03-31 21:56
@JuanAlejandro Any update on whether your fix continues to solve the issue?

**Comment by smali-kazmi** [comment] 2022-04-05 22:11
any fix for this issue? because lot of our users facing the same issue if they have Samsung Device

**Comment by smali-kazmi** [comment] 2022-04-06 12:30
> We were able to reproduce this bug and we found that setting `autoCorrect` to `false` in the `TextInput` solves the issue. We are planning to roll out this soon and expect ANR numbers to go down. I'll keep you posted.
> 
> Try this and let me know if it works for you.
> 
> P.S.: Since this is happening only for Samsung devices with Android 12 I made this util to only set autoCorrect to false when the device meets these props:
> 
> ```
> import { toLower } from 'lodash';
> import { getSystemVersion, useManufacturer } from 'react-native-device-info';
> 
> export const useIsSamsungWithAndroid12 = (): boolean => {
>   const { loading, result } = useManufacturer();
>   const systemVersion = getSystemVersion();
> 
>   return !loading && toLower(result) === 'samsung' && systemVersion.startsWith('12');
> };
> ```

doesn't fix the issue

**Comment by efstathiosntonas** [comment] 2022-10-05 02:56
Bad bot, issue still exists to this day

**Comment by efstathiosntonas** [comment] 2022-10-17 12:08
Hey fellow devs, please upvote the comment under the Meta discussion about what to improve: https://github.com/react-native-community/discussions-and-proposals/discussions/528#discussioncomment-3890273

let’s hope it will get enough attention

**Comment by carstenhag** [comment] 2022-10-21 16:52
Issue also exists with native android :D so I really don't think React can do anything apart from disabling hints on Samsung

**Comment by efstathiosntonas** [comment] 2022-10-21 17:59
@carstenhag I have many samsung devices, I do not face such an issue with native apps. Can you please link a repro or a link to an issue? Thanks

**Comment by carstenhag** [comment] 2022-10-24 12:15
@efstathiosntonas This is the code that we are using (native android project):
```
            <EditText
                android:id="@+id/inputFormFieldEditText"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_gravity="center_vertical"
                android:layout_weight="1"
                android:background="@android:color/transparent"
                android:ellipsize="end"
                android:importantForAutofill="no"
                android:inputType="textFilter|textNoSuggestions"
                android:maxLines="1"
                android:textColor="@{whiteLabelThemePalette.textPrimaryColor}"
                android:textColorHint="@{whiteLabelThemePalette.textInactiveColor}"
                tools:text="Input text" />
```

```
        editText.addTextChangedListener(
            TextChangeListener {
                // Clear error text on input change.
                hideErrorText()
            }
        )
// and a few other methods like this, nothing affecting predictions 
```

Here's a repro description (sorry, only got it as png)
![bug-description-1](https://user-images.githubusercontent.com/3776997/197522927-66c98089-bbf1-413d-9968-5a799c1fc162.png)

I can also reproduce it with a Samsung Galaxy S22.

**Comment by smali-kazmi** [comment] 2022-10-30 16:41
This issue is still exist any work around of this issue?

**Comment by j-duggirala** [comment] 2022-11-06 06:23
@smali-kazmi Did you get any work around?

**Comment by smali-kazmi** [comment] 2022-11-11 09:19
> @smali-kazmi Did you get any work around?
this fix work for some user but for Android 13 facing the same issue
https://github.com/facebook/react-native/issues/33139#issuecomment-1069560920

**Comment by JuanAlejandro** [comment] 2022-11-11 16:59
> > @smali-kazmi Did you get any work around?
> > this fix work for some user but for Android 13 facing the same issue
> > [#33139 (comment)](https://github.com/facebook/react-native/issues/33139#issuecomment-1069560920)

@j-duggirala @smali-kazmi I opened [another issue](https://github.com/facebook/react-native/issues/35155) because we are having problems again with Android 13. This time the text suggestions setting is causing the ANRs in our app. The temporary solution we implemented was to set the `keyboardType` to `visible-password`. This is not ideal because it adds a lot of limitations to the writing experience of the user but at least doesn't get the app to freeze.

I'm worried about this because this issue was opened almost one year ago and we haven't got one single response from the react-native team.

**Comment by Phong-TH** [comment] 2022-11-22 07:19
@JuanAlejandro I have the same issue on our Samsung devices and received a lot of reports related to it. Just typing a sentence, the application will throw the ANR pop-up and must be forced close, the render thread is running forever. It can be solved by turning off the predictive and spell check but it causes a lot of bad situations 😕 We are crazy about this, any update for this?

**Comment by gkasireddy202** [comment] 2022-11-25 11:52
@JuanAlejandro Any update on this?

**Comment by mark-careplanner** [comment] 2022-11-28 10:56
We have this issue too. Disabling auto-suggest isn't an option for users who might have English as a second language.

**Comment by gkasireddy202** [comment] 2022-11-28 11:09
Anyone please let me know if this issue is happening due to a Samsung OS update or a react-native problem?

**Comment by efstathiosntonas** [comment] 2022-11-28 11:12
@gkasireddy202 prior Android 13 we had issues with autoCorrect and autoComplete, when we turned them off on Android devices it worked but with limitations for the end user. 

Android 13 brings the issue back even though the “fix” above worked on < 13.

**Comment by gkasireddy202** [comment] 2022-11-28 11:18
@efstathiosntonas -  This issue will resolve by Google for Android 13?

**Comment by mark-careplanner** [comment] 2022-11-28 11:28
@efstathiosntonas My only thought is why this hasn't become a bigger issue? Is there something unique we are doing (as in, people on this thread) that is causing this? Because if every RN TextInput on every new Samsung device failed to work, surely Facebook would have done something by now?!

**Comment by efstathiosntonas** [comment] 2022-11-28 11:33
@gkasireddy202 no, we cannot get around it, only way to make the textInput to act as `visible-password` among all the other hacks: https://github.com/facebook/react-native/issues/35155#issuecomment-1324712290

@mark-careplanner it's an issue for a really long time ([it's around for at least 2 years](https://github.com/facebook/react-native/issues/30263)) and unfortunately it's not solved yet.

**Comment by efstathiosntonas** [comment] 2022-11-28 11:36
@mark-careplanner I mentioned it on the latest react-native team discussion thread: https://github.com/react-native-community/discussions-and-proposals/discussions/528#discussioncomment-3890273, let's hope it gets enough attention. This is a big breaker, noone is quite sure if this is Android 13 issue (in general, not only Samsung) or Samsung/Pixel devices only. If it's Android 13 then we're f*cked since a fix can take a while to be shipped to affected devices and besides that, when users will upgrade/update to it?

**Comment by efstathiosntonas** [comment] 2022-11-28 11:39
On the other hand, I got users claiming that the textInput of other apps (probably native) is working fine but in our app it breaks.

**Comment by carstenhag** [comment] 2022-11-28 11:52
As I mentioned earlier, this also applies to native android apps. Our testers tried to repro this with many devices and apart from the Samsung devices, they were able to repro it with a Huawei P30 Pro as well. 

So it seems like Samsung/Huawei are at fault here. I don't think react-native can do anything to fix it - (if I can't fix it natively, how would react-native be able to do so?) :(.

**Comment by mark-careplanner** [comment] 2022-11-28 14:30
@efstathiosntonas - does your implementation listen for any changes to the TextInput? I.e. does it implement 'onChange' or similar?

**Comment by mark-careplanner** [comment] 2022-11-28 16:40
Thanks very much for this @Houguiram. All of our inputs are controlled, which has given us something interesting to look into!

**Comment by nes123** [comment] 2022-11-30 00:40
@Houguiram Just made some checks on Samsung S10 OS 12 and the problems are still there even if there is no value nor default value. Are you sure about what you are saying?

**Comment by Houguiram** [comment] 2022-11-30 16:37
@nes123 It seems like the issue still happens but is a lot less likely to happen with uncontrolled inputs. I can still reproduce an ANR with an uncontrolled input but I need to paste a much bigger wall of text before it happens.

We just released the change from controlled to uncontrolled inputs to our users. We're waiting for more data to confirm it, but it's starting to look like an order of magnitude of decrease in crashes for Samsung phones (1 ANR out of 730 sessions in the new versions VS  121 ANRs out of 5,965 sessions in the previous one).

**Comment by efstathiosntonas** [comment] 2022-11-30 16:42
Just tested it with Facebook app on a Samsung S22 Android 13 and it ANR, no crash. The amount of entered text was huge when it started lagging compared to my app which starts lagging with much fewer text.

**Comment by Houguiram** [comment] 2022-11-30 16:52
Btw from the manual testing we've done it looks like what makes a difference is wether the `TextInput` component rerenders on each value change or not. Hence why it crashes a lot for a controlled input or for an uncontrolled input with a defaultValue set to the value updated by onChange, but not for an uncontrolled input with no defaultValue or with a memoized defaultValue.

**Comment by nes123** [comment] 2022-11-30 16:54
@Houguiram did you check if it makes a difference to use a text child instead of a value to render the input? not sure if it can eliminate the re-renders.

**Comment by nes123** [comment] 2022-11-30 16:56
@Houguiram in any case in our use case the text is always long so even increasing the ANR tolerance is not good enough.

**Comment by Houguiram** [comment] 2022-11-30 17:24
I haven't yet. Could be worth trying if you need a controlled input.

**Comment by sabidhasan** [comment] 2022-11-30 17:33
> to use a text child instead of a value to render the input

@nes123 and @Houguiram  Can you please elaborate what you mean by this? Sorry I am relatively new to React Native so still not familiar with the terminology/APIs for all of the components.

**Comment by nes123** [comment] 2022-11-30 17:39
@sabidhasan You can use two forms

<Textinput value={this.state.text}/>

or

<Textinput>
<Text>{this.state.text}</Text>
</Textinput>

I doubt that there is a difference, but worth checking. I am not familiar with Textinput implementation.

**Comment by sabidhasan** [comment] 2022-11-30 18:04
> @sabidhasan You can use two forms
> 
> `<Textinput value={this.state.text}/>`
> 
> or
> 
> ```
> <Textinput>
> <Text>{this.state.text}</Text>
> </Textinput>
> ```
> 
> I doubt that there is a difference, but worth checking. I am not familiar with Textinput implementation.

Thanks for the response. Confirming that the latter form doesn't make a difference - the keyboard/inputs still slow down after typing ~1 paragraph of text. Appreciate the help/suggeston though!

**Comment by Houguiram** [comment] 2022-12-02 12:11
Now that the change has been rolled out to more users, I can confirm that the issue still happens but _way_ less as can be seen here (11.18.2 contains the change): 
![image](https://user-images.githubusercontent.com/15668626/205288119-7213d8b5-9de1-47e9-8a65-558899316399.png)

Here is the exact change we made:

```diff
const NoteInput = (props: Props) => {
  const { onChangeText, formikFieldName } = props;
  const { values, setFieldValue } = useFormikContext<FormikNoteInputType>();
  const onChangeTextCallback = React.useCallback(
    (text: string) => {
      setFieldValue(formikFieldName ?? 'note', text);
      onChangeText?.(text);
    },
    [onChangeText, setFieldValue, formikFieldName],
  );

-  const inputValue = formikFieldName ? values[formikFieldName] : values.note;
+  const originalInputValue = useMemo(
+    () => (formikFieldName ? values[formikFieldName] : values.note),
+    // We don't want to rerender the TextInput when the value changes
+    // as it's an uncontrolled input and can create performance issues
+    // with some text suggestion integrations e.g. Grammarly.
+    // eslint-disable-next-line react-hooks/exhaustive-deps
+    [formikFieldName],
+  );

   return (
     <TextInput
       {...props}
-      value={inputValue || ''}
+      defaultValue={originalInputValue || ''}
       onChangeText={onChangeTextCallback}
     />
   );
```

**Comment by KazakovVS** [comment] 2022-12-19 22:03
Any updates on the issue?

**Comment by fabriziobertoglio1987** [comment] 2022-12-22 09:43
https://github.com/facebook/react-native/pull/35691#issuecomment-1362551508

**Comment by fabriziobertoglio1987** [comment] 2022-12-22 09:46
https://github.com/facebook/react-native/issues/35590#issuecomment-1362625671

**Comment by Saad-Bashar** [comment] 2022-12-28 07:52
> Now that the change has been rolled out to more users, I can confirm that the issue still happens but _way_ less as can be seen here (11.18.2 contains the change): ![image](https://user-images.githubusercontent.com/15668626/205288119-7213d8b5-9de1-47e9-8a65-558899316399.png)
> 
> Here is the exact change we made:
> 
> ```diff
> const NoteInput = (props: Props) => {
>   const { onChangeText, formikFieldName } = props;
>   const { values, setFieldValue } = useFormikContext<FormikNoteInputType>();
>   const onChangeTextCallback = React.useCallback(
>     (text: string) => {
>       setFieldValue(formikFieldName ?? 'note', text);
>       onChangeText?.(text);
>     },
>     [onChangeText, setFieldValue, formikFieldName],
>   );
> 
> -  const inputValue = formikFieldName ? values[formikFieldName] : values.note;
> +  const originalInputValue = useMemo(
> +    () => (formikFieldName ? values[formikFieldName] : values.note),
> +    // We don't want to rerender the TextInput when the value changes
> +    // as it's an uncontrolled input and can create performance issues
> +    // with some text suggestion integrations e.g. Grammarly.
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
> +    [formikFieldName],
> +  );
> 
>    return (
>      <TextInput
>        {...props}
> -      value={inputValue || ''}
> +      defaultValue={originalInputValue || ''}
>        onChangeText={onChangeTextCallback}
>      />
>    );
> ```



Thanks @Houguiram, I tested your solution and so far it seems to have a far better result. I still have not pushed it to prod. I was just testing on my Samsung device (Android 13). 

This video shows ANR and it is the old implementation of our TextInput (Not memoized). This one results in ANR.
https://user-images.githubusercontent.com/13269141/209777762-ab11338f-f216-4160-b943-59d133c29c3f.mp4


This is with memoized. 
https://user-images.githubusercontent.com/13269141/209777875-44f26da7-b7de-4867-a2c4-edce0105599b.mp4

**Comment by mglobel** [comment] 2022-12-29 20:41
For anyone dealing with this issue, the freezing only seems to be happening using the default Samsung keyboard. We've been able to recommend to our users to install Google's Keyboard and the freezing does not happen.

https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin&hl=en_US&gl=US

Not a great long term solution, but hopefully can help provide some relief while this is investigated.

**Comment by smali-kazmi** [comment] 2022-12-30 10:32
Hello everyone here are my findings to avoid keyboard crash issue

1. I changed  `value={inputValue || ''}` to `defaultValue={originalInputValue || ''}` as suggested by @Houguiram 
2. **switch to Microsoft SwiftKey Keyboard** or for default Samsung s22 keyboard I turn off following two settings 
3. Suggest Text Corrections
4. More Typing options > Enhanced accuracy 

![Screenshot_20221230_152810_Samsung Keyboard](https://user-images.githubusercontent.com/749977/210060620-edfec821-20dd-4167-b167-e18600eb78b3.jpg)
![Screenshot_20221230_152823_Samsung Keyboard](https://user-images.githubusercontent.com/749977/210060626-2bd3230f-f802-4976-a9bf-03857a8967c9.jpg)

**Comment by rodrigobertolottizinsp** [comment] 2023-01-03 20:36
Please we need a solution for this.

**Comment by Steve-Rynjah** [comment] 2023-01-04 06:24
@here any solution on this yet please reply. Thank you.

**Comment by gkasireddy202** [comment] 2023-01-05 08:18
Any solution.

**Comment by Saad-Bashar** [comment] 2023-01-06 06:53
@mglobel did you push the fix to prod? I also had seen a good result which I mentioned here, https://github.com/facebook/react-native/issues/33139#issuecomment-1366442110

But I have not yet pushed it to production.

**Comment by mglobel** [comment] 2023-01-06 16:52
@Saad-Bashar Our fix is currently rolling out. We were also able to see an improvement on our own Samsung Android 13 device. By Monday I should have more confirmation from our users whether the fix is a widespread improvement.

**Comment by mglobel** [comment] 2023-01-09 15:28
@Saad-Bashar We've rolled out the fix and have confirmation from several users that it resolved the issue for them.

**Comment by Saad-Bashar** [comment] 2023-01-09 18:27
> @Saad-Bashar We've rolled out the fix and have confirmation from several users that it resolved the issue for them.

Thanks for the feedback! I just wanted to confirm again, uncontrolled input and removing re-renders solve the issue for you?

**Comment by Jack-Alfie** [comment] 2023-01-10 13:42
I have the same issue and tried some of the solutions but not working fine. Now simply I have fixed this by changing the keyboard type to email-address.

**Comment by Jack-Alfie** [comment] 2023-01-11 15:52
@LunyovYuriy yes right its not a perfect solution but its not crashing the app and autocorrect is not working when we use email-address keyboard.

**Comment by lunaleaps** [comment] 2023-01-12 19:37
Closing issue as we're addressing in https://github.com/facebook/react-native/issues/35590#issuecomment-1380871509

**Closed by lunaleaps** 2023-01-12 19:37 UTC
Labels: Component: TextInput, API: Keyboard, Needs: Triage :mag:
