### ISSUE TITLE
TextInput on iOS accepting autocorrect does not fire onChange or onChangeText event.

### ISSUE THREAD

**Issue by joonhocho** [facebook/react-native#6715] opened 2016-03-30 02:03 UTC
- [ ] Provide a **minimal code snippet** / [rnplay](https://rnplay.org/) example that reproduces the bug.
- [ ] Provide **screenshots** where appropriate
  
  http://cdn.iphonehacks.com/wp-content/uploads/2013/10/autocorrect-ios-7-keyboard.jpg
- [ ] What's the **version** of React Native you're using?
 
  0.22.2
- [ ] Does this occur on iOS, Android or both?
  
  Only tested on iOS
- [ ] Are you using Mac, Linux or Windows?
  
  Mac

Accepting autocorrect suggestion on iOS does not trigger onChange nor onChangeText events.

**Comment by dsibiski** [comment] 2016-03-30 12:23
This is a dupe of https://github.com/facebook/react-native/issues/2552 let's keep tracking it there and it's PR here: https://github.com/facebook/react-native/pull/2596

**Comment by dsibiski** [comment] 2016-03-30 12:43
@facebook-github-bot duplicate #2552

**Closed** 2016-03-30 12:45 UTC
Labels: Ran Commands

**Comment by rohitgoyal** [comment] 2017-04-26 14:01
It still exist in react-native version 0.43.4.
