### ISSUE TITLE
npm 5.3 (node 8.2.1) is not compatible with rn0.46.4

### ISSUE THREAD

**Issue by yexiaosong** [facebook/react-native#15362] opened 2017-08-04 01:33 UTC
### Is this a bug report?

no

### Have you read the Bugs section of the How to Contribute guide?

(Write your answer here.)

### Environment

1. `react-native -v`: 0.46.4
2. `node -v`: 8.2.1
3. `npm -v`: 5.3.0
4. `yarn --version`: 0.27.5

Then, specify:

- Target Platform: IOS

- Development Operating System: macOS

- Build tools: Xcode

### Steps to Reproduce

(Write your steps here:)

1. just react-native-init PROJECT-NAME
2. cd PROJECT-NAME && react-native run-ios
3. 

### Expected Behavior

 ios-simulator opend and hello-world appears. 

### Actual Behavior

 Entry, ":CFBundleIdentifier", Does Not Exist

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by mfrachet** [comment] 2017-08-04 05:41
Have you tried some stuff related to this https://github.com/facebook/react-native/issues/7308 ?

**Comment by hramos** [comment] 2017-08-04 06:44
We see a few issues get opened every day about this: https://github.com/facebook/react-native/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20CFBundleIdentifier

I've updated #14423 with all the relevant information.

**Comment by hramos** [comment] 2017-08-04 06:44
Duplicate of #14423

**Closed by hramos** 2017-08-04 06:44 UTC

**Comment by yexiaosong** [comment] 2017-08-04 13:45
Thank you for taking time to answer my questions.
