### ISSUE TITLE
libhwui.so crash only on android 11 (react native 0.67.3)

### ISSUE THREAD

**Issue by HessiPard** [facebook/react-native#34009] opened 2022-06-14 09:15 UTC
### Description

Hi, in recent versions of react-native we are facing an weired native crash that being reported in google play console and we can't reproduce it, and it happens only in **Android 11**:
```
backtrace:
  #00  pc 000000000004e40c  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164)
  #00  pc 0000000000062730  /apex/com.android.runtime/lib64/bionic/libc.so (__stack_chk_fail+20)
  #00  pc 0000000000653b88  /system/lib64/libhwui.so (GrTextStrike::addGlyphToAtlas(SkGlyph const&, GrMaskFormat, bool, GrResourceProvider*, GrDeferredUploadTarget*, GrAtlasManager*, GrGlyph*)+840)
  #00  pc 0000000000657894  /system/lib64/libhwui.so (GrTextBlob::VertexRegenerator::regenerate(int, int)+712)
  #00  pc 000000000061726c  /system/lib64/libhwui.so (GrAtlasTextOp::onPrepareDraws(GrMeshDrawOp::Target*)+1288)
  #00  pc 0000000000513418  /system/lib64/libhwui.so (GrOpsTask::onPrepare(GrOpFlushState*)+356)
  #00  pc 0000000000501c00  /system/lib64/libhwui.so (GrDrawingManager::flush(GrSurfaceProxy**, int, SkSurface::BackendSurfaceAccess, GrFlushInfo const&, GrPrepareForExternalIORequests const&)+1584)
  #00  pc 0000000000502a20  /system/lib64/libhwui.so (GrDrawingManager::flushSurfaces(GrSurfaceProxy**, int, SkSurface::BackendSurfaceAccess, GrFlushInfo const&)+132)
  #00  pc 0000000000532bec  /system/lib64/libhwui.so (GrRenderTargetContext::flush(SkSurface::BackendSurfaceAccess, GrFlushInfo const&)+96)
  #00  pc 000000000056780c  /system/lib64/libhwui.so (SkGpuDevice::flush()+48)
  #00  pc 0000000000218154  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaPipeline::renderFrame(android::uirenderer::LayerUpdateQueue const&, SkRect const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::RenderNode> > > const&, bool, android::uirenderer::Rect const&, sk_sp<SkSurface>, SkMatrix const&)+256)
  #00  pc 00000000002151b8  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaOpenGLPipeline::draw(android::uirenderer::renderthread::Frame const&, SkRect const&, SkRect const&, android::uirenderer::LightGeometry const&, android::uirenderer::LayerUpdateQueue*, android::uirenderer::Rect const&, bool, android::uirenderer::LightInfo const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::RenderNode> > > const&, android::uirenderer::FrameInfoVisualizer*)+416)
  #00  pc 000000000021e198  /system/lib64/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw()+832)
  #00  pc 00000000002205ec  /system/lib64/libhwui.so (_ZNSt3__110__function6__funcIZN7android10uirenderer12renderthread13DrawFrameTask11postAndWaitEvE3$_0NS_9allocatorIS6_EEFvvEEclEv$c303f2d2360db58ed70a2d0ac7ed911b+480)
  #00  pc 000000000020ed94  /system/lib64/libhwui.so (android::uirenderer::WorkQueue::process()+220)
  #00  pc 000000000023006c  /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+88)
  #00  pc 00000000000154cc  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+260)
  #00  pc 0000000000014d90  /system/lib64/libutils.so (thread_data_t::trampoline(thread_data_t const*)+412)
  #00  pc 00000000000b0048  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64)
  #00  pc 00000000000503c8  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
```

### Version

0.67.3

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 8.49 GB / 15.89 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - D:\Android\Projects\client-dev\node_modules\.bin\yarn.CMD
    npm: 7.6.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20200816.222424.0 - D:\Android\Projects\watchman\watchman.EXE
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
  IDEs:
    Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8309675
    Visual Studio: Not Found
  Languages:
    Java: 11.0.14 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.3 => 0.67.3
    react-native-windows: Not Found

### Steps to reproduce

it is unreproducable :)

### Snack, code example, screenshot, or link to a repository

build.gradle:
```
buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
		ndkVersion = "21.4.7075529"

		excludeAppGlideModule = true
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.2'
        classpath 'com.google.gms:google-services:4.3.10'
		classpath 'com.google.firebase:firebase-crashlytics-gradle:2.8.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
		maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
		mavenCentral {
            // We don't want to fetch react-native from Maven Central as there are
            // older versions over there.
            content {
                excludeGroup "com.facebook.react"
            }
        }
		google()
		jcenter()
		maven { url 'https://www.jitpack.io' }
    }
}
```

**Comment by arjun1194** [comment] 2022-06-15 08:59
facing the same issue on our app -> react-native-version 0.67.4

**Comment by cortinico** [comment] 2022-06-15 21:51
Closing as this is a duplicate of #33083

**Closed by cortinico** 2022-06-15 21:51 UTC
Labels: Platform: Android, Needs: Triage :mag:
