### ISSUE TITLE
react-native-git-upgrade breaks over yarn.lock?

### ISSUE THREAD

**Issue by braco** [facebook/react-native#12486] opened 2017-02-21 05:07 UTC
--- Please use this template, and delete everything above this line before submitting your issue --- 

### Description

react-native-git-upgrade seems to fail with "error: yarn.lock: does not exist in index"

$ react-native-git-upgrade --version
0.2.7

$ react-native-git-upgrade

```
...
HEAD is now at 6f89aa9 Project snapshot
git-upgrade info Apply the patch
error: patch failed: .flowconfig:28
Falling back to three-way merge...
Applied patch to '.flowconfig' with conflicts.
error: patch failed: .gitignore:34
Falling back to three-way merge...
Applied patch to '.gitignore' with conflicts.
error: patch failed: android/app/src/main/java/com/ditto/MainApplication.java:17
Falling back to three-way merge...
Applied patch to 'android/app/src/main/java/com/ditto/MainApplication.java' cleanly.
error: patch failed: ios/ditto.xcodeproj/project.pbxproj:22
Falling back to three-way merge...
Applied patch to 'ios/ditto.xcodeproj/project.pbxproj' with conflicts.
error: patch failed: ios/ditto.xcodeproj/xcshareddata/xcschemes/ditto.xcscheme:3
Falling back to three-way merge...
Applied patch to 'ios/ditto.xcodeproj/xcshareddata/xcschemes/ditto.xcscheme' cleanly.
error: patch failed: ios/ditto/AppDelegate.m:9
Falling back to three-way merge...
Applied patch to 'ios/ditto/AppDelegate.m' with conflicts.
error: patch failed: ios/ditto/Info.plist:4
Falling back to three-way merge...
Applied patch to 'ios/ditto/Info.plist' with conflicts.
error: yarn.lock: does not exist in index
git-upgrade WARN The upgrade process succeeded but there might be conflicts to be resolved. See above for the list of files that have merge conflicts.
```

Despite success message, none of the files in my project are changed.

### Reproduction

yarn add react-native@0.39.x

react-native-git-upgrade

### Solution

Not sure about solution. Tried to override .gitignore and add yarn.lock to a commit, didn't work

### Additional Information

* React Native version: 0.39.x
* Platform: n/a
* Operating System: MacOS

**Comment by dwilt** [comment] 2017-02-22 01:41
@braco sounds like a duplicate of https://github.com/facebook/react-native/issues/12112

**Closed** 2017-02-22 22:58 UTC
