### ISSUE TITLE
[CameraRoll] Rotation bug

### ISSUE THREAD

**Issue by pawellewandowski** [facebook/react-native#14280] opened 2017-05-31 21:30 UTC
RN: 0.43 or 0.44 (0.42.3 everything is ok)

Reproduction:
I made 1 photos, next I close camera, reopen and made 2 photos (camera orientation not changed):
![c0e7c33c-27a6-11e7-8587-2f0dc1306386](https://cloud.githubusercontent.com/assets/3199040/26654944/f68e7ae6-4658-11e7-8b19-c8ff8e14221f.png)

**Comment by hramos** [comment] 2017-05-31 21:46
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-05-31 21:46 UTC

**Comment by pawellewandowski** [comment] 2017-06-01 07:31
updated.

**Comment by hramos** [comment] 2017-06-01 16:23
Can you provide sample code and more detailed repro steps?

**Comment by jose920405** [comment] 2018-01-19 18:39
any solution for this issue?
