### ISSUE TITLE
00000000000793d4 _JNIEnv::CallVoidMethod(_jobject*, _jmethodID*, ...) LINE:libreactnativejni.so

### ISSUE THREAD

**Issue by zhy1023** [facebook/react-native#38741] opened 2023-08-02 02:33 UTC
### Description

Thread Name: 'mqt_native_modu'
pid: 22474, tid: 2545  >>> com.chuangmi.imihome <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0000000000000004
  x0   0000000000000000  x1   0000000000002a02  x2   0000000000002a02  x3   0000007459d4b2a0
  x4   0000000000000061  x5   000000751ed57cbf  x6   0000000000000000  x7   0000000000000028
  x8   0000000000000000  x9   0000000000000001  x10  000000759ca18000  x11  000000759ca15000
  x12  0000007459d4b510  x13  000000759c21889c  x14  000000759c2188fc  x15  0000000000000000
  x16  00000074177de698  x17  000000741779c360  x18  0000000000000000  x19  0000007459d4b350
  x20  0000000000002a02  x21  0000007459d4b2a0  x22  000000758467d770  x23  0000000000000000
  x24  0000000000000043  x25  0000007459d4c000  x26  000000759c0b4382  x27  000000759c0b6482
  x28  000000759c0954eb  x29  0000007459d4b250  x30  000000759c628c0c
  sp   0000007459d4b1c0  pc   000000759c628c14  pstate 0000000060000000
  v0   0000007459d4b4a00000007459d4b510  v1   ffffff80ffffffd80000007459d4b470
  v2   00000000000000000000000000000000  v3   809f0000000000000000000000000000
  v4   80601806806018068060180680601806  v5   00ff0000000000000000000000000000
  v6   00000000000000000000000000000000  v7   80601806806018068060180680601806
  v8   00000000000000000000000000000000  v9   00000000000000000000000000000000
  v10  00000000000000000000000000000000  v11  00000000000000000000000000000000
  v12  00000000000000000000000000000000  v13  00000000000000000000000000000000
  v14  00000000000000000000000000000000  v15  00000000000000000000000000000000
  v16  c0300c03c0300c03c0300c03c0300c03  v17  a00aa00aa00aa00aaaaaaaaa90000000
  v18  80200802802008028020080280200802  v19  0000000000000000bff2495b9b4845e9
  v20  0000000000000000bfe5515621f780a3  v21  00000000000000003fe9944444040ae5
  v22  f2a2a72ca6e4fdae7f2a0db0bf83a6a2  v23  ea7737ea6eb75d978bd609512a7289aa
  v24  000000000000000000000000ebad8088  v25  000000000000000000000000ebad8089
  v26  000000000000000000000000ebad808a  v27  000000000000000000000000ebad808b
  v28  000000000000000000000000ebad808c  v29  000000000000000000000000ebad808d
  v30  000000000000000000000000ebad808e  v31  00760061006a002e0064006100650072
  fpsr 0800001b  fpcr 00000000
    #00 pc 0000000000428c14  /apex/com.android.art/lib64/libart.so (_ZN3art35InvokeVirtualOrInterfaceWithVarArgsIPNS_9ArtMethodEEENS_6JValueERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectT_St9__va_list+84)
    #01 pc 0000000000428f34  /apex/com.android.art/lib64/libart.so (_ZN3art35InvokeVirtualOrInterfaceWithVarArgsIP10_jmethodIDEENS_6JValueERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectT_St9__va_list+92)
    #02 pc 0000000000279b40  /apex/com.android.art/lib64/libart.so (_ZN3art3JNIILb0EE15CallVoidMethodVEP7_JNIEnvP8_jobjectP10_jmethodIDSt9__va_list+616)
    #03 pc 00000000000793d4  /data/app/~~iZBdvaocZZDVQjhi3u6X9g==/com.chuangmi.imihome-3ikpd2AZlQcCn8lNH-aQMw==/lib/arm64/libreactnativejni.so (_ZN7_JNIEnv14CallVoidMethodEP8_jobjectP10_jmethodIDz+116)
    #04 pc 00000000000880a8  /data/app/~~iZBdvaocZZDVQjhi3u6X9g==/com.chuangmi.imihome-3ikpd2AZlQcCn8lNH-aQMw==/lib/arm64/libreactnativejni.so
    #05 pc 0000000000080f74  /data/app/~~iZBdvaocZZDVQjhi3u6X9g==/com.chuangmi.imihome-3ikpd2AZlQcCn8lNH-aQMw==/lib/arm64/libreactnativejni.so
    #06 pc 0000000000015e84  /data/app/~~iZBdvaocZZDVQjhi3u6X9g==/com.chuangmi.imihome-3ikpd2AZlQcCn8lNH-aQMw==/lib/arm64/libfbjni.so (_ZN8facebook3jni6detail13MethodWrapperIMNS0_15JNativeRunnableEFvvEXadL_ZNS3_3runEvEES3_vJEE8dispatchENS0_9alias_refIPNS1_8JTypeForINS0_11HybridClassIS3_NS0_9JRunnableEE8JavaPartESA_vE11_javaobjectEEE+32)
    #07 pc 0000000000015dfc  /data/app/~~iZBdvaocZZDVQjhi3u6X9g==/com.chuangmi.imihome-3ikpd2AZlQcCn8lNH-aQMw==/lib/arm64/libfbjni.so (_ZN8facebook3jni6detail15FunctionWrapperIPFvNS0_9alias_refIPNS1_8JTypeForINS0_11HybridClassINS0_15JNativeRunnableENS0_9JRunnableEE8JavaPartES7_vE11_javaobjectEEEESC_vJEE4callEP7_JNIEnvP8_jobjectSF_+60)
    #08 pc 000000000013c90c  /memfd:jit-cache (deleted)

    >>> [translate by crash parser] <<<
    #00 pc 0000000000428c14 art::JValue art::InvokeVirtualOrInterfaceWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, std::__va_list) LINE:libart.so
    #01 pc 0000000000428f34 art::JValue art::InvokeVirtualOrInterfaceWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list) LINE:libart.so
    #02 pc 0000000000279b40 art::JNI<false>::CallVoidMethodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list) LINE:libart.so
    #03 pc 00000000000793d4 _JNIEnv::CallVoidMethod(_jobject*, _jmethodID*, ...) LINE:libreactnativejni.so
    #04 pc 00000000000880a8 /data/app/~~iZBdvaocZZDVQjhi3u6X9g==/com.chuangmi.imihome-3ikpd2AZlQcCn8lNH-aQMw==/lib/arm64/libreactnativejni.so
    #05 pc 0000000000080f74 /data/app/~~iZBdvaocZZDVQjhi3u6X9g==/com.chuangmi.imihome-3ikpd2AZlQcCn8lNH-aQMw==/lib/arm64/libreactnativejni.so
    #06 pc 0000000000015e84 facebook::jni::detail::MethodWrapper<void (facebook::jni::JNativeRunnable::*)(), &facebook::jni::JNativeRunnable::run, facebook::jni::JNativeRunnable, void>::dispatch(facebook::jni::alias_ref<facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<facebook::jni::JNativeRunnable, facebook::jni::JRunnable>::JavaPart, facebook::jni::JRunnable, void>::_javaobject*>) LINE:libfbjni.so
    #07 pc 0000000000015dfc facebook::jni::detail::FunctionWrapper<void (*)(facebook::jni::alias_ref<facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<facebook::jni::JNativeRunnable, facebook::jni::JRunnable>::JavaPart, facebook::jni::JRunnable, void>::_javaobject*>), facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<facebook::jni::JNativeRunnable, facebook::jni::JRunnable>::JavaPart, facebook::jni::JRunnable, void>::_javaobject*, void>::call(_JNIEnv*, _jobject*, void (*)(facebook::jni::alias_ref<facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<facebook::jni::JNativeRunnable, facebook::jni::JRunnable>::JavaPart, facebook::jni::JRunnable, void>::_javaobject*>)) LINE:libfbjni.so
    #08 pc 000000000013c90c deleted LINE:memfd:jit-cache

    >>> [Dalvik stack info] <<<
    at com.facebook.jni.NativeRunnable.run(Native method)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:38)
    at java.lang.Thread.run(Thread.java:920)

    >>> [Error stack info] <<<

    >>> [translate by crash parser from stackpointer] <<<

### React Native Version

0.71.4

### Output of `npx react-native info`

no

### Steps to reproduce

There is no necessary path

### Snack, screenshot, or link to a repository

no

**Comment by cortinico** [comment] 2023-08-02 08:40
Could you provide a reproducer as we can't really help with just a stacktrace

**Comment by zhy1023** [comment] 2023-08-11 03:35
hi cortinico，What are the possibilities?

**Comment by cortinico** [comment] 2023-08-11 14:36
> hi cortinico，What are the possibilities?

You should provide a reproducer as suggested here https://github.com/facebook/react-native/issues/38741#issuecomment-1661398247

**Comment by yiwowang** [comment] 2023-08-18 07:30
I have a same crash

**Comment by cortinico** [comment] 2023-12-04 12:56
Closing as repro was never provided

**Closed by cortinico** 2023-12-04 12:56 UTC
Labels: Needs: Triage :mag:, Needs: Repro, Newer Patch Available

**Comment by cortinico** [comment] 2025-04-09 15:48
For context: this is a duplicate of https://github.com/facebook/react-native/issues/49510

Will be fixed by https://github.com/facebook/react-native/pull/50592
