### ISSUE TITLE
[Animation] Using SpringAnimation like UIScrollView's rebound

### ISSUE THREAD

**Issue by aleclarson** [facebook/react-native#6197] opened 2016-02-28 12:36 UTC
Are `tension` & `friction` (or `speed` & `bounciness`) sufficient to mimic the rebounding in Apple's `UIScrollView`?

I assume not, since [`CASpringAnimation`](https://github.com/nst/iOS-Runtime-Headers/blob/master/Frameworks/QuartzCore.framework/CASpringAnimation.h) has `mass`, `damping`, & `stiffness` properties.

For example, when you fling a `UIScrollView` and it hits the upper bound while decelerating, there is a noticeably longer overshoot than I've experienced with React Native's `SpringAnimation`. But perhaps this effect is achievable with `tension` & `friction` (or `speed` & `bounciness`)?

Maybe `SpringAnimation` should have `mass`, `damping`, & `stiffness` properties?

[`RBBSpringAnimation`](https://github.com/robb/RBBAnimation/blob/master/RBBAnimation/RBBSpringAnimation.m) seems like a good place to start.

cc @sahrens

**Comment by mkonicek** [comment] 2016-03-20 19:20
@facebook-github-bot stack-overflow

**Comment by mkonicek** [comment] 2016-03-20 19:20
@facebook-github-bot feature

**Comment by mkonicek** [comment] 2016-03-20 19:23
> Are tension & friction (or speed & bounciness) sufficient to mimic the rebounding in Apple's UIScrollView?

Maybe they are, I'm not sure. What's the specific issue you've ran into. Have you found a use case where the tension and friction don't work well enough?

**Comment by mkonicek** [comment] 2016-03-20 19:24
I'll close this as I don't see how the issue is actionable (yet) but feel free to use this issue for discussion.

**Closed by mkonicek** 2016-03-20 19:24 UTC
Labels: Contains Potential Question Keywords, Feature Request, Ran Commands

**Comment by aleclarson** [comment] 2016-04-03 06:01
This is my main issue:

> when you fling a UIScrollView and it hits the upper bound while decelerating, there is a noticeably longer overshoot than I've experienced with React Native's SpringAnimation

After tinkering with the values of `tension/friction` and `speed/bounciness`, it seems impossible to get a longer overshoot using `SpringAnimation`.
