### ISSUE TITLE
hot reload doesnt update listview rows

### ISSUE THREAD

**Issue by pvinis** [facebook/react-native#12075] opened 2017-01-26 09:34 UTC
### Description
i have a list view with dataSource, renderRow etc, and when i change the style of something inside the renderRow, the hot reload runs but doesnt change anything in the items rendered

if i change something in the view but outside the list, eg the background color of the whole list, it works. but if i change the textColor in the items inside the renderRow, it doesnt.

### Solution
i guess just rerender the list items on hot reload? no idea.

### Additional Information

* React Native version: 0.39
* Platform: iOS
* Operating System: MacOS

**Comment by SRandazzo** [comment] 2017-01-26 13:28
My guess is that since your listview's data source is (presumably) not changing, the renderRow function is never invoked, so the code in renderRow does not get invoked. You can confirm if this is true by placing a log in renderRow and invoking a hot reload. 

Something to try:
If the component returned from renderRow is a custom component (rather then just composing your hierarchy inside of renderRow and returning it), making changes to your custom component _might_ invoke hot reload correctly. Give it a shot

**Comment by pvinis** [comment] 2017-01-26 13:41
indeed that works. if i have a separate component, it refreshes. but why? whats the difference?

**Comment by SRandazzo** [comment] 2017-01-26 16:27
all conjecture but -

`render` is called on your main component because it is in the view hierarchy tree. 
That call applies to it's children (your ListView component), and as expected, that call also occurs on the ListView's children (it's rows). However, since you are creating the view hierarchy inside of renderRow, as opposed to them being _their own_ component subclass, you're not _actually_ modifying the ListView's children, but instead the function that produces the children.

When the rows _are_ their own subclass, the hot reloader is presumably smart enough to grab each reference of that subclass and reload it

Kind of hard to explain!

If you feel this is resolved, feel free to close! I do feel this is intended/expected behavior of ListView, but if a contributor thinks other wise feel free to open!

**Comment by pvinis** [comment] 2017-01-26 17:29
aha. thanks for explaining. i can close this then. do you think its fair to just leave it as is, or maybe make it so it rerenders in both cases?

**Comment by shahen94** [comment] 2017-01-27 19:09
For the first try to understand what hot loading does.

It tries to rerender updated component doing setState. It means the following life cycles will calls

1. ComponentWillReceiveProps.
2. shouldComponentUpdate
3. ComponentWillUpdate
4. Render
5. ComponentDidUpdate

You have rowHasChanged prop into your data source, it will invoke in shouldComponentUpdate life cycle , if it will return false then nothing will be updated

**Comment by shahen94** [comment] 2017-01-27 19:10
@pvinis Its not a issue

**Comment by pvinis** [comment] 2017-01-28 14:48
it makes sense, but still, the point of hot reloading is to rerender the ui. so it would be cool to rerender the row too right? why should it work with a custom component row and not with a simple inline one?

**Comment by hramos** [comment] 2017-03-31 18:33
Closing as ListView is deprecated in 0.43. Use FlatList.

**Closed by hramos** 2017-03-31 18:33 UTC
