### ISSUE TITLE
Perf monitor FPS around 30

### ISSUE THREAD

**Issue by skv-headless** [facebook/react-native#10608] opened 2016-10-28 10:35 UTC
### Description

Without any interaction FPS monitor shows 30 fps for js and ui thread.
### Reproduction

Just launch perf monitor

<img src="https://cloud.githubusercontent.com/assets/1488195/19803748/81ce7850-9d1b-11e6-9c6f-179c6562f0c5.png" width="200" />

<img src="https://cloud.githubusercontent.com/assets/1488195/19803762/909641ec-9d1b-11e6-82bb-e7688d9a7a48.png" width="200" />
### Additional Information
- React Native version: 0.34, 0.36, master
- Platform: iOS(simulator), Android and iOS can't test now, but will test later.
- Operating System: MacOS, (XCode 8, XCode7)

**Comment by gitim** [comment] 2016-10-28 13:18
Also I noticed that JSC memory consumption field is always 0.00.

**Comment by scarlac** [comment] 2016-10-28 15:01
I'm pretty sure this is a new "feature" in the iOS simulator since XCode 8.

I noticed the same slowdown after upgrading to XCode 8. It's not limited to React Native it seems. The Simulator speeds up to 60fps when you interact with it. You can test this in any app, e.g. open Settings app, swipe-scrolling with the mouse pressed down. Notice how smooth it is. When you let go and inertial scrolling takes over, you'll see the stuttering begins. RN apps just seem more sensitive to this change.

**Comment by brentvatne** [comment] 2016-10-30 15:36
@scarlac's answer makes sense here, I can't find any official Apple documentation about this though. I wonder if there is a way to disable this, anybody know?

**Comment by skv-headless** [comment] 2016-11-02 12:16
I've created objective-c app and CADisplayLink selector called just 30 times per seconds 😢

**Comment by ide** [comment] 2016-11-02 18:57
Let's close this then, it's how iOS works, filing a radar with Apple sounds like the path forward here.

**Closed by ide** 2016-11-02 18:57 UTC

**Comment by skv-headless** [comment] 2016-11-03 08:19
https://productpains.com/post/react-native/fix-fps-monitor-on-ios
guys please vote. I liked this tool so much 😭

**Comment by rodriguesbreno** [comment] 2016-11-08 17:13
Also experience this issue, the simulator seems be unusable since even a touchable reaction became slow.

The same behavior is reproduced in the Xcode 7.3 (my version is the  7.3.1 (7D1014) ), 
the only difference is that JSC memory consumption field display a value different then 0.0

@skv-headless are you using macOS Sierra? I think this issue is related to a change in the system.

**Comment by skv-headless** [comment] 2016-11-09 06:55
Yes. I use macOS Sierra. I also think that's the reason.

**Comment by rodriguesbreno** [comment] 2016-11-09 13:11
Yes, it's the MacOS sierra. Just reversed to El Capitan and the simulator returned to run in 60fps. Haven't test yet with Xcode 8. But as I remember last month before the update it was working fine too.

**Comment by lengocgiang** [comment] 2016-11-19 05:25
@skv-headless : Do you solve this problem?

**Comment by joehoyle** [comment] 2016-11-26 16:40
I'm seeing very similar issues on Sierra with XCode 8. 23 - 30 FPS, and 1 second touch response times with react-native. Let me know if I can do anything to help debug.

**Comment by rodriguesbreno** [comment] 2016-11-26 17:00
@joehoyle I downgrade to El Capitan, and it just works fine. It's an behavior of Sierra.
And isn't related to Xcode or React Native

**Comment by joehoyle** [comment] 2016-11-26 18:03
Hmm so this is _intentional_ behaviour from Apple do you think? I can understand 30FPS, but the super laggy mouse clicks / touch interactions and animations makes it virtually impossible to feel productive with the simulator!

**Comment by rodriguesbreno** [comment] 2016-11-26 18:16
Yes, it's virtually impossible use the simulator in that way. Hope they don't do it in the next version of the iOS too. This is kinda a limit to the CADisplayLink in idle mode, when you start interacting it's supposed be more fast, but it doesn't work well to the RN apps.

**Comment by max-mykhailenko** [comment] 2016-11-26 19:23
On sierra all iOS interface is laggy. Try to move on screens or go to the settings.

**Comment by brycepavey** [comment] 2016-11-27 23:01
Also experiencing massive lag on iOS simulator when debugging in chrome since updating to Sierra. If I stop remote debugging, close the chrome debugger tab and then turn remote debugging back on it resolves the problem temporarily but seems to return after a few reloads.

**Comment by fungilation** [comment] 2017-01-05 02:29
Same experience with fps drop in Simulator, since upgrading from El Capitan to Sierra. It was 60 fps, now it's 30 or less. Would be great if there's a workaround, in macOS?

**Comment by jjhesk** [comment] 2017-03-01 17:16
same in here. I use macOSX serria 10.12.1 and it is slow. i get only 21 - 24 FPS.

**Comment by lengocgiang** [comment] 2017-03-02 10:55
I downgraded to Elcapitan 10.11 , it solved

**Comment by fungilation** [comment] 2017-03-02 22:50
Requiring downgrade in one's OS is no "solution".

**Comment by oneatcoe** [comment] 2017-03-10 04:45
same issue :(

**Comment by bosung90** [comment] 2017-03-13 02:51
Having same issue...

**Comment by xilonxiao** [comment] 2017-03-27 01:06
Just reporting here that, yesterday with el captain the simulator was fine, and today post update to sierra I'm having the same problem.

**Comment by rodriguesbreno** [comment] 2017-03-30 21:33
Latest version of Xcode 8.3 (8E162) and Mac Sierra 10.12.4 (16E195)  fix the issue.
It's running 60FPS again 🎉

![simulator screen shot mar 30 2017 6 32 09 pm](https://cloud.githubusercontent.com/assets/19731692/24527114/36f3a218-1577-11e7-878a-4ec14a2db9a9.png)

**Comment by xilonxiao** [comment] 2017-03-30 22:02
Just confirming what @rodriguesbreno said, these updates fix the issue.
