### ISSUE TITLE
[Image] Resizing image with Animation (with resizeMode="cover") is glitchy

### ISSUE THREAD

**Issue by skevy** [facebook/react-native#2283] opened 2015-08-10 17:58 UTC
You can see the issue here:  

![Image of issue](https://s3.amazonaws.com/f.cl.ly/items/2Q3R2F0K2e3k3c3T0M1k/Screen%20Recording%202015-08-10%20at%2011.38%20PM.gif)

Video of Issue (if gif is not clear): http://s.sk3vy.com/cCZ0

(you can see that it glitches a little bit as it resizes)

Code-wise, all I'm doing is doing:

```
Animated.parallel([
  Animated.spring(
    this.state.imageOverlay.position, {
      toValue: { x: 0, y: 0 },
      friction: 20,
      tension: 220
  }),
  Animated.spring(
    this.state.imageOverlay.size, {
      toValue: { x: this.screenWidth, y: this.screenHeight },
      friction: 20,
      tension: 220
  })
]).start();
```

Nothing out of the ordinary there.

In debugging this issue...it seems it may have something to do with this:

https://github.com/facebook/react-native/blob/757d6d204ae2d743634af64e3f78a4aad9d53f70/Libraries/Image/RCTImageView.m#L174-L176

When I don't reload the image (comment out line 175), it's smooth as butter, as you might expect. Obviously that's not a solution here, but I think it does give insight into the problem.

It seems like it would be good to somehow (perhaps optionally) defer the reloading and resampling of the image until after an animation has completed.

**Comment by shayne** [comment] 2015-08-10 18:09
The Objective-C code isn't friendly to animations like the one you've demonstrated. We shouldn't swap out the image  / reload it during the animation, but decide to do it either before or after. Which may be a developer's preference depending on the image.

Are you animating a style transform or the actual width and height? Assuming it's the width and height try animating a transform scaleX/scaleY instead and see if you get the same results.

**Comment by nicklockwood** [comment] 2015-08-10 20:39
Hmm, even with the reloading it shouldn't glitch like that. Is it skipping frames or actually resizing incorrectly? It's hard to see from the gif.

**Comment by skevy** [comment] 2015-08-11 02:33
@nicklockwood it appears (based on the FPS monitor) that it isn't skipping frames...just resizing incorrectly. As I said, it does seem to be working right with stretch.

**Comment by skevy** [comment] 2015-08-11 03:39
I updated the gif - it's a little more clear.

**Comment by potsypantsy** [comment] 2015-08-12 06:14
I ran into a similar issue also! Hoping that this will be fixed soon!

**Comment by ms88privat** [comment] 2015-08-12 10:53
+1. It is very buggy behaviour. In my case I am trying to resize the Animated.Image (only height) with pan responder. I can not transformY or scaleY, because i need the image content to adjust to the new aspect ratio with resizeMode 'cover' in "realtime". But is is very glitchy and bounces a'lot even after i stopped resizing.  It feels like, the resizeMode of the image can't keep up with the actual resizing. :/

**Comment by ms88privat** [comment] 2015-08-12 13:06
Seems like there is something really of with images resizeMode...

I removed the image reload like @skevy suggested. Now the performance is smooth, but it doesn't cover the image to the new size anymore... but sometimes only a little bit. Very unstable behaviour which is very bad! 

Example screenshots

1. Two Images, cropped with resizeMode 'cover'
 https://www.dropbox.com/s/7aeqxmgqmbena8y/exp1.png?dl=0
2. (with image reload) After resizing the height of one image (step by step) - feely very bad, slow and bounces to 'cover' the new aspect ratio - feels like it can't keep up with the panning - but the result is what i want in principle!
https://www.dropbox.com/s/wsojaotorbzrkge/exp2.png?dl=0
3. (without image reload) The resize feels very smooth, but it doesn't 'cover' the new aspect ratio - or only a little bit sometimes.
https://www.dropbox.com/s/70zyesjk6ilv2wi/exp3.png?dl=0

**Comment by nicklockwood** [comment] 2015-08-12 17:42
I've worked out what the issue is, and should have a fix ready soon.

The problem is that in cover mode, we currently clip the image to the correct size to fit the view, so (for example) if the image is landscape or portrait shaped, and it's being displayed inside a square view, we clip the image to a square when we resize it.

As far a I can tell, the logic to do that is working perfectly. The problem is that when the view is resized, that square shape may no longer be correct, so the image looks distorted unless it's redrawn for the new frame (which we only do if the frame is >20% different in size).

My fix is to resize the image without cropping, so that the frame can be animated without requiring the underlying image to be redrawn.

**Comment by skevy** [comment] 2015-08-12 17:46
@nicklockwood this is awesome news. Would love to know when you have an RFC of this so I can merge it into my fork and use it on this app.

**Comment by potsypantsy** [comment] 2015-08-12 17:51
@nicklockwood this is really awesome :+1:

**Comment by ms88privat** [comment] 2015-08-12 18:13
Thanks, looking forward to this :+1:

**Comment by ms88privat** [comment] 2015-08-27 15:02
@nicklockwood what's your progress here? I was hoping it will hit 0.11-rc, but it did not? Thanks a'lot!

**Comment by nicklockwood** [comment] 2015-08-27 15:49
That's odd - I thought it had landed already. I'll investigate.

**Comment by ms88privat** [comment] 2015-08-27 16:44
@nicklockwood maybe it did, i don't know the pull request id. But my image does not re-adjust if i prevent it from reloading on size change.

**Comment by ms88privat** [comment] 2015-08-27 17:22
@nicklockwood I'm very sorry. Npm did not update my react-native version at first. So i will give it another try after i fix my compile error!

**Comment by nicklockwood** [comment] 2015-08-27 17:26
This was the change that I thought had fixed it:

https://github.com/facebook/react-native/commit/7232b1bbc7d0477233829b19c91e8654dbb9203f

Can you let me know if it's still not working?

**Comment by skevy** [comment] 2015-08-27 17:41
I'll test as well. Currently using my hacked Image class...will try with
native again and let you know what happens.

**Comment by ms88privat** [comment] 2015-08-27 19:45
@nicklockwood it is working now. It is a little bit slower then the resizeMode 'cover' for example. But i think this is normal.

**Comment by skevy** [comment] 2015-08-27 20:50
@nicklockwood new code works flawlessly with my use-case. It'll make it into the next app store update. Thanks! :+1:

**Comment by ide** [comment] 2015-08-27 20:53
awesometown
population: nicklockwood

**Closed by ide** 2015-08-27 20:53 UTC
