### ISSUE TITLE
Navigator inside Navigator and contexts differ warning

### ISSUE THREAD

**Issue by JonasJonny** [facebook/react-native#1159] opened 2015-05-05 15:37 UTC
There is a warning when I create Navigator inside Navigator
"**Warning:** owner-based and parent-based contexts differ (values: `undefined` vs `[object Object]`) for key (navigator) while mounting Navigator..."

```javascript
// IndexScreen
...
<Navigator
  style={styles.navigator}
  renderScene={this.renderScene}
  initialRoute={{
    component: HomeScreen
  }}
/>
...

// HomeScreen
...
<SMXTabBarItemIOS
  name="activity"
  iconName={'ion|ios-bell-outline'}
  title={'Activity'}
  iconSize={30}
  selected={this.state.selectedTab === 'ActivityScreen'}
    onPress={() => {
      this.setState({
        selectedTab: 'ActivityScreen',
      });
    }}>
    <Navigator
      style={styles.navigator}
      renderScene={this.renderScene}
      initialRoute={{
        component: ActivityScreen
      }}
    />
</SMXTabBarItemIOS>
...
```
In HomeScreen I have SMXTabBarItemIOS (**Should be the same as TabBarIOS**) where I need to use another Navigator inside SMXTabBarItemIOS (TabBarIOS.Item) to have persistent tabbar through application.
Is that fine for my use case or should I change something to get rid of this warning?

Thank you anyone.

**Comment by spicyj** [comment] 2015-05-05 21:18
cc @ericvicenti

**Comment by JonasJonny** [comment] 2015-05-05 21:20
Thanks @spicyj.

**Comment by JonasJonny** [comment] 2015-05-06 17:05
Hello again.
I don't know if this is related or not but I have another problem with Navigator which I can't solve.
I am using 4 tabs together with Navigator. I have to use navigator inside each TabBarIOS.Item to have persistent tabs through app. When I reload app -> HomeScreen is my default view. I can use Navigator without problem. Push and Pop (Back button) works just fine. When I select different bar (ActivityScreen) - again everything works (I can go to another screen and back through back button). But when I click on HomeScreen tab again I can see last state/position screen where HomeScreen was left. But when back button is shown and clicked then It will pop/remove screen from ActivityScreen (Latest screen/state before screen tab was clicked) and not actual state in HomeScreen where I clicked the back button. btw: slide from left to right work and I can go back to right screen.
It is not possible to have more (2+) different navigators with their own states? Now it looks like there are somehow connected to each other and I can't use back button/pop correctly for separate tabs.
I tried to find solution for a several hours but without luck.

Without your help @ericvicenti or anyone I am stucked and lost :(.

Thank you

```
//renderScene()

renderScene(route, navigator) {

        var Component = route.component;
        var navBar = route.navigationBar;

        if (navBar) {
            navBar = React.addons.cloneWithProps(navBar, {
                navigator: navigator,
                route: route
            });
        }

        return (
            <View style={styles.container}>
                {navBar}
                <Component navigator={navigator} route={route} routerTab={this.state.routerTab} />
            </View>
        );
    }

// render()

<TabBarIOS>
    <TabBarIOS.Item
        title={'Home'}
        selected={this.state.selectedTab === 'HomeScreen'}
        onPress={() => {
                            this.setState({
                                selectedTab: 'HomeScreen',
                            });
                          }}
        >
        <Navigator
            renderScene={this.renderScene.bind(this)}
            initialRoute={{
                                component: HomeScreen,
                                navigationBar: <NavigationBar
                                    title="Home"
                                    customNext={<WriteIcon/>}
                                    titleColor="#fff"
                                    buttonsColor="#fff"
                                    style={styles.appHeader}
                                />
                            }}
            />
    </TabBarIOS.Item>
    <TabBarIOS.Item
        title={'Activity'}
        selected={this.state.selectedTab === 'ActivityScreen'}
        onPress={() => {
                            this.setState({
                                selectedTab: 'ActivityScreen',
                            });
                          }}
        >
        <Navigator
            renderScene={this.renderScene.bind(this)}
            initialRoute={{
                                component: ActivityScreen,
                                navigationBar: <NavigationBar
                                    title="Activity"
                                    titleColor="#fff"
                                    buttonsColor="#fff"
                                    style={styles.appHeader}
                                />
                            }}
            />
    </TabBarIOS.Item>
   ...
   ...
</TabBarIOS>
```
I am using https://github.com/Kureev/react-native-navbar but I think it is same even with default Navigator.

**Comment by ericvicenti** [comment] 2015-05-06 17:44
@JonasJonny, That nesting of Navigators should work, but this might be a bug. It will be much easier for me to see what is going wrong if you could put a basic version of the bug in a gist, or perhaps add functionality to the [navigator example](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/Navigator/NavigatorExample.js) which exposes the bug (and include repro instructions).

I'm not sure what is going wrong with the context warning, but there is a possibility that the bug is related because we haven't seen that same warning internally.

**Comment by JonasJonny** [comment] 2015-05-06 17:50
I tried to use Navigator ref="nav1", ref="nav2" ... and it looks like "this.refs.nav1.pop()", "this.refs.nav2.pop()" is working. But I don't know how to pass them into another component and it is not a best practice I guess.

---
I will try to create gist.

**Comment by JonasJonny** [comment] 2015-05-06 18:35
Ok @ericvicenti, here is the gist https://gist.github.com/JonasJonny/78c3a02d33e776d6b5f8.

index.ios.js -> redirect to -> MainScreen.js -> render -> HomeScreen.js
Write.js is custom icon.
I am sorry but you have to correct required path.

1. HomeScreen - You can see when you click next -> back button appear and is working -> click to next at least 1x
2. Click Activity - The same
3. Click Home - You can see screen as you left him at 1 with Back text. -> Click back and nothing happen - Actually screen from Activity was removed.

Thank you very much for any help.

**Comment by JonasJonny** [comment] 2015-05-06 23:28
I tried to change deprecated React.addons.cloneWithProps with React.cloneElement but the same result.

**Comment by ericvicenti** [comment] 2015-05-07 02:48
Ah, I see what the problem is. Right now you have two navigators directly inside one scene. The parent navigator does not know how to treat this situation properly.

Long story short, you need to use a navigator to switch between the child navigators in each tab. If you look into the [jumping nav sample](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/Navigator/JumpingNavSample.js), you can see how to do that with a tabs-like interface. Right now there is no way to disable the animation between the tabs, but I will fix that soon.

This is an issue we face internally, so we all need a more easy-to-use solution. I am working on it. I can update this issue when there is a better story here.

**Comment by JonasJonny** [comment] 2015-05-07 14:00
Thank you @ericvicenti .
I got working "jumping nav sample" example for my case. 
But I found out I can't use "back-swipe gesture" for current screen with another Navigator because is already "binded" to tabs-like-interface/JumpingNavSample Navigator.

It looks like I should stick with my solution. 
Try to use refs and find a way how to pass them into component class (Or I will have all logic for one tab in one file). At least for now I am not skilful enough to find another solution.

When there will be "easy-to-use solution" please update this issue. It will be very appreciated.

**Comment by romanonthego** [comment] 2015-05-17 07:47
my issue https://github.com/facebook/react-native/issues/1298 seems to be clone of this one.
@JonasJonny - I've found out that this issues is coused by navigators having parentNavigator and [this method](https://github.com/facebook/react-native/blob/fec81947bddba99ab9c34c8813dbe7113f825e46/Libraries/CustomComponents/Navigator/Navigator.js#L393) actually proxying `pop()` and `push()` to parent navigator under the hood. This is tricky one since if you inspect navigator object calling `pop()` in your component it will be a `childNavigator`, but the `parentNavigator` is one actually doing the transition. Why context is switching by switching tabs is not clear to me, but nested navigators starts to behave weird, it's for sure.
Monkey-patching solve issue for me, i've just removed proxy block from method.

**Comment by rxb** [comment] 2015-05-20 03:34
I did the same thing as @JonasJonny and had the same problem. I think i'm having trouble understanding how things are actually supposed to fit together.

Is the idea that you would need a structure like this:
* "App" Navigator, then...
* "Tab" Navigator & TabBarIOS (with TabBarIOS being used as the Navigator's NavigationBar, rather than relying on TabBarIOS to switch between Navigators), then... 
* "TabItem" Navigators which route to wherever...

Is it correct that you can only ever have one Navigator at each "level" and that even though TabBarIOS seems to "navigate", it's actually doing something a bit more simple?

**Comment by rxb** [comment] 2015-05-21 02:50
Ok, here's a working Gist that gives you a 3-level navigator structure
* Navigator A: routes tab scene + modals
* Navigator B: routes tabs
* Navigators C: route for each tab item
https://gist.github.com/rxb/57f45c327d0f6847a821

Setting `gestures: false` on line 157 of tabBarNavigator.ios.js kills the swipe gesture between tabs and allows pop gesture within the tab item navigators. 

Things I was not able to figure out:
* How to prevent animation when transitioning between tabs (though @ericvicenti mentioned in previous comment there's a real fix coming soon for this)
* How to properly pass a reference for Navigator A to a scene loaded in Navigator C, in order to be able to use Navigator A to present a modal scene.

**Comment by brentvatne** [comment] 2015-05-29 20:15
Thanks for the follow up @rxb!

I'm going to close this issue for now as it looks like the initial issue has been solved.

**Closed by brentvatne** 2015-05-29 20:15 UTC

**Comment by kalyan4** [comment] 2015-11-13 08:27
My task is to change tabbar iem position change according to user criteria my if-condition not perfectly working at this point
CGPoint touchlocation;
    [pan locationInView:self.view];
    
    if (tabbarview == nil) {
        tabbarview =[tbItems objectAtIndex:self.tabBarController.selectedIndex];
        [self.tabBarController.view addSubview:tabbarview];
    }
    if (fixedPos == 0) {
        fixedPos=touchlocation.y;
        
    }[tabbarview removeFromSuperview];
    tabbarview.center = touchlocation;
    
    if (pan.state == UIGestureRecognizerStateEnded) {
        // [tabbarview removefromsuperview]
        [tabbarview removeFromSuperview];
        tabbarview =nil;
        fixedPos = 0;
        
        if(touchlocation.x<4){
            
            if (touchlocation.x<=109)
            {
                [tbItems exchangeObjectAtIndex:0 withObjectAtIndex:self.tabBarController.selectedIndex];
                NSMutableArray *tvcs=[[self.tabBarController viewControllers]mutableCopy];
                id tempvc=[tvcs objectAtIndex:self.tabBarController.selectedIndex];
                [tvcs removeObject:tempvc];
                [tvcs insertObject:tempvc atIndex:1];
                [self.tabBarController setViewControllers:tvcs animated:YES];
                
            }else
            if (touchlocation.x>109 && touchlocation.x<=215)
            {
                [tbItems exchangeObjectAtIndex:1 withObjectAtIndex:self.tabBarController.selectedIndex];
                NSMutableArray *tvcs=[[self.tabBarController viewControllers]mutableCopy];
                id tempvc=[tvcs objectAtIndex:self.tabBarController.selectedIndex];
                [tvcs removeObject:tempvc];
                [tvcs insertObject:tempvc atIndex:2];
                [self.tabBarController setViewControllers:tvcs animated:YES];
                
            }else if (touchlocation.x>215 )
            {
                [tbItems exchangeObjectAtIndex:2 withObjectAtIndex:self.tabBarController.selectedIndex];
                NSMutableArray *tvcs=[[self.tabBarController viewControllers]mutableCopy];
                id tempvc=[tvcs objectAtIndex:self.tabBarController.selectedIndex];
                [tvcs removeObject:tempvc];
                [tvcs insertObject:tempvc atIndex:3];
                [self.tabBarController setViewControllers:tvcs animated:YES];
                
            }else
            {
                [tbItems exchangeObjectAtIndex:3 withObjectAtIndex:4];
                NSMutableArray *tvcs=[[self.tabBarController viewControllers]mutableCopy];
                id tempvc=[tvcs objectAtIndex:self.tabBarController.selectedIndex];
                [tvcs removeObject:tempvc];
                [tvcs insertObject:tempvc atIndex:4];
                [self.tabBarController setViewControllers:tvcs animated:YES];
            }


        }else
        {
            [tbItems exchangeObjectAtIndex:3 withObjectAtIndex:4];
            NSMutableArray *tvcs=[[self.tabBarController viewControllers]mutableCopy];
            id tempvc=[tvcs objectAtIndex:self.tabBarController.selectedIndex];
            [tvcs removeObject:tempvc];
            [tvcs insertObject:tempvc atIndex:4];
            [self.tabBarController setViewControllers:tvcs animated:YES];
        }
    }
