### ISSUE TITLE
Upgrading from v0.70.6 to v0.71.0 causing extremely slow debugging mode on Android

### ISSUE THREAD

**Issue by alabsi91** [facebook/react-native#35828] opened 2023-01-13 14:03 UTC
### Description

I recently upgraded my react-native project from version `0.70.6` to `0.71.0` using the `React Native Upgrade Helper` and have noticed a significant decrease in performance when using the debugging mode. The app takes much longer to load and the debugging process is extremely slow, making it difficult to make any changes.

### Version

0.70.1

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 4.42 GB / 15.93 GB
  Binaries:
    Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 31, 32, 33
      Build Tools: 30.0.3, 31.0.0, 33.0.0
      System Images: android-31 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-213.7172.25.2113.9123335
    Visual Studio: 17.4.33110.190 (Visual Studio Community 2022)
  Languages:
    Java: 11.0.17
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.2.0 => 18.2.0 
    react-native: ^0.71.0 => 0.71.0 
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Upgrade react-native project from version 0.70.6 to 0.71.0
Run the app in debugging mode
Notice the slow performance and long loading time

### Snack, code example, screenshot, or link to a repository

//

**Comment by edsztukowski** [comment] 2023-01-13 15:06
We're experiencing the same issue, we upgraded from RN 0.70.1.

**Comment by manosKas** [comment] 2023-01-13 17:00
+1

I'm guessing it has something to do with forcing all libraries to use 0.71.0

since i can only launch the app if i've built with the following in app/build.gradle:

```
configurations.all {
    resolutionStrategy {
        force 'com.facebook.react:react-native:0.71.0'
    }
}

``` 

cause otherwise i would get the following error:
 
[couldn't find DSO to load: libjscexecutor.so](https://github.com/facebook/react-native/issues/32928)

**Comment by inferusvv** [comment] 2023-01-13 18:03
Oh, I spent so many time today thinking that one of my dependencies works wrong... Yeah, seems like this is React Native issue

**Comment by muzhaqi16** [comment] 2023-01-13 20:03
I am having the same issue after upgrading, It takes about 2-4 after pressing something to respond, and the whole application is slow.

**Comment by muzhaqi16** [comment] 2023-01-13 20:05
```
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900HK
    Memory: 14.89 GB / 31.69 GB
  Binaries:
    Node: 16.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowAllTrustedApps: Disabled
  IDEs:
    Android Studio: AI-213.7172.25.2113.9123335
    Visual Studio: Not Found
  Languages:
    Java: 18.0.2 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.0 => 0.71.0 
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by inferusvv** [comment] 2023-01-13 20:21
I want to add, that not only buttons (touchable) works slowly. UI updates on active screen are throttling. And what is interesting - React Navigation transition animations works fine. And ScrollView works fine. Perf monitor shows -2 FPS sometimes (whatever that means)

**Comment by cortinico** [comment] 2023-01-13 20:22
Thanks for the issue report.
Several questions to help me investigate what's going on:

1. Are you using Hermes or JSC?
2. Is this happening also on a blank project created with `npx react-native init RN071`?

**Comment by inferusvv** [comment] 2023-01-13 20:27
1. Hermes
2. Yes. I started new project. You can see that links on default page work a bit slowly. But if you setup basic React Navigation with 2 screens you can see how long it takes to start switching screens

p.s. production build via `./gradlew assembleRelease` works fine, no throttling. Only dev mode issue on android

**Comment by AlirezaHadjar** [comment] 2023-01-13 20:27
I'm facing the same issue. On the bright side, everything is normal in the release apk.
By the way Cortinico I'm using Hermes.

**Comment by cortinico** [comment] 2023-01-13 20:29
@inferusvv Does the issue happens also if you disable Hermes (there is a flag in the `app/android/gradle.properties` file).

**Comment by muzhaqi16** [comment] 2023-01-13 20:29
The blank react-native project works fine.

**Comment by inferusvv** [comment] 2023-01-13 20:32
@cortinico Without Hermes it works fine.

I've set `hermesEnabled=false` at `android/gradle.properties`

**Comment by muzhaqi16** [comment] 2023-01-13 20:36
I can also confirm that once Hermes is disabled, it works fine.
`hermesEnabled=false`

**Comment by cortinico** [comment] 2023-01-13 20:44
> @cortinico Without Hermes it works fine.

Thanks for the confirmation. We'll be releasing 0.71.1 sometime next week with the fix for this. I believe the version of Hermes that comes with 0.71.0 is coming with Hermes in Debug mode which is causing this. I'll publish an update on this issue once we have the point release out.

For the time being you can either:
- Disable Hermes
- Stay on 0.70.x

**Comment by migueldaipre** [comment] 2023-01-13 21:08
@cortinico I have a similar problem with Hermes enabled and release mode. 
Do you have any idea?

`E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.x, PID: 858
    g4.c: Error: Exception in HostFunction: java.lang.UnsatisfiedLinkError: dlopen failed: library "libhermes-executor-debug.so" not found: needed by /data/app/~~Ns2koKqLBQX7wBUnu4tVuQ==/com.x-AIBSl2ICRWAREL01a4QKbg==/lib/arm64/libreanimated.so in namespace classloader-namespace, js engine: hermes, stack:`

> > @cortinicoSem Hermes funciona bem.
> 
> Obrigado pela confirmação. Estaremos lançando o 0.71.1 na próxima semana com a correção para isso. Acredito que a versão do Hermes que vem com 0.71.0 está vindo com o Hermes no modo de depuração, o que está causando isso. Publicarei uma atualização sobre esse problema assim que tivermos o lançamento pontual.
> 
> Por enquanto, você pode:
> 
> * Desabilitar Hermes
> * Fique em 0.70.x

**Comment by saxahan** [comment] 2023-01-14 16:26
Why is upgrading react-native is so HARD? cant upgrade to 0.71 and upgrade helper cannot help me!!

**Comment by manosKas** [comment] 2023-01-14 16:34
@saxahan send me an email with your issue, i may be able to help

**Comment by saxahan** [comment] 2023-01-14 18:19
> @saxahan send me an email with your issue, i may be able to help

Thanks for your helpful thought.
I managed to upgrade step by step by hands. Now I can run android and ios. However; ios cannot be installed from react-native run-ios, so I installed via Xcode.

**Comment by Stecken** [comment] 2023-01-14 19:15
for me too, I realized that version 0.71 is super throttled.

When starting Metro, you already feel the lag.

**Comment by aakash2016** [comment] 2023-01-16 16:15
thank god I found this issue, after a day of wasteful effort and countless StackOverflow and GitHub issue searches!!
Must Say, it is very to do an upgrade in react native and the updates are also very frequent.

**Comment by engmja** [comment] 2023-01-17 07:48
same issue here

**Comment by cortinico** [comment] 2023-01-17 11:40
Hey @alabsi91 @inferusvv @muzhaqi16
I do have a potential fix, but I'm looking into getting a reproducer to validate this fix before we include it in `0.71.1`.

So if you or anyone else could provide a reproducer, that would be greatly beneficial to verify this.

**Comment by enahum** [comment] 2023-01-17 11:42
@cortinico feel free to share the details and I can test it as is reproducing for me as well

**Comment by cortinico** [comment] 2023-01-17 11:44
> @cortinico feel free to share the details and I can test it as is reproducing for me as well

The fix is nothing you can change locally as you would need a newer version of Hermes that needs to be prebuilt. 
So I would need a Github project, starting from `npx react-native init RN071` which reproduces this issue. I will test it on my machine and we'll follow up as soon as the issue is fixed in a numbered release.

**Comment by alabsi91** [comment] 2023-01-17 13:33
@cortinico 
- Tested on Android Emulator and Samsung S10 device - debug mode -  Hermes enabled.
- a simple test app with `react navigation` and `FlatList`, I hope this will hellp.
https://github.com/alabsi91/RN071-hermes-debug-throttle-issue

**Comment by inferusvv** [comment] 2023-01-17 15:31
@alabsi91 Thank you for demo, also wanted to created :)

I wondered, is it possible that it is an issue of reanimated? @migueldaipre Attached another issue from software-mansion project

**Comment by manosKas** [comment] 2023-01-17 15:40
@inferusvv React-Navigation uses the Reanimated library, so...

**Comment by migueldaipre** [comment] 2023-01-17 15:43
I believe it has no connection, the problem in reanimated happened in release builds.

**Comment by inferusvv** [comment] 2023-01-17 15:43
> @inferusvv React-Navigation uses the Reanimated library, so...

Yeah, that is why I have such question :) I see that everyone here is using react navigation. Let's see what happens after Reanimated updated. They merged attached to this issue MRs, but honestly I have no idea what about they are 😅

**Comment by cortinico** [comment] 2023-01-17 18:45
@alabsi91 Thanks for the repro, I was able to confirm that the fix is working. It will be available in 0.71.1

And no, the issue is not related to react-navigation but to how we build and bundle Hermes

**Comment by johnf** [comment] 2023-01-17 21:03
@cortinico Any rough idea on then that might land? I need to make a call on whether we roll back or not.

**Comment by soemarko** [comment] 2023-01-18 11:40
I'm rolling back for now. Just keeping the file changes in another branch so I'll have an easier time upgrading after the fix is launched

**Comment by kelset** [comment] 2023-01-18 12:02
we have an hiccup for the Hermes fix in the sense that we need to wait for a piece of the pipeline to get released and there's a problem with getting it out of the door because of old credentials 😅 we want this fix to land asap but no clear ETA of when we'll be unlocked (doesn't depend on us) - as soon as we know more we'll let you know

**Comment by manosKas** [comment] 2023-01-18 12:04
@kelset well as long as we can temp fix it via disabling Hermes in debug, the matter is not that urgent so...

**Comment by mayconline** [comment] 2023-01-18 23:51
> > @cortinico Without Hermes it works fine.
> 
> Thanks for the confirmation. We'll be releasing 0.71.1 sometime next week with the fix for this. I believe the version of Hermes that comes with 0.71.0 is coming with Hermes in Debug mode which is causing this. I'll publish an update on this issue once we have the point release out.
> 
> For the time being you can either:
> 
> * Disable Hermes
> * Stay on 0.70.x

Thanks, solution with `hermesEnabled=false`

**Comment by kelset** [comment] 2023-01-19 19:11
as soon as maven publishes the artifacts, yeah... sadly there's some hiccup on their side so please keep an eye on  https://github.com/facebook/react-native/issues/35904

**Comment by kelset** [comment] 2023-01-19 20:23
ok artifacts are out now, 0.71.1 can be used and yes it should have the fix you need :)

**Comment by gvarandas** [comment] 2023-01-19 21:00
Can confirm it's been fixed on `0.71.1`. 🎉

**Comment by emanueljcc** [comment] 2023-01-20 02:42
I also confirm that the hermes is already adjusted in android and everything is going smoothly. It was also adjusted that it did not automatically launch the android emulator but in this version `0.71.1` it was already adjusted! thank you. :)

**Comment by kelset** [comment] 2023-01-20 08:45
perfect, closing!

**Closed by kelset** 2023-01-20 08:45 UTC
Labels: Platform: Android, Tech: Hermes, Needs: Repro, Needs: Attention, Needs: React Native Team Attention, Impact: Bug

**Comment by 98rahul** [comment] 2023-01-20 11:50
just wow for the  RN-0.71.1 as  all the issue fixes within a day by upgrading to latest.
but, one thing once we change the UI (added some style) and saving , instantly changes are not reflecting as of now need to reload the app then changes are reflecting.

**Comment by AliZaib-Emumba** [comment] 2023-02-07 06:54
App is running very slow on `0.71.2`. Updated from 0.66.5 and now its very slow in response on both development and release.

**Comment by AlirezaHadjar** [comment] 2023-02-07 12:19
@AliZaib-Emumba I don't think the answer you're looking for is in this issue. This issue was caused by 0.71.0 which is resolved in 0.71.2. Your problem is probably different.

**Comment by furkanuzundev** [comment] 2023-02-24 08:52
Is there anyone to occuring still this issue? I'm on 0.71.3 and it's very slow on Android.

**Comment by manosKas** [comment] 2023-02-24 09:07
@furkanuzundev are you sure that in 0.70.6 is not happening?

**Comment by furkanuzundev** [comment] 2023-02-24 09:12
@manosKas actually i didn't try on 0.70.6.I have updated from 0.67 to the latest version

**Comment by maxs1m** [comment] 2023-02-24 10:28
> Есть ли у кого-нибудь еще эта проблема? У меня 0.71.3 и на Андроиде очень тормозит.

Та же проблема.

**Comment by GuidoGagliardini** [comment] 2023-03-21 15:33
i'm same issue on 0.70.6, very slow navigation in tabs. I can't find a solution, and I already have `hermbesEnabled = false`

**Comment by mayconline** [comment] 2023-03-21 17:41
> i'm same issue on 0.70.6, very slow navigation in tabs. I can't find a solution, and I already have `hermbesEnabled = false`

my solution was update to version `0.71.4`  and ` cd android && ./grandlew clean`

**Comment by nelsonhernandez20** [comment] 2023-04-12 02:40
hermesEnabled=false I noticeably improved the performance of the app

**Comment by saxahan** [comment] 2023-04-12 07:29
I was thinking like should we really use react-native for cross-platform app development anymore!

**Comment by HaddyYang** [comment] 2023-05-05 06:30
0.71.4 has same issus

**Comment by marcin-piela-800** [comment] 2023-05-31 14:02
0.71.8 has same issue

**Comment by GuidoGagliardini** [comment] 2023-05-31 15:11
I think it is an important bug of the library. The app is practically unbrowsable at times.
0.70.6 
I have` hermbesEnabled = false `and `newArchEnabled = false`  NOT WORK. Very slow.
no new?

**Comment by hassanannajjar** [comment] 2023-06-22 14:05
0.71.11 has same issue

**Comment by hassanannajjar** [comment] 2023-06-22 14:06
0.71.11 has the same issue
I `havehermbesEnabled = false` and `newArchEnabled = false` NOT WORK. Very slow.

**Comment by hassanannajjar** [comment] 2023-06-22 14:07
`hermbesEnabled = false`
`newArchEnabled = false`
react-native `0.71.11` 
has the same issue Very slow.

**Comment by tapz** [comment] 2023-06-22 18:14
@GuidoGagliardini @hassanannajjar Maybe `hermesEnabled` works better than `hermbesEnabled`?
