### ISSUE TITLE
[ANDROID] Transform Perspective not working

### ISSUE THREAD

**Issue by antoxi4** [facebook/react-native#9740] opened 2016-09-05 08:10 UTC
I just use 3D rotate with perspective.

`<Animated.View style={[styles.flipFrontCard, {transform: [{perspective: 1000}, {rotateY: flipCardDegrees}]}]} /> `

On IOS it work, but in Android doesn't.

**Comment by nihgwu** [comment] 2016-09-05 08:41
That's a knowing issue, please search the issues first
#2915 #6159 #6926 , waiting for someone to review the PR, I'm waiting for this to be merged too

**Comment by antoxi4** [comment] 2016-09-05 09:12
@nihgwu  Omg, Thanks)

**Comment by ryankask** [comment] 2016-09-05 19:45
@facebook-github-bot duplicate #6926

**Comment by facebook-github-bot-5** [comment] 2016-09-05 19:47
@ryankask tells me this issue is a duplicate of #6926. Let's discuss there, closing this one.

**Closed by facebook-github-bot-5** 2016-09-05 19:47 UTC
Labels: Ran Commands
