### ISSUE TITLE
Unable to resolve module `AccessibilityInfo`

### ISSUE THREAD

**Issue by naiduprakash** [facebook/react-native#20245] opened 2018-07-17 07:05 UTC
The development server returned response error code: 500

URL: http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false

Body:
{"originModulePath":"E:\\xampp\\htdocs\\practice\\testing react-native\\AwesomeProject\\node_modules\\react-native\\Libraries\\react-native\\react-native-implementation.js","targetModuleName":"AccessibilityInfo","message":"Unable to resolve module `AccessibilityInfo` from `E:\\xampp\\htdocs\\practice\\testing react-native\\AwesomeProject\\node_modules\\react-native\\Libraries\\react-native\\react-native-implementation.js`: Module `AccessibilityInfo` does not exist in the Haste module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.","errors":[{"description":"Unable to resolve module `AccessibilityInfo` from `E:\\xampp\\htdocs\\practice\\testing react-native\\AwesomeProject\\node_modules\\react-native\\Libraries\\react-native\\react-native-implementation.js`: Module `AccessibilityInfo` does not exist in the Haste module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`."}],"name":"Error","stack":"Error: Unable to resolve module `AccessibilityInfo` from `E:\\xampp\\htdocs\\practice\\testing react-native\\AwesomeProject\\node_modules\\react-native\\Libraries\\react-native\\react-native-implementation.js`: Module `AccessibilityInfo` does not exist in the Haste module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.\n    at ModuleResolver.resolveDependency (E:\\xampp\\htdocs\\practice\\testing react-native\\AwesomeProject\\node_modules\\metro\\src\\node-haste\\DependencyGraph\\ModuleResolution.js:167:1306)\n    at ResolutionRequest.resolveDependency (E:\\xampp\\htdocs\\practice\\testing react-native\\AwesomeProject\\node_modules\\metro\\src\\node-haste\\DependencyGraph\\ResolutionRequest.js:80:16)\n    at DependencyGraph.resolveDependency (E:\\xampp\\htdocs\\practice\\testing react-native\\AwesomeProject\\node_modules\\metro\\src\\node-haste\\DependencyGraph.js:237:485)\n    at Object.resolve (E:\\xampp\\htdocs\\practice\\testing react-native\\AwesomeProject\\node_modules\\metro\\src\\lib\\transformHelpers.js:116:25)\n    at dependencies.map.result (E:\\xampp\\htdocs\\practice\\testing react-native\\AwesomeProject\\node_modules\\metro\\src\\DeltaBundler\\traverseDependencies.js:298:29)\n    at Array.map (<anonymous>)\n    at resolveDependencies (E:\\xampp\\htdocs\\practice\\testing react-native\\AwesomeProject\\node_modules\\metro\\src\\DeltaBundler\\traverseDependencies.js:294:16)\n    at E:\\xampp\\htdocs\\practice\\testing react-native\\AwesomeProject\\node_modules\\metro\\src\\DeltaBundler\\traverseDependencies.js:159:33\n    at Generator.next (<anonymous>)\n    at step (E:\\xampp\\htdocs\\practice\\testing react-native\\AwesomeProject\\node_modules\\metro\\src\\DeltaBundler\\traverseDependencies.js:239:307)"}
processBundleResult
    BundleDownloader.java:285
access$200
    BundleDownloader.java:37
onResponse
    BundleDownloader.java:163
execute
    RealCall.java:153
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1113
run
    ThreadPoolExecutor.java:588
run
    Thread.java:818

**Comment by slavikdenis** [comment] 2018-07-17 07:16
Do you even check the other issues before adding a new one?

**Comment by naiduprakash** [comment] 2018-07-17 07:20
yes @slavikdenis  but didn't get any solution.
when i init a new project with version 0.44.0 (react-native init myapp --version="0.44.0") then it works fine.

**Comment by gluons** [comment] 2018-07-17 07:38
I also face this issue too.  
It's probably duplicate of #19953.  
Maybe you can track on that issue.

**Comment by slavikdenis** [comment] 2018-07-17 07:40
Damn... Duplicate of https://github.com/facebook/react-native/issues/20190 too.

**Closed** 2018-07-17 08:05 UTC
