### ISSUE TITLE
Networking.sendRequest failed to allocate memory in POST request

### ISSUE THREAD

**Issue by eduardo-schork** [facebook/react-native#22225] opened 2018-11-09 17:22 UTC
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment

React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-4770S CPU @ 3.10GHz
      Memory: 1.23 GB / 7.95 GB
    Binaries:
      Yarn: 1.10.1 - C:\Users\Schork\AppData\Roaming\npm\yarn.CMD
      npm: 6.3.0 - C:\Users\Schork\AppData\Roaming\npm\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338

react-native-cli: 2.0.1
react-native: 0.57.4

## Description

I'm trying to send a large json (aprox. > 30 mb) to my django webserver using an Axios POST request(version 0.18.0) but i'm having trouble, first I needed change the `maxContentLength` from POST request in Axios,  then I tried again so I got another error saying: 

`Could not invoke Networking.sendRequest null Failed to allocate a (x number) byte allocation with (another x number) free bytes...` 

(complete error message bellow).

So... i don't know what do with this error and need some help

## Reproducible Demo

![screenshot_20181109-144713](https://user-images.githubusercontent.com/27635248/48277747-b4588d00-e432-11e8-99bd-f19d7d0c5d19.png)

**Comment by bartolkaruza** [comment] 2018-11-11 03:13
The problem is that your post body is causing an allocation of 100MB, which is well over the limit. The workaround, which is also much safer with unreliable network connections, is to split up your JSON file into multiple pages, none larger than ~5MB, and send each as a separate request. Mobile apps have limited memory which they are allowed to consume. 

A simpler workaround, you could try increasing the allowed memory usage on Android, using the [large heap](https://developer.android.com/guide/topics/manifest/application-element#largeHeap) value in the manifest. I recommend looking at reducing the post request size though, as huge requests tend to be unreliable.

@kelset This is not a bug

**Comment by kelset** [comment] 2018-11-12 10:38
Thanks Bartol for the writeup, I'll close this 👍

**Closed by kelset** 2018-11-12 10:38 UTC
