### ISSUE TITLE
bundling :UnableToResolveError

### ISSUE THREAD

**Issue by yash2code** [facebook/react-native#13625] opened 2017-04-22 05:25 UTC
error: bundling: UnableToResolveError: Unable to resolve module `BatchedBridge` from `E:\reactNative\albums\node_modules\react-native\Libraries\Interaction\InteractionManager.js`: Module does not exist in the module map or in these directories:
  E:\reactNative\albums\node_modules

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start --reset-cache`.
    at p.catch.error (E:/reactNative/albums/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:366:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)
Bundling `index.android.js`  98.1% (519/524), failed.

**Comment by hramos** [comment] 2017-04-24 13:07
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-04-24 13:07 UTC
