### ISSUE TITLE
PermissionsAndroid not work with Android 7.0

### ISSUE THREAD

**Issue by utopianism** [facebook/react-native#14184] opened 2017-05-25 07:11 UTC
### Description

seems PermissionsAndroid does not work properly with Android 7.0

### Reproduction Steps and Sample Code

I need detect incoming phone state,  then I had involved the PermissionsAndroid API  request READ_PHONE_STATE permission. 
as http://facebook.github.io/react-native/releases/0.41/docs/permissionsandroid.html doc:
> If the optional rationale argument is included (which is an object with a title and message), this function checks with the OS whether it is necessary to show a dialog explaining why the permission is needed (https://developer.android.com/training/permissions/requesting.html#explain) and then shows the system permission dialog

`granted === PermissionsAndroid.RESULTS.GRANTED` return true, 
but dialog didn't show, and I can't detect phone state.

### Additional Information

* React Native version: 0.41
* Platform: Android 7.0

**Comment by hramos** [comment] 2017-05-25 19:58
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-05-25 19:58 UTC
