### ISSUE TITLE
react-native 0.63.2  Image upload error [TypeError: Network request failed]

### ISSUE THREAD

**Issue by sureshhallyali** [facebook/react-native#29493] opened 2020-07-25 19:52 UTC
## Description:
When I am trying to post data with fetch() it will post data successfully but if image or any file try to post then  it will throw error as shown below
Error :   [TypeError: Network request failed]

code:

 function openImagePicker() {
              ImagePicker.openPicker({
              width: 300,
              height: 400,
              cropping: true
            })
            .then(image => {
                console.log(image.path);
                        const data = new FormData();
                        data.append('email', "email");
                         data.append('file',  { uri:image.path, name: 'image.jpg', type: 'image/jpeg/jpg'});

                        let res = fetch(
                                      'http://134.209.144.127/cowsoncloud/admin/cowRegister.php',{
                                      method: 'POST',
                                      body: data,
                                      headers: {
                                                  'Accept': "application/json",
                                                  'Content-Type': 'multipart/form-data',
                                                },
                                  })
                        .then(response => response.json())
                        .then(responseJson => {
                            console.log('upload succes',+responseJson);
                            alert('Upload success!'+JSON.stringify(responseJson));
                        })
                        .catch(error => {
                            console.log('upload error', error);
                            alert('Upload failed!'+error);
                        });
                        
        });
 } 
Note:
* Using  react-native-image-crop-picker package
* in android permission also given such as 
   <uses-permission android:name="android.permission.CAMERA"/>
    android:usesCleartextTraffic="true"
     in this file android/app/src/main/AndroidManifest.xml

## Tried this all solution but not working

1 : By giving  Permission
uesCleartextTraffic="true" to the AndroidManifest.xml file found inside the dir android/app/src/main/AndroidManifest.xml
for handle http and https

2: Adding comment
        // initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
               in this file /android/app/src/main/java/com/{your_project}/MainApplication.java
3: Adding comment
         // builder.addNetworkInterceptor(new FlipperOkhttpInterceptor(networkFlipperPlugin));
         in his file android/app/src/debug/java/com/{your_project}/ReactNativeFlipper.java

4: By upgrading upgrade react native to 63.2 or new  version 
5: FLIPPER version upgrading to 50.0

Source image
![Screenshot from 2020-07-26 01-19-53](https://user-images.githubusercontent.com/57383836/88465142-39712780-cede-11ea-9398-ac83577c1791.png)

**Comment by nhuson269** [comment] 2020-07-26 00:40
My application needs to solve this problem, I have had an issue with iOS since upgrading to version 0.63.x

https://github.com/facebook/react-native/issues/29021

**Comment by Mhde96** [comment] 2020-07-28 13:19
am have same issues with react native 0.63

**Comment by sjonchhe** [comment] 2020-07-30 05:41
I had the same issue in rn v0.62.2. Solved it by upgrading flipper version to 0.47.0

**Comment by andrekovac** [comment] 2020-07-31 10:12
@sjonchhe How do you upgrade the Flipper version for iOS?

For Android I update `FLIPPER_VERSION` in `gradle.properties`. But I don't know how to do it for iOS..

**Comment by dharmendrashah** [comment] 2020-07-31 10:56
i remember this issue, i spent 4 days to google this thing out but nothing works.
will this is a vey common problem in RN 0.62
But this [react-native-fetch-blob](https://www.npmjs.com/package/react-native-fetch-blob) package is really good try this it will sure help you out.

**Comment by andrekovac** [comment] 2020-07-31 11:07
For me it's an issue because the requests of packages I use (i.e. `react-native-video` and `@aws-amplify/auth`) fail..

**Comment by ignaciosantise** [comment] 2020-07-31 20:27
In my case, the problem was Flipper. 
This is how i partially solved the problem in Android:

https://github.com/facebook/react-native/issues/28551#issuecomment-610652110

**Comment by cbedoy** [comment] 2020-08-03 04:45
Same error here, iOS app work perfectly but Android is failing.

```
2020-08-02 23:41:44.331 22868-22964/com.rndagm8 E/unknown:NetworkingModule: Failed to send url request: http://amazing.url.com
    java.lang.IllegalStateException: Multipart body must have at least one part.
        at okhttp3.MultipartBody$Builder.build(MultipartBody.java:341)
``` 

I already disabled Flipper and still failing, oh god! I've expending to much time facing error with iOS releasing and now this thing, what's next?

**Comment by safaiyeh** [comment] 2020-08-03 16:48
Duplicate of https://github.com/facebook/react-native/issues/28551

Let me know if the solutions on that issue help resolve this.

**Closed** 2020-08-03 16:48 UTC
Labels: Component: Image, Needs: Triage :mag:, Resolution: Duplicate

**Comment by meiqi1992** [comment] 2020-08-14 10:05
same issue+1

**Comment by premdasvm** [comment] 2020-09-25 15:04
same issue +1

**Comment by sudheepkr** [comment] 2020-09-27 19:01
Error gone i coded like this.
let formData = new FormData(); formData.append('file_name', {uri: fileUri,type:fileType,name:fileName});

**Comment by Asimurrehman** [comment] 2020-12-19 10:04
### **I am  also using "react-native": "0.63.2"**

my error Gone i did in the same way above :

1)Added a comment
// builder.addNetworkInterceptor(new FlipperOkhttpInterceptor(networkFlipperPlugin));
file path: android/app/src/debug/java/com/{your_project}/ReactNativeFlipper.java
then Rebuild my App using 'yarn run android '
then every thing will successfully worked  

**my code 👍** 

        let body = new FormData();
        body.append('submit', 'ok');
        body.append('file', {
          uri: res.uri,
          name: res.fileName,
          type: res.type,
        });

**Comment by phaolin10** [comment] 2021-01-04 03:29
same issue

**Comment by prakhar-mindcrew** [comment] 2021-04-16 09:29
still facing issue, rn version 0.63.4 and FLIPPER_VERSION=0.54.0. please suggest how can i fix ?

**Comment by prakhar-mindcrew** [comment] 2021-04-16 09:30
still getting same, rn version 0.63.4 and FLIPPER_VERSION=0.54.0. please suggest how can i fix ?

**Comment by banjo09** [comment] 2021-05-26 13:03
Doing this:

appending the uri information does not work. It doesn't even send the network request when I try to append an object. But if I append it as a string using Json stringify method.

Then it will send the request, but it breaks for obvious reasons. Why is FormData not allowing me to append an object?

from https://github.com/react-native-image-picker/react-native-image-picker/issues/798 by https://github.com/reboss

**Comment by 11AA8R4** [comment] 2021-08-13 14:17
**_### Answer_**
1 - on android, if your 'uri' or 'path' being uploaded is not starting with **file://** appearently you wont be uploading your file, so:
2 - try some of these:
  a - `if(asset.slice(0,7)!=='file://' && Platform.OS==='android') asset = 'file://'+asset // (where 'asset' is your path/uri)`
  b - or, temporarily upload your image with `RNFetchBlob `// (i teach you how to later on)
  then add the `'file://'` in front of your uri/path
  

**_### Additional_**
How to upload localy using RNFetchBlob (_if you want_):
1 - install the library: rn-fetch-blob
**Note:** _There are additional steps in installation that must be done, like the one to add_ `android:requestLegacyExternalStorage="true"`
_to your manifest's android file (without this and the other steps you might be not being able to store the image)_
2 - Then when rn-fetch-blob is properly (and fully) installed, create your file: (_replace **AAAA** with your desired folder inside your phone_)
```
const type = (service.assets[key].split(':')[1]).split('/')[0]
const ext = (service.assets[key].split(';')[0]).split('/')[1]
const path = `{RNFetchBlob.fs.dirs.DCIMDir}/AAAA/${fileName}.${ext}`
await RNFetchBlob.fs.writeFile(path,service.assets[key].split(',')[1],'base64')
```
This code will detected file **type**, **extension**, create a **path** where you desire (this path will be your uri further) and **store** your image localy on your phone as a base64 image
**Finally** all you need is to use that path variable inside your **formData** AS FOLLOWS **if android**:
`'file://'+path`

Usage example:
```
if(path.slice(0,7)!=='file://' && Platform.OS==='android') path = 'file://'+path
formData.append(index,{uri:path,name:'fileName.jpeg',type:'image/jpeg'})
```
