### ISSUE TITLE
the scrollToEnd / scrollToOffset methods of FlatList execute unexpected if set ListHeaderComponent prop

### ISSUE THREAD

**Issue by kid-wumeng** [facebook/react-native#15804] opened 2017-09-05 04:39 UTC
Hi, good people... thanks your contributions for react-native, the amazing framework.

Now... I happen the issue, very headache...

react-native version: 0.47.1

Example, render the FlatList like this:

```
<FlatList
  ref="flatlist"
  ListHeaderComponent={one header component...}
/>
```

Maybe, the header component has a height such as 300.

When i execute `scrollToEnd` methods, i hope the list scroll to end, and the scroll distance should includes the header height (now 300).

But, it will scroll unexpected. the list will scroll to an uncertain position.

Based on my observation, it seemingly did not computed and included the header height.

Whether this is a bug or not ? How can i solve it in current version ?

**Comment by sm2017** [comment] 2017-09-05 10:16
@facebook-github-bot no-template

**Comment by hramos** [comment] 2017-09-05 19:28
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue that meets the requirements set forth in the template. Thanks!

**Closed by hramos** 2017-09-05 19:28 UTC

**Comment by adamterlson** [comment] 2018-03-16 12:21
I also suffered from this issue, and was able to work around it by accessing the scrollResponder directly:

```javascript
    this.listRef.getScrollResponder().scrollResponderScrollToEnd({
      animated: animated,
    });
```
