### ISSUE TITLE
Bound class property functions don't hot reload

### ISSUE THREAD

**Issue by levibuzolic** [facebook/react-native#15363] opened 2017-08-04 02:48 UTC
### Is this a bug report?

Yes.

### Have you read the Bugs section of the How to Contribute guide?

Yes.

### Environment

```yml
react-native-cli: 2.0.1
react-native: 0.47.1
node: 6.9.1
npm: 5.3.0
yarn: 0.27.5
```

- Target Platform: iOS
- Development Operating System: macOS 10.12.6
- Build tools: `react-native run-ios`

### Steps to Reproduce

1. Define a component with an auto bound class property function like: 
    ```js
    render() {
      return <View>{this.renderSomething()}</View>;
    }

    renderSomething = () => {
      return <Text>Test</Text>;
    }
    ```
2. With Hot Reloading turned on, update the text in the `renderSomething` function.

### Expected Behavior

The component is hot-reloaded and the render is updated.

When using the manual bind in constructor syntax, hot reloading works.

### Actual Behavior

Hot reloading message shows up but the bound function isn't re-rendered.

### Reproducible Demo

https://github.com/levibuzolic/HotReloadBug

```js
import React from 'react';
import {View, Text} from 'react-native';

export default class HotReloadingTest extends React.Component {
  constructor(props) {
    super(props);

    this.manualBind = this.manualBind.bind(this);
  }

  render() {
    return (
      <View style={{flex: 1, paddingTop: 20}}>
        <View style={{flex: 1, backgroundColor: 'rgba(0, 255, 0, 0.1)'}}>
          {this.manualBind()}
        </View>
        <View style={{flex: 1, backgroundColor: 'rgba(255, 0, 0, 0.1)'}}>
          {this.autoBind()}
        </View>
      </View>
    );
  }

  manualBind() {
    return (
      <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
        <Text>Manual reloads fine</Text>
      </View>
    );
  }

  autoBind = () => {
    return (
      <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
        <Text>Auto doesn’t hot reload</Text>
      </View>
    );
  }
}
```

![kapture 2017-08-04 at 12 42 21](https://user-images.githubusercontent.com/721323/28952150-b2ad49b4-7912-11e7-9b99-d77b85293d45.gif)

**Comment by mfrachet** [comment] 2017-08-04 05:37
Can this be related to https://github.com/facebook/react-native/issues/10991#issuecomment-309595705 ?

**Comment by levibuzolic** [comment] 2017-08-04 05:47
Yes, @mfrachet I think it may be.

Looks like it's likely because React Native is using `react-transform-hmr` and not the newer `react-hot-loader`.

Unfortunately @bvic23's solution - [babel-plugin-functional-hmr](https://github.com/bvic23/babel-plugin-functional-hmr) doesn't appear to work for arrow functions defined in classes.

**Comment by hramos** [comment] 2017-08-04 06:40
Duplicate of #10991

**Closed by hramos** 2017-08-04 06:40 UTC

**Comment by grit96** [comment] 2018-07-11 13:59
@hramos can you re-open this as it is a different issue to #10991

**Comment by trongnd** [comment] 2018-08-29 18:56
I created this babel plugin [babel-plugin-transform-class-bound-properties](https://github.com/trongnd/babel-plugin-transform-class-bound-properties) to solve hot loading issue with class bound properties. Works with babel 6.x
