### ISSUE TITLE
[Layout] Vertical centering fails when container has absolute positioning and no explicit height

### ISSUE THREAD

**Issue by premasagar** [facebook/react-native#1234] opened 2015-05-11 11:09 UTC
The code below renders like this, with the red square at the top of the container (screenshot from iOS 8.3 simulator):

![positioning-1](https://cloud.githubusercontent.com/assets/116809/7563533/04c9c63e-f7d6-11e4-969a-c92f63b6cba3.png)

If an explicit `height:70` is set on the container, then the red square is vertically centered:

![positioning-2](https://cloud.githubusercontent.com/assets/116809/7563534/04d04f04-f7d6-11e4-9825-e703894b0257.png)

I would expect the square to be vertically centered within its container, without needing to set an explicit height. The yellow background color fills the height of the element without an explicit height set.

This is only an issue for elements that have absolute positioning, not those with relative positioning.

``` jsx
<View>
    <View style={{
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      flex: 1,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'yellow'
    }}>
      <View style={{
        backgroundColor: 'red',
        width: 10,
        height: 10
      }}/>
    </View>

    <View style={{
      opacity: 0.5,
      borderColor: 'black',
      borderWidth: 1
    }}>
      <Text>Lorem ipsum lorem ipsum</Text>
      <Text>Lorem ipsum lorem ipsum</Text>
      <Text>Lorem ipsum lorem ipsum</Text>
      <Text>Lorem ipsum lorem ipsum</Text>
    </View>
  </View>
```

Maybe related #384

**Comment by BlooJeans** [comment] 2015-05-22 20:19
Also experiencing this issue, hardcoding the height fixes it for me

**Comment by brentvatne** [comment] 2015-05-29 22:32
Looks like a bug to me, @lwansbrough can you test this out when you pull the newest version of css-layout? 

Runnable example that you can just copy and paste in: [here](https://rnplay.org/plays/QsaXWA/edit)

**Comment by chirag04** [comment] 2015-06-10 18:12
+1. Just got hit by this bug. need to explicitly give a height.

**Comment by dubert** [comment] 2015-07-16 14:41
:+1: I have a very similar issue but it doesn't matter whether or not the position is it. In my case, if there are several columns in a row, and the content in one column determines the height of the row, vertical centering does not work in the other columns.

<img width="379" alt="screen shot 2015-07-16 at 10 36 34" src="https://cloud.githubusercontent.com/assets/1843672/8726240/012f1074-2ba7-11e5-877e-bfb4f885742d.png">

Here is the css for this screenshot:
```
leftRowActions: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',

    borderBottomColor: 'white',
    borderBottomWidth: 2,
    backgroundColor: '#3878c8'
  },
  rightRowActions: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',

    borderBottomColor: 'white',
    borderBottomWidth: 2,
    backgroundColor: '#26c3bd'
  },
```

**Comment by pietropizzi** [comment] 2015-08-31 13:14
+1 On this bug. Should we create an issue in https://github.com/facebook/css-layout ?

**Comment by eluleci** [comment] 2015-09-06 09:09
+1. I am having same issue too.

**Comment by alvingarcia** [comment] 2015-09-07 11:57
+1. having same issue

**Comment by ide** [comment] 2015-09-07 17:54
Please open this bug in the css-layout repo.

**Comment by pietropizzi** [comment] 2015-09-07 21:40
I'm actually pretty sure it has already been opened https://github.com/facebook/css-layout/issues/83 Needs some love there though

**Comment by hufeng** [comment] 2015-09-12 04:24
Yes, + 1. I am having same issue too.

**Comment by kitt1987** [comment] 2015-09-14 08:03
+1

**Comment by jhau** [comment] 2015-09-21 03:14
+1

**Comment by swathysubhash** [comment] 2015-09-24 11:28
+1

**Comment by ilansas** [comment] 2015-10-20 15:15
+1

**Comment by SteveMellross** [comment] 2015-10-25 08:59
+1

**Comment by respectTheCode** [comment] 2015-11-24 10:59
+1

**Comment by smalllixin** [comment] 2015-12-16 11:28
+1

**Comment by olivierlesnicki** [comment] 2015-12-26 17:52
+1

**Comment by niftylettuce** [comment] 2016-01-07 20:03
+1

**Comment by kaplanov** [comment] 2016-01-15 15:10
+1

**Comment by janmonschke** [comment] 2016-01-21 13:35
Ran into this issue just now as well. I hope https://github.com/facebook/css-layout/pull/145 gets merged soon which will fix this issue.

**Comment by waterdoo** [comment] 2016-02-10 21:23
+1

**Comment by guyca** [comment] 2016-02-18 08:14
+1

**Comment by joonhocho** [comment] 2016-05-07 20:20
+1

**Comment by MateuszMxxxx** [comment] 2016-05-25 08:03
+1

**Comment by ultragtx** [comment] 2016-05-31 12:47
+1

**Comment by braco** [comment] 2016-06-29 19:39
@janmonschke: looks like its merged, issue still exist?

**Comment by edencakir** [comment] 2016-10-15 13:59
+!

**Comment by edencakir** [comment] 2016-10-15 14:14
+1 exists

**Comment by goodyboy6** [comment] 2016-10-31 06:06
+1

**Comment by mrpp01** [comment] 2016-11-21 00:38
I could not reproduce the bug as described. I think it has been resolved with the recent css-layout merge.

**Comment by jose920405** [comment] 2016-11-28 16:52
+1

**Comment by ericvicenti** [comment] 2017-03-06 06:42
Closing because this appears to be solved. Please re-open a new issue if you have a clear reproduction on new versions of RN.

**Closed by ericvicenti** 2017-03-06 06:42 UTC
Labels: iOS
