### ISSUE TITLE
[0.54] <TextInput> not support chinese

### ISSUE THREAD

**Issue by musicode** [facebook/react-native#18260] opened 2018-03-08 01:59 UTC

**Comment by bunnyc1986** [comment] 2018-03-09 14:03
I am facing the same issue. I upgrade RN from 0.50 to 0.54 today. Suddenly, I cannot type Chinese with the iOS built in Chinese keyboard.
Please investigate.

**Comment by kidmysoul** [comment] 2018-03-10 07:09
the same for japanese input . cannot type the word but only alphabet

https://github.com/facebook/react-native/issues/12599

**Comment by jiangbophd** [comment] 2018-03-14 15:31
What is time can be fixed? this is very big issue!!!!!

**Comment by danielsuo** [comment] 2018-03-16 03:43
@jiangbophd @kidmysoul @bunnyc1986 @musicode Would it be all right to consolidate our comments over on issue #18403? I filled out the template and created both working and broken examples / tagged the authors of the likely commits that caused the breaking change. Hopefully, it will get the attention of Facebook folk faster.

Even though this bug is annoying, really glad that others are also experiencing and it's not just me!

**Comment by hramos** [comment] 2018-03-19 21:22
Duplicate of #18403

**Closed by hramos** 2018-03-19 21:22 UTC
Labels: :clipboard:No Template, :large_orange_diamond:TextInput, Ran Commands
