### ISSUE TITLE
RN75 Upgrade - RNGP no longer allows me to exclusively use corporate Maven registry 

### ISSUE THREAD

**Issue by henrygrant** [facebook/react-native#46375] opened 2024-09-06 19:06 UTC
### Description

My company blocks access to typical public maven registries like MavenCentral, GradlePluginPortal, etc. We host an internal Nexus Maven registry that proxies all of those public registries through it. 

We do a similar thing for NPM, and in that case we just set the registry's url in our `.npmrc` file and call it a day. This is not the case for Maven. 

Currently we're on React Native 74 and have historically done 2 things in order to force our project to use our internal registry exclusively:

First, we created an [init.gradle](https://github.com/henrygrant/rn-private-reg/blob/broken-75/ReproducerApp/init.gradle) file that overrides repositories and plugin repositories with ours. React Native Gradle Plugin (and perhaps other gradle-files-buried-in-node-modules) doesn't seem to respect this configuration, and I've never been able to figure out a Gradle-based way to handle it. This leads me to [the second piece of our solution](https://github.com/henrygrant/rn-private-reg/blob/broken-75/ReproducerApp/postinstall.sh), which is just shoving our repository url into RNGP's `settings.gradle.kts`'s `repositories{}` block. 

This works up until React Native 75, where something has changed but I can't seem to tell what. I now consistently get the below error both in my company's project and this example project, where `gson`, `guava`, `kotlin-stdlib`, and `javapoet` are trying to hit public registries and ignoring both my `init.gradle` and my edits to RNGP's `settings.gradle.kts`.

Does anyone who works on React Native Gradle Plugin have a suggestion here? I really wish there was some kind of configuration I could pass to React Native Gradle Plugin to override it's looking in public repositories exclusively, but that is more of a feature request. RNGP not respecting `init.gradle` seems to be more of a bug though, as that should be overriding any gradle configuration of any lower project. 

### Steps to reproduce

Hard to test from your end as I don't imagine you have a nexus registry to use. I did reproduce the issue in the reproducer [here](https://github.com/henrygrant/rn-private-reg/tree/broken-75). 

1. Block access to MavenCentral, GradlePluginPortal, GoogleMaven, etc
2. Replace url in `init.gradle` and `postinstall.sh` with your registry
3. `yarn`
4. `yarn android`

It's worth noting that I also made identical changes to a reproducer on RN74 and did not see this issue.

### React Native Version

0.75.2

### Affected Platforms

Runtime - Android, Build - MacOS

### Output of `npx react-native info`

```text
info Fetching system and libraries information...
System:
  OS: macOS 14.6.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 76.88 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.18.2
    path: ~/.nvm/versions/node/v18.18.2/bin/node
  Yarn:
    version: 3.6.4
    path: ~/.nvm/versions/node/v18.18.2/bin/yarn
  npm:
    version: 9.8.1
    path: ~/.nvm/versions/node/v18.18.2/bin/npm
  Watchman:
    version: 2023.12.04.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK:
    API Levels:
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
    Build Tools:
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 33.0.1
      - 33.0.2
      - 34.0.0
    System Images:
      - android-31 | Google APIs ARM 64 v8a
      - android-33 | Google APIs ARM 64 v8a
      - android-33 | Google Play ARM 64 v8a
      - android-35 | Google Play Experimental 16k Page Size ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2411.12169540
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 3.2.2
    path: /opt/homebrew/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.2
    wanted: 0.75.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
```

### Stacktrace or Logs

```text
info Installing the app...
Starting a Gradle Daemon (subsequent builds will be faster)
Repository names before: [Google, Gradle Central Plugin Repository, MavenRepo, maven]
Repository names after: [REDACTED]
8 actionable tasks: 8 executed

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 


FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all artifacts for configuration 'classpath'.
> Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.9.24.
  Required by:
      unspecified:unspecified:unspecified > project :gradle-plugin:settings-plugin
      unspecified:unspecified:unspecified > project :gradle-plugin:settings-plugin > project :gradle-plugin:shared
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.9.24.
      > Could not get resource 'https://plugins.gradle.org/m2/org/jetbrains/kotlin/kotlin-stdlib/1.9.24/kotlin-stdlib-1.9.24.pom'.
         > Could not HEAD 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.9.24/kotlin-stdlib-1.9.24.pom'. Received status code 503 from server: Service Unavailable
> Could not resolve com.google.code.gson:gson:2.8.9.
  Required by:
      unspecified:unspecified:unspecified > project :gradle-plugin:settings-plugin
      unspecified:unspecified:unspecified > project :gradle-plugin:settings-plugin > project :gradle-plugin:shared
   > Could not resolve com.google.code.gson:gson:2.8.9.
      > Could not get resource 'https://plugins.gradle.org/m2/com/google/code/gson/gson/2.8.9/gson-2.8.9.pom'.
         > Could not HEAD 'https://repo.maven.apache.org/maven2/com/google/code/gson/gson/2.8.9/gson-2.8.9.pom'. Received status code 503 from server: Service Unavailable
> Could not resolve com.google.guava:guava:31.0.1-jre.
  Required by:
      unspecified:unspecified:unspecified > project :gradle-plugin:settings-plugin
      unspecified:unspecified:unspecified > project :gradle-plugin:settings-plugin > project :gradle-plugin:shared
   > Could not resolve com.google.guava:guava:31.0.1-jre.
      > Could not get resource 'https://plugins.gradle.org/m2/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.pom'.
         > Could not HEAD 'https://repo.maven.apache.org/maven2/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.pom'. Received status code 503 from server: Service Unavailable
> Could not resolve com.squareup:javapoet:1.13.0.
  Required by:
      unspecified:unspecified:unspecified > project :gradle-plugin:settings-plugin
   > Could not resolve com.squareup:javapoet:1.13.0.
      > Could not get resource 'https://plugins.gradle.org/m2/com/squareup/javapoet/1.13.0/javapoet-1.13.0.pom'.
         > Could not HEAD 'https://repo.maven.apache.org/maven2/com/squareup/javapoet/1.13.0/javapoet-1.13.0.pom'. Received status code 503 from server: Service Unavailable

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 21s
error Failed to install the app. Command failed with exit code 1: ./gradlew app:installDebug -PreactNativeDevServerPort=8081 FAILURE: Build failed with an exception. * What went wrong:
Could not resolve all artifacts for configuration 'classpath'.
> Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.9.24. Required by: unspecified:unspecified:unspecified > project :gradle-plugin:settings-plugin unspecified:unspecified:unspecified > project :gradle-plugin:settings-plugin > project :gradle-plugin:shared > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.9.24. > Could not get resource 'https://plugins.gradle.org/m2/org/jetbrains/kotlin/kotlin-stdlib/1.9.24/kotlin-stdlib-1.9.24.pom'. > Could not HEAD 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.9.24/kotlin-stdlib-1.9.24.pom'. Received status code 503 from server: Service Unavailable
> Could not resolve com.google.code.gson:gson:2.8.9. Required by: unspecified:unspecified:unspecified > project :gradle-plugin:settings-plugin unspecified:unspecified:unspecified > project :gradle-plugin:settings-plugin > project :gradle-plugin:shared > Could not resolve com.google.code.gson:gson:2.8.9. > Could not get resource 'https://plugins.gradle.org/m2/com/google/code/gson/gson/2.8.9/gson-2.8.9.pom'. > Could not HEAD 'https://repo.maven.apache.org/maven2/com/google/code/gson/gson/2.8.9/gson-2.8.9.pom'. Received status code 503 from server: Service Unavailable
> Could not resolve com.google.guava:guava:31.0.1-jre. Required by: unspecified:unspecified:unspecified > project :gradle-plugin:settings-plugin unspecified:unspecified:unspecified > project :gradle-plugin:settings-plugin > project :gradle-plugin:shared > Could not resolve com.google.guava:guava:31.0.1-jre. > Could not get resource 'https://plugins.gradle.org/m2/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.pom'. > Could not HEAD 'https://repo.maven.apache.org/maven2/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.pom'. Received status code 503 from server: Service Unavailable
> Could not resolve com.squareup:javapoet:1.13.0. Required by: unspecified:unspecified:unspecified > project :gradle-plugin:settings-plugin > Could not resolve com.squareup:javapoet:1.13.0. > Could not get resource 'https://plugins.gradle.org/m2/com/squareup/javapoet/1.13.0/javapoet-1.13.0.pom'. > Could not HEAD 'https://repo.maven.apache.org/maven2/com/squareup/javapoet/1.13.0/javapoet-1.13.0.pom'. Received status code 503 from server: Service Unavailable * Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org. BUILD FAILED in 21s.
info Run CLI with --verbose flag for more details.
```

### Reproducer

https://github.com/henrygrant/rn-private-reg/tree/broken-75

**Comment by zamanphp** [comment] 2024-09-08 21:53
I have the same error

**Comment by cortinico** [comment] 2024-09-12 17:39
So there are a couple of things to unfold here:

> First, we created an [init.gradle](https://github.com/henrygrant/rn-private-reg/blob/broken-75/ReproducerApp/init.gradle?rgh-link-date=2024-09-06T19%3A06%3A22Z) file that overrides repositories and plugin repositories with ours. React Native Gradle Plugin (and perhaps other gradle-files-buried-in-node-modules) doesn't seem to respect this configuration, and I've never been able to figure out a Gradle-based way to handle it. This leads me to [the second piece of our solution](https://github.com/henrygrant/rn-private-reg/blob/broken-75/ReproducerApp/postinstall.sh?rgh-link-date=2024-09-06T19%3A06%3A22Z), which is just shoving our repository url into RNGP's settings.gradle.kts's repositories{} block.

I don't think you need `init.gradle` at all. I see you already have a `postinstall.sh` script that manipulates the RNGP repositories block.

Then the only other thing you need is to edit the `android/settings.gradle` file as follows:

```diff
+pluginManagement {
+   repositories {
+       println "Plugin MGMT - Repository names before: " + repositories.getNames()
+       clear()
+       maven { url "https://example.com/m2/" }
+       println "Plugin MGMT - Repository names after: " + repositories.getNames()
+   }
+   includeBuild("../node_modules/@react-native/gradle-plugin")
+}
-pluginManagement { includeBuild("../node_modules/@react-native/gradle-plugin") }
plugins { id("com.facebook.react.settings") }
extensions.configure(com.facebook.react.ReactSettingsExtension){ ex -> ex.autolinkLibrariesFromCommand() }
rootProject.name = 'ReproducerApp'
include ':app'
includeBuild('../node_modules/@react-native/gradle-plugin')

+dependencyResolutionManagement {
+    repositories {
+       clear()
+       maven { url "https://example.com/m2/" }
+   }
+}
```

> This works up until React Native 75, where something has changed but I can't seem to tell what

What changed is that from 0.75, RNGP ships 2 modules (a project plugin and a settings plugin).
I can't fully reproduce this environment for you as I don't have a URL of a public mirror, but I think you should just add a also to `node_modules/@react-native/gradle-plugin/settings.gradle`

```diff
+dependencyResolutionManagement {
+    repositories {
+       clear()
+       maven { url "https://example.com/m2/" }
+   }
+}
```

and you should be good 👍

Please let me know if this unblocks you

**Comment by mehedisarkar2k** [comment] 2024-09-13 01:58
Same here, the issue is still present.

**Comment by henrygrant** [comment] 2024-09-13 15:01
@cortinico 

Thanks for the info. Your solution got me running, but I couldn't fully get away from `init.gradle`. [Check out this commit](https://github.com/henrygrant/rn-private-reg/commit/901231731566c33c8ee6127c3e89db49a2e76e8b) to see the working state of the reproducer.

I'd love to be able to avoid having an `init.gradle` altogether. I tried to put the below configuration in a few different places but ultimately can't seem to figure out where else it can live.

```
def MY_REPOS = {
    maven { url = uri("https://myrepo.com/nexus/repository") }
}

allprojects {
    repositories(MY_REPOS)
    buildscript {
        repositories(MY_REPOS)
    }
}
```

**Comment by cortinico** [comment] 2024-09-13 16:40
> Thanks for the info. Your solution got me running

Closing then.

> I'd love to be able to avoid having an init.gradle altogether. I tried to put the below configuration in a few different places but ultimately can't seem to figure out where else it can live.

What is the error you're having? Did it just ignore your configuration?
I think the problem is the timing of when the `init.gradle` script is executed.

**Closed by cortinico** 2024-09-13 16:40 UTC
Labels: Resolution: Answered

**Comment by henrygrant** [comment] 2024-09-13 16:54
It's the same error as before, attempting to hit public registries instead of my internal one. At the bottom of this comment is the output of the Gradle build without the below configuration in `init.gradle`.
```
def MY_REPOS = {
    maven { url = uri("https://myrepo.com/nexus/repository") }
}

allprojects {
    repositories(MY_REPOS)
    buildscript {
        repositories(MY_REPOS)
    }
}
```


```
info Installing the app...
> Task :gradle-plugin:shared:compileKotlin FAILED
3 actionable tasks: 3 executed

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gradle-plugin:shared:compileKotlin'.
> Could not resolve all files for configuration ':gradle-plugin:shared:compileClasspath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.9.24.
     Required by:
         project :gradle-plugin:shared
      > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.9.24.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.9.24/kotlin-stdlib-1.9.24.pom'.
            > Could not HEAD 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.9.24/kotlin-stdlib-1.9.24.pom'. Received status code 503 from server: Service Unavailable
   > Could not resolve com.google.code.gson:gson:2.8.9.
     Required by:
         project :gradle-plugin:shared
      > Could not resolve com.google.code.gson:gson:2.8.9.
         > Could not get resource 'https://repo.maven.apache.org/maven2/com/google/code/gson/gson/2.8.9/gson-2.8.9.pom'.
            > Could not HEAD 'https://repo.maven.apache.org/maven2/com/google/code/gson/gson/2.8.9/gson-2.8.9.pom'. Received status code 503 from server: Service Unavailable
   > Could not resolve com.google.guava:guava:31.0.1-jre.
     Required by:
         project :gradle-plugin:shared
      > Could not resolve com.google.guava:guava:31.0.1-jre.
         > Could not get resource 'https://repo.maven.apache.org/maven2/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.pom'.
            > Could not HEAD 'https://repo.maven.apache.org/maven2/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.pom'. Received status code 503 from server: Service Unavailable

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 7s
error Failed to install the app. Command failed with exit code 1: ./gradlew app:installDebug -PreactNativeDevServerPort=8081 FAILURE: Build failed with an exception. * What went wrong:
Execution failed for task ':gradle-plugin:shared:compileKotlin'.
> Could not resolve all files for configuration ':gradle-plugin:shared:compileClasspath'. > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.9.24. Required by: project :gradle-plugin:shared > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.9.24. > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.9.24/kotlin-stdlib-1.9.24.pom'. > Could not HEAD 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.9.24/kotlin-stdlib-1.9.24.pom'. Received status code 503 from server: Service Unavailable > Could not resolve com.google.code.gson:gson:2.8.9. Required by: project :gradle-plugin:shared > Could not resolve com.google.code.gson:gson:2.8.9. > Could not get resource 'https://repo.maven.apache.org/maven2/com/google/code/gson/gson/2.8.9/gson-2.8.9.pom'. > Could not HEAD 'https://repo.maven.apache.org/maven2/com/google/code/gson/gson/2.8.9/gson-2.8.9.pom'. Received status code 503 from server: Service Unavailable > Could not resolve com.google.guava:guava:31.0.1-jre. Required by: project :gradle-plugin:shared > Could not resolve com.google.guava:guava:31.0.1-jre. > Could not get resource 'https://repo.maven.apache.org/maven2/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.pom'. > Could not HEAD 'https://repo.maven.apache.org/maven2/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.pom'. Received status code 503 from server: Service Unavailable * Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org. BUILD FAILED in 7s.
```

**Comment by cortinico** [comment] 2024-09-13 18:45
> At the bottom of this comment is the output of the Gradle build without the below configuration in `init.gradle`.

Although it's an anti-pattern, could you try to edit your `init.gradle` as follows:

```groovy
allprojects {
	afterEvaluate {
        repositories(MY_REPOS)
        buildscript {
            repositories(MY_REPOS)
        }
    }
}
```

**Comment by smith-xyz** [comment] 2025-01-24 18:44
Just to clarify - is there no other way to get @react-native/gradle-plugin/settings.gradle.kts to use the private repository config in the pluginManagement {} block?

I have a native module library with an example app built in. Trying to configure this with the company's private repository and had to follow a similar pattern of writing a script to inject the setup into @react-native/gradle-plugin/settings.gradle.kts - this could just be my lack of understanding of how gradle works in this situation.

Here is the setup to be used as a reproducer: 
https://github.com/smith-xyz/react-native-bridge-template

For this, I do actually have an init.gradle in my /Users/<username>/.gradle folder that doesn't seem to be executed prior to this event. 

Running gradlew build --info I do see the hierarchy is using the /example/settings.gradle to include the build of this plugin.

Let me know if this should be opened as a different issue.

**Comment by cortinico** [comment] 2025-01-27 18:36
> Let me know if this should be opened as a different issue.

Yes please 👍
