### ISSUE TITLE
[TextInput] Supply access to UITextView.inputAccessoryView attribute on <TextInput />

### ISSUE THREAD

**Issue by rebeccahughes** [facebook/react-native#371] opened 2015-03-27 22:23 UTC
It would be cool to have this to make sticky text inputs.

(t21661353)

**Comment by sahrens** [comment] 2015-03-28 20:16
Yes definitely - this is how we built parts of the comment input in the Groups app. Hopefully we'll be able to clean it up soon and release it to you guys.

**Comment by ide** [comment] 2015-05-12 07:19
@sahrens do you have code you could throw over the wall that I could take a pass at cleaning up?

**Comment by brentvatne** [comment] 2015-05-31 18:24
@sahrens - this would be great to see, this seems to be a highly requested feature

**Comment by sahrens** [comment] 2015-06-01 16:39
I'll take a look at what we have.

**Comment by irfaan** [comment] 2015-07-14 18:40
Was there any luck with this? @sahrens , @auser (https://github.com/facebook/react-native/issues/1190)?

**Comment by tpisto** [comment] 2015-07-28 22:18
+1 for solving this

**Comment by auser** [comment] 2015-07-30 20:12
Not yet, but would be a good idea to get back on this...

**Comment by auser** [comment] 2015-08-01 22:37
I have an initial implementation in progress that is not quite ready yet. When I get it working, I'll gist it. I'm currently working on it as a component (outside of the main repo), but will plan on making it a pull req when it is functional. Also... the API might need some help...

**Comment by LeoFidjeland** [comment] 2015-08-11 16:52
+1

**Comment by OpakAlex** [comment] 2015-08-25 12:11
+1

**Comment by alancmclean** [comment] 2015-08-31 15:19
+1

**Comment by sahrens** [comment] 2015-09-04 02:55
Sounds great, @auser - looking forward to that PR ;)

**Comment by sjmueller** [comment] 2015-09-05 05:12
I've been playing around with tying an inputAccessoryView with RN.  One thing I immediately noticed is that when using the navigator component, keyboard dismissal isn't as clean as with UINavigationController.  An example of the regular behavior:

![keyboard-slideaway](https://cloud.githubusercontent.com/assets/29085/9697784/cb5d038a-5350-11e5-9887-8f4755e06fae.gif)

Notice how the keyboard slides away in tandem with the view as the controller is popped?  Using the navigator component, there's no direct correlation and so the keyboard stays in place (or slides downward if you preemptively dismiss).  The reason why I bring this up is because when using an InputAccessoryView, this difference becomes much more amplified, because the content of the view is usually much more scene-specific than the generic keyboard.

Any suggestions?  I looked all over the groups app, and couldn't find a place where the navigation slides in a way that would reveal this issue.

**Comment by brentvatne** [comment] 2015-09-10 17:18
cc @ericvicenti @hedgerwang @ide - interesting point raised above by @sjmueller

**Comment by ide** [comment] 2015-09-10 20:42
Great point and quite tricky I believe. Since we don't want to use UINavigationController and UIViewController we're going to need to move the keyboard ourselves. Should be possible by getting the UIWindow that contains the keyboard and applying a transform to it. Certainly yet another thing to consider for Navigator scenes.

**Comment by ericvicenti** [comment] 2015-09-10 21:12
Agreed, this will be very tricky. Even if we have the ability to animate the keyboard from RN, the off-thread operation will cause the keyboard animation to lag.

@javache, any idea if we can add hooks to animate the keyboard from RN?

cc @sahrens for the main-thread animation concerns

**Comment by sahrens** [comment] 2015-09-11 05:12
Yeah, messy. Native animations won't handle this any time soon. Might be
worth some custom native hook to link the keyboard to a view based on react
node handle?

**Comment by nicklockwood** [comment] 2015-09-11 12:45
We have an inputAccessoryView prototype internally that would solve this problem, but there were some concerns about performance that have stopped us from shipping it. I'll see if we can revisit that.

**Comment by sjmueller** [comment] 2015-09-11 20:52
@nicklockwood, curious what approach is used with the fb prototype?  Like @ide says, there's no UINavigationController and UIViewController with the Navigator component, so it'd be interesting to learn about the way you're currently solving the challenge.

**Comment by idibidiart** [comment] 2015-09-21 19:12
If it's easier to make it work with NavigatorIOS then let's have that first, please. It's a show stopper in apps that take numeric input for the user not to be able to signal "done" explicitly.  

+1

**Comment by auser** [comment] 2015-09-24 05:09
@idibidiart Can you share your solution? Is that a pure-JS solution or a UIInputAccessory?

**Comment by sjmueller** [comment] 2015-09-30 05:26
@auser not sure how far along you were from this gist: https://gist.github.com/auser/38d7484d986ab911152c#file-UIViewController+InputAccessory-m

**Comment by idibidiart** [comment] 2015-09-30 12:26
@auser sorry didn't see uour messsage. I'm just browsing this thread again. Mine is a simple JS based solution that is based on DeviceEmitter/KeyboardWillShow event and a simple ankmation of a "Done" button view that is initially hidden below the screen and is then animated up to coincide with the keyboards own animation. I just saw the native solution by @sjmeuller and I'm wondering if something like ut can make it into the next version of React Native @nicklockwood @ide

**Comment by auser** [comment] 2015-09-30 15:41
@sjmueller I forgot I posted that!

Thanks for the reminder. That was the beginning of my work. The issue with that code, as of then was that I wanted to design it with the native 'View' library. With that implementation, it doesn't quite work yet. 

Was talking with @ide to understand that. Perhaps he has an idea with the release of 0.11.x. That was on 0.5.0. 

Anyway, I can get back to work on it. Thanks for the reminder.

**Comment by GantMan** [comment] 2015-10-27 15:11
+1 :+1:

**Comment by pfeiffer** [comment] 2015-10-29 08:24
:+1:

**Comment by braunsquared** [comment] 2015-11-18 15:55
+1

Is there any update on this?  Maybe an updated gist that we could leverage locally in the meantime?

**Comment by lewisbarber** [comment] 2015-11-24 14:59
Still not implemented?

**Comment by shaikhussian** [comment] 2015-11-30 04:26
can any tell me that how to add done button for the keyboardType="number-pad". At the top of the keyboard

**Comment by danleveille** [comment] 2016-01-10 01:58
+1

Any progress on this? :smile::+1:

**Comment by yuriyvl** [comment] 2016-01-11 13:52
+1

**Comment by Obooman** [comment] 2016-01-12 08:14
+1
@auser some progress notification may be great.😄

**Comment by sowdri** [comment] 2016-01-18 07:18
+1

**Comment by jacob-russo** [comment] 2016-02-02 10:50
this would be amazing. really annoying not being able to close the keyboard on the numeric keypad.

**Comment by israelidanny** [comment] 2016-02-10 03:09
@auser and @idibidiart - did either of you come up with a solution that is usable, however imperfectly?

**Comment by danleveille** [comment] 2016-02-10 04:18
@israelidanny I ended up making my own custom one, though the implementation is pretty messy. Had trouble with the animations, though it's usable and it seems to be working fine in my live app.

**Comment by lewisbarber** [comment] 2016-02-24 11:22
@danleveille - could you share your solution please?

**Comment by brentvatne** [comment] 2016-03-07 00:05
Created a ProductPains issue for this here: https://productpains.com/post/react-native/make-ios-uitextviewinputaccessoryview-on-textinput-/ -- please upvote if this is important to you.

@danleveille - if you can share your implementation, messy or otherwise, that could be helpful as a starting point :)

**Comment by danleveille** [comment] 2016-03-15 07:33
@brentvatne @lewisbarber @israelidanny So sorry for the late response!

Here's my current implementation: [@danleveille/react-native-input-accessory-demo](https://github.com/danleveille/react-native-input-accessory-demo)

Again, it's not perfect, and it's a little messy, but it works and I'm using it in my live app and never had any users complain. Feel free to contribute if you can make it any smoother.

**Comment by nazywamsiepawel** [comment] 2016-05-23 13:12
+1

**Comment by EmilScherdin** [comment] 2016-05-30 20:32
+1

**Comment by GantMan** [comment] 2016-05-30 23:24
Would anyone be interested in a component that you could import and use?   I've been considering writing one.

**Comment by latusaki** [comment] 2016-06-04 09:15
+1

**Comment by thethanghn** [comment] 2016-06-06 07:50
+1

**Comment by ammichael** [comment] 2016-06-07 01:55
+1

**Comment by nazywamsiepawel** [comment] 2016-06-13 16:22
@GantMan yes please!

**Comment by danleveille** [comment] 2016-06-13 23:19
@GantMan If you find use in the implementation I shared above, please feel free to reuse any of that. Again, it's a bit amateur, but it works.

**Comment by nazywamsiepawel** [comment] 2016-06-14 16:13
hey @danleveille - just tried your version. I'm trying to get a chat input box done. I reckon the general issue is that until we will be able to somehow get access to native inputAccessoryView the only way is a view chasing the keyboard. That solution usually goes visually out of sync. Closest attempt I have seen so far is contained in [react-native-keyboard-space](https://www.npmjs.com/package/react-native-keyboard-spacer). Still, if even a couple frames are dropped during the animation the "accessory view" is going out of sync and doesn't follow the keyboard as nicely as a native would do. [react-native-gifted-messenger](https://github.com/FaridSafi/react-native-gifted-messenger) has the same problem.

**Comment by melvinxie** [comment] 2016-07-10 07:03
+1

**Comment by congnguyen91** [comment] 2016-07-14 10:10
+1

**Comment by dcosson** [comment] 2016-07-15 07:31
+1

**Comment by sahrens** [comment] 2016-07-15 16:27
So internally we've mostly been using KeyboardAvoidingView and DockingScrollView (and similar one-off components). Have you guys been able to get those to do what you want?

If not, I would suggest using something from @GantMan or @danleveille

**Comment by chirag04** [comment] 2016-07-15 16:51
@sahrens  any plans to open source `DockingScrollView`?

This is what i'm currently using - keyboardAvoidingScrollView: https://gist.github.com/chirag04/d7a7d58f4afc9520a51f511ce7f67788

**Comment by sahrens** [comment] 2016-07-15 17:22
Oh sorry, I thought it was OSS already :\

**Comment by chirag04** [comment] 2016-07-15 18:17
not yet but now i know it's coming :D

**Comment by latusaki** [comment] 2016-07-18 10:55
@sahrens had to add +        android:windowSoftInputMode="adjustPan" on AndroidManifest for KeyboardAvoidingView to work properly on Android. Without it, it would bug after app going to inactive state (when pressing android multitask button)

**Comment by DeDuckProject** [comment] 2016-09-21 13:04
+1

**Comment by knguyen2708** [comment] 2016-11-17 05:20
+1

**Comment by yonkshi** [comment] 2016-11-17 20:24
+1

**Comment by dcosson** [comment] 2016-11-17 22:01
So it sounds like Facebook internally has this and it's called `DockingScrollView`? Is it possible to verify if that is true and get a decision/milestone if and when it can be open sourced?

This is a pretty important feature IMO, and the issue is approaching 2 years old. As far as I know a huge category of things involving keyboard input are impossible to build and make feel native in iOS without `inputAccessoryView`, including a basic chat or messages view, the done button on a number pad, previous & next buttons for navigating between form fields, etc. So I imagine this is a pretty big blocker for lots of apps to use React Native.

**Comment by nazywamsiepawel** [comment] 2016-11-17 22:06
> So I imagine this is a pretty big blocker for a lot of apps that might want to use React Native.

In my case, it was a blocker big enough to come switch back to Swift. For anybody looking for a solid solution I recommend having a look at [https://github.com/slackhq/SlackTextViewController](url)

**Comment by logancarmody** [comment] 2016-11-19 19:17
+1

**Comment by zkrige** [comment] 2016-11-23 06:47
+1

**Comment by jgkim** [comment] 2016-12-06 15:01
+1

**Comment by kumarpatel** [comment] 2016-12-06 15:04
Same issue here. No return key to close onscreen numeric keyboard in iOS

**Comment by nezaidu** [comment] 2016-12-06 15:04
+1

**Comment by appscaptain** [comment] 2016-12-07 11:09
Yeah, the biggest issue in React Native IMHO. It really gives a bad user experience, when working with text-field heavy apps.

**Comment by chih** [comment] 2016-12-18 15:30
I wasn't satisfied with the other solutions presented (jerky or unsynced animations, etc), so I just ended up just creating a modified version of react native with a showDoneButton attribute added to TextInput.

Basically, in RCTTextFieldManager.m, I added...
```
RCT_CUSTOM_VIEW_PROPERTY(showDoneButton, BOOL, RCTTextField)
{
  if (json && ([RCTConvert BOOL:json])) {
    UIToolbar* toolbar = [[UIToolbar alloc] init];
    [toolbar sizeToFit];
    UIBarButtonItem* flex = [[UIBarButtonItem alloc]
                             initWithBarButtonSystemItem:UIBarButtonSystemItemFlexibleSpace
                             target:nil action:nil];
    UIBarButtonItem* doneButton = [[UIBarButtonItem alloc]
                                   initWithBarButtonSystemItem:UIBarButtonSystemItemDone
                                   target:view action:@selector(endEditing:)];
    toolbar.items = @[flex, doneButton];
    view.inputAccessoryView = toolbar;
  } else {
    view.inputAccessoryView = nil;
  }
}
```

And then I can do         
`<TextInput keyboardType={'numeric'} showDoneButton={true}

And get a native inputAccessoryView with the keyboard showing a Done button

I won't bother with a pull request since it seems like a more generic solution is in the works, but this might help those who can't wait for a fully generic solution and just need a Done button above a number pad (like I do)

**Comment by evollu** [comment] 2016-12-18 20:06
I'm using `react-native-textinput-utils` which provides 2 buttons for accessory as a temporary solution

**Comment by MattyK14** [comment] 2016-12-19 21:27
@chih good stuff! Any way to change the colour to match the dark style keyboard? aka `keyboardAppearance="dark`

**Comment by chih** [comment] 2016-12-19 22:14
@MattyK14 You can just do       

toolbar.barStyle = UIBarStyleBlack; 

right below

    UIToolbar* toolbar = [[UIToolbar alloc] init];

to get a dark toolbar.  A better solution, of course, would be to do that based on reading the value of a prop

**Comment by aprct** [comment] 2016-12-27 17:22
+1

**Comment by chumster** [comment] 2017-01-05 09:29
+1

**Comment by milkers** [comment] 2017-01-05 19:53
+1

**Comment by avogel3** [comment] 2017-01-09 16:39
+1

**Comment by xicovarisco** [comment] 2017-01-09 23:58
+1

**Comment by fdecampredon** [comment] 2017-01-13 18:23
I ended up with this 'hackish' implementation: https://gist.github.com/fdecampredon/a94f47170a2921ac422ebca49eb3817a

You can use it like this (at your own risk): 

```javascript
class Component {

   getTextInputRef = () => this.refs.textInput,
    
   renderInputAccessoryView = () => {
     return <View>...</View>
   }

   render() {
     return (
       <FormScrollView>
         <TextInput ref="textInput" />
         <InputAccessoryView 
           render={this.renderInputAccessoryView}
           getTextInputRef={this.getTextInputRef}
           height={40} 
         />
       </FormScrollView>
     );
   }
}
```

**Comment by henrikra** [comment] 2017-01-19 08:49
@chih Is your solution already in RN core? or do you have info that they are doing something to this?

**Comment by danleveille** [comment] 2017-01-20 05:02
Here's the Product Pains link -- feel free to upvote: https://productpains.com/post/react-native/make-ios-uitextviewinputaccessoryview-on-textinput

(The previous link in this thread is broken.)

**Comment by stief510** [comment] 2017-01-26 16:22
+1

**Comment by artald** [comment] 2017-01-31 23:29
If anyone’s interested, you can try using a component I wrote a while back called [react-native-keyboard-tracking-view](https://github.com/wix/react-native-keyboard-tracking-view).

Although it's not an actual `inputAccessoryView`, it behaves pretty much the same and allows you to have a view that “sticks” to the keyboard. Useful in case you need a text input or a toolbar that moves along with the keyboard.

**Comment by ericvicenti** [comment] 2017-03-06 07:39
Lets keep track of this feature request on canny: https://react-native.canny.io/feature-requests/p/make-ios-uitextviewinputaccessoryview-on-textinput

**Comment by twvdb** [comment] 2017-03-31 08:47
+1

**Comment by simistern** [comment] 2017-09-06 15:59
+1

**Comment by ahmadmuhsink** [comment] 2017-09-19 06:54
+1

**Comment by douglasjunior** [comment] 2017-10-04 13:03
Any news on this?

Until version 0.46.4 was possible to access the `inputAcessoryView` and customize the keyboard toolbar externally. And I created a [library](https://github.com/douglasjunior/react-native-keyboard-manager/) that does it very well. But, after [this commit](https://github.com/facebook/react-native/commit/2b1795c5add2e1442878a884d6dcd8f0ec5c1572) that was released in version 0.47.0, access the `inputAcessoryView` is impossible.

We are discussing this on https://github.com/douglasjunior/react-native-keyboard-manager/issues/3 and https://github.com/facebook/react-native/issues/16071, but it seems that there is no interest on the part of the RN team.

**Comment by iworkinprogress** [comment] 2017-11-21 20:47
+1

**Comment by luco** [comment] 2018-01-03 13:36
+1 on this.

**Comment by jnrepo** [comment] 2018-01-09 18:50
why is this closed, there is no functionality for this on RN?

**Comment by jpudysz** [comment] 2018-01-30 09:26
+1

**Comment by hery** [comment] 2018-02-13 17:53
One solution is to use a native UI component using [this guide](https://facebook.github.io/react-native/docs/native-components-ios.html) :)

I'll see if I can share some code or open source something.

**Comment by EmilScherdin** [comment] 2018-02-14 08:43
This works for getting that nice swipe to close with the keyboard (`keyboardDismissMode =interactive`) from what I've tested. Seems to work well with a lot of other things as well.

https://github.com/wix/react-native-keyboard-input

**Comment by sahrens** [comment] 2018-02-14 14:51
@PeteTheHeat is going to have an RN Core solution on iOS pretty soon!

**Comment by hery** [comment] 2018-02-23 18:57
Hello! Thanks @sahrens! Any idea how soon?

I've solved this by implementing a native textfield component and adding that functionality, but now I need to do that for a textarea as well so I'm wondering if I should just wait for a React Native solution.

Thanks!

**Comment by PeteTheHeat** [comment] 2018-03-02 22:50
I built this https://github.com/facebook/react-native/commit/38197c8230657d567170cdaf8ff4bbb4aee732b8 and added an example here https://github.com/facebook/react-native/commit/84ef7bc372ad870127b3e1fb8c13399fe09ecd4d

**Closed by PeteTheHeat** 2018-03-02 22:50 UTC
Labels: Ran Commands

**Comment by PeteTheHeat** [comment] 2018-04-06 01:07
@loxtank yup https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#055. I'm still fixing some things with it. Feel free to open any issues you find.

**Comment by Ashoat** [comment] 2018-07-11 17:35
@PeteTheHeat thanks so much for working on this!

There are several serious issues with the implementation as it stands:

1. #18997, doesn't work with multiline inputs.
2. Doesn't work with a tab bar, ie. no way to customize bottom padding when keyboard is collapsed.
3. #18987, impossible to close YellowBox warnings when `InputAccessoryView` is active.

Knowing FB culture around code ownership, I imagine you've probably moved on to something else. But if you have any spare cycles at all, would appreciate you looking into some of these issues. Any pointers on how to address them would be appreciated as well.

**Comment by LevelUp8** [comment] 2019-12-08 15:26
I also think this issue is relevant:

[#27440 ](https://github.com/facebook/react-native/issues/27440) -> React native IOS InputAccessoryView disappear from the screen after close modal.

 Any help will be appreciated.
