### ISSUE TITLE
[iOS] LayoutAnimation does not animate Text

### ISSUE THREAD

**Issue by bolismauro** [facebook/react-native#6502] opened 2016-03-17 11:27 UTC
Hello,
I'm creating a component that should animate the position of a `Text` element.
It seems that LayoutAnimation does not animate the Text frame unless it is wrapped in a `View` element.

I'm using absolute positioning together with top and left attributes in the CSS

**Comment by brentvatne** [comment] 2016-03-20 19:09
@nicklockwood - known issue? If so, I can document this limitation.

**Comment by nicklockwood** [comment] 2016-03-21 13:48
@brentvatne I believe it's deliberate. Animating text looks pretty weird, so we disabled it.

(The technical reason is that text doesn't animate like you'd expect, with the text re-wrapping each frame - instead, because text is rendered as an image internally, what happens is that the rendered text image is stretched to fit the new frame, and then immediately wraps to the new layout after the animation completes.)

**Comment by nicklockwood** [comment] 2016-03-21 13:49
I guess we might be able to animate the *position* of the frame, but not its size. I don't know if that would work any better in practice though.

**Comment by bolismauro** [comment] 2016-03-21 14:14
> because text is rendered as an image internally
Is this something RN or iOS side? (I know that UILabels are backed by textures)

Just to give some context, I'm running some experiments to understand how RN fits some pieces of UI we have and I also tried to animate a Text component. More specifically I tried to animate the position, not the size, which may make sense sometimes.

As far as I can see there are three ways to handle this:
- document the behaviour
- RN triggers a warning in dev mode, so the Text doesn't animate but developers know the reason
- RN animates the position but not the size (probably either point 1 or 2 is still needed in this case though)

**Comment by nicklockwood** [comment] 2016-03-21 14:23
>Is this something RN or iOS side? (I know that UILabels are backed by textures)

It's just the way iOS does it. Drawing text is expensive, and is done mostly on the CPU not the GPU, so it's not something that can easily be done in real time, which is why iOS does it by pre-drawing the text into a texture. We could try to force it to redraw the text every frame when animating, but the performance would probably be horrible.

**Comment by bolismauro** [comment] 2016-03-21 14:33
Most likely yes. 
Moreover I think that no one will ever animate the size of a label. Changing the position, instead, can be useful (even if not really common).

The only thing is that it may be weird that `LayoutAnimation` behaves differently for different components. If not specified in the documentation (or maybe using a warning), someone may think that there is something broken in his code (as I did). I only discovered that by looking at an example I found online and by checking and testing differences between this example and my code

**Comment by ericmasiello** [comment] 2016-04-20 02:03
I agree with the above. I just ran into the same issue trying to animate Text. layout animation could use some more documentation

**Comment by lacker** [comment] 2016-10-21 02:01
We updated a bunch of docs including Animated. Since this is "working as intended" and just a docs thing I'm going to close this issue, feel free to reopen if you have a specific complaint about the new animation docs though.

**Closed by lacker** 2016-10-21 02:01 UTC

**Comment by ericapply** [comment] 2017-03-22 17:49
I would like to have LayoutAnimation work with iOS text. If the performance is a problem maybe enable it with a flag.

**Comment by jslz** [comment] 2018-05-16 19:40
"Moreover I think that no one will ever animate the size of a label" 

Hm, I think that's actually what I was trying to do yesterday! :-) Worked OK in iOS but the text was clipped on Android going from a smaller text word to a longer one.
