### ISSUE TITLE
react-native v0.44.0 After the software is loaded, it has been white screen

### ISSUE THREAD

**Issue by holleword** [facebook/react-native#14187] opened 2017-05-25 09:41 UTC
After the software is loaded, it has been white screen

**Comment by AlanFoster** [comment] 2017-05-25 12:01
@holleword There's information missing from this ticket; What are the steps to reproduce?

**Comment by hramos** [comment] 2017-05-25 19:57
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-05-25 19:57 UTC
