### ISSUE TITLE
react-native 0.56 on Windows = SyntaxError: Unexpected token import 

### ISSUE THREAD

**Issue by victorhugoweb** [facebook/react-native#20072] opened 2018-07-06 11:39 UTC
# Environment
 react-native info
AwesomeProject\node_modules\react-native\local-cli\cliEntry.js:30
import type {CommandT} from './commands';
^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Module._compile (C:\Users\cweb\AwesomeProject\node_modules\pirates\lib\index.js:91:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (C:\Users\cweb\AwesomeProject\node_modules\pirates\lib\index.js:96:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)

## Description

![capturar](https://user-images.githubusercontent.com/29238083/42377054-04f8b166-80f8-11e8-843d-8b31bdfa2b40.PNG)

## Reproducible Demo
install react-native 0.56 on Windows

**Comment by Hunsu** [comment] 2018-07-06 11:50
It is a known issue https://github.com/facebook/react-native/issues/20015

**Comment by charpeni** [comment] 2018-07-06 12:39
Thank you for reporting this issue, we are aware of the situation, and we are working on this.

Duplicate of #20015, let's close this one.

**Closed by charpeni** 2018-07-06 12:39 UTC
Labels: :clipboard:No Environment Info

**Comment by a-eid** [comment] 2018-07-09 11:15
@chadbay  what can I do meanwhile to avoid this error?

**Comment by JeysonGustavo** [comment] 2018-07-09 22:16
Hey guys, I had this problem too and I installed the react-native with older version with the following command:
react-native init --version="0.44.0" app_name

You can substitute the version 0.44.0 for another version, but I don't tested it yet.
This works for me, I hope its help you.

**Comment by HemantSharmaVB** [comment] 2018-07-10 06:40
I also faced this issue and search for this issue then I found this error is coming from backend issue is new React-Native Version you have to wait for the new version or downgrade your react-native Version to work

http://qna.vbagetech.com/question/331/SyntaxError-Unexpected-token-import-in-React-Native

**Comment by charpeni** [comment] 2018-07-10 12:13
This issue is a duplicate, please refer to https://github.com/facebook/react-native/issues/20015.
