### ISSUE TITLE
[WebSocket] Look into whether state == OPEN check should go into _closeWebSocket

### ISSUE THREAD

**Issue by ide** [facebook/react-native#3364] opened 2015-10-12 18:15 UTC
See https://github.com/facebook/react-native/pull/3347.

**Comment by satya164** [comment] 2015-10-26 11:03
Also, I've been using this for quite a while, and though rare, I get runtime exceptions  due to trying to close already closed socket connections. - https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/modules/websocket/WebSocketModule.java#L152

Though I understand that it's a programmer error, on the web, it doesn't throw any error even if I try to close a connection multiple times. And I think we should mirror the same.

@mkonicek @ide Thoughts on this?

**Comment by mkonicek** [comment] 2015-10-26 22:53
Yes, moving the check to `_closeWebSocket` sounds good to me.

@satya164 Why does your code try to close the same socket multiple times? I'm fine if you change this to log instead of throwing if that's the web behavior.

**Comment by satya164** [comment] 2015-10-27 05:13
@mkonicek I'm using engine.io, so not something in my control I think.

Thanks. I'll send a pull request.

**Comment by ide** [comment] 2015-10-27 05:16
Also, if we can make the native layer robust against crashes I think we should do that too. Redboxes on Android are especially painful because they destroy the Catalyst instance.

**Comment by satya164** [comment] 2015-10-27 07:30
@ide We have another place where we're throwing a runtime exception - https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/modules/websocket/WebSocketModule.java#L153

There is already a check in https://github.com/facebook/react-native/blob/master/Libraries/WebSocket/WebSocketBase.js#L64 though, which will throw an error on JavaScript side.

**Comment by puf** [comment] 2015-11-13 01:44
Using Firebase it is a simple to reproduce this bug:
```
var Firebase = require('firebase');
var React = require('react-native');
var {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  TextInput,
  TouchableHighlight,
} = React;

var AwesomeProject = React.createClass({
  getInitialState: function() {
    return {
      items: []
    };
  },
  componentWillMount: function() {
    this.ref = new Firebase('https://<yourapp>.firebaseio.com/');
    this.ref.on('value', function(snapshot) {
      var items = [];
      snapshot.forEach(function(child) {
        items.push(child.val());
      });
      this.setState({ 'items': items });
    }.bind(this));
  },
```
The Firebase server performs a so-called reset when the client initially connects, redirecting it to the correct server. In this scenario the server closes the socket, after which the Firebase client also closes the socket and thus causes the RuntimeException. [The PR](https://github.com/facebook/react-native/pull/3347) perfectly fixes the problem.

**Comment by satya164** [comment] 2015-11-13 03:19
This issue should be closed.

**Comment by puf** [comment] 2015-11-13 03:43
I installed the latest release of React Native today and the problem still exists there. It would help if you specify based on what it should be closed ([this commit](https://github.com/skillz/react-native/commit/d4103310700a59f539cc1039c0273173dac10811) perhaps?)

**Comment by satya164** [comment] 2015-11-13 07:57
@puf This issue should not happen any more with master or the latest RC.

**Comment by satya164** [comment] 2015-11-13 07:59
cc @ide

**Comment by mkonicek** [comment] 2015-11-13 14:59
https://github.com/skillz/react-native/commit/d4103310700a59f539cc1039c0273173dac10811 Will go out in 0.15 end of next week, thanks for doing that @satya164! Will close this issue.

**Closed by mkonicek** 2015-11-13 14:59 UTC
