### ISSUE TITLE
```react-native run-ios --configuration Release``` - does not work

### ISSUE THREAD

**Issue by GeoffreyPlitt** [facebook/react-native#16194] opened 2017-10-03 23:38 UTC
RN=0.48

I run ```react-native run-ios --configuration Release``` and it loads on IOS phone, but in Debug mode (shake shows menu)

**Comment by hramos** [comment] 2017-10-05 02:17
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue that meets the requirements set forth in the template. Thanks!

**Closed by hramos** 2017-10-05 02:17 UTC
