### ISSUE TITLE
Can't turn off developer mode

### ISSUE THREAD

**Issue by flipstewart** [facebook/react-native#1054] opened 2015-04-28 21:55 UTC
I'm curling with the provided command, `curl 'http://localhost:8081/index.ios.bundle?dev=false&minify=true' -o iOS/main.jsbundle`, but when I shake any device the app is on, the developer menu pops up!

What am I missing?

**Comment by tadeuzagallo** [comment] 2015-04-28 22:36
The developer mode is because you're building your app in debug mode. You can edit your scheme on Xcode and build it for release instead. Also since 8e15a0d5e716ca63d0610e4b947ff2ab784e3ca2 you can:

```objc
#define RCT_DEV 0
// You can also remove redbox errors with
#define RCT_DEBUG 0
```

**Comment by flipstewart** [comment] 2015-04-29 18:12
@tadeuzagallo fantastic!

While this solves my immediate issue, is this present in documentation? Should it be added to [this guide](https://facebook.github.io/react-native/docs/runningondevice.html)? I assumed that turning off dev in the manner described therein would also apply to this.

**Comment by brentvatne** [comment] 2015-04-29 19:03
@flipstewart - makes sense, can you submit a PR?

**Comment by flipstewart** [comment] 2015-04-29 19:57
@brentvatne happy to!

imho both the runningondevice and debugging sections could use a bit more information on how the dev modes work.

Perhaps the content could go in the debugging docs and the runningondevice docs could link there?

**Comment by brentvatne** [comment] 2015-04-29 20:13
@flipstewart - seems reasonable to me, let's see how that looks when it's in place!

**Comment by flipstewart** [comment] 2015-04-30 00:48
@tadeuzagallo hey! So I'm no iOS development pro... where would be the best spot to put `#define RCT_DEV 0`?

**Comment by nicklockwood** [comment] 2015-04-30 14:17
You can either change the value in RCTDefines.h, or in the build settings for the React lib project, search for "Preprocessor Macros" and add RCT_DEV=0 to the section where DEBUG=1 is currently defined.

**Comment by flipstewart** [comment] 2015-04-30 16:02
I feel like there has to be a better way to turn off the debugger than by altering a dependency.

Is there another option for building without the developer menu? @tadeuzagallo mentioned that I was building in debug mode; how do I not build in debug mode?

(PR is incoming, I just want to make sure I have things right)

**Comment by tadeuzagallo** [comment] 2015-04-30 16:12
You can change your scheme on Xcode, change build configuration of Run to Release instead of Debug

**Comment by flipstewart** [comment] 2015-04-30 16:15
Aha! I didn't know that menu even existed... great, I'll have the PR open shortly.

**Comment by nicklockwood** [comment] 2015-04-30 17:32
The fact that the developer menu stays active in release mode was a bug that has now been fixed on our internal build. That should make it into the next OSS release. Sorry for any inconvenience.

**Comment by opolyo01** [comment] 2015-05-10 01:29
I ran my code in the release mode, but still getting development popup when I shake the phone.

![screen shot 2015-05-09 at 6 25 01 pm](https://cloud.githubusercontent.com/assets/558296/7552700/30677a7e-f679-11e4-91ea-7e2235246ae4.png)
![screen shot 2015-05-09 at 6 05 43 pm](https://cloud.githubusercontent.com/assets/558296/7552701/3eac902e-f679-11e4-8273-bebdf918f107.png)
![devpopup](https://cloud.githubusercontent.com/assets/558296/7552702/5adec32a-f679-11e4-9d09-42b3b25c08ab.PNG)

**Comment by ide** [comment] 2015-05-10 02:02
@opolyo01 two things to check - are you using the latest version of react? and what does this print for you? `NSLog(DEBUG ? @"DEBUG" : @"RELEASE");` (or maybe it doesn't compile because DEBUG is undefined depending on your settings)

**Comment by opolyo01** [comment] 2015-05-10 21:40
Yes Debug is undefined when I run in release mode.  It is displaying DEBUG in debug mode.
I tried adding  in AppDelegate.m 

NSLog(DEBUG ? @"DEBUG" : @"RELEASE");
/Users/opolyakov/react-projects/reactNativeProjects/openHouse/iOS/AppDelegate.m:51:11: Use of undeclared identifier 'DEBUG'

Where do I define this setting?

**Comment by nicklockwood** [comment] 2015-05-10 22:42
@opolyo01 are you using version 0.4.2? I believe 0.4.1 had a bug that would explain this, but it's fixed in 0.4.2.

You can manually disable the dev menu by changing the value of RCT_DEV to 0 in RCTDefines.h, but that should be the default value in release mode anyway unless something is wrong.

**Comment by opolyo01** [comment] 2015-05-11 04:47
Thanks,  moving to 0.4.2 fixed the development popup issue.

**Closed** 2015-05-11 06:52 UTC

**Comment by Creemli** [comment] 2016-03-31 03:06
@ide   I noticed that the developer menu is global: if React view has been loaded successfully, it will show whatever page when I shake the phone. Could we change the mode that it displays only when we are in React view？

**Comment by ide** [comment] 2016-03-31 03:22
@Creemli I don't think we'd want to do that automatically ("when we are in React view" is up to you to determine) but we should probably offer a way to toggle the dev menu programmatically via the bridge if that's not provided.

**Comment by Creemli** [comment] 2016-03-31 03:29
@ide   Yeah， I have tried the way above, it's ok. Actually the problem is (I am integrating React with existing App) that the developer menu stops the shake event and the other shake functionality will not be fired. I wonder whether we can improve this situation?

**Comment by Rizwanilahi** [comment] 2018-01-10 14:15
I can't off Developer menu in production build on Android. Developer Menu is showing on shake in productions(Release Build).
