### ISSUE TITLE
jsSchedulingOverhead (-10ms) should be positive YellowBox.js:57 jsSchedulingOverhead (-19ms) should be positive

### ISSUE THREAD

**Issue by nowaits** [facebook/react-native#5136] opened 2016-01-06 04:13 UTC
problem on master
jsSchedulingOverhead (-10ms) should be positive YellowBox.js:57 jsSchedulingOverhead (-19ms) should be positive

**Comment by corbt** [comment] 2016-02-03 11:37
Closing, this is a duplicate of #1598.

**Closed by corbt** 2016-02-03 11:37 UTC
