### ISSUE TITLE
【iOS】setInterval/setTimeout causes the app to crash, May be the problem with RCTTiming.m

### ISSUE THREAD

**Issue by bashen1** [facebook/react-native#26995] opened 2019-10-25 02:25 UTC
React Native version:
System:
    OS: macOS 10.15
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 63.55 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 25.0.2, 27.0.3, 28.0.3, 29.0.1, 29.0.2
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce

1. react-native init demo
2. modify demo/App.js

```javascript
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow
 */

import React, {PureComponent} from 'react';
import {
    SafeAreaView,
    ScrollView,
    View,
    Text,
    StatusBar,
} from 'react-native';

class App extends PureComponent {
    constructor(props) {
        super(props);
        this.state = {
            num: 0
        }
    }

    componentDidMount(): * {
        this.timer = setInterval(() => {
            this.setState({
                num: this.state.num + 1
            })
        }, 1000)
    }

    render(): boolean | number | string | React$Element<*> | React$Portal | Iterable | null {
        return (
            <>
                <StatusBar barStyle="dark-content"/>
                <SafeAreaView>
                    <ScrollView
                        contentInsetAdjustmentBehavior="automatic"
                       >
                      <View>
                        <Text>{this.state.num}</Text>
                      </View>
                    </ScrollView>
                </SafeAreaView>
            </>
        )
    }
}

export default App;
```
3. Keep the application foreground(background). Device lock screen, then unlock for a few minutes, app crash，sometimes will show redscreen「Timed out waiting for modules to be invalidated」

LOG
```
Process exited: <FBApplicationProcess: 0x11d5fb5f0; application<org.reactjs.native.example.demo>:16512> -> <RBSProcessExitContext; specific: <RBSProcessExitStatus; domain: runningboard (15); code: 0x2182baad>; terminationContext: <RBSTerminateContext: 0x280ee4840; code: 0x2182BAAD; explanation: "Timed-out waiting for process [application<org.reactjs.native.example.demo>:16512] to invalidate assertion with identifier 26-16512-127410 and explanation 'Shared Background Assertion 2 for org.reactjs.native.example.demo'. Direct this report to owners of that process"; reportType: 0; maxRole: 7; maxTerminationResistance: 3>>
```

**Comment by mmahdigh** [comment] 2019-10-27 13:42
I can't reproduce this issue. 
Could you give us more details? like on what device you run your app on (emulator or physical)?

**Comment by bashen1** [comment] 2019-10-28 01:14
@mmahdigh 

``Info``
Phone: iPhone 7 128GB(Physical)
OS: iOS 13.1.2

``Setps``
1.  react-native init demo
2. modify demo/App.js just like 
```javascript
import React, {PureComponent} from 'react';
import {
    SafeAreaView,
    ScrollView,
    View,
    Text,
    StatusBar,
} from 'react-native';

class App extends PureComponent {
    constructor(props) {
        super(props);
        this.state = {
            num: 0
        }
    }

    componentDidMount(): * {
        this.timer = setInterval(() => {
            this.setState({
                num: this.state.num + 1
            })
        }, 1000)
    }

    render(): boolean | number | string | React$Element<*> | React$Portal | Iterable | null {
        return (
            <>
                <StatusBar barStyle="dark-content"/>
                <SafeAreaView>
                    <ScrollView
                        contentInsetAdjustmentBehavior="automatic"
                       >
                      <View>
                        <Text>{this.state.num}</Text>
                      </View>
                    </ScrollView>
                </SafeAreaView>
            </>
        )
    }
}

export default App;
```
3. run debug/release on the physical device
4. app background with the device not lockscreen OR foreground with the device lockscreen
5. wait just about one minutes or more, app crash

> Android is OK

**Comment by radko93** [comment] 2019-10-31 11:40
Duplicate of #26696

**Closed by radko93** 2019-10-31 11:40 UTC
Labels: Bug
