### ISSUE TITLE
Got Undefined NativeModules

### ISSUE THREAD

**Issue by kfir91** [facebook/react-native#11046] opened 2016-11-21 15:18 UTC
Hello i installed react-native-country-picker
and when i run it i got error: undefined is not an object NativeModules.CountryPicker.show
i did
 react-native upgrade
and
rnpm link
(after the plugin install)
and same error...

**Comment by ericvicenti** [comment] 2016-11-21 15:41
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but we can reopen if additional information is provided. Thanks!

**Closed by ericvicenti** 2016-11-21 15:41 UTC

**Comment by kfir91** [comment] 2016-11-21 15:53
what ? i explained everything ...
again:
Description:
i did to  install react-native-country-picker 
i use this:
`npm install react-native-country-picker --save`
after that i doing this in my code:
`var CountryPicker = require('react-native-country-picker');`

and i got error:
`undefined is not an object NativeModules.CountryPicker.show`

in line:
`NativeModules.CountryPicker.show(callBack);`

i see solotions but nothing helped me:
the solution that i tried:
`react-native upgrade`
`rnpm link`

tnx

**Comment by ericvicenti** [comment] 2016-11-21 16:31
These are the questions I had:

- Are you sure the bug is not within `react-native-country-picker`? Maybe the issue should be posted there. (I am pretty sure this is the problem, because `NativeModules` has moved.)
- How can somebody else see the same issue? Can you post a basic app that shows this issue?
- What platform are you running on, iOS or Android?
- Are you on windows, mac, or linux?
- What version of RN did you start on?
- Are there any warnings or error screens?

If you have all this information and you're still sure the problem is within react-native core, then feel free to open a new more detailed issue :-D

**Comment by kfir91** [comment] 2016-11-21 17:02
@ericvicenti 
hello tnx for your help,
for your questions:
1. I think that the bug not there because i tried react-native-search-bar too
and i got same error on the NativeModules...

2. No i cant post a basic app right now...
3. Android
4. Windows 7
5. The new one (i use react-native upgrade)
6. actually the error screen is what i said only red screen with this error...

**Comment by sanjibnarzary** [comment] 2016-11-21 17:12
@kfir91 
When you file a bug report use this template.


### Description

[FILL THIS OUT: Explain what you did, what you expected to happen, and what actually happens.]

### Reproduction

[FILL THIS OUT: Try to reproduce your bug on rnplay.org and provide a link. If you can't reproduce the bug on rnplay.org, provide a sample project.]

### Solution

[FILL THIS OUT: What needs to be done to address this issue? Ideally, provide a pull request with a fix.]

### Additional Information

* React Native version: [FILL THIS OUT]
* Platform: [FILL THIS OUT: iOS, Android, or both?]
* Operating System: [FILL THIS OUT: MacOS, Linux, or Windows?]

**Comment by kfir91** [comment] 2016-11-21 17:23
@sanjibnarzary 
i think that i explained good enough the problem without the template...
