### ISSUE TITLE
React native android build started to fail which was working previously

### ISSUE THREAD

**Issue by nkjs-git** [facebook/react-native#35334] opened 2022-11-14 09:47 UTC
### Description

My react-native android build started to fail suddenly when I tried to build my application to generate android app on 11-11-2022. I was previously able to build the android app from my react-native code both in local and azure DevOps pipeline. I'm unable to understand what went wrong.

The error is seen as below when I build android app using command cd android && ./gradlew assembleRelease:

Task :expo-modules-core:downloadBoost
Download https://github.com/react-native-community/boost-for-react-native/releases/download/v1.63.0-0/boost_1_63_0.tar.gz

Task :expo-modules-core:downloadDoubleConversion
Download https://github.com/google/double-conversion/archive/v1.1.6.tar.gz

Task :expo-modules-core:downloadFolly
Download https://github.com/facebook/folly/archive/v2021.06.28.00.tar.gz

Task :expo-modules-core:configureCMakeRelWithDebInfo
C/C++: prefabcom.google.prefab.api.NoMatchingLibraryException: No compatible library found for //fbjni/fbjni. Rejected the following libraries:
C/C++: prefabandroid.arm64-v8a: User is targeting armeabi-v7a but library is for arm64-v8a
C/C++: prefabandroid.armeabi-v7a: User is using a static STL but library requires a shared STL
C/C++: prefabandroid.x86: User is targeting armeabi-v7a but library is for x86
C/C++: prefabandroid.x86_64: User is targeting armeabi-v7a but library is for x86_64
C/C++: prefabcom.google.prefab.api.NoMatchingLibraryException: No compatible library found for //fbjni/fbjni. Rejected the following libraries:
C/C++: prefabandroid.arm64-v8a: User is using a static STL but library requires a shared STL
C/C++: prefabandroid.armeabi-v7a: User is targeting arm64-v8a but library is for armeabi-v7a
C/C++: prefabandroid.x86: User is targeting arm64-v8a but library is for x86
C/C++: prefabandroid.x86_64: User is targeting arm64-v8a but library is for x86_64
C/C++: prefabcom.google.prefab.api.NoMatchingLibraryException: No compatible library found for //fbjni/fbjni. Rejected the following libraries:
C/C++: prefabandroid.arm64-v8a: User is targeting x86 but library is for arm64-v8a
C/C++: prefabandroid.armeabi-v7a: User is targeting x86 but library is for armeabi-v7a
C/C++: prefabandroid.x86: User is using a static STL but library requires a shared STL
C/C++: prefabandroid.x86_64: User is targeting x86 but library is for x86_64
C/C++: prefabcom.google.prefab.api.NoMatchingLibraryException: No compatible library found for //fbjni/fbjni. Rejected the following libraries:
C/C++: prefabandroid.arm64-v8a: User is targeting x86_64 but library is for arm64-v8a
C/C++: prefabandroid.armeabi-v7a: User is targeting x86_64 but library is for armeabi-v7a
C/C++: prefabandroid.x86: User is targeting x86_64 but library is for x86
C/C++: prefabandroid.x86_64: User is using a static STL but library requires a shared STL

Task :expo-modules-core:buildCMakeRelWithDebInfo
C/C++: ninja: Entering directory `/node_modules/expo-modules-core/android/.cxx/RelWithDebInfo/3k1n4b3g/armeabi-v7a'
C/C++: In file included from ../../../../src/main/cpp/JavaScriptModuleObject.cpp:3:
C/C++: ../../../../src/main/cpp/JavaScriptModuleObject.h:7:10: fatal error: 'react/bridging/LongLivedObject.h' file not found
C/C++: In file included from ../../../../src/main/cpp/ExpoModulesHostObject.cpp:3:
C/C++: In file included from ../../../../src/main/cpp/ExpoModulesHostObject.h:5:
C/C++: In file included from ../../../../src/main/cpp/JSIInteropModuleRegistry.h:6:
C/C++: ../../../../src/main/cpp/JavaScriptModuleObject.h:7:10: fatal error: 'react/bridging/LongLivedObject.h' file not found
C/C++: In file included from ../../../../src/main/cpp/JNIInjector.cpp:3:
C/C++: In file included from ../../../../src/main/cpp/JSIInteropModuleRegistry.h:6:
C/C++: ../../../../src/main/cpp/JavaScriptModuleObject.h:7:10: fatal error: 'react/bridging/LongLivedObject.h' file not found
C/C++: In file included from ../../../../src/main/cpp/JSIInteropModuleRegistry.cpp:3:
C/C++: In file included from ../../../../src/main/cpp/JSIInteropModuleRegistry.h:6:
C/C++: ../../../../src/main/cpp/JavaScriptModuleObject.h:7:10: fatal error: 'react/bridging/LongLivedObject.h' file not found
C/C++: In file included from ../../../../src/main/cpp/MethodMetadata.cpp:1:
C/C++: ../../../../src/main/cpp/MethodMetadata.h:8:10: fatal error: 'react/bridging/LongLivedObject.h' file not found

Task :expo-modules-core:buildCMakeRelWithDebInfo FAILED
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':expo-modules-core:buildCMakeRelWithDebInfo'.
Build command failed.
Error while executing process /Users/ee211312/Library/Android/sdk/cmake/3.10.2.4988404/bin/ninja with arguments {-C /node_modules/expo-modules-core/android/.cxx/RelWithDebInfo/3k1n4b3g/armeabi-v7a expo-modules-core}
ninja: Entering directory `/node_modules/expo-modules-core/android/.cxx/RelWithDebInfo/3k1n4b3g/armeabi-v7a'
[1/12] Building CXX object CMakeFiles/expo-modules-core.dir/src/main/cpp/Exceptions.cpp.o
[2/12] Building CXX object CMakeFiles/expo-modules-core.dir/src/main/cpp/JavaScriptModuleObject.cpp.o
FAILED: CMakeFiles/expo-modules-core.dir/src/main/cpp/JavaScriptModuleObject.cpp.o
/Users/ee211312/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ --target=armv7-none-linux-androideabi21 --gcc-toolchain=/Users/ee211312/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64 --sysroot=/Users/ee211312/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/sysroot -Dexpo_modules_core_EXPORTS -I/node_modules/react-native/React -I/node_modules/react-native/React/Base -I/node_modules/react-native/ReactAndroid/src/main/jni -I/node_modules/react-native/ReactAndroid/src/main/jni/react -I/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/turbomodule/core/jni -I/node_modules/react-native/ReactCommon -I/node_modules/react-native/ReactCommon/react/nativemodule/core -I/node_modules/react-native/ReactCommon/callinvoker -I/node_modules/react-native/ReactCommon/jsi -I../../../../build/third-party-ndk/boost/boost_1_63_0 -I../../../../build/third-party-ndk/double-conversion -I../../../../build/third-party-ndk/folly -I../../../../build/fbjni-0.2.2-headers.jar -I../../../../ -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security -O2 -g -DNDEBUG -fPIC -DFOLLY_NO_CONFIG=1 -DFOLLY_HAVE_CLOCK_GETTIME=1 -DFOLLY_HAVE_MEMRCHR=1 -DFOLLY_USE_LIBCPP=1 -DFOLLY_MOBILE=1 -DUSE_HERMES=0 -DUNIT_TEST=0 -O2 -frtti -fexceptions -Wall -fstack-protector-all -std=gnu++1z -MD -MT CMakeFiles/expo-modules-core.dir/src/main/cpp/JavaScriptModuleObject.cpp.o -MF CMakeFiles/expo-modules-core.dir/src/main/cpp/JavaScriptModuleObject.cpp.o.d -o CMakeFiles/expo-modules-core.dir/src/main/cpp/JavaScriptModuleObject.cpp.o -c ../../../../src/main/cpp/JavaScriptModuleObject.cpp
In file included from ../../../../src/main/cpp/JavaScriptModuleObject.cpp:3:
../../../../src/main/cpp/JavaScriptModuleObject.h:7:10: fatal error: 'react/bridging/LongLivedObject.h' file not found
#include <react/bridging/LongLivedObject.h>
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[3/12] Building CXX object CMakeFiles/expo-modules-core.dir/src/main/cpp/ExpoModulesHostObject.cpp.o
FAILED: CMakeFiles/expo-modules-core.dir/src/main/cpp/ExpoModulesHostObject.cpp.o
/Users/ee211312/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ --target=armv7-none-linux-androideabi21 --gcc-toolchain=/Users/ee211312/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64 --sysroot=/Users/ee211312/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/sysroot -Dexpo_modules_core_EXPORTS -I/node_modules/react-native/React -I/node_modules/react-native/React/Base -I/node_modules/react-native/ReactAndroid/src/main/jni -I/node_modules/react-native/ReactAndroid/src/main/jni/react -I/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/turbomodule/core/jni -I/node_modules/react-native/ReactCommon -I/node_modules/react-native/ReactCommon/react/nativemodule/core -I/node_modules/react-native/ReactCommon/callinvoker -I/node_modules/react-native/ReactCommon/jsi -I../../../../build/third-party-ndk/boost/boost_1_63_0 -I../../../../build/third-party-ndk/double-conversion -I../../../../build/third-party-ndk/folly -I../../../../build/fbjni-0.2.2-headers.jar -I../../../../ -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security -O2 -g -DNDEBUG -fPIC -DFOLLY_NO_CONFIG=1 -DFOLLY_HAVE_CLOCK_GETTIME=1 -DFOLLY_HAVE_MEMRCHR=1 -DFOLLY_USE_LIBCPP=1 -DFOLLY_MOBILE=1 -DUSE_HERMES=0 -DUNIT_TEST=0 -O2 -frtti -fexceptions -Wall -fstack-protector-all -std=gnu++1z -MD -MT CMakeFiles/expo-modules-core.dir/src/main/cpp/ExpoModulesHostObject.cpp.o -MF CMakeFiles/expo-modules-core.dir/src/main/cpp/ExpoModulesHostObject.cpp.o.d -o CMakeFiles/expo-modules-core.dir/src/main/cpp/ExpoModulesHostObject.cpp.o -c ../../../../src/main/cpp/ExpoModulesHostObject.cpp
In file included from ../../../../src/main/cpp/ExpoModulesHostObject.cpp:3:
In file included from ../../../../src/main/cpp/ExpoModulesHostObject.h:5:
In file included from ../../../../src/main/cpp/JSIInteropModuleRegistry.h:6:
../../../../src/main/cpp/JavaScriptModuleObject.h:7:10: fatal error: 'react/bridging/LongLivedObject.h' file not found
#include <react/bridging/LongLivedObject.h>
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[4/12] Building CXX object CMakeFiles/expo-modules-core.dir/src/main/cpp/JNIInjector.cpp.o
FAILED: CMakeFiles/expo-modules-core.dir/src/main/cpp/JNIInjector.cpp.o
/Users/ee211312/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ --target=armv7-none-linux-androideabi21 --gcc-toolchain=/Users/ee211312/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64 --sysroot=/Users/ee211312/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/sysroot -Dexpo_modules_core_EXPORTS -I/node_modules/react-native/React -I/node_modules/react-native/React/Base -I/node_modules/react-native/ReactAndroid/src/main/jni -I/node_modules/react-native/ReactAndroid/src/main/jni/react -I/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/turbomodule/core/jni -I/node_modules/react-native/ReactCommon -I/node_modules/react-native/ReactCommon/react/nativemodule/core -I/node_modules/react-native/ReactCommon/callinvoker -I/node_modules/react-native/ReactCommon/jsi -I../../../../build/third-party-ndk/boost/boost_1_63_0 -I../../../../build/third-party-ndk/double-conversion -I../../../../build/third-party-ndk/folly -I../../../../build/fbjni-0.2.2-headers.jar -I../../../../ -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security -O2 -g -DNDEBUG -fPIC -DFOLLY_NO_CONFIG=1 -DFOLLY_HAVE_CLOCK_GETTIME=1 -DFOLLY_HAVE_MEMRCHR=1 -DFOLLY_USE_LIBCPP=1 -DFOLLY_MOBILE=1 -DUSE_HERMES=0 -DUNIT_TEST=0 -O2 -frtti -fexceptions -Wall -fstack-protector-all -std=gnu++1z -MD -MT CMakeFiles/expo-modules-core.dir/src/main/cpp/JNIInjector.cpp.o -MF CMakeFiles/expo-modules-core.dir/src/main/cpp/JNIInjector.cpp.o.d -o CMakeFiles/expo-modules-core.dir/src/main/cpp/JNIInjector.cpp.o -c ../../../../src/main/cpp/JNIInjector.cpp
In file included from ../../../../src/main/cpp/JNIInjector.cpp:3:
In file included from ../../../../src/main/cpp/JSIInteropModuleRegistry.h:6:
../../../../src/main/cpp/JavaScriptModuleObject.h:7:10: fatal error: 'react/bridging/LongLivedObject.h' file not found
#include <react/bridging/LongLivedObject.h>
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[5/12] Building CXX object CMakeFiles/expo-modules-core.dir/src/main/cpp/JSIInteropModuleRegistry.cpp.o
FAILED: CMakeFiles/expo-modules-core.dir/src/main/cpp/JSIInteropModuleRegistry.cpp.o
/Users/ee211312/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ --target=armv7-none-linux-androideabi21 --gcc-toolchain=/Users/ee211312/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64 --sysroot=/Users/ee211312/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/sysroot -Dexpo_modules_core_EXPORTS -I/node_modules/react-native/React -I/node_modules/react-native/React/Base -I/node_modules/react-native/ReactAndroid/src/main/jni -I/node_modules/react-native/ReactAndroid/src/main/jni/react -I/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/turbomodule/core/jni -I/node_modules/react-native/ReactCommon -I/node_modules/react-native/ReactCommon/react/nativemodule/core -I/node_modules/react-native/ReactCommon/callinvoker -I/node_modules/react-native/ReactCommon/jsi -I../../../../build/third-party-ndk/boost/boost_1_63_0 -I../../../../build/third-party-ndk/double-conversion -I../../../../build/third-party-ndk/folly -I../../../../build/fbjni-0.2.2-headers.jar -I../../../../ -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security -O2 -g -DNDEBUG -fPIC -DFOLLY_NO_CONFIG=1 -DFOLLY_HAVE_CLOCK_GETTIME=1 -DFOLLY_HAVE_MEMRCHR=1 -DFOLLY_USE_LIBCPP=1 -DFOLLY_MOBILE=1 -DUSE_HERMES=0 -DUNIT_TEST=0 -O2 -frtti -fexceptions -Wall -fstack-protector-all -std=gnu++1z -MD -MT CMakeFiles/expo-modules-core.dir/src/main/cpp/JSIInteropModuleRegistry.cpp.o -MF CMakeFiles/expo-modules-core.dir/src/main/cpp/JSIInteropModuleRegistry.cpp.o.d -o CMakeFiles/expo-modules-core.dir/src/main/cpp/JSIInteropModuleRegistry.cpp.o -c ../../../../src/main/cpp/JSIInteropModuleRegistry.cpp
In file included from ../../../../src/main/cpp/JSIInteropModuleRegistry.cpp:3:
In file included from ../../../../src/main/cpp/JSIInteropModuleRegistry.h:6:
../../../../src/main/cpp/JavaScriptModuleObject.h:7:10: fatal error: 'react/bridging/LongLivedObject.h' file not found
#include <react/bridging/LongLivedObject.h>
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[6/12] Building CXX object CMakeFiles/expo-modules-core.dir/src/main/cpp/JavaScriptRuntime.cpp.o
[7/12] Building CXX object CMakeFiles/expo-modules-core.dir/src/main/cpp/JavaScriptValue.cpp.o
[8/12] Building CXX object CMakeFiles/expo-modules-core.dir/src/main/cpp/MethodMetadata.cpp.o
FAILED: CMakeFiles/expo-modules-core.dir/src/main/cpp/MethodMetadata.cpp.o
/Users/ee211312/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ --target=armv7-none-linux-androideabi21 --gcc-toolchain=/Users/ee211312/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64 --sysroot=/Users/ee211312/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/sysroot -Dexpo_modules_core_EXPORTS -I/node_modules/react-native/React -I/node_modules/react-native/React/Base -I/node_modules/react-native/ReactAndroid/src/main/jni -I/node_modules/react-native/ReactAndroid/src/main/jni/react -I/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/turbomodule/core/jni -I/node_modules/react-native/ReactCommon -I/node_modules/react-native/ReactCommon/react/nativemodule/core -I/node_modules/react-native/ReactCommon/callinvoker -I/node_modules/react-native/ReactCommon/jsi -I../../../../build/third-party-ndk/boost/boost_1_63_0 -I../../../../build/third-party-ndk/double-conversion -I../../../../build/third-party-ndk/folly -I../../../../build/fbjni-0.2.2-headers.jar -I../../../../ -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security -O2 -g -DNDEBUG -fPIC -DFOLLY_NO_CONFIG=1 -DFOLLY_HAVE_CLOCK_GETTIME=1 -DFOLLY_HAVE_MEMRCHR=1 -DFOLLY_USE_LIBCPP=1 -DFOLLY_MOBILE=1 -DUSE_HERMES=0 -DUNIT_TEST=0 -O2 -frtti -fexceptions -Wall -fstack-protector-all -std=gnu++1z -MD -MT CMakeFiles/expo-modules-core.dir/src/main/cpp/MethodMetadata.cpp.o -MF CMakeFiles/expo-modules-core.dir/src/main/cpp/MethodMetadata.cpp.o.d -o CMakeFiles/expo-modules-core.dir/src/main/cpp/MethodMetadata.cpp.o -c ../../../../src/main/cpp/MethodMetadata.cpp
In file included from ../../../../src/main/cpp/MethodMetadata.cpp:1:
../../../../src/main/cpp/MethodMetadata.h:8:10: fatal error: 'react/bridging/LongLivedObject.h' file not found
#include <react/bridging/LongLivedObject.h>
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[9/12] Building CXX object CMakeFiles/expo-modules-core.dir/src/main/cpp/JNIFunctionBody.cpp.o
[10/12] Building CXX object CMakeFiles/expo-modules-core.dir/src/main/cpp/CachedReferencesRegistry.cpp.o
[11/12] Building CXX object CMakeFiles/expo-modules-core.dir/src/main/cpp/JavaScriptObject.cpp.o
ninja: build stopped: subcommand failed.

Try:
Run with --stacktrace option to get the stack trace.
Run with --info or --debug option to get more log output.
Run with --scan to get full insights.

Get more help at https://help.gradle.org/
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 6 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

BUILD FAILED in 24m
657 actionable tasks: 628 executed, 29 up-to-date

Please help me to solve this issue.

### Version

0.68.2

### Output of `npx react-native info`

expo-env-info 1.0.5 environment info:
System:
OS: macOS 12.3.1
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 16.15.0 - /usr/local/bin/node
npm: 8.5.5 - /usr/local/bin/npm
Watchman: 2022.03.21.00 - /usr/local/bin/watchman
Managers:
CocoaPods: 1.11.3 - /usr/local/bin/pod
IDEs:
Android Studio: 2021.1 AI-211.7628.21.2111.8309675
Xcode: /undefined - /usr/bin/xcodebuild
npmPackages:
expo: ~46.0.0 => 46.0.17
react: 17.0.2 => 17.0.2
react-dom: 17.0.2 => 17.0.2
react-native: 0.68.2 => 0.68.2
react-native-web: 0.17.7 => 0.17.7
npmGlobalPackages:
eas-cli: 0.52.0
expo-cli: 5.4.6
Expo Workflow: bare

### Steps to reproduce

package.json:

{
"name": "mobile-cross-platform",
"version": "1.0.0",
"scripts": {
"start": "expo start --dev-client",
"android": "expo run:android",
"ios": "expo run:ios",
"web": "expo start --web",
"eject": "expo eject",
"android:dev": "npx react-native run-android --variant=devrelease",
"android:qa": "npx react-native run-android --variant=qarelease",
"android:demo": "npx react-native run-android --variant=demorelease",
"android:prod": "npx react-native run-android --variant=prodrelease"
},
"dependencies": {
"@react-native-async-storage/async-storage": "~1.17.3",
"@react-navigation/drawer": "^6.4.3",
"@react-navigation/native": "^6.0.11",
"@react-navigation/native-stack": "^6.7.0",
"buffer": "^6.0.3",
"expo": "~46.0.0",
"expo-barcode-scanner": "~11.3.0",
"expo-splash-screen": "~0.15.1",
"expo-status-bar": "~1.3.0",
"gs1-barcode-parser": "^1.0.1",
"jexl": "^2.3.0",
"jwt-decode": "^3.1.2",
"moment": "^2.29.4",
"react": "17.0.2",
"react-dom": "17.0.2",
"react-native": "0.68.2",
"react-native-config": "1.4.6",
"react-native-dialog-input": "^1.0.8",
"react-native-gesture-handler": "~2.5.0",
"react-native-modal": "^13.0.1",
"react-native-pager-view": "5.4.15",
"react-native-reanimated": "^2.9.1",
"react-native-restart": "^0.0.24",
"react-native-progress": "^5.0.0",
"react-native-safe-area-context": "4.2.4",
"react-native-screens": "~3.18.2",
"react-native-select-dropdown": "^2.0.4",
"react-native-splash-screen": "^3.3.0",
"react-native-step-indicator": "^1.0.3",
"react-native-svg": "^12.4.3",
"react-native-tab-view": "^3.1.1",
"react-native-uuid": "^2.0.1",
"react-native-vector-icons": "^9.2.0",
"react-native-web": "0.17.7",
"react-native-webview": "^11.22.7",
"react-timer-mixin": "^0.13.4",
"uuidv4": "^6.2.13",
"expo-camera": "~12.3.0"
},
"devDependencies": {
"@babel/core": "^7.12.9"
},
"private": true
}

Command used to generate the android apk:

npm run android:dev

and also

cd android && ./gradlew assembledevrelease

### Snack, code example, screenshot, or link to a repository

none

**Comment by elabayoub** [comment] 2022-11-14 10:20
Duplicate ? [#18412](https://github.com/expo/expo/issues/18412)

**Comment by cortinico** [comment] 2022-11-25 12:36
Duplicate of #35210

**Closed by cortinico** 2022-11-25 12:36 UTC
Labels: Needs: Triage :mag:

**Comment by axolotl0212** [comment] 2022-12-08 15:30
The header file `LongLivedObject.h` is moved in commit https://github.com/facebook/react-native/commit/6a9497dbbbdf76e65cdf1ea20561ad1f2c13372e in this repo

Hence the error is caused by `expo` incompatible with the `react-native` (in this case `expo` = `46.0.17`, `react-native` = `0.68.2`), leading to header not found error.

To fix this issue, either upgrading `react-native` to version which includes the commit above, or downgrading `expo` to sdk 45 or below.
