### ISSUE TITLE
[Android] It's not support mipmap folder

### ISSUE THREAD

**Issue by 157688302** [facebook/react-native#7852] opened 2016-05-31 15:13 UTC
must be use drawable-xx folder , mipmap folder is invalidation

**Comment by charpeni** [comment] 2016-05-31 16:41
@facebook-github-bot duplicate #2737

**Comment by facebook-github-bot-0** [comment] 2016-05-31 16:42
@charpeni tells me this issue is a duplicate of #2737. Let's discuss there, closing this one.

**Closed by facebook-github-bot-0** 2016-05-31 16:42 UTC
Labels: Ran Commands
