### ISSUE TITLE
TypeError: cli.init is not a function Error

### ISSUE THREAD

**Issue by garawaa** [facebook/react-native#34262] opened 2022-07-24 01:28 UTC
### Description

In latest version new project gives this error:
TypeError: cli.init is not a function Error

### Version

0.69

### Output of `npx react-native info`

  cli.init(root, projectName);
      ^

TypeError: cli.init is not a function
    at run (C:\dev\node-v14.17.5-win-x64\node-v14.17.5-win-x64\node_modules\react-native-cli\index.js:302:7)
    at createProject (C:\dev\node-v14.17.5-win-x64\node-v14.17.5-win-x64\node_modules\react-native-cli\index.js:249:3)
    at init (C:\dev\node-v14.17.5-win-x64\node-v14.17.5-win-x64\node_modules\react-native-cli\index.js:200:5)
    at Object.<anonymous> (C:\dev\node-v14.17.5-win-x64\node-v14.17.5-win-x64\node_modules\react-native-cli\index.js:153:7)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47

### Steps to reproduce

npx react-native init AwesomeProject

### Snack, code example, screenshot, or link to a repository

No screenshot

**Comment by wuyue1019** [comment] 2022-07-25 14:11
`yarn add react-native --exact
`
This should be able to fix your problem, dont know exactly why though

**Comment by cortinico** [comment] 2022-07-29 15:59
Essentially a duplicate of https://github.com/facebook/react-native/issues/34055
Please find the suggested workaround over there 👍

**Closed by cortinico** 2022-07-29 15:59 UTC
Labels: Needs: Triage :mag:
