### ISSUE TITLE
Question:  Xcode 11 and RN 0.58.6 / not find Iphone X Simulator

### ISSUE THREAD

**Issue by zhenghaiyang** [facebook/react-native#26677] opened 2019-10-01 14:41 UTC
React Native version: 0.58.6
  react:16.6.3
  xcode: Version 11.1 (11A1027) 
  node:12.11.0

## Steps To Reproduce

1. My Xcode run App is success
2. Execute the command ‘react-navite run-ios’ or 'npm run ios' .Error message 
    -  Found Xcode workspace elApp.xcworkspace
    -  CoreData: annotation:  Failed to load optimized model at path  '/Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/Frameworks/InstrumentsPackaging.framework/Versions/A/Resources/XRPackageModel.momd/XRPackageModel 9.0.omo'

    - Could not find iPhone X simulator

    - Error: Could not find iPhone X simulator
    at Promise.then.udid.udid (/Users/point/Documents/Work/Elitesland/GY/gy-b2bv2-app/node_modules/react-native/local-cli/runIOS/runIOS.js:149:13)
    at new Promise (<anonymous>)
    at runOnSimulator (/Users/point/Documents/Work/Elitesland/GY/gy-b2bv2-app/node_modules/react-native/local-cli/runIOS/runIOS.js:134:10)
    at Object.runIOS [as func] (/Users/point/Documents/Work/Elitesland/GY/gy-b2bv2-app/node_modules/react-native/local-cli/runIOS/runIOS.js:106:12)
    at /Users/point/Documents/Work/Elitesland/GY/gy-b2bv2-app/node_modules/react-native/local-cli/cliEntry.js:117:22

3. please help my.
       

Describe what you expected to happen:

Snack, code example, screenshot, or link to a repository:

**Comment by radko93** [comment] 2019-10-01 14:43
Duplicate of https://github.com/react-native-community/cli/issues/739

**Closed by radko93** 2019-10-01 14:43 UTC
Labels: Bug
