### ISSUE TITLE
when in smartbar case the Dimensions ‘s height is not correct on Android

### ISSUE THREAD

**Issue by shengbo1992** [facebook/react-native#13031] opened 2017-03-20 13:10 UTC
when the devices have a smartbar,I handle the smartbar on/off, and js use  Dimensions  get height is not correct,
i saw the code in  ReactRootView.java。it use the OnGlobalLayoutListener'callback to notify the js.
but the emitUpdateDimensionsEvent function use DisplayMetricsHolder.getWindowDisplayMetrics() always get the same vaule.

**Comment by hramos** [comment] 2017-03-20 16:30
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-03-20 16:30 UTC
