### ISSUE TITLE
ScrollView paging/snapToInterval does not work

### ISSUE THREAD

**Issue by Kurt57** [facebook/react-native#12274] opened 2017-02-08 02:09 UTC
### Description

I  have add an scrollview and define mine behaviors. one of this behaviors is that on diverse states enable the paging and calculate a snapToInterval. i debug and see that pagingEnabled is true and snapToInterval is calculated right. But the behavoir in the app is like paging is disabled or snapToInterval is very low like 0

### Reproduction

add a long scrollview with the probs:pagingEnabled={true} snapToInterval={300}
try to scroll on android in 300 intervalls/paging

### Solution

---

### Additional Information

* React Native version: 0.41.0
* Platform: android
* Operating System: MacOS

**Comment by lacker** [comment] 2017-02-10 00:37
Sorry, but I can't reproduce this problem. I think it would be really helpful to provide a sample app on rnplay.org or a similar service reproducing this; otherwise I don't know that we will be able to make any progress. I am going to close this issue but please feel free to reopen one if you do keep running into this and have a repro app available.

**Closed by lacker** 2017-02-10 00:37 UTC
