### ISSUE TITLE
WebSocket - java.lang.RuntimeException 

### ISSUE THREAD

**Issue by murugancmi** [facebook/react-native#16108] opened 2017-09-26 20:58 UTC
websocket connection closed automatically and crash app ,getting following crash report java.lang.RuntimeException: 
  at com.facebook.react.modules.websocket.WebSocketModule.send (WebSocketModule.java:221)

**Comment by hramos** [comment] 2017-09-27 19:11
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue that meets the requirements set forth in the template. Thanks!

**Closed by hramos** 2017-09-27 19:11 UTC
