### ISSUE TITLE
Using zIndex in a ListView

### ISSUE THREAD

**Issue by getnashty** [facebook/react-native#9491] opened 2016-08-20 05:27 UTC
I have a ListView of "cards" (styled view).

When one is tapped, I'm trying to grow it to full screen with absolute positioning. 

Regardless of how high I set the zIndex on one of these "card" - it seems to make no difference within the ListView component (it does not appear above the other items in the list view)- even though I am successfully using the zIndex elsewhere.

Is there a better way to do this?

**Comment by damusnet** [comment] 2016-08-20 13:37
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-0** [comment] 2016-08-20 13:38
Hey @getnashty and thanks for posting this! @damusnet tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Closed by facebook-github-bot-0** 2016-08-20 13:38 UTC
Labels: For Stack Overflow, Ran Commands

**Comment by luisfuertes** [comment] 2017-07-03 09:39
I'm trying to use Animated.View as row in ListView, when i animate row, set {zIndex: 999} style.

The problem is the render order. zIndex of last row works perfect, and move above others rows, but first row is rendered first, its zIndex is always lower and is seen underneath the other rows.

The items with absolute position have an incremental zIndex by default, in the order in which they are rendered, but i dont use position absolute. 

Some idea if it is a bug or if i am doing something wrong? Thanks
