### ISSUE TITLE
Imposible to create Grid with Flex

### ISSUE THREAD

**Issue by vnswvnsw** [facebook/react-native#13087] opened 2017-03-22 17:07 UTC
I do not thnik its possible to create great like bootstrap for responsivnes on different orientation or different screens.

Because of flex: 1 , if last line has less columns , they will be different size. 
So there is impossible to create table with flex with same columns.

**Comment by hramos** [comment] 2017-03-22 20:02
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-03-22 20:02 UTC
