### ISSUE TITLE
[0.57.0-rc.0] react-native-git-upgrade and old school upgrade are broken

### ISSUE THREAD

**Issue by fungilation** [facebook/react-native#20710] opened 2018-08-17 05:07 UTC
## Environment
```
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
      Memory: 8.52 GB / 15.95 GB
    Binaries:
      Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.0 - C:\Program Files\nodejs\npm.CMD
```
I'm upgrading from React Native 0.56.0.

## Description
```
PS C:\Users\Gary\Documents\code\WonderSwipe> react-native-git-upgrade.cmd 0.57.0-rc.0
git-upgrade info Check for updates
git-upgrade info Using yarn 1.9.4
git-upgrade info Read package.json files
git-upgrade info Check declared version
git-upgrade info Check matching versions
git-upgrade info Check React peer dependency
git-upgrade info Check that Git is installed
git-upgrade info Get information from NPM registry
git-upgrade info Upgrading to React Native 0.57.0-rc.0, React 16.4.1
git-upgrade info Setup temporary working directory
git-upgrade info Configure Git environment
git-upgrade info Init Git repository
git-upgrade info Add all files to commit
git-upgrade info Commit current project sources
git-upgrade info Create a tag before updating sources
git-upgrade info Generate old version template
git-upgrade ERR! An error occurred during upgrade:
git-upgrade ERR! Error: Plugin 0 specified in "C:\\Users\\Gary\\Documents\\code\\WonderSwipe\\node_modules\\babel-preset-react-native\\index.js" provided an invalid property of "default" (While processing preset: "C:\\Users\\Gary\\Documents\\code\\WonderSwipe\\node_modules\\babel-preset-react-native\\index.js")
    at Plugin.init (C:\Users\Gary\AppData\Roaming\npm\node_modules\react-native-git-upgrade\node_modules\babel-core\lib\transformation\plugin.js:131:13)
    at Function.normalisePlugin (C:\Users\Gary\AppData\Roaming\npm\node_modules\react-native-git-upgrade\node_modules\babel-core\lib\transformation\file\options\option-manager.js:152:12)
    at C:\Users\Gary\AppData\Roaming\npm\node_modules\react-native-git-upgrade\node_modules\babel-core\lib\transformation\file\options\option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (C:\Users\Gary\AppData\Roaming\npm\node_modules\react-native-git-upgrade\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (C:\Users\Gary\AppData\Roaming\npm\node_modules\react-native-git-upgrade\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at C:\Users\Gary\AppData\Roaming\npm\node_modules\react-native-git-upgrade\node_modules\babel-core\lib\transformation\file\options\option-manager.js:265:14
    at C:\Users\Gary\AppData\Roaming\npm\node_modules\react-native-git-upgrade\node_modules\babel-core\lib\transformation\file\options\option-manager.js:323:22
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (C:\Users\Gary\AppData\Roaming\npm\node_modules\react-native-git-upgrade\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
git-upgrade ERR! Restore initial sources
Note: checking out 'project-snapshot'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>
```

## Reproducible Demo
Run `react-native-git-upgrade 0.57.0-rc.0`. I can reproduce same error on both Windows and MacOS (latest High Sierra).

I've never encountered a similar breakage with `git-upgrade` for about the last 10 version of RN upgrades I've done with `react-native-git-upgrade`.

Ref: https://github.com/react-native-community/react-native-releases/issues/34

**Comment by eshikerya** [comment] 2018-08-17 05:27
confirm. could upgrade by ```react-native upgrade 0.57.0-rc.0``` and manually go through files.
not very successful cause there some other issues. script is bundled, but one time I got error screen about importing static config object from file (defined as ```module.exports = {...}```), now I got message:
```
Failed to load bundle(http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false) with error:(/Users/user/project/index.js: ENOENT: no such file or directory, uv_cwd (null))

__38-[RCTCxxBridge loadSource:onProgress:]_block_invoke.248
    RCTCxxBridge.mm:429
___ZL36attemptAsynchronousLoadOfBundleAtURLP5NSURLU13block_pointerFvP18RCTLoadingProgressEU13block_pointerFvP7NSErrorP9RCTSourceE_block_invoke.118
__80-[RCTMultipartDataTask URLSession:streamTask:didBecomeInputStream:outputStream:]_block_invoke
-[RCTMultipartStreamReader emitChunk:headers:callback:done:]
-[RCTMultipartStreamReader readAllPartsWithCompletionCallback:progressCallback:]
-[RCTMultipartDataTask URLSession:streamTask:didBecomeInputStream:outputStream:]
__88-[NSURLSession delegate_streamTask:didBecomeInputStream:outputStream:completionHandler:]_block_invoke
__NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
-[NSBlockOperation main]
-[__NSOperationInternal _start:]
__NSOQSchedule_f
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_continuation_pop
_dispatch_async_redirect_invoke
_dispatch_root_queue_drain
_dispatch_worker_thread2
_pthread_wqthread
start_wqthread
```

**Comment by kelset** [comment] 2018-08-17 08:17
Have you tried manually upgrading to 0.57?

**Comment by christianbach** [comment] 2018-08-17 09:09
Removing my local `.babelrc` file before running `react-native-git-upgrade 0.57.0-rc.0` solved the problem for me

**Comment by grabbou** [comment] 2018-08-17 10:32
@kelset I don't think you need to set dependency on the preset anyway, because it's part of Metro dependencies and ends up being in your node modules anyway. Remember that its version has to always match internal Metro version, which may be hard to keep in sync due to lack of peer dependency on RN.

**Comment by rizwanatta** [comment] 2018-08-17 18:35
ALL WORK LIKE PEAS AND CARROTS ON MY MAC! but I am team lead at a react native base software house and my co-workers are **WINDOWS BASED HUMANOIDS** so here is what I have found !

I have been asking about **this ISSUE of RN 0.56** !!for like from weeks! on **reactiflux, slack communities**, and been following **twitter announcements**; I just saw couple of hours ago on twitter **that 0.57 is here**! I jumped into my package.json, updated manually and react-native-git-upgrader. but after manually updating it all things seemed to work out well ! that INFAMOUS 500 server error was long gone! but now it says
**OLD BUT GOLD ERROR**
"Unable to load script from assets index.android.bundle on windows"

one ERROR GOES AND THERE IS ANOTHER RED SCREEN POPING up! I had to do jump and bump among several GIT ISSUES threads and stacks! but I am still not able to do it! 

MY BEST GUESS HERE is:

as in versions before 0.56 of RN we used to have index.android.js & index.ios.js files , and somehow the 0.57rc update is taking an old PR of code structure or something !        

again above said is a theory I won't dare to upgrade 0.57rc on my Mac for now! but any Window's user at RN dev community should try this one! please ! we WINDOW users are HUMANS Too.

**Comment by kelset** [comment] 2018-08-17 19:52
I guess that I've to lock this issue too, apparently it's impossible to avoid disruptive people when trying to fix issues related to release candidates 🤷‍♂️

I'll keep saying it, it's an open source project. Don't you like something? Fork it and fix it yourself. Writing these kinds of comments is just pathetic.

**Comment by fungilation** [comment] 2018-08-18 20:12
Tried upgrading the old fashioned way. I first ran `yarn add react-native@0.57.0-rc.0` without issue, and modified my `.babelrc` to
```
{
  "presets": ["module:metro-react-native-babel-preset"],
  "plugins": ["idx"]
}
```

Then I ran `react-native upgrade`, and I get
```
PS C:\Users\Gary\Documents\code\WonderSwipe> react-native upgrade
Scanning folders for symlinks in C:\Users\Gary\Documents\code\WonderSwipe\node_modules (28ms)
(node:16936) UnhandledPromiseRejectionWarning: Error: Cannot find module 'metro/src/blacklist'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\Gary\Documents\code\WonderSwipe\rn-cli.config.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._compile (C:\Users\Gary\Documents\code\WonderSwipe\node_modules\pirates\lib\index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .js] (C:\Users\Gary\Documents\code\WonderSwipe\node_modules\pirates\lib\index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
(node:16936) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16936) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Metro still?

PS. output: https://github.com/facebook/react-native/issues/20720#issuecomment-413984074 from `yarn add` for metro/babel versions upgraded to. Need locking to specific versions instead of latest?

**Comment by kelset** [comment] 2018-08-20 09:33
@fungilation can you copy/paste your `package.json` if possible?
But yeah that blacklist error seems Metro related.

**Comment by fungilation** [comment] 2018-08-20 17:09
<details><summary>My package.json</summary>

```json
{
  "name": "wonderswipe",
  "version": "0.0.1",
  "private": true,
  "eslintConfig": {
    "parserOptions": {
      "ecmaVersion": 7,
      "sourceType": "module",
      "ecmaFeatures": {
        "jsx": true
      }
    },
    "env": {
      "browser": true,
      "node": true
    },
    "plugins": [
      "react",
      "react-native"
    ],
    "rules": {
      "comma-dangle": [
        2,
        "always-multiline"
      ],
      "semi": [
        2,
        "never"
      ],
      "react-native/no-unused-styles": 2,
      "react-native/split-platform-components": 2
    }
  },
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "babel-plugin-idx": "^2",
    "he": "^1.1.0",
    "lodash": "^4.17.2",
    "moment": "^2.19.0",
    "moment-timezone": "^0.5.10",
    "node-summary": "../node-summary",
    "react": "16.4.1",
    "react-native": "0.57.0-rc.0",
    "react-native-actionsheet": "^2.4.2",
    "react-native-blur": "^3.2.0",
    "react-native-cached-image": "../react-native-cached-image",
    "react-native-code-push": "^5.3",
    "react-native-custom-tabs": "^0.1.7",
    "react-native-easy-toast": "^1.0.9",
    "react-native-firebase": "^3.0",
    "react-native-fit-image": "^1.4.8",
    "react-native-flanimatedimage": "^0.4.0",
    "react-native-highlight-words": "^1.0.1",
    "react-native-keep-awake": "^3.0.1",
    "react-native-linear-gradient": "^2.0.0",
    "react-native-modalbox": "^1.6.0",
    "react-native-orientation": "^3.1.3",
    "react-native-parallax-scroll-view": "../react-native-parallax-scroll-view",
    "react-native-rate": "^1.0.8",
    "react-native-safari-view": "^2.0.0",
    "react-native-sentry": "^0.38.0",
    "react-native-sha256": "^1.1.1",
    "react-native-status-bar-size": "^0.3.2",
    "react-native-swiper": "../react-native-swiper",
    "react-native-tooltip": "^5.2.0",
    "react-native-tts": "^1.5.0",
    "react-native-vector-icons": "^4.1.1",
    "react-native-webview-bridge": "../react-native-webview-bridge-RN0.51",
    "react-redux": "^5.0.1",
    "redux": "^4.0.0",
    "redux-thunk": "^2.1.0"
  },
  "devDependencies": {
    "redux-logger": "^3.0.6"
  }
}
```

</details>

**Comment by fungilation** [comment] 2018-08-20 18:07
Made those changes and ran `yarn`. Confirmed that `yarn.lock` shows babel deps now at 7.0.0-beta.56 instead of 7.0.0-beta.47 before.

But running `react-native upgrade` hits the same `Error: Cannot find module 'metro/src/blacklist'`... as before.

**Comment by rafeca** [comment] 2018-08-21 10:43
I've done some investigation and the original reported issue is caused by `react-native-git-upgrade` using still Babel 6 to transpile itself:

https://github.com/facebook/react-native/blob/9c1ea45d38a6ec731894443debe8879fa3876ab7/react-native-git-upgrade/cli.js#L12-L19


Babel by default tries to find `.babelrc` files to configure itself, and once it finds the one from the RN app (which links to the RN preset that only works on Babel 7) it fails.

The easiest patch to fix this issue is to add `babelrc: false` to the `babel-register` method, so Babel does not read any additional `.babelrc` file.

@fungilation can you give this a try? feel free to send a PR if this fixes the issue 😃

**Comment by ngraef** [comment] 2018-08-22 04:08
FWIW, @rafeca's fix worked for me. Patched and ran `react-native-git-upgrade`, resolved merge conflicts, cleaned up with `npm uninstall babel-preset-react-native`, and I'm good to go (or rather, I've moved on to the next issue, #20712).

<details>
<summary>Environment</summary>

```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
      Memory: 849.51 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.10.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 5.10.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.3, 27.0.3, 28.0.2
        API Levels: 23, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.4.1 => 16.4.1
      react-native: ^0.57.0-rc.0 => 0.57.0-rc.0
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```
</details>

**Comment by kelset** [comment] 2018-08-22 08:57
Good to hear, @ngraef would you mind creating a PR with the fix so that it can be merged and cherry-picked for a rc1 release, so that it can be available?

**Comment by Todilo** [comment] 2018-08-22 09:40
@ngraef did you have to do some additional babel configuration? 
https://github.com/facebook/react-native/issues/20712
there is a suggestion fix
```
const procConfig = {cwd: scriptsDir};
with
const procConfig = {};
```

Which also "solves" that problem for me. However I get error from
`node_modules\react-native\Libraries\Image\Image.android.js: Support for the experimental syntax 'optionalChaining' isn't currently enabled (221:13):`

**Closed** 2018-08-22 19:33 UTC
Labels: :warning:Regression, :wrench:Tooling, 📦Bundler
