### ISSUE TITLE
[Image]Remote image with 640*27239 can't load.

### ISSUE THREAD

**Issue by l327253678** [facebook/react-native#11523] opened 2016-12-17 08:06 UTC
render() {
    return (
      <Image
        style={{width:640,height:700}}
        source={{uri:'http://mpic.spriteapp.cn/x/640x400/ugc/2016/12/09/584a3d502f9ab_1.jpg'}}
        />
    )
  }
The image height is 27239.It load failed with Image component( iOS Simulator and Genymotion ).Is it a bug?

**Comment by linmic** [comment] 2016-12-18 17:22
I believe this is a duplicate of #10470.

**Comment by linmic** [comment] 2016-12-18 17:29
Can you make sure the image was loaded rather slowly or didn't render at all. I encountered this issue on Android but not iOS, it was just loaded really slow on iOS but rendered nothing in Android.

If it's only on Android, this is a known issue, see #10470.

**Comment by l327253678** [comment] 2016-12-19 08:20
@linmic Thanks for your Help.As one solution,i resize the image as  thumbnail in server-side.The ListView receive the thumbnail and display the image detail in WebView.

**Comment by hramos** [comment] 2017-05-25 20:31
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Closed by hramos** 2017-05-25 20:31 UTC
