### ISSUE TITLE
broken Image cached while network fail

### ISSUE THREAD

**Issue by notlose** [facebook/react-native#6755] opened 2016-04-01 06:12 UTC
RN 0.22
Network image cached even network fail,
it always render blank even network resume normal.

**Comment by prtkkmrsngh** [comment] 2016-04-12 09:26
Same issue I also faced but realized that in build version not an issue anymore.

**Comment by notlose** [comment] 2016-04-12 09:29
I still facing this problem in my released app..

Sent from Outlook Mobile




On Tue, Apr 12, 2016 at 2:28 AM -0700, "prtkkmrsngh" <notifications@github.com> wrote:





Same issue I also faced but realized that in build version not an issue anymore.

---

**Comment by prtkkmrsngh** [comment] 2016-04-12 10:05
This shouldn't happen may be your image is corrupt. Still you can try this 
`<Image key={url} />` which will replace your old image with a new one each time the URL changes.

**Comment by lacker** [comment] 2016-10-21 00:04
Hey, I think this issue lacks enough information to reproduce the problem, so I'm going to close it. If it turns out the problem is not a corrupted image but rather a bug in React Native then feel free to reopen an issue.

**Closed by lacker** 2016-10-21 00:04 UTC
