### ISSUE TITLE
Can't Init project - It won't install CocoaPods

### ISSUE THREAD

**Issue by tinymobile** [facebook/react-native#41250] opened 2023-10-30 17:53 UTC
### Description

I have a brand new mac and am trying to initialise a new React Native project. However, it fails when trying to install CocoaPods:

✔ Downloading template
✔ Copying template
✔ Processing template
✔ Installing Ruby Gems
ℹ Installing Ruby Gems
✖ Installing CocoaPods
error 
✖ Installing CocoaPods
error An error occured while trying to install CocoaPods, which is required by this template.
Please try again manually: sudo gem install cocoapods.

If I try to manually install Cocoapods as it suggests, it says:

Error installing cocoapods:
	There are no versions of cocoapods-downloader (>= 2.0) compatible with your Ruby & RubyGems. Maybe try installing an older version of the gem you're looking for?
	cocoapods-downloader requires Ruby version >= 2.7.4. The current ruby version is 2.6.10.210.
	
Do I have to update Ruby? 

### React Native Version

0.72.6

### Output of `npx react-native info`

npx react-native info
info Fetching system and libraries information...
System:
  OS: macOS 14.1
  CPU: (10) arm64 Apple M2 Pro
  Memory: 180.22 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.1.0
    path: /opt/homebrew/bin/node
  Yarn: Not Found
  npm:
    version: 10.2.1
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.10.23.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods: Not Found
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.6
    wanted: 0.72.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

(node:21795) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

### Steps to reproduce

npx react-native@latest init AwesomeProject

### Snack, screenshot, or link to a repository

N/A

**Comment by frankcalise** [comment] 2023-10-30 19:21
Hello @tinymobile 

Can you provide the following output please?

```
which pod
pod --version
```

Asking because it doesn't appear that the `info` command was able to find CocoaPods installed

**Comment by yuriiburov** [comment] 2023-10-30 19:43
@tinymobile the same

**Comment by yuriiburov** [comment] 2023-10-30 20:09
@tinymobile I've already fixed it

My steps to fix it
type in terminal (bash)

sudo gem uninstall cocoapods
sudo gem install cocoapods
brew install cocoapods
brew reinstall cocoapods

and run again
npx react-native@latest init AwesomeProject

looks strange, but the main thing is that it solved the problem)

**Comment by frankcalise** [comment] 2023-10-30 20:52
@tinymobile are you following the [Environment Setup](https://reactnative.dev/docs/environment-setup?platform=ios) docs?

**Comment by Carlosv310** [comment] 2023-10-31 02:34
having same issue! Did anyone solve?

**Comment by tinymobile** [comment] 2023-10-31 05:34
> @tinymobile are you following the [Environment Setup](https://reactnative.dev/docs/environment-setup?platform=ios) docs?

Yes.  I've done everything apart from this:

CocoaPods
You can install CocoaPods using the version of Ruby that ships with the latest version of macOS.

For more information, please visit [CocoaPods Getting Started guide](https://guides.cocoapods.org/using/getting-started.html).

The problem is, I cannot install CocoaPods using the version of Ruby that ships with the latest version of macOS.

It fails and says I require a later version of Ruby, which I obviously don't want to do.

When I try react-native init, it also tries to install Cocoapods as it's the first time i've run it on this machine, and that also fails.

Is the problem with Cocoapods?

**Comment by tinymobile** [comment] 2023-10-31 05:42
> @tinymobile I've already fixed it
> 
> My steps to fix it type in terminal (bash)
> 
sudo gem uninstall cocoapods 
sudo gem install cocoapods 
brew install cocoapods 
brew reinstall cocoapods
> 
> and run again npx react-native@latest init AwesomeProject
> 
> looks strange, but the main thing is that it solved the problem)


Yes, this worked for me as well. Very strange! I'll keep rebuilding my project to see if it causes any issues down the line, and let you know. Thanks!

**Comment by cipolleschi** [comment] 2023-10-31 15:50
In theory, it should not be required.
As you can see [here](https://app.circleci.com/pipelines/github/facebook/react-native/34321/workflows/cd65d786-7ac1-46fb-ba23-77fa08411301/jobs/1133029) we are building the 0.72 branch using Ruby 2.6.10, which is the one that comes with MacOS.

What's happening is that:
- you don't have cocoapods installed
- when you try to install it, it tries to fetch the most recent version (1.14.0) which depends on a newer version of ruby
- by uninstalling it from `gem` and installing it with `brew`, you are retrieveing the latest version on `brew`, which is not 1.14.0 yet, but it is 1.13.0, which depends on a compatible version of Cocoapods-downloader
and that's why it works.

We need to pin some dependency to make sure that this does not happen. Thank you for reporting.

I'll keep the issue open until we have a fix for it landed on `main`.

**Comment by Cubik65536** [comment] 2023-11-05 01:17
What I did to solve this is to install a newer Ruby by `brew install ruby`.
(also with macOS 14.1 on M2 Pro)

According to [CocoaPods' Installation Guide](https://cocoapods.org/):

> CocoaPods is built with Ruby and is installable with the default Ruby available on macOS. We recommend you use the default ruby.

But it's not true (at least for now) as the log says:

> cocoapods-downloader requires Ruby version >= 2.7.4. The current ruby version is 2.6.10.210.

A newer Ruby version downloaded (from HomeBrew for me, but I think other sources might work as well) is needed according to this prompt and it does work.

**Comment by Godden13** [comment] 2023-11-06 20:14
It works for me when I use **brew install cocaopods**
Don't follow **sudo gem install cocoapods** as it will keep throwing the same error

**Comment by WuChenDi** [comment] 2023-11-07 02:55
> It works for me when I use **brew install cocaopods** Don't follow **sudo gem install cocoapods** as it will keep throwing the same error

I execute brew install cocaopods the following error: 
```
Warning: Treating cocoapods as a formula. For the cask, use homebrew/cask/cocoapods
Warning: You are using macOS 14.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
pre-release version.

Error: cocoapods: no bottle available!
You can try to install from source with:
  brew install --build-from-source cocoapods
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
```

**Comment by cipolleschi** [comment] 2023-11-07 14:35
@WuChenDi have you tried run `brew update` first?

Otherwise, the solution is in the message:
> Error: cocoapods: no bottle available!
> You can try to install from source with:
>  brew install --build-from-source cocoapods

You are already on Sonoma and either your brew is not updated or Cocopods has not prepared the brew formula for it yet and you have to build it from source.

**Comment by patrykborkowskitukano** [comment] 2023-11-08 08:45
I tried above solution and doesn't work. 

sudo gem uninstall cocoapods  -> Gem 'cocoapods' is not installed

sudo gem install cocoapods  ->  ERROR:  Error installing cocoapods:
        There are no versions of cocoapods-downloader (>= 2.0) compatible with your Ruby & RubyGems. Maybe try installing an older version of the gem you're looking for?
        cocoapods-downloader requires Ruby version >= 2.7.4. The current ruby version is 2.6.10.210.

brew install cocoapods  -> cocoapods 1.14.2 is already installed and up-to-date.

brew reinstall cocoapods. -> just reinstalled

pod: v1.14.2
gem: v3.0.3.1
node: v16.14.2
npm: v8.5.0

**Comment by cipolleschi** [comment] 2023-11-08 14:45
@patrykborkowskitukano what's exactly your problem?

what happens if you run 
```
npx react-native@latest init AwesomeProject --skip-install
cd AwesomeProject
yarn
cd ios
bundle install
bundle exec pod install
cd ..
yarn ios
```
?

**Comment by CarlitosDroid** [comment] 2023-11-08 16:48
I have the same issue. In my case I just want to install cocoapods for my XcodeProject and I get the same error as @tinymobile @patrykborkowskitukano . I'm not using React right now so I don't have any react-related dependency installed. I think the problem is with Cocoapods. 

Mac Version: Ventura 13.6.1

**Comment by cipolleschi** [comment] 2023-11-09 16:23
@CarlitosDroid 
both `brew install cocoapods` and `sudo gem install cocoapods` are failing for you?
have you tried to run `brew update` before running `brew install cocoapods`?

**Comment by CarlitosDroid** [comment] 2023-11-09 17:41
@cipolleschi At the end I could figure out what was the problem.

I run 

> brew link cocoapods

<img width="683" alt="1" src="https://github.com/facebook/react-native/assets/10377529/558a7595-2aa5-48bc-9e5c-e61aec93c6db">

As you can see, It cannot symblink because `xcodeproj` already exists in the path `/user/local/bin/xcodeproj`. 
**So I had to remove it manually and then run brew link cocoapods**

<img width="1035" alt="2" src="https://github.com/facebook/react-native/assets/10377529/98b0993e-01a7-4e0c-b11e-66a60248a2bb">


Nitpick:
I guess everything happened because I installed Xcode first (which install the comand line tools) and then `brew install cocoapods` (which also install the command line tools, maybe in a different path), but I'm not sure.

**Comment by CarlitosDroid** [comment] 2023-11-09 17:45
> @CarlitosDroid both `brew install cocoapods` and `sudo gem install cocoapods` are failing for you? have you tried to run `brew update` before running `brew install cocoapods`?

Yes both:

1. `brew install cocoapods` -> it gave me the warning about cocapods 1.14.2 is already installed.
2. `sudo gem install cocoapods` -> it gave me the error about cocoapods-downloader requries Ruby version >= 2.7.4

**Comment by patrykborkowskitukano** [comment] 2023-11-09 21:07
the same result as @CarlitosDroid
during GitHub workflow action I'm stuck on:

      - uses: NiftyStack/install-cocoapods-action@1.0.1
      - run: cd ios &&  arch -x86_64 pod install --repo-update
      
      maybe it's problem that I use MBP M1 Pro with ARM64 processor
      
I configured as self-hosted virtual machine
Actually it's working on my friend's windows pc and we both have ruby version 2.6.10p210 and cocoapods v1.14.2

**Comment by cipolleschi** [comment] 2023-11-09 21:30
1. you don't have to use `arch -x86_64` anymore
2. from the `ios` folder,  run `bundle install`. This install [Ruby Bundler](https://bundler.io/) which is the dependency manager for ruby. This makes sure that you are using compatible versions of Ruby dependencies.
3. then run `bundle exec pod install`

**Comment by kaimacuser** [comment] 2023-11-11 01:07
I have the same Problem (macOS Sonoma 14.1.1) while executing `sudo gem install cocoapods` and I get the following error message:
`ERROR:  Error installing cocoapods:
	There are no versions of cocoapods-downloader (>= 2.0) compatible with your Ruby & RubyGems. Maybe try installing an older version of the gem you're looking for?
	cocoapods-downloader requires Ruby version >= 2.7.4. The current ruby version is 2.6.10.210.`

It worked for the previous version of cocoapods. While executing the command I was asked to install a few other things, so the final order was:

1. `sudo gem install drb -v 2.0.5`
2. `sudo gem install activesupport -v 6.1.7.6`
3. `sudo gem install cocoapods -v 1.13.0`

Good luck :)

**Comment by benfodil** [comment] 2023-11-11 16:43
> I have the same Problem (macOS Sonoma 14.1.1) while executing `sudo gem install cocoapods` and I get the following error message: `ERROR: Error installing cocoapods: There are no versions of cocoapods-downloader (>= 2.0) compatible with your Ruby & RubyGems. Maybe try installing an older version of the gem you're looking for? cocoapods-downloader requires Ruby version >= 2.7.4. The current ruby version is 2.6.10.210.`
> 
> It worked for the previous version of cocoapods. While executing the command I was asked to install a few other things, so the final order was:
> 
> 1. `sudo gem install drb -v 2.0.5`
> 2. `sudo gem install activesupport -v 6.1.7.6`
> 3. `sudo gem install cocoapods -v 1.13.0`
> 
> Good luck :)

Thanks, its work

**Comment by cipolleschi** [comment] 2023-11-11 18:34
Can you use Ruby bundler, please? 
You just have to run `bundle install && bundle exec pod install`. Ruby bundler takes care of handling the gem dependencies FOR YOU! That's the reason why we added it. By using `bundle install`, it will make sure that you are using the right versions of Cocoapods, ActiveSupports and all the other dependencies.

**Closed by cipolleschi** 2023-11-11 18:34 UTC
Labels: Needs: Triage :mag:, Needs: Repro
