### ISSUE TITLE
Didn’t find class on path DexPathList Android 0.71.0

### ISSUE THREAD

**Issue by affansk** [facebook/react-native#35891] opened 2023-01-19 09:44 UTC
### Description

The Android App Is crashing on start up after upgrading to version 0.71.0

### Version

0.71.0

### Output of `npx react-native info`

 FATAL EXCEPTION: main
                                                                                                    Process: com.project.driver.uat, PID: 6331
                                                                                                    java.lang.RuntimeException: Unable to instantiate application com.project.MainApplication package com.project.driver.uat: java.lang.ClassNotFoundException: Didn't find class "com.project.MainApplication" on path: DexPathList[[zip file "/data/app/~~UdRN3hbxUZtcAvI_jWXe7A==/com.project.driver.uat-_AmZEFHDAHR4Br4Efb-ksQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~UdRN3hbxUZtcAvI_jWXe7A==/com.project.driver.uat-_AmZEFHDAHR4Br4Efb-ksQ==/lib/arm64, /data/app/~~UdRN3hbxUZtcAvI_jWXe7A==/com.project.driver.uat-_AmZEFHDAHR4Br4Efb-ksQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
                                                                                                    	at android.app.LoadedApk.makeApplication(LoadedApk.java:1364)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6695)
                                                                                                    	at android.app.ActivityThread.access$1500(ActivityThread.java:256)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2090)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7842)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.project.MainApplication" on path: DexPathList[[zip file "/data/app/~~UdRN3hbxUZtcAvI_jWXe7A==/com.project.driver.uat-_AmZEFHDAHR4Br4Efb-ksQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~UdRN3hbxUZtcAvI_jWXe7A==/com.project.driver.uat-_AmZEFHDAHR4Br4Efb-ksQ==/lib/arm64, /data/app/~~UdRN3hbxUZtcAvI_jWXe7A==/com.project.driver.uat-_AmZEFHDAHR4Br4Efb-ksQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
                                                                                                    	at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:52)
                                                                                                    	at android.app.Instrumentation.newApplication(Instrumentation.java:1189)
                                                                                                    	at android.app.LoadedApk.makeApplication(LoadedApk.java:1356)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6695) 
                                                                                                    	at android.app.ActivityThread.access$1500(ActivityThread.java:256) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2090) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7842) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 

### Steps to reproduce

Upgrade to React native 0.71.0
build the app. the app will build 
it will crash on startup

### Snack, code example, screenshot, or link to a repository

 FATAL EXCEPTION: main
                                                                                                    Process: com.project.driver.uat, PID: 6331
                                                                                                    java.lang.RuntimeException: Unable to instantiate application com.project.MainApplication package com.project.driver.uat: java.lang.ClassNotFoundException: Didn't find class "com.project.MainApplication" on path: DexPathList[[zip file "/data/app/~~UdRN3hbxUZtcAvI_jWXe7A==/com.project.driver.uat-_AmZEFHDAHR4Br4Efb-ksQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~UdRN3hbxUZtcAvI_jWXe7A==/com.project.driver.uat-_AmZEFHDAHR4Br4Efb-ksQ==/lib/arm64, /data/app/~~UdRN3hbxUZtcAvI_jWXe7A==/com.project.driver.uat-_AmZEFHDAHR4Br4Efb-ksQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
                                                                                                    	at android.app.LoadedApk.makeApplication(LoadedApk.java:1364)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6695)
                                                                                                    	at android.app.ActivityThread.access$1500(ActivityThread.java:256)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2090)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7842)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.project.MainApplication" on path: DexPathList[[zip file "/data/app/~~UdRN3hbxUZtcAvI_jWXe7A==/com.project.driver.uat-_AmZEFHDAHR4Br4Efb-ksQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~UdRN3hbxUZtcAvI_jWXe7A==/com.project.driver.uat-_AmZEFHDAHR4Br4Efb-ksQ==/lib/arm64, /data/app/~~UdRN3hbxUZtcAvI_jWXe7A==/com.project.driver.uat-_AmZEFHDAHR4Br4Efb-ksQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
                                                                                                    	at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:52)
                                                                                                    	at android.app.Instrumentation.newApplication(Instrumentation.java:1189)
                                                                                                    	at android.app.LoadedApk.makeApplication(LoadedApk.java:1356)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6695) 
                                                                                                    	at android.app.ActivityThread.access$1500(ActivityThread.java:256) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2090) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7842) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by cortinico** [comment] 2023-01-19 09:50
> Caused by: java.lang.ClassNotFoundException: Didn't find class "com.project.MainApplication" on path:

This happens when the class `"com.project.MainApplication"` is missing becuase of Proguard or a misconfiguration of your build.gradle/Manifest or other files.

We would need a reproducer to help you further

**Comment by anvarisy** [comment] 2023-01-31 15:43
> ### Description
> The Android App Is crashing on start up after upgrading to version 0.71.0
> 
> ### Version
> 0.71.0
> 
> ### Output of `npx react-native info`
> FATAL EXCEPTION: main Process: com.project.driver.uat, PID: 6331 java.lang.RuntimeException: Unable to instantiate application com.project.MainApplication package com.project.driver.uat: java.lang.ClassNotFoundException: Didn't find class "com.project.MainApplication" on path: DexPathList[[zip file "/data/app/~~UdRN3hbxUZtcAvI_jWXe7A==/com.project.driver.uat-_AmZEFHDAHR4Br4Efb-ksQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~UdRN3hbxUZtcAvI_jWXe7A==/com.project.driver.uat-_AmZEFHDAHR4Br4Efb-ksQ==/lib/arm64, /data/app/~~UdRN3hbxUZtcAvI_jWXe7A==/com.project.driver.uat-_AmZEFHDAHR4Br4Efb-ksQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]] at android.app.LoadedApk.makeApplication(LoadedApk.java:1364) at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6695) at android.app.ActivityThread.access$1500(ActivityThread.java:256) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2090) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loopOnce(Looper.java:201) at android.os.Looper.loop(Looper.java:288) at android.app.ActivityThread.main(ActivityThread.java:7842) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) Caused by: java.lang.ClassNotFoundException: Didn't find class "com.project.MainApplication" on path: DexPathList[[zip file "/data/app/~~UdRN3hbxUZtcAvI_jWXe7A==/com.project.driver.uat-_AmZEFHDAHR4Br4Efb-ksQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~UdRN3hbxUZtcAvI_jWXe7A==/com.project.driver.uat-_AmZEFHDAHR4Br4Efb-ksQ==/lib/arm64, /data/app/~~UdRN3hbxUZtcAvI_jWXe7A==/com.project.driver.uat-_AmZEFHDAHR4Br4Efb-ksQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]] at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218) at java.lang.ClassLoader.loadClass(ClassLoader.java:379) at java.lang.ClassLoader.loadClass(ClassLoader.java:312) at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76) at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:52) at android.app.Instrumentation.newApplication(Instrumentation.java:1189) at android.app.LoadedApk.makeApplication(LoadedApk.java:1356) at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6695)  at android.app.ActivityThread.access$1500(ActivityThread.java:256)  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2090)  at android.os.Handler.dispatchMessage(Handler.java:106)  at android.os.Looper.loopOnce(Looper.java:201)  at android.os.Looper.loop(Looper.java:288)  at android.app.ActivityThread.main(ActivityThread.java:7842)  at java.lang.reflect.Method.invoke(Native Method)  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
> 
> ### Steps to reproduce
> Upgrade to React native 0.71.0 build the app. the app will build it will crash on startup
> 
> ### Snack, code example, screenshot, or link to a repository
> FATAL EXCEPTION: main Process: com.project.driver.uat, PID: 6331 java.lang.RuntimeException: Unable to instantiate application com.project.MainApplication package com.project.driver.uat: java.lang.ClassNotFoundException: Didn't find class "com.project.MainApplication" on path: DexPathList[[zip file "/data/app/~~UdRN3hbxUZtcAvI_jWXe7A==/com.project.driver.uat-_AmZEFHDAHR4Br4Efb-ksQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~UdRN3hbxUZtcAvI_jWXe7A==/com.project.driver.uat-_AmZEFHDAHR4Br4Efb-ksQ==/lib/arm64, /data/app/~~UdRN3hbxUZtcAvI_jWXe7A==/com.project.driver.uat-_AmZEFHDAHR4Br4Efb-ksQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]] at android.app.LoadedApk.makeApplication(LoadedApk.java:1364) at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6695) at android.app.ActivityThread.access$1500(ActivityThread.java:256) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2090) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loopOnce(Looper.java:201) at android.os.Looper.loop(Looper.java:288) at android.app.ActivityThread.main(ActivityThread.java:7842) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) Caused by: java.lang.ClassNotFoundException: Didn't find class "com.project.MainApplication" on path: DexPathList[[zip file "/data/app/~~UdRN3hbxUZtcAvI_jWXe7A==/com.project.driver.uat-_AmZEFHDAHR4Br4Efb-ksQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~UdRN3hbxUZtcAvI_jWXe7A==/com.project.driver.uat-_AmZEFHDAHR4Br4Efb-ksQ==/lib/arm64, /data/app/~~UdRN3hbxUZtcAvI_jWXe7A==/com.project.driver.uat-_AmZEFHDAHR4Br4Efb-ksQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]] at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218) at java.lang.ClassLoader.loadClass(ClassLoader.java:379) at java.lang.ClassLoader.loadClass(ClassLoader.java:312) at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76) at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:52) at android.app.Instrumentation.newApplication(Instrumentation.java:1189) at android.app.LoadedApk.makeApplication(LoadedApk.java:1356) at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6695)  at android.app.ActivityThread.access$1500(ActivityThread.java:256)  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2090)  at android.os.Handler.dispatchMessage(Handler.java:106)  at android.os.Looper.loopOnce(Looper.java:201)  at android.os.Looper.loop(Looper.java:288)  at android.app.ActivityThread.main(ActivityThread.java:7842)  at java.lang.reflect.Method.invoke(Native Method)  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

you can create your own MainApplication file.

**Comment by leolusoli** [comment] 2023-02-20 09:37
+1

**Comment by Vekt0r11** [comment] 2023-03-15 14:40
+1

**Comment by oTiMo** [comment] 2023-03-17 14:24
+1

**Comment by florentferry** [comment] 2023-03-17 15:09
+1

**Comment by IgorRomanvsky** [comment] 2023-03-17 22:30
+1

**Comment by IgorRomanvsky** [comment] 2023-03-17 23:57
How can we solve this issue? We can't build the project.

**Comment by cortinico** [comment] 2023-04-06 09:20
> I've opened a detailed issue regarding this problem => #36519

Closing as the linked issue is resolved: https://github.com/facebook/react-native/issues/36519#issuecomment-1474840971

Please open a separate issue if you're still having this prolbem

**Closed by cortinico** 2023-04-06 09:20 UTC
Labels: Platform: Android, Needs: Author Feedback, Needs: Repro

**Comment by oTiMo** [comment] 2023-04-06 12:06
@cortinico the resolution seems to be for expo users only
