### ISSUE TITLE
undefined is not an object (evaluating '_reactNative.propTypes.object')

### ISSUE THREAD

**Issue by Julianhm9612** [facebook/react-native#13502] opened 2017-04-14 04:41 UTC
### My problem is the next:

undefined is not an object (evaluating '_reactNative.propTypes.object')

I'm using part of the react-native-material demo:

![image](https://cloud.githubusercontent.com/assets/24255842/25033374/b8dfd932-20a2-11e7-8ef2-eea3e000465b.png)

import React, { Component } from 'react';
import { PropTypes, View, Text, Image } from 'react-native';
import { Avatar, Drawer, Divider, COLOR, TYPO } from 'react-native-material-design';

export default class Navigation extends Component {
    static contextTypes = {
        drawer: PropTypes.object.isRequired,
        navigator: PropTypes.object.isRequired
    };
    constructor(props) {
        super(props);
        this.state = {
            route: null
        }
    }
    changeScene = (path, name) => {
        const { drawer, navigator } = this.context;
        this.setState({
            route: path
        });
        navigator.to(path, name);
        drawer.closeDrawer();
    };
    render() {
        const { route } = this.state;
        return (
            <Drawer theme='light'>
                <Drawer.Header image={<Image source={require('./../img/nav.jpg')} />}>
                    <View style={styles.header}>
                        <Avatar size={80} image={<Image source={{ uri: "http://facebook.github.io/react-native/img/opengraph.png?2" }}/>} />
                        <Text style={[styles.text, COLOR.paperGrey50, TYPO.paperFontSubhead]}>React Native Material Design</Text>
                    </View>
                </Drawer.Header>

                <Drawer.Section
                    items={[{
                        icon: 'home',
                        value: 'Welcome',
                        active: !route || route === 'welcome',
                        onPress: () => this.changeScene('welcome'),
                        onLongPress: () => this.changeScene('welcome')
                    }]}
                />

                <Drawer.Section
                    title="Components"
                    items={[{
                        icon: 'face',
                        value: 'Avatars',
                        label: '12',
                        active: route === 'avatars',
                        onPress: () => this.changeScene('avatars'),
                        onLongPress: () => this.changeScene('avatars')
                    },
                    {
                        icon: 'label',
                        value: 'Subheaders',
                        label: '4',
                        active: route === 'subheaders',
                        onPress: () => this.changeScene('subheaders'),
                        onLongPress: () => this.changeScene('subheaders')
                    }]}
                />
                <Divider style={{ marginTop: 8 }} />
                <Drawer.Section
                    title="Config"
                    items={[{
                        icon: 'invert-colors',
                        value: 'Change Theme',
                        label: '24',
                        active: route === 'themes',
                        onPress: () => this.changeScene('themes'),
                        onLongPress: () => this.changeScene('themes')
                    }]}
                />
            </Drawer>
        );
    }
}

const styles = {
    header: {
        paddingTop: 16
    },
    text: {
        marginTop: 20
    }
};

**Comment by hramos** [comment] 2017-04-14 22:38
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-04-14 22:38 UTC
