### ISSUE TITLE
[Image][iOS and Android] Animated gifs are not working properly

### ISSUE THREAD

**Issue by mdluo** [facebook/react-native#8043] opened 2016-06-10 09:43 UTC
===
#### react-native `0.24.1` and react 0.14.5

\<Image\> with gif `source` wrapped in \<Text\> (inline image) don't move on both iOS and Android

Live sample:  https://rnplay.org/apps/89njTA

```javascript
<View>
  <Text>
    Sample Text
    <Image    // <-- Stay still on both platform
      style={{width: 100, height: 100}} 
      source={{uri: 'http://www.clicktorelease.com/code/gif/1.gif'}} />    
  </Text>
  <Image    // <-- Animated gif on both platform
    style={{width: 100, height: 100}} 
    source={{uri: 'http://www.clicktorelease.com/code/gif/1.gif'}} /> 
</View>
```

===

#### react-native `0.27.0` and react 15.0.2

Then I upgraded rn to 0.27.0, and inline gif image works fine on iOS. However, gif images on Android of both wrapped in \<Text\> and \<View\> don't even show up, just leaving a blank space of their size.

```javascript
<View>
  <Text>
    Sample Text
    <Image    // <-- Animated gif on iOS but blank space on Android
      style={{width: 100, height: 100}} 
      source={{uri: 'http://www.clicktorelease.com/code/gif/1.gif'}} />    
  </Text>
  <Image    // <-- The same for this one
    style={{width: 100, height: 100}} 
    source={{uri: 'http://www.clicktorelease.com/code/gif/1.gif'}} /> 
</View>
```

**Comment by charpeni** [comment] 2016-06-10 14:11
See this https://github.com/facebook/react-native/issues/7760#issuecomment-221898901

**Comment by charpeni** [comment] 2016-06-10 14:12
@facebook-github-bot duplicate #7760

**Comment by facebook-github-bot-9** [comment] 2016-06-10 14:12
@charpeni tells me this issue is a duplicate of #7760. Let's discuss there, closing this one.

**Closed by facebook-github-bot-9** 2016-06-10 14:12 UTC
Labels: Ran Commands
