### ISSUE TITLE
Keyboard congestion in oppo mobile phones!!!

### ISSUE THREAD

**Issue by ZHT131** [facebook/react-native#14523] opened 2017-06-15 02:45 UTC
### Keyboard congestion in oppo mobile phones!

For example, there are two pages of A and B, write a TextInput component respectively in the two page, when in the A page, click on the pop-up keyboard TextInput, and then close the keyboard, and then open the new page B, click on the pop-up TextInput keyboard, the keyboard is closed again, and then return to the A page, click TextInput cannot eject keyboard. The keyboard had blocked, when you press the standby button again and open the pop-up keyboard, ask the people encountered this problem? Hope to answer it.

![abc](https://user-images.githubusercontent.com/22323594/27163070-99f62db4-51b7-11e7-8d33-c61ede86592a.gif)
### Additional Information
* react-native:0.45.1
* react-navigation:1.0.0-bate.11

**Comment by ZHT131** [comment] 2017-06-15 02:51
This is also true in several closed Issues
[#12671](https://github.com/facebook/react-native/issues/12671)
[#12864](https://github.com/facebook/react-native/issues/12864)
[#14489](https://github.com/facebook/react-native/issues/14489)

**Comment by hramos** [comment] 2017-06-15 04:24
We really need more detailed reproduction steps, and most importantly, sample code. That's probably why those other issues were closed as well.

**Comment by ZHT131** [comment] 2017-06-15 04:44
@hramos  But here, as in GIF, there are only two simple pages, each containing a TextIput, and nothing else

**Comment by ZHT131** [comment] 2017-06-15 04:45
@hramos This problem can be reproduced in a OPPO cell phone

**Comment by ZHT131** [comment] 2017-06-15 04:51
## This is page A
`export default class tongcheng extends Component {
    render() {
        return (
            <View style={{ flex: 1 }}>
                <TextInput
                    style={{ height: 40, borderColor: 'gray', borderWidth: 1 }}
                />
                <TouchableOpacity onPress={()=>this.props.navigation.navigate('New')}>
                    <Text>open</Text>
                </TouchableOpacity>
            </View>
        );
    }
}`
## This is page B
`export default class New extends Component {
    render() {
        return (
           <View style={{ flex: 1 }}>
                <TextInput
                    style={{ height: 40, borderColor: 'gray', borderWidth: 1 }}
                />
            </View>
        );
  }
}`

# Navigation uses react-navigation

**Comment by ZHT131** [comment] 2017-06-15 04:59
After you open the keyboard and close it on the B page, return to the A page and click TextInput, then you can't open the keyboard

**Comment by hramos** [comment] 2017-06-15 15:46
Have you tested this on other devices (non-OPPO)? Does it reproduce on Snack?

**Comment by ZHT131** [comment] 2017-06-16 02:25
@hramos Other devices are normal, oppo has this problem

**Comment by ZHT131** [comment] 2017-06-16 02:29
@hramos It was also mentioned that Meizu mobile phone has this problem

**Comment by hramos** [comment] 2017-08-24 20:42
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Closed by hramos** 2017-08-24 20:42 UTC
Labels: Icebox

**Comment by ZhengZhiQI** [comment] 2017-12-18 02:12
I have solved by set window focus in java:
```
setFocusableInTouchMode(true);
setFocusable(true);
requestFoucus();
```
hope can help you.

**Comment by Gemmily** [comment] 2017-12-25 07:57
same problem
