### ISSUE TITLE
ReadableArray getMap pops the item out of the array.

### ISSUE THREAD

**Issue by SudoPlz** [facebook/react-native#8557] opened 2016-07-04 11:29 UTC
Thus if we run a for loop to iterate through all the maps within a ReadableArray, our array is left empty.

Now I'm not aware of a way to clone a ReadableArray, so I think there should be away to access the children of a ReadableArray without deleting them afterwards.

Is this a bug or is it intended behaviour?

**Comment by grabbou** [comment] 2016-07-29 19:14
CC: @cjhopman I can see you have a TODO in a native implementation of `getMap`. Maybe you have more details regarding this issue.

**Comment by cjhopman** [comment] 2016-08-01 04:37
I mean, it's intended behavior, but just because nobody wanted to take the time to implement behavior that makes more sense. My preference would be that getMap() (and similar) not pop out the item.

The issue is that these java-c++ hybrid objects all are set up so that the java object owns the underlying c++ object (and so the c++ object is deleted when there are no more references to the java object). To support getMap() and similar having the better behavior it would probably be easiest to in some way reference count (or strong java reference type ownership) the underlying outer folly::dynamic and keep pointers into it for the thing that you want.  That is, a ReadableNativeArray will have one strong reference into the outermost folly::dynamic and then some reference into the folly::dynamic that corresponds to that array.

Because of the way these are passed around, it is probably easiest to make the c++ part of these look something like:

  struct DynamicOwner {
    std::unique_ptr<folly::dynamic> obj;
  }

  struct JReadableNativeArray : HybridClass<JReadableNativeArray, ReadableArray> {
    std::shared_ptr<DynamicOwner> outer;
    folly::dynamic* obj;
  }

where obj is a pointer into outer (and in the constructed from c++ case, outer == obj).

**Comment by rigdern** [comment] 2016-08-16 06:48
I hit this bug as well. It's very surprising that `getMap` pops. I also noticed that the npm module [react-native-contacts made the same bad assumption](https://github.com/rt2zz/react-native-contacts/blob/8febdd9b310503ff403d4b463b6252d0dd6dbb66/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java#L69-L70) about the behavior of `getMap`.

@cjhopman did `getMap` use to behave differently? If yes, what's the first release of RN to include the popping behavior? Are there any other methods that also pop even though their names would suggest otherwise?

**Comment by cjhopman** [comment] 2016-08-16 23:38
@rigdern I'm not sure how long this has been the behavior of getMap (I think it's always been the behavior, but I haven't looked back to confirm that). I think only getMap() does this, all the others (get map/array from map/array) all create copies (which is also rather bad).

**Comment by cjhopman** [comment] 2016-08-17 00:26
But yeah, I still think that popping the map is crazy. We should just have getMap() create a copy like all the others. It's possible that for configuration of the bridge (i.e. creating the batched bridge config) making copies will be a significant perf hit, but we can just add a popMap() if that's the case.

**Comment by rigdern** [comment] 2016-08-17 00:44
@cjhopman I just did a quick test with a couple of versions of my app. It looks like the behavior of `getMap` did change:
  - [getMap in ~0.25](https://github.com/facebook/react-native/blob/a95405f4194480d22005df0ac1c32e44753d17be/ReactAndroid/src/main/jni/react/jni/OnLoad.cpp#L207-L211) does not pop
  - [getMap in 0.32.0-rc.0](https://github.com/facebook/react-native/blob/b00f70033a0a92f91d787a14c72bc3f7c8e98505/ReactAndroid/src/main/jni/xreact/jni/ReadableNativeArray.cpp#L79-L84) pops

I'm not sure exactly when the behavioral change occurred. If it was a recent change, I think the behavior should be switched back before doing a release to avoid breaking apps.

**Comment by cjhopman** [comment] 2016-08-24 00:29
This is fixed in https://github.com/facebook/react-native/commit/9a5d3bacb99275e952619ab142f4381008d13d89

**Comment by grabbou** [comment] 2016-08-24 13:25
Closing as @cjhopman points to a commit that fixes the issue described.

**Closed** 2016-08-24 13:24 UTC
