### ISSUE TITLE
How to fix the error "Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8." in React Native? 

### ISSUE THREAD

**Issue by wg-d** [facebook/react-native#33416] opened 2022-03-13 03:33 UTC
### Description

[admin@DF713 android % ./gradlew app:installDebug
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/admin/Downloads/ritehauler-user/android/app/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin 'com.android.internal.application'.
   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
     You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

I am running the command from zsh terminal.
Thanks.

### Version

0.67.2

### Output of `npx react-native info`

System:
    OS: macOS 11.6
    CPU: (4) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Memory: 64.71 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
    Yarn: 1.22.17 - ~/Downloads/ritehauler-user/node_modules/.bin/yarn
    npm: 6.14.14 - ~/.nvm/versions/node/v14.17.5/bin/npm
    Watchman: 2022.01.24.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/admin/.gem/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 28, 29, 32
      Build Tools: 29.0.2, 32.1.0
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8092744
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.2 => 0.67.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Run react-native run-android  in project root directory.

**Comment by cortinico** [comment] 2022-03-13 14:37
> Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.

As the message says, you need to run on Java 11. You're probably running on Java 1.8.

The environment setup page on our website explains how to install Java 11:
https://reactnative.dev/docs/next/environment-setup

Closing here, but feel free to reopen if the issue is not solved.

**Closed by cortinico** 2022-03-13 14:37 UTC
Labels: Platform: Android, Needs: Triage :mag:

**Comment by wg-d** [comment] 2022-03-13 16:24
Thanks! It's resolved now and I faced another issue.
https://github.com/facebook/react-native/issues/33417

**Comment by mMarcos208** [comment] 2022-04-20 18:24
Thanks @cortinico 

I updated jdk with flowing commands:

```
brew tap homebrew/cask-versions
brew install --cask zulu11
```

**Comment by muhammadashariabdillah24** [comment] 2022-04-27 12:38
Only for linux users

The first thing you have to do is install the JDK 11 package from oracle with the command

sudo apt-get install openjdk-11-jdk

Wait until the process is complete after that

type command

sudo apt-get update && sudo apt-get upgrade

and it worked

**Comment by iamabdulhaseeb** [comment] 2022-04-28 19:40
Thanks @mMarcos208 
`brew tap homebrew/cask-versions
brew install --cask zulu11`

this command worked for me.

**Comment by gowthamcodes** [comment] 2022-05-18 04:11
in gradle.properties, 
add following

org.gradle.java.home=C:/Program Files/Android/Android Studio/jre (refer to your path)
