### ISSUE TITLE
Border "position" inconsistent between platforms

### ISSUE THREAD

**Issue by rborn** [facebook/react-native#14206] opened 2017-05-26 12:15 UTC
Hi, 

### Description
When setting a border to a view, there are inconsistencies between ios and android.

It seems that the border position is inconsistent between Android and iOS.
On iOS the border is `inside` while on android is `center`.

Basically on android the border is going outside the view it belongs to, while on iOS it stays within the limits which is correct. In fact it seems that on android the view shrinks with the borderWidth/2.

This only happens when the border has a radius and it's very obvious only if the border has an `alpha < 1`.

Any way to avoid this? (the behaviour should be like on iOS)

![screen shot 2017-05-27 at 13 42 39](https://cloud.githubusercontent.com/assets/406409/26521218/67024d80-42e3-11e7-8118-e4e39023350f.png)
![screen shot 2017-05-27 at 13 42 06](https://cloud.githubusercontent.com/assets/406409/26521219/6711bf5e-42e3-11e7-9baa-8b72f65ea0f7.png)

### Reproduction Steps and Sample Code

Here is an [Expo demo](https://snack.expo.io/rkxGK5rZW)

But the code is very simple:
~~~
const styles = StyleSheet.create({
  box: {
    width:252,
    height:172,
    borderWidth:30,
    overflow:'hidden',
    // borderStyle:'dotted',
    borderColor: 'rgba(255,0,0,.50)',
    backgroundColor:'rgba(245,156,35,1)',
    borderTopLeftRadius: 4,
    borderTopRightRadius: 10,
    borderBottomLeftRadius: 21,
    borderBottomRightRadius: 56
  });
~~~

### Additional Information

* React Native version: 0.43 I believe, the example is with Expo 16.0
* Platform: both
* Development Operating System: OsX
* Dev tools: Expo

Thank you 😄

**Comment by hramos** [comment] 2017-05-26 21:58
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by rborn** [comment] 2017-05-27 11:50
Hi @hramos 
Thank you for replying but I really think it's a bug 😢 
I suppose you didn't have time to look at the demo so I'm attaching the next screenshots to be more clear what I mean:

( Please ignore the dashed border, is there to make the things even clearer) 
Basically on android the border is going outside the view it belongs to, while on ios it stays within the limits which is correct. In fact it seems that the view shrinks with the borderWidth/2.

Is this a known issue documented anywhere?
Thank you.

![screen shot 2017-05-27 at 13 42 39](https://cloud.githubusercontent.com/assets/406409/26521218/67024d80-42e3-11e7-8118-e4e39023350f.png)
![screen shot 2017-05-27 at 13 42 06](https://cloud.githubusercontent.com/assets/406409/26521219/6711bf5e-42e3-11e7-9baa-8b72f65ea0f7.png)

**Comment by hramos** [comment] 2017-05-30 17:58
If you'd like to file this as an issue, can you update your original post and make sure it follows the new issue template? It's the bit of text shown when you create a new issue. Otherwise your post reads like a question.

**Comment by rborn** [comment] 2017-05-31 08:19
@hramos done, thank you 😄

**Comment by hramos** [comment] 2017-08-16 03:09
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Closed by hramos** 2017-08-16 03:09 UTC
Labels: Android, Icebox

**Comment by brinkkemper** [comment] 2018-04-13 12:14
Any resolution though? This seems like fair bug is true.
