### ISSUE TITLE
[iOS] [RN-0.40] Conversion from value of type 'NSArray<RCTJSStackFrame *> *' to incompatible type 'NSArray<NSDictionary *> *'

### ISSUE THREAD

**Issue by PaulRBerg** [facebook/react-native#12118] opened 2017-01-30 07:24 UTC
Just updated to 0.40 and this brought a lot of issues to the table. I can't make the app compile in Xcode, I always get the following issue:
![snip20170130_2](https://cloud.githubusercontent.com/assets/8782666/22415211/e6993b8e-e6cd-11e6-8b45-6310941bbe8e.png)

Any ideas?

* React Native version: 0.40
* Platform: iOS
* Operating System: MacOS

**Comment by olliekav** [comment] 2017-01-30 15:15
+1

**Comment by ide** [comment] 2017-01-30 17:49
These are just analysis warnings, not compiler errors. You can get around it by setting your compiler to ignore these warnings as you would in any other Xcode project.

**Comment by mattsoftware** [comment] 2017-01-31 08:09
Very poor work-around I know, but you can add this around the code thats throwing the warning.

#ifndef __clang_analyzer__
<code for the analyzer to ignore>
#endif

**Comment by rh389** [comment] 2017-01-31 15:33
This was fixed in https://github.com/facebook/react-native/commit/40f2b1bbb7dfc37ddd7109c208050e3486455ba9 (will be in 0.42)

**Comment by dannyyaou** [comment] 2017-02-20 06:45
+1
@rh389 @maartenschumacher thx, but that does'nt help to fix the problem

**Comment by rh389** [comment] 2017-02-20 15:44
It can be safely ignored and shouldn't stop a build - what problem is it causing?

**Comment by hramos** [comment] 2017-07-26 05:45
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Closed by hramos** 2017-07-26 05:45 UTC
Labels: Icebox, iOS
