### ISSUE TITLE
[Packager] Packager does not start after upgrading to NPM 3.0 beta

### ISSUE THREAD

**Issue by frostney** [facebook/react-native#1758] opened 2015-06-26 15:43 UTC
After upgrading to NPM 3.0 beta (https://github.com/npm/npm/releases/tag/v3.0.0), I re-installed the `node_modules` through `npm install` in my React Native project. Everything showed up in the file system, but after calling `npm start` I get the error:
```
Could not find dependencies.
Ensure dependencies are installed - run 'npm install' from project root.
```
No matter how often I call `npm install` and `npm start`, the error persists.
This happens for me with both `0.6.0` and `0.7.0-rc`.

**Comment by jsierles** [comment] 2015-06-28 10:17
This happens because the packager is looking for react-native's dependencies in its own node_modules directory. In npm 3, all dependencies install flat in the top level node_modules.

https://github.com/facebook/react-native/blob/master/packager/packager.js#L18

I'd love to start using npm3 - will look into a PR.

**Comment by fatuhoku** [comment] 2015-07-18 09:03
This happens for `0.8.0-rc` as well. I thought NPM 3.0.x was needed for the latest release. Surprised to find there are issues!

**Comment by tachim** [comment] 2015-07-21 01:03
I just had this issue with react-native 0.6.0 and npm 2.13.0. The issue went away by upgrading to react-native 0.7.1 but there's probably a simpler solution

**Comment by brentvatne** [comment] 2015-07-21 01:25
@fatuhoku - not sure where you read that, npm 3 is not required for the new release, iojs is :smile:

We don't support npm 3 yet, help from the community on that would be great!

**Comment by globexdesigns** [comment] 2015-08-19 17:29
+1 for this issue. require statements should be updated to not include npm packages via relative paths.

**Comment by lightsofapollo** [comment] 2015-08-29 23:17
+1 hit this too would a simple require check be good enough ? A simple way to detect this would be to try to require some dep and throw the error if it was missing.

**Comment by eddiemonge** [comment] 2015-09-15 20:56
Its the framework trying to be too smart. [These lines](https://github.com/facebook/react-native/blob/master/packager/packager.js#L19-L27) are merely checking to see if `node_modules` is present. It doesn't need to do this check. If a dependency isn't there then require will throw an error. Could always monkey patch `require` to throw that message if the module isn't found.

**Comment by Stephen304** [comment] 2015-09-18 17:12
Another +1 for this issue. I'm on npm 3.3.3 and node 4.1.0.

**Comment by eddiemonge** [comment] 2015-09-18 18:56
I've been using my [Pull Request](https://github.com/facebook/react-native/pull/2732) since I submitted it with no problems so far. It's a simple seeming change so hopefully they can merge it soon and be done with this.

> require statements should be updated to not include npm packages via relative paths

Its not even that complicated since it already does that. Like I said, it merely tests for `node_modules` at a specific location, doesn't even save or use it from that location that I can tell.

**Comment by Jarema** [comment] 2015-09-18 19:28
+1. Same on node 4.0.0 and npm 3.3.3

**Comment by Stephen304** [comment] 2015-09-18 20:11
@eddiemonge I'm not sure how to use that PR because I'm not sure where the react-native files are... I should be able to just edit the matching file right?

**Comment by sethwklein** [comment] 2015-09-19 03:27
One way to work around this temporarily is to downgrade npm by running `npm install -g 'npm@<3'`.

**Comment by edge** [comment] 2015-09-20 18:27
+1. This is pretty troublesome.

**Comment by ide** [comment] 2015-09-20 22:09
The packager will be moved out into its own repo in the near future, and supporting npm 3 can happen then.

**Comment by vjeux** [comment] 2015-09-21 02:15
Yeah, the resolution algorithm of the packager needs to be upgraded for npm 3. Also, sadly `npm install` takes 3x more time for react-native :( https://github.com/npm/npm/issues/8826#issuecomment-141818982

**Comment by martinbigio** [comment] 2015-09-21 21:20
I've tested this on npm 3 and looks like the dependency resolution system works fine. I'll remove the check that makes ` packager.sh` fail on npm 3 (will be available next time we sync). Other than that doesn't seem there's any actionable item here.

**Comment by BerndWessels** [comment] 2015-09-23 10:09
Hi
Seems that this is still not working with Node 4 and NPM 3. Can you please let us know when this is fixed?
Cheers
Bernd

**Comment by antigirl** [comment] 2015-09-25 12:55
+1

**Comment by guoziyan** [comment] 2015-09-25 21:28
+1

**Comment by piotrblasiak** [comment] 2015-09-26 00:03
+1

**Comment by faurehu** [comment] 2015-09-26 00:25
I have node v4.0 and npm v3.3.4 and this issue also affects me.

**Comment by garrettmaring** [comment] 2015-09-26 01:43
+1 (still not working)

**Comment by ide** [comment] 2015-09-26 01:51
@amasad @martinbigio where are we at with moving the packager to another repo?

**Comment by nashpro** [comment] 2015-09-28 15:33
+1

**Comment by mschwartz** [comment] 2015-09-28 16:17
+1

**Comment by FaridSafi** [comment] 2015-09-28 16:24
+1

**Comment by koi646** [comment] 2015-09-28 17:13
+1

**Comment by nashpro** [comment] 2015-09-28 18:03
solved this problem with 
```
npm i react-native@0.11.3
npm rebuild
```

**Comment by HugoSTorres** [comment] 2015-09-28 18:29
+1

@nashpro I tried that, still got the same error. Just to confirm here's the output of `npm list react-native`:

    myapp@0.0.1 /Users/hugo/src/myapp
    └── react-native@0.11.3 

Running node 4.1.1 with npm 3.3.4

**Comment by oguzbilgic** [comment] 2015-09-29 23:19
+1

**Comment by bluesea** [comment] 2015-09-30 07:38
+1

**Comment by didierstockmans** [comment] 2015-09-30 07:41
same story, fixed it by downgrading npm to version 2.14.6

**Comment by tuanmai** [comment] 2015-09-30 17:24
+1

**Comment by ogonbat** [comment] 2015-09-30 19:24
same story
i have update to npm 3 and have the error
i have downgraded npm to npm@2.14.6 and still have the same error
this is the react native version
react-native@0.11.4
and node 4.1.1

have some solution?

**Comment by HugoSTorres** [comment] 2015-09-30 20:22
I can confirm @didierstockmans fix works. I downgraded npm to 2.14.6 and ran it without issue.

I then upgraded to react-native 0.11.4 and it still works. Still running node 4.1.1.

**Comment by eddiemonge** [comment] 2015-09-30 21:22
Downgrading is not a fix for this specific problem. There is a fix in https://github.com/facebook/react-native/commit/daba14264c9f0d29c0327440df25d81c2f58316c but it hasn't been released yet. You could install master from this repo and use that

**Comment by mkonicek** [comment] 2015-10-22 13:38
https://github.com/facebook/react-native/commit/daba14264c9f0d29c0327440df25d81c2f58316c will go out in 0.13 soon.

**Comment by HugoSTorres** [comment] 2015-10-22 13:55
@eddiemonge sorry I meant work around. Lol.

**Comment by grabbou** [comment] 2015-11-12 10:01
@mkonicek unfortunately it's not the only issue. It introduces naming collisions because it takes `react-tools` from some packages (e.g. immutable, ^0.11.0) and puts it in the root `node_modules` which conflicts with `react-native/node_modules/react-tools`. Not sure if there's any workaround to this issue apart from downgrading, which I don't like because of peerDependencies.

**Comment by mkonicek** [comment] 2015-11-12 17:07
Interesting, maybe @spicyj might know about react-tools?

**Comment by spicyj** [comment] 2015-11-12 17:14
immutable lists react-tools only as a dev dependency so `npm install immutable` won't install it and you shouldn't need it to use immutable:

https://github.com/facebook/immutable-js/blob/5138e1d37daa63c03142ef2e5a8b2076c250311e/package.json#L50

**Comment by grabbou** [comment] 2015-11-12 17:18
Ok, fair enough :) Might be coming from a different package then. I definitely don't get the `npm3` system behind node_modules structure, because even if I do `rm -rf ./node_modules/react-tools` - it still works.

**Comment by spicyj** [comment] 2015-11-12 17:22
(Eventually RN will depend on `react` directly and this won't be an issue even if you install react-tools.)

**Comment by mkonicek** [comment] 2015-11-13 15:14
:+1: nice!

**Comment by ide** [comment] 2015-11-19 06:25
This works with simple RN projects. External npm packages might cause trouble -- so if you encounter issues please test with a basic RN project with no extra dependencies.

**Closed by ide** 2015-11-19 06:25 UTC
Labels: Packager

**Comment by belvikram** [comment] 2015-12-22 18:47
Downgrading the npm@2.14.6 works for me.

**Comment by jdk89757** [comment] 2015-12-24 14:55
PATH: [Your Project]/node_modules/react-native/package/packager.js
SOLUTION: add'../..'  &  delete 'node_modules',
CODE:if (!fs.existsSync(path.resolve(__dirname, '../..', ''))) {
              console.log(
               '\n' + path.resolve(__dirname, '../..', '') +
              'Could not find dependencies.\n' +
              'Ensure dependencies are installed - ' +
              'run \'npm install\' from project root.\n'
               );
              process.exit();
             }

**Comment by austinkelleher** [comment] 2016-06-19 15:21
+1

**Comment by GinjiBan** [comment] 2016-07-08 17:29
+1
