### ISSUE TITLE
run js remotely in ios simluator can't debug project source js

### ISSUE THREAD

**Issue by castielLi** [facebook/react-native#14299] opened 2017-06-02 07:11 UTC
i am a freshman in react-native and i'm very enjoy developing with this tool. When i builded a demo in iOS and debug its js file by following the docs, things happened to me just difference from docs.  There are no my demo project files in source tab but only two js file at localhost:8081 root
1.debuggerworker.js
2 index.ios.bundle?platform=ios&dev=true&minify=false

also cmd+p could not find my source js. neither i edit debugger in js can hit the file.
everything runs very fine including console log but find source files.
even i can debug with index.ios.bunlexxx js file.And  i found all my source code just be compile in this file.

environment:
1. Chrome 58.0.3029.110 (64-bit) 
2. React Developer Tools 2.21
3. react-native-cli 2.0.1

appreciate any help.

**Comment by hramos** [comment] 2017-06-02 17:08
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-02 17:08 UTC
