### ISSUE TITLE
After calling scrollToLocation method of SectionList, scroll is jumping

### ISSUE THREAD

**Issue by hamidhadi** [facebook/react-native#22809] opened 2018-12-27 08:31 UTC
**UPDATE**
[Check this out](https://github.com/facebook/react-native/pull/22837)

I want to implement something like scrollspy on the web with section list.
I'm using `scrollToLocation` method. 
The problem is when scrolling is finished the scroll is jumping. I think it causes by loading previous rows. I don't know why this issue happens even when providing `getItemLayout` prop.
Here is a basic demo.

![demo4](https://user-images.githubusercontent.com/6258297/50472650-e7e57b80-09ce-11e9-9b1e-3790d0f9bbc8.gif)

**Comment by bartolkaruza** [comment] 2018-12-29 10:06
Looks like the effect you would see if `getItemLayout` is not implemented correctly. Can you post a reproducible demo?

**Comment by hamidhadi** [comment] 2018-12-29 10:30
@bartolkaruza I just created a repo on Gitlab [here](https://gitlab.com/hamidhadi/react-native-section-list-scroll-spy)

**Comment by danilobuerger** [comment] 2019-01-01 15:42
Possible duplicate of #20956

**Comment by jeffmon** [comment] 2019-01-04 22:00
I have some pretty deeply nested "list" components and I'm having the same issue. I noticed once I switch to a basic `View`, `Image`, and `Text` component with no expensive calculations, that jumping does not occur anymore. 

I'm thinking this issue correlates to having a "complex" repeating list component.

**Closed** 2019-01-14 20:05 UTC
Labels: Ran Commands, 🔶Components, 🔶Lists, 🔶SectionList, 🚫For Stack Overflow
