### ISSUE TITLE
Unexpected token ';' no stack error 

### ISSUE THREAD

**Issue by ChayanonSaelee** [facebook/react-native#32976] opened 2022-01-27 10:03 UTC
### Description

I try to run " npx react-native run-android " with my emulator I will create new metro terminal and build success but in my screen emulator show error Unexpected token ';' Unexpected token ';' no stack error no stack error  How I slove it ? 

![image](https://user-images.githubusercontent.com/69430930/151335563-011ffefc-5794-485a-a45f-e4941098d930.png)

### Version

react-native-cli: 2.0.1, react-native: 0.64.3 ,android version 11

### Output of `npx react-native info`

warn Package react-native-ios-context-menu has been ignored because it contains invalid configuration. Reason: Cannot find module 'react-native-ios-context-menu/package.json'
Require stack:
- /mnt/d/LndHub/BlueWallet/node_modules/react-native/node_modules/@react-native-community/cli/build/tools/config/resolveNodeModuleDir.js
- /mnt/d/LndHub/BlueWallet/node_modules/react-native/node_modules/@react-native-community/cli/build/tools/releaseChecker/index.js
- /mnt/d/LndHub/BlueWallet/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/start/runServer.js
- /mnt/d/LndHub/BlueWallet/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/start/start.js
- /mnt/d/LndHub/BlueWallet/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/index.js
- /mnt/d/LndHub/BlueWallet/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js
- /mnt/d/LndHub/BlueWallet/node_modules/react-native/cli.js
info Fetching system and libraries information...
System:
    OS: Linux 4.4 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 4.21 GB / 15.85 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.10 - /mnt/c/Users/NeayNie/AppData/Roaming/npm/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: ^0.64.3 => 0.64.3
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. first terminal : run " npm start " result :
![image](https://user-images.githubusercontent.com/69430930/151336483-55a9f66b-6031-4d7e-8743-502aad5ed106.png)

2. second terminal : run " npx react-native run-android " result :
![image](https://user-images.githubusercontent.com/69430930/151336571-9299d13f-ff50-4757-bcf8-1b8ed79de7e5.png)

3. found error !!

**Comment by hellforever** [comment] 2022-01-27 18:16
I got the same error on my Android 9 device, I am trying to update react-native version from 0.63 to 0.67.1, also updating a bunch of libraries due to compatibility issues.
![QQ20220127-0](https://user-images.githubusercontent.com/5683380/151418882-0c153028-b77c-4ccf-9da2-fad5bbb665e5.jpg)


System:
    OS: macOS 11.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 617.83 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.3 - ~/.nvm/versions/node/v14.18.3/bin/node
    Yarn: Not Found
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.3/bin/npm
    Watchman: 2022.01.17.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/fepc-412/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 28.0.3, 29.0.1, 29.0.2, 30.0.1, 30.0.2, 30.0.3, 31.0.0
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google APIs ARM 64 v8a, android-31 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8092744
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_291 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.1 => 0.67.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

  "dependencies": {
    "@bankify/redux-persist-realm": "0.1.3",
    "@farmersedge/react-native-geojson-to-svg": "1.1.3",
    "@google-cloud/translate": "4.1.3",
    "@react-native-community/art": "1.2.0",
    "@react-native-community/async-storage": "1.12.1",
    "@react-native-community/geolocation": "1.4.2",
    "@react-native-community/netinfo": "6.0.0",
    "@react-native-community/progress-bar-android": "1.0.4",
    "@react-native-community/progress-view": "1.3.1",
    "@react-native-community/slider": "2.0.9",
    "@react-native-firebase/analytics": "10.1.1",
    "@react-native-firebase/app": "8.4.7",
    "@react-native-firebase/crashlytics": "8.4.12",
    "@react-native-firebase/iid": "7.4.10",
    "@react-native-firebase/messaging": "7.9.2",
    "@react-native-firebase/perf": "7.4.10",
    "@react-native-mapbox-gl/maps": "8.4.0",
    "@redux-saga/delay-p": "1.0.1",
    "@turf/boolean-crosses": "6.0.1",
    "@turf/center-of-mass": "6.0.1",
    "@turf/turf": "5.1.6",
    "@welldone-software/why-did-you-render": "4.2.1",
    "array-flat-polyfill": "1.0.1",
    "art": "0.10.3",
    "assert": "2.0.0",
    "base64-image-loader": "1.2.1",
    "buffer": "5.6.0",
    "convert-units": "github:granduke/cab-convert-units#v2.3.4",
    "d3": "5.9.7",
    "d3-array": "2.2.0",
    "d3-scale": "3.0.0",
    "d3-shape": "1.3.5",
    "fbjs": "3.0.2",
    "geojson": "0.5.0",
    "geojson-tools": "0.2.2",
    "geostats": "github:simogeo/geostats",
    "lodash": "4.17.15",
    "memoize-one": "5.0.5",
    "moment": "2.24.0",
    "moment-timezone": "0.5.26",
    "native-fetch": "github:granduke/native-fetch",
    "react": "17.0.2",
    "react-dom": "16.8.6",
    "react-native": "0.67.1",
    "react-native-app-settings": "2.0.1",
    "react-native-base64": "0.0.2",
    "react-native-ble-plx": "2.0.3",
    "react-native-calendars": "1.200.0",
    "react-native-collapsible": "1.4.0",
    "react-native-config": "1.4.1",
    "react-native-datepicker": "1.7.2",
    "react-native-device-info": "5.5.6",
    "react-native-gesture-handler": "2.2.0",
    "react-native-i18n": "github:granduke/react-native-i18n",
    "react-native-image-crop-picker": "0.36.3",
    "react-native-image-picker": "1.0.1",
    "react-native-mapbox-drawing-tools": "github:granduke/react-native-mapbox-drawing-tools",
    "react-native-material-design": "github:granduke/react-native-material-design",
    "react-native-material-design-styles": "github:react-native-material-design/react-native-material-design-styles",
    "react-native-navigation": "7.25.1",
    "react-native-pager-view": "5.4.9",
    "react-native-pdf": "6.2.1",
    "react-native-permissions": "3.2.0",
    "react-native-svg": "9.5.3",
    "react-native-switch": "2.0.0",
    "react-native-tab-view": "3.1.1",
    "react-native-uuid": "1.4.9",
    "react-native-vector-icons": "8.1.0",
    "react-native-view-shot": "3.1.2",
    "react-native-zip-archive": "5.0.6",
    "react-redux": "7.1.0",
    "realm": "10.20.0-beta.1",
    "redux": "4.0.4",
    "redux-loop": "5.0.0",
    "redux-persist": "6.0.0",
    "redux-saga": "1.0.5",
    "reselect": "4.0.0",
    "rn-fetch-blob": "0.12.0",
    "supercluster": "4.1.1",
    "sync-storage": "0.4.2"
}

**Comment by cortinico** [comment] 2022-01-28 17:50
> react-native-cli: 2.0.1, react-native: 0.64.3 ,android version 11

You're on a really old RN version. Consider updating to 0.67.x and try again.

**Comment by ethanneff** [comment] 2022-02-01 18:57
You potentially have a semicolon within your JSX that is not wrapped around with a `<Text>` component

**Comment by hikaaam** [comment] 2022-02-19 16:41
same thing happens to me on an old project.
i comment my app.js and make a simple one still showing the same error

**Comment by willks** [comment] 2022-03-03 00:11
Why no stack trace to find out issue? It's a terrible framework and consistently blocks me with weird issues like this. No stack? Why not.

**Comment by tushar04** [comment] 2022-06-20 08:58
Any updates on this issue?

**Comment by halojamalu** [comment] 2022-07-29 10:27
Try update :
1. Nodejs LTS
2. Update React Native
3. Update SDK

**Comment by willks** [comment] 2022-07-29 13:36
I think I have to take back my comments. It seems I had a rogue character from a copy & paste - but it took me a good time to figure out. However RN could benefit to at least show us at what point parsing failed.

@tushar04 With my issue, I had to go back to previous commit that worked, once I found that, I did a diff to find out where things went wrong and in the end, it was a rogue character. However, the error screen did not give ANY indication as to what file failed to parse. Frustrating. But in the end, I slayed that dragon thanks to GIT. Without it, I'd be screwed

**Comment by cortinico** [comment] 2022-07-29 14:56
> You potentially have a semicolon within your JSX that is not wrapped around with a `<Text>` component

Closing as previously mentioned, you're on a old RN version. The solution suggested by @ethanneff is correct + without your code is impossible to help further

**Closed by cortinico** 2022-07-29 14:56 UTC
Labels: Platform: Linux, Needs: Triage :mag:

**Comment by jhiin** [comment] 2022-10-31 15:20
i have same problem becuse  i use tailwind and tailwind.json empty This is the cause of the problem
