### ISSUE TITLE
v0.46 React Packager is not working

### ISSUE THREAD

**Issue by webyonet** [facebook/react-native#14836] opened 2017-07-05 17:59 UTC
```
/Users/webyonet/Deneme/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328
        throw e;
        ^

ReferenceError: Unknown plugin "transform-runtime" specified in "/Users/webyonet/Deneme/node_modules/regenerator-transform/package.json" at 0, attempted to resolve relative to "/Users/webyonet/Deneme/node_modules/regenerator-transform" (While processing preset: "/Users/webyonet/Deneme/node_modules/babel-preset-react-native/index.js")
    at /Users/webyonet/Deneme/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/webyonet/Deneme/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/webyonet/Deneme/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/webyonet/Deneme/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/Users/webyonet/Deneme/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/webyonet/Deneme/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/webyonet/Deneme/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
Process terminated. Press <enter> to close the window
```

**Comment by Amurmurmur** [comment] 2017-07-05 18:35
+1
Also I face another problem when upgrading babel-preset-react-native to 2.1.0 
```
undefined is not an object (evaluating 'regeneratorRuntime.mark')
<unknown>
    
loadModuleImplementation
    require.js:174:12
guardedLoadModule
    require.js:126:36
_require
    require.js:110:24
<unknown>
    index.js:2
loadModuleImplementation
    require.js:174:12
guardedLoadModule
    require.js:126:36
_require
    require.js:110:24
<unknown>
    configureStore.js:19
loadModuleImplementation
    require.js:174:12
guardedLoadModule
    require.js:126:36
_require
    require.js:110:24
<unknown>
    index.js:32
loadModuleImplementation
    require.js:174:12
guardedLoadModule
    require.js:126:36
_require
    require.js:110:24
<unknown>
    index.android.js:10
loadModuleImplementation
    require.js:174:12
guardedLoadModule
    require.js:119:45
_require
    require.js:110:24
global code
   
```

**Comment by grabbou** [comment] 2017-07-05 19:46
Looks like it's duplicate of #14530

**Closed by grabbou** 2017-07-05 19:46 UTC
