### ISSUE TITLE
React-native 0.44.2 and react-native-fbsdk 0.6.0 troubles.

### ISSUE THREAD

**Issue by edcalderin** [facebook/react-native#14344] opened 2017-06-06 18:19 UTC
Hi Guys. I was working with RN 0.37.x and react-native-fbsdk 0.5.0. 
It was neat but I upgraded my project to RN 0.44.2 recently and fbsdk 0.6.0 as well but it didn't work. I had to uninstall it and to install react-native-facebook-login. In android Studio console, I saw some errors:

Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

I have been editing build.gradle according to others forums about this. But I could not solve this. 
In the meantime, I am using RN Facebook Login but It is limited. FBSDK has a lot of advantages.

**Comment by hramos** [comment] 2017-06-06 19:17
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-06 19:17 UTC
