### ISSUE TITLE
Error running react-native upgrade on MacOS [1.9]

### ISSUE THREAD

**Issue by adamtwiss** [facebook/react-native#5668] opened 2016-02-01 15:47 UTC
Upgrading from react-native 1.7 to 1.9 on MacOS 11.11.4 (Beta) fails when upgrading a project

`$ react-native upgrade
/Users/adam/Documents/Versio4/XXXXXXX/node_modules/react-native/local-cli/setup_env.sh: line 8: ulimit: open files: cannot modify limit: Operation not permitted
child_process.js:464
    throw err;
`

The reason it errors is that setup_env.sh tries to do:

`ulimit -n 4096`

On my MacOS I can't as a non-root user increase the ulimit above 2048

```
Adams-MacBook-Pro:tmp adam$ ulimit -n 2048
Adams-MacBook-Pro:tmp adam$ ulimit -n 4096
-bash: ulimit: open files: cannot modify limit: Operation not permitted
Adams-MacBook-Pro:tmp adam$ ulimit -n 2049
-bash: ulimit: open files: cannot modify limit: Operation not permitted
```

Editing the setup_env.sh to use 2048 fixes the issue.

Full platform:
Node v4.2.2
MacOS 10.11.4 Beta (15E27e)

**Comment by bestander** [comment] 2016-02-05 11:21
@nicklockwood @vjeux do you think 2048 would be enough for RN to run by default?
Kind of reasonable not to require root permissions to run RN.

**Comment by vjeux** [comment] 2016-02-05 11:30
Yeah we don't want to require sudo to run react native. Can you send a diff to use 2048 and see if anyone complains about it? :p

**Comment by bestander** [comment] 2016-02-05 12:14
duplicate https://github.com/facebook/react-native/issues/5314

**Comment by bestander** [comment] 2016-02-05 12:17
Created diff D2905603

**Comment by donaldpipowitch** [comment] 2016-03-08 20:35
I just stumbled over the same problem. Do you know when this will be released? Thanks.

**Comment by bestander** [comment] 2016-03-08 20:38
It should be in 0.21 already

**Comment by donaldpipowitch** [comment] 2016-03-08 21:08
Strange. I'll check my version tomorrow, but I installed it just two hours ago. Thanks so far.

**Comment by bestander** [comment] 2016-03-08 23:40
sure, this setting is definitely in 0.21: https://github.com/facebook/react-native/blob/0.21-stable/local-cli/setup_env.sh

**Comment by donaldpipowitch** [comment] 2016-03-09 13:44
I don't know why this happened. I use 0.21 and you're right, I have "ulimit -n 2048", too.

**Comment by bestander** [comment] 2016-03-09 13:59
And what message do you get when you run it?

**Comment by donaldpipowitch** [comment] 2016-03-09 15:53
I had `ulimit: open files: cannot modify limit: Operation not permitted` yesterday, but switched to a root user since then. I can't reproduce it now easily, sorry.

**Comment by bestander** [comment] 2016-03-09 15:56
No worries.
I'll close the task.
This question would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Closed by bestander** 2016-03-09 15:56 UTC

**Comment by wtfil** [comment] 2016-03-10 11:10
Hi!
I faced with the same problem. For some reason, my machine allows me to call `ulimit` only for 1024 without root access, so [this](https://github.com/facebook/react-native/blob/0.21-stable/local-cli/setup_env.sh#L9) limitation does not work for me.
I found the fix which could be useful for others with same problem. All you need is to all following lines into you `.profile` file

```bash
function ulimit() { builtin ulimit -n 1024; }
export -f ulimit
```

This will redefine ulimit calls in order to call it with 1024 limit all the time.

Pls, note that this overwriting will ignore all arguments, so use `builtin ulimit` for real ulimit

**Comment by jskye** [comment] 2016-05-30 15:15
I had previously defined a limit in bash_profile
`ulimit -n 1024`
when i removed it it fixed the error for me.

**Comment by jsg2021** [comment] 2016-11-02 16:27
macOS 10.12.1 doesn't let you `ulimit -n 2048` without `sudo`.  I've commented out the offending line to get by. My `.profile` already raises my `ulimit -n 1024`.

**Comment by jacob-meacham** [comment] 2016-11-29 07:05
I believe the actual issue is that `ulimit -n 2048` sets both the soft and the hard file limits, and OS X only lets you lower the hard limit once it's been set:

```
$ ulimit -Hn
unlimited
$ ulimit -n
256
$ ulimit -n 10000
$ ulimit -n
10000
$ ulimit -Hn
10000
$ ulimit -n 10001
-bash: ulimit: open files: cannot modify limit: Operation not permitted
$ ulimit -n 9999
$ ulimit -n 10000
-bash: ulimit: open files: cannot modify limit: Operation not permitted
```

On my system (OS X 10.11.6), `ulimit -Hn` is by default unlimited. A more elegant solution here might be to only set `ulimit -Sn 2048` and only do so if the hard limit is high enough. If the hard limit is too low, I don't think a non-root shell will be able to change it regardless, so an error should be thrown.

**Comment by wtfil** [comment] 2016-11-30 21:10
@jacob-meacham just try my solution :)
