### ISSUE TITLE
Prevent Flatlist from scrolling when new items are added.

### ISSUE THREAD

**Issue by ragnorc** [facebook/react-native#13607] opened 2017-04-21 11:31 UTC
When adding data to the Flatlist (e.g. subscriptions) it scrolls down leading to a very bad UX.
Any idea on how this could be solved?

**Comment by hramos** [comment] 2017-04-24 13:09
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Closed by hramos** 2017-04-24 13:09 UTC

**Comment by chinalwb** [comment] 2018-05-24 08:39
I think I find the cause (but still not find solution). For my use case, append items to the end of the list, it is no problem that the FlatList won't jump, i.e.: the FlatList doesn't scroll.

When scrolling up to load previous page I prepend items to the start of the list, the FlatList will scroll to top.

I think the cause is when FlatList do render, the Diff algorithm realizes that the top items have been changed so it re-renders the top items, hence the FlatList 'scrolls to top', in fact when scrolling up the FlatList, the FlatList itself is at its top, and after re-render it still 'keeps at top'. But to the end users, the scroller cannot keep the previous top item at the screen top, that's why the user feels FlatList is scrolling.

Hope this can be improved in the next release.

Thanks.
