### ISSUE TITLE
Cmd-R not refreshing?

### ISSUE THREAD

**Issue by tehfailsafe** [facebook/react-native#306] opened 2015-03-27 04:00 UTC
Everything loads up fine, example are are running smoothly, but if I make a change in the JS file and hit Cmd-R in the simulator, nothing happens. Did I forget something?

xcode - Version 6.2 (6C131e)
simulator - Version 8.2 (553.8
watchman - 3.0.0
node - 0.12.1

**Comment by tischler** [comment] 2015-03-27 04:17
+1 -- I've even deleted the folder, re-created a new folder, run the app, and I'm still seeing my changes from before the delete. 

xcode - Version 6.2 (6C131e)
yosemite - 10.10.1
node 0.12.0

**Comment by amasad** [comment] 2015-03-27 04:20
Can you try restarting your computer? The FileWatcher might be in a bad state

**Comment by tehfailsafe** [comment] 2015-03-27 04:22
I restarted a few times, uninstalled/reinstalled node and watcher, and now reinstalling xcode.

**Comment by tjwudi** [comment] 2015-03-27 04:24
It works fine for me. Make sure to use the latest stable version of XCode, and install XCode Command Line Tools.

**Comment by tehfailsafe** [comment] 2015-03-27 04:26
Installing xcode from the app store, should I grab a different one?

**Comment by amasad** [comment] 2015-03-27 04:29
I doubt Xcode is the problem here. If the app opens in the simulator and renders it's probably something in the packager. This is a long shot but maybe the packager is run in in the wrong directory. Can you go to the directory you're changing and manually start the packager? You can use react-native start

**Comment by tehfailsafe** [comment] 2015-03-27 04:37
I was running `npm start` from react-native root, but even starting it deeper in still pacakages from the main directory.

```
> react-native@0.2.1 start /Users/me/react/react-native
> ./packager/packager.sh

```

**Comment by tehfailsafe** [comment] 2015-03-27 04:37
Also watching some others on youtube and it seems there's a blink or flash in the simulator on the reload. When I hit Cmd-R there's no blink or anything, nothing happens at all.

**Comment by amasad** [comment] 2015-03-27 04:39
Are there any logs in your terminal? It should say something about the
requests and time taken.

If there aren't any then there might be something wrong with the Cmd r
itself

**Comment by tehfailsafe** [comment] 2015-03-27 04:42
When I make a change in the editor I see this in the terminal:
```
[21:46:15] <START> find dependencies
[21:46:15] <END>   find dependencies(5ms)
[21:46:15] <START> transform
[21:46:15] <END>   transform(189ms)
```

But that is when I save from the editor, before attempting to hit Cmd-R

**Comment by tehfailsafe** [comment] 2015-03-27 04:44
hitting Cmd-R in the simulator produces no logs in the terminal or in xcode console.

**Comment by montogeek** [comment] 2015-03-27 04:51
You have to hit Cmd+R twice, every time :)

**Comment by tehfailsafe** [comment] 2015-03-27 04:53
I am spamming it 50 times, doubt that's the problem... :)

**Comment by tehfailsafe** [comment] 2015-03-27 04:55
Fun note, learned from @jordwalke on twitter to use the shake gesture to bring up the dev dialog, and reloading from there works great. Also enabling live reload now works by just saving the JS file without touching Cmd-R.

**Comment by tehfailsafe** [comment] 2015-03-27 05:40
Turns out it's a simple hardware keyboard setting in the simulator menu. Never would have thought to check that, especially since things like alt-drag work for multi-touch emulation without this setting enabled. 

![image](https://cloud.githubusercontent.com/assets/1388454/6863127/03837824-d409-11e4-9251-e05bd31d978f.png)

**Comment by sahrens** [comment] 2015-03-27 05:44
Glad you could figure it out. What to send a PR with the tip?

**Comment by tehfailsafe** [comment] 2015-03-27 07:15
Sure first thing in the morning!

**Comment by imWildCat** [comment] 2015-03-27 08:48
@tehfailsafe Fixed, thanks!

**Comment by vjeux** [comment] 2015-03-27 17:00
#326 is related. If you don't have a qwerty/azerty keyboard layout, it won't work

**Comment by rywhee** [comment] 2015-03-28 05:31
Unfortunately, the keyboard toggle does not fix the issue for me. Have tried that as well as uninstalls and reboots. Two near identical machines:

Yosemite 10.10.2
Xcode 6.2
iOS Simulator 8.2
node v0.12.1

First run of the project:

```
[12:26:54 AM] <START> request:/index.ios.bundle
[12:26:54 AM] <START> find dependencies
[12:27:00 AM] <END>   find dependencies(6496ms)
[12:27:00 AM] <START> transform
[12:27:00 AM] <END>   transform(202ms)
```

Cmd-R (2x) in the simulator causes a screen flash, as if a reload is happening; but new content is not pulled in.

**Comment by amasad** [comment] 2015-03-28 05:37
@rywhee no `<END> request:/index.ios.bundle` event?

**Comment by rywhee** [comment] 2015-03-28 05:41
@amasad my bad, I snipped it!

```
[12:39:38 AM] <START> request:/index.ios.bundle
[12:39:38 AM] <START> find dependencies
[12:39:44 AM] <END>   find dependencies(5888ms)
[12:39:44 AM] <START> transform
[12:39:45 AM] <END>   transform(234ms)
[12:39:45 AM] <END>   request:/index.ios.bundle(6140ms)
```

**Comment by amasad** [comment] 2015-03-28 05:44
So it seems like the simulator is requesting the package and receiving it. Maybe the packager isn't picking up your changes. Try stopping the packager and starting it manually via `react-native start` in your project dir.

**Comment by rywhee** [comment] 2015-03-28 06:06
Thanks @amasad. Unfortunately, a manual start does not resolve the issue for me.

FYI - I have had to bump MAX_WAIT_TIME in FileWatcher to avoid the 'Watcher took too long to load' error...

**Comment by amasad** [comment] 2015-03-28 06:13
Does it at least pick up changes between stopping and starting the packager? (Trying to make sure it's not a file watcher issue)

**Comment by rywhee** [comment] 2015-03-28 06:26
@amasad yep, when stopping then re-starting the packager; changes are picked up fine. It's just the live reload that's not happening.

**Comment by jordanfloyd** [comment] 2015-03-28 19:36
@rywhee are you using sublime text 3? I had to disable atomic save for refresh to work properly.

**Comment by rywhee** [comment] 2015-03-29 22:55
My issue refresh issue was related to watchman permissions.... solved here

facebook/watchman#90

**Comment by vjeux** [comment] 2015-04-01 02:35
Closing this issue for now since it seems resolved, please re-open if you face it again

**Comment by amasad** [comment] 2015-04-01 02:36
If you have time please update the troubleshooting page with the your workarounds/fixes.

**Closed by vjeux** 2015-04-01 02:35 UTC

**Comment by tehfailsafe** [comment] 2015-04-01 17:25
updated to add the watchman permissions fix.
https://github.com/facebook/react-native/pull/585

**Comment by eyaleizenberg** [comment] 2015-06-26 06:19
@rywhee Thanks dude! Solved all my issues!

**Comment by rywhee** [comment] 2015-07-14 19:23
@eyaleizenberg :thumbsup: - happy coding!

**Comment by Tom-E** [comment] 2015-11-07 05:44
I am not able to reload through command+r.
Shake + Reload, or Shake + Live Reload both work... Just the manual reload does not. Any ideas?
Thanks

**Comment by siemiatj** [comment] 2016-01-18 09:57
In case somebody is using Dvorak layout, you need to refresh with Cmd+P.

**Comment by Bob1993** [comment] 2016-01-20 07:23
Maybe it's just caused by the different build mode，you need to change the build mode into debug if it is release mode currently. command+R and command+D is the special key combination while you debug the program with simulator....the concrete step is : [In Xcode 6 & 7] Choose Product -> Scheme -> Edit Scheme. Change the Build Configuration under the Info tab.

**Comment by dvisco** [comment] 2016-03-02 19:08
@Bob1993 many thanks, was as simple such!

**Comment by Bob1993** [comment] 2016-03-03 02:39
@dvisco It's my pleasure ~

**Comment by sashafklein** [comment] 2016-03-15 23:07
@Bob1993 Ditto -- forgot I had to change the scheme back to debug!

**Comment by Bob1993** [comment] 2016-03-16 01:57
@sashafklein Hahahaha...

**Comment by JakeLin** [comment] 2016-03-20 22:25
@tehfailsafe save my life. 👍

**Comment by xcchcaptain** [comment] 2016-04-18 03:27
@jordanfloyd  thanks ,solved my problem
does that mean autosave will disable live loading  ?

**Comment by devyu** [comment] 2016-05-02 04:47
@tehfailsafe thanks, it is work!

**Comment by zire** [comment] 2016-08-04 02:14
@Bob1993 Thank you so much! Yes changing the mode to **Debug** fixed this refresh issue for me.

**Comment by JJMoon** [comment] 2016-12-06 12:02
I have this issue.  
Mac os : Sierra.
watchman : 4.7.0
react-native : 0.38.1
react-native-cli: 1.2.0
xcode : 8.1
I did watchman install --HEAD ...  not work..

**Comment by ngothanhtai** [comment] 2017-10-09 03:35
Quit the simulator and start again. Works for me.

**Comment by struggle-fish** [comment] 2018-02-12 07:19
![image](https://user-images.githubusercontent.com/12171471/36086503-c883db18-1007-11e8-8fbe-db582c6fdad1.png)

**Comment by luizdias** [comment] 2018-02-25 03:28
In my case I could only get cmd+R working after disabling "Send Menu Shortcuts to Device":

<img width="630" alt="captura de tela 2018-02-25 as 00 24 59" src="https://user-images.githubusercontent.com/713058/36637795-a6c0f8b6-19c2-11e8-9bea-3a86d112ae69.png">

**Comment by yanush** [comment] 2018-03-03 14:44
in my case my build configuration was set to release. changing it to debug solved the problem

**Comment by aloifolia** [comment] 2018-05-04 10:48
For me, nothing works. The build configuration is set to debug and "Send Menu Shortcuts to Device" is disabled...
