### ISSUE TITLE
[0.42.0] Missing Pod specs

### ISSUE THREAD

**Issue by Maxwell2022** [facebook/react-native#12670] opened 2017-03-03 02:33 UTC
I'm not sure I should report this here or in Yoga repo.

Running `pod install` with react-native 0.42.0 I got the following error:

> None of your spec sources contain a spec satisfying the dependency: `Yoga (= 0.42.0.React)`.

![screen shot 2017-03-03 at 1 30 41 pm](https://cloud.githubusercontent.com/assets/670701/23535948/dbc74690-0015-11e7-94f1-ce429b05ca76.png)

**Comment by rgoldiez** [comment] 2017-03-03 21:05
Same issue.

**Comment by ide** [comment] 2017-03-03 23:33
The official fix for this is to explicitly specify the location of React Native's copy of Yoga in your Podfile:

```rb
# In Podfile
react_native_path = "node_modules/react-native"
pod "React", :path => react_native_path
pod "Yoga", :path => "#{react_native_path}/ReactCommon/yoga"
```

Would anyone like to submit a docs PR?

**Comment by Maxwell2022** [comment] 2017-03-05 07:51
@ide I'd be happy to do it, where would that documentation live? I don't think there is any section in the docs for Pods installation at the moment, except in troubleshooting?

I think it would a good idea to edit the release message (https://github.com/facebook/react-native/releases/tag/v0.42.0) to mention it too (@grabbou).

**Comment by ide** [comment] 2017-03-05 17:54
Git grep for where there are docs on using cocoa pods, iirc there is a docs page that explains what the podfile should look like.

**Comment by hramos** [comment] 2017-07-25 22:58
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Closed by hramos** 2017-07-25 22:58 UTC
Labels: Icebox
