### ISSUE TITLE
[Text] has superfluous lines on iPhone Plus

### ISSUE THREAD

**Issue by blockspeiser** [facebook/react-native#10682] opened 2016-11-01 17:28 UTC
### Description

![Image of superfluous lines](http://i.imgur.com/2r0ngFU.jpg)

Our app in progress is showing undesired grey lines on the top and/or right of every Text component when run on an iPhone Plus.  The bug does not reproduce on the simulator, only on device. 

When inspecting the Text components, any component that has a non-integer width or height will show a line like this. A non-integer width adds a border to the right, a non-integer height adds a border to the top. 

If I explicitly set a height for each Text component to an integer value I can prevent the top borders, but the width of the Text depends on the length of it content which I cannot control. In the attached image the texts that say "Commentary | 24" and "Tanakh | 2" have the same structure/styling -- but the difference in text length causes one to have a border right and the other not.

This seems related to this issue: https://github.com/facebook/react-native/issues/2018

Any suggestions for workarounds are greatly appreciated as well. This issue is ugly and pervasive. 

### Reproduction

The bug is present in this app: https://github.com/Sefaria/Sefaria-iOS

### Additional Information

* React Native version: 0.35.0
* Platform: iOS on devices with PixelDensity 3, does not reproduce on simulator.

**Comment by lacker** [comment] 2016-11-30 21:00
Do you have a simple repro app like a rnplay.org link that reproduces this? That's not using a simulator.

**Comment by blockspeiser** [comment] 2016-12-21 20:58
After better grokking the details discussed in the issue https://github.com/facebook/react-native/issues/2018, we saw also that the line disappear from when the Launch screen is reenabled. So we have a work around to the bug, but seems to confirm the issue still exists when the Launch screen is disabled.

**Comment by asivura** [comment] 2017-02-21 02:10
I have the same issue on iPhone 7plus when app does not support 3x resolution.
React native 0.41.0.

Workaround: add {backgroundColor: 'transparent'} to Text style.

**Comment by Virsaviya** [comment] 2017-02-28 21:04
I'm on 0.35 and @asivura's solution works.  Thanks!  Have you found a more scalable workaround, by any chance?

**Comment by asivura** [comment] 2017-02-28 21:11
@Virsaviya I have not. I hope it will be fixed in next versions or we'll stop to use compatibility mode for iOS app in the feature. But it might be an effect from another more complicated issue. I don't know.

**Comment by hramos** [comment] 2017-07-20 22:35
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/text-has-superfluous-lines-on-iphone-plus

**Closed by hramos** 2017-07-20 22:35 UTC
Labels: Icebox

**Comment by mrdezzods** [comment] 2017-08-31 12:57
We are experiencing the same issue. We tested on iPhone 6 and iPhone 7 plus. We get the exact same issue in iPhone 7 plus.

**Comment by calvinlang** [comment] 2017-12-23 17:36
I am having the exact same issue. Never happens on simulator only on real iOS Plus devices.

**Comment by kidequinox** [comment] 2018-01-10 18:15
+1

**Comment by allthetime** [comment] 2018-05-25 04:03
Why is this closed? Has it been fixed on latest version? It's present on v0.51 at least and I'm curious what the fix is.

**Comment by dakiquang** [comment] 2018-06-22 03:44
Thanks @asivura. It works for me. I got the same problem in iPhone 6Plus and 7Plus
