### ISSUE TITLE
keyboardDidShow listener does not fire in 'horizontal' orientation

### ISSUE THREAD

**Issue by neilzhengzx** [facebook/react-native#22305] opened 2018-11-16 02:10 UTC
- [Yes] Review the documentation: https://facebook.github.io/react-native
  - [Yes] Search for existing issues: https://github.com/facebook/react-native/issues
  - [Yes] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
 React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 23.02 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 9.8.0 - /usr/local/bin/node
      Yarn: 1.6.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        Build Tools: 19.0.3, 19.1.0, 21.1.0, 21.1.1, 21.1.2, 22.0.1, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.3
        API Levels: 17, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 

## Description
when the app in horizontal, keyboardDidShow not work. when change to Vertical,its work.

## Reproducible Demo
this.keyboardDidShow = Keyboard.addListener('keyboardDidShow', () => {
      console.log('its show');
    });

**Comment by neilzhengzx** [comment] 2018-11-16 03:17
[skip envinfo]

**Comment by hramos** [comment] 2018-12-14 21:41
Can you add more information? It's not clear from the description what the problem is. What were you expecting to happen, and how did the actual result deviate from those expectations?

**Comment by neilzhengzx** [comment] 2018-12-18 08:11
when the app in horizontal,  Keyboard.addListener can't get callback.

**Comment by dulmandakh** [comment] 2019-03-19 15:09
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy

**Closed by dulmandakh** 2019-03-19 15:09 UTC
Labels: API: Keyboard, Platform: Android, Type: Bug Report
