### ISSUE TITLE
Android: Live regions

### ISSUE THREAD

**Issue by amarlette** [facebook/react-native#30857] opened 2021-02-03 22:45 UTC
## Description
- This seems to exist as a prop, but is not functioning properly according to the documentation. 
- It only seems to exist on <View> and only seems to announce changes to the View's accessibilityLabel, not its descendant elements.

## React Native version:
v0.63

**Comment by blavalla** [comment] 2021-02-18 21:47
I can no longer reproduce the issue here, this property seems to be functioning correctly.
Snack example link - https://snack.expo.io/9nyaxiJSK

I think we can close this one out.

**Closed** 2021-02-18 21:48 UTC
Labels: Accessibility, Accessibility Team - Evaluated, Needs: Triage :mag:, Platform: Android
