### ISSUE TITLE
WebView Crashes app when you zoom fully in or out

### ISSUE THREAD

**Issue by aidan2129** [facebook/react-native#13338] opened 2017-04-06 11:40 UTC
I tried using the Webview on when i zoom out/in on any site fully it crashes the app every time.

**Comment by hramos** [comment] 2017-04-06 17:44
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-04-06 17:44 UTC

**Comment by aidan2129** [comment] 2017-04-07 08:29
@hramos Sorry about that i have updated this one and created a new issue like you said here https://github.com/facebook/react-native/issues/13374
