### ISSUE TITLE
[RN 0.36] crash at RCTImageLoader dequeueTasks

### ISSUE THREAD

**Issue by RichardJing** [facebook/react-native#10731] opened 2016-11-04 05:41 UTC
### Description
Crash report contains only one line: 
```
[RCTImageLoader dequeueTasks]_block_invoke (RCTImageLoader.m:254)
```
code at [RCTImageLoader](https://github.com/facebook/react-native/blob/0.36-stable/Libraries/Image/RCTImageLoader.m)
```
 (void)dequeueTasks
{
  dispatch_async(_URLRequestQueue, ^{
    // Remove completed tasks
    for (RCTNetworkTask *task in self->_pendingTasks.reverseObjectEnumerator) {
      switch (task.status) {
        case RCTNetworkTaskFinished:
          [self->_pendingTasks removeObject:task];
          self->_activeTasks--;
          break;
        case RCTNetworkTaskPending:
          break;
        case RCTNetworkTaskInProgress:
          // Check task isn't "stuck"
          if (task.requestToken == nil) {
            RCTLogWarn(@"Task orphaned for request %@", task.request);
            [self->_pendingTasks removeObject:task];
            self->_activeTasks--;
            [task cancel];  //  **** Line 254 at here **** //
          }
          break;
      }
    }

```

### Reproduction
Can not find a certain way to trigger this crash 

### Additional Information

* React Native version: 0.36.0
* Platform: iOS 10.0.1, iPhone 6s

**Comment by gitim** [comment] 2016-11-04 14:51
It is the same issue as in https://github.com/facebook/react-native/issues/10433#issuecomment-256744358.

**Comment by brentvatne** [comment] 2016-11-06 18:23
Indeed, dupe of #10433

**Closed by brentvatne** 2016-11-06 18:23 UTC

**Comment by huitsing** [comment] 2016-12-02 06:26
https://github.com/facebook/react-native/issues/10433 was closed with a fix that addresses some image loading crashes, but not this crash, FYI. Should it be re-opened, or should this issue be re-opened?
