### ISSUE TITLE
New react-native projects fail to start

### ISSUE THREAD

**Issue by SeanRog** [facebook/react-native#33834] opened 2022-05-14 02:16 UTC
### Description

New react-native projects fail to start.

I do this with 3 different windows machines and get the same error.

error in the CMD:
error Android project not found. Are you sure this is a React Native project? If your Android files are located in a non-standard location (e.g. not inside 'android' folder), consider setting `project.android.sourceDir` option to point to a new location.
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.

when I open with android studio, i get this build error (during sync):
React Native CLI failed to determine Android project configuration. This is likely due to misconfiguration. Config output:

[root:D:\repos\DeepLinkingApp1, reactNativePath:D:\repos\DeepLinkingApp1\node_modules\react-native, dependencies:[:], commands:[[name:log-ios, description:starts iOS device syslog tail], [name:run-ios, description:builds your app and starts it on iOS simulator, examples:[[desc:Run on a different simulator, e.g. iPhone SE (2nd generation), cmd:react-native run-ios --simulator "iPhone SE (2nd generation)"], [desc:Pass a non-standard location of iOS directory, cmd:react-native run-ios --project-path "./app/ios"], [desc:Run on a connected device, e.g. Max's iPhone, cmd:react-native run-ios --device "Max's iPhone"], [desc:Run on the AppleTV simulator, cmd:react-native run-ios --simulator "Apple TV"  --scheme "helloworld-tvOS"]], options:[[name:--simulator <string>, description:Explicitly set simulator to use. Optionally include iOS version between parenthesis at the end to match an exact version: "iPhone 6 (10.0)", default:iPhone 13], [name:--configuration <string>, description:Explicitly set the scheme configuration to use, default:Debug], [name:--scheme <string>, description:Explicitly set Xcode scheme to use], [name:--project-path <string>, description:Path relative to project root where the Xcode project (.xcodeproj) lives., default:ios], [name:--device [string], description:Explicitly set device to use by name.  The value is not required if you have a single device connected.], [name:--udid <string>, description:Explicitly set device to use by udid], [name:--no-packager, description:Do not launch packager while building], [name:--verbose, description:Do not use xcbeautify or xcpretty even if installed], [name:--port <number>, default:8081], [name:--terminal <string>, description:Launches the Metro Bundler in a new window using the specified terminal path.]]], [name:log-android, description:starts logkitty], [name:run-android, description:builds your app and starts it on a connected Android emulator or device, options:[[name:--root <string>, description:[DEPRECATED - root is discovered automatically] Override the root directory for the android build (which contains the android directory), default:], [name:--variant <string>, description:Specify your app's build variant, default:debug], [name:--appFolder <string>, description:[DEPRECATED â€“ use "project.android.appName" in react-native.config.js] Specify a different application folder name for the android source. If not, we assume is "app"], [name:--appId <string>, description:Specify an applicationId to launch after build. If not specified, `package` from AndroidManifest.xml will be used., default:], [name:--appIdSuffix <string>, description:Specify an applicationIdSuffix to launch after build., default:], [name:--main-activity <string>, description:Name of the activity to start, default:MainActivity], [name:--deviceId <string>, description:builds your app and starts it on a specific device/simulator with the given device id (listed by running "adb devices" on the command line).], [name:--no-packager, description:Do not launch packager while building], [name:--port <number>, default:8081], [name:--terminal <string>, description:Launches the Metro Bundler in a new window using the specified terminal path.], [name:--tasks <list>, description:Run custom Gradle tasks. By default it's "installDebug"], [name:--no-jetifier, description:Do not run "jetifier" â€“ the AndroidX transition tool. By default it runs before Gradle to ease working with libraries that don't support AndroidX yet. See more at: https://www.npmjs.com/package/jetifier.], [name:--active-arch-only, description:Build native libraries only for the current device architecture for debug builds., default:false]]]], assets:[], healthChecks:[], platforms:[ios:[:], android:[:]], project:[ios:[sourceDir:D:\repos\DeepLinkingApp1\ios, folder:D:\repos\DeepLinkingApp1, pbxprojPath:D:\repos\DeepLinkingApp1\ios\DeepLinkingApp1.xcodeproj\project.pbxproj, podfile:D:\repos\DeepLinkingApp1\ios\Podfile, podspecPath:null, projectPath:D:\repos\DeepLinkingApp1\ios\DeepLinkingApp1.xcodeproj, projectName:DeepLinkingApp1.xcodeproj, libraryFolder:Libraries, sharedLibraries:[], plist:[], scriptPhases:[]], android:null]]

### Version

0.68.2

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
    Memory: 4.13 GB / 15.93 GB
  Binaries:
    Node: 14.17.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8309675
    Visual Studio: Not Found
  Languages:
    Java: 11.0.11 - C:\Program Files\jdk-11.0.11\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.2 => 0.68.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

cmd:
react-native init DeepLinkingApp1
cd DeepLinkingApp1
react-native run-android

**Comment by hafiz-sameed** [comment] 2022-05-14 12:04
I am also facing the same issue. Any help would be appreciated.

**Comment by cortinico** [comment] 2022-05-14 12:13
Closing as it's a duplicate of #33835

**Closed by cortinico** 2022-05-14 12:13 UTC
Labels: Needs: Triage :mag:

**Comment by hafiz-sameed** [comment] 2022-05-14 12:16
I'm also facing the same issue. Any solution?

**Comment by ClenildoCardoso** [comment] 2022-05-14 16:40
Solução:
npm i glob@7.2.0

Vê se dá certo
