### ISSUE TITLE
FlatList does not accept (number) zero or empty string items

### ISSUE THREAD

**Issue by josvos** [facebook/react-native#13578] opened 2017-04-19 11:16 UTC
When using plain numbers or strings as items (in the "data" list property), rendering FlatList results in an error when encountering number 0 or string ''.  The error is "No item for index X" where X is the index of the 0 or '' in the list.  Examples where the error is "No item for index 2" are data={[-2, -1, 0, 1, 2]} and data={['a', 'b', '']}.

**Comment by Lizhooh** [comment] 2017-04-20 02:35
I have encountered this situation
Now the solution is to turn Number to String

```js
<Text>{`${count}`}</Text>
```

**Comment by hramos** [comment] 2017-04-25 13:35
Dupe of #12905. Try the workaround above.

**Closed by hramos** 2017-04-25 13:35 UTC

**Comment by rightaboveit** [comment] 2017-09-20 17:48
@Lizhooh's solution didn't work for me as I had a data source of empty URIs for Images, and received the 'No item for index X'

How I fixed it was for my images to just pass in a string 'blank' and check like so.
```
source={(imgSource != 'blank') ? {uri: imgSource} : undefined}
```
