### ISSUE TITLE
Bug in Movies example

### ISSUE THREAD

**Issue by findjashua** [facebook/react-native#477] opened 2015-03-30 05:07 UTC
In the movies example:
1. click into a movie's detail page
2. click back into the list view 
3. enter text in search bar
4. the list of movies updates, but the images don't

**Comment by barrettcook** [comment] 2015-03-30 23:13
Looks like a duplicate of https://github.com/facebook/react-native/issues/89

**Closed** 2015-05-31 17:40 UTC
