### ISSUE TITLE
ListHeaderComponent in SectionList is not sticky

### ISSUE THREAD

**Issue by max-zu** [facebook/react-native#20809] opened 2018-08-23 09:51 UTC
## Environment
```
  React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
      CPU: x64 Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz
      Memory: 153.75 MB / 15.36 GB
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 10.9.0 - /usr/bin/node
      Yarn: 1.9.4 - /usr/bin/yarn
      npm: 6.2.0 - /usr/bin/npm
    npmPackages:
      react: ^16.3.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
```

## Description
ListHeaderComponent is not sticky and it scrolls as other Section Headers. How to fix it on top of the list ?

## Reproducible Demo
https://snack.expo.io/HkRGmWhIX

**Comment by dulmandakh** [comment] 2018-08-29 10:40
This is expected behavior, not a bug. So closing this issue.

**Closed by dulmandakh** 2018-08-29 10:40 UTC
Labels: :large_orange_diamond:Lists, :small_blue_diamond:Linux

**Comment by max-zu** [comment] 2018-09-03 19:06
As for me, it looks very strange if this is expected behavior. Espesially if compare SectionList with FlatList, where ListHeaderComponent is always on top and does not scroll with other list data.

**Comment by hakankaradis** [comment] 2019-02-11 18:51
use `stickyHeaderIndices={[0]}` to make the `ListHeaderComponent` sticky

**Comment by matteocollina** [comment] 2019-02-14 12:06
@hakankaradis it works for sections of SectionList but not for `ListHeaderComponent`
