### ISSUE TITLE
Exception is thrown in the code, but it works normally

### ISSUE THREAD

**Issue by iamdurui** [facebook/react-native#14217] opened 2017-05-27 01:15 UTC
when I create a native module in Android, throwing an exception , it is Method threw 'com.facebook.react.bridge.ObjectAlreadyConsumedException' exception. Cannot evaluate com.facebook.react.bridge.WritableNativeMap.toString()
my code is:
array=new WritableNativeArray();
for(int i=0;i<fileList.size();i++){
WritableMap map=new WritableNativeMap();
map.putString("uri","file://"+fileList.get(i).getAbsolutePath());
map.putString("fileName",fileList.get(i).getName());
map.putInt("size", (int) fileList.get(i).length());
array.pushMap(map);
}
callback.invoke(array);

    React Native version: 0.39.0
    Platform: Android
    Development Operating System: Windows
    Dev tools: Android Studio version 2.1.2,com.android.tools.build:gradle:2.2.3, buildToolsVersion "24.0.2"
![b727ed32-41f9-11e7-9312-2ef694d2ff31](https://cloud.githubusercontent.com/assets/16399401/26516687/0f44dad4-42bd-11e7-8786-6dd1812bdda1.png)
![fd21e568-41f9-11e7-8e9c-1b19c1b69d50](https://cloud.githubusercontent.com/assets/16399401/26516688/0f44d868-42bd-11e7-8a39-a9337e3047d6.png)

when i >0; the exception is thrown, I guess it is to be caused by the code(WritableMap map=new WritableNativeMap() ), Thanks!
    Although the error is appeared, but it is not crash, I want to be given a solution ,thanks

**Comment by hramos** [comment] 2017-05-30 18:15
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-05-30 18:15 UTC

**Comment by rochapablo** [comment] 2018-01-04 11:06
@iamdurui, did you solve the issue?
