### ISSUE TITLE
React native The app references non-public selectors in Payload

### ISSUE THREAD

**Issue by ajouve** [facebook/react-native#35025] opened 2022-10-19 09:49 UTC
### Description

I have the following issue when I upload my React Native app to the app store

```
The app references non-public selectors in Payload/AppGeolocNative.app/AppGeolocNative: getAuthorizationStatus:, isPassthrough, newSocketQueueForConnectionFromAddress:onSocket:, onSuccess:, relativeSize, removeValuesForKeys:completion:, socket:didAcceptNewSocket:, socket:didConnectToHost:port:, socket:didConnectToUrl:, socket:didReadData:withTag:, socket:didReadPartialDataOfLength:tag:, socket:didReceiveTrust:completionHandler:, socket:didWriteDataWithTag:, socket:didWritePartialDataOfLength:tag:, socket:shouldTimeoutReadWithTag:elapsed:bytesDone:, socket:shouldTimeoutWriteWithTag:elapsed:bytesDone:, socketDidCloseReadStream:, socketDidDisconnect:withError:, socketDidSecure:, spanArray, spanArray_Count, strikeThrough, underline
```

I do not really understand what is the issue, everything is working ok, this is just a warning

### Version

0.70.0

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 309.92 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    Watchman: 2022.09.12.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/ajouve/.rvm/gems/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.0 => 0.70.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Archive and then distribute iOS app

### Snack, code example, screenshot, or link to a repository

<img width="745" alt="8FX2T" src="https://user-images.githubusercontent.com/2337492/196658042-e12d942e-4fe5-4c43-acf7-b5b653743418.png">

**Comment by cortinico** [comment] 2022-10-19 17:43
Essentially a duplicate of https://github.com/facebook/react-native/issues/31507
You should be able to use one of the solution suggested in the linked issue 👍

**Closed by cortinico** 2022-10-19 17:43 UTC
Labels: Needs: Triage :mag:
