### ISSUE TITLE
Image URL with an apostrophe causes complete app crash

### ISSUE THREAD

**Issue by paramaggarwal** [facebook/react-native#1069] opened 2015-04-30 02:24 UTC
An <Image> component with `source.uri` set as `http://www.example.com/Last-week’s-best-dressed-ladies.jpg` causes the React Native app to crash completely. The crash happens at this point: https://github.com/facebook/react-native/blob/862d9fba09046b6ca82bcc75197de69cbfb8fa41/Libraries/Image/RCTImageDownloader.m#L72 where `cacheKey` comes as `nil` and hence attempting to insert in dictionary with `nil` key causes exception and crash.

`cacheKey` comes `nil` because attempting to do `[NSURL urlWithString:@"http://www.example.com/Last-week’s-best-dressed-ladies.jpg"]` returns a `nil` because `NSURL` refuses to parse the URL as it contains a `’` character. Not showing an image is cool, but crashing on an arbitrary URL string isn't.

We have two ways around this. I believe we need to take care of both.

1. `nil` check on cacheKey and the immediate output of converting to `NSString` URL to `NSURL`.
2. Doing a `[urlString stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding]` on the input string. Unclear if modifying the URL is ok like this, hence just a suggestion.

**Comment by brentvatne** [comment] 2015-04-30 04:26
@paramaggarwal - this is a dupe of #914 I believe.

**Closed by brentvatne** 2015-04-30 04:26 UTC

**Comment by paramaggarwal** [comment] 2015-04-30 04:54
Yes, the issue is a duplicate, but this one causes a full app crash, so we need a `nil` check on `cacheKey` till a proper fix is in place.

**Comment by binlaniua** [comment] 2015-05-02 03:52
```javascript
http://manhua1017.122-228-171-12.cdndm5.com/a/aphorism格言/aphorism格言_CH01/01.jpg?cid=70452&key=7ffad26a265c2a3b5910818c9f4d37c3
```
has the same problem

NSURL is nil in the xcode debug console
