### ISSUE TITLE
Appearance addChangeListener handler is called when app goes to background with wrong color scheme

### ISSUE THREAD

**Issue by rosskhanas** [facebook/react-native#28525] opened 2020-04-04 09:51 UTC
## Description

A handler function of `Appearance.addChangeListener` is triggered when the app goes to the background. It also has a wrong `colorScheme` value.

## React Native version:

```
System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Memory: 92.24 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.13.0 - /usr/local/bin/node
    Yarn: 1.12.1 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.2, 28.0.3, 29.0.2
      System Images: android-23 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.1 => 0.62.1 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce

1. Register `Appearance.addChangeListener` at the root of the app (I use it with react-native-navigation).

```
Appearance.addChangeListener(({ colorScheme }) => {
  console.log(colorScheme);
});
```

2. Move the app to the background.

## Expected Results
No theme changed.

**Comment by rosskhanas** [comment] 2020-04-15 13:06
Here is a repo: https://github.com/rosskhanas/react-native-appearance-bug

Once the app goes to the background it logs 2 rows - 2 different values to the console - `light`, and `dark`.

**Comment by AntoinedeChassey** [comment] 2020-04-23 08:13
+1, having the same issue !

**Comment by rosskhanas** [comment] 2020-07-25 11:44
Not stale

**Comment by manuhook** [comment] 2020-07-30 09:02
The problem is on iOS only.
When backgrounding the app, perhaps due to a bug on iOS 13 the user interface style changes to the opposite color scheme and then back to the current color scheme immediately afterwards. The best solution is to debounce the notification calls by 10ms like they did on react-native-appearance.

`  dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0,01 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
    [[NSNotificationCenter defaultCenter] postNotificationName:RCTUserInterfaceStyleDidChangeNotification
                                                        object:self
                                                      userInfo:@{
                                                        RCTUserInterfaceStyleDidChangeNotificationTraitCollectionKey: self.traitCollection,
                                                      }];
  });`

**Comment by david-cako** [comment] 2020-08-07 02:21
Definitely still seeing this.  Moved to [expo/react-native-appearance](https://github.com/expo/react-native-appearance) for now.

**Comment by justincbeck** [comment] 2020-08-26 12:25
With this code in my App.js, I am seeing the extra calls but not the flash back and forth between themes:
`
const systemScheme = useColorScheme();
  const themeObject = systemScheme === 'light' ? light : dark;

  const toggleTheme = useCallback((colorScheme) => {
    const statusBarTheme = colorScheme === 'light' ? 'dark' : 'light';
    StatusBar.setBarStyle(`${statusBarTheme}-content`);
  }, []);

  useEffect(() => {
    Appearance.addChangeListener(({ colorScheme }) => {
      toggleTheme(colorScheme);
    });
    return () => {
      Appearance.removeChangeListener();
    };
  }, [toggleTheme]);
`
Hope that helps someone.

**Comment by Macrow** [comment] 2020-09-30 01:25
I have the same problem in iOS.

**Comment by jasonaibrahim** [comment] 2020-10-29 22:58
@Macrow your workaround helped. thank you

here it is as a hook (and in typescript) so others can drop this in and use this in lieu of the rn `useColorScheme` hook

```typescript jsx
import { Appearance, ColorSchemeName, useColorScheme as _useColorScheme } from 'react-native';
import { useEffect, useState } from 'react';
import { throttle } from 'lodash';

// Workaround for https://github.com/facebook/react-native/issues/28525
export default function useColorScheme(): NonNullable<ColorSchemeName> {
  const [colorScheme, setColorScheme] = useState(_useColorScheme());

  useEffect(() => {
    const onColorSchemeChange = async (preferences: Appearance.AppearancePreferences) => {
      setColorScheme(preferences.colorScheme);
    };

    Appearance.addChangeListener(throttle(onColorSchemeChange, 1000, {
      leading: false,
      trailing: true
    }));

    return () => {
      Appearance.removeChangeListener(onColorSchemeChange);
    };
  }, []);

  return colorScheme as NonNullable<ColorSchemeName>;
}
```

**Comment by CalebLovell** [comment] 2021-04-21 22:52
Thanks @jasonaibrahim, I really didn't want to fool with this nonsense today. That makes it easy! 🙌

**Comment by mrsimply** [comment] 2021-05-16 12:51
Dump question, isn't it the easiest way to just call `Appearance.getColorScheme()` when the Listener fires? Works well for me without a cumbersome timer...

```ts
  const initAppearanceListener = () => {
    const listener: Appearance.AppearanceListener = ({ colorScheme }) => {
      setColorScheme(Appearance.getColorScheme());
    };
    Appearance.addChangeListener(listener);
    return () => Appearance.removeChangeListener(listener);
  };
```

**Comment by Codelica** [comment] 2021-05-29 03:18
@mrsimply you could, although I'm not sure what ignoring the colorScheme that's sent in really buys.   Are you not seeing the listener fired twice with the wrong and then correct color scheme when the app is backgrounded? 

 I definitely do, so for now have just been ignoring the colorScheme listener calls when AppState says things are backgrounded.

**Comment by marcshilling** [comment] 2021-06-11 01:05
> Dump question, isn't it the easiest way to just call `Appearance.getColorScheme()` when the Listener fires? Works well for me without a cumbersome timer...

This worked for me, just ignoring the argument passed into the function

**Comment by monomichael** [comment] 2021-07-19 07:54
> Here is a repo: https://github.com/rosskhanas/react-native-appearance-bug
> 
> Once the app goes to the background it logs 2 rows - 2 different values to the console - `light`, and `dark`.

I believe this is a feature on iOS 13 and above. It does this to take screenshots of the app for the App Switcher in case color scheme changes.

**Comment by outaTiME** [comment] 2021-08-12 03:50
> Dump question, isn't it the easiest way to just call `Appearance.getColorScheme()` when the Listener fires? Works well for me without a cumbersome timer...
> 
> ```ts
>   const initAppearanceListener = () => {
>     const listener: Appearance.AppearanceListener = ({ colorScheme } /* <-- ignore */) => {
>       setColorScheme(Appearance.getColorScheme());
>     };
>     Appearance.addChangeListener(listener);
>     return () => Appearance.removeChangeListener(listener);
>   };
> ```

Sorry, but as I say in the following link, it keeps happening very randomly with your workaround:

https://github.com/expo/expo/issues/10815#issuecomment-897325894

**Comment by komik966** [comment] 2021-08-29 14:54
Results of my investigation:

This happens, because RN subscribes to changes inside `traitCollectionDidChange`. iOS toggles to both light and dark schemes to make light and dark snapshot of the application. More here: https://stackoverflow.com/a/63372828
It confirms @monomichael 's suggestion.

https://github.com/facebook/react-native/blob/b51a99c73cc4fbcbb03c97f92b7f7f166493538f/React/CoreModules/RCTAppearance.mm#L120-L124

https://github.com/facebook/react-native/blob/b51a99c73cc4fbcbb03c97f92b7f7f166493538f/React/Base/RCTRootView.m#L363-L373

**Comment by martsie** [comment] 2021-10-20 09:15
This issue broke our Facebook login because we were rebooting the app to load dark mode theme mid login when the Facebook app took focus to do OAuth. Pretty difficult to troubleshoot.

**Comment by gunnartorfis** [comment] 2021-11-03 20:07
This is still happening in React Native 0.66.1. 
I'm not using any listeners, just the useColorScheme hook. 

If I go to the device's home screen and open the app again (without closing entirely), the app flashes for a second with dark appearance although the system scheme is set as light.

**Comment by Jay-flow** [comment] 2021-11-05 04:36
> @Macrow your workaround helped. thank you
> 
> here it is as a hook to use in lieu of the rn `useColorScheme` hook. I also used `setTimeout` instead of `throttle`
> 
> ```ts
> import { Appearance, ColorSchemeName } from 'react-native';
> import { useEffect, useRef, useState } from 'react';
> 
> export default function useColorScheme(delay = 500): NonNullable<ColorSchemeName> {
>   const [colorScheme, setColorScheme] = useState(Appearance.getColorScheme());
> 
>   let timeout = useRef<NodeJS.Timeout | null>(null).current;
> 
>   useEffect(() => {
>     Appearance.addChangeListener(onColorSchemeChange);
> 
>     return () => {
>       resetCurrentTimeout();
>       Appearance.removeChangeListener(onColorSchemeChange);
>     };
>   }, []);
> 
>   function onColorSchemeChange(preferences: Appearance.AppearancePreferences) {
>     resetCurrentTimeout();
> 
>     timeout = setTimeout(() => {
>       setColorScheme(preferences.colorScheme);
>     }, delay);
>   }
> 
>   function resetCurrentTimeout() {
>     if (timeout) {
>       clearTimeout(timeout);
>     }
>   }
> 
>   return colorScheme as NonNullable<ColorSchemeName>;
> }
> ```

As of November 5, 2021
Even if there is a delay, the light value is also returned to me.

Is there any other solution?


https://github.com/facebook/react-native/issues/28525#issuecomment-897327174
The same issue for this solution.

**Comment by KrifaYounes** [comment] 2021-12-08 20:33
there is a patch package for this issues ?

**Comment by emrekaranfil** [comment] 2021-12-26 09:01
I started having this problem.

**Comment by DavinAhn** [comment] 2022-02-16 15:19
The theme change in App Switcher is not applied immediately, and response is slow when entering foreground, but it is resolved.

But I want it to be solved in react-native.

```ts
import { useEffect, useMemo, useState } from 'react';
import { AppState, AppStateStatus, ColorSchemeName, useColorScheme as _useColorScheme } from 'react-native';
import { useSubscription } from 'use-subscription';

export const useAppState = (): AppStateStatus => {
  const subscription = useMemo(
    () => ({
      getCurrentValue: () => AppState.currentState,
      subscribe: (callback: () => void) => {
        const appStateSubscription = AppState.addEventListener('change', callback);
        return () => appStateSubscription.remove();
      },
    }),
    [],
  );
  return useSubscription(subscription);
};

export const useColorScheme = (): NonNullable<ColorSchemeName> => {
  const colorScheme = _useColorScheme() as NonNullable<ColorSchemeName>;
  const [currentScheme, setCurrentScheme] = useState(colorScheme);
  const appState = useAppState();

  useEffect(() => {
    if (appState === 'active') {
      setCurrentScheme(colorScheme);
    }
  }, [appState, colorScheme]);

  return currentScheme;
};
```

**Comment by hrdyjan1** [comment] 2022-04-13 11:14
https://reactnative.dev/docs/usecolorscheme
This hook could help someone.

**Comment by jrhager84** [comment] 2022-08-04 08:58
Any fixes?

**Comment by cyim02** [comment] 2022-08-12 03:52
+1 The issue still persists in RN0.69+

**Comment by zhumingcheng697** [comment] 2022-10-03 18:21
The only way to 100.00% fix the flashing as of right now seems to be what @komik966 suggested in https://github.com/facebook/react-native/issues/28525#issuecomment-907805294: refactor every color with [`DynamicColorIOS`](https://reactnative.dev/docs/dynamiccolorios), which I assume passes the color values for all appearances down to the OS and let the OS pick the right color value for the color mode, instead of listening for color mode changes and swapping the color in React Native.

I have refactored my project with `DynamicColorIOS` and now the app also transitions very nicely when the color mode changes, but it requires a lot of additional work as `DynamicColorIOS` is only supported in iOS and libraries like React Navigation also don’t fully support it (https://github.com/react-navigation/react-navigation/issues/10891), so such refactoring may not be practical for large complex projects.

https://user-images.githubusercontent.com/31050761/193649332-f2211749-d1f7-461b-8a8a-1b474bdda38b.mp4

> ### Conclusion:
> Use `DynamicColorIOS`, it will:
> 
> * get rid of UI flashing effect when switching to background
> * properly update app switcher snapshot

**Comment by komik966** [comment] 2022-10-04 07:42
@zhumingcheng697 Have you tried to change OS color scheme via OS settings like shown on the recording in this comment https://github.com/mattermost/mattermost-mobile/pull/5635#pullrequestreview-736553295 ? It should also work perfectly.

**Comment by zhumingcheng697** [comment] 2022-10-04 16:53
@komik966 Very glad that you asked! I thought it would, and it almost did, but there were two minor cases where the `DynamicColorIOS` colors were not updated correctly in the app switcher, specifically:
1. the custom border color I set for React Navigation header and tab bar
2. the custom border color I set for [NativeBase](https://nativebase.io/) `Input` and `Select` components

Not sure if it is because `borderColor`s are being handled differently, since all my other `color`s and `backgroundColor`s are being handled perfectly fine in both React Navigation and NativeBase.

https://user-images.githubusercontent.com/31050761/193877709-07496d89-63e2-40e8-a407-c0b7c9d9859e.MP4

At the end, I chose to use the same color for the borders under both light and dark mode to avoid the flashing when going to the app switcher.

**Comment by noumantahir** [comment] 2022-11-09 12:14
> https://reactnative.dev/docs/usecolorscheme This hook could help someone.

Experiencing flashing with useColorScheme hook as well..

"react-native": "0.70.4",

**Comment by s123121** [comment] 2023-04-06 11:07
2 years passed and this bug still haunted me every other day

**Comment by efstathiosntonas** [comment] 2023-08-02 11:54
this worked for me:

```tsx
import React, { useState } from "react";
import { Appearance, ColorSchemeName } from "react-native";
import debounce from "lodash/debounce";

// This hook is from https://github.com/facebook/react-native/issues/28525
export function useColorScheme(): NonNullable<ColorSchemeName> {
  const [colorScheme, setColorScheme] = useState(Appearance.getColorScheme());

  const initAppearanceListener = () => {
    const listener: Appearance.AppearanceListener = () => {
      debounce(
        () => {
          setColorScheme(Appearance.getColorScheme());
        },
        200,
        { leading: false, trailing: true }
      );
    };
    const changeListener = Appearance.addChangeListener(listener);
    return () => changeListener.remove();
  };

  React.useEffect(() => {
    initAppearanceListener();
  }, []);

  return colorScheme as NonNullable<ColorSchemeName>;
}
```

**Comment by imransilvake** [comment] 2023-08-11 18:38
I solved it finally 🎉.

```
import { useColorScheme as useNativeWindColorScheme } from 'nativewind';
import { AppState, useColorScheme } from 'react-native';

const Root = () => {
	const currentColorScheme = useColorScheme();
	const { colorScheme, setColorScheme } = useNativeWindColorScheme();
	const isDarkTheme = colorScheme === GlobalSchemeEnum.DARK;
	const LightTheme = { dark: !isDarkTheme, colors: ThemeNavigationLightColors };
	const DarkTheme = { dark: isDarkTheme, colors: ThemeNavigationDarkColors };
	const theme = isDarkTheme ? DarkTheme : LightTheme;

	useEffect(() => {
		const subscription = AppState.addEventListener('change', (state) => {
			const isActive = state === 'active';
			if (!isActive) return;
			currentColorScheme && setColorScheme(currentColorScheme);
		});
		return () => subscription.remove();
	}, [colorScheme, setColorScheme, currentColorScheme]);

	{/* Navigation */}
	<NavigationContainer theme={theme}>
		<App />		
	</NavigationContainer>
};

AppRegistry.registerComponent(appName, () => Root);
```

Let me know if it doesn't work!

**Comment by blueberry6401** [comment] 2023-08-25 09:21
2023, latest version, and this bug is still there.
My (workaround) solution is using debounce.

**Comment by russeg** [comment] 2023-08-29 16:48
wow how is this bug still not fixed. i remember having this same bug in flutter, but there the issue was tagged, reproed, triaged, and fixed in less than 12 hours. 

anyway, thanks for the many and varied workarounds.

**Comment by jrhager84** [comment] 2023-08-30 07:27
It's kind of sad how many persistent bugs just sit for years without much notice. Oh well... :/

**Comment by bitcrumb** [comment] 2023-08-30 07:35
Imho, you could argue if it is a bug or not, since the behavior follows the underlying iOS framework behavior. However, it does feel as unwanted behavior.

That being said, it is easily remediated by just checking if the change happens in the foreground. In our codebase we just query the current AppState in the listener and only if it is equal to "foreground" we act upon it.

**Comment by jrhager84** [comment] 2023-08-30 07:45
> Imho, you could argue if it is a bug or not, since the behavior follows the underlying iOS framework behavior. However, it does feel as unwanted behavior.
> 
> 
> 
> That being said, it is easily remediated by just checking if the change happens in the foreground. In our codebase we just query the current AppState in the listener and only if it is equal to "foreground" we act upon it.

But if someone changes their dark mode in the settings while the app is in background mode, it won't track.

At least the last time I tried it wouldn't work.

I would love to see your implementation if you wouldn't mind.

**Comment by komik966** [comment] 2023-08-30 07:47
Hi all, did you try this solution https://github.com/facebook/react-native/issues/28525#issuecomment-1265851586 ? This seems the best solution which also updates app screenshot in the app switcher.

**Comment by Codelica** [comment] 2023-08-30 15:04
Maybe I'm missing something here, but I just ignore listener calls when the app is backgrounded and manually check the current system theme when it becomes active.

**Comment by vasylnahuliak** [comment] 2023-08-30 15:36
My workaround (https://github.com/ds300/patch-package use for applying changes)

```
diff --git a/node_modules/react-native/React/CoreModules/RCTAppearance.mm b/node_modules/react-native/React/CoreModules/RCTAppearance.mm
index 17535a9..e7fd131 100644
--- a/node_modules/react-native/React/CoreModules/RCTAppearance.mm
+++ b/node_modules/react-native/React/CoreModules/RCTAppearance.mm
@@ -106,9 +106,8 @@ RCT_EXPORT_METHOD(setColorScheme : (NSString *)style)
 
 RCT_EXPORT_SYNCHRONOUS_TYPED_METHOD(NSString *, getColorScheme)
 {
-  if (_currentColorScheme == nil) {
-    _currentColorScheme = RCTColorSchemePreference(nil);
-  }
+  _currentColorScheme = RCTColorSchemePreference(nil);
+
   return _currentColorScheme;
 }
 ```

⚠️ PAY ATTENTION: These changes can create new bugs!

[react-native+0.72.3.patch](https://github.com/facebook/react-native/files/12477357/react-native%2B0.72.3.patch)

**Comment by fabOnReact** [comment] 2024-02-02 05:49
how many devs experience this issue in the latest version of react-native?

**Comment by junebugfix** [comment] 2024-02-29 01:21
This was fixed for me on 0.73.5! 🎉

**Comment by outaTiME** [comment] 2024-02-29 01:23
> This was fixed for me on 0.73.5! 🎉

I am using version `0.73.4` and it seems to be working correctly as well 🙌

**Comment by kelset** [comment] 2024-02-29 10:08
that's great! Given that there are a couple of reports of the issue being fixed let's close this. If you have any further issues I would recommend opening a new issue with a proper repro.

**Closed by kelset** 2024-02-29 10:08 UTC
Labels: Resolution: Fixed

**Comment by Andreibv** [comment] 2024-09-11 17:57
> Dump question, isn't it the easiest way to just call `Appearance.getColorScheme()` when the Listener fires? Works well for me without a cumbersome timer...
> 
> ```ts
>   const initAppearanceListener = () => {
>     const listener: Appearance.AppearanceListener = ({ colorScheme } /* <-- ignore */) => {
>       setColorScheme(Appearance.getColorScheme());
>     };
>     Appearance.addChangeListener(listener);
>     return () => Appearance.removeChangeListener(listener);
>   };
> ```

2024 not working for me :(
