### ISSUE TITLE
connectAnimatedNode: AnimatedNode with child tag does not exist - Getting this crash with SectionList.stickySectionHeadersEnabled={true} in Android devices

### ISSUE THREAD

**Issue by gnair03** [facebook/react-native#37126] opened 2023-04-27 13:23 UTC
### Description

We have a component in our project that uses SectionList, with stickySectionHeadersEnabled={true}. There have been instances of the connectAnimatedNode crash, happening on this screen. On debugging, I found that whenever stickySectionHeadersEnabled is true, I am able to reproduce this crash with certainty. When this is disabled, the crash does not re-occur. Even the native method in NativeAnimatedNodesManager class is NOT called, when this prop is disabled. 

As part of fixing this, I tried:
1. Reanimated.Flatlist with stickyHeaderIndices --> Still caused the same crash
2. Animated.createanimatedComponent(SectionList) --> Still caused the same crash

Should I work on creating a custom sticky component, instead? 

Any help here? 

### React Native Version

0.69.1

### Output of `npx react-native info`

---

### Steps to reproduce

Simply press back from the screen that has the SectionList, even before/just as the screen loads. This was reproducible 3/10 times on my Samsung Galaxy S10 Android 12 device

### Snack, code example, screenshot, or link to a repository

----

**Comment by gnair03** [comment] 2023-04-27 13:24
Migrating to a newer version of ReactNative is not amongst the immediate goals we have. Is this issue fixed in the latest RN, anyway?

**Comment by gnair03** [comment] 2023-05-02 06:58
Any update here?

**Comment by gnair03** [comment] 2023-05-02 07:03
@cortinico - Please let me know if this is known.

**Comment by cortinico** [comment] 2023-05-02 09:34
Your bug report is incomplete:
1. You don't mention what's the crash (can you provide a stacktrace)
2. You haven't provided a reproducer

**Comment by gnair03** [comment] 2023-05-04 07:36
About the reproducer:

`import React, {useCallback} from 'react';

import {SectionList, Text} from 'react-native';

type SectionData = {
  title: string;
  data: string[];
};

const LIST_DATA: SectionData[] = [
  {
    title: 'A',
    data: [
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '13',
      '14',
      '15',
    ],
  },
  {
    title: 'B',
    data: [
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '13',
      '14',
      '15',
    ],
  },
  {
    title: 'C',
    data: [
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '13',
      '14',
      '15',
    ],
  },
  {
    title: 'D',
    data: [
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '13',
      '14',
      '15',
    ],
  },
  {
    title: 'E',
    data: [
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '13',
      '14',
      '15',
    ],
  },
];

export const PureSectionList = () => {
  const ItemView = useCallback(({item}) => {
    return <Text style={{height: 25}}>{item}</Text>;
  }, []);

  return (
    <>
      <SectionList
        sections={LIST_DATA}
        stickySectionHeadersEnabled={true}
        renderSectionHeader={HeaderView}
        renderItem={ItemView}
      />
    </>
  );
};

export const HeaderView = (info: {section: SectionData}) => {
  return (
    <Text style={{height: 25, backgroundColor: 'red'}}>
      {info.section.title}
    </Text>
  );
};
`

**Comment by gnair03** [comment] 2023-05-04 07:41
We are getting a lot of instances of the above mentioned crash, with the above specified code block. On debugging, it is found that SectionList's **`stickyHeaderEnabled`** is the cause of this crash. When this prop is applied and is set to true, the connectAnimatedNode crash is randomly observed. But, when this prop is not added at all, or set to false, this crash does not occur at all. 

Reproducing this crash is not very easy and is not consistently reproducible either. So, I have added debug pointers in the native java class - NativeAnimatedNodesManager.connectAnimatedNode method, and I check if this code block(connectAnimatedNode method) is ever called. 

This crash-causing code block is always called when stickyHeaders are enabled. That means, that there could be instances where this exception is thrown and the crash could occur. Internally, stickyHeaderIndices use the 'animated' module for the sticky animation, and hence this could be the cause of the crash. 

What can be done here to avoid this issue? 

@cortinico

**Comment by cortinico** [comment] 2023-05-05 10:26
> @cortinico - Does the above data help?

Yes that's a duplicate of other issues: #33375 #36921 #33375 and others 

I'll close this as a duplicate, and the conversation happens over here:
- #37267

Hopefully we'll be able to find a fix or a workaround of some sort.

**Closed by cortinico** 2023-05-05 10:26 UTC
Labels: Platform: Android, API: Animated, Component: SectionList, Needs: Repro, Needs: Verify on Latest Version, Needs: Attention
