### ISSUE TITLE
Argument list too long: 

### ISSUE THREAD

**Issue by qjloong** [facebook/react-native#797] opened 2015-04-10 10:40 UTC
Argument list too long: recursive header expansion failed at /Users/qycloud/workspace/ReactNative/example1/test1/Pods/React/packager/node_modules/module-deps/node_modules/duplexer2/node_modules/readable-stream/node_modules/core-util-is/lib.

**Comment by jaygarcia** [comment] 2015-04-10 13:21
Can you please help us understand what you did to get this error?

**Comment by brentvatne** [comment] 2015-04-15 22:25
As @jaygarcia mentioned, it would be helpful to have a bit more information :smile: - if this is still an issue, feel free to ping me and provide the full error message and the code that caused it and we can help you further @qjloong! I'll close the issue until then.

**Closed by brentvatne** 2015-04-15 22:25 UTC

**Comment by mvayngrib** [comment] 2015-05-10 23:57
I have the same error, reproducible with the following steps:
```
react-native init longargs
cd longargs
npm install --save react-native-udp
npm install --save-dev react-native-webpack-server
open longargs.xcodeproj
# Link up react-native-udp:
#   1. add node_modules/react-native-udp/UdpSockets.xcodeproj 
#   2. link libUdpSockets.a from UdpSockets lib
# Build
```

**Comment by mvayngrib** [comment] 2015-05-11 00:17
i guess it's an Xcode thing, having to do with recursive Header Search Paths: $(SRCROOT)/../../React

**Comment by paramaggarwal** [comment] 2015-06-18 13:31
I was hitting this issue. In your project and target build settings, search for 'Header Search Paths' and 'User Search Header Paths' and make sure that you are not making Xcode recurse over a very very very large set of files and folders recursively. In my case, I was overwriting the one that CocoaPods had added there, and hence it was recursing over an extremely large directory.

**Comment by brentvatne** [comment] 2015-06-18 13:35
@paramaggarwal - do you think it's worth adding a note about this to the documentation anywhere?

**Comment by paramaggarwal** [comment] 2015-06-18 13:56
Good thought. If somebody searches the issues or Google with their error message 'Argument list too long', they'll hopefully land here. I went to the React Native documentation, and noticed that the sidebar does not link to the [Troubleshooting](https://facebook.github.io/react-native/docs/troubleshooting.html) page. That would be a great place to add stuff like this, that is gathered from the issues. What do you think?

**Comment by paramaggarwal** [comment] 2015-06-22 05:46
@brentvatne I raised #1701 documenting this possible issue.

**Comment by brentvatne** [comment] 2015-06-23 23:54
Thanks!

**Comment by ATeamMac2014** [comment] 2016-06-16 02:02
who can fixed?

**Comment by stevenyap** [comment] 2016-12-20 05:49
My ios builds are failing due to: `/Users/***/mobile/ios/../node_modules/react-native-device-info/android/build/intermediates/exploded-aar/com.facebook.fresco/fbcore/0.11.0`

I managed to fix this issue by adding `android` in xcode under Build Settings > Search Paths > Sub-Directories to Exclude in Recursive Searches

This managed to solve my problem even though I am not exactly sure why. It does not affect my android builds and my codes are all working.

If someone can explain why this works, it would be great.

**Comment by Luckygirlllll** [comment] 2018-02-03 19:30
i have the same error, any efficient solutions so far?

**Comment by BigPun86** [comment] 2018-02-13 00:42
+1

**Comment by cinder92** [comment] 2018-02-17 18:35
+1

**Comment by SnowDang** [comment] 2018-04-18 04:44
I have the same error

**Comment by burkaslarry** [comment] 2018-04-18 11:56
how to solve this ?
