### ISSUE TITLE
Why does onEndReached callback trigger twice sometime ?

### ISSUE THREAD

**Issue by phuoctuong** [facebook/react-native#15473] opened 2017-08-12 10:22 UTC
When I use FlatList Component in react-native 0.47, onEndReached trigger automatically.
My data array includes 10 elements and just 9 elements are visible on screen. 
The first time render, onEndReached callback trigger automatically but I don't want it.
This bug takes me a long time to research.
Can anyone give me a solution for that ? 
Thank you so much

**Comment by hramos** [comment] 2017-08-15 17:27
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-08-15 17:27 UTC

**Comment by subhaabhi21** [comment] 2017-09-22 07:26
If I enclose the flatlist in a View then my onEndReached triggers infinitely if I remove the enclosing View onEndReached is not triggered at all.

render(){

     return (
        <Root>
             <Container>
                     <Content>                  
                        <View>
                                {this.state.listView &&
                                    <FlatList
                                    data={this.state.variants}
                                    keyExtractor={this._keyExtractor}
                                    onEndReachedThreshold={0.5}
                                    onEndReached={({ distanceFromEnd }) => {
                                         console.log('on end reached ', distanceFromEnd);
                                         this.loadMore();
                                     }}
                                    numColumns = {1}
                                    renderItem={({item, index}) =><CatalogRow item={item} in_wishlist={this.state.in_wishlist} toggleWishlist={() => this.toggleWishlist(item.title)} listView={this.state.listView}/>}
                                />}

                            </View>
                     </Content>
                </Container>
            </Root>
    );
    }
And my distanceFromEnd takes values like 0 , 960,1200 when it is trigerred. What does it indicate? I'm using react-native 0.47.2

**Comment by anil1712** [comment] 2018-02-02 04:31
Yeah, the thing is happening to me also. Is someone got any solution?

**Comment by DavitVosk** [comment] 2018-02-17 00:24
The same problem here. Why close the issue if it is not gone away?

**Comment by anil1712** [comment] 2018-02-17 08:44
Don't know why its closed without the solution

**Comment by mrtry** [comment] 2018-02-25 14:14
I think that `<Content>` is the cause.
I hope this will help. ;)

see: https://github.com/facebook/react-native/issues/12827#issuecomment-320508221
