### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by duarte-evocorp** [facebook/react-native#25355] opened 2019-06-22 02:49 UTC
Compile error

* /root/.gradle/caches/transforms-1/files-1.1/drawee-2.0.0.aar/968f7ced5a440968f6c39ec435ba6404/res/values/values.xml:3:5-141:23: AAPT: error: resource android:attr/fontVariationSettings not found.

* /root/.gradle/caches/transforms-1/files-1.1/drawee-2.0.0.aar/968f7ced5a440968f6c39ec435ba6404/res/values/values.xml:3:5-141:23: AAPT: error: resource android:attr/ttcIndex not found.

React Native Environment Info:
    System:
      OS: Linux 4.9 Debian GNU/Linux 9 (stretch) 9 (stretch)
      CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
      Memory: 789.67 MB / 7.60 GB
      Shell: 4.4.12 - /bin/bash
    Binaries:
      Node: 8.16.0 - /usr/bin/node
      Yarn: 1.16.0 - /usr/bin/yarn
      npm: 6.9.0 - /usr/bin/npm
    SDKs:
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 26.0.1, 26.0.2, 27.0.3, 28.0.0, 28.0.2, 28.0.3
        System Images: android-25 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-Q | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: ^0.58.5 => 0.58.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

**Comment by dulmandakh** [comment] 2019-06-22 04:36
duplicate of https://github.com/facebook/react-native/issues/25356

**Closed by dulmandakh** 2019-06-22 04:36 UTC
Labels: API: Linking, Bug, Platform: Android, Platform: Linux

**Comment by hadpro24** [comment] 2020-05-25 22:04
Are you solve it ?
