### ISSUE TITLE
[ListView & Image] Loading 100 big images into a ListView not only crashes the app, but also crashes the os

### ISSUE THREAD

**Issue by xiaodao** [facebook/react-native#1360] opened 2015-05-21 06:57 UTC
I have a list of 100 image URLs and seeded them into the datasource of the ListView. 

then I used this one for renderRow:

    <Image source={{uri: imageUri}} style={styles.image} />

and it worked fine when I was scrolling the top 40~50 images, but when I scrolled to the end of the list, then the app crashed and I saw the white apple on the screen.

And there is no stacktrace in crash report.

**Comment by Iragne** [comment] 2015-05-26 14:00
it's cleary an issue with the size of the images.
It's a memory warning

**Comment by tadeuzagallo** [comment] 2015-05-26 14:07
Can you reproduce that constantly?

**Comment by Iragne** [comment] 2015-05-26 14:51
As soon as you load big image in a list you get this problem i will investigate more.
I solve in a way this issue on Library Asset https://github.com/facebook/react-native/pull/1406

**Comment by nparsons08** [comment] 2015-05-26 14:55
You could use preprocessing like http://6px.io

**Comment by Iragne** [comment] 2015-05-26 14:59
yes if you want it will work.
But i think we should implement it in react

**Comment by nparsons08** [comment] 2015-05-26 15:00
Totally agree. I have an application that will be loading several hundred.
Would love to see a fix for this. +1.

**Comment by Iragne** [comment] 2015-05-26 15:02
+1

**Comment by Iragne** [comment] 2015-05-26 15:18
https://github.com/Iragne/UIImage-ResizeMagick ;) it's a good start !!!

**Comment by xiaodao** [comment] 2015-05-26 22:54
@tadeuzagallo Yes, I can reproduce it constantly

**Comment by KJlmfe** [comment] 2015-05-29 02:56
I also have this problem. 

I implement this page http://www.tmall.com/wh/tmall/act/14242/jfbybk with react-native ListView component, when I run in IPad air(not  Simulator), it crash when I scroll fast or scroll to the bottom.

**Comment by brentvatne** [comment] 2015-05-29 21:05
@xiaodao @KJlmfe - can you link us to a public repo where we can see the bug in action? Thanks!

cc @tadeuzagallo

**Comment by sahrens** [comment] 2015-06-15 19:51
I think the general fix is view recycling, but we might need to do Image caching differently as well.

**Comment by soliury** [comment] 2015-07-20 03:48
@sahrens  How about the tabView?

**Comment by fishedee** [comment] 2015-10-17 01:00
+1

**Comment by nparsons08** [comment] 2016-03-09 03:11
Hi facebook/react-nativ,

I'd like to add you to my professional network on LinkedIn.

- Nick

Confirm that you know Nick: https://www.linkedin.com/e/v2?e=0-ilk9qrdu-ol&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=3ciWTf73&invitationId=6113168880128061442








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ilk9qrdu-ol&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHD5Yyl865szAAAAVNZW2CEL_n7VnBL3g8qOG0pTJ4BMVKyVo8jwBus7Eny15fGdhv23C2faC7le3XVVKPhJKiNg0_Tio3FqGRugNuswbJtL50Ngf5Mz7TEMLCtQGnaLLaGbVegi93jKG92MSj3KupmU2FRbxxcI4JxUTRFfMV5r0T22s9EapcUtnjwhFykc5r8&eid=0-ilk9qrdu-ol


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ilk9qrdu-ol&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by nparsons08** [comment] 2016-03-09 03:11
Hi,

I'd like to add you to my professional network on LinkedIn.

- Nick

Confirm that you know Nick: https://www.linkedin.com/e/v2?e=0-ilk9qrcm-sn&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=4OJ1V-TX&invitationId=6113168880501346305








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ilk9qrcm-sn&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHRwHtZNf32kgAAAVNZW15dnActPdOI4FeJZ5HZGVyU6F5Cz7F3tqAC8xOlcTw03rwv27qCyoDZtvgtR7gYNR_qiRFJEZBWlZEw-XeyZ4PTz1zFJbXR8hraYicjAyRGjfWfyxO76zPeVCzMLFTrtvaBMAsd_x6z-t_7S9Wx50UNxg7a9ISe4BZtLMkQonYtWVzf&eid=0-ilk9qrcm-sn


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ilk9qrcm-sn&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by udfalkso** [comment] 2016-03-09 22:35
@nparsons08 Stop that.

**Comment by nparsons08** [comment] 2016-03-16 01:00
Nick Parsons would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-oyn4oy-iltv9hug-fa&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=3ciWTf73&invitationID=6113168880128061442

View Nick Parsons&#39;s profile: https://www.linkedin.com/e/v2?e=-oyn4oy-iltv9hug-fa&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=3ciWTf73&invitationID=6113168880128061442





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-oyn4oy-iltv9hug-fa&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-oyn4oy-iltv9hug-fa&loid=AQFFOKc534M4pgAAAVN879sGIAf9yxthf6K3oob1ZXnWernl6-7Mktr1NL6MqbMn8rG4GLsNpaS-LDLGZkriOwOtGFGG-zZklqcZSbZxhWHOBm7Tnjy2NJqlwD71W0an-CnIwmfg3Y_iwEpO9c5_gqaPaVyfKQCuIVXgmJb-zv2AgLDH_DQ7NK5XXXosRjg5lTnz

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-oyn4oy-iltv9hug-fa&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by nparsons08** [comment] 2016-03-16 01:00
Nick Parsons would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-tx99vx-iltv9hnr-yy&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=4OJ1V-TX&invitationID=6113168880501346305

View Nick Parsons&#39;s profile: https://www.linkedin.com/e/v2?e=-tx99vx-iltv9hnr-yy&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=4OJ1V-TX&invitationID=6113168880501346305





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-tx99vx-iltv9hnr-yy&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-tx99vx-iltv9hnr-yy&loid=AQG2j6lc8itRmwAAAVN8780GFjbUZ8-I7Dfjx6mKvjJDe7yfXUZyGsm5XaiKHlEDYsW_v2KXF8UC7NVrkCtxETykVoCNfQEhErqxoHKHer_Dlc75y9z4oNm8fuu9dAhPwCRbC4dY-lhkx6U58mMlibDA_GlfFVpmIiQZ-4pbLeOK5B5p_jHQ5hbSCRMYecnTkT9a

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-tx99vx-iltv9hnr-yy&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by nparsons08** [comment] 2016-03-22 20:01
Nick Parsons would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-oyn4oy-im3mumil-6b&a=preRegInvite&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=3ciWTf73&invitationID=6113168880128061442

View Nick Parsons&#39;s profile: https://www.linkedin.com/e/v2?e=-oyn4oy-im3mumil-6b&a=preRegInvite&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=3ciWTf73&invitationID=6113168880128061442





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-oyn4oy-im3mumil-6b&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=-oyn4oy-im3mumil-6b&loid=AQGExaH7ziUiqwAAAVOf6rnUf8KXfVX4JsIHjc3FeBpCv7QQbXMqxYHIWvHNrRK2QkoFgV2C5hSkfzx9TTwKfMveGwAmKSBgSEYeTu7pZ8P49Dj6gDLei7mkhE2OZjeIx_NmxgqkNDjjZMAJwvOsDWCp-NiPBi6_GILyy5bxL8Q8qS64OiG75BdERxtBWcX_7YDI

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-oyn4oy-im3mumil-6b&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by mkonicek** [comment] 2016-07-29 23:09
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/listview-image-loading-100-big-images-into-a-listview-not-only-crashes-the-app-but-also-crashes-the-os

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Closed by mkonicek** 2016-07-29 23:09 UTC
Labels: Icebox
