### ISSUE TITLE
borderStyle: 'dashed' / 'dotted' does not work on android in version 0.55.1

### ISSUE THREAD

**Issue by neilzhengzx** [facebook/react-native#19234] opened 2018-05-12 06:14 UTC
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

  Environment:
    OS:  macOS High Sierra 10.13.2
    Node:  8.4.0
    Yarn:  0.27.5
    npm:  5.4.0
    Watchman:  4.7.0
    Android Studio:  3.0

  Packages: (wanted => installed)
    react-native: 0.55.1 => 0.55.1

### Steps to Reproduce

borderStyle: 'dashed'

### Expected Behavior

the border will be dashed

### Actual Behavior

the border not be dashed

### Reproducible Demo

borderStyle: 'dashed'

**Comment by hramos** [comment] 2018-05-12 06:41
Duplicate of #18285

**Closed by hramos** 2018-05-12 06:41 UTC
Labels: :large_blue_diamond:Android

**Comment by nhayfield** [comment] 2018-08-31 15:27
This is not fixed
