### ISSUE TITLE
Live-reload gets disabled after reload

### ISSUE THREAD

**Issue by mbrgm** [facebook/react-native#1067] opened 2015-04-29 20:58 UTC
Whenever I enable live-reload, it gets disabled immediately after the reload took place. Can anyone confirm this problem?

**Comment by dvdhsu** [comment] 2015-04-29 23:40
Yes, can confirm this happens in 0.4.1.

**Comment by brentvatne** [comment] 2015-04-30 03:08
Confirmed this, what's happening is that `_liveReload` and `_liveReloadPeriod` are being thrown away on each reload because the devmenu is dealloc'd when a reload occurs - other menu options don't have their state stored in a devmenu class instance variable.

**Comment by brentvatne** [comment] 2015-04-30 04:27
Closing this as we are tracking it now in the aforementioned pull request! Thanks :smile:

**Closed by brentvatne** 2015-04-30 04:27 UTC
