### ISSUE TITLE
Exception is thrown in the code, but it works normally

### ISSUE THREAD

**Issue by iamdurui** [facebook/react-native#14183] opened 2017-05-25 07:10 UTC
![hf omj6 g6rh xz1a7nq6](https://cloud.githubusercontent.com/assets/16399401/26439159/7728033e-4159-11e7-9ca5-57cf8311a38b.png)

when I create a native module in Android, throwing an exception , it is Method threw 'com.facebook.react.bridge.ObjectAlreadyConsumedException' exception. Cannot evaluate com.facebook.react.bridge.WritableNativeMap.toString()
my code is:
         array=new WritableNativeArray();
                        for(int i=0;i<fileList.size();i++){
                            WritableMap map=new WritableNativeMap();
                            map.putString("uri","file://"+fileList.get(i).getAbsolutePath());
                            map.putString("fileName",fileList.get(i).getName());
                            map.putInt("size", (int) fileList.get(i).length());
                            array.pushMap(map);
                        }
                        callback.invoke(array);

* React Native version: 0.39.0
* Platform:  Android
* Development Operating System: Windows
* Dev tools: Android Studio version 2.1.2,com.android.tools.build:gradle:2.2.3, buildToolsVersion "24.0.2"
Although the error is appeared, but it is not crash, I want to be given a solution ,thanks

**Comment by hramos** [comment] 2017-05-25 19:57
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-05-25 19:57 UTC

**Comment by iamdurui** [comment] 2017-05-26 01:57
@hramos 
this code is 
for(int i=0;i<fileList.size();i++){
                            WritableMap map=new WritableNativeMap();
                            map.putString("uri","file://"+fileList.get(i).getAbsolutePath());
                            map.putString("fileName",fileList.get(i).getName());
                            map.putInt("size", (int) fileList.get(i).length());
                            array.pushMap(map);
                        }
when i >0; the exception is thrown, I guess it is to be caused by the code(WritableMap map=new WritableNativeMap() ), Thanks!
![i2 2 5 c poz qn7_l 3o](https://cloud.githubusercontent.com/assets/16399401/26477653/b7276e98-41f9-11e7-84f6-bfec64a59420.png)
![pj7 wubfla58 l znza4q3](https://cloud.githubusercontent.com/assets/16399401/26477654/b727ed32-41f9-11e7-9312-2ef694d2ff31.png)
