### ISSUE TITLE
0.46 rc.2 Error: Couldn't find preset "env" relative to directory

### ISSUE THREAD

**Issue by compojoom** [facebook/react-native#14741] opened 2017-06-27 09:15 UTC
Hey guys,
I'm updating a project to 0.46 and I ran in several issues. I tried to reproduce them on a new app with success

I created a new app with:
react-native init rn46crash --version react-native@0.46.0-rc.2

Everything went fine. When I tried to start the app with xcode, the app is building fine, but the packager runs in the following error:

```
/Users/xxx/Documents/Development/Apps/rn-46-crash/rn46crash/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328
        throw e;
        ^

Error: Couldn't find preset "env" relative to directory "/Users/xxx/Documents/Development/Apps/rn-46-crash/rn46crash/node_modules/regenerator-transform" (While processing preset: "/Users/xxx/Documents/Development/Apps/rn-46-crash/rn46crash/node_modules/babel-preset-react-native/index.js")
    at /Users/xxx/Documents/Development/Apps/rn-46-crash/rn46crash/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/xxx/Documents/Development/Apps/rn-46-crash/rn46crash/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/xxx/Documents/Development/Apps/rn-46-crash/rn46crash/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/xxx/Documents/Development/Apps/rn-46-crash/rn46crash/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/xxx/Documents/Development/Apps/rn-46-crash/rn46crash/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/Users/xxx/Documents/Development/Apps/rn-46-crash/rn46crash/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/xxx/Documents/Development/Apps/rn-46-crash/rn46crash/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/xxx/Documents/Development/Apps/rn-46-crash/rn46crash/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:503:32)
Process terminated. Press <enter> to close the window
```

I created a repository with the issue:
https://github.com/compojoom/rn46crash/commit/6f2df822bc9c4b37cdad9f1dc3c9321a7bc993fe - this commit crashes

This one is fine:
https://github.com/compojoom/rn46crash/commit/9e3672d410d227b1215120fa174af6e339ef79b1 - I've renamed .babelrc and it's being used.

**Comment by ZeusTheTrueGod** [comment] 2017-06-28 11:13
I have a similar issue - the project was working, I decided to remove all node_modules to check that all works well, then started to get those messages.

option a) - downgrade to 0.45
option b)  (Although did not work) - run `react-native start` in one tab first, and then run `react-native run-ios` in the other tab

**Comment by grabbou** [comment] 2017-07-05 19:49
Duplicate of #14530

**Closed by grabbou** 2017-07-05 19:49 UTC
