### ISSUE TITLE
React Native Build Failed react-native run-ios

### ISSUE THREAD

**Issue by dereklim12** [facebook/react-native#21631] opened 2018-10-10 06:21 UTC
The project cannot run in MAC. It can run in Windows on Android Studio.
## Environment
  React Native Environment Info:
    System:
      OS: OS X Yosemite 10.10.5
      CPU: x64 Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
      Memory: 7.45 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: X 10.11, iOS 9.0, watchOS 2.0
    IDEs:
      Xcode: 7.0/7A220 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.1 => 0.57.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native: 0.23.1

## Description
** BUILD FAILED **

The following commands produced analyzer issues:

	Analyze /Users/derek/reactNativeProjects/EBI/node_modules/react-native/ReactCommon/cxxreact/CxxNativeModule.cpp
	Analyze /Users/derek/reactNativeProjects/EBI/node_modules/react-native/ReactCommon/cxxreact/NativeToJsBridge.cpp
(2 commands with analyzer issues)

The following build commands failed:
	CompileC /Users/derek/reactNativeProjects/EBI/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTShadowView+Internal.o Views/RCTShadowView+Internal.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/EBI.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/EBI.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/EBI.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:602:13)
    at Object.execFileSync (child_process.js:622:13)
    at Promise.then (/Users/derek/reactNativeProjects/EBI/node_modules/react-native/local-cli/runIOS/runIOS.js:208:5)
    at <anonymous>

## Reproducible Demo
react-native init EBI
cd EBI
react-native run-ios

**Comment by sw-tt-jigneshkumarchitaliya** [comment] 2018-10-10 08:57
same issue

**Comment by vitorreis** [comment] 2018-10-10 12:57
Same here, with an existing project. it works in the machine of the 1st dev that started the project, but any team member which clones the repo gets this error.

Tested in a Mac with High Sierra
Xcode: 10.0 10A255

And also tested in a Mac with Sierra
Xcode: Version 9.2 (9C40b)

Also tried the instructions described in #20774 but it didn't work.

**Comment by hamidtirmizi** [comment] 2018-10-10 17:41
Seeing this on Mac:

** BUILD FAILED **



The following build commands failed:
	CompileC /Users/hamid/Work/linuplayer/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/fixed-dtoa.o /Users/hamid/Work/linuplayer/node_modules/react-native/third-party/double-conversion-1.1.6/src/fixed-dtoa.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/hamid/Work/linuplayer/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/fast-dtoa.o /Users/hamid/Work/linuplayer/node_modules/react-native/third-party/double-conversion-1.1.6/src/fast-dtoa.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/hamid/Work/linuplayer/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/strtod.o /Users/hamid/Work/linuplayer/node_modules/react-native/third-party/double-conversion-1.1.6/src/strtod.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(3 failures)

Installing build/Build/Products/Debug-iphonesimulator/linuplayer.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/linuplayer.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist


Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/linuplayer.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:601:13)
    at Object.execFileSync (child_process.js:621:13)
    at Promise.then (/Users/hamid/Work/linuplayer/node_modules/react-native/local-cli/runIOS/runIOS.js:208:5)
    at <anonymous>

**Comment by saxenanickk** [comment] 2018-10-11 23:35
@dereklim12 

1. Open project in Xcode.

2. Navigate to File > Project Settings > Build System.

3. Change this to Legacy Build System.

4. Try to run your project.

It worked for me.

**Comment by rodrigoelp** [comment] 2018-10-12 04:02
The build crashes and the fix has nothing to do with the new build system

If you run `react-native run-ios` again it fixes the build issue.

**Comment by kelset** [comment] 2018-10-12 15:11
Duplicate of https://github.com/facebook/react-native/issues/21741

**Closed by kelset** 2018-10-12 15:11 UTC
Labels: :large_blue_diamond:iOS
