### ISSUE TITLE
Elevation does not animate when it is inside a view which animates its opacity (Android P)

### ISSUE THREAD

**Issue by temhota** [facebook/react-native#23670] opened 2019-02-27 12:05 UTC
## 🐛 Bug Report
What described in the title works in any Android but not on Android P. See the differences:

**Android P:**
![5](https://user-images.githubusercontent.com/37623333/53489037-50fd7400-3a90-11e9-88f2-4af9236ad210.gif)

**Below Android P:**
![6](https://user-images.githubusercontent.com/37623333/53489043-53f86480-3a90-11e9-97e1-9060293344ae.gif)

## Code Example
https://snack.expo.io/@satya164/elevation-issue---android-p

## Environment
```React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 137.99 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.6.0 - ~/.nvm/versions/node/v10.6.0/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.1.0 - ~/.nvm/versions/node/v10.6.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.3, 25.0.2, 27.0.3, 28.0.2, 28.0.3
        System Images: android-26 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.58.4 => 0.58.4

**Comment by hramos** [comment] 2019-02-27 23:49
Can you fully fill out the template? (expected behavior, for example). It will help folks understand the issue better.

**Comment by leethree** [comment] 2019-03-26 11:14
I've encountered the same issue. Also for "Below Android P" it doesn't work perfectly either. You can see a grey bordered square appear when the box is being animated. 

![image](https://user-images.githubusercontent.com/648142/54992855-4fa06800-4fb8-11e9-9a1d-27b4666ca66c.png)

The expected behaviour is that the shadow should fade with the view and the view should change uniformly.

@hramos I think the bug report is clear enough and very easy to understand.

**Comment by satya164** [comment] 2019-05-30 16:26
Duplicate of #23090

**Closed by satya164** 2019-05-30 16:26 UTC
Labels: Bug, Platform: Android
