### ISSUE TITLE
Not able to run a new react-native project for ios

### ISSUE THREAD

**Issue by aghishbabu** [facebook/react-native#15210] opened 2017-07-26 12:11 UTC
### Is this a bug report?
Yes

### Have you read the Bugs section of the How to Contribute guide?

yes

### Environment

1. `react-native -v`: react-native-cli: 2.0.1
2. `node -v`: v6.11.1
3. `npm -v`: 3.10.10
4. `yarn --version`: 0.27.5

Then, specify:

- Target  #Platform: iOS

- Development Operating System: macOS Sierra v10.12.3

- Build tools: Xcode 8.3.3

### Steps to Reproduce

(Write your steps here:)

1.Open terminal   
2.react-native init ProjectName
3.From project folder type react-native start
4.react-native run-ios

### Expected Behavior

It should build a project which shows the initial page of the react-native app.

### Actual Behavior

It shows Build Failed and displays a list a errors.

![screen shot 2017-07-26 at 5 01 25 pm](https://user-images.githubusercontent.com/30345372/28619027-3995e620-7224-11e7-8e26-d75a66e825ff.png)
This is what is shows.

tar: Error exit delayed from previous errors.

Command /bin/sh failed with exit code 1

** BUILD FAILED **

The following commands produced analyzer issues:

	Analyze /Users/apple/Desktop/RCTApp/RCTApp/node_modules/react-native/ReactCommon/yoga/yoga/YGNodeList.c
	Analyze /Users/apple/Desktop/RCTApp/RCTApp/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.c
(2 commands with analyzer issues)

The following build commands failed:
	PhaseScriptExecution Install\ Third\ Party /Users/apple/Desktop/RCTApp/RCTApp/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/double-conversion.build/Script-190EE32F1E6A43DE00A8543A.sh
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/RCTApp.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/RCTApp.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

When the same project is run on Xcode 8.3.3 I get issues as below:
![screen shot 2017-07-26 at 5 37 20 pm](https://user-images.githubusercontent.com/30345372/28620150-55d765ac-7229-11e7-94f1-0d0d9a56dcfa.png)

### Reproducible Demo
It happens to every newly created react native projects 

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by gedeagas** [comment] 2017-07-29 04:25
this happen to me today for the first time.

**Comment by simonepauro** [comment] 2017-07-30 16:38
I had this same problem, looks like this is a problem with the latest react-native versions.
- Make sure you are running the latest version of Sierra, mine is 10.12.6
- Init the new project with `rninit init AwesomeProject --source react-native@0.44`

**Comment by webkixi** [comment] 2017-07-30 18:48
I had this same problem in cli

in xcode, the error message is `/Users/yc/rn/mymy/node_modules/react-native/third-party/folly-2016.09.26.00/folly/detail/BitIteratorDetail.h:21:10: 'boost/iterator/iterator_adaptor.hpp' file not found`

In fact the file is stored in `boost/iterator_adaptor.hpp`

I looked at all the files in `node_modules/react-native/third-party/boost_1_63_0/boost` and seemed to have this problem

**Comment by jjerryhan** [comment] 2017-08-01 16:27
This article would be helpful : `https://medium.com/@jjerryhan/handling-third-party-build-error-on-react-native-0-46x-445f867e7a2b`

**Comment by hramos** [comment] 2017-08-03 17:31
Duplicate of #14447

**Closed by hramos** 2017-08-03 17:31 UTC

**Comment by hramos** [comment] 2017-08-03 17:58
Duplicate of #14423

**Comment by alfonsodlopez** [comment] 2018-01-29 07:37
Has anyone been able to come up with a resolution for this? I cannot comment on #14423 so I am commenting here. The proposed workarounds on that thread do not work in the projects I am working with. Please advise.
