### ISSUE TITLE
Error: Duplicate resources is showing when trying to run ./gradlew assembleRelease

### ISSUE THREAD

**Issue by danielbbt** [facebook/react-native#31769] opened 2021-06-24 06:14 UTC
React Native version: 0.63.4

Please note that I have already tried the solutions in but still to no avail: 
https://github.com/facebook/react-native/issues/22234
https://github.com/facebook/react-native/issues/26245
https://shreyasnisal.medium.com/solved-packing-error-in-react-native-release-apk-f887687edc4f

The error that I am receiving is below:

```
[raw/assets_fonts_galioextra] android/app/build/generated/res/react/release/raw/assets_fonts_galioextra.json
[raw/assets_fonts_galioextra] android/app/build/generated/res/react/release/raw/assets_fonts_galioextra.ttf
Error: Duplicate resources
```

**Comment by SConaway** [comment] 2021-06-28 01:07
Probably too simple of a solution / thought, but here's what I'm thinking: 

Is it possible that you've copied the `assets_fonts_galioextra.json` and `assets_fonts_galioextra.ttf` files yourself to somewhere in `android/app/src/main/res/`? Maybe you already copied it once, and then some part of the build script is copying it again. 

Also try cleaning everything with: `./gradlew clean` and then rebuild.

**Comment by developerdanx** [comment] 2021-08-09 08:14
> React Native version: 0.63.4
> 
> Please note that I have already tried the solutions in but still to no avail:
> #22234
> #26245
> https://shreyasnisal.medium.com/solved-packing-error-in-react-native-release-apk-f887687edc4f
> 
> The error that I am receiving is below:
> 
> ```
> [raw/assets_fonts_galioextra] android/app/build/generated/res/react/release/raw/assets_fonts_galioextra.json
> [raw/assets_fonts_galioextra] android/app/build/generated/res/react/release/raw/assets_fonts_galioextra.ttf
> Error: Duplicate resources
> ```

@danielbbt I have the same problem as you and the solutions didn't work for me either. 

Did you found something else ? :)

**Comment by samin-alabz** [comment] 2022-06-01 11:36
Just to put it out there and to help anyone who is still looking

`[raw/assets_fonts_galioextra] android/app/build/generated/res/react/release/raw/assets_fonts_galioextra.json
[raw/assets_fonts_galioextra] android/app/build/generated/res/react/release/raw/assets_fonts_galioextra.ttf
Error: Duplicate resources`

You have a file assets/fonts/galioextra.json which is shown as "assets_fonts_galioextra.json". Notice the other one has the same name, regardless of the extension.

Renaming one of the file will resolve this issue :)

**Comment by andreiciceu** [comment] 2023-02-17 08:00
The problem for my setup was this line in `app/build.gradle` leftover from older react-native versions:
```gradle
apply from: "../../node_modules/react-native/react.gradle"
```
removed it and build works now

**Comment by cortinico** [comment] 2023-02-17 08:50
> React Native version: 0.63.4

Closing as this is on a really old RN version, the issue is missing our template and is not actionable. Some of the workaround provided were also valid so there is nothing left for us to do here.

**Closed by cortinico** 2023-02-17 08:50 UTC
Labels: Needs: Triage :mag:
