### ISSUE TITLE
Dimensions.get('window') is not returning the current values on Android

### ISSUE THREAD

**Issue by pmulholland42** [facebook/react-native#29323] opened 2020-07-09 16:05 UTC
## Description
The width and height returned by Dimensions.get('window') are not updating. The first time it's called, it returns the correct values. But if I change the device screen orientation and call it again, it returns the same values as before. This only happens on Android, and only started happening after I upgraded from RN 0.62.2 to 0.63.0

## React Native version:
0.63.0
Android only

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Add an onLayout like this to a View in your app: `onLayout={() => {
      console.log(Dimensions.get('window'));
    }`
2. Rotate the device and notice that the width and height printed to the console stay the same after each rotation

## Expected Results
The width and height should update to reflect the new screen layout

**Comment by JamesClarkeFP** [comment] 2020-07-11 00:17
have you tried the newer useWindowDimensions()?

https://reactnative.dev/docs/usewindowdimensions

**Comment by pmulholland42** [comment] 2020-07-13 13:20
I haven't yet. Seems handy, but our app is all class components so we can't use it without rewriting them or wrapping them in function components.

**Comment by oliverdolgener** [comment] 2020-07-15 08:19
I can confirm. On Android the event listener wont trigger on orientation change. It makes no difference if we use `Dimensions.addEventListener('change', setWindowSize);` or `useWindowDimensions()`. On iOS it still works

**Comment by AndrewMorsillo** [comment] 2020-07-15 21:36
onLayout seems to have changed behavior in 0.63 but I'm not sure exactly how. It's breaking my app on iOS only right now by failing to call onLayout when a parent element resize causes a child element to move on the screen. Seems likely related to this issue. What changed with onLayout in 0.63?

**Comment by aryojamousi** [comment] 2020-07-16 15:48
weirdly, when using [this](https://github.com/react-native-community/hooks) package the device orientation changes get detected...

**Comment by NguyenKyThinh94** [comment] 2020-09-14 07:42
> I can confirm. On Android the event listener won't trigger on orientation change. It makes no difference if we use `Dimensions.addEventListener('change', setWindowSize);` or `useWindowDimensions()`. On iOS it still works

Yes, it not work with android !!

**Comment by CmerCy132** [comment] 2020-10-08 05:40
Any updates on this issue?

**Comment by R4DIC4L** [comment] 2020-10-08 13:52
I can confirm it is not working on android, but on iOS is it still ok. Using RN 0.63.2. Probably also happening on 0.63.3, I will try to update later.

This has broken my orientation-dependent rendering, I had to check the 'screen' dimensions to get the correct orientation change and I see a lag in the orientation layout change after device rotation of about 2-3 seconds (only on android).

**Comment by wmonecke** [comment] 2020-10-15 09:26
How is this issue still going on? How can such a popular framework not have a working Dimensions module?!

**Comment by AndrewMorsillo** [comment] 2020-10-15 16:57
This one is pretty mild, it has only been open for 3 months. There are outstanding bugs going on 4 years without solutions. There's a lot of undocumented, inconsistent-across-platforms, or (especially on Android) broken stuff in RN. FB has developed somewhat of a reputation for subpar community management with this project. Many issues get closed without resolution or explanation. PRs linger for months or years. Long standing bugs never get fixed/merged because FB has closed internal workarounds. etc, etc.

I'm not complaining however, it's free software, we can fork and fix it ourselves if the quirks bother us. It's just a shame to see an innovative and otherwise great project like RN marred and slowed by seemingly indifferent maintainers. 

As for a fix, I've found that many measurement problems on Android are corrected by doing two things:

1. Add `collapsible={false}` to your views you plan to measure. Even if you have a `ref` on a view Android/RN will still "optimize" (remove) it leading to unexpected behavior
2. Use a ref and the `.measure` function to get the measurement at the time you need it instead of relying on `onLayout`. Frequently `onLayout` doesn't get called when expected or doesn't return the values you expect because of animations or mounting behavior. Just be aware that `.measure` returns different values than `onLayout`. IIRC measure will give you the absolute pixel size on screen where onLayout gives you the untransformed original size (ex: if transform: [{scale: 2}] is on a view onLayout will give width: 50 and .measure will give width: 100)

**Comment by oleksandr-dziuban** [comment] 2020-10-19 21:20
@react-native-bot This is the really critical issue which breaks all Android orientation related styling in apps. When this can be reviewed by maintainers? Thanks...

**Comment by luisnaranjo733** [comment] 2020-11-11 19:24
The fix for this is checked into the master branch (thank you @ajpaulingalls and @ejanzer) and will naturally make its way into the first react-native@0.64 release candidates.
If you want it to be included in the future react-native@0.63.4 patch release, please upvote this comment.

https://github.com/react-native-community/releases/issues/212#issuecomment-725612630

**Comment by bigcupcoffee** [comment] 2020-12-24 20:17
I'd like to note that my issue about the dimensions API is still actuai, and dimensions is not working good with (at least) a split-screen feature, my issue is #30371 and it's still broken on 0.63.4(as I just tested), since the patch mentioned above was included in 0.63.4 I expected it to work, but it didn't do a thing to me.

Also let me know if I should close my issue(react with -1), since this one seems to be the same. Can anyone else also confirm the issue being present in 0.63.4, or am I trippin

**Comment by martingg88** [comment] 2021-03-15 14:36
any solution for this issue?

**Comment by jcabrerazuniga** [comment] 2021-03-16 00:44
Hi
     I am in this problem, too... any solutions?

**Comment by bigcupcoffee** [comment] 2021-03-17 15:13
@martingg88 @jcabrerazuniga https://github.com/facebook/react-native/issues/30371#issuecomment-794430866 might be pretty helpful for certain cases

**Comment by ws333** [comment] 2021-05-03 07:20
Dimensions.get('screen') still doen'tt update when rotating device. I have to close/reopen the app to get it to update.
Dimensions.get('window') seems to work though, but I use both in my app to calculate dim of statusbar/navbar.

RN version 0.64

**Comment by 0rsa** [comment] 2021-05-05 15:37
Hello,
I can't use orientation feature. useWindowDimensions() never fires or a console.log("dimensions") forcing a rerender is never updated with right values.
My app is already big and its is complicated to know what it can be conflicting

**Comment by jmsbrett** [comment] 2021-06-11 12:28
This is still an issue in 64.1.

**Comment by ws333** [comment] 2021-06-11 14:49
> This is still an issue in 64.1.

@jmsbrett Version [0.64.2](https://github.com/facebook/react-native/releases/tag/v0.64.2) seem to have a fix for it.

**Comment by bigcupcoffee** [comment] 2021-06-11 19:59
@ws333 just tested, 0.64.2 still got #30371 thought, going to bump it once again at 0.65 😩

**Comment by MrAdex77** [comment] 2021-07-02 14:18
Hi, is there any fix? still its not working for me on android

**Comment by bigcupcoffee** [comment] 2021-07-02 20:26
@MrAdex77 does it actually work on 0.64.2? Last time I tried it still had the same value for whatever split screen dimension I've put

**Comment by nickfujita** [comment] 2021-09-27 05:38
Updated to 0.63.4 from 0.63.3, and confirmed fixed on Android.

**Closed** 2021-09-27 08:51 UTC
Labels: Platform: Android, API: Dimensions, Needs: Triage :mag:
