### ISSUE TITLE
Animated spring callback not called immediately after the animation finishes

### ISSUE THREAD

**Issue by MarkOSullivan94** [facebook/react-native#20783] opened 2018-08-22 10:29 UTC
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment

Environment:
  OS: Linux 4.4
  Node: 9.4.0
  Yarn: Not Found
  npm: 6.2.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.3.1 => 16.4.2
  react-native: ^0.56.0 => 0.56.0

## Description

This issue had been originally brought up back in 2015 but was never sorted https://github.com/facebook/react-native/issues/1951

There is a noticeable delay in the callback which is triggered after the animation ends, this is a major issue whenever you want to hide / show content once the animation is finished and so it would be great if this delay could be completely eliminated.

I have noticed that Animated.timing(...) does not have this delay after the animation has finished.

## Reproducible Demo

I did try and get a expo snack demo working but wasn't able to. 

Below is the code I use to setup the animation
```
let animation = Animated.timing(
			this.state.animation,
			{
				toValue: finalValue,
			}
);

animation.start(this._animationFinishCallback());
```

Below is the callback trigger when the animation finishes.

```
_animationFinishCallback = () => {
		console.log("animationFinish");
};
```

**Comment by MarkOSullivan94** [comment] 2018-12-21 14:33
Not sure if this has been fixed, would be good if one of the React Native team could clarify.

**Comment by sunnylqm** [comment] 2018-12-25 08:56
@MarkOSullivan94  After a glance at the [source code](https://github.com/facebook/react-native/blob/a689711f680bb23795dea6391627383ca6973f88/ReactAndroid/src/main/java/com/facebook/react/animated/SpringAnimation.java#L115) here, I guess that you may try to increase `restSpeedThreshold` and `restDisplacementThreshold` of [spring](https://facebook.github.io/react-native/docs/animated#spring) to make it more "immediate" to end.

**Comment by khusmann** [comment] 2019-02-05 15:03
@sunnylqm @MarkOSullivan94 hmmm, I tried fiddling with `restSpeedThreshold` and `restDisplacementThreshold` but am not really observing an effect. There is still a delay for the callback to run after the animation stops.

**Comment by MoOx** [comment] 2019-04-09 18:19
With something like `restSpeedThreshold: 100, restDisplacementThreshold: 40` it can have a nice effect for an animation that cover an entire smartphone (eg: view swiped down to fold it a la Apple Music). Thanks for the pointer @sunnylqm

**Comment by satya164** [comment] 2019-05-30 16:54
Spring animations take a long time to fully settle. You can't notice the animation during the end because it's too slow, but it's still happening. You should be able to verify this by adding `addListener` on the animated value.

Closing because it's not a bug.

**Closed by satya164** 2019-05-30 16:54 UTC
Labels: API: Animated, Bug, Platform: Linux

**Comment by devproivansurzhenko** [comment] 2019-06-04 09:32
@MoOx You solution works pretty perfect in my case. Thank you!
