### ISSUE TITLE
[ListView.DataSource] Comprehensive documentation & Sorting/Grouping

### ISSUE THREAD

**Issue by yelled3** [facebook/react-native#1880] opened 2015-07-06 16:19 UTC
I was trying to understand how to work with `ListView.DataSource`;

one of the key use case that I was interested in is sorting;
my list is a collection of names, grouped by first letter:
```js
A:
  Adam,
  Amy,
B:
  Ben,
  Bob
...
```

where should the sorting and grouping logic be?
assuming I want to keep the list sorted and be able to add/remove rows.

the docs offered very little guidance:
http://facebook.github.io/react-native/docs/listview.html#datasource

aside from the code example: http://facebook.github.io/react-native/docs/listview.html#examples
there was nothing really in the docs about the `ListView.DataSource`.

the only thing close to a documentation, that I was able to find, was in the source:
https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/ListView/ListViewDataSource.js

another source that helped was:
http://www.reactnative.com/react-native-tutorial-for-creating-listview-with-section-headers/

but again, it was fairly limited.

so, I would like to suggest that  `ListView.DataSource` be added to the docs (as a page of it's own)
and include a few examples.
also, I think this a very common use case and should probably be included in the docs.

**Comment by octatone** [comment] 2015-07-28 12:24
:+1: 

The react-native abstractions around ListView and the accompanying data source, are very hard to reason about when provided with zero documentation.

**Comment by akabab** [comment] 2015-08-04 08:44
+1!

**Comment by yelled3** [comment] 2015-08-04 10:59
@ide @brentvatne /cc

**Comment by christopherdro** [comment] 2015-09-13 17:50
These examples should help anybody having trouble understanding how to deal ListView's dataSource.

Rows: https://rnplay.org/apps/d3DM6A
Rows with Sections: https://rnplay.org/apps/xnyaYw

@brentvatne You can maybe take a look at these examples. If they are good enough you can maybe fork them over to the account for the examples and link them inside the docs.

**Comment by ipsy-eric** [comment] 2016-03-10 00:01
:+1: The documentation literally says "See ListViewDataSource" lol

**Comment by mark0978** [comment] 2016-03-20 22:01
I'm going to say these don't help much more than the tutorial which doesn't show me anything but how to use a simple case of the datasource.  Maybe the datasource has no other features......

**Comment by SudoPlz** [comment] 2016-04-11 13:45
I don't understand Datasource either, did you finally get how it works?

**Comment by satya164** [comment] 2016-04-12 06:28
Duplicate of #410

**Closed by satya164** 2016-04-12 06:28 UTC

**Comment by JO-WTF** [comment] 2016-05-25 19:52
@christopherdro I have to say those examples are brilliant!

That solved my questions!

Thank you very much!!!

**Comment by JO-WTF** [comment] 2016-05-25 19:53
@christopherdro Well, it's a shame that I cannot copy the code from there though.

**Comment by christopherdro** [comment] 2016-05-25 20:26
@JO-WTF You can fork that example into your own account.

**Comment by JO-WTF** [comment] 2016-05-25 20:30
@christopherdro It's alright. I got the idea, that's the point :)

Thanks a lot. You have been really helpful.
