### ISSUE TITLE
Print: Entry, ":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by xclidongbo** [facebook/react-native#15444] opened 2017-08-10 06:27 UTC
### Is this a bug report?

(write your answer here)

** BUILD FAILED **

The following commands produced analyzer issues:

	Analyze /Users/lidongbo/Desktop/RN/AwesomeProject/node_modules/react-native/ReactCommon/yoga/yoga/YGNodeList.c
	Analyze /Users/lidongbo/Desktop/RN/AwesomeProject/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.c
(2 commands with analyzer issues)

The following build commands failed:
	PhaseScriptExecution Install\ Third\ Party /Users/lidongbo/Desktop/RN/AwesomeProject/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/double-conversion.build/Script-190EE32F1E6A43DE00A8543A.sh
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/AwesomeProject.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/AwesomeProject.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.47.1

2. `node -v`: v8.2.1

3. `npm -v`: 5.3.0

4. `yarn --version`:

Then, specify:

- Target Platform: iOS

- Development Operating System: macOS

- Build tools: iOS

### Steps to Reproduce

(Write your steps here:)

1. react-native init AwesomeProject
2. cd AwesomeProject
3. react-native run-ios

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by hramos** [comment] 2017-08-15 17:24
Duplicate of #14423

**Closed by hramos** 2017-08-15 17:24 UTC

**Comment by MaxiSantos** [comment] 2017-10-20 02:00
I could solved it by installing the 3rd party libraries
[ https://github.com/whg1412/ThirdParty]( https://github.com/whg1412/ThirdParty) from here [https://github.com/facebook/react-native/issues/14447](https://github.com/facebook/react-native/issues/14447)
