### ISSUE TITLE
pixel size (px) value of some style properties (padding, margin) may broke the app.

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [facebook/react-native#20206] opened 2018-07-14 14:24 UTC
## Environment
Run `react-native info` in your terminal and paste its contents here.
```
Environment:
  OS: Windows 10
  Node: 8.11.3
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: ~0.55.2 => 0.55.4
```
> I tried to use the latest version (0.56) but as [this issue](https://github.com/facebook/react-native/issues/14209) reported, it even failed to installed.

## Description
Just create an new app, and only try to add `padding: '20px'` into the style of view, then it broken and could not open again.
Nothing error found, both the app and the Metro Bundler Console. When I connect the android log (react-native log-android), I just found that:
```
CatalystInstanceImpl.destroy() start
```

## Reproducible Demo
``` javascript
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Text>Open up App.js to start working on your app!</Text>
        <Text>Changes you make will automatically reload.</Text>
        <Text /* style={{margin: '20px'}} */ >Shake your phone to open the developer menu.</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    // padding: '20px', // cancel the comment and the app will be broken.
  },
});

```

**Comment by jamsch** [comment] 2018-07-15 02:49
All dimensions in React Native are _unitless_, and represent density-independent pixels.

So for styles, you need to do the following:

```javascript
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
});
```

**Comment by zhengxiaoyao0716** [comment] 2018-07-15 08:15
@jamsch I know that, but I think it shouldn't cause the app broken without any error message.

**Comment by ggtmtmgg** [comment] 2018-07-21 02:03
I am trying to make first contribution, can I give it a try?

**Comment by kelset** [comment] 2018-07-23 09:37
> I know that, but I think it shouldn't cause the app broken without any error message.

Feel free to open a PR for that, in the meantime I'm closing this since it works as expected 😶

**Closed by kelset** 2018-07-23 09:37 UTC
Labels: :rewind:Old Version

**Comment by ggtmtmgg** [comment] 2018-07-26 01:57
I confirmed whether it reproduces on iOS or not.
On iOS, the exception is correctly handled.

**Comment by regalstreak** [comment] 2019-07-02 21:28
```
import { StyleSheet, PixelRatio } from "react-native";

...

  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20 / PixelRatio.get(),
  },

```

This will convert the absolute 20dp padding to 20px fixed. Useful for developers following a strict design spec or something like that. 

More info on [PixelRatio ](https://facebook.github.io/react-native/docs/0.8/pixelratio)
