### ISSUE TITLE
[Android] Gradle APK Sign issues since upgrade to 0.59

### ISSUE THREAD

**Issue by reime005** [facebook/react-native#24150] opened 2019-03-26 10:40 UTC
## 🐛 Bug Report
The android signing process seems to be broken since react-native version 0.59.0. I've upgraded from 0.57.8. 

After upgrading the project, this did not work anymore. The passwords are getting passed correctly to the gradle taskGraph part. They seem to be overridden or assigned too late in the build process.

My guess is there was some change in gradle, which changed the build order. Thanks for your help.

## To Reproduce
* Initialize react native project
* Configure your project for app signing
* Build using the following:`./gradlew assembleRelease -PkeyPass=mySecretKey -PkeystorePass=mySecretKeystorePass`

## Expected Behavior
Signing should work.

## Stack Trace
```
> Task :app:packageRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageRelease'.
> com.android.ide.common.signing.KeytoolException: Failed to read key com.foo.app from store "/Users/foo/app/store.keystore.": Keystore was tampered with, or password was incorrect
```

## Code Example
```
// android/app/build.gradle

gradle.taskGraph.whenReady { taskGraph ->
    if (taskGraph.hasTask(':app:assembleRelease')) {
        android.signingConfigs.release.storePassword = keystorePass
        android.signingConfigs.release.keyPassword = keyPass
    }
}
...
android {
    ...
    signingConfigs {
        release {
            storeFile file(MY_STORE_FILE)
            keyAlias MY_STORE_ALIAS
            storePassword ''
            keyPassword ''
        }
    }
    ...
    buildTypes {
        release {
            ...
            signingConfig signingConfigs.release
            ...
        }
    }
    ...
```
## Environment
```
  React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
      Memory: 12.72 GB / 32.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        Build Tools: 23.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.2, 27.0.3, 28.0.2, 28.0.3
        API Levels: 14, 21, 23, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: ^0.59.1 => 0.59.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2
      react-native-git-upgrade: 0.2.7
```

**Comment by kelset** [comment] 2019-03-26 10:57
Can you create a repro of this issue?

I feel it may be something that is related to your project upgrade process, as I didn't experience a similar issue.

**Comment by pilgr** [comment] 2019-03-26 21:44
what I found is that `gradle.taskGraph.whenReady` doesn't work anymore. haven't find the solution yet.

**Comment by darekg11** [comment] 2019-03-27 12:49
Did you try to see if entering your password directly in `build.gradle` makes it work? Because we are at `0.59.2` and everything works without any problems. We are using `System.getenv` calls in signing configuration.

**Comment by pilgr** [comment] 2019-03-27 13:10
yeah I realized the problem is with `android.signingConfigs.release.storePassword = keystorePass`, it just doesn't set the value to the release config.

**Comment by kelset** [comment] 2019-03-28 10:55
It seems to me that then it's not a react-native issue...?

I'm going to close this since there is no repro, but I'll reopen if there is one 🤗

**Closed by kelset** 2019-03-28 10:55 UTC
Labels: Platform: Android, Resolution: Needs Repro, Type: Bug Report

**Comment by abdurahmanadilovic** [comment] 2019-04-29 13:57
I had the same issue, the problem was due to gradle cache, I tried to build my app while hard-coding a wrong password in the app gradle file and that password got cached in the gradle build process. So I just cleaned the project from android studio and the new gradle config took affect, which generated a signed apk successfully. 

I just ran grep to find out where was the old keystore path saved, as it turned out: in some build folder
```
grep -r "keystores/release_keystore_3.jks" .
````
Returned this
```
./app/build/intermediates/signing_config/release/out/signing-config.json:{"mName":"release","mStoreFile":"/somepath/keystores/release_keystore_3.jks","mStorePassword":"","mKeyAlias":"test","mKeyPassword":"test","mStoreType":"pkcs12","mV1SigningEnabled":true,"mV2SigningEnabled":true}
```

So try to clean the project from android studio and then run ./gradlew assembleRelease

**Comment by ndvbd** [comment] 2019-05-16 08:34
Any solutions?

**Comment by reza7rm** [comment] 2019-05-27 09:11
I have the same issue in "react-native": "0.59.5".
I had no problem signing the apps in previous versions. double checked everything, created another keystore, but not working

**Comment by tereshchenkoartyom94** [comment] 2019-05-27 12:48
The same problem for me, just updated to a 0.59.8 and my release build doesn't work anymore

**Comment by tereshchenkoartyom94** [comment] 2019-05-27 13:03
Thanks, @abdurahmanadilovic, your solution works!

**Comment by madhudskumar** [comment] 2019-07-08 11:45
./gradlew clean in android folder and rebuild

**Comment by 889149885** [comment] 2019-08-02 19:48
./gradlew clean worked for me
