### ISSUE TITLE
[Android 0.13.0] Websockets throws exception 'No transports available' with Firebase

### ISSUE THREAD

**Issue by yeso126** [facebook/react-native#3645] opened 2015-10-23 21:47 UTC
I'm using Firebase sdk which uses websocket, when I create a ref to my firebase I get the message.

**Comment by ide** [comment] 2015-10-23 22:03
Can you debug what's going on e.g. where the source of the error is?

**Comment by yeso126** [comment] 2015-10-23 22:29
I'm on windows so debugging does not work. :(  ![error](http://imgur.com/NIxoYZn)

**Comment by mkonicek** [comment] 2015-10-23 23:45
Wait you don't even see line numbers? The source map is fetched asynchronously. Do the line numbers appear after a while. It's possible source maps are not supported yet on Windows.

**Comment by mkonicek** [comment] 2015-10-23 23:45
Would be good to know whether source maps work or not. If more people confirm we should add it here:
https://facebook.github.io/react-native/docs/linux-windows-support.html

**Comment by yeso126** [comment] 2015-10-24 15:36
I've updated to 0.13.1 
Looks like it has something to do with firebase 
![error](http://i.imgur.com/HxX4kxC.png)

**Comment by satya164** [comment] 2015-10-24 17:33
I've been using WebSockets with socket.io for sometime now. I had to disable the `jsonp` transport for it to work.

**Comment by mkonicek** [comment] 2015-10-26 23:27
Interesting! Can you try using non-minified version of Firebase and reading it source at the place where it happens / Googling why Firebase throws this error?

**Comment by mkonicek** [comment] 2015-10-26 23:27
I'm glad the source maps are working for you!

**Comment by puf** [comment] 2015-11-13 01:25
@satya164 @ide 
This problem seems to be caused by the loading order. If you use this order it works:
```
var React = require('react-native')
var Firebase = require('firebase');
```

But if you swap them around, you get the problem described:

```
var React = require('react-native')
var Firebase = require('firebase');
```

It seems like the WebSocket polyfill is being loaded as part of the react-native module, which unfortunately doesn't work.

So the work-around for the issue is to ensure you require react-native first, but it's still a bug. WebSockets are natively available on most browsers, so it's better to ensure they're available before module loading starts.

**Comment by yeso126** [comment] 2015-11-13 01:33
omg, how didn't I think about that? thanks

**Comment by ide** [comment] 2015-11-13 01:47
@puf, yes this is a known issue. For the time being, always start your entry point off with requiring/importing react-native. Would appreciate a PR adding that to the troubleshooting docs.

**Comment by puf** [comment] 2015-11-13 02:07
https://github.com/facebook/react-native/pull/4108

**Comment by mkonicek** [comment] 2015-11-13 15:30
Oh OK this is a tough one :) It would be amazing if you could send a PR to Firebase to make that error message more explanatory. Any better ideas?

**Comment by puf** [comment] 2015-11-13 15:42
The Firebase client tries to use WebSockets to connect to the server, but they are missing (because the polyfill is not loaded yet). It then tries to fall back to long-polling, which it also cannot do in the context of React Native. So it finally throws an error that it cannot find a suitable transport mechanism to connect to the server.

I think we'll have a better chance at people finding this issue (and the workaround of putting the require() statements in the right order) now that it's properly labeled/titled.

**Comment by mkonicek** [comment] 2015-11-14 19:28
Linked here: https://productpains.com/post/react-native/firebase-not-working-on-android/

Thanks so much for reporting and debugging this and adding the docs @puf!

I'll close this one as it looks like the issue is solved.

**Closed** 2015-11-14 19:29 UTC

**Comment by puf** [comment] 2015-11-15 00:23
The cause of the problem is clear, there is a workaround, and we documented it to make it more findable. 

But there is still an underlying problem in the loading order of dynamic modules vs polyfills for native functionality (such as WebSockets). @ide commented that this was a known issue, in which case this report should probably be linked to that known issue too.

**Comment by paramaggarwal** [comment] 2016-08-16 15:49
@puf you mentioned:
> It then tries to fall back to long-polling, which it also cannot do in the context of React Native.

Why so? I am looking to using socket.io in `['polling', 'websocket']` mode with `jsonp: false`. THis is because unencrypted websockets won't work in certain client network proxies.

**Comment by puf** [comment] 2016-08-16 16:22
Hmm... I don't remember why I commented with that.
I think at the time it was related to requiring the window object (possibly
related to JSONP).
Sorry I can't be of more help.
