### ISSUE TITLE
NetInfo always returns offline

### ISSUE THREAD

**Issue by cloudify** [facebook/react-native#873] opened 2015-04-16 04:15 UTC
Not sure if this used to work in previous releases, but in latest (`0.3.11` and 2cc3c50235c73c530a29633d4273e8f2950299d5) it always return `offline`. I tried both APIs (`NetInfo.reachabilityIOS` and `NetInfo.isConnected`) and also the `UIExplorer` demo seem broken.

![netinfo-bug](https://cloud.githubusercontent.com/assets/48206/7173930/8b204356-e3cd-11e4-8949-26ae2ff5733f.gif)

**Comment by soheil** [comment] 2015-04-16 18:07
+1

**Comment by brentvatne** [comment] 2015-04-19 00:14
@cloudify @soheil - I don't have a device on me at the moment so I can only test in the simulator and was able to confirm this, could you test this on a device and let me know if it works there? Thanks! :smile:

**Comment by soheil** [comment] 2015-04-20 01:58
Tested on device with the same results.

**Comment by brentvatne** [comment] 2015-04-20 05:30
cc @tadeuzagallo - I stepped through `RCTReachability` and couldn't find the root cause of the issue - `RCTReachabilityCallback` always enters the `RCTReachabilityStateNone` block, any ideas?

**Comment by soheil** [comment] 2015-04-20 05:38
Just throwing a few ideas out there: 1. using an old version? 2. multiple
definition for `RCTReachability`?

**Comment by nicklockwood** [comment] 2015-04-20 10:27
OK, it turns out that this is because I used "http://apple.com" as the host, when it should just be "apple.com". Dumb mistake 😞

I've submitted a fix which should land shortly. In the meantime, if you make that change yourself locally inside RCTReachability.m, it will solve the problem.

**Comment by brentvatne** [comment] 2015-04-20 16:58
thanks @nicklockwood :smile:

**Comment by soheil** [comment] 2015-04-20 17:05
Good stuff!

**Comment by cloudify** [comment] 2015-04-20 18:22
thanks @nicklockwood !

**Comment by lazywei** [comment] 2015-04-22 07:14
@nicklockwood the modification works. However, I noticed that the passed `reachability` is not correct. For example, with the code:
```
  _handleReachabilityChange(reachability) {
    alert(reachability);
  },

  componentDidMount() {
    NetInfo.reachabilityIOS.addEventListener(
      "change",
      this._handleReachabilityChange
    );
  },
```

When I first disable the network, it will popup "wifi". After that, when I enable the network, it will popup "none". I think this is incorrect? I'm trying this on simulator.

Thanks.

**Comment by nicklockwood** [comment] 2015-04-22 11:00
It's working for me on device and simulator, but I vaguely recall there was a bug on OSX reachability that may have been fixed in 10.10.3. If you haven't upgraded yet, that might explain why you're seeing this.

**Comment by nicklockwood** [comment] 2015-04-22 11:02
To be clear, the bug was on Mac OS, so it only affected the simulator. As far as I know, it should work fine on the device for all iOS versions.

**Comment by soheil** [comment] 2015-04-22 18:37
I can verify that the problem occurs on device as well.

**Comment by brentvatne** [comment] 2015-04-22 22:20
@soheil - with `RCTReachability.m` updated to refer to `apple.com` rather than `http://apple.com`?

**Comment by soheil** [comment] 2015-04-22 23:44
@brendanv with the host change it works fine on device now!

**Comment by brentvatne** [comment] 2015-04-22 23:47
Great! @brendanv sorry you've been getting pinged for me so much on this repo for some reason!

**Comment by soheil** [comment] 2015-04-23 00:05
I doubt he minds it. I always assumed github was smart enough to first show repo-related usernames in the auto-complete dropdown, but I guess I was WRONG!

**Comment by brentvatne** [comment] 2015-04-23 00:46
@soheil - haha seems like that would be a useful feature indeed

**Comment by brentvatne** [comment] 2015-05-31 00:13
Fixed in bbd52595864a3ac6469b46b3789b882b51f33e86

**Closed by brentvatne** 2015-05-31 00:13 UTC

**Comment by TimonSotiropoulos** [comment] 2015-08-10 01:17
I am having the same issue however I do have the updated version of RCTReachability. I am currently running react-native 0.4.4 on this project with basically the same code as is on the NetInfo docs. Maybe I'm missing something super obvious, but even when the simulator is correctly downloading content off the internet, NetInfo.isConnected only returns false.

    componentWillMount: function() {
        var self = this;
        NetInfo.isConnected.fetch().done((isConnected) => {
            console.log("Initial Network Connection Status Obtained.");
            console.log("Current Status is: " + isConnected);
            self.setState({
                networkConnected: isConnected
            });
        });
    },
    componentDidMount: function() {
        UserStore.listen(this._onChange);
        NetInfo.isConnected.addEventListener('change', this._updateNetworkStatus);
    },
    componentWillUnmount: function() {
        UserStore.unlisten(this._onChange);
        NetInfo.isConnected.removeEventListener('change', this._updateNetworkStatus);
    },
    getInitialState: function() {
        return {
            User: UserStore.getState().User,
            networkConnected: null
        };
    },
    _updateNetworkStatus(isConnected) {
        console.log("Network Connection Status Changed");
        console.log("Current Status is: " + isConnected);
        this.setState({
            networkConnected: isConnected
        });
    },

I've triple checked my RCTReachability and it does have the above mentions changed within it. Any help would be greatly appreciated.

**Comment by nicklockwood** [comment] 2015-08-10 08:18
@TimonSotiropoulos the critical fix in this case was the change in RCTReachability.m from:

     [self initWithHost:@"http://apple.com"];

to

     [self initWithHost:@"apple.com"];

Do you have that?

**Comment by TimonSotiropoulos** [comment] 2015-08-11 00:06
Hi Nick, it definitely has the second line of code in RCTReachability.m. I have done a bit more testing this morning and it seems to be correctly firing events when the simulator status is going from online -> offline (I guess is just needed an afternoon off!), however the reverse isn't causing the event to fire. I will do some additional testing as I have a few calls to Parse that could be blocking the event from firing. If I can't figure out the issue i'll create a new app with just NetInfo and do some more testing directly on that.

**Comment by TimonSotiropoulos** [comment] 2015-08-11 03:18
Further to the above comment, I have tested with a brand new project and on an actual device and it all seems to be working as expected. It seems to be only not working when trying to test in the simulator, essentially turning the wifi of the computer off correctly caused the test to fail, however when the wifi is turned back on it doesn't seem to fire the event telling the app you are connected again. I then have to close the simulator and re-open the simulator with the internet connection running for it to recognise that the connection is back. 

Not sure if this is a React Native issue or an actual XCode one though, as it seems simulating a dropped connection in the simulator can be relatively problematic. Has anyone had any success testing the NetInfo stuff inside the simulator?

**Comment by nicklockwood** [comment] 2015-08-11 06:39
@timonsotiropoulos as I mentioned above there is/was a bug in Mac OS that caused reachability updates to fail on the simulator. I guess that's still the case. As long as it works on the devuce though, I'm not too concerned.

Reachability should only ever be used as a diagnostic tool btw, so if you try to make an XHR request and it fails, reachability is a good way to find out why (no network signal), but you shouldn't ever assume that because reachability says you do or don't have a connection that you will or won't be able to make a network request successfully.

In otherwords, you should design your app to function the same regardless of whether reachability is working correctly.
