### ISSUE TITLE
Can't find variable: require

### ISSUE THREAD

**Issue by lebronjl** [facebook/react-native#21475] opened 2018-10-04 10:49 UTC
## Environment
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
      Memory: 4.07 GB / 15.43 GB
    Binaries:
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5014246

## Description
When created a new project from scratch. The emulator/real device shows the next error:

![screenshot_2018-10-02-14-11-41-648_com react057test](https://user-images.githubusercontent.com/493384/46469456-bb590380-c7d3-11e8-85ed-752e9f587e05.png)

It does not happen on all the machines, but I don't know what is making it break.

The RN version is 0.57.1

## Reproducible Demo
Create a new project from scratch and try to run on android from Windows.

**Comment by kelset** [comment] 2018-10-05 08:41
> Create a new project from scratch
can you detail what you mean with that?

It seems that your error is related someway to the bundler, but I can't really understand what about it would cause it.

Using older versions of React Native make the problem disappear?

**Comment by lebronjl** [comment] 2018-10-05 10:52
Hi. I created a new project (react-native init awesomeproject) and then tried to run in on an android emulator. The error appears randomly and it seems to be related to the bundler. 

When I downgrade to 0.55.x react-native version everything runs ok.

**Comment by kelset** [comment] 2018-10-05 11:08
uhm understood, can you also try the workaround suggested here? https://github.com/facebook/react-native/issues/21490

I know it's not exactly the same but may be worth a shot.

**Comment by kelset** [comment] 2018-10-05 12:51
Actually, duplicate of https://github.com/facebook/react-native/issues/21048

**Closed by kelset** 2018-10-05 12:51 UTC
Labels: 📦Bundler

**Comment by Tecode** [comment] 2018-10-24 04:34
I solved this problem on babel7
```
  React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
      CPU: x64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
      Memory: 2.78 GB / 15.54 GB
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
      Yarn: 1.10.1 - /usr/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.10.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.0 => 0.57.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1

```
Configure babel.config.js(Not a .babelrc file, it seems to be a problem)
```
module.exports = function (api) {
    api.cache(true)
    const presets = [
        "module:metro-react-native-babel-preset"
    ];
    const plugins = [
        "@babel/plugin-transform-flow-strip-types",
        ["@babel/plugin-proposal-decorators", { "legacy": true }],
        ["@babel/plugin-proposal-class-properties", { "loose" : true }],
        "@babel/plugin-transform-regenerator",
        "@babel/plugin-transform-async-to-generator",
        "@babel/plugin-transform-runtime"
    ];

    return {
        presets,
        plugins,
        'sourceMaps': true,
    };
}
```
My project [#react-native-mobx](https://github.com/Tecode/react-native-mobx) you can try it
