### ISSUE TITLE
[WebView] not calling onNavigationStateChange when some link is clicked 

### ISSUE THREAD

**Issue by ucoker** [facebook/react-native#7602] opened 2016-05-17 14:27 UTC
- [ ] Provide a **minimal code snippet** / [rnplay](https://rnplay.org/) example that reproduces the bug.
- not calling onNavigationStateChange when some link is clicked in WebView.
	
	```js
	_onNavigationStateChange(navState) {
		console.log('_onNavigationStateChangeevent:',navState);
	}
	
	render() {
		return(
			<WebView
				style={{
				  flex:1,
				  marginTop:20
				}}
				ref={WEBVIEW_REF}
				source={{uri: 'https://www.tumblr.com/explore/text'}}
				scalesPageToFit={true}
				contentInset={{bottom:44}}
				onLoadStart={this._onLoadStart.bind(this)}
				onLoad={this._onLoadEnd.bind(this)}
				onNavigationStateChange={this._onNavigationStateChange.bind(this)}
				onShouldStartLoadWithRequest={this._onShouldStartLoadWithRequest}
				startInLoadingState={true}
				javaScriptEnabled={true}
				domStorageEnabled={true}
			/>
		);
	}
	```
  
- [ ] Provide **screenshots** where appropriate
- calling onNavigationStateChange method when first time open.
![qq20160517-1](https://cloud.githubusercontent.com/assets/12216739/15323882/95d2cf98-1c76-11e6-95b8-cfe1d24cd2a6.png)
- not calling onNavigationStateChange when I clicked the Photos button.
![qq20160517-2-2](https://cloud.githubusercontent.com/assets/12216739/15325083/cd5e3934-1c7b-11e6-8415-57e037a167eb.png)
- onNavigationStateChange method is called when I clicked the Reload button.
![qq20160517-3](https://cloud.githubusercontent.com/assets/12216739/15325115/e8f50998-1c7b-11e6-84cc-d90ddb16deb8.png)

- [ ] What's the **version** of React Native you're using?

	```"react-native": "^0.25.1"```

- [ ] Does this occur on iOS, Android or both?

	```I test in iOS.```

- [ ] Are you using Mac, Linux or Windows?

	```Mac OS X EI Capitan 10.11.4```

**How to know the navState if the onNavigationStateChange method is not called?**

**Comment by DanielMSchmidt** [comment] 2016-05-18 12:52
The problem is, AFAIK, that `_onNavigationStateChange` relies on `_onLoadingStart` and the iOS Implementation is [here](https://github.com/facebook/react-native/blob/774296b26349dbf6a1a0ccb1a870e3038ea2e046/React/Views/RCTWebView.m#L211)

As you may see it may only get information about a page load that is going to happen or has happened. The app you are using is a single page web application, which does not trigger native load events (as you may see if you switch to the network tab, no new route is requested directly). So in fact, this is currently expected behavior. If you would like to change this, [you should file an issue at procut pains](https://productpains.com/product/react-native).

**Comment by DanielMSchmidt** [comment] 2016-05-18 12:53
@facebook-github-bot expected

**Comment by facebook-github-bot-1** [comment] 2016-05-18 12:56
The comment above tells me this is expected behavior. Closing this as we'd like to use the GitHub issue tracker for bugs. If you'd like to change how this feature works please post a feature request on [Product Pains](https://productpains.com/product/react-native/) so that other people can vote on it.

**Closed by facebook-github-bot-1** 2016-05-18 12:56 UTC
Labels: Ran Commands

**Comment by slender9168** [comment] 2017-06-01 18:39
@ucoker did you manage to find a workaround ?

Thanks.

**Comment by Xaber20110202** [comment] 2017-10-31 14:02
@ucoker @slender9168  you can inject script like this
`
;(function() {
  var history = window.history;
  var pushState = history.pushState;
  history.pushState = function(state) {
    setTimeout(function () {
      window.postMessage(JSON.stringify({
        type: 'navStateChange',
        navState: { url: location.href, title: document.title }
      }))
    }, 100)
    return pushState.apply(history, arguments)
  }
})()
`
and then, handle the bridge message to change nav state. another thing is, use url compare to go back, don't use canBack, like this
`
const compareUrl = (u1 = '', u2 = '') => {
    return u1.split('?')[0].replace(/\/$/, '') === u2.split('?')[0].replace(/\/$/, '')
}
`

**Comment by uuau99999** [comment] 2018-03-21 06:55
@Xaber20110202 Your code does work but in ios, however, everytime the web page pushes state, it will trigger the webview onLoadStart event double times than it last triggers, which may lead to serious performance impact when the page is navigating to a deep level.
