### ISSUE TITLE
BackHandler and remote debug

### ISSUE THREAD

**Issue by sm2017** [facebook/react-native#15497] opened 2017-08-15 08:34 UTC
### Is this a bug report?

(Yes)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Yes)

### Environment

1. `react-native -v`:
```
react-native-cli: 2.0.1
react-native: 0.47.1
```

2. `node -v`:
```
v8.1.3
```

3. `npm -v`:
```
5.0.3
```

4. `yarn --version`:
```
0.27.5
```

Then, specify:

- Target Platform: Android

- Development Operating System: Windows10

- Build tools: `react-native run-android`

### Steps to Reproduce

(Write your steps here:)

```js
class App extends Component {
  componentDidMount() {
    BackHandler.addEventListener('hardwareBackPress', this.onBackPress);
  }
  componentWillUnmount() {
    BackHandler.removeEventListener('hardwareBackPress', this.onBackPress);
  }
  onBackPress = () => {
    return true;
  };
  render() {
    return (
      <Text>Press back buton</Text>
    );
  }
}
```
If you run the code in `development` environment , it don't works and when you press back button , app will be closed , but in `development` environment if you turn on `remote debug` , the code works well and app not closed

### Expected Behavior

(Prevent closing app on back button pressed)

### Actual Behavior

(On `development` environment when `remote debug` is off it don't woks but when `remote debug` is on it works)

### Reproducible Demo

(N/A)

**Comment by sm2017** [comment] 2017-08-30 15:33
Any updates??

**Comment by Sean-Snow** [comment] 2017-09-04 11:31
+1

**Comment by hramos** [comment] 2017-09-07 17:21
Can you reproduce the issue using [Snack](http://snack.expo.io)? This step is necessary for people to be able to see and debug the issue being reported.

**Comment by sm2017** [comment] 2017-09-11 11:20
@hramos I explain in details how to reproduce the issue , I cannot reproduce the issue using Snack because there is no dev menu in Snack and you cannot turn on remote debug

**Comment by hramos** [comment] 2017-09-11 18:09
You can run the Snack within the Expo Client and shake the device to trigger a menu to show up, no? 

In any case, this is a community project. To answer your "any updates?" question, we'd take a look at any PR that proposes a fix.

**Comment by sm2017** [comment] 2017-09-12 04:58
@hramos , I tried before using Expo Client , there is no dev menu , You can try it yourself
exp://expo.io/@snack/SJn2le4cZ

**Comment by dantman** [comment] 2017-09-27 19:03
@sm2017 Is there a Symbol polyfill included by your app or any of your dependencies?

If you do, than this could be caused by issue #11968, which I have a PR to fix #15182.

**Comment by howilliams** [comment] 2017-11-28 07:35
Hi, I am having the same trouble with it.
I am trying to implement custom action for back button and I have added the code like the below.
But it's getting an event when I enable "Debug JS Remotely" but it's not getting an event when I disable it. What's up?
I am trying to implement that backbutton functionality and I am having trouble with that.

componentDidMount () {
        ToastAndroid.show("Event Listener added", ToastAndroid.SHORT);
        BackHandler.addEventListener('hardwareBackPress', () => this.backAndroid()) // Listen for the hardware back button on Android to be pressed
}

componentWillUnmount () {
        BackHandler.removeEventListener('hardwareBackPress', () => this.backAndroid()) // Remove listener
}

backAndroid () {
        ToastAndroid.show("Welcome", ToastAndroid.SHORT);
        // Actions.pop() // Return to previous screen
        return true // Needed so BackHandler knows that you are overriding the default action and that it should not close the app
}

**Comment by howilliams** [comment] 2017-11-28 07:42
@sm2017, have you resolved this issue?

**Comment by sm2017** [comment] 2017-12-13 12:13
@howilliams No
Everybody that have same issue , Please add a `+1` comment here

**Comment by krunalpanchal** [comment] 2017-12-13 18:35
Same issue here, is there any workaround ?

**Comment by Victoriayangx** [comment] 2017-12-27 08:40
i met this issue too, when i open debugger,android back button works well to go back to the previous page,but when i close debugger or release a version ,press back button just lead to exit app.Pls help to solve this issue asap,thanks.

**Comment by dantman** [comment] 2017-12-27 08:49
@Victoriayangx Please upgrade to 0.51, your likely encountering a bug that has already been fixed.

**Comment by cooleagle8837** [comment] 2017-12-28 15:18
Hey, @dantman.
I found out that Version0.51 has some upgraded codes but it does not work at all.

<img width="420" alt="screenshot at dec 28 19-17-03" src="https://user-images.githubusercontent.com/30376020/34414623-ccb19bc6-ec03-11e7-821a-e99f84108a81.png">

<img width="336" alt="screenshot at dec 28 19-08-50" src="https://user-images.githubusercontent.com/30376020/34414457-e55b465a-ec02-11e7-9dc7-6f126394e1b0.png">

It still doesn't work in normal mode, but it's working on 'Debug Only' mode and it's really really weird.

I have spent 2 days to track the issues and found out that it's the same on version 0.51.

I am gonna attach another screenshot when we run it in the 'Debug Mode'.
<img width="568" alt="screenshot at dec 28 19-16-52" src="https://user-images.githubusercontent.com/30376020/34414634-d5be8dfa-ec03-11e7-8f6b-5fcf94d9d3cb.png">

As you can see, in the debug mode, the Set are converted well to Array var but that doesn't work in normal mode.

**Comment by cooleagle8837** [comment] 2017-12-29 08:29
HI, @sm2017. Have you found the round-about?

**Comment by Navneet2105** [comment] 2017-12-30 11:14
Hi @sm2017, I am facing the same issue. I am using React Navigation. When the remote debug mode is on, the back handler works perfectly,
After turning the remote debug off or in release mode of the app, the back handler doesn't work.
Have you found a way to fix this behavior?

**Comment by Victoriayangx** [comment] 2018-01-05 06:18
I changed the source code in BackHandler.android.js,then it worked.

**Background:**
After redux integration with react-navigation,i also met this issue.
refer:https://reactnavigation.org/docs/guides/redux


**SourceCode:(react-native/Libraries/Utilities/BackHandler.android.js)**
RCTDeviceEventEmitter.addListener(DEVICE_BACK_EVENT, function() {
  var subscriptions = [];
  var invokeDefault = true;

  _backPressSubscriptions.forEach(item=>subscriptions.push(item));
  for (var i = 0; i < subscriptions.length; ++i) {
    if (subscriptions[subscriptions.length-1-i]()) {
      invokeDefault = false;
      break;
    }
  }
  // var backPressSubscriptions = new Set(_backPressSubscriptions);
  // var invokeDefault = true;
  // var subscriptions = [...backPressSubscriptions].reverse();
  // for (var i = 0; i < subscriptions.length; ++i) {
  //   if (subscriptions[i]()) {
  //     invokeDefault = false;
  //     break;
  //   }
  // }

  if (invokeDefault) {
    BackHandler.exitApp();
  }
});

**Comment by cooleagle8837** [comment] 2018-01-05 06:44
Bingo!!! This works.
Good job, @Navneet2105.

Can you fork the repo and submit a merge request so that the developers all over the world would get updated one.

**Comment by Navneet2105** [comment] 2018-01-06 19:14
Hey Guys. For me, this issue for Back Handler was due to a react-native-pathjs-charts package that was being used. I created a new solution and added each package one by one and kept on testing. 

Path js package stopped the back handler. ES6 syntax distribution for that package worked for me. I copied that files and add that to my component and used it from there.

Same package or some other package might have caused the same for you.

**Comment by krunalpanchal** [comment] 2018-01-07 02:54
Hi Navneet,

Can you please explain me what exactly is to be done? I am using react-native-pathjs-charts in my project, so can you please explain me what is to be changed and where?

**Comment by AgNm** [comment] 2018-01-08 12:13
@Victoriayangx Thanks a ton!!! 💃  you are my saviour

**Comment by Victoriayangx** [comment] 2018-01-10 03:27
@dantman ,
Hi, **I suspect BackHandler cause App exit maybe caused by “new Set”.**

Recently I met another issue  about duplicate remove in Array.
1、By using "**let newArray = Array.from(new Set( array ))**" ,  in debug mode, the  newArray shows ok ,when close debug mode or release mode, sometimes the newArray  shows ok ,sometimes the newArray shows empty. it is not stable for App.
2、By using forEach & indexOf to remove the duplicate  element in array, it alaways shows ok till now.  


So,I suspect BackHandler cause App exit maybe also caused by “new Set”. So in Our React-Native Project, to achieve remove duplicate in Array , we will not use new Set untils the issue is resolved. 

Hope it can help.Any advice,pls let me know.thanks.

**Comment by dantman** [comment] 2018-01-10 04:30
@Victoriayangx You're basically describing the same things I researched when I had the issue: https://github.com/facebook/react-native/issues/11968#issuecomment-296543410

There's also a fair bit of comparison of various methods of iterating in the comments of my PR:
https://github.com/facebook/react-native/pull/15182

**Comment by Victoriayangx** [comment] 2018-01-10 08:00
@dantman  i get it, you are awesome.

**Comment by Navneet2105** [comment] 2018-01-11 14:05
@krunalpanchal 

I was using the **Radar graph** from the react-native-paths-js.

Download the es6 folder from the below link:

https://github.com/andreaferretti/paths-js/tree/master/dist

Add a new folder in your components section in your app. Let us say, I added the folder named as **Radar**. Create a new folder named as **charts** inside the Radar folder. Copy all the files of the es6 folder to that chart folder.

Now create a new js file( **CustomRadar.js** in my case ) for the graph which you are using in the Radar folder. I was using Radar graph. So, I copied the Radar.js from the following link :
https://github.com/capitalone/react-native-pathjs-charts/tree/master/src

You can copy the type of js file based on the graph you are using. Now you have created your own path js library under the components folder.

In CustomRadar.js ( in my case), make sure all the references in that copied content are pointing to the same files name under your component. If your custom file requires any reference file which is not yet added to the Radar folder. Just add that file to your folder and the alter the reference path.

Make sure all the file references path are pointing to the custom files we added.

**Comment by dbalodia** [comment] 2018-03-14 09:12
@Victoriayangx Is there any solution other than changing in the library because I am using Expo that won't allow me to make the change in the library.

**Comment by jerolimov** [comment] 2018-04-30 17:57
Hi, I created a PR which fixes this issue in react-native.

Maybe you can verify this this change and give a thump up for #19077, so that we get this fix in the next react-native release. 😄

**Comment by vyshakh** [comment] 2018-05-13 07:58
This fix worked for me.  https://github.com/facebook/react-native/issues/3223#issuecomment-355064410

**Comment by nimeshgurung** [comment] 2018-05-30 14:20
This issue occurred for me when pulling in `core-js/es6/symbol` in the app. Used `es6-symbol` instead which does not seem to conflict with `babel transforms` or `JavascriptCore` which is where I think the issue is when `core-js/es6/symbol` is imported.

`bable-react-native-preset@5.0.0` supports `Symbol` as far as I can tell but that throws another error, so can't really verify.

For other people the issue could be happening because the polyfill is being imported from third party, might be able to override how `symbol` is being pulled in via `rn-cli.config.js`.

**Comment by rayj10** [comment] 2018-06-26 04:42
still getting the problem and won't be able to change android folder because I'm using expo, please someone from RN, take one of the PRs here into consideration, really need it to work! :(

**Comment by princepardeep** [comment] 2018-06-28 12:15
@Victoriayangx You are the great buddy.

Working like this in 54.2


var DeviceEventManager = require('NativeModules').DeviceEventManager;
var RCTDeviceEventEmitter = require('RCTDeviceEventEmitter');

var DEVICE_BACK_EVENT = 'hardwareBackPress';

type BackPressEventName = $Enum<{
  backPress: string,
}>;

var _backPressSubscriptions = new Set();

RCTDeviceEventEmitter.addListener(DEVICE_BACK_EVENT, function () {
  var invokeDefault = true;
  var subscriptions = [];

  // var subscriptions = Array.from(_backPressSubscriptions.values()).reverse();
  _backPressSubscriptions.forEach(item => subscriptions.push(item));
  for (var i = 0; i < subscriptions.length; ++i) {
    if (subscriptions[i]()) {
      invokeDefault = false;
      break;
    }
  }

  if (invokeDefault) {
    BackHandler.exitApp();
  }
});

**Comment by rayj10** [comment] 2018-07-06 01:59
Any updates on this? editing android folder shouldn't be the only way to fix this issue... it's unfair for CRNA/Expo users :$

**Comment by FibreFoX** [comment] 2018-07-25 13:13
@princepardeep isn't this workaround? https://github.com/facebook/react-native/issues/3223#issuecomment-355064410

**Comment by TranHanHieu** [comment] 2018-08-30 09:54
I that have same issue, what is the solution?

**Comment by princepardeep** [comment] 2018-08-30 13:43
it was working fine in my case.

change in this file 
source code:(react-native/Libraries/Utilities/BackHandler.android.js)

Working like this in 54.2

var DeviceEventManager = require('NativeModules').DeviceEventManager;
var RCTDeviceEventEmitter = require('RCTDeviceEventEmitter');

var DEVICE_BACK_EVENT = 'hardwareBackPress';

type BackPressEventName = $Enum<{
backPress: string,
}>;

var _backPressSubscriptions = new Set();

RCTDeviceEventEmitter.addListener(DEVICE_BACK_EVENT, function () {
var invokeDefault = true;
var subscriptions = [];

// var subscriptions = Array.from(_backPressSubscriptions.values()).reverse();
_backPressSubscriptions.forEach(item => subscriptions.push(item));
for (var i = 0; i < subscriptions.length; ++i) {
if (subscriptionsi) {
invokeDefault = false;
break;
}
}

if (invokeDefault) {
BackHandler.exitApp();
}
});

**Comment by FibreFoX** [comment] 2018-08-30 13:57
@princepardeep this is the same code you already posted, and which is posted in https://github.com/facebook/react-native/issues/3223#issuecomment-355064410 ... you should avoid re-posting the same code.

But yes, it is frustrating, that this kind of bug still exists. But instead of fixing that inside the core-file, I've added this code to my main app class:
```js
  constructor(props){
    super(props);
    // https://github.com/facebook/react-native/issues/3223#issuecomment-355064410
    this.backPressSubscriptions = new Set();
  }

    componentDidMount() {
      if (Platform.OS === 'android') {
          // there is a bug/workaround on android https://github.com/facebook/react-native/issues/3223#issuecomment-355064410
          DeviceEventEmitter.removeAllListeners('hardwareBackPress');
          DeviceEventEmitter.addListener('hardwareBackPress', () => {
            let invokeDefault = true;
            const subscriptions = [];
      
            this.backPressSubscriptions.forEach(sub => subscriptions.push(sub));
      
            for (let i = 0; i < subscriptions.reverse().length; i += 1) {
              if (subscriptions[i]()) {
                invokeDefault = false;
                break;
              }
            }
      
            if (invokeDefault) {
              BackHandler.exitApp();
            }
          });
      
          this.backPressSubscriptions.add(this.handleAndroidHardwareBack);
      }
    }

    componentWillUnmount() {
      if (Platform.OS === 'android') {
        DeviceEventEmitter.removeAllListeners('hardwareBackPress');
        this.backPressSubscriptions.clear();
      }
    }
```

**Comment by TranHanHieu** [comment] 2018-09-05 06:41
I find it unfeasible for me to create multiple listening events in different components

**Comment by jerolimov** [comment] 2018-09-05 07:06
There is still my 4 month old PR #19077 which fixes this... But nobody have the time to review/merge it. 😞

@TranHanHieu @princepardeep @FibreFoX Maybe you can verify if this change works for you as well and upvote the PR?

**Comment by TranHanHieu** [comment] 2018-09-05 07:44
oke, thanks you @jerolimov  !

**Comment by GitHubTracey** [comment] 2018-09-05 08:42
@tranhanhieu,

I created an HOC to handle android back button press, then just pass on a function I want to call...  I don’t actually have a viewable component to it, I return null, and then just add it to the bottom of each component I need it.

**Comment by jerolimov** [comment] 2019-01-28 16:41
PR #19077 is merged and is finally part of the latest RN release 0.58+

I hope for all of you that this issue here is fixed when you upgrade your RN version. 😄

**Comment by kelset** [comment] 2019-01-28 16:44
Awesome! I'm going to close this for the time being, if the issue is still present please submit a new issue :)

**Closed by kelset** 2019-01-28 16:44 UTC
Labels: Bug Report, Help Wanted :octocat:
