### ISSUE TITLE
ReactNativeJS: TypeError: undefined is not an object (evaluating 't.target._internalFiberInstanceHandleDEV.memoizedProps') 

### ISSUE THREAD

**Issue by k1941996** [facebook/react-native#29887] opened 2020-09-08 07:22 UTC
To Produce the issue : 
```
changeText =(e) =>{
        let name = e.target._internalFiberInstanceHandleDEV.memoizedProps.name
        let value = e.nativeEvent.text
        this.setState({...this.state,[name]:value})

    }
...
...
<TextInput 
            name="LastName"
            onChange={changeText}
            placeholder="Name"
            placeholderTextColor="white"
            style={styles.input}></TextInput>
```

Run in release mode. Debug mode doesn't cause this issue.

Cause of Issue :
on cmd run "adb logcat *:E" to detect the issue 
![image](https://user-images.githubusercontent.com/24502716/92445412-f17a3b80-f1d1-11ea-9d98-66d86b4a37ba.png)

Environment Info: 
System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
    Memory: 1.40 GB / 7.88 GB
  Binaries:
    Node: 12.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 23.0.1, 23.0.3, 28.0.3, 29.0.2, 29.0.3
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_211
    Python: 3.8.3
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by k1941996** [comment] 2020-09-20 04:58
Any resolution ?

**Comment by chrisglein** [comment] 2020-10-27 17:55
Based on the name `_internalFiberInstanceHandleDEV` I'd guess that this is an internal member and maybe not reliable in your context. What are you trying to do?

**Comment by k1941996** [comment] 2020-10-29 05:41
I was trying to make a function which can used used with many textInputs. Digging deep i found name and value can be used to work. So what i did was :

        let name = e.target._internalFiberInstanceHandleDEV.memoizedProps.name // returns the name prop
        let value = e.nativeEvent.text // returns the user input value as a prop 

works well in development mode ( debug and non debug ) . breaks in production mode (released apk).

**Comment by chrisglein** [comment] 2020-10-29 18:59
> _internalFiberInstanceHandleDEV

I have no material knowledge here. But the name of that field sends up huge red flags to me ("_internal" and "DEV") that you shouldn't be relying it. Which matches an experience where it's maybe optimized away in production builds. If you're experiencing issues using it... don't use it?

The only other hit I'm seeing is [this StackOverflow article](https://stackoverflow.com/questions/46148936/react-native-onchange-event-has-name-type-value-undefined), but that's you. What sent you down this path? It seems like there are other ways to achieve what you're looking to achieve.

FYI I've recreated your repro in a Snack [here](https://snack.expo.io/@chrisglein/repro29887).

**Comment by k1941996** [comment] 2020-11-04 05:00
To reproduce the minimal code is down below:(reproducible example)

```
import React from 'react'

export class App extends Component {
constructor(props) {
        super(props);
        this.state = {username:""};
    }

    const changeText =(e) =>{
        let name = e.target._internalFiberInstanceHandleDEV.memoizedProps.name
        let value = e.nativeEvent.text
        this.setState({...this.state,[name]:value})
    }

    return (<>
    <TextInput 
            name="LastName"
            onChange={changeText}
            placeholder="username"
            style={styles.input}></TextInput>
</>)}
```

This code works in development mode but not in prod.

**Comment by chrisglein** [comment] 2020-11-04 19:53
> To reproduce the minimal code is down below:(reproducible example)

Your repo has errors in it.
- it declares a class component but then isn't using a `render()` function
- other than setting the state, it doesn't use it, so I'm not sure where you want to see it working
- the state is initialized for a `username` key but the rest doesn't map to that at all
- I'm not sure why your `setState` is passing in a spread of the current state - you should just apply the diffs, not the whole previous state ([see this](https://reactjs.org/docs/state-and-lifecycle.html#state-updates-are-merged))

I attempted to correct your repro into the Snack [here](https://snack.expo.io/@chrisglein/repro29887). Let me know if that's correct or not to your intent. As expected it fails to reference `_internalFiberInstanceHandleDEV`. But as said above, you shouldn't be relying on that member. You can access things like `e.target.value` and `e.target.placeholder`, but not a value you've attached as props for the `TextInput`.

I'm not seeing a bug here. This seems to be behaving as intended.

**Comment by k1941996** [comment] 2020-11-17 14:05
I tried to obtain the error on the snack but i dont know why it doesnt appeared on the web interface. It only generates on react pc....

**Comment by chrisglein** [comment] 2020-11-17 18:48
I haven't seen any indication that the `_internalFiberInstanceHandleDEV` is intended to be a public consumable API. You should find a different way to get the context to your shared handler, or abandon having a shared handler. The behavior here (it being optimized out in Release) seems to be by design.

**Closed by chrisglein** 2020-11-17 18:48 UTC
Labels: Needs: Attention, Needs: Repro
