### ISSUE TITLE
[iOS] ActionSheetIOS flashes black when using "anchor"

### ISSUE THREAD

**Issue by samuelkraft** [facebook/react-native#8129] opened 2016-06-15 14:20 UTC
When opening an ActionSheet on iPad with the "anchor" prop the sheet flashes black when dismissed or something is selected. 

Make sure [this commit](https://github.com/facebook/react-native/commit/b91bf8eeacae4c873348cfbfb77bce2a6ca27c64) is applied in order to test this or the ActionSheet will crash when adding "anchor".

Gif: 
![actionsheet](https://cloud.githubusercontent.com/assets/2223418/16083152/4a181a36-3314-11e6-9f3f-5e40fc69cc7a.gif)

**Comment by esamelson** [comment] 2016-07-15 22:01
I've been having this issue as well - even on ActionSheets which do not have the "anchor" prop set. It seems to be exclusive to iPad builds.

**Comment by oblador** [comment] 2016-08-06 10:26
For me this only happens in the simulator.

**Comment by ericvicenti** [comment] 2016-11-14 20:11
Closing because this is only reported to happen in the simulator. If this is still important to  you, please re-open and post some code that can be used to reproduce it!

**Closed by ericvicenti** 2016-11-14 20:11 UTC
