### ISSUE TITLE
Can't create bundle: react-native-xcode.sh fails to call react-native

### ISSUE THREAD

**Issue by heliumsoule** [facebook/react-native#3948] opened 2015-11-06 10:17 UTC
I recently updated node to 5.0.0 and react-native won't compile in Xcode. Previous projects still work though. Does anyone have any thoughts? Thank you!

+ react-native bundle --entry-file index.ios.js --platform ios --dev true --bundle-output /Users/[username]/Library/Developer/Xcode/DerivedData/firstP-diwselkaoasmusemncrzcyzygens/Build/Products/Debug-iphonesimulator/firstP.app/main.jsbundle --assets-dest /Users/[username]/Library/Developer/Xcode/DerivedData/firstP-diwselkaoasmusemncrzcyzygens/Build/Products/Debug-iphonesimulator/firstP.app
../node_modules/react-native/packager/react-native-xcode.sh: line 36: react-native: command not found
Command /bin/sh failed with exit code 127

**Comment by greyexpert** [comment] 2015-11-06 11:42
I have the same problem. 
I found that XCode ```$PATH``` differs from terminal ```$PATH``` and it doesn't include path of nvm nodes (~/.nvm/versions/...). 
I have temporary fixed it by adding ```source ~/.bash_profile``` to the beginig of ```react-native-xcode.sh``` but there should be a better solution.

**Comment by Jerrylingit** [comment] 2015-11-06 14:05
as greyexpert's way，it works，but i still don't konw why……

**Comment by JonathanWi** [comment] 2015-11-06 14:12
Same here, thanks @greyexpert, now to find a real solution :)

**Comment by jstowell29** [comment] 2015-11-06 14:14
Experiencing the same issue... used @greyexpert workaround and was able to compile. Thanks

**Comment by sheets** [comment] 2015-11-06 16:45
@greyexpert work around worked for me as well.

**Comment by bartonhammond** [comment] 2015-11-06 19:51
I had to add '/usr/local/bin' explicitly to ~/.bash_profile along w/ @greyexpert  workaround

**Comment by timfpark** [comment] 2015-11-06 21:09
+1

**Comment by bartonhammond** [comment] 2015-11-06 21:57
I created new project (react-native @0.14.0 and changing index.ios.js does not update in iOS simulator w/ Cmd+R.  Anyone else experience this w/ this newest release?

**Comment by samsalisbury** [comment] 2015-11-06 22:10
@bartonhammond I had to kill the initial packager that was started after `react native init ...` and start it again with `npm start` to get it to work in general.. However it's now failing in the way reported by the OP

**Comment by samsalisbury** [comment] 2015-11-06 22:14
For me, the Xcode build script failure as originally reported started after I upgraded a 0.13.2 project to 0.14.0. I then created a new 0.14.0 project from scratch, and it all worked. I took my original `index.os.js`, `styles.os.js`, and dependencies from `package.json` (including 2 libraries with native components) into the fresh new project, and then this issue started again. I have not yet tried @greyexpert's trick.

Here is the relevant bit of the build log from Xcode:

```
DEST=/Users/xxx/Library/Developer/Xcode/DerivedData/AwesomeProject-gttzgacpenhrxsfurdqdxmuyymsa/Build/Products/Debug-iphonesimulator/AwesomeProject.app
+ react-native bundle --entry-file index.ios.js --platform ios --dev true --bundle-output /Users/xxx/Library/Developer/Xcode/DerivedData/AwesomeProject-gttzgacpenhrxsfurdqdxmuyymsa/Build/Products/Debug-iphonesimulator/AwesomeProject.app/main.jsbundle --assets-dest /Users/xxx/Library/Developer/Xcode/DerivedData/AwesomeProject-gttzgacpenhrxsfurdqdxmuyymsa/Build/Products/Debug-iphonesimulator/AwesomeProject.app
/Users/xxx/AwesomeProject/node_modules/react-native/node_modules/promise/lib/done.js:10
      throw err;
      ^

TypeError: Cannot assign to read only property 'undefined' of [object Object]
    at /Users/xxx/AwesomeProject/node_modules/react-native/private-cli/src/bundle/buildBundle.js:22:5
    at tryCallTwo (/Users/xxx/AwesomeProject/node_modules/react-native/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/xxx/AwesomeProject/node_modules/react-native/node_modules/promise/lib/core.js:171:13)
    at new Promise (/Users/xxx/AwesomeProject/node_modules/react-native/node_modules/promise/lib/core.js:65:3)
    at buildBundle (/Users/xxx/AwesomeProject/node_modules/react-native/private-cli/src/bundle/buildBundle.js:18:10)
    at Array.bundle (/Users/xxx/AwesomeProject/node_modules/react-native/private-cli/src/bundle/bundle.js:19:10)
    at Object.run (/Users/xxx/AwesomeProject/node_modules/react-native/local-cli/cli.js:68:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:27:7)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
Command /bin/sh failed with exit code 1
```

**Comment by bartonhammond** [comment] 2015-11-06 22:14
argh - @samsalisbury that was it. thanks

**Comment by samsalisbury** [comment] 2015-11-06 22:53
np @bartonhammond 

UPDATE: I have isolated the problem in my case to my `.babelrc`. Simply adding this file to a brand new (verified working) RN 0.14.0 project causes the above failure. I suspect this may related to some global dependencies I've installed and forgotten about which pick up on this, I'm going to try & isolate it.

Here's my `.babelrc` for completeness:

```
{
  "whitelist": [
    "es6.modules",
    "es6.arrowFunctions",
    "es6.blockScoping",
    "es6.classes",
    "es6.destructuring",
    "es6.parameters",
    "es6.properties.computed",
    "es6.properties.shorthand",
    "es6.spread",
    "es6.templateLiterals",
    "es7.trailingFunctionCommas",
    "es7.objectRestSpread",
    "flow",
    "react",
    "es7.classProperties",
    "es7.asyncFunctions",
    "es7.decorators",
    "regenerator",
    "utility.inlineEnvironmentVariables"
  ]
}
```

**Comment by samsalisbury** [comment] 2015-11-06 23:33
*UPDATE:* I've found a few things out:

- Even a .babelrc file containing only `{}` was causing the above failure.
- I _had_ a globally-installed `babel-eslint 4.1.3` (RN has a dev dependency on `4.1.1`). I removed this.
- Now, the `{}` .babelrc file now _did not_ cause a build failure, but the above posted one still did. Progress.
- I bisected the .babelrc from above and **isolated the issue to a single line whitelist entry:**

```
{
  "whitelist": [
    "utility.inlineEnvironmentVariables"
  ]
}
```

The above `.babelrc` file plus a brand new `react-native init ...` project comprises a complete repro of the issue as far as I can tell. Anyone else here want to see if they get the same results?

**Comment by samsalisbury** [comment] 2015-11-06 23:46
**UPDATE: Removing the `"utility.inlineEnvironmentVariables"` whitelist entry from .babelrc from my original upgraded project resolved the original issue.** Everything is fixed for me, I hope some of this is helpful for anyone else with these issues.

**Comment by samsalisbury** [comment] 2015-11-07 00:22
Just realised my issue wasn't the same as the OP's, oops, I've been running on Node 4.2.1 rather than 5, and had a different error from the same script...

**Comment by AustinAmoruso** [comment] 2015-11-07 00:33
==================== SOLUTION ====================
@greyexpert has the right idea the pathing of the script is wrong either add source ~/.bash_profile or .zshrc or what ever you use these days to get the path set up correctly.

**Comment by heliumsoule** [comment] 2015-11-07 01:11
Thank you all for the help! @greyexpert I ended up reinstalling react-native, and then updating Xcode from 6.4 to 7.1 which fixed the compilation error.

**Comment by heliumsoule** [comment] 2015-11-07 01:27
Thank you for the help @greyexpert That fix worked!

**Comment by lyptt** [comment] 2015-11-07 10:57
Only adding source ~/.bash_profile was able to fix this for me. I didn't have a .babelrc at all, and this was a brand new project on the latest version of the react native tools.

**Comment by imansyaefulloh** [comment] 2015-11-07 10:59
Thank you for the help @greyexpert that fix worked for me.

**Comment by vood** [comment] 2015-11-07 16:25
@greyexpert great solution thanks. One thing to add: in my case it was not exactly `source ~/.bash_profile` but `source ~/.zshrc` because i'm using oh-my-zsh. The path to the file to change is `/path/to/the/project/node_modules/react-native/packager/react-native-xcode.sh`

**Comment by jwhitley** [comment] 2015-11-09 00:53
It's a bad idea in general to source one's bash/zsh environment into any automation system.  I've done a lot of work with highly repeatable automation environments (complex dev-to-production & devops VM environments, build systems, etc.), and nvm/rvm are an absolute plague there.  Neither of those tools can run without a shell using their injected runtime functions as a proxy.  This is outright impossible to do sanely and/or repeatably with many tools.  Shell functions are absolutely the wrong means to this end.

Instead, I use and highly recommend [ndenv](https://github.com/riywo/ndenv) for node (and its namesake rbenv for Ruby users).  ndenv manages node versions via a directory of shim scripts, `~/.ndenv/shims`.  For each node bin script available, ndenv creates a matching shim script.  The shim dir is then placed on PATH.  When a script is run, e.g. `react-native`, the shim asks ndenv which node version is active then proxies to the original bin script using the correct node environment.  This works very reliably just by adding one directory to PATH, no complex shell injection required.

**HOWEVER**: I get the same error using ndenv because <*expletive deleted*> Xcode 7.1 wholly overwrites a PATH set as a user-defined project setting.  E.g. I can add a setting for PATH as `$PATH:~/.ndenv/shims`, see that the shims dir is correctly expanded and added to the iOS default PATH in the Xcode settings UI... but all of that is thrown away in PATH in the environment dump when `react-native-xcode.sh` is run.  I describe that problem in more detail [over on StackOverflow](http://stackoverflow.com/questions/33588598/setup-of-react-native-using-ndenv-on-os-x).

This would allow for an easy and robust solution, but so far, I've been unable to determine whether there's any mechanism as of Xcode 7.1 that allows PATH to be augmented. :disappointed:

**Comment by jwhitley** [comment] 2015-11-09 00:54
For completeness, I've also inquired about the Xcode PATH behavior [over on the Apple Developer Forums](https://forums.developer.apple.com/message/85689#85689), but have yet to get any responses as of this writing.

**Comment by diffractometer** [comment] 2015-11-09 06:16
@vood your solution worked for me thanks!

**Comment by LeeBlaze** [comment] 2015-11-09 10:19
thanks, it really worked

**Comment by christopherdro** [comment] 2015-11-09 17:35
Another possible temporary solution can be found here. https://github.com/facebook/react-native/issues/3946#issuecomment-154446396

**Comment by ide** [comment] 2015-11-10 03:24
Please try react-native 0.14.2, which should include a fix for this.

**Comment by MossP** [comment] 2015-11-10 16:24
Not sure what's caused it. But running 14.2 *had* fixed this issue for me. I tried installing react-native-icons, then I got the error again, uninstalling did nothing to fix the error.

On a side note: It seems that I cannot install any plugin to my app now without it throwing an error about unknown modules.

**Comment by MossP** [comment] 2015-11-10 17:26
Ignore me for a bit. I'll do some more digging. Something is causing it to all trip over every now and then. I'll take regular snapshots to see what's changing at the point of error and open an issue - if I can recreate it - with more details.

**Comment by Thorbenandresen** [comment] 2015-11-11 02:20
It does still not work for me, getting the error: `Command /bin/sh failed with exit code 8`. Just to double check: I use v14.2 if it says "react-native": "^0.14.2" in my package.json after a new react-native init, correct?  The only workaround that work for me is [#3946 (comment)](https://github.com/facebook/react-native/issues/3946#issuecomment-154446396)
.

**Comment by MossP** [comment] 2015-11-11 12:39
Done a little digging into this. It can also occur while the xcode script is running if there are any references in the JS code to images that aren't corrected located in the base project. It doesn't warn that the image is the problem, or load the project and then highlight the issue. it just fails with no meaningful error message.

**Comment by jackqqxu** [comment] 2015-11-14 08:21
@greyexpert thanks, it works for me.
add source ~/.bash_profile before case "$CONFIGURATION" in...
the final shell file:

#!/bin/bash
# Copyright (c) 2015-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

# Bundle React Native app's code and image assets.
# This script is supposed to be invoked as part of Xcode build process
# and relies on envoronment variables (including PWD) set by Xcode

source ~/.bash_profile

case "$CONFIGURATION" in
  Debug)
    DEV=true
    ;;
  Release)
    DEV=false
    ;;

**Comment by BobD** [comment] 2015-11-15 17:47
@MossP I seem to have the same issue with a supposedly missing image. Even though it is correctly added in xcode like in all other projects. Did you find a workaround perhaps?

**Comment by MossP** [comment] 2015-11-16 08:53
@BobD Not yet. I was just testing the new version but I will have to tackle the issue soon so I'll keep you posted. Let me know if you find a way around it too.

**Comment by fedorinoGore** [comment] 2015-11-16 16:48
@MossP , @BobD I could confirm that issue appear just after importing a single image to XCode project... Have no idea what causing it

**Comment by Thorbenandresen** [comment] 2015-11-16 21:34
@ide Can we please re-open this issue. I have 0.14.2 installed and I am still getting the error "Command /bin/sh failed with exit code 8". What info would you need from me?  (btw. adding `source ~/.bash_profile ` does not work for me either)

**Comment by christopherdro** [comment] 2015-11-16 21:46
@Thorbenandresen Could you check the error log inside of xcode and report back what the error is on?

**Comment by Thorbenandresen** [comment] 2015-11-16 22:08
@christopherdro thanks - is this here enough do you need the whole log? 
```
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Module._extensions..js (module.js:474:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/thorbenandresen2/Documents/@Code - React Native/NewProject/node_modules/react-native/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/thorbenandresen2/Documents/@Code - React Native/NewProject/node_modules/react-native/cli.js:15:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
Command /bin/sh failed with exit code 8
````

**Comment by ide** [comment] 2015-11-16 22:48
what version of Node are you using?

**Comment by Thorbenandresen** [comment] 2015-11-17 02:21
v4.0.0 - too old?

**Comment by ide** [comment] 2015-11-17 02:25
4.0 is fine -- mainly 0.8-0.12 are problems.

**Comment by lasergoat** [comment] 2015-11-17 16:19
node `5.0.0` with react-native `0.14.2` and the issue is persisting. Currently, the only fix I've found is @greyexpert's `source ~/.bash_profile` at the top of `react-native-xcode.sh`

**Comment by MossP** [comment] 2015-11-17 17:24
@lasergoat Are your co-workers all using node 5.0.0 also?

**Comment by Thorbenandresen** [comment] 2015-11-17 18:09
I also upgraded to `5.0.0` and I also still have the issue on `0.14.2`. The `source ~/.bash_profile` does still not work for me.

**Comment by jonolock91** [comment] 2015-11-17 18:58
I'm experiencing the same error with my Xcode build after upgrading to 0.14.2, but not straight away it happened after a few hours of tinkering and I don't know why. Where do I add `source ~/.bash_profile` to `react-native-xcode.sh` I can't figure it out.

**Comment by jonolock91** [comment] 2015-11-17 19:10
When I removed from my build phases:
Bundle React Native code and images
`/bin/sh`
`../node_modules/react-native/packager/react-native-xcode.sh`
it then worked, but I assume this is needed for the new image changes in 0.14.2 for iOS and Android.

**Comment by Thorbenandresen** [comment] 2015-11-18 01:33
Update: I deleted my `.bash_profile` and created a new one from scratch. Now this `0.14.2` compiles fine,  even without adding `source ~/.bash_profile` to the `react-native-xcode.sh`. 

HOWEVER, when I `react-native init` a new project, the error re-surfaces and I have no clue how I can fix that. This is very mysterious to me.

**Comment by Thorbenandresen** [comment] 2015-11-18 16:36
Update: My bad, creating a new empty bash file didn't fix it either. I have currently no way to run the react-native-xcode.sh with `RN 0.14.2' , `RN CLI 0.1.7` & `XCode 7.1.1`. No clue what else I could try...

**Comment by petarslovic** [comment] 2015-11-19 01:52
Hi guys, hope this helps someone, I solved it by changing my shell in XTerm's Build Phases, since it's `/bin/sh` by default, and I'm running Fish.

![screen shot 2015-11-19 at 2 49 24 am](https://cloud.githubusercontent.com/assets/5387195/11260128/8f561aa4-8e68-11e5-9fb5-9cd919168d4d.png)

**Comment by yangfei2013** [comment] 2015-11-19 03:32
fixed:react-native-xcode.sh 45 react-native:command not found
1.add source ~/.bash_profile to the begining of react-native-xcode.sh(path/to/your/app/node_modules/react-native/packager/react-native-xcode.sh)
if .bash_profile does not exist in your home/name then :touch .bash_profile
2.add export PATH=/usr/local/bin:$PATH to .bash_profile

**Comment by Thorbenandresen** [comment] 2015-11-20 00:34
still not working for mea

**Comment by Thorbenandresen** [comment] 2015-11-20 16:49
I solved my problem: Turns out that I had Node 5.1 installed with Mac-Installer, while the NVM was still using an (too) old version of node. So I updated NVM and then installed the new version with `nvm install 5.1`. Now everything works fine and there is no need to source the `.bash_profile` any longer. 

Can be closed for my sake.

**Comment by BobD** [comment] 2015-11-21 12:30
@MossP It seems the issue with the missing native image asset was simply due to an syntax change in the react native update http://facebook.github.io/react-native/docs/images.html

**Comment by aceywli** [comment] 2015-11-23 15:21
I have the same issue,but I can't fixed the issue.Pls help!!!

**Comment by akovantsev** [comment] 2015-11-23 15:51
It is worth mentioning, that `react-native` command (as in `line 36: react-native: command not found`) is provided by `react-native-cli` npm package. All the PATH manipulations will not help unless `react-native-cli` is installed.

**Comment by MossP** [comment] 2015-11-23 17:12
@BobD Thanks. I had to have a look at this today. That helped. Thank you

**Comment by gre** [comment] 2015-11-25 09:04
I've created https://productpains.com/post/react-native/fix-regression-on-xcodenvm-react-native-xcodesh-throws-react-native-command-not-found/

**Comment by mkonicek** [comment] 2015-11-30 20:20
I have little context on this but see that people have posted multiple workarounds. Is anyone up for sending a PR to fix this in a generic way?

**Comment by allanjsx** [comment] 2015-12-01 05:24
I am hitting the same issue. Switching Node versions (4.2.2 -> 4.1.1 -> 5.1) doesn't help. I couldn't get it work with source ~/.bash_profile adding to the top of the script either.

**Comment by gre** [comment] 2015-12-02 13:34
for some reason I can't get the sourcing working anymore (I used to have it working) in 0.15.x :(
I basically can't run any RN project.

**Comment by mkonicek** [comment] 2015-12-02 22:35
`react-native-xcode.sh` was written by @frantic, we'll know more once he's back from vacation.

Why does `react-native bundle` call `react-native-xcode.sh`? It looks like it should only be called by Xcode:
- https://facebook.github.io/react-native/docs/upgrading.html#manual-upgrades
- https://github.com/facebook/react-native/search?utf8=%E2%9C%93&q=react-native-xcode

**Comment by mkonicek** [comment] 2015-12-02 22:37
@frantic will be back on Dec 7. Does anyone want to step up and fix this?

**Comment by mkonicek** [comment] 2015-12-02 22:38
> It is worth mentioning, that react-native command (as in line 36: react-native: command not found) is provided by react-native-cli npm package. All the PATH manipulations will not help unless react-native-cli is installed.

Yes, you can't use React Native without the CLI. See https://facebook.github.io/react-native/docs/getting-started.html#quick-start

**Comment by mkonicek** [comment] 2015-12-02 22:43
The [documentation on upgrading]( https://facebook.github.io/react-native/docs/upgrading.html) says this at the bottom:

If you installed Node via nvm, you might experience "react-native: command not found". See #3974 for workaround and #4015 for the fix.

**Comment by mkonicek** [comment] 2015-12-02 22:46
The fix is in 0.16.0-rc. Thank you @ide! https://github.com/facebook/react-native/commit/9a64f17de84e50a4fc60f1b96168aa61925934a8

**Comment by gre** [comment] 2015-12-03 13:51
I was still having the problem because my nvm wasn't set to a default version.
Make sure you have a `.nvmrc` file defined somewhere in your path. For instance in your ~ (home).

You can bootstrap it like this:
```
nvm version > ~/.nvmrc
```

**Comment by jonolock91** [comment] 2015-12-09 11:37
I've upgraded to version 0.16.0 but I'm still getting the error `Command /bin/sh failed with exit code 1` to do with the Bundle React Native code and images.

**Comment by myusuf3** [comment] 2015-12-09 21:30
This isn't solved. I have been blocked from upgrading for a few because of this issue!

**Comment by mkonicek** [comment] 2015-12-09 22:51
Have you guys tried `nvm version > ~/.nvmrc`?

**Comment by mkonicek** [comment] 2015-12-09 22:53
Does this happen always or only when building a release version from Xcode? Have little context here.

Do you hit this when doing `react-native init`, open the project in Xcode and click 'Run'?

**Comment by SpeCT** [comment] 2015-12-11 16:14
```bash
nvm version > ~/.nvmrc
```

This helps, thanks @gre :+1:

**Comment by SunLn** [comment] 2015-12-13 07:11
I have soloved this problem by this answer. 
http://stackoverflow.com/a/29211118

**Comment by ChrisSki** [comment] 2015-12-19 20:32
+1 to @SunLn.

node: 4.2.3
npm: 2.14.7
nvm: 0.29.0

**Comment by liyaodong** [comment] 2015-12-20 16:16
I'm using [tj/n](https://github.com/tj/n) to manage node, same problem,can fix with `source ~/.bash_profile` & @SunLn solution  hope a official solution .

**Comment by richarddewit** [comment] 2015-12-30 13:59
+1 to @SunLn :+1:

**Comment by backslash112** [comment] 2015-12-31 03:04
+1 to @SunLn :+1:, worked for me!

**Comment by chiho13** [comment] 2016-01-24 21:16
@greyexpert how do you add source ~/.bash_profile to the beginning of react-native-xcode.sh (where do you find this)

**Comment by frantic** [comment] 2016-01-24 21:19
Hopefully the changes in https://github.com/facebook/react-native/pull/5518 will solve these problems once and for all.

**Comment by freeman983** [comment] 2016-03-02 03:07
http://stackoverflow.com/questions/34975286/reactnativecli-init-helloworld-project-build-error-with-babel-transformerror%E3%80%82

**Comment by Kureev** [comment] 2016-03-02 09:16
Well, the initial issue is about `react-native: command not found`. Installing `react-native-cli` globally should solve the problem, right?

What do I miss, @mkonicek?

**Comment by frantic** [comment] 2016-03-05 21:05
#5518 has landed and we no longer depend on global `react-native-cli` to build iOS projects.

**Closed by frantic** 2016-03-05 21:05 UTC

**Comment by WangMasterpro** [comment] 2016-10-24 03:09
Selected “Run Script only when installing”。like this http://stackoverflow.com/a/29211118
