### ISSUE TITLE
enableHermes on React Native 0.60.3 is extremely slow.

### ISSUE THREAD

**Issue by ollydixon** [facebook/react-native#25986] opened 2019-08-08 15:46 UTC
I'm testing with two real devices and an emulator. They are all extremely slow with the hermes flag enabled. Had to enabled it for 0.60.3 :-(

By extremely slow, pressing something takes about 3 seconds for it to react.

App was working fine before swiching flag.

My configuration is as such:
(Hidious I know)

**app/build.gradle**
```
apply plugin: "com.android.application"

import com.android.build.OutputFile

apply plugin: 'io.fabric'
repositories {
    maven { url 'https://maven.fabric.io/public' }
}

project.ext.react = [
        entryFile: "index.js",
        enableHermes: true,
]

def jscFlavor = 'org.webkit:android-jsc:+'
def enableHermes = project.ext.react.get("enableHermes", false)


apply from: "../../node_modules/react-native/react.gradle"

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion

    defaultConfig {
        applicationId "com.magicword.ahahah"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 46
        versionName "1.4.1"
        ndk {
            abiFilters "armeabi-v7a", "x86", "arm64-v8a"
        }
        multiDexEnabled true
        vectorDrawables.useSupportLibrary = true
    }
    lintOptions {
        abortOnError false
    }
    buildTypes {
        debug {
            manifestPlaceholders = [isDebug: true]
        }
        release {
            manifestPlaceholders = [isDebug: false]
            minifyEnabled false
            useProguard true
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a": 1, "x86": 2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    packagingOptions {
        pickFirst 'lib/x86/libc++_shared.so'
        pickFirst 'lib/x86_64/libjsc.so'
        pickFirst 'lib/arm64-v8a/libjsc.so'
        pickFirst 'lib/arm64-v8a/libc++_shared.so'
        pickFirst 'lib/x86_64/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
    }
}

dependencies {
    implementation 'com.android.support:multidex:1.0.3'
    implementation project(':react-native-iap')
    implementation project(':react-native-location')
    implementation project(':react-native-fbsdk')
    implementation project(':react-native-navigation')
    compile fileTree(include: ['*.jar'], dir: 'libs')
    // Android stuff
    implementation 'com.google.android.material:material:1.0.0'
    implementation 'com.android.support:multidex:1.0.3'
    implementation "com.android.support:support-annotations:${rootProject.ext.supportLibVersion}"
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.android.support:animated-vector-drawable:${rootProject.ext.supportLibVersion}"
    implementation "com.android.support:customtabs:${rootProject.ext.supportLibVersion}"
    implementation "com.android.support:design:${rootProject.ext.supportLibVersion}"
    //Google stuff
    implementation "com.google.android.gms:play-services-location:16.0.0"
    implementation 'com.google.android.gms:play-services-identity:16.0.0'
    implementation "com.google.android.gms:play-services-base:17.1.0"
    // Maps
    // React native stuff
    implementation 'com.facebook.react:react-native:+'
    // From node_modules
    // Facebook
    implementation 'com.facebook.android:facebook-android-sdk:4.38.1'
    // Firebase stuff
    implementation project(':react-native-firebase')

    implementation 'com.google.firebase:firebase-core:16.0.8'
    implementation 'com.google.firebase:firebase-firestore:18.2.0'
    implementation 'com.google.firebase:firebase-storage:16.1.0'
    implementation 'com.google.firebase:firebase-auth:16.2.1'
    implementation 'com.google.firebase:firebase-messaging:17.5.0'
    implementation 'com.google.firebase:firebase-functions:16.3.0'
    compile('com.crashlytics.sdk.android:crashlytics:2.9.2@aar') {
        transitive = true
    }
    compile project(path: ':lottie-react-native')
    compile project(path: ':rn-fetch-blob')
    compile project(path: ':react-native-linear-gradient')
    compile project(path: ':react-native-image-crop-picker')
    compile project(path: ':react-native-maps')
    compile project(path: ':react-native-device-info')
    compile project(path: ':react-native-cookies')
    compile project(path: ':react-native-cookies')
    compile project(path: ':react-native-webview')

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermesvm/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply plugin: 'com.google.gms.google-services'
// https://stackoverflow.com/questions/51839721/the-library-com-google-firebasefirebase-iid-is-being-requested-by-various-other
//com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true
```

**android/build.gradle**
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.


buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 21
        compileSdkVersion = 28
        targetSdkVersion = 27
        supportLibVersion = "28.0.0"
        googlePlayServicesVersion = "16.1.0"
        androidMapsUtilsVersion = "0.5+"
    }
    repositories {
        google()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        mavenLocal()
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.2'
        classpath 'com.google.gms:google-services:4.3.0'
        classpath 'io.fabric.tools:gradle:1.+'
        // NOTE: Do not place your application dependencies here; they belong
        // In the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        maven { url 'https://maven.google.com' }
        maven { url "https://jitpack.io" }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        mavenLocal()
        jcenter()
    }
}

//Force all projects to use the same build tools.
subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 28
                buildToolsVersion "28.0.3"
            }
        }
    }
}

subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "28.0.3"
            }
            if (details.requested.group == 'androidx.core'
                    && !details.requested.name.contains('androidx') ) {
                details.useVersion "1.0.1"
            }
        }
    }
}
```

**Comment by Zloka** [comment] 2019-08-12 09:20
Experiencing similar issues, though I'm using RN 0.60.4.

**Comment by ollydixon** [comment] 2019-08-12 09:26
@Zloka I can't revert back from hermes now otherwise the SoLoader fails. The project is stuck now, any ideas?

**Comment by Zloka** [comment] 2019-08-12 10:16
@ollydixon Yup, just noticed I have the same issue when I figured I'd forego using hermes for now. Application builds just fine, but crashes on launch with the following output:

```
2019-08-12 13:02:27.866 14055-14082/fi.mafynetti.mafyclient E/SoLoader: couldn't find DSO to load: libhermes.so
2019-08-12 13:02:27.867 14055-14082/fi.mafynetti.mafyclient E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: fi.mafynetti.mafyclient, PID: 14055
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
        at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
        at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java:27)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:949)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by ollydixon** [comment] 2019-08-12 10:43
@Zloka exactly the same issue, I spent two days trying to find a fix. I'll let you know if I find one.

**Comment by gaodeng** [comment] 2019-08-12 11:22
@Zloka @ollydixon  try this

```
cd android
./gradlew clean

```

**Comment by Zloka** [comment] 2019-08-12 11:31
@gaodeng Been there, done that.

@ollydixon I'll be looking for a fix as well, will let you know if I make any progress. Came across this, which might be relevant: https://github.com/facebook/hermes/issues/78#issuecomment-517810830

**Comment by Zloka** [comment] 2019-08-12 13:28
@ollydixon This is what I've got so far:

It seems that loading hermes is the fallback for when loading JSC fails, which is why our apps crash with that error message, since hermes wasn't setup at all due to `enableHermes: false` and there's no further error-handling in this case.

In order to fix the initial problem, I added the following to the android-level `build.gradle`-file: 
```
maven {
    // Android JSC is installed from npm
    url("$rootDir/../node_modules/jsc-android/dist")
}
```
`./gradlew clean` after that, and my issues go away in the sense that I can properly opt out of using Hermes.

I'm not really sure what changed when it comes to how JSC is loaded, but I might try to make sense of that this weekend, I'm a bit too pressed by other deadlines to further look into it right now.

Here's what my files look like right now:
`android/app/build.gradle`:
```
...
project.ext.react = [
    entryFile: "index.js",
    jsBundleDirRelease: "$buildDir/intermediates/merged_assets/release/out",
    enableHermes: false,  // clean and rebuild if changing
    hermesCommand: "../../node_modules/hermes-engine/%OS-BIN%/hermes",
]

def jscFlavor = 'org.webkit:android-jsc:+'
def enableHermes = project.ext.react.get("enableHermes", false);
...
dependencies {
    ....
    if (enableHermes) {
      def hermesPath = "../../node_modules/hermesvm/android/";
      debugImplementation files(hermesPath + "hermes-debug.aar")
      releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
      implementation jscFlavor
    }
    ...
}
```

`android/build.gradle`:
```
...
allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        google()
    }
}
...
```

**Comment by ollydixon** [comment] 2019-08-12 13:35
@Zloka thanks, I'll try this in the next few days (I also have a few other deadlines :-)

**Comment by ollydixon** [comment] 2019-08-12 16:33
Here's the full error I'm getting

```
2019-08-12 18:32:28.058 8170-8229/com.polydelic.righter E/SoLoader: couldn't find DSO to load: libhermes.so
    
    --------- beginning of crash
2019-08-12 18:32:28.058 8170-8229/com.polydelic.righter E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.polydelic.righter, PID: 8170
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
        at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
        at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java:27)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:949)
        at java.lang.Thread.run(Thread.java:919)
```

I have in the onCreate in MainApplication.java

`SoLoader.init(this, false);`

No luck.

**Comment by Sam-Martin** [comment] 2019-08-18 10:24
I've been having similar issues. A regex heavy task which took 3-5 seconds with hermes enabled took 40-50 seconds with hermes enabled!  
With @Zloka 's suggesting I was able to disable Hermes and saved myself from tearing my hair out!

**Comment by deceive3w** [comment] 2019-08-21 04:54
try enable debug mode, there no issue on release build

**Comment by Ekhui** [comment] 2019-08-22 02:59
> I've been having similar issues. A regex heavy task which took 3-5 seconds with hermes enabled took 40-50 seconds with hermes enabled!
> With @Zloka 's suggestion I was able to disable Hermes and saved myself from tearing my hair out!

unwork for me ..

**Comment by BogdanRad** [comment] 2019-08-30 14:21
I have the same problem :(

**Comment by baldursson** [comment] 2019-09-08 16:02
I just upgraded to React Native 0.60.5 just to try Hermes because my Android app was really slow, but it made my app to go from slow to ultra slow. It's totally useless with Hermes enabled.

**Comment by tal987** [comment] 2019-09-09 14:35
any solution?

**Comment by baldursson** [comment] 2019-09-09 14:54
Hmm, one thing I see in common with my project and @ollydixon is that we both use the Firebase. That is also the dependency I've had most trouble with compiling. Could try to remove Firebase and see if it helps. How about everyone else who experience the same issue, do you see anything else in common?

**Comment by tal987** [comment] 2019-09-09 14:59
@baldursson  did you fix the issue? its still very very slow, I'm using firebase too

**Comment by baldursson** [comment] 2019-09-10 07:27
@tal987 I haven't had time to try Hermes without Firebase yet. Maybe I will later today, I'll keep you posted

**Comment by tal987** [comment] 2019-09-10 10:43
@baldursson did you get to check on production? Is that slow too in production or it’s only problem with develop?

**Comment by baldursson** [comment] 2019-09-10 11:23
@tal987 It's the same slow behavior in both release and debug builds. I just tried to remove Firebase and rebuilt my app with Hermes, and I could definitely see an improvement in performance. But, I can't say I noticed any performance boost from compiling without Hermes. It could actually still be slower

**Comment by tal987** [comment] 2019-09-10 11:37
@baldursson so what are our options now? We can’t stay with this slow performance. Before the upgrade my performance was very fast...

**Comment by baldursson** [comment] 2019-09-10 11:59
@tal987 I have confirmed that my app is still faster without Hermes, so my option is not to use it. It seams like there may be requirements on third party dependencies to be able to use the "boost" Hermes is supposed to achieve. Are these documented?

I haven't tried Hermes in a fresh React Native product, but I guess (hope) it works there

**Comment by tal987** [comment] 2019-09-10 12:46
@baldursson but we need the herms for the 64bit to work. Can you still upload your app to google play without herms?

**Comment by wouterds** [comment] 2019-09-10 13:17
Can confirm that with _the herms_ enabled our app is noticeably slower (although the startup time seems to have improved somewhat). We need to release some updates asap, but without Hermes we risk 64-bit related crashes on Android - that do not occur with Hermes enabled.

So for now we'll probably make the trade-off of a slower but at least not crashing Android app.

**Comment by baldursson** [comment] 2019-09-10 13:23
@baldursson I haven't come as far as updating the app on Google Play yet. But how is Hermes related to 64-bit support? 64-bit support was introduced in React Native 0.59, before Hermes was included

**Comment by tal987** [comment] 2019-09-10 13:35
@baldursson the all reason I updated my react native its bc I couldn't upload the app to google play from the reason that its not support 64 bit when I tried to upgrade my app without Hermes my app crashed most of the time... and I read that I need to update to 0.60.5 and enable the herms... anyway from some reason, no idea why, my app start work fast again with herms, I didn't change anything

**Comment by wouterds** [comment] 2019-09-10 13:42
@baldursson: Yes 64-bit support was indeed introduced with React-Native 0.59. We rolled out our app to a small percentage on the Google Play store after this upgrade (as I already read some reports of increased crashes on Github) and also noticed a surge in crashes. Not only on older devices but also fairly new devices. Currently we're in the process of testing if with Hermes enabled these crashes do not occur anymore (but I read in a few Github threads that it doesn't 🤞).

**Comment by wouterds** [comment] 2019-09-10 13:43
@tal987: Ah you're talking about debug mode, Hermes in debug mode is extremely slow (known bug). But we also notice a much slower app in production, not as extreme as in debug mode though.

**Comment by baldursson** [comment] 2019-09-10 13:58
@tal987 The app is always much faster when remote debugging because the javascript is processed by the computer you are debugging from instead of the phone

**Comment by tal987** [comment] 2019-09-11 11:57
@baldursson @wouterds on release mode the app works much faster, still not perfect but faster...

**Comment by Zloka** [comment] 2019-09-11 12:21
I haven't had any time to look into using Hermes lately, but that might change soon as our app is nearing release and I'd be interested in resolving this.

@baldursson To add some more context, I'm not using Firebase.

**Comment by dngconsulting** [comment] 2019-09-13 09:42
Same for me here, disabled Hermes, damn slow ...

**Comment by nes123** [comment] 2019-09-19 09:03
Great promise big disappointment. The package is just not ready to be delivered in production..

**Comment by wouterds** [comment] 2019-09-19 10:39
Looks like there's a [new release (0.2.1) of _the herms_](https://github.com/facebook/hermes/releases/tag/v0.2.1).
>Since the last release, there have been hundreds of bug fixes, performance improvements, and feature implementations gearing up for major feature milestones.
>
>For React Native developers, the most visible changes in this release are that:
>
>- The speed of reloads in development should have improved
>- The C++ runtime library is now packaged in a separate AAR to avoid pickFirst nondeterminisms

Anyone cares to try and see if it improves the situation?

**Comment by marf** [comment] 2019-09-23 12:07
Same problem here. With hermes enabled app is significantly slower than before.
Any solutions?

**Comment by YGKtech** [comment] 2019-09-25 19:41
Same issues here, updating from RN 0.59 to ~0.60 caused serious performance issues for my project.  Disabling hermes helped a bit, but performance was still noticeably degraded, we just had to roll back to 0.59 for now.

iOS builds were not effected

**Comment by saudahmed** [comment] 2019-09-27 09:50
I have faced a same problem, enabling Hermes on react native 0.60.5 has significantly lowered app performance. Tap takes 3 seconds to the response. Hermes is now such a big disappointment. Converted my project to use only this feature for quick app starts. I hope so it will be bringing some improvements in the feature. I am also using firebase in my project.

**Comment by samulon13** [comment] 2019-09-29 09:07
I lost hours trying to improve my app performance and im here. ☹️

**Comment by sunnylqm** [comment] 2019-10-01 08:05
Maybe related https://github.com/facebook/hermes/issues/111#issuecomment-533313121
If you are doing a lot of string concatenate, I suggest using [v8](https://github.com/Kudo/react-native-v8) instead of hermes at the moment

**Comment by courptwayne** [comment] 2019-10-06 19:11
Not Working~ 
maven {
    // Android JSC is installed from npm
    url("$rootDir/../node_modules/jsc-android/dist")
}

**Comment by brooklyn097** [comment] 2019-10-18 02:53
Hermes only slow on Debug mode, on a release build it's much faster and i can reduce my app from ~40MB to 17MB.

**Comment by DISKONEKTeD** [comment] 2019-10-29 04:24
Yeah, can confirm my app runs normal on release it seems too (just checked), but super slow on debug. Which lead me to this thread.

**Comment by roots-ai** [comment] 2019-11-03 18:38
How to resolve this?

**Comment by roots-ai** [comment] 2019-11-03 19:09
@brooklyn097 what version of React Native are you using? Can you please share your build.gradle?

**Comment by cisplRejjak** [comment] 2019-11-04 12:53
I am using 0.61.1, it's very slow, please let me know how to solve this.
after completing this app, I'll never work on react native.

fuck react native

**Comment by DISKONEKTeD** [comment] 2019-11-04 22:09
@cisplRejjak just don't enable it then? You don't technically need it. The boost bootup time isn't that big anyway, and a smaller file isn't' that big of a deal. It works fine on release it seems, just not while debugging. It's a new feature, so there are bound to be issues. React Native works fine otherwise. It's come a long way. I suggest people to just disable it while debugging and enable it when ya wanna release. Though you'll probably have to test it manually extensively

**Comment by roots-ai** [comment] 2019-11-05 12:56
@DISKONEKTeD Issue is before making such major release such issues/concerns should be reported to the developers beforehand. It's been a while since Hermes was released, even new versions of RN have come since then.

**Comment by muhammadwafa** [comment] 2019-11-14 15:01
Android 5.0.2
Device Galaxy A5
Release 2015
6 third party Native plugin
react-native v 0.61.2

It get launch in 8 seconds.

Wow very slow, how to can I faster it

**Comment by akwebengineer26** [comment] 2019-11-16 04:15
I have Also Performance issue with the Hermes Enabled on RN 0.60.4 on android devices,
it extremely slow on debug build and take 2-3 second on click on a static button,
Please Suugest me any Solution,
But it works fine on IOS devices

**Comment by keech** [comment] 2019-12-02 03:46
Any updates?

**Comment by BartJanvanAssen** [comment] 2019-12-05 21:25
> @ollydixon This is what I've got so far:
> 
> It seems that loading hermes is the fallback for when loading JSC fails, which is why our apps crash with that error message, since hermes wasn't setup at all due to `enableHermes: false` and there's no further error-handling in this case.
> 
> In order to fix the initial problem, I added the following to the android-level `build.gradle`-file:
> 
> ```
> maven {
>     // Android JSC is installed from npm
>     url("$rootDir/../node_modules/jsc-android/dist")
> }
> ```
> 
> `./gradlew clean` after that, and my issues go away in the sense that I can properly opt out of using Hermes.
> 
> I'm not really sure what changed when it comes to how JSC is loaded, but I might try to make sense of that this weekend, I'm a bit too pressed by other deadlines to further look into it right now.
> 
> Here's what my files look like right now:
> `android/app/build.gradle`:
> 
> ```
> ...
> project.ext.react = [
>     entryFile: "index.js",
>     jsBundleDirRelease: "$buildDir/intermediates/merged_assets/release/out",
>     enableHermes: false,  // clean and rebuild if changing
>     hermesCommand: "../../node_modules/hermes-engine/%OS-BIN%/hermes",
> ]
> 
> def jscFlavor = 'org.webkit:android-jsc:+'
> def enableHermes = project.ext.react.get("enableHermes", false);
> ...
> dependencies {
>     ....
>     if (enableHermes) {
>       def hermesPath = "../../node_modules/hermesvm/android/";
>       debugImplementation files(hermesPath + "hermes-debug.aar")
>       releaseImplementation files(hermesPath + "hermes-release.aar")
>     } else {
>       implementation jscFlavor
>     }
>     ...
> }
> ```
> 
> `android/build.gradle`:
> 
> ```
> ...
> allprojects {
>     repositories {
>         mavenLocal()
>         jcenter()
>         maven {
>             // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
>             url "$rootDir/../node_modules/react-native/android"
>         }
>         maven {
>             // Android JSC is installed from npm
>             url("$rootDir/../node_modules/jsc-android/dist")
>         }
>         google()
>     }
> }
> ...
> ```


Looks like i got it working on the 0.61.5 version. i failed to fill the android/build.gradle file correctly... I did change the file but notice i had 2 places where i had to change the **maven config** 1st place is the allprojects => repositories. the second one is the buildscript => repositories. i forgot the first one and kept on searching for days for this to fix.. maybe i can help someone ;-)

**Comment by ollydixon** [comment] 2019-12-06 10:06
@BartJanvanAssen thanks for the reply but we no longer do React Native (Flutter is far far superior) 😎😎

**Comment by elie222** [comment] 2019-12-11 16:41
> > @ollydixon This is what I've got so far:
> > It seems that loading hermes is the fallback for when loading JSC fails, which is why our apps crash with that error message, since hermes wasn't setup at all due to `enableHermes: false` and there's no further error-handling in this case.
> > In order to fix the initial problem, I added the following to the android-level `build.gradle`-file:
> > ```
> > maven {
> >     // Android JSC is installed from npm
> >     url("$rootDir/../node_modules/jsc-android/dist")
> > }
> > ```
> > 
> > 
> > `./gradlew clean` after that, and my issues go away in the sense that I can properly opt out of using Hermes.
> > I'm not really sure what changed when it comes to how JSC is loaded, but I might try to make sense of that this weekend, I'm a bit too pressed by other deadlines to further look into it right now.
> > Here's what my files look like right now:
> > `android/app/build.gradle`:
> > ```
> > ...
> > project.ext.react = [
> >     entryFile: "index.js",
> >     jsBundleDirRelease: "$buildDir/intermediates/merged_assets/release/out",
> >     enableHermes: false,  // clean and rebuild if changing
> >     hermesCommand: "../../node_modules/hermes-engine/%OS-BIN%/hermes",
> > ]
> > 
> > def jscFlavor = 'org.webkit:android-jsc:+'
> > def enableHermes = project.ext.react.get("enableHermes", false);
> > ...
> > dependencies {
> >     ....
> >     if (enableHermes) {
> >       def hermesPath = "../../node_modules/hermesvm/android/";
> >       debugImplementation files(hermesPath + "hermes-debug.aar")
> >       releaseImplementation files(hermesPath + "hermes-release.aar")
> >     } else {
> >       implementation jscFlavor
> >     }
> >     ...
> > }
> > ```
> > 
> > 
> > `android/build.gradle`:
> > ```
> > ...
> > allprojects {
> >     repositories {
> >         mavenLocal()
> >         jcenter()
> >         maven {
> >             // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
> >             url "$rootDir/../node_modules/react-native/android"
> >         }
> >         maven {
> >             // Android JSC is installed from npm
> >             url("$rootDir/../node_modules/jsc-android/dist")
> >         }
> >         google()
> >     }
> > }
> > ...
> > ```
> 
> Looks like i got it working on the 0.61.5 version. i failed to fill the android/build.gradle file correctly... I did change the file but notice i had 2 places where i had to change the **maven config** 1st place is the allprojects => repositories. the second one is the buildscript => repositories. i forgot the first one and kept on searching for days for this to fix.. maybe i can help someone ;-)

After an hour or two of bashing my head against the wall, this comment fixed my issue. Thanks! I didn't realise it was the bottom section that needed the fix.

**Comment by hramos** [comment] 2020-01-21 20:28
Closing after several months without followup from the author. Please make sure to fill in the issue template if you decide to file a new issue.

**Closed by hramos** 2020-01-21 20:28 UTC
Labels: Bug, Hermes, Needs: Author Feedback, Needs: Issue Template, Ran Commands

**Comment by msqar** [comment] 2020-02-15 21:04
I'm using Hermes in "true" in RN 0.60.6 and it works extremely fast. Now my app loads 2x faster when Hermes was in "false".

**Comment by ghasemikasra39** [comment] 2020-04-30 18:15
same here. Super slow

**Comment by baotoan1905** [comment] 2020-05-27 03:55
Any idea how to disable hermes. I set it false but get error 
![image](https://user-images.githubusercontent.com/7258479/82976191-9cdaf800-a008-11ea-9f7a-9ee3d0a0a059.png)

**Comment by ecreeth** [comment] 2020-05-27 04:04
@baotoan1905 if you've already built your app at least once, clean the build running this:
```sh
$ cd android && ./gradlew clean
```

**Comment by baotoan1905** [comment] 2020-05-27 07:19
> @baotoan1905 if you've already built your app at least once, clean the build running this:
> 
> ```shell
> $ cd android && ./gradlew clean
> ```

@ecreeth: Thanks for your replying. I have figured it out. It was because of that previously I got issue app crash when generating app bundle in release mode, to deal with it I had to add exclude '**/libjscexecutor.so' to section packagingOptions like bellow. 
![image](https://user-images.githubusercontent.com/7258479/82989452-ef2a1200-a024-11ea-82ab-9f900f131e5c.png)
After comment it out, it works if I want to disable hermes.

**Comment by rahamin1** [comment] 2020-10-12 11:30
My app, with hermes disabled, is slower on android with RN 0.62.2 than it was with 0.59.9 (but not as slow as it is for some people here that use hermes, nothing like 3 seconds response time). On iOS it is working fine.

@msqar 
> I'm using Hermes in "true" in RN 0.60.6 and it works extremely fast. Now my app loads 2x faster that when Hermes was in "false". (Release mode)
Did it only speed startup time or also speed the app afterwards? In my case, startup time is not a real concern...

@ollydixon 
> I'm testing with two real devices and an emulator. They are all extremely slow with the hermes flag enabled. Had to enabled it for 0.60.3 :-(
Why did you have to enable it? The docs say that it is optional.

**Comment by Anujmoglix** [comment] 2020-11-11 10:13
Why react native 0.63 very slow .?

**Comment by jeffelector** [comment] 2020-11-11 11:57
@Anujmoglix  Same here !!

**Comment by AngelLlamosas** [comment] 2020-11-16 03:32
same error in react-native 0.63.0

**Comment by Anujmoglix** [comment] 2020-11-16 19:37
React Native team is not working properly now .

**Comment by Arshimonde** [comment] 2021-02-08 09:15
Hello Guys, I tried this line of code in `/android/app/build.gradle` and it works
`configurations.all {
    resolutionStrategy {
        force "com.facebook.soloader:soloader:0.8.2"
    }
}`

**Comment by wmonecke** [comment] 2021-05-07 11:51
Guys we don't need comments like the ones left by @cisplRejjak or @ollydixon.
React Native is open-source after all and if you are so incompetent to deactivate it / upgrade to the next stable version then the problem might be you. If you bash the RN team or post condescending comments for these types of issues, then I pray for your coworker's health and sanity.

**Comment by ollydixon** [comment] 2021-05-07 11:58
@wmonecke it's not an issue with RN though it's more that it's not a container. It will always have significant platform bugs introduced by Android manufacturers and iOS updates and Android API changes. This isn't the case with Flutter since it effectivity runs on it's own engine.

I found that over the years, RN was pushing extremely broken and immature updates and using technologies that were new or not completed. For people who develop apps for multiple companies it was becoming a huge time sink to be on top of this.

Not only that; be we picked up hundreds of bugs across Android manufactures and design inconsistencies with our RN projects; which was the straw that broke the camels back.

If you're a professional developer, my advice is to stay very far from RN and use something like Flutter.

Even Native Android dev is broken; some of the manufacturers override default styles and margins, for example (many other things, like broken standard APIs; look at file management, for example.)

:-)

**Comment by wmonecke** [comment] 2021-05-07 14:44
@ollydixon It seems you have an opinion and I congratulate you! I have 50K MAU and very few bugs. To each, his own.

**Comment by marf** [comment] 2021-05-07 14:49
@ollydixon  We have 4.5M MAU and app is pretty stable with 99.77% crash-free users  using RN ;)

**Comment by ollydixon** [comment] 2021-05-08 14:46
> @ollydixon It seems you have an opinion and I congratulate you! I have 50K MAU and very few bugs. To each, his own.

It’s not an opinion it’s based of hard data. You can run a standard warehouse test across 20 different manufacturers for example; they’ll give you video results. Look at how broken RN is on some of those manufacturers. Firebase has cloud testing warehouses you can monkey run; you can see tons of inconsistencies and crashes with RN and even native Android dev :-) 

Hope this helps you find bugs 🐜

**Comment by wmonecke** [comment] 2021-05-08 15:18
😂 ok. In other words, dont post inflammatory and condescending comments on
an open source project. This is on a personal level. :-)

All the best and stay safe,

Walter Monecke

**Comment by rahamin1** [comment] 2021-05-11 20:10
> Hello Guys, I tried this line of code in `/android/app/build.gradle` and it works
> `configurations.all { resolutionStrategy { force "com.facebook.soloader:soloader:0.8.2" } }`

Thanks @Arshimonde. I tried this but it didn't help me:
- Without hermes, the app with 0.63.3 is **about 10 times slower** than the app with 0.59.9 (https://github.com/facebook/react-native/issues/30403)
- With hermes it is even slower (with 0.63.3, it is about 50% slower than without hermes)

**Comment by abdoutech19** [comment] 2021-06-11 10:12
Still same issue, hermes is super slow on debug mode, but not so bad on release mode. I really hope they fix this it's not just about startup time, hermes has to be enabled to setup and use Reanimated 2. :/

**Comment by rahamin1** [comment] 2021-06-15 20:17
@serjek Did you test the app on 0.63 and/or 0.62 and/or 0.59, too?

**Comment by serjek** [comment] 2021-06-15 21:49
> @serjek Did you test the app on 0.63 and/or 0.62 and/or 0.59, too?

Nope, only 64

**Comment by samulon13** [comment] 2021-06-16 00:57
you should test it also on a better android phone. I created a word search
puzzle and a candy crush like map using v64 and reanimated 2 and it runs
smoothly in my Xiaomi Redmi note 7. but it is slower in older phones. and
also the fact that the virtual list of rn is so much outdated might also be
a reason because the virtual list
requires a lot of ram unlike using a recyclable list. 😑

 PregTech
<https://drive.google.com/file/d/1WGHlAdLLqGvnpqR4iTrxohcChptdpagk/view?usp=drive_web>

>

**Comment by rahamin1** [comment] 2021-06-16 06:05
Thanks @samulron
How much RAM does your Redme note 7 have? [This page](https://www.gsmarena.com/xiaomi_redmi_note_7-9513.php) says 3 to 6GB...
I am testing on devices that have 4GB RAM.

@serek How much RAM do you have on the phone you are testing on?

**Comment by serjek** [comment] 2021-06-16 07:22
I did test with galaxy s9 (released in march 2018) which has 4GB of RAM. Worth noting that my users with different devices also report improved performance once I disabled hermes.

**Comment by rahamin1** [comment] 2021-06-16 07:47
Thanks. My main problem, though, is the degradation in performance from RN59 to later versions: https://github.com/facebook/react-native/issues/26870

**Comment by jslok** [comment] 2021-06-30 22:29
Same issue here on 64.1. Startup with hermes is slower. Changing images has a noticeable lag with hermes. Testing in release mode on a galaxy s20.

**Comment by pkpardeep482** [comment] 2021-09-06 08:52
Hi. Even i am facing same issue. i am using RN-0.60.4 and its works well on release builds. But due to some reasons which do test few items in debug builds too. Now due to hermes debug builds are too slow. Please help me out.

**Comment by tapz** [comment] 2021-09-20 11:28
0.65.1 with hermes debug builds seems to be extremely slow in Android. Not just the startup time, but the ui is super slow.
