### ISSUE TITLE
es6 `let` block-scope binding construct is particularly dangerous

### ISSUE THREAD

**Issue by psbanka** [facebook/react-native#1328] opened 2015-05-18 18:47 UTC
React-native's support for ES6 is fantastic, but one area where this could use some improvement is how `let` is handled.

When a developer is using Chrome for debugging, the `let` statement is fine and no errors are produced. However, when a dev switches to the native JS engine in the phone or emulator, you get a white-screen crash with no error messages. This can result in a very sad and painful debugging experience, that I can personally attest to :cry: . 

It would be nice if the pre-compile step would throw an exception for `let` when bundling or to throw an error in Chrome's console. Is that possible?

**Comment by ide** [comment] 2015-05-18 19:25
https://github.com/facebook/react-native/commit/723e988416f453f5ed1d382f84f96d3a73d17f21 should make this less of a mystery by putting up an error box when there's a syntax error. Not the same as your suggested fix but I believe it should make debugging the root cause a lot easier.

**Comment by jtremback** [comment] 2015-05-19 18:06
Why doesn't react-native just use babel?

**Comment by psbanka** [comment] 2015-05-20 15:44
Anything that crashes loudly would be perfect. Sounds good :+1:

**Comment by ide** [comment] 2015-05-20 19:31
@jtremback it's partly historical and partly due to performance as I understand it. Babel/6to5 wasn't as big as it is today (or didn't even exist) when React/RN were developed, and FB's JS processing pipeline already used jstransform. The good news is that a migration to Babel is on the horizon, though someone else would have to give you the timeline for that. https://github.com/facebook/esprima/issues/111

**Comment by ide** [comment] 2015-05-28 16:27
Babel is in master, RN is JS-hipster-approved, closing this out. https://github.com/tadeuzagallo/react-native/commit/56d6ee3f0fadeb66aeb6cf9156c723759f48f617

**Closed by ide** 2015-05-28 16:27 UTC

**Comment by jtremback** [comment] 2015-05-28 17:58
Is this in RN5.0?

**Comment by ide** [comment] 2015-05-28 18:09
I expect it will ship with 0.6 because it's a bigger change and not a bug fix for 0.5.0 rc.

**Comment by jtremback** [comment] 2015-05-28 18:11
Phew! Those 2 hours setting up and debugging Babel in my project yesterday
were not wasted!

**Comment by psbanka** [comment] 2015-05-31 02:48
Thank you!
