### ISSUE TITLE
Version 0.48.4 missing from npm

### ISSUE THREAD

**Issue by Armageddonas** [facebook/react-native#16074] opened 2017-09-23 15:16 UTC
`npm show react-native version` returns `0.48.3`  although version [0.48.4](https://github.com/facebook/react-native/releases/tag/v0.48.4) is released

**Comment by grabbou** [comment] 2017-09-23 17:49
This version hasn't been released yet. Latest is 0.48.3 as I said in the other issue.

We are aware of an issue that prevents latest build from being published and are working on a fix.

**Comment by hramos** [comment] 2017-09-23 20:12
Release is out now

Duplicate of #16022

**Closed by hramos** 2017-09-23 20:12 UTC
