### ISSUE TITLE
react native crashed in letv phone

### ISSUE THREAD

**Issue by tigerohuang** [facebook/react-native#13528] opened 2017-04-16 14:56 UTC
when I installed my app, even a new app from "react-native init xxx", it crashed immediately when start app, and I got error from logcat as following:

04-16 11:20:25.159 29156-29156/? I/art: Late-enabling -Xcheck:jni
04-16 11:20:25.177 29156-29162/? E/art: Failed sending reply to debugger: Broken pipe
04-16 11:20:25.177 29156-29162/? I/art: Debugger is no longer active
04-16 11:20:25.192 29156-29156/? V/fb-UnpackingSoSource: locked dso store /data/user/0/com.letv/lib-main
04-16 11:20:25.192 29156-29156/? I/fb-UnpackingSoSource: dso store is up-to-date: /data/user/0/com.letv/lib-main
04-16 11:20:25.192 29156-29156/? V/fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.letv/lib-main
04-16 11:20:25.192 29156-29156/? I/ActivityThreadEui: Handling launch of ActivityRecord{4c523ae token=android.os.BinderProxy@f63654f {com.letv/com.letv.MainActivity}} startsNotResumed=false
04-16 11:20:25.225 29156-29156/? W/unknown:React: You seem to be running on device. Run 'adb reverse tcp:8081 tcp:8081' to forward the debug server's port to the device.
04-16 11:20:25.225 29156-29171/? W/unknown:React: You seem to be running on device. Run 'adb reverse tcp:8081 tcp:8081' to forward the debug server's port to the device.
04-16 11:20:25.229 29156-29170/? W/unknown:React: You seem to be running on device. Run 'adb reverse tcp:8081 tcp:8081' to forward the debug server's port to the device.
04-16 11:20:25.232 29156-29156/? W/unknown:React: Packager connection already open, nooping.
04-16 11:20:25.232 29156-29156/? W/unknown:React: Inspector connection already open, nooping.
04-16 11:20:25.233 29156-29156/? D/ActivityThreadEui: check reason flags for activity window =com.letv.MainActivity reasonFlags=10000000
04-16 11:20:25.240 29156-29180/? D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
04-16 11:20:25.240 29156-29174/? W/unknown:ReconnectingWebSocket: Couldn't connect to "ws://localhost:8081/message?role=android-rn-devserverhelper", will silently retry
04-16 11:20:25.240 29156-29173/? W/unknown:InspectorPackagerConnection: Couldn't connect to packager, will silently retry
04-16 11:20:25.244 29156-29172/? W/unknown:React: The packager does not seem to be running as we got an IOException requesting its status: Failed to connect to localhost/127.0.0.1:8081
04-16 11:20:25.253 29156-29180/? I/Adreno: QUALCOMM build                   : ce26904, I3f4bae6ca5
                                           Build Date                       : 08/09/16
                                           OpenGL ES Shader Compiler Version: XE031.06.00.02
                                           Local Branch                     : 
                                           Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.BF64.1.2.2_RB4.06.00.01.180.046
                                           Remote Branch                    : NONE
                                           Reconstruct Branch               : NOTHING
04-16 11:20:25.258 29156-29180/? I/OpenGLRenderer: Initialized EGL, version 1.4
04-16 11:20:25.292 29156-29156/? I/art: Thread[1,tid=29156,Native,Thread*=0xf4476500,peer=0x739862a0,"main"] recursive attempt to load library "/data/app/com.letv-1/lib/arm/libfb.so"
04-16 11:20:25.307 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupViewManager
04-16 11:20:25.308 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupShadowNode
04-16 11:20:25.310 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeViewManager
04-16 11:20:25.310 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeShadowNode
04-16 11:20:25.312 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextViewManager
04-16 11:20:25.312 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextShadowNode
04-16 11:20:25.313 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewManager
04-16 11:20:25.316 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewShadowNode
04-16 11:20:25.320 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDialogPickerManager
04-16 11:20:25.321 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode
04-16 11:20:25.321 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
04-16 11:20:25.324 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDropdownPickerManager
04-16 11:20:25.324 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
04-16 11:20:25.327 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.image.ReactImageManager
04-16 11:20:25.330 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ReactModalHostManager
04-16 11:20:25.331 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ModalHostShadowNode
04-16 11:20:25.331 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
04-16 11:20:25.333 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
04-16 11:20:25.334 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
04-16 11:20:25.336 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextShadowNode
04-16 11:20:25.338 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
04-16 11:20:25.340 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager
04-16 11:20:25.342 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager$ReactSliderShadowNode
04-16 11:20:25.342 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
04-16 11:20:25.344 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
04-16 11:20:25.345 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageViewManager
04-16 11:20:25.345 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageShadowNode
04-16 11:20:25.346 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputManager
04-16 11:20:25.351 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
04-16 11:20:25.351 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextViewManager
04-16 11:20:25.352 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.toolbar.ReactToolbarManager
04-16 11:20:25.356 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
04-16 11:20:25.359 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.viewpager.ReactViewPagerManager
04-16 11:20:25.360 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
04-16 11:20:25.360 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.webview.ReactWebViewManager
04-16 11:20:25.362 29156-29183/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
                                                                       
                                                                       [ 04-16 11:20:25.380 29156:29183 E/         ]
                                                                       Unable to load script from assets: index.android.bundle
04-16 11:20:25.382 29156-29185/? E/unknown:React: Exception in native call from JS
                                                  com.facebook.react.devsupport.JSException: Could not get BatchedBridge, make sure your bundle is packaged correctly
                                                      at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                      at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                      at android.os.Looper.loop(Looper.java:148)
                                                      at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                      at java.lang.Thread.run(Thread.java:818)
                                                   Caused by: com.facebook.jni.CppException: Could not get BatchedBridge, make sure your bundle is packaged correctly
                                                      at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                      at android.os.Handler.handleCallback(Handler.java:739) 
                                                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                      at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                                                      at android.os.Looper.loop(Looper.java:148) 
                                                      at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196) 
                                                      at java.lang.Thread.run(Thread.java:818) 
04-16 11:20:25.392 29156-29156/? W/unknown:React: Packager connection already open, nooping.
04-16 11:20:25.392 29156-29156/? W/unknown:React: Inspector connection already open, nooping.
04-16 11:20:25.395 29156-29185/? E/unknown:React: Exception in native call
                                                  java.lang.RuntimeException: Error calling RCTDeviceEventEmitter.emit
                                                      at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                      at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                      at android.os.Looper.loop(Looper.java:148)
                                                      at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                      at java.lang.Thread.run(Thread.java:818)
                                                   Caused by: java.lang.RuntimeException: Empty Optional cannot be unwrapped
                                                      at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                      at android.os.Handler.handleCallback(Handler.java:739) 
                                                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                      at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                                                      at android.os.Looper.loop(Looper.java:148) 
                                                      at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196) 
                                                      at java.lang.Thread.run(Thread.java:818) 
04-16 11:20:25.400 29156-29185/? E/unknown:React: Exception in native call
                                                  java.lang.RuntimeException: Error calling AppRegistry.runApplication
                                                      at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                      at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                      at android.os.Looper.loop(Looper.java:148)
                                                      at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                      at java.lang.Thread.run(Thread.java:818)
                                                   Caused by: java.lang.RuntimeException: Empty Optional cannot be unwrapped
                                                      at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                      at android.os.Handler.handleCallback(Handler.java:739) 
                                                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                      at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                                                      at android.os.Looper.loop(Looper.java:148) 
                                                      at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196) 
                                                      at java.lang.Thread.run(Thread.java:818) 
04-16 11:20:25.419 29156-29156/? W/unknown:React: Calling JS function after bridge has been destroyed.

**Comment by marktolson** [comment] 2017-05-03 01:10
Im also receiving the error: "Error calling Appregistry.runApplication" after creating a brand new project. Any updates?

**Comment by lanjie233** [comment] 2017-05-09 08:33
me too

**Comment by hramos** [comment] 2017-05-22 23:15
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-05-22 23:15 UTC
