### ISSUE TITLE
FlatList performance slow on large changes to list

### ISSUE THREAD

**Issue by davidliu** [facebook/react-native#18142] opened 2018-03-01 00:42 UTC
### Is this a bug report?

Yes. A reopening of #16186, as it is reproducible on 0.53.3

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes.

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 9.4.0
  Yarn: 1.3.2
  npm: 4.6.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.3 => 0.53.3

Target Platform: iOS and Android (various OS versions, up to and including latest on each).

### Steps to Reproduce

(Copied from the previous issue, as it still applies).

I have a FlatList that contains many items (1000+). It represents a lengthy checklist. I have a "Select All" button which causes every item in the list to be selected. The performance of rendering this is noticeably bad.

1. Open the Snack https://snack.expo.io/S1z6PMZnZ (preferably on a physical device since iOS simulator will likely have better performance than a physical device)
2. Tap on an individual row to see a slight lag in performance
3. Tap on "Select All" or "Deselect All" to change every item in the list and see a big delay in rendering the new state

Note that in the Snack, I am only recreating a single object of id->boolean key/value pairs when a change is made. This is my effort to isolate FlatList performance.

### Expected Behavior

Since a FlatList doesn't render offscreen components, it should not synchronously update any offscreen elements, but instead asynchronously update those elements as it does for its initial load. This will result in a quick and responsive update of onscreen elements without blocking the ui for too long.

### Actual Behavior

If you tap "Select All" or "Deselect All" (whichever changes all the items in a list), there is a large amount of rendering lag. 

![31130396-840df172-a814-11e7-856a-ab6e8d076f26](https://user-images.githubusercontent.com/242400/36821051-e83262e0-1ca5-11e8-9cb3-b94eb54166b7.gif)

If you profile it on a device with Chrome Debugging tools, you'll notice that it spends a lot of time updating every single row, even though most of the rows are offscreen.

<img width="1384" alt="screen shot 2018-02-28 at 4 39 50 pm" src="https://user-images.githubusercontent.com/242400/36821080-0b78e12a-1ca6-11e8-9e9f-e1e0f32b8087.png">

<img width="1347" alt="screen shot 2018-02-28 at 4 40 49 pm" src="https://user-images.githubusercontent.com/242400/36821112-32884fee-1ca6-11e8-8bcf-a06cd77bb2dd.png">

### Reproducible Demo

https://snack.expo.io/S1z6PMZnZ

**Comment by davidliu** [comment] 2018-03-01 00:45
The profile.json for the above chrome debugging profile.

[Profile-20180228T164420.json.txt](https://github.com/facebook/react-native/files/1769327/Profile-20180228T164420.json.txt)

**Comment by davidliu** [comment] 2018-03-05 21:53
Confirmed bug still exists in 0.54.0

**Comment by rawrmaan** [comment] 2018-05-06 04:39
Have you tried adjusting the `maxToRenderPerBatch` or `windowSize` props on FlatList?

**Comment by davidliu** [comment] 2018-05-16 02:24
@react-native-bot Yes, the issue is still present on v0.55.

**Comment by davidliu** [comment] 2018-05-16 03:26
@rawrmaan seems like the issue is related to the default `windowSize` for these small rows. With a default windowSize of 21, 10 screens of rows in each direction are rendered. When the select all happens, all of those "rendered" views will each get the update call propagated to them synchronously, regardless of if they're onscreen or not. For these small rows, that's about 300ish views total.

`windowSize` can be tweaked to band-aid around this issue, but I think it should be the responsibility of VirtualizedList to only immediately re-render synchronously onscreen items, and not offscreen items.

**Comment by davidliu** [comment] 2018-05-16 03:27
@react-native-bot still exists on latest v0.55.

**Comment by kelset** [comment] 2018-05-23 08:47
Duplicate of https://github.com/facebook/react-native/issues/14968

**Comment by davidliu** [comment] 2018-05-23 20:26
@kelset These two bugs seem unrelated? #14968 is an issue of cells not being initially rendered and not added to the view fast enough due to the asynchronous nature of VirtualizedList rendering.

This issue is different, in that views that have been already rendered (due to windowSize) will get rerendered synchronously after a setState call.

**Comment by kelset** [comment] 2018-05-24 07:41
I see your point - I'll reopen this. (usually issues related to lists tend to be more, like, collections of different issues so I thought I saw in the comments there something related to yours and was trying to reduce the redundancy)

Anyway, I'll reopen and tag properly.

**Comment by ccoeder** [comment] 2018-08-25 09:56
I can confirm that bug is still exists.

**Comment by fogil** [comment] 2018-11-10 17:56
FlatList renders every item in a list, regardless if they are within the view space or not.  Put a console.log('hi i am being rendered') in the renderItem function.  For a list of a thousand items, you'll get a thousand console log messages.

Use RecyclerListView instead, it does what it advertises but unfortunately does not support Headers/Footers.

**Comment by cmacdonnacha** [comment] 2019-03-05 22:23
Any update on this? Same issue occurs for a SectionList. Any workaround?

**Comment by bvaughn** [comment] 2019-08-29 17:23
Doesn't seem like this should have been closed. Re-opening.

cc @sahrens in case you're interested.

**Comment by sahrens** [comment] 2019-08-29 17:54
@davidliu: I don't think adjusting the parameters to better fit for a specific workload is that big of a problem - does it not address your use-case? You can also try https://github.com/Flipkart/recyclerlistview - it might be a better fit for your usecase.

I don't think it's feasible for `VirtualizedList` to implement even more complex scheduling of react component rendering and updates - the ReactJS core is enabling that with async/concurrent mode with priorities, and `VirtualizedList` (or maybe even `ScrollView` itself) will be able to integrate with those APIs, but it is quite a ways off (maybe post-Fabric which will unlock a lot of awesome potential there, including optional synchronous rendering to prevent checkerboarding). However, if you have ideas for how to fix things now that doesn't complicate the code too much or compromise other features, I'm happy to consider a PR.

@bvaughn: how does react-window handle the "select all" case for thousands of elements? Any tricks or does it just rely on faster desktops and smaller window sizes by default?

**Comment by bvaughn** [comment] 2019-08-29 18:02
> @bvaughn: how does react-window handle the "select all" case for thousands of elements? Any tricks or does it just rely on faster desktops and smaller window sizes by default?

@sahrens I think I'm missing some context. "select all" sounds like a data/state update. Why would it render anything that isn't visible on the screen?

**Comment by sahrens** [comment] 2019-08-30 12:54
The list could have thousands of entries, many of which aren't rendered thanks to windowing. But VirtualizedList and react-window both have a concept of buffer/overscan to render content outside of the immediately visible viewport. It sounds like react-window just has a small enough overscanCount (2 rows by default?) that it's not an issue if every row that's rendered needs to be updated at the same time.

@davidliu: please try a smaller windowSize - 1.0, 0.5, or maybe even 0.25. Also, make sure your row components are optimized to avoid deep renders of children that don't actually need to be updated when the selected state changes.

I'm going to close this out because I don't think there is any further action we are going to take until Fabric rolls out.

**Closed by sahrens** 2019-08-30 12:54 UTC
Labels: Bug, Component: FlatList, Issue: Author Provided Repro, JavaScript, Ran Commands

**Comment by bvaughn** [comment] 2019-08-30 14:51
@sahrens That's not what I understood was happening. Based on [this comment](https://github.com/facebook/react-native/issues/18142#issuecomment-437603136) it sounded like the list was rendering *every item* (not just an overscanned batch).

> For a list of a thousand items, you'll get a thousand console log messages.

**Comment by sahrens** [comment] 2019-09-04 16:50
> For a list of a thousand items, you'll get a thousand console log messages.

We have recently confirmed this is not the case - windowing works correctly. If @fogil is seeing otherwise, he should submit another issue with a repro case.

**Comment by bvaughn** [comment] 2019-09-04 16:57
Gotcha. Thanks for clarifying.
