### ISSUE TITLE
The --device option fails on command line in v53.0

### ISSUE THREAD

**Issue by berkcoker** [facebook/react-native#17921] opened 2018-02-09 04:26 UTC
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.9.0
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.2.0 => 16.2.0
  react-native: ^0.53.0 => 0.53.0

### Steps to Reproduce

The following commit that came with the new release (v53.0) causes problems when the --device option is specified. The port is set to undefined for the Metro bundler.

_react-native run-ios now supports the --port argument for metro (33d710e)_

**Comment by hramos** [comment] 2018-02-09 20:41
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue that meets the requirements set forth in the template. Thanks!

**Closed by hramos** 2018-02-09 20:41 UTC
Labels: Failed Commands

**Comment by Gulci** [comment] 2018-02-14 03:50
I'm having this issue as well. I've reopened it for him here: https://github.com/facebook/react-native/issues/17973
