### ISSUE TITLE
BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 63

### ISSUE THREAD

**Issue by mrsants** [facebook/react-native#36313] opened 2023-02-27 16:04 UTC
### Description

It is not clear to me that it is related to the Java version, it would be interesting to verify the Java version or a friendlier message

<img width="1442" alt="Captura de Tela 2023-02-27 às 13 01 04" src="https://user-images.githubusercontent.com/59406899/221614870-b46d562e-c072-437a-b654-be35514defdd.png">

### React Native Version

0.71.0

### Steps to reproduce

react native 0.71.0
mac ventura
nodejs 16

**Comment by cortinico** [comment] 2023-02-27 18:38
Please provide the information the bot asked you about

**Comment by Nicksqain** [comment] 2023-03-01 14:59
Hello! I have a problem with launching the created application.
npx-react-native doctor showed that everything is ready, but this happens. Help me solve this problem.

![изображение](https://user-images.githubusercontent.com/67852536/222176654-1ac2dfc6-f3d4-40fc-925b-9adcaf42c68f.png)

**Comment by mrsants** [comment] 2023-03-01 17:05
> Hello! I have a same problem with launching the created application. npx-react-native doctor showed that everything is ready, but this happens. Help me solve this problem.
> 
> ![изображение](https://user-images.githubusercontent.com/67852536/222176654-1ac2dfc6-f3d4-40fc-925b-9adcaf42c68f.png)


check the jdk version installed on your machine and check the requested version in react native

**Comment by cortinico** [comment] 2023-03-01 18:54
@mrsants can you please provide your `react-native config` output as the bot asked you about?
The issue is related to wrong Java version but we can't help wihtout knowing which version you have.

**Comment by mrsants** [comment] 2023-03-01 19:25
> @mrsants can you please provide your `react-native config` output as the bot asked you about? The issue is related to wrong Java version but we can't help wihtout knowing which version you have.

actually I'm not sure if it's related to the jdk version, and at some point I used version 19 and there was this error, I regressed to version 11 and there was no error in the build

**Comment by cortinico** [comment] 2023-03-02 12:01
> actually I'm not sure if it's related to the jdk version, and at some point I used version 19 and there was this error, I regressed to version 11 and there was no error in the build

Then it's definitely related to the Java version.
Anyway, closing as you mentioned you've solved this issue by switching to JDK 11 (which is the recommended one).

**Closed by cortinico** 2023-03-02 12:01 UTC
Labels: Needs: Environment Info, Needs: Verify on Latest Version, Needs: Attention
