### ISSUE TITLE
Yoga Logic Error

### ISSUE THREAD

**Issue by PrimeLens** [facebook/react-native#14686] opened 2017-06-22 15:13 UTC
I'm getting the following Yoga logic errors (see attached) and they started appearing at the same time as [this issue here](https://github.com/facebook/react-native/issues/11498#issuecomment-310400069) which may or may not be unrelated.  When I reduce my app down to a simple hello world the app compiles and runs fine in the simulator despite the Yoga errors showing.
<img width="295" alt="yoga issues" src="https://user-images.githubusercontent.com/636249/27441222-dd9fe798-573a-11e7-8ca8-1ceaa97ba60d.png">
<img width="280" alt="yoga issues2" src="https://user-images.githubusercontent.com/636249/27441225-e1e76894-573a-11e7-9077-172a67ef115f.png">

**Comment by tabrindle** [comment] 2017-06-22 16:26
If you run `npm i -g envinfo` then`envinfo --packages react,react-native`, you will get an output of all the relevant debug information like this:

```
Environment:
  OS:  macOS Sierra
  Node:  v7.10.0
  Yarn:  0.24.5
  npm:  4.2.0
  Xcode:  Xcode 8.3.3 Build version 8E3004b 
  Android Studio:  2.3 AI-162.3934792 
  react:  16.0.0-alpha.6
  react-native:  0.44.0
```

**Comment by hramos** [comment] 2017-06-26 14:26
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-26 14:26 UTC

**Comment by warrenronsiek** [comment] 2017-07-08 21:15
I have the same problem after upgrading to react-native 0.46.1. Running envinfo gives me:
```
Environment:
  OS:  macOS Sierra 10.12.5
  Node:  v7.7.1
  Yarn:  0.27.5
  npm:  5.0.3
  Xcode:  Xcode 8.3.3 Build version 8E3004b 
  Android Studio:  2.1 AI-143.2790544 
Packages:
  react:  ^16.0.0-alpha.12
  react-native:  ^0.46.1
```

**Comment by lucasromanojf** [comment] 2017-10-09 14:12
+1

**Comment by hanjianqiao** [comment] 2017-10-20 03:30
### Is this a bug report?

Surely is. I think the bug belongs to Xcode.


### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

No!

### Environment



```
Environment:
  OS:  macOS Sierra 10.12.6
  Node:  8.6.0
  Yarn:  Not Found
  npm:  5.5.1
  Watchman:  4.9.0
  Xcode:  Xcode 9.0.1 Build version 9A1004
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.3 => 0.49.3
```

### Steps to Reproduce



(Write your steps here:)

1. following [React Native: Getting Started](https://facebook.github.io/react-native/docs/getting-started.html)
2. open ios project with Xcode
3. run build

### Expected Behavior



I think it will produce some warnings then successfully build the application.

### Actual Behavior



The logical error in build time:
same as @PrimeLens 
```
![image](https://user-images.githubusercontent.com/636249/27441222-dd9fe798-573a-11e7-8ca8-1ceaa97ba60d.png)
```

### Reproducible Demo



I think the bug belongs to either xcode or yoga:

code have logical error:
```
```

code not have logical error:

**Comment by hramos** [comment] 2017-10-20 14:21
Do you want to post this as a new issue?
