### ISSUE TITLE
[0.19][Android][ListView] onChangeVisibleRows isn't called on Android

### ISSUE THREAD

**Issue by bit3725** [facebook/react-native#5688] opened 2016-02-02 05:03 UTC
Hi, i found the function for **onChangeVisibleRows** of ListView would be called on iOS when init or scroll a ListView but not on Android. 

I did a quick dig in source code of ListView component and found **e.nativeEvent.updatedChildFrames** was undefined when passed to _updateVisibleRows function which caused **onChangeVisibleRows** can't be called on Android. 

I checked UIExplorer example also and saw this prop was demonstrated in ListViewPagingExample, but only included in example of iOS version. Does it mean it's not supported on Android currently?

**Comment by nikuz** [comment] 2016-02-06 06:37
The issue is reproduced for me also. The "onChangeVisibleRows" event is triggered on iOS but don't triggered on Android.

**Comment by alongubkin** [comment] 2016-02-06 15:29
Same here

**Comment by nikuz** [comment] 2016-02-08 06:55
Adding "renderScrollComponent" to the "ListView" will break the "onChangeVisibleRows" even in iOS as and "onEndReached".

**Comment by terrysahaidak** [comment] 2016-03-27 15:41
any updates?

**Comment by terrysahaidak** [comment] 2016-04-11 09:03
For everyone interested I've created [productpain post](https://productpains.com/post/react-native/listview-onchangevisiblerows-android-support).

**Comment by Mohamed-amin** [comment] 2016-05-15 14:13
No updates on this ?

**Comment by sampurcell93** [comment] 2016-05-16 00:20
Hi, to anybody looking for a solution to this problem, I wrote one in javascript. It seems to work pretty well, but only for vertical listviews (at the moment), and with no real thought given to additional complexity. I haven't submitted a pull request because I think this should be done natively, and my code is not robust enough yet. However, if you'd like to follow these steps, you can increase the performance of your ListView by a lot and get onChangeVisibleRows to fire.

- [Add this diff to your ListView](https://cloud.githubusercontent.com/assets/197597/9294313/8c5ffa86-43fe-11e5-8044-c469a9b64d57.png). Careful to convert offsetX/offsetY to regular offsets, as support for horizontal ListViews has apparently been added since this diff was recorded.
- At the top of `_updateVisibleRows` add the following code: 
```
    var updatedFrames = [];
    let ySum = 0;
    for (var i = 0; i < this.props.dataSource._dataBlob.s1.length; i++) {
      const height = (this.props.childHeights[i] || this.props.defaultRowHeight);
      updatedFrames.push({
        index: i,
        x: 0,
        y: ySum,
        width: this.props.defaultRowWidth,
        height
      });
      ySum += height;
    }
```

This will make sure that you have an array of meta data with which the existing algorithm can calculate changes in visibility.

- In order to make this work, you need to bind an onLayoutHandler to each item in the list that populates the childHeights array. Something like: 
```
class MyListWrapper extends Component {
  constructor() {
    super()
    this.childHeights = [];
  }
 ....
renderRow(data, index) {
  return <View onLayout={(e) => {this.childHeights[index] = e.nativeEvent.layout.height;}}/>
}
...
render() {
  return <ListView renderRow={this.renderRow} childHeights={this.childHeights} defaultRowHeight={n}/>
}
```
This could also probably be done within the ListView itself. But I didn't want to go around meddling too much in there. I have not had any problems with rendering since implementing this, and I can confirm that views are indeed recycled as you scroll. I have an image heavy ListView in my app, and now I can confirm that my memory allocation has been decimated since doing this.

I just want to reiterate that this solution is a *hack* and only to be used when you have little time for anything else. Hope it helps somebody that's in a jam.

Sam

**Comment by Mohamed-amin** [comment] 2016-05-17 06:29
@sampurcell93  Thanks sam! though, I agree with you that should be handled natively

**Comment by terrysahaidak** [comment] 2016-05-17 07:03
@sampurcell93 thank you so much! Gonna try your workaround with my [GitterMobile](https://github.com/terrysahaidak/GitterMobile) and will write back my results for anyone interested.

**Comment by sampurcell93** [comment] 2016-05-17 15:26
Also, I just realized I'm an idiot and forgot that the x and y values are present in the nativeEvent.layout object. So there is no need for computing those.

**Comment by terrysahaidak** [comment] 2016-05-17 15:34
@sampurcell93 so what should I do? I didn't understand :) I think it would be great if you write the blog post or smth like that about it.

**Comment by sampurcell93** [comment] 2016-05-17 17:10
Hey terry, the wrapper code can be modified to look something like this:
```
class MyListWrapper extends Component {
  constructor() {
    super()
    this.childHeights = [];
  }
   ....
  renderRow(data, secId, rowId) {
    /** Don't get layout.height, just get layout. It already contains {height, x, y, width} so we don't need to compute */
    return <View onLayout={(e) => {this.childHeights[parseInt(rowId)] = e.nativeEvent.layout;}}/>
  }
  ...
  render() {
    return <ListView renderRow={this.renderRow} childHeights={this.childHeights} defaultRowHeight={n}/>
  }
}
```

And the ListView itself, at the top of _updateVisibleRows():
```
var updatedFrames = [];
    const horizontal = this.props.horizontal;
    if (this.props.dataSource._dataBlob.s1) {
      for (var i = 0; i < this.props.dataSource._dataBlob.s1.length; i++) {
        if (this.props.childSizes[i]) {
          updatedFrames.push({
            ...this.props.childSizes[i],
            index: i
          })
        } else {
          updatedFrames.push({
            index: i,
            height: horizontal ? 0 : this.props.defaultRowSize,
            width: horizontal ? this.props.defaultRowSize : 0,
            y: horizontal ? 0 : i * this.props.defaultRowSize,
            x: horizontal ? i * this.props.defaultRowSize : 0
          });
        }
      }
    }
```

Just a reminder that `this.props.dataSource._dataBlob.s1` will fail on any list with custom sections / more than one section.

**Comment by terrysahaidak** [comment] 2016-05-17 21:14
Thanks, @sampurcell93, but it doesn't want to work for some reasons. Can you, please, share working example? (:

**Comment by sampurcell93** [comment] 2016-05-17 21:25
Make sure you comment out this line:

```
if (!this.props.onChangeVisibleRows) {
  return; // No need to compute visible rows if there is no callback
}
```

Follow to flow of your code. Ensure that the updatedFrames array is being populated correctly.

**Comment by terrysahaidak** [comment] 2016-05-18 15:45
Still can't get it works. Also, I've noticed some naming differents between list view component in your diff and official one.
Can you make a gist with working ListView, please?

**Comment by terrysahaidak** [comment] 2016-05-19 15:51
So, I realized you've used RN 0.8 version of ListView, so now seems to works, but very laggy. For first -- all my rows are visible after render (why?). Second -- updateVisibleRows doesn't calls while scrolling; Third -- it's randomly calling; Fourth -- I have to delete `isVsisble` part because my rows don't render at all.

/cc @sampurcell93

**Comment by sampurcell93** [comment] 2016-05-20 14:55
Hey terry, sorry for the delay. [Here is a link to the complete ListView gist](https://gist.github.com/sampurcell93/8cfdf99e03ccea0a68c4fdd947645f0f).

When calling this listview, pass in an array of height numbers (ie `[300, 327, ...etc]`). You can also pass in withOptimizations={false} to disable this computation behavior.

**Comment by terrysahaidak** [comment] 2016-05-20 15:36
Hey, Sam. Thank you so much! Now it works great.

**Comment by terrysahaidak** [comment] 2016-05-27 10:41
Hey, Sam. Can you make an npm module with your modified ListView? It would be super cool as I'm not using forked react native, also it would be great if you will maintain it. 

/cc @sampurcell93

**Comment by guyca** [comment] 2016-06-14 07:01
+1

**Comment by terrysahaidak** [comment] 2016-06-14 07:05
@guyca it'll be better if you vote up [productpains post](https://productpains.com/post/react-native/listview-onchangevisiblerows-android-support) and ask your friends to do the same thing instead of letting a useless comment like `+1`. Thanks)

**Comment by plraphael** [comment] 2016-08-04 15:21
Thanks for the gist @sampurcell93. One question: is it possible to use your code if I don't know in advance the height of my rows (because they have variable height)?

**Comment by droidwolf** [comment] 2016-09-23 06:49
I wrote a real android RecyclerView to solve this problem. No memory leaks and slide is very smooth.
[react-native-RealRecyclerView](https://github.com/droidwolf/react-native-RealRecyclerView)

**Comment by terrysahaidak** [comment] 2016-09-23 08:32
@droidwolf is it working with dynamic rows' height?

**Comment by droidwolf** [comment] 2016-09-23 08:37
No, you need to set up [rowHeight] (https://github.com/droidwolf/react-native-RealRecyclerView/blob/master/index.android.js#L38) property values

**Comment by DannyvanderJagt** [comment] 2016-11-11 11:35
Any progress on this issue? Would be nice if it worked 👍

**Comment by ptomasroos** [comment] 2017-01-17 19:36
I've provided a PR on this at https://github.com/facebook/react-native/pull/11945

**Comment by hramos** [comment] 2017-03-31 18:29
Closing as ListView is deprecated in 0.43. Use FlatList.

**Closed by hramos** 2017-03-31 18:29 UTC
Labels: Android

**Comment by kitolog** [comment] 2017-06-22 12:19
Does FlatList support pages? may I do a pagination using FlatList?
