### ISSUE TITLE
Can't read json response when negociating with an external server

### ISSUE THREAD

**Issue by patricekaratchentzeff** [facebook/react-native#37774] opened 2023-06-08 15:40 UTC
### Description

Hi,

I submit a json request as couple login + password for connecting to an external server. The server receives the json couple and if the couple is right, sent a json for indicating that the state is connected, otherwise unconnected.

On the server side, all is OK (it is a Perl Dancer2):

```
% curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"login":"PK","password":"PK"}' \
  http://localhost:5000/connect
{"ConnectionState":"connected"}

% curl --header "Content-Type: application/json" --request POST --data
'{"login":"PK","password":""}' http://localhost:5000/connect
{"ConnectionState":"unconnected"}

% curl --header "Content-Type: application/json" --request POST
http://localhost:5000/connect
{"ConnectionState":"unconnected"}

% curl  http://localhost:5000/connect
{"status":404,"title":"Error 404 - Not Found","message":"/connect"}

% curl --header "Content-Type: application/json" --request POST
http://localhost:5000/connect
{"ConnectionState":"unconnected"}
```
Firefox tells me that the json response is uncorrect:

```
 Uncaught (in promise) SyntaxError: JSON.parse: unexpected
end of data at line 1 column 1 of the JSON data
```

But its network debugger shows a correct negotiation and a nice json response.

Chromium (I work on Linux) stops immediately with the error on json response:

```
p.js:34 Uncaught (in promise) SyntaxError: Unexpected end of input (at App.js:34:1)
    at App.js:34:1
```
and its network debugger indicates no negotiation.

The server logs are in phase with the two both behaviors.

Since the server seems OK without my native React script, I suspect now a bug anywhere in the process inside Native React (may be in my script, but it is enough classical and you can find it anywhere on the net as example).

I have isolated the bug in a single script that I put into the bug report.

I have changed of nvm version without change.

### React Native Version

0.71.8

### Output of `npx react-native info`

% npx react-native info
info Fetching system and libraries information...
System:
    OS: Linux 5.15 Linux Mint 21.1 (Vera)
    CPU: (4) x64 Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
    Memory: 13.73 GB / 31.25 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.2.0 - ~/.nvm/versions/node/v20.2.0/bin/node
    Yarn: Not Found
    npm: 9.6.6 - ~/.nvm/versions/node/v20.2.0/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.8 => 0.71.8
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

```
% npx create-expo-app my-app
% cd my-app
% nps expo install react-dom react-native-web @expo/webpack-config
```

Replace App.js per my code.

If you not have a server, please uncomment the external server for json response

```
%  npx expo start -- -c
```

Active web metro server:

Then goto FF and Chromium to print the page and see the log and debug network pages.

I let in the code the different accesses to debug (console.log) and a analyse of text instead of json for the response.

### Snack, code example, screenshot, or link to a repository

```javascript
import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
} from 'react-native';

const ipAddress     = "192.168.1.103";   
const portAddress   ="5000";
const httpProtocol  = "http";
const uriBase       = httpProtocol + "://" + ipAddress + ":" + portAddress ;


function App() {

  const jsonReader = { 'login':"PK", 'password':"PK" };
  let string = JSON.stringify(jsonReader);
  
  const [message, setMessage] = useState("disconnected");
  
  const submitConnectAsync2 = async () => {
    return fetch(
            uriBase + '/connect', {
      //'http://jsonplaceholder.typicode.com/posts', {
	mode: 'no-cors', // beurk... 
	method: 'POST',
	headers: {
          'Accept' : 'application/json',
          'Content-Type' : 'application/json',
	},
	body: JSON.stringify(jsonReader),
      })
      .then( (response) => {
      	//response.text();
	response.json();
      	//console.log("Response:", response.text());
	console.log("Response:", response.json());
      	console.log("Fin de l'envoi");
      })
      .then(text => {
        console.log(`Received ${JSON.stringify(text)}`);
      	console.log("text :", text);
        //let json = JSON.parse(text);
        //setMessage(json);
        console.log("Coucou2");
      })
      .then( (json) => {
      	setMessage("Connecté à la main");
      	console.log("(1) connection state:", message);
      	console.log("Fin de la réception");
      })
      .catch( error => {
	console.log("Transaction error:", error);
	//console.log("body:", JSON.stringify(jsonReader));
	//console.log("response:", response.son());
	//console.log("json:", json);
      });
  };
  console.log("(2) connection state:", message);

  useEffect(() => {
    submitConnectAsync2();
  }, []);
  
  
 return (
   <View style={{flex:1,backgroundColor:"white"}}>
     <Text>
       {message}
     </Text>
   </View>
  );
  
    
}

export default App;
```

**Comment by patricekaratchentzeff** [comment] 2023-06-08 15:46
I have upgraded at 0.71.10 as asked by the robot.

metro does not appreciate, but seems still functional.

There is no change about my problem.

Thanks in advance

**Comment by cortinico** [comment] 2023-06-19 15:48
Closing as duplicate of #37907

**Closed by cortinico** 2023-06-19 15:48 UTC
Labels: Needs: Triage :mag:, Newer Patch Available
