### ISSUE TITLE
one webview bug  not fit screen on android 

### ISSUE THREAD

**Issue by hongshu123** [facebook/react-native#15579] opened 2017-08-21 04:53 UTC
this url : 'http://www.dadichuangke.vip/app/index.php?i=1&c=entry&eid=15', i open in  phone‘s   browser   is ok ,but  i make a webview   ，it cant  fit screen on android 。 

```
<WebView
					ref={(e)=> {
						this.WEBVIEW_REF = e
					}}
					onLoadEnd={this.onLoadEnd.bind(this)}
					source={{uri:'http://www.dadichuangke.vip/app/index.php?i=1&c=entry&eid=15&xxx=11' }}
					javaScriptEnabled={true}
				/>
```

in this website has : 
```
	head = document.getElementsByTagName('head');
	viewport = document.createElement('meta');
	viewport.name = 'viewport';
	viewport.content = 'target-densitydpi=device-dpi, width=' + 640 + 'px, user-scalable=no';
	head.length > 0 && head[head.length - 1].appendChild(viewport);  
```

i found  it's because  this js has not exec。

![1111](https://user-images.githubusercontent.com/12556069/29504970-f24000e2-8675-11e7-8671-f1d4234e9d8d.png)

**Comment by hongshu123** [comment] 2017-08-21 08:08
e..， i add  a scalesPageToFit={false}  ,that is ok ...   thanks

**Comment by hramos** [comment] 2017-08-23 19:22
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-08-23 19:22 UTC
