### ISSUE TITLE
error: bundling: UnableToResolveError: Unable to resolve module `ReactNativeART` from `/node_modules/react-native/Libraries/react-native/react-native-implementation.js`: Module does not exist in the module map or in these directories:

### ISSUE THREAD

**Issue by karthiganesan90** [facebook/react-native#14491] opened 2017-06-13 14:43 UTC
## Reporting Bugs

Recently I have updated the npm & react-native package.
I am getting this error while running the build in both IOS & Android.

**Version:**

Updated react-native version : 0.45.1
Updated npm version : 3.10.10

**dependencies**

"dependencies": {
    "react": "^16.0.0-alpha.6",
    "react-addons-pure-render-mixin": "^15.5.2",
    "react-native": "^0.45.1",
    "react-native-fingerprint-android": "^0.1.4",
    "react-native-linear-gradient": "^2.0.0",
    "react-native-navigation-drawer": "^1.2.2",
    "react-native-touch-id": "^3.0.0",
    "react-navigation": "git+https://github.com/react-community/react-navigation.git",
    "react-static-container": "^1.0.1"
  },

**Comment by hramos** [comment] 2017-06-13 16:44
Hey, thanks for reporting this issue! Can you provide exact reproduction steps?

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-13 16:44 UTC

**Comment by aaronbuchanan** [comment] 2017-06-22 21:11
I'm also getting this error (in 44.2 though), @karthiganesan90 did you find a solve?

**Comment by karthiganesan90** [comment] 2017-06-23 10:01
@aaronbuchanan - This issue had happened of newly added npm moudle causes-( react-native-navigation-drawer.)

1. remove the react-native-navigation-drawer npm module
2. please update your react native libs using react-native-git-upgrade

**Comment by EugeneBichel** [comment] 2017-07-12 08:57
Hey, I faced the same issue. 
<img width="334" alt="screen shot 2017-07-12 at 11 53 54 am" src="https://user-images.githubusercontent.com/5603242/28109759-e01b8086-66f8-11e7-881d-a8eb1ed09941.png">

Yesterday it worked well until I run the following command for removing node_modules: `rm -rf node_modules` and then run `npm install`. 

I tried the steps for fixing in the error description, tried to run react-native-git-upgrade, even removed npm globally and then install again. I will glad for any help. Thanks.

**Comment by JonasLaux** [comment] 2017-07-18 17:30
Hi,
I also have the same issue.
My dependencies are only these ones:
`    
    "react": "16.0.0-alpha.12",
    "react-native": "0.46.4",
    "react-native-android-permissions": "1.0.0",
    "react-native-vector-icons": "^4.0.1"
`
i tried to remove the node_modules and cleaned my yarn and npm cache.

**Comment by Charles-LMQ** [comment] 2017-07-24 11:28
hi, the same problem in 
 "react": "16.0.0-alpha.12"
 "react-native": "0.46.4"

and solved it by downgrade to:

 "react": "16.0.0-alpha.6",
 "react-native": "0.44.0",

**Comment by EugeneBichel** [comment] 2017-07-24 11:38
Hi, @Charles-LMQ 
thank you for the answer. The set of "react": "16.0.0-alpha.6",
"react-native": "0.44.0" is working for me as well.

**Comment by oliviachang29** [comment] 2017-10-27 22:01
Downgrading to 0.44.0 and 16.0.0-alpha.6 worked for me as well.

**Comment by Johncy1997** [comment] 2018-03-07 11:07
![screenshot_2018-03-07-16-33-38](https://user-images.githubusercontent.com/25324938/37089117-88e87272-2225-11e8-93d5-a8dfdbc31a99.png)
Today I am facing this error..I want to use the Carousel from this package..I gave 
    npm i --save react-native-banner-carousel and react-native link..But the same error is repeating..

Please tell me someone what is the problem here..Thanks in advance

**Comment by karthiganesan90** [comment] 2018-03-07 13:51
@Johncy1997 Can you share your dependencies libs and RN version?

**Comment by Johncy1997** [comment] 2018-03-07 15:55
@karthiganesan90 Thanks for your reply.I am new to this language.now,i don't understand what your are asking me.
Luckily i resolved this by following these steps.
      1. Clear watchman watches: watchman watch-del-all.
      2.Delete the node_modules folder: rm -rf node_modules && npm install.
      3.Reset packager cache: rm -fr $TMPDIR/react-* or npm start -- --reset-cache."


package.json:
***************************
{
  "name": "ZGROO",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "native-base": "^2.3.9",
    "react": "16.2.0",
    "react-native": "0.53.3",
    "react-native-banner-carousel": "^1.0.2",
    "react-native-elements": "^0.19.0",
    "react-native-splash-screen": "^3.0.6",
    "react-native-swiper": "^1.5.13",
    "react-navigation": "^1.4.0",
    "react-redux": "^5.0.7",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0"
  },
  "devDependencies": {
    "babel-jest": "22.4.1",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.4.2",
    "react-test-renderer": "16.2.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by karthiganesan90** [comment] 2018-03-07 16:51
we can make it as one comment like `watchman watch-del-all && rm -rf node_modules/ && yarn cache clean && yarn install && yarn start -- --reset-cache`

Yes, I am trying to know about your project `package.json` dependencies and the React native lib version.
