### ISSUE TITLE
Flatlist not rendering item correctly when orientation changes.

### ISSUE THREAD

**Issue by hyochan** [facebook/react-native#19615] opened 2018-06-08 03:37 UTC
## Environment
 OS: macOS High Sierra 10.13.4
  Node: 10.2.1
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: 3.1 AI-173.4720617

## Packages
Packages: (wanted => installed)
  react: ^16.3.2 => 16.3.2
  react-native: ^0.55.4 => 0.55.4

In real device and emulator.

## Description

When I try to rotate screens, sometime UI crashes as shown in the [clip](https://firebasestorage.googleapis.com/v0/b/dooboolab-2f044.appspot.com/o/cooni%20strange%20orientation.mov?alt=media&token=5dbd2e2f-96fd-40cc-b47d-8bff8b793e61).

## Steps to Reproduce
Rotate, rotate.

## Expected Behavior
UI should not crash.

## Actual Behavior
UI crashes like in the [clip](https://firebasestorage.googleapis.com/v0/b/dooboolab-2f044.appspot.com/o/cooni%20strange%20orientation.mov?alt=media&token=5dbd2e2f-96fd-40cc-b47d-8bff8b793e61). You can [download](https://firebasestorage.googleapis.com/v0/b/dooboolab-2f044.appspot.com/o/cooni%20strange%20orientation.mov?alt=media&token=5dbd2e2f-96fd-40cc-b47d-8bff8b793e61).

--------------------
I've edited environment in my post but `react-native-bot` [here](https://github.com/facebook/react-native/issues/19561) won't get this away so I posted again.

**Comment by dooboolab** [comment] 2018-09-09 17:40
Still facing issue in 0.56

**Comment by dooboolab** [comment] 2018-12-09 09:12
This is still happening in `0.57` I need community for attention. There is some bug in orientation when ui is bit complex. Therefore I am using `RN` as `portrait` only.

**Comment by terrysahaidak** [comment] 2018-12-09 11:09
Hi @dooboolab, could you please create a reproducible example and post a link to github repo? I will help a lot.

**Comment by dooboolab** [comment] 2018-12-10 16:42
@terrysahaidak Ok I will. But it would take time for me because I need to move out of code from my production app. Thanks.

**Comment by dulmandakh** [comment] 2019-03-19 15:26
Hello there 👋 this issue has been reported for an old version of React Native. Ideally we'd like everyone to be using 0.59 (see the [awesome changes](https://facebook.github.io/react-native/blog/2019/03/12/releasing-react-native-059) it brought) but we know updating can be a pain. We are going to close this issue because it's from a version before 0.57, which is really old.

But please, if it's actually still an issue with 0.59 please comment below and we can reopen it. Even better, please send us a pull request with a fix 😊

**Closed by dulmandakh** 2019-03-19 15:26 UTC
Labels: Component: FlatList, Type: Bug Report
