### ISSUE TITLE
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libjscexecutor.so

### ISSUE THREAD

**Issue by sarmad6146324** [facebook/react-native#33495] opened 2022-03-25 07:50 UTC
### Description

App running in debug mode but after running this command 
npx react-native run-android --variant=release

App crashes immediately 

Error:
`E/HwDetectorWithState: a: 3
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.rnespclient, PID: 21704
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libjscexecutor.so
    	SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/com.rnespclient/lib-main flags = 1]
    	SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/~~w2nIgrLTQGqeN-xT7qolwQ==/com.rnespclient-txIJ5efndrtcV97wOdorlA==/lib/arm64 flags = 0]
    	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
    	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
    	Native lib dir: /data/app/~~w2nIgrLTQGqeN-xT7qolwQ==/com.rnespclient-txIJ5efndrtcV97wOdorlA==/lib/arm64
     result: 0
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1098)
        at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:914)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:826)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:773)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:743)
        at com.facebook.react.jscexecutor.JSCExecutor.loadLibrary(JSCExecutor.java:24)
        at com.facebook.react.jscexecutor.JSCExecutor.<clinit>(JSCExecutor.java:20)
        at com.facebook.react.jscexecutor.JSCExecutor.loadLibrary(Unknown Source:0)
        at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:352)
        at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:319)
        at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:95)
        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:42)
        at com.rnespclient.MainApplication.onCreate(MainApplication.java:55)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1242)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7220)
        at android.app.ActivityThread.access$1600(ActivityThread.java:265)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2169)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:257)
        at android.app.ActivityThread.main(ActivityThread.java:8220)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)`

### Version

0.67.4

### Output of `npx react-native info`

System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 32.05 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.3.0 - /usr/local/bin/npm
    Watchman: 2021.12.27.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 32.0.0
      System Images: android-29 | Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.3 => 0.67.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

npx react-native run-android --variant=release

**Comment by FadiAboMsalam** [comment] 2022-03-30 07:52
Same issue here did you manage to find a solution @sarmad6146324 ?

**Comment by FadiAboMsalam** [comment] 2022-03-30 09:00
i managed to fix it  using the following for my stage variant

`    deleteDebugFilesForVariant: {

        def variant -> variant.name.toLowerCase().contains("release") || variant.name.toLowerCase().contains("stage")

    }//0.67.4 fix stage release build
 `

**Comment by StevenGardnerGMJ** [comment] 2022-05-29 13:22
project.ext.react = [
    enableHermes: false,  // clean and rebuild if changing
    deleteDebugFilesForVariant: {
        def variant -> variant.name.toLowerCase().contains("release") || variant.name.toLowerCase().contains("stage")
    }//0.67.4 fix stage release build
]

**Comment by Yandamuri** [comment] 2022-07-08 12:14
> i managed to fix it using the following for my stage variant
> 
> ```
> 
>   deleteDebugFilesForVariant: {
> 
>         def variant -> variant.name.toLowerCase().contains("release") || variant.name.toLowerCase().contains("stage")
> 
>     }//0.67.4 fix stage release build
> ```

This solution didn't work for me

**Comment by jfaq89** [comment] 2022-08-24 20:10
I am also facing this problem after updating React Native to version 0.69.4.
I cannot reproduce it with my device but I do see it on Crashlytics.

**Comment by mrados7** [comment] 2022-09-13 12:09
@jfaq89 any solutions yet? For me it works only in debug mode. But when release is built I get that error.

**Comment by roots-ai** [comment] 2022-10-22 07:10
Any updates herE?

**Comment by Brittognanaraj** [comment] 2022-11-06 17:36
Any updates. Any one got a fix?

**Comment by swaroopaillinda** [comment] 2022-11-09 16:04
hi any solution for this issue i have done everything mentioned but its not working

**Comment by cortinico** [comment] 2023-01-19 10:36
This and all the "couldn't find DSO to load" bugs have been fixed in React Native 0.71.

The issue on previous versions was a "too aggressive" clean-up logic in the `react.gradle` file. In 0.71 the clean-up logic has been rewritten to be more Android friendly and is now living inside the React Native Gradle Plugin.

I'm closing this, please update to 0.71 and open a new issue if the "couldn't find DSO to load" crash is still happening on 0.71+.

**Closed by cortinico** 2023-01-19 10:36 UTC
Labels: Needs: Triage :mag:

**Comment by bozaigao** [comment] 2023-02-19 03:47
Run ./gradlew clean then build again

**Comment by dev9-rn** [comment] 2023-12-18 12:35
> I am also facing this problem after updating React Native to version 0.69.4. I cannot reproduce it with my device but I do see it on Crashlytics.

Have you found the solution?
