### ISSUE TITLE
Task :app:createBundleReleaseJsAndAssets FAILED

### ISSUE THREAD

**Issue by 98rahul** [facebook/react-native#36040] opened 2023-02-02 13:28 UTC
getting same error in order to get rid of https://github.com/facebook/react-native/issues/36014#issue-1564187093

as i am following this [article](https://www.waldo.com/blog/react-native-version-mismatch) and triggering bunch of errors
using this command
./gradlew clean build --refresh-dependencies --no-build-cache

New Version
0.71.1

Old Version
0.63.4

**Comment by cortinico** [comment] 2023-02-08 19:39
Closing as duplicate of https://github.com/facebook/react-native/issues/36014#issue-1564187093
Let's keep the conversation on a single issue

**Closed by cortinico** 2023-02-08 19:39 UTC
