### ISSUE TITLE
Vysor breaks react native apps. (Error Tried to get non-existent cookie @ TouchEventCoalescingKeyHelper.java:75)

### ISSUE THREAD

**Issue by MarcoPolo** [facebook/react-native#3678] opened 2015-10-26 04:36 UTC
[Vysor](http://www.vysor.io/) is a tool that mirrors your android on your computer. Similar to the ios simulator but with an actual backing device. (Also happens to be really useful for developing)

While this may be something that only affects Vysor, it may also be part of a bigger problem.

Using the app works fine, but as soon as you drag in vysor, the app crashes.

Repro:
New react-native project from scratch.
Open Vysor, and drag anywhere in the app.

[Full stack trace](https://gist.githubusercontent.com/MarcoPolo/ee7bb7cb4ee191d07fd7/raw/3c9d4e3703bc19ee633bb557ce6a38426aadf0e9/gistfile1.txt)

I can take a stab at it if you think it's part of a bigger issue and not Vysor specific.

**Comment by astreet** [comment] 2015-10-27 17:06
Interesting. This would be indicative of a move event being dispatched before a down event was dispatched (see the TouchEvent constructor where this is happening from). This isn't an error we've seen in production... does Vysor alter the touch events that are sent to the system?

**Comment by atom992** [comment] 2016-02-04 16:52
I have the same issue. env:
Samsung SCH-I959 (real devices)
Android 5.0.1
react native 0.17.0
Vysor Version: 1.0.6.4

**Comment by grabbou** [comment] 2016-04-25 16:27
Closing as duplicate of #5944 (actually that was duplicate of this one, but since it has more comments, better to keep debugging there)

**Closed by grabbou** 2016-04-25 16:27 UTC
Labels: Android

**Comment by remch1990** [comment] 2016-12-08 16:40
What is the solution to this problem?
RN: 0.33 Android
FATAL EXCEPTION: main
java.lang.RuntimeException: Tried to get non-existent cookie; no stack available (TouchEventCoalescingKeyHelper.java:75)

**Comment by yaxin3690** [comment] 2017-05-25 08:07
+1
