### ISSUE TITLE
Plugin paths in `.babelrc` should be relative to the project directory

### ISSUE THREAD

**Issue by steveluscher** [facebook/react-native#5864] opened 2016-02-10 22:38 UTC
I have a project that looks like this:

```
/
--> .babelrc
--> android/
--> ios/
--> scripts/
  --> somePlugin.js
--> index.js
--> package.json
```

The `.babelrc` looks like this:

```
{
  "presets: ["react-native"],
  "plugins": ["./scripts/somePlugin"]
}
```

I would expect that to find `somePlugin.js` but it doesn't. Changing the path to `../scripts/somePlugin` makes it work.

This means that paths are relative to `node_modules/` and not to the directory containing `.babelrc`, which was surprising to me.

**Comment by ide** [comment] 2016-02-10 23:28
cc @skevy. any idea if we can change babel's notion of cwd?

**Comment by skevy** [comment] 2016-02-10 23:31
Looking into it.

**Comment by skevy** [comment] 2016-02-11 00:25
@steveluscher @ide evidently this is just not how Babel works.

It resolves with a root of "node_modules"...relevant code is here: https://github.com/babel/babel/blob/master/packages/babel-core/src/helpers/resolve.js

**Comment by skevy** [comment] 2016-02-11 15:55
Turns out this is a bug in Babel related to how it uses some of Node's internals to do it's plugin resolution.

PR submitted here: https://github.com/babel/babel/pull/3350

**Comment by skevy** [comment] 2016-03-03 16:59
@steveluscher Fixed in Babel 6.6.4 by https://github.com/babel/babel/commit/f4197cc77b464f34c14085d0a0b4c67265432f54

**Comment by skevy** [comment] 2016-03-03 16:59
Just need to upgrade our babel deps now in RN.

**Closed by skevy** 2016-03-03 16:59 UTC

**Comment by janaka** [comment] 2016-08-29 12:24
Holding note for other while I confirm: the problem this fix intends to fix doesn't seem to be completely resolved. There appears to be a combination that results in behaviour that goes against what's documented and working for others. I'm seeing it with babelRelayPlugin setup for React Native + Relay. It cannot find the plugin path `Unknown plugin '../plugins/babelRelayPlugin' specified in 'foreign' at 0, attempted to resolve relative to '.'`

Logging message format https://github.com/babel/babel/blob/4c371132ae7321f6d08567eab54a59049e07f246/packages/babel-messages/src/index.js#L42

Error appear to be thrown from 
https://github.com/babel/babel/blob/v6.14.0/packages/babel-core/src/transformation/file/options/option-manager.js#L130

My runtime error stack trace says `option-manager.js line 172` which obviously doesn't match witht he above hence leading me to believe my code is actually loading a different version of babel-core that what package.json has.

Seems like the babel-core installed by react-native init is an old version or something along those lines. I think the React Native example TodoMVC works (not confirmed as there was some network related error most likely GraphQL server running on a diff port to the emulator proxy).

Trying to clear the npm cache. I'll update here as an when I find out more.

**Comment by akman003** [comment] 2016-10-28 17:25
@janaka any luck finding a better solution? I have a very similar problem in a react (non-native) project and it will only work when using an absolute path.

**Comment by janaka** [comment] 2016-11-13 16:33
@akman003 Added update4 above. My issue wasn't actually specific to Babel. It was simple the place I was seeing it at that point. It was an issue with Windows support.
