### ISSUE TITLE
MIT License update for React Software

### ISSUE THREAD

**Issue by edudemy** [facebook/react-native#16180] opened 2017-10-03 09:58 UTC
Isn't react-native software covered under the MIT License update? https://github.com/facebook/react/commit/b765fb25ebc6e53bb8de2496d2828d9d01c2774b

**Comment by kelset** [comment] 2017-10-03 10:18
No. And as far as I know they won't for the foreseeable future.
This is not a bug report or a feature request so I suggest you close it.

**Closed** 2017-10-03 13:35 UTC

**Comment by edudemy** [comment] 2017-10-08 10:33
Thanks for the clarification.

 Shall ask our community to stick with Vuejs and Weex. 
1. https://github.com/vuejs/vue/issues/2119
2. https://weex.incubator.apache.org/ 

Regards,

**Comment by gaearon** [comment] 2018-02-17 17:15
React Native (including Metro, Fresco, and Yoga) has also been relicensed as MIT.

https://github.com/facebook/react-native/commit/26684cf3adf4094eb6c405d345a75bf8c7c0bf88
