### ISSUE TITLE
Border is invisible when using borderStyle='dashed' with borderBottom

### ISSUE THREAD

**Issue by sesm** [facebook/react-native#7838] opened 2016-05-30 20:59 UTC
Border is invisible when using borderStyle='dashed' with borderBottom
Example: https://rnplay.org/apps/ESEkXQ
Environment: react-native 0.26, iOS

**Comment by kamek-pf** [comment] 2016-06-15 15:46
I'm experiencing this too (RN 0.27.2 here).
If `borderStyle` is set to anything other than `solid` (which is the default), then properties like `borderBottomWidth`, `borderTopWidth` etc. won't work, nothing is displayed.

Setting `borderWidth` does work though, you just don't get to specify a side.

**Comment by springwq** [comment] 2016-07-15 01:46
I have the same issue, too.
Environment: react-native 0.26.2, iOS

**Comment by rmevans9** [comment] 2016-08-12 17:04
Posted in #9343 originally but moving here since I closed the other as a duplicate of this ticket. This is currently expected behavior:

Based upon looking at the code this looks like a intentional limitation. There is code that specifically checks to see if both the color and width are the same on all sides if trying to use a dashed or dotted border. I would venture to guess that if you were to set borderWidth to 1 instead of just borderBottomWidth that the warning will go away and your border will show.

ref: https://github.com/facebook/react-native/blob/235b16d93287061a09c4624e612b5dc4f960ce47/React/Views/RCTBorderDrawing.m (line 382)

**Comment by rmevans9** [comment] 2016-08-12 17:05
@facebook-github-bot expected

**Comment by facebook-github-bot-2** [comment] 2016-08-12 17:05
The comment above tells me this is expected behavior. Closing this as we'd like to use the GitHub issue tracker for bugs. If you'd like to change how this feature works please post a feature request on [Product Pains](https://productpains.com/product/react-native/) so that other people can vote on it.

**Closed by facebook-github-bot-2** 2016-08-12 17:05 UTC
Labels: Ran Commands

**Comment by sdeleon28** [comment] 2017-04-02 07:37
I was able to achieve this effect by using this hack:

```javascript
const inputStyles = StyleSheet.create({
  container: {
    height: 20,
    marginRight: 25,
    marginLeft: 25,
    paddingTop: 25,
    paddingBottom: 25,
    borderStyle: 'dotted',
    borderWidth: 2,
    borderColor: '#b7c2c6',
    position: 'relative',
    overflow: 'hidden',
  },
  topMask: {
    height: 3,
    width: 9999,
    backgroundColor: 'white',
    position: 'absolute',
    top: -3,
    left: 0,
  },
  rightMask: {
    height: 9999,
    width: 3,
    backgroundColor: 'white',
    position: 'absolute',
    top: 0,
    right: -3,
  },
  leftMask: {
    height: 9999,
    width: 3,
    backgroundColor: 'white',
    position: 'absolute',
    top: 0,
    left: -3,
  },
});

const UnderlinedInput = props => (
  <View style={inputStyles.container}>
    <View style={inputStyles.topMask} />
    <View style={inputStyles.rightMask} />
    <View style={inputStyles.leftMask} />
    <TextInput {...props} />
  </View>
);
UnderlinedInput.propTypes = TextInput.propTypes;
```

**Comment by shams-in** [comment] 2018-04-10 17:39
@springwq

**Comment by shams-in** [comment] 2018-04-10 17:40
Testing is always a **better** option

`container: {
    height: 20,
    marginRight: 25,
    marginLeft: 25,
    paddingTop: 25,
    paddingBottom: 25,
    borderStyle: 'dotted',
    borderWidth: 2,
    borderColor: '#b7c2c6',
    position: 'relative',
    overflow: 'hidden',
  }`

**Comment by shams-in** [comment] 2018-04-10 17:41
[this is a link](https://rnplay.org/apps/ESEkXQ)
