### ISSUE TITLE
onResponderRelease does not work on android devices

### ISSUE THREAD

**Issue by 12d** [facebook/react-native#8178] opened 2016-06-17 07:18 UTC
Exactly speaking, 
onResponderRelease is not triggered on Android if it nested with Text, but works well with IOS devices. Here is my quite simple code: 
```
render (){
        return (
            <Text>
            <Image onResponderRelease={()=>{alert(1)}} onStartShouldSetResponder={()=>true} source={{height: 100, width: 100, uri: 'http://dimg04.c-ctrip.com/images//u00l0400000000dq8C668.jpg'}}/>
            </Text>
        )
}
```

**Comment by charpeni** [comment] 2016-06-17 13:55
@facebook-github-bot duplicate #8177

**Comment by facebook-github-bot-9** [comment] 2016-06-17 13:56
@charpeni tells me this issue is a duplicate of #8177. Let's discuss there, closing this one.

**Closed by facebook-github-bot-9** 2016-06-17 13:56 UTC
Labels: Ran Commands
