### ISSUE TITLE
RCTView: Shadow warnings with transparent backgrounds

### ISSUE THREAD

**Issue by a-koka** [facebook/react-native#11910] opened 2017-01-14 16:15 UTC
### Description
RCTView throws warnings when trying to set shadows on components with transparent backgrounds.

### Reproduction
Assign the following style to any Component.

```
const styles = StyleSheet.create({
  shadowWithWarning: {
    backgroundColor: 'transparent',
    shadowColor: '#555',
    shadowOpacity: 0.5,
    shadowRadius: 2,
    shadowOffset: {
      height: 2,
      width: 1
    }
  }
```

### Solution
Although `RCTView` complains about not being able to calculate the shadow efficiently, the shadows render just fine. Would be great to be able to suppress this warning.

### Additional Information

* React Native version: 0.39.2
* Platform: iOS
* Operating System: MacOS

**Comment by prithsharma** [comment] 2017-05-22 13:12
I am also facing the same warning for `backgroundColor` as `transparent` - in fact, for `backgroundColor` with any opacity other than 1(using rgba).
While [this commit](https://github.com/facebook/react-native/commit/e4c53c28aea7e067e48f5c8c0100c7cafc031b06) explains the reason for the warning, but says nothing about a solution for using transparent backgrounds in a performant way other than not using transparent backgrounds.

For people who don't have enough native iOS knowledge, can someone please clarify if using transparent backgrounds on iOS is actually non-performant and should be avoided or this is a limitation of the current RN implementation of shadows(and would be fixed in a later version)?

**Comment by hramos** [comment] 2017-07-26 05:45
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Closed by hramos** 2017-07-26 05:45 UTC
Labels: Icebox

**Comment by Adamnator92** [comment] 2017-08-02 09:21
@prithsharma the warning gone after i apply `shadowOpacity: 0`

**Comment by himelnagrana** [comment] 2017-11-09 12:48
@prithsharma  @Adamnator92 
in my case it solved by putting:
`shadowOpacity: 0.9`

The look is almost same but removes the warning.
