### ISSUE TITLE
android build apk error on master

### ISSUE THREAD

**Issue by nowaits** [facebook/react-native#5304] opened 2016-01-14 10:00 UTC
01-14 17:58:43.349 27580-27635/com.mmww.erxi W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.image.ReactImageManager
01-14 17:58:43.439 27580-27635/com.mmww.erxi W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
01-14 17:58:43.439 27580-27635/com.mmww.erxi W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
01-14 17:58:43.439 27580-27635/com.mmww.erxi W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
01-14 17:58:43.439 27580-27635/com.mmww.erxi W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextShadowNode
01-14 17:58:43.439 27580-27635/com.mmww.erxi W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.recyclerview.RecyclerViewBackedScrollViewManager
01-14 17:58:43.469 27580-27635/com.mmww.erxi W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
01-14 17:58:43.469 27580-27635/com.mmww.erxi W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
01-14 17:58:43.469 27580-27635/com.mmww.erxi W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
01-14 17:58:43.469 27580-27635/com.mmww.erxi W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputManager
01-14 17:58:43.479 27580-27635/com.mmww.erxi W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
01-14 17:58:43.479 27580-27635/com.mmww.erxi W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextViewManager
01-14 17:58:43.489 27580-27635/com.mmww.erxi W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.toolbar.ReactToolbarManager
01-14 17:58:43.489 27580-27635/com.mmww.erxi W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
01-14 17:58:43.499 27580-27635/com.mmww.erxi W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.viewpager.ReactViewPagerManager
01-14 17:58:43.499 27580-27635/com.mmww.erxi W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextInlineImageViewManager
01-14 17:58:43.499 27580-27635/com.mmww.erxi W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextInlineImageShadowNode
01-14 17:58:43.509 27580-27635/com.mmww.erxi W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
01-14 17:58:43.509 27580-27635/com.mmww.erxi W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
01-14 17:58:43.519 27580-27635/com.mmww.erxi W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.webview.ReactWebViewManager

**Comment by skevy** [comment] 2016-01-14 20:00
Can you help us understand how to reproduce this issue, and what steps you've already taken to resolve it?

**Comment by nowaits** [comment] 2016-01-15 02:20
i set minifyEnabled in gradle file on release build mode.

**Comment by nowaits** [comment] 2016-01-15 02:21
i set minifyEnabled true in gradle file on release build mode.

**Comment by nowaits** [comment] 2016-01-15 02:38
i set minifyEnabled in gradle file on release build type



发自我的小米手机在 Adam Miskiewicz <notifications@github.com>，2016年1月15日 上午4:02写道：Can you help us understand how to reproduce this issue, and what steps you've already taken to resolve it?

**Comment by cosmith** [comment] 2016-02-01 11:29
I have the same issue after upgrading to RN 0.19 on Android. Changing the value of `minifyEnabled` doesn't seem to have any effect... Has there been a change to the way UI components are defined?

My native modules other than the Google Maps one still work well... not sure why this one doesn't, but it's the only one that defines a UI component.

The `@ReactProp` annotated setters are not called, but events are being sent from native to JS.

Example method: 
```java
    @SuppressWarnings("unused")
    @ReactProp(name = "cameraPosition")
    public void setCameraPosition(GoogleMapView view, ReadableMap options) {
        Log.d(REACT_CLASS, "cameraPosition set");
        view.setCameraPosition(options);
    }
```

Logs:
```
02-01 12:11:49.663 17243-17293/com.truckfly.truckfly W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTRenderableViewManager
02-01 12:11:49.665 17243-17293/com.truckfly.truckfly W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupShadowNode
02-01 12:11:49.668 17243-17293/com.truckfly.truckfly W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeShadowNode
02-01 12:11:49.672 17243-17293/com.truckfly.truckfly W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextShadowNode
02-01 12:11:49.674 17243-17293/com.truckfly.truckfly W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewManager
02-01 12:11:49.680 17243-17293/com.truckfly.truckfly W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewShadowNode
02-01 12:11:49.688 17243-17293/com.truckfly.truckfly W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDialogPickerManager
02-01 12:11:49.691 17243-17293/com.truckfly.truckfly W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode
02-01 12:11:49.692 17243-17293/com.truckfly.truckfly W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
02-01 12:11:49.696 17243-17293/com.truckfly.truckfly W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDropdownPickerManager
02-01 12:11:49.697 17243-17293/com.truckfly.truckfly W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
02-01 12:11:49.699 17243-17293/com.truckfly.truckfly W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.image.ReactImageManager
02-01 12:11:49.704 17243-17293/com.truckfly.truckfly W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
02-01 12:11:49.707 17243-17293/com.truckfly.truckfly W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
02-01 12:11:49.709 17243-17293/com.truckfly.truckfly W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
02-01 12:11:49.711 17243-17293/com.truckfly.truckfly W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextShadowNode
02-01 12:11:49.716 17243-17293/com.truckfly.truckfly W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
02-01 12:11:49.718 17243-17293/com.truckfly.truckfly W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
02-01 12:11:49.720 17243-17293/com.truckfly.truckfly W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
02-01 12:11:49.721 17243-17293/com.truckfly.truckfly W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextInlineImageViewManager
02-01 12:11:49.722 17243-17293/com.truckfly.truckfly W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextInlineImageShadowNode
02-01 12:11:49.725 17243-17293/com.truckfly.truckfly W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputManager
02-01 12:11:49.730 17243-17293/com.truckfly.truckfly W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
02-01 12:11:49.732 17243-17293/com.truckfly.truckfly W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextViewManager
02-01 12:11:49.732 17243-17293/com.truckfly.truckfly W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.toolbar.ReactToolbarManager
02-01 12:11:49.737 17243-17293/com.truckfly.truckfly W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
02-01 12:11:49.742 17243-17293/com.truckfly.truckfly W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.viewpager.ReactViewPagerManager
02-01 12:11:49.744 17243-17293/com.truckfly.truckfly W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
02-01 12:11:49.745 17243-17293/com.truckfly.truckfly W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.webview.ReactWebViewManager
02-01 12:11:49.747 17243-17293/com.truckfly.truckfly W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.recyclerview.RecyclerViewBackedScrollViewManager
02-01 12:11:49.755 17243-17293/com.truckfly.truckfly W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
02-01 12:11:49.764 17243-17293/com.truckfly.truckfly W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.truckfly.rctgooglemaps.GoogleMapViewManager
```

**Comment by artem-russkikh** [comment] 2016-02-01 20:55
I upgrade react-native to 0.19.0
Development mode works fine. When I make a release build - app is crashing. Commenting `minifyEnabled` in andorid/app/build.gradle makes build working

**Comment by kristjanmik** [comment] 2016-02-01 21:06
Same for me, the minify process breaks the prod build

**Comment by cosmith** [comment] 2016-02-02 08:57
So I guess this commit has something to do with it? https://github.com/facebook/react-native/commit/57f6cbb3dc12d2dcc3eedd9712c36bb3d39149a5

It says `The annotation processor is currently not working when building with Gradle.`

@lexs could you take a look?

**Comment by lexs** [comment] 2016-02-02 12:12
Hey!

The error you're seeing is because the annotation processor is not ran on Gradle builds (as it's not yet supported there), however this means that it will just fall back to the old reflection-based approach.

Do you have a log of the actual crash with stack trace?

**Comment by cosmith** [comment] 2016-02-02 13:16
I don't have any crashes so it's hard to pinpoint the issue, but my custom UI component does not receive calls from the javascript side. It might be a completely separate issue from what the others are experiencing with the crashes...

**Comment by lexs** [comment] 2016-02-02 13:52
@cosmith Is it possible for you to test a version where 57f6cbb3dc12d2dcc3eedd9712c36bb3d39149a5 is reverted? Otherwise is it possible to make a minimal test case that I could dig into?

**Comment by kristjanmik** [comment] 2016-02-02 19:36
It crashes on the generated default project from the cli. Here is a dump:

````
02-02 11:34:57.216  6657  6670 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTRenderableViewManager
02-02 11:34:57.218  6657  6670 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupShadowNode
02-02 11:34:57.219  6657  6670 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeShadowNode
02-02 11:34:57.220  6657  6670 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextShadowNode
02-02 11:34:57.221  6657  6670 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewManager
02-02 11:34:57.222  6657  6670 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewShadowNode
02-02 11:34:57.222  6657  6670 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDialogPickerManager
02-02 11:34:57.223  6657  6670 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode
02-02 11:34:57.224  6657  6670 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
02-02 11:34:57.228  6657  6670 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDropdownPickerManager
02-02 11:34:57.229  6657  6670 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
02-02 11:34:57.232  6657  6670 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.image.ReactImageManager
02-02 11:34:57.235  6657  6670 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
02-02 11:34:57.237  6657  6670 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
02-02 11:34:57.238  6657  6670 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
02-02 11:34:57.240  6657  6670 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextShadowNode
02-02 11:34:57.242  6657  6670 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
02-02 11:34:57.243  6657  6670 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
02-02 11:34:57.246  6657  6670 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
02-02 11:34:57.246  6657  6670 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextInlineImageViewManager
02-02 11:34:57.249  6657  6670 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextInlineImageShadowNode
02-02 11:34:57.250  6657  6670 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputManager
02-02 11:34:57.251  6657  6670 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
02-02 11:34:57.252  6657  6670 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextViewManager
02-02 11:34:57.253  6657  6670 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.toolbar.ReactToolbarManager
02-02 11:34:57.257  6657  6670 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
02-02 11:34:57.259  6657  6670 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.viewpager.ReactViewPagerManager
02-02 11:34:57.260  6657  6670 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
02-02 11:34:57.261  6657  6670 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.webview.ReactWebViewManager
02-02 11:34:57.261  6657  6670 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.recyclerview.RecyclerViewBackedScrollViewManager
02-02 11:34:57.262  6657  6657 W unknown:React: Unable to dispatch keyboard events in JS as the react instance has not been attached
02-02 11:34:57.265  6657  6670 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
02-02 11:34:57.278  5159  5205 I ActivityManager: Displayed com.awesomeproject/.MainActivity: +180ms
02-02 11:34:57.482  6657  6672 E ReactNativeJS: undefined is not an object (evaluating 'h.propTypes.style')
02-02 11:34:57.492  6657  6673 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
02-02 11:34:57.492  6657  6673 E AndroidRuntime: Process: com.awesomeproject, PID: 6657
02-02 11:34:57.492  6657  6673 E AndroidRuntime: com.facebook.react.modules.core.JavascriptException: <unknown>
02-02 11:34:57.492  6657  6673 E AndroidRuntime:     index.android.bundle:15:9209
02-02 11:34:57.492  6657  6673 E AndroidRuntime: r
02-02 11:34:57.492  6657  6673 E AndroidRuntime:     index.android.bundle:1:575
02-02 11:34:57.492  6657  6673 E AndroidRuntime: n
02-02 11:34:57.492  6657  6673 E AndroidRuntime:     index.android.bundle:1:241
02-02 11:34:57.492  6657  6673 E AndroidRuntime: <unknown>
02-02 11:34:57.492  6657  6673 E AndroidRuntime:     index.android.bundle:16:29346
02-02 11:34:57.492  6657  6673 E AndroidRuntime: r
02-02 11:34:57.492  6657  6673 E AndroidRuntime:     index.android.bundle:1:575
02-02 11:34:57.492  6657  6673 E AndroidRuntime: n
02-02 11:34:57.492  6657  6673 E AndroidRuntime:     index.android.bundle:1:241
02-02 11:34:57.492  6657  6673 E AndroidRuntime: <unknown>
02-02 11:34:57.492  6657  6673 E AndroidRuntime:     index.android.bundle:16:26956
02-02 11:34:57.492  6657  6673 E AndroidRuntime: r
02-02 11:34:57.492  6657  6673 E AndroidRuntime:     index.android.bundle:1:575
02-02 11:34:57.492  6657  6673 E AndroidRuntime: n
02-02 11:34:57.492  6657  6673 E AndroidRuntime:     index.android.bundle:1:241
02-02 11:34:57.492  6657  6673 E AndroidRuntime: <unknown>
02-02 11:34:57.492  6657  6673 E AndroidRuntime:     index.android.bundle:16:20170
02-02 11:34:57.492  6657  6673 E AndroidRuntime: r
02-02 11:34:57.492  6657  6673 E AndroidRuntime:     index.android.bundle:1:575
02-02 11:34:57.492  6657  6673 E AndroidRuntime: n
02-02 11:34:57.492  6657  6673 E AndroidRuntime:     index.android.bundle:1:241
02-02 11:34:57.492  6657  6673 E AndroidRuntime: <unknown>
02-02 11:34:57.492  6657  6673 E AndroidRuntime:     index.android.bundle:16:18534
02-02 11:34:57.492  6657  6673 E AndroidRuntime: r
02-02 11:34:57.492  6657  6673 E AndroidRuntime:     index.android.bundle:1:575
02-02 11:34:57.492  6657  6673 E AndroidRuntime: n
02-02 11:34:57.492  6657  6673 E AndroidRuntime:     index.android.bundle:1:241
02-02 11:34:57.492  6657  6673 E AndroidRuntime: <unknown>
02-02 11:34:57.492  6657  6673 E AndroidRuntime:     index.android.bundle:16:17342
02-02 11:34:57.492  6657  6673 E AndroidRuntime: r
02-02 11:34:57.492  6657  6673 E AndroidRuntime:     index.android.bundle:1:575
02-02 11:34:57.492  6657  6673 E AndroidRuntime: n
02-02 11:34:57.492  6657  6673 E AndroidRuntime:     index.android.bundle:1:241
02-02 11:34:57.492  6657  6673 E AndroidRuntime: AppRegistry
02-02 11:34:57.492  6657  6673 E AndroidRuntime:     index.android.bundle:1:27541
02-02 11:34:57.492  6657  6673 E AndroidRuntime: <unknown>
02-02 11:34:57.492  6657  6673 E AndroidRuntime:     index.android.bundle:1:12592
02-02 11:34:57.492  6657  6673 E AndroidRuntime: r
02-02 11:34:57.492  6657  6673 E AndroidRuntime:     index.android.bundle:1:575
02-02 11:34:57.492  6657  6673 E AndroidRuntime: r
02-02 11:34:57.492  6657  6673 E AndroidRuntime:     index.android.bundle:1:304
02-02 11:34:57.492  6657  6673 E AndroidRuntime: n
02-02 11:34:57.492  6657  6673 E AndroidRuntime:     index.android.bundle:1:241
02-02 11:34:57.492  6657  6673 E AndroidRuntime: <unknown>
02-02 11:34:57.492  6657  6673 E AndroidRuntime:     global code@index.android.bundle:17:26446
02-02 11:34:57.492  6657  6673 E AndroidRuntime:
02-02 11:34:57.492  6657  6673 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:68)
02-02 11:34:57.492  6657  6673 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:56)
02-02 11:34:57.492  6657  6673 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-02 11:34:57.492  6657  6673 E AndroidRuntime: 	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:249)
02-02 11:34:57.492  6657  6673 E AndroidRuntime: 	at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:158)
02-02 11:34:57.492  6657  6673 E AndroidRuntime: 	at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:58)
02-02 11:34:57.492  6657  6673 E AndroidRuntime: 	at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.call(CatalystInstanceImpl.java:431)
02-02 11:34:57.492  6657  6673 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnableDeprecated.run(Native Method)
02-02 11:34:57.492  6657  6673 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
02-02 11:34:57.492  6657  6673 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-02 11:34:57.492  6657  6673 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
02-02 11:34:57.492  6657  6673 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
02-02 11:34:57.492  6657  6673 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:185)
02-02 11:34:57.492  6657  6673 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
02-02 11:34:57.494  5159 10900 W ActivityManager:   Force finishing activity com.awesomeproject/.MainActivity
02-02 11:34:57.527  5159  5186 W BroadcastQueue: Skipping deliver [background] BroadcastRecord{5599fc6 u-1 android.net.conn.CONNECTIVITY_CHANGE} to ReceiverList{eb04608 6657 com.awesomeproject/10114/u0 remote:4149fab}: process crashing
02-02 11:34:57.531  6657  6672 E ReactNativeJS: Module AppRegistry is not a registered callable module.

**Comment by calflegal** [comment] 2016-02-02 20:02
Yes I can confirm this happens on a fresh project from the cli tool. My native modules are not working on 0.19.0

**Comment by kristjanmik** [comment] 2016-02-04 22:01
We have a good discussion going on in #5655

**Comment by arunabha** [comment] 2016-02-13 10:15
I too am having a similar issue, the app starts fine, but none of the calls from javascript to set properties for native components seems to be taking effect. I've confirmed this by adding a log statement to a method annotated with '@ReactProp'. The log statement never gets triggered when the corresponding property is set in Javascript.

**Comment by cosmith** [comment] 2016-02-13 10:42
@arunabha the import changed for @ReactProp, you now have to import  `com.facebook.react.uimanager.annotations.ReactProp;` in RN 0.19+

**Comment by arunabha** [comment] 2016-02-13 11:49
@cosmith Yes, I just realized that reading https://github.com/facebook/react-native/issues/5649

The fix is fairly easy, but it sort of forces a dependency on 0.19 so all users of the library will have to upgrade. Is there a way of supporting both 0.19 and < 0.19 ?

**Comment by yipengmu** [comment] 2016-02-17 11:23
see the https://github.com/janicduplessis/react-native/blob/f95915fa1adfb601d34a98e003027df4ff8ca6d3/local-cli/generator-android/templates/src/app/proguard-rules.pro ,help me solve this issue

**Comment by mkonicek** [comment] 2016-02-21 18:36
Looks like this has been fixed in #5304 and answered here, closing. Sorry about the breakage.

**Closed by mkonicek** 2016-02-21 18:36 UTC
Labels: Android, Needs more information

**Comment by patsimon** [comment] 2017-01-16 11:50
I'm currently using 0.40 and am getting the above document issue.

**Comment by Wirg** [comment] 2017-01-19 01:10
Same than Patsimon, I ran into that issue when running on react-native 0.40 .

I tried a few of the bug solutions but nothing really worked.

``` 14942-16141/com.company.project W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
 14942-16141/com.company.project W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.viewpager.ReactViewPagerManager
 14942-16141/com.company.project W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
 14942-16141/com.company.project W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.webview.ReactWebViewManager
 14942-16141/com.company.project W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.recyclerview.RecyclerViewBackedScrollViewManager
 14942-16141/com.company.project W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
 14942-16145/com.company.project E/ReactNativeJS: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner}).
 14942-16147/com.company.project E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                                                                  Process: com.company.project, PID: 14942
                                                                  com.facebook.react.common.JavascriptException: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner})., stack:
```

This only shows on the android project, the ios one works.
So I have got a bunch of those `unknown:ViewManagerPropertyUpdater: Could not find generated setter for class`, then I have an error stating `Objects are not valid as a React child`.
Checking those 2 messages, the 2nd one means that I have an issue with my React (render probably ?), but as the iOS part is working, I guess that the error might be due to the previous warnings (maybe ?).


Has anyone else experienced that and have an idea/solution ?

**Comment by booboothefool** [comment] 2017-01-20 08:46
Getting this on 0.37.

**Comment by vdesdoigts** [comment] 2017-01-23 14:34
Same on RN 0.40

**Comment by Wirg** [comment] 2017-01-23 20:13
@booboothefool : is this something really specific to you or would you mind sharing what you did/had ?

**Comment by edmundito** [comment] 2017-02-02 18:21
@Wirg I've experienced the same `Objects are not valid as React child` issue during my upgrade from 0.37 to 0.39. This happens in the Android emulation or the build. When I turn on debug mode it runs normally. I am still looking into what the cause is, but there are not a lot of answers online. Please let me know if you find a solution.

**Comment by MintyOwl** [comment] 2017-02-07 18:53
Yes, I am on 0.41 right now, trying to pull string values from java into my javascript side. Debugging it successfully shows the string however I see big red error message on emulator saying

> Objects are not valid as a React child (found: object with keys {_45, _81, _65, _54}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `View`.

I cannot get passed through this.

**Comment by patsimon** [comment] 2017-02-19 00:07
I have a found a solution to the problem of finding a mobile cross platform native open source framework that is stable - Nativescript :)

**Comment by tomasdelima** [comment] 2017-04-25 00:31
I had the same issue, and found out the problem: in my JS files I was using `performance.now()`. As soon as I replaced it for `new Date()`, I managed to get my code working in the release version
