### ISSUE TITLE
[iOS] "Could not locate shadow view with tag" problem

### ISSUE THREAD

**Issue by zhangjiuzhou** [facebook/react-native#17906] opened 2018-02-08 09:52 UTC
Our react-native version is 0.46.2. When using several **TextInput** components in one screen, app may crash for reason "Could not locate shadow view with tag" in **iOS**.

I try a newer version 0.51, it will not crash, but print some log for the same reason.

Another issue describes the same problem (https://github.com/facebook/react-native/issues/7977), but lack of reproduce.

I write a DEMO, render for 500 times in a short time, then  reproduce this problem. Here is my code.

```
import React, { Component } from 'react';
import {
  AppRegistry,
  View,
  TextInput,
  AsyncStorage,
  ActivityIndicator
} from 'react-native';

export default class testrn extends Component {
  state = {
    loading: false
  }

  componentWillMount () {
    for (let i = 0; i < 500; ++i) {
      setTimeout(() => {
        this.setState({loading: true})
        AsyncStorage.getItem('foo', () => {
          setTimeout(() => {
            this.setState({loading: false})
          }, 100)
        })
      }, 100 * i)
    }
  }

  render() {
    if (this.state.loading) {
      return <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
        <ActivityIndicator />
      </View>
    }

    return (
      <View style={{flex: 1, paddingTop: 64}}>
        <TextInput style={{width: 200, height: 35, borderWidth: 1}} />
        <TextInput style={{width: 200, height: 35, borderWidth: 1}} />
        <TextInput style={{width: 200, height: 35, borderWidth: 1}} />
        <TextInput style={{width: 200, height: 35, borderWidth: 1}} />
        <TextInput style={{width: 200, height: 35, borderWidth: 1}} />
        <TextInput style={{width: 200, height: 35, borderWidth: 1}} />
        <TextInput style={{width: 200, height: 35, borderWidth: 1}} />
        <TextInput style={{width: 200, height: 35, borderWidth: 1}} />
        <TextInput style={{width: 200, height: 35, borderWidth: 1}} />
        <TextInput style={{width: 200, height: 35, borderWidth: 1}} />
        <TextInput style={{width: 200, height: 35, borderWidth: 1}} />
        <TextInput style={{width: 200, height: 35, borderWidth: 1}} />
        <TextInput style={{width: 200, height: 35, borderWidth: 1}} />
        <TextInput style={{width: 200, height: 35, borderWidth: 1}} />
        <TextInput style={{width: 200, height: 35, borderWidth: 1}} />
        <TextInput style={{width: 200, height: 35, borderWidth: 1}} />
        <TextInput style={{width: 200, height: 35, borderWidth: 1}} />
      </View>
    );
  }
}

AppRegistry.registerComponent('testrn', () => testrn);
```

**Comment by hramos** [comment] 2018-02-09 20:41
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue that meets the requirements set forth in the template. Thanks!

**Closed by hramos** 2018-02-09 20:41 UTC
Labels: Failed Commands
