### ISSUE TITLE
webView Encountered an error loading page canGoForward: false, code: -1, canGoBack: false, description: "net::ERR_ACCESS_DENIED", loading: false, …}

### ISSUE THREAD

**Issue by mohamed-sultan** [facebook/react-native#21104] opened 2018-09-13 22:29 UTC
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
      CPU: x64 Intel(R) Core(TM) i5 CPU       M 460  @ 2.53GHz
      Memory: 122.76 MB / 5.62 GB
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 8.10.0 - /usr/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 3.5.2 - /usr/bin/npm
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.1 => 0.56.1
    npmGlobalPackages:
      react-native-cli: 2.0.1

dependencies:
axios": "^0.18.0",
    "react": "16.4.1",
    "react-native": "0.56.1",
    "react-native-file-viewer": "^1.0.5",
    "react-native-fs": "^2.11.15",
    "react-native-image-placeholder": "^1.0.14",
    "react-native-vector-icons": "^5.0.0",
    "react-native-zip-archive": "^2.2.6",
    "rn-fetch-blob": "^0.10.13"
  }

## Description
failed to load internal  html file from android emulator In WebView 
## Reproducible Demo
here is my source code 
  <WebView 
            
              style={{width:'100%',height:'100%'}}
              source={{ uri: `file://${RNFS.DocumentDirectoryPath}/fake/Elements/index.html`}}
    />

**Comment by maxammann** [comment] 2018-09-17 10:38
I'm experiencing a similar problem when trying to show an image:
```
                  <WebView
                    source={{
                      baseUrl: RNFetchblob.fs.dirs.DocumentDir,
                      // html: '<html><body><a href="file:///data/user/0/com.app/files/red.png">asdf</a></body></html>'
                    }}
                    allowFileAccess={true}
                    scalesPageToFit={true}
                    originWhitelist={['*']}
                  />
```

**Comment by maxammann** [comment] 2018-09-17 10:44
This probably belongs to https://github.com/react-native-community/react-native-webview/issues now.

**Comment by maxammann** [comment] 2018-09-17 14:42
The reason is that this commit is missing in react native 0.57.0.

**Comment by Titozzz** [comment] 2018-09-26 22:06
Closing here. If the issue is still present on the new repository please open an issue there as @maxammann said :heart:

**Closed by Titozzz** 2018-09-26 22:06 UTC
Labels: :large_orange_diamond:Components, :large_orange_diamond:WebView, :rewind:Old Version, :small_blue_diamond:Linux

**Comment by hvlong** [comment] 2018-10-17 10:33
I load webview from folder file:///data/data/package-name/abc.html
And I got the same error.
I spend on 3 days to research it, But I don't know any solution.
"react-native": "0.57.1",

Plz help me check it.

**Comment by zhllucky** [comment] 2018-11-15 13:14
@react-native-bot  I have the same question in 0.57.3

**Comment by mnoandh** [comment] 2018-12-06 15:52
it happened to me also in android only when I use WebView from react-native  .. but when I use WebView  from  react-native-webview I get another error for both ios and android !  is there any solution! 



OS: Windows 7
Node: 8.11.1
Yarn: 1.9.4
npm: 6.2.0
 "dependencies": {
    "axios": "^0.16.2",
    "expo": "^25.0.0",
    "html-entities": "^1.2.1",
    "moment": "^2.18.1",
    "native-base": "^2.8.1",
    "prop-types": "^15.6.0",
    "react": "16.2.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz",
    "react-native-htmlview": "^0.13.0",
    "react-native-render-html": "^3.10.0",
    "react-native-video": "^3.2.1",
    "react-native-webview": "^2.14.0",
    "react-navigation": "^1.0.0-beta.27",
    "react-redux": "^5.0.5",
    "redux": "^3.7.2",
    "redux-persist": "^4.8.2",
    "redux-thunk": "^2.2.0",
    "sanitize-html": "1.15.0"
  },

![1079339668](https://user-images.githubusercontent.com/44123373/49594823-a5bdb100-f9b1-11e8-90eb-2d53e3307a8c.jpg)
![1419591602](https://user-images.githubusercontent.com/44123373/49594911-d6054f80-f9b1-11e8-833d-3a0649586f30.jpg)

**Comment by maxammann** [comment] 2018-12-06 18:12
@mnoandh Please open an issue in the react-native-webview github repo. Also add a code example.
