### ISSUE TITLE
React-Native Webview auto Height not working 

### ISSUE THREAD

**Issue by samridhgupta** [facebook/react-native#15532] opened 2017-08-17 09:31 UTC
I m using a Webview for rendering some content to a view, to calculate the height of the content I m using a script to get the height of the content, the span tag contains the content.

    const commonHtml =<html id="htmlContent">
    <body>
        <span>
        ...
        //content
        ...
        </span>
        <script>
            document.addEventListener('DOMContentLoaded', function () {
                document.title = document.getElementById('htmlContent').offsetHeight;
                window.location.hash = 1;
            });
        </script>
    </body>
    </html>

And here is the webview component : 

    const commonHtmlStyle= `font-weight:300; font-family:sans-serif; font-size: 18px; color:rgb(136,136,136); backgroundColor:rgba(0,0,0,0);`;

    <WebView style={{ height:  this.state.height }}
        ref={(ref) => { this.webview = ref; }}
        automaticallyAdjustContentInsets={true}
        scrollEnabled={false}
        javaScriptEnabled={true}
        source={{ html: commonHtml }}
        onNavigationStateChange={this.setState({
            height: parseInt(navState.title) 
        })}
    />  

                     

So results, 
i m seeing blank spaces while running in Android (script returns appox double the height)
and clipped content on iOS (returns height less than the content height).

I tried using other autoHeight webview components like ([react-native-webview-autoheight][1]) but still shows nearly same results for both iOS and Android.

I m trying wrap my head around this issue but but not able to solve this any how. Any help would be appreciated.

  [1]: https://www.npmjs.com/package/react-native-webview-autoheight

**Comment by hramos** [comment] 2017-08-17 13:17
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-08-17 13:17 UTC

**Comment by iou90** [comment] 2017-09-01 08:48
try this: https://github.com/iou90/react-native-autoheight-webview

**Comment by cinder92** [comment] 2017-11-27 21:38
same issue here, only works on iOs but no Android :/

**Comment by el-lsan** [comment] 2018-03-20 15:39
@samridhgupta Did you manage to solve this issue ?
