### ISSUE TITLE
0.61.1 Android set borderRadius have no effect

### ISSUE THREAD

**Issue by aijason** [facebook/react-native#26676] opened 2019-10-01 11:02 UTC
"react": "16.9.0",
"react-native": "0.61.1",
in IOS ok, in Android no effect

<View style={{
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 5,
    backgroundColor: 'red'
  }}>
  <Text style={{fontSize: 14, color: 'white'}}>
Test
</Text>
</View>

**Comment by aijason** [comment] 2019-10-01 11:05
"react": "16.9.0",
"react-native": "0.61.1",
in IOS ok, in Android no effect

<View style={{
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 5,
    backgroundColor: 'red'
  }}>
  <Text style={{fontSize: 14, color: 'white'}}>
Test
</Text>
</View>

**Comment by andvm** [comment] 2019-10-01 11:06
[https://github.com/facebook/react-native/issues/26627](url)

**Comment by radko93** [comment] 2019-10-01 12:22
Duplicate of #26627

**Closed by radko93** 2019-10-01 12:22 UTC
Labels: Bug, Platform: Android, Ran Commands, Resolution: Needs More Information

**Comment by aflahkp** [comment] 2019-10-05 12:06
but #26627 is not fixed yet
