### ISSUE TITLE
[Android] random error with Web Socket

### ISSUE THREAD

**Issue by PierBover** [facebook/react-native#8687] opened 2016-07-11 09:32 UTC
I'm using Firebase 0.3.1 with RN 0.29.0.

I'm getting this error randomly using logcat:

```
07-11 04:27:55.469 18176 18633 E unknown:React: Could not close WebSocket connection for id 0
07-11 04:27:55.469 18176 18633 E unknown:React: java.net.SocketException: Socket is closed
07-11 04:27:55.469 18176 18633 E unknown:React: 	at com.android.org.conscrypt.OpenSSLSocketImpl.checkOpen(OpenSSLSocketImpl.java:247)
07-11 04:27:55.469 18176 18633 E unknown:React: 	at com.android.org.conscrypt.OpenSSLSocketImpl.-wrap0(OpenSSLSocketImpl.java)
07-11 04:27:55.469 18176 18633 E unknown:React: 	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:756)
07-11 04:27:55.469 18176 18633 E unknown:React: 	at okio.Okio$1.write(Okio.java:80)
07-11 04:27:55.469 18176 18633 E unknown:React: 	at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
07-11 04:27:55.469 18176 18633 E unknown:React: 	at okio.RealBufferedSink.emit(RealBufferedSink.java:178)
07-11 04:27:55.469 18176 18633 E unknown:React: 	at okhttp3.internal.ws.WebSocketWriter.writeControlFrameSynchronized(WebSocketWriter.java:152)
07-11 04:27:55.469 18176 18633 E unknown:React: 	at okhttp3.internal.ws.WebSocketWriter.writeClose(WebSocketWriter.java:111)
07-11 04:27:55.469 18176 18633 E unknown:React: 	at okhttp3.internal.ws.RealWebSocket.close(RealWebSocket.java:168)
07-11 04:27:55.469 18176 18633 E unknown:React: 	at com.facebook.react.modules.websocket.WebSocketModule.close(WebSocketModule.java:194)
07-11 04:27:55.469 18176 18633 E unknown:React: 	at java.lang.reflect.Method.invoke(Native Method)
07-11 04:27:55.469 18176 18633 E unknown:React: 	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
07-11 04:27:55.469 18176 18633 E unknown:React: 	at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:187)
07-11 04:27:55.469 18176 18633 E unknown:React: 	at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:62)
07-11 04:27:55.469 18176 18633 E unknown:React: 	at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.call(CatalystInstanceImpl.java:432)
07-11 04:27:55.469 18176 18633 E unknown:React: 	at com.facebook.react.bridge.queue.NativeRunnableDeprecated.run(Native Method)
07-11 04:27:55.469 18176 18633 E unknown:React: 	at android.os.Handler.handleCallback(Handler.java:742)
07-11 04:27:55.469 18176 18633 E unknown:React: 	at android.os.Handler.dispatchMessage(Handler.java:97)
07-11 04:27:55.469 18176 18633 E unknown:React: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
07-11 04:27:55.469 18176 18633 E unknown:React: 	at android.os.Looper.loop(Looper.java:148)
07-11 04:27:55.469 18176 18633 E unknown:React: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:193)
07-11 04:27:55.469 18176 18633 E unknown:React: 	at java.lang.Thread.run(Thread.java:818)
```

Is this only related to the dev server?

**Comment by paramaggarwal** [comment] 2016-08-16 10:53
Please follow along on #8949.

**Comment by rmevans9** [comment] 2016-08-16 11:34
Closing as duplicate as this appears to be the same issue.

**Comment by rmevans9** [comment] 2016-08-16 11:34
@facebook-github-bot duplicate 8949

**Comment by rmevans9** [comment] 2016-08-16 11:36
@facebook-github-bot duplicate #8949

**Comment by facebook-github-bot-2** [comment] 2016-08-16 11:37
@rmevans9 tells me this issue is a duplicate of #8949. Let's discuss there, closing this one.

**Closed by facebook-github-bot-2** 2016-08-16 11:37 UTC
Labels: Android, Ran Commands
