### ISSUE TITLE
new images asset system can't load image in dev mode

### ISSUE THREAD

**Issue by lizt99** [facebook/react-native#4010] opened 2015-11-09 18:19 UTC
##### step to reproduce
1. on real machine (OS: android, React-native version: 0.14.1) 
2. enter "Dev setting", setup the "Debug server host & port for device" with value of  "192.168.1.3:8081"  (please specify the real ip address for your server)
3. code in view as following
     ` <Image source={require('./my-icon.png')} /> `
4. you will see image will not be load and show as blank area in screen.

##### relate code (no investigation result yet) :
in file "react-native/Libraries/Image/resolveAssetSource.js"  
```
function getDevServerURL() {
  if (_serverURL === undefined) {
    var scriptURL = SourceCode.scriptURL;
    var match = scriptURL && scriptURL.match(/^https?:\/\/.*?\//);
    if (match) {
      // Bundle was loaded from network
      _serverURL = match[0];
    } else {
      // Bundle was loaded from file
      _serverURL = null;
    }
  }

  return _serverURL;
}
```

**Comment by hoangstorm** [comment] 2015-11-10 07:09
in file "react-native/Libraries/Image/resolveAssetSource.js", change the line 96 to
```javascript
if (path[0] === '\\') {
```

**Comment by lizt99** [comment] 2015-11-10 10:15
Yes, thanks.

/**
 * Returns a path like 'assets/AwesomeModule'
 */
function getBasePath(asset) {
  // TODO(frantic): currently httpServerLocation is used both as
  // path in http URL and path within IPA. Should we have zipArchiveLocation?
  var path = asset.httpServerLocation;
  if (path[0] === '/' || path[0] === '\\') {
    path = path.substr(1);
  }

  return path;
}

**Comment by rockerhieu** [comment] 2015-11-16 03:06
Similar issue? https://github.com/facebook/react-native/issues/4084

**Comment by mkonicek** [comment] 2015-11-17 14:53
Is this on Windows? Closing as duplicate of https://github.com/facebook/react-native/issues/3980

If it's not Windows let's reopen.

**Closed by mkonicek** 2015-11-17 14:53 UTC
