### ISSUE TITLE
[Android] ListView With Refresh Control Has Style Applied Twice 

### ISSUE THREAD

**Issue by T-Spoon** [facebook/react-native#10742] opened 2016-11-04 12:27 UTC
### Description

When using the a `ListView` with a `RefreshControl` on Android, the ListView is wrapped by the RefreshControl. [Relevant code](https://github.com/facebook/react-native/blob/9ee815f6b52e0c2417c04e5a05e1e31df26daed2/Libraries/Components/ScrollView/ScrollView.js#L525)

The issue is that the styles are applied to both the RefreshControl wrapper, and the original ListView.  This means that if you had padding/margin on the ListView, then this is compounded, and you'll end up with double the amount of margin/padding.

It should be noted that this only applies when using the default `ScrollView` component, not the `RecyclerViewBackedScrollView`.  But the `RecyclerViewBackedScrollView` has it's own issues, which makes it unsuitable for some use cases. See here: #7001

### Reproduction

1. Create `ListView` (without a `RefreshControl`). Don't use `RecyclerViewBackedScrollView`
2. Add some padding to the `ListView` and render on Android (it should show as expected)
3. Add a `RefreshControl` to the `ListView` and notice that the padding has doubled.

### Additional Information

* React Native version: 0.3.6
* Platform: Android
* Operating System: MacOS

**Comment by brentvatne** [comment] 2016-11-06 18:07
Hi @T-Spoon! Thanks for the report. Can you create a repository so that we can just clone it? Also it seems that you have a solid grasp of what the problem is, so a pull request would be welcome.

**Comment by linmic** [comment] 2016-11-12 22:00
@brentvatne @T-Spoon I took a stab at this, #10899 should resolve this issue.

**Comment by hramos** [comment] 2017-03-31 18:35
Closing as ListView is deprecated in 0.43. Use FlatList.

**Closed by hramos** 2017-03-31 18:35 UTC
Labels: Android, Help Wanted
