### ISSUE TITLE
Bug in TextInput's text style in android, when the text's style in changed conditionally

### ISSUE THREAD

**Issue by losh11** [facebook/react-native#29804] opened 2020-08-29 04:36 UTC
We are conditionally changing the style of the text in TextInput. On iOS and Web this doesn't seem to have an issue, on android when the second condition is reached, the text looses all of its style. Please keep in mind that the text is still in state, the only thing wrong here is the style.

```js
<TextInput
 ...
 style={[
  styles.wordText,
  index === phrase ? style1 : null, 
 ]}
/>
```

## Description
Code example available in this snack: https://snack.expo.io/@loshan1212/losh11-textinput-bug-android

On react-native web, please try entering text into the text input and press the return key. As you can see the app will move you into the second text input, and the style of the original text input changes as it becomes inactive, whilst text input 2 is now active. 

Now try this in android. You will see that whilst text input 2's style becomes active, text input 1's text disappears. This is the bug.

## React Native version:
```
System:
    OS: macOS 11.0
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 459.01 MB / 24.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v10.16.3/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v10.16.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 20.0, macOS 11.0, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.0
      System Images: android-25 | Google APIs ARM EABI v7a, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 12.0/12A8189n - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce

1. Please see code snack above.

## Expected Results
The inactive TextInput's text shouldn't become invisible!

## Snack, code example, screenshot, or link to a repository:
https://snack.expo.io/@loshan1212/losh11-textinput-bug-android

**Comment by SYNTAG** [comment] 2020-08-31 18:27
Duplicate of https://github.com/facebook/react-native/issues/29717

**Comment by safaiyeh** [comment] 2020-09-04 05:51
Thanks for the issue @losh11, I'll close this so we can track it in one place #29717

**Closed by safaiyeh** 2020-09-04 05:51 UTC
Labels: Component: TextInput, Needs: Triage :mag:, Platform: Android
