### ISSUE TITLE
Animations on borderRadius don't work as expected

### ISSUE THREAD

**Issue by tomerlevi444** [facebook/react-native#11925] opened 2017-01-16 09:45 UTC
### Description

When animating on borderRadius, the result looks strange.
For instance, when animating from fullCircle to emptyCircle in the following example, the borderRadius in the beginning of the animation seems to be 0 but should be 20 (hence, the animation starts with a square instead of a circle).
```
StyleSheet.create({
  emptyCircle: {
      width: 10,
      height: 10,
      borderRadius: 5,
      borderWidth: 1,
      borderColor: 'grey'
    },
  fullCircle: {
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: 'black'
    }
})
```

This is how it looks like when animating with `LayoutAnimation.Presets.linear`:

![file](https://cloud.githubusercontent.com/assets/7806514/21977910/f9f9e9d2-dbe0-11e6-9c0b-258604346866.gif)

**Comment by janicduplessis** [comment] 2017-01-17 03:58
This is because `LayoutAnimation` only works for animating layout props (anything that changes a view position or size) but borderRadius is not one. What I recommend doing here is using `Animated` instead. You can do something like:
``` js
_onButtonPress() {
  Animated.timing(this.state.anim, {
    toValue: 1,
    duration: 500,
  });
}

render() {
  const scale = this.state.anim.interpolate({
    inputRange: [0, 1],
    outputRange: [1, 0.5],
  });
  const backgroundColor = this.state.anim.interpolate({
    inputRange: [0, 1],
    outputRange: ['black', 'white'],
  });
  return (
    <Animated.View style={[styles.circle, { backgroundColor, transform: [{ scale }] }]} />
  );
}
...

const styles = StyleSheet.create({
  circle: {
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: 'black'
    }
})
```

**Comment by janicduplessis** [comment] 2017-01-17 03:58
Closing as this is not a bug.

**Closed by janicduplessis** 2017-01-17 03:58 UTC
