### ISSUE TITLE
TextInput multiline value, smaller than placeholder in TextInput component

### ISSUE THREAD

**Issue by jackc105** [facebook/react-native#14920] opened 2017-07-10 08:13 UTC
When adding text into a `<TextInput>` component with `multiline` set to false the `value` text matches the `placeholder` text font size, whereas if `multiline` is equal to true, the `value` text font size is smaller than the placeholder font size.

![so](https://user-images.githubusercontent.com/15000036/28008118-107ba38e-654e-11e7-9040-577365d6e2fc.gif)

Haven't tried this on Android yet as I'm only making an iOS application.

Code:

```
/* @flow */

import React from 'react'
import Separator from './components/Separator'
import {Button, StyleSheet, TextInput, View} from 'react-native'

const styles = StyleSheet.create({
    subject: {
        height: 20,
    },
    body: {
        height: 100,
    },
})

export default class NewQuestion extends React.Component {
    static navigationOptions = ({navigation}) => ({
        title: 'AIBU',
        headerLeft: (
            <Button
                onPress={() => {
                    navigation.goBack()
                }}
                title="Back"
            />
        ),
    })

    state = {
        subject: '',
        body: '',
    }

    render() {
        return (
            <View>
                <TextInput
                    autoFocus
                    onChangeText={subject => this.setState({subject})}
                    placeholder="Enter your AIBU subject..."
                    style={styles.subject}
                    value={this.state.subject}
                />
                <Separator />
                <TextInput
                    multiline
                    onChangeText={body => this.setState({body})}
                    placeholder="Enter your AIBU description..."
                    style={styles.body}
                    value={this.state.body}
                />
            </View>
        )
    }
}
```

1. Target Platform - iOS
2. Development Operating System - macOS Sierra
3. Xcode & Atom

### Expected Behavior

That the fontSize of placeholder and value would be the same

### Actual Behavior

The fontSize appears different

**Comment by hramos** [comment] 2017-07-10 18:45
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-07-10 18:45 UTC

**Comment by LaszloDev** [comment] 2017-08-17 11:10
Any update here? Having the same problem with `<TextInput multiline={true}><TextInput/>` that the input text is smaller than the fontSize on React-Native 0.46.

**Comment by pt-mpb** [comment] 2017-09-04 17:12
Hi,

I'm having this exact same issue. Using React-Native 0.42. 
Any news?

**Comment by enthal** [comment] 2017-10-25 17:37
Same.

**Comment by hramos** [comment] 2017-10-27 19:07
No updates here - the issue was closed because it did not meet our guidelines. Highly recommend filing a new issue.
