### ISSUE TITLE
[Bridge] Deallocating memory when popping ViewController that contains React Native component

### ISSUE THREAD

**Issue by jessepollak** [facebook/react-native#1487] opened 2015-06-02 01:09 UTC
I'm using React Native inside an existing app. I create a `RCTBridge` in `didFinishLaunchingWithOptions`, which I use to initialize `ReactRootView`s in certain ViewControllers (who's only purpose is to show the `ReactRootView`). 

I've create a `RCTReactViewManager`, which lets me pop out of those React Views through some View Controller gymnastics (this was the best way I could figure out how to do it).

```objective-c
@implementation RCTReactViewManager

RCT_EXPORT_MODULE(RCTReactViewManager);
RCT_EXPORT_METHOD(returnFromReactView) {
    UIWindow *keyWindow = [[UIApplication sharedApplication] keyWindow];
    UIViewController *mainViewController = keyWindow.rootViewController.childViewControllers[0];
    dispatch_async(dispatch_get_main_queue(), ^{
        [mainViewController.navigationController popViewControllerAnimated:true];
    });
}

@end
```

The problem: when I pop out of the React View Controllers, large chunks of memory are stuck in the VM: JS Garbage Collector and never deallocated.

![screenshot 2015-06-01 18 08 38](https://cloud.githubusercontent.com/assets/1097953/7926548/410cd276-0889-11e5-8c0a-c9dea3a82cc9.png)

I'm guessing this is because I am using the `RCTBridge`, which is holding the execution context across the whole app, so I'm curious whether there's any manual way to deallocate that memory that is consumed.

Thanks for all of y'alls help :)

**Comment by JohnyDays** [comment] 2015-06-02 10:32
I worked around this problem by instantiating a bridge for every viewController, although you have to pay the startup cost every time

**Comment by imton** [comment] 2015-12-10 05:51
Aked the same here: http://stackoverflow.com/questions/34168314/unload-release-remove-react-native-view-from-runtime

How to do this? Thanks!

**Comment by jnak** [comment] 2016-03-15 02:16
@JohnyDays I have the same problem even though I do initialize my view with a bridge (instantiated by my view controller) and release the bridge in the viewDidDisappear of my view controller. Is that what you did?

@jessepollak  When I use instruments to inspect my memory usage, I do see the memory increasing but I'm not able to see an item "VM: JS garbage collector".  How did you manage to have this line show up?

Thanks!

**Comment by jessepollak** [comment] 2016-03-15 02:28
@jnak this was a while ago, so I imagine the implementation has changed such that the "VM: JS garbage collector" no longer is there, sorry!

**Comment by jnak** [comment] 2016-03-15 16:37
@jessepollak thanks for your answer. Yes that makes sense. Did you end solving your memory leak? It's only a few mb for simple views but when I load a map, my app is leaking +100Mb. It's very very concerning to me ;)

**Comment by jessepollak** [comment] 2016-03-15 23:25
I believe that we now recreate the `RCTBridge` every time we pop on a new React view controller.

**Comment by jnak** [comment] 2016-03-16 21:33
Actually I'm not able to reproduce the leak. It might have been cause by the new relic sdk that keeps some objects around in some cases.

Anyway if we are all good, let's close the ticket for now?

**Comment by jsierles** [comment] 2016-04-27 22:13
@facebook-github-bot close

**Comment by facebook-github-bot-4** [comment] 2016-04-27 22:18
@jsierles tells me to close this issue. If you think it should still be opened let us know why.

**Closed by facebook-github-bot-4** 2016-04-27 22:18 UTC
Labels: Ran Commands
