### ISSUE TITLE
Error when I try to upgrade to react-native 0.57.0

### ISSUE THREAD

**Issue by ferily7** [facebook/react-native#20723] opened 2018-08-17 23:17 UTC
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
      Memory: 5.89 GB / 15.84 GB
    Binaries:
      npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
      Watchman: 4.9.4 - C:\Users\User\watchman\watchman.EXE
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4907809

## Description
When I try to upgrade my version from 0.56 to 0.57, I am getting some kind of error with the babel-preset-react native:

```
git-upgrade ERR! An error occurred during upgrade:
git-upgrade ERR! Error: Plugin 0 specified in "C:\\Users\\User\\Documents\\Test\\node_modules\\babel-preset-react-native\\index.js" provided an invalid property of "default" (While processing preset: "C:\\Users\\User\\Documents\\Test\\node_modules\\babel-preset-react-native\\index.js")
    at Plugin.init (C:\Users\User\AppData\Roaming\npm\node_modules\react-native-git-upgrade\node_modules\babel-core\lib\transformation\plugin.js:131:13)
    at Function.normalisePlugin (C:\Users\User\AppData\Roaming\npm\node_modules\react-native-git-upgrade\node_modules\babel-core\lib\transformation\file\options\option-manager.js:152:12)
    at C:\Users\User\AppData\Roaming\npm\node_modules\react-native-git-upgrade\node_modules\babel-core\lib\transformation\file\options\option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (C:\Users\User\AppData\Roaming\npm\node_modules\react-native-git-upgrade\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (C:\Users\User\AppData\Roaming\npm\node_modules\react-native-git-upgrade\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at C:\Users\User\AppData\Roaming\npm\node_modules\react-native-git-upgrade\node_modules\babel-core\lib\transformation\file\options\option-manager.js:265:14
    at C:\Users\User\AppData\Roaming\npm\node_modules\react-native-git-upgrade\node_modules\babel-core\lib\transformation\file\options\option-manager.js:323:22
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (C:\Users\User\AppData\Roaming\npm\node_modules\react-native-git-upgrade\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
git-upgrade ERR! Restore initial sources
Note: checking out 'project-snapshot'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 43d94ce Project snapshot
```

## Reproducible Demo
```
react-native init Test
cd Test
react-native-git-upgrade
```

**Comment by mikalai-silivonik** [comment] 2018-08-18 18:39
@ferily7 In my case reverting `babel-preset-react-native` fixed the issue. 

Run 

```shell
npm install babel-preset-react-native@4.0.0 --save-dev
```

And check whether that fixes this particular issue.

**Comment by kelset** [comment] 2018-08-18 19:39
Duplicate of https://github.com/facebook/react-native/issues/20710

**Closed by kelset** 2018-08-18 19:39 UTC
Labels: :clipboard:No Environment Info

**Comment by zhuanghongji** [comment] 2019-02-13 15:55
> @ferily7 In my case reverting `babel-preset-react-native` fixed the issue.
> 
> Run
> 
> ```shell
> npm install babel-preset-react-native@4.0.0 --save-dev
> ```
> 
> And check whether that fixes this particular issue.

It worked for me.
