### ISSUE TITLE
0.16.0-rc Command /bin/sh failed with exit code 1

### ISSUE THREAD

**Issue by jasonmerino** [facebook/react-native#4509] opened 2015-12-02 18:43 UTC
After upgrading to 0.16.0-rc I am now not able to archive the project in Xcode.

The `react-native bundle` script that runs as my last build phase in Xcode bombs out and spits this at me.

```
react-native bundle --entry-file index.ios.js --platform ios --dev false --bundle-output /Users/jason.merino/Library/Developer/Xcode/DerivedData/MyApp-eldkyikzvyjteiggldraztbktyqq/Build/Intermediates/ArchiveIntermediates/MyApp/BuildProductsPath/Release-iphoneos/MyApp.app/main.jsbundle --assets-dest /Users/jason.merino/Library/Developer/Xcode/DerivedData/MyApp-eldkyikzvyjteiggldraztbktyqq/Build/Intermediates/ArchiveIntermediates/MyApp/BuildProductsPath/Release-iphoneos/MyApp.app
bundle: Created ReactPackager
bundle: start
[10:27:32 AM] <START> Whole Program Optimisations
uncaught error TypeError: unknown: Property property of MemberExpression expected node to be of a type ["Identifier"] but instead got "BooleanLiteral"
    at validate (/Users/jason.merino/Code/MyApp/node_modules/react-native/node_modules/babel-types/lib/definitions/index.js:98:13)
    at Object.validate (/Users/jason.merino/Code/MyApp/node_modules/react-native/node_modules/babel-types/lib/definitions/core.js:412:45)
    at Object.validate (/Users/jason.merino/Code/MyApp/node_modules/react-native/node_modules/babel-types/lib/index.js:266:9)
    at NodePath._replaceWith (/Users/jason.merino/Code/MyApp/node_modules/react-native/node_modules/babel-core/node_modules/babel-traverse/lib/path/replacement.js:201:7)
    at NodePath.replaceWith (/Users/jason.merino/Code/MyApp/node_modules/react-native/node_modules/babel-core/node_modules/babel-traverse/lib/path/replacement.js:179:8)
    at firstPass.Identifier (dead-module-elimination.js:96:14)
    at NodePath._call (/Users/jason.merino/Code/MyApp/node_modules/react-native/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:74:18)
    at NodePath.call (/Users/jason.merino/Code/MyApp/node_modules/react-native/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:46:17)
    at NodePath.visit (/Users/jason.merino/Code/MyApp/node_modules/react-native/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:104:12)
    at TraversalContext.visitQueue (/Users/jason.merino/Code/MyApp/node_modules/react-native/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:153:16)
Command /bin/sh failed with exit code 1
```

Looks like this is lower down in some of the babel dependencies. 

The app works in development mode, but when going to create the archive it fails. I've removed and reinstalled node_modules a few times, and believe I have updated everything correctly and am at a loss for what to do next. Any help would be appreciated.

**Comment by mkonicek** [comment] 2015-12-02 21:56
Looks like a duplicate of #3948?

**Comment by mkonicek** [comment] 2015-12-02 21:56
Let's reopen if it's not a duplicate.

**Closed by mkonicek** 2015-12-02 21:56 UTC

**Comment by jasonmerino** [comment] 2015-12-02 22:33
@mkonicek to me it looks like this issue is different. #3948 seems to be related to not being able to compile the project. I can compile my project just fine and everything works in development mode. It's when I go to create the archive and the `--dev` flag is set to `false` that this issue crops up.

In fact, I went back and tried out the command just from the terminal and it worked with `--dev true`.

```bash
react-native bundle --entry-file index.ios.js --platform ios --dev true --bundle-output ...
```
 but throws an uncaught error with `--dev false`.

```bash
react-native bundle --entry-file index.ios.js --platform ios --dev false --bundle-output ...
```

Looks like something after "Whole Program Optimisations" is throwing the error.

**Comment by jasonmerino** [comment] 2015-12-02 22:34
Please re-open.

**Comment by jasonmerino** [comment] 2015-12-03 19:16
@mkonicek It looks like I have resolved the issue I was having. I guess that now when you bundle the app it doesn't understand referencing `global.__DEV__`. If I change my if statements from

```javascript
if (global.__DEV__) {
...
```

to 

```javascript
if (__DEV__) {
...
```

Then it creates the bundle successfully.

**Comment by niftylettuce** [comment] 2016-01-07 21:31
+1 same issue

**Comment by niftylettuce** [comment] 2016-01-07 21:38
Thanks @jasonmerino for reporting how you fixed it, this fix worked for me.

**Comment by jasonmerino** [comment] 2016-01-12 22:17
@niftylettuce :+1:

**Comment by zhaowx** [comment] 2016-01-21 03:55
@jasonmerino   hou to reslove this problem?
    ' if (global.__DEV__) {'? 
which file? 
please help!

**Comment by jasonmerino** [comment] 2016-01-21 15:53
@zhaowx In the project I had the issue in I had to change any reference to `global.__DEV___` to just `__DEV__`. That was the whole change. Couldn't use the `global` portion while bundling the app.
