### ISSUE TITLE
[RN 0.12] borderTopLeftRadius and the other 3 corner radius counterparts not working

### ISSUE THREAD

**Issue by ACCTFORGH** [facebook/react-native#3940] opened 2015-11-06 05:54 UTC
I was trying to round the corner of my square views but found the corner border radius props not working.  I have tried all four of them(borderTopLeftRadius, borderTopRightRadius, borderBottomLeftRadius, borderBottomRightRadius), but none works. The borderRadius props though work fine. I am using RN 0.12 on Mac OS.

The code snippet is as below.

< View
            name ='Button'
            style = {{flex:1, backgroundColor:'white',borderBottomLeftRadius:30, borderBottomRightRadius:30, height:75,width:345 }}>

  {children}

</ View>

same issue was raised in StackOverflow: http://stackoverflow.com/questions/33560373/bordertopleftradius-and-the-other-3-corner-radius-counterparts-not-working

Thank you.

**Comment by maraujop** [comment] 2015-11-10 17:21
I believe this issue is a duplicate of https://github.com/facebook/react-native/issues/3040

**Comment by browniefed** [comment] 2016-03-20 21:31
@facebook-github-bot duplicate #3040

**Closed** 2016-03-20 21:31 UTC
Labels: Ran Commands
