### ISSUE TITLE
com.facebook.react.bridge.JSExecutionException: SyntaxError: Unexpected EOF

### ISSUE THREAD

**Issue by arjunkomath** [facebook/react-native#6178] opened 2016-02-26 17:58 UTC
My app was working fine in production until out of nowhere it started crashing as soon as the app was loaded. Surprisingly, I got **more than 100 crash reports in just an hour**. Every single crash was same as given below:

```
com.facebook.react.bridge.JSExecutionException: SyntaxError: Unexpected EOF (line 1 in the generated bundle)
	at com.facebook.react.bridge.ReactBridge.callFunction(Native Method)
	at com.facebook.react.bridge.CatalystInstanceImpl$3.run(CatalystInstanceImpl.java:199)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
	at android.os.Looper.loop(Looper.java:194)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$1.run(MessageQueueThreadImpl.java:137)
	at java.lang.Thread.run(Thread.java:818)
```

Current version of RN is 0.17

**Things I already tried:**

- Rebuild the whole app
- Remove code push
- Update to RN 0.20

Everything results in the same error, but the **app works perfectly fine when Debug in Chrome** is enabled. So basically, my apps works ONLY in debug.

Any help would be appreciated.

**Comment by dsibiski** [comment] 2016-02-26 17:59
@arjunkomath When you upgraded RN to 0.20, did you run the `react-native upgrade` command to update some of the project files?

**Comment by arjunkomath** [comment] 2016-02-26 18:01
Yes, the app works fine in RN 0.20, if and ONLY if debug in chrome is enabled. When I disable that I get the exact same error in both RN 0.20 and 0.17

**Comment by lostintangent** [comment] 2016-02-26 18:05
Could this possibly be related to #4407? It wasn't clear what the root cause of that issue was, and the symptoms seem pretty identical.

**Comment by arjunkomath** [comment] 2016-02-27 09:23
Surprisingly the app is working now, and I have no idea what caused this bug or how it got fixed.

First Crash At:
27 Feb 2016, 03:11

Last Crash At:
27 Feb 2016, 14:48

Number of Crashes
167

Reason: com.facebook.react.bridge.JSExecutionException: SyntaxError: Unexpected EOF (line 1 in the generated bundle)

Conclusion: ?!

**Comment by dsibiski** [comment] 2016-02-27 12:12
I'll close it for now, since it seems like you're back up and running. :+1:

**Closed by dsibiski** 2016-02-27 12:12 UTC

**Comment by arjunkomath** [comment] 2016-02-29 09:22
We don't know what caused this issue or what to do if this happens again.

**Comment by satya164** [comment] 2016-07-10 21:48
Duplicate of https://github.com/facebook/react-native/issues/4961
