### ISSUE TITLE
[0.57.0-rc.0] react-native-git-upgrade and old school upgrade are broken

### ISSUE THREAD

**Issue by fungilation** [facebook/react-native#20720] opened 2018-08-17 20:35 UTC
## Environment
```
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
      Memory: 8.52 GB / 15.95 GB
    Binaries:
      Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.0 - C:\Program Files\nodejs\npm.CMD
```
I'm upgrading from React Native 0.56.0.

## Description
Continuing on from https://github.com/facebook/react-native/issues/20710 since 1 disruptive comment there is *too heated*, and apparently it's better to lock that issue instead of just deleting said comment and not bar anyone including myself from adding to my own bug report there. (please ease on the heavy handed moderation, locking everything isn't the way unless you want 0 feedback from everyone)

Now I'm hitting this:
```
PS C:\Users\Gary\Documents\code\WonderSwipe> react-native upgrade
Scanning folders for symlinks in C:\Users\Gary\Documents\code\WonderSwipe\node_modules (28ms)
(node:16936) UnhandledPromiseRejectionWarning: Error: Cannot find module 'metro/src/blacklist'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\Gary\Documents\code\WonderSwipe\rn-cli.config.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._compile (C:\Users\Gary\Documents\code\WonderSwipe\node_modules\pirates\lib\index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .js] (C:\Users\Gary\Documents\code\WonderSwipe\node_modules\pirates\lib\index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
(node:16936) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16936) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Metro still?

## Reproducible Demo
I first ran `yarn add react-native@0.57.0-rc.0` without issue, and modified my `.babelrc` to
```json
{
  "presets": ["module:metro-react-native-babel-preset"],
  "plugins": ["idx"]
}
```

Then I ran `react-native upgrade`, and I get output above under Description.

**Comment by fungilation** [comment] 2018-08-17 20:48
PS. output from `yarn add` for metro/babel versions upgraded to. Need locking to specific versions instead of latest?
```
> yarn add react-native@0.57.0-rc.0
yarn add v1.9.4
[1/5] Resolving packages...
[2/5] Fetching packages...
[----------------------------------------------------------------------------------------------------------------------] 0/807(node:12256) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/5] Linking dependencies...
warning " > react-native-actionsheet@2.4.2" has unmet peer dependency "prop-types@>=15.4.0".
warning " > react-native-easy-toast@1.1.0" has unmet peer dependency "prop-types@^15.5.7".
warning " > react-native-firebase@3.3.1" has unmet peer dependency "fbjs@*".
warning " > react-native-flanimatedimage@0.4.0" has unmet peer dependency "prop-types@*".
warning " > react-native-highlight-words@1.0.1" has incorrect peer dependency "react@^15.5.0".
[4/5] Building fresh packages...
[5/5] Cleaning modules...
success Saved lockfile.
success Saved 38 new dependencies.
info Direct dependencies
└─ react-native@0.57.0-rc.0
info All dependencies
├─ @babel/helper-builder-binary-assignment-operator-visitor@7.0.0-beta.56
├─ @babel/helper-builder-react-jsx@7.0.0-beta.56
├─ @babel/helper-call-delegate@7.0.0-beta.56
├─ @babel/helper-define-map@7.0.0-beta.56
├─ @babel/helper-explode-assignable-expression@7.0.0-beta.56
├─ @babel/helper-hoist-variables@7.0.0-beta.56
├─ @babel/helper-module-transforms@7.0.0-beta.56
├─ @babel/helper-wrap-function@7.0.0-beta.56
├─ @babel/helpers@7.0.0-beta.56
├─ @babel/highlight@7.0.0-beta.56
├─ @babel/plugin-external-helpers@7.0.0-beta.56
├─ @babel/plugin-syntax-class-properties@7.0.0-beta.56
├─ @babel/plugin-syntax-dynamic-import@7.0.0-beta.56
├─ @babel/plugin-syntax-flow@7.0.0-beta.56
├─ @babel/plugin-syntax-object-rest-spread@7.0.0-beta.56
├─ @babel/plugin-syntax-optional-catch-binding@7.0.0-beta.56
├─ @babel/plugin-syntax-optional-chaining@7.0.0-beta.56
├─ @babel/plugin-syntax-typescript@7.0.0-beta.56
├─ @babel/plugin-transform-sticky-regex@7.0.0-beta.56
├─ @babel/plugin-transform-typescript@7.0.0-beta.56
├─ argparse@1.0.10
├─ babel-preset-fbjs@2.2.0
├─ cosmiconfig@5.0.6
├─ is-directory@0.3.1
├─ jest-docblock@23.2.0
├─ jest-worker@23.2.0
├─ js-yaml@3.12.0
├─ json-parse-better-errors@1.0.2
├─ metro-babel-register@0.43.6
├─ metro-config@0.43.6
├─ metro-memory-fs@0.43.6
├─ metro-minify-uglify@0.43.6
├─ metro-react-native-babel-preset@0.43.6
├─ metro-source-map@0.43.6
├─ metro@0.43.6
├─ pirates@4.0.0
├─ react-native@0.57.0-rc.0
└─ sprintf-js@1.0.3
Done in 63.75s.
```

**Comment by kelset** [comment] 2018-08-18 19:45
Duplicate of #https://github.com/facebook/react-native/issues/20710

> apparently it's better to lock that issue instead of just deleting said comment and not bar anyone including myself from adding to my own bug report there. (please ease on the heavy handed moderation, locking everything isn't the way unless you want 0 feedback from everyone)

It is better, and I am getting really tired of such behaviours. I'll unlock the previous issue for now, but I hope you can understand that just posting useless comments is not moving the issue forward in any way.

**Closed by kelset** 2018-08-18 19:45 UTC
