### ISSUE TITLE
Prevent system font from overriding app font

### ISSUE THREAD

**Issue by damathryx** [facebook/react-native#12978] opened 2017-03-16 17:23 UTC
I need to force app font inside the app and not to be overridden by system font. Namely font size and fontFamily. I also added the font I am using in assets and resources for android and iOS respectively. 

rn: 0.42

**Comment by hramos** [comment] 2017-03-16 18:09
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-03-16 18:09 UTC
