### ISSUE TITLE
App crashes when displayName is written in CJK(Chinese, Korean, Japanese)

### ISSUE THREAD

**Issue by ZeroCho** [facebook/react-native#34066] opened 2022-06-24 09:15 UTC
### Description

In android emulator, if I change app name to Korean or Chinese, it crashes.
If I revert the name of an app to english, it works well again.

### Version

0.69

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22000
    CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
    Memory: 5.96 GB / 31.93 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20210110.135312.0 - C:\ProgramData\chocolatey\bin\watchman.EXE
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowAllTrustedApps: Disabled
      Versions: 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 11.0.1
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.0 => 0.69.0
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. react-native init koreantestapp
2. change app_name to 세종대왕 in `res/values/strings.xml `  OR (make `res/values-ko/strings.xml` and change app_name to 세종대왕)
3. npm run android
4. Crash!

### Snack, code example, screenshot, or link to a repository

https://github.com/ZeroCho/food-delivery-app-69

**Comment by mensonones** [comment] 2022-06-24 18:33
Hey, @ZeroCho!  reproduced this error!

I put a logcat and the following error is shown: JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal continuation byte 0x25

This problem is most likely caused by something internal to the jni, not react native.

**Comment by ZeroCho** [comment] 2022-06-25 05:11
@mensonones Thx, it's a Flipper issue.

android/gradle.properties
```
FLIPPER_VERSION=0.145.0
```
works fine.

**Comment by oakis** [comment] 2022-11-28 08:50
> @mensonones Thx, it's a Flipper issue.
> 
> android/gradle.properties
> 
> ```
> FLIPPER_VERSION=0.145.0
> ```
> 
> works fine.

This was also the solution for me. I had a Swedish character in my name and couldn't figure out why the app crashed. Thanks for the solution!

**Comment by cortinico** [comment] 2022-11-28 11:05
Thanks for sharing the resolution @ZeroCho 
I'm closing as we updated the default Flipper version last week. It will land in 0.72
Users on previous versions of RN can still manually update the version as you suggested

**Closed by cortinico** 2022-11-28 11:05 UTC
Labels: Resolution: Fixed

**Comment by sqlsystems** [comment] 2022-12-01 10:26
@ZeroCho 감사합니다. 디버그 실력에 감탄 했습니다!

**Comment by Pointotech** [comment] 2023-01-10 20:25
This is a nasty bug that breaks apps created with older versions of React Native. Updating Flipper to `0.145.0` fixes this.

@ZeroCho Thanks for the fix!
