### ISSUE TITLE
Functional components allow to have `this` reference

### ISSUE THREAD

**Issue by riwu** [facebook/react-native#18942] opened 2018-04-19 09:55 UTC
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
Environment:
  OS: macOS Sierra 10.12.6
  Node: 9.10.1
  Yarn: 1.5.1
  npm: 3.10.10
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.2 => 0.55.2

## Steps to Reproduce
```
const Example = props => (
  <Button
    title="Click"
    onPress={() => {
      this.count = (this.count || 0) + 1;
      props.setCount(this.count);
    }}
  />
);

class App extends React.Component {
  state = {
    count1: 0,
    count2: 0,
  };
  render() {
    return (
      <View style={{ alignItems: 'center', justifyContent: 'center', flex: 1 }}>
        <Example setCount={count => this.setState({ count1: count })} />
        <Text>{this.state.count1}</Text>
        <Example setCount={count => this.setState({ count2: count })} />
        <Text>{this.state.count2}</Text>
      </View>
    );
  }
}
```
![](https://i.imgur.com/9j88LKa.gif)

In React.js, stateless components are not allowed to have `this` reference so `Example` would give an error on click. 

In react-native, `this` unexpectedly behaves like a class property instead. 

Both the `<Example />` instances share the same `this`, so clicking on one button would increment `this.count` for both instances.

**Comment by syumai** [comment] 2018-08-05 06:03
In bundled js file, babel declares `_this` and intializes with `this` to transpile arrow functions to es5 functions.
The content of `this` was the global object named `DedicatedWorkerGlobalScope`.
I confirmed that the same phenomenon will occur in the release build.

Since a Object (in this case, `DedicatedWorkerGlobalScope`) is passed, 
it can have the `count` property and the value of its `count` property can be referenced.

In expo snack, it failes because global object is `undefined` in snack.
Here's link of snack: https://snack.expo.io/SJVB1fESm

link of a part of bundled JS: https://gist.github.com/syumai/0dbe2d8bcbc17475a211b39ec6ee4241#file-bundle-js-L17

**Comment by riwu** [comment] 2018-11-03 15:44
Should this be fixed?

**Comment by TheSavior** [comment] 2019-03-19 14:56
Babel has been updated since 0.55.2, does this repro in 0.59? I'm going to close this as the version in the original post is quite old, but if this reproes still in 0.59 then let us know and we can reopen the issue.

**Closed by TheSavior** 2019-03-19 14:56 UTC
Labels: JavaScript, Type: Bug Report
