### ISSUE TITLE
Artifacts on View with borderRadius on only 2 corners on iOS

### ISSUE THREAD

**Issue by DenJohX** [facebook/react-native#11897] opened 2017-01-14 01:39 UTC
### Description

I need a couple of Views with border radius only on the top or bottom corners, to use as container for TextInputs (its a email/password form).

### Reproduction

Using this code:
```javascript
    // style
    inputExample: {
        borderColor: '#9b9b9b',
        backgroundColor: 'white',
        borderWidth: 1,
        borderStyle: 'solid',
        height: 50,
    },
    inputTop: {
        borderTopLeftRadius: 6,
        borderTopRightRadius: 6,
        borderBottomLeftRadius: 0,
        borderBottomRightRadius: 0,
    },
    inputBottom: {
        borderTopLeftRadius: 0,
        borderTopRightRadius: 0,
        borderBottomLeftRadius: 6,
        borderBottomRightRadius: 6,
        marginBottom: 60
    },
```

```javascript
// render
    <View style={[style.inputExample, style.inputTop]}>
    </View>
    <View style={[style.inputExample, style.inputBottom]}>
    </View>
```

The result is as expected, but with artifacts on the corners with radius:0

![screen shot 2017-01-13 at 7 30 12 pm](https://cloud.githubusercontent.com/assets/991651/21951083/34eb192e-d9c7-11e6-8ff0-d80ed6492dcb.png)

### Solution

Don't know yet

### Additional Information

* React Native version: 0.36.1
* Platform: iOS
* Operating System: MacOS

**Comment by frmrgr** [comment] 2017-01-24 11:29
I confirm, this is a nasty issue (iOS only). However in case you don't need different outer border colors/styles/widths on your blocks, you can wrap both views in a container and give it overflow:'hidden' along with needed borderRadius:6 instead of each half separately.

**Comment by farwayer** [comment] 2017-02-04 13:29
I just trapped into this. Enough of one corner  

![untitled2](https://cloud.githubusercontent.com/assets/2343101/22618786/e64487a6-eaf6-11e6-9f5a-5da4aa472e21.png)

**Comment by ismdcf** [comment] 2017-05-18 07:16
try using 
`                borderWidth: StyleSheet.hairlineWidth,
`
might work

**Comment by hramos** [comment] 2017-07-20 22:13
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/artifacts-on-view-with-borderradius-on-only-2-corners-on-ios

**Comment by malangaveuday** [comment] 2017-07-28 13:05
same issue

**Comment by zinoviev** [comment] 2017-08-21 15:48
Got some for RN 0.47 and iPhone 6

In my case, it looks like essentially same as in https://github.com/kirankalyan5/react-native-segmented-control-tab/issues/10

Folks in issue above describes how to get workaround, but source problem still exists in RN

**Comment by AlexanderPinkerton** [comment] 2017-10-03 18:27
Still an issue. Reopen and fix the bug.

**Comment by SupriyaKalghatgi** [comment] 2017-12-15 07:22
Facing similar issue
When can we expect the fix for this

**Comment by shergin** [comment] 2017-12-19 01:46
It was fixed in master.

**Comment by SupriyaKalghatgi** [comment] 2018-02-16 06:32
```
<View>
  <View
    style={{
      margin: 20,
      width: 100,
      height: 50,
      borderWidth: 1,
      borderColor: "blue",
      borderTopLeftRadius: 5,
      borderBottomLeftRadius: 5
    }}
  />
</View>
```

with RN 0.53.0
![img_0117](https://user-images.githubusercontent.com/13464885/36296019-119582b4-1311-11e8-9739-f2089ce7a3c0.PNG)

When was this fix pushed? I dont find it in RN 0.53.0 even

Reopen this issue and need fix ASAP

**Comment by ismdcf** [comment] 2018-02-21 01:55
@SupriyaKalghatgi did you try

<View>
  <View
    style={{
      margin: 20,
      width: 100,
      height: 50,
      borderWidth: **StyleSheet.hairlineWidth**,
      borderColor: "blue",
      borderTopLeftRadius: 5,
      borderBottomLeftRadius: 5
    }}
  />
</View>

**Comment by zinoviev** [comment] 2018-02-21 12:25
I was lucky enough to meet this bug in one more project. It happens only on iphone, renders fine on emulator

![image](https://user-images.githubusercontent.com/848985/36479844-3933b602-171b-11e8-9eb1-1567bb265e64.png)

**Comment by SupriyaKalghatgi** [comment] 2018-02-21 15:15
@ismdcf Whats difference between snippet i shared and that of yours?

**Comment by shergin** [comment] 2018-02-21 18:30
@zinoviev Is it happened on master? Have you tried this on Simulator with same pixel density as device?

**Comment by zinoviev** [comment] 2018-02-21 18:48
@shergin Not sure tbh, it's RN bundled with the latest expo. I will check with vanilla RN and write back here. 

My coworkers tell me it's not reproduced on iPhone 5 but happen with iPhone 6. I don't check myself yet but will try later this week.

**Comment by zinoviev** [comment] 2018-02-22 23:05
@shergin I can confirm this happens on RN 52(bundled with expo), 53.3(current master) and 54-rc3

I try iPhone 6, iPhone 6s emulators - everything is fine, blurring occurs only on real device

**Comment by zinoviev** [comment] 2018-02-22 23:31
Well, I don't sure if things I'm talking about actually related to @SupriyaKalghatgi post and probably her case may be fixed in master and worth for separate investigating. It's can be different bugs

My case with Segmented buttons as original post in this issue - you need more than one View. Repro is like:
- Put two views with border-radius side by side, they **must** share side
- They **must** have doubled border on connected side
- Run on iPhone 6+
- You have glitch

And these have the workaround: remove doubled border programmatically

**Comment by Hades1996** [comment] 2018-03-12 19:54
Still happening in 0.50.4

**Comment by waitopiggu** [comment] 2018-04-30 11:41
Still happening in 0.55.1

![img_c8915211f01a-1](https://user-images.githubusercontent.com/26673366/39425515-bfc32620-4c73-11e8-896c-418f39db254c.jpeg)

**Comment by mattijsf** [comment] 2018-05-02 07:15
Its not pretty but I found one temporary workaround which is assigning a small border radius on the corners that should not have a radius, like so:
```
  patialBorder: {
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomLeftRadius: 1.0,
    borderBottomRightRadius: 1.0,
  },
```

iPhone 5s / iOS 11 now works:
![image uploaded from ios 4](https://user-images.githubusercontent.com/706368/39510069-b8ab4b44-4de8-11e8-9170-e1f96347e089.png)

**Comment by SupriyaKalghatgi** [comment] 2018-05-08 09:41
@mattijsf whats the version of React Native you tried this example with?

**Comment by mattijsf** [comment] 2018-05-09 19:38
@SupriyaKalghatgi I tested with 0.55.3

**Comment by SupriyaKalghatgi** [comment] 2018-05-11 06:02
@hramos @shergin Its been so long waiting for this fix

**Comment by hramos** [comment] 2018-05-16 00:26
@SupriyaKalghatgi which fix? Can you link to the PR?

**Comment by SupriyaKalghatgi** [comment] 2018-05-16 06:30
@hramos You can check the above conversation
It was said that, this issue was fixed on `master`, which is not actually

**Comment by mattijsf** [comment] 2018-05-20 18:33
0.55.4 Still there.

I'm peeking at https://github.com/facebook/react-native/blob/master/React/Views/RCTBorderDrawing.m in which I think the bug is caused. But it's pretty mumbo jumbo at first sight...

**Comment by hramos** [comment] 2018-05-24 19:09
@SupriyaKalghatgi in that case, this issue is open and waiting for a fix from the community. Feel free to send a PR. Thanks!

**Comment by SupriyaKalghatgi** [comment] 2018-05-25 06:19
@hramos Yes, i know that the issue is still kept open

Without any fix!

**Comment by zinoviev** [comment] 2018-05-27 19:56
@SupriyaKalghatgi I assume you one of nativebase maintainers and if you facing this issue for segmented controls it's pretty easy to implement workaround - remove opposite to round corners border with applying a style like borderRightWidth: 0. Bleeding is happening on the side without border-radius, so just remove this side entirely and let another view be its border. You may use 1pt width view if you don't have a logical neighbor.

**Comment by mattijsf** [comment] 2018-06-06 21:08
I did create PR #19451 It would be great if some  people can confirm if it is fixed.

**Comment by mattijsf** [comment] 2018-06-11 07:41
I just tested on iOS 12 beta. Same problem. My PR fixes it there too though.

**Comment by Damirikys** [comment] 2018-07-27 16:44
Maybe someone will help it:
I just did instead of `borderLeftWidth: 4` like this `borderLeftWidth: StyleSheet.hairlineWidth * 6`.
And it works for me. 

P.S.: Tested on iPhone 6 (real device)

**Comment by gbhasha** [comment] 2018-08-06 15:05
@Damirikys issue still there if the borderRadius is more than the borderWidth.

**Comment by a-fortunato** [comment] 2018-09-07 06:54
I'm facing this same issue, only in iOS (tested on iPhone 5s). React-native version 0.55.4
```
dropDown: {
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
    borderColor: 'red',
    borderWidth: 1,
}
```

**Comment by Faolain** [comment] 2018-09-17 02:18
Same issue here on Views with React-Native version 0.57.0 and Android

**Comment by plopzer** [comment] 2018-10-04 16:50
I'm having the same artifacting issue when all 4 corners have the same border radius, but one side has a different border width.

```
<View style={{
  borderLeftWidth: 2,
  borderRadius: 2,
  borderColor: 'red',
  height: 50,
  width: 50
}}></View>
```

![border issue](https://user-images.githubusercontent.com/14914224/46489522-9a90ae00-c7d3-11e8-8fed-352c4f2936c6.jpg)

**Comment by hramos** [comment] 2018-10-04 23:30
https://github.com/facebook/react-native/pull/21208 has been merged and the fix is now in `master`.

**Closed by hramos** 2018-10-04 23:30 UTC
Labels: :clock1:PR Pending, :large_blue_diamond:iOS, Help Wanted :octocat:, Ran Commands
