### ISSUE TITLE
Incorrect gradle distrubution url prevents starting project from runnning

### ISSUE THREAD

**Issue by Schnarfengargle123** [facebook/react-native#30634] opened 2020-12-22 20:59 UTC
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.

npx react-native init MyApp contains a bug with the following file;

./android/gradle/wrapper/gradle-wrapper.properties

This file has a bug on line 3, where the distributionUrl has a lower version of gradle, which causes the npx react-native init MyApp (the default starter project), to not launch on an Android emulator, when running npx react-native run-android

Screenshot
____________

![image](https://user-images.githubusercontent.com/11248167/102932238-cd4c1d00-4497-11eb-969e-e3aa8c5db45f.png)

```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-all.zip
# distributionUrl=https\://services.gradle.org/distributions/gradle-6.2-all.zip # I don't fucking work anymore!
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```

This is my first bug report. Have a good Christmas, stay safe!

Kind regards,
Scott

Please test using the latest React Native release to make sure your issue has not already been fixed: https://reactnative.dev/docs/upgrading.html

## React Native version:
Run `react-native info` in your terminal and copy the results here.
System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 AMD Ryzen 3 1300X Quad-Core Processor
    Memory: 1.08 GB / 7.93 GB
  Binaries:
    Node: 15.2.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.0.8 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-202.7319.50.2031.7019041
    Visual Studio: 16.8.30717.126 (Visual Studio Community 2019)
  Languages:
    Java: 15.0.1
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

![image](https://user-images.githubusercontent.com/11248167/102932238-cd4c1d00-4497-11eb-969e-e3aa8c5db45f.png)

**Comment by dulmandakh** [comment] 2021-01-16 02:44
Thanks for the report, the issue is not in RN but gradle distribution. Closing the issue.

**Closed by dulmandakh** 2021-01-16 02:44 UTC
Labels: Needs: Triage :mag:
