### ISSUE TITLE
Building React Native from source doesn't work

### ISSUE THREAD

**Issue by skv-headless** [facebook/react-native#11677] opened 2016-12-30 08:14 UTC
### Description

[Building React Native from source doesn't work](https://facebook.github.io/react-native/docs/android-building-from-source.html) 
`FIRMessagingModule.java:36: error: FIRMessagingModule is not abstract and does not override abstract method onActivityResult(int,int,Intent) in ActivityEventListener`

I'm pretty sure that gradle choose old `react-native` version for `react-native-fcm`

### Reproduction

1) `react-native init AwesomeProject`
2) follow this article https://facebook.github.io/react-native/docs/android-building-from-source.html
3) `npm install react-native-fcm --save`
4) `react-native link react-native-fcm`

here https://github.com/skv-headless/rn-build-fail project with this steps.

`exclude` should work but it doesn't make any difference https://facebook.github.io/react-native/docs/android-building-from-source.html#4-making-3rd-party-modules-use-your-fork

All projects which behave same way set  `repositories { mavenCentral() }` inside their `build.gradle`

### Solution

I've added to `package.json`

`"postinstall": "find . -type f -name build.gradle -not -path \"*/react-native/*\" -not -path \"*/Examples/*\" -not -path \"*/examples/*\" -print0 -exec sed -i '' \"s/.*com.facebook.react:react-native:.*/    compile project(':ReactAndroid')/\" {} +"`

but I don't think it is the best solution.

### Additional Information

* React Native version: [master, "facebook/react-native#01af9ee8a7ec8921590e4cac29bf14267b068ddc"]
* Platform: [Android]
* Operating System: [MacOS]

**Comment by chirag04** [comment] 2016-12-30 15:15
building RN from source works for us. Looking at your project here are some pointers:

- remove this: https://github.com/skv-headless/rn-build-fail/blob/master/android/build.gradle#L20-L23

- change the ordering and naming here https://github.com/skv-headless/rn-build-fail/blob/master/android/settings.gradle#L5-L8 to 
```
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile project(':react-native-android')
    compile project(':react-native-fcm')
```

If i remember correctly calling it ReactAndroid excluded RN dependency itself.

- change these https://github.com/skv-headless/rn-build-fail/blob/master/android/settings.gradle#L5-L8 to reflect above changes. call it react-native-android instead of ReactAndroid.

**Comment by skv-headless** [comment] 2017-01-02 08:09
@chirag04 thank you for response I made changes that you suggested (I hope I did it right) https://github.com/skv-headless/rn-build-fail/commit/97649bfeef5f33ffd4713dec0d7ff1901625f431 but I have same error 😞

**Comment by ssomnoremac** [comment] 2017-01-25 15:40
@skv-headless , man I with you. I can't get rid of the 
```class FIRMessagingModule extends ReactContextBaseJavaModule implements LifecycleEventListener, ActivityEventListener``` error using every suggestion in the fcm issue and everything here. Still using a separate repo without my forked RN to build Android. Moving to RN40 soon which will allow me to avoid using my fork, but at some point I want to understand what's going on here.

**Comment by chrisbianca** [comment] 2017-02-13 20:40
I've got the same issue when trying to build from a fork of React Native 0.41.2.

Have spent the whole afternoon trying to get it to work with all sorts of different fixes suggested arounf the web but it doesn't want to work.  As soon as I switch back and point at 0.41.2 from npm it works fine, even when building from source!!

I haven't managed to figure out what's different between building from source on npm and from source on my fork...

**Comment by LucasSouzaa** [comment] 2017-03-06 19:41
Somebody with an solution ?? I'm with the same error and I can not found no one solution

**Comment by farazs** [comment] 2017-03-08 19:37
Same issue here. I suspect the issue is this chunk in build.gradle:
```
allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
```

These files exist when a version is installed from npm but not in the forked react-native:
<img width="475" alt="screen shot 2017-03-08 at 2 17 34 pm" src="https://cloud.githubusercontent.com/assets/5759678/23720431/a3a796fc-040c-11e7-8671-8b5b262b22dc.png">


I couldn't use this information to find a solution but maybe someone else can. You could add those files to your forked repo and then it would probably work but that doesn't seem correct.

**Comment by hramos** [comment] 2017-07-20 22:20
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/building-react-native-from-source-doesnt-work

**Closed by hramos** 2017-07-20 22:20 UTC
Labels: Icebox
