### ISSUE TITLE
main.jsbundle does not exist. This must be a bug with

### ISSUE THREAD

**Issue by VKGraphics** [facebook/react-native#18313] opened 2018-03-10 07:06 UTC
File /Users/admin/Library/Developer/Xcode/DerivedData/choubek-cqlacyerebnrpoacifbtrgaeuibp/Build/Intermediates.noindex/ArchiveIntermediates/choubek/BuildProductsPath/Release-iphoneos/choubek.app/main.jsbundle does not exist. This must be a bug with

![screen shot 2018-03-10 at 12 35 51 pm](https://user-images.githubusercontent.com/24429336/37239329-9f01e8f4-245f-11e8-94e7-2902c3193181.png)

**Comment by WoodyWoodsta** [comment] 2018-03-12 16:31
I'm having this issue as well. I was able to make builds before the weekend, but all of a sudden, I am getting this error. I'm not sure what has changed, unfortunately.

**Comment by hramos** [comment] 2018-03-26 21:24
Closing after seven days with no follow up from the author.

**Closed by hramos** 2018-03-26 21:24 UTC
Labels: :clipboard:Needs Repro Steps, :clipboard:No Template, :grey_question:Needs More Information, Ran Commands

**Comment by Stas-Buzunko** [comment] 2018-04-01 01:15
got this error when library was added but forgot to run npm i / yarn
npm i fixed it

**Comment by PerspectivesLab** [comment] 2018-07-16 19:19
actually its not a bug, its more likelly that xcode didnt copy main.jsbundle and the folder 'assets' produced from the bundle to the 'DerivatedData' folder, to resolve this:
in xcode, on left menu, on folder 'ressource', right click and choose 'add files to ...'
choose main.jsbundle, and afterwards 'assets' folder, 
compile and it should be fine.

you can verify by going with finder: open a finder instance then: ctrl + shift + g
paste: /Users/admin/Library/Developer/Xcode/DerivedData/choubek-cqlacyerebnrpoacifbtrgaeuibp/Build/Intermediates.noindex/ArchiveIntermediates/choubek/BuildProductsPath/Release-iphoneos/

right click on icon: choubek.app, then choose: show package contents.
if you find main.jsbundle there it worked !

**Comment by thanhcuong1990** [comment] 2018-09-15 10:45
This issue take me some days to fixed.
Here is my fix: 
Add this line to `scripts` in your package.json file. 
```
"build:ios": "react-native bundle --entry-file='index.js' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios'"
```
Now your can run the command to generate `main.jsbundle`. 
`yarn build:ios` or `npm run build:ios`

Open the Xcode -> Select project target -> add `main.jsbundle` to `Copy Bundle Resource` in Build Phases. (image below).

<img width="960" alt="screen shot 2018-09-15 at 5 37 09 pm" src="https://user-images.githubusercontent.com/3401929/45585484-2a4ae700-b90f-11e8-9a99-b3ff06ff365e.png">

**Comment by robbiemilejczak** [comment] 2018-09-27 20:16
@thanhcuong1990 thank you! My project was failing to bundle, after running that command I was able to see what was causing the bundling to fail, and then fix the issue. My build succeeds now!

I'm wondering if there is any way for XCode to report these errors? Metro was not reporting any errors when running in a dedicated terminal, I only was able to see the error when running that bundle command.

**Comment by tracinah** [comment] 2018-10-04 13:29
Request for $150.00. Complete the request now.
[image: Google Pay logo]
Money request
$ 150
Pay now
<https://pay.google.com/r/settle?tt=848DC1F4E0C680FDyxbGovShti2JEB9YrhCyZw>
Decline request
<https://pay.google.com/r/declineRequest?tt=848DC1F4E0C680FDyxbGovShti2JEB9YrhCyZw>
Money requested from Gmail · Learn how
<https://support.google.com/mail/?p=email_money>
[image: Google logo]
ID: L.848D-C1F4-E0C6-80FD
pay.google.com
<https://pay.google.com/?utm_source=wallet&utm_campaign=gmail-snippet&utm_medium=email>
 · Help Center <http://support.google.com/wallet/?p=email_help> · Protect
against fraud <http://support.google.com/wallet/?p=email_spam>

**Comment by delyar** [comment] 2019-02-06 07:03
removed Bundle React Native code and images from Build Phases in Xcode and solved my problem.
