### ISSUE TITLE
WebView does not send custom request header after the first initial page load

### ISSUE THREAD

**Issue by chiraggshah** [facebook/react-native#8693] opened 2016-07-11 12:40 UTC
The [source prop](https://facebook.github.io/react-native/docs/webview.html#source) for WebView allows for passing request headers. When the webview renders for the first time, the request headers are sent. 

But when the links within that page are clicked, the headers are not sent to the server in the request header.
Similarly, when the goBack() method is called on the WebView, the request headers are not being sent.

**Comment by dunghuynh** [comment] 2016-07-17 07:21
+1. I got the same problem with version 30-rc

**Comment by dunghuynh** [comment] 2016-07-17 07:24
And it only exists on Android. My iOS app works normally.

**Comment by ghidinelli** [comment] 2016-07-18 01:24
We are seeing the problem on iOS

**Comment by chiraggshah** [comment] 2016-08-23 12:58
Any update on this? Facing the problem on both iOS and Android. Or anyone point me in the right direction on how to fix this?

**Comment by ghidinelli** [comment] 2016-09-04 07:50
Reliable HTTP headers are important for many apps / APIs to work. Any update on this?

**Comment by karankurani** [comment] 2016-11-26 10:37
+1

**Comment by lacker** [comment] 2016-11-30 00:20
Can you provide a sample rnplay.org app that reproduces this problem?

**Comment by ghidinelli** [comment] 2016-12-01 01:17
I'll see if @chiraggshah can provide a sample from our application however he's on holiday for the next 2.5 weeks.

**Comment by peichao01** [comment] 2016-12-10 03:01
react-native-cli: 1.3.0
react-native: 0.38.1

Android has the same problem, not test iOS.

**Comment by alkhanna** [comment] 2016-12-28 21:02
I was wondering if anyone has a workaround or fix for this issue?

**Comment by evanidul** [comment] 2017-03-02 10:12
+1

**Comment by chiraggshah** [comment] 2017-04-17 18:51
@satya164 : Can you point me to the right person who possibly would have the insight on how to fix this? This is a long time issue and has not received much attention.

**Comment by chiraggshah** [comment] 2017-04-17 19:37
Or someone can guide me on how to fix it or where to start looking? That too would be a good start.

**Comment by ismdcf** [comment] 2017-06-15 09:00
+1

**Comment by hmatijevic** [comment] 2017-06-20 10:50
+1

**Comment by asimen1** [comment] 2017-07-06 11:56
+1

**Comment by xaphod** [comment] 2017-07-31 18:47
If you're iOS only, you can use this workaround (use as prop of your WebView, I assume you store the webview's url in this.state.source). Yeah, it sucks... hopefully this gets fixed soon. 

          onShouldStartLoadWithRequest={(request) => {
            console.log('**** REQUEST.url: ' + request.url + '\n**** REQUEST.navigationType: ' + request.navigationType);
            if (request.url === this.state.source) {
              return true;
            }
            // HORRENDOUS hack: RN's WebView doesn't bother keeping headers around.
            // So we always fail new requests, then update state to re-render with new URL
            // NOTE: only works on iOS
            this.setState({ source: request.url });
            return false;
          }}

**Comment by chiraggshah** [comment] 2017-07-31 19:02
@xaphod : You can use the workaround I posted above. That works for both iOS and Android

**Comment by xaphod** [comment] 2017-07-31 19:14
@chiraggshah Thanks, yes I saw your workaround. It has several disadvantages for me, chiefly hitting all endpoints twice. That's why I used a different workaround

**Comment by Red-Rock** [comment] 2017-09-08 08:31
react-native-cli: 2.0.1
react-native: 0.45.1
Facing the problem on iOS, no problem with Android.

@xaphod Your workaround is wonderful on iOS. My workaround is based on yours and I add an Array to save histories to enable goBack feature (iOS only).


    historyUrl: string[] = new Array();

    onShouldStartLoadWithRequest = (request) => {
        let curUrl = this.state.url;
        let newUrl = request.url;

        if (newUrl === curUrl) {
            return true;
        }

        this.historyUrl.push(curUrl);
        this.setState({
            url : newUrl
        });
        return false;
    }

    componentWillReceiveProps(nextProps) {
        if (nextProps.goBack) {
            if (this.historyUrl.length === 0) {
                // exit 
                ......
            } else {
                let newUrl = this.historyUrl.pop();
                
                this.setState({
                    url : newUrl
                });
            }
        }
    }

For I haven't faced the problem on Android, so I use `this.refs[WEBVIEW_REF].goBack()` to enable goBack feature for Android.

However, there isn't  `onShouldStartLoadWithRequest` function for Android. 
So if you face the problem on Android, @chiraggshah 's workaround is the best way so far, but it will results in double-request.

**Comment by enagorny** [comment] 2017-11-09 14:27
This is still issue for me. Universal workaround above works only GET requests, but doesn't on POST.

**Comment by jqn** [comment] 2017-11-09 16:26
I'm facing the same problem. It seems this bug is by design from the React team, so is it something that would likely be fixed or what's the reasoning behind it?

**Comment by chiraggshah** [comment] 2018-01-08 18:37
This issue needs to be open because certain websites do expect api-token/auth-token or certain headers to be present in each request.

**Comment by shaneosullivan** [comment] 2018-01-17 05:08
Any movement on this one?  It's a pretty bad bug that forces horrible workarounds.  Can someone on the RN team please acknowledge that this issue has been read and triaged?

**Comment by shaneosullivan** [comment] 2018-01-17 07:27
Probably the right solution is to treat the WebView as a fully controlled component, similar to how an <input> can take defaultValue and value.  

So, if the WebView gets defaultSource, it continues to behave as it does today.
If the WebView gets a source attribute, it is then a fully controlled component.  It should cancel all page transitions and provide a new callback, something like `onChange(url, type, postBody)` which can then be used up update the source attribute in the application code.

**Comment by 471685249** [comment] 2018-02-01 08:37
+1

**Comment by micaleel** [comment] 2018-03-02 18:59
+1

**Comment by oleksandrriabykh** [comment] 2018-03-07 12:21
+1

**Comment by 471685249** [comment] 2018-03-12 07:21
+1

**Comment by UsabilitySoft** [comment] 2018-03-14 17:43
+1

**Comment by jr-k** [comment] 2018-04-05 10:46
+1

**Comment by rdeift** [comment] 2018-04-10 12:28
+1

**Comment by banichols** [comment] 2018-04-14 22:34
+1

A note for anyone needing this for Basic Authentication - on iOS you can pass the username and password in as part of the URL: https://username:password@www.example.com . Sadly this doesn't work for Android.

**Comment by mausworks** [comment] 2018-05-08 16:26
+1, running into this issue as well, it's extremely frustrating. Any updates?

Given how common hybrid apps are, and how common Basic Authentication is, I honestly think this deserves more attention. Taking into consideration that this issue has been open for almost two years now &hellip;

If the intention of `source.headers` is to simply provide custom headers with the *first request*, then you could provide a `defaultHeaders?`-property, and still maintain backward compatibility. I would certainly *not expect* the "source headers" to get passed with each consecutive request.

A more "catch-all" solution would be to provide a `onRequest`-callback, where the user can modify the request as they see fit, for instance:

```jsx
<WebView 
  onRequest={req => req.addHeader('Authorization', 'Basic c2VyaW91c2x5Ond0Zg==')}
  />
```

**Comment by wuyunqiang** [comment] 2018-05-14 07:27
+1

**Comment by shopshow** [comment] 2018-06-19 05:02
facing the same issue

**Comment by Titozzz** [comment] 2018-09-26 21:59
Closing here but we are committed to fix this and keep discussing on the new repo

**Closed by Titozzz** 2018-09-26 21:59 UTC
Labels: :large_orange_diamond:Components, :large_orange_diamond:WebView, Help Wanted :octocat:
