### ISSUE TITLE
Websocket issue

### ISSUE THREAD

**Issue by sm2017** [facebook/react-native#15036] opened 2017-07-16 12:36 UTC
I have issue with this line
https://github.com/facebook/react-native/blob/master/Libraries/WebSocket/WebSocket.js#L158

Why when `ev.type === 'binary'` you consider data as base64? Currently I have issue with android (There is no issue in ios with same message from server)

https://github.com/beatgammit/base64-js/blob/master/index.js#L23 throw this error `Invalid string. Length must be a multiple of 4`

**Comment by sm2017** [comment] 2017-07-17 05:21
I send https://github.com/facebook/react-native/pull/15046 but why base64 encode/decode is required? it is big overhead

**Comment by hramos** [comment] 2017-07-17 14:45
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-07-17 14:45 UTC
