### ISSUE TITLE
 The keyboard may not show sometimes when using Oppo phone

### ISSUE THREAD

**Issue by 13160102112** [facebook/react-native#12864] opened 2017-03-10 17:05 UTC
Generally speaking,the keyboard shows when the textinput is on focus ,however,when I use Oppo phone to test my app,the keyboard may not show sometimes,and after it happens,the keyboard will not show any more otherwise exiting the app completely or long pressing the textinput which can pop up a window to make the keyboard show.

**Comment by 13160102112** [comment] 2017-03-10 17:06
My version is 0.39.0,and I have not tested any other version.

**Comment by 13160102112** [comment] 2017-03-10 17:08
My app is ok on iphone and some other android phones except Oppo phone

**Comment by 13160102112** [comment] 2017-03-10 17:10
Some people have the same problem with me

**Comment by hramos** [comment] 2017-03-10 17:23
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-03-10 17:23 UTC

**Comment by vickychu** [comment] 2017-06-09 08:42
i have the same problem

**Comment by ZHT131** [comment] 2017-06-13 12:17
I have the same problem, can you tell me how to solve it?
