### ISSUE TITLE
org.gradle.wrapper.GradleWrapperMain

### ISSUE THREAD

**Issue by karenYerevan** [facebook/react-native#18073] opened 2018-02-23 18:28 UTC
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

I want generate APK after this
cd android && ./gradlew assembleRelease

I get error 
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

**Comment by hramos** [comment] 2018-02-24 02:49
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue that meets the requirements set forth in the template. Thanks!

**Closed by hramos** 2018-02-24 02:49 UTC
