### ISSUE TITLE
RCTJSONStringify() encountered the following error: The data couldn't be written because of an error in the content of the data

### ISSUE THREAD

**Issue by giangqaz** [facebook/react-native#14410] opened 2017-06-09 02:37 UTC
I got this issue when try input emoji into a textinput that has maxlength defined
ex:
I have a text input with props: maxLength=30
I type 29 characters and then type 1 emoji, it will fire this bug.
It's ok if I type 28 character and then type 1 emoji

addition info:

- React Native version: 0.44.0
- Platform: iOS 10.3
- Development Operating System: MacOS
- Dev tools: Xcode 8.3

![simulator screen shot jun 9 2017 9 28 11 am](https://user-images.githubusercontent.com/2919890/26958854-21f58b12-4cf7-11e7-92e6-629b2db7b20a.png)

**Comment by hramos** [comment] 2017-06-09 17:06
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-09 17:06 UTC

**Comment by tautvilas** [comment] 2018-01-09 14:57
I am experiencing the same problem

**Comment by andfk** [comment] 2018-01-09 22:05
same as @tautvilas so odd that its happening almost at the same time. Did something updated and we didn't noticed that is breaking RN now?
