### ISSUE TITLE
RN 0.70 puts 1.5G+ hermes binaries into ios/Pods 

### ISSUE THREAD

**Issue by denisk20** [facebook/react-native#34643] opened 2022-09-09 07:40 UTC
### Description

After upgrading to 0.70 I've noticed that `ios/Pods` now includes huge hermes binaries in
`ios/Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework`
One is ~1GB, another is ~500MB. We store `ios/Pods` in VCS, so can't afford to push huge binaries like these. Is this approach going to stay?

<img width="423" alt="image" src="https://user-images.githubusercontent.com/3080318/189297480-efd28be5-9e42-4681-aaa1-111356731681.png">

### Version

0.70

### Output of `npx react-native info`

System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 185.20 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/denyskniazhev/.rvm/gems/ruby-2.6.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 28, 30, 31
      Build Tools: 28.0.2, 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-30 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.8 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.0 => 0.70.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Upgrade to 0.70
cd ios/
run `pod install`
check files in `ios/Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework`

### Snack, code example, screenshot, or link to a repository

see Steps to reproduce

**Comment by iBotPeaches** [comment] 2022-09-09 15:00
Do you store `node_modules` as well in VCS? Just curious since in my head `Pods` folder is comparable to `node_modules` and generally not committed.

**Comment by iBotPeaches** [comment] 2022-09-09 15:26
> I highly doubt that your `node_modules` is that big because of 1GB+ binaries inside.

Well it's 2.2gb right now, but that's because of Realm. Wasn't aware that was a recommendation of Pods. Good luck with the report.

**Comment by hanayashiki** [comment] 2022-09-10 07:12
am i waiting for 30mins for that? got to get back to 0.69

**Comment by cortinico** [comment] 2022-09-15 13:23
> After upgrading to 0.70 I've noticed that `ios/Pods` now includes huge hermes binaries in
> `ios/Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework`

This is not related to the 0.70 update. It was the same with 0.69 (and previous version).
The reason why this is happening is that 0.70 enabled Hermes by default for new projects.

You're free to use Hermes or not in your project as you wish.

> We store ios/Pods in VCS, so can't afford to push huge binaries like these.

Sadly, you're not supposed to so.
In the template we pre-generate a `.gitignore` which removes `ios/Pods` from the VCS:
https://github.com/facebook/react-native/blob/9cb716ff76e45583999b040be8a99b00f0e022e1/template/_gitignore#L63

If you decide to store the `Pods` folder on VCS, you do it at your own risks.
I could suggest tweaking your gitignore so that you ignore those specific files.

> Is this approach going to stay?

For the foreseable future, I believe yes. In the first iteration of 0.69 we actually worked on a solution that relied on distributing Hermes sources instead. We received a lot of complaints related to high build times. Therefore, we switched to prebuilt binaries (which occupies space as they need to be store locally somewhere).

> while Pods contain source files which are always the same, thus it's eligible for storing in VCS. In fact, this is what cocoapods docs [recommend](https://guides.cocoapods.org/using/using-cocoapods.html#should-i-check-the-pods-directory-into-source-control).

The Cocoapods docs suggests that it's up to every specific project to decide if the folder should be versioned or not. For React Native projects, we don't suggest so.

**Closed by cortinico** 2022-09-15 13:23 UTC
Labels: Platform: iOS, Needs: Triage :mag:

**Comment by kg-currenxie** [comment] 2022-10-30 10:04
That might be true, but when other sources potentially recommend it, its would be quite common to have users caught by this

https://guides.cocoapods.org/using/using-cocoapods.html#should-i-check-the-pods-directory-into-source-control

**Comment by codekojo** [comment] 2022-11-24 21:19
Any update?

**Comment by cortinico** [comment] 2022-11-25 12:06
> Any update?

There are no updates to be given here. That's behaving as expected. We can update the docs if needed to make it clear for users that this is the intended behavior

**Comment by muhammadali543** [comment] 2024-07-08 05:54
provide any indicator like 0%-100% for dependencies in react native. very bad experience!
