### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lefex** [facebook/react-native#15049] opened 2017-07-17 06:48 UTC
I am install RN through http://facebook.github.io/react-native/docs/integration-with-existing-apps.html, but it have errors.

Undefined symbols for architecture arm64:
  "facebook::react::customJSCWrapper()", referenced from:
      -[RCTSamplingProfilerPackagerMethod handleRequest:withResponder:] in libReact.a(RCTSamplingProfilerPackagerMethod.o)
      -[RCTDevSettings isJSCSamplingProfilerAvailable] in libReact.a(RCTDevSettings.o)
      -[RCTDevSettings toggleJSCSamplingProfiler] in libReact.a(RCTDevSettings.o)
  "facebook::react::systemJSCWrapper()", referenced from:
      -[RCTSamplingProfilerPackagerMethod handleRequest:withResponder:] in libReact.a(RCTSamplingProfilerPackagerMethod.o)
      -[RCTDevSettings isJSCSamplingProfilerAvailable] in libReact.a(RCTDevSettings.o)
      -[RCTDevSettings toggleJSCSamplingProfiler] in libReact.a(RCTDevSettings.o)
  "facebook::react::parseTypeFromHeader(facebook::react::BundleHeader const&)", referenced from:
      +[RCTJavaScriptLoader attemptSynchronousLoadOfBundleAtURL:runtimeBCVersion:sourceLength:error:] in libReact.a(RCTJavaScriptLoader.o)
  "_JSNoBytecodeFileFormatVersion", referenced from:
      +[RCTJavaScriptLoader loadBundleAtURL:onProgress:onComplete:] in libReact.a(RCTJavaScriptLoader.o)
      +[RCTJavaScriptLoader attemptSynchronousLoadOfBundleAtURL:runtimeBCVersion:sourceLength:error:] in libReact.a(RCTJavaScriptLoader.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by charpeni** [comment] 2017-07-17 14:03
Are you using React Native with CocoaPods?

**Comment by hramos** [comment] 2017-07-17 14:43
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-07-17 14:43 UTC

**Comment by RobertWSaunders** [comment] 2017-07-18 16:05
Followed the same tutorial,  http://facebook.github.io/react-native/docs/integration-with-existing-apps.html, i.e. integrating React Native components into existing applications and receiving same error as mentioned above, see mine below:

```
Undefined symbols for architecture x86_64:
  "facebook::react::customJSCWrapper()", referenced from:
      -[RCTSamplingProfilerPackagerMethod handleRequest:withResponder:] in libReact.a(RCTSamplingProfilerPackagerMethod.o)
      -[RCTDevSettings isJSCSamplingProfilerAvailable] in libReact.a(RCTDevSettings.o)
      -[RCTDevSettings toggleJSCSamplingProfiler] in libReact.a(RCTDevSettings.o)
  "facebook::react::systemJSCWrapper()", referenced from:
      -[RCTSamplingProfilerPackagerMethod handleRequest:withResponder:] in libReact.a(RCTSamplingProfilerPackagerMethod.o)
      -[RCTDevSettings isJSCSamplingProfilerAvailable] in libReact.a(RCTDevSettings.o)
      -[RCTDevSettings toggleJSCSamplingProfiler] in libReact.a(RCTDevSettings.o)
  "facebook::react::parseTypeFromHeader(facebook::react::BundleHeader const&)", referenced from:
      +[RCTJavaScriptLoader attemptSynchronousLoadOfBundleAtURL:runtimeBCVersion:sourceLength:error:] in libReact.a(RCTJavaScriptLoader.o)
  "_JSNoBytecodeFileFormatVersion", referenced from:
      +[RCTJavaScriptLoader loadBundleAtURL:onProgress:onComplete:] in libReact.a(RCTJavaScriptLoader.o)
      +[RCTJavaScriptLoader attemptSynchronousLoadOfBundleAtURL:runtimeBCVersion:sourceLength:error:] in libReact.a(RCTJavaScriptLoader.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Best steps to reproduce is to follow the tutorial posted about. I am using CocoaPods with React Native as suggested in the tutorial. Any suggestions would be greatly appreaciated.

**Comment by RobertWSaunders** [comment] 2017-07-18 16:13
Duplicate of #14925

**Comment by RobertWSaunders** [comment] 2017-07-18 16:14
Adding `BatchedBridge` as a subspec in your `Podfile` resolves the issue.

**Comment by deepax11** [comment] 2017-07-18 21:45
@RobertWSaunders thanks. You saved my night. :)

**Comment by itinance** [comment] 2018-01-11 10:10
+1 @RobertWSaunders Thx a lot.

I've added this piece to the Docs with a PR: https://github.com/facebook/react-native-website/pull/131

**Comment by RobertWSaunders** [comment] 2018-01-11 21:40
No worries! Nice work getting the PR in!
