### ISSUE TITLE
fetch request freeze app

### ISSUE THREAD

**Issue by magrinj** [facebook/react-native#9452] opened 2016-08-17 14:46 UTC
Hi everyone,

I have some problem in my app with the requests. My problem is the following:

If I go in a view that load a list of elements, when the request is awaiting and my spinner is shown, the app is totally freeze and the clicking event on the back button will be only triggered when the request is done.

I use InteractionManager everywhere in my app, my Flux implementation is `Alt.js` and my `fetch` calls are done in `async`.

I also try to use xhr, and abort the request when back button is clicked, but same problem happened, because the event is always triggered at the end of the request.

If anyone got the same issue and find a way to handle it, please answer! :)

**Comment by magrinj** [comment] 2016-08-17 14:57
If I remove `InteractionManager`, the back button seems to work better, but the navigator push animation is really slow down

**Comment by stovmascript** [comment] 2016-10-19 15:03
Hey, I have the same problem. Sadly, I haven't figured out how to fix it.

I am using `NavigationExperimental` and also the `InteractionManager` for transitioning between components which need to prefetch data. But the freezing is happening even when I just scroll a `ListView` which is `fetch`ing more items on the same screen. When the fetch is in progress I can't open the drawer menu I have in my layout - it opens right after the fetch completes.

I'm using `redux` and `redux-thunk` to make the async fetch.

@magrinj Have you had any progress with this?

**Comment by stovmascript** [comment] 2016-10-19 15:16
It might be useful to list the relevant dependencies, so here they are:

```
"dependencies": {
	...
	"react": "15.3.2",
	"react-native": "0.35.0",
	"react-native-blur": "1.0.1",
	"react-native-camera": "pelmet/react-native-camera#c33f484",
	"react-native-device-detection": "0.1.3",
	"react-native-device-info": "0.9.5",
	"react-native-dismiss-keyboard": "1.0.0",
	"react-native-gallery": "pelmet/react-native-gallery#martins/initial-list-size-fix",
	"react-native-htmlview": "pelmet/react-native-htmlview#fcbb0d0",
	"react-native-keyboard-aware-scrollview": "1.1.1",
	"react-native-keychain": "0.3.2",
	"react-native-linear-gradient": "1.5.12",
	"react-native-orientation": "yamill/react-native-orientation#05d0f60",
	"react-native-push-notification": "zo0r/react-native-push-notification",
	"react-native-randombytes": "2.1.0",
	"react-native-sglistview": "0.3.2",
	"react-native-share": "1.0.13",
	"react-native-tableview": "madlandev/react-native-tableview#rn-0.33-compatability",
	"react-native-vector-icons": "2.0.3",
	"react-native-version": "2.0.1",
	"react-native-view-shot": "1.4.0",
	"react-redux": "4.4.5",
	"redux": "3.5.2",
	"redux-persist": "3.2.2",
	"redux-persist-transform-encrypt": "0.1.2",
	"redux-thunk": "2.1.0",
	"rn-nodeify": "6.0.1",
	...
},
"devDependencies": {
	...
	"babel-plugin-transform-decorators-legacy": "^1.3.4",
	"babel-preset-react-native": "^1.9.0",
	"react-native-code-push": "^1.14.4-beta",
	...
}
```

**Comment by magrinj** [comment] 2016-10-20 07:22
@stovmascript I still have the same issue :/ Sadly, I didn't find anything to solve it for the moment

**Comment by magrinj** [comment] 2016-11-17 16:18
Anyone ?

**Comment by nsmag** [comment] 2017-03-08 08:29
I have the same problem. Has anyone found any solution yet?

**Comment by gungungun93** [comment] 2017-03-08 08:31
same here

**Comment by komaldeep** [comment] 2017-03-17 10:27
I am facing same problem.... Anybody found solution for it

**Comment by hramos** [comment] 2017-03-31 18:37
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-03-31 18:37 UTC
