### ISSUE TITLE
How to bind multiple data using DeviceEventEmitter?. 

### ISSUE THREAD

**Issue by RiyasMeeran** [facebook/react-native#14098] opened 2017-05-22 13:40 UTC
![screenshot_20170522-190619](https://cloud.githubusercontent.com/assets/16999176/26311546/4fa8f518-3f22-11e7-95a4-dae2f8eec6d5.jpg)
 Like mic volume bind to view. but i got error ("Client is busy with a request").

```
<View>
 <Text style={styles.instructions}>
          Mic Level {this.state.micLevel}
        </Text>
</View>
```

```
DeviceEventEmitter.addListener('onMicLevelChange', (level) => {
          event.setState({micLevel:data});
        });
```

http://i.imgur.com/zjUjgY5.jp

**Comment by hramos** [comment] 2017-05-22 17:57
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-05-22 17:57 UTC
