### ISSUE TITLE
Failed to load bundle localhost 8081 on 0.59 version

### ISSUE THREAD

**Issue by Gapur** [facebook/react-native#24051] opened 2019-03-20 06:17 UTC
<img width="937" alt="Screen Shot 2019-03-20 at 12 12 33 PM" src="https://user-images.githubusercontent.com/10502684/54662984-0c527f00-4b0a-11e9-9bad-6ebcc7e8d379.png">

React: 16.8.4;
React-native: 0.59

**Comment by bartolkaruza** [comment] 2019-03-20 08:02
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗

**Closed by bartolkaruza** 2019-03-20 08:02 UTC
Labels: Type: Bug Report

**Comment by 40for** [comment] 2019-03-23 23:54
I have same issue. I am using react native cli just like getting started guide says. I run following commands:

- npm install -g react-native-cli
- react-native init AwesomeProject
- cd AwesomeProject && react-native run-ios

Then iPhone emulator starts up, app launches for the second and then it throws the same error @Gapur showed before. 

I found this [issue](https://github.com/facebook/react-native/issues/18962), which suggest downgrade metro-react-native-babel-preset to babel-preset-react-native. However in [here](https://www.npmjs.com/package/babel-preset-react-native) it says that it's deprecated. I still tried it, and restarted my computer multiple times, but I still haven't fixed it yet. What should I do?

**Comment by bartolkaruza** [comment] 2019-03-24 12:01
Just to help you debug this; The error message indicates that the React Native packager cannot be reached by the app. In debug, the app is installed on your simulator and then the app tries to fetch the javascript bundle from a node.js server (the packager) that runs on your computer. If that server is not running, or is not reachable because of some other issues, you will see this error. Try starting the packager manually, using ```yarn start``` in the root of your app project. Next, to debug any network issues between your simulator and your computer, try opening http://localhost:8081/debugger-ui on the simulators Safari browser. If the page cannot be loaded, something is wrong on the networking side of the simulator or the host machine.

**Comment by grewal25** [comment] 2019-03-24 23:20
> I have same issue. I am using react native cli just like getting started guide says. I run following commands:
> 
> * npm install -g react-native-cli
> * react-native init AwesomeProject
> * cd AwesomeProject && react-native run-ios
> 
> Then iPhone emulator starts up, app launches for the second and then it throws the same error @Gapur showed before.
> 
> I found this [issue](https://github.com/facebook/react-native/issues/18962), which suggest downgrade metro-react-native-babel-preset to babel-preset-react-native. However in [here](https://www.npmjs.com/package/babel-preset-react-native) it says that it's deprecated. I still tried it, and restarted my computer multiple times, but I still haven't fixed it yet. What should I do?

same here, was working fine till yesterday. Have you found any solution?

**Comment by Gapur** [comment] 2019-03-25 07:07
I wanted to use React Native Hooks. When I have updated RN version to 0.59 and I will have this error. So I couldn't fix then I changed RN version to 0.58. It is sad.

**Comment by 40for** [comment] 2019-03-25 14:47
Thanks @bartolkaruza for an explanation! It did work! @grewal25 I run command `react-native start` and after I run `react-native run-ios`

**Comment by bartolkaruza** [comment] 2019-03-31 15:04
Hey, I'm locking this issue as it will keep catching unrelated comments like
> I wanted to use React Native Hooks. When I have updated RN version to 0.59 and I will have this error. So I couldn't fix it then I changed RN version to 0.58. It is sad.
@Gapur I'm sorry you were experiencing issues with regards to upgrading. We're actively working on improving that experience and if you have specific issues, please report them in one issue report per issue with some reproduction information.
