### ISSUE TITLE
App crashes on android when new arch is enabled

### ISSUE THREAD

**Issue by aleluiah** [facebook/react-native#34207] opened 2022-07-17 18:17 UTC
### Description

C:\Windows\System32>adb logcat *:S ReactNative:V ReactNativeJS:V
--------- beginning of crash
--------- beginning of system
--------- beginning of main
07-17 18:55:24.428  2667  2775 E ReactNativeJS: Invariant Violation: ViewPropTypes has been removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'., js engine: hermes
07-17 18:55:24.670  2667  2775 E ReactNative: C:/Cliqueon/node_modules/react-native/ReactCommon/react/renderer/uimanager/bindingUtils.cpp:29: function getModule: assertion failed (moduleAsValue.isObject())
07-17 18:55:24.670  2667  2775 F ReactNative: C:/Cliqueon/node_modules/react-native/ReactCommon/react/renderer/uimanager/bindingUtils.cpp:29: function getModule: assertion failed (moduleAsValue.isObject())
07-17 18:57:22.517  3022  3091 E ReactNativeJS: Invariant Violation: ViewPropTypes has been removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'., js engine: hermes
07-17 18:57:22.743  3022  3091 E ReactNative: C:/Cliqueon/node_modules/react-native/ReactCommon/react/renderer/uimanager/bindingUtils.cpp:29: function getModule: assertion failed (moduleAsValue.isObject())
07-17 18:57:22.743  3022  3091 F ReactNative: C:/Cliqueon/node_modules/react-native/ReactCommon/react/renderer/uimanager/bindingUtils.cpp:29: function getModule: assertion failed (moduleAsValue.isObject())
07-17 19:04:48.569  3419  3488 E ReactNativeJS: Invariant Violation: ViewPropTypes has been removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'., js engine: hermes
07-17 19:04:48.804  3419  3488 E ReactNative: C:/Cliqueon/node_modules/react-native/ReactCommon/react/renderer/uimanager/bindingUtils.cpp:29: function getModule: assertion failed (moduleAsValue.isObject())
07-17 19:04:48.804  3419  3488 F ReactNative: C:/Cliqueon/node_modules/react-native/ReactCommon/react/renderer/uimanager/bindingUtils.cpp:29: function getModule: assertion failed (moduleAsValue.isObject())

### Version

0.69.1

### Output of `npx react-native info`

C:\Windows\System32>adb logcat *:S ReactNative:V ReactNativeJS:V
--------- beginning of crash
--------- beginning of system
--------- beginning of main
07-17 18:55:24.428  2667  2775 E ReactNativeJS: Invariant Violation: ViewPropTypes has been removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'., js engine: hermes
07-17 18:55:24.670  2667  2775 E ReactNative: C:/Cliqueon/node_modules/react-native/ReactCommon/react/renderer/uimanager/bindingUtils.cpp:29: function getModule: assertion failed (moduleAsValue.isObject())
07-17 18:55:24.670  2667  2775 F ReactNative: C:/Cliqueon/node_modules/react-native/ReactCommon/react/renderer/uimanager/bindingUtils.cpp:29: function getModule: assertion failed (moduleAsValue.isObject())
07-17 18:57:22.517  3022  3091 E ReactNativeJS: Invariant Violation: ViewPropTypes has been removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'., js engine: hermes
07-17 18:57:22.743  3022  3091 E ReactNative: C:/Cliqueon/node_modules/react-native/ReactCommon/react/renderer/uimanager/bindingUtils.cpp:29: function getModule: assertion failed (moduleAsValue.isObject())
07-17 18:57:22.743  3022  3091 F ReactNative: C:/Cliqueon/node_modules/react-native/ReactCommon/react/renderer/uimanager/bindingUtils.cpp:29: function getModule: assertion failed (moduleAsValue.isObject())
07-17 19:04:48.569  3419  3488 E ReactNativeJS: Invariant Violation: ViewPropTypes has been removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'., js engine: hermes
07-17 19:04:48.804  3419  3488 E ReactNative: C:/Cliqueon/node_modules/react-native/ReactCommon/react/renderer/uimanager/bindingUtils.cpp:29: function getModule: assertion failed (moduleAsValue.isObject())
07-17 19:04:48.804  3419  3488 F ReactNative: C:/Cliqueon/node_modules/react-native/ReactCommon/react/renderer/uimanager/bindingUtils.cpp:29: function getModule: assertion failed (moduleAsValue.isObject())

### Steps to reproduce

![git1](https://user-images.githubusercontent.com/65899491/179419339-de83459f-43ff-4abc-bae7-7630358e07b3.jpg)

### Snack, code example, screenshot, or link to a repository

![git1](https://user-images.githubusercontent.com/65899491/179419349-47b37e8e-3ccd-4df0-99b8-774a949e16ba.jpg)

**Comment by aleluiah** [comment] 2022-07-17 18:53
@waqas19921 hi, were you still getting the error with hermes disabled ?

**Comment by cortinico** [comment] 2022-07-29 16:39
Closing as a duplicate of #33734

**Closed by cortinico** 2022-07-29 16:39 UTC
Labels: Platform: Android, Needs: Triage :mag:
