### ISSUE TITLE
android RCTDeviceEventEmitter does not work (only work debug )

### ISSUE THREAD

**Issue by py110** [facebook/react-native#6236] opened 2016-03-02 02:03 UTC
in my java ,i send event to js

```
 WeChatModule.reactApplicationContext.getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class)
                    .emit("finishedPay", params);
```

in js 

```
componentWillMount: function() {
    DeviceEventEmitter.addListener('finishedPay', function(e){
       console.log(e);
        }
      })
  },

  componentWillUnmount: function() {
    DeviceEventEmitter.removeAllListeners("finishedPay");
  },
```

the code in debug  status is work,the normal status it does not work

rn  version 0.20

**Comment by grabbou** [comment] 2016-03-03 13:38
I am using similar functionality internally and all works well. Are you sure event is emitted from native code? Have you tried putting a simple log above it to check if that line is hit?

**Comment by brentvatne** [comment] 2016-03-06 20:07
@py110 - can you post the full code for your WeChatModule as well? This should work. A style comment -- you might want to create a public method on WeChatModule called `finishPayment` or something like that which accepts params and handles emitting the event using `getReactApplicationContext()`

**Comment by brentvatne** [comment] 2016-03-06 21:10
On second thought I am going to close this issue for now, we cannot debug with the information that has been given because this works for us (you can try the NetInfo module for example and you will see that this exact behaviour works as expected on Android in debug or otherwise). Please reopen an issue with a project that we can reproduce the issue in.

**Closed by brentvatne** 2016-03-06 21:10 UTC
Labels: Needs more information

**Comment by peichao01** [comment] 2017-01-04 11:54
i got the same error in release mode, install released APK
