### ISSUE TITLE
Could not install the app on the device, read the error above for details.

### ISSUE THREAD

**Issue by Abdul-majid-ashrafi** [facebook/react-native#14129] opened 2017-05-23 13:14 UTC
react-native run-android
Starting JS server...

Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

adb devices
List of devices attached
T062808LX3 device

**Comment by godspeedelbow** [comment] 2017-05-23 16:10
Did you turn on USB debugging on your device?

**Comment by hramos** [comment] 2017-05-23 16:18
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-05-23 16:18 UTC

**Comment by labidiaymen** [comment] 2017-10-09 10:33
For windows users ,run "react-native run-android" via cmd as admin
