### ISSUE TITLE
if remote js debug is enabled, doing a reload (manually on hot/live) hang up the app on android. v. 0.47.1

### ISSUE THREAD

**Issue by bgiavotto** [facebook/react-native#15339] opened 2017-08-02 18:49 UTC
### Is this a bug report?

yes

### Have you read the Bugs section of the How to Contribute guide?

yes

### Environment

1. Please see issue number #15298 it is not fixed in version 0.47.1

Then, specify:

- Target Platform:
see issue nr. #15298

- Development Operating System:
see issue nr. #15298

- Build tools:
see issue nr. #15298
### Steps to Reproduce

(Write your steps here:)

### Expected Behavior

see issue nr. #15298

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by rajsuvariya** [comment] 2017-08-03 07:23
+1

**Comment by hramos** [comment] 2017-08-03 19:11
Duplicate of #15298

**Closed by hramos** 2017-08-03 19:11 UTC
