### ISSUE TITLE
undefined is not an object (evaluting 'validAttributes.style')

### ISSUE THREAD

**Issue by qiaoyd523** [facebook/react-native#6028] opened 2016-02-19 08:53 UTC
here is the code : 

```jsx
const style = {
  marginTop: 11.8,
  marginLeft: marginLeft,
  marginRight: marginRight,
  width: width
};
/// ...       
itemviews.push(
  <TouchableHighlight 
    underlayColor="#00000000" 
    key={i} 
    style={style}
    onPress={this.onPressunCoverList.bind(this, moneyDict.gameId, moneyDict.userName)}>
      <Image 
        style={[styles.noredimageStyle, {width: width}]} 
        source={require('../../image/noRedPacket.png')}/>
  </TouchableHighlight>
)
```

If i click the Image on a android device, it will show this: "undefined is not an object (evaluting 'validAttributes.style')", but iOS device is ok.

**Comment by Kureev** [comment] 2016-02-19 09:32
@qiaoyd523 can you please provide a body of the `onPressunCoverList`?

**Comment by qiaoyd523** [comment] 2016-02-20 02:23
here is the code  onPressunCoverList:function(gameId,userName){
        this.props.navigator.push({
            title:'Redpacket',
            component:RedpacketList,
            passProps: {
                gameId:gameId,
                type:0,
                userName:userName
            }
        })
    },

**Comment by Kureev** [comment] 2016-02-20 11:11
From what I see, you shouldn't encounter this error. Can you tell me what happened before this error? Have you tried to upgrade your react-native version?

**Comment by qiaoyd523** [comment] 2016-02-22 01:58
@Kureev I just click this image,then the error appeared on android device. My react-native is 0.1.7 and i will try to upgrade it .

**Comment by Kureev** [comment] 2016-02-22 02:29
cc @mkonicek

**Comment by staradayev** [comment] 2016-02-26 14:39
Hello! I had the same issue. 

There are pictures containing ListView, and press event assigned to everyone:

        ```
        <TouchableHighlight onPress={this.onPressPicture.bind(this, image)} key={image.id + '_tocheble'}>
          <Image key={image.id} style={[styles.image, this.calculateSize()]} source={{uri: 'http://dev.pics.care/media/'+image.picture_url}}  >
              <View style={styles.description}>
                   ............
              </View>           
          </Image>
         </TouchableHighlight>
```

Also press on picture handler is:

onPressPicture(image) {
    this.props.navigator.push({
        name: image.name,
        component: onPressPicture(image) {
    this.props.navigator.push({
        name: image.name,
        component: PictureDetailsView,
        passProps: {
          pictureId: image.id,
        },
    });
  },
        passProps: {
          pictureId: image.id,
        },
    });
  }

iOS works perfect, Android cause an error. Also i tied to do the PictureDetailsView fresh and blank. Animation from Navigator configureScene removed too.

**Comment by staradayev** [comment] 2016-02-26 14:43
I have read tree above. I updated my react-native to the latest 0.20.0 version. Nothing changed. I still see this issue.

**Comment by mkonicek** [comment] 2016-03-01 19:17
Can you please debug why this happens (do you see a stack trace in the logs for example)?

**Comment by staradayev** [comment] 2016-03-03 18:49
![s60303-194355](https://cloud.githubusercontent.com/assets/5321206/13505238/0099a53a-e181-11e5-937a-2bb9c381b324.jpg)

Here is screenshot from Meizu M2, (android 5.1 flume), also the same i saw on latest nexus (android 6.0.1) and android emulator (Android 21).

P.S. Padding at the bottom i have seen only on Meizu.

**Comment by Kureev** [comment] 2016-03-03 18:53
If I understand correct, then you're using a style attributes which are implemented for iOS only. Can you share a style you supply to the `<Image />`?

**Comment by staradayev** [comment] 2016-03-03 18:53
A few details:

- this issue occurs only on picture click (tap)
- I tried to clear all styles of picture, still exist
- Moving onPress binding from the covering TouchableHighlight to nested image doesn't have result also.

**Comment by staradayev** [comment] 2016-03-03 18:57
I didn't use any styles except calculated width and height.

`<Image key={image.id} style={[styles.image, this.calculateSize()]} source={{uri: 'http://dev.pics.care/media/'+image.picture_url}}  >`

styles.image is empty
calculateSize() return {width: size, height: size}

**Comment by Kureev** [comment] 2016-03-03 19:02
Well, then your code looks good to me and it means that the issue could be in the cache. Run the packager with a `--reset-cache` flag, that may solve your problem.

**Comment by staradayev** [comment] 2016-03-03 21:37
Finally I founded case, for reproduce tis issue.

**This construction will cause an error on Android:**

`<TouchableHighlight onPress={this.onPressPicture.bind(this, image)}>
      <Image>
          <View>
          </View>           
      </Image>
</TouchableHighlight>`

But,
**This construction works well on both:**

`<TouchableOpacity onPress={this.onPressPicture.bind(this, image)}>
      <Image>
          <View>
          </View>           
      </Image>
</TouchableOpacity>`

Question, why TouchableHighlight cause an error?

**Comment by qiaoyd523** [comment] 2016-03-07 03:55
@Kureev I replace the TouchableHighlight with TouchableOpacity,then it work well.Thanks @staradayev

**Comment by staradayev** [comment] 2016-03-07 10:36
@qiaoyd523 you are welcome :)

**Comment by MaximLeonov** [comment] 2016-03-11 16:33
Changing TouchableHighlight to TouchableOpacity fixed this issue for Image component. But for Animated.Image issue still appears while changing height property of image.

**Comment by everfire130** [comment] 2016-03-23 08:36
@MaximLeonov I also found that the Animated.Image issue.Now I use Animated.View to wrap Image...  So,if you want to use TouchableHighlight,you can do like this  @qiaoyd523 
```
< TouchableHighlight>
  <View>
    <Image/>
  </View>
</TouchableHighlight>
```

**Comment by finalquest** [comment] 2016-03-23 12:21
Im also facing this error when trying to set native props in a touchableOpacity button.

setNativeProps({style:{backgroundColor: Color.GREEN}});

**Comment by mkonicek** [comment] 2016-07-29 23:15
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/undefined-is-not-an-object-evaluting-validattributesstyle

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Closed by mkonicek** 2016-07-29 23:15 UTC
Labels: GH Review: review-needed, Icebox
