### ISSUE TITLE
Dangerous permissions are being auto granted even on android M and above.

### ISSUE THREAD

**Issue by AggarwalAnkit** [facebook/react-native#14553] opened 2017-06-16 10:50 UTC
Whatever dangerous permission I add in Android Manifest file and run the app in emulator or mobile having SDK version >= M, I get that permission automatically. Even if I manually switch off the permission I PermissionsAndroid.request() returns true for that permission. I am following the [example code](https://facebook.github.io/react-native/docs/permissionsandroid.html#example) from ReactNative docs. I am using exact code sample and haven't added anything extra.

**Comment by hramos** [comment] 2017-06-16 20:14
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-16 20:14 UTC

**Comment by franciscocpg** [comment] 2017-07-28 14:07
For someone else with the same problem reported here, I managed to solve this problem by changing `android:targetSdkVersion` at `AndroidManifest.xml` file to 23 or higher **and** `targetSdkVersion` at `build.gradle` file to 23 or higher.

**Comment by AggarwalAnkit** [comment] 2017-07-31 05:14
@franciscocpg I want to target my app to lower versions also (Kitkat and above). Is there any solution for that?

**Comment by franciscocpg** [comment] 2017-07-31 11:54
Yes, just set `minSdkVersion`

More info:
https://developer.android.com/guide/topics/manifest/uses-sdk-element.html
