### ISSUE TITLE
Creating Native UI Component per docs results in duplicate symbols error

### ISSUE THREAD

**Issue by faalsh** [facebook/react-native#12404] opened 2017-02-15 18:12 UTC
### Description

I'm trying to create a native UI component as per the documentation http://facebook.github.io/react-native/releases/0.42/docs/native-components-ios.html

But I got error 

```
duplicate symbol _OBJC_CLASS_$_RCTMapManager in:
   /Library/Developer/Xcode/DerivedData/AwesomeProject-cmpcijgfhosaanaxtdllprpmiwll/Build/Intermediates/AwesomeProject.build/Debug-iphonesimulator/AwesomeProject.build/Objects-normal/x86_64/RCTMapManager.o
   /Library/Developer/Xcode/DerivedData/AwesomeProject-cmpcijgfhosaanaxtdllprpmiwll/Build/Products/Debug-iphonesimulator/libReact.a(RCTMapManager.o)
duplicate symbol _OBJC_METACLASS_$_RCTMapManager in:
    /Library/Developer/Xcode/DerivedData/AwesomeProject-cmpcijgfhosaanaxtdllprpmiwll/Build/Intermediates/AwesomeProject.build/Debug-iphonesimulator/AwesomeProject.build/Objects-normal/x86_64/RCTMapManager.o
  /Library/Developer/Xcode/DerivedData/AwesomeProject-cmpcijgfhosaanaxtdllprpmiwll/Build/Products/Debug-iphonesimulator/libReact.a(RCTMapManager.o)
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Reproduction

I've created a new project using react-native command, opened the Xcode project and added a new file RCTMapManager.m

```
// RCTMapManager.m
#import <MapKit/MapKit.h>

#import <React/RCTViewManager.h>

@interface RCTMapManager : RCTViewManager
@end

@implementation RCTMapManager

RCT_EXPORT_MODULE()

- (UIView *)view
{
  return [[MKMapView alloc] init];
}

@end

``` 

### Additional Information

* React Native version: 0.42
* Platform: iOS
* Operating System: MacOS Sierra, Xcode Version 8.2.1

**Comment by shergin** [comment] 2017-02-16 05:17
So, it is because RN already has a class with this name: https://github.com/facebook/react-native/blob/master/React/Views/RCTMapManager.h

**Comment by hramos** [comment] 2017-02-17 20:02
^ correct. Closing as this is working as intended.

**Comment by faalsh** [comment] 2017-02-17 20:11
@shergin Many thanks for the heads up.
@hramos Do you think the documentation should be corrected?

**Comment by hramos** [comment] 2017-02-17 20:23
Oh I see, the documentation can certainly be improved here.

**Closed** 2017-03-08 17:53 UTC
Labels: Documentation
