### ISSUE TITLE
Error: "react-native run-ios" not working even for sample apps, AwesomeProject

### ISSUE THREAD

**Issue by bluej-21** [facebook/react-native#9391] opened 2016-08-13 21:16 UTC
I'm using a Macbook air to test run some application for ios. the react-native run-ios does not seem to work appropriately as I always get the "unable to connect to server... do npm start" error message as soon as I open up the app on the emulator. 
I've tried this again for facebook's example app, AwesomeProject and I still got the same error. 
The react-native version I am using is 0.30.0 and the react-native-cli is 1.0.0

**Comment by stoffern** [comment] 2016-08-13 21:24
@bluej-21 do you have watchman installed?
https://facebook.github.io/react-native/docs/getting-started.html

**Comment by bluej-21** [comment] 2016-08-14 04:03
yes, I do. Also it seems like the packager is running, it'll display the <start> messages on the packager but it doesn't seem to display the <end> messages.

**Comment by tjfi222** [comment] 2016-08-14 21:17
I also am having trouble running the AwesomeProject example. I've looked through every Github/Stack solutions and none of them work.  Using fresh installs of literally everything.

:CFBundleIdentifier does not exist

Please advise! 
.

**Comment by itinance** [comment] 2016-08-15 13:14
For me everything is working fine. 
Have you tried to reset the packager?
`node node_modules/react-native/local-cli/cli.js start --reset-cache`

Or the hard way with reinstalling everything and restarting watchman also:
`rm -rf node_modules/ && npm cache clear && watchman watch-del-all && npm i`

Is network working well? Can you open the index.js-File in your browser?
Something like this: http://localhost:8081/index.ios.js?platform=ios&dev=true&minify=false

Anyhow, let's compare versions:

within the Project after "react-native init AwesomProject":
```
$ react-native --version
react-native-cli: 1.0.0
react-native: 0.31.0

```
```
$ node -v
v6.3.1

```
```
$ uname -a
Darwin macbook.fritz.box 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64

(OSX El Capitain Version 10.11.6 (15G31))
```
XCode Version 7.3.1 (7D1014)

**Comment by nicholasstephan** [comment] 2016-09-23 19:28
I've run into this issue since upgrading to Xcode 8.

**Comment by ericvicenti** [comment] 2016-10-24 22:35
I'm on Xcode 8 and I haven't seen this problem yet. Is it still causing troubles for people?

**Comment by ostigley** [comment] 2016-11-01 04:43
I have a similar problem.  I don't get an error; instead it just hangs.  Nothing happens.  Only since upgrading Xcode and OSX

**Comment by blackburnian** [comment] 2016-11-02 22:04
Earlier today watchman was not reloading my JS when I made changes.  Tried fresh install of watchman, react-native-cli, rebooting, etc.  Now I’m experiencing a similar issue to @ostigley .  In my current react native project when I run `react-native run-ios`, nothing happens.  No errors.  Just hangs.

Tried creating a new project with `react-native init AwesomeProject`, and this hangs as well.

@itinance I tried running node node_modules/react-native/local-cli/cli.js start --reset-cache, and this hangs as well.

Tried running `rm -rf node_modules/ && npm cache clear && watchman watch-del-all && npm i`, and this hangs on the watchman command.

So something seems to be wrong with my watchman.  I might be related to the Xcode and or OS update (recently updated to macOS 10.12.1 and Xcode 8), but not sure.

```
watchman -v
4.7.0
```

```
react-native -v
react-native-cli: 1.2.0
react-native: 0.34.1
```

```
node -v
v5.7.1
```

Any ideas?

**Comment by ostigley** [comment] 2016-11-02 22:11
@blackburnian I found the problem was with watchman.  Fixed it here: 
https://github.com/facebook/watchman/issues/381#issuecomment-257669560

**Comment by vikrampanwar** [comment] 2017-04-16 13:05
I tried many github examples but non of them is working with latest react native installation, but my own made projects are working fine

**Comment by hepiska** [comment] 2017-06-16 07:58
@vikrampanwar  get same issue, have u update your node to node 8?

**Comment by hramos** [comment] 2017-08-03 17:35
Let's merge this into a more recent issue, for clarity.

**Comment by hramos** [comment] 2017-08-03 17:35
Duplicate of #14447

**Closed by hramos** 2017-08-03 17:35 UTC
Labels: iOS

**Comment by hramos** [comment] 2017-08-03 17:58
Duplicate of #14423
