### ISSUE TITLE
upgrade React Native to 0.57.3 TypeError: undefined is not a function (evaluating 'instance.render()')

### ISSUE THREAD

**Issue by yaoyingjiang** [facebook/react-native#21856] opened 2018-10-19 02:06 UTC
- [ ] Review the documentation: https://facebook.github.io/react-native
  - [ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
 React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 134.06 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.4.0 - /usr/local/bin/node
      Yarn: 1.7.0 - ~/.yarn/bin/yarn
      npm: 5.8.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 20.0.0, 23.0.1, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3
        API Levels: 21, 22, 23, 24, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728 
      react-native: 0.57.3 => 0.57.3 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
upgrade React Native to 0.57.3 , Android Studio build project finish. i run android complete but when App start show a red box about 
    TypeError: undefined is not a function (evaluating 'instance.render()')

    This error is located at:
        in RootSiblingsWrapper (at AppContainer.js:112)
        in RCTView (at View.js:44)
        in AppContainer (at renderApplication.js:33)

![image](https://user-images.githubusercontent.com/19427456/47193628-909bad00-d386-11e8-8c21-0ae0f7d988b8.png)
![image](https://user-images.githubusercontent.com/19427456/47193661-b0cb6c00-d386-11e8-9995-b20a9d656453.png)

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, share a project, or     share an app that reproduces the issue using https://snack.expo.io/. Please follow the guidelines for providing a MCVE: https://stackoverflow.com/help/mcve

**Comment by rahimasgari** [comment] 2018-11-13 15:11
I have the same problem. 
any solution?

**Comment by tomershohet** [comment] 2018-11-15 15:30
Same here

**Comment by jerinho** [comment] 2018-11-22 05:55
is react native dead already. honestly i think it's facebook should be dead. why invent a broken tools that not solves our problem but kills people? fuck you !!

**Comment by LingYun** [comment] 2018-12-03 07:30
> Same on RN 0.57.5 . Maybe it is some way related to some unresolved old dependencies.
> 
> UPD: Solved this, by deleting android/ and ios/ folders, making `react-native eject` and `react-native link` again.

@NelGarbuzova Can you tell me your specific operation? I have the same problem now. Thank you very much!

**Comment by NelGarbuzova** [comment] 2018-12-03 07:36
@LingYun i just deleted android/ and ios/ folders, then run `react-native eject` , then `react-native link`, then `react-native run-android `. And that's all. Everything start to work.

**Comment by duchunter** [comment] 2018-12-11 10:18
i dunno how but yarn add @babel/runtime or npm i -s @babel/runtime works for me

**Comment by abdulsalam90** [comment] 2019-01-01 14:31
@duchunter did not worked.

**Comment by huytran123** [comment] 2019-01-02 08:32
Use this version to resolve this error :): 
    "react": "16.6.3",
    "react-native": "0.58.0-rc.2"

**Comment by rosebless** [comment] 2019-01-09 17:50
any idea? or any one know the cause of problem? i can't solve this problem. i try all comment but not work

**Comment by ferrannp** [comment] 2019-03-19 14:04
We are going to close this issue as it seems to be out of date. Please try to update to latest React Native 0.59.x and we can reopen this if the issue still persists.

**Closed** 2019-03-19 14:05 UTC
Labels: Resolution: Needs Repro, Type: Bug Report
