### ISSUE TITLE
[babel] custom plugin not called with invalid module path

### ISSUE THREAD

**Issue by tleunen** [facebook/react-native#6118] opened 2016-02-24 05:59 UTC
Hi,
I'm the author of the babel plugin [module-alias](https://github.com/tleunen/babel-plugin-module-alias), allowing users use aliases for the import/require path to their files.

I tried to use it in a React Native application, but it doesn't work. From what I've seen, the plugin is not called unless the initial path is valid (which is impossible when you want to use aliases).

Because I don't see any logs of the plugin being used when the path is incorrect, I guess React-Native does make some testing before bundling the code (?) Is a feature like path aliases already in react-native? Is there anything we can do to make my plugin work with react-native?

**Comment by mroswald** [comment] 2016-03-01 13:02
you can simple write
```
/*
 * @providesModule NAMEOFYOURMODULE
 */
```

on top of your file which will make it "importable" under this alias "NAMEOFYOURMODULE". Does that help in your case?

**Comment by vitorbal** [comment] 2016-03-01 13:15
@mroswald Thanks, that actually is super useful. Was it a conscious decision to not mention it in the docs? or would it be possible to add it to the docs somewhere?

**Comment by mroswald** [comment] 2016-03-01 13:35
@vitorbal documentation on how the haste resolver works was hard to find out for me. That's a part of the project which is quite not well documented as you stated. If anybody has more information, I'd really appreciate that

**Comment by tleunen** [comment] 2016-03-02 15:52
@mroswald Oh I didn't know we could use that "internal" system for our code.

I guess it's a nice workaround, but maybe we could have a way to choose to run our plugins before or after the native plugins?

**Comment by satya164** [comment] 2016-03-02 20:26
cc @martinbigio

**Comment by martinbigio** [comment] 2016-03-03 04:33
Yeah, the packager supports "haste" modules so I'm not sure if the module-alias plugin would provide much value.

Wow, you're right, there's no documentation about the module system we support :'(. Maybe we could add a section here: https://facebook.github.io/react-native/docs/javascript-environment.html#content

cc @vjeux

**Comment by vjeux** [comment] 2016-03-03 05:35
We should mention in the docs the fact that we use this internally but insist on the fact that this is an implementation detail and you should NOT use this when building a react native app

**Comment by adamterlson** [comment] 2016-03-03 08:31
@vjeux Just out of curiosity, why add it to the docs if folks should not use it?

**Comment by vjeux** [comment] 2016-03-03 10:41
@adamterlson: good question. All the js files in the implementation of react native (outside of the examples) are using it. Since this is non standard and a bit esoteric, we should mention it so that people are not confused.

**Comment by adamterlson** [comment] 2016-03-04 11:35
@vjeux Thanks for the clarity!  Makes sense.  

The reason why you don't want folks to be using this is because it's part of fbjs, and the plan is to ultimately remove fbjs from React Native, so the support for this will go away?

Is it also true that the `module-alias` plugin is likely to start working when fbjs is removed?

I ask because I'd like to have some sort of solution for removing the `../../../../` from my RN project now, and so I'm wondering if I can get away with using `providesModule` "for now" then replace it with `module-alias` once it's removed.

**Comment by vjeux** [comment] 2016-03-04 14:33
What haste does is to provide a global namespace for your modules. You can do @providesModule bla in any file and then do require('bla').

This is great inside of fb because we control all the codebase and has nice properties like the ability to move around files without having to change the requires of tons of files.

Now, the issue is that it makes a global namespace. If you put this in the hands of the open source community, it will conflict all the time and cause massive pains.

**Comment by akaila** [comment] 2016-04-29 20:34
@providesModule is probably the worst feature of react-native as it keeps thowing conflicts in custom build systems (I have one in my company where react and react-native are siblings within node_modules folder). It would be great if there is a tool that we can run that statically replaces the requires at build time so @providesModule is simply ignored.

**Comment by satya164** [comment] 2016-04-29 21:04
@akaila What versions of `react-native` you use? I also have `react-native` and `react` as my dependencies and it's fine. Also there's work going on to transition to `react` 15 too.

**Comment by akaila** [comment] 2016-04-29 21:21
I am using react-native version 23 and through some other dependency have reactjs version 15. These are incompatible because they use providesModules across packages even. Other times I see similar problems with babel react transform that cannot find chalk module etc etc.

**Comment by lacker** [comment] 2016-10-21 04:47
I think the overall situation here is, providesModule is not a concept we want to export, so don't depend on it. Unfortunately it means some alternative build pipelines don't work, but I think we just can't support general nonstandard build mechanisms. I am going to close this issue but it would be "nice to have" someday to not use providesModule - maybe productpains is good for that.

**Closed by lacker** 2016-10-21 04:47 UTC
Labels: Packager
