### ISSUE TITLE
[RN 0.48.3 Xcode 9] RCTImageStoreManager: Semantic Issue 

### ISSUE THREAD

**Issue by delef** [facebook/react-native#16070] opened 2017-09-23 00:37 UTC
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  8.4.0
  Yarn:  Not Found
  npm:  5.4.2
  Watchman:  4.7.0
  Xcode:  Xcode 9.0 Build version 9A235
  Android Studio:  2.1 AI-143.3101438

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: ^0.48.3 => 0.48.3

### Steps to Reproduce

1. react-native init test
2. Install latest xcode version
3. Open ~/test/ios/test.xcodeproj (xcode)
3. Update to recommended settings (for all xcodeproj)
4. Build

### Expected Behavior

The project started with the old version of xcode.

### Actual Behavior

"This block declaration is not a prototype"

<img width="251" alt="screen shot 2017-09-21 at 02 18 13" src="https://user-images.githubusercontent.com/2103263/30768402-878111b6-a00f-11e7-8700-229074b6e6c7.png">
<img width="848" alt="screen shot 2017-09-21 at 02 39 03" src="https://user-images.githubusercontent.com/2103263/30768403-8f3331f0-a00f-11e7-9533-3b3811bfd198.png">

### Reproducible Demo
https://github.com/delef/rn-xcode9

**Comment by SupriyaAdep** [comment] 2017-09-23 09:48
Facing similar issue

**Comment by ragamufin** [comment] 2017-09-23 18:48
You can try:

https://stackoverflow.com/a/44473380/577280

**Comment by michaelmerrill** [comment] 2017-09-24 23:08
Having this issue as well. RN 0.48.4, RCT 16.0.0-rc.3.

**Comment by glebovitz** [comment] 2017-09-25 19:21
Having this issue as well.

**Comment by Evaske** [comment] 2017-09-27 11:51
Also having this issue. Can't get it to run on a device. Build fails with the above error.

**Comment by glebovitz** [comment] 2017-09-27 16:10
I got my code to compile. The offending code is the prototype for the blocks argument to the removeImageForTag method in RCTImaeStoreManager.h and RCTImaeStoreManager.m node_modules/react-native/Libraries/Image.

The compiler appears to no longer treat empty arguments to a method as a warning. The fix is to make the empty parameter void.

Original code:

```
- (void)removeImageForTag:(NSString *)imageTag withBlock:(void (^)())block
 ```
working code
```
- (void)removeImageForTag:(NSString *)imageTag withBlock:(void (^)(void))block
```
I don't know if this is a general fix, but it worked for me.

**Comment by tolgaduzenli** [comment] 2017-09-29 19:49
doesnt work for me. RN 0.43.3
When I try @glebovitz 's solution I am getting this error;
Conflicting parameter types in implementation of 'removeImageForTag:withBlock:': 'void (^__strong)()' vs 'void (^__strong)(void)'

**Comment by glebovitz** [comment] 2017-09-29 21:16
@tolgaduzenli - did you make the change to both the RCTImaeStoreManager.h and RCTImaeStoreManager.m files. Looks like you changed only the header file.

**Comment by tolgaduzenli** [comment] 2017-10-02 19:45
@glebovitz thank you so much man, now my build is successful.

**Comment by shivankpal** [comment] 2017-10-03 12:10
@glebovitz thankyou man

**Comment by goldblade** [comment] 2017-11-18 22:31
@glebovitz thank you! i solved the problem

**Comment by delef** [comment] 2018-01-17 22:56
We need a global solution to the problem

**Comment by andpor** [comment] 2019-03-01 18:42
Same problem after upgrade to XCode 10.1

**Comment by cpojer** [comment] 2019-05-09 13:45
Is there somebody who could send a Pull Request with a fix for this problem?

**Comment by shubhamguptadream11** [comment] 2024-10-15 16:18
There hasn't been any activity on this issue from long. Also the reproducer provided doesn't seems to exist now.

If someone still getting this on latest RN version. Feel free to re-open this.

**Closed by shubhamguptadream11** 2024-10-15 16:18 UTC
Labels: Platform: iOS, Help Wanted :octocat:, Bug
