### ISSUE TITLE
[iOS - RN 0.61.1 migration] React/RCTBridgeModule.h file not found

### ISSUE THREAD

**Issue by alnorris** [facebook/react-native#26678] opened 2019-10-01 20:15 UTC
Reopening bug that is wrongly closed
https://github.com/facebook/react-native/issues/26615

React Native version: 0.61

## Steps To Reproduce

1. Upgrade to 0.61 with [upgrade-helper-tool](https://github.com/react-native-community/upgrade-helper)
2. If your project has a 3rd party module that are Linked manually, building it results in: React/RCTBridgeModule.h file not found

Describe what you expected to happen:
To compile correctly

**Comment by Cosmin-Ciolacu** [comment] 2019-10-02 09:26
> Reopening bug that is wrongly closed
> #26615
> 
> React Native version: 0.61
> 
> ## Steps To Reproduce
> 1. Upgrade to 0.61 with [upgrade-helper-tool](https://github.com/react-native-community/upgrade-helper)
> 2. If your project has a 3rd party module that are Linked manually, building it results in: React/RCTBridgeModule.h file not found

I have same issue

**Comment by loga4** [comment] 2019-10-02 11:12
the same 

many libraries migrated to pods

```
[!] CocoaPods could not find compatible versions for pod "ReactCommon/callinvoker":
```

**Comment by ma96o** [comment] 2019-10-02 11:45
@loga4 
Have you checked https://github.com/facebook/react-native/pull/26599?

**Comment by loga4** [comment] 2019-10-03 12:38
@ma96o thks!

**Comment by craftmusic** [comment] 2019-10-06 23:27
Also being affected by this and can no longer build link + build my custom native module

**Comment by Alaa-Ben** [comment] 2019-10-09 12:16
Hi @alnorris ! 
When you go to scheme -> edit scheme -> build. Do you have see React (missing) ? If so, i might have a solution because this happened to me. If not, need more information :/

**Comment by usrbowe** [comment] 2019-10-10 02:52
I had the same issue. I just did following to fix:
1. Remove the `package-name.xcodeproj` of package from `Libraries` in Xcode
2. Remove package `Frameworks` if any, in Xcode.
3. Remove package from `Build Phases > Link Binary with Libraries`
2. Remove search headers of that package in: `Build Settings > Header Search Paths` (do that for all project Targets, even `-tv`, `-tests`)
3. Make sure the package implements correctly `package-name.podspec` file in root (check any community based package for reference)
4. run `cd ios && pod install`
5. Run: Clean `⇧+⌘+K` & Clean Build Folder `⎇+⇧+⌘+K`

This helped me solve the missing `xxx.h` files from React.
I also did remove React.xcodeproj from scheme build targets, since it was remove in latest release.

**Comment by alnorris** [comment] 2019-10-10 10:02
@usrbowe This is good workaround, but it doesn't solve the issue of manually linked packages. Some old packages don't have podspecs and have package owners are unresponsive to PR's to add them.

**Comment by grabbou** [comment] 2019-10-11 22:36
Can you point me to an example of such a library? I will try to reproduce it. You can also zip me your project and I will try to see what changes are needed to make it work.

My understanding is that these cases are deprecated and we are moving towards fully automatic linking w/o relying on that.

**Comment by alnorris** [comment] 2019-10-12 10:30
@grabbou, any library without a podspec. Ex: https://github.com/smalltownheroes/react-native-adobe-analytics. If manual linking is in fact deprecated, this would advise to include this as a breaking change, and remove this from the documentation: https://facebook.github.io/react-native/docs/linking-libraries-ios#manual-linking

**Comment by BrennanGlynn** [comment] 2019-10-14 21:24
> Hi @alnorris !
> When you go to scheme -> edit scheme -> build. Do you have see React (missing) ? If so, i might have a solution because this happened to me. If not, need more information :/

I'm seeing that. How did you fix it?

**Comment by alpamys-qanybet** [comment] 2019-10-15 07:39
@grabbou, I have similar situation, I cannot use React-native-navigation V2 or V3 because of bugs,  but V1 does not support ^RN60above, can you help, I have my forked [RNNV1](https://github.com/alpamys-qanybet/react-native-navigation)?

**Comment by zhenghui0705** [comment] 2019-10-16 03:17
> Hi @alnorris !
> When you go to scheme -> edit scheme -> build. Do you have see React (missing) ? If so, i might have a solution because this happened to me. If not, need more information :/

My question is this, is there any way to solve it?

**Comment by Alaa-Ben** [comment] 2019-10-16 07:03
@zhenghui0705  well if you have the react missing thing, here's what I did.
1. Check that I have React in my pods (pod 'React', :path => '../node_modules/react-native/'). If not, add it.
2. Uninstall reinstall pods (pod deintegrate && pod clean && pod install in the ios folder,  I believe the pod deintegrate command needs to be downloaded and isn't available by default)
3. Go to scheme -> edit scheme -> build, delete the React(missing) using the 'minus' button. Click on 'add' or a 'plus' button. Find React (should be in the Pods category) and add it. Finally, make sure all boxes are ticked for React, and place it at the top of the list.

Here you go, I hope this helps. If however you do not have the React(missing), I have no idea how to solve this since i've never had this problem :/

**Comment by TommyLeong** [comment] 2019-10-16 07:20
@zhenghui0705 Here's how I made it work with the workaround. 
[React/RCTDefines.h' file not found (RN0.61)](https://stackoverflow.com/a/58398989/4311268)

**Comment by GutteApps** [comment] 2019-11-18 19:59
After burning a day on this, building with legacy build system did the trick:
File>Workspace Settings> Build system > legacy build system

**Comment by vivianlamCP** [comment] 2019-12-10 08:32
any solution? I also find this error in upgrading to RN 0.61.5

**Comment by luco** [comment] 2019-12-10 18:55
Getting this on 0.61.4

**Comment by luco** [comment] 2019-12-12 01:47
I managed to fix it by adding `$(SRCROOT)/../../../../ios/Pods/Headers/Public/**` to each 3rd party target. React it's only accessible by pods now.

**Comment by lgh06** [comment] 2019-12-30 08:50
> I managed to fix it by adding `$(SRCROOT)/../../../../ios/Pods/Headers/Public/**` in `Header Search Paths (recursive)` to each 3rd party target. React it's only accessible by pods now.

faced same issue. why there are so many slashes ? Shouldn't it be `$(SRCROOT)/Pods/Headers/Public/**` ?

**Comment by luatnd** [comment] 2020-01-02 12:13
> @zhenghui0705 well if you have the react missing thing, here's what I did.
> 
> 1. Check that I have React in my pods (pod 'React', :path => '../node_modules/react-native/'). If not, add it.
> 2. Uninstall reinstall pods (pod deintegrate && pod clean && pod install in the ios folder,  I believe the pod deintegrate command needs to be downloaded and isn't available by default)
> 3. Go to scheme -> edit scheme -> build, delete the React(missing) using the 'minus' button. Click on 'add' or a 'plus' button. Find React (should be in the Pods category) and add it. Finally, make sure all boxes are ticked for React, and place it at the top of the list.
> 
> Here you go, I hope this helps. If however you do not have the React(missing), I have no idea how to solve this since i've never had this problem :/

It's seem OK, but in my case: After click Plus Sign > I cannot found React in Pods, only ReactCore and ReactCoreModules were seen :(

**Comment by d3020** [comment] 2020-01-03 17:54
Is there any updated solution for this? I'm using react native 0.61.5 and still getting the React/RCTBridgeModule.h file not found in ImagePickerManager.h?

**Comment by luatnd** [comment] 2020-01-06 10:15
I spent 2 days on getting this all in one workaround:
https://github.com/facebook/react-native/issues/26665#issuecomment-571082076

**Comment by 1rjun** [comment] 2020-02-19 17:15
Just install everything from Pods, 
cd ios
pod init
install all the required libraries using pod, 
remove all the Xcode project from libraries,
remove all the libraries from linked frameworks and libraries except libPods-ProjectName.a
Go to your Build Setting, Header Search Paths, remove all the paths and add  “$(SRCROOT)/Pods/Headers/”

Now open .xworkspace and your code will work like a charm 

https://medium.com/@arjunsinghrajput/something-wrong-with-react-native-b398d5a66278

**Comment by raphaelpinel** [comment] 2020-03-06 11:47
> 2\. pod deintegrate && pod clean && pod install
@Alaa-Ben
pod clean is not a valid command. Did you mean 
`pod cache clean`?

**Comment by Alaa-Ben** [comment] 2020-03-06 13:12
@raphaelpinel 
`pod clean`and `pod deintegrate` are downloadable plugins:
`sudo gem install cocoapods-deintegrate cocoapods-clean`

**Comment by hamoudaarfaoui** [comment] 2020-04-08 08:26
> Hi @alnorris !
> When you go to scheme -> edit scheme -> build. Do you have see React (missing) ? If so, i might have a solution because this happened to me. If not, need more information :/

Yes it does for me , can you help ?

**Comment by willnaoosmit** [comment] 2020-04-09 12:58
Same error here

**Comment by hamoudaarfaoui** [comment] 2020-04-09 13:51
the only solution that worked for me is that you create .podspec file to whatever library you using and install it using Pods , and dont manual link or anything of that .. saddly not all libraries are up to date, so had to do it yourself manually to setup a .podspec file

**Comment by EhteshamAnwar** [comment] 2020-04-12 00:14
> @loga4
> Have you checked #26599?
@ma96o  did this and the run pod install, I got this error.
![image](https://user-images.githubusercontent.com/16754151/79057596-6d507600-7c7c-11ea-9a0e-c1293a20c2ec.png)

**Comment by hamoudaarfaoui** [comment] 2020-04-12 19:30
this should fix this hell https://medium.com/@hamoudaarfawi/upgrading-react-native-to-rn0-60-react-rct-h-file-not-found-solved-e9bd65fc4ee6

**Comment by willnaoosmit** [comment] 2020-04-14 14:09
The solution, for me, was deleting the entire ios folder, generating a new project with react-native-init, and moving the ios folder from the newer project to the official one.
wrong?
yes
but it worked.
maybe this happens when you upgrade your react native version

**Closed** 2020-04-16 23:27 UTC
Labels: DX: Upgrading, Platform: iOS, Ran Commands, Type: Upgrade Issue

**Comment by simon-davies-avtura** [comment] 2020-04-30 01:32
> @raphaelpinel
> `pod clean`and `pod deintegrate` are downloadable plugins:
> `sudo gem install cocoapods-deintegrate cocoapods-clean`

Absolutely got myself in a tangled mess with the state of projects/podfiles/caches. I backed out my (very messy) changes then tried the above deintegrate and clean, pow, really unexpected but it was a silver bullet! Reloaded everything and it *just worked*. Thank you so much for the suggestion.

**Comment by Hamza6244** [comment] 2020-12-09 16:29
Still, I'm getting the same error anyone finds a solution for this?  Basically, I'm using react-native-create module lib for but it creates iOS folder without pod file so now i want to use pods and when i'm adding custom pods then i'm getting React/RCTBridgeModule.h file not found

**Comment by abdelhedydev** [comment] 2021-04-27 11:18
This solution was solved my problem
https://github.com/joltup/rn-fetch-blob/issues/461#issuecomment-553355501
