### ISSUE TITLE
Can't run run debug mode in android emulator

### ISSUE THREAD

**Issue by emadbaqeri** [facebook/react-native#32461] opened 2021-10-22 15:17 UTC
### Description

I have cloned my project from GitHub that I have been working on for a couple of months, but I have changed my distro to Ubuntu and then set up my work environment again and started to work on the project.
When I want to install `npm packages` using npm install see the error below:

![NHlDx](https://user-images.githubusercontent.com/50639499/138476806-663c2ad3-d834-4dae-98ce-aac5f9708288.jpg)

<details>
<summary>Details</summary>

</details>

### Version

0.64.1

### Output of `react-native info`
```bash
System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 1.10 GB / 15.42 GB
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 26, 29, 30, 31
      Build Tools: 19.1.0, 20.0.0, 21.1.2, 22.0.1, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0
      System Images: android-26 | Android TV Intel x86 Atom, android-26 | China version of Android Wear Intel x86 Atom, android-26 | Android Wear Intel x86 Atom, android-26 | Intel x86 Atom, android-26 | Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-29 | Android TV Intel x86 Atom, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs ARM 64 v8a, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play ARM 64 v8a, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: AI-203.7717.56.2031.7784292
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.1 => 0.64.1 
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

- I have changed my distro from arch Linux to Ubuntu
- Cloned project from GitHub
- Tried to install `npm packages` using `npm install`
- and face the error that I have mentioned

### Snack, code example, screenshot, or link to a repository

This is my `package.json` file, I put this here if that helps
```json
{
  "name": "dummyapp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx",
    "pretty": "npx prettier --write ."
  },
  "dependencies": {
    "@apollo/client": "^3.4.8",
    "@babel/preset-typescript": "^7.15.0",
    "@eva-design/eva": "^2.1.1",
    "@react-native-async-storage/async-storage": "^1.15.7",
    "@react-native-community/datetimepicker": "^3.5.2",
    "@react-navigation/bottom-tabs": "^6.0.5",
    "@react-navigation/devtools": "^6.0.2",
    "@react-navigation/drawer": "^6.1.6",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/native-stack": "^6.0.6",
    "@react-navigation/stack": "^6.0.9",
    "@types/react-navigation": "^3.4.0",
    "@ui-kitten/components": "^5.1.1",
    "dotenv": "^10.0.0",
    "formik": "^2.2.9",
    "graphql": "^15.5.1",
    "lodash": "^4.17.21",
    "moment": "^2.29.1",
    "native-base": "^3.2.0",
    "react": "17.0.1",
    "react-native": "0.64.1",
    "react-native-config": "^1.4.3",
    "react-native-dotenv": "^3.2.0",
    "react-native-flipper": "^0.111.0",
    "react-native-flipper-apollo-devtools": "^0.0.2",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-image-crop-picker": "^0.36.2",
    "react-native-paper": "^4.9.2",
    "react-native-reanimated": "^2.3.0-beta.1",
    "react-native-responsive-screen": "^1.4.2",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "^3.7.2",
    "react-native-shared-element": "^0.8.3",
    "react-native-svg": "^12.1.1",
    "react-native-vector-icons": "^8.1.0",
    "react-navigation-shared-element": "^3.1.3",
    "recoil": "^0.4.1",
    "rn-async-storage-flipper": "^0.0.10",
    "styled-components": "^5.3.1",
    "styled-system": "^5.1.5",
    "uuid": "^8.3.2",
    "yup": "^0.32.9"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@types/graphql": "^14.5.0",
    "@types/jest": "^26.0.23",
    "@types/lodash": "^4.14.175",
    "@types/moment": "^2.13.0",
    "@types/react-native": "^0.64.5",
    "@types/react-native-vector-icons": "^6.4.8",
    "@types/react-test-renderer": "^16.9.2",
    "@types/recoil": "0.0.9",
    "@types/uuid": "^8.3.1",
    "@types/yup": "^0.29.13",
    "babel-jest": "^26.6.3",
    "babel-preset-react-native": "^2.1.0",
    "eslint": "^7.14.0",
    "eslint-config-prettier": "^8.3.0",
    "husky": "^4.2.3",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.64.0",
    "pretty-quick": "^2.0.1",
    "react-test-renderer": "17.0.1",
    "typescript": "^4.3.5"
  },
  "resolutions": {
    "@types/react": "^17"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  }
}
```

**Comment by cortinico** [comment] 2021-10-31 15:28
> Is there any way of preventing this?

That's how NPM versioning works. If you specify `"react-native-reanimated": "^2.3.0-beta.1",`, you're allowing for all the minor version bumps when you run `npm install`.
You can learn more about it on https://semver.npmjs.com/

Like
![Screenshot 2021-10-31 at 15 26 35](https://user-images.githubusercontent.com/3001957/139590714-611fe91b-7b8c-4354-8e93-7f02afaaa80e.png)

You could remove the `^` from your versions so the exact version gets donwloaded.
Closing as the root cause got identified. Feel free to reopen if you have other issues.

**Closed by cortinico** 2021-10-31 15:28 UTC
Labels: Platform: Android, Platform: Linux, Needs: Environment Info, Needs: Attention

**Comment by emadbaqeri** [comment] 2021-11-10 09:10
> > Is there any way of preventing this?

Thank you this is helped me and saved lots of effort 👍🏽
