### ISSUE TITLE
onCatalystInstanceDestroy of java module is called on UI thread

### ISSUE THREAD

**Issue by dryganets** [facebook/react-native#13297] opened 2017-04-04 17:31 UTC
### onCatalystInstanceDestroy called on UI thread while @ReactMethod is called on native_module tread.

This is a fragile design as modules authors are not aware of it.
If you have a module which requires de-initialization this fact overcomplicates the design of the module.

**Comment by hramos** [comment] 2017-04-04 21:34
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-04-04 21:34 UTC
