### ISSUE TITLE
RCTWebSocket.m (2 issues)

### ISSUE THREAD

**Issue by ozguruksal** [facebook/react-native#8975] opened 2016-07-22 16:35 UTC
XCode version 7.3.1 is fine but if I use version 8.2(beta) instead, then the XCode reports two issues: 

1. /pathTo/myProject/node_modules/react-native/Libraries/WebSocket/RCTSRWebSocket.m:494:3: **Ignoring return value of function declared with warn_unused_result attribute**
2. /pathTo/myProject/node_modules/react-native/Libraries/WebSocket/RCTSRWebSocket.m:1334:5: **Ignoring return value of function declared with warn_unused_result attribute**

If I comment out the following two lines from "RCTWebSocket.m", the build succeeds:
`SecRandomCopyBytes(kSecRandomDefault, keyBytes.length, keyBytes.mutableBytes);`
`  SecRandomCopyBytes(kSecRandomDefault, sizeof(uint32_t), (uint8_t *)mask_key);`

**Comment by zhileichen** [comment] 2016-07-24 04:16
Specifically, it caused by the llvm compiler flag **-Werror**, _means turn warnings into errors,_ which might works in later llvm 8.0, you can removed it in the building setting of RCTWebSocket project.

**Comment by TimBroddin** [comment] 2016-08-04 15:17
I posted a fix here: 
#8584

**Comment by javache** [comment] 2016-08-16 15:52
Fixed by https://github.com/facebook/react-native/commit/2f788524112d59f62a295e7f4b0c1cfa0f6203fe

**Closed by javache** 2016-08-16 15:52 UTC
