### ISSUE TITLE
Error: watchman --no-pretty get-sockname returned with exit code=3221225595

### ISSUE THREAD

**Issue by FrankenSteinxD** [facebook/react-native#15157] opened 2017-07-23 20:21 UTC
When I run `yarn run build` which is `relay-compiler --src ./ --schema ./schema.json`
I get this error:

    Watchman:  watchman --no-pretty get-sockname returned with exit code=3221225595, signal=null, 
    stderr=
    events.js:160
      throw er; // Unhandled 'error' event

    Error: watchman --no-pretty get-sockname returned with exit code=3221225595, signal=null, stderr=
    at ChildProcess.<anonymous> (C:\Users\Rashad Kokash\Downloads\repos\vascular-native-
    app\node_modules\relay-compiler\node_modules\fb-watchman\index.js:198:18)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

I should mention that running `watchman --version` shows me an error dialog with code 0xc000007b, I tried fixing this by installing .NET, directx and visual c++ redistribution, I have watchman in my path, and the problem is not fixed.

**Comment by hramos** [comment] 2017-07-24 17:25
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-07-24 17:25 UTC
