### ISSUE TITLE
backfaceVisibility not documented

### ISSUE THREAD

**Issue by jaygarcia** [facebook/react-native#13921] opened 2017-05-11 15:46 UTC
Just an FYI, backfaceVisibility doesn't seem to be documented anywhere, but exists for iOS at least.

```
commander-keen:react-native jgarcia$ grep -r backfaceVisibility .
./Libraries/Components/View/ViewStylePropTypes.js:  backfaceVisibility: ReactPropTypes.oneOf(['visible', 'hidden']),
./Libraries/Image/ImageStylePropTypes.js:  backfaceVisibility: ReactPropTypes.oneOf(['visible', 'hidden']),
./React/Views/RCTViewManager.m:RCT_REMAP_VIEW_PROPERTY(backfaceVisibility, layer.doubleSided, css_backface_visibility_t)
./RNTester/js/TransformExample.js:    backfaceVisibility: 'hidden',
```

**Comment by chirag04** [comment] 2017-05-11 16:33
view style props are not auto generated anymore it seems.

**Comment by hramos** [comment] 2017-06-01 18:25
Dupe of #14147

**Closed by hramos** 2017-06-01 18:25 UTC
Labels: Documentation
