### ISSUE TITLE
DevMenu

### ISSUE THREAD

**Issue by huangcheng1** [facebook/react-native#12558] opened 2017-02-24 07:10 UTC
when i use devmenu to debug, i found when i open many rootview , shake device ,will open many devmenu . but i want just open one . 
be more easy , i want modify the bridge showshake property , but when i modify in other place ,will update , because RN use userdefault save . so can't just one to one save?  

RN 0.39.2

**Comment by hramos** [comment] 2017-02-24 17:35
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Does this reproduce on the latest version of RN? Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-02-24 17:35 UTC
