### ISSUE TITLE
Inline image isn't scaled in Android version

### ISSUE THREAD

**Issue by alexustinovsm** [facebook/react-native#11906] opened 2017-01-14 12:22 UTC
When I use inline Image component with static image resources with different densities, I'll have problem in Android version with scaling of image. It looks like the app uses 1x instead of 3x image, but iOS version works fine.

Part of my code:
```javascript
<Text>
  <Image source={ require('./imgs/my_icon.png') } /> with some text here
</Text>
```

My static image resources:
```
./imgs
|----> my_icon.png
|----> my_icon@1.5x.png
|----> my_icon@2x.png
|----> my_icon@3x.png
+----> my_icon@4x.png
```

ReactNative v0.40.0

**Comment by yloeza** [comment] 2017-03-04 04:09
after some debugging on my own I found the reason why text inline image is not getting scaling properly, here my findings:

During this commit change: https://github.com/facebook/react-native/commit/68c6d71cea4e37f0360453be6e7f792ed12f6f3a
The way width and height are used to generate TextInlineImageSpan was changed:
from:
 ```java
public TextInlineImageSpan buildInlineImageSpan() {
      Resources resources = getThemedContext().getResources();
 int height = (int) Math.ceil(getStyleHeight());
 int width = (int) Math.ceil(getStyleWidth());
  return new FrescoBasedReactTextInlineImageSpan(
    resources,
    height,
  ...
```
to:
```java
public TextInlineImageSpan buildInlineImageSpan() {
  Resources resources = getThemedContext().getResources();
  int height = (int) Math.ceil(mWidth);
  int width = (int) Math.ceil(mHeight);
  return new FrescoBasedReactTextInlineImageSpan(
    resources,
    height,
    ...
```
so before it was getting set from `getStyle*()` methods, that returns a value stored based on the result of the `setStyle*()` call, which transform the value of width to the pixel unit based of resolution.

 ```java
public void setWidth(float width) {
    setStyleWidth(CSSConstants.isUndefined(width) ? width : PixelUtil.toPixelFromDIP(width));
  }
```

currently, this class does not apply any transformation to the width/height value so it ends up rendering without any notion of the current resolution.

a workaround for now is doing something like this:
```js
class App extends Component {

  render() {
    const width = 80 * (Platform.OS === 'ios' ? 1 : PixelRatio.get());
    const height = 80 * (Platform.OS === 'ios' ? 1 : PixelRatio.get());
    return (
      <View style={{flex: 1}}>
        <Text style={{backgroundColor: 'red'}}>
          <Image
            style={{width, height}}
            source={{uri: 'http://s3.hilariousgifs.com/displeased-cat.jpg'}}
          />
        </Text>
      </View>
    );
  }
}
```
I hope this info is helpful to clarify this issue so we can expect a fix for this soon. Let me know if you guys need any more information.
I also noticed that iOS is rendering inline image a little off. 
ReactNative v0.41.2
iOS:
![image](https://cloud.githubusercontent.com/assets/1137100/23575961/884569d4-004c-11e7-9362-89413d109aad.png)

before workaround:
![image](https://cloud.githubusercontent.com/assets/1137100/23575960/63bcc99a-004c-11e7-8834-9facf557a54a.png)

after workaround:
![image](https://cloud.githubusercontent.com/assets/1137100/23575952/3bbc6f90-004c-11e7-90a2-5b496bc4c828.png)

**Comment by yloeza** [comment] 2017-04-11 18:11
@christopherdro is there any news/progress around this issue?

**Comment by hramos** [comment] 2017-07-20 22:13
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/inline-image-isnt-scaled-in-android-version

**Closed by hramos** 2017-07-20 22:13 UTC
Labels: Android, Icebox

**Comment by chuckwu0** [comment] 2017-08-14 04:06
thx @yloeza .this work around for me

**Comment by doublex** [comment] 2017-12-12 09:14
@alexustinovsm 
Still not fixed - could you re-open this issue?

**Comment by hramos** [comment] 2017-12-21 17:29
I won't be reopening this issue as it does not contain sufficient information as required by the template. You may open a new one.

**Comment by doublex** [comment] 2017-12-22 12:00
@hramos 

The problem is simple: <Images> inside <Text> on Android are not calculated according to "device pixels" but according to "real pixels" (which is wrong on high resolution devices).

A new issue would loose the information in the thread.

**Comment by hramos** [comment] 2017-12-22 17:05
You can always link back to the thread and make sure the new issue summarizes any relevant information from this thread.
