### ISSUE TITLE
SectionSeparatorComponent wrap issue in horizontal SectionList

### ISSUE THREAD

**Issue by nenti** [facebook/react-native#15822] opened 2017-09-05 23:05 UTC
# Issue with SectionSeparatorComponent placement in horizontal mode

**SectionSeparatorComponent** get stacked on top of the component as in a vertical list rather than put in front of the 1st item. So if you put a separator component of 50x50px into a horizontal list the first section item is moved 50px to the bottom rather than 50px to the right.

From what I know it is not possible to handle this, as there is no control over the `renderItemWithSection` function, but rather only for the `renderItem` and the `renderSection` function.

## Tested on react-native v0.48.1

**Comment by hramos** [comment] 2017-09-07 17:19
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue that meets the requirements set forth in the template. Thanks!

**Closed by hramos** 2017-09-07 17:19 UTC
