### ISSUE TITLE
Infinite recursion in RCTFatal when the bundle fails to execute

### ISSUE THREAD

**Issue by ide** [facebook/react-native#5090] opened 2016-01-03 09:06 UTC
RCTFatal calls _RCTLogNativeInternal which enqueues a JS call. This can fail because a previous RCTFatal occurred because the bundle failed to execute in the first place (ex: `__fbBatchedBridge is undefined`). So when RCTFatal fails, it ends up calling RCTFatal again in an infinite loop.

cc @javache

**Comment by javache** [comment] 2016-01-05 23:30
I believe I fixed this in https://github.com/facebook/react-native/commit/0cfe76399c3f38d8120e83e634475d00a55a718a

If an error happens as part of bridge init, the JS executor is invalidated and will no longer enqueue the JS call.

**Comment by skevy** [comment] 2016-01-05 23:33
@javache I encountered this error on master about 3 days ago, fyi.

**Comment by philikon** [comment] 2016-01-08 06:12
I don't believe 0cfe763 fixed this because the bug is present in 0.18.0rc.

**Comment by javache** [comment] 2016-01-08 10:27
@philikon Can you provide an example of how to reproduce this? If something as fundamental as __fbBatchedBridge is broken, it should be caught during startup and cause the bridge to be invalidated.

Either way, this bug should only be present when debugging using the Chrome executor.

**Comment by jvliwanag** [comment] 2016-01-08 10:36
Using a new 0.18.0rc project. Replace the contents of `index.ios.js` with:

```
asdfasdf
```

Doesn't need to run on chrome executor.

**Comment by yueshuaijie** [comment] 2016-01-09 01:02
I encountered this error, too. Hope to find a solution.

**Comment by philikon** [comment] 2016-01-09 01:45
@javache I get this if the package server isn't reachable / running for the app.

#4739 seems related.

**Comment by Creemli** [comment] 2016-01-12 14:50
I also see this error when i use 0.18.0-rc with bundled js.

**Comment by Purii** [comment] 2016-01-12 15:26
Me too @Creemli
I get this error only, when I use bundled js.

**Comment by stereodenis** [comment] 2016-01-12 15:35
waiting for fix too

**Comment by Creemli** [comment] 2016-01-13 08:44
@Purii  I fixed this issue by copying the code from http://localhost:8081/index.ios.bundle to main.jsbundle.  And it works well~~~

**Comment by Purii** [comment] 2016-01-14 18:32
@Creemli doesn't work for me. Neither with `dev=false` nor `dev=true`

**Comment by Mokto** [comment] 2016-01-14 19:23
I also got this error.

**Comment by javache** [comment] 2016-01-15 12:33
This is now failing recursively because we check more carefully for an invalid bundle (https://github.com/facebook/react-native/commit/5b4e873c68be9a788ac8cc3f67199fbaacb58921). I'm looking to see if there's any way we can bail out earlier in this case without breaking other debug tools.

**Comment by Purii** [comment] 2016-01-15 13:39
@javache 
> check more carefully for an invalid bundle

Does this mean, that there is something wrong with our code, or is it the packager which fails?

**Comment by javache** [comment] 2016-01-15 13:42
@Purii: yes, please verify that the bundle you're trying to load in the packager is valid.

**Comment by Purii** [comment] 2016-01-16 01:33
@javache Running `eslint` on the bundle throws the following errors:
* `"babelHelpers" is not defined`
* `"__d" is not defined`
* `"__BUNDLE_START_TIME__" is not defined`
* `"self" is not defined`
* `"__REACT_DEVTOOLS_GLOBAL_HOOK__" is not defined`
* `"GLOBAL" is not defined`
* `"window" is read only`
* `"MessageChannel" is not defined`
* `"FileReader" is not defined`
* `"Blob" is not defined`
* `"FormData" is not defined`
* `"Node" is not defined`
* `"math" is not defined`
* `"regeneratorRuntime" is not defined`

The list looks similar on a new project with `0.17.0`.
Checking my source files via `eslint` doesn't throw any error.

**Comment by dsernst** [comment] 2016-01-17 04:14
Seeing this after following the standard instructions from https://facebook.github.io/react-native/docs/getting-started.html#quick-start

**Comment by Purii** [comment] 2016-01-18 22:08
Fixed with `0.18.0-final`.

**Comment by danscan** [comment] 2016-01-19 15:41
I'm seeing this issue after upgrading a project from 0.15 to 0.18.  I used `react-native upgrade`, and updated deps that can now depend on `react`.

**Comment by jasonmerino** [comment] 2016-01-19 19:30
I'm seeing this issue after trying to upgrade from 0.16 to 0.18. I also used `react-native upgrade`.

**Comment by yueshuaijie** [comment] 2016-01-20 03:17
I'm seeing this issue in 0.18.0-rc, after upgrade to 0.18.0, it disappeared.

**Comment by mkonicek** [comment] 2016-01-20 14:12
@javache tells me this one should help too: 8ea9a1bc94a0d5635f6ab286331a8acba912f15f, just released 0.18.1 with that commit, give it a try.

**Comment by 23c** [comment] 2016-01-24 02:16
I downgrade to 0.16.0 version, over this problem.

**Comment by mkonicek** [comment] 2016-01-25 00:17
8ea9a1b released with 0.18.1 should be the fix. Let's close this and reopen if it still appears in 0.18.1 and later versions.

**Closed by mkonicek** 2016-01-25 00:17 UTC
Labels: iOS

**Comment by mixophrygian** [comment] 2016-01-25 00:41
just encountered this in 0.18.0 - somehow ReactLog.m was getting a new line prepended to the top of the file.  Problem went away when it was removed.

**Comment by dvcrn** [comment] 2016-01-25 10:48
Just encountered this with 0.18.1. Didn't have it in 0.18-rc but since the update this is appearing for me as well

**Comment by leeabc** [comment] 2016-01-25 16:42
Still get this issue in 0.18.1

Step:
1. npm install --save react-native@0.18
2. react-native upgrade
3. run in xcode

[error][tid:com.facebook.React.JavaScript] Unable to execute JS call: __fbBatchedBridge is undefined

Could someone can help on this case ?

**Comment by javache** [comment] 2016-01-25 16:46
That means something went wrong with loading/executing your JS bundle. This task only concerns infinite recursion happening as a side-effect of that. Please open a new issue instead.

**Comment by DickyT** [comment] 2016-01-28 06:18
also got this issue *sometimes*, using bundled js without dev mode in 0.19-rc

**Comment by stereodenis** [comment] 2016-02-03 16:37
@javache got this issue with 0.19
I think react-native-xcode.sh is not packing main.jsbundle

**Comment by ide** [comment] 2016-02-03 22:32
@stereodenis are you experiencing infinite recursion or seeing `__fbBatchedBridge is undefined`?

**Comment by shohey1226** [comment] 2016-02-03 23:26
I saw this with 0.19 when I tried to run on device after upgraded from 0.13.  I checked in the log and realized that `react-native-xcode.sh` is just missing.. needed to do work on https://facebook.github.io/react-native/docs/upgrading.html#manual-upgrades

**Comment by stereodenis** [comment] 2016-02-04 08:20
@ide __fbBatchedBridge is undefined

**Comment by javache** [comment] 2016-02-04 17:58
Please file a new issue when you're just seeing this error. `__fbBatchedBridge is undefined` points at issues with the JS bundle setup. Since the infinite recursion here has been resolved, I'm locking this issue.
