### ISSUE TITLE
React Native version mismatch (on app that was working a couple of hours ago) - Android #19259

### ISSUE THREAD

**Issue by vahid263** [facebook/react-native#19270] opened 2018-05-15 14:12 UTC
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.4.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51.0 => 0.51.0

## Steps to Reproduce

   //compile 'com.facebook.react:react-native:+'
        compile 'com.facebook.react:react-native:0.51.0' { force = true } // From node_modules
## Expected Behavior
solve the mismatch problem.

## Actual Behavior

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find method com.facebook.react:react-native:0.51.0() for arguments [build_bkmkoxgkg43bukky670k8y3zq$_run_closure2$_closure14@26f588d9] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by danilags** [comment] 2018-05-15 15:29
it happens to me as well. +1

**Comment by hramos** [comment] 2018-05-15 15:31
Duplicate of #19259

**Comment by OrRosenblatt** [comment] 2018-05-15 15:32
Fix is being purposed for the same issue, opened 10 hours ago:
https://github.com/facebook/react-native/issues/19259

**Closed by hramos** 2018-05-15 15:31 UTC
Labels: :large_blue_diamond:Android, :rewind:Old Version

**Comment by zmbeex** [comment] 2018-05-16 02:13
compile ('com.facebook.react:react-native:0.51.+') { force = true }

**Comment by zmbeex** [comment] 2018-05-16 02:14
compile ('com.facebook.react:react-native:0.51.+') { force = true }

**Comment by ray-shawn** [comment] 2018-05-16 02:37
compile("com.facebook.react:react-native:0.44.0") { force = true } does **not** work on me.

**Comment by ray-shawn** [comment] 2018-05-16 03:30
Add to android/build.gradle saves me

subprojects {
configurations.all {
resolutionStrategy {
force 'com.facebook.react:react-native:0.44.0'
}
}
}

**Comment by hramos** [comment] 2018-05-17 00:27
Locking as this is a duplicate of an issue that was locked.
