### ISSUE TITLE
rootTag changed when back button pressed

### ISSUE THREAD

**Issue by tomasdelima** [facebook/react-native#13661] opened 2017-04-25 16:50 UTC
When I open my app for the first time, I get the following message on my logs:
> Running application "AppName" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF

But whenever I quit my app with the Back button, I get the following message:

> Running application "AppName" with appParams: {"initialProps":{},"rootTag":11}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF

The parameter `rootTag` is changed to 11. This prevents my to change scenes with my navigator through `navigator.push({...})`, as I receive the warning message:
> Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.
Please check the code for the exports component.

Any help?
Thanks in advance

**Update**

Every next time I exit the app with the Back button, the parameter `rootTag` is increased by 10, so becoming 21, 31, 41, ...

**Comment by hramos** [comment] 2017-04-26 16:38
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-04-26 16:38 UTC
