### ISSUE TITLE
[Andriod] Failed to open project in Android Studio with pnpm

### ISSUE THREAD

**Issue by Shad02w** [facebook/react-native#34432] opened 2022-08-17 04:08 UTC
### Description

Open a react-native android project in Android studio will lead to error message:
`Exception during working with external system: java.lang.AssertionError`

I am using `pnpm` as the package manager,  use `yarn` will NOT have the same issue. It since like some packages is missing but i failed to find one.

However, I am able to run android from command line using `react-native run-android` with no problem.

### Version

0.69.4

### Output of `npx react-native info`

System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 160.70 MB / 32.00 GB
    Shell: 3.5.0 - /opt/local/bin/fish
  Binaries:
    Node: 16.15.1 - ~/.local/share/nvm/v16.15.1/bin/node
    Yarn: 1.22.19 - ~/.local/share/nvm/v16.15.1/bin/yarn
    npm: 8.12.1 - ~/.local/share/nvm/v16.15.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /Users/alvistse/.asdf/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: 8.0.6 => 8.0.6 
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.4 => 0.69.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. `npx react-native init repro --template react-native-template-typescript`
2. Run `pnpm install`
3. Added following packages to fixed the symlink issues: `@react-native-comunity/cli-platform-ios`,`@react-native-comunity/cli-platform-android`, `@react-native-comunity/cli`, `@rnx-kit/metro-config`, `@rnx-kit/metro-resolver-symlinks`, `react-native-gradle-plugin@0.0.7`
4. open `android` folder in android studio.
5. Failed with `Exception during working with external system: java.lang.AssertionError`

### Snack, code example, screenshot, or link to a repository

Here is the repo i made to reproduce the problem: https://github.com/Shad02w/rn-pnpm-repro
![Snipaste_2022-08-17_12-05-30](https://user-images.githubusercontent.com/6605655/185032599-67f63fd6-366f-4712-ab05-6dd838eb4977.png)

**Comment by cortinico** [comment] 2022-08-17 10:14
> I am using `pnpm` as the package manager, use `yarn` will NOT have the same issue

We don't support pnpm at the moment, so that's why you're facing those (or other issues). 
We would need to full build log from Android Studio to understand what happened here.

**Comment by Shad02w** [comment] 2022-08-18 03:38
I think I can only provide the `idea.log`(it contains some of the build log). If there are any other places to find log, please let me know, thanks
[idea.log](https://github.com/facebook/react-native/files/9367441/idea.log)

**Comment by cortinico** [comment] 2022-08-18 12:27
I believe the failure is here:
https://cs.github.com/finch0001/intellij-community/blob/971f6b3d8125f7bd271146ca7016a96d5f8dc069/plugins/gradle/src/org/jetbrains/plugins/gradle/service/project/CommonGradleProjectResolverExtension.java?q=CommonGradleProjectResolverExtension.java#L121

I also found this project from Nebula which seems to have your same stacktrace:
https://github.com/nebula-plugins/gradle-nebula-integration/tree/main/intellij-buildSrc-issue

The fact that this is happening only in the IDE and not in the terminal makes me lean towards an IDE-specific issue.

I would suggest you:
1. Try to open the project with IntelliJ and verify if the issue persists also there
1. Open an issue on IntelliJ IDEA issue tracker https://youtrack.jetbrains.com/issues/IDEA
1. Try to create a pnpm project, without React Native, and open it with IntelliJ IDEA or WebStorm and understand what could be the issue.

I'm closing this as this is not really actionable for us, but please share more findings if you have any.

**Closed by cortinico** 2022-08-18 12:27 UTC
Labels: Platform: Android

**Comment by Traviskn** [comment] 2023-01-11 22:37
I also ran into this issue, and the reason android studio fails to sync the project is because pnpm creates a symlink to the react-native-gradle-plugin. I confirmed this by deleting the symlink pnpm had created and copying the actual react-native-gradle-plugin folder into my node_modules, and it worked. It seems that android studio can't follow the symlinks unfortunately.

**Comment by keeslinp** [comment] 2023-01-12 16:00
This fixed the issue for me
```
diff --git a/app/android/settings.gradle b/app/android/settings.gradle
index 01924f836c..fd4c35d4f3 100644
--- a/app/android/settings.gradle
+++ b/app/android/settings.gradle
@@ -1,7 +1,7 @@
 rootProject.name = 'Simplifi'
 apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
 include ':app'
-includeBuild('../node_modules/react-native-gradle-plugin')
+includeBuild(file('../node_modules/react-native-gradle-plugin').toPath().toRealPath().toAbsolutePath().toString())
 
 if (settings.hasProperty("newArchEnabled") && settings.newArchEnabled == "true") {
     include(":ReactAndroid")
```

if you manually resolve the symlink before passing it in then you don't have to worry about gradle being unable to follow the symlink.

**Comment by nzcodarnoc** [comment] 2023-03-14 00:16
Thanks @keeslinp, I'm developing React Native in an nx monorepo and had this issue, and your fix worked, I'm mentioning it for the next nx dev who googles this error.

**Comment by MikeHewett** [comment] 2023-03-17 08:47
@keeslinp thanks for the workaround, mate. This saved me.

**Comment by bimusiek** [comment] 2023-05-30 13:39
Why is this not yet supported, I don't get. But thank you for the workaround @keeslinp !

**Comment by NicholasBoccuzzi** [comment] 2023-06-09 20:33
@keeslinp Thank you for the help!

**Comment by israromar** [comment] 2023-06-27 06:35
> Thanks @keeslinp, I'm developing React Native in an nx monorepo and had this issue, and your fix worked, I'm mentioning it for the next nx dev who googles this error.

faced the same issue in monorepo,  thank you for your comment [nzcodarnoc](https://github.com/nzcodarnoc)
and [keeslinp](https://github.com/keeslinp)

**Comment by komailabbas12** [comment] 2023-08-03 08:41
If the above solution are not working for you. that's because of the path
changed
`includeBuild('../node_modules/@react-native/gradle-plugin')`
to
`includeBuild(file('../node_modules/@react-native/gradle-plugin').toPath().toRealPath().toAbsolutePath().toString())`

**Comment by zhiqingchen** [comment] 2024-01-26 02:53
> If the above solution are not working for you. that's because of the path changed `includeBuild('../node_modules/@react-native/gradle-plugin')` to `includeBuild(file('../node_modules/@react-native/gradle-plugin').toPath().toRealPath().toAbsolutePath().toString())`

This change works, can you add this change to the official template? @cortinico
