### ISSUE TITLE
 'value' is unavailable problem with RN 71.10 & XCode 14.3.1

### ISSUE THREAD

**Issue by efecantekin** [facebook/react-native#37799] opened 2023-06-09 13:02 UTC
### New Version

71.10

### Old Version

71.06

### Build Target(s)

iOS Simulator

### Output of `react-native info`

System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 136.61 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.0.0 - ~/.nvm/versions/node/v18.0.0/bin/node
    Yarn: Not Found
    npm: 8.6.0 - ~/.nvm/versions/node/v18.0.0/bin/npm
    Watchman: 2023.03.20.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/efecantekin/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.10 => 0.71.10
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

Hello,

After upgrade RN & XCode I started to get error in XCode. 

![image](https://github.com/facebook/react-native/assets/3815883/23e7aeae-32c8-4bcd-bfed-4a05af7fb28c)

When I changed React-Codegen's deployment target to 12.4, different pods start to give same error.

How can I solve this problem?

Thanks,

**Comment by serhii-kucherenko** [comment] 2023-06-10 15:21
Same here

**Comment by simonNeo** [comment] 2023-06-13 04:02
same here.
some detail:
in June 13，App Store rejected my app archive because "This app was built with the iOS 15.5 SDK. All iOS and iPadOS apps submitted to the App Store must be built with the ios ...", so I have to upgrade my xcode by guide.

**Comment by kelset** [comment] 2023-08-16 10:40
duplicate of https://github.com/facebook/react-native/issues/36739

**Closed by kelset** 2023-08-16 10:40 UTC
Labels: Needs: Triage :mag:, Type: Upgrade Issue
