### ISSUE TITLE
RCTAsyncStorage.getAllKey callback does not happen RN 0.31 Android 4.2.2 when debugging

### ISSUE THREAD

**Issue by eranbes** [facebook/react-native#9319] opened 2016-08-09 14:31 UTC
Android 4.2.2
RN 0.31

`RCTAsyncStorage.getAllKeys(function(error, keys) {` line in `AsyncStorage.js`, `getAllKeys` method never gets to callback when debugging in chrome.
Also, `AsyncStorage.js` chooses to use sqlite implementation (at least in the chrome debugger).

This issue happen only in debug.

**Comment by corbt** [comment] 2016-08-11 20:16
I have replicated this issue on 0.31 and 0.32.0-rc.0.

Haven't isolated the problem, but can confirm that `AsyncStorage.getAllKeys` works while running on the device normally, but *not* when debugging JS remotely in Chrome.

**Comment by alenia** [comment] 2016-08-12 18:46
I'm also experiencing this issue. It means I haven't been able to use the chrome debugger since upgrading to 0.31. Anyone have any workarounds for now?

**Comment by corbt** [comment] 2016-08-12 19:14
@alenia nope, still broken for me. Haven't had a chance to investigate.

**Comment by kageurufu** [comment] 2016-08-12 23:36
I have the same issue, it works as expected in 0.30.

I have downgraded until the cause is determined. I have tested on a Nexus 5 a 6.0.1, and a Nexus 6P at N preview 5

**Comment by rigdern** [comment] 2016-08-16 18:45
I hit this as well in 0.32.0-rc. I suspect that the commit in 0.31.0 (c89c25f27d115c1928104b06dbe6eabf005995a6) which makes the new bridge the default bridge introduced the issue.

**Comment by rigdern** [comment] 2016-08-17 00:47
@cjhopman, do you have any thoughts on this issue. Do you think my theory about your commit (c89c25f27d115c1928104b06dbe6eabf005995a6) is accurate?

**Comment by kageurufu** [comment] 2016-08-17 20:12
@rigdern the bridge is definitely the issue. I modified my MainApplication to call ``setUseOldBridge(true)`` in the ReactNativeHost subclass, and I'm now able to use AsyncStorage while debugging on Android with 0.31.0

I don't have the time to debug this issue fully beyond that, but for those experiencing this issue, I posted a workaround: https://gist.github.com/kageurufu/79e4aaa1c41cbdb147e936d7e473029d

**Comment by mkonicek** [comment] 2016-08-20 14:32
@rigdern Thanks for looking into it! I'll ping @cjhopman and @mhorowitz on fb@work messenger.

**Comment by lexs** [comment] 2016-08-23 10:44
Closing in favor of https://github.com/facebook/react-native/issues/9436

**Closed** 2016-08-23 10:44 UTC
Labels: Android, Regression
