### ISSUE TITLE
Failed to load bundle: Cannot read property 'throwIfClosureRequired' of undefined

### ISSUE THREAD

**Issue by everdrone** [facebook/react-native#18962] opened 2018-04-20 17:49 UTC
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.5.0
  Yarn: 1.5.1
  npm: 5.8.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3

## Steps to Reproduce
```
react-native init RNApp
# ...
react-native run-ios
```
or by opening RNApp.xcodeproj and hitting "run"

## Expected Behavior
App launches normally on simulator

## Actual Behavior
<img width="459" alt="screen shot 2018-04-20 at 19 41 25" src="https://user-images.githubusercontent.com/22671061/39065921-9c11bbd0-44d3-11e8-883e-34d0b7e8e884.png">

**Comment by duro** [comment] 2018-04-20 18:11
This is throwing in my tests when upgrading to `babel-preset-react-native` to 5.0.0

Does not happen on 4.x of preset with `0.55.3` of react-native installed

**Comment by godinhoaugusto** [comment] 2018-04-20 19:36
Same here

**Comment by husnaintahir** [comment] 2018-04-20 19:44
same issue, happened just now

**Comment by Amar-HBCC** [comment] 2018-04-20 19:47
Same issue happened in windows for run-android

**Comment by damiandizeo** [comment] 2018-04-20 19:47
same here, downgraded `babel-preset-react-native` to 4.0.0 but still the same

**Comment by rondaniel00** [comment] 2018-04-20 19:57
downgraded babel-preset-react-native to 4.0.0 and worked. same as the comments above.

**Comment by artisologic** [comment] 2018-04-20 21:13
First time I tried to play with `react-native` and I was greeted by the same bug too. So unfortunate for a first experience!! I can however confirm that downgrading `babel-preset-react-native` to `4.0.0` worked for me as well.

**Comment by andrewcpeltier** [comment] 2018-04-20 21:50
How do you downgrade bable-preset-react-native to 4.0.0?

**Comment by Sapulidi** [comment] 2018-04-20 22:15
@andrewcpeltier I just ran into this issue as well. Just edit the version number in your package.json file and npm install.

**Comment by VikAdvani** [comment] 2018-04-20 22:15
Also, confirming this seemed to just start to happen. Downgrading works.

**Comment by achuvm** [comment] 2018-04-20 22:16
@andrewcpeltier,

Open your `package.json` and change the `devDependencies` to:

```
  "devDependencies": {
    ...
    "babel-preset-react-native": "4.0.0",
    ...
  },
```

Then run `npm install`.

**Comment by andrewcpeltier** [comment] 2018-04-20 22:29
Yeah looks like this started happening right after the publish. But that worked! Thanks a bunch for the help @achuvm and @Sapulidi !

**Comment by GantMan** [comment] 2018-04-21 00:54
What's funny is this wasn't changed that long ago:  https://github.com/facebook/react-native/commit/34bd776af2f2529009188fced91083203a48fd40

Odd how that came right through to everyone's CLI.  Seems to me it should be tied to the specific RN version, not github?

**Comment by achuvm** [comment] 2018-04-21 01:31
@GantMan 

The issue are due to these lines in the `react-native init` script (copied below):

https://github.com/facebook/react-native/blob/57919a3edd3d09f595224e0d92f95da1df75e884/local-cli/init/init.js#L88-L97

```
    const jestDeps = (
      `jest babel-jest babel-preset-react-native react-test-renderer@${reactVersion}`
    );
    if (yarnVersion) {
      console.log('Adding Jest...');
      execSync(`yarn add ${jestDeps} --dev --exact`, {stdio: 'inherit'});
    } else {
      console.log('Installing Jest...');
      execSync(`npm install ${jestDeps} --save-dev --save-exact`, {stdio: 'inherit'});
    }
```

You can see that the `jestDeps` are `jest babel-jest babel-preset-react-native react-test-renderer@${reactVersion}`, but only the `react-test-renderer` is given a version. Which means every time anyone runs the `react-native init` script, it'll install the latest `jest`, `babel-jest` and `babel-preset-react-native` versions from `npm` as `devDependencies`.

The change you see shouldn't actually affect why we see this bug, but rather, it's the fact that version `5.0.0` of `babel-preset-react-native` was made the `latest` release about 9 hours ago: https://www.npmjs.com/package/babel-preset-react-native

**Comment by hoangvuanhdevelopervn** [comment] 2018-04-21 01:42
same here

**Comment by jaimemendozadev** [comment] 2018-04-21 03:08
I'm still get the same red error screen if I set the dev dependency to `"babel-preset-react-native": "4.0.0"`. Anybody else running into the same issue?

**Comment by jaimemendozadev** [comment] 2018-04-21 03:14
Nvm, now it works. Weird. Thanks everyone! 😄

**Comment by satish25** [comment] 2018-04-21 03:41
The same issue for me as well, after changing `"babel-preset-react-native": "4.0.0"`, it's not working...!

**Comment by mgtitimoli** [comment] 2018-04-21 04:48
This issue is caused by the fact that most of us have installed the babel version present at [depencies](https://github.com/facebook/react-native/blob/master/babel-preset/package.json#L18), that's **v7.0.0-beta.40**.

This version had an issue on **babel-plugin-transform-block-scoping**, as at this stage [babel-helper-plugin-utils](https://github.com/babel/babel/tree/v7.0.0-beta.41/packages/babel-helper-plugin-utils) had not yet been created, and this one (created on v7.0.0-beta.41) is used to set a default `{}` for the options when they are not present (see [here](https://github.com/babel/babel/blob/v7.0.0-beta.41/packages/babel-helper-plugin-utils/src/index.js#L13)), that's the case for **babel-plugin-transform-block-scoping** declared [here](https://github.com/facebook/react-native/blob/master/babel-preset/configs/main.js#L11).

The only alternative would be to use [yarn resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) and lock all the babel depedencies to latest, but sadly this doesn't work either, as metro-bundler is in the middle of the migration to babel 7 and they are still using babel-core (core package from babel version 6), so when you run the packager, everything breaks.

So based on all this, I believe that the most sane alternative would be to wait for babel-preset-react-native and metro-bundler to update their babel dependencies to latest.

**Comment by danielcolgan** [comment] 2018-04-21 05:14
Downgraded babel-preset-react-native to 4.0.0 and worked! Thank you!

**Comment by Nitingadhiya** [comment] 2018-04-21 06:56
If not work try this solution.
i) delete node_module folder.
ii) Open your package.json and change the devDependencies to:

  "devDependencies": {
    ...
    "babel-preset-react-native": "4.0.0",
    ...
  },
Then run npm install.
It's worked for me.

**Comment by rassemdev** [comment] 2018-04-21 07:10
drowgrading to "babel-preset-react-native": "4.0.0" didn't work for me :(

**Comment by Owl7** [comment] 2018-04-21 08:11
I changed to 4 but error still.

**Comment by pritam-patil** [comment] 2018-04-21 08:48
For those who have updated the "babel-preset-react-native" to version "4.0.0", and still seeing the issue:
1. Run `npm install` again before running the app with `react-native run-android` or `react-native run-ios`
2. If you still see the issue, clear 'node_modules' directory, run `rm -rf node_modules/` from your project directory and repeat step 1. 

Worked for me with the environment:

- OS: Ubuntu 17.04 64-bit
- Project dependancies (package.json): 

```
"dependencies": {
    "react": "16.3.1",
    "react-native": "0.55.3"
  },
  "devDependencies": {
    "babel-jest": "22.4.3",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.4.3",
    "react-test-renderer": "16.3.1"
  }

**Comment by lehoangnam97** [comment] 2018-04-21 08:57
Owl7 Did you run "npm install" yet ?

**Comment by Owl7** [comment] 2018-04-21 08:59
@lehoangnam97 of course

**Comment by Owl7** [comment] 2018-04-21 09:08
@pritam-patil error still. 😢

**Comment by Owl7** [comment] 2018-04-21 09:14
@pritam-patil @lehoangnam97 Started work, I restarted the computer. 😄

**Comment by garmjs** [comment] 2018-04-21 09:28
@Owl7 looks like cache issue, I was having the same problem

**Comment by rassemdev** [comment] 2018-04-21 09:36
after restarting my pc and then downgrading to "babel-preset-react-native": "4.0.0", solved the problem. Thanks @Owl7

**Comment by haiptsn481991** [comment] 2018-04-21 10:13
Can you give me specific instructions?
Step 1: Run cmd
Step 2: react-native init app-name
Then how to fix the error.
thanks

**Comment by haiptsn481991** [comment] 2018-04-21 10:35
thanks @husnaintahir ,
It already works

WARN eslint-plugin-react-native@3.2.1 requires a peer of eslint@^3.17.0 || ^ 4.0.0 but none is installed. You must install dependencies yourself peer.
This error installs any package. thank you

**Comment by sasos90** [comment] 2018-04-21 11:29
Guys don't forget to remove yarn.lock or package-lock.json, before you do yarn install (npm install), otherwise the change of the version won't help ;)

**Comment by shobhitnpm** [comment] 2018-04-21 12:10
downgrading to "babel-preset-react-native": "4.0.0"  works!! Thanks to damiandizeo.
just change version of above dependency to 4.0.0 in package.json and run npm install, it will work.

**Comment by Ikiugu** [comment] 2018-04-21 13:10
Just confirmed, downgrading babel to "babel-preset-react-native": "4.0.0" in the project's package.json works. Thanks @damiandizeo

**Comment by marksturm** [comment] 2018-04-21 14:50
if you run into trouble after changing "babel-preset-react-native": "4.0.0" ... run in your terminal:
 
`watchman watch-del-all && rm -rf $TMPDIR/react-* && rm -rf node_modules/ && npm cache clean && npm install && npm start -- --reset-cache
`

**Comment by kleberapsilva** [comment] 2018-04-21 16:05
"devDependencies": {
    "babel-jest": "22.4.3",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.4.3",
    "react-test-renderer": "16.3.1"
  },
Thanks

**Comment by sagaquisces** [comment] 2018-04-21 18:09
Yes, removing yarn.lock and node_modules/ and changing babel-preset-react-native in package.json got the basic app to run.

**Comment by SamilMehdiyev** [comment] 2018-04-21 19:00
Hi everyone,
To fix problem I did following steps:
1) remove node_modules folder : `rm -rf node_modules/` and package-lock.json file
2) change `"babel-preset-react-native": "4.0.0"` 
3) run `npm install`
4) restart OS. Aftering restart 'cd' to app folder and `react-native run-ios`. 

Hope it will help.

**Comment by marlonnardi** [comment] 2018-04-21 20:30
@andrewcpeltier,

Open your package.json and change the devDependencies to:

  "devDependencies": {
    ...
    "babel-preset-react-native": "4.0.0",
    ...
  },
Then run npm install.

Thanks, this worked...

**Comment by abhisheksingh1** [comment] 2018-04-21 21:37
@turnipdabeets - Are u able to run the app after changing package.json. I am able to launch the app.

**Comment by mortezaalizadeh** [comment] 2018-04-21 21:38
same issue, happened just now after upgrading to version 5

**Comment by turnipdabeets** [comment] 2018-04-21 21:57
@abhijitnukalapati - yes I am able to run the app after changing babel-preset-react-native to  "4.0.0"
Try to change package.json and then re-install node modules
`rm -rf node_modules && npm i`

**Comment by abhisheksingh1** [comment] 2018-04-21 22:00
Open your package.json and change the devDependencies to:

"devDependencies": {
...
"babel-preset-react-native": "4.0.0",
...
},
Then run **npm install**.
Don't forgot to start yarn once again  - **yarn start**
Thanks @**turnipdabeets**,  it's working.

**Comment by macloving** [comment] 2018-04-22 00:04
I am very sorry sorry, but how is this do?

> This is throwing in my tests when upgrading to babel-preset-react-native to 5.0.0
> Does not happen on 4.x of preset with 0.55.3 of react-native installed

**Comment by jinaddavid** [comment] 2018-04-22 03:34
After changing change change "babel-preset-react-native": "5.0.0" To "babel-preset-react-native": "4.0.0"

and run npm install. its works for me

Thanks so much

**Comment by Jimato** [comment] 2018-04-22 05:07
"babel-preset-react-native": "4.0.0"
it works, thanks!!!

**Comment by nikthakkar** [comment] 2018-04-22 06:02
@marksturm Thanks for the command. That worked for me finally. 
Only one thing if you are using npm version > 5 then use this
`watchman watch-del-all && rm -rf $TMPDIR/react-* && rm -rf node_modules/ && npm cache clean   
 **--force** && npm install && npm start -- --reset-cach`

**Comment by adriantoari** [comment] 2018-04-22 10:03
Thanks... It works..
"babel-preset-react-native": "4.0.0"

**Comment by hiradarshadi** [comment] 2018-04-22 12:10
@marksturm you just saved my life! <3 
thanks a lot man, that was very helpful.

**Comment by thiennhank9** [comment] 2018-04-22 14:39
u guys saved me, thank you so much

**Comment by stevemu** [comment] 2018-04-22 15:08
Using `"babel-preset-react-native": "4.0.0",` works for me. Thank you!

**Comment by uneeb123** [comment] 2018-04-22 20:37
What's the root cause?

**Comment by fcastaneda9725** [comment] 2018-04-23 00:25
The same problem, i solved dowgrading "babel-preset-react-native": "4.0.0" and restanting my computer, i'm on Ubuntu 17.10

**Comment by grabbou** [comment] 2018-04-23 07:43
Will get this fixed in next minor release today.

**Comment by kitze** [comment] 2018-04-23 08:43
The legend says that one day you will be able to generate a react-native project without solving random errors.

**Comment by chuwuwang** [comment] 2018-04-23 09:44
fuck you

**Comment by grabbou** [comment] 2018-04-23 09:50
@chuwuwang I am going to delete your comment and report this activity to Github. We do not accept such behavior that is way below the accepted standards. If React Native pisses you off, just don't use it. It's free world.

**Comment by AlagicAmir** [comment] 2018-04-23 10:15
downgrade babbel and run npm install is not helping ...

**Comment by kelset** [comment] 2018-12-18 13:59
(closing as inactive, there have been new issues on the bundler subject and since this issue many things changed)

(if necessary open a new issue)

**Closed by kelset** 2018-12-18 13:59 UTC
Labels: 📦Bundler
