### ISSUE TITLE
Could not list contents of '/third-party/glog-0.3.4/test-driver' - Android Release

### ISSUE THREAD

**Issue by ben-snaize** [facebook/react-native#14464] opened 2017-06-12 09:05 UTC
**Scenario**
When creating an Android release APK, the error `Could not list contents of '/Users/user/project/node_modules/react-native/third-party/glog-0.3.4/test-driver'` is encountered which causes the build to fail.

**Steps to Reproduce**
`npm i react-native@0.45 --save`
`cd android && ./gradlew assembleRelease && ./gradlew installRelease`

There is a folder named `third-party-podspecs` that contains the `GLog.podspec`. This probably gets expanded into another folder, `third-party` on build. Inside of this, there is a file under `glog-0.3.4/test-driver` which appears to be an alias that does not resolve.

<img width="983" alt="screen shot 2017-06-12 at 10 03 32" src="https://user-images.githubusercontent.com/13312361/27026659-6f2acbb6-4f56-11e7-9fea-f95c52c1d336.png">

There is a temporary fix which is to delete the `third-party` folder. Please can we look at getting this one corrected?

**Comment by ms88privat** [comment] 2017-06-12 23:43
https://github.com/facebook/react-native/issues/14417

**Comment by nehvaleem** [comment] 2017-06-13 19:54
also having this issue

**Comment by g4laura** [comment] 2017-06-18 00:55
I'm also having this issue.

**Comment by itinance** [comment] 2017-06-18 17:04
This worked for me: to delete the broken test-driver-link as follows

` unlink node_modules/react-native/third-party/glog-0.3.4/test-driver `

**Comment by kelset** [comment] 2017-07-04 16:50
Same issue over here, fix by @itinance works 🔥

**Comment by tapz** [comment] 2017-07-12 10:30
In addition to unlinking, I also had to remove `third-party/glog-0.3.4` in the project root.

**Comment by ujwal-setlur** [comment] 2017-07-14 21:58
With RN 0.46.3, @itinance solution worked for me.

**Comment by ujwal-setlur** [comment] 2017-07-14 22:24
This issue occurs in 0.46.3 only if you do an android build **after** you do an iOS build. That link gets created during the iOS build. If you do an android build after a fresh npm install, it's fine.

It's ironic that I ran into this issue after I upgraded after https://github.com/facebook/react-native/issues/14382#issuecomment-315233853 was fixed in 0.46.3

**Comment by ujwal-setlur** [comment] 2017-07-14 23:37
Please see https://github.com/facebook/react-native/commit/5c53f89dd86160301feee024bce4ce0c89e8c187#commitcomment-23107918

**Comment by ujwal-setlur** [comment] 2017-07-14 23:39
This is fixed in master branch. Guess we need to wait for 0.47.0

**Comment by hramos** [comment] 2017-09-21 15:09
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Closed by hramos** 2017-09-21 15:09 UTC
Labels: Icebox

**Comment by alexgvozden** [comment] 2017-10-25 18:44
issue does happen, I deleted the folder third_party and it worked...
I have this issue with XCode too which running ios-install-glog solves

**Comment by devbriguy** [comment] 2018-01-29 20:34
After unlink, I ran the command and get stuck at `:app:bundleReleaseJsAndAssets` #10078

**Comment by thomashagstrom** [comment] 2018-09-18 07:15
We're on react-native *0.55.3* and get this for release build Android, so I don't understand why it's closed.

We have no `node_modules/react-native/third-party` folder, as seen in screenshot.

`gradlew assembleRelease -s`

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Failed to capture snapshot of input files for task ':app:bundleReleaseJsAndAssets' property '$1' during up-to-date check.
> > Could not list contents of '/Users/thomas/Source/ParkeraApp.React/mobile/third-party/glog-0.3.4/test-driver'. Couldn't follow symbolic link.
> 
> * Try:
> Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Exception is:
> org.gradle.api.UncheckedIOException: Failed to capture snapshot of input files for task ':app:bundleReleaseJsAndAssets' property '$1' during up-to-date check.

![package_json](https://user-images.githubusercontent.com/396545/45670158-57231800-bb22-11e8-9c97-05f1ed4ceb3a.jpg)
