### ISSUE TITLE
TouchableNativeFeedback's ripples aren't affected by borderRadius on Android 9

### ISSUE THREAD

**Issue by jeffchienzabinet** [facebook/react-native#6480] opened 2016-03-16 04:57 UTC
This is a bit of a problem when creating buttons with borderRadius and TouchableNativeFeedback, and the ripples extend out. I'm not an expert but I suppose setNativeBackground needs to get the corner radius when making the mask for the RippleDrawable and setBorderRadius may need to remake the background drawable somehow.

**Comment by jonathanpalma** [comment] 2016-06-04 16:11
Attached the following images to represent graphically what is proposed

![before](https://cloud.githubusercontent.com/assets/12414771/15800623/623d4082-2a3b-11e6-9891-e57bbe4a4c5c.gif)
![after](https://cloud.githubusercontent.com/assets/12414771/15800622/623aebb6-2a3b-11e6-8c6e-589f3bbc7df8.gif)

Images were taken from <a href="http://michaelevans.org/blog/2015/05/07/android-ripples-with-rounded-corners/">Michael Evans Blog - Android Ripples With Rounded Corners</a>

**Comment by antoinerousseau** [comment] 2016-07-14 01:02
It's supposed to be implemented in https://github.com/facebook/react-native/pull/6515 but I can't make it work :/

**Comment by antoinerousseau** [comment] 2016-07-14 01:12
I realize that PR got reverted

**Comment by reyesr** [comment] 2016-07-25 05:52
FWIW, as of 0.30, the ripple effect works with respect to the borderRadius of its parent <View>, but it requires its borderless effect to be set to true.
Eg:

`<View style={{borderRadius: 24, backgroundColor: '#F66', width: 48,height: 48}}>
    <TouchableNativeFeedback background={TouchableNativeFeedback.Ripple('#AAF', true)}>
[snip]
    </TouchableNativeFeedback>
</View>
`
If this is the intented effect, it should probably be made explicit, and added to the documentation. It it's a side effect (no pun intented), #6515 still makes sense.

**Comment by tituswoo** [comment] 2016-07-25 09:02
@reyesr OMG thank you so much for this!  👍

**Comment by jonathanpalma** [comment] 2016-08-05 02:00
@reyesr IT WORKS!!! Thank you so much buddy!! :raised_hands:

**Comment by ericvicenti** [comment] 2016-11-14 20:28
Looks like this is resolved. Feel free to open a new issue if you're still having troubles with it

**Comment by satya164** [comment] 2018-08-20 10:04
Re-opening since this issue has re-surfaced on Android P.

**Comment by ferrannp** [comment] 2018-08-20 10:50
Just to illustrate from Android P:

![screenshot_20180820-124834_2](https://user-images.githubusercontent.com/774577/44336358-88eb8500-a477-11e8-8ea7-b83b62d626b2.png)

**Comment by lalosh** [comment] 2018-09-01 12:37
@reyesr thank you..yet it worked for me after I added a View inside TochableNativeFeedback with the same parent style .. like:
        <View style={{ borderRadius: 20, backgroundColor: '#2f2', width: 80, height: 80 }}>
            <TouchableNativeFeedback background={TouchableNativeFeedback.Ripple('#AAF', true)}>
                <View style={{ borderRadius: 20, backgroundColor: '#2f2', width: 80, height: 80 }}>
                    <Text> test button </Text>
                </View>
             </TouchableNativeFeedback> 
         </View>

**Comment by yaronlevi** [comment] 2018-09-26 14:37
0.55 + Android Pie = The ripple is not affected by the borderRadius.
Tried all the variations (View from outside, View from inside, both).

**Comment by aMarCruz** [comment] 2018-10-11 23:31
This issue was never resolved, the solution given in a comment above was a hack.

**Comment by yaronlevi** [comment] 2018-10-19 12:35
Any updates on the issue?

**Comment by balthazar** [comment] 2018-11-14 15:47
```js
<View style={{ borderRadius: 5, overflow: 'hidden' }}>
  <TouchableNativeFeedback
        onPress={() => {}}
        background={TouchableNativeFeedback.Ripple('red')}
      >
        {'CLICK CLICK'}
      </TouchableNativeFeedback>
</View>
```

You guys should try to wrap your `TouchableNativeFeedback` in a view with a ``border-radius` and an hidden overflow.

**Comment by aMarCruz** [comment] 2018-11-14 16:30
@balthazar , wrapping the touchable hides the effect of borderless ripple, as desired in Floating Action Buttons components.

**Comment by balthazar** [comment] 2018-11-14 16:55
@aMarCruz I'm not talking about borderless ripples here, as my example shows.

**Comment by RichardLindhout** [comment] 2019-01-14 22:19
For me it works when I set in TouchableRipple.js the useForeground true + borderless false
```
  disabled={disabled}
          useForeground={true}
          background={
            background != null
              ? background
              : TouchableNativeFeedback.Ripple(calculatedRippleColor, false)
          }
```

Also on e.g. the FAB its needs an overflow: 'hidden' style. Works for me on both iOS and Android!
```
  touchable: {
    borderRadius: 28,
    overflow: 'hidden',
  },
```

I'm running the latest Android (9 Pie)

**Comment by RichardLindhout** [comment] 2019-01-14 22:24
I'm seeing some side effects in e.g. the header for the back button is a square now.

**Comment by ferrannp** [comment] 2019-01-30 11:09
@RichardLindhout but did you try for example with a circular button? Some view that has `borderRadius` like https://github.com/facebook/react-native/issues/6480#issuecomment-414275796.

**Comment by rickhanlonii** [comment] 2019-03-19 16:39
Thanks @RichardLindhout

If anyone is still experiencing this on the latest release please submit a new issue

**Comment by satya164** [comment] 2019-03-19 16:48
@rickhanlonii That's a workaround which we can't use if `oveflow: hidden` is not desirable. The behavior is still different between Android versions and buggy.

**Comment by rickhanlonii** [comment] 2019-03-19 16:57
@satya164 do you think we should keep this open so contributors need to read though the whole thread from 2016 to understand what the current status is or should we file a new issue with the current state of the bug and no superfluous/outdated information?

**Comment by satya164** [comment] 2019-03-19 17:09
@rickhanlonii someone can open a new issue, but this issue lists some workarounds which are useful to people coming from google, which is better than a new empty issue imo, given that this thread isn't quite short.

**Comment by tsvetan-ganev** [comment] 2019-04-02 13:22
It's 2019 and I can't create a touchable element with border radius which works on both platforms without using dirty hacks.

**Comment by nhunzaker** [comment] 2019-06-20 15:17
I poked around with this a bit. One solution is to change the mask on the ripple drawable to be a ShapeDrawable with a corner radius. So instead of:

https://github.com/facebook/react-native/blob/cbf1b39c662eeede356214ba276a105604b75bb2/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactDrawableHelper.java#L78-L86

ColorDrawable is just a rectangle, but it can be replaced with a ShapeDrawable that uses a RoundRectShape. So you could do:

```java
private static Drawable getRippleMask() {
    // Border radii
    float[] outerRadii = new float[] { 12f, 12f, 12f, 12f, 12f, 12f, 12f, 12f };

    RoundRectShape r = new RoundRectShape(outerRadii, null, null);

    ShapeDrawable shapeDrawable = new ShapeDrawable(r);
    shapeDrawable.getPaint().setColor(Color.WHITE);

    return shapeDrawable;
  }

  public static Drawable createDrawableFromJSDescription(Context context, ReadableMap drawableDescriptionDict) {
  // Later on
  return new RippleDrawable(colorStateList, null, mask);
}
```

This works!

![Screenshot_1561043846](https://user-images.githubusercontent.com/590904/59860531-de145380-9333-11e9-98e6-6970821e3e23.png)

However it needs to:

1. Account for border-width (the mask should only apply to the edge of the border)
2. Account for the actual border radius

So I think I _might_ have a fix for this! I just need to figure out how to pass the border and corner radius fields `ReactDrawableHelper`.

**Comment by nhunzaker** [comment] 2019-06-21 02:42
I sent out a possible fix for this here:
https://github.com/facebook/react-native/pull/25342

**Comment by satya164** [comment] 2019-09-19 13:00
Fixed in https://github.com/facebook/react-native/commit/14b455f69a30d128db384749347f41b03b9a6000

**Comment by grabbou** [comment] 2019-10-02 07:55
Unfortunately, the commit that was supposed to fix this issue introduced a major regression and we had to roll it back.

I am reopening this issue as it's still the case. Hopefully, prior work by @nhunzaker can be helpful to work on a fix once again.

**Comment by InceptSolutions** [comment] 2019-11-30 10:46
My fix to this was to add `overflow:'hidden'` and the needed `borderRadius` to the parent view containing the `TouchableNativeFeedback` and then add `useForeground={true}` to the `TouchableNativeFeedback` :)

**Comment by RichardLindhout** [comment] 2019-11-30 10:47
> For me it works when I set in TouchableRipple.js the useForeground true + borderless false
> 
> ```
>   disabled={disabled}
>           useForeground={true}
>           background={
>             background != null
>               ? background
>               : TouchableNativeFeedback.Ripple(calculatedRippleColor, false)
>           }
> ```
> 
> Also on e.g. the FAB its needs an overflow: 'hidden' style. Works for me on both iOS and Android!
> 
> ```
>   touchable: {
>     borderRadius: 28,
>     overflow: 'hidden',
>   },
> ```
> 
> I'm running the latest Android (9 Pie)

I was first :-P

**Comment by InceptSolutions** [comment] 2019-11-30 11:04
@RichardLindhout Hahahaha, nice one :D

**Comment by Kleinhummel** [comment] 2020-02-06 17:30
> FWIW, as of 0.30, the ripple effect works with respect to the borderRadius of its parent , but it requires its borderless argument to be set to true.
> Eg:
> 
> `<View style={{borderRadius: 24, backgroundColor: '#F66', width: 48,height: 48}}> <TouchableNativeFeedback background={TouchableNativeFeedback.Ripple('#AAF', true)}> [snip] </TouchableNativeFeedback> </View> `
> If this is the intented effect, it should probably be made explicit, and added to the documentation. It it's a side effect (no pun intented), #6515 still makes sense.

This causes the ripple to completely ignore the size of the button:

![Button](https://user-images.githubusercontent.com/47432229/73962348-851f1d00-490e-11ea-912a-3f840afb99f0.png)

> My fix to this was to add `overflow:'hidden'` and the needed `borderRadius` to the parent view containing the `TouchableNativeFeedback` and then add `useForeground={true}` to the `TouchableNativeFeedback` :)

This was also the working solution for me. But what if I want the ripples in the background and not in the foreground??

**Comment by likrot** [comment] 2020-07-07 10:41
> > FWIW, as of 0.30, the ripple effect works with respect to the borderRadius of its parent , but it requires its borderless argument to be set to true.
> > Eg:
> > `<View style={{borderRadius: 24, backgroundColor: '#F66', width: 48,height: 48}}> <TouchableNativeFeedback background={TouchableNativeFeedback.Ripple('#AAF', true)}> [snip] </TouchableNativeFeedback> </View> `
> > If this is the intented effect, it should probably be made explicit, and added to the documentation. It it's a side effect (no pun intented), #6515 still makes sense.
> 
> This causes the ripple to completely ignore the size of the button:
> 
> ![Button](https://user-images.githubusercontent.com/47432229/73962348-851f1d00-490e-11ea-912a-3f840afb99f0.png)
> 
> > My fix to this was to add `overflow:'hidden'` and the needed `borderRadius` to the parent view containing the `TouchableNativeFeedback` and then add `useForeground={true}` to the `TouchableNativeFeedback` :)
> 
> This was also the working solution for me. But what if I want the ripples in the background and not in the foreground??

Hi,

I don't know if do you have still a problem, but this is how I'm using it ( "react-native": "0.62.2",):

```
    buttonShape: {
        borderRadius: 50,
        overflow: 'hidden',
    },
    button: {
        backgroundColor:  'green',
        height: 80,
        width: 80,
    },

[...]

            <View style={styles.buttonShape}>
                <TouchableFeedback>
                    <View style={styles.button}>
                        <Text>
                            Floating btn
                        </Text>
                    </View>
                </TouchableFeedback>
            </View>
```

**Comment by Bardiamist** [comment] 2020-07-16 05:13
Same problem in Pressable =\

**Comment by tpakhoa1996** [comment] 2020-08-26 14:43
I tried every possible ways and this problem still persist. Are there any solutions for 0.63.2 yet?

**Comment by RichardLindhout** [comment] 2020-08-26 15:59
> For me it works when I set in TouchableRipple.js the useForeground true + borderless false
> 
> ```
>   disabled={disabled}
>           useForeground={true}
>           background={
>             background != null
>               ? background
>               : TouchableNativeFeedback.Ripple(calculatedRippleColor, false)
>           }
> ```
> 
> Also on e.g. the FAB its needs an overflow: 'hidden' style. Works for me on both iOS and Android!
> 
> ```
>   touchable: {
>     borderRadius: 28,
>     overflow: 'hidden',
>   },
> ```
> 
> I'm running the latest Android (9 Pie)

This still works but it's in the hidden comments now..

**Comment by mrousavy** [comment] 2020-11-18 18:05
The `<Pressable>` doesn't have a `useForeground` prop, how are we supposed to show ripple effects with buttons that have backgrounds (such as a LinearGradient) in a Pressable?

**Comment by panjiahnh** [comment] 2021-01-20 20:26
Is there any update and better solution to this? I've already tried each solution like wrapping the TouchableNativeFeedback in View, setForeground to true, overflow hidden, etc but none of them works. I run it on my phone on Android Pie.

**Comment by RichardLindhout** [comment] 2021-01-20 20:28
> Is there any update and better solution to this? I've already tried each solution like wrapping the TouchableNativeFeedback in View, setForeground to true, overflow hidden, etc but none of them works. I run it on my phone on Android Pie.

Have you explicitly set the borderless={false} + adding a view around it with overflow:'hidden' and the same borderRadius as the ripple?

**Comment by panjiahnh** [comment] 2021-01-20 20:40
> Have you explicitly set the borderless={false} + adding a view around it with overflow:'hidden' and the same borderRadius as the ripple?

I did. But in this case, the ripple doesn't appear at all. There's no feedback when pressing the button. 

This is the code:

```
    <View
      style={{ backgroundColor, borderRadius: 16, overflow: "hidden" }}
    >
      <TouchableNativeFeedback
        onPress={onPress}
        background={TouchableNativeFeedback.Ripple(rippleColor, false, 16)}
      >
        {children}
      </TouchableNativeFeedback>
    </View>
```

**Comment by RichardLindhout** [comment] 2021-01-20 20:51
> For me it works when I set in TouchableRipple.js the useForeground true + borderless false
> 
> ```
>   disabled={disabled}
>           useForeground={true}
>           background={
>             background != null
>               ? background
>               : TouchableNativeFeedback.Ripple(calculatedRippleColor, false)
>           }
> ```
> 
> Also on e.g. the FAB its needs an overflow: 'hidden' style. Works for me on both iOS and Android!
> 
> ```
>   touchable: {
>     borderRadius: 28,
>     overflow: 'hidden',
>   },
> ```
> 
> I'm running the latest Android (9 Pie)

This did work for me

**Comment by panjiahnh** [comment] 2021-01-20 21:22
> 
> 
> Ok I found some code in the hidden comments from when I did have problems with this.
> 
> > For me it works when I set in TouchableRipple.js the useForeground true + borderless false
> > ```
> >   disabled={disabled}
> >           useForeground={true}
> >           background={
> >             background != null
> >               ? background
> >               : TouchableNativeFeedback.Ripple(calculatedRippleColor, false)
> >           }
> > ```
> > 
> > 
> > Also on e.g. the FAB its needs an overflow: 'hidden' style. Works for me on both iOS and Android!
> > ```
> >   touchable: {
> >     borderRadius: 28,
> >     overflow: 'hidden',
> >   },
> > ```
> > 
> > 
> > I'm running the latest Android (9 Pie)
> 
> This did work for me
> 
> I think in your example it should be something like
> 
> ```js-jsx
> <View
>       style={{borderRadius: 16, overflow: "hidden" }}
>     >
>       <TouchableNativeFeedback
>         onPress={onPress}
>         style={{borderRadius: 16 }}
>          useForeground={true}
>          borderless={false}
>         background={TouchableNativeFeedback.Ripple(rippleColor, false, 16)}
>       >
>         {children}
>       </TouchableNativeFeedback>
>     </View>
>     
> ```
> 
> Maybe also consider using the Pressable component instead of the TouchableNativeFeedback

TouchableNativeFeedback doesn't recognize `borderless={false}` as a prop. It's the 2nd argument of Ripple.

Seems like I'm gonna try using Pressable instead. Thanks!

**Comment by panjiahnh** [comment] 2021-01-21 04:52
Just a heads up. Instead of wrapping the Touchable inside View, I tried wrapping the View inside the Touchable. This works for me! 

```
    <TouchableNativeFeedback
      onPress={onPress}
      style={{borderRadius: 16 }}
      background={TouchableNativeFeedback.Ripple(rippleColor, false)}
      useForeground={true}
    >
      <View
        style={[
          styles.buttonContainer,
          { backgroundColor, overflow: "hidden" },
        ]}
      >
        {children}
      </View>
    </TouchableNativeFeedback>
```

**Comment by vasilestefirta** [comment] 2021-02-16 06:25
@panjiahnh's suggestion worked for me. Here's my full `Button.js` component if anyone is interested. It's using `TouchableOpacity` on iOS and `TouchableNativeFeedback` on Android.

```js
import React from 'react';
import PropTypes from 'prop-types';
import {
  StyleSheet,
  TouchableOpacity,
  TouchableNativeFeedback,
  Platform,
  Text,
  View,
  ViewPropTypes,
} from 'react-native';
import { colors, fonts } from '../../config/styles';

const Button = (props) => {
  const { style, type, children, disabled, onPress } = props;
  const isPrimary = type === 'primary';
  const isSecondary = type === 'secondary';
  const isTransparent = type === 'transparent';

  const buttonText = (
    <Text style={[styles.buttonText, !isPrimary && styles.buttonTextDark]}>{children}</Text>
  );

  if (Platform.OS === 'ios') {
    return (
      <TouchableOpacity
        style={[
          styles.button,
          isPrimary && styles.buttonPrimary,
          isSecondary && styles.buttonSecondary,
          style,
          disabled && styles.buttonDisabled,
        ]}
        onPress={onPress}
        disabled={disabled}
      >
        {buttonText}
      </TouchableOpacity>
    );
  }

  return (
    <TouchableNativeFeedback
      onPress={onPress}
      disabled={disabled}
      background={
        Platform.Version >= 21
          ? TouchableNativeFeedback.Ripple(
              isPrimary || isSecondary ? colors.whiteBg : colors.blueBg,
              false
            )
          : TouchableNativeFeedback.SelectableBackground(5)
      }
      useForeground={isTransparent}
    >
      <View
        style={[
          styles.button,
          isPrimary && styles.buttonPrimary,
          isSecondary && styles.buttonSecondary,
          isTransparent && { overflow: 'hidden' },
          style,
          disabled && styles.buttonDisabled,
        ]}
      >
        {buttonText}
      </View>
    </TouchableNativeFeedback>
  );
};

Button.propTypes = {
  onPress: PropTypes.func,
  style: ViewPropTypes.style,
  type: PropTypes.oneOf(['primary', 'secondary', 'transparent']),
  children: PropTypes.oneOfType([PropTypes.string, PropTypes.array]),
  disabled: PropTypes.bool,
};

Button.defaultProps = {
  onPress: (f) => f,
  style: {},
  type: 'primary',
  children: '',
  disabled: false,
};

const styles = StyleSheet.create({
  button: {
    borderRadius: 27,
    height: 45,
    paddingHorizontal: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonPrimary: {
    backgroundColor: colors.blueBg,
  },
  buttonSecondary: {
    backgroundColor: colors.greenBg,
  },
  buttonText: {
    color: '#FFF',
    fontSize: 16,
    fontFamily: fonts.regular,
    letterSpacing: 1.15,
    textAlign: 'center',
  },
  buttonTextDark: {
    color: colors.darkBlueText,
  },
  buttonDisabled: {
    opacity: 0.3,
  },
});

export default Button;
```

**Comment by SaeedZhiany** [comment] 2021-05-23 06:41
@vasilestefirta

using `overflow: 'hidden'` hides elevation effect on android in my case. I didn't test, but maybe it hides shadows on iOS too.

**Comment by safaiyeh** [comment] 2021-08-16 16:17
Closing as @panjiahnh suggestion works. Feel free to open a new issue if this is still happening.

**Closed by safaiyeh** 2021-08-16 16:17 UTC
Labels: Platform: Android, Component: TouchableNativeFeedback, Bug

**Comment by SaeedZhiany** [comment] 2021-08-17 03:24
> Closing as @panjiahnh suggestion works. Feel free to open a new issue if this is still happening.


@safaiyeh Are you read [my comment](https://github.com/facebook/react-native/issues/6480#issuecomment-846513213)?  @panjiahnh suggestion is just a workaround and doesn't fix the problem correctly. please reopen this issue.

**Comment by dsoffiantini** [comment] 2022-03-12 01:31
> 

This solution works for the transparent button, but it does not work for the colored buttons. It looks like it does since the effect is white, but if you try changing it to black or a color, you see the square surrounding the button still.

**Comment by HeadJk** [comment] 2022-06-14 13:23
I have tried these solutions, and the ripple effect is working, but the touchable is responding to presses outside of the border radius.

The red area is where it should respond to presses, and the black area is where it is actually responding to presses.

**Comment by gaganbiswas** [comment] 2022-06-21 15:28
So, I tried a solution and it works as expected. The ripple effect works behind the background and it doesn't require useForeground={true}

```js
<View style={{ borderRadius: 30, overflow: "hidden"}}>
    <TouchableNativeFeedback
          background={TouchableNativeFeedback.Ripple("#1D4ED8", false)}
          onPress={() => {}}
    >
          <View style={{ padding: 8, borderRadius: 30 }}>
              <Ionicons name="call-outline" size={24} color={"white"} />
          </View>
    </TouchableNativeFeedback>
</View>
```

Try this out and let me know if it works for you 👯.
P.S. Change the Ripple color to suit your needs.
