### ISSUE TITLE
Picker's  onValueChange  is not fire  when picker first item 

### ISSUE THREAD

**Issue by hongshu123** [facebook/react-native#15672] opened 2017-08-28 05:02 UTC
### Is this a bug report?

Picker's  onValueChange  is not fire  when picker first item 

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Environment

1. `react-native -v`:  0.44
2. `node -v`:
3. `npm -v`:
4. `yarn --version`:

Then, specify:

- Target Platform:

- Development Operating System:

- Build tools:

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by hramos** [comment] 2017-08-29 16:29
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-08-29 16:29 UTC
