### ISSUE TITLE
Print: Entry, ":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by naxiaoguang** [facebook/react-native#14448] opened 2017-06-10 20:35 UTC
** BUILD FAILED **

The following commands produced analyzer issues:
	Analyze /Users/naxiaoguang/File/projects/untitled/node_modules/react-native/ReactCommon/yoga/yoga/YGNodeList.c

	Analyze /Users/naxiaoguang/File/projects/untitled/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.c
(2 commands with analyzer issues)

The following build commands failed:
	PhaseScriptExecution Install\ Third\ Party /Users/naxiaoguang/File/projects/untitled/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/double-conversion.build/Script-190EE32F1E6A43DE00A8543A.sh
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/untitled.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/untitled.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by Mikael491** [comment] 2017-06-10 23:39
What version of RN and NPM are you on? @naxiaoguang

**Comment by naxiaoguang** [comment] 2017-06-12 06:05
"dependencies": {
		"react": "16.0.0-alpha.12",
		"react-native": "0.45.1"
	},
	"devDependencies": {
		"babel-jest": "20.0.3",
		"babel-preset-react-native": "1.9.2",
		"jest": "20.0.4",
		"react-test-renderer": "16.0.0-alpha.12"
	},


npm : 4.2.0

**Comment by hramos** [comment] 2017-06-12 20:54
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-12 20:54 UTC

**Comment by hramos** [comment] 2017-08-04 06:51
Duplicate of #14423
