### ISSUE TITLE
 com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'i.readDir')

### ISSUE THREAD

**Issue by yjchen920927** [facebook/react-native#15463] opened 2017-08-11 08:45 UTC
Recently, we found a problem in Android when set minifyEnabled = true , the problem's crash log as follows when start app：
08-11 16:21:01.574 17035-17067/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                                                   Process: com.test.jpush, PID: 17035
                                                   com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'i.readDir'), stack:
                                                   <unknown>@863:183
                                                   n@2:557
                                                   i@2:348
                                                   t@2:210
                                                   <unknown>@862:243
                                                   n@2:557
                                                   i@2:348
                                                   t@2:210
                                                   <unknown>@861:194
                                                   n@2:557
                                                   i@2:348
                                                   t@2:210
                                                   <unknown>@859:350
                                                   n@2:557
                                                   i@2:348
                                                   t@2:210
                                                   <unknown>@848:311
                                                   n@2:557
                                                   i@2:348
                                                   t@2:210
                                                   <unknown>@847:194
                                                   n@2:557
                                                   i@2:348
                                                   t@2:210
                                                   <unknown>@844:301
                                                   n@2:557
                                                   i@2:348
                                                   t@2:210
                                                   <unknown>@842:325
                                                   n@2:557
                                                   i@2:348
                                                   t@2:210
                                                   <unknown>@682:733
                                                   n@2:557
                                                   i@2:348
                                                   t@2:210
                                                   <unknown>@675:312
                                                   n@2:557
                                                   i@2:348
                                                   t@2:210
                                                   <unknown>@657:311
                                                   n@2:557
                                                   i@2:348
                                                   t@2:210
                                                   <unknown>@13:322
                                                   n@2:557
                                                   i@2:348
                                                   t@2:210
                                                   <unknown>@12:24
                                                   n@2:557
                                                   i@2:278
                                                   t@2:210
                                                   global code@904:9
                                                   
                                                       at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:97)
                                                       at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:81)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:318)
                                                       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
                                                       at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                       at android.os.Looper.loop(Looper.java:185)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                       at java.lang.Thread.run(Thread.java:761)

**Comment by hramos** [comment] 2017-08-15 17:27
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-08-15 17:27 UTC
