### ISSUE TITLE
iOS Build Fails (expo@52.0.0-preview.5 and react-native@0.76.0)

### ISSUE THREAD

**Issue by emregngr** [facebook/react-native#47221] opened 2024-10-27 08:45 UTC
### Description

I’m encountering an issue where my project builds and runs successfully on Android, but fails to build on iOS. The error occurs when attempting to run on either an iOS simulator or a physical device. Detailed information and error messages are provided below.

### Steps to reproduce

<img width="1176" alt="Ekran Resmi 2024-10-27 11 33 09" src="https://github.com/user-attachments/assets/da60b5c9-b9a4-4b15-97e6-f867da63642f">

### React Native Version

0.76.0

### Affected Platforms

Runtime - iOS

### Areas

Fabric - The New Renderer, TurboModule - The New Native Module System, Bridgeless - The New Initialization Flow

### Output of `npx react-native info`

```text
System:
      OS: macOS 15.0.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.10.0 - ~/.nvm/versions/node/v22.10.0/bin/node
      npm: 10.9.0 - ~/.nvm/versions/node/v22.10.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
    IDEs:
      Android Studio: 2024.1 AI-241.18034.62.2412.12266719
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~11.0.15 => 11.0.15 
      expo: ^52.0.0-preview.5 => 52.0.0-preview.5 
      expo-router: ~3.5.23 => 3.5.23 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.0 => 0.76.0 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      expo-cli: 6.3.12
    Expo Workflow: bare
```

### Stacktrace or Logs

```text
'ReactCommon/RCTHost.h' file not found
```

### Reproducer

https://github.com/emregngr/fridayMessages

### Screenshots and Videos

<img width="1176" alt="Ekran Resmi 2024-10-27 11 33 09" src="https://github.com/user-attachments/assets/6ab219b3-6499-44c6-8eac-a51d2940cd38">

**Comment by cipolleschi** [comment] 2024-10-27 16:13
@emregngr thanks for the issue. SDK52 is still in beta, have you tried opening the issue in the [expo repo]( https://github.com/expo/expo) first? They might be more helpful.

If then they discover that the problem is in React Native, we are more than happy than look into that.

**Comment by brentvatne** [comment] 2024-10-29 23:05
it looks like this was related to static frameworks and fixed in https://github.com/expo/expo/pull/32358

update to the latest sdk 52 beta: `npx expo install expo@next --fix`

**Closed by brentvatne** 2024-10-29 23:05 UTC
Labels: Platform: iOS, Needs: Author Feedback, Type: New Architecture, 0.76
