### ISSUE TITLE
Border color bleeding bug when border radius is set.

### ISSUE THREAD

**Issue by joonhocho** [facebook/react-native#10823] opened 2016-11-09 04:47 UTC
![img_8660](https://cloud.githubusercontent.com/assets/930795/20127467/48ddc406-a5f4-11e6-84ea-fd17227fe2b5.PNG)

As you can see in the picture, border colors are bleeding when `borderRadius` is set.
It only happens when I use corner border radius such as `borderBottomLeftRadius`, `borderBottomRightRadius`.

Here's style for the node: 

```
    borderWidth: StyleSheet.hairlineWidth,
    borderRightWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: 2 * StyleSheet.hairlineWidth,
    borderColor: colors.itemBorder,
    borderRightColor: '#bbbcbd',
    borderBottomColor: '#bbbcbd',
    borderBottomLeftRadius: 4,
    borderBottomRightRadius: 4,
    overflow: 'hidden',
```

I've tried with different colors and it still happens.

Tested both on iOS simulator and real device iPhone 6 Plus. Same bug.
Haven't tested on Android.

**Comment by thomasobrien99** [comment] 2016-11-10 23:43
+1 to this issue, screenshot from iPhone 6. Style for code is:
  scaleLevels: {
    backgroundColor: colors.deepSkyBlue1,
    borderColor: colors.deepSkyBlue1,
    borderRadius: dimensions.borderRadius, // 4
    borderWidth: dimensions.borderWidth, // 1
    flexDirection: 'row'
  },
scaleLevel: {
    alignItems: 'center',
    borderColor: colors.deepSkyBlue1,
    borderLeftWidth: dimensions.borderWidth // 1,
    flex: 1,
    height: dimensions.scaleLevelHeight,
    justifyContent: 'center'
  },
scaleLevelFirst: {
    borderBottomLeftRadius: 3,
    borderLeftWidth: 0,
    borderTopLeftRadius: 3
  },
scaleLevelLast: {
    borderBottomRightRadius: 3,
    borderTopRightRadius: 3
  }
![image](https://cloud.githubusercontent.com/assets/13715890/20198952/6c118dae-a75c-11e6-8c5b-94b8a2b88643.png)

**Comment by thomasobrien99** [comment] 2016-11-10 23:44
Doesn't seem to affect smaller devices

**Comment by jevakallio** [comment] 2016-11-13 18:46
There was an issue https://github.com/facebook/react-native/issues/6082 that was closed by @lacker for lack of reproducible example. 

Here's a minimal repro on RNPlay: https://rnplay.org/apps/XiWz1g - It appears this issue happens when you provide border radius to some corners, but not all. Affects iOS only.

<img width="313" alt="screen shot 2016-11-13 at 10 45 30" src="https://cloud.githubusercontent.com/assets/1203949/20247938/5ac84a72-a98e-11e6-94b5-6ca3ba05d45f.png">

**Comment by MiLeung** [comment] 2017-01-12 19:20
Same issue.  Any janky code workarounds for this issue yet?

![fullsizerender 2](https://cloud.githubusercontent.com/assets/9166324/21904574/03b14eb4-d8b9-11e6-8c5c-562477317e79.jpg)
![fullsizerender 3](https://cloud.githubusercontent.com/assets/9166324/21904575/03c02e02-d8b9-11e6-94dd-52666c705237.jpg)
![fullsizerender 4](https://cloud.githubusercontent.com/assets/9166324/21904576/03cabd22-d8b9-11e6-84c4-63f692c380b7.jpg)
![fullsizerender](https://cloud.githubusercontent.com/assets/9166324/21904577/03dca4ec-d8b9-11e6-9744-fa2b28df91f6.jpg)

**Comment by code-by** [comment] 2017-02-15 17:00
Same problem for Android. borderRadius / backgroundColor not works together

**Comment by bedemiralp** [comment] 2017-04-01 00:21
#11897

**Comment by bedemiralp** [comment] 2017-04-01 00:24
This problem is also reported under #11897

**Comment by hramos** [comment] 2017-07-20 22:33
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/border-color-bleeding-bug-when-border-radius-is-set

**Closed by hramos** 2017-07-20 22:33 UTC
Labels: Icebox

**Comment by alenia** [comment] 2017-08-22 00:49
@MiLeung the janky workaround is to not put a border on the edge opposite the radius

              
A   _____________ B
   |                      | 
   |                      | 
   |_____________/ 
D                         C

for a quadrilateral ABCD if corner C has a border radius, then edge AD should not have a border (considering putting a border on its neighbor instead)
I.E. if borderTopRightRadius = 4, then if the bottom right corner has an artifact borderBottom should be 0 (or the borderBottomRightRadius should be defined)
