### ISSUE TITLE
WebView onMessage only receive one message

### ISSUE THREAD

**Issue by fov42550564** [facebook/react-native#13042] opened 2017-03-21 02:56 UTC
```js
module.exports = React.createClass({
    test () {
        this.webview.postMessage('I am from react');
        this.webview.postMessage('I am from react1');
    },
    onMessage(e) {
        console.log(e.nativeEvent.data);
    },
    render () {
        return (
            <View style={{flex: 1, paddingTop: 60}}>
                <Button onPress={this.test}>测试</Button>
                <WebView
                    ref={(ref)=>{this.webview=ref}}
                    onMessage={this.onMessage}
                    source={{html: `
                        <script>
                            document.addEventListener('message', function(e) {
                                window.postMessage(e.data + '[back]');
                                window.postMessage(e.data + '[back]');
                                window.postMessage(e.data + '[back]');
                            });
                        </script>`}
                    }
                    />
            </View>
        );
    },
});
```
react-native: 0.42.0
on ios, only receive one time `I am from react1[back]`
on android, receive nothing

**Comment by fov42550564** [comment] 2017-03-21 03:00
react-native-webview-bridge is work well.

**Comment by hramos** [comment] 2017-03-21 18:36
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-03-21 18:36 UTC
