### ISSUE TITLE
Can't add borderStyle for single side border of a view

### ISSUE THREAD

**Issue by Bob1993** [facebook/react-native#9343] opened 2016-08-11 09:07 UTC
I wanna set borderStyle for  bottom border of a view, so I have following code: 
```
<View style={{borderColor: 'red', borderWidth: 0, borderBottomWidth: 1, borderStyle: 'dashed'}}>
  <Text>Example</Text>
</View>
```

As well, I get warning like this: `Unsupported dashed / dotted border style`.  
Is there any ways to solve the problem ? Thanks any way...

------------------------------------------------------------------
* version of react native: 0.30.0

**Comment by rmevans9** [comment] 2016-08-11 11:22
Based upon looking at the code this looks like a intentional limitation. There is code that specifically checks to see if both the color and width are the same on all sides if trying to use a dashed or dotted border. I would venture to guess that if you were to set borderWidth to 1 instead of just borderBottomWidth that the warning will go away and your border will show.

**Comment by Bob1993** [comment] 2016-08-11 11:54
@rmevans9 I just need bottomBorderWidth, not for each border. And thanks a lot for your explanation

**Comment by rmevans9** [comment] 2016-08-11 11:57
A workaround might be to put a view within the containing view, push it to the bottom and give it the border with a height of 0 (or you might need to do 1). This will make it seem like you have a border just on the bottom.

**Comment by Bob1993** [comment] 2016-08-12 02:07
yeah, It could be a pretty resolution~

**Comment by RichardLindhout** [comment] 2016-08-12 10:26
Looks like   this https://github.com/facebook/react-native/issues/9262

**Comment by rmevans9** [comment] 2016-08-12 17:03
Closing this as a duplicate of #7838 since it is exactly the same. @Bob1993 you can subscribe over there to see updates.

**Comment by rmevans9** [comment] 2016-08-12 17:03
@facebook-github-bot duplicate #7838

**Comment by facebook-github-bot-2** [comment] 2016-08-12 17:03
@rmevans9 tells me this issue is a duplicate of #7838. Let's discuss there, closing this one.

**Closed by facebook-github-bot-2** 2016-08-12 17:03 UTC
Labels: Ran Commands

**Comment by shubham81407** [comment] 2017-11-22 13:32
Try to add borderRadius: ''your value here'
