### ISSUE TITLE
'yoga/Yoga.h' file not found

### ISSUE THREAD

**Issue by Aleksandriukas** [facebook/react-native#44340] opened 2024-04-30 16:30 UTC
### Description

Hey, Im using pnpm and trying to enable use_frameworks (`use_frameworks! :linkage => :static`). How can I fix this error ? `'yoga/Yoga.h' file not found`

### Steps to reproduce

1. Add `use_frameworks! :linkage => :static` into Podfile. 
2. Run `pod install`. 
3. Build project in Xcode.

### React Native Version

0.74.0

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.4.1
  CPU: (12) arm64 Apple M2 Pro
  Memory: 292.22 MB / 32.00 GB
  Shell:
    version: 3.2.57
    path: /bin/bash
Binaries:
  Node:
    version: 20.11.0
    path: /usr/local/bin/node
  Yarn: Not Found
  npm:
    version: 10.2.4
    path: /usr/local/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK:
    API Levels:
      - "30"
      - "33"
      - "34"
    Build Tools:
      - 30.0.3
      - 33.0.0
      - 33.0.1
      - 34.0.0
    System Images:
      - android-24 | Google APIs ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2023.2 AI-232.10300.40.2321.11668458
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 19.0.2
    path: /usr/bin/javac
  Ruby:
    version: 3.3.0
    path: /opt/homebrew/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: ^18.2.0
  react-native:
    installed: 0.74.0
    wanted: ^0.74.0
  react-native-macos: Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
'yoga/Yoga.h' file not found
```

### Reproducer

n/a

**Comment by NickGerleman** [comment] 2024-04-30 20:31
This is a dupe of https://github.com/facebook/react-native/issues/41938

**Closed by NickGerleman** 2024-04-30 20:31 UTC
Labels: Needs: Triage :mag:, Needs: Author Feedback, Needs: Repro

**Comment by Nantris** [comment] 2024-06-16 00:31
@NickGerleman are you entirely certain this is a duplicate? It seems related, but not necessarily duplicated, and this issue remains an unresolved showstopper for us. I've burned at least a week on this bug without the slightest progress.

Please see here: https://github.com/facebook/react-native/issues/41938#issuecomment-2170989955
