### ISSUE TITLE
RCTSetLogFunction error when building to device

### ISSUE THREAD

**Issue by getsetbro** [facebook/react-native#3157] opened 2015-09-30 19:43 UTC
Running a react native app is working in the ios simulator but when I try to deploy it to a device the build fails with errors (see image)
<img width="409" alt="screen shot 2015-09-30 at 2 40 25 pm" src="https://cloud.githubusercontent.com/assets/442793/10204478/8f6f106c-6781-11e5-906d-9509762f40ec.png">

**Comment by ide** [comment] 2015-09-30 20:43
Dupe of https://github.com/facebook/react-native/issues/2685

**Closed by ide** 2015-09-30 20:43 UTC
