### ISSUE TITLE
error: method does not override or implement a method from a supertype     @Override

### ISSUE THREAD

**Issue by manuTro** [facebook/react-native#19272] opened 2018-05-15 17:07 UTC
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x]  I am using the react-native-cli: 2.0.1
react-native: 0.44.3

## Environment

This morning I got this error after running `react-native run-android` I got this error 
``` node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/FBSDKPackage.java:61: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/manuela/robonica/roboapp/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/Utility.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
:react-native-fbsdk:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-fbsdk:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 22.481 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html 
```

I'm getting this error with a lot of libraries, so the problem is not just this library, but something changes on React-native i think. 

Also I notice this

```Building and installing the app on the device (cd android && ./gradlew installDebug)...
Download https://jcenter.bintray.com/com/facebook/react/react-native/0.55.3/react-native-0.55.3.pom
Download https://jcenter.bintray.com/com/facebook/fresco/fresco/1.3.0/fresco-1.3.0.pom
Download https://jcenter.bintray.com/com/facebook/fresco/imagepipeline-okhttp3/1.3.0/imagepipeline-okhttp3-1.3.0.pom
Download https://jcenter.bintray.com/com/facebook/fresco/drawee/1.3.0/drawee-1.3.0.pom
Download https://jcenter.bintray.com/com/facebook/fresco/fbcore/1.3.0/fbcore-1.3.0.pom
Download https://jcenter.bintray.com/com/facebook/fresco/imagepipeline/1.3.0/imagepipeline-1.3.0.pom
Download https://jcenter.bintray.com/com/facebook/fresco/imagepipeline-base/1.3.0/imagepipeline-base-1.3.0.pom
Download https://jcenter.bintray.com/com/facebook/fresco/fbcore/1.3.0/fbcore-1.3.0.aar
Download https://jcenter.bintray.com/com/facebook/fresco/drawee/1.3.0/drawee-1.3.0.aar
Download https://jcenter.bintray.com/com/facebook/fresco/imagepipeline-base/1.3.0/imagepipeline-base-1.3.0.aar
Download https://jcenter.bintray.com/com/facebook/fresco/imagepipeline/1.3.0/imagepipeline-1.3.0.aar
Download https://jcenter.bintray.com/com/facebook/fresco/fresco/1.3.0/fresco-1.3.0.aar
Download https://jcenter.bintray.com/com/facebook/fresco/imagepipeline-okhttp3/1.3.0/imagepipeline-okhttp3-1.3.0.aar
Download https://jcenter.bintray.com/com/facebook/react/react-native/0.55.3/react-native-0.55.3.aar
Incremental java compilation is an incubating feature.
Could not find google-services.json while looking in [src/nullnull/debug, src/debug/nullnull, src/nullnull, src/debug, src/nullnullDebug]
Could not find google-services.json while looking in [src/nullnull/release, src/release/nullnull, src/nullnull, src/release, src/nullnullRelease]
```

Why is downloading react-native 0.55.3 pom files?

Thx

**Comment by guerjon** [comment] 2018-05-15 17:16
I got this same error, but with a different library BLE (https://github.com/innoveit/react-native-ble-manager) also with the 0.44 Version on Android.

**Comment by fearmear** [comment] 2018-05-15 19:53
@thebergamo You have to lock down RN version for every package, not just your app. I got 5 of them on current project. Ideally every package has to read RN version from gradle.properties.
Is there a better solution?

**Comment by fearmear** [comment] 2018-05-15 21:37
Hey, I figured out how to lock down transitive dependencies for such projects.
Add this to root **youappname.gradle** file. Don't forget to change the version.
```
subprojects {
    configurations.all {
        resolutionStrategy {
            force 'com.facebook.react:react-native:0.46.4'
        }
    }
}
```

**Comment by FernandoWahl** [comment] 2018-05-15 22:17
Work for me: 

compile ("com.facebook.react:react-native:0.44.+") { force = true }  // From node_modules

**Comment by zhaoxm** [comment] 2018-05-16 02:49
@fearmear did you mean **build.gradle**??

**Comment by ray-shawn** [comment] 2018-05-16 03:07
@fearmear Save me after adding to build.gradle

subprojects {
    configurations.all {
        resolutionStrategy {
            force 'com.facebook.react:react-native:0.44.0'
        }
    }
}

**Comment by jqn** [comment] 2018-05-16 03:57
These fixes don't seem to be working for me anymore:

```
subprojects {
    configurations.all {
        resolutionStrategy {
            force 'com.facebook.react:react-native:0.46.4'
        }
    }
}
```

or 

`  compile ("com.facebook.react:react-native:0.44.2") { force = true } `

**Comment by Mahaswami** [comment] 2018-05-16 06:10
In our case react-native-audio plugin brought 0.55.3 dependency and caused this havoc.

Here is how we locked down our RN version across all modules.
```
allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        configurations.all {
          resolutionStrategy {
            **force 'com.facebook.react:react-native:0.45.1'   //Your RN version should go here**
          }
        }
    }
}
```

**Comment by nkchouhan** [comment] 2018-05-16 06:49
Its https://github.com/facebook/react-native/issues/19272#issuecomment-389405958 working for me

**Comment by kelset** [comment] 2018-05-16 07:26
Closing as duplicate of https://github.com/facebook/react-native/issues/19259

**Closed by kelset** 2018-05-16 07:26 UTC
Labels: :grey_question:Needs More Information

**Comment by lucinick** [comment] 2018-05-16 07:45
@Mahaswami  Thank for your guide... My version is 0.44.0 and it work for me.

**Comment by manuTro** [comment] 2018-05-16 08:45
https://github.com/facebook/react-native/issues/19272#issuecomment-389405958 worked for me as well! thanks!

**Comment by Mahaswami** [comment] 2018-05-17 06:50
@jupassamani, saw your -1. Can you share what specifically did not work for you so I can update my comments for others benefit? Thanks.

**Comment by Hemanth1985** [comment] 2018-05-17 08:55
I am on RN 0.44.0, I added it configurations.all {
          resolutionStrategy {
            // START: RN version lockdown 
            force 'com.facebook.react:react-native:0.44.0’   //Your RN version should go here
            // END: RN version lockdown 
          }
        }
and specified the actual version in 
 react-native-code-push: 
dependencies {     compile "com.facebook.react:react-native:0.44.0”     
compile 'com.nimbusds:nimbus-jose-jwt:5.1' }

i am getting error couldn’t find com.facebook.react:react-native:0.44.0 
Can anyone help me?

**Comment by jupassamani** [comment] 2018-05-17 11:42
Hey @Mahaswami I tried 
```
 allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            url "$rootDir/../node_modules/react-native/android"
        }
        configurations.all {
          resolutionStrategy {
            force 'com.facebook.react:react-native:0.44' 
          }
        }
    }
} 
```
 however it didn't work for me - same error.  I also tried to edit android/app/build.gradle 

`compile ("com.facebook.react:react-native:0.44") { force = true } // From node_modules `

no luck so far...

**Comment by lucinick** [comment] 2018-06-15 08:36
@youki666 You just only comment or remove @override.
