### ISSUE TITLE
[CameraRoll] Image Orientation Bug

### ISSUE THREAD

**Issue by myusuf3** [facebook/react-native#1845] opened 2015-07-02 02:40 UTC
This is blocking bug for us. I have seen a couple of issues and followed the suggest tips but I am still unable to get this image to render with proper orientation. This issue #1567 make reference to the bug and memory issues large camera rolls. 

Here is an example of what I am talking about as you can see top image is rotated incorrectly. Doesn't happen with all images though oddly enough.

![image](https://cloud.githubusercontent.com/assets/156825/8468995/cf18267c-2041-11e5-9f31-dddaf1c5f7ce.png)

**Comment by myusuf3** [comment] 2015-07-02 16:06
@a2 ping

**Comment by myusuf3** [comment] 2015-07-02 17:34
@brentvatne ping

**Comment by brentvatne** [comment] 2015-07-02 20:32
@myusuf3 - I'm not familiar with this part of the codebase, it sucks that it's a blocking issue for you :( perhaps @nicklockwood has some insight

**Comment by myusuf3** [comment] 2015-07-02 20:53
That would be awesome @nicklockwood if you could provide some insight!

**Comment by nicklockwood** [comment] 2015-07-02 20:55
I don't have time to investigate this fully right now, however I have a theory about what the issue is. 

UIImage has a concept of orientation which may be being ignored when the image is drawn.

The orientation metadata means that images in the camera roll aren't necessarily stored "right-way-up" on disk, but are instead rotated to the correct angle when drawn by iOS. If we're not taking the orientation into account, it would explain why some images are rotated and others aren't.

**Comment by VonD** [comment] 2015-07-02 21:03
@myusuf3 does the orientation appear differently on your thumbnails than it does on the Apple Photos app ?

**Comment by ide** [comment] 2015-07-02 21:04
Some reading on orientation for those interested: http://www.daveperrett.com/articles/2012/07/28/exif-orientation-handling-is-a-ghetto/

**Comment by VonD** [comment] 2015-07-02 21:28
@ide thanks for the article. nice read!

**Comment by myusuf3** [comment] 2015-07-02 21:32
@VonD yes it does appear differently in both places. correct in the photos app and broken in our react application.

**Comment by VonD** [comment] 2015-07-02 22:04
@myusuf3  OK, here's a little experiment : a photo of my keyboard taken in the 4 orientations. Below are two screenshots : on the top the Photos app, on the bottom my RN app. The orientations seem consistent. I'm using RN 0.6.0 + the patch provided here : #1567 , and the screenshots are from a device with ios 8.3. How does this test work for you ?

![orientation](https://cloud.githubusercontent.com/assets/752330/8488877/a5b5d538-2116-11e5-8fa2-798d4e147b30.png)

**Comment by myusuf3** [comment] 2015-07-02 22:25
Is this the patch exactly?

``` objc
  if ([imageTag hasPrefix:@"assets-library"]) {
    [[RCTImageLoader assetsLibrary] assetForURL:[NSURL URLWithString:imageTag] resultBlock:^(ALAsset *asset) {
      if (asset) {
        // ALAssetLibrary API is async and will be multi-threaded. Loading a few full
        // resolution images at once will spike the memory up to store the image data,
        // and might trigger memory warnings and/or OOM crashes.
        // To improve this, process the loaded asset in a serial queue.
        dispatch_async(RCTImageLoaderQueue(), ^{
          // Also make sure the image is released immediately after it's used so it
          // doesn't spike the memory up during the process.
          @autoreleasepool {
            ALAssetRepresentation *representation = [asset defaultRepresentation];
            ALAssetOrientation orientation = [representation orientation];
            UIImage *image = [UIImage imageWithCGImage:[asset thumbnail] scale:1.0f orientation:UIImageOrientationUp];
            RCTDispatchCallbackOnMainQueue(callback, nil, image);
          }
        });
```

This to me doesn't make sense since you are forcing all the images in the up orientation which should result in everything that wasn't take in up orientation to be broken.

**Comment by myusuf3** [comment] 2015-07-02 22:27
@VonD  ^^^

**Comment by a2** [comment] 2015-07-02 22:41
@myusuf3 I mean I can't say for certain that will work. It was just a thought. My thought was that the `-thumbnail` method is documented as performing the rotation for you and having an `Up` image orientation.

**Comment by myusuf3** [comment] 2015-07-02 22:52
So if I apply thumbnail `[asset thumbnail]` it will put everything in the up position once its done? @a2 Anyways I got that piece working and things in the application aren't flipped anymore. I was using a custom Image component in the camera roll screen. I will fix my PR #1842 to reflect it.

**Comment by unknownexception** [comment] 2015-08-03 09:36
@myusuf3 What's the status for orientation issue? Do you have a fork which works for you?

**Comment by nicklockwood** [comment] 2015-08-03 09:48
This should be fixed now. If not, please re-open.

**Comment by unknownexception** [comment] 2015-08-03 10:34
@nicklockwood Orientation doesn't work for me on current master. When rnplay.org will update to 0.9.0 I'll post example there, maybe there is some misunderstanging.

**Comment by myusuf3** [comment] 2015-08-03 17:15
@unknownexception I am still patching the file for it to work. I hoping to see if this  #2008 was merged into 0.8.0 so we could ditch this patch we currently have in our code which works well.  @nicklockwood can you confirm that PR was merged in?

**Comment by aroth** [comment] 2015-08-03 17:39
@myusuf3 Changes from #2008 were committed to master on 7/21 (https://github.com/facebook/react-native/commit/9c73e2ff7aeac8c65f25472135e4c0410f797eea). @nicklockwood committed additional enhancements shortly thereafter (https://github.com/facebook/react-native/commit/85cb35c51439a17c0961cc80518d2e979d7279c0). 

Merged into 0.9.0-rc.

**Comment by aroth** [comment] 2015-08-03 18:22
@myusuf3 @nicklockwood I've created PR #2214 to resolve this.  The original fix was overwritten by other recent camera roll enhancements.

**Comment by nicklockwood** [comment] 2015-08-04 11:55
@aroth @myusuf3 can you provide some sample photos that show at the wrong orientation in the camera roll example? I've tried taking photos in all orientations with the camera, but they always show the right way up even without @aroth's fix, and I don't want to merge it unless I can verify that it works.

**Comment by aroth** [comment] 2015-08-04 15:51
Without fix:
![screen shot 2015-08-04 at 11 50 12 am](https://cloud.githubusercontent.com/assets/542/9065370/0e453124-3a9f-11e5-828b-dc464cee3ebb.png)

With fix:
![screen shot 2015-08-04 at 11 50 21 am](https://cloud.githubusercontent.com/assets/542/9065371/0e46d560-3a9f-11e5-992d-e2602c37cf7b.png)

**Comment by unknownexception** [comment] 2015-08-05 06:42
@aroth can confirm, that fixed some cases. Thank you for your fix.

**Comment by thomashermant** [comment] 2015-08-27 09:03
I've got the same problem here. 
My images get from CameraRoll has a bad orientation.
![image_with_orientations](https://cloud.githubusercontent.com/assets/86210/9516731/e6101598-4caa-11e5-8e01-34a299827d95.jpg)

When I read message above seems to be fixed...
Do you have an idea when it will be in a released version?

Best regards,
Tom

ps: You are making an awesome job guys! Thank you!

**Comment by aroth** [comment] 2015-08-27 16:26
@thomashermant The fix for this has been included in 0.11-rc.  

https://github.com/facebook/react-native/releases

**Comment by myusuf3** [comment] 2015-08-27 17:38
its not in 0.10.0? ugh.

**Comment by browniefed** [comment] 2015-09-13 16:16
@brentvatne this is fixed already in .11. Close.

**Closed** 2015-09-13 19:11 UTC

**Comment by pawellewandowski** [comment] 2017-04-22 18:53
Reopen... I have the same problem in RN 0.43.
![screenshot_20170422-204923](https://cloud.githubusercontent.com/assets/3199040/25307234/9b814680-279d-11e7-8bca-2eeca6da9132.png)

**Comment by seancunningham** [comment] 2017-05-24 16:34
Same problem, did you manage to resolve yours after the month or so?

**Comment by pawellewandowski** [comment] 2017-05-24 17:43
I return to RN 0.42 ...

**Comment by Iyoss** [comment] 2017-10-16 14:37
@pawellewandowski Have you resolved this issue? I have this with RN 0.48.3 and 16.0.0-alpha.12

**Comment by jose920405** [comment] 2018-01-19 16:43
Still hapenning in `0.51.0`

**Comment by ewein** [comment] 2018-02-07 23:07
I'm getting this issue on iOS using React Native v0.52.0

**Comment by phillmill** [comment] 2018-05-29 00:30
Getting this issue on Android, React Native 0.55

**Comment by phillmill** [comment] 2018-06-22 21:25
Hey @jose920405 I see you used react-native-exif to fix your issue (in the stackoverflow article). I gave it a try, but the thing is, is it's telling me to rotate images 90 degrees correctly, but in other instances it's also telling me to rotate images that are _already_ correct.

Below is a screenshot of two images, both of which are actually portrait images (and display as portrait in default gallery app). But as you can see, the Exif value says rotate 90 for both :S.

![orientation](https://user-images.githubusercontent.com/10585687/41799876-7a7ad130-7649-11e8-9e59-4b3493a930cc.jpg)
