### ISSUE TITLE
Metro Server not starting: error attachToServer is not a function

### ISSUE THREAD

**Issue by ymc-thzi** [facebook/react-native#33144] opened 2022-02-18 15:13 UTC
### Description

I've updated my project as usual with a fresh `npm install` today like I did 1000 times before. When I try to run `npm start` metro starts but now it is always crashing: `error attachToServer is not a function`
I have updated node, brew, ...everything. Nothing helps.

![Bildschirmfoto 2022-02-18 um 16 02 21](https://user-images.githubusercontent.com/1804472/154709445-cbe21732-ff13-4e10-902d-6f7cc764ae74.png)

### Version

0.66.4

### Output of `npx react-native info`

System:
    OS: macOS 12.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 106.25 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.5.0 - ~/.nvm/versions/node/v17.5.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.4.1 - ~/.nvm/versions/node/v17.5.0/bin/npm
    Watchman: 2022.02.14.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29, 30, 31
      Build Tools: 27.0.3, 28.0.2, 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-19 | Google APIs Intel x86 Atom, android-21 | Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-R | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8092744
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.1 => 17.0.2
    react-native: ^0.66.3 => 0.66.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

`$ npm start`
or
`$ yarn start`

**Comment by ymc-thzi** [comment] 2022-02-18 15:34
Have seen this here some minutes ago on react-native-community/cli-plugin-metro
"Published a breaking change to 6.x by mistake. Working on a fix right now."
https://github.com/react-native-community/cli/issues/1561

**Comment by motiz88** [comment] 2022-02-18 15:36
Yes, this is a duplicate of https://github.com/react-native-community/cli/issues/1561 which is now closed.

> The fix should be ready on npm: https://www.npmjs.com/package/@react-native-community/cli-server-api
Please [update the `@react-native-community/cli`](https://github.com/react-native-community/cli#updating-the-cli) to the 6.x version by invalidating the lock file.

_Originally posted by @thymikee in https://github.com/react-native-community/cli/issues/1561#issuecomment-1044668487_

**Closed by motiz88** 2022-02-18 15:36 UTC
Labels: Needs: Triage :mag:
