### ISSUE TITLE
[FlatList][0.45.1] onEndReached gets called before dataSource being filled

### ISSUE THREAD

**Issue by PauloMelo** [facebook/react-native#14456] opened 2017-06-11 13:15 UTC
<FlatList
data={dataSource}
keyExtractor={(_, i) => i}
numColumns={2}
renderItem={({ item }) => this._renderListItem(item)}
onRefresh={() => this.handleRefresh()}
refreshing={refreshing}
onEndReached={() => this.handleLoadMore()}
onEndReachedThreshold={0.3}
/>

onEndReached is called one or two times before the first load ends and data array is filled.
It should only get called when the data is loaded and the onEndReachedThreshold is true. 
Since no data is yet displayed, the onEndReached should not be called.

**Comment by RooneyJung** [comment] 2017-06-12 01:40
At initial time, dataSource maybe empty array.
So, It can call onEndReached. (empty = on end reached)
Furthermore, FlatList only knows dataSource's reference not the state.
It means FlatList can't know data is loading, is loaded or is initializing. 
So, 'It should only get called when the data is loaded' is not right.
(If FlatList can accept a dataSource as null, it may be right.)

And You have to check that FlatList did call onEndReached twice or the component rendered FlatList twice.
Because there are several reasons that components re-rendered.
ex, Some modules (like redux) may change the component's state twice or more at initial time.

**Comment by PauloMelo** [comment] 2017-06-12 08:14
I am sorry but I do not agree with your reasoning.

At initial time, dataSource may be empty or not. It may even be null.
The API states that onEndReached is called once when the scroll position gets within onEndReachedThreshold of the rendered content.
So if dataSource is null or an Array with 0 size it cannot be called because ScrollIndex is 0 and onEndReached is not at x% of TotalListHeight. Thus this should only be called at least when some data is displayed and ScrollIndex is at the onEndReachedThreshold.

Furthermore, it is the responsibility of the component to call the events properly when they occur. It is not the implementation of the called function, that should test if it is time to be called or not.

Just to finish. This worked perfectly on 0.44 and it does not on 0.45 or 0.45.1 

With the above reasoning I believe this is a bug.

**Comment by RooneyJung** [comment] 2017-06-12 09:58
I am sorry. I was rash. I just focused 'loaded' meaning. It's my fault.
So, I tested some codes with FlatList, and I have a question.
Is the refreshing property false before loaded?
If refreshing is true, it triggers onEndReached in my tests.
(tested with RN 0.44, currently I can't test with RN 0.45. It has some issues can't run-ios)

**Comment by PauloMelo** [comment] 2017-06-12 14:53
Sorry if I sounded harsh. 
The refresh property is false before loading the data.

**Comment by hramos** [comment] 2017-06-12 20:55
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-12 20:55 UTC

**Comment by grin** [comment] 2017-06-23 14:25
You may be running into the issue described: https://github.com/facebook/react-native/issues/14015 (where I also described my solution)
