### ISSUE TITLE
zIndex lose effectiveness after upgrade RN from 0.48.0 to 0.53.0 on android

### ISSUE THREAD

**Issue by sejo2016** [facebook/react-native#17907] opened 2018-02-08 09:54 UTC
Packages: (previous => current)
    react-native: 0.48.0 => 0.53.0
    react: 16.0.2-alpha.12 => 16.2.0

  Target Platform: android 8

#### Steps to Reproduce

After update the RN version from 0.48.0 to 0.53.0,zIndex lose effectiveness on android.what should I do to fix this difference?

```
<Animated.View key={index} style={[style.card, cardStyle, {
                    zIndex,
                    top,
                    transform: [{scale}]
                }, currentIndex === index && animatedStyle]}>
...
</Animated.View>
```

#### Expected Behavior
![image](https://user-images.githubusercontent.com/19886235/35965825-095372e8-0cf7-11e8-8c31-8b69326dc803.png)

#### Actual Behavior
![image](https://user-images.githubusercontent.com/19886235/35965839-0e4416fe-0cf7-11e8-8411-779860d266f6.png)

**Comment by hramos** [comment] 2018-02-09 20:41
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue that meets the requirements set forth in the template. Thanks!

**Closed by hramos** 2018-02-09 20:41 UTC
Labels: Failed Commands
