### ISSUE TITLE
Animated.Value on PanResponder and Animated.timing causes interpolation to not render with useNativeDriver = true

### ISSUE THREAD

**Issue by rory-pickering** [facebook/react-native#17909] opened 2018-02-08 12:10 UTC
Im trying to create a list of items, with swipe to delete functionality.

I have an Animated.Value attached to a PanRepsonder.onPanResponderMove Animated.Event. onPanResponderRelease i Animated the value back to 0

If i add in useNativeDriver to the Animated.timing function (seen below) then not all interpolate values update. without native driver or if i just user `setValue(0)` it all works ok.

check out these gifs for easier understanding

with native driver 
![with native driver](https://i.imgur.com/VpSZ8DN.gif)

without native driver on the Timing.
![without native driver](https://i.imgur.com/SLXBIpM.gif)

```
this._panResponder = PanResponder.create({
  ...
  onPanResponderMove: Animated.event([
    null, { dx: this.state.panNew }
  ]),
  onPanResponderRelease: (e, {vx, vy}) => {
    if( this.state.panNew._value < width * -0.6 ) {
      this.remove();
      return;
    }
    Animated.timing(this.state.panNew, {
      toValue:0, 
      duration: 150,
      useNativeDriver:true //breakInterpolateValuesRandomly: true
    }).start();
  }
});
```

and then in my render function something like this (i've striped it down a little, i have 6 interpolate values in total)

```
render() { 
  ...
  const contentPosition = this.state.panNew.interpolate({
    inputRange: [width*-1, 0],
    outputRange: [width*-1, 0],
    extrapolate: 'clamp'
  });
  const swipeBgPosition = this.state.panNew.interpolate({
    inputRange: [width*-1, 0],
    outputRange: [0, width*0.5],
    extrapolate: 'clamp'
  });
  const pullToRemoveOpacity = this.state.panNew.interpolate({
    inputRange: [width*-0.3, width*-0.27],
    outputRange: [0, 1],
    extrapolate: 'clamp'
  });

  return (
    <View style={{backgroundColor:'red'}}>
      <Animated.View style={[styles.swipeBackground, { transform: [{translateX:swipeBgPosition}], backgroundColor: 'rgb(237, 94, 104)' }]}>
        <Animated.Text style={[styles.pullText, {
          opacity: pullToRemoveOpacity,
          transform: [{scale:0.5}]
        }]}>Pull To{"\n"}Remove</Animated.Text>
      </Animated.View>
      <Animated.View style={[styles.content, { transform: [{translateX:contentPosition}]}]}  {...this._panResponder.panHandlers}>
          {this.renderImage()}
          <Text style={styles.title}>
            {this.props.title}
          </Text>
        </Animated.View>
    </View>
  );
}
```

These above functions are from my ListItem Component rendered inside a `FlatList`

### Environment
  OS: macOS High Sierra 10.13.3
  Node: 9.3.0
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.53.0 => 0.53.0

**Comment by hramos** [comment] 2018-02-09 20:42
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue that meets the requirements set forth in the template. Thanks!

**Closed by hramos** 2018-02-09 20:42 UTC
Labels: Failed Commands
