### ISSUE TITLE
react native ListView with scrollable content in both vertical AND horizontal doesn't seem to work anymore with react-native 0.28 (react 15.1.0)

### ISSUE THREAD

**Issue by BricePissard** [facebook/react-native#8369] opened 2016-06-23 16:59 UTC
[react native ListView with scrollable content in both vertical AND horizontal doesn't seem to work anymore with react-native 0.28 (react 15.1.0)](http://stackoverflow.com/questions/37997344/react-native-listview-with-scrollable-content-in-both-vertical-and-horizontal-do)

Since the react-native last release 0.27 > 0.28 (and React 15.0.2 > 15.1.0) a ListView that contain a scrollable content in both vertical and horizontal can now only be scrolled in only one direction:

- if the listView is defined with a flexDirection = "row", the listView can be scrolled horizontally but rebound back to a fix height position preventing to see what the listView contain down vertically.
- if the listView is defined with a flexDirection = "column", the listView can be scrolled vertically but rebound back to a fix width position preventing to see what the listView contain horizontally further left.
sample:

```
export default React.createClass({
 ...

 render():View {
  return(
    <ListView
      decelerationRate                  = "fast"
      snapToAlignment                   = "start"
      dataSource                        = {this.state.dataSource}
      style                             = {styles.listView}
      renderRow                         = {this._getColumn}
      initialListSize                   = {100}
      scrollEnabled                     = {true}
      horizontal                        = {true}
      pagingEnabled                     = {false}
      showsHorizontalScrollIndicator    = {false}
      showsVerticalScrollIndicator      = {false}
      removeClippedSubviews             = {true}
      automaticallyAdjustContentInsets  = {true}
      alwaysBounceVertical              = {true}
      alwaysBounceHorizontal            = {true}
      bouncesZoom                       = {false}
      canCancelContentTouches           = {true}
      centerContent                     = {false}
      directionalLockEnabled            = {true}
     />
   );
 },

 ...

 _getColumn(el:Array<Object>, sectionID:string, rowID:string):View {
   return(
     <View
        key    = {"row-`$(sectionID)`:`$(rowID)`"}
        style  = {styles.column}
      >
        ...
      </View>
   );
 },

 ...

});

const styles:StyleSheet = StyleSheet.create({
   listView: {
     position          : "relative",
     flexDirection     : "row", // <---------- 'row' || 'column'
     flexWrap          : "wrap",
     alignSelf         : "stretch",
     top               : 0,
     width             : 380,
     height            : 600,
     backgroundColor   : "transparent",
     overflow          : "hidden",
   },
   column: {
     flex              : 1,
     flexDirection     : "row",
     alignSelf         : "stretch",
     alignItems        : "flex-start",
     justifyContent    : "flex-start",
     backgroundColor   : "red",
     position          : "relative",
     width             : 380/3,
     height            : 1250,
   },


});
```

Before, with React 15.0.2 and react-native 0.26 it worked as expected: it was possible to navigate horizontally and vertically in the columns that appeared within the listView.

Is there anything wrong in my way of setting the StyleSheet? I've tested a lot of combination so some extra (maybe not necessary) StyleSheet arguments are still in used in styles.listView and styles.column...

**Comment by faisalil** [comment] 2016-06-23 18:00
+1. My example is a bit simpler. I have a scrollview around an image and I am trying to make it scroll in all directions. Before moving to react-native 0.28, it was working fine. Now, its not working. 
`        return (
            <ScrollView
                ref={(scrollView) => { this._scrollView = scrollView; } }
                directionalLockEnabled={false}
                horizontal={true}
                style={{
                    backgroundColor: '#FFF',
                    flex: 1
                }}>
                <View style={{
                    marginVertical: 50
                }}>
                    <Image source={require('../image.png') }>
                    </Image>
                </View>
            </ScrollView>
`

**Comment by faisalil** [comment] 2016-06-23 18:23
@emilsjolander and @devknoll , I can see that you guys had changes on the scrollView in the 0.28 release. Can any of you take a look?

**Comment by faisalil** [comment] 2016-06-23 18:38
I reverted back to 0.27 and the problem is not happening anymore.

**Comment by yspychala** [comment] 2016-06-24 13:16
Same problem for me, it worked fine with 0.27.

I have several `<ListView />` (vertical scroll) contained in a horizontal ScrollView. Like this :

```javascript
<ScrollView
  horizontal
  pagingEnabled
>
  <ListView />
  <ListView />
  <ListView />
</ScrollView>
```

The horizontal scroll is controlled by tabs. When I select a tab, the `<ScrollView />` goes to the next page, but I can't switch pages manually.

**Comment by baotang** [comment] 2016-06-26 10:28
I'm new to react-native ,meet the same problem,my `ScrollView` can't work!
```jsx
<ScrollView
        contentContainerStyle={{paddingVertical: 20}}
      style={[styles.twitterPostContainer]}
      automaticallyAdjustContentInsets={false}
      refreshControl={
          <RefreshControl
            refreshing={this.state.isRefreshing}
            onRefresh={()=>this._onRefresh()}
            title="refreshing"
            tintColor="#53cac3"/>}>
            <View style={{position:'absolute',top:0,width:Util.size.width}}>
              <Image
                resizeMode="stretch"
                source={{uri:'day3'}}
                style={{width:Util.size.width, height:Util.size.height}}></Image>
            </View>
      </ScrollView>
```
I'm very depressed!
Should I resolve it by revert it to 0.27

**Comment by LiuCao** [comment] 2016-06-27 11:29
@baotang  
delete the below two properties
`contentContainerStyle={{paddingVertical: 20}}`
`style={[styles.twitterPostContainer]}`

it's work to me !!!

**Comment by LiuCao** [comment] 2016-06-27 11:30
@baotang  @BricePissard 
delete the below two properties
`contentContainerStyle={{paddingVertical: 20}}`
`style={[styles.twitterPostContainer]}`

it's work to me !!!

**Comment by LiuCao** [comment] 2016-06-27 11:30
@baotang  @BricePissard 
delete the below two properties
`contentContainerStyle={ ... }`
`style={ ... }`

it's work to me !!!

**Comment by BricePissard** [comment] 2016-06-28 09:15
@emilsjolander, @devknoll

It seems to me that there is bug in RN v0.28.0.

It doesn't seem to be possible to have a <ListView> that moves its content in both directions (whether directionalLockEnabled is enabled or not). 
The ListView component are now stuck to move or horizontally or vertically what they are supposed to scroll, but can't do both.

Using <ListView> instead of <ScrollView> allows the use of "initialListSize" and <ListView> have a better performance for large data to scroll. It should be possible to use <ListView> for that purpose.

Is there anyone who passed through this issue? (appart reverting back to 0.27.x which work very well indeed). 

Waiting for a bug fix for the next release is not a mater but knowing that this problem is really a bug can change some dev roadmap.

**Comment by BricePissard** [comment] 2016-06-29 10:56
OK @baotang thanks,

I've just tried to set the contentContainerStyle and it finally it worked.
So for those of you who faced the same problem here is my corrected sample:

```
export default React.createClass({
 ...

 render():ListView {
  return(
    <ListView
      decelerationRate                  = "fast"
      snapToAlignment                   = "start"
      dataSource                        = {this.state.dataSource}
      style                             = {styles.listView}
      contentContainerStyle       = {styles.listViewContentContainer}  // <-------- set the content style
      renderRow                         = {this._getColumn}
      initialListSize                   = {100}
      scrollEnabled                     = {true}
      horizontal                        = {true}
      pagingEnabled                     = {false}
      showsHorizontalScrollIndicator    = {false}
      showsVerticalScrollIndicator      = {false}
      removeClippedSubviews             = {true}
      automaticallyAdjustContentInsets  = {true}
      alwaysBounceVertical              = {true}
      alwaysBounceHorizontal            = {true}
      bouncesZoom                       = {false}
      canCancelContentTouches           = {true}
      centerContent                     = {false}
      directionalLockEnabled            = {true}
     />
   );
 },

 ...

 _getColumn(el:Array<Object>, sectionID:string, rowID:string):View {
   return(
     <View
        key    = {"row-`$(sectionID)`:`$(rowID)`"}
        style  = {styles.column}
      >
        ...
      </View>
   );
 },

 ...

});

const styles:StyleSheet = StyleSheet.create({
   listView: {
     position          : "relative",
     flexDirection     : "row",
     flexWrap          : "wrap",
     alignSelf         : "stretch",
     top               : 0,
     width             : 380,
     height            : 600,
     backgroundColor   : "transparent",
     overflow          : "hidden",
   },
   listViewContentContainer: {
     width               : 6000,  // <-------------- set the max width of the scrolled content
     height              : 1250,  // <-------------- set the max height of the scrolled content
   },
   column: {
     flex              : 1,
     flexDirection     : "row",
     alignSelf         : "stretch",
     alignItems        : "flex-start",
     justifyContent    : "flex-start",
     backgroundColor   : "red",
     position          : "relative",
     width             : 380/3,
     height            : 1250,
   },


});
```

**Closed** 2016-06-29 11:01 UTC

**Comment by markortiz** [comment] 2016-07-15 11:44
I do have the same problem on my `ListView` when I add `contentContainerStyle` to create a `Gridview`
@BricePissard your solution that will put max `height` works really great.
```
   listViewContent: {
     width             : 6000,  // <--- set the max width of the scrolled content
     height            : 1250,  // <--- set the max height of the scrolled content
   },
```

But how I can put max height if I have a dynamic numbers of items , as well as different  height per Item?

**Comment by mschipperheyn** [comment] 2016-07-15 22:58
I have tons of indeterminate problems with flex after upgrading to 0.28+.
