### ISSUE TITLE
[FlatList] stack: Error: Failed to execute "importScript" on "workerGlobalScope" React-Native FlatList 

### ISSUE THREAD

**Issue by AvijitDutta95** [facebook/react-native#13558] opened 2017-04-18 12:50 UTC
When I'm trying to use FlatList on my application its given this error (error details in screenshot) 
![capture](https://cloud.githubusercontent.com/assets/26165120/25131450/68f60184-2463-11e7-957b-fbf5ff03d963.JPG) 

 My code:

```
`import React from 'react';
import { Text, View, Button, FlatList } from 'react-native';
import { graphql } from 'react-apollo';
import gql from 'graphql-tag';

class HomeScreen extends React.Component {
  static navigationOptions = {
    title: 'Home',
  };

  static propTypes = {
      data: React.PropTypes.shape({
        loading: React.PropTypes.bool,
        error: React.PropTypes.object,
        viewer: React.PropTypes.object,
      }).isRequired,
    }

  render() {
    const { navigate } = this.props.navigation;

    if (this.props.data.error) {
      console.log(this.props.data.error)
      return (<Text style={{marginTop: 50}}>An unexpected error occurred</Text>)
    }

    if (this.props.data.loading || !this.props.data.viewer.allFormData.edges) {
      return (<Text style={{marginTop: 50}}>Loading</Text>)
    } else {
      return (
        <View style={{ marginTop: 50 }}>
          <FlatList
            data={this.props.data.viewer.allFormData.edges[0].node}
            renderItem={({data}) =>
              <Text>Source: {data.source}</Text>
              <Text>formDataId: {data.formDataId}</Text>
            }
           />
          <Button
            onPress={() => navigate('chat')}
            title="Chat with Lucy"
          />
        </View>
      );
    }
  }
}


const TestQuery = gql `query {
  viewer {
    allFormData(companyId: "WitByBit", formSchemaId: 1) {
      edges {
        node {
          companyId,
          tokenId,
          source,
          formDataId,
          formData{
            sectionId,
            fieldPath,
            index,
            value,
            type
          }
        }
      }
    }
  }
}`

const HomeWithData = graphql(TestQuery)(HomeScreen);

export default HomeWithData;
`
```

**Comment by hramos** [comment] 2017-04-25 13:35
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-04-25 13:35 UTC

**Comment by anvesh523** [comment] 2017-09-07 04:02
I'm getting the same error message when I'm working on async & AsyncStorage. Please help me with the above error.

**Comment by bnovf** [comment] 2017-10-29 05:26
For me this error happens only when I import FlatList

https://github.com/bnovf/react-native-github-graphql-app/issues/3
