### ISSUE TITLE
React/RCTview.h not found in react-native-facebook-login

### ISSUE THREAD

**Issue by chiragkukreja** [facebook/react-native#16047] opened 2017-09-21 11:21 UTC
### Is this a bug report?
YES

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1. npm install react-native-facebook-login --save
2. react-native link react-mative-facebook-login
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by hramos** [comment] 2017-09-21 15:20
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue that meets the requirements set forth in the template. Thanks!

**Closed by hramos** 2017-09-21 15:20 UTC
