### ISSUE TITLE
[Android] VerifyError on pre API21 devices

### ISSUE THREAD

**Issue by ps-swaroop** [facebook/react-native#10249] opened 2016-10-05 12:13 UTC
### Issue Description

VerifyError on pre API21 devices
### Steps to Reproduce / Code Snippets

Fatal Exception: java.lang.VerifyError: com/facebook/soloader/c$1
       at com.facebook.soloader.ExtractFromZipSoSource$ZipUnpacker.ensureDsos(SourceFile:76)
       at com.facebook.soloader.ExtractFromZipSoSource$ZipUnpacker.getDsoManifest(SourceFile:123)
       at com.facebook.soloader.UnpackingSoSource.refreshLocked(SourceFile:278)
       at com.facebook.soloader.UnpackingSoSource.prepare(SourceFile:374)
       at com.facebook.soloader.SoLoader.initImpl(SourceFile:196)
       at com.facebook.soloader.SoLoader.init(SourceFile:105)
       at com.facebook.soloader.SoLoader.init(SourceFile:116)
       at com.facebook.react.ReactInstanceManagerImpl.initializeSoLoaderIfNecessary(SourceFile:356)
       at com.facebook.react.ReactInstanceManagerImpl.(SourceFile)
       at com.facebook.react.ReactInstanceManager$Builder.build(SourceFile:371)
       at com.flipkart.seller.core.react.ReactNativeBaseActivity.initializeReactNative(SourceFile:113)
       at com.flipkart.seller.payments.ui.activities.PaymentBreakupDetailActivity.onCreate(SourceFile:119)
       at android.app.Activity.performCreate(Activity.java:5411)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2396)
       at android.app.ActivityThread.access$800(ActivityThread.java:139)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:149)
       at android.app.ActivityThread.main(ActivityThread.java:5257)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
       at dalvik.system.NativeStart.main(NativeStart.java)

EDIT: Working fine with v0.30
#### Expected Results

No Crash
### Additional Information
- React Native version:0.34.1
- Platform(s) (iOS, Android, or both?):Android

**Comment by lacker** [comment] 2016-11-30 19:57
I think this issue is missing enough info to reproduce it so I am going to close the issue. If someone can repro this with sample code like a rnplay.org link then please feel free to open a new issue.

**Closed by lacker** 2016-11-30 19:57 UTC
Labels: Android

**Comment by npomfret** [comment] 2017-02-21 10:10
I've got the same issue, but only when running direct from android studio on 4.1 devices with RN 0.39

**Comment by npomfret** [comment] 2017-03-22 16:36
I can also reproduce it in production devices now.  Running 4.4 or 4.1

**Comment by drakmail** [comment] 2017-07-16 19:59
Have same issue in development and release modes (android 4.4.2)

```
W/dalvikvm( 3521): VFY:  rejected Lcom/facebook/soloader/SoLoader;.loadLibraryBySoName (Ljava/lang/String;I)V
W/dalvikvm( 3521): Verifier rejected class Lcom/facebook/soloader/SoLoader;
D/AndroidRuntime( 3521): Shutting down VM
W/dalvikvm( 3521): threadid=1: thread exiting with uncaught exception (group=0xaf7c0b20)
E/AndroidRuntime( 3521): FATAL EXCEPTION: main
E/AndroidRuntime( 3521): Process: com.youme, PID: 3521
E/AndroidRuntime( 3521): java.lang.VerifyError: com/facebook/soloader/SoLoader
E/AndroidRuntime( 3521): 	at com.youme.MainApplication.onCreate(MainApplication.java:66)
E/AndroidRuntime( 3521): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
E/AndroidRuntime( 3521): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4344)
E/AndroidRuntime( 3521): 	at android.app.ActivityThread.access$1500(ActivityThread.java:135)
E/AndroidRuntime( 3521): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
E/AndroidRuntime( 3521): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 3521): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 3521): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
E/AndroidRuntime( 3521): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 3521): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 3521): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
E/AndroidRuntime( 3521): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
E/AndroidRuntime( 3521): 	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by butchmarshall** [comment] 2017-09-11 03:01
One of my users just submitted a very similar bug report

`java.lang.VerifyError: com/facebook/soloader/SoLoader
	at com.snow_trails.MainApplication.onCreate(MainApplication.java:79)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4615)
	at android.app.ActivityThread.access$1600(ActivityThread.java:169)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1340)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5487)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)`

**Comment by Gumija** [comment] 2017-10-04 12:29
Hey guys, I have the same problem. Looking into info about this, the problem is on Java side, a `synchronized` statement inside a `try/catch` block is the cause (https://stackoverflow.com/a/28368177/6098387). Any ideas what can be done about this?

**Comment by Gumija** [comment] 2017-10-04 13:55
My logcat output btw:
```
D/dalvikvm( 4800): GC_CONCURRENT freed 358K, 13% free 3314K/3796K, paused 0ms+2ms, total 5ms
I/dalvikvm( 4800): Could not find method android.system.Os.posix_fallocate, referenced from method com.facebook.soloader.UnpackingSoSource.regenerate
W/dalvikvm( 4800): VFY: unable to resolve static method 6182: Landroid/system/Os;.posix_fallocate (Ljava/io/FileDescriptor;JJ)V
D/dalvikvm( 4800): VFY: replacing opcode 0x71 at 0x0154
W/dalvikvm( 4800): VFY: unable to resolve exception class 922 (Landroid/system/ErrnoException;)
W/dalvikvm( 4800): VFY: unable to find exception handler at addr 0x1f6
W/dalvikvm( 4800): VFY:  rejected Lcom/facebook/soloader/UnpackingSoSource;.regenerate (BLcom/facebook/soloader/UnpackingSoSource$DsoManifest;Lcom/facebook/soloader/UnpackingSoSource$InputDsoIterator;)V
W/dalvikvm( 4800): VFY:  rejecting opcode 0x0d at 0x01f6
W/dalvikvm( 4800): VFY:  rejected Lcom/facebook/soloader/UnpackingSoSource;.regenerate (BLcom/facebook/soloader/UnpackingSoSource$DsoManifest;Lcom/facebook/soloader/UnpackingSoSource$InputDsoIterator;)V
W/dalvikvm( 4800): Verifier rejected class Lcom/facebook/soloader/UnpackingSoSource;
D/AndroidRuntime( 4800): Shutting down VM
W/dalvikvm( 4800): threadid=1: thread exiting with uncaught exception (group=0xa4d3bb20)
W/genymotion_audio(  318): out_write() limiting sleep time 73650 to 39909
W/genymotion_audio(  318): out_write() limiting sleep time 93605 to 39909
W/genymotion_audio(  318): out_write() limiting sleep time 113560 to 39909
E/CrashlyticsCore( 4800): Failed to execute task.
E/CrashlyticsCore( 4800): java.util.concurrent.TimeoutException
E/CrashlyticsCore( 4800):       at java.util.concurrent.FutureTask.get(FutureTask.java:176)
E/CrashlyticsCore( 4800):       at com.crashlytics.android.core.CrashlyticsBackgroundWorker.submitAndWait(CrashlyticsBackgroundWorker.java:41)
E/CrashlyticsCore( 4800):       at com.crashlytics.android.core.CrashlyticsController.handleUncaughtException(CrashlyticsController.java:285)
E/CrashlyticsCore( 4800):       at com.crashlytics.android.core.CrashlyticsController$5.onUncaughtException(CrashlyticsController.java:269)
E/CrashlyticsCore( 4800):       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:30)
E/CrashlyticsCore( 4800):       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
E/CrashlyticsCore( 4800):       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
E/CrashlyticsCore( 4800):       at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 4800): FATAL EXCEPTION: main
E/AndroidRuntime( 4800): Process: com.gpsgate.assetprotection, PID: 4800
E/AndroidRuntime( 4800): java.lang.VerifyError: com/facebook/soloader/UnpackingSoSource
E/AndroidRuntime( 4800):        at com.facebook.soloader.SoLoader.initImpl$1a54e370(SoLoader.java:189)
E/AndroidRuntime( 4800):        at com.facebook.soloader.SoLoader.init$1a552341(SoLoader.java:1105)
E/AndroidRuntime( 4800):        at com.gpsgate.assetprotection.MainApplication.onCreate(MainApplication.java:62)
E/AndroidRuntime( 4800):        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
E/AndroidRuntime( 4800):        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4328)
E/AndroidRuntime( 4800):        at android.app.ActivityThread.access$1500(ActivityThread.java:135)
E/AndroidRuntime( 4800):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
E/AndroidRuntime( 4800):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 4800):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 4800):        at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime( 4800):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 4800):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 4800):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime( 4800):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime( 4800):        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Gumija** [comment] 2017-10-04 14:14
Tested on android 4.4.4. Error with dalvik and works fine with ART.

**Comment by Gumija** [comment] 2017-10-06 09:47
For me adding this in `proguard-rules.pro` fixed it:
```
# SoLoader
-keep class com.facebook.soloader.** { *; }
```

**Comment by butchmarshall** [comment] 2017-10-11 13:00
I also added to the end of /android/app/proguard-rules.pro - but to no effect.

Do I need to do some extra compilation step in order for this to work?

**Comment by fenglu09** [comment] 2018-01-23 03:43
Add `-keep class com.facebook.soloader.** { *; }`  not working for me ,too.

**Comment by fenglu09** [comment] 2018-01-24 11:17
Did someone have solved it？ Help me please.
RN: 0.48.2

**Comment by ccdwyer** [comment] 2018-02-04 23:22
I'm having the same issue, but with react-native-pdf. https://github.com/wonday/react-native-pdf/issues/89

**Comment by fenglu09** [comment] 2018-04-18 06:56
Andy update ？

**Comment by fenglu09** [comment] 2018-04-19 09:57
@drakmail  Had you solved it? I have the exactly the same issue

**Comment by LironErman** [comment] 2018-05-01 14:00
According to: https://github.com/facebook/react-native/issues/7530#issuecomment-267388528
I added this:
```
# SoLoader
-keep class com.facebook.soloader.** { *; }
-keepclassmembers class com.facebook.soloader.SoLoader {
   static <fields>;
}
```

and now it works

react-native 0.54.2
android 4.4.2
