### ISSUE TITLE
Docs for TextInput don't say what styles it can take, incorrectly hint that they can handle all Text styles

### ISSUE THREAD

**Issue by seanparsons** [facebook/react-native#7070] opened 2016-04-19 17:15 UTC
According to the docs for [TextInput](https://facebook.github.io/react-native/docs/textinput.html) it supports the same styling options as [Text](https://facebook.github.io/react-native/docs/text.html). In testing this at the bare minimum all of the shadow and line decoration options aren't supported.

This can be seen in this playground:
[https://rnplay.org/apps/sdqbqw](https://rnplay.org/apps/sdqbqw)
If the `Text` element is replaced with a `TextInput` element with the same style the shadow is lost.

I can imagine that the native text input element isn't conducive to supporting shadows, which is why this is happening.

**Comment by dimitrovskif** [comment] 2016-04-21 17:45
Please label your issue with a platform. 

> I can imagine that the native text input element isn't conducive to supporting shadows, which is why this is happening.

At least on Android, native text inputs don't have text shadows (although background shadows are common)

**Comment by seanparsons** [comment] 2016-04-21 20:38
@dimitrovskif So far I've only tested this on iOS.

**Comment by dimitrovskif** [comment] 2016-04-21 20:47
@seanparsons Have you tried rendering text shadow on text input control on iOS using native swift/objective-c? I am not sure if that is possible.

**Comment by seanparsons** [comment] 2016-04-21 20:55
@dimitrovskif I've not, but since it works for `Text` and not `TextInput` it doesn't really matter either way. The docs list it as being possible when it isn't.

**Comment by dimitrovskif** [comment] 2016-04-21 21:08
`Text.js` uses `UITextView` and `TextInput.js` uses `UITextField` so they are completely different native objects.

The docs say that the `TextInput` can receive the same props as `TextView` but that doesn't mean the engine can render all styles. A quick search says that there is no built-in support for text shadow on inputs, however you may access the internal `CALayer` and apply shadow to it (which unfortunately will apply shadow to the cursor, the selection indicator and all field subviews)

**Comment by seanparsons** [comment] 2016-04-21 22:08
@dimitrovskif I'm really not sure what point you're trying to make, it shouldn't make any difference what Apple or Google support natively in their controls. The docs should represent what is supported by React Native, leaving everyone to find it out blindly (some of them are explicitly listed as being only available on iOS as well) isn't a great experience for anyone.

**Comment by grabbou** [comment] 2016-04-23 15:31
@dimitrovskif in fact, our docs are saying it accepts the same style https://facebook.github.io/react-native/docs/textinput.html#style

**Comment by lacker** [comment] 2016-10-21 04:07
Yeah, these docs are pretty bad right now - in particular https://facebook.github.io/react-native/docs/textinput.html#style says nothing but that should probably be a concise description of which styles work and which don't.

**Comment by hramos** [comment] 2017-05-25 20:42
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by ajostergaard** [comment] 2017-05-25 21:27
Given that the docs still don't actually say which styles will actually work don't you think closing the issue is premature?

**Comment by hramos** [comment] 2017-05-25 21:40
Good point. I've been tackling docs issues, so I'll just assign this to myself.

**Comment by xaviervia** [comment] 2017-06-16 14:24
Coming here from the documentation about TextField: it seems that replacing the font family is not working on Android. Is this one of the styles that is not supported? I’m surprised that I did not find any issue specifically about that, so I think I might have missed something.

**Comment by RUIFERNANDE5** [comment] 2017-06-20 13:40
I'm having trouble setting in `paddingVertical` on multiline inputs. Any known issue?

**Comment by Amurmurmur** [comment] 2017-07-17 01:04
@RUIFERNANDE5 use `marginVertical` 👍

**Comment by zeddysoft** [comment] 2017-07-26 19:41
Hi @hramos  ! I am new to Open Source and want to dive into this issue, though i could see you have assigned it to yourself, it is possible you re-assign it to me so i can get started with contributing.

**Comment by hramos** [comment] 2017-07-26 21:06
Sure! Thanks for volunteering 🙌

**Comment by hramos** [comment] 2017-07-26 21:06
All yours

**Comment by zeddysoft** [comment] 2017-07-27 14:58
Hi @hramos , to get started, i guess i would have to check out Text styles that do not work for TextInput component right and list them? because the doc has already being updated with the below:

'Note that not all Text styles are supported, see Issue#7070 for more detail.'

**Closed** 2017-10-09 17:27 UTC
Labels: Documentation, Icebox

**Comment by marcind** [comment] 2017-10-12 18:36
Hi, this is still not resolved: http://facebook.github.io/react-native/releases/0.50/docs/textinput.html Please reopen and throw together a simple bullet point list of what is supported.

**Comment by hramos** [comment] 2017-10-12 19:25
@marcind please open a PR and I'll take a look

**Comment by marcind** [comment] 2017-10-12 21:34
Sorry, I'm not familiar with the internal workings of react-native so wouldn't know where to start to figure this out (other than trying every style property in some sample to see what works and what does not). I was hoping that someone who maintains this project has enough knowledge to quickly provide a list.
I found this issue while trying to determine why my code was not working and was dismayed that it keeps getting closed by a bot.
Anyway, here's the PR: https://github.com/facebook/react-native/pull/16346
