### ISSUE TITLE
Websockets iOS Simulator — Invalid Sec-WebSocket-Accept response

### ISSUE THREAD

**Issue by movie4** [facebook/react-native#15082] opened 2017-07-18 14:57 UTC
1. `react-native -v`: 0.44.0
2. `node -v`: v8.0.0
3. `yarn --version`0.27.5:

- Target Platform: iOS Simulator 9.3
- Development Operating System: MacOS Sierra
- Build tools: Xcode 8.3.3

Demo example from http://facebook.github.io/react-native/docs/network.html#websocket-support not connect to websockets

**Comment by hramos** [comment] 2017-07-18 20:06
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-07-18 20:06 UTC
