### ISSUE TITLE
SyntaxError: Unexpected token '...' after fresh npm install

### ISSUE THREAD

**Issue by KevinGrandon** [facebook/react-native#2141] opened 2015-07-27 20:05 UTC
This started happening on both 0.8 and 0.6, so my guess is that a dependency broke.

![ilpzase](https://cloud.githubusercontent.com/assets/122602/8916398/11ef4d68-3460-11e5-8f4a-db8f67d48ba1.png)

**Comment by KevinGrandon** [comment] 2015-07-27 20:06
In my local index.ios.bundle, this leads to this line:
`warning = function(condition,format,...args){`

**Comment by ericvicenti** [comment] 2015-07-27 20:28
Transform error. cc @amasad @DmitrySoshnikov

**Comment by ericvicenti** [comment] 2015-07-27 21:07
Dupe of #2134. A workaround is explained there.

**Closed by ericvicenti** 2015-07-27 21:07 UTC
