### ISSUE TITLE
Jumpy sticky section headers in SectionList

### ISSUE THREAD

**Issue by sachinB94** [facebook/react-native#22775] opened 2018-12-24 09:27 UTC
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.5
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 99.75 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        API Levels: 17, 19, 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.1, 27.0.3, 28.0.2, 28.0.3
        System Images: android-17 | Google APIs Intel x86 Atom, android-19 | Google APIs Intel x86 Atom, android-21 | Google APIs ARM EABI v7a, android-22 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom_64, android-24 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-25 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.57.8 => 0.57.8
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-ci-tools: 1.1.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Description
Section header jumps a lot when `stickySectionHeadersEnabled` prop is passed. When rendering a section with large number of items, and scrolling to it, the header keeps on jumping. Also, the scroll keeps on going backwards.

One thing to note is that, `onScroll` is never fired when this behaviour is happening. Although, `onViewableItemsChanged` keeps on firing.

## Reproducible Demo
https://snack.expo.io/SJeFV7Ax4

I think this is related to #15445. But, that issue is already closed.

**Comment by danilobuerger** [comment] 2019-01-01 15:43
Possible duplicate of #20956

**Comment by sachinB94** [comment] 2019-01-02 10:06
@danilobuerger I'm using `0.57.8`, which, I believe, already has that pull request merged.

![code](https://user-images.githubusercontent.com/5407782/50587427-ec64d500-0ea3-11e9-8ab0-a71d361ea7ab.png)

But, the issue is still there.

**Comment by danilobuerger** [comment] 2019-01-02 10:08
The PR is not merged -> #22025

**Comment by tomas-paronai** [comment] 2019-02-05 12:52
Tried the patch in our app and it did not help. When I scrollToLocation somewhere near the bottom and do a little scrolling the content jumps unexpectedly. Sometimes exchanging sections forth and back.

**Comment by michalchudziak** [comment] 2019-04-25 15:29
Hello there 👋 this issue seems to have been inactive for the past few weeks. Because of this, it's likely that the issue is not a high priority anymore or it has been solved by OP; for these reasons, we'll close it. But please, if it's actually still an issue with 0.59 please comment below and we can reopen it or please send us a Pull Request with a fix 😊

**Closed by michalchudziak** 2019-04-25 15:29 UTC
Labels: Component: SectionList, Type: Bug Report

**Comment by shilch** [comment] 2019-05-03 09:01
Bump
