### ISSUE TITLE
Requiring image by name gives warning

### ISSUE THREAD

**Issue by anahitsk123** [facebook/react-native#11116] opened 2016-11-24 16:14 UTC
Hi ,

I get this warning on chrome debugger:
Requiring module <IMAGE> by name is only supported for debugging purposes and will BREAK IN PRODUCTION!

Can you help me, why I get this ?

**Comment by mkonicek** [comment] 2016-11-24 21:01
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but we can reopen if additional information is provided. Thanks!

**Closed by mkonicek** 2016-11-24 21:01 UTC

**Comment by anahitsk123** [comment] 2016-11-28 15:31
Hi again. 

yes, I am requiring an image like this:

<Image source={require('./img/SOMEIMAGE.png')} />

and get the warning in debugger.

**Comment by rccoder** [comment] 2017-03-26 12:24
@anahitsk123  Hi, I get this problem too.

Could you solve it?

**Comment by haifaGh** [comment] 2017-04-14 12:24
hey, i'm facing the exact same problem .. so did you find a solution yet ?
