### ISSUE TITLE
setState not work, UI cannot refresh data

### ISSUE THREAD

**Issue by ToccaLeee** [facebook/react-native#3411] opened 2015-10-14 14:28 UTC
When JS calls the native method that doing a long time task( such as network data fetch, or just let the thread sleep for a while), then calling the callback JS passed。In JS callback, use setState to update data, but the UI cannot be refreshed. for example:
native code:
RCT_EXPORT_METHOD(getAppVersion:(RCTResponseSenderBlock)callback) {
    callback(@[[NPSSystemInfo appVersionStringValue]]);
}
JS code:
   NativeModules.NPSSystemInfo.getDetailAppVersion((version) => {
      if (version !== undefined) {
        alert(version);
         this.setState({appVersion:version});
      }
   });

the alert view can show the correct data, but the view use the version data cannot be refreshed, why ? can anyone help ??

**Comment by javache** [comment] 2015-10-14 16:00
Duplicate of #3410.

**Closed by javache** 2015-10-14 16:00 UTC
