### ISSUE TITLE
NavigationExperimental slow/freeze on Android compiled from Windows

### ISSUE THREAD

**Issue by bosung90** [facebook/react-native#6666] opened 2016-03-26 09:50 UTC
https://goo.gl/photos/X4xmbXJFGXtbvg389
Using Windows 10 x64
Pushing/popping causes JS frame to go to -2 and freezes eventually crashing.
Happens on RN 0.22
On RN 0.23 the frame drops very low (0~20) on push/pop but usually recovers after a short delay, due to low JS frame animation is not smooth.

Note that JS frame rate dropping happens regardless of navigation animation (ex. tabbar).

Also tried on latest master branch and same thing occurs. (Commit: 235b16d)

Occurs 100% of the time on physical device Galaxy S6 on Android 5.1.1 and emulator nexus 5 x64 Android 6.

**Comment by satya164** [comment] 2016-03-26 10:14
@bosung90 Are you connected to the debugger by any chance?

**Comment by terrysahaidak** [comment] 2016-03-26 10:23
I have the similar issue as well. With production build on my Galaxy S4 i9505 Android 5.1.1 it's super slow and sometimes it freezes and crashes. Thought its only problem with android, but it also cen be related to operation system I'm using - windows 10.

**Comment by rulatir** [comment] 2016-03-26 16:54
Same issue here. Setup: developing on linux, running on Android emulator on the same machine. This probably indicates that the bug is not platform specific.

Also, **very weirdly**, while this appears to be **caused** by the involvement of NavigationExperimental (via react-native-router-flux in my case), it is apparently not related to navigation actions. I am not even navigating, but merely clicking on a hello world component that displays a number incremented on every click (stored in component's state), and that is literally all it does. After every click memory is leaked, and **exponentially so**: cat /proc/$pid/status shows things like this (grepped output):

VmData:   154092 kB
VmData:   154356 kB
VmData:   154568 kB
VmData:   154972 kB
VmData:   157032 kB
VmData:   158480 kB
VmData:   167032 kB
VmData:   198712 kB
VmData:   332040 kB
VmData:   818432 kB

The corresponding diffs are:

264
212
404
2060
1448
8552
31680
133328
486392

Additional observations:

* After the 7th click and all subsequent clicks there is noticeable CPU grinding.
* Weirdly, the grinding happens **after** the component is re-rendered. During the grinding memory usage goes up rapidly, and eventually the app OOMs after the 10th click, while the number 10 is already being displayed.

**Comment by bosung90** [comment] 2016-03-26 19:28
@satya164 I am not using chrome debugger. 
I was using dev=true and minify=false but I just tried dev=false and minify=true and I still get non-smooth navigation animation during push/pop but not as bad.

**Comment by agrass** [comment] 2016-03-28 19:02
I'm with same problem of @rulatir after upgrading to RN 0.22.2 on Linux running in genymotion emulator of Android nexus 5 and also in not emulated device.  I'm working with  react-native-router-flux 3.2.3, but if more people are with this issue without react-native-router-flux may be is problem of NavigationExperimental. Someone with some workaround for this?

**Comment by rulatir** [comment] 2016-03-29 03:54
The author of react-native-router-flux maintains that the problem is indeed in NavigationExperimental.

**Comment by delta-9** [comment] 2016-03-29 07:53
I confirm this issue, the app freeze and crash after 5-10 scene rendering with the new NavigationExperimental.

**Comment by thessem** [comment] 2016-03-29 11:00
This is a problem for me with through react-native-router-flux, though the author says the issue is with NavigationExperimental. This is with and without debug on a real device from osx with RN 0.22.2

**Comment by satya164** [comment] 2016-03-29 11:20
cc @ericvicenti @hedgerwang

**Comment by satya164** [comment] 2016-03-29 11:22
Can anybody give a simple reproducible example?

**Comment by thessem** [comment] 2016-03-29 11:31
The example project over at https://github.com/aksonov/react-native-router-flux/tree/master/Example on an android device should do it, although I haven't personally run it and seen this bug, I've also seen on a few other issues that this happens on the RN UIExplorer project on android without using RNRF (e.g. https://github.com/aksonov/react-native-router-flux/issues/355 for UIExplorer and https://github.com/aksonov/react-native-router-flux/issues/401 for somebody having the issue with RNRF example)

Apologies for these being RNRF based but that's how I'm interacting with the navigator

**Comment by satya164** [comment] 2016-03-29 11:40
@thessem The example provided there is not strictly NavigationExperimental, even if it uses it. So it's difficult to pinpoint the issue from there. It'll be useful to have a simpler example just using NavigationExperimental and no other libraries.

**Comment by terrysahaidak** [comment] 2016-03-29 12:42
@satya164 you can check also my attempt to use it, but it's pretty complex:
https://github.com/terrysahaidak/GitterMobile/tree/experimental-navigator
Simple [navigation module](https://github.com/terrysahaidak/GitterMobile/blob/experimental-navigator/app/modules/navigation.js), [main routes files](https://github.com/terrysahaidak/GitterMobile/blob/experimental-navigator/app/screens/index.js), and [simple navigation animated view with opacity](https://github.com/terrysahaidak/GitterMobile/blob/experimental-navigator/app/components/NavigationOpacityView.js). It freezes after several pushes, also app crashes even without animation view and any transitions.

**Comment by albo1337** [comment] 2016-03-31 14:36
how is the status here? I have the same problem

**Comment by bosung90** [comment] 2016-03-31 22:27
@albo1337 0.23rc seems to solve a lot of problems with freezing so I think you can start using 0.23rc and just hope it will be fixed in future releases.

**Comment by caledhwa** [comment] 2016-04-01 16:40
I also have this same issue. I'm running on MacOSx and using Genymotion for testing. No noticeable issues in iOS Simulator - only Genymotion. I am also using react-native-router-flux. This seems like a pretty serious issue IMHO. Going to switch to 0.23.0-rc4 to see if there's any improvement there.

**Comment by bosung90** [comment] 2016-04-01 18:15
@caledhwa Let me know how it goes

**Comment by caledhwa** [comment] 2016-04-01 19:24
So, definite improvement of navigation performance on Android with react-native-router-flux AND 0.23.0-rc4. 

However, it broke many other things. I'm also using https://github.com/brentvatne/react-native-linear-gradient - and it stopped rendering those components altogether on android. 

But the worst problem? It's related to this issue: https://github.com/aksonov/react-native-router-flux/issues/416 - this completely stops my app on iOS. So, if I can't run it on iOS and Android with success, I'm a bit hosed. For now, I'm doing most of my dev back on 0.22.2 and am just not testing on Android with hopes for a fix here.

**Comment by sylvainbaronnet** [comment] 2016-04-09 14:22
seems fixed with 0.24.0-rc3

**Comment by caledhwa** [comment] 2016-04-09 14:28
It was fixed for me (the slowness) on 0.24.0-rc2

**Comment by devux** [comment] 2016-04-21 05:53
Thanks all I have same problem fixed now after upgrading to 0.24.0 but now the screens or overriding when moving to another screen any solutions for that?

**Comment by satya164** [comment] 2016-04-21 09:05
Closing since this seems to be fixed.

**Comment by satya164** [comment] 2016-04-21 09:06
@devux What do you mean by that?

**Closed by satya164** 2016-04-21 09:05 UTC
Labels: Android, Perf
