### ISSUE TITLE
Non-Latin Text Misalignment in Android 13 with RN 0.72.6

### ISSUE THREAD

**Issue by GGlin98** [facebook/react-native#41128] opened 2023-10-20 18:29 UTC
### Description

I've encountered an issue related to the vertical alignment of non-Latin text within the Text component when running on Android 13 devices. The text fails to align vertically in the center as expected. This issue seems to be specific to Android 13, as the same code works perfectly and aligns the text as expected on Android 12 devices.

### React Native Version

0.72.6

### Output of `npx react-native info`

System:
  OS: macOS 14.0
  CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Memory: 20.12 GB / 64.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.0.0
    path: ~/.nvm/versions/node/v21.0.0/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 10.2.1
    path: ~/.nvm/versions/node/v21.0.0/bin/npm
  Watchman:
    version: 2023.10.09.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10811636
  Xcode:
    version: 15.0/15A240d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.21
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.6
    wanted: 0.72.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

1. Create a new React Native project.
2. Replace the default code with the provided code snippet.
3. Run the app on an Android 13 device.

```typescript
import { StyleSheet, Text, View } from 'react-native';

export default function App() {
  return (
    <View style={styles.container}>
      <View style={styles.text_container}>
        <Text style={styles.text}>中文中文中文中文</Text>
      </View>

      <View style={styles.text_container}>
        <Text style={styles.text}>にほんごにほんご</Text>
      </View>

      <View style={styles.text_container}>
        <Text style={styles.text}>한국어한국어한국어</Text>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff'
  },
  text_container: {
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    backgroundColor: '#ff0',
  },
  text: {
    fontSize: 40,
    color: '#f00'
  }
});
```

### Snack, screenshot, or link to a repository

[Reproducer Snack](https://snack.expo.dev/@lgz616/reproduce-bug)

|  Android 12 (Expected Behavior)   | Android 13 (Observed Issue)  |
|  ----  | ----  |
| <img height="500" alt="image" src="https://github.com/facebook/react-native/assets/31837979/1cba77c5-2d50-409e-8705-55564a791118">  | <img height="500" alt="image" src="https://github.com/facebook/react-native/assets/31837979/d77cb116-96c6-41af-92ef-9196a2f42bc1"> |

**Comment by cortinico** [comment] 2023-10-24 13:25
Duplicate of https://github.com/facebook/react-native/issues/39750

**Closed by cortinico** 2023-10-24 13:25 UTC
Labels: Platform: Android, Needs: Triage :mag:
