### ISSUE TITLE
socket.io not emitting any events with RN

### ISSUE THREAD

**Issue by jchoi18** [facebook/react-native#9515] opened 2016-08-22 04:55 UTC
There seems to be a bug when using RN with socket.io. Using the socket.io-client api, everything works fine but the emit function. I can connect/disconnect, and receive events on the client side but not fire any. 

http://stackoverflow.com/questions/39068632/react-native-socket-io-no-events-being-emitted-from-client/39071513?noredirect=1#comment65491379_39071513

**Comment by jchoi18** [comment] 2016-08-22 15:01
This issue might be related to https://github.com/socketio/engine.io-parser/issues/59?

**Comment by polarathene** [comment] 2016-09-05 00:22
The issue does cause problems using socket.io with React-Native. It's been fixed in git with the PR but the maintainer never released a new version on NPM. He's been unresponsive to that repo since April. No idea when/if it'll see a release as reaching out to other members for the project has not been effective.

**Comment by sibelius** [comment] 2016-10-09 02:07
any progress or workaround on this @jchoi18 @polarathene ?

**Comment by polarathene** [comment] 2016-10-09 06:02
@sibelius The maintainer recently addressed it with a new release containing the PR. The problem shouldn't exist anymore, I'm unable to verify any time soon.

**Comment by chirag04** [comment] 2016-10-09 17:27
engine.io-parser#55 has been merged on master, both socket.io-client and engine.io-client are bumped to a new version. I can confirm it all works now. 

Let's reopen if this is still an issue.

**Closed by chirag04** 2016-10-09 17:27 UTC
