### ISSUE TITLE
debugging does not work in Chrome

### ISSUE THREAD

**Issue by hamicornfury** [facebook/react-native#10729] opened 2016-11-04 03:52 UTC
### Description
I really like a lot of things about React Native, but debugging is really sub-par. WHEN the Chrome development tools "kinda" work with RN performance becomes so slow that you cannot really do anything, including debug. 

I am unable to set breakpoints, they just don't set or they "jump" to other lines and still don't work. Even if I put "debugger" in my code it does not stop on those statements. I end up using console.warn statements, which is also far from optimal. 

Totally get that RN is new, it is hard to make it all play nice etc. etc., but wow would it be great to have a decent debugging experience. 

This my not qualify as a bug, as in some exception, but it definitely is a bug in usability. This problem is not only me and my computer/setup. I have seen the same issues with other people I code with. 

### Additional Information

* React Native version: 0.31 and 0.36
* Platform: Android
* Operating System: Mac OSX 
* Chrome Version 54.0.2840.87

**Comment by hamicornfury** [comment] 2016-11-06 02:16
So I have been having similar issues related with a game that I have been developing. Chrome Developer Tools basically useless, which really is unfortunate since they are actually helpful. 

What I have been doing is using console.warn to get output in my simulator, or using adb logcat from the command line to see console.log statements. While both work, I like modern convenience and the fact that JS is an interpreted language and I can play around with it in a debug environment.

Any how, figured let's update to 0.36 start code over and see if there was something I was doing that broke things. 

What I found, by chance for me, was that if you have even one extra Chrome window/tab open besides the Chrome Developer Tools window the debugger basically does not work, WTF. 

With just the Developer Tools open debugger actually works, again WTF. There is still a performance hit, but at least for me it is usable. 

Hope this helps others.

**Comment by holleB** [comment] 2016-11-10 09:12
Same here, but closing all chrome tabs besides developer tools doesn't help. 
- React Native 0.36 & 0.37
- Platform Android & iOS Simulator
- OS macOS
- latest Chrome 54.0.2840.98

**Comment by hamicornfury** [comment] 2016-11-14 05:30
@holleB it is a bummer that debugging via Chrome is not better. Hopefully it will get some love, the annoying part is that it is inconsistent, i.e. for some people it appears to work fine for other no go :( 

Not only that, but it is inconsistent in the same project, I have some files that it works fine, some files that the source-map does not work. Sometimes when debugging performance is horrible, sometimes it is good :(

**Comment by bartonhammond** [comment] 2016-11-14 16:30
+1
* RN: 0.37
* iOS Simulator
* MacOS: 10.11.5
* Chrome:  54.0.2840.98 (64-bit)

<img width="950" alt="screen shot 2016-11-14 at 10 29 45 am" src="https://cloud.githubusercontent.com/assets/1282364/20272999/57d72820-aa55-11e6-9cf1-b5d17ef6b618.png">

**Comment by holleB** [comment] 2016-11-15 14:11
Ok, so after days of trying to fix this I stumbled upon a workaround. At least for me the problem tends to appear in files > 100 lines with multiple arrow functions. So my workaround ist to split these files without changing the functionality of the code. Sounds strange but works :-( Very unsatisfying, but I neither have the time nor the javascript foo to figure out the root cause.

**Comment by bartonhammond** [comment] 2016-11-15 15:17
That's not good.  I've been working on this and it seems to be with the
source maps.  There is an issue on FB RN about it.  Hopefully it will be
addressed.

**Comment by hamicornfury** [comment] 2016-11-17 04:46
@holleB, if you remove the arrow functions does that also work?

**Comment by holleB** [comment] 2016-11-17 08:08
@hamicornfury Tried but didn't work. *But* what seems to work is the fix mentioned https://github.com/bartonhammond/snowflake/issues/164 by @wookiem. Thx a lot guys!

**Comment by duhseekoh** [comment] 2017-01-19 22:19
FYI. I was having trouble setting breakpoints when I had `function someFn() {}`.

Replace `function someFn() {}`
with
`const someFn = () => {}`

**Comment by wookiem** [comment] 2017-01-20 16:08
@duhseekoh You've made my day!! This has been a huge PITS for me.  

Would you mind posting your solution to: http://stackoverflow.com/questions/37078774/cant-always-set-react-native-breakpoints-in-chrome/40532885#40532885

**Comment by wookiem** [comment] 2017-01-26 21:09
@duhseekoh I added your detailed solution to the stackoverflow link that I referenced.  

I think we can consider this issue closed now.

**Comment by jhabdas** [comment] 2017-02-28 17:41
I believe this is a source maps issue unrelated to RN or Webpack, but exacerbated by them. It's been around since Backbone. Which source map style are you using? Also, ProTip, try moving your breakpoint to the next line and leverage "debugger" statements. If you're logging you're wasting time.

**Comment by ciceroneves** [comment] 2017-03-13 23:24
Hey @jhabdas,

I am facing the same issue where when I set a breakpoint, it is automatically moved to the next function declaration. I suspected it had something to do with the source map when the code is transpiled by babel. Do you have any tips on how to fix it? Even pointing to an issue being more actively tracked would help.
I don't think changing all the function declarations like was suggested before is an acceptable solution. It is just a workaround.

Thanks in advance
Thanks

**Comment by jhabdas** [comment] 2017-03-14 02:43
Tips:

- Add a line of code immediately above the line you want to break on and reset your breakpoint after it shifts when the source maps are rebuilt
- Add "debugger" where you want to break, then remove it when you're finished
- If the breakpoint you set in Dev Tools jumps to the bottom of the block when you set it, try it anyway as looks can sometimes be deceiving

Point to an issue? Nope. Been seeing the problem since Backbone + jQuery. Does it happen in Firefox or WebKit? That will be your tell as to the root cause.

**Comment by astapinski** [comment] 2017-03-18 19:10
Just FYI , try this again with RN 0.42. The source map generation was refactored and it seems to have solved similar issues in my company's app.

**Comment by zjaml** [comment] 2017-03-20 00:51
@astapinski Thanks! That worked for me just in time!

**Comment by ciceroneves** [comment] 2017-03-29 16:50
I have tried the *"debugger"* approach before but it did not work. The issue is mainly visual and I am saying that because when I take a look on the context when the breakpoint is hit it shows me all the variables in original place I put the breakpoint. I just wanted a way to fix this because it is so annoying.

I will try the RN 0.42 and see if it works :)

So far what worked for me was the suggestion made by @duhseekoh. I don't understand why there can't be ANY functions in the source file you're trying to set a breakpoint in.

Thanks!

**Comment by hramos** [comment] 2017-07-20 22:35
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/debugging-does-not-work-in-chrome

**Closed by hramos** 2017-07-20 22:35 UTC
Labels: Icebox

**Comment by hovox** [comment] 2018-02-21 12:45
Hi, we are using 0.53 version of react native and still can't use breakpoints consistently. Sometimes when setting a breakpoint it's moving the bottom, or sometimes it's moving to the completely different file. Would be good to reopen this issue. Can someone explain how it's working and why it's working incorrectly (setting a breakpoint). I would like to contribute on the fix. Thanks.

**Comment by jim-lake** [comment] 2018-02-24 18:14
Adding `"sourceMaps": "inline"` to .bablerc fixed this for me.

**Comment by reedspool** [comment] 2018-02-28 05:11
@jim-lake's suggestion cured my blues. If there are no downsides to this I vote to add this to core.

**Comment by saumya27** [comment] 2018-03-09 05:14
@duhseekoh thanks a lot... it worked like a bliss... dont know the reson though, but good until chrome developers fix their dev tool totally :)

**Comment by jack828** [comment] 2018-07-15 08:41
I was also experiencing this issue - huge thanks to @jim-lake for the fix!
