### ISSUE TITLE
Attempt to invoke virtual method 'void com.facebook.react.uimanager.UlManagerModule.onBatchComplete()' on a null object reference

### ISSUE THREAD

**Issue by NomanAli65** [facebook/react-native#47757] opened 2024-11-20 12:25 UTC
### Description

Android app crashes when input is focused

### Steps to reproduce

create new react-native app on 0.76.2
create a new screen and add input
run and test it will crash

### React Native Version

0.76.2

### Affected Platforms

Runtime - Android

### Areas

Fabric - The New Renderer

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.1.1
  CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Memory: 6.22 GB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 22.4.1
    path: /usr/local/bin/node
  Yarn:
    version: 3.6.4
    path: /usr/local/bin/yarn
  npm:
    version: 10.8.1
    path: /usr/local/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.13.0
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9514443
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.1
    wanted: 15.0.1
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.2
    wanted: 0.76.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
```

### Stacktrace or Logs

```text
.........
```

### Reproducer

https://github.com/NomanAli65

**Comment by kosick** [comment] 2024-11-21 08:09
I also encountered the same issue, and as mentioned in this comment, 
[#47445](https://github.com/facebook/react-native/issues/47445#issuecomment-2487129890)
removing react-native-ui-lib resolved the problem. After removing the library, I verified that the TextInput now functions as expected.

**Comment by cipolleschi** [comment] 2024-12-02 17:32
closing as this is a duplicate of https://github.com/facebook/react-native/issues/47662 which has the simplest reproducer (a snack)

**Closed by cipolleschi** 2024-12-02 17:32 UTC
Labels: Needs: Author Feedback, Needs: Repro, Type: New Architecture
