### ISSUE TITLE
Is there any plan to upgrade the android support libraries to the latest version (25+)?

### ISSUE THREAD

**Issue by drivedreams** [facebook/react-native#14516] opened 2017-06-14 15:17 UTC
Why react do not upgrade the support libraries` version. **I am confused for that!!!**   Library version 25 has already been publish for a long time.  Less and less project will continue use api 23. 
I want to integrate react-native into my project, but the ridiculous version problem stop me!  I have used so many open source project, there is no one like that.  Can any contributor solve it?

I am appreciate to the contributors for provide such a great project. I hope react-native to better!

**Comment by hramos** [comment] 2017-06-14 17:58
This is a dupe of your earlier issue #12025. If you think that issue should remain open, perhaps comment on it instead of opening a new one?

**Closed by hramos** 2017-06-14 17:58 UTC
