### ISSUE TITLE
[IOS] Simulator : JavaScriptCoreWTF::CrashOnOverflow::crash:

### ISSUE THREAD

**Issue by cherniv** [facebook/react-native#10127] opened 2016-09-27 09:48 UTC
While testing in iPhone SE simulator pressing CMD+R freezes the app with this error in xCode:
[![enter image description here](http://i.stack.imgur.com/DyUQU.png)](http://i.stack.imgur.com/DyUQU.png)

React Native version: 0.34, 
platform: iOS.

Started after upgrading of xCode to version 8.0

**Comment by lacker** [comment] 2016-11-30 20:20
I can't reproduce this problem. It does seem like there were some other reports that were fixed by reinstalling parts of the build process, so it's annoying but if this persists you might want to try reinstalling react native + xcode.

**Closed by lacker** 2016-11-30 20:20 UTC
