### ISSUE TITLE
Can't override babel-preset-react-native settings

### ISSUE THREAD

**Issue by keeth** [facebook/react-native#6611] opened 2016-03-23 18:39 UTC
Following up on a conversation related to 36893ec.

Upgrading babel-preset-react-native from 1.5.2 to 1.5.3 broke our app, due to firebase.js not being strict-mode compatible.  I worked around this, but wanted to file a follow-up issue that the technique suggested in the 36893ec commit message for overriding the preset to disable strict mode does not work.

I put together a minimal case.. just apply the following patch over an empty 'react-native init' (RN 0.22) project. the error evaluating 'n.navigator', due to Firebase not being strict-mode compatible, happens even with a .babelrc that overrides the preset.

It looks like the ability to override presets in Babel 6 [is a work in progress](https://github.com/babel/babel/pull/3331).

```
diff -rNu -x node_modules -x ios strictbug/.babelrc strictbug2/.babelrc
--- strictbug/.babelrc  1969-12-31 16:00:00.000000000 -0800
+++ strictbug2/.babelrc 2016-03-23 09:36:33.000000000 -0700
@@ -0,0 +1,6 @@
+{
+  "presets": ["react-native"],
+  "plugins": [
+    ["transform-es2015-modules-commonjs", { "strict": false, "allowTopLevelThis": true }]
+  ]
+}
diff -rNu -x node_modules -x ios strictbug/index.ios.js strictbug2/index.ios.js
--- strictbug/index.ios.js  2016-03-23 09:41:31.000000000 -0700
+++ strictbug2/index.ios.js 2016-03-23 09:35:27.000000000 -0700
@@ -11,6 +11,8 @@
   View
 } from 'react-native';

+import Firebase from 'firebase';
+
 class strictbug extends Component {
   render() {
     return (
diff -rNu -x node_modules -x ios strictbug/package.json strictbug2/package.json
--- strictbug/package.json  2016-03-23 09:41:43.000000000 -0700
+++ strictbug2/package.json 2016-03-23 09:46:05.000000000 -0700
@@ -6,6 +6,7 @@
     "start": "node node_modules/react-native/local-cli/cli.js start"
   },
   "dependencies": {
+    "firebase": "^2.4.1",
     "react": "^0.14.7",
     "react-native": "^0.22.2"
   }
```

**Comment by satya164** [comment] 2016-03-23 18:57
Wait, I didn't read your diff properly last time. Unfortunately, you can't override presets (as you mentioned). You'll need to copy the plugin list manually. And change the ones you want.

I think we should close this since this is an issue with how babel works, and not RN. cc @janicduplessis 

Thanks a lot for the detailed report with reproducible issue.

**Comment by janicduplessis** [comment] 2016-03-23 19:01
@satya164 Last time I tried it did work, not sure why if it isn't supported. I'll test again tonight.

**Comment by janicduplessis** [comment] 2016-03-23 19:04
@bestander Also had issues with this internally at fb, any luck finding why it didn't work?

**Comment by satya164** [comment] 2016-03-23 19:09
@janicduplessis https://phabricator.babeljs.io/T2756

**Comment by bestander** [comment] 2016-03-23 19:09
@janicduplessis it is still on my list

**Comment by bestander** [comment] 2016-03-29 13:40
Ok, we are reverting the default `"strict": true` change right now.
Thanks, @janicduplessis.
It will be in 0.23.0.
Ok to close?

**Closed by bestander** 2016-03-29 13:40 UTC
