### ISSUE TITLE
React Native version mismatch

### ISSUE THREAD

**Issue by lavarajallu** [facebook/react-native#19268] opened 2018-05-15 12:27 UTC
react-native-cli: 2.0.1
react-native: 0.50.3

in my package .json file 
  "react-native": "^0.50.4",

getting error like this below screen
![screen shot 2018-05-15 at 5 53 09 pm](https://user-images.githubusercontent.com/20550556/40056559-6686d884-5869-11e8-959c-660aa78f7426.png)

i used this 
compile ("com.facebook.react:react-native:0.52.0") { force = true }
But getting error like : 
       In case of problem, please repackage it with jarjar to change the class packages
File /Users/stellent/.android/repositories.cfg could not be loaded.

FAILURE: Build failed with an exception.

```
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find com.facebook.react:react-native:0.50.4.
     Required by:
         project :app
   > Could not find com.facebook.react:react-native:0.50.4.
     Required by:
         project :app > project :react-native-image-resizer
         project :app > project :react-native-fast-image
         project :app > project :react-native-push-notification
         project :app > project :react-native-cookies
         project :app > project :react-native-exception-handler
         project :app > project :@yfuks/react-native-action-sheet
         project :app > project :react-native-incall-manager
         project :app > project :react-native-youtube
         project :app > project :react-native-webrtc
         project :app > project :react-native-xmpp
   > Could not find com.facebook.react:react-native:0.50.4.
     Required by:
         project :app > project :react-native-camera
   > Could not find com.facebook.react:react-native:0.50.4.
     Required by:
         project :app > project :react-native-blur
```

**Comment by Fanghornn** [comment] 2018-05-15 12:33
this... https://github.com/facebook/react-native/issues/19259

**Comment by lavarajallu** [comment] 2018-05-15 12:44
Its not working for me

**Comment by kelset** [comment] 2018-05-15 13:05
Duplicate of #19259

**Closed by kelset** 2018-05-15 13:05 UTC
Labels: :clipboard:No Template

**Comment by flyskywhy** [comment] 2018-05-16 07:55
@lavarajallu , I solved "Could not find com.facebook.react:react-native:0.50.4" by:

move my customize
```
    url "$rootDir/../app/node_modules/react-native-bt-csr/android/libs"
```
in `allprojects.repositories.maven` of `android/build.gradle` to `android/app/build.gradle` and `react-native-bt-csr/android/build.gradle` :
```
repositories {
    maven { url "$rootDir/../app/node_modules/react-native-bt-csr/android/libs" }
}
```
In a word, keep original `allprojects.repositories.maven` of `android/build.gradle`:
```
allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
```
