### ISSUE TITLE
[0.54] <TextInput> not support chinese

### ISSUE THREAD

**Issue by jiangbophd** [facebook/react-native#18379] opened 2018-03-14 15:45 UTC
TextInput not support Chinese

Version: 0.54. 0.55 -rc

Only for IOS

**Comment by vovkasm** [comment] 2018-03-14 21:08
I probably can reproduce this (or similar issue) in simulator.

Environment:
- Xcode 9.2
- iOS 11.2 iPhone 6 simulator
  - Use the same languages as macOS: enabled
  - Connect hardware keyboard: enabled
- RN 0.54.2
- Tested languages: en, ru, ja

Expected behavior (in Settings app):
![native input](http://vovkasm.skitch.vovkasm.org/rn-native-input_2059C445.png)

Actual behavior (in our app single line TextInput):
![TextInput](http://vovkasm.skitch.vovkasm.org/rn-textinput_2059C623.png)
In this case no suggestions, no kanji, most key presses translated to Latin symbols.

**Comment by ForU** [comment] 2018-03-15 12:30
Same Issue occurs on iOS for "react-native": "0.54.0"
on iOS, it can not show the chinese candidate words when keyboard is pressed, like following:

![kapture 2018-03-15 at 20 22 36](https://user-images.githubusercontent.com/1693614/37463182-60980ba0-288f-11e8-82f2-281cd722f342.gif)

i am not familiar with iOS input framework, but guesses can be made that language locales maybe got involved and not handled properly, just a guess!

**Comment by luosong** [comment] 2018-03-16 02:25
@ForU I have same Issue occurs on iOS for "react-native": "0.54.0"

**Comment by danielsuo** [comment] 2018-03-16 03:44
@vovkasm @ForU @luosong Would it be all right to consolidate our comments over on issue #18403? I filled out the template and created both working and broken examples / tagged the authors of the likely commits that caused the breaking change. Hopefully, it will get the attention of Facebook folk faster.

Even though this bug is annoying, really glad that others are also experiencing and it's not just me!

**Comment by danielsuo** [comment] 2018-03-16 03:54
@ForU: I borrowed your excellent gif in my issue (with credit). Hope you don't mind!

**Comment by hramos** [comment] 2018-03-19 21:34
Duplicate of #18403

**Closed by hramos** 2018-03-19 21:34 UTC
Labels: :clipboard:Needs Repro Steps, :clipboard:No Template, :grey_question:Needs More Information, :large_orange_diamond:TextInput, Ran Commands
