### ISSUE TITLE
ios app crashing after launch on ios 14 built on xcode 12.2

### ISSUE THREAD

**Issue by madhudskumar** [facebook/react-native#30428] opened 2020-11-19 14:09 UTC
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
ios app archived on any arm64, arm7 when installed on a real device crashing after launch. Working fine on Debug and release in simulators. 

## React Native version:
Run `react-native info` in your terminal and copy the results here.
```
System:
    OS: macOS 11.0.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 193.51 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.3 - /var/folders/nd/22pg7sxd4xb0gwrm3r5sjf3w0000gn/T/yarn--1605794649569-0.24273519177982372/node
    Yarn: 1.19.1 - /var/folders/nd/22pg7sxd4xb0gwrm3r5sjf3w0000gn/T/yarn--1605794649569-0.24273519177982372/yarn
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-24 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_222 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. npx react-native init testprod --template react-native-template-typescript
2. open testprod.xcworkspace
3. build and run
4. archive 
5. export the ipa
6. run it reald revice (or use browserstack)

## Expected Results
the app runs

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

this might help. 
```
Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x000000000000000e   x1: 0x0000000000000003   x2: 0x0000000000000028   x3: 0x0000000000000030
    x4: 0x0000000000000603   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000403
    x8: 0x0000000000000000   x9: 0x0000000000000000  x10: 0xffffffffffffffff  x11: 0x0000000000000000
   x12: 0x000000028135f138  x13: 0x000000000000ffef  x14: 0x0080000000000000  x15: 0x0000004000000001
   x16: 0xffffffffffffffdc  x17: 0x0000000000000001  x18: 0x0000000000000000  x19: 0x0000000281e53420
   x20: 0x0000000281e533e0  x21: 0xffffffffffffffff  x22: 0x0000000000000001  x23: 0x00000001d4693a71
   x24: 0x0000000000000000  x25: 0x00000001d4256b0b  x26: 0x000000002b870064  x27: 0x0000000000000010
   x28: 0x0000000000000000   fp: 0x000000016cf24e10   lr: 0x000000018d02318c
    sp: 0x000000016cf24e00   pc: 0x00000001b7dc6680 cpsr: 0x60000000
   esr: 0x56000080  Address size fault
```

**Comment by dulmandakh** [comment] 2020-11-21 12:22
Sorry, closing this because we don't have reproducible demo code, thus we cannot investigate the issue. Will re-open once we have. Thanks

**Closed by dulmandakh** 2020-11-21 12:22 UTC
Labels: Needs: Triage :mag:, Platform: iOS

**Comment by madhudskumar** [comment] 2020-11-23 06:28
https://drive.google.com/file/d/1le9LaEAD8nODxK0XN0st5UIzqq_dJ3i-/view?usp=sharing

this is the packaged app.

steps to get there;

1. npx react-native init testprod --template react-native-template-typescript
2. open testprod.xcworkspace
3. archive
4. export the ipa
5. run it reald revice (or use browserstack)

there was one bug for linking on the release chain . fixed by following here https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios

I confirm there was no other changes in the code /. any new code was added .

can we please look into this. ?

**Comment by dulmandakh** [comment] 2020-11-23 13:10
Do you mean that typescript template is crashing? Are you sure that you made no change?

**Comment by madhudskumar** [comment] 2020-11-23 13:15
the app is running fine on simulators, for ios. its only when packaged with `arm64 arm7` arch. it is crashing when running on a real device.

**Comment by madhudskumar** [comment] 2020-11-29 16:34
hey any update on this ? @dulmandakh

**Comment by madhudskumar** [comment] 2020-11-30 07:15
moved to #30500

**Comment by faridsaud** [comment] 2021-04-16 20:54
Same issue here
