### ISSUE TITLE
[arm64-v8a] Crash. UnsatisfiedLinkError in libc++_shared.so on Android when 3rd party lib

### ISSUE THREAD

**Issue by promanowicz** [facebook/react-native#33191] opened 2022-02-27 10:17 UTC
### Description

Crash can be observed on arm64 device (Pixel 3a, physical and simulator) when 
RN 0.67.2 is used with 3rd pary library that uses libc++_shared.so.
There is strong suspicion that this happens due to different versions of NDK used with both libs:
23.1.7779620 vs 21.4.7075529
Because project wants cinterop libc++.so and RN libc++.so, 
gradle config includes: 
```
packagingOptions {
  pickFirst("**/libc++_shared.so")
}
```
This results in UnsatisfiedLinkError:

```
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__emutls_get_address" referenced by "/data/app/~~1OdRcdrRGBvzrkIJ8Ak36g==/com.....androidApp-GxBncVvTbA9_hL_OloW8kg==/base.apk!/lib/arm64-v8a/librealmc.so"...
    at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
    at java.lang.Runtime.loadLibrary0(Runtime.java:998)
    at java.lang.System.loadLibrary(System.java:1656)
    at com.....compmulti.android.AndroidApplication.onCreate(AndroidApplication.kt:28)
    at com....Application.onCreate(CompanionApplication.kt:51)
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6725)
    at android.app.ActivityThread.access$1500(ActivityThread.java:247)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7839)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```
If I force usage local c++ lib, different crash happens
`A/libc: Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x7b2d028000 in tid 8424 (create_react_co), pid 8368 `

### Version

0.67.2

### Output of `npx react-native info`

```
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Memory: 125.50 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Watchman: 2022.02.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 28, 29, 30, 31, 32
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0
      System Images: android-32 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8139111
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.2 => 0.67.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

### Steps to reproduce

Run react-native project with realm-kotlin on arm64-v8a android device.

**Comment by cortinico** [comment] 2022-03-01 11:05
> There is strong suspicion that this happens due to different versions of NDK used with both libs:
> 23.1.7779620 vs 21.4.7075529
> Because project wants cinterop libc++.so and RN libc++.so,

That's most likely the root cause.

> Run react-native project with realm-kotlin on arm64-v8a android device.

Have you asked folks in realm-kotlin here https://github.com/realm/realm-kotlin
If they bundle a prebuilt, that's most likely an ABI incompatiblity.

**Comment by promanowicz** [comment] 2022-03-01 16:04
@cortinico Confirmed, realm is building libc++_shared library.
https://github.com/realm/realm-kotlin/issues/694#issuecomment-1055517542

**Comment by cortinico** [comment] 2022-03-01 17:34
I've followed up on the issue you linked. Also what's the reason you're not using the realm-js SDK?

**Comment by promanowicz** [comment] 2022-03-02 09:39
At first we have started using kotlin-multiplatform in addition to exisitng iOS and Android apps.
At some point we have added kotlin-realm but still with native UI's.
React is the latest framework that was included, where we already have some business logic implemented in kotlin.

Additionaly, it was easier to move from native Kotlin/Swift to kotlin-multiplatform.

**Comment by ilyagru** [comment] 2022-03-03 11:42
+1. Also having this issue, but I'm not using Realm in my project. Looking for the report to share here...

**Comment by cortinico** [comment] 2022-03-25 14:11
Closing as the upstream issue is also resolved in the upcomign realm SDK. Feel free to reopen if the issue persists

**Closed by cortinico** 2022-03-25 14:11 UTC
Labels: Platform: Android, API: Share

**Comment by ahmadbajwa8282** [comment] 2022-06-06 06:32
+1
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)
backtrace:
  #00  pc 000000000001c8cc  /vendor/lib64/libsrv_um.so (PVRSRVDevVarGet+4)
  #00  pc 00000000000e30dc  /vendor/lib64/egl/libGLESv2_mtk.so
  #00  pc 0000000000053a0c  /vendor/lib64/egl/libGLESv2_mtk.so
  #00  pc 0000000000051bc8  /vendor/lib64/egl/libGLESv2_mtk.so
  #00  pc 000000000002f0c0  /vendor/lib64/egl/libGLESv2_mtk.so
  #00  pc 0000000000033fb0  /vendor/lib64/egl/libGLESv2_mtk.so
  #00  pc 0000000000033dc8  /vendor/lib64/egl/libGLESv2_mtk.so (glFramebufferTexture2D+104)
  #00  pc 0000000000055330  /data/app/com.hmbl.live.wallpapers.wallpaper.screen.theme-Rnvra3bo8r5ie4jAvK1q2Q==/split_config.arm64_v8a.apk!lib/arm64-v8a/libCGE.so (offset 0x1000)
  #00  pc 000000000004ebe4  /data/app/com.hmbl.live.wallpapers.wallpaper.screen.theme-Rnvra3bo8r5ie4jAvK1q2Q==/split_config.arm64_v8a.apk!lib/arm64-v8a/libCGE.so (offset 0x1000)
  #00  pc 0000000000060dd0  /data/app/com.hmbl.live.wallpapers.wallpaper.screen.theme-Rnvra3bo8r5ie4jAvK1q2Q==/split_config.arm64_v8a.apk!lib/arm64-v8a/libCGE.so (offset 0x1000)
  #00  pc 0000000000021544  /data/app/com.hmbl.live.wallpapers.wallpaper.screen.theme-Rnvra3bo8r5ie4jAvK1q2Q==/oat/arm64/base.odex (offset 0x21000)
