### ISSUE TITLE
NullPointerException when showing Android Modal

### ISSUE THREAD

**Issue by idris** [facebook/react-native#10795] opened 2016-11-07 20:25 UTC
### Description
We are getting a NullPointerException _sometimes_ upon trying to show a modal (see "Reproduction" section for details).

Stack Trace:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.facebook.react.uimanager.ReactShadowNode.setStyleWidth(float)' on a null object reference
	at com.facebook.react.uimanager.UIImplementation.updateNodeSize(UIImplementation.java:151)
	at com.facebook.react.uimanager.UIManagerModule.updateNodeSize(UIManagerModule.java:213)
	at com.facebook.react.views.modal.ReactModalHostView$DialogRootViewGroup$1.run(ReactModalHostView.java:301)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
	at android.os.Looper.loop(Looper.java:148)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
	at java.lang.Thread.run(Thread.java:818)
```

It sounds like this commit may be related, and may have fixed a similar issue: https://github.com/facebook/react-native/commit/922cd6ddfc2414d274a53a5a6259ad50cb232782
From that commit message:
> In some cases, the size of the content view changes before we add views to the
Modal. That means that the size of that view will not be set through the
`onSizeChanged` method. This can result in some apps apparently freezing,
since the dialog is created, but there are no actual views in it.

The part about "dialog is created, but there are no actual views in it" makes me feel it's related, because the NullPointerException happens here: https://github.com/facebook/react-native/blob/v0.36.0/ReactAndroid/src/main/java/com/facebook/react/views/modal/ReactModalHostView.java#L301-L302
So apparently `getChildAt(0).getId()` returns an ID that is unavailable by the time `setStyleWidth` is called.

### Reproduction

Unfortunately, it's a tough case to reproduce.  Even in our app it only happens about half the time.  We have one modal show first, and when the user clicks "OK" on that one, we show another "saving" modal, then when saving is complete we remove the modal.  It seems in between the user clicking "OK" and the "saving" modal displaying, we get a crash (about half the time).

### Additional Information

* React Native version: v0.36.0
* Platform: Android (tested on Nexus 5)
* Operating System: Android (Tried genymotion, but can only reproduce on a real device)

**Comment by charpeni** [comment] 2016-11-09 00:32
@facebook-github-bot label Android

**Comment by akzhou** [comment] 2016-11-09 15:47
I have the save question  on React Native version: v0.36.1

**Comment by kruczy** [comment] 2016-11-23 14:29
Hi,
 I have a similar issue that happens only when closing a modal (but not always), the error is in a different place in the code but it seems it is related: https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIImplementation.java#L151

hope this helps with solving the problem

**Comment by idris** [comment] 2016-11-29 18:22
Looks like @Proberts has a way to reproduce this: https://github.com/facebook/react-native/issues/10845#issuecomment-263537217

**Comment by fermuch** [comment] 2016-12-05 15:52
Same issue in RN 0.39.0. It happens randomly, but seems to be triggered by `onLayout` on the root component.

**Comment by grahamtallen** [comment] 2017-01-31 22:05
+1

**Comment by mbresnan1701** [comment] 2017-02-02 22:04
I only experience this crash on QA builds for some reason. But yeah, this still needs a solution(v0.39).

**Comment by mbresnan1701** [comment] 2017-02-11 00:57
My company needed a fix for this, as this crash was happening in production and it was vital we fixed it, but we were unable to come up with a good method of testing and fixing this issue. We managed to "fix" the issue by ripping out the Modal component from our code. In our case, Modal was used to show a loading indicator.

We originally had this code:
https://gist.github.com/mbresnan1701/379d017d8179143446d4850948e1e351

In it's place, we used this:
https://gist.github.com/mbresnan1701/4e6357507218b79a509b0fe796cff84a

Few problems with this solution is that it wont cover native components(i.e. title bar), as it's limited to the react-native view. Also if the user changes orientation while this "Modal" is up, it wont rerender(so it looks funky), and so we had to add a listener to rerender this component whenever orientation changes. 

Despite these problems, we absolutely had to fix this issue so users didn't crash, so we ended up using our solution. 

Feel free to copy-pasta if it helps.

**Comment by JakeRawr** [comment] 2017-02-17 01:45
+1, This happens for me even if `visible = { false }`

**Comment by butchmarshall** [comment] 2017-04-03 00:15
I get this crash randomly while using [react-native-loading-spinner-overlay](https://www.npmjs.com/package/react-native-loading-spinner-overlay)

**Comment by gsaandy** [comment] 2017-04-06 13:02
any updates on this?

**Comment by fermuch** [comment] 2017-04-06 15:22
@gsaandy after using a custom version compiled from master, the problem is gone for me.
I'm using `react-native-router-flux` for navigation.

**Comment by kelvinaliyanto** [comment] 2017-04-25 17:56
Any workaround for this now?

**Comment by jlo1** [comment] 2017-05-10 01:06
Seems fixed in latest 0.44.0 release (https://github.com/facebook/react-native/commit/5873a228f41bca763c35c470375a9f3cb36f80ab)

**Comment by edmofro** [comment] 2017-07-11 05:53
Pretty sure this issue can be closed - it's essentially a duplicate of the now fixed #10845

**Comment by charpeni** [comment] 2017-07-11 14:00
Then let's close this, if it happens again please open a new issue.

**Comment by charpeni** [comment] 2017-07-11 14:00
@facebook-github-bot close

**Comment by charpeni** [comment] 2017-07-12 18:11
@facebook-github-bot close

**Closed by charpeni** 2017-07-12 18:11 UTC
Labels: Android, Ran Commands

**Comment by weimengxi** [comment] 2017-07-20 10:02
@JakeRawr I've met this problem, too. `visible = { false } ` leads to crash in ios .
