### ISSUE TITLE
when i init a react-native project by using react-native init firstRnProject,i meet the following questions

### ISSUE THREAD

**Issue by blachworld** [facebook/react-native#15525] opened 2017-08-17 04:36 UTC
An unexpected error occurred: "http://registry.npm.taobao.org/babel-polyfill/download/babel-polyfill-6.26.0.tgz: Request failed \"502 Bad Gateway\"".

**Comment by blachworld** [comment] 2017-08-17 04:37
my react-native version is 0.47, node-version is 7.1, yarn version is v0.27.5

**Comment by hramos** [comment] 2017-08-17 05:13
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-08-17 05:13 UTC
