### ISSUE TITLE
[Bundle] "Allocation failed - process out of memory" in OSX making bundle

### ISSUE THREAD

**Issue by Takeno** [facebook/react-native#5196] opened 2016-01-08 13:08 UTC
I get an error archiving iOS app, while react-native-xcode.sh is running.

I have found the command which throw the error:
```
$ react-native bundle --entry-file index.ios.js --platform ios --dev false --bundle-output /Users/matteo/Library/Developer/Xcode/DerivedData/XXX-giksyrhhnbtkzvexaglpgclnuxxc/Build/Intermediates/ArchiveIntermediates/XXX/BuildProductsPath/Release-iphoneos/XXX.app/main.jsbundle --assets-dest /Users/matteo/Library/Developer/Xcode/DerivedData/XXX-giksyrhhnbtkzvexaglpgclnuxxc/Build/Intermediates/ArchiveIntermediates/XXX/BuildProductsPath/Release-iphoneos/XXX.app --verbose
```

Output:
```
  ReactNativePackager:SocketClient connecting to +0ms /var/folders/vf/51_gzv_93q5dv1zcs0m_8vkr0000gn/T/react-packager-5aca564e0b1dba4dc62417c52f2469f6
bundle: Created ReactPackager
  ReactNativePackager:SocketClient got message with type +859ms result
bundle: start
[14:01:19] <START> Whole Program Optimisations

<--- Last few GCs --->

   15879 ms: Scavenge 1398.4 (1455.5) -> 1398.4 (1455.5) MB, 0.8 / 0 ms (+ 2.0 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
   16864 ms: Mark-sweep 1398.4 (1455.5) -> 1396.3 (1455.5) MB, 984.7 / 0 ms (+ 3.5 ms in 2 steps since start of marking, biggest step 2.0 ms) [last resort gc].
   17817 ms: Mark-sweep 1396.3 (1455.5) -> 1398.2 (1455.5) MB, 953.2 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1ab707fe3ac1 <JS Object>
    1: get [/Users/matteo/mobile-workspace/XXX/node_modules/babel-traverse/lib/path/index.js:~75] [pc=0x26d5471a2791] (this=0x618f966b51 <JS Function NodePath (SharedFunctionInfo 0x36f8c2bcf7d1)>,_ref2=0x3de3985e7ca9 <an Object with map 0x2b945634e609>)
    2: node [/Users/matteo/mobile-workspace/XXX/node_modules/babel-traverse/lib/index.js:~119] [pc=0x26d54711edf4] (this=0x618f967bf1 <JS F...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Abort trap: 6
```

My versions:
```
$ react-native -v
react-native-cli: 0.1.8
react-native: 0.17.0

$ node -v
v5.4.0
```

With DEV=true there are no problems.

**Comment by Takeno** [comment] 2016-01-08 13:16
Just to help someone else, increasing the node memory space-size I'm able to make the bundle:

```
node --max-old-space-size=4096 /Users/matteo/.nvm/versions/node/v5.4.0/bin/react-native bundle --entry-file index.ios.js --platform ios --dev false --bundle-output /Users/matteo/Library/Developer/Xcode/DerivedData/XXX-giksyrhhnbtkzvexaglpgclnuxxc/Build/Intermediates/ArchiveIntermediates/XXX/BuildProductsPath/Release-iphoneos/XXX.app/main.jsbundle --assets-dest /Users/matteo/Library/Developer/Xcode/DerivedData/XXX-giksyrhhnbtkzvexaglpgclnuxxc/Build/Intermediates/ArchiveIntermediates/XXX/BuildProductsPath/Release-iphoneos/XXX.app --verbose
  ReactNativePackager:SocketClient connecting to +0ms /var/folders/vf/51_gzv_93q5dv1zcs0m_8vkr0000gn/T/react-packager-5aca564e0b1dba4dc62417c52f2469f6
bundle: Created ReactPackager
  ReactNativePackager:SocketClient got message with type +3s result
bundle: start
[14:11:36] <START> Whole Program Optimisations
[14:13:38] <END>   Whole Program Optimisations (121866ms)
[14:13:38] <START> minify
[14:14:22] <END>   minify (44438ms)
bundle: finish
bundle: Writing bundle output to: /Users/matteo/Library/Developer/Xcode/DerivedData/XXX-giksyrhhnbtkzvexaglpgclnuxxc/Build/Intermediates/ArchiveIntermediates/XXX/BuildProductsPath/Release-iphoneos/XXX.app/main.jsbundle
bundle: Closing client
  ReactNativePackager:SocketClient closing connection +3m
bundle: Done writing bundle output
```

**Comment by Bhullnatik** [comment] 2016-02-25 19:07
I just got the same error trying to deploy for Android.

```

<--- Last few GCs --->

  104954 ms: Scavenge 1391.5 (1457.3) -> 1391.5 (1457.3) MB, 0.9 / 0 ms (+ 2.0 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
  106385 ms: Mark-sweep 1391.5 (1457.3) -> 1391.4 (1457.3) MB, 1431.3 / 0 ms (+ 2.6 ms in 2 steps since start of marking, biggest step 2.0 ms) [last resort gc].
  107967 ms: Mark-sweep 1391.4 (1457.3) -> 1391.4 (1457.3) MB, 1582.1 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0xb316fee3ac1 <JS Object>
    1: print [0xb316fe04189 <undefined>:~4086] [pc=0x8efff9f9933] (this=0x4f85dbde139 <an AST_SymbolDefun with map 0x269d0e0e4a1>,stream=0x22b3a20de9e9 <an Object with map 0x269d0e0daa9>,force_parens=0xb316fe04189 <undefined>)
    2: arguments adaptor frame: 1->2
    3: _do_print [0xb316fe04189 <undefined>:~4455] [pc=0x8efff9d8762] (this=0x4f85dbddde9 <an AST_Defun with map 0x269d0e0e8c1>,output...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```

```
$ react-native -v
react-native-cli: 0.1.10
react-native: 0.20.0

$ node -v
v5.7.0
```

Didn't change anything major to the workflow since last release.

@Takeno I was able to use your solution to generate my apk anyway, thanks!

**Comment by abhinavsingi** [comment] 2016-02-27 13:49
@Takeno @Bhullnatik - you can try this
[Increase node memory](http://stackoverflow.com/questions/34727743/getting-gc-process-out-of-memory-error-while-bundling-via-webpack/34743377#34743377)

**Comment by Takeno** [comment] 2016-02-29 09:25
@abhinavsingi - Yeah, it was I did to run with more memory. But I don't know if it is caused by a memory leak of packager or too many dependecies to be bundled. e.g. my **not minified** bundle ios is about 40MB.

**Comment by pesterhazy** [comment] 2016-03-09 10:58
Seeing a similar problem when running the packager (0.19) on OSX (machine has 4GB). The command line is:

```
"node" "--max-old-space-size=4096" "/Users/macmini/.jenkins/jobs/integration/workspace/ios/app/node_modules/react-native/local-cli/cli.js" "bundle" "--platform" "ios" "--dev" "true" "--entry-file" "nested/temp/6bae1978-4954-41ec-9b84-0cac4d865cec.js" "--bundle-output" "/Users/macmini/.boot/cache/tmp/Users/macmini/.jenkins/jobs/integration/workspace/ios/1r3o/ho4uid/main.jsbundle" "--assets-dest" "/Users/macmini/.boot/cache/tmp/Users/macmini/.jenkins/jobs/integration/workspace/ios/1r3o/ho4uid"
```

The GC log says:

```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

<--- Last few GCs --->

  233312 ms: Scavenge 1398.1 (1456.7) -> 1398.1 (1456.7) MB, 0.7 / 0 ms (+ 2.9 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
  236765 ms: Mark-sweep 1398.1 (1456.7) -> 1398.1 (1456.7) MB, 3452.5 / 0 ms (+ 4.4 ms in 2 steps since start of marking, biggest step 2.9 ms) [last resort gc].
  240197 ms: Mark-sweep 1398.1 (1456.7) -> 1398.1 (1456.7) MB, 3432.6 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x24e91eae3ac1 <JS Object>
    2: FunctionExpression [/Users/macmini/.jenkins/jobs/integration/workspace/ios/app/node_modules/babel-generator/lib/generators/methods.js:~64] [pc=0xfc19ce75266] (this=0x33f29aca7431 <a CodeGenerator with map 0x3bdc545c4cc9>,node=0x2575f22c3801 <a Node with map 0x3bdc545bc299>)
    3: arguments adaptor frame: 2->1
    4: _print [/Users/macmini/.jenkins/jobs/integration/workspace/ios/app/node...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory```

**Comment by abhinavsingi** [comment] 2016-03-09 13:14
@pesterhazy Did you try with `"--max-old-space-size=8192"`?

**Comment by pesterhazy** [comment] 2016-03-09 14:11
@abhinavsingi, I did, but it did not have any effect on the memory consumption -- it maxed out at 1.4G (verified using `htop`).

Actually when the packager runs, there are multiple node processes running. `max-old-space-size` only applies to the parent process, but the worker processes don't inherit the command line argument (you can see that using `ps`). The code uses https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options, and I don't see a way to have the heap size propagate to the child processes.

**Comment by pianetarosso** [comment] 2016-03-09 19:15
@Bhullnatik how you succeed on android?

Could you share the command used? 

Until now I built the apk using _./gradlew assembleRelease_ but it doesn't work anymore...

**Comment by Bhullnatik** [comment] 2016-03-09 19:23
@pianetarosso I modified the command in `react.gradle` from 
```groovy
commandLine "react-native", "bundle", "--platform", "android", "--dev", "${devEnabled}",
"--entry-file", entryFile, "--bundle-output", jsBundleFile, "--assets-dest", resourcesDir
```
to 
```groovy
commandLine "usr/local/bin/node", "--max-old-space-size=4096", "/usr/local/bin/react-native", "bundle", "--platform", "android", "--dev", "${devEnabled}",
"--entry-file", entryFile, "--bundle-output", jsBundleFile, "--assets-dest", resourcesDir
```

The paths might be relative to your system configuration.

**Comment by pianetarosso** [comment] 2016-03-09 19:35
It worked!!! Thank you

**Comment by jsierles** [comment] 2016-03-20 21:47
@Takeno Thanks for digging into this issue! Maybe you'd be interested to submit a PR to add a memory limit option, or at least to document the issue in the [Troubleshooting section](https://facebook.github.io/react-native/docs/troubleshooting.html)?

**Comment by jasonwiener** [comment] 2016-04-13 05:00
@pianetarosso & @Bhullnatik thanks! i had to do one additional step.  i modified the /node_modules/react-native/packager/packager.sh from 

`node "$THIS_DIR/../local-cli/cli.js" start "$@"`

to

`node --max_old_space_size=4096 "$THIS_DIR/../local-cli/cli.js" start "$@"`

**Comment by pianetarosso** [comment] 2016-04-14 18:31
We had the same problem building for IOS, we solved it changing the file

`/node_modules/react-native/packager/react-native-xcode.sh`

like this:

`$NODE_BINARY "--max-old-space-size=4096" "$REACT_NATIVE_DIR/local-cli/cli.js" bundle \`

**Comment by gnl** [comment] 2016-04-14 19:48
Increasing the memory limit in react-native-xcode.sh works fine on RN 0.22.2, but it has no effect on 0.23.1.

**Comment by gnl** [comment] 2016-04-24 21:50
Build still failing on 0.24.1:

```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

<--- Last few GCs --->

  132645 ms: Scavenge 1398.4 (1456.6) -> 1398.4 (1456.6) MB, 1.9 / 0 ms (+ 29.6 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
  135194 ms: Mark-sweep 1398.4 (1456.6) -> 1398.4 (1456.6) MB, 2548.8 / 0 ms (+ 46.9 ms in 7 steps since start of marking, biggest step 29.6 ms) [last resort gc].
  138043 ms: Mark-sweep 1398.4 (1456.6) -> 1398.3 (1456.6) MB, 2849.2 / 0 ms [last resort gc].

```

**Comment by mroswald** [comment] 2016-05-09 12:05
In general, how do we fix this? Adding a fix value in the code seems not good. But calculating a possible value for memory size could be reasonable? Sth like:

`if ram <= 4GB, use 2,5GB`
`if ram <= 8GB, use 4GB`
`else use 8GB`

Another way could be to read if there is an environment var set and use it (which would be my favourite).

**Comment by johnwonder** [comment] 2016-06-29 14:00
it  still exists on windows8.1,how to resolve it?

**Comment by mroswald** [comment] 2016-06-29 14:16
@johnwonder call the bundling with `node --max_old_space_size=4096 node_modules/react-native/local-cli/cli.js bundle ...`

**Comment by seantempesta** [comment] 2016-08-04 13:18
Okay, this is a dirty dirty hack, but after staring at the internals of the packager for several hours (and not understanding it) I've found a way to get the packager to complete a bundle.  

edit `node_modules/babel-traverse/lib/index.js` and add this to the top of the file:
```
function scheduleGc() {
  if (!global.gc) {
    console.log('Garbage collection is not exposed');
    return;
  }
var timeoutId = setTimeout(function(){
    global.gc();
    console.log('Manual gc', process.memoryUsage());
    scheduleGc();
  },30000);
timeoutId.unref();
}
// call this in the startup script of your app (once per process)
scheduleGc();
```

Now you need to call the bundler like this (to enable garbage collection):

`node --expose-gc --max_old_space_size=4096 "./node_modules/react-native/local-cli/cli.js" bundle  --entry-file ./index.ios.js   --platform ios   --dev false   --reset-cache true   --bundle-output "MyApp.app/main.jsbundle" --assets-dest "MyApp.app"`

NOTE:  I'm not sure what the values are supposed to be for `--bundle-output` and -assets-dest`, but the key thing to note is the **--expose-gc** flag which allows this to work.

So, what is this doing?  For me at least, the bundler was running out of memory during babel transformation (or ast building?).  Putting that code at the top of that file runs garbage collection every 30 seconds (might have to tune it depending on your machine).  It seems to work well enough to stop V8 from running out of heap memory.   But yes, it's a dirty dirty hack.

**Comment by levitanong** [comment] 2016-10-16 07:00
I too am having this issue. I seem to be having the same issue as @pesterhazy. I've brought up the memory allocation to 8192, but still no dice. 

```
<--- Last few GCs --->

  172830 ms: Mark-sweep 1357.7 (1434.2) -> 1357.7 (1434.2) MB, 2484.1 / 0.0 ms [allocation failure] [GC in old space requested].
  175206 ms: Mark-sweep 1357.7 (1434.2) -> 1357.7 (1434.2) MB, 2376.1 / 0.0 ms [allocation failure] [GC in old space requested].
  177622 ms: Mark-sweep 1357.7 (1434.2) -> 1361.1 (1418.2) MB, 2415.8 / 0.0 ms [last resort gc].
  180068 ms: Mark-sweep 1361.1 (1418.2) -> 1364.5 (1418.2) MB, 2446.2 / 0.0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x32b438ecfb51 <JS Object>
    1: popContext [/Users/levi/repos/load-app/node_modules/babel-traverse/lib/path/context.js:~222] [pc=0x33f44087ba3] (this=0xad6726c2a11 <a NodePath with map 0x39e99bd95a91>)
    2: visitQueue [/Users/levi/repos/load-app/node_modules/babel-traverse/lib/context.js:~114] [pc=0x33f440a0b38] (this=0x3f92f83ffb99 <a TraversalContext with map 0x39e99bd95c49>,queue=0x391f7874e479 <JS Array[1]>)
    ...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

**Comment by seantempesta** [comment] 2016-10-17 02:17
@levitanong: Did you try my hack?  Read the comment above yours.

**Comment by levitanong** [comment] 2016-10-17 05:23
@seantempesta I'm getting `../node_modules/react-native/local-cli/cli.js: Permission denied` even with sudo T_T

**Comment by seantempesta** [comment] 2016-10-17 15:35
Yeah, not sure what's going on there.  I just put the --expose-gc flag in the react-native-xcode.sh file.

node_modules/react-native/packager/react-native-xcode.sh:
```
$NODE_BINARY \
  --expose-gc \
  --max_old_space_size=4096 \
"$REACT_NATIVE_DIR/local-cli/cli.js" bundle \
  --entry-file index.ios.js \
  --platform ios \
  --dev $DEV \
  --reset-cache true \
  --bundle-output "$DEST/main.jsbundle" \
  --assets-dest "$DEST"
```

**Comment by levitanong** [comment] 2016-10-20 15:42
@seantempesta I got the gc to work! While I couldn't get your react-native-xcode.sh snippet to work, it did make me look at packager.sh, and that's where I placed --expose-gc and max_old_space_size. Thanks, man!

**Comment by lacker** [comment] 2016-10-25 01:30
This issue now seems like a set of related problems rather than a single bug, so I think it has lived its useful lifetime and I'm going to close it. People who do have similar problems in the future, please feel free to open a new issue, but also please provide enough information to reproduce the specific problem.

**Closed by lacker** 2016-10-25 01:30 UTC
Labels: Documentation, Packager, Triage - In Progress

**Comment by seantempesta** [comment] 2016-10-25 01:54
I'm pretty sure it's all the same bug.  I've traced the problem to the babel-traverse library, but haven't been able to figure out what part is blowing the heap. 

`node_modules/babel-traverse/lib/index.js`

I'm using ClojureScript with react-native which compiles all of the javascript down to a single file (index.[ios|android].js) using the Google closure compiler.  The package manager worked fine for a while until the file size grew too large.  Increasing the node memory fixes the problem for a while, but the only stable long term solution was to manually initiate garbage collection during the parsing.  As far as I can tell, the packager is just doing this to get a set of require's for final packaging?

I don't know how to reproduce it with pure javascript.

**Comment by lacker** [comment] 2016-10-25 05:00
It seems like it's all the same symptom - the bundler is running out of memory. I dunno if it's the same problem, though, a bunch of folks are just chiming in saying yeah I also had an out-of-memory. It seems un-reproducible though. Especially if it only happens in conjunction with some other build tools. If it were possible to reproduce this in a simple pure javascript project then it seems like we could make progress. Even if perhaps it were a single enormous repetitive file. I think that would be worth a new issue but as is it seems impossible to reproduce and therefore hard to have the issue go somewhere.

**Comment by IanVS** [comment] 2016-10-26 19:18
I'm having this problem right now in CircleCI.  The box that the container runs in has plenty of memory, but CircleCI limits the container to a max of 4GB.  I can limit the number of workers with `REACT_NATIVE_MAX_WORKERS`, but then each worker still ends up using too much memory.  It would be great if there were an environment variable that I could set which would limit the total amount of memory consumed by the workers.

**Comment by levitanong** [comment] 2016-11-08 15:45
@seantempesta Just an update: with "babel-plugin-transform-es2015-block-scoping": "6.15.0" and latest re-natal + react-native, I no longer need to cast your babel-traverse black magic. 😜 Only `--expose-gc --max_old_space_size=4096` is necessary for me.

**Comment by seantempesta** [comment] 2016-11-09 00:54
Oh yeah?  Sweet!  I'll check it out.
