### ISSUE TITLE
NativeRunnable.java: Failed to create String from JSON

### ISSUE THREAD

**Issue by npomfret** [facebook/react-native#9117] opened 2016-07-31 11:12 UTC
Got the following error in a production deployment which crashed my app.  Anyone know what it means?

RN 0.29.2
Android 6

```
Fatal Exception: java.lang.RuntimeException: Failed to create String from JSON
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:234)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:193)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by npomfret** [comment] 2016-08-17 08:28
Same on android 5, RN 0.30

```
E/unknown:React: Exception in native call from JS
                                                             com.facebook.react.devsupport.JSException: Failed to create String from JSON
                                                                 at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                 at android.os.Handler.handleCallback(Handler.java:815)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                 at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                 at android.os.Looper.loop(Looper.java:194)
                                                                 at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                 at java.lang.Thread.run(Thread.java:818)
                                                              Caused by: com.facebook.jni.CppException: Failed to create String from JSON
                                                                 at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                 at android.os.Handler.handleCallback(Handler.java:815) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:104) 
                                                                 at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                                                                 at android.os.Looper.loop(Looper.java:194) 
                                                                 at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196) 
                                                                 at java.lang.Thread.run(Thread.java:818)
```

**Comment by GeoffreyPlitt** [comment] 2016-09-22 21:11
Same here

**Comment by GeoffreyPlitt** [comment] 2016-09-26 21:55
Maybe JSON.parse() is the culprit? Maybe the parsing happens in native-land?

**Comment by GeoffreyPlitt** [comment] 2016-10-04 00:32
Any ideas?

**Comment by leeight** [comment] 2016-10-05 11:54
Could you try it on the master branch? If you can reproduce it, you'll get the invalid JSON.

**Comment by GeoffreyPlitt** [comment] 2016-10-05 17:25
@leeight Thanks, but I don't understand your suggestions at all.

Master branch? What do you mean? We're not using a non-master branch, what indicated that to you?

Invalid JSON: No, the whole problem is we have no way of knowing what the invalid JSON is. I'm not sending any JSON anywhere, this is deep in the RN codebase, it's happening in NativeRunnable.run(). I would absolutely LOVE if I could see the offending JSON, because then I would not be 100% stuck with this error.

**Comment by leeight** [comment] 2016-10-06 00:33
@GeoffreyPlitt

This commit will print the invalid JSON If failed.
https://github.com/facebook/react-native/commit/9a7e4b4902ffc733faa0facf86e9ceacd9f3f6a9

**Comment by GeoffreyPlitt** [comment] 2016-10-06 00:51
@leeight Awesome, that helps, thanks!

**Comment by brentvatne** [comment] 2016-11-06 18:03
Closing this and moving discussion to #10756

**Closed by brentvatne** 2016-11-06 18:03 UTC
