### ISSUE TITLE
 Cannot run Project.afterEvaluate(Closure) when the project is already evaluated. (When upgrade 0.64.4)

### ISSUE THREAD

**Issue by AlpMehmet** [facebook/react-native#35376] opened 2022-11-17 13:36 UTC
### Description

Hey, I'm having some issues when upgrading from react-native v0.64.2 -> v0.64.4. Below is the error message I am getting when trying to create a build or running ./gradlew clean in the android directory. Any help?

1: Task failed with an exception.
-----------
* Where:
Script '~/node_modules/react-native/react.gradle' line: 360

* What went wrong:
A problem occurred evaluating script.
> Cannot run Project.afterEvaluate(Closure) when the project is already evaluated.

### Version

0.64.4

### Output of `npx react-native info`

System:
    OS: macOS 12.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 81.56 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.0.1 - ~/.nvm/versions/node/v19.0.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v19.0.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v19.0.1/bin/npm
    Watchman: 2022.11.14.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 29, 31, 33
      Build Tools: 28.0.3, 30.0.2, 30.0.3, 31.0.0
      System Images: android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.5 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.4 => 0.64.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

It started when upgrade from react-native v0.64.2 -> v0.64.4. 

### Snack, code example, screenshot, or link to a repository

![Screen Shot 2022-11-17 at 16 35 51](https://user-images.githubusercontent.com/66008246/202460474-c3a5d671-6427-4586-9889-6c1435d6c7cf.png)

**Comment by AlpMehmet** [comment] 2022-11-21 08:53
I fixed gradle issue but i keep getting the error.

**Comment by mlostekk** [comment] 2022-11-21 18:15
Any fix out there? Having the same issue, RN 0.64.4, and. trying to upgrade gradle to 7.4

**Comment by AlpMehmet** [comment] 2022-11-23 07:07
> Any fix out there? Having the same issue, RN 0.64.4, and. trying to upgrade gradle to 7.4

I tried different solutions but none of them worked.

**Comment by cortinico** [comment] 2022-11-23 15:32
Could you share a reproducer?
This is probably caused by a library you're importing as an empty `0.64.4` project builds fine.

Frankly your on a really old version of React Native, that it's quite of a challenge to help here. Have you considered upgrading to the latest versions?

**Comment by cortinico** [comment] 2022-11-25 12:33
> It was because there are some error codes in my build.gradle, after I removed it, the build worked.
> I used compileSdkVersion 31 & gradle 6.7 at the end.

Thanks for the follow up.
I'm going to close this as it's not a React Native issue itself

**Closed by cortinico** 2022-11-25 12:33 UTC
Labels: Needs: Triage :mag:

**Comment by DeepikaSharma5** [comment] 2022-12-04 15:43
Any solution to this? I am not even using OneSignal-Gradle-Plugin in my project.But getting this error when update the gradle version to 7.4

**Comment by AlpMehmet** [comment] 2022-12-08 19:53
i don't use either. I couldn't fix the problem so I downgraded my project back to 64.2 working with gradle 7.4.

**Comment by mcsony** [comment] 2022-12-15 07:24
I had same issue. I could fix it buy downgrading gradle from 7.2 to 6.9.

In android/gradle/wrapper/gradle-wrapper.properties change your  distributionUrl value to 
https\://services.gradle.org/distributions/gradle-6.9-all.zip

**Comment by cortinico** [comment] 2023-04-20 19:18
> When was the RN Gradle Plugin introduced? Is it possible to use from RN version 0.63?

No sorry. RNGP Requires 0.71.+

Hoewever, you should be fine wiht anything above 0.65+ as that `afterEvaluate` block is not needed anymore:
https://github.com/facebook/react-native/blob/2642fe185f9282ef6e39619617671068f9696008/react.gradle#L361-L373

As a rule of thumb, consider updating to newer versions. 0.63 is not supported anymore

**Comment by seanabraham** [comment] 2023-04-20 19:28
Gotcha, thank you for the heads up @cortinico!

**Comment by cvetkovskiDejan** [comment] 2023-05-10 18:15
I also had the same problem and many solutions were mentioned here, but they all led me to upgrade the gradle, which always led to the same error:
"Cannot run Project.afterEvaluate(Closure) when the project is already evaluated"
A solution that fixed the problem for me is to check the JDK version that android studio uses to build the project.
Go to Project Settings and for Mac set the JDK version that is installed on your Mac(--cask zulu11) when you set up the Android Environment.
**Be sure to have compatible Gradle version and Gradle plug-in version and compatible JDK
Close Android studio and open the project again and build.

**Comment by thuongtv-vn** [comment] 2023-05-12 06:24
Hi @cortinico 
I am facing the same issue when tried to add a library which is configurated gradle:
classpath 'com.android.tools.build:gradle:7.0.4'

I changed may gradle to that version too. And got this error, My react-native version currently is 0.63.5. In order to integrate with that library. I must upgrade react-native version right? is there any other solution?

Thanks.

**Comment by cortinico** [comment] 2023-05-15 10:31
> Hi @cortinico
> I am facing the same issue when tried to add a library which is configurated gradle:
> classpath 'com.android.tools.build:gradle:7.0.4'

Please refrain from commenting on already closed/answered issues with your specific problem and open a separate issue. Also we can't offer support among all the React Native versions so we're focusing only on the last 3 released stable.
