### ISSUE TITLE
[Android] java.lang.illegalstateException :closed

### ISSUE THREAD

**Issue by yqz0203** [facebook/react-native#17905] opened 2018-02-08 08:30 UTC
When exiting react-native activity, throw this error and app crashes. This only happen in some phone and not always happen.

![image](https://user-images.githubusercontent.com/8850879/35962511-ab29c334-0cec-11e8-8fda-29bb92c2f9b7.png)

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 7.7.1
  Yarn: 1.3.2
  npm: 5.4.2
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.0.0 => 16.0.0
  react-native: ^0.51.0 => 0.51.0

Phone model: motorola:XT1650-05:arm64-v8a.

**Comment by hramos** [comment] 2018-02-09 20:41
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue that meets the requirements set forth in the template. Thanks!

**Closed by hramos** 2018-02-09 20:41 UTC
Labels: Failed Commands
