### ISSUE TITLE
The injectedJavaScript props in webview executed before the page loading finished

### ISSUE THREAD

**Issue by falltodis** [facebook/react-native#6445] opened 2016-03-14 06:35 UTC
Hi 
  I am using a js lib called *echart* to render chart in React native by *webview*,The code is like 
![image](https://cloud.githubusercontent.com/assets/7006864/13736482/cab07a8a-e9ef-11e5-9d20-651edeaf26f1.png)

And the html is a file like 
![image](https://cloud.githubusercontent.com/assets/7006864/13736506/f9d2093c-e9ef-11e5-9758-ecce766101e2.png)

However ,the chart view is white and looks like below when the app started .
![image](https://cloud.githubusercontent.com/assets/7006864/13736561/75a1e730-e9f0-11e5-9c1a-36690ade20bf.png)

I got no errors or warnings . 

Then I refresh the app by **command+R** ,The chart come to my eyes correctly.

The echart need the page load completely (that means all style script lib ), so I thought injectedJavaScript executed before the page loading finished.

That may be a bug.

**Comment by grabbou** [comment] 2016-03-14 07:53
I am not sure if that's a bug. The behaviour is probably similar as if the script was injected into head section. If that's the case, you should:
```js
function main() {
   // your current code
}

window.onload = main;
```

More details here -> http://www.w3schools.com/jsref/event_onload.asp

**Comment by tomkur** [comment] 2016-03-15 10:32
I am also suffering from this. In my case I have three webviews on single screen and it is always the case that:
* random one of them has JS injected after window load
* the other two have JS injected before window load

The docs for `injectedJavaScript` say:

> Sets the JS to be injected when the webpage loads.

so I'd also treat it as a bug.

@grabbou I think your solution will not work if JS is injected after window load. So this workaround needs to check for that as well. And I guess we can't even use `jQuery.ready`, because the script might be injected before jQuery is loaded (unless the injected script loads it on its own, which would be even more ugly). So I guess sth like:
```html
<body onload="window.loaded = true">
```
and:
```js
function main() {
   // your current code
}
if (window.loaded) {
  main()
} else {
  window.onload = main
}
```

**Comment by falltodis** [comment] 2016-03-30 12:32
@grabbou  @tomkur   In my case, the [DomReady](https://github.com/ded/domready) help me .  I try `window.onload=function(){ // my code}` directly, but it did not work. I think @tomkur  is right and I will try. Thanks !

**Comment by charpeni** [comment] 2016-08-09 12:55
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/the-injectedjavascript-props-in-webview-executed-before-the-page-loading-finished

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix.**
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment] 2016-08-09 12:55
@facebook-github-bot label Icebox

**Comment by charpeni** [comment] 2016-08-09 12:55
@facebook-github-bot close

**Comment by facebook-github-bot-5** [comment] 2016-08-09 12:55
@charpeni tells me to close this issue. If you think it should still be opened let us know why.

**Closed by facebook-github-bot-5** 2016-08-09 12:55 UTC
Labels: Icebox, Ran Commands

**Comment by aniddan** [comment] 2016-12-31 15:46
So what is the expected behaviour? Can it be added to the docs?

**Comment by WolfieZero** [comment] 2017-10-09 16:14
Wondering if this should be opened again? I'm finding a difference in results when comparing dev environment to the test/release builds. (For context https://stackoverflow.com/questions/46648549/react-native-webview-javascript-issue-on-build)
