### ISSUE TITLE
[0.46] Packager fails: Unknown plugin "transform-runtime"

### ISSUE THREAD

**Issue by sjmueller** [facebook/react-native#14530] opened 2017-06-15 08:36 UTC
Create a fresh app with: `react-native init rn46 --version "0.46.0-rc.2"`, then `CMD+R` in Xcode which attempts to fire up the packager, but immediately bombs with:

```
ReferenceError: Unknown plugin "transform-runtime" specified in "/rn46/node_modules/regenerator-transform/package.json" at 0, attempted to resolve relative to "/rn46/node_modules/regenerator-transform" (While processing preset: "/rn46/node_modules/babel-preset-react-native/index.js")
    at /rn46/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (/rn46/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/rn46/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/rn46/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/rn46/node_modules/babel-register/lib/node.js:103:45)
    at loader (/rn46/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/rn46/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

Since it's a reference error, I add the dependency `npm i babel-plugin-transform-runtime --save-dev` and rerun, which now bombs with:

```
Error: Couldn't find preset "env" relative to directory "/rn46/node_modules/regenerator-transform" (While processing preset: "/rn46/node_modules/babel-preset-react-native/index.js")
    at /rn46/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/rn46/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/rn46/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/rn46/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/rn46/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/rn46/node_modules/babel-register/lib/node.js:103:45)
    at loader (/rn46/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/rn46/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
```

Okay, let's now try `npm i --save-dev babel-preset-env`, which bombs with:

```
Error: Options {"loose":true} passed to /rn46/node_modules/babel-preset-env/lib/index.js which does not accept options. (While processing preset: "/rn46/node_modules/babel-preset-env/lib/index.js") (While processing preset: "/rn46/node_modules/babel-preset-env/lib/index.js") (While processing preset: "/rn46/node_modules/babel-preset-react-native/index.js")
    at /rn46/node_modules/babel-core/lib/transformation/file/options/option-manager.js:314:17
    at Array.map (native)
    at OptionManager.resolvePresets (/rn46/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/rn46/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/rn46/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/rn46/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/rn46/node_modules/babel-register/lib/node.js:103:45)
    at loader (/rn46/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/rn46/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
```

Something has definitely gone wrong down this rabbit hole. I noticed that @davidaurelio just upgraded `babel-preset-react-native` with commit bc22a4d, not sure if it's related but the update is already showing up in the initialized package.json:

```
	"devDependencies": {
		"babel-jest": "20.0.3",
		"babel-preset-react-native": "2.0.0",
		"jest": "20.0.4",
		"react-test-renderer": "16.0.0-alpha.12"
	}
```

**Comment by SudoPlz** [comment] 2017-06-20 19:12
I've got the exact same problem after upgrading to 0.46.0-rc.2, @sjmueller have you managed to sort that out?

**Comment by SudoPlz** [comment] 2017-06-20 19:20
Ok @sjmueller  `rm -rf .babelrc` solved that problem for me. No idea why.

**Comment by sjmueller** [comment] 2017-06-20 23:03
I haven't been able to sort it out yet. Tried a bunch of different things, but reverted and now stuck on `0.44` until this can be fixed.

**Comment by SudoPlz** [comment] 2017-06-20 23:20
Why don't you just delete the `.babelrc` file @sjmueller ?

**Comment by sjmueller** [comment] 2017-06-21 09:07
@SudoPlz because I'm using `transform-decorators-legacy` in my project, and I have decorators all over the place.

However just to check, I did try deleting my `.babelrc` just to see if it get passed the problem; it does, but unfortunately I just get slammed with `Unable to resolve module 'AccessibilityInfo'` that everyone is dealing with on #14209. Yes I tried:
```
rm -rf node_modules
rm -rf $TMPDIR/react-*
watchman watch-del-all
npm i
npm start -- --reset-cache
```
So gracious for what react-native and the core team, but honestly the amount of instability over the past few releases is pretty staggering -- 0.44.2+, 0.45+, and 0.46 rc all have their own set of problems. We really need the bug fixes in `FlatList` and `NativeAnimated` in the past two months, but can't get at them no matter how hard we try...

**Comment by grabbou** [comment] 2017-07-05 19:52
Just to put more context here:

Looks that the problem is React Packager trying to transpile `regenerator-transform` that has been already transpiled before publishing to `npm`. It still defines `transform-runtime` in its `package.json`, however it's under dev dependencies.

Another explanation of similar issue from another repository: https://github.com/tommikaikkonen/redux-orm/issues/24#issuecomment-228623502

**Comment by nprz** [comment] 2017-07-05 20:05
Currently getting this error as well...
```
ReferenceError: Unknown plugin "transform-runtime" specified in "/../node_modules/regenerator-transform/package.json"
```

on version `0.46.0` of react native

**Comment by joriswa** [comment] 2017-07-05 20:35
Also getting this error in 0.46.0

**Comment by nprz** [comment] 2017-07-05 20:56
@joriswa I just tried this and it works. Any insight as to why that fixed the issue or if that fix will cause any other issues down the road?

**Comment by joriswa** [comment] 2017-07-05 21:10
@nprz I got no idea whatsoever.

**Comment by cmdshepard** [comment] 2017-07-05 21:25
Also got this error after upgrading from 0.45 to 0.46

I resolved it by adding ```babel-plugin-transform-runtime``` & ```regenerator-transform``` to dev dependencies.

Then running ```./node_modules/react-native/scripts/packager.sh --reset-cache```

**Comment by raunaqss** [comment] 2017-07-06 08:51
Dong this `rm -rf .babelrc` resolved the issue for me as well. However, I'm concerned whether this will create more problems ahead?

**Comment by JimmyDaddy** [comment] 2017-07-06 08:54
I deleted `.babelrc`, then I encountered this problem #14209.

**Comment by zamotany** [comment] 2017-07-06 12:04
As a quick workaround, you can use [haul](https://github.com/callstack-io/haul) which works just fine.

**Comment by chilijung** [comment] 2017-07-06 13:55
deleted `.babelrc` also works for me. But I am also using babel `transform-decorators-legacy` plugin, did anyone know how could I use decorators without `.babelrc` settings? thanks.

**Comment by otoinsa** [comment] 2017-07-06 14:11
The same issue here, wanted to start a new project :(

**Comment by jeanlauliac** [comment] 2017-07-06 14:46
I noticed doing `(cd node_modules/react-native && node "./local-cli/cli.js" start)` repros the error, but doing `node node_modules/react-native/local-cli/cli.js start` shows no error and packager starts seemingly correctly. I didn't expect the working directory to have effect, something is anormal.

**Comment by thechee514** [comment] 2017-07-06 15:17
rm -rf .babelrc works, but when I try to run npm install --save redux react-redux in the project directory it causes this error: 

<img width="373" alt="screenshot 2017-07-06 11 16 31" src="https://user-images.githubusercontent.com/20151633/27918321-938ba9be-623c-11e7-9544-70e9b36b4d7e.png">

I'm assuming this is related to the problem w/ upgrading from 0.45 -> 0.46?

**Comment by jeanlauliac** [comment] 2017-07-06 16:36
I found a solution. This is due to what I think is a kinda-bug in Babel, but I have a workaround anyway. Sending a PR soon.

**Comment by cmdshepard** [comment] 2017-07-06 17:03
@thechee514 try resetting the packager cache
``` ./node_modules/react-native/scripts/packager.sh --reset-cache ```

**Comment by thechee514** [comment] 2017-07-06 17:24
@cmdshepard it gives me this error: 
no such file or directory: ./node_modules/react-native/scripts/packager.sh

Could this be because I have yarnpkg installed? So instead of entering: _npm install --save redux react-redux_ I should enter _yarn add redux_?

**Comment by cmdshepard** [comment] 2017-07-06 17:29
@thechee514 what version of react-native are you using?

**Comment by thechee514** [comment] 2017-07-06 17:32
@cmdshepard 0.46

**Comment by cmdshepard** [comment] 2017-07-06 17:35
@thechee514 try ```/Users/thechee514/Documents/workspace/test/node_modules/react-native/scripts/packager.sh --reset-cache```

**Comment by dioxide** [comment] 2017-07-06 17:36
downgrade babel-preset-react-native 2.1.0  to 2.0.0  is working fine in my case.

**Comment by thechee514** [comment] 2017-07-06 17:42
@cmdshepard I'm still getting the same error, here is the output after attempting to install redux: 
<img width="693" alt="screenshot 2017-07-06 13 41 34" src="https://user-images.githubusercontent.com/20151633/27924912-e79b0176-6250-11e7-8bcc-cf6d8f94c22d.png">

**Comment by cmdshepard** [comment] 2017-07-06 17:49
@thechee514 You're using react-native 0.45.1 - On this version, the packager is located in a different directory. Try running ```./node_modules/react-native/packager/react-native-xcode.sh``` from your project directory.

**Comment by thechee514** [comment] 2017-07-06 18:24
@cmdshepard, I'm getting a slightly different error now: _./node_modules/react-native/packager/react-native-xcode.sh must be invoked by Xcode_. I was actually running the code you sent earlier on 0.46.

**Comment by cmdshepard** [comment] 2017-07-06 19:05
@thechee514 yes. ```yarn add redux``` will do the same thing although if you initialized your project using yarn, you should stick to using yarn

**Comment by thechee514** [comment] 2017-07-06 19:08
Okay, I initialized the project with _react-native init project_, but I think it just uses yarn. Thanks for the help though @cmdshepard!

**Comment by jp928** [comment] 2017-07-06 21:38
I don't know why Facebook releases RN with bug which is so obvious. User reported this issue in rc and the bug still exists in the stable release. User even couldn't run a `react-native init `
and make it run straightforward. Similar packager issue was found in 0.45. So disappointing.

**Comment by jeanlauliac** [comment] 2017-07-07 13:57
So, the original problem "Unknown plugin "transform-runtime"" should now be fixed for v0.46 if you do a clean set-up, or if you upgrade the `metro-bundler` package to `0.7.8` in your repo/lockfile. I'll wait for confirmation this looks fixed for you folks before closing.

Creating a project from scratch with v0.46 worked for me, and the simulator loads the app correctly. For the other problems that may still happen, please open new issues :)

**Comment by cpojer** [comment] 2017-07-07 14:07
@jp928 Facebook doesn't manage open source releases for react-native, and we are probably not as actively involved as we should be. There are probably ways we can get better at this, but if this is a huge problem for you, it would be awesome if you could step up and help us avoid this class of problems in the future by helping us straighten out the release cycle.

**Comment by grabbou** [comment] 2017-07-07 16:12
@jp928 I am really sorry for the inconvenience. The "RC" bug report somewhat got lost in my inbox full of notifications. During manual testing that I usually do (as well as testing on the CI) the bug wasn't revealed. Sometimes not every single issue can be reproduced, but I think we did our best to fix it as soon as possible post the release.

**Comment by fungilation** [comment] 2017-07-07 16:57
So is a minor release fix coming? I'm working around with a manual `react-native start`, as `run-ios` result in the babel related packager errors. Other workarounds haven't worked for me on getting `run-ios` to work.

A side question is this: does this affect production releases, which wouldn't be tied to a running instance of the packager?

Repasting from the other issue, my package.json:
```
{
  "name": "<name>",
  "version": "0.0.1",
  "private": true,
  "eslintConfig": {
    "parserOptions": {
      "ecmaVersion": 6,
      "sourceType": "module",
      "ecmaFeatures": {
        "jsx": true,
        "experimentalObjectRestSpread": true
      }
    },
    "env": {
      "browser": true,
      "node": true
    },
    "plugins": [
      "react",
      "react-native"
    ],
    "rules": {
      "comma-dangle": [
        2,
        "always-multiline"
      ],
      "semi": [
        2,
        "never"
      ],
      "react-native/no-unused-styles": 2,
      "react-native/split-platform-components": 2
    }
  },
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "babel-plugin-idx": "^1.1.0",
    "bugsnag-react-native": "^2.2.3",
    "he": "^1.1.0",
    "lodash": "^4.17.2",
    "moment-timezone": "^0.5.10",
    "node-summary": "file:../node-summary/",
    "react": "16.0.0-alpha.12",
    "react-native": "0.46.0",
    "react-native-blur": "^3.1",
    "react-native-code-push": "3.0.1-beta",
    "react-native-firebase-analytics": "^3.0.0",
    "react-native-fit-image": "^1.4.8",
    "react-native-highlight-words": "^1.0.0",
    "react-native-keep-awake": "^2.0.4",
    "react-native-linear-gradient": "^2.0.0",
    "react-native-modalbox": "^1.3.8",
    "react-native-notification": "^2.0.0",
    "react-native-orientation": "file:../react-native-orientation-RN0.40/",
    "react-native-parallax-scroll-view": "^0.19.0",
    "react-native-safari-view": "^2.0.0",
    "react-native-status-bar-size": "^0.3.2",
    "react-native-swiper": "^1.5.4",
    "react-native-tooltip": "^5.0.0",
    "react-native-tts": "^1.3.0",
    "react-native-vector-icons": "^4.1.1",
    "react-native-webview-bridge": "file:../react-native-webview-bridge-RN0.40/",
    "react-redux": "^5.0.1",
    "realm": "^1.3.1",
    "redux": "^3.6.0",
    "redux-thunk": "^2.1.0"
  },
  "devDependencies": {
    "redux-logger": "^3.0.6"
  }
}
```

.babelrc:
```
{
  "presets": ["react-native"],
  "plugins": ["idx"]
}
```

**Comment by grabbou** [comment] 2017-07-07 17:10
0.46.1 is coming with a fix for different issue. Fix for this issue was
released to metro-bundler package directly. Metro-bundler is React Native
dependency "^0.7.6" meaning that you will get latest patch version every
time you do a fresh install. Since they released 0.7.8 with a fix, no React
Native update is required.

**Comment by fungilation** [comment] 2017-07-07 17:17
Can you clarify on "you will get latest patch version every time you do a fresh install"? Does it include running a `react-native-git-upgrade`?

**Comment by jeanlauliac** [comment] 2017-07-07 17:22
> Does it include running a react-native-git-upgrade?

I believe not. The action necessary depends on what package manager you use. For `yarn`, you have to upgrade the version of `metro-bundler` used in the lockfile. I believe `yarn upgrade` can be used for that. For `npm` 5, there should be a similar command to upgrade the locked dependencies, but I'm not familiar. For `npm` 4, deleting `node_modules` and running `npm install` again should do the deal, or upgrading the `shrinkwrap` file if any.

**Comment by fungilation** [comment] 2017-07-07 17:41
Confirm fixed with `yarn upgrade`, and yarn.lock file went from `version "0.7.6"` to `version "0.7.8"`, under the line `metro-bundler@^0.7.4:`. Thanks for the clarification!

A side issue I noticed now on React Packager's terminal below. Does this warrant a new issue?
```
Loading dependency graph...jest-haste-map: @providesModule naming collision:
  Duplicate module name: base64-js
  Paths: /Users/<user>/Documents/code/<project>/node_modules/react-native/node_modules/base64-js/package.json collides with /Users/<user>/Documents/code/<project>/node_modules/react-native/node_modules/simple-plist/node_modules/base64-js/package.json
```

**Comment by jeanlauliac** [comment] 2017-07-07 17:48
> A side issue I noticed now on React Packager's terminal below. Does this warrant a new issue?

I believe it's the issue reported in https://github.com/facebook/metro-bundler/issues/18. We have a fix that's been landed, not sure when we'll make it spread through `react-native` yet.

**Comment by fungilation** [comment] 2017-07-07 17:57
That's fine, shouldn't be a blocker as it's just a console warning.

**Comment by grabbou** [comment] 2017-07-11 22:14
Going to close it as it looks like the issue has been resolved :)

**Closed by grabbou** 2017-07-11 22:14 UTC
