### ISSUE TITLE
React-Native 0.70 Issue

### ISSUE THREAD

**Issue by hoadesign09** [facebook/react-native#34715] opened 2022-09-17 17:54 UTC
### Description

I have some problem when I upgrade RN version 0.70. Please help me fix it
<img width="594" alt="Screen Shot 2022-09-17 at 18 48 53" src="https://user-images.githubusercontent.com/93867067/190870036-30298070-df06-4446-9659-b919dab7143a.png">

### Version

0.70

### Output of `npx react-native info`

System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 30.64 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.13.2 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.3.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.0 => 0.70.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

no opinion

### Snack, code example, screenshot, or link to a repository

<img width="594" alt="Screen Shot 2022-09-17 at 18 48 53" src="https://user-images.githubusercontent.com/93867067/190870093-531cd84d-13b3-4e30-add4-e80d9e2bab3a.png">

**Comment by cortinico** [comment] 2022-09-17 18:29
Duplicate of https://github.com/facebook/react-native/issues/34706

**Closed by cortinico** 2022-09-17 18:29 UTC
Labels: Needs: Triage :mag:
