### ISSUE TITLE
after upgrade 0.66.4 -> 0.69.1 build was success but it crash when startup app...

### ISSUE THREAD

**Issue by rdtf1230** [facebook/react-native#34219] opened 2022-07-19 02:20 UTC
### New Version

0.69.1

### Old Version

0.66.4

### Build Target(s)

android

### Output of `react-native info`

System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
    Memory: 7.68 GB / 31.94 GB
  Binaries:
    Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.6.3 - ~\AppData\Roaming\npm\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-212.5712.43.2112.8609683
    Visual Studio: Not Found
  Languages:
    Java: 11.0.8 - /c/Program Files/Common Files/Oracle/Java/javapath/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.1 => 0.69.1
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

just startup app, it craash
by logcat here
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libjscexecutor.so caused by: couldn't find DSO to load: libjsc.so

i saw upgrade helper, and I have modified all the files

but i cant escape this crash...

I'm using productFlavors, could this be a problem?

flavorDimensions "mode"
    productFlavors {
        dev {
            dimension "mode"
        }
        prod {
            dimension "mode"
        }
        staging {
            dimension "mode"
        }
    }

**Comment by nschild** [comment] 2022-07-20 13:18
I've battled that error before on an earlier version of RN. I don't recall the solution right now, but google is your friend with this one. If it comes back to me, I'll post it.

**Comment by rdtf1230** [comment] 2022-07-20 19:09
> I've battled that error before on an earlier version of RN. I don't recall the solution right now, but google is your friend with this one. If it comes back to me, I'll post it.

oh plz help me ;)

**Comment by quicksilverr** [comment] 2022-07-21 13:44
@nschild Any recollection?

**Comment by lenoirzamboni** [comment] 2022-07-22 14:29
@rdtf1230 Maybe related to [this](https://github.com/facebook/react-native/issues/34231)?

**Comment by cortinico** [comment] 2022-07-22 14:48
> java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libjscexecutor.so caused by: couldn't find DSO to load: libjsc.so

This might be a valid bug, but in order to investigate this we need:
- To know what's the version of Gradle & Android Gradle Plugin you're using
- Someone to try out of a release build on a **fresh** React Native 0.69.1 project

If the latter is turning out to crash with the same stacktrace, that it's a bug that we need to fix.

**Comment by rdtf1230** [comment] 2022-07-23 12:19
> @rdtf1230아마도 이것과 관련 [이](https://github.com/facebook/react-native/issues/34231) 있습니까?
it didnt work for me....
logcat just said 'java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libjscexecutor.so caused by: couldn't find DSO to load: libjsc.so' X(

**Comment by rdtf1230** [comment] 2022-07-23 12:26
> > java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libjscexecutor.so caused by: couldn't find DSO to load: libjsc.so
> 
> This might be a valid bug, but in order to investigate this we need:
> 
> * To know what's the version of Gradle & Android Gradle Plugin you're using
> * Someone to try out of a release build on a **fresh** React Native 0.69.1 project
> 
> If the latter is turning out to crash with the same stacktrace, that it's a bug that we need to fix.

here is my gradle
android/build.gradle - classpath("com.android.tools.build:gradle:7.1.1")
android/gradle/wrapper/gradle-wrapper.properties - https\://services.gradle.org/distributions/gradle-7.3.3-all.zip

and it belongs to upgrade helper 0.66.4 -> 0.69.1
![image](https://user-images.githubusercontent.com/58766003/180604745-dab61eb7-198a-4579-b9e5-9ed86046737b.png)
![image](https://user-images.githubusercontent.com/58766003/180604755-e34cc194-0640-4b66-8e7a-8bbfab69b9d0.png)

**Comment by Limoer96** [comment] 2022-07-25 06:35
@rdtf1230 any solutions? This problem has been bothering me for a long time.

**Comment by rdtf1230** [comment] 2022-07-25 07:12
> @rdtf1230 any solutions? This problem has been bothering me for a long time.

Unfortunately so am I.... 
Probably I won't upgrade until I find a workaround

**Comment by codeOlam** [comment] 2022-07-26 13:44
I am also experiencing same problem. When I checked the crash log from the install apk on a physical device I go the follow report: 

```
FATAL EXCEPTION: create_react_context

java.lang.RuntimeException: Unable to load script. Make sure you're either running Metro (run 'npx react-native start') or that your bundle 'index.android.bundle' is packaged correctly for release. 
```

- react v18.0.0
- react-native v0.69.3
- com.android.tools.build:gradle:7.0.4

Is there any work around for this?

@cortinico

**Comment by codeOlam** [comment] 2022-07-26 23:00
> I am also experiencing same problem. When I checked the crash log from the installed apk on a physical device I got the following report:
> 
> ```
> FATAL EXCEPTION: create_react_context
> 
> java.lang.RuntimeException: Unable to load script. Make sure you're either running Metro (run 'npx react-native start') or that your bundle 'index.android.bundle' is packaged correctly for release. 
> ```
> 
>     * react v18.0.0
> 
>     * react-native v0.69.3
> 
>     * com.android.tools.build:gradle:7.0.4
> 
> 
> Is there any work around or fix for this?

So i was able to get my project to install and run properly on a physical device by doing the following;

- installed RN v0.69.2
- com.android.tools.build:gradle:7.1.1
- reset metro cache
- cleaned build
- then created a new signed apk release.

Hope this helps.

**Comment by rdtf1230** [comment] 2022-07-28 11:51
> > I am also experiencing same problem. When I checked the crash log from the installed apk on a physical device I got the following report:
> > ```
> > FATAL EXCEPTION: create_react_context
> > 
> > java.lang.RuntimeException: Unable to load script. Make sure you're either running Metro (run 'npx react-native start') or that your bundle 'index.android.bundle' is packaged correctly for release. 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > * react v18.0.0
> > 
> > * react-native v0.69.3
> > 
> > * com.android.tools.build:gradle:7.0.4
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is there any work around or fix for this?
> 
> So i was able to get my project to install and run properly on a physical device by doing the following;
> 
> * installed RN v0.69.2
> * com.android.tools.build:gradle:7.1.1
> * reset metro cache
> * cleaned build
> * then created a new signed apk release.
> 
> Hope this helps.

it didnt work for me ;) anyway thank you...

**Comment by codeOlam** [comment] 2022-07-28 12:28
Sorry about that, but are you updating the version of an exisiting RN project or starting a new one ? @rdtf1230

**Comment by rdtf1230** [comment] 2022-07-28 12:47
> 죄송합니다. 기존 RN 프로젝트의 버전을 업데이트하거나 새 프로젝트를 시작하시겠습니까?@rdtf1230

Someday i will try ;)
Create a new project with 0.69.1 and
Move files from an existing from 0.66.4 project

I'm asking because it's something I've never done before.
Do other developers usually solve problems like this??
Wonder if i try to step into wrong side...

**Comment by codeOlam** [comment] 2022-07-28 14:09
> > 죄송합니다. 기존 RN 프로젝트의 버전을 업데이트하거나 새 프로젝트를 시작하시겠습니까?@rdtf1230
> 
> Someday i will try ;) Create a new project with 0.69.1 and Move files from an existing from 0.66.4 project
> 
> I'm asking because it's something I've never done before. Do other developers usually solve problems like this?? Wonder if i try to step into wrong side...

In RN doc, there is a guide that show how to safely upgrade RN versions. either using RN-CLI or manually. you could check it out. 

https://reactnative.dev/docs/upgrading

**Comment by Limoer96** [comment] 2022-07-29 08:58
When I create a project using the latest RN version, it works fine for me. But when I config the build variants, it crash on any android simulator. Is there something wrong with my configuration?@codeOlam
`
    flavorDimensions "env"

    productFlavors {
        dev {
            resValue "string", "app_name", "Dev.xx"
            applicationIdSuffix ".dev"
        }
        staging {
            resValue "string", "app_name", "Stag.xx"
            applicationIdSuffix ".stag"
        }
        demo {
            resValue "string", "app_name", "Demo.xx"
            applicationIdSuffix ".demo"
        }
        prod {
            resValue "string", "app_name", "xx"
        }
    }`

**Comment by Limoer96** [comment] 2022-07-29 09:00
When I create a project using the latest RN version, it works fine for me. But when I config the build variants, it crash on any android simulator.

**Comment by rdtf1230** [comment] 2022-07-29 12:04
> When I create a project using the latest RN version, it works fine for me. But when I config the build variants, it crash on any android simulator.

i think so too
Is there no solution?

**Comment by cortinico** [comment] 2022-07-29 15:01
> Someone to try out of a release build on a fresh React Native 0.69.1 project

Can someone try to create a reproducer? It would help us investigate what's the root cause of this issue.

**Comment by nschild** [comment] 2022-08-10 17:55
Coming back to this as I had a coworker with a similar issue. Have you tried opening your project in Android Studio then file > sync project files with gradle.

**Comment by Limoer96** [comment] 2022-08-12 07:49
I found that RN v0.69.4 seems to solve the above problem @rdtf1230

**Comment by rdtf1230** [comment] 2022-08-17 08:49
> I found that RN v0.69.4 seems to solve the above problem @rdtf1230

Thank you so much for posting the answer.

I updated to 0.69.4 after seeing this answer, but the same error kept coming up,
I've tried many things and it seems to have finally been fixed
Now let's introduce the method

Edit app/build.gradle file

Previously my file was

1. apply plugin
2. apply from
...
n project.ext.react

After trying various things, I moved 'project.ext.react' to the top line.

like this
1. project.ext.react
2. apply plugin ~~
3. apply from

When I run the app, I see that the libso error no longer appears, and the problem seems to have been resolved.

But another error appeared...

https://github.com/facebook/react-native/issues/34408#issuecomment-1217688994

I hope this article is helpful to people who have had the same type of problem.

Now I have to think again to solve another problem.

**Comment by cleandersonlobo** [comment] 2022-10-18 01:24
I was having the same problem.

There was a problema in react-native-gradle-plugin that was fixed in 0.71.4, but react-native@0.70+ uses version 0.70.3.

That solved it for me:

**package.json**
```json
  {
  .....
  "resolutions": {
    "react-native-gradle-plugin": "0.71.4"
  },
  "dependencies": {
    "react-native-gradle-plugin": "0.71.4"
      .....
  }
  ```

**Comment by aniravi24** [comment] 2022-10-21 03:01
> I was having the same problem.
> 
> * react v18.10.0
> * react-native v0.70.3
> * com.android.tools.build:gradle:7.0.4
> 
> There was a problema in react-native-gradle-plugin that was [fixed](https://github.com/facebook/react-native/commit/6125f1f866da129dbdc01f5b9e4fac27fa77ed8a), but react-native@0.70+ uses version 0.70.3.
> 
> That solved it for me:
> 
> **package.json**
> 
> ```json
>   {
>   .....
>   "resolutions": {
>     "react-native-gradle-plugin": "0.71.4"
>   },
>   "dependencies": {
>     "react-native-gradle-plugin": "0.71.4"
>       .....
>   }
> ```
> 
> > react-native+0.70.3.patch
> 
> ```shell
> diff --git a/node_modules/react-native/react.gradle b/node_modules/react-native/react.gradle
> index 912a407..d182708 100644
> --- a/node_modules/react-native/react.gradle
> +++ b/node_modules/react-native/react.gradle
> @@ -386,8 +386,8 @@ afterEvaluate {
>                      // Workaround for Android Gradle Plugin 3.4+ new asset directory
>                      into ("merged_assets/${variant.name}/out")
>  
> -                    // Workaround for Android Gradle Plugin 7.1 asset directory
> -                    into("$buildDir/intermediates/assets/${variant.name}/merge${targetName}Assets")
> +                    // Workaround for Android Gradle Plugin 7.3 asset directory
> +                    into("$buildDir/intermediates/assets/${variant.name}")
>                  }
>              }
>  
> ```

Thanks for this! This helped me realize what caused my production crashes on RN 0.70. I bumped my gradle plugin to 7.3.1 and didn't realize that would be a breaking change. Downgrading gradle to the version in the RN template (7.2.1) fixed the build for me.

**Comment by cortinico** [comment] 2022-10-21 15:25
> Thanks for this! This helped me realize what caused my production crashes on RN 0.70. I bumped my gradle plugin to 7.3.1 and didn't realize that would be a breaking change. Downgrading gradle to the version in the RN template (7.2.1) fixed the runtime crash for me.

As @aniravi24 mentioned, RN 0.70 builds with AGP 7.2.1
Diverging from the AGP version is **not recommended** and will most likely cause crashes.

Specifically @cleandersonlobo I see you are on RN 0.70 with AGP 7.0.4. This is not supported. Doing a patch-package of react-native and using "react-native-gradle-plugin": "0.71.4" is **not recommended** and will result in further update issues in the future.

I'm also closing here as the reproducer I asked was never provided and I suppose the issue was related to a wrong AGP version.

**Closed by cortinico** 2022-10-21 15:25 UTC
Labels: Needs: Repro, Needs: Attention, Type: Upgrade Issue

**Comment by HaddyYang** [comment] 2022-11-21 10:28
> > I was having the same problem.
> > 
> > * react v18.10.0
> > * react-native v0.70.3
> > * com.android.tools.build:gradle:7.0.4
> > 
> > There was a problema in react-native-gradle-plugin that was [fixed](https://github.com/facebook/react-native/commit/6125f1f866da129dbdc01f5b9e4fac27fa77ed8a), but react-native@0.70+ uses version 0.70.3.
> > That solved it for me:
> > **package.json**
> > ```json
> >   {
> >   .....
> >   "resolutions": {
> >     "react-native-gradle-plugin": "0.71.4"
> >   },
> >   "dependencies": {
> >     "react-native-gradle-plugin": "0.71.4"
> >       .....
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > react-native+0.70.3.patch
> > 
> > 
> > ```shell
> > diff --git a/node_modules/react-native/react.gradle b/node_modules/react-native/react.gradle
> > index 912a407..d182708 100644
> > --- a/node_modules/react-native/react.gradle
> > +++ b/node_modules/react-native/react.gradle
> > @@ -386,8 +386,8 @@ afterEvaluate {
> >                      // Workaround for Android Gradle Plugin 3.4+ new asset directory
> >                      into ("merged_assets/${variant.name}/out")
> >  
> > -                    // Workaround for Android Gradle Plugin 7.1 asset directory
> > -                    into("$buildDir/intermediates/assets/${variant.name}/merge${targetName}Assets")
> > +                    // Workaround for Android Gradle Plugin 7.3 asset directory
> > +                    into("$buildDir/intermediates/assets/${variant.name}")
> >                  }
> >              }
> >  
> > ```
> 
> Thanks for this! This helped me realize what caused my production crashes on RN 0.70. I bumped my gradle plugin to 7.3.1 and didn't realize that would be a breaking change. Downgrading gradle to the version in the RN template (7.2.1) fixed the runtime crash for me.

it worked for me! 7.2.1 version fixed it
