### ISSUE TITLE
<Image /> defaultSource not working

### ISSUE THREAD

**Issue by wong2** [facebook/react-native#980] opened 2015-04-23 04:13 UTC
I'd like to show a loading image while the real image is loading:

`<Image style={styles.image} source={{uri: this.props.url}} defaultSource={require('image!loading')} />`

but it just shows blank until the remote image arrives.

I've added `loading` in Xcode assets (they are png files):

![](http://doora.qiniudn.com/GSSvM.png)

**Comment by brentvatne** [comment] 2015-04-23 06:55
@wong2 - just tried this out on my own, seems to work as expected. Does your `loading` image display normally? Like this: `<Image style={styles.image} source={require('image!loading')} />`

This works for me on `0.4.0` (I used the name `cat` for my image though):

```javascript
  render() {
    return (
      <Image defaultSource={require('image!cat')}
             source={{uri: "http://upload.wikimedia.org/wikipedia/commons/3/3f/Fronalpstock_big.jpg"}}
             style={{flex: 1}} />
    )
  }
```

**Comment by wong2** [comment] 2015-04-23 07:33
@brentvatne  it works after I update to `0.4.0`, thanks!

**Comment by marcshilling** [comment] 2015-06-02 14:15
@brentvatne I'm working from the current master branch, and defaultSource is not working for me.

Here's my code:
```javascript
<Image style={styles.avatar}
       source={{uri: 'http://cdn.macrumors.com/article-new/2015/06/Apple-Watch-Midnight-Blue-250x299-250x273.jpg?retina'}}
       defaultSource={require('image!placeholder')} 
/>
```

I use the network link conditioner tool to slow down my internet connection so that I can test this, and the image view remains blank until the URL is loaded, at which point it is displayed. I can confirm my "placeholder" image is working correctly because it is displayed fine when I do:

```javascript
<Image style={styles.avatar}
       source={require('image!placeholder')} 
/>
```

Did this break again since `0.4.0`?

**Comment by marcshilling** [comment] 2015-06-03 16:52
Another thing I discovered - this for some reason works on the iPhone 4s simulator, but not any of the other ones...

**Comment by brentvatne** [comment] 2015-06-15 22:30
@marcshilling - thanks for following up, still having this problem?

**Comment by marcshilling** [comment] 2015-06-16 14:37
@brentvatne Yeah, I am...and unlike last time, I can actually share a project as proof!
https://github.com/marcshilling/ImageDefaultSourceExample

**Comment by ide** [comment] 2015-08-15 05:17
Should be fixed in 0.10.0-rc.

**Closed by ide** 2015-08-15 05:17 UTC

**Comment by smk524198002** [comment] 2017-03-02 09:24
defaultSource is also working in android?

**Comment by qq326646683** [comment] 2017-03-27 05:41
@smk524198002 ,can it support in android?
