### ISSUE TITLE
Command `run-platform` unrecognized. Make sure that you have run `npm install` and that you are inside a react-native project.

### ISSUE THREAD

**Issue by zhyilong** [facebook/react-native#15477] opened 2017-08-13 05:13 UTC
### Is this a bug report?

(write your answer here)

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Environment

1. `react-native -v 0.47.1`:
2. `node -v 8.1.3`:
3. `npm -v 5.0.3`:
4. `yarn --version 0.27.5`

Then, specify:

- Target Platform:

- Development Operating System: macOS Sierra

- Build tools:

### Steps to Reproduce

(Write your steps here:)

1.  i create project and run on iOS and Android well done;
2. npm install --save react-navigation and install smoothly；
3. react-native run-platform after notice: "ommand `run-android` unrecognized. Make sure that you have run `npm install` and that you are inside a react-native project."
4. run npm install but notice error still；

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by hramos** [comment] 2017-08-15 17:27
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-08-15 17:27 UTC
