### ISSUE TITLE
'react-native upgrade' overwrites .flowconfig without asking

### ISSUE THREAD

**Issue by gnl** [facebook/react-native#5455] opened 2016-01-21 08:47 UTC
...when upgrading to 0.18.1.
react-native-cli version is 0.1.10

**Comment by mkonicek** [comment] 2016-01-21 11:58
@gnl Would you be up for sending a PR to fix this?

**Comment by satya164** [comment] 2016-01-21 12:51
Duplicate of #4852

**Closed by satya164** 2016-01-21 12:51 UTC

**Comment by gnl** [comment] 2016-01-21 13:40
Looks like someone's already on it (I guess a search might've been a good idea before filing this)
