### ISSUE TITLE
Unable to start app on iOS simulator

### ISSUE THREAD

**Issue by James2516** [facebook/react-native#16487] opened 2017-10-22 01:21 UTC
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  8.6.0
  Yarn:  Not Found
  npm:  4.6.1
  Watchman:  4.7.0
  Xcode:  Xcode 9.0.1 Build version 9A1004
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: ^0.48.4 => 0.48.4

 Target Platform: iOS (10.3)

### Steps to Reproduce

I installed XCode 9.1 beta yesterday and subsequently uninstalled it (and remains with Xcode 9.0), but now i can no longer open a react native app on the iPhone simulator.

It's able to start the simulator, but the terminal header just rapidly toggle between node and simctl and Expo client doesn't get installed.

I have try reinstalling XCode, didn't fix the problem.

Gif: https://thumbs.gfycat.com/ThirstyYoungAmazontreeboa-size_restricted.gif

**Comment by ShylahChiera** [comment] 2017-10-22 02:24
I'm experiencing the same, even with newly initiated projects. My simulator and packager start but the compilation just hangs.

**Comment by James2516** [comment] 2017-10-22 04:29
Yeah Xcode 8.3.3 works. Doesn't work on Xcode 9 though.

**Comment by MacKentoch** [comment] 2017-10-22 10:06
Downgrading Xcode is not a solution.

Thank you @James2516 for reopening.

**Comment by hramos** [comment] 2017-10-23 16:21
Is there any console output you can share?

**Comment by James2516** [comment] 2017-10-23 16:24
As seen in the gif, it's stuck there without any output other than the Starting iOS...

**Comment by shripada** [comment] 2017-11-14 05:14
Seeing the same error with Xcode Version 9.1 beta (9B46)

**Comment by sourcec0de** [comment] 2018-01-17 22:46
If anyone runs into this issue simply slide the screen to the left and open the `expo` app. Then click `open app` This will trigger the application to build in the console.

**Comment by andrzey** [comment] 2018-02-07 08:09
@sourcec0de what if my simulator dont have the expo app? I struggle with the same issue.

**Comment by hramos** [comment] 2018-02-08 01:15
Closing as this issue doesn't have enough actionable information.

**Closed by hramos** 2018-02-08 01:15 UTC

**Comment by tmehta2442** [comment] 2018-02-08 04:19
Hello, sorry for adding to a closed issue but I ran into the same issue (thank you for adding the gif, precisely the same on my system). After awhile of frustration I simply changed the hardware from iOS 11.2, iPhone X to iPhone 8 and it works fine now. Also, I can go back to X and things appear to work as intended.

**Comment by azamsharp** [comment] 2018-02-08 18:35
This is a huge issue and it still exists. Here is a video I created which highlight the issue in detail. You can even see that I cannot even click on Open Expo App as it does nothing: 
https://twitter.com/azamsharp/status/961667289815900160

**Comment by vjsingh** [comment] 2018-05-04 18:33
Encountered this problem and the fix from @tmehta2442 worked for me

**Comment by raphaelrk** [comment] 2018-11-14 07:56
Still running into this issue, both with Xcode 9 and 10
[gif](https://gfycat.com/HairyAdolescentAppaloosa)
