### ISSUE TITLE
Unable to build with XCode 14.0

### ISSUE THREAD

**Issue by alois-beto** [facebook/react-native#34673] opened 2022-09-13 10:55 UTC
### Description

XCode 14.0 is released since yesterday, and I have the following error while building a fresh app on a physical device:
```
[...]/ios/Pods/Pods.xcodeproj error project: Signing for "React-Core-AccessibilityResources" requires a development team. Select a development team in the Signing & Capabilities editor.
```

Is react-native ready for XCode 14?

### Version

0.70.0

### Output of `npx react-native info`

System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 6.53 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: Not Found
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Watchman: 2022.08.29.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.0 => 0.70.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- Create a fresh react-native app with `npx react-native init MyApp`
- Open XCode and try to build the app on a real device

### Snack, code example, screenshot, or link to a repository

https://github.com/BeTomorrow/react-native-file-logger/tree/master/example
<img width="835" alt="Capture d’écran 2022-09-13 à 12 53 28" src="https://user-images.githubusercontent.com/83418275/189883447-94ef2246-f7ff-4db1-8621-4483f3fbbaa1.png">

**Comment by Thanaen** [comment] 2022-09-13 12:06
I also tried to compile the application in "any device" mode (so not specifically for a physical device), and I get the same error in XCode 14.

Manually selecting a team for these pods seems to solve the problem.

**Comment by pnthach95** [comment] 2022-09-13 13:51
I use [this script](https://github.com/CocoaPods/CocoaPods/issues/11402#issuecomment-1201464693) and it works

**Comment by fabiendem** [comment] 2022-09-13 16:35
From https://github.com/facebook/react-native/issues/34673#issuecomment-1245445193.
What does `CODE_SIGNING_ALLOWED` do? Isn't it needed?

**Comment by danilobuerger** [comment] 2022-09-13 18:21
See https://github.com/CocoaPods/CocoaPods/issues/11402

**Comment by Isaccobosio** [comment] 2022-09-15 09:43
> I use [this script](https://github.com/CocoaPods/CocoaPods/issues/11402#issuecomment-1201464693) and it works

Does it work even for react-native apps? 
My podFile has this line at the end
```
post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
```
How can I merge with that script?

**Comment by pnthach95** [comment] 2022-09-15 11:03
> How can I merge with that script?

Replace with this
```ruby
  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.targets.each do |target|
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
```

**Comment by relez** [comment] 2022-09-15 13:44
My workaround was to specify the TEAM_ID, my lines looks like this:

```
post_install do |installer|
  react_native_post_install(installer)
  __apply_Xcode_12_5_M1_post_install_workaround(installer)
  # Add these lines for Xcode 14 builds
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings["DEVELOPMENT_TEAM"] = "TEAM_ID"
        end
    end
  end
  # End of added lines
end
```
I hope it helps!

**Comment by pinokyov** [comment] 2022-09-15 15:28
I solved this problem select development team.

**Comment by hakansaglam29** [comment] 2022-09-16 12:49
> How can I merge with that script?

```
  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
        installer.pods_project.build_configurations.each do |config|
             config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
    end
  end
```

you can change your also like this.

**Comment by sunchanras** [comment] 2022-09-16 23:47
@hakansaglam29  I got 

> > How can I merge with that script?
> 
> ```
>   post_install do |installer|
>     react_native_post_install(installer)
>     __apply_Xcode_12_5_M1_post_install_workaround(installer)
>     installer.pods_project.build_configurations.each do |config|
>         config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
>     end
>   end
> ```
> 
> you can change your script also like this.

I got no bitcode error on production build with bitcode enable.

**Comment by hugozerken** [comment] 2022-09-19 13:32
same issue here, so how is the effection about setting CODE_SIGNING_ALLOWED = 'NO'

**Comment by Nerotox** [comment] 2022-09-20 09:53
> My workaround was to specify the TEAM_ID, my lines looks like this:
> 
> ```
> post_install do |installer|
>   react_native_post_install(installer)
>   __apply_Xcode_12_5_M1_post_install_workaround(installer)
>   # Add these lines for Xcode 14 builds
>   installer.generated_projects.each do |project|
>     project.targets.each do |target|
>         target.build_configurations.each do |config|
>             config.build_settings["DEVELOPMENT_TEAM"] = "TEAM_ID"
>         end
>     end
>   end
>   # End of added lines
> end
> ```
> 
> I hope it helps!

Worked perfectly thanks!

If anyone else isn't sure where to get his team ID, it can be found on the apple developer website https://developer.apple.com/account/#/membership under the menu "Certificates, Identifiers & Profiles" and then look at the top right under your account name.

**Comment by davidking1234** [comment] 2022-09-21 04:12
When implementing this fix, I am getting the following error:
"undefined method `react_native_post_install' for #<Pod::Podfile:0x00007fea76758c18>"

Is there something else we have to do to get that method to work?

Thanks in advance!

**Comment by breezertwo** [comment] 2022-09-21 12:30
@Nerotox. 

For me the string from the page would't be recocnized by Xcode:
I needed my `DEVELOPMENT_TEAM` id from `project.pbxproj` file --> looked like this: 0A11BC2345

**Comment by christianrank** [comment] 2022-09-21 16:03
I tried adding the fix mentioned here to the Podfile, and it worked locally.

But on the CI running on App Center, I am now getting this error:
```
/Users/runner/work/1/s/ios/Pods/Pods.xcodeproj: error: No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "XXX" with a private key was found. (in target 'React-Core-AccessibilityResources' from project 'Pods')
```

Any ideas about that?

**Comment by Jin-seop** [comment] 2022-09-22 05:24
xcode downgrade 13.4.1 version.

**Comment by christianrank** [comment] 2022-09-22 08:01
Downgrade is not a real solution, only a quick fix.

**Comment by christianrank** [comment] 2022-09-22 08:50
I found out [this](https://github.com/facebook/react-native/issues/34673#issuecomment-1245445193) script actually works on my CI, just [this](https://github.com/facebook/react-native/issues/34673#issuecomment-1248122805) doesn't.

**Comment by ansarikhurshid786** [comment] 2022-09-26 11:50
i simply select provision profile and without clear i build again it works for me.

**Comment by kelset** [comment] 2022-09-27 09:44
can you folks try this workaround? https://github.com/expo/expo/commit/d970a9ecbb15b554b6fa23e8d43006fd15152028

it's the one the Expo team has been implementing and it seems to be in line with some comments [in the pods issue](https://github.com/CocoaPods/CocoaPods/issues/11402#issuecomment-1259231655).

**Comment by hamidhadi** [comment] 2022-09-27 10:13
@kelset That workaround works for me.

**Comment by kg-currenxie** [comment] 2022-09-30 09:07
```
  post_install do |installer|
    react_native_post_install(installer)
    ...

    # AccessibilityResources gives an error, so it has to be removed
    # https://stackoverflow.com/questions/63082833/how-to-fix-react-native-app-not-building-for-ios
    installer.pods_project.targets.each do |target|
      target.remove_from_project if target.name == 'React-Core.common-AccessibilityResources'
      target.remove_from_project if target.name == 'React-Core-AccessibilityResources'
    end
  end
```

**Comment by steven-halla** [comment] 2022-10-04 02:28
> My workaround was to specify the TEAM_ID, my lines looks like this:
> 
> ```
> post_install do |installer|
>   react_native_post_install(installer)
>   __apply_Xcode_12_5_M1_post_install_workaround(installer)
>   # Add these lines for Xcode 14 builds
>   installer.generated_projects.each do |project|
>     project.targets.each do |target|
>         target.build_configurations.each do |config|
>             config.build_settings["DEVELOPMENT_TEAM"] = "TEAM_ID"
>         end
>     end
>   end
>   # End of added lines
> end
> ```
> 
> I hope it helps!

One thing to add is that you have to name your team in signing and capabilities as well. 

Thank you for this post its exactly what I needed. If I could give you a gold star I would!

**Comment by zienna** [comment] 2022-10-06 22:45
The script above will work to build the app but it breaks some libraries. It seems that globals in babel.config.js can't be seen. In our case that happens for react-native-vision-camera

**Comment by kelset** [comment] 2022-10-07 09:33
just as an headsup, we have a PR getting merged with a fix that we think is the right level of "scope": https://github.com/facebook/react-native/pull/34826 it will get cherry picked for the next 0.70 release

**Comment by ucheNkadiCode** [comment] 2022-10-10 03:59
Hey Everyone! I was able to find a solution! It's honestly much simpler than I thought. 

I believe the bug must have gotten introduced in XCode 14 and it was not setting a development team for the iOS pod named "React-Core-AccessibilityResources".  This was stopping me from being able to build my app on my IPhone and likely would have stopped me from being able to archive my build to get it on the App Store.

Solution: 

When you see this message: 
<img width="780" alt="Screen Shot 2022-10-09 at 8 42 15 PM" src="https://user-images.githubusercontent.com/20650058/194796404-5fc26d19-86da-4c3e-914e-92a3fc6db1c0.png">

The MISTAKE I was making was trying to go to my AppName -> Signing & Capabilities. This message is trying to tell you the error is within this specific POD. 

All you have to do is
1. Double click on the red text of the message. This is equivalent to clicking on "Pods" in the root folder. NOT the Pods folder of your AppName. 
<img width="246" alt="Screen Shot 2022-10-09 at 8 45 47 PM" src="https://user-images.githubusercontent.com/20650058/194796694-0ec6a525-dfe8-4dee-8688-22cf4d060337.png">
2. Double Clicking on the red message will take you straight to the specific Pod, otherwise, click Root level Pods folder then scroll in the nav bar to "React-Core-AccessibibilityResources" 

<img width="496" alt="Screen Shot 2022-10-09 at 8 50 13 PM" src="https://user-images.githubusercontent.com/20650058/194796939-30d9299e-b6c7-417f-967e-cd2c99264529.png">

3. Here you will see the issue: 
<img width="719" alt="Screen Shot 2022-10-09 at 8 52 59 PM" src="https://user-images.githubusercontent.com/20650058/194797235-ab7b6a52-5a14-4136-ba2d-2b057a06f693.png">

Select your team of choice and move on with your day!

**Comment by christianrank** [comment] 2022-10-10 07:47
@ucheNkadiCode this works only until you do `pod install` the next time.

**Comment by aprilmintacpineda** [comment] 2022-10-10 23:52
> > How can I merge with that script?
> 
> Replace with this
> 
> ```ruby
>   post_install do |installer|
>     react_native_post_install(installer)
>     __apply_Xcode_12_5_M1_post_install_workaround(installer)
>     installer.pods_project.targets.each do |target|
>       if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
>         target.build_configurations.each do |config|
>             config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
>         end
>       end
>     end
>   end
> ```

This solution worked best. https://github.com/facebook/react-native/issues/34673#issuecomment-1245445193

**Comment by kelset** [comment] 2022-10-12 14:57
hey folks, we have released a fix for this in 0.70.3 - please update to this new version: https://github.com/facebook/react-native/releases/tag/v0.70.3

**Closed by kelset** 2022-10-12 14:57 UTC
Labels: Tool: Xcode, Needs: Triage :mag:

**Comment by ucheNkadiCode** [comment] 2022-10-12 19:05
> hey folks, we have released a fix for this in 0.70.3 - please update to this new version: https://github.com/facebook/react-native/releases/tag/v0.70.3

I have a problem with this new release unless @kelset can answer. For new version 70.3, the solution involves turning off code signing for all React-Core packages. What does that do and how does it affect publishing to App Store? 

Thank you

**Comment by verifiedanswer** [comment] 2022-10-19 03:37
[[Solved] Select a development team in the Signing & Capabilities editor](https://verifiedanswer.com/select-a-development-team-in-the-signing-capabilities-editor/)

**Comment by tomwanzek** [comment] 2023-03-23 19:57
For current reference, we just ran into this issue when trying to upgrade our CI/CD pipeline to use
* Fastlane 2.212.1
* XCode 14.2

Incidentally, what seems to have made a difference is upgrading Cocoapods to 1.12.0. To be clear we did not add any of the workarounds in the Pod file post_install hooks as described earlier.

**Comment by liamjones** [comment] 2023-03-24 08:48
> Incidentally, what seems to have made a difference is upgrading Cocoapods to 1.12.0. To be clear we did not add any of the workarounds in the Pod file post_install hooks as described earlier.

Yes, Cocoapods 1.12.0 contains a fix for this issue (although it was missing from the release notes): https://github.com/CocoaPods/CocoaPods/commit/141a082a3fda27e73fe7b32bd999eac53b44cf12

**Comment by penghuiliada** [comment] 2023-03-24 12:41
> For current reference, we just ran into this issue when trying to upgrade our CI/CD pipeline to use
> 
> * Fastlane 2.212.1
> * XCode 14.2
> 
> Incidentally, what seems to have made a difference is upgrading Cocoapods to 1.12.0. To be clear we did not add any of the workarounds in the Pod file post_install hooks as described earlier.

Hi @tomwanzek , the cocoapods also helped us, now we can publish our app to TestFlight, but apple still complains that `ITMS-90129: The bundle uses a bundle name or display name that is already taken.`, we didn't change any name for our app.

before upgrading cocoapods, we can't even publish to TestFlight, the publish step already failed with that error message.

do you have any idea?
Thanks! 🙏

**Comment by Harukisatoh** [comment] 2023-03-29 01:28
For some reason upgrading cocoapods to 1.12.0 works locally, but doesn't work for AppCenter which is the CI I'm currently using. The post_install workaround also appears to not work for me.

**Comment by Harukisatoh** [comment] 2023-03-29 20:00
> For some reason upgrading cocoapods to 1.12.0 works locally, but doesn't work for AppCenter which is the CI I'm currently using. The post_install workaround also appears to not work for me.

For those who has the same issue as me:

Here's a link that explains the post install workaround: https://stackoverflow.com/a/39949186
After every pod install execution, the post install script is executed too. This script is used to disable the code signing on each pod library.

My problem was that this script was never being executed on CI. After a lot of hours trying to figure out why, I've finally found the cause in this link: https://learn.microsoft.com/en-us/appcenter/build/ios/#38-cocoapods
In the warning section they say: "If the repository already contains a /Pods folder, App Center assumes you've checked in the pods in your repository and will no longer perform pod install". And luckily (or no) in my repo I had the /Pods folder commited, and because of that, App Center never executed the script.

After that, the only thing I had to do was to execute a pod install locally, and commit all changes from /Pods folder to the repo, this way App Center received the already signed pods.

**Comment by tomwanzek** [comment] 2023-04-02 17:25
@penghuiliada Unfortunately, I have not much to add about

> TMS-90129: The bundle uses a bundle name or display name that is already taken.

It's an issue we have not encountered (so far 🤞). As you suggested with the "_before upgrading cocoapods_ ", this seems to have been a preexisting issue and not a new one introduced with Cocoapods 1.12.0. Good luck, hope you find a solution.

**Comment by penghuiliada** [comment] 2023-04-03 07:56
thank you @tomwanzek for checking!

Sorry, forgot to give update here, yes, it's indeed something wrong with our app, i documented the problem and solution here: https://github.com/CocoaPods/CocoaPods/issues/11402#issuecomment-1489846509

In case someone has the same problem.

**Comment by kennedy-f** [comment] 2023-04-14 17:16
Today, I encountered a similar issue and after inspecting the Expo code, I found a solution in their GitHub repository: https://github.com/expo/expo/blob/main/ios/Podfile#L78

To resolve my issue, I added the code snippet above to my Podfile, ran pod install again, and was able to successfully archive my application and distribute. 

```ruby post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    
    installer.target_installation_results.pod_target_installation_results
         .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
```

**Comment by sanoofrahiman960** [comment] 2023-07-11 05:38
> post_install do |installer|
>     react_native_post_install(installer)
>     __apply_Xcode_12_5_M1_post_install_workaround(installer)
>   end



1, when run i code " npx react-native run-ios"
i got error like this how to solve i stuck with 2 weeks
"
** BUILD FAILED **


The following build commands failed:
        CompileC /Users/sanoofrahimanj/Library/Developer/Xcode/DerivedData/milmaDataEntry-awvvzufrdwnctpalvkdkgvyaxbpw/Build/Intermediates.noindex/milmaDataEntry.build/Debug-iphonesimulator/milmaDataEntry.build/Objects-normal/arm64/AppDelegate.o /Users/sanoofrahimanj/Desktop/Workspace/DonamsTechLabs/milma-pms-app/ios/milmaDataEntry/AppDelegate.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'milmaDataEntry' from project 'milmaDataEntry')
(1 failure)"
 
**my pod file attached below**
<img width="1093" alt="Screenshot 2023-07-11 at 11 05 53 AM" src="https://github.com/facebook/react-native/assets/81160871/e3c38acb-ca14-433c-9d95-3b8e94edc73b">

my system info run :-npx react native info
System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M1
    Memory: 107.86 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.4.1 - ~/.nvm/versions/node/v16.17.1/bin/npm
    Watchman: 2023.02.27.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/sanoofrahimanj/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 19.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.1.0 => 18.2.0 
    react-native: ^0.70.6 => 0.70.12 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by thellecodes** [comment] 2024-03-10 18:30
> Today, I encountered a similar issue and after inspecting the Expo code, I found a solution in their GitHub repository: https://github.com/expo/expo/blob/main/ios/Podfile#L78
> 
> To resolve my issue, I added the code snippet above to my Podfile, ran pod install again, and was able to successfully archive my application and distribute.
> 
> ```ruby
>     react_native_post_install(
>       installer,
>       # Set `mac_catalyst_enabled` to `true` in order to apply patches
>       # necessary for Mac Catalyst builds
>       :mac_catalyst_enabled => false
>     )
>     __apply_Xcode_12_5_M1_post_install_workaround(installer)
>     
>     installer.target_installation_results.pod_target_installation_results
>          .each do |pod_name, target_installation_result|
>       target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
>         resource_bundle_target.build_configurations.each do |config|
>           config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
>         end
>       end
>     end
>   end
> ```

Worked for me  😇
