### ISSUE TITLE
ScrollView -- Deleting last index from array doesn't fallback to previous index, screen goes blank

### ISSUE THREAD

**Issue by vineelk8** [facebook/react-native#29515] opened 2020-07-28 11:09 UTC
I'm using the horizontal scroll view to show an array of images.
 
## Description

Let's think there are 3 images in an array rendered to the horizontal scroll view. When I delete 2nd image it's working fine. But when I try to delete the last image there will be a blank screen. When I swipe to left manually then the previous images will be seen.

### Problem Explanation:

I have three images in the scroll view as shown below.

*Scenario 1*

#### Image 1                                             Image 2                                         Image 3

Deleting Image 2 will display like below

#### Image 1                                             Image 3                     

*Scenario 2*

#### Image 1                                             Image 2                                         Image 3

Deleting Image 3 will display like below

#### Image 1                                             Image 2                                         Blank Screen

*Expected behavior *

When deleting Image 3 should fallback to image 2 but stays with a blank screen 

## React Native version:

System:

    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 609.41 MB / 7.90 GB

  Binaries:

    Node: 13.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.13.6 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found

  SDKs:

    Android SDK:
      API Levels: 25, 26, 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.0
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found

  IDEs:

    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763

  Languages:

    Java: 1.8.0_181
    Python: 2.7.17

  npmPackages:

    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2

**Comment by dulmandakh** [comment] 2020-09-01 21:06
Closing the issue because this issue tracker is intended to track RN issues, but the issue is related to your code. I would suggest to use FlatList instead.

**Closed by dulmandakh** 2020-09-01 21:06 UTC
Labels: Needs: Triage :mag:
