### ISSUE TITLE
Creating an instance of URL like: `new URL('http://facebook.com')` throws an exception.

### ISSUE THREAD

**Issue by ipeychev** [facebook/react-native#16434] opened 2017-10-17 16:35 UTC
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

  Environment:
  OS:  macOS Sierra 10.12.6
  Node:  8.6.0
  Yarn:  0.24.6
  npm:  5.3.0
  Watchman:  4.7.0
  Xcode:  Xcode 8.3 Build version 8E162
  Android Studio:  2.3 AI-162.3934792

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: ^0.48.4 => 0.48.4
  Target Platform: iOS (10.3)

### Steps to Reproduce

1. Create a ReactNative project, which uses React Native 16
2. Try to create an instance of `URL` in any .js file, like this:
    ```javascript
    const url = new URL('http://facebook.com');
    ```
3. Run the project

### Expected Behavior

The URL to be the native URL, [this one](https://developer.mozilla.org/en-US/docs/Web/API/URL). **It was working fine in React 15, but in React 16 it was replaced with something [internal](https://github.com/facebook/react-native/blob/91372e8f9aafcad2b5594175b1a3ce6f9c8f3b8e/Libraries/Blob/URL.js).** We use URL to parse URLs and extract information about the hostname, port, etc. so we need this behaviour back.

### Actual Behavior
An exception is thrown: `Creating BlobURL objects is not supported yet.`

<img width="376" alt="screen shot 2017-10-17 at 18 15 19" src="https://user-images.githubusercontent.com/78014/31676230-3e1d639c-b367-11e7-852b-23f528e7a2ef.png">

### Reproducible Demo

https://snack.expo.io/SJUA5i7TZ

**Comment by phillbaker** [comment] 2017-11-08 16:28
`requiring` the module seemed to work for me:

```
const url = require('url');
console.log(url.parse('https://example.com'));
```

**Comment by Panthro** [comment] 2018-02-24 22:24
not stale bot! Really annoying this issue! =\

**Comment by ck-alpha** [comment] 2018-02-25 13:56
Any updates on this??

**Comment by Trenrod** [comment] 2018-02-26 08:15
Reproduced with:
Environment:
  OS: Windows 10
  Node: 6.12.3
  Yarn: Not Found
  npm: 3.10.10
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.3 => 0.53.3

**Comment by lxcid** [comment] 2018-03-11 07:01
Reproduced in:

```
Environment:
  OS: macOS High Sierra 10.13.2
  Node: 9.2.0
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.2 => 0.53.2
```

**Comment by m-vdb** [comment] 2018-03-28 07:38
Having the issue as well, so sad :(

```
Environment:
  OS: macOS Sierra 10.12.6
  Node: 6.11.2
  Yarn: Not Found
  npm: 5.3.0
  Watchman: 4.5.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.2 => 0.52.2
```

**Comment by ovy9086** [comment] 2018-04-03 13:47
totally not stale bot :)

**Comment by benjohnson2001** [comment] 2018-04-24 18:41
+1

**Comment by danleechina** [comment] 2018-04-27 07:40
+1

**Comment by mike-marcacci** [comment] 2018-05-25 18:48
This can be worked around. Add this little piece of nastiness to your `index.js`:

```ts
// see https://github.com/facebook/react-native/issues/14796
import { Buffer } from "buffer";
global.Buffer = Buffer;

// see https://github.com/facebook/react-native/issues/16434
import { URL, URLSearchParams } from "whatwg-url";
global.URL = URL;
global.URLSearchParams = URLSearchParams;
```

**Comment by ricardochen** [comment] 2018-06-06 01:35
+1

**Comment by kodayashi** [comment] 2018-06-10 15:19
Same here. This would be nice to use when parsing URLs for deep link routing.

**Comment by bryce-larson** [comment] 2018-07-16 19:13
+1

**Comment by kharenzze** [comment] 2018-07-25 20:17
+1

**Comment by iwazzz** [comment] 2018-08-12 10:05
+2

**Comment by itskevinsam** [comment] 2018-08-27 03:53
+1

**Comment by tuncaulubilge** [comment] 2018-09-14 13:10
React-native seems to replace URL with this one, to support local blob urls: https://github.com/facebook/react-native/blob/master/Libraries/Blob/URL.js

**Comment by dzek69** [comment] 2019-01-03 16:15
For all readers here: @mike-marcacci presented a solution, but it's a bit unsafe - it RN have own incompatible, global `URL` - replacing it with "your own" implementation can break things when RN will be expecting his own URL you've rewritten.

Polyfilling `Buffer` this way should be safe, as RN doesn't implement `Buffer` at all.
It's always safe to import `URL` each time you need it.

I don't know any good solution if external library depends on `URL` (some kind of global overwriting, but only for some deps would be a solution here).

I just tweaked my own personal library so I can feed it with "custom" `URL` class instead of using global one - just to make it compatible with RN.

**Comment by dzek69** [comment] 2019-01-04 08:45
@kelset you've added `old version` tag, but the issue is still happening, just with a different message

**Comment by joelgetaction** [comment] 2019-02-12 01:44
+1 any update?

**Comment by nicolashardy** [comment] 2019-02-25 11:27
The 

```
// see https://github.com/facebook/react-native/issues/14796
import { Buffer } from "buffer";
global.Buffer = Buffer;

// see https://github.com/facebook/react-native/issues/16434
import { URL, URLSearchParams } from "whatwg-url";
global.URL = URL;
global.URLSearchParams = URLSearchParams;
```

Workaround does not work for release apk on android :( 

Any other workaround ?

**Comment by L-Yeiser** [comment] 2019-03-06 20:02
Still seeing this.
RN version `"^0.58.6"`

**Comment by nicolashardy** [comment] 2019-03-07 09:16
My workaround for android release was ```yarn add url-parse-lax```

on index.js : 

```
var url = require('url-parse-lax');
global.URL = url;
```

**Comment by matthargett** [comment] 2019-04-11 22:29
Hi! Our implementation of URL is narrow to avoid the bundle size impact of the more spec-complete implementation. Is there a library dependency you have that uses the URL constructor in this way?

If you can be more specific with what your code is trying to do, I can make a suggestion on the PR.

**Comment by satya164** [comment] 2019-04-25 16:03
> The URL to be the native URL

I just tested on iOS 12 and there doesn't seem to be a native URL global at all. How were you using it before? Did you have a polyfill?

**Comment by Asday** [comment] 2019-05-20 11:59
> Hi! Our implementation of URL is narrow to avoid the bundle size impact of the more spec-complete implementation. Is there a library dependency you have that uses the URL constructor in this way?
> 
> If you can be more specific with what your code is trying to do, I can make a suggestion on the PR.

I'm trying to parse a URL.  The `URL` class is perfect for that.  I don't see anything in the docs mentioning you've gutted `URL` for "bundle size" reasons.

```
if (new URL(url, baseURL).origin === baseURL && !headers.Authorization) {
  headers.Authorization = `Token ${token}`
}
```

What's _really_ cool about that is that is that it works _just_ fine in testing because `jest` is running in a completely different environment to what the app actually will, so I've had something in `master` for about a week that simply breaks immediately.

Could y'all fix this, please?  The way I see it, `URL`, being pretty standard and built in, isn't going to change much.  Likely means the first time someone downloads an app will be the last time they download `URL`, so bundle size be damned - that always takes ages anyway.  At least let me, as a developer, opt _in_ to the butchery.

**Comment by Asday** [comment] 2019-06-19 14:47
@satya164 Could you let me know what more information I can provide you further to my last comment?

**Comment by BettyJJ** [comment] 2019-07-05 08:37
Sad, another basic feature missing.

**Comment by cup** [comment] 2019-10-14 17:41
https://github.com/facebook/hermes/issues/132

**Comment by charpeni** [comment] 2019-11-25 01:46
👋 You should check this out: https://github.com/charpeni/react-native-url-polyfill.

**Comment by hramos** [comment] 2020-01-30 05:50
Closing as a workaround is provided in https://github.com/facebook/react-native/issues/16434#issuecomment-557956079

**Closed by hramos** 2020-01-30 05:50 UTC
Labels: Mid-Pri, Needs: Author Feedback, 🌐Networking

**Comment by Slapbox** [comment] 2021-09-18 19:56
@hramos if a polyfill existing is reason enough to close this issue then I think the React Native team should deprecate the URL module and outsource it to the community as they have with others. This weird, multi-year, limbo state of the URL module is not good...
