### ISSUE TITLE
[android] react native 0.43 webview issue display blank??

### ISSUE THREAD

**Issue by gongchao** [facebook/react-native#13627] opened 2017-04-22 09:59 UTC
```javascript
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  WebView,
  TouchableOpacity
} from 'react-native';

export default class testapp extends Component {

  constructor(props) {
    super(props)
    this.state = {
      tab: 0
    }
  }

  render() {
    return (
      <View style={styles.container}>
        <View style={{flex: 1, paddingTop: 30, paddingLeft: 30}}>
          <TouchableOpacity onPress={()=>this.setState({tab: this.state.tab ? 0 : 1})}><Text>切换</Text></TouchableOpacity>
          <Text>{this.state.tab}</Text>
        </View>
        {!!this.state.tab && (
          <WebView source={{uri: 'http://www.google.com'}} style={{ width: 200, height: 200 }}/>
        )}
        {!this.state.tab && (
          <WebView source={{uri: 'http://www.google.com'}} style={{ width: 200, height: 200 }}/>
        )}
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#F5FCFF',
  }
});

AppRegistry.registerComponent('testapp', () => testapp);

```

上边代码，点击 切换 tab

如果点击速度快的话，webview 会不显示，只在 android 是这样子。

并且没有任何报错信息

android 6/5

**Comment by gongchao** [comment] 2017-04-22 10:02
<Text>tab</Text> Quick Tap Tiles, <WebView/> display blank ??

android 5\6

**Comment by gongchao** [comment] 2017-04-22 14:48
```
W/art: Attempt to remove non-JNI local reference, dumping thread
W/AwContents: onDetachedFromWindow called when already detached. Ignoring
I/TAG: AwSettings.setUseWideViewPort === use=false; mAppPackageName=com.testapp
W/cr.ScreenOrientation: Removing an inexistent observer!
I/cr.CleanupReference: --- CLEANING ONE REF
```

**Comment by gongchao** [comment] 2017-04-22 15:00
![img](http://i2.muimg.com/567571/f5e8556f4c7425ee.jpg)

**Comment by hramos** [comment] 2017-04-24 13:06
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-04-24 13:06 UTC
