### ISSUE TITLE
could not find com.facebook.react:react-android:0.71.3

### ISSUE THREAD

**Issue by SharvanTech5** [facebook/react-native#36234] opened 2023-02-21 15:19 UTC
### New Version

0.61.4

### Old Version

0.71.3

### Build Target(s)

android

### Output of `react-native info`

System:
    OS: macOS 12.2
    CPU: (8) arm64 Apple M1
    Memory: 95.97 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.19.0 - /opt/homebrew/opt/node@16/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - /opt/homebrew/opt/node@16/bin/npm
    Watchman: 2022.11.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.3 => 0.71.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    react-native: Not Found

### Issue and Reproduction Steps

 react-native run-android
Output:
* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find com.facebook.react:react-android:0.71.3.
     Required by:
         project

**Comment by cortinico** [comment] 2023-02-21 15:28
Please provide:
- Your `android/app/build.gradle`
- Your `android/build.gradle`
- Your `settings/build.gradle`
- A reproducer project (if possible)

**Comment by SharvanTech5** [comment] 2023-02-21 15:32
rootProject.name = 'projectname'
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'
includeBuild('../node_modules/react-native-gradle-plugin')
include ':app', ':react-native-code-push'
project(':react-native-code-push').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-code-push/android/app')
include ':react-native-moengage'
project(':react-native-moengage').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-moengage/android')

**Comment by cortinico** [comment] 2023-02-21 17:36
You setup looks correct to me. Can you create a repro?

**Comment by carlosalmonte04** [comment] 2023-02-21 17:46
I was able to reproduce after copying and pasting the provided files into a new `npx react-native init AwesomeProject --version=0.71.3` project.

```
* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find com.facebook.react:react-android:0.71.3.
     Required by:
         project :app
   > Could not find com.facebook.react:hermes-android:0.71.3.
     Required by:
         project :app
```

**Comment by Ashish-5566** [comment] 2023-02-22 07:56
I am also facing same issue @SharvanTech5

**Comment by verochan** [comment] 2023-02-22 08:04
I'm also suffering this error after updating from 0.70.7 to 0.71.3 using align-deps: 

`npx @rnx-kit/align-deps --requirements react-native@0.71 --write`

This is the complete error:

```
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081 -PreactNativeDebugArchitectures=arm64-v8a -PreactNativeArchitectures=arm64-v8a

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.facebook.react:react-native:0.71.3.
     Searched in the following locations:
       - file:/Users/verochan/app-native/node_modules/react-native/android/com/facebook/react/react-native/0.71.3/react-native-0.71.3.pom
       - file:/Users/verochan/app-native/node_modules/jsc-android/dist/com/facebook/react/react-native/0.71.3/react-native-0.71.3.pom
       - file:/Users/verochan/.m2/repository/com/facebook/react/react-native/0.71.3/react-native-0.71.3.pom
       - https://dl.google.com/dl/android/maven2/com/facebook/react/react-native/0.71.3/react-native-0.71.3.pom
       - https://www.jitpack.io/com/facebook/react/react-native/0.71.3/react-native-0.71.3.pom
       - file:/Users/verochan/app-native/node_modules/@notifee/react-native/android/libs/com/facebook/react/react-native/0.71.3/react-native-0.71.3.pom
     Required by:
         project :app > project :react-native-interactable
         project :app > project :react-native-fs
         project :app > project :intercom_intercom-react-native
         project :app > project :notifee_react-native
         project :app > project :react-native-community_async-storage
         project :app > project :react-native-community_geolocation
         project :app > project :react-native-community_masked-view
         project :app > project :react-native-community_netinfo
         project :app > project :react-native-community_picker
         project :app > project :react-native-bootsplash
         project :app > project :react-native-config
         project :app > project :react-native-device-info
         project :app > project :react-native-get-random-values
         project :app > project :react-native-localize
         project :app > project :react-native-maps
         project :app > project :react-native-pager-view
         project :app > project :react-native-permissions
         project :app > project :react-native-safe-area-context
         project :app > project :react-native-screens
         project :app > project :react-native-sqlite-storage
         project :app > project :react-native-svg
         project :app > project :react-native-vector-icons
         project :app > project :rollbar-react-native
         project :app > project :react-native-flipper
   > Could not find com.facebook.react:react-android:.
     Required by:
         project :app > project :react-native-gesture-handler
```

On iOS, it's working fine. Any ideas?

**Comment by RonRadtke** [comment] 2023-02-22 09:01
Same issue for me after creating a brand new project and starting to migrate all the old code over (due to too many fixes I would have had to do by hand)

**Comment by bingaicao** [comment] 2023-02-22 09:30
I also encountered the same problem and fell back to 0.71.2 OK

**Comment by SharvanTech5** [comment] 2023-02-22 09:32
@bingaicao in 0.71.2 android and iOS both working fine ?

**Comment by bingaicao** [comment] 2023-02-22 09:49
> I'm an android, but you can try

**Comment by RonRadtke** [comment] 2023-02-22 09:58
Downgrade to 0.71.2 did not do the cut for me.
Still:
```
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find com.facebook.react:react-android:0.71.2.
     Required by:
         project :app
   > Could not find com.facebook.react:hermes-android:0.71.2.
     Required by:
         project :app
   > Could not find com.facebook.react:react-android:0.71.2.
     Required by:
         project :app > project :react-native-firebase_app
         project :app > project :react-native-firebase_messaging
         project :app > project :react-native-picker_picker
```

**Comment by bingaicao** [comment] 2023-02-22 10:06
> 

@RonRadtke You can clean up the project and rebuild it to ensure that the Gradle is not in offline mode

**Comment by RonRadtke** [comment] 2023-02-22 10:13
@bingaicao running a gradlew clean and rebuilding did not help. Running it via react-native start --reset-cache didn't help either

**Comment by RonRadtke** [comment] 2023-02-22 10:23
After removing ththe following in android/build.gradle it worked:
```
...
exclusiveContent {
               filter {
                   includeGroup "com.facebook.react"
               }
               forRepository {
                   maven {
                       url "$rootDir/../node_modules/react-native/android"
                   }
               }
        }
        ...
````

**Comment by bingaicao** [comment] 2023-02-22 10:27
After version 0.71.0, the local mode is no longer available. The global dependent version needs to be replaced online to ensure that all dependent versions are uniform

**Comment by RonRadtke** [comment] 2023-02-22 10:45
@bingaicao Thanks a lot for the Information! I just assumed it is fine since cortinico said it was fine.
@SharvanTech5 you have the same block in that I had to remove.

**Comment by carlosalmonte04** [comment] 2023-02-22 22:16
> After removing ththe following in android/build.gradle it worked:
> 
> ```
> ...
> exclusiveContent {
>                filter {
>                    includeGroup "com.facebook.react"
>                }
>                forRepository {
>                    maven {
>                        url "$rootDir/../node_modules/react-native/android"
>                    }
>                }
>         }
>         ...
> ```
> 
> Removing this part also makes the project build (until other errors pop up) with 0.71.3

This worked for me also, thanks. There is only a README.md file in that directory `$rootDir/../node_modules/react-native/android` hence why the not found errors. 

"Starting from React Native 0.71, we're not shipping the /android folder inside the React Native NPM package anymore due to sizing constraints on NPM. The Android artifacts are distributed via Maven Central." https://github.com/facebook/react-native/tree/main/android.

**Comment by joaquim-manzini** [comment] 2023-02-24 22:18
This **force** command in android/build.gradle seems to be forcing the use of 0.71.3 but it doesn't exist at maven repo:

```
allprojects {
    configurations.all {
        resolutionStrategy {
            force "com.facebook.react:react-native:" + REACT_NATIVE_VERSION
        }
    }
    ...

```
After commenting only the **force** line, it took from the version `https://mvnrepository.com/artifact/com.facebook.react/react-native/0.71.0-rc.0` and finished building!

**Comment by dragorwyin** [comment] 2023-03-08 14:20
> After version 0.71.0, the local mode is no longer available. The global dependent version needs to be replaced online to ensure that all dependent versions are uniform

Hello, it's seems to being a conflicting issue for artifactory proxies. I have such situation when I'm able to build it locally but I'm unable to build the project on Jenkins pipeline which is using artifactory proxy and is out of external internet connection.
I can read in @carlosalmonte04 comment that it's getting from maven central. What is the address I should point into to make a proper proxy traffic and allow to download this package?

**Comment by RubenPM-dev** [comment] 2023-03-23 14:07
Hi, 
also having this issue, I've compared the gradle files on the upgrade helper and my files and seem to be ok, still can't figure out the solution for this.

These are the buil
android/build.gradle
https://raw.githubusercontent.com/react-native-community/rn-diff-purge/release/0.71.1/RnDiffApp/android/build.gradle

My file
```
buildscript {
    ext {
        
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.3.1")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("de.undercouch:gradle-download-task:4.1.2")
        classpath("com.google.gms:google-services:4.3.14")
        classpath("com.google.firebase:firebase-crashlytics-gradle:2.9.1")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files   
    }
}

allprojects {
    repositories {
        google()
    }
}
```

And the app/build.gradle
https://raw.githubusercontent.com/react-native-community/rn-diff-purge/release/0.71.3/RnDiffApp/android/app/build.gradle

My app/build.gradle
```
apply plugin: "com.android.application"
apply plugin: "com.facebook.react"

[...]

def reactNativeArchitectures() {
    def value = project.getProperties().get("reactNativeArchitectures")
    return value ? value.split(",") : ["armeabi-v7a", "x86", "x86_64", "arm64-v8a"]
}

def pass = getPassword(System.getenv('KEYCHAIN_USER'), System.getenv('KEYCHAIN_SERVICE'))

android {
    ndkVersion rootProject.ext.ndkVersion

    compileSdkVersion rootProject.ext.compileSdkVersion

    namespace "com.myapp"
    defaultConfig {
        manifestPlaceholders = [appAuthRedirectScheme: 'myapp.auth']
        applicationId 'com.myapp'
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        if (project.hasProperty('RACENET_ANDROID_VERSION')) {
            versionCode RACENET_ANDROID_BUILD_NUMBER.toInteger()
            versionName RACENET_ANDROID_VERSION
        } else {
            versionCode 1
            versionName "1.1.3"
        }
        // buildConfigField "boolean", "IS_NEW_ARCHITECTURE_ENABLED", isNewArchitectureEnabled().toString()
        flavorDimensions "default"
        resValue "string", "build_config_package", "com.myapp
    }

    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include (*reactNativeArchitectures())
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
        release {
            if (project.hasProperty('MYAPP_UPLOAD_STORE_FILE')) {
                storeFile file(MYAPP_UPLOAD_STORE_FILE)
                storePassword pass
                keyAlias MYAPP_UPLOAD_KEY_ALIAS
                keyPassword pass
            }
        }
    }

    productFlavors {
        development {
            applicationId 'com.myapp'
            minSdkVersion rootProject.ext.minSdkVersion
            targetSdkVersion rootProject.ext.targetSdkVersion
        }
        internaltest {
            applicationId 'com.myapp'
            minSdkVersion rootProject.ext.minSdkVersion
            targetSdkVersion rootProject.ext.targetSdkVersion
        }
        firstparty {
            applicationId 'com.myapp'
            minSdkVersion rootProject.ext.minSdkVersion
            targetSdkVersion rootProject.ext.targetSdkVersion
        }
        preprod {
            applicationId 'com.myapp'
            minSdkVersion rootProject.ext.minSdkVersion
            targetSdkVersion rootProject.ext.targetSdkVersion
        }
        production {
            applicationId 'com.myapp'
            minSdkVersion rootProject.ext.minSdkVersion
            targetSdkVersion rootProject.ext.targetSdkVersion
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            debuggable false
            signingConfig signingConfigs.release
            minifyEnabled enableProguardInReleaseBuilds
            // shrinkResources true
            proguardFiles ( getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro" )
            firebaseCrashlytics {
                nativeSymbolUploadEnabled true
                unstrippedNativeLibsDir 'build/intermediates/merged_native_libs/release/out/lib'
            }
            ndk {
                debugSymbolLevel 'FULL'
            }
        }
    }

    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            // Example: versionCode 1 will generate 1001 for armeabi-v7a, 1002 for x86, etc.
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        defaultConfig.versionCode * 1000 + versionCodes.get(abi)
            }

        }
    }
}

dependencies {
     // The version of react-native is set by the React Native Gradle Plugin
    implementation("com.facebook.react:react-android")
    implementation("androidx.swiperefreshlayout:swiperefreshlayout:1.0.0")
    // implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation project(':react-native-inappbrowser-reborn')
    
    implementation project(':react-native-linear-gradient')

    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}")
    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.squareup.okhttp3', module:'okhttp'
    }

    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}")
    if (hermesEnabled.toBoolean()) {
        implementation("com.facebook.react:hermes-android")
    } else {
        implementation jscFlavor
    }

    constraints {
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.0") {
            because("kotlin-stdlib-jdk7 is now a part of kotlin-stdlib")
        }
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.0") {
            because("kotlin-stdlib-jdk8 is now a part of kotlin-stdlib")
        }
    }
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
```

And the settings.gradle
```
rootProject.name = 'myapp'
include ':react-native-vector-icons'
project(':react-native-vector-icons').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-vector-icons/android')
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'
includeBuild('../node_modules/react-native-gradle-plugin')
include ':react-native-linear-gradient'
project(':react-native-linear-gradient').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-linear-gradient/android')
include ':react-native-inappbrowser-reborn'
project(':react-native-inappbrowser-reborn').projectDir = new File(rootProject.projectDir, 	'../node_modules/react-native-inappbrowser-reborn/android')
```

**Comment by sehrish30** [comment] 2023-03-26 12:32
apply plugin: "com.facebook.react"

add this in your build.gradle/app

**Comment by lcastelnovo-atix** [comment] 2023-04-04 18:03
same issue here with react-native 0.71.4

**Comment by neketsushonen** [comment] 2023-04-04 21:23
same issue here with react-native 0.71.6

**Comment by rutgervanwilligen** [comment] 2023-04-16 12:02
Might be unrelated, but I had the same problem when upgrading my app from RN 0.68 to 0.71. In the end, I found out that my `package.json` still contained a reference to `"react-native-gradle-plugin": "^0.0.7"`. Removing that line solved the issue for me.

**Comment by nicks258** [comment] 2023-04-27 08:00
Can someone please conclude how to solve this?

**Comment by LouisMuriuki** [comment] 2023-05-06 12:53
@nicks258 
for my case I commented this line out
allprojects {
    configurations.all {
        resolutionStrategy {
        //    force "com.facebook.react:react-native:" + REACT_NATIVE_VERSION
        }
    }
    and did this
    apply plugin: "com.facebook.react"

add this in your build.gradle/app

**Comment by cortinico** [comment] 2023-05-09 10:57
> Asking again, can we get a reproducer?

I'm closing this as we couldn't get a reproducer from anyone. This is not an issue in React Native core but in some library. Without a repro we can't even provide workarounds.

**Closed by cortinico** 2023-05-09 10:57 UTC
Labels: Platform: Android, Needs: Author Feedback, Needs: Repro, Type: Upgrade Issue

**Comment by glennweb** [comment] 2023-06-29 01:33
I was upgrading to "react-native": "^0.72.0".

For me the issue was that for some reason react-native was not including the gradle plugin as a dependency. Was missing in my yarn.lock. 

Manually adding `yarn add react-native-gradle-plugin` and `yarn build` and then editing settings.gradle file by adding this line:

includeBuild('../node_modules/react-native-gradle-plugin')

seemed to fix.

More info here:
https://reactnative.dev/docs/next/integration-with-existing-apps?package-manager=yarn#adding-react-native-to-your-app

**Comment by kunalpal-cpi** [comment] 2023-07-18 11:49
Adding this line solved build issues

includeBuild('../node_modules/@react-native/gradle-plugin')

**Comment by sebas21** [comment] 2023-08-18 02:16
any solution?? I already tried everything

react-native:0.71.12

* What went wrong:
Could not determine the dependencies of task ':app:compileCertDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:certDebugCompileClasspath'.
   > Could not find com.google.firebase:firebase-bom:28.0.1.
     Required by:
         project :app
   > Could not find com.google.firebase:firebase-iid:.
     Required by:
         project :app
   > Could not find com.google.firebase:firebase-analytics:.
     Required by:
         project :app
   > Could not find com.google.firebase:firebase-messaging:23.1.1.
     Required by:
         project :app
   > Could not find androidx.appcompat:appcompat:1.3.1.
     Required by:
         project :app
         project :app > com.google.dagger:dagger-android-support:2.42
   > Could not find androidx.security:security-crypto:1.0.0.
     Required by:
         project :app
   > Could not find androidx.mediarouter:mediarouter:1.2.2.
     Required by:
         project :app
   > Could not find androidx.vectordrawable:vectordrawable-animated:1.1.0.
     Required by:
         project :app
   > Could not find androidx.multidex:multidex:2.0.1.
     Required by:
         project :app
   > Could not find com.facebook.react:react-android:.
     Required by:
         project :app
   > Could not find androidx.core:core:1.6.0.
     Required by:
         project :app
   > Could not find androidx.multidex:multidex:2.0.1.
     Required by:
         project :app
   > Could not find androidx.swiperefreshlayout:swiperefreshlayout:1.0.0.
     Required by:
         project :app
   > Could not find androidx.work:work-runtime:2.7.1.
     Required by:
         project :app
   > Could not find com.facebook.react:hermes-android:.
     Required by:
         project :app
   > Could not find any matches for com.facebook.react:react-native:+ as no versions of com.facebook.react:react-native are available.
     Required by:
         project :app > project :react-native-community_art
         project :app > project :react-native-firebase_analytics
         project :app > project :react-native-firebase_app
         project :app > project :react-native-firebase_dynamic-links
         project :app > project :react-native-firebase_messaging
         project :app > project :react-native-restart
   > Could not find androidx.activity:activity:1.3.1.
     Required by:
         project :app > com.google.dagger:dagger-android-support:2.42
   > Could not find androidx.annotation:annotation:1.2.0.
     Required by:
         project :app > com.google.dagger:dagger-android-support:2.42
         project :app > com.google.dagger:dagger-android:2.42
   > Could not find androidx.fragment:fragment:1.3.6.
     Required by:
         project :app > com.google.dagger:dagger-android-support:2.42
   > Could not find androidx.lifecycle:lifecycle-common:2.3.1.
     Required by:
         project :app > com.google.dagger:dagger-android-support:2.42
   > Could not find androidx.lifecycle:lifecycle-viewmodel:2.3.1.
     Required by:
         project :app > com.google.dagger:dagger-android-support:2.42
   > Could not find androidx.lifecycle:lifecycle-viewmodel-savedstate:2.3.1.
     Required by:
         project :app > com.google.dagger:dagger-android-support:2.42
   > Could not find com.google.firebase:firebase-messaging:23.1.1.

**Comment by ariel-ariel-liao** [comment] 2023-08-30 03:52
@sebas21  have you solved it? I also tried everything but nothing solves the problem.

**Comment by gsudhanshu** [comment] 2023-09-18 10:57
running 
1. npm start
2. on another terminal: npx react-native run-android

**Comment by lokesh12510** [comment] 2023-11-03 13:22
I faced same issue with react-native:0.64.2

![image](https://github.com/facebook/react-native/assets/49193177/beff449d-960e-4ce2-87c2-72e2be57f3ff)

I edited the android/app/build.gradle file

```
dependencies {
...
implementation "com.facebook.react:react-native:0.64.2-4"  // Version installed see in package.json
...
}
```

It worked!

**Comment by amadasif-dev** [comment] 2024-01-26 06:53
BUILD FAILED in 1m 47s
10 actionable tasks: 5 executed, 5 up-to-date
PS F:\fapProject\android> cd..
PS F:\fapProject> npx react-native run-android
info JS server already running.
info Installing the app...
5 actionable tasks: 5 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor

Picked up _JAVA_OPTIONS: -Xmx1024M

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find com.facebook.react:react-android:0.72.0.
     Required by:
         project :app
   > Could not find com.facebook.react:hermes-android:0.72.0.
     Required by:
         project :app

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
error Failed to install the app. Command failed with exit code 1: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
Picked up _JAVA_OPTIONS: -Xmx1024M FAILURE: Build failed with an exception. * What went wrong: Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'. > Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'. > Could not find com.facebook.react:react-android:0.72.0. Required by: project :app > Could not find com.facebook.react:hermes-android:0.72.0. Required by: project :app * Try: > Run with --stacktrace option to 
get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. * Get more help at https://help.gradle.org BUILD FAILED in 16s.
info Run CLI with --verbose flag for more details.
" am facing this issue too. Can anyone help me?

**Comment by durupanya** [comment] 2024-03-07 08:11
After updating react-native 0.73 and gradle 8.3, I received the following error
**Could not find com.facebook.react:react-native:0.73.5**

and I solved this by applying step by step from the link below as some friends explained, this error is also **Plugin with id 'com.facebook.react' not found**. It solves this too.

https://reactnative.dev/docs/next/integration-with-existing-apps?package-manager=yarn#adding-react-native-to-your-app

--------------
Note: After the update, you will definitely have missing files in the following files that are compatible with the new version:
build.gradle, app/build.gradle,  gradle.properties, settings.gradle, et.. *.gradle

**Comment by Ghabriel-elias** [comment] 2024-05-28 18:54
> Depois de remover o seguinte em Android/build.gradle funcionou:
> 
> ```
> ...
> exclusiveContent {
>                filter {
>                    includeGroup "com.facebook.react"
>                }
>                forRepository {
>                    maven {
>                        url "$rootDir/../node_modules/react-native/android"
>                    }
>                }
>         }
>         ...
> ```
> 
> A remoção desta parte também faz com que o projeto seja compilado (até que outros erros apareçam) com 0.71.3

thanks man, that soulved my problem. using react native 74.1
