### ISSUE TITLE
'react/bridging/LongLivedObject.h' file not found And Could not build module 'ReactCommon'

### ISSUE THREAD

**Issue by sushant115** [facebook/react-native#35664] opened 2022-12-16 13:29 UTC
### Description

<Project path>/Pods/Headers/Public/ReactCommon/ReactCommon/LongLivedObject.h:11:10 'react/bridging/LongLivedObject.h' file not found

<Project path>/Pods/Headers/Public/React-Core/React/RCTAppSetupUtils.h:30:9 Could not build module 'ReactCommon'

<img width="417" alt="Screenshot 2022-12-16 at 6 52 48 PM" src="https://user-images.githubusercontent.com/5407772/208107709-2badff10-9619-4b5b-9e49-8ea549c8ba8b.png">

### Version

0.70.6

### Output of `npx react-native info`

System:
    OS: macOS 13.0.1
    CPU: (8) x64 Apple M1 Pro
    Memory: 11.91 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.2.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm
    Watchman: 2022.11.28.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: ^0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Integrated RN version 0.70.6 to existing ios apps
Installed pod vial this command RCT_NEW_ARCH_ENABLED=1 fabric_enabled=1 arch -x86_64 pod install

### Snack, code example, screenshot, or link to a repository

<img width="417" alt="Screenshot 2022-12-16 at 6 52 48 PM" src="https://user-images.githubusercontent.com/5407772/208108842-e0d8528a-183f-48a6-a5d8-1d6f950b70b7.png">

**Comment by raldred** [comment] 2022-12-23 16:45
We're seeing this on 0.68.2
Not opted in to new architecture

**Comment by daogurtsov** [comment] 2022-12-26 15:51
Happens to me with new architecture on 0.70.6

**Comment by ste7en** [comment] 2023-01-04 11:48
Happens to me on 0.69.7, not opted in to new architecture nor Hermes

**Comment by liyanfei1004774105** [comment] 2023-02-08 08:00
Happens to me with new architecture on 0.71.1

**Comment by turboladen** [comment] 2023-02-15 01:00
Also seeing it.

```
❯ yarn react-native info
info Fetching system and libraries information...
System:
    OS: macOS 13.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 75.94 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /private/var/folders/k9/xm7wlry90z3fjwl909bs1bb80000gp/T/xfs-cc83b2a2/node
    Yarn: 3.4.1 - /private/var/folders/k9/xm7wlry90z3fjwl909bs1bb80000gp/T/xfs-cc83b2a2/yarn
    npm: 9.4.2 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/steve.loveless/.gem/ruby/2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9514443
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.2.0 => 18.2.0
    react-native: ^0.71.3 => 0.71.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by fobos531** [comment] 2023-02-25 08:39
@cortinico I'm pretty sure the nature of this issue is the same as what [this PR](https://github.com/facebook/react-native/commit/43f831b23caf22e59af5c6d3fdd62fed3d20d4ec#diff-bea68284f792a68eff3d058d7ce97bab593e1e5848f7b43bf5e5842460641ff9) fixes. It sounds like the same error, just for a different header file. I tried naively adding the `#ifdef __cplusplus` declaration analogous to the PR to the LongLivedObject.h, but it didn't resolve it to me. @janicduplessis Do you maybe have some insight on this?

**Comment by cipolleschi** [comment] 2023-02-27 12:01
Hi there, I'm sorry for this problem.

Can anyone provide a repro I can try on my own? 

It's not the first time we see such issues. Our CI has tests for both the Old and the New Architecture, to make sure that it builds, so it should be some edge case that we are not handling properly.

For context:
- We currently have 2 `LongLivedObject.h`: one in [`ReactCommon/react/bridging`](https://github.com/facebook/react-native/blob/5ff8895c2705b38d8ff0c0804055fc80a20ff282/ReactCommon/react/bridging/LongLivedObject.h#L23) and one in [ReactCommon/react/nativemodule/core/ReactCommon](https://github.com/facebook/react-native/blob/5ff8895c2705b38d8ff0c0804055fc80a20ff282/ReactCommon/react/nativemodule/core/ReactCommon/LongLivedObject.h).
- The second one is required to make sure that `use_frameworks!` actually work as expected.
- We are excluding the duplicated files [here](https://github.com/facebook/react-native/blob/0.71-stable/ReactCommon/ReactCommon.podspec#L70) because Xcode can't really build two files with the same name when they are in the same folder.

Now, my gut feeling is that there is something in your configuration that changes the HEADER_SEARCH_PATH of React Native and makes it lose the reference to the `ReactCommon` base path.

But to verify this, I'll need to reproduce it on a small sample.

**Comment by carlosalmonte04** [comment] 2023-04-06 19:14
Hey @cipolleschi I am also facing this issue after following [the guide to create a turbo module](https://reactnative.dev/docs/next/the-new-architecture/cxx-cxxturbomodules#how-to-create-a-c-turbo-native-module).

Here is a reproducer: https://github.com/carlosalmonte04/CxxTurboModulesGuide.

It built successfully after commenting out [the code you pointed to](https://github.com/facebook/react-native/blob/0.71-stable/ReactCommon/ReactCommon.podspec#L70).

**Comment by kaushal9808** [comment] 2023-05-12 11:41
Hello  @cipolleschi , is this issues has been fixed, we are facing the same issue. ?

**Comment by cipolleschi** [comment] 2023-05-15 12:27
Hi @kaushal9808, unfortunately I didn't have much time to go deeper in the repro. :( 
This week will be tricky, but I'll try to prioritize it next week.

Thank you all for your patience! 🙇

**Comment by lc3t35** [comment] 2023-06-06 18:03
Facing the same issue, using img.ly's PE.SDK with localization : https://img.ly/docs/pesdk/react-native/guides/user-interface/localization/ 

_including #import <RNPhotoEditorSDK/RNPhotoEditorSDK.h> in AppDelegate.mm_

_adding CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES option and select Yes. Then, search for c++ flags and add -fcxx-modules to both Debug and Release._

without localization and these additions, it build well.

**Comment by belakm** [comment] 2023-06-07 09:16
Facing the same issue after upgrading to 0.69.x

**Comment by lc3t35** [comment] 2023-06-08 21:35
Thank you @cipolleschi , I have now this error : 

[!] There are multiple dependencies with different sources for `RNPhotoEditorSDK` in `Podfile`:
- RNPhotoEditorSDK (from `../node_modules/react-native-photoeditorsdk`)
- RNPhotoEditorSDK

**Comment by cipolleschi** [comment] 2023-06-09 12:32
> EXJSIUtils

Are you using Expo? Or just some libraries from Expo but the main flow is handled by the RN CLI?

**Comment by lc3t35** [comment] 2023-06-09 13:56
Yes expo in bare mode, so RN mode.

**Comment by cipolleschi** [comment] 2023-06-12 15:39
@lc3t35 Ok, so, would you mind open an issue on their repo? Expo does some other things on top of the vanilla RN setup, so it could be that they are applying some changes to the Cocoapods setup that I would not be able to repro.
If they says that's a problem on the RN side, we would need a repro for React Native vanilla in order to work on that.

**Comment by cortinico** [comment] 2023-06-12 18:21
As mentioned by @cipolleschi, let's move this issue over to expo:

https://github.com/expo/expo/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.

**Closed by cortinico** 2023-06-12 18:21 UTC
Labels: Needs: Triage :mag:

**Comment by stigi** [comment] 2023-06-13 23:28
I believe the problem is that the header moved. There's a proxy header created [here](https://github.com/facebook/react-native/blob/a7e5c96a3d11671ed45b5d4f02334e8cc988ce9e/packages/react-native/ReactCommon/react/nativemodule/core/ReactCommon/LongLivedObject.h), but cocoapods seems to not make it available, because there's no implementation file.

If I manually touch up the files that contain the import `#import <ReactCommon/LongLivedObject.h>` and replace that with `#import <react/bridging/LongLivedObject.h>` the build succeeds.

**Comment by lc3t35** [comment] 2023-06-16 07:39
Here is the [patch-package](https://www.npmjs.com/package/patch-package) for react-native 0.71.3 : 

create patches/react-native+0.71.3.patch and add `"postinstall": "patch-package"`in your package.json.

```
diff --git a/node_modules/react-native/ReactCommon/react/nativemodule/core/ReactCommon/TurboModuleBinding.cpp b/node_modules/react-native/ReactCommon/react/nativemodule/core/ReactCommon/TurboModuleBinding.cpp
index 03c65ef..b41b29d 100644
--- a/node_modules/react-native/ReactCommon/react/nativemodule/core/ReactCommon/TurboModuleBinding.cpp
+++ b/node_modules/react-native/ReactCommon/react/nativemodule/core/ReactCommon/TurboModuleBinding.cpp
@@ -10,7 +10,7 @@
 #include <stdexcept>
 #include <string>
 
-#include <ReactCommon/LongLivedObject.h>
+#include <react/bridging/LongLivedObject.h>
 #include <cxxreact/SystraceSection.h>
 
 using namespace facebook;
diff --git a/node_modules/react-native/ReactCommon/react/nativemodule/core/ReactCommon/TurboModuleBinding.h b/node_modules/react-native/ReactCommon/react/nativemodule/core/ReactCommon/TurboModuleBinding.h
index 1791d4e..ed4184a 100644
--- a/node_modules/react-native/ReactCommon/react/nativemodule/core/ReactCommon/TurboModuleBinding.h
+++ b/node_modules/react-native/ReactCommon/react/nativemodule/core/ReactCommon/TurboModuleBinding.h
@@ -9,7 +9,7 @@
 
 #include <string>
 
-#include <ReactCommon/LongLivedObject.h>
+#include <react/bridging/LongLivedObject.h>
 #include <ReactCommon/TurboModule.h>
 #include <jsi/jsi.h>
 
diff --git a/node_modules/react-native/ReactCommon/react/nativemodule/core/platform/ios/RCTTurboModule.mm b/node_modules/react-native/ReactCommon/react/nativemodule/core/platform/ios/RCTTurboModule.mm
index 1ee5908..8aab28f 100644
--- a/node_modules/react-native/ReactCommon/react/nativemodule/core/platform/ios/RCTTurboModule.mm
+++ b/node_modules/react-native/ReactCommon/react/nativemodule/core/platform/ios/RCTTurboModule.mm
@@ -22,7 +22,7 @@
 #import <React/RCTModuleMethod.h>
 #import <React/RCTUtils.h>
 #import <ReactCommon/CallInvoker.h>
-#import <ReactCommon/LongLivedObject.h>
+#import <react/bridging/LongLivedObject.h>
 #import <ReactCommon/TurboModule.h>
 #import <ReactCommon/TurboModulePerfLogger.h>
 #import <ReactCommon/TurboModuleUtils.h>
```

**Comment by cortinico** [comment] 2023-06-16 14:59
> @cortinico as you can see all modules are react-native 0.71.3 related not expo (version 48.0.19 I currently use)
> Can you please check if these imports are corrected in upper version of react-native ?

Can you please create a repro on 0.71 or 0.72 which doesn't use Expo and reproduces this issue? Once you have it please open a new issue and link this one, and we can look into it
