### ISSUE TITLE
Textinput (Android) - Support onKeyPreIme. && BackHandler while keyboard shown.

### ISSUE THREAD

**Issue by TronNatthakorn** [facebook/react-native#19095] opened 2018-05-02 05:48 UTC
In native code (java) I can create TextInput with handle onKeyPreIme for force keyboard do not hide after Back press like this

[Textinput (React Native - Android) - Support onKeyPreIme
](https://stackoverflow.com/questions/50127094/textinput-react-native-android-support-onkeypreime)

Does TextInput support `onKeyPreIme` ?

## Expected Behavior
Expect keyboard do not hide after Back press. (In native code I can do with `onKeyPreIme`)

## Actual Behavior
Keyboard hide after Back press.

## Environment
Environment:
  OS: macOS High Sierra 10.13.2
  Node: 8.9.3
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.9.1
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4697961

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.3 => 0.53.3

**Comment by TronNatthakorn** [comment] 2018-05-02 06:57
I reproduce issue [https://github.com/facebook/react-native/issues/19096](https://github.com/facebook/react-native/issues/19096)

**Comment by kelset** [comment] 2018-05-16 10:16
Duplicate of #19096

**Closed by kelset** 2018-05-16 10:16 UTC
Labels: :large_blue_diamond:Android, :large_orange_diamond:TextInput, :rewind:Old Version
