### ISSUE TITLE
Registering Push Notifications Twice

### ISSUE THREAD

**Issue by bleonard** [facebook/react-native#3288] opened 2015-10-08 18:05 UTC
I've been following https://github.com/facebook/react-native/pull/2332 and am glad that it looks like it will be in, but I still think there is an issue. I'm running iOS 8+

I'm seeing the push registration callback twice.

My appdelegate looks like this...

```
- (void)application:(UIApplication *)application didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings {
  [RCTPushNotificationManager application:application didRegisterUserNotificationSettings:notificationSettings];
}

- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
{
  [RCTPushNotificationManager application:application didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
}

- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)notification
{
  [RCTPushNotificationManager application:application didReceiveRemoteNotification:notification];
}
```

The JS code ends up calling `requestPermissions` (RCTPushNotificationManager.m) which does

```
[[UIApplication sharedApplication] registerUserNotificationSettings:notificationSettings];
[[UIApplication sharedApplication] registerForRemoteNotifications];
```

Then there is the appdelgate callback to didRegisterUserNotificationSettings and then `didRegisterForRemoteNotificationsWithDeviceToken`(both)

The first one calls back into RCTPushNotificationManager, which does this.

```
+ (void)application:(UIApplication *)application didRegisterUserNotificationSettings:(__unused UIUserNotificationSettings *)notificationSettings
{
  [application registerForRemoteNotifications];
}
```

You'll note there is a second call to `registerForRemoteNotifications`

My iOS guy says he would remove the call to `registerForRemoteNotifications` in `requestPermissions`

Anyone else seeing this?

**Comment by DannyvanderJagt** [comment] 2015-10-19 10:04
I have tried to replicate your problem but the register callback keeps firing once. 

Which version of RN are you using? 
If you did use v0.12 and lower did you apply the fix from #2332 ?

**Comment by bleonard** [comment] 2015-12-03 04:49
I'll try it again in the more recent releases.

**Comment by chirag04** [comment] 2016-01-08 17:43
I'm also seeing this on 0.17. 

registerPermissions calls 
```
 [app registerUserNotificationSettings:notificationSettings];
 [app registerForRemoteNotifications];
```
https://github.com/facebook/react-native/blob/b9c5f753aaac7b387e671e0df3cef4cc19c088f4/Libraries/PushNotificationIOS/RCTPushNotificationManager.m#L160


and ``didRegisterUserNotificationSettings`` also calls ``registerForRemoteNotifications``
https://github.com/facebook/react-native/blob/b9c5f753aaac7b387e671e0df3cef4cc19c088f4/Libraries/PushNotificationIOS/RCTPushNotificationManager.m#L78

cc @ericvicenti @nicklockwood

**Comment by insraq** [comment] 2016-02-01 07:36
I've tried this on RN 0.19 and can reproduce this issue.

**Comment by yueshuaijie** [comment] 2016-02-02 01:10
I use 0.19, have this problem, too.

my code:
- (void)application:(UIApplication*)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData*)deviceToken
{
    [RCTPushNotificationManager didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
}

**Comment by MichaelCereda** [comment] 2016-02-03 00:19
i'm currently on 0.18 and i see this problem too, to avoid too many useless calls to my server i solved (not really) the issue adding a timeout+lock similar to this

```javascript
   this.lock = false;
   ............
   ...........
   PushNotificationIOS.addEventListener('register', (token)=>{
      if(!this.lock){
        ....... sending token to server here .....
        this.lock = true;
        setTimeout(()=>{this.lock=false},1000*5); // 5 seconds
      }
    });

```

**Comment by insraq** [comment] 2016-02-03 09:11
@MichaelCereda You could just comment out the the call to `registerForRemoteNotifications` in `requestPermission`. That's way easier. Just patch `RCTPushNotificationManager.m` https://github.com/facebook/react-native/blob/b9c5f753aaac7b387e671e0df3cef4cc19c088f4/Libraries/PushNotificationIOS/RCTPushNotificationManager.m#L160

**Comment by MichaelCereda** [comment] 2016-02-03 20:24
thanks @insraq i just used this method because i don't want to patch react-native itself (and lose the changes in case of an update) :) 
thank you anyways.

**Comment by insraq** [comment] 2016-02-11 02:25
Can we have a PR for this?

**Comment by jacob-israel-turner** [comment] 2016-02-23 17:55
I'm having this same issue, a PR would be nice.  Is the best solution to simply remove the `registerForRemoteNotifications` call in `requestPermissions`?

**Comment by sgonyea** [comment] 2016-04-09 15:57
The change that was merged in for this hsa actually broken push notifications in 0.23. I can't register for push unless I revert this change, in 0.23.

**Comment by sgonyea** [comment] 2016-04-09 15:57
.... which sucks, because it means I have to resubmit to the app store to get push notifications working again :(.

**Comment by sgonyea** [comment] 2016-04-09 16:05
The breaking change in question is:  https://github.com/facebook/react-native/commit/5c418655bf3423bff268aca670477a1ec8f5058e

Granted, putting it back DOES invoke multiple calls.  But that beats no calls :)

**Comment by sgonyea** [comment] 2016-04-09 20:14
The issue is basically that I can request to send push notifications (that works!) but I can't seem to get the Push Token via JS.  So although the user's approved it, I can't send the token back to the server. 😢

**Comment by insraq** [comment] 2016-04-13 08:04
@sgonyea I've test 0.23 on my device. It works without any issue. Have you set up the event handlers in AppDelegate.m according to this page? https://facebook.github.io/react-native/docs/pushnotificationios.html

The code for event hook has changed as I recall. If you follow the old instruction, you might need to update your code.

**Comment by tomazahlin** [comment] 2016-09-01 15:13
Having the same issue, any news on this?

**Comment by charpeni** [comment] 2016-11-14 01:14
@facebook-github-bot label Icebox

**Comment by charpeni** [comment] 2016-11-14 01:14
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/registering-push-notifications-twice

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment] 2016-11-14 01:14
@facebook-github-bot close

**Closed** 2016-11-14 01:15 UTC
Labels: Icebox, Ran Commands
