### ISSUE TITLE
How to run React native in Android Studio behind corporate proxy?

### ISSUE THREAD

**Issue by nanda248** [facebook/react-native#15247] opened 2017-07-28 06:15 UTC
​Hi,
The question I'm going to ask my be irrelevant for this Q&A section. But I still can't resolve this problem after a day. 

I'm trying to run React Native app on my company PC (windows 10). When I opened the android project created by react native in Android Studio, I got error as shown in the link(https://pasteboard.co/GCZ0R2Z.png​). I clicked the error link (https://docs.gradle.org/current/userguide/userguide_single.html#sec:accessing_the_web_via_a_proxy​) in the terminal window and followed the instructions on how to configure proxy in gradle.properties. But still, there is no luck. 

If anyone knows how to resolve the issue, kindly please help to share.
I have been using react native in my personal PC and there is no such error. It only happens on my company PC.

(Note: there is such error with gradle with android project which I created with Android Studio. The error only occurs on the android project created by React Native)​

**Comment by rajsuvariya** [comment] 2017-07-28 08:59
@nanda248 The link of pasteboard is not opening properly please check or post the image directly here

**Comment by hramos** [comment] 2017-07-28 18:49
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-07-28 18:49 UTC
