### ISSUE TITLE
Issues with rtl on ios

### ISSUE THREAD

**Issue by kfir91** [facebook/react-native#13406] opened 2017-04-09 12:53 UTC
Hello,
i added
```
 // in AppDelegate.m
   [[RCTI18nUtil sharedInstance] allowRTL:YES];
```
and
`I18nManager.forceRTL(true);`

in main js
and still when i use flex: 1 the text ltr and textAlign not help for this...

the problem is only on ios, in android all the things are good.

tnx a lot

**Comment by hramos** [comment] 2017-05-31 20:32
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-05-31 20:32 UTC

**Comment by big-toni** [comment] 2017-12-08 15:19
@kfir91 i had the same issue:

if your localization strings files are inside react native project, iOS project doesn't know the app "ready" for localization. 

you need to add DUMMY Localizable.strings language files to make app "ready" for RTL
 
i added Localizable.strings for 'ar' and 'en' both containing only: "DUMMY_KEY" = "DUMMY_VALUE";

and now the app starts RTL by defaul if the device is set to RTL
