### ISSUE TITLE
FlatList paddingBottom not working

### ISSUE THREAD

**Issue by xahon** [facebook/react-native#15707] opened 2017-08-30 10:48 UTC
### Is this a bug report?
yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
yes

### Environment
1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.45.1

2. `node -v`:
v7.10.1

3. `npm -v`:
4.2.0

4. `yarn --version`:
0.27.5

Then, specify:

- Target Platform: Android

- Development Operating System: Ubuntu 16.04Lts

- Build tools: Expo

### Steps to Reproduce

1. Create a FlatList component with items
2. Add style with `paddingBottom` to FlatList
3. No padding after that

### Expected Behavior
FlatList has empty space after last rendered item

### Actual Behavior
FlatList has no space after last item

(Write what happened. Add screenshots!)
![screenshot_2017-08-30-13-40-51-988_host exp exponent](https://user-images.githubusercontent.com/18731681/29868999-6e352db2-8dc4-11e7-821b-a6a4c5003abe.png)
List in screenshot is scrolled to bottom

Simple issue, i think it not needs any other information

**Comment by pqkluan** [comment] 2017-08-30 11:49
I'm having trouble with this issue, after the research I found out that:
- This issue is dated way back to 2015. Related issues: 2914, 11367.
- The root of this issue belongs to `ScrollView` component.
- Since `ListView`, `FlatList`, `Sections` and `VirtualizedList` extend `ScrollView` they share the same issue.
- The reason why this issue still alive due to a work around by adding white space using `renderFooter` or putting `paddingBottom ` inside `contentContainerStyle` prop. Which gives a similar result like `paddingBottom` from `ScrollView` style but actually not the same.

Flatlist with card effect:
```
<FlatList	style={{ padding: 16 }} .../>
```
http://imgur.com/yxbX2Hb

http://imgur.com/UTdl00Y

As you can see, the content container touch the Flatlist container without any spacing. Notice that the scroll indicator show that it hasn't reached the bottom.

I have a theory about the cause of this bug. The actual scrollable area was determined using `contentContainer` offset + height, ignore any space between the content container and the container outside.

**Comment by Shpadoinkle** [comment] 2017-09-13 00:59
Hey guys, 

Ran into the same problem today and just thought id post a work around for other who encounter it. 

For some reason applying top or bottom padding to the flatList component creates this issue where it pushes the inner content down out of view for the amount you specified. 

So the easiest way to tackle this is to apply either no padding at all, or only side padding.  Use bottom padding/ margin on your inner list items items instead.    And then pass an index through to your inner items so you can apply some top margin/padding to your first item. 

ie: 
` 
renderItem={({ item, index }) => <ListItem
                    Index={index}
                    event={item}
                />}
`

**Comment by dotansimha** [comment] 2017-10-30 09:09
For me it works with `{ flexGrow: 1, paddingBottom: 20}` with 0.49.5

**Comment by jgbaEmento** [comment] 2017-10-31 13:20
I added `contentContainerStyle={{paddingBottom:xxx}}` prop for extending the contentview. haven't testet on Flatlist but works on SectionList

**Comment by yasir-netlinks** [comment] 2017-12-26 11:46
Hi there, I have a somewhat a similar problem , I have been stuck for couple of days now
```
<View style={{flex: 1}}>
    <View style={{flexDirection: 'row'}}>
        <SearchBox />  // returns a TextInput
    </View>
    
    <FlatListComp />  //  returns a flatlist items
</View>
```
The `<SearchBox />` pushes the `FlatListComp` down out the view screen. I can see the scrollbar indicator going down beyond the screen view, so some list items are hidden (the last 2 or 3 items in the list cannot be seen)

![screenshot from 2017-12-23 13-18-30](https://user-images.githubusercontent.com/26054956/34356064-049f5328-ea58-11e7-8e2f-bd0ba1712ce2.png)

**Comment by kirankalyan5** [comment] 2018-01-09 09:03
For the last item to be visible in FlatList I added this *contentInset* prop with a bottom value instead for paddingBottom. I worked like a charm.

<FlatList  contentInset= {{bottom: 60}} />

**Comment by fcostaprojects** [comment] 2018-01-28 02:23
Try

1 => Add View in FlatList  
2 => Define style height for View
3 => Get screen height on Dimensions function from React Native 
4 => Adjust height in StyleSheet
`
```js
import {
  View,
  StyleSheet,
  Dimensions,
  FlatList
} from 'react-native';

<View style={styles.vwList}>
  <FlatList
   data={this.props.listData}
   keyExtractor={this._keyExtractor}
   renderItem={this._renderRow()} />
</View>

let { height } = Dimensions.get("window");

const styles = StyleSheet.create({
  vwList: {
    height: height - 250 //adjust
  }
});
```
`

**Comment by hramos** [comment] 2018-03-20 21:19
Closing due to [workaround provided](https://github.com/facebook/react-native/issues/15707#issuecomment-340759872).

**Closed by hramos** 2018-03-20 21:19 UTC
Labels: :large_orange_diamond:Lists

**Comment by pqkluan** [comment] 2018-03-21 01:27
> The reason why this issue still alive due to a workaround by adding white space using renderFooter or putting paddingBottom inside contentContainerStyle prop. Which will give a similar result like paddingBottom from ScrollView style but not the same.

Then you guy close it again without actually fix the root cause (ﾒﾟ皿ﾟ)

**Comment by hramos** [comment] 2018-03-21 17:43
@pqkluan do you have a PR with a fix you'd like us to look at?

**Comment by rsp8055** [comment] 2018-04-04 08:36
This code also helps to make the space at the footer in the flat-list or any list component

renderFooter = () => {
        return (
            <View style={{ margin: 50, }} />
        );
    };

<FlatList
....
....
  ListFooterComponent={this.renderFooter}

/>

**Comment by Haraldson** [comment] 2018-04-11 16:28
I solved this by using [`contentInset` from `scrollView`](https://facebook.github.io/react-native/docs/scrollview.html#contentinset);

```jsx
<FlatList
	// ...
	contentInset={{ bottom: 16 }}
	inverted />
```

As I have an **inverted** list that scrolls to the bottom by default (chat), adding 16 pixels to the bottom weirdly applies it to the top, which is what I wanted as all my items have `marginBottom` applied.

**Comment by riwu** [comment] 2018-04-14 13:10
@hramos the workaround you linked will not work properly for some cases.
Eg. 
```
const App = () => (
  <FlatList
    contentContainerStyle={{ padding: 100 }}
    data={[1, 2]}
    ItemSeparatorComponent={() => <View style={{ margin: 10 }} />}
    renderItem={() => <Button title="button" />}
  />
);
```
https://snack.expo.io/@riwu/flatlist-bottom-margin

The bottom button will not have the shadow styling on Android:
![](https://i.imgur.com/kOWRxTJ.png)

Wrapping `Button` with a `View` and adding margin to the `View` will be the correct workaround in this case.
 
I'm personally not affected too much by this bug since I'm aware of it and the workaround, but i feel sorry for the other thousands of developers who would have to waste their time figuring this out because a dev from RN decided that a workaround is a good enough solution to a bug.

Perhaps none of us here knows a good way to fix this bug, but shouldn't the issue be left opened so that another more enlightened dev might be able to come up with a proper fix?

**Comment by hodgef** [comment] 2018-05-10 15:47
@hramos What's the point of closing an issue if it hasn't been fixed? I don't see the point of sweeping bugs under the carpet, other than to frustrate the developers using your product. It just doesn't make sense from a bug tracking perspective.

**Comment by hramos** [comment] 2018-05-10 22:35
It's a prioritization matter due to the number of open issues. Happy to re-open if someone commits to opening a PR.

**Comment by jimitpatel** [comment] 2018-09-11 12:52
Work around is available but should also be able to work through styles.

**Comment by ogil7190** [comment] 2018-09-21 20:02
This problem of last 2 3 items not visible is maybe due to irregular size of Flatlist, wrap the Flatlist using a view and provide it a flex count to fix its size and now working like charm!

for ex:

<View>
<View style={{flex : 3}}> {some other view }} </View>
<View style={{flex : 7}}> <Flatlist ... /> </View> // wrapped inside a view
</View>

**Comment by steffodimfelt** [comment] 2018-12-08 19:41
> I added `contentContainerStyle={{paddingBottom:xxx}}` prop for extending the contentview. haven't testet on Flatlist but works on SectionList

Works fine in FlatList too. Thanks a lot!

**Comment by Moreno97** [comment] 2018-12-18 13:47
The solution offered by @jgbaEmento is not always working, and it depends on the content. Another solution that is working for us is to remove all padding or margin from children/item and set that style to the item children (eg. if the children have a `<Text>` or a `<View>`, set the style to that).

**Comment by JosuGZ** [comment] 2019-06-11 15:12
The workaround helps but it is not intuitive and it does not completely solve the problem as the scrollbar don't touch the bottom.

> It's a prioritization matter due to the number of open issues. Happy to re-open if someone commits to opening a PR.

If the issue is closed, it will be missed by people searching for something to work on.

**Comment by tungcao** [comment] 2019-06-12 07:14
> I'm having trouble with this issue, after the research I found out that:
> 
> * This issue is dated way back to 2015. Related issues: #2914, #11367.
> * The root of this issue belongs to `ScrollView` component.
> * Since `ListView`, `FlatList`, `Sections` and `VirtualizedList` extend `ScrollView` they share the same issue.
> * The reason why this issue still alive due to a work around by adding white space using `renderFooter` or putting `paddingBottom ` inside `contentContainerStyle` prop. Which gives a similar result like `paddingBottom` from `ScrollView` style but actually not the same.
> 
> Flatlist with card effect:
> 
> ```
> <FlatList style={{ padding: 16 }} .../>
> ```
> 
> ![flatlist with card effect 1](https://user-images.githubusercontent.com/12025966/29871072-ac383f92-8db4-11e7-8f4a-f30635967d7e.png)
> 
> ![flatlist with card effect 2](https://user-images.githubusercontent.com/12025966/29871077-b1c362b6-8db4-11e7-9588-00f01d7533ae.png)
> 
> As you can see, the content container touch the Flatlist container without any spacing. Notice that the scroll indicator show that it hasn't reached the bottom.
> 
> I have a theory about the cause of this bug. The actual scrollable area was determined using `contentContainer` offset + height, ignore any space between the content container and the container outside.

Sorry, unrelated. How do you create the view with style?

**Comment by shubham1164** [comment] 2019-06-15 11:23
Use this ListFooterComponent={ <View style={{ margin: 50 }} /> }

**Comment by johncurt** [comment] 2019-08-24 16:45
When using an inverted FlatList, using contentContainerStyle={{paddingTop: xxx}}  (instead of paddingBottom) works

**Comment by alexdant91** [comment] 2019-10-16 10:33
Thanks @jgbaEmento, it work for me!
