### ISSUE TITLE
Bundle failure on decorators

### ISSUE THREAD

**Issue by haggholm** [facebook/react-native#19955] opened 2018-06-28 20:56 UTC
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
  React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04 LTS (Bionic Beaver)
      CPU: x64 Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
      Memory: 3.13 GB / 31.39 GB
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 8.11.1 - /usr/bin/node
      Yarn: 1.5.1 - /usr/local/bin/yarn
      npm: 6.1.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        Build Tools: 23.0.1, 25.0.0, 25.0.2, 26.0.0, 26.0.1, 26.0.2, 27.0.1, 27.0.3
        API Levels: 23, 24, 26, 27
    npmPackages:
      @client/react: ^1.0.13 => 1.0.62 
      @client/react-native: ^1.0.13 => 1.0.62 
      react-native: ^0.56.0-rc.4 => 0.56.0-rc.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

## Description
Multi-platform app with both regular React (Webpack) and React Native builds. I upgraded RN to 0.56, which of course necessitated changes to the Babel environment, e.g. `babel-plugin-transform-decorators-legacy` → `@babel/plugin-proposal-decorators` (`{legacy:true}`). The Webpack version builds fine. The RN version fails bundling:

```
error: bundling failed: TypeError: Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got null
    at Object.validate (/home/petter/owl/client2/root/node_modules/@babel/types/lib/definitions/utils.js:128:13)
    at validate (/home/petter/owl/client2/root/node_modules/@babel/types/lib/validators/validate.js:17:9)
    at builder (/home/petter/owl/client2/root/node_modules/@babel/types/lib/builders/builder.js:46:27)
    at Object.AssignmentExpression (/home/petter/owl/client2/root/node_modules/@babel/types/lib/builders/generated/index.js:233:31)
    at _core.types.sequenceExpression.identDecorators.map.decorator (/home/petter/owl/client2/root/node_modules/@babel/plugin-proposal-decorators/lib/transformer-legacy.js:47:26)
    at Array.map (<anonymous>)
    at applyEnsureOrdering (/home/petter/owl/client2/root/node_modules/@babel/plugin-proposal-decorators/lib/transformer-legacy.js:44:59)
    at PluginPass.ClassExpression (/home/petter/owl/client2/root/node_modules/@babel/plugin-proposal-decorators/lib/transformer-legacy.js:161:28)
    at newFn (/home/petter/owl/client2/root/node_modules/metro/node_modules/@babel/traverse/lib/visitors.js:237:21)
 BUNDLE  [android, dev] ./index.android.js ▓▓▓▓▓▓▓░░░░░░░░░ 45.7% (809/1197), failed.
``` 

What puzzles me is that, again, *the Webpack version works*, so presumably there’s nothing inherently problematic about our Babel setup, and migration to Babel 7 was successful. The only difference in Babel configuration here is `babel-preset-react-native` (5.0.2) versus `@babel/preset-env`. (The thought occurred to me that this might be due to the RN preset importing `proposal-class-properties` before `-decorators`, but modifying `babel-preset-react-native/configs/main.js` to include the decorator plugin does not help.)

Looking at the AST in Babel, it looks like it’s failing with both class and method decorators.

Unfortunately I do not have a demo and can’t share the (proprietary) source, but any suggestions on how to go about debugging this would be welcome.

**Comment by jeffreymendez1993** [comment] 2018-06-29 15:08
@haani104 I am experiencing the same issue. Might be worth to wait until 56 is stable.

**Comment by kelset** [comment] 2018-07-02 09:54
I think this is a duplicate of #19789, and in particular I think you should take a look at [this comment](https://github.com/facebook/react-native/issues/19789#issuecomment-398988249)

**Comment by haggholm** [comment] 2018-07-03 18:28
The comment unfortunately doesn’t help—as mentioned above, I *am* using the new `@babel`-scoped packages, which work with Babel 7 (as demonstrated by the fact that the Webpack build works properly).

**Comment by kelset** [comment] 2018-07-04 09:19
Uhm could it be then that maybe some react-native only lib is still on babel 6, or something like that?

In our app we had to add this [babel-bridge](https://github.com/babel/babel-bridge) and enforce [yarn resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) in order to make sure that everything was being bundled properly.

That said, we will release 0.56.0 today (if nothing goes wrong) in order to increase the surface of devs using it, and hopefully lead to faster fixes for issues like yours.

**Comment by haggholm** [comment] 2018-07-04 21:10
After purging some old Babel plugins, pinning the versions of all `@babel/`-scoped packages to match the precise version pinned by `babel-preset-react-native`, &c., I was finally able to get past this error message and get stuck on a different error message that also seems to be related to Babel and decorators, and also happens in RN even though it works with Webpack: https://github.com/facebook/react-native/issues/20038

**Comment by TitanKing** [comment] 2018-07-05 14:00
Attempted everything that @haggholm did but can't get past the "bundling failed: TypeError: Property right of AssignmentExpression". I am going to attempt getting around this for a little while else I will have to revert to older version again.

**Comment by farwayer** [comment] 2018-07-05 20:49
I have another problem with decorators with 0.56 in **release** build only:
```js
function test() {}

class Test {
  @test val;
}
```
```
undefined is not a function (evaluating 'babelHelpers.applyDecoratedDescriptor(_class.prototype, "val", [test], {
    enumerable: true,
    initializer: null
  })')
```

**Comment by alessandro-bottamedi** [comment] 2018-07-08 09:13
Same problem here after upgrading to RN 0.56.

The app works in `DEBUG` with this configuration:

***package.json***
    
    ...
    "devDependencies": {
        "@babel/core": "7.0.0-beta.47",
        "@babel/plugin-proposal-decorators": "7.0.0-beta.47"
        ...
    }

***.babelrc***

    {
      "presets": [
        ["react-native"]
      ],
      "plugins": [
        ["@babel/plugin-proposal-decorators", { "legacy": true }]
      ]
    }
    
But in `RELEASE` xCode crash with this error:

    babelHelpers.applyDecoratedDescriptor is not a function.

**Comment by abelcha** [comment] 2018-07-08 23:12
It seems the error is caused by a dependency version missmatch between `babel-plugin-react-native-web`, which use the `7.0.0-beta.47` and the local babel packages.

The problem in our case was that some babel packages where installed using a caret range `^7.0.0-beta.47`. we fixed it using the hard coded version `7.0.0-beta.47`.

What make me tick was to run this command: 

`grep -r 'version' node_modules/@babel/*/package.json|grep version`

And I found that some babel presets were not installed with the beta.47 version

Hope it help

**Comment by thientnc-ibl** [comment] 2018-07-09 08:39
@kelset 
I fixed and used the version `@babel/core:7.0.0-beta.47` with `"@babel/plugin-proposal-decorators": "7.0.0-beta.47", and this error was resolved.
**BUT** I got the new error in `Animated.createAnimatedComponent`. I left the comment in this issue
[https://github.com/facebook/react-native/issues/19763](https://github.com/facebook/react-native/issues/19763)

**Comment by farwayer** [comment] 2018-07-09 13:52
Using `@babel/transform-runtime` fix the problem with `babelHelpers.applyDecoratedDescriptor is not a function.`

```json
{
  "presets": ["react-native"],
  "plugins": [
    ["@babel/proposal-decorators", {"legacy": true}],
    ["@babel/transform-runtime", {
      "polyfill": false,
      "regenerator": false
    }]
  ]
}
```
```json
"devDependencies": {
...
    "@babel/plugin-proposal-decorators": "7.0.0-beta.47",
    "@babel/plugin-transform-runtime": "7.0.0-beta.47",
    "@babel/runtime": "7.0.0-beta.47"
...
  }
```

Thanks to @alessandro-bottamedi. But this brings another problem:
```
TypeError: undefined is not an object (evaluating '_getPrototypeOf2.default')

This error is located at:
    in Icon
    in RCTView
    in App
    in RCTView
    in RCTView
    in AppContainer
```

**Comment by farwayer** [comment] 2018-07-09 14:38
@alessandro-bottamedi `react-native-vector-icons` and it works without `transform-runtime` but throws error with.

**Comment by thientnc-ibl** [comment] 2018-07-09 17:44
@farwayer 
You should edit your `.babelrc` like @alessandro-bottamedi 's comment. This is [https://github.com/facebook/react-native/issues/19763#issuecomment-403415501](https://github.com/facebook/react-native/issues/19763#issuecomment-403415501)

**Comment by SurpassRabbit** [comment] 2018-07-10 06:02
@thientnc-ibl  I still have the same problem.

```
{
  "presets": [
    "react-native"
  ],
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-transform-runtime", {
      "helpers": true,
      "polyfill": false,
      "regenerator": false
    }]
  ]
}



"devDependencies": {
    "@babel/core": "^7.0.0-beta.52",
    "@babel/plugin-proposal-decorators": "^7.0.0-beta.52",
    "@babel/plugin-transform-runtime": "^7.0.0-beta.52",
    "@babel/runtime": "^7.0.0-beta.52",
    "babel-jest": "^23.2.0",
    "babel-preset-react-native": "5.0.2",
    "jest": "23.3.0",
    "mobx": "^5.0.3",
    "mobx-react": "^5.2.3",
    "react-test-renderer": "16.4.1"
  },
```

**Comment by thientnc-ibl** [comment] 2018-07-10 06:05
@SurpassRabbit 
You MUST use fixed version `7.0.0-beta.47` for all @babel dependencies, like this
```    "@babel/plugin-proposal-decorators": "7.0.0-beta.47",
    "@babel/plugin-transform-runtime": "7.0.0-beta.47",
    "@babel/runtime": "7.0.0-beta.47"```

**Comment by farwayer** [comment] 2018-07-10 11:36
@kelset It should be doc'ed of course but what about errors in **RELEASE** bundle transformation? Build should work as is without using `@babel/tranform-runtime`. Some babel helpers missed in **RELEASE** bundle (`applyDecoratedDescriptor` for example). Not sure but look like it is trimming error while bundle optimization.
Should we open new issue for this?

@thientnc-ibl I already have same babel config as @alessandro-bottamedi. It's another error I got while using `@babel/transform-runtime`.

**Comment by farwayer** [comment] 2018-07-11 13:10
Created new issue with 2 workarounds for babel helpers bug https://github.com/facebook/react-native/issues/20150

**Comment by kelset** [comment] 2018-07-23 14:51
BTW related to decorators I found this in a [React-related issue](https://github.com/facebook/create-react-app/issues/167) I was reading earlier, I think it's worth sharing here:

> For people coming to this thread later—if you use MobX or a similar library, you don’t need decorators. They are just syntax sugar in this case.
> Learn more: [#214 (comment)](https://github.com/facebook/create-react-app/issues/214#issuecomment-236151343), [#411 (comment)](https://github.com/facebook/create-react-app/issues/411#issuecomment-238974268).
> Here is why we don’t include them: [#411 (comment)](https://github.com/facebook/create-react-app/issues/411#issuecomment-242740921).

**Comment by EyMaddis** [comment] 2018-08-13 17:33
@farwayer How did you solve the `_getPrototypeOf2`-Error? I tried to use the same babelHelpers workaround by adding it to babelHelpers, but it seems to get included from somewhere else and fails

**Comment by r3wt** [comment] 2018-08-24 21:12
@kelset using that approach might work but its a massive undertaking, especially if you are using a ton of decorators all through out your project.

**Comment by takion** [comment] 2018-09-10 11:07
I've solved it using beta.47 version of babel (like the ReactNative'one)
see https://github.com/babel/babel/issues/7831#issuecomment-419558735

**Comment by thereis** [comment] 2018-09-13 17:04
I'm having the same issue with RN 0.57

**Comment by LinusU** [comment] 2018-09-14 09:39
Okay, the problem is that React Native is bundling its own version of babel-helpers (exposed as a global variable named `babelHelpers`), which doesn't include support for decorators.

This will be fixed when this PR lands in Metro, and when React Native upgrades to that version of Metro. (I'm guessing React Native 0.58)

https://github.com/facebook/metro/pull/198

In the meantime, you can use this workaround:

```diff
diff --git a/index.js b/index.js
index 77f0986..8d0a685 100644
--- a/index.js
+++ b/index.js
@@ -1,7 +1,13 @@
+import applyDecoratedDescriptor from '@babel/runtime/helpers/esm/applyDecoratedDescriptor'
+import initializerDefineProperty from '@babel/runtime/helpers/esm/initializerDefineProperty'
+
 import { AppRegistry } from 'react-native'
-import App from './App'
+
+Object.assign(babelHelpers, { applyDecoratedDescriptor, initializerDefineProperty })
+
+const App = require('./App.tsx').default
 
 AppRegistry.registerComponent('Ctrlpanel', () => App)
```

Together with `npm add @babel/runtime`

**Comment by flexaddicted** [comment] 2018-09-21 15:03
> Okay, the problem is that React Native is bundling its own version of babel-helpers (exposed as a global variable named `babelHelpers`), which doesn't include support for decorators.
> 
> This will be fixed when this PR lands in Metro, and when React Native upgrades to that version of Metro. (I'm guessing React Native 0.58)
> 
> [facebook/metro#198](https://github.com/facebook/metro/pull/198)
> 
> In the meantime, you can use this workaround:
> 
> ```diff
> diff --git a/index.js b/index.js
> index 77f0986..8d0a685 100644
> --- a/index.js
> +++ b/index.js
> @@ -1,7 +1,13 @@
> +import applyDecoratedDescriptor from '@babel/runtime/helpers/esm/applyDecoratedDescriptor'
> +import initializerDefineProperty from '@babel/runtime/helpers/esm/initializerDefineProperty'
> +
>  import { AppRegistry } from 'react-native'
> -import App from './App'
> +
> +Object.assign(babelHelpers, { applyDecoratedDescriptor, initializerDefineProperty })
> +
> +const App = require('./App').default
>  
>  AppRegistry.registerComponent('Ctrlpanel', () => App)
> ```
> 
> Together with `npm add @babel/runtime`

I'm working on a Brownfield app and I've just updated to 0.57.

I receive this error when doing the release (both iOS and Android):

> [tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: babelHelpers.typeof is not a function. (In 'babelHelpers.typeof(n)', 'babelHelpers.typeof' is undefined)

I've applied the workaround by @LinusU but it does not work. The `console.log` is never printed.

```
import applyDecoratedDescriptor from '@babel/runtime/helpers/esm/applyDecoratedDescriptor'
import initializerDefineProperty from '@babel/runtime/helpers/esm/initializerDefineProperty'

console.log(applyDecoratedDescriptor);
console.log(initializerDefineProperty);

Object.assign(babelHelpers, {
  applyDecoratedDescriptor,
  initializerDefineProperty,
});

require('./src/ApplicationRegistry');
```

`ApplicationRegistry` is the file where I register the component in order to be exposed to the native world.

Here my package.json.

```
"dependencies": {
    "@babel/polyfill": "^7.0.0",
    "@babel/runtime": "7.0.0",
    "ent": "^2.2.0",
    "jssha": "^2.3.1",
    "lodash": "^4.17.10",
    "moment": "^2.19.4",
    "moment-timezone": "^0.5.17",
    "react": "^16.5.2",
    "react-native": "^0.57",
    "react-native-elements": "^0.19.1",
    "react-native-fast-image": "^4.0.14",
    "react-native-htmlview": "^0.13.0",
    "react-native-hyperlink": "0.0.11",
    "react-native-remote-svg": "^1.2.0",
    "react-native-scrollable-tab-view": "^0.8.0",
    "react-native-svg": "^6.3.1",
    "react-native-vector-icons": "^5.0.0",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-saga": "^0.16.0",
    "reselect": "^3.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "@babel/preset-react": "^7.0.0",
    "babel-core": "7.0.0-bridge.0",
    "babel-plugin-transform-inline-environment-variables": "^0.4.3",
    "concurrently": "^2.2.0",
    "jest": "^23.6.0",
    "metro-react-native-babel-preset": "^0.45.2",
    "msvgc": "^0.1.1",
    "prettier": "1.9.2",
    "react-dom": "^16.3.0-alpha.1",
    "react-native-storybook-loader": "^1.6.0"
  }
```

Here my `.babelrc`:

```
{
  "presets": ["@babel/preset-env", "module:metro-react-native-babel-preset"],
  "plugins": [
    ["transform-inline-environment-variables"]
  ]
}
```

Any idea?

**Comment by Fendoro** [comment] 2018-09-24 12:14
@flexaddicted, i got same error `Unhandled JS Exception: babelHelpers.typeof is not a function.` in release build and fixed it by deleting `@babel/preset-env` from `presets` in `.babelrc`

Here my `.babelrc`:
```
{
  "presets": [
    "module:metro-react-native-babel-preset"
  ]
}
```

**Comment by shinriyo** [comment] 2018-10-03 23:27
`undefined is not a function (near '...babelHelpers.applyDecoratedDescriptor...')`
Mine can't work on release build. But, Simulator can.

I just mimicked "LinusU commented".

```
{
  plugins: [
    ['@babel/plugin-proposal-decorators', {legacy: true}],
    ["@babel/plugin-transform-runtime", { "helpers": true }] # I added this
  ],
  "presets": ["module:metro-react-native-babel-preset"]
}
```

My `package.json` doesn't have them.
"@babel/plugin-transform-runtime"
"@babel/runtime"

So, I also did the command.
```
yarn add @babel/plugin-transform-runtime --dev
yarn add @babel/runtime --dev
```

now I have them in my `package.json`.
```
    "@babel/plugin-transform-runtime": "^7.1.0",
    "@babel/runtime": "^7.1.2",
```

But, doesn't work yet..

**Comment by shinriyo** [comment] 2018-10-03 23:30
I also did `yarn add babel-plugin-transform-inline-environment-variables --dev`

`package.json.`
```
    "babel-plugin-transform-inline-environment-variables": "^0.4.3",
```

**Comment by shinriyo** [comment] 2018-10-05 15:42
I also use `react-native-vector-icons`. version 5.

**Comment by shinriyo** [comment] 2018-10-05 16:00
`yarn add babel-preset-react-native@5 --dev` but not success.

**Comment by shinriyo** [comment] 2018-10-07 08:08
I don't know why resolve.

My ReactNative project is created like this. 
Why `0.57.0-rc.3`? cause I'd like to use TypeScript.
`react-native init RN057Sample --version 0.57.0-rc.3`

my `package.json`

```
{
  "name": "kazoemon",
  "version": "0.0.1",
  "license": "UNLICENSED",
  "private": true,
  "scripts": {
    "start": "yarn jest --clearCache && react-native start",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "test": "jest"
  },
  "dependencies": {
    "mobx": "^5.1.2",
    "mobx-react": "^5.2.8",
    "react": "^16.5.2",
    "react-dom": "^16.5.2",
    "react-native": "0.57.0-rc.3",
    "react-native-admob": "2.0.0-beta.5",
    "react-native-elements": "^0.19.1",
    "react-native-radio-buttons": "^1.0.0",
    "react-native-vector-icons": "^5.0.0",
    "react-navigation": "^2.16.0"
  },
  "devDependencies": {
    "@babel/plugin-proposal-decorators": "7.0.0-beta.47",
    "@babel/plugin-transform-runtime": "7.0.0-beta.47",
    "@babel/runtime": "^7.1.2",
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "^0.43.5",
    "react-test-renderer": "16.4.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

what I did is.
I guess `7.0.0-beta.47` is important version.
```
yarn add --dev @babel/core
yarn add --dev @babel/plugin-proposal-decorators@7.0.0-beta.47
yarn add --dev @babel/plugin-transform-runtime@7.0.0-beta.47
```

My `.babelrc`

```
{
  "presets": [
    "react-native"
  ],
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-transform-runtime", {
      "helpers": true,
      "polyfill": false,
      "regenerator": false
    }]
  ]
}
```

I mimicked what "Alessandro Bottamedi" answered in the site
https://stackoverflow.com/questions/51212618/how-to-use-mobx-in-react-native-0-56-babel-7-with-decorators

**Comment by williscool** [comment] 2018-10-17 06:45
inspired by @Fendoro 's comment

I got my react native build back working by not adding plugins that are already present in 

https://github.com/facebook/metro/blob/master/packages/metro-react-native-babel-preset/src/configs/main.js

I don't really use anything not in the preset to begin with lol.

Hope this helps someone else.

Ironically this even made my test suite faster lol.

Go figure.

I also run a node server our of the same repo that builds with the same babel config too

**Comment by cpojer** [comment] 2019-03-20 08:58
It seems like this shouldn't be an issue any more with the latest versions of RN and there are workarounds mostly related to babel.

**Closed by cpojer** 2019-03-20 08:58 UTC
Labels: JavaScript, Type: Bug Report, 📦Bundler
