### ISSUE TITLE
[0.54] TextInput.setNativeProps({text: ''}) no longer works

### ISSUE THREAD

**Issue by benadamstyles** [facebook/react-native#18272] opened 2018-03-08 11:48 UTC
### Environment

```
Environment:
  OS:  macOS Sierra 10.12.6
  Node:  8.7.0
  Yarn:  1.3.2
  npm:  5.6.0
  Watchman:  4.7.0
  Xcode:  Xcode 9.2 Build version 9C40b
  Android Studio:  3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.54.0 => 0.54.0
```

### Expected Behavior

Calling `textInputRef.setNativeProps({text: ''})` or `textInputRef.clear()` clears the text input – this was working in previous versions (before the `<Text>` rewrite in `0.54`).

### Actual Behavior

Calling `textInputRef.setNativeProps({text: ''})` or `textInputRef.clear()` does nothing.

### Steps to Reproduce

Repro here: https://github.com/Leeds-eBooks/react-native-0.54-text-input-clear-repro

**Comment by Leeds-eBooks** [comment] 2018-03-08 12:18
Ok here's a repro: https://github.com/Leeds-eBooks/react-native-0.54-text-input-clear-repro

**Comment by magicien** [comment] 2018-03-08 17:14
It's not completed yet, but TextInput.clear() works again with this change (#18278).

**Comment by AMHZR** [comment] 2018-04-12 14:03
is there any update here.. as i have a serious dependency on this..

**Comment by kushal** [comment] 2018-04-12 16:39
I ended up manually applying the patch
https://github.com/facebook/react-native/pull/18363/files locally on top of
0.55.2 just to keep making progress

**Comment by Leeds-eBooks** [comment] 2018-04-16 12:08
@kushal Have you found a way to patch locally without losing your patch whenever you run `npm install` or `yarn`?

**Comment by pualxiao** [comment] 2018-05-10 09:19
https://github.com/pualxiao/React-Native-TextInput-Bug-Fix

**Comment by padvlad** [comment] 2018-05-16 12:17
I am using v0.55.3 and I've encountered the same issue. ```textInputRef.clear()``` and ```textInputRef.setNativeProps({text: ''})``` only seem to work on Android. On iOS nothing happens.

**Comment by x3388638** [comment] 2018-05-30 17:30
v0.55.3
a dirty solution for iOS
```
if (Platform.OS === 'ios') {
	this.textInputRef.setNativeProps({ text: ' ' });
}

setTimeout(() => {
	this.textInputRef.setNativeProps({ text: '' });
});
```

**Comment by assafb81** [comment] 2018-05-31 06:38
@x3388638,
in RN version 0.55.4 your solution does not work :(

**Comment by minhchienwikipedia** [comment] 2018-06-08 03:37
I had create new Text Input for fix this bug right now, everybody can use it before RN fix it.
https://github.com/agiletechvn/react-native-text-input-enhance

**Comment by datvtwakumo** [comment] 2018-06-13 02:54
@minhchienwikipedia you are using 
clear() {
    this.setState({ text: '' });
 } 
in IOS
Pratically, we don't want to do that because it affects keyboard behavior!

**Comment by minhchienwikipedia** [comment] 2018-06-14 04:28
@datvtwakumo Can you explain your issue?

**Comment by sasayahiromu** [comment] 2018-06-15 09:09
@minhchienwikipedia
if using this.setState and value, inputing word is confirmed(?) and can't convert.
It can be used in Engleish, somehow, but handling language which is needed to convert, such as Japanese, it don't work.

**Comment by datvtwakumo** [comment] 2018-06-15 14:28
@sasayahiromu you are right
@minhchienwikipedia one more problem that you don't want to rerender your input component with every setState, right? If you need a default value, there is defaultValue, and with every change, try to not setState, but to send new value elsewhere or debounce listening function so that you do not need to rerender component!

**Comment by jaimehing** [comment] 2018-06-17 11:27
hi, is there a plan fixing this in v 0.56?

**Comment by ATShiTou** [comment] 2018-06-20 09:16
I hava a simple solution

```
<TextInput key={this._key}/>
```
then
```
clear() {
    this._key++;
    this.forceUpdate();
  }
```

**Comment by hramos** [comment] 2018-06-22 00:28
@jaimehing not at this time. Anything that is not fixed on `master` right now is unlikely to be part of 0.56.

**Comment by bbeckk** [comment] 2018-06-24 07:01
Simply unfocusing the textInput solves the problem

```
<View style={styles.textInputStyle}>

    <TextInput onChangeText={(text) => this.setState({searchText: text}, () => {
                   this.state.searchText.length > 1 ? this._getSearchedData() : null
               })}
               value={this.state.searchText}
               placeholder='Search restaurant or cuisine'
    />

    <TouchableOpacity  onPress={() => {
                    this.setState({searchText: ''}),
                    Keyboard.dismiss()
                }}>
    <Icon name="md-close-circle" style={{color: 'gray', fontSize: 15,}}/>
</TouchableOpacity>

</View>
```

**Comment by Lidanha** [comment] 2018-06-25 08:35
@x3388638's solution works well for me.

**Comment by doublex** [comment] 2018-07-04 15:07
+1

**Comment by sunr1ze** [comment] 2018-07-11 17:16
This works for me

**RN v0.55.3**
```
setTimeout(() => {
    this.textInputRef.clear();
});
```

With **styled-components v3.2.6**
```
setTimeout(() => {
    this.textInputRef.root.clear();
});
```

**Comment by tli4** [comment] 2018-07-14 08:19
@kushal I updated the file you mentioned locally, but since then. I could no longer change the value of a TextInput if I specified a const value for that textbox

**Comment by g00dnatur3** [comment] 2018-07-24 09:49
This fix worked for me on all versions of RN with 0.54 - 0.56

```  
textDidChange(text) {
    this.textInput.setNativeProps({text})
}
```

then you can use `textInputRef.clear()` no problems...

**Comment by tabfed** [comment] 2018-07-26 08:21
```
this.state = {
  current:0,
}

//no set value , change key ,  foreceUpdate
<Text key={this.state.current} />

<Button onClick={this.setState({
   current:this.state.current+1
})}/>
```

**Comment by datvtwakumo** [comment] 2018-07-29 05:52
this hack works for me, please tried this :D
https://github.com/facebook/react-native/issues/18767#issuecomment-403685280

**Closed** 2018-09-11 00:51 UTC
Labels: :clock1:PR Pending, :large_orange_diamond:TextInput, :warning:Regression, Ran Commands
