### ISSUE TITLE
[0.19][ios]Error 'babelHelpers.typeof is not a function'  running examples UIExplorer

### ISSUE THREAD

**Issue by asd123freedom** [facebook/react-native#5747] opened 2016-02-04 06:13 UTC
The project I inited before run normally. But the example cloned from react-native of github could not works. I followed the steps in README, and I find out one module require babel@5.8.29 when I run 'npm install'.
I assume that the error occurs because of the version of babel. But I can not solve the problem by install latest version of babel.

**Comment by gijoehosaphat** [comment] 2016-02-04 15:39
@asd123freedom I also got this upon upgrading. I tried clearing babel cache and the react native packager cache. It wasn't until I literally rebooted that it was resolved. 

Not the most concrete solution I understand, but this is eventually what solved it for me. I suspect there was something being cached somewhere in $TMP but couldn't track it down.

**Comment by asd123freedom** [comment] 2016-02-04 15:52
@gijoehosaphat Thanks a lot. I will try it as soon as possible

**Comment by skevy** [comment] 2016-02-04 16:30
@asd123freedom @gijoehosaphat the best way to make sure the packager cache is cleared is by doing:

```bash
watchman watch-del-all
[packager command] --reset-cache
```

**Comment by niftylettuce** [comment] 2016-02-04 19:43
For me, the fix was getting rid of `es-2015` as a preset in my `.babelrc` file, thanks @skevy

**Comment by bestander** [comment] 2016-02-05 11:11
@gijoehosaphat was the problem solved?

**Comment by gijoehosaphat** [comment] 2016-02-05 12:06
I ended up not having to change any code in the project, and continue to use stage-0, es2015 and react babel presets. I believe it was just cache causing a conflict.

**Comment by bestander** [comment] 2016-02-05 12:09
cc @asd123freedom good to close?

**Comment by asd123freedom** [comment] 2016-02-05 12:43
@bestander Because of Chinese new year I am in a vacation not having my mac aside. I  will  try the solution @gijoehosaphat  suggested when I come back from vacation. So it's good to close. Thanks a lot.

**Comment by bestander** [comment] 2016-02-05 12:50
:+1: reopen if it is still an issue

**Comment by mikepugh** [comment] 2016-02-19 14:20
I'm now running into this issue with v0.19.0, so I tried upgrading to v0.20.0 but I still run into the issue.

Newly init'd projects work fine, but a project I started about a week ago is broken. I've tried all of the above suggestions with no luck. 

This morning I've done the following:
`rm -rf node_modules/`
`watchman watch-del-all`
`npm cache clean`
I then removed all dev and regular dependencies from package.json except for `react-native@0.20.0`
`npm install`
`react-native run-ios`

And it still comes up with the undefined `babelHelpers.typeof` exception.

I was able to take my application specific code and basically dump that into a newly init'd project and it runs fine. I'd still like to know why my original repo is hosed though, and fix if possible.

**Comment by bestander** [comment] 2016-02-19 14:47
what does your package.json look like?

**Comment by mikepugh** [comment] 2016-02-19 16:21
I took it down to its bare minimum, trying to replicate a fresh `react-native init`.

```
{
  "name": "testApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",    
  },
  "dependencies": {
    "react-native": "0.20.0"    
  }
}
```

Previously there was more (See below), but I spent several hours adding and removing package dependencies to try and figure out if one of them was the problem. One step I did take last night was to `react-native init` a new app, and then one by one add the dependencies seen below and after each one I ran the simulator. I was able to get my app running in the simulator this way, so I'm at a loss for what might be the root cause in my original repo folder.

```
{
  "name": "testApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "remotedev": "remotedev --hostname=localhost --port=8000",
    "test": "mocha --compilers js:babel-register --require  ./test/test_helper.js --require babel-polyfill --recursive || true"
  },
  "dependencies": {
    "firebase": "2.4.0",
    "geofire": "3.2.4",
    "history": "2.0.0",
    "immutable": "3.7.6",
    "ramda": "0.19.1",
    "react-addons-pure-render-mixin": "0.14.7",
    "react-native": "0.20.0",
    "react-native-drawer": "1.15.0",
    "react-native-geocoder": "0.3.1",
    "react-native-maps": "0.3.0",
    "react-native-router-flux": "2.2.0",
    "react-redux": "4.4.0",
    "redux": "3.3.1",
    "redux-saga": "0.7.0",
    "redux-thunk": "1.0.3",
    "reselect": "2.0.3"
  },
  "jscsConfig": {
    "maximumLineLength": null
  },
  "devDependencies": {
    "babel-cli": "6.5.1",
    "babel-plugin-transform-regenerator": "6.5.2",
    "babel-polyfill": "6.5.0",
    "babel-preset-es2015": "6.5.0",
    "babel-register": "6.5.2",
    "chai": "3.5.0",
    "chai-immutable": "1.5.3",
    "mocha": "2.4.5",
    "remote-redux-devtools": "0.1.2",
    "remotedev-server": "0.0.3"
  }
}
```

**Comment by Kureev** [comment] 2016-02-19 16:37
@mikepugh 
```
$ npm cache clean
``` 
is something different from 
```
[packager command] --reset-cache
```
Try to run 
```
$ ./node_modules/react-native/packager/packager.sh start --resetCache
``` 
from your application folder first.

**Comment by mikepugh** [comment] 2016-02-19 17:02
@Kureev - ok thanks for the tip, I'll try that out once I'm back on that machine this afternoon. 

I don't have a .babelrc file, I did have a "babel" section within package.json which loaded the `es2015` preset, but it's missing at the moment due to all of the recent meddling.

**Comment by mikepugh** [comment] 2016-02-19 22:23
@Kureev awesome - the --reset-cache fixed it.

**Comment by Kureev** [comment] 2016-02-19 22:28
@mikepugh I'm glad it helped you.

**Comment by prasanthu** [comment] 2016-02-22 20:40
I have the same problem for a fresh clean project created the project using
`react-native init`

**Comment by lifehackett** [comment] 2016-02-23 16:05
I've tried all the above suggestions and am still running into this problem. `Uncaught TypeError: babelHelpers.typeof is not a function`
Node v4.3.1
NPM v3.7.3

I've been running 
`npm run reset`
`node node_modules/react-native/local-cli/cli.js run-ios --reset-cache`

```
{
  "name": "mobile_moderation",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "remotedev": "remotedev --hostname=localhost --port=8000",
    "reset": "rm -rf node_modules/ && npm cache clear && watchman watch-del-all && rm -rf $TMPDIR/react-* && npm i",
    "start": "node node_modules/react-native/local-cli/cli.js start --reset-cache",
    "test": "mocha --compilers js:babel-core/register --require ./test/test-helper.js --recursive",
    "test:watch": "npm run test -- --watch --watch-extensions jsx"
  },
  "babel": {
    "presets": [
      "es2015",
      "stage-2"
    ],
    "plugins": [
      "transform-regenerator",
      "transform-flow-strip-types"
    ]
  },
  "dependencies": {
    "immutable": "^3.7.6",
    "ramda": "^0.19.1",
    "react": "^0.14.7",
    "react-native": "^0.20.0",
    "react-redux": "^4.4.0",
    "redux": "^3.3.1",
    "redux-saga": "^0.8.2",
    "reselect": "^2.0.3"
  },
  "devDependencies": {
    "babel-cli": "^6.5.1",
    "babel-core": "^6.5.2",
    "babel-plugin-transform-flow-strip-types": "^6.5.0",
    "babel-plugin-transform-regenerator": "^6.5.2",
    "babel-polyfill": "^6.5.0",
    "babel-preset-es2015": "^6.5.0",
    "babel-preset-stage-2": "^6.5.0",
    "chai": "^3.5.0",
    "chai-immutable": "^1.5.3",
    "mocha": "^2.4.5",
    "remotedev-server": "0.0.3"
  }
}
```

**Comment by xuezhma** [comment] 2016-02-25 03:40
@prasanthu @lifehackett 
I was just having the same problem. 
What I did were:
```
$npm uninstall -g react-native-cli
$brew update && brew upgrade
$npm uninstall -g react-native-cli
```
I'm at
```
$ node -v
v5.6.0
$ react-native -v
react-native-cli: 0.1.10
react-native: 0.20.0
```

**Comment by sambarboza** [comment] 2016-02-25 12:44
Did what @xuezhma told but it didn't fixed for me, any other solution? Thanks!

**Comment by Kureev** [comment] 2016-02-25 16:10
@lifehackett @sambarboza Can you please share your `.babelrc` configs? (if you already tried to run a packager with `--reset-cache` option)

**Comment by sambarboza** [comment] 2016-02-25 16:17
@Kureev are theses .babelrc configs global or per project? On the project folder I don't have this file. I've tried to run the packager command with --reset-cache.

**Comment by lifehackett** [comment] 2016-02-25 16:33
@Kureev I wasn't using a `.babelrc` config in my original post.  The babel transforms were applied in my `package.json` https://github.com/facebook/react-native/issues/5747#issuecomment-187765275

I have tried this setup as well and gotten the same results.

.babelrc
```
{
    "extends": "react-native/packager/react-packager/.babelrc"
}
```

package.json
```
{
  "name": "TestProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "remotedev": "remotedev --hostname=localhost --port=8000",
    "reset": "rm -rf node_modules/ && npm cache clear && watchman watch-del-all && rm -rf $TMPDIR/react-* && npm i",
    "start": "node node_modules/react-native/local-cli/cli.js start --reset-cache & sudo dtruss -fn node",
    "test": "mocha --compilers js:babel-core/register --require ./test/test-helper.js --recursive",
    "test:watch": "npm run test -- --watch --watch-extensions jsx"
  },
  "dependencies": {
    "immutable": "^3.7.6",
    "ramda": "^0.19.1",
    "react": "^0.14.7",
    "react-native": "^0.20.0",
    "react-redux": "^4.4.0",
    "redux": "^3.3.1",
    "redux-saga": "^0.8.2",
    "reselect": "^2.0.3"
  },
  "devDependencies": {
    "babel-cli": "^6.5.1",
    "babel-plugin-transform-flow-strip-types": "^6.5.0",
    "babel-plugin-transform-regenerator": "^6.5.2",
    "babel-preset-es2015": "^6.5.0",
    "babel-preset-stage-2": "^6.5.0",
    "chai": "^3.5.0",
    "chai-immutable": "^1.5.3",
    "mocha": "^2.4.5",
    "remote-redux-devtools": "^0.1.2",
    "remotedev-server": "0.0.3"
  }
}

```

**Comment by Kureev** [comment] 2016-02-25 16:40
@lifehackett you shouldn't extend react-native's babelrc file. Try using this https://github.com/facebook/react-native/tree/master/babel-preset instead of es2015 and stage-2.

**Comment by lifehackett** [comment] 2016-02-25 16:47
@Kureev Same result

**Comment by sambarboza** [comment] 2016-02-25 16:59
@lifehackett @Kureev same thing here.

**Comment by JAStanton** [comment] 2016-02-25 18:19
I had been running into this issue for the last few days, just solved this by switching the `es2015` preset from my `.babelrc` with `react-native` and then running `react-native start --reset-cache`. My `.babelrc` file looks like this now:

```json
{
  "presets": ["stage-1", "stage-2", "stage-3", "react-native"],
  "plugins": ["transform-decorators-legacy"],
}
```

and my `package.json` looks like this:

```json
{
  "private": true,
  "name": "[REDACTED]",
  "version": "0.0.0",
  "scripts": {
    "authenticate": "scripts/authenticate",
    "bundle": "scripts/bundle:js",
    "bundle:js": "scripts/bundle:js",
    "clean": "scripts/clean:cache && scripts/clean:deps",
    "clean:cache": "scripts/clean:cache",
    "clean:deps": "scripts/clean:deps",
    "postinstall": "scripts/postinstall",
    "provision": "scripts/provision",
    "publish": "scripts/publish",
    "publish:all": "scripts/publish demo && scripts/publish production",
    "publish:sourcemap": "scripts/publish:sourcemap",
    "publish:codepush": "scripts/publish:codepush",
    "shrinkwrap": "npm-shrinkwrap",
    "start": "scripts/start",
    "start:ios": "scripts/start:ios",
    "test": "mocha --require babel/register"
  },
  "dependencies": {
    "google-libphonenumber": "1.0.7",
    "js-quantities": "1.6.0",
    "lodash": "3.10.1",
    "moment-timezone": "0.4.1",
    "numeral": "1.5.3",
    "pluralize": "1.2.1",
    "raven-js": "1.3.0",
    "react-addons-shallow-compare": "0.14.0",
    "react-addons-update": "0.14.0",
    "react-mixin": "3.0.0",
    "react-native": "0.20.0",
    "react-native-audioplayer": "0.2.0",
    "react-native-background-geolocation": "0.3.3",
    "react-native-code-push": "1.7.3-beta",
    "react-native-file-upload": "1.0.4",
    "react-native-image-picker": "marcshilling/react-native-image-picker#5720a18",
    "react-native-mixpanel": "0.0.7",
    "react-native-orientation": "JAStanton/react-native-orientation#340a0ba",
    "react-native-scrollable-tab-view": "0.3.7",
    "react-native-side-menu": "0.18.0",
    "react-native-vector-icons": "1.2.1",
    "react-timer-mixin": "0.13.3",
    "redux": "3.3.1",
    "redux-thunk": "1.0.3",
    "shallowequal": "0.2.2",
    "url": "0.11.0"
  },
  "devDependencies": {
    "babel-plugin-transform-decorators-legacy": "1.3.4",
    "babel-preset-react-native": "1.4.0",
    "babel-preset-stage-1": "6.5.0",
    "babel-preset-stage-2": "6.5.0",
    "babel-preset-stage-3": "6.5.0",
    "code-push-cli": "1.5.0-beta",
    "ios-sim": "5.0.6",
    "mocha": "2.3.3",
    "react-native-cli": "0.1.10",
    "sinon": "1.17.1"
  }
}
```

I am on node-version: `v4.1.0`
I am on npm version: `2.14.3`
I installed all my dependencies with `npm3 install`.

**Comment by Kureev** [comment] 2016-02-25 18:24
@JAStanton I already recommended @lifehackett and @sambarboza to replace es2015 by react-native preset and clear the cache, but seems they have the same problem still.

P.S. You can remove stage-2 and stage-3 from your config, stage-1 includes 2nd and 3rd stages by default

**Comment by JAStanton** [comment] 2016-02-25 18:34
@Kureev oh! Thanks :)

Could it be that another one of their presets includes `es2015`? Correct me if I'm wrong but the `babel.typeof` source code is coming from whatever code `es2015` includes. Remove that and that code isn't even in your source. IMO they still have the old cache sticking around somehow. Anyways thats my $0.02 if it helps any.

**Comment by sambarboza** [comment] 2016-02-25 20:31
Thanks guys! With @JAStanton and @Kureev tip's to use stage-1, was already using react-native preset, added stage-1 and it worked.

**Comment by JAStanton** [comment] 2016-02-25 20:45
huzzah! Glad to hear it!

**Comment by Kureev** [comment] 2016-02-25 21:32
Hey, glad that it helped! :+1:

**Comment by mikepugh** [comment] 2016-02-26 03:09
There's something unsettling about the number of different 'solutions' to this issue, and how they don't seem to work reliably for everybody.

**Comment by drewsbrew** [comment] 2016-02-26 19:09
Following this thread as well as I'm getting the same `babelHelpers.typeof ` error mentioned above and haven't had success with any suggestions. 

I tried adding `stage-1` to my `.babelrc` presets, cleared cache, etc. with no luck running:
`node v4.3.1`
`npm v3.7.5`

App is running `react-native v0.20.0`.

**Comment by lifehackett** [comment] 2016-02-26 19:41
I have some more data points.

1. Created a new repo. Ran without errors
2. Added some dependencies (none babel related). Ran without errors
3. I used a destructuring import statement `import { actionTypes } from ../constants`. Got an error that `actionTypes` is undefined

Conclusion: Doesn't know how to handle destructuring.

4. Shutdown server and emulator
5. `rm -rf node_modules/`
6. `npm clear cache`
7. `npm i`
8. `npm i --save-dev babel-preset-react-native`
9. Added `"babel": { "presets": ["react-native"] }` to `package.json`
10. `watchman watch-del-all`
11. `node node_modules/react-native/local-cli/cli.js run-ios --reset-cache`
12. Still get error about `actionTypes` being undefined

I looked at `babel-preset-react-native` and it depends on `babel-plugin-transform-es2015-destructuring` which would seem like it would handle my scenario.  The conclusion I am therefore drawing is that my preset definition is not getting picked up/recognized.  This seems to jive with the "fixes" people have been identifying and the idea that there is some sort of caching issue, but none of the methods I used above fixed the problem.  It seems like the cache issue could be internal to `react-native`.

For completeness
node- 4.3.1
npm- 3.7.5

```
{
  "name": "fresh",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "babel": {
    "presets": ["react-native"]
  },
  "dependencies": {
    "immutable": "^3.7.6",
    "ramda": "^0.19.1",
    "react": "^0.14.7",
    "react-native": "^0.20.0",
    "react-redux": "^4.4.0",
    "redux": "^3.3.1",
    "redux-saga": "^0.9.1",
    "reselect": "^2.0.3"
  },
  "devDependencies": {
    "babel-preset-react-native": "^1.4.0"
  }
}
```

**Comment by whusted** [comment] 2016-02-26 20:30
+ 1

**Comment by Apercu** [comment] 2016-02-29 00:53
Also getting this error with 0.20 (node 5.7 & npm 3.6), tried both with es2015 and react-native presets with a clear-cache didn't fix the issue on my side (axios package).

**Comment by elementalvoid** [comment] 2016-02-29 19:40
Same problems here. Initializing a brand new project then adding Babel with es2015 and stage-2 results in the error. I've cleared npm cache, uninstalled (local and global) node_modules, the entire node installation, and used the --reset-cache option. I've also tried using dropping 'es2015' in favor of 'react-native' as suggested earlier.

**Comment by gobadiah** [comment] 2016-03-01 15:36
Same here, tried everything as well and I still have the error, latest versions everywhere.

**Comment by nevir** [comment] 2016-03-02 03:58
> Same problems here. Initializing a brand new project then adding Babel with es2015 and stage-2 results in the error. 

It's a fun windy path, but I think I have an explanation:

* The `es2015` preset includes `transform-es2015-typeof-symbol`
* `transform-es2015-typeof-symbol` transforms all `typeof` comparisons into a call to `babelHelpers.typeof`
* The react packager bundles its [own implementation of `babelHelpers`](https://github.com/facebook/react-native/blob/master/packager/react-packager/src/Resolver/polyfills/babelHelpers.js), which does not include an implementation of `typeof` (and several other helpers defined in [Babel's implementation](https://github.com/babel/babel/blob/master/packages/babel-helpers/src/helpers.js))
* From what I can tell, you can't hook into the load process early enough to monkey patch the packager's implementation w/ missing methods from the official implementation

**Comment by shangsunset** [comment] 2016-03-03 02:53
Having the same problem here. Tried the fix other people suggested but when i put `react-native` in `.babelrc` instead of `es2005`, i got error:
```
/Users/shangyeshen/Sites/cairn/node_modules/react-native/Libraries/react-native/react-native.js:114
  ...require('React'),
  ^^^

SyntaxError: Unexpected token ...
```

and when added `stage-1` to `.babelrc`, got error:
```
Error: Couldn't find preset "stage-1" relative to directory "/path/to/project"
```

.babelrc
```
{
  "presets": [
    "stage-1",
    "react-native"
  ]
}
```

this is my package.json:
```javascript
{
  "name": "app",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "server": "nodemon index.server.js",
    "test": "PORT=3001 mocha --compilers js:babel-core/register server/tests"
  },
  "dependencies": {
    "body-parser": "^1.15.0",
    "express": "^4.13.4",
    "express-session": "^1.13.0",
    "jsonwebtoken": "^5.7.0",
    "mocha": "^2.4.5",
    "mongoose": "^4.4.3",
    "morgan": "^1.7.0",
    "react-native": "^0.19.0",
    "react-native-fbsdkcore": "0.0.8",
    "react-native-fbsdklogin": "0.0.8",
    "react-redux": "^4.4.0",
    "redux": "^3.3.1",
    "redux-logger": "^2.5.0",
    "redux-thunk": "^1.0.3",
    "supertest": "^1.2.0"
  },
  "devDependencies": {
    "babel-core": "^6.5.2",
    "babel-preset-es2015": "^6.5.0",
    "nodemon": "^1.8.1",
    "supertest": "^1.2.0"
  }
}
```

**Comment by Apercu** [comment] 2016-03-03 03:02
@shangsunset Please leave this issue clean, the error message should be obvious about what your problem really is.

**Comment by lifehackett** [comment] 2016-03-03 15:08
I just upgraded to the newly released `react-native@0.21.0` and am no longer experiencing the issue.  I'll hold off on declaring the issue resolved as some of the "fixes" listed in this thread have provided temporary relief only to have the error resurface.  I suggest other try upgrading.  I'll update in a few days.  These commits stood out as potential fixes

https://github.com/facebook/react-native/commit/a72c295
https://github.com/facebook/react-native/commit/727a2a9

**Comment by gavin1990** [comment] 2016-03-04 08:39
I just upgraded version 0.21.0 but also appeared the problem....

**Comment by gobadiah** [comment] 2016-03-04 15:54
After upgrading to 0.21.0 I also still have the problem.

**Comment by lifehackett** [comment] 2016-03-04 16:13
@gobadiah You said you are using "Latest versions everywhere". Does that mean 5.x? I'm using 4.3.1.  
@gavin1990 What node version are you using?

**Comment by gobadiah** [comment] 2016-03-04 16:20
@lifehackett Yes node 5.7.0, I'm trying to find out now what's going on. If I don't succeed I'll reverse to 4.3.1 to see what happens.

**Comment by gobadiah** [comment] 2016-03-04 16:56
There are other issues regarding babelHelpers. I followed [this comment](https://github.com/facebook/react-native/issues/4844#issuecomment-191282653) by @justinr1234 .

It simply suggests ... to edit the babelHelper file and add the code needed. In our case, edit the file 

    vim node_modules/react-native/packager/react-packager/src/Resolver/polyfills/babelHelpers.js 

add these lines :

    babelHelpers.typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) {
      return typeof obj;
    } : function (obj) {
      return obj && typeof Symbol === "function" && obj.constructor === Symbol ? "symbol" : typeof obj;
    };

After babelHelpers definition ( `var babelHelpers = global.babelHelpers = {};`)

Hopefully this will be integrated in future versions.

**Comment by gavin1990** [comment] 2016-03-08 04:14
@lifehackett node  v5.6.0

**Comment by emroot** [comment] 2016-03-18 02:06
same here, having the issue on my end as well. probably worth re-opening the issue since it seems to affect people still. I tried to update `babelHelpers.js` with this:
``` javascript
babelHelpers.typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) {
  return typeof obj;
} : function (obj) {
  return obj && typeof Symbol === "function" && obj.constructor === Symbol ? "symbol" : typeof obj;
};
```
no luck...
cleared my npm cache, nuked my node_modules dir, re-cloned my repo, no luck. help will be greatly appreciated.

**Comment by justinr1234** [comment] 2016-03-18 03:08
@emroot did you try my comment on this page: https://github.com/facebook/react-native/issues/4844#issuecomment-191282653

**Comment by lifehackett** [comment] 2016-03-18 13:04
Although upgrading to `react-native@0.21` initially resolved the issue for me, it has returned.  I'll try @justinr1234 hack, but I think this needs to be addressed at the core.

**Comment by emroot** [comment] 2016-03-18 16:23
@justinr1234 yeah it's already in my .babelrc
I tried doing this too, just in case if any other .babelrc file would screw things up.
find node_modules -type f -name .babelrc | grep -v /react-native/ | xargs rm
Everything was working fine until I installed https://www.npmjs.com/package/react-native-push-notification, that when I started getting the error. I then removed the packages and the issue sticked. I tried deleting node_modules, clear npm cache, run with --reset-cache, downgrade react-native to 0.20 (I am running on `0.21). No luck. I'm debating in reinstalling npm from scratch.

here's a backtrace of the error if this helps:
![error](http://cl.ly/2w0b1M311r09/download/Screen%20Recording%202016-03-17%20at%2009.15%20PM.gif)

**Comment by justinr1234** [comment] 2016-03-18 16:51
@lifehackett any luck?

@emroot did you specifically try modifying the babelHelpers.js file in your node_modules here:  https://github.com/facebook/react-native/blob/master/packager/react-packager/src/Resolver/polyfills/babelHelpers.js

And replace it with your own generated by following directions here:  http://stackoverflow.com/a/34943779/3096547

I'm confused by what you said, because it sounds like you followed a different (probably equivalent) method. I'm no expert on the situation, but the steps I outlined are the only way I was able to fix my errors.

**Comment by emroot** [comment] 2016-03-18 17:20
@justinr1234 yeah I did it last, see my previous comment [here](https://github.com/facebook/react-native/issues/5747#issuecomment-198163620).

**Comment by gm758** [comment] 2016-03-18 18:47
This error has been holding up my team for the last 2 days. My local repo currently works as expected, but several of my teammates have had this issue arise (seemingly out of nowhere). When I push my repo up to github, pull down a fresh copy, and try to run the project from there, I get the error as well. But my local repo still works fine.

Would really appreciate any help!

**Comment by justinr1234** [comment] 2016-03-18 19:27
@gm758 Have you tried archiving your working install and sending to someone on your team?

**Comment by gm758** [comment] 2016-03-18 21:23
@justinr1234 I did, but with no luck. Even when I copy the repo into a new directory on my computer, this error pops up.

**Comment by lifehackett** [comment] 2016-03-21 15:43
@justinr1234 applying your fix did NOT resolve the error in my case.

**Comment by lifehackett** [comment] 2016-03-21 15:55
The work around I have been doing and seems to consistently work is to `react-native init` a new project and then copy over my files from the broken project into the new one.  This is certainly not ideal especially from a VC perspective.

**Comment by justinr1234** [comment] 2016-03-21 16:45
@lifehackett what other debugging steps did you take from this thread? That sounds like it could be a cache issue maybe...

**Comment by lifehackett** [comment] 2016-03-21 18:06
@justinr1234 I've tried every single one mentioned in this and any other threads I can find.  Some of my earlier posts on this issue detail them.

**Comment by gm758** [comment] 2016-03-21 18:26
After cleaning my build folder and restarting my computer due to an unrelated issue, I am now getting this error like the rest of my team. Apparently whatever was keeping my safe from this bug is gone now. We've pretty much had to revert to not using babel at all, which precludes doing any testing in ES6+ or defining our own presets. 

I know of at least 2 other teams working with react native who've been hamstrung by this error. I think this issue should reopened.

**Comment by iandeboisblanc** [comment] 2016-03-21 18:34
I was having the same issue. I tried most of the techniques on this page without luck. 
I was finally able to fix it, but I had to remove all babel dependencies. Here are the steps I took:

npm uninstall everything with the word 'babel' (not sure if this is strictly necessary, but I was fed up)
npm install (to re-include the babel dependencies required by react-native)

/node_modules/react-native/packager/packager.sh start --reset-cache 
  --to get this to work, i actually had to run 'lsof -i :8081' and kill the PID using that port before

**Comment by balanceiskey** [comment] 2016-03-22 13:40
I was running into this issue last night. Some combination of `--reset-cache` and removing `stage-1` and `es2015` presets from my .babelrc seems to have resolved it. My .babelrc only has the `react-native` preset now, which is fine for my use case but I imagine that might not fly for everyone.

**Comment by skevy** [comment] 2016-03-31 17:26
Hey everyone -

Please see this comment on how to possibly fix this issue (if you're trying to use babel-preset-react-native along with stage-0, stage-1, stage-2, or stage-3 presets).

https://github.com/facebook/react-native/issues/4844#issuecomment-204035720

Thanks,
-Adam

**Comment by ekryski** [comment] 2016-04-01 05:07
I'm with @balanceiskey. On RN 0.22.2 I removed `es2015` and `stage-0` presets and now only have the `react-native` presets. If I add either of the ones I removed I get the same error. Doesn't matter if you use `--reset-cache`, `npm cache clean` or not. I mean their may be lingering modules if you don't use those but the root is somewhere in using the `es2015` or `stage-0`/`stage1` presets I think.

**Comment by skevy** [comment] 2016-04-01 12:58
@ekryski you're correct. Please see the comment I linked to above.

**Comment by juanserra** [comment] 2016-04-01 13:29
I run into this problem, and after several hours of research and trial and error, the solution that worked for me was using @skevy's package. Massive thanks to you sir

**Comment by nikhildaga** [comment] 2016-04-09 21:15
still facing this issue

**Comment by satya164** [comment] 2016-05-05 11:10
Re-opening the issue. FYI I've only seen it happen when you've a dependency which is compiled using another preset other than `react-native`. It also happens if you've a `.babelrc` with a different preset under a subdirectory.

**Comment by jeffgran** [comment] 2016-06-01 22:45
@satya164 I experienced the same thing just now. I have a dependency that is compiled using different presets. I was able to get it working by (a) installing the presets that the dependency needs `npm install --save dev <whatever babel preset the error message says i'm missing>` and (b) DO NOT add that preset to your `.babelrc`. I was able to add whatever other babel transforms I needed by adding the specific transforms to my `.babelrc`, but it seems if you add any other *presets* you end up with this or a similar error.

**Comment by amallo** [comment] 2016-06-16 17:13
I had same problem with react-native 0.27.2 and `react-native start --reset-cache` works for me

**Comment by fab1an** [comment] 2016-06-21 09:46
I have the same problem with latest react-native and nothing works for me. Live Reloading works, but Bundling doesn't.

I tried
* removing ALL `.babelrcs` that I use
* deleting the caches (watchman and packager)
* removing all node_modules and reinstalling them

**Comment by fab1an** [comment] 2016-06-21 10:19
Ok, I got to another bottom of this: https://github.com/facebook/react-native/issues/7850#issuecomment-227398161

(right now the react package also picks up `.babelrc` of unrelated dependencies in `node_modules` and breaks things)

**Comment by af7** [comment] 2016-07-28 12:37
+1 Is there any resolution on this? 

The strange thing is that our Android app *does* work when on "DEBUG" mode but not when in "RELEASE" mode. I assume because the "iterator" works due to chrome dev tools being loaded?

**Comment by marcellosachs** [comment] 2016-09-30 20:05
The cause /solution in my case seems like it might be esoteric, but for the sake of completeness :  

I was using a node_module (that I had myself created), and that node_module did not have an `.npm_ignore` file, thus the `src` as well as the `.babelrc` file were being unnecessarily included in the module as it was downloaded.

I added the appropriate `.npm_ignore` file to that module, included `src` and `.babelrc` in that file, republished the module, re-installed the module in my react-native app, and the problem was solved.

**Comment by ivanakimov** [comment] 2016-10-05 20:22
`RN 0.33.0`, same issue, `./node_modules/react-native/packager/packager.sh start --reset-cache` does not seem to help.

**Comment by jeffgran** [comment] 2016-10-06 00:21
I believe @marcellosachs solution is correct. A dependency that has a `.babelrc` in it will cause that `.babelrc` to get picked up by the react native packager. @ivanakimov I would try to figure out which npm module is the one that has a `.babelrc` in it (maybe like `find ./node_modules -name .babelrc`) and see if that can be removed or fixed.

**Comment by THIAGOWESLLEY2** [comment] 2016-10-06 00:44
Um pouco de Like

Em 05/10/2016 21:23, jeffgran <notifications@github.com> escreveu:

I believe @marcellosachs<https://github.com/marcellosachs> solution is correct. A dependency that has a .babelrc in it will cause that .babelrc to get picked up by the react native packager. @ivanakimov<https://github.com/ivanakimov> I would try to figure out which npm module is the one that has a .babelrc in it (maybe like find ./node_modules -name .babelrc) and see if that can be removed or fixed.

**Comment by ivanakimov** [comment] 2016-10-06 17:56
@jeffgran this is what I get when searching for `.babelrc`:

```
./node_modules/babel-preset-react-native/node_modules/babel-plugin-react-transform/.babelrc
```

(everything else is either in "test" or "lint" folders, I'm guessing those don't count?)

**Comment by jeffgran** [comment] 2016-10-10 01:51
Huh. I don't know. My issue definitely seemed to be resolved when I figured out that multiple (incompatible) .babelrc files were being picked up. Maybe there are multiple causes of this issue.

**Comment by hellogerard** [comment] 2016-10-12 14:34
Interestingly, I came here because I started getting this error after installing my npm dependencies with [yarn](https://github.com/yarnpkg/yarn). Using npm works fine. Installing with yarn, and then running my React Native project results in this error.

**Comment by ivanakimov** [comment] 2016-10-12 17:22
@hellogerard same. Tested yarn, it didn't install everything properly, went back to npm. Too new.

**Comment by Simek** [comment] 2016-10-21 11:41
When this will be fixed or fix will be shipped/merged?

**Comment by lacker** [comment] 2016-12-17 00:52
At this point this thread appears to be a number of unrelated issues globbed together with the original one fixed. I am going to close this issue and encourage people who still have something similar to open a new issue with repro steps that are specific to their app. Thanks folks!

**Closed by lacker** 2016-12-17 00:52 UTC

**Comment by yordis** [comment] 2017-02-01 04:18
@lacker I am having this exact issue.

**Log**
`babelHelpers.typeof is not a function. (In 'babelHelpers.typeof(target)', 'babelHelpers.typeof' is undefined)`

**.babelrc**
```
{
"presets": ["env","react-native"],
"plugins": [],
"sourceMaps": true
}
```

**Deps**
```
    "react": "~15.4.0-rc.4",
    "react-native": "0.40.0",
    "react-native-checkbox": "^1.1.0",
    "react-native-elements": "^0.9.2",
    "react-native-vector-icons": "^4.0.0"
  },
  "devDependencies": {
    "babel-cli": "^6.22.2",
    "babel-eslint": "^7.1.1",
    "babel-jest": "18.0.0",
    "babel-preset-env": "^1.1.8",
    "babel-preset-react-native": "1.9.1",
    "eslint": "^3.14.0",
    "eslint-config-react-native": "^1.6.0",
    "eslint-plugin-flowtype": "^2.30.0",
    "flow-bin": "^0.36.0",
    "jest": "18.1.0",
    "react-test-renderer": "~15.4.0-rc.4"
  }
```

**Comment by erichua23** [comment] 2017-02-12 13:56
In my case, i forget to set presets in .babelrc, add "react-native" as preset in .babelrc works

**Comment by superquest** [comment] 2017-03-16 06:50
I just encountered this problem when adding the a dependency called redux-query.

Changing the [redux-query .babelrc](https://github.com/amplitude/redux-query/blob/v1.2.0/.babelrc) from:

```
{
    "presets": ["react", "es2015", "stage-2"]
}
```

To:

```
{
    "presets": ["react", "react-native", "stage-2"]
}
```

Made problem go away.
