### ISSUE TITLE
Error: bundling failed: Error: Unable to resolve module `./../react-transform-hmr/lib/index.js` in react-native version "0.57.2"

### ISSUE THREAD

**Issue by divyangsolanki** [facebook/react-native#21511] opened 2018-10-05 09:22 UTC
## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
      Memory: 498.90 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.4 - /usr/local/bin/node
      Yarn: 1.5.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.2 => 0.57.2 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
When ever i try to run the app it throws this error if same code i run in react-native 0.55.4 version it works fine. I have just made new application using " react-native init test " command and run it in IOS but it gives this error. I haven't included my code and packages in it.
I tried so many ways to solve but cant solve it.
**Error Detail:**
error: bundling failed: Error: Unable to resolve module `./../react-transform-hmr/lib/index.js` from `/ReactNative/UsermanagementNav/App.js`: The module `./../react-transform-hmr/lib/index.js` could not be found from `/ReactNative/UsermanagementNav/App.js`. Indeed, none of these files exist:
  * `/ReactNative/react-transform-hmr/lib/index.js(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
  * `/ReactNative/react-transform-hmr/lib/index.js/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
    at ModuleResolver.resolveDependency (/ReactNative/UsermanagementNav/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:209:697)
    at ResolutionRequest.resolveDependency (/ReactNative/UsermanagementNav/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:83:16)
    at DependencyGraph.resolveDependency (/ReactNative/UsermanagementNav/node_modules/metro/src/node-haste/DependencyGraph.js:222:485)
    at Object.resolve (/ReactNative/UsermanagementNav/node_modules/metro/src/lib/transformHelpers.js:149:25)
    at dependencies.map.result (/ReactNative/UsermanagementNav/node_modules/metro/src/DeltaBundler/traverseDependencies.js:316:29)
    at Array.map (<anonymous>)
    at resolveDependencies (/ReactNative/UsermanagementNav/node_modules/metro/src/DeltaBundler/traverseDependencies.js:312:16)
    at /ReactNative/UsermanagementNav/node_modules/metro/src/DeltaBundler/traverseDependencies.js:169:33
    at Generator.next (<anonymous>)
    at step (/ReactNative/UsermanagementNav/node_modules/metro/src/DeltaBundler/traverseDependencies.js:271:307)

**Comment by kelset** [comment] 2018-10-05 10:14
Duplicate of https://github.com/facebook/react-native/issues/21490

**Closed by kelset** 2018-10-05 10:14 UTC
Labels: 📦Bundler
