### ISSUE TITLE
Fetch is not working

### ISSUE THREAD

**Issue by PerfectJoy** [facebook/react-native#12128] opened 2017-01-31 06:28 UTC
--- Please use this template, and delete everything above this line before submitting your issue --- 

### Description

Fetch is not working when request.
`try {
fetch(url).then((response) => response.json()).then((responseJson) => {
      // responseJson with some functions
      })
      .catch((error) => {
        console.error("REQ ERROR::: " + error);
      });
} catch(ex) {
   console.log(ex.message);
}
`
it always goes to exception which says 
"E/ReactNativeJS( 1853): undefined is not an object (evaluating 'self.fetch')   
 E/ReactNativeJS( 1853): Requiring module "349", which threw an exception.       
E/ReactNativeJS( 1853): undefined is not an object (evaluating 'require(349 /* fetch */).fetch')                                                                
"

### Additional Information

* React Native version: [0.40.0]
* Platform: [Android]
* Operating System: [Windows]

**Comment by petrbela** [comment] 2017-02-05 23:14
Duplicate of #9599?

**Comment by hramos** [comment] 2017-07-26 05:45
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Closed by hramos** 2017-07-26 05:45 UTC
Labels: Icebox
