### ISSUE TITLE
[WebView] Is it possible to load local js file in WebView html prop?

### ISSUE THREAD

**Issue by bright-sea** [facebook/react-native#1442] opened 2015-05-29 07:30 UTC
For Example, I put a web/jquery.js file in bundle, then I would like to use:

    var html=`
    <html>
    <script src="web/jquery.js"></script>
    ...`;

then use WebView to set html prop to html.

I tried to set src to jquery in CDN, it works fine. but don't work with above code. 

Is it because currently local js in WebView not be supported? Or I miss something at here?

**Comment by JohnyDays** [comment] 2015-05-29 08:47
I'm not sure you can do this, but if you can you would use a file:// protocol, which you would grab from the following snippet (I'm assuming jquery.js is in your xcode project)
````objective-c
NSUrl *jqueryLocation = [[NSBundle mainBundle] urlForResource:@"jquery" withExtension:@"js"];
````

That would return a uri with something like file://something/Devices/abcd-123/caches/bundle/jquery.js which is the absolute path on the device/emulator after compiling your app

**Comment by brentvatne** [comment] 2015-05-29 17:24
@bright-sea - I think what we want here is something like:

`<WebView url="web/index.html" />`

Then we just check if the url is http http or not - if not, we do [something like this](http://stackoverflow.com/a/5810930/659988)

Do you want to try submitting a patch for that? cc @JohnyDays

**Comment by JohnyDays** [comment] 2015-05-29 19:12
@brentvatne I don't have access to a MAC over the weekend, if noone takes it up until monday I'll give it a shot.
However I don't think that's what @bright-sea was asking for! His question was more about requiring a <script> tag inside of the html(which is inlined and dynamically generated), where the source script was a file required inside the app bundle. Though perhaps you just explained how to do that and I misunderstood.

**Comment by bright-sea** [comment] 2015-05-29 19:15
@brentvatne  - set url or html to an local html file is what I want. What I need to put some js files(css files and any other web assets) into bundle, then in html template we can use these files so that we can do any kinds of works from there.

@JohnyDays  - Thanks, your suggestion helps me. I use [react-native-fs](https://github.com/johanneslumpe/react-native-fs) to get the path of main bundle, then use list below code and it works fine:

    <script src="file://"+${mainBundlePath}+"web/jquery.js"></script>

 Of couse, if we can have this kinds of support in react native directly instead of depends on third party module would be great.

**Comment by brentvatne** [comment] 2015-05-29 19:17
@bright-sea - the second option I proposed would help:

`<WebView baseURL="/web" html={html} />`

By setting the baseURL, like in the [example I linked to on StackOverflow](http://stackoverflow.com/questions/5733883/loading-javascript-into-a-uiwebview-from-resources/5810930#5810930), the WebView knows where to look for the css/js that you link to :smile:

The `html` var I'm using there is just the same as what you used in your original post.

**Comment by brentvatne** [comment] 2015-05-29 19:18
@JohnyDays - that would be great! looking forward to seeing it when you have time.

Given that this issue has been solved for now I'll close this, but I hope to see a PR to add something like what I mentioned above to WebViews - I think that would be very useful.

**Closed by brentvatne** 2015-05-29 19:18 UTC
Labels: Good first task

**Comment by bright-sea** [comment] 2015-05-29 19:22
@brentvatne yes, you are right! Your proposal will be more elegant.

**Comment by JohnyDays** [comment] 2015-05-29 19:57
Oops apparently having a ````<script>```` tag in your comment hides the rest, apologies!

**Comment by gs-akhan** [comment] 2015-11-13 15:37
@bright-sea 
Hi. Your solution works like a chart. But would that work even App is packaged and deployed on a device ?
Thanks You..

**Comment by richardbrammer** [comment] 2016-03-05 16:30
If I package my app and view it on an iOS device, the asset files are not there. The only file, that is there, is the html file used by the WebView (and required). 
How can I make sure, the packager copies the *.js and *.css files to the asset directory?

**Comment by DanielApt** [comment] 2016-09-26 11:37
I have the same question as @richardbrammer. Any updates or guidance would be very welcome.

**Comment by qxqxqxqx** [comment] 2016-10-21 05:12
+1 on Android @richardbrammer .

**Comment by liuliangsir2016** [comment] 2016-11-13 12:29
+1 on Android

**Comment by matdru** [comment] 2017-04-12 07:14
+1 on Ios

**Comment by VishwajeetDagar** [comment] 2017-04-14 08:35
+1 on android

**Comment by AyubaMakoa** [comment] 2017-09-18 09:48
what is will like to ask is how to load a react base webapp on a webview. i think that is what he is asking ..

**Comment by brancooo1** [comment] 2017-10-09 20:02
How this can be closed, when people still are having issues with loading local html, css, js files, crossplatform in react-native :(  @brentvatne

**Comment by brentvatne** [comment] 2017-10-09 20:21
@brancooo1 - this isn't the right place for feature requests, if this hasn't been implemented it's because the contributors to the project don't need it for their apps. you can post a feature request to https://react-native.canny.io/feature-requests or implement it yourself or pay someone to implement it for you :)

**Comment by sujitpk-perennial** [comment] 2017-10-10 03:38
I am also facing the same issue. My .js .css files are loaded on simulator and it is working as expected. But those files are not loaded on iOS device. any help?

**Comment by sujitpk-perennial** [comment] 2017-10-10 14:02
After doing some R&D, for me expo was creating the issue. After uninstalling the expo from the app, app is working as expected. It looks like expo is ignoring the js, css files.

**Comment by 0xc0d3r** [comment] 2017-11-19 06:50
Hey guys!
I am also facing the same problem. Following is the my app folder structure.

```
<ProjectName>
  app
    Common
      assets
        fonts
        js
          myLocalFile.js
      components
      containers
      stores
      .
      .
      .
    Module1
      components
        WebViewComponent
          index.js    <- I'd like to import `myLocalFile.js` in html string and pass it to `WebView` 
    Module2
    Module3
    .
    .
   ```

In `WebViewComponent/index.js`,

```
const htmlString = '<head><script src="myLocalFile.js"></script></head><div>some html code</div>'

render() {
return (
<View style={styles.viewStyles}>
          <WebView
            source={{ html: htmlString, baseUrl: 'app/Common/assets/js/' }}
            scrollEnabled={false}
          />
        </View>
}
```

I am rendering above code and unable to execute my js code.

Any suggestions

**Comment by fedegl** [comment] 2017-11-27 22:25
I am facing the exact same problem, and haven't found any solutions online.

**Comment by sujitpk-perennial** [comment] 2018-01-22 13:02
I faced this issue multiple times. Each time it caused by different reason. 
1 - First time after removing of expo it works.
2 - I used let keyboard to declare a variable. let not support in Safari. I replaced it with var. 
3 - Need to add scripts in head for iOS and in body for Android.
4 - Specifically for iOS, if we need to run in release mode then we should create assets folder and need to add all images and js, css file at that path. 
    Refer: https://github.com/facebook/react-native/issues/4084
5 - Put alert into js file to check is it loading or not.

   Better to debug webView in Safari and chrome. Few times I found that some functions was giving errors.

**Comment by kirtjarmona** [comment] 2018-02-17 10:01
Do not use absolute path instead use relative path with dot(.) followed with the path. 
Like this:
`<script src="./js/jquery.js"></script>`
                     ^

**Comment by brainbrain34** [comment] 2018-04-16 14:58
The best solution is to encode the images in base 64 and works perfectly from the WebView.

**Comment by Arshiamidos** [comment] 2018-04-24 16:56
hey guys  
found the trick base on [Image doesn't show after bundling into the apk](https://github.com/facebook/react-native/issues/4084).   
as you know **require('index.html')** work on _simulator_ and _emulator_ for both &driod and IOS  
but problem will faced when you bundle and you want release your app   
for android just follow this  **enablejavascript**  and copy you files in **assets** folder in `YOUR_APP/app/src/main/assets` and use just picture below.  

and for ios just bundle package with 
`react-native bundle --entry-file index.ios.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios`
when bundle created you have **main.bundle.js** and **asset** folder   
just copy you files in  **.xcworkspace** like this image  
![ios](https://user-images.githubusercontent.com/6451804/39201543-963c2e00-4804-11e8-9031-fb87a9f2c46e.jpg)
and set free all **refrence** in will be and unchanged just like mine. 
![screen shot - - at](https://user-images.githubusercontent.com/6451804/39201713-1260aeac-4805-11e8-92dd-efd9209cb44f.png)
i hope this tutorial help you from confusing release app in RN
