### ISSUE TITLE
textTransform not working in  react-native

### ISSUE THREAD

**Issue by rahul-mutyalkar** [facebook/react-native#22599] opened 2018-12-11 08:52 UTC
- [yes ] Review the documentation: https://facebook.github.io/react-native
  - [ yes] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ yes] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.
React Native Environment Info:
    System:
      OS: Linux 4.13 Ubuntu 17.10 (Artful Aardvark)
      CPU: (4) x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
      Memory: 328.05 MB / 7.71 GB
      Shell: 4.4.12 - /bin/bash
    Binaries:
      Node: 11.0.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.2, 27.0.3, 28.0.0
        System Images: android-26 | Android TV Intel x86 Atom, android-26 | China version of Android Wear Intel x86 Atom, android-26 | Android Wear Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728 
      react-native: 0.57.5 => 0.57.5 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1

## Description
I am trying to use textTransform property in the <Text> but it is not working.The text inside <Text> gets hide when i add textTransform property in it.Please solve this issue for me.
## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, share a project, or     share an app that reproduces the issue using https://snack.expo.io/. Please follow the guidelines for providing a MCVE: https://stackoverflow.com/help/mcve

**Comment by sumitjr** [comment] 2018-12-11 10:54
seems like a duplicate of 21966

**Comment by sameersitre** [comment] 2018-12-28 21:17
same problem. it works in ios simulator but not working on any android os.
I think it is a new problem.

**Comment by rickhanlonii** [comment] 2018-12-31 16:10
Hey @rahul-mutyalkar, thanks for filing! Closing as a dupe of #21966

**Closed by rickhanlonii** 2018-12-31 16:10 UTC
Labels: 🔶Components, 🔶Text, 🔷Linux
