### ISSUE TITLE
Fails to run react-native run-android (v0.68.0) without yarn

### ISSUE THREAD

**Issue by pushpender-singh-ap** [facebook/react-native#33525] opened 2022-03-30 18:34 UTC
### Description

when I create a test project and enable new architecture and Hermes it's giving me this type error below:-

NOTE:- I KNOW I DON'T HAVE YARN (i love using npm that's why I don't install yarn in my system maybe this error is fixed after yarn install but it does not mean we can't run our project through npm)

```
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 936 file(s) to forward-jetify. Using 8 workers...
info JS server already running.
info Installing the app...

> Configure project :app
Unable to detect AGP versions for included builds. All projects in the build should use the same AGP version. Class name for the included build object: org.gradle.composite.internal.DefaultIncludedBuild$IncludedBuildImpl_Decorated.

> Task :ReactAndroid:generateCodegenSchemaFromJavaScript FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
9 actionable tasks: 1 executed, 8 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ReactAndroid:generateCodegenSchemaFromJavaScript'.
> A problem occurred starting process 'command 'yarn''

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ReactAndroid:generateCodegenSchemaFromJavaScript'.
> A problem occurred starting process 'command 'yarn''

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

    at makeError (/Users/pushpendersingh/Desktop/Projects/RN/testV68/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:174:9)
    at /Users/pushpendersingh/Desktop/Projects/RN/testV68/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/pushpendersingh/Desktop/Projects/RN/testV68/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/usr/local/lib/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.
```

### Version

0.68.0

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.3
    CPU: (8) arm64 Apple M1
    Memory: 89.94 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.3.1 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 28, 30, 31, 32
      Build Tools: 30.0.2, 32.0.0, 32.1.0, 33.0.0
      System Images: android-32 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 12.0.2 - /Library/Java/JavaVirtualMachines/jdk-12.0.2.jdk/Contents/Home/bin//javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.0 => 0.68.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. react-native init test
2. cd test
3. enable newArchEnabled=true (gradle.properties)
4. enable enableHermes: true (build.gradle)
5. react-native run-android (when the yarn is not installed on the system)

### Snack, code example, screenshot, or link to a repository

Github Repo:- https://github.com/pushpender-singh-ap/testV68

**Comment by cortinico** [comment] 2022-03-31 11:33
That's not expected. It's a bug in the setup of the New Architecture. Obviously installing yarn would fix it. @danilobuerger is working on a fix for this in https://github.com/facebook/react-native/pull/33530

**Closed** 2022-04-04 12:55 UTC
Labels: Resolution: PR Submitted, Platform: Android, New Architecture

**Comment by ItsCDubb** [comment] 2022-04-20 13:24
> 

Except I use yarn already & I'm getting the same error, so it has nothing do do with yarn

**Comment by ItsCDubb** [comment] 2022-04-20 16:48
> Hey @ItsCDubb, are you still seeing the same issue in the 0.68.1 release?

Yes I am & I don't know what it means in order to resolve it

**Comment by fortmarek** [comment] 2022-04-21 07:50
@ItsCDubb I think it would be the most transparent if you created a new issue with reproducible steps instead 🙏

**Comment by ranadawar** [comment] 2022-04-21 10:27
I'm using yarn and still facing the same error in v0.68.1. Any solution to solve the error? Because of this error unable to install the app neither in the emulator nor in android device

**Comment by pushpender-singh-ap** [comment] 2022-04-21 18:12
version `0.68.1` this issue has been `resolved`.

**Comment by FayyazAliKhan1** [comment] 2022-05-31 15:18
@pushpender-singh-ap  I am using 0.68.2 but it's still appearing, debug build not creating due to this

**Comment by pushpender-singh-ap** [comment] 2022-05-31 15:28
@FayyazAliKhan1 If you could send us screenshots with a sample repository, that would be helpful.

**Comment by palavellig** [comment] 2022-09-17 04:53
gradlew clean --stacktrace

> Configure project :app
Unable to detect AGP versions for included builds. All projects in the build should use the same AGP version. Class name for the included build object: org.gradle.composite.internal.DefaultIncludedBuild$IncludedBuildImpl_Decorated.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

  "react": "17.0.2",
    "react-native": "0.68.2",

any help??

**Comment by m7amad-7asan** [comment] 2022-10-20 08:10
getting build failed with the same error when trying to clean or build the app
gradlew clean or gradlew assembleRelease

react: 17.0.2
react-native: 0.68.2

anyone got this error resolved ?

**Comment by m7amad-7asan** [comment] 2022-10-20 08:39
@palavellig did you find any solution ?

**Comment by palavellig** [comment] 2022-10-20 08:42
Open Android Studio Settings,  then select Gradle JDK as version 11 from the dropdown.

![sckAv](https://user-images.githubusercontent.com/61959533/196900497-6394c542-f4cf-449f-aecc-a62d0fd3bfe0.png)

**Comment by palavellig** [comment] 2022-10-20 08:46
the solution which i answered was worked for me.

**Comment by m7amad-7asan** [comment] 2022-10-20 08:59
Thanks for your response

could you please tell how to get this screen

**Comment by Johnhollack** [comment] 2022-10-23 01:53
adding this to your eas.json resolves the problem for me: @m7amad-7asan

"build": {
  "production": {
        "android": {
          "buildType": "app-bundle",
          "image": "latest"
        }
      }
}

**Comment by m7amad-7asan** [comment] 2022-10-23 07:38
@Johnhollack

Thanks but I'm not using expo

**Comment by Mmferry** [comment] 2023-03-13 13:24
I'm facing same problem have anyone solved?

**Comment by pushpender-singh-ap** [comment] 2023-03-13 13:28
@Mmferry This issue fix in latest react native versions

**Comment by Mmferry** [comment] 2023-03-13 18:41
> @Mmferry This issue fix in the latest react native versions

Is it worked with expo 45

**Comment by pushpender-singh-ap** [comment] 2023-03-13 18:45
> > @Mmferry This issue fix in the latest react native versions
> 
> Is it worked with expo 45

Expo 45 is already deprecated use 48 and 47

**Comment by Mmferry** [comment] 2023-03-13 18:48
> > > @Mmferry This issue fix in the latest react native versions
> > 
> > 
> > Is it worked with expo 45
> 
> Expo 45 is already deprecated use 48 and 47

I'm just upgrading incrementally from expo 43 and wanna make sure it build successfully

**Comment by pushpender-singh-ap** [comment] 2023-03-13 18:51
> > > > @Mmferry This issue fix in the latest react native versions
> > > 
> > > 
> > > Is it worked with expo 45
> > 
> > Expo 45 is already deprecated use 48 and 47
> 
> I'm just upgrading incrementally from expo 43 and wanna make sure it build successfully 

Than upgrade to 46 because deprecated versions not run in expo go application

**Comment by Malik-Usman17** [comment] 2023-03-14 10:31
Still facing the same issue and i am not using expo, i am working react-native cli.
When i run my project on cmd by running this command **npx react-native run-android** or  **yarn react-native run-android**, 
it gave these errors.

**Comment by pushpender-singh-ap** [comment] 2023-03-14 15:22
@Malik-Usman17 can you tell us which react native version are you using
