### ISSUE TITLE
error       Unable to resolve module `AccessibilityInfo`？

### ISSUE THREAD

**Issue by QAQXiYangYang** [facebook/react-native#20444] opened 2018-07-29 07:53 UTC

**Comment by Tchanu** [comment] 2018-07-29 07:59
Duplicate of #4968

**Closed** 2018-07-29 08:05 UTC

**Comment by alexander0205** [comment] 2018-08-04 21:45
That is the solution step by step 
`https://stackoverflow.com/questions/51333897/react-native-build-error-development-server-returned-response-error-code-500/51360535`
