### ISSUE TITLE
Namespace not specified

### ISSUE THREAD

**Issue by priyaWedo** [facebook/react-native#38660] opened 2023-07-28 05:34 UTC
### Description

I specified namespace in android>app>build.gradle , still this error is occurring ! Anyone can please help how to resolve this !

android {
    ndkVersion rootProject.ext.ndk

    compileSdkVersion rootProject.ext.compileSdkVersion

    namespace "com.myapp"
    defaultConfig {
        applicationId  "com.myapp"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
    }
 }

### React Native Version

0.72.3

### Output of `npx react-native info`

![Screenshot 2023-07-28 at 11 04 02 AM](https://github.com/facebook/react-native/assets/126875445/2167f19e-c77d-4c1e-8c62-08d1236dcc44)

### Steps to reproduce

when i build app in android studio Flamingo 

### Snack, screenshot, or link to a repository

![Screenshot 2023-07-28 at 11 04 49 AM](https://github.com/facebook/react-native/assets/126875445/c17bcb74-bfa7-46d6-829f-dc783b6acda6)

**Comment by cortinico** [comment] 2023-07-28 11:02
Can you please share:
1. your `android/app/build.gradle` file?
2. the full build log

Plus having a repro would help

**Comment by priyaWedo** [comment] 2023-08-01 07:12
android/app/buid.gradle : 

------------------------------------------------------------------------------------------------------------------------
 buildscript {
    ext {
        buildToolsVersion = "33.0.1"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33
         // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
       
        if (System.properties['os.arch'] == "aarch64") {
            // For M1 Users we need to use the NDK 24 which added support for aarch64
            ndkVersion = "24.0.8215888"
        } else {
            // Otherwise we default to the side-by-side NDK version from AGP.
            ndkVersion = "21.4.7075529"
        }
        kotlinVersion = '1.8.0'
        playServicesVersion = "17.0.0"  
        androidMapsUtilsVersion="2.2.6"
    }
      
    repositories {
        google()
        jcenter()
        mavenCentral()
        // maven { url 'https://www.jitpack.io' }
    }
    dependencies {
        classpath('com.android.tools.build:gradle')
        classpath("com.facebook.react:react-native-gradle-plugin")
        // classpath("com.facebook.react:@react-native/gradle-plugin")
        classpath 'com.google.gms:google-services:4.3.8'
        classpath "com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin:2.0.0"
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.8.1'
        classpath "com.android.tools.build:gradle:$agp_version4"
    }
}

allprojects {
    repositories {
     mavenCentral()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
             url("$rootDir/../node_modules/react-native/android")
        }
         maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}
------------------------------------------------------------------------------------------------------------------------


repro: 
------------------------------------------------------------------------------------------------------------------------
npx react-native run-android 
------------------------------------------------------------------------------------------------------------------------

**Comment by cortinico** [comment] 2023-08-02 14:19
Please share the missing things I asked. Plus the file I asked for is `android/app/build.gradle` and not `android/build.gradle`.

**Comment by priyaWedo** [comment] 2023-08-10 05:05
@cortinico updated the file , please review it

**Comment by cortinico** [comment] 2023-08-11 14:29
The issue is caused by one of your dependency. Sadly it's impossible to say which one, as I see you have `:react-native-twilio-video-webrtc` and `:react-native-maps`

I suspect the issue will be fixed once you bump the version of those dependencies:
- https://github.com/blackuy/react-native-twilio-video-webrtc/pull/713

Closing for now as this is not an issue in React Native itself

**Closed by cortinico** 2023-08-11 14:29 UTC
Labels: Needs: Triage :mag:, Needs: Repro

**Comment by priyaWedo** [comment] 2023-08-14 06:16
@cortinico thank you for your help

**Comment by MechLocator** [comment] 2023-10-31 00:37
Hi, I managed to solve this error by including the namespace in the dependencies that caused the errors. I located them from my node modules, navigated to the build.gradle file of each dependency in the android directory,
[solution for the dependency react-native-splash-screen.txt.txt](https://github.com/facebook/react-native/files/13210809/solution.for.the.dependency.react-native-splash-screen.txt.txt)
[solution for the dependency react-native-splash-screen.txt.txt](https://github.com/facebook/react-native/files/13210813/solution.for.the.dependency.react-native-splash-screen.txt.txt)
 and then added the namespace under the android block.

Below is the exact solution I applied to this error for the react-native-splash-screen dependency.

def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

apply plugin: 'com.android.library'

def DEFAULT_COMPILE_SDK_VERSION             = 26
def DEFAULT_BUILD_TOOLS_VERSION             = "26.0.2"
def DEFAULT_TARGET_SDK_VERSION              = 26
def DEFAULT_SUPPORT_LIB_VERSION             = "26.1.0"

android {
    namespace "com.example.app" // <- add this here
    compileSdkVersion rootProject.hasProperty('compileSdkVersion') ? rootProject.compileSdkVersion : DEFAULT_COMPILE_SDK_VERSION
    buildToolsVersion rootProject.hasProperty('buildToolsVersion') ? rootProject.buildToolsVersion : DEFAULT_BUILD_TOOLS_VERSION

    defaultConfig {
        minSdkVersion safeExtGet('minSdkVersion', 16)
        targetSdkVersion rootProject.hasProperty('targetSdkVersion') ? rootProject.targetSdkVersion : DEFAULT_TARGET_SDK_VERSION
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    def supportLibVersion = rootProject.hasProperty('supportLibVersion') ? rootProject.supportLibVersion : DEFAULT_SUPPORT_LIB_VERSION

    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.12'
    implementation "com.android.support:appcompat-v7:$supportLibVersion"
    implementation "com.facebook.react:react-native:+" // From node_modules
}

I hope this helps someone solve this problem. If it does, that will be awesome.
PS: please follow my personal GitHub profile here: https://www.github.com/Moses-Githinji
Happy coding!!

**Comment by MechLocator** [comment] 2023-10-31 00:42
Hi, I managed to solve this error by including the namespace in the dependencies that caused the errors. I located them from my node modules, navigated to the build.gradle file of each dependency in the android directory,
[solution for the dependency react-native-splash-screen.txt.txt](https://github.com/facebook/react-native/files/13210809/solution.for.the.dependency.react-native-splash-screen.txt.txt)
[solution for the dependency react-native-splash-screen.txt.txt](https://github.com/facebook/react-native/files/13210813/solution.for.the.dependency.react-native-splash-screen.txt.txt)
 and then added the namespace under the android block.

**### Below is the exact solution I applied to this error for the react-native-splash-screen dependency.**

def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

apply plugin: 'com.android.library'

def DEFAULT_COMPILE_SDK_VERSION             = 26
def DEFAULT_BUILD_TOOLS_VERSION             = "26.0.2"
def DEFAULT_TARGET_SDK_VERSION              = 26
def DEFAULT_SUPPORT_LIB_VERSION             = "26.1.0"

android {
    namespace "com.example.app" // <- add this here
    compileSdkVersion rootProject.hasProperty('compileSdkVersion') ? rootProject.compileSdkVersion : DEFAULT_COMPILE_SDK_VERSION
    buildToolsVersion rootProject.hasProperty('buildToolsVersion') ? rootProject.buildToolsVersion : DEFAULT_BUILD_TOOLS_VERSION

    defaultConfig {
        minSdkVersion safeExtGet('minSdkVersion', 16)
        targetSdkVersion rootProject.hasProperty('targetSdkVersion') ? rootProject.targetSdkVersion : DEFAULT_TARGET_SDK_VERSION
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    def supportLibVersion = rootProject.hasProperty('supportLibVersion') ? rootProject.supportLibVersion : DEFAULT_SUPPORT_LIB_VERSION

    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.12'
    implementation "com.android.support:appcompat-v7:$supportLibVersion"
    implementation "com.facebook.react:react-native:+" // From node_modules
}

I hope this helps someone solve this problem. If it does, that will be awesome.
PS: please follow my personal GitHub profile here: https://www.github.com/Moses-Githinji
Happy coding!!

**Comment by MechLocator** [comment] 2023-10-31 00:47
The presentation above depicts a rookie's mistake, but I want to direct your attention to the lines below, 

android {
    **_namespace "com.example.app"_**
    compileSdkVersion rootProject.hasProperty('compileSdkVersion') ? rootProject.compileSdkVersion : DEFAULT_COMPILE_SDK_VERSION
    buildToolsVersion rootProject.hasProperty('buildToolsVersion') ? rootProject.buildToolsVersion : DEFAULT_BUILD_TOOLS_VERSION

    defaultConfig {
        minSdkVersion safeExtGet('minSdkVersion', 16)
        targetSdkVersion rootProject.hasProperty('targetSdkVersion') ? rootProject.targetSdkVersion : DEFAULT_TARGET_SDK_VERSION
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

**Comment by MechLocator** [comment] 2023-10-31 01:24
Make sure to replace "com.example.app" with the package name from each dependency's AndroidManifest.xml file which you should find in the "../android/src/main/AndroidManifest.xml" path. 

For example, if the package name from Androidmanifest.xml is "com.sortnumbers.mathsapp", then in the dependency's build.gradle file, inside the android scope, make sure you've indicated this exactly.

android {
  namespace "com.sortnumbers.mathsapp"
}

**Comment by mukesh-simform** [comment] 2024-06-12 06:53
@cortinico By any chance is there any workaround for this issue if third-party dependencies are not having that namespace defined in their respective build gradle files? 

For react native 0.73+ AGP 8+ is required and that enforces all the libraries to have namespace: https://github.com/react-native-community/discussions-and-proposals/issues/671

Currently, upgrading to 0.73+ is a bit challenging because that namespace required build error is expected. Not only in this single third-party library, but build throws an error in other libraries as well.

For e.g 

<img width="1110" alt="Screenshot 2024-06-12 at 11 58 10 AM" src="https://github.com/facebook/react-native/assets/56827526/cfbfa7ea-1c24-495d-987e-36464965630b">

Manually adding namespace in gradle file of each dependencies resolves this issue, somehow this can be a patch package for few depdencies until there's an update available, but that's not feasible when application has multiple dependencies 

Even following workaround is also not working. Any workaround is highly appreciated on this issue. Thank you!

```
android/build.gradle
--------------------

allprojects {
  ....
}

subprojects {
      afterEvaluate {
          project ->
              if (project.hasProperty("android")) {
                  android {
                      def agpVersion = com.android.Version.ANDROID_GRADLE_PLUGIN_VERSION.tokenize('.')[0].toInteger()
                      if (namespace == null && agpVersion >= 7) {
                          namespace project.group
                      }
                  }
              }
      }
  }
```

**Comment by cortinico** [comment] 2024-06-12 09:04
> Manually adding namespace in gradle file of each dependencies resolves this issue, somehow this can be a patch package for few depdencies until there's an update available, but that's not feasible when application has multiple dependencies

Why is it not feasible with multiple dependencies?
You should reach out to those dependencies and ask them to update their libraries to conditionally add `namespace` in their Gradle files.

Other than this, there is nothing much we can do. We communicated this change long ago exactly to avoid scenarios like this. If you're depending on old/unmaintained libraries, I would advice to consider moving away from those dependencies.
