### ISSUE TITLE
Boundary sometimes contains invalid '/' character when using "fetch + FormData" to post.

### ISSUE THREAD

**Issue by jaggerwang** [facebook/react-native#11416] opened 2016-12-12 09:42 UTC
### Description

After upgrade RN from 0.35 to 0.39, I got "mime: invalid media parameter" error from my golang server. This error not shows everytime, and it takes me a couple of days to figured out the reason. It is because the form multipart boundary contains invalid '/' character. It waste me a lot of time!!!

It is such a serious problem, can someone fixed it quickly?

### Additional Information

* React Native version: 0.39.0
* Platform: iOS
* Operating System: macOS

**Comment by lacker** [comment] 2016-12-17 00:19
How did you send this post request to your server? It is not clear to me that this is a React Native problem without getting more information.

**Comment by jaggerwang** [comment] 2016-12-18 03:41
```
POST /postLike/create HTTP/1.1
Host: api.zqc.dev
Content-Type: multipart/form-data; boundary=BHtyypVdlQVkn6tXeVfwQxmLXQhp4ryB45X0XBZC0CFLiNnkacJs9AytpU8ctvDd_r
Cache-Control: no-cache

--BHtyypVdlQVkn6tXeVfwQxmLXQhp4ryB45X0XBZC0CFLiNnkacJs9AytpU8ctvDd_r
Content-Disposition: form-data; name="postId"

580ad5456b09330013f0b663
--BHtyypVdlQVkn6tXeVfwQxmLXQhp4ryB45X0XBZC0CFLiNnkacJs9AytpU8ctvDd_r--
```

When boundary contains "/", the golang server will complain "mime: invalid media parameter". I've already fixed locally, and see somebody else have made a pull request. It should be merged quickly.

**Comment by cava23** [comment] 2017-01-10 00:52
This is an issue when using a Node.JS Express backend as well. Forward slashes do not follow the RFC specification. See this issue for the Express type-parsing module for more information: https://github.com/jshttp/media-typer/pull/1

I'm wrapping the boundary parameter in quotes to get around this for now. Can someone confirm this is a new issue? I can't believe I haven't run into it before, but it just started with 0.39 for us.

cc @seanj

**Comment by cava23** [comment] 2017-01-11 15:37
Why was this closed?

**Comment by jaggerwang** [comment] 2017-01-12 03:08
@cava23 , There is already has a same issue about this, and a pull request. So I closed.

**Comment by cava23** [comment] 2017-01-12 18:16
Could you link to the PR? That way people that find this issue first can track it (like me :)

**Comment by jaggerwang** [comment] 2017-01-13 01:32
Duplicated as issue #7564

**Comment by jaggerwang** [comment] 2017-01-16 09:43
It's still exist in 0.40, Why not merge? It's a so serious problem and the fix is very simple.

Just remove the '/' in boundaryChars, which exist in file 'RCTNetworking.mm'.
```
...
static NSString *RCTGenerateFormBoundary()
{
  const size_t boundaryLength = 70;
  const char *boundaryChars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_./";
...
```

**Comment by latte-diygame** [comment] 2017-01-26 04:00
I hava same issue and it is not merged in 0.41 pre-release.
I spent about 2 days with this issue.
Why not merge?

**Comment by alexanderjarvis** [comment] 2017-02-02 14:57
Also hitting this issue as a regression since previous releases.

**Comment by latte-diygame** [comment] 2017-02-03 01:17
i solved this issue with following.

Thanks to @jaggerwang 

```
// 'RCTNetworking.mm' file
static NSString *RCTGenerateFormBoundary()
{
    const size_t boundaryLength = 70;
    // Remove '/' in boundaryChars !!!
    const char *boundaryChars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_./";

    ...
}
```

**Comment by mienaikoe** [comment] 2017-04-27 18:48
Hitting this issue as well. Not really a fan of fixing things in local node_modules. I'd have to tell all my devs to do this.

**Comment by hramos** [comment] 2017-07-20 22:27
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/boundary-sometimes-contains-invalid--character-when-using-fetch--formdata-to-pos

**Closed by hramos** 2017-07-20 22:27 UTC
Labels: Icebox
