### ISSUE TITLE
MapView annotation focus triggers TabBarIOS.Item onPress()

### ISSUE THREAD

**Issue by stanlemon** [facebook/react-native#8093] opened 2016-06-13 15:30 UTC
When I have a MapView inside of a TabBarIOS.Item I am seeing that the selection of an annotation triggers the TabBarIOS.Item's onPress() event (as if the TabBar button was pressed), which does not seem to make sense.  This can be problematic if if the TabBar's onPress event does additional work that should not be fired during annotation selection.

In order to demonstrate what I am seeing and reproduce I created this rnplay: https://rnplay.org/apps/rcn5cg

If you follow the console you will see that before the onFocs() event on the annotation is called the TabBar's onPress() event is fired.

**Comment by katrinanova** [comment] 2016-08-04 02:10
I have the same issue. If anyone comes up with some work around, please post.

**Comment by charpeni** [comment] 2016-08-07 13:27
Unfortunately, map component is not maintained anymore, at least by the React Native Core Contributors team.

You should use [react-native-maps](https://github.com/lelandrichardson/react-native-maps) as it is more feature-complete than our internal implementation.

**Comment by charpeni** [comment] 2016-08-07 13:28
@facebook-github-bot bugfix

**Comment by facebook-github-bot-7** [comment] 2016-08-07 13:28
Hey @stanlemon, we're a small team and rely on the community to fix issues that don't affect fb apps. If you're sure this is a bug can you send a pull request with a fix?

**Comment by modeling** [comment] 2016-08-23 21:47
The same issue also is present when using the react-native-maps as suggested by chaperni. This seems to be an issue with TabBarIOS.Item and not the core map component. Hopefully a fix can be rolled out so that MapView can work with TabBarIOS.

**Comment by lacker** [comment] 2016-11-30 00:24
We are deprecating maps entirely now so I am closing this issue. If there's still an issue that relates to code that continues to be not-deprecated then I encourage people to open a new issue with reproduction information that doesn't involve maps.

**Closed by lacker** 2016-11-30 00:24 UTC
Labels: Ran Commands
