### ISSUE TITLE
Components appear blurry on certain iOS devices

### ISSUE THREAD

**Issue by comountainclimber** [facebook/react-native#7678] opened 2016-05-22 17:26 UTC
Please view the following rnplay.org sample app: https://rnplay.org/apps/xUYNIQ

As you can see it is as simple as it gets... My issue is that there seems to be no way for me to correct this side effect of `pixel grid snapping` (see blurry lines). **Is there currently anyway supported method to ensure my components render consistently within my react-native iOS application?**

This issue occurs both in simulator and on my device.

**Comment by comountainclimber** [comment] 2016-05-23 02:21
here is another example https://rnplay.org/apps/n3THVA with using `StyleSheet.hairlineWidth`

**Comment by lacker** [comment] 2016-10-26 05:59
I think the way it works has a decent explanation in the docs at https://facebook.github.io/react-native/docs/pixelratio.html:

> In iOS, you can specify positions and dimensions for elements with arbitrary precision, for example 29.674825. But, ultimately the physical display only have a fixed number of pixels, for example 640×960 for iphone 4 or 750×1334 for iphone 6. iOS tries to be as faithful as possible to the user value by spreading one original pixel into multiple ones to trick the eye. The downside of this technique is that it makes the resulting element look blurry.

In practice, we found out that developers do not want this feature and they have to work around it by doing manual rounding in order to avoid having blurry elements. In React Native, we are rounding all the pixels automatically.

We have to be careful when to do this rounding. You never want to work with rounded and unrounded values at the same time as you're going to accumulate rounding errors. Having even one rounding error is deadly because a one pixel border may vanish or be twice as big.

In React Native, everything in JS and within the layout engine work with arbitrary precision numbers. It's only when we set the position and dimensions of the native element on the main thread that we round. Also, rounding is done relative to the root rather than the parent, again to avoid accumulating rounding errors.

AFAICT you don't get much customization here. I'm going to close this issue as "working as intended" but if you have an example where the underlying behavior is not according to this description then please let me know / reopen a new issue. Thanks for bringing up this issue!

**Closed by lacker** 2016-10-26 05:59 UTC

**Comment by comountainclimber** [comment] 2016-10-26 15:13
@lacker very confused as to how flickering lines and borders are working as intended... I have read this information in th documentation before and it sounds like the rounding is supposed to prevent this issue not cause it unless I am missing something. Thanks for responding!

**Comment by lacker** [comment] 2016-10-26 20:31
Mmm, OK let me take another look. Those rnplay links don't seem to work for me any more, though - do you have a working link?
