### ISSUE TITLE
[NavigatorIOS] doesn't update when passProps update

### ISSUE THREAD

**Issue by lazywei** [facebook/react-native#795] opened 2015-04-10 09:53 UTC
I'm not sure if this is a feature or a bug:

When I change the value of `passProps` of a navigator, I expect it would re-render again, just like other react components do. However, it seems it will not do so.

For example,

```
          <NavigatorIOS
            style={{flex: 1}}
            initialRoute={{
              component: MyChatList,
              title: "My Chat List",
              passProps: {
                recentChats: this.state.ChatListData.recentChats,
                renderRow: this.renderRecentChat,
              },
            }} />
```

When the state `ChatListData` (which comes from flux) updates, the navigator will not update it self correspondly.

**Comment by iostalk** [comment] 2015-04-10 16:43
I don't know

**Comment by ericvicenti** [comment] 2015-04-10 20:51
`initialRoute` only specifies the initial scene in the navigator.

The reason we don't do this is we don't want to re-render all of the scenes every time you re-render `NavigatorIOS`. This would make the app very slow once you have several scenes open. If your props are changing, you can call `navigator.replace(newRoute)`, or use event emitters to communicate to inner scenes.

`Navigator` handles this case a bit better. When you re-render, it will call `renderScene` again for the currently-visible scenes (unless you are mid-transition).

I'm still trying to figure out the ideal pattern for re-rendering internal scenes. Feedback and ideas are welcome!

**Comment by lazywei** [comment] 2015-04-11 03:52
@ericvicenti Oh, I totally forgot I can use `replace`. I feel that is a little anti-react though. I mean, monitoring new props ourself. On the other hand, using event emitters is probably more like Flux, right? However, I'd personally prefer keep the states on the top-most components and let it pass props down, instead of let the navigator listen to the store directly.

For the `Navigator`, would it also be slow if I keep re-render (new props keep coming, for example)?

Thanks for your elaborating.

**Comment by mjw56** [comment] 2015-04-11 13:28
I too ran into this when I first started writing a RN app. 

Is there any way that calling setState can update props to any potential children on the same route like with React?

ie:

```javascript
  _buttonPress() {

    this.setState({
      input: 'heyo'
    })

  },

  render() {
    return (
      <View>
         <ChildComponent input={this.state.input} /> // input prop change will be heard by Child
      </View>
    )
  }
```

**Comment by ericvicenti** [comment] 2015-04-13 20:45
@mjw56, That code should work, the input prop would be updated when setState is called. Are you having difficulties when putting ChildComponent inside a Navigator or NavigatorIOS?

@lazywei, I agree that it would be nicer to re-render the scene when the NavigatorIOS gets re-rendered. It would be great if somebody could implement `Navigator`'s `renderScene` API for `NavigatorIOS`. That way the initial route would remain, but you could re-render the scene according to changing state outside the navigator.

When it comes to slowness from re-rendering in `Navigator`, it shouldn't be a problem because `Navigator` is careful to only re-render scenes that are visible. This would also be important to do if somebody adds the `renderScene` API to `NavigatorIOS`.

You might run into issues if you want to re-render aggressively, but you could always improve the `shouldComponentUpdate` logic in your scenes.

**Comment by ustun** [comment] 2015-04-14 14:41
It also doesn't update when navigationBarHidden is changed, see https://github.com/facebook/react-native/issues/846

**Comment by mars** [comment] 2015-06-06 18:33
Still an issue with React Native 0.6rc. Workaround is calling `this.refs.navigator.replace(…)` with the updated state in `passProps`.

**Comment by Iragne** [comment] 2015-06-24 16:26
may be this PR can solved your issue ?
https://github.com/facebook/react-native/pull/1733

**Comment by edo1493** [comment] 2015-07-09 14:46
@mars: It's a Workaround if you haven't got anything in NavigatorIOS. What if you have pushed several routes? 

I am trying to use resetTo() in order to reset the whole thing every time new props come in. (http://stackoverflow.com/questions/31320583/invariant-violation-calling-pop-to-route-for-a-route-that-doesnt-exist)

Any idea?

**Comment by mars** [comment] 2015-07-09 19:57
@edo1493 I ended up using the more manual but less limiting `React.Navigator` and `…navigator.immediatelyResetRouteStack()`. See [Navigator docs](https://facebook.github.io/react-native/docs/navigator.html)

**Comment by edo1493** [comment] 2015-07-09 20:49
@ericvicenti have you seen this? Thanks.

**Comment by facebook-github-bot-3** [comment] 2015-08-04 18:05
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by ericvicenti** [comment] 2015-08-04 20:30
Is this issue about `Navigator` or `NavigatorIOS`? I see references to both in here.

For clarification about the difference, check out @brentvatne's [comparison](http://facebook.github.io/react-native/docs/navigator-comparison.html#content)

**Comment by mars** [comment] 2015-08-05 01:48
@ericvicenti this issue is w/ `NavigatorIOS`

Using the `Navigator` module instead re-renders routes/scenes at the appropriate times.

**Comment by edo1493** [comment] 2015-08-05 07:56
The issue is with NavigatorIOS. 
Since I didn't have to re-render anything, I have solved with an EventEmitter that pass the updated props from componentWillReceiveProps.

**Comment by ericvicenti** [comment] 2015-08-05 18:57
Ok, that sounds like a reasonable workaround for now. We currently don't use `NavigatorIOS` at Fb, so its up to the community to get this one fixed.

**Comment by chirag04** [comment] 2015-08-30 21:47
@ericvicenti @vjeux @brentvatne  this may sound crazy but should react native move ``NavigatorIOS`` out of core?

It can live in userland and will be better supported i guess if it's in userland.

**Comment by aphillipo** [comment] 2015-09-13 17:05
Yes.  Please either remove it so people don't get confused or put a big red warning in the docs saying "this component breaks the underlying working of react".  Wasted time until I found this bug.

**Comment by browniefed** [comment] 2015-09-13 17:22
@chirag04 there is already this https://github.com/facebook/react-native/issues/1519

**Comment by edo1493** [comment] 2015-10-28 17:17
I know this is a bit off-topic, but is there a way to update the props of each component in the stackRoute of Navigator? 

I am updating the state where Navigator is rendered, but the props don't seem to update.

**Comment by bokuweb** [comment] 2015-10-30 13:23
I use v0.13.1.
I create getter method to get updated props, and pass to  `NavigatorIOS`.
It is easy to keep the states on the top-most components and let it pass props down.
In this case there will be a problem?

For example,
```  javascript
  getRecentChats() {
    return this.state.ChatListData.recentChats;
  }
  render() {
    return (
      <NavigatorIOS
        style={{flex: 1}}
        initialRoute={{
          component: MyChatList,
          title: "My Chat List",
          passProps: {
            recentChats: getRecentChats.bind(this),
            renderRow: this.renderRecentChat,
          },
       }} />
    );
}

**Comment by maxkrieger** [comment] 2015-12-28 17:46
I've been using `replacePreviousAndPop({})` for more complex pagination scenarios and it has worked fine, albeit less cache-y than I'd hoped.

**Comment by katrinanova** [comment] 2016-01-11 23:08
@ericvicenti any idea why navigator.replace(newRoute) does't work in RN version 17 and 16? going back to version 14 now :( 
replaceAtIndex method of NavigatorIOS seems to be identical.

**Comment by ericvicenti** [comment] 2016-01-11 23:17
It might be due to changes on the native side. I don't really work with NavigatorIOS, so I'm not sure

**Comment by hasen6** [comment] 2016-02-26 03:16
What happened with this? I'm also experiencing this error. Apparently we were going to see a response in 30 days but that was about 5 or 6 months ago.

**Comment by tkmoney** [comment] 2016-03-05 22:54
+1

**Comment by sericaia** [comment] 2016-04-19 16:30
:+1:

**Comment by ryanyu104** [comment] 2016-06-28 03:31
＋1

**Comment by oktapodi** [comment] 2016-09-18 20:40
+1

**Comment by aphillipo** [comment] 2016-09-19 04:43
Facebook don't support the native control - Navigator is their JS replacement and it works okay.

**Comment by Gagege** [comment] 2016-10-06 20:55
I'm using version 0.34.0 and Navigator (not NavigatorIOS) and I'm having this exact problem. State changes in my parent screens get passed into child/sibling screens via passProps, but the child/sibling screens don't get re-rendered. I have to call this.forceUpdate() on my child/sibling screens after calling back to the parent screen. It works fine, but it's not very "Reacty".

**Comment by mrEmo** [comment] 2016-10-16 17:25
I am also experiencing the issue described by @Gagege, which is very easy to reproduce. It is counter intuitive because with all react components, you expect that props passed to a child will automatically re-render the child when they are updated in the parent via setState(). 

The use of Navigator's passProps functionality breaks this pattern and makes it difficult to update any view that is a child of a navigator.

I am going to try using NavigationExperimental to see if it has the same issue

**Comment by lacker** [comment] 2016-10-21 05:09
This issue seems like it is now a bunch of different issues combined. @felipemullen I suggest trying ExNavigation and complaining to @skevy if it is not good enough, rather than NavigationExperimental which we are figuring out how to combine with ExNavigation soon. I'm going to close this issue, and I suggest if people continue to have similar problems they open a new issue and be very clear about whether the problem applies to `Navigator` or `NavigatorIOS` because they are pretty different in terms of getting them fixed.

**Closed by lacker** 2016-10-21 05:09 UTC
Labels: Community Responsibility
