### ISSUE TITLE
keyboard may not show when using OPPO phone sometimes

### ISSUE THREAD

**Issue by 13160102112** [facebook/react-native#12671] opened 2017-03-03 02:41 UTC
keyboard may not show when using OPPO phone sometimes

**Comment by ericvicenti** [comment] 2017-03-06 08:18
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by ericvicenti** 2017-03-06 08:18 UTC

**Comment by ZHT131** [comment] 2017-06-13 12:20
I have the same problem, can you tell me how to solve it?
