### ISSUE TITLE
WebView onLoadEnd never get call (iOS)

### ISSUE THREAD

**Issue by james1888** [facebook/react-native#18802] opened 2018-04-11 07:19 UTC
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.9.4
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.54.0 => 0.54.0

## Steps to Reproduce

```js
import React from "react";
import { StyleSheet, Text, View, WebView } from "react-native";

export default class App extends React.Component {
  render() {
    return (
      <WebView
        source={{ html: "<h1>Hello World<h1>" }}
        onLoadEnd={e => console.log("end", e)}
        onLoadStart={e => console.log("start", e)}
        onError={e => console.log("error", e)}
      />
    );
  }
}

```

[Snack](https://snack.expo.io/SyG8rNjjf)

## Expected Behavior

It should both log start and end.

## Actual Behavior

Only start event is logged.

**Comment by mengkheang** [comment] 2018-04-11 07:28
yes

**Comment by Tamiyadd** [comment] 2018-05-16 16:32
i can confirm issue too

**Comment by 337240552** [comment] 2018-05-30 00:53
i can confirm issue too, android platform

**Comment by mhidou** [comment] 2018-07-02 10:52
When you use `WebView` with `source={{ html }}` the url is `about:blank`.

In`RCTWebView.m:346` we have `![webView.request.URL.absoluteString isEqualToString:@"about:blank"]`:

``` objective-c
// we only need the final 'finishLoad' call so only fire the event when we're actually done loading.
  else if (_onLoadingFinish && !webView.loading && ![webView.request.URL.absoluteString isEqualToString:@"about:blank"]) {
  _onLoadingFinish([self baseEvent]);
}
```

Setting an empty url in `WebView`'s source fixes this issue:

```jsx
<WebView
  source={{ html: `<h1>Hello World<h1>`, baseUrl: '' }}
  onLoadEnd={e => console.log('end', e)}
  onLoadStart={e => console.log('start', e)}
  onError={e => console.log('error', e)}
  />
```

**Comment by Damoness** [comment] 2018-07-02 14:31
you have solved my problem

**Comment by soyanakagawa** [comment] 2018-08-11 03:06
v0.56.0
baseUrl not work.

This issue will solve when RN use WKWebView instead of UIWebView.
https://github.com/facebook/react-native/issues/321

**Comment by kelset** [comment] 2018-09-24 08:39
There has been no further interaction here so I feel safe in closing per comment above

**Closed by kelset** 2018-09-24 08:39 UTC
Labels: :large_blue_diamond:iOS, :large_orange_diamond:Components, :large_orange_diamond:WebView

**Comment by arfa123** [comment] 2019-04-16 11:16
> v0.56.0
> baseUrl not work.
> 
> This issue will solve when RN use WKWebView instead of UIWebView.
> #321

this works for me, thanks
