### ISSUE TITLE
global.nativeTraceBeginSection is not a function

### ISSUE THREAD

**Issue by songxuhua** [facebook/react-native#14965] opened 2017-07-12 08:27 UTC
Once i run the project(react-native run-ios),i edit my js file,try to Reload JS ,but get error global.nativeTraceBeginSection is not a function,what is the wrong?
![2017-07-12 4 26 43](https://user-images.githubusercontent.com/10429468/28108671-f0cea5fe-671e-11e7-9215-be6f723bfee4.png)

**Comment by hramos** [comment] 2017-07-12 15:05
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-07-12 15:05 UTC

**Comment by PublicParadise** [comment] 2017-07-17 00:30
I am seeing this problem, too. This happens after the first reload in the simulator. Workaround is killing the app and relaunching it from XCode. Pretty annoying.

**Comment by songxuhua** [comment] 2017-07-17 00:43
I fix it. just launching it from xcode,not from 
terminal.Thanks!

**Comment by sportsbench** [comment] 2017-07-20 12:38
What is the fix for this? Getting this error when I updated to `react v16.0.0-alpha.12` from `react v16.0.0-alpha.6` and `react-native: 0.44` to `react-native: 0.45.1`

**Comment by 13941089621** [comment] 2017-08-23 07:34
为什么还不好使

**Comment by 13941089621** [comment] 2017-08-23 07:34
![simulator screen shot 2017 8 23 1 45 50](https://user-images.githubusercontent.com/26081015/29603955-8da0552a-8818-11e7-8323-e81df3313d68.png)

**Comment by AlexanderYao** [comment] 2017-08-30 05:16
`Stop SysTrace` works

**Comment by jack2684** [comment] 2018-01-08 08:28
@AlexanderYao Sorry noob question, how to `Stop SysTrace`?

**Comment by AlicanC** [comment] 2018-01-09 17:58
> how to Stop SysTrace?

It's in the [Developer Menu](https://facebook.github.io/react-native/docs/debugging.html#accessing-the-in-app-developer-menu).

**Comment by babelchips** [comment] 2018-01-09 23:25
Just started getting the sys trace error.   Actually had the No Bundle URL present error prior(for no reason....), so tried building and running from Xcode etc. to solve that...

Thankfully stopping Sys Trace via the Dev Menu (cmd D) in the simulator worked.  Anyone know what causes it to happen in the first place and will I have to contend with these issues randomly from now on?
