### ISSUE TITLE
changing listview datasource is not resetting state

### ISSUE THREAD

**Issue by jcharbo** [facebook/react-native#12046] opened 2017-01-23 20:50 UTC
### Description

I'm using RN 39 and I'm using a listview with a datasource.  Say the datasource has three items: a,b, and c.  If I change the state in item b, for example setting an open flag, and then insert a row to the datasource, the state from b moves to item a so that a is open instead of b.

### Reproduction

https://rnplay.org/apps/nN5Z6A

Go to this app and toggle row b to be closed.  Click Add row and you'll notice that row b is now open and row a is closed.

### Additional Information

* React Native version: 33 and 39
* Platform: both
* Operating System: Mac

**Comment by rgoldiez** [comment] 2017-02-25 12:03
I think the problem is that you're passing in an array (vs. an object/collection) to your cloneWithRows.  ListView.DataSource isn't smart enough to know which (in your case) non-keyed row has prior state; when you update your datasource, you're getting a full replacement.  If you try this with a object/collection, I think you'll get the results you're looking for.

Something like this `const initialBlob = {a: 'a', b: 'b', c: 'c'}` and then update your datasource to `const newBlob = {...initialBlob, d: 'd'}` (I wrote this with spread but that isn't required.

**Comment by hramos** [comment] 2017-03-31 18:33
Closing as ListView is deprecated in 0.43. Use FlatList.

**Closed by hramos** 2017-03-31 18:33 UTC
