### ISSUE TITLE
react-native run-android is starting up the app with an error "index.android.bundle" on react native @5.6

### ISSUE THREAD

**Issue by bishrulhaq** [facebook/react-native#20678] opened 2018-08-15 11:35 UTC
**Environment** 

 React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
      Memory: 1.46 GB / 7.88 GB
    Binaries:
      npm: 6.3.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4819257

I have been trying several times to run the project and i couldn't be able to run it on my mobile, due to the "index.android.bundle" error. 

I have tried using the below commands and yet the error remains
- npm start -- --reset-cache (to reset the cache)
- adb reverse tcp:8081 tcp:8081 (adb port changes)
- npm i react-native-material-design --save (installing the material design)

![error](https://user-images.githubusercontent.com/12353697/44146485-5ab4947e-a0ad-11e8-8d8d-3fa81862c7a7.png)

**Comment by LaylaCsAvila** [comment] 2018-08-17 19:37
Try uploading your Android Studio. I was having the same issue and could not run in the emulator nor in a real device until I upgraded this morning. Both started working again after updating to version 3.1.4. My OS is not Windows (Ubuntu 18.04), but maybe it helps.

**Comment by bishrulhaq** [comment] 2018-08-18 06:48
@LaylaCsAvila I have tried using Android Studio and the issue remains same. React Native @0.55.2  works fine with both in Android Studio and VS Code. When i upgrade it to the @5.6 then the  "index.android.bundle" error pops up. I think it's a bug with react native @5.6 for windows platform.

**Comment by kelset** [comment] 2018-08-18 19:41
Duplicate of https://github.com/facebook/react-native/issues/19953

**Closed by kelset** 2018-08-18 19:41 UTC
Labels: :large_blue_diamond:Android
