### ISSUE TITLE
passing Flatlist prop scrollEventThrottle doesn't make sense (regression 0.59.5 -> 0.59.8)

### ISSUE THREAD

**Issue by alyalya** [facebook/react-native#25027] opened 2019-05-24 14:27 UTC
After updating React Native from 0.59.5 to 0.59.8 scrollEventThrottle in Flatlist stopped working, which resulted in ramming the bridge

React Native version:
0.59.8

## Steps To Reproduce

1. Add scrollEventThrottle prop to Flatlist
2. Scroll Flatlist
3. We get every scroll event in onScroll prop

Describe what you expected to happen:

Expected to get throttled scroll events 

Snack, code example, or link to a repository:

**Comment by satya164** [comment] 2019-05-30 15:48
Can you provide a minimal repro demonstrating the bug?

**Comment by Krizzu** [comment] 2019-05-30 15:56
Probably caused by [this commit](https://github.com/facebook/react-native/commit/39776a82f0c5d9b84feef79cf87f8e8da243424f)

**Comment by kelset** [comment] 2019-05-30 16:01
I think this is a duplicate of this: https://github.com/facebook/react-native/issues/24826

Apparently there was a subsequent fix, I'm still trying to find the commit.

**Comment by zhongwuzw** [comment] 2019-05-31 01:22
May fixed in https://github.com/facebook/react-native/pull/25098.

**Closed** 2019-06-03 09:11 UTC
Labels: Bug, Component: FlatList, Impact: Regression, Resolution: Needs Repro
