### ISSUE TITLE
Autocomplete credit card not working on iOS

### ISSUE THREAD

**Issue by tushe-tv** [facebook/react-native#46910] opened 2024-10-09 08:20 UTC
### Description

autoComplete/textContentType credit card not working on TextInput on iOS  - I've saved cards to Safari Autofill, to Wallet and in my profile Payment and Shipping, but no suggestions are shown

### Steps to reproduce

Add to TextInput autoCmpleate="cc-number" or textContentType="creditCardNumber" and see if any cards are shown when the pad shows

### React Native Version

0.75.4

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.6.1
  CPU: (10) arm64 Apple M2 Pro
  Memory: 68.59 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.17.0
    path: ~/.nvm/versions/node/v20.17.0/bin/node
  Yarn:
    version: 4.5.0
    path: ~/.nvm/versions/node/v20.17.0/bin/yarn
  npm:
    version: 10.8.2
    path: ~/.nvm/versions/node/v20.17.0/bin/npm
  Watchman:
    version: 2024.09.30.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.0
      - iOS 18.0
      - macOS 15.0
      - tvOS 18.0
      - visionOS 2.0
      - watchOS 11.0
  Android SDK:
    API Levels:
      - "31"
      - "33"
      - "34"
    Build Tools:
      - 29.0.2
      - 30.0.3
      - 33.0.0
      - 33.0.1
      - 34.0.0
    System Images:
      - android-29 | Google Play ARM 64 v8a
      - android-30 | Google Play ARM 64 v8a
      - android-30 | Google APIs ATD ARM 64 v8a
      - android-31 | Google APIs ARM 64 v8a
      - android-31 | Google Play ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
      - android-34 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.21829.142.2421.12409432
  Xcode:
    version: 16.0/16A242d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.4
    wanted: 0.75.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Screenshots and Videos

![Screenshot 2024-10-09 at 11 22 33](https://github.com/user-attachments/assets/a1b74687-8177-4553-a530-b2435517dd73)

**Comment by shubhamguptadream11** [comment] 2024-10-10 07:31
@tushe-tv Is this issue happening on New architecture as well?

**Comment by tushe-tv** [comment] 2024-10-10 07:38
Have not test it on it. 
I've test it on swift, but did not get any card suggestions as well:
```swift
TextField("Card Number", text: $cardNumber).textContentType(.creditCardNumber)
TextField("Exp Date", text: $date).textContentType(.creditCardExpiration)
TextField("CVV", text: $cvv).textContentType(.creditCardSecurityCode)
TextField("Name", text: $name).textContentType(.creditCardName)
```

**Comment by Gambitboy** [comment] 2024-10-31 16:09
https://github.com/facebook/react-native/issues/36089

I brought this issue up last year February with no real input.
I've since retested on 0.76.1.

Android works.
iOS does not work.

When you tap on the input and select autofill, a "AutoFill Unavailable" popup appears.

**Comment by cortinico** [comment] 2024-11-01 11:31
Closing as duplicate of https://github.com/facebook/react-native/issues/36089

Thanks for the heads up @Gambitboy let's keep the conversation going over there 👍

**Closed by cortinico** 2024-11-01 11:31 UTC
Labels: Platform: iOS, Issue: Author Provided Repro
