### ISSUE TITLE
Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by mounlion** [facebook/react-native#17320] opened 2017-12-22 12:23 UTC
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

```
"dependencies": {
    "@yfuks/react-native-action-sheet": "0.0.4",
    "native-base": "2.3.3",
    "react": "16.0.0",
    "react-native": "0.51.0",
    "react-native-cookies": "3.2.0",
    "react-native-device-info": "^0.10.2",
    "react-native-google-analytics": "^1.3.2",
    "react-native-google-analytics-bridge": "^5.4.1",
    "react-native-htmlview": "0.12.1",
    "react-native-image-picker": "^0.26.7",
    "react-native-image-progress": "^1.0.1",
    "react-native-maps": "0.19.0",
    "react-native-permissions": "0.2.7",
    "react-native-photo-view": "^1.5.2",
    "react-native-router-flux": "4.0.0-beta.24",
    "react-native-segmented-control-tab": "^3.2.1",
    "react-native-share": "^1.0.23",
    "react-native-store-review": "^0.1.3",
    "react-native-vector-icons": "4.4.2",
    "react-redux": "5.0.6",
    "react-static-container": "^1.0.2",
    "redux": "3.6.0",
    "redux-actions": "1.2.1",
    "redux-logger": "2.8.1",
    "redux-thunk": "2.2.0"
  },
  "devDependencies": {
    "babel-jest": "21.2.0",
    "babel-preset-react-native": "4.0.0",
    "jest": "21.2.1",
    "react-test-renderer": "16.0.0"
  },
```
### Expected Behavior

Not runing

### Actual Behavior

```

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RCTReconnectingWebSocket", referenced from:
      objc-class-ref in libReact.a(RCTPackagerConnection.o)
  "_OBJC_CLASS_$_RCTSRWebSocket", referenced from:
      objc-class-ref in libReact.a(RCTInspectorPackagerConnection.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)


```

I try this https://stackoverflow.com/questions/41477241/react-native-xcode-upgrade-and-now-rctconvert-h-not-found/41488258#41488258 but it does not help me

**Comment by charpeni** [comment] 2017-12-22 14:19
Duplicate of #14925.

**Closed by charpeni** 2017-12-22 14:19 UTC
