### ISSUE TITLE
0.56 broken dependencies ? Could not find com.android.tools:common:25.3.3.

### ISSUE THREAD

**Issue by ArThoX** [facebook/react-native#22608] opened 2018-12-11 22:49 UTC
## Environment
```
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Memory: 7.30 GB / 15.84 GB
    Binaries:
      Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338
```

## Description
package.json : `"react-native": "0.56.0",`
Fresh `android` dir through `react-native upgrade` then `react-native run-android`.

> react-native run-android
> Scanning folders for symlinks in C:\Users\root\Desktop\Dev\todo\node_modules (62ms)
> Starting JS server...
> Building and installing the app on the device (cd android && gradlew.bat installDebug)...
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring root project 'example'.
> > Could not resolve all dependencies for configuration ':classpath'.
>    > Could not find com.android.tools:common:25.3.3.
>      Searched in the following locations:
>          https://jcenter.bintray.com/com/android/tools/common/25.3.3/common-25.3.3.pom
>          https://jcenter.bintray.com/com/android/tools/common/25.3.3/common-25.3.3.jar
>          https://maven.google.com/com/android/tools/common/25.3.3/common-25.3.3.pom
>          https://maven.google.com/com/android/tools/common/25.3.3/common-25.3.3.jar
>      Required by:
>          project : > com.android.tools.build:gradle:2.3.3 > com.android.tools.build:gradle-core:2.3.3 > com.android.tools.build:builder:2.3.3
>          project : > com.android.tools.build:gradle:2.3.3 > com.android.tools.build:gradle-core:2.3.3 > com.android.tools.build:builder:2.3.3 > com.android.tools.build:manifest-merger:25.3.3
>          project : > com.android.tools.build:gradle:2.3.3 > com.android.tools.build:gradle-core:2.3.3 > com.android.tools.build:builder:2.3.3 > com.android.tools.ddms:ddmlib:25.3.3
>          project : > com.android.tools.build:gradle:2.3.3 > com.android.tools.build:gradle-core:2.3.3 > com.android.tools.build:builder:2.3.3 > com.android.tools.analytics-library:shared:25.3.3
>          project : > com.android.tools.build:gradle:2.3.3 > com.android.tools.build:gradle-core:2.3.3 > com.android.tools.build:builder:2.3.3 > com.android.tools.analytics-library:tracker:25.3.3
>          project : > com.android.tools.build:gradle:2.3.3 > com.android.tools.build:gradle-core:2.3.3 > com.android.tools.build:builder:2.3.3 > com.android.tools:sdklib:25.3.3 > com.android.tools.layoutlib:layoutlib-api:25.3.3
>          project : > com.android.tools.build:gradle:2.3.3 > com.android.tools.build:gradle-core:2.3.3 > com.android.tools.build:builder:2.3.3 > com.android.tools:sdklib:25.3.3 > com.android.tools:dvlib:25.3.3
>          project : > com.android.tools.build:gradle:2.3.3 > com.android.tools.build:gradle-core:2.3.3 > com.android.tools.build:builder:2.3.3 > com.android.tools:sdklib:25.3.3 > com.android.tools:repository:25.3.3
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED
> 
> Total time: 5.059 secs
> Could not install the app on the device, read the error above for details.
> Make sure you have an Android emulator running or a device connected and have
> set up your Android development environment:
> https://facebook.github.io/react-native/docs/getting-started.html

**Comment by hramos** [comment] 2018-12-11 23:00
Duplicate of #22602

**Closed by hramos** 2018-12-11 23:00 UTC
