### ISSUE TITLE
Consuming lot of RAM : Continous increase in RAM consumption 

### ISSUE THREAD

**Issue by Rishabh-Rathod** [facebook/react-native#25514] opened 2019-07-05 10:18 UTC
React Native version:
System:
    OS: Linux 4.15 Ubuntu 18.04 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    Memory: 3.42 GB / 7.65 GB
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 12.5.0 - /usr/bin/node
    npm: 6.10.0 - /usr/bin/npm
    Watchman: 4.9.0 - /home/linuxbrew/.linuxbrew/bin/watchman
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.0 => 0.60.0 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce

1. go to the project root folder
2. run "react-native start"

Describe what you expected to happen:
Expected 
Bundler to get ready and a message
Loading dependency graph...done

Snack, code example, or link to a repository:

file:///home/rishabh/Pictures/reactnativeissue.png

**Comment by Rishabh-Rathod** [comment] 2019-07-05 10:20
file:///home/rishabh/Pictures/reactnativeissue.png

**Comment by thymikee** [comment] 2019-07-05 10:30
Duplicate of https://github.com/react-native-community/cli/issues/477

**Closed by thymikee** 2019-07-05 10:30 UTC
Labels: Bug, Platform: Linux
