### ISSUE TITLE
SyntaxError: Strict mode does not allow function declarations in a lexically nested statement on a newly created app

### ISSUE THREAD

**Issue by lednhatkhanh** [facebook/react-native#11389] opened 2016-12-09 10:50 UTC
It worked untill yesterday

I tried all these things: Remove nodejs, reinstall react-native-cli, run npm start -- --reset-cache. wipe my android emulator data.

I asked the question on stackoverflow but it's look like that no one have interested in it...

This's really annoying, I can see that someone also has the same problem with me.

Windows 10 64bit.
Latest react-native-cli.
Newly created app without any modification.
Nodejs 7.2.1

npm-debug

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\lednh\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start',
1 verbose cli   '--',
1 verbose cli   '--reset-cache' ]
2 info using npm@4.0.5
3 info using node@v7.2.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ReactTodosApp@0.0.1~prestart: ReactTodosApp@0.0.1
6 silly lifecycle ReactTodosApp@0.0.1~prestart: no script for prestart, continuing
7 info lifecycle ReactTodosApp@0.0.1~start: ReactTodosApp@0.0.1
8 verbose lifecycle ReactTodosApp@0.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle ReactTodosApp@0.0.1~start: PATH: C:\Users\lednh\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\lednh\Documents\react-native\ReactTodosApp\node_modules\.bin;C:\flow;c:\program files (x86)\graphicsmagick-1.3.25-q16;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Program Files\Java\jdk1.8.0_112\bin;C:\Users\lednh\AppData\Local\Android\sdk\platform-tools;C:\Users\lednh\AppData\Local\Android\sdk\tools;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Python27\python.exe;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Yarn\bin;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Program Files\dotnet\;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\nodejs\;C:\Program Files\MongoDB\Server\3.4\bin;C:\Users\lednh\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\lednh\AppData\Local\.meteor\;C:\Python27\python.exe;C:\Users\lednh\AppData\Local\Yarn\.bin;C:\Users\lednh\AppData\Roaming\Composer\vendor\bin;C:\Users\lednh\AppData\Roaming\npm
10 verbose lifecycle ReactTodosApp@0.0.1~start: CWD: C:\Users\lednh\Documents\react-native\ReactTodosApp
11 silly lifecycle ReactTodosApp@0.0.1~start: Args: [ '/d /s /c',
11 silly lifecycle   'node node_modules/react-native/local-cli/cli.js start "--reset-cache"' ]
12 silly lifecycle ReactTodosApp@0.0.1~start: Returned: code: 3221225786  signal: null
13 info lifecycle ReactTodosApp@0.0.1~start: Failed to exec start script
14 verbose stack Error: ReactTodosApp@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start "--reset-cache"`
14 verbose stack Exit status 3221225786
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\lednh\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\lednh\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid ReactTodosApp@0.0.1
16 verbose cwd C:\Users\lednh\Documents\react-native\ReactTodosApp
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\lednh\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start" "--" "--reset-cache"
19 error node v7.2.1
20 error npm  v4.0.5
21 error code ELIFECYCLE
22 error ReactTodosApp@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start "--reset-cache"`
22 error Exit status 3221225786
23 error Failed at the ReactTodosApp@0.0.1 start script 'node node_modules/react-native/local-cli/cli.js start "--reset-cache"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ReactTodosApp package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node node_modules/react-native/local-cli/cli.js start "--reset-cache"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ReactTodosApp
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ReactTodosApp
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

After a while searching on google, I can see that many people are facing this problems and there are no proper fix for this...

**Comment by Taximan** [comment] 2016-12-09 10:59
same here, worked yesterday, started a new project this morning and got this very same error.

**Comment by lednhatkhanh** [comment] 2016-12-09 11:02
If you make a search, you can see that many many people have the exact same problem and many of they change the pc, or reinstall their OS to make rn work again.

**Comment by suevalov** [comment] 2016-12-09 11:14
I see the same and only for Android version. When debug is enabled everything works.

I've tried to understand the cause of the problem, jumping from commit to commit back in history and it looks like the reason of problem is the latest release of babel. https://github.com/babel/babel/releases/tag/v6.20.0

With babel 6.18.0 in yarn.lock file everything is okay. When I remove yarn.lock and install it again one of sub-dependencies fetches the latest version of babel and the problem appears.

**Comment by lednhatkhanh** [comment] 2016-12-09 11:30
@suevalov Can you please tell me how to lock the babel version to 6.18? Thank you.

**Comment by karpoff** [comment] 2016-12-09 11:47
FYI failing code is placed at node_modules\react-native\ReactAndroid\src\androidTest\assets\AndroidTestBundle.js
if(!global.__fbDisableExceptionsManager){(function(){
function handleError(e,isFatal){
try{
ExceptionsManager.handleException(e,isFatal);
}catch(ee){

**Comment by karpoff** [comment] 2016-12-09 12:04
and for me it works without any error if remote debugging is enabled

**Comment by raitucarp** [comment] 2016-12-09 13:18
is issue still happening right now?

**Comment by rogvold** [comment] 2016-12-09 13:19
@karpoff your solution works for mw too. Thanks! Hope it will be fixed soon

**Comment by lohithananda** [comment] 2016-12-09 13:22
I am new to react native but i am getting the red screen with syntaxError:SyntaxError: Strict mode does not allow function declarations in a lexically nested statement. any one please help.

@karpoff how we can enable remote debugging  for android device

**Comment by lednhatkhanh** [comment] 2016-12-09 13:24
@lohithananda On the android emulater, press Ctrl+M to open the dev menu, and then choose start Rote JS Debugging, it will open a new tab in chrome, keep it open.

**Comment by lohithananda** [comment] 2016-12-09 13:27
@lednhatkhanh i am working on the real android device

**Comment by karpoff** [comment] 2016-12-09 14:13
@lohithananda enabling dev menu on real device is performed by shaking phone in your hand. on some devices soft menu button is available (it looks like hamburger button on my phone)

**Comment by ColCh** [comment] 2016-12-09 14:54
You can revert update to RN v0.39 also ... v0.38 works nice :)

**Comment by lohithananda** [comment] 2016-12-09 15:41
Thank u soo much:)@ColCh

**Comment by smhatre59** [comment] 2016-12-09 17:24
Issue exists on react native v0.39.1
Solution suggested by @karpoff  works 
Thank you so much

**Comment by busterkikas** [comment] 2016-12-09 19:02
I've been running a day running my first application and I can not believe the mistake was this ...

It works for me too...

Thanks @karpoff

**Comment by gabrielgomesferraz** [comment] 2016-12-09 19:48
Thank u soo much:)@ColCh

**Comment by EQuimper** [comment] 2016-12-09 23:34
@karpoff Thank you :)

**Comment by pratik151192** [comment] 2016-12-10 00:23
@karpoff Hi, I'm having trouble locating the file. I do not have the Libraries folder at all under ../npm/node-modules/react-native-cli.....there's another node-modules folder in it which doesn't have the Libraries folder either

**Comment by EQuimper** [comment] 2016-12-10 00:35
@pratik151192 this is not in the react-native-cli this is under the node_modules/react-native/ inside you project

**Comment by pratik151192** [comment] 2016-12-10 01:02
Argh! My bad! Thanks @EQuimper

**Comment by arv** [comment] 2016-12-10 04:12
The reason this fails on Android is because RN uses an ancient version of JSC which does not support lexical function declarations.

There is a babel plugin that fixes this (since updating JSC is a big project #10245)

https://babeljs.io/docs/plugins/transform-es2015-block-scoping/

Can we add this plugin to the current babel preset?

**Comment by PuYart** [comment] 2016-12-10 05:22
@arv While I add `babel-plugin-transform-es2015-block-scoping` like this:

```json
{
  "presets": ["react-native"],
  "plugins": ["transform-es2015-block-scoping"]
}
```

Issue also exists

**Comment by raitucarp** [comment] 2016-12-10 10:23
Please fix this issue and update react @facebook-github-bot

**Comment by bozzmob** [comment] 2016-12-10 19:51
Hope this gets merged soon. Lot of applications are failing after update.

**Comment by snsekar** [comment] 2016-12-11 06:05
+1

**Comment by d0ptnow** [comment] 2016-12-11 07:09
+1

**Comment by cyclops24** [comment] 2016-12-11 07:25
I also have same problem. Did it fixed?

**Comment by mattisx** [comment] 2016-12-11 11:25
+1

**Comment by dennisfleischmann** [comment] 2016-12-11 15:09
+1

**Comment by raulinoneto** [comment] 2016-12-11 18:22
@karpoff work it for me too, thank you.

**Comment by nikolal** [comment] 2016-12-11 20:06
The same issue. 
I solved it by downgrading to react-native 0.38.

Thanks @ColCh

**Comment by karpoff** [comment] 2016-12-11 20:26
https://github.com/facebook/react-native/pull/11390 is merged to master
so issue will be fixed in 0.40

**Comment by grabbou** [comment] 2016-12-11 22:08
Shipped to 0.39.2.

**Closed by grabbou** 2016-12-11 22:08 UTC

**Comment by nmfzone** [comment] 2016-12-12 05:11
@grabbou So, when 0.39.2 will be available in NPM registry?

**Comment by gnanaprakash** [comment] 2016-12-12 10:42
Works fine on with react-native version 0.39.2.

**Comment by TannerPlauche** [comment] 2016-12-13 20:55
Just wanna say thanks to @karpoff for the work around! Worked!

**Comment by cavilaho** [comment] 2016-12-14 09:33
Thank you so much @karpoff ! Why was it happening, just out of curiosity?

**Comment by karpoff** [comment] 2016-12-14 10:00
@cavilaho have no idea :)
ColCh has guessed that it probably caused by npm cache - different babel versions are used
you can see his comment in pull request https://github.com/facebook/react-native/pull/11390

**Comment by cavilaho** [comment] 2016-12-14 11:39
@karpoff On my way. Thanks again!

**Comment by yudori** [comment] 2016-12-15 13:41
@karpoff Works like charm! Thanks

**Comment by TannerPlauche** [comment] 2016-12-15 16:40
This bug has been fixed. If you `react-native init` a new project now, you will see that this code/bug has been changed.

**Comment by markbiek** [comment] 2016-12-15 18:46
@TannerPlauche What's the process for fixing an existing project?

Doing a `react-native upgrade` doesn't do it.

**Comment by TannerPlauche** [comment] 2016-12-15 19:02
I think you might have to do `npm upgrade`, but that would upgrade all of your node modules, not just react native. Otherwise I would just do Karpoff's solution. It's the 5th response from the top.

**Comment by ryanhomer** [comment] 2017-01-12 00:01
🥇 Fixed on React Native 0.40.0

**Comment by jeremyeaton89** [comment] 2017-01-19 18:05
0.39.2 includes a fix

**Comment by niranjan-b-prajapati** [comment] 2017-02-20 07:51
I have an app which till yesterday was working properly and i have to implement new plugin so i switched to different branch on my git flow and installed that plugin, but i had got to make build for client it was the urgent requirement so i switched back to develop branch and removed node_modules folder and did NPM install but after that i started getting following issue:SyntaxError: Strict mode does not allow function declarations in a lexically nested statement I checked the work around solution you provided about opening node_modules\react-native\Libraries\Core\InitializeCore.js line 112 and making required changes. but in my react-native\Libraries\ folder in node_modules i am not able to see Core folder nor am i able to find InitializeCore.js in whole react-native folder. 


Following are my versions of react & react-native mentioned in package.json:
"react": "15.3.1",
"react-native": "0.34.1", 

And the application has to be uploaded to play store in next 2 days. So i am not in a position to upgrade react-native version also.

Please suggest some solution.
Stuck badly.

**Comment by dhuidrom** [comment] 2017-02-21 10:31
@niranjan-b-prajapati   update react and react-native to
 "react": "~15.4.0",
  "react-native": "^0.41.2"
  Delete node-modules of your project and install npm.
  For me it works.

**Comment by rohan-sethi** [comment] 2017-02-21 17:08
@lednhatkhanh Thanks ! you saved my life.

**Comment by taozijie** [comment] 2017-02-22 06:28
I can't find node_modules\react-native\Libraries\Core\InitializeCore.js,Whta to do? @ @Taximan @

**Comment by vijayperlakota** [comment] 2017-02-22 06:40
+ 1 @karpoff your solution works. Thanks :)

**Comment by LitbLeo** [comment] 2017-02-22 09:24
@taozijie @Taximan Me too,what to do?My version is 0.34.1

**Comment by vijayperlakota** [comment] 2017-02-22 11:41
@LitbLeo try this

open node_modules\react-native\Libraries\Core\InitializeCore.js line 112
change function handleError(e, isFatal) to var handleError = function(e, isFatal)
then do npm start -- --reset-cache

Solution suggested by @karpoff

**Comment by quietbits** [comment] 2017-02-22 15:42
Another way to "fix" this, if you can't update to a newer version yet, is to enable JS Minify mode in Dev Settings. Works on version 0.34.0.

**Comment by LitbLeo** [comment] 2017-02-23 01:50
@vijayperlakota Thanks!But i can not find the file node_modules\react-native\Libraries\Core\InitializeCore.js  
in my version of 0.34.1,so i do not konw how to fix this issue.

**Comment by LitbLeo** [comment] 2017-02-23 02:31
@quietbits Thanks,this way can fix this issue!

**Comment by karpoff** [comment] 2017-02-23 10:40
@LitbLeo looks like this code is in another place in 0.34.1
try to open node_modules\react-native\Libraries\JavaScriptAppEngine\Initialization\InitializeJavaScriptAppEngine.js line 120 and change function handleError(e, isFatal) to var handleError = function(e, isFatal)
then do npm start -- --reset-cache

**Comment by LitbLeo** [comment] 2017-02-24 02:23
@karpoff  Thanks!

**Comment by santhosh77h** [comment] 2017-02-25 12:01
@karpoff I did that still i'm getting the same error
But if i run using debug  js remotely it works fine

**Comment by MorrisDa** [comment] 2017-02-25 16:49
Me too, same error

**Comment by mkoo21** [comment] 2017-03-01 18:42
Same issue on RN 0.35
Tried changing the declaration of`handleError`, still get same issue
This issue suddenly appeared in all of our android apps around 2 weeks ago

**Comment by futurechallenger** [comment] 2017-03-04 06:46
I got this problem because i started a 0.39 package server before i start the 0.41 one. Turn the 0.39 one off, then start 0.41 again. everything works fine!

**Comment by empitechathu** [comment] 2017-03-14 19:35
@karpoff  ur solution is not working mate :(

**Comment by empitechathu** [comment] 2017-03-14 19:35
im having "react-native": "0.29.0",

**Comment by blackPeanut** [comment] 2017-03-20 14:56
For everyone who still facing this error try to edit _**node_modules/react-native/Libraries/Utilities/UIManager.js**_ file and replace:

```function normalizePrefix(moduleName: string): string {``` 
with
```var normalizePrefix = function (moduleName: string): string {```

This worked for me, 
referencing superfe [issue](https://github.com/super-fe/superfe-rn-troubleshooting/issues/7)

**Comment by arsenslyusarchuk** [comment] 2017-03-20 21:05
Running React-native 0.35 and having same issue -- this is what helped to me

* In node_modules/react-native/Libraries/BatchedBridge/BatchedBridgedModules/NativeModules.js 

    `function normalizePrefix(moduleName: string) ...`

  REPLACE WITH:

    `const normalizePrefix = function(moduleName: string)`

* In /node_modules/react-native/Libraries/Utilities/UIManager.js:

    `function normalizePrefix(moduleName: string) ...`

  REPLACE WITH:

    const normalizePrefix = function(moduleName: string)

* In InitializeJavascriptAppEngine.js:

    `function handleError(e, isFatal) ...`

  REPLACE WITH:

    `var handleError = function(e, isFatal)`


then do npm start -- --reset-cache

**Comment by jcbiznoff** [comment] 2017-03-21 00:50
@arsenslyusarchuk  this works for me well. I was having so much problem before.

**Comment by ariona** [comment] 2017-03-24 04:31
I am using react-native 0.39, and the solution from @karpoff works for me :) https://github.com/facebook/react-native/issues/11389#issuecomment-265995961

**Comment by arsenslyusarchuk** [comment] 2017-03-24 07:43
@ariona Yes, for 0.39 it works, but for 0.35 (which I'm using) there is no such file at all. If I remember correctly, it appeared in 0.36 or 0.37

**Comment by blackPeanut** [comment] 2017-03-25 09:49
for 0.35 [this](https://github.com/facebook/react-native/issues/11389#issuecomment-287784965) solution works just great

**Comment by huhanghao** [comment] 2017-03-29 07:27
my react-native version is "0.31.0"。set emulator dubug js remote works,but my emulator runs slowly.I'm finding another way to save it. God bless me.

**Comment by huhanghao** [comment] 2017-03-29 07:37
thx to @niranjan-b-prajapati ,I change my react version to v15.4.0 , my react-native to 0.41.2. It works to me

**Comment by cubbuk** [comment] 2017-04-03 13:11
Had the same exact issue out of blue sky with RN `0.31` @arsenslyusarchuk' suggestion fixed it for me, have no idea why it has started, it was working fine

**Comment by dmueller39** [comment] 2017-04-13 14:50
For the lazy:
```
# formatted for OSX: http://stackoverflow.com/questions/19456518/invalid-command-code-despite-escaping-periods-using-sed
sed -i '' -e 's/function normalizePrefix(moduleName: string)/const normalizePrefix = function(moduleName: string)/g' ./node_modules/react-native/Libraries/BatchedBridge/BatchedBridgedModules/NativeModules.js

sed -i '' -e 's/function normalizePrefix(moduleName: string)/const normalizePrefix = function(moduleName: string)/g' ./node_modules/react-native/Libraries/Utilities/UIManager.js

sed -i '' -e 's/function handleError(e, isFatal)/var handleError = function(e, isFatal)/g' ./node_modules/react-native/Libraries/JavaScriptAppEngine/Initialization/InitializeJavaScriptAppEngine.js

# check that it worked
grep normalize ./node_modules/react-native/Libraries/BatchedBridge/BatchedBridgedModules/NativeModules.js

grep normalize ./node_modules/react-native/Libraries/Utilities/UIManager.js

grep handleError ./node_modules/react-native/Libraries/JavaScriptAppEngine/Initialization/InitializeJavaScriptAppEngine.js

```

**Comment by CandyKTN** [comment] 2017-04-25 09:55
@dmueller39 it works, do u know what caused it?

**Comment by Glaucoweb** [comment] 2017-05-25 13:30
This is problem in a Network! Active mode Remote JS Debuggin in APP!
It worked here!

**Comment by jwerlley** [comment] 2017-06-13 13:27
Just activate a JS Minify option in the Emulator Dev Settings

    In Emulator: Menu > Dev Settings > JS Minify ☑(active)

Here it worked only with this, I hope it has helped;)

**Comment by Youngdi** [comment] 2017-07-04 07:43
Hey, guys, I found the same issue on RN `45.1` install on ios` 9.3`.

**Comment by TheCodeDestroyer** [comment] 2017-07-28 07:51
Same happens in `v0.46.1`

**Comment by developer239** [comment] 2017-07-28 19:38
Fuck my life

**Comment by jrempel1** [comment] 2017-07-31 04:09
This is occurring in 0.46.4.

`07-31 00:07:35.786 4831-5376/com.nycevents E/ReactNativeJNI: Got JS Exception: SyntaxError: Strict mode does not allow function declarations in a lexically nested statement. (http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:1583)
07-31 00:07:35.786 4831-5376/com.nycevents E/unknown:React: Exception in native call from JS
                                                            com.facebook.react.devsupport.JSException: SyntaxError: Strict mode does not allow function declarations in a lexically nested statement. (http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:1583)
                                                                at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                at android.os.Looper.loop(Looper.java:148)
                                                                at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
                                                                at java.lang.Thread.run(Thread.java:818)
                                                             Caused by: com.facebook.jni.CppException: SyntaxError: Strict mode does not allow function declarations in a lexically nested statement. (http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:1583)
                                                                at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                at android.os.Handler.handleCallback(Handler.java:739) 
                                                                at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                                                                at android.os.Looper.loop(Looper.java:148) 
                                                                at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194) 
                                                                at java.lang.Thread.run(Thread.java:818) 
07-31 00:07:35.788 4831-5376/com.nycevents E/unknown:React: Exception in native call
                                                            java.lang.RuntimeException: Error calling AppRegistry.runApplication
                                                                at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                at android.os.Looper.loop(Looper.java:148)
                                                                at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
                                                                at java.lang.Thread.run(Thread.java:818)
                                                             Caused by: com.facebook.jni.CppException: Could not get BatchedBridge, make sure your bundle is packaged correctly
                                                                at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                at android.os.Handler.handleCallback(Handler.java:739) 
                                                                at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                                                                at android.os.Looper.loop(Looper.java:148) 
                                                                at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194) 
                                                                at java.lang.Thread.run(Thread.java:818) `

**Comment by brunocascio** [comment] 2017-07-31 21:53
I'm facing the same issue @jrempel1. Any fix?

**Comment by NickAnthony** [comment] 2017-08-02 05:31
Updated react-native to version 0.47.0 and it fixed it.

**Comment by Ashoat** [comment] 2017-08-02 18:08
I am seeing this issue in 0.47.0 and 0.47.1 on Android. The error doesn't seem to indicate the actual file and line where it's occurring.

**Comment by jrempel1** [comment] 2017-08-02 23:51
I was able to resolve with:
```
-    "react": "^16.0.0-beta.1",
+    "react": "16.0.0-alpha.12",

```

**Comment by wootwoot1234** [comment] 2017-08-04 16:19
@jrempel1 what version of react native are you running with "react": "16.0.0-alpha.12"?

**Comment by wootwoot1234** [comment] 2017-08-04 16:20
I'm seeing the issue and running:

    "react": "^16.0.0-alpha.12",
    "react-native": "^0.47.0",

**Comment by jorge8989** [comment] 2017-08-24 16:09
hey @arsenslyusarchuk  thanks a lot! your hack saved my day. Can you explain how did you come to that solution?

**Comment by chishui** [comment] 2017-10-09 06:51
Same failure on ios8 with combination:
```
"react": "16.0.0-alpha.6",
"react-native": "0.44.2",
```
Any solution for this?

**Comment by Macstyg** [comment] 2017-10-27 13:55
Same for the 
```
"react": "16.0.0-beta.5",
"react-native": "0.49.3",
```
after upgrade from the 46.3 version.

**Comment by marcianoviereck** [comment] 2017-11-02 13:49
For me, the issue was that 'use strict' was not enabled by babel (suddenly).

I used this plugin and modified my .babelrc to set the "strict" to false, then remade the bundle for android and restarted the emulator and then it worked again!

https://www.npmjs.com/package/babel-plugin-transform-strict-mode

**Comment by wlwl2** [comment] 2017-11-10 20:52
@jwerlley solution worked the best for me. No hacks e.g. changing node_modules, or any of my dependencies, or babel.

**Comment by lotosbin** [comment] 2017-11-13 19:24
"react": "15.3.1",
"react-native": "^0.34.1",
in node_modules/react-native/Libraries/Utilities/UIManager.js
remove 'use strict';

```
gulp.task('fix', () =>
    gulp.src('node_modules/react-native/Libraries/Utilities/UIManager.js')
        .pipe(replace(/\'use\ strict\'\;/g, ''))
        .pipe(gulp.dest('node_modules/react-native/Libraries/Utilities/')));
```

**Comment by rawrmaan** [comment] 2017-12-11 04:13
This is still happening to me in 0.51.0 and none of the fixes above work in Android 8.0 simulator. This is awful :(

**Comment by flavio-dev** [comment] 2018-01-19 14:26
Hello:
"react": "16.2.0"
"react-native": "0.52.0"

with a .babelrc using that plugin you mentioned @marcianoviereck :
```{
  "presets": [
    "babel-preset-react-native-stage-0/decorator-support"
  ],
  "env": {
    "development": {
      "plugins": [
        "transform-react-jsx-source",
        ["transform-strict-mode", {
          "strict": false
        }]
      ]
    }
  },
  "plugins": [
    ["transform-strict-mode", {
      "strict": false
    }]
  ]
}
```

and I have the problem when Remote Debug JS is off. Works ok when Remote JS is on.

Anyone else?

Thank you!

**Comment by Ciberusps** [comment] 2018-02-02 03:14
For all who want to solve problem.

Mb u want to add babel plugin which add "use strict" just delete it.
1) Delete it from .babelrc
2) npm start -- --reset-cache
All works.
