### ISSUE TITLE
Problem while making react native to run using npx

### ISSUE THREAD

**Issue by soberservicesguy** [facebook/react-native#28722] opened 2020-04-22 05:58 UTC
## Description
I am having problem in setting up react native, previously I was using with expo so was not having problem but I needed to use AsyncStorage so I went to use npx instead.
The screenshots of bug are attached
![Kazam_screenshot_00000](https://user-images.githubusercontent.com/54809206/79945822-19b60780-8488-11ea-8835-b90042e976f2.png)
![Kazam_screenshot_00001](https://user-images.githubusercontent.com/54809206/79945823-1c186180-8488-11ea-8b72-d3fb79ce2490.png)

## React Native version:
System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 168.68 MB / 7.65 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 10.20.1 - /usr/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.14.4 - /usr/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.6 - /usr/bin/javac
    Python: 2.7.17 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
so I created new app using 
`npx react-native init my_app`  
and then I entered its directory then I ran 
`npm install` 
so that it installs its dependencies from file,  then I created this folder 
`mkdir android/app/src/main/assets` 
, then I ran  
`react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res`
 then I started android studio and openned the android folder in the app and it updated its gradle probably, then I ran 
`adb reverse tcp:8081 tcp:8081` 
 finally I ran 
`npx react-native run-android --port=8081` . 
 Build was successful, before running the final command I had my emulator on. It does try to show app but it goes on error. 

## Expected Results
Expected was it to run properly like it used to in expo.

## Snack, code example, screenshot, or link to a repository:
The complete code is in the repo 
https://github.com/soberservicesguy/bug_containing_app/tree/master/portfolio_app_1_proper

**Comment by safaiyeh** [comment] 2020-04-22 17:24
The error looks like your own defined `userToken` variable in your project. A quick search of it https://github.com/soberservicesguy/bug_containing_app/search?q=userToken&unscoped_q=userToken

This seem like an issue with your setup, could you create a smaller reproducible demo with an issue coming from core? Closing for now as this is not actionable on our end.

**Closed by safaiyeh** 2020-04-22 17:24 UTC
Labels: Needs: Triage :mag:, Platform: Linux
