### ISSUE TITLE
App crashes when using geolocation when ACCESS_FINE_LOCATION permission is missing

### ISSUE THREAD

**Issue by laurent22** [facebook/react-native#15034] opened 2017-07-16 09:53 UTC
### Is this a bug report?

yes

### Steps to Reproduce

1. Use geolocation without ACCESS_FINE_LOCATION permission
2. Application crashes

### Expected Behavior

I would expect an error message or a dialog to authorise ACCESS_FINE_LOCATION.

### Stacktrace

```
07-16 10:43:40.786 10457 10457 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {net.cozic.joplin/net.cozic.joplin.MainActivity}: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
07-16 10:43:40.786 10457 10457 E AndroidRuntime:        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3493)
07-16 10:43:40.786 10457 10457 E AndroidRuntime:        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3533)
07-16 10:43:40.786 10457 10457 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1558)
07-16 10:43:40.786 10457 10457 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
07-16 10:43:40.786 10457 10457 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:241)
07-16 10:43:40.786 10457 10457 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6274)
07-16 10:43:40.786 10457 10457 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-16 10:43:40.786 10457 10457 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
07-16 10:43:40.786 10457 10457 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
07-16 10:43:40.786 10457 10457 E AndroidRuntime: Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
07-16 10:43:40.786 10457 10457 E AndroidRuntime:        at com.facebook.react.modules.permissions.PermissionsModule$1.invoke(PermissionsModule.java:119)
07-16 10:43:40.786 10457 10457 E AndroidRuntime:        at com.facebook.react.modules.permissions.PermissionsModule.onRequestPermissionsResult(PermissionsModule.java:207)
07-16 10:43:40.786 10457 10457 E AndroidRuntime:        at com.facebook.react.ReactActivityDelegate$1.invoke(ReactActivityDelegate.java:211)
07-16 10:43:40.786 10457 10457 E AndroidRuntime:        at com.facebook.react.ReactActivityDelegate.onResume(ReactActivityDelegate.java:131)
07-16 10:43:40.786 10457 10457 E AndroidRuntime:        at com.facebook.react.ReactActivity.onResume(ReactActivity.java:66)
07-16 10:43:40.786 10457 10457 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1270)
07-16 10:43:40.786 10457 10457 E AndroidRuntime:        at android.app.Activity.performResume(Activity.java:6824)
07-16 10:43:40.786 10457 10457 E AndroidRuntime:        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3470)
07-16 10:43:40.786 10457 10457 E AndroidRuntime:        ... 8 more
```

**Comment by hramos** [comment] 2017-07-17 20:32
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-07-17 20:32 UTC
