### ISSUE TITLE
Android device only show blank screen and crash after build success

### ISSUE THREAD

**Issue by Adamnator92** [facebook/react-native#15617] opened 2017-08-23 08:47 UTC
### Is this a bug report?
Yes

1. `react-native -v`:0.47.1
2. `node -v`: v6.9.2
3. `npm -v`: 3.10.9

- Target Platform: Android & IOS
- Development Operating System: macOS

### Steps to Reproduce

build app on android device, it show only white blank screen and crash after force quit and touch the screen,  it didnt show any error message at all.

*everything is run perfectly on IOS device.

**Comment by dinithminura** [comment] 2017-08-23 10:00
I faced the same issue, but in my scenario I was trying to upgrade react native from 0.36.0 to 0.47.1 and resolved other issues. Still getting the issue.

**Comment by hramos** [comment] 2017-08-23 19:18
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-08-23 19:18 UTC

**Comment by zhangkaiyulw** [comment] 2017-12-04 05:17
This bug happens with react-native 0.50.4
