### ISSUE TITLE
Can not start a new project on Ubuntu 16.04, RN 35

### ISSUE THREAD

**Issue by Tiagojdferreira** [facebook/react-native#10375] opened 2016-10-13 21:15 UTC
### Issue Description

Just did a fresh install of React Native on ubuntu and I can not start a new project.
I am using nvm to run node v6.3.1, with npm 3.10.3.
I installed Android-studio, set up path variables, and installed watchman.
Android-studio works fine. (I can start an empty project)
Watchman works fine.

```
watchman -v
4.7.0
```
### Steps to Reproduce / Code Snippets

npm install -g react-native-cli
react-native init AwesomeProject
#### Expected Results

Get the following error:

```
$ react-native init AwesomeProject
This will walk you through creating a new React Native project in /home/tiago/Documents/projects/AwesomeProject
Installing react-native package from npm...
Setting up new React Native app in /home/tiago/Documents/projects/AwesomeProject
module.js:442
    throw err;
    ^

Error: Cannot find module './src/init'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/tiago/Documents/projects/AwesomeProject/node_modules/gulp-sourcemaps/index.js:4:9)
    at Module._compile (module.js:541:32)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/tiago/Documents/projects/AwesomeProject/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)

```
### Additional Information
- React Native version: 
  react-native-cli: 1.0.0
  react-native: 0.34.0
- Platform(s) (iOS, Android, or both?): Android
- Operating System (macOS, Linux, or Windows?): Linux Ubuntu 16.04 LTS Xenial 64-bit

**Comment by dtoebe** [comment] 2016-10-13 21:17
Same issue here on Ubuntu 16.10 and Node Ver: 6.8.0;

**Comment by bmathews** [comment] 2016-10-13 21:34
Caused by https://github.com/floridoo/gulp-sourcemaps/issues/238

**Comment by sbalay** [comment] 2016-10-13 21:35
Is there any workaround until the issue in gulp-sourcemaps gets resolved?

**Comment by nicbarker** [comment] 2016-10-13 21:40
Same issue here on OSX 10.11.6

**Comment by Tiagojdferreira** [comment] 2016-10-13 21:45
Go to the folder and do:
```
npm install gulp-sourcemaps@1.6
npm install
react-native android
```
Then just run the

**Comment by sbalay** [comment] 2016-10-13 21:53
@Tiagojdferreira's solution works great. A little clarification for those starting a new project
```
mkdir project
cd project
npm i gulp-sourcemaps@1.6
cd ..
react-native init project
```

**Comment by nicbarker** [comment] 2016-10-13 22:05
Great, thanks @sbalay and @Tiagojdferreira this fixed the issue for me.

**Comment by lacker** [comment] 2017-02-09 22:56
I'm closing since there's a workaround here. Thanks folks for chiming in with fixes!

**Closed by lacker** 2017-02-09 22:56 UTC
