### ISSUE TITLE
ListView scrolling in Apple TV (TV OS)

### ISSUE THREAD

**Issue by milhauscz** [facebook/react-native#12793] opened 2017-03-08 12:10 UTC
### Description

In an Apple TV app I use a horizontal ListView. When the last visible item is focused, sometimes the ListView starts frantically scrolling, reaches the end of the ListView and then even bounces back and scrolls to the first item again.

### Reproduction

Can be reproduced with both horizontal and vertical ListView. It seems that the bug occurs more if the items inside the ListView are bigger.

### Solution

So far I didn't find any solution.

### Additional Information

* React Native version: 0.42
* Platform: TV OS (Apple TV)
* Operating System: MacOS

**Comment by hramos** [comment] 2017-03-08 23:12
cc @dlowder-salesforce

**Comment by dlowder-salesforce** [comment] 2017-03-08 23:27
I'll take a look....

**Comment by dlowder-salesforce** [comment] 2017-03-08 23:41
Yep if you scale up the grid cells in `ListViewGridLayoutExample.js` this is pretty reproducible.  Looks like a bad interaction between native scrolling by the focus engine and ScrollView code.  This will take some time to debug properly.

**Comment by dlowder-salesforce** [comment] 2017-03-09 23:45
Debugging indicates that the problem is all happening on the native side -- setting breakpoints or modifying JS code has no effect.

**Comment by dlowder-salesforce** [comment] 2017-03-10 01:19
Native debugging indicates that the problem is actually in the way the focus engine implements scrolling, and there are some recommendations on how to fix this.... https://forums.developer.apple.com/thread/19638

**Comment by shergin** [comment] 2017-03-10 20:54
Possible related: https://github.com/facebook/react-native/issues/12374

**Comment by dlowder-salesforce** [comment] 2017-03-10 21:15
@milhauscz this can be fixed by setting the ListView's removeClippedSubviews property to false.  Otherwise, tvOS will believe that the bottommost unclipped view is the last one, and try to scroll all the way to the bottom of the view, leading to the unpleasant behavior you are seeing.  For example code see the commits in https://github.com/dlowder-salesforce/react-native/tree/tvos-listview

**Comment by dlowder-salesforce** [comment] 2017-03-11 01:02
https://github.com/dlowder-salesforce/react-native/tree/tvos-listview-fix has a modification to actually fix this for all ListViews, and some changes to the UIExplorer ListViewGridLayoutExample.  When you run the example on tvOS with these changes, the scrolling problem is fixed, and also you can actually see new cells render at the bottom of the screen as you navigate down using the TV remote.

**Comment by milhauscz** [comment] 2017-03-13 11:36
@dlowder-salesforce Works like a charm, thank you for your help!

**Comment by shergin** [comment] 2017-03-15 20:42
@dlowder-salesforce, @milhauscz I would love to fix this issue properly... but... Could you please confirm one more time: Does setting `removeClippedSubviews` really fix the problem?
I am asking because... I double check and found that setting `removeClippedSubviews` for `UIScrollView` **does literally nothing**, the proof: https://github.com/facebook/react-native/blob/5353d39172034d04114f8e498fc983b92a786a78/React/Views/RCTScrollView.m#L380

**Comment by dlowder-salesforce** [comment] 2017-03-15 21:33
@shergin Yes it really fixes the problem... PR #12944 fixes it on the JS side.

**Comment by dlowder-salesforce** [comment] 2017-03-15 21:44
Inspecting the code, it seems that the real implementation that uses `removeClippedSubviews` is in `RCTView.m` and `RCTViewManager.m`

**Comment by shergin** [comment] 2017-03-15 22:24
@dlowder-salesforce Oh, thank you! I missed that this property is also proxied to `ScrollContentContainerViewClass`.

**Comment by hramos** [comment] 2017-07-25 22:57
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Closed by hramos** 2017-07-25 22:57 UTC
Labels: Icebox, iOS
