### ISSUE TITLE
Flatlist: Rows disappear when scrolling fast

### ISSUE THREAD

**Issue by ragnorc** [facebook/react-native#13658] opened 2017-04-25 12:46 UTC
When scrolling fast rows disappear and reappear again. Additionally, scroll performance is really bad although I am using PureComponent for the rows.

### Additional Information

* React Native version: 0.43
* Platform: iOS
* Development Operating System:  MacOS

**Comment by hramos** [comment] 2017-04-25 13:16
Can you provide a minimal amount of code to reproduce this using [Snack](http://snack.expo.io)? This is necessary for people to be able to see and debug the issue being reported.

Closing this issue as it is not actionable. Please open a new one with a Snack link (preferred), or link to a GitHub repo with clear instructions how to repro.

**Closed by hramos** 2017-04-25 13:16 UTC

**Comment by annelorraineuy** [comment] 2017-06-14 21:17
I encountered this issue too, but it's difficult because repro rate isn't 100% of the time. Not certain what factors cause this yet.

**Comment by axelphunter** [comment] 2017-08-11 09:34
+1

**Comment by wellyal** [comment] 2017-11-28 18:38
I'm also facing this problem. When all items are loaded and I try to scroll all the way back with a fast scroll, the items disappear for a moment and it shows again on the list.
