### ISSUE TITLE
React Native Linking  openURL with "index.bundle:7693 Native module cannot be null" error

### ISSUE THREAD

**Issue by jackchou** [facebook/react-native#17903] opened 2018-02-08 07:06 UTC
I am wroking with react native 0.49, when i import Linking from react- native , and open a web link like "https://www.google.com", i get  `Native module cannot be null` errors, any one can help me what should I do for this error ? thanks all.

my code here
```
import {
    Text,
    View,
    ImageBackground,
    NativeModules,
    TouchableWithoutFeedback,
    Linking
} from 'react-native';


//use
Linking.openURL("https://www.google.com")
```
error stack
```
Native module cannot be null.
handleException @ index.bundle:7693
handleError @ index.bundle:10996
reportFatalError @ index.bundle:697
guardedLoadModule @ index.bundle:80
_require @ index.bundle:63
get Linking @ index.bundle:1514
(anonymous) @ VM42:1
onClickSplashScreen @ index.bundle:58474
proxiedMethod @ index.bundle:27523
onPress @ index.bundle:58504
touchableHandlePress @ index.bundle:43892
_performSideEffectsForTransition @ index.bundle:38191
_receiveSignal @ index.bundle:38128
touchableHandleResponderRelease @ index.bundle:38017
_invokeGuardedCallback @ index.bundle:2553
invokeGuardedCallback @ index.bundle:2527
invokeGuardedCallbackAndCatchFirstError @ index.bundle:2530
executeDispatch @ index.bundle:2613
executeDispatchesInOrder @ index.bundle:2620
executeDispatchesAndRelease @ index.bundle:6230
executeDispatchesAndReleaseTopLevel @ index.bundle:6236
forEachAccumulated @ index.bundle:6225
processEventQueue @ index.bundle:6296
runEventQueueInBatch @ index.bundle:6540
handleTopLevel @ index.bundle:6544
(anonymous) @ index.bundle:6572
batchedUpdates @ index.bundle:5651
performFiberBatchedUpdates @ index.bundle:2710
stackBatchedUpdates @ index.bundle:2704
batchedUpdates @ index.bundle:2713
batchedUpdatesWithControlledComponents @ index.bundle:2720
_receiveRootNodeIDEvent @ index.bundle:6571
receiveTouches @ index.bundle:6586
__callFunction @ index.bundle:2086
(anonymous) @ index.bundle:1902
__guard @ index.bundle:2057
MessageQueue.callFunctionReturnFlushedQueue @ index.bundle:1901
(anonymous) @ debuggerWorker.js:72
index.bundle:7693 Requiring module "Linking", which threw an exception: Invariant Violation: Native module cannot be null.
handleException @ index.bundle:7693
handleError @ index.bundle:10996
reportFatalError @ index.bundle:697
guardedLoadModule @ index.bundle:80
_require @ index.bundle:63
get Linking @ index.bundle:1514
onClickSplashScreen @ index.bundle:58478
proxiedMethod @ index.bundle:27523
onPress @ index.bundle:58504
touchableHandlePress @ index.bundle:43892
_performSideEffectsForTransition @ index.bundle:38191
_receiveSignal @ index.bundle:38128
touchableHandleResponderRelease @ index.bundle:38017
_invokeGuardedCallback @ index.bundle:2553
invokeGuardedCallback @ index.bundle:2527
invokeGuardedCallbackAndCatchFirstError @ index.bundle:2530
executeDispatch @ index.bundle:2613
executeDispatchesInOrder @ index.bundle:2620
executeDispatchesAndRelease @ index.bundle:6230
executeDispatchesAndReleaseTopLevel @ index.bundle:6236
forEachAccumulated @ index.bundle:6225
processEventQueue @ index.bundle:6296
runEventQueueInBatch @ index.bundle:6540
handleTopLevel @ index.bundle:6544
(anonymous) @ index.bundle:6572
batchedUpdates @ index.bundle:5651
performFiberBatchedUpdates @ index.bundle:2710
stackBatchedUpdates @ index.bundle:2704
batchedUpdates @ index.bundle:2713
batchedUpdatesWithControlledComponents @ index.bundle:2720
_receiveRootNodeIDEvent @ index.bundle:6571
receiveTouches @ index.bundle:6586
__callFunction @ index.bundle:2086
(anonymous) @ index.bundle:1902
__guard @ index.bundle:2057
MessageQueue.callFunctionReturnFlushedQueue @ index.bundle:1901
(anonymous) @ debuggerWorker.js:72
index.bundle:7693 Cannot read property 'openURL' of undefined
handleException @ index.bundle:7693
handleError @ index.bundle:10996
reportFatalError @ index.bundle:697
__guard @ index.bundle:2059
MessageQueue.callFunctionReturnFlushedQueue @ index.bundle:1901
(anonymous) @ debuggerWorker.js:72
index.bundle:7701 Unhandled JS Exception: Native module cannot be null.
reactConsoleErrorHandler @ index.bundle:7701
console.error @ index.bundle:51390
logToConsole @ index.bundle:15618
logIfNoNativeHook @ index.bundle:15601
__callFunction @ index.bundle:2086
(anonymous) @ index.bundle:1902
__guard @ index.bundle:2057
MessageQueue.callFunctionReturnFlushedQueue @ index.bundle:1901
(anonymous) @ debuggerWorker.js:72
index.bundle:7701 Unhandled JS Exception: Requiring module "Linking", which threw an exception: Invariant Violation: Native module cannot be null.
reactConsoleErrorHandler @ index.bundle:7701
console.error @ index.bundle:51390
logToConsole @ index.bundle:15618
logIfNoNativeHook @ index.bundle:15601
__callFunction @ index.bundle:2086
(anonymous) @ index.bundle:1902
__guard @ index.bundle:2057
MessageQueue.callFunctionReturnFlushedQueue @ index.bundle:1901
(anonymous) @ debuggerWorker.js:72
index.bundle:7701 Unhandled JS Exception: Cannot read property 'openURL' of undefined
```

**Comment by hunterway55** [comment] 2018-02-08 13:27
Have you configured your native modules? To import native modules you need to have your own native code set up for both android and ios. 

Remove native modules from this import and it will work.

**Comment by hramos** [comment] 2018-02-09 20:41
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue that meets the requirements set forth in the template. Thanks!

**Closed by hramos** 2018-02-09 20:41 UTC
Labels: Failed Commands
