### ISSUE TITLE
[Android] borderStyle does not work with specific borderWidth (borderBottomWidth, etc).

### ISSUE THREAD

**Issue by awitherow** [facebook/react-native#11042] opened 2016-11-21 11:18 UTC
borderStyle does not work with specific borderWidth.

```
borderBottomWidth: 1,
borderBottomColor: '#979797',
borderStyle: 'dotted',
```

shows no dotted border.

**Comment by linmic** [comment] 2016-11-21 18:27
I assume this is a duplicate of #8236.

**Comment by armres** [comment] 2016-11-24 14:39
If set
`{
  borderWidth: 1,
  borderTopWidth: 0,
  borderLeftWidth: 0,
  borderRightWidth: 0,
  borderBottomColor: '#979797',
  borderStyle: 'dotted'
}`
It's work

**Comment by brentvatne** [comment] 2016-12-30 20:33
:+1: repro'd this

**Comment by mkonicek** [comment] 2016-12-31 01:29
Thanks for reporting. Any chance you could send a PR with a fix? :)

@brentvatne I believe this was owned by someone who doesn't work on RN anymore (possible to find out using blame info).

**Comment by brentvatne** [comment] 2016-12-31 17:28
cc @ahmedre as you're likely the most knowledgable person about this

**Comment by ahmedre** [comment] 2017-01-01 05:38
i am not really sure, but the border code in Android is [here](https://github.com/facebook/react-native/blob/1604f1088959428fab8cd4d3c451585d914464a9/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewBackgroundDrawable.java).

it looks like we have two cases - `drawRectangularBackgroundWithBorders` and `drawRoundedBackgroundWithBorders`. it seems that in this case, we go to the latter (because the style is not solid), which doesn't seem to support non-uniform borders. the easiest fix here would be to replace the if on line 105 with `if (!roundedBorders)`. this should work because styles can be applied on `Path`s, and `drawRectangularBackgroundWithBorders` also generates a `Path` to draw the borders now.

if no one gets to this before Tuesday, i can give it a shot.

**Closed** 2017-02-06 17:58 UTC

**Comment by Lxxyx** [comment] 2017-02-08 14:31
same problem.

**Comment by sospedra** [comment] 2017-04-03 15:47
+1 why is this closed?

**Comment by RobTS** [comment] 2017-04-12 09:25
+1 

Border turned solid after upgrading from RN 41.2 to 43.3. Styling:

```
  imagePlaceholder: {
    borderStyle: "dashed",
    margin: 10,
    padding: 30,
    alignItems: "center",
    borderColor: Colors.gray,
    borderWidth: 3
  },
```

**Comment by xiemeilong** [comment] 2017-05-24 08:06
+1

**Comment by cgx9** [comment] 2017-05-31 07:28
same problem. +1

**Comment by xsgkaka** [comment] 2017-06-09 17:05
i got the same problem

**Comment by adrianlemess** [comment] 2017-06-12 17:29
Same problem here, when I'm using borderTopRightRadius and to make a semi circle. When I'm put borderTopWidth, borderRightWidth and borderLeftWidth with value and borderBottomWidth 0, the border disappear. And if I'm just put borderWidth: value and borderBottomWIdth: 0 the border bottom showing again:
![image](https://user-images.githubusercontent.com/12432777/27046603-753a787e-4f7b-11e7-84d7-5b6d780ff347.png)
 and if I remove the borderTopRightRadius and borderTopLeftRadius: 
![image](https://user-images.githubusercontent.com/12432777/27046634-9508ac20-4f7b-11e7-9607-0926b317f887.png)

**Comment by zoharlevin** [comment] 2017-06-22 07:07
still happening as you can see here
https://github.com/facebook/react-native/issues/13464

**Comment by MrSpeedR** [comment] 2017-09-26 21:24
@adrianlemess Did you solve your problem? I have got same issue creating semi circle without bottom boarder.

**Comment by gregblass** [comment] 2017-10-09 18:07
Anyone know if this issue still open or if it's been resolved? Looks like it may have originated over a year ago. I'm still on 0.44, so just wondering if this was addressed in any of the later releases?

I think I can workaround it by just adding a `<View>` element to act as a faux-border, but would rather avoid that if an upgrade to the latest RN will fix it.

**Comment by AlanChauchet** [comment] 2017-11-08 16:02
@gregblass Still opened.
I have the same issue when using some style like
```
{ 
    backgroundColor: APP_COLOR,
    borderTopWidth: 4,
    borderRadius: 5,
}
```
As long as borderRadius is set, no top border at all

**Comment by wcandillon** [comment] 2017-12-02 21:09
I can confirm that this issue is still present in version `0.50.4`.

**Comment by kerwin1** [comment] 2017-12-25 10:00
I have the same problem(v0.47.2 on android)

**Comment by porluz** [comment] 2018-01-11 19:02
+1  "react": "16.0.0", "react-native": "0.50.3".

**Comment by sadi304** [comment] 2018-01-18 17:30
This issue needs to be addressed -__-. Been there for almost one and a half year

**Comment by sound2gd** [comment] 2018-01-22 01:50
+1 "react": "16.0.0", "react-native": "0.51".

**Comment by LouisJS** [comment] 2018-03-22 14:34
+1 "react": "16.2.0",
    "react-native": "0.52.0",

**Comment by orhanberamus** [comment] 2018-04-11 14:51
+1
