### ISSUE TITLE
[Android] [0.68.0] Cannot find symbols for new architecture upgrade

### ISSUE THREAD

**Issue by Mingyang-Li** [facebook/react-native#33623] opened 2022-04-13 00:26 UTC
### New Version
0.68.0

### Old Version
0.65.1

### Build Target(s)

Android - Pixel 4 (API 32)

### Output of `react-native info`

System:
    OS: Windows 10 10.0.19042
    CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
    Memory: 18.33 GB / 31.94 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.1.1 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowAllTrustedApps: Disabled
  IDEs:
    Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8193401
    Visual Studio: 17.0.31912.275 (Visual Studio Community 2022)
  Languages:
    Java: 1.8.0_312
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.0 => 0.68.0
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

**Issue**: Cannot find symbol `BuildConfig`
**Places issues detected:**
File `android\app\src\main\java\com\rndiffapp\MainApplication.java`
1. `import com.rndiffapp.newarchitecture.components.MainComponentsRegistry;`
2. `return BuildConfig.DEBUG;`
3. `if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED)`

Steps tried to debug:
1. Adding `import com.rndiffapp.BuildConfig;` for this file

**Issue**: Cannot find symbol MainComponentsRegistry
File `android\app\src\main\java\com\rndiffapp\newarchitecture\MainApplicationReactNativeHost.java`
1. `return new MainApplicationTurboModuleManagerDelegate.Builder();`
2. `MainComponentsRegistry.register(componentFactory);`

Steps tried to debug:
1. Adding `import com.rndiffapp.newarchitecture.components.MainComponentsRegistry;` to top of file
2. Addeding `import com.rndiffapp.newarchitecture.modules.MainApplicationTurboModuleManagerDelegate;` to top of file

Steps to reproduce:
1. Follow upgrade guide on https://react-native-community.github.io/upgrade-helper/?from=0.65.1&to=0.68.0
5. Keep updating files from the top all the way till `android/app/src/main/java/com/rndiffapp/MainApplication.java`
6. Open Android studio
7. Start running any virtual device
8. run `yarn android` or `npm run react-native`

**Comment by RalissonMattias** [comment] 2022-04-14 11:22
Try adding this to the top of your `MainApplication.java`
- Add `import com.facebook.react.BuildConfig;`

**Comment by finnp** [comment] 2022-04-25 12:17
I've run into the same issue when running react-native upgrade. Suggestion with BuildConfig didn't help and also wasn't really found here: https://react-native-community.github.io/upgrade-helper/?from=0.67.2&to=0.68.1

**Comment by finnp** [comment] 2022-04-25 12:34
In my case react native upgrade had failed to upgrade `android/app/build.gradle`. Not sure why, but adding these missing changes resolved the issues. However I realize that my issue wasn't the symbol `BuildConfig`. It was the `IS_NEW_ARCHITECTURE_ENABLED` symbol as this line was missing:

```
buildConfigField "boolean", "IS_NEW_ARCHITECTURE_ENABLED", isNewArchitectureEnabled().toString()
```

**Comment by Mingyang-Li** [comment] 2022-04-25 21:20
@finnp Ummm I'm gonna give your trick a try - will let you know

**Comment by swrobel** [comment] 2022-04-29 16:48
@finnp where'd you get this from and where does it go? I don't see `buildConfigField` in any of my app's files (or anywhere in RNDiffApp for that matter)
> ```
> buildConfigField "boolean", "IS_NEW_ARCHITECTURE_ENABLED", isNewArchitectureEnabled().toString()
> ```

**Comment by cortinico** [comment] 2022-05-03 13:16
As @finnp and @swrobel already mentioned, the issue is that you bumped your RN version to 0.68 **without** using `react-native upgrade` or the Upgrade Helper:
https://react-native-community.github.io/upgrade-helper/?from=0.65.1&to=0.68.1

You need to edit your `build.gradle` file to add a `buildConfigField` for "IS_NEW_ARCHITECTURE_ENABLED", otherwise it won't be possible to know at runtime if the New Architecture is enabled or not.

Closing as this looks resolved, feel free to reopen if this is not the case.

**Closed by cortinico** 2022-05-03 13:16 UTC
Labels: Platform: Android, Needs: Triage :mag:, Type: Upgrade Issue, New Architecture

**Comment by leotm** [comment] 2022-05-05 15:21
the diff can b a bit... iffy at times 😅 here's what we want

https://react-native-community.github.io/upgrade-helper/?from=0.65.1&to=0.69.0-rc.0

![Capture](https://user-images.githubusercontent.com/1881059/166953725-1ab3a393-64a5-44ba-aacc-44a0700ce05e.PNG)

to enable
- TurboModules (via `MainApplication.java`)
- Fabric (via `MainActivity.java`)

from `gradle.properties` when
- `newArchEnabled=true`

if that helps clarify @swrobel

**Comment by piscespieces** [comment] 2022-06-07 20:54
I don't understand.

Getting this same error out of nowhere, because I was already working with RN 68.1. I was able to run the Android app and to generate AAB and APK files. With all the stuff that gets auto generated it's imposible for me to say when and where this started happening.

Solutions stated above are somewhat obscure

```
buildConfigField "boolean", "IS_NEW_ARCHITECTURE_ENABLED", isNewArchitectureEnabled().toString()
```

What is this? Where would you place it? Is there a code snippet to point you exactly WHERE AND HOW?

Why is this issue closed? I haven't found a clear solution yet

**Comment by cortinico** [comment] 2022-06-15 22:27
> Solutions stated above are somewhat obscure

Your `build.gradle` files should reflect the same files we have in our `/template` folder. If they don't (i.e. if you just "bump" the `react-native` version in your package.json), things might break.

> ```
> buildConfigField "boolean", "IS_NEW_ARCHITECTURE_ENABLED", isNewArchitectureEnabled().toString()
> ```
> What is this? Where would you place it? Is there a code snippet to point you exactly WHERE AND HOW?

This is a buildConfigField from Android. You can read more about it here:
https://developer.android.com/studio/build/gradle-tips#share-custom-fields-and-resource-values-with-your-app-code

It's needed to be placed inside your `android/app/build.gradle` file like here:
https://github.com/facebook/react-native/blob/main/template/android/app/build.gradle#L142

This is necessary if you enable the New Architecture as it will tell the runtime if you enabled or not the `newArchEnabled` Gradle Property.

> Why is this issue closed? I haven't found a clear solution yet, neither @swrobel seems yo have gotten a response back...

This issue is closed because, as I previously said, the upgrade process was not followed properly. We have the Upgrade Helper tool that explains steps by steps how to update your files and setup. If some of those steps are missed (i.e. you forget to edit a build.gradle file) things will not work properly.

I hope this clarifies @piscespieces

**Comment by marlonschlosshauer** [comment] 2022-07-19 14:45
I had a similar issue, but unrelated to upgrading. Nonetheless I had a similar fix. Instead of ``import com.facebook.react.BuildConfig;`` I had to use ``import com.projectname.BuildConfig;``, where `projectname` is the name of my project. Hope this helps someone out there.

**Comment by huanguolin** [comment] 2022-11-08 09:16
`import <manifest package name>.BuildConfig;`
see [stackoverflow](https://stackoverflow.com/a/32319395/6198916)

**Comment by beisert1** [comment] 2023-02-17 20:43
Thank you @hadnet our issue was the namespace should not be the same as applicationId. namespace needs to be same as the value used at top of MainActivity.java, MainApplication.java, and ReactNativeFlipper.java for the package.

**Comment by chemiadel** [comment] 2023-02-26 03:44
important thing, if you have changed the *project name* be sure to delete `build` folders on both `android/app/build/`and `android/build`, run ``gradlew clean`` then start your project again

**Comment by Mukhammadjon-Jalolov** [comment] 2023-02-28 11:44
Hi everyone. 
- I created a completely new architecture app using: npx react-native@latest init FabricApp
- Then I enabled: `newArchEnabled=true` in gradle.properties
- I followed the steps exactly as written in the documentation to use a Fabric Component
But when I run yarn android command I'm getting cannot find symbol error. I cannot figure out what's getting wrong in this case. Thank you in advance

`Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
C:\Users\User\Documents\FabricApp\node_modules\rtn-centered-text\android\src\main\java\com\rtncenteredtext\CenteredTextManager.java:16: error: cannot find symbol
public class CenteredTextManager extends SimpleViewManager<RTNCenteredText> implements RTNCenteredTextManagerInterface<RTNCenteredText> {
                                                           ^
  symbol: class RTNCenteredText
C:\Users\User\Documents\FabricApp\node_modules\rtn-centered-text\android\src\main\java\com\rtncenteredtext\CenteredTextManager.java:16: error: cannot find symbol
public class CenteredTextManager extends SimpleViewManager<RTNCenteredText> implements RTNCenteredTextManagerInterface<RTNCenteredText> {
                                                                                                                       ^  symbol: class RTNCenteredText
C:\Users\User\Documents\FabricApp\node_modules\rtn-centered-text\android\src\main\java\com\rtncenteredtext\CenteredTextManager.java:18: error: cannot find symbol
    private final ViewManagerDelegate<RTNCenteredText> mDelegate;`

**Comment by ShadyXV** [comment] 2023-03-14 12:31
> Thank you @hadnet our issue was the namespace should not be the same as applicationId. namespace needs to be same as the value used at top of MainActivity.java, MainApplication.java, and ReactNativeFlipper.java for the package.
> 
> so importing BuildConfig in MainApplication.java is not needed

Seems like having the same value for namespace and applicationId was causing the issue in my project too. I tried so many things but nothing else worked for me.

**Comment by KaivG** [comment] 2023-04-01 20:02
> Thank you @hadnet our issue was the namespace should not be the same as applicationId. namespace needs to be same as the value used at top of MainActivity.java, MainApplication.java, and ReactNativeFlipper.java for the package.
> 
> so importing BuildConfig in MainApplication.java is not needed

I started an expo project, ejected and the ReactNativeFlipper.java had the namespace specified as package, but MainActivity.java and MainApplication.java had the applicationId specified as package.

**Comment by hkvongit** [comment] 2023-05-20 18:11
> I had a similar issue, but unrelated to upgrading. Nonetheless I had a similar fix. Instead of `import com.facebook.react.BuildConfig;` I had to use `import com.projectname.BuildConfig;`, where `projectname` is the name of my project. Hope this helps someone out there.

This worked for me. My sleep got saved.

**Comment by aj019** [comment] 2023-06-25 15:46
Check the namespace value in app/build.gradle . For me fixing the namespace to the package name of the app fixed the issue. Hope it helps others.

**Comment by akshitrcrm** [comment] 2023-07-11 10:46
> I updated RN from 0.70.4 to 0.71.2 and I'm facing this issue
> 
> ```
> BUILD FAILED in 9s
> 
> error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
> Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
> /Users/user/ReactNativeProj/testProj/android/app/src/main/java/com/testproj/MainApplication.java:39: error: cannot find symbol
>           return BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
>                             ^
>   symbol:   variable IS_NEW_ARCHITECTURE_ENABLED
>   location: class BuildConfig
> /Users/user/ReactNativeProj/testProj/android/app/src/main/java/com/testproj/MainApplication.java:44: error: cannot find symbol
>           return BuildConfig.IS_HERMES_ENABLED;
>                             ^
>   symbol:   variable IS_HERMES_ENABLED
>   location: class BuildConfig
> /Users/user/ReactNativeProj/testProj/android/app/src/main/java/com/testproj/MainApplication.java:57: error: cannot find symbol
>     if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
>                    ^
>   symbol:   variable IS_NEW_ARCHITECTURE_ENABLED
>   location: class BuildConfig
> /Users/user/ReactNativeProj/testProj/android/app/src/main/java/com/testproj/MainApplication.java:57: error: illegal parenthesized expression
>     if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
>        ^
> 4 errors
> ```
> 
> NOTE: Ok, got it. The error was caused because in android/app/build.gradle the applicationId got the name wrong, so yeah, pay attention to the name so that it's the same as the original.:
> 
> ```
> android {
>     ndkVersion rootProject.ext.ndkVersion
> 
>     compileSdkVersion rootProject.ext.compileSdkVersion
> 
>     namespace "com.testproj" // pay attention to the name 
>     defaultConfig {
>         applicationId "com.testproj" // same here
>         minSdkVersion rootProject.ext.minSdkVersion
>         targetSdkVersion rootProject.ext.targetSdkVersion
>         versionCode 1
>         versionName "1.0"
>     }
> ...
> ```

Excellent! But in my case the applicationId is dynamic, it is different for debug and release builds so how do I give the namespace a dynamic value rather than a static value?

**Comment by tholmgren** [comment] 2023-07-12 00:11
@akshitrcrm, that was my issue too....

Here's a great video with the solution
https://www.youtube.com/watch?v=TSfE-4CVgDU

Check to make sure your namespace and packages names are correct.

**Comment by RhamHarts** [comment] 2023-07-22 02:03
I have a problem that is almost similar to this. I made an android project from react native and expo. when I try to build the application the error appears like this

```

> Task :app:compileDebugJavaWithJavac
D:\Projek Data posyandu\New folder\amonisasi\android\app\src\main\java\com\hamirz\amonisasi\MainActivity.java:3: error: cannot find symbol
import com.hamirz.amonisasi.BuildConfig;
                           ^
  symbol:   class BuildConfig
  location: package com.hamirz.amonisasi
D:\Projek Data posyandu\New folder\amonisasi\android\app\src\main\java\com\hamirz\amonisasi\MainApplication.java:3: error: cannot find symbol
import com.hamirz.amonisasi.BuildConfig;
                           ^
  symbol:   class BuildConfig
  location: package com.hamirz.amonisasi
D:\Projek Data posyandu\New folder\amonisasi\android\app\src\main\java\com\hamirz\amonisasi\MainActivity.java:40: error: cannot find symbol
    return new ReactActivityDelegateWrapper(this, BuildConfig.IS_NEW_ARCHITECTURE_ENABLED, new DefaultReactActivityDelegate(                                                  ^
  symbol:   variable BuildConfig
  location: class MainActivity
D:\Projek Data posyandu\New folder\amonisasi\android\app\src\main\java\com\hamirz\amonisasi\MainApplication.java:28: error: 
cannot find symbol
        return BuildConfig.DEBUG;
               ^
  symbol: variable BuildConfig
D:\Projek Data posyandu\New folder\amonisasi\android\app\src\main\java\com\hamirz\amonisasi\MainApplication.java:47: error: 
cannot find symbol
        return BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
               ^
  symbol: variable BuildConfig
D:\Projek Data posyandu\New folder\amonisasi\android\app\src\main\java\com\hamirz\amonisasi\MainApplication.java:52: error: 
cannot find symbol
        return BuildConfig.IS_HERMES_ENABLED;
               ^
  symbol: variable BuildConfig
D:\Projek Data posyandu\New folder\amonisasi\android\app\src\main\java\com\hamirz\amonisasi\MainApplication.java:65: error: 
cannot find symbol
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
        ^
  symbol:   variable BuildConfig
  location: class MainApplication
D:\Projek Data posyandu\New folder\amonisasi\android\app\src\main\java\com\hamirz\amonisasi\MainApplication.java:65: error: 
illegal parenthesized expression
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
       ^
8 errors

> Task :app:compileDebugJavaWithJavac FAILED
w: Detected multiple Kotlin daemon sessions at build\kotlin\sessions

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org
```

what i already tried :
1.)i already tried to change the gradle version from 7.5.1 which is default from folder to 8.2.1 newest version.

2.)try to compatible the java version with kotlin version.

and the same error still appear like this.

**Comment by joshAntoniuk** [comment] 2023-08-11 21:57
Still have this issue. My namespaces, packages, and imports are all correct and matching. npx expo run:android works, but building or running the release version crashes with the ReactNativeFlipper cannot find symbol error. Ive been stuck on this for the past week and still can't figure it out...

**Comment by joshAntoniuk** [comment] 2023-08-14 15:26
I have noticed that building the project in the 'debug' variant creates a BuildConfig.java which builds and runs smoothly - but when building with the 'release' variant the BuildConfig.java is not created - which creates the error. Any ideas on this? Been stuck on it for a couple weeks...

**Comment by cirilojesus** [comment] 2023-10-30 21:46
> I updated RN from 0.70.4 to 0.71.2 and I'm facing this issue
> 
> ```
> BUILD FAILED in 9s
> 
> error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
> Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
> /Users/user/ReactNativeProj/testProj/android/app/src/main/java/com/testproj/MainApplication.java:39: error: cannot find symbol
>           return BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
>                             ^
>   symbol:   variable IS_NEW_ARCHITECTURE_ENABLED
>   location: class BuildConfig
> /Users/user/ReactNativeProj/testProj/android/app/src/main/java/com/testproj/MainApplication.java:44: error: cannot find symbol
>           return BuildConfig.IS_HERMES_ENABLED;
>                             ^
>   symbol:   variable IS_HERMES_ENABLED
>   location: class BuildConfig
> /Users/user/ReactNativeProj/testProj/android/app/src/main/java/com/testproj/MainApplication.java:57: error: cannot find symbol
>     if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
>                    ^
>   symbol:   variable IS_NEW_ARCHITECTURE_ENABLED
>   location: class BuildConfig
> /Users/user/ReactNativeProj/testProj/android/app/src/main/java/com/testproj/MainApplication.java:57: error: illegal parenthesized expression
>     if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
>        ^
> 4 errors
> ```
> 
> NOTE: Ok, got it. The error was caused because in android/app/build.gradle the applicationId got the name wrong, so yeah, pay attention to the name so that it's the same as the original.:
> 
> ```
> android {
>     ndkVersion rootProject.ext.ndkVersion
> 
>     compileSdkVersion rootProject.ext.compileSdkVersion
> 
>     namespace "com.testproj" // pay attention to the name 
>     defaultConfig {
>         applicationId "com.testproj" // same here
>         minSdkVersion rootProject.ext.minSdkVersion
>         targetSdkVersion rootProject.ext.targetSdkVersion
>         versionCode 1
>         versionName "1.0"
>     }
> ...
> ```

Yeah this is the solution, thank you

**Comment by jede87** [comment] 2023-10-31 07:39
@joshAntoniuk I encountered the same issue as you. To fix this issue I've added **buildConfigField** in the defaultConfig found in "android\app\build.gradle" like this:
```
defaultConfig {
        applicationId "com.my.app"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "0.0.1"
        buildConfigField "String", "APPLICATION_ID", "\"$applicationId\"" 
        buildConfigField "boolean", "IS_NEW_ARCHITECTURE_ENABLED", "true"
        buildConfigField "boolean", "IS_HERMES_ENABLED", "true"
        buildConfigField "boolean", "DEBUG", "true"
    }
```
Then I've added an import where the BuildConfig fields are used. In my case I've to add the import to MainApplication.java and AppProvider.java like this:
```
import com.my.app.BuildConfig;
```

Hope this will help someone getting stuck. :)

**Comment by jeetvani** [comment] 2023-11-06 05:27
Solution Found - : https://stackoverflow.com/a/77428914/16116610

**Comment by b8ne** [comment] 2023-11-09 07:01
I just came across this after updating from 0.69 to 0.72.  Couldn't solve it so installed a fresh RN app and saw that there was no `import com.facebook.react.BuildConfig`. I literally just removed the import and it built fine.
