### ISSUE TITLE
BlockStatement expected node issue 

### ISSUE THREAD

**Issue by arn-ob** [facebook/react-native#31962] opened 2021-08-05 05:14 UTC
## Description
When I install the app it's giving me this message

node_modules/react-native/Libraries/Components/ScrollView/ScrollViewContext.js: Property body[6] of BlockStatement expected node to be of a type ["Statement"] but instead got "AssignmentExpression"

## React Native version:
System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 154.93 MB / 7.03 GB
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.6.0 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 7.19.1 - /usr/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
  npmGlobalPackages:
    *react-native*: Not Found

## Expected Results
It should be run the mobile application

**Comment by brentvatne** [comment] 2021-08-05 05:32
this is a known issue caused by a bug in a newly released version of babel. it will impact all new react-native and expo apps. you can resolve it with yarn resolutions in a new project:

```diff
--- a/package.json
+++ b/package.json
@@ -25,5 +25,8 @@
   },
   "jest": {
     "preset": "react-native"
+  },
+  "resolutions": {
+    "@babel/plugin-transform-react-display-name": "7.14.5"
   }
 }
```

see some discussion here:
- https://twitter.com/notbrent/status/1423152953876176897
- https://twitter.com/notbrent/status/1423153268423790594

**Comment by zwang62** [comment] 2021-08-05 05:59
@brentvatne It is still not work.How can I make this “resolutions” work

**Comment by brentvatne** [comment] 2021-08-05 06:04
> @brentvatne It is still not work.How can I make this “resolutions” work

use yarn

**Comment by zwang62** [comment] 2021-08-05 06:08
> > @brentvatne It is still not work.How can I make this “resolutions” work
> 
> use yarn

You mean I can't use NPM? I build my project in the App Center, using NPM by default

**Comment by brentvatne** [comment] 2021-08-05 06:10
> > > @brentvatne It is still not work.How can I make this “resolutions” work
> > 
> > use yarn
> 
> You mean I can't use NPM? I build my project in the App Center, using NPM by default

I'm just sharing a temporary workaround and npm does not support resolutions and thus does not support this workaround

**Comment by zwang62** [comment] 2021-08-05 06:11
> > > > @brentvatne It is still not work.How can I make this “resolutions” work
> > > 
> > > 
> > > use yarn
> > 
> > 
> > You mean I can't use NPM? I build my project in the App Center, using NPM by default
> 
> I'm just sharing a temporary workaround and npm does not support resolutions and thus does not support this workaround

Thank you anyway. I will solve my problem based on your solution

**Comment by zq0904** [comment] 2021-08-05 06:40
Thank you for your effort. This problem has taken me the whole morning

**Comment by kelset** [comment] 2021-08-05 08:51
Duplicate of https://github.com/facebook/react-native/issues/31960

**Closed by kelset** 2021-08-05 08:51 UTC
Labels: Needs: Triage :mag:
