### ISSUE TITLE
[0.19+][Released APK] Failed to require images from custom path

### ISSUE THREAD

**Issue by changminc** [facebook/react-native#5853] opened 2016-02-10 09:32 UTC
This error occurs only in a **released apk** file with RN 0.19+ on Android. 
It did work well with RN 0.18 and also did with RN 0.19+ in Android Emulator(genymotion)
I think it is derived from the recent breaking change ( https://github.com/facebook/react-native/commit/e730a9fdd08e63eabf75963ed9cdc17564cf0bfb).

[Problem]
In a released apk With 0.19+ version, the test app went down at starting.
The test app has the structure like below. 

> /index.android.js
> /component/A.js
> /img.png

I confirmed that index.android.js loads an image with `<Image source={require('./img.png')} />` well. 
However, A.js doesn't seem to load an image, When using by `<Image source={require('../img.png')} />`.

**Comment by geof90** [comment] 2016-02-15 11:12
I failed to reproduce this error with a similar structure.

**Comment by christopherdro** [comment] 2016-04-10 18:22
@changminc Is this still an issue?

**Comment by satya164** [comment] 2016-04-10 21:37
I've never faced this issue. Closing this since this issue for now. Let's reopen if you're able to reproduce the issue.

**Closed by satya164** 2016-04-10 21:37 UTC
