### ISSUE TITLE
Native Contacts on iOS generating errors

### ISSUE THREAD

**Issue by lutakyn** [facebook/react-native#28017] opened 2020-02-11 11:27 UTC
Description:

    I am trying to access contacts on native iOS device because react-native-contacts didn't work well as expected. I managed to access contacts on native iOS devices using NativeModules. However trying to send a callback when a contact is picked is giving errors **Thread 1: EXC_BAD_ACCESS (code=1, address=0x10)**. I need help to make one of the functions a callback when contact is selected so that I can get contact in react native. 

React Native version:

   System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
    Memory: 215.89 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
   
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
     Atom, android-24 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom

    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.12.0 => 16.12.0 
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-git-upgrade: 0.2.7

## Steps To Reproduce
1.  Created ContactPicker.m  objective-C file
2. Called NativeModule.callbackmethod in react native

## Expected Results

    Contact selected should be seen in react native console.log

## Snack, code example, screenshot, or link to a repository:

     `#import <UIKit/UIKit.h>
      #import <Foundation/Foundation.h>
      #import "React/RCTBridgeModule.h"
     @import Contacts;
       @import ContactsUI;

      @interface ContactPicker : UIViewController
      @end

    //@end

      @interface ContactPicker () <CNContactPickerDelegate, RCTBridgeModule>
      @property(nonatomic,retain) NSString *contact;
      @property (copy) RCTResponseSenderBlock callbackstored;
      @end
     @implementation ContactPicker

     @synthesize contact;
     @synthesize callbackstored;

      RCT_EXPORT_MODULE();
     RCT_EXTERN_METHOD(getContacts: (RCTResponseSenderBlock)callback);
     //RCT_EXTERN_METHOD(getContactDetails: (RCTResponseSenderBlock)callback)
       RCT_EXTERN_METHOD(getContactDetails: (NSString)
      - (void)viewDidLoad {
      [super viewDidLoad];
      // Do any additional setup after loading the view, typically from a nib
       }
       - (void)getContacts: (RCTResponseSenderBlock)callback {
     CNContactPickerViewController *contactPicker = [CNContactPickerViewController new];
       self.callbackstored = callbackstored;
 
      contactPicker.delegate = self;
     presentViewController:contactPicker animated:YES completion:nil];
     [[[[[UIApplication sharedApplication] delegate] window] rootViewController] 
     presentViewController: contactPicker animated:YES completion:nil]; 
      }

       - (void) contactPicker:(CNContactPickerViewController *)picker
        didSelectContact:(CNContact *)contact {
       [self getContactDetails:contact];
  
      }

       -(NSString *)getContactDetails:(CNContact *)contactObject{

        NSString * phone = @"";
  
        for(CNLabeledValue * phonelabel in contactObject.phoneNumbers) {
       CNPhoneNumber * phoneNo = phonelabel.value;
       phone = [phoneNo stringValue];
       if (phone) {
      self.contact = phone;
      }}
     self.callbackstored(@[[NSNull null], phone]);
     NSLog(@"PHONE NO :: %@",self.contact);
    return self.contact;
    }
     @end`
The error i'm getting in XCode is `Thread 1: EXC_BAD_ACCESS (code=1, address=0x10)`

     `Main Thread Checker: UI API called on a background thread: -[UIWindow rootViewController]
     PID: 12998, TID: 446725, Thread name: (none), Queue name: 
     com.facebook.react.ContactPickerQueue, QoS: 0
     Backtrace:
     4   AppTracker                       0x0000000106673071 -[ContactPicker getContacts:] + 241
     5   CoreFoundation                      0x000000010fabc4cc __invoking___ + 140
    6   CoreFoundation                      0x000000010fab9a45 -[NSInvocation invoke] + 325
    7   CoreFoundation                      0x000000010fab9e96 -[NSInvocation invokeWithTarget:] + 54
    8   AppTracker                       0x00000001069dbb6a -[RCTModuleMethod 
     invokeWithBridge:module:arguments:] + 2810
    9   AppTracker                       0x00000001069dfe16 
    _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 
     790
     10  AppTracker                       0x00000001069df923 _ 
    ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 131
    11  AppTracker                       0x00000001069df899 
     ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 25
    12  libdispatch.dylib                   0x0000000111611d7f _dispatch_call_block_and_release + 12
     13  libdispatch.dylib                   0x0000000111612db5 _dispatch_client_callout + 8
    14  libdispatch.dylib                   0x000000011161a225 _dispatch_lane_serial_drain + 778
    15  libdispatch.dylib                   0x000000011161ae9c _dispatch_lane_invoke + 425
    16  libdispatch.dylib                   0x0000000111624ea3 _dispatch_workloop_worker_thread + 733
    17  libsystem_pthread.dylib             0x00000001119a1611 _pthread_wqthread + 421
      18  libsystem_pthread.dylib             0x00000001119a13fd start_wqthread + 13
      2020-02-11 11:03:12.810923+0000 AppTracker[12998:446725] [reports] Main Thread Checker: 
      UI API called on a background thread: -[UIWindow rootViewController]
      PID: 12998, TID: 446725, Thread name: (none), Queue name: 
      com.facebook.react.ContactPickerQueue, QoS: 0
      Backtrace:
      4   AppTracker                       0x0000000106673071 -[ContactPicker getContacts:] + 241
      5   CoreFoundation                      0x000000010fabc4cc __invoking___ + 140
     6   CoreFoundation                      0x000000010fab9a45 -[NSInvocation invoke] + 325
     7   CoreFoundation                      0x000000010fab9e96 -[NSInvocation invokeWithTarget:] + 54
      8   AppTracker                       0x00000001069dbb6a -[RCTModuleMethod 
       invokeWithBridge:module:arguments:] + 2810
       9   AppTracker                       0x00000001069dfe16 
     _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 
      790
       10  AppTracker                       0x00000001069df923 
      _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 131
       11  AppTracker                       0x00000001069df899 
       ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 25
        12  libdispatch.dylib                   0x0000000111611d7f _dispatch_call_block_and_release + 12
        13  libdispatch.dylib                   0x0000000111612db5 _dispatch_client_callout + 8
       14  libdispatch.dylib                   0x000000011161a225 _dispatch_lane_serial_drain + 778
       15  libdispatch.dylib                   0x000000011161ae9c _dispatch_lane_invoke + 425
        16  libdispatch.dylib                   0x0000000111624ea3 _dispatch_workloop_worker_thread + 
        733
       17  libsystem_pthread.dylib             0x00000001119a1611 _pthread_wqthread + 421
        18  libsystem_pthread.dylib             0x00000001119a13fd start_wqthread + 13
          2020-02-11 11:03:12.914246+0000 AppTracker[12998:446725] [Assert] Cannot be called 
       with asCopy = NO on non-main thread.
       2020-02-11 11:03:13.652149+0000 AppTracker[12998:446680] [MC] System group container      
     2020-02-11 11:03:13.652636+0000 AppTracker[12998:446680] [MC] Reading from private 
     effective user settings.
     (lldb) `

**Comment by lutakyn** [comment] 2020-02-12 09:20
I'm doing a follow up on this good people

**Comment by lutakyn** [comment] 2020-02-12 13:47
Yes a duplicate but have you tried to help to get a solution?

**Comment by hramos** [comment] 2020-02-13 01:36
Going to close as duplicate of #28033, since that one has more information.

**Closed by hramos** 2020-02-13 01:36 UTC
Labels: Needs: Triage :mag:
