### ISSUE TITLE
[android] Accidentally quite 意外退出

### ISSUE THREAD

**Issue by ibeeger** [facebook/react-native#13960] opened 2017-05-14 01:41 UTC
android 从侧面向内触摸 闪退 不论那个 场景 都会闪退 每次必现，

![output](https://cloud.githubusercontent.com/assets/1124832/26030564/6efe6bcc-3889-11e7-9be6-aad3cab776d2.gif)

<pre>
"dependencies": {
                "react": "16.0.0-alpha.6",
                "react-native": "0.43.4"
        },
        "devDependencies": {
                "babel-jest": "19.0.0",
                "babel-preset-react-native": "1.9.1",
                "jest": "19.0.2",
                "react-test-renderer": "16.0.0-alpha.6"
        },
</pre>

**Comment by nihgwu** [comment] 2017-05-14 03:53
Huawei?

**Comment by Kureev** [comment] 2017-05-14 18:43
It isn't really possible to tell you what goes wrong w/o knowing what happens in your application. I believe you can try to debug your application using Google Chrome / Perf Monitor. If that won't help, try to check out some logs / systrace. 

Anyway, w/o this data we can't do anything.

**Comment by lostaloneesk** [comment] 2017-05-15 02:34
@ibeeger 0.44 has fixed it

**Comment by ibeeger** [comment] 2017-05-15 06:18
可能是这里的原因
<pre>
render() {
    return (
         <Navigator
          initialRoute={INITIAL_ROUTE}
          configureScene={this.configureScene}
          renderScene={this.renderScene.bind(this)}
        />
    );
  }
</pre>

**Comment by Kureev** [comment] 2017-05-15 07:56
@ibeeger please, try to upgrade your react-native version according to @lostaloneesk's answer

**Comment by ibeeger** [comment] 2017-05-15 08:52
@Kureev  ok  我试试

**Comment by hramos** [comment] 2017-05-15 18:55
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-05-15 18:55 UTC

**Comment by America-first-melon** [comment] 2017-05-24 09:12
@ibeeger  啥原因？版本的问题还是navigator的原因?

**Comment by dongodngtang** [comment] 2017-06-20 03:47
我页遇到这个问题了，怎么解决

**Comment by America-first-melon** [comment] 2017-06-20 04:15
@dongodngtang 升级到44 就解决了。

**Comment by dongodngtang** [comment] 2017-06-20 09:05
44都不存在Navigator了，你有什么替代的

**Comment by dongodngtang** [comment] 2017-06-20 09:06
@America-first-melon 44都不存在Navigator了，你有什么替代的
