### ISSUE TITLE
Memory Leak in 0.16

### ISSUE THREAD

**Issue by sghiassy** [facebook/react-native#4730] opened 2015-12-11 13:48 UTC
Looks like the base React-Native app has a memory leak

Running `react-native init AwesomeProject` and then running the app produces the following memory graph.

![screen shot 2015-12-11 at 5 47 49 am](https://cloud.githubusercontent.com/assets/792606/11745139/bb5ec362-9fca-11e5-89aa-84532fd2a9d2.png)

**Comment by skevy** [comment] 2015-12-11 17:18
@sghiassy could you try running it in production mode and seeing if the memory leak still exists? `react-native bundle --dev=false` and uncomment the appropriate line in `AppDelegate.m`?

There are several performance concerns that are ignored in dev mode, in order to allow for a good developer experience.

**Comment by sghiassy** [comment] 2015-12-11 20:26
I compiled the JS bundle using command 
```
react-native bundle  --verbose='true' --reset-cache  --entry-file='index.ios.js' --platform='ios'  --bundle-output='build/main.jsbundle' --dev='false' 
```

and referenced the bundle in the app delegate. 

Running the application again produces the same memory problem. It almost seems like the memory growth in production mode seems worse

![screen shot 2015-12-11 at 12 25 39 pm](https://cloud.githubusercontent.com/assets/792606/11754771/59227058-a002-11e5-9ac7-433b512ded37.png)


![screen shot 2015-12-11 at 12 26 26 pm](https://cloud.githubusercontent.com/assets/792606/11754782/6cd26f7c-a002-11e5-822e-299830b8b07b.png)

**Comment by sghiassy** [comment] 2015-12-11 20:28
The project is using `0.16` but I believe I've seen the same problem on `0.15` as well

**Comment by ide** [comment] 2015-12-11 20:54
Also be sure to test an iOS release binary instead of debug.

**Comment by skevy** [comment] 2015-12-11 21:07
@sghiassy as you can see in the log at the bottom of the screen, you're not running in non dev mode. It still says performance optimizations are off.

**Comment by imton** [comment] 2015-12-12 01:26
Thank you guys for the feedback. A little bit busy, will keep iterating slowly, but I promise I will take care of this :)

Some updates to the home. Still alpha. 

I think we should put killer example there in the hero, for iOS and Android and let the switch. Would be nice to should the result too.

![screen shot 2015-12-11 at 10 25 28 pm](https://cloud.githubusercontent.com/assets/637225/11759280/22fe2da6-a056-11e5-93fa-f63539a2220b.png)

**Comment by aroth** [comment] 2015-12-12 01:44
@imton, I think you meant #4720. 

Regarding the memory leak:

*dev = true*
* release: leak
* debug: leak

*dev = false*
* release: no leak
* debug: no leak

I noticed this on a 0.14 to 0.16 upgrade last week. This evening I took a closer look with a fresh 0.16 project to confirm. Any ideas higher up? I'll see if I can profile further.

**Comment by skevy** [comment] 2015-12-12 01:50
If I'm not mistaken, I don't think we really care too much (at least right now) about any potential leaks on dev...that's kind of expected, given the fact that absolutely no performance optimizations are put into dev mode (on purpose, to allow for easy debugging).

So if there's no leak in production mode, I think we're good here.

Feel free to let me know if you feel differently.

**Comment by jadsonlourenco** [comment] 2015-12-12 02:01
For me on 0.16:

debug = leak;
release = no leak;

**Comment by imton** [comment] 2015-12-12 02:14
I forked master, fixed a couple of things (package version) an leaks are  gone on dev too

**Comment by aroth** [comment] 2015-12-12 02:21
@imton -- What did you change? I'd like to take a look.

![](http://i.imgur.com/fY2HM1n.png)

**Comment by imton** [comment] 2015-12-12 02:25
@aroth use master, not .16

**Comment by aroth** [comment] 2015-12-12 03:15
0.17.0-rc is still leaking, although at a much slower rate than 0.16. it's certainly in a better spot. as @skevy states, this may not be so critical at the moment. I tested 0.12 and the chart was very similar. 0.16 was the outlier. 

![screen shot 2015-12-11 at 10 10 14 pm](https://cloud.githubusercontent.com/assets/542/11759900/0ae2b5d6-a054-11e5-95c2-5a7afc66b2f0.png)

**Comment by skevy** [comment] 2015-12-12 03:30
@all - I guess what I'm trying to get at is an actionable issue here.

Do you, as community members, consider it a blocking (or even major) issue for the dev version of your React Native apps (that run in the simulator and on computers that probably have 16GB of RAM) to be leaking memory? If so, and even if I may disagree, let's start investigating _what_ may be causing the memory leak.

If this is not an issue at the moment, and we've determined that the example app is not leaking memory in production mode (and I think we have determined that here), let's close this issue.

**Comment by aroth** [comment] 2015-12-12 03:40
+1 to close.

**Comment by imton** [comment] 2015-12-12 03:47
Well my app on .16 was getting to 3Gb of ram in 1 minute on simulator, so sure it is important to fix. On the other hand, I don't know If I am up to the challenge :s Maybe master is leaking too, I can confirm is way better, but can't for sure say if in my case it was solved 100% or not.

**Comment by skevy** [comment] 2015-12-12 03:53
@imton I won't exclude the possibility that there was some kind of memory leak regression on .16 - perhaps theres something to be said for having some type of suite of acceptance tests for perf before release (though, that's a huge amount of work).

If the leak is small enough on master to not be a detriment to the development process, then I think that's satisfactory at the moment.

**Comment by rclai** [comment] 2015-12-12 04:49
The leak rate is way too high to justify leaving it as is. I would appreciate an appropriate fix.

**Comment by ide** [comment] 2015-12-12 06:01
@rclai are you on 0.17-rc? as mentioned above, the leak rate is not that high.

**Comment by sghiassy** [comment] 2015-12-12 06:23
Looks like I forget to set the scheme to `release`. In doing so, I can confirm that the memory leak disappears.. yay!

I think the fact that it doesn't happen on `release` builds certainly takes the problem down from a red issue to yellow. But I also can't advocate simply living with a memory leak of this size.

**Comment by sghiassy** [comment] 2015-12-12 06:24
Glad to see `0.17-rc` reduces the memory-leak rate

**Comment by jadsonlourenco** [comment] 2015-12-12 13:02
I can confirm, on 0.17.0-rc fix the leak!

**Comment by rclai** [comment] 2015-12-12 17:26
Oh I haven't tried 0.17.0 rc. I trust it's fixed if others so :).

**Comment by ender672** [comment] 2015-12-14 05:34
I believe the leak is due to repeated websocket connection errors on localhost:8097.

This commit seems to be related:
https://github.com/facebook/react-native/commit/9a93a3cba47722a590a8912a5ace1c479eb4178a

If this was fixed in 0.17, could something be backported to 0.16? The leak makes testing dev builds on device very difficult.

**Comment by imton** [comment] 2015-12-14 06:15
I don't think it is fully solved, more over, I can't seem to get debug on
chrome work :(

Best,

Gaston
+59898704249

**Comment by ender672** [comment] 2015-12-14 21:39
Pretty sure that the originally reported issue and the issue I am seeing is fixed in 0.17. This issue seems to be a duplicate of https://github.com/facebook/react-native/issues/3953

**Comment by ajwhite** [comment] 2015-12-15 04:19
I believe I can confirm that `0.17.0-rc` **does not** resolve the leak.

Via https://github.com/facebook/react-native/issues/4761,


### Case 1 - `0.17.0-rc` with a polling network request

- `dev=false`
- `setInterval` with an http request every second

This leaks around 1MB/min

```js
componentDidMount() {
  setInterval(() => {
    fetch('https://google.com').then(() => {
      this.state.value++;
      this.setState(this.state);
    });
  }, 1000);
}
```

![leak](https://cloud.githubusercontent.com/assets/656630/11786120/dc5afce0-a252-11e5-9490-9a352281e665.png)



### Case 2 - `0.17.0-rc` with an interval modifying state every 100ms

This leaks around 250KB/min

- `dev=false`
- `setInterval` invoking a state change every `100ms`

```js
componentDidMount() {
  setInterval(() => {
    this.state.value++;
    this.setState(this.state);
  }, 100);
}
```

![leak](https://cloud.githubusercontent.com/assets/656630/11787328/0db9bc1c-a259-11e5-86fd-a4173541bd9a.png)


----

Test case includes the example component with an interval invoked when the component mounts. If you run the component below over the course of an hour, you will see a low growth in the memory footprint of around 10-15MB. Over the course of half a day this can grow to nearly 100MB.
If you couple this with network requests and more components, this will incur a higher growth rate.
```js
class NetworkTesting extends Component {
  constructor(props) {
    super(props);
    this.state = {value: 1};
  }
  componentDidMount() {
    this.fetchInterval = setInterval(() => {
      this.state.value++;
      this.setState(this.state);
    }, 100);
  }
  componentWillUnmount() {
    clearInterval(this.fetchInterval);
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          {this.state.value}
        </Text>
      </View>
    );
  }
}
```

**Comment by toriumi0118** [comment] 2015-12-17 07:58
Hi. I took couple hours and tried to find the cause. 
it may be related with #4282 and @ender672 mentioned above.

Same as #4282 and @ender672, I have checked the files below.

* https://github.com/facebook/react-native/blob/master/Libraries/Devtools/setupDevtools.js

The cause can be setupDevtools method called endless. But facebook/react-native#4283 is mentioned about how to fix it.

I think I need to wait a devtool that will connect to port 8097 by Websocket.
Or just comment out https://github.com/facebook/react-native/blob/master/Libraries/JavaScriptAppEngine/Initialization/InitializeJavaScriptAppEngine.js#L210 until devtool or new direction decide.

And some of report above about this leak will be happened **debug mode** only.
At the InitializeJavaScriptAppEngine.js#L189-L190

``` js
  if (__DEV__) { // TODO(9123099) Strip `__DEV__ &&`
    if (!window.document && require('Platform').OS === 'ios') {
```

so, this leak might happen **dev mode** and **ios** only.

**Comment by jadsonlourenco** [comment] 2015-12-17 14:47
@toriumi0118 I tried what you said but not work I think, look:
![Screen](http://uploadpie.com/TmnTb)

**Comment by toriumi0118** [comment] 2015-12-17 15:08
@jadsonlourenco thanks your share.

The condition may be different.
My condition is like this.

* Real Device Debug (iPhone 6)
* OSX 10.10.5
* Xcode 7.2
* react-native version 0.16.0 

Result is like this.

*comment out version* (setUpDevTools(); is not working.)
![2015-12-17 23 55 41](https://cloud.githubusercontent.com/assets/2346203/11872892/1dc3a2d4-a51b-11e5-927c-96a6e598e587.png)

*not comment out version* (setUpDevTools(); is working.)
![2015-12-17 23 59 51](https://cloud.githubusercontent.com/assets/2346203/11872941/621dd918-a51b-11e5-8241-c44256385520.png)

Both of them is passed about 2 min after launch in same project.

**Comment by jadsonlourenco** [comment] 2015-12-18 00:06
@toriumi0118 great to know, because I tested with v0.17.0-rc, that has new bugs and not fix this issue too. But the v0.16.0 give me the same result, leak, on real device (iPhone 6+, IOS 9.2, Xcode 7.2, OSX 10.11.2), I will try your advice now with v0.16.0, thank you.

**Comment by kozlowskij** [comment] 2015-12-29 23:35
I had some old "OPTION 1" AppDelegate.m code that looked like this:

```jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios&dev=true"];```

Replacing that with:

```jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?&dev=true"];```

fixed the egregious debug memory issue in 0.16.0 for me.

**Comment by insraq** [comment] 2016-02-16 04:37
@toriumi0118 I can confirm this on the latest 0.19. In debug mode, it's still leaking memory, at about 0.5mb/s. After removing `setUpDevTools();` the leaking stops.
It thinks it's related to #4282. Can we actually have a proper fix? Since devTool is not working anyway, I have simply commented it out.

**Comment by toriumi0118** [comment] 2016-02-16 06:00
@insraq I have not check with v0.19. Although I agree with you that this issue relate with #4282.
This problem bit complex because I have to know about devtool more.

**Comment by hasen6** [comment] 2016-03-05 11:44
Just wondering if this would ever be fixed. Up to 0.21 now and still seeing the memory leak...albeit not as extreme as before. I know its only in debug mode but its debug mode where we're on the lookout for errors. This could be misleading.

**Comment by jeremyong** [comment] 2016-03-08 05:04
@skevy 
> If I'm not mistaken, I don't think we really care too much (at least right now) about any potential leaks on dev...that's kind of expected, given the fact that absolutely no performance optimizations are put into dev mode (on purpose, to allow for easy debugging).

I'm not sure what aspect of a memory leak that causes my app to be unrunnable after a few minutes of use in a simulator makes dev mode easier to debug.

Also how are you supposed to debug an *actual* leak if leaks already exist? The reason debug builds are slow is because unoptimized code maps in a one to one fashion to source code, which makes it easy to step through a debugger. That's it. The presence of leaks and other bugs in debug mode should be just as serious as bugs in any other mode. I think this is a pretty fundamental software engineering discipline.

**Comment by hasen6** [comment] 2016-03-08 05:13
Exactly, Its pretty hard to debug anything when you don't know if the ever expanding memory is anything to do with it. Not only that but it seems the source of the memory leak has already been isolated.

**Comment by skevy** [comment] 2016-03-08 05:26
@jeremyong If the leak is causing your app to be "unrunnable" after a few minutes of use, then yes, of course I consider it a blocking issue.

When I commented previously, that wasn't my understanding of the problem (and I'm sorry if I misunderstood). It seemed as though it was something that happened over long term use, or at least at a slow rate...specifically, a rate that wasn't detrimental to the dev process. There are many things to work on in RN, and I was merely trying to triage, not dismiss completely.

Regarding debugging an actual leak...in typical React/React Native development, you wouldn't debug leaks in dev mode...there are specifically dev helpers (logging, error messages etc) that use resources that wouldn't be used in production. You would debug that leak in production mode...as close to the environment that the app will finally live in as possible.

RE: the cause of the leak -- honestly, I had missed the comment on this issue 21 days ago that alluded to it. Let me review the associated PR's in the morning, and see 1) whether we can take immediate action or 2) if we can do a bit more work to come to a solution. It's not intentional that I (or we) was ignoring this issue...just a consequence of being mentioned and subscribed to many issues on this repo, and it's hard to keep up. Thanks for mentioning me and bringing it up again.

Also, @sebmarkbage has mentioned recently that he and others on the React team want to audit "dev mode" in React, to make sure that it's not doing things that it doesn't need to do and that (possibly) don't cause issues such as memory leaks. I'll let him speak to it here.

**Comment by skevy** [comment] 2016-03-08 05:27
@tadeuzagallo I unassigned you from this until I do a bit more investigation. Will re-assign if I find that it's something that you could help with/fix :)

**Comment by jeremyong** [comment] 2016-03-08 05:51
@skevy Thanks for looking into it :)

**Comment by battman21** [comment] 2016-06-20 10:09
Hi guys
Any update on this issue? We are hitting it pretty badly. Happy to fix our code if required and is us using something badly, but any idea on what path to take would be great / if there is any update at all?

Thanks!

**Comment by hasen6** [comment] 2016-06-20 13:36
Its a 7 month problem now. I find it unlikely it will ever be fixed even though its probably the most major issue.

**Comment by battman21** [comment] 2016-06-20 14:02
I'm baffled... surely this needs addressing??

**Comment by hasen6** [comment] 2016-06-20 14:56
@battman21 I think everyone is baffled. Even the cause was identified three months ago but still is yet to be resolved.

**Comment by insraq** [comment] 2016-06-20 15:52
Hmm... I haven't got any issue with recent React Native releases (0.27) since I have received no memory warning. But I will double check with memory usage graph.

**Comment by tadeuzagallo** [comment] 2016-06-20 16:04
Just ran `react-native init <project>`, got version `0.27.2` and this is what I saw:

![screen shot 2016-06-20 at 16 59 54](https://cloud.githubusercontent.com/assets/764414/16201257/8b2bab26-3708-11e6-94c3-67db4eef1e69.png)

@hasen6 can you confirm you still have this issue with the latest version of React Native?

@battman21 can you confirm this is the same issue you have? Have you checked what's the source of the leak with instruments? I'm happy to help with that if you need, more information would help: what version of RN are you using? Phone or emulator? Debug or Production? which iOS version?

**Comment by hasen6** [comment] 2016-06-21 02:50
Until its listed as fixed in the updates I doubt it will be gone.

**Comment by fab1an** [comment] 2016-09-01 11:32
I still have this with 0.32.

**Comment by lacker** [comment] 2016-11-30 00:22
It seems like this issue has now become a grab bag of different problems so I am going to close it. If people have a single app that reproduces a problem then I encourage them to reopen a new issue here.

**Closed by lacker** 2016-11-30 00:22 UTC
Labels: iOS
