### ISSUE TITLE
Why is this phenomenon in PanResponder?

### ISSUE THREAD

**Issue by MrErHu** [facebook/react-native#15980] opened 2017-09-18 06:47 UTC
English is  poor, so show code: 
```javascript
class Demo extends React.Component{
    constructor(props){
        super(props);
        this.state = {
            bg: 'white',
            bg2: 'white'
        }
    }

    componentWillMount(){

        this.pan1 = PanResponder.create({
            onStartShouldSetPanResponder: () => {
                console.log('outer: ', 'onStartShouldSetPanResponder')
                return true;
            },

            onMoveShouldSetPanResponder: () => {
                console.log('outer: ', 'onMoveShouldSetPanResponder')
                return true;
            },

            onPanResponderGrant: () => {
                console.log('outer: ', 'onResponderGrant')
                this.setState({bg: 'red'})
            },

            onPanResponderRelease: () => {
                console.log('outer: ', 'onPanResponderRelease');
                this.setState({bg: 'white'})
            },


            onPanResponderTerminate: ()=>{
                console.log('outer: ', 'onPanResponderTerminate');
                this.setState({bg: 'white'})
            }
        });


        this.pan2 = PanResponder.create({
            onStartShouldSetPanResponder: () => {
                console.log('inner: ', 'onStartShouldSetPanResponder')
                return true;
            },

            onMoveShouldSetPanResponder: () => {
                console.log('inner: ', 'onMoveShouldSetPanResponder')
                return true;
            },

            onPanResponderGrant: () => {
                console.log('inner: ', 'onResponderGrant')
                this.setState({bg2: 'green'})
            },

            onPanResponderRelease: () => {
                console.log('outer: ', 'onPanResponderRelease');
                this.setState({bg2: 'white'})
            },


            onPanResponderTerminate: ()=>{
                console.log('inner: ', 'onPanResponderTerminate')
                this.setState({bg2: 'white'})
            }
        })

    }

    render() {
        return (
            <View style={styles.container}>
                <View
                    {...this.pan1.panHandlers}
                    style={[styles.rect,{"backgroundColor": this.state.bg}]}
                >
                    <View
                        {...this.pan2.panHandlers}
                        style={[styles.rect2,{"backgroundColor": this.state.bg2}]}
                    >

                    </View>
                </View>
            </View>
        );
    }


}

var styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F5FCFF',
    },
    rect: {
        width: 200,
        height: 200,
        borderWidth: 1,
        borderColor: 'black',
        justifyContent: 'center',
        alignItems: 'center',
    },
    rect2: {
        width: 100,
        height: 100,
        borderWidth: 1,
        borderColor: 'black'
    }
});
```
when I press center box and move into outer, I can find this phenomenon:
![](http://oj232uzqf.bkt.clouddn.com/1.gif)
console show message:
```
inner:  onStartShouldSetPanResponder
inner:  onResponderGrant
outer:  onMoveShouldSetPanResponder
outer:  onResponderGrant
inner:  onPanResponderTerminate
//......
```
the outer box get `panResponder` from inner box。This can be explained。
But I try to press outer box and move into inner box, The phenomenon is:
![](http://oj232uzqf.bkt.clouddn.com/2.gif)
console show message:
```
outer:  onStartShouldSetPanResponder
outer:  onResponderGrant
outer:  onPanResponderRelease
```
Why I can not see the phenomenon that inner box get `panResponder` from outer  #box?

**Comment by hramos** [comment] 2017-09-21 15:08
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue that meets the requirements set forth in the template. Thanks!

**Closed by hramos** 2017-09-21 15:08 UTC
