### ISSUE TITLE
> Task :app:processReleaseMainManifest (Execution optimizations have been disabled for task ':app:processReleaseMainManifest')

### ISSUE THREAD

**Issue by Rehan-05** [facebook/react-native#33205] opened 2022-03-02 09:58 UTC
### Description

F:\Project Fivers\fixlancer\android>gradlew assembleRelease -x bundleReleaseJsAndAssets
Starting a Gradle Daemon, 3 incompatible Daemons could not be reused, use --status for details

> Task :app:processReleaseMainManifest
Execution optimizations have been disabled for task ':app:processReleaseMainManifest' to ensure correctness due to the following reasons:       
  - Gradle detected a problem with the following location: 'F:\Project Fivers\fixlancer\android\app\build\intermediates\navigation_json\release\navigation.json'. Reason: Task ':app:processReleaseMainManifest' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :app:processReleaseManifest
Execution optimizations have been disabled for task ':app:processReleaseManifest' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: 'F:\Project Fivers\fixlancer\android\app\build\intermediates\compatible_screen_manifest\release'. Reason: Task ':app:processReleaseManifest' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: 'F:\Project Fivers\fixlancer\android\app\build\intermediates\merged_manifest\release\AndroidManifest.xml'. Reason: Task ':app:processReleaseManifest' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :app:processReleaseManifestForPackage
Execution optimizations have been disabled for task ':app:processReleaseManifestForPackage' to ensure correctness due to the following reasons: 
  - Gradle detected a problem with the following location: 'F:\Project Fivers\fixlancer\android\app\build\intermediates\merged_manifests\release'. Reason: Task ':app:processReleaseManifestForPackage' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :app:mergeReleaseNativeLibs
Execution optimizations have been disabled for task ':app:mergeReleaseNativeLibs' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: 'F:\Project Fivers\fixlancer\android\app\build\intermediates\merged_jni_libs\release\out'. Reason: Task ':app:mergeReleaseNativeLibs' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit 
dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :app:compressReleaseAssets
Execution optimizations have been disabled for task ':app:compressReleaseAssets' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: 'F:\Project Fivers\fixlancer\android\app\build\intermediates\merged_assets\release\out'. Reason: Task ':app:compressReleaseAssets' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :app:sdkReleaseDependencyData
Execution optimizations have been disabled for task ':app:sdkReleaseDependencyData' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: 'F:\Project Fivers\fixlancer\android\app\build\intermediates\metadata_library_dependencies_report\release\dependencies.pb'. Reason: Task ':app:sdkReleaseDependencyData' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.       

> Task :app:mergeExtDexRelease
Execution optimizations have been disabled for task ':app:mergeExtDexRelease' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: 'F:\Project Fivers\fixlancer\android\app\build\intermediates\duplicate_classes_check\release'. Reason: Task ':app:mergeExtDexRelease' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit 
dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: 'F:\Project Fivers\fixlancer\android\app\build\intermediates\external_file_lib_dex_archives\release'. Reason: Task ':app:mergeExtDexRelease' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :app:mergeReleaseJavaResource
Execution optimizations have been disabled for task ':app:mergeReleaseJavaResource' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: 'F:\Project Fivers\fixlancer\android\app\build\intermediates\java_res\release\out'. Reason: Task ':app:mergeReleaseJavaResource' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :app:stripReleaseDebugSymbols
Execution optimizations have been disabled for task ':app:stripReleaseDebugSymbols' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: 'F:\Project Fivers\fixlancer\android\app\build\intermediates\merged_native_libs\release\out'. Reason: Task ':app:stripReleaseDebugSymbols' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
Unable to strip the following libraries, packaging them as they are: libbetter.so, libc++_shared.so, libfabricjni.so, libfb.so, libfbjni.so, libfolly_futures.so, libfolly_json.so, libglog.so, libglog_init.so, libimagepipeline.so, libjsc.so, libjsi.so, libjsijniprofiler.so, libjsinspector.so, liblogger.so, libmapbufferjni.so, libnative-filters.so, libnative-imagetranscoder.so, libreact_codegen_rncore.so, libreact_debug.so, libreact_nativemodule_core.so, libreact_render_animations.so, libreact_render_attributedstring.so, libreact_render_componentregistry.so, libreact_render_core.so, libreact_render_debug.so, libreact_render_graphics.so, libreact_render_imagemanager.so, libreact_render_leakchecker.so, libreact_render_mapbuffer.so, libreact_render_mounting.so, libreact_render_runtimescheduler.so, libreact_render_scheduler.so, libreact_render_telemetry.so, 
libreact_render_templateprocessor.so, libreact_render_textlayoutmanager.so, libreact_render_uimanager.so, libreact_utils.so, libreactconfig.so, 
libreactnativeblob.so, libreactnativejni.so, libreactnativeutilsjni.so, libreactperfloggerjni.so, librrc_image.so, librrc_modal.so, librrc_progressbar.so, librrc_root.so, librrc_scrollview.so, librrc_slider.so, librrc_switch.so, librrc_text.so, librrc_textinput.so, librrc_unimplementedview.so, librrc_view.so, libturbomodulejsijni.so, libyoga.so.

> Task :app:extractReleaseNativeSymbolTables
Execution optimizations have been disabled for task ':app:extractReleaseNativeSymbolTables' to ensure correctness due to the following reasons: 
  - Gradle detected a problem with the following location: 'F:\Project Fivers\fixlancer\android\app\build\intermediates\merged_native_libs\release\out'. Reason: Task ':app:extractReleaseNativeSymbolTables' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: 'F:\Project Fivers\fixlancer\android\app\build\intermediates\stripped_native_libs\release\out'. Reason: Task ':app:extractReleaseNativeSymbolTables' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
Unable to extract native debug metadata from F:\Project Fivers\fixlancer\android\app\build\intermediates\merged_native_libs\release\out\lib\arm64-v8a\libbetter.so because unable to locate the objcopy executable for the arm64-v8a ABI.
Unable to extract native debug metadata from F:\Project Fivers\fixlancer\android\app\build\intermediates\merged_native_libs\release\out\lib\arm64-v8a\libc++_shared.so because unable to locate the objcopy executable for the arm64-v8a ABI.
Unable to extract native debug metadata from F:\Project Fivers\fixlancer\android\app\build\intermediates\merged_native_libs\release\out\lib\arm64-v8a\libfabricjni.so because unable to locate the objcopy executable for the arm64-v8a ABI.
Unable to extract native debug metadata from F:\Project 
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.       

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 10 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

BUILD SUCCESSFUL in 1m 15s
289 actionable tasks: 12 executed, 277 up-to-date

### Version

0.67

### Output of `npx react-native info`

F:\Project Fivers\fixlancer>npx react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 932.27 MB / 7.78 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.3 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7784292
    Visual Studio: 17.0.31903.59 (Visual Studio Community 2022)
  Languages:
    Java: 11.0.13 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.0 => 0.67.0
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Wanted To Generate the apk with this command gradlew assembleRelease -x bundleReleaseJsAndAssets
then
facing this error and then gave me output crached apk.

**Comment by Ivandeclei** [comment] 2022-03-18 20:58
i have this problem

**Comment by kchijim** [comment] 2022-03-23 08:48
i have this problem, but my apk can use

**Comment by sarons** [comment] 2022-04-23 19:57
A temporary solution I found was to add this config to gradle.properties
org.gradle.jvmargs=-Xmx1536M --add-opens java.base/java.io=ALL-UNNAMED

**Comment by Rehan-05** [comment] 2022-04-24 09:55
@sarons Thanks for sharing. I will try.

**Comment by cortinico** [comment] 2022-05-06 19:01
Closing as a duplicate of #33202.
The root cause is the `:app:copyReleaseBundledJs` task and it's output paths

**Closed by cortinico** 2022-05-06 19:01 UTC
Labels: Needs: Triage :mag:

**Comment by gigby** [comment] 2023-01-23 11:29
I got the same issue when I did release build and forgot to put **release-upload-key.keystore** file
RN: 0.68.2
Command: "./gradlew assembleRelease"
