### ISSUE TITLE
RefreshControl has a bug on iOS platform

### ISSUE THREAD

**Issue by cizhaoyang** [facebook/react-native#8595] opened 2016-07-06 10:12 UTC
When I use 'RefreshControl' of component on iOS platform,there is a black ActivityIndicator on the top right corner

**Comment by tofrookie** [comment] 2016-07-07 08:43
+1

**Comment by kkgelu** [comment] 2016-07-07 13:24
+1 after upgrading to 0.28

**Comment by kkgelu** [comment] 2016-07-07 21:40
This duplicates #7976

**Comment by charpeni** [comment] 2016-07-11 13:25
@facebook-github-bot duplicate #7976

**Comment by facebook-github-bot-0** [comment] 2016-07-11 13:26
@charpeni tells me this issue is a duplicate of #7976. Let's discuss there, closing this one.

**Closed by facebook-github-bot-0** 2016-07-11 13:26 UTC
Labels: Ran Commands
