### ISSUE TITLE
DNS Cache Issue

### ISSUE THREAD

**Issue by basith374** [facebook/react-native#14441] opened 2017-06-10 12:42 UTC
### Description

I have migrated my server to a different host. The IP has changed and now some of the apps in production is not working(not everyone affected). Not working as in network error caused due to the change in IP address probably.  Especially affected those who are using android with version less than 5(lollipop). Is this issue known or is it something else? I am using react-native v0.35.0

My question is somehow related with this [10404](https://github.com/facebook/react-native/issues/10404)

From what i understand, this is related to name resolution, and the app is contacting the old server ip. The old IP must've cached in the phone. Is there a way to fix this other than rollback to the old server ip?

### Reproduction Steps and Sample Code

This problem cannot be reproduced using snack :(

### Solution

I don't know what to do :(

### Additional Information

* React Native version: 0.35.0
* Platform: iOS & Android

**Comment by hramos** [comment] 2017-06-12 20:50
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-12 20:50 UTC

**Comment by 0x0E** [comment] 2017-12-07 08:09
got same issue, how do you fixed it? thx

**Comment by basith374** [comment] 2017-12-07 08:15
i didn't fix it. from what i understand, the issue is somewhere in the OS
or with react-native.

Regards
Basith
