### ISSUE TITLE
react native android get hangs when loading multiple images

### ISSUE THREAD

**Issue by karthickvkumar** [facebook/react-native#5265] opened 2016-01-12 06:34 UTC
I tried to render a list of images in screen. But my app is get hangs while using in emulator as well as mobile

**Comment by Ehesp** [comment] 2016-01-12 08:57
Can you show some code?

**Comment by mkonicek** [comment] 2016-01-14 18:28
Hey and thanks for reporting this!

There's an awesome place to post code and ask question first before filing an issue: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see your question, you can vote on answers and mark question as answered etc. This lets us keep a list of bug reports and feature requests on github and especially [Product Pains](https://productpains.com/product/react-native/?tab=top) (again, with voting which is really nice).

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)

I'll close this and please open an issue with detailed repro steps once you've confirmed there's a bug.

**Closed by mkonicek** 2016-01-14 18:28 UTC
Labels: Android
