### ISSUE TITLE
Pressable delay too long for `pressed` to be true

### ISSUE THREAD

**Issue by mrousavy** [facebook/react-native#29321] opened 2020-07-09 13:50 UTC
## Description

The `<Pressable>` component (and all other Touchable components) have received added delay until the `onPressIn` function fires in `react-native` 0.63. This means any `TouchableOpacity`s will feel sluggish and won't immediately respond to touches. See:

![1 mov](https://user-images.githubusercontent.com/15199031/87047904-61347000-c1fb-11ea-8af5-017336edfe36.gif)

> When immediately clicking, the `pressed` property won't be set to true at all, so no opacity changes/feedback to the user!

![2 mov](https://user-images.githubusercontent.com/15199031/87047899-60034300-c1fb-11ea-806a-f20dcd5205fc.gif)

> After holding (Long press) the `pressed` property is true and the opacity switches.

Note: When I manually set `delayPressIn={0}` the feedback appears instant again, but I'm not going to do that for hundreds of Touchables inside my project. Also, this only works on Touchable components, [`Pressable`](https://reactnative.dev/docs/next/pressable) doesn't even have this feature!

Am I missing something? Is this intended behaviour?

## React Native version:

```
info Fetching system and libraries information...
(node:14869) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 5.47 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 25, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.0, 30.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: 21.2.6472646
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.0 => 0.63.0 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce

1. Use `<TouchableOpacity>` component (or `<Pressable>` and use style function to toggle between opacity depending on `pressed` property)
2. Press it

## Expected Results

The Touchable/Pressable should show feedback right away

## Snack, code example, screenshot, or link to a repository:

![1 mov](https://user-images.githubusercontent.com/15199031/87047904-61347000-c1fb-11ea-8af5-017336edfe36.gif)

> When immediately clicking, the `pressed` property won't be set to true at all, so no opacity changes/feedback to the user!

![2 mov](https://user-images.githubusercontent.com/15199031/87047899-60034300-c1fb-11ea-806a-f20dcd5205fc.gif)

> After holding (Long press) the `pressed` property is true and the opacity switches.

**Comment by TheSavior** [comment] 2020-07-09 18:25
Looks like this commit got missed: https://github.com/facebook/react-native/commit/4aaf62998247bcfd8ebf369d73290096fde08012#diff-ff4d5358a97501a402a3f234318497e4

**Comment by TheSavior** [comment] 2020-07-09 18:27
Also, looks like this is a duplicate of https://github.com/facebook/react-native/issues/29313

**Closed by TheSavior** 2020-07-09 18:27 UTC
Labels: Needs: Triage :mag:
