### ISSUE TITLE
react native app restarted when changing permission through settings

### ISSUE THREAD

**Issue by pandiaraj44** [facebook/react-native#15193] opened 2017-07-25 12:59 UTC
I have a react native app. Which is working fine in both ios & android but if change any permissions(Camera, Storage) through settings option then app get restarted.

For Example, If I am on the home-screen and I had changed the permission then the app will get restarted and takes me to the login screen.

Are there any options to maintain current app state(both ios and android)?

Please suggest me.

**Comment by hramos** [comment] 2017-07-25 17:03
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-07-25 17:03 UTC

**Comment by pandiaraj44** [comment] 2017-07-26 05:54
Hi @hramos ,
Edited the description & created the new issue https://github.com/facebook/react-native/issues/15207
