### ISSUE TITLE
Fix 0.76.4 version for android please

### ISSUE THREAD

**Issue by Dallas62** [facebook/react-native#48173] opened 2024-12-08 10:05 UTC
### Description

Since 0.76.4 no more modules are loaded on Android with new arch.
Require release of https://github.com/facebook/react-native/pull/48156#issue-2723478104

### Steps to reproduce

Create new Android App with 0.76.4 and at least one turbo module active, load will fail.

### React Native Version

0.76.4

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
0.76.4 - Android
```

### Stacktrace or Logs

```text
Sorry to not provide more but looks like not useful.
```

### Reproducer

https://github.com/facebook/react-native

**Comment by cortinico** [comment] 2024-12-09 11:12
Thanks for the heads up. CLosing as the issue is fixed already, we just need to merge the revert

**Closed by cortinico** 2024-12-09 11:12 UTC
Labels: Platform: Android, Needs: Author Feedback, Needs: Repro

**Comment by Dallas62** [comment] 2024-12-09 13:45
Any ETA for the release of this PR ?
More repositories are linking this issue since it's breaking the latest version, probably due to `^0.76.X` in the `package.json`.

**Comment by cortinico** [comment] 2024-12-09 14:25
> Any ETA for the release of this PR ?

It will be out in the immediate future
