### ISSUE TITLE
[Android] Shared ReactInstanceManager in a singleton between multiple activities failing while showing a modal

### ISSUE THREAD

**Issue by yurykorzun** [facebook/react-native#15108] opened 2017-07-19 16:02 UTC
I integrated a React Native app into an existing Android app. When a native app requests a React Native view, I start a new activity with a React Native view in it. I wrapped ReactInstanceManager in a singleton class and initialize it when the Android app loads.

The problem I experience is that ReactInstanceManager cannot be shared between multiple instances of ReactNative views. For example, if I start one React Native activity and show a share sheet using the Share component, the next time I start a new activity and provide it the cached ReactInstanceManager, it will fail while trying to show a Modal. When the React Native tries to call mDialog.show it fails with  android.view.WindowManager$BadTokenException: Unable to add window.
It looks like it tries to attach a dialog to a non-existent activity. It has something to do with the React Themed Context I guess.

It looks like ReactInstanceManager cannot be loaded once and shared safely between multiple instances of React Native views.

If anyone can share insight on how to share ReactInstanceManager properly, I would really appreciate that. Currently I am refreshing the manager every time I close a React Native Activity, but I would like to have a single instance.

1. `react-native -v`: 0.42.3
2. `node -v`: v6.11.0
3. `npm -v`: 5.2.0
4. platform: Android

**Comment by hramos** [comment] 2017-07-19 17:35
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-07-19 17:35 UTC

**Comment by ManishPatiyal** [comment] 2017-07-27 10:10
+1

**Comment by ManishPatiyal** [comment] 2017-07-27 10:13
I also have the same requirement and need to have singleton pattern for ReactInstanceManager as I need to send custom events using RCTDeviceEventEmitter to react. For this I need the ReactInstanceManager which is null at the time I build it on android activities oncreate() method .

**Comment by AnyGong** [comment] 2017-09-01 01:50
+1

**Comment by jkwangbest** [comment] 2018-04-19 08:29
+1  In https://facebook.github.io/react-native/docs/integration-with-existing-apps.html 
It says: 
`A ReactInstanceManager can be shared by multiple activities and/or fragments. You will want to make your own ReactFragment or ReactActivity and have a singleton holder that holds a ReactInstanceManager. When you need the ReactInstanceManager (e.g., to hook up the ReactInstanceManager to the lifecycle of those Activities or Fragments) use the one provided by the singleton.`
But no example
