### ISSUE TITLE
[0.56.0] Unable to resolve module `AccessibilityInfo` when init App on WINDOWS

### ISSUE THREAD

**Issue by QinGuan2004** [facebook/react-native#20689] opened 2018-08-16 14:49 UTC
## Environment
Windows 10
React Native 0.56.0
React 16.4.1
[skip envinfo]

## Description
Unable to resolve module `AccessibilityInfo` when loading app 

## Reproducible Demo
On *WINDOWS*, 
```$ react-native init```
```$ react-native run-android```

Error should appear when app is loading from packager.
Issue has been reported before on React Native v0.4x

**Comment by hramos** [comment] 2018-08-16 20:10
Duplicate of #20353

**Closed by hramos** 2018-08-16 20:10 UTC
Labels: :clipboard:No Environment Info

**Comment by fantasy525** [comment] 2018-08-17 03:03
#20707 I got same issues ,and I have enviroment Infos, @react-native-bot

**Comment by QinGuan2004** [comment] 2018-08-17 03:48
This is duplicate but issue was never solved properly @hramos is there usable solution

**Comment by hramos** [comment] 2018-08-17 16:59
It's still a duplicate - you can subscribe to #20353 for updates.
