### ISSUE TITLE
Cannot run simulator on iOS with expo 

### ISSUE THREAD

**Issue by nguyentvnhat** [facebook/react-native#24858] opened 2019-05-15 01:11 UTC
Hi guys,

I have got expo message after upgrade MacOS:
====
Trying to open the project in iOS simulator...
Simulator is installed but is identified as 'com.apple.CoreSimulator.SimulatorTrampoline'; don't know what that is.
Simulator not installed. Please visit https://developer.apple.com/xcode/download/ to download Xcode and the iOS simulator. If you already have the latest version of Xcode installed, you may have to run the command `sudo xcode-select -s /Applications/Xcode.app`.
==== 
I tried run "sudo xcode-select -s /Applications/Xcode.app" but it doesn't working.

Could you tell me how to solve them, please?

Thank you.

**Comment by zhongwuzw** [comment] 2019-05-15 15:05
@nguyentvnhat Thanks for reporting, we'll close because duplicate of https://github.com/facebook/react-native/issues/23878.

**Closed by zhongwuzw** 2019-05-15 15:05 UTC
Labels: Bug, Platform: iOS, Ran Commands, Resolution: Needs More Information
