### ISSUE TITLE
How to switch from one view to the other?

### ISSUE THREAD

**Issue by ele828** [facebook/react-native#919] opened 2015-04-19 01:31 UTC
Hi, I am wonder how to switch from one view to the other with some animation? Thanks

**Comment by mjw56** [comment] 2015-04-19 02:20
You could use the [Navigator](http://facebook.github.io/react-native/docs/navigator.html#content) for setting up "scenes" of your app and transitioning between them.

Navigator has a ```configureScene``` prop which you can provide to the [initial ```Navigator``` component](https://github.com/facebook/react-native/blob/b360168e8ba791dd48c7fd0cbaff23b66e5eb5a4/Examples/UIExplorer/Navigator/JumpingNavSample.js#L114-L116) to play around with some initial animations.

The available animation properties on ```Navigator.SceneConfigs``` are:
```
FloatFromBottom
FloatFromRight
HorizontalSwipeJump
PushFromRight
```

**Comment by ele828** [comment] 2015-04-19 04:29
Thank you very much @mjw56

**Comment by ele828** [comment] 2015-04-19 05:59
@mjw56  I met another problem, the `Push` method works well, but when I try to use ``this.props.navigator.replace()``, it goes wrong with ``Navigator.SceneConfigs.FloatFromBottom``, and all the other animation doesn't work. 

Cause I want to prevent user to goback to previous Scene. So I have to use `replace` method. thanks a lot :)

**Comment by mjw56** [comment] 2015-04-19 13:11
@ele828 hm, I am not sure about replace as I have not used that yet.

@ericvicenti do you know if animations work with replace? Also, will the example above work with 0.4.0?

**Comment by mjw56** [comment] 2015-04-20 01:51
I can confirm animation doesn't work with replace in 0.4.0. Probably we should close this and open a new issue for this.

**Comment by ericvicenti** [comment] 2015-04-20 19:40
We currently don't support animations on replace. The closest thing we have so far is the ability to put a Navigator inside of a Navigator and do a push on the inside one. Or you could simply do a push and then call `popToRoute` when you want to go back. This has worked fine for us so far, but I see why an animated replace would be easier to use.

We usually want to avoid the animations for replace, because it lets us re-configure the route and the scene without causing any movement. If replace animates then we would loose that ability.

I'm happy to hear more thoughts on how this can be improved!

**Comment by brentvatne** [comment] 2015-05-30 22:55
@mjw56 @ericvicenti - if there is still interest in pursuing animations on replace, let's open a new issue for it

**Closed by brentvatne** 2015-05-30 22:55 UTC
