### ISSUE TITLE
How to present to a TabBarIOS with native code?

### ISSUE THREAD

**Issue by magic3584** [facebook/react-native#10968] opened 2016-11-16 09:04 UTC
### Description

Present to a TabBarIOS with native code

### Reproduction

http://stackoverflow.com/questions/40627144/is-there-anyway-to-present-a-native-controller-to-a-tabbarios-with-react-native

**Comment by ericvicenti** [comment] 2016-11-16 16:57
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but we can reopen if additional information is provided. Thanks!

**Closed by ericvicenti** 2016-11-16 16:57 UTC

**Comment by magic3584** [comment] 2016-11-17 01:32
It's my fault that I forgot to include **RCTImage**  [http://stackoverflow.com/a/40634881/4256995](url)

All react native modules including TabBarIOS are views, am I right?

**Comment by ericvicenti** [comment] 2016-11-17 01:53
All native modules are either views, where there can be many of them, all managed by a ViewManager. Or you can export APIs, and there is only one of each. On iOS you can export an API with RCT_EXPORT_MODULE. (You can search around to find out more about how it is used)
