### ISSUE TITLE
Picker Component resets when items list changes

### ISSUE THREAD

**Issue by stochris** [facebook/react-native#13351] opened 2017-04-06 17:54 UTC
### Description

If the picker item list changes, then, in some cases, the picker will call the `onValueChange` callback with the first item in the list as it's argument.

### Reproduction Steps and Sample Code

This can be reproduced at [https://snack.expo.io/Sy1JClEag](https://snack.expo.io/Sy1JClEag).

Select 2 or 3, then click on exclude. The new value is 1. This does not happen if you select a higher value than the one being excluded

### Solution

Do not call the `onValueChange` callback when the items list changes, but the `selectedValue` is stil present in the list

### Additional Information

* React Native version: 0.42
* Platform: Android
* Development Operating System: Linux
* Dev tools: Android SDK version 23

**Comment by caseyg1204** [comment] 2017-04-24 21:24
Did you find a work around for this?

**Comment by stochris** [comment] 2017-04-24 22:08
Nope. In theory, I think it should be doable, but it seems overly complicated. In my case, I managed to get rid of the need to change the picker items.

**Comment by joshuapinter** [comment] 2017-07-12 04:29
Got snagged with this as well. I am renaming my items in the Picker and when you update the Picker items, including the renamed one, it loses the selected value, even if your selected value is still in the list. 

For example: 

```js
<Picker selectedValue="2" ...>
  <Picker.Item key="1" value="1" label="One" />
  <Picker.Item key="2" value="2" label="Two" />
  <Picker.Item key="3" value="3" label="Three" />
</Picker>
```

If you change the second `Picker.Item` to: 

```js
<Picker.Item key="2" value="2" label="Second" />
```

It has to re-renders but it loses the selectedValue is just becomes the first one, even though the value of the selected item hasn't changed, just the label.

Might be a little confusing but it's a real pain when renaming things. For now, I am getting around it with a dirty solution that adds a new `Picker.Item` to the list instead of renaming one, which seems to work fine. Except that now you have an invalid Picker.Item in the list.

**Comment by goblinbr** [comment] 2017-07-25 17:53
This resolved for me:

```javascript
import React, { Component } from 'react';
import { Picker, Platform } from 'react-native';

class MyPicker extends Component {

  componentWillReceiveProps(nextProps) {
    if (Platform.OS === 'android') {
      let selectedIndex = -1;
      nextProps.children.forEach((c, i) => {
        if (c.props.value === nextProps.selectedValue) {
          selectedIndex = i;
        }
      });
      this.refs.picker._reactInternalInstance._renderedComponent._instance.setState({ initialSelectedIndex: selectedIndex, selectedIndex });
    }
  }

  onValueChange(value, index) {
    if (value !== this.props.selectedValue) {
      this.props.onValueChange(value, index);
    }
  }

  render() {
    return (
      <Picker ref='picker' {...this.props} onValueChange={this.onValueChange.bind(this)}>
        {this.props.children}
      </Picker>
    );
  }
}

MyPicker.Item = Picker.Item;

export { MyPicker };
```

**Comment by denisftw** [comment] 2017-08-10 12:31
@goblinbr Thanks for the solution, but for some reason it didn't help me.

Honestly, I'm a little surprised that a major bug such as this attracts so little attention. I just started working with the `Picker` component and immediately stumbled upon it. It is easily reproducible on the latest 0.47 version on both the emulator and the actual Android 6.0 phone despite the fact that #9220 was closed a couple of weeks ago.

**Comment by ethan6077** [comment] 2017-08-11 00:23
@goblinbr Thank you for you solution, but it doesn't work on me as well. This would not stop triggering the "onValueChange". Is there any other walkaround?

**Comment by Hirvesh** [comment] 2017-09-10 09:11
Having the same issue. React Native 0.48.2

**Comment by joshuapinter** [comment] 2017-09-10 15:25
I would love it if an core member would jump in here and give their thoughts. That would be enough for myself or somebody else to work on a PR. But working on a PR without a core member's encouragement is a risky use of time.

**Comment by Hirvesh** [comment] 2017-09-13 03:42
Never mind, the issue was on my side, I has two onValueChange attritubes declared on my component. :man_facepalming:

**Comment by joshuapinter** [comment] 2017-09-13 15:04
@hirvesh So you're saying this is no longer an issue on 0.48.2?

**Comment by denisftw** [comment] 2017-09-13 16:27
I've just tried it on 0.48.2 - same problem. 

In my scenario, I have a component with multiple Picker elements and one of them changes the interface language. When I change the language and save the settings, the component re-renders and some Picker elements receive new labels. All numeric Pickers retain the correct states, but all text-based ones are reset to the first element.

Probably @Hirvesh's use case is different.

**Comment by ylac** [comment] 2017-10-27 00:54
I get this bug as well on react native 0.44.3. I traced it to the event argument in _onChange in PickerAndroid.android, but I can't see any difference between the event arg when the option is actually being selected and when the options are changing. 

Could one of the core devs please look into this?

**Comment by laurent22** [comment] 2017-11-03 17:32
Still happening in 0.49. This Picker component is so full of bugs that I wonder if it'd make sense to just rewrite it.

**Comment by rahulrvp** [comment] 2017-12-06 13:20
Hi there, I had the same issue (resetting display value to 0th index on value change) and this is how I solved this.

```js
<Picker
  selectedValue = { this.state.selectedValue }
  onValueChange = {
    (itemValue, itemIndex) => { this.setState({ selectedValue : itemValue })}
  }>
    {
      /* code to populate picker with items */
    }
</Picker>

```

Hope this helps!

**Comment by syamjayaraj** [comment] 2018-01-24 03:49
https://stackoverflow.com/questions/37597665/how-to-make-react-native-picker-stay-at-newly-selected-option

Working perfectly

**Comment by pencilcheck** [comment] 2018-01-29 07:43
Has to coerce into string for proper comparison

**Comment by joshuapinter** [comment] 2018-06-17 02:45
@stale This is still an issue. 

@syamjayaraj's link to a "solution" that is "working perfectly" has nothing to do with this issue. That solution refers to changing the selection of a Picker, not editing an Option for the Picker and having the current value reset after making that edit.

So, yes, this is still an issue in the react-native core and should remain on here and get some attention from the react-native core.

**Comment by bitcrumb** [comment] 2018-06-26 12:40
@stale Also experiencing this issue

**Comment by hramos** [comment] 2018-06-26 19:37
I took a look at this, and it seems to be expected behavior. From the [`PickerAndroid.android.js` source code](https://github.com/facebook/react-native/blob/master/Libraries/Components/Picker/PickerAndroid.android.js#L135-L140),

    // The picker is a controlled component. This means we expect the
    // on*Change handlers to be in charge of updating our
    // `selectedValue` prop. That way they can also
    // disallow/undo/mutate the selection of certain values. In other
    // words, the embedder of this component should be the source of
    // truth, not the native component.

Therefore, @goblinbr's [solution](https://github.com/facebook/react-native/issues/13351#issuecomment-317817198) is correct.

**Comment by denisftw** [comment] 2018-06-27 01:44
@hramos Thanks for checking out this thread, but I doubt that this could be expected behaviour. Have you seen my use case?

> In my scenario, I have a component with multiple Picker elements and one of them changes the interface language. When I change the language and save the settings, the component re-renders and some Picker elements receive new labels. All numeric Pickers retain the correct states, but all text-based ones are reset to the first element.

Note that I only update the labels, not values, and there is no reason for the component to touch `selectedValue`, let alone reset it to the first option. 

Also, as far as I can tell, the solution you're referring to didn't help anyone in this thread.

**Comment by slorber** [comment] 2018-06-27 17:30
Hey @hramos 

I can actually confirm the usecase of @denisftw because I have the exact same problem on the exact same usecase. I want my users to be able to select the app language.

My code looks like:

```js
class PhotographerLanguageSection extends React.PureComponent {
  render() {
    return (
      <LanguageConsumer>
        {(language, updateLanguage) => {
          return (
            <PreferenceSection name="language">
              <View padding={Spacing}>
                <Picker
                  primary
                  values={AVAILABLE_LANGUAGES}
                  label={lang =>
                    formatMessage({ id: `preferences.language.${lang}` })
                  }
                  selectedValue={language}
                  onValueChange={newLanguage => {
                    updateLanguage(newLanguage);
                  }}
                />
              </View>
            </PreferenceSection>
          );
        }}
      </LanguageConsumer>
    );
  }
}
```

And I get the `onValueChange` triggered 3 times everytime I select a new language.


Now, if I simply remove the 

```js
                  label={lang =>
                    formatMessage({ id: `preferences.language.${lang}` })
                  }
```

it actually works fine (and I'll use that as a workaround for now)

The problem is that when the language change, I actually want to translate the language options in the new language :)

**Comment by iswanj** [comment] 2018-06-28 10:00
Having the same issue on React Native 0.55.4. It only happens when sending new `Picker.Item` lists

**Comment by savvopoulos** [comment] 2018-07-07 10:42
same here

**Comment by savvopoulos** [comment] 2018-07-13 22:44
The last solution didn't fix it for me - however it made me realize what was going on.

In my case, there was an event that was changing the Picker.Items' labels. That was then causing the currently selected item to reset.

**Comment by moltenyyu** [comment] 2018-12-27 11:05
Here's a simple workaround I'm using. This might not suit all usages.

The key point is when you know the options' label will be changed, force React to create a new `Picker` node instead of updating the existing one.

```
// inside a component which renders Picker
render() {
  // say you know the change of UI language will cause the labels to be changed
  return (
    <div>
        <Picker
            key=`gender-${language}`
        >
            {genderOptions}
        </Picker>
        <Picker
            key=`month-${language}`
        >
            {birthMonthOptions}
        </Picker>
    </div>
  );
}
```

**Comment by jcppman** [comment] 2018-12-27 11:06
Here's a simple workaround I'm using. This might not suit all usages.

The key point is when you know the options' label will be changed, force React to create a new Picker node instead of updating the existing one.

// inside a component which renders Picker
render() {
  // say you know the change of UI language will cause the labels to be changed
  return (
    <div>
        <Picker
            key=`gender-${language}`
        >
            {genderOptions}
        </Picker>
        <Picker
            key=`month-${language}`
        >
            {birthMonthOptions}
        </Picker>
    </div>
  );
}

**Comment by joshuapinter** [comment] 2018-12-27 17:13
@jcppman Interesting. I wonder if you could use a SHA hash or some unique ID for the Array of options, and keep that in the `Picker`'s `key` prop. Then whenever the values change at all, it would cause a re-render of the entire `Picker` component. 

Very similar to how assets are hashed in web servers, like Rails.

**Comment by joshuapinter** [comment] 2018-12-28 16:37
@jcppman Nice job! Can't wait to give this a go and see how it works. 👍

**Comment by Keronmat** [comment] 2019-02-07 16:02
You can try this 
`onValueChange (value: string) {
        this.setState({
            selected1 : value
        });
    }

 <Picker
                        iosHeader="Select one"
                        mode="dropdown"
                        selectedValue={this.state.selected1}
                        onValueChange={this.onValueChange.bind(this)}>
                        <Item label="Cats" value="key0" />
                        <Item label="Dogs" value="key1" />
                        <Item label="Birds" value="key2" />
                        <Item label="Elephants" value="key3" />
                   </Picker>`

**Comment by Octaner** [comment] 2019-02-26 11:35
@goblinbr alternative component version to fix this problem with deep-equal npm package

`import React, { Component } from 'react'
import { Picker, Platform } from 'react-native'
import equal from 'deep-equal'

class FixedPicker extends Component {
  disabledOnValueChange = false

  componentWillReceiveProps (nextProps) {
    if (Platform.OS === 'android') {
      const thisChildrenProps = this.props.children.map(child => child.props)
      const nextChildrenProps = nextProps.children.map(child => child.props)

      if (equal(thisChildrenProps, nextChildrenProps) === false) this.disabledOnValueChange = true
    }
  }

  onValueChange = (value, index) => {
    if (this.disabledOnValueChange === true) {
      this.disabledOnValueChange = false
      return
    }

    this.props.onValueChange(value, index)
  }

  render() {
    return (
      <Picker
        ref='picker'
        {...this.props}
        onValueChange={this.onValueChange}
      >
        {this.props.children}
      </Picker>
    )
  }
}

FixedPicker.Item = Picker.Item

export { FixedPicker }`

**Comment by joshuapinter** [comment] 2019-02-28 01:47
Hey @jcppman, that worked great!!

**Comment by joshuapinter** [comment] 2019-02-28 02:26
For those that might want this in a Component form, here's the modified version. 

```js
import React      from "react";
import { Picker } from "react-native";

// This is necessary because the native Picker does not handle edits of existing Picker.Items.
// For example, if you edit the selected Picker.Item, it will lose the selected value. This fixes that.
//
// See https://github.com/facebook/react-native/issues/13351#issuecomment-450281257
//
export default class FixedPicker extends React.Component {

  render() {
    const key = React.Children.map( this.props.children, child => Object.values( child.props ).join( "," ) ).join( ";" );

    return <Picker { ...this.props } key={ key } />;
  }

}
```

Thanks again, @jcppman!

**Comment by itachi-rg** [comment] 2019-03-10 06:13
Thanks @jcppman and @joshuapinter ! Modifications at multiple places was made simple by the modified version !

**Comment by antonioaltamura** [comment] 2019-03-16 18:48
@jcppman I wasted hours on this bug, at first I thought it came from react-18next (my use case is the same of yours, a Picker to switch app language). Thanks a lot!

Honestly, seeing open issue this big from 2017 is worring me a lot, is React-native still in active development/bugfixing?

**Comment by joshuapinter** [comment] 2019-03-16 18:54
@antonioaltamura Are you kidding me? There's been 4 commits in the last 12 hours. 

<img width="642" alt="Screen Shot 2019-03-16 at 12 52 48 PM" src="https://user-images.githubusercontent.com/180819/54480131-7e655400-47ea-11e9-9d5f-a518e843f3a2.png">

Don't get me wrong, I'm as frustrated as you are that these seemingly glaring bugs are still not fixed in master after several years and a dozen releases, but a quick look at the repo shows it's under *very* active development.

**Comment by TheSavior** [comment] 2019-03-19 17:02
I was able to repro this on 0.59. If someone wants to investigate this problem and send a PR that would be greatly appreciated.

**Comment by cpojer** [comment] 2019-05-09 13:48
cc @Kudo

**Comment by Kudo** [comment] 2019-05-10 05:41
@cpojer Here is the PR https://github.com/facebook/react-native/pull/24793 to address this issue.
Controlled component is hard, hopefully if there could be some systematical solution.

**Closed** 2019-05-10 07:55 UTC
Labels: Bug, Help Wanted :octocat:, Platform: Android, Ran Commands

**Comment by waqaramjad** [comment] 2019-10-07 14:20
same issue here

**Comment by waqaramjad** [comment] 2019-10-07 14:25
> https://stackoverflow.com/questions/37597665/how-to-make-react-native-picker-stay-at-newly-selected-option
> 
> Working perfectly

you should understand the issue first

**Comment by lucasriondel** [comment] 2020-01-03 13:15
same issue.

**Comment by shogunpurple** [comment] 2020-01-21 11:33
Same issue here.

**Comment by AlexandrDobrovolskiy** [comment] 2020-02-14 12:37
There is this naming trouble, be careful, prop `selectedValue` accepts the **index** of the selected value.
