### ISSUE TITLE
SyntaxError: Unexpected use of reserved word 'let' in strict mode

### ISSUE THREAD

**Issue by tomprogers** [facebook/react-native#6298] opened 2016-03-04 17:04 UTC
Transpiled `import` code throws an immediate exception at runtime:

```
SyntaxError: Unexpected use of reserved word 'let' in strict mode
```

There is exactly one instance of `let` in the transpiled code, which I believe I've traced back to this statement in `@exponent/react-native-navigator`: 

```
// ExNavigator.js:21
import type * as ExRoute from './ExRoute';
```

Here's the specific set of dependencies and my project's entire babelrc:

`package.json`
```
{
  "name": "test",
  "dependencies": {
    "babel-plugin-transform-decorators-legacy": "1.3.4",
    "babel-preset-react-native": "1.5.1",
    "react-native": "0.20.0",
    "react-native-router-flux": "2.3.9"
  }
}
```

`.babelrc`
```
{
    "presets": ["react-native"],
    "plugins": ["transform-decorators-legacy"]
}
```

My understanding is that the `react-native` babel preset is responsible for transforming the entire dependency chain into something that will run inside the react-native runtime environment. It's emitting a `let` statement that won't run.

**Env info**
OS: MacOS 10.11.3
Runtime: iPhone5 simulator via Xcode Version 7.2 (7C68)
node: v5.5.0
npm: 3.6.0

**Comment by marcshilling** [comment] 2016-03-04 17:13
This literally just happened to me. My project was working fine, but when a coworker pulled it down fresh from github he ran into it. I then deleted my project to try to reproduce and the same thing happened to me. Stumped.

**Comment by tomprogers** [comment] 2016-03-04 17:32
@marcshilling I'm talking to the babeljs people about it now, and I'm setting up a small repo that demonstrates the problem. Should be up in 10 minutes.

**Comment by marcshilling** [comment] 2016-03-04 18:32
I locked my babel-preset devDependency versions to where they were previously working, and still the same issue. This is absurd.

**Comment by ide** [comment] 2016-03-04 18:45
We ran into this yesterday and didn't dig deep but believe that Babel could have broken something. @marcshilling even if your babel preset's version is locked, its dependencies aren't locked so....

**Comment by tomprogers** [comment] 2016-03-04 19:29
Yeah, the only way to really avoid these problems is to shrinkwrap your project. We hadn't gotten that far, because we're still choosing libraries.

**Comment by brentvatne** [comment] 2016-03-06 19:32
@kittens @amasad @thejameskyle

**Comment by thejameskyle** [comment] 2016-03-06 21:08
If someone can provide input code that creates invalid output code then I could reproduce this, but using the example in this issue works as expected: https://github.com/thejameskyle/__babel-bug-react-native-6298

**Comment by amasad** [comment] 2016-03-06 21:11
Cc @hzoo I think there was a bad release that broke block scoping. Are you
sure you're at the latest version?

I also want us to move away from using semver versions in Babel internally
so that if you look your Babel-core or preset version you wouldn't get
transitive dependency that were just released.

**Comment by brentvatne** [comment] 2016-03-06 21:19
>  I also want us to move away from using semver versions in Babel internally
> so that if you look your Babel-core or preset version you wouldn't get
> transitive dependency that were just released.

@amasad - is there an issue tracking that on babel phabricator? if so we can just close this and link to it

**Comment by thejameskyle** [comment] 2016-03-06 21:23
Discussing removing the ^semver ranges here https://github.com/kittens/lerna/issues/76 and updates on transitive dependencies here: https://github.com/kittens/lerna/issues/27

**Comment by kittens** [comment] 2016-03-06 21:27
react native uses a shrinkwrap so I don't think that issue is relevant?

**Comment by hzoo** [comment] 2016-03-06 21:47
It's weird that `import type * as ExRoute from './ExRoute';` is resulting in a let?

`import type` should be stripped away by the strip-flow-types plugin in the react-native preset https://github.com/facebook/react-native/blob/master/babel-preset/plugins.js#L28?

**Comment by hzoo** [comment] 2016-03-06 21:48
Ah and also regarding `let`, in 6.6.5, we pushed a release that removes `let` from the common js transform (which is what this is about `import *`), since before we were relying on the block scoping plugin to run and change it to a var.

https://github.com/babel/babel/releases/tag/v6.6.5

> #3391 Make buildExportAll generate pure ES5 code.. (@benjamn), https://github.com/babel/babel/pull/3391

So it shouldn't be an issue after updating to that?

**Comment by brentvatne** [comment] 2016-03-06 22:04
See #6203 for another instance of this occurring

**Comment by thejameskyle** [comment] 2016-03-06 22:11
@brentvatne You sure this isn't because react-native is shipping uncompiled code? That example in the other issue is from `node_modules/react-native/local-cli/cli.js:74` and Babel shouldn't be compiling `node_modules`

**Comment by brentvatne** [comment] 2016-03-06 22:20
@thejameskyle - I'm not so familiar with how the cli works, I'll reopen that issue and ping appropriate person, sorry about the noise!

**Comment by hzoo** [comment] 2016-03-06 23:50
I just setup react native on android with the same preset/plugins and with `import type * as ExRoute from './ExRoute';` and wasn't able to reproduce.

This is with `babel-plugin-transform-es2015-modules-commonjs@6.6.5` which has the changes I mentioned [above](https://github.com/facebook/react-native/issues/6298#issuecomment-193003007).

**Comment by martinbigio** [comment] 2016-03-07 01:30
The problem is that `babel/register` doesn't work for the file that includes that directory, on this case `local-cli/cli.js`. Replacing `const` for `var` should fix the issue. I'm not sure why this doesn't repro consistently..

**Comment by martinbigio** [comment] 2016-03-07 01:31
Sorry, I meant to comment on https://github.com/facebook/react-native/issues/6203.

**Comment by kittens** [comment] 2016-03-07 01:46
The source should just be compiled instead of using `babel/register`. `babel/register` is bad for performance and memory. Take a peak at `~/.babel.json` after running the react native CLI. All of that is being loaded into memory, and on first load/compile it's pretty slow.

**Comment by martinbigio** [comment] 2016-03-07 02:16
cc @davidaurelio

**Comment by davidaurelio** [comment] 2016-03-07 09:43
@hzoo: unfortunately, the packager currently follows type imports. I’m going to land a change today that changes that.

@martinbigio Yes, I was thinking about that for a while. But it’s doesn’t have a high prio for me. We should tailor a transform that keeps everything that node 4 supports natively.

**Comment by davidaurelio** [comment] 2016-03-07 09:46
I meant, use [babel-preset-modern-node](https://www.npmjs.com/package/babel-preset-modern-node)

**Comment by martinbigio** [comment] 2016-03-07 15:30
Oh that's awesome!

**Comment by tomprogers** [comment] 2016-03-07 18:28
As of this morning, the issue appears to be fixed. I'm not shrinkwrapping my deps just yet, so nuking my node_modules and reinstalling very possibly pulled in a different version of babel, react-native, and/or the react-native babel preset.

Thanks everyone for whatever you did. 8)

Today will be spent setting up npm-shrinkwrap.

**Comment by marcshilling** [comment] 2016-03-07 19:06
Confirmed this is also resolved for me now!

@tomprogers shouldn't take you a day, I just set it up in 2 minutes! Let's hope it prevents crap like this from happening again :)

**Comment by satya164** [comment] 2016-03-08 18:23
Closing this since this seems to be fixed now.

**Closed by satya164** 2016-03-08 18:23 UTC
