### ISSUE TITLE
[Android] should i call Fresco.shutDown() in reactActivity.onDestroy() 

### ISSUE THREAD

**Issue by JuanbingTeam** [facebook/react-native#8518] opened 2016-07-01 04:23 UTC
I tried the following steps:
1. start my RN app
2. exit by pressing back button
3. repeat 1,2 for several times

I found the memory keep increasing , and finally it lead to an OOM Exception.
With the help of AndroidStudio Monitor View, i found too many bitmaps were cached.

I tried to call Fresco.shutdown() manually in onDestroy, it seems better.

`@Override
    protected void onDestroy() {

super.onDestroy();
Fresco.shutDown();   // call shutdown manually
  if (mReactInstanceManager != null) {
            mReactInstanceManager.destroy();
        }
    }`

Here are my questions:
1. When will the images cached by Fresco be recycled?
2. Do I need to release images manually?

Thanks guys....

**Comment by oprisnik** [comment] 2016-08-01 12:28
This could be related to #8677. In theory, you should not need to do anything manually.

**Comment by norman-kapschefsky** [comment] 2016-09-20 14:47
Have to clear Fresco stuff as well in ``onDestroy()`` of ``ReactActivity``. Without it the memory of app process gets higher and higher wenn starting and closing the app frequently. Without it the problem is gone. Should be investigated in more detail because that is critical I guess. I did:

```
@Override
protected void onDestroy() {
    super.onDestroy();

    ImagePipeline imagePipeline = Fresco.getImagePipeline();
    imagePipeline.clearMemoryCaches();
    Fresco.shutDown();
}
```

**Comment by oprisnik** [comment] 2016-09-20 16:36
This should have been fixed with recent React Native versions. RN was re-initializing Fresco which lead to these issues.

**Comment by JuanbingTeam** [comment] 2016-09-22 09:22
Thanks @oprisnik  & @norman-kapschefsky , I will do more tests with latest version.

**Comment by ericnakagawa** [comment] 2017-01-10 18:23
Hi @JuanbingTeam I'll be closing this issue since there has been several updated versions of RN.

**Closed by ericnakagawa** 2017-01-10 18:23 UTC
Labels: Android

**Comment by JuanbingTeam** [comment] 2017-01-12 11:24
thank you, yes ,this has been fixed~
