### ISSUE TITLE
Modal component on Android is not underneath a translucent StatusBar, inconsistent with iOS

### ISSUE THREAD

**Issue by calebmer** [facebook/react-native#9090] opened 2016-07-29 18:06 UTC
When you set `translucent` to true in a `StatusBar` component in Android, then open a `Modal` component, the `Modal` children are not underneath the status bar like the main content. This is inconsistent to the behavior on iOS where `Modal` children are underneath the status bar. Therefore as a workaround you need to add a style that looks something like this to the body of a modal:

``` js
marginTop: Platform.OS === 'android' ? -StatusBar.currentHeight : 0
```
- Minimal code snippet: https://rnplay.org/apps/0ppHZw
- Version of React Native is `0.29.0`
- The error only occurs in Android (but if it occurred in both would it be a feature and not a bug?)
- I’m developing on a Mac.

…and here is the code snippet copy/pasted from RNPlay (works on both iOS and Android):

``` js
import React, { Component } from 'react'
import { AppRegistry, View, Text, TouchableOpacity, StatusBar, Modal } from 'react-native'

class SampleApp extends Component {
  state = {
    isModalOpen: false,
  }

  handleModalOpen = () => this.setState({ isModalOpen: true })
  handleModalClose = () => this.setState({ isModalOpen: false })

  render () {
    return (
      <View>
        <StatusBar
            translucent
            barStyle="light-content"
            backgroundColor="rgba(0, 0, 0, 0.2)"
        />
        <Text>I’m underneath the status bar</Text>
        <TouchableOpacity onPress={this.handleModalOpen}>
            <Text style={{ marginTop: 50 }}>Press me to open the modal</Text>
        </TouchableOpacity>
        <Modal
            animationType="slide"
              transparent={false}
            visible={this.state.isModalOpen}
            onRequestClose={this.handleModalClose}
        >
            <View style={{ flex: 1, backgroundColor: 'white' }}>
            <Text>I should be underneath the status bar</Text>
            <TouchableOpacity onPress={this.handleModalClose}>
              <Text style={{ marginTop: 50 }}>Press me to close the modal</Text>
            </TouchableOpacity>
            </View>
          </Modal>
      </View>
    )
  }
}

AppRegistry.registerComponent('SampleApp', () => SampleApp)
```
### iOS Modal closed

![screen shot 2016-07-29 at 2 03 49 pm](https://cloud.githubusercontent.com/assets/8282507/17258539/6bec04bc-5595-11e6-8f58-fa1266cf2dfd.png)
### iOS Modal opened

![screen shot 2016-07-29 at 2 04 04 pm](https://cloud.githubusercontent.com/assets/8282507/17258546/7578c16e-5595-11e6-8e78-00cae76b17fe.png)
### Android Modal closed

![screen shot 2016-07-29 at 2 04 22 pm](https://cloud.githubusercontent.com/assets/8282507/17258558/7f466322-5595-11e6-9518-d9678e39a6b7.png)
### Android Modal opened (ERROR HERE)

![screen shot 2016-07-29 at 2 04 32 pm](https://cloud.githubusercontent.com/assets/8282507/17258562/8729b436-5595-11e6-9fb3-1ea1201d1997.png)

**Comment by lacker** [comment] 2016-10-28 20:23
Is this still a problem? I seem to recall @satya164 discussing some fix here but I could be mistaken.

**Comment by mvf4z7** [comment] 2016-11-08 20:37
As far as I can tell, yes this is still a problem, as I believe I am dealing with something similar.

My situation is that I have set the status bar to hidden at the root of my app, but when I am on android and display a modal the status bar becomes visible. On iOS the status bar remains invisible in this situation (the desired behavior for my application).

Furthermore, I have my app in Immersive mode, and as such the soft navigation buttons (ie back, home, multitasking) are also hidden throughout the app. When a modal is displayed the navigation keys become visible, similar to the status bar.

**Comment by kevinresol** [comment] 2017-01-19 09:11
> Furthermore, I have my app in Immersive mode, and as such the soft navigation buttons (ie back, home, multitasking) are also hidden throughout the app. When a modal is displayed the navigation keys become visible, similar to the status bar.

I can confirm this behaviour.

**Comment by nascode** [comment] 2017-04-06 18:19
0.43.0 here. I can confirm that there is still a bug when using modal with translucent status bar on android

**Comment by PestiB9** [comment] 2017-04-30 18:13
Yep, if i set my StatusBar to translucent its background just become black (my app don fit his space), and hidden it's not working (the background still green and StatusBar always visible)

**Comment by dantman** [comment] 2017-04-30 18:31
It's not a direct fix for this, but I fixed the related bug that causes the translucent StatusBar to darken when the Modal is opened on android. #13629

**Comment by hramos** [comment] 2017-07-21 05:21
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, it does not seem like there has been any traction on this issue for some time.

The issue is being copied over to our feature request tracker at Canny: https://react-native.canny.io/admin/board/feature-requests/p/modal-component-on-android-is-not-underneath-a-translucent-statusbar-inconsisten

There you can upvote issues that are important to you. This will help contributors identify the issues that the community cares about.

If you think this issue should definitely remain open here in the issue tracker and not on Canny, let us know.

**Closed by hramos** 2017-07-21 05:21 UTC
Labels: Android

**Comment by alexmngn** [comment] 2017-10-18 15:13
This is still an issue for me, RN 0.49

**Comment by firatakandere** [comment] 2018-02-07 13:46
Still an issue, 0.52.2

**Comment by AnyGong** [comment] 2018-02-08 01:50
+1

**Comment by firatakandere** [comment] 2018-02-16 10:59
+1

**Comment by sound2gd** [comment] 2018-03-16 05:52
+1

**Comment by edo1493** [comment] 2018-03-17 13:55
+1

**Comment by mderrick** [comment] 2018-05-16 09:41
I still have this issue and the `-StatusBar.currentHeight` trick no longer works for me.

**Comment by tinisky** [comment] 2018-05-17 04:09
+1

**Comment by arsal-wal** [comment] 2018-06-26 08:06
+1

**Comment by lihxhit** [comment] 2018-07-01 13:15
+1

There seems to be a pr which deal with the hidden statusbar
but we need a translucent StatusBar
