### ISSUE TITLE
Command+M doesn't work but i can see the menu

### ISSUE THREAD

**Issue by sunxlfree** [facebook/react-native#13667] opened 2017-04-26 03:10 UTC
i can run the react native project on a genymotion and i can see the screen correctly.
but when i want to open the menu, Command+M or Fn + F2 doesn't work
and i can see the menu at the right side, but it doesn't work when i click it
![image](https://cloud.githubusercontent.com/assets/9950351/25416451/7f506d4e-2a70-11e7-986c-67fcf77bd767.png)
and if i click the R，it seems that the StackNagivator is work
![image](https://cloud.githubusercontent.com/assets/9950351/25416498/ab6dc160-2a70-11e7-8caf-824fbeb3b73e.png)

**Comment by hramos** [comment] 2017-04-26 16:35
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-04-26 16:35 UTC
