### ISSUE TITLE
Your RubyGems version (3.0.3.1) has a bug that prevents `required_ruby_version` from working for Bundler

### ISSUE THREAD

**Issue by programerTala** [facebook/react-native#37301] opened 2023-05-08 08:56 UTC
### Description

**i am trying to install react native and give many errors for two days.please help me to fix my errors**
**I tried to install everythings are explained here 'https://reactnative.dev/docs/environment-setup?guide=native' but at least when i run init project gives me error**

<img width="429" alt="Screen Shot 1402-02-18 at 12 21 59" src="https://user-images.githubusercontent.com/132842846/236780775-21cb7d99-c537-41d6-931f-ee68a5d2d5b1.png">

`error Your RubyGems version (3.0.3.1) has a bug that prevents `required_ruby_version` from working for Bundler. Any scripts that use `gem install bundler` will break as soon as Bundler drops support for your Ruby version. Please upgrade RubyGems to avoid future breakage and silence this warning by running `gem update --system 3.2.3` Gem::Ext::BuildError: ERROR: Failed to build gem native extension. current directory: /Users/apple/Desktop/template/vendor/bundle/ruby/2.6.0/gems/ffi-1.15.5/ext/ffi_c /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20230508-4891-11u18l.rb extconf.rb --enable-system-libffi checking for ffi_prep_closure_loc() in -lffi... no checking for ffi_prep_closure_loc() in -llibffi... no checking for ffi_prep_closure_loc() in -llibffi-8... no system libffi is not usable *** extconf.rb failed *** Could not create Makefile due to some reason, probably lack of necessary libraries and/or headers.  Check the mkmf.log file for more details.  You may need configuration options. Provided configuration options: --with-opt-dir --without-opt-dir --with-opt-include --without-opt-include=${opt-dir}/include --with-opt-lib --without-opt-lib=${opt-dir}/lib --with-make-prog --without-make-prog --srcdir=. --curdir --ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/$(RUBY_BASE_NAME) --with-ffi_c-dir --without-ffi_c-dir --with-ffi_c-include --without-ffi_c-include=${ffi_c-dir}/include --with-ffi_c-lib --without-ffi_c-lib=${ffi_c-dir}/lib --enable-system-libffi --with-libffi-config --without-libffi-config --with-pkg-config --without-pkg-config --with-ffilib --without-ffilib --with-libffilib --without-libffilib --with-libffi-8lib --without-libffi-8lib To see why this extension failed to compile, please check the mkmf.log which can be found here: /Users/apple/Desktop/template/vendor/bundle/ruby/2.6.0/extensions/universal-darwin-21/2.6.0/ffi-1.15.5/mkmf.log extconf failed, exit code 1 Gem files will remain installed in /Users/apple/Desktop/template/vendor/bundle/ruby/2.6.0/gems/ffi-1.15.5 for inspection. Results logged to /Users/apple/Desktop/template/vendor/bundle/ruby/2.6.0/extensions/universal-darwin-21/2.6.0/ffi-1.15.5/gem_make.out /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:99:in `run' /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/ext_conf_builder.rb:47:in `block in build' /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tempfile.rb:295:in `open' /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/ext_conf_builder.rb:29:in `build' /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:185:in `block in build_extension' /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize' /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:181:in `build_extension' /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:229:in `block in build_extensions' /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:226:in `each' /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:226:in `build_extensions' /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/installer.rb:830:in `build_extensions' /Users/apple/.gem/ruby/2.6.0/gems/bundler-2.4.12/lib/bundler/rubygems_gem_installer.rb:72:in `build_extensions' /Users/apple/.gem/ruby/2.6.0/gems/bundler-2.4.12/lib/bundler/rubygems_gem_installer.rb:28:in `install' /Users/apple/.gem/ruby/2.6.0/gems/bundler-2.4.12/lib/bundler/source/rubygems.rb:198:in `install' /Users/apple/.gem/ruby/2.6.0/gems/bundler-2.4.12/lib/bundler/installer/gem_installer.rb:54:in `install' /Users/apple/.gem/ruby/2.6.0/gems/bundler-2.4.12/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec' /Users/apple/.gem/ruby/2.6.0/gems/bundler-2.4.12/lib/bundler/installer/parallel_installer.rb:156:in `do_install' /Users/apple/.gem/ruby/2.6.0/gems/bundler-2.4.12/lib/bundler/installer/parallel_installer.rb:147:in `block in worker_pool' /Users/apple/.gem/ruby/2.6.0/gems/bundler-2.4.12/lib/bundler/worker.rb:62:in `apply_func' /Users/apple/.gem/ruby/2.6.0/gems/bundler-2.4.12/lib/bundler/worker.rb:57:in `block in process_queue' /Users/apple/.gem/ruby/2.6.0/gems/bundler-2.4.12/lib/bundler/worker.rb:54:in `loop' /Users/apple/.gem/ruby/2.6.0/gems/bundler-2.4.12/lib/bundler/worker.rb:54:in `process_queue' /Users/apple/.gem/ruby/2.6.0/gems/bundler-2.4.12/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads' An error occurred while installing ffi (1.15.5), and Bundler cannot continue. In Gemfile: cocoapods was resolved to 1.12.1, which depends on cocoapods-core was resolved to 1.12.1, which depends on typhoeus was resolved to 1.4.0, which depends on ethon was resolved to 0.16.0, which depends on ffi error Error: Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/next/environment-setup and follow the React Native CLI QuickStart guide for macOS and iOS. Error: Error: Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/next/environment-setup and follow the React Native CLI QuickStart guide for macOS and iOS. at createFromTemplate (/Users/apple/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/commands/init/init.js:131:11) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async Object.initialize [as func] (/Users/apple/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/commands/init/init.js:184:3) at async Command.handleAction (/Users/apple/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/index.js:106:9)`

### After this error created a folder with enesial react native codes but does not run at all 
<img width="748" alt="Screen Shot 1402-02-18 at 12 39 49" src="https://user-images.githubusercontent.com/132842846/236784973-b896c2bc-af78-4a79-bce6-782dc5788f4c.png">

**My macbook pro mid 2015 **
<img width="674" alt="Screen Shot 1402-02-18 at 12 17 54" src="https://user-images.githubusercontent.com/132842846/236779775-c111b0c8-3088-47c5-b89b-4151530f5bf1.png">

<img width="877" alt="Screen Shot 1402-02-18 at 12 19 46" src="https://user-images.githubusercontent.com/132842846/236780159-e29331ed-f047-4ce6-9aed-2238a0200f20.png">

<img width="507" alt="Screen Shot 1402-02-18 at 12 20 59" src="https://user-images.githubusercontent.com/132842846/236780549-9f905b7e-f034-42cb-80f8-3a925f9f4e07.png">

<img width="763" alt="Screen Shot 1402-02-18 at 12 35 40" src="https://user-images.githubusercontent.com/132842846/236783936-c49c1096-10fa-46bf-b4c1-98f6fad82a34.png">
<img width="1280" alt="Screen Shot 1402-02-18 at 12 38 12" src="https://user-images.githubusercontent.com/132842846/236784470-b29d7008-1b9b-4589-8887-a05e35337ffe.png">

### React Native Version

0.71
latest version (i run react-native@latest)

### Output of `npx react-native info`

error: unknown command 'info'
(Did you mean init?)

<img width="748" alt="Screen Shot 1402-02-18 at 13 31 23" src="https://user-images.githubusercontent.com/132842846/236795873-c439c44d-d6aa-430e-842d-4a9ea388727e.png">

### **Tried to update rubygem but**

<img width="748" alt="Screen Shot 1402-02-18 at 18 59 00" src="https://user-images.githubusercontent.com/132842846/236866450-5943f264-5ee5-4f52-857d-727a4af3c6fb.png">

### Steps to reproduce

these things make problem 
cocopods 
bundle install 
ruby 

### Snack, code example, screenshot, or link to a repository

just run simple command in terminal 
`npx react-native@latest init AwesomeProject`

**Comment by programerTala** [comment] 2023-05-09 08:16
### [Errors when installing cocoapods with gem](https://stackoverflow.com/questions/60481623/errors-when-installing-cocoapods-with-gem)

### Fixed 
`
sudo xcodebuild -license accept
`
`ruby -rrbconfig -e 'puts RbConfig::CONFIG["rubyhdrdir"]'`
### Need to install 'libffi' and 'libffi-dev'
### Fixed 
install port at first from [here](https://guide.macports.org/chunked/installing.macports.html) 
`sudo port install libffi`
OR try with brew 
`brew install libffi`

### Installing xcodeproj 1.22.0 error
### Fixed 
I had this same error on macOS Monterey 12.6.2 with Xcode 13.4, Xcode 14.0.1 and Xcode 14.2 installed. Changing the default Xcode (Xcode / Preferences / Locations - "Command Line Tools:) from the latest (14.2) to 13.4 and trying again was successful. With 14.2 as the default: sudo gem install cocoapods -v 1.11.2 => #fail sudo gem install cocoapods => #fail (different error message) After changing to 13.4 as the default: sudo gem install cocoapods -v 1.11.2 => success, and pod --version => 1.11.2

### Install Gcc 
I had this issue today. install GCC prior to executing bundle install

### installing ffi 1.15.5 with native extensions building native extensions with: '--enable-system-libffi'
### Fixed 
bundle config --local build.ffi --with-cflags=-Wno-error=implicit-function-declaration

bundle install


### i think we can comment --enable-system-libffi from bundle config file in ~/.bundle/config
<img width="685" alt="237035577-2466f9cd-3e77-4cdf-946c-fefb6e3f42f3" src="https://user-images.githubusercontent.com/132842846/237036491-f413b321-4340-4afd-b906-9c228cb098cd.png">

**Comment by cortinico** [comment] 2023-05-09 10:46
That's a duplicate of https://github.com/facebook/react-native/issues/37183

**Comment by programerTala** [comment] 2023-05-09 11:23
> That's a duplicate of #37183
there is not perfect and complete soulution for this issue there...

**Closed** 2023-05-09 11:56 UTC
Labels: Needs: Attention, Needs: Version Info, 📦Bundler

**Comment by programerTala** [comment] 2023-05-09 16:17
### This steps work for me perfectly to create react native project without error 
1- npx react-native init testproject --skip-install -—npm
2- cd testproject 
3- npm install or yearn install 
4- cd ios
5- bundle config --local build.ffi --with-cflags=-Wno-error=implicit-function-declaration
6- bundle install
7- bundle exec pod install

**Comment by programerTala** [comment] 2023-05-09 17:42
This steps work for me perfectly to create react native project without error
1- npx react-native init testproject --skip-install -—npm
2- cd testproject
3- npm install or yearn install
4- cd ios
5- bundle config --local build.ffi --with-cflags=-Wno-error=implicit-function-declaration
6- bundle install
7- bundle exec pod install

Chek https://github.com/facebook/react-native/issues/37301 more information
