### ISSUE TITLE
[0.28] NetInfo.isConnected issue with RCTNetInfo + new event system

### ISSUE THREAD

**Issue by ryankask** [facebook/react-native#8469] opened 2016-06-28 12:22 UTC
`RCTNetInfo` was recently converted to use the new event system in https://github.com/facebook/react-native/commit/b71db1155440ec433dcf51b54c015166ecca8732 and this is causing issues with the `NetInfo` JS interface. I think this is because `RCTNetInfo.startObserving` is only called when an event listener is first added.

The following code:

```
componentDidMount() {
  setInterval(() => {
    NetInfo.isConnected.fetch().then(isConnected => console.log('isConnected?', isConnected));
  }, 250);
}
```

Will always return `isConnected? false` in 0.28 unless an event listener is added at some point. For example:

```
NetInfo.isConnected.addEventListener('change', Function.prototype);
```

Previous versions would quickly log `true` after start up. (see https://rnplay.org/apps/TJxDsQ -- note that RNPlay.org doesn't have 0.28 so the bug doesn't show up. That being said, if you comment out `NetInfo.isConnected.addEventListener` line, you can see the status still changes)

If this is supposed to be the new behaviour, I'm happy to write a documentation patch.

I've seen a few reports in the issues for this repo and a Facebook core developers group comment mentioning that users who show a bar when connectivity is lost see that bar on start up.

This is likely a side effect of the change although there was probably always an underlying timing issue that didn't show up because the the SCNetworkReachability code was running earlier in the start up process.

**Comment by mangogogos** [comment] 2016-07-22 18:08
For anyone who's looking for a workaround I do the following to force the module to be initialised:

````
// index.ios.js
import { AppRegistry, NetInfo } from 'react-native';
NetInfo.addEventListener( 'change', () => null ).remove();

... proceed with app startup logic
````

**Comment by ibussieres** [comment] 2016-09-01 18:04
For some reason, I am experiencing the same problem, but NOT on iOS (device or simulator). Only Android. 

    "react": "15.1.0",
    "react-native": "0.28.0"

**Comment by lacker** [comment] 2016-11-30 01:01
This seems like a dupe of https://github.com/facebook/react-native/issues/8615 so let's discuss in there. It's really not clear to me that this is intentional behavior fwiw.

**Closed by lacker** 2016-11-30 01:01 UTC
