### ISSUE TITLE
Android Push Notification

### ISSUE THREAD

**Issue by jihopark** [facebook/react-native#3683] opened 2015-10-26 09:08 UTC
Hi, I am now experimenting with React Native to build apps for both platforms to be on production.
However, I cannot find enough resources to work push notifications in Android platform (using GCM). Is it yet to be implemented? Can anyone give me some resource to test if it works?

**Comment by divyenduz** [comment] 2015-10-26 09:10
You get a generated Android project with a React Native app. You can always jump into Java and implement push notification the old way. I will share any react native specific resources I come across in a while.

**Comment by hswolff** [comment] 2015-10-27 13:55
I recently got this working in my project. Deserves a mini write up but the short of it is you need to do some native Java/Android work to set-up GCM in there. FYI I used this example project as a working example and it proved immensely helpful when setting up my own code: https://github.com/googlesamples/google-services/tree/master/android/gcm

**Comment by mlabrum** [comment] 2015-11-16 04:09
Looks like someone has implemented it https://github.com/oney/react-native-gcm-android

**Comment by liesislukas** [comment] 2016-02-25 10:56
https://github.com/oney/react-native-gcm-android works well with current RN version (v0.20) :+1:

**Comment by satya164** [comment] 2016-02-25 16:06
Duplicate of #3423

**Closed by satya164** 2016-02-25 16:06 UTC
Labels: Android
