### ISSUE TITLE
NetInfo.isConnected.fetch() is always returning false

### ISSUE THREAD

**Issue by dwilt** [facebook/react-native#9245] opened 2016-08-05 18:46 UTC
I'm trying to run `NetInfo.isConnected.fetch()` in my `componentDidMount` method but noticed that on both the simulator _and_ device it was returning false.  Clearly though I can tell I'm online because my component is `fetch`ing it's data and displaying it. As well as the fact that I can see I have 4 bars and am on 4g.

**Note**: I am using the Personal Hotspot on my phone that I am testing the internet connection on. The simulator that I'm running is on my computer that is tethered to my phone. Not sure if this would cause an issue. Here's my code:

```jsx
componentDidMount() {
    NetInfo.isConnected.fetch().then(isOnline => {
        // isOnline is always false!
    });
}
```

```
"react": "15.2.1",
"react-native": "0.28.0"
```

**I've only tested this on iOS - NOT Android**

I am using a Mac. 

I came across this [issue](https://github.com/facebook/react-native/issues/873) but I didn't understand what to do with `RCTReachability` in order to try and solve. Since it was last August though and I have been keeping up to date, I figured this was a separate issue.

**Comment by ryankask** [comment] 2016-08-06 09:16
@facebook-github-bot duplicate #8469

**Comment by facebook-github-bot-4** [comment] 2016-08-06 09:18
@ryankask tells me this issue is a duplicate of #8469. Let's discuss there, closing this one.

**Closed by facebook-github-bot-4** 2016-08-06 09:18 UTC
Labels: Ran Commands
