### ISSUE TITLE
Margin affects padding inside button (0.54.2) sdk 26

### ISSUE THREAD

**Issue by nikolal** [facebook/react-native#18911] opened 2018-04-18 07:01 UTC
Environment:
  OS: OS X El Capitan 10.11.6
  Node: 8.4.0
  Yarn: 1.3.2
  npm: 4.6.1
  Watchman: 4.7.0
  Xcode: Xcode 8.2.1 Build version 8C1002
  Android Studio: 2.2 AI-145.3537739

Packages: (wanted => installed)
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz => 0.54.2

Steps to Reproduce
1 - uncomment marginTop

Expected Behavior
- Text inside button should be centralized

Actual Behavior
- Text is moved on top of the button

Reproducible Demo
https://snack.expo.io/SJhhndX3G

This is happening after updating to React native 0.54.2

**Comment by nikolal** [comment] 2018-04-18 07:03
I created issue on expo board first. They pointed to several commits in React Native repo. 

https://github.com/expo/expo/issues/1667#issuecomment-382159045

**Comment by FlaviooLima** [comment] 2018-05-17 10:00
Only Happens with margin declared with a percentage.
#19164

**Comment by artdent** [comment] 2018-09-13 16:14
I just verified that this issue is still present in v0.57.0.

**Comment by brettdh** [comment] 2018-10-31 14:58
This is not just an Android issue; as the erroneously-closed #14722 indicates. I'm experiencing it as well on iOS.

**Comment by brettdh** [comment] 2018-10-31 15:18
This only appears to apply for percentage margins, not integer margins: 
https://snack.expo.io/Byj4wSvhQ

**Comment by artdent** [comment] 2019-03-19 14:57
I was still able to reproduce this on react-native 0.59.1.

**Comment by cpojer** [comment] 2019-05-09 13:49
Is there somebody who'd like to send a PR with a fix for this issue?

**Comment by brettdh** [comment] 2019-08-07 14:58
This is still an issue, as the Snack I linked above demonstrates.

**Comment by brettdh** [comment] 2019-08-07 15:03
Just tested it again with Expo SDK 32 and 34. Same (still broken) behavior in both (tested iOS).

Interestingly, the behavior is correct in expo-web.

**Comment by garronej** [comment] 2019-09-24 05:58
Still broken

**Comment by jpyne17** [comment] 2019-10-24 22:34
Still broken!

**Comment by FlaviooLima** [comment] 2019-10-29 10:56
I can't understand why this is still in the same state without a single higher up reckon this issue or give some info about it! 
:/

**Comment by garronej** [comment] 2020-01-29 01:06
Is it fixed now?

**Comment by FlaviooLima** [comment] 2020-02-04 17:30
@garronej  Version `0.61.5` and still happening

**Comment by garronej** [comment] 2020-05-06 09:58
@stale It hasn't been fixed, please leave it open.

**Comment by jpyne17** [comment] 2020-08-08 08:20
@stale very much not fixed 😘

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by artdent** [comment] 2020-12-27 05:05
I think this is fixed in react v0.62. You can verify online that the [snack](https://snack.expo.io/SJhhndX3G) in the original bug report is broken in Expo v37 (react-native 0.61) and fixed in Expo v38 (react-native 0.62). (You have to test in iOS or Android mode, not web mode.) Skimming the changelog, I think that https://github.com/facebook/react-native/commit/1d683faf1dc89e4950e7e1f5c5a67f9a7ca1ee24 was the fix.

**Comment by dulmandakh** [comment] 2021-01-17 12:33
Closing this because it's been fixed in 0.62 according to @artdent. Thanks

**Closed by dulmandakh** 2021-01-17 12:33 UTC
Labels: Bug, Platform: Android
