### ISSUE TITLE
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

### ISSUE THREAD

**Issue by EroticCode** [facebook/react-native#15702] opened 2017-08-30 01:59 UTC
React Native run-android build today and have issue , how can i solve it

**Comment by hramos** [comment] 2017-08-30 07:22
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-08-30 07:22 UTC
