### ISSUE TITLE
No apps connected. Sending "reload" to all React Native apps failed. Make sure your app is running in the simulator or on a phone connected via USB.

### ISSUE THREAD

**Issue by hakkikonu** [facebook/react-native#29396] opened 2020-07-16 11:13 UTC
On my Iphone, React Native Debugger does not work. 

With emulator there is no problem. But when I use my Iphone, If I click reload button in Chrome React Native Debugger it is not working and it throws below error.

I can see logs on my Chrome React native debugger but it is not stable.

_Warn in Metro bundler console:_

`No apps connected. Sending "reload" to all React Native apps failed. Make sure your app is running in the simulator or on a phone connected via USB.`

Real device is connected. My all devices use same Wireless network. 

## React Native version:
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 110.77 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_232 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 

## Steps To Reproduce

1. Connect IOS device (IOS 13.6) to device.
2. Validate real device connection on XCode
3. Start app on real device
4. Debugger and metro bundler starts
5. Press reload button in debugger and get above error in metro bundler console

**Comment by adarshponaka** [comment] 2020-07-16 18:12
Same issue for me

**Comment by Johbrun** [comment] 2020-07-16 18:32
Same issue for me too after migrate to RN 0.62 (from 0.59)
Using Windows and tested on Android

**Comment by hakkikonu** [comment] 2020-07-16 18:44
So can you provide your full solution step by step please?

**Comment by Johbrun** [comment] 2020-07-16 19:08
I don't have any solution about "No apps connected" problem, because I still have the same ...

I have just a solution about bundling (ci below), but I don't know if it is linked. Do you have the same problem ?

[https://github.com/facebook/react-native/issues/18692](https://github.com/facebook/react-native/issues/18692)

**Comment by hakkikonu** [comment] 2020-07-17 09:32
After 24 hours I solved this issue. Problem is somehow related to rn0.62 or its dependencies. I upgrade my project to 0.63.1 and it solved. 0.62 is really buggy version. I recommend 0.63.x

**Comment by Johbrun** [comment] 2020-07-17 12:17
Okay, I will try this, thanks !

**Comment by luvnish19** [comment] 2020-07-20 07:19
@hakkikonu Not working to me in Android. With command: react-native run-android, it is not attaching with npm. Please suggest any way out.

**Comment by hakkikonu** [comment] 2020-07-20 07:24
use 0.63.1

**Comment by luvnish19** [comment] 2020-07-20 07:34
> use 0.63.1

I am using 0.63.1 as you recommended but still it's not working. Any another way out?

**Comment by exotexot** [comment] 2020-07-20 09:09
I'm having a similar issue and i think it is related to the Metro Bundler. Out of nowhere my React Native project stopped working. But even worse: No matter how fat I went back in my git history, This also affects new react native projects. When I create a new project with react-native init, after installing dependencies and pods, i cannot get the example app to run with react-native run-ios.

**Comment by luvnish19** [comment] 2020-07-20 10:38
> use 0.63.1

I am already using as you recommended. After too many deeps I found the problem which is My project got corrupted after package name changes.

**Comment by exotexot** [comment] 2020-07-20 11:42
Did you upgrade xcode recently? I started experiencing this problem since the day I installed Xcode 11.6. Downgrading to 11.5 and reported if it solved my issue.

**Comment by exotexot** [comment] 2020-07-20 11:48
I also only have problems while deploying on actual devices. You can try to run the metro bundler from console while specifying a port
 react-native start --port 8085 --reset-cache

Then try to see if you can access metro bundler from the browser: localhost:8085. Here you should see metro bundler info. In theory I guess, you should also be able to access this address from your phone or tablet. (Sometimes replacing "localhost" with your actual ip address helps). Here is also my problem, that this address isnt accessible through my devices, even while being on the same network.

**Comment by exotexot** [comment] 2020-07-20 16:18
Downgrading to 11.5 wont change a thing for me. 

To anyone who also experinces this error: do you have also problems with freshly created projects using react-native init???

**Comment by Johbrun** [comment] 2020-07-20 17:32
Yes, in my case I migrated an app from 0.48 to 0.52. So, I created a new project, and copy/paste codebase. 
And yes, I have this problem since this new project.
I upgrade to 0.63 but still the same problem

**Comment by next-gen-2020** [comment] 2020-07-21 11:17
I m using RN version 0.63.1, but still getting the same error.

**Comment by imoby** [comment] 2020-07-22 05:07
For me I realized the issue was because my phone and laptop were not on the same network (one was on wifi one was on cellular). After putting phone on wifi it worked.

**Comment by DzTheRage** [comment] 2020-07-22 23:01
React Native is a real piece of work.

**Comment by WillRock19** [comment] 2020-07-27 23:11
I have the same problem.

And also, another: 

I've created a react application with the command **npx react-native init**. it worked well. I can deploy this app on an Android Emulator, but cannot do it on my device. The device is in developer mode and when I run the command **adb devices** it returns the device connected.

But, when I try to run the **npx react-native run-android** command, it responds that  **No Android device or emulator connected**.

**Comment by Johbrun** [comment] 2020-07-28 08:27
Ok I solved this issue (on Android Emulator). Please follow this steps **(only for Android)** : 

-  Open **MainApplication.java** and remove `import com.facebook.react.BuildConfig;`

- Reset metro bundler cache : `npx react-native start --reset-cache`

- Remove Android assets cache : `cd android && ./gradlew clean`

- Relaunch metro server : `npx react-native run-android`

And see the magic 🎉 

If you have a error like `Invariant Violation: Module AppRegistry is not a registered callabel module`, scroll on your terminal to see root cause.

**Comment by DzTheRage** [comment] 2020-07-28 18:06
I was able to resolve this on **iOS when running on a real device**. After bundle finishes, press the stop button in Xcode then open and close the app and it works fine.

**Comment by asor7007** [comment] 2020-08-04 06:36
![image](https://user-images.githubusercontent.com/57497414/89260658-ad8e9680-d667-11ea-8c20-07192d3b28a7.png)
If the app build mode is a `Release`, it will not be connected.
To switch build you should go to the `Product > Scheme > Edit Scheme` and select Debug for Build Configuration.

**Comment by sharpcodepro** [comment] 2020-08-17 18:23
The phone and the computer have to be on the same WiFi connection.

**Comment by Johbrun** [comment] 2020-08-17 18:37
Sometimes connect pc and phone on the same network is not enough :/

**Comment by jpodpro** [comment] 2020-08-17 23:17
i painstakingly updated from RN 0.59 to 0.62 and now i have this issue on iOS device. no shake, no metro-triggered dev menu or reload works. 

i would try upgrading to 0.63 but react-native-webview doesn't fully support it.

**Comment by jbromberg** [comment] 2020-08-26 16:00
I am having this issue with iOS. Using RN v0.63.2 and code v12.0 beta 5 with ios 14 beta on my device. I am unable to connect to the metro bundler and the app can only run on my device while it is running inside of xcode.

**Comment by viniciuspetrachin** [comment] 2020-08-27 18:16
Windows 10.
With me the problem was solved as follows.
I was using PowerShell before and the error started to appear out of nowhere.
Then I opened the Command Prompt (CMD) in administrator mode. I ran the npx react-native run-android and then opened the normal emulator and stopped giving this error.

**Comment by astronino** [comment] 2020-09-02 14:04
https://docs.microsoft.com/fr-fr/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7

if u r in windows change this setup works for me

**Comment by chrisglein** [comment] 2020-09-02 17:29
Sounds like some people were able to fix this by upgrading 0.63.x, others are reporting that didn't work, there's some workarounds suggested... but overall lots of people are hitting this and there's some confusion for sure. As people are able to unblock themselves definitely share so that others can benefit.

**Comment by tsvetan-ganev** [comment] 2020-09-04 13:19
I also had the same problem in Android only - the development build didn't have Developer Menu or connection to the Metro Bundler.

The answer from @Johbrun helped me resolve it - just remove `import com.facebook.react.BuildConfig;`. I have added that line because I thought the `BuildConfig` class wasn't imported. However, that's not the case and importing it from the `com.facebook.react` namespace actually caused harm:

```java
// com.facebook.react.BuildConfig;
public final class BuildConfig {
    public static final boolean DEBUG = false;
    public static final String LIBRARY_PACKAGE_NAME = "com.facebook.react";
    /** @deprecated */
    @Deprecated
    public static final String APPLICATION_ID = "com.facebook.react";
    public static final String BUILD_TYPE = "release";
    public static final String FLAVOR = "";
    public static final int VERSION_CODE = 1;
    public static final String VERSION_NAME = "1.0";
    public static final int EXOPACKAGE_FLAGS = 0;
    public static final boolean IS_INTERNAL_BUILD = false;

    public BuildConfig() {
    }
}
```

The global `BuildConfig` which is the correct one:
```java
public final class BuildConfig {
  public static final boolean DEBUG = Boolean.parseBoolean("true");
  public static final String APPLICATION_ID = "my_app_id";
  public static final String BUILD_TYPE = "debug";
  public static final String FLAVOR = "";
  public static final int VERSION_CODE = 22;
  public static final String VERSION_NAME = "2.2";
}
```

**Comment by safaiyeh** [comment] 2020-09-06 05:26
@tsvetan-ganev that seems like it should be included. Could you send a PR for that for someone to check out?

**Comment by csillaj** [comment] 2020-09-13 14:38
I had the same problem so I put the app in debug mode and saw this error
`java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libreactnativejni.so`
This answer helped [https://stackoverflow.com/questions/54888255/react-native-app-crashes-on-real-android-device/54889555#54889555](url)

**Comment by johnsaigle** [comment] 2020-09-28 00:17
I had this error when developing using `react-native-macos`. When I did `npm run start:macos` I got the error. Running `npx react-native run-macos` made it work again.

**Comment by hemith** [comment] 2020-10-07 14:22
shaking device (or CMD + D ...) -> Configure Bundler -> metro bundler machine IP Address on Local Network 

and also check this

iOS 14 > Settings > Privacy > Local Network

It works fine.

**Comment by woodcockjosh** [comment] 2020-10-10 18:38
I had to run `yarn web` instead of `yarn start`

**Comment by EduardoFLima** [comment] 2020-10-18 09:55
For me it was happening when using android emulator. Adding this to the android manifest did the trick:

android:usesCleartextTraffic="true"


reference: https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted

**Comment by tomlagier** [comment] 2020-10-26 18:23
For us, the issue was using a different configuration on ios. We created a `Local` configuration to connect to an emulated backend, this caused the live reload to stop working. It seems like it only works on `Debug` configuration.

**Comment by wpram45** [comment] 2020-10-27 17:25
Try this hakkı kardeş put your terminal command at below.
**`adb reverse tcp:8081 tcp:8081`**
Then just start server
**`npx react-native start --reset-cache`**

It worked for me

**Comment by developerdex2908** [comment] 2020-10-30 22:07
> Ok I solved this issue "No apps connected. " (on Android Emulator). Please follow this steps **(only for Android)** :
> 
> * Open **MainApplication.java** and remove `import com.facebook.react.BuildConfig;`
> * Reset metro bundler cache : `npx react-native start --reset-cache`
> * Remove Android assets cache : `cd android && ./gradlew clean`
> * Relaunch metro server : `npx react-native run-android`
> 
> And see the magic 🎉
> 
> If you have an error like `Invariant Violation: Module AppRegistry is not a registered callabel module`, scroll on your terminal to see the root cause.

I tried everything... I almost wanted to remove my code bit by bit to see which one is causing the issue. Luckily I didn't, it would've been a waste of time. Thank you so much!!!!!

**Comment by sislovesmedotcom** [comment] 2020-11-06 03:08
In my case, it works well on ios simulator and android but not on real ios devices. What worked for me in ios was.

- **npx react-native start --reset-cache --port 8081** in terminal
- Shake your ios device
- Configure Bundler
- Enter IP address from system preferences like the picture below
- Add 8081 on the next field and empty on last

<img width="321" alt="Screen Shot 2020-11-06 at 11 06 30 AM" src="https://user-images.githubusercontent.com/39583750/98321480-2236ef80-2020-11eb-98e1-e64bd100659f.png">

<img width="688" alt="Screen Shot 2020-11-06 at 10 56 52 AM" src="https://user-images.githubusercontent.com/39583750/98321448-10ede300-2020-11eb-9fe7-d1f8a5d322fa.png">

**Comment by abininmakes** [comment] 2020-11-07 06:49
> Ok I solved this issue "No apps connected. " (on Android Emulator). Please follow this steps **(only for Android)** :
> 
> * Open **MainApplication.java** and remove `import com.facebook.react.BuildConfig;`
> * Reset metro bundler cache : `npx react-native start --reset-cache`
> * Remove Android assets cache : `cd android && ./gradlew clean`
> * Relaunch metro server : `npx react-native run-android`
> 
> And see the magic 🎉
> 
> If you have an error like `Invariant Violation: Module AppRegistry is not a registered callabel module`, scroll on your terminal to see the root cause.

It Works for me

**Comment by sparcbr** [comment] 2020-11-16 23:48
I think that metro shoul be smart enough to open the port redirection through adb as the default connection depends on that

**Comment by utnhim** [comment] 2020-11-17 03:36
> Ok I solved this issue "No apps connected. " (on Android Emulator). Please follow this steps **(only for Android)** :
> 
> * Open **MainApplication.java** and remove `import com.facebook.react.BuildConfig;`
> * Reset metro bundler cache : `npx react-native start --reset-cache`
> * Remove Android assets cache : `cd android && ./gradlew clean`
> * Relaunch metro server : `npx react-native run-android`
> 
> And see the magic 🎉
> 
> If you have an error like `Invariant Violation: Module AppRegistry is not a registered callabel module`, scroll on your terminal to see the root cause.

Thanks you, i search Google in 3 days and you help me. Thanks you so much

**Comment by alejogo4** [comment] 2020-11-26 15:55
> El teléfono y la computadora deben estar en la misma conexión WiFi.

I have had the same problem in iOS with React native 0.62 and the solution was it

**Comment by dbarner1** [comment] 2020-12-10 05:48
Experienced this. My device was on a different network than machine running metro.  Don't be me! Run on the same network!

**Comment by nvt-it** [comment] 2020-12-11 01:25
> Ok I solved this issue "No apps connected. " (on Android Emulator). Please follow this steps **(only for Android)** :
> 
> * Open **MainApplication.java** and remove `import com.facebook.react.BuildConfig;`
> * Reset metro bundler cache : `npx react-native start --reset-cache`
> * Remove Android assets cache : `cd android && ./gradlew clean`
> * Relaunch metro server : `npx react-native run-android`
> 
> And see the magic 🎉
> 
> If you have an error like `Invariant Violation: Module AppRegistry is not a registered callabel module`, scroll on your terminal to see the root cause.

It's worked!

**Comment by rgomezp** [comment] 2020-12-15 22:14
> In my case, it works well on ios simulator and android but not on real ios devices. What worked for me in ios was.
> 
> * **npx react-native start --reset-cache --port 8081** in terminal
> * Shake your ios device
> * Configure Bundler
> * Enter IP address from system preferences like the picture below
> * Add 8081 on the next field and empty on last
> 
> <img alt="Screen Shot 2020-11-06 at 11 06 30 AM" width="321" src="https://user-images.githubusercontent.com/39583750/98321480-2236ef80-2020-11eb-98e1-e64bd100659f.png">
> 
> <img alt="Screen Shot 2020-11-06 at 10 56 52 AM" width="688" src="https://user-images.githubusercontent.com/39583750/98321448-10ede300-2020-11eb-9fe7-d1f8a5d322fa.png">

This one worked for me!

**Comment by AndresdoSantos** [comment] 2021-01-07 23:09
> Ok, resolvi esse problema "Nenhum aplicativo conectado." (No Android Emulator). Siga estas etapas **(apenas para Android)** :
> 
> * Abra **MainApplication.java** e remova`import com.facebook.react.BuildConfig;`
> * Redefinir o cache do bundler metro: `npx react-native start --reset-cache`
> * Remova o cache de ativos do Android: `cd android && ./gradlew clean`
> * Reiniciar servidor metro: `npx react-native run-android`
> 
> E veja a magia 🎉
> 
> Se você tiver um erro como `Invariant Violation: Module AppRegistry is not a registered callabel module`, role em seu terminal para ver a causa raiz.

Uoouu ... it worked for me.

**Comment by Itachi625** [comment] 2021-01-27 10:47
> Ok I solved this issue "No apps connected. " (on Android Emulator). Please follow this steps **(only for Android)** :
> 
> * Open **MainApplication.java** and remove `import com.facebook.react.BuildConfig;`
> * Reset metro bundler cache : `npx react-native start --reset-cache`
> * Remove Android assets cache : `cd android && ./gradlew clean`
> * Relaunch metro server : `npx react-native run-android`
> 
> And see the magic 🎉
> 
> If you have an error like `Invariant Violation: Module AppRegistry is not a registered callabel module`, scroll on your terminal to see the root cause.

My MainApplication.java file does not have - "import com.facebook.react.BuildConfig;", what to do?? :(

**Comment by MannySAD** [comment] 2021-02-04 21:48
> > Ok I solved this issue "No apps connected. " (on Android Emulator). Please follow this steps **(only for Android)** :
> > 
> > * Open **MainApplication.java** and remove `import com.facebook.react.BuildConfig;`
> > * Reset metro bundler cache : `npx react-native start --reset-cache`
> > * Remove Android assets cache : `cd android && ./gradlew clean`
> > * Relaunch metro server : `npx react-native run-android`
> > 
> > And see the magic 🎉
> > If you have an error like `Invariant Violation: Module AppRegistry is not a registered callabel module`, scroll on your terminal to see the root cause.
> 
> My MainApplication.java file does not have - "import com.facebook.react.BuildConfig;", what to do?? :(

Same :(

**Comment by sparcbr** [comment] 2021-02-05 17:37
If you're using USB connection, the most common case is that you don't have the port redirection running. So run:
```
adb reverse tcp:8081 tcp:8081
adb reverse tcp:8097 tcp:8097 # for flipper
```

**Comment by jxanders** [comment] 2021-02-10 00:57
Happens to me too. Worked fine on 0.62.2 and then when I upgraded to 0.63.4 I could not longer get it to work for iPhone. Works fine on android phone and iOS simulator, but not on the iPhone.
I've checked:
- The phone and computer are on the same network
- The scheme is on the Debug build configuration

While viewing the logs I noticed that the connection from the phone to the laptop was attempted but the connection was refused.

`2021-02-09 19:44:18.804771-0500 unit[1076:1041269] Task <5666-0E66-446F-A3F3-1404C54B5955>.<1> finished with error [-1001] Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x2817d4300 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <5666-0E66-446F-A3F3-1404C54B5955>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <5666-0E66-446F-A3F3-1404C54B5955>.<1>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=http://192.168.254.30:8081/status, NSErrorFailingURLKey=http://192.168.254.30:8081/status, _kCFStreamErrorDomainKey=4}
2021-02-09 19:44:18.834182-0500 unit[1076:1041011] [native] Running application main ({
    initialProps =     {
    };
    rootTag = 1;
})
2021-02-09 19:45:19.248767-0500 unit[1076:1041269] Task <48D57837-F00E-47EA-B4CF-6A28376E727>.<2> finished with error [-1001] Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x2817ed020 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <48D57837-F00E-47EA-B4CF-6A28376E727>.<2>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <48D57837-F00E-47EA-B4CF-6A28376E727>.<2>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=http://192.168.254.30:8081/status, NSErrorFailingURLKey=http://192.168.254.30:8081/status, _kCFStreamErrorDomainKey=4}
2021-02-09 19:45:19.334461-0500 unit[1076:1041270] [connection] nw_socket_handle_socket_event [C3.1:1] Socket SO_ERROR [61: Connection refused]
2021-02-09 19:45:19.335218-0500 unit[1076:1041270] [connection] nw_socket_handle_socket_event [C4.1:1] Socket SO_ERROR [61: Connection refused]
2021-02-09 19:45:19.337833-0500 unit[1076:1041270] [connection] nw_socket_handle_socket_event [C3.2:1] Socket SO_ERROR [61: Connection refused]`

**Comment by jxanders** [comment] 2021-02-10 01:46
Here's my steps to reproduce in a clean project, with a clean install of react-native-cli and react-native. I also cleared my Metro cache.

- Run `npx react-native init pleasework --version 0.63.4`
- Open the .xcworkspace
- Select your real device
- Hit run

Surprisingly, the first build seemed to initially working. After doing a clean build it stopped working. This is of course with the Debug build config and I've even tried some other results from 2018 like disabling the Xcode debugger but that hasn't helped.

**Comment by HermesE30** [comment] 2021-02-11 11:53
> Ok, resolvi esse problema "Nenhum aplicativo conectado." (No Android Emulator). Siga estas etapas **(apenas para Android)** :
> 
> * Abra **MainApplication.java** e remova`import com.facebook.react.BuildConfig;`
> * Redefinir o cache do bundler metro: `npx react-native start --reset-cache`
> * Remova o cache de ativos do Android: `cd android && ./gradlew clean`
> * Reiniciar servidor metro: `npx react-native run-android`
> 
> E veja a magia 
> 
> Se você tiver um erro como `Invariant Violation: Module AppRegistry is not a registered callabel module`, role em seu terminal para ver a causa raiz.

This worked for me! Thank you

**Comment by belmonj1** [comment] 2021-02-23 20:52
> > Ok I solved this issue "No apps connected. " (on Android Emulator). Please follow this steps **(only for Android)** :
> > 
> > * Open **MainApplication.java** and remove `import com.facebook.react.BuildConfig;`
> > * Reset metro bundler cache : `npx react-native start --reset-cache`
> > * Remove Android assets cache : `cd android && ./gradlew clean`
> > * Relaunch metro server : `npx react-native run-android`
> > 
> > And see the magic 🎉
> > If you have an error like `Invariant Violation: Module AppRegistry is not a registered callabel module`, scroll on your terminal to see the root cause.
> 
> My MainApplication.java file does not have - "import com.facebook.react.BuildConfig;", what to do?? :(

Same for me...

**Comment by leohuff** [comment] 2021-02-26 06:28
> > > Ok I solved this issue "No apps connected. " (on Android Emulator). Please follow this steps **(only for Android)** :
> > > 
> > > * Open **MainApplication.java** and remove `import com.facebook.react.BuildConfig;`
> > > * Reset metro bundler cache : `npx react-native start --reset-cache`
> > > * Remove Android assets cache : `cd android && ./gradlew clean`
> > > * Relaunch metro server : `npx react-native run-android`
> > > 
> > > And see the magic tada
> > > If you have an error like `Invariant Violation: Module AppRegistry is not a registered callabel module`, scroll on your terminal to see the root cause.
> > 
> > 
> > My MainApplication.java file does not have - "import com.facebook.react.BuildConfig;", what to do?? :(
> 
> Same for me...

same...

**Comment by akhilsanker** [comment] 2021-03-11 09:07
Hi,
Same issue here.
Both mac and iPhone connected to same network but on reloading metro blunder a warning is show no connected apps.
Xcode 12.4
Mac OS : 10.15.7
iPhone: 14.4.1

Any solution?

**Comment by t29mato** [comment] 2021-03-20 20:53
Hi, I got the same issue, but the situation is a little different.

I have schemes Debug (default scheme) and copy-of-Debug.
Debug scheme works, but the copy-of-Debug has the error message.

It seems the configuration file is the same as Debug.

**Comment by moGeekHex** [comment] 2021-03-23 23:17
hello everyone .... I had the same problem

When i removed  _import com.facebook.react.BuildConfig_ from _MainApplication.java_ and delete cache 

Everything was fine

**Comment by Rafael-Pessoni** [comment] 2021-04-23 18:56
> > > > Ok I solved this issue "No apps connected. " (on Android Emulator). Please follow this steps **(only for Android)** :
> > > > 
> > > > * Open **MainApplication.java** and remove `import com.facebook.react.BuildConfig;`
> > > > * Reset metro bundler cache : `npx react-native start --reset-cache`
> > > > * Remove Android assets cache : `cd android && ./gradlew clean`
> > > > * Relaunch metro server : `npx react-native run-android`
> > > > 
> > > > And see the magic tada
> > > > If you have an error like `Invariant Violation: Module AppRegistry is not a registered callabel module`, scroll on your terminal to see the root cause.
> > > 
> > > 
> > > My MainApplication.java file does not have - "import com.facebook.react.BuildConfig;", what to do?? :(
> > 
> > 
> > Same for me...
> 
> same...

same..

**Comment by dikrandikranian** [comment] 2021-05-02 18:39
> > > > > Ok I solved this issue "No apps connected. " (on Android Emulator). Please follow this steps **(only for Android)** :
> > > > > 
> > > > > * Open **MainApplication.java** and remove `import com.facebook.react.BuildConfig;`
> > > > > * Reset metro bundler cache : `npx react-native start --reset-cache`
> > > > > * Remove Android assets cache : `cd android && ./gradlew clean`
> > > > > * Relaunch metro server : `npx react-native run-android`
> > > > > 
> > > > > And see the magic tada
> > > > > If you have an error like `Invariant Violation: Module AppRegistry is not a registered callabel module`, scroll on your terminal to see the root cause.
> > > > 
> > > > 
> > > > My MainApplication.java file does not have - "import com.facebook.react.BuildConfig;", what to do?? :(
> > > 
> > > 
> > > Same for me...
> > 
> > 
> > same...
> 
> same..

same... has anyone found a solution for this? (also using an android emulator)

**Comment by Jon-Rez** [comment] 2021-05-07 02:21
Adding android:usesCleartextTraffic="true" in the Android Manifest File solves it for me. Seems in newer versions of RN or some of its packages this is disabled.
`<application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:usesCleartextTraffic="true"
      ...
/>`

**Comment by gnabloviseo** [comment] 2021-05-07 07:49
> Hi, I got the same issue, but the situation is a little different.
> 
> I have configurations Debug (default scheme) and copy-of-Debug.
> Debug configuration works, but the copy-of-Debug has the error message.
> 
> It seems the configuration file causes it, but I don't find the difference.

In my case I created new targets for our app's different environments and renamed Debug to SIT.

I tried duplicating SIT and renaming it to Debug. App runs both on simulator and Xcode but bundler can't detect the device and thus auto-reload is not working.

**Comment by sametyabalak** [comment] 2021-05-20 14:11
> I was able to resolve this on **iOS when running on a real device**. After bundle finishes, press the stop button in Xcode then open and close the app and it works fine.

It worked for me. Thanks al lot !! But its so weird :d

**Comment by Rafael-Pessoni** [comment] 2021-05-24 21:52
Here is what worked for me:

![image](https://user-images.githubusercontent.com/11237682/119411645-1f9c9e80-bcc1-11eb-8dd6-b04d30014092.png)

http://hiddenlinux.blogspot.com/2016/01/how-to-fix-adb-device-offline.html

**Comment by LogLiangTang** [comment] 2021-05-29 11:02
> hello everyone .... I had the same problem in app react-native version 62.0
> 
> When i removed _import com.facebook.react.BuildConfig_ from _MainApplication.java_ and delete cache
> 
> Everything became normal

How do you fix this? Or have any solution to create multiple environment?

**Comment by SmilerKai** [comment] 2021-06-03 07:13
> > > > > > Ok I solved this issue "No apps connected. " (on Android Emulator). Please follow this steps **(only for Android)** :
> > > > > > 
> > > > > > * Open **MainApplication.java** and remove `import com.facebook.react.BuildConfig;`
> > > > > > * Reset metro bundler cache : `npx react-native start --reset-cache`
> > > > > > * Remove Android assets cache : `cd android && ./gradlew clean`
> > > > > > * Relaunch metro server : `npx react-native run-android`
> > > > > > 
> > > > > > And see the magic tada
> > > > > > If you have an error like `Invariant Violation: Module AppRegistry is not a registered callabel module`, scroll on your terminal to see the root cause.
> > > > > 
> > > > > 
> > > > > My MainApplication.java file does not have - "import com.facebook.react.BuildConfig;", what to do?? :(
> > > > 
> > > > 
> > > > Same for me...
> > > 
> > > 
> > > same...
> > 
> > 
> > same..
> 
> same... has anyone found a solution for this? (also using an android emulator)

same for me :<

**Comment by john1jan** [comment] 2021-06-05 15:41
> Adding android:usesCleartextTraffic="true" in the Android Manifest File solves it for me. Seems in newer versions of RN or some of its packages this is disabled.
> `<application android:name=".MainApplication" android:label="@string/app_name" android:icon="@mipmap/ic_launcher" android:usesCleartextTraffic="true" ... />`

This worked for me

**Comment by brunobrante** [comment] 2021-06-09 05:54
> > > > > > > Ok I solved this issue "No apps connected. " (on Android Emulator). Please follow this steps **(only for Android)** :
> > > > > > > 
> > > > > > > * Open **MainApplication.java** and remove `import com.facebook.react.BuildConfig;`
> > > > > > > * Reset metro bundler cache : `npx react-native start --reset-cache`
> > > > > > > * Remove Android assets cache : `cd android && ./gradlew clean`
> > > > > > > * Relaunch metro server : `npx react-native run-android`
> > > > > > > 
> > > > > > > And see the magic tada
> > > > > > > If you have an error like `Invariant Violation: Module AppRegistry is not a registered callabel module`, scroll on your terminal to see the root cause.
> > > > > > 
> > > > > > 
> > > > > > My MainApplication.java file does not have - "import com.facebook.react.BuildConfig;", what to do?? :(
> > > > > 
> > > > > 
> > > > > Same for me...
> > > > 
> > > > 
> > > > same...
> > > 
> > > 
> > > same..
> > 
> > 
> > same... has anyone found a solution for this? (also using an android emulator)
> 
> same for me :<

Same !

**Comment by linus-komnick** [comment] 2021-07-03 14:13
What did the trick for me was the following:
In Xcode go to Debug/Detach from YourAppName
Then reattach it by going to Debug/Attach to Process, select your app from the list (usually the first entry at the top).

**Comment by sukhsfu** [comment] 2021-07-06 05:05
in gradle-wrapper.properties change to distributionUrl=https\://services.gradle.org/distributions/gradle-6.3-all.zip

from 5.x

**Comment by maitham** [comment] 2021-07-08 16:28
Make sure you're not on a vpn 😅

**Comment by sujanvaland** [comment] 2021-08-04 11:04
> Ok I solved this issue "No apps connected. " (on Android Emulator). Please follow this steps **(only for Android)** :
> 
> * Open **MainApplication.java** and remove `import com.facebook.react.BuildConfig;`
> * Reset metro bundler cache : `npx react-native start --reset-cache`
> * Remove Android assets cache : `cd android && ./gradlew clean`
> * Relaunch metro server : `npx react-native run-android`
> 
> And see the magic 🎉
> 
> If you have an error like `Invariant Violation: Module AppRegistry is not a registered callabel module`, scroll on your terminal to see the root cause.

This save my job...thankyou very much

**Comment by safaiyeh** [comment] 2021-08-04 15:49
Thanks everyone for providing suggestions & work arounds. Closing as there isn't an actionable pull request for this.

**Closed by safaiyeh** 2021-08-04 15:49 UTC
Labels: Needs: React Native Team Attention

**Comment by jerry-inc** [comment] 2021-12-05 11:34
> I was able to resolve this on **iOS when running on a real device**. After bundle finishes, press the stop button in Xcode then open and close the app and it works fine.

This solution worked for me

**Comment by my-name-is-nheo** [comment] 2021-12-10 03:55
building through xcode, started metro, but will not cannot to metro. 
- device and laptop are connected to the same wifi
- Tried the option of stopping as the soon as the bundle finished but never connected. 
- Made sure the build configuration was set to "DEBUG" instead of RELEASE.
- clear cache, reinstalled pods, watchman watch-del-all, rm -rf /temp/metro-* 
cannot believe this is still an issue. Is there a proper fix for this?

**Comment by linus-komnick** [comment] 2021-12-10 07:56
Try this:

1. Open the terminal. 
2. `cd` into the root directory of your app.
3. run `npm start -- --reset-cache`

**Comment by cynical1031** [comment] 2022-06-08 01:24
i solved this issue too
my issue is network problem
and I'm reset the network profile

**Comment by chzappsinc** [comment] 2022-06-08 05:55
If you have this code in androidmanifest.xml then remove
`android:dataExtractionRules="@xml/data_extraction_rules"`

This was auto-gen by the android studio while you clicked ALT+ENTER on the warning (<application.....)

**Comment by olegderecha** [comment] 2022-07-30 18:23
> The phone and the computer have to be on the same WiFi connection.

You will not believe... I spent 2 days and could not understand why iPhone didn't want to connect to JS bundler (Android worked).

**Comment by chzappsinc** [comment] 2022-07-30 18:25
Try to remove any network_config.xml in debug mode
Android

**Comment by DaveLomber** [comment] 2022-08-03 12:48
Had a similar issue but [React Native: Emulator stuck on "loading from localhost:8081.."](https://stackoverflow.com/questions/50226232/react-native-emulator-stuck-on-loading-from-localhost8081)

solution is here https://stackoverflow.com/a/72322750/574475

fixed this by uninstalling watchman. Could be an issue with installing it on M1 or something but it worked immediately after.

brew uninstall watchman
