### ISSUE TITLE
Text truncation too much on Android, comparing to on iOS

### ISSUE THREAD

**Issue by marty-wang** [facebook/react-native#3455] opened 2015-10-16 05:38 UTC
it appears that Text component truncates too much on Android than on iOS. Please reference the screenshots below. 

Here is my code

```
<View style={styles.secondColumn}>
    <Text style={styles.firstRow} numberOfLines={1}>My awesome and beautiful app</Text>
</View>

const styles = StyleSheet.create({
    secondColumn: {
        flex: 1,
        justifyContent: "center",
        marginRight: 10,
    },
    firstRow: {
        fontSize: 18,
    },
});
```
on Android
![screen shot 2015-10-15 at 10 27 49 pm](https://cloud.githubusercontent.com/assets/1132214/10534381/ac02b9d8-738c-11e5-9e2e-6b22b04e8d02.png)
on iOS
![screen shot 2015-10-15 at 10 30 12 pm](https://cloud.githubusercontent.com/assets/1132214/10534385/b1af94e6-738c-11e5-9724-7fead7385e50.png)

**Comment by sospartan** [comment] 2015-10-16 10:16
what's your device?
I think different resolution and PPI may cause this result.

**Comment by marty-wang** [comment] 2015-10-16 17:53
@sospartan I tested it on both my MotoX (2nd gen) and android simulator(not remember which profile, though). The result appeared the same.

I am not sure if it is result of different resolution and PPI. But regardless, the framework should take care of the discrepancy, since the measurement in RN is unit-less.

**Comment by ide** [comment] 2015-10-16 18:02
RN uses points/virtual pixels. Same as iOS and CSS. It should render differently on devices with bigger screens. There may be a bug with truncation (or maybe not) but it's not a goal of RN to look pixel perfect across devices that are different sizes.

**Comment by sospartan** [comment] 2015-10-16 18:08
@marty-wang  u may try PixelRatio http://facebook.github.io/react-native/docs/pixelratio.html#content
as @ide said RN do have unit

**Comment by marty-wang** [comment] 2015-10-16 19:37
I can understand the rendering difference on devices with different resolutions and PPI. but I would still argue this is a truncation bug, because regardless of resolutions and PPI, Text component should accommodate as many as letters until it cannot. On Android, clearly there is still more room.

**Comment by ide** [comment] 2015-10-16 19:56
@kmagiera could you assign this to the person who is most familiar with ReactTextView? The issue is that Android will truncate entire words, and iOS will truncate only part of a word.

Original string: "My awesome and beautiful app"
Android: "My awesome and..."
iOS: "My awesome and beauti..."

It looks like this is part of Android's behavior though: https://stackoverflow.com/questions/1698881/cant-get-ellipsis-to-work-on-android

**Comment by mkonicek** [comment] 2016-04-10 16:59
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/text-truncation-too-much-on-android-comparing-to-on-ios

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Closed by mkonicek** 2016-04-10 16:59 UTC
Labels: Android, Help Wanted, Icebox

**Comment by mkonicek** [comment] 2016-04-10 17:02
A pull request to fix this would be awesome! We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
