### ISSUE TITLE
Flavors & App Bundle  missing index.android.bundle

### ISSUE THREAD

**Issue by lorenzoangelini** [facebook/react-native#29398] opened 2020-07-16 13:54 UTC
## Description 
We use the flavors into our apps to use different version. We have dev, test and prod. When we have upgraded to 0.63, to classpath("com.android.tools.build:gradle:3.5.3") and distributionUrl=https\://services.gradle.org/distributions/gradle-6.2-all.zip, we cannot use the appbundle.
when we run ./gradlew bundleDevRelease -> we cannot find into the app-dev-release.aab the index.android.bundle. This cause a crash when open the app. 
If we run this command :  ./gradlew bundleRelease -> it build all variants 
app-dev-release.aab -> missing
app-test-release.aab -> index.android.bundle present
app-prod-release.aab -> index.android.bundle present

it seems that the first time not set the index.android.bundle into assets

## React Native version:
System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 382.96 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 11.10.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 27, 28, 29
      Build Tools: 26.0.2, 27.0.3, 28.0.3, 29.0.2
      System Images: android-19 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-27 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_201 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.0 => 0.63.0 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
1.Create a new project: npx react-native init AppName  --template react-native-template-typescript
2. Add to gradle.build :
 productFlavors {
            prod {
            }
            dev {
                applicationId 'com.appname.dev'
                resValue "string", "build_config_package", "com.appname"
            }
            test {
                applicationId 'com.appname.test'
                resValue "string", "build_config_package", "com.appname"
            }
        }
3. run into android folder : ./gradlew clean && ./gradlew bundleDevRelease

## Expected Results
Obtain an .aab file into android/build/outputs/bundle/devRelease. when i open the .aab i expect to find the folder base and into the base the folder assets that contain the index.android.bundle.

**Comment by thanakij** [comment] 2020-08-24 04:09
One more clue here, I find that we have to run `./gradlew bundleRelease` twice as "index.android.bundle" will be missing in the first generated AAB. After running the same command again, this time "index.android.bundle" will be included in the final AAB.

**Comment by safaiyeh** [comment] 2020-08-24 04:25
Thanks for the issue @lorenzoangelini!

> One more clue here, I find that we have to run `./gradlew bundleRelease` twice as "index.android.bundle" will be missing in the first generated AAB. After running the same command again, this time "index.android.bundle" will be included in the final AAB.
Hmm are you saying after the second run of `./gradlew bundleRelease` it is generated correctly?

**Comment by thanakij** [comment] 2020-08-24 05:59
In a sense, yes. Below is what I have in my release script for Android side. It works well so far.

```
./gradlew clean
./gradlew bundleRelease; ./gradlew bundleRelease # Fix bug, index.android.bundle is not included in AAB
fastlane android upload
```

Otherwise, "index.android.bundle" won't be included in the generated AAB. I saw that "index.android.bundle" generation step is invoked but it is simply not included in AAB.

**Comment by lorenzoangelini** [comment] 2020-08-24 07:26
@safaiyeh @thanakij  yes it seems that the first time the folder assets with "index.android.bundle" is not present. 
Run twice the ./gradlew bundleRelease for me is not a just solution, because the build time is x2. 
In my case if i run bundleRelease i get three apps, dev,test and production. Where in dev, it crash when launch the app, because is missing the "index.android.bundle". 
The goal is launch for example ./gradlew bundleRelease and obtain the an aab that works, like the previous version of the gradle. I think that is a problem of cli. 
I use a monorepo.

**Comment by thanakij** [comment] 2020-08-24 07:32
I would like to provide my setting below:

```
react-native: 0.62.2
Gradle: 6.4.1
Gradle Plugin: 4.0.1
```

```
proguard: enabled
```

Hopefully, this would help maintainers fix the issue.

**Comment by lorenzoangelini** [comment] 2020-08-24 08:08
With this i have the issue:
react-native: 0.63.2
com.android.tools.build:gradle:3.5.3
https://services.gradle.org/distributions/gradle-6.2-all.zip

With this version the issue is not present
react-native: 0.63.2
com.android.tools.build:gradle:3.4.2
https://services.gradle.org/distributions/gradle-5.5-all.zip

**Comment by patrickkempff** [comment] 2020-08-26 19:11
I have a build with the same problem. The bundle is missing but the images are copied correctly it seems. 
Can anyone confirm their images are also present in the drawable folders?

**Comment by caseyli** [comment] 2020-09-02 20:01
I can confirm that running a double-build (ie. `./gradlew bundleRelease` twice) solves the issue. Not obviously a good long term solution, but definitely a hint to what's going on.

**Comment by alessioemireni** [comment] 2020-09-07 12:56
@thanakij with the same gradle configuration and with

`def enableProguardInReleaseBuilds = false`

the index.android.js is correctly injected in the aab archive without the need to run a double-build.

I haven't reproduce the same behaviour with a new react-native project.

**I think that the main problem is when there are multiple dex files** as in my project.

**Comment by tomoima525** [comment] 2020-10-13 22:58
The same issue happened to me when `com.android.tools.build:gradle:` was updated to 3.5.3 => 4.1.0 and 
https\://services.gradle.org/distributions/gradle to 5.5 => 6.5

**Comment by AndrewMorsillo** [comment] 2020-10-13 23:56
I'm running into this as well. In my case I'm attempting to `assembleRelease` instead of `bundleRelease`.

Everything is correct in the APK (all assets present) except it's missing the bundle! The bundle gets generated without issue, it's sitting in the correct directory, it just never gets added to the APK for unknown reasons. I've been tearing my hair out all day trying to figure out how/why this is happening.

Unfortunately running `assembleRelease` twice does not solve the problem.

It's definitely caused by the upgrade to android gradle plugin 4.1. Reverting to 3.6.4 fixes the issue however I need to use 4.1 for other reasons.

@safaiyeh Did you ever get to take a look at this? I think it can be reproduced on any app with multidex by upgrading gradle to 6.5+ and android gradle plugin to 4.1.0+. Do a clean and then `assembleRelease` and the APK will contain everything except the app bundle which remains in the generated outputs.

**Comment by tomoima525** [comment] 2020-10-14 05:11
I have a reproducible project here => https://github.com/tomoima525/android_build_test_rn

**Comment by dulmandakh** [comment] 2020-10-14 05:12
@tomoima525 thanks

**Comment by tomoima525** [comment] 2020-10-14 16:55
> I'm running into this as well. In my case I'm attempting to `assembleRelease` instead of `bundleRelease`.
> 
> Everything is correct in the APK (all assets present) except it's missing the bundle! The bundle gets generated without issue, it's sitting in the correct directory, it just never gets added to the APK for unknown reasons. I've been tearing my hair out all day trying to figure out how/why this is happening.
> 
> Unfortunately running `assembleRelease` twice does not solve the problem.
> 
> It's definitely caused by the upgrade to android gradle plugin 4.1. Reverting to 3.6.4 fixes the issue however I need to use 4.1 for other reasons.
> 
> @safaiyeh Did you ever get to take a look at this? I think it can be reproduced on any app with multidex by upgrading gradle to 6.5+ and android gradle plugin to 4.1.0+. Do a clean and then `assembleRelease` and the APK will contain everything except the app bundle which remains in the generated outputs.

Are you running `clean` before running `assembleRelease` the second time? If you run `clean` then the asset bundle file gets removed so it will not be included in the apk/aab file

**Comment by AndrewMorsillo** [comment] 2020-10-14 17:23
@tomoima525 @dulmandakh I found a workaround. It seems to be a gradle task ordering issue. It appears that assets get merged before the bundle gets copied to the intermediate output directory. Adding the following to `android/app/build.gradle` forces the bundle copy task to happen before merging assets.

```
//Fix for bundle not getting included in APK or AAB with android gradle plugin 4+
//Seems like there's a task ordering issue and the assets get computed before the bundle is copied
//This forces the copy task to run before merge resources
project.afterEvaluate {
        tasks.findAll { task ->
            task.name.startsWith('merge') && task.name.endsWith('Resources')
        }.each { t -> t.dependsOn "copyReleaseBundledJs" }
}
```

I have little knowledge of gradle so this isn't a great workaround, it doesn't account for different build variants etc but at least it works for basic `:app:assembleRelease`. I guess gradle or android plugin behavior changed at some point that causes this task ordering issue to crop up. I don't know enough about gradle to track down the actual source but hopefully this gives more knowledgeable people a good clue to go on =)

**Comment by tomoima525** [comment] 2020-10-14 18:57
@AndrewMorsillo Amazing, thank you for your input! Your idea does make sense and solves the issue. I dug into `react.gradle` and just gave a patch. The issue seems resolved by testing it on my reproducible repository.

**Comment by alessioemireni** [comment] 2020-10-15 10:18
@tomoima525 @AndrewMorsillo  In my case with Proguard enable doesn't work.

**Comment by tomoima525** [comment] 2020-10-16 18:51
@alessioemireni interesting. I'll check with my reproducible repository https://github.com/tomoima525/android_build_test_rn in my spare time( I turned off proguard in that project because `assembleRelease` failed with OOM). Can you also check the behavior with the fix I made in #30177 ?

**Comment by alessioemireni** [comment] 2020-10-16 19:54
@tomoima525 yes, I have applied a patch with your fix, but the result is the same.

react-native: 0.62.2
gradle-tool: 6.0.1
gradle-plugin: 3.6.4

I have also increased the gradle plugin version to 4.1+ but the bundle is missing in aab.

**Comment by tomoima525** [comment] 2020-10-18 07:06
@alessioemireni your case seems something different. This is reproducible when android gradle plugin is 4.1 and gradle is 6.5.

The issue does not happen with android gradle plugin 3.5.3/ gradle 6.2 so you might want to change to that version for now.

**Comment by tomoima525** [comment] 2020-10-18 07:09
@dulmandakh 

I have the reproducible case and fixed case with the fix I made in https://github.com/facebook/react-native/pull/30177.
Do you mind reviewing & checking it?

Repository: https://github.com/tomoima525/android_build_test_rn

## Reproducible case

To reproduce the issue, run the command below

```
$ cd android
$ ./gradlew clean :app:assembleRelease // or ./gradlew clean :app:releaseBundle
```

app-release.apk will be generated but it does not have index.android.bundle build

## Fixed case

I added the fix in https://github.com/facebook/react-native/pull/30177 . Running the command below will apply the patch to `react.gradle` and you can see the issue is resolved

```
$ yarn add_patch
$ cd android
$ ./gradlew clean :app:assembleRelease // or ./gradlew clean :app:releaseBundle
```

`index.android.bundle` is generated under `assets`

<img width="1016" alt="Screen Shot 2020-10-17 at 11 28 40 PM" src="https://user-images.githubusercontent.com/6277118/96360890-f76b1280-10d5-11eb-8d00-31fd10cdddf2.png">


(The script is tested on Mac. If the copying does not work on Linux, try directly copying the `react-patch.gradle` to `node_modules/react-native/react.gradle`)

**Closed** 2020-10-26 23:06 UTC
Labels: Needs: Attention, Platform: Android, 📦Bundler

**Comment by plowman** [comment] 2020-11-09 23:44
Huge thanks to @tomoima525 and @AndrewMorsillo for all of your work finding a solution!

I was having a nearly identical issue where doing `./gradlew clean assembleProductionRelease` would result in this error: `java.lang.RuntimeException: Unable to load script. Make sure you're either running a Metro server (run 'react-native start') or that your bundle 'index.android.bundle' is packaged correctly for release.` but ONLY when you did a clean. Running the same command again as `./gradlew assembleProductionRelease` would work.

For people who don't want to manually patch the `node_modules/react-native/react.gradle` until React Native does the next release, I've hacked together a solution (based on the work of @tomoima525 and @AndrewMorsillo) that you can drop into your `app/build.gradle` at the top level:
```gradle
// This forces the copy task to run before merge resources. This should be removable starting with RN 0.63.4.
project.afterEvaluate {
  def isAndroidLibrary = plugins.hasPlugin("com.android.library")
  def variants = isAndroidLibrary ? android.libraryVariants : android.applicationVariants
  variants.all { def variant ->
    def targetName = variant.name.capitalize()
    def mergeResourcesTask = tasks.findByName("merge${targetName}Resources")
    def assetsCopyTask = tasks.findByName("copy${targetName}BundledJs")
    mergeResourcesTask.dependsOn(assetsCopyTask)
    logger.warn("Making task ${mergeResourcesTask} depend on ${assetsCopyTask}")
  }
}
```

**Comment by nilavassg** [comment] 2020-11-17 16:36
Sorry to comment on this issue again. But the patch by @plowman works only for assemble builds not but bundling aab unfortunately.

**Comment by FelipeLimaDeSouza** [comment] 2020-11-17 22:39
> Huge thanks to @tomoima525 and @AndrewMorsillo for all of your work finding a solution!
> 
> I was having a nearly identical issue where doing `./gradlew clean assembleProductionRelease` would result in this error: `java.lang.RuntimeException: Unable to load script. Make sure you're either running a Metro server (run 'react-native start') or that your bundle 'index.android.bundle' is packaged correctly for release.` but ONLY when you did a clean. Running the same command again as `./gradlew assembleProductionRelease` would work.
> 
> For people who don't want to manually patch the `node_modules/react-native/react.gradle` until React Native does the next release, I've hacked together a solution (based on the work of @tomoima525 and @AndrewMorsillo) that you can drop into your `app/build.gradle` at the top level:
> 
> ```groovy-gradle
> // This forces the copy task to run before merge resources. This should be removable starting with RN 0.63.4.
> project.afterEvaluate {
>   def isAndroidLibrary = plugins.hasPlugin("com.android.library")
>   def variants = isAndroidLibrary ? android.libraryVariants : android.applicationVariants
>   variants.all { def variant ->
>     def targetName = variant.name.capitalize()
>     def mergeResourcesTask = tasks.findByName("merge${targetName}Resources")
>     def assetsCopyTask = tasks.findByName("copy${targetName}BundledJs")
>     mergeResourcesTask.dependsOn(assetsCopyTask)
>     logger.warn("Making task ${mergeResourcesTask} depend on ${assetsCopyTask}")
>   }
> }
> ```

In my project assetsCopyTask is null

**Comment by plowman** [comment] 2020-11-18 21:34
> Sorry to comment on this issue again. But the patch by @plowman works only for assemble builds not but bundling aab unfortunately.

@nilavassg what command are you running and what error are you seeing?

> In my project assetsCopyTask is null

@FelipeLimaDeSouza you can add a line so that `mergeResourcesTask.dependsOn(assetsCopyTask)` is only called if both mergeResourcesTask and assetsCopyTask are not null.

**Comment by FelipeLimaDeSouza** [comment] 2020-11-18 21:48
> > Sorry to comment on this issue again. But the patch by @plowman works only for assemble builds not but bundling aab unfortunately.
> 
> @nilavassg what command are you running and what error are you seeing?
> 
> > In my project assetsCopyTask is null
> 
> @FelipeLimaDeSouza you can add a line so that `mergeResourcesTask.dependsOn(assetsCopyTask)` is only called if both mergeResourcesTask and assetsCopyTask are not null.

I did this but it comes null in all commands.

**Comment by plowman** [comment] 2020-11-18 22:12
> I did this but it comes null in all commands.

@FelipeLimaDeSouza I see. I'm not an expert at any of this. My only guess is that `tasks.findByName("copy${targetName}BundledJs")` and `tasks.findByName("merge${targetName}Resources")` can't find the proper tasks in your environment. Perhaps because the `targetName` in these cases has different capitalization than what we're expecting? Idk.

If you do this you can find the steps which should be candidates:
```
# Starting at your root project directory
cd ./android
./gradlew tasks --all | grep -E "^app:merge.+Resources"
# For comparison, here is my output:
# app:mergeInternalDebugAndroidTestResources
# app:mergeInternalDebugResources
# app:mergeInternalReleaseResources
# app:mergeProductionDebugAndroidTestResources
# app:mergeProductionDebugResources
# app:mergeProductionReleaseResources

./gradlew tasks --all | grep -E "^app:copy.+BundledJs"
# For comparison, here is my output:
# app:copyInternalDebugBundledJs - copy bundled JS into InternalDebug.
# app:copyInternalReleaseBundledJs - copy bundled JS into InternalRelease.
# app:copyProductionDebugBundledJs - copy bundled JS into ProductionDebug.
# app:copyProductionReleaseBundledJs - copy bundled JS into ProductionRelease.
```

**Comment by FelipeLimaDeSouza** [comment] 2020-11-19 00:01
> > I did this but it comes null in all commands.
> 
> @FelipeLimaDeSouza I see. I'm not an expert at any of this. My only guess is that `tasks.findByName("copy${targetName}BundledJs")` and `tasks.findByName("merge${targetName}Resources")` can't find the proper tasks in your environment. Perhaps because the `targetName` in these cases has different capitalization than what we're expecting? Idk.
> 
> If you do this you can find the steps which should be candidates:
> 
> ```
> # Starting at your root project directory
> cd ./android
> ./gradlew tasks --all | grep -E "^app:merge.+Resources"
> # For comparison, here is my output:
> # app:mergeInternalDebugAndroidTestResources
> # app:mergeInternalDebugResources
> # app:mergeInternalReleaseResources
> # app:mergeProductionDebugAndroidTestResources
> # app:mergeProductionDebugResources
> # app:mergeProductionReleaseResources
> 
> ./gradlew tasks --all | grep -E "^app:copy.+BundledJs"
> # For comparison, here is my output:
> # app:copyInternalDebugBundledJs - copy bundled JS into InternalDebug.
> # app:copyInternalReleaseBundledJs - copy bundled JS into InternalRelease.
> # app:copyProductionDebugBundledJs - copy bundled JS into ProductionDebug.
> # app:copyProductionReleaseBundledJs - copy bundled JS into ProductionRelease.
> ```

Even with the task in the task list, it returns null.
I had to run the "bunbleRelease" command twice to work.

**Comment by thanakij** [comment] 2020-11-19 14:36
> Sorry to comment on this issue again. But the patch by @plowman works only for assemble builds not but bundling aab unfortunately.

Me too, the solution from @tomoima525 only solves some part of the problem. It is still not working in case of AAB.

I have gone through _react.gradle_ file and investigated the output when running **bundleRelease**. The remaining issue is because the task **copyReleaseBundleJs** is executed before **bundleReleaseJsAndAssets**. In short, the copy task is executed before the actual JS generation task.

Below line will make it works with "bundleRelease" (in addition to "assembleRelease"):

`currentAssetsCopyTask.dependsOn(currentBundleTask)`

**Comment by nilavassg** [comment] 2020-11-19 18:34
> > > Sorry to comment on this issue again. But the patch by @plowman works only for assemble builds not but bundling aab unfortunately.
> > 
> > 
> > @nilavassg what command are you running and what error are you seeing?

`./gradlew bundleProdRelease`

Also confirmed the same by @thanakij

**Comment by thanakij** [comment] 2020-11-24 00:48
Below is what I have:

![change](https://i.imgur.com/ZP0DSC4.png)

**Comment by FelipeLimaDeSouza** [comment] 2020-11-25 21:45
> Below is what I have:
> 
> ![change](https://camo.githubusercontent.com/62181254ff23bbae68843b0faa156687f92737fbac6b902c4e6b52ac89bcd6ec/68747470733a2f2f692e696d6775722e636f6d2f5a5030445343342e706e67)

Worked for me. Thank you

**Comment by techinsider99** [comment] 2020-11-30 15:22
@thanakij This works!🔥. Thank you.

**Comment by ilyagru** [comment] 2021-01-15 14:18
I can't make the .aab work. I just updated my RN version to 0.63.4 which contains the fix but it seems the issue comes from Bitrise (Assemble Release, Export Universal APK, Android Sign, Deploy to Google Play steps) which handle artefacts in an unexpected way...
https://github.com/bitrise-steplib/steps-gradle-runner/issues/72
https://github.com/bitrise-steplib/steps-deploy-to-bitrise-io/issues/93
If anyone has other ideas to look into, please let me know.

**Comment by cristianoccazinsp** [comment] 2021-02-25 18:25
Experiencing the same issue after migrating gradle from 3.5.3 to 4.1.0 and wrapper from 6.2 to 6.7. Very annoying issue.

Running `./gradlew assembleDevRelease` ends up with a missing bundle file. Running it again, bundles it just fine.

**Comment by qindachang** [comment] 2021-03-11 07:38
> @tomoima525 @dulmandakh I found a workaround. It seems to be a gradle task ordering issue. It appears that assets get merged before the bundle gets copied to the intermediate output directory. Adding the following to `android/app/build.gradle` forces the bundle copy task to happen before merging assets.
> 
> ```
> //Fix for bundle not getting included in APK or AAB with android gradle plugin 4+
> //Seems like there's a task ordering issue and the assets get computed before the bundle is copied
> //This forces the copy task to run before merge resources
> project.afterEvaluate {
>         tasks.findAll { task ->
>             task.name.startsWith('merge') && task.name.endsWith('Resources')
>         }.each { t -> t.dependsOn "copyReleaseBundledJs" }
> }
> ```
> 
> I have little knowledge of gradle so this isn't a great workaround, it doesn't account for different build variants etc but at least it works for basic `:app:assembleRelease`. I guess gradle or android plugin behavior changed at some point that causes this task ordering issue to crop up. I don't know enough about gradle to track down the actual source but hopefully this gives more knowledgeable people a good clue to go on =)

work for me, thanks
