### ISSUE TITLE
Hot Module Reloading crashes packager when adding images.

### ISSUE THREAD

**Issue by dslounge** [facebook/react-native#7703] opened 2016-05-23 16:46 UTC
Hi,

I've been trying to figure a problem with the packager server. Whenever I add a new image to my files the packager server crashes due to `Syntax Error: ... Unexpected character '�'`. Here's a screenshot: 

<img width="1028" src="https://cloud.githubusercontent.com/assets/492403/15477739/4f101d8c-20e4-11e6-8547-70c678d3f133.png">

Should HRM be trying to parse images? Is there a way that I can get to not do that?

**Comment by jpokrzyk** [comment] 2016-05-23 19:22
It builds a map on server startup. You just have to restart the server. It's not an HMR issue. If you just do a regular reload I think you'll have the same problem unless that got changed recently.

**Comment by fab1an** [comment] 2016-05-25 13:23
This happens because, for some reason, the package tries to parse image files (or even sent them through babel). I tried using a `ignore` or `only` directive in my `.babelrc` which make the error go away, but crash the transformer at a different point instead.

**Comment by viix** [comment] 2016-06-15 10:01
same problem

**Comment by satya164** [comment] 2016-06-15 12:44
Duplicate of #7279

**Closed by satya164** 2016-06-15 12:44 UTC
