### ISSUE TITLE
Gradle "Implicit dependencies between tasks" warning on fresh install

### ISSUE THREAD

**Issue by williamgurzoni** [facebook/react-native#33202] opened 2022-03-01 23:15 UTC
### Description

Multiple warnings on a fresh React Native project during Android **Release** build.

The warnings are related with [Implicit Dependencies](https://docs.gradle.org/current/userguide/validation_problems.html#implicit_dependency).

Eg.

```
Execution optimizations have been disabled for task ':app:copyReleaseBundledJs' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '<path>/PocDependency/android/app/build/intermediates'. Reason: Task ':app:analyticsRecordingRelease' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
```

Please see full log on code example.

Thank you.

### Version

0.67.3

### Output of `npx react-native info`

```
npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 12.2.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 179.91 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.9.1 - ~/.nvm/versions/node/v16.9.1/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 7.21.1 - ~/.nvm/versions/node/v16.9.1/bin/npm
    Watchman: 2021.12.13.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 25, 26, 28, 29, 30, 31
      Build Tools: 25.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-21 | Google APIs Intel x86 Atom_64, android-25 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_251 - /Library/Java/JavaVirtualMachines/jdk1.8.0_251.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.3 => 0.67.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. npx react-native init ProjectName
2. cd ProjectName
3. npx react-native run-android --variant release

### Snack, code example, screenshot, or link to a repository

`npx react-native run-android --variant release` output:

```
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 863 file(s) to forward-jetify. Using 8 workers...
info JS server already running.
info Installing the app...

> Task :app:bundleReleaseJsAndAssets
warning: the transform cache was reset.
                    Welcome to Metro!
              Fast - Scalable - Integrated


info Writing bundle output to:, /Users/william/Documents/projects/temp/PocDependency/android/app/build/generated/assets/react/release/index.android.bundle
info Writing sourcemap output to:, /Users/william/Documents/projects/temp/PocDependency/android/app/build/generated/sourcemaps/react/release/index.android.bundle.map
info Done writing bundle output
info Done writing sourcemap output
info Copying 1 asset files
info Done copying assets

> Task :app:copyReleaseBundledJs
Execution optimizations have been disabled for task ':app:copyReleaseBundledJs' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/william/Documents/projects/temp/PocDependency/android/app/build/intermediates'. Reason: Task ':app:analyticsRecordingRelease' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :app:processReleaseMainManifest
Execution optimizations have been disabled for task ':app:processReleaseMainManifest' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/william/Documents/projects/temp/PocDependency/android/app/build/intermediates/navigation_json/release/navigation.json'. Reason: Task ':app:processReleaseMainManifest' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
[androidx.vectordrawable:vectordrawable-animated:1.0.0] /Users/william/.gradle/caches/transforms-3/5232169e73d4423ea21d51876a2d84b1/transformed/vectordrawable-animated-1.0.0/AndroidManifest.xml Warning:
        Package name 'androidx.vectordrawable' used in: androidx.vectordrawable:vectordrawable-animated:1.0.0, androidx.vectordrawable:vectordrawable:1.0.1.

> Task :app:processReleaseManifest
Execution optimizations have been disabled for task ':app:processReleaseManifest' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/william/Documents/projects/temp/PocDependency/android/app/build/intermediates/compatible_screen_manifest/release'. Reason: Task ':app:processReleaseManifest' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/william/Documents/projects/temp/PocDependency/android/app/build/intermediates/merged_manifest/release/AndroidManifest.xml'. Reason: Task ':app:processReleaseManifest' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :app:compressReleaseAssets
Execution optimizations have been disabled for task ':app:compressReleaseAssets' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/william/Documents/projects/temp/PocDependency/android/app/build/intermediates/merged_assets/release/out'. Reason: Task ':app:compressReleaseAssets' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :app:sdkReleaseDependencyData
Execution optimizations have been disabled for task ':app:sdkReleaseDependencyData' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/william/Documents/projects/temp/PocDependency/android/app/build/intermediates/metadata_library_dependencies_report/release/dependencies.pb'. Reason: Task ':app:sdkReleaseDependencyData' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :app:processReleaseManifestForPackage
Execution optimizations have been disabled for task ':app:processReleaseManifestForPackage' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/william/Documents/projects/temp/PocDependency/android/app/build/intermediates/merged_manifests/release'. Reason: Task ':app:processReleaseManifestForPackage' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :app:mergeReleaseJavaResource
Execution optimizations have been disabled for task ':app:mergeReleaseJavaResource' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/william/Documents/projects/temp/PocDependency/android/app/build/intermediates/java_res/release/out'. Reason: Task ':app:mergeReleaseJavaResource' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :app:mergeExtDexRelease
Execution optimizations have been disabled for task ':app:mergeExtDexRelease' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/william/Documents/projects/temp/PocDependency/android/app/build/intermediates/duplicate_classes_check/release'. Reason: Task ':app:mergeExtDexRelease' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/william/Documents/projects/temp/PocDependency/android/app/build/intermediates/external_file_lib_dex_archives/release'. Reason: Task ':app:mergeExtDexRelease' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :app:mergeReleaseNativeLibs
Execution optimizations have been disabled for task ':app:mergeReleaseNativeLibs' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/william/Documents/projects/temp/PocDependency/android/app/build/intermediates/merged_jni_libs/release/out'. Reason: Task ':app:mergeReleaseNativeLibs' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :app:stripReleaseDebugSymbols
Execution optimizations have been disabled for task ':app:stripReleaseDebugSymbols' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/william/Documents/projects/temp/PocDependency/android/app/build/intermediates/merged_native_libs/release/out'. Reason: Task ':app:stripReleaseDebugSymbols' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
Unable to strip the following libraries, packaging them as they are: libbetter.so, libc++_shared.so, libfabricjni.so, libfb.so, libfbjni.so, libfolly_futures.so, libfolly_json.so, libglog.so, libglog_init.so, libimagepipeline.so, libjsc.so, libjscexecutor.so, libjsi.so, libjsijniprofiler.so, libjsinspector.so, liblogger.so, libmapbufferjni.so, libnative-filters.so, libnative-imagetranscoder.so, libreact_codegen_rncore.so, libreact_debug.so, libreact_nativemodule_core.so, libreact_render_animations.so, libreact_render_attributedstring.so, libreact_render_componentregistry.so, libreact_render_core.so, libreact_render_debug.so, libreact_render_graphics.so, libreact_render_imagemanager.so, libreact_render_leakchecker.so, libreact_render_mapbuffer.so, libreact_render_mounting.so, libreact_render_runtimescheduler.so, libreact_render_scheduler.so, libreact_render_telemetry.so, libreact_render_templateprocessor.so, libreact_render_textlayoutmanager.so, libreact_render_uimanager.so, libreact_utils.so, libreactconfig.so, libreactnativeblob.so, libreactnativejni.so, libreactnativeutilsjni.so, libreactperfloggerjni.so, librrc_image.so, librrc_modal.so, librrc_progressbar.so, librrc_root.so, librrc_scrollview.so, librrc_slider.so, librrc_switch.so, librrc_text.so, librrc_textinput.so, librrc_unimplementedview.so, librrc_view.so, libturbomodulejsijni.so, libyoga.so.

> Task :app:installRelease
Installing APK 'app-release.apk' on 'SM-T355Y - 7.1.1' for app:release
Installed on 1 device.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 10 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

BUILD SUCCESSFUL in 51s
37 actionable tasks: 37 executed
info Connecting to the development server...
info Starting the app on "147642cb"...
Starting: Intent { cmp=com.pocdependency/.MainActivity launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } }
```

**Comment by Rehan-05** [comment] 2022-03-02 09:46
Facing the Same Issue. Same Version and Same Release Error in React Native.
Pleas guide.
Thank You

**Comment by cortinico** [comment] 2022-03-02 23:36
Yup we're aware of this (cc @ShikaSD). It's a new warning that Gradle introduced, so far it's not affecting the build output, but we'll look into finding a different approach to fix it.

**Comment by cristianoccazinsp** [comment] 2022-03-22 17:31
Same issue, it is scary and very noisy, but the final build seems ok.

Please, I really hope this doesn't mean upgrading native dependencies one by one to fix / correct a gradle config issue, but rather a global fix from RN.

**Comment by cortinico** [comment] 2022-03-26 15:19
> Please, I really hope this doesn't mean upgrading native dependencies one by one to fix / correct a gradle config issue, but rather a global fix from RN.

Yes this is addressable as a fix from our end.

> it is scary and very noisy,

Agree that is noisy, but is nothing to worry about. This is just Gradle mentioning that it can't parallelize the build further, as there are two tasks writing to the same folder. The final output won't be affected

**Comment by sunshinelancer828** [comment] 2022-04-08 15:52
same issue

**Comment by anwersolangi** [comment] 2022-04-11 15:20
Same version, same warnings, does anyone found the solution?

**Comment by paramsinghvc** [comment] 2022-04-11 22:24
My Android bundle being generated is not updating with new code changes and these warnings are always showing up.

**Comment by arjun1194** [comment] 2022-04-15 17:34
Same Issue

**Comment by drb1** [comment] 2022-04-19 18:03
Same issue, apk is build from Vs but not from android studio

**Comment by raf2019** [comment] 2022-05-03 21:05
Same error but for me, it affects the build (even for a recently created react-native project), when changed to android folder, and then run the command "./gradlew assembleRelease" to build an apk. The errors are released, the apk is generated, but dynamic interactions as links or requests for apis didn't work.

**Comment by fondue-tech** [comment] 2022-05-04 08:50
Same issue

**Comment by coolusaHD** [comment] 2022-05-06 16:51
same for me but app crashed on build...

**Comment by paramsinghvc** [comment] 2022-05-06 17:36
Gradle is just the saddest tool I've ever seen. Making Android development miserable.

**Comment by EmanueleAgo** [comment] 2022-05-14 17:12
Same for me, how did you fix this problem?

**Comment by goodryanboy** [comment] 2022-05-19 12:16
Same issue for react-native 0.67.0

**Comment by AhmedCommando** [comment] 2022-05-20 11:45
same for react native 0.67.4 with more extras errors

`Execution optimizations have been disabled for task ':app:copyReleaseBundledJs' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/ahmedbejaoui/Development/finway-group/mobile-app/android/app/build/intermediates'. Reason: Task ':app:compileDebugJavaWithJavac' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/ahmedbejaoui/Development/finway-group/mobile-app/android/app/build/intermediates'. Reason: Task ':app:compressDebugAssets' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/ahmedbejaoui/Development/finway-group/mobile-app/android/app/build/intermediates'. Reason: Task ':app:dexBuilderDebug' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/ahmedbejaoui/Development/finway-group/mobile-app/android/app/build/intermediates'. Reason: Task ':app:mergeDebugAssets' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/ahmedbejaoui/Development/finway-group/mobile-app/android/app/build/intermediates'. Reason: Task ':app:mergeDebugJavaResource' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/ahmedbejaoui/Development/finway-group/mobile-app/android/app/build/intermediates'. Reason: Task ':app:mergeDebugNativeLibs' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/ahmedbejaoui/Development/finway-group/mobile-app/android/app/build/intermediates'. Reason: Task ':app:mergeExtDexDebug' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/ahmedbejaoui/Development/finway-group/mobile-app/android/app/build/intermediates'. Reason: Task ':app:mergeLibDexDebug' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/ahmedbejaoui/Development/finway-group/mobile-app/android/app/build/intermediates'. Reason: Task ':app:mergeProjectDexDebug' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/ahmedbejaoui/Development/finway-group/mobile-app/android/app/build/intermediates'. Reason: Task ':app:packageDebug' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/ahmedbejaoui/Development/finway-group/mobile-app/android/app/build/intermediates'. Reason: Task ':app:processDebugMainManifest' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.`

**Comment by PamelinaDu** [comment] 2022-05-24 23:29
Same issue for RN 0.68 :/ I agree that probably is an issue of RN

**Comment by bloggerklik** [comment] 2022-06-09 15:34
Hi, there is no problem in the development environment, but when I get the release build, the app crashes. (Android) I created a new project (v0.68.2), I didn't make any changes, the room crashed in the same way.

**Comment by dmacpro91** [comment] 2022-06-15 23:52
Having to spend quite a bit of time fixing all kinds of build pipeline issues like this kinda sucks.  This is happening because the phase for adding in the index.android.bundle isn't working correctly.  It appears that file gets created correctly, but doesn't end up in the actual APK/AAB since when a gradle update comes out, the copy/merge process is slightly different.  Working on a workaround now...

**Comment by chipcop106** [comment] 2022-07-01 10:17
Any update on this?

**Comment by sud007** [comment] 2022-07-15 18:11
Same issue on KMM based project. seems like just a warning and beyond RN

**Comment by cortinico** [comment] 2022-07-29 16:52
> This causes our release build to fail

As mentioned by @sud007, that's a warning. It's unlikely this is causing your build to fail.

**Comment by sheikx1221** [comment] 2022-08-21 17:12
When will it be fixed ?
it clutters the whole terminal and is even worse when flavors enabled. It is in many many files and in many expo packages. Build times increased but isn't affecting final build.

**Comment by anassbenayed** [comment] 2022-08-23 17:34
Any updates on this? my app literally crashes on release builds.

**Comment by cortinico** [comment] 2022-09-16 15:04
> Build times increased but isn't affecting final build.

As mentioned, this is a warning, not an error.

> When will it be fixed ?

THis is under our radar and it's going to be fixed in the near future.

**Comment by rumax** [comment] 2022-10-12 13:57
> > Build times increased but isn't affecting final build.
> 
> As mentioned, this is a warning, not an error.
> 
> > When will it be fixed ?
> 
> THis is under our radar and it's going to be fixed in the near future.

@cortinico seems like you did focus on "Build times increased" instead of actual issue which is:

> This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.

So yes, technically it is a "warning" but it can also cause unexpected results.

**Comment by cortinico** [comment] 2022-10-14 19:19
> @cortinico seems like you did focus on "Build times increased" instead of actual issue which is.

@rumax Can I ask you where this claim comes from?
I'm aware of the implications of implicit task dependencies in Gradle, and rest assured that is high on my agenda as I mentioned before.

Similarly, we do have other build failures (not warning, i.e. the build is always broken) of specific platforms and user scenarios which have a higher priority that fixing implicit task dependencies.

**Comment by skavor** [comment] 2022-11-04 23:55
> Same issue for RN 0.68 :/ I agree that probably is an issue of RN

any update for this issue ?? 

thanks

**Comment by cortinico** [comment] 2022-11-05 04:06
Yes. I'm happy to share that I worked on this issue and it will be fixed with 0.71.0

**Comment by herbertvuijk** [comment] 2022-11-13 17:50
@cortinico Hotfix on 0.70 would be nice, just finished upgrade from .63 to 0.70.5 and took me a full week for my project. I see the impact of going from 0.70 to 0.71 is also not small.

**Comment by cortinico** [comment] 2022-11-23 20:23
> @cortinico Hotfix on 0.70 would be nice, just finished upgrade from .63 to 0.70.5 and took me a full week for my project. I see the impact of going from 0.70 to 0.71 is also not small.

Sadly that's not easy. The amount of work necessary to fix this (and other issues on the Gradle side of thigns) measn that we can't just backport this fix back on 0.70

**Comment by anwarhamr** [comment] 2022-12-03 07:36
I have a production product out that recently started to have this issue now I can't build and I cannot upgrade from 67 in the time necessary.  Is there anything I can do?  @cortinico what is your fix?

**Comment by cortinico** [comment] 2022-12-05 11:56
> I have a production product out that recently started to have this issue now I can't build and I cannot upgrade from 67 in the time necessary

The reported issue is a 'build warning', not an error, so definitely not your issue @anwarhamr  Please open a separate issue and provide a reproducer.
Fix for this issue will be shipped in 0.71.0

**Comment by spinoza1791** [comment] 2023-01-31 17:53
For those stuck in 0.70.x, can a fix be made for 0.70.x as well? I'm on 0.70.7 today, and cannot port all my plugins to 0.71.x

**Comment by cortinico** [comment] 2023-02-01 11:57
> For those stuck in 0.70.x, can a fix be made for 0.70.x as well?

Sadly not as this is a warning, not an error. The fix was a major reword of the build logic, we can't simply backport it to 0.70.

Closing as this issue is fixed in 0.71. If the issue persists on 0.71, please open a separate issue.

**Closed by cortinico** 2023-02-01 11:57 UTC
Labels: Tool: Gradle, Shared with React Native Team

**Comment by MobileMon** [comment] 2023-02-09 14:02
@cortinico I'm still getting this error in 0.71.2

**Comment by cortinico** [comment] 2023-02-09 14:09
@MobileMon 

> If the issue persists on 0.71, please open a separate issue.

As mentioned, please open a separate issue and provide a reproducer
