### ISSUE TITLE
Performance issue on v0.42

### ISSUE THREAD

**Issue by tuandt** [facebook/react-native#12779] opened 2017-03-08 03:42 UTC
Hi you guys,
I just upgraded my app from v0.37 to v0.42, my app is so slow now. Do you guys have same problem?

### Additional Information

* React Native version: 0.42
* Platform: Android
* Operating System: Windows

**Comment by nihgwu** [comment] 2017-03-08 06:14
#11809

**Comment by janicduplessis** [comment] 2017-03-08 08:35
Closing as a duplicate of #11809

**Closed by janicduplessis** 2017-03-08 08:35 UTC
