### ISSUE TITLE
AAPT: error: resource android:attr/lStar not found.

### ISSUE THREAD

**Issue by Atreyarao** [facebook/react-native#35286] opened 2022-11-09 13:32 UTC
### Description

I have made no changes to project, but still I am getting this error "AAPT: error: resource android:attr/lStar not found.".
My compileSdkVersion,  targetSdkVersion, is 30. I dont want to upgrade it to 31 as it will break other things. 

### Version

0.63.4

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
    Memory: 4.01 GB / 15.84 GB
  Binaries:
    Node: 16.16.0 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - D:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 11.0.16.1 - D:\Program Files\Eclipse Adoptium\jdk-11.0.16.101-hotspot\bin\javac.EXE
    Python: 3.11.0 - C:\Python311\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Snack, code example, screenshot, or link to a repository

 ext {
         googlePlayServicesVersion = "+" 
        firebaseMessagingVersion = "+" 

       buildToolsVersion = "28.0.3"

      minSdkVersion = 23
        compileSdkVersion = 30
        targetSdkVersion = 30
        supportLibVersion ="23.1.1"
        kotlinVersion = "1.6.0"
        
        
    }

**Comment by anhkieet** [comment] 2022-11-09 15:24
Update RN to 0.63.5

**Comment by NaitikDartexon** [comment] 2022-11-10 06:57
I cannot update my version but i make some changes and now i was able to create a release build this solution is works for me.
1. Revert back all the changes you have made after that.
2. delete node_module than delete build folder (android/build & android/app/build)
3. run npm i than clean cache ./gradlew cleanBuildCache
4. go to build gradle file in android and add this line of code
![image](https://user-images.githubusercontent.com/106224314/201021086-29e4d888-4beb-45f9-ac3c-2c7071ad9252.png)
5. cd android && ./gradlew clean && cd ..
6. npx react-native run-android 
7. After successfully run just create your release application (cd android && ./gradlew clean && ./gradlew assembleRelese)

**Comment by cortinico** [comment] 2022-11-25 12:57
> ### Description
> I have made no changes to project, but still I am getting this error "AAPT: error: resource android:attr/lStar not found.". My compileSdkVersion, targetSdkVersion, is 30. I dont want to upgrade it to 31 as it will break other things.
> 
> ### Version
> 0.63.4

Closing as a duplicate of #35210

**Closed by cortinico** 2022-11-25 12:57 UTC
Labels: Platform: Android, Needs: Triage :mag:

**Comment by dseipp** [comment] 2023-01-10 16:07
This solved the problem, details in issue #35210 didn't work.
