### ISSUE TITLE
Remote Debug JS - works only DEV mode after 0.58 , but in 0.57 all good

### ISSUE THREAD

**Issue by in4core** [facebook/react-native#23254] opened 2019-02-01 20:49 UTC
## Environment
React Native Environment Info:
System:
OS: Windows 10
CPU: (4) x64 Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
Memory: 1.68 GB / 7.95 GB
Binaries:
npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
IDEs:
Android Studio: Version 3.3.0.0 AI-182.5107.16.33.5199772

Dependencies :
"dependencies": {
"react": "16.6.3",
"react-native": "0.58.3",
"react-native-gesture-handler": "^1.0.15",
"react-native-img-cache": "^1.6.0",
"react-native-section-list-get-item-layout": "^2.2.3",
"react-native-vector-icons": "^6.2.0",
"react-navigation": "^3.0.9",
"rn-fetch-blob": "^0.10.15"
},

## Description
Remote Debug JS - works only DEV mode after 0.58 , but in 0.57 all good.
When starts it in Prod mode we have some errors
Cannot read property 'Constants' of null
Module AppRegistry is not a registered callable module (calling runApplication)

**Comment by Abuitime** [comment] 2019-02-20 21:50
Same

**Comment by darekg11** [comment] 2019-02-23 17:38
Just leaving comment, it is also happening to me.  
But seeing that not so many people reported this, do you think that this might be bound to specific 3rd module having problems with newest React-Native (0.58)?

**Comment by in4core** [comment] 2019-02-25 09:17
> Just leaving comment, it is also happening to me.
> But seeing that not so many people reported this, do you think that this might be bound to specific 3rd module having problems with newest React-Native (0.58)?

I dont know,  but i will try use clear project, without dependencies - today.  But, if i think true, clear project also fail

**Comment by in4core** [comment] 2019-02-25 09:17
"dependencies": {
    "js-md5": "^0.7.3",
    "react": "16.6.3",
    "react-native": "^0.58.5",
    "react-native-device-info": "^0.26.2",
    "react-native-gesture-handler": "^1.0.15",
    "react-native-image-picker": "^0.28.0",
    "react-native-img-cache": "^1.6.0",
    "react-native-push-notification": "^3.1.2",
    "react-native-section-list-get-item-layout": "^2.2.3",
    "react-native-vector-icons": "^6.2.0",
    "react-native-webview": "^5.0.5",
    "react-navigation": "^3.0.9",
    "rn-fetch-blob": "^0.10.15"
  },

**Comment by abs-zero** [comment] 2019-03-13 10:39
This problem still persists in v0.59

**Comment by dulmandakh** [comment] 2019-03-19 14:40
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗

**Closed by dulmandakh** 2019-03-19 14:40 UTC
Labels: Type: Bug Report

**Comment by abs-zero** [comment] 2019-03-20 05:42
## Reproducible Demo:
On a freshly created project by `react-native-cli` in android:

1. Shake phone -> Dev Settings -> Uncheck `JS Dev` Mode and `Use JS Deltas`. Then back.
2. Shake phone -> Turn on Debug JS Remotely. Then back
3. Reload

### Errors I got, visible in chrome developer tool console:

```
Animated.js:32 Invariant Violation: requireNativeComponent: "RCTView" was not found in the UIManager.

This error is located at:
    in RCTView
    in App
    in RCTView
    in RCTView
    in AppContainer
handleException @ Animated.js:32
logCapturedError @ TouchableOpacity.js:163
logError @ TouchableOpacity.js:198
expirationTime.callback @ VirtualizedList.js:10
commitUpdateEffects @ TouchableNativeFeedback.android.js:278
commitUpdateQueue @ TouchableNativeFeedback.android.js:266
commitAllLifeCycles @ VirtualizedList.js:516
commitRoot @ VirtualizedList.js:561
(anonymous) @ VirtualizedList.js:905
exports.unstable_runWithPriority @ ReactNativeRenderer-prod.js:281
completeRoot @ VirtualizedList.js:901
performWorkOnRoot @ VirtualizedList.js:879
performWork @ VirtualizedList.js:860
requestWork @ VirtualizedList.js:803
scheduleWork @ VirtualizedList.js:724
updateContainer @ VirtualizedList.js:983
render @ VirtualizedList.js:1243
renderApplication @ blob:http://localhost:8081/a1b75748-f7b0-4700-aeec-ff13938d9900:37149
run @ ListViewDataSource.js:188
runApplication @ ListViewDataSource.js:255
__callFunction @ ReactNativeART.js:322
(anonymous) @ ReactNativeART.js:157
__guard @ ReactNativeART.js:280
callFunctionReturnFlushedQueue @ ReactNativeART.js:157
(anonymous) @ debuggerWorker.js:80
Animated.js:32 Invariant Violation: requireNativeComponent: "RCTView" was not found in the UIManager.

This error is located at:
    in RCTView
    in App
    in RCTView
    in RCTView
    in AppContainer
```
@dulmandakh 	Hi, can you check this and consider reopening the issue? Thanks.

**Comment by th317erd** [comment] 2019-06-05 18:57
@dulmandakh Can you reopen this issue? I am also having the same problem, and now there is a reproducible example (posted above).
