### ISSUE TITLE
 Trying to add unknown view tag: 682

### ISSUE THREAD

**Issue by wj495175289** [facebook/react-native#14768] opened 2017-06-29 03:22 UTC
### Is this a bug report?

No

### Have you read the Bugs section of the Contributing to React Native Guide?

Yes

### Environment

1. `react-native -0.43.4`:
2. `node -6.9.1`:
3. `npm -3.10.8`:
4. `yarn --version` (if you use Yarn):

Then, specify:

1. Target Platform (e.g. iOS, Android): Android
2. Development Operating System (e.g. macOS Sierra, Windows 10): Mac OS
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant):
Android Studio SDK version 24

### Steps to Reproduce

(Write your steps here:)

1.Even now, can not reproduce, only to see the online error log
2. com.facebook.react.uimanager.IllegalViewOperationException: Trying to add unknown view tag: 682
3.How to find where the problem occurred?  the tag? but how to find in js file?

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by hramos** [comment] 2017-06-29 03:46
Closing as this is not a bug report.

**Closed by hramos** 2017-06-29 03:46 UTC
