### ISSUE TITLE
React-native run-android in loop  (Starting JS server ... )

### ISSUE THREAD

**Issue by EvertonCosmo** [facebook/react-native#26097] opened 2019-08-18 12:30 UTC
After starting a new project and trying to test it, it starts js serving. In this case I used the test app, but I have an app in the same situation

React Native version:
System:
    OS: Linux 5.2 Arch Linux undefined
    CPU: (4) x64 Intel(R) Core(TM) i3-5015U CPU @ 2.10GHz
    Memory: 230.84 MB / 3.56 GB
    Shell: 5.7.1 - /usr/bin/zsh
  Binaries:
    Node: 11.15.0 - /usr/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.10.3 - /usr/bin/npm
  SDKs:
    Android SDK:
      API Levels: 22, 25, 27, 28, 29
      Build Tools: 28.0.3, 29.0.1
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce

1.type react-native init 
2.type react-native run-android (with devices or emulator connected)

![Screenshot from 2019-08-18 09-26-50](https://user-images.githubusercontent.com/12981463/63224451-d1c53f00-c19a-11e9-90ed-13e4f66d733f.png)

**Comment by craicoverflow** [comment] 2019-08-18 15:11
I'm also facing this issue.

**Comment by creativemind1** [comment] 2019-08-19 05:29
same here

**Comment by nicolaslima321** [comment] 2019-08-19 13:46
i'm with same problem, i tried to reinstall nodejs and react-native but no success

**Comment by nicolaslima321** [comment] 2019-08-19 14:30
![image](https://user-images.githubusercontent.com/23743072/63273612-ae6ec280-c274-11e9-91fe-ebe2f728441c.png)

Using Fedora 30

**Comment by aismaniotto** [comment] 2019-08-19 23:33
Same problem on Manjaro. :(

**Comment by ogiansouza** [comment] 2019-08-20 02:04
It's links solved my problem: https://stackoverflow.com/questions/57313661/stuck-on-info-starting-js-server

**Comment by aismaniotto** [comment] 2019-08-20 03:15
Thank you very much. That's works as a workaround. Waiting for final solution. And again, thank you!!

**Comment by EvertonCosmo** [comment] 2019-08-20 11:35
@ogiansouza Thanks a lot

**Comment by efranelas** [comment] 2019-10-08 11:53
> It's links solved my problem: https://stackoverflow.com/questions/57313661/stuck-on-info-starting-js-server

Works perfectly, thanks!

**Comment by vkasraj** [comment] 2019-10-18 16:40
I am also facing this issue.

### React Native
```
react-native-cli: 2.0.1
react-native: 0.61.2
```

### Kernel
```
Linux hello-pc 5.2.21-1-MANJARO #1 SMP PREEMPT Sat Oct 12 11:09:56 UTC 2019 x86_64 GNU/Linux
```

### OS
```
Description:    Manjaro Linux
Release:        18.1.1
Codename:       Juhraya
```

> It's links solved my problem: https://stackoverflow.com/questions/57313661/stuck-on-info-starting-js-server

Though this solved my issue. But many of the devs did not want to run two commands to run the project.

**Comment by siddhi-sandy** [comment] 2019-11-19 10:36
Any fix yet?

**Comment by franjorub** [comment] 2019-12-07 06:40
same issue in openSuSe tumbleweed

**Comment by Ianito** [comment] 2019-12-27 17:58
Same here.

Manjaro 18.1.4
Kernel: x86_64 Linux 5.4.2-1-MANJARO

**Comment by cassioalmeidas** [comment] 2020-01-02 03:17
Temporary fix:

`REACT_TERMINAL=<your terminal> react-native run-android`

in my case with archlinux + xfce4:

`REACT_TERMINAL=xfce4-terminal react-native run-android`

or puts in your .bashrc:

`export REACT_TERMINAL=xfce4-terminal`

note: it will use two instances of terminal

**Comment by karansapolia** [comment] 2020-01-07 19:15
> It's links solved my problem: https://stackoverflow.com/questions/57313661/stuck-on-info-starting-js-server

Wish this is officially resolved soon.

**Comment by albertschulz** [comment] 2020-01-18 02:55
The issue is caused, because spawning the process to run the Metro Bundler does not return:
https://github.com/react-native-community/cli/blob/master/packages/platform-android/src/commands/runAndroid/index.ts#L348

This seems to be an issue in the `execa` library, which was introduced by this merge:
https://github.com/react-native-community/cli/pull/601/files

It can be fixed by replacing the call with the previous one:
`spawn('sh', [launchPackagerScript], procConfig);`

**Possible workarounds**, by setting the terminal
* explicitly, using `$ react-native run-android --terminal path/to/terminal`
* implicitly, by setting one of the environment variables `TERM_PROGRAM` or `REACT_TERMINAL`

**Comment by numToStr** [comment] 2020-02-20 14:55
I hope this issue get resolved quickly for all the linux guys.✌🏻

**Comment by mrsoftware** [comment] 2020-02-29 15:07
same.

**Comment by mondyfy** [comment] 2020-03-03 16:59
Stuck in the same issue in manjaro 19.0 Kyria.

**Comment by Rapiz1** [comment] 2020-03-12 11:01
same.

**Comment by h2ash** [comment] 2020-03-19 18:48
manjaro 19 kde
same

**Comment by arafatzahan** [comment] 2020-03-30 17:54
How's this still not fixed? Sad

**Comment by Esemesek** [comment] 2020-04-05 20:29
Fix for that is already merged in the `cli` - https://github.com/react-native-community/cli/issues/1066. I think we're safe to close this issue.

**Comment by ShivamJoker** [comment] 2020-04-07 13:00
How this issue is still present in the latest version of RN -_- please fix it

**Comment by Esemesek** [comment] 2020-04-07 13:13
@ShivamJoker First of all, please stop spamming various repos without giving any additional or helpful information.
Second of all, this issue is about terminal not launching on `Linux` machines, while your issue is connected to `OSX` (https://github.com/react-native-community/cli/issues/1066#issuecomment-610369254). This issue should be fixed in the latest version of `@react-native-community/cli`. Your problem seems to be connected to your local env setup.
@cpojer Can we close this issue as it was already fixed and released in the CLI (https://github.com/react-native-community/cli/pull/1099)

**Comment by BrenoMazieiro** [comment] 2020-04-08 22:54
**Linux:**
Go to the terminal and type:
`react-native start`

and then in **OTHER** terminal, inside your project folder:
`yarn android`
or
`npm run android`

**Comment by yassinebridi** [comment] 2020-05-31 01:30
@Esemesek this issues is still occuring, using the lates cli version 2.0.1

**Comment by safaiyeh** [comment] 2020-08-23 22:06
> @ShivamJoker First of all, please stop spamming various repos without giving any additional or helpful information.
> Second of all, this issue is about terminal not launching on `Linux` machines, while your issue is connected to `OSX` ([react-native-community/cli#1066 (comment)](https://github.com/react-native-community/cli/issues/1066#issuecomment-610369254)). This issue should be fixed in the latest version of `@react-native-community/cli`. Your problem seems to be connected to your local env setup.
> @cpojer Can we close this issue as it was already fixed and released in the CLI ([react-native-community/cli#1099](https://github.com/react-native-community/cli/pull/1099))

Closing, for future CLI issues please file issues at https://github.com/react-native-community/cli

**Closed by safaiyeh** 2020-08-23 22:06 UTC
Labels: Bug, Platform: Android, Platform: Linux

**Comment by jose2007kj** [comment] 2020-09-23 01:56
> **Linux:**
> Go to the terminal and type:
> `react-native start`
> 
> and then in **OTHER** terminal, inside your project folder:
> `yarn android`
> or
> `npm run android`

thanks this got the issue fixed for me in arch-linux

**Comment by whatdtech** [comment] 2020-10-31 09:25
Reinstalling android studio with a new emulator or changing the app name in **app.json , build.gradle and android manifest.xml** solved the issue.
