### ISSUE TITLE
build rn 0.70.5 with new Architecture on M1

### ISSUE THREAD

**Issue by sssajjad007** [facebook/react-native#35230] opened 2022-11-07 08:05 UTC
### Description

i got this error  when add this flag ``` newArchEnabled=true ```
 to gradle.properties.

```
CMake Error in CMakeLists.txt:
Imported target "folly_runtime" includes non-existent path
```

### Version

0.70.5

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 101.59 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
    Watchman: 2022.10.31.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/Hamid/.gem/ruby/2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.4 => 0.70.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Enable new architecture on android.
when I try to build via android studio project I get the above error.
When I try yarn android, it builds properly.

### Snack, code example, screenshot, or link to a repository

https://github.com/sssajjad007/react-native-0.70.5-template

**Comment by rasoulm777** [comment] 2022-11-07 08:07
i got this error too ...

**Comment by hamidrahimi** [comment] 2022-11-07 08:08
+1

**Comment by rasoulm777** [comment] 2022-11-07 08:10
my os is windows 10 and it doesn't seem to matter

**Comment by cortinico** [comment] 2022-11-07 18:53
> CMake Error in CMakeLists.txt:
> Imported target "folly_runtime" includes non-existent path

Can you share your whole build log?

**Comment by sssajjad007** [comment] 2022-11-08 07:01
> > CMake Error in CMakeLists.txt:
> > Imported target "folly_runtime" includes non-existent path
> 
> Can you share your whole build log?

This is what I see in Android Studio: 
<img width="1936" alt="Screen Shot 2022-11-08 at 9 44 20 AM" src="https://user-images.githubusercontent.com/37308584/200496286-00e4385e-62f2-4920-94d0-19ee181e7359.png">

**Comment by hamidrahimi** [comment] 2022-11-08 07:27
![image](https://user-images.githubusercontent.com/579156/200500643-0d2e57cb-ce49-4598-95e3-c37a121fad6a.png)
@cortinico

**Comment by cortinico** [comment] 2022-11-25 15:00
@sssajjad007 @hamidrahimi Could you try on `0.71.0-rc2` as the issue should be solved there

**Comment by sssajjad007** [comment] 2022-11-25 16:45
> @sssajjad007 @hamidrahimi Could you try on `0.71.0-rc2` as the issue should be solved there
hi. I got this error when building on Windows.
I will try on M1 later & I'll let you know 
```
info Starting JS server...
* daemon not running; starting now at tcp:5037
* daemon started successfully
info Launching emulator...
info Successfully launched emulator.
info Installing the app...
5 actionable tasks: 5 executed

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Illegal character in authority at index 7: file://C:\Users\Acer\Documents\RN0710RC2\node_modules\react-native/android

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Illegal character in authority at index 7: file://C:\Users\Acer\Documents\RN0710RC2\node_modules\react-native/android

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

    at makeError (C:\Users\Acer\Documents\RN0710RC2\node_modules\execa\index.js:174:9)
    at C:\Users\Acer\Documents\RN0710RC2\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (C:\Users\Acer\Documents\RN0710RC2\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (C:\Users\Acer\Documents\RN0710RC2\node_modules\@react-native-community\cli\build\index.js:142:9)
info Run CLI with --verbose flag for more details.
```

**Comment by cortinico** [comment] 2022-11-25 19:19
> Illegal character in authority at index

Interesting, that's a duplicate of https://github.com/facebook/react-native/issues/35472
We definitely need to fix this before we release 0.71.0

Thank you very much for testing it 🙏

**Comment by hamidrahimi** [comment] 2022-11-25 20:08
@cortinico I tested everything on a Macbook M1 Pro with **newArchEnabled**, and everything worked without a hitch 🙏

**Comment by sssajjad007** [comment] 2022-11-26 07:43
@cortinico everything work fine in M1 and iMac ( Intel ), android & iOS with newArchEnabled = true,
thanks a lot :v:

**Comment by sssajjad007** [comment] 2022-11-30 19:45
> > Illegal character in authority at index
> 
> Interesting, that's a duplicate of #35472 We definitely need to fix this before we release 0.71.0
> 
> Thank you very much for testing it 🙏

Hi,
I made a new project with version 0.71.0-rc.3 & newArchEnabled and it works without any problems on Windows.

**Comment by cortinico** [comment] 2022-12-01 13:06
Great, closing this then 👍

**Closed by cortinico** 2022-12-01 13:06 UTC
Labels: Needs: Attention, Type: New Architecture

**Comment by godlatro** [comment] 2022-12-05 10:50
I have Cmake error on RN 0.70.5 and gradle plugin 7.2.1
Try change to gradle plugin to 7.3.1 and find new error "Could not create task ':ReactAndroid:compileDebugKotlin'"
