### ISSUE TITLE
ScrollView Example not working

### ISSUE THREAD

**Issue by dbnex14** [facebook/react-native#15163] opened 2017-07-24 04:40 UTC
### Is this a bug report?
Yes

### Have you read the Bugs section of the How to Contribute guide?

No

### Environment

1. `react-native -v`: 0.45.1
2. `node -v`: 6.11.1
3. `npm -v`: 3.10.10
4. `yarn --version`:

Then, specify:

- Target Platform:running on Android but just learning about RN and going through examples and run into issue with ScrollView complaining that could not find favicon.png

- Development Operating System:MacOS

- Build tools:I am using Atom to go through your examples and Expo to run them on Android

### Steps to Reproduce

(Write your steps here:)

1. Copy/paste ScrollView example (http://facebook.github.io/react-native/docs/using-a-scrollview.html) into Athom CRNA App.js
2.open Terminal and issue npm start
3.this will generate QR
4. open Expo on Android and scan the QR
5. this runs app and in terminal shows "9:32:26 PM: Failed building JavaScript bundle"
6. on device I get "The developent server returned response error code: 500 ..." the rest of error shown in attached screenshot
![screenshot_20170723-213417](https://user-images.githubusercontent.com/8755679/28508318-fe320992-6fee-11e7-87e0-b4481897b36d.png)

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by hramos** [comment] 2017-07-24 17:25
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-07-24 17:25 UTC
