### ISSUE TITLE
'folly/folly-config.h' file not found

### ISSUE THREAD

**Issue by alreadyRight** [facebook/react-native#18769] opened 2018-04-09 09:06 UTC
![image](https://user-images.githubusercontent.com/23163815/38488831-36717f14-3c17-11e8-91e1-cb26da6e04ce.png)
I've got the issue "folly/folly-config.h' file not found"
"react-native" : "0.55.1"
I‘ve create the profile
```
pod 'React', :path => '../../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../../node_modules/react-native/third-party-podspecs/Folly.podspec'
```
install success
then I run the ios product get the "folly/folly-config.h' file not found" Error message
How can I solve it？

**Comment by kelset** [comment] 2018-04-09 10:02
This happens when your pod cache is corrupted. Try cleaning the Xcode project, then the build folder, then the DerivedData folder, then the pod cache, then run again pod install.

**Comment by maxdavidson** [comment] 2018-04-09 13:32
Duplicate of #18683?

**Comment by kelset** [comment] 2018-04-09 14:28
Nice catch, thanks @maxdavidson.

Duplicate of https://github.com/facebook/react-native/issues/18683

**Closed by kelset** 2018-04-09 14:28 UTC
Labels: :clipboard:No Template, :large_blue_diamond:iOS

**Comment by xiaoyongchen** [comment] 2018-04-17 06:42
@alreadyRight
哥们，你的这个问题解决没有

**Comment by alreadyRight** [comment] 2018-04-17 06:51
当时没解决，但现在按照RN文档上操作一遍就成功了

**Comment by xiaoyongchen** [comment] 2018-04-17 11:07
@alreadyRight 
自己搞个新项目能行，
在原来项目就报错

**Comment by jdegger** [comment] 2018-04-17 11:45
Going back to 0.54.2 worked for me. 0.55.0 should not have been released as stable.

**Comment by LionBuer** [comment] 2018-06-05 08:19
@alreadyRight @xiaoyongchen 新项目没问题，集成进老项目就报错，很无奈

**Comment by Feng999** [comment] 2018-06-25 13:57
@alreadyRight  按照哪块的文档操作好的呀

**Comment by YVvanessa** [comment] 2019-02-22 00:51
> @alreadyRight
> 自己搞个新项目能行，
> 在原来项目就报错

遇到了同样的问题，你后来怎么解决的丫？
