### ISSUE TITLE
Android apk release build is successful but crashes on start: couldn't find DSO to load: libjscexecutor.so

### ISSUE THREAD

**Issue by tonydatw** [facebook/react-native#35426] opened 2022-11-22 05:50 UTC
### Description

Android .apk build is successful without any error message, however it crashes immediately after opening it. Logcat is as follows:
```

11-25 00:08:53.644 29631 29631 E SoLoader: couldn't find DSO to load: libjscexecutor.so
11-25 00:08:53.644 29631 29631 E SoLoader:      SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/com.wanderapp/lib-main flags = 1]
11-25 00:08:53.644 29631 29631 E SoLoader:      SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/com.wanderapp-iyjZsNCgivNS6ppjJ55hlQ==/lib/arm flags = 0]
11-25 00:08:53.644 29631 29631 E SoLoader:      SoSource 2: com.facebook.soloader.DirectorySoSource[root = /vendor/lib flags = 2]
11-25 00:08:53.644 29631 29631 E SoLoader:      SoSource 3: com.facebook.soloader.DirectorySoSource[root = /system/lib flags = 2]
11-25 00:08:53.644 29631 29631 E SoLoader:      Native lib dir: /data/app/com.wanderapp-iyjZsNCgivNS6ppjJ55hlQ==/lib/arm
11-25 00:08:53.644 29631 29631 E SoLoader:  result: 0
11-25 00:08:53.660 29631 29631 E SoLoader: couldn't find DSO to load: libhermes-executor-debug.so
11-25 00:08:53.660 29631 29631 E SoLoader:      SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/com.wanderapp/lib-main flags = 1]
11-25 00:08:53.660 29631 29631 E SoLoader:      SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/com.wanderapp-iyjZsNCgivNS6ppjJ55hlQ==/lib/arm flags = 0]
11-25 00:08:53.660 29631 29631 E SoLoader:      SoSource 2: com.facebook.soloader.DirectorySoSource[root = /vendor/lib flags = 2]
11-25 00:08:53.660 29631 29631 E SoLoader:      SoSource 3: com.facebook.soloader.DirectorySoSource[root = /system/lib flags = 2]
11-25 00:08:53.660 29631 29631 E SoLoader:      Native lib dir: /data/app/com.wanderapp-iyjZsNCgivNS6ppjJ55hlQ==/lib/arm
11-25 00:08:53.660 29631 29631 E SoLoader:  result: 0
11-25 00:08:53.664 29631 29631 E SoLoader: couldn't find DSO to load: libhermes-executor-release.so
11-25 00:08:53.664 29631 29631 E SoLoader:      SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/com.wanderapp/lib-main flags = 1]
11-25 00:08:53.664 29631 29631 E SoLoader:      SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/com.wanderapp-iyjZsNCgivNS6ppjJ55hlQ==/lib/arm flags = 0]
11-25 00:08:53.664 29631 29631 E SoLoader:      SoSource 2: com.facebook.soloader.DirectorySoSource[root = /vendor/lib flags = 2]
11-25 00:08:53.664 29631 29631 E SoLoader:      SoSource 3: com.facebook.soloader.DirectorySoSource[root = /system/lib flags = 2]
11-25 00:08:53.664 29631 29631 E SoLoader:      Native lib dir: /data/app/com.wanderapp-iyjZsNCgivNS6ppjJ55hlQ==/lib/arm
11-25 00:08:53.664 29631 29631 E SoLoader:  result: 0
11-25 00:08:53.666 29631 29631 E AndroidRuntime: FATAL EXCEPTION: main
```

### Version

0.70.4

### Output of `npx react-native info`

```
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz  
    Memory: 586.66 MB / 7.86 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE       
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.22.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 11.0.12
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.70.4 => 0.70.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1 - create a new device from android studio before version 12.
2 - type react-native run-android --variant release on console
3 - Open Logcat from android studio, select debuggable phone and error section from combobox.
4 - Search couldn't find DSO to load to find error.

### Snack, code example, screenshot, or link to a repository

`build.gradle` :

```
apply plugin: "com.android.application"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation. If none specified and
 *   // "index.android.js" exists, it will be used. Otherwise "index.js" is
 *   // default. Can be overridden with ENTRY_FILE environment variable.
 *   entryFile: "index.android.js",
 *
 *   // https://reactnative.dev/docs/performance#enable-the-ram-format
 *   bundleCommand: "ram-bundle",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    enableHermes: true  // clean and rebuild if changing
]

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

/**
 * The preferred build flavor of JavaScriptCore.
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US.  Note that
 * this variant is about 6MiB larger per architecture than default.
 */
def jscFlavor = 'org.webkit:android-jsc:+'
def useIntlJsc = false
/**
 * Whether to enable the Hermes VM.
 *
 * This should be set on project.ext.react and mirrored here.  If it is not set
 * on project.ext.react, JavaScript will not be compiled to Hermes Bytecode
 * and the benefits of using Hermes will therefore be sharply reduced.
 */
def enableHermes = project.ext.react.get("enableHermes", false);

android {
    ndkVersion rootProject.ext.ndkVersion

    compileSdkVersion rootProject.ext.compileSdkVersion

    packagingOptions {
        pickFirst '**/armeabi-v7a/libc++_shared.so'
        pickFirst '**/x86/libc++_shared.so'
        pickFirst '**/arm64-v8a/libc++_shared.so'
        pickFirst '**/x86_64/libc++_shared.so'
        pickFirst '**/x86/libjsc.so'
        pickFirst '**/armeabi-v7a/libjsc.so'
        jniLibs.useLegacyPackaging = true
    }

    defaultConfig {
        applicationId "com.app"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
        release {
            if (project.hasProperty('MYAPP_UPLOAD_STORE_FILE')) {
                storeFile file(MYAPP_UPLOAD_STORE_FILE)
                storePassword MYAPP_UPLOAD_STORE_PASSWORD
                keyAlias MYAPP_UPLOAD_KEY_ALIAS
                keyPassword MYAPP_UPLOAD_KEY_PASSWORD
            }
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug
            signingConfig signingConfigs.release
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }

    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            // Example: versionCode 1 will generate 1001 for armeabi-v7a, 1002 for x86, etc.
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        defaultConfig.versionCode * 1000 + versionCodes.get(abi)
            }

        }
    }
}

dependencies {

    
    implementation fileTree(dir: "libs", include: ["*.jar"])
    //noinspection GradleDynamicVersion
    implementation "com.facebook.react:react-native:+"  // From node_modules

    implementation "androidx.core:core-splashscreen:1.0.0-alpha02" // Add this line

    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"

    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
      exclude group:'com.facebook.fbjni'
    }

    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
        exclude group:'com.squareup.okhttp3', module:'okhttp'
    }

    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }

    if (enableHermes) {

                implementation("com.facebook.react:hermes-engine:0.70.4") { // From node_modules
            exclude group:'com.facebook.fbjni'
                }
    } else {
        implementation jscFlavor
    }
    if (useIntlJsc) {
     implementation 'org.webkit:android-jsc-intl:+'
} else {
     implementation 'org.webkit:android-jsc:+'
}
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.implementation
    into 'libs'
}

apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"
apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
```

**Comment by tomcheung1208** [comment] 2022-11-27 15:22
I have same issue, anyone can help? My company is waiting the build, thanks so much

**Comment by tomcheung1208** [comment] 2022-11-27 15:42
in android/app/build.gradle -> project.ext.react
If I set enableHermes to false or add
`
    deleteDebugFilesForVariant: {
        def variant ->
            variant.name.toLowerCase().contains("release") || variant.name.toLowerCase().contains("staging")
    }
`

the build error will change to "java.lang.RuntimeException: Unable to load script. Make sure you're either running Metro (run 'npx react-native start') or that your bundle 'index.android.bundle' is packaged correctly for release."

My project is upgrade from 0.69.6 to 0.70.5

**Comment by tonydatw** [comment] 2022-12-15 07:52
@tomcheung1208 did you manage to solve it? @cortinico, any update on this?

**Comment by cortinico** [comment] 2022-12-15 13:24
> @cortinico, any update on this?

@tonydatw The update is that this issue is missing a reproducer. Without it we can't investigate further

**Comment by cortinico** [comment] 2023-01-19 10:35
This and all the "couldn't find DSO to load" bugs have been fixed in React Native 0.71.

The issue on previous versions was a "too agressive" cleanup logic in the `react.gradle` file.
In 0.71 the cleanup logic has been rewritten to be more Android friendly and is now living inside the React Native Gradle Plugin.

I'm closing this, please update to 0.71 and open new issue if the "couldn't find DSO to load" crash is still happening on 0.71+.

**Closed by cortinico** 2023-01-19 10:35 UTC
Labels: Platform: Android, Needs: Repro

**Comment by Vadko** [comment] 2023-01-27 17:51
> This and all the "couldn't find DSO to load" bugs have been fixed in React Native 0.71.
> 
> The issue on previous versions was a "too agressive" cleanup logic in the `react.gradle` file. In 0.71 the cleanup logic has been rewritten to be more Android friendly and is now living inside the React Native Gradle Plugin.
> 
> I'm closing this, please update to 0.71 and open new issue if the "couldn't find DSO to load" crash is still happening on 0.71+.

is there any way to patch 0.70.5 to fix that? We are using expo SDK and since there is highest possible version in expo sdK 47 - 0.70.5 it is not possible to upgrade

**Comment by cortinico** [comment] 2023-01-27 18:36
> is there any way to patch 0.70.5 to fix that? 

Sadly not. This change relies on a significant rewrite of our build logic and can't be easily backported.

**Comment by Vadko** [comment] 2023-01-27 19:27
> > is there any way to patch 0.70.5 to fix that? 
> 
> 
> 
> Sadly not. This change relies on a significant rewrite of our build logic and can't be easily backported.

:( so the only solution if this error happens is to wait for expo newer sdk version?

**Comment by bozaigao** [comment] 2023-02-19 03:47
Run ./gradlew clean then build again
