### ISSUE TITLE
[Xcode 11] [iOS 13] EXC_BAD_ACCESS in fishhook.c

### ISSUE THREAD

**Issue by chrisspankroy** [facebook/react-native#25182] opened 2019-06-06 22:28 UTC
# Bug

When running my app on an iPhone XR (iOS 13), the app immediately crashes with EXC_BAD_ACCESS. 

<img width="1440" alt="Screen Shot 2019-06-06 at 5 04 19 PM" src="https://user-images.githubusercontent.com/30426775/59069711-a6120880-887d-11e9-86a5-609178c6f4b1.png">

I can only reproduce this when running on a physical iPhone. iPad and simulator both work fine.

## Environment info

React native info output:

```bash
 info
  React Native Environment Info:
    System:
      OS: macOS 10.15
      CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
      Memory: 1.78 GB / 16.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 8.16.0 - ~/.nvm/versions/node/v8.16.0/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 11.0/11M336w - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.6 => 16.8.6
      react-native: ^0.59.9 => 0.59.9
```

Library version: 0.59.9

## Steps To Reproduce

Make a new React Native project with `react-native init` and run on device.

Describe what you expected to happen:

1. App to not crash immediately

## Reproducible sample code

[Here](https://github.com/chrisspankroy/crash_test) That's a link to a repo I just made for a test project.

EDIT: Fixed the link to the repo

**Comment by ryanoconnor7** [comment] 2019-06-10 03:58
I found a temporary (and terrible) workaround of simply commenting that line out 🙃

**Comment by chrisspankroy** [comment] 2019-06-10 16:15
What version of React Native are you using? There was a similar issue ( #25138 ) that was fixed in 59.9. I'm using 59.9 and after commenting out the line in `fishhook.c`, I can get the app to run fine. But, I'm willing to bet that's not the right solution 😕

**Comment by chrisspankroy** [comment] 2019-06-10 17:02
I might have a real fix for it. PR coming soon

**Comment by ryanoconnor7** [comment] 2019-06-10 23:32
Got it, thanks. Hopefully that fixes it. Sorry for asking this here but what should I do if I'm using expo and need to upgrade to 59.9?

**Comment by chrisspankroy** [comment] 2019-06-11 00:10
I’ve never used Expo, but my understanding of how it works is it can take about a month after a version of React Native comes out for it to be supported on Expo. The Expo SDK should support 59.9 in a few weeks

**Comment by ryanoconnor7** [comment] 2019-06-11 00:19
I’m seriously considering ditching it, haha

**Comment by mmmulani** [comment] 2019-06-12 13:22
this should be fixed by 46bdb4161c84b33f1d0612e9c7cdd824462a31fd, let me know if it doesn't work for you

**Closed by mmmulani** 2019-06-12 13:22 UTC
Labels: Bug, Platform: iOS

**Comment by chrisspankroy** [comment] 2019-06-12 14:15
Awesome, thanks!

**Comment by mjgallag** [comment] 2019-09-20 17:53
Does anyone understand why this crashes in production when all the references to `RCTReconnectingWebSocket` are in `DevSupport` classes? I ask because I'm trying to figure out if there is anything I can possibly do to address this issue from a javascript code push. Shot in the dark but if anyone has any ideas let me know, thanks!

**Comment by enaluz** [comment] 2019-10-15 04:18
I'm still getting this bug. Any updates on this?

**Comment by mmmulani** [comment] 2019-10-15 04:33
upgrade your version of RN, it was fixed months ago

**Comment by Mcebrera** [comment] 2019-10-21 21:18
@mmmulani What RN version fixed this? I'm on `0.59.10`

**Comment by mmmulani** [comment] 2019-10-21 21:35
v61.0 I believe is the first to have this fix

**Comment by nomoreboredom** [comment] 2019-10-25 13:36
I am also still on 0.59.10, needed to apply these manually to compile https://github.com/facebook/react-native/commit/46bdb4161c84b33f1d0612e9c7cdd824462a31fd

**Comment by xeric** [comment] 2019-10-28 15:20
For you guys who are still working on 0.59.10 and hard to apply [46bdb41](https://github.com/facebook/react-native/commit/46bdb4161c84b33f1d0612e9c7cdd824462a31fd) patch in to your local.
1. Go to ‘node_modules/react-native/Libraries/fishhook/fishhook.c' and delete whole method 'perform_rebinding_with_section'
2. Find all place in this file where used above method, remove lines.
3. run debug and you should see some error on unused variable because #2 lines removed
3. remove these unused variables
4. Product -> Clean Build Folder
5. run debug, it should work now
This quick and dirty fix may have some unknown issue, but at least it made my physical device debug mode back.

**Comment by ipenpen** [comment] 2019-12-06 05:34
I am using React Native 0.59.9, Xcode 11.2.1(11B500). I tried to reproduce this crash but could not.
It work fine in both simulator and real device(include iPhone XR iOS 13).

I have to decide to update to new React Native version or not.
Do you have any idea why I can not reproduce this crash?

**Comment by GleidsonDaniel** [comment] 2020-01-09 13:10
@xeric you saved my life!
The curious thing is that this error only happens on iphones 11, on inferior devices like X, the error does not happen ...

**Comment by meetyourdev** [comment] 2020-04-27 10:31
> For you guys who are still working on 0.59.10 and hard to apply [46bdb41](https://github.com/facebook/react-native/commit/46bdb4161c84b33f1d0612e9c7cdd824462a31fd) patch in to your local.
> Go to ‘node_modules/react-native/Libraries/fishhook/fishhook.c' and delete whole method 'perform_rebinding_with_section' content, keep the method definition.
> Save -> Done.

This still works in 2020

**Comment by IdrisHanafi** [comment] 2020-05-23 22:27
> The curious thing is that this error only happens on iphones 11, on inferior devices like X, the error does not happen ...

+1 This error occurred only on iPhone 11s. Worked on all other devices including emulators.

> v61.0 I believe is the first to have this fix

Oof that sucks because one of our dependencies max supported version as of now is 0.59.9
