### ISSUE TITLE
Setting modal visible to false not working

### ISSUE THREAD

**Issue by kelvinaliyanto** [facebook/react-native#10534] opened 2016-10-25 04:13 UTC
I have just upgraded my react-native from 0.29 to 0.35, but in my latest version, the modal seems to be not working. For example, when I call server I set the visible attribute to true, then when I get the response, I set the visible attribute to false, and then pop the navigator. However not only the modal persists on the page, it also persists in the page before even though that page does not even have any modal. I try to use my 0.29 version and it works just fine.

**Comment by lacker** [comment] 2016-10-25 04:16
Can you provide some sample code on rnplay.org that reproduces this problem?

**Comment by kelvinaliyanto** [comment] 2016-10-25 04:53
Hi @lacker I tried to create in rnplay.org but it works just fine. Anyway I am currently developing for the ios version.

**Comment by lacker** [comment] 2016-10-25 05:02
OK, so if you can't reproduce it on rnplay.org then I don't think I will be able to reproduce this either so I don't see how I can be helpful here. I am going to close this issue but if you do find a way to reproduce this bug please feel free to reopen this discussion.

**Closed by lacker** 2016-10-25 05:02 UTC
