### ISSUE TITLE
Style is not passed down to custom components

### ISSUE THREAD

**Issue by javorosas** [facebook/react-native#10031] opened 2016-09-21 18:51 UTC
Why do I have to explicitly pass the `style` prop to custom components? Is this by design?

Consider the following app

```jsx
import React from 'react';
import { View, StyleSheet, Text } from 'react-native';

const Component = () => {
  return (
    <View>
      <Text>This is a custom component</Text>
    </View>
  );
}

const App = () => {
  return (
    <View>
      <Component style={styles.component} />
      <Component style={styles.component} />
    </View>
  );
}

const styles = StyleSheet.create({
  component: {
    backgroundColor: '#f88',
    marginVertical: 10
  }
});

export default App;
```

I would intuitively expect to be styling the component's container `View` without explicitly passing the style as a prop. Is this intended?

**Comment by brunolemos** [comment] 2016-09-21 18:59
Yes this is by design. The `Component` must clearly specify the props it can receive, and it does not apply anything implicitly to its children.

**Comment by charpeni** [comment] 2016-09-21 19:27
@brunolemos has answered the question correctly, so I'll close this issue. Don't forget you can use [StackOverflow](http://stackoverflow.com/questions/tagged/react-native) for your question.

Besides, IMO you should use regular fonction instead of arrow function as they are anonymous, so you're relying on function name inference.

**Comment by charpeni** [comment] 2016-09-21 19:27
@facebook-github-bot answered

**Comment by facebook-github-bot-4** [comment] 2016-09-21 19:27
Closing this issue as @charpeni says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

**Closed by facebook-github-bot-4** 2016-09-21 19:27 UTC
Labels: Ran Commands

**Comment by javorosas** [comment] 2016-09-21 19:29
Ok, I get it. Just for future reference, this is what needs to be done to achieve the desired behavior:

```jsx
const Component = (props) => {
  return (
    <View {...props}>
      <Text>This is a custom component</Text>
    </View>
  );
}
```

**Comment by smitthakkar1** [comment] 2017-07-25 20:37
Still not getting the desired behavior.
Can I export a component with styles?
