### ISSUE TITLE
Inline image not animated when wrapped in a Text component

### ISSUE THREAD

**Issue by tikkichan4** [facebook/react-native#15686] opened 2017-08-29 04:07 UTC
I am using Fresco v1.0.1 (Latest version with React native supported).
It just works fine in IOS and Android when rendering the gif only.
Once the image is wrapped in a text component, it just dont worked. (The image component always display the first frame of gif, but not animated)

Please note that this bug is reported by other user before. But that issue is closed without situation.

**Comment by hramos** [comment] 2017-08-31 01:27
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-08-31 01:27 UTC
