### ISSUE TITLE
reaact native version 0.60. ++ new project error Failed to run jetifier. Run CLI with --verbose flag for more details.

### ISSUE THREAD

**Issue by sarunopassawas** [facebook/react-native#25669] opened 2019-07-16 04:57 UTC
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
error Failed to run jetifier. Run CLI with --verbose flag for more details.
Error: spawnSync C:\reactNative\moFCM\node_modules\jetifier\bin\jetify ENOENT
    at Object.spawnSync (internal/child_process.js:990:20)
    at spawnSync (child_process.js:601:24)
    at execFileSync (child_process.js:629:13)
    at Object.runAndroid [as func] (C:\reactNative\moFCM\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:101:41)
    at Command.handleAction (C:\reactNative\moFCM\node_modules\react-native\node_modules\@react-native-community\cli\build\cliEntry.js:160:21)
    at Command.listener (C:\reactNative\moFCM\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:189:13)
    at Command.parseArgs (C:\reactNative\moFCM\node_modules\commander\index.js:651:12)
    at Command.parse (C:\reactNative\moFCM\node_modules\commander\index.js:474:21)
    at setupAndRun (C:\reactNative\moFCM\node_modules\react-native\node_modules\@react-native-community\cli\build\cliEntry.js:210:24)

react-native run-android --no-jetifier work.
But I want to know if it will have any effect?

React Native version:
version 0.60. ++

**Comment by SistemasIntegrales** [comment] 2019-07-16 05:16
This is also happening to me, I updated everything today, even uninstalled and reinstalled to the latest versions of node and android, and I've already created to react-native apps.
Just doing `react-native init project`, then going to the directory of my project and executing `react-native run-android` and that's all it takes for that message to pop-up.
I understand Google just did a major update or at least a relevant update with AndroidX, and I'm sure we all will need to be sure our apps can run with this new update.

**Comment by janibhargav** [comment] 2019-07-16 05:42
you are right 
error An unexpected 
error occurred: "https://registry.yarnpkg.com/jetify: Not found".

**Comment by janibhargav** [comment] 2019-07-16 05:43
i think this is a bug, please open a bug report

**Comment by zhudan1027** [comment] 2019-07-16 06:13
I had the same problem.It worked yesterday.
Another post said use this command to start.
**react-native run-android --no-jetifier**

**Comment by janibhargav** [comment] 2019-07-16 06:25
temporary run with 
react-native run-android --no-jetifier

**Comment by yang200258** [comment] 2019-07-16 06:25
确实出错了，是因为react-native的更新问题吗？

**Comment by HamitEnes** [comment] 2019-07-16 07:41
#25667 issue related that

**Comment by Guyana345** [comment] 2019-07-16 08:07
still having the same issues
Another post said use this command to start.
react-native run-android --no-jetifier
this works fine but you can't keep running like this all the time 
i hope there will be a fix soon

**Comment by jin006s** [comment] 2019-07-16 08:28
same issues , please fix soon

**Comment by niedem** [comment] 2019-07-16 08:57
--no-jetifier doesnt work either if you have a lib that requires jetifier such as react-native-gesture-handler

**Comment by ShantkumarMethre** [comment] 2019-07-16 09:28
cmd react-native run-android --no-jetifier 
it will work

**Comment by narratones** [comment] 2019-07-16 09:42
I've just built from the latest and received no errors, as below:

`react-native init NewProject`

`npx react-native run-android`

This didn't start my metro builder, so in another terminal - 

`react-native start`

Then:

`npx react-native run-android`

Environment:

Node : v10.2.1
NPM/NPX: v6.9.0
Mac OSx

**Comment by thymikee** [comment] 2019-07-16 13:01
Duplicate of https://github.com/facebook/react-native/issues/25667

**Closed by thymikee** 2019-07-16 13:01 UTC
Labels: Bug

**Comment by wkwyatt** [comment] 2019-08-16 19:45
I am getting the error unknown option --no-jetifier

**Comment by thymikee** [comment] 2019-08-16 19:49
@wkwyatt Please [update the `@react-native-community/cli`](https://github.com/react-native-community/cli#updating-the-cli) to the latest version.

**Comment by bedus-creation** [comment] 2019-08-23 10:52
error: unknown option `--no-jetifier'

**Comment by gilsonjoanelo** [comment] 2019-09-27 11:22
The same problem occurred after upgrading to the latest versions, after several searches, got to the project link at npm, followed the step by step link below and solved the problem.

https://www.npmjs.com/package/jetifier

**Comment by juslin03** [comment] 2019-11-11 16:40
@narratones thank, this works for me

**Comment by o-pooja-o** [comment] 2020-01-28 11:43
> The same problem occurred after upgrading to the latest versions, after several searches, got to the project link at npm, followed the step by step link below and solved the problem.
> 
> https://www.npmjs.com/package/jetifier

how to implement these steps ...

**Comment by sohaib3335** [comment] 2021-03-12 22:07
Just make sure that you are in the main directory. i.e. root directory of your project. Trying to run 'npx react-native run-android' from any sub directory can cause this issue.

**Comment by pbdigital** [comment] 2021-04-22 02:59
> Just make sure that you are in the main directory. i.e. root directory of your project. Trying to run 'npx react-native run-android' from any sub directory can cause this issue.

Made this mistake by trying to run `npx react-native run-android`from the android folder. running from the root directory solved the problem.

Thanks
