### ISSUE TITLE
TextInput box with Limited height doesn't focus to end of line after input exceeds height (RN 47.1, 45.1)

### ISSUE THREAD

**Issue by gavin-gmlab** [facebook/react-native#15778] opened 2017-09-04 03:07 UTC
### Is this a bug report?

YES

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

YES

### Environment

1. `react-native -v`:
react-native-cli: 2.0.1
react-native: 0.47.1
2. `node -v`:
v7.10.1
3. `npm -v`:
4.2.0
4. `yarn --version`:

Then, specify:

- Target Platform:
iOS, Android - Problem only reproducable on Android right now.

- Development Operating System: MacOS 10.12, 

- Build tools: Android Studio 2.3.3

### Steps to Reproduce

1. Create a new project with create-react-native-app AwesomeProject
2. Change the code in App.js to the following (apologies for the styling)

`
import React from 'react';
import { StyleSheet, Text, View, TextInput, Platform } from 'react-native';

export default class App extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
      value: '',
      height: 20
    }
    this.onContentSizeChange = this.onContentSizeChange.bind(this)
  }
  onContentSizeChange(e) {
    const contentSize = e.nativeEvent.contentSize
    this.setState({height: contentSize.height > 100 ? 100 : contentSize.height})
    console.log(this.state.height)
  }

  render() {
    return (
      <View style={styles.container}>
        <View style={{flex:1}}>
          <Text>Open up App.js to start working on your app!</Text>
          <Text>Changes you make will automatically reload.</Text>
          <Text>Shake your phone to open the developer menu.</Text>
        </View>
        <TextInput
           placeholder = 'type your text here'
           multiline = {true}
           style = {[styles.textInput,{height: this.state.height, width: 200}]}
           value = {this.state.text}
           onContentSizeChange={(e)=> this.onContentSizeChange(e)}
           />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    paddingTop: 40,
    paddingHorizontal: 10
  },
  textInput: {
    marginLeft: 10,
    fontSize: 16,
    lineHeight: 18,
    marginTop: Platform.select({
      ios: 6,
      android: 0,
    }),
    marginBottom: Platform.select({
      ios: 5,
      android: 3,
    }),
  },
});
`

3. Run the app and start typing in the text input box until the whole text input box is filled and keep going. Past that point you can't see what you are typing any more.
4. This behaviour happens even if we replace the height with a static value (eg. 100) instead of this.state.height

### Expected Behavior

The focus of the text input should remain at the last character input.

### Actual Behavior

Focus of the text input is outside the visible area

![screen shot 2017-09-04 at 11 05 14 am](https://user-images.githubusercontent.com/20513400/30010252-12496c16-9161-11e7-93d9-d116dc6e11b5.png)

### Reproducible Demo

See the example code listed above.

**Comment by gavin-gmlab** [comment] 2017-09-07 05:05
No one else facing this problem?

**Comment by allpwrfulroot** [comment] 2017-09-12 02:47
Seeing something potentially related, I'm getting a weird `onContentSizeChange` event: the multiline TextInput's contentSize decides to increase as if it needs a new line, when the text has actually only reached ~60% of the width of a line. So my TextInput grows at very odd points and too much.

**Comment by gavin-gmlab** [comment] 2017-09-18 04:00
@allpwrfulroot, there was a bug reported about that and was supposedly fixed for 47.2. I'm seeing this problem only on Android btw and only if I limit the expanding input field to x lines by the code above. If I let the input box keep growing, no problem

**Comment by jamesreggio** [comment] 2017-09-21 23:52
I'm seeing this on Android, too.

**Comment by jamesreggio** [comment] 2017-09-21 23:52
Actually, duplicate of #12799.

**Comment by gavin-gmlab** [comment] 2017-09-22 06:36
@jamesreggio Yes, didn't see that before I submitted, even though I went through the TextInput issues before I submitted this one. So I'm not alone... So it's been broken for most of the 40+ versions of RN and hasn't been fixed...

**Comment by shergin** [comment] 2017-11-28 01:40
Duplicate of #12799.
And, I hope, 0bef872f3fc8b1cd78c574d03eacc886bef4e239 fixes that.

**Closed by shergin** 2017-11-28 01:40 UTC
Labels: Android
