### ISSUE TITLE
react-native-fcm:compileReleaseJavaWithJavac FAILED

### ISSUE THREAD

**Issue by piyush2468** [facebook/react-native#15710] opened 2017-08-30 13:30 UTC
![error](https://user-images.githubusercontent.com/18625797/29874653-10f7e022-8db5-11e7-8c75-34034f940b8a.png)
Hey i'm facing this issue can you guys give me suggestions?
Before you do i've already tried removing caches, downgrading react and the dependency so what else is there am i missing ?

**Comment by kelset** [comment] 2017-08-30 15:36
It looks like you are not using the latest version of `react-native-google-places`. Make sure you are on v2.4.2.

It's not a `react-native` issue per se.

**Comment by chirag04** [comment] 2017-08-30 16:41
closing as per above comment.

**Closed by chirag04** 2017-08-30 16:41 UTC

**Comment by piyush2468** [comment] 2017-08-31 06:10
You Guys are way quick to close this issue actually it's not the google places issue, it seems to be that i have installed the v2.4.2 of it and i've tried it like 10 times already.
please fix this issue.

**Comment by kelset** [comment] 2017-08-31 07:59
The issue is with `react-native-google-places` **for sure**. That's what the error message says. Again, go open an issue into that library; moreover, you didn't even comply with the issue template, so this issue would have been closed anyway.

**Comment by piyush2468** [comment] 2017-08-31 12:41
thanks a lot for the info as i'm very new to this platform.
I'll do that.
Thanks again.

**Comment by treily** [comment] 2018-05-05 09:45
5
