### ISSUE TITLE
pod install fails: Codegen issue (IOS)

### ISSUE THREAD

**Issue by Ammarlio** [facebook/react-native#45864] opened 2024-08-01 14:10 UTC
### Description

i am facing error after doing pod install

i removed node_modules, yarn.lock, reset cache, podfile.lock.

even after removing all of these still facing same issue

### Steps to reproduce

1. yarn install
2. cd ios
3. pod install

### React Native Version

0.74.1

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.1.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 110.41 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.7.1
    path: /opt/homebrew/bin/node
  Yarn:
    version: 3.6.4
    path: /usr/local/bin/yarn
  npm:
    version: 10.5.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK:
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: 2023.3 AI-233.14808.21.2331.11842104
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.22
    path: /usr/bin/javac
  Ruby:
    version: 3.3.0
    path: /opt/homebrew/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.74.1
    wanted: 0.74.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
[!] Invalid `Podfile` file: [!] /opt/homebrew/bin/node ./../node_modules/react-native/scripts/generate-codegen-artifacts.js -p /Users/myuser/Desktop/Projects/myApp/ios/.. -o /Users/myuser/Desktop/Projects/myApp/ios -t ios

[Codegen] Analyzing /Users/myuser/Desktop/Projects/myApp/package.json
[Codegen] Searching for codegen-enabled libraries in the app.
[Codegen] The "codegenConfig" field is not defined in package.json. Assuming there is nothing to generate at the app level.
[Codegen] Searching for codegen-enabled libraries in the project dependencies.
[Codegen] Found @react-native-async-storage/async-storage
[Codegen] Found @react-native-clipboard/clipboard
[Codegen] Found lottie-react-native
[Codegen] Found react-native
[Codegen] Found react-native-blob-util
[Codegen] Found react-native-bootsplash
[Codegen] Found react-native-date-picker
[Codegen] Found react-native-document-picker
[Codegen] Found react-native-gesture-handler
[Codegen] Found react-native-haptic-feedback
[Codegen] Found react-native-image-picker
[Codegen] Found react-native-localize
[Codegen] Found react-native-pager-view
[Codegen] CodegenConfig Deprecated Setup for react-native-pager-view.
    The configuration file still contains the codegen in the libraries array.
    If possible, replace it with a single object.
  
BEFORE:
    {
      // ...
      "codegenConfig": {
        "libraries": [
          {
            "name": "libName1",
            "type": "all|components|modules",
            "jsSrcsRoot": "libName1/js"
          },
          {
            "name": "libName2",
            "type": "all|components|modules",
            "jsSrcsRoot": "libName2/src"
          }
        ]
      }
    }

    AFTER:
    {
      "codegenConfig": {
        "name": "libraries",
        "type": "all",
        "jsSrcsRoot": "."
      }
    }
  
[Codegen] Found react-native-pdf
[Codegen] Found react-native-permissions
[Codegen] Found react-native-reanimated
[Codegen] Found react-native-safe-area-context
[Codegen] Found react-native-screens
[Codegen] Found react-native-share
[Codegen] Found react-native-svg
[Codegen] Found react-native-vector-icons
[Codegen] Found react-native-webview


[Codegen] >>>>> Searching for codegen-enabled libraries in react-native.config.js
[Codegen] Processing rnasyncstorage
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Supported Apple platforms: ios, macos, tvos, visionos for rnasyncstorage
[Codegen] Processing rnclipboard
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Supported Apple platforms: ios, macos, tvos, visionos for rnclipboard
[Codegen] Processing lottiereactnative
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Supported Apple platforms: ios, macos, tvos for lottiereactnative
[Codegen] Processing FBReactNativeSpec
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Processing rncore
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Processing ReactNativeBlobUtilSpec
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Supported Apple platforms: ios for ReactNativeBlobUtilSpec
[Codegen] Processing RNBootSplashSpec
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Supported Apple platforms: ios, tvos for RNBootSplashSpec
[Codegen] Processing RNDatePickerSpecs
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Supported Apple platforms: ios for RNDatePickerSpecs
[Codegen] Processing rndocumentpicker
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Supported Apple platforms: ios for rndocumentpicker
[Codegen] Processing rngesturehandler_codegen
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Supported Apple platforms: ios, macos, tvos, visionos for rngesturehandler_codegen
[Codegen] Processing RNHapticFeedbackSpec
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Supported Apple platforms: ios for RNHapticFeedbackSpec
[Codegen] Processing RNImagePickerSpec
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Supported Apple platforms: ios for RNImagePickerSpec
[Codegen] Processing RNLocalizeSpec
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Supported Apple platforms: ios, macos, tvos, visionos for RNLocalizeSpec
[Codegen] Processing RNCViewPager
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Supported Apple platforms: ios, visionos for RNCViewPager
[Codegen] Processing LEGACY_RNCViewPager
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Supported Apple platforms: ios, visionos for LEGACY_RNCViewPager
[Codegen] Processing rnpdf
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Supported Apple platforms: ios, tvos for rnpdf
[Codegen] Processing RNPermissionsSpec
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Supported Apple platforms: ios, tvos for RNPermissionsSpec
[Codegen] Processing rnreanimated
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Supported Apple platforms: ios, macos, tvos, visionos for rnreanimated
[Codegen] Processing safeareacontext
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Supported Apple platforms: ios, tvos, visionos for safeareacontext
[Codegen] Processing rnscreens
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Supported Apple platforms: ios, tvos, visionos for rnscreens
[Codegen] Processing RNShareSpec
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Supported Apple platforms: ios for RNShareSpec
[Codegen] Processing rnsvg
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Supported Apple platforms: ios, macos, tvos, visionos for rnsvg
[Codegen] Processing RNVectorIconsSpec
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Supported Apple platforms: ios, tvos, visionos for RNVectorIconsSpec
[Codegen] Processing RNCWebViewSpec
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Supported Apple platforms: ios, macos, visionos for RNCWebViewSpec
[Codegen] Generating Native Code for ios
[Codegen] Generated artifacts: /Users/myuser/Desktop/Projects/myApp/ios/build/generated/ios
[Codegen] Generating Native Code for ios
[Codegen] Generated artifacts: /Users/myuser/Desktop/Projects/myApp/ios/build/generated/ios
[Codegen] Generating Native Code for ios
[Codegen] Generated artifacts: /Users/myuser/Desktop/Projects/myApp/ios/build/generated/ios
[Codegen] Generating Native Code for ios
[Codegen] Generated artifacts: /Users/myuser/Desktop/Projects/myApp/ios/build/generated/ios
[Codegen] Generating Native Code for ios
[Codegen] Generated artifacts: /Users/myuser/Desktop/Projects/myApp/node_modules/react-native/ReactCommon
[Codegen] Generating Native Code for ios
[Codegen] Generated artifacts: /Users/myuser/Desktop/Projects/myApp/ios/build/generated/ios
[Codegen] Generating Native Code for ios
[Codegen] Generated artifacts: /Users/myuser/Desktop/Projects/myApp/ios/build/generated/ios
[Codegen] Generating Native Code for ios
[Codegen] Generated artifacts: /Users/myuser/Desktop/Projects/myApp/ios/build/generated/ios
[Codegen] Generating Native Code for ios
[Codegen] Generated artifacts: /Users/myuser/Desktop/Projects/myApp/ios/build/generated/ios
[Codegen] Generating Native Code for ios
[Codegen] Generated artifacts: /Users/myuser/Desktop/Projects/myApp/ios/build/generated/ios
[Codegen] Generating Native Code for ios
[Codegen] Done.
Error: Union types are unsupported in structs
    at StructCollector.process (/Users/myuser/Desktop/Projects/myApp/node_modules/@react-native/codegen/lib/generators/modules/GenerateModuleObjCpp/StructCollector.js:195:15)
    at getParamObjCType (/Users/myuser/Desktop/Projects/myApp/node_modules/@react-native/codegen/lib/generators/modules/GenerateModuleObjCpp/serializeMethod.js:261:23)
    at /Users/myuser/Desktop/Projects/myApp/node_modules/@react-native/codegen/lib/generators/modules/GenerateModuleObjCpp/serializeMethod.js:117:31
    at Array.forEach (<anonymous>)
    at serializeMethod (/Users/myuser/Desktop/Projects/myApp/node_modules/@react-native/codegen/lib/generators/modules/GenerateModuleObjCpp/serializeMethod.js:115:10)
    at serializeProperty (/Users/myuser/Desktop/Projects/myApp/node_modules/@react-native/codegen/lib/generators/modules/GenerateModuleObjCpp/index.js:118:14)
    at Array.forEach (<anonymous>)
    at generate (/Users/myuser/Desktop/Projects/myApp/node_modules/@react-native/codegen/lib/generators/modules/GenerateModuleObjCpp/index.js:133:10)
    at Object.generate (/Users/myuser/Desktop/Projects/myApp/node_modules/@react-native/codegen/lib/generators/RNCodegen.js:212:9)
    at Object.generateSpecFromInMemorySchema (/Users/myuser/Desktop/Projects/myApp/node_modules/react-native/scripts/codegen/generate-specs-cli-executor.js:78:22)
.

 #  from /Users/myuser/Desktop/Projects/myApp/ios/Podfile:63
 #  -------------------------------------------
 #    $RNFirebaseAsStaticFramework = true
 >    use_react_native!(
 #      :path => config[:reactNativePath],
 #  -------------------------------------------

[!] [Codegen] warn: using experimental new codegen integration
```

### Reproducer

https://github.com/Ammarlio/reproduce

**Comment by Ammarlio** [comment] 2024-08-01 15:43
@dkumar-carfax did you find any workaround?

**Comment by dkumar-carfax** [comment] 2024-08-01 15:43
No, not at the moment.

**Comment by dkumar-carfax** [comment] 2024-08-01 16:17
@Ammarlio I found the issue is in one of the packages, I am using, `react-native-haptic-feedback`. 

1. I removed the above package from `package.json`
2. Deleted the `node_modules` and `package-lock.json`
3. Deleted `ios/Pods` folder and `ios/Podfile.lock`
4. ran `npm install`
5. ran `pod install`

And it worked. I still need to figure out, how to fix issues with the above package.
I hope this helps.

**Comment by dkumar-carfax** [comment] 2024-08-01 16:18
Looks like people are already raised it here: https://github.com/mkuczera/react-native-haptic-feedback/issues/127

**Comment by dkumar-carfax** [comment] 2024-08-01 16:21
@Ammarlio Downgrading the package also works, that is a work around for me. for now I have version `2.2.0` for `react-native-haptic-feedback`

**Comment by Ammarlio** [comment] 2024-08-01 16:30
@dkumar-carfax thank you bro

**Comment by cortinico** [comment] 2024-08-01 18:06
Closing as conversation continues here:
https://github.com/mkuczera/react-native-haptic-feedback/issues/127

**Closed by cortinico** 2024-08-01 18:06 UTC
Labels: Needs: Triage :mag:, Newer Patch Available

**Comment by elite-mob** [comment] 2024-08-02 16:46
I am getting the same erorr and removed haptic library as well. But still the same...  

> pod install
Auto-linking React Native modules for target `project`: RNCAsyncStorage, RNDeviceInfo, RNFastImage, RNGestureHandler, RNImageCropPicker, RNReactNativeHapticFeedback, RNReanimated, RNScreens, react-native-blur, react-native-maps, and react-native-safe-area-context
Framework build type is static library
    [Codegen] Adding script_phases to React-Codegen.
    [Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
    
    [!] Invalid `Podfile` file: [!] /Users/admin/.nvm/versions/node/v20.16.0/bin/node ./../node_modules/react-native/scripts/generate-codegen-artifacts.js -p /Users/admin/Documents/GitHub/project-mobile/ios/.. -o /Users/admin/Documents/GitHub/project-mobile/ios -t ios
    
    [Codegen] Analyzing /Users/admin/Documents/GitHub/project-mobile/package.json
    [Codegen] Searching for codegen-enabled libraries in the app.
    [Codegen] The "codegenConfig" field is not defined in package.json. Assuming there is nothing to generate at the app level.
    [Codegen] Searching for codegen-enabled libraries in the project dependencies.
    [Codegen] Found @react-native-async-storage/async-storage
    [Codegen] Found @react-native-community/blur
    [Codegen] Found react-native
    [Codegen] Found react-native-gesture-handler
    [Codegen] Found react-native-haptic-feedback
    [Codegen] Found react-native-reanimated
    [Codegen] Found react-native-safe-area-context
    [Codegen] Found react-native-screens
    
    
    [Codegen] >>>>> Searching for codegen-enabled libraries in react-native.config.js
    [Codegen] Processing rnasyncstorage
    [Codegen] Searching for podspec in the project dependencies.
    [Codegen] Supported Apple platforms: ios, macos, tvos, visionos for rnasyncstorage
    [Codegen] Processing rnblurview
    [Codegen] Searching for podspec in the project dependencies.
    [Codegen] Supported Apple platforms: ios, tvos, visionos for rnblurview
    [Codegen] Processing FBReactNativeSpec
    [Codegen] Searching for podspec in the project dependencies.
    [Codegen] Processing rncore
    [Codegen] Searching for podspec in the project dependencies.
    [Codegen] Processing rngesturehandler_codegen
    [Codegen] Searching for podspec in the project dependencies.
    [Codegen] Supported Apple platforms: ios, macos, tvos, visionos for rngesturehandler_codegen
    [Codegen] Processing RNHapticFeedbackSpec
    [Codegen] Searching for podspec in the project dependencies.
    [Codegen] Supported Apple platforms: ios for RNHapticFeedbackSpec
    [Codegen] Processing rnreanimated
    [Codegen] Searching for podspec in the project dependencies.
    [Codegen] Supported Apple platforms: ios, macos, tvos, visionos for rnreanimated
    [Codegen] Processing safeareacontext
    [Codegen] Searching for podspec in the project dependencies.
    [Codegen] Supported Apple platforms: ios, tvos, visionos for safeareacontext
    [Codegen] Processing rnscreens
    [Codegen] Searching for podspec in the project dependencies.
    [Codegen] Supported Apple platforms: ios, tvos, visionos for rnscreens
    [Codegen] Generating Native Code for ios
    [Codegen] Generated artifacts: /Users/admin/Documents/GitHub/project-mobile/ios/build/generated/ios
    [Codegen] Generating Native Code for ios
    [Codegen] Generated artifacts: /Users/admin/Documents/GitHub/project-mobile/ios/build/generated/ios
    [Codegen] Generating Native Code for ios
    [Codegen] Generated artifacts: /Users/admin/Documents/GitHub/project-mobile/ios/build/generated/ios
    [Codegen] Generating Native Code for ios
    [Codegen] Generated artifacts: /Users/admin/Documents/GitHub/project-mobile/node_modules/react-native/ReactCommon
    [Codegen] Generating Native Code for ios
    [Codegen] Generated artifacts: /Users/admin/Documents/GitHub/project-mobile/ios/build/generated/ios
    [Codegen] Generating Native Code for ios
    [Codegen] Done.
    Error: Union types are unsupported in structs
        at StructCollector.process (/Users/admin/Documents/GitHub/project-mobile/node_modules/@react-native/codegen/lib/generators/modules/GenerateModuleObjCpp/StructCollector.js:195:15)
        at getParamObjCType (/Users/admin/Documents/GitHub/project-mobile/node_modules/@react-native/codegen/lib/generators/modules/GenerateModuleObjCpp/serializeMethod.js:261:23)
        at /Users/admin/Documents/GitHub/project-mobile/node_modules/@react-native/codegen/lib/generators/modules/GenerateModuleObjCpp/serializeMethod.js:117:31
        at Array.forEach (<anonymous>)
        at serializeMethod (/Users/admin/Documents/GitHub/project-mobile/node_modules/@react-native/codegen/lib/generators/modules/GenerateModuleObjCpp/serializeMethod.js:115:10)
        at serializeProperty (/Users/admin/Documents/GitHub/project-mobile/node_modules/@react-native/codegen/lib/generators/modules/GenerateModuleObjCpp/index.js:118:14)
        at Array.forEach (<anonymous>)
        at generate (/Users/admin/Documents/GitHub/project-mobile/node_modules/@react-native/codegen/lib/generators/modules/GenerateModuleObjCpp/index.js:133:10)
        at Object.generate (/Users/admin/Documents/GitHub/project-mobile/node_modules/@react-native/codegen/lib/generators/RNCodegen.js:212:9)
        at Object.generateSpecFromInMemorySchema (/Users/admin/Documents/GitHub/project-mobile/node_modules/react-native/scripts/codegen/generate-specs-cli-executor.js:78:22)
.

     #  from /Users/admin/Documents/GitHub/project-mobile/ios/Podfile:20
     #  -------------------------------------------
     #  
     >    use_react_native!(
     #      :path => config[:reactNativePath],
     #  -------------------------------------------
Couldn't install Pods. Updating the Pods project and trying again...

Here is my package.json

    {
      "name": "project",
      "version": "0.0.1",
      "private": true,
      "scripts": {
        "android": "react-native run-android",
        "ios": "react-native run-ios",
        "lint": "eslint .",
        "start": "react-native start",
        "test": "jest"
      },
      "dependencies": {
        "@gorhom/bottom-sheet": "^4.6.3",
        "@react-native-async-storage/async-storage": "^1.23.1",
        "@react-native-community/blur": "^4.4.0",
        "@react-native-material/core": "^1.3.7",
        "@react-navigation/bottom-tabs": "^6.6.0",
        "@react-navigation/native": "^6.1.17",
        "@react-navigation/stack": "^6.4.0",
        "@types/react-native": "^0.73.0",
        "axios": "^1.7.2",
        "chroma-js": "^2.4.2",
        "react": "18.2.0",
        "react-native": "^0.74.4",
        "react-native-action-sheet": "^2.2.0",
        "react-native-device-info": "^11.1.0",
        "react-native-fast-image": "^8.6.3",
        "react-native-gesture-handler": "^2.17.1",
        "react-native-haptic-feedback": "^2.2.0",
        "react-native-image-crop-picker": "^0.41.2",
        "react-native-maps": "^1.17.3",
        "react-native-reanimated": "^3.13.0",
        "react-native-root-toast": "^3.6.0",
        "react-native-safe-area-context": "^4.10.7",
        "react-native-screens": "^3.32.0"
      },
      "devDependencies": {
        "@babel/core": "^7.20.0",
        "@babel/plugin-proposal-export-namespace-from": "^7.18.9",
        "@babel/plugin-transform-class-properties": "^7.24.7",
        "@babel/plugin-transform-private-methods": "^7.24.7",
        "@babel/plugin-transform-private-property-in-object": "^7.24.7",
        "@babel/preset-env": "^7.20.0",
        "@babel/runtime": "^7.20.0",
        "@react-native/babel-preset": "0.74.86",
        "@react-native/eslint-config": "0.74.86",
        "@react-native/metro-config": "0.74.86",
        "@react-native/typescript-config": "0.74.86",
        "@tsconfig/react-native": "^3.0.5",
        "@types/chroma-js": "^2",
        "@types/jest": "^29.5.12",
        "@types/react": "^18.2.6",
        "@types/react-test-renderer": "^18.0.0",
        "babel-jest": "^29.6.3",
        "babel-plugin-module-resolver": "^5.0.2",
        "eslint": "^8.19.0",
        "jest": "^29.6.3",
        "metro-react-native-babel-preset": "^0.77.0",
        "prettier": "2.8.8",
        "react-test-renderer": "18.2.0",
        "reactotron-react-native": "^5.1.7",
        "typescript": "5.0.4"
      },
      "engines": {
        "node": ">=18"
      },
      "packageManager": "yarn@3.6.4"
    }

pod file is here:

    # Resolve react_native_pods.rb with node to allow for hoisting
    require Pod::Executable.execute_command('node', ['-p',
      'require.resolve(
        "react-native/scripts/react_native_pods.rb",
        {paths: [process.argv[1]]},
      )', __dir__]).strip
    
    platform :ios, min_ios_version_supported
    prepare_react_native_project!
    
    linkage = ENV['USE_FRAMEWORKS']
    if linkage != nil
      Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
      use_frameworks! :linkage => linkage.to_sym
    end
    
    target 'project' do
      config = use_native_modules!
    
      use_react_native!(
        :path => config[:reactNativePath],
        # An absolute path to your application root.
        :app_path => "#{Pod::Config.instance.installation_root}/.."
      )
    
      target 'projectTests' do
        inherit! :complete
        # Pods for testing
      end
    
      post_install do |installer|
        # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
        react_native_post_install(
          installer,
          config[:reactNativePath],
          :mac_catalyst_enabled => false,
          # :ccache_enabled => true
        )
      end
    end

**Comment by Ammarlio** [comment] 2024-08-05 06:55
> > Updating
> 
> Please were you able have it fixed

Update react-native-haptic-feedback to 2.3.1-next.0, and watch the library for any further updates.

**Comment by PierreCapo** [comment] 2024-08-05 11:44
> > > Updating
> > 
> > 
> > Please were you able have it fixed
> 
> Update react-native-haptic-feedback to 2.3.1-next.0, and watch the library for any further updates.

Many thanks for the follow-up @Ammarlio , your solution works!

**Comment by sandeepmansotra** [comment] 2024-08-08 15:49
Yes removing react-native-haptic-feedback will fix the issue

**Comment by bogdanovic91** [comment] 2024-08-20 11:19
the same issue and I do not use react-native-haptic-feedback... do you maybe know in which other library can the problem be?


[!] Invalid `Podfile` file: [!] /Users/bogdanovicn/.nvm/versions/node/v18.17.0/bin/node ./../node_modules/react-native/scripts/generate-codegen-artifacts.js -p /Users/bogdanovicn/projects/brand_mobile_app/ios/.. -o /Users/bogdanovicn/projects/brand_mobile_app/ios -t ios

[Codegen] Analyzing /Users/bogdanovicn/projects/brand_mobile_app/package.json
[Codegen] Searching for codegen-enabled libraries in the app.
[Codegen] Found brand_mobile_app
[Codegen] Searching for codegen-enabled libraries in the project dependencies.
[Codegen] Found @react-native-async-storage/async-storage
[Codegen] Found @react-native-community/blur
[Codegen] Found react-native
[Codegen] Found react-native-date-picker
[Codegen] Found react-native-gesture-handler
[Codegen] Found react-native-image-picker
[Codegen] Found react-native-localization-settings
[Codegen] Found react-native-mmkv
[Codegen] Found react-native-permissions
[Codegen] Found react-native-reanimated
[Codegen] Found react-native-safe-area-context
[Codegen] Found react-native-screens
[Codegen] Found react-native-svg
[Codegen] Found react-native-webview


[Codegen] >>>>> Searching for codegen-enabled libraries in react-native.config.js
[Codegen] Done.
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at Object.join (node:path:1171:7)
    at generateSchemaInfo (/Users/bogdanovicn/projects/brand_mobile_app/node_modules/react-native/scripts/codegen/generate-artifacts-executor.js:392:40)
    at Array.map (<anonymous>)
    at generateSchemaInfos (/Users/bogdanovicn/projects/brand_mobile_app/node_modules/react-native/scripts/codegen/generate-artifacts-executor.js:449:20)
    at Object.execute (/Users/bogdanovicn/projects/brand_mobile_app/node_modules/react-native/scripts/codegen/generate-artifacts-executor.js:653:27)
    at Object.<anonymous> (/Users/bogdanovicn/projects/brand_mobile_app/node_modules/react-native/scripts/generate-codegen-artifacts.js:31:10)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10) {
  code: 'ERR_INVALID_ARG_TYPE'
}
.

 #  from /Users/bogdanovicn/projects/brand_mobile_app/ios/Podfile:75
 #  -------------------------------------------
 #  
 >    use_react_native!(
 #      :path => config[:reactNativePath],
 #  -------------------------------------------

**Comment by bogdanovic91** [comment] 2024-08-20 13:00
Update: the issue was in https://www.npmjs.com/package/react-native-localization?activeTab=readme package

https://github.com/jakex7/react-native-localization-settings/pull/6/files

**Comment by ucheNkadiCode** [comment] 2024-08-23 03:48
> > > > Updating
> > > 
> > > 
> > > Please were you able have it fixed
> > 
> > 
> > Update react-native-haptic-feedback to 2.3.1-next.0, and watch the library for any further updates.
> 
> Many thanks for the follow-up @Ammarlio , your solution works!

They now have version 2.3.1 which is the newest. -> this was an issue affecting me once I upgraded to react native 75.1

**Comment by Mihai-github** [comment] 2024-10-10 16:39
I'm getting the same error but not running the react-native-haptic-feedback package

**Comment by pistonsky** [comment] 2025-09-30 07:06
In my case I was able to fix this issue by patching one of the libraries (the one that appeared in error logs). I had to change all type declarations that were declared as union types (like `type A = 'x' | 'y'`) to enums. So just check what library is mentioned in the error logs, and then check its source code - ts files.
