### ISSUE TITLE
Codegen: Int32 generate double on Java

### ISSUE THREAD

**Issue by mensonones** [facebook/react-native#45659] opened 2024-07-25 04:19 UTC
### Description

I'm trying to create a turbo module. Example below:

```js 
import type { TurboModule } from 'react-native/Libraries/TurboModule/RCTExport';
import { TurboModuleRegistry } from 'react-native';
import { Int32 } from 'react-native/Libraries/Types/CodegenTypes';

export interface Spec extends TurboModule {
    startSyncService(intervalTimeSync: Int32): void;
 }
   ```
   
However, I get the following error:

error: FastSellerModule is not abstract and does not override abstract method startSyncService(double) in NativeFastSellerSpec

When looking at the file **GenerateModuleJavaSpec.js**

![image](https://github.com/user-attachments/assets/7a143a35-6bd6-47d6-90e2-e83f6c8f080c)

I'm confused. How can I work with int?

### Steps to reproduce

1 - Create Turbo MModule and method work with int type
2 - Try add Turbo Module in Your React Native project version 0.73.9 
3 - Run your project and get error

### React Native Version

0.73.9

### Affected Platforms

Runtime - Android

### Areas

Codegen

### Output of `npx react-native info`

```text
System:
  OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
  CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
  Memory: 13.43 GB / 31.12 GB
  Shell:
    version: 5.1.16
    path: /bin/bash
Binaries:
  Node:
    version: 20.12.2
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.22
    path: /usr/local/bin/yarn
  npm:
    version: 10.5.0
    path: /usr/local/bin/npm
  Watchman:
    version: 4.9.0
    path: /usr/bin/watchman
SDKs:
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.9
    wanted: ^0.73.7
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
```

### Stacktrace or Logs

```text
node_modules/rtn-fastseller/android/src/main/java/br/com/polibrasnet/libfastseller/interfaces/FastSellerModule.java:91: error: FastSellerModule is not abstract and does not override abstract method startSyncService(double) in NativeFastSellerSpec
public class FastSellerModule extends NativeFastSellerSpec {
```

### Reproducer

https://github.com/mensonones/RnNewArchBugReproducer

**Comment by cortinico** [comment] 2024-07-25 10:48
This is basically a duplicate of:
- https://github.com/facebook/react-native/issues/44963

Long story short: in the past we added `Int32` support for Codegen but the implementation was not complete so we had to revert it.

We're probably going to add `Int32` support in the future (cc @dmytrorykun)

**Comment by mensonones** [comment] 2024-07-25 11:31
Got it! Thanks for the reply, @cortinico

**Closed** 2024-07-25 11:31 UTC
Labels: Type: Enhancement, Tech: Codegen, Type: New Architecture
