### ISSUE TITLE
Not Support iOS7.x ,Crash

### ISSUE THREAD

**Issue by tiger8888** [facebook/react-native#9631] opened 2016-08-29 07:22 UTC
```objc
- (NSURLSessionDataTask *)sendRequest:(NSURLRequest *)request
                         withDelegate:(id<RCTURLRequestDelegate>)delegate
{
  // Lazy setup
  if (!_session && [self isValid]) {

    NSOperationQueue *callbackQueue = [NSOperationQueue new];
    callbackQueue.maxConcurrentOperationCount = 1;
  // underlyingQueue only support iOS8+
    callbackQueue.underlyingQueue = [[_bridge networking] methodQueue];
    NSURLSessionConfiguration *configuration = [NSURLSessionConfiguration defaultSessionConfiguration];
    _session = [NSURLSession sessionWithConfiguration:configuration
                                             delegate:self
                                        delegateQueue:callbackQueue];

    _delegates = [[NSMapTable alloc] initWithKeyOptions:NSPointerFunctionsStrongMemory
                                           valueOptions:NSPointerFunctionsStrongMemory
                                               capacity:0];
  }
```

**Comment by hramos** [comment] 2016-09-07 19:55
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but we can reopen if additional information is provided. Thanks!

**Closed by hramos** 2016-09-07 19:55 UTC

**Comment by Ferb2012** [comment] 2016-09-20 10:38
I have the same problem when I run my project on device iOS7.1.1, RN0.33.0.
When run to

`> callbackQueue.underlyingQueue = [[_bridge networking] methodQueue]`

It will throw an error like this:

> 2016-09-20 17:18:58.332 xxx[926:4807] -[NSOperationQueue setUnderlyingQueue:]: unrecognized selector sent to instance 0x16740100
> 2016-09-20 17:18:59.405 xxx[926:60b] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSOperationQueue setUnderlyingQueue:]: unrecognized selector sent to instance 0x16740100'
> *** First throw call stack:
> (0x2ded1fd3 0x3861cccf 0x2ded5967 0x2ded4253 0x2de237b8 0x147327 0x13cdf5 0x1309e7 0x38b04833 0x38b0af11 0x38b0ac97 0x38b0ba45 0x38b0bd29 0x38c46bd3 0x38c46a98)
> libc++abi.dylib: terminating with uncaught exception of type NSException
> 

Thank you!

**Comment by JuliusMalisauskasDB** [comment] 2016-09-30 10:25
We have the same issue on 0.33. 
Any news on fixing this?

**Comment by chirag04** [comment] 2016-09-30 11:26
RN has dropped support for ios 7 on master already.
