### ISSUE TITLE
incorrect rows reported in onChangeVisibleRows

### ISSUE THREAD

**Issue by dmueller39** [facebook/react-native#7360] opened 2016-05-03 17:13 UTC
There is a bug in onChangeVisibleRows when the renderSeparator is not null. The _updateVisibleRows function does not account for the presence of separator frames in the _childFrames array.

![yeeqnmvmif](https://cloud.githubusercontent.com/assets/9422359/14515342/38543952-01c7-11e6-984c-7c1a3fc3d820.gif)

Built using https://gist.github.com/dmueller39/f95028f6fe8bd251944bb604e51f18b2

There is a PR for this already, but I figured I needed to open an issue to give it more visibility:
https://github.com/facebook/react-native/pull/6965

**Comment by damusnet** [comment] 2016-05-05 21:17
@facebook-github-bot duplicate #6702

**Comment by facebook-github-bot-5** [comment] 2016-05-05 21:22
@damusnet tells me this issue is a duplicate of #6702. Let's discuss there, closing this one.

**Closed by facebook-github-bot-5** 2016-05-05 21:22 UTC
Labels: Ran Commands
