### ISSUE TITLE
NDK build fail ?! Win7 64 + android-ndk-r10e

### ISSUE THREAD

**Issue by lhholylight** [facebook/react-native#12968] opened 2017-03-16 03:58 UTC
Information:Gradle tasks [clean, :app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies, :app:compileDebugSources, :app:compileDebugAndroidTestSources, :app:compileDebugUnitTestSources, :ReactAndroid:generateDebugSources, :ReactAndroid:mockableAndroidJar, :ReactAndroid:prepareDebugUnitTestDependencies, :ReactAndroid:generateDebugAndroidTestSources, :ReactAndroid:compileDebugSources, :ReactAndroid:compileDebugUnitTestSources, :ReactAndroid:compileDebugAndroidTestSources]
D:\Android\sdk\android-ndk-r10e\build\core\prebuilt-library.mk
Error:(45) *** Android NDK: Aborting    .  Stop.
Error:Execution failed for task ':ReactAndroid:cleanReactNdkLib'.
> Process 'command 'D:\Android\sdk\android-ndk-r10e\ndk-build.cmd'' finished with non-zero exit value 2
Information:BUILD FAILED
Information:Total time: 1.95 secs
Information:2 errors
Information:0 warnings
Information:See complete output in console

**Comment by hramos** [comment] 2017-03-16 18:19
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-03-16 18:19 UTC
