### ISSUE TITLE
[Android]java.lang.IllegalArgumentException: method com.facebook.react.uimanager.LayoutShadowNode.setWidth argument 1 has type float, got null

### ISSUE THREAD

**Issue by Ray-Ni** [facebook/react-native#15225] opened 2017-07-27 06:38 UTC
When two instance of ReactInstanceManager work in the same time， there is a trouble:

```java
07-27 14:27:23.009 18792-18879/com.ecovacs.ecosphere E/unknown:ViewManager: Error while updating prop width
                                                                            java.lang.IllegalArgumentException: method com.facebook.react.uimanager.LayoutShadowNode.setWidth argument 1 has type float, got null
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:105)
                                                                                at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:148)
                                                                                at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:52)
                                                                                at com.facebook.react.uimanager.ReactShadowNode.updateProperties(ReactShadowNode.java:258)
                                                                                at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:184)
                                                                                at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:235)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
                                                                                at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
                                                                                at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                                at android.os.Handler.handleCallback(Handler.java:743)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                                at android.os.Looper.loop(Looper.java:150)
                                                                                at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                                at java.lang.Thread.run(Thread.java:833)
```

Follow is some code in [ViewManagersPropertyCache](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/uimanager/ViewManagersPropertyCache.java):
```java
    // The following Object arrays are used to prevent extra allocations from varargs when we call
    // Method.invoke. It's safe for those objects to be static as we update properties in a single
    // thread sequentially
    private static final Object[] VIEW_MGR_ARGS = new Object[2];
    private static final Object[] VIEW_MGR_GROUP_ARGS = new Object[3];
    private static final Object[] SHADOW_ARGS = new Object[1];
    private static final Object[] SHADOW_GROUP_ARGS = new Object[2];
```
use static for `VIEW_MGR_ARGS` and `VIEW_MGR_GROUP_ARGS` is safe, because update view always in UI thread。

but static for `SHADOW_ARGS` and `SHADOW_GROUP_ARGS` is unsafe,  shadow node is upateed in deamon thread。

Well, remove static is not safe, either .  UIImplementation always use same PropSetter for same ShadowNode class and same property

**Comment by hramos** [comment] 2017-07-27 16:45
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-07-27 16:45 UTC

**Comment by SinLucifer** [comment] 2017-08-28 08:07
I meet the same problem, can you tell me more details?

**Comment by jabajaj** [comment] 2017-10-26 05:11
I'm also seeing this issue, would be nice to know how to go about resolving it.

**Comment by hramos** [comment] 2017-10-27 19:08
Please submit a new issue and make sure it fills out the template as advised above.

**Comment by wv1124** [comment] 2018-04-19 02:01
SDK_INT = 26
PRODUCT = vbox86p
MODEL = Google Pixel - 8.0 - API 26 - 1080x1920
versionName = 5.9.0
versionCode = 260
Thread Name: mqt_native_modules
com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'flex' in shadow node of type: RCTView
	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:116)
	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:154)
	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:58)
	at com.facebook.react.uimanager.ReactShadowNode.updateProperties(ReactShadowNode.java:272)
	at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:197)
	at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:249)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:363)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:166)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
	at android.os.Looper.loop(Looper.java:164)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalArgumentException: method com.facebook.react.uimanager.LayoutShadowNode.setFlex argument 1 has type float, got null
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:105)
	... 15 more

**Comment by kinglong123** [comment] 2018-05-09 09:08
I meet the same problem，
The native component is placed on the tab of two React-native pages, and then clicks two tab quickly.
