### ISSUE TITLE
It would always use 0.7 version when we are using --template

### ISSUE THREAD

**Issue by dotku** [facebook/react-native#34681] opened 2022-09-13 20:21 UTC
### Description

I create a project with command `npx react-native init AwesomeTSProject --version 0.64.2 --template react-native-template-typescript` it always using 0.70.0 even I specify the version to 0.64.2.

### Version

0.70

### Output of `npx react-native info`

System:
    OS: macOS 12.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 133.19 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.19.3 - ~/.nvm/versions/node/v14.19.3/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.12.1 - ~/.nvm/versions/node/v14.19.3/bin/npm
    Watchman: 2022.08.08.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 29, 30, 31, 32
      Build Tools: 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0
      System Images: android-28 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8512546
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /Library/Java/JavaVirtualMachines/jdk-11.0.15.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

create a project with command `npx react-native init AwesomeTSProject --version 0.64.2 --template react-native-template-typescript`

### Snack, code example, screenshot, or link to a repository

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/1519232/190001530-3e31873a-ce67-4cb0-aed1-00750a13dc18.png">

**Comment by billnbell** [comment] 2022-09-14 02:50
Yep same thing happens for me.

**Comment by kelset** [comment] 2022-09-14 13:08
cc @radko93 @thymikee

**Comment by skdrew** [comment] 2022-09-14 17:30
This is because the latest typescript-template is always set in parity with the latest RN version. To use an older version of RN, you need to use an older template as per the instructions in the documentation:

For example, to use 0.64 you'd need to use v6.6.5
```
npx react-native init MyApp --template react-native-template-typescript@6.6.5
```

**Comment by radko93** [comment] 2022-09-15 12:05
As @skdrew, you can find the compatibility table here https://github.com/react-native-community/react-native-template-typescript#react-native--template-version

**Comment by cortinico** [comment] 2022-09-15 12:37
This is an 'issue' of the CLI:
- https://github.com/react-native-community/cli/issues/1636#issue-1289615381

Essentially, the `--template` overrides your `--version` command. I believe we might want to output a warning in this case, but that's the intended behavior.

I'm closing this 👍

**Closed by cortinico** 2022-09-15 12:37 UTC
Labels: 💻CLI, Resolution: Answered
