### ISSUE TITLE
Opening Warning / Yellow Box details ui spikes CPU usage in iOS

### ISSUE THREAD

**Issue by IljaDaderko** [facebook/react-native#22150] opened 2018-11-05 15:19 UTC
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 51.45 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.11.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: 16.4.18 => 16.4.18 
      @types/react-native: 0.57.7 => 0.57.7 
      react: 16.7.0-alpha.0 => 16.7.0-alpha.0 
      react-native: 0.57.4 => 0.57.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

## Description
Opening / Expanding warning notification to view fullscreen message causes massive CPU spike that persists and starts heating up my mac until that view is closed.

**Just warning notification**

<img width="793" alt="screenshot 2018-11-05 at 17 17 02" src="https://user-images.githubusercontent.com/3154053/48006690-ae0a9e00-e11e-11e8-9d17-a429ca3f1888.png">

**Viewing full details**

<img width="887" alt="screenshot 2018-11-05 at 17 21 11" src="https://user-images.githubusercontent.com/3154053/48006952-3b4df280-e11f-11e8-8457-af0d95c9021e.png">

## Reproducible Demo
Simply add `console.warn("Test")` anywhere in your application and open details view.

**Comment by orta** [comment] 2019-03-19 12:38
This was definitely happening to me on a production build of RN, but when I tested in master on RNTester I couldn't repro. 

0.59:
<img width="1424" alt="Screen Shot 2019-03-19 at 12 22 56 PM" src="https://user-images.githubusercontent.com/49038/54606499-ee224b80-4a43-11e9-95ab-9a3da9dbc7d0.png">

Master:
<img width="1473" alt="Screen Shot 2019-03-19 at 12 37 37 PM" src="https://user-images.githubusercontent.com/49038/54606510-f5e1f000-4a43-11e9-918b-d3a82bd631e8.png">

**Comment by cpojer** [comment] 2019-03-26 20:23
Closing as it isn't happening on master any more. Happy to reopen if it is still an issue.

**Closed by cpojer** 2019-03-26 20:23 UTC
Labels: Follow Up, Platform: iOS, Type: Bug Report

**Comment by ravirajn22** [comment] 2019-09-11 07:21
The issue still occurs in 0.60.5 version of react-native, it wont happen every time but 40% of the time. When it happens you can see the yellow box at the bottom vibrating(small but visible). Its a serious issue where it pushes the mac to over 200% CPU usage, if not careful could seriously affect machines long time performance. Tested on emulator iPhone Xr in a new project. Not attaching image because its easily reproducible.  @cpojer
