### ISSUE TITLE
array to ListView with Render and bind not working just giving result blank   

### ISSUE THREAD

**Issue by ashikjs** [facebook/react-native#13633] opened 2017-04-24 01:13 UTC
This is my code it's not working , give me blank result ...

```
`import React, {Component} from 'react';
import {AppRegistry, ListView, Text, View, StyleSheet} from 'react-native';
const users = [
    {name: 'John Doe'},
    {name: 'Brad Traversy'},
    {name: 'Steve Smith'},
    {name: 'Janet Williams'},
    {name: 'Ashik   Billa'}
];

export default class Component4 extends Component {
    constructor() {
        super();
        const ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2});
        this.state = {
            userDataSource: ds.cloneWithRows([users]),
        };
    }

    renderRow(user, sectionId, rowId, highlightRow) {
        console.log(user.name);
        return (
            <View>
                <Text>{user.name}</Text>
            </View>

        )
    }

    render() {
        return (
            <ListView
                dataSource={this.state.userDataSource}
                renderRow={this.renderRow.bind(this)}
            />
        );
    }
}


AppRegistry.registerComponent('Component4', () => Component4);

`
```

**Comment by hramos** [comment] 2017-04-25 13:20
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-04-25 13:20 UTC
