### ISSUE TITLE
Trying to add unknown view tag

### ISSUE THREAD

**Issue by wj495175289** [facebook/react-native#14944] opened 2017-07-11 11:33 UTC
Is this a bug report?

Yes

Have you read the Bugs section of the Contributing to React Native Guide?

Yes

Environment

react-native -0.43.4:
node -6.9.1:
npm -3.10.8:
yarn --version (if you use Yarn):
Then, specify:

Target Platform (e.g. iOS, Android): Android
Development Operating System (e.g. macOS Sierra, Windows 10): Mac OS
Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant):
Android Studio SDK version 24
Steps to Reproduce

(Write your steps here:)

1.Even now, can not reproduce, only to see the online error log
2. com.facebook.react.uimanager.IllegalViewOperationException: Trying to add unknown view tag: 682
3.How to find where the problem occurred? the tag? but how to find in js file?

Expected Behavior

(Write what you thought would happen.)

Actual Behavior

(Write what happened. Add screenshots!)

Not necessarily now，Online crash

com.facebook.react.uimanager.IllegalViewOperationException: Trying to add unknown view tag: 769
	at com.facebook.react.uimanager.UIImplementation.setChildren(UIImplementation.java:388)
	at com.facebook.react.uimanager.UIManagerModule.setChildren(UIManagerModule.java:326)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:345)
	at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:141)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
	at android.os.Looper.loop(Looper.java:146)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
	at java.lang.Thread.run(Thread.java:841)

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by hramos** [comment] 2017-07-11 17:01
I'm closing this as the author states it cannot be reproduced. In general, debugging crashes shown in logs that can't be reproduced locally is not something that can be handled nicely here in this issue repo. I'm not saying the problem is not there - however I believe it's best to wait until this can be reproduced locally before opening an issue. Thanks for your understanding!

**Closed by hramos** 2017-07-11 17:01 UTC

**Comment by diegocouto** [comment] 2017-07-22 03:35
I'm also experiencing this issue. It seems to be already discussed on [#13984](https://github.com/facebook/react-native/issues/13984).

Using LayoutAnimation on Android with react-native version prior to 0.45 is probably leading to this problem.

**Comment by nikhilag** [comment] 2017-10-30 06:44
I am still seeing this issue in 0.49.3:-
`
10-30 10:57:15.239 8499-8499/? E/UncaughtException: com.facebook.react.uimanager.IllegalViewOperationException: Trying to add unknown view tag: 13
                                                     detail: View tag:24
                                                      children(2): [
                                                    8,10,
                                                     ],
                                                      viewsToAdd(1): [
                                                    [2,13],
                                                     ],
                                                    
                                                        at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:388)
                                                        at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:180)
                                                        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:815)
                                                        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:922)
                                                        at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:47)
                                                        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:982)
                                                        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
                                                        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136)
                                                        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:941)
                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:755)
                                                        at android.view.Choreographer.doFrame(Choreographer.java:687)
                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:929)
                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                        at android.os.Looper.loop(Looper.java:154)
                                                        at android.app.ActivityThread.main(ActivityThread.java:6334)
                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
`

**Comment by hramos** [comment] 2017-10-30 16:55
This issue is closed, I recommend opening a new issue.

**Comment by a6051529** [comment] 2017-12-17 08:38
@hramos  It's a random crash that occurs 10% of the time when called in the runApplication method in Libraries / ReactNative / AppRegistry.js，and I get a crash report that looks like this.
![image](https://user-images.githubusercontent.com/7309118/34077851-bd016d82-e348-11e7-994b-4a57a2947f0e.png)

**Comment by filipef101** [comment] 2018-02-05 13:00
Any update? I'm on a recent fork done from wix master

**Comment by hpyfei** [comment] 2018-02-05 13:24
i have the same problem

**Comment by GianniGM** [comment] 2018-02-14 11:59
Same problem

**Comment by filipef101** [comment] 2018-02-14 12:02
I solved with this I think, https://github.com/reyalpsirc/react-native-navigation/commit/a0ea2013920d4d9f2356acf644b1aaf5b57c9b8d

**Comment by filipef101** [comment] 2018-02-14 12:02
just apply that patch https://github.com/reyalpsirc/react-native-navigation/commit/a0ea2013920d4d9f2356acf644b1aaf5b57c9b8d.patch

**Comment by SudoPlz** [comment] 2018-06-07 11:39
Duplicate of https://github.com/facebook/react-native/issues/17178#issuecomment-394662148
