### ISSUE TITLE
Error: Expected "/*" or ";" but "\"" found. 

### ISSUE THREAD

**Issue by damathryx** [facebook/react-native#12969] opened 2017-03-16 07:08 UTC
While trying to link libraries `react-native link` I'm getting this error:

![screen shot 2017-03-16 at 3 06 06 pm](https://cloud.githubusercontent.com/assets/14576761/23985480/5095d8bc-0a5a-11e7-97be-9c711d2591bb.png)

react-native-cli: 2.0.1
react-native: 0.42

**Comment by hramos** [comment] 2017-03-16 18:19
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-03-16 18:19 UTC
