### ISSUE TITLE
[Image] 0.8.0-rc.2 Appearing 1px border When the image is scaled.

### ISSUE THREAD

**Issue by cssoul** [facebook/react-native#2099] opened 2015-07-23 09:20 UTC
I should display brand images in box, the images size is 186x120, But it's too big,so I use resizeMode:Image.resizeMode.contain to control. 
However, If you're using iPhone 6Plus, it shows the following appearance.:sob:  Who has met this problem,Seeking solutions.

![error pic](https://github.com/cssoul/react-native-trade/blob/master/demo3/error.jpg?raw=true)

This is the demo:
[https://github.com/cssoul/react-native-trade/blob/master/demo3/brands.js](https://github.com/cssoul/react-native-trade/blob/master/demo3/brands.js)

**Comment by grabbou** [comment] 2015-07-24 07:06
Duplicate of my own #1870

**Comment by brentvatne** [comment] 2015-07-24 07:07
Thanks @grabbou!

**Closed by brentvatne** 2015-07-24 07:07 UTC
