### ISSUE TITLE
Picker scrolling and selecting issue on iOS devices.

### ISSUE THREAD

**Issue by RD1991** [facebook/react-native#7578] opened 2016-05-16 05:16 UTC
Hi There, 

Im facing issue while using more than 1 'Picker' on iOS device. Alignment is being broken when I use container property flexDirection as 'row'. 

pickerWrapper:{
    flex:1,
    backgroundColor:'gray',
    flexDirection:'row',
    justifyContent:'flex-start',
  },

picker:{
    flex:1,
    alignSelf:'center',
  },

Adding demo video so the issue will be more clearer. This issue might be copy of [react-native-open-issue](https://github.com/facebook/react-native/issues/1587). 

[Picker_Issue.zip](https://github.com/facebook/react-native/files/265582/Picker_Issue.zip)

**Comment by DanielMSchmidt** [comment] 2016-05-17 09:22
@facebook-github-bot duplicate 1587

**Comment by DanielMSchmidt** [comment] 2016-05-17 13:43
@facebook-github-bot duplicate #1587

**Comment by facebook-github-bot-2** [comment] 2016-05-17 13:43
@DanielMSchmidt tells me this issue is a duplicate of #1587. Let's discuss there, closing this one.

**Closed by facebook-github-bot-2** 2016-05-17 13:43 UTC
Labels: Ran Commands
