### ISSUE TITLE
[0.60.0] Fresh install : 'cxxreact/ModuleRegistry.h' file not found

### ISSUE THREAD

**Issue by psyzz** [facebook/react-native#25480] opened 2019-07-03 20:05 UTC
When running an iOS fresh app with react-native 0.60.0 the build failed with this error:

``'cxxreact/ModuleRegistry.h' file not found``

macOS Mojave 10.14.5
xCode 10.2.1

React Native version:
react-native-cli: 2.0.1
react-native: 0.60.0

## Steps To Reproduce

1. react-native init projectname
2. open . xcworkspace
3. hit run
=> error: 
``'cxxreact/ModuleRegistry.h' file not found``

or

1. react-native init projectname
2. react-native run-ios 
=> error: 
``error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening testproj060.xcworkspace. Run CLI with --verbose flag for more details.
** BUILD FAILED **``

**Comment by murrayee** [comment] 2019-07-04 07:10
+1

**Comment by gongshouhui** [comment] 2019-07-04 07:43
+1

**Comment by kelset** [comment] 2019-07-04 09:58
👋 as pointed out by @murrayee 	it's likely that you didn't have cocoapods installed - or something went wrong during linking. I just tried to do the same flow you described and I can't reproduce it - I'll close this for now.

**Closed by kelset** 2019-07-04 09:58 UTC
Labels: Bug

**Comment by psyzz** [comment] 2019-07-04 10:41
i already had cocoapods installed.
Doing a brew install cocoapods and redo a pod install fix it, thanks

**Comment by dragooncjw** [comment] 2019-07-23 15:20
@murrayee I did what you told. But it showed '[!] No `Podfile' found in the project directory.'.
What should I do next?

**Comment by betopompolo** [comment] 2019-09-27 00:04
@dragooncjw you need to execute `pod install` inside `ios/` folder. Did you try that? 🤔

**Comment by lizhengjin** [comment] 2019-11-06 07:47
i try this same flow but i can't solve it
