### ISSUE TITLE
Unoptimized APK

### ISSUE THREAD

**Issue by tiennguyen9988** [facebook/react-native#25166] opened 2019-06-06 04:58 UTC
React Native version: 0.57.1

## Steps To Reproduce

1. gradlew assembleRelease

Describe what you expected to happen:
I had issue with android, they alert: my app is "Unoptimized APK" and not accept for my app although they still accept prev version my app.

**Comment by hosseintoussi** [comment] 2019-06-06 06:39
We have the same problem.

**Comment by suresh-borad** [comment] 2019-06-08 17:09
Yes, We are on the same boat :1234:

**Comment by eai301** [comment] 2019-06-11 08:57
Google Play is generating and optimizing APKs from your Android App Bundle. This may take a few minutes, depending on the size of your app bundle.

did you try to upload .aab file!?

**Comment by raiedahmed** [comment] 2019-06-13 01:25
how create .aab  react natice v. expo

**Comment by eai301** [comment] 2019-06-13 04:24
gradlew bundleRelease

**Comment by nainishmodi** [comment] 2019-06-13 07:13
I m also facing same issue..
Here are some snips of my configurations of my project.

I have also set 
**def enableSeparateBuildPerCPUArchitecture = true**

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
**def enableProguardInReleaseBuilds = true**

 splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            **include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"**
        }
    }

buildTypes {
        release {
            **minifyEnabled enableProguardInReleaseBuilds
            shrinkResources true**
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }

Any help would be greatly appreciated.

![2](https://user-images.githubusercontent.com/17999172/59411266-752f5780-8dd8-11e9-81f8-7ff1a5f912e6.PNG)
![3](https://user-images.githubusercontent.com/17999172/59411267-752f5780-8dd8-11e9-8a5e-bebdc161b156.PNG)
![p](https://user-images.githubusercontent.com/17999172/59411268-75c7ee00-8dd8-11e9-8552-20f9d131adf5.PNG)
![1](https://user-images.githubusercontent.com/17999172/59411269-75c7ee00-8dd8-11e9-89ac-b26596d86c39.PNG)

**Comment by atha-github** [comment] 2019-06-18 13:59
I am experiencing the same issue, I am using 
    "expo": "^33.0.0",
    "expo-asset": "^5.0.1",
    "expo-constants": "^5.0.1",
    "expo-file-system": "^5.0.1",
    "expo-font": "^5.0.1",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
    "react-native-elements": "^1.1.0",
    "react-navigation": "^3.11.0",

After expo build:android I got a apk of 19MB, But unable to review and publish in google playstore.
![531e10d5fe8ca6e7e4c5538912bd90490f3eba9a_2_690x163](https://user-images.githubusercontent.com/20313606/59690658-5fb69500-91ff-11e9-9cf5-749f1e3b45c4.png)
![17380331cb142d4d0cf0774b865f61870962f29f_2_690x302](https://user-images.githubusercontent.com/20313606/59690669-647b4900-91ff-11e9-9c57-a0ec0af5ce60.png)

**Comment by kelset** [comment] 2019-06-18 15:26
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Can anyone look a bit deeper in what causes this error? Maybe in the google play store development portal there may be a doc explaining it?

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗

**Closed by kelset** 2019-06-18 15:26 UTC
Labels: Bug

**Comment by ebaynaud** [comment] 2019-06-21 15:02
When bundling, simply replace the old `./gradlew assembleRelease` by `./gradlew bundleRelease` then upload app.aab instead of app.apk

Before uploading app.aab, you must be enrolled in App Signing by Google Play: https://facebook.github.io/react-native/docs/signed-apk-android#migrating-old-android-react-native-apps-to-use-app-signing-by-google-play

**Comment by ReactAndrey** [comment] 2019-07-06 11:03
I found one solution.
Please reply me if someone interested in this.

**Comment by ssg-luke** [comment] 2019-07-06 14:07
@ReactAndrey Could you share the solution to this?

**Comment by nainishmodi** [comment] 2019-07-06 14:44
Please let me know.

Sent from Yahoo Mail on Android 
 
  On Sat, Jul 6, 2019 at 4:36 PM, Andrey Skumin<notifications@github.com> wrote:   
I found one solution.
Please reply me if someone interested in this.

**Comment by pragneshpj** [comment] 2019-07-10 05:08
> I found one solution.
> Please reply me if someone interested in this.
@ReactAndrey 
Could you share the solution to this?

**Comment by NazarK** [comment] 2019-07-11 07:55
You should just build and upload aab (Android App Bundle)  file instead of apk .
```
cd android
./gradlew bundleRelease
cd ..
```
aab file will be placed in"/android/app/build/outputs/bundle/release/"

**Comment by jwheat** [comment] 2019-07-15 11:20
As a follow up to @NazarK (thank you BTW), you **MUST** opt-in to the Google Managed App Signing, or else it will not accept your .aab file. I had opted-out and couldn't find a way to change my mind, had to delete the app from my dashboard and start over, which was fine since I was just starting.

This whole thing started because my .apk was 'too large' (have a lot of images). Ironically, my .aab file was exactly 30 bytes smaller 

```31391694 Jul 14 21:09 app-release.apk
31319664 Jul 15 06:32 app.aab```

**Comment by nainishmodi** [comment] 2019-07-15 11:27
I just created the .aab file using below command
**cd android** then **gradlew bundleRelease**

You will find you the .aab file inside **android/app/build/outputs/bundle/release**
and then I uploaded it on PS and then that warning disappears so my suggestion is to all who are struggling with this error kindly go with this.

**Comment by anastely** [comment] 2019-08-01 16:51
I want to reduce my APK Size 
I followed these https://facebook.github.io/react-native/docs/signed-apk-android  
and run ./gradlew bundleRelease instead of assembleRelease 
But I Got Error 

> Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> Job failed,

So how can I solve it, I'm Google it but the issue is still! 
But without Enable Proguard it's work very well and I got (Aab & .Apk )  SO How To Solve it!

I think the issue with this file but I don't know how to configure that!


**proguard-rules.pro**
```

# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in /usr/local/Cellar/android-sdk/24.3.3/tools/proguard/proguard-android.txt
# You can edit the include path and order by changing the proguardFiles
# directive in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# Add any project specific keep options here:

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}

```

**Comment by anastely** [comment] 2019-08-01 16:57
I want to reduce my APK Size 
I followed these https://facebook.github.io/react-native/docs/signed-apk-android  
and run ./gradlew bundleRelease instead of assembleRelease 
But I Got Error 

> Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> Job failed,

So how can I solve it, I'm Google it but the issue is still! 
But without Enable Proguard it's work very well and I got (Aab & .Apk )  SO How To Solve it!

I think the issue with this file but I don't know how to configure that!


**proguard-rules.pro**
```

# Add any project specific keep options here:

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}

```

**Comment by ReactAndrey** [comment] 2019-08-02 13:48
> @ReactAndrey Could you share the solution to this?

Hi sorry for late reply. I am busy for some projects.
You can simple do such like this.
Open your app in android studio.
Maybe you have to upgrade android studio version.
And then Build/Generated Signed Bundle on Apk and then you can choose Android App Bundle.
After create aab file you can upload this.

**Comment by Johnny-lou** [comment] 2020-03-20 06:34
@hosseintoussi  problem solved?

**Comment by Johnny-lou** [comment] 2020-03-20 06:36
@ReactDevs007  I have the same problem, what should I do?
