### ISSUE TITLE
IOS removeClippedSubviews not working

### ISSUE THREAD

**Issue by antoxi4** [facebook/react-native#8749] opened 2016-07-13 16:22 UTC
When removeClippedSubviews true ListView behaves incorrectly. Page size not work and scrollRenderAheadDistance work incorrect too.

**Comment by grabbou** [comment] 2016-07-14 19:33
Mind providing a bit more context to this issue? There's already another one (that seems similar) opened here #8607.

**Comment by antoxi4** [comment] 2016-07-23 10:03
No, after last release truble not fixed. On Ios when i try use removeClippedSubviews i see blank screen in listView!

this is my code

```
<ListView
            ref={'listView'}
            pageSize={15}
            renderRow={this.renderList}
            dataSource={this.state.dataSource}
            renderHeader={this.renderListHeader}
            pagingEnabled={true}
            initialListSize={30}
            removeClippedSubviews={false}
            scrollRenderAheadDistance={150}/>
```

**Comment by leeabc** [comment] 2016-07-26 07:44
After add removeClippedSubviews={false}, we solved the issue .
RN version 0.30.0

**Comment by antoxi4** [comment] 2016-07-26 12:26
@leeabc  yep but its not normal i need removeClippedSubviews={true}

**Comment by satya164** [comment] 2016-07-26 13:37
Duplicate of #8607

**Closed by satya164** 2016-07-26 13:37 UTC
Labels: Needs more information
