### ISSUE TITLE
[Touchable*] onPress responds slowly when development mode is enabled

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#2558] opened 2015-09-04 22:37 UTC
While re-implementing a feature from a native app, I was chatting with @ide about how `onPress` seemed really slow in comparison -- he suggested that I try disabling it (`dev=false` in packager url, for those of you who want to try it), which made a huge difference.

`onPress` should have the same performance characteristics regardless of whether the app is in development mode.

**Comment by brentvatne** [comment] 2015-09-04 22:39
cc @a2 as your name shows up most in `git blame` for `Touchable` files :) :hand:

**Comment by aleclarson** [comment] 2015-09-05 00:55
+1

**Comment by despairblue** [comment] 2015-09-07 13:22
:relieved:  I already thought I'm the only experiencing this:
![screen shot 2015-09-07 at 15 19 25](https://cloud.githubusercontent.com/assets/927609/9717545/f132302e-5573-11e5-8ae6-2656b8b617e6.png)

This happens when opening a post from a list. So it takes 1.5 seconds (in the simulator) to handle a single tap. On a real device it's taking a couple of seconds. :confused:

**Comment by despairblue** [comment] 2015-09-07 14:09
I tried `dev=false`, but it didn't help:
![screen shot 2015-09-07 at 16 07 52](https://cloud.githubusercontent.com/assets/927609/9718280/bbbcd578-557a-11e5-96df-0c791df4811c.png)

3 seconds to handle a tap :disappointed:

**Comment by despairblue** [comment] 2015-09-07 14:38
Ok, the reason for this huge delay is [redux-logger](https://github.com/fcomb/redux-logger) and that console.log is synchronous.

**Comment by grabbou** [comment] 2016-01-25 18:23
Same here, no logging, the TouchableHighlight onPress is called with 2/3 seconds when having like ~100 items in a list view (touchable is the entire row)

**Comment by jsierles** [comment] 2016-03-20 16:23
@grabbou @brentvatne is this still an issue?

**Comment by grabbou** [comment] 2016-03-20 17:21
In my case, this was caused by re-renders of list view rows - added few perf tweaks and now no delay happens :)

**Comment by janicduplessis** [comment] 2016-05-20 07:16
@brentvatne Is this still an issue or should we close this?

**Comment by Thorbenandresen** [comment] 2016-05-23 15:38
I still have the issue (0.24) - debug mode slow, release mode no problem

**Comment by mkonicek** [comment] 2016-10-27 21:48
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/touchable-onpress-responds-slowly-when-development-mode-is-enabled

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Closed by mkonicek** 2016-10-27 21:48 UTC
Labels: Icebox, Perf

**Comment by trcarlocastro** [comment] 2017-03-24 07:55
@grabbou Good day sir, what tweaks did you do to solve your problem?

**Comment by grabbou** [comment] 2017-03-31 08:22
In particular, I have worked on making ListView.DataSource comparator
return `false` when it doesn't have to rerender the view. I believe it's no
longer applicable as there's FlatList that offers better performance out of
the box.
