### ISSUE TITLE
cocoapods improt react-native error: No component found for view with name "RCTText"

### ISSUE THREAD

**Issue by haidizhilei** [facebook/react-native#17920] opened 2018-02-09 04:22 UTC
### Is this a bug report?

I use cocoapods import react-native to my ios project  this is Podfiile:

target 'reactnativeTest' do
   pod 'React', :path => './rnproject/node_modules/react-native', :subspecs => [
    'Core',            
    'BatchedBridge',    
    'DevSupport',      
    'ART',  
    'RCTActionSheet',  
    'RCTAnimation',  
    'RCTCameraRoll',  
    'RCTGeolocation',  
    'RCTImage',  
    'RCTNetwork',  
    'RCTPushNotification',  
    'RCTSettings',  
    'RCTText',  
    'RCTVibration',  
    'RCTWebSocket',     
    'RCTLinkingIOS'  
  ]
  pod 'yoga', :path => './rnproject/node_modules/react-native/ReactCommon/yoga'
end

when I run project ther error messgae is :  No component found for view with name "RCTText"
How can I do ?

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

<!--
  In your terminal run `react-native info` and paste its contents here. Next, specify your target platform, like this:

  Environment:
    OS:  macOS Sierra 10.12.6
    Node:  7.7.3
    Yarn:  0.27.5
    npm:  5.4.0
    Watchman:  4.7.0
    Xcode:  Xcode 8.3.3 Build version 8E3004b
  Packages: (wanted => installed)
    react-native: 0.51.0 
    react: 16.0.0-alpha.12 => 16.0.0-alpha.12

  Target Platform: iOS (10.3.3)

**Comment by HarrySu** [comment] 2018-02-09 08:39
+1

**Comment by KelaKing** [comment] 2018-02-09 09:14
open `./node_modules/react-native/React.podspec`
change
```diff
  s.subspec "RCTText" do |ss|
    ss.dependency             "React/Core"
-   ss.source_files         = "Libraries/Text/*.{h,m}"
+   ss.source_files         = "Libraries/Text/**/*.{h,m}"
  end
```

**Comment by awinograd** [comment] 2018-02-09 15:31
Looks like the fix is in master but didn't make it into the release

https://github.com/facebook/react-native/commit/7e7d00aebefd2416f948066c65c739581c6e3f54

**Closed** 2018-02-09 20:55 UTC

**Comment by Salinn** [comment] 2018-06-19 22:40
I am still having this issue. Anyone else running into this? I confirmed that my source files match what @KelaKing has listed there. Just upgraded from 50.4 with no issue.

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.0.0
  Yarn: 1.6.0
  npm: 5.0.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4670197

Packages: (wanted => installed)
  react: ^16.3.1 => 16.3.1
  react-native: ^0.55.4 => 0.55.4

**Comment by neomib** [comment] 2018-09-17 08:43
I just deleted the ios and node_modules folders and reinstalled everything.
If you do that make sure you save any important changes first (like info.plist file).
