### ISSUE TITLE
iOS build fails to run in with Xcode 11.0 beta

### ISSUE THREAD

**Issue by vivekhumnabad** [facebook/react-native#25138] opened 2019-06-04 07:30 UTC
React Native version:

## Steps To Reproduce

1.Create a new react-native project with react-native init "<projectname>"
2.open iOS project and run

Describe what you expected to happen:
Build and run successfully and show launch screen with default UI

What is happening:
Build shows Error Screen saying -
"Unknown argument type '__attribute__' in method -[RCTAppState getCurrentappState:error:].
Extend RCTConvert to support this type

Snack, code example, or link to a repository:
Happens with all my existing projects and newly created samples as well.Here is the sample code I have tried.
[FinalTry.zip](https://github.com/facebook/react-native/files/3251039/FinalTry.zip)

Please refer to below screenshot for error data
![Simulator Screen Shot - iPhone Xʀ - 2019-06-04 at 12 30 26](https://user-images.githubusercontent.com/40496367/58859937-91d8da80-86c8-11e9-94ef-2a0524373b27.png)

NOTE:
Happens only in newly launched MacOS and Xcode 11 beta

**Comment by zhongwuzw** [comment] 2019-06-04 14:13
OMG, seems Xcode 11 beta breaks method signature parsing. Now I have no chance to install Xcode beta. @vivekhumnabad Would you mind paste the method selector string for us? just add the `NSLog` like below.

![image](https://user-images.githubusercontent.com/5061845/58886118-f2423900-8715-11e9-9b41-ca0bff652700.png)

**Comment by ericlewis** [comment] 2019-06-04 16:15
fixed by #25146

**Comment by vivekhumnabad** [comment] 2019-06-04 16:22
@ericlewis  Any idea when this will be released???

**Comment by ericlewis** [comment] 2019-06-04 16:48
@vivekhumnabad needs to be accepted and merged, which shouldn't take long, and after maybe @grabbou wouldn't mind pulling it in to the 0.60 RC, since it is a pretty minor change? :D

**Comment by ericlewis** [comment] 2019-06-04 20:59
@vivekhumnabad its been merged, this will land hopefully in 0.60 or 0.61!

**Closed by ericlewis** 2019-06-04 20:59 UTC
Labels: Bug, Platform: iOS

**Comment by Yuncun** [comment] 2019-07-11 00:15
> @vivekhumnabad its been merged, this will land hopefully in 0.60 or 0.61!

Hey Eric, do you know if this fix ended up in 0.60?

**Comment by ollydixon** [comment] 2019-07-25 09:34
Would it be possible to get a fix in version precceding 0.60? Say 59?
(0.60 completely breaks a lot of third party packages that are no longer supported)

**Comment by betko** [comment] 2019-07-29 08:30
@ollydixon This fix is already part of the 59.9 react-native.

**Comment by MuhammadUsman786786** [comment] 2019-09-01 23:20
I am still facing this issue on 

> react natvie :0.59.3

**Comment by nschild** [comment] 2019-09-03 15:41
@MuhammadUsman786786 
According to Betko's post, it is included in 0.59.9, you are using 0.59.3. You will need to upgrade to see the fix.

**Comment by Desintegrator** [comment] 2019-09-20 16:08
Does it affect on users upgraded to ios13 with apps that is currently in store?

**Comment by nschild** [comment] 2019-09-20 19:58
@Desintegrator Users who are on iOS13 can download and run React Native 0.59.<9 apps from the play store, as long as they are built with Xcode 10. The issue is when building apps with Xcode 11 (which is required to run locally on iOS 13 devices).

**Comment by NguyenVanVietPoLy** [comment] 2019-09-21 04:23
> OMG, dường như Xcode 11 beta phá vỡ phân tích chữ ký phương thức. Bây giờ tôi không có cơ hội để cài đặt Xcode beta. @vivekhumnabad Bạn có phiền dán chuỗi chọn phương thức cho chúng tôi không? chỉ cần thêm `NSLog`như dưới đây.
> 
> ![Hình ảnh, tưởng tượng](https://user-images.githubusercontent.com/5061845/58886118-f2423900-8715-11e9-9b41-ca0bff652700.png)

not work for me

**Comment by NguyenVanVietPoLy** [comment] 2019-09-21 05:34
> fixed by #25146

https://github.com/facebook/react-native/pull/25146/files that work in my case, react-native 0.59.8

**Comment by pqminh** [comment] 2019-09-21 06:10
react-native 0.52.3

### fix xcode 11 beta
code ./node_modules/react-native/React/Base/RCTModuleMethod.mm
Replace 
return RCTReadString(input, "__unused") ||
         RCTReadString(input, "__attribute__((unused))");
To
return RCTReadString(input, "__attribute__((unused))") ||
         RCTReadString(input, "__attribute__((__unused__))") ||
         RCTReadString(input, "__unused");

**Comment by CaopanHuster** [comment] 2019-09-21 08:27
> > fixed by #25146
> 
> https://github.com/facebook/react-native/pull/25146/files that work in my case, react-native 0.59.8

it works for me. do reinstall the app after replace

**Comment by Desintegrator** [comment] 2019-09-21 10:23
> @Desintegrator Users who are on iOS13 can download and run React Native 0.59.<9 apps from the play store, as long as they are built with Xcode 10. The issue is when building apps with Xcode 11 (which is required to run locally on iOS 13 devices).

What about app from the store that is currently run React Native 0.55.0?

**Comment by vijay-dadhich09** [comment] 2019-09-21 14:41
Thanks, @CaopanHuster for confirming about 0.59.8. Is this change available on RN 0.59.8? I can't upgrade my RN version further 0.59.8.

**Comment by umkhan65** [comment] 2019-09-23 07:56
@NguyenVanVietPoLy "RCTReadString(input, "__attribute__((__unused__))")" adding this worked for me on 0.57.4

**Comment by gogogous88** [comment] 2019-09-24 18:37
react native 0.59.9 solved this problem.
but if you want to keep 0.59.0~0.59.8
find the file here: node_modules/react-native/React/base/RCTModuleMethod.mm
at line 93 add:
`static BOOL RCTParseUnused(const char **input)
{
  return RCTReadString(input, "__unused") ||
         RCTReadString(input, "__attribute__((__unused__))") || //solve by add this line
         RCTReadString(input, "__attribute__((unused))");
}`

**Comment by matwming** [comment] 2019-11-06 23:27
This issue still exists in xcode 11.1 and rn 0.59.9. Do I have to update to 0.6**?Thanks.

**Comment by brunolemos** [comment] 2019-11-06 23:29
Yes, upgrade to the latest version of react-native.

**Comment by JTangming** [comment] 2020-03-04 09:47
> fixed by https://github.com/facebook/react-native/pull/25146/files#diff-263fc157dfce55895cdc16495b55d190

it works for me.
but if you want to keep a stable version
update here: node_modules/react-native/React/base/RCTModuleMethod.m
then [patch-package](https://github.com/ds300/patch-package),patch-package lets app authors instantly make and keep fixes to npm dependencies.

**Comment by vnrtumu** [comment] 2020-03-13 06:10
if ([@(input) hasPrefix:@"getCurrentAppState"]){
    NSLog(@"@", @(input))
  }

**Comment by aliszafar1** [comment] 2020-04-15 07:53
> react native 0.59.9 solved this problem.
> but if you want to keep 0.59.0~0.59.8
> find the file here: node_modules/react-native/React/base/RCTModuleMethod.mm
> at line 93 add:
> `static BOOL RCTParseUnused(const char **input) { return RCTReadString(input, "__unused") || RCTReadString(input, "__attribute__((__unused__))") || //solve by add this line RCTReadString(input, "__attribute__((unused))"); }`

Worked for me
