### ISSUE TITLE
zIndex for a native view doesn't work.

### ISSUE THREAD

**Issue by gourav-singhal** [facebook/react-native#16052] opened 2017-09-21 13:06 UTC
Hi All,

I have two views which are created in native code I want to show 2nd view over 1st view (this view is covering full screen). I have tried providing zIndex to the 2nd view so that it may appear above the 1st native view.

But zIndex doesn't work when the views are native views. 

There are some other local images which are displayed at zIndex on these views they work fine but not the views.

Please help me whether it is possible to to do so in react native or not?

**Comment by hramos** [comment] 2017-09-21 15:20
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue that meets the requirements set forth in the template. Thanks!

**Closed by hramos** 2017-09-21 15:20 UTC
