### ISSUE TITLE
App is not running on iOS for latest version of react-native.

### ISSUE THREAD

**Issue by Ashi90** [facebook/react-native#15282] opened 2017-07-31 06:23 UTC
## New project fail to build on iOS.
Create new project with react-native init [Project Name]
then run using react-native run-ios, and got below issues on terminal,

** BUILD FAILED **

```
The following commands produced analyzer issues:
        Analyze /Volumes/mac\ data/react/UpdateVersion/node_modules/react-native/ReactCommon/yoga/yoga/YGNodeList.c
        Analyze /Volumes/mac\ data/react/UpdateVersion/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.c
(2 commands with analyzer issues)

The following build commands failed:
        PhaseScriptExecution Install\ Third\ Party /Volumes/mac\ data/react/UpdateVersion/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/double-conversion.build/Script-190EE32F1E6A43DE00A8543A.sh
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/UpdateVersion.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/UpdateVersion.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

```

# Other Information

- React Native version: 0.46.4
- Platform: iOS
- Development Operating System: macOS Sierra 10.12.5
- Dev tools: Xcode 8.3.3

**Comment by hramos** [comment] 2017-07-31 17:57
There's several issues with this same error. This one doesn't seem to provide details so I'm going to go ahead and close it, but feel free to go through the issues at https://github.com/facebook/react-native/search?q=CFBundleIdentifier&type=Issues&utf8=%E2%9C%93 to learn more.

**Closed by hramos** 2017-07-31 17:57 UTC

**Comment by hramos** [comment] 2017-08-04 06:49
Duplicate of #14423
