### ISSUE TITLE
react native init throwing error  ERR_INVALID_ARG_TYPE(name, 'string', value)

### ISSUE THREAD

**Issue by anik587** [facebook/react-native#24103] opened 2019-03-22 19:10 UTC
Hello, I am having some issue with react native init for creating a new project. The error is something like
![wqeqweasadad](https://user-images.githubusercontent.com/13942364/54847712-4b9aee80-4d09-11e9-8833-ad5bf667d658.PNG)

just executing react-native init projectName
project creation failed wth 
`  internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)

`

node v11.10.0
npm 6.7.0
yarn 1.13.0

**Comment by sivdead** [comment] 2019-03-22 19:30
i have met this problem too,looked up the stack trace it seems that PackageManager.projectDir is not set 😢

**Comment by anik587** [comment] 2019-03-22 19:35
I really don't understand. What's wrong !!!! Is that the react-native cli causing this problem. I am just hanged up don't and can't find

**Comment by Gerlison** [comment] 2019-03-22 19:36
I'm too. Yesterday was working fine, but now dive this error. I tried to put a package.json file and run "npm i", but when i run the app, it doesn't recognize the AVD

**Comment by BenHurMartins** [comment] 2019-03-22 19:36
same problem here, just can't start a new project

**Comment by mixkorshun** [comment] 2019-03-22 19:37
Have same issue:
node v11.12.0
npm 6.7.0

```
info Adding required dependencies
internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

```

**Comment by BenHurMartins** [comment] 2019-03-22 19:39
this is how my package.json looked after the react-native init command:

```
{
  "name": "answers",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "react-native": "0.59.1"
  }
}

```

**Comment by mixkorshun** [comment] 2019-03-22 19:43
It works with previous versions:

```
react-native init --version "0.58.6"
```

**Comment by BenHurMartins** [comment] 2019-03-22 20:05
> It works with previous versions:
> 
> ```
> react-native init --version "0.58.6"
> ```

worked pretty well

**Comment by anik587** [comment] 2019-03-22 20:08
Yes working thanks a lot but there are some issues with 0.59 version of react native.
I am not closing the issue because it's going to be fixed right!!!?

**Comment by BenHurMartins** [comment] 2019-03-22 20:19
I don't think the problem is with the version 0.59.1, I think it is with some dependency, two days ago I've used the 0.59 and it worked fine.

**Comment by anik587** [comment] 2019-03-22 20:26
Just about 2-3 hours ago it stopped working. I'm using 0.59.1 almost a month now 😟😟

**Comment by afstanton** [comment] 2019-03-22 22:51
Just got the same error, confirmed.

**Comment by Leopard** [comment] 2019-03-22 23:38
<img width="588" alt="Screen Shot 2019-03-23 at 10 07 58" src="https://user-images.githubusercontent.com/7047/54858242-93466800-4d53-11e9-89d0-f4a12803d297.png">
the same here ...

**Comment by sseoussama** [comment] 2019-03-22 23:52
same here, I am stuck with this error since the morning .

**Comment by pjay79** [comment] 2019-03-23 00:02
Same problem here

**Comment by matteusprado** [comment] 2019-03-23 00:04
Same here.

**Comment by athmangude** [comment] 2019-03-23 00:05
Same for me too

**Comment by adonaipinheiro** [comment] 2019-03-23 00:07
Same for me

**Comment by matteusprado** [comment] 2019-03-23 00:11
This error is occurring since this morning. I'm using the 0.59.1 about a month.

**Comment by matteusprado** [comment] 2019-03-23 00:16
I am using "react" 16.8.3 in my old project with "0.59.1" react-native. But when I try to create a new project with 0.59.1, "yarn" tries to create with version 16.8.5 of "react". I checked the "CHANGELOG" of the "react" and realized that a new version was released 10 hours ago. Can this be related? (sorry for my bad english)

**Comment by sseoussama** [comment] 2019-03-23 00:17
> It works with previous versions:
> 
> ```
> react-native init --version "0.58.6"
> ```

it worked with the old version

**Comment by IvanaSimunic** [comment] 2019-03-23 00:19
Same error here

**Comment by matteusprado** [comment] 2019-03-23 01:55
same problem happens with node 10 and 11 here.

Looks like it's probably related to @react-native-community/cli being updated 7 hours ago.

react-native-community/react-native-cli#260

If you're looking for a quick solution can edit a file in node modules: react-native-community/react-native-cli@0c00895 and re-run the command. It worked for me.

**Comment by c9n** [comment] 2019-03-23 02:10
info Adding required dependencies
internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:1036:7)
    at isProjectUsingYarn (/Users/lynn/Developer/QingHe/neo/node_modules/@react-native-community/cli/build/tools/yarn.js:101:51)
    at shouldUseYarn (/Users/lynn/Developer/QingHe/neo/node_modules/@react-native-community/cli/build/tools/PackageManager.js:36:39)

**Comment by zsubzwary** [comment] 2019-03-23 03:27
I am having the exact same issue !!
# 😭 😭 😭 😭

```
Done in 191.71s.
info Setting up new React Native app in D:\WorkSpace\awesomeApp
info Adding required dependencies
path.js:39
    throw new ERR_INVALID_ARG_TYPE('path', 'string', path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:432:7)
    at isProjectUsingYarn (D:\WorkSpace\awesomeApp\node_modules\@react-native-community\cli\build\tools\yarn.js:101:51)
    at shouldUseYarn (D:\WorkSpace\awesomeApp\node_modules\@react-native-community\cli\build\tools\PackageManager.js:36:39)
    at Object.install (D:\WorkSpace\awesomeApp\node_modules\@react-native-community\cli\build\tools\PackageManager.js:44:10)
    at generateProject (D:\WorkSpace\awesomeApp\node_modules\@react-native-community\cli\build\commands\init\init.js:111:18)
    at Object.init (D:\WorkSpace\awesomeApp\node_modules\@react-native-community\cli\build\commands\init\init.js:94:3)
    at run (C:\Users\Zaki\AppData\Roaming\npm\node_modules\react-native-cli\index.js:302:7)
    at createProject (C:\Users\Zaki\AppData\Roaming\npm\node_modules\react-native-cli\index.js:249:3)
    at init (C:\Users\Zaki\AppData\Roaming\npm\node_modules\react-native-cli\index.js:200:5)

```

**Comment by c9n** [comment] 2019-03-23 03:30
Reason:

`projectDir` in `node_modules/@react-native-community/cli/build/tools/PackageManager.js` is`undefined`

related files:

```
./packages/cli/src/commands/init/init.js
```
![image](https://user-images.githubusercontent.com/6159817/54861118-03a6b680-4d5f-11e9-85e0-4afcd203b5de.png)

**Comment by acheraime** [comment] 2019-03-23 03:31
Same issue here. Any update?

**Comment by zsubzwary** [comment] 2019-03-23 03:36
@matteusprado how do I fix this ?? [Your Solution](https://github.com/facebook/react-native/issues/24103#issuecomment-475829605) I did not understand where the files are that I should change ?

**Comment by zsubzwary** [comment] 2019-03-23 03:52
> It works with previous versions:
> 
> ```
> react-native init --version "0.58.6"
> ```

Thank you soo much !! 
# 😘😘
You saved my life !! 😂😂

**Comment by neupaneanish** [comment] 2019-03-23 05:46
Same Problem

**Comment by ngquangan** [comment] 2019-03-23 05:50
Same for me too. 😭 😭 😭 😭

**Comment by MagudeshStriker** [comment] 2019-03-23 05:59
any idea abt this issue ?

**Comment by ATShiTou** [comment] 2019-03-23 06:38
It seems that some dependencies has updated. I have initialed react-native 0.59.0-rc3 project last week successfully. But now failed, too.

**Comment by ZohaibAhmad786** [comment] 2019-03-23 07:28
I am having the Exact Same issue as above mentioned

info Setting up new React Native app in C:\Users\ZohaibAhmad\AwesomeProjec
info Adding required dependencies
internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:427:7)
    at isProjectUsingYarn (C:\Users\ZohaibAhmad\AwesomeProjec\node_modules\@react-native-community\cli\build\tools\yarn.js:101:51)
    at shouldUseYarn (C:\Users\ZohaibAhmad\AwesomeProjec\node_modules\@react-native-community\cli\build\tools\PackageManager.js:36:39)
    at Object.install (C:\Users\ZohaibAhmad\AwesomeProjec\node_modules\@react-native-community\cli\build\tools\PackageManager.js:44:10)
    at generateProject (C:\Users\ZohaibAhmad\AwesomeProjec\node_modules\@react-native-community\cli\build\commands\init\init.js:111:18)
    at Object.init (C:\Users\ZohaibAhmad\AwesomeProjec\node_modules\@react-native-community\cli\build\commands\init\init.js:94:3)
    at run (C:\Users\ZohaibAhmad\AppData\Roaming\npm\node_modules\react-native-cli\index.js:302:7)
    at createProject (C:\Users\ZohaibAhmad\AppData\Roaming\npm\node_modules\react-native-cli\index.js:249:3)
    at init (C:\Users\ZohaibAhmad\AppData\Roaming\npm\node_modules\react-native-cli\index.js:200:5)

**Comment by zsubzwary** [comment] 2019-03-23 07:45
@ZohaibAhmad786  try [this solution](https://github.com/facebook/react-native/issues/24103#issuecomment-475836633) 

It will resolve the issue on hand 😇😇

**Comment by ZohaibAhmad786** [comment] 2019-03-23 08:00
> @ZohaibAhmad786  try this solution
> It will resolve the issue on hand 😇😇

Thanks it's Work with 0.58.6

**Comment by grabbou** [comment] 2019-03-23 08:40
Apologies for the troubles. We are shipping a fix to this right now. This is a regression inside CLI due to recent refactor. Will be fixed soon.

**Comment by thymikee** [comment] 2019-03-23 08:44
Whoa, this blew up. Fix published, sorry for the wait!

**Closed by thymikee** 2019-03-23 08:44 UTC
Labels: Ran Commands, Resolution: Needs More Information, Type: Bug Report
