### ISSUE TITLE
NavigationExperimental: panResponder does not work well with sub-component's gesture

### ISSUE THREAD

**Issue by filod** [facebook/react-native#6672] opened 2016-03-26 13:06 UTC
like this mapView page, i just can not drag the map to right:

![image](https://cloud.githubusercontent.com/assets/679897/14060181/8ba3164e-f396-11e5-8066-f5abf1b57cc2.png)

ps, i used react-native 0.23.0-rc `UIExplore`

**Comment by skevy** [comment] 2016-04-05 21:39
@ericvicenti @hedgerwang

**Comment by lacker** [comment] 2016-10-20 00:09
Hey, since it's been a while I am going to close this issue. I think we would need more specific information to make progress here - either a specific way to reproduce a bug, or a specific description of what does not work and what should work. Feel free to reopen or open a new issue if there is more information.

**Closed by lacker** 2016-10-20 00:09 UTC
