### ISSUE TITLE
Set-Cookie response header is not working on react-native 0.44.0

### ISSUE THREAD

**Issue by nsisodiya** [facebook/react-native#14154] opened 2017-05-24 11:17 UTC
I have created a Github repo for showcasing the bug.

Problem
======
When App make a XHR request for login. Login server sends cookie. App send XHR to get data and server read auth cookie on XHR. This is working fine with Android. However same code is not working with iPhone. At server side I am getting following logs. `JWT token is undefined`

How to reproduce this bug
=================
```git clone https://github.com/nsisodiya/react-native-cookie-bug.git
cd react-native-cookie-bug
yarn install
react-native run-ios
```

On iPhone Simulator, this will print like this

![image](https://cloud.githubusercontent.com/assets/333455/26400776/585de946-40a0-11e7-8b4d-6be864c4b727.png)

On Android , this print like this
![image](https://cloud.githubusercontent.com/assets/333455/26400791/646483a8-40a0-11e7-9e71-3c8318d7b81e.png)

Online Demo
========
Created https://snack.expo.io/BJAHjhMb- online demo, but here things are working fine because they are using Expo 16 which use react 0.43.4 where this bug do not present.

**Comment by hramos** [comment] 2017-05-24 19:24
Isn't this a duplicate of #14063?

**Comment by nsisodiya** [comment] 2017-05-24 19:33
Yes I think so.

**Comment by DanielZlotin** [comment] 2017-05-25 02:09
Yes same issue, see #14064 for the fix

**Closed** 2017-05-25 16:59 UTC

**Comment by deepaksisodiya** [comment] 2017-06-07 07:56
@nsisodiya You should try this
fetch(url, {
  credentials: 'include',
  ...otherOptions,
});

**Comment by aqnaruto** [comment] 2017-06-12 11:46
@deepaksisodiya it is not work on rn 4.4 ios.  but android works well

**Comment by nsisodiya** [comment] 2017-06-12 12:00
For me `include` is working on both.

On ios, if you close the app, cookie will be deleted. So you need to save
Cookie on AsyncStorage.

**Comment by Piyush905** [comment] 2017-10-05 09:05
@nsisodiya  I am facing the same problem which you mentioned "On ios, if you close the app, cookie will be deleted". I stored the Cookie in AsyncStorage but I am not able to figure it out -"how to load back the cookie into our app". I want to use the stored cookies for Fetch request.  Any idea?

**Comment by Palisand** [comment] 2017-10-05 20:09
@Piyush905 You can store the cookie in AsyncStorage, although you should not do so if the cookie holds sensitive information, and use [react-native-cookie](https://github.com/shimohq/react-native-cookie) to set it again.

Note, I am experience cookie deletion on Android as well.

**Comment by Piyush905** [comment] 2017-10-07 08:00
@Palisand Thanks. Yes, I am doing the same way. But, is there any other way where we can directly push cookie into the Fetch without using react-native-cookie. Also, I am facing challenge to get cookie from Webview (without  react-native-cookie) once authentication is successful.

**Comment by Palisand** [comment] 2017-10-07 14:08
The only other way, as far as I know, is to make the API call that sets the cookie header every time you start the app. If you're dealing with a user session, you would securely store credentials on the device and re-authenticate on app startup. However, this can render cookie expiration moot.

**Comment by almirfilho** [comment] 2017-10-18 01:13
Using RN 0.49 and neither `credentials: 'include'` nor `withCredentials: true` are working.

**Comment by jbosse** [comment] 2017-10-28 14:56
@almirfilho I am also finding that it doesn't seem to work in 48.4 but I cannot verify it's not just my code that is bad. :-/

**Comment by aqnaruto** [comment] 2017-10-31 04:53
@Palisand how to store cookies in asyncstorage  or delete cookie?
when i using cookie, 'credentials: 'include'  ,session time is out,so,i relogin, the server is updating session,  but, my cookie is still not updated in some device such as android 5.5 ,ios 10.1

**Comment by Palisand** [comment] 2017-10-31 17:40
@aqnaruto Can't you just use [react-native-cookie](https://github.com/shimohq/react-native-cookie) or [react-native-cookies](https://github.com/joeferraro/react-native-cookies) to access the cookie you want to store in device storage?
```
import {AsyncStorage} from "react-native";

const cookie = getCookieWithOneOfTheLibrariesStatedAbove();
AsyncStorage.setItem(cookie.name, cookie.value);
```
For deleting specific cookies, you'd want to use react-native-cookies's (that's with an "s"!) `clearByName`, and for removing them from storage, just call `AsyncStorage.removeItem`.

Again, do not use [AsyncStorage](https://facebook.github.io/react-native/docs/asyncstorage.html) if your cookie is holding sensitive data, like an authentication token! It is an unencrypted store, so if a user's device is rooted or jailbroken, their information is at risk of exposure.

If you are storing sensitive data, please consider using iOS's keychain and/or Android's keystore. Please read [this short blog post](http://randycoulman.com/blog/2017/07/25/secure-storage-in-react-native/) before choosing a secure storage library.

**Comment by aqnaruto** [comment] 2017-11-01 04:15
@Palisand thankyou ,but, i have tried react-native-cookies before,but it  not works well on reactnative0.44&0.46 ,
okay,mabe i should try it more

**Comment by Palisand** [comment] 2017-11-01 04:19
@aqnaruto Please let me know if it does work out. Just out of curiosity, are you using cookies for session authentication? If that's the only reason you're using them, then you should consider switching to token-based auth. Sorry I could not be of more help.

**Comment by aqnaruto** [comment] 2017-11-01 04:29
thankyou , yeah i am  using cookies for session authentication, i don't want to change backend code now to switch token-based.
when i using react-native-cookies ,it caused my app a lot error occured , such as react-navigation's view can't find、android compile error....
