### ISSUE TITLE
Presence of local-cli __fixtures__ file breaks react-native-vector-icons

### ISSUE THREAD

**Issue by dave-irvine** [facebook/react-native#17610] opened 2018-01-15 15:07 UTC
### Is this a bug report?

yes 

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 6.9.2
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0

### Steps to Reproduce

1. Install https://github.com/oblador/react-native-vector-icons
2. Use in a component
3. Start app

### Expected Behavior

App starts successfully

### Actual Behavior

Error is shown:

````
error: bundling failed: Error: While resolving module `react-native-vector-icons/MaterialIcons`, the Haste package `react-native-vector-icons` was found. However the module `MaterialIcons` could not be found within the package. Indeed, none of these files exist:

* `/Users/user/my-app/node_modules/react-native/local-cli/core/__fixtures__/files/MaterialIcons(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
* `/Users/user/my-app/node_modules/react-native/local-cli/core/__fixtures__/files/MaterialIcons/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`

````

### Steps to fix

As per https://github.com/oblador/react-native-vector-icons/issues/626

    rm ./node_modules/react-native/local-cli/core/__fixtures__/files/package.json

It looks like [this](https://github.com/facebook/react-native/blob/master/local-cli/core/__fixtures__/files/package.json) file is outdated for some time, I'm not sure if it needs to be there but it should either be updated or removed. For some reason it refers directly to the react-native-vector-icons project.

**Comment by vovkasm** [comment] 2018-01-16 08:14
Workaround: addition of `rn-cli.config.js` (for RN 0.52 at least):
```
const blacklist = require('metro/src/blacklist')
module.exports = {
  getBlacklistRE () {
    return blacklist([/react-native\/local-cli\/core\/__fixtures__.*/])
  },
}
```

It seems some blacklist items were lost in the process of moving from RN to metro :-/

**Comment by afilp** [comment] 2018-01-16 10:59
@vovkasm Where do we add this file?

**Comment by vovkasm** [comment] 2018-01-16 11:09
@afilp `rn-cli.config.js` should be located in the root directory of the project. It is location where RN will find it automatically (https://github.com/facebook/react-native/issues/7271). Seems this info not documented.

**Comment by CityLifeCorp** [comment] 2018-01-17 15:42
Try this
rm ./node_modules/react-native/local-cli/core/__fixtures__/files/package.json

**Comment by afilp** [comment] 2018-01-18 09:56
@CityLifeCorp Thanks, I think though that we should not do this because next time we 'npm i' (or a colleague does this on her computer) the change will be lost.

This is why I believe a 'permanent' change needs to be made in 'react-native' logic itself and be released in a next version.

**Comment by t4deu** [comment] 2018-01-19 13:08
Hello guys, just sent a PR with a fix, hope it helps everyone

**Comment by dazweeja** [comment] 2018-01-25 01:27
I think changing the blacklist is only necessary if the fixtures directory is causing other issues.

The simply fact is that package.json from version 1.0.0 of react-native-vector-icons should not be in the react-native repo at all but it is:

https://github.com/facebook/react-native/tree/1e8f3b11027fe0a7514b4fc97d0798d3c64bc895/local-cli/core/__fixtures__/files

**Comment by vovkasm** [comment] 2018-01-25 05:38
@dazweeja 
If you delete `local-cli/core/__fixtures__/files/package.json` this test will fail:
`local-cli/core/__tests__/findAssets.spec.js`.

I think that it was not supposed to be "package.json from old version of react-native-vector-icons", instead it was added as "package.json from some real module to test RN behavior with real-world complicated example". I think it totally valid have any `package.json` or other files with any content in repo for tests.

But `__fixtures__` directories as collection of data for tests definitely should not be included in module search paths.

**Comment by dazweeja** [comment] 2018-01-25 06:24
@vovkasm
Thanks. That explanation makes sense. The PR from @t4deu seems like a good solution in that case.

**Comment by Yandamuri** [comment] 2018-01-30 04:18
@vovkasm 
You solution worked for me. Thank you. But Could you tell why the issue is accruing? I ma new to react-native

**Comment by vovkasm** [comment] 2018-02-01 20:18
@Yandamuri Sorry I couldn't. I'am only one of many developers that use RN in their work... But it seems real issue is #17677 and what I know is that issue was introduced between version 0.51.0 and 0.52.0 of RN.

**Closed** 2018-02-17 04:49 UTC
Labels: Developer Experience, Help Wanted, Tooling

**Comment by AylwSt01** [comment] 2018-02-19 13:31
will this fix be available in 0.54?

**Comment by tychota** [comment] 2018-02-21 08:51
Would like to backport this commit to 0.53-stable as well !

cc @grabbou

**Comment by grabbou** [comment] 2018-02-21 11:53
Oh, yeah, it's unfortunate. I'll cherry-pick that onto both branches and let it wait for a while before next release to make sure I catch all the commits.
