### ISSUE TITLE
Can't find ”RCTAssert.h” while compiling after freshly generated project on v0.10.0

### ISSUE THREAD

**Issue by bouk** [facebook/react-native#2454] opened 2015-08-27 01:29 UTC
It seems there's an error in v0.10.0 that causes application generated with `react-native init` to not be compilable immediately. The fix is to open `<AppName>.xcodeproj/project.pbxproj` and find and replace any mention of `"$(SRCROOT)/node_modules/react-native/React/**"` with `"$(SRCROOT)/../node_modules/react-native/React/**"` (note the `..`)

**Comment by chirag04** [comment] 2015-08-27 01:39
Seem like you don't have node_modules installed under project project directory. Run npm install inside you project folder.

``"$(SRCROOT)/node_modules/react-native/React/**"`` seem fine to me if you have node_modules installed correctly under your project dir.

**Comment by license2e** [comment] 2015-08-27 01:41
I am facing the same issue, and `npm install` doesn't do anything for me since 'react-native' was already installed. 

Looking through the file, it seems that there are some path inconsistencies in the `<AppName>.xcodeproj/project.pbxproj` file as mentioned by the poster.

**Comment by license2e** [comment] 2015-08-27 01:44
And changing the paths as suggested fixes the issue..

**Comment by nakulpathak3** [comment] 2015-08-27 01:45
I _think_ this is the file and it has the correct paths - https://github.com/facebook/react-native/blob/f0dd9fb358efb94fba4dd2ba74fb4910bd929056/local-cli/generator-ios/templates/xcodeproj/project.pbxproj.

**Comment by license2e** [comment] 2015-08-27 01:48
Yeah, I was just looking at that, I am going to try generate a new react-native app and see if it has the correct paths.. Is there a generator step that changes that anywhere?

**Comment by license2e** [comment] 2015-08-27 01:52
Nope, same issue.. looking to see if that template is being manipulated somewhere downstream in terms of the SRCROOT path..

**Comment by chirag04** [comment] 2015-08-27 02:02
I just generated a new project and seems like this is only a problem with tests. If i remove the testing code then the build works fine.

**Comment by ide** [comment] 2015-08-27 03:36
Can someone submit a PR to fix this? I'm about to take off on a flight right now and can take a look and publics 0.10.1 when I land in a few hours.

**Comment by besarthoxhaj** [comment] 2015-08-27 11:47
I had the same problem. After trying a bit I just copied all the `React/Base/` files into my `iOS/appTests/`. That solved the problem for me!

Let me know if that helps!

**Comment by brenmcnamara** [comment] 2015-08-27 16:42
The problem for me was that the Test Target had an incorrect Header Search Path. This can be fixed by going into xcode, selected the Test Target, going to build Settings, going into the section "Search Paths".

Inside this "Search Paths" section, there is a "Header Search Paths" attribute, select it and make sure there is a search path: $(SRCROOT)/../node_modules/react-native/React set to Recursive. MAKE SURE THE ".." is present after $(SRCROOT) or it will be looking in the wrong directory.

![screen shot 2015-08-27 at 9 41 44 am](https://cloud.githubusercontent.com/assets/2343120/9526742/eb23c116-4c9f-11e5-86a6-9d9c47bf410e.png)

**Comment by sghiassy** [comment] 2015-08-27 18:01
@brenmcnamara's fix worked for me

**Comment by philikon** [comment] 2015-08-27 23:46
This seems to have been introduced in 0.10 (e9f69bc2e4bff3aaff2f77268087c362916d3756), but fixed in 0.11rc with the move to yeoman (f83675d1915b5e77638c117c82f8641cea367ffe). Do we need to release 0.10.1?

**Comment by ide** [comment] 2015-08-27 23:49
Yes, that sounds good. @philikon are you able to test whether the yeoman commit fixes things?

**Comment by philikon** [comment] 2015-08-28 00:05
@ide yes, I just confirmed that it's fixed in master/0.11. But OMFGWTFSIGH we changed the format of the project *again*, this time from `iOS/` to `ios/` cc @a2 @foghina @mkonicek

**Comment by inselmensch** [comment] 2015-08-28 05:40
hey guys, how do i update to 0.11? i just got the same issue with correct search path set.. removing test code kind of solves this issue. but don't think that should be the solution. so, how do i fix it?

**Comment by LukasBombach** [comment] 2015-08-28 09:28
Can confirm this happens on a completely fresh install—I installed react native for the first time ever, followed the instructions on [Getting Started](https://facebook.github.io/react-native/docs/getting-started.html#content) precisely and ran into this.

**Comment by j-mutter** [comment] 2015-08-28 14:29
I can also confirm it works on 0.11, and @philikon's fix looks good.

For anyone else stuck on this, @brenmcnamara's walkthrough for the `Header Search Paths` is the way to go.

**Comment by ide** [comment] 2015-08-28 20:01
react-native 0.10.1 is now on npm with @philikon's diff. Let us know if things are working for you.

**Closed by ide** 2015-08-28 20:01 UTC

**Comment by yorkie** [comment] 2015-08-29 15:54
```
["0.11.0-rc","0.10.0","0.10.0-rc","0.9.0","0.9.0-rc","0.8.0","0.8.0-rc.2","0.8.0-rc","0.7.1","0.7.0-rc.2","0.7.0-rc","0.6.0","0.6.0-rc","0.5.0","0.5.0-rc1","0.4.4","0.4.3","0.4.2","0.4.1","0.4.0","0.3.11","0.3.10","0.3.9","0.3.8","0.3.7","0.3.6","0.3.5","0.3.4","0.3.3","0.3.2","0.3.1","0.3.0","0.2.1","0.2.0","0.1.0","0.0.6","0.0.5","0.0.0"]
```

There is no valid version 0.10.1 at npm :(

**Comment by ide** [comment] 2015-08-29 17:41
@yorkie you may have a stale npm cache or be reading from a mirror. The npm repo has 0.10.1:
```
$ npm v react-native time | grep '0\.10\.1'
  '0.10.1': '2015-08-28T19:59:24.605Z' }
```

**Comment by yorkie** [comment] 2015-08-29 18:12
Works, sorry I did use China mirror :(

**Comment by truongluong1314520** [comment] 2018-06-20 10:04
@brenmcnamara Thank you, your solution help me to fix this. I do not know why in year 2018, this problem still occur :( so sad
