### ISSUE TITLE
Crash in iOS

### ISSUE THREAD

**Issue by xutm** [facebook/react-native#24800] opened 2019-05-10 13:32 UTC
When xcode is compiled and passed, the app will have a certain probability of crash.

As shown in the figure below

![企业微信截图_ff19a547-4028-420c-9a5c-fb578c762fde(1)](https://user-images.githubusercontent.com/11706751/57530929-e6f42b80-736a-11e9-91f3-a5680674bb24.png)

Does anybody have a look?

React Native version:
0.59.4

**Comment by zhongwuzw** [comment] 2019-05-11 14:46
@xutm Hi, seems you have two bridges? Can you still reproduce? I think it may related to some race condition, can you show how other `JavaScript thread` is doing like `com.facebook.react.JavaScript(41)` below.

<img width="533" alt="image" src="https://user-images.githubusercontent.com/5061845/57571244-0f992580-743e-11e9-9f01-74f8c3052e2a.png">

**Comment by xutm** [comment] 2019-05-13 09:05
@zhongwuzw 
- two bridges when App init.(One cache, one not)
- have a certain probability of crash.(Low frequency)

**Comment by kelset** [comment] 2019-05-13 09:15
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Also, it's really hard to help you when you don't follow the provided template.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗

**Closed by kelset** 2019-05-13 09:15 UTC
Labels: Bug, Platform: iOS

**Comment by zhongwuzw** [comment] 2019-05-13 09:27
@xutm Emm, seems your infos are not sufficient to investigate by us, as @kelset said, please fill in the issue template and more importantly for this crash is provide the entire crash log, contains all related infos. After that, we can fix this issue and reopen it. :)
