### ISSUE TITLE
Xcode error

### ISSUE THREAD

**Issue by kuangmeng** [facebook/react-native#14409] opened 2017-06-09 02:27 UTC
react-native-cli: 2.0.1
node v8.0.0
npm  v5.0.0
Command /bin/sh failed with exit code 1

**Comment by kumarryogeshh** [comment] 2017-06-09 07:31
Same issue.

react-native-cli: 2.0.1
react-native: 0.45.0
node: v6.6.0
npm: 5.0.3

**Comment by Sophia-Gao** [comment] 2017-06-09 08:09
the same issue

**Comment by carera** [comment] 2017-06-09 08:26
Same as https://github.com/facebook/react-native/issues/14368 ?

**Comment by hramos** [comment] 2017-06-09 17:06
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-09 17:06 UTC

**Comment by kamyzd** [comment] 2017-06-14 10:12
Maybe you are using Xcode 8.1 , I upgraded Xcode to 8.2.1 which fixed my problem
