### ISSUE TITLE
0.36 breaks my layouts across the board

### ISSUE THREAD

**Issue by mschipperheyn** [facebook/react-native#10615] opened 2016-10-29 01:47 UTC
Upgrading 0.35 to 0.36 breaks my layouts across the board. They are not small issues. I assume it has to do with the breaking changes. It would be nice if some additional information could be provided on what kind of typical issues can be expected and how to solve this.

**Comment by anttimo** [comment] 2016-10-29 06:08
Have you seen this change: https://github.com/facebook/react-native/commit/0a9b6bedb312eba22c5bc11498b1cc41363e5f27 ?

This is mentioned in the breaking changes of the release so maybe you already saw this but just in case since your issue sounds like it could be caused by it.

**Comment by mschipperheyn** [comment] 2016-10-29 12:55
I saw it. But a breaking change that breaks designs across the board, across components, is not a breaking change without a clear solution, well.... 

Assuming that this issue can be fixed on my side (it's not clearly indicated what to do with this breaking change), I'm looking at days and days of work. I have better things to do.

It's hard not to be pissed about the cavalier way in which these major changes are implemented. Not the first time either. Stylesheet processing shouldn't be this brittle. Have you ever seen an update to Chrome that broke designs across the board? There would be a riot. It's just not acceptable.

**Comment by ide** [comment] 2016-10-29 20:02
The commit that @anttimo linked explains how to fix layouts that might have changed. I've added that explanation to the release notes.

**Comment by mschipperheyn** [comment] 2016-10-29 21:35
Ok, I will have a look. But I dread the cascading effects in the numerous libraries I'm using.

**Comment by brentvatne** [comment] 2016-10-30 15:14
@mschipperheyn - unfortunately it's the cost of progress :( thanks for pointing out that release notes weren't descriptive enough, closing this issue!

**Closed by brentvatne** 2016-10-30 15:14 UTC
