### ISSUE TITLE
Error: UNKNOWN: unknown error, open 'C:\Users\me\.babel.json'

### ISSUE THREAD

**Issue by progrmor** [facebook/react-native#11803] opened 2017-01-10 09:52 UTC
This warning is produced when I initialize a new ReactNative project: `react-native init Test`

> npm WARN react-native@0.40.0 requires a peer of react@~15.4.0-rc.4 but none was
installed.

> npm WARN prefer global marked@0.3.6 should be installed with -g

and when I run `react-native start` from inside the project folder I get this error:

> Error: UNKNOWN: unknown error, open 'C:\Users\Me\\.babel.json'
at Object.fs.openSync <fs.js:557:18>
at Object.fs.writeFileSync <fs.js:1222:33>
at save <E:\Restoration\Workshop\App\Test\node-modules\babel-register\lib\cache.js:45:16>

and when the app launches on my device it shows:

> Could not get BatchedBridge, make sure your bundle is packaged correctly

* React Native version: react-native-cli: 2.0.1
* Platform: Android
* Operating System: Windows 7

**Comment by rmevans9** [comment] 2017-01-10 12:49
To fix the react warning ensure React at version 15.4.0-rc.4 is also installed to your project. I thought it got installed with init but it seems that may not be the case here.

Not sure what is going on with the marked dependency. I am not sure that it is a React Native dependency at all.

You have a babel.json file at C:\Users\Me that is invalid. Fix that or remove that. This was not created by React Native and is not needed unless you want to set some global babel settings for every project on your machine.

You are seeing that error because the packager failed to start because of the babel issue.

**Comment by progrmor** [comment] 2017-01-10 13:02
@rmevans9 how do I check if that version is installed to my project? The only variable I know how to get hold of is "react-native-cli: 2.0.1" . I managed to fix the babel.json issue by reinstalling everything a third time for some reason.

**Comment by rmevans9** [comment] 2017-01-10 13:08
All installed packages are listed in the package.json file in your project folder. You can also run `npm list --depth=0` in your project folder to see the version of all installed packages.

**Comment by progrmor** [comment] 2017-01-10 13:31
@rmevans9 Well it seems I have 2 versions above? 
`"dependencies": {
		"react": "15.4.2",
		"react-native": "0.40.0"
	},`

so do I need to downgrade or something?

**Comment by rmevans9** [comment] 2017-01-10 17:44
Not really - you can likely just let React stay the way it is as React Native will eventually catch up and use that version of React.

**Comment by rasenplanscher** [comment] 2017-02-08 08:13
Hey there,
I have run into this as well and debugged it as far as I could right now. The error arises from some race condition:
+ during the build, `babel-register` writes a cache to `~/.babel.json`, on every tick
+ since the write is synchronous, the race condition cannot arise within a single node thread
+ since node is single-threaded by design, this must be on account of some parallel execution in Java, triggering several parallel node threads

I have no idea why this doesn't happen to everybody or why this only happens after having used react native for some time...

This will need to be fixed in React Native, probably in coordination with `babel-register`...

I have posted this into [the related StackOverflow question](https://github.com/facebook/react-native/issues/11803) as well.

**Comment by stanonyime** [comment] 2017-05-04 12:06
Why was this issue closed? I'm still running into this issue

**Comment by wdamien** [comment] 2017-05-12 18:31
I was having this same issue, and for me deleting `node_modules` and reinstalling everything worked.  I'm not sure if it was a permissions issue or I just needed to get the latest packages, but either way that got my build working again. (Windows 10).

**Comment by alexisfontaine** [comment] 2017-05-13 20:26
I had the same issue (Windows 10) and disabling Babel's cache solved it. https://babeljs.io/docs/usage/babel-register/#environment-variables-babel-disable-cache

**Comment by elantion** [comment] 2017-05-18 01:17
I am facing this issue too. Using almost the same environment. Why was this issue closed? I follow the get-start tutorian and came out this issue. I think this should be an issue not a question.

**Comment by progrmor** [comment] 2017-05-19 08:13
Re-opening the issue since no solution was found and lots of other people seem to have the same problem.

**Comment by hramos** [comment] 2017-07-20 22:14
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/error-unknown-unknown-error-open-cusersmebabeljson

**Closed by hramos** 2017-07-20 22:14 UTC
Labels: Icebox
