### ISSUE TITLE
 bundling: UnableToResolveError

### ISSUE THREAD

**Issue by chandanGr** [facebook/react-native#14418] opened 2017-06-09 10:23 UTC
I installed react-native-fbsdk (Facebook SDK) for the login in my app and I get this error which I am not able to understand. 

error: bundling: UnableToResolveError: Unable to resolve module `prop-types` from `C:\Users\suhas\Documents\FacebookTest\node_modules\react-native-fbsdk\js\FBLikeView.js`: Module does not exist in the module map or in these directories:
  C:\Users\suhas\Documents\FacebookTest\node_modules
,   C:\Users\suhas\node_modules

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.
    at UnableToResolveError (C:/Users/suhas/Documents/FacebookTest/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:525:5)
    at ResolutionRequest._resolveNodeDependency (C:/Users/suhas/Documents/FacebookTest/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:394:11)
    at ResolutionRequest.resolveDependency (C:/Users/suhas/Documents/FacebookTest/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:141:29)
    at dependencyNames.map.name (C:/Users/suhas/Documents/FacebookTest/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:145:59)
    at Array.map (native)
    at ResolutionRequest.resolveModuleDependencies (C:/Users/suhas/Documents/FacebookTest/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:145:42)
    at Promise.resolve.then (C:/Users/suhas/Documents/FacebookTest/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:169:21)
    at process._tickCallback (internal/process/next_tick.js:109:7)
Bundling `index.android.js`  93.0% (408/423), failed.

**Comment by chandanGr** [comment] 2017-06-09 10:36
I am using Windows 10 and I am getting the same error even after running the following commands:
del node_modules && npm install
npm start -- --reset-cache

**Comment by hramos** [comment] 2017-06-09 17:04
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-09 17:04 UTC
