### ISSUE TITLE
Unhandled JS Exception: Unexpected token '{'. import call expects exactly one argument.  no stack

### ISSUE THREAD

**Issue by Steffi3rd** [facebook/react-native#24094] opened 2019-03-21 22:09 UTC
Everything's work fine until I build my project on Xcode to see my app on real device...

Everything is build fine with no errors, yarn start and Xcode Play button (for build)

<img width="498" alt="Capture d’écran 2019-03-21 à 23 06 17" src="https://user-images.githubusercontent.com/814410/54788090-2eddb880-4c2e-11e9-8b0a-2577ee55fb2b.png">

```
$ react-native info
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.1
      CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
      Memory: 170.70 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.10.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.0 => 0.59.0

```

**Comment by karanjthakkar** [comment] 2019-03-21 22:29
Can you provide a minimal reproducible example for this? That would help us narrow down the issue better.

**Comment by Gerlison** [comment] 2019-03-22 19:49
Seems like a error in your code. Can you provide a screenshot of console with Debug JS Remotely?

**Comment by turnrye** [comment] 2019-03-22 21:53
Hey @steffi3rd, I suspect that there's actually an issue in your project's code. I think if you look at Metro, you'll see a build-time error.

A few tips:

1. Try resetting all of the caches with:
```bash
 watchman watch-del-all && rm -rf $TMPDIR/react-native-packager-cache-* && rm -rf $TMPDIR/metro-bundler-cache-* && rm -rf node_modules/ && npm cache clean --force && npm install && npm start -- --reset-cache
```
2. Go ahead and upgrade to 0.59.1

Without a repository of your source, it's hard to give specific advice. This seems like an environment issue, but please do follow up with more detail if my pointers above don't help.

**Comment by Steffi3rd** [comment] 2019-03-22 22:01
I did 

```
watchman watch-del-all && rm -rf $TMPDIR/react-native-packager-cache-* && rm -rf $TMPDIR/metro-bundler-cache-* && rm -rf node_modules/ && npm cache clean --force && npm install && npm start -- --reset-cache
```

Now the error has changed but similar. 
I don't any details on "Extra Info"

- It works very well on Simulator. 
- Metro bundler is build fine
- Xcode project build success

![IMG_810D99BDE348-1](https://user-images.githubusercontent.com/814410/54855390-69ab2380-4cf6-11e9-8905-80709685bc12.jpeg)
![IMG_9447](https://user-images.githubusercontent.com/814410/54855391-69ab2380-4cf6-11e9-9139-39770c084d73.PNG)

**Comment by SourceCipher** [comment] 2019-05-12 22:48
Having the same issue.. Cant see whats causing this nonsense.. Metro running fine, everything compiles.. Upon app launch this error comes up with no indication.. Nothing in the console either..

**Comment by MaxBabenko** [comment] 2019-05-23 20:00
Got the same error. Renaming root `index.js` to `index.ios.js` did the trick for me. But I'm not sure what is the real issue here

**Comment by gianpaj** [comment] 2019-05-24 12:24
Upgrading to these versions seems to have fixed this issue for me on `react-native v0.59.8`

`package.json`
```diff
   "devDependencies": {
-    "@babel/core": "^7.4.4",
-    "@babel/runtime": "^7.4.4",
+    "@babel/core": "^7.4.5",
+    "@babel/runtime": "^7.4.5",
@@ -101,7 +101,7 @@
-    "metro-react-native-babel-preset": "^0.54.0",
+    "metro-react-native-babel-preset": "^0.54.1",
````

**Comment by satya164** [comment] 2019-05-30 15:47
I'm closing this issue since no repro was provided.

**Closed by satya164** 2019-05-30 15:47 UTC
Labels: Bug, Resolution: Needs Repro

**Comment by jeffreyhaen** [comment] 2019-06-13 14:05
I'm having the same issue after upgrading to RN 0.59.9. The error message gives basically no clue what's wrong...

**Comment by unmec** [comment] 2019-09-11 07:10
I had a similar issue with error ```Unhandled JS Exception: Unexpected identifier 'App'. import call expects exactly one argument. no stack```

So the problem is apparently ```import App from './App';```

I had several code blocks and reminders commented out above it, removing all these comments then the build is successful. So I suggest you to check your import methods.

Also, be careful when comment out code in RN in general, especially within render function. Hope it's helpful.

**Comment by unmec** [comment] 2019-09-11 11:00
UPDATE

OK here is the digest of a few good hours spent:

In your ```index.js```, there is something like this:
```
import { name as appName } from './app.json';
AppRegistry.registerComponent(appName, () => App);
```

Which import the name from app.json
```
{
  "name": "yourAppName",
  "displayName": "yourAppName"
}
```

To get rid of this error, just change ```index.js``` to:
```
AppRegistry.registerComponent('yourAppName', () => App);
```
and stop importing that json file.

You can keep all your present settings in ```devDependencies```

**Comment by ghasemikasra39** [comment] 2019-10-05 06:23
same issue

**Comment by wuweijian1997** [comment] 2019-10-24 03:00
Windows 10 - Android
![image](https://user-images.githubusercontent.com/29529286/67449329-68572600-f64c-11e9-8f0e-191f1ec9cab5.png)
`
info
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
      Memory: 1.19 GB / 7.91 GB
    Binaries:
      Node: 10.16.3 - C:\kafka\setting\node\node.EXE
      Yarn: 1.19.1 - C:\kafka\setting\yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\kafka\setting\node\npm.CMD
`
same issue

**Comment by ajGingrich** [comment] 2019-10-27 19:31
I fixed this problem by deleting the entire `babel.config.js` for the time being and letting react-native handle babel

**Comment by wonga151** [comment] 2020-02-09 00:06
If this helps anyone I had the same issue and this helped me solve it. https://github.com/facebook/react-native/issues/21530#issuecomment-427577349
