### ISSUE TITLE
Poor iOS sim performance when one or more extra tabs in Chrome opened alongside Debugger

### ISSUE THREAD

**Issue by jdoyle65** [facebook/react-native#10705] opened 2016-11-02 18:27 UTC
### Description

iOS Simulator connected to debugger runs very slow in Chrome when the Chrome Window containing the debugging tab also has any other tabs. If the only tab open is the debugging tab, everything runs smooth as normal.

### Reproduction

1) Open up React Native app in iOS sim, and enable remote JD debugging.
2) Open up a second tab along side the React Native Debugger tab.
3) Watch as performance of simulator drastically decreases (sometimes this decrease in performance is delayed, and takes a few minutes to set in).
4) Close the second tab you opened in step 2, leaving ONLY the React Native Debugger tab open.
5) Performance returns to normal.

This issue was reproduced on another colleague's machine on a completely different project, but started happening to both of us at the same time. We suspect an update to Chrome is the root cause for this.

### Additional Information

* React Native version: 0.34
* Platform: iOS
* Operating System: MacOS
* Chrome version: 54.0.2840.71 (64-bit)

**Comment by marcosinigaglia** [comment] 2016-11-03 11:42
Same problem on real device and RN 0.36, using Firefox I have no issue.

**Comment by davidgruebl** [comment] 2016-11-03 13:54
@jdoyle65 I'm experiencing the same issue. As a workaround using the [React Native Debugger
](https://github.com/jhen0409/react-native-debugger) works for me. Hope this is helpful :)

**Comment by hramos** [comment] 2016-11-03 14:18
Thanks for the issue! This seems to be a duplicate of #10559.

**Closed by hramos** 2016-11-03 14:18 UTC
