### ISSUE TITLE
Keyboard.addListener('keyboardDidShow', ...) callback is invoked with inaccurate measures in Android devices with notch

### ISSUE THREAD

**Issue by jsamr** [facebook/react-native#27089] opened 2019-11-02 10:38 UTC
### Incriminated API

``` js
// In Android
Keyboard.addListener('keyboardDidShow', e => {
   // On OnePlus 7, and Pixel 3XL (simulator) this value is underestimated by exactly StatusBar.currentHeight.
    e.endCoordinates.height
})
```

### Prerequisites

In `AndroidManifest.xml`, set `android:windowSoftInputMode="adjustPan"`.

### Visual tests

*The black horizontal bar should be the same width (40dp) as the red bar, in a container with a bottom padding of the keyboard's height. This component mimics KeyboardAvoidingView with behavior padding set. The height of keyboard should be the same as the height of the red bar. The issue has been reproduced with GBoard, SwiftKey...*

**Remarks**: *I would have imagined that the view height would equal keyboard height + keyboard Y. But that is only true ... on OnePlus7, which is the problematic device!*

| Emulator, Pixel 2 XL, Android 10 | OnePlus 7, Android 10, OxygenOS 10.0.1 |
|:-------------:|:-------------:|
| <img src="https://user-images.githubusercontent.com/3646758/68069734-282a2e80-fd43-11e9-80ab-891cd31aa08f.png" width="400"> | <img src="https://user-images.githubusercontent.com/3646758/68069735-2a8c8880-fd43-11e9-8805-ee96e1eaea46.jpg" width="400"> |

React Native version:
```
System:
    OS: Linux 4.19 Manjaro Linux undefined
    CPU: (8) x64 Intel(R) Core(TM) i7-8809G CPU @ 3.10GHz
    Memory: 565.35 MB / 31.33 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.0 - /usr/bin/node
    npm: 6.12.0 - /usr/bin/npm
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
  npmPackages:
    react: 16.8.1 => 16.8.1 
    react-native: 0.61.3 => 0.61.3
```

## Steps To Reproduce

1. Open the reproduction demo in a Pixel 3XL emulator with Android 10+.
2. Observe that `KeyboardAvoidingView` with behavior padding doesn't add enough padding.

Describe what you expected to happen: The padding should match keyboard's real height.

**Full reproduction** : [react-native-oneplus7-keyboard-height-discrepancy
](https://github.com/jsamr/react-native-oneplus7-keyboard-height-discrepancy)

## Observations

- `StatusBar.currentHeight` is substituted to the keyboard layout end frame `height`.
- `StatusBar.currentHeight` is also substituted from keyboard layout end frame `screenY`

**Comment by jsamr** [comment] 2020-01-20 19:45
Just preventing this silly bot from the future: the issue is still there!

**Comment by shaneschulte** [comment] 2020-01-21 19:22
I've also observed a similar issue between devices (in this case, Google Pixel 3 and Essential Phone)

**Comment by TuurDutoit** [comment] 2020-03-19 14:45
Do these devices have notches? I think this might be the same as this: https://github.com/facebook/react-native/issues/26296

**Comment by jsamr** [comment] 2020-06-17 15:19
Has anyone been able to reproduce the issue with the latest RN release?

**Comment by TuurDutoit** [comment] 2020-06-17 15:22
We haven't upgraded yet, so I haven't been able to test. Your demo repo should be easy to upgrade and test though.

**Comment by fabriziobertoglio1987** [comment] 2020-07-06 08:59
we need OnePlus 7 so this issue will not be solved... I don't have such device OnePlus 7

**Comment by jsamr** [comment] 2020-07-06 11:38
OK I am gooing to test soon.

**Comment by fabriziobertoglio1987** [comment] 2020-07-08 14:44
@jsamr I wrote a pull request https://github.com/facebook/react-native/pull/29292 that fixes the same issue with event `keyboardDidHide`. I can not reproduce your issue as I don't have a OnePlus device.  and I can not fix it, but you can try applying a similar fix 

https://github.com/facebook/react-native/blob/cfa42605989eee5a9de42bdb1259fb7f4d9451fb/ReactAndroid/src/main/java/com/facebook/react/ReactRootView.java#L671-L677

you can build from source, change the above source code with either numbers like `10` or `900` and see the effect to understand how the function works.
https://github.com/facebook/react-native/wiki/Building-from-source#publish-your-own-version-of-react-native

This is the definition of `createKeyboardEventPayload`
https://github.com/facebook/react-native/blob/cfa42605989eee5a9de42bdb1259fb7f4d9451fb/ReactAndroid/src/main/java/com/facebook/react/ReactRootView.java#L755-L770

Those values are returned to the `react-native` javascript library which is responsible for displaying the Black Area

![image](https://user-images.githubusercontent.com/24992535/86932775-16065880-c13a-11ea-8bb4-f958e16ba2bc.png)

additionally there is no OxygenOS emulator https://stackoverflow.com/a/43549663/11452286

**Comment by lightrow** [comment] 2020-07-14 17:44
i have this issue on oneplus 6, i need to add exactly 30dp for it to be perfect. On the iOS simulator it's the other way around, i need to subtract some value, and the value is not always the same.

**Comment by jsamr** [comment] 2020-11-14 16:15
I have updated the reproduction to React Native 0.63.3 and it consistently fails on any device with a notch, including the Pixel 3XL in emulator. I noticed that the underestimated height consistently corresponds to the height of `StatusBar.currentHeight`.

**Comment by fabriziobertoglio1987** [comment] 2020-11-16 07:33
<image src="https://user-images.githubusercontent.com/24992535/99224211-2e703900-27e6-11eb-82de-12c674f87372.png" width="300" />
not releated to my commit which for my understanding is still in master. Hopefully gets fixed by https://github.com/facebook/react-native/pull/29292. Thanks

**Comment by jsamr** [comment] 2020-11-16 10:09
@fabriziobertoglio1987 I thought your PR was only about keyboardDidHide?

**Comment by fabriziobertoglio1987** [comment] 2021-02-08 11:33
https://github.com/facebook/react-native/blob/d79212120b7168015d3d0225ef372ed851a230fa/ReactAndroid/src/main/java/com/facebook/react/ReactRootView.java#L757-L758

Without Notch
`DisplayMetricsHolder.getWindowDisplayMetrics().heightPixels` returns 1794

With Notch
`DisplayMetricsHolder.getWindowDisplayMetrics().heightPixels` returns 1668

The docs info on [`android:windowSoftInputMode`](https://developer.android.com/guide/topics/manifest/activity-element) `adjustPan`

![image](https://user-images.githubusercontent.com/24992535/107213131-3ec03a80-6a08-11eb-8fde-5ddde36f7673.png)

**<details><summary>CLICK TO OPEN TESTS RESULTS</summary>**
<p>

Without Notch
`DisplayMetricsHolder.getWindowDisplayMetrics().heightPixels` returns 1794

| **BEFORE** | **AFTER** | 
|:-------------------------:|:-------------------------:|
| <img src="https://user-images.githubusercontent.com/24992535/107212700-a1fd9d00-6a07-11eb-9248-26f9c4d92ae3.png" width="300" height="" /> | <img src="https://user-images.githubusercontent.com/24992535/107212590-7975a300-6a07-11eb-89f4-891a37a7c406.png"  width="300" height="" /> |

With Notch
`DisplayMetricsHolder.getWindowDisplayMetrics().heightPixels` returns 1668

| **BEFORE** | **AFTER** | 
|:-------------------------:|:-------------------------:|
| <img src="https://user-images.githubusercontent.com/24992535/107212619-81cdde00-6a07-11eb-9630-7e7c8c34d798.png" width="300" height="" /> | <img src="https://user-images.githubusercontent.com/24992535/107212707-a4f88d80-6a07-11eb-9134-f077059c83a6.png"  width="300" height="" /> |
</p>
</details>

My observations:
- The issue seems to be the MainActivity not respecting the rule `android:windowSoftInputMode="adjustPan"` and not `KeyboardAvoidingView`.
- `DisplayMetricsHolder.getWindowDisplayMetrics().heightPixels` value of  `1668` seems to be correct

**Comment by jsamr** [comment] 2021-02-08 14:13
@fabriziobertoglio1987 Which version / branch are you using to perform those tests?

**Comment by jsamr** [comment] 2021-02-08 14:49
@fabianeichinger I've updated the example here: https://github.com/jsamr/react-native-oneplus7-keyboard-height-discrepancy
It is much more straightforward. With react-native@0.63.4, you can very well see the keybord height discrepancy in the below screenshots. The height of the red bar is assigned to `ev.endCoordinates.height` (`keyboardDidShow`). The red bar has been duplicated to bottom for height comparison with Keyboard:

<table>
    <tr>
        <th>Emulator, Pixel 3 XL, Android 10 (simulator)</th>
        <th>Nexus 5X, Android 10 (simulator)</th>
    </tr>
    <tr>
        <td valign="top"><img src="https://raw.githubusercontent.com/jsamr/react-native-oneplus7-keyboard-height-discrepancy/master/images/pixel-3xl.png" width="400"></td>
        <td valign="top"><img src="https://raw.githubusercontent.com/jsamr/react-native-oneplus7-keyboard-height-discrepancy/master/images/nexus-5x.png" width="400"></td>
    </tr>
</table>

I haven't dig into the native java code, and I am not familiar with Android UI APIs. But perhaps what you're showing is actually the fixed version on master.

**Comment by fabriziobertoglio1987** [comment] 2021-02-08 15:26
Thanks for your feedback @jsamr I allways work with the updated react-native master branch

My main point in message https://github.com/facebook/react-native/issues/27089#issuecomment-775080854 was that the keyboard height was not causing this issue, but the presence of a Notch or No Notch

Now you include different scenarios with different status bars.. I can not say about that, but I can say that `DisplayMetricsHolder.getWindowDisplayMetrics().heightPixels` values seems to me correct taking in consideration we added the `notch` to the device.

The screenshots you include are:
- from two different devices
- with 2 different StatusBar heights
- with 2 different keyboards

I would avoid to add more troubleshooting scenarios, but actually to limit the number of scenarios and identify the bug

What is causing your issue? 
The Notch? The StatusBar? The Keyboard?

Maybe you think the computation of the Keyboard Height is wrong?

This does not make sense, because if I remove the Notch it works perfectly.

**<details><summary>CLICK TO OPEN TESTS RESULTS</summary>**
<p>

Without Notch
`DisplayMetricsHolder.getWindowDisplayMetrics().heightPixels` returns 1794

| **BEFORE** | **AFTER** | 
|:-------------------------:|:-------------------------:|
| <img src="https://user-images.githubusercontent.com/24992535/107212700-a1fd9d00-6a07-11eb-9248-26f9c4d92ae3.png" width="300" height="" /> | <img src="https://user-images.githubusercontent.com/24992535/107212590-7975a300-6a07-11eb-89f4-891a37a7c406.png"  width="300" height="" /> |

With Notch
`DisplayMetricsHolder.getWindowDisplayMetrics().heightPixels` returns 1668

| **BEFORE** | **AFTER** | 
|:-------------------------:|:-------------------------:|
| <img src="https://user-images.githubusercontent.com/24992535/107212619-81cdde00-6a07-11eb-9630-7e7c8c34d798.png" width="300" height="" /> | <img src="https://user-images.githubusercontent.com/24992535/107212707-a4f88d80-6a07-11eb-9134-f077059c83a6.png"  width="300" height="" /> |
</p>
</details>

**Comment by TuurDutoit** [comment] 2021-02-08 16:19
As I understand it, the height of the keyboard, as reported in the event object, changes based on the presence of a notch. In fact, looking at your test screenshots, you can see this exact issue: in the case with _no_ notch, the height is reported as 282dp; in the case _with_ a notch, it reports 234dp! That would mean the height of the keyboard changed, but it doesn't look like that's the case.

**Comment by jsamr** [comment] 2021-02-08 16:33
@fabianeichinger The goal of the screenshots is to compare with notch (Pixel 3XL) and without notch (Nexus 5X). With notch, the red vertical bar height doesn't match the keyboard's height. Without, it does.

> with 2 different keyboards

That was because I used android 10 in the Pixel and android 11 in the nexus. I have fixed that issue and updated the screenshots. But anyway, the relevant part is that **it seems that having a notch causes `ev.endCoordinates.height` to be miscalculated**. Compare the vertical red bar with keyboard's height on the Pixel, you'll notice a mismatch.

**Comment by fabriziobertoglio1987** [comment] 2021-02-08 17:26
Thanks, you are both right. I believe the best solution is using the Android API to calculate the Keyboard height instead of calculating it as the difference

https://github.com/facebook/react-native/blob/d79212120b7168015d3d0225ef372ed851a230fa/ReactAndroid/src/main/java/com/facebook/react/ReactRootView.java#L757-L758

**Comment by jsamr** [comment] 2021-02-08 17:28
@fabianeichinger Thank you so much for your great involvement in this open source project, looking forwards for your take on this!

**Comment by fabriziobertoglio1987** [comment] 2021-02-09 10:08
Thanks a lot @jsamr My ambition is to really get to know the reactnative sourcecode and hopefully one day give relevant contributions to the community

The issue is caused by [`getWindowDisplayFrame`](https://github.com/aosp-mirror/platform_frameworks_base/blob/master/core/java/android/view/View.java) which sets the `mVisibleViewArea.bottom` used to compute the keyboard height. 

https://github.com/facebook/react-native/blob/1049835b504cece42ee43ac5b554687891da1349/ReactAndroid/src/main/java/com/facebook/react/ReactRootView.java#L756

- `mVisibleViewArea.bottom` is `1794` when the keyboard is hidden and covers the entire screen from top to bottom
- `mVisibleViewArea.bottom` is `1053` when the keyboard is open and cover from the top till the top margin of the keyboard

This computation is wrong and does not take in consideration the Notch or other screen decorations, as you can see below does not change the total height when using the notch.

I think that **I found a workaround** to fix this by calculating the notch height and substracting it from the above calculation. I will publish my pr soon. I researched and it is common practice on Android Sdk to calculate keyboard height by deducting it from other parameters


**<details><summary>MORE DETAILS</summary>**
<p>

**Without Notch**
- `DisplayMetricsHolder.getWindowDisplayMetrics().heightPixels` is `1794`
- `mVisibleViewArea.bottom` is `1794`

**With Notch**
- `DisplayMetricsHolder.getWindowDisplayMetrics().heightPixels` is `1668`
- `mVisibleViewArea.bottom` is `1794`
The android `View` sourcecode is available [here](https://github.com/aosp-mirror/platform_frameworks_base/blob/master/core/java/android/view/View.java)

```java
    /**
     * Retrieve the overall visible display size in which the window this view is
     * attached to has been positioned in.  This takes into account screen
     * decorations above the window, for both cases where the window itself
     * is being position inside of them or the window is being placed under
     * then and covered insets are used for the window to position its content
     * inside.  In effect, this tells you the available area where content can
     * be placed and remain visible to users.
     *
     * <p>This function requires an IPC back to the window manager to retrieve
     * the requested information, so should not be used in performance critical
     * code like drawing.
     *
     * @param outRect Filled in with the visible display frame.  If the view
     * is not attached to a window, this is simply the raw display size.
     */
    public void getWindowVisibleDisplayFrame(Rect outRect) {
        if (mAttachInfo != null) {
            try {
                mAttachInfo.mSession.getDisplayFrame(mAttachInfo.mWindow, outRect);
            } catch (RemoteException e) {
                return;
            }
            // XXX This is really broken, and probably all needs to be done
            // in the window manager, and we need to know more about whether
            // we want the area behind or in front of the IME.
            final Rect insets = mAttachInfo.mVisibleInsets;
            outRect.left += insets.left;
            outRect.top += insets.top;
            outRect.right -= insets.right;
            outRect.bottom -= insets.bottom;
            return;
        }
        // The view is not attached to a display so we don't have a context.
        // Make a best guess about the display size.
        Display d = DisplayManagerGlobal.getInstance().getRealDisplay(Display.DEFAULT_DISPLAY);
        d.getRectSize(outRect);
    }
```

</p>
</details>

**Closed** 2021-09-28 17:42 UTC
Labels: Platform: Android, Platform: Linux, API: Keyboard, Bug
