### ISSUE TITLE
[Android only] [ActivityIndicatorIOS] SyntaxError: Attempted to redefine propterty '__source'

### ISSUE THREAD

**Issue by Swordsman-Inaction** [facebook/react-native#7841] opened 2016-05-31 03:50 UTC
* react-native-cli: 0.2.0
* react-native: 0.25.1
* Mac

![image](https://cloud.githubusercontent.com/assets/12252463/15662586/ae9b3296-2724-11e6-9200-4c0e461b9918.png)

**SyntaxError: Attempted to redefine propterty '__source'**
I only got this error on Android, IOS is fine. And if I try to debug, the error disappeared without any console error log.

I pulled the `ReactNativeDevBundle.js`, and I found this:
```
module.exports=emptyFunction;
});
__d(14 /* ActivityIndicatorIOS */, function(global, require, module, exports) {'use strict';var _jsxFileName='/Users/edward/native/node_modules/react-native/Libraries/Components/ActivityIndicatorIOS/ActivityIndicatorIOS.android.js',_jsxFileName2='/Users/edward/native/node_modules/react-native/Libraries/Components/ActivityIndicatorIOS/ActivityIndicatorIOS.android.js';

var React=require(15 /* React */);
var View=require(313 /* View */);

var ActivityIndicatorIOS=React.createClass({displayName:'ActivityIndicatorIOS',
render:function render(){
return React.createElement(View,babelHelpers.extends({},this.props,{__source:{fileName:_jsxFileName,lineNumber:18},__source:{fileName:_jsxFileName2,lineNumber:18}}));}});

```
It seems that the `ActivityIndicatorIOS.android.js` is been compiled twice. 

And I've tried to clean cache of npm, but it didn't work anyway.

**Comment by charpeni** [comment] 2016-05-31 19:51
I'll close this issue since it's seem a duplicate of #7592.

Let me know if it's not fixed.

**Comment by charpeni** [comment] 2016-05-31 19:51
@facebook-github-bot duplicate #7592

**Comment by facebook-github-bot-5** [comment] 2016-05-31 19:54
@charpeni tells me this issue is a duplicate of #7592. Let's discuss there, closing this one.

**Closed by facebook-github-bot-5** 2016-05-31 19:54 UTC
Labels: Ran Commands

**Comment by Swordsman-Inaction** [comment] 2016-06-01 02:27
Thanks man.
