### ISSUE TITLE
Command /bin/sh failed with exit code 127

### ISSUE THREAD

**Issue by shahzeb1** [facebook/react-native#3946] opened 2015-11-06 09:11 UTC
(Using Node version v4.2.1)
 
This is the terminal window when I click on build inside of XCode: 

```shell
/Users/bla/Documents/ios-apps/emesgee/node_modules/react-native/local-cli/cli.js:56
  const setupEnvScript = /^win/.test(process.platform)
  ^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
Process terminated. Press <enter> to close the window
```

**Comment by topicus** [comment] 2015-11-06 14:09
Same issue here.

**Comment by adamtwiss** [comment] 2015-11-06 15:21
Same here ...  happy to help with any diagnostics.  I am using react-native-cli 0.1.7 and Node v5.0.0

I thought I'd have a quick at just commenting out the 'use strict;' in cli.js to see if that would fix it.

But then I get:

```
/Users/adam/Documents/code/AwesomeProject/node_modules/react-native/local-cli/cli.js:104
class CreateSuppressingTerminalAdapter extends TerminalAdapter {
^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
Process terminated. Press <enter> to close the window
```

**Comment by MicheleBertoli** [comment] 2015-11-06 15:24
+1

**Comment by ffugly** [comment] 2015-11-06 15:36
+1

**Comment by shahzeb1** [comment] 2015-11-06 15:53
Temporary work around (to at least get React Native working):

1. Use node version v4.2.1
2. `cd` into [your app]/node_modules/react-native/packager
3. Run `./packager.sh` (for some reason this runs fine
4. Go into XCode and go to the Build Phases tab.
5. Remove the last item on the list (the one that runs the script). So you're left with Target Dependencies, Compile Sources, Link Binary With Libraries, and Copy Bundle Resources. 

Now run the app. Since the shell script is no longer part of the XCode build routine, it shouldn't fail. And if you have the react native client server running in another terminal window, then everything should get build fine.

**Comment by bradbumbalough** [comment] 2015-11-06 16:32
Thanks @shahzeb1, that solved my problem.

**Comment by TalkingQuickly** [comment] 2015-11-06 16:38
+1

**Comment by l-lawliett** [comment] 2015-11-06 18:51
Thats greate but all you need to do is just delete the last Item in Build Phase in Xcode perfect not a work around dont need to cd into anything after that

**Comment by asamiller** [comment] 2015-11-06 20:46
Running `react-native upgrade` fixed this for me.

**Comment by shahzeb1** [comment] 2015-11-06 21:40
@asamiller I got the following error in terminal `Command `upgrade` unrecognized. Did you mean to run this inside a react-native project?`

**Comment by nvcken** [comment] 2015-11-07 05:42
same here.
+1

**Comment by m20io** [comment] 2015-11-07 14:49
+1

**Comment by m20io** [comment] 2015-11-07 15:08
Anybody figured out a solution for this with android?

**Comment by m20io** [comment] 2015-11-07 15:26
ok it seams to be enough to run separatly
`[your app]/node_modules/react-native/packager/packager.sh`

**Comment by sarahsalder** [comment] 2015-11-07 17:36
+1

**Comment by sarahsalder** [comment] 2015-11-07 17:48
@shahzeb1 your workaround worked for me as well. thanks

**Comment by gre** [comment] 2015-11-09 10:15
related https://github.com/facebook/react-native/issues/3948

**Comment by marcshilling** [comment] 2015-11-09 22:14
Deleting that build step works and all, but I'm pretty sure that step is required to get the new assets system working when you bundle for running on device...
At least, that's what I'm experiencing...no images appear when bundled.

**Comment by paulgessinger** [comment] 2015-11-10 00:05
That's what I thought too. Images are acting all kinds of weird after deleting this step.

**Comment by huitsing** [comment] 2015-11-10 00:15
+1

**Comment by shahzeb1** [comment] 2015-11-10 00:34
Does adding 'source ~/.bash_profile' to the top of packager.sh and keeping the build step work?

**Comment by sulliwane** [comment] 2015-11-10 03:43
I solved this by creating symlink for react-native and node:
```
sudo ln -s /Users/CNme/.nvm/versions/node/v4.2.1/bin/react-native /bin/react-native
sudo ln -s /Users/CNme/.nvm/versions/node/v4.2.1/bin/node /bin/
```

**Comment by shahzeb1** [comment] 2015-11-10 05:35
react-native 0.14.2 seems to have fixed this issue.

**Comment by MossP** [comment] 2015-11-11 13:06
I don't believe this is fixed.. Installing plugins can still lead to the error as well as referencing images that aren't present in the project. The error message doesn't give any indication as to what the cause is. It just fails. I have resorted to remming out masses of code just so that I can push a build to the device then unrem them and reload JS from device so that I can get an error message with any meaning. Something's a bit off here.

**Comment by Thorbenandresen** [comment] 2015-11-11 16:36
How can I restore the deleted Build Phase as suggested by @shahzeb1? My problem is now that my build freezes (for all of my RN project) at `Running 1 of 1 custom shell scripts` and I suspect that this because I delete that build phase.

**Comment by robinsonlam** [comment] 2015-11-12 03:32
Hey guys, not sure if it's the exact same issue.
I use zsh so in my build phase under *Bundle React Native code and images* I changed my shell from `/bin/sh` to `/usr/local/bin/zsh`

Hope that helps

**Comment by rubinovitz** [comment] 2015-11-16 22:32
This is broken for me.

**Comment by fforres** [comment] 2015-11-17 14:35
In case you are using OHMYZSH @robinsonlam comment was really helpful.
```
which zsh
```
tells you the bin location for the zsh.

Also, i had to enable the "Run script only when installing" option

**Comment by Thorbenandresen** [comment] 2015-11-17 21:11
@fforres if you remove "Run script only when installing" then you wont be able to bundle, correct?

**Comment by franfran** [comment] 2015-11-18 06:40
In my case

```
../node_modules/react-native/packager/react-native-xcode.sh: line 45: react-native: command not found
Command /bin/sh failed with exit code 127
```

Environment:
xcode 6.3.1 + react native 0.14.2 produced the error above

xcode 6.3.1 + react native 0.12.0 was running fine

I upgraded xcode to 7.1.1 and problem solved.

**Comment by Thorbenandresen** [comment] 2015-11-18 16:25
Upgrading to 7.1.1. did not do the job for me either :(

**Comment by browniefed** [comment] 2015-11-18 18:50
This issue deals with installed node via nvm and not having your `/.bash_profile` sourced, or whatever else you are using as a profile. You may need to add your nvm configuration to whichever profile you use and then additionally add the `source ~/.bash_profile` or whichever profile to the top of `react-native-xcode.sh` file. 
I believe this has been fixed in master though.

**Comment by stoitsev** [comment] 2015-11-18 19:35
My problem was that I installed node 4.2.2 with nvm but did not set it to be the default version. The shell that was running the build process had my default node.js running which was very old. To fix it, I ran:

```
nvm alias default 4.2.2
```

**Comment by strefethen** [comment] 2015-11-18 23:32
I got this error trying to run the RN bundler from Terminal here is what worked for me (see "start" defined below):

nvm exec npm start

In our package.json we have "start" defined as follows:

  "scripts": {
    "start": "node_modules/react-native/packager/packager.sh --root ./ReactComponent --assetRoots ./iPhoneGeo/Images.xcassets",
...
ReactComponent and iPhoneGeo are specific to our project

**Comment by Thorbenandresen** [comment] 2015-11-20 16:50
https://github.com/facebook/react-native/issues/3948#issuecomment-158457216

**Comment by tonylukasavage** [comment] 2015-11-20 22:10
I'm having the same problem with the following setup, also using `zsh`:

* Mac OSX 10.10.5
* node.js 4.2.2 (via nvm)
* XCode 7.1.1

The workaround suggested by @m20io by running the `[your app]/node_modules/react-native/packager/packager.sh` script manually was the workaround that worked for me.

**Comment by alfrednerstu** [comment] 2015-11-23 13:08
I get the same `Command /bin/sh failed with exit code 127` when trying to build in Xcode.

The terminal says this:
```
Error: Cannot find module 'amdefine'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/alfred/Dropbox/_PROJECTS/slamdunk/node_modules/react-native/node_modules/babel-core/node_modules/source-map-support/node_modules/source-map/lib/source-map/source-map-generator.js:8:18)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
Process terminated. Press <enter> to close the window
```

**Comment by gpbl** [comment] 2015-11-23 18:42
Had same problem too, node `5.1.0`. Fixed with `npm i react-native-cli -g`.

**Comment by Clunt** [comment] 2015-11-24 03:19
I had the same problem too, but when I check my nvm default I solve this problem.
I use node@4.2.1 in work terminal,but the node@0.12.0 is my nvm default setting. When run the ios project, system will open a new terminal use node@0.12.0.
*So, Please check your node version in nvm default.*
```sh
$ nvm ls
>        v0.10.33
>         v0.12.0
> ->       v4.2.1
> default -> v4.2.1
> node -> stable (-> v4.2.1) (default)
> stable -> 4.2 (-> v4.2.1) (default)
> iojs -> iojs- (-> N/A) (default)
```
*If not, set the default version(v4.2.1) or your lastest version.*
```sh
$ nvm alias default v4.2.1
```

**Comment by vincentbello** [comment] 2015-11-30 06:03
`source ~/.bashrc` (wherever your nvm config is) fixed my issue.

**Comment by xxmyjk** [comment] 2015-12-31 08:59
I got the same problem, using nvm causing it !  `Command` + `R` will run the default alias node version in nvm, so use 
```
nvm alias default v4(or newer)
```
will help it.

**Comment by jooj123** [comment] 2016-01-23 06:24
@fforres that did the trick for me, thanks

**Comment by charleschu-cc** [comment] 2016-01-29 15:33
setting the nvm default version works for. But, run 'nvm which 4.2' to get the correct version. 

nvm alias default 4.2.2

**Comment by MacgyverMartins** [comment] 2016-02-01 12:49
+1

My setup, also using zsh:

- Mac OSX 10.11
- Node v5.0 (nvm)
- Xcode 7.2

I got the error 
```bash
Users/macgyvermartins/Development/AwesomeProject/node_modules/react-native/local-cli/cli.js:74
  const setupEnvScript = /^win/.test(process.platform)
  ^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at `node.js:814:3
```

**Comment by MacgyverMartins** [comment] 2016-02-01 13:27
Well, I fix the error change zsh in shell, like @robinsonlam was commented and setting nvm default:
`nvm alias default v5.0.0`

Now it's work!

**Comment by marcgarreau** [comment] 2016-02-04 18:59
+1, broken out of the box for node version `4.2.6`. Issue resolved for me by just switching to `4.2.1` or `5.5.0` (only two I tried). Switching back to `4.2.6` after a successful run on one of the others works too.

**Comment by adokania** [comment] 2016-03-03 05:08
What worked for me is running 'npm start' from react-native root..

**Comment by hchoriq** [comment] 2016-03-03 16:22
nvm alias default v5.6.0 did it for me. It was referencing an older node version by default.

**Comment by jsierles** [comment] 2016-03-20 18:02
@facebook-github-bot answered

**Closed** 2016-03-20 18:04 UTC
Labels: Ran Commands

**Comment by SudoPlz** [comment] 2016-03-21 17:20
For people that still struggle with this, [THIS so answer](http://stackoverflow.com/questions/13006464/how-to-fix-the-issue-command-bin-sh-failed-with-exit-code-1-in-iphone/29211118#29211118) immediately solved my problem with 1 click.

**Comment by Muneefm** [comment] 2016-05-03 18:11
Hi.  
i had this issue couple days ago. and i was stuck with this.   i tried everything i saw in here and stackoverflow.    and at last i sorted out the issue.   

my issue was i had already installed the node.js for some other reason..  and when i started with react native i reinstalled the node through nvm.  but it seams like react was using the node that i have already installed.    i guess that was old version.  anyway  so i just removed every node modules. and reinstalled  everything.   this answer helped me for that. http://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x

**Comment by SudoPlz** [comment] 2016-06-03 12:18
SOLVED: For people looking for an answer to this in the future just add the line this SO post says. http://stackoverflow.com/questions/37230040/why-does-mainjs-bundle-not-build-with-reactnative-0-25-1/37614200#37614200
