### ISSUE TITLE
iOS borderWidth smaller than 0.5 

### ISSUE THREAD

**Issue by atlanteh** [facebook/react-native#12401] opened 2017-02-15 13:49 UTC
### Description

In iOS, setting a borderWidth of less than 0.5 results in incorrect behaviour of the entire View background is distorted
<img width="174" alt="screen shot 2017-02-15 at 3 47 28 pm" src="https://cloud.githubusercontent.com/assets/3952700/22977158/3902f124-f396-11e6-941b-e4abfe6f493b.png">

### Reproduction
```
<View style={{width: 200, height: 200, backgroundColor: 'white', borderColor: 'green', borderWidth: 0.2 }} />
```

https://rnplay.org/apps/BZSqVA

### Additional Information

* React Native version: 0.41.2
* Platform: iOS
* Operating System: MacOS

**Comment by niztal** [comment] 2017-02-15 14:50
+1

**Comment by minhtc** [comment] 2017-02-16 07:35
occurs on plus device when I set borderWidth = 0.5

**Comment by soorajvnair** [comment] 2017-02-21 22:04
Yes i can confirm this is happening on my end too.

**Comment by ericvicenti** [comment] 2017-03-06 08:12
I'm going to close this because I don't think it makes sense to set a borderWidth to `0.2`

**Comment by atlanteh** [comment] 2017-03-06 08:16
Why not? We use it both in android and in ios.. this makes the border very thin like we need it..
If you think this makes no sense then we need to disallow it both in android and ios. not let them behave differently.
(BTW I liked ur fbstart lecture :+1:  )

**Comment by ericvicenti** [comment] 2017-03-06 08:24
On iOS it doesn't make sense to set the width to something less than the `StyleSheet.hairlineWidth`, because it will be less than a physical pixel.

Glad you liked the AMA! 😄

**Comment by atlanteh** [comment] 2017-03-06 08:28
So you're saying that in android it's ok two have 0.2 borderWidth but on ios it's not?

**Comment by mintotsai** [comment] 2017-03-06 19:56
There's a bug here. I'm running on the iPhone 7 Plus simulator. React native 0.40.0.

```
console.log('>>>StyleSheet.hairlineWidth='+StyleSheet.hairlineWidth);
>>>StyleSheet.hairlineWidth=0.3333333333333333
```

However, "setting borderWidth: 0.5" results in the same behavior as that in the first comment.

**Comment by bsiddiqui** [comment] 2017-03-10 19:26
@ericvicenti agree that it doesn't make sense to set borderWidth < StyleSheet.hairlineWidth but there's still a bug.

On iPhone 7 plus StyleSheet.hairlineWidth === 0.3333333333333333.

Setting borderWidth to 0.5 should work, right? It doesn't - it's distorted like the original post mentions. Setting it to 0.66 works as expected though. Seems like unpredictable behavior to me.

**Comment by niztal** [comment] 2017-03-14 07:56
@ericvicenti I think this issue should be reopened since it was prove by all the guys here , that the problem exist.
Thanks.

**Comment by aknad** [comment] 2017-03-28 08:21
in my layout I use a 0.5 border for a list separator
with borderBottomWidth=0.5 it works
but with borderTopWidth=0.5 it's wrong

<img width="431" alt="screen shot 2017-03-28 at 10 20 33" src="https://cloud.githubusercontent.com/assets/7056879/24395530/494b7fea-13a0-11e7-9cad-ef8eb025b0b6.png">

**Comment by SimplGy** [comment] 2017-05-22 17:16
I can repro this at 0.5 width on large devices (iPhone 6s+). Doesn't show up on iPhone 6s. Same behavior on both simulator and physical device. Setting the border to 1 makes it go away. Strangest thing ever.

**Comment by shergin** [comment] 2017-05-22 18:16
@SimplGy iPhone 6s+ is not "double density" device, it is kinda "triple density" device, so you have to use `StyleSheet.hairlineWidth` (==`0.33`) instead of `0.5`.

**Comment by SimplGy** [comment] 2017-05-22 21:45
@shergin Ok, great. Seems like hairlineWidth is canonical and that's awesome. Still think there's a bug here.

Why would specifying a "slightly too large" border (0.33 instead of 0.5) result in anything other than a slightly too large and/or blurry line?

Instead, we get this unexpected behavior where they (A) start acting proportional and (B) become partially transparent.

**Comment by shergin** [comment] 2017-05-23 01:57
@SimplGy Yeah, I see now.
(Repro on @2x devices: https://snack.expo.io/B11TIM-ZW )

**Comment by SimplGy** [comment] 2017-05-23 21:06
A few workarounds "fix" the strange border behavior:

    borderRadius: 1 // any non-fractional border radius

**Comment by nicotroia** [comment] 2017-07-25 06:37
Getting this issue as well on the iPhone 7Plus. However, I was able to refactor all the borderWidths to `StyleSheet.hairlineWidth` to fix the visual bug.

**Closed** 2017-10-09 17:26 UTC
Labels: Author Provided Repro, Icebox

**Comment by danieldelouya** [comment] 2017-12-07 13:00
I'm having this issue on some Android devices. eg. Google Pixel. 
I have the problem on a flatlist with a separator with the height: Stylesheet.hairlineWidth, then there's a flicker on the separators while scrolling.

**Comment by shergin** [comment] 2017-12-15 19:47
This particular iOS problem was fixed recently.
@danieldelouya You are probably experiencing completely another issue, could you please open another issue?
