### ISSUE TITLE
android: crash on localeCompare with empty string

### ISSUE THREAD

**Issue by simonbothen-radinn** [facebook/react-native#32174] opened 2021-09-09 09:36 UTC
## Description
`localeCompare` with empty string as input causes a native crash. Null seems to be fine.
**Using Hermes.**

## React Native version:
Run `react-native info` in your terminal and copy the results here.
System:
    OS: macOS 11.3.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 198.79 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.2.0 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 7.13.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Arctic Fox 2020.3.1 Patch 2 Arctic Fox 2020.3.1 Patch 2
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.1 => 0.65.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
1. Write  `'hello world'.localeCompare('');` anywhere

## Expected Results
return 1;

**Comment by moughxyz** [comment] 2022-01-04 18:34
Ha, same exact issue. Began in RN 0.65.1. Took hours to uncover. 

The following lines work:

```javascript
'foo'.localeCompare(undefined);
'foo'.localeCompare(null);
'foo'.localeCompare('bar');
```

But this results in a cryptic crash:

```javascript
'foo'.localeCompare('');
```

Exception:

> /com.app E/libc++abi: terminating with uncaught exception of type facebook::jni::JniException: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference

**Comment by rinoarmadiaz** [comment] 2022-01-05 13:41
hi @moughxyz @simonbothen-radinn, seems the issue is related with this
https://github.com/facebook/hermes/issues/602

i can confirm, currently using 0.66.4 and calling localeCompare gave crash on my app as well, resulting the same Exception : 

> /com.app E/libc++abi: terminating with uncaught exception of type facebook::jni::JniException: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference

**Comment by cortinico** [comment] 2022-01-05 14:13
> hi @moughxyz @simonbothen-radinn, seems the issue is related with this
> [facebook/hermes#602](https://github.com/facebook/hermes/issues/602)

Thanks for pointing this out @simonbothen-radinn.
I'm closing this as this is related to Hermes and it's already fixed in their latest version.

**Closed by cortinico** 2022-01-05 14:13 UTC
Labels: Needs: Triage :mag:
