### ISSUE TITLE
facebook.github.io redirecting to Getting Started

### ISSUE THREAD

**Issue by ignivalancy** [facebook/react-native#5977] opened 2016-02-17 12:19 UTC
When we try to open a link the website always redirecting to http://facebook.github.io/react-native/docs/getting-started.html.

----------------------------------------------------------

try to click over next button here --- >
http://facebook.github.io/react-native/docs/navigator.html#content

**Comment by mkonicek** [comment] 2016-02-17 13:28
The next button works just fine for me. Closing as cannot repro.

**Closed by mkonicek** 2016-02-17 13:28 UTC
Labels: Needs more information

**Comment by satya164** [comment] 2016-02-17 13:34
Can reproduce when I select the version as `next`. Duplicate of #5964
