### ISSUE TITLE
React-native upgrade doesn't upgrade

### ISSUE THREAD

**Issue by pistou** [facebook/react-native#23867] opened 2019-03-12 16:14 UTC
## 🐛 Bug Report
I'm trying to upgrade my projet to 0.59 as it released, but it tries to upgrade to 0.58.6, which is my current react-native version.

```
$~ > react-native info

  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
      Memory: 8.01 GB / 15.90 GB
    Binaries:
      Yarn: 1.13.0 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.1.0 - C:\Program Files\nodejs\npm.CMD

$~ > react-native --version
react-native-cli: 2.0.1
react-native: 0.58.6

$~ > react-native upgrade
You should consider using the new upgrade tool based on Git. It makes upgrades easier by resolving most conflicts automatically.
To use it:
- Go back to the old version of React Native
- Run "npm install -g react-native-git-upgrade"
- Run "react-native-git-upgrade"
See https://facebook.github.io/react-native/docs/upgrading.html
Upgrading project to react-native v0.58.6
Check out the release notes and breaking changes: https://github.com/facebook/react-native/releases/tag/v0.58.0
Successfully upgraded this project to react-native v0.58.6

$~ > react-native --version
react-native-cli: 2.0.1
react-native: 0.58.6
```

I tried to uninstall and reinstall `react-native-cli` just in case but didn't change much.

**Comment by darknblack** [comment] 2019-03-12 16:25
facing the same issue ^

**Comment by hramos** [comment] 2019-03-12 16:47
Duplicate of #23866

**Closed by hramos** 2019-03-12 16:47 UTC
Labels: Type: Bug Report, 💻CLI
