### ISSUE TITLE
Missing TypeScript types for `userSelect` style property on Text component - type error: 'userSelect' does not exist in type

### ISSUE THREAD

**Issue by jobpaardekooper** [facebook/react-native#39015] opened 2023-08-15 08:18 UTC
### Description

When setting the `userSelect` property inside the style property of a `Text` component you get a Typescript error. For example:

```tsx
<Text style={{ userSelect: 'all' }} >example</Text>
```
Gives the following type error:
```
Type '{ userSelect: string; }' is not assignable to type 'StyleProp<TextStyle>'.
      Object literal may only specify known properties, and 'userSelect' does not exist in type 'TextStyle | RecursiveArray<Falsy | TextStyle | RegisteredStyle<TextStyle>>'.
```

### React Native Version

0.72.4

### Output of `npx react-native info`

System:
  OS: macOS 13.4
  CPU: (10) arm64 Apple M1 Pro
  Memory: 442.78 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.13.0
    path: ~/.nvm/versions/node/v16.13.0/bin/node
  Yarn:
    version: 1.22.15
    path: ~/.nvm/versions/node/v16.13.0/bin/yarn
  npm:
    version: 9.8.1
    path: ~/Developer/transcribe/rn-app/node_modules/.bin/npm
  Watchman:
    version: 2023.06.12.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2021.2 AI-212.5712.43.2112.8609683
  Xcode:
    version: 14.3/14E222b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.1
    path: /usr/bin/javac
  Ruby:
    version: 3.2.2
    path: /Users/jobpaardekooper/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: ^0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

Create a `Text` component in a Typescript file as follows:

```tsx
<Text style={{ userSelect: 'all' }} >example</Text>
```

### Snack, screenshot, or link to a repository

https://github.com/jobpaardekooper/rn-userSelect-example

**Comment by cortinico** [comment] 2023-08-15 10:43
We do have a sample in React Native that tests exactly that:
https://github.com/facebook/react-native/blob/e9b565381c9e6aa989731824150fda2daa7114bc/packages/rn-tester/js/examples/Text/TextExample.android.js#L998-L1007

Can you share a reproducer as requested?

**Comment by jobpaardekooper** [comment] 2023-08-15 11:52
I have created a [repo that reproduces the issue](https://github.com/jobpaardekooper/rn-userSelect-example) but it is really nothing special. All I did was add a Text component like in my original description of the issue.

To be clear, the Text component **is** selectable and is working as it should. It just gives a type error in Typescript. For example when I have the project open in VSCode is see this:

![Screenshot 2023-08-15 at 13 51 22](https://github.com/facebook/react-native/assets/34612663/4102a779-5e07-4cef-b5f1-2677c00da8de)

**Comment by cortinico** [comment] 2023-08-15 12:52
Oh I see. That's because the TypeScript types haven't been updated.
This should be an easy fix so I marked it as "Good first issue" if someone wants to pick it up

**Comment by MjMoshiri** [comment] 2023-08-15 15:52
Hi, I would like to work on this if it's possible

**Comment by cortinico** [comment] 2023-08-15 16:06
> Hi, I would like to work on this if it's possible

I've assigned it to you 👍

**Comment by MjMoshiri** [comment] 2023-08-15 17:54
Hi again, the 1 liner change is ready :D.

**Comment by Stunner05** [comment] 2023-08-16 17:49
> Hi, I would like to work on this if it's possible

Can i assist you on this

**Comment by MjMoshiri** [comment] 2023-08-16 18:53
> > Hi, I would like to work on this if it's possible
> 
> Can i assist you on this

Hi, sure. If you think something is missing apart from the change I made in the pull request above. Please do 🙏. But I think the intended change is done. merge request already has an approval.

**Closed** 2023-09-18 06:38 UTC
Labels: Good first issue, Help Wanted :octocat:, Bug, Typescript
