### ISSUE TITLE
React Native JS server stops frequently. Remove temporary files watching.

### ISSUE THREAD

**Issue by waqas19921** [facebook/react-native#9784] opened 2016-09-07 06:21 UTC
### Issue Description

I am using Webstorm for react native apps development the react native server stops after some time due to change of files by webstorm and react native server is unable to read them. Folowing is the error which comes very oftenly.

```
{"errno":-4048,"code":"EPERM","syscall":"lstat","path":"D:\\Projects\\risemom-ignite\\RiseMom\\.idea\\workspace.xml___jb_old___"} ERROR 
 EPERM: operation not permitted, lstat 'D:\Projects\risemom-ignite\RiseMom\.idea\workspace.xml___jb_old___'

Error: EPERM: operation not permitted, lstat 'D:\Projects\risemom-ignite\RiseMom\.idea\workspace.xml___jb_old___'
See     at Error (native)
http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.
```
### Steps to Reproduce / Code Snippets

Please remove watching of files other than js or asset images. Remove watching of gradle build and temporary [.fileextension]**_jb_old_** files created by webstorm.
#### Expected Results

React native server will not watch for extra files that webstorm or android studio create temporarily and delete them.
### Additional Information
- React Native version: 0.32.0
- React Native CLI version: 1.0.0
- Platform(s): both
- Operating System: macOS, Windows

**Comment by af7** [comment] 2016-09-08 18:18
I experience exactly the same behavior and is very annoying as it delays development a lot (we need to recompile the app very often). Can this be looked at? Thanks!

**Comment by af7** [comment] 2016-09-12 13:43
@waqas19921 Did you find any workaround? For example, closing WebStorm or anything else? This is very problematic when using hotloading.

**Comment by lacker** [comment] 2016-12-15 23:35
Since this seems like a webstorm-specific problem I am not sure how to reproduce it without webstorm. I think we should close this issue but if there is something like a regex to ignore that we could add somewhere for better webstorm compatibility, that sounds like a great pull request to send in. Thanks for reporting this problem!

**Closed by lacker** 2016-12-15 23:35 UTC
