### ISSUE TITLE
ios: after updating react-native version(0.72.4), Not able to debug the app

### ISSUE THREAD

**Issue by TRIPTI-JAIN** [facebook/react-native#39101] opened 2023-08-22 08:12 UTC
### New Version

0.72.4

### Old Version

0.71.11

### Build Target(s)

9

### Output of `react-native info`

System:
  OS: macOS 12.6.6
  CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Memory: 144.41 MB / 16.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 20.3.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 9.6.7
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.06.12.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/triptijain/.rvm/gems/ruby-2.7.6/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.2
      - iOS 16.2
      - macOS 13.1
      - tvOS 16.1
      - watchOS 9.1
  Android SDK:
    API Levels:
      - "28"
      - "31"
      - "32"
      - "33"
    Build Tools:
      - 30.0.3
      - 33.0.0
      - 34.0.0
    System Images:
      - android-31 | Google APIs Intel x86_64 Atom
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10406996
  Xcode:
    version: 14.2/14C18
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.19
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/triptijain/.rvm/rubies/ruby-2.7.6/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: false

### Issue and Reproduction Steps

Update the react native version to 0.72.4

**Comment by cortinico** [comment] 2023-08-22 09:22
Potentially a duplicate of #39080
Plus you're not describing the issue you're having so we can't really help here, sorry.

**Closed by cortinico** 2023-08-22 09:22 UTC
Labels: Platform: iOS, Needs: Triage :mag:, Needs: Repro, Type: Upgrade Issue
