### ISSUE TITLE
NetInfo can't detect the wifi without Internet connection

### ISSUE THREAD

**Issue by armanbabai** [facebook/react-native#18424] opened 2018-03-17 12:00 UTC
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

I use my device to connect to a wifi that does't connect to Internet. ButNetInfo.isConnected return true, I really can not visit Internet.

## Environment

Environment:
OS: Windows 10
Node: 9.4.0
Yarn: 1.3.2
npm: 5.7.1
Watchman: Not Found
Xcode: N/A
Android Studio: Not Found

Packages: (wanted => installed)
react: 16.2.0 => 16.2.0
react-native: 0.54.0 => 0.54.0

**Comment by hramos** [comment] 2018-03-20 17:13
It looks like this may be related to #18368. We'll need to figure out if this is working as expected (i.e. it's true that the device is connected to WiFi, after all).

Duplicate of #18368

**Closed by hramos** 2018-03-20 17:13 UTC
Labels: :clipboard:Needs Repro Steps, :globe_with_meridians:Networking, :grey_question:Needs More Information
