### ISSUE TITLE
TransformError: AwesomeProject/index.ios.js: Cannot read property 'error' of null

### ISSUE THREAD

**Issue by abbood** [facebook/react-native#5221] opened 2016-01-09 11:11 UTC
I initially got the same error as the one reported in [this](https://github.com/facebook/react-native/issues/1875) issue..  and following these steps:

```
brew update
brew uninstall watchman
brew unlink watchman
brew install watchman --HEAD
```

seemed to have fixed _that_ error (that error appeared on the terminal window that auto-opens when running from xcode)..

but now the terminal window stops here:

```
React packager ready.

~/Library/LaunchAgents/com.github.facebook.watchman.plist: service already loaded

~/Library/LaunchAgents/com.github.facebook.watchman.plist: service already loaded

[1:05:35 PM] <END>   Crawling File System (1942ms)
[1:05:35 PM] <START> Building in-memory fs for JavaScript
[1:05:37 PM] <END>   Building in-memory fs for JavaScript (2426ms)
[1:05:37 PM] <START> Building in-memory fs for Assets
[1:05:39 PM] <END>   Building in-memory fs for Assets (1848ms)
[1:05:39 PM] <START> Building Haste Map
[1:05:41 PM] <START> Building (deprecated) Asset Map
[1:05:41 PM] <END>   Building (deprecated) Asset Map (667ms)
[1:05:41 PM] <END>   Building Haste Map (2439ms)
[1:05:41 PM] <END>   Building Dependency Graph (8660ms)
```

**and i get this error on the error console of xcode:**

```
uncaught error Error: TypeError: Cannot read property 'error' of null
    at index.js:117:20
    at tryCallOne (/Users/abdullahbakhach/dev/js/AwesomeProject/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/abdullahbakhach/dev/js/AwesomeProject/node_modules/react-native/node_modules/promise/lib/core.js:123:15
    at flush (/Users/abdullahbakhach/dev/js/AwesomeProject/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at nextTickCallbackWith0Args (node.js:456:9)
TransformError: /Users/abdullahbakhach/dev/js/AwesomeProject/index.ios.js: Cannot read property 'error' of null
See logs /var/folders/jm/wfcxbcj167zf14c2kjmwsqtw0000gn/T/react-packager.log
    at SocketClient._handleMessage (SocketClient.js:139:23)
    at BunserBuf.<anonymous> (SocketClient.js:53:42)
    at emitOne (events.js:77:13)
    at BunserBuf.emit (events.js:169:7)
    at BunserBuf.process (/Users/abdullahbakhach/dev/js/AwesomeProject/node_modules/react-native/node_modules/bser/index.js:289:10)
    at /Users/abdullahbakhach/dev/js/AwesomeProject/node_modules/react-native/node_modules/bser/index.js:244:12
    at nextTickCallbackWith0Args (node.js:456:9)
    at process._tickCallback (node.js:385:13)
Command /bin/sh failed with exit code 1
```

**Comment by corbt** [comment] 2016-01-09 18:11
#5191 is tracking that actual error message (which is related to underlying babel messages not being passed through), but you still shouldn't be getting an error on a fresh project.

**Comment by israelidanny** [comment] 2016-01-10 05:20
I'm getting the exact same error by updating react 0.17 to 0.18.0-rc

**Comment by tdzl2003** [comment] 2016-01-10 09:04
Maybe it's caused by `.babelrc` from module `react-deep-force-update` which is incompatible with babel 6.x

**Comment by zsuswy** [comment] 2016-01-15 16:15
yeah. I have exactly the same issue on a fresh project. Looking for a solution.

bundle: Created ReactPackager
uncaught error Error: TypeError: Cannot read property 'error' of null
    at index.js:117:20
    at tryCallOne (/Users/sunwuyang/百度云同步盘/MAC/2.代码/r_n_test01/node_modules/promise/lib/core.js:37:12)
    at /Users/sunwuyang/百度云同步盘/MAC/2.代码/r_n_test01/node_modules/promise/lib/core.js:123:15
    at flush (/Users/sunwuyang/百度云同步盘/MAC/2.代码/r_n_test01/node_modules/asap/raw.js:50:29)
    at nextTickCallbackWith0Args (node.js:433:9)
TransformError: /Users/sunwuyang/百度云同步盘/MAC/2.代码/r_n_test01/node_modules/react-deep-force-update/lib/index.js: Cannot read property 'error' of null
See logs /var/folders/67/phf6vz9566v6wq57tbyjtqpw0000gn/T/react-packager.log
    at SocketClient._handleMessage (SocketClient.js:139:23)
    at BunserBuf.<anonymous> (SocketClient.js:53:42)
    at emitOne (events.js:77:13)
    at BunserBuf.emit (events.js:169:7)
    at BunserBuf.process (/Users/sunwuyang/百度云同步盘/MAC/2.代码/r_n_test01/node_modules/bser/index.js:289:10)
    at /Users/sunwuyang/百度云同步盘/MAC/2.代码/r_n_test01/node_modules/bser/index.js:244:12
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickCallback (node.js:362:13)
Command /bin/sh failed with exit code 1

**Comment by corbt** [comment] 2016-01-15 16:50
Hey everybody, this error message is a known issue in 0.18-rc that will be fixed in the 0.18 release. The problem is that underlying babel errors aren't getting displayed to the user. If this is affecting you, the best solution at the moment is to use 0.17 until 0.18 lands in a few days. Let's keep tracking this issue in #5191.

**Closed by corbt** 2016-01-15 16:50 UTC

**Comment by zsuswy** [comment] 2016-01-17 12:44
@corbt Thanks!

**Comment by yxw2014** [comment] 2016-01-19 03:54
I have the same problem!
