### ISSUE TITLE
Start Remote JS Debugging, Chrome Debugger Control no-response,seconds later, Control auto Close.

### ISSUE THREAD

**Issue by cyzaoj** [facebook/react-native#11108] opened 2016-11-24 06:20 UTC
Description:

1.  Start Remote JS Debugging
2.  print app load log, but Chrome Control lose response ,and then "Clear Button" Can't be clicked.
3.  seconds later, Control auto Close.

**Comment by mkonicek** [comment] 2016-11-24 21:09
Hey, thanks for reporting this issue!

Can you provide more info? By "print app log" do you mean `react-native log-ios`?

I don't understand "Control auto Close" unfortunately, can you explain please?

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but we can reopen if additional information is provided. Thanks!

**Closed by mkonicek** 2016-11-24 21:09 UTC
