### ISSUE TITLE
[Android] [adjustResize] Keyboard pushes absolute-positioned dynamic-height component off screen

### ISSUE THREAD

**Issue by jayesbe** [facebook/react-native#6785] opened 2016-04-03 12:17 UTC
I created a ticket related to the ExNavigator here https://github.com/exponentjs/ex-navigator/issues/105

However I believe this is a core issue.  

Currently I am using RN 0.22.2 (on Android)

Basically this is my View

```
<View style={{flex: 1}}>
      <View style={[position: 'absolute', top: 0, left: 0, right: 0, height: 50]}>

      </View>
      <View style={[position: 'absolute', bottom: 0, left: 0, right: 0, height: 50]}>
          <TextInput />
     </View>
<View>
```

This is basically a chat window with an input field positioned at the bottom of the screen and a header positioned at the top of the screen.

When I first open / run the app, Upon focus of the TextInput, the keyboard appears and the View component positioned at the top is pushed off the page. 

I spent a day yesterday figuring out why but in the end I used keyboardDidShow and keyboardDidHide to offset the position of the element so it kind of works.

However today I noticed something different.  By chance I minimized the App.  I didn't close it.  I opened it back up and now the View component that should be positioned at the top was now in the middle. (My offset was calculated to ~270) 

So I once again removed the offset handling changes and positioned it statically at the top with top: 0. 
I then ran the app again by closing and reopening, as expected the View component was once again pushed off the screen when the keyboard appeared.

I minimized the app, then brought it back up. This time when the keyboard appeared, the View component stayed at the top! This is what I am expecting when you open the app the first time, however it only works after minimizing it first.  

Definitely seems like a bug to me.

**Comment by MrOpposite** [comment] 2016-05-01 09:19
I just ran into the same problem. My entire view gets pushed off top when the keyboard pops up. making coding really hard since any keyboard-showing-code I may throw at the application suddenly gets interrupted by the entire view being pushed.

**Comment by dwaligora** [comment] 2016-05-16 16:53
I have experienced the same issue unfortunately.

**Comment by Sylor73** [comment] 2016-08-25 16:41
This problem is a small , but annoying. Fix this , please.

**Comment by Sylor73** [comment] 2016-09-19 12:25
Bump

**Comment by BigPun86** [comment] 2016-10-11 12:22
+1

**Comment by marcshilling** [comment] 2016-10-31 15:23
I'm experiencing this too. Android only, and only when the selected text input WOULD BE obscured by the keyboard. If I select an input that would remain visible after the keyboard appearance, this does not occur.

**Comment by jveldboom** [comment] 2016-11-01 13:52
As a quick fix for this, setting the height on the parent `View` with `onLayout` seems to fix the issue.

```javascript
<View onLayout={(event) => {
     var {height} = event.nativeEvent.layout;
     this.setState({height})
  }}
  style={{flex: 1, height: this.state.height}}>
  <View style={[position: 'absolute', top: 0, left: 0, right: 0, height: 50]}>

  </View>
  <View style={[position: 'absolute', bottom: 0, left: 0, right: 0, height: 50]}>
    <TextInput />
  </View>
<View>
```

**Comment by marcshilling** [comment] 2016-11-29 15:48
Setting `android:windowSoftInputMode="adjustNothing"` on the MainActivity in `AndroidManifest.xml` to completely disable the automatic keyboard resizing was my workaround. I then do all the keyboard resizing/scrolling logic myself.

**Comment by ericvicenti** [comment] 2017-03-06 07:56
I think `android:windowSoftInputMode="adjustResize"` is the best option here

**Comment by nihgwu** [comment] 2017-03-06 08:43
but `android:windowSoftInputMode="adjustResize"` still doesn't resolve this issue @ericvicenti

**Comment by krailler** [comment] 2017-03-06 14:51
Same issue..

**Comment by AtixD** [comment] 2017-03-12 17:02
+

**Comment by bpt2410** [comment] 2017-03-21 04:04
I also have the same issue

**Comment by lolobosse** [comment] 2017-05-02 12:12
+1

**Comment by luco** [comment] 2017-05-05 20:02
+1 on this.

Using `android:windowSoftInputMode="adjustNothing"` breaks some classes, as chat which floats when keyboard slide in.

**Comment by irsyadmhdilham** [comment] 2017-05-14 15:40
same issue

**Comment by a407121393** [comment] 2017-06-02 05:41
same issue+1

**Comment by davebro** [comment] 2017-06-10 17:50
+1

**Comment by danstepanov** [comment] 2017-06-18 03:56
+1

**Comment by chudnyi** [comment] 2017-07-13 12:51
+1

**Comment by nikoootine** [comment] 2017-07-14 20:49
+1

**Comment by neetocode** [comment] 2017-07-16 10:36
+1

**Comment by atakanyenel** [comment] 2017-07-31 21:40
`android:windowSoftInputMode="adjustNothing"` fixed it for me too in Android.

**Comment by ivanzotov** [comment] 2017-08-09 15:24
android:windowSoftInputMode="adjustPan" works for me

**Comment by rochapablo** [comment] 2017-09-04 12:31
```
android:windowSoftInputMode="adjustPan|adjustResize"
```

[more](https://stackoverflow.com/questions/17410499/difference-between-adjustresize-and-adjustpan-in-android)

**Comment by IljaDaderko** [comment] 2017-11-13 16:28
`android:windowSoftInputMode="adjustNothing"` does the trick

**Comment by sabbyt54** [comment] 2017-11-28 03:13
+1

**Comment by daxaxelrod** [comment] 2017-12-29 04:59
+1 Have the same issue. have a standard container with flex:1 and 2 components, flex:.8 and flex:.2

When the textinput is selected and the keyboard comes up, its as if the entire flex is squished

**Comment by gongteng0215** [comment] 2018-01-19 05:50
@marcshilling Thank you,That helped me!

**Comment by Asleepace** [comment] 2018-01-23 01:00
Setting the height of the view to the screen's height worked for me!

**Comment by RavinderRikhi** [comment] 2018-01-24 21:06
Set the Parent container height to Device height fixed it for me . I think the view shrinks only if it is designed using flex boxes .

**Comment by dccarmo** [comment] 2018-02-19 15:02
@ericvicenti Honestly this issue should be reopened, there isn't a clear solution.

Ideally `android:windowSoftInputMode="adjustNothing"` would be applied and then `KeyboardAvoidingView` would work as intended, which is not the case.

**Comment by kaueDM** [comment] 2018-02-27 17:18
Bump

I have lots of absolute positioned components. My entire app breaks when the keyboard pops up.

**Comment by Ashoat** [comment] 2018-03-14 18:00
I'm gonna reopen this issue since the solution provided when it was closed doesn't actually fix the problem.

**Comment by ankitkante** [comment] 2018-04-03 17:40
Hi, for ejected apps `android:windowSoftInputMode="adjustNothing"` may work, but, we need a solution that works for non-ejected apps too.

**Comment by ChristianTucker** [comment] 2018-04-14 16:38
@ankitkante  Your issue of "Ejecting" has nothing to do with react-native and has everything to do with expo. You should ask for a solution over there. :)

**Comment by ospfranco** [comment] 2018-06-21 13:28
Another possible workaround as mentioned by @Asleepace is using a fixed height.

Worked for me, not ideal, but better than nothing.

**Comment by maxfadeev** [comment] 2018-07-13 21:30
None of solutions helps me(except android:windowSoftInputMode="adjustNothing", but I don't think it's a proper solution)

**Comment by maxfadeev** [comment] 2018-07-17 18:06
Surprised, my problem was in the hidden StatusBar, I didn't run into such issue before. So check if you have the hidden StatusBar in you code :smiley:. Anyway it's a weird behaviour. Still wondering if there is a workaround.

**Comment by jh2oman** [comment] 2018-07-19 23:04
+1

**Comment by charpeni** [comment] 2018-07-19 23:33
Please use reaction instead of "+1" comment, adding noise won't help the issue.

**Comment by galkahana** [comment] 2018-08-16 07:15
I found the solution of @jveldboom to be the only one that actually works. mind you it should be minHeight and not height...otherwise flex will win.

**Comment by lyminhtanh** [comment] 2018-08-23 13:14
Adding this line of code in the manifest file for the activity you want to apply. 
I confirm that it works in my case. My activity layout is a Constraint layout
` <activity
            android:name=".activity.MyProfileActivity"
            android:screenOrientation="portrait"
            **android:windowSoftInputMode="adjustNothing"**/>`

**Comment by iamshadmirza** [comment] 2019-01-31 11:08
Using `android:windowSoftInputMode="adjustPan"` in `AndroidManifest.xm`l is fixes the issue but then `KeyboardAvoidingView` is not working properly, some part of View is always getting hidden behind the keyboard. I tried with both positive and negative offset in `keyboardVerticalOffset`. 
I have been scratching my head for so long and tried everything, there is no clear solution.

**Comment by MurugappanV** [comment] 2019-02-06 08:41
Setting full device height to absolute layout works fine for me

**Comment by mahendramahi** [comment] 2019-02-06 08:54
@iamshadmirza  use this library if you want to control you view when open keyboard in android and ios both  
`react-native-keyboard-aware-scrollview `

**Comment by bartolkaruza** [comment] 2019-03-19 14:30
This issue looks very similar (if not identical) to https://github.com/facebook/react-native/issues/13000, which is closed as 'un-actionable' because the root cause is an underlying Android [system issue](https://issuetracker.google.com/issues/36911528).

There appear to be several workarounds in the issue comments above, which allow you to solve this case. The separate issue about the KeyboardAvoidingView not working with 'adjustPan' should be posted as a standalone issue, if that is still the case.

The reproduction posted by the OP (after fixing the syntax) does not reproduce the issue on recent Android emulator (Android 9).

I'm closing this for now, if you disagree, please help us out with an easy to setup (in a repository) reproduction.

**Closed by bartolkaruza** 2019-03-19 14:30 UTC
Labels: Platform: Android, Ran Commands, Type: Bug Report

**Comment by lilosir** [comment] 2019-05-31 16:43
`android:windowSoftInputMode="adjustPan"` is working, but at the same time, the header will be pushed up as well.

**Comment by stefanfrancis93** [comment] 2019-08-19 13:50
> `android:windowSoftInputMode="adjustPan"` works for me

This worked for me. Thanks 💯

**Comment by mahdidarzi** [comment] 2019-10-24 20:13
Setting android:windowSoftInputMode="adjustNothing" on the MainActivity in AndroidManifest.xml to completely disable the automatic keyboard resizing was my workaround. I then do all the keyboard resizing/scrolling logic myself. after this pls run your project again

**Comment by AmitPandya007** [comment] 2019-11-05 08:06
I have used this below library but scrollview gets stuck when the keyboard appears.
https://github.com/APSL/react-native-keyboard-aware-scroll-view

and my project is an undetached Expo project.
Please help me with some solutions related to this. Thanks in Advance.

**Comment by mahdidarzi** [comment] 2019-11-05 13:40
hi, dude, I don't use this library

**Comment by e3bmo3ty** [comment] 2019-12-03 17:53
still same issue on iOS, when keyboard shows up it resize the main container and pushes the view up :(...... thats so frustrated

**Comment by Elmarino** [comment] 2019-12-09 10:38
I faced this issue on android on RN 0.60 and the solution gave by @rochapablo fixed it.

https://github.com/facebook/react-native/issues/6785#issuecomment-326951566

**Comment by Hristijan95** [comment] 2019-12-27 12:54
On Android it's impossible to cover all scenarios. Either there is a problem with empty spacing above the keyboard, if I fix this by "adjustNothing" in android manifest, the KeyboardAvoidingView is completely dead.
