### ISSUE TITLE
'dev' of null at getBoolOptionFromQuery

### ISSUE THREAD

**Issue by Kureev** [facebook/react-native#254] opened 2015-03-26 21:11 UTC
Hi all,
I followed by [quick start guide](http://facebook.github.io/react-native/docs/getting-started.html#quick-start) and faced following error "Cannot read property 'dev' of null at getBoolOptionFromQuery".

[Screenshot attached](http://goo.gl/6xVNWh)

**Comment by amasad** [comment] 2015-03-26 21:12
duplicate of #218 
Fix coming

**Closed by amasad** 2015-03-26 21:12 UTC
