### ISSUE TITLE
[Android] Support for Image onError

### ISSUE THREAD

**Issue by MichaelDanielTom** [facebook/react-native#7440] opened 2016-05-07 22:11 UTC
Hey Guys,

Will there be support for an onError callback on Image for Android? I want to set an error image if the image fails to load, without resorting to hacking around onLoad and onLoadEnd. If I'm overlooking an obvious easy way to do this please let me know :)

**Comment by brentvatne** [comment] 2016-05-11 04:59
https://github.com/facebook/react-native/commit/68b2f49a314ae07681353d89b89f2a7f28cef10d adds support for this to an extent, but it's not perfect -- it doesn't handle some cases like 404s which Fresco (the underlying image library) doesn't handle yet afaik, cc @tyronen

**Comment by ide** [comment] 2016-05-11 17:10
The Java implementation of Image.prefetch calls the rejection callback on error so Fresco might expose errors now, worth revisiting.

**Comment by ajoshdee** [comment] 2016-07-22 04:22
Same with ios, i want to set default image onError, dunno how.

**Comment by ajwhite** [comment] 2016-07-26 13:52
@ajoshdee, you'd need to make a component that handles the error, sets a state indicating there's an error, and then using that default image when an error exists

**Comment by webzepter** [comment] 2016-08-15 16:08
@brentvatne This 68b2f49 commit dispatches event, but JS component does not receive it (but `onLoadEnd` works great). Why it happens?

**Comment by lacker** [comment] 2016-11-29 22:15
We closed the referenced pull request as "working as intended" so I think we should close this issue as well.

**Closed by lacker** 2016-11-29 22:15 UTC
Labels: Android

**Comment by ajwhite** [comment] 2016-11-29 23:22
@lacker it sounds like the conclusion there is that `onError` will not currently work on Android. Would prefer to keep an issue open for visibility, discussions, and future outlook

**Comment by lacker** [comment] 2016-11-30 00:05
Our goal right now is to focus the github issues for bug reports - it had been months on this anyway with no activity. If someone has a proposal for how to fix this then I think it would be worth opening another issue to debate it.

**Comment by ajwhite** [comment] 2016-11-30 00:36
Sounds good @lacker - thanks for explaining.

Dropping this here for anyone that comes seeking this issue, this is a solution we threw together to achieve the platform consistency:

https://github.com/robinpowered/react-native-android-image-polyfill
https://www.npmjs.com/package/react-native-android-image-polyfill
