### ISSUE TITLE
Cannot run a new project using run-android (unable to resolve module ./index) 

### ISSUE THREAD

**Issue by wendy-peiwen** [facebook/react-native#24147] opened 2019-03-26 08:34 UTC
after i react-native init newProject, and react-native run-android, it pop up an error page saying unable to resolve module ./index. Anyone of you can solve this problem?

React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
      Memory: 1.30 GB / 7.82 GB
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5264788

**Comment by hasannizamani** [comment] 2019-03-26 08:42
This is a duplicate of #24112 which has a workaround.

**Comment by wendy-peiwen** [comment] 2019-03-26 08:46
> This is a duplicate of #24112 which has a workaround.

but the discussion is already closed. and the issue is not fix for android version

**Comment by hasannizamani** [comment] 2019-03-26 08:47
The workaround that worked for me at least is to run `react-native start --reset-cache` in one terminal and then `run react-native run-android` in another terminal https://github.com/facebook/react-native/issues/24112#issuecomment-476514784

**Comment by hasannizamani** [comment] 2019-03-26 08:48
> > This is a duplicate of #24112 which has a workaround.
> 
> but the discussion is already closed. and the issue is not fix for android version

The workaround that worked for me at least is to run react-native start --reset-cache in one terminal and then run react-native run-android in another terminal #24112 (comment)

**Comment by kelset** [comment] 2019-03-26 11:02
Thanks @hasannizamani for helping out with this :)

@wendy-peiwen as pointed out, it's a matter of making sure that the bundler is running correctly.

**Closed by kelset** 2019-03-26 11:02 UTC
Labels: Platform: Android, Type: Bug Report, 📦Bundler
