### ISSUE TITLE
Setting borderStyle on <View> to dashed or dotted for a single side does not render correctly on both iOS and Android

### ISSUE THREAD

**Issue by Eyesonly88** [facebook/react-native#24224] opened 2019-03-31 23:35 UTC
## 🐛 Bug Report

Setting the CSS property `borderStyle` to `dashed` or `dotted` for a single side on a `View` component does not work on both iOS and Android.

The docs show available values: https://facebook.github.io/react-native/docs/view-style-props#borderstyle

### Android renders solid line for both dashed/dotted

![Screen Shot 2019-04-01 at 12 20 02 PM](https://user-images.githubusercontent.com/767013/55296739-4b71c000-547a-11e9-856b-d4e2806cf52a.png)

### iOS does not render anything for dashed/dotted

![Screen Shot 2019-04-01 at 12 18 50 PM](https://user-images.githubusercontent.com/767013/55296746-617f8080-547a-11e9-8c82-9158c6c55494.png)

## To Reproduce

Set a `borderStyle` css property on a `View` for a single side like this:

```
borderLeftWidth: 3,
borderLeftColor: 'red',
borderStyle: 'dashed',
``` 

## Expected Behavior

A dashed border is rendered correctly on iOS and Android

## Code Example

Snack: https://snack.expo.io/@mido/react-native-borderstyle-dashed-and-dotted-broken

## Environment

```
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
      Memory: 977.25 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
      Yarn: 1.6.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 21, 22, 23, 24, 25, 26, 27
        Build Tools: 26.0.3, 27.0.3, 28.0.2, 28.0.3
        System Images: android-24 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.2 => 0.59.2
    npmGlobalPackages:
      react-native-log-ios: 1.0.1
```

**Comment by Eyesonly88** [comment] 2019-03-31 23:47
Tested on `0.59.2` as well and its still broken.

**Comment by retyui** [comment] 2019-04-01 07:09
https://github.com/facebook/react-native/issues/23537

**Comment by Eyesonly88** [comment] 2019-04-01 20:47
@retyui thanks for the link. This bug is specifically talking about `<View>` borderStyle prop which should be supported according to the docs.

**Comment by michalchudziak** [comment] 2019-04-25 15:07
I was able to reproduce the issue with the latest release (`0.59.5`)

**Comment by Eyesonly88** [comment] 2019-08-05 08:43
Heya, this is still an issue with latest `0.60.4`.

**Comment by craig8two** [comment] 2019-08-06 10:35
Still an issue. +1

**Comment by WizardPro** [comment] 2019-08-18 06:45
Still an issue. +2 with 0.60.4

**Comment by KingAmo** [comment] 2019-08-23 12:07
still have the same issue with `rn 0.60.5`

**Comment by diazdell91** [comment] 2019-09-14 12:10
still have the issue

**Comment by darsodango** [comment] 2019-10-10 07:40
Wow. this issue still exist. How about that. Any fix for this? Thanks!

**Comment by youngjuning** [comment] 2019-10-25 10:10
still have the issue

**Comment by ihwf** [comment] 2019-11-06 03:11
**react-native: "0.61.3"
still have the issue**

**Comment by sirajalam049** [comment] 2019-11-12 13:42
Same problem, 
for now, this hack work for me

`style={{ borderWidth: 1, borderStyle: 'dotted', borderColor: '#fff', borderBottomColor: theme.colors.teal2 }}`

**Comment by rhythmpatel** [comment] 2019-12-26 10:11
This works for me for vertical dashed line. But gives double width.
"react-native": "0.59.10",

`width: 0,
    height: 45,
    borderStyle: 'dashed',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius : 1,`

**Comment by pixelize** [comment] 2020-01-07 15:18
same issue, the border is not rendered at all (react-native": "^0.60.5")

```
const styles = StyleSheet.create({
  item: {
    borderBottomColor: colors.light,
    borderBottomWidth: 1,
    borderStyle: "dashed"
  }
});

export const ProfileHealth = () => (
    <View style={styles.item}>
      <Text>Text</Text>
    </View>
);
```

**Comment by anton-sharpdev** [comment] 2020-01-13 06:09
Same thing, I am trying to use border to show breadcumbs-like line on left side of view without using another view for this:
```
container: {
    marginLeft: 24,
    paddingLeft: 8,
    borderLeftWidth: 1,
    borderStyle: 'dashed',
    borderLeftColor: 'black',
  }
```
This style isn't applying to view. Tried to vanish other borders - line become solid
```
container: {
    marginLeft: 24,
    paddingLeft: 8,
    borderWidth: 1,
    borderRadius: 1,
    borderStyle: 'dashed',
    borderLeftColor: 'black',
  }
```

Doesn't work on Android, iOS still not supports 'dashed' or 'dotted' style

**Comment by kgirma** [comment] 2020-03-16 17:43
Same issue. Are we resolving this anytime soon?

**Comment by dimaip** [comment] 2020-03-28 09:16
Here's how I got it to work (RN version 59.10)
```js
          <View style={{ overflow: 'hidden' }}>
            <View
              style={{
                borderWidth: 1,
                borderStyle: 'dashed',
                borderColor: '#000000',
                marginTop: -1,
                marginLeft: -1,
                marginRight: -1,
              }}
            >
              Content
            </View>
          </View>
```

**Comment by kennethbrent** [comment] 2020-03-30 23:03
Same issue

**Comment by agnjkafgh** [comment] 2020-03-31 08:59
Can confirm that `borderStyle: dashed` works only when you add `borderRadius` to the style.
I am using **react-native v0.61.2**

**Comment by johhansantana** [comment] 2020-04-08 00:04
> This works for me for vertical dashed line. Both Android and iOS. But gives double width.
> **"react-native": "0.59.10",**
> 
> ```
> style={{
>     width: 0,
>     height: 45,
>     borderStyle: 'dashed',
>     borderWidth: 1,
>     borderColor: '#ddd',
>     borderRadius : 1,
> }}
> ```
> 
> ## Update: (31-Mar-2020)
> I finally ended up using `react-native-dash` - https://github.com/obipawan/react-native-dash for consistent results in both iOS and android

I think this is the easiest consistent workaround. Thanks for the library.

**Comment by euthribeiro** [comment] 2020-04-13 16:13
For some reason, it only works when used in conjunction with borderRadius. With borderRadius: 1, rounding the border is almost imperceptible.

**Comment by ihwf** [comment] 2020-05-28 06:30
Heya, this is still an issue with latest `0.62.2`. unbelievable!! this issue has appear for a long time and have not resolve it

**Comment by fabriziobertoglio1987** [comment] 2020-05-28 12:17
not a priority

```javascript
import * as React from 'react';
import { Text, View, StyleSheet } from 'react-native';

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container} />
    );
  }
}

const styles = StyleSheet.create({
  container: {
    marginTop: 100,
    marginLeft: 100,
    height: 100,
    width: 200,
    backgroundColor: 'yellow',
    borderWidth: 2,
    borderStyle: 'dotted',
    borderRadius: 0.0000001,
  },
});
```
<img src="https://user-images.githubusercontent.com/24992535/83140157-e4877f80-a0ed-11ea-96a0-b9824a5c9825.png" width="250" />

**Comment by ihwf** [comment] 2020-05-29 01:57
> not a priority
> 
> ```js
> import * as React from 'react';
> import { Text, View, StyleSheet } from 'react-native';
> 
> export default class App extends React.Component {
>   render() {
>     return (
>       <View style={styles.container} />
>     );
>   }
> }
> 
> const styles = StyleSheet.create({
>   container: {
>     marginTop: 100,
>     marginLeft: 100,
>     height: 100,
>     width: 200,
>     backgroundColor: 'yellow',
>     borderWidth: 2,
>     borderStyle: 'dotted',
>     borderRadius: 0.0000001,
>   },
> });
> ```
> 
> <img alt="" width="250" src="https://user-images.githubusercontent.com/24992535/83140157-e4877f80-a0ed-11ea-96a0-b9824a5c9825.png">
not four side, just add a single side(left/right/top/bottom), it will render to solid line, no matter change a side borderColor or borderWidth, the dashed or dotted will render to solid line

**Comment by fabriziobertoglio1987** [comment] 2020-06-02 09:36
You are right 

```javascript
import * as React from 'react';
import { Text, View, StyleSheet } from 'react-native';

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container} />
    );
  }
}

const styles = StyleSheet.create({
  container: {
    marginTop: 100,
    marginLeft: 100,
    height: 100,
    width: 200,
    backgroundColor: 'yellow',
    borderLeftWidth: 2,
    borderStyle: 'dotted',
    borderTopLeftRadius: 1,
    borderTopEndRadius: 1,
    borderTopRightRadius: 1,
    borderTopRightRadius: 1,
    borderBottomRightRadius: 1,
    borderBottomEndRadius: 1,
    borderBottomLeftRadius: 1,
  },
});
```
<img src="https://user-images.githubusercontent.com/24992535/83504796-37ce4900-a4c5-11ea-91fe-860d86fdd4ff.png" width="250" />

**Comment by fabriziobertoglio1987** [comment] 2020-06-08 17:30
This is not one bug, but several issues from ReactViewBackgroundDrawable. I am not going to fix this. Thanks

**Comment by fabriziobertoglio1987** [comment] 2020-06-08 19:03
This are multiple issues that should be solved with multiple pull requests

`ReactViewBackgroundDrawable` handles different scenarios with a series of if statements:

- rounded borders
- non rounded borders
- settings one border at the time (`borderLeftWidth` and `borderLeftRadius`)

```
  @Override
  public void draw(Canvas canvas) {
    updatePathEffect();
    if (!hasRoundedBorders()) {
      drawRectangularBackgroundWithBorders(canvas);
    } else {
      drawRoundedBackgroundWithBorders(canvas);
    }
  }
```
This does not work with dotted style both on:

1) With rectangular shape (no rounded borders) with `drawRectangularBackgroundWithBorders`
2) When setting only one side of the rectangular (with rounded borders) for ex. with `borderLeftWidth: 2` (method `drawRoundedBackgroundWithBorders`).


Issue 2) is connected to the drawing done with `drawQuadrilateral`. 
There must be a reason we are using `lineTo` instead of `drawRect`, but I ignore it. 

The fact is seems that the logic to include special border style was not implemented here and I was able to add it. The style dotted or solid depend on the variable `mPaint`.

https://github.com/facebook/react-native/blob/7e300db7035c98537e0719c88a7c1a451e59e250/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewBackgroundDrawable.java#L1208-L1215

Seems to me that the logic for drawing rounded corners rectangles is included in [updatePath](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewBackgroundDrawable.java#L480)

https://github.com/facebook/react-native/blob/7e300db7035c98537e0719c88a7c1a451e59e250/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewBackgroundDrawable.java#L615-L691

and then applied by clipping the canvas (cropping the rectangle so it looks like has rounded borders)

https://github.com/facebook/react-native/blob/7e300db7035c98537e0719c88a7c1a451e59e250/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewBackgroundDrawable.java#L375-L376

This is important in case you are using rounded corners rectangle and setting each border side width and style.... This issue is real headache..

**Comment by fabriziobertoglio1987** [comment] 2020-06-09 07:27
```ruby
class Side < Path
  def init(x, y, z, w)
    moveTo(x,y)
    side.lineTo(z,w)
  end
end

class Border
  def init(leftBorder, topBorder, rightBorder, bottomBorder)
     # intersect 4 Paths for borders
     # intersect also the other 4 Paths for corners 
  end  
end

class Corner
  # def init()
  #    arcTo()  
  # end
end

leftBorder = new Side(10,10, 10, 50)
corner = new Corner()
border = new Border(leftBorder, topBorder, rightBorder, bottomBorder)
canvas.drawPath(border, mPaint)
```
This fixes the issue:

```java
          if (borderLeft > 0) {
            int leftInset = left + borderLeft;
            mPaint.setStyle(Paint.Style.STROKE);
            DashPathEffect dash = new DashPathEffect(
              new float[] {9, 9}, 0);
            mPaint.setPathEffect(dash);
            mPaint.setStrokeWidth(10);
            Path side = new Path();
            side.moveTo(left, top);
            side.lineTo(leftInset, bottom - borderBottom);
            canvas.drawPath(side, mPaint);
            // canvas.drawRect(left, top, leftInset, bottom - borderBottom, mPaint);
          }
```
https://github.com/facebook/react-native/blob/7e300db7035c98537e0719c88a7c1a451e59e250/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewBackgroundDrawable.java#L1102-L1105

<img src="https://user-images.githubusercontent.com/24992535/84116749-b3ce1100-aa30-11ea-9840-60645d569482.png" width="250" />

I'll write a pull request with a quick fix.

**Comment by Gazizbek** [comment] 2020-06-13 21:11
You can set like below for only bottom border:
borderWidth: 1,
borderLeftWidth: 0,
borderRightWidth: 0,
borderTopWidth: 0,
borderStyle: 'dashed'

**Comment by amiratak88** [comment] 2020-06-22 13:34
This is still an issue

**Comment by DenisDovganiuc** [comment] 2020-06-23 11:35
Same issue

**Comment by fabriziobertoglio1987** [comment] 2020-07-06 08:04
@Gazizbek  @amiratak88 @DenisDovganiuc there is a pr https://github.com/facebook/react-native/pull/29099 that fixes this. Please test that PR and support. Thanks. Fabrizio

**Comment by fabriziobertoglio1987** [comment] 2020-07-09 07:25
I wrote pull request https://github.com/facebook/react-native/pull/29099 that fixes this issue

After a quick reserach I noticed that we have 25 issues in react-native for this bug https://github.com/facebook/react-native/issues/24224 https://github.com/facebook/react-native/issues/28695 https://github.com/facebook/react-native/issues/23651 https://github.com/facebook/react-native/issues/23475 https://github.com/facebook/react-native/issues/22256 https://github.com/facebook/react-native/issues/22226 https://github.com/facebook/react-native/issues/19234 https://github.com/facebook/react-native/issues/18285 https://github.com/facebook/react-native/issues/17344 https://github.com/facebook/react-native/issues/17343 https://github.com/facebook/react-native/issues/17251 https://github.com/facebook/react-native/issues/12817 https://github.com/facebook/react-native/issues/12403 https://github.com/facebook/react-native/issues/11042 https://github.com/facebook/react-native/issues/9343 https://github.com/facebook/react-native/issues/8236 https://github.com/facebook/react-native/issues/8105 https://github.com/facebook/react-native/issues/7838 https://github.com/facebook/react-native/issues/6721 https://github.com/facebook/react-native/issues/5411 https://github.com/facebook/react-native/issues/3159 https://github.com/facebook/react-native/issues/2335 https://github.com/facebook/react-native/issues/840 https://github.com/facebook/react-native/issues/27133 https://github.com/facebook/react-native/issues/28695

I decided to post this message and trigger linking between all this issues.

**Comment by joshuapinter** [comment] 2020-07-30 16:21
Nice job @fabriziobertoglio1987! Hopefully this gets merged in for the next release.

For the record: 

> @Gazizbek 
> You can set like below for only bottom border:
> borderWidth: 1,
> borderLeftWidth: 0,
> borderRightWidth: 0,
> borderTopWidth: 0,
> borderStyle: 'dashed'

This doesn't work. Changes the remaining border styles to a solid line.


> @sirajalam049
> Same problem,
> for now, this hack work for me
> 
> `style={{ borderWidth: 1, borderStyle: 'dotted', borderColor: '#fff', borderBottomColor: 'red' }}`

This also doesn't work. It uses the `borderColor` and ignores the specific side's color.

**Comment by janewuwz** [comment] 2020-09-09 07:37
Still an issue on rn 0.63

**Comment by Rramandeep** [comment] 2020-10-16 07:51
here is a workaround for setting dashed border at bottom. by this approach dashed style border can be set on any side.

 <View>
                  <Text style={{ marginRight: 10, color: '#006087' }}>Routing Numbers</Text>
                  <View style={{ marginRight: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-evenly', marginTop: -10 }}>
                    <Text>-</Text>
                    <Text>-</Text>
                    <Text>-</Text>
                    <Text>-</Text>
                    <Text>-</Text>
                    <Text>-</Text>
                    <Text>-</Text>
                    <Text>-</Text>
                    <Text>-</Text>
                    <Text>-</Text>
                    <Text>-</Text>
                    <Text>-</Text>
                    <Text>-</Text>
                    <Text>-</Text>
                    <Text>-</Text>
                  </View>
                </View>

**Comment by Rramandeep** [comment] 2020-10-16 07:53
` <View>
                  <Text style={{ marginRight: 10, color: '#006087' }}>Routing Numbers</Text>
                  <View style={{ marginRight: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-evenly', marginTop: -10 }}>
                    <Text>-</Text>
                    <Text>-</Text>
                    <Text>-</Text>
                    <Text>-</Text>
                    <Text>-</Text>
                    <Text>-</Text>
                    <Text>-</Text>
                    <Text>-</Text>
                    <Text>-</Text>
                    <Text>-</Text>
                    <Text>-</Text>
                    <Text>-</Text>
                    <Text>-</Text>
                    <Text>-</Text>
                    <Text>-</Text>
                  </View>
                </View>`

**Comment by kishanbharda** [comment] 2021-01-27 14:08
"react-native": "0.63.4" and still have an issue. Have anyone find solution ?

**Comment by euthribeiro** [comment] 2021-01-27 14:35
@kishanbharda The only solution to this problem so far is to define a borderRadius with a value of 1

**Comment by kishanbharda** [comment] 2021-01-28 05:14
@euthribeiro I tried but not working in iOS. Same code working for Snack.io but not working in iOS.

**Comment by fabriziobertoglio1987** [comment] 2021-01-29 08:15
Thanks a lot. There is a pr https://github.com/facebook/react-native/pull/29099 that fixes this issues. Please review and test my pull request. :peace_symbol: :pray:

**Comment by euthribeiro** [comment] 2021-01-29 12:34
@kishanbharda Really, in IOS I also can't get a dashed line or a partial border (only on top, bottom and etc). I believe it is a limitation of IOS.

**Comment by kishanbharda** [comment] 2021-01-29 12:39
Yes @euthribeiro  may be. But I have currently solved my issue using workaround solution. I used [react-native-dash](https://github.com/obipawan/react-native-dash) library to solve this issue. It gives you workaround solution to draw specific side border, actually may be that not a border but you can use to solve issue.

**Comment by euthribeiro** [comment] 2021-01-29 12:43
@euthribeiro Gosh, thanks for sharing!

**Comment by chybisov** [comment] 2021-02-08 12:30
I have the same issue. 😞

**Comment by chinieer** [comment] 2021-03-12 08:31
temporary fix by this hacker

    <View style={[{ height: 1, overflow: 'hidden' }]}>
      <View style={[{ height: 2, borderWidth: 1, borderColor: '#ddd', borderStyle: 'dashed' }]}></View>
    </View>

**Comment by fabriziobertoglio1987** [comment] 2021-03-16 15:57
> Please, is it possible to merge this PR in the next version ?

To answer the question of when the pr https://github.com/facebook/react-native/pull/29099 which fixes this issue will be released in the next version of React Native, I suggest you to follow the discussions at https://github.com/react-native-community/releases/issues by subscribing to those threads. The process of releasing a new version with a bug fix is the following:

- an Issue is opened in facebook/react-native
- a contributor writes a Pull Request to fix/close the react-native Issue
- The Pull Request is merged in Master
- For each realease (the upcoming one is 0.64.1) there will be a separate discussion on https://github.com/react-native-community/releases/issues where anyone can request a commit to be cherrypicked from master. The link need to be from the a **commit** from master (for ex. https://github.com/facebook/react-native/pull/29157#issuecomment-651430945) and not a Pull Request not yet merged in master :peace_symbol: :pray:

**Comment by khushal87** [comment] 2021-04-25 17:28
Any fix for this?

**Comment by Akumzy** [comment] 2021-05-08 09:18
@chinieer it's not working for me and I'm using expo

**Comment by Akumzy** [comment] 2021-05-08 09:18
@chinieer it's not working for me and I'm using expo

**Comment by AstroCorp** [comment] 2021-05-13 13:50
Still an issue on rn 0.64.1 :'v

**Comment by nobi1007** [comment] 2021-05-27 09:49
hack: (inspired from @chinieer's hack)

```js
<View style={{overflow:'hidden'}}>
  <View style={{borderStyle: 'dashed', borderWidth: 1, borderColor: '#000', margin: -2, marginBottom:0}}>
    <Text>Some Data to be underlined</Text>
  </View>
</View>
  
```

**Closed** 2021-08-02 11:06 UTC
Labels: Bug, Low-Pri, Platform: Android, Platform: iOS

**Comment by evilrescuer** [comment] 2021-08-05 13:39
> temporary fix by this hacker
> 
> ```
> <View style={[{ height: 1, overflow: 'hidden' }]}>
>   <View style={[{ height: 2, borderWidth: 1, borderColor: '#ddd', borderStyle: 'dashed' }]}></View>
> </View>
> ```
overflow is amazing

**Comment by georgeemichel** [comment] 2021-11-01 09:16
still an issue. 
<View 
     style={{
     borderColor:"#000",
     borderBottomWidth:1,
     borderStyle:'dashed'
     }}
 />
 
 react-native 65.1

**Comment by bbenoi01** [comment] 2022-05-02 20:19
Still having issue in RN 0.64.3

**Comment by anatooly** [comment] 2022-06-09 10:09
Still having issues in RN 0.67.4

**Comment by aipjamjam** [comment] 2022-06-14 02:16
> <View style={[{ height: 1, overflow: 'hidden' }]}>
>   <View style={[{ height: 2, borderWidth: 1, borderColor: '#ddd', borderStyle: 'dashed' }]}></View>
> </View>

thanks dude, this is work for me. Everyone when u will make dotted or dashed, can use this

**Comment by fuadrifki** [comment] 2022-06-25 16:45
> hack: (inspired from @chinieer's hack)
> 
> ```js
> <View style={{overflow:'hidden'}}>
>   <View style={{borderStyle: 'dashed', borderWidth: 1, borderColor: '#000', margin: -2, marginBottom:0}}>
>     <Text>Some Data to be underlined</Text>
>   </View>
> </View>
>   
> ```

till now still having issue in RN 0.68.1. but this is work for me. thank you

**Comment by sairamreddy2211** [comment] 2022-07-16 16:02
> @euthribeiro I tried but not working in iOS. Same code working for Snack.io but not working in iOS.
 
any idea how to make it work in IOS @euthribeiro

**Comment by rodnick5** [comment] 2022-07-19 14:36
<View style={{overflow:'hidden'}}>
  <View style={{borderStyle: 'dashed', borderWidth: 1, borderColor: '#000', margin: -2, marginBottom:0}}>
    <Text>Some Data to be underlined</Text>
  </View>
</View>

It doesn't work for Android, but works for IOS

**Comment by sergeu90** [comment] 2022-11-26 15:44
I getting warning Unsupported dashed / dotted border style on the ios.

**Comment by MeFelixWang** [comment] 2022-12-15 01:35
Still having issue  in 0.70.5

**Comment by IvanAfonin** [comment] 2023-08-20 10:35
Still having this issue 0.72.3

**Comment by TomasSestak** [comment] 2024-02-02 14:55
Should be reopened

**Comment by suhitaga** [comment] 2024-08-01 00:39
How is this still an issue? It's been like this since 2017 or so? Text already has a similar feature with the `textDecorationStyle: "dotted"`/`textDecorationStyle: "dashed"`
