### ISSUE TITLE
Error after upgrade to 0.12.0

### ISSUE THREAD

**Issue by Pajn** [facebook/react-native#3344] opened 2015-10-11 19:59 UTC
After upgrade I got the same error as anyone else (Android), but after changing the dependency in `build.gradle` to 0.12 and running `react-native run-android` I got

```
10-11 21:55:44.998  5656  5656 E unknown:React: Exception in native call from JS
10-11 21:55:44.998  5656  5656 E unknown:React: com.facebook.react.bridge.UnexpectedNativeTypeException: TypeError: expected dynamic type `int64', but had type `string'
10-11 21:55:44.998  5656  5656 E unknown:React: 	at com.facebook.react.bridge.ReadableNativeMap.getInt(Native Method)
10-11 21:55:44.998  5656  5656 E unknown:React: 	at com.facebook.react.views.view.ReactDrawableHelper.createDrawableFromJSDescription(ReactDrawableHelper.java:66)
10-11 21:55:44.998  5656  5656 E unknown:React: 	at com.facebook.react.views.view.ReactViewManager.updateView(ReactViewManager.java:137)
10-11 21:55:44.998  5656  5656 E unknown:React: 	at com.facebook.react.views.view.ReactViewManager.updateView(ReactViewManager.java:40)
10-11 21:55:44.998  5656  5656 E unknown:React: 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:53)
10-11 21:55:44.998  5656  5656 E unknown:React: 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:182)
10-11 21:55:44.998  5656  5656 E unknown:React: 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:137)
10-11 21:55:44.998  5656  5656 E unknown:React: 	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:574)
10-11 21:55:44.998  5656  5656 E unknown:React: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:622)
10-11 21:55:44.998  5656  5656 E unknown:React: 	at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
10-11 21:55:44.998  5656  5656 E unknown:React: 	at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:114)
10-11 21:55:44.998  5656  5656 E unknown:React: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
10-11 21:55:44.998  5656  5656 E unknown:React: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
10-11 21:55:44.998  5656  5656 E unknown:React: 	at android.view.Choreographer.doFrame(Choreographer.java:603)
10-11 21:55:44.998  5656  5656 E unknown:React: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
10-11 21:55:44.998  5656  5656 E unknown:React: 	at android.os.Handler.handleCallback(Handler.java:739)
10-11 21:55:44.998  5656  5656 E unknown:React: 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-11 21:55:44.998  5656  5656 E unknown:React: 	at android.os.Looper.loop(Looper.java:148)
10-11 21:55:44.998  5656  5656 E unknown:React: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
10-11 21:55:44.998  5656  5656 E unknown:React: 	at java.lang.reflect.Method.invoke(Native Method)
10-11 21:55:44.998  5656  5656 E unknown:React: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-11 21:55:44.998  5656  5656 E unknown:React: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by mpatric** [comment] 2015-10-12 11:14
This is a duplicate of #2983 - looks like it will be fixed in the next RC of 0.13

**Comment by mkonicek** [comment] 2015-10-12 13:03
When upgrading to 0.12, you need to update the JS version in `package.json` and Android artifacts version in `build.gradle`. This is not obvious, we either need the JS to be able to detect the Android artifacts are old, or release the Android artifacts to npm along with the JS.

**Closed** 2015-10-12 13:03 UTC

**Comment by Pajn** [comment] 2015-10-12 13:25
This is another issue. As I said I did update the `build.gradle`. If I don't I get the exception `TypeError: expected dynamic type 'string', but had type 'int64` but after I update `build.gradle` I get `TypeError: expected dynamic type 'int64', but had type 'string'`.

Notice that it's a different exception (the types are reversed) and is thrown from a different place.

**Comment by Pajn** [comment] 2015-10-12 14:41
I found the error to be in `TouchableNativeFeedback`. If I remove the usage of that from the app it works.

**Comment by javamonn** [comment] 2015-10-12 18:44
+1, I encountered this same error after updating the react-native version in `build.gradle` and `package.json`. Fix for me (after reading @Pajn's note) was to update the `underlayColor` prop of `TouchableHighlight` to use the int representation of a hex string instead of passing the hex string in directly, which worked fine on 0.11.0. 

` <TouchableHighlight undlerlayColor={parseInt(this.props.underlayColor, 16)} />`

I assume a similar fix would work for `TouchableNativeFeedback`.

**Comment by Pajn** [comment] 2015-10-12 19:51
@javamonn Thank you for your fix, will try it tomorrow! :)

**Comment by cosmith** [comment] 2015-10-20 10:15
I have this same issue and I don't use `TouchableHighlight` or `TouchableNativeFeedback`. I'm downgrading to `0.11.4` for now cause I'm not sure where to look for a fix.
