### ISSUE TITLE
React-native apps not able to connect with backend apis when uploaded to the playstore (for some mobile brands like oneplus, Huawei). only works locally.

### ISSUE THREAD

**Issue by vipin-developer** [facebook/react-native#26669] opened 2019-10-01 08:22 UTC
I was trying to fetch the data from backend APIs which is in node.js, I was able to fetch the data until it is uploaded to play store after play store it doesn't give any error neither warning nor data. and this problem only occurs with some of the mobile brands(like OnePlus and Huawei) for other brands like MI, Samsung it works fine.
``
React Native version:0.60.0 and 0.61.0

## Steps To Reproduce

1. Build app 
2. Upload in play store
3. Open and try to login or see any data.

Describe what you expected to happen: I want to know if there is a problem with fetch on Axios APIs which doesn't support the latest react-native or something.

Snack, code example, screenshot, or link to a repository:

export async function login(email,pass) {
var data={
  email:email,
  password:pass
}
let result = await fetch(url+'login',{method: 'POST',
body: JSON.stringify(data),
headers: {
   Accept: 'application/json',
'Content-Type': 'application/json',
}}).then(response => response.json());

return result;
}

**Comment by radko93** [comment] 2019-10-01 08:28
Are you connecting to `https` APIs only?

**Comment by vipin-developer** [comment] 2019-10-01 09:02
no it's Http only.

**Comment by radko93** [comment] 2019-10-01 09:33
Duplicate of https://github.com/facebook/react-native/issues/24627
Please read more on this issue.

**Closed by radko93** 2019-10-01 09:33 UTC
Labels: Bug

**Comment by vipin-developer** [comment] 2019-10-02 07:10
Thanks @radko93 , it worked saved my day.
