### ISSUE TITLE
Setting styleAttr to "Inverse" in ProgressBarAndroid does not actually invert anything.

### ISSUE THREAD

**Issue by yashvekaria** [facebook/react-native#7084] opened 2016-04-20 10:14 UTC
I have used ProgressBar and applied **styleAttr ="Inverse"**, but it still animating in clockwise direction just like its normal prgress does. I think it's animating behavior should be anticlockwise. Kindly check it or guide me if I have done something wrong.

**Comment by dsibiski** [comment] 2016-04-20 12:20
The prop is `styleAttr` not `styleAttrib`.

http://facebook.github.io/react-native/releases/0.23/docs/progressbarandroid.html#styleattr

**Comment by yashvekaria** [comment] 2016-04-21 06:31
I have checked prop is styleAttr, I have even checked the documentation from your given link. Moreover styleAttr is working correctly for small. large and normal properties. It's Inverse properties are not working well. 

Here are the screenshot , which shows prop is styleAttr not styleAttrib
![p1](https://cloud.githubusercontent.com/assets/5152954/14699822/c2172a40-07b8-11e6-9295-866bb80b908d.png)
![p2](https://cloud.githubusercontent.com/assets/5152954/14699824/cc4182d6-07b8-11e6-9dd6-65d3ba5c824c.png)

**Comment by lacker** [comment] 2016-10-21 03:42
I can reproduce this - looks like `styleAttr` isn't actually doing anything. A small app that reproduces this problem is here: https://rnplay.org/apps/GgLjOw . Based on the docs at https://facebook.github.io/react-native/docs/progressbarandroid.html I would expect setting `styleAttr="Inverse"` to actually invert the progress bar, but it doesn't. (I removed some comments arguing about spelling which I think were a red herring and helpful to this issue.)

**Comment by sreejithr** [comment] 2016-11-14 08:00
I'd like to point that, by inversion, Android means inverting the color.

> The "inverse" styles provide an inverse color scheme for the spinner, which may be necessary if your application uses a light colored theme (a white background).
https://developer.android.com/reference/android/widget/ProgressBar.html

And yea. It's not inverting colors. So there is a problem.

**Comment by djubreel** [comment] 2016-11-26 19:19
@sreejithr is right, but I set up progressbar in a native app and there was really no much difference from the normal style and the inverse style.

**Comment by oximer** [comment] 2017-04-27 01:41
I did a test using a pure android application and the results are similar to what we have on React Native. 

In addition, I found this stackoverflow question: http://stackoverflow.com/questions/15710262/difference-for-widget-progressbar-small-and-widget-progressbar-small-inverse


My source code:
https://paste.ofcode.org/32cTy266vWjpJzbr4bNQhw

Result
![issue](https://cloud.githubusercontent.com/assets/2430694/25464185/50c18a74-2ad1-11e7-854f-12b750c8f9b0.gif)

Suggestion: 
Close this issue.

**Comment by hramos** [comment] 2017-07-20 21:17
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/setting-styleattr-to-inverse-in-progressbarandroid-does-not-actually-invert-anyt

**Closed by hramos** 2017-07-20 21:17 UTC
Labels: Android, Good First Task, Icebox
