### ISSUE TITLE
TextInput > Placeholder prop does not re-render

### ISSUE THREAD

**Issue by joncursi** [facebook/react-native#15348] opened 2017-08-02 23:56 UTC
Consider the following example:

```jsx
<TextInput
  placeholder={this.state.placeholder}
/>
```

The placeholder will not re-render with new text, even if state changes.

**Comment by rmevans9** [comment] 2017-08-03 01:48
I just gave this a test and was unable to repro in Snack with SDK 19 (RN 0.46.1). Could you provide more information?

https://snack.expo.io/Byxte-gvZ

**Comment by hramos** [comment] 2017-08-03 14:47
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-08-03 14:47 UTC
