### ISSUE TITLE
Requiring unknown module "undefined"

### ISSUE THREAD

**Issue by jkbreunig** [facebook/react-native#18179] opened 2018-03-03 22:46 UTC
Error after upgrading 0.54.0 from 0.53.3.

Requiring unknown module "undefined".If you are sure the module is there, try restarting Metro Bundler. You may also want to run `yarn`, or `npm install` (depending on your environment).
handleException @ ExceptionsManager.js:65
handleError @ InitializeCore.js:115
reportFatalError @ error-guard.js:44
guardedLoadModule @ require.js:141
_require @ require.js:130
executeApplicationScript @ debuggerWorker.js:40
(anonymous) @ debuggerWorker.js:65
ExceptionsManager.js:65 Module AppRegistry is not a registered callable module (calling runApplication)

### Environment
Environment:
  OS:  macOS High Sierra 10.13.3
  Node:  8.9.4
  Yarn:  1.5.1
  npm:  5.6.0
  Watchman:  4.9.0
  Xcode:  Xcode 9.2 Build version 9C40b
  Android Studio:  3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.54.0 => 0.54.0

### Expected Behavior
App should launch

### Actual Behavior
UnknownModuleError

### Steps to Reproduce
react-native run-android

**Comment by Jeepeng** [comment] 2018-03-04 18:05
Same problem

**Comment by itchingpixels** [comment] 2018-03-04 18:40
Same here!

**Comment by mobdim** [comment] 2018-03-04 19:25
Same problem. A few days can't solve.

**Comment by HumanUndead** [comment] 2018-03-05 10:38
same problem, stuck too

**Comment by Maydar** [comment] 2018-03-05 11:05
same issue

**Comment by hugoskwirrel** [comment] 2018-03-05 19:07
https://github.com/react-community/react-native-maps/issues/2051#issuecomment-370055156

**Comment by hramos** [comment] 2018-03-05 19:12
Can you clarify - this happens on a brand new project?

**Comment by HumanUndead** [comment] 2018-03-05 21:58
this happens after upgrading from 0.53.3 to 0.54 not on the whole project but some screens

**Comment by HumanUndead** [comment] 2018-03-05 22:25
ok fixed my problem, in my case it was An import for a component using relative path, instead of the @ way. replacing that fixed it

**Comment by cipriancaba** [comment] 2018-03-06 12:38
@HumanUndead Do you have an example of what your problem is? I have a simple class export that is failing with undefined

```
export class TouchableOpacityWebSafe extends Component { ... }
```

and importing with 
```
import { TouchableOpacityWebSafe } from '../../components/webSafe/TouchableOpacityWebSafe'
```

fails.

This happened after upgrade from 0.53.3 to 0.54

**Comment by HumanUndead** [comment] 2018-03-06 12:48
Fix your import, dont use ../../ for your import, use @.

**Comment by cipriancaba** [comment] 2018-03-06 12:56
How would that work? This is a relative path in my custom components.. It's not related to any package.. Maybe I'm missing something about the `@` import syntax?

**Comment by HumanUndead** [comment] 2018-03-06 12:59
Place a packages.json file in your components folder, give it name: ‘components’
Then you can use the @ import syntax

**Comment by cipriancaba** [comment] 2018-03-06 13:42
Even if that might work, I don't think this is the solution for the problem.. The problem is that the imports are failing and I don't really understand why..

Reverted to 0.53.3 for now..

**Comment by HumanUndead** [comment] 2018-03-06 13:48
It will work but its up to you

**Comment by wildseansy** [comment] 2018-03-06 20:52
@HumanUndead - I removed relative imports that go 'up' directories, using the package.json and `import MyComponent from 'components/MyComponent'` syntax.  What do you mean by the '@ syntax' though...? I'm still getting the issue with `unknown module 'undefined'`.  Did you have to replace ALL relative imports, including ones with './MyModule'? ...or just ones that go up 1 or more directories ('../MyModule')?

**Comment by esutton** [comment] 2018-03-07 13:44
Are you using **react-native-maps** ?  

If so, this may be the problem preventing you form using **0.54.0**

See: Requiring unknown module "undefined". #2051

**Comment by kengjungwa** [comment] 2018-03-08 14:00
This is a big show stopper for our team. We've been waiting for 0.54 to get Android's keyboard crash fixes but can't due to this issue. The error occurs even on our internal file import from the same directory (import * as util from './util'). Try to fix for a few days but no luck. Also already tried putting package.json in the component folder but got same error. Not sure how to use  '@ syntax'. So painful to see the app crashes on users everyday. Could anyone shed some light or share any workaround?  Thanks!

**Comment by seantimm** [comment] 2018-03-09 15:43
We're blocked here as well.  I had to change several of our dynamic requires into static imports but finally got blocked at a third-party library that is having the same issue.  It's unclear to me if this is a Metro bundler issue, or if this is a change that libraries need to accommodate.  If it's the latter, I guess I'll start digging in and making pull requests.

**Comment by wildseansy** [comment] 2018-03-09 20:06
In case anyone was wondering tried `0.54.1`, still same issue

**Comment by mkuczera** [comment] 2018-03-12 09:52
This happens also on iOS. Is this related to the metro-bundler? 0.54.1 is facing the same issue and it´s currently blocking from upgrading. Moving to absolute paths would be a huge change right now, so we planned to move the components one after another instead of all 500 files. 

Is there maybe any workaround to allow relative paths through the rn-cli.config ?

**Comment by webraptor** [comment] 2018-03-13 08:05
Happens as well on 
"react": "16.3.0-alpha.1",
"react-native": "0.54.2",
"react-native-maps": "0.20.1",

**Comment by pavel-beloborodov** [comment] 2018-03-13 12:45
any updates?

**Comment by andrew-wagner89** [comment] 2018-03-13 14:48
@pavel-beloborodov I opened an issue on the metro repository ([here](https://github.com/facebook/metro/issues/152)) we'll see if that helps

**Comment by andrew-wagner89** [comment] 2018-03-13 18:07
@pavel-beloborodov seems like they found the problem and are looking into a metro fix now!

**Comment by Arshiamidos** [comment] 2018-03-13 21:52
i upgraded to 0.54 for this #18359 reason.and now this issue :|

**Comment by rnageli** [comment] 2018-03-14 05:39
React native requiring unknown module "492", if you are sure module is there try restarting metro-bundler.

I got the above error on android OS. I closed the app on the multi-task button and opened the app again from within the emulator and it worked for me.

**Comment by wildseansy** [comment] 2018-03-14 13:59
@rnageli - that is likely a different issue. This one produces `Requiring unknown module "undefined"`, on both Android and iOS consistently. Have tried restarting metro-bundler, re-installing node_modules, clearing caches etc...  Doesn't help.

**Comment by wildseansy** [comment] 2018-03-14 14:45
I was able to resolve this issue for my project by doing the following...

Given that this issue seems to be caused when there is `import {y} from x` and `import {z} from x` in the same file, I was able to track down these files with these steps:

1. Run your app until you get the error message
1. In the stack trace, click on the filename included from your project, under one of the `_require` items in the stack trace.  See screenshot below.
![simulator screen shot - iphone 7 - 2018-03-14 at 07 23 53](https://user-images.githubusercontent.com/177857/37409002-83734c6a-275a-11e8-9cb8-09cfdb67a726.png)

### In my file (actions.js), before changes
```javascript
import {
  getUserEmail
} from 'myapp/user/selectors';

import {
  getUserName
} from './selectors';  //<-- same file as 'myapp/user/selectors'. This is why metro crashes
```
### actions.js after changes
```javascript
// Change the above to: 
import {
  getUserEmail,
  getUserName
} from 'myapp/user/selectors';
```

This will also work:
```javascript

// Or you can change it to: 
import {
  getUserEmail,
  getUserName
} from './selectors';
```

I just had to do this 3-4 times before I had found all of the modules that import from the same file.  Hope this helps someone else.

**Comment by esutton** [comment] 2018-03-14 14:57
@wildseansy Thanks!

Similar to other metro errors that have blocked upgrading ( more than once ) over the past few months...

I was totally **clueless** on how to track this down and had given up upgrading to **RN 0.54**

* yarn *usually* gives a clue when something goes wrong.  
* metro "not so much"

**Comment by davidck** [comment] 2018-03-14 19:45
Ran into this issue with RN 0.54.2 with latest `react-native-maps` update; they now "fixed" it in their master branch.

**Comment by Arshiamidos** [comment] 2018-03-14 20:22
i also solved with package.json manipulatoin 
check this out #2051

**Comment by sibelius** [comment] 2018-03-14 22:12
you can use a eslint rule to help on this https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-duplicates.md

**Comment by cyardimci** [comment] 2018-03-15 17:29
Hey guys, for me the problem was the following
in my index.js (or whatever you call it)

```
import { AppRegistry } from 'react-native';
import { MyApp } from './app/index';

AppRegistry.registerComponent('my-app', () => MyApp);
```

MyApp was exported like
```
export default () => (
    ... some stuff
);
```

so instead I did the following
```
const MyApp = () => (
    .. some stuff
);

export { MyApp };
```

So you may try converting some default exports to named ones.

**Comment by andrew-wagner89** [comment] 2018-03-16 14:30
Seems like this has been fixed in metro with [this](https://github.com/facebook/metro/commit/233b00e8366b4429bee4104502339ccb7e7bcb91) commit and released in v0.30.2, which react native just bumped its dependency to in master so hopefully its included in the next release

**Comment by tahatag** [comment] 2018-03-16 23:18
@wildseansy saved me

**Comment by thatjuan** [comment] 2018-04-03 02:40
@wildseansy good call. That's the issue, spot on.

**Comment by huy-lv** [comment] 2018-04-06 03:36
@wildseansy you saved my life :)) sometime the error show on console.error not correct line, but correct filename

**Comment by mshavandi** [comment] 2018-05-21 05:43
My Error was: 

> Requiring unknown module "492"

The problem was in my index.js file and App.js file both! My index,js file was like:
```
import { AppRegistry } from 'react-native';
import { MyApp } from './app';

AppRegistry.registerComponent('my-app', () => MyApp);
```
And my App.js had the same sentences as the first and the last sentence in my index.js file. Meaning my App.js file was like:
```
import React, { Component } from 'react'
import {
  AppRegistry,
...,
...,
}
 My code;
.
.
AppRegistry.registerComponent('my-app', () => MyApp);
```

I just deleted the first line and the last line of index.js file and it worked. Meaning the index.js file of mine turned into:

`import { MyApp } from './app';`

Hope this help you too.

**Comment by mikehuebner** [comment] 2018-06-02 02:44
Also seeing this issue with a node_module item that is calling a local file. However calling the file from the source (for example import {ITEM} from 'MODULE/FILE') works fine. I've trying to see if renaming the file or just moving the file helps but so far no luck.

**Comment by deGhost** [comment] 2018-09-13 11:59
I fixed this problem by npm start

**Comment by michalchudziak** [comment] 2019-03-19 12:51
The issue was referenced by a metro team: https://github.com/facebook/metro/issues/152 and should be fixed with the new version of React Native.

We are going to close this issue. If it's actually still an issue with 0.59 please comment below and we can reopen it.

**Closed** 2019-03-19 13:50 UTC
Labels: Help Wanted :octocat:, Type: Bug Report

**Comment by abhishekgoyal88** [comment] 2019-06-26 05:27
Thanks @cyardimci. it works

**Comment by gventuri** [comment] 2019-07-15 21:38
<img width="320" alt="Screenshot 2019-07-15 at 23 37 44" src="https://user-images.githubusercontent.com/15671184/61251032-9974b000-a759-11e9-8cbe-be464acb28c9.png">
Still a bug on 0.59 as far as I know..

**Comment by git-jr** [comment] 2019-08-10 18:05
Sometimes cleaning and restarting can help, worked for me on android:

`cd android && gradlew clean && cd .. && react-native run-android`

**Comment by rdankhara** [comment] 2020-01-01 23:52
Below is what I started seeing, it was working fine, suddenly started seeing below, no clue of what file is causing, tried changing imports

![image](https://user-images.githubusercontent.com/550208/71647622-906ca080-2cf1-11ea-9097-37d32374c7f9.png)

**Comment by rdankhara** [comment] 2020-01-02 19:51
For me it was problem in importing React as well

**Comment by thomashagstrom** [comment] 2020-02-15 16:39
> Below is what I started seeing, it was working fine, suddenly started seeing below, no clue of what file is causing, tried changing imports
> 
> ![image](https://user-images.githubusercontent.com/550208/71647622-906ca080-2cf1-11ea-9097-37d32374c7f9.png)

Got exacty this error when I forgot to install and link (pod install) 

**react-native-vector-icons**

**Comment by ahsan-khan1999** [comment] 2020-02-28 16:31
Same issue !

**Comment by abdi4** [comment] 2020-03-13 06:26
Same here. None of the above solutions apply/work for me
