### ISSUE TITLE
Unexpected token ) with React Native 0.56.0-rc.2

### ISSUE THREAD

**Issue by SupriyaKalghatgi** [facebook/react-native#19820] opened 2018-06-20 10:08 UTC
## Environment
Run `react-native info` in your terminal and paste its contents here.
```
react-native info
RN56/node_modules (32ms)

  React Native Environment Info:
    System:
      OS: macOS Sierra 10.12.6
      CPU: x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
      Memory: 25.48 MB / 8.00 GB
      Shell: 5.2 - /bin/zsh
    Binaries:
      Node: 8.0.0 - ~/.nvm/versions/node/v8.0.0/bin/node
      Yarn: 1.3.2 - ~/.yarn/bin/yarn
      npm: 5.0.0 - ~/.nvm/versions/node/v8.0.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.2, macOS 10.13, tvOS 11.2, watchOS 4.2
      Android SDK:
        Build Tools: 23.0.1, 25.0.3, 26.0.1, 26.0.2
        API Levels: 23, 25, 26
    IDEs:
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      react: 16.3.2 => 16.3.2
      react-native: 0.56.0-rc.2 => 0.56.0-rc.2
```

## Description
https://user-images.githubusercontent.com/13464885/41651555-74625b94-749e-11e8-898a-9b6e5ee3561b.png

I then get 
https://user-images.githubusercontent.com/13464885/41651909-5a3b5c9c-749f-11e8-8f6a-e19c153b61e8.png

## Reproducible Demo
Create app with these dependencies
```
  "dependencies": {
    "react": "16.3.2",
    "react-native": "0.56.0-rc.2"
  },
```

**Comment by SupriyaKalghatgi** [comment] 2018-06-20 10:09
https://github.com/facebook/react-native/issues/19819

**Comment by kelset** [comment] 2018-06-21 09:42
Hi @SupriyaKalghatgi , I am going to close this since it seems that the error is caused by a configuration issue on your side - I suggest you keep an eye on #19789 for how to tackle errors related to custom configs.

On the other hand, I suggest that you wait until 0.56.0 gets released and then use `react-native-git-upgrade` to update your project to this new version.

If you think that your issue is not being covered by what I wrote about, please provide more details about how to reproduce your issue.

**Closed by kelset** 2018-06-21 09:42 UTC
Labels: :wrench:Tooling
