### ISSUE TITLE
React Native 0.47, onScroll is not triggered after scrollTo is called with no animation

### ISSUE THREAD

**Issue by naqvitalha** [facebook/react-native#15563] opened 2017-08-19 08:07 UTC
### Is this a bug report?
Yes.

The repro is simple. Scrolling using `scrollTo` does not trigger an onScroll event. No log will be printed in given example. However, if animation is enabled it works fine. Is this expected? On older versions of react native if wasn't this way (talking about 0.30.0).

```js
componentDidMount() {
         this._svRef.scrollTo({x:0,y:100});
}
_handleScroll = (e) =>{
         console.log(e);
}
render(){
         return  <ScrollView ref={(x)=>this.svRef = x} onScroll={this._handleScroll}/>
}
```

**Comment by naqvitalha** [comment] 2017-08-19 10:04
The issue is on Android, working fine in iOS.

**Comment by hramos** [comment] 2017-08-23 19:23
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-08-23 19:23 UTC

**Comment by Manweill** [comment] 2017-08-29 05:51
I has same issue
