### ISSUE TITLE
Component methods not visible in documentation

### ISSUE THREAD

**Issue by chiraggshah** [facebook/react-native#10277] opened 2016-10-06 20:42 UTC
On the current documentation page for [WebView](https://facebook.github.io/react-native/docs/webview.html), the methods (reload, goForward, goBack etc.) are not shown. Which wasn't the case earlier docs for [v0.31](http://facebook.github.io/react-native/releases/0.31/docs/webview.html)

I did some digging and found that maybe it was because of the syntax changes of functions to es6 https://github.com/facebook/react-native/commit/a2fb703bbb988038323c55b29b40e8f5ff52966d
The new syntax it seems is not able to recognize the function from the source code and is not able to generate the documentation

To support my observation, the [current documentation](http://facebook.github.io/react-native/docs/drawerlayoutandroid.html) for DrawerLayoutAndroid and the [v0.31 documentation](http://facebook.github.io/react-native/releases/0.31/docs/drawerlayoutandroid.html) both show the methods available for it. And by checking the [source code](https://github.com/facebook/react-native/blob/master/Libraries/Components/DrawerAndroid/DrawerLayoutAndroid.android.js#L263), the syntax changes were not made.

Can this be fixed? Can someone point me to where should the changes be made so that I can have a look and try fixing it? Or maybe I am wrong and this is caused by some other bug. 
Thanks

**Comment by ericvicenti** [comment] 2016-10-11 18:16
I'm guessing the issue is somewhere in here: 

https://github.com/facebook/react-native/blob/master/website/server/extractDocs.js

You can try running the website with these directions: https://github.com/facebook/react-native/blob/master/website/README.md

This was the biggest recent change to doc generation, can you see if this cased the bug?

https://github.com/facebook/react-native/commit/857bae4ea37411eaa4356e6a0f7292b96389a196

**Comment by chiraggshah** [comment] 2017-02-10 10:10
@lacker : Not sure if the issue is fixed as I still do not see the methods (reload, goForward, goBack etc.) in the documentation for WebView. This might be a trivial thing for experienced developers but for newbies just starting off with WebView, they would have to look into the code/examples to actually find these methods. 
Wouldn't it be great if the documentation is fixed?

**Comment by lacker** [comment] 2017-02-10 20:16
Yeah, sorry I closed it since nobody responded to Eric's question rather than saying that the bug is fixed. Are you interested in making an attempt at fixing this? I agree it's quite likely related to the parsing. I think Eric's suggestion of checking out extractDocs is the way to go. Also tagging @hramos as an FYI since Hector is the docsmaster.

**Comment by chiraggshah** [comment] 2017-02-13 10:20
I did try to fix it but was unsuccessful. I see that @hramos has assigned the issue to himself. 👍

**Comment by hramos** [comment] 2017-07-20 22:43
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/component-methods-not-visible-in-documentation

**Closed by hramos** 2017-07-20 22:43 UTC
Labels: Icebox
