### ISSUE TITLE
ScrollView sticky header flickers in the latest builds ( > RN 0.47.1 )

### ISSUE THREAD

**Issue by muhammedbasilsk** [facebook/react-native#15445] opened 2017-08-10 06:33 UTC
### Is this a bug report?
Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`:
`react-native-cli: 2.0.1`
`react-native: 0.47.1`
2. `node -v`:
`v6.11.1`
3. `npm -v`:
`3.10.10`

Then, specify:

- Target Platform:
iOS and Android

- Development Operating System:
macOS

- Build tools:
react-native run-android
react-native run-ios
### Steps to Reproduce

1. Launch the app.
2. Scroll down and up
3. Watch the sticky header behavior

### Expected Behavior

Sticky header should be fixed to the top when scrolling down. And should be stayed without moving unless scrolled back to top and reached at it's actual position. Works well in iOS and Android version RN0.46.4.

### Actual Behavior

With the latest RN release verison (0.47.0), (0.47.1) and pre-release version (v0.48.0-rc.0) sticky header flickers when scrolling down and up.

### Reproducible Demo

Created an expo for this. But the expo SDK have RN version 0.46.1.
Issue can't be seen in expo. But the code can be used.
[expo snack](https://snack.expo.io/BkS0p_KP-)
![android_scrollview_flickering](https://user-images.githubusercontent.com/1559822/29156651-a664489e-7dc0-11e7-93f8-eb9878b47924.gif)

**Comment by nihgwu** [comment] 2017-08-10 08:50
https://github.com/facebook/react-native/issues/2700#issuecomment-321260084

**Comment by linjson** [comment] 2017-08-11 02:43
you should change code in ReactScrollView.java
```
 @Override
  protected void onScrollChanged(int x, int y, int oldX, int oldY) {
    super.onScrollChanged(x, y, oldX, oldY);

    if (mOnScrollDispatchHelper.onScrollChanged(x, y)) {
      if (mRemoveClippedSubviews) {
        updateClippingRect();
      }

      if (mFlinging) {
        mDoneFlinging = false;
      }

      ReactScrollViewHelper.emitScrollEvent(this);
    }
  }
```
find this `onScrollChanged `method,then delete `if (mOnScrollDispatchHelper.onScrollChanged(x, y)) `

**Comment by muhammedbasilsk** [comment] 2017-08-11 13:52
Okay, I will try this change in the RNAndroid. 
Looks like now velocity is brought into the onScrollChanged method.
Need to try different cases anyway.
Thanks for suggestion @linjson

**Comment by onlydave** [comment] 2017-08-22 12:37
Removing the if statement didn't seem to improve much for me on 0.47.1

**Comment by muhammedbasilsk** [comment] 2017-08-22 13:41
@onlydave it is more than just condition if I guess.
I checked the code and found the velocity is being introduced. So removing the if condition may break other areas. Need to check different areas for impacts.

I am using **RN0.46.4**. Which doesn't have this issue. But have issue in flexbox layouting. 
Flex box layout issue is fixed in the **RN0.47.1**, but due to the flickering, I am not able to upgrade.
Hope to get fixed issue in the upcoming releases.

**Comment by janicduplessis** [comment] 2017-09-01 20:46
This is a regression caused by https://github.com/facebook/react-native/commit/f954f3d9b674b13977f722bc3b8dc6c1b99fe6c7, we're looking into a fix!

**Comment by muhammedbasilsk** [comment] 2017-09-06 04:05
thanks for the update @janicduplessis, really appreciate it.

**Comment by gigeos** [comment] 2017-09-07 15:30
To inform people who search informations, it's not fixed in 0.48.1

**Comment by nihgwu** [comment] 2017-09-08 02:46
It should be fixed in 0.48.2

**Closed** 2017-09-09 03:55 UTC

**Comment by onlybenyang** [comment] 2017-10-20 01:31
This issue not fixed on 0.49.x

**Comment by rupamgho123** [comment] 2017-12-22 11:06
@janicduplessis any idea whether this bug will be fixed in future react versions

**Comment by eli-isbell-h360** [comment] 2018-01-05 18:56
@rupamgho123 Upgrading to 0.51.0 seems to have fixed this problem for me, working on both iOS and Android.

**Comment by shleyZ** [comment] 2018-05-06 10:58
@janicduplessis This issue not fixed on RN 0.55.3

**Comment by CharlieOrlando** [comment] 2018-05-28 21:57
Experiencing the same issue in 0.55.4

**Comment by wanghe826** [comment] 2018-08-08 10:15
same issue in 0.54.3
