### ISSUE TITLE
App crashes in 64 bit Android devices

### ISSUE THREAD

**Issue by keerthanarbt** [facebook/react-native#12680] opened 2017-03-03 09:02 UTC
Hi @hramos ,
Please give some explanation.
It seems like some issue related to cpu architecture support.
(We were able to reproduce issues in Samsung S6, S7, Lenova K4 note.. devices)

The same code works fine with other 32 bit devices like, Nexus 5,6, Asus and Moto android devices..
The same code work perfect in Apple device.

Really stuck here please help out.
Otherwise give some reason why you closed this issue. Which will be helpful.

**Comment by rmevans9** [comment] 2017-03-03 11:55
@facebook-github-bot duplicate #12684

**Comment by rmevans9** [comment] 2017-03-03 12:10
Duplicate of https://github.com/facebook/react-native/issues/12684

Github bot is not listening for some reason so can someone close this?

**Closed** 2017-03-03 15:31 UTC
