### ISSUE TITLE
RN project fails with "Property body[6] of BlockStatement..." (Babel related issue)

### ISSUE THREAD

**Issue by wdamien** [facebook/react-native#31960] opened 2021-08-04 23:36 UTC
*EDIT by @kelset: this is caused by a Babel release, read more at [this comment](https://github.com/facebook/react-native/issues/31960#issuecomment-893176992). The offending commit has been reverted, as [mentioned here](https://github.com/facebook/react-native/issues/31960#issuecomment-893213313) - so the issue is solved now. If you are still experiencing it, follow the steps [described here](https://github.com/facebook/react-native/issues/31960#issuecomment-893326758).*

*PLEASE don't post comments like "same here", they only create noise*

---

When creating a new project via `npx react-native init Foo --template react-native-template-typescript`, then running the default `yarn ios` metro throws a compile error:

`error: node_modules/react-native/Libraries/Image/ImageAnalyticsTagContext.js: Property body[6] of BlockStatement expected node to be of a type ["Statement"] but instead got "AssignmentExpression"`

Tested using:
- Typescript 3.9.4 and 4.3.5
- React Native: 0.64.1
- macOS 11.4
- node v14.15.1
- yarn 1.22.10

**Comment by pulnec** [comment] 2021-08-04 23:47
This error started to come out today too.

**Comment by enrickpb** [comment] 2021-08-05 00:18
Same here

**Comment by amadeuszblanik** [comment] 2021-08-05 00:23
Same here

**Comment by douglowder** [comment] 2021-08-05 00:28
Same.

**Comment by GiordanoSpiropulos** [comment] 2021-08-05 00:37
Same, even without using Typescript, creating a newly generated project doesn't work.

**Comment by vkkostin** [comment] 2021-08-05 00:53
Same for us, started about three hours ago.

**Comment by amadeuszblanik** [comment] 2021-08-05 01:08
Tried many different variants and with and without typescript. Nothing works for me.

**Comment by pulnec** [comment] 2021-08-05 01:29
Apparently it may be a problem with the babel, copy the folder '@babel' that is in the node_modules of a working project, in the new project and it ran without problems.

it may be due to an update they did a couple of hours ago

**Comment by GiordanoSpiropulos** [comment] 2021-08-05 01:34
> Apparently it may be a problem with the babel, copy the folder '@babel' that is in the node_modules of a working project, in the new project and it ran without problems.
> 
> it may be due to an update they did a couple of hours ago

Ow, Wow, it worked :)

**Comment by douglowder** [comment] 2021-08-05 01:52
Anyone know which Babel project changed? 😀

**Comment by nucks** [comment] 2021-08-05 01:54
@douglowder @babel/core

**Comment by fnsvalue-git** [comment] 2021-08-05 01:59
> Apparently it may be a problem with the babel, copy the folder '@babel' that is in the node_modules of a working project, in the new project and it ran without problems.
> 
> it may be due to an update they did a couple of hours ago

WOW! This worked! Oh gosh! I thought I messed up my project or sth. Turned out it's just some bugs from the update.

**Comment by douglowder** [comment] 2021-08-05 02:00
I'll try adding a "resolutions" to package.json to force the previous core version and see if that solves the issue

**Comment by GiordanoSpiropulos** [comment] 2021-08-05 02:00
Hope they fix it soon :)

**Comment by punreachrany** [comment] 2021-08-05 02:00
> Apparently it may be a problem with the babel, copy the folder '@babel' that is in the node_modules of a working project, in the new project and it ran without problems.
> 
> it may be due to an update they did a couple of hours ago

WOW! This worked! Oh gosh! I thought I messed up my project or sth. Turned out it's just some bugs from the update.

**Comment by pulnec** [comment] 2021-08-05 02:04
you can also remove the current @babel/core from the package.json and install this version `npm install --save-dev@babel/ core@7.12.9`

**Comment by nucks** [comment] 2021-08-05 02:56
@pulnec is this the only version that works for you? We're struggling to replicate your success.

**Comment by pulnec** [comment] 2021-08-05 03:03
@nucks what I did was check the package.json of the most recent project that I have working with the same version of react native, and make the change from @ babel / core with version 7.19.2, it is important to remove node_modules first.

**Comment by lslsls0001** [comment] 2021-08-05 03:46
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~42.0.1",
    "expo-status-bar": "~1.0.4",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
    "react-native-web": "~0.13.12"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0"
  },
  "private": true
}

Follow exactly the RN demonstration to create the app, this is the package.json without any change, still same issue. I have tried change the other version number, adding plugin, no useful here.

**Comment by nucks** [comment] 2021-08-05 03:48
@lslsls0001 `^7.9.0` will put in the latest update. You'll have to specifically target the other version number, although that still hasn't worked for us either.

**Comment by lslsls0001** [comment] 2021-08-05 03:50
@GiordanoSpiropulos, I copy a @babel/core folder from old react project, change and replace it in the node_modules of this RN project, not working so far.

**Comment by lslsls0001** [comment] 2021-08-05 03:51
2018 comments saying, we have to make sure the version number for all @babel dependencies same, I also tried this method, not working.

**Comment by lslsls0001** [comment] 2021-08-05 03:52
@nucks, they probably will fix it later I hope.

**Comment by pulnec** [comment] 2021-08-05 03:55
this are my dependencies  
` "@babel/core": "7.12.9",
    "@babel/runtime": "7.12.9"`

**Comment by nucks** [comment] 2021-08-05 04:04
@pulnec how is that working? `@babel/runtime` version `7.12.9` does not exist.

**Comment by catnofish93** [comment] 2021-08-05 04:05
@pulnec same problem, @babel/runtime version 7.12.9 does not exist.

**Comment by hansol-yang** [comment] 2021-08-05 04:09
this are my dependencies
`"@babel/core": "7.14.6", "@babel/runtime": "7.14.6"`

**Comment by nucks** [comment] 2021-08-05 04:13
@hansol-yang do those dependencies work for you? Did they fix the problem?

**Comment by JavanHuang** [comment] 2021-08-05 05:29
I'm currently working on an existing project but I have also encountered the same error as well. There may be some problems with `v7.15.0` of `@babel/core` as mentioned earlier in this issue thread.

What I did was to force the version of `@babel/core` and `@babel/runtime` to the previous stable version `v7.14.8`, as below: (all of this is temporary, I would strong discourage pushing this changes until the issues with`@babel/core@7.15.0` are fixed.

```json
"@babel/core": "7.14.8",
"@babel/runtime": "7.14.8",
```
It's currently working for me, but I'll revert back to the following once the issues with `@babel/core@7.15.0` are fixed.
```json
"@babel/core": "^7.15.0",
"@babel/runtime": "^7.15.0",
```

**Comment by brentvatne** [comment] 2021-08-05 05:32
this is a known issue caused by a bug in a newly released version of babel. it will impact all new react-native and expo apps. you can resolve it with yarn resolutions in a new project:

```diff
--- a/package.json
+++ b/package.json
@@ -25,5 +25,8 @@
   },
   "jest": {
     "preset": "react-native"
+  },
+  "resolutions": {
+    "@babel/plugin-transform-react-display-name": "7.14.5"
   }
 }
```

see some discussion here:
- https://twitter.com/notbrent/status/1423152953876176897
- https://twitter.com/notbrent/status/1423153268423790594

**Comment by uwemneku** [comment] 2021-08-05 06:09
> ```diff
> +++ b/package.json
> @@ -25,5 +25,8 @@
> ```

This worked for me with the latest babel updates ie "@babel/core": "^7.15.0" and @babel/runtime": "^7.14.8",

Thanks @brentvatne

**Comment by Talha-6122000** [comment] 2021-08-05 06:34
I just started learning React Native and I was so confused that what is going on

**Comment by Revolt9k** [comment] 2021-08-05 06:47
Same problem here, replacing @babel folder or adding plugin-thansforms-react-display-name to resolutuions doesn't help. Any other suggestions?

**Comment by nicolo-ribaudo** [comment] 2021-08-05 06:54
We are sorry for this, I'm reverting the change at https://github.com/babel/babel/pull/13637.

**Comment by nicolo-ribaudo** [comment] 2021-08-05 07:32
Released in `@babel/plugin-transform-react-display-name@7.15.1`: https://www.npmjs.com/package/@babel/plugin-transform-react-display-name/v/7.15.1

**Comment by nicolo-ribaudo** [comment] 2021-08-05 07:34
We'll try to reland this change making sure that it doesn't break. I never used React Native: is there an example app or a command I can run on Linux to reproduce the error?

**Comment by Revolt9k** [comment] 2021-08-05 07:47
> Released in `@babel/plugin-transform-react-display-name@7.15.1`: https://www.npmjs.com/package/@babel/plugin-transform-react-display-name/v/7.15.1
Still facing the same issue, updation plugin to 7.15.1 doesnt help.

**Comment by nicolo-ribaudo** [comment] 2021-08-05 08:46
@Revolt9k Can you share your lockfile?

**Comment by kelset** [comment] 2021-08-05 09:56
@Revolt9k me and @nicolo-ribaudo have just done a pairing session to verify that `@babel/plugin-transform-react-display-name` version `7.15.1` works correctly.

Aside from making sure that in your yarn/npm lock you have the correct version installed (so checking that you have something like this in place):

```
"@babel/plugin-transform-react-display-name@^7.0.0":
  version "7.15.1" <--- THIS IS THE VERSION YOU NEED TO HAVE
  resolved "https://registry.yarnpkg.com/@babel/plugin-transform-react-display-name/-/plugin-transform-react-display-name-7.15.1.tgz#6aaac6099f1fcf6589d35ae6be1b6e10c8c602b9"
  integrity sha512-yQZ/i/pUCJAHI/LbtZr413S3VT26qNrEm0M5RRxQJA947/YNYwbZbBaXGDrq6CG5QsZycI1VIP6d7pQaBfP+8Q==
  dependencies:
    "@babel/helper-plugin-utils" "^7.14.5"
```

You also need to reset your Metro cache; you can do it in a few ways, the one I use the most is to kill off the running instance, and trigger it via `yarn start --reset-cache`. Doing so will ensure that Metro will pick up the correct plugin and things should work again for you too :)

**Comment by sammy-SC** [comment] 2021-08-05 09:59
> We'll try to reland this change making sure that it doesn't break. I never used React Native: is there an example app or a command I can run on Linux to reproduce the error?

@nicolo-ribaudo you can follow https://reactnative.dev/docs/environment-setup to create and build a project. If the error happens on Android, you should be able to repro on Linux as well. If it happens on iOS only, you will need MacOS.

**Comment by kelset** [comment] 2021-08-05 10:10
@sammy-SC yeah the error happens at the Metro step so the Babel team should be even able to get a "small footprint" CI setup for their workflow that is able to catch these kind of issues in the future: https://github.com/babel/babel/issues/13639

**Comment by Revolt9k** [comment] 2021-08-05 10:19
Thank you guys, reseting Metro cache finally fixes the issue. You are amazing <3.

**Comment by BlockChainerIT** [comment] 2021-08-05 10:57
I have still problem.
node_modules/react-native/Libraries/Image/ImageAnalyticsTagContext.js: Property body[6] of BlockStatement expected node to be of a type ["Statement"] but instead got "AssignmentExpression"

**Comment by NicolasFelippe** [comment] 2021-08-05 11:20
Thanks for this solution, for people who still have the problem, make sure you are following the step by step of the friend from above.

@Kelset

**Comment by vmarcel** [comment] 2021-08-05 13:13
After applying the fix I get a new issue.
```
error: index.js: .env["development"].plugins[0][1] must be an object, false, or undefined
```

Should I just scrap it and create a new project?

**Comment by PedRonald** [comment] 2021-08-05 22:29
resolvi segue a solução:



digita dentro do seu projeto:



npm update @babel/plugin-transform-react-display-name



após finalizar a atualização, so dar npx react-native run-android e seja feliz

**Comment by safaiyeh** [comment] 2021-08-16 16:11
Closing as the team got a resolution for this.

**Closed by safaiyeh** 2021-08-16 16:11 UTC
Labels: JavaScript, Impact: Regression, Resolution: Fixed, 📦Bundler
