### ISSUE TITLE
[Navigator] pressing navigator buttons during pop-transition gives completely empty view

### ISSUE THREAD

**Issue by mfuruskog** [facebook/react-native#7111] opened 2016-04-21 08:59 UTC
We are currently making an app (RN 0.22.2) and have been using Navigator for navigation. Now a very annoying bug as appeared. 

In our navigation bar the right button pushes to the next view and the left button pops. If we press the right button very quickly during a pop transition it however pushes to an empty view. This only occurs if the view we are popping from has a right button. Hence, it seems like the right button listener from the unmounting view is still there during the transition. 
![screen shot 2016-04-21 at 10 53 19](https://cloud.githubusercontent.com/assets/16755510/14703339/a90737b0-07af-11e6-9f81-6056c79e2ede.png)
The right button pushes to a new view.
![screen shot 2016-04-21 at 10 53 44](https://cloud.githubusercontent.com/assets/16755510/14703357/be7c9a5e-07af-11e6-96de-0d7d3e63f805.png)
The left button of the navigation bar in the new view pops back to Start.

![screen shot 2016-04-21 at 10 54 56](https://cloud.githubusercontent.com/assets/16755510/14703409/f7a8d9f0-07af-11e6-82d7-a48bd0d8d38c.png)
If we during the pop transition quickly press the right button, this view appears.

This occurs both on device and in the emulator..

Shouldn't the navigation bar be disabled during the actual transition? If not, how to fix this?

**Comment by grabbou** [comment] 2016-04-24 01:33
I can confirm this is happening, been able to reproduce. Not sure what exactly is happening just yet, but will try to dig in deeper in the morning.

**Comment by mfuruskog** [comment] 2016-04-25 07:26
@grabbou I'm glad you'll look into it. 

I found the issue #4559 where a similar problem is described. I managed to solve our problem by modifying the solution proposed in in that issue. 

The solution described in #4559 is to add a method to the NavigationBar which modifies the pointer-events. The method is then called in Navigator when a transition is completed.
```
updatePointerEvents: function(fromIndex, toIndex) {
  var routeFrom = this.props.navState.routeStack[fromIndex];
  var routeTo = this.props.navState.routeStack[toIndex];

  COMPONENT_NAMES.forEach(function (componentName) {
    var map = this._components[componentName];
    var componentFrom = map.get(routeFrom);
    var componentTo = map.get(routeTo);
    componentFrom && componentFrom.setNativeProps({ pointerEvents:'none' });
    componentTo && componentTo.setNativeProps({ pointerEvents:'box-none' });
  }, this);
},
```

Using only this did not solve our problem. However, I cloned the method and changed ```pointerEvents``` to ```none``` for both cases and called this in ```_transitionTo``` of ```Navigator.js``` and called the above method when the transition had completed. This way, the navigation bar is completely unresponsive to events during transition and becomes clickable only when the transition has finished.

While this works, it feels like a weird hack and it's annoying that we have to modify the Navigator and NavigationBar code.

**Comment by grabbou** [comment] 2016-04-25 11:45
So the issue here is - race condition.

When you fire `pop` - it starts the animation and clears all scenes past index after transition is done. If you call `push` in the meantime, it will also clear that scene which results in a blank page.

**Comment by mfuruskog** [comment] 2016-04-27 08:39
Yea, that should be the issue.. Any idea of how to resolve this in practice?

**Comment by lacker** [comment] 2016-10-21 04:29
It's been a while but nowadays I would recommend using a better navigation library like ExNavigation. Since there's a workaround anyway I'm going to close this issue - feel free to reopen it if there is still a specific bug here that someone should be fixing.

**Closed by lacker** 2016-10-21 04:29 UTC
