### ISSUE TITLE
Upgrading to 0.26.0-rc only works while chrome debugging

### ISSUE THREAD

**Issue by MichaelDanielTom** [facebook/react-native#7592] opened 2016-05-16 22:48 UTC
Hey guys,
After upgrading to 0.26.0-rc, the app only works while chrome debugging (on Android). If not in chrome debug mode, I get:

`attempted to redefine property '__source'`

Any insight into why this is happening?

**Comment by rops** [comment] 2016-05-17 11:55
I'm seeing this as well but I'm still at 0.23.1. I'm assuming some nested dependency got updated overnight?

**Comment by dsibiski** [comment] 2016-05-17 12:44
Would either of you be able to provide a minimal example repo? Does it happen right after `react-native init`?

**Comment by rops** [comment] 2016-05-17 12:49
Happens when the app starts up. Red error screen

**Comment by dsibiski** [comment] 2016-05-17 12:59
@rops: Sorry, I meant does it happen even when creating a brand new project from scratch via the `react-native init` command, or is it something only affecting your existing app?

**Comment by rops** [comment] 2016-05-17 13:10
It doesn't happen with a freshly new app. I'll investigate and provide more info 👍

**Comment by dsibiski** [comment] 2016-05-17 13:18
Great thanks!

**Comment by satya164** [comment] 2016-05-17 13:35
It might have to do with packager cache. Try running packager with `--reset-cache`

**Comment by experimentsin** [comment] 2016-05-17 14:47
I still see this after resetting the package cache. Downloading the bundle by hand with curl and looking at the line that's being complained about yields:

```javascript
var React=require(2 /* React */);
var View=require(119 /* View */);

var ActivityIndicatorIOS=React.createClass({displayName:'ActivityIndicatorIOS',
render:function render(){
return React.createElement(View,babelHelpers.extends({},this.props,{__source:{fileName:_jsxFileName,lineNumber:18},__source:{fileName:_jsxFileName2,lineNumber:18}}));}});



module.exports=ActivityIndicatorIOS;
});
```

where the `babelHelpers.extends()` is the offending line with two `__source` properties.

**Comment by experimentsin** [comment] 2016-05-17 16:14
I don't pretend to understand the root cause of the recent change in behaviour yet (I'm still on 0.23.1 so a breaking npm update elsewhere still suspected) but these ```_jsxFileName``` source annotations seem to originate from:

```
node_modules/babel-plugin-transform-react-jsx-source/lib/index.js
```

By temporarily patching the above file locally such that the visitor function does nothing, then resetting the packager cache and restarting the packager, the problematical duplicate ``__source`` annotations are no longer generated (although at the cost of losing source info for JSX elements I assume).

Should unblock things in a pinch.

**Comment by scriptjs** [comment] 2016-05-17 18:06
@experimentsin Can confirm that works temporarily.

in `node_modules/babel-plugin-transform-react-jsx-source/lib/index.js`, I nulled the visitor and it runs.
```
  return {
    visitor: null
  };
```

**Comment by experimentsin** [comment] 2016-05-17 18:48
It looks like this problem has in fact been patched in `babel-plugin-transform-react-jsx-source` (within the last 24 hours) but not yet released:

https://github.com/babel/babel/pull/3504 

> jsx-source used to blindly add __source to elements without checking if it already exists. When applied more than once or when user has __source property defined on their own, this results in a syntax error ("SyntaxError: Attempted to redefine property '__source'.")

**Comment by experimentsin** [comment] 2016-05-17 19:05
Patch released a few minutes ago as part of Babel 6.9.0 (see Bug Fix section):

https://github.com/babel/babel/releases/tag/v6.9.0

**Comment by scriptjs** [comment] 2016-05-17 19:06
@experimentsin sweet

**Comment by experimentsin** [comment] 2016-05-17 19:26
Confirmed locally that nuking node_modules and doing a fresh `npm install` now yields:

```
> npm list | grep jsx
│   ├─┬ babel-plugin-syntax-jsx@6.8.0
│   ├─┬ babel-plugin-transform-react-jsx@6.8.0
│   │ ├─┬ babel-helper-builder-react-jsx@6.9.0
│   └─┬ babel-plugin-transform-react-jsx-source@6.9.0
│ │ └─┬ acorn-jsx@2.0.1
```

and further that babel-plugin-transform-react-jsx-source@6.9.0 does indeed seem to address the reported problem out of the box without further patching.

**Comment by scriptjs** [comment] 2016-05-17 19:47
Confirming that upgrade to babel@6.9.0 fixes this.

**Comment by dsibiski** [comment] 2016-05-17 20:28
Great, thanks guys. I'll close this for now, let me know if it is not fixed.

**Closed by dsibiski** 2016-05-17 20:28 UTC
Labels: Needs more information
