### ISSUE TITLE
Json value 'auto34' of type nsstring cannot be converted of a YGValue. Did you forget the % or pt suffix

### ISSUE THREAD

**Issue by thangvo406** [facebook/react-native#23995] opened 2019-03-18 09:02 UTC
I using property style sheet. height:'auto'. I run my app on iPhone X 12.1. I get this red screen.

viewBottom:{
        height:'auto',
        borderTopWidth: 0,
        shadowOffset: { width: 0, height: 0 },
        shadowColor: 'transparent',
        shadowOpacity: 0,
        elevation: 0,
        borderWidth:1,
        borderBottomColor:'white',
        backgroundColor:'white',
        borderLeftWidth: 0,
        borderRightWidth: 0,
        borderBottomWidth: 0,
    }
how to resolved this issue?? 
P/s: only appear on iphone X
 
Thank guys.

react native: 0.57
OS: iOS
Device: iPhone X 12.1

![image](https://user-images.githubusercontent.com/48477187/54518561-2881df00-4997-11e9-9ede-a4d6ccc7f3c7.png)

**Comment by kelset** [comment] 2019-03-19 13:00
👋 there - I just tested your snippet on a fresh `react-native init`'ed project and I couldn't reproduce the issue you are mentioning.

I used this code
```
import React from 'react';
import { StyleSheet, Text, View, ScrollView, SafeAreaView } from 'react-native';

export default class App extends React.Component {
  render() {
    return (
      <SafeAreaView style={styles.container}>
        <View style={styles.viewBottom}>
          <Text>Hello!</Text>
        </View>
      </SafeAreaView>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    alignItems: 'center',
    backgroundColor: '#fff',
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    paddingVertical: 30
  },
  viewBottom: {
    height: 'auto',
    borderTopWidth: 0,
    shadowOffset: { width: 0, height: 0 },
    shadowColor: 'transparent',
    shadowOpacity: 0,
    elevation: 0,
    borderWidth: 1,
    borderBottomColor: 'white',
    backgroundColor: 'white',
    borderLeftWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0
  }
});
```

Given that I have only partial visibility to your code, maybe the view that uses that style is not contained by any other view...?

Anyway, I'll close this since it seems fixed in 59. Please provide a repro if it still happens for you - maybe it's something else

**Closed by kelset** 2019-03-19 13:00 UTC
Labels: Ran Commands, Resolution: Needs More Information, Type: Bug Report
