### ISSUE TITLE
NativeRunnable.java: Failed to create Value from JSON:

### ISSUE THREAD

**Issue by NicWickman** [facebook/react-native#22445] opened 2018-11-28 11:43 UTC
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment

react-native: 0.57.7

  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (12) x64 Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
      Memory: 2.48 GB / 11.90 GB
    Binaries:
      Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.2.0 - C:\Program Files\nodejs\npm.CMD

## Description
Fetching a photo object from the Google Maps API causes a fatal error. Works as expected on RN 55.4, but crashes on 57.7

"Error calling RCTDeviceEventEmitter.emit
Failed to create Value from JSON:"

## Reproducible Demo

React Native 57.7

`fetch('https://maps.googleapis.com/maps/api/place/photo?maxwidth=200&photoreference=CnRvAAAAwMpdHeWlXl-lH0vp7lez4znKPIWSWvgvZFISdKx45AwJVP1Qp37YOrH7sqHMJ8C-vBDC546decipPHchJhHZL94RcTUfPa1jWzo-rSHaTlbNtjh-N68RkcToUCuY9v2HNpo5mziqkir37WU8FJEqVBIQ4k938TI3e7bf8xq-uwDZcxoUbO_ZJzPxremiQurAYzCTwRhE_V0' + '&key={SOME API KEY}')
`

**Comment by cmejet** [comment] 2018-12-21 04:46
I also have this issue on 57 when it is a photo. I've racked my brain trying to figure out a way around this, but so far nothing.

Can reproduce by a fetch call that is pulling a photo response. Like above.

**Comment by NicWickman** [comment] 2018-12-23 01:58
As an alternative for now I am using the package react-native-fetch-blob
which works as expected.

**Comment by Pingou** [comment] 2019-01-18 18:02
Same problem using XMLHttpRequest().

**Comment by nonoyek** [comment] 2019-01-28 08:39
Error will come out when i try to read a photo, but text file just work fine. Is there anyone know how to make it work? : (

**Comment by NicWickman** [comment] 2019-01-28 09:46
Use axiom package instead of fetch for now

**Comment by darknblack** [comment] 2019-02-17 21:33
faceing the same problem

**Comment by kelset** [comment] 2019-02-21 15:47
(sorry clicked the close button by mistake!)

Can anyone create a repro with 0.59?

**Comment by grabbou** [comment] 2019-03-19 12:19
Hello there 👋 this issue doesn't have a repro (which means, a react-native init-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗

**Comment by grabbou** [comment] 2019-03-19 12:19
Update: I've tried reproducing with another image and it downloads it w/o issues. Please provide Snack link, here's my example: https://snack.expo.io/HkeWCL0PV

**Closed by grabbou** 2019-03-19 12:19 UTC
Labels: JavaScript, Resolution: Needs Repro, Type: Bug Report

**Comment by cahaverl** [comment] 2019-07-16 00:00
@grabbou Actually that Snack example was very helpful. It does crash on the Honor 7X (made by Huawei) BND-L24. Getprop gives: [ro.build.version.base_os]: [HONOR/BND-L24/HWBND-H:8.0.0/HONORBND-L24/344(C567):user/release-keys].

With the latest version of the Expo app (2.11.4), I get crashes for Expo SDK versions 31 and 32, but not 33, leading to hope that this is fixed in RN 0.59.8.

Huawei-derived phones have been the most susceptible to this bug in my experience.

**Comment by cahaverl** [comment] 2019-07-16 00:42
@grabbou I found also that the "Tap to Play" (again for https://snack.expo.io/HkeWCL0PV) in Snack on Android follows the same pattern, failure for SDKs 31 and 32, success for SDK 33.

**Comment by wiess-huabo** [comment] 2019-12-30 12:08
why this is close? come across this issue.
