### ISSUE TITLE
Unhandle ApolloError@10.0.2.2:8081

### ISSUE THREAD

**Issue by lyquocnam** [facebook/react-native#13346] opened 2017-04-06 15:24 UTC
![image](https://cloud.githubusercontent.com/assets/8347826/24762080/7b476468-1b17-11e7-8e17-7b0edf064494.png)

i trying to use react native android with react-apollo, but this error.
on IOS, this not happen.

**Comment by hramos** [comment] 2017-04-06 17:42
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-04-06 17:42 UTC

**Comment by lyquocnam** [comment] 2017-04-06 22:47
@hramos here is my project
https://github.com/lyquocnam/react-native-demo
please help, im so confuse with this @@

**Comment by JakeDawkins** [comment] 2017-06-01 19:08
@lyquocnam did you resolve this? I'm having the same issue now

**Comment by lyquocnam** [comment] 2017-06-04 07:05
i abandon this project so long @JakeDawkins, react-native update many after that.
