### ISSUE TITLE
navigator.replace have no animation

### ISSUE THREAD

**Issue by L-Jovi** [facebook/react-native#6288] opened 2016-03-04 08:26 UTC
sorry to trouble, I found that `this.props.navigator.replace(route)` have no animation as default `push(route)` action, how could I replace current route with animation transition of `Navigator.SceneConfigs.HorizontalSwipeJump`?

thanks for your time.

regards,

**Comment by grabbou** [comment] 2016-03-04 12:55
Closing as duplicate of https://github.com/facebook/react-native/issues/1981

**Closed by grabbou** 2016-03-04 12:55 UTC
Labels: Contains Potential Question Keywords
