### ISSUE TITLE
bridge is not set (bridge always be nil)

### ISSUE THREAD

**Issue by Symous** [facebook/react-native#15407] opened 2017-08-08 08:22 UTC
I create a iOS class to post event from Native to JS refer to the react native document.

but when I try to execute send event ,it give me an error that 
```js
[tid:com.facebook.react.ShadowQueue] Exception 'bridge is not set. 
This is probably because you've explicitly synthesized the bridge in RCTCameraEvent, 
even though it's inherited from RCTEventEmitter.'
was thrown while invoking capture on target CameraManager with params (
        {
        audio = 0;
        barCodeTypes =         (
        );
        description = "";
        mirrorImage = 0;
        mode = 1;
        playSoundOnCapture = 1;
        preferredTimeScale = 30;
        quality = 0;
        target = 1;
        title = "";
        totalSeconds = 10;
        type = 1;
    },
    3892,
    3893
)
```

we can see that the bridge is nil;

and this is my code :

.h
```oc
#import <React/RCTBridgeModule.h>
#import <React/RCTEventEmitter.h>

@interface RCTCameraEvent : RCTEventEmitter<RCTBridgeModule>

@end
```

.m
```oc
#import "RCTCameraEvent.h"

@implementation RCTCameraEvent

RCT_EXPORT_MODULE();

- (NSArray<NSString *> *)supportedEvents
{
    return @[@"RecordVideoStart"];
}

- (void)onRecordVideoStarted
{
    [self sendEventWithName:@"RecordVideoStart" body:@{@"name": @"111"}];
}

@end
```

code to invoke that :
```oc
RCTCameraEvent * cameraEvent = [[RCTCameraEvent alloc]init];
[cameraEvent onRecordVideoStarted];
```

> related issue: https://github.com/facebook/react-native/issues/8714

React-Native Version: 0.45.1
Platform : iOS 10

**Comment by hramos** [comment] 2017-08-08 18:41
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-08-08 18:41 UTC

**Comment by Liqiankun** [comment] 2017-10-10 03:02
Finally, I got the solution.
```
#import "RNNotification.h"
@implementation RNNotification

RCT_EXPORT_MODULE();

+ (id)allocWithZone:(NSZone *)zone {
    static RNNotification *sharedInstance = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        sharedInstance = [super allocWithZone:zone];
    });
    return sharedInstance;
}

- (NSArray<NSString *> *)supportedEvents
{
    return @[@"EventReminder"];
}

- (void)sendNotificationToReactNative
{
    [self sendEventWithName:@"EventReminder" body:@{@"name": @"name"}];
}
```
When you use it!
```
RNNotification *notification = [RNNotification allocWithZone: nil];
[notification sendNotificationToReactNative]
```

**Comment by ZiBo1233** [comment] 2018-01-16 06:28
@Liqiankun your demo is working.but i want to know why dose it work?

**Comment by Liqiankun** [comment] 2018-01-16 07:52
@ZiBo1233 Truth be told! I don't know!

**Comment by ZiBo1233** [comment] 2018-01-16 08:00
@Liqiankun It's just my guess:In your location, you create a singleton.The Object is the only one.So the class's bridge becomes the singleton.So,no matter where or when you use it , the bridge object is the same .so ,it works.
I'm not sure the guess is truth or not.  😂
