### ISSUE TITLE
JavaScriptException :{}

### ISSUE THREAD

**Issue by abhishekpandeykr** [facebook/react-native#14298] opened 2017-06-02 06:02 UTC
```com.facebook.react.common.JavaScriptException : {}```,
I am getting this issue:
https://lh3.googleusercontent.com/-dcP7z0OZd7E/WTD9h58OKmI/AAAAAAAAAMI/7gEpJgcPNcskrJYJhq4OfSUzeRyNvVUQQCL0B/h1280/3584356336441677400%253Faccount_id%253D2

don't know whats getting wrong?

**Comment by hramos** [comment] 2017-06-02 17:08
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-02 17:08 UTC
