### ISSUE TITLE
Scrollview clips subviews when using LayoutAnimation

### ISSUE THREAD

**Issue by MyGuySi** [facebook/react-native#13870] opened 2017-05-09 15:19 UTC
### Description

I'm trying to animate the height of a header component with a scrollview beneath it using LayoutAnimation. Collapsing is fine but when it's expanding the scrollview seems to calculate it's final height at the start of the animation and clip the subviews.

### Reproduction Steps and Sample Code

Here's a Snack that demonstrates it: https://snack.expo.io/By0fp8yg-

### Additional Information

* React Native version: 0.43.3
* Platform: only tested on iOS
* Development Operating System: macOS

**Comment by beaudry** [comment] 2017-06-09 19:45
Since you change only the height value, I suggest you use the [Animated API](https://facebook.github.io/react-native/docs/animated.html)

**Comment by brennanerbz** [comment] 2017-06-11 21:28
Did you find a fix for this? @MyGuySi

**Comment by MyGuySi** [comment] 2017-06-12 10:19
I haven't had time to try the suggestion above so no progress yet

**Comment by hramos** [comment] 2017-08-16 03:09
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Closed by hramos** 2017-08-16 03:09 UTC
Labels: Icebox
