### ISSUE TITLE
'app:bundleDebugJsAndAssets' as a task with that name already exists

### ISSUE THREAD

**Issue by wv1124** [facebook/react-native#6967] opened 2016-04-14 04:03 UTC
Add productFlavor:
 productFlavors {
        Beta {
            manifestPlaceholders = [UMENG_CHANNEL:"Beta"]
            buildConfigField "String", "CHANNEL", "\"Beta\""
        }

        Qianmi {
            manifestPlaceholders = [UMENG_CHANNEL:"WEB"]
            buildConfigField "String", "CHANNEL", "\"WEB\""
        }
}

solution:
react.gradle
`gradle.projectsEvaluated {
    // Grab all build types and product flavors
    def buildTypes = android.buildTypes.collect { type -> type.name }
    def productFlavors = android.productFlavors.collect { flavor -> flavor.name }

    // When no product flavors defined, use empty
    if (!productFlavors) productFlavors.add('')
    def currentBundleTask
    productFlavors.each { productFlavorName ->
        buildTypes.each { buildTypeName ->
            // Create variant and source names
            def sourceName = "${buildTypeName}"
            def targetName = "${sourceName.capitalize()}"
            if (productFlavorName) {
                sourceName = "${productFlavorName}${targetName}"
            }

            // React js bundle directories
            def jsBundleDirConfigName = "jsBundleDir${targetName}"
            def jsBundleDir = elvisFile(config."$jsBundleDirConfigName") ?:
                    file("$buildDir/intermediates/assets/${sourceName}")

            def resourcesDirConfigName = "jsBundleDir${targetName}"
            def resourcesDir = elvisFile(config."${resourcesDirConfigName}") ?:
                    file("$buildDir/intermediates/res/merged/${sourceName}")
            def jsBundleFile = file("$jsBundleDir/$bundleAssetName")

            // Bundle task name for variant
            def bundleJsAndAssetsTaskName = "bundle${targetName}JsAndAssets"
            if(currentBundleTask == null){
                currentBundleTask = tasks.create(
                        name: bundleJsAndAssetsTaskName,
                        type: Exec) {
                    group = "react"
                    description = "bundle JS and assets for ${targetName}."

                    // Create dirs if they are not there (e.g. the "clean" task just ran)
                    doFirst {
                        jsBundleDir.mkdirs()
                        resourcesDir.mkdirs()
                    }

                    // Set up inputs and outputs so gradle can cache the result
                    inputs.files fileTree(dir: reactRoot, excludes: inputExcludes)
                    outputs.dir jsBundleDir
                    outputs.dir resourcesDir

                    // Set up the call to the react-native cli
                    workingDir reactRoot

                    // Set up dev mode
                    def devEnabled = !targetName.toLowerCase().contains("release")
                    if (Os.isFamily(Os.FAMILY_WINDOWS)) {
                        commandLine "cmd", "/c", "react-native", "bundle", "--platform", "android", "--dev", "${devEnabled}",
                                "--entry-file", entryFile, "--bundle-output", jsBundleFile, "--assets-dest", resourcesDir
                    } else {
                        commandLine "react-native", "bundle", "--platform", "android", "--dev", "${devEnabled}",
                                "--entry-file", entryFile, "--bundle-output", jsBundleFile, "--assets-dest", resourcesDir
                    }

                    enabled config."bundleIn${targetName}" ?: targetName.toLowerCase().contains("release")
                }
            }
            // Hook bundle${productFlavor}${buildType}JsAndAssets into the android build process
            currentBundleTask.dependsOn("merge${targetName}Resources")
            currentBundleTask.dependsOn("merge${targetName}Assets")

            runBefore("processArmeabi-v7a${targetName}Resources", currentBundleTask)
            runBefore("processX86${targetName}Resources", currentBundleTask)
            runBefore("processUniversal${targetName}Resources", currentBundleTask)
            runBefore("process${targetName}Resources", currentBundleTask)
        }
    }
}
`

**Comment by AndrewJack** [comment] 2016-04-14 16:25
Cannot reproduce with the steps and it's unclear what the fix is? 
Could you either submit a pull request with the fix or add more information?

**Comment by AndrewJack** [comment] 2016-04-15 09:02
@facebook-github-bot label Needs more information

**Comment by AndrewJack** [comment] 2016-04-15 09:05
@facebook-github-bot label Needs more information

**Comment by charpeni** [comment] 2016-06-04 14:03
This issue seems fixed since 0.25, I'll close it.

**Comment by facebook-github-bot-6** [comment] 2016-06-04 14:05
@charpeni tells me to close this issue. If you think it should still be opened let us know why.

**Closed by facebook-github-bot-6** 2016-06-04 14:05 UTC
Labels: Android, Needs more information, Ran Commands
