### ISSUE TITLE
[0.45.0] Android release build failed

### ISSUE THREAD

**Issue by vomchik** [facebook/react-native#14417] opened 2017-06-09 09:14 UTC
After updating to new version release build failed. Any ideas how does this fix?

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not list contents of '/Users/vomchik/Projects/LITS/toolook/toolook-app-react-native/node_modules/react-native/third-party/glog-0.3.4/test-driver'. Couldn't follow symbolic link.
```

**Comment by olivierkaisin** [comment] 2017-06-09 10:56
Same problem here, it happens to me when I try to build a release APK for Android at the `:app:bundleReleaseJsAndAssets` step.

As a temporary solution deleting the whole `node_modules` folder and re-installing dependencies fixes it.

**Comment by tabrindle** [comment] 2017-06-09 14:07
I use a Makefile that points its clean target to a full clean script. I have found most issues like this can be solved by killing all simulators, packagers, etc, running clean, then reinstalling node_modules:

clean.sh
```
watchman watch-del-all
rm -rf node_modules
rm -rf $TMPDIR/react-*
```

**Comment by hramos** [comment] 2017-06-09 17:04
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-09 17:04 UTC

**Comment by cinder92** [comment] 2017-06-10 01:04
same issue here! whats going on with latest react native release? is fully os issues in both platforms :(

**Comment by jdeibe** [comment] 2017-06-10 08:48
Same error for me but after a cleanup all works.

**Comment by benoitvallon** [comment] 2017-06-11 03:29
I have the same error. Cleaning the `node_modules` works for me but the error reappears after every Xcode build. Any idea why?

**Comment by nehvaleem** [comment] 2017-06-12 22:14
Also having exact same issue. Solution provided by @olivierkaisin seems to work, but it is indeed frustrating having to delete node_modules at each build.

**Comment by attilaaronnagy** [comment] 2017-06-15 10:49
after every node_modules reinstall i have to update the build tools versions.. so the solution provided by @olivierkaisin works, but please fix this bug, every android build takes 10 times longer than before :(

**Comment by hramos** [comment] 2017-06-15 15:42
This issue is closed. If this is still affecting you, please open a new issue and make sure to fill out everything in the template as documented in the contribution guidelines. Thanks!

**Comment by lslvxy** [comment] 2017-06-16 04:51
Removing node_modules/.bin/ worked

**Comment by itinance** [comment] 2017-06-18 17:03
For me helped to delete the broken test-driver-link:

` unlink node_modules/react-native/third-party/glog-0.3.4/test-driver `

**Comment by Guardiannw** [comment] 2017-06-18 18:26
This is a problem.  Please resolve this.  It is very annoying

**Comment by hramos** [comment] 2017-06-19 23:17
@Guardiannw see my earlier comment.

**Comment by lprhodes** [comment] 2017-06-20 05:05
@hramos  Not every issue should require all details to be filled out before its looked into...it's not always something you can create steps to reproduce. Closing an genuine issue because it doesn't meet your guidelines is pretty poor form.

**Comment by hramos** [comment] 2017-06-20 15:46
My goal here is to get the issue tracker into a better state. There aren't enough people following up and submitting PRs to fix the existing set of open issues. Opening a new issue without providing a minimum level of details is not helping out. I'm happy to reconsider the guidelines once the number of outstanding issues is in better shape. Thanks for understanding.

**Comment by benoitvallon** [comment] 2017-06-20 15:54
The linked issue https://github.com/facebook/react-native/issues/14464 above is perfectly describing what is happening in this issue so there is no need for that one to stay open.

**Comment by ringo22** [comment] 2017-10-22 08:54
@itinance thanks for the answer, for me worked fine!
