### ISSUE TITLE
[Lint] Clean up the JS lint warnings and consider adding `npm run lint` to Travis

### ISSUE THREAD

**Issue by ide** [facebook/react-native#3316] opened 2015-10-09 23:29 UTC
We have over 200 lint warnings 😓Trying to fix them all in one commit is going to be rough and harder to test, bisect, and deal with merge conflicts, but if we attacked them a few files at a time I bet we could knock that number down to zero pretty quickly.

(Thank you to everyone who's submitted a PR. If you are interested in helping out please look at the submitted PRs so we don't overlap!)

**Comment by chirag04** [comment] 2015-10-10 15:02
153 problems (99 errors, 54 warnings) now with that PR.

**Comment by ide** [comment] 2015-10-10 20:50
I got 99 errors but... 😎

Thanks for the PR @chirag04!

**Comment by chirag04** [comment] 2015-10-10 20:58
:+1:  I only focused on trivial things inside library directory.

**Comment by billglover** [comment] 2015-10-16 12:29
It isn't immediately clear why PR #3332 was closed, but I'll assume it was a duplicate of other requests that addressed similar warnings. Apologies for not spotting the overlap before submission.

**Comment by ide** [comment] 2015-10-16 19:58
Your commit was merged so that's why the PR was closed.

**Comment by rumal** [comment] 2015-11-18 17:12
How about https://github.com/jshint/fixmyjs/ on the code?

**Comment by trave7er** [comment] 2015-11-30 23:25
I have several potential PRs that could fix a number of lint warnings in the Libraries directory. Should I make those PR's separately?

**Comment by ide** [comment] 2015-11-30 23:29
@trave7er yes, separate commits would make them easier to review, merge, and bisect if there's an issue. thanks!

**Comment by udnisap** [comment] 2015-12-15 12:23
Now it is `259 problems (119 errors, 140 warnings)`. I can fix it to `199 problems (119 errors, 80 warnings)` with `eslint --fix` Will send a PR

**Comment by mkonicek** [comment] 2016-04-10 16:59
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/lint-clean-up-the-js-lint-warnings-and-consider-adding-npm-run-lint-to-travis

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Closed by mkonicek** 2016-04-10 16:59 UTC
Labels: Good First Task, Help Wanted, Icebox, JS
