### ISSUE TITLE
Use BackHandler in Modal at tvOS

### ISSUE THREAD

**Issue by redak105** [facebook/react-native#14636] opened 2017-06-20 18:18 UTC
Hi,
I try to use BackHandler by tutorial at tvOS. I want to catch press at menu on remote in Modal view.
But, when I show Modal, Modal view stop to listen AppleTV remote events. It stops to sending any RCTTVNavigationEventNotification. I was only particularly successful with transparent modal view. But it didn't work at some designs, mostly connected with flex style.
I want to update my state of my parent ,to let him know, that Modal was closed. Basically set state, which showing this Modal to false.

I am using react native 0.45.1 with npm 5.03.

Can you give me a hint how to do it or fix it?

**Comment by hramos** [comment] 2017-06-20 21:03
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-20 21:03 UTC

**Comment by redak105** [comment] 2017-06-21 08:59
Instriction to create simple exaple at tvOS.
Create component which is showing Modal. In this modal will be another component. Lets call it DetailComponent.  In this component add BackHandler to catch events from remote. In render show only some text. 
Run this and you show Modal with DetailComponent. Whe you touch menu at remote. BackHandler is called. 
Now add some touchable to render of DetailComponent. 
Reload it and show modal again. When you touch menu at remote, BackHandler is not called now. 

When I was looking to native Obj-c code. In the RCTTVRemoteHandler, when I show Modal, didn't call listener to UIGestureRecognizer. Then it can't send notification RCTTVNavigationEventNotification with type of event to Javascript code.

**Comment by BenBenz** [comment] 2017-06-27 12:59
I have the same problem

**Comment by redak105** [comment] 2017-07-18 14:52
How I can reopen this issue?

**Comment by hramos** [comment] 2017-07-18 17:03
@redak105 let us know after you've edited your original comment and we can re-open it. As I said earlier, there's a template that needs to be filled out in order to keep an issue open. You can see it when you create a new issue.
