### ISSUE TITLE
Error Undefined is not an object (evaluating 'self.fetch') when importing Realm in React Native

### ISSUE THREAD

**Issue by ataravati** [facebook/react-native#22956] opened 2019-01-11 01:14 UTC
## Environment
React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
      Memory: 1.47 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.1 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 27
        Build Tools: 27.0.3, 28.0.3
        System Images: android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.2 => 0.57.2
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
I get the following error message when importing Realm.  

> Undefined is not an object (evaluating 'self.fetch')

The issue has already been discussed [here](https://github.com/facebook/react-native/issues/9599) and [here](https://github.com/realm/realm-js/issues/1509). 

## Reproducible Demo
I tried the solution provided in the other posts mentioned under Description, and the issue was resolved temporarily, until I added a reference to one of my mobx-state-tree stores. I did try the same solution in other screens, but that didn't help.

**Comment by maxammann** [comment] 2019-01-11 10:44
I can confirm this issue. This happens only in when "Debug JS Remotely" is turned off.

**Comment by leaphawk** [comment] 2019-02-08 20:23
This is likely an issue with the `npm` & `builder` cache. You must be having another dependency depending on `whatwg-fetch`.

Which you can easily check with `npm ls whatwg-fetch`.

Remove the dependency which is using `whatwg-fetch` reinstall it. Also clear the builder cache. If you're using expo `expo start -c`

You'll find some solution stating to do: `global.self = global`. Which is not really a solution.

**Comment by ataravati** [comment] 2019-03-14 22:07
@leaphawk The only dependency is fbjs which is part of react-native. I did manage to resolve the issue by using `global.self = global`, but as I added more screens to the application the issue came back.

**Comment by dulmandakh** [comment] 2019-03-19 14:09
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗

**Comment by dulmandakh** [comment] 2019-03-19 14:10
Please upgrade to 0.59, and also provide reproducible demo.

**Closed by dulmandakh** 2019-03-19 14:09 UTC
Labels: Type: Bug Report, 🌐Networking

**Comment by maxammann** [comment] 2019-05-17 16:35
In my case this was caused by using the legacy babel plugin "transform-es2015-modules-commonjs".
