### ISSUE TITLE
 Caused by: java.lang.IllegalStateException: closed 

### ISSUE THREAD

**Issue by Rcrosp** [facebook/react-native#13853] opened 2017-05-09 05:31 UTC
java.lang.RuntimeException: An error occurred while executing doInBackground()
AndroidRuntime: at android.os.AsyncTask$3.done(AsyncTask.java:309)
AndroidRuntime: at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
AndroidRuntime: at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
AndroidRuntime: at java.util.concurrent.FutureTask.run(FutureTask.java:242)
AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
AndroidRuntime: at java.lang.Thread.run(Thread.java:818)
AndroidRuntime: Caused by: java.lang.IllegalStateException: closed
AndroidRuntime: at okhttp3.internal.ws.RealWebSocket.close(RealWebSocket.java:164)
AndroidRuntime: at com.facebook.react.packagerconnection.ReconnectingWebSocket.closeWebSocketQuietly(ReconnectingWebSocket.java:110)
AndroidRuntime: at com.facebook.react.packagerconnection.ReconnectingWebSocket.closeQuietly(ReconnectingWebSocket.java:103)
AndroidRuntime: at com.facebook.react.packagerconnection.JSPackagerClient.close(JSPackagerClient.java:96)
AndroidRuntime: at com.facebook.react.devsupport.DevServerHelper$2.doInBackground(DevServerHelper.java:158)
AndroidRuntime: at com.facebook.react.devsupport.DevServerHelper$2.doInBackground(DevServerHelper.java:154)
AndroidRuntime: at android.os.AsyncTask$2.call(AsyncTask.java:295)
AndroidRuntime: at java.util.concurrent.FutureTask.run(FutureTask.java:237)
AndroidRuntime: ... 3 more

AndroidRuntime: at okhttp3.internal.ws.Rea

**Comment by Rcrosp** [comment] 2017-05-09 05:34
"react-native": "^0.43.2"

**Comment by dobrienlzd** [comment] 2017-05-09 16:02
Check if react-native 0.43.2 is actually installed.
npm list -g --depth=0

you can install latest with 
npm install --save react-native@0.44.0  or at least 0.43.4 which is what i have.

**Comment by jayshah123** [comment] 2017-05-22 10:18
This happens when I do  -> MainActivity.this.recreate(); in dev mode.

**Comment by githubdoramon** [comment] 2017-06-01 21:56
It is happening to me almost every time on dev mode

**Comment by githubdoramon** [comment] 2017-06-13 12:36
Please.... any advice on this? It is getting impossible to develop... I can't use dev mode anymore

**Comment by iegik** [comment] 2017-06-16 16:03
Same on RN 0.42.3

**Comment by hramos** [comment] 2017-06-16 20:12
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-16 20:12 UTC
