### ISSUE TITLE
Getting started doesn't ends up with success.

### ISSUE THREAD

**Issue by damianprzygodzki** [facebook/react-native#11157] opened 2016-11-27 15:08 UTC
Really simply issues, that i can't handle. 

As 'getting started' says,

```
brew install node
brew install watchman
sudo npm install -g react-native-cli
react-native init AwesomeProject
cd AwesomeProject
sudo react-native run-ios
```

ends up with opened simulator and installed `AwesomeProject` app. After trying to open that app, we see the launch view and app close suddenly.

UPDATE: It is weird as hell, after few hours of investigating.

1) I've tried to build app from XCode, it throws exception:

```
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'bundleURL must be non-nil when not implementing loadSourceForBridge'
```

Then i've found that theres lot of solutions for it, and one is to put the localhost:8081 directly to jsCodeLocation var in AppDelegate - i think, "what the heck localhost:8081?", and after that, i've just 
```
npm start
```
in the main directory of my app, and it started working.

C'mon team, with much love and respect, please extend documentation for very noob people that want to go into the React Native world.

**Comment by mkonicek** [comment] 2016-11-28 01:37
`react-native run-ios` should open a new terminal window with the packager running, so you don't have to run `npm start`. What OS are you using?

Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, please feel free to open a new one with necessary information to debug this. Thanks!

**Closed by mkonicek** 2016-11-28 01:37 UTC

**Comment by wangking873** [comment] 2016-12-09 17:51
127.0.0.1 localhost
