### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: com.facebook.react.packagerconnection.ReconnectingWebSocket

### ISSUE THREAD

**Issue by braheja** [facebook/react-native#14201] opened 2017-05-26 05:22 UTC
I am getting following exception after adding some android specific library in app:

FATAL EXCEPTION: AsyncTask #1
                                                 Process: com.dummyapp, PID: 3773
                                                 java.lang.RuntimeException: An error occured while executing doInBackground()
                                                     at android.os.AsyncTask$3.done(AsyncTask.java:304)
                                                     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                     at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                     at java.lang.Thread.run(Thread.java:818)
                                                  Caused by: java.lang.NoClassDefFoundError: com.facebook.react.packagerconnection.ReconnectingWebSocket
                                                     at com.facebook.react.packagerconnection.JSPackagerClient.<init>(JSPackagerClient.java:79)
                                                     at com.facebook.react.devsupport.DevServerHelper$1.doInBackground(DevServerHelper.java:157)
                                                     at com.facebook.react.devsupport.DevServerHelper$1.doInBackground(DevServerHelper.java:132)
                                                     at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                     at java.lang.Thread.run(Thread.java:818)

**Comment by braheja** [comment] 2017-05-26 05:24
I am getting following exception after adding some android specific library in app: 
FATAL EXCEPTION: AsyncTask #1
                                                 Process: com.dummyapp, PID: 3773
                                                 java.lang.RuntimeException: An error occured while executing doInBackground()
                                                     at android.os.AsyncTask$3.done(AsyncTask.java:304)
                                                     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                     at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                     at java.lang.Thread.run(Thread.java:818)
                                                  Caused by: java.lang.NoClassDefFoundError: com.facebook.react.packagerconnection.ReconnectingWebSocket
                                                     at com.facebook.react.packagerconnection.JSPackagerClient.<init>(JSPackagerClient.java:79)
                                                     at com.facebook.react.devsupport.DevServerHelper$1.doInBackground(DevServerHelper.java:157)
                                                     at com.facebook.react.devsupport.DevServerHelper$1.doInBackground(DevServerHelper.java:132)
                                                     at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                     at java.lang.Thread.run(Thread.java:818)

**Comment by hramos** [comment] 2017-05-26 21:59
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-05-26 21:59 UTC

**Comment by Krupen** [comment] 2017-05-31 12:11
For me, problem was because "package" in AndroidManifest.xml and "applicationId" in build.gradle(app) was different. Making them same solved the problem for me.

**Comment by sytolk** [comment] 2017-08-14 07:32
For me, this happened after update from "react": "16.0.0-alpha.6" and "react-native": "0.44.1"

react-native-cli: 2.0.1
react-native: 0.46.0
node -v  v7.8.0
npm -v 5.3.0
yarn --version 0.27.5

```
--------- beginning of crash
08-14 10:16:40.751 5613-5670/de.drivelog.connect.poc E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                                       Process: de.drivelog.connect.poc, PID: 5613
                                                                       java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                           at android.os.AsyncTask$3.done(AsyncTask.java:304)
                                                                           at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                           at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                           at java.lang.Thread.run(Thread.java:818)
                                                                        Caused by: java.lang.NoClassDefFoundError: com.facebook.react.packagerconnection.ReconnectingWebSocket
                                                                           at com.facebook.react.packagerconnection.JSPackagerClient.<init>(JSPackagerClient.java:77)
                                                                           at com.facebook.react.devsupport.DevServerHelper$1.doInBackground(DevServerHelper.java:164)
                                                                           at com.facebook.react.devsupport.DevServerHelper$1.doInBackground(DevServerHelper.java:138)
                                                                           at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                           at java.lang.Thread.run(Thread.java:818) 
08-14 10:16:40.770 5613-5671/de.drivelog.connect.poc I/Process: Sending signal. PID: 5613 SIG: 9
08-14 10:16:40.786 1522-1564/system_process W/InputDispatcher: channel 'f5a899a de.drivelog.connect.poc/de.drivelog.connect.poc.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
08-14 10:16:40.786 1522-1564/system_process E/InputDispatcher: channel 'f5a899a de.drivelog.connect.poc/de.drivelog.connect.poc.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
```
