### ISSUE TITLE
低版本编译报错，项目app比较老 之前编译都是没问题的

### ISSUE THREAD

**Issue by githubbaichi520** [facebook/react-native#19267] opened 2018-05-15 12:16 UTC
我们的项目比较老没有更新，之前打包都能正常打包，但是今天编译代码发现编译失败，不知道为什么，我看到build里面使用了最新的库 0.55.3 ，不是项目里面package.json配置的react-native 0.37.0
下面是package.json配置 和 错误信息
{
  "name": "nutreat",
  "version": "2.0.4",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "release-android": "cd android && ./gradlew assembleRelease",
    "install-android": "cd android && ./gradlew installRelease"
  },
  "dependencies": {
    "deep-equal": "^1.0.1",
    "humps": "^2.0.0",
    "leancloud-realtime": "3.3.0",
    "leancloud-realtime-plugin-typed-messages": "^1.0.0",
    "leancloud-storage": "1.5.1",
    "meetui-react-native": "0.0.8",
    "moment": "^2.17.1",
    "react": "15.3.2",
    "react-native": "0.37.0",
    "react-native-actionsheet": "^2.2.0",
    "react-native-audio": "^2.2.0",
    "react-native-button": "^1.7.1",
    "react-native-communications": "^2.1.3",
    "react-native-datepicker": "1.4.2",
    "react-native-dropdownalert": "^2.10.0",
    "react-native-easy-toast": "^1.0.6",
    "react-native-fetch-blob": "0.10.0",
    "react-native-gallery": "0.0.17",
    "react-native-gifted-chat": "0.0.10",
    "react-native-gifted-spinner": "^0.1.0",
    "react-native-image-pan-zoom": "^2.0.1",
    "react-native-image-picker": "0.22.9",
    "react-native-image-zoom-viewer": "^2.0.5",
    "react-native-menu": "0.20.1",
    "react-native-modal-picker": "0.0.16",
    "react-native-navbar": "^1.6.0",
    "react-native-parsed-text": "0.0.16",
    "react-native-permissions": "0.2.5",
    "react-native-photo-browser": "^0.3.1",
    "react-native-picker": "3.0.5",
    "react-native-pull": "^2.0.2 ",
    "react-native-pullrefresh-scrollview": "^1.1.3",
    "react-native-scrollable-tab-view": "^0.6.0",
    "react-native-storage": "0.1.4",
    "react-native-svg": "4.3.1",
    "react-native-swipeout": "^2.1.1",
    "react-native-swiper": "1.5.1",
    "react-native-tab-navigator": "^0.3.3",
    "react-native-umeng-push": "1.0.5",
    "react-native-vector-icons": "^3.0.0",
    "react-native-wechat": "1.8.0",
    "react-navigation": "^1.0.0-beta.11",
    "react-redux": "^4.4.5",
    "redux": "^3.5.2",
    "redux-thunk": "2.1.0",
    "rn-alipay": "0.2.3",
    "shortid": "^2.2.6"
  },
  "devDependencies": {
    "babel-core": "^6.21.0",
    "babel-eslint": "^7.0.0",
    "eslint": "^3.12.2",
    "eslint-config-airbnb": "^13.0.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^2.2.3",
    "eslint-plugin-react": "^6.8.0",
    "eslint-plugin-react-native": "^2.0.0"
  }
}

配置0.37.0 编译使用了 0.55.3
![android1111](https://user-images.githubusercontent.com/26995854/40056016-92832236-587c-11e8-90b9-e4c4e0b7af8a.jpeg)
错误信息
![android2222](https://user-images.githubusercontent.com/26995854/40056052-ab9c6c46-587c-11e8-9c9c-86656a5a7013.jpeg)

**Comment by RWOverdijk** [comment] 2018-05-15 13:32
I don't think anyone here reads Chinese.

Anyway, I have the same issue. Out of nowhere, android is being built with 0.55.3 instead of the version I was using.

**Comment by RWOverdijk** [comment] 2018-05-15 13:44
https://github.com/facebook/react-native/issues/19259

**Comment by hramos** [comment] 2018-05-15 15:33
Duplicate of #19259

**Closed by hramos** 2018-05-15 15:33 UTC
Labels: :clipboard:No Template

**Comment by githubbaichi520** [comment] 2018-05-16 03:10
@hramos @RWOverdijk Thank you very much!My English is not good, or help me solve the problem
