### ISSUE TITLE
[update error]Duplicate module name: TouchHistoryMath

### ISSUE THREAD

**Issue by MervynFang** [facebook/react-native#7384] opened 2016-05-04 13:15 UTC
## I update react-native to 0.24.1 and install the peer dependency react @latest(15.0.2) then run `react-native upgrade` and `react-native run-android`. and get the error as following:

Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: TouchHistoryMath
  Paths: /Users/Mervyn/CodingNet/playwithreactnative/node_modules/react/lib/TouchHistoryMath.js collides with /Users/Mervyn/CodingNet/playwithreactnative/node_modules/react-native/Libraries/vendor/react/browser/eventPlugins/TouchHistoryMath.js

This error is caused by a @providesModule declaration with the same name accross two different files.
Error: @providesModule naming collision:
  Duplicate module name: TouchHistoryMath
  Paths: /Users/Mervyn/CodingNet/playwithreactnative/node_modules/react/lib/TouchHistoryMath.js collides with /Users/Mervyn/CodingNet/playwithreactnative/node_modules/react-native/Libraries/vendor/react/browser/eventPlugins/TouchHistoryMath.js

This error is caused by a @providesModule declaration with the same name accross two different files.
    at HasteMap._updateHasteMap (/Users/Mervyn/CodingNet/playwithreactnative/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:160:15)
    at /Users/Mervyn/CodingNet/playwithreactnative/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:125:25
    at run (/Users/Mervyn/CodingNet/playwithreactnative/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:89:22)
    at /Users/Mervyn/CodingNet/playwithreactnative/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/Users/Mervyn/CodingNet/playwithreactnative/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:18:9)
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)
~
Process terminated. Press <enter> to close the window
## and I solve it by downgrading react version as the tips of react-native's npm warn to 0.14.5.

I want to know the reason. Anybody meets the same situation?

**Comment by radko93** [comment] 2016-05-04 14:05
Probably you had two different React versions installed. So there was a naming collision.

**Comment by calvinf** [comment] 2016-05-04 15:35
@radko93 no, the same module is in both React and React Native and they're conflicting in the packager build.

> &lt;my app&gt;/node_modules/react/lib/TouchHistoryMath.js collides with <my app>/node_modules/react-native/Libraries/vendor/react/browser/eventPlugins/

**Comment by ineffably** [comment] 2016-05-04 23:34
I'm using both react/react-native in our project and I'm hitting this issue too.  
```Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: TouchHistoryMath
  Paths: /Users/cneff/git/gx-reactnative-poc/node_modules/react/lib/TouchHistoryMath.js collides with /Users/cneff/git/gx-reactnative-poc/node_modules/react-native/Libraries/vendor/react/browser/eventPlugins/TouchHistoryMath.js

This error is caused by a @providesModule declaration with the same name accross two different files.
Error: @providesModule naming collision:
  Duplicate module name: TouchHistoryMath
  Paths: /Users/cneff/git/gx-reactnative-poc/node_modules/react/lib/TouchHistoryMath.js collides with /Users/cneff/git/gx-reactnative-poc/node_modules/react-native/Libraries/vendor/react/browser/eventPlugins/TouchHistoryMath.js```

**Comment by grabbou** [comment] 2016-05-05 11:50
As a temporary fix, please refer to this comment: https://github.com/facebook/react-native/issues/7271#issuecomment-215375355

**Comment by Kim-Andersen** [comment] 2016-05-06 19:59
Same issue.

**Comment by mvnnn** [comment] 2016-06-14 06:13
I get same issue

**Comment by Sherlock92** [comment] 2016-06-24 17:21
Same here

**Comment by DominicTobias** [comment] 2016-06-27 14:51
Same with 0.28.0 when trying to do `npm link` for local module development

**Comment by tanpuer** [comment] 2016-08-24 02:08
I also get the same issue @0.31.0. 
This error is caused by a @providesModule declaration with the same name accross two different files.
    at HasteMap._updateHasteMap (/Users/chenwei/Project/eengoo_upgrade_27/eengoo.app.react/node_modules/react-native/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:162:15)
    at /Users/chenwei/Project/eengoo_upgrade_27/eengoo.app.react/node_modules/react-native/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:127:25

don't know how to slove

**Comment by TheIndianRaj** [comment] 2016-10-10 16:55
Any fixes for this one?

**Comment by stief510** [comment] 2016-10-10 21:52
+1

**Comment by mvnnn** [comment] 2016-10-12 09:16
I make new react-native project and i do copy paste all source code and new project working fine.

**Comment by sghiassy** [comment] 2016-10-24 21:12
I was getting errors like 

    Failed to build DependencyGraph: @providesModule naming collision:
    Failed to build DependencyGraph: @providesModule naming collision:
    Duplicate module name: accepts
    Duplicate module name: accepts

I solved it by deleting the folder `.npm_cache` and rerunning `packager` with `--reset-cache`

    rm -rf .npm_cache

**Comment by tianwawawa** [comment] 2017-02-11 08:38
npm start -- --reset-cache

**Comment by ericvicenti** [comment] 2017-03-06 06:36
Sometimes errors like these can be fixed by wiping out node_modules and re-installing everything. Also by getting dependencies up to date.

I'm closing this for now because there are several workarounds for it, but I also think the packager team is working on making this more resilient.

**Closed by ericvicenti** 2017-03-06 06:36 UTC

**Comment by ze25800000** [comment] 2018-06-25 01:35
git clone your code -> npm install -> react-native run-android
