### ISSUE TITLE
DisplayMetricsHolder crashes on Android API Level 16 with Xposed installed

### ISSUE THREAD

**Issue by Alonexx** [facebook/react-native#14769] opened 2017-06-29 03:40 UTC
### Environment

Android 4.1 (API Level 16) with Xposed installed

### Steps to Reproduce

1. Find an Android 4.1 device.
2. Install Xposed.
3. Initialize React-Native

Fatal Exception: java.lang.RuntimeException: Error getting real dimensions for API level < 17
       at com.facebook.react.uimanager.DisplayMetricsHolder.initDisplayMetrics(DisplayMetricsHolder.java:85)
       at com.facebook.react.uimanager.DisplayMetricsHolder.initDisplayMetricsIfNotInitialized(DisplayMetricsHolder.java:51)
       at com.facebook.react.ReactInstanceManager.(ReactInstanceManager.java:317)
       at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:227)
       at com.ss.android.ugc.aweme.rn.MyReactNativeHost.createReactInstanceManager(MyReactNativeHost.java:47)
       at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41)
       at myOnClickListener.onClick
       at android.view.View.performClick(View.java:4349)
       at android.view.View$PerformClick.run(View.java:17893)
       at android.os.Handler.handleCallback(Handler.java:800)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5493)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:849)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NoSuchMethodException: getRawHeight []
       at java.lang.Class.getConstructorOrMethod(Class.java:460)
       at java.lang.Class.getMethod(Class.java:915)
       at com.facebook.react.uimanager.DisplayMetricsHolder.initDisplayMetrics(DisplayMetricsHolder.java:80)
       at com.facebook.react.uimanager.DisplayMetricsHolder.initDisplayMetricsIfNotInitialized(DisplayMetricsHolder.java:51)
       at com.facebook.react.ReactInstanceManager.(ReactInstanceManager.java:317)
       at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:227)
       at com.ss.android.ugc.aweme.rn.MyReactNativeHost.createReactInstanceManager(MyReactNativeHost.java:47)
       at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41)
       at myOnClickListener.onClick
       at android.view.View.performClick(View.java:4349)
       at android.view.View$PerformClick.run(View.java:17893)
       at android.os.Handler.handleCallback(Handler.java:800)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5493)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:849)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by hramos** [comment] 2017-06-29 03:47
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-29 03:47 UTC
