### ISSUE TITLE
occurred error when i execute react-native init xxx 

### ISSUE THREAD

**Issue by jamesduan** [facebook/react-native#15844] opened 2017-09-07 09:47 UTC
```
** BUILD FAILED **


The following commands produced analyzer issues:
	Analyze /Users/duanlingxiao/MyProjects/blank01/node_modules/react-native/ReactCommon/yoga/yoga/YGNodeList.c
	Analyze /Users/duanlingxiao/MyProjects/blank01/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.c
(2 commands with analyzer issues)

The following build commands failed:
	PhaseScriptExecution Install\ Third\ Party /Users/duanlingxiao/MyProjects/blank01/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/double-conversion.build/Script-190EE32F1E6A43DE00A8543A.sh
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/blank01.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/blank01.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

Do you meet this error before? Who can help me !

**Comment by hramos** [comment] 2017-09-07 17:12
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue that meets the requirements set forth in the template. Thanks!

**Closed by hramos** 2017-09-07 17:12 UTC
