### ISSUE TITLE
New React Native project won't build on Xcode 13.

### ISSUE THREAD

**Issue by adrianbartyczak** [facebook/react-native#31733] opened 2021-06-16 18:32 UTC
## Description
Running a new React Native project on Xcode 13 beta throws the following error:

```
ld: warning: Could not find or use auto-linked library 'swift_Concurrency'
ld: warning: Could not find or use auto-linked library 'swiftFileProvider'
Undefined symbols for architecture x86_64:
  "__swift_FORCE_LOAD_$_swiftFileProvider", referenced from:
      __swift_FORCE_LOAD_$_swiftFileProvider_$_YogaKit in libYogaKit.a(YGLayoutExtensions.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftFileProvider_$_YogaKit)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

/Users/admin/testpro/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'Flipper-Glog' from project 'Pods')
/Users/admin/testpro/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.4, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'Flipper-PeerTalk' from project 'Pods')
/Users/admin/testpro/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'YogaKit' from project 'Pods')
/Users/admin/testpro/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'boost-for-react-native' from project 'Pods')
/Users/admin/testpro/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'Flipper-DoubleConversion' from project 'Pods')

2021-06-16 14:18:52.665 xcodebuild[28989:583546] [MT] DVTPlugInManager: Required plug-in compatibility UUID 42E1F17B-27B3-4DE8-92A8-DC76BA4F5921 for DVTCoreGlyphs.framework (com.apple.dt.DVTCoreGlyphs) not present
** BUILD FAILED **

The following build commands failed:
        Ld /Users/admin/Library/Developer/Xcode/DerivedData/testpro-bhjbeszkrctxppesyqiyhzyvzilq/Build/Products/Debug-iphonesimulator/testpro.app/testpro normal (in target 'testpro' from project 'testpro')
```

## React Native version:

```
System:
    OS: macOS 11.4
    CPU: (4) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Memory: 4.20 GB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.3.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.15.1 - /usr/local/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.0/13A5154h - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce

1. Initialize a project with `npx react-native init testproject`.
2. Run the project with `npx react-native run-ios`.

## Expected Results
I expected the application to build.

**Comment by kelset** [comment] 2021-06-18 11:25
👋 Adian, couple of quick questions:

1) are you building against iOS 14 or 15?
2) can you try with 0.65-rc.2 and see if it breaks there too?

Some folks have reported that their project was building fine with Xcode 13

**Comment by leotm** [comment] 2021-06-19 16:03
Same error logs here with XCode 13.0 beta and 0.65-rc.2 referenced above ^

XCode 12.5 builds fine on both 0.64.2 and 0.65.0-rc.2

I'm on macOS Monterey 12.0 Beta too

**Comment by leotm** [comment] 2021-06-20 11:05
Seems related to flipper, disabling it builds successfully for now as a temporary workaround

_Podfile_

```diff
- use_flipper!()
+ # use_flipper!()
```

```sh
pod install
```

_ios/MyApp/AppDelegate.m_

```diff
+ // #ifdef FB_SONARKIT_ENABLED
+ // #import <FlipperKit/FlipperClient.h>
+ // #import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
+ // #import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
+ // #import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
+ // #import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
+ // #import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

+ // static void InitializeFlipper(UIApplication *application) {
+ //   FlipperClient *client = [FlipperClient sharedClient];
+ //   SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
+ //   [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
+ //   [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
+ //   [client addPlugin:[FlipperKitReactPlugin new]];
+ //   [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
+ //   [client start];
+ // }
+ // #endif

...

+ // #ifdef FB_SONARKIT_ENABLED
+ //   InitializeFlipper(application);
+ // #endif
```

**Comment by gazedash** [comment] 2021-06-24 20:28
Can flopper be opt in and not too invasive in project code? Too much problems for nothing.

**Comment by peterkuiper** [comment] 2021-07-15 12:59
@leotm You might want to checkout this comment: https://github.com/zalando/SwiftMonkey/issues/80#issuecomment-604994492

All this does is add `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = YES;` to your build settings.

**Comment by fkgozali** [comment] 2021-08-23 19:55
We believe this fixed it (in main): https://github.com/facebook/react-native/commit/eb938863063f5535735af2be4e706f70647e5b90

cc @sammy-SC

**Comment by sammy-SC** [comment] 2021-09-13 10:32
@alexisbronchart confirmed that https://github.com/facebook/react-native/commit/eb938863063f5535735af2be4e706f70647e5b90 fixes build issue in Xcode 13. I'm closing this.

**Closed by sammy-SC** 2021-09-13 10:32 UTC
Labels: Platform: iOS, Needs: Triage :mag:

**Comment by woohoou** [comment] 2021-09-21 16:05
Same, swift file and bridge header works.

**Comment by debianw** [comment] 2021-09-21 22:55
Same here, just created a new Swift file + Bridging Header and it worked!!. I don't know why Lol

**Comment by nithinyell** [comment] 2021-09-22 13:59
I have updated to `react-native 0.65.0` and able to build in `Xcode 13(13A233)`

**Comment by ksarna** [comment] 2021-09-23 16:41
Bridging Header didn't help in rn 0.63. I had to turn off flipper

**Comment by debianw** [comment] 2021-09-23 17:03
> Bridging Header didn't help in rn 0.63. I had to turn off flipper

Try this for flipper:

```
use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
```

**Comment by EvanBacon** [comment] 2021-09-23 20:29
Someone building a project with `expo run:ios`, that was bootstrapped with React Native community CLI, will encounter the same error, but formatted as:
```
⚠️  ld: Could not find or use auto-linked library 'swift_Concurrency'
⚠️  ld: Could not find or use auto-linked library 'swiftFileProvider'
⚠️  ld: Could not find or use auto-linked library 'swiftDataDetection'
❌  Undefined symbols for architecture x86_64
┌─ Symbol: __swift_FORCE_LOAD_$_swiftDataDetection
└─ Referenced from: __swift_FORCE_LOAD_$_swiftDataDetection_$_YogaKit in libYogaKit.a(YGLayoutExtensions.o)

❌  ld: symbol(s) not found for architecture x86_64

❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

## Solution

Create a bridging header, as described above.

- `xed ios` to open the project
- `⌘+N` - select swift file
- Select "Create Bridging Header"
- Rebuild `expo run:ios` should work as expected.

**Comment by AbdelrahmanTealab** [comment] 2021-09-26 17:16
> Can flopper be opt in and not too invasive in project code? Too much problems for nothing.
> Project was not building on 12.5, removed it and it worked

I completely agree, everytime I make a project I have to go through this hassle with Flipper. 
I dont understand why facebook does this, it's absurd.

**Comment by nriccar** [comment] 2021-09-30 11:15
Anyone with this message error? 

``
39 duplicate symbols for architecture arm64
``

Its getting tricky.. Xcode updates always breaks things 😅

**Comment by nriccar** [comment] 2021-09-30 14:42
If you upgrade RN version and get to change the iOS target version to 11, don't forget to change it from Xcode under Build Settings => iOS Deployment Target.

**Comment by nithinyell** [comment] 2021-09-30 14:45
#32301

**Comment by danidaryaweesh** [comment] 2021-10-01 01:35
Doing the following fixed the issue for me in Xcode without disabling Flipper: 

1. Go to Build Settings --> Search for "Search paths" and then add $(SDKROOT)/usr/lib/swift to "Library search paths"
2. Change "iOS deployment target" in Xcode to 11
3. Remove pods and build again it should work

I'm using RN 0.64.2

**Comment by eliataylor** [comment] 2021-10-01 03:10
> If you upgrade RN version and get to change the iOS target version to 11, don't forget to change it from Xcode under Build Settings => iOS Deployment Target.

what packages are you using and how many broken during the upgrade?

**Comment by nriccar** [comment] 2021-10-01 08:57
> > If you upgrade RN version and get to change the iOS target version to 11, don't forget to change it from Xcode under Build Settings => iOS Deployment Target.
> 
> 
> 
> @nriccar, what packages are you using and how many broken during the upgrade?

Only one, react-native-view-pager. Why?

**Comment by JeffPatricio** [comment] 2021-10-05 22:51
I'm using native react 0.64.0 and it worked for me after commenting out the use_flipper!() line In Podfile.

**Comment by nikola-vujkovic** [comment] 2021-11-13 14:49
Finally fixed this after so many headaches...

Using React Native 0.66 and in Podfile, if in the post_install section you have a line of code calling an "Xcode 12.5 M1 workaround" then you have to comment it out if you're using Xcode 13 or higher (I'm using 13.2 Beta).

Just to note, I'm using macOS Monterey, which doesn't allow Xcode 12.5.1 or other earlier versions. Also, I am using an M1 MacBook Air.

![clipboard_image_2246dcd3a97](https://user-images.githubusercontent.com/85709802/141648111-edd0cb59-9093-45a0-8f87-2c0788f039db.png)

**Comment by Applizone** [comment] 2021-12-01 03:50
I have follow [leotm here](https://github.com/facebook/react-native/issues/31733#issuecomment-864536726) and [gcrozariol here](https://github.com/facebook/react-native/issues/31733#issuecomment-924016466) and [samridhgupta here](https://stackoverflow.com/a/69882460/17290519) and [Saveen here](https://stackoverflow.com/a/65602500/17290519) but I'm still having the error while build. 

I already publish the app last month and turn off mac. And when I open to do some change to code, the error shows up.
These are the less error after I comment flipper. If not, it will show more than this on the Xcode issue navigator
```
Showing Recent Messages
Could not find or use auto-linked library 'swiftSwiftOnoneSupport'
Could not find or use auto-linked library 'swiftObjectiveC'
Could not find or use auto-linked library 'swiftCoreGraphics'
Could not find or use auto-linked library 'swiftCore'
Could not find or use auto-linked library 'swiftDispatch'
Could not find or use auto-linked library 'swiftCoreFoundation'
Could not find or use auto-linked library 'swiftFoundation'
Could not find or use auto-linked library 'swiftDarwin'
Undefined symbol: __swift_FORCE_LOAD_$_swiftCoreFoundation
Undefined symbol: __swift_FORCE_LOAD_$_swiftDispatch
Undefined symbol: __swift_FORCE_LOAD_$_swiftDarwin
Undefined symbol: __swift_FORCE_LOAD_$_swiftObjectiveC
Undefined symbol: __swift_FORCE_LOAD_$_swiftCoreGraphics
Undefined symbol: __swift_FORCE_LOAD_$_swiftFoundation
```

Why is it suddenly happening?

**Comment by mercpls** [comment] 2021-12-02 01:18
> * `⌘+N` - select swift file
> * Select "Create Bridging Header"

Hi Evan, I don't see the 'Create bridging header' option after creating a swift file. I just get a blank swift file in the root dir it looks like.

**Comment by personjerry** [comment] 2021-12-13 21:45
Looks like this will be fixed in 0.67 https://github.com/facebook/react-native/pull/32284/files but for anyone looking for a workaround see my comment on the Flipper thread: https://github.com/facebook/flipper/issues/3150#issuecomment-992936879

**Comment by EvanBacon** [comment] 2021-12-13 21:58
@mercpls Xcode can be buggy, [create a bridging header manually](https://stackoverflow.com/questions/31716413/xcode-not-automatically-creating-bridging-header) or use Expo's new custom managed workflow to fix.

**Comment by Rebsos** [comment] 2022-06-16 23:30
If you recently upgraded nodejs with nvm and got this error. Try this:
https://stackoverflow.com/a/72652877/3585272
