### ISSUE TITLE
yarnpkg run android taking more than 30 minutes starting package....

### ISSUE THREAD

**Issue by dansmog** [facebook/react-native#15350] opened 2017-08-03 02:54 UTC
After installing create-react-native-app and creating a react native app, running yarnpkg run android so as to be able to use with my android mobile connected to my pc, it takes more than 30 minutes starting package and still doesnt finish it, i constantly quit the app.

What can be done.

**Comment by glauberfc** [comment] 2017-08-03 10:41
On my PC too, when I try to run yarnpkg it takes a long time.

**Comment by hramos** [comment] 2017-08-03 14:47
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-08-03 14:47 UTC

**Comment by jdemangeon** [comment] 2017-08-15 14:22
Same issue for me... There's no new issue about that ? I can't collect more information about the error.

**Comment by TEJAPS** [comment] 2018-06-16 04:53
any solution recommended for this in windows10?
