### ISSUE TITLE
ListEmptyComponent not taking full screen with flex 1 in SectionList

### ISSUE THREAD

**Issue by AlexisLeon** [facebook/react-native#17944] opened 2018-02-12 05:11 UTC
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

```
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.9.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: ^16.2.0 => 16.2.0
  react-native: 0.53.0 => 0.53.0
```

### Expected Behavior
`ListEmptyComponent` (my `EmptyComponent`) has style `flex: 1` and should be rendered taking full screen.
If `ListHeaderComponent` or `ListFooterComponent` are defined and styled with `flex: 1`, should render the elements with the same proportion and using the **whole screen**.

![simulator screen shot - iphone 8 plus - 2018-02-11 at 22 55 10](https://user-images.githubusercontent.com/10150214/36084056-f4ffab92-0f7e-11e8-823c-a4fae0ecdeac.png)

### Actual Behavior
`ListEmptyComponent` (my `EmptyComponent`) renders using only the space it needs (to fit).

![simulator screen shot - iphone 8 plus - 2018-02-11 at 22 54 56](https://user-images.githubusercontent.com/10150214/36084057-f52ca9bc-0f7e-11e8-9080-e1dc1eff8624.png)

### Reproducible Demo

```javascript
import React from 'react';
import { SectionList, Text, View, StyleSheet } from 'react-native';

const EmptyComponent = ({ title }) => (
  <View style={styles.emptyContainer}>
    <Text style={styles.emptyText}>{title}</Text>
  </View>
);

const App = () => (
  <View style={styles.app}>
    <SectionList
      keyExtractor
      renderItem={({ item }) => <Text>{item.name}</Text>}
      sections={[]}
      ListEmptyComponent={
        <EmptyComponent title="Nothing here, come back later.." />
      }
    />
  </View>
);

const styles = StyleSheet.create({
  app: {
    flex: 1,
  },
  emptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyText: {
    fontSize: 30,
  },
});
```

**Comment by Barylskyigb** [comment] 2018-02-13 16:28
having same issue on 0.52.2

**Comment by TheDutchCoder** [comment] 2018-02-14 16:53
Same issue on RN 0.53.0

**Comment by ram-vertace** [comment] 2018-03-02 10:18
Same issues on RN 0.53.3

**Comment by smsmdida** [comment] 2018-03-06 01:42
The same issue on RN 0.54

**Comment by kdastan** [comment] 2018-03-12 11:30
Any news ?

**Comment by inferusvv** [comment] 2018-04-04 13:44
The same for me. RN 0.54.4

**Comment by jayesbe** [comment] 2018-04-16 19:41
contentContainerStyle={{ flexGrow: 1 }}

worked better for me.

**Comment by smsmdida** [comment] 2018-04-19 12:28
@inferusvv we can't use flex in conentContainerStyle it will disable the scroll

**Comment by inferusvv** [comment] 2018-04-19 12:31
@smsmdida Hm, you might be right. In my case I have container without scrolling inside

**Comment by hbarylskyi** [comment] 2018-04-19 14:43
Had to use this:

`contentContainerStyle={[ { flexGrow: 1} , items.length ? null : { justifyContent: 'center'} ]}`

**Comment by sagarrabadiya** [comment] 2018-05-25 11:28
same here RN: 0.55.4 the above workaround spoils the entire layout.. 😆

**Comment by lahed** [comment] 2018-05-30 08:03
don't work for me

```
<ScrollView contentContainerStyle={{ flexGrow: 1 }} >
    <View style={{ flex: 1, backgroundColor:'red'}} >
      <Text>asdasdsad</Text>
    </View>
  </ScrollView>
```

**Comment by Iyoss** [comment] 2018-06-27 16:58
@hbarylskyi It doesn't work if your FlatList has a header component.

**Comment by jkdf2** [comment] 2018-09-20 22:47
List should be linked to (and hopefully closed by): PR #18206

**Comment by kientux** [comment] 2018-10-06 05:16
Is this fixed? I'm still facing this bug in 0.57.

**Comment by tobiastornros** [comment] 2018-10-11 12:00
Still an issue with 0.57.1. 
contentContainerStyle with flex or flexGrow will destroy header component or makes items in list not clickable.

**Comment by Faolain** [comment] 2018-11-30 04:31
As mentioned above still a bug in 0.57

**Comment by kcotias** [comment] 2018-11-30 19:10
> ```
> contentContainerStyle={{ flexGrow: 1 }}
> ```
> worked better for me.

Worked like a charm! Thanks a lot!

**Comment by FirdousNath** [comment] 2018-12-19 11:10
I got success with the simple trick as below

```
import { Dimensions } from "react-native";
const SCREEN_HEIGHT = Dimensions.get("window").height;
```
than I declare the empty component

```
_listEmptyComponent = () => {
    return (
      <View
        style={{
          justifyContent: "center",
          alignItems: "center",
          height: SCREEN_HEIGHT , //responsible for 100% height
          backgroundColor: "#ddd"
        }}
      >
        <Text
          style={{
            justifyContent: "center",
            alignItems: "center",
            fontSize: 20
          }}
        >
          No Contracts Found
        </Text>
      </View>
    );
```
And at last Flatlist look like :

 ```
 <FlatList
            extraData={this.props.contracts}
            data={this.props.contracts}
            ListEmptyComponent={this._listEmptyComponent.bind(this)}
            renderItem={({ item }) => (
              <Text>{item.contractName}>
              <Text/>
            )}
            keyExtractor={(item, index) => item.id}
          />
```

**Comment by riadeveloper** [comment] 2019-01-11 16:33
And this is probably the best solution to fix it

**Comment by Salakar** [comment] 2019-04-10 21:03
👋 hey all, this issue has been pretty quiet lately - is this still an issue with the latest version of React Native?

Please let me know if so and I'll re-open.

Thank you.

**Comment by elyalvarado** [comment] 2019-04-11 16:26
Hi @Salakar, I can confirm this is still an issue in 0.59.4.

**Comment by jayan2019** [comment] 2019-04-12 05:45
```javascript contentContainerStyle={{ flexGrow: 1 }}``` Worked on 0.59, but not in 0.59.4

**Comment by Salakar** [comment] 2019-04-13 05:33
@elyalvarado @jayan2019 - thanks for confirming - I've re-opened this issue.

**Comment by elyalvarado** [comment] 2019-04-14 03:25
This should be fixed with the merged PR #24339, as soon as it lands in a release version

**Comment by cpojer** [comment] 2019-04-14 11:51
Fixed on master.

**Closed by cpojer** 2019-04-14 11:51 UTC
Labels: Component: SectionList, Low-Pri, Type: Bug Report

**Comment by supersunkist** [comment] 2019-08-06 08:37
I think it's not workking in 0.60

**Comment by Vijay-mRoads** [comment] 2019-08-12 19:08
It's not working in 0.60.4.

**Comment by Technaur** [comment] 2019-08-26 10:31
I fixed it by wrapping my FlatList in a View with flexGrow: 1 on the View and on the FlatList contentContainerStyle I also set flexGrow: 1 (Working on 0.60.5 for me)

`
    <View style={{ flexGrow: 1 }}>
          <FlatList
            contentContainerStyle={{
              flexGrow: 1
            }}
          />
        </View>
`

Just make sure that any parent views this component is wrapped in are also flex: 1 (I have noticed that this can have an effect on children components flex)

Hope this helps :)

**Comment by jayan2019** [comment] 2019-09-06 09:26
Working on 0.60.5

```
<FlatList 
      contentContainerStyle={{ flex: 1 }}
      renderItem={({item}) => (<View />)}
      ListEmptyComponent={() => (
      <View style={{flex: 1, alignItems: 'center', justifyContent: 'center',}}>
           <Text>No Scheduled Jobs</Text>
      </View>
      )}
/> 
```

**Comment by yishin** [comment] 2019-12-20 07:40
contentContainerStyle={{ height: '100%' }}

**Comment by diegoP08** [comment] 2020-03-14 19:13
contentContainerStyle={{minHeight: '100%'}} works for me

**Comment by ChenhuaWANG22** [comment] 2020-03-24 19:13
on 0.61.5:

1.  below two will work, but it will make items overlapping for list with length >0.
so something like this may help.
contentContainerStyle={items.length ? {} : { flex: 1 } }

@jayan2019
> Working on 0.60.5
> 
> ```
> <FlatList 
>       contentContainerStyle={{ flex: 1 }}
>       renderItem={({item}) => (<View />)}
>       ListEmptyComponent={() => (
>       <View style={{flex: 1, alignItems: 'center', justifyContent: 'center',}}>
>            <Text>No Data Found</Text>
>       </View>
>       )}
> /> 
> ```

@yishin
> contentContainerStyle={{ height: '100%' }}

2. below is working correctly for empty list and list with content.
@diegoP08 
> contentContainerStyle={{minHeight: '100%'}} works for me

3. but, at the end, I am still afraid of this issue will arise again once I upgrade RN.
so, I prefer to wrap FlatList into MyFlatList:
```
    return (
        data.length > 0
            ? <FlatList
                style={styles.flatList}
                renderItem={({ item, index }) => renderItem(item, index)}
                ItemSeparatorComponent={ItemSeparatorComponent}
                data={data}
                keyExtractor={keyExtractor}
            />
            : <View style={styles.textWrap}>
                <Text style={styles.placeholderText}>
                    {placeholder}
                </Text>
            </View>
    )
```

**Comment by fsobh** [comment] 2020-04-02 02:19
> contentContainerStyle={{ height: '100%' }}

Worked like a charm :)
