### ISSUE TITLE
SectionList SectionHeaders jumpy and glitchy in 0.57+

### ISSUE THREAD

**Issue by KevinGulj** [facebook/react-native#21361] opened 2018-09-27 07:18 UTC
## Environment
     React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
      Memory: 2.33 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.9.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.2.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.1 => 16.5.1 
      react-native: 0.57.1 => 0.57.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-macos-cli: 2.0.1

## Description
SectionList scrolling & rendering in longer list cases is very sluggish and glitchy after 0.57+
In 0.55.4 it was smooth even for a lot longer lists. Now in 0.57 and 0.57.1 when the lists are 100+ in length, the section headers start jumping around/disappearing and the list is rubber-banding itself up and down.

## Reproducible Demo
Try to scroll to bottom with the list on the RIGHT side without the headers going crazy (some 500 elements and 5 headers).
LEFT side is 75 elements and is working fine.
https://snack.expo.io/SJ0xLb5Km
EDIT: Seems I can't usually reproduce it with simple list elements.

**Comment by KevinGulj** [comment] 2018-09-27 09:20
I am also using the scrollTo method, which also breaks after a certain length
`
 this.scrollView.scrollToLocation({
      itemIndex,
      sectionIndex,
      animated: true,
      viewPosition: 1,
      viewOffset: -40
    });
`
Please someone look at this video: [https://streamable.com/11zvo](url)
SectionList completely breaks after about 100-ish elements.
After that I cant even properly scroll up or down.

**Comment by Freddy03h** [comment] 2018-09-27 12:04
Experiencing same issue on both iOS and Android

**Comment by hramos** [comment] 2018-09-28 21:10
Duplicate of #20956

**Closed by hramos** 2018-09-28 21:10 UTC
Labels: :large_orange_diamond:Components, :large_orange_diamond:Lists
