### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by anks333** [facebook/react-native#13013] opened 2017-03-18 22:42 UTC
Unfortunately, appName has stopped

When i'm trying to load Image using Image comp, Immediately my app crashes.
I'm using exactly same code as the code given here https://facebook.github.io/react-native/docs/images.html

`03-19 05:16:02.557  1546  1546 D wpa_supplicant: WPS:  * Configuration Error (0)
03-19 05:16:05.077 18286 18356 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lbolts/Task;
03-19 05:16:05.077 18286 18356 E AndroidRuntime:        Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
03-19 05:16:05.113   978   999 I WindowManager: Focus moving from Window{6ea66a2 u0 com.demoapp/com.demoapp.MainActivity} to Window{4fbe5ca u0 Application Error: com.demoapp}
03-19 05:16:05.113   978   999 I WindowManager: Gaining focus: Window{4fbe5ca u0 Application Error: com.demoapp}
03-19 05:16:05.118   329   329 I BufferQueueConsumer: [Application Error: com.demoapp](this:0x7fa5f45400,id:172,api:0,p:-1,c:329) setConsumerName: Application Error: com.demoapp
03-19 05:16:05.118   329   329 I BufferQueueConsumer: [Application Error: com.demoapp](this:0x7fa5f45400,id:172,api:0,p:-1,c:329) setDefaultBufferSize: width=193 height=193
03-19 05:16:05.128   329   329 I BufferQueueConsumer: [Application Error: com.demoapp](this:0x7fa5f45400,id:172,api:0,p:-1,c:329) setDefaultBufferSize: width=1218 height=632
03-19 05:16:05.131   329   528 I BufferQueueProducer: [Application Error: com.demoapp](this:0x7fa5f45400,id:172,api:1,p:978,c:329) connect(P): api=1 producer=(978:system_server) producerControlledByApp=false
03-19 05:16:05.138   329  7320 I BufferQueueProducer: [Application Error: com.demoapp](this:0x7fa5f45400,id:172,api:1,p:978,c:329) new GraphicBuffer needed
03-19 05:16:05.221   329   528 I BufferQueueProducer: [Application Error: com.demoapp](this:0x7fa5f45400,id:172,api:1,p:978,c:329) new GraphicBuffer needed
03-19 05:16:06.069  1546  1546 D wpa_supplicant: WPS:  * Configuration Error (0)
03-19 05:16:06.128   329   528 I BufferQueueProducer: [Application Error: com.demoapp](this:0x7fa5f45400,id:172,api:1,p:978,c:329) new GraphicBuffer needed
03-19 05:16:06.718   329   528 I BufferQueueProducer: [Application Error: com.demoapp](this:0x7fa5f45400,id:172,api:1,p:978,c:329) new GraphicBuffer needed
03-19 05:16:06.726   329  2108 I BufferQueueProducer: [Application Error: com.demoapp](this:0x7fa5f45400,id:172,api:1,p:978,c:329) queueBuffer: fps=1.90 dur=1582.48 max=905.89 min=82.88
03-19 05:16:07.914   329   530 I BufferQueueProducer: [Application Error: com.demoapp](this:0x7fa5f45400,id:172,api:1,p:978,c:329) queueBuffer: fps=15.99 dur=1187.94 max=914.30 min=7.66
03-19 05:16:07.985   329  7320 I BufferQueueProducer: [Application Error: com.demoapp](this:0x7fa5f45400,id:172,api:1,p:-1,c:329) disconnect(P): api 1
03-19 05:16:07.985   329  7320 I BufferQueueConsumer: [Application Error: com.demoapp](this:0x7fa5f45400,id:172,api:1,p:-1,c:329) getReleasedBuffers: returning mask 0xfffffffffffffffd
03-19 05:16:07.989   329  2108 I BufferQueueProducer: [Application Error: com.demoapp](this:0x7fa5f45400,id:172,api:1,p:-1,c:329) disconnect(P): api 1
03-19 05:16:07.994   978   999 I WindowManager: Focus moving from Window{4fbe5ca u0 Application Error: com.demoapp EXITING} to Window{59eb7ed u0 com.sonyericsson.home/com.sonymobile.home.HomeActivity}
03-19 05:16:07.994   978   999 I WindowManager: Losing focus: Window{4fbe5ca u0 Application Error: com.demoapp EXITING}
03-19 05:16:08.121   327   327 E lowmemorykiller: Error writing /proc/18286/oom_score_adj; errno=22
03-19 05:16:08.203   329   329 I BufferQueueConsumer: [Application Error: com.demoapp](this:0x7fa5f45400,id:172,api:1,p:-1,c:-1) disconnect(C)
03-19 05:16:08.204   329   329 I BufferQueue: [Application Error: com.demoapp](this:0x7fa5f45400,id:172,api:1,p:-1,c:-1) ~BufferQueueCore`

 

* React Native version: 0.42.3
* Platform:  Android
* Operating System: Windows
* Dev tools: VS Code

**Comment by hramos** [comment] 2017-03-20 16:33
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-03-20 16:33 UTC
Labels: Android
