### ISSUE TITLE
[Android] com.meizu.widget.OverScrollerExt cannot be cast to android.widget.OverScroller

### ISSUE THREAD

**Issue by alexHlebnikov** [facebook/react-native#9697] opened 2016-09-01 04:58 UTC
Hi, I have a problem with my app on Meizu MX2 (Android 4.4.4).

After my app launches and I'm trying to open menu or do any other action in my app, I've got this error:

![s60901-104703](https://cloud.githubusercontent.com/assets/1951398/18155697/47a35154-703a-11e6-8672-138ac4773acf.jpg)

It's in debug mode, in release mode my app just silently crashes.

I googled a lot and here are the things I have tried: 

- add `android:overScrollMode="never"` to maps.xml:
```
<fragment xmlns:android="http://schemas.android.com/apk/res/android"
    ...
    android:overScrollMode="never"
    ... />
```
*It doesn't helps.*

 - add the following to styles.xml:
```
<resources>
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:overScrollMode">never</item>
        <item name="android:listViewStyle">@style/Widget.AppTheme.ListView</item>
        <item name="android:scrollViewStyle">@style/Widget.AppTheme.ScrollView</item>
    </style>

    <style name="Widget.AppTheme.ListView" parent="android:Widget.ListView">
        <item name="android:overScrollMode">never</item>
    </style>

    <style name="Widget.AppTheme.ScrollView" parent="android:Widget.ScrollView">
        <item name="android:overScrollMode">never</item>
    </style>
</resources>
```

*It doesn't helps.*

Maybe someone can help me.

*There is custom firmware installed by default on Meizu phones - Flyme OS (on MX2 it's Flyme OS 4.2.8.2i).*
I think the problem is connected with it.

I'm using RN 0.33.0.RC.0, MacOS 10.11.6.

**Comment by zhouzefei** [comment] 2016-09-11 02:02
i have the same problem. have you solved?

**Comment by sidgwick** [comment] 2016-09-11 11:26
I have this problem too.

It seems that this error occurs only on Meizu devices, My code run well on simulator.

**Comment by alexHlebnikov** [comment] 2016-09-12 05:36
I still have no solution for this :( 
I think we need sombody from RN developers to solve this problem.

**Comment by wooter-s** [comment] 2016-09-13 13:54
I have the same problem when I upgrade 0.33 from 0.31

**Comment by alexHlebnikov** [comment] 2016-09-13 15:48
It's also on 0.34.RC.0.

**Comment by zackteng** [comment] 2016-09-14 06:44
I have the same problem

**Comment by kyangc** [comment] 2016-09-18 02:22
Same issue.

**Comment by zackteng** [comment] 2016-09-18 02:57
@janicduplessis this problem seems still exist on v0.34.0-rc.0.

**Comment by nihgwu** [comment] 2016-09-18 03:24
It should be irrelevant with the RN, most likely the Flyme OS extends the official ScrollView (for bouncing?) I don't have a device by Meizu to verify though.

**Comment by leeight** [comment] 2016-09-18 05:21
You can contact some Flyme OS developers to investigate this issue: https://github.com/flymeOS.

cc @duanqz

**Comment by zackteng** [comment] 2016-09-18 06:38
@nihgwu but version 0.31 is ok, so i think it could be modify something what  cause this problem

**Comment by nihgwu** [comment] 2016-09-18 07:09
@zackteng then you can compare the branches to locate the commit which result this regression, since witch release

**Comment by leeight** [comment] 2016-09-19 23:06
It was fixed by this commit: https://github.com/facebook/react-native/commit/5deb528695a8a47156a331b2a0182fabef0253d7

**Comment by janicduplessis** [comment] 2016-09-20 00:35
Closing this since it was fixed.

**Closed by janicduplessis** 2016-09-20 00:35 UTC

**Comment by 15185155806** [comment] 2016-10-10 09:07
mark
