### ISSUE TITLE
Why Live reloading cause re-downloading bundle (during 2 minutes) for a simple modification ? (On iOS Device)

### ISSUE THREAD

**Issue by Steffi3rd** [facebook/react-native#24125] opened 2019-03-24 17:42 UTC
## 🐛 Bug Report

Hi, 

I use a real iOS device to test my App.
When I do a modification such as `Hello` to `Hello World`, everything is re-downloading... 
Takes 1-2 minutes

So it's very long to change text...

I don't understand because Live reloading is enable

What's wrong?

## To Reproduce

1 - Run Build on XCode
2 - Download Javascript bundle (2 minutes)
3 - Do a modification with Live Reloading Enabled : `Hello` to `Hello World`
4 - Re-downloading for 2 minutes (instead fast update)

## Expected Behavior
No downloading bundle, or very fast downloading. Because It's a simple modification

## Code Example
None

## Environment

```
 React Native Environment Info:
    System:
      OS: macOS 10.14.1
      CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
      Memory: 1.58 GB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.10.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.0 => 0.59.0 
```

**Comment by kelset** [comment] 2019-05-03 15:37
👋 there.

This is a weird behaviour, it seems be have something to do/being misconfigured on your machine - I can't reproduce it on mine (and our macos config is fairly similar if not identical).

What do you mean with "Download Javascript bundle"? What happens if you use CMR+R to refresh the app? Is it as slow?

**Comment by kelset** [comment] 2019-07-02 15:52
Closing as there as not been any follow up - and that the FB team announced a re-implementation of this feature :)

**Closed by kelset** 2019-07-02 15:52 UTC
Labels: Bug, Platform: iOS, 📦Bundler
