### ISSUE TITLE
hot loading ... not work when ATR.Text's font change 

### ISSUE THREAD

**Issue by jiarWang** [facebook/react-native#15612] opened 2017-08-23 02:55 UTC
(Android5.0 RN0.47)

When change the `params` in `font` like: `fontFamily`, `fontSize`, but the ***hot loading ...*** can't refresh my words'  font in `ART.Text` .
```jsx
<ART.Text
         font = {{
             fontFamily:'sans-serif',
             fontSize:24,
             fontWeight:"normal", 
             fontStyle:"normal" 
                    }}
         x = {60}
         y ={0}
         fill = "#000000"
         alignment = 'center'
         >
          Hello World
   </ART.Text>
```
There also a problem when I change `fontFamily` and ***reload***, but no thing changed.

Another problem is that is there any development-DOC about ART and it's children, eg: `ART.Text`?
Thank U for you help.

**Comment by hramos** [comment] 2017-08-23 19:18
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-08-23 19:18 UTC
