### ISSUE TITLE
React-Native Upgrade Wiped Out Android Folder and Reset Back to Init State

### ISSUE THREAD

**Issue by ACCTFORGH** [facebook/react-native#5659] opened 2016-02-01 09:40 UTC
I was trying to upgrade my RN from 0.15 to 0.19 using the commands from the doc, i.e. 
npm install --save react-native@0.19
react-native upgrade

The nam install step worked fine but the upgrade step wiped out all my code in android folder and overwrite it with the initial code when init the project. I am using Mac OS and mainly develop on Android.

Thanks!

**Comment by ACCTFORGH** [comment] 2016-06-15 09:40
I tried again on RN 0.27 and upgrade still wipes out all the added Java projects and gradle. Did anyone else encounter the same issue?

**Comment by jhabdas** [comment] 2016-09-19 18:46
@christopherdro this isn't an android only issue. The upgrade tool is dumb in the sense it doesn't try and reconcile changes, and will wipe out anything in its path if one is not careful.

**Comment by jhabdas** [comment] 2016-09-19 18:47
I bet there are dozens of issues related to the upgrade process which could all be rolled into one, for that matter.

**Comment by jhabdas** [comment] 2016-09-19 18:48
@ACCTFORGH your best bet IMHO is don't upgrade unless you have to. Mind closing this issue?

**Comment by ACCTFORGH** [comment] 2016-09-19 22:00
@jhabdas I would think it's better to keep this post open because with the speed of RN upgrading, critical bugs do happen (e.g. ProgressBarAndroid in RN0.24 had a race condition that caused crash). Third party plugins change fast and lose support for legacy RN versions as well. Postponing upgrade could be a short term solution but having a upgrade tool that resolves the conflicts would help with the app development a lot.

**Comment by jhabdas** [comment] 2016-09-20 11:52
Makes sense to me. At this point my concern was the 100+ open issues discovered when I searched this repo for "upgrade", as my gut tells me many of them are duplicative or otherwise directly related.

**Comment by pvinis** [comment] 2016-11-09 07:33
same here. on ios, it overwrites the launchscreen.xib.
i found https://github.com/ncuillery/rn-diff this that might help. manual upgrading till the upgrade command works.

**Comment by hramos** [comment] 2017-05-25 20:42
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Closed by hramos** 2017-05-25 20:42 UTC
Labels: Android

**Comment by jhabdas** [comment] 2017-05-25 20:58
@hramos you just swept dirt under the rug my friend

**Comment by jhabdas** [comment] 2017-05-25 20:58
@brentvatne

**Comment by hramos** [comment] 2017-05-25 21:02
We're cutting down on the number of outstanding issues, in order to allow us to focus. I'm closing this issue because it has been open for over six months with no activity. If you think it should still be opened let us know why. PRs are always welcome.

**Comment by jhabdas** [comment] 2017-05-25 21:08
Justification improving, but I've already covered the root cause and described the 100+ related issues (likely much higher now) here: https://github.com/facebook/react-native/issues/5659#issuecomment-248279482

Has the root cause been addressed? If yes, please provide reference for continuity or point to valid issue to address issue.

**Comment by jhabdas** [comment] 2017-05-25 21:19
> I don't see much value in keeping the issue open if there has been no movement since late last year.

There is no I in team.
