### ISSUE TITLE
[0.30] Commits to cherry pick into stable release

### ISSUE THREAD

**Issue by grabbou** [facebook/react-native#8586] opened 2016-07-05 22:46 UTC

**Comment by jmurzy** [comment] 2016-07-13 00:36
#8709 fixes a major bug in NavigationTransitioner.

So the following is for NavigationExperimental:

@3a53228127b3e4c2e7424fd7735e28cf852bf658

/cc @ericvicenti @hedgerwang

🍺

**Comment by ericvicenti** [comment] 2016-07-13 00:48
Thanks for being on top of this @jmurzy!

**Comment by AndrewJack** [comment] 2016-07-14 11:22
Picked commits from 0.29.1 - https://github.com/facebook/react-native/issues/8676

**Comment by grabbou** [comment] 2016-07-17 14:40
https://github.com/facebook/react-native/commit/3c8a2eed92587ef3a79352b71073e4cfccb2a7df

**Comment by nihgwu** [comment] 2016-07-20 02:53
sorry to bother but will #8607 be closed in 0.30 as is broken since 0.29 and new issues about that are increasing

**Comment by grabbou** [comment] 2016-07-20 14:24
If it gets fixed until stable, it will be cherry-picked straight away. Otherwise, we might release patch to both 0.29 and 0.30 for users.

**Comment by nihgwu** [comment] 2016-07-20 15:09
@grabbou It's a regression, turning off `removeClippedSubviews` is just a workaround, I can confirm that it would be fixed by reverting https://github.com/facebook/react-native/commit/1048e5d3445094393298d4e818ff04c41f4e56a7

**Comment by ide** [comment] 2016-07-26 18:31
Closing since 0.30 was released. 0.31 list here: https://github.com/facebook/react-native/issues/9029

**Closed** 2016-07-26 23:12 UTC
Labels: Release
