### ISSUE TITLE
TextInput onContentSizeChange wrong content height

### ISSUE THREAD

**Issue by moonjava2005** [facebook/react-native#15326] opened 2017-08-02 06:13 UTC
TextInput fire onContentSizeChange with wrong content height.
While you typing the text to the half of TextView width (I'm sure that the text still not reach the end of TextInput width by rendering the red background), the onContentSizeChange fire with the new height (of course bigger than the previous height). But the text still not wrap to new line, you can continue typing on the first line.
1. `react-native -v`: 0.47.0

Then, specify:

- Target Platform: iOS 10.3

**Comment by hramos** [comment] 2017-08-02 17:05
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-08-02 17:05 UTC

**Comment by eliperkins** [comment] 2017-08-08 16:59
I'm fairly certain this is a real issue. I'm seeing it crop up after upgrading from 0.46 to 0.47. It looks like 603cc48ceba001827d10231d51b4031c7768eef8 address it, but only in 0.48. What do we think about getting this into 0.47 as well?

**Comment by aksonov** [comment] 2017-08-25 14:33
@hramos Why this issue was closed? I still see this issue, it brakes auto-expanding text input controls...

**Comment by chourobin** [comment] 2017-08-25 15:46
It was merged into 0.47.2

**Comment by hramos** [comment] 2017-08-25 17:04
@aksonov I explained why the issue was closed above.

**Comment by ChristianTucker** [comment] 2017-08-28 09:13
@hramos I've upgraded to 0.47.2 and this is still an issue.

**Comment by aksonov** [comment] 2017-08-28 09:51
@chourobin Thanks! It works well for me

**Comment by chourobin** [comment] 2017-08-28 14:44
@ChristianTucker shooting in the dark here but are you using cocoa pods? (if so, make sure you pod install to update rn)

**Comment by ChristianTucker** [comment] 2017-08-28 21:25
@chourobin Thank you! There's no information on needing to do this in the [Upgrade docs](https://facebook.github.io/react-native/docs/upgrading.html). Sometimes I forgot the native aspect of react-native.
