### ISSUE TITLE
[Touches] Translated components receive touches at their non-translated position

### ISSUE THREAD

**Issue by ide** [facebook/react-native#3557] opened 2015-10-21 01:26 UTC
When translating a View on Android (0.14.0-dev), it continues to receive touches at its original position which is probably not what you want. Here's the repro with PanResponderExample in the UIExplorer (you need to touch the top-left of the scene to move the circle):
```
diff --git a/Examples/UIExplorer/PanResponderExample.js b/Examples/UIExplorer/PanResponderExample.js
index c2e6a66..f469439 100644
--- a/Examples/UIExplorer/PanResponderExample.js
+++ b/Examples/UIExplorer/PanResponderExample.js
@@ -53,8 +53,10 @@ var PanResponderExample = React.createClass({
     this._previousTop = 84;
     this._circleStyles = {
       style: {
-        left: this._previousLeft,
-        top: this._previousTop
+        transform: [
+          { translateY: this._previousTop },
+          { translateX: this._previousLeft },
+        ],
       }
     };
   },
@@ -112,8 +114,10 @@ var PanResponderExample = React.createClass({
     this._highlight();
   },
   _handlePanResponderMove: function(e: Object, gestureState: Object) {
-    this._circleStyles.style.left = this._previousLeft + gestureState.dx;
-    this._circleStyles.style.top = this._previousTop + gestureState.dy;
+    this._circleStyles.style.transform = [
+      { translateY: this._previousTop + gestureState.dy },
+      { translateX: this._previousLeft + gestureState.dx },
+    ];
     this._updatePosition();
   },
   _handlePanResponderEnd: function(e: Object, gestureState: Object) {
```

**Comment by ide** [comment] 2015-10-21 02:22
cc @mkonicek @kmagiera is this simply how Android behaves? I can use absolute positioning instead, but if it's possible for RN to fix this in a nice way, that would be great too.

**Comment by PhilippKrone** [comment] 2015-10-31 21:07
Ah
@ide is this basically the reason for https://github.com/exponentjs/react-native-invertible-scroll-view/issues/16?

**Comment by ide** [comment] 2015-10-31 23:58
Yeah I think so. It might just be Android clowniness but perhaps RN is doing something to disable hitbox translation or can change this behavior on Android.

**Comment by mkonicek** [comment] 2015-11-06 13:31
Interesting, @andreicoman11 do you think it's related to the issue where touch coordinates are absolute instead of relative on Android?

**Comment by satya164** [comment] 2015-11-16 13:57
This regression was introduced in https://github.com/facebook/react-native/commit/c805157cac6acbb74690f209fe7bfd9ea51f8e55

**Comment by mkonicek** [comment] 2015-11-17 16:36
@dmmiller Is now working on making the payload of touch events consistent between iOS and Android.

**Comment by PhilippKrone** [comment] 2015-11-17 16:47
@dmmiller thanks a lot! :)

**Comment by PhilippKrone** [comment] 2015-11-19 06:36
@dmmiller Sorry to ask again, but is there any ETA on this? Or any hotfix I could test?

**Comment by satya164** [comment] 2015-11-23 00:03
@PhilipKrone Currently I've reverted the commit I've linked to and building from source. I needed to use `adjustResize` for the keyboard since reverting the commit re-surfaces the bug where touch points will be wrong if view is moved up due to keyboard focus. Really waiting for the fix.

**Comment by PhilippKrone** [comment] 2015-11-24 19:22
@satya164 OK, I understand. I'm currently checking whether the following PR by @dmmiller  might fix this issue: https://github.com/facebook/react-native/commit/0c2ee5d480e696f8621252c936a8773e8de9f8b6, but it seems not to. :(

**Comment by PhilippKrone** [comment] 2015-11-25 11:17
I've now implemented this fix but the issue is not gone yet.

**Comment by satya164** [comment] 2015-11-25 11:37
@PhilippKrone Which fix?

**Comment by PhilippKrone** [comment] 2015-11-25 11:41
@satya164 Sorry, I guess the message didnt come through: https://github.com/facebook/react-native/commit/0c2ee5d480e696f8621252c936a8773e8de9f8b6

**Comment by dmmiller** [comment] 2015-11-25 16:31
I have a fix internally that I should be pushing in the next day or so.

**Comment by ide** [comment] 2015-11-25 17:30
@dmmiller thanks for the update. Much appreciated I'm sure.

**Comment by dmmiller** [comment] 2015-11-25 17:47
@PhilippKrone @satya164 That fix you mentioned was not a fix for this issue.  That fix fixed the values passed in the touch events to be local to the targeted view.  The fix for this is currently in review and is explicitly for transformed views.

**Comment by satya164** [comment] 2015-11-26 00:49
@dmmiller Looking forward to the fix. Thanks a lot :)

**Comment by satya164** [comment] 2015-11-27 01:49
@dmmiller Would be totally awesome if we could get it to 0.16.0

**Comment by PhilippKrone** [comment] 2015-11-28 09:02
@dmmiller Anything new concerning this fix for transformed views?

**Comment by dmmiller** [comment] 2015-11-30 09:49
Waiting on @andreicoman11 to get back from holiday and accept it :)  He should be back today so hopefully, we can get it pushed today.

**Comment by satya164** [comment] 2015-11-30 10:05
@dmmiller That would be awesome. Thank you :D

**Closed** 2015-11-30 14:12 UTC
Labels: Android
