### ISSUE TITLE
Failed to build DependencyGraph: @providesModule naming collision error

### ISSUE THREAD

**Issue by niocncn** [facebook/react-native#12504] opened 2017-02-21 22:34 UTC
After adding pods to my project: 
Podfile
```
platform :ios, '9.0'
target 'MyApp' do
pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTAnimation',
    'RCTActionSheet',
    'RCTImage',
    'RCTGeolocation',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
    ]
pod 'react-native-vkontakte-login', :path => '../node_modules/react-native-vkontakte-login'
end
```

I got error

```
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: react-native-packager
  Paths: /Users/alex/Repos/MyApp/node_modules/react-native/packager/package.json collides with /Users/alex/Repos/MyApp/ios/Pods/React/packager/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: react-native-packager
  Paths: /Users/alex/Repos/MyApp/node_modules/react-native/packager/package.json collides with /Users/alex/Repos/MyApp/ios/Pods/React/packager/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (/Users/alex/Repos/MyApp/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:158:13)
    at p.getName.then.name (/Users/alex/Repos/MyApp/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:133:31)
~
```

cleaning cache not resolve problem

```
react@15.4.2
react-native@0.41.2
```

**Comment by ericvicenti** [comment] 2017-03-06 06:39
I think this is a dupe of https://github.com/facebook/react-native/issues/4968

**Closed by ericvicenti** 2017-03-06 06:39 UTC

**Comment by AdrianBrown1** [comment] 2017-07-07 16:15
I am having the same issue but looking at #4968 is not helpful...
