### ISSUE TITLE
OBJ is Added to String using dictation in iOS

### ISSUE THREAD

**Issue by gkasireddy202** [facebook/react-native#36497] opened 2023-03-16 12:24 UTC
### Description

Hi,

When I use dictation adding text to TextInput in iOS.
OBJ is added to the text input value.
Please find the attached screenshot.

Thanks,

<img width="346" alt="Screenshot 2023-03-15 at 6 43 07 PM" src="https://user-images.githubusercontent.com/90603484/225615167-50f0cddd-11dc-4e03-bea5-6f47f497924c.png">

**Comment by lunaleaps** [comment] 2023-03-20 18:17
Closing this as its a duplicate of https://github.com/facebook/react-native/issues/36521

**Closed by lunaleaps** 2023-03-20 18:17 UTC
Labels: Needs: Author Feedback, Type: Unsupported Version

**Comment by gkasireddy202** [comment] 2023-05-10 11:25
https://github.com/facebook/react-native/issues/22139

Above #22139 issue is fixed?
