### ISSUE TITLE
Header height not getting calculated in pageY value for components in new architecture

### ISSUE THREAD

**Issue by ManiTWIndia** [facebook/react-native#43500] opened 2024-03-15 04:57 UTC
### Description

When using default header from the stack navigation, facing inconsistency in pageY value of component rendered in old and new architecture. In the example screenshots, I am passing screenOptions={{headerStyle: {height: 150}}} to Stack navigator in React native new architecture and the pageY is being returned without taking the header height into consideration.

The issue happens in iOS new architecture only. In old architecture, the header height is taken into consideration when calculating pY value

### Steps to reproduce

https://github.com/ManiTWIndia/stack-navigation-header-issue

### React Native Version

0.73.6

### Affected Platforms

Runtime - iOS

### Areas

Fabric - The New Renderer

### Output of `npx react-native info`

```text
npx react-native info
info Fetching system and libraries information...
System:
  OS: macOS 14.4
  CPU: (8) arm64 Apple M1 Pro
  Memory: 1.53 GB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.15.1
    path: ~/.nvm/versions/node/v16.15.1/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v16.15.1/bin/yarn
  npm:
    version: 8.11.0
    path: ~/.nvm/versions/node/v16.15.1/bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/manikanda.s/.rvm/rubies/ruby-2.7.6/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11076708
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /opt/homebrew/opt/openjdk@17/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/manikanda.s/.rvm/rubies/ruby-2.7.6/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.6
    wanted: 0.73.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Stacktrace or Logs

```text
NA
```

### Reproducer

https://github.com/ManiTWIndia/stack-navigation-header-issue

### Screenshots and Videos

iOS New architecture
![iOS new architecture](https://github.com/facebook/react-native/assets/104359410/41bbba23-328c-478d-bcca-969a082027d0)

iOS Old architecture
![iOS old architecture](https://github.com/facebook/react-native/assets/104359410/ff413204-b155-4d91-8d17-9c8ca4788bf1)

**Comment by cortinico** [comment] 2024-03-21 09:56
@ManiTWIndia Thanks for reporting this.
I believe the issue here is that you're using react-native-screens under the hood which is affected by this bug:
https://github.com/facebook/react-native/issues/36710

Can you try again on 0.74 + do a patch-package of `react-native-screens`

https://github.com/software-mansion/react-native-screens/pull/2028

and report back if the issue is fixed?

**Comment by ManiTWIndia** [comment] 2024-03-25 12:28
Hi @cortinico I am facing some issues in using patch-package of react-native-screens. There are lot of commits after the last release version. Can we get a beta release of react-native-screens to test it out in local?
Thanks

**Comment by tboba** [comment] 2024-03-25 12:44
Hi @ManiTWIndia, we will be releasing a new version of react-native-screens today (or tomorrow), so I believe beta won't be needed for now! 😄

**Comment by ManiTWIndia** [comment] 2024-03-26 07:22
@tboba @cortinico With and without header, its still showing the same pY value. I have updated and using the latest packages in the project. I have pushed the changes. Can you please check in the repo to reverify the issue?
Thanks

![WithoutHeader](https://github.com/facebook/react-native/assets/104359410/40298a91-6c8e-45ff-be08-9ffadf64255d)
![WithHeader](https://github.com/facebook/react-native/assets/104359410/f7f7fd79-c3de-4bac-939b-43d6c37179f4)


System:
  OS: macOS 14.4
  CPU: (8) arm64 Apple M1 Pro
  Memory: 125.22 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.1
    path: ~/.nvm/versions/node/v20.11.1/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 10.2.4
    path: ~/.nvm/versions/node/v20.11.1/bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/manikanda.s/.rvm/rubies/ruby-2.7.6/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11076708
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /opt/homebrew/opt/openjdk@17/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/manikanda.s/.rvm/rubies/ruby-2.7.6/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.6
    wanted: 0.73.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true

**Comment by tboba** [comment] 2024-03-26 14:49
@ManiTWIndia Yeah, I can reproduce that on your example. However, after changing the navigator from `stack` to `native-stack`, the button has correct target!
<img width="427" alt="image" src="https://github.com/facebook/react-native/assets/23281839/c3034894-183c-4145-8587-22b194ee64e3">

I'm curious why this bug still occurs on JS stack, maybe because it still uses `~3.20.0` as the dev dependency of native-stack?
cc @satya164 Do you know if we somehow need to bump screens version to make this issue fixed? I know that screens are defined as a peer dependency in native-stack, but maybe defining it also as the dev dependency impacts that "contract"?

**Comment by satya164** [comment] 2024-03-26 15:13
> Do you know if we somehow need to bump screens version to make this issue fixed? I know that screens are defined as a peer dependency in stack, but maybe defining it also as the dev dependency impacts that "contract"?

Nope, only the version installed and linked into the project can impact it.

**Comment by cortinico** [comment] 2024-04-11 16:03
@ManiTWIndia are you still able to reproduce on 0.74 with the latest version of react-native-screens? As I believe this is practically fixed

**Comment by WoLewicki** [comment] 2024-04-19 11:47
It didn't work on normal stack probably due to my mistake with `ifs`. It should be fixed with this PR: https://github.com/software-mansion/react-native-screens/pull/2107. Could you check it?

**Comment by cortinico** [comment] 2024-05-28 12:12
Closing as potentially fixed by: 
- https://github.com/software-mansion/react-native-screens/pull/2107

As @ManiTWIndia we haven't heard from you, we assume this is fixed. Please get back to us if this is not fixed.

**Closed by cortinico** 2024-05-28 12:12 UTC
Labels: Issue: Author Provided Repro, Needs: Attention, Type: New Architecture
