### ISSUE TITLE
Flex subviews aren't the same height when superview doesn't have height

### ISSUE THREAD

**Issue by xueduany** [facebook/react-native#6239] opened 2016-03-02 06:39 UTC
No, you mistake my means(https://github.com/facebook/react-native/issues/6229), first I build a project reactmix(https://github.com/xueduany/react-mix) can translate react style H5 code into react-native real code. So the code above you see is just what I mean.
The real react-native code is below

![image](https://cloud.githubusercontent.com/assets/1139866/13460658/f8823080-e0b6-11e5-9282-21fbbfa85535.png)

but the flex style is not working as I expect that
![image](https://cloud.githubusercontent.com/assets/1139866/13452629/9433bb9e-e084-11e5-8a72-410bea8d16cd.png)

the origin issue is that,

I try it on React-Native 0.16, like

                <Div className="content">
                kqwjelqkwjelkqjw
                kqwjelqkwjelkqjw
                kqwjelqkwjelkqjw
                kqwjelqkwjelkqjw
                kqwjelqkwjelkqjw
                kqwjelqkwjelkqjw
                kqwjelqkwjelkqjw
                kqwjelqkwjelkqjw
                kqwjelqkwjelkqjw
                kqwjelqkwjelkqjw
                kqwjelqkwjelkqjw
                kqwjelqkwjelkqjw
                kqwjelqkwjelkqjw
                kqwjelqkwjelkqjw
                kqwjelqkwjelkqjw
                kqwjelqkwjelkqjw
                kqwjelqkwjelkqjw
                </Div>
            </Div>
.good, .bad {
display: flex;
flex-direction: row;
}

.good .title, .bad .title {
flex: 0.5;
font-weight: bold;
font-size: 2rem;
display: flex;
}

.good .content, .bad .content {
flex: 1;
padding-right: 10px;
padding-top: 1px;
font-size:15pt;
}

but two flex item not same height, also not working on vesion 0.21.0-rc

**Comment by xueduany** [comment] 2016-03-02 11:45
sorry i find that the editor remove my source code tag,i must redit this issue description. wait

**Comment by corbt** [comment] 2016-03-02 15:23
This issue looks like a duplicate of https://github.com/facebook/css-layout/issues/127. A fix was merged in https://github.com/facebook/css-layout/issues/145. That fix hasn't been pulled into this repository yet, but will likely be available by the time 0.22 comes out. Sorry for the wait!

**Closed by corbt** 2016-03-02 15:23 UTC
Labels: Contains Potential Question Keywords
