### ISSUE TITLE
useEffect not update the redux value its return null but i make change and save its work. first time app loaded its not work.

### ISSUE THREAD

**Issue by vijay-mca** [facebook/react-native#29817] opened 2020-08-31 08:47 UTC
if i run the app value not update in useEffect please help me

**Comment by dulmandakh** [comment] 2020-09-01 23:52
Please provide more information and reproducible sample code so we can further investigate the issue. Thanks

**Comment by dulmandakh** [comment] 2020-09-05 00:47
Sorry, closing this issue because this issue tracker is intended to track React Native issues, but this issue looks like an issue with your code or implementation.

**Closed by dulmandakh** 2020-09-05 00:47 UTC
Labels: Needs: Author Feedback, Needs: Environment Info
