### ISSUE TITLE
react-native-session-is-not-created-when-imbed-html-and-js-in-webview

### ISSUE THREAD

**Issue by hyochan35** [facebook/react-native#14484] opened 2017-06-13 09:41 UTC
## Reporting Bugs

I have created WebView like below in react-native.

<WebView
    source = { require('./web/index.html') }
    javaScriptEnabled={ true }/>
which works fine. But WebView won't save the cookie and store it.
When I request to rest api that requires session id, It prints out that it is undefined.

When I test this locally in browser, it works fine but not in react-native WebView.

When I use use URI and call remote url, it works fine either.

https://stackoverflow.com/questions/44515828/react-native-session-is-not-created-when-imbed-html-and-js-in-webview

**Comment by hramos** [comment] 2017-06-13 16:43
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-13 16:43 UTC
