### ISSUE TITLE
this.onMainScreen() is not defined

### ISSUE THREAD

**Issue by imWildCat** [facebook/react-native#8822] opened 2016-07-16 01:47 UTC
- [x] Provide a **minimal code snippet** / [rnplay](https://rnplay.org/) example that reproduces the bug.

  As http://facebook.github.io/react-native/docs/backandroid.html goes:
```js
BackAndroid.addEventListener('hardwareBackPress', function() {
     if (!this.onMainScreen()) {
       // Do something
       return true;
     }
     return false;
});
```
- [x] Provide **screenshots** where appropriate
  ![screenshot_2016-07-16-09-44-37](https://cloud.githubusercontent.com/assets/2396817/16892079/0ecced1a-4b3a-11e6-9b93-32976f9c3d99.png)
- [x] What's the **version** of React Native you're using?

  0.29
- [x] Does this occur on iOS, Android or both? 

  Android
- [x] Are you using Mac, Linux or Windows? 

  Mac

**Comment by DanielMSchmidt** [comment] 2016-07-16 05:50
The problem is, that `this` is not defined, where you are executing the `this.onMainScreen()` command. You need to use `.bind` on the outer function, for more details on this topic see [here](https://github.com/getify/You-Dont-Know-JS/blob/master/this%20&%20object%20prototypes/ch1.md). Next time, please ask this kind of questions on StackOverflow.

**Comment by DanielMSchmidt** [comment] 2016-07-16 05:50
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-4** [comment] 2016-07-16 05:51
Hey @imWildCat and thanks for posting this! @DanielMSchmidt tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Closed by facebook-github-bot-4** 2016-07-16 05:51 UTC
Labels: For Stack Overflow, Ran Commands

**Comment by imWildCat** [comment] 2016-07-16 06:39
@DanielMSchmidt But there is no component or module which has 'onMainScreen' method. So what does it mean?

**Comment by nihgwu** [comment] 2016-07-16 07:20
That's not the `bind` stuff but `onMainScreen ` is undefined, perhaps the sample code should be improved to tell that it's just a pseudo one, you have to define your own `onMainScreen` (or even `goBack` method in the example)

**Comment by mateoKaradza** [comment] 2016-07-16 10:47
To check if you are on the mainScreen, just check length of current route:
https://github.com/mateoKaradza/Crystal-Lexicon-App/blob/master/app/components/NavBar.js#L12

However, is there any way to tell this event listener to just do this once? Tried everything, searched for hours but nothing - I event tried using state but it doesn't change fast enough.

**Comment by DanielMSchmidt** [comment] 2016-07-16 10:48
Oh, I see the problem: You took the example from the docs, correct? In the docs they simply show what is possible with the module described. As @nihgwu said, you need to implement your own code there.

**Comment by DanielMSchmidt** [comment] 2016-07-16 10:50
@mateoKaradza Please ask this on StackOverflow, so that others may find the answer later. Github Issues should be used for bugs only
