### ISSUE TITLE
App is crashing on Launch Screen

### ISSUE THREAD

**Issue by hamidhadi** [facebook/react-native#12586] opened 2017-02-25 23:17 UTC
When I'm testing my app on develop mode, everything is ok, but when I'm sending a test flight version of my app to the app store my app is crashing at Launch Screen and I have to open the app from recent list of iPhone. 
I really don't know what is my problem and how can I fix that.

**Comment by anteloe** [comment] 2017-02-27 07:13
Not sure, but I would guess you have to bundle your app. See http://facebook.github.io/react-native/releases/0.19/docs/running-on-device-ios.html

**Comment by ericvicenti** [comment] 2017-02-27 08:18
Yeah, you may want to use some crash reporting system to get the error, but it may be that you haven't packaged it correctly. I'm closing this for now because you haven't provided enough information for anybody to reproduce the issue.

**Closed by ericvicenti** 2017-02-27 08:18 UTC
