### ISSUE TITLE
Two application simultaneously on iOS

### ISSUE THREAD

**Issue by oximer** [facebook/react-native#14351] opened 2017-06-06 22:29 UTC
I'm having trouble when drawing two React Application simultaneously on iOS.
Something when a click on button from application 1, the button from application 2 is also triggered.
It seems to me that both components have the same reactTagId and it is messing the whole thing.

It's not possible to have two application (Rootview) sharing a screen? Something like a big screen shared in two frames, each one with a different application.

I did that on Android, using two ReactInstanceManger and it works.
However, it doesn't work on iOS.

So te bug is: clicking in button 1 from ReactApp one and have button 1 and button 2 triggered.

**Comment by hramos** [comment] 2017-06-07 17:46
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-07 17:46 UTC
