### ISSUE TITLE
Unexpected use of reserved word 'class'.

### ISSUE THREAD

**Issue by clluiz** [facebook/react-native#33009] opened 2022-01-31 21:15 UTC
### Description

I'm trying to run a legacy react native app on my cellphone but I'm getting this strange error. I can't get any details or where on my code this problem exist.

I think it may be on some dependency. I'll put part of my package.json here:
![image](https://user-images.githubusercontent.com/1070968/151873794-bde89ac9-d6ac-44e4-b6e3-fa7a8eb78720.png)

Node version: 12.14.0
NPM: 6.13.4

### Version

0.58.5

### Output of `npx react-native info`

  React Native Environment Info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
      CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
      Memory: 4.02 GB / 15.51 GB
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
      Watchman: 20200726.234435.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 18, 23, 28, 29
        Build Tools: 28.0.3, 29.0.0, 29.0.2, 29.0.3
        System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.5 => 0.58.5 
    npmGlobalPackages:
      react-native-vector-icons: 6.6.0

### Steps to reproduce

1. clone the project
2. npm install
3. npm start
The project builds correctly but it shows de red screen shown at the start of this post.

**Comment by phoebe-lqr** [comment] 2022-03-04 06:33
i have the same issue...

**Comment by clluiz** [comment] 2022-03-04 09:46
@phoebe-lqr as I could not a solution here or in other places I used a "brute force approach". I removed all my dependencies from package.json and add one by one to see where the problem as happening. In my case was some dependencies on build.gradle that was mis configured and libs that were with conflicting versions.

**Comment by clluiz** [comment] 2022-05-11 17:55
I couldn't @frru . As a said, the way I "solved" this problem was to recreate the project from scratch, reinstalling all dependecies.

**Comment by cortinico** [comment] 2022-05-11 22:35
> As a said, the way I "solved" this problem was to recreate the project from scratch, reinstalling all dependecies.

Closing as the issue is solved + it was related to a old RN version

**Closed by cortinico** 2022-05-11 22:35 UTC
Labels: Platform: Linux
