### ISSUE TITLE
 React-native [0.59.x] library connection error

### ISSUE THREAD

**Issue by meftunca** [facebook/react-native#23964] opened 2019-03-15 19:48 UTC
## 🐛 Bug Report
Cannot find the debug folder of the libraries I have linked

## To Reproduce
Rebuilt the links but it didn't work

## Expected Behavior

Running smoothly in version 58.4

## Code Example
 
```sh
yarn run v1.12.3
warning ../../../../package.json: No license field
$ react-native run-android
info JS server already running.
info Building and installing the app on the device (cd android && ./gradlew app:installDebug)...
> Task :react-native-gesture-handler:generateDebugRFile FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-gesture-handler:generateDebugRFile'.
> java.nio.file.NoSuchFileException: /Users/meftunca/Desktop/projects_me/reactNative/ui/node_modules/react-native-gesture-handler/android/build/intermediates/merged_man?fests/debug/../../l?brary_man?fest/debug/AndroidManifest.xml

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BU?LD FAILED in 2s
14 actionable tasks: 1 executed, 13 up-to-date
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: ./gradlew app:installDebug
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
 

## Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: (4) x64 Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
      Memory: 34.98 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.1 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-23 | Google APIs Intel x86 Atom, android-27 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.4 => 16.8.4 
      react-native: 0.59.1 => 0.59.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-debugger-open: 0.3.17
      react-native-git-upgrade: 0.2.7

**Comment by dulmandakh** [comment] 2019-03-19 11:56
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗

**Closed by dulmandakh** 2019-03-19 11:56 UTC
Labels: Follow Up, Platform: Android, Type: Bug Report

**Comment by hsynran** [comment] 2019-03-23 01:44
Hi @dulmandakh 
You can reproduce this issue easily.
React Native 0.59.1 cannot link any library for android. I have tried with react-native-vector-icons library and got the same error.
```
Execution failed for task ':react-native-vector-icons:generateDebugRFile'.
```

**Comment by KevinCallagher** [comment] 2019-05-28 12:35
I've been experiencing same issue for a few days with multiple libraries such as Async Storage and Realm. Finally solved it.

Open android project in Android Studio. Do 'Clean Project' and then 'Rebuild Project'. Now execute 'react-native run-android'. It should not throw 'react-native-gesture-handler:generateDebugRFile FAILED' error anymore..
