### ISSUE TITLE
com.facebook.react.common.JavascriptException: Invalid property.

### ISSUE THREAD

**Issue by itlipan** [facebook/react-native#13917] opened 2017-05-11 12:54 UTC
Recently, we found that users frequently appear this problem, the problem's  crash log as follows：

```
com.facebook.react.common.JavascriptException: Invalid property.  'value' present on property with getter or setter., stack:
o@559:174
c@559:1022
<unknown>@559:1037
n@383:557
i@383:278
t@383:210
global code@890:9

	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:97)
	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:81)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:318)
	at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
	at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
	at android.os.Looper.loop(Looper.java:179)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
	at java.lang.Thread.run(Thread.java:818)


```

The problem  did not appear during the development and QA，And We did not get some useful information in StackOverFlow.

* reactNative version: 0.39

* Crashed Devices : Android 5.0, 5.1,6.0,7.0...

**Comment by hramos** [comment] 2017-05-15 18:57
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-05-15 18:57 UTC

**Comment by Hao3o5** [comment] 2018-03-25 14:45
Also got this error and stuck on it:
_________________________________________________________________________
com.facebook.react.common.JavascriptException: Invalid property.  'value' present on property with getter or setter., stack:
n@7548:32
d@7600:11
<unknown>@7604:10
o@48:12
e@25:10
i@18:46
global code@27098:16

	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:56)
	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:40)
..........................
_________________________________________________________________________
