### ISSUE TITLE
[Debugger] Asynchronous callbacks aren't called until the screen is touched

### ISSUE THREAD

**Issue by aleclarson** [facebook/react-native#5712] opened 2016-02-02 21:23 UTC
Have you guys experienced this before? Or should we get a repro going?

This is only when debugging in Chrome.

**Comment by aleclarson** [comment] 2016-03-12 00:48
I think this behavior is coming from `requestAnimationFrame`. Not 100% sure though.

**Comment by ide** [comment] 2016-03-12 00:49
Is this when you type requestAnimationFrame into the Chrome REPL (expected that this doesn't work -- it runs on a different event loop), or when you have requestAnimationFrame in your app's code?

**Comment by aleclarson** [comment] 2016-03-12 00:51
@ide In my experience, it's when I call a function that sets an `AnimatedValue`. And since that API uses `requestAnimationFrame`, that must be where it's getting hung up.

**Comment by aleclarson** [comment] 2016-03-12 03:46
@ide It's also happening with `onLayout` callbacks. Touching the screen seems to flush the Chrome event loop?

**Comment by ide** [comment] 2016-03-12 04:43
Touching the screen will run the React Native event loop. What's happening, roughly, is that when you execute code from the REPL, you're not inside of the React Native event loop. The native side of the bridge isn't in a call stack that receives commands from JS and processes them.

Last I looked into this about a year ago, there's no easy way to hook into the Chrome REPL (maybe an extension?) so that before each REPL command we could prepare the JS environment for the next iteration of the event loop in JS and then flush the command queue when it's done. So to be safe, don't use the Chrome REPL -- even if tapping the screen ends up flushing elements in the command queue, the JS environment hasn't been prepared for the next run of the event loop when you execute code from the REPL.

**Comment by aleclarson** [comment] 2016-03-12 04:58
> when you execute code from the REPL, you're not inside of the React Native event loop. The native side of the bridge isn't in a call stack that receives commands from JS and processes them.

Does that mean native is "responsible" for any UI jitter while `Debug in Chrome` is enabled? Or are there side effects to the JS thread too?

> Touching the screen will run the React Native event loop

Could we "prevent" the event loop from sleeping when `Debug in Chrome` is enabled?

**Comment by ide** [comment] 2016-03-12 05:27
> Does that mean native is "responsible" for any UI jitter while Debug in Chrome is enabled? Or are there side effects to the JS thread too?

It depends on the type of jitter. For something like Animated, which computes each frame in real time on the JS thread and sends it from JS to native (over the WebSocket connection in the Chrome debugger's case), it's probably due to the JS thread not being able to send frames consistently at 60fps to the native side. The cause of that could be slow JS (ex: a heavy JSON.parse in the middle of an animation) or high latency between JS and native (ex: WebSockets w/Chrome debugger).

> Could we "prevent" the event loop from sleeping when Debug in Chrome is enabled?

Technically, yes. We could have the native event loop always ask JS if its command queue has commands in it. With the Chrome debugger, there's a lot of overhead because native needs to communicate over a WebSocket to talk to JS.

The bigger problem, though, is that even if the native side continuously polls the JS side, executing JS through the REPL still happens outside of the JS part of React Native's event loop. (See next answer.)

> By preparing the JS environment, do you mean "replaying" the actions performed by the REPL on the device JS thread?

Not quite. Look at this code here: https://github.com/facebook/react-native/blob/060664fd3d9331f062696e68179bac9cd4544a06/Libraries/WebSocket/RCTWebSocketExecutor.m#L173

```objc
  [self sendMessage:message waitForReply:^(NSError *socketError, NSDictionary<NSString *, id> *reply) {
    if (socketError) {
      onComplete(nil, socketError);
      return;
    }

    NSString *result = reply[@"result"];  // this is the command queue
    id objcValue = RCTJSONParse(result, NULL);
    onComplete(objcValue, nil);  // process the command queue
  }];
```

Aside from the app's initialization, the only time we initiate JS execution is when there's a native event (ex: a touch, network response, geolocation event, push notification, etc.) -- the point being that *all JS execution is initiated from the native side over the course of an application's lifetime*.

The code snippet above is how native initiates that execution via WebSockets -- it sends a message via a WebSocket to Chrome, telling Chrome to run a piece of JS. This marks the beginning of the JS side of React Native's event loop. At this point in time, the RN core JS may prepare itself to capture setTimeout calls, start profiling markers, and other things you'd want to do at the start of executing a JS command.

After the environment is prepared, the next thing that happens is that your JS is run. It might do setImmediate calls, which the JS environment is prepared to capture.

After your JS finishes running, the JS call stack is back at the RN core JS. This is where it runs enqueued setImmediate calls and cleanup work you'd want to do at the end of the event loop. One other thing it does is take all the native module calls that you may have made from your JS (this is the command queue) and sends them back over the WebSocket.

Finally we're back in native, and process the commands in the queue.

*The problem with the REPL is that you're executing JS outside of the RN core JS that normally prepares the environment and later cleans it up.* What we need is for the REPL to simulate the WebSocket listener on the JS side: prepare the environment, run your code, clean up the environment. But what's happening now is:

1. the REPL runs your code
3.you touch the screen which tells native to send an event to JS, prepare the environment, run the touch event listeners,

**Comment by aleclarson** [comment] 2016-03-12 05:51
> ...or high latency between JS and native (ex: WebSockets w/Chrome debugger).

Would it be possible to reduce latency by going through direct connection (as opposed to wireless)?

> We could have the native event loop always ask JS if its command queue has commands in it.

Should we get a PR going on this? Or is hooking into the Chrome REPL a choke point? 

As for the overhead with Chrome, avoiding wi-fi could make this workable. Or just raising the polling interval.

**Comment by ide** [comment] 2016-03-12 06:29
> Would it be possible to reduce latency by going through direct connection (as opposed to wireless)?

I'm not sure how much of the latency comes from where. You might be able to test this (relatively) easily by setting up tethering over USB.

> Should we get a PR going on this?

I don't think this is a good direction - it doesn't fix the root issue of the REPL executing code out of band, adds complexity to the bridge code, and makes the development environment less like production.

**Comment by geirman** [comment] 2016-04-20 00:24
@ide this makes for an interesting read, but I'm not quite clear what steps (if any) should be taken to close this issue. Can you clarify, or should we consider this "question answered"?

**Comment by ide** [comment] 2016-04-20 02:33
Let's leave this open but I'm not sure how to fix this off the top of my head. Probably need to make a change on Chrome's side, either by submitting a patch to Blink or writing a Chrome extension if that's possible.

**Comment by ylligashi** [comment] 2016-06-28 13:57
Hi guys, I am having the same problem in here when trying some async call and then return the response. It does not show to the view until I press the screen. I am running the emulator on the genymotion. Any idea to this one. Thanks

**Comment by bestander** [comment] 2016-06-30 16:10
related to https://github.com/facebook/react-native/issues/6679

**Comment by mkonicek** [comment] 2016-10-27 22:18
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/debugger-asynchronous-callbacks-arent-called-until-the-screen-is-touched

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Closed by mkonicek** 2016-10-27 22:18 UTC
Labels: Icebox
