### ISSUE TITLE
[Android] Multiple app instances on first run

### ISSUE THREAD

**Issue by zxyah** [facebook/react-native#13029] opened 2017-03-20 12:42 UTC
the same problem: https://github.com/facebook/react-native/issues/12562

i have got the same isuse
and i log Activity's life recycle
the log is:
`
03-20 20:19:05.871 8053-8053/? E/com.nongfenqi.app.android.thrall.MainActivity: ,onCreate:null
03-20 20:19:05.871 8053-8053/? E/com.nongfenqi.app.android.thrall.MainActivity: ,onResume:com.nongfenqi.app.android.thrall.MainActivity@a36c5db
03-20 20:19:29.571 8053-8053/? E/com.nongfenqi.app.android.thrall.MainActivity: ,onPause:com.nongfenqi.app.android.thrall.MainActivity@a36c5db
03-20 20:19:45.151 8053-8053/? E/com.nongfenqi.app.android.thrall.MainActivity: ,onCreate:null
03-20 20:19:45.151 8053-8053/? E/com.nongfenqi.app.android.thrall.MainActivity: ,onResume:com.nongfenqi.app.android.thrall.MainActivity@cb9fdca
03-20 20:21:03.081 8053-8053/? E/com.nongfenqi.app.android.thrall.MainActivity: ,onPause:com.nongfenqi.app.android.thrall.MainActivity@cb9fdca

03-20 20:24:24.621 8936-8936/? E/com.nongfenqi.app.android.thrall.MainActivity: ,onCreate:null
03-20 20:24:24.631 8936-8936/? E/com.nongfenqi.app.android.thrall.MainActivity: ,onResume:com.nongfenqi.app.android.thrall.MainActivity@70d85f4
03-20 20:24:30.361 8936-8936/? E/com.nongfenqi.app.android.thrall.MainActivity: ,onPause:com.nongfenqi.app.android.thrall.MainActivity@70d85f4
03-20 20:24:42.361 8936-8936/? E/com.nongfenqi.app.android.thrall.MainActivity: ,onResume:com.nongfenqi.app.android.thrall.MainActivity@70d85f4
`

scene is:
after i installed the app,runing it, then press home button, open other app, then back to my app
it happend and create two instance

but when i killed my app,open it again ,do the same thing again, it no happen
this happend only at first times!!!

my react-native version is: 0.42.2
my test phone is : samsung galaxy on7(sm-g6100) android version is:6.0.1
and huawei p9(EVA-AL10) android version is: 7.0

**Comment by hramos** [comment] 2017-03-20 16:29
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-03-20 16:29 UTC
