### ISSUE TITLE
You uploaded an APK or Android App Bundle that was signed in debug mode in react-native

### ISSUE THREAD

**Issue by NitinSidhu** [facebook/react-native#27939] opened 2020-02-03 18:18 UTC
having troubles releasing app 
i followed the steps from official  [docs](https://facebook.github.io/react-native/docs/signed-apk-android)
You uploaded an APK or Android App Bundle that was signed in debug mode in react-native

**Comment by hramos** [comment] 2020-02-04 22:49
@NitinSidhu please make sure to follow the issue template when filing an issue. Closing as the issue is incomplete.

**Closed by hramos** 2020-02-04 22:49 UTC
Labels: Needs: Environment Info, Needs: Issue Template, Needs: Triage :mag:
