### ISSUE TITLE
RN 0.59.1 sourcemap error in Android

### ISSUE THREAD

**Issue by xutm** [facebook/react-native#24059] opened 2019-03-20 08:13 UTC
## 🐛 Bug Report
RN 0.59.1 sourcemap error in Android.

In **Scene.js**, add `console.log(======rendersss===)`. 

![image](https://user-images.githubusercontent.com/11706751/54668824-cb1e9700-4b2a-11e9-85d2-7f724f27a96e.png)

But sourcemap is **SaleEvent.js**

![image](https://user-images.githubusercontent.com/11706751/54668611-3f0c6f80-4b2a-11e9-91d0-37340a05cccd.png)

![image](https://user-images.githubusercontent.com/11706751/54668954-1fc21200-4b2b-11e9-9b39-49ba8b625b15.png)

## Environment
react-native: 0.59.1

  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
      Memory: 411.95 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.2.0 - ~/.nvm/versions/node/v10.2.0/bin/node
      Yarn: 1.10.1 - ~/.nvm/versions/node/v10.2.0/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.2.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        API Levels: 25, 26, 27, 28
        Build Tools: 26.0.0, 26.0.2, 27.0.3, 28.0.3
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by cpojer** [comment] 2019-03-20 08:29
Can you provide a repository with a repro? Screenshots won't help us solve this issue. Alternatively, you could also try to send a PR with a fix!

**Comment by OsamaSaleem95** [comment] 2019-03-20 13:29
same problem here

**Comment by yurykorzun** [comment] 2019-03-22 14:14
The bundler is producing a wrong source map on Android in 0.59.1 and 0.59.0. At least it is consistently happening in my React Native project, but works fine on iOS. I tried to disable JS deltas, it doesn't help.

Related issues #23955 #6946

It could be related to JSC upgrade, but because I don't know how source maps are generated and mapped to running javascript on a device, I don't know exactly what is causing it.

**Comment by kelset** [comment] 2019-03-22 18:07
Closing as duplicate of #23955

**Closed by kelset** 2019-03-22 18:07 UTC
Labels: Platform: Android, Type: Bug Report
