### ISSUE TITLE
Object Identification is too difficult using Appium 

### ISSUE THREAD

**Issue by mali5590** [facebook/react-native#17923] opened 2018-02-09 05:43 UTC
Team,
I gonna start app automation using the React Native App, 
Compared to Native app, The React Native app has challenges in object identification,

![image](https://user-images.githubusercontent.com/35725322/36013334-958dabd8-0d89-11e8-8e6e-5ce8126e8444.png)

IF you see the snapshot all the object has same name , Is there any way where we can setup the unique object name in app ,

Kindly provide your input which will help us to start our application testing using appium

**Comment by hey99xx** [comment] 2018-02-09 08:59
Should be closed as not following issue template.

**Comment by hramos** [comment] 2018-02-09 20:41
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue that meets the requirements set forth in the template. Thanks!

**Closed by hramos** 2018-02-09 20:41 UTC
Labels: Failed Commands
