### ISSUE TITLE
[Android] Rotating screens makes app restart to initial scrren

### ISSUE THREAD

**Issue by itswaze** [facebook/react-native#14941] opened 2017-07-11 09:46 UTC
Hi!

I have a modal that shows a swiper with images, and It has landscape support. But on Android, everytime I rotate the screen the app resets to main screen. Although on iOS it works perfectly fine.

Anyone experienced this?

**Comment by hramos** [comment] 2017-07-11 17:17
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-07-11 17:17 UTC
