### ISSUE TITLE
"textAlignVertical" is not a valid style property

### ISSUE THREAD

**Issue by eduvon0220** [facebook/react-native#5503] opened 2016-01-23 22:38 UTC
I am getting an error saying "textAlignVertical" is not a valid style property when attempting to use the 'textAlignVertical' style on a Text element.  I've checked the documentation and it says I should be able to use this style property: https://facebook.github.io/react-native/docs/text.html

**Comment by vjeux** [comment] 2016-01-24 03:13
Looks like textAlignVertical is only supported by Android so far but we don't display that information on the docs yet :(

https://github.com/facebook/react-native/blob/master/Libraries/Text/TextStylePropTypes.js#L52

**Comment by vjeux** [comment] 2016-01-24 03:16
Actually this isn't the issue. The docs are based off of master and not on the latest release.

2 days ago, textAlignVertical was changed from being a prop to being a style. https://github.com/facebook/react-native/commit/f453e14c8f91d00a8205e6bb06094c85281b38be

Cc @mkonicek

**Comment by janicduplessis** [comment] 2016-01-24 07:43
Something like #3459 would be great :)

**Comment by mkonicek** [comment] 2016-01-24 23:48
vjeux is right, what's described on the website will be available in React Native 0.19 on Feb 1.

We'll need a "staging" version of the website based on master, as described in https://github.com/facebook/react-native/issues/3459

**Comment by mkonicek** [comment] 2016-01-24 23:49
Closing as this is caused by #3459.

**Closed by mkonicek** 2016-01-24 23:48 UTC
