### ISSUE TITLE
Modal's onDismiss callback is wrongly implemented in 0.61.0-rc.3

### ISSUE THREAD

**Issue by wddwycc** [facebook/react-native#26473] opened 2019-09-17 08:58 UTC
Issue:

With [This commit](https://github.com/facebook/react-native/commit/bd2b7d6c0366b5f19de56b71cb706a0af4b0be43), `onDismiss` on `Modal` will never be called when dismissed, code below as an example.

```jsx
const App = () => {
  const [visible, setVisible] = useState(true)
  const onClosePress = useCallback(() => setVisible(false), [])
  const onDismiss = useCallback(() => { console.log('dismiss') }, [])
  return (
    <View>
      <TouchableOpacity onPress={onClosePress}>
        <Text>Close</Text>
      </TouchableOpacity>
      <Modal visible={visible} onDismiss={onDismiss} />
    </View>
  )
}
```

This is not the intended behavior of this callback according to [the document](https://facebook.github.io/react-native/docs/modal#ondismiss)

---

React Native version:

System:
    OS: macOS 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 1.32 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.9.0 - /usr/local/bin/node
    npm: 6.2.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  IDEs:
    Xcode: 11.0/11A419c - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.0-rc.3 => 0.61.0-rc.3

**Comment by xiao99xiao** [comment] 2019-09-17 09:05
The commit https://github.com/facebook/react-native/commit/bd2b7d6c0366b5f19de56b71cb706a0af4b0be43 is a disaster. It actually introduced the problem which it claims to solve in its summary.

```
# Problem:
`onDismiss` prop isn't being called once the modal is dismissed, this diff fixes it.
```

**Comment by bartolkaruza** [comment] 2019-09-18 15:05
Fix for this issue is on the way, I'll try to get it cherry-picked in the next RC for 0.61 as well. https://github.com/facebook/react-native/pull/26490
Thanks for reporting this!

**Comment by wddwycc** [comment] 2019-09-19 08:50
This issue has been resolved with https://github.com/facebook/react-native/commit/a5353c0361f330b2b8aebc5de8dc2d006887081b

**Closed** 2019-09-19 09:04 UTC
Labels: Bug, Component: Modal

**Comment by annjawn** [comment] 2020-03-16 02:17
This still seems to be broken as of 0.61.5

**Comment by lidonghua** [comment] 2020-04-01 09:19
The same issue confirmed in 0.62 stable release. It seems the [Fix](https://github.com/facebook/react-native/commit/a5353c0361f330b2b8aebc5de8dc2d006887081b) is not included in the new release.

**Comment by farbexot** [comment] 2020-04-08 20:43
I was sort of hoping, that the onDismiss callback would also fire, if I swipe it away on iOS. It doenst do that for me on 0.62.1

**Comment by xiao99xiao** [comment] 2020-04-09 07:20
@farbexot You should open a new ticket.

**Comment by fedex995** [comment] 2020-04-14 00:05
@farbexot did you open the new ticket? I'm expecting the same fix

**Comment by gadaubac339** [comment] 2020-04-26 15:43
Open Modal.js in folder node_modules/react-native/Libraries/Modal, you can see:
`componentDidMount() {
    if (ModalEventEmitter) {
      this._eventSubscription = ModalEventEmitter.addListener(
        'modalDismissed',
        event => {
          if (event.modalID === this._identifier && this.props.onDismiss) {
            this.props.onDismiss();
          }
        },
      );
    }
  }

  componentWillUnmount() {
    if (this._eventSubscription) {
      this._eventSubscription.remove();
    }
  }
`
The root cause is iOS call "dismiss event" **AFTER** componentWillUnmount is called.
And there is no subscription exists for "onDismiss".
Try modify "componentWillUnmount":

componentWillUnmount() {
    if (Platform.OS === 'ios') {
      //do nothing
    }
    else {
    if (this._eventSubscription) {
      this._eventSubscription.remove();
    }
  }
  }

And remove subscription:
componentDidMount() {
    if (ModalEventEmitter) {
      this._eventSubscription = ModalEventEmitter.addListener(
        'modalDismissed',
        (event) => {
          if (event.modalID === this._identifier && this.props.onDismiss) {
            if (Platform.OS === 'ios') {
              if (this._eventSubscription) {
                this._eventSubscription.remove();
              }
            }
            this.props.onDismiss();
          }
        },
      );
    }
  }
Good luck.
