### ISSUE TITLE
webview reload not working on android

### ISSUE THREAD

**Issue by TisnKu** [facebook/react-native#14938] opened 2017-07-11 02:29 UTC
I try to reload a `WebView` in `componentWillReceiveProps` when `state` changes. It works as expected on IOS but not on Android. Although loading indicator does show up, the web page does not redraw and no http request is sent.

### Environment
1. `react-native 0.35.0`:
2. `node 6.6.0`:
3. `npm 3.10.3`:
4. Target Platform Android
5. Development Operating System : macOS Sierra

**Comment by laurent22** [comment] 2017-07-11 11:32
Not sure if that helps but I couldn't get reload working either, so I've ended up doing this: 

https://github.com/laurent22/joplin/blob/master/ReactNativeClient/lib/components/screens/onedrive-login.js#L64

**Comment by hramos** [comment] 2017-07-11 17:18
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-07-11 17:18 UTC
