### ISSUE TITLE
warning using LayoutAnimation on 0.43.0-rc.1

### ISSUE THREAD

**Issue by francisco-sanchez-molina** [facebook/react-native#12848] opened 2017-03-10 07:47 UTC
### Description
After I upgrade RN to 0.43.0-rc.1 I got this waring:

`You are manually calling a React.PropTypes validation function for the 'duration' prop on 'LayoutAnimation.configureNext'. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details`

### Reproduction

`... 
LayoutAnimation.easeInEaseOut()
...`

### Additional Information

* React Native version: 0.43.0-rc.1
* Platform: iOS
* Operating System: MacOS

**Comment by RichardLindhout** [comment] 2017-03-12 22:04
I have this error also!

**Comment by janicduplessis** [comment] 2017-03-14 03:42
Duplicate of #12458, working on fixing this now.

**Closed by janicduplessis** 2017-03-14 03:42 UTC
