### ISSUE TITLE
more than one library with package name 'com.google.android.gms.license'

### ISSUE THREAD

**Issue by Lifesoftware** [facebook/react-native#18485] opened 2018-03-21 13:10 UTC
issue regarding to firebase plugin.

![issue](https://user-images.githubusercontent.com/14052916/37711615-4860917c-2d37-11e8-94ad-3913f7fc871d.png)

**Comment by radko93** [comment] 2018-03-21 16:32
Duplicate of #18479. Also look at https://github.com/evollu/react-native-fcm/issues/857 if it's `react-native-fcm`.

**Closed by radko93** 2018-03-21 16:32 UTC
Labels: :clipboard:No Template, :large_blue_diamond:Android, :no_entry_sign:Invalid
