### ISSUE TITLE
[Navigator Performance] Memory is not released after scene popped in Navigator 

### ISSUE THREAD

**Issue by chenjun1011** [facebook/react-native#4740] opened 2015-12-12 08:06 UTC
I have a large list rendered in Navigator, but when I popped the scene, memory was not released.

The memory usage in Instruments was like this.

![image](https://cloud.githubusercontent.com/assets/1303018/11760902/c1438cf8-a0e8-11e5-83ed-70379fe81a20.png)

But if I destroy the list  without Navigator,  memory usage would drop quickly as the following picture show:

![image](https://cloud.githubusercontent.com/assets/1303018/11760890/7d4a914a-a0e8-11e5-9214-0c2457234fd7.png)

So anyone please could give me a hint on this problem? Or anyone else has this problem too?

**Comment by noscripter** [comment] 2015-12-12 08:11
+1

**Comment by yuanyan** [comment] 2015-12-12 08:13
Memory is big problem.

**Comment by ippa** [comment] 2015-12-12 09:58
+1, I think I've experienced this as well (android, devmode & debug off) when transitioning between two Navigator scenes (one is a small list) are slow but getting slower and finally grinds to a halt.

**Comment by guangwong** [comment] 2015-12-12 15:42
+1

**Comment by 362228416** [comment] 2015-12-15 03:19
+1

**Comment by dajomu** [comment] 2015-12-15 17:39
+1

**Comment by golorry** [comment] 2015-12-21 11:38
+1, also some variables are not destroyed so it's saved in memory with old data which causes confusion in usage.

**Comment by ACCTFORGH** [comment] 2015-12-21 11:38
+1, also some variables are not destroyed so it's saved in memory with old data which causes confusion in usage.

**Comment by jozn** [comment] 2015-12-21 20:14
+1 Memory usage is big problem for me. I wanted to post slimier problem for android. I have monitored android app memory usage, most of memory seems to be eated by none-java code(dalvik heap),  in adb command report it reports most of memory is used by 'Unknown'. this is probably is javascript VM, (javascriptcore), and some other react-native c++ tools (NDK stuff). i hoe this problem resolve.

**Comment by satya164** [comment] 2015-12-22 23:58
Please consider creating product pains post and upvoting there.

**Comment by cnsnake11** [comment] 2015-12-24 09:43
+1

**Comment by toriumi0118** [comment] 2015-12-30 20:09
I also run into this problem in the debug build.
Although, it may not be happened in the release build for my application, which is not the match memory remain.

**Comment by jozn** [comment] 2015-12-31 04:04
This memory leak is related to #4963

**Comment by cosmith** [comment] 2016-01-14 13:57
+1, please upvote here on Product Pains for more visibility! https://productpains.com/post/react-native/navigator-performance-memory-is-not-released-after-scene-popped-in-navigator/

**Comment by af7** [comment] 2016-01-21 21:08
+1

**Comment by af7** [comment] 2016-01-22 10:34
In our iOS app, memory is increasing even when the app is "idle" (user does nothing and views are setled). 

If I use the `replace` instead of `push` in the Navigator then this does not happen, so it is clearly a `Navigator` issue. Is there a fix for this, as this made us use only the `replace` method which means that we have no `back` functionality.

**Comment by ericvicenti** [comment] 2016-01-24 03:01
@af7 , Navigator does not unmount scenes that are off screen, because you might want to quickly go back and keep internal state like scroll position.

It sounds like we may be talking about 3 issues here:

1. Navigator does not unmount any of the current scenes - known design problem. We have ideas to address this in the RFC of the next navigator: https://github.com/ericvicenti/navigation-rfc/issues/4
2. Increasing memory usage while idle, as experienced by @af7 . We should track this in a separate issue. @hedgerwang, have you seen any memory issues with Navigator while idle?
3. This issue as described by the title: memory is not freed for popped scenes. From what I can tell on this thread, it seems to be Android-only and may be the same thing as #4963

**Comment by kiatweitan** [comment] 2016-05-09 06:31
+1 old variables not re-initialized

**Comment by lacker** [comment] 2016-10-24 20:54
This issue seems like it went a few different ways but overall I think it led into a feature request for better navigation which is in progress so I am going to close this issue.

**Closed by lacker** 2016-10-24 20:54 UTC
Labels: JS, Perf

**Comment by ephemer** [comment] 2016-11-07 16:36
#10789 contains a fix for this for iOS. We aren't running Android yet so that must be a separate issue (possibly with a similar fix though). That said, this bug does exist on iOS, as I realised last week, and as reported by OP @chenjun1011, so I'm assuming others will find it via this issue.

@lacker can you re-open this until the PR gets merged?

**Comment by ericvicenti** [comment] 2016-11-07 17:20
This issue was about Navigator and not NavigatorIOS. 

But regardless, thanks for fixing it! The issue is super clear as you have described it, and your fix makes sense, so I've started merging it.

**Comment by ephemer** [comment] 2016-11-07 17:41
@ericvicenti thanks!

**Comment by otoinsa** [comment] 2017-02-06 09:55
Android still never clears the whole route stack (after 40 views app becomes slow and will eventually crash). Why is this closed?

**Comment by jasongrishkoff** [comment] 2017-02-21 20:00
Also having major issues with memory building up for each view that I go to -- to the point that the app becomes the #1 candidate for garbage collection/memory cleanup when it is backgrounded. This is a problem because it's a streaming music app, and staying alive in the background is essential.

**Comment by ambarc** [comment] 2017-04-13 06:54
our app at rest (login view with 3 sliding images) takes up more mem (120MB) than a reasonably active slack app. agreed this is opaque feedback. RN 0.35. investigating instruments in iOS.
