### ISSUE TITLE
Unable to create react-native app

### ISSUE THREAD

**Issue by tigerbally** [facebook/react-native#15118] opened 2017-07-20 08:34 UTC
Hi,

D:\Bally\ReactNativeApp>node -v v6.11.1
D:\Bally\ReactNativeApp>npm -v 5.3.0
D:\Bally\ReactNativeApp>create-react-native-app AweApp 'create-react-native-app' is not recognized as an internal or external command, operable program or batch file.
D:\Bally\ReactNativeApp>

Everything configured properly but commands not recognized...don`t know why
unable to create react native app by Node Plz provide step by step app creation process...

**Comment by hramos** [comment] 2017-07-20 16:44
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-07-20 16:44 UTC
