### ISSUE TITLE
ViewPagerAndroid Failing in Master Branch

### ISSUE THREAD

**Issue by Vani-gurnani** [facebook/react-native#9151] opened 2016-08-01 22:25 UTC
![image](https://cloud.githubusercontent.com/assets/13322122/17310893/31fbed8a-57fc-11e6-88ad-c6631d3e353b.png)

**Comment by duranmla** [comment] 2016-08-29 18:09
Did you solve this? I got this error after upgrade to RN 0.32 but when I switch back to RN 0.31 there is not issues, what I do not understand is that you got this from 28 days ago, so may not be the React version, instead may be something local.

**Comment by niksinfinite10** [comment] 2016-08-30 08:27
I got this on Upgrade of 0.32

**Comment by caofb** [comment] 2016-09-16 11:34
@orlando not work for me,I got this on Upgrade of 0.33

**Comment by caofb** [comment] 2016-09-16 13:36
work now,need to --resetCache

**Comment by orlando** [comment] 2016-09-16 13:38
@caofb probably that too, packager will not recompile the file if it's in cache. Glad you figure it out

**Comment by kamek-pf** [comment] 2016-09-26 20:23
Stumbled upon this too, is it a bug from Babel ? It doesn't look too good, we should report this somewhere.

**Comment by orlando** [comment] 2016-09-26 21:53
yeah looks like a babel bug, it makes sense that the outputs are not the same given the order of the plugins, but that's not good. Output should be the same always (like order the plugins by name or something before applying them).

I'll open an issue in babel to see how it goes

**Comment by pthrasher** [comment] 2016-10-01 15:10
@orlando The plugins have to be in a specific order because certain babel transforms depend on other transforms having already been run. Therefore, they cannot be run in an arbitrary order.

Perhaps one day we'll have some kind of dependency specification system for these transforms... Or some way of controlling this a bit better.

**Comment by orlando** [comment] 2016-10-01 15:14
@pthrasher yeah that makes sense, do you have any example of a plugin depending on other?

**Comment by fab1an** [comment] 2016-10-04 11:59
@kamek-pf @orlando This is not a bug, but intended behaviour of babel. I linked to a proposal for explicit plugin ordering.

**Comment by orlando** [comment] 2016-10-04 12:17
cool, thanks for the input @fab1an, I learned some things on https://github.com/babel/babel/issues/4488.

Is there anyway to see the order in which plugins are applied? (like babel --debug or something)

**Comment by fab1an** [comment] 2016-10-04 12:33
@orlando I think you can gain some info by running babel with enviroment `DEBUG="*"`. But plugins aren't run in a particular order, they get all merged into a single pass, as far as I know. So basically babel encounters a node and applies all matching plugins to it.

**Comment by orlando** [comment] 2016-10-04 12:36
@fab1an oh ok cool, I'll take a look how this works, Babel is like a really dark black box for me right now. Thanks again for taking the time 🌮

**Comment by lacker** [comment] 2017-02-08 01:51
It seems like this was an upgrade-specific issue for a particular past upgrade, & there is a workaround, so I think this issue is essentially resolved. Please feel free to reopen if there is a RN bug here that continues to exist.

**Closed by lacker** 2017-02-08 01:51 UTC
