### ISSUE TITLE
New ImageBackground

### ISSUE THREAD

**Issue by marlti7** [facebook/react-native#16101] opened 2017-09-26 10:24 UTC
`why you not set borderRadius(or other image props) in props style but in imagestyle?  meanwhile you set width and height in style props`
[https://github.com/facebook/react-native/blob/dc97e3fb4e1a297d18b9361710290468060626fc/Libraries/Image/ImageBackground.js](url)

**Comment by hramos** [comment] 2017-09-27 19:11
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue that meets the requirements set forth in the template. Thanks!

**Closed by hramos** 2017-09-27 19:11 UTC
