### ISSUE TITLE
Failed to parse SourceMap

### ISSUE THREAD

**Issue by someok** [facebook/react-native#7820] opened 2016-05-28 21:34 UTC
Debug at iPhone device.

> React Native: 0.25-0.26

package.json:

```
"babel": {
    "presets": [
      "react-native"
    ]
  },
```

show error at load begin:
> Failed to parse SourceMap: http://192.168.1.xxx:8081/index.ios.map?platform=ios&dev=true&hot=true

The SourceMap has wrong positon after reload:
![2016-05-29 5 36 52](https://cloud.githubusercontent.com/assets/1523082/15630098/986c2064-255f-11e6-8234-6e7bcb70f225.png)

**Comment by charpeni** [comment] 2016-05-29 17:13
```
"babel": {
  "presets": [
    "react-native"
  ],
  "sourceMaps": false
}
```

**Comment by someok** [comment] 2016-05-30 09:08
@charpeni thanks, The parse error is dispeared, but the source's map still wrong, like my picture shown.

**Comment by rops** [comment] 2016-06-02 11:52
+1

**Comment by experimentsin** [comment] 2016-06-02 14:38
After some trial an error, it looked to us like a regression in Chrome. So we went looking and found this recent Chrome defect: 

Failed to parse SourceMap
https://bugs.chromium.org/p/chromium/issues/detail?id=611328

**Comment by charpeni** [comment] 2016-06-04 14:47
@experimentsin Good catch.

I'll close this issue since it's related to Chrome, it's already fixed in Canary, it should be fixed soon into Chrome.

**Comment by charpeni** [comment] 2016-06-04 14:47
@facebook-github-bot close

**Closed** 2016-06-04 14:48 UTC

**Comment by mactive** [comment] 2016-06-23 00:12
@someok  后来解决了? 我也遇到这个问题了, 还没有解决. 貌似跟 你自己定义过 .babelrc 有关.

**Comment by xtdhwl** [comment] 2016-07-07 10:08
我也遇到了这个问题，现在解决了。
2种解决方案：

第一种方案
1:Setting－extensions－React Developer Tools（是否安装）
如果安装了React Developer Tools插件卸载在重启Chrome

第二种方案安装Chromium浏览器重试
