### ISSUE TITLE
apk size got increased to almost 50mb from 20mb 

### ISSUE THREAD

**Issue by 98rahul** [facebook/react-native#36105] opened 2023-02-09 10:27 UTC
### New Version

0.71.1

### Old Version

0.63.4

### Build Target(s)

Android

### Output of `react-native info`

**android/build.gradle** and **android/app/build.gradle** attached [here](https://github.com/facebook/react-native/issues/36070#issuecomment-1422075380)

### Issue and Reproduction Steps

migrate to RN-0.71.1 and create an apk

**Comment by cortinico** [comment] 2023-02-09 11:29
Duplicate of https://github.com/facebook/react-native/issues/32933
Essentially, the APK size increase is coming from Android not shipping compressed native libraries anymore. However the .apk file will be zipped when distributed from the play store.

**Closed by cortinico** 2023-02-09 11:29 UTC
Labels: Needs: Triage :mag:, Type: Upgrade Issue

**Comment by 98rahul** [comment] 2023-02-09 11:46
so, making the .aab file

> Duplicate of #32933 Essentially, the APK size increase is coming from Android not shipping compressed native libraries anymore. However the .apk file will be zipped when distributed from the play store.

@cortinico please confirm this...
so, making the .aab file will also have the same size(almost 50 mb) or will come to 20mb (so called zipped..)??

**Comment by cortinico** [comment] 2023-02-09 11:53
.aab or .apk makes no difference in terms of size as the user will always receive an .apk file

**Comment by 98rahul** [comment] 2023-02-09 17:35
[refer](https://github.com/facebook/react-native/issues/32463#issuecomment-966913614) assign minSdkVersion to 21 (in my project it was [minSdkVersion = 23](https://github.com/facebook/react-native/issues/36070#issuecomment-1422075380))
and app size gets reduced to 21mb 🎉
