### ISSUE TITLE
[iOS] Red Screen with Unhandled Exception: SyntaxError

### ISSUE THREAD

**Issue by sreejithr** [facebook/react-native#11397] opened 2016-12-10 16:30 UTC
I did a `react-native init` and ran it on the simulator using `react-native run-ios`. This red screen appeared with no information other than `Unhandled Exception: SyntaxError`. I haven't changed a line of code anywhere.

I tried what folks at #10891 were saying. **App works in remote debugger mode**. I'm posting this since #10891 is closed.

### Additional Information

* React Native version: `0.39.1`
* Platform: iOS
* Operating System: MacOS

**Comment by cyclops24** [comment] 2016-12-11 07:27
@sreejithr Maybe related to this: https://github.com/facebook/react-native/issues/11389

**Comment by damusnet** [comment] 2016-12-13 15:21
@facebook-github-bot duplicate #11389

**Comment by insraq** [comment] 2016-12-21 05:43
I don't think it's a duplicate of #11389.

I am on React Native 0.39.2 and can still see this error. The error message only prints "Syntax Error" without any other details and only occurs in iOS 8.x, like in #10891

I believe it's either the code or transformers that produce a newer syntax that is not recognised in JSC in iOS 8.

**Comment by damusnet** [comment] 2016-12-21 13:59
Hi @insraq, does this happen on a fresh new project? Does the error go away once you turn debugging on? Can you try and run it on Android? In my experience it sometimes provides a better error.

**Comment by insraq** [comment] 2016-12-22 02:41
On an existing project after I re-install node_modules. I've traced down almost all dependencies and found out it was one of the library that contains faulty code where a Component defines `style` property twice.

Strange thing is it works fine on iOS 10, Remote Debug mode but fails with `SyntaxError` on iOS 8. The red error screen fails to provide any useful debug information. However, after inserting an `NSLog(@"%@", exception)` in this method https://github.com/facebook/react-native/blob/master/React/Executors/RCTJSCErrorHandling.mm#L19 I was able to acquire more information. The actually error message is "SyntaxError: Attempted to redefine property 'style'". Maybe we should take a look at why the error message somehow fails to show up in the error screen.

**Comment by damusnet** [comment] 2016-12-23 12:22
Agreed, this looks different from the other issues.

@facebook-github-bot open

**Comment by damusnet** [comment] 2016-12-23 12:23
@facebook-github-bot reopen

**Comment by SoloRN** [comment] 2017-03-21 05:36
I have the same issue, do you have the way to resolve this issue ?  @insraq

**Comment by glinjy** [comment] 2017-03-21 09:19
@insraq  I meet same issue on **iOS 8.4** but error message is `SyntaxError: Attempted to redefine property 'backgroundColor'`. Then I find out the 'backgroundColor' and delete it,  it works fine. Thanks!

**Comment by hramos** [comment] 2017-07-20 22:27
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/ios-red-screen-with-unhandled-exception-syntaxerror

**Closed by hramos** 2017-07-20 22:27 UTC
Labels: Icebox, iOS, Ran Commands
