### ISSUE TITLE
PanResponder major bug while using react-native ^0.55.4

### ISSUE THREAD

**Issue by lukebrandonfarrell** [facebook/react-native#19952] opened 2018-06-28 14:32 UTC
## Environment
**Environment:**
  OS: macOS High Sierra 10.13.5
  Node: 10.5.0
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

**Packages: (wanted => installed):**
  react: ^16.1.0 => 16.2.0
  react-native: ^0.55.4 => 0.55.4

## Description
Hey folks,

There seems to be an issue in the newer versions of React Native when using multiple PanResponders in one scene. Triggering one PanResponder causes all the other PanResponders to trigger.

<p align="center">
<img src="https://user-images.githubusercontent.com/18139277/42040397-6c7f147c-7ae7-11e8-9746-89cbe102075a.gif" alt="panresponder_bug" width="280px"/>
</p>

This may be the underlying issue with [#19244](https://github.com/facebook/react-native/issues/19244). Who is also having problems with PanResponder in react-native ^0.55.0.

## Steps to Reproduce

You can go here and install this package which will allow you to reproduce the error: https://github.com/lukebrandonfarrell/react-native-images-collage/tree/panresponder_bug

## Expected Behavior

Only one image should move.

**Comment by jakallergis** [comment] 2018-08-02 17:05
I have the same problem! This is related to #20215 #19244 and is really frustrating. the translateY/X workaround is working but it doesn't change drag the parent layout with it so its not for every scenario. This doesn't fix it.

For me it happend after I upgraded to 0.55.0

**Comment by jakallergis** [comment] 2018-10-11 14:21
I can confirm that this is fixed now.
My project deps:
react: 16.5.0
react-native: 0.57.1

**Comment by patrickkempff** [comment] 2019-02-17 15:15
Thanks for reaching out! I'm closing this because this issue seems to be resolved. If the issue still persists in the latest version of React Native, please feel free to file a new issue report. Thank you.

**Closed by patrickkempff** 2019-02-17 15:15 UTC
Labels: API: PanResponder, Type: Bug Report
