### ISSUE TITLE
 bundling failed:Unable to resolve module (rn version 0.46.4)

### ISSUE THREAD

**Issue by craftdong** [facebook/react-native#15364] opened 2017-08-04 03:17 UTC
in react-native version 0.44,the code below runs well

require('./img/tabbar/pfb_tabbar_homepage_selected@2x.png')

but when i update react-native to version 0.46.4, the code runs error.
the error msg shows:

 bundling failed: "Unable to resolve module ./img/tabbar/pfb_tabbar_homepage@2x.png from F:\\code\\react-native\\meituanCopy\\src\\RootScene.js: could not resolve `F:\code\react-native\meituanCopy\src\img\tabbar\pfb_tabbar_homepage@2x.png' as a folder: it did not contain a package, nor an index file"

**Comment by craftdong** [comment] 2017-08-04 03:19
any facebook offical solution for this issue? @hramos

**Comment by leechance** [comment] 2017-08-04 03:34
i miss the same issue. did you resolved it? @craftdong

**Comment by leechance** [comment] 2017-08-04 03:35
i miss the same issue. did you resolved it? @hramos

**Comment by hramos** [comment] 2017-08-04 06:38
Three mentions within seconds of creating the issue is a bit excessive. In any case, there's already an issue open about this in #14980.

**Comment by hramos** [comment] 2017-08-04 06:38
Duplicate of #14980

**Closed by hramos** 2017-08-04 06:38 UTC

**Comment by caipizi** [comment] 2017-09-30 06:43
Image naming cannot be @ symbol

**Comment by kccheung** [comment] 2018-01-30 06:59
Anyone knows how to resolve this problem? I am under react native 0.52.5 and cannot load images with filename containing @ symbol.

**Comment by RiBj1993** [comment] 2018-04-11 14:28
run this in cmd   :
react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res

**Comment by mariraj-mitosis** [comment] 2018-07-12 12:00
But this command  not workin

react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
