### ISSUE TITLE
Elements in KeyboardAvoidingView still covered by keyboard.

### ISSUE THREAD

**Issue by marksbren** [facebook/react-native#13497] opened 2017-04-13 23:13 UTC
### Description

I am trying to add a KeyboardAvoidingView to one page of my application. There is a form at the bottom of the page (using the 'react-native-elements' library). When I open the keyboard, form elements move, but not enough. They keyboard still covers part of the form.

![2017-04-14 06 46 13](https://cloud.githubusercontent.com/assets/229684/25027659/f928a756-20e0-11e7-81c1-e944226aea68.gif)

### Reproduction Steps and Sample Code

My current render function is below. I have also tried removing elements. Even if there is ONLY the FormInput within the KeyboardAvoidingView (I removed the FormValidationMessage and 2 Button tags) the FormInput tag does not move up enough and is still covered by the keyboard.

```
render() {
    return (
      <View style={styles.container}>
      <KeyboardAvoidingView behavior="padding">
        <FormInput
          containerStyle = {styles.formInput}
          ref= 'urlinput'
          textInputRef= 'urltext'
          placeholder= "https://www.url.com/...."
          value={this.state.urlTextInput}
          onChangeText={(data) => this.editText(data)}/>
        <FormValidationMessage>{this.state.errorMsg}</FormValidationMessage>
        <Button
          buttonStyle={[styles.button, styles.btnFullWidth, styles.btnText]}
          icon={{name: 'content-paste',color:colors.btnBlue}}
          title='Paste From Clipboard' 
          backgroundColor={colors.white}
          color={colors.btnBlue}
          onPress={(data) => this.pasteUrl()}
        />
        <Button
          buttonStyle={[styles.button, styles.btnFullWidth]}
          //icon={{name: 'cached'}}
          title='Save' 
          disabled={!this.state.inputValid}
          backgroundColor={colors.btnGreen}
          onPress={(data) => this.saveUrl()}
        />
        <View>
          <Text>This is text</Text>
        </View>
        </KeyboardAvoidingView>
      </View>
     
    )
  }
```

### Solution

I have tried multiple solutions but they have not worked:

1. Removed the Button and FormValidationMessage
2. Wrapped the FormInput in a View
3. Changed the behavior to 'height' and 'position'
4. Added a native Text tag inside the KeyboardAvoidingView

However, the KeyboardAvoidingView still does not move up enough to completely avoid the keyboard.

### Additional Information

* React Native version: 0.42.0
* Platform: iOS
* Development Operating System: MacOS Sierra 10.12.4
* Dev tools: iOS Simulator iPhone 6 iOS 10.3

**Comment by sellmeadog** [comment] 2017-04-15 02:39
Experiencing the same issues.  No permutations of view nesting with KeyboardAvoidingView seem to work with react-native-elements.

**Comment by RyanMitchellWilson** [comment] 2017-05-09 19:59
I'm getting this problem as well

**Comment by RyanMitchellWilson** [comment] 2017-05-11 16:14
I found a fix for this, there is prop call `keyboardVerticalOffset` that you can pass to the KeyboardAvoidingView that will change how much the keyboard moves past the textInput. 
Sample of my code:
```
const keyboardVerticalOffset = Platform.OS === 'ios' ? 40 : 0

return (
  <KeyboardAvoidingView behavior='position' keyboardVerticalOffset={keyboardVerticalOffset}>
    <ListView .../>
  <KeyboardAvoidingView/>
)
```

My listview in this example has a textInput element inside one of the rendered rows and it works perfectly. You can adjust the number of the offset to whatever you'd like that looks best.

Found here [https://github.com/facebook/react-native/blob/master/Libraries/Components/Keyboard/KeyboardAvoidingView.js#L97](https://github.com/facebook/react-native/blob/master/Libraries/Components/Keyboard/KeyboardAvoidingView.js#L97)

**Comment by hramos** [comment] 2017-07-25 22:36
Hi there! This issue is being closed because {:search=>"repo:facebook/react-native is:open is:issue updated:<2017-05-25 -label:\"Good First Task\" -label:\"Help Wanted\" ", :message=>"it has been inactive for a while"}. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Closed by hramos** 2017-07-25 22:36 UTC
Labels: Icebox

**Comment by kodayashi** [comment] 2017-11-19 17:01
Hi there, I'm still seeing this. I have a button at the bottom of a signup form and the iOS keyboard covers the button. It's almost as if this feature only works for TextInputs. I'm using react-native 0.50.3. The workaround above got things working, but it'd be great if this was addressed!

**Comment by hegelstad** [comment] 2018-03-31 13:54
It might be caused by using navigation libraries that are adding their own headers that aren't calculated into the equation.

**Comment by dsimushkin** [comment] 2018-04-22 22:31
https://github.com/react-navigation/react-navigation/issues/721#issuecomment-383417050

**Comment by dsimushkin** [comment] 2018-04-22 22:46
https://github.com/react-navigation/react-navigation/issues/721#issuecomment-383417050

**Comment by hegelstad** [comment] 2018-07-08 19:31
Try this module (https://github.com/APSL/react-native-keyboard-aware-scroll-view).

It has a lot more thought put into it.
