### ISSUE TITLE
Hot Reloading causes crash on iOS

### ISSUE THREAD

**Issue by alleniver** [facebook/react-native#22116] opened 2018-11-04 12:21 UTC
## Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
      Memory: 5.93 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.12.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728 
      react-native: 0.57.4 => 0.57.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-rename: 2.3.1

## Description
under RN 0.57.2-4, when I turn on Hot Reloading, the iPhone emulator crashes whenever I save the file.The same problem occurs when I create a new RN0.57.4 project. I initially suspected that it was an XCode or emulator problem, but it didn't matter with the XCode version and the emulator version; however, Hot Reloading works fine under RN0.57.1.

**Comment by thiszhong** [comment] 2018-11-05 01:35
+1. After 0.57.1 => 0.57.4

**Comment by as27543035** [comment] 2018-11-07 07:28
+1. After 0.57.3 => 0.57.4

**Comment by nighttiger1990** [comment] 2018-11-07 11:45
+1

**Comment by mikeATL** [comment] 2018-11-07 22:37
+1 bump.  I'm having the same issue, do not have the issue in 0.57.2.  Is there a workaround?

**Comment by levani** [comment] 2018-11-11 20:50
I'm fighting with this all day long. Now I'm glad I found this issue :D

**Comment by narciero** [comment] 2018-11-11 20:50
+ 1 - yet another example of where a RN release is cut without testing core + essential features

**Comment by kelset** [comment] 2018-11-13 14:45
Hey everyone, never noticed this post, and for some reason the bot ignored it too.

So, there are still some information missing to understand why this issue is happening; @alleniver you mention

> it didn't matter with the XCode version and the emulator version

what version of XCode have you been able to replicate this with?

Did you see any commit from the transition between 0.57.1 to 0.57.2/3/4 that seem to be related to it?

**Comment by levani** [comment] 2018-11-13 14:54
> what version of XCode have you been able to replicate this with?

This happens to me on xcode 10, (with legacy build system enabled, is that matters).

I created a new project with `react-native init` and could reproduce the issue.

**Comment by dslounge** [comment] 2018-11-13 20:33
I wish I could help figure out this issue, but I'm not sure what's going on. Trying a hot module reload crashes here.
![image](https://user-images.githubusercontent.com/492403/48439124-8d13ff80-e753-11e8-960d-e077a820f567.png)

My info:
```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
      Memory: 65.13 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        API Levels: 19, 21, 23, 24, 25, 26
        Build Tools: 19.1.0, 23.0.1, 23.0.3, 24.0.3, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.3, 27.0.3
        System Images: android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728
      react-native: 0.57.5 => 0.57.5
```

**Comment by Liqiankun** [comment] 2018-11-14 06:06
Same issue after upgrade to `0.57.5`

**Comment by kelset** [comment] 2018-11-14 10:21
Thanks for moving this forward:
* given the comments above, I still believe it's probably easier to understand what was cherry-picked in 0.57.3 (which seems to be the first issue to have this issue) -> https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#0573

* Here's the commit history (on 0.57-stable) that involves the folder @dslounge screenshot -> https://github.com/facebook/react-native/commits/0.57-stable/ReactCommon/jschelpers

* the fact that it works find when the remote debugging is on is also a hint, maybe it's simply something missconfigured? 🤔

**Comment by eoinnorris** [comment] 2018-11-14 12:00
This code is called only when #if Debug is on ( I don't see it on in my version of react which is 0.55).
It happens in the 

 void JSCExecutor::initOnJSVMThread() 

method in JSCExecutor.cpp

#if DEBUG
      installGlobalFunction(m_context, "nativeInjectHMRUpdate", nativeInjectHMRUpdate);
#endif

**Comment by levani** [comment] 2018-11-14 12:31
@kelset 

0.57.4 version is broken, not 0.57.3

**Comment by kelset** [comment] 2018-11-14 13:20
You are right, I'll edit my comment above - sorry I misread ;)

**Comment by alleniver** [comment] 2018-11-15 01:08
@kelset  I have tested all the environments, XCode 9.3, 10.0, 10.1, iOS 9, 10, 10, all have this problem, but after starting the remote debugging, there is no problem, the project created by react-native init is the same, very strange.

**Comment by alleniver** [comment] 2018-11-15 01:14
@kelset quote"the fact that it works find when the remote debugging is on is also a hint, maybe it's simply something missconfigured? thinking".
i have re-created with react-native init,but the problem still exists.

**Comment by dslounge** [comment] 2018-11-16 04:43
I just tried a brand new project using `0.57.3`, and trying HMR crashed the app. I wonder if it's something xcode related. I'm on Xcode: 9.4.1 still

**Comment by kelset** [comment] 2018-11-16 09:15
Uhm, nice catch! Can you, instead of relying on 0.47, try to fix the dep to 

```
  "resolutions": {
    "metro": "0.48.2",
    "metro-babel-register": "0.48.2",
    "metro-core": "0.48.2",
    "metro-memory-fs": "0.48.2"
  }
```

And let me know if it fixes it for you?

**Comment by dslounge** [comment] 2018-11-16 17:41
@kelset setting metro to `0.48.2` did not work :(

**Comment by cesargdm** [comment] 2018-11-19 02:42
Opening with Xcode and running in debug mode, it crashes at 
```
JSStringRef jsStr = JSC_JSValueToStringCopy(context(), m_value, &exn);
```
Error message: `com.facebook.react.JavaScript (9): EXC_BAD_ACCESS (code=1, address=0x171abda48)`

File: Libraries/React.xcodeproj/ReactCommon/jshelpers/Value.cpp/Value::toString()

**Comment by kelset** [comment] 2018-11-20 09:52
Thanks everyone, it seems it's something related to Metro 0.48 - this means that probably we should move this issue to the Metro repo. I wonder if, before that, anyway could try moving to latest Metro (0.49.2) (which requires Jest alpha 24.0.0-alpha.6) and double check that this still happens in that scenario.

**Comment by charpeni** [comment] 2018-11-20 15:47
Thanks, @kelset.

I tried with the following resolutions:

```
 "resolutions": {
    "metro": "0.49.2",
    "metro-babel-register": "0.49.2",
    "metro-core": "0.49.2",
    "metro-memory-fs": "0.49.2",
    "jest": "24.0.0-alpha.6"
  },
```

Unfortunately, it doesn't work. The app won't crash, but the hot reloading does nothing.

**Comment by vovkasm** [comment] 2018-11-20 20:36
RN 0.57.5, metro 0.48.3
It works in debug because of this function (`metro/src/lib/bundle-modules/injectDelta.js`):
```js
function injectDelta(modules) {
  modules.forEach((_ref, i) => {
    var _ref2 = _slicedToArray(_ref, 2);
    let id = _ref2[0],
      code = _ref2[1];
    // TODO(T34661038): This used to support source maps, but I've
    // removed the corresponding code for now since the HmrServer
    // does not generate source maps.

    // In JSC we need to inject from native for sourcemaps to work
    // (Safari doesn't support `sourceMappingURL` nor any variant when
    // evaluating code) but on Chrome we can simply use eval.
    const injectFunction =
      typeof global.nativeInjectHMRUpdate === "function"
        ? global.nativeInjectHMRUpdate
        : eval; // eslint-disable-line no-eval

    injectFunction(code);
  });
}
```
It calls `nativeInjectHMRUpdate` only if it is JSC (i.e. not under debugger, because debugger is Chrome).
Next, it calls `nativeInjectHMRUpdate` with only one argument. But RN blindly expects two args:
```C++
#if DEBUG
static JSValueRef nativeInjectHMRUpdate(
    JSContextRef ctx,
    JSObjectRef function,
    JSObjectRef thisObject,
    size_t argumentCount,
    const JSValueRef arguments[],
    JSValueRef* exception) {
  String execJSString = Value(ctx, arguments[0]).toString();
  String jsURL = Value(ctx, arguments[1]).toString();
  evaluateScript(ctx, execJSString, jsURL);
  return Value::makeUndefined(ctx);
}
#endif
```
This leads to crash.

This works for me (but I don't know how correctly will be source info for loaded scripts without source URL):
```C++
#if DEBUG
static JSValueRef nativeInjectHMRUpdate(
    JSContextRef ctx,
    JSObjectRef function,
    JSObjectRef thisObject,
    size_t argumentCount,
    const JSValueRef arguments[],
    JSValueRef* exception) {
  String execJSString = Value(ctx, arguments[0]).toString();
  String jsURL = argumentCount > 1 ? Value(ctx, arguments[1]).toString() : String();
  evaluateScript(ctx, execJSString, jsURL);
  return Value::makeUndefined(ctx);
}
#endif
```

**Comment by vovkasm** [comment] 2018-11-21 05:58
Some analysis:
- metro was broken in commit: [Update the HMR logic to the new IncrementalBundler](https://github.com/facebook/metro/commit/422e46e5f3bdd68cae2c29d6532672ce6b2f3be8#diff-aac659b3bda87811c6c06220ba04081bR28)
- before this commit, working code was: [Update the HMR logic to the new IncrementalBundler working part](https://github.com/facebook/metro/commit/422e46e5f3bdd68cae2c29d6532672ce6b2f3be8#diff-b8e2212de7ffdcb3d043223b5321e757L63)
- metro was fixed in this commit (after 0.48.3): [Source map support for HMR](https://github.com/facebook/metro/commit/5413dcd5b11f3701967107075863330c91c89a99#diff-d5c78d337ba3b55566ec0ac3724afa21R28)

**Comment by vovkasm** [comment] 2018-11-21 06:29
Workaround (not fully tested, but fix HMR for me):
Update to metro 0.49.2
Add this to dependencies in `package.json`:
```json
"devDependencies": {
  ...
  "metro": "0.49.2",
  "metro-react-native-babel-preset": "0.49.2",
  ...
}
```
then `npm install`

PS. I'm getting one warning in app after this: `unknown call: "relay:check"`, it seems react-devtools-core should also be updated...

**Comment by kelset** [comment] 2018-11-21 08:58
Thanks everyone for the feedback - it seems indeed that in newer Metro the issue is fixed (thanks @vovkasm for the investigation 😊).

Btw does the warning you see disappear if you set Jest to be `"jest": "24.0.0-alpha.6"`?

I'd really prefer not to force this newer version in 0.57.6 since it requires the Jest alpha, but if it's the 'best way' to fix this issue I may have to, or at least to ask. (since it seems that Jest 24 is still [a bit far out](https://github.com/facebook/jest/milestone/8))

**Comment by vovkasm** [comment] 2018-11-21 09:03
@kelset 
> Btw does the warning you see disappear if you set Jest to be "jest": "24.0.0-alpha.6"?

Warning I seen, dissapeared after `npm install -g react-devtools` and run new react-devtools :-)
I'm not update jest, only metro & metro-react-native-babel-preset.

**Comment by kelset** [comment] 2018-11-21 09:08
🤦‍♂️ I'm dumb - sorry I misunderstood the PS section. I'll look if I find any commits in master that are related to devtool.

**Comment by kelset** [comment] 2018-11-21 09:36
Ah nice catch, I actually found one which is strictly related to ReactDevTools -> [Fix React Native AsyncMode and DevTools](https://github.com/facebook/react-native/commit/aacb06c594dcd4581918035f713a69cf73bf125b)

**Comment by kk412027247** [comment] 2018-11-23 02:50
After turning on the **Debug JS Remotely**, there is no more crash.

"react-native": "0.57.5"

**Comment by sryze** [comment] 2018-11-24 02:30
Still crashes in 0.57.5

**Comment by vovkasm** [comment] 2018-11-24 06:56
@kelset Updating metro to 0.49.2 will broke remote debug in chrome:

![Exception in remote debugger](http://vovkasm.skitch.vovkasm.org/rn-debug_21A92B34.png)

I think this exception can be easily fixed but the process of this will be long: it needs to be fixed, then new version of metro should be rolled, than it should be moved to RN... too long.

So I returned to my original solution described here https://github.com/facebook/react-native/issues/22116#issuecomment-440420713

This changes native code so that it will not crash. So question. Will you plan a new patch release of RN 0.57 if I send PR against `0.57-stable` branch (can such PR be accepted? because I can't patch `master` - this code not exists anymore in master)

**Comment by alleniver** [comment] 2018-11-25 11:48
@vovkasm  nice job!

**Comment by alleniver** [comment] 2018-11-25 11:50
thanks all.

**Comment by kelset** [comment] 2018-11-26 09:22
Hey @vovkasm thanks for the update!

> (can such PR be accepted? because I can't patch master - this code not exists anymore in master)

Yes I can accept & merge PRs towards the branch, I was just wondering if we can find the commit that removes the code that you modified before - because maybe there is a better solution to this hidden in the commits and it's easier to just cherry pick that ;)

Also it makes me wonder if this fix will work with both Metro 48 and 49.

**Comment by vovkasm** [comment] 2018-11-26 09:53
@kelset 
> Also it makes me wonder if this fix will work with both Metro 48 and 49.
Yet. My fix totally backward and forward compatible. It simple fix crash if JS call function `nativeInjectHMRUpdate` with one argument. If JS will call `nativeInjectHMRUpdate` with two arguments it will behave as before and count source of code (the second argument).

> if we can find the commit that removes the code that you modified before
I was tried to search `nativeInjectHMRUpdate` in new jsi code from master, but found nothing. I don't know why. May be because `eval` (https://github.com/facebook/metro/blob/v0.49.2/packages/metro/src/lib/bundle-modules/injectUpdate.js#L19) supposed to work with new jsi may be it simple wasn't implemented... (
Anyway commit that removed `nativeInjectHMRUpdate` is this: https://github.com/facebook/react-native/commit/7ffb406517e70a2ac299d20020d3798a5b7dc612

**Comment by kelset** [comment] 2018-11-26 10:42
Ah awesome! Then yeah I think that we can proceed without too many problems with a PR to the branch. I was planning to release 0.57.6 today, but it can wait if you think you can create the PR in the next few days

**Comment by vovkasm** [comment] 2018-11-26 10:58
Done #22412

**Comment by otaro808** [comment] 2018-11-27 03:56
+1 after 0.57.0 => 0.57.5

**Comment by vovkasm** [comment] 2018-11-27 05:39
Should be fixed in 0.57.6

**Closed** 2018-11-28 09:05 UTC
Labels: ⚠️Regression, 📦Bundler, 🔧Tooling, 🔷iOS

**Comment by sryze** [comment] 2018-11-29 23:48
Did this patch actually fix hot reloading? I think it's not working properly in 0.57.6, although doesn't crash anymore. In my case there is a "Hot Reloading..." notification shown but the screen is not reloaded.

**Comment by vovkasm** [comment] 2018-11-30 05:07
@sryze Yes, it actually fix hot reloading. I checked HMR enabled with remote debugger and without. It actually work. Can you check with empty project after `react-native init`?

**Comment by xanderberkein** [comment] 2018-11-30 10:20
Can confirm, hot reloading broke again in 0.57.7

**Comment by charpeni** [comment] 2018-12-03 14:21
This may be not directly related to this issue, but I can confirm that HMR could be broken as stated in my previous comment: https://github.com/facebook/react-native/issues/22116#issuecomment-440320895.

I have updated an existing RN app to 0.57.7, the crash issue has been solved. Unfortunately, now I can only see the HMR banner pop in and out without actually making any visible changes.

On a freshly created RN 0.57.7 project, I do not have any issue, only on an updated one.

I do not have any reproducible steps, I'm trying to reproduce it in a sample repo.

**Comment by Titozzz** [comment] 2018-12-03 14:38
I updated to 0.57.7 and had no issue 🤔 , should I reopen this or maybe we need to create another issue ?

**Comment by kelset** [comment] 2018-12-03 14:41
I feel that it would be best to open a new issue if we can get to a stage where there is a repro.

**Comment by xanderberkein** [comment] 2018-12-04 12:14
Seemed to be an issue with outdated dependencies indeed!

Since I didn't feel safe deleting my `yarn.lock` file on a production app, I ran `yarn upgrade` on all my babel packages, which resolved the hot reload issue.

**Comment by sryze** [comment] 2018-12-05 12:08
Do you know which dependencies exactly caused this? It seems strange to me if core features of react-native break because of some third-party dependencies being "outdated", I thought that's what version numbers are for in package.json

**Comment by servocoder** [comment] 2018-12-05 20:46
@charpeni I went through all the steps, but still get `unknown call: "relay:check"` with the following crash on reload, unfortunately. My environment: https://github.com/facebook/react-native/issues/22349#issuecomment-443846352
