### ISSUE TITLE
NavigatorIOS: navigator.push causes images to flicker

### ISSUE THREAD

**Issue by blairvanderhoof** [facebook/react-native#3187] opened 2015-10-02 04:40 UTC
* Create an app with NavigatorIOS
* Create a ListView that renders a vertical list of images urls (not local images)
* use this.props.navigator.push to cause a new view to slide in from the right
* See the images on the current view flicker once

**Comment by oblador** [comment] 2015-10-02 20:29
Probably a dupe of https://github.com/facebook/react-native/issues/2490

**Comment by christopherdro** [comment] 2015-11-07 11:54
@blairvanderhoof Are you still having issues with this?

Looks like it might of been resolved from this commit. 
https://github.com/facebook/react-native/commit/a4ef7abebb01a3f968aae41c84d878b3bc93e025

**Comment by mkonicek** [comment] 2016-04-10 16:38
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/navigatorios-navigatorpush-causes-images-to-flicker

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Closed by mkonicek** 2016-04-10 16:38 UTC
Labels: Icebox
