### ISSUE TITLE
[Android] - WebView with embed video not working inside <View> <Navigator> or  <DrawerLayoutAndroid>

### ISSUE THREAD

**Issue by lneves12** [facebook/react-native#7226] opened 2016-04-26 04:51 UTC
I am trying to use the WebView component to have an external embed video.

When I have the WebView alone it works as expected:

`<WebView style={styles.container} javaScriptEnabled={true} source={{uri: `https://player.vimeo.com/video/159542449title=0&byline=0&badge=0&portrait=0&autoplay=1`}}/>`

If i use it inside a View it shows a white screen. Example: https://rnplay.org/apps/ZER6Lg

Using inside `<Navigator> or  <DrawerLayoutAndroid>` I am getting an black screen.

RN Version: Tried with 24 and 25-RC

**Comment by grabbou** [comment] 2016-04-26 05:47
When you remove:
```js
alignItems: 'center',
```
it works.

**Comment by lneves12** [comment] 2016-04-26 09:35
Removing alignItems: 'center' works in IOS, but in android the problem still persists.

Using View I get a white screen and using Navigator/DrawerLayoutAndroid I get a black screen. I don't know if the issues are related or are two separated problem. But I will try to do some deeper investigation too when I have some time.

**Comment by grabbou** [comment] 2016-04-26 20:30
@lneves12 I think the iOS-issue might be related to #6110 actually, not sure why on Android is still broken.

**Comment by lacker** [comment] 2016-10-24 20:47
I can't reproduce this from the rnplay link. I am going to theorize it's fixed and close this issue, but feel free to reopen it if the issue is persisting and I'll try to help repro it.

**Closed by lacker** 2016-10-24 20:47 UTC
Labels: Android
