### ISSUE TITLE
[0.45.0] new app setup fails "bundling: Error at DependencyGraph._getAbsolutePath" 

### ISSUE THREAD

**Issue by br4nnigan** [facebook/react-native#14366] opened 2017-06-07 13:20 UTC
react-native init testApp
cd testApp
react-native run-ios

yields:

`
error: bundling: Error
    at DependencyGraph._getAbsolutePath (/Users/nilspoltoraczyk/Desktop/temp/testApp/node_modules/react-native/packager/src/node-haste/DependencyGraph.js:280:11)
    at DependencyGraph.getDependencies (/Users/nilspoltoraczyk/Desktop/temp/testApp/node_modules/react-native/packager/src/node-haste/DependencyGraph.js:218:26)
    at Resolver.getDependencies (/Users/nilspoltoraczyk/Desktop/temp/testApp/node_modules/react-native/packager/src/Resolver/index.js:107:27)
    at /Users/nilspoltoraczyk/Desktop/temp/testApp/node_modules/react-native/packager/src/Bundler/index.js:591:37
    at Generator.next (<anonymous>)
    at step (/Users/nilspoltoraczyk/Desktop/temp/testApp/node_modules/react-native/packager/src/Bundler/index.js:12:445)
    at /Users/nilspoltoraczyk/Desktop/temp/testApp/node_modules/react-native/packager/src/Bundler/index.js:12:605
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
Bundling index.ios.js  0.0% (0/1), failed.
`

OSX 10.11.6

**Comment by aparedes** [comment] 2017-06-07 13:49
I got it to work by starting the packager with `npm run start -- --reset-cache`. 

But you have to reset the cache each time you close it.

**Comment by dmbfm** [comment] 2017-06-07 14:06
Getting the same error here after the last Xcode update.

**Comment by SirNeuman** [comment] 2017-06-07 14:30
Also getting the same error with Android. 

react-native init Project
cd Project
react-native run-android

Android: 7.0 and 6.0 (real devices)
Mac: OS 10.12.5
"react": "16.0.0-alpha.12",
"react-native": "0.45.0"

**Comment by cmcguire79** [comment] 2017-06-07 14:34
Getting the same error for run-ios and run-android. 
Looking for JS files in <project-route>/node_modules/react-native/packager
instead of <project-root>

npm start works ok

**Comment by crazywako** [comment] 2017-06-07 15:08
Cannot run on-device debug. Getting this error. Trying to look files from '/node_modules/react-native/packager'

**Comment by PublicParadise** [comment] 2017-06-07 15:42
I am seeing the same problem after upgrading to react-native 0.45. But my error message is slightly different:
```NotFoundError: Cannot find entry file build/app/app.ios.js in any of the roots: ["<omitted>/client/node_modules/react-native"]```

That might be the reason why @aparedes's `npm run start -- --reset-cache` didn't work for me. Using `--root` as suggested [here](https://stackoverflow.com/a/29390078) did work, though: 

`npm run start -- --root <directory_with_your_react_component_js_sources>`

**Comment by ccdwyer** [comment] 2017-06-07 19:24
I'm having this issue as well. @aparedes's advice is getting me by for now, but it's annoying having to run that command every time I want to launch my app.

macOS: 10.12.5 (16F73)

**Comment by pjeide** [comment] 2017-06-07 21:39
Same problem as @br4nnigan but with Android, @aparedes's solution seems to be working.

Windows 10
react-native 0.45.0
react 16.0.0-alpha.12
Android

**Comment by br4nnigan** [comment] 2017-06-08 05:31
I ended up using [rninit](https://github.com/jacobbubu/rninit) to initialize the project with the previous release.

**Comment by xxxinghao** [comment] 2017-06-08 11:41
I met a problem, also hope to get some help, thank you very much:
Error message:
<
Loading dependency graph, done.
error: bundling: Error
    at DependencyGraph._getAbsolutePath (/Users/xinghao/Desktop/RNNewsCar/node_modules/react-native/packager/src/node-haste/DependencyGraph.js:280:11)
    at DependencyGraph.getDependencies (/Users/xinghao/Desktop/RNNewsCar/node_modules/react-native/packager/src/node-haste/DependencyGraph.js:218:26)
    at Resolver.getDependencies (/Users/xinghao/Desktop/RNNewsCar/node_modules/react-native/packager/src/Resolver/index.js:107:27)
    at /Users/xinghao/Desktop/RNNewsCar/node_modules/react-native/packager/src/Bundler/index.js:591:37
    at Generator.next (<anonymous>)
    at step (/Users/xinghao/Desktop/RNNewsCar/node_modules/react-native/packager/src/Bundler/index.js:12:445)
    at /Users/xinghao/Desktop/RNNewsCar/node_modules/react-native/packager/src/Bundler/index.js:12:605
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
Bundling `index.ios.js`  0.0% (0/1), failed.
error: bundling: Error
    at DependencyGraph._getAbsolutePath (/Users/xinghao/Desktop/RNNewsCar/node_modules/react-native/packager/src/node-haste/DependencyGraph.js:280:11)
    at DependencyGraph.getDependencies (/Users/xinghao/Desktop/RNNewsCar/node_modules/react-native/packager/src/node-haste/DependencyGraph.js:218:26)
    at Resolver.getDependencies (/Users/xinghao/Desktop/RNNewsCar/node_modules/react-native/packager/src/Resolver/index.js:107:27)
    at /Users/xinghao/Desktop/RNNewsCar/node_modules/react-native/packager/src/Bundler/index.js:591:37
    at Generator.next (<anonymous>)
    at step (/Users/xinghao/Desktop/RNNewsCar/node_modules/react-native/packager/src/Bundler/index.js:12:445)
    at /Users/xinghao/Desktop/RNNewsCar/node_modules/react-native/packager/src/Bundler/index.js:12:605
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
Bundling `index.ios.js`  0.0% (0/1), failed.

>
I don't know how this is a mistake 
I NPM is 5.0
 node is 8.0 
10.12.5 is OS
Hope to get answer Thank you very much

**Comment by jdeibe** [comment] 2017-06-08 12:06
I'm having the same problems after upgrade from react native 0.36.0 to 0.45.0 and running npm run start -- --root starts      from console starts the app. Running latest xcode update

**Comment by muhdashiq** [comment] 2017-06-08 16:18
I am also facing similar error.
Loading dependency graph, done.
error: bundling: Error
    at DependencyGraph._getAbsolutePath (/Users/ashiqm/Ashiq/Learning/React-native/kasave/node_modules/react-native/packager/src/node-haste/DependencyGraph.js:280:11)
    at DependencyGraph.getDependencies (/Users/ashiqm/Ashiq/Learning/React-native/kasave/node_modules/react-native/packager/src/node-haste/DependencyGraph.js:218:26)
    at Resolver.getDependencies (/Users/ashiqm/Ashiq/Learning/React-native/kasave/node_modules/react-native/packager/src/Resolver/index.js:107:27)
    at /Users/ashiqm/Ashiq/Learning/React-native/kasave/node_modules/react-native/packager/src/Bundler/index.js:591:37
    at Generator.next (<anonymous>)
    at step (/Users/ashiqm/Ashiq/Learning/React-native/kasave/node_modules/react-native/packager/src/Bundler/index.js:12:445)
    at /Users/ashiqm/Ashiq/Learning/React-native/kasave/node_modules/react-native/packager/src/Bundler/index.js:12:605
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
Bundling `index.android.js`  0.0(0/1), failed.

**Comment by mateofd** [comment] 2017-06-08 16:24
Me too

**Comment by croshim** [comment] 2017-06-08 17:00
+1

**Comment by ozburo** [comment] 2017-06-08 18:43
Doesn't anyone test these releases?

**Comment by muhdashiq** [comment] 2017-06-08 19:03
Issue resolved for me.

The react-native launched new release 0.45 a few days back. So, the commands to create a react-native application and running locally have many differences. 

npm install -g create-react-native-app
Then run the following commands to create a new React Native project called "AwesomeProject":

the new way of creating a react-native application as follows
`create-react-native-app AwesomeProject`

```
cd AwesomeProject
npm start
```

Please follow the official documentation for creating an application and running the application on locally. hope the below link will help you.
https://facebook.github.io/react-native/docs/getting-started.html

Enjoy, Happy coding :)

**Comment by hramos** [comment] 2017-06-08 19:37
Applications created using `create-react-native-app` are set up in a different manner. Projects created using `react-native init`, e.g. "Projects Built with Native Code", are still supported and should work. The workaround is not to switch to CRNA, but rather to kill and restart the packager directly using `npm start`. At this point you can reconnect your app to the packager by reloading.

Closing as duplicate of #14246.

**Closed by hramos** 2017-06-08 19:37 UTC

**Comment by flyandi** [comment] 2017-06-09 04:28
+1 - this happens on an upgraded application as well.

**Comment by xxxinghao** [comment] 2017-06-09 05:16
Brothers, ladies I found the solution:0.45.0 seems to be a beta and formal version of the mixtureWhen we are creating a new project to knock this command react - native init XXX - versoin 0.44.3Then you can I've tried no problem is not in use 0.45.0 version created

**Comment by AndreyPatseiko** [comment] 2017-06-09 06:50
$ react-native init ProjectName --version 0.42.0
