### ISSUE TITLE
[Blur & Focus] Support relinquishing focus from multiple views via container

### ISSUE THREAD

**Issue by ide** [facebook/react-native#113] opened 2015-03-01 02:42 UTC
If you have two text inputs in a container view, calling `container.blur()` could make both of the text inputs try to resign their first responder status. In UIKit this is built-in as `-[UIView endEditing:animated]`. This way you can just blur the root view if you want the keyboard to go away.

**Comment by brentvatne** [comment] 2015-04-21 16:48
ping @ide

**Comment by ide** [comment] 2015-05-06 20:46
Confirmed that `this.refs.parentView.blur` does not blur its child views. Where this would be handy is in the navigator stack where a scene will lose focus without being unmounted, and you want to make sure to blur all of its text fields. So instead of 
```
this.refs.textInput1.blur();
this.refs.textInput2.blur();
this.refs.textInput3.blur();
```
you want to write
```
this.refs.container.blur();
```

**Comment by brentvatne** [comment] 2015-05-10 16:38
This does seem like it would be useful! Another issue came up (referenced above) where this would solve the problem. cc @ide @vjeux

**Comment by dhrrgn** [comment] 2015-05-20 21:42
@brentvatne I came up with a simple solution for this internally where I wrote a component that essentially just extends `UIView` and blurs all of the views.  Here is the guts of it:

``` objc

@implementation KBCloserView

- (void)didMoveToSuperview
{
    self.userInteractionEnabled = TRUE;
    [super didMoveToSuperview];
}

-(void)touchesBegan:(NSSet *)touches withEvent:(UIEvent *)event{
    for (UIView *subview in self.subviews) {
        [subview endEditing:YES];
    }
}

@end
```

So I just convert my container `View`'s to `<KBCloserView>` components, and :boom: tap anywhere in the view to close the keyboard.

I share this because I think adding a `closeKeyboardOnPress` type property to the RN `View` component, which just does the above, would be simple and solve this problem entirely without having to go through the effort of changing how `blur` works (I personally like that it only blurs the specific input).

**Comment by brentvatne** [comment] 2015-05-31 19:56
Nice on @dhrrgn! Seems simple enough. Might be worth putting into a library on npm until a solution is integrated into core

**Comment by dhrrgn** [comment] 2015-05-31 22:18
@brentvatne I will do that tomorrow...right after I figure out how to create an Xcode project people can just add to their's (bit of an Xcode "noob") haha. (Side note: it would be awesome if their was a "Creating Distributable Native Components" section of the docs for this sort of thing).

**Comment by brentvatne** [comment] 2015-05-31 22:32
@dhrrgn - I have something about that on my blog: [Packaging a React Native component](http://brentvatne.ca/packaging-react-native-component/)

**Comment by dhrrgn** [comment] 2015-05-31 22:41
@brentvatne Awesome, thanks.

**Comment by grabbou** [comment] 2015-06-08 15:17
Any updates on that? Calling `blur` on a view should act like `endEditing` as per @ide suggestion. If not, maybe worth adding another method.

My use case:
Using @brentvatne modal with `click backdrop to dismiss` feature. When the keyboard is opened, I'd prefer closing the keyboard instead of dismissing the modal so user has the ability to continue editing. Not all keyboard types are provided `done` button as of now (e.g. `numpad`) so it gets tricky.

**Comment by brentvatne** [comment] 2015-06-08 18:03
@grabbou - do you have time to make the changes that @ide mentioned above and submit a PR?

**Comment by grabbou** [comment] 2015-06-08 18:31
Yeah, can do. Just may need some to dig into the React as haven't contributed yet but would love to.

**Comment by brentvatne** [comment] 2015-06-15 22:22
@ide - what do you think about @grabbou's observation above?

**Comment by ide** [comment] 2015-06-15 22:42
Not sure why that's happening. Maybe something changed. Feel free to close this if it just works now.

**Comment by brentvatne** [comment] 2015-06-15 23:53
@ide - seems to be a false alarm, still not working for me with 0.5: https://rnplay.org/apps/SwEnTw - tried it against master as well, same thing: https://rnplay.org/apps/AxZnJw

@grabbou - can you reproduce that fix on rnplay.org?

**Comment by admmasters** [comment] 2015-06-22 11:44
Not working for me either - an outstanding issue I'm afraid.

**Comment by brentvatne** [comment] 2015-06-23 23:52
Anyone up for fixing this? Would be a great way to learn about some of the React Native internals

**Comment by josebalius** [comment] 2015-07-22 21:07
It is still outstanding, I made another rnplay: https://rnplay.org/apps/aAb8aA/ to showcase the problem with 0.6.0 and can reproduce with 0.8.0-rc, I'm going to give this a try with my limited Objective-C skills.

**Comment by brentvatne** [comment] 2015-07-22 21:32
It looks like nobody on the team at Facebook has a need for this at the moment so I've tagged it as Community Responsibility :smile:

**Comment by josebalius** [comment] 2015-07-23 00:45
@brentvatne So i went off and tried to do it, and I have something working but wanted to show you first as this is my first time messing with the internals so want to see if I should change my approach.

In NativeMethodsMixin.js I added the following under blur():
```
endEditing: function() {
    RCTUIManager.endEditing(findNodeHandle(this));
  }
```

In RCTUIManager.m I did the following:
```
- (void)endEditingForShadowView:(NSNumber *)reactTag
{
    [self addUIBlock:^(__unused RCTUIManager *uiManager, RCTSparseArray *viewRegistry){
      RCTShadowView *shadowView = uiManager.shadowViewRegistry[reactTag];

      for(RCTShadowView *subview in [shadowView reactSubviews]) {
          if([subview.viewName isEqualToString:@"RCTTextField"]) {
              UIView *view = viewRegistry[subview.reactTag];
              [view resignFirstResponder];
          } else if([[subview reactSubviews] count] > 0) {
              [uiManager endEditingForShadowView:subview.reactTag];
          }

      }
    }];
}

RCT_EXPORT_METHOD(endEditing:(NSNumber *)reactTag)
{
  if (!reactTag) return;
  [self endEditingForShadowView:reactTag];
}
```

My test case:

```
blurFields() {
        this.refs.xview.endEditing();
}

<View style={{flex: 1}}>
                <ScrollView ref="scrollView">
                    <View testProp={true} ref="xview">
                        <TextInput ref="field1" style={{backgroundColor: 'red', width: 100, height: 20}} />
                        <TextInput ref="field2" style={{backgroundColor: 'blue', width: 100, height: 20, marginTop: 20}} />
                        <View>
                            <TextInput ref="field3" style={{backgroundColor: 'green', width: 100, height: 20, marginTop: 20}} />
                        </View>
                      	<TouchableHighlight onPress={() => this.blurFields()}>
                            <Text>Blur fields</Text>
                      	</TouchableHighlight>
                    </View>

                </ScrollView>
            </View>
```

Everything seems to work okay and the functionality works as expected. What do you think?

**Comment by brentvatne** [comment] 2015-07-24 02:41
@josebalius - this looks very reasonable to me, @tadeuzagallo what do you think?

**Comment by josebalius** [comment] 2015-07-24 13:36
@brentvatne roger on the API, i thought about the same thing shouldn't be a problem. If @tadeuzagallo is fine with the code i'll submit the PR with an API like `this.refs.parentView.blur(true)` `true` for deep search, if not `true` then it will act the same as it does now which is tries to blur the active text field.

**Comment by brentvatne** [comment] 2015-07-24 17:53
@josebalius - yeah I agree, if it's just a TextField then we don't have to be concerned about traversing any children

**Comment by wluxion** [comment] 2015-09-18 18:14
This can be closed, no?
https://github.com/facebook/react-native/blob/master/Libraries/Utilities/dismissKeyboard.js

```javascript
var dismissKeyboard = require('dismissKeyboard')
...
onClose: function() {
	dismissKeyboard();
}
```

**Comment by ryanmcdermott** [comment] 2015-10-09 16:00
@wluxion Looks interesting, how do you require the dismissKeyboard Utility in a project? I didn't see Utilities or that particular one in the docs. Will it work on iOS and Android?

**Comment by brentvatne** [comment] 2015-10-09 16:26
We are exposing TextInputState in #3308 which will allow you to do this too. I'm not sure it's worth exposing this one line function as it will increase API surface area, if you believe it's important then feel free to chime in on that PR! Thanks @wluxion for the heads-up.

**Closed by brentvatne** 2015-10-09 16:26 UTC
Labels: Community Responsibility, Good first task

**Comment by ryanmcdermott** [comment] 2015-10-09 16:39
@brentvatne Looks great, I look forward to it.

**Comment by josebalius** [comment] 2016-01-03 05:29
@brentvatne Any update on this? I am upgrading a couple of projects to the latest RN and running into blur issues not hiding the keyboard, do we have docs on the proper way to do it?

**Comment by brentvatne** [comment] 2016-01-03 05:39
@josebalius - hmmm I'm not sure about this, could you put together a small example and create a new issue?
