### ISSUE TITLE
Weird position after rotate

### ISSUE THREAD

**Issue by WitzHsiao** [facebook/react-native#9484] opened 2016-08-19 09:27 UTC
As title, not sure if it causes by mis-use or bug. The following is snippet and screenshot.
Is there a way to make the rotated child works fine with flexbox?

``` js
<View style={{flex:1}}>
  <View style={{backgroundColor: 'black', width: 195, height: 300, transform: [{rotateZ: '90deg'}]}}>
  </View>
</View>
```

![simulator screen shot aug 19 2016 5 25 09 pm](https://cloud.githubusercontent.com/assets/1393727/17805395/f3188558-6631-11e6-9081-ccb24da553f6.png)

**Comment by jasongaare** [comment] 2016-09-19 15:14
When you rotate you will have to translate as well. 

Translation is that (-52.5, 52.5) you see there in the inspector, which is simply the half of the absolute value of the difference between the image width and height.

Not a bug as far as I'm concerned

**Comment by WitzHsiao** [comment] 2016-09-21 10:35
@jasongaare, thanks! But how can I do that?

**Comment by ericnakagawa** [comment] 2017-01-10 18:15
Following @jasongaare 's lead and closing this issue as it isn't a bug.

**Closed by ericnakagawa** 2017-01-10 18:15 UTC
