### ISSUE TITLE
[Image] Image components don't retain resizing when re-rendering

### ISSUE THREAD

**Issue by andrewngu** [facebook/react-native#733] opened 2015-04-07 22:54 UTC
On inital rendering my <Image> element is appropriately resized by it's given stylesheet rule (Image.resizeMode.cover). When a change to my component's state occurs, causing a rerender the image then appears stretched (image.resizeMode.stretch). If I do a reload, the image renders fine.

Also, the source is always a network image.

Thanks for your guys' work on this btw. It's awesome.

**Comment by jaygarcia** [comment] 2015-04-08 00:34
It would be beneficial to everyone here if you could post code to replicate issues like these :)

JG

:: @moduscreate

:: sent from my mobile device ::

**Comment by andrewngu** [comment] 2015-04-08 03:07
Sure thing!

So I did a little more digging and it turns out that it only happens with really large images. Is it because the view is rendering before the image has finished downloading? Is there a way to preload the image within a react component? Anyways, here's the code to reproduce the issue.

    /**
     * Sample React Native App
     * https://github.com/facebook/react-native
     */
    'use strict';

    var React = require('react-native');
    var {
        AppRegistry,
        Image,
        StyleSheet,
        Text,
        TouchableHighlight,
        View,
    } = React;

    var ImagesTest = React.createClass({
        getInitialState: function(){
            return {
                images: [
                    '{"image": "http://imageshack.com/a/img540/5042/7rh9dZ.jpg"}',
                    '{"image": "http://i1196.photobucket.com/albums/aa419/lefashion/lefashion054/2-Le-Fashion-Blog-Model-Crush-Joanna-Halpin-Long-Hair-White-Jeans-Via-Mate-The-Label.jpg"}',
                    '{"image": "http://imageshack.us/a/img43/6163/stylemintbluetopstriped.jpg"}',
                    '{"image": "http://www.styledumonde.com/wp-content/uploads/2014/02/May-Buranasiri-dailycherie-by-STYLEDUMONDE-Street-Style-Fashion-Blog_MG_88211.jpg"}',
                    '{"image": "http://www.made-in-italy.com/files/imagecache/lg/pictures/italian-fashion/news/2013/04/fashion-blogger-di-betty.jpg"}',
                ]
            };
        },
        getImage: function() {
            var image = JSON.parse(this.state.images[0]);
            return image.image;
        },
        shiftImages: function() {
            var images = this.state.images;
            var firstImage = images.shift();
            images.push(firstImage);
            this.setState({
                images: images,
            });
        },
        render: function() {
            return (
                <View style={styles.container}>
                    <Image style={styles.image} source={{uri: this.getImage()}} />
                    <TouchableHighlight style={styles.button} onPress={this.shiftImages}>
                        <Text>Press to change photo</Text>
                    </TouchableHighlight>
                </View>
            );
        }
    });

    var styles = StyleSheet.create({
        container: {
            flex: 1,
            flexDirection: 'column',
            justifyContent: 'center',
            alignItems: 'center',
            backgroundColor: '#F5FCFF',
        },
        image: {
            flex: 1,
            width: 340,
            resizeMode: Image.resizeMode.cover,
        },
        button: {
            height: 50,
            justifyContent: 'center',
        }
    });

    AppRegistry.registerComponent('ImagesTest', () => ImagesTest);

**Comment by browniefed** [comment] 2015-07-20 18:35
@andrewngu can you take a look and see if this is still being reproduced in latest react-native .80.
If not a possible workaround would be to use the new image callback `onLoaded` and cause a refresh?

**Comment by brentvatne** [comment] 2015-07-20 18:51
@andrewngu - if you get a chance to double check that this is still a bug it would be great, closing this issue until then as so much has changed in react-native since this was originally posted :smile:

**Closed by brentvatne** 2015-07-20 18:51 UTC

**Comment by andrewngu** [comment] 2015-07-21 00:45
Yep, this has definitely been fixed. Thanks guys!
