### ISSUE TITLE
Unrecognized font family 'XXX'，both iOS & Android.

### ISSUE THREAD

**Issue by dongdong204hn** [facebook/react-native#18558] opened 2018-03-26 03:51 UTC
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

I customized a RN template with a .ttf file inside. When I use my template to initialize the project, for example: react-native init xxx --template xx. I run the simulator and I get the following error:
![simulator screen shot - iphone 6s - 2018-03-23 at 17 44 54](https://user-images.githubusercontent.com/2776064/37885592-ab5532ce-30e8-11e8-8717-35c001248823.png)

When I checked the ttf file in the project, it was found to have been tampered with. The following is the result of comparing the original ttf in the template:
![rn_init_ ttf](https://user-images.githubusercontent.com/2776064/37885700-545e9fe0-30e9-11e8-95f0-710ebf67dea2.jpg)

I think this is a bug and I want to know how to solve it.

## Environment

OS: macOS Sierra 10.12.6
Node: 7.10.1
Yarn: 1.3.2
npm: 4.1.0
Watchman: 4.9.0
Xcode: Xcode 9.2 Build version 9C40b
Android Studio: 2.3 AI-162.3764568

Packages: (wanted => installed)
react: 16.0.0-alpha.12 => 16.0.0-alpha.12
react-native: 0.47.2 => 0.47.2

## Steps to Reproduce

1. Customize a template: XXX
2.Add any .ttf file into Customize a template
3.Use the template XXX to initialize a project：react-native init project --version="0.47.2" --template XXX
4.Compare the .ttf file in the new project with the original one.
5.Use this .ttf in your new project.

## Expected Behavior

The .ttf file in the new project as same as the original one.
The .ttf can be used normally in new projects.

## Actual Behavior

Just like the screenshot above. The contents of the .ttf have been changed and can not be read by the project.

**Comment by dongdong204hn** [comment] 2018-03-26 06:14
@react-native-bot  Yes, I can reproduce the issue on the [latest release, v0.54](https://github.com/facebook/react-native/releases/tag/v0.54.0).

**Comment by dongdong204hn** [comment] 2018-03-27 00:58
@jimji1005 After using the template to initialize a project, the font is imported as an asset. Because the font is useful in the JS file of the template, it is best to be added to the template for convenience.

**Comment by kelset** [comment] 2018-04-13 16:17
Duplicate of https://github.com/facebook/react-native/issues/18269

**Closed by kelset** 2018-04-13 16:17 UTC
Labels: :large_blue_diamond:Android, :large_blue_diamond:iOS, :rewind:Old Version

**Comment by dongdong204hn** [comment] 2018-04-14 01:54
@kelset Hello, I hope you can see my problems carefully, instead of just looking at the headlines. These are two completely different problems. In my problem, the TTF file is preset in the template, and the TTF file will be tampered in the process of react-native init. 
You can have a try, after react-native init --template fego, song.ttf font file has been unable to read normally. Fego is my template name. The song.ttf file is in the resource directory of the new project coming out of init.
