### ISSUE TITLE
[Style] "letterSpacing" and "padding" is not effective on <Text />

### ISSUE THREAD

**Issue by LeoJiaXin** [facebook/react-native#3485] opened 2015-10-18 06:41 UTC
platform: Android4.3 
simulator: Genymotion,Google Nexus 4, Android 4.3
react native version: 0.12.0
react-native-cli: 0.1.5

```
var React = require('react-native');

var {
    StyleSheet,
    Text
} = React;

var Test = React.createClass({
    render: function() {
        return (
            <Text style={styles.text}>123123</Text>
        );
    }
});

var styles = StyleSheet.create({
    text: {
        letterSpacing: 20,
        padding: 10,
        backgroundColor: '#f00'
    }
});

```

but result is:
![2015-10-18 14 40 23](https://cloud.githubusercontent.com/assets/7020278/10562926/30b3c648-75a6-11e5-820f-2ee58a003d80.png)

seems `letterSpacing` and `padding` is not supported

**Comment by brentvatne** [comment] 2015-10-18 18:50
Confirmed in this example: https://rnplay.org/apps/5M_0Nw

cc @kmagiera @foghina

**Comment by crm416** [comment] 2015-10-18 23:58
Seems like the letter spacing attribute was only added in [API 21](https://developer.android.com/reference/android/widget/TextView.html#setLetterSpacing(float)), but RN's minimum supported version is [API 16](https://github.com/facebook/react-native/blob/master/README.md).

**Comment by ide** [comment] 2015-10-19 05:05
@crm416 thanks for the research.

@mkonicek @vjeux what do you want to do here if old Android doesn't support a feature? Looks like AppCompatTextView doesn't backport letterSpacing (https://developer.android.com/reference/android/support/v7/widget/AppCompatTextView.html) so we may need to reimplement text rendering if we wanted this. Or we could get it working on modern Android (if it doesn't work already) and mention that in the RN docs.

**Comment by kmagiera** [comment] 2015-10-19 08:12
We don't expose this property yet on android (even on API 21+)

On API <21 we could potentially implement it using `ReplacementSpan`, but I'd rather only support it whenever available as using `ReplacementSpan` may not be the most efficient way to do that. One can always use custom font to achieve similar results although it won't be possible to tweak the value just by changing a single param. We already have a number of props that we support only for certain android release (e.g. some of the accessibility properties or borderless ripple params) so I think it would be fine to  do the same here.

Anyone fancy sending PR?

**Comment by ide** [comment] 2015-10-19 09:07
> We already have a number of props that we support only for certain android release (e.g. some of the accessibility properties or borderless ripple params) so I think it would be fine to do the same here.

Sounds like a good plan. I've marked this as "Help Wanted" for enthusiastic contributors.

**Comment by crm416** [comment] 2015-10-20 01:16
@kmagiera I'd be happy to give it a shot.

**Comment by PhilippKrone** [comment] 2015-10-22 10:07
@crm416 This seems to be connected to https://github.com/facebook/react-native/issues/3233 - are you working on it? If yes, those two issues could be merged. @ide

**Comment by ide** [comment] 2015-10-22 10:14
Most of the convo in this issue is about letterSpacing and #3233 is more about padding so let's keep them separate for now. If both issues are fixed in the same PR, just write "Fixes #3485, fixes #3233".

**Comment by PhilippKrone** [comment] 2015-10-26 05:39
@crm416 Did you already have a chance to take a shot here? :)

**Comment by crm416** [comment] 2015-10-27 03:24
@PhilippKrone not yet! been a little busy. feel free to take it over if you're interested.

**Comment by crm416** [comment] 2015-10-29 05:10
I started working on this tonight, but it's turning out to be non-trivial. The issue is that bumping up the letter spacing can in turn increase the number of lines in the text, and so `ReactTextShadowNode` has to account for that possibility (else, if you bump up the letter spacing and your text now spans an additional line or two, those lines will get cutoff). There isn't really a simple way to do that, since the final number of lines will be based on the font size and the actual contents of the text. (Aside: letter spacing is specified in `em`, unlike almost any other property in Android, which doesn't help.) So, I think that the letter spacing value will have to be passed all the way down to the `StaticLayout` constructor, but the code in that file is pretty complex, and I wanted to check back here before diving in.

On that note: please let me know if I'm missing something obvious! Very new to this codebase.

**Comment by satya164** [comment] 2016-03-20 13:26
Closing in favor of #3233

**Closed by satya164** 2016-03-20 13:26 UTC
Labels: Android, Help Wanted

**Comment by jerolimov** [comment] 2017-03-29 14:17
See also #13199
