### ISSUE TITLE
Camera interface white SDK: 22, the user manually shut down Camera permissions

### ISSUE THREAD

**Issue by TrustTheBoy** [facebook/react-native#13581] opened 2017-04-19 12:52 UTC
Camera authority is not open, the camera interface is white, how to solve?
PermissionsAndroid only works at SDK> = 23
Will the SDK <23 how to detect whether the user manually closed by the user?

windows 10
phone: Samsung
Android ：5.0

**Comment by hramos** [comment] 2017-05-31 20:46
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-05-31 20:46 UTC
