### ISSUE TITLE
React Native link adds tvOS library targets to the ios target

### ISSUE THREAD

**Issue by cmcewen** [facebook/react-native#13783] opened 2017-05-04 17:43 UTC
### Description

In adding a tvOS target to the react-native-vector-icons library, `react-native link` inadvertently adds the tvOS target to the normal ios target causing the app to fail to run

### Reproduction Steps and Sample Code

Described here: https://github.com/oblador/react-native-vector-icons/issues/461

### Solution

React Native link needs to properly link the ios and tvOS library targets with the right target

### Additional Information

* React Native version: 0.44
* Platform: iOS
* Development Operating System: MacOS
* Dev tools: XCode 8.3.2

**Comment by ericvicenti** [comment] 2017-05-04 18:09
Ah, bummer. `react-native link` can sometimes be clumsy, cc @grabbou who knows more about it

**Comment by oblador** [comment] 2017-05-04 18:30
Also perhaps @Kureev?

**Comment by engmsaleh** [comment] 2017-05-04 19:15
I have the same problem

**Comment by grabbou** [comment] 2017-05-08 09:42
The issue is in this code https://github.com/facebook/react-native/blob/master/local-cli/link/ios/registerNativeModule.js#L36-L40

It calls `getProducts` that returns an array of all products (the array will typically have two items `tvOS` and `iOS` targets) and adds them to `getFirstTarget()`.

We need to handle those things in a way that we link tvOS with tvOS and iOS with iOS (and other targets in the future as well).

I'll be looking into that later this week - if anyone wants to start earlier, you can hit me up on slack.callstack.io and will be happy to help.

**Comment by grabbou** [comment] 2017-06-28 13:16
I am starting work on this issue and hopefully a nice solution lands soon :)

**Comment by grabbou** [comment] 2017-08-22 08:22
FYI: I have been working on this for past two weeks from time to time - the issue turned out to be quite complex and requires few changes to `link` and `unlink` philosophy. I keep posting updates here.

**Comment by srameshr** [comment] 2017-09-27 16:46
Im stuck with this. ANy help?

**Comment by YasirPanjsheri** [comment] 2017-11-02 05:20
Hi, do we need to have tvOS? How do we remove it from the project?

**Comment by dlowder-salesforce** [comment] 2017-11-20 16:21
@grabbou any update on this?  Is there anything I can do to help?

**Comment by grabbou** [comment] 2017-11-21 08:59
Yeah! Would love to pair and brainstorm few ideas out - do you think we could follow up on Slack and get this done? It's going to be a big rewrite of internals but it's quite needed.

**Comment by matthargett** [comment] 2017-11-24 19:39
@dlowder-salesforce were you still planning to extract tvOS to be hosted out of tree?

**Comment by dlowder-salesforce** [comment] 2017-11-27 22:39
@matthargett extracting tvOS is something that can hopefully be done eventually, but will take some time.  For now, I'm just planning to fix the tvOS-specific issues, and work with @grabbou on cleaning up the CLI internals.

**Comment by TheoGit** [comment] 2017-12-20 21:37
@dlowder-salesforce what as a user do I need to do to get this fix? (great Chain React video btw)

**Comment by ankitdesai** [comment] 2017-12-20 23:32
@TheoGit this worked for me: https://github.com/rebeccahughes/react-native-device-info/issues/258#issuecomment-340434729

replace `libRNDeviceInfo-tvOS.a` with whatever lib is causing your build to fail

**Comment by TheoGit** [comment] 2017-12-20 23:49
@ankitdesai I just got it to work - thanks!  @dlowder-salesforce I have the simulator running now and look forward to having created an Apple TV App with React Native

**Comment by dlowder-salesforce** [comment] 2017-12-21 08:34
@TheoGit thanks for the kind words.... to get my fix directly you can use

`"react-native": "https://github.com/dlowder-salesforce/react-native#tvos-cli-link-fix-2",`

in your package.json, or you can wait for this branch to get merged to a release version.

**Comment by TheoGit** [comment] 2017-12-21 17:24
@dlowder-salesforce thanks!  I'm working on a big project and will visiting often - I also saw the rn-tvos-example-2048 project if you think that will help

**Comment by egid** [comment] 2018-01-11 01:11
@dlowder-salesforce any idea when this branch will merge?

**Comment by dlowder-salesforce** [comment] 2018-01-11 02:50
@grabbou will be reviewing the PR for this shortly.

**Closed** 2018-01-31 00:30 UTC

**Comment by grabbou** [comment] 2019-02-05 16:13
Or, manually add it if it wasn't added by `link` (this is literally what we
just stumbled upon internally)
