### ISSUE TITLE
iOS Simulator CMD+R CMD+D Shake doesn't work at all after some time

### ISSUE THREAD

**Issue by v0lume** [facebook/react-native#27384] opened 2019-12-02 10:40 UTC
React Native version:
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 397.52 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/opt/nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.19.1 - /usr/local/Cellar/yvm/3.6.1/shim/yarn
    npm: 6.9.0 - /usr/local/opt/nvm/versions/node/v10.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 14, 25, 26, 28, 29
      Build Tools: 28.0.3, 29.0.0, 29.0.1
      System Images: android-26 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.1 => 0.61.1 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce

1. yarn ios
2. switch to another window for some time
3. switch back to ios simulator

simulator doesn't recognize any shortcuts. Keyboard is working ok - I still can fill text inputs in app. Also dev menu is shown in case of any error in JS runtime after fastrefresh.
Closing simulator and starting it once again fixed an issue for some time. But after 5-10 minutes it can happen once again.

It's very annoying cause it can be reproduced 10-20 times during a day.

**Comment by vishgoel007** [comment] 2019-12-03 12:23
You can use ctrl + cmd + z to open the shake menu.

**Comment by v0lume** [comment] 2019-12-09 13:39
@vishgoel007 thanks, it helps to reload app, but how to fix hanged cmd+d cmd+r ?

**Comment by vishgoel007** [comment] 2019-12-09 13:42
@v0lume I don't know, facing same issue.

**Comment by ragamufin** [comment] 2019-12-31 09:22
if cmd + d doesn't work for me then as per @vishgoel007 's comment ctrl + cmd + z does the shake gesture and the menu shows up but shows up twice as if the previous cmd + d action runs at the same time. Only started noticing this on the most recent version or maybe a version before that

**Comment by kamui545** [comment] 2020-04-01 11:13
Still happening.
I think I've found a solid way to reproduce the issue:

1. Make sure "Send Keyboard Input to Device" is checked (I/O -> Input on XCode 11.4).
2. CMD + R, it works
3. Focus any other macOS app: Finder, Terminal, Editor etc...
4. Go back to simulator and check the setting, it is now unchecked.

I am pretty sure this is not React Native fault but in fact the Simulator itself, which will probably be harder to get fixed... =/

In the meantime, you can use "R" and "D" in the Metro terminal tab.
"D" seems to be broken on my app though, React 0.62...

**Comment by darrylyoung** [comment] 2020-04-03 10:06
Confirmed that I'm also seeing this issue, too. I'm using Expo. What's strange is that it only started happening the day I upgraded to macOS 10.15.4 and Xcode 11.4. That was around a week ago. Before that, I'd been using the same Simulator setup for months and could always hit CMD + R to reload. Now, it just works once and I have to use CTRL + CMD + Z to simulate a shake and open the Expo developer tools if I want to manually trigger a reload. Pressing "R" in the Metro terminal tab does _work_ but it restarts the bundler and that's not exactly what I wanted.

I've spoken to one of the Expo developers and while they personally can't reproduce, they have spoken to others (in the Expo Slack, for example) who have. I guess, as @kamui545 said, it's an issue with the Simulator itself. 🤔

**Comment by hlthi** [comment] 2020-04-03 16:18
> Confirmed that I'm also seeing this issue, too. I'm using Expo. What's strange is that it only started happening the day I upgraded to macOS 10.15.4 and Xcode 11.4. That was around a week ago. Before that, I'd been using the same Simulator setup for months and could always hit CMD + R to reload. Now, it just works once and I have to use CTRL + CMD + Z to simulate a shake and open the Expo developer tools if I want to manually trigger a reload. Pressing "R" in the Metro terminal tab does _work_ but it restarts the bundler and that's not exactly what I wanted.
> 
> I've spoken to one of the Expo developers and while they personally can't reproduce, they have spoken to others (in the Expo Slack, for example) who have. I guess, as @kamui545 said, it's an issue with the Simulator itself. 🤔

I have exactly same problem.

**Comment by hlthi** [comment] 2020-04-03 16:38
> Confirmed that I'm also seeing this issue, too. I'm using Expo. What's strange is that it only started happening the day I upgraded to macOS 10.15.4 and Xcode 11.4. That was around a week ago. Before that, I'd been using the same Simulator setup for months and could always hit CMD + R to reload. Now, it just works once and I have to use CTRL + CMD + Z to simulate a shake and open the Expo developer tools if I want to manually trigger a reload. Pressing "R" in the Metro terminal tab does _work_ but it restarts the bundler and that's not exactly what I wanted.
> 
> I've spoken to one of the Expo developers and while they personally can't reproduce, they have spoken to others (in the Expo Slack, for example) who have. I guess, as @kamui545 said, it's an issue with the Simulator itself. 🤔

<img width="1086" alt="Screen Shot 2020-04-03 at 19 36 45" src="https://user-images.githubusercontent.com/16364199/78384307-9faa0580-75e2-11ea-9087-2a506febf873.png">

Can you try select send keyboard input to device ? It solves my problem.

**Comment by darrylyoung** [comment] 2020-04-07 08:12
Hi, @hlthi. Thanks for your reply but that unfortunately doesn't help in my case.

**Comment by leviduan** [comment] 2020-04-07 08:21
Hi, @hlthi. Thanks for your reply but that unfortunately doesn't help in my case.

**Comment by leviduan** [comment] 2020-04-07 08:22
> Hi, @hlthi. Thanks for your reply but that unfortunately doesn't help in my case.

If you resolve the questions, please notify me.

**Comment by hlthi** [comment] 2020-04-07 10:22
IOS 13.4  cause that problem. You can back IOS 13.3.

1. Open XCode.
2. Press ⌘ + ,  -> or open Preferences
3. Press Components
4. Download IOS 13.3 Simulator.
5. After download, close all simulators.
6. Open new device with IOS 13.3.

<img width="693" alt="Screen Shot 2020-04-07 at 13 20 46" src="https://user-images.githubusercontent.com/16364199/78658281-a8485780-78d2-11ea-9d64-7d2ae70118b8.png">

**Comment by darrylyoung** [comment] 2020-04-07 10:25
> IOS 13.4 cause that problem. You can back IOS 13.3.

That's useful to know, and could be a quick workaround, but isn't ideal as you _should_ be able to test on the latest iOS, against the latest APIs, etc. Thanks for the tip, though.

Let's just hope that this gets fixed on Apple's side. I wonder where/how this could be reported. 🤔

**Comment by bolan9999** [comment] 2020-04-10 12:53
My XCode‘s version is 11.4, and I got the same problem, too. I found a  solution which is not prefect:

Every time after you switch back to ios simulator, you can click `Menu Bar => I/O => Input => send keyboard input to device`, and then type `command + R` twice. It means you must take 5-10s to reload.

**Comment by weinixuehao** [comment] 2020-05-15 13:53
@bolan9999
There is not a perfect solution ?

**Comment by bolan9999** [comment] 2020-05-18 12:53
@weinixuehao switch your ios simulator version to 13.3 as hlthi said.

**Comment by ospfranco** [comment] 2020-05-29 18:49
I've been having this issue for over a year now, did not start for me with 13.3 but with 12.x, going to the menu and clicking on `send keyboard input to device` is a waste of my time, daily.

**Comment by terrencebob** [comment] 2020-06-01 08:42
first press D ，then press CMD+D can solve, but I do not why.
the same press R ，then press CMD+R

**Comment by v0lume** [comment] 2020-06-03 12:12
One more solution:

1. Simulator -> Customize Touch Bar...
2. Add Shake Device to touch bar

![image](https://user-images.githubusercontent.com/5075100/83635268-98848100-a5ac-11ea-81b7-9c805df66174.png)

**Comment by kangfenmao** [comment] 2020-09-02 06:15
Not fixed

**Comment by kamui545** [comment] 2020-09-17 11:31
It looks like this is finally fixed on XCode 12 + iOS 14 ✨

**Comment by safaiyeh** [comment] 2020-09-17 14:39
Thanks @kamui545, since this is a pretty dated I'll close this. If this continues on a fresh React Native template on the latest version please feel free to open another issue with the issue template. Thanks!

**Closed by safaiyeh** 2020-09-17 14:39 UTC
Labels: Bug, Platform: iOS

**Comment by ospfranco** [comment] 2020-09-18 09:21
This is not fixed for me, I'm using Xcode 12 GM and after one reload cycle the simulator stops responding

**Comment by nlindroos** [comment] 2021-04-07 11:30
The same kinds of issues are still present with (at least) Xcode 12.4, iOS 14.4 and RN 0.64.0. @kamui545's announcement is premature and not accurate.

Although this issue is old, the problems still persist. I don't mean to sound offensive. I just don't think closing issues with the reasoning that they have been opened a long time ago, with no indication of a fix, is the correct approach. Thanks

**Comment by kamui545** [comment] 2021-04-07 11:50
@nlindroos As far as I can tell, this issue is about the "Send keyboard input to device" bug from XCode, which is not related to React Native at all. I just checked again and the issue is still not happening on my end.

Your issue might be related to Metro however, could you please provide more detail on how to reproduce the issue?

If it's not reloading, can you at least open the debug menu (cmd+d)? If so, then it's probably Metro and I would recommend opening a new issue

**Comment by wmonecke** [comment] 2021-05-02 15:06
For me, it went from `CMD` + `D` to just pressing `D` when the simulator is focused.
(iPhone12; iOS 14.4)

**Comment by ospfranco** [comment] 2021-06-09 07:55
I have noticed that pressing `R` `R` reloads the app on the latest react-native versions, same as on the android emulator, so maybe this is an intentional change.

**For those coming in nowadays**
In any case, so far the workarounds seem to be:

- `cmd` + `shift` + `z` to trigger the dev menu and then click on reload
- `r` `r` sometimes also does the trick
- `d` if the simulator is focused

**Comment by HugoGresse** [comment] 2021-08-19 13:10
After the update to RN 0.64, the `cmd` + `d`  stopped working... unless the build is done directly through XCode. I though `react-native run-ios` was having issues, but the build from CLI is still debug and `cmd` + `alt` + `z` still work from the CLI build.... I have no clue what's going on. 
iPhone 12, iOS 14.5
