### ISSUE TITLE
Nested React Native projects result in TypeError: undefined is not an object (evaluating self.fetch)

### ISSUE THREAD

**Issue by migueloller** [facebook/react-native#9599] opened 2016-08-26 05:40 UTC
I'm unsure how related this is to #5667 or #3975 but I've been trying to figure this out for 5 hours.

Here's the repo: https://github.com/bloveit/react-native-redux-navigation

I'm trying to create a React Native example for this module but there is an error that occurs when trying to run the example.

To reproduce:

```
git clone https://github.com/bloveit/react-native-redux-navigation.git
cd react-native-redux-navigation
npm i
cd examples/TabsExample
npm i
react-native run-ios
```

I tried to pinpoint the error to a specific package, but no luck. I also tried nesting other React Native projects but the bug didn't happen (it seems to be an edge case).

Would greatly appreciate some insight on this bug!

Screenshot:
![simulator screen shot aug 26 2016 1 39 12 am](https://cloud.githubusercontent.com/assets/5677929/17995209/e8b9f230-6b2d-11e6-8bab-b3418bcfd215.png)

Thanks! 🍺

**Comment by migueloller** [comment] 2016-08-26 14:40
A most peculiar thing is that if remote JS debugging is turned on, the error goes away.

**Comment by willks** [comment] 2016-09-20 23:43
@migueloller I'm also getting this since trying to upgrade to RN 0.33 - and this is my latest issue. It works in DEBUG mode for me as well. Did you ever get around this issue?

**Comment by migueloller** [comment] 2016-09-20 23:46
@willks,

I did not. 😞 

I ended up removing the example folder completely and was going to look at the problem a bit closer at a later time.

**Comment by willks** [comment] 2016-09-21 11:26
@migueloller Hey I got it working using RN 0.33 and doing a hack - following this project:

https://github.com/johanneslumpe/react-native-browser-polyfill

Specifically, I added the following to my app.js:

`global.self = global;`

I added it right at the top. Now my fetches are working properly again. Seems like a dirty hack but I was a bit desperate to get it going on iOS10 and now it's running again.

**Comment by migueloller** [comment] 2016-09-21 16:05
@willks,

Interesting fix, I wonder if React Native should do this by itself?

**Comment by compojoom** [comment] 2016-11-11 08:35
I had the same issue for the past 2 months and I was always wondering what's going on. 

@migueloller - thanks, your fix works for me as well.

**Comment by compojoom** [comment] 2016-11-11 08:39
Actually I had to do this:
```
if(typeof global.self === "undefined")
{
    global.self = global;
}
```

because when debuging remotely I was getting: "cannot assign to read only property 'self' of object '#<DedicatedWorkerGlobalScope>?"

**Comment by tqc** [comment] 2017-05-17 03:31
This is caused by the fetch polyfill from https://github.com/github/fetch / https://www.npmjs.com/package/whatwg-fetch requiring self or this to be defined. 

The workaround from other comments usually succeeds, but is not completely reliable because the packager/transpiler does not guarantee that that will run before whatever is calling fetch. Usually that isn't a problem because global.fetch is implemented as a lazy getter, but a module containing `if (fetch)` on startup is sufficient to trigger the bug.

**Closed** 2017-10-09 17:27 UTC
Labels: Icebox

**Comment by apolishch** [comment] 2018-02-19 22:39
This issue has reappeared for me when upgrading from RN0.51 to RN0.53
The workaround in this commit:
https://github.com/davidvuong/ddfa-rn-app/commit/e54a799a92d28a894b7c1ad6d2e3efc727922069

makes the problem go away

**Comment by iamlasse** [comment] 2018-03-04 21:48
I just opened my project this morning after working on it last night without problem to see this weird error... ANyone find a fix or workaround for this??

**Comment by panuhorsmalahti** [comment] 2018-03-05 11:14
We're also seeing this. At the moment we're using a workaround like this: https://github.com/panuhorsmalahti/aws-sdk-js/commit/309db2c349dab361f6e940cc7da7dd4ab1408f7a

**Comment by alexfoxy** [comment] 2018-03-05 18:47
I also have this issue all of a sudden. I have tried the global.self = global; fix to no avail. Running RN0.54

**Comment by nhannah** [comment] 2018-03-27 01:37
I rebooted my computer and my react app went from running fine to only running with expo in debug as described. @apolishch 's referenced fix worked for me for now, but seems very odd that it came out of no where.

**Comment by MarkOSullivan94** [comment] 2018-07-19 16:19
Also using a nested RN project and came across this issue in 0.55.4

@compojoom's solution fixed this for me: https://github.com/facebook/react-native/issues/9599#issuecomment-259908536

**Comment by Calsowah** [comment] 2018-08-05 16:30
@alexfoxy where you able to find an alternative solution? I have also tried the global.self=global solution but am still having the same error

**Comment by paulmars** [comment] 2018-08-13 22:49
Appearing for me. 

    "react": "^16.4.2",
    "react-native": "~0.55.2",

**Comment by amitlibra** [comment] 2018-08-23 16:09
I am noticing this issue only on Android
```
    "react": "16.4.2",
    "react-native": "0.55.4",
```
I used the above recommended fix:
```
if (global && !global.self && Platform.OS === 'android') {
  global.self = global;
}
```
