### ISSUE TITLE
RCTFatal + 448 crash when testing via iOS TestFlight

### ISSUE THREAD

**Issue by udarts** [facebook/react-native#20715] opened 2018-08-17 15:43 UTC
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
````
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 25.20 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.10.0 - /usr/local/bin/node
      npm: 6.3.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 23.0.3, 24.0.1, 25.0.1, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3
        API Levels: 16, 17, 18, 19, 20, 21, 23, 24, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.2 => 16.4.2 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
````

## Description
I have released my app for testing by a specific group of people via Apple's TestFlight.
For most of the testers it seems to work perfect, but I had 1 person reporting a crash, I loaded into XCode and got the RCTFatal + 448 error.

Which seems to relate to:
<img width="1083" alt="screen shot 2018-08-17 at 17 41 36" src="https://user-images.githubusercontent.com/11528890/44275391-e64bc000-a244-11e8-900c-6f25a24570e8.png">

Found in:
<img width="506" alt="screen shot 2018-08-17 at 17 41 45" src="https://user-images.githubusercontent.com/11528890/44275408-eea3fb00-a244-11e8-8f2b-6131305007e5.png">

At this moment no idea what it is causing the crash. So no idea what code to provide.

**Comment by radik** [comment] 2018-09-05 07:39
@udarts Did you solve it?

**Comment by udarts** [comment] 2018-09-05 07:46
@radik nope, as I still have no idea what the issue is and why it happened.

**Comment by radik** [comment] 2018-09-05 11:06
@udarts Could you share your package.json?
Here is mine:

```json
{
  "name": "MyApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "test:lint": "eslint ."
  },
  "dependencies": {
    "eslint-plugin-jest": "^21.18.0",
    "lodash": "^4.17.10",
    "mobx": "5.0.0",
    "mobx-react": "5.2.0",
    "moment": "^2.22.2",
    "native-base": "^2.7.2",
    "prop-types": "^15.6.2",
    "react": "16.4.1",
    "react-native": "0.56.0",
    "react-native-maps": "^0.21.0",
    "react-native-router-flux": "git+https://github.com/aksonov/react-native-router-flux.git",
    "react-native-scalable-image": "^0.4.0",
    "react-native-star-rating": "^1.0.9",
    "react-native-swiper": "^1.5.13"
  },
  "devDependencies": {
    "@babel/core": "7.0.0-beta.47",
    "@babel/runtime": "7.0.0-beta.47",
    "@babel/plugin-proposal-decorators": "7.0.0-beta.47",
    "@babel/plugin-transform-classes": "7.0.0-beta.47",
    "@babel/plugin-transform-runtime": "7.0.0-beta.47",
    "babel-bridge": "^1.12.11",
    "babel-eslint": "^8.2.6",
    "babel-jest": "23.4.0",
    "babel-plugin-transform-decorators-legacy": "1.3.4",
    "babel-preset-react-native": "^5.0.2",
    "eslint": "^5.2.0",
    "eslint-config-airbnb-base": "^13.0.0",
    "eslint-plugin-import": "^2.13.0",
    "eslint-plugin-react": "^7.10.0",
    "eslint-plugin-react-native": "^3.2.1",
    "jest": "23.4.1",
    "jsc-android": "^224109.1.0",
    "prettier-eslint": "^8.8.2",
    "react-test-renderer": "16.4.1"
  },
  "jest": {
    "preset": "react-native",
    "transform": {
      "^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"
    }
  },
  "rnpm": {
    "assets": [
      "./src/assets/fonts/"
    ]
  }
}
```

**Comment by radik** [comment] 2018-09-05 11:18
@udarts Do you have this problem on Android?

**Comment by udarts** [comment] 2018-09-05 11:26
@radik no problem on android, seems ios related

here is my package.json

```` json
{
  "name": "MyApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "firebase": "^5.4.0",
    "lodash": "^4.17.10",
    "moment": "^2.22.2",
    "moment-timezone": "^0.5.21",
    "native-base": "^2.7.2",
    "node-quill-converter": "^0.3.1",
    "quill-delta-to-html": "^0.8.4",
    "random-string": "^0.2.0",
    "react": "16.4.2",
    "react-native": "0.56.0",
    "react-native-action-button": "^2.8.4",
    "react-native-bottom-toolbar": "^4.1.2",
    "react-native-checkbox-heaven": "^0.1.5",
    "react-native-communications": "^2.2.1",
    "react-native-datepicker": "^1.7.2",
    "react-native-drawer": "^2.5.0",
    "react-native-elements": "^0.19.1",
    "react-native-firebase": "^4.3.8",
    "react-native-i18n": "^2.0.15",
    "react-native-keyboard-spacer": "^0.4.1",
    "react-native-loading-spinner-overlay": "^0.5.2",
    "react-native-modal": "^6.5.0",
    "react-native-modal-picker": "0.0.16",
    "react-native-popup-dialog": "^0.15.0",
    "react-native-restart": "0.0.6",
    "react-native-root-toast": "^3.0.1",
    "react-native-side-menu": "^1.1.3",
    "react-native-simple-store": "^1.3.0",
    "react-native-splash-screen": "^3.1.1",
    "react-native-svg": "^6.5.2",
    "react-native-swipeout": "^2.3.6",
    "react-native-swiper": "^1.5.13",
    "react-native-switch-selector": "^1.1.8",
    "react-native-tableview-simple": "^0.17.5",
    "react-native-vector-icons": "^5.0.0",
    "react-native-webhtmlview": "0.0.3",
    "react-native-webview-bridge": "^0.33.0",
    "react-native-webview-quilljs": "^0.8.34",
    "react-navigation": "^2.11.2",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-devtools-extension": "^2.13.5",
    "redux-thunk": "^2.3.0",
    "toggle-switch-react-native": "^1.0.0"
  },
  "devDependencies": {
    "babel-jest": "23.4.0",
    "babel-preset-react-native": "5.0.2",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "react-devtools": "^3.2.3",
    "jest": "23.4.1",
    "react-test-renderer": "16.4.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
````

**Comment by radik** [comment] 2018-09-05 14:49
@udarts For me, it has exactly the same behavior on android (signed release apk): shortly crashes after start.
Also, it crashes in release mode on iOS:
```
react-native run-ios --configuration Release
```

**Comment by radik** [comment] 2018-09-05 18:49
@udarts I'm not sure, that this will help you, but I found a reason for my project.
Having "@babel/plugin-proposal-decorators" as plugin for babel cause crash of app in release mode.
After removing all `@observer` and `@observable` from `mobx` package my app is finally started in release mode. Here is the diff of .babelrc:

```sh
--- a/.babelrc
+++ b/.babelrc
@@ -1,13 +1,5 @@
 {
   "presets": [
     "react-native"
-  ],
-  "plugins": [
-    [
-      "@babel/plugin-proposal-decorators",
-      {
-        "legacy": true
-      }
-    ]
   ]
 }
```

This is not a proper solution, but at least I found a reason. Still working to figure out what to do.

@udarts Please, let me know if find anything related to issue.

**Comment by nicholasc** [comment] 2018-10-15 17:31
+1
I haven't tested because I have some many decorators, but I also get this error and use the legacy transform decorator plugin.

**Comment by nicholasc** [comment] 2018-10-19 14:33
Upgrading react-native from 0.57.1 to 0.57.3 "fixed" this for me.

**Comment by lenvonsam** [comment] 2018-12-08 05:45
I have faced same problem, any solution?
react-native 0.55.0
react 16.3.1

**Comment by webfalcon** [comment] 2018-12-15 06:52
Is anyone solved this problem?

**Comment by iLevye** [comment] 2019-01-20 16:01
I can not reproduce the issue but there is too much users facing it specially after iOS 12.1
I am using react-native@0.55.2

My packages:
```
    "create-hmac": "1.1.7",
    "crypto-js": "3.1.9-1",
    "firebase": "4.5.1",
    "native-base": "2.3.3",
    "react": "16.3.1",
    "react-native": "0.55.2",
    "react-native-admob": "2.0.0-beta.2",
    "react-native-cookies": "3.2.0",
    "react-native-device-info": "0.11.0",
    "react-native-fs": "2.11.15",
    "react-native-google-analytics-bridge": "5.3.3",
    "react-native-iap": "^2.4.0-beta6",
    "react-native-localization": "0.2.1",
    "react-native-md5": "1.0.0",
    "react-native-onesignal": "3.2.12",
    "react-native-progress-circle": "2.0.0",
    "react-native-prompt": "https://github.com/iLevye/react-native-prompt.git",
    "react-native-push-notification": "3.0.2",
    "react-native-rate": "1.0.8",
    "react-native-responsive-grid": "0.33.0",
    "react-native-router-flux": "4.0.0-beta.27",
    "react-native-swiper": "1.5.13",
    "react-native-twitter": "https://github.com/iLevye/react-native-twitter.git",
    "react-native-twitter-signin": "1.0.2",
    "react-native-vector-icons": "^5.0.0",
    "react-native-video": "3.1.0",
    "react-redux": "5.0.6",
    "recyclerlistview": "1.1.4",
    "redux": "3.7.2",
    "redux-thunk": "2.2.0",
    "rn-ios-user-agent": "1.0.0"
```

**Comment by iLevye** [comment] 2019-01-20 16:10
> Upgrading react-native from 0.57.1 to 0.57.3 fixed this for me.

@nicholasc can you confirm this today? Did you checked Xcode crash logs at these days?

![screen shot 2019-01-20 at 19 08 28](https://user-images.githubusercontent.com/1510974/51441824-d4d07d80-1ce6-11e9-9804-81671ac308d7.png)

**Comment by cihati** [comment] 2019-02-01 15:17
I see this with RN 0.57.5:

![image](https://user-images.githubusercontent.com/461998/52131353-78e5ed00-2634-11e9-935f-0993be5e077d.png)

**Comment by grabbou** [comment] 2019-03-19 12:33
Hello there 👋 this issue doesn't have a repro (which means, a react-native init-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗

**Comment by grabbou** [comment] 2019-03-19 12:34
Developers, be aware: RCTFatal appears in almost every stack trace you have on iOS, but it's not the original error message. It's just a utility that is supposed to print the error for you. 

Before commenting, make sure you check your stack trace and look for the original issue.

**Closed by grabbou** 2019-03-19 12:33 UTC
Labels: Platform: iOS, Type: Bug Report

**Comment by cihati** [comment] 2019-03-19 12:48
@grabbou what would be a meaningful way to dig deeper into errors like this?

**Comment by quantumpotato** [comment] 2019-06-25 01:07
Encountering this. No useful stacktrace provided.
