### ISSUE TITLE
[Android] measure not returning values unless element has onLayout property

### ISSUE THREAD

**Issue by oblador** [facebook/react-native#3282] opened 2015-10-08 12:18 UTC
I have something similar to this:

```
handleSomething: function() {
  this._root.measure((ox, oy, width, height, px, py) => {
    console.log({ox, oy, width, height, px, py});
  });
},
render: function() {
  return (<View ref={component => this._root = component}>...</View>);
}
```

This code works flawlessly on iOS, but on android the measure callback will always be called with `undefined` arguments  – unless I put an empty callback on the `onLayout` property.

**Comment by foghina** [comment] 2015-10-21 16:20
@oblador what happens if, instead of logging `arguments`, you log `ox`, `oy` etc.?

**Comment by oblador** [comment] 2015-10-21 16:22
@foghina: they log as `undefined`, logging `arguments` is just shorter to write.

**Comment by oblador** [comment] 2015-10-21 16:24
@foghina: in case you don't know of `arguments`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments

**Comment by foghina** [comment] 2015-10-21 16:38
@oblador I know about `arguments`, we just ran into this internally and it turned out `arguments` was wrong for some reason, but logging the arguments by name worked.

Can you try wrapping the measure call in `requestAnimationFrame`? E.g.:

```javascript
this.requestAnimationFrame(() => {
  this._root.measure((ox, oy, width, height, px, py) => {
    console.log(arguments);
  });
});
```

**Comment by ide** [comment] 2015-10-21 16:41
@foghina "arguments" in an arrow function refers to the enclosing non-arrow function's arguments (same rule as "this"). Maybe that was the issue you were seeing.

**Comment by foghina** [comment] 2015-10-21 16:54
@ide that does not explain why it works on iOS :-/

**Comment by ide** [comment] 2015-10-21 18:50
There was a timing change with how iOS does measurement that may have fixed this issue. Haven't really looked into it in detail, but it might be related? https://github.com/facebook/react-native/commit/aa62a5e4e016b67dc3f7dc902a18edbc88c867c4

**Comment by oblador** [comment] 2015-10-21 18:55
I've updated the issue to not confuse anybody. It works as expected on iOS for all I know, but not on android. Wasn't aware of arrow functions inheriting the `arguments` object, but it's unrelated to this issue.

**Comment by ide** [comment] 2015-10-21 18:57
@oblador does wrapping the call in a rAF callback help?

**Comment by oblador** [comment] 2015-10-21 19:00
@ide haven't tried, but don't really understand why it would make a difference. `handleSomething` is supposed to be a Touchable* callback.

**Comment by ide** [comment] 2015-10-21 19:01
Yeah you're probably right.

**Comment by marcshilling** [comment] 2016-02-08 21:16
I'm also experiencing this. Along with `onLayout`, I've found that settings `renderToHardwareTextureAndroid={true}` on the view also makes measure return values.

**Comment by chirag04** [comment] 2016-03-26 21:35
@oblador @marcshilling can you try `collapsable: false` prop on your view? Android may remove the view from hierarchy for optimization purpose.

I just ran into something similar. 

https://facebook.github.io/react-native/docs/view.html#content

**Comment by sodik82** [comment] 2016-04-27 09:56
I have same problem and can confirm that using `onLayout` or `collapsable={false}` helps

**Comment by udfalkso** [comment] 2016-05-20 20:07
@chirag04 collapsable: false helped for me, thanks.

**Comment by chirag04** [comment] 2016-05-20 20:43
@facebook-github-bot close

**Comment by facebook-github-bot-7** [comment] 2016-05-20 20:50
@chirag04 tells me to close this issue. If you think it should still be opened let us know why.

**Comment by eremzeit** [comment] 2016-07-08 21:03
FYI, I'm using 0.26.3 and this was still an issue.  I had to add an empty `onLayout` before `measure` would return integers instead of just undefined.

**Comment by nickmaxwell10** [comment] 2016-07-11 13:17
I am having trouble with this on iOS as well.

**Comment by eremzeit** [comment] 2016-07-18 21:25
Was this fixed in a more recent version?  Using the unrelated properties `onLayout` or `collapsable` to force this functionality seems to me to be a hack rather than a fix.  I know there are limited resources to fix things, but at least there could be something in the docs about it?

**Comment by JAStanton** [comment] 2016-08-08 00:12
@chirag04 you closed this but it's actually not resolved. 
1) There are no docs
2) There is no actual fix.

Also the y position (second argument) is always 0 if the element you are measure is in a scroll view. Joy.

**Comment by hey99xx** [comment] 2016-08-13 22:11
@facebook-github-bot open

**Comment by julien-rodrigues** [comment] 2016-09-29 20:41
I can confirm the bug is still here

**Comment by MattFoley** [comment] 2016-10-06 01:38
Also still seeing this issue, will report back with any findings.

**Comment by zoharlevin** [comment] 2016-10-13 11:18
this bug still exists

**Comment by chirag04** [comment] 2016-10-13 13:25
@zoharlevin @MattFoley  @julien-rodrigues Do you guys see this even after setting `collapsable:false` on your view?

**Comment by leecade** [comment] 2016-10-13 19:53
confirm that [v0.35.0]

**Comment by grabbou** [comment] 2016-10-15 15:52
Can be closed. `collapsable: false` fixes that one, just run into it.

**Comment by blackburnian** [comment] 2016-11-08 22:28
I still see the issue of y coming through as 0 for Android, even after setting `collapsable={false}` on the View.  Again, working fine in iOS.

@JAStanton I also tried setting `collapsable={false}` on the ScrollView up the tree, but that still did not help.

**Comment by marcshilling** [comment] 2016-11-14 22:20
@grabbou I have a situation that is not resolved with `collapsable`.

**Comment by minhmera** [comment] 2016-12-29 08:14
i am  using react native version 0.36 and got this issues on Android, but on iOS , it work well
here is my code , pls help me, many thanksthis.refs.field.measure((x, y, width, height, px, py) =>{
            console.log('----------   height   ',height)
 ``

**Comment by joturako** [comment] 2016-12-31 15:48
setting `collapsable={false}` on a `View` solved this problem for me. I'm on `0.39.2`

**Comment by dragonwong** [comment] 2017-01-16 14:26
@chirag04 `collapsable={false}` Thanks, it works!

**Comment by nhatho89** [comment] 2017-02-15 22:16
I was still experiencing the issue with collapsable={false}.

What fixed it for me was adding onLayout={() => {}} instead.

**Comment by wschurman** [comment] 2017-04-14 18:31
Using [`measureLayout`](http://facebook.github.io/react-native/releases/0.43/docs/nativemethodsmixin.html#measurelayout) (relative to specific node) seemed to solve this for me.

**Comment by Altusvdm** [comment] 2017-05-18 09:49
I was experiencing this issue on Views and managed to work around it by adding empty onLayout as suggested.

However now I am trying to measure a ScrollView and adding onLayout did not fix the issue. I managed to work around it by wrapping all the content of my ScrollView with a View, adding an empty onLayout to that View, and then measuring that View.

**Comment by luisfuertes** [comment] 2017-06-09 07:54
I have the same problem, but props arent undefined.

I have a listview with this rows:
``` 
  renderRow(rowData, sectionID, rowID) {
    return (
      <View
        style={{padding: 20, backgroundColor: rowData.color, marginHorizontal: 20, marginVertical: 10, alignItems: 'center'}}
        ref={(row) => this.rows[rowID] = row}
        collapsable={false}
        {...this.customPanResponder.panHandlers}
      >
        <Text>{rowData.text}</Text>
      </View>
    )
  }
```

With
``` 
    _.map(this.rows, row => {
          row.measure( (ox, oy, width, height, px, py) => console.log("ox: ", ox, " oy: ", oy, " height: ", height, " px: ", px, " py: ", py))
        })
```


On iOS measure logs: 
``` 
ox:  20  oy:  10  height:  57  px:  20  py:  74
ox:  20  oy:  87  height:  57  px:  20  py:  151
ox:  20  oy:  164  height:  57  px:  20  py:  228
``` 

On Android measure logs: 
```
ox:  0  oy:  0  height:  59  px:  20  py:  66
ox:  0  oy:  0  height:  59  px:  20  py:  145
ox:  0  oy:  0  height:  59  px:  20  py:  224
``` 

Why my oy on android is always 0?

**Comment by SteffeyDev** [comment] 2017-06-23 22:23
I just found that on iOS, measuring a Text component nested in another Text component results in all 0's as well.  Haven't tested on Android yet.  Also noted that onLayout on a nested Text component is never called, very strange.

**Comment by joturako** [comment] 2017-06-24 02:52
@SteffeyDev I think it have something to do with the way they render nested Text Component. Basically they used attributed text on the outermost Text element and all the nested ones are parsed to be merged into the parent as 1 large text item. That's how I think it's on iOS.

**Comment by SteffeyDev** [comment] 2017-06-24 03:07
@joturako That makes sense, and explains why I can't get layout information.  If I have a large body of text in a scrollview, how would you recommend I find the position of a smaller portion so that I can scroll there?  Or is there no way to do that?

**Comment by joturako** [comment] 2017-06-24 03:47
@SteffeyDev I think you have to write a custom component, for iOS for example you can look for more information on how to scroll a `UITextView` to a selection: `[textView scrollRangeToVisible:[textView.text rangeOfString:@"Lorem ipsum"]];`

**Comment by hramos** [comment] 2017-08-31 01:26
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Closed by hramos** 2017-08-31 01:26 UTC
Labels: Android, Icebox, Needs Response from Author, Ran Commands

**Comment by andriichernenko** [comment] 2018-06-13 08:19
Still hitting this issue when using `measureInWindow` with React Native 0.54.2.
