### ISSUE TITLE
navigator.geolocation.getCurrentPosition stop working after we add NSLocationAlwaysUsageDescription and NSLocationWhenInUseUsageDescription to plist.

### ISSUE THREAD

**Issue by sadeghipour** [facebook/react-native#19057] opened 2018-04-27 21:37 UTC
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.11.1
  Yarn: 1.6.0
  npm: Not Found
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.0 => 0.53.0
## Steps to Reproduce

@tarikkurucu and me are developing an application with pure react-native (not with expo) and yesterday we deploy our new version of application to App Store in order to test in TestFlight. after application uploaded to store we received a letter from Apple that we must add 2 keys to our .plist file as below:

> We identified one or more issues with a recent delivery for your app, "***********". Please correct the following issues, then upload again.
> 
> Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSLocationAlwaysUsageDescription key with a string value explaining to the user how the app uses this data.
> 
> Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSLocationWhenInUseUsageDescription key with a string value explaining to the user how the app uses this data.

 After we add keys to .plist file we figured out that **navigator.geolocation.getCurrentPosition**  stopped working.

After searching in Internet we couldn't find any solution and finally we write our native module.

## Expected Behavior

navigator.geolocation.getCurrentPosition must return user location after user allows to reach GPS. 

## Actual Behavior

navigator.geolocation.getCurrentPosition not fire up after call.

NativeLocationRequest.h:

      #import <React/RCTBridgeModule.h>
      @interface NativeLocationRequest : NSObject<RCTBridgeModule>
       @end

NativeLocationRequest.m:

    #import "NativeLocationRequest.h"
    #import <CoreLocation/CoreLocation.h>

    @implementation NativeLocationRequest
    RCT_EXPORT_MODULE();

    CLLocationManager *locationManager;

    RCT_EXPORT_METHOD(NativeLocationRequestStart)
    {
      
      if ([CLLocationManager locationServicesEnabled]) {
        
        switch ([CLLocationManager authorizationStatus]) {
          case kCLAuthorizationStatusDenied:
            locationManager = [[CLLocationManager alloc] init];
            locationManager.desiredAccuracy = kCLLocationAccuracyBest;
            //[locationManager requestAlwaysAuthorization];
            [locationManager requestWhenInUseAuthorization];
            
            break;
          case kCLAuthorizationStatusRestricted:
            
            locationManager = [[CLLocationManager alloc] init];
            locationManager.desiredAccuracy = kCLLocationAccuracyBest;
            //[locationManager requestAlwaysAuthorization];
            [locationManager requestWhenInUseAuthorization];
            
            break;
          case kCLAuthorizationStatusAuthorizedAlways:
            
            break;
          case kCLAuthorizationStatusAuthorizedWhenInUse:
            
            break;
          case kCLAuthorizationStatusNotDetermined:
            locationManager = [[CLLocationManager alloc] init];
            locationManager.desiredAccuracy = kCLLocationAccuracyBest;
            //[locationManager requestAlwaysAuthorization];
            [locationManager requestWhenInUseAuthorization];
            break;
          default:
            break;
        }
      } else {
        locationManager = [[CLLocationManager alloc] init];
        locationManager.desiredAccuracy = kCLLocationAccuracyBest;
        //[locationManager requestAlwaysAuthorization];
        [locationManager requestWhenInUseAuthorization];
        
      }
      
    }
    @end

**Comment by sadeghipour** [comment] 2018-04-29 10:02
Same result with fresh react-native init 

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.11.1
  Yarn: 1.6.0
  npm: 6.0.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3

**Comment by sfyfe31** [comment] 2018-05-17 01:02
I'm having the same issue after upgrading to RN 0.55.4
Without `NSLocationAlwaysUsageDescription` in `Info.plist`, rejected by Apple
With `NSLocationAlwaysUsageDescription` in `Info.plist`, `navigator.geolocation.getCurrentPosition` doesn't work

**Comment by sfyfe31** [comment] 2018-05-17 07:38
I think this is a recent change in Apple's binary submission checks, because after downgrading to 0.54.0, my builds are still being rejected for not including `NSLocationAlwaysUsageDescription in `Info.plist`. Even though I successfully submitted a binary on RN 0.54.0 a few days ago

**Comment by sfyfe31** [comment] 2018-05-17 07:57
Can confirm my RN 0.54.0 build was accepted in iTunes Connect with the following temporary change to `node_modules/react-native/Libraries/Geolocation/RCTLocationObserver.m`:

Before:

```
if ([[NSBundle mainBundle] objectForInfoDictionaryKey:@"NSLocationAlwaysUsageDescription"] &&
    [_locationManager respondsToSelector:@selector(requestAlwaysAuthorization)]) {
    [_locationManager requestAlwaysAuthorization];

    // On iOS 9+ we also need to enable background updates
    NSArray *backgroundModes  = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"UIBackgroundModes"];
    if (backgroundModes && [backgroundModes containsObject:@"location"]) {
      if ([_locationManager respondsToSelector:@selector(setAllowsBackgroundLocationUpdates:)]) {
        [_locationManager setAllowsBackgroundLocationUpdates:YES];
      }
    }
  } else if ([[NSBundle mainBundle] objectForInfoDictionaryKey:@"NSLocationWhenInUseUsageDescription"] &&
    [_locationManager respondsToSelector:@selector(requestWhenInUseAuthorization)]) {
    [_locationManager requestWhenInUseAuthorization];
  }
```

After:

```
// Request location access permission
  /*if ([[NSBundle mainBundle] objectForInfoDictionaryKey:@"NSLocationAlwaysUsageDescription"] &&
    [_locationManager respondsToSelector:@selector(requestAlwaysAuthorization)]) {
    [_locationManager requestAlwaysAuthorization];

    // On iOS 9+ we also need to enable background updates
    NSArray *backgroundModes  = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"UIBackgroundModes"];
    if (backgroundModes && [backgroundModes containsObject:@"location"]) {
      if ([_locationManager respondsToSelector:@selector(setAllowsBackgroundLocationUpdates:)]) {
        [_locationManager setAllowsBackgroundLocationUpdates:YES];
      }
    }
  } else */if ([[NSBundle mainBundle] objectForInfoDictionaryKey:@"NSLocationWhenInUseUsageDescription"] &&
    [_locationManager respondsToSelector:@selector(requestWhenInUseAuthorization)]) {
    [_locationManager requestWhenInUseAuthorization];
  }
```

**Comment by uuau99999** [comment] 2018-05-24 01:19
Same problem.  @sfyfe31  Thanks for your solution but is any workaround other than overwriting the RCTLocationObserver.m ?

**Comment by sadeghipour** [comment] 2018-05-24 09:27
@uuau99999 I preferred to get user location by hand made native component (NativeLocationRequest that I defined above) till react-native fix this.

**Comment by pavermakov** [comment] 2018-06-04 06:49
So, what's the final solution to the issue?

**Comment by pavermakov** [comment] 2018-06-04 07:45
@sfyfe31 Thank you! That worked for me.

**Comment by arosca** [comment] 2018-07-27 08:32
Had the same problem, got it working by adding all 3:

```
    <key>NSLocationWhenInUseUsageDescription</key>
    <string>Enabling location copy - in use</string>
    <key>NSLocationAlwaysUsageDescription</key>
    <string>Enabling location copy - always</string>
    <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
    <string>Enabling location copy - both</string>
```

According to the docs here: https://developer.apple.com/documentation/corelocation/choosing_the_authorization_level_for_location_services/requesting_always_authorization

> You are required to include the NSLocationWhenInUseUsageDescription and NSLocationAlwaysAndWhenInUseUsageDescription keys in your app's Info.plist file. (If your app supports iOS 10 and earlier, the NSLocationAlwaysUsageDescription key is also required.) If those keys are not present, authorization requests fail immediately.

**Comment by Palisand** [comment] 2018-08-24 14:27
The problem isn't with 0.54.0. The changes made in #5093 coupled with new Apple requirements are the issue. The PR comment states "If NSLocationAlwaysUsageDescription is set, NSLocationWhenInUseUsageDescription will be simply ignored". @sadeghipour might have left out part of the email he received from apple:

> Starting spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string.If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs.

So there's your answer right there and would explain why commenting out `objectForInfoDictionaryKey:@"NSLocationAlwaysUsageDescription"]` as @sfyfe31 has done would result in a successful App Store Connect submission.

**Comment by Palisand** [comment] 2018-08-24 17:35
@crsunik Your question is better suited for https://github.com/react-community/create-react-native-app. Unfortunately, expo does appear to use Location Service by default and disabling may not be possible at the moment. From expo docs:

>[Expo includes a bunch of APIs regardless of whether or not you are using them... We will make this customizable in the future, so you can trim down the size of your binaries.](https://docs.expo.io/versions/v29.0.0/introduction/why-not-expo#if-you-need-to-keep-your-app_)

See also: https://docs.expo.io/versions/latest/sdk/location#__next

**Comment by sadeghipour** [comment] 2018-08-29 05:47
@palisand

Unfortunately the is problem continues and not fixed yet.

https://forums.expo.io/t/rejected-from-app-store-missing-location-string/13029

**Comment by tclarke-scottlogic** [comment] 2018-08-29 13:15
@sadeghipour I don't appear to have access to that forum post, what does it say?

**Comment by tclarke-scottlogic** [comment] 2018-08-29 14:44
@Palisand Given the code in [this section](https://github.com/facebook/react-native/blob/5c2720b089dd0fb277771b0ac8b0e7788c493e5d/Libraries/Geolocation/RCTLocationObserver.m#L207-L221), would adding the purpose string mean wasteful behaviour would start occurring?

**Comment by Palisand** [comment] 2018-08-29 17:00
@sadeghipour I've updated my first comment in light of you having verified the contents of the email you received.

@tclarke-scottlogic I'm not exactly sure what you're asking. If you leave react-native untouched and do not want to receive a warning email from apple, a purpose string is required for the `NSLocation*` keys present in the section you posted (which I had included a previous comment). However, failing to provide the string apparently does not result in an app rejection (see @sadeghipour latest comment). If by wasteful behavior you mean including an extra `Always` permission rather than just `When In Use`, that should depend on what iOS version you're running and the inclusion of `NSLocationAlwaysAndWhenInUseUsageDescription`. I suggest that if you not using expo, are working on a shared codebase, have not forked or don't want to fork react-native, and all you want to do is access a user's location only while that user is using your app, you should use [patch-package](patch-package) and update _`RCTLocationObserver.m`_.

**Comment by DanGDroid** [comment] 2018-09-16 10:37
@Palisand 
if we need only 'when use' location
use 2 keys in `info.plist`:
`
         <key>NSLocationWhenInUseUsageDescription</key>
	<string>message</string>
	<key>NSLocationAlwaysAndWhenInUsageDescription</key>
	<string>message</string>`
it passes apple review.
you doent need `<key>NSLocationAlwaysUsageDescription</key>` this key is why `Geolocation` fails

**Comment by 12343954** [comment] 2018-10-27 14:40
> Had the same problem, got it working by adding all 3 keys in Info.plist:
> 
> ```
>     <key>NSLocationWhenInUseUsageDescription</key>
>     <string>Enabling location copy - in use</string>
>     <key>NSLocationAlwaysUsageDescription</key>
>     <string>Enabling location copy - always</string>
>     <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
>     <string>Enabling location copy - both</string>
> ```
> According to the docs here: https://developer.apple.com/documentation/corelocation/choosing_the_authorization_level_for_location_services/requesting_always_authorization
> 
> > You are required to include the NSLocationWhenInUseUsageDescription and NSLocationAlwaysAndWhenInUseUsageDescription keys in your app's Info.plist file. (If your app supports iOS 10 and earlier, the NSLocationAlwaysUsageDescription key is also required.) If those keys are not present, authorization requests fail immediately.

this way works for me! thank you !

**Comment by kelset** [comment] 2018-12-14 13:31
Uhm given that is seems that the solution is to add those string to the info.plist, do you feel that we can close this issue? Any reason why this should stay open? 🤔

**Closed** 2018-12-23 13:04 UTC
Labels: 🔷iOS

**Comment by pavermakov** [comment] 2019-05-27 11:45
@arosca Thank you so much!

**Comment by edrichhans** [comment] 2019-07-01 15:00
> @Palisand
> if we need only 'when use' location
> use 2 keys in `info.plist`:
> ` <key>NSLocationWhenInUseUsageDescription</key> <string>message</string> <key>NSLocationAlwaysAndWhenInUsageDescription</key> <string>message</string>`
> it passes apple review.
> you doent need `<key>NSLocationAlwaysUsageDescription</key>` this key is why `Geolocation` fails

Wow this actually solved it for me!

**Comment by jasperkuperus** [comment] 2019-07-17 06:57
Adding all 3 keys, as @arosca mentioned, works for me. The documentation however only urges new users to add `NSLocationWhenInUseUsageDescription` to the `Info.plist`:

https://facebook.github.io/react-native/docs/0.59/geolocation

Would be nice to have the official documentation reflect tge correct way to get started with geolocation. (@kelset?)

**Comment by kelset** [comment] 2019-07-17 16:54
I guess that you could submit a PR for that? Btw in case you missed, geolocation now lives in its own repo -> https://github.com/react-native-community/react-native-geolocation

**Comment by jasperkuperus** [comment] 2019-07-17 18:38
@kelset Ah, totally missed that. Submitted a PR, thanks!

**Comment by kelset** [comment] 2019-07-17 21:02
no thank you :3
