### ISSUE TITLE
RCTTouchHandler doesn't work properly with nested RCTRootViews

### ISSUE THREAD

**Issue by willorfang** [facebook/react-native#14395] opened 2017-06-08 10:25 UTC
This is the scenario:
There are two nested RCTRootViews: A & B。C is a normal RCTView within B.
Currently, when C is touched, two touch events are dispatched to C, with different <PageX, PageY> pairs. <PageX, PageY> is calculated according to A and B‘s coordinate respectively。

<img width="166" alt="2017-06-08 18 26 12" src="https://user-images.githubusercontent.com/5610207/26924356-108d154a-4c78-11e7-97d8-d18e400985ce.png">

I assume that C is a TouchOpacity instance. Because two different touch events are dispatched, onPressIn (JS) and onPressOut (JS) are invoked frequently, and onPress (JS) will not be called. Besides, the opacity change animation will not take effect.

For my understanding, if the event with A should not be dispatched, everything works right.

**Comment by hramos** [comment] 2017-06-08 16:08
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-08 16:08 UTC
