### ISSUE TITLE
transform.forEach is not a function, after init and run-ios

### ISSUE THREAD

**Issue by 12343954** [facebook/react-native#15228] opened 2017-07-27 09:03 UTC
try lots of times to init , and still like this,
who can help me , thank you so much !

![image](https://user-images.githubusercontent.com/1804003/28662338-5e765fec-72ec-11e7-87cb-465558f5a782.png)

### Environment

1. `react-native -v`:
```
**react-native-cli: 2.0.1
react-native: 0.46.4**
```

2. `node -v`: **v8.2.1**
3. `npm -v`: **5.3.0**
4. `yarn --version`:  **0.27.5**

**Comment by brunocascio** [comment] 2017-07-27 11:23
Try with node 6.11.

**Comment by hramos** [comment] 2017-07-27 16:45
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-07-27 16:45 UTC
