### ISSUE TITLE
Android app throws on launch with [SyntaxError: Unexpected token '='] no stack

### ISSUE THREAD

**Issue by jfpuissant** [facebook/react-native#30805] opened 2021-01-27 17:18 UTC
I open this issue to let maintainers know of the problem and share with other users my workaround to this hard to diagnose problem. iOS is not affected.

![Screenshot_1611767509](https://user-images.githubusercontent.com/22294137/106033361-f6348300-60d1-11eb-890f-be21916b3139.png)

## Description
If your code uses the operator `||=` or `&&=` your app will crash on launch on Android but work fine on iOS. I suppose the version of JSC shipped with Android does not support it. Here is the logcat for reference:

```
2021-01-27 18:15:23.927 6096-6631/lu.arhs.fleetback.dev E/unknown:ReactRootView: runApplication: call AppRegistry.runApplication
2021-01-27 18:15:24.220 6096-6630/lu.arhs.fleetback.dev E/unknown:ReactNative: CatalystInstanceImpl caught native exception
    com.facebook.react.devsupport.JSException: Unexpected token '='
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: com.facebook.jni.CppException: Unexpected token '='
    
    no stack
    	... 7 more
2021-01-27 18:15:24.221 6096-6630/lu.arhs.fleetback.dev E/unknown:ReactNative: Exception in native call from JS
    com.facebook.react.devsupport.JSException: Unexpected token '='
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: com.facebook.jni.CppException: Unexpected token '='
    
    no stack
    	... 7 more
2021-01-27 18:15:24.221 6096-6630/lu.arhs.fleetback.dev E/ReactNativeJNI: Attempting to call JS function on a bad application bundle: HMRClient.setup()
2021-01-27 18:15:24.222 6096-6630/lu.arhs.fleetback.dev E/unknown:ReactNative: CatalystInstanceImpl caught native exception
    java.lang.RuntimeException: Attempting to call JS function on a bad application bundle: HMRClient.setup()
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:919)
```

## React Native version:
System:
    OS: macOS 11.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 501.10 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: Not Found
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 26, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_275 - /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/javac
    Python: 2.7.16 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: ^4.10.0 => 4.13.1 
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce

1. Create a basic app with no dependencies.
2. Add a function like this `function foo() { const a = 1; const b =2; a ||= b }` anywhere
3. Install and launch the app on an Android device or emulator
 
## Expected Results
The app should not crash

## Snack, code example, screenshot, or link to a repository:
Add `function foo() { const a = 1; const b =2; a ||= b }` anywhere to your app.

## Suggestion
Not supporting the operators is ok but the error message could be more helpful.

**Comment by ecreeth** [comment] 2021-02-02 16:40
I can confirm this issue in this [snack](https://snack.expo.io/@ecreeth/grounded-bubblegum). Looks like metro doesn't have support to `Logical OR assignment (||=)` operator

Additional information can be found in [Babel](https://babeljs.io/docs/en/babel-plugin-syntax-logical-assignment-operators.html) and [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment)

**Comment by dulmandakh** [comment] 2021-02-04 02:45
I found that logical assignment is an ES2021 feature (https://v8.dev/features/tags/es2021), so you need to configure babel to make it work. Closing this because it's not a RN issue.

**Closed by dulmandakh** 2021-02-04 02:45 UTC
Labels: Bug, Needs: Issue Manager Attention, Platform: Android
