### ISSUE TITLE
Error on running  Couldn't find "Debug" build variant.

### ISSUE THREAD

**Issue by pipo151086** [facebook/react-native#36561] opened 2023-03-21 18:09 UTC
### New Version

0.72.0-rc.0

### Old Version

0.71.3

### Build Target(s)

Android

### Output of `react-native info`

info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-4770S CPU @ 3.10GHz
    Memory: 1.49 GB / 11.91 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20210110.135312.0 - C:\ProgramData\chocolatey\bin\watchman.EXE
  Managers:
    RubyGems: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 26, 28, 29, 30, 31, 33
      Build Tools: 28.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.1, 33.0.2
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google 
APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-33 | Google APIs Intel x86 Atom_64, android-33 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-221.6008.13.2211.9619390
    Visual Studio: 17.5.33424.131 (Visual Studio Professional 2022)
  Languages:
    Java: 11.0.2 - C:\Users\Miguel.Altamirano\AppData\Local\jdk-11.0.2\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.72.0-rc.0 => 0.72.0-rc.0
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

just create a new project

react-native init AwesomeProject --version 0.72.0-rc.0

cd AwesomeProject 

npx react-native run-android

RESULT>>>>>>>

error Failed to install the app. Couldn't find "Debug" build variant. Available variants are: .
info Run CLI with --verbose flag for more details.

**Comment by kelset** [comment] 2023-03-22 10:48
I can't reproduce your issue.

can you try again with:
1. using `npx react-native@latest init RN0720RC0 --version 0.72.0-rc.0` instead
2. using `yarn android` instead of npx react-native run-android?

**Comment by pipo151086** [comment] 2023-03-23 13:56
nothing
![image](https://user-images.githubusercontent.com/12957383/227226287-9a0b780f-2d38-4468-aaf3-8d5ae0b4892b.png)

**Comment by cortinico** [comment] 2023-03-31 15:44
This could also be CLI related 🤔

**Comment by mengtao-code** [comment] 2023-05-04 12:56
The same problem occurs

**Comment by pipo151086** [comment] 2023-05-04 14:07
still stuck here

**Comment by kelset** [comment] 2023-05-04 14:42
please try with 0.72 RC2, we just released it and contains a bunch of improvements for CLI

**Comment by pipo151086** [comment] 2023-05-04 15:17
> please try with 0.72 RC2, we just released it and contains a bunch of improvements for CLI

Noup....

cant make it work

![image](https://user-images.githubusercontent.com/12957383/236252292-f0875386-d42d-4cc6-9b04-ea278766167f.png)

**Comment by thymikee** [comment] 2023-05-05 13:42
@pipo151086 can you run `gradlew.bat tasks` locally and pass the output?

**Comment by pipo151086** [comment] 2023-05-05 14:50
@thymikee 
sure:
![image](https://user-images.githubusercontent.com/12957383/236492119-562c8d06-5490-4a81-844c-acb521bf854c.png)

**Comment by szymonrybczak** [comment] 2023-05-15 19:34
Hey, since this issue was fixed last week in https://github.com/react-native-community/cli/pull/1933 - we can close this issue. cc. @cortinico

**Comment by pipo151086** [comment] 2023-05-16 14:23
@szymonrybczak 

Not yet....

just about an hour ago they released the new version (11.3.0)  that contains the fix of the whitespaces....

https://github.com/react-native-community/cli/compare/v11.2.3...v11.3.0

please update the inner dependecy of cli from 11.2.3 to 11.3.0

**Comment by cortinico** [comment] 2023-05-17 17:06
I'm closing this as it's effectively fixed on our end. We're going to bump the CLI and you'll get the fix automatically. Please comment further if the issue is unsolved.

**Closed by cortinico** 2023-05-17 17:06 UTC
Labels: Platform: Windows, 💻CLI, Needs: Triage :mag:, Type: Upgrade Issue

**Comment by robprado-dev** [comment] 2023-06-04 00:46
@cortinico  I updated react-native-community/cli and I keep getting this error

**Comment by mordechaim** [comment] 2023-06-04 04:35
Use this patch:

**@react-native-community+cli-platform-android+11.2.3.patch**
```diff
diff --git a/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/listAndroidTasks.js b/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/listAndroidTasks.js
index 59fe1e2..89a0e54 100644
--- a/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/listAndroidTasks.js
+++ b/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/listAndroidTasks.js
@@ -37,7 +37,7 @@ const parseTasksFromGradleFile = (taskType, text) => {
   const instalTasks = [];
   const taskRegex = new RegExp(taskType === 'build' ? '^assemble|^bundle' : '^install');
   text.split('\n').forEach(line => {
-    if (taskRegex.test(line) && /(?!.*?Test)^.*$/.test(line)) {
+    if (taskRegex.test(line.trim()) && /(?!.*?Test)^.*$/.test(line.trim())) {
       const metadata = line.split(' - ');
       instalTasks.push({
         task: metadata[0],
```

**Comment by robprado-dev** [comment] 2023-06-04 05:17
> 

Great! It works. Thank you.

![image](https://github.com/facebook/react-native/assets/93489733/2d2f8f26-6d07-408b-9ca1-0d2d6da170f7)

**Comment by kelset** [comment] 2023-06-05 09:26
@mordechaim can you submit that as a PR to the CLI repo? or is a fix on their end already out?

**Comment by szymonrybczak** [comment] 2023-06-05 10:41
@kelset The fix is [already merged](https://github.com/react-native-community/cli/pull/1933) in CLI, and it is released in v11.3.0

**Comment by JoyCood** [comment] 2023-08-08 01:35
@

> 

i upgrade from 0.70.6 to 0.72.3, and the eact-native-community/cli version is 11.3.5, when run: yarn android, the error occur:
```
knight@192 awasome % yarn android
yarn run v1.22.19
$ react-native run-android
info Starting JS server...

info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 


error Failed to install the app. Couldn't find "Debug" build variant. Available variants are: .
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by dowon938** [comment] 2023-08-09 01:06
> The same problem occurs

**Comment by lauhon** [comment] 2023-08-10 15:17
@cortinico this issue still persists on my end.

I am working on a mac m1, maybe that makes a difference for some reason?

I tested the fix locally, my gradlew build is a success, but the new regex is not resulting in `true` for any of the lines.

**Comment by szymonrybczak** [comment] 2023-08-10 15:56
@lauhon please open new issue in https://github.com/react-native-community/cli and provide your setup.
