### ISSUE TITLE
Task failed with an exception.(A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction)

### ISSUE THREAD

**Issue by inshad7229** [facebook/react-native#35484] opened 2022-11-25 19:26 UTC
### Description

```
BUILD FAILED in 19s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     error: resource android:style/TextAppearance.Material not found.
     error: resource android:style/TextAppearance.Material.Body1 not found.
     error: resource android:style/TextAppearance.Material.Body2 not found.
     error: resource android:style/TextAppearance.Material.Button not found.
     error: resource android:style/TextAppearance.Material.Caption not found.
     error: resource android:style/TextAppearance.Material.Display1 not found.
     error: resource android:style/TextAppearance.Material.Display2 not found.
     error: resource android:style/TextAppearance.Material.Display3 not found.
     error: resource android:style/TextAppearance.Material.Display4 not found.
     error: resource android:style/TextAppearance.Material.Headline not found.
     error: resource android:style/TextAppearance.Material.Inverse not found.
     error: resource android:style/TextAppearance.Material.Large not found.
     error: resource android:style/TextAppearance.Material.Large.Inverse not found.
     error: resource android:style/TextAppearance.Material.Widget.PopupMenu.Large not found.
     error: resource android:style/TextAppearance.Material.Widget.PopupMenu.Small not found.
     error: resource android:style/TextAppearance.Material.Medium not found.
     error: resource android:style/TextAppearance.Material.Medium.Inverse not found.
     error: resource android:style/TextAppearance.Material.Menu not found.
     error: resource android:style/TextAppearance.Material.SearchResult.Subtitle not found.
     error: resource android:style/TextAppearance.Material.SearchResult.Title not found.


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 19s

    at makeError (/Users/inshadansari/Desktop/inshad/AwesomeProject/node_modules/execa/index.js:174:9)
    at /Users/inshadansari/Desktop/inshad/AwesomeProject/node_modules/execa/index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (/Users/inshadansari/Desktop/inshad/AwesomeProject/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Users/inshadansari/Desktop/inshad/AwesomeProject/node_modules/@react-native-community/cli/build/index.js:142:9)
info Run CLI with --verbose flag for more details.
```

### Version

0.70.6

### Output of `npx react-native info`

inshadansari@192 AwesomeProject % npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 156.63 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.1.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - /opt/homebrew/bin/npm
    Watchman: 2022.11.14.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

**Create new project(Macbook Pro M1)**
1:npx react-native init AwesomeProject

**Run project using command**
1:npx react-native run-android

**Note Also try to run via android studio same error and same code is working fine for ios**

### Snack, code example, screenshot, or link to a repository

<img width="1509" alt="Screenshot 2022-11-26 at 12 55 55 AM" src="https://user-images.githubusercontent.com/34847809/204044820-f92d672a-33c2-462b-825d-5e617caf9dcc.png">

**Comment by wangyupeng993** [comment] 2022-12-28 14:05
@cortinico // Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31

        if (System.properties['os.arch'] == "aarch64") {
            // For M1 Users we need to use the NDK 24 which added support for aarch64
            ndkVersion = "24.0.8215888"
        } else {
            // Otherwise we default to the side-by-side NDK version from AGP.
            ndkVersion = "21.4.7075529"
        }
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.2.1")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("de.undercouch:gradle-download-task:5.0.1")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        mavenCentral {
            // We don't want to fetch react-native from Maven Central as there are
            // older versions over there.
            content {
                excludeGroup "com.facebook.react"
            }
        }
        google()
        maven { url 'https://www.jitpack.io' }
    }
}

**Comment by wangyupeng993** [comment] 2022-12-28 14:09
`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31

        if (System.properties['os.arch'] == "aarch64") {
            // For M1 Users we need to use the NDK 24 which added support for aarch64
            ndkVersion = "24.0.8215888"
        } else {
            // Otherwise we default to the side-by-side NDK version from AGP.
            ndkVersion = "21.4.7075529"
        }
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.2.1")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("de.undercouch:gradle-download-task:5.0.1")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        mavenCentral {
            // We don't want to fetch react-native from Maven Central as there are
            // older versions over there.
            content {
                excludeGroup "com.facebook.react"
            }
        }
        google()
        maven { url 'https://www.jitpack.io' }
    }
}
`

**Comment by wangyupeng993** [comment] 2022-12-28 14:10
@cortinico 

`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31

        if (System.properties['os.arch'] == "aarch64") {
            // For M1 Users we need to use the NDK 24 which added support for aarch64
            ndkVersion = "24.0.8215888"
        } else {
            // Otherwise we default to the side-by-side NDK version from AGP.
            ndkVersion = "21.4.7075529"
        }
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.2.1")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("de.undercouch:gradle-download-task:5.0.1")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        mavenCentral {
            // We don't want to fetch react-native from Maven Central as there are
            // older versions over there.
            content {
                excludeGroup "com.facebook.react"
            }
        }
        google()
        maven { url 'https://www.jitpack.io' }
    }
}
`

**Comment by SMJ93** [comment] 2023-02-02 18:02
Also getting this issue since updating to React Native 0.71.2

**Comment by wangyupeng993** [comment] 2023-02-03 01:38
@SMJ93 Haven't found a solution yet

**Comment by SMJ93** [comment] 2023-02-03 10:04
@wangyupeng993 if I disable CodePush in `android/app/build.gradle` the app builds as expected:

```
// apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"
```

Looks like CodePush is not compatible with 0.71: https://github.com/microsoft/react-native-code-push/issues/2418

**Comment by wangyupeng993** [comment] 2023-02-06 07:03
@SMJ93 I'm a new project, and I haven't installed other dependencies, so that's it

**Comment by SMJ93** [comment] 2023-02-06 17:21
@wangyupeng993 did you try updating to 0.71?

**Comment by wangyupeng993** [comment] 2023-02-07 07:56
@SMJ93 Not yet, I'm still in 0.70.6

**Comment by wangyupeng993** [comment] 2023-02-13 17:28
@SMJ93 I updated to 0.71 still the same, I don't know wha

**Comment by Youssef-Durgham** [comment] 2023-02-18 15:12
same error here

**Comment by cortinico** [comment] 2023-02-20 12:42
Can we get a reproducer from someone?

**Comment by LayMui** [comment] 2023-03-11 08:29
I also have this same issue after upgrade RN to 0.71.4
 "react": "^18.2.0",
 "react-native": "^0.71.4",

here is my android/app/build.gradle 
```
apply plugin: "com.android.application"
apply plugin: "com.facebook.react"

/**
 * This is the configuration block to customize your React Native Android app.
 * By default you don't need to apply any configuration, just uncomment the lines you need.
 */
react {
    /* Folders */
    //   The root of your project, i.e. where "package.json" lives. Default is '..'
    // root = file("../")
    //   The folder where the react-native NPM package is. Default is ../node_modules/react-native
    // reactNativeDir = file("../node_modules/react-native")
    //   The folder where the react-native Codegen package is. Default is ../node_modules/@react-native/codegen
    // codegenDir = file("../node_modules/@react-native/codegen")
    //   The cli.js file which is the React Native CLI entrypoint. Default is ../node_modules/react-native/cli.js
    // cliFile = file("../node_modules/react-native/cli.js")

    /* Variants */
    //   The list of variants to that are debuggable. For those we're going to
    //   skip the bundling of the JS bundle and the assets. By default is just 'debug'.
    //   If you add flavors like lite, prod, etc. you'll have to list your debuggableVariants.
    // debuggableVariants = ["liteDebug", "prodDebug"]

    /* Bundling */
    //   A list containing the node command and its flags. Default is just 'node'.
    // nodeExecutableAndArgs = ["node"]
    //
    //   The command to run when bundling. By default is 'bundle'
    // bundleCommand = "ram-bundle"
    //
    //   The path to the CLI configuration file. Default is empty.
    // bundleConfig = file(../rn-cli.config.js)
    //
    //   The name of the generated asset file containing your JS bundle
    // bundleAssetName = "MyApplication.android.bundle"
    //
    //   The entry file for bundle generation. Default is 'index.android.js' or 'index.js'
    // entryFile = file("../js/MyApplication.android.js")
    //
    //   A list of extra flags to pass to the 'bundle' commands.
    //   See https://github.com/react-native-community/cli/blob/main/docs/commands.md#bundle
    // extraPackagerArgs = []

    /* Hermes Commands */
    //   The hermes compiler command to run. By default it is 'hermesc'
    // hermesCommand = "$rootDir/my-custom-hermesc/bin/hermesc"
    //
    //   The list of flags to pass to the Hermes compiler. By default is "-O", "-output-source-map"
    // hermesFlags = ["-O", "-output-source-map"]
}

/**
 * Set this to true to Run Proguard on Release builds to minify the Java bytecode.
 */
def enableProguardInReleaseBuilds = false

/**
 * The preferred build flavor of JavaScriptCore (JSC)
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US. Note that
 * this variant is about 6MiB larger per architecture than default.
 */
def jscFlavor = 'org.webkit:android-jsc:+'

android {
    ndkVersion rootProject.ext.ndkVersion

    compileSdkVersion rootProject.ext.compileSdkVersion

    namespace "com.nativeIntegration"
  
    defaultConfig {
        applicationId "com.nativeIntegration"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
    }
    splits {
        abi {
            reset()
            // enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            // include (*reactNativeArchitectures())
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
}

dependencies {

    // The version of react-native is set by the React Native Gradle Plugin
    implementation("com.facebook.react:react-android")

    implementation("androidx.swiperefreshlayout:swiperefreshlayout:1.0.0")

    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}")
    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.squareup.okhttp3', module:'okhttp'
    }

    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}")
    if (hermesEnabled.toBoolean()) {
        implementation("com.facebook.react:hermes-android")
    } else {
        implementation jscFlavor
    }
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)

```

**Comment by RickyMadava** [comment] 2023-04-03 17:39
Hello everyone,
I had the same problem and here is the solution I did, in any case it solved my problem: 
**The problem is that I made a wrong copy and paste in the folder "...../app/android/app/src/main/res".**
1. I double-checked and put back all the files and folders from before, carefully adding other necessary files and folders.
2. I restarted the command: ./gradlew assembleRelease
3. Build completed successfully

Here under some necessary captures 
"react": "18.2.0",
"react-native": "0.71.4",

**Before**
![image](https://user-images.githubusercontent.com/48678325/229584837-596eadbc-a44b-43e5-b8e1-70b1f2897984.png)
![image](https://user-images.githubusercontent.com/48678325/229584981-ee3e5062-c54d-4841-9fd7-bce90b039392.png)

**After**
![image](https://user-images.githubusercontent.com/48678325/229585265-996fb25f-8d63-4ef6-bd37-3a282b83d27b.png)


_I hope this will help you
Peace out_

**Comment by cortinico** [comment] 2023-04-05 10:50
Closing as I've been asking for a repro, which was never provided. So this issue is not actionable for us

**Closed by cortinico** 2023-04-05 10:50 UTC
Labels: Platform: Android, Needs: Author Feedback, Needs: Repro

**Comment by PulasthiAbey** [comment] 2024-02-14 05:03
I had a react native project in version `0.62` and i created a new project with the latest react native version and add all the dependencies & copy paste my codebase to the new project. Only the JavaScript code base. 

Here is my current RN info.

```
System:
  OS: macOS 12.7.3
  CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Memory: 346.08 MB / 16.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 18.16.1
    path: ~/.nvm/versions/node/v18.16.1/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 9.5.1
    path: ~/.nvm/versions/node/v18.16.1/bin/npm
  Watchman:
    version: 2023.12.04.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.2
      - iOS 16.2
      - macOS 13.1
      - tvOS 16.1
      - watchOS 9.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11255304
  Xcode:
    version: 14.2/14C18
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.4
    wanted: ^0.73.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

My `root build.gradle`

```
buildscript {
    ext {
        buildToolsVersion = "34.0.0"
        minSdkVersion = 21
        compileSdkVersion = 34
        targetSdkVersion = 34
        ndkVersion = "25.1.8937393"
        kotlinVersion = "1.8.0"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin")
        classpath("com.android.tools.build:gradle:4.1.2")
    }
}

apply plugin: "com.facebook.react.rootproject"

```


app level `build.gradle`

```
apply plugin: "com.android.application"
apply plugin: "org.jetbrains.kotlin.android"
apply plugin: "com.facebook.react"

react {}

android {
    ndkVersion rootProject.ext.ndkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion
    compileSdk rootProject.ext.compileSdkVersion

    namespace "com.xxx"
    defaultConfig {
        applicationId "com.variety_events"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
}

dependencies {
    // The version of react-native is set by the React Native Gradle Plugin
    implementation("com.facebook.react:react-android")
    implementation("com.facebook.react:flipper-integration")

    if (hermesEnabled.toBoolean()) {
        implementation("com.facebook.react:hermes-android")
    } else {
        implementation jscFlavor
    }
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)

```


Error message I am getting

```
* What went wrong:
Execution failed for task ':app:mergeLibDexDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingTaskDelegate
   > There was a failure while executing work items
      > A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingWorkAction
         > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
           Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
           Type org.reactnative.maskedview.BuildConfig is defined multiple times: node_modules/@react-native-community/masked-view/android/build/.transforms/878cd6189667619a98524ec3c202754f/transformed/classes/classes_dex/classes.dex, /Volumes/Macintosh HD - Data/Projects/Variety App/variety_events/node_modules/@react-native-masked-view/masked-view/android/build/.transforms/8e27f993ec9b5b873b42ba3299b6e240/transformed/classes/classes_dex/classes.dex
```

**Comment by PrasathRV** [comment] 2024-07-17 09:39
Hi @PulasthiAbey,
Please follow the Stackoverflow solution, it will fix the issue.
Stackoverflow link: [https://stackoverflow.com/questions/57606462/a-failure-occurred-while-executing-com-android-build-gradle-internal-tasks](https://stackoverflow.com/questions/57606462/a-failure-occurred-while-executing-com-android-build-gradle-internal-tasks)

**Comment by PrasathRV** [comment] 2024-07-17 09:49
Hi @cortinico ,
I got one email from the Google Play Console to update the target SDK version to a higher API version. In my case, it is version 34. So I updated the targetSdkVersion and compileSdkVersion to 34. Then I got the same issue, 

**Issue:** Task failed with an exception. (A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction)

What I did is, update the **targetSdkVersion to 34** and **compileSdkVersion to 31**. So the issue went off and the app runs properly in the Emulator 👍 

It will work for **React native versions 0.62, 0.63, 0.65**.

**Comment by Kolosafo** [comment] 2025-01-14 21:11
For my case, I was missing a file in the `android\app\src\main\res` folder. The first drawable folder under the directory was missing a file: `rn_edit_text_material.xml`
With the following content:

`<?xml version="1.0" encoding="utf-8"?>

<inset xmlns:android="http://schemas.android.com/apk/res/android"
       android:insetLeft="@dimen/abc_edit_text_inset_horizontal_material"
       android:insetRight="@dimen/abc_edit_text_inset_horizontal_material"
       android:insetTop="@dimen/abc_edit_text_inset_top_material"
       android:insetBottom="@dimen/abc_edit_text_inset_bottom_material"
       >

    <selector>
        
        <item android:state_enabled="false" android:drawable="@drawable/abc_textfield_default_mtrl_alpha"/>
        <item android:drawable="@drawable/abc_textfield_activated_mtrl_alpha"/>
    </selector>

</inset>
`


This is the complete path to this file now:  `/android/app/src/main/res/drawable/rn_edit_text_material.xml`
