### ISSUE TITLE
Creating a new app with npx react-native init exit with error 

### ISSUE THREAD

**Issue by EinarHm** [facebook/react-native#31961] opened 2021-08-05 02:01 UTC
## Description
 I create a new protect with npx react-native init <proyect name> then I run npx react-native run-ios and the following error occurs. Other projects run good
 
error: node_modules/react-native/Libraries/Image/ImageAnalyticsTagContext.js: Property body[6] of BlockStatement expected node to be of a type ["Statement"] but instead got "AssignmentExpression"

## React Native version:
System:
    OS: macOS 11.5.1
    CPU: (8) arm64 Apple M1
    Memory: 276.03 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.5.0 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.19.1 - /opt/homebrew/bin/npm
    Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3, 31.0.0
      System Images: android-30 | Google APIs Intel x86 Atom, android-31 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. npx react-native init <project name>
2.npx react-native run-ios

## Expected Results
Describe what you expected to happen.
Run the app in iOS Simulator
#

**Comment by pulnec** [comment] 2021-08-05 02:08
#31960 see please.

**Comment by lslsls0001** [comment] 2021-08-05 03:21
node_modules/react-native/Libraries/Components/ScrollView/ScrollView.js: Property body[42] of BlockStatement expected node to be of a type ["Statement"] but instead got "AssignmentExpression"

Same issue here, I follow exactly the instructions of RN web demonstration, no way to solve it. I also checked some 

> #31960 see please.
> the problem is due to a babel update that affected the RN project.

Hi pulnec, can you solve it? I follow exactly the RN webs demonstration, still same error show up, try all the ways I can, no useful so far.

**Comment by pulnec** [comment] 2021-08-05 03:27
Show your package.json

**Comment by KendallConsults** [comment] 2021-08-05 03:32
Came here to say I'm having the exact same problem

**Comment by lslsls0001** [comment] 2021-08-05 03:44
> Show your package.json

{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~42.0.1",
    "expo-status-bar": "~1.0.4",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
    "react-native-web": "~0.13.12"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0"
  },
  "private": true
}

This is the exactly package.json file after app created, nothing change, even if I change the @babel/core to other version, no useful

**Comment by ellismarjr** [comment] 2021-08-05 04:15
I'm facing same problem here with react native cli and expo

**Comment by danielrangelsa** [comment] 2021-08-05 05:23
Same problem here!

**Comment by HieuMinh1907** [comment] 2021-08-05 05:30
hi guys, same problem I had this problem while building App. I can't figure out how to fix it, can someone here help me?

error: node_modules/react-native/Libraries/Image/ImageAnalyticsTagContext.js: Property body[6] of BlockStatement expected node to be of a type ["Statement"] but instead got "AssignmentExpression"

**Comment by brentvatne** [comment] 2021-08-05 05:32
this is a known issue caused by a bug in a newly released version of babel. it will impact all new react-native and expo apps. you can resolve it with yarn resolutions in a new project:

```diff
--- a/package.json
+++ b/package.json
@@ -25,5 +25,8 @@
   },
   "jest": {
     "preset": "react-native"
+  },
+  "resolutions": {
+    "@babel/plugin-transform-react-display-name": "7.14.5"
   }
 }
```

see some discussion here:
- https://twitter.com/notbrent/status/1423152953876176897
- https://twitter.com/notbrent/status/1423153268423790594

**Comment by hmhm2292** [comment] 2021-08-05 05:41
@brentvatne where in the project do can i add the code you shared??

**Comment by brentvatne** [comment] 2021-08-05 05:44
package.json

**Comment by hmhm2292** [comment] 2021-08-05 05:46
@brentvatne thank you

**Comment by hmhm2292** [comment] 2021-08-05 05:51
@brentvatne would you know if by any chance this causes crashes in apps that is release in production?? or would this only affect people that are trying to build in development?

**Comment by danielrangelsa** [comment] 2021-08-05 05:59
> this is a known issue caused by a bug in a newly released version of babel. it will impact all new react-native and expo apps. you can resolve it with yarn resolutions in a new project:
> 
> ```diff
> --- a/package.json
> +++ b/package.json
> @@ -25,5 +25,8 @@
>    },
>    "jest": {
>      "preset": "react-native"
> +  },
> +  "resolutions": {
> +    "@babel/plugin-transform-react-display-name": "7.14.5"
>    }
>  }
> ```
> 
> see some discussion here:
> 
> * https://twitter.com/notbrent/status/1423152953876176897
> * https://twitter.com/notbrent/status/1423153268423790594

Thanks man, works for me!

**Comment by brentvatne** [comment] 2021-08-05 06:05
> @brentvatne would you know if by any chance this causes crashes in apps that is release in production?? or would this only affect people that are trying to build in development?
> 

it won't impact existing releases. if you're able to do a new release (the app compiles) then this particular issue will not cause any problems

**Comment by ssahn0806** [comment] 2021-08-05 06:11
It can be done by installing the project with low version of react native.

just like npx react-native init project_name --version 0.63.X

**Comment by Anmolnoor** [comment] 2021-08-05 06:17
:: Solution ::

Just copy the @Babel from an Old Project and Replace it. In Node_module

or download ir from here

**Comment by ldh1428a** [comment] 2021-08-05 07:31
why babel making it so hard on me..... 😢 😢 😢

**Comment by kelset** [comment] 2021-08-05 08:42
Closing this in favour of: https://github.com/facebook/react-native/issues/31960

**Closed by kelset** 2021-08-05 08:42 UTC
Labels: Impact: Regression, JavaScript, Needs: Attention, Needs: Triage :mag:
