### ISSUE TITLE
Suddenly "CFBundleIdentifier" Does Not Exist

### ISSUE THREAD

**Issue by sospedra** [facebook/react-native#12080] opened 2017-01-26 15:31 UTC
```
The following build commands failed:
	CompileC /Users/mars/code/mobile-apps/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTPlatform.o Base/RCTPlatform.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/ulabox.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/ulabox.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

Versions:
* Tried node: boron and 7.4.0
* react-native 0.40.0
* watchman 4.1.0

Tried:
* `watchman watch-del-all`
* `npm start -- --reset-cache`
* `rm -rf project/ && git clone project && yarn`
* This: https://github.com/facebook/react-native/issues/11265
* This: https://github.com/facebook/react-native/issues/10545
* And aaaaall of this: https://github.com/facebook/react-native/issues/7308

**Comment by sospedra** [comment] 2017-01-26 15:31
What surprise the most is that you actually closed those 3 issues :/

**Comment by sospedra** [comment] 2017-01-26 15:35
Finally, my special discovery. All the errors posted are nothing but a chained massive destruction. The origin is here:

```
/Users/mars/code/mobile-apps/node_modules/react-native/React/Views/RCTTabBarItem.m:111:12: error: property 'badgeColor' not found on object of type 'UITabBarItem *'
  _barItem.badgeColor = bagdeColor;
           ^
1 error generated.
```

**Comment by ericvicenti** [comment] 2017-01-26 16:59
Does that mean you found the problem? How can the error be reproduced?

**Comment by charlle** [comment] 2017-01-26 20:01
@sospedra can you tell me where this file, ulabox.app, is?  
Was it in this folder?
And do you have an extra "Build" folder?
ios/build/`Build`/Products/Debug-iphonesimulator/ulabox.app

**Comment by sospedra** [comment] 2017-01-26 22:16
I guess `ulabox.app` it's an autogenerated file. Because I didn't added to the project myself.

I netiher add a `Build` directory at any time. Not manually.

**Comment by rh389** [comment] 2017-01-27 18:21
Looking at the line in `RCTTabBarItem.m` I guess this was triggered by an iOS SDK update on your machine? The offending line is preprocessed out unless building against iOS >= 10.0, when [UITabBarItem.badgeColor](https://developer.apple.com/reference/uikit/uitabbaritem/1648567-badgecolor) was introduced.

What's weird is that the preprocessor guard is meant to prevent exactly this error and I can't see anything wrong with it. It'd be interesting to know what SDK version you were using before you updated Xcode but it's probably too late now.

**Comment by charlle** [comment] 2017-01-27 20:24
@sospedra ulabox.app is your actually iOS app that Xcode builds for you.  The Build directory gets added when your xCode project goes from `project` to `workspace`.
xCode project = build/Products/Debug...
xCode workspace = build/Build/Products/Debug...
As apps evolve from project to workspace, xCode will build the directories and drop the app in them.  Unfortunately React Native has the path to your app, ulabox.app, hardcoded in their runIOS.js file, so if xCode moves it, then your app will break.

**Comment by WaterEye0o** [comment] 2017-02-13 07:47
@sospedra are you resolve problem?

**Comment by ericvicenti** [comment] 2017-03-06 01:59
So it looks like this issue can be resolved by updating Xcode?

Closing for now, but if anybody has a complete description of the issue, and repro steps, please file it as a new issue

**Closed by ericvicenti** 2017-03-06 01:59 UTC

**Comment by sospedra** [comment] 2017-03-07 15:57
@WaterEye0o as me and @ericvicenti  mentioned bumping Xcode version seems to fix the issue

**Comment by Ethan0007** [comment] 2017-06-16 08:58
@sospartan  sir, what xcode version are you using right now? I'm having the same issue.

**Comment by florismettey** [comment] 2017-06-27 12:04
I found how to solve the issue: do NOT use space in your project path! 🎉  😄

**Comment by Ethan0007** [comment] 2017-06-27 13:26
@florismettey sir, its not like that, i think the issue is the XCODE version.

**Comment by evaldasjab** [comment] 2017-07-01 15:41
I had the same error, using Xcode 7.2.1.

I had to comment out these lines causing build failures, to run my SimpleApp.xcodeproj in Xcode: 
- `case UIUserInterfaceIdiomCarPlay: return @"carplay";` in RCTPlatform.m
- `self.barItem.badgeColor = badgeColor;` in RCTTabBarItem.m
- `_tabController.tabBar.unselectedItemTintColor = unselectedItemTintColor;` in RCTTabBar.m
- `activityViewController.completionWithItemsHandler = ...` in RCTProfile.m

Now the app also opens in the virtual device with `react-native run-ios` in Terminal.

Versions:
"react": "16.0.0-alpha.12",
"react-native": "0.45.1"

**Comment by tharakabimal** [comment] 2017-07-19 08:26
Here's what I get.

     Node v8.0.0
     react-native": 0.46.3
     XCode Version 8.3.3 (8E3004b)

when I run `react-native run-ios --simulator="iPhone 7"` I get the following error

<br/>

    === BUILD TARGET third-party OF PROJECT React WITH CONFIGURATION Debug ===

    Check dependencies


    ** BUILD FAILED **


    The following build commands failed:
	CompileC /Users/tharaka/Documents/Projects/Abiling/AbilingApp/ios/build/Build/Intermediates/RCTText.build/Debug-iphonesimulator/RCTText.build/Objects-normal/x86_64/RCTTextView.o RCTTextView.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    (1 failure)

    Installing build/Build/Products/Debug-iphonesimulator/AbilingApp.app
    An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
    Failed to install the requested application
    The bundle identifier of the application could not be determined.
    Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
    Print: Entry, ":CFBundleIdentifier", Does Not Exist

    Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-
    iphonesimulator/AbilingApp.app/Info.plist
    Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by hramos** [comment] 2017-08-04 06:53
Duplicate of #14423

**Comment by sospedra** [comment] 2017-09-15 16:00
More like the other one is the duplicate 🤔 
However, issue still rising sometimes
