### ISSUE TITLE
after upgrading to version 0.76.0, the application began to weigh 2 times more

### ISSUE THREAD

**Issue by valery-lavrik** [facebook/react-native#47222] opened 2024-10-27 11:01 UTC
### Description

after updating to 0.76.0, the application began to weigh 2 times more.
since version 0.74.0, the weight of the application was 39 mb.  updated to 0.76.0 - the size of the application has become 79mb

### Steps to reproduce

./gradlew clean &&   ./gradlew assembleRelease 

### React Native Version

0.76.0

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
$ npx react-native info
info Fetching system and libraries information...
System:
  OS: Windows 11 10.0.22631
  CPU: (16) x64 13th Gen Intel(R) Core(TM) i7-13620H
  Memory: 3.90 GB / 15.71 GB
Binaries:
  Node:
    version: 20.14.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: C:\Program Files (x86)\Yarn\bin\yarn.CMD
  npm:
    version: 10.7.0
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-241.15989.150.2411.11948838
  Visual Studio: Not Found
Languages:
  Java:
    version: 17.0.11
    path: /c/Program Files/Microsoft/jdk-17.0.11.9-hotspot/bin/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Stacktrace or Logs

```text
Package.jso:

{
    "name": "my_app",
    "version": "2.5.19",
    "private": true,
    "scripts": {
        "android": "react-native run-android --active-arch-only",
        "ios": "react-native run-ios",
        "lint": "eslint .",
        "start": "react-native start",
        "test": "jest"
    },
    "dependencies": {
        "@react-native-async-storage/async-storage": "^2.0.0",
        "@react-native-community/netinfo": "^11.4.1",
        "@react-native-community/slider": "^4.5.5",
        "@react-native-firebase/analytics": "^21.2.0",
        "@react-native-firebase/app": "^21.2.0",
        "@react-native-firebase/crashlytics": "^21.2.0",
        "@react-native-firebase/messaging": "^21.2.0",
        "@react-native-firebase/storage": "^21.2.0",
        "@react-native-masked-view/masked-view": "^0.3.1",
        "@react-navigation/drawer": "^6.7.2",
        "@react-navigation/native": "^6.1.18",
        "@react-navigation/native-stack": "^6.11.0",
        "axios": "^1.7.7",
        "manage-external-storage": "^0.1.3",
        "moment": "^2.30.1",
        "qs": "^6.13.0",
        "react": "18.3.1",
        "react-native": "0.76.0",
        "react-native-blob-util": "^0.19.11",
        "react-native-document-picker": "^9.3.1",
        "react-native-gesture-handler": "^2.20.2",
        "react-native-photo-manipulator": "^1.8.1",
        "react-native-reanimated": "^3.16.1",
        "react-native-safe-area-context": "^4.11.1",
        "react-native-screens": "^3.35.0",
        "react-native-system-navigation-bar": "^2.6.4",
        "react-native-vector-icons": "^10.2.0",
        "react-native-webview": "^13.12.3",
        "yandex-mobile-ads": "^0.1.1"
    },
    "devDependencies": {
        "@babel/core": "^7.26.0",
        "@babel/preset-env": "^7.26.0",
        "@babel/runtime": "^7.26.0",
        "@react-native-community/cli": "15.0.0",
        "@react-native-community/cli-platform-android": "15.0.0",
        "@react-native-community/cli-platform-ios": "15.0.0",
        "@react-native/babel-preset": "0.76.0",
        "@react-native/eslint-config": "0.76.0",
        "@react-native/metro-config": "0.76.0",
        "@react-native/typescript-config": "0.76.0",
        "@tsconfig/react-native": "^3.0.5",
        "@types/jest": "^29.5.14",
        "@types/react": "^18.3.12",
        "@types/react-test-renderer": "^18.3.0",
        "babel-jest": "^29.7.0",
        "eslint": "^9.13.0",
        "jest": "^29.7.0",
        "prettier": "3.3.3",
        "react-test-renderer": "18.3.1",
        "typescript": "5.6.3"
    },
    "engines": {
        "node": ">=18"
    }
}
```

### Reproducer

https://github.com/facebook/react-native

**Comment by migueldaipre** [comment] 2024-10-27 15:11
Hey @valery-lavrik, can you share a reproducer with minimal dependencies?

The issue here could be your project's dependencies.

**Comment by cortinico** [comment] 2024-10-28 03:57
> since version 0.74.0, the weight of the application was 39 mb. updated to 0.76.0 - the size of the application has become 79mb

Also how are you measuring the size of your application? @valery-lavrik ?

**Comment by valery-lavrik** [comment] 2024-10-28 05:22
> > since version 0.74.0, the weight of the application was 39 mb. updated to 0.76.0 - the size of the application has become 79mb
> 
> Also how are you measuring the size of your application? @valery-lavrik ?

just checking the size of the apk file after the build

**Comment by valery-lavrik** [comment] 2024-10-28 05:24
> Hey @valery-lavrik, can you share a reproducer with minimal dependencies?
> 
> The issue here could be your project's dependencies.

I thought that it might be not only react-native, but also the packages that I had to update to get the application to start. Do you happen to know how to view which of the packages in package.how much space does json take up in the apk file?  I can't think of a way right away...

**Comment by migueldaipre** [comment] 2024-10-28 10:54
> > Hey @valery-lavrik, can you share a reproducer with minimal dependencies?
> > 
> > The issue here could be your project's dependencies.
> 
> I thought that it might be not only react-native, but also the packages that I had to update to get the application to start. Do you happen to know how to view which of the packages in package.how much space does json take up in the apk file?  I can't think of a way right away...

You can compare your apk in the Android Studio [Apk Analyzer](https://developer.android.com/studio/debug/apk-analyzer).

**Comment by valery-lavrik** [comment] 2024-10-28 12:13
> > > Hey @valery-lavrik, can you share a reproducer with minimal dependencies?
> > > The issue here could be your project's dependencies.
> > 
> > 
> > I thought that it might be not only react-native, but also the packages that I had to update to get the application to start. Do you happen to know how to view which of the packages in package.how much space does json take up in the apk file?  I can't think of a way right away...
> 
> You can compare your apk in the 

https://github.com/user-attachments/assets/747cf4fd-143f-48ce-9aa5-71d6297b4aac

Android Studio [Apk Analyzer](https://developer.android.com/studio/debug/apk-analyzer).

It doesn't work for some reason...  What am I doing wrong?  (attached video)

**Comment by migueldaipre** [comment] 2024-10-28 12:53
> > > > Hey @valery-lavrik, can you share a reproducer with minimal dependencies?
> > > > The issue here could be your project's dependencies.
> > > 
> > > 
> > > I thought that it might be not only react-native, but also the packages that I had to update to get the application to start. Do you happen to know how to view which of the packages in package.how much space does json take up in the apk file?  I can't think of a way right away...
> > 
> > 
> > You can compare your apk in the
> 
>  2024-10-28.151125.mp4 
> Android Studio [Apk Analyzer](https://developer.android.com/studio/debug/apk-analyzer).
> 
> It doesn't work for some reason... What am I doing wrong? (attached video)

You need to select the previous apk and then the latest one.

**Comment by valery-lavrik** [comment] 2024-10-28 14:06
> > > > > Hey @valery-lavrik, can you share a reproducer with minimal dependencies?
> > > > > The issue here could be your project's dependencies.
> > > > 
> > > > 
> > > > I thought that it might be not only react-native, but also the packages that I had to update to get the application to start. Do you happen to know how to view which of the packages in package.how much space does json take up in the apk file?  I can't think of a way right away...
> > > 
> > > 
> > > You can compare your apk in the
> > 
> > 
> > 2024-10-28.151125.mp4
> > Android Studio [Apk Analyzer](https://developer.android.com/studio/debug/apk-analyzer).
> > It doesn't work for some reason... What am I doing wrong? (attached video)
> 
> You need to select the previous apk and then the latest one.

What do you mean, the previous one?  I have one apk file and that's it...

**Comment by migueldaipre** [comment] 2024-10-28 14:09
@valery-lavrik You need to select the apk generated in version v0.74.0 (39 mb) and then the new apk generated in version v0.76.0

**Comment by valery-lavrik** [comment] 2024-10-28 15:24
> @valery-lavrik You need to select the apk generated in version v0.74.0 (39 mb) and then the new apk generated in version v0.76.0

But this is not a comparison of two files, but an analysis of one. There's clearly something wrong here...

Anyway, I found an online tool that showed me this picture
![image](https://github.com/user-attachments/assets/87656fde-6c84-4b91-91d2-de11a7a539fc)
x86 I tried to open
![image](https://github.com/user-attachments/assets/5228bddb-d395-48eb-94c3-a0e9972737ca)

It looks like it's about react-native. But I don't understand what it is yet.

**Comment by valery-lavrik** [comment] 2024-10-28 15:26
![image](https://github.com/user-attachments/assets/79f48beb-d2b8-46e8-8322-0f38094278f4)
Here is a comparison of the two versions

**Comment by cortinico** [comment] 2024-10-29 11:53
> But this is not a comparison of two files, but an analysis of one. There's clearly something wrong here...

I believe this is introduced by AGP 8.3 as reported by other users here:
https://issuetracker.google.com/issues/330756859

You can verify this by upgrading to 0.75 instead of 0.76.

The answer is that you can't just compare the disk size of the APKs as the APK content get compressed differently between different AGP versions (which we bump between RN versions).

I've used the official APK analyser from Google and those are the results of the difference between versions. The delta seems to be in ~10Mb added (which is still a lot, but not a 2x increase).

![Screenshot 2024-10-29 at 11 51 44](https://github.com/user-attachments/assets/fe25e6b9-3599-417c-926a-fc14b3a48795)

Also I see you ship a universal APK which is not recommended if you're concerned on APK size. You should instead ship an AAB so the user will download only the needed architecture.

**Comment by valery-lavrik** [comment] 2024-10-29 13:59
> > But this is not a comparison of two files, but an analysis of one. There's clearly something wrong here...
> 
> I believe this is introduced by AGP 8.3 as reported by other users here: https://issuetracker.google.com/issues/330756859
> 
> You can verify this by upgrading to 0.75 instead of 0.76.
> 
> The answer is that you can't just compare the disk size of the APKs as the APK content get compressed differently between different AGP versions (which we bump between RN versions).
> 
> I've used the official APK analyser from Google and those are the results of the difference between versions. The delta seems to be in ~10Mb added (which is still a lot, but not a 2x increase).
> 
> ![Screenshot 2024-10-29 at 11 51 44](https://private-user-images.githubusercontent.com/3001957/381110625-fe25e6b9-3599-417c-926a-fc14b3a48795.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMTAyNjUsIm5iZiI6MTczMDIwOTk2NSwicGF0aCI6Ii8zMDAxOTU3LzM4MTExMDYyNS1mZTI1ZTZiOS0zNTk5LTQxN2MtOTI2YS1mYzE0YjNhNDg3OTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjlUMTM1MjQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODc5OTBhOWQ3NzU5NjliNjVjOTNhYTA1Y2FmYTQ5YmYyZGY1YTllNTM2YWQwODM4NjI0ZGE2NDQ2NTI0NGE4MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.KLn_3BRNTcvlThJWBh7zhso29gPhOjsDnKxq_eH1POg)
> 
> Also I see you ship a universal APK which is not recommended if you're concerned on APK size. You should instead ship an AAB so the user will download only the needed architecture.

what can I do in the end if I want to use RN 0.76.0 and still not lose the file size?  Any ideas?  (I can't use aab for various reasons)

**Comment by cortinico** [comment] 2024-10-29 15:06
> what can I do in the end if I want to use RN 0.76.0 and still not lose the file size? Any ideas?

Can you try to upgrade to 0.75.x and report what's the size difference?

**Comment by NickGerleman** [comment] 2024-10-29 16:29
Note that, minSdk bump changed default behavior of `extractNativeLibs`. On old version of Android, native binaries in APK were compressed, but then during installation, Android would decompress them into a new copy, and you would end up locally with two copies of each binary. Google changed the default to instead ship uncompressed native binaries, because despite the larger looking APK, it takes less space on the actual device.

**Comment by valery-lavrik** [comment] 2024-10-30 06:28
> > what can I do in the end if I want to use RN 0.76.0 and still not lose the file size? Any ideas?
> 
> Can you try to upgrade to 0.75.x and report what's the size difference?

I conducted an experiment with assemblies:

0.73.5 - 35mb - https://disk.yandex.ru/d/YpF1K_DXu1BstA
0.75.4 - 83.9mb - https://disk.yandex.ru/d/wgp8iIv5jdRPmA
0.76.0 - 79.4mb - https://disk.yandex.ru/d/DBgH6SauAP16ZQ

It seems that something happened in version 75 that greatly increased the size of the application. but it is unclear what exactly...

**Comment by cortinico** [comment] 2024-10-30 11:20
> 0.73.5 - 35mb - [disk.yandex.ru/d/YpF1K_DXu1BstA](https://disk.yandex.ru/d/YpF1K_DXu1BstA)
> 0.75.4 - 83.9mb - [disk.yandex.ru/d/wgp8iIv5jdRPmA](https://disk.yandex.ru/d/wgp8iIv5jdRPmA)
> 0.76.0 - 79.4mb - [disk.yandex.ru/d/DBgH6SauAP16ZQ](https://disk.yandex.ru/d/DBgH6SauAP16ZQ)

In your original post you mentioned:

> since version 0.74.0, the weight of the application was 39 mb.

But here you point out to 0.73.5, what is the right version you're starting from @valery-lavrik?

Anyway as I already shared above, the way how things are compressed inside the APK changed due to AGP 8.3 (shipped in 0.75).
The reccomendation is to use AAB, but if you can't my suggestion is to either:
1. Play with the `extractNativeLibs` as @NickGerleman suggested.
2. Create a split APK (one per architecture).
3. Attempt to downgrade AGP to 8.2 (you can do so by patch-packaging the `libs.versions.toml` file inside `@react-native/gradle-plugin`.

Ultimately, this is a problem with Android and not with React Native itself so it might be worth raising an issue with the Google Issue Tracker.

**Comment by valery-lavrik** [comment] 2024-10-30 12:02
> But here you point out to 0.73.5, what is the right version you're starting from @valery-lavrik?

The fact is that I've been playing with different versions of react-native and related packages for 3 days now. Probably, the versions of additional packages have changed in today's build, but this does not change the essence.

In any case, I understood the reason, and I will try to follow your recommendations. Thanks for the help!

**Comment by cortinico** [comment] 2024-10-30 23:35
> In any case, I understood the reason, and I will try to follow your recommendations. Thanks for the help!

I'm closing this as there is nothing to fix inside React Native. Feel free to report back if you find a solution that could also help others 👍

**Closed by cortinico** 2024-10-30 23:35 UTC
Labels: Needs: Repro, Needs: Attention

**Comment by valery-lavrik** [comment] 2024-10-31 07:43
Just for information, if anyone comes across my problem.

Experimenting with the parameter

 ```android:extractNativeLibs="true"```

I managed to reduce the size of the apk file
android:extractNativeLibs="false" - 79mb
android:extractNativeLibs="true" - 37mb


I studied what this parameter means and if I understood everything correctly, it should have been the other way around but not. But testing has shown the opposite. I must have misunderstood something. Well, that's fine! the main thing is that I managed to reduce the size of the apk file

**Comment by FawadAhmad007** [comment] 2024-12-10 13:25
It's working 

> Just for information, if anyone comes across my problem.
> 
> Experimenting with the parameter **extractNativeLibs**
> 
> I managed to reduce the size of the apk file android:extractNativeLibs="false" - 79mb android:extractNativeLibs="true" - 37mb
> 
> I studied what this parameter means and if I understood everything correctly, it should have been the other way around but not. But testing has shown the opposite. I must have misunderstood something. Well, that's fine! the main thing is that I managed to reduce the size of the apk file

It's working.
Thank you @valery-lavrik

**Comment by NickGerleman** [comment] 2024-12-10 20:35
The above flag reduces APK size, but will make the app larger on device, and is discouraged by Google for a reason. I would not use it blindly.

**Comment by valery-lavrik** [comment] 2024-12-11 06:39
> The above flag reduces APK size, but will make the app larger on device, and is discouraged by Google for a reason. I would not use it blindly.

Can this affect the braking in the app?  Lags when changing the screen orientation, rendering by steps, etc.

**Comment by Topiya** [comment] 2025-06-05 08:28
@valery-lavrik 
Did you find any solution to reduce apk size?

**Comment by Topiya** [comment] 2025-06-05 08:28
@valery-lavrik
Can you please let me know if you find any solution to reduce apk size?
