### ISSUE TITLE
fetch problem

### ISSUE THREAD

**Issue by tqqttq** [facebook/react-native#8139] opened 2016-06-16 01:57 UTC
```js
fetch(path, {
            method,
            headers: {
              'Accept': 'application/json',
              'Content-Type': 'application/json',
            },
            body: JSON.stringify(data || {})
          }).then((response) => { 
            return response.text() 
          }).then((responseText) => {
            console.log('responseText===>', responseText)
            resolve(JSON.parse(responseText))
          })
```
the code [console.log('responseText===>', responseText)] can not run somethimes when remote js debugging

**Comment by satya164** [comment] 2016-06-16 07:44
Can you post a reproducible example?

**Comment by DanielMSchmidt** [comment] 2016-06-16 15:35
And could you add the server response?

**Comment by tqqttq** [comment] 2016-06-17 03:28
can get response when i trun off debug

**Comment by eremzeit** [comment] 2016-06-21 03:50
I have a similar problem that might be the same thing.  When using `fetch` while remote debugging is turned on the promise returned by `fetch` doesn't get resolved until I tap the screen.  This does *not* happen while not remote debugging.  A couple thoughts come to mind on what it could be:

1) a race condition with event processing the debugging bridge
2) something to do with whether you're using the native chrome `fetch` or the `fetch` polyfill included in RN.

**Comment by bestander** [comment] 2016-06-30 16:09
duplicate of https://github.com/facebook/react-native/issues/6679

**Closed by bestander** 2016-06-30 16:09 UTC
Labels: Needs more information
