### ISSUE TITLE
'self.bridge.eventDispatcher sendAppEventWithName' does not work

### ISSUE THREAD

**Issue by BaoBaoJianqiang** [facebook/react-native#13088] opened 2017-03-22 17:09 UTC
First, the method 'sendAppEventWithName' is deprecated.
2nd, "self.bridge" is always null, so OC can't invoke js function in RN.

**Comment by hramos** [comment] 2017-03-22 20:02
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-03-22 20:02 UTC
