### ISSUE TITLE
React native fails silently when exceptions are thrown in render

### ISSUE THREAD

**Issue by potsypantsy** [facebook/react-native#2168] opened 2015-07-29 16:34 UTC
A lot of times react native will fail silently (no console error and no red box) when exceptions are thrown in render. I traced through the stack and It looks like the perform method in https://github.com/facebook/react/blob/master/src/shared/utils/Transaction.js#L124 is not propagating any exceptions. Any help would be great!

**Comment by ide** [comment] 2015-07-29 17:39
@potsypantsy do you have a small repro case you could share?

**Comment by jacob-israel-turner** [comment] 2015-08-01 17:01
+1

**Comment by potsypantsy** [comment] 2015-08-02 19:58
I encounter this in my app but was having trouble reproducing this in a simplified example. I am going to try again in a few days

**Comment by rxb** [comment] 2015-08-03 04:06
It happened to me only after my project got fairly complex. Now I rarely get red screen errors. Next project I'll be on the lookout for the moment it starts.

**Comment by potsypantsy** [comment] 2015-08-09 04:42
This seems to solved my problem. 
```Note that we call done() at the end of the promise chain - always make sure to call done() or any errors thrown will get swallowed.```

**Comment by ide** [comment] 2015-08-15 04:55
Closing this since the issue is with ES6 promises.

**Closed by ide** 2015-08-15 04:55 UTC

**Comment by steida** [comment] 2015-12-01 02:48
It's happening to me as well, using await async with promises in componentWillMount. I'm confused a bit, because `done` is not part of specs or I'm missing something. Why my code should use it?

**Comment by guyanbiao** [comment] 2016-01-25 14:29
https://github.com/facebook/react/blob/master/src/shared/utils/Transaction.js#L132

add catch block will pop the error

```js
    try {
      this._isInTransaction = true;
      // Catching errors makes debugging more difficult, so we start with
      // errorThrown set to true before setting it to false after calling
      // close -- if it's still set to true in the finally block, it means
      // one of these calls threw.
      errorThrown = true;
      this.initializeAll(0);
      ret = method.call(scope, a, b, c, d, e, f);
      errorThrown = false;
    } catch(e)  {
      console.error(e)
    } finally {
```
