### ISSUE TITLE
[React Native for X] TVOS

### ISSUE THREAD

**Issue by tpisto** [facebook/react-native#2618] opened 2015-09-09 19:19 UTC
Any insights already about new Apple TVOS development using React Native?

**Comment by ide** [comment] 2015-09-09 19:49
It should work with a couple of modifications although not all of the native modules are present since some of them don't make sense. Without having done any tvOS development, my current guess is you could get it running in a weekend.

**Comment by dotcypress** [comment] 2015-09-09 21:30
:+1:

**Comment by Kureev** [comment] 2015-09-10 20:29
Let me know if I can help you somehow, very excited about it!

**Comment by ide** [comment] 2015-09-10 20:33
I'm not actively working on it. Someone smart should just do it. Go for it @Kureev.

**Comment by auser** [comment] 2015-09-11 19:56
+1 (@Kureerv -- I'd be down to attempt help this weekend)

**Comment by jordanbyron** [comment] 2015-09-11 23:01
I spend a little time this afternoon ripping bits and pieces out of react-native that don't play nice with tvOS and got the SampleApp running on tvOS:

https://github.com/jordanbyron/react-native/tree/tvOS

![screen shot 2015-09-11 at 6 50 33 pm](https://cloud.githubusercontent.com/assets/40662/9828128/5aa2b600-58b7-11e5-9c2f-64af286fb74f.png)

Fair warning a lot is broken and still needs to be fixed:

1. The developer menu is shot because tvOS does not support `UIActionSheet`.
2. I commented out a few deprecated lines from `RCTWebSocketExecutor.m`
3. Lists should always have at least three things. So insert your favorite emoji here :fire_engine: 

Hopefully this can start as a jumping off point if you anyone else wants to seriously get react-native support in tvOS.

**Comment by brentvatne** [comment] 2015-09-11 23:08
![f5ff8bbf2baedef02048f6de48f8b821ad10334a9747e5bf630d78775c0dd61f](https://cloud.githubusercontent.com/assets/90494/9828236/552c40a0-589f-11e5-928e-5d5b1ba9803f.jpg)

**Comment by rileybracken** [comment] 2015-09-11 23:11
![jaw drop](https://media.giphy.com/media/a8RO6kWdcjVp6/giphy.gif)

**Comment by browniefed** [comment] 2015-09-11 23:13
![http://i.giphy.com/WXOs3HvaUw1Hi.gif](http://i.giphy.com/WXOs3HvaUw1Hi.gif)

**Comment by ide** [comment] 2015-09-11 23:18
![54353572](https://cloud.githubusercontent.com/assets/379606/9828347/c2f08154-58a0-11e5-8939-b8d018138fd2.jpg)

**Comment by michalgritzbach** [comment] 2015-09-12 16:22
![what a twist](https://cloud.githubusercontent.com/assets/352464/9832443/3bad2496-597b-11e5-928b-2aaaff424c67.gif)

**Comment by SOSANA** [comment] 2015-09-12 18:21
https://s-media-cache-ak0.pinimg.com/originals/d4/04/b1/d404b18b5fa6b8513d14bac7ea68ed7a.jpg

**Comment by SOSANA** [comment] 2015-09-12 18:23
![d404b18b5fa6b8513d14bac7ea68ed7a](https://cloud.githubusercontent.com/assets/2634185/9833109/f5bfaa3a-5948-11e5-9c92-c49c19c0cf28.jpg)

**Comment by jordanbyron** [comment] 2015-09-12 19:54
I hope you're happy @brentvatne. Look what you've done!

This afternoon I've been messing around with restoring the developer menu. Looking through Apple's new [HIG for tvOS](https://developer.apple.com/tvos/human-interface-guidelines/ui-elements/) there isn't an equilivelent to `UIActionSheet` so I was thinking a left-aligned table would work just as well with buttons in each cell. 

![slice 1](https://cloud.githubusercontent.com/assets/40662/9833490/7eda01d6-5966-11e5-8ffd-ab9cded12cfc.png)

That being said all of this is pushing my Obj-C / UIKit knowledge to the limits so if anyone with a bit more experience wants to help get the dev menu restored let me know. Luckily the CMD+D shortcut is still working so we have a way to toggle the menu while using the simulator. I haven't thought of any clever ways to activate the menu on real hardware vis-à-vis shaking on iOS. But that's a problem for later.

**Comment by dhrrgn** [comment] 2015-09-13 04:45
@jordanbyron Nice work here.  As for the dev menu when running on the hardware:

The new remote has built a built in gyro and accelerometer, so you could probably take advantage of that fairly easily with the new [GCMotion class](https://developer.apple.com/library/prerelease/tvos/documentation/GameController/Reference/GCMotion_Ref/index.html#//apple_ref/occ/instp/GCMotion).  Most notably, the `userAcceleration` property.

Another option is to use the Play/Pause button, and trigger the menu after it is pressed for 2 seconds or something (to avoid conflicting with what the app may want to do when that button was pressed).  That is also fairly simple: [Detecting Gestures and Button Presses](https://developer.apple.com/library/prerelease/tvos/documentation/General/Conceptual/AppleTV_PG/DetectingButtonPressesandGestures.html#//apple_ref/doc/uid/TP40015241-CH16-SW1) (`UIPressType. UIPressTypePlayPause`)

**Comment by dhrrgn** [comment] 2015-09-13 05:00
@jordanbyron Also, just noticed that tvOS *does* have Action Sheet support, but `UIActionSheet has been replaced by [UIAlertController](https://developer.apple.com/library/prerelease/tvos/documentation/UIKit/Reference/UIAlertController_class/index.html).  You just have to set the `preferredStyle` to `UIAlertControllerStyleActionSheet`.

*Side Note: That class also replaces `UIAlertView`, so you would need to update `RCTAlertManager` to use that on tvOS (although I see you just removed that file altogether)*

**Comment by jordanbyron** [comment] 2015-09-13 15:08
@dhrrgn dude that's exactly what I was looking for! You rock :metal: 

Check it out:

https://github.com/jordanbyron/react-native/commit/c7c4d9a941f6c0025633dd7bbbe6179d2a0f88f4

And 

![tvos-dev](https://cloud.githubusercontent.com/assets/40662/9837268/b7833ede-5a07-11e5-8ee0-70601a177d1e.gif)

**Comment by WillsonSmith** [comment] 2015-09-13 16:18
Wow. That was fast. 
![Nooice](http://i.imgur.com/L1LRnMO.gif)

**Comment by sabeurthabti** [comment] 2015-09-13 18:43
sick

![excited](http://www.reactiongifs.com/r/The-Hills.gif)

**Comment by frankbolviken** [comment] 2015-09-14 06:43
![Image of Yaktocat](http://i0.kym-cdn.com/photos/images/original/000/967/317/afc.jpg)

**Comment by robwormald** [comment] 2015-09-14 11:40
great, there goes my productivity this week. awesome!

**Comment by oronbz** [comment] 2015-09-14 11:40
![Image of Nice](https://media.giphy.com/media/IUZtGhVO8hZ6w/giphy.gif)

**Comment by jamgraham** [comment] 2015-09-15 03:21
![200w](https://cloud.githubusercontent.com/assets/187200/9866983/1e3edb6c-5b1e-11e5-9322-993558f3b03b.gif)

**Comment by fsbdev** [comment] 2015-09-21 05:46
How is setting up the focus chain with `preferredFocusedComponent` going to work? It requires references to other components in the tree.

**Comment by dhrrgn** [comment] 2015-09-21 06:20
@fsbdev I am not exactly sure what `preferredFocusedComponent` is (although I have an idea), however the UIManager has a `viewRegistry` which has references to all of the Views (keyed by reactTag, which is just an integer id). With that in mind, it should be relatively simple to do whatever to need. With component references.

**Comment by deanmcpherson** [comment] 2015-10-01 06:20
This is cool, I got it up and running this afternoon. Am wondering how to get a button working. Should I try and modify Touchable to be navigable, or is it really more the place of a new component?

**Comment by respectTheCode** [comment] 2015-10-01 13:37
What is the path to getting a tvOS or any new platform supported?

**Comment by grabbou** [comment] 2015-10-09 15:31
Maybe packager could support .tvos.js extension so we can start writing platform specific code. Not sure about native modules, but with an easy way to replace non supported native APIs this shouldn't take long.

**Comment by grabbou** [comment] 2015-10-11 15:14
I think I have purely theoretical idea how this can be easily integrated into React Native itself, will try to publish it to GitHub/npm later today!

**Comment by duro** [comment] 2015-11-02 18:47
Will these efforts at some point be merged with the react-native project, or do they need to be ported out to a separate project? Is there somewhere I can learn what you guys have done already? I want in on the tvOS party!! 😜😜😜😜

**Comment by kinergy** [comment] 2015-11-10 17:56
+1

**Comment by dhrrgn** [comment] 2015-11-11 23:10
@duro There hasn't been any work/movement on this in 2 months, so...unless someone puts real effort into getting everything working (the OP had to strip out a lot of things not supported by tvOS), I don't see this going anywhere anytime soon.  Unless Facebook wants to release an Apple TV app written in RN.

As for seeing what is done already, you can see the comparison here: https://github.com/tadeuzagallo/react-native/compare/d5bce33f696606d639a7630403393de496760f63...jordanbyron:tvOS

Note: As I mentioned, the commits are 2 months old, so...YMMV.

**Comment by grabbou** [comment] 2015-11-12 09:21
I have a working demo of TVOS where I followed @jordanbyron work + organised it in a better `mergable` way w/o mirroring the whole repository. The only issue I had encountered was not being able to override React headers. And because React Native was using some classes not present on TVOS, it was causing compile-time errors. Obviously, implementation can be easily overwritten, but as per compiler design, it first looks for headers in current directory, then in `header search paths`, so even if you `override` RCTUtils.h, some stuff from `node_modules/react-native/React/Base` will keep referring to it.

The only solution I can see atm to get it working is to add in some compile time flags (I guess 3) to skip some methods that use classes not available on TVOS. 

That's all. Then we can get `npm-publishable` react-native-tvos project that does not duplicate `react-native` but only defines its own `RCT....xcodeproj` stuff + overrides maybe 3 or 4 core files.

**Comment by braunsquared** [comment] 2015-11-13 01:26
Hey @grabbou, any chance you'd be willing to share your work somewhere?  I'm looking to start investigating react-native on TVOS and it sounds like you may have a great starting point.  I'd rather not reinvent the wheel if it's already in the works.

Thanks!

**Comment by grabbou** [comment] 2015-11-13 08:54
Yeah. I'll try to make it on GitHub this week and post a link here :)

**Comment by braunsquared** [comment] 2015-11-14 09:26
So I decided to tackle it anyway.  I introduced a new platform to the react-native cli for code generation and the packager.  I also created all the needed platform specific component scripts and created new tvOS targets for the React xcode projects.  The template for the new tvOS project still needs to be updated and the dev tools need to modified for tvOS.  There are some stragglers hanging around too that I simply haven't been able to get to yet. 

For any shared objc code which has calls that aren't supported on tvOS, I've wrapped with TARGET_OS_IOS preprocessor macros.  There were only a handful of these so it wasn't so bad.

Feel free to check it out https://github.com/braunsquared/react-native

Things I still need to address:
- DevTools - I see someone addressed it above so maybe I'll merge their changes in.  I still have to look at it in detail.
- UIAlertView alternatives - There are some places a call to RCTAlertView is used.  Only found one or two, but these will have to be updated to a UIAlertController for tvOS.
- tvOS template project needs to be updated to make a tvOS based xcodeproj.  Currently it's a mirror of the ios template which I manually update for tvOS.
- I was running into an issue with babel on the master branch not finding the plugins since it's not looking in the right place for them.  As a work around, I manually installed the babel plugins into my test project but this isn't right and will continue to bug me.  I couldn't find any simple immediate solution.  I'm currently assuming it's because it's the master branch and they just moved to babel-6
- How best to handle the new intents mechanisms for tvOS?
- Need to start reviewing the new tvOS specific components and look at implements the view managers.

First screener for your viewing pleasure:
![image](https://cloud.githubusercontent.com/assets/1265928/11162931/cd948bbe-8a87-11e5-812a-10d10fb6258e.png)

**Comment by braunsquared** [comment] 2015-11-16 17:49
So I made some more commits to my endeavors over the weekend.  The base environment seems to be quite stable although changes to user input are going to present an interesting challenge.  I've updated the dev tools menu to work with tvOS as well as updated the red box error view to better handle tvOS styling.  Debug in Chrome is working as well.  The inspector doesn't work since the input mechanism relies on touch to work properly (something to think about, I've seen some apps make their own cursor so maybe this is an option for use input inside the inspector).

Since I based the fork off of the master branch, there are some hurdles to get past.  Babel 6 continues to have issues finding it's plugins as it's not looking in the right spot for the deps.  The react-haste module, which has no repo associated with it so I have no way to submit a pull request, has some changes from the release version of react-native which cause js exceptions when debugging in chrome.  Most specifically, there is an __DEV__ conditional which attempts to make a reference to document from inside the debug worker which kills debugging in chrome.  

To truly put it through it's paces, I've begun porting the samples over to tvOS.  Since there is such a drastic change to user input, I will likely focus there first.  

I've also started to look into adding a TVMLTVOS component since this seems to be a primary native component for tvOS.

Any feedback or suggestions for user input is most appreciated.

Game2048 in action:  (Displays great, no user input yet :/ )
![image](https://cloud.githubusercontent.com/assets/1265928/11189799/16d6a6de-8c60-11e5-83d5-654eb982b4ce.png)

Working Red Box Error: (navigating/selecting stack works as expected)
![image](https://cloud.githubusercontent.com/assets/1265928/11189811/32a0197c-8c60-11e5-9ccf-52e5a5537df1.png)

**Comment by idibidiart** [comment] 2015-11-23 20:43
HI,

Wouldn't Facebook want to release a social app for TvOS at some point in the future? Wondering if it's too early to tag this as 'Community Responsibility' ? @brentvatne

**Comment by deanmcpherson** [comment] 2015-12-01 20:57
So in terms of getting input working, a naive quick win could be to try and port over UIButton? Not sure whether that is an extremely difficult thing to do. According to http://nerds.airbnb.com/tvos-focus-engine/ the only UIKit components that are focussable are;

UIButton
UIControl
UISegmentedControl
UITabBar
UITextField
UISearchBar

**Comment by bleonard** [comment] 2015-12-18 22:12
I realized something that seems interesting, but it's not clear to me how it applies.

This whole [TVML](https://developer.apple.com/library/tvos/documentation/LanguagesUtilities/Conceptual/ATV_Template_Guide/index.html#//apple_ref/doc/uid/TP40015064-CH41-SW1) thing is basically the same approach as react native.

* The application delegate launches the javascript
* the JS renders a template and the native layout engine maps that to UIKIt items
* The JS is debugged using the Safari web inspector
* there is a bridge between the native and JS code

My first thoughts on doing React Native on Apple TV would be to basically have the same code. I'd be very nervous that all the elements would work differently. Apple sees it very different than iOS because it's not actually touching them. It's focus based. What I'd be worried about with that approach is that it doesn't fit in with the rest of the apps. There are strong patterns in place.

So it feels like there is something about these TVML components and well-worn templates.

Maybe in JSX it should be a top level `<TVML>` component with mapped TVML components within it. There would be little to do as the OS already knows how to render that template. It's all one "view."

Maybe. I'm not sure. But I think there's something interesting there.

**Comment by boffbowsh** [comment] 2016-01-02 12:28
For info, there's an attempt at TVML bindings here https://github.com/ramitos/react-tvml.

I've been trying to use it myself, but I'm a total newcomer to React. But I have done some raw TVML. The issues are that a lot of "normal" React relies on `window` and `document` global variables being available, which isn't the case in the TVML environment. So that might be fixed/helped by https://github.com/facebook/react/issues/3213.

**Comment by brentvatne** [comment] 2016-01-03 03:35
As far as I know, nobody on the React Native team will be working on this any time in the next six months, probably more, so I'm going to close this. If you think this is very important and the react-tvml repo mentioned above is the wrong approach and you think it needs to be built into React Native, then please upvote and comment on this issue with some reasons why: https://productpains.com/post/react-native/react-native-for-tvos/ :)

**Closed by brentvatne** 2016-01-03 03:35 UTC
Labels: Community Responsibility

**Comment by deanmcpherson** [comment] 2016-02-10 21:58
I know this is closed, but at the moment TVML looks like a dead end. The templates are very restrictive, and the DOM implementation looks only half baked for truly dynamic apps. @braunsquared did you get much further with your implementation?

**Comment by braunsquared** [comment] 2016-02-10 23:05
I did not. When the Facebook team closed the ticket it became clear to me that since the changes required to support a new platform are so extensive a fork would be impossible to maintain and the work would never be merged back into the root project.

**Comment by deanmcpherson** [comment] 2016-02-10 23:08
Fair call. Guess I'll learn swift :)

**Comment by faceyspacey** [comment] 2016-04-05 11:13
This is much needed. It's an obvious progression that has to happen. Looking at it any other way is absurd. There's more than enough overlap in similar tools provided by the underlying Apple platforms. It's basically expected. React Native is absolutely killing it on iOS. It's been absolutely beautiful for me to work with. So when the React Native team at Facebook eventually get the time, this must become a major priority. If there's any way to expedite that, we should figure it out. 

*Also*, the time is now to make a splash in the Apple TV space. Facebook has billions of dollars--I don't see why they can't hire more developers. I don't get what the problem is. The open source community leads itself--Facebook barely has to train these developers. They come self-trained and know exactly what to do and what needs to be done, especially when it comes to open source projects. So I don't get @brentvatne's comments about not being able to make any progress on this in the next 6 months. Some reasons why Facebook can't just hire more developers would clarify that. I'll work on it. Hire me. Hire the contributors above. I love the absolute steady pace of these React Native releases. It is incredible. It's clear the core developers behind it truly recognize the value they are delivering. There's just a whole ton of value here, that it doesn't make sense not to put as much resources behind it as absolutely possible. There's always mention here on Github regarding the react native issues backlog and how there are too many that they gotta heavily triage. Meanwhile Facebook's playing around with Occulus Rift, but React Native is a development platform that can eat the world *today*! Put $2 billion dollars behind React Native and it will be better spent than playing in the VR/AR wars. It's a guaranteed win. 

@brentvatne what's holding Facebook back from building a bigger react native team? It can't be the money--coordination??

**Comment by jondwillis** [comment] 2016-04-13 07:06
The focus engine isn't so different from touch, really.

TVML is inappropriately restrictive for many app experiences that Apple never envisioned. Many of which have been featured in the store by none other than Apple itself.

**Comment by douglowder** [comment] 2016-07-31 19:54
I have React Native fully operational on Apple TV, with support for the focus engine, focus animations, and changes to allow code using TouchableHighlight or TouchableOpacity to work with few or no changes.  https://github.com/douglowder/react-native-appletv/blob/master/README-appletv.md

**Comment by deanmcpherson** [comment] 2016-07-31 22:53
What a champion. Will check it out.

**Comment by deanmcpherson** [comment] 2016-08-02 00:59
Hey @douglowder, do you have some tips to get this up and running on a new project? In particular, how to set up the TV specific xcode project?

**Comment by deanmcpherson** [comment] 2016-08-02 04:34
Never mind, I copied one of the examples. Looking good! I had to remove NetworkOverlay from the InspectorPanel to get the app to load, but other than that it appears to be working well. Tested out the focus engine and support for things like LayoutAnimation. Is this going to stay separate as fork to RN? Would be good to put in its own repo if it's going to stay separate, so we can submit issues / PRs.

**Comment by douglowder** [comment] 2016-08-02 15:09
@deanmcpherson My plan is to ask FB to merge this to the main repo, once all the issues are resolved.  In the meantime, please let me know if you find any TV-specific problems with the code....

**Comment by zhihuikeji** [comment] 2016-08-03 13:49
I think Android TV also need focus engine

**Comment by stan229** [comment] 2016-08-19 03:26
@deanmcpherson do you happen to have a blank (init-bootstrap) app using @douglowder 's fork? I'm trying to copy one of the examplses, but am also trying to pull it out as a standalone xcode project.

**Comment by deanmcpherson** [comment] 2016-08-19 03:43
@stan229 There is this: https://github.com/deanmcpherson/react-native-tvos-example

**Comment by stan229** [comment] 2016-08-19 03:53
@deanmcpherson Thanks. Unfortunately my Apple TV simulator is not showing up in the simulators list when I open the townskeTVtv project (even though tvOS is set as the architecture). The simulator does show up when I try to open one of the example projects included in the fork.

**Comment by rikukissa** [comment] 2016-08-21 09:23
I spent last night trying to run @deanmcpherson's example project in Apple TV simulator and for some reason it wasn't as straightforward as the readme suggests. Anyways, I managed to run it eventually and decided to write this short tutorial on how I did it, since it took me a couple of hours to figure it out.

https://gist.github.com/rikukissa/7f141a2b497f1bdae1cf0d7eb4f4765e

**Comment by douglowder** [comment] 2016-08-21 18:55
@stan229 @deanmcpherson @rikukissa I've added Apple TV support for initial project generation using react-native-cli.  The generated project folder now has a TV xcode project in the generated ios subfolder.  To make this work, you'll need to clone my repo (https://github.com/douglowder/react-native-appletv) and follow the steps for using it with a local npm registry (https://www.npmjs.com/package/react-native-cli).

**Comment by stan229** [comment] 2016-08-25 04:27
@douglowder followed your steps but I'm not seeing the tvOS Simulator when I open the TV-suffixed xcode project. I see "My Mac" as the option for my app. There's another project option with the same name and that gives me a Generic tvOS Device Option, but no Simulator. Only the React library is giving me a simulator option.

**Comment by stan229** [comment] 2016-09-04 15:27
Looks like I didn't have a tvOS 9.3 simulator (and that was the deployment target). Once I changed it to 9.2, all good! Thanks @douglowder

**Comment by naoufal** [comment] 2016-10-06 04:44
@stan229 @douglowder do your projects run on tvOS 10? I'm seeing "cannot find mutex" errors on build. Any ideas?

**Comment by dlowder-salesforce** [comment] 2016-10-06 11:53
Yes they should run fine on tvOS 10. I'm using Xcode 8 for my local builds and haven't seen any issues.  I just updated my repo yesterday... please try pulling the latest and see if it works.

Good news is, I've already started sending pull requests to Facebook, so all this functionality should be available in the main repo very soon.  The first two PRs are already committed.  See https://github.com/facebook/react-native/commit/d368ebfab2c389cc093f6a73e5c1021408cc6a73 and https://github.com/facebook/react-native/pull/9649 and https://github.com/facebook/react-native/commit/86229983359f1b80817bfb6b15d1a154b75b1917 .

**Comment by naoufal** [comment] 2016-10-06 12:28
@douglowder @dlowder-salesforce Yeah, I'm on Xcode 8 as well and I've pulled the latest master commit `91760c`.

and when running the UIExplorerTV project I get the following error:

```
No such file or directory: '~/dev/react-native-appletv/Libraries/Network/RCTNetworking.m'
```

**Comment by douglowder** [comment] 2016-10-06 14:47
Ok I'll have a look later today.

**Comment by dlowder-salesforce** [comment] 2016-10-06 18:57
This is fixed now -- updated the tvOS project files in my repo.  FYI: When all of my changes are eventually merged to facebook/react-native, these special tvOS project files are going away.  If you look at the regular iOS project files now, you will see that they already have tvOS targets.

**Comment by naoufal** [comment] 2016-10-06 23:48
@douglowder thanks. I ended up using the changes you've merged into master.  any tips for pulling out the developer menu?

**Comment by dlowder-salesforce** [comment] 2016-10-07 01:22
Just type command-D in the simulator, the dev menu should come up and be navigable with the arrow keys.

**Comment by fungilation** [comment] 2016-10-16 00:35
Does WebView work currently on tvOS? Assuming that's allowed by Apple's app approval, possibly with local, sanitized, tv screen formatted HTML instead of unformatted HTML from the wild wild web.

**Comment by naoufal** [comment] 2016-10-16 01:31
@fungilation tvOS doesn't support WebViews at the moment.

**Comment by fungilation** [comment] 2016-10-16 02:03
It does, [unofficially](https://github.com/jvanakker/tvOSBrowser). Hence my comment about Apple possibly allowing if we present TV screen formatted HTML in WebView that looks native?

**Comment by douglowder** [comment] 2016-10-16 02:13
The web view may render, but it won't support Siri Remote input properly, and it won't pass App Store review....

**Comment by naoufal** [comment] 2016-10-16 14:58
@fungilation I misread your comment, sorry about that!

**Comment by michaelknoch** [comment] 2017-03-11 14:21
i recently discovered tvOs specific code in react-native. Are there any plans for official appletv support, by now?
 
https://github.com/facebook/reactnative/blob/77b8c097277b5cf248d08e772ea8bb8d8583e9a1/Examples/UIExplorer/js/UIExplorerExampleList.js#L105

**Comment by apgl** [comment] 2017-03-14 13:06
Does anyone know if tvOS apps build with react native will be accepted into the App Store? Thanks.

**Comment by naoufal** [comment] 2017-03-14 15:04
@apgl shouldn't be a problem. I have a React Native TV app in the App Store.

**Comment by TrevorSayre** [comment] 2017-05-03 14:06
@naoufal Are you open to sharing which app? It would be helpful for pitching this as a project to be able to point at an existing app in the App Store.

**Comment by naoufal** [comment] 2017-05-03 14:13
@TrevorSayre it's Unsplash for Apple TV. More about it here. https://medium.com/unsplash-unfiltered/introducing-unsplash-for-apple-tv-50228252af44?source=linkShare-fac695f6bd9b-1493820756

**Comment by dlowder-salesforce** [comment] 2017-05-03 19:34
For those of you building RN apps for Apple TV, I'd recommend 0.43 or later.  Everything is now merged to Facebook repo.  I wrote some docs here: http://facebook.github.io/react-native/releases/next/docs/building-for-apple-tv.html

**Comment by Kaidash** [comment] 2018-02-10 06:10
What about supporting Android TV focus engine? I can't find info about it.

**Comment by dlowder-salesforce** [comment] 2018-02-10 06:55
@Kaidash please see #16500

**Comment by euroclydon37** [comment] 2018-02-14 15:32
I've hit a hiccup that I can't seem to find an answer to with Menu Button functionality. I've read that your app will get rejected if the menu button doesn't exit to home screen (at least when your app is at its own internal home screen), but I can't seem to make that happen. `BackHandler.exitApp()` doesn't work. And having no listeners at all does nothing.

Is RN intercepting the event by default?

**Comment by dlowder-salesforce** [comment] 2018-02-14 19:05
@euroclydon37 : Yes RN is intercepting the event.  RN needs to do that in order for the BackHandler to work.  FYI: recent versions of tvOS now exit to home screen whenever the user does a long press on the menu button, and application code can't override that behavior.  So I'm not sure if exit on menu tap is still an App Store requirement.  Please create an issue and I'll investigate to see if I can come up with a generic way of dealing with this problem.
