### ISSUE TITLE
Horizontal Scrollview nested with multi ListView has two problem

### ISSUE THREAD

**Issue by someok** [facebook/react-native#6703] opened 2016-03-29 12:59 UTC
The problem:

1. When I config ScrollView with "contentContainerStyle={{flex: 1}}", It will show warning:

> Warning: ScrollView doesn't take rejection well - scrolls anyway

2. The nested ListView cannot scroll to top when I click the iPhone status bar.

env:

- React Native: 0.22
- Device: iPhone 6s

**Comment by DanielMSchmidt** [comment] 2016-03-29 20:58
It would help if you could provide an example, e.g. via [rnplay](https://rnplay.org/). That way we may see if this may be intended behaviour or an actual bug.

**Comment by someok** [comment] 2016-03-30 04:02
@DanielMSchmidt https://rnplay.org/apps/Ew-zjQ

![image](https://cloud.githubusercontent.com/assets/1523082/14131580/456a7cd6-f66f-11e5-8328-e01b56e2d9a8.png)

**Comment by charpeni** [comment] 2016-08-09 12:31
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/horizontal-scrollview-nested-with-multi-listview-has-two-problem

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix.**
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment] 2016-08-09 12:31
@facebook-github-bot label Icebox

**Comment by charpeni** [comment] 2016-08-09 12:35
@facebook-github-bot close

**Comment by facebook-github-bot-5** [comment] 2016-08-09 12:36
@charpeni tells me to close this issue. If you think it should still be opened let us know why.

**Closed by facebook-github-bot-5** 2016-08-09 12:36 UTC
Labels: Icebox, Ran Commands
