### ISSUE TITLE
Keyboardavoidingview not working properly with TextInput Password Field

### ISSUE THREAD

**Issue by hussainahmad** [facebook/react-native#23818] opened 2019-03-08 06:49 UTC
## 🐛 Bug Report
When we make `TextInput` as a password fields KeyboardAvoidingView not work as expected.  
Currently when remove secureTextEntry={true} it works fine like when I press next button on keyboard it will go to password textInput field from State textInput field and also password textInput field scroll up and works perfectly, but when I added secureTextEntry={true} which is mandatory this is not working for password fields, working fine on other fields perfectly. I also created a demo code, Please look into this. This issue is only in Android.

![53394742-fd245980-39c1-11e9-9734-035712d6c2ae](https://user-images.githubusercontent.com/5903522/54012456-ecc96700-4197-11e9-9b12-4810348ce27b.png)

## To Reproduce
I made a demo code to check this issue, just remove `secureTextEntry={true}` from Password Fields This issue will arise only in android,

## Expected Behavior
When I press next on keyboard it should go to password field and password field should scroll up like other Input Fields.

## Code Example
[Demo Code having Issue](https://github.com/hussainahmad/React-Native-Form-Demo)
[Question on StackOverflow](https://stackoverflow.com/questions/54880842/keyboardavoidingview-not-working-with-textinput-password-fields-properly-on-andr)

## Environment

software | version
-- | --
android | 8.0.1
react-native | 0.57.1
node | 8.12.0
npm | 6.4.1
expo sdk | 32.0.0

**Comment by JKCooper2** [comment] 2019-03-09 00:38
Unable to repro using example: https://snack.expo.io/@jkcooper/rn23818-keyboardavoidingview-android-autoscroll

On Android the KeyboardAvoidingView will only scroll when starting to type (not on focus), regardless of whether secureTextEntry is enabled. There are differences between how KeyboardAvoidingView works based on the platform as noted in the docs (https://facebook.github.io/react-native/docs/keyboardavoidingview#behavior).

Unfortunately I wasn't able to figure out how to get the behaviour you were looking for, but this may be a better question somewhere like Reactiflux (https://www.reactiflux.com/)

**Comment by hussainahmad** [comment] 2019-03-11 09:25
Hi @JKCooper2 Thanks 
> On Android the KeyboardAvoidingView will only scroll when starting to type (not on focus) regardless of whether secureTextEntry is enabled. 

I am sure you are right but now please look into this code [https://snack.expo.io/S1DzLq7PE](https://snack.expo.io/S1DzLq7PE) . using `TextInput` of [`react-native-paper`](https://github.com/callstack/react-native-paper) if I disable secureTextEntry then it works fine with Password fields.

**Comment by dulmandakh** [comment] 2019-03-19 17:22
I couldn't reproduce the issue on RN 0.59, or I can click next and go to a next field even if it has secureTextEntry={true}

Hello there 👋 this issue has been reported for an old version of React Native. Ideally we'd like everyone to be using 0.59 (see the [awesome changes](https://facebook.github.io/react-native/blog/2019/03/12/releasing-react-native-059) it brought) but we know updating can be a pain. We are going to close this issue because it's from a version before 0.57, which is really old.

But please, if it's actually still an issue with 0.59 please comment below and we can reopen it. Even better, please send us a pull request with a fix 😊

**Closed by dulmandakh** 2019-03-19 17:22 UTC
Labels: API: Keyboard, Component: KeyboardAvoidingView, Component: TextInput, Platform: Android, Resolution: Missing Environment Info, Type: Bug Report

**Comment by hussainahmad** [comment] 2019-03-20 06:27
>I couldn't reproduce the issue on RN 0.59, or I can click next and go to a next field even if it has secureTextEntry={true}

yes you are right it go to the next field this is not the issue. I tried with RN 0.59.1 but Issue I am discussing here not fixed , I am sure you didn't understand my context or may be I am explaining in a wrong way.  
AS @JKCooper2 mentioned 
>On Android the KeyboardAvoidingView will only scroll when starting to type (not on focus), regardless of whether secureTextEntry is enabled.

I think in android too keyboard should scroll when click next before we start type

**Comment by ironhide0396** [comment] 2019-10-10 17:26
Hi , I am facing the same issue as exactly mentioned by @hussainahmad  . The error does occur in 0.59 too . One way i fixed it was to wrap the KeyBoardAvoidingView inside a ScrollView.
Let me know if that works out .
