### ISSUE TITLE
ViewPagerAndroid returns empty view when new source data added

### ISSUE THREAD

**Issue by ACCTFORGH** [facebook/react-native#4775] opened 2015-12-15 01:19 UTC
I am currently using the ViewPagerAndroid component to do a matching/unmatching function which requires dynamic data updating in the source data of the component. The children of of the view pager is generated by a function makeItems(this.state.data) and it returns an array of keyed views. i.e. [< View key={1}/>, < View key={2}/>....] with the index being the index of the for loop that generates the array from the source data. The views contain composite views of touchable highlight but all are wrapped by a view container. I kept the data in the state of the component and whenever data updates I call setState and ViewPagerAndroid.setPage(0). The data update works fine when I reduce the data (splice) but returns an empty view for the new data when I add new data to the array. The data before the update was displayed properly.I have checked my makeItems() function that the updated data has been passed in proper. 

```
< ViewPagerAndroid
          name = 'Page Viewer 1'
          style = {styles.matchingPanelViewPager}
          initialPage={this.state.currentPage}
          onPageSelected = {(e)=>{
            console.log(e.nativeEvent.position);
          }}
          ref = {viewPager =>{this.viewPager = viewPager;}}>

          { this.makeItems(this.state.data) }

        </ ViewPagerAndroid>
```

I am using RN0.16.0 on Mac OS X, Genymotion, Android 4.2.2.

Same issue raised in StackOverflow: http://stackoverflow.com/questions/34279503/viewpagerandroid-returns-empty-view-when-new-source-data-added
Thanks a lot for your help!

**Comment by finalquest** [comment] 2015-12-15 19:49
Hi.
I'm facing the same issue.
I have a pager that renders an array of views.
When I deleted an entry of the array, the next render of the pager is drawing an empty view.
Also, the last view of the array goes out of screen bounds and cant be reached.

I dont really know where I have to start looking to fully realize whats really happen

Regards

**Comment by brentvatne** [comment] 2015-12-24 23:37
I ran into this too and my temporary solution was to give it a key, then change that key every time you update the data source. A PR is welcome to fix this!

**Comment by ACCTFORGH** [comment] 2016-01-09 22:03
I used this third party component and it works well with data updates. The syntax is more elegant too.

https://github.com/race604/react-native-viewpager

**Comment by yonatanmn** [comment] 2016-03-09 09:30
Having the same issue (actually adding is ok, but slicing array of pages, and pushing causes this).
I've tried changing key (to `AndroidViewPager`) according to @brentvatne proposal, but then other problems occurred - no animation sometimes, and after some fast changes errors spawned.

I know there are problems with the native android component ([look here](http://stackoverflow.com/questions/13664155/dynamically-add-and-remove-view-to-viewpager)), so maybe the solution should start there.
But actually the best solution (for my desires) will be to add `pagingEnabled` to `ScrollView` in android, and than even deprecate `AndroidViewPager`.

BTW, Iv'e tried the third party solution @ACCTFORGH suggested, but it's really low performant.

**Comment by MrPluto** [comment] 2016-04-25 09:43
any solution?  same here. update data but return a empty view

**Comment by yonatanmn** [comment] 2016-04-25 10:15
In my scenario I'm either appending a page or slicing and then appending to the sliced pages array, 

What currently works for me is adding key based on time on this condition:
` androidViewPagerKey = newPages.length < pages.length ? Date.now() : androidViewPagerKey
  return <ViewPagerAndroid
                  key={androidViewPagerKey}...
`

**Comment by Richard-Cao** [comment] 2016-05-04 07:10
any solution?

**Comment by thrap** [comment] 2016-05-10 14:38
@Richard-Cao, this hack works for me `<ViewPagerAndroid key={Math.random()}... `. 

Thanks a lot @yonatanmn

**Comment by Richard-Cao** [comment] 2016-05-10 15:59
Thx, I wil try.  @thrap

**Comment by bollogo** [comment] 2016-05-24 10:23
Having the same issue. Using a new key for the ViewPagerAndroid Component solves this for now, but it is not an efficient solution, when only certain pages of the ViewPager should be replaced.

**Comment by kvj** [comment] 2016-06-13 05:08
Faced the same issue, and there is a fix for this.

Actually the implementation of `ReactViewPager.java` is incomplete.

Following method should be implemented also:

```
    @Override
    public int getItemPosition(Object object) {
      int index = mViews.indexOf(object);
      if (index >= 0) return index;
      return PagerAdapter.POSITION_NONE;
    }

```

Next, following method also should be fixed:

```
    @Override
    public void destroyItem(ViewGroup container, int position, Object object) {
      View view = (View) object;
      container.removeView(view);
    }

```

In my case, I copied `com.facebook.react.views.viewpager` classes to my project, fixed it and exported it as my own native view using same name. Now `ViewPagerAndroid` pages are properly created and destroyed reflecting changes of `children` array

**Comment by mkonicek** [comment] 2016-10-27 21:57
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/viewpagerandroid-returns-empty-view-when-new-source-data-added

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Closed by mkonicek** 2016-10-27 21:57 UTC
Labels: Android, Icebox

**Comment by satya164** [comment] 2016-12-29 11:22
@kvj Do you want to send a PR adding those methods?

**Comment by RichardLindhout** [comment] 2017-04-19 19:15
+1 for a fix. I think it's important because we can't have infinite viewpagers otherwise in Android.

**Comment by adhambadr** [comment] 2017-07-24 17:23
its def. still a problem version: 0.44.3 yonatanmn's solution with setting a key = current timestamp on the viewPager itself fixes. its fine for now. or till 2038 :)

**Comment by basvdheijden** [comment] 2017-07-27 13:45
Adding a dynamic key fixes the problem. But if I do i.e. ``key={pages.length}`` (so the key changes whenever the number of children changes) I experience a flickering behaviour if the key changes.

**Comment by RichardLindhout** [comment] 2017-07-28 20:34
Have you tried the virtualizedList with pagingenabled?
On iOS that works perfect for an infinite viewpager.


*Vriendelijke groeten,*
*Richard Lindhout*

*Is uw website al mobiel-vriendelijk?*

>>       webRidge.nl

Beatrixlaan 2, 4694 EG Scherpenisse

TEL:         06 43424567
KVK:        56845367
BTW:       NL225072464B01
IBAN:       NL47ABNA0567375412

2017-07-27 15:47 GMT+02:00 Bas van der Heijden <notifications@github.com>:

**Comment by basvdheijden** [comment] 2017-07-31 10:51
The problem is specifically related to android.

**Comment by RichardLindhout** [comment] 2017-08-01 10:09
I know but maybe is ViewPagerAndroid not the way to go. I have an infinite viewpager made with virutalizedList. I'm sure you'll need some customizing

```
import { View, StyleSheet, Dimensions, VirtualizedList } from 'react-native'
```
```
const { width, height } = Dimensions.get('window')
const startAtIndex = 5000
const stupidList = new Array(startAtIndex * 2)
```

```
  _renderPage(info) {
    const { index } = info

    return (
      <View style={{ width, height }}>
        
        <Header
          title={`index:${index}`}
        />
      </View>
    )
  }
```


```
      <VirtualizedList
            horizontal
            pagingEnabled
            initialNumToRender={3}
            getItemCount={data => data.length}
            data={stupidList}
            initialScrollIndex={startAtIndex}
            keyExtractor={(item, index) => index}
            getItemLayout={(data, index) => ({
              length: width,
              offset: width * index,
              index,
            })}
            maxToRenderPerBatch={1}
            windowSize={1}
            getItem={(data, index) => ({ index })}
            renderItem={this._renderPage}
            onMomentumScrollEnd={this._onScrollEnd}
          />

```
