### ISSUE TITLE
undefined is not an object (evaluating 'regeneratorRuntime.mark')

### ISSUE THREAD

**Issue by Amurmurmur** [facebook/react-native#14838] opened 2017-07-05 19:47 UTC
### Is this a bug report?
Yes
(write your answer here)

### Have you read the Bugs section of the Contributing to React Native Guide?

(Write your answer here.)

### Environment

1. `react-native -v`: 0.45.1
2. `node -v`: 8.1.3
3. `npm -v`: 5.0.4
4. `yarn --version` (if you use Yarn): 0.27.5

Then, specify:

1. Target Platform (e.g. iOS, Android): Android
2. Development Operating System (e.g. macOS Sierra, Windows 10): macOS Sierra 10.12.5
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): Android SDK 25, Android Build Tools 25.0.2

### Steps to Reproduce

(Write your steps here:)

1. react-native init AwesomeProject
2. react-native run-android

### Expected Behavior

Should work as it did with RN v0.44.0 or RN 0.45.0
(Write what you thought would happen.)

### Actual Behavior

```
undefined is not an object (evaluating 'regeneratorRuntime.mark')
<unknown>
    
loadModuleImplementation
    require.js:174:12
guardedLoadModule
    require.js:126:36
_require
    require.js:110:24
<unknown>
    index.js:2
loadModuleImplementation
    require.js:174:12
guardedLoadModule
    require.js:126:36
_require
    require.js:110:24
<unknown>
    configureStore.js:19
loadModuleImplementation
    require.js:174:12
guardedLoadModule
    require.js:126:36
_require
    require.js:110:24
<unknown>
    index.js:32
loadModuleImplementation
    require.js:174:12
guardedLoadModule
    require.js:126:36
_require
    require.js:110:24
<unknown>
    index.android.js:10
loadModuleImplementation
    require.js:174:12
guardedLoadModule
    require.js:119:45
_require
    require.js:110:24
global code
   
```
<img width="424" alt="screen shot 2017-07-05 at 22 42 33" src="https://user-images.githubusercontent.com/8608333/27882006-9a026684-61d3-11e7-90df-f05fd7ab3a24.png">

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by messense** [comment] 2017-07-06 06:56
+1

**Comment by messense** [comment] 2017-07-06 06:56
I am getting this on 0.46

**Comment by Amurmurmur** [comment] 2017-07-06 10:49
Alright seems like I've managed to fix this on RN 0.45.1
Just clean everything:
```
watchman watch-del-all
rm -rf $TMPDIR/react-*
rm -rf yarn.lock
rm -rf ./node_modules
yarn install
```

Worked for me, also unlinking and linking might help.

**Comment by ernoaapa** [comment] 2017-07-06 12:50
Face same problem when creating new project with [Ignite](https://github.com/infinitered/ignite).
- `react-native -V` 0.45.1
- `node -v` v7.10.0 
- `npm -v` 4.2.0
- `yarn --version` 0.27.5

@Amurmurmur suggestion didn't help.

**Comment by ernoaapa** [comment] 2017-07-06 13:38
Found the problem what I had (with new project generated with [Ignite](https://github.com/infinitered/ignite)).

The error were pointing in my project to line `import rootSaga from '../Sagas/'` which contain export like this:
```
export default function * root () {
  yield [
    // ... snip ....
  ]
}
```

After changing it to this started to work:
```

const root = function * root () {
  yield [
    // .... snip ....
  ]
}
export default root
```

I'm not yet familiar with the ES6 generator functions and `require` support for them, but at least now I can continue. And have to say that the error were pointing to the place where the invalid `export` were. I hope this helps someone.

**Comment by GantMan** [comment] 2017-07-06 14:16
https://github.com/infinitered/ignite/issues/1098#issuecomment-313406895

**Comment by grabbou** [comment] 2017-07-06 15:48
Wasn't this fixed here? https://github.com/facebook/react-native/commit/e7c1cf5b7d2eba9468804635d0c2a0fc6725e42a

**Comment by GantMan** [comment] 2017-07-06 15:56
So this won't roll out till 0.47?

**Comment by grabbou** [comment] 2017-07-06 16:02
Could be, someone just need to confirm it's a fix :D Let me know and I'll
do it. Planning to ship 0.46.1 soon

**Comment by Amurmurmur** [comment] 2017-07-06 18:35
Tried to fix with the suggested Saga solution, its surely something to do with saga because when I comment out saga implementation in my configureStore, the error is gone however trying suggested solution doesnt work for me. :/

**Comment by Amurmurmur** [comment] 2017-07-06 20:42
Alright guys, figured out the problem
downgraded `babel-preset-react-native` form `2.1.0` to `2.0.0` all works fine on Android/iOS 
Though once upgraded to 0.46 the error comes back.
As for RN 0.47-rc.0, most packages I have linked, wont work due to some changes to the api of the react-native I guess because they will throw errors such as:
```
:react-native-blur:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/amurmurmur/exampleapp/node_modules/react-native-blur/android/src/main/java/com/cmcewen/blurview/BlurViewPackage.java:23: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: /Users/amurmurmur/exampleapp/node_modules/react-native-blur/android/src/main/java/com/cmcewen/blurview/BlurringView.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
:react-native-blur:compileReleaseJavaWithJavac FAILED
```

**Comment by kcalmes** [comment] 2017-07-07 16:52
@Amurmurmur I am still seeing the issue on 0.45.1 even after downgrading babel. I wonder how much node and npm versions might be affecting which fixes work and which ones don't. 
node: v8.1.0
npm: 5.1.0
OS: macOS Sierra 10.12.5

**Comment by Amurmurmur** [comment] 2017-07-07 17:37
@kcalmes Make sure you reset react-native packager after you've downgraded babel with:
```
npm start -- --reset-cache
```

**Comment by kcalmes** [comment] 2017-07-07 18:05
That did the trick, I previously deleted the node_modules dir, but I didn't realize I missed the other cache. Thanks for your help @Amurmurmur!

**Comment by brentvatne** [comment] 2017-07-08 00:47
@facebook-github-bot close

**Comment by vongohren** [comment] 2017-07-09 13:00
Still experiencing this with 0.46.1 and babelrc on both 2.0.0 and 2.1.0. Tried all the things done here but it doesnt fix it. Why was this closed @brentvatne @grabbou

**Comment by Amurmurmur** [comment] 2017-07-09 14:47
@vongohren Double make sure you reset the packager, Im using react-native 0.46.1 and babel at 2.0.0 all good on both platforms Debug/Release builds.
Please make sure you run 
```
watchman watch-del-all
rm -rf ./node_modules
rm -rf $TMPDIR/react-*
npm i babel-preset-react-native@2.0.0 -D -S
npm install
npm start -- --reset-cache
```

Also make sure you reset your android/ios emulator/simulator, delete both android/ios build folders.

**Comment by vongohren** [comment] 2017-07-09 15:17
Loool, this is what I have done all the way, but I did not reset the emulator and delete the build folder. Seemed to help, thanks man. But can anyone answere why this happens? @grabbou @brentvatne

**Comment by yabeow** [comment] 2017-07-10 02:50
Downgrade babel-preset-react-native to 2.0.0 work for me too. But why 2.1.0 don't work?

**Comment by matt-oakes** [comment] 2017-07-10 13:53
Downgrading worked for me, but I'd also like to know what the issue actually is and what a real fix is.

**Comment by vongohren** [comment] 2017-07-10 14:31
Running a completly new project, that is not dependent on cocoapods or swift, works out of the box. I did not try to add all my dependencies but that could be a test case.

**Comment by Amurmurmur** [comment] 2017-07-10 19:51
@vongohren Indeed the fresh project will work for you however once you start using babel features such as export/import you will face the problem with babel-preset-react-native 2.1.0
This is a relevant issue #14933

**Comment by HelloEdit** [comment] 2017-07-12 12:04
Same issue here, from `react-native version `react-native: 0.45.1` on Windows, downgrading and @Amurmurmur's method doesn't work

**Comment by Amurmurmur** [comment] 2017-07-12 12:38
@HelloEdit 
But it works, can you share an example project where the problem occurs for you ?
It works fine on my side no matter RN 0.45.1 or 0.46.1 all still.

**Comment by kaxline** [comment] 2017-07-12 19:40
For me, using [yarn](https://yarnpkg.com/) instead of `npm` was the only thing that worked.

```bash
watchman watch-del-all
rm -rf ./node_modules
rm -rf $TMPDIR/react-*
npm cache clear
npm start -- --reset-cache
yarn cache clear
yarn install
react-native run-ios
```

I also downgraded `babel-preset-react-native` to 2.0.0, so I'm not sure if it was the combination or just switching to `yarn`.

**Comment by spiskommg** [comment] 2017-07-12 19:56
yes yes yes! @kaxline i agree with your yarn theory. relying on that as well as downgrade babel-preset-react-native@2.0.0, react@045.1, and moving /node_modules/react-native/packager/react-native-xcode.sh 
to =>  
/node_modules/react-native/scripts/react-native-xcode.sh 

finally! i've been trying everything for the past few hours.

**Comment by HelloEdit** [comment] 2017-07-12 21:01
I upgrade my project to RN 0.46.1, and it's work !

**Comment by anhngd** [comment] 2017-07-13 09:30
@kaxline Thank you. It worked for me!

**Comment by arufian** [comment] 2017-07-20 21:52
@HelloEdit updated to 0.46.1 didn't work for me.

Is there any clear solution ?, I don't want to downgrade `babel-preset-react-native` every time I set  `redux-saga` for  my react-native app.

**Comment by HelloEdit** [comment] 2017-07-21 12:25
↪️ @arufian Hum...Just change the version did not work for me, I had to regenerate a new project (with [ignite](https://github.com/infinitered/ignite)) with RN 0.46.2

**Comment by dioxide** [comment] 2017-07-23 21:17
The problem always in RN 0.46.4

**Comment by HelloEdit** [comment] 2017-07-23 21:22
@dioxyde Have you tried 0.46.2 ? It's work like a charm for me 👍

**Comment by Amurmurmur** [comment] 2017-07-23 21:52
@dioxide Running RN 0.46.4 with babel-preset-react-native 2.0.0 just fine.

Try reseting the packages with `npm start -- --reset-cache`

**Comment by tugorez** [comment] 2017-07-26 18:53
Another workaround pointed by [Markus](https://github.com/markusguenther) in https://github.com/facebook/react-native/issues/14933 which doesnt require downgrade the babel preset is to use variables

so instead of 

```javascript
function* foo() {}
```
do 

```javascript
const foo = function* () {}
```

**Comment by sayhei** [comment] 2017-08-05 08:05
oh no,this solutions all not work for me

**Comment by Amurmurmur** [comment] 2017-08-06 14:36
@sayhei 
![imposibru](https://user-images.githubusercontent.com/8608333/29004271-6da9e6f8-7acd-11e7-8e20-e59b4fe0d752.jpg)
Most likely you have to:
clean yarn/npm cache
install babel with `yarn add babel-preset-react-native@2.0.0` 
run React-native packager with `npm start -- --reset cache`,  and rebuild the debug/release builds

**Comment by Noitidart** [comment] 2017-08-09 14:37
In RN 0.47.1 even just doing this:

```
function* upAsyncWorker(action: UpAsyncAction) {
/// ...
}
```

Without an export is causing this error. I fixed it by doing the `const` trick above. So this works now:


```
const upAsyncWorker = function* upAsyncWorker(action: UpAsyncAction) {
/// ...
}
```

**Comment by Amurmurmur** [comment] 2017-08-09 15:22
The only question I have is that, the const way of exporting sagas, going to be the standard now? Or next babel-present release will fix that ?

**Comment by Dimon70007** [comment] 2017-08-14 18:21
> Another workaround pointed by Markus in #14933 which doesnt require downgrade the babel preset is to use variables so
> 
> instead of
> 
> function* foo() {}
> 
> do
> 
> const foo = function* foo() {}
is work for me too, but only on latest versions of react-native and babel-preset-react-native. I am happy)))

**Comment by fernandopasik** [comment] 2017-08-16 13:22
I tried babel-preset-react-native v3.0.0 and still see the same issue

**Comment by HelloEdit** [comment] 2017-08-16 13:39
Hello @brentvatne, this issue is apparently always present... Consider its re-opening please : )

**Comment by gibo** [comment] 2017-08-17 19:30
is still an issue in react-native .47
tried downgrading to babel-preset-react-native v2.0.0

**Comment by shenjunru** [comment] 2017-08-18 14:44
This issue caused by commits:
* e7c1cf5b7d2eba9468804635d0c2a0fc6725e42a added a new babel transformer (babel-preset/transforms/transform-regenerator-runtime-insertion.js)
* 3103258ca0fd2fb0fda0da1120d9cdf4baf0ca05 cherry-pick of 361f03badb2080c009080312bbf45a7372b6a387  removed `global.regeneratorRuntime`. But, this commit has been reverted.

This code will be inserted by babel.  And the order of variables causes the `undefined` issue. 
```javascript
var _marked = regeneratorRuntime.mark(...);
var regeneratorRuntime = require("regenerator-runtime"); // inserted by the new transformer
```

**Comment by HelloEdit** [comment] 2017-08-18 15:21
Yep it's good solution while waiting for a patch of presets
Nobody knows if it will happen soon?

**Comment by Noitidart** [comment] 2017-08-18 21:46
> Hello @brentvatne, this issue is apparently always present... Consider its re-opening please : )

Oh wow I'm super surprised to see this closed. Closing this says "no we don't want to support the standard established syntax". Is there a valid reason like the empty object assign?

**Comment by HelloEdit** [comment] 2017-08-18 21:53
Hello @Noitidart,
I'm definitely a bit naive but I think it's just a bug, not a stuff like "change everything and say nothing to anyone".
If a member of the react team wanted to give us an answer, we would all be happy I think...

**Comment by HelloEdit** [comment] 2017-08-18 21:54
PS: I absolutely do not know how the Facebook bot works for Github, we can not ask him to reopen the issue?

**Comment by shenjunru** [comment] 2017-08-19 00:59
Hi @mjesun, could you follow this issue, either improve the transformer or remove it.
Thanks.

**Comment by brentvatne** [comment] 2017-08-20 21:53
hello! this seems to be a problem for everyone using redux-sagas, I don't use it and I don't really touch this part of the code so if someone wants to fix it, that would be great. please include a unit test in the fix so it doesn't regress in the future.

**Comment by matt-oakes** [comment] 2017-08-20 22:50
@brentvatne Thanks for reopening this!

If I'm understanding the commits @shenjunru posted correctly (thanks!) this is what I think has happened:

https://github.com/facebook/react-native/commit/3103258ca0fd2fb0fda0da1120d9cdf4baf0ca05 Removed the global for regeneratorRuntime
https://github.com/facebook/react-native/commit/e7c1cf5b7d2eba9468804635d0c2a0fc6725e42a added a new babel transformer which should have added the `require("regeneratorRuntime")` where needed, however, this plugin adds in _after_ the `var _marked = regeneratorRuntime.mark(...);` line, leading to the error.

I know absolutely nothing about babel transformers, but I would imagine this means that the fix needs to be in the `babel-preset/transforms/transform-regenerator-runtime-insertion.js` file.

If no one with some experience of babel is able to take this up, I can give it a go, but it might take me a bit of research.

**Comment by shenjunru** [comment] 2017-08-21 04:18
@matt-oakes The simplest way to fix this issue, just revert the commit e7c1cf5b7d2eba9468804635d0c2a0fc6725e42a 😉

**Comment by matt-oakes** [comment] 2017-08-21 08:02
@shenjunru Maybe I'm misunderstanding, but wouldn't something like that transformation be needed now that there is no global for `regeneratorRuntime` because of https://github.com/facebook/react-native/commit/3103258ca0fd2fb0fda0da1120d9cdf4baf0ca05?

**Comment by shenjunru** [comment] 2017-08-21 08:57
@matt-oakes
Commit 3103258ca0fd2fb0fda0da1120d9cdf4baf0ca05 has been reverted. So the `regeneratorRuntime` became global again.
And commit e7c1cf5b7d2eba9468804635d0c2a0fc6725e42a (transform-regenerator-runtime-insertion) is not necessary anymore.

**Comment by matt-oakes** [comment] 2017-08-21 09:08
@shenjunru That makes sense! Just to confirm, this is the commit which reverted it https://github.com/facebook/react-native/commit/737abe3b7603e27a1a88498b3a260d67fa747ee7#diff-3edd4dd9f4a04de3c7b2f2f12caa6cdc (19th July 2017) and therefore should be in the 0.48.0-rc.0 release.

**Comment by mjesun** [comment] 2017-08-21 09:26
Hi @matt-oakes , @shenjunru!

First off, sorry for the late reply; it's been a busy weekend. Thanks for taking care of the revert; I'm sorry this code was still here because we also experienced internally some issues and we were almost certain it was reverted (which obviously, it was not). We also had a previous try where we tried adding it but we also had to revert so that is what probably caused the confusion :(

Either way, thanks once again for taking care of it! :)

**Comment by matt-oakes** [comment] 2017-08-21 10:03
@mjesun I have just opened a PR (#15584) which reverts that commit and removes the unnecessary transformer. Hopefully, this is correct and fixes the issue!

**Comment by mjesun** [comment] 2017-08-21 17:15
That should do the trick, yes :)

**Closed** 2017-08-23 15:07 UTC
Labels: Ran Commands

**Comment by ide** [comment] 2017-08-23 20:12
I published babel-preset-react-native@3.0.2-rc.0 with the latest code. Please try it out and if it's working well we can publish 3.0.2.

**Comment by matt-oakes** [comment] 2017-08-24 06:44
@ide That version seems to work great! Thanks for publishing it!

**Comment by michaelduminy** [comment] 2017-08-24 09:09
@ide Confirmed it's working! Thanks

**Comment by BrutHellman** [comment] 2017-08-24 10:48
@ide Thanks!!! `babel-preset-react-native@3.0.2-rc.0` is working!

**Comment by Palisand** [comment] 2017-08-29 21:12
@ide Is 3.0.2 ready to publish?

**Comment by ide** [comment] 2017-08-30 03:28
Thanks for confirming, everyone. I published `babel-preset-react-native@3.0.2` (dist-tag = latest) as well as v2.0.1 with this fix.

**Comment by nonotest** [comment] 2017-09-04 13:31
still got issues on latest RN even with the latest preset

**Comment by Manuelandro** [comment] 2017-09-04 16:49
Same issue here.
RN: "0.47.2"
babel-preset-react-native: "2.0.0"

Any help?

**Comment by michaelduminy** [comment] 2017-09-04 16:58
@Manuelandro update to babel-preset-react-native 2.0.1 or 3.0.2

**Comment by Manuelandro** [comment] 2017-09-05 09:46
@michaelduminy  thanks for your suggest but it still doesn't work. Neither 3.0.2 or 2.0.1 

![schermata 2017-09-05 alle 11 44 21](https://user-images.githubusercontent.com/3776546/30055456-d045a076-922f-11e7-9aa2-772e1be3c47a.png)

**Comment by fengshuo** [comment] 2017-09-06 00:51
same issue here
react-native: 0.47.2
"babel-preset-react-native": "^3.0.2"

**Comment by tibbus** [comment] 2017-09-06 09:10
I had the same issue using 2.1.0 and downgraded to 2.0.0 which fixed the issue.

Now for some reason it doesn't work anymore with 2.0.0 😕

**Comment by Manuelandro** [comment] 2017-09-06 11:07
@fengshuo thanks, but already tried and didn't work. 
I'm with Expo create-react-native-app, maybe it adds some to this issue

**Comment by webwelten** [comment] 2017-09-06 20:17
Same here, also coming from Expo create-react-native-app.

**Comment by Palisand** [comment] 2017-09-06 23:09
@fengshuo @webwelten I believe you (and I) are going to have to wait and see if this gets updated in SDK 21, or for`babel-preset-expo` to get updated... or you can try and not use the default crna _`.babelrc`_ and set the preferred, non-decorator-refactor-requiring preset. You will have to account for `@expo/vector-icons` though; see [this comment](https://github.com/tleunen/babel-plugin-module-resolver/issues/167#issuecomment-299635336) and the one below it.

**Comment by Manuelandro** [comment] 2017-09-08 09:05
Just to let you know that i solved ejecting from Expo

**Comment by HelloEdit** [comment] 2017-09-14 15:23
Hello @arminsal1 try `AppRegistry.registerComponent('VIVA', Home);`

**Comment by SudoPlz** [comment] 2017-09-15 16:44
I'm using react-native **0.48.3** and what fixed it for me is the following steps (all of them not sure which one was the most important):

1) I created a `.babelrc` file with the following contents in the root of the project
```javascript
{
  "presets": ["react-native"]
}
```
2) I installed babel-preset-react-native@**3.0.2**
3) I ran `npm start -- --reset-cache`

Problem is now gone.

**Comment by arminsal1** [comment] 2017-09-15 17:27
@SudoPlz How do I create a .babelrc file?

**Comment by SudoPlz** [comment] 2017-09-15 17:50
@arminsal1 Open a terminal, `cd` to your project dir and type `touch .babelrc`

**Comment by arminsal1** [comment] 2017-09-15 18:22
@SudoPlz Your solution solved my problem, thank you so much!

**Comment by SudoPlz** [comment] 2017-09-15 18:26
I'm glad, :)

**Comment by eneskaya** [comment] 2017-09-18 09:39
@SudoPlz, thanks. This did the trick finally. Can you explain also why only after this it starts to work?

**Comment by deot** [comment] 2017-10-07 03:29
@ernoaapa  Thanks

**Comment by rainjm** [comment] 2017-11-09 02:18
```
watchman watch-del-all
rm -rf ./node_modules
rm -rf $TMPDIR/react-*
npm i babel-preset-react-native@2.0.0 -D -S
npm install
npm start -- --reset-cache
react-native run-ios

```

From：
https://stackoverflow.com/questions/45155249/when-using-redux-saga-with-react-native-web-we-get-an-error-cannot-read-propert

ps:
First remove `package-lock.json` or yarn.lock because other packages may also use `babel-preset-react-native`, **and you can open the lock file to check that they depend on the `babel-preset-react-native`, which may be the locked version 2.1.0**

**Comment by csuermann** [comment] 2017-11-10 12:15
I ran into this error using _babel-preset-expo_ and fixed it by switching to _babel-preset-react-native_: 

`yarn add babel-preset-react-native` 

in _.babelrc_:
```
"presets": [
    "babel-preset-react-native"
  ]
```

**Comment by karllson** [comment] 2017-11-12 11:27
@csuermann Thanks! That worked for me!

**Comment by brentvatne** [comment] 2017-11-15 01:50
what sdk version were you using @csuermann? this shouldn't be a problem with latest version of expo

**Comment by csuermann** [comment] 2017-11-15 07:45
@brentvatne:
`"sdkVersion": "21.0.0"`

**Comment by wvmitchell** [comment] 2017-11-18 18:19
@brentvatne I am running into the same issue with sdkVersion "22.0.0"

It seems that the version of babel-preset-react-native that babel-preset-expo depends on is 2.1.0. Per what I've read above, this may be causing the problem (and downgrading to 2.0.0 is a potential solution)

**Comment by mlukasch** [comment] 2017-11-28 11:07
I have a bug in the Expo's Font.loadAsync dependency. It uses async and I get this error:
![bildschirmfoto 2017-11-28 um 12 06 45](https://user-images.githubusercontent.com/17597578/33316562-a4d28606-d434-11e7-84e6-0a2c71af9b20.png)
Please help me. Im on time pressure. Thanks

**Comment by JulienMalige** [comment] 2017-11-29 21:35
@SudoPlz 
`node node_modules/react-native/local-cli/cli.js start --reset-cache`  works for me !! 😁

``` 
"babel-preset-react-native": "^4.0.0",`
"react-native": "^0.50.4",
"react": "16.0.0"
```

**Comment by Pokute** [comment] 2018-01-08 16:22
Please note that this also error might also happen with old code (react native 0.44 and about as old babel-preset-react-native) if using Node >= 9.

A fix is to use any Node <9 version which might be a lot easier than upgrading react native.

**Comment by angeloocana** [comment] 2018-01-26 19:54
@Pokute  I downgraded Node from 9 to 8, and it worked for me! 
Thank you!!!
