### ISSUE TITLE
RCTContextExecutor designated initializer is confused

### ISSUE THREAD

**Issue by jwyld** [facebook/react-native#1010] opened 2015-04-24 23:19 UTC
The header doesn't mark -initWithJavaScriptThread:globalContextRef: as it's designated initializer.  In fact, it steers callers away.  This would tend to make a caller assume -init is the designated initializer.  Looking at the code though, -init does funnel through -initWithJavaScriptThread:globalContextRef:.

BTW, I'm hitting this when trying to supply a custom thread for JS.  RCTBridge calls -init.  This forces me to override  -initWithJavaScriptThread:globalContextRef: to ignore the thread and create mine in place.

**Comment by nicklockwood** [comment] 2015-04-24 23:53
I'm curious what the use case is for setting a custom thread?

**Comment by jwyld** [comment] 2015-04-25 12:07
multiple, non-interfering contexts

**Comment by nicklockwood** [comment] 2015-04-25 13:24
Hmm. The fact that all RCTContextExecutors share a single thread is probably a design error. It dates back to when we had to create seperate bridges for each rootView, but now I think it would be better if each RCTContextExecutor created its own thread instance.

@tadeuzagallo would you agree with that?

@jwyld would that be a more straightforward solution to your requirement?

**Comment by tadeuzagallo** [comment] 2015-04-25 13:48
@nicklockwood Every `RCTContextExecutor` has its own thread right now.

If I understand correctly the problem is that `RCTBridge` calls `- [RCTContextExecutor init]` instead of `initWithJavaScriptThread:globalContextRef:`, but that shouldn't really matter, because it's created internally by the bridge, you wouldn't have access to it anyway... What you really need is what we spoke about on the other thread, the ability to provide a custom executor.

As for the header note, I think it's perfectly correct. It says `"You probably don't want to use this; use -init instead"`, what I believe is true, most of the people won't create their own thread.

**Comment by jwyld** [comment] 2015-04-25 13:49
That would solve my issue.

The next issue uncovered for me though, which I haven't filed, is the methodQueue (previously shadowQueue) must be shared by the bridge instances.  +[RCTConvert UIColor:] has a shared cache which is not thread safe.  I bring up the issue to highlight that all of react-native may not be prepared to run this way.  If I can get a multithreaded executors with a single methodQueue, I'm fine with that solution.  I'm really out to prevent the multiple JS contexts from stalling each other.

**Comment by jwyld** [comment] 2015-04-25 13:55
@tadeuzagallo I believe specifying the custom executor would be fine.  My issue is that if -init is the designated initializer on RCTContextExecutor, then -initWithJavaScriptThread:globalContextRef: should go through it.  To provide my own RCTContextExecutor subclass, I need to override the designated initializer, or I need to override or funnel both in order to prevent the com.facebook.React.JavaScript thread from being used.

**Comment by tadeuzagallo** [comment] 2015-04-25 13:59
@jwyld `-init` is not the designated initializer. There's no designated initializer actually, you can override and just call `- [super initWithJavaScriptThread:globalContextRef]`. You'd indeed have to override `- init` as well. I'll look into it though.

**Comment by tadeuzagallo** [comment] 2015-04-25 14:04
Thanks for raising this other issues, I'll look into it, totally makes sense. We're really not ready to support multiple instances of the bridge running concurrently, the design in theory supports, but it's very likely that you'll find some more issues like that, since it haven't really been used like that yet. But we've been looking into that issues, and most of my time I've spending in fixing multithreading issues, so feel free to ping me when you hit those issues and we'll look into it.

**Comment by jwyld** [comment] 2015-04-25 14:12
There is no explicit designated initializer.  Subclassers must implicitly override.  If RCTContextExecutor is to be subclassed, -initWithJavaScriptThread:globablContextRef: should be declared as the designated initializer.  The stern warning can be kept on it though.

Part of the issue is that the Class is used as the interface to RCTBridge.  RCTBridge makes the choice to call -init.  A subclasser must understand -init is called, but they must call -[super initWithJavaScriptThread:globalContextRef:] from their -init override or they must override -initWithJavaScriptThread:globalContextRef: call the super method anyhow.

Ultimately, the initialization sequence for RCTContextExecutor needs to be more explicit for subclasses.  That's really what I'm trying to get here.

**Comment by tadeuzagallo** [comment] 2015-04-25 14:18
Sure, I totally agree, I'll update that. As for how the context is initialized, that's part of the issue of how to provide custom executors, that has to basically solve how you can provide N custom executors, that might have custom initializers, and need to show up in the dev menu (and still be able to use the core executors)

**Comment by jwyld** [comment] 2015-04-25 14:23
What if a context executor factory was used as the API instead of the actual class?  The factory could be called to provide the context whenever a new one was needed.  This puts the creation and initialization entirely in the hands of the subclass.

**Comment by tadeuzagallo** [comment] 2015-04-25 14:25
And how would we list the executors to show in the dev menu? How would the factor know which executor we want? Also, maybe the executors should be bridge modules, they behave as such.

**Comment by jwyld** [comment] 2015-04-25 14:36
The factory could be the class/subclass itself.  Enforce the requirement using a protocol which requires class methods for population of the dev menu as well as creation and other things as you expand.

Something along the lines of:
@protocol ClassProtocol <NSObject>
@required
+ (NSArray*)provideAList;
+ (id)createSomething;
@end

Your property on the bridge is declared as Class<ClassProtocol>.

**Comment by jwyld** [comment] 2015-04-25 14:41
BTW, RCTCreateExecutor got close to this, but it's outside the realm of override.

**Comment by tadeuzagallo** [comment] 2015-04-25 18:28
I'm sorry, just going back a little bit, @nicklockwood was right, by default, if you just call `-init`, all the instances will share the same thread. What I meant is that they're not forced to share the same thread, since you can pass it into the initializer, but since it's created internally by the bridge, the end result is that they share the same thread indeed.

**Comment by brentvatne** [comment] 2015-05-29 21:10
Can we close this @tadeuzagallo?

**Comment by jwyld** [comment] 2015-05-29 21:13
Based upon changes on master (actually in latest release), things are good for my needs.

**Comment by tadeuzagallo** [comment] 2015-05-29 21:14
:+1:

**Closed** 2015-05-29 21:51 UTC
