### ISSUE TITLE
When I use AsyncStorage.getItem() not able to retrieve a specific field in return value.

### ISSUE THREAD

**Issue by ShailajaV** [facebook/react-native#14242] opened 2017-05-29 16:34 UTC
Stored objected is: { name: 'Chris', age: 30, traits: { hair: 'brown', eyes: 'brown' }, };
 not able to retrieve value.propertyName.

AsyncStorage.getItem('key').then( (value) => console.log('value ', value, 'name is ', value.name));

output is : value {"name":"Chris","age":30,"traits":{"hair":"brown","eyes":"brown"}} name is undefined.

Please let me know how to retrieve a specific value from promise object

**Comment by hramos** [comment] 2017-05-30 18:07
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-05-30 18:07 UTC
