### ISSUE TITLE
ListView separator line skips every other row

### ISSUE THREAD

**Issue by agersoncgps** [facebook/react-native#13959] opened 2017-05-13 18:46 UTC
I am running "react-native": "0.43.4". I searched StackOverflow and found [this post](http://stackoverflow.com/questions/38012355/reactnative-listview-inconsistent-separator-lines) describing it as bug with only a hack fix.

Here is my style for the separator:
```
const styles = StyleSheet.create({
  separator: {
    flex: 1,
    height: StyleSheet.hairlineWidth,
    backgroundColor: '#8E8E8E',
  },
});
```

Here is my ListView:
```
  <ListView
            dataSource={this.state.dataSource}
           renderRow={(data) => <View><Text>{data.bb_first_name}</Text></View>}
            renderSeparator={(sectionId, rowId) => <View key={rowId} style={styles.separator} />}
          />

```

Here is how it renders:
![screenshot 2017-05-13 14 41 14](https://cloud.githubusercontent.com/assets/336441/26028234/7295a5ec-37ea-11e7-9135-388d10316340.png)

**Comment by MyGuySi** [comment] 2017-05-15 07:40
Just out of curiosity, are you viewing the simulator at 100%? Anything less than that will cause hairline width details not to render correctly because of the downscaling

**Comment by hramos** [comment] 2017-05-15 18:55
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-05-15 18:55 UTC

**Comment by agersoncgps** [comment] 2017-05-15 23:30
Thanks MyGuySi, that was it!

**Comment by MyGuySi** [comment] 2017-05-16 05:24
@agersoncgps No problem, it's caught me out a few times too!
