### ISSUE TITLE
[PACKAGER] Current master does not successfully start packager.

### ISSUE THREAD

**Issue by admmasters** [facebook/react-native#3262] opened 2015-10-07 10:08 UTC
Not sure if this is a new known regression, but I'm getting the below error after updating to the current master:
```
*******/ReactNative/*******/node_modules/react-native/packager/react-packager/src/Server/index.js:199
      );
      ^

SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Module._extensions..js (module.js:452:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Volumes/Developer/Qinec/ReactNative/PatientApp/node_modules/react-native/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Volumes/Developer/Qinec/ReactNative/PatientApp/node_modules/react-native/packager/react-packager/index.js:16:14)
    at Module._compile (module.js:434:26)
```

**Comment by admmasters** [comment] 2015-10-07 10:27
Presumably this is a breaking change around specifying platform?

**Comment by admmasters** [comment] 2015-10-07 10:30
Ok looks like 7ad418a396994324764f19907b86f4d3c5b39e41 has broken this - as commented on. Feel free to close, but this change should be documented.

**Comment by nsimmons** [comment] 2015-10-07 21:02
Just ran into the same issue. It's preventing me from testing my PR @martinbigio.

**Comment by ide** [comment] 2015-10-07 21:03
Thanks for opening an issue @admmasters

**Comment by martinbigio** [comment] 2015-10-08 14:47
I can't get a repro by getting a fresh clone of the repo running
> npm install
> npm start

I must be doing something wrong, @admmasters could you provide me repro steps?

However I've seen this past 2 or 3 days errors with trailing commas, like the one you mention, so most likely the mentioned change somehow broke the use of `.babelrc` which configures support for `es7.trailingFunctionCommas`.

Thanks for reporting this I'll fix it asap!

**Comment by martinbigio** [comment] 2015-10-08 14:49
It might be related to where the `babelrc` is..

**Comment by sebmck** [comment] 2015-10-08 15:56
The issue is that by default `babel/register` has an `ignore` of `node_modules` when neither `ignore` or `only` are specified. The removal of the `only` option in 7ad418a396994324764f19907b86f4d3c5b39e41 causes all files inside of `node_modules` to be ignored.

**Comment by sebmck** [comment] 2015-10-08 15:57
Also if it makes it any easier, the `only`/`ignore` option can be a function if you want to do a more dynamic check eg:

```javascript
require("babel/register")({
  only: function (loc) {
    // return true if you want this file to be transformed
    return false;
  }
});
```

**Comment by martinbigio** [comment] 2015-10-08 16:41
Thanks @sebmck. Fix coming out soon.

**Comment by ide** [comment] 2015-10-09 11:39
Fixed in https://github.com/facebook/react-native/commit/32b62ef055e1a99211860d0ca0b0c41fbf529757?

**Comment by martinbigio** [comment] 2015-10-09 14:26
Yes, it's already fixed. Sorry for missing the original mention. I was getting way to many github notification.. Just tune the config to get a reasonable :)

**Closed by martinbigio** 2015-10-09 14:26 UTC
Labels: Packager, Regression
