### ISSUE TITLE
Using the Animated.Flatlist or Animated.ScrollView to animate an Animated.View is not smooth

### ISSUE THREAD

**Issue by KakarN** [facebook/react-native#15769] opened 2017-09-03 08:41 UTC
### Is this a bug report?
Yes

### Environment

1. ` react`: 16.0.0-alpha.12,
1. `react-native -v`: ^0.47.0,
2. `node -v`: v7.7.3
3. `npm -v`: 4.1.2
4. `yarn --version`: 0.21.3

- Target Platform:
iOS and Android

- Development Operating System:
macOS

- Build tools:
expo

### Steps to Reproduce

1. Created an animated component of FlatList.
2. Used the `onScroll` function to update the animated value.
3. Placed a view (Animated.View) as the header above the animated FlatList using position absolute.
4. Interpolate the animated value to change the view (Animated.View) using transform properties.

### Expected Behavior

I [saw this issue](https://github.com/facebook/react-native/issues/14037) of how using `scrollEventThrottle` helps the smoothness. So I thought using FlatList would be smooth.

### Actual Behavior

However, when scrolling the FlatList, the animated view does animate, but the animation is not smooth. If your scroll while pressing, it's smooth. But if you scroll and leave the finger, it's jumpy ( I don't know how to describe it. Sorry). The animated view (Header) animation is not smooth at all.

### Reproducible Demo
Snack link for animated FlatList and animated header
[Animated Flat List](https://snack.expo.io/HySw-PtY-)

**Update**

So, I tried to implement the same functionality using ScrollView. However, I think, its even worse using ScrollView when compared to FlatList.

[Here is the expo snack demo: Animated ScrollView Header](https://snack.expo.io/BJYG3iFFZ)

I think I need to mention how I got here at the first place. So, I tried to implement this by a [very nice tutorial in Medium](https://medium.com/appandflow/react-native-scrollview-animated-header-10a18cb9469e), and also by watching this [awesome youtube react conf viedo](https://www.youtube.com/watch?v=pZCriZRuaow) by @brentvatne . However, the exact code used on youtube video has the same effect. Also, on the Medium tutorial, the author has given a [Link to his expo Animated header link](https://exp.host/@janic/scrollable-header), which works very smoothly on the device. But the same code doesn't work smoothly when I copy paste the code and test it. So, I think the problem is with the react or react native version. I will update if I have any new update. Thank you.

**Comment by KakarN** [comment] 2017-09-03 16:39
****

**Comment by jevakallio** [comment] 2017-09-03 17:32
I can reproduce this, seems like binding `Animated.Views` to  ScrollView scroll position with `Animated.event` and `userNativeDriver` has gotten deoptimised. Doing some bisecting on Snack, seems like this broke between Expo 18 (React Native 0.45) and Expo 19 (React Native 0.46). 

Between those versions, seems like there were two commits landed to Animated, both by @janicduplessis:
- https://github.com/facebook/react-native/commit/08f41bcbf4bfa208ce32572cb3e934a66fa97481
- https://github.com/facebook/react-native/commit/c87524e0a6f1b411adc3d54741f7ff58faa1e38a

The diff is https://github.com/facebook/react-native/compare/v0.45.1...v0.46.4#diff-f048d92ca0be679bc38d38147b311100

**Comment by janicduplessis** [comment] 2017-09-04 00:08
There has been a regression with scroll events on Android. https://github.com/facebook/react-native/commit/e964a7f4ef93fcadf5cfd1c269b77b13cb3be374 fixes it, I'll try to get it cherry picked in the next 0.48 patch.

**Comment by eladgel** [comment] 2017-09-05 09:28
This also happens on RN v0.46.4 ios

**Comment by bitcrumb** [comment] 2017-09-07 20:48
+1

I am experiencing this behavior on iOS as well. I also tried out setting scrollEventThrottle to 16. But the experience was still jittery.

**Comment by KakarN** [comment] 2017-09-22 04:13
I think this is solved with the new updates. I have tested this both with the ScrollView and FlatList, and it's fine now. 

@jevakallio Can you please confirm? So that I can close this issue?

**Comment by ssssssssssss** [comment] 2017-09-22 05:06
Looks good now.

**Comment by MSSPL-PiyaleeMaiti** [comment] 2017-09-22 06:44
@KakarN what is your version of react-native?

**Comment by bitcrumb** [comment] 2017-09-22 07:27
@KakarN Which version are you referring to? I would like to update as well since we are facing the issues too.

**Comment by bitcrumb** [comment] 2017-09-22 10:36
Thanks for the quick feedback. We updated our React Native version to 0.48.3 and it is inderdaad resolved. Thanks for pointing this out to us!

**Comment by KakarN** [comment] 2017-09-22 13:38
@bitcrumb No problem!

**Closed** 2017-09-22 13:38 UTC

**Comment by yaronlevi** [comment] 2017-12-19 14:17
The code in the expo link you attached saved me hours of googling and got me started quickly. Thank you!
