### ISSUE TITLE
AsyncStorage.getItem blocks when debugging remotely

### ISSUE THREAD

**Issue by bartolkaruza** [facebook/react-native#12830] opened 2017-03-09 16:08 UTC
### Description

In some situations when calling AsyncStorage.getItem, either with a callback, calling `then` or using `async await`, the proceeding callback is not called and the promise does not resolve. This only happens when the remote debugger is on.

result or error are not called below:
````
AsyncStorage.getItem('key')
      .then(result => console.log('result', result))
      .catch(e => console.log('err', e));
````

AFTER is not printed (and no error is thrown):
````
console.log('BEFORE');
const result = await AsyncStorage.getItem('key');
console.log('AFTER');
````

The same code above completes the first time (and several consecutive times) it is run in the same debug session but blocks at a later stage. The point in time where it starts blocking is consistent in my app, so there is a piece of context that I haven't found yet which is causing it. I will continue searching for this context. Are maybe others running into similar behavior?

No matter the availability of data, getItem should always resolve (or reject), right?

### Reproduction

I will keep trying to isolate the reproduction but so far I have not been able to cleanly reproduce, but in my full app, it is consistently occurring.

### Additional Information

This issue is occurring on both iOS devices and simulators. I haven't seen it on Android yet.
OS X 10.11.6
Xcode 8.2.1
React Native Debugger 0.5.6
React Native 0.42.0

```
  "dependencies": {
    "react": "15.4.2",
    "react-native": "0.42.0",
    "analytics-react-native": "^1.0.1",
    "axios": "^0.11.1",
    "bugsnag-react-native": "^2.0.2",
    "firebase": "^3.6.10",
    "moment": "2.17.1",
    "react-native-auth0": "^1.0.0-beta.1",
    "react-native-code-push": "^1.17.2-beta",
    "react-native-drawer": "^2.2.3",
    "react-native-gifted-chat": "https://github.com/immidi/react-native-gifted-chat",
    "react-native-loading-spinner-overlay": "^0.4.1s",
    "react-native-lock": "git+ssh://git@github.com/auth0/react-native-lock.git",
    "react-native-navbar-wrapper": "^1.0.0",
    "react-native-onesignal": "^3.0.2",
    "react-native-smart-badge": "1.1.1",
    "react-navigation": "1.0.0-beta.3",
    "react-redux": "^4.4.5",
    "redux": "^3.5.2",
    "redux-devtools-extension": "^2.13.0"
  },
  "devDependencies": {
    "babel-jest": "19.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "19.0.2",
    "react-test-renderer": "15.4.2",
    "remote-redux-devtools": "^0.5.7",
    "chai": "*",
    "chai-as-promised": "*",
    "colors": "*",
    "mocha": "*",
    "q": "*",
    "underscore": "*",
    "wd": "*",
    "eslint": "^3.1.1",
    "eslint-plugin-react": "^5.2.2",
    "eslint-plugin-react-native": "^1.1.0",
    "babel-eslint": "^6.1.2"
  }
```

**Comment by hramos** [comment] 2017-05-25 21:04
We're cutting down on the number of outstanding issues, in order to allow us to focus. I'm closing this issue because it has been open for over 60 days with no activity. If you think it should still be opened let us know why. PRs are always welcome.

**Comment by YouHan26** [comment] 2017-08-08 03:04
any update? see the same problem

**Comment by bartolkaruza** [comment] 2017-08-08 07:55
@YouHan26 This issue has stopped for me. Not sure what the reason is, but have you tried upgrading react native to the latest version?

**Comment by davidblurton** [comment] 2017-08-22 18:23
Still broken on react native 0.46.4 on a real device.

**Comment by davidblurton** [comment] 2017-08-23 10:48
@hramos please reopen. AsyncStorage is a key component of react native and it's currently unusable when debugging.

**Comment by mehdijjz** [comment] 2017-09-13 11:01
I'm experiencing the same issue. RN 48, Genymotion running android 7

**Comment by iamanam** [comment] 2017-11-23 22:54
i am having the same issue. Anyone had any solution>

**Comment by gosuperninja** [comment] 2017-11-25 20:20
This is happening for me fairly consistently with RN 0.50.3. I can refresh my app a couple times with the multiGet promise completing, but after that the promise no longer completes. Issuing a `react-native run-android` will allow the multiget to return. This is happening with an Android Emulator API version 26.

**Comment by Ble3k** [comment] 2017-12-14 10:16
Same issue, running running on nexus 5x api 23 (emulator), but when switch to nexus 6p api 23 (emulator) the problem **SEEMS** (I mean I don't know exactly, but tried to reload 10 times and didn't face the problem) disappear.

I think this problem should be payed attention.

**Comment by krean93** [comment] 2017-12-14 16:46
I have the same problem 
`console.log('beforereadtoken')
  try {
    let token = await AsyncStorage.getItem('fb_token');
  } catch(e) {
    console.log('there was an error');
    console.log(e);
  }

  console.log('afterreadtoken')`

The second console.log does not get printed, also no errors are printed

**Comment by matejukmar** [comment] 2017-12-18 23:05
I have same problem on Android. Statements after 'await' are never executed.

**Comment by Hades1996** [comment] 2017-12-26 16:13
Same problem here using node v8.8.1, npm v5.6, RN v0.50.4 and debugging using chrome 62.

I'm using a real device by the way

**Comment by afrakhan123** [comment] 2018-01-05 13:38
Hi this was happening to me until I ran "react-native run-android" again. I seem to need to do this everytime I import AsyncStorage to a new file.

**Comment by luhui** [comment] 2018-01-10 08:19
Same issue on Android with real device, after reload the device. When it happened, I must kill the app and relaunch. 

Can we re-open this issue? @bartolkaruza 

RN v0.51.0

**Comment by bartolkaruza** [comment] 2018-01-12 10:09
@hramos There seems to be regular activity on this issue on very recent versions, even though I have not experienced it myself recently. Could you re-open it?

**Comment by fatfatson** [comment] 2018-01-24 04:10
+1 Same issue on Android, have to restarting app

**Comment by nenti** [comment] 2018-01-24 18:03
This issue is also a regular problem that ocvures on `redux-persist` project. [Issue #603] (https://github.com/rt2zz/redux-persist/issues/603#issuecomment-360215088)

**Comment by DarkSmile92** [comment] 2018-02-18 15:58
Having the same issue out of the blue from one day to another without changing anything on my react-native project!

**Comment by acherkashin** [comment] 2018-02-24 11:12
+1 Same issue on Android 6, API Level 23. I resolve this issue by rerun 'react-native run-android'.

**Comment by amclelland** [comment] 2018-02-26 13:32
+1

**Comment by rohitranjan1991** [comment] 2018-02-27 14:24
+1. Any update on this ? This is a issue worth looking into. cannot go ahead with this for production apps.

**Comment by NomadGraphix** [comment] 2018-03-01 18:04
I've been able to confirm that this is as a result of some kind of blocking in Android when debugging with an emulator.

**Comment by NomadGraphix** [comment] 2018-03-01 18:04
A fix would definitely be nice.

**Comment by nmfzone** [comment] 2018-03-02 12:46
It's still happening, even in recent react native version. It's very annoying, why this issue not prioritize to solve?

**Comment by Joey33** [comment] 2018-03-03 12:35
If it would help you:

I discovered this issue only now after starting to use VSC debugger or RNDebugger. I've always debugged in Chrome before and never ever experienced any AsyncStorage failures. So I tried now a few times in Chrome (opening&closing remote debugging session from app) and in Chrome it's fine.

What else have I observed:
1. When you start debugging session in VSC/RND and never exit dbg mode, it's fine (though slow of course)
2. When you exit remote dbg and AsyncStorage gets screwed up, when you do 'react'native run-android' again the issue is gone

**Comment by carlos-pereira** [comment] 2018-03-06 17:39
+1

**Comment by gabrielmancini** [comment] 2018-03-07 00:20
even callback not work, there is no solution, for me its a very critical bug

**Comment by 0xc0d3r** [comment] 2018-03-08 11:24
+1

**Comment by emik** [comment] 2018-03-08 17:30
+1

**Comment by Bryze** [comment] 2018-03-09 08:33
This is indeed a very critical one, 
One workaround for debugging is - stop debugging, rebuild the app again

and check logs via `react-native log-android`
Also, the same logs can be checked at `logcat` in `android studio`

**Comment by Jono20201** [comment] 2018-03-09 14:55
This seems to have gotten worse now. Normally I could refresh a few times, but now it isn't working at all.

**Comment by NomadGraphix** [comment] 2018-03-09 18:08
Solution I currently have: 1. Launch app using android studio. 2. Quit android studio. 3. Restart app. 

Even this doesn't always work.

**Comment by Bryze** [comment] 2018-03-10 05:51
@Jono20201  try uninstalling and installing the app again?

**Comment by Jono20201** [comment] 2018-03-12 08:28
@Bryze Tired that. Even if that did work this needs to be addressed properly.

**Comment by lanlin** [comment] 2018-03-13 02:47
RN: 0.55.2
@all what's wrong with AsyncStorage? it's not working, even I've closed the remote debugger and none errors showing here.

**Comment by alwex** [comment] 2018-03-14 00:31
Same issue here with RN 0.53.3, this is a very critical bug even in non debug mode.

**Comment by hjJunior** [comment] 2018-03-15 12:14
Same issue here with RN 0.54.0, any updates?

**Comment by mvayngrib** [comment] 2018-03-19 19:16
in case it helps anyone:

on ios simulator and iphone 6+, it works for me with:
  React Native Debugger (0.7.17)
  react-native 0.53.3

but not with dev tools

**Comment by uruir** [comment] 2018-03-22 03:39
the same problem
react-native 0.54.0-rc.3
debugging with true device

**Comment by reetou** [comment] 2018-03-22 14:29
Happens every time for me, very painful because my app is working with AsyncStorage and restarting app every time I need to test my code hurts me at bottom. `react-native run-android` helps but only for 1-2 calls of `AsyncStorage.getItem()` and then again its stuck. 
RN 0.53.3;

**Comment by KartikShankhavaram** [comment] 2018-03-23 07:10
Initially, asyncStorage showed up in Reactotron's timeline, but now, even that has stopped happening. There is no action whatsoever when I try to save or get any data from asyncStorage.

**Comment by lanlin** [comment] 2018-03-23 09:27
wow, there is still no response to this issue...

![qq c7qbl o18a0u 3 m](https://user-images.githubusercontent.com/3468024/37821679-40faa178-2ebf-11e8-8027-8416adfc9ee7.gif)

**Comment by reetou** [comment] 2018-03-23 09:42
Yep, pretty annoying. Any alternatives to async storage? Realm?

**Comment by MadalenaGoncalves** [comment] 2018-03-23 14:12
+1

**Comment by ZehraPunjwani** [comment] 2018-03-23 18:06
use react-native-async-storage-dev-menu-item if you wish to see your asyncStorage data in the console

**Comment by C0dekid** [comment] 2018-03-23 20:12
AsyncStorage stopped working for me too! I use to develop with a real device

Android 7.0
react-native-cli: 2.0.1
react-native: 0.54.2
react: 16.3.0-alpha.1

What is the solution to fix this issue?

**Comment by reetou** [comment] 2018-03-24 21:29
@mvayngrib Worked for some time, now it doesnt.

**Comment by superyarik** [comment] 2018-03-29 11:14
have same problem, android emulator, "react-native": "^0.50.0",

**Comment by xiechao06** [comment] 2018-03-30 07:52
I've met the same problem using emulator, But I found kill the debugging application, and reopen it, getItem won't block anymore

**Comment by ouabing** [comment] 2018-03-30 10:15
same here

**Comment by sojek** [comment] 2018-03-30 11:52
same here

**Comment by grzegorz-bielski** [comment] 2018-03-30 12:37
For me the only solution to debug AsyncStorage was ```react-native log-android```

**Comment by apcjs** [comment] 2018-04-02 10:39
This is pretty consistent for me. First time I run the app on the Android emulator, await AsyncStorage.getItem returns a value. The moment I hit RR to reload, execution stops at this line and any further calls to AsyncStorage.getItem also fail to fulfill the promise. The only way out is to run the app again using react-native run-android. Using version 0.54.2.

Its frustrating, I hope we get a fix for this soon.

**Comment by jo-va** [comment] 2018-04-03 22:48
Same problem here on a real Android device.

**Comment by sydneywu** [comment] 2018-04-10 03:02
I got the same problem on when running on android device. 

        try {
            userToken = await AsyncStorage.getItem(USER_TOKEN)
        } catch (error) {
            console.log('error is ', error);
        }
        console.log('userToken', userToken)

No error displayed. The console after this is not shown. Somehow AsyncStorage.getItem did not resolve or reject. Even when the remote debugging and it still does not work. This sounds like a core feature.

**Comment by Bolik** [comment] 2018-04-12 08:15
+1

**Comment by rococtz** [comment] 2018-04-12 09:30
Is there any alternative approach/module/library/workaround to this? Some simple key-value storage?

**Comment by izaa** [comment] 2018-04-16 07:07
+1

**Comment by massivebrains** [comment] 2018-04-17 09:40
+1

**Comment by HAMPLENI** [comment] 2018-04-17 23:49
At least on Android and on at least an emulator, after reloading the app by pressing 'r' twice or through the developer menu by clicking "Reload", I often run into this issue where the first `AsyncStorage.getItem` call never hits a `.then` or `.catch` chained off of it.

It does not matter for me whether a debugger is attached or not.

Closing the app and then starting it resolves the issue.  It is just very tedious and time consuming to do that often.

**Comment by Nyadesune** [comment] 2018-04-19 01:46
@sydneywu absolutely not

can confirm that after killing the app and then starting it again asyncstorage works fine

**Comment by C0dekid** [comment] 2018-04-20 07:04
Just fix the issue please, many people are waiting for it, thanks :)

**Comment by juniorjp** [comment] 2018-04-23 02:28
+1

**Comment by nartjie101** [comment] 2018-04-25 04:01
+1

**Comment by jean-ben-guigui** [comment] 2018-04-25 16:10
+1![bitmoji](https://render.bitstrips.com/v2/cpanel/b23e163b-0eea-495f-8a26-da0ccf648517-6e47ceb0-9505-4007-8d7b-b843bb1de264-v1.png?transparent=1&palette=1&width=246)

**Comment by nstanwar** [comment] 2018-04-27 04:14
+1

**Comment by patriciy** [comment] 2018-04-28 13:44
+1

**Comment by mtkhorma** [comment] 2018-05-01 01:08
as far as i know we cant use local storage in RN, so if we can't debug our apps when using Asyncstorage, what on earth we can do to store some data locally on the device?

**Comment by trexguo** [comment] 2018-05-05 08:56
+1

**Comment by dgarciamuria** [comment] 2018-05-08 15:02
+1

**Comment by gosuperninja** [comment] 2018-05-08 18:05
+1

**Comment by teraconsulting** [comment] 2018-05-09 17:35
+1

**Comment by ianbarnett8** [comment] 2018-05-10 11:01
+1

**Comment by LordShiroe** [comment] 2018-05-10 15:19
+1

**Comment by iamanam** [comment] 2018-05-11 15:14
This issue is opened for more than year but still nothing. That's really sad. Someone really need to look at it.

**Comment by clementm916** [comment] 2018-05-12 07:45
+1

**Comment by SurajMDurgad** [comment] 2018-05-12 15:54
+1

**Comment by nicolascoutureau** [comment] 2018-05-14 12:06
+1

**Comment by brunneus** [comment] 2018-05-14 18:51
+1

**Comment by cpojer** [comment] 2019-02-15 14:45
This issue has been moved to react-native-community/react-native-async-storage#11.

**Closed by cpojer** 2019-02-15 14:45 UTC
Labels: API: AsyncStorage, Help Wanted :octocat:, Type: Bug Report
