### ISSUE TITLE
Dirty upgrade to 0.43. Cannot link

### ISSUE THREAD

**Issue by sospedra** [facebook/react-native#13427] opened 2017-04-10 15:36 UTC
In addition to other reports onto 0.43.x problems #12261

I've spend the past 4 hours manual merging the `react-native-git-upgrade` conflicts. I'm pretty sure that all my files are ok, tho I still have issues like this one after linking.

```
Something went wrong while linking. Error: Expected "/*" or ";" but "\"" found.
Please file an issue here: https://github.com/facebook/react-native/issues
```

I can attach `*.xcodeproj` files and Android related ones.

**Comment by hramos** [comment] 2017-05-31 20:37
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-05-31 20:37 UTC
