### ISSUE TITLE
[MapView][detailCalloutView] Callout clips the content of the `detailCalloutView`, only shows it partially and outside of it

### ISSUE THREAD

**Issue by af7** [facebook/react-native#5488] opened 2016-01-22 18:54 UTC
Unfortunately, sometimes the `detailCalloutView` fails to **push** the callout bubble and make it larger, resulting in something like this:

![image](https://cloud.githubusercontent.com/assets/7850073/12519834/c0f36dd2-c149-11e5-8297-2bf659e8bd7c.png)

(an **extra image** was supposed to be shown **below the small flag**, plus **some text**)

This happens at random times but is very often. Not sure what *race condition* causes this but it is a bug which makes the use of the `detailCalloutView` impossible.

**Comment by iricketson** [comment] 2016-03-06 00:54
Is this a duplicate of #5435?

**Comment by af7** [comment] 2016-03-06 10:07
Yes it is eventually.

I ended up using `react-native-maps` which doesn't have this problem:
https://github.com/lelandrichardson/react-native-maps

Maybe you would like to see what they are doing there OR (even better) work together and merge it into `react-native`?

**Comment by mkonicek** [comment] 2016-07-29 23:18
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/mapviewdetailcalloutview-callout-clips-the-content-of-the-detailcalloutview-only-shows-it-partially-and-outside-of-it

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Closed by mkonicek** 2016-07-29 23:18 UTC
Labels: Icebox
