### ISSUE TITLE
onScrollAnimationEnd not firering

### ISSUE THREAD

**Issue by dvine-multimedia** [facebook/react-native#1324] opened 2015-05-18 05:47 UTC
I'n not sure if I'm missing something here, but I couldn't get onScrollAnimationEnd to fire. Neither with manual scrolling nor with scrollTo()

I'm using react-native 0.4.2 and a simulator with iOS SDK 8.3

Cheers
Georg

**Comment by christopherdro** [comment] 2015-05-19 14:57
Yea I've been having the same issue working with ScrollView the last couple of days.

Trying using onMomentumScrollEnd for now, this should get it working until the issue is resolved.

**Comment by christopherdro** [comment] 2015-05-28 06:32
#1410

**Comment by christopherdro** [comment] 2015-05-28 06:33
#1410

**Comment by brentvatne** [comment] 2015-05-29 18:14
@dvine-multimedia - silly me, I didn't search before opening my issue - thanks for the report! Given that I have more notes in the other issue, I'll close this instead

**Closed by brentvatne** 2015-05-29 18:14 UTC
