### ISSUE TITLE
TextInput : Unable to prevent chars to be added on iOS.

### ISSUE THREAD

**Issue by yairopro** [facebook/react-native#19252] opened 2018-05-14 16:31 UTC
- [v] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [v] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [v] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

It's impossible on iOS to prevent some new chars to be typed.
[**Here's a snack**](https://snack.expo.io/SJsmZ4DRM) where only numbers are accepted in the input. It works perfectly on android. No on iOS.

## Environment
  OS: macOS High Sierra 10.13.4
  Node: 9.11.1
  Yarn: 1.6.0
  npm: 6.0.0
  Watchman: Not Found
  Xcode: Not Found
  Android Studio: 3.1 AI-173.4720617

## Steps to Reproduce
1. Taking the text from `onChangeText` callback
2. Removing the new typed char if it's not accepted.
3. Updating the `TextInput`'s value using the `setState` method.

## Expected Behavior
Removing the char as soon as it's been typed. Works on Android.

## Actual Behavior
The non accepted char stays in the TextInput even though the component re-rendered assigning the corrected value to the `TextInput`.

**Comment by yairopro** [comment] 2018-05-14 16:50
It's already included.

**Comment by francisli** [comment] 2018-05-14 17:37
Maybe a duplicate of #18874 ...?

**Comment by yairopro** [comment] 2018-05-14 19:05
@francisli That's right. Sorry.
Should I close?

**Closed** 2018-05-15 21:55 UTC
Labels: :grey_question:Needs More Information, :large_blue_diamond:iOS, :large_orange_diamond:TextInput
