### ISSUE TITLE
Android version app crashes with <com.facebook.react.modules.dialog.SupportAlertFragment> is not accessible from java.lang.Class<android.support.v4.app.Fragment>

### ISSUE THREAD

**Issue by lesliesam** [facebook/react-native#7080] opened 2016-04-20 04:22 UTC
I am using RN 0.24 version and we got a stack trace of a crash and here it is:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tradehero.cfd/com.tradehero.cfd.MainActivity}: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment com.facebook.react.modules.dialog.SupportAlertFragment: make sure class name exists, is public, and has an empty constructor that is public
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2421)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
	at android.app.ActivityThread.access$900(ActivityThread.java:153)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5432)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:735)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
Caused by: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment com.facebook.react.modules.dialog.SupportAlertFragment: make sure class name exists, is public, and has an empty constructor that is public
	at android.support.v4.app.Fragment.instantiate(Fragment.java:438)
	at android.support.v4.app.FragmentState.instantiate(Fragment.java:102)
	at android.support.v4.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:1907)
	at android.support.v4.app.FragmentController.restoreAllState(FragmentController.java:135)
	at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:251)
	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:61)
	at com.tradehero.cfd.MainActivity.onCreate(MainActivity.java:37)
	at android.app.Activity.performCreate(Activity.java:6303)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2374)
	... 9 more
Caused by: java.lang.IllegalAccessException: java.lang.Class<com.facebook.react.modules.dialog.SupportAlertFragment> is not accessible from java.lang.Class<android.support.v4.app.Fragment>
	at java.lang.Class.newInstance(Native Method)
	at android.support.v4.app.Fragment.instantiate(Fragment.java:423)
	... 18 more

The fix should be very simple. But the class "SupportAlertFragment" is marked as 'package' intentionally and I am not sure if it would break anything else if I change it to public.

Please advise!

**Comment by grabbou** [comment] 2016-04-20 06:12
Are you trying to use it in your code or is that potentially coming from a 3rd party module?

**Comment by lesliesam** [comment] 2016-04-20 06:18
It is brought in by DialogModule, I guess there is a alert dialog been shown at the moment. 
And both AlertFragment and SupportAlertFragment are marked as package somehow. I assume that one might crash too.

**Comment by grabbou** [comment] 2016-04-20 07:13
If you could try to fix it locally first that would be awesome! 

What you can do is get latest master, compile Android from source (see this docs: https://facebook.github.io/react-native/docs/android-building-from-source.html#content), make that change and see if it works!

If it does - PR would be welcome with a quick steps to reproduce :)

**Comment by lesliesam** [comment] 2016-04-21 02:02
The reproduce steps are not 100% unclear right now.
The bug is found when user locks their phone for quite a long time and then reopen it. Then the app might crash with the given stack trace.

**Comment by lacker** [comment] 2016-10-21 02:07
Looks like this got fixed in https://github.com/facebook/react-native/pull/7105

**Closed by lacker** 2016-10-21 02:07 UTC
Labels: Android
