### ISSUE TITLE
Some components (ProgressBarAndroid and ToolbarAndroid) is not Mounting

### ISSUE THREAD

**Issue by holoto** [facebook/react-native#7915] opened 2016-06-03 15:33 UTC
# Some components useless 
## Genymotion setting
![Genymotion setting](http://7xv1u3.com1.z0.glb.clouddn.com/Screen%20Shot%202016-06-03%20at%2011.13.01%20PM.png)
## Screenshot,ps:Has Reload Js
![Screenshot](http://7xv1u3.com1.z0.glb.clouddn.com/Screen%20Shot%202016-06-03%20at%2011.10.36%20PM.png)
![Screenshot](http://7xv1u3.com1.z0.glb.clouddn.com/Screen%20Shot%202016-06-03%20at%2011.10.53%20PM.png)
### index.android.js
``` 
/*
* @Author: holoto
* @Date:   2016-06-03 22:19:53
* @Last Modified by:   holoto
* @Last Modified time: 2016-06-03 22:20:30
*/
// import React,{Component} from 'react';

import {
  AppRegistry
} from 'react-native';

import {ProgressBarAndroidDemo} from './MyCp/ProgressBarAndroidDemo';
import {ToolbarAndroidDemo} from './MyCp/ToolbarAndroidDemo';


AppRegistry.registerComponent('demo',()=>ToolbarAndroidDemo);
```
### in MyCp; ToolbarAndroidDemo.js
```
/*
* @Author: holoto
* @Date:   2016-06-03 21:10:07
* @Last Modified by:   holoto
* @Last Modified time: 2016-06-03 23:10:27
*/
import React,{Component} from 'react';
import {
	View,
	ProgressBarAndroid
} from 'react-native';
var ToolbarAndroid=require('ToolbarAndroid');
var ProgressBar=require('ProgressBarAndroid');
class ToolbarAndroidDemo extends Component{
	constructor(props) {
	  super(props);

	  this.state = {};
	}
	render(){
		return(
			<View>
			<ToolbarAndroid/>
			<ProgressBarAndroid
			styleAttr="Large"
			/>
			<ProgressBar/>
			</View>
			)
	}
};



export {ToolbarAndroidDemo};



```
## Other components can use

**Comment by damusnet** [comment] 2016-06-04 15:02
@facebook-github-bot duplicate #5293

Try setting a height to your `<ToolbarAndroid/>`. Also set styles to your view to fill the screen.

**Comment by damusnet** [comment] 2016-06-04 15:16
@facebook-github-bot duplicate #5293

**Comment by facebook-github-bot-9** [comment] 2016-06-04 15:20
@damusnet tells me this issue is a duplicate of #5293. Let's discuss there, closing this one.

**Closed by facebook-github-bot-9** 2016-06-04 15:20 UTC
