### ISSUE TITLE
[Android] CameraRoll groupTypes not supported on Android

### ISSUE THREAD

**Issue by filippofilip95** [facebook/react-native#15409] opened 2017-08-08 09:45 UTC
Hi, when define groupTypes for CameraRoll in react-native 45.1 it throws me groupTypes not supported on Android.

Is implementation of groupTypes for Android planned in the near future ? 
Thank for answer.

**Enviroment**
- react-native: 0.45.1
- node: 8.0.0
- yarn: 0.27.5

**Comment by hramos** [comment] 2017-08-08 18:41
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-08-08 18:41 UTC
