### ISSUE TITLE
app crashes when enabling remote JS debug (after updating to new RN version)

### ISSUE THREAD

**Issue by RyanWan** [facebook/react-native#14672] opened 2017-06-22 03:51 UTC
After updating to v0.45.1, the app crashes whenever I enable remote debugging. I tried to deleted all node_modules and reinstall them as well as reset simulator. Both are not helpful. In the end, I have to download to previous version and it just works fine. I am not sure how to deal with that.

**Comment by formatlos** [comment] 2017-06-22 07:05
Can you provide more information about your issue, I haven't had problems with remote debugging in v0.45.1. Which simulator are you using (iPhone 6, 7 ...), what iOS version are you on and please provide the system-logs (iOS Simulator > Menu Bar > Debug > Open System Log)

**Comment by tabrindle** [comment] 2017-06-22 16:25
If you run `npm i -g envinfo` then`envinfo --packages react,react-native`, you will get an output of all the relevant debug information like this:

```
Environment:
  OS:  macOS Sierra
  Node:  v7.10.0
  Yarn:  0.24.5
  npm:  4.2.0
  Xcode:  Xcode 8.3.3 Build version 8E3004b 
  Android Studio:  2.3 AI-162.3934792 
  react:  16.0.0-alpha.6
  react-native:  0.44.0
```

**Comment by RyanWan** [comment] 2017-06-22 18:18
OS:  macOS Sierra
  Node:  v4.4.0
  Yarn:  0.24.4
  npm:  4.2.0
  Xcode:  Xcode 8.2.1 Build version 8C1002 
  Android Studio:  2.3 AI-162.3934792 
  react:  ^16.0.0-alpha.12
  react-native:  ^0.45.1
Simulator: iPhone 6
iOS: 10.2

**Comment by aurnik** [comment] 2017-06-22 23:45
@RyanWan When you say you downgraded to the previous version do you mean 0.45.0?
This doesn't really solve your situation but I also was trying 0.45.1 with the debugger it seems like there are a lot of new issues introduced with performance.

**Comment by RyanWan** [comment] 2017-06-23 00:04
@aurnik  I downgraded to 0.44.0, the version I used before the upgrade

**Comment by Jacse** [comment] 2017-07-07 19:51
Experiencing this as well. Environment: 
````
Environment:
  OS:  macOS Sierra 10.12
  Node:  v8.1.3
  Yarn:  0.27.5
  npm:  5.0.3
  Xcode:  Xcode 8.3.2 Build version 8E2002
  Android Studio:  2.3 AI-162.3764568
Packages:
  react:  16.0.0-alpha.12
  react-native:  ^0.45.1
````

Error in logs: `fatal][tid:main] Exception '*** -[__NSArrayI objectAtIndex:]: index 2 beyond bounds [0 .. 1]' was thrown from JS thread`

**Comment by Jacse** [comment] 2017-07-07 19:52
For the record it happened after upgrading to `0.45.1` from `0.44`.

**Comment by Jacse** [comment] 2017-07-07 19:53
Duplicate of #14288

**Comment by hramos** [comment] 2017-09-21 15:09
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Closed by hramos** 2017-09-21 15:09 UTC
Labels: Icebox

**Comment by Albinzr** [comment] 2017-12-04 08:27
Still crashing

**Comment by llzz19851985** [comment] 2017-12-19 02:24
Still crash on version :0.50.3

**Comment by havinhthai** [comment] 2018-05-26 11:49
Still on version 0.55.4

**Comment by Albinzr** [comment] 2018-05-27 19:15
Im giving up on RN, Not worth for production apps

**Comment by SSTPIERRE2** [comment] 2018-06-07 19:53
I'm going to try using Expo next, but on 0.50.1 the remote debugging experience has been really bad on both platforms 🙁 Randomly I get RSOD so often saying "cannot connect to development server", or even a WSOD where the app doesn't load and in Xcode I get that classic thread 1: exception.

**Comment by brayanL** [comment] 2018-08-28 14:57
What is the solution? in a day of development with the debugger enabled my application dies at least 15 times.
