### ISSUE TITLE
[Webview] startInLoadingState={true}

### ISSUE THREAD

**Issue by smartdevth** [facebook/react-native#14440] opened 2017-06-10 10:23 UTC
I have an issue with startInLoadingState={true} on first load on web view (only iOS) it broke some javascript related to scroll position but when startInLoadingState is disable, everything is fine. I saw that the code in WebView.ios.js set Webview hidden when startInLoadingState is enable with style height=0. I think this causes the problem. 

NOTE: #{html_element_id} at the end of url won't scroll the page to that element too.

### Additional Information
RN: 0.43
Platform: iOS

**Comment by hramos** [comment] 2017-06-12 20:50
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed** 2017-06-12 20:50 UTC

**Comment by ShaikhKabeer** [comment] 2018-06-05 09:45
Hi @fokoz , How you solved this problem ? I'm also facing this one.
Here is my code snippet.

`<WebView
                  bounces={false}
                  source={{html:this.state.htmlResponse}}
                  startInLoadingState={true}
                />`

If we use startInLoadingState prop true then in iOS webView is not showing.

**Comment by fokoz** [comment] 2018-06-06 07:06
@ShaikhKabeer I decided to use ActivityIndicator instead of that prop and remove it in callback.
