### ISSUE TITLE
[0.28.0] - Native module cannot be null - Cannot find entry file

### ISSUE THREAD

**Issue by GantMan** [facebook/react-native#8449] opened 2016-06-27 00:41 UTC
Upgrading an app from 0.27.2 to 0.28.0 I get this message in simulator with no stack trace:
![image](https://cloud.githubusercontent.com/assets/997157/16366014/7632023e-3bd5-11e6-9e67-0716132653ca.png)

When I look at packager I get the message: 
```
NotFoundError: Cannot find entry file global code@http://localhost:8081/index.ios.js in any of the roots: ["/Users/gantman/Documents/Projects/rn/MyApp"]
    at DependencyGraph._getAbsolutePath (/Users/gantman/Documents/Projects/rn/MyApp/node_modules/node-haste/lib/index.js:288:13)
    at /Users/gantman/Documents/Projects/rn/MyApp/node_modules/node-haste/lib/index.js:226:30
    at process._tickCallback (node.js:379:9)
```

It looks like I'm not the only one: http://stackoverflow.com/questions/37999468/entry-file-error-in-react-native-from-packager/38044411

The stackoverflow issue claims this is due to dependencies that cannot handle 0.28.0 - which leads me to wonder what kind of error message would do that?

This is keeping our ignite project from progressing from 0.27.2 to 0.28 -> https://github.com/infinitered/ignite/issues/199

I've been trying to crack this nut for a few days, any feedback/help would be appreciated.  I'm currently going to init a new project and add dependencies one at a time to see if I can find the culprit.   Not a very fun process, but there doesn't seem to be a clear opportunity otherwise.

Thanks ahead of time for whomever helps.

**Comment by ashleydw** [comment] 2016-06-27 06:37
The dependency is probably using `require` instead of the new `import`. As in: https://github.com/facebook/react-native/releases/tag/v0.25.1

But strange if it worked in 0.27.2

**Comment by satya164** [comment] 2016-06-27 11:59
Closing since this issue is with a third party module (from the issue you linked to) and it should be filed with that module's repo..

**Comment by GantMan** [comment] 2016-06-27 14:07
@satya164 - don't you think the error message should be better?   Would that be a different issue to file?

**Comment by satya164** [comment] 2016-06-27 14:56
@GantMan Feel free to open a new issue if you manage to get a reduced test case of this.

**Comment by JohnyDays** [comment] 2016-07-01 11:25
Also having this problem, but only on iOS 😢

**Comment by aymericbouzy** [comment] 2016-07-01 17:42
Building with Xcode rather than running the command `react-native run-ios` solved it for me.

**Comment by kfiroo** [comment] 2016-07-03 14:24
I have a similar issue, you guys might have some insight.

My problem is with **react-native run-android** only, ios runs just fine.

My packager server is running, I can get **http://localhost:8081/index.android.bundle** in the browser.
When running **react-native run-android**, the build completes successfully but I get this error in my packager console:

> NotFoundError: Cannot find entry file global code@http://10.0.2.2:8081/index.android.js in any of the roots: [...]

the problem is that it seems to look for the index file in **10.0.2.2:8081** instead of **localhost:8081**.

Any idea where is this defined?

Thanks

**Comment by GantMan** [comment] 2016-07-03 14:45
Just to make sure the IP is the problem, neuter your initial screen from all `imports` outside of RN.   If it runs, then it's the same issue we've seen.   If it truly is the IP, look into the port/ip forwarding solutions many Android devs have worked with.

**Comment by JohnyDays** [comment] 2016-07-04 10:26
For the record, in my case this error was occuring because I had not correctly setup push notifications on my xCode project. As soon as I linked the library, the error disappeared.

**Comment by TheoGit** [comment] 2016-08-30 20:59
@JohnyDays I'm having same issue; could you please expound a little more on "not correctly setup push notifications on my xCode project" - how would I fix this???

**Comment by 7ynk3r** [comment] 2016-09-06 18:43
In my case I was following the steps in the docs for `Integration With Existing Apps`.

The example is broken. To fix it you need to add a pod subspec 

    pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'Core',
      'RCTText',
      'RCTWebSocket', # needed for debugging
      'RCTNetwork', # this is the missing one!!
      # Add any other subspecs you want to use in your project
    ]

**Comment by SandroMachado** [comment] 2016-10-14 13:27
Since #10358 was closed. I created #10389.

**Closed** 2016-10-14 14:14 UTC

**Comment by erichua23** [comment] 2017-03-03 06:36
I my case, since i used Navigator, the 'RCTLinkingIOS' subspec is needed, add it to Podfile and it works. 
``` oc
pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'RCTText',
  'RCTWebSocket',
  'RCTNetwork',

  'RCTLinkingIOS' # add this for Navigator
  # Add any other subspecs you want to use in your project
]
```
