### ISSUE TITLE
undefined is not a function (evaluating 'transform.forEach')

### ISSUE THREAD

**Issue by divyanshupathak** [facebook/react-native#14079] opened 2017-05-20 20:32 UTC
I create a fresh app and got the following error while running it on android device:-

undefined is not a function (evaluating 'transform.forEach')

I had node version 6.10.3 and React Native version 2.0.1 and npm version 3.10.10.
I am using windows 10 (64 bit).

Please help for this issue.
Thanks.

**Comment by jhonnold** [comment] 2017-05-21 02:20
+1

**Comment by brimes** [comment] 2017-05-21 21:47
I have the same problem. 

```
05-21 18:43:49.790 26269 26295 I ReactNativeJS: Running application "CrowdCheck" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
05-21 18:43:49.850 26269 26295 W ReactNativeJS: Warning: Failed prop type: Invalid prop `position` of value `function checkType() {
05-21 18:43:49.850 26269 26295 W ReactNativeJS:     [native code]
05-21 18:43:49.850 26269 26295 W ReactNativeJS: }` supplied to `View`, expected one of ["absolute","relative"].
05-21 18:43:49.850 26269 26295 W ReactNativeJS: Bad object: {}
05-21 18:43:49.850 26269 26295 W ReactNativeJS:     in View
05-21 18:43:49.850 26269 26295 W ReactNativeJS: Warning: Failed prop type: Invalid prop `position` of value `function checkType() {
05-21 18:43:49.850 26269 26295 W ReactNativeJS:     [native code]
05-21 18:43:49.850 26269 26295 W ReactNativeJS: }` supplied to `RCTView`, expected one of ["absolute","relative"].
05-21 18:43:49.850 26269 26295 W ReactNativeJS: Bad object: {}
05-21 18:43:49.850 26269 26295 W ReactNativeJS:     in RCTView (at View.js:127)
05-21 18:43:49.860 26269 26295 E ReactNativeJS: undefined is not a function (evaluating 'transform.forEach')
```

**Comment by dpluna** [comment] 2017-05-22 20:38
+1

**Comment by b3ni** [comment] 2017-05-23 05:52
+1

**Comment by kyomic** [comment] 2017-05-23 09:22
+1

**Comment by Carole89** [comment] 2017-05-23 14:25
+1

**Comment by mads79** [comment] 2017-05-23 15:20
+1

**Comment by DContra** [comment] 2017-05-23 18:14
+1

**Comment by DContra** [comment] 2017-05-23 18:20
`TypeError: Cannot convert undefined or null to object
    at Function.from (native)
    at _toArray (/home/kontra/React-Native/Template/node_modules/react-native/local-cli/server/util/launchEditor.js:9:78)
    at launchEditor (/home/kontra/React-Native/Template/node_modules/react-native/local-cli/server/util/launchEditor.js:143:59)
    at Object.handle (/home/kontra/React-Native/Template/node_modules/react-native/local-cli/server/middleware/openStackFrameInEditorMiddleware.js:17:7)
    at next (/home/kontra/React-Native/Template/node_modules/react-native/node_modules/connect/lib/proto.js:174:15)
    at Object.handle (/home/kontra/React-Native/Template/node_modules/react-native/local-cli/server/middleware/getDevToolsMiddleware.js:74:7)
    at next (/home/kontra/React-Native/Template/node_modules/react-native/node_modules/connect/lib/proto.js:174:15)
    at Object.handle (/home/kontra/React-Native/Template/node_modules/react-native/local-cli/server/middleware/getDevToolsMiddleware.js:74:7)
    at next (/home/kontra/React-Native/Template/node_modules/react-native/node_modules/connect/lib/proto.js:174:15)
    at Object.compression [as handle] (/home/kontra/React-Native/Template/node_modules/react-native/node_modules/connect/node_modules/compression/index.js:205:5)`

**Comment by DContra** [comment] 2017-05-23 19:32
I am getting the same error running off Ubuntu.
Node v 7.10.0
React Native Cli 2.0.1
React Native 0.44.0
React 16.0.0-alpha 6
Npm v 4.6.1
JDK v 8

**Comment by DContra** [comment] 2017-05-23 20:17
I realized I built this project before I implemented the JAVA_HOME path, and upgraded npm, react, and node. I built another project after that, and am having no issues with the new one.

**Comment by meistocko** [comment] 2017-05-25 13:21
Afer installing NVM to manage node versions (I'm on Ubuntu 17.04) this mostly works. 

I run `nvm use node` which sets node o v7.x, then `react-native run-android`.

**Comment by sheelendar** [comment] 2017-05-25 17:40
I solved this. As told by DContra was help full for me. First i deleted all demo projects(AwesomeProject).
And then create new project with 
command :- react-native init HelloProject
next :-  cd HelloProject/android
create a file inside HelloProject/android (local.properties)
:- nano local.properties
Open the file and paste your Android SDK path like below
sdk.dir = C:/Users/USERNAME/AppData/Local/Android/sdk
USERNAME should be your user name;
Now build project
:- react-native run-android

**Comment by DContra** [comment] 2017-05-25 17:55
@sheelendar Would setting a system variable like 
`set ANDROID_HOME=[Your SDK Path]`
`setx ANDROID_HOME=[Your SDK Path]`
resolve this as well? 
Some people are reporting that react isn't locating the android sdk directory nor the JDK directory after the 0.44 update. Seems like setting JAVA_HOME and ANDROID_HOME variables and building a new project is resolving a lot of issues. However, some people are also having an issue with Watchman reacting to updated scripts as well, fix currently unknown other than a downgrade

**Comment by ManishPatiyal** [comment] 2017-06-05 14:09
+1

**Comment by yliu05** [comment] 2017-06-06 04:25
I feel it's difficult for me to find the reason for the warnings and error same as @brimes's. 
And this issue has wasted much time (almost one day).
Finally, I found in the menu **Dev Settings**, unckecking the check box **JS Dev Mode** (default checked) works for me.
While in the adb output, u can see **__DEV__ === false**.
I know the warnings and error just temporarily hide by this way. 
Hope someone can solve this problem thoroughly.
My ENV as follows:
react : 16.0.0-alpha.6
react-native : 0.44.2
node : v6.9.2
npm : 2.15.11
python : 2.7.13
android sdk : API 23
OS : WIN 7 (32 Bits)

**Comment by yliu05** [comment] 2017-06-08 08:14
In the file View\ViewPropType.js, there is a line like this:
`style: stylePropType,`
Comment this line or change the "style" key to other name. This works 4 me.

**Comment by flyher** [comment] 2017-06-27 06:32
@divyanshupathak 

https://github.com/facebook/react-native/issues/13765

**Comment by mikelambert** [comment] 2017-07-03 06:53
I've posted an update on the other thread here https://github.com/facebook/react-native/issues/13765#issuecomment-312557021, which makes me believe there's some sort of non-determinism in the Haste packager that sometimes loads from node_modules/.

**Comment by iwangx** [comment] 2017-07-11 05:34
I solved the problem by installing the application using yarn
```
npm install -g yarn react-native-cli
```
```
yarn install
```

**Comment by hramos** [comment] 2017-09-21 15:13
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Closed by hramos** 2017-09-21 15:13 UTC
Labels: Icebox
