### ISSUE TITLE
[still broken] error: bundling failed: Error: Unable to resolve module `./../react-transform-hmr/lib/index.js

### ISSUE THREAD

**Issue by Ry7n** [facebook/react-native#21645] opened 2018-10-10 14:50 UTC
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment

```
  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i7-6660U CPU @ 2.40GHz
      Memory: 319.66 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.11.0 - /usr/local/Cellar/node/10.11.0/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.2 => 0.57.2 
```

## Description

This is a duplicate of https://github.com/facebook/react-native/issues/21490 -- but that ticket is resolved, so I cannot comment there.

Mitigation steps remain the same. It appears that a version lock (perhaps the cyclic dependency between metro and metro-config — I couldn't track it down) prevents yarn from resolving 0.48.0 of metro.

## Reproducible Demo

```
brew install nvm
brew install yarn --without-node
nvm install v10.11.0
nvm use v10.11.0
npx react-native-cli init myapp
```

**Expected**

Yarn installs metro 0.48.0

**Actual**

Yarn installs:

```
├─ metro-babel-register@0.47.1
├─ metro-babel7-plugin-react-transform@0.47.1
├─ metro-config@0.47.1
├─ metro-memory-fs@0.47.1
├─ metro-minify-uglify@0.47.1
├─ metro-react-native-babel-preset@0.47.1
├─ metro-source-map@0.47.1
├─ metro@0.47.1
```

In addition, manually installing metro 0.48.0 in the project doesn't appear to help because yarn will resolve both dependencies.

**Comment by jjenzz** [comment] 2018-10-10 17:11
If you are using Yarn, I was able to setup a resolution in my `package.json` to fix it for now:

```
"resolutions": {
  "metro": "0.48.0"
}
```

**Comment by Ry7n** [comment] 2018-10-11 02:57
Thanks for the tip, @jjenzz! I actually needed:

```
  "resolutions": {
    "metro": "^0.48.1",
    "metro-babel-register": "^0.48.1",
    "metro-core": "^0.48.1",
    "metro-memory-fs": "^0.48.1"
  },
```

To ensure all of the metro-related things were at the same version and unduplicated.

**Comment by a-tarasyuk** [comment] 2018-10-11 19:55
+1. The issue still exists on iOS, Android. macOS 10.14, Xcode: 10.0.

```shell
"react": "16.5.1",
"react-dom": "16.5.1",
"react-native": "0.57.2",
"metro-react-native-babel-preset": "0.48.1",
```
For me only helps `react-native start -- --reset-cache`.

**Comment by sw-tt-keyurprajapati** [comment] 2018-10-12 06:59
Solution @ Same Problem https://github.com/facebook/react-native/issues/21648#issuecomment-428828608

**Comment by kelset** [comment] 2018-10-12 15:08
Duplicate of #21490

**Closed by kelset** 2018-10-12 15:08 UTC
Labels: 📦Bundler
