### ISSUE TITLE
"Error: Requiring module "BatchedBridge" which threw an exception" after upgrade to 0.14.1

### ISSUE THREAD

**Issue by javamonn** [facebook/react-native#4022] opened 2015-11-09 23:02 UTC
Hi all,

Hitting some errors after upgrading from 0.13.0 to 014.1. I followed the upgrade instructions in the docs. This trace is while running in iOS simulator.

![screen shot 2015-11-09 at 6 00 14 pm](https://cloud.githubusercontent.com/assets/5216744/11049378/d0e944fa-870b-11e5-91bc-eb91464375e6.png)

**Comment by castlesix** [comment] 2015-11-10 01:28
Android is also the same. :(

**Comment by kusamakura** [comment] 2015-11-10 03:56
I get exactly this when I try to use react-relay via the [Shopify fork](https://github.com/Shopify/relay). (Also using npm install inside node_modules/react-relay, and deleting node_modules/react-relay/react-native)

**Comment by skv-headless** [comment] 2015-11-10 07:09
same for me:(

**Comment by sooth-sayer** [comment] 2015-11-10 08:33
+1

**Comment by javamonn** [comment] 2015-11-10 15:10
@kusamakura We're using nuclear-js, this stack trace linked to from this issue appears related: https://github.com/facebook/react-native/issues/1437.

**Comment by TylerK** [comment] 2015-11-10 23:32
Not using `nuclear-js` on a local project and am running into the following errors as well: 
![screen shot 2015-11-10 at 3 32 40 pm](https://cloud.githubusercontent.com/assets/1141040/11079319/4bfb5d90-87c0-11e5-884a-fd62e63f706e.png)

**Comment by ide** [comment] 2015-11-10 23:35
Try blowing away your node_modules maybe? Wondering if the issue could be related to dupe copies of React Native somehow.

**Comment by TylerK** [comment] 2015-11-11 00:02
Hey @ide! Sadly, I have nuked my `node_modules` folder a few times, with no success. If it helps, here are my dependencies for this project: https://gist.github.com/TylerK/650eec685ee9a8d6581c

Currently running Node 5.0.0 and NPM 3.3.9

**Comment by TylerK** [comment] 2015-11-11 00:03
To add: I've attempted this with `react-native` 0.14.0, 0.14.1, and the 0.15.0-rc as above. All throw the same error.

**Comment by adrianrego** [comment] 2015-11-11 02:35
Same here.  Upgraded from 0.13 to 0.14.2.  Blew out node_modules and updated assets to get the iOS project to build.

**Comment by gudmundurmar** [comment] 2015-11-11 09:58
+1

**Comment by wanwanxie** [comment] 2015-11-11 09:59
same issue

**Comment by adrianrego** [comment] 2015-11-11 13:47
Trying to narrowdown the problem on my setup.  Starting with a new, project I started importing my dependencies one by one in index.ios.js and reloading the app.

I hit this exact error once I imported the following dependencies:
* redux-persist  ```import { persistStore } from 'redux-persist';```
* react-redux ```import { connect } from 'react-redux';```

**Comment by idibidiart** [comment] 2015-11-11 23:30
is anyone able to run 0.14.2 without errors?

**Comment by AndreyNikiforov** [comment] 2015-11-12 03:46
in my case same error appeared after adding react-redux@4.0.0 to new simple app. Downgrading to react-redux@3.1.0 and adding react@0.14.2 to dependencies fixed the issue.

**Comment by ide** [comment] 2015-11-12 03:56
It might have to do with having two copies of React. react-redux 4 peer-depends on React and npm pulls it in...

**Comment by klausbreyer** [comment] 2015-11-12 07:55
Same for me. 

What I did: removed every stain of system node and io.js and reinstalled nvm. My only global installed node module is now react-native-cli.

The error occures, when I add flux to the project .

https://github.com/rackt/react-redux/issues/184#issuecomment-156004118

**Comment by klausbreyer** [comment] 2015-11-12 07:56
@idibidiart brand new project works fine with 0.14.2 but adding react redux cause the same error. I did a mini example here..  https://github.com/klausbreyer/redux-react-debugging-completly-new

**Comment by idibidiart** [comment] 2015-11-12 19:10
@ide  
@klausbreyer et al

I managed to get my project working normally with RN 0.14.2 by clearing out the npm cache

sudo npm cache clean -f

Yay!

Let me know if this doesn't work for you... I'm interested in figuring out the various variables, so we can help improve the getting started and upgrade docs.

**Comment by adrianrego** [comment] 2015-11-12 21:48
@klausbreyer I'm getting a Failed build on your mini example due to React being a peer dependency of redux-react.

```npm WARN EPEERINVALID react-redux@4.0.0 requires a peer of react@^0.14.0 but none was installed.```

I don't see react in your package.json.  Did you install it somewhere else?

**Comment by ide** [comment] 2015-11-12 21:49
react-redux 4 is incompatible with React Native. be sure to use 3.x

**Comment by klausbreyer** [comment] 2015-11-12 22:08
Oh, interestint information.  @ide  :) sad :(

**Comment by adrianrego** [comment] 2015-11-12 22:12
Downgraded to 3.1.0.  Still complains that it doesn't find module 'react' in /User/node_modules/... which seems odd..

I'm not using nvm.  If I explicitly install React 0.13.3, I can get the project to build, but then I ran into the original error in this issue.

Xcode Build Failure output:

```
+ DEST=/Users/adrian/Library/Developer/Xcode/DerivedData/CompletlyNew-fhatjocdorpiecheprivmlmzgfru/Build/Products/Debug-iphonesimulator/CompletlyNew.app
+ '[' -z '' ']'
+ export NVM_DIR=/Users/adrian/.nvm
+ NVM_DIR=/Users/adrian/.nvm
+ [[ -s /Users/adrian/.nvm/nvm.sh ]]
++ command -v brew
+ [[ -x /usr/local/bin/brew ]]
++ brew --prefix nvm
+ [[ -s /usr/local/Cellar/nvm/0.29.0/nvm.sh ]]
+ react-native bundle --entry-file index.ios.js --platform ios --dev true --bundle-output /Users/adrian/Library/Developer/Xcode/DerivedData/CompletlyNew-fhatjocdorpiecheprivmlmzgfru/Build/Products/Debug-iphonesimulator/CompletlyNew.app/main.jsbundle --assets-dest /Users/adrian/Library/Developer/Xcode/DerivedData/CompletlyNew-fhatjocdorpiecheprivmlmzgfru/Build/Products/Debug-iphonesimulator/CompletlyNew.app
bundle: Created ReactPackager
uncaught error Error: UnableToResolveError: Unable to resolve module react from /Users/adrian/Code/redux-react-debugging-completly-new/node_modules/react-redux/lib/index.js: Invalid directory /Users/node_modules/react
    at /Users/adrian/Code/redux-react-debugging-completly-new/node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/ResolutionRequest.js:323:15
    at tryCallOne (/Users/adrian/Code/redux-react-debugging-completly-new/node_modules/promise/lib/core.js:37:12)
    at /Users/adrian/Code/redux-react-debugging-completly-new/node_modules/promise/lib/core.js:103:15
    at flush (/Users/adrian/Code/redux-react-debugging-completly-new/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
See logs /var/folders/0s/ywjxsh9s3nq8ypqwfp44y7180000gn/T/react-packager.log
    at SocketClient._handleMessage (/Users/adrian/Code/redux-react-debugging-completly-new/node_modules/react-native/packager/react-packager/src/SocketInterface/SocketClient.js:131:23)
    at BunserBuf.<anonymous> (/Users/adrian/Code/redux-react-debugging-completly-new/node_modules/react-native/packager/react-packager/src/SocketInterface/SocketClient.js:52:42)
    at emitOne (events.js:77:13)
    at BunserBuf.emit (events.js:169:7)
    at BunserBuf.process (/Users/adrian/Code/redux-react-debugging-completly-new/node_modules/bser/index.js:289:10)
    at /Users/adrian/Code/redux-react-debugging-completly-new/node_modules/bser/index.js:244:12
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
Command /bin/sh failed with exit code 1
```

**Comment by Iliker** [comment] 2015-11-13 07:57
Same for me.

**Comment by klausbreyer** [comment] 2015-11-13 11:21
Delete your modules and make a new npm i ?
iliker <notifications@github.com> schrieb am Fr., 13. Nov. 2015 um 08:58:

**Comment by adrianrego** [comment] 2015-11-13 12:21
Deleted node_modules.  Installed nvm and getting similar results.  

This is the line sticking out for me:

```Unable to resolve module react from /Users/adrian/Code/redux-react-debugging-completly-new/node_modules/react-redux/lib/index.js: Invalid directory /Users/node_modules/react
    at /Users/adrian/Code/redux-react-debugging-completly-new/node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/ResolutionRequest.js:323:15```

Why is the DependencyResolver looking for 'react' in /Users/node_modules?

Build Output:
```
++ export MANPATH
++ export PATH
++ hash -r
++ export NVM_PATH=/Users/adrian/.nvm/versions/node/v5.0.0/lib/node
++ NVM_PATH=/Users/adrian/.nvm/versions/node/v5.0.0/lib/node
++ export NVM_BIN=/Users/adrian/.nvm/versions/node/v5.0.0/bin
++ NVM_BIN=/Users/adrian/.nvm/versions/node/v5.0.0/bin
++ '[' '' = true ']'
++ local NVM_USE_OUTPUT
++ nvm_is_iojs_version v5.0.0
++ case "$1" in
++ return 1
++ '[' 1 -ne 1 ']'
++ '[' _v5.0.0 '!=' _system ']'
++ local NVM_USE_CMD
++ NVM_USE_CMD='nvm use --delete-prefix'
++ '[' -n node ']'
++ NVM_USE_CMD='nvm use --delete-prefix v5.0.0'
++ '[' 1 -eq 1 ']'
++ NVM_USE_CMD='nvm use --delete-prefix v5.0.0 --silent'
++ nvm_die_on_prefix 0 'nvm use --delete-prefix v5.0.0 --silent'
++ local NVM_DELETE_PREFIX
++ NVM_DELETE_PREFIX=0
++ case "$NVM_DELETE_PREFIX" in
++ local NVM_COMMAND
++ NVM_COMMAND='nvm use --delete-prefix v5.0.0 --silent'
++ '[' -z 'nvm use --delete-prefix v5.0.0 --silent' ']'
++ '[' -n '' ']'
++ '[' -n '' ']'
++ nvm_has npm
++ type npm
++ local NVM_NPM_PREFIX
+++ npm config get prefix
++ NVM_NPM_PREFIX=/Users/adrian/.nvm/versions/node/v5.0.0
++ nvm_tree_contains_path /Users/adrian/.nvm /Users/adrian/.nvm/versions/node/v5.0.0
++ '[' -n '' ']'
+ react-native bundle --entry-file index.ios.js --platform ios --dev true --bundle-output /Users/adrian/Library/Developer/Xcode/DerivedData/CompletlyNew-fhatjocdorpiecheprivmlmzgfru/Build/Products/Debug-iphonesimulator/CompletlyNew.app/main.jsbundle --assets-dest /Users/adrian/Library/Developer/Xcode/DerivedData/CompletlyNew-fhatjocdorpiecheprivmlmzgfru/Build/Products/Debug-iphonesimulator/CompletlyNew.app
bundle: Created ReactPackager
uncaught error Error: UnableToResolveError: Unable to resolve module react from /Users/adrian/Code/redux-react-debugging-completly-new/node_modules/react-redux/lib/index.js: Invalid directory /Users/node_modules/react
    at /Users/adrian/Code/redux-react-debugging-completly-new/node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/ResolutionRequest.js:323:15
    at tryCallOne (/Users/adrian/Code/redux-react-debugging-completly-new/node_modules/promise/lib/core.js:37:12)
    at /Users/adrian/Code/redux-react-debugging-completly-new/node_modules/promise/lib/core.js:103:15
    at flush (/Users/adrian/Code/redux-react-debugging-completly-new/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
See logs /var/folders/0s/ywjxsh9s3nq8ypqwfp44y7180000gn/T/react-packager.log
    at SocketClient._handleMessage (/Users/adrian/Code/redux-react-debugging-completly-new/node_modules/react-native/packager/react-packager/src/SocketInterface/SocketClient.js:131:23)
    at BunserBuf.<anonymous> (/Users/adrian/Code/redux-react-debugging-completly-new/node_modules/react-native/packager/react-packager/src/SocketInterface/SocketClient.js:52:42)
    at emitOne (events.js:77:13)
    at BunserBuf.emit (events.js:169:7)
    at BunserBuf.process (/Users/adrian/Code/redux-react-debugging-completly-new/node_modules/bser/index.js:289:10)
    at /Users/adrian/Code/redux-react-debugging-completly-new/node_modules/bser/index.js:244:12
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
Command /bin/sh failed with exit code 1
```

**Comment by TylerK** [comment] 2015-11-13 23:50
Some steps to reproduce: 

* `react-native init test-project` 
* `cd text-project`
* `npm install --save react redux react-redux`
* In `./index.ios.js` add `var provider = require('react-redux');` underneath the `react-native` require. 
* Open `./ios/testProject.xcodeproj` in Xcode and run it in a simulator
* Notice the error output to the console

React-redux v4.0.0 and v3.1.0 both cause this error.

**Comment by ide** [comment] 2015-11-14 00:11
`npm install --save react`-- this is your problem right here. Be sure not to (transitively) have react under node_modules.

**Comment by TylerK** [comment] 2015-11-14 00:19
Unfortunately that's very necessary for a multi-platform React & React-Native based application. Luckily it doesn't appear to be the problem as you can reproduce the above with just including `react-redux`.

**Comment by jakepusateri** [comment] 2015-11-14 00:47
I've found that the 'react' package itself doesn't play nicely with 'react-native', which contains its own special copy of React. I am able to use generic components that only interface with React via createClass and createElement by including the following file in my node_modules folder under the names 'react.ios.js' and 'react.android.js'.
```
module.exports = require('react-native');
```
This way, modules that require 'react' will get react native's version. I'm sure a simpler way to share components between web/native is on the roadmap but hasn't officially landed yet.

**Comment by nodkrot** [comment] 2015-11-14 22:24
#2985

**Comment by skv-headless** [comment] 2015-11-16 09:22
Situation from my point of view:
react-native 0.14 depends on react 0.14beta
react-redux 4 depends on react 0.14
react-redux 3 depends on react ^0.14.0-rc1
I don't see any way to update my app to react-native v0.14 . Only wait for v0.15 and hope that I'll be able to update to 2 versions at once. Please correct me if I'm wrong.

**Comment by psbanka** [comment] 2015-11-24 04:53
Oh no, React Native `0.15` doesn't solve the problem either:

```
nvm use 5
npm cache clean
react-native init test1
cd test1
npm install react-redux redux --save
patch -p0 index.ios.js << EOD
13a14
> var provider = require('react-redux')
EOD
open ios/test1.xcodeproj/
```
And here is the corresponding `package.json` just to be clear:
```
{
  "name": "test1",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start"
  },
  "dependencies": {
    "react-native": "^0.15.0",
    "react-redux": "^4.0.0",
    "redux": "^3.0.4"
  }
}
```
Also get the same result with:
- react-redux 3.1.0 and node 4.2.2 / npm 2.14.7
- react-redux 4.0.0 and node 4.2.2 / npm 2.14.7

So it sounds like if we want to be able to use React Native with modules that themselves require React, we need to stick with version 0.13.0

**Comment by adrianrego** [comment] 2015-11-24 13:18
@psbanka that's correct. The issue to track was referenced above: https://github.com/facebook/react-native/issues/2985

**Comment by bruz** [comment] 2015-12-07 20:11
@psbanka in troubleshooting a related issue I tried your barebones repro case. At least with react-redux 3.1.0, the reason this fails appears to be:

    var provider = require('react-redux')

which should be:

    var provider = require('react-redux/native')

**Comment by andrewljohnson** [comment] 2015-12-15 18:58
I was having this issue, and @bruz solution worked for me... I had to change the react-redux imports when I updated react-native from .13 to .14.

**Comment by jsierles** [comment] 2016-03-20 18:20
@facebook-github-bot answered

**Closed** 2016-03-20 18:21 UTC
Labels: Ran Commands
