### ISSUE TITLE
React-native resolving dependencies is Very Slow and Blocking in step 4/11

### ISSUE THREAD

**Issue by Rebaiahmed** [facebook/react-native#14241] opened 2017-05-29 16:22 UTC
Hi everyone , I'm trying all the day to rebuild my react-native application , in Gneymotion but whet whn i run react-native run-android 
I  get this 
![issues](https://cloud.githubusercontent.com/assets/13053759/26556545/f9e210d0-4492-11e7-9cb1-12bd55227a78.png)

react-native-cli: 2.0.1
react-native: 0.42.3

* Platform: [Android,]
* Development Operating System: , Linux, 
* Dev tools:n, Android SDK version 23.01 ,

**Comment by hramos** [comment] 2017-05-30 18:07
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-05-30 18:07 UTC
