### ISSUE TITLE
0.16.0-rc react-native start Error [Windows]

### ISSUE THREAD

**Issue by danhanfry** [facebook/react-native#4417] opened 2015-11-30 02:30 UTC
Good.

As far as I know, to use version 0.16.0-rc I have to do the following.

1. `` react-native init NewVersion ``
2. modify package.json of 0.15.0 to 0.16.0-rc
3. npm install
4. console ``react-native start``
5. console ``react-native run-android``

ok

![image](https://cloud.githubusercontent.com/assets/8139751/11462298/91b6ff22-9712-11e5-8350-9b8e4b357988.png)

![image](https://cloud.githubusercontent.com/assets/8139751/11462302/9a4aa8c8-9712-11e5-9bdf-45aade5b944f.png)

I have been looking for information and find nothing.

**Comment by mkonicek** [comment] 2015-11-30 14:57
This is caused by the "Watcher took too long to load" error.

**A note about Windows as a dev environment:** As RN iOS requires a Mac and most of the programmers at Facebook and the RN developers use Macs, support for OS X is a top priority. However, we would like to support developers using Linux and Windows too. We believe we'll get the best Windows support from people using Windows on a daily basis. So to begin with, **Windows support for the development environment is an ongoing community responsibility.** This can mean filing issues and submitting PRs, and we'll help review and merge them. We are looking forward to your contributions and appreciate your patience.

**Comment by danhanfry** [comment] 2015-11-30 23:47
in the previous version 0.15.0 this part works well

**Comment by deepakmega** [comment] 2015-12-03 17:10
For now you could try this fix suggested [here](https://github.com/facebook/react-native/issues/2841#issuecomment-141635574).

**Comment by satya164** [comment] 2015-12-04 12:51
Duplicate of #2841

**Closed by satya164** 2015-12-04 12:51 UTC
Labels: Community Responsibility, Windows
