### ISSUE TITLE
RN Project Build Error !!

### ISSUE THREAD

**Issue by bilinovabilisim** [facebook/react-native#35390] opened 2022-11-18 10:17 UTC
### Description

Hello, I have this problem when I try to get a release (aab,apk) again in the application that I have previously released. I also don't know how to apply the released patch. Can you help me? Thank you.
![builderr](https://user-images.githubusercontent.com/90574220/202677797-7aed9a68-c223-42a1-88fb-49524bd95f06.png)

### Version

0.69.2

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Memory: 3.99 GB / 15.87 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
  IDEs:
    Android Studio: AI-212.5712.43.2112.8512546
    Visual Studio: Not Found
  Languages:
    Java: 11.0.15 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: ^0.69.2 => 0.69.2 
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

About a month ago, the application that I sent webview to the stores gives an error when I try to re-release it.

### Snack, code example, screenshot, or link to a repository

![Uploading builderr.png…]()

**Comment by kelset** [comment] 2022-11-18 11:06
duplicate of https://github.com/facebook/react-native/issues/35391

**Closed by kelset** 2022-11-18 11:06 UTC
Labels: Needs: Triage :mag:
