### ISSUE TITLE
onContentSizeChange support for growing multiline TextInput

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#6552] opened 2016-03-20 18:47 UTC
Original discussion here: https://github.com/facebook/react-native/pull/1229#issuecomment-185462712
### Problem

> the `onChange` event that we depend upon here only fires when a user enters text via a keyboard. This means that if there is more than one line of text loaded in (e.g. resuming a form), the height will be restricted to whatever the default is. Is there any way to trigger (or measure) the contentSize so that we can set an accurate initial height?
### Potential solutions
- Fix `onChange` like @deanmcpherson did in https://github.com/facebook/react-native/pull/6283
- "Add a separate `onContentSizeChange` event which can be observed independently of onTextChange." (https://github.com/facebook/react-native/pull/1229#issuecomment-191996041) -- I did this for Android in [this commit](https://github.com/exponentjs/react-native/commit/ae182937552066598955937636adea24a51dca8d).
### Decision that needs to be made
- Do we push forward with `onContentSizeChange`?  (an aside, see our [justification for naming](https://twitter.com/notbrent/status/709445076850597888)).
- If yes:
  - do we back out of providing layout information in the `onChange` event from TextInput and just provide it in `onContentSizeChange`?
  - who will implement this on iOS?

@nicklockwood @deanmcpherson @bestander

**Comment by mangogogos** [comment] 2016-06-14 18:05
Any update on this? Most of the relevant issues have gone quiet

**Comment by bestander** [comment] 2016-06-21 13:46
I posted internally to get some attention, sorry for the wait.
Meanwhile if this affects you and you want to raise visibility, create an entry in [product pains](https://productpains.com/product/react-native/)

**Comment by holyxiaoxin** [comment] 2016-09-08 10:16
How is onContentSizeChange getting fired? I'm on Android and react-native v0.32.0, multiline is true. I only get onContentSizeChange fired for the first time, after that it doesn't fire even after i'm hitting the next line.

**Comment by ChristianTucker** [comment] 2016-09-22 09:05
Our application has tons of forms that are paused and resumed at a later date, and currently this issue alone is making react-native a headache for us.

**Comment by jayshah123** [comment] 2016-09-23 13:44
Checking on v0.33 rn on android, multiline is true.
I only get onContentSizeChange fired for the first time, after that it doesn't fire even after i'm hitting the next line.

**Comment by oargaruna** [comment] 2016-09-28 07:42
Issue reported by @jayshah123 and @holyxiaoxin still persists on v0.34. For now I am using both onChange and onContentSizeChange. The former for Android and the latter for iOS.

**Comment by snowjade** [comment] 2016-10-08 10:55
Oh ,I get the same issue too as reported by @jayshah123 and @holyxiaoxin

**Comment by sibelius** [comment] 2016-11-11 13:33
onContentSizeChange is not working on 0.37

**Comment by vaibhawc** [comment] 2016-11-25 17:36
is it still on there?

**Comment by aleclarson** [comment] 2016-12-17 15:25
FWIW `TextInput` + `props.onContentSizeChange` + `props.multiline` is working as intended for me
(using **0.37.0**)

**Comment by muszu** [comment] 2017-01-02 15:59
It's still on there :) 
onContentSizeChange on Android is fired only once (^0.39.0-rc.0), works fine on iOS.

**Comment by huangmr** [comment] 2017-01-03 11:11
the issue is in 0.38.1

**Comment by ericvicenti** [comment] 2017-03-06 07:53
Looks like this is fixed in newer versions of RN

**Closed by ericvicenti** 2017-03-06 07:53 UTC
