### ISSUE TITLE
Different positioning behavior for left-top and bottom-right in bordered box

### ISSUE THREAD

**Issue by kohver** [facebook/react-native#7152] opened 2016-04-22 12:37 UTC
Hey guys! First of all, thanks for react native, it's awesome!

I think I found a bug with layout system. It's about `position: absolute` inside bordered view. Image is better than 1000 words:
![image](https://cloud.githubusercontent.com/assets/795466/14741461/fb11ad16-089e-11e6-89d2-16b6947948f3.png)
Reproduced on ios and android. Check the demo: https://rnplay.org/apps/R-QCoA

---
What I expect – http://jsbin.com/novelowoti/4/edit?html,css,output
![image](https://cloud.githubusercontent.com/assets/795466/14741698/c626c076-08a0-11e6-8e99-fc6abc0d220c.png)

**Comment by grabbou** [comment] 2016-04-23 17:41
PS. Situation is even worse when you define different borders (which is because different code is applied):
<img width="190" alt="screen shot 2016-04-23 at 19 39 52" src="https://cloud.githubusercontent.com/assets/2464966/14763065/3b61d124-098b-11e6-934a-24294aadeff8.png">

I believe it's because of:
> iOS clips to the outside of the border, but CSS clips to the inside. To solve this, we'll need to add a container view inside the main view to correctly clip the subviews.

**Comment by lacker** [comment] 2016-10-21 04:12
Sorry about leaving this un-responded-to for so long. So, that rnplay link doesn't seem to be working any more. I'm going to close this issue, but this does sound like a problem so if it is a real problem still and if someone can reproduce it on master then please feel free to reopen.

**Closed by lacker** 2016-10-21 04:12 UTC
Labels: iOS
