### ISSUE TITLE
undefined is not a function (evaluating 'Object.getOwnPropertyNames(t)[typeof Symbol === "function" ? Symbol.iterator : "@@iterator"]()')

### ISSUE THREAD

**Issue by ianho** [facebook/react-native#15704] opened 2017-08-30 07:05 UTC
When I run my app on Android Simulator, I get:

`undefined is not a function (evaluating 'Object.getOwnPropertyNames(t)[typeof Symbol === "function" ? Symbol.iterator : "@@iterator"]()')
y
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:53718:117
_extend
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:53768:18
exports
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:54818:34
<unknown>
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:55585:171
e
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:53057:97
<unknown>
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:53070:19
<unknown>
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:53071:4
<unknown>
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:53053:79
<unknown>
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:53054:2
loadModuleImplementation
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:109:12
guardedLoadModule
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:70:36
_require
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:54:77
<unknown>
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:1259:32
loadModuleImplementation
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:109:12
guardedLoadModule
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:63:45
_require
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:54:77
global code
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:69165:9
`

**Comment by hramos** [comment] 2017-08-30 07:22
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-08-30 07:22 UTC
