### ISSUE TITLE
TexInput - textAlign={"start"} prop not working

### ISSUE THREAD

**Issue by iamhardik08** [facebook/react-native#15633] opened 2017-08-24 12:35 UTC
I have been using TextInput .

As per the documentation textAlign enum('start', 'center', 'end') 

Set the position of the cursor from where editing will begin. 

I had made the following changes 

<TextInput
                  ref="company"
                  autoCapitalize='none'
                  style={[styles.input,styles.formLabel,commonStyles.smallText]}
                  value={this.state.company}
                  underlineColorAndroid={'transparent'}
                  onChangeText={(text) => this.setState({company:text})}
                  textAlign={"start"}
 />

and getting this error 

Error while updating property 'textAlign' in shadow node of type AndroidTextInput

**Comment by hramos** [comment] 2017-08-24 17:05
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-08-24 17:05 UTC
