### ISSUE TITLE
Modal on iOS (0.42.0-rc.3) not showing when in remote debugging

### ISSUE THREAD

**Issue by Dvidan** [facebook/react-native#12515] opened 2017-02-22 14:43 UTC
### Description

Modal not showing when using "Debug JS Remotely" on a newly created react native project with 0.42.0-rc.3 and using the example for modal found at https://facebook.github.io/react-native/docs/modal.html.

Tested on a real device and simulator

No error in either Developer console or in xCode debug output.

### Reproduction

`git clone git@github.com:Dvidan/modalBugRN0420rc3 && cd modalBugRN0420rc3 && npm i`
Run iOS simulator, toggle "Debug JS Remotely" from developer menu
Click "Show Modal"
Nothing happens
Toggle "Stop Remote JS Debuggin" from developer menu
Click "Show Modal"
Modal is shown

### Solution

No idea.

### Additional Information

* React Native version: 0.42.0-rc.3
* Platform:  iOS
* Operating System: macOS Sierra 10.12.3

### See also
https://github.com/facebook/react-native/issues/12368

**Comment by patrikholcak** [comment] 2017-02-22 21:12
Related: #12223

**Comment by ajwhite** [comment] 2017-03-06 20:17
An example of this can be seen in https://github.com/JodiWarren/BrokenModal via #12747

**Comment by tuneZola** [comment] 2017-03-07 23:31
I am getting the same thing, for my whole app.

**Comment by tuneZola** [comment] 2017-03-07 23:44
Its not related to the model. Its fixed in https://github.com/facebook/react-native/issues/12223

**Comment by hramos** [comment] 2017-07-25 22:58
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Closed by hramos** 2017-07-25 22:58 UTC
Labels: Icebox, iOS
