### ISSUE TITLE
FlatList【onEndReached】 not work on Android at 0.69.1 which 0.68.x is work.

### ISSUE THREAD

**Issue by chuckwu0** [facebook/react-native#34128] opened 2022-07-05 02:40 UTC
### Description

FlatList【onEndReached】 not work on Android at 0.69.1
which 0.68.x is work.

### Version

0.69.1

### Output of `npx react-native info`

System:
OS: macOS 12.4
CPU: (8) x64 Apple M1
Memory: 35.58 MB / 16.00 GB
Shell: 5.8.1 - /bin/zsh
Binaries:
Node: 16.13.2 - /usr/local/bin/node
Yarn: 1.22.15 - /usr/local/bin/yarn
npm: 8.1.2 - /usr/local/bin/npm
Watchman: 2022.03.21.00 - /usr/local/bin/watchman
Managers:
CocoaPods: 1.11.3 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
Android SDK:
API Levels: 22, 23, 24, 26, 27, 28, 29, 30, 31
Build Tools: 25.0.0, 26.0.1, 26.0.2, 27.0.3, 28.0.3, 29.0.2, 30.0.1, 30.0.2, 30.0.3, 31.0.0
System Images: a...s_playstore | Google Play Intel x86 Atom Sys..., a...google_apis | Google APIs Intel x86 Atom Sys...
Android NDK: 17.2.4988734
IDEs:
Android Studio: 2021.2 AI-212.5712.43.2112.8609683
Xcode: 13.4/13F17a - /usr/bin/xcodebuild
Languages:
Java: 1.8.0_241 - /usr/bin/javac
npmPackages:
@react-native-community/cli: Not Found
react: 18.0.0 => 18.0.0
react-native: 0.69.1 => 0.69.1
react-native-macos: Not Found
npmGlobalPackages:
react-native: Not Found

### Steps to reproduce

/

### Snack, code example, screenshot, or link to a repository

/

**Comment by cortinico** [comment] 2022-07-05 15:13
Hey @chuckwu0 Please fill in the rest of the issue boxes (specifically the reproducer), thanks.

**Comment by AntoineDoubovetzky** [comment] 2022-07-06 11:49
@chuckwu0 I tried to reproduce but it is seems to be working fine on both 0.68 and 0.69

**Comment by cortinico** [comment] 2022-07-29 17:22
Closing due to lack of reproducer. Feel free to reopen once you can provide a reproducer 👍

**Closed by cortinico** 2022-07-29 17:22 UTC
Labels: Platform: Android, Component: FlatList, Needs: Author Feedback, Needs: Repro, Needs: Issue Template
