### ISSUE TITLE
onLongPress doesn't work for nested <Text>

### ISSUE THREAD

**Issue by evollu** [facebook/react-native#11462] opened 2016-12-14 17:29 UTC
### Description

onLongPress is not called if a Text is inside another Text

### Reproduction

It works fine on rnplay with RN v0.33
Here is a sample code that doesn't work. Clicking on aaaa will show a touch effect and nothing happens after
```
<Text style={styles.instructions}>
          Press Cmd+R to reload,{'\n'}
          Cmd+D or shake for dev menu

          <Text  onLongPress={()=>Alert.alert('aaaa')}>aaaa</Text>
</Text>
```

### Additional Information

* React Native version: 0.39.1
* Platform: iOS
* Operating System: MacOS

**Comment by evollu** [comment] 2016-12-15 00:26
i realized that it is caused by PRESS_RECT_OFFSET. Is there a way to override it?

**Comment by lacker** [comment] 2016-12-15 00:28
So it works on 0.33 but not in 0.39? Can you figure out which version of React Native broke this?

**Comment by evollu** [comment] 2016-12-15 00:45
just tried 0.33 in local machine and it breaks too. I've figured out the issue
RectOffset was hard coded https://github.com/facebook/react-native/blob/master/Libraries/Text/Text.js#L327
After changing them to 0 it starts to work again.

**Comment by lacker** [comment] 2016-12-15 00:52
It seems like this is intentional behavior, then, like there's just supposed to be an offset for which touches count on text and you want it to work differently. It seems like Text-inside-Text is a bit odd, maybe a workaround is to just not put Text inside of other Text and use Views instead?

**Comment by lacker** [comment] 2016-12-15 00:53
Sorry, didn't mean to close it. Well, unless my analysis is correct and this is indeed "working as intended".

**Comment by evollu** [comment] 2016-12-15 01:28
Is there any reason for these numbers? Can I make it customizable?

**Comment by evollu** [comment] 2016-12-15 14:51
UPDATE: change PRESS_RECT_OFFSET no longer works. I don't know what is the cause of the problem now

**Comment by lacker** [comment] 2016-12-15 17:49
How about just listening for `onPress` and then calculating whether the press is long or not yourself? Just as a way to get this done.

**Comment by evollu** [comment] 2016-12-17 21:18
@lacker I didn't know I can do that. Is it in the event object passed into onPress callback?

**Comment by evollu** [comment] 2016-12-18 01:48
I find `UIManager.measure(tag, this._handleQueryLayout)` calls _handleQueryLayout with (0,0,0,0,0,0) for inner text.

**Comment by lacker** [comment] 2016-12-19 18:36
I mean whether something is long is just a calculation based on lower-level events, so you can figure it out yourself, right? Without changing code in the guts of React Native.

**Comment by evollu** [comment] 2016-12-19 18:55
React Native triggers `pressOut` and end press event once it finds the touch point is outside of Touchable rect. 
I can't figure it out myself because React Native thinks the touch is cancelled (not finished) immediately, it doesn't trigger any callback like onPress or onLongPress.

**Comment by TGPSKI** [comment] 2017-03-09 01:07
I'm also having the same issue and it is really driving me mad. Wasting a lot of time trying to debug this issue.

RN: 0.40
Device: iPhone 7

I added some quick console logs to see exactly what is happening in this case.

I also included @evollu's small mod to Text.js to accept PRESS_RECT_OFFSET prop overrides:
```
this.touchableGetPressRectOffset = function(): RectOffset {
                return this.props.pressRetentionOffset || PRESS_RECT_OFFSET;
              };
```

https://github.com/evollu/react-native/blob/153eb4781d7eaf8a3602bd106c7c03329c198eb2/Libraries/Text/Text.js#L237
```
              this.touchableHandleActivePressIn = () => {
                console.log('text press in');
                if (this.props.suppressHighlighting || !this._hasPressHandler()) {
                  return;
                }
                this.setState({
                  isHighlighted: true,
                });
              };

              this.touchableHandleActivePressOut = () => {
                console.log('text press out');
                if (this.props.suppressHighlighting || !this._hasPressHandler()) {
                  return;
                }
                this.setState({
                  isHighlighted: false,
                });
              };
```

What I see is that as soon as I do a press or a long press event, the `text press in` log is triggered, followed immediately by `text press out,` whether or not my finger has left the screen.

Open the page in question, press on the text link to open a web URL, hold the press down for X amount of time. If I hold down for any amount of time the onPress and onLongPress callbacks are not triggered. If I very quickly tap the same text component, the onPress fires. I can never get onLongPress to fire. 

I really really really want to use nested text components here so I can get hyperlinks to render inline with text blocks. Using Touchables are hard because then I have to wrap the text in a view, and getting text to render on the same line as non-url text is very hard.

Any ideas or help is appreciated. Stuck on this stupid thing instead of pushing my project forward. 

![image](https://cloud.githubusercontent.com/assets/12532803/23731260/660888dc-0421-11e7-9d07-5a9f20bb63db.png)

**Comment by evollu** [comment] 2017-03-09 01:13
I have #11530 that temporarily fixes this press out issue. don't know when it will be merged into main though

**Comment by TGPSKI** [comment] 2017-03-09 01:18
@evollu works fine with https://github.com/facebook/react-native/pull/11530. I think I will have to patch locally for now. However, still broken in RN master obviously. 

Thanks!

**Comment by TGPSKI** [comment] 2017-03-09 02:09
@lacker What are the issues keeping this from being pulled into master? Just want to understand a bit better. I've seen this issue open and close a few times since December. Still broken without the patch from where I sit.

Right now https://github.com/facebook/react-native/pull/11530 is a critical need for our production app, and we'll have to run npm postinstall scripts to handle this patch until it is merged.

**Comment by TGPSKI** [comment] 2017-03-09 02:16
Also @lacker re:  `It seems like Text-inside-Text is a bit odd, maybe a workaround is to just not put Text inside of other Text and use Views instead?`

I use nested text components to support inline links in a paragraph of text. If I don't use nested text, I have to run some nasty parsing functions to find the line of text where the link lives, break out that text into three separate views, and dynamically render a flexbox based approach to have the lines render properly. As part of the parse, you have to know screen size, font size, and a lot of onLayout stuff to get the thing to show up on the same line consistently. 

I'm open to other approaches but haven't figured them out yet. 

A common workaround would be to instead use a <TouchableOpacity> or similar to handle the onPress. However, these touchable components have to have a defined width and height when nested inside of a <Text> component. This would require more nasty parsing as alluded to above to find the screen size, font size, and touchable size and then set width & height dynamically.

**Comment by TGPSKI** [comment] 2017-03-09 02:24
Could the difference in RCTText vs RCTVirtualText be causing this issue? 

Does UIManager.measure handle RCTVirtualText properly? 
`UIManager.measure(tag, this._handleQueryLayout)`

https://github.com/facebook/react-native/blob/master/Libraries/Text/Text.js#L355
```
    if (this.context.isInAParentText) {
      return <RCTVirtualText {...newProps} />;
    } else {
      return <RCTText {...newProps} />;
```

**Comment by TGPSKI** [comment] 2017-03-14 20:50
@lacker @evollu any updates on the questions above? When will this PR get merged into master?

**Comment by hramos** [comment] 2017-07-20 22:26
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/onlongpress-doesnt-work-for-nested-text

**Closed by hramos** 2017-07-20 22:26 UTC
Labels: Icebox
