### ISSUE TITLE
ERR_INVALID_ARG_TYPE(name, 'string', value);     ^  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined     at validateString (internal/validators.js:125:11)     at Object.join (path.js:1147:7)

### ISSUE THREAD

**Issue by Steffi3rd** [facebook/react-native#24108] opened 2019-03-22 23:02 UTC
I just run 
```
$ react-native init AwesomeProject
```

Package are installed but I have an error

```
info Setting up new React Native app in /Users/xx/Sites/AwesomeProject
info Adding required dependencies
internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:1147:7)
    at isProjectUsingYarn (/Users/xx/Sites/AwesomeProject/node_modules/@react-native-community/cli/build/tools/yarn.js:101:51)
    at shouldUseYarn (/Users/xx/Sites/AwesomeProject/node_modules/@react-native-community/cli/build/tools/PackageManager.js:36:39)
    at Object.install (/Users/xx/Sites/AwesomeProject/node_modules/@react-native-community/cli/build/tools/PackageManager.js:44:10)
    at generateProject (/Users/xx/Sites/AwesomeProject/node_modules/@react-native-community/cli/build/commands/init/init.js:111:18)
    at Object.init (/Users/xx/Sites/AwesomeProject/node_modules/@react-native-community/cli/build/commands/init/init.js:94:3)
    at run (/Users/xx/.config/yarn/global/node_modules/react-native-cli/index.js:302:7)
    at createProject (/Users/xx/.config/yarn/global/node_modules/react-native-cli/index.js:249:3)
    at init (/Users/xx/.config/yarn/global/node_modules/react-native-cli/index.js:200:5)

**Comment by Steffi3rd** [comment] 2019-03-22 23:08
https://github.com/facebook/react-native/issues/24107

**Comment by Steffi3rd** [comment] 2019-03-22 23:11
https://github.com/facebook/react-native/issues/24103

**Comment by yaaanhue** [comment] 2019-03-23 00:00
i am having the same problem

**Comment by rodrigodocarmo1** [comment] 2019-03-23 00:08
I'm facing the same issue

**Comment by allain** [comment] 2019-03-23 00:25
same problem happens with node 10 and 11 here

**Comment by turnrye** [comment] 2019-03-23 02:46
ceci est un duplicata de #24103.

**Comment by FIyxian** [comment] 2019-03-23 05:35
metoo……

**Comment by wilbyang** [comment] 2019-03-23 06:44
I have the same issue

**Comment by muhammadridho** [comment] 2019-03-23 07:04
its work on previous version, you can try

`react-native init AwesomeProject --version "0.58.6"`

**Comment by hbmmy1234** [comment] 2019-03-23 08:41
I hava this problem too
info Setting up new React Native app in D:\ReactNative\MyApp
info Adding required dependencies
path.js:39
    throw new ERR_INVALID_ARG_TYPE('path', 'string', path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:432:7)
    at isProjectUsingYarn (D:\ReactNative\MyApp\node_modules\@react-native-community\cli\build\tools\yarn.js:101:51)
    at shouldUseYarn (D:\ReactNative\MyApp\node_modules\@react-native-community\cli\build\tools\PackageManager.js:36:39)
    at Object.install (D:\ReactNative\MyApp\node_modules\@react-native-community\cli\build\tools\PackageManager.js:44:10)
    at generateProject (D:\ReactNative\MyApp\node_modules\@react-native-community\cli\build\commands\init\init.js:111:18)
    at Object.init (D:\ReactNative\MyApp\node_modules\@react-native-community\cli\build\commands\init\init.js:94:3)
    at run (C:\Users\user\AppData\Roaming\npm\node_modules\react-native-cli\index.js:302:7)
    at createProject (C:\Users\user\AppData\Roaming\npm\node_modules\react-native-cli\index.js:249:3)
    at init (C:\Users\user\AppData\Roaming\npm\node_modules\react-native-cli\index.js:200:5)

D:\ReactNative>node -v
v10.15.0

D:\ReactNative>npm -v
6.4.1

**Comment by thymikee** [comment] 2019-03-23 08:45
Duplicate of https://github.com/facebook/react-native/issues/24103 (already fixed)

**Closed by thymikee** 2019-03-23 08:45 UTC
Labels: Ran Commands, Resolution: Needs More Information, Type: Bug Report

**Comment by XiaoJianPeng** [comment] 2019-03-23 09:47
I have the same issue
