### ISSUE TITLE
[0.61][iOS 13] pageSheet/formSheet dismissal from swipe not propagated

### ISSUE THREAD

**Issue by rewieer** [facebook/react-native#26892] opened 2019-10-17 06:35 UTC
When the user dismisses the modal by a swipe gesture using a custom presentation style,
the event isn't caught by onDismiss.

React Native version: 0.61.0

Sample code :
```js
import React, { Component } from 'react';
import {
  StyleSheet,
  Text,
  Button,
  View,
  Modal as RNModal,
} from 'react-native';

export default class Example extends Component {
  state = {
    visible: false,
  };
  
  render() {
    return (
      <View style={styles.container}>
        <Button
          onPress={() => this.setState({ visible: true })}
          title="Default"
        />
        <RNModal
          visible={this.state.visible}
          onDismiss={() => console.log("on dismiss")}
          onRequestClose={() => console.log("on dismiss")}
          presentationStyle={"pageSheet"}>
          <View style={styles.content}>
            <Text style={styles.contentTitle}>Open</Text>
            <Button
              onPress={() => this.setState({ visible: false })}
              title="Close"
            />
          </View>
        </RNModal>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
  },
  content: {
    backgroundColor: 'white',
    padding: 22,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 4,
    borderColor: 'rgba(0, 0, 0, 0.1)',
  },
  contentTitle: {
    fontSize: 20,
    marginBottom: 12,
  },
});
```

I'm no expert in iOS, but [this article](https://medium.com/@hacknicity/view-controller-presentation-changes-in-ios-13-ac8c901ebc4e) might give a hint. 

I can fill in a PR with some help.

**Comment by danielfein** [comment] 2019-10-19 06:40
Also experiencing this.

**Comment by tomeberle** [comment] 2019-10-21 17:43
Same here.

**Comment by janpe** [comment] 2019-10-30 09:49
Having this problem as well.

**Comment by epicbytes** [comment] 2019-11-04 21:49
same problem on iOS 13
I tried using the module "react-native-swipe-gestures", but it was a terrible experience. Now at all there is no way to swipe to set the activity flag at the modal window, it is always true.

**Comment by akondo06** [comment] 2019-11-12 15:01
any update on this? I was just about to use it when noticed the swipe down problem.

**Comment by petekp** [comment] 2019-11-12 17:57
Same issue. Took a look at the RN modal implementation but didn't see any obvious reasons this would not be working. It's possible the iOS modal API has changed since this feature was introduced.

**Comment by petekp** [comment] 2019-11-12 18:16
`onDismiss` doesn't appear to be a supported property in the modal interface: https://github.com/facebook/react-native/blob/aee88b6843cea63d6aa0b5879ad6ef9da4701846/React/Views/RCTModalHostView.h

**Comment by petekp** [comment] 2019-11-12 18:27
If it helps identify the issue, here are a couple recent changes related to `onDismiss` — the first one adds the functionality, and the second one replaces the implementation entirely:

https://github.com/facebook/react-native/commit/a389ffbd84224b583e71cf7c1468409cbc91ec8e#diff-c3bc2fe21eb2b2bcef4a55b8a29eec35

https://github.com/facebook/react-native/commit/bd2b7d6c0366b5f19de56b71cb706a0af4b0be43#diff-cbc57fb957557ddaed3e385bf78d4a2c

**Comment by Appkidd** [comment] 2019-11-19 17:06
Also experiencing. So frustrating.

**Comment by jimcamut** [comment] 2019-11-20 15:31
I had to change the presentationStyle to 'overFullScreen' to prevent swiping down. It's certainly no replacement for pageSheet, but if you need an onDismiss function to trigger it can be a temporary solution until this is fixed.

**Comment by excitedcat** [comment] 2019-11-21 09:09
I am using `Modal` from `react-native`, `presentationStyle ="pageSheet"` which means I can slide to dismiss. 

However when I do that, no function is fired. 

onDismiss only fires when I close it from a button. 

The modal won't open again if I do like this because it doesn't change it's state.

**Comment by humphreyja** [comment] 2019-12-03 00:23
I've been running into this issue.  I wrote a library (basically just copied over React Native's Modal code) to see if I could fix this issue.  I hook into the `viewDidDisappear` function in the ModalHostViewController which does get called when the Native iOS gesture for dismissing the modal happens.  I then manually call the onDismiss function.  Here's the library: https://github.com/HarvestProfit/react-native-modal-patch

I'm not that familiar with Objective-C so I'm not sure if this is a great solution, but hopefully it helps someone.  If someone more familiar thinks this is a valid solution, then I'll create a PR.

**Comment by amilaDulanjana** [comment] 2019-12-11 12:17
I am also experiencing this. Please release a fix for this.

**Comment by jpamarohorta** [comment] 2019-12-19 18:50
Same. Does anyone knows how to prevent the swipe? Not a solution but a possible workaround for now

**Comment by beniaminrychter** [comment] 2019-12-24 13:50
Same issue here. Because of that it's `Modal` component is useless.

**Comment by massoprod** [comment] 2020-01-10 11:07
Same problem with dismissing modal in presentation style. When I swipe it down to close, then state is not changed.

**Comment by lrholmes** [comment] 2020-01-18 11:46
Here is a (not-ideal/hacky!) workaround while awaiting a proper fix if anyone is also desperate for the pull-down modal behaviour. It does not solve the problem that there's no way to fire a callback when user dismisses the modal, but enables reopening the modal after being pulled-down.

The idea behind the logic is to check if an imperative modal-open is being attempted on an "already open" modal, and forcing a couple of re-renders to reset the value on the modal.

![modal](https://user-images.githubusercontent.com/6804978/72663153-0c036880-39e7-11ea-9a9c-3be33906e7bc.gif)


```js
import { useState, useEffect } from 'react';

export const useModalState = initialState => {
  const [modalVisible, setModalVisible] = useState(initialState);
  const [forceModalVisible, setForceModalVisible] = useState(false);

  const setModal = modalState => {
    // tyring to open "already open" modal
    if (modalState && modalVisible) {
      setForceModalVisible(true);
    }
    setModalVisible(modalState);
  };

  useEffect(() => {
    if (forceModalVisible && modalVisible) {
      setModalVisible(false);
    }
    if (forceModalVisible && !modalVisible) {
      setForceModalVisible(false);
      setModalVisible(true);
    }
  }, [forceModalVisible, modalVisible]);

  return [modalVisible, setModal];
};

// use it the same way as before (as docs recommend)
const [modalVisible, setModalVisible] = useModalState(false)

```

Hope it may help some of you!

**Comment by r4mdat** [comment] 2020-01-26 01:48
I wasn't able to get the workaround @lrholmes posted above to work. For whatever reason, the TouchableOpacity used to open the modal (and interestingly any adjacent TouchOpacity components) would no longer fire their onPress after the modal was swiped down. Desperate to get this working, I ended up putting a ScrollView around the entire modal content and used onDragEnd to flip the modal state variable. Works if your modal contents don't scroll. Not by any means ideal but was a reasonable trade-off in my situation.

**Comment by deniscreamer** [comment] 2020-01-30 10:17
@r4mdat 

Just try use Modal component inside TouchableWithoutFeedback. 
Then onPress will does not blocked.
And use function like @lrholmes

```<TouchableWithoutFeedback>
            <Modal
                visible={enable}
                presentationStyle={'formSheet'}
            </Modal>
</TouchableWithoutFeedback>```

```<TouchableOpacity
            onPress={() => {
                setModalSelectPhotos(false);
                setTimeout(() => {
                    setModalSelectPhotos(true);
                }, 50);
            }}>
.......
</TouchableOpacity>```

It was help me

**Comment by HarishMurru** [comment] 2020-01-30 10:24
> I've been running into this issue. I wrote a library (basically just copied over React Native's Modal code) to see if I could fix this issue. I hook into the `viewDidDisappear` function in the ModalHostViewController which does get called when the Native iOS gesture for dismissing the modal happens. I then manually call the onDismiss function. Here's the library: https://github.com/HarvestProfit/react-native-modal-patch
> 
> I'm not that familiar with Objective-C so I'm not sure if this is a great solution, but hopefully it helps someone. If someone more familiar thinks this is a valid solution, then I'll create a PR.

Thank you @humphreyja. I think it's not a permanent fix, but it works for me. Thanks for solution.

**Comment by scarlac** [comment] 2020-02-03 00:58
**Patch workaround**
Here's a patch that triggers `onDismiss` callback when a modal is dismissed by swiping down, on iOS 13. However, there is a caveat: Once you patch the code, Xcode seems to change the default modal behavior for the entire app (at least for me), causing all modals to appear in the new style, on iOS 13. Depending on how your app is, this may be unwanted so please consider that before using the patch in production.

**Download patch**
https://gist.github.com/scarlac/ec162221e11927c52cfc9c94e7252824

**Installation**
You can apply it:
- Manually (which is temporary - yarn may remove it) using:
  `patch < react-native+0.61.2.patch` in your project root folder
- Automatically using [patch-package](https://www.npmjs.com/package/patch-package) (recommended)

**Comment by martsie** [comment] 2020-02-03 09:49
Same issue - even with the patched versions.

**Comment by scarlac** [comment] 2020-02-03 12:54
@martsie You need to recompile your app. Set a breakpoints in the newly added lines to verify

**Comment by scarlac** [comment] 2020-02-03 20:22
Sorry, @martsie there was a line missing from my diff. You'll need to add a delegate as well. I've updated the link

**Comment by thomasttvo** [comment] 2020-02-10 01:26
> I wasn't able to get the workaround @lrholmes posted above to work. For whatever reason, the TouchableOpacity used to open the modal (and interestingly any adjacent TouchOpacity components) would no longer fire their onPress after the modal was swiped down. Desperate to get this working, I ended up putting a ScrollView around the entire modal content and used onDragEnd to flip the modal state variable. Works if your modal contents don't scroll. Not by any means ideal but was a reasonable trade-off in my situation.
@r4mdat just put your Modal in a View with `height: 0`
```
<View style={{height:0}}><Modal>....</Modal></View>
```

**Comment by bmkopp10** [comment] 2020-02-11 23:56
> @r4mdat
> 
> Just try use Modal component inside TouchableWithoutFeedback.
> Then onPress will does not blocked.
> And use function like @lrholmes
> 
> ```
> <TouchableWithoutFeedback>
>             <Modal
>                 visible={enable}
>                 presentationStyle={'formSheet'}
>             </Modal>
> </TouchableWithoutFeedback>
> 
> 
> 
> <TouchableOpacity
>             onPress={() => {
>                 setModalSelectPhotos(false);
>                 setTimeout(() => {
>                     setModalSelectPhotos(true);
>                 }, 50);
>             }}>
> .......
> </TouchableOpacity>
> ```
> 
> It was help me

This worked perfectly fine for me.  I would suggest this over any other options as it takes the least amount of code and is the most understandable.  Also, once the issue is fixed, it will be the simplest to revert.

**Comment by aca-hakan-pinar** [comment] 2020-03-02 12:48
Hey everyone, 

Im having the same issue. onDismiss property doesn't clear the Modal component. Can someone help me?

Thanks

**Comment by jdanthinne** [comment] 2020-03-02 12:53
@aca-hakan-pinar: @scarlac solution (https://github.com/facebook/react-native/issues/26892#issuecomment-581198937) works fine for me.

**Comment by noambonnie** [comment] 2020-03-06 18:32
Has this patch been merged? I'm on 0.61.5 and still experiencing the issue.

**Comment by annjawn** [comment] 2020-03-16 02:22
This still persists on 0.61.5. This bug is the entire reason why I am resorting to using a third party library.

**Comment by CodingByJerez** [comment] 2020-03-18 11:38
I am using this workaround while waiting for the fix:
```js
const MayComponent = () => {

    const [isOpen, setIsOpen] = useState<boolean>(false);

    return (
        <>
            <Modal
                presentationStyle="formSheet"
                animationType="slide"
                transparent={false}
                visible={isOpen}
            >
                <TouchableWithoutFeedback onBlur={() => setIsOpen(false)}>
                    <SafeAreaView>



                    </SafeAreaView>
                </TouchableWithoutFeedback>
    
            </Modal>

            <Button title={'demo'} onPress={() => setIsOpen(true)} />

        </>
    )
}
```

**Comment by CodingByJerez** [comment] 2020-03-18 13:19
until the problem is fixed:

```js
const MayComponent = () => {

    const [modalView, setModalView] = useState<null|SafeAreaView>(null);
    const [isOpen, setIsOpen] = useState<boolean>(false);

    return (
        <>
            <Modal
                presentationStyle="formSheet"
                animationType="slide"
                transparent={false}
                visible={isOpen}
            >
                <TouchableWithoutFeedback
                    onPressIn={() => Keyboard.dismiss()}
                    onPressOut={() => {
                        if(!modalView)
                            return;

                        modalView.measure((fx, fy, width, height, px, py) => {
                        if(py === Dimensions.get('window').height)
                            setIsOpen(false);
                    });
                }}>
                    <SafeAreaView ref={(ref) => setModalView(ref)}>


                    </SafeAreaView>
                </TouchableWithoutFeedback>
            </Modal>

            <Button title={'demo'} onPress={() => setIsOpen(true)} />
        </>
    );
};
``

**Comment by s-h-a-d-o-w** [comment] 2020-03-28 20:38
@CodingByJerez 

Thanks a lot for posting this but when it comes to the use of `SafeAreaView` - that sure isn't working for me on iOS 13.2.3. It has to be a regular `View`. (Possibly related to [this](https://github.com/facebook/react-native/issues/10180)?)

**Comment by CodingByJerez** [comment] 2020-03-29 07:40
@s-h-a-d-o-w 
I run it on iOS 13.3, and I don't have a problem.
Have you tried the loop? (This is the safest way)

```js
import React, { FunctionComponent, useEffect, useRef, useState } from 'react';
import { SafeAreaView, Modal } from 'react-native';


interface IProps {
    visible:boolean,
    onVisible(bool:boolean):void,
}
const MyComponent:FunctionComponent<IProps> = ({visible, onVisible, children}) => {

    const [modalView, setModalView] = useState<null|SafeAreaView>(null);
    const [isOpen, setIsOpen] = useState<boolean>(false);
    const intervalRef = useRef<null|number>(null);

    useEffect(() => setIsOpen(visible),[visible]);


    useEffect(() => {
        if(visible !== isOpen)
            onVisible(isOpen);

        const clearLoop = () => {
            if(intervalRef.current){
                clearInterval(intervalRef.current);
                intervalRef.current = null;
            }
        };

        if(isOpen && modalView)
            intervalRef.current = setInterval(() => tryClose(), 500);
        else if (intervalRef.current != null)
            clearLoop();

        return () => clearLoop();

    },[isOpen, modalView]);


    const tryClose = () => {
        if(!modalView)
            return;

        modalView.measure((fx, fy, width, height, px, py) => {
            if (py === 0)
                setIsOpen(false);
        });
    };

    return (
        <Modal
            presentationStyle={'formSheet'}
            animationType={'slide'}
            transparent={false}
            visible={isOpen}
            onRequestClose={() => setIsOpen(false)}>
            <SafeAreaView ref={(ref) => setModalView(ref)}>
                {children}
            </SafeAreaView>
        </Modal>
    );

};
```

**Comment by levelingup** [comment] 2020-03-30 02:26
I'm on react native 0.62.0 and its still not working for me

**Comment by annjawn** [comment] 2020-03-30 04:11
Yes, this still continues to be a bug. I am thinking that RN core is planning to get rid of `Modal` from core altogether and move it to react-native-community and thus there has been no interest in fixing this?? still not sure...

**Comment by jdanthinne** [comment] 2020-03-30 13:27
@scarlac Patch workaround doesn't work anymore in RN 0.62.0… `RCTModalManager.h file not found in RCTModalHostView.m`.

**Comment by r0b0t3d** [comment] 2020-03-31 01:51
@jdanthinne you could try this gist https://gist.github.com/r0b0t3d/3c9f77434e6fbcfa78698dcf57614fad

```
<Modal
      visible={visible}
      animationType="slide"
      presentationStyle="pageSheet"
      onRequestClose={onClose}
    >
</Modal>
```

**Comment by jdanthinne** [comment] 2020-03-31 07:03
@r0b0t3d Working fine. Thanks!

**Comment by noambonnie** [comment] 2020-03-31 19:20
Anyone knows why this issue is still marked as closed despite the issue still happening? @r0b0t3d do you know if there's a pull request for the gist you posted?

**Comment by annjawn** [comment] 2020-03-31 19:38
@noambonnie i think that's because they are planning to remove `Modal` out of core and move it to `react-native-community`; there's already a lib out there [react-native-community/react-native-modal](https://github.com/react-native-community/react-native-modal). 

I am not a 100% sure if this is true though.

**Comment by scarlac** [comment] 2020-03-31 19:44
@annjawn I see no indication that they'll move it out. That library relies on the modal component, does not provide the same default look, and has no native integrations like page sheets.
Is there a discussion where they are considering it?

**Comment by annjawn** [comment] 2020-03-31 19:48
@scarlac as I said, I am not 100% certain that's the plan but seeing how many of the things are with core, this could very well be a possibility. Yes, the community modal doesn't closely support the navigations and native integrations but I would venture a guess that it won't be a huge deal to support native view controller integrations there for both iOS and Android. But again , all of this is a big speculation on my side.

**Comment by amilaDulanjana** [comment] 2020-03-31 19:55
@jdanthinne Does @r0b0t3d ’s solution working ? Would you be able to close the modal programmatically ?

**Comment by jdanthinne** [comment] 2020-04-01 06:30
@amilaDulanjana Yes, working fine for me.

**Comment by jacobp100** [comment] 2020-04-01 14:27
@annjawn that package re-uses the existing Modal from react-native, and adds styling on top. It's purely JS and has no native code.

**Comment by ebm93** [comment] 2020-04-23 12:55
> @jdanthinne Does @r0b0t3d ’s solution working ? Would you be able to close the modal programmatically ?

not working for me..any other ideas so far?

**Comment by WonSong** [comment] 2020-04-24 21:36
I have it working with combination of two solutions mentioned in this thread..

1. Wrap <Modal /> with <View style={{ height: 0}} />
This allows the button triggering the modal to be clicked again

2. Ensure that you always set isVisible to false first, then set to true to "refresh" the modal state.
Note I have the modal state in Redux store, but it should work with local state as well.

I guess this will leave the modal instance hanging around, but using setting setModalOpen to false on unmount should help?

```typescript
const [isModalOpen, setModalOpen] = React.useState<boolean>(false);

const showModal = (): void => {
    setModalOpen(false);
    requestAnimationFrame(() => setModalOpen(true));
};

// React.useEffect() to setModalOpen to false on component unmount
```

Modal example

```typescript
import * as React from 'react';
import { Modal, View } from 'react-native';
import { IPageSheetModalProps } from './PageSheetModal.types';

export function PageSheetModal(
    props: React.PropsWithChildren<IPageSheetModalProps>
): React.ReactElement {
    const { isVisible, children } = props;

    return (
        <View style={{ height: 0 }}>
            <Modal presentationStyle="pageSheet" visible={isVisible} animationType="slide">
                {children}
            </Modal>
        </View>
    );
}
```

I've also tried using TouchableWithoutFeedback, but it caused issues if I had ScrollView inside. The above example also works with ScrollView inside the modal.

**Comment by farbexot** [comment] 2020-04-27 19:01
> @jdanthinne you could try this gist https://gist.github.com/r0b0t3d/3c9f77434e6fbcfa78698dcf57614fad
> 
> ```
> <Modal
>       visible={visible}
>       animationType="slide"
>       presentationStyle="pageSheet"
>       onRequestClose={onClose}
>     >
> </Modal>
> ```

This helped me back than. It broke for me on 0.62.2 somehow...

**Comment by glenngijsberts** [comment] 2020-04-28 21:33
> @jdanthinne you could try this gist https://gist.github.com/r0b0t3d/3c9f77434e6fbcfa78698dcf57614fad
> 
> ```
> <Modal
>       visible={visible}
>       animationType="slide"
>       presentationStyle="pageSheet"
>       onRequestClose={onClose}
>     >
> </Modal>
> ```

How can I test this with my local project? What should I do with the gist?

**Comment by LMestre14** [comment] 2020-04-29 17:46
> **Patch workaround for React Native 0.61.2**
> Here's a patch that triggers `onDismiss` callback when a modal is dismissed by swiping down, on iOS 13. ~However, there is a caveat: Once you patch the code, Xcode seems to change the default modal behavior for the entire app (at least for me), causing all modals to appear in the new style, on iOS 13. Depending on how your app is, this may be unwanted so please consider that before using the patch in production.~ Edit: There is no caveat anymore. Updated patch in link works as intended.
> 
> **Download patch**
> https://gist.github.com/scarlac/ec162221e11927c52cfc9c94e7252824
> 
> **Installation**
> You can apply it using either:
> 
>     * Manually (which is temporary - yarn may remove it) using:
>       `patch < react-native+0.61.2.patch` in your project root folder or...
> 
>     * Automatically using [patch-package](https://www.npmjs.com/package/patch-package) (recommended)

This was the solution for me
I'm using react-native 0.61.5

**Comment by ashkan-yazdani** [comment] 2020-05-03 00:44
before opening modal, set visible state to false, then set visible state to true again, because if modal already open, closed and open again

showModal = () => {
        this.setState({ modalVisible:false},function(){
            this.setState({ modalVisible: true })
        })
}

**Comment by dcosmin2003** [comment] 2020-05-06 08:23
I've updated to RN 0.62.2 and the bug persist.

**Comment by mydesweb** [comment] 2020-05-09 12:05
still not working in RN 0.62.2 onDismiss is never called

**Comment by budet-b** [comment] 2020-05-09 13:48
I used `react-native-modal` as a small workaround for this issue https://github.com/react-native-community/react-native-modal. It works as expected.

**Comment by cuddeford** [comment] 2020-05-09 16:31
Any solution for Expo users?

**Comment by alloy** [comment] 2020-05-12 09:23
Will somebody create a PR with @scarlac’s patch?

**Comment by budet-b** [comment] 2020-05-12 10:05
A patch has been published and then revert on 0.62.2 as we can see here https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#v0622 maybe a new patch will come with v0.63.0-rc.2 ?

**Comment by alloy** [comment] 2020-05-12 11:55
Ah yes, that change. Thanks for reminding me. There is no pending fix that I know of, if it existed it would most likely have been linked here.

Now that I think about it, I had asked @neilkimmett to [share a fix he has](https://twitter.com/alloy/status/1246054932094074882)–which iirc I observed from one of the threads discussing this issue. Perhaps he has time now, or at least to share it in such a way that one of you can make it into a proper PR.

**Comment by aelesia** [comment] 2020-05-14 07:52
Not working 0.62.2.

**Comment by mattdamon108** [comment] 2020-06-01 06:14
It works perfectly for my case.
https://gist.github.com/r0b0t3d/3c9f77434e6fbcfa78698dcf57614fad

**Comment by vasiliicuhar** [comment] 2020-07-23 19:38
I found much simpler workaround, it looks like instead of:

```js
onPress={() => setModalVisible(true)
```

You might try this

```js
onPressIn={() => setModalVisible(false)}
onPressOut={() => setModalVisible(true)}
```

Of course, that means that your button component should provide you these events (TouchableOpacity does)

**Comment by SimonHausdorf** [comment] 2020-08-02 12:58
> I found much simpler workaround, it looks like instead of:
> 
> ```js
> onPress={() => setModalVisible(true)
> ```
> 
> You might try this
> 
> ```js
> onPressIn={() => setModalVisible(false)}
> onPressOut={() => setModalVisible(true)}
> ```
> 
> Of course, that means that your button component should provide you these events (TouchableOpacity does)

that's the way to go! Thanks

**Comment by gboyegadada** [comment] 2020-08-04 21:22
> I found much simpler workaround, it looks like instead of:
> 
> ```js
> onPress={() => setModalVisible(true)
> ```
> 
> You might try this
> 
> ```js
> onPressIn={() => setModalVisible(false)}
> onPressOut={() => setModalVisible(true)}
> ```
> 
> Of course, that means that your button component should provide you these events (TouchableOpacity does)


Worked like magic ! 
If you are getting accidental taps (while scrolling in a list e.t.c), try doing:
```js
onPressIn={() => setModalVisible(false)} // 👉  as before
onPress={() => setModalVisible(true)} // 👉  onPress can tell when you are scrolling and not tapping
```

**Comment by tsdmrfth** [comment] 2020-08-10 20:12
I have merged solutions of @thomasttvo and @lrholmes and it has worked now. 💯

**Comment by Garrett1Tolbert** [comment] 2020-08-15 22:24
> I found much simpler workaround, it looks like instead of:
> 
> ```js
> onPress={() => setModalVisible(true)
> ```
> 
> You might try this
> 
> ```js
> onPressIn={() => setModalVisible(false)}
> onPressOut={() => setModalVisible(true)}
> ```
> 
> Of course, that means that your button component should provide you these events (TouchableOpacity does)

This works 100%! Even logically, it makes sense.

**Comment by safaiyeh** [comment] 2020-08-16 00:10
> I found much simpler workaround, it looks like instead of:
> 
> ```js
> onPress={() => setModalVisible(true)
> ```
> 
> You might try this
> 
> ```js
> onPressIn={() => setModalVisible(false)}
> onPressOut={() => setModalVisible(true)}
> ```
> 
> Of course, that means that your button component should provide you these events (TouchableOpacity does)

Thanks for the fix! Closing this out.

**Closed by safaiyeh** 2020-08-16 00:10 UTC
Labels: Bug, Platform: iOS

**Comment by salp13** [comment] 2020-08-16 15:27
For me a pretty quick fix was more in how the modal is triggered. I have a button that used to just set the modal's viewable variable to true when the button was pressed; however, now when the button is pressed I set the viewable to false and then setTimeout for 10 ms and then set the viewable variable to true. The change is pretty seamless, the user won't notice the 10ms.  This is better for me because I have a scrollView in the modal and wrapping the modal in a TouchableOpacity was not working well with scrolling. 


    onPressFilter() {
        this.setState({
          filterModalViewable: false,
        })
        setTimeout(() => this.setState({
          filterModalViewable: true,
        }), 10)
    }


Issue I'm still having is sending any data back to the parent component when the swipe occurs, but at least now the modal can be opened again and the scrolling works perfectly.

**Comment by jahnueldorelus** [comment] 2020-10-01 15:12
Going along with what @lieberscott said above, you have to go one step further for iOS 13. I've found that while @lieberscott's example worked perfectly, there's still a SERIOUS bug that can be very frustrating to fix. Be very careful when using the component "Button" from "react-native".

If you swipe down from anywhere in the Modal, @lieberscott's function will work perfectly. HOWEVER, if you click on a Button component and swipe down at the same time to dismiss the Modal, no event is fired. After hours of tinkering, I've found that you can bypass this by using TouchableOpacity instead of a Button. I have no idea why that is but upon using TouchableOpacity, @lieberscott's function worked perfectly again. Hope this helps anyone who has been running into this issue!

**Comment by ps73** [comment] 2020-10-23 12:34
Hey,
I have built a patch file for react-native 0.63.3 that fixes this issue: https://gist.github.com/ps73/012b8b97bb7866db4b2b4636a8396d98

If you embed this to your project you just have to set the onRequestClose property and the swipe down works as expected for `formSheet` and `pageSheet` modals on iOS. If you don't set onRequestClose the swipe down is disabled.

**Comment by alloy** [comment] 2020-10-23 13:02
@ps73 It’s a little hard for me to judge if this is generic enough that it would be a solution for all. If you do think or want to let others weigh in, mind creating a PR for it?

**Comment by lsiqueira-jc** [comment] 2020-10-28 20:36
> Eu encontrei uma solução alternativa muito mais simples, parece em vez de:
> 
> ```js
> onPress = { ( )  =>  setModalVisible ( true )
> ```
> 
> Você pode tentar isso
> 
> ```js
> onPressIn = { ( )  =>  setModalVisible ( false ) } 
> onPressOut = { ( )  =>  setModalVisible ( true ) }
> ```
> 
> Claro, isso significa que o componente do botão deve fornecer esses eventos (TouchableOpacity fornece)

Show man!
very good.

**Comment by jamesmcn1** [comment] 2020-11-02 17:48
@vasiliicuhar solution worked for me with RN 0.62.2:

```
      <Modal
        visible={visible}
        animationType={animation || 'slide'}
        onRequestClose={onClose}
        presentationStyle={presentationStyle}
        onDismiss={onDismiss}
        statusBarTranslucent={statusBarTranslucent}
      >
        <TouchableWithoutFeedback
          // for bug which prevents dismiss from firing on swipe close
          // https://github.com/facebook/react-native/issues/26892
          onPressOut={onDismiss}
        >
          <SafeAreaView
            testID={generateDismissibleModalTestId(testIDBase)}
            style={styles.SafeAreaView}
            forceInset={{ bottom: 'always' }}
          >
            {this.content()}
          </SafeAreaView>
        </TouchableWithoutFeedback>
      </Modal>
```

**Comment by oarsoy** [comment] 2020-11-03 20:33
This issue seems still exist in iOS 14 as well.

**Comment by arvidnilber** [comment] 2021-01-21 12:22
@alloy update on this bug? Not working yet in 0.63.4.

**Comment by alloy** [comment] 2021-01-21 14:26
I alas have no updates on this, my last question was if somebody wanted to solve it.

**Comment by oarsoy** [comment] 2021-01-21 17:18
That's embarrassing. Nobody could fix this Modal problem in React Native for long time.

**Comment by edi** [comment] 2021-01-28 15:09
I've tried quite a few of the above, nothing works for me ... others are quite ugly to implement.

Any advice on how to work around this issue ... seems quite weird.

**Comment by ps73** [comment] 2021-01-29 08:40
> Hey,
> I have built a patch file for react-native 0.63.3 that fixes this issue: https://gist.github.com/ps73/012b8b97bb7866db4b2b4636a8396d98
> 
> If you embed this to your project you just have to set the onRequestClose property and the swipe down works as expected for `formSheet` and `pageSheet` modals on iOS. If you don't set onRequestClose the swipe down is disabled.

@edi I've updated my patch-file for 0.63.4.

Just follow my instructions in the first comment. After that you have to reinstall your app on your simulator or real device.

After all these steps you can use `onRequestClose` property to allow the swipe down gesture (equivalent to android back button behavior). You can also disable swipe-gesture by unsetting `onRequestClose`.

**Comment by arvidnilber** [comment] 2021-01-31 15:40
So there is a fix for this issue? Why not include this in a new release?

**Comment by oarsoy** [comment] 2021-02-10 17:10
Airbnb was right. React Native is really s*cks. After every version change, even so base functionalities stop working for no reason and it's really tiring to track these things. And it seems Facebook or repository admins do NOT want to fix/merge the most of issues.

I'm switching to Flutter.

**Comment by jacobp100** [comment] 2021-02-10 17:25
Have people tried in 0.64?

**Comment by Yerlan** [comment] 2021-03-27 17:10
> Have people tried in 0.64?

Not working in `v0.64` as well

**Comment by oarsoy** [comment] 2021-03-27 21:37
> > Have people tried in 0.64?
> 
> Not working in `v0.64` as well

:) No surprise.

**Comment by Yerlan** [comment] 2021-03-28 08:26
> :) No surprise.

Yeah, there must be a good reason (I assume it's performance) why the patch was included and then removed from the recent version.

As a temporary workaround, you can use [React Native Modalize](https://jeremybarbet.github.io/react-native-modalize/#/), I think they pretty much have everything you want to work with page/form sheet modals (inc. swipe down to close).

![80501705-458d2d80-895f-11ea-9667-d193c135cabf](https://user-images.githubusercontent.com/3915771/112746595-8fe4b780-8fd1-11eb-9227-f6fbd720ae5d.gif)

**Comment by enestatli** [comment] 2021-04-03 10:37
My solution works only who uses `react-navigation` in her/his project.

Create a modal stack in your navigator and nest a regular stack inside it. Then simply call your modal screen anywhere in your project, just like your other screens. `navigation.navigate('MyModalScreen')`

Now, you can have ModalPresentationIOS transition in both platform.


```
 <RootStack.Navigator mode="modal">
      <RootStack.Screen
        name="Main"
        component={MainStackScreen}
        options={{ headerShown: false }}
      />
      <RootStack.Screen name="MyModalScreen" component={MyModalScreen} />
    </RootStack.Navigator>

**Comment by rockwotj** [comment] 2021-04-14 19:52
@rewieer can this be reopened? This is still an issue.

**Comment by fallaciousreasoning** [comment] 2021-04-19 11:07
I just encountered this too. I was pretty surprised @thomasttvo's suggestion fixed it. Would you mind explaining what it's doing?

> @r4mdat just put your Modal in a View with height: 0

```tsx
<View style={{ height: 0 }}>
    <Modal ...>
        <YourModalContent />
    </Modal>
<View>
```

**Comment by rockwotj** [comment] 2021-04-19 20:51
@fallaciousreasoning the height=0 trick doesn't seem to work for me :/

**Comment by thomasttvo** [comment] 2021-04-20 14:01
> I just encountered this too. I was pretty surprised @thomasttvo's suggestion fixed it. Would you mind explaining how the fix works?
> 
> > @r4mdat just put your Modal in a View with height: 0
> 
> ```tsx
> <View style={{ height: 0 }}>
>     <Modal ...>
>         <YourModalContent />
>     </Modal>
> <View>
> ```

That was a long time ago, but I vaguely remember it has something to do with event propagation and TouchableWithoutFeedback, not entirely sure tho.

**Comment by oarsoy** [comment] 2021-05-01 23:25
> > :) No surprise.
> 
> Yeah, there must be a good reason (I assume it's performance) why the patch was included and then removed from the recent version.
> 
> As a temporary workaround, you can use [React Native Modalize](https://jeremybarbet.github.io/react-native-modalize/#/), I think they pretty much have everything you want to work with page/form sheet modals (inc. swipe down to close).
> 
> ![80501705-458d2d80-895f-11ea-9667-d193c135cabf](https://user-images.githubusercontent.com/3915771/112746595-8fe4b780-8fd1-11eb-9227-f6fbd720ae5d.gif)

Modal is very base functionality. And it should stay as native. It doesn't make sense to use a third party dependency or library to be able to solve this basic problem or to be able to use modal.

**Comment by anthlasserre** [comment] 2021-05-04 14:49
> @vasiliicuhar solution worked for me with RN 0.62.2:
> 
> ```
>       <Modal
>         visible={visible}
>         animationType={animation || 'slide'}
>         onRequestClose={onClose}
>         presentationStyle={presentationStyle}
>         onDismiss={onDismiss}
>         statusBarTranslucent={statusBarTranslucent}
>       >
>         <TouchableWithoutFeedback
>           // for bug which prevents dismiss from firing on swipe close
>           // https://github.com/facebook/react-native/issues/26892
>           onPressOut={onDismiss}
>         >
>           <SafeAreaView
>             testID={generateDismissibleModalTestId(testIDBase)}
>             style={styles.SafeAreaView}
>             forceInset={{ bottom: 'always' }}
>           >
>             {this.content()}
>           </SafeAreaView>
>         </TouchableWithoutFeedback>
>       </Modal>
> ```

Thanks @vasiliicuhar 
I Confirm! Actually the only trick to close this type of modal is to do like this
```javascript
<Modal
  visible={showModal}
  animationType="slide"
  presentationStyle="formSheet"
>
  <TouchableWithoutFeedback
    // for bug which prevents dismiss from firing on swipe close
    // https://github.com/facebook/react-native/issues/26892
    onPressOut={() => console.log('Close modal')}
  >
    <View style={{ flex: 1 }}>
      {/* YOUR CONTENT */}
    </View>
  </TouchableWithoutFeedback>
</Modal>
```

**Comment by oarsoy** [comment] 2021-05-05 15:40
> ```js
> <Modal
>   visible={showModal}
>   animationType="slide"
>   presentationStyle="formSheet"
> >
>   <TouchableWithoutFeedback
>     // for bug which prevents dismiss from firing on swipe close
>     // https://github.com/facebook/react-native/issues/26892
>     onPressOut={() => console.log('Close modal')}
>   >
>     <View style={{ flex: 1 }}>
>       {/* YOUR CONTENT */}
>     </View>
>   </TouchableWithoutFeedback>
> </Modal>
> ```

I can confirm too, this example finally works with 0.63 & 0.64. I hope they will not break again this base functionality.

**Comment by whalemare** [comment] 2021-05-20 07:55
This solution close modal on any touch outside, not on swipe

**Comment by oarsoy** [comment] 2021-05-20 15:28
> This solution close modal on any touch outside, not on swipe.
> 
> We are waiting for merge this pr: #31500

I agree it's not ideal but only working solution so far. I hope they merge this because I think FB hates iOS and they love to keep it broken.

**Comment by sgup** [comment] 2021-06-16 23:21
Still having this issue

**Comment by Jonatthu** [comment] 2021-08-01 02:01
I am still having issues with this. Waiting on #31500
