### ISSUE TITLE
watchman permission problem

### ISSUE THREAD

**Issue by msudgh** [facebook/react-native#10476] opened 2016-10-20 09:50 UTC
Hello,
i'm trying to build a app and when i run `npm run start` command to building i got the following errors which contains watchman lib, i'm sure problem is from watchman permission. how can i fix this?
**P.S:** There's no problem when i use `npm run start` command with `sudo` 

---

Terminal Log:
```bash
masoud@zombies:~/Desktop/AwesomeProject$ npm run start

> AwesomeProject@0.0.1 start /home/masoud/Desktop/AwesomeProject
> node node_modules/react-native/local-cli/cli.js start

Scanning 715 folders for symlinks in /home/masoud/Desktop/AwesomeProject/node_modules (5ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /home/masoud/Desktop/AwesomeProject 

[10/20/2016, 1:09:32 PM] <START> Building Dependency Graph
[10/20/2016, 1:09:32 PM] <START> Crawling File System
[Hot Module Replacement] Server listening on /hot

React packager ready.

ERROR: Unknown option --no-pretty

Watchman:  watchman--no-pretty get-sockname returned with exit code 1 ERROR: Unknown option --no-pretty

 ERROR  watchman--no-pretty get-sockname returned with exit code 1 ERROR: Unknown option --no-pretty

Error: watchman--no-pretty get-sockname returned with exit code 1 ERROR: Unknown option --no-pretty

    at ChildProcess.<anonymous> (/home/masoud/Desktop/AwesomeProject/node_modules/fb-watchman/index.js:198:18)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.

npm ERR! Linux 4.4.0-43-generic
npm ERR! argv "/home/masoud/.nvm/versions/node/v6.5.0/bin/node" "/home/masoud/.nvm/versions/node/v6.5.0/bin/npm" "run" "start"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! AwesomeProject@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start`
npm ERR! Exit status 11
npm ERR! 
npm ERR! Failed at the AwesomeProject@0.0.1 start script 'node node_modules/react-native/local-cli/cli.js start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the AwesomeProject package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/react-native/local-cli/cli.js start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs AwesomeProject
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls AwesomeProject
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/masoud/Desktop/AwesomeProject/npm-debug.log
```

**Comment by ericvicenti** [comment] 2016-10-24 20:54
This appears to be a duplicate of https://github.com/facebook/react-native/issues/2941. Closing for now

**Closed by ericvicenti** 2016-10-24 20:54 UTC
