### ISSUE TITLE
Fresh install react native 0.64.0 causing PhaseScriptExecution error on build

### ISSUE THREAD

**Issue by ptdede** [facebook/react-native#31206] opened 2021-03-22 04:16 UTC
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Fresh install react native won't start on iOS. It's causing `PhaseScriptExecution` error. Complete errors: 
```
warning: Skipping duplicate build file in Compile Sources build phase: /Users/dede/Documents/.../AwesomeProject/node_modules/react-native/React/FBReactNativeSpec/FBReactNativeSpec/FBReactNativeSpec-generated.mm (in target 'FBReactNativeSpec' from project 'Pods')

** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/dede/Library/Developer/Xcode/DerivedData/AwesomeProject-bsimnvrrdjnvzpfrnwlngefpegdm/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBReactNativeSpec.build/Script-05D50821C94A0DBD14B3F558B92333A5.sh
(1 failure)
```

## React Native version:
```
System:
    OS: macOS 11.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 355.91 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.7.0 - ~/.nvm/versions/node/v14.7.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.7.0/bin/yarn
    npm: 7.5.2 - ~/.nvm/versions/node/v14.7.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.0 => 0.64.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Uninstall react-native-cli globally for both yarn and npm
2. `npx react-native init AwesomeProject`
3. `cd AwesomeProject &&  npx react-native start`
4. `npx react-native run-ios`

## Expected Results
The script should build and run the project into iOS simulator

## Snack, code example, screenshot, or link to a repository:
<img width="843" alt="Screen Shot 2021-03-22 at 12 18 06" src="https://user-images.githubusercontent.com/3388701/111940149-fb79e100-8b08-11eb-98ec-9b17c1a4adf3.png">

**Comment by jensneuber** [comment] 2021-03-22 08:51
Duplicate of https://github.com/facebook/react-native/issues/31181?

**Comment by ptdede** [comment] 2021-03-22 09:16
I solve this by moving the project into directory that the path not contain space in it.
ex: `/Users/dede/Documents/Poc Project` to `/Users/dede/Documents/POC`

This solve this issue. I think related to this: https://github.com/facebook/react-native/pull/31141

**Closed** 2021-03-22 09:17 UTC
Labels: Needs: Triage :mag:

**Comment by devinkg** [comment] 2021-11-26 07:32
> I solve this by moving the project into directory that the path not contain space in it. ex: `/Users/dede/Documents/Poc Project/` to `/Users/dede/Documents/POC/`
> 
> This solve this issue. I think related to this: #31141

This worked me too. Thanks ❤️
