### ISSUE TITLE
Flow cannot resolve react-native modules

### ISSUE THREAD

**Issue by skidding** [facebook/react-native#19797] opened 2018-06-19 06:21 UTC
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.5
      CPU: x64 Intel(R) Core(TM) m5-6Y54 CPU @ 1.10GHz
      Memory: 182.06 MB / 8.00 GB
      Shell: 5.2 - /usr/local/bin/zsh
    Binaries:
      Node: 8.11.2 - /usr/local/Cellar/node@8/8.11.2/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/Cellar/node@8/8.11.2/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react-native: ^0.56.0-rc.2 => 0.56.0-rc.2 
```

I tried with both `0.55.4` and `0.56.0-rc.2`.

## Description
Installing the latest `react-native` with the latest `flow-bin` yields type errors for every require call inside `node_modules/react-native/Libraries/react-native/react-native-implementation.js`

> Cannot resolve module Alert.
> Cannot resolve module AlertIOS.
> ...

![screenshot 2018-06-19 09 10 37](https://user-images.githubusercontent.com/250750/41579948-9b0535b2-73a1-11e8-9bf6-b8dd2de6fbda.png)

## Reproducible Demo
https://github.com/skidding/react-native-flow

The solution might be obvious, but I looked for it in many places and couldn't find it. Thanks!

**Comment by TheSavior** [comment] 2018-06-19 15:39
Duplicate of #19766. The fix has landed but a new version hasn’t been cut yet. You can use the fix to the flowconfig from that issue.

**Closed by TheSavior** 2018-06-19 15:39 UTC
