### ISSUE TITLE
[XMLHttpRequest] Fetch / XMLHttpRequest does not work if ssl certificate is not valid

### ISSUE THREAD

**Issue by artyomtrityak** [facebook/react-native#1884] opened 2015-07-06 18:42 UTC
React Native XMLHttpRequest finishing with error

```
The operation couldn’t be completed. (NSURLErrorDomain error -1202.)
```

Is it possible to add some flag to XMLHttpRequest to allow invalid ssl certificate?

**Comment by colinramsay** [comment] 2015-07-07 14:12
React Native's XMLHttpRequest is a polyfill for the web version of XHR. Since I don't believe you can do this in the web version then it shouldn't be available in the React Native version either.

**Comment by nicklockwood** [comment] 2015-07-07 15:25
This is a restriction imposed by iOS's networking stack, rather than something we've deliberately put in to emulate XHR's CORS behavior.

It looks like there's a solution here that you may be able to hack into RCTHTTPRequestHandler, if you're willing to dig into the Objective-C code: http://stackoverflow.com/questions/20230169/nsurlsession-server-with-self-signed-cert

**Comment by artyomtrityak** [comment] 2015-07-07 15:30
@colinramsay that's true but in Web version i can manually add exception in browser

**Comment by artyomtrityak** [comment] 2015-07-08 11:55
@nicklockwood thank you for your research, as you mention there is a solution using ObjC code, is it possible to include fix in XMLHttpRequest ? In browser you can manually add exception, in node.js you can add `process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";` to fix this issue.

That would be awesome to allow enabling untrusted requests without ObjC digging.

**Comment by despairblue** [comment] 2015-09-09 19:09
:+1:

**Comment by ide** [comment] 2015-09-09 19:56
Send a PR!

**Comment by despairblue** [comment] 2015-09-09 20:19
I doubt it would get merged. One option would be to ignore certificates all together, the other would be to add an override option to the fetch polyfill (or XMLHttpRequest), which would make it deviate from the spec.

**Comment by yoniholmes** [comment] 2016-03-11 11:04
Hi @artyomtrityak, did you have any success working around this problem? I'm working on an app for an internal team that relies on accessing webviews, and until the underlying certificate issue can be resolved this problem effectively prevents the app from working as intended. Any tips or work arounds welcome! Cheers, Jonathan

**Comment by JoeLucky** [comment] 2016-04-22 08:24
@artyomtrityak  Do you solve this problem in android now? I try to make it trusts all certificates, but didn't work. It really makes me headache. I am a fresh man about android.
By the way, I find a solution in IOS. Here the link
http://stackoverflow.com/questions/36289125/answer/submit 
But there seem to be some problem. (I try to download some file, but failed.)

**Comment by grabbou** [comment] 2016-04-24 12:47
FYI you can generate valid certificates using https://letsencrypt.org/ not only for development but also for production. That's probably a partial solution.

**Comment by mkonicek** [comment] 2016-07-29 23:08
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/xmlhttprequest-fetch-xmlhttprequest-does-not-work-if-ssl-certificate-is-not-valid

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Closed by mkonicek** 2016-07-29 23:08 UTC
Labels: Community Responsibility, Feature Request, Icebox

**Comment by aleclarson** [comment] 2016-10-02 07:36
@nicklockwood @ide Could we just override the necessary Objective-C when `RCT_DEV` is true?

[Here's a commit](https://github.com/aleclarson/react-native/commit/0e30c915d84dc99dbdc2e6ad5c6c6d5fd962b289) that does that very thing, if anyone's interested.

**Comment by xemasiv** [comment] 2018-02-22 13:08
Just use a Free SSL that isn't self-signed instead.

## Free SSL & React Native Apps

Problem:
* Your react-native app can't reach your http server, since https is required
* Your https server can't be reached, because sites / endpoints using self-signed certificates are disallowed
* Long story short, XHR / axios / Webview can't reach your server

Solution:

1. Generate a CSR

* You can use Namecheap's tool - https://decoder.link/csr_generator
* Make sure you keep the private key, you'll use it later

2. Go get a Free SSL catered by Comodo.

* https://ssl.comodo.com/free-ssl-certificate.php
* The certificate bundle you'll get won't be a self-signed one, a commodo support representative confirmed this with me.
* Use your CSR, then validate your ownership
* After couple of minutes you'll receive your cert bundle in your email, with 4 files
  * `api_realtycoast_io.crt` (named after the domain I used, which is api.realtycoast.io)
  * `AddTrustExternalCARoot.crt`
  * `COMODORSAAddTrustCA.crt`
  * `COMODORSADomainValidationSecureServerCA.crt`
  
3. Do a CA/End-Entity Certificate matching

* Go to CA/End-Entity Certificate Matcher
* Paste the content of your `api_realtycoast_io.crt` equivalent as the END ENTITY CERTIFICATE
* Paste the content of your `COMODORSADomainValidationSecureServerCA.crt` as the CA CERTIFICATE
* Validate that shit, should be successful - if so, we proceed

4. Configure your Express SSL configuration

* Create a `/ssl` folder
* Put all those certificate files there
* Create a `private.key` file, PASTE YOUR PRIVATE KEY from STEP 1 there
* Now we use your site's certificate, your private key, and your CA certificate

```
const fs = require('fs');
const http = require('http');
const https = require('https');
const express = require('express');
const bodyParser = require('body-parser');

const SSL = {
  credentials: {
    key: fs.readFileSync('ssl/private.key', 'utf8'),
    cert: fs.readFileSync('ssl/api_realtycoast_io.crt', 'utf8'),
    ca: [
      fs.readFileSync('ssl/COMODORSADomainValidationSecureServerCA.crt', 'utf8')
    ]
  }
};

const app = express();
app.use(bodyParser.json());
app.get('/', (req, res) => res.send('Hello World!'));
http.createServer(app).listen(80);
https.createServer(SSL.credentials, app).listen(443);
```

* Git add, commit and push that shit
* Run your nodejs server again

5. Verify that shit

* Visit your `https://yoursite.com/` that should be working well
* Visit `https://www.sslshopper.com/ssl-checker.html`
* Check your server endpoint's url there, you should be seeing ALL CHECKS, AND NO X's

6. Rebuild your react-native app, and re-run it - should be workign well now

* Test code for webview

```
import { WebView, View } from 'react-native';

// in your component render(), below

return (
<View style={{flex:1}}>
	<WebView
	source={{uri: 'https://api.realtycoast.io/auth'}}
	javaScriptEnabled={true}
	domStorageEnabled={true}
	startInLoadingState={true}
	style={{ flex:1, height: 500, width: 350 }}
	/>
	</View>
);
```

* Test code for axios

```
	// replace your baseURL and url, below
	
          <Button onPress={
            ()=>{
              const x = axios.create({
                baseURL: 'https://api.realtycoast.io/',
                timeout: 10000,
                headers: {
                  'Accept': 'application/json',
                  'Content-Type': 'application/json',
                }
              });
            x.request({
              url: '/user/123'
            })
              .then(function (response) {
                console.log(response);
              })
              .catch(function (error) {
                console.log(error);
              });
            }
          }>
            <Text>Axios Test</Text>
          </Button>
```
