### ISSUE TITLE
RCTRootView in UINavigationController has topLayoutGuide issues

### ISSUE THREAD

**Issue by quentinfasquel** [facebook/react-native#12283] opened 2017-02-08 11:37 UTC
### Description

Easiest is to show with a video: https://youtu.be/MwIoeJ4lChY

1- The scroll view's content inset isn't adjusting with the navigationController however it's supposed to by default. This content inset gets adjusted when putting the app in background and getting it back in foreground.
2- You can notice the warning view is going under the navigation bar.

### Reproduction

Using `facebook/react-native#master` with a custom CocoaPods integration of React (along with yoga) and having a simple Main.storyboard with a UINavigationController, adding an RCTRootView as a ViewController's view...and a simple code adding a ScrollView with a Text "Hello React!". Forcing a warning.

### Solution

I don't have one except using react-native-navigation to create the UINavigationController, but it isn't my goal for now as I am integrating a react view in an existing project.

### Additional Information

* React Native version: soon to be 0.42.0, facebook/react-native#master
* Platform: iOS
* Operating System: MacOS

**Comment by fkgozali** [comment] 2017-02-08 18:26
Not entirely sure, but could you try setting the navbar to non-translucent in your UINavigationController?

```
self.navigationBar.translucent = NO;
```

I think this won't fix (2), but likely (1).

**Comment by fkgozali** [comment] 2017-02-09 05:25
https://github.com/facebook/react-native/commit/3ca719072f5d0a48a570e365328b456c955ae596 should fix (2)

**Comment by hramos** [comment] 2017-07-25 22:59
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Closed by hramos** 2017-07-25 22:59 UTC
Labels: Icebox
