### ISSUE TITLE
scrollResponder.scrollResponderScrollNativeHandleToKeyboard crops FlatList content on focus

### ISSUE THREAD

**Issue by SMJ93** [facebook/react-native#14401] opened 2017-06-08 14:45 UTC
### Description

I have a flat list which includes a list of form elements (input, select etc). On any input focus I want the FlatList to scroll to the selected Element. I am using the scrollResponder to do this.

The focus works for the first item in the FlatList, but the further down the FlatList the form element the more out of sync the scroll gets. It seems to scroll to the correct position (y) in the FlatList, but crops out form elements further up the FlatList and adds appends a transparent area to the bottom of the FlatList. It basically removes the area from the top of the FlatList and adds to the bottom.

I need it to scroll down to the focussed input item and not crop other form elements out of the FlatList. I have put together some screenshots to try and help explain this (see bottom of question):

### Reproduction Steps and Sample Code

```
<FlatList
        keyExtractor={ item => item[0].name }
        ref={(thisComponent) => { this.questionsList = thisComponent; }}
        data={dataSource} //An array of elements

        renderItem={({ item, index }) => {
          return(
             //Each question is a FormElement (TextInput, Radio button etc)
            <Question
              key={ index }
              index={ index }
              question={ item }
              isLastQuestion={ (dataSource.length - 1) === index }
              onFocusScroll={ (refComponent = false) => {
                if (Platform.OS === 'ios' && !refComponent.target) {
                  setTimeout(() => {
                    const scrollResponder = this.questionsList.getScrollResponder();
                    if (scrollResponder) {
                      //This crops some of the form elements out of the FlatList
                      scrollResponder.scrollResponderScrollNativeHandleToKeyboard(
                        findNodeHandle(refComponent),
                        85,
                        false
                      );
                    }
                  }, 50);
                }
              }} />
          );

        }}
        />
```

### Solution

The top of the form should not be cropped (see screenshot 3) and it should scroll the the focussedItem with 85 bottom offset to the keyboard.

### Additional Information

* React Native version: 0.45.0
* Platform: iOS 10.3
* Development Operating System: MacOS
* Dev tools: Xcode 8.3.2 (8E2002)

### Screeshots

Before focus:
![1](https://user-images.githubusercontent.com/2145641/26933664-12e6c282-4c5f-11e7-884d-642ed1630b96.png)
On focus:
![2](https://user-images.githubusercontent.com/2145641/26933666-131015f6-4c5f-11e7-8874-ff6188ed49c1.png)
When I then scroll up the Form Element is cropped:
![3](https://user-images.githubusercontent.com/2145641/26933665-12ec7358-4c5f-11e7-9e97-5fb71b81503c.png)
At the bottom the cropped area has been appended to the FlatList:
![4](https://user-images.githubusercontent.com/2145641/26934922-8a1c9f2c-4c62-11e7-920f-e2a7c617a12c.png)

**Comment by hramos** [comment] 2017-06-08 16:06
This issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native).

StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

Will close this as this is really a question that should be asked on StackOverflow.

**Comment by SMJ93** [comment] 2017-06-08 16:09
@hramos it seems like a bug with React Native scrollResponder?

**Comment by hramos** [comment] 2017-08-16 03:08
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Closed by hramos** 2017-08-16 03:08 UTC
Labels: Icebox
