### ISSUE TITLE
More Context in setState Warning!

### ISSUE THREAD

**Issue by DHidee66** [facebook/react-native#6486] opened 2016-03-16 13:40 UTC
Hi,

It would be very helpful if the `setState on a unmounted component` warning gave any context on what the name of the component is or any other info to track down the issue.
I think react already has this.

Thank You!

**Comment by janicduplessis** [comment] 2016-03-17 03:37
I'm pretty sure this issue should be in the react repo instead since that's where this warning comes from.

**Comment by DHidee66** [comment] 2016-03-17 08:37
@janicduplessis They fixed the issue in React I think, maybe it doesn't work on RN.

**Comment by janicduplessis** [comment] 2016-03-19 01:42
What version of react-native are you using? Since 0.21 we use react from npm. You could check in your node_modules what version of react is installed. The fix for the warning you are talking about is only in react@0.14+

**Comment by DHidee66** [comment] 2016-03-19 08:46
RN 0.21 and React 0.14.7.

**Comment by brentvatne** [comment] 2016-03-20 18:27
@DHidee66 - if this is fixed on React then it will be pulled into React Native when React 15 is released (currently in RC), otherwise I agree with @janicduplessis that this an issue that belongs on the React repo :) Can you reproduce this in a simple example, try it on the current version of React Native and then on the web with the newest version of React and report it on the React repo if it still exists? :rocket:

Thanks for report!

**Closed by brentvatne** 2016-03-20 18:27 UTC

**Comment by DHidee66** [comment] 2016-03-20 19:36
@brentvatne That's what I'll do. Thank you for your help. :)
