### ISSUE TITLE
Build Failing on IOS with RN 0.61 

### ISSUE THREAD

**Issue by vigilantee** [facebook/react-native#27521] opened 2019-12-15 20:35 UTC
echo 'error: File /Users/abhishek/Library/Developer/Xcode/DerivedData/DishFishClientApp-afzwpvkciygvqbeypfawoirbjhfr/Build/Intermediates.noindex/ArchiveIntermediates/DishFishClientApp/BuildProductsPath/Release-iphoneos/DishFishClientApp.app/main.jsbundle does not exist. This must be a bug with'
error: File /Users/abhishek/Library/Developer/Xcode/DerivedData/DishFishClientApp-afzwpvkciygvqbeypfawoirbjhfr/Build/Intermediates.noindex/ArchiveIntermediates/DishFishClientApp/BuildProductsPath/Release-iphoneos/DishFishClientApp.app/main.jsbundle does not exist. This must be a bug with
+ echo 'React Native, please report it here: https://github.com/facebook/react-native/issues'
React Native, please report it here: https://github.com/facebook/react-native/issues
+ exit 2

**Comment by gokhandoslu** [comment] 2019-12-15 20:48
Duplicate of #27314

**Closed** 2020-03-05 00:50 UTC
Labels: Bug, Needs: Author Feedback, Platform: iOS, Ran Commands
