### ISSUE TITLE
Secure text being enabled on normal text fields from other text inputs

### ISSUE THREAD

**Issue by JoeyHenriques** [facebook/react-native#8374] opened 2016-06-23 18:30 UTC
If you create a field as secure text, then remove it from the DOM and replace it with a normal text input, the normal text input has secure text turned on by default. 

[Here is a quick rnplay of the bug.](https://rnplay.org/apps/beptdQ) You'll notice that flipping from normal text to secure text, then back to normal text will turn on the secure text field by default, regardless of if there was text previously in the field. 

Currently using version .26 on mac. The rnplay is for iOS.

**Comment by christopherdro** [comment] 2016-06-26 16:32
It appears that secure entry isn't reset automatically.

As a temp workaround you can force `secureTextEntry={false}`.

**Comment by christopherdro** [comment] 2016-06-26 16:32
@facebook-github-bot bugfix

**Comment by facebook-github-bot-9** [comment] 2016-06-26 16:32
Hey @JoeyHenriques, we're a small team and rely on the community to fix issues that don't affect fb apps. If you're sure this is a bug can you send a pull request with a fix?

**Comment by RD1991** [comment] 2016-09-13 07:18
Not able to reproduce with react-native 0.33 version.

**Comment by lacker** [comment] 2016-12-15 00:39
I'm going to close since it seems this is fixed now. Thanks everyone!

**Closed by lacker** 2016-12-15 00:39 UTC
Labels: Ran Commands
