### ISSUE TITLE
React Native 0.70.1 Release APK could not be installed on device on Android 10

### ISSUE THREAD

**Issue by Bayramito** [facebook/react-native#34772] opened 2022-09-23 07:11 UTC
### Description

I just started to get negative feedbacks from our testers that on Android 10 devices release APK that i sent to them cannot be installed. 

I don't know how to debug this too since it's a release apk.  Is there anyone facing this issue? 
On android simulators like 'genymotion' works normally but on real device cannot be installed. 

I generate the apk with 

`./gradlew assembleRelease`

command, i don't know how to deal with this

### Version

0.70.1

### Output of `npx react-native info`

none

### Steps to reproduce

cd android && gradlew assembleRelease - on WIN

### Snack, code example, screenshot, or link to a repository

none

**Comment by cortinico** [comment] 2022-09-23 11:38
> I just started to get negative feedbacks from our testers that on Android 10 devices release APK that i sent to them cannot be installed.

What's the error message? We can't help without further information. Thanks

**Comment by ts-ign0re** [comment] 2022-09-26 08:32
Hi! Could you provide `android/app/build.gradle` file listing here (please remove sensitive information)

Thank you

**Comment by agrittiwari** [comment] 2022-09-28 11:34
I am also facing similar issue @cortinico  I guess.
 I don't know what led to code break overnight. 
 MIne error occured during build failure:
 `
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed with multiple errors, see logs`

Should I add more here or raise a separate issue!?

**Comment by Bayramito** [comment] 2022-09-28 13:02
Just remove the old installation

**Comment by agrittiwari** [comment] 2022-09-29 04:31
Tried all the conventional ways, but nothing worked!
There's this release of Android 12, and the error is associated with it, I guess so.
Similar error:
https://www.reddit.com/r/reactnative/comments/xq95ih/task_appprocessdebugmainmanifest_failed_manifest/?utm_medium=android_app&utm_source=share

**Comment by agrittiwari** [comment] 2022-09-29 04:36
Here's the complete Error:

`
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1372 file(s) to forward-jetify. Using 8 workers...
info Starting JS server...
* daemon not running; starting now at tcp:5037
* daemon started successfully
info Launching emulator...
info Successfully launched emulator.
info Installing the app...
Starting a Gradle Daemon, 2 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Configure project :@react-native-firebase_analytics
:@react-native-firebase_analytics package.json found at C:\Users\TJ\Desktop\Work\truckjunctionnew\node_modules\@react-native-firebase\analytics\package.json
:react-native-firebase_app package.json found at C:\Users\TJ\Desktop\Work\truckjunctionnew\node_modules\@react-native-firebase\app\package.json
:@react-native-firebase_analytics:firebase.bom using default value: 29.1.0
:@react-native-firebase_analytics package.json found at C:\Users\TJ\Desktop\Work\truckjunctionnew\node_modules\@react-native-firebase\analytics\package.json
:@react-native-firebase_analytics:version set from package.json: 14.5.0 (14,5,0 - 14005000)
:@react-native-firebase_analytics:android.compileSdk using custom value: 31
:@react-native-firebase_analytics:android.targetSdk using custom value: 31
:@react-native-firebase_analytics:android.minSdk using custom value: 21
:@react-native-firebase_analytics:reactNativeAndroidDir C:\Users\TJ\Desktop\Work\truckjunctionnew\node_modules\react-native\android

> Configure project :react-native-firebase_analytics
:react-native-firebase_analytics package.json found at C:\Users\TJ\Desktop\Work\truckjunctionnew\node_modules\@react-native-firebase\analytics\package.json
:react-native-firebase_app package.json found at C:\Users\TJ\Desktop\Work\truckjunctionnew\node_modules\@react-native-firebase\app\package.json
:react-native-firebase_analytics:firebase.bom using default value: 29.1.0
:react-native-firebase_analytics package.json found at C:\Users\TJ\Desktop\Work\truckjunctionnew\node_modules\@react-native-firebase\analytics\package.json
:react-native-firebase_analytics:version set from package.json: 14.5.0 (14,5,0 - 14005000)
:react-native-firebase_analytics:android.compileSdk using custom value: 31
:react-native-firebase_analytics:android.targetSdk using custom value: 31
:react-native-firebase_analytics:android.minSdk using custom value: 21
:react-native-firebase_analytics:reactNativeAndroidDir C:\Users\TJ\Desktop\Work\truckjunctionnew\node_modules\react-native\android

> Configure project :react-native-firebase_app
:react-native-firebase_app package.json found at C:\Users\TJ\Desktop\Work\truckjunctionnew\node_modules\@react-native-firebase\app\package.json
:react-native-firebase_app:firebase.bom using default value: 29.1.0
:react-native-firebase_app:play.play-services-auth using default value: 20.1.0
:react-native-firebase_app package.json found at C:\Users\TJ\Desktop\Work\truckjunctionnew\node_modules\@react-native-firebase\app\package.json
:react-native-firebase_app:version set from package.json: 14.5.0 (14,5,0 - 14005000)
:react-native-firebase_app:android.compileSdk using custom value: 31
:react-native-firebase_app:android.targetSdk using custom value: 31
:react-native-firebase_app:android.minSdk using custom value: 21
:react-native-firebase_app:reactNativeAndroidDir C:\Users\TJ\Desktop\Work\truckjunctionnew\node_modules\react-native\android

> Configure project :react-native-firebase_messaging
:react-native-firebase_messaging package.json found at C:\Users\TJ\Desktop\Work\truckjunctionnew\node_modules\@react-native-firebase\messaging\package.json
:react-native-firebase_app package.json found at C:\Users\TJ\Desktop\Work\truckjunctionnew\node_modules\@react-native-firebase\app\package.json
:react-native-firebase_messaging:firebase.bom using default value: 29.1.0
:react-native-firebase_messaging package.json found at C:\Users\TJ\Desktop\Work\truckjunctionnew\node_modules\@react-native-firebase\messaging\package.json
:react-native-firebase_messaging:version set from package.json: 14.5.0 (14,5,0 - 14005000)
:react-native-firebase_messaging:android.compileSdk using custom value: 31
:react-native-firebase_messaging:android.targetSdk using custom value: 31
:react-native-firebase_messaging:android.minSdk using custom value: 21
:react-native-firebase_messaging:reactNativeAndroidDir C:\Users\TJ\Desktop\Work\truckjunctionnew\node_modules\react-native\android

> Task :app:processDebugMainManifest FAILED

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.


Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings
152 actionable tasks: 2 executed, 150 up-to-date
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
C:\Users\TJ\Desktop\Work\truckjunctionnew\android\app\src\main\AndroidManifest.xml Error:
        Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.
C:\Users\TJ\Desktop\Work\truckjunctionnew\android\app\src\main\AndroidManifest.xml Error:
        Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 40s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
C:\Users\TJ\Desktop\Work\truckjunctionnew\android\app\src\main\AndroidManifest.xml Error:
        Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.
C:\Users\TJ\Desktop\Work\truckjunctionnew\android\app\src\main\AndroidManifest.xml Error:
        Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 40s

    at makeError (C:\Users\TJ\Desktop\Work\truckjunctionnew\node_modules\execa\index.js:174:9)
    at C:\Users\TJ\Desktop\Work\truckjunctionnew\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (C:\Users\TJ\Desktop\Work\truckjunctionnew\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (C:\Users\TJ\Desktop\Work\truckjunctionnew\node_modules\@react-native-community\cli\build\index.js:192:9)
info Run CLI with --verbose flag for more details.
`
What I tried  are these resources: [This](https://stackoverflow.com/questions/28095703/manifest-merger-failed-error/31793227#31793227) , [this](https://stackoverflow.com/questions/35842955/manifest-merger-failed-with-multiple-errors-in-android-studio) and [this](https://stackoverflow.com/questions/67654506/manifest-merger-failed-targeting-android-12/67668116#67668116) 
Kindly let me know, I am trying all of these links again

**Comment by agrittiwari** [comment] 2022-09-29 04:52
Solved with this, 
Facebook SDK release version error
[https://stackoverflow.com/questions/73875070/execution-failed-for-task-appprocessdebugmainmanifest](https://stackoverflow.com/questions/73875070/execution-failed-for-task-appprocessdebugmainmanifest)

**Comment by cortinico** [comment] 2022-10-03 11:53
The conversation is going off-topic so I'm closing this.

@Bayramito is unresponsieve, hence I'm closing this. I've just tested on a blank project and I could not reproduce the issue.

@agrittiwari please open a separate issue, or refer to other issue more specific to your issue https://github.com/facebook/react-native/issues/34827

**Closed by cortinico** 2022-10-03 11:53 UTC
Labels: Platform: Android, Needs: Attention
