### ISSUE TITLE
Error: Command failed:

### ISSUE THREAD

**Issue by TuKun33** [facebook/react-native#10730] opened 2016-11-04 05:03 UTC

**Comment by TuKun33** [comment] 2016-11-04 05:04
child_process.js:488
    throw err;
    ^

Error: Command failed: D:\Folder(6)\Desktop\project\rn\project_1\node_modules\react-native\local-cli\setup_env.bat
'D:\Folder' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

    at checkExecSyncError (child_process.js:465:13)
    at Object.execFileSync (child_process.js:485:13)
    at Object.run (D:/Folder(6)/Desktop/project/rn/project_1/node_modules/react-native/local-cli/cliEntry.js:163:16)
    at Object.<anonymous> (C:\Users\Natukun\AppData\Roaming\npm\node_modules\react-native-cli\index.js:116:7)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)

**Comment by hramos** [comment] 2016-11-04 21:15
Closing due to lack of sufficient information. Check out the new issue template for tips on what info we're looking for!

**Closed by hramos** 2016-11-04 21:15 UTC

**Comment by Qwindoo** [comment] 2016-11-13 14:34
Hi, I do have the exact same issue. What kind of additional info would you need?

```
C:\Users\Me\code\AwesomeProject>react-native run-android
child_process.js:506
throw err;
^

Error: Command failed: C:\Users\Me\code\AwesomeProject\node_modules\react-native\local-cli\setup_env.bat
at checkExecSyncError (child_process.js:483:13)
at Object.execFileSync (child_process.js:503:13)
at Object.run (C:/Users/Me/code/AwesomeProject/node_modules/react-native/local-cli/cliEntry.js:157:16)
at Object.<anonymous> (C:\Users\Me\AppData\Roaming\npm\node_modules\react-native-cli\index.js:116:7)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.runMain (module.js:604:10)

```

**Comment by TuKun33** [comment] 2016-11-14 03:54
IT is like the cli have error ！i am useing windows10. my friends use win7 is ok



发自我的小米手机
在 Qwindoo <notifications@github.com>，2016年11月13日 下午10:35写道：

Hi, I do have the exact same issue. What kind of additional info would you need?

C:\Users\Me\code\AwesomeProject>react-native run-android
child_process.js:506
throw err;
^

Error: Command failed: C:\Users\Me\code\AwesomeProject\node_modules\react-native\local-cli\setup_env.bat
at checkExecSyncError (child_process.js:483:13)
at Object.execFileSync (child_process.js:503:13)
at Object.run (C:/Users/Me/code/AwesomeProject/node_modules/react-native/local-cli/cliEntry.js:157:16)
at Object.<anonymous> (C:\Users\Me\AppData\Roaming\npm\node_modules\react-native-cli\index.js:116:7)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.runMain (module.js:604:10)

**Comment by wenkesj** [comment] 2017-01-29 22:59
@TuKun33 I think this is caused by a lack of file permissions. If you attempt to move `/cli.js` or any directories containing the file, you are risking some issues with permissions. FMI, search **EACCES**.

**Comment by shemmarrah** [comment] 2017-03-20 15:09
@TuKun33 Did u ever fixed this issue. I need help. I'm using windows 8.1, node v 7.7.3, npm v4.4.1, 
yarn v0.21.3, and Python 2.7.13. At this point, I have no clue what I can be possibly be doing wrong.

C:\Users\shemmarrah\Desktop\shem3>react-native run-android
The system cannot find the path specified.
child_process.js:512
    throw err;
    ^

Error: Command failed: C:\Users\shemmarrah\Desktop\shem3\node_modules\react-native\local-cli\setup_env.bat
The system cannot find the path specified.

at checkExecSyncError (child_process.js:489:13)
at Object.execFileSync (child_process.js:509:13)
at Object.run (C:/Users/shemmarrah/Desktop/shem3/node_modules/react-native/local-cli/cliEntry.js:136:16)
    at Object.<anonymous> (C:\Users\shemmarrah\AppData\Roaming\npm\node_modules\react-native-cli\index.js:117:7)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)

**Comment by knoja4** [comment] 2017-09-05 16:14
I am having the same exact issue as the folks above. Why was this issue closed? It seems to me that the info provided sufficiently details the problem. The fact that this is not a one-off issue should also add to its legitimacy. What gives???

**Comment by taggaddaaaa** [comment] 2017-09-09 17:50
inside your project : 
``chmod -R 777 node_modules``
that will fix the issue

**Comment by pareshchouhan** [comment] 2017-09-20 12:33
@taggaddaaaa , this is windows so that won't work.
