### ISSUE TITLE
Android <Text> color becomes invisible when switching back to initial state

### ISSUE THREAD

**Issue by syntag** [facebook/react-native#29717] opened 2020-08-20 22:21 UTC
## Description
This happens on `react-native: 0.63.2` on `Android`.

<Text> color is visible initially, however, when you dynamically update a state to change the color of <Text> and then revert it back by changing the state, the text will become invisible. This did not happen on `react-native: 0.62.2` and previous versions. Android forgets what its initial color was unless you explicitly set the default color. 

I also thought it might be my default Android theme, but here is what I have for that:
**/android/app/main/res/values/styles.xml**
```xml
<resources>
    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="android:textColor">#000000</item>
    </style>
</resources>
```

## React Native version:
```
System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz
    Memory: 33.62 GB / 63.93 GB
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.5 - ~\AppData\Roaming\npm\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
  Languages:
    Java: 12.0.2 - /c/Program Files (x86)/Java/jdk-12.0.2/bin/javac
    Python: 2.7.14 - /c/Users/Steven/.windows-build-tools/python27/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
**Example code:**
```javascript
let active = false;
<Text style={active ? { color: 'green' } : null}>Example</Text>
```
1. "Example" text is initially black (default color) and visible since `active` is false
2. Set `active` state to true to toggle text color to green.
3. Then set `active` state back to false, the text color is now invisible.

## Expected Results
What I expect to happen is for the text to return back to its original color before the state was changed.

## Snack, code example, screenshot, or link to a repository:
**react-native (0.63.2):**

```javascript
import * as React from 'react';
import { Text, View, TouchableOpacity, StyleSheet } from 'react-native';

export default function App() {
  const [active, setActive] = React.useState(false);

  return (
    <View >
      <Text style={active ? {color: 'green'} : null}>Example</Text>

      <TouchableOpacity onPress={() => setActive(!active)}>
        <Text>Toggle Active</Text>
      </TouchableOpacity>
    </View>
  );
}
```

**Comment by safaiyeh** [comment] 2020-08-24 05:19
Thanks for the issue @SYNTAG. This is odd behavior... seems to be introduced in 0.63. Thanks for the code snipet.

**Comment by hank121314** [comment] 2020-09-03 01:51
Hi @safaiyeh and @SYNTAG .
I have made a pr to fix this issue.
Would you please help me to test it?

**Comment by safaiyeh** [comment] 2020-09-03 01:58
Awesome @hank121314! I'll check this out tomorrow. @ me if I don't give an update as I promised

**Comment by effektsvk** [comment] 2020-09-08 14:31
@safaiyeh Hello, I believe I stumbled upon this issue as well, although for me it's happening with the `tintColor` prop on Image component. Any chance the PR is getting merged? Thanks. 🙏

**Comment by hank121314** [comment] 2020-09-09 00:34
Hi @effektsvk !
I think this should be a related issue.
How did you patch node_modules with the change in PR?
Did you use [building from source](https://github.com/facebook/react-native/wiki/Building-from-source)?
And also thanks for your testing!

**Comment by hank121314** [comment] 2020-09-09 02:19
I have made a video to show the patch should work.
Before patching: https://streamable.com/x4hfk8
After patching: https://streamable.com/ycf9k9
Example code: 
```
import * as React from 'react';
import {Text, View, TouchableOpacity, PlatformColor, Image} from 'react-native';

export default function App() {
  const [active, setActive] = React.useState(false);

  return (
    <View>
      <Text style={active ? {color: 'green'} : null}>Example</Text>
      <Text
        style={
          active ? {color: PlatformColor('@android:color/holo_purple')} : null
        }>
        Example2
      </Text>
      <Image
        source={{
          uri:
            'https://www.edamam.com/web-img/22c/22c27bdc6b8dc67215c7478cb4e5dc42.jpg',
        }}
        style={
          active
            ? {tintColor: 'green', width: 200, height: 200}
            : {width: 200, height: 200}
        }
      />
      <TouchableOpacity onPress={() => setActive(!active)}>
        <Text>Toggle Active</Text>
      </TouchableOpacity>
    </View>
  );
}
```

**Comment by effektsvk** [comment] 2020-09-09 07:43
I think you're right, I didn't try building from source, I just patched the .java file. I didn't realize it was pre-compiled. 😅 I will try it out and let you know, but I think it will work.

**Comment by effektsvk** [comment] 2020-09-10 06:57
I tried building from source, faced some issues while building which I eventually solved, but in the end, it did not work for me. Although I'm not 100% sure that I did it correctly. I checked the size of `.aar` file, it is slightly different than the one in `node_modules` of the clean app so I guess there should be some change.

**Comment by preflower** [comment] 2020-12-09 08:26
Have any feedback about this question ?

**Comment by tell-y** [comment] 2021-02-01 06:17
Hi @safaiyeh @hank121314 
I'm facing almost same issue on TextInput.
You can reproduce it like this.

```
import * as React from 'react';
import { Text, View, TouchableOpacity, StyleSheet, TextInput } from 'react-native';

export default function App() {
  const [active, setActive] = React.useState(false);
  const [text, setText] = React.useState("");
  return (
    <View >
      <Text style={active ? {color: 'green'} : null}>Example</Text>
      <TextInput
        style={active ? {color: 'green'} : null} // also not good works with style={active ? {color: 'green'} : { color: 'black' }}
        value={text}
        onChange={({value}) => setText(value)}
      />
      <TouchableOpacity onPress={() => setActive(!active)}>
        <Text>Toggle Active</Text>
      </TouchableOpacity>
    </View>
  );
}
```

**Comment by hank121314** [comment] 2021-02-01 06:42
Hi @tell-y can you try to patch this pr #29830 to test whether the pr fixes your issue?
If not this might be a different issue.

**Comment by tell-y** [comment] 2021-02-03 04:59
I tried to [set up my environment](https://github.com/facebook/react-native/wiki/Building-from-source#android) to test it, but other issue is preventing me.
I'm trying to resolve my set up issue, I need more time.

**Comment by tell-y** [comment] 2021-02-03 06:55
Hi @hank121314 
I confirmed the P-R fix works well but unfortunately it does not effect to TextInput.

https://user-images.githubusercontent.com/6883692/106709625-2af78b80-6638-11eb-8447-a76b2ee09a76.mov

**Closed** 2021-08-18 01:01 UTC
Labels: Resolution: PR Submitted, Platform: Android, API: StyleSheet, Component: Text
