### ISSUE TITLE
Immutable list rehydrating as a map, after upgrading to react-native 0.44.0

### ISSUE THREAD

**Issue by cbjs** [facebook/react-native#13746] opened 2017-05-03 01:26 UTC
### Description

use redux / immutable for state. 
redux-persist / redux-persist-transform-immutable for state persistence.

Every is good with react-native 0.43.4.
Immutable list rehydrating as a map, after upgrading to react-native 0.44.0

![1](https://cloud.githubusercontent.com/assets/1215843/25645630/6b669494-2fe2-11e7-8eab-d5d970e814a2.png)

### Reproduction Steps and Sample Code

```js
import { persistStore, autoRehydrate } from 'redux-persist';
import immutableTransform from 'redux-persist-transform-immutable';

const configureStore = () => {
  const store = createStore(
    reducer,
    composeEnhancers( applyMiddleware(...middlewares), autoRehydrate() )
  );

  return store;
}
const store = configureStore();

persistStore(store, {
      storage: AsyncStorage,
      transforms: [immutableTransform()]
});
```

### Solution

No workaround.
May this issue is related to packager updates in 0.44.0
related issues: https://github.com/rt2zz/redux-persist-transform-immutable/issues/21
https://github.com/glenjamin/transit-immutable-js/issues/32

### Additional Information

* React Native version: [0.44.0]
* Platform: [Android]
* Development Operating System: [Linux]
* Dev tools: [android-23]

**Comment by brunolemos** [comment] 2017-05-29 04:12
Hi @cbjs,

#### Problem
This issue was caused by multiple versions os `immutable` being installed, like pointed out on this issue: https://github.com/glenjamin/transit-immutable-js/issues/32

#### Solution
Run: `npm i --save react-native@0.45.0-rc.2 react@16.0.0-alpha.12`

Upgrade `react-native` to `0.45`, as `immutable` dependency has been removed in this [commit](https://github.com/facebook/react-native/commit/be5a4609e6359b01f8cde540baedd8f9e3716617).


#### Alternative solution
> Ensure you only have 1 version of `immutable` installed. Change your immutable version to the same as react native is using (`npm i --save immutable@3.7.6`). Check for other packages requiring a specific version of `immutable` as well. Make a PR to them removing it or moving to `peerDependencies` if necessary. *(if you use npm5 or yarn, check the lock file to see all immutable versions and who required them)*

Feel free to close this issue if it works for you.
Thanks!

**Comment by hramos** [comment] 2017-07-31 21:54
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Closed by hramos** 2017-07-31 21:54 UTC
Labels: Icebox
