### ISSUE TITLE
fetch's response.json() promise not getting resolved when debugging in chrome

### ISSUE THREAD

**Issue by akocmark** [facebook/react-native#7381] opened 2016-05-04 10:53 UTC
Hi there,

I'm trying to run the android version of the sample code on react-native's tutorial page. It runs exactly like expected however, when running the code with chrome debug enabled, the promise returned by response.json() doesn't get resolved.
It will only get resolved when:
 1) I reload the js files.
2) I close the app and re-open it again.

here's my code snippet
```
  fetchData() {

    console.log('pre-fetch');
    fetch(REQUEST_URL)
      // .then((response) => response.json())
      .then((response) => {
        console.log('fetch-promise resolution');
        console.log(response.json);
        return response.json();
      })
      .then((responseData) => {
        console.log('response.json-promise resolution');
        // this.setState({
        //   dataSource: this.state.dataSource.cloneWithRows(responseData.movies),
        //   loaded: true,
        // });
      })
      .done();
  }
```

and here are the screenshots

1) The app stopped at `console.log(response.json);`
![Alt text](http://i.imgur.com/WMnNGZg.png?raw=true)

2) When reloading the js files (or closing and re-opening the app), you could see that the previous promise returned by response.json() got resolved and stopped again before resolving the new promise
![Alt text](http://i.imgur.com/lxAtdNi.png?raw=true)

Am I missing something here?
Here is my machine
OS: Mac OSX Yosemite
NodeJS: 4.2.3
Chrome: Version 50.0.2661.86 (64-bit)
React-Native: 0.24.1

Thanks

**Comment by damusnet** [comment] 2016-05-04 11:33
@facebook-github-bot duplicate #6679

**Comment by facebook-github-bot-5** [comment] 2016-05-04 11:46
@damusnet tells me this issue is a duplicate of #6679. Let's discuss there, closing this one.

**Closed by facebook-github-bot-5** 2016-05-04 11:46 UTC
Labels: Ran Commands

**Comment by mkonicek** [comment] 2016-05-04 18:35
Thanks for finding the duplicate @damusnet!
