### ISSUE TITLE
Add callbacks to Navigator methods (push / pop / etc)

### ISSUE THREAD

**Issue by JedWatson** [facebook/react-native#2313] opened 2015-08-12 17:53 UTC
Not sure if this is something you're interested in adding, but I think it would be useful to be able to pass a `callback` to `Navigator` methods that would fire when the transition (as defined by the `sceneConfig`) has completed.

### Use case

I'm working on an app with a pin entry screen that is displayed whenever you start a workflow on the Home screen. I want the pin entry scene to float up from the bottom of the screen, then when it's dismissed, I want the next scene to enter from the right _after_ the pin screen has animated out.

### Example

(user taps a button)

```
navigator.push({
  scene: PinEntryScene,
  sceneConfig: FloatFromBottom,
  props: { nextScene: WorkflowScene }
});
```

(user enters pin)

```
navigator.pop(() => {
  navigator.push({
    scene: this.props.nextScene,
    sceneConfig: HorizontalSwipeJump
  });
});
```

### Workaround

It's awkward to use the `navigationContext` events to manage this, so at the moment I'm wrapping my next scene transition in a `setTimeout` which is quite brittle (it relies on knowing the `sceneConfig` used to transition to a scene, which will not always be possible)

```
navigator.pop();
setTimeout(() => {
  navigator.push({
    scene: this.props.nextScene,
    sceneConfig: HorizontalSwipeJump
  });
}, 500);
```

...or is there a better way to achieve this that I've missed?

**Comment by ide** [comment] 2015-08-12 21:55
Cc @ericvicenti @hedgerwang I think we wanted events instead of callbacks. Do we just need willblur/didblur to address this use case?

**Comment by potsypantsy** [comment] 2015-08-13 06:20
@JedWatson previously I was using setTimeout, but I wasn't sure what delay to use. I am currently using InteractionManager.runAfterInteractions as an alternative work around.

**Comment by hedgerwang** [comment] 2015-08-13 19:35
@JedWatson we're building the navigation events system that supports bubbling, propagation, and reconciliation.

For instance:

```
// hooks for upcoming actions.
navigation.addListener('action', (event) => {
  var route = event.data.route;
  if (route === 'modal-route' && navigation.route !== route) {
    // you can't leave a route while a modal-route is focused.
    event.preventDefault();
  }
});

// hooks for upcoming changes.
navigation.addListener('willchange', (event) => {
  console.log({
    nextRoute: event.data.route,
    nextStack: event.data.stack,
  });
});

// hooks for monitioring changes.
navigation.addListener('change', (event) => {
  console.log({
    currentRoute: event.target.route,
    currentStack: event.target.stack,
  });
});

// enters a modal scene
navigation.push('modal-route');

// enters another scene, and this will be prevented.
navigation.push('blah-route');

// exit the modal scene
navigationContext.pop();
```

**Comment by brentvatne** [comment] 2015-09-13 21:57
Conversation here seems to have died and work is being done on this, so I'll close this as the issue isn't doing much good any more :smile:

**Closed by brentvatne** 2015-09-13 21:57 UTC

**Comment by Kudo** [comment] 2015-11-27 11:45
Are there any updates for change/willchange or willblur/didblur event?
I didn't see these events in current master branch code.
I would like to have willblur/didblur and I can help for a PR but not sure if this will fit React Native's road map.

My use case is for react-redux.
Currently I use Navigator with react-redux, unfortunately, Navigator.push() will keep old components and these old/hidden components also listen for new actions.
When doing Navigator.pop(), the old component was be changed due to previous action changes.

What I am thinking is to add `Component.tryUnsubscribe()` in willblur and `Component.trySubscribe()` in didfocus.

**Comment by hulvei3** [comment] 2016-12-28 09:08
For me the problem was that the `InteractionManager` wasn't highlighted enough in the docs :)
If you just need to wait for animations to finish use this.
http://facebook.github.io/react-native/releases/0.39/docs/timers.html
