### ISSUE TITLE
Error running react-native-upgrade on 0.57.1: Couldn't find preset "module:metro-react-native-babel-preset"

### ISSUE THREAD

**Issue by mimamuh** [facebook/react-native#21531] opened 2018-10-06 11:05 UTC
## Environment
```
React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      Memory: 516.46 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 23.0.3, 26.0.3, 27.0.3
        API Levels: 23, 26, 27, 28
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^v4.0.0-alpha.24 => 4.0.0-alpha.24
      @types/react: ^16.4.14 => 16.4.14
      @types/react-native: ^0.57.0 => 0.57.0
      react: 16.5.0 => 16.5.0
      react-native: 0.57.1 => 0.57.1
```
## Description
I tried to upgrade from 0.57.1 to 0.57.2 with `react-native-upgrade` but it fails with the following error: 
```
Error: Couldn't find preset "module:metro-react-native-babel-preset" relative to directory "/Users/macbook/Documents/jobs/coding/app"
    at /Users/macbook/.nvm/versions/node/v8.12.0/lib/node_modules/react-native-git-upgrade/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/macbook/.nvm/versions/node/v8.12.0/lib/node_modules/react-native-git-upgrade/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/macbook/.nvm/versions/node/v8.12.0/lib/node_modules/react-native-git-upgrade/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/macbook/.nvm/versions/node/v8.12.0/lib/node_modules/react-native-git-upgrade/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/macbook/.nvm/versions/node/v8.12.0/lib/node_modules/react-native-git-upgrade/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/Users/macbook/.nvm/versions/node/v8.12.0/lib/node_modules/react-native-git-upgrade/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/macbook/.nvm/versions/node/v8.12.0/lib/node_modules/react-native-git-upgrade/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/macbook/.nvm/versions/node/v8.12.0/lib/node_modules/react-native-git-upgrade/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:566:32)
```

## Reproducible Demo
Use this repro: I made it for a different issue, but it is mostly a blank new setup where I try to run the upgrade command and it fails there too: [https://github.com/mimamuh/storybook-issue-4286](https://github.com/mimamuh/storybook-issue-4286)

**Comment by mimamuh** [comment] 2018-10-10 15:19
@ataomega Not for the issue itself. I upgrades using the manual upgrade. I don‘t use expo but the native code install and on the docs you can read about how ton manually upgrade if the git upgrade failed: https://facebook.github.io/react-native/docs/upgrading


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jinaddavid** [comment] 2018-10-10 15:45
Facing the same issue , please any solution to this ?

**Comment by tavrez** [comment] 2018-10-23 12:07
Rename .babelrc to something else, then upgrade and rename it back after upgrade

**Comment by tavrez** [comment] 2018-10-23 12:13
Duplicate of #21241

**Comment by kelset** [comment] 2018-12-17 12:22
Closing as duplicate.

**Closed by kelset** 2018-12-17 12:22 UTC
