### ISSUE TITLE
Android: when i using `borderRadius` and `borderLeftWidth` together, the border has no effect

### ISSUE THREAD

**Issue by zhuxindaba** [facebook/react-native#9759] opened 2016-09-06 08:50 UTC
```
    borderRadius: 3,
    width: 100,
    height: 50,
    borderLeftWidth: 3,
    borderColor: 'red',
    backgroundColor: 'tan'
```

**Comment by kulmajaba** [comment] 2016-09-06 09:08
Duplicate of #8236

**Comment by charpeni** [comment] 2016-11-14 01:20
@facebook-github-bot label Icebox

**Comment by charpeni** [comment] 2016-11-14 01:20
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-when-i-using-borderradius-and-borderleftwidth-together-the-border-has-no-effect

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment] 2016-11-14 01:20
@facebook-github-bot close

**Comment by bunnyboy1** [comment] 2016-11-14 01:24
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (70/60 (116%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:43141)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1c660U-000NdN-8B
	for bunny@thumbmunkeys.com; Mon, 14 Nov 2016 01:24:23 +0000
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196] helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1c660S-0004ZW-Q9
	for bunny@thumbmunkeys.com; Sun, 13 Nov 2016 18:24:21 -0700
Date: Sun, 13 Nov 2016 17:24:20 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1479086660;
	bh=2Sed1g6nLn0QJX8kqpxmPV+l4LehD4MRdAiO57TjsGQ=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=gleqQxh2DIcQWVSkSNOgXPQZuqOA2vM3N4seO1x33ZnLGkrIB1Hga4jXbweZMZoBU
	 9PjQTdmcjhM4IFBVUsBmZZFEWd92nXaQBbAQidMQmkRYOnxhTgCaIJBOTeH3g79+XC
	 eScBBW4fHPZbJW7ZeclUjUT6byEO89pfGc4rkprA=

**Closed** 2016-11-14 01:23 UTC
Labels: Icebox, Ran Commands
