### ISSUE TITLE
[Android] Multiple app instances on first run

### ISSUE THREAD

**Issue by selcute** [facebook/react-native#12562] opened 2017-02-24 12:54 UTC
Hi. I've just experienced weird thing using react native. When I run command react-native run-android (can't test on iOS) app runs ok, when I press Home button and run it again using app icon, app creates second instance, and doing it again creates +1 instance. 
After killing this first-run app makes the problem disappear - next run and doing same thing makes the app back to its instance. 
So first run = multiple instances, then leaving (back press (times number of instances)) or killing from recent tasks and everything is fine.

I've tested it on empty app created with react-native init, and the problem remains - I've just added componentDidMount and componentWillUnmount and it mounts multiple times without unmounting. I've tested it with realese apk file and same there - first app run - multiple instances (after running multiple instances pressing back doesn't close app, just close one instance and show another), then all ok. Tried both on emulator and physical device. RN41

Is it a bug or am I doing something wrong? Thanks in advance.

**Comment by hramos** [comment] 2017-02-24 17:37
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-02-24 17:37 UTC

**Comment by zxyah** [comment] 2017-03-20 12:40
@selcute @hramos 

i have got the same isuse 
and i log Activity's life recycle
the log is:
`
03-20 20:19:05.871 8053-8053/? E/com.nongfenqi.app.android.thrall.MainActivity: ,onCreate:null
03-20 20:19:05.871 8053-8053/? E/com.nongfenqi.app.android.thrall.MainActivity: ,onResume:com.nongfenqi.app.android.thrall.MainActivity@a36c5db
03-20 20:19:29.571 8053-8053/? E/com.nongfenqi.app.android.thrall.MainActivity: ,onPause:com.nongfenqi.app.android.thrall.MainActivity@a36c5db
03-20 20:19:45.151 8053-8053/? E/com.nongfenqi.app.android.thrall.MainActivity: ,onCreate:null
03-20 20:19:45.151 8053-8053/? E/com.nongfenqi.app.android.thrall.MainActivity: ,onResume:com.nongfenqi.app.android.thrall.MainActivity@cb9fdca
03-20 20:21:03.081 8053-8053/? E/com.nongfenqi.app.android.thrall.MainActivity: ,onPause:com.nongfenqi.app.android.thrall.MainActivity@cb9fdca


03-20 20:24:24.621 8936-8936/? E/com.nongfenqi.app.android.thrall.MainActivity: ,onCreate:null
03-20 20:24:24.631 8936-8936/? E/com.nongfenqi.app.android.thrall.MainActivity: ,onResume:com.nongfenqi.app.android.thrall.MainActivity@70d85f4
03-20 20:24:30.361 8936-8936/? E/com.nongfenqi.app.android.thrall.MainActivity: ,onPause:com.nongfenqi.app.android.thrall.MainActivity@70d85f4
03-20 20:24:42.361 8936-8936/? E/com.nongfenqi.app.android.thrall.MainActivity: ,onResume:com.nongfenqi.app.android.thrall.MainActivity@70d85f4
`

scene is:
after i installed the app,runing it, then press home button, open other app, then back to my app
it happend and create two instance

but when i killed my app,open it again ,do the same thing again, it no happen
this happend only at first times!!!

my react-native version is: 0.42.2
my test phone is : samsung galaxy on7(sm-g6100) android version is:6.0.1
and huawei p9(EVA-AL10) android version is: 7.0

**Comment by ravirajn22** [comment] 2017-10-07 07:28
Why is this issue closed, I do have the same problem in android with RN - 0.43.0-rc.4.
Any solution would be greatly helpful.

**Comment by radubatori** [comment] 2017-10-10 12:22
My solution to this was to set ```android:launchMode="singleTop"``` on the main activity in `AndroidManifest.xml`. More info [here](https://developer.android.com/guide/topics/manifest/activity-element.html#lmode).

I do not know if there are any side-effects though.

**Comment by hramos** [comment] 2017-10-10 17:11
I provided a reason for closing earlier in the thread. You can open a new issue if you're encountering this.
