### ISSUE TITLE
Build Failed with an exception. A Problem occurred configuring project ':app'. java.lang.NullPointerException.

### ISSUE THREAD

**Issue by AshokICreate** [facebook/react-native#12955] opened 2017-03-15 17:11 UTC
I created react-native project but when i run `react-native run-android` on my windows i am getting below error(please find screenshots).

```
Build Failed with an exception. 

A Problem occurred configuring project ':app'. 
>java.lang.NullPointerExceptio
```

<img width="647" alt="screen shot 2017-03-15 at 9 57 40 pm" src="https://cloud.githubusercontent.com/assets/7522708/23961271/6f363dbe-09d0-11e7-99b1-08e20f6a3028.png">
<img width="644" alt="screen shot 2017-03-15 at 9 57 27 pm" src="https://cloud.githubusercontent.com/assets/7522708/23961270/6f34ad00-09d0-11e7-85dc-e46ad2c7e8a5.png">

**Comment by hramos** [comment] 2017-03-15 17:47
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-03-15 17:47 UTC
