### ISSUE TITLE
Issue replacing Text's fontFamily while state changes..

### ISSUE THREAD

**Issue by premrajt** [facebook/react-native#22644] opened 2018-12-13 23:28 UTC
- [*] Review the documentation: https://facebook.github.io/react-native
  - [*] Search for existing issues: https://github.com/facebook/react-native/issues
  - [*] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      Memory: 126.22 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.0, 28.0.2, 28.0.3
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.57.8 => 0.57.8
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

## Description
Hi.. 

I am reporting an issue concerning TextInput in **Android** where fontFamily not changing on state changes.. 

Scenario : 
- on Initial component load i am using normal fontFamily (using state) to display place holder. **(Working Fine)**
- When enter value in textField then fontFamily state should change & display Bold text. **(Working Fine)**
- Again if I remove values from the textfield & if the text field value is empty then the state should update to normal fontFamily **(Not Working - i can see state is updated but view is not changing)**
- Again enter value in the textfield It should show bold fontFamily but it showing the unknown fontFamily

**When inspecting the changes State and Style are changing perfectly.. Not sure the problem in the view**

**Initial Load :** 
![screen shot 2018-12-14 at 11 31 20 am](https://user-images.githubusercontent.com/44417475/49971751-62a4a480-ff94-11e8-8d64-78a13a9c06ea.png)

**if value is not empty:**
![screen shot 2018-12-14 at 11 31 31 am](https://user-images.githubusercontent.com/44417475/49971771-7c45ec00-ff94-11e8-80d7-dfc420b4031c.png)

**After Clearing the input Field:**
![screenshot_20181214-115212](https://user-images.githubusercontent.com/44417475/49972999-40148a80-ff98-11e8-871c-d93b26de2eac.png)

**Note** : However in **IOS** all these things working fine.

```
Font Family used:  "Montserrat-ExtraBold",  "Montserrat-Medium";
```

## Reproducible Demo
```
https://snack.expo.io/@premdev077/aW5wdX
https://snack.expo.io/HkCg9wexE (Font is not loaded)
```

**Comment by roadev** [comment] 2018-12-17 20:18
I can't reproduce your issue, I got this:

![screenshot_2018-12-17-14-48-55](https://user-images.githubusercontent.com/4525107/50113104-00a3a380-020f-11e9-85ff-2437bdb58aef.png)

**Comment by premrajt** [comment] 2019-01-07 19:38
> I can't reproduce your issue, I got this:
> 
> ![screenshot_2018-12-17-14-48-55](https://user-images.githubusercontent.com/4525107/50113104-00a3a380-020f-11e9-85ff-2437bdb58aef.png)

**Comment by dulmandakh** [comment] 2019-03-19 12:59
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗

**Closed by dulmandakh** 2019-03-19 12:59 UTC
Labels: Component: Text, Type: Bug Report

**Comment by dulmandakh** [comment] 2019-03-19 13:01
please use underscores in font file names, and it should work.
