### ISSUE TITLE
In horizontal scrollview text input keyboard scrolls the view horizontally

### ISSUE THREAD

**Issue by yasicmd** [facebook/react-native#12043] opened 2017-01-23 17:51 UTC
When I put a set of text input fields as a matrix like structure( table ) inside a Horizontal scroll view the view scrolls sidewise which is not necessary. 

I hope you guys check this issue.

Thanks.

**Comment by ura1a** [comment] 2017-05-19 20:45
Have you been able to find a work around? We are facing the same issue.

**Comment by ura1a** [comment] 2017-05-19 21:20
our use case was fixed by setting ScrollView's `contentContainerStyle={{flex: 1}}`

**Comment by hramos** [comment] 2017-07-26 05:45
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Closed by hramos** 2017-07-26 05:45 UTC
Labels: Icebox
