### ISSUE TITLE
When and How the react-native update the shadowNode( or a view )

### ISSUE THREAD

**Issue by SinLucifer** [facebook/react-native#15616] opened 2017-08-23 08:17 UTC
In my code, ReactTextShadowNode will be added into PendingList when this node fails in `getTypeFace()` (get font family) after the `FontFamily` was downloaded, how could I refresh the node to make it work properly.

Actually, the node will update automatically if I want to use `shadownode.markUpdate()` and plz tell me why.

There might be two possibilities:

a) The ui_thread check the nodes periodically and refresh them when it finds the nodes are marked to update/dirty.

b) Something else needs to update its view and find other nodes are marked to update/dirty and refresh them.

Correct me if I am wrong.

**Comment by hramos** [comment] 2017-08-23 19:18
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-08-23 19:18 UTC
