### ISSUE TITLE
Java Exception and Error 500 on android-run command

### ISSUE THREAD

**Issue by stephane-r** [facebook/react-native#23346] opened 2019-02-08 13:46 UTC
Hi community !

## 🐛 Bug Report (?)
On a very recent react-native project, i've an `Java exception` that (apparently) create an classic `error 500 type InternalError` with metro bundler.

This error is with `android-run`

![image](https://user-images.githubusercontent.com/4712791/52481815-e7d0c200-2baf-11e9-8b55-1cc5cf916ec5.png)

With classic `npm start`, the error is other : 

```
Loading dependency graph...(node:1363) UnhandledPromiseRejectionWarning: Error: jest-haste-map: @providesModule naming collision:
  Duplicate module name: react-animated
  Paths: /app/.cache/yarn/v4/npm-react-native-0.57.8-1a840fbe144cd3902cc14313a783ce28efc48cb9/node_modules/react-native/Libraries/Animated/release/package.json collides with /app/node_modules/react-native/Libraries/Animated/release/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at setModule (/app/node_modules/metro/node_modules/jest-haste-map/build/index.js:462:17)
    at workerReply (/app/node_modules/metro/node_modules/jest-haste-map/build/index.js:512:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1363) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1363) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1363) UnhandledPromiseRejectionWarning: Error: jest-haste-map: @providesModule naming collision:
  Duplicate module name: react-animated
  Paths: /app/.cache/yarn/v4/npm-react-native-0.57.8-1a840fbe144cd3902cc14313a783ce28efc48cb9/node_modules/react-native/Libraries/Animated/release/package.json collides with /app/node_modules/react-native/Libraries/Animated/release/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at setModule (/app/node_modules/metro/node_modules/jest-haste-map/build/index.js:462:17)
    at workerReply (/app/node_modules/metro/node_modules/jest-haste-map/build/index.js:512:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1363) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

## Environment
From Docker container : 

```
  React Native Environment Info:
    System:
      OS: Linux 4.15 Debian GNU/Linux 9 (stretch) 9 (stretch)
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 6.18 GB / 15.37 GB
      Shell: 4.4.12 - /bin/bash
    Binaries:
      Node: 10.15.1 - /usr/bin/node
      Yarn: 1.13.0 - /usr/bin/yarn
      npm: 6.4.1 - /usr/bin/npm
    SDKs:
      Android SDK:
        API Levels: 26, 27
        Build Tools: 27.0.3
```

Has anyone ever had the problem ?

Thank you community !

**Comment by kelset** [comment] 2019-03-20 10:50
👋 there - sorry for the late reply (as you can see there are a lot of open issues! 😅)

So, by looking at the error message you can see that it says

`@providesModule naming collision:
  Duplicate module name: react-animated
`

What this implies is that you are having `react-animated` defined twice in your codebase. Maybe you added a new package that installed a different version? 🤔
One way you can double check that is by running `yarn why react-animated`.

Because it doesn't seem to be related to RN, I'm going to close this - but feel free to comment further and lmk if that helped, or even provide a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). And if it turns out it's actually caused by RN we can investigate it further 🤗

**Closed by kelset** 2019-03-20 10:50 UTC
Labels: Platform: Android, Platform: Linux, Type: Bug Report
