### ISSUE TITLE
Different String.startsWith behaviour on Android vs iOS

### ISSUE THREAD

**Issue by jdmunro** [facebook/react-native#11370] opened 2016-12-08 13:14 UTC
### Description

I'm using the ```startsWith``` method on JavaScript strings to compare some values. Specifically the string contains emoji characters, but not at the beginning of the string.

On iOS:

```
'Fish and Chips 🐟🍟'.startsWith('F') // true
```

The exact same code on Android:

```
'Fish and Chips 🐟🍟'.startsWith('F') // false
```

This may not be an issue of React Native but the underlying JS implementation - just a guess.

### Reproduction

Here's a reproduction of the issue: https://rnplay.org/apps/yKn2qA

If you delete the emoji characters from the string the bug goes away. 

### Additional Information

* React Native version: v0.33 to v0.39
* Platform: Android

**Comment by MatthewAwesome** [comment] 2017-04-08 00:13
Issue persists in RN version 42, and I get it even with usual characters :( More of annoyance than anything, as String.indexOf('subString') == 0 as suffices as a workaround.

**Comment by blaues0cke** [comment] 2017-05-31 08:54
Can confirm that this issue exists in RN 42, too. Also have no emojis (but the text is encoded to support emojis). In my case this occurs in a regular `JSON` response.

![rn-fail](https://cloud.githubusercontent.com/assets/5159398/26623820/3fc3107e-45ef-11e7-806b-1c7c3e9c85b5.png)

**Comment by zhuyifan2013** [comment] 2017-06-05 14:05
Still exists in RN 44

**Comment by ide** [comment] 2017-06-05 16:24
This issue exists because iOS uses many different versions of JavaScriptCore (a different version of iOS 8, 9, 10, 11) and RN Android uses its own JSC version. So there will *always* be some differences between different platforms until JSC completely stabilizes (maybe never, since JS changes each year).

To work around this you could write a polyfill or your own startsWith function instead.

**Comment by levsero** [comment] 2017-08-03 14:38
@ide `String.startsWith` is already polyfilled in rn so I believe it should work regardless of the platform - https://github.com/facebook/react-native/blob/master/Libraries/polyfills/String.prototype.es6.js#L20

**Comment by artdent** [comment] 2017-08-03 14:45
As you can see, the polyfill is only installed if the native version does not exist.

In this case, either the JSC implementation on Android should be fixed or the polyfill should be uninstalled unconditionally. It's disconcerting to encounter bugs in the JS standard library.

**Comment by jlangr** [comment] 2017-08-25 17:50
In my case, the following expression returns false:
    if (url.toLowerCase().startsWith('this://'))
... when no debugger is attached, and when url (loaded from a GET request) has the value 'this://44'. The byte codes of all the chars match, too.
When a debugger is attached, the expression returns true.

If I explicitly set String.prototype.startsWith to the version defined in the polyfill source-- https://github.com/facebook/react-native/blob/master/Libraries/polyfills/String.prototype.es6.js#L20 -- the expression returns true when expected. (The polyfill also matches the source I can view from my browser when attached to the debugger.)

(I'd like to see the source used for startsWith when not attached to a debugger, but calling toString() against the function just tells me that it's picking up native code--same result as when the debugger is attached. Is there another technique?)

Thanks MatthewAwesome for the (successful) workaround tip.

**Comment by ide** [comment] 2017-08-25 18:00
The debugger has different behavior because it runs on a different computer and on a different VM. Currently I really recommend that you use it only to debug specific issues rather than the way you develop.

This startsWith issue may get fixed in a few months if we are able to upgrade JSC. There is no real ETA though and if this issue is pressing for you I recommend you use your own String polyfill.

**Comment by jlangr** [comment] 2017-08-25 18:17
Thanks for the quick response ide!

I get the bit about the debugger, thanks. The curiosity I have: (When I was not attached to the debugger,) I substituted the RN source as above, supposedly the polyfill used, and things worked just fine. So without this substitution, when startsWith does not behave correctly, some other source must be getting used--is there an easy way to know where that's coming from?

**Comment by ide** [comment] 2017-08-25 18:31
You could print `''.startsWith.toString()` to see its source and then grep for that in node_modules.

**Comment by jlangr** [comment] 2017-08-25 18:53
Thanks ide. Note my earlier comment: It returns "function startsWith() {  [native code] }"

**Comment by jlangr** [comment] 2017-08-25 19:13
Unfortunately it just tells me it's [native code]. In node_modules it looks like there are at least a few definitions of String.prototype.startsWith.

**Comment by ide** [comment] 2017-08-25 21:53
That means it's using the native startsWith implementation then.

**Comment by artdent** [comment] 2017-10-24 22:21
This issue has not been fixed. In this case, two months of inactivity just means that there's nothing more to describe about the bug. Please keep it open.

**Comment by jdmunro** [comment] 2017-10-25 08:37
I'd forgotten all about this issue but it actually still impacts my app. Can add a temporary work around to my code, but it looks like there are 2 longer term solutions for RN:

1. Update to more modern version of JSC as @ide mentioned
2. Always polyfill `startsWith`

Is there any reason not to do 2. as this seems to be a legitimate bug potentially affecting any app that uses `startsWith` on Android?

**Comment by artdent** [comment] 2017-12-24 19:26
Please keep it open.

> This issue has not been fixed. In this case, two months of inactivity just means that there's nothing more to describe about the bug.

**Comment by jdmunro** [comment] 2018-02-23 09:42
Please keep this open 👍

**Closed** 2018-02-24 03:27 UTC
Labels: Ran Commands

**Comment by blaues0cke** [comment] 2018-02-27 19:28
Cannot reproduce this in v0.53.0 using the Android simulator, tested on:

- Nexus_6P_API_23(AVD) - 6.0
- Nexus_4_API_22(AVD) - 5.1.1

**Comment by ziyafenn** [comment] 2018-07-15 11:29
`react-native": "^0.50.4` bug is still there.

**Comment by ziyafenn** [comment] 2018-07-15 13:46
Using v0.55.4 and problem still exist in Android version.

**Comment by patrickkempff** [comment] 2018-07-15 13:50
Thank you @ziyafenn. Can you verify if the issue also exists if you use the JavaScriptCode from https://github.com/react-community/jsc-android-buildscripts?

**Comment by hey99xx** [comment] 2018-10-03 07:45
I tried "this://44" thing mentioned above but couldn't get incorrect results with that. I could only see incorrect values when emojis are included. Also `String.prototype.endsWith()` seems broken symmetrically.

Rather than checking jsc-android-buildscripts that is not production-ready yet, I'd be more curious to know if this issue happens on iOS 8/9 devices or not, but I don't have any devices to test. If it does not happen this bug might also mean FB's android-jsc is truly incompatible with standard iOS JSC runtimes.

**Comment by ziyafenn** [comment] 2018-12-01 16:35
Hi @patrickkempff. Sorry for a VERY late answer. I checked it with `jsc-android` and there was no issue with it.

**Comment by ahmetabdi** [comment] 2018-12-06 14:51
Same issue with latest RN

**Comment by ahmetabdi** [comment] 2019-01-22 08:56
@yernandus An alternative that works on both is:

`url.indexOf('http') === 0`

**Comment by hey99xx** [comment] 2019-01-23 19:48
RN made the JSC upgrade in master branch, expected release is 0.59 https://github.com/facebook/react-native/issues/19737#issuecomment-453690580 This should likely be fixed with that.
