### ISSUE TITLE
Cannot find entry file index.android.js in any of the roots

### ISSUE THREAD

**Issue by rushabhmakwana** [facebook/react-native#14386] opened 2017-06-08 07:32 UTC
![screen shot 2017-06-08 at 1 05 32 pm](https://user-images.githubusercontent.com/24916127/26917125-a4e52422-4c4a-11e7-8e72-c97b8616a6c2.png)

**Comment by coma** [comment] 2017-06-08 07:43
I'm getting this too on a freshly created app (react-native init foo) using react-native-cli 2.0.1 on OSx.

**Comment by rushabhmakwana** [comment] 2017-06-08 07:48
@coma Same here.

**Comment by coma** [comment] 2017-06-08 07:49
The bundling process is failing somehow...

**Comment by rushabhmakwana** [comment] 2017-06-08 07:58
Yup..waiting for an expert to help here.

**Comment by DemisBand** [comment] 2017-06-08 08:02
Same problem since upgrade react native 0.44 to 0.45

**Comment by engladgut** [comment] 2017-06-08 08:16
`react-native-git-upgrade 0.44.0`

I know this not the answer for 0.45 but this solved all my problem like yours or this one -> [14209](https://github.com/facebook/react-native/issues/14209)

I think I will stay at 0.44.0 for now. 0.44.1~3? Didn't work for me.

**Comment by coma** [comment] 2017-06-08 08:29
Yupe, after initing a new app, just downgraded to react-native@0.44.2 and it's working now...

**Comment by aramiscubillo** [comment] 2017-06-08 08:41
Yeap, downgraded to 0.44.0 and works now. In cause somebody doesn't know how to downgrade react, you need to install: https://github.com/facebook/react-native/tree/master/react-native-git-upgrade

**Comment by ngtranthanhtoan** [comment] 2017-06-08 10:24
Me too get the same. Hope someone help

**Comment by GetSource1234** [comment] 2017-06-08 10:55
Got the same issue.

**Comment by rvpyrv** [comment] 2017-06-08 11:38
Same issue.

**Comment by juhasuni** [comment] 2017-06-08 12:18
In my case `react-native start --reset-cache` was the key for resolving the issue.

After that I had to do some other changes to codebase. I had `import ... from 'immutable';` statement, which I removed since I don't need `immutable` and it was not in my `package.json`.

I was also using `id` prop with some views, which I needed to rename, since Android was throwing me an error with registering a root view with explicit id prop or something.

Hope this helps someone.

**Comment by gdboling** [comment] 2017-06-08 12:53
Also having this problem. Downgrading works, as suggested. But creating brand new app with latest react-native-cli gives the "Cannot find entry file..." error.

**Comment by Benouzef** [comment] 2017-06-08 13:01
Same problem since upgrade react native 0.44 to 0.45

**Comment by florinpop17** [comment] 2017-06-08 13:17
+1

**Comment by fbyn** [comment] 2017-06-08 13:23
Same problem with 0.45

**Comment by cgoudouris** [comment] 2017-06-08 14:44
+1

**Comment by ggcaponetto** [comment] 2017-06-08 14:52
<code>react-native start --reset-cache</code> seems to fix only the next start. Killing the packager process and running <code>react-native run-android</code> leads to the same problem, again.

**Comment by pbailey** [comment] 2017-06-08 14:54
+1

**Comment by ggcaponetto** [comment] 2017-06-08 15:22
0.45 seems to have a whole different project structure and entry point. The docs just got updated btw. The new entry point seems to be App.js, placed on the root.

**Comment by gdboling** [comment] 2017-06-08 16:05
@ggcaponetto what? I don't see a new project structure. Are you saying that react-native-cli isn't generating the appropriate project structure and that could be the issue?

**Comment by hramos** [comment] 2017-06-08 16:11
@ggcaponetto that is only the case when a new project is created using `create-react-native-app`. The behavior of `react-native init` should remain the same.

**Comment by ggcaponetto** [comment] 2017-06-08 16:12
You are right, sorry to have brought confusion.

**Comment by sonikro** [comment] 2017-06-08 17:00
When running **react-native run-android** on React-native 0.45, the packager is looking for JS files in \Project\node_modules\react-native\packager. That's why It's not finding the index.android.js file.

If I use react-native start, the packager will start looking for JS files in the correct place (\Project).

**Comment by samartha-kar23** [comment] 2017-06-08 18:36
The fix which seem to work well is upgrading your project to the current version **0.45**.
You should consider using the new upgrade tool based on Git. It makes upgrades easier by resolving most conflicts automatically.
To use it:
- Go back to the old version of React Native(If you haven't tried upgrading likewise )
-Go to your project folder with old version of React Native
- Run "**npm install -g react-native-git-upgrade**"
- Run "**react-native-git-upgrade**"
See **https://facebook.github.io/react-native/docs/upgrading.html**

**PS**- If you have installed **additional packages** like react-navigator from npm you need to **reinstall** them again.
now as @sonikro mentioned use **react-native start** and **reload**.
- If you are getting Application not registered error, you need to kill the old packager instance by:
**react-native start --reset-cache**

**Comment by gdboling** [comment] 2017-06-08 18:50
@samartha-kar23 So I need to upgrade a project I just created from scratch? That's not a fix. A brand new `react-native init App` should work.

**Comment by AVBelousov** [comment] 2017-06-08 19:07
In first console window, from project folder run:
`npm start --root .`
(run packager manually with right root)

In second console window, from project folder run:
`react-native run-android`

**Comment by hramos** [comment] 2017-06-08 19:37
Closing as duplicate of #14246.

**Closed by hramos** 2017-06-08 19:37 UTC

**Comment by rushabhmakwana** [comment] 2017-06-09 06:25
"react-native init YourAppName" creates an application with the react native version 0.45.0 and that creates the problem.
So I create new app with the specified version of react-native via "react-native init --version="version_number" MyFirstApp" command i.e "react-native init --version="0.44.2" MyFirstApp" and that solves my problem.
