### ISSUE TITLE
Print: Entry, ":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by omi10859** [facebook/react-native#20596] opened 2018-08-09 08:19 UTC
## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
      Memory: 2.51 GB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.8.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.2.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.4.1 => 16.4.2 
      react-native: ^0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-linear-gradient: 2.4.0

## Description
App is working fine with android while running  react-native run-ios is giving error  
Scanning folders for symlinks in /Users/omkaryadav/Documents/project/react/july17/node_modules (35ms)
Found Xcode workspace weatherApp.xcworkspace
Building using "xcodebuild -workspace weatherApp.xcworkspace -configuration Debug -scheme weatherApp -destination id=7DF3F4ED-1395-4452-B409-6AE1B9263D6F -derivedDataPath build"
User defaults from command line:

    IDEDerivedDataPathOverride = /Users/omkaryadav/Documents/project/react/july17/ios/build

2018-08-09 13:45:17.205 xcodebuild[55741:1825313] Error Domain=NSCocoaErrorDomain Code=3840 "Unexpected character / at line 1" UserInfo={NSDebugDescription=Unexpected character / at line 1, kCFPropertyListOldStyleParsingError=Error Domain=NSCocoaErrorDomain Code=3840 "Expected terminating '}' for dictionary at line 42" UserInfo={NSDebugDescription=Expected terminating '}' for dictionary at line 42}}

2018-08-09 13:45:17.207 xcodebuild[55741:1825313] [MT] IDEFileReferenceDebug: [Load] <IDEFileReference, 0x7fe9ae022ee0: group:weatherApp.xcodeproj> Failed to load container at path: /Users/omkaryadav/Documents/project/react/july17/ios/weatherApp.xcodeproj, Error: Error Domain=Xcode3ProjectErrorDomain Code=2 "Project /Users/omkaryadav/Documents/project/react/july17/ios/weatherApp.xcodeproj cannot be opened because the project file cannot be parsed." UserInfo={NSLocalizedDescription=Project /Users/omkaryadav/Documents/project/react/july17/ios/weatherApp.xcodeproj cannot be opened because the project file cannot be parsed.}

--- xcodebuild: WARNING: Unable to open project file '/Users/omkaryadav/Documents/project/react/july17/ios/weatherApp.xcodeproj' in workspace 'weatherApp.xcworkspace'.

xcodebuild: error: The workspace named "weatherApp" does not contain a scheme named "weatherApp". The "-list" option can be used to find the names of the schemes in the workspace.

Installing build/Build/Products/Debug-iphonesimulator/weatherApp.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/weatherApp.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by omi10859** [comment] 2018-08-09 08:20
I'm losing faith in react-native now 
error that keep coming randomly :)

**Comment by Parvinderjit** [comment] 2018-08-09 17:01
Getting same issue every time even when creating new project

**Comment by vdlindenmark** [comment] 2018-08-09 22:08
Just build your app before running `react-native run-ios`. And please use [Markdowns](https://guides.github.com/features/mastering-markdown/) when you past some errors or code.

**Comment by omi10859** [comment] 2018-08-13 16:48
Yes there are lot of question on the internet and none of them solves my problem.
I'm facing this problem from a while and not able to solve it so I thought opening new issue would be able to attract focus of some people who can possibly help me out

**Comment by vdlindenmark** [comment] 2018-08-13 17:11
Could you tell us what you have already tried? Without that, we basically just suggest to do that what already is suggested on the internet.

**Comment by Parvinderjit** [comment] 2018-08-14 17:44
Every time creating a new project gives me the following:


The following commands produced analyzer issues:
	Analyze Base/RCTModuleMethod.mm normal x86_64
(1 command with analyzer issues)

Installing build/Build/Products/Debug-iphonesimulator/calculator.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/calculator.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by abdullahtariq1171** [comment] 2018-08-20 07:44
Facing same issue, have tried multiple solutions 



> ** BUILD SUCCEEDED **

> The following commands produced analyzer issues:
> 	Analyze Base/RCTModuleMethod.mm normal x86_64
> (1 command with analyzer issues)
> 
> Installing build/Build/Products/Debug-iphonesimulator/abc.app
> An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
> Failed to install the requested application
> An application bundle was not found at the provided path.
> Provide a valid path to the desired application bundle.
> Print: Entry, ":CFBundleIdentifier", Does Not Exist
> 
> Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/abc.app/Info.plist
> Print: Entry, ":CFBundleIdentifier", Does Not Exist



**Solution Tried: **

https://github.com/facebook/react-native/issues/7308#issuecomment-216317248 

https://github.com/facebook/react-native/issues/7308#issuecomment-219597774

https://github.com/facebook/react-native/issues/7308#issuecomment-230198331

**Comment by tolulopep** [comment] 2018-08-26 15:06
Facing the same issue

**Comment by omi10859** [comment] 2018-08-26 15:50
It looks like react native developers can't solve this issue and I should start learning flutter 🔢

**Comment by prabhu0023** [comment] 2018-08-31 12:31
Facing the same issue, can anyone help on it.

**Comment by woohoou** [comment] 2018-08-31 14:33
Facing the same issue

**Comment by woohoou** [comment] 2018-08-31 18:48
The first answer works for me https://stackoverflow.com/questions/37461703/print-entry-cfbundleidentifier-does-not-exist

**Comment by emaddoma** [comment] 2018-09-14 19:12
For those of you who are starting an app from scratch and do not want to use Expo, we had success getting around this error by starting the app with Expo and then ejecting.

**Comment by robmoorman** [comment] 2018-09-21 01:14
Running from xcode and choose another older iPhone works for me, e.g. `react-native run-ios --simulator="iPhone 8`

**Comment by hramos** [comment] 2018-09-24 22:45
Reiterating what Marc said in #14423 at the start of the year. This error plainly indicates the project failed to compile or link. You'll need to look further up in your output for a hint of the root cause. I've opened #21303 in order to help people who run into this issue, and will lock this thread to avoid causing more confusion.

Duplicate of #21303

**Closed by hramos** 2018-09-24 22:45 UTC
Labels: :large_blue_diamond:iOS
