### ISSUE TITLE
case sensitivity ignored when sending custom headers through fetch  request

### ISSUE THREAD

**Issue by ismdcf** [facebook/react-native#9561] opened 2016-08-24 05:06 UTC
I am using react native 0.23.1 (also tried it using 29) on Mac. during a fetch request react ios, when I send a custom header (eg 'Api-Version' : '0.1' ) the server receives it all in lower case ('api-version':'0.1').The standard of writing a header is using camel case, I don't have control over the server code so the request fails as it is expecting the headers in camel case.When checking the server log found out that all the other non custom headers come as camel case while only the custom headers come as all lowercase.

I tried using different http clients such as frisbee and axios still it was the same. 

Doing the same request using a chrome console was successful.  

Following is my fetch code 

      fetch(Properties.uris.base + Properties.uris.getBusinessDetails.replace("{businessId}",   Properties.appId).replace("{timezone",this.getTimeZone()), {
            method: "GET",
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json',
                'User-Agent': DeviceInfo.getUserAgent(),
                'X-UserId':userDetailsJson.username,
                'X-BusinessId':Properties.appId,
                'X-App-Version': DeviceInfo.getVersion(),
                'Api-Version': Properties.fetchHeaderInformation.apiVersion,
            }})
            .then((response) => response.json())

**Comment by ryankask** [comment] 2016-08-24 07:42
This isn't a React Native issue because the HTTP spec says that header fields are case insensitive. You should probably file a bug with the API provider.

Note that RN uses the underlying iOS networking libraries. Check out this note in the `NSURLRequest` docs: "The name of the header field to set. In keeping with the HTTP RFC, HTTP header field names are case-insensitive." (https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSMutableURLRequest_Class/index.html#//apple_ref/occ/instm/NSMutableURLRequest/setValue:forHTTPHeaderField:)

**Comment by ryankask** [comment] 2016-08-24 07:44
@facebook-github-bot expected

**Comment by facebook-github-bot-0** [comment] 2016-08-24 07:45
The comment above tells me this is expected behavior. Closing this as we'd like to use the GitHub issue tracker for bugs. If you'd like to change how this feature works please post a feature request on [Product Pains](https://productpains.com/product/react-native/) so that other people can vote on it.

**Closed by facebook-github-bot-0** 2016-08-24 07:45 UTC
Labels: Ran Commands

**Comment by ryankask** [comment] 2016-08-24 07:49
I did some searching and can see that there was a commit that addressed this: https://github.com/facebook/react-native/commit/7069e4cd3f1228e0508988ecdee2afb3899aedfc

I thought the iOS was doing that but that looks like it isn't the case although the reason is the same.

You could probably monkeypatch that function if necessary.

**Comment by ismdcf** [comment] 2016-08-24 08:47
@ryankask thanks for the heads up. did the patch works like a charm (also had to patch the Fetch module in Network folder for it to work ) 👍
