### ISSUE TITLE
borderStyle: 'dashed' / 'dotted' does not work

### ISSUE THREAD

**Issue by Liqiankun** [facebook/react-native#22256] opened 2018-11-13 10:14 UTC
## Environment
```
npm: 6.1.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728
      react-native: 0.57.3 => 0.57.3
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

## Description
borderStyle: 'dashed' / 'dotted' does not work

**Comment by bartolkaruza** [comment] 2018-11-14 02:29
@kelset duplicate of https://github.com/facebook/react-native/issues/22227 or https://github.com/facebook/react-native/issues/22226

**Comment by kelset** [comment] 2018-11-14 09:07
Thanks, closing

**Closed by kelset** 2018-11-14 09:07 UTC
Labels: ❔Needs More Information, 📋No Environment Info, 📋No Repro Steps
