### ISSUE TITLE
Simulator waits for processing a request using fetch until a click is made on the screen

### ISSUE THREAD

**Issue by alfonsoperez** [facebook/react-native#2603] opened 2015-09-08 15:25 UTC
Hi all,

In one of my action callers of my app, where I need to call an external API (using fetch api), I have something like this.

    console.log('fetching...');

    _pendingRequests[key] = fetch(url, metadata).then(r => r.json())
                                    .then(data => { dispatch(key, data, params) })
                                    .catch(apiError);

With all the other fetches everything works fine, but there is a fetch that happens when some coordinates are updated, the callback is called, and thus this action caller is called, 

> fetching... 

is displayed in the console but **until I don't CLICK** on the simulator the promise is not resolved and so the response is not dispatched, in the device everything works as expected.

What can it be?

Thanks

**Comment by ide** [comment] 2015-09-08 17:12
Are you using the Chrome debugger? I could see that causing issues... Basically your click is causing React Native's event loop to run and I think another event loop (V8 maybe) is running without RN being aware of it.

**Comment by alfonsoperez** [comment] 2015-09-08 17:51
humm.. yes, in fact when I disable Chrome debugger now it doesn't work (ie. the request arrives to the backend but the promise is not resolved)

**Comment by brentvatne** [comment] 2015-09-09 18:50
I think we need more information about the context of this fetch call -- given that all others work fine, there is nothing specific about this that I see causing problems. Please try to post a reproducible example that we can run against! Otherwise there's not much more we can say here :smile:

**Comment by brentvatne** [comment] 2015-09-13 18:07
Closing, ping me when you have a chance to reply and I can reopen!

**Closed by brentvatne** 2015-09-13 18:07 UTC
Labels: Needs more information

**Comment by eremzeit** [comment] 2016-06-09 22:38
I'm seeing this same behavior.  It only happens when using the chrome debugger.  I'm digging in and will report back when I know more.

**Comment by eremzeit** [comment] 2016-06-10 00:38
Oh, I upgraded to 0.24.x to 0.26.x and the problem was resolved.

**Comment by duanhaowei** [comment] 2016-06-10 07:11
I also have this problem and it happen on 0.26.x , when i use code from  https://facebook.github.io/react-native/docs/sample-application-movies.html 

when i disable Chrome debug "remote debug" model , the bug is gone. 
so it seem like something wrong wiht remote debug

**Comment by martin-cech** [comment] 2016-09-19 19:05
Hi, I'm having exactly the same issue in 0.33 after upgrade from 0.32. After disconnecting the debugger it works fine

**Comment by Victoor** [comment] 2016-09-24 13:53
Same problem as @martin-cech says... 😕

**Comment by martin-cech** [comment] 2016-09-25 14:42
Turns out it might not be relevant to version of React, I reverted to 0.32 and the problem was still there. I tried deleting node_modules folder, even completely clean git checkout but nothing worked. I think after 

    rm -rf /usr/local/lib/node_modules/npm/node_modules

the issue went away. No guarantees whether that works or why, I was just trying to clean as much as possible.

**Comment by ewendel** [comment] 2017-06-20 15:51
I'm seeing the same problem now, with RN 0.45.1 and React 16.0.0-alpha.12.

**Comment by giulianok** [comment] 2017-07-16 00:48
I'm having the same issue. When I'm debugging with Chrome, for each request, I have to click on the app (simulator) to be able to make each request. Without debugging I works fine :(

**Comment by guilhermemello** [comment] 2017-07-18 14:15
Same problem.
RN 0.46.1

**Comment by moalamin** [comment] 2017-07-26 20:47
Same here, "react-native": "0.46.4".

redditActions.js:
```
import thunk from 'redux-thunk';

export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_COMPLETE = 'FETCH_POSTS_COMPLETE';

export function fetchPosts(dispatch) {
  return (dispatch) => {
    window.fetch('https://www.reddit.com/.json')
    .then( resp => resp.json() )
    .then( data => {
      dispatch(fetchPostsComplete(data.data.children))
    })
  }
}

export function fetchPostsComplete (posts) {
    return {
      type: FETCH_POSTS_COMPLETE,
      payload: posts
    }
}
```

reducers.js:
```
import {FETCH_POSTS, FETCH_POSTS_COMPLETE} from './redditActions';

const initialState = { posts: [] }
export const redditReducer = (state=initialState, action) => {
  switch (action.type) {
    case FETCH_POSTS_COMPLETE: {
      const newState = Object.assign({}, state, {posts: action.payload})
      return newState;
    }
    default: {
      return state;
    }
  }
}
```

Reddit.js:
```
class Reddit extends Component {
  constructor(props) {
    super(props)
    console.log(this.props)
  }
  componentWillMount() {
    this.props.actions.fetchPosts()
  }
  render() {
    return (
      <View>
        <Text>Reddit</Text>
        {
          this.props.posts.map( post => <Text key={post.data.id}>{post.data.title}</Text>)
        }
      </View>
    )
  }
}

function mapStateToProps(state) {
  return {
    posts: state.posts
  }
}

function mapDispatchToProps(dispatch) {
  return { actions: bindActionCreators(redditActions, dispatch) }
}

export default connect(mapStateToProps, mapDispatchToProps)(Reddit)
```

When I reload the application, the screen on the IOS simulator is blank until I click on it, then the state seems to get updated and a render happens. Not sure if I'm handling async actions wrong, or if it's react-native (new to react and redux).
