### ISSUE TITLE
The RN app get a high allocated memory on OPPO devices.

### ISSUE THREAD

**Issue by 452MJ** [facebook/react-native#14218] opened 2017-05-27 01:48 UTC
### Description

The same RN app runs on OPPO devices and Huawei devices but have a different performance on allocated memory.

### Reproduction Steps and Sample Code

git  https://github.com/452MJ/Mtime-React-Native

cd app

npm install

react-native link

react-native start

react-native run-android

### Solution

![1](https://cloud.githubusercontent.com/assets/13673008/26516935/82d22bf6-42c1-11e7-9aa1-8dd2195a38e6.png)

![2](https://cloud.githubusercontent.com/assets/13673008/26516936/876391dc-42c1-11e7-9684-06afb56fe4c8.png)

Fix the higt memory problems.

### Additional Information

* React Native version: 0.44.0
* Platform: Android
* Development Operating System: Windows
* Dev tools: IntelliJ IDEA 2017.1.2

**Comment by hramos** [comment] 2017-05-30 18:16
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-05-30 18:16 UTC
