### ISSUE TITLE
"Warning: SceneView has a method called shouldComponentUpdate()", used with react-native-router-flux

### ISSUE THREAD

**Issue by cronos88** [facebook/react-native#14427] opened 2017-06-09 16:50 UTC
In react-native v0.45.0 when is used with react-native-router-flux v3.39.2, show the following warning in the emulator:

Warning: SceneView has a method called shouldComponentUpdate(). shouldComponentUpdate should not be used when extending React.PureComponent. Please extended React.Component if shouldComponentUpdate is used.

**Comment by hramos** [comment] 2017-06-09 17:03
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-09 17:03 UTC

**Comment by cronos88** [comment] 2017-06-09 18:30
Thanks
