### ISSUE TITLE
Error try to run app in iOS

### ISSUE THREAD

**Issue by GustavoMSevero** [facebook/react-native#20657] opened 2018-08-13 16:07 UTC
## Environment

> React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-2435M CPU @ 2.40GHz
      Memory: 1.41 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1

## Description
This error appears when i try to run ios version.

> /Users/gustavo/React-native/projetos/SmartPark/node_modules/react-native/React/../third-party/glog-0.3.4/src/base/mutex.h:105:10: fatal error: 'config.h' file not found
#include "config.h"           // to figure out pthreads support
         ^~~~~~~~~~

** BUILD FAILED **

The following build commands failed:

	CompileC /Users/gustavo/React-native/projetos/SmartPark/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/third-party.build/Objects-normal/x86_64/raw_logging.o /Users/gustavo/React-native/projetos/SmartPark/node_modules/react-native/third-party/glog-0.3.4/src/raw_logging.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/SmartPark.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/SmartPark.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

## Reproducible Demo
react-native run-ios

**Comment by GustavoMSevero** [comment] 2018-08-13 16:30
I found a solution on this link [http://tuntunir.blogspot.com/2018/02/react-native-fatal-error-configh-file.html](url)
But i will have to do this every app? kkkkk

**Comment by hramos** [comment] 2018-09-24 22:48
Reiterating what Marc said in #14423 at the start of the year. This error plainly indicates the project failed to compile or link. You'll need to look further up in your output for a hint of the root cause. I've opened #21303 in order to help people who run into this issue, and will lock this thread to avoid causing more confusion.

Duplicate of #21303

**Closed by hramos** 2018-09-24 22:48 UTC
Labels: :large_blue_diamond:iOS
