### ISSUE TITLE
0.62.1 Error: Unable to resolve module `./YellowBoxImageSource` 

### ISSUE THREAD

**Issue by khkwan0** [facebook/react-native#28519] opened 2020-04-03 20:14 UTC
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
pristine react-native init, attempted to react-native run-android, during run time got yellowbox error.  Did not occur with 0.62.0.

## React Native version:
Run `react-native info` in your terminal and copy the results here.

info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 18.09 GB / 31.95 GB
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 22, 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.3, 26.0.1, 26.0.3, 27.0.3, 28.0.3, 29.0.0, 29.0.2
      System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
  Languages:
    Python: 2.7.13 - C:\Python27\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.1 => 0.62.1
  npmGlobalPackages:
    *react-native*: Not Found
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. npx react-native init xxx
2. npx react-native run-android

## Expected Results
See the sample react native screen

**Comment by kamui545** [comment] 2020-04-04 02:12
I can confirm, here's the stack for more detail:

```
error: Error: Unable to resolve module `./YellowBoxImageSource` from `node_modules/react-native/Libraries/YellowBox/UI/YellowBoxInspectorHeader.js`: 

None of these files exist:
  * node_modules/react-native/Libraries/YellowBox/UI/YellowBoxImageSource(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * node_modules/react-native/Libraries/YellowBox/UI/YellowBoxImageSource/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (/Users/manu/Code/mtd-mobile/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/Users/manu/Code/mtd-mobile/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/manu/Code/mtd-mobile/node_modules/metro/src/node-haste/DependencyGraph.js:287:16)
    at Object.resolve (/Users/manu/Code/mtd-mobile/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at /Users/manu/Code/mtd-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:434:31
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/manu/Code/mtd-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:431:18)
    at /Users/manu/Code/mtd-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/manu/Code/mtd-mobile/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
```

**Comment by enosh94** [comment] 2020-04-04 06:58
I also experience the same since yesterday.. Nothing has changed in any file, but same code worked well day before yesterday. 

[Sat Apr 04 2020 12:15:00.350]  BUNDLE  ./index.js

error: Error: Unable to resolve module `./YellowBoxImageSource` from `node_modules\react-native\Libraries\YellowBox\UI\YellowBoxInspectorHeader.js`:

None of these files exist:
  * node_modules\react-native\Libraries\YellowBox\UI\YellowBoxImageSource(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules\react-native\Libraries\YellowBox\UI\YellowBoxImageSource\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (F:\projects\React-Native\chat-app\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (F:\projects\React-Native\chat-app\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (F:\projects\React-Native\chat-app\node_modules\metro\src\node-haste\DependencyGraph.js:287:16)
    at Object.resolve (F:\projects\React-Native\chat-app\node_modules\metro\src\lib\transformHelpers.js:267:42)
    at F:\projects\React-Native\chat-app\node_modules\metro\src\DeltaBundler\traverseDependencies.js:434:31
    at Array.map (<anonymous>)
    at resolveDependencies (F:\projects\React-Native\chat-app\node_modules\metro\src\DeltaBundler\traverseDependencies.js:431:18)
    at F:\projects\React-Native\chat-app\node_modules\metro\src\DeltaBundler\traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (F:\projects\React-Native\chat-app\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)

**Comment by vimalraj9423** [comment] 2020-04-04 10:01
yes for me also same error

**Comment by TheRakeshPurohit** [comment] 2020-04-06 08:30
same error. Caan't develop further.
solve as soon as possible.

**Comment by gdritterbu** [comment] 2020-04-06 12:46
I tried `react-native start --reset-cache`.
Afterwards I once again ran `npx react-native run-android` and it worked.

See [this ](https://stackoverflow.com/questions/40985027/unable-to-resolve-module-in-react-native-app) on stackoverflow.

**Comment by gluix20** [comment] 2020-04-06 17:48
Same issue with 0.62.1, this worked for me:
```
watchman watch-del-all
rm -rf $TMPDIR/haste-map-metro*
rm -rf $TMPDIR/metro-cache*
rm -rf node_modules
npm cache clean --force
npm install
npm start -- --reset-cache
```

**Comment by khkwan0** [comment] 2020-04-07 04:01
> I tried `react-native start --reset-cache`.
> Afterwards I once again ran `npx react-native run-android` and it worked.
> 
> See [this ](https://stackoverflow.com/questions/40985027/unable-to-resolve-module-in-react-native-app) on stackoverflow.

That worked!  Thanks!

**Comment by isuru3ranga** [comment] 2020-04-07 04:06
`npx react-native start --reset-cache` fixed the above issue for me too.

**Comment by TheRakeshPurohit** [comment] 2020-04-07 12:05
> I tried `react-native start --reset-cache`.
> Afterwards I once again ran `npx react-native run-android` and it worked.
> 
> See [this ](https://stackoverflow.com/questions/40985027/unable-to-resolve-module-in-react-native-app) on stackoverflow.

Superb. Issue Solved. Thank you so much. Close the Issue.

**Comment by TheSavior** [comment] 2020-04-08 00:48
I'm glad you were able to find a resolution for this!

**Closed by TheSavior** 2020-04-08 00:48 UTC
Labels: Issue When Upgrading

**Comment by victor200-tech** [comment] 2020-04-12 02:41
npx react-native start --reset-cache

and i got 

Command `start` unrecognized. Make sure that you have run `npm install` and that you are inside a react-native project.

**Comment by WemersonPD** [comment] 2020-07-08 23:25
> Eu tentei `react-native start --reset-cache`.
> Depois corri mais uma vez `npx react-native run-android`e funcionou.
> 
> Veja [isso](https://stackoverflow.com/questions/40985027/unable-to-resolve-module-in-react-native-app) no stackoverflow.

**Comment by thiagosteps227** [comment] 2020-07-17 18:49
That also worked for me!! Thanks!!

**Comment by Shihaburabbi** [comment] 2020-09-28 06:00
this worked 0.63.2
watchman watch-del-all
rm -rf $TMPDIR/haste-map-metro*
rm -rf $TMPDIR/metro-cache*
rm -rf node_modules
npm cache clean --force
npm install
npm start -- --reset-cache
