### ISSUE TITLE
Build Failed of newest version in IOS

### ISSUE THREAD

**Issue by vivichen123** [facebook/react-native#18650] opened 2018-04-02 06:06 UTC
- [ yes] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [ yes] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ yes] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment

Environment:
  OS: OS X El Capitan 10.11.6
  Node: 6.2.2
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 8.2.1 Build version 8C1002
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0
  react-native: 0.54.4 => 0.54.4

## Steps to Reproduce

run command “react-native init AwesomeProject” as demo, then build the project use Xcode.

## Expected Behavior

Build Successfully, the content of app.js show in the IOS simulator

## Actual Behavior

Build Failed. throw errors like below:

1. /Users/vivichen/Documents/reactnative/AwesomeProject/node_modules/react-native/React/Views/RCTFont.mm:110:39: Unknown type name 'UIFontWeight'; did you mean 'RCTFontWeight'?

2. /Users/vivichen/Documents/reactnative/AwesomeProject/node_modules/react-native/React/Views/RCTFont.mm:118:56: Unknown type name 'UIFontWeight'; did you mean 'RCTFontWeight'?

3. /Users/vivichen/Documents/reactnative/AwesomeProject/node_modules/react-native/Libraries/Text/BaseText/RCTBaseTextShadowView.m:69:54: Incompatible pointer types sending 'NSDictionary<NSAttributedString *,id> *' to parameter of type 'NSDictionary<NSString *,id> * _Nullable'

**Comment by meenunegi** [comment] 2018-04-02 09:36
I am having the same issue with ios.

**Comment by DLevai94** [comment] 2018-04-02 14:39
@vivichen123 I think this is a duplicate of my issue. https://github.com/facebook/react-native/issues/18638

**Comment by hramos** [comment] 2018-04-02 19:58
Duplicate of #18638

**Closed by hramos** 2018-04-02 19:58 UTC
Labels: :large_blue_diamond:iOS
