### ISSUE TITLE
Android：helloworld project crashed when debug by android studio

### ISSUE THREAD

**Issue by Wangzihao5325** [facebook/react-native#13696] opened 2017-04-28 09:08 UTC
ver：0.43.4
just a helloworld project will crash，after i remote JS debugging.
and android studio will console

04-28 16:39:49.897 25339-26675/com.outofmemery E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
                                                                 Process: com.outofmemery, PID: 25339
                                                                 java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Out of memory
                                                                     at java.lang.Thread.nativeCreate(Native Method)
                                                                     at java.lang.Thread.start(Thread.java:1078)
                                                                     at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:921)
                                                                     at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
                                                                     at okhttp3.ConnectionPool.put(ConnectionPool.java:135)
                                                                     at okhttp3.OkHttpClient$1.put(OkHttpClient.java:149)
                                                                     at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:188)
                                                                     at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
                                                                     at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
                                                                     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
                                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
                                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
                                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
                                                                     at okhttp3.RealCall.access$100(RealCall.java:33)
                                                                     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
                                                                     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                     at java.lang.Thread.run(Thread.java:833)
04-28 16:39:49.961 25339-26675/com.outofmemery I/Process: Sending signal. PID: 25339 SIG: 9

**Comment by hramos** [comment] 2017-04-29 11:54
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-04-29 11:54 UTC
