### ISSUE TITLE
Cannot use node module called speedtest-net

### ISSUE THREAD

**Issue by ferily7** [facebook/react-native#20717] opened 2018-08-17 16:24 UTC
## Environment
Environment:
  OS: Windows 10
  Node: 8.11.3
  Yarn: Not Found
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4907809

Packages: (wanted => installed)
  react: 16.4.1 => 16.4.1
  react-native: ^0.55.4 => 0.55.4

## Description
Hello, I am new to React Native and I'm trying to use this library/API called [speedtest.net](https://github.com/ddsol/speedtest.net) to get the upload and download speed from a server. However when I try to do `const speedTest = require('speedtest-net');` in my React Native application, I am getting the following error:

> Error: Unable to resolve module url from C:\Users\username\Documents\Project\node_modules\speedtest-net\index.js: Module url does not exist in the Haste module map

I know that there is a similar issue here on GitHub (#4968) and I tried to follow the steps, but I still get this error. I tried in install watchman but I wasn't sure what it meant by setting your PATH to where the watchman.exe is. Even so, I tried all the other steps and it didn't do anything. I tried to create a brand new project and try to use speedtest-net, but it still doesn't work. Any tips or help would be great because I really need to use this library in my app.

## Reproducible Demo
```
import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View} from 'react-native';

const instructions = Platform.select({
  ios: 'Press Cmd+R to reload,\n' + 'Cmd+D or shake for dev menu',
  android:
    'Double tap R on your keyboard to reload,\n' +
    'Shake or press menu button for dev menu',
});
const speedTest = require('speedtest-net');
//const speedTest = require('./speedtest');
const test = speedTest({maxTime: 5000});

type Props = {};
export default class App extends Component<Props> {
  constructor()  {
    super();
  }

  componentWillMount() {
    test.on('downloadspeed', speed => {
       console.log('Download speed:', speed.toFixed(2));
   });
    
    test.on('uploadspeed', speed => {
       console.log('Upload speed:',(speed * 125).toFixed(2),'KB/s');
    })
  }

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>Welcome to React Native!</Text>
        <Text style={styles.instructions}>To get started, edit App.js</Text>
        <Text style={styles.instructions}>{instructions}</Text>
      </View>
    );
  }
}
```

**Comment by ferily7** [comment] 2018-08-17 16:30
Another thing to note is that I managed to follow the steps in [this article](https://hackernoon.com/using-core-node-js-modules-in-react-native-apps-64acd4d07140) and it got rid of this error:

> Error: Unable to resolve module url from C:\Users\username\Documents\Project\node_modules\speedtest-net\index.js: Module url does not exist in the Haste module map

but now when I try to do `const test = speedTest({maxTime: 5000});`, I get another error/warning in the console:

> Possible Unhandled Promise Rejection (id: 0): TypeError: Network request failed TypeError: Network request failed at XMLHttpRequest.xhr.onerror at XMLHttpRequest.dispatchEvent at XMLHttpRequest.setReadyState at XMLHttpRequest.__didCompleteResponse at blob:http://localhost:8081/b1cfcde4-0ef7-4805-bd16-22849a1db8e3:17594:47 at RCTDeviceEventEmitter.emit at MessageQueue.__callFunction at blob:http://localhost:8081/b1cfcde4-0ef7-4805-bd16-22849a1db8e3:2156:17 at MessageQueue.__guardSafe at MessageQueue.callFunctionReturnFlushedQueue
> 
> Possible Unhandled Promise Rejection (id: 1): TypeError: One of the sources for assign has an enumerable key on the prototype chain. Are you trying to assign a prototype property? We don't allow it, as this is an edge case that we do not support. This error is a performance optimization and not spec compliant. TypeError: One of the sources for assign has an enumerable key on the prototype chain. Are you trying to assign a prototype property? We don't allow it, as this is an edge case that we do not support. This error is a performance optimization and not spec compliant. at Object.assign at Object.request at Object.https.get at getHttp at getXML at nextServer at gotServers at blob:http://localhost:8081/b1cfcde4-0ef7-4805-bd16-22849a1db8e3:87345:24 at module.exports. at module.exports.

**Comment by ferily7** [comment] 2018-08-17 20:27
If I try to use the latest version, I cannot even start up my React Native application. Just like  https://github.com/react-community/create-react-native-app/issues/401

**Comment by hramos** [comment] 2018-08-17 21:37
This is fixed on master and on the latest release candidate.

Duplicate of #20353

**Closed by hramos** 2018-08-17 21:37 UTC
Labels: :rewind:Old Version

**Comment by ferily7** [comment] 2018-08-17 21:49
Sorry, I'm new React Native, but how can I update my version? I'm currently using 0.55.4

**Comment by hramos** [comment] 2018-08-17 22:33
http://facebook.github.io/react-native/docs/upgrading

**Comment by ferily7** [comment] 2018-08-20 17:58
@hramos I updated my version to 0.57 and I'm still getting the same error:

> Error: Unable to resolve module `url` from `C:\Users\user\Documents\testVersion\node_modules\speedtest-net\index.js`: Module `url` does not exist in the Haste module map

Current version information: `react-native-cli: 2.0.1
react-native: 0.57.0-rc.0` Could this be an issue with the library I'm using?
