### ISSUE TITLE
TextInput keyboard sound feedback bug

### ISSUE THREAD

**Issue by macelii** [facebook/react-native#14234] opened 2017-05-28 14:04 UTC
This is something new when I upgrade an existing iOS project made with RN in 2015 to RN 0.39

When I type in the TextInput area, the 3rd or the fourth press will give a "boost sound" with noticeable higher volume than usual, this boost appears randomly if I keep typing.

Anyone has encountered the similar issue? Any ideas why this is now happening?

Many Thanks

**Comment by hramos** [comment] 2017-05-30 18:18
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-05-30 18:18 UTC

**Comment by renanpupin** [comment] 2018-04-05 13:24
@unmec I found the same problem, did you solve this?

**Comment by unmec** [comment] 2018-04-05 15:27
@renanpupin Not really. Since it's happening on a login page where users input their username and password, we think its rather a nice-to-fix than a must-fix. Lazy human.
