### ISSUE TITLE
[Android] alignItems: 'baseline' doesn't work 

### ISSUE THREAD

**Issue by MrSeaWave** [facebook/react-native#21918] opened 2018-10-24 08:36 UTC
- [X] Review the documentation: https://facebook.github.io/react-native
  - [X] Search for existing issues: https://github.com/facebook/react-native/issues
  - [X] Use the latest React Native release: https://github.com/facebook/react-native/releases

## on Android this bug still exists...

```
react-native init AwesomeProject
cd AwesomeProject
react-native run-android
```

## Environment
`react-native-info`
```
 React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
      Memory: 30.11 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 26.0.3, 27.0.3, 28.0.3
        API Levels: 26, 27, 28
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728 
      react-native: 0.57.3 => 0.57.3 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

my package.json is
```
{
  "name": "TemReactNative",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.6.0-alpha.8af6728",
    "react-native": "0.57.3"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.48.1",
    "react-test-renderer": "16.6.0-alpha.8af6728"
  },
  "jest": {
    "preset": "react-native"
  }
}
```
the Code is

```jsx
import React, { PureComponent } from 'react';
import { Text, View, StyleSheet } from 'react-native';

export default class TestTextBaseline extends PureComponent {
  render() {
    return (
      <View style={styles.container}>
        <View style={styles.textContainer}>
          <Text style={{ fontSize: 65, backgroundColor: '#ff9c6e' }}>1</Text>
          <Text style={{ fontSize: 55, backgroundColor: '#ff9c6e' }}>1</Text>
          <Text style={{ fontSize: 45, backgroundColor: '#ff9c6e' }}>1</Text>
          <Text style={{ fontSize: 35, backgroundColor: '#ff9c6e' }}>1</Text>
          <Text style={{ fontSize: 25, backgroundColor: '#ff9c6e' }}>1</Text>
        </View>
      </View>
    );
  }
}

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center'
  },
  textContainer: {
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'baseline'
  }
});

```

ios is correct

![image](https://user-images.githubusercontent.com/21967852/47329231-82ab9c00-d6a6-11e8-8500-05fa8b6d5125.png)

But android is wrong
![image](https://user-images.githubusercontent.com/21967852/47329191-5bed6580-d6a6-11e8-96cb-cdb6caa40bdc.png)

just like this https://github.com/facebook/react-native/issues/15858#issuecomment-432052143

**Comment by MrSeaWave** [comment] 2018-10-26 03:52
maybe we can use this code to solve this problem, but I think it's not a good idea
```jsx
import React, { PureComponent } from 'react'
import { Text, View, StyleSheet } from 'react-native'

export default class FixTextBaseline extends PureComponent {
  render() {
    return (
      <View style={styles.container}>
        <View style={styles.textContainer}>
          <Text>
            <Text style={{ fontSize: 65, backgroundColor: '#ff9c6e' }}>1</Text>
            <Text style={{ fontSize: 55, backgroundColor: '#ff9c6e' }}>1</Text>
            <Text style={{ fontSize: 45, backgroundColor: '#ff9c6e' }}>1</Text>
            <Text style={{ fontSize: 35, backgroundColor: '#ff9c6e' }}>1</Text>
            <Text style={{ fontSize: 25, backgroundColor: '#ff9c6e' }}>1</Text>
          </Text>
        </View>
      </View>
    )
  }
}

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center'
  },
  textContainer: {
    justifyContent: 'center',
    flexDirection: 'row'
    // alignItems: 'baseline'
  }
})
```
![fix](https://user-images.githubusercontent.com/21967852/47543600-97419b80-d915-11e8-9358-6fad49e088f5.jpg)

**Comment by rickhanlonii** [comment] 2019-03-19 15:46
Dupe of #20666

**Closed by rickhanlonii** 2019-03-19 15:46 UTC
Labels: Platform: Android, Type: Bug Report
