### ISSUE TITLE
Task 'installDebug' not found in root project ''.

### ISSUE THREAD

**Issue by CoLagon** [facebook/react-native#13229] opened 2017-03-31 05:07 UTC
C:\dev\myApp>react-native run-android
Scanning 552 folders for symlinks in C:\dev\myApp\node_modules (15ms)
Starting JS server...
Building and installing the app on the device (cd android && gradlew.bat installDebug)...

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDebug' not found in root project ''.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --inf or                                                                                                                     --debug                                                                                                                  option to get more log output.

BUILD FAILED

Total time: 12.126 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by CoLagon** [comment] 2017-03-31 05:10
I've been looking at this error for about a week now. I looked at every tutorial and even tried looking at stackoverflow for some answers. I can't run my app on my virtual device because of an error that doesn't specify what root project that installDebug needs to be in. I am running windows 10, any help will help me.

**Comment by hramos** [comment] 2017-03-31 16:44
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-03-31 16:44 UTC
