### ISSUE TITLE
Secured text strip the last character when set the state

### ISSUE THREAD

**Issue by vistiyos** [facebook/react-native#23081] opened 2019-01-20 01:25 UTC
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 30.55 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.1.0 - ~/.nvm/versions/node/v11.1.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v11.1.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 26, 27, 28
        Build Tools: 27.0.3, 28.0.2, 28.0.3
        System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.58.2 => 0.58.2
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2
      react-native-git-upgrade: 0.2.7

## Description
As it was discussed on #11631, this issue is still happening on RN 0.57.8, at least on Android, but that issue was marked as resolved, which is not. Is there any update on this or any workaround besides the proposed?

## Reproducible Demo
Here is the gif showing the behavior, as you can see in the logcat console behind the simulator, the state does not match the value in the screen:

![231de26d4bb824c8a3743041d5dd87f5](https://user-images.githubusercontent.com/822629/51804061-3bf8af80-225c-11e9-9dc4-775d0f1710bf.gif)

**Comment by hramos** [comment] 2019-01-23 00:31
Thanks for filing a new issue. Can you edit your issue and make sure all fields are sufficiently filled out? It's much cleaner and straightforward to take your issue into consideration when all the relevant information is in one place, even if you're simply duplicating what is already covered in the other issue. Otherwise, anyone interested in helping out will need to do duplicate work and go through the linked issue to figure out what information is still relevant. Thanks for taking this into consideration!

**Comment by vistiyos** [comment] 2019-01-27 16:52
I have updated the original post with the latest version (0.58.2) and it still happening.

**Comment by hramos** [comment] 2019-01-28 20:38
Thanks for verifying on the latest version. Do you have a small sample of code that would help us reproduce the issue?

**Comment by dulmandakh** [comment] 2019-03-19 15:28
Hello there 👋 this issue has been reported for an old version of React Native. Ideally we'd like everyone to be using 0.59 (see the [awesome changes](https://facebook.github.io/react-native/blog/2019/03/12/releasing-react-native-059) it brought) but we know updating can be a pain. We are going to close this issue because it's from a version before 0.57, which is really old.

But please, if it's actually still an issue with 0.59 please comment below and we can reopen it. Even better, please send us a pull request with a fix 😊

**Closed by dulmandakh** 2019-03-19 15:28 UTC
Labels: Resolution: Needs Repro, Type: Bug Report
