### ISSUE TITLE
Release version not package right when use flavorDimensions in gradle

### ISSUE THREAD

**Issue by cani1see** [facebook/react-native#14329] opened 2017-06-06 02:54 UTC
Build with demension1flavour-demension2flavour-release
Error:
Caused by: com.facebook.jni.CppException: Could not get BatchedBridge, make sure your bundle is packaged correctly

**Comment by hramos** [comment] 2017-06-06 04:48
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-06 04:48 UTC
