### ISSUE TITLE
[FlatList] serious problem

### ISSUE THREAD

**Issue by fangkyi02** [facebook/react-native#13609] opened 2017-04-21 12:47 UTC
![image](https://cloud.githubusercontent.com/assets/3389652/25277781/ad5be336-26d2-11e7-9b03-9de2194c785d.png)

**Problem description**
If I add components in renderitem using the flatlist display and the symbol is to click on it will display error

*error message**
0.43.3 err 
![1](https://cloud.githubusercontent.com/assets/3389652/25277916/34cd25f0-26d3-11e7-8699-267d86328810.png)
_0.43.4 err_
![2](https://cloud.githubusercontent.com/assets/3389652/25277930/3dccc4c6-26d3-11e7-9ad0-2b658472883f.png)

**Error code**
![image](https://cloud.githubusercontent.com/assets/3389652/25278013/9db0650a-26d3-11e7-9aa2-17870fc626b9.png)
Normal code
![image](https://cloud.githubusercontent.com/assets/3389652/25278047/bcd91f44-26d3-11e7-96c9-b81bb99bbfae.png)

**Comment by beeglebug** [comment] 2017-04-21 14:48
Think this might be related to #12905, I had the same thing in a FlatList when using a number as text

**Comment by Ehesp** [comment] 2017-04-21 15:16
@fangkyi02 for now, do `<Text>{`${index}`}</Text>`. I believe this has been raised a few times!

**Comment by hramos** [comment] 2017-04-25 13:33
Seems like a dupe of #12905. Try the workaround above. A fix will ship in the next release.

**Closed by hramos** 2017-04-25 13:33 UTC
