### ISSUE TITLE
linking package causes error when build

### ISSUE THREAD

**Issue by ozergul** [facebook/react-native#15413] opened 2017-08-08 16:23 UTC
Hello,
I created a project 

`react-native init test`

After this run this command

```
npm install react-native-image-picker@latest --save
react-native link
```

Here is the error... 
> 
> C:\Users\ozer\Desktop\rn\test33\node_modules\react-native-image-picker\android\src\main\java\com\imagepicker\ImagePickerPackage.java:34: error: method does not override or implement a method from a supertype
>   @Override
>   ^
> :react-native-image-picker:compileReleaseJavaWithJavac FAILED
> 1 error
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':react-native-image-picker:compileReleaseJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 

Also guys, I get this error all packages just not to this..

> react-native-cli: 2.0.1
> react-native: 0.47.1

I do everything, tried all solution ways. But still same errors... I can't link projects, always gives error.

**Comment by hramos** [comment] 2017-08-08 18:42
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Comment by Amurmurmur** [comment] 2017-08-08 18:42
@ozergul react-native-image-picker needs to update a method for android, more specifically:
```
@Override
```
at [https://github.com/react-community/react-native-image-picker/blob/develop/android/src/main/java/com/imagepicker/ImagePickerPackage.java#L29](https://github.com/react-community/react-native-image-picker/blob/develop/android/src/main/java/com/imagepicker/ImagePickerPackage.java#L29)

needs to be removed to support backward compatibillity

**Closed by hramos** 2017-08-08 18:42 UTC

**Comment by ozergul** [comment] 2017-08-08 18:51
@Amurmurmur same error.

**Comment by Amurmurmur** [comment] 2017-08-08 19:01
@ozergul Make sure to make a clean build. and reset react-native packager.

**Comment by ozergul** [comment] 2017-08-08 19:16
```
gradlew clean
react-native start

```
runned these command but same error..
