### ISSUE TITLE
Xcode 8.3 IOS 10.3 with react-native 0.39.2 doesn't work

### ISSUE THREAD

**Issue by philipphecht** [facebook/react-native#13223] opened 2017-03-30 18:08 UTC
* React Native version:0.39.2
* Platform: IOS 10.3
* Development Operating System: MACOS
* Dev tools: XCODE 8.3

Class PLBuildVersion is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x1200d7cc0) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x11feee6f0). One of the two will be used. Which one is undefined.
2017-03-30 20:06:37.637 [info][tid:main][RCTBatchedBridge.m:72] Initializing <RCTBatchedBridge: 0x610000380000> (parent: <RCTBridge: 0x6100000af420>, executor: RCTJSCExecutor)
2017-03-30 20:06:37.638 SocialApp[20996:74712] *** Assertion failure in -[RCTBatchedBridge loadSource:onProgress:](), /

**Comment by hramos** [comment] 2017-03-30 18:13
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-03-30 18:13 UTC
