### ISSUE TITLE
Unable to use react-native-git-upgrade tool successfully

### ISSUE THREAD

**Issue by purezen** [facebook/react-native#11742] opened 2017-01-06 07:26 UTC
I want to update my app on rn version 0.28 to latest. I tried using `react-native-git-upgrade` tool for the purpose.
So from the app dir, where I had previously done `npm install`, I did npm i -g react-native-git-upgrade and then accessed the tool using react-native-git-upgrade.

This is what I see:

```
⚡ react-native-git-upgrade
git-upgrade info Check for updates
git-upgrade info Read package.json files
git-upgrade info Check declared version
git-upgrade info Check matching versions
git-upgrade info Check React peer dependency
git-upgrade info Check that Git is installed
git-upgrade info Get information from NPM registry
git-upgrade info Upgrading to React Native 0.40.0, React ~15.4.0-rc.4
git-upgrade info Setup temporary working directory
git-upgrade info Configure Git environment
git-upgrade info Init Git repository
git-upgrade info Add all files to commit
git-upgrade info Commit current project sources
git-upgrade info Create a tag before updating sources
git-upgrade info Generate old version template
git-upgrade info Add updated files to commit
git-upgrade info Commit old version template
git-upgrade info Install the new version
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
git-upgrade info Generate new version template
git-upgrade info Add updated files to commit
git-upgrade info Commit new version template
git-upgrade info Generate the patch between the 2 versions
git-upgrade info Save the patch in temp directory
git-upgrade info Reset the 2 temporary commits
git-upgrade info Apply the patch
/var/folders/sh/jgy3w2sx20z_557gfg95sl9h0000gn/T/react-native-git-upgrade/upgrade_0.28.0_0.40.0.patch:281: indent with spaces.
          new MainReactPackage()
/var/folders/sh/jgy3w2sx20z_557gfg95sl9h0000gn/T/react-native-git-upgrade/upgrade_0.28.0_0.40.0.patch:425: trailing whitespace.
@if "%DEBUG%" == "" @echo off
/var/folders/sh/jgy3w2sx20z_557gfg95sl9h0000gn/T/react-native-git-upgrade/upgrade_0.28.0_0.40.0.patch:426: trailing whitespace.
@rem ##########################################################################
/var/folders/sh/jgy3w2sx20z_557gfg95sl9h0000gn/T/react-native-git-upgrade/upgrade_0.28.0_0.40.0.patch:427: trailing whitespace.
@rem
/var/folders/sh/jgy3w2sx20z_557gfg95sl9h0000gn/T/react-native-git-upgrade/upgrade_0.28.0_0.40.0.patch:428: trailing whitespace.
@rem  Gradle startup script for Windows
error: patch failed: .flowconfig:1
Falling back to three-way merge...
Applied patch to '.flowconfig' with conflicts.
error: patch failed: .gitignore:22
Falling back to three-way merge...
Applied patch to '.gitignore' with conflicts.
error: patch failed: android/app/BUCK:5
Falling back to three-way merge...
Applied patch to 'android/app/BUCK' with conflicts.
error: patch failed: android/app/src/main/java/com/goodbox/MainActivity.java:1
Falling back to three-way merge...
Applied patch to 'android/app/src/main/java/com/goodbox/MainActivity.java' with conflicts.
error: cannot apply binary patch to 'android/app/src/main/res/mipmap-hdpi/ic_launcher.png' without full index line
Falling back to three-way merge...
error: cannot apply binary patch to 'android/app/src/main/res/mipmap-hdpi/ic_launcher.png' without full index line
error: android/app/src/main/res/mipmap-hdpi/ic_launcher.png: patch does not apply
error: cannot apply binary patch to 'android/app/src/main/res/mipmap-mdpi/ic_launcher.png' without full index line
Falling back to three-way merge...
error: cannot apply binary patch to 'android/app/src/main/res/mipmap-mdpi/ic_launcher.png' without full index line
error: android/app/src/main/res/mipmap-mdpi/ic_launcher.png: patch does not apply
error: cannot apply binary patch to 'android/app/src/main/res/mipmap-xhdpi/ic_launcher.png' without full index line
Falling back to three-way merge...
error: cannot apply binary patch to 'android/app/src/main/res/mipmap-xhdpi/ic_launcher.png' without full index line
error: android/app/src/main/res/mipmap-xhdpi/ic_launcher.png: patch does not apply
error: cannot apply binary patch to 'android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png' without full index line
Falling back to three-way merge...
error: cannot apply binary patch to 'android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png' without full index line
error: android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png: patch does not apply
error: patch failed: ios/goodbox.xcodeproj/project.pbxproj:22
Falling back to three-way merge...
Applied patch to 'ios/goodbox.xcodeproj/project.pbxproj' with conflicts.
error: patch failed: ios/goodbox.xcodeproj/xcshareddata/xcschemes/goodbox.xcscheme:37
Falling back to three-way merge...
Applied patch to 'ios/goodbox.xcodeproj/xcshareddata/xcschemes/goodbox.xcscheme' cleanly.
error: patch failed: ios/goodbox/AppDelegate.m:17
Falling back to three-way merge...
Applied patch to 'ios/goodbox/AppDelegate.m' cleanly.
error: patch failed: ios/goodbox/Info.plist:45
Falling back to three-way merge...
Applied patch to 'ios/goodbox/Info.plist' with conflicts.
error: patch failed: ios/goodboxTests/goodboxTests.m:10
Falling back to three-way merge...
Applied patch to 'ios/goodboxTests/goodboxTests.m' cleanly.
git-upgrade WARN The upgrade process succeeded but there might be conflicts to be resolved. See above for the list of files that have merge conflicts.
git-upgrade info Upgrade done
```

However, my package.json is still on v.28 whose corresponding java package gets installed on my device when I do react-native run-android.

### Additional Information

* React Native version: 0.28
* Platform: Android
* Operating System: MacOS

**Comment by ericvicenti** [comment] 2017-01-06 20:04
cc @mkonicek

**Comment by ncuillery** [comment] 2017-01-06 21:23
From the output, it seems to be a duplicate of #11402. @purezen you'll find a workaround there.

On a side note, I'd recommend to upgrade from 0.28 to 0.29 first, then verify your app is working well and then upgrade to the latest. The upgrade 0.28 👉 0.29 was a big one.

**Comment by mkonicek** [comment] 2017-01-17 22:42
@facebook-github-bot duplicate #11402 .

**Comment by mkonicek** [comment] 2017-01-17 22:55
@facebook-github-bot duplicate #11402

**Comment by mkonicek** [comment] 2017-01-17 23:03
Bot's not working, pinged people at fb to look into it.

**Comment by mkonicek** [comment] 2017-01-18 01:48
@facebook-github-bot duplicate #11402

**Closed** 2017-01-18 01:48 UTC
Labels: Ran Commands
