### ISSUE TITLE
 java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes-executor-release.so. in React-Native: 0.70.6

### ISSUE THREAD

**Issue by Brittognanaraj** [facebook/react-native#35710] opened 2022-12-23 19:52 UTC
### Description

I am getting this error in React-Native: 0.70.6
 java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes-executor-release.so

SoSource 0: com.facebook.soloader.DirectorySoSource[root = /data/app/~~Ugf7fQtxfAVyef-2afpx_A==/com.swellmoney.qa.android-bbsSDgEUlLKmTLucaSeD8g==/lib/arm64 flags = 0]
SoSource 1: com.facebook.soloader.DirectApkSoSource[root = (/data/app/~~Ugf7fQtxfAVyef-2afpx_A==/com.swellmoney.qa.android-bbsSDgEUlLKmTLucaSeD8g==/base.apk!/lib/arm64-v8a, )]
                                                                                                    	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
                                                                                                    	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
                                                                                                    	Native lib dir: /data/app/~~Ugf7fQtxfAVyef-2afpx_A==/com.swellmoney.qa.android-bbsSDgEUlLKmTLucaSeD8g==/lib/arm64
                                                                                                     result: 0
                                                                                                    	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1127)
                                                                                                    	at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:943)
                                                                                                    	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:855)
                                                                                                    	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:802)
                                                                                                    	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:772)
                                                                                                    	at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:30)
                                                                                                    	at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:19)
                                                                                                    	at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:23)
                                                                                                    	at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:393)
                                                                                                    	at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:343)
                                                                                                    	at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:96)
                                                                                                    	at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:42)
                                                                                                    	at com.swellmoney.android.MainApplication.onCreate(MainApplication.java:67)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
                                                                                                    	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:223)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7656)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

### Version

0.70.6

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 122.73 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.11.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
    Watchman: 2022.10.17.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 23, 29, 30, 31, 32, 33
      Build Tools: 29.0.2, 29.0.3, 30.0.2, 30.0.3, 32.0.0, 32.1.0, 33.0.0, 33.0.1
      System Images: android-24 | Google APIs ARM 64 v8a, android-25 | Google APIs ARM 64 v8a, android-28 | Google APIs ARM 64 v8a, android-28 | Google ARM64-V8a Play ARM 64 v8a, android-29 | ARM 64 v8a, android-29 | Google Play ARM 64 v8a, android-30 | ARM 64 v8a, android-30 | Intel x86 Atom_64, android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play ARM 64 v8a, android-30 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64, android-31 | ARM 64 v8a, android-31 | Intel x86 Atom_64, android-31 | Google APIs ARM 64 v8a, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play ARM 64 v8a, android-31 | Google Play Intel x86 Atom_64, android-32 | Google APIs ARM 64 v8a, android-32 | Google APIs Intel x86 Atom_64, android-32 | Google Play ARM 64 v8a, android-32 | Google Play Intel x86 Atom_64, android-33 | Google APIs ARM 64 v8a, android-Tiramisu | Google Play ARM 64 v8a
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.8 - /Library/Java/JavaVirtualMachines/openlogic-openjdk-11.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

While opening an app itself I am getting below crash

 java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes-executor-release.so

SoSource 0: com.facebook.soloader.DirectorySoSource[root = /data/app/~~Ugf7fQtxfAVyef-2afpx_A==/com.swellmoney.qa.android-bbsSDgEUlLKmTLucaSeD8g==/lib/arm64 flags = 0]
SoSource 1: com.facebook.soloader.DirectApkSoSource[root = (/data/app/~~Ugf7fQtxfAVyef-2afpx_A==/com.swellmoney.qa.android-bbsSDgEUlLKmTLucaSeD8g==/base.apk!/lib/arm64-v8a, )]
                                                                                                    	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
                                                                                                    	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
                                                                                                    	Native lib dir: /data/app/~~Ugf7fQtxfAVyef-2afpx_A==/com.swellmoney.qa.android-bbsSDgEUlLKmTLucaSeD8g==/lib/arm64
                                                                                                     result: 0
                                                                                                    	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1127)
                                                                                                    	at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:943)
                                                                                                    	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:855)
                                                                                                    	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:802)
                                                                                                    	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:772)
                                                                                                    	at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:30)
                                                                                                    	at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:19)
                                                                                                    	at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:23)
                                                                                                    	at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:393)
                                                                                                    	at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:343)
                                                                                                    	at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:96)
                                                                                                    	at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:42)
                                                                                                    	at com.swellmoney.android.MainApplication.onCreate(MainApplication.java:67)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
                                                                                                    	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:223)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7656)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

### Snack, code example, screenshot, or link to a repository

https://stackoverflow.com/questions/74903512/java-lang-unsatisfiedlinkerror-couldnt-find-dso-to-load-libhermes-executor-re

**Comment by domeknn** [comment] 2022-12-24 10:15
+1

**Comment by Brittognanaraj** [comment] 2022-12-30 07:42
Anyone got a solution?

**Comment by 98rahul** [comment] 2023-01-13 13:44
@Brittognanaraj  did it solve? 
as same issue generating for 0.70.5 version

**Comment by KrisLau** [comment] 2023-01-13 21:45
https://github.com/facebook/react-native/issues/2814

**Comment by fleuverouge** [comment] 2023-01-16 07:08
This issue is serious. I wonder if there is any plan to fix this?

**Comment by Brittognanaraj** [comment] 2023-01-16 09:31
No @98rahul

**Comment by cortinico** [comment] 2023-01-18 16:17
> java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes-executor-release.so

This and all the "couldn't find DSO to load" bugs have been fixed in React Native 0.71
I'm closing this, please update to 0.71 and open new issue if the problem persists.

**Closed by cortinico** 2023-01-18 16:17 UTC
Labels: Needs: Triage :mag:

**Comment by Hmoulvad** [comment] 2023-01-19 11:25
@cortinico I have still having this issue while upgrading to 0.71.0.

`couldn't find DSO to load: libjscexecutor.so`

**Comment by cortinico** [comment] 2023-01-19 11:33
> I'm closing this, please update to 0.71 and open new issue if the problem persists.

Then please create a new issue and share your setup. If it's a but in 0.71 we'll get it fixed.

**Comment by sultanularefin** [comment] 2023-01-22 05:29
My React Native app(0.71.1 ) was crushin due to this issue, I found the cause of the error (please check the comments) like below in my **gradle.properties file**:

1. **With Error** 
hermesEnabled= true # true # false #true #https://github.com/facebook/react-native/issues/35828#issuecomment-1382357834


1. Without Error 
hermesEnabled= true
# comments are now put in another line.
# true # false #true #https://github.com/facebook/react-native/issues/35828#issuecomment-1382357834

**Comment by deflexable** [comment] 2023-04-01 00:14
@sultanularefin were you able to fix this? also having the same issue 🫤

**Comment by grkemtneri** [comment] 2023-04-11 20:04
Did you find any solution ?
