### ISSUE TITLE
Finalizers are retained and causing Out of memory crash

### ISSUE THREAD

**Issue by pitchourou** [facebook/react-native#21875] opened 2018-10-21 00:03 UTC
## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.3
      CPU: x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Memory: 347.45 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.9.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.2.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.2, macOS 10.13, tvOS 11.2, watchOS 4.2
      Android SDK:
        Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3
        API Levels: 23, 25, 26, 27
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.2 => 0.57.2
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Description
As you can see below there is a serious issue with memory used by Finalizers, objects are retained and never cleaned, this is causing Out of memory crash on production version. Got the same behavior with latest RN release 0.57 and I'm only displaying a large Flatlist with numColumns={2}. I tried FastImage thinking it was a Fresco issue , but got the same result

<img width="1088" alt="capture d ecran 2018-10-21 a 00 38 05" src="https://user-images.githubusercontent.com/16292971/47261668-2a20a700-d4cc-11e8-9007-f6e18bbb4082.png">

## Reproducible Demo
Flatlist with remote images

**Comment by pitchourou** [comment] 2018-10-21 14:36
Any comment ?

**Comment by jpaas** [comment] 2018-11-23 18:48
I'm running 0.57.5 and seeing similar problems. App pretty much unusable on any Android phone with 2Gb RAM.

**Comment by dulmandakh** [comment] 2019-03-19 14:22
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗

**Comment by dulmandakh** [comment] 2019-03-19 14:23
Could you please upgrade to 0.59 and check if issue persists. Also please provide reproducible demo, so we can investigate the issue.

**Closed by dulmandakh** 2019-03-19 14:22 UTC
Labels: Type: Bug Report
