### ISSUE TITLE
NAV_BAR_HEIGHT shouldn't be hardcoded

### ISSUE THREAD

**Issue by gre** [facebook/react-native#7774] opened 2016-05-26 08:39 UTC
Instead it should use the height I give in style param of NavigatorBar.
Because of this, I will have issues like overflow hidden happening on the Left section as soon as my nav bar is > NAV_BAR_HEIGHT:

<img width="145" alt="screen shot 2016-05-26 at 10 39 24" src="https://cloud.githubusercontent.com/assets/211411/15568802/25218154-232e-11e6-9d68-f54e15ea0f21.png">

**Comment by satya164** [comment] 2016-05-26 13:26
@gre It's a bit complicated because,
1) you need both the statusbar height and the desired appbar height, so when you're passing a custom height, you need to take care of providing different heights for Android and iOS,
2) the height constant is exported for use at other places, if we use the style passed in via the style prop, we lose this convenience

The `<NavigationHeader />` styles aren't very customizable. We might need to provide a way to override them while ensuring that it doesn't interfere with the styles we actually need.

We export the back button and the title component though, so you can always set custom styles on those.

**Comment by gre** [comment] 2016-05-26 13:46
Ok I see. Then, how do you feel about removing the `overflow:hidden`

here
https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/Navigator/NavigatorNavigationBarStylesIOS.js#L53

and here
https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/Navigator/NavigatorNavigationBarStylesIOS.js#L62

which is, I think, the only blocking reason we can't have navigator bar greater than NAV_BAR_HEIGHT (because things become hidden after this).
I'm not sure the reason of this style, also weirdly it's not present on **Title**.

**Comment by satya164** [comment] 2016-05-28 13:10
Oh, sorry, I assumed you're talking about `NavigationExperimental`. Though what I said still stands true. I'm not sure why `overflow: hidden` is added there, so I don't know what'll happen when we remove it.

**Comment by lacker** [comment] 2016-10-21 07:26
It seems like this issue is resolved as "working as intended" so I am going to close this issue.

**Closed by lacker** 2016-10-21 07:26 UTC
