### ISSUE TITLE
Share feature not working properly with Google Inbox

### ISSUE THREAD

**Issue by WaldoJeffers** [facebook/react-native#16002] opened 2017-09-19 09:30 UTC
### Is this a bug report?
Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
Yes

### Environment

1. react-native: 0.47.2
2. node: 8.4.0
3. npm: 5.3.0
4. yarn: 0.27.5

- Target Platform:
iPhone 5/6/7, iOS 10.3.3

- Development Operating System:
macOS Sierra 10.12.6

- Build tools:
Xcode v8.3.3

Also, the **Google Inbox** version I'm using on my phone is **1.3.170813**
### Steps to Reproduce

1. Create a button that uses the [Share feature](https://facebook.github.io/react-native/docs/share.html) and set a distinct message & title, like this: 
```js
import {Share} from 'react-native';

Share.share({
    message: `message`,
    title: `title`
});
```
2. Click on the button/trigger the share feature, and select Google Inbox
3. Observe the email's subject and body

### Expected Behavior

The email's subject should be filled with the `title` option's value. It's impossible to set up a correct email subject at the moment.

### Actual Behavior

The `title` option is not used, and the email's subject is actually using the `message` option. The email body is entirely pasted to the email's subject field. 

### Reproducible Demo

[Reproducible Snack demo](https://snack.expo.io/S17YzPA9-)

### Additional info
I can share content using Inbox with other apps without problems, so I don't think it's a problem with Google Inbox itself.
Interestingly, there is a [very similar issue](https://github.com/EstebanFuentealba/react-native-share/issues/89) on `react-native-share`'s repo, and [another one on this repo](https://github.com/facebook/react-native/issues/14607).

**Comment by GollyJer** [comment] 2017-10-13 16:06
Hi.  I wanted to chime in on this because I ran into it today.

**In a nutshell...**
On **iOS only**, when sharing to the Google Inbox app, the `message:` method is incorrectly set as the email subject instead of `title:` method.

It behaves as expected on Android.
@janicduplessis, it would probably be good to change the issue label.

**Comment by WaldoJeffers** [comment] 2017-12-11 16:40
Yep, this is an iOS issue

**Comment by WaldoJeffers** [comment] 2017-12-13 14:44
Tested on 0.51, the recently `subject`option does not seem to help. This is really frustrating. Is there any plans to fix it? Is there any way we can help? And again, it should be labelled as an iOS issue.

**Comment by dsc-ian** [comment] 2018-01-12 05:45
Any update on this issue?

**Comment by WaldoJeffers** [comment] 2018-06-17 19:32
This still has not been fixed it, move over stalebot!

**Comment by qaiser110** [comment] 2018-09-18 23:46
This issue still has not been fixed

**Comment by kelset** [comment] 2018-09-21 09:31
So, this issue happens only in iOS with Google Inbox?

Does is still happen with 0.57? Is it reproducible in all iOS versions available?

Does it happen with other email clients?

Because if it's a Google Inbox specific issue I don't think it will be fixed, considering that Inbox is going to be dismissed in early 2019.

**Comment by hramos** [comment] 2019-01-29 20:52
Closing due to lack of follow up.

**Closed by hramos** 2019-01-29 20:52 UTC
Labels: Bug Report, Platform: iOS, Resolution: Needs More Information, ✅Author Provided Repro
