### ISSUE TITLE
ToastAndroid has no respond

### ISSUE THREAD

**Issue by micsay** [facebook/react-native#9869] opened 2016-09-13 00:43 UTC
```
render() {
        return (
            <View style={{flex: 1, justifyContent: "center", alignItems: "center"}}>
                <TouchableNativeFeedback
                    onPress={() => {
                        ToastAndroid.show('pressing', ToastAndroid.SHORT);
                    }}
                    background={TouchableNativeFeedback.SelectableBackground()}>
                    <View>
                        <Text>Click me</Text>
                    </View>
                </TouchableNativeFeedback>
                <TextInput onChangeText={(value)=>{
                    ToastAndroid.showWithGravity('altering', ToastAndroid.SHORT, ToastAndroid.TOP);
                    this.setState({
                        value: value,
                    });
                }}/>
            </View>
        );
}
```

it doesn't work when I alter text or press

**Comment by micsay** [comment] 2016-09-13 00:44
Maybe someone could help me, thanks.

**Comment by leeight** [comment] 2016-09-13 01:50
Can not reproduce it on the master branch.

![image](https://cloud.githubusercontent.com/assets/104052/18458869/849d1caa-7997-11e6-87a2-a04898b7ecec.png)

**Comment by Anuj-786** [comment] 2016-09-28 10:47
Hey @micsay, can you share what error you face, Because the code you shared is working 
![screenshot_2016-09-28-16-09-24](https://cloud.githubusercontent.com/assets/15275386/18910730/f4eee5aa-8596-11e6-8fda-2010498dff9d.png)
![screenshot_2016-09-28-16-09-34](https://cloud.githubusercontent.com/assets/15275386/18910731/f5170fe4-8596-11e6-806e-b2e0227caf11.png)

**Comment by lacker** [comment] 2017-02-07 21:40
Closing as "cannot reproduce".

**Closed by lacker** 2017-02-07 21:40 UTC

**Comment by aMarCruz** [comment] 2018-07-01 04:11
@micsay did you solve your issue? I have the same.
