### ISSUE TITLE
RequestAnimationFrame + ListView + Animated.View with transform:scale doesn't render before first scroll event

### ISSUE THREAD

**Issue by Purii** [facebook/react-native#8840] opened 2016-07-16 23:40 UTC
There seems to be a bug with the following construction since several releases (worked at least on 0.25).

`requestAnimationFrame` +  `ListView` (Elements `Animated.View` with `transform:scale`)

Using these elements and APIs together hides the elements of the ListView until the first scroll event.

* Works without `ListView`
* Works without `requestAnimationFrame`
* Works with `opacity` instead of `transform:scale`

## Reproduce

*Based on template of 0.29.1. Tested with iOS Simulator + iPhone 5s*

```
...
constructor(props) {
    super(props);
    this.animationId = null;
    this.state = {
      bounceValue: new Animated.Value(0),
    };
    this.dataSource = new ListView.DataSource({ rowHasChanged: (row1, row2) => row1 !== row2 });
  }

componentDidMount() {
    this.animationId = GLOBAL.requestAnimationFrame(() => {
      this.state.bounceValue.setValue(0.5);
      Animated.spring(
        this.state.bounceValue, 
        {
          toValue: 1,
          tension: 30, 
          friction: 3, 
        }
      ).start();
    });
}
componentWillUnmount() {
    GLOBAL.cancelAnimationFrame(this.animationId);
}
render() {
    const renderElement = () => (
      <Animated.View
        style={[
          styles.container,
          {
            transform: [                        
              { scale: this.state.bounceValue },
            ],
            flex: 1,
          }
        ]}
      >
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.ios.js
        </Text>
        <Text style={styles.instructions}>
          Press Cmd+R to reload,{'\n'}
          Cmd+D or shake for dev menu
        </Text>
      </Animated.View>
    );

    return (
      <ListView
        automaticallyAdjustContentInsets={false}
        contentContainerStyle={{flex: 1}}
        dataSource={this.dataSource.cloneWithRows(["bla"])}
        renderRow={renderElement}
      />
    )
}
...
```

| Initial render | after scroll event |
| :------------: | :---------------: |
| ![initialrender](https://cloud.githubusercontent.com/assets/7056989/16897831/d9cc024c-4bbe-11e6-9afb-c064be81c27e.png) | ![afterscrollevent](https://cloud.githubusercontent.com/assets/7056989/16897830/d9963478-4bbe-11e6-85da-f6d640ed8582.png) |

**Comment by TheSisb** [comment] 2016-08-15 20:53
Also facing this issue after upgrading from RN 0.26 to 0.30

**Comment by chirag04** [comment] 2016-08-15 20:57
can you try setting `removeClippedSubviews={false}` on your listview and see if works?

**Comment by TheSisb** [comment] 2016-08-15 21:00
That fixes it.  @chirag04

**Comment by chirag04** [comment] 2016-08-15 21:06
thanks for confirming. I would make it as duplicate of https://github.com/facebook/react-native/issues/1831 then.

**Closed by chirag04** 2016-08-15 21:06 UTC
