### ISSUE TITLE
Getting ReactAndroid:configureNdkBuildDebug Error when NewArch is Enabled

### ISSUE THREAD

**Issue by CortexTN** [facebook/react-native#33742] opened 2022-05-02 11:04 UTC
### New Version

0.68.1

### Old Version

0.67.3

### Build Target(s)

Android Debug

### Output of `react-native info`

System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz
    Memory: 447.12 MB / 3.88 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 30, 31, 32
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0
      Android NDK: 24.0.8215888
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 11.0.15 - C:\Program Files\Eclipse Adoptium\jdk-11.0.15.10-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.1 => 0.68.1
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### My Issue:
I'm facing an error when buidling my react-native project, to be precisely, it's an ndk problem when NewArch is enabled, but when it's disabled, build success.

### Error Log: 
`> Task :ReactAndroid:configureNdkBuildDebug[arm64-v8a] FAILED
C/C++: C:\Users\Administrator\Documents\GitHub\MoonMeet-CrossPlatform\node_modules\react-native\ReactAndroid/../ReactCommon/butter/Android.mk:28: *** Android NDK: Aborting. 
   .  Stop.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ReactAndroid:configureNdkBuildDebug[arm64-v8a]'.
> [CXX1405] error when building with ndkBuild using C:\Users\Administrator\Documents\GitHub\MoonMeet-CrossPlatform\node_modules\react-native\ReactAndroid\src\main\jni\react\jni\Android.mk: Build command failed.
  Error while executing process C:\Users\Administrator\AppData\Local\Android\Sdk\ndk\23.1.7779620\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\Users\Administrator\Documents\GitHub\MoonMeet-CrossPlatform\node_modules\react-native\ReactAndroid\src\main\jni\react\jni\Android.mk APP_ABI=arm64-v8a NDK_ALL_ABIS=arm64-v8a NDK_DEBUG=1 APP_PLATFORM=android-21 NDK_LIBS_OUT=C:\Users\Administrator\Documents\GitHub\MoonMeet-CrossPlatform\node_modules\react-native\ReactAndroid\build\intermediates\cxx\Debug\2l523i4m/lib NDK_APPLICATION_MK=C:\Users\Administrator\Documents\GitHub\MoonMeet-CrossPlatform\node_modules\react-native\ReactAndroid/src/main/jni/Application.mk THIRD_PARTY_NDK_DIR=C:\Users\Administrator\Documents\GitHub\MoonMeet-CrossPlatform\node_modules\react-native\ReactAndroid\build\third-party-ndk REACT_COMMON_DIR=C:\Users\Administrator\Documents\GitHub\MoonMeet-CrossPlatform\node_modules\react-native\ReactAndroid/../ReactCommon REACT_GENERATED_SRC_DIR=C:\Users\Administrator\Documents\GitHub\MoonMeet-CrossPlatform\node_modules\react-native\ReactAndroid\build/generated/source REACT_SRC_DIR=C:\Users\Administrator\Documents\GitHub\MoonMeet-CrossPlatform\node_modules\react-native\ReactAndroid/src/main/java/com/facebook/react -j4 NDK_OUT=C:\Users\Administrator\Documents\GitHub\MoonMeet-CrossPlatform\.cxx NDK_APP_SHORT_COMMANDS=true APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
  Android NDK: WARNING: Ignoring unknown import directory: C:\Users\Administrator\Documents\GitHub\MoonMeet-CrossPlatform\node_modules\react-native\ReactAndroid\build/generated/source
  Android NDK: C:\Users\Administrator\Documents\GitHub\MoonMeet-CrossPlatform\node_modules\react-native\ReactAndroid/../ReactCommon/butter/Android.mk: Cannot find module with tag 'glog' in import path
  Android NDK: Are you sure your NDK_MODULE_PATH variable is properly defined ?
  Android NDK: The following directories were searched:
  Android NDK:

  C:\Users\Administrator\Documents\GitHub\MoonMeet-CrossPlatform\node_modules\react-native\ReactAndroid/../ReactCommon/butter/Android.mk:28: *** Android NDK: Aborting.    . 
 Stop.`

### Attachments:

I've seen something like ` Android NDK: Are you sure your NDK_MODULE_PATH variable is properly defined ?` i did define it but  still the same error

![Screenshot (12)](https://user-images.githubusercontent.com/73752904/166224144-efd0263d-fa33-488b-ac07-9003a45aeb99.png)

![Screenshot (13)](https://user-images.githubusercontent.com/73752904/166224157-344f918f-35d5-4901-a955-23e3747cd777.png)

**I can provide another files if recommended, Thanks React-Native Team!**

**Comment by fortmarek** [comment] 2022-05-02 14:45
Hey @CortexTN 👋 

You might try to check out these two PRs (https://github.com/facebook/react-native/pull/33682 and https://github.com/facebook/react-native/pull/33707) and patch your local React Native to see if that helps. Whenever those PRs are merged, we plan to release another patch release `0.68.2`.

In the meantime, if you could also provide reproducible steps, that would be fabulous.

@mganandraj do you think this issue might be related to your PRs?

**Comment by CortexTN** [comment] 2022-05-02 15:00
Thanks for responding, I don't know how to reproduce steps for issues, but i clearly remember myself followed react native upgrade helper guide then i builded the app end up getting this error

**Comment by fortmarek** [comment] 2022-05-02 15:11
I recommend creating a new app with `npx react-native init MySample --version 0.68.1` and trying to reproduce the issue there. Of course, it might not be always possible but it's worth trying.

**Comment by CortexTN** [comment] 2022-05-02 15:24
I'll try it and comeback to you ASAP

**Comment by CortexTN** [comment] 2022-05-02 15:54
Hello again @fortmarek 
I've downloaded the fresh react-native template (0.68.1) as you said, and i can now confirm that building a react native app with new arch is broken on windows, I haven't change anything on the template and i got an error like you mentioned above (Long Paths), i hope you guys fix build on windows, anyway build on windows with new arch disabled works well!

**Comment by fortmarek** [comment] 2022-05-02 16:57
Thanks for getting back to us - the fix should be hopefully be merged soon 🙌 You can also try out the new `0.69.0-rc.0` where the approach has changed and the long paths should no longer be an issue.

**Comment by CortexTN** [comment] 2022-05-02 18:03
Thanks for help sir, much appreciated, anyway i saw both PRs (https://github.com/facebook/react-native/pull/33682 and https://github.com/facebook/react-native/pull/33707) and i patched my local react native, but still an error. i guess i did everything correctly.

**Comment by mganandraj** [comment] 2022-05-02 19:23
> Hey @CortexTN 👋
> 
> You might try to check out these two PRs (#33682 and #33707) and patch your local React Native to see if that helps. Whenever those PRs are merged, we plan to release another patch release `0.68.2`.
> 
> In the meantime, if you could also provide reproducible steps, that would be fabulous.
> 
> @mganandraj do you think this issue might be related to your PRs?

Yep, [PR#33707](https://github.com/facebook/react-native/pull/33707) should fix the build on Windows boxes with reasonable application root path.. But, as long as we use NDK21, we are still prone to issues with long file paths if the root path is long (>15 chars).. 
[PR#33707](https://github.com/facebook/react-native/pull/33707) is currently blocked though because of complexities in bringing fixes to react-native-codegen package into stable branches.

**Comment by CortexTN** [comment] 2022-05-02 19:26
> > Hey @CortexTN 👋
> > 
> > You might try to check out these two PRs (#33682 and #33707) and patch your local React Native to see if that helps. Whenever those PRs are merged, we plan to release another patch release `0.68.2`.
> > 
> > In the meantime, if you could also provide reproducible steps, that would be fabulous.
> > 
> > @mganandraj do you think this issue might be related to your PRs?
> 
> Yep, [PR#33707](https://github.com/facebook/react-native/pull/33707) should fix the build on Windows boxes with reasonable application root path.. But, as long as we use NDK21, we are still prone to issues with long file paths if the root path is long (>15 chars).. 
> [PR#33707](https://github.com/facebook/react-native/pull/33707) is currently blocked though because of complexities in bringing fixes to react-native-codegen package into stable branches.
> 

I've tried patching my local react native with your changes and unfortunately it didn't work

**Comment by mganandraj** [comment] 2022-05-02 19:26
> > > Hey @CortexTN 👋
> > > You might try to check out these two PRs (#33682 and #33707) and patch your local React Native to see if that helps. Whenever those PRs are merged, we plan to release another patch release `0.68.2`.
> > > In the meantime, if you could also provide reproducible steps, that would be fabulous.
> > > @mganandraj do you think this issue might be related to your PRs?
> > 
> > 
> > Yep, [PR#33707](https://github.com/facebook/react-native/pull/33707) should fix the build on Windows boxes with reasonable application root path.. But, as long as we use NDK21, we are still prone to issues with long file paths if the root path is long (>15 chars)..
> > [PR#33707](https://github.com/facebook/react-native/pull/33707) is currently blocked though because of complexities in bringing fixes to react-native-codegen package into stable branches.
> 
> I've tried patching my local react native with your changes and unfortunately it didn't work

Could you share the build logs ?

**Comment by CortexTN** [comment] 2022-05-02 19:29
> > > > Hey @CortexTN 👋
> > > > You might try to check out these two PRs (#33682 and #33707) and patch your local React Native to see if that helps. Whenever those PRs are merged, we plan to release another patch release `0.68.2`.
> > > > In the meantime, if you could also provide reproducible steps, that would be fabulous.
> > > > @mganandraj do you think this issue might be related to your PRs?
> > > 
> > > 
> > > Yep, [PR#33707](https://github.com/facebook/react-native/pull/33707) should fix the build on Windows boxes with reasonable application root path.. But, as long as we use NDK21, we are still prone to issues with long file paths if the root path is long (>15 chars)..
> > > [PR#33707](https://github.com/facebook/react-native/pull/33707) is currently blocked though because of complexities in bringing fixes to react-native-codegen package into stable branches.
> > 
> > I've tried patching my local react native with your changes and unfortunately it didn't work
> 
> Could you share the build logs ?

sure but not now, I'm outside doing some businesses, I'll mention the build logs as soon i back home (i may stay 3 hours outside)

**Comment by CortexTN** [comment] 2022-05-02 21:05
Hey @mganandraj 

This is the build log from gradle, i think that this what you meant by build log.
[build.txt](https://github.com/facebook/react-native/files/8606016/build.txt)

**Comment by CortexTN** [comment] 2022-05-02 23:58
@fortmarek the 0.69 release candidate one have a problem with most dependencies, an error like 
`warn Package @react-native-firebase/app has been ignored because it contains invalid configuration. Reason: "dependency.platforms.ios.scriptPhases[0]" must be a string
warn Package @react-native-firebase/crashlytics has been ignored because it contains invalid configuration. Reason: "dependency.platforms.ios.scriptPhases[0]" must be a string
warn Package react-native-vector-icons has been ignored because it contains invalid configuration. Reason: "dependency.assets" is not allowed`
and build failed because those dependencies are ignored, that's all.

**Comment by mganandraj** [comment] 2022-05-03 04:27
> 

@CortexTN You root directory is very long : "C:/Users/Administrator/Documents/GitHub/MoonMeet-CrossPlatform/"

log file suggests the build is failing while setting up the gdbserver, even before the compilation starts. Could you try creating th e project directly under "c:\". Also, use powershell for building, which supports longer command lines.

One more caveat: If you applied the changes in the above mentioned PR, make sure that you manually apply the changes in the android.mk in react-native-codegen.

**Comment by fortmarek** [comment] 2022-05-03 07:38
> the 0.69 release candidate one have a problem with most dependencies, an error like

If you could provide some more details and post them [here](https://github.com/reactwg/react-native-releases/discussions/21), somebody might be able to look into that 👍

**Comment by CortexTN** [comment] 2022-05-03 10:47
> > 
> 
> @CortexTN You root directory is very long : "C:/Users/Administrator/Documents/GitHub/MoonMeet-CrossPlatform/"
> 
> log file suggests the build is failing while setting up the gdbserver, even before the compilation starts. Could you try creating th e project directly under "c:\". Also, use powershell for building, which supports longer command lines.
> 
> One more caveat: If you applied the changes in the above mentioned PR, make sure that you manually apply the changes in the android.mk in react-native-codegen.

Tried this, but didn't work (tried without patching my local react native, kinda lazy to do so)

**Comment by CortexTN** [comment] 2022-05-03 10:48
> > the 0.69 release candidate one have a problem with most dependencies, an error like
> 
> If you could provide some more details and post them [here](https://github.com/reactwg/react-native-releases/discussions/21), somebody might be able to look into that 👍 

sorry sir, already downgraded yesterday

**Comment by CortexTN** [comment] 2022-05-03 11:38
> > > 
> > 
> > @CortexTN You root directory is very long : "C:/Users/Administrator/Documents/GitHub/MoonMeet-CrossPlatform/"
> > 
> > log file suggests the build is failing while setting up the gdbserver, even before the compilation starts. Could you try creating th e project directly under "c:\". Also, use powershell for building, which supports longer command lines.
> > 
> > One more caveat: If you applied the changes in the above mentioned PR, make sure that you manually apply the changes in the android.mk in react-native-codegen.
> 
> Tried this, but didn't work (tried without patching my local react native, kinda lazy to do so) 

I haven't found any Android.mk in react native codegen

**Comment by cortinico** [comment] 2022-05-03 14:54
> I'll wait for a stable fix like 0.68.2.

Yup we're still looking into how to build the New Architecture on Windows as the proposed fixes (i.e. #33707) haven't been confirmed yet.

**Comment by CortexTN** [comment] 2022-05-03 15:42
Yes with all respect to #33707 's owner, it doesn't fix my problem, anyway i'm using `0.68.1` on this open source project [MoonMeet](https://github.com/MoonMeet/MoonMeet-CrossPlatform) if you want to test changes or see if i did something wrong etc...

**Comment by mganandraj** [comment] 2022-05-03 19:01
> 
@CortexTN Unfortunately, Applying https://github.com/facebook/react-native/pull/33707 is still required to reduce the file path lengths to below windows limits, even after shortening the root path .. Yeah, it doesn't sound great :( The longer term solution is to upgrade NDK to r22 which doesn't have this long file path limit (If configured so through Windows registry) but we are seeing some intermittent crashes with r23. We are working on sorting it out !

**Comment by CortexTN** [comment] 2022-05-03 19:39
> > 
> @CortexTN Unfortunately, Applying https://github.com/facebook/react-native/pull/33707 is still required to reduce the file path lengths to below windows limits, even after shortening the root path .. Yeah, it doesn't sound great :( The longer term solution is to upgrade NDK to r22 which doesn't have this long file path limit (If configured so through Windows registry) but we are seeing some intermittent crashes with r23. We are working on sorting it out !

yeah i noticed the reduced file paths, but still some long paths, even trying all NDK versions `(21, 23, 24, I think those are the correct NDK versions)` and the PowerShell (both stock and 7.1 from Microsoft website), please mention me if you guys fix it!

**Comment by cortinico** [comment] 2022-05-04 10:21
> please mention me if you guys fix it!

Yesterday I was able to test #33707 and verify that is effectively fixing the issue, with NDK 21 + I needed a new release of `react-native-codegen` (which is something we'll have to do on the release branch as well).

**Comment by CortexTN** [comment] 2022-05-04 11:12
Hello Again.
please tell me when you fix react native codegen and tell me the steps (i mean what files to patch and what to add exactly on my local react native)
Thanks y'all.

**Comment by CortexTN** [comment] 2022-05-07 20:18
Hello Everyone, is there any news expected soon ?

**Comment by fortmarek** [comment] 2022-05-09 08:13
The fix should be a part of the `0.68.2` release, so follow the Github releases and let us know if you no longer see the issue on that version once it's out 🙂

**Comment by xy371661665** [comment] 2022-05-11 03:23
> @CortexTN have you been able to confirm that `0.68.2` works for you?

Hello, I have a same problem with 0.68.2.
NDK version is 21.4.7075529

**Comment by CortexTN** [comment] 2022-05-11 09:19
> > @CortexTN have you been able to confirm that `0.68.2` works for you?
> 
> @fortmarek 
> Hello, I have a same problem with 0.68.2.
> NDK version is 21.4.7075529 
> 

Hello, i didn't try it yet, still have some problems, i can't code at the moment, I'll try with different NDK version ASAP

**Comment by xy371661665** [comment] 2022-05-11 09:20
谢谢，已经收到你的邮件~~

**Comment by CortexTN** [comment] 2022-05-11 10:53
Hello again, i've been trying with different NDK Versions, and all failed on NDK build
here is some build logs:
### NDK 21
[NDK21.txt.txt](https://github.com/facebook/react-native/files/8669235/NDK21.txt.txt)
### NDK 23
[NDK23.txt.txt](https://github.com/facebook/react-native/files/8669243/NDK23.txt.txt)
### NDK 24
[NDK24.txt.txt](https://github.com/facebook/react-native/files/8669251/NDK24.txt.txt)

I hope you guys fix this ASAP, Thanks.

**Comment by fortmarek** [comment] 2022-05-11 15:58
@mganandraj are the persistent errors due to the current paths too long or is it indicative of the issue not being resolved?

**Comment by Elabar** [comment] 2022-05-11 17:21
@CortexTN Can you try to build with Windows Power Shell?
I had errors with bash/cmd as well. (Not sure if it is the same errors as yours)
But I had success with Power Shell.

**Comment by CortexTN** [comment] 2022-05-11 17:35
> @CortexTN Can you try to build with Windows Power Shell?
> I had errors with bash/cmd as well. (Not sure if it is the same errors as yours)
> But I had success with Power Shell.

VSCoduim default terminal use PowerShell

**Comment by CortexTN** [comment] 2022-05-11 17:38
> @mganandraj are the persistent errors due to the current paths too long or is it indicative of the issue not being resolved?

i think the issue is not being resolved, please see the logs, I can't see long paths, but something called `NDK_MODULE_PATH` isn't resolved and searched directories are null (" ")

**Comment by CortexTN** [comment] 2022-05-11 19:38
hello again, great news, new arch works on windows with fresh project, the problem is with my project, I'll do some workaround to see what's the bug on my project, Thanks all for your work

**Comment by CortexTN** [comment] 2022-05-11 21:50
[log.txt](https://github.com/facebook/react-native/files/8673645/log.txt)
getting this build log when trying to manage my project to work

**Comment by cortinico** [comment] 2022-05-11 22:32
Hey @CortexTN 
I've just tested 0.68.2 on a fresh project on Windows, and I can confirm it builds and works correctly.

The error you're experiencing is most likely related to dirtly build folder.
I would suggest you to clean up the project and try re-building

**Comment by kelset** [comment] 2022-05-12 11:37
hey folks, I just realised that this is technically a duplicate of https://github.com/facebook/react-native/issues/33528.
A few folks are also reporting there that 0.68.2 addresses the problem but only for fresh new apps. Let's close this and have the conversation progress there as it seems that now the ball is in the hands of the library maintainers to add new arch support.

**Closed by kelset** 2022-05-12 11:37 UTC
Labels: Platform: Windows, Platform: Android, Codegen, New Architecture

**Comment by linjson** [comment] 2022-05-19 05:36
> resh project o
 0.68.2 NewArch not work on Mac 11.6.5

**Comment by linjson** [comment] 2022-05-19 05:37
0.68.2 NewArch not work on Mac 11.6.5


> Hey @CortexTN I've just tested 0.68.2 on a fresh project on Windows, and I can confirm it builds and works correctly.
> 
> The error you're experiencing is most likely related to dirtly build folder. I would suggest you to clean up the project and try re-building

**Comment by cortinico** [comment] 2022-05-19 15:38
> 0.68.2 NewArch of Android not work on Mac 11.6.5

This issue is about Windows, not Mac. Please open another issue.
