### ISSUE TITLE
User Script Sandboxing Misconfigured in default React Native project

### ISSUE THREAD

**Issue by coolsoftwaretyler** [facebook/react-native#47228] opened 2024-10-27 19:14 UTC
### Description

When I attempt to follow the [Fabric Native Component guide in the React Native docs](https://reactnative.dev/docs/fabric-native-components-introduction), I encountered errors that look like:

```sh
error: Sandbox: rsync.samba(76606) deny(1) file-write-create /Users/tylerwilliams/Library/Developer/Xcode/DerivedData/PlainRN-dolxtgnoeodnpofjdcgzfoepsrdp/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/hermes-engine/Pre-built/hermes.framework/.Info.plist.PNqVDm (in target 'hermes-engine' from project 'Pods')
```

At first I thought this might come from setting up new groups in Xcode as per the directions. But I found this error is reproduced even after running:

```sh
npx @react-native-community/cli@latest init PlainRN
cd PlainRN
yarn run ios
```

I'm able to get the issue fixed if I change the setting through Xcode in the Pods project:

<img width="851" alt="Screenshot 2024-10-27 at 1 03 17 PM" src="https://github.com/user-attachments/assets/6063edf6-8985-4e17-801d-065e7b1fc228">

I'm filing this under the New Architecture bug report since it showed up first for me when trying to do Codegen for Fabric Native components, and the source of the error is coming from the ReactCodegen target in the Pods project. It's not entirely clear to me if this is a codegen issue or maybe some upstream problem with Cocoapods configuration. I found [some related issues in Cocoapods](https://github.com/CocoaPods/CocoaPods/issues/11946). I see in the `Gemfile` that some prior versions of Cocoapods are excluded:

```rb
gem 'cocoapods', '>= 1.13', '!= 1.15.0', '!= 1.15.1'
```

Perhaps we also need to exclude `1.15.2`, which is what you'll see in my `npx react-native info` output.

### Steps to reproduce

```sh
npx @react-native-community/cli@latest init PlainRN
cd PlainRN
yarn run ios
```

### React Native Version

0.76.0

### Affected Platforms

Build - MacOS

### Areas

Fabric - The New Renderer, Codegen

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.6
  CPU: (16) arm64 Apple M3 Max
  Memory: 78.09 MB / 48.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 22.9.0
    path: ~/.asdf/installs/nodejs/22.9.0/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.asdf/shims/yarn
  npm:
    version: 10.8.3
    path: ~/.asdf/plugins/nodejs/shims/npm
  Watchman:
    version: 2024.09.30.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/tylerwilliams/.asdf/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.0
      - iOS 18.0
      - macOS 15.0
      - tvOS 18.0
      - visionOS 2.0
      - watchOS 11.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.21829.142.2421.12409432
  Xcode:
    version: 16.0/16A242d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /usr/bin/javac
  Ruby:
    version: 3.3.4
    path: /Users/tylerwilliams/.asdf/shims/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.0-alpha.2
    wanted: 15.0.0-alpha.2
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.0
    wanted: 0.76.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
▸ Compiling bignum-dtoa.cc
▸ Running script '[CP] Copy XCFrameworks'

❌  error: Sandbox: rsync.samba(76606) deny(1) file-write-create /Users/tylerwilliams/Library/Developer/Xcode/DerivedData/PlainRN-dolxtgnoeodnpofjdcgzfoepsrdp/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/hermes-engine/Pre-built/hermes.framework/.Info.plist.PNqVDm (in target 'hermes-engine' from project 'Pods')



❌  error: Sandbox: rsync.samba(76606) deny(1) file-write-create /Users/tylerwilliams/Library/Developer/Xcode/DerivedData/PlainRN-dolxtgnoeodnpofjdcgzfoepsrdp/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/hermes-engine/Pre-built/hermes.framework/.hermes.dFI84M (in target 'hermes-engine' from project 'Pods')


▸ Compiling DebugStringConvertibleItem.cpp
▸ Compiling DebugStringConvertible.cpp
▸ Touching glog_privacy.bundle (in target 'glog-glog_privacy' from project 'Pods')
▸ Touching boost_privacy.bundle (in target 'boost-boost_privacy' from project 'Pods')
▸ Compiling react_native_log.cpp
▸ Compiling ReactPerfettoCategories.cpp
▸ Compiling ReactPerfetto.cpp
▸ Compiling HermesPerfettoDataSource.cpp
▸ Compiling FuseboxTracer.cpp
▸ Compiling BridgeNativeModulePerfLogger.cpp
    Run script build phase '[CP-User] [Hermes] Replace Hermes for the right configuration, if needed' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'hermes-engine' from project 'Pods')
    Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'PlainRN' from project 'PlainRN')
    Run script build phase '[CP-User] [RN]Check rncore' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-FabricComponents' from project 'Pods')
    Run script build phase '[CP-User] [RN]Check rncore' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-Fabric' from project 'Pods')

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor

error Failed to build ios project. "xcodebuild" exited with error code '65'. To debug build logs further, consider building your app with Xcode.app, by opening 'PlainRN.xcworkspace'.
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Reproducer

https://github.com/coolsoftwaretyler/reproducer-user-sandbox-error

### Screenshots and Videos

<img width="1384" alt="Screenshot 2024-10-27 at 1 06 47 PM" src="https://github.com/user-attachments/assets/e307369e-ab53-446b-a28e-7554903d1012">

**Comment by coolsoftwaretyler** [comment] 2024-10-27 19:18
I tried forcing Cocoapods to version `1.14.3`, but there was no change in outcome.

**Comment by cipolleschi** [comment] 2024-10-27 19:58
Interesting... this should not happen with a new app created with the template.
Instead, it happens if you create a regular iOS project and you add React Native later.

In this case, we highlighted that step [here](https://reactnative.dev/docs/integration-with-existing-apps?language=apple#:~:text=Make%20sure%20to%20disable%20the%20Sandbox%20scripting) in the **Integrating with Existing Apps** guide.

**Comment by cipolleschi** [comment] 2024-10-27 20:00
Which version of Xcode are you using?

**Comment by JorenVos** [comment] 2024-10-27 21:11
Dealing with exactly the same issue using Xcode 15.4 and Cocoapods versions 1.15.2. The `Pods` project gets `User Script Sandboxing` defaulting to `YES` (every `pod install` reverts this setting to the default `YES`-value). 

(_After setting this value to `NO`, I get `double-quoted include "NSRunLoop+SRWebSocket.h" in framework header, expected angle-bracketed instead` in a lot of dependencies_)

**Comment by coolsoftwaretyler** [comment] 2024-10-27 21:21
I'm on Xcode 16.0/16A242d

I'll try a new Expo project and then a CLI project with version 0.75 and see if I run into the same problems.

Will report back shortly.

**Comment by coolsoftwaretyler** [comment] 2024-10-27 21:46
With `npx create-expo-app@latest`, the Expo Go app works fine. 

Then I ran:
```sh
npx expo prebuild
cd ios 
open testappforuserpermissions.xcworkspace/
```

Building that from Xcode worked as expected.

Here is the `npx react-native info` output for that test run:

```sh
System:
  OS: macOS 14.6
  CPU: (16) arm64 Apple M3 Max
  Memory: 229.86 MB / 48.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 22.9.0
    path: ~/.asdf/installs/nodejs/22.9.0/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.asdf/shims/yarn
  npm:
    version: 10.8.3
    path: ~/.asdf/plugins/nodejs/shims/npm
  Watchman:
    version: 2024.09.30.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/tylerwilliams/.asdf/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.0
      - iOS 18.0
      - macOS 15.0
      - tvOS 18.0
      - visionOS 2.0
      - watchOS 11.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.21829.142.2421.12409432
  Xcode:
    version: 16.0/16A242d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /usr/bin/javac
  Ruby:
    version: 3.3.4
    path: /Users/tylerwilliams/.asdf/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

Will try a CLI project on 0.75.x next.

**Comment by coolsoftwaretyler** [comment] 2024-10-27 21:50
Then I ran `npx @react-native-community/cli@latest init cltesterrepro --version 0.75.4`. I chose to install CocoaPods during the installation step.

Afterwards, ran:

```
cd cltesterrepro/
yarn run ios
```

That got me similar errors:

```
❌  error: Sandbox: rsync.samba(65050) deny(1) file-write-create /Users/tylerwilliams/Library/Developer/Xcode/DerivedData/cltesterrepro-cpwbxfxdtusuovdkysvmogtxkpar/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/hermes-engine/Pre-built/hermes.framework/.Info.plist.gFDtzk (in target 'hermes-engine' from project 'Pods')



❌  error: Sandbox: rsync.samba(65050) deny(1) file-write-create /Users/tylerwilliams/Library/Developer/Xcode/DerivedData/cltesterrepro-cpwbxfxdtusuovdkysvmogtxkpar/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/hermes-engine/Pre-built/hermes.framework/.hermes.ucZRDV (in target 'hermes-engine' from project 'Pods')
```

Same build failures when running via Xcode.

Perhaps this is a problem with `@react-native-community/cli` and not React Native.

**Comment by coolsoftwaretyler** [comment] 2024-10-27 21:53
Ran:

```sh
npx @react-native-community/cli@14.1.0 init olderclitest --version 0.75.4
# Selected Yes to install CocoaPods during setup
cd olderclitest/
npx react-native run-ios
```

Similar errors:

```sh
❌  error: Sandbox: rsync.samba(75818) deny(1) file-write-create /Users/tylerwilliams/Library/Developer/Xcode/DerivedData/olderclitest-fpvnjkwfdzckavetrxxfbiticefi/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/hermes-engine/Pre-built/hermes.framework/.Info.plist.wFiuSv (in target 'hermes-engine' from project 'Pods')



❌  error: Sandbox: rsync.samba(75818) deny(1) file-write-create /Users/tylerwilliams/Library/Developer/Xcode/DerivedData/olderclitest-fpvnjkwfdzckavetrxxfbiticefi/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/hermes-engine/Pre-built/hermes.framework/.hermes.1y2kb2 (in target 'hermes-engine' from project 'Pods')
```

Maybe it's an environment thing, although it's strange that Expo worked fine, even while building with Xcode.

**Comment by Jensileus** [comment] 2024-10-27 21:58
I have the exact same problem.

**Comment by dentemm** [comment] 2024-10-28 08:25
Same problem, but I cannot bypass since `ENABLE_USER_SCRIPT_SANDBOXING` is already disabled

**Comment by hoangdoanfinx** [comment] 2024-10-28 08:41
same problem to my Github Action Runner, I can still build the app from manually from my machine.

**Comment by JorenVos** [comment] 2024-10-28 08:53
> Same problem, but I cannot bypass since `ENABLE_USER_SCRIPT_SANDBOXING` is already disabled

Maybe `ENABLE_USER_SCRIPT_SANDBOXING` is enabled in your Pods-project?

**Comment by Jensileus** [comment] 2024-10-28 08:55
I can just speak for myself, but i deleted and re-installed pods again. So how can that happen? And also, mine is totally new - i did not do anything else then making a React-Native app. So just for checking what was wrong with my "old" since that had the same problem I started a new one. And it automatically have the same problem?

**Comment by hoangdoanfinx** [comment] 2024-10-28 08:56
> > Same problem, but I cannot bypass since `ENABLE_USER_SCRIPT_SANDBOXING` is already disabled
> 
> Maybe `ENABLE_USER_SCRIPT_SANDBOXING` is enabled in your Pods-project?

all my targets are disabled `ENABLE_USER_SCRIPT_SANDBOXING` but it did not work

**Comment by dentemm** [comment] 2024-10-28 09:01
Came across RN-Reanimated's action runners, which have been failing since yesterday as well. Currently upgrading Xcode and will try some things afterwards

https://github.com/software-mansion/react-native-reanimated/actions/runs/11543283561

**Comment by dentemm** [comment] 2024-10-28 09:05
> > Same problem, but I cannot bypass since `ENABLE_USER_SCRIPT_SANDBOXING` is already disabled
> 
> Maybe `ENABLE_USER_SCRIPT_SANDBOXING` is enabled in your Pods-project?

Good suggestion, but didn't work

**Comment by Jensileus** [comment] 2024-10-28 09:15
It's started yesterday as well. it worked saturday, but yesterday problems all over with rsync.sandbox.

**Comment by krystofwoldrich** [comment] 2024-10-28 10:02
I got the same issue,
after disabling scripts sandboxing for Pods.

I'm getting errors from [`replace-hermes-version.js`](https://github.com/facebook/react-native/blob/2e2f8a668907552070a2a53a47137b1449b66bbd/packages/react-native/sdks/hermes-engine/utils/replace_hermes_version.js#L60)

```
Node found at: /Users/krystofwoldrich/.nvm/versions/node/v20.15.0/bin/node
Preparing the final location
/Users/krystofwoldrich/repos/react-native-versions/0.76.0/RnDiffApp/ios/Pods
Extracting the tarball
tar: Error opening archive: Failed to open '/Users/krystofwoldrich/repos/react-native-versions/0.76.0/RnDiffApp/ios/Pods/hermes-engine-artifacts/hermes-ios-0.76.0-release.tar.gz'
node:child_process:965
    throw err;
    ^

Error: Command failed: tar -xf /Users/krystofwoldrich/repos/react-native-versions/0.76.0/RnDiffApp/ios/Pods/hermes-engine-artifacts/hermes-ios-0.76.0-release.tar.gz -C hermes-engine
tar: Error opening archive: Failed to open '/Users/krystofwoldrich/repos/react-native-versions/0.76.0/RnDiffApp/ios/Pods/hermes-engine-artifacts/hermes-ios-0.76.0-release.tar.gz'
```

**Comment by helloagain-dev** [comment] 2024-10-28 10:28
in our case, the problem is related to the latest release of xcodeproj (1.26.0) ruby library
https://github.com/CocoaPods/Xcodeproj/releases/tag/1.26.0
pinning it to 1.25 in gem file should fix the issue for now

`gem 'xcodeproj', '1.25.1'`

**Comment by cipolleschi** [comment] 2024-10-28 10:36
Yes, our CI is red as well.
As @helloagain-dev mentioned, Xcodeproj released yesterday and that broke the build for almost everyone.

I'll pin the gem to the right value in the Gemfile, we will release 0.76.1 today.

cc. @blakef @cortinico 
--
@krystofwoldrich I don't think that the two are related. The sandbox scripting prevents for scripts to run. In your error, the script is running but it fails to open the tarball. So you might missing the tarball or there might be something else going on.

**Comment by dentemm** [comment] 2024-10-28 10:36
@helloagain-dev great find, works like a charm 👏

**Comment by cipolleschi** [comment] 2024-10-28 10:42
Opened a issue here: https://github.com/CocoaPods/Xcodeproj/issues/989

**Comment by krystofwoldrich** [comment] 2024-10-28 10:46
@cipolleschi Thanks, yes, it was unrelated. Cleaning my `Pods` and rerunning `pod install` downloaded the tarballs.

**Comment by hoangdoanfinx** [comment] 2024-10-28 11:10
@cipolleschi thanks, you saved my life

**Comment by migueldaipre** [comment] 2024-10-28 13:05
Fixed in #47237

**Comment by SwetaTanwar** [comment] 2024-10-28 13:06
Able to able to unblock with the same error by explicitly setting the flag as NO in podfile

```
installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      end
end
```

**Closed** 2024-10-28 14:47 UTC
Labels: Resolution: PR Submitted, Type: New Architecture

**Comment by kiki-eng** [comment] 2024-10-28 23:30
Hello everyone, i want to know if this is some sort of new problem, i only push my latest update to github yesterday and since then have been experiencing this error  Sandbox: mkdir(19746) deny(1) file-write-create /Users/olawaleabosede/Library/Developer/Xcode/DerivedData/My750hrstracker-erjbkgyqqlopoegusonsambuhznx/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-rncore.build/DerivedSources/generated
have done everything suggested by AI nothing is working

**Comment by iameli** [comment] 2024-10-29 00:30
For anyone like me whose CI environment upgraded underneath you and broke your RN builds, this gets the job done:
```
sudo gem uninstall xcodeproj -x --ignore-dependencies
sudo gem install xcodeproj -v 1.25.1
```
I didn't have a Gemfile in the repo at all so that approach didn't help me much.

**Comment by kigh143** [comment] 2024-10-29 05:29
> in our case, the problem is related to the latest release of xcodeproj (1.26.0) ruby library https://github.com/CocoaPods/Xcodeproj/releases/tag/1.26.0 pinning it to 1.25 in gem file should fix the issue for now
> 
> `gem 'xcodeproj', '1.25.1'`

This worked for me thank you.

**Comment by krystofwoldrich** [comment] 2024-10-29 09:17
Updating to `Cocoapods 1.16.0` https://github.com/CocoaPods/CocoaPods/releases/tag/1.16.0 also fixes the issue.

From the changelog:
> Update project generator to set ENABLE_USER_SCRIPT_SANDBOXING = NO = NO` on pod targets to fix build failures with vendored frameworks.

**Comment by alexma01** [comment] 2024-10-29 15:19
@krystofwoldrich I can confirm that with CocoaPods 1.6.1, it works!

**Comment by ko100v-xgt** [comment] 2024-10-29 16:35
@alexma01 can you provide your Gemfile? Did you remove gem 'xcodeproj', '< 1.26.0' and set gem cocoapods, 1.6.1?

**Comment by vladimirevstratov** [comment] 2024-10-29 20:30
> sudo gem uninstall xcodeproj -x --ignore-dependencies
> sudo gem install xcodeproj -v 1.25.1

thank you, this helps with cocoapods version 1.15.2

**Comment by SaadBinWaheed-og** [comment] 2024-10-29 20:51
Added both these files in my Gemfile but same error:

```
gem 'cocoapods', '1.16.0'
gem 'xcodeproj', '1.25.1'
```

**Comment by joaogabriellima** [comment] 2024-10-29 21:06
@SaadBinWaheed-og cocoapods [1.16](https://github.com/CocoaPods/CocoaPods/releases/tag/1.16.0) requires xcodeproj 1.26, here we solved adding this line on the gemfile:

`gem 'cocoapods', '=1.16.0'`

**Comment by banananeer** [comment] 2024-10-30 12:19
> sudo gem install xcodeproj -v 1.25.1

You are a legend. This worked for me. Thank you!

**Comment by habtamu** [comment] 2024-10-30 13:25
uninstalling xcodeproj version 1.26.0 works for me.

**Comment by jeremiahlachica** [comment] 2024-10-30 14:13
xcodeproj-1.25.1 works for me.

I had to uninstall all versions using:
`gem uninstall xcodeproj`

Then install 1.25.1:
`sudo gem install xcodeproj -v 1.25.1`

**Comment by cipolleschi** [comment] 2024-10-31 15:17
1.25.x is fine.
1.26 only works with version 1.16 of Cocoapods.

**Comment by saminium** [comment] 2024-11-01 03:54
> 1.16

Thanks

**Comment by chohra-med** [comment] 2024-11-01 20:08
updating the Pod version to the latest fix the issue

```
sudo gem update --system
sudo gem install cocoapods
```
