### ISSUE TITLE
Cyclic dependency returns empty object

### ISSUE THREAD

**Issue by jorilallo** [facebook/react-native#3298] opened 2015-10-09 05:50 UTC
http://stackoverflow.com/questions/29807664/cyclic-dependency-returns-empty-object-in-react-native

I ran into above issue myself when I accidentally tried to require module A from module B which accidentally had the A also required (not to be confued with navigation issue on #3076). It took some head scratching to determine why the object came back as empty so ideally a warning would be raised when accidentally (or purposefully) doing this.

**Comment by ide** [comment] 2015-10-09 05:53
There might not be a fix for this if it's intended behavior. I believe this is how the module spec works and could be an issue with CommonJS more than React Native. I would be interested to see how other require systems handle this.

**Comment by satya164** [comment] 2015-10-09 06:31
Same thing happens in Node also.

**Comment by ide** [comment] 2015-10-11 11:15
Looking at ES6 modules I believe they behave similarly. I'll close this issue since it's how JavaScript works.

**Closed by ide** 2015-10-11 11:15 UTC
Labels: JS

**Comment by mhofman** [comment] 2016-10-18 18:00
Actually, cyclical dependencies in CommonJS are allowed in some circumstances:

See https://github.com/systemjs/systemjs/issues/136 for more details.

I'm currently running into the exact same scenario with a 3rd party library that cannot easily be modified to do lazy loading or dependency injection. React-native's loader should support all the CommonJS use cases.

I'll try to make a PR with a fix.
