### ISSUE TITLE
There is a Bug about TextInput on version 0.54.0 on iOS Device

### ISSUE THREAD

**Issue by yang-haofeng** [facebook/react-native#19362] opened 2018-05-21 03:14 UTC
I want to control and change inputing text  in 'onChangeText' method, but it is no useful on version 0.54.0, and I have bind TextInput 'value' property to a state value. however It work normal on 0.44.3 version before.

**Comment by vovkasm** [comment] 2018-05-21 22:49
Duplicate of #18874

**Closed** 2018-05-24 00:00 UTC
Labels: :clipboard:No Template, :large_blue_diamond:iOS, :large_orange_diamond:TextInput, Ran Commands
