### ISSUE TITLE
fetch() API doesn't allow a timeout?

### ISSUE THREAD

**Issue by niftylettuce** [facebook/react-native#3876] opened 2015-11-04 01:19 UTC
I'd like to set a timeout before "Network error" occurs.  What's the easiest way  to do this?  Some setTimeout that throws some sort of error?  Has anyone done this or has the docs for it?

**Comment by niftylettuce** [comment] 2015-11-04 01:20
e.g. I test with my API server turned off... I don't want the spinning progress bar I have to keep going for minutes, I want to give it a limit, like 10 seconds for my server to respond before I trigger a modal with the error

**Comment by cancan101** [comment] 2015-11-04 04:42
See also: https://github.com/whatwg/fetch/issues/20

**Comment by pangers** [comment] 2015-11-04 11:44
I'm not sure whether fetch has a timeout function. After a quick skim of the link by @cancan101 it doesn't seem like there is one.

However it sounds like something that RxJS might be able to solve. Check out this operator.
https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/timeout.md

**Comment by brentvatne** [comment] 2015-11-15 19:27
Dupe of some closed issues before. It doesn't support this yet but there are some hand-rolled solutions in the link that @cancan101 shared above, or something like RxJS would also work well here :)

**Closed by brentvatne** 2015-11-15 19:27 UTC

**Comment by adambene** [comment] 2017-02-28 18:16
dupe #2556
