### ISSUE TITLE
react-native init testProject always fails with unexpected token.

### ISSUE THREAD

**Issue by Rohit-shopasky** [facebook/react-native#15040] opened 2017-07-16 18:18 UTC
Installing react-native...
Consider installing yarn to make this faster: https://yarnpkg.com
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN react-native@0.46.3 requires a peer of react@16.0.0-alpha.12 but none was installed.

added 570 packages in 68.157s
c:\and\test\node_modules\metro-bundler\build\lib\TerminalClass.js:141
    this._nextStatusStr = util.format(format, ...args);
                                              ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (c:\and\test\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (c:/and/test/node_modules/react-native/local-cli/server/runServer.js:18:18)
    at Module._compile (module.js:409:26)

**Comment by deepax11** [comment] 2017-07-16 20:52
I am facing the same problem from last days and tried all possible solution mentioned on stack over flow + GitHub. This is the first time I am trying to learn React Native. Can some one add some more idea?

**Comment by hramos** [comment] 2017-07-17 14:46
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-07-17 14:46 UTC

**Comment by Rohit-shopasky** [comment] 2017-07-17 16:45
I am also new to react native. I followed following steps while installing react-native 

1. I have installed Nodejs, Python2 , JDK, Android studio.
2.  After that i run the following command from cmd `npm install -g react-native-cli`
3.  It shows me successfully added 41 packages.
4.  When i typed `react-native init AwesomeProject` in cmd it doesn't do anything. Command prompt does not shows me anything. It just ready for taking another command

**Comment by yandan66** [comment] 2017-07-20 14:26
Very similar problem for me yesterday. And I had resolved it by upgrade my node.js version to v6.11.1.

**Comment by junibrosas** [comment] 2017-07-23 16:09
Currently it works for me with node v8.

Update node version on macOS.
sudo npm cache clean -f
sudo npm install -g n
sudo n stable

**Comment by syed-haroon** [comment] 2017-07-23 17:05
Assuming that you are using `nvm` and multiple versions of node installed, here is the solution:

 1. Say that you run `npm install -g react-native-cli` in `v6.9.5`.  
 2. Now make `v6.9.5` as default by running `nvm alias default 6.9.5`
 3. Now run `react-native run-ios`

The problem is, you have multiple versions of node installed via `nmp` and to install `react-native-cli` you have switched or installed latest version of node, which is not marked as default node to point in `nvm` yet. When you run `react-native run-ios` this opens up another new terminal window in which default `nvm` is not pointed to the node version where you have installed `react-native-cli`. Just follow the above setup, I hope that should help.  

Answered the same here: https://stackoverflow.com/a/45267703/1292050

**Comment by russelh15** [comment] 2017-08-02 02:42
^ Aliasing solved the issue for me

Thanks @syed-haroon !

**Comment by cxlbus** [comment] 2017-08-09 04:08
I have the same problem

**Comment by russelh15** [comment] 2017-08-09 13:45
@cxlbus Which Node version are you using? Are you using NVM?

**Comment by monlyu** [comment] 2017-08-18 01:22
my package.json is 

`{
  "name": "RNBBS",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.0",
    "react-native-material-kit": "^0.4.1"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "3.0.0",
    "jest": "20.0.4",
    "react-test-renderer": "16.0.0-alpha.6"
  },
  "jest": {
    "preset": "react-native"
  }
}`

I last found some error in babel-preset-react-native

fixed this js file at node_modules/babel-preset-react-native/configs/main.js

line 22 - 38 

remove the last ','


` 
 plugins.push (
    'syntax-class-properties',
    'syntax-trailing-function-commas',
    'transform-class-properties',
    'transform-es2015-block-scoping',
    'transform-es2015-computed-properties',
    'transform-es2015-destructuring',
    'transform-es2015-function-name',
    'transform-es2015-literals',
    'transform-es2015-parameters',
    'transform-es2015-shorthand-properties',
    'transform-flow-strip-types',
    'transform-react-jsx',
    'transform-regenerator',
    require('../transforms/transform-regenerator-runtime-insertion'),
    ['transform-es2015-modules-commonjs', {strict: false, allowTopLevelThis: true}]
  );
`
