### ISSUE TITLE
app crash and can't open after installing from play store

### ISSUE THREAD

**Issue by sharifashraful** [facebook/react-native#32325] opened 2021-10-03 13:41 UTC
Type
java.lang.RuntimeException
java.lang.RuntimeException: 
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:7532)
  at android.app.ActivityThread.access$1400 (ActivityThread.java:301)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2150)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8587)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
Caused by: java.lang.RuntimeException: 
  at com.facebook.soloader.SoLoader.init (SoLoader.java:12)
  at com.reactnativenavigation.NavigationApplication.onCreate (NavigationApplication.java:6)
  at com.pathabo.MainApplication.onCreate (MainApplication.java)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1192)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:7527)
  at android.app.ActivityThread.access$1400 (ActivityThread.java:301)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2150)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8587)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
Caused by: java.io.FileNotFoundException: 
  at libcore.io.IoBridge.open (IoBridge.java:492)
  at java.io.FileOutputStream.<init> (FileOutputStream.java:236)
  at java.io.FileOutputStream.<init> (FileOutputStream.java:186)
  at com.facebook.soloader.FileLocker.<init> (FileLocker.java:5)
  at com.facebook.soloader.FileLocker.lock (FileLocker.java:2)
  at com.facebook.soloader.UnpackingSoSource.prepare (UnpackingSoSource.java:22)
  at com.facebook.soloader.SoLoader.initSoSources (SoLoader.java:390)
  at com.facebook.soloader.SoLoader.init (SoLoader.java:13)
  at com.facebook.soloader.SoLoader.init (SoLoader.java:1)
  at com.facebook.soloader.SoLoader.init (SoLoader.java:5)
  at com.reactnativenavigation.NavigationApplication.onCreate (NavigationApplication.java:6)
  at com.pathabo.MainApplication.onCreate (MainApplication.java)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1192)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:7527)
  at android.app.ActivityThread.access$1400 (ActivityThread.java:301)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2150)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8587)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
Caused by: android.system.ErrnoException: 
  at libcore.io.Linux.open (Native Method)
  at libcore.io.ForwardingOs.open (ForwardingOs.java:166)
  at libcore.io.BlockGuardOs.open (BlockGuardOs.java:254)
  at libcore.io.ForwardingOs.open (ForwardingOs.java:166)
  at android.app.ActivityThread$AndroidOs.open (ActivityThread.java:8448)
  at libcore.io.IoBridge.open (IoBridge.java:478)
  at java.io.FileOutputStream.<init> (FileOutputStream.java:236)
  at java.io.FileOutputStream.<init> (FileOutputStream.java:186)
  at com.facebook.soloader.FileLocker.<init> (FileLocker.java:5)
  at com.facebook.soloader.FileLocker.lock (FileLocker.java:2)
  at com.facebook.soloader.UnpackingSoSource.prepare (UnpackingSoSource.java:22)
  at com.facebook.soloader.SoLoader.initSoSources (SoLoader.java:390)
  at com.facebook.soloader.SoLoader.init (SoLoader.java:13)
  at com.facebook.soloader.SoLoader.init (SoLoader.java:1)
  at com.facebook.soloader.SoLoader.init (SoLoader.java:5)
  at com.reactnativenavigation.NavigationApplication.onCreate (NavigationApplication.java:6)
  at com.pathabo.MainApplication.onCreate (MainApplication.java)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1192)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:7527)
  at android.app.ActivityThread.access$1400 (ActivityThread.java:301)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2150)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8587)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)

E:\mobile apps\Pathabo>react-native info
info Fetching system and libraries information...
(node:7596) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
    Memory: 8.38 GB / 15.91 GB
  Binaries:
    Node: 14.16.0 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.11 - D:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 21, 23, 25, 26, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
      System Images: android-21 | ARM EABI v7a, android-21 | Intel x86 Atom, android-21 | Google APIs ARM EABI v7a, android-21 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_111
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.65.1 => 0.65.1
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by sharifashraful** [comment] 2021-10-03 15:19
info Fetching system and libraries information...
(node:7596) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use node --trace-warnings ... to show where the warning was created)
System:
OS: Windows 10 10.0.18362
CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
Memory: 8.38 GB / 15.91 GB
Binaries:
Node: 14.16.0 - D:\Program Files\nodejs\node.EXE
Yarn: 1.15.2 - ~\AppData\Roaming\npm\yarn.CMD
npm: 6.14.11 - D:\Program Files\nodejs\npm.CMD
Watchman: Not Found
SDKs:
Android SDK:
API Levels: 21, 23, 25, 26, 28, 29, 30
Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
System Images: android-21 | ARM EABI v7a, android-21 | Intel x86 Atom, android-21 | Google APIs ARM EABI v7a, android-21 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
Android NDK: Not Found
Windows SDK: Not Found
IDEs:
Android Studio: Not Found
Visual Studio: Not Found
Languages:
Java: 1.8.0_111
npmPackages:
@react-native-community/cli: Not Found
react: 17.0.2 => 17.0.2
react-native: 0.65.1 => 0.65.1
react-native-windows: Not Found
npmGlobalPackages:
react-native: Not Found

**Comment by kimihiro64** [comment] 2021-11-11 00:39
This is fixed in soloader 0.10.3, as mentioned in [facebook/SoLoader#74](https://github.com/facebook/SoLoader/issues/74). We have over 5k crashes caused by this. As a workaround, clearing storage and restarting the app will bypass the crash.

**Closed** 2022-01-20 14:21 UTC
Labels: Needs: Environment Info, Needs: Attention
