### ISSUE TITLE
React Native Dev tool lauching error

### ISSUE THREAD

**Issue by varunajmera0** [facebook/react-native#17910] opened 2018-02-08 14:17 UTC
I am requesting to launch dev tool but it forwards to http://10.0.2.2:8081/debugger-ui

![](https://user-images.githubusercontent.com/22893376/35977215-7333c6a2-0d08-11e8-9e15-2fa6d56b8f29.png)

![](https://user-images.githubusercontent.com/22893376/35977177-59624d66-0d08-11e8-92c5-70f0f8b6a565.png)

![](https://user-images.githubusercontent.com/22893376/35977064-18719c94-0d08-11e8-8f9e-8ff605caad12.png)

**Comment by blazergame** [comment] 2018-02-08 16:12
@varunajmera0 try killing the process of your browser and emulator. Run ```adb kill-server``` to remove your attached devices. Restart your emulator and rerun the remote debugger. The remote debugger should be pointing to your `localhost:8081/debugger-ui`

**Comment by varunajmera0** [comment] 2018-02-08 17:45
it has never happened before @blazergame

**Comment by blazergame** [comment] 2018-02-08 17:52
I had a similar issue last night. It seems like the emulator is connecting to an old debugger session. By resetting that connection, it'll create a new connection to reconnect with. If that didn't work, it might be something else that I'm not too sure of.

**Comment by varunajmera0** [comment] 2018-02-09 11:42
I have just deployed one app with   "react-native": "0.52.2". It doesn't happen with this version (  "react-native": "0.52.2"). It is happening only with   "react-native": "0.53.0".

**Comment by hramos** [comment] 2018-02-09 20:42
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue that meets the requirements set forth in the template. Thanks!

**Closed by hramos** 2018-02-09 20:42 UTC
Labels: Failed Commands

**Comment by varunajmera0** [comment] 2018-02-10 05:50
What kind of description is missing or list of reproduction steps?
Your Dev tool is not launching.

**Comment by varunajmera0** [comment] 2018-02-10 05:52
See again, every time I have to write manually this http://localhost:8081/debugger-ui/
![image](https://user-images.githubusercontent.com/22893376/36059001-8456c09a-0e54-11e8-8575-7eebe0a48f1d.png)

**Comment by Dimous** [comment] 2018-02-10 07:57
@blazergame is right! Just now had the same problem (tahts why I'm here) and solved it by killing adb server, wiping user data in emulator and restarting.

**Comment by vladp** [comment] 2018-04-08 23:14
I have same issue with 0.54. 
Why is react-native bridge asking Chrome to access  http://10.0.2.2:8081/debugger-ui
?
this is an internal address within emulator and will not be accessible by chrome.

Not clear why this issue is closed, has it been resolved or is this a user error?

**Comment by varunajmera0** [comment] 2018-04-09 04:25
@vladp they won't give any response. Before 0.54, I didn't get that error.

**Comment by ichoubrahim** [comment] 2018-04-24 12:34
Try to access the debugger with your local address : http://127.0.0.1:8081/debugger-ui/ because 10.0.x.x is not accessible by chrome.

**Comment by devmrin** [comment] 2018-05-17 08:36
Solved the issue for me following:

Press Cmd + M on emulator screen
Go to Dev settings > Debug server host & port for device
Set localhost:8081
Rerun the android app: react-native run-android
Debugger is connected now!

**Comment by chenUT** [comment] 2018-05-17 16:32
@devmrin 's solution works for me. Thanks.

**Comment by YogendraShelke** [comment] 2018-06-06 07:41
Use actual device for debugging

**Comment by mohammadse2** [comment] 2018-07-04 06:43
The solution by  devmrin commented on May 17  works for me too

**Comment by Johncy1997** [comment] 2018-08-27 09:02
@devmrin solution will work.

**Comment by aswinaryal** [comment] 2018-09-03 12:08
the perfect solution for this issue is:
Press `Cmd + M`
Go to Dev Settings and under Debugging menu click 
> Debug server host & port for device
Set it to 
`localhost: 8081`.
Reload the app.
