### ISSUE TITLE
React Native : App crashes in samsung devices

### ISSUE THREAD

**Issue by keerthanarbt** [facebook/react-native#12466] opened 2017-02-20 04:48 UTC
Hi,
Error message:
react.uimanager.ReactShadowNode.setStyleWidth(float)' on a null object reference

com.facebook.react.uimanager.UIImplementation.updateNodeSize (UIImplementation.java:151)
com.facebook.react.uimanager.UIManagerModule.updateNodeSize (UIManagerModule.java:213)
com.facebook.react.views.modal.ReactModalHostView$DialogRootViewGroup$1.run (ReactModalHostView.java:302)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (MessageQueueThreadHandler.java:31)
android.os.Looper.loop (Looper.java:158)
com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run (MessageQueueThreadImpl.java:196)
java.lang.Thread.run (Thread.java:818)

please help us with the same..with some example codes..

**Comment by brentvatne** [comment] 2017-02-22 23:32
Hello! Closing because we can't reproduce without some code.

**Closed by brentvatne** 2017-02-22 23:32 UTC
