### ISSUE TITLE
npm start failed

### ISSUE THREAD

**Issue by nikhilmandalia** [facebook/react-native#12470] opened 2017-02-20 07:41 UTC
19 error node v7.5.0
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error myapp@0.1.0 start: `webpack-dev-server --hot`
22 error Exit status 1
23 error Failed at the myapp@0.1.0 start script 'webpack-dev-server --hot'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the myapp package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-dev-server --hot
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs myapp
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls myapp
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by nikhilmandalia** [comment] 2017-02-21 11:05
if anybody could resolve above issue?

**Comment by hramos** [comment] 2017-02-21 21:33
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-02-21 21:33 UTC

**Comment by nikhilmandalia** [comment] 2017-02-22 14:33
I do not think description is mandatory field , not sure but created separated folder and install require lib except ***-cli and then it was working.

anyways thanks to look into this issue
