### ISSUE TITLE
ReactNativeRenderer.mountSafeCallback throws isMounted() deprecation errors 

### ISSUE THREAD

**Issue by EdwardDrapkin** [facebook/react-native#18927] opened 2018-04-18 20:33 UTC
Hi there, 

I'm getting a handful of isMounted deprecation errors since upgrading to 0.55.3.  

The stack trace looks like this:

```

  | console.warn | @ | YellowBox.js:80
  | printWarning | @ | react.development.js:88
  | lowPriorityWarning | @ | react.development.js:107
  | get | @ | react.development.js:272
  | (anonymous) | @ | ReactNativeRenderer-dev.js:3518
  | __invokeCallback | @ | MessageQueue.js:398
  | (anonymous) | @ | MessageQueue.js:137
  | __guardSafe | @ | MessageQueue.js:314
  | invokeCallbackAndReturnFlushedQueue | @ | MessageQueue.js:136
  | (anonymous) | @ | debuggerWorker.js:70

```

The function in question looks like this right now:

```
/**
 * In the future, we should cleanup callbacks by cancelling them instead of
 * using this.
 */
function mountSafeCallback(context, callback) {
  return function() {
    if (!callback) {
      return undefined;
    }
    if (typeof context.__isMounted === "boolean") {
      // TODO(gaearon): this is gross and should be removed.
      // It is currently necessary because View uses createClass,
      // and so any measure() calls on View (which are done by React
      // DevTools) trigger the isMounted() deprecation warning.
      if (!context.__isMounted) {
        return undefined;
      }
      // The else branch is important so that we don't
      // trigger the deprecation warning by calling isMounted.
    } else if (typeof context.isMounted === "function") {
      if (!context.isMounted()) {
        return undefined;
      }
    }
    return callback.apply(context, arguments);
  };
}

``` 

so it seems there was some effort made to suppress this warning from being thrown, but because context.isMounted has a getter with side effects ಠ_ಠ, this gets thrown anyway:

```
var deprecatedAPIs = {
    isMounted: ['isMounted', 'Instead, make sure to clean up subscriptions and pending requests in ' + 'componentWillUnmount to prevent memory leaks.'],
    replaceState: ['replaceState', 'Refactor your code to use setState instead (see ' + 'https://github.com/facebook/react/issues/3236).']
  };
  var defineDeprecationWarning = function (methodName, info) {
    Object.defineProperty(Component.prototype, methodName, {
      get: function () {
        lowPriorityWarning$1(false, '%s(...) is deprecated in plain JavaScript React classes. %s', info[0], info[1]);
        return undefined;
      }
    });
  };
```

I've suppressed the warnings myself for now, but since it seems that someone took some effort to make sure these warnings don't happen, I thought I'd go ahead and open the ticket.

**Comment by FredyC** [comment] 2018-04-19 09:18
I've got that too, but it's expected. See release notes ...

https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#054

**Comment by bvaughn** [comment] 2018-04-21 21:32
Duplicate of #18868

**Closed by bvaughn** 2018-04-21 21:32 UTC
Labels: :clipboard:No Template
