### ISSUE TITLE
Build Failed    UIViewController *vc = [[[RCTSharedApplication() delegate] window] rootViewController];

### ISSUE THREAD

**Issue by jpca999** [facebook/react-native#13901] opened 2017-05-10 18:24 UTC
/ios/managerTests/managerTests.m:40:29: error: implicit declaration of function 'RCTSharedApplication' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  UIViewController *vc = [[[RCTSharedApplication() delegate] window] rootViewController];

![image](https://cloud.githubusercontent.com/assets/1026325/25914402/308fa478-358c-11e7-81b5-9e54ee1fd212.png)

heres my package.json
{
  "name": "manager",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "firebase": "^3.9.0",
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.3",
    "react-native-router-flux": "3.38.0",
    "react-redux": "4.4.5",
    "redux": "^3.6.0",
    "redux-thunk": "^2.2.0"
  },
  "devDependencies": {
    "babel-jest": "19.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "19.0.2",
    "react-test-renderer": "16.0.0-alpha.6"
  },
  "jest": {
    "preset": "react-native"
  }
}

![2__jay_jai____code_nativereact_udemycompletereactn_del__manager-rn__zsh__and_glass_and_iphone_6_ _ios_8_1__12b411_](https://cloud.githubusercontent.com/assets/1026325/25914720/4772e064-358d-11e7-9fa2-d4842ec80f21.jpg)

Initially it wasn't ablel to find a module, so I reverted back my code , and now I see that The simulator works, , but still it says that Build Failed,      what is that ? Please guide.

**Comment by Ashish5591** [comment] 2017-05-10 23:19
I am facing the same issue. Please let me know if anyone knows the fix.

**Comment by stoffern** [comment] 2017-05-12 18:17
remove the `node_modules` and install them again.
You are using old libs..

`rm -rf node_modules`
`npm i`

**Comment by andfk** [comment] 2017-05-16 00:22
@stoffern solution didnt worked for me but like he says, i´ve been using old libs, so after upgrading RN it worked. I did `react-native-git-upgrade` (`react-native upgrade`) and now it uses v0.44

**Comment by jkomyno** [comment] 2017-05-26 14:32
Reinstalling the node modules worked for me. Thanks @stoffern!

**Comment by wv1124** [comment] 2017-06-02 01:58
v0.43.4 didn't work, i need fixed in v0.43.4

**Comment by hramos** [comment] 2017-08-16 03:09
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Closed by hramos** 2017-08-16 03:09 UTC
Labels: Icebox
