### ISSUE TITLE
IOS React Native build is not working

### ISSUE THREAD

**Issue by rohitlf** [facebook/react-native#14283] opened 2017-06-01 07:58 UTC
I tried to run my react-native workspace using but it is giving below error.
<img width="315" alt="screen shot 2017-06-01 at 1 28 37 pm" src="https://cloud.githubusercontent.com/assets/24771677/26670121/0bf53c4c-46ce-11e7-83bf-9c98b5de3ec4.png">

I have made sure there is no code like the error as mentioned. 

Also I created new project using react-native init NewProject and tried to start it as well. Its also giving the same error.

Dependancies in code looks like below

```
"dependencies": {
    "@remobile/react-native-cordova": "1.0.9",
    "@remobile/react-native-file-transfer": "1.0.5",
    "react": "15.4.1",
    "react-native": "0.39.2",
    "react-native-drawer": "2.3.0",
    "react-native-facebook-login": "1.4.0",
    "react-native-fbsdkcore": "0.0.8",
    "react-native-fetch-blob": "0.10.1",
    "react-native-gifted-chat": "0.1.3",
    "react-native-image-picker": "0.24.1",
    "react-native-keyboard-aware-scroll-view": "0.2.5",
    "react-native-keychain": "0.3.2",
    "react-native-navbar": "1.5.4",
    "react-native-onesignal": "^3.0.3",
    "react-native-parallax": "0.3.0",
    "react-native-root-toast": "1.0.3",
    "react-native-swiper": "1.5.4",
    "react-native-vector-icons": "3.0.0"
  },
  "devDependencies": {
    "babel-jest": "18.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "18.0.0",
    "react-test-renderer": "15.4.1"
  },
```

**Comment by hramos** [comment] 2017-06-01 17:10
Hey, thanks for reporting this issue! It looks like you have a lot of dependencies for something that should be a plain new project. 

It does not look like this may be an issue with the framework itself. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-01 17:10 UTC
