### ISSUE TITLE
Outdated documentation for gif support on Android

### ISSUE THREAD

**Issue by juangl** [facebook/react-native#14323] opened 2017-06-05 15:42 UTC
## Reporting Bugs

https://github.com/facebook/react-native/blob/master/Libraries/Image/Image.ios.js#L109

Using this version of `animated-gif` with React Native 0.44 my app crashes on Android. To fix it, I'm using this version:

```
compile "com.facebook.fresco:animated-gif:0.14.1"
```

**Comment by hramos** [comment] 2017-06-05 16:33
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-05 16:33 UTC
