### ISSUE TITLE
Error: AMQJS0016E Invalid MQTT message type 0 (MQTT on React Native)

### ISSUE THREAD

**Issue by ngocdb** [facebook/react-native#15188] opened 2017-07-25 08:18 UTC
I am using Paho Mqtt JS (https://github.com/eclipse/paho.mqtt.javascript) on React Native via the bridge (https://github.com/Introvertuous/react_native_mqtt)

It works well on the old version of React Native
"react": "~15.4.0-rc.4",
"react-native": "0.40.0",
"react-native-elements": "^0.9.2",
"react-native-storage": "^0.1.4",
"react-native-vector-icons": "^4.0.0",
"react_native_mqtt": "^1.1.4"

But it doesn't work any more with new versions:
"react": "16.0.0-alpha.12",
"react-native": "0.46.4",
"react-native-elements": "^0.15.0",
"react-native-storage": "^0.2.2",
"react-native-vector-icons": "^4.2.0",
"react_native_mqtt": "^1.1.6"

I always get the error "Object {invocationContext: undefined, errorCode: 16, errorMessage: "AMQJS0016E Invalid MQTT message type 0."}"

I think there are changes in the new version of RN may break the mqtt feature (may be related to websocket ?)

I tried a lot of ways but can not find any clue to solve the issue. Please help me... any idea is welcomed...

**Comment by ngocdb** [comment] 2017-07-25 10:05
I tested up to the 0.45.0 version

> ...
> "react": "16.0.0-alpha.12",
> "react-native": "0.45.0",
> ...
> 
and it still runs well.

But it fails with the 0.46.4 version. Check the release notes, I see there is a change with websocket in the latest version.

> Added Cookie Header to XML and Websocket request (047961f)

Not sure how this thing affect the mqtt ?

**Comment by hramos** [comment] 2017-07-25 17:04
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-07-25 17:04 UTC

**Comment by hramos** [comment] 2018-06-12 18:22
Unfortunately, it did not follow the template. We require a minimum amount of effort when filing issues.
