### ISSUE TITLE
Shake Gesture doesn't work on Android 5.1 / Huawei G7

### ISSUE THREAD

**Issue by fab1an** [facebook/react-native#7254] opened 2016-04-27 09:12 UTC
When I start the activity I get the following stacktrace:

![screen shot 2016-04-27 at 11 10 42](https://cloud.githubusercontent.com/assets/55547/14847425/de3e8df8-0c68-11e6-8c3b-6794e697ebd2.png)

**Comment by lacker** [comment] 2016-10-21 05:16
I think we would need more info to reproduce this. I am going to close this issue but if you have a small sample app that can reproduce this, feel free to open a new one.

**Closed by lacker** 2016-10-21 05:16 UTC
Labels: Android

**Comment by fab1an** [comment] 2016-10-25 18:32
This is reproducible with the vanilla test app.

**Comment by lacker** [comment] 2016-10-26 01:11
You just start the vanilla sample app on a Huawei G7 and it crashes?

**Comment by fab1an** [comment] 2016-10-26 07:17
The app doek work, but it shows the stacktrace above and the shake gesture doesn't work.

**Comment by lacker** [comment] 2016-10-26 20:20
It seems like something is borked at the Android level since that stack trace goes past React Native entirely. It also just seems pretty odd to me that a single type of phone would break like this. I wonder if it is something specific to this one phone.
