### ISSUE TITLE
[iOS][Accessibility] Picker item scroll not announcing the current selected value 

### ISSUE THREAD

**Issue by realrider** [facebook/react-native#14928] opened 2017-07-10 11:30 UTC
Our project is a hybrid of React Native modules and native UI. We are adding accessibility to our App and are hitting on issue, one finger scroll up or down not announcing the current selected/shown value.

Tapping on it again would announce the complete information about the picker item with hints, but one finger scroll up not announcing the current value.

[Video Attachment.zip](https://github.com/facebook/react-native/files/1135303/Video.Attachment.zip)

**Comment by hramos** [comment] 2017-07-10 18:47
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-07-10 18:47 UTC
