### ISSUE TITLE
yeoman-environment version 1.2.8

### ISSUE THREAD

**Issue by design1online** [facebook/react-native#8616] opened 2016-07-06 19:27 UTC
In package.json you're including: ` "yeoman-environment": "^1.2.7",`

However, when npm updates to the latest version of yeoman@1.2.8 you get errors that the yeoman-environment module was not found with the babel-register.

**Comment by design1online** [comment] 2016-07-06 19:28
FYI for anyone running into this error, when I did `npm install yeoman-environment@1.2.7`and tried running `react-native run-ios` it worked without any further issues.

**Comment by chirag04** [comment] 2016-07-06 19:30
I can confirm running 1.2.7 works fine v/s 1.2.8 is breaking. v1.2.8 was published today.

cc @bestander

**Comment by tychota** [comment] 2016-07-06 19:44
Duplicate of #8610, I think.

**Closed** 2016-07-06 19:48 UTC
