### ISSUE TITLE
The ScrollView in Scrollview can not scroll on android

### ISSUE THREAD

**Issue by falltodis** [facebook/react-native#9836] opened 2016-09-10 05:12 UTC
### Issue Description

The code struct is like below 

```
  <ScrollView>
       <ScrollView>
          something...
       </ScrollView>
       ...
 </ScrollView>
```

The Inner scrollview would never catch any events and repsond to `scroll inner`, the outer scrollveiw catch all the `scroll events`

I seached from some issues but  not work
https://github.com/facebook/react-native/issues/41

Also I set panRepsoner of  innter srollview , not work.

Something else , It's ok on ios
### Additional Information
- React Native version: 0.31
- Platform(s) (iOS, Android, or both?): [android]
- Operating System (macOS, Linux, or Windows?): [mac]

**Comment by RD1991** [comment] 2016-09-13 06:06
Duplicate of #1046 ?

**Comment by falltodis** [comment] 2016-09-13 06:27
@RD1991 I am not sure, in my case the children are scrollviews not view and only occur on `android` ,  however they may have something similarity

**Comment by RD1991** [comment] 2016-09-13 06:35
May be someone from facebook can do a quick review about this.

**Comment by tioback** [comment] 2016-09-21 04:42
Also related to #41

**Comment by ericnakagawa** [comment] 2017-01-10 18:14
Hi folks, are you folks still experiencing this issue?

**Comment by ericnakagawa** [comment] 2017-01-12 17:55
@falltodis I'm closing this issue since there hasn't been any activity on it in a couple months. If this issue still persists reopen and I'll track down someone to review.

**Closed by ericnakagawa** 2017-01-12 17:55 UTC

**Comment by Monte9** [comment] 2017-08-06 05:09
@ericnakagawa Hey! I am running into this on Android. Here's what my code looks like:
```
<ScrollView style={{flex: 1}}>
  <View style={{flex: 1, width: SCREEN_WIDTH, marginTop: 20}}>
    <ScrollView
      style={{flex: 1}}
      horizontal
      showsHorizontalScrollIndicator={false}
    >
  </View>
</ScrollView>
```
And it seems like the outer/parent ScrollView hijacks all the touches, and I am unable to scroll the child ScrollView. 

Strangely, this is only an issue on Android. Works perfectly fine on iOS. Any help is appreciated. Thanks.

**Comment by Mark2xv** [comment] 2017-08-21 12:54
Any news on this issue? I'm experiencing the same problem with nested ScrollViews on Android, with roughly the same components as @Monte9's example code. iOS works fine.

**Comment by ardboer** [comment] 2017-12-28 20:55
+1

**Comment by MrFoxPro** [comment] 2018-01-18 15:08
+1

**Comment by johnfdhartman** [comment] 2018-02-02 02:15
+1

**Comment by ign47ev** [comment] 2018-02-11 22:12
++

**Comment by Liruwei** [comment] 2018-03-13 02:55
+1

**Comment by cyclone747** [comment] 2018-03-16 09:56
+1

**Comment by falltodis** [comment] 2018-03-20 04:01
@ericnakagawa I think you should open this issue!

**Comment by adikp09** [comment] 2018-03-21 08:06
i have this issue too. help please

**Comment by evgeni-tsn** [comment] 2018-03-21 10:14
+1

**Comment by wanbok** [comment] 2018-03-27 03:16
+1

**Comment by ios-dev-newbie** [comment] 2018-03-27 15:51
+1 facing the same problem

**Comment by Metroxe** [comment] 2018-04-05 19:02
+1

**Comment by titianqx** [comment] 2018-04-12 10:50
```
this.state = {
  ...
  fScrollEnabled:true,
 };


componentWillMount(){
  this._panResponder = PanResponder.create({

    onMoveShouldSetResponderCapture: () => true,

    onMoveShouldSetPanResponderCapture: () => true,

    onPanResponderMove: () => {
      this.setState({ fScrollEnabled:false })
    },
    onPanResponderRelease: () => {
      this.setState({ fScrollEnabled:true })
    }
  })
}

<ScrollView
	
  {...this._panResponder.panHandlers}

  scrollEnabled={fScrollEnabled}>

  <ScrollView

  {...this._panResponder.panHandlers}

  scrollEnabled={!fScrollEnabled}>

    something...

  </ScrollView>

</ScrollView>

```


[#1046](https://github.com/facebook/react-native/issues/1046)

**Comment by HamidReazaNikoonia** [comment] 2018-05-23 09:32
im also have this problem in android ! please help me

**Comment by titianqx** [comment] 2018-06-07 02:05
optimize version

```
componentWillMount(){
    this._panResponder = PanResponder.create({
      onMoveShouldSetResponderCapture: () => true,
      onMoveShouldSetPanResponderCapture: (evt,gestureState) => {
        return Math.abs(gestureState.dy) > 2 ;  // can adjust this num
      },
      onPanResponderGrant: (e, gestureState) => {
        this.fScroll.setNativeProps({ scrollEnabled: false })
      },
      onPanResponderMove: () => { },
      onPanResponderTerminationRequest: () => true,
    })
} 

<ScrollView ref={(e) => { this.fScroll = e }} >    
  <ScrollView 
    {...this._panResponder.panHandlers}
    onScrollEndDrag={() => this.fScroll.setNativeProps({ scrollEnabled: true })} >
  </ScrollView>
</ScrollView>

```



[#1046](https://github.com/facebook/react-native/issues/1046)

**Comment by ButuzGOL** [comment] 2018-07-10 04:31
@titianqx with this solution sometimes callback with "scrollEnabled: true" not calling
when you a little bit touching sub scroll area

**Comment by titianqx** [comment] 2018-07-10 06:43
@ButuzGOL use gestureState.dy

**Comment by ButuzGOL** [comment] 2018-07-10 09:44
not clear i have tried both solution but issue the same ?

**Comment by ButuzGOL** [comment] 2018-07-10 20:33
i start using https://github.com/cesardeazevedo/react-native-nested-scroll-view it works fine
