### ISSUE TITLE
Unable to resolve module

### ISSUE THREAD

**Issue by jcampbell05** [facebook/react-native#4398] opened 2015-11-28 17:59 UTC
React Native was working fine and its in my list of local packages and npm is able to detect it when I run `npm list`.

Yet when I run it on the simulator I get this:

![simulator screen shot 28 nov 2015 17 58 11](https://cloud.githubusercontent.com/assets/1484989/11453210/b7460f54-95f9-11e5-9394-6720ecfbc5ca.png)

Notice how it doesn't load from my user path just the root user folder ?

**Comment by satya164** [comment] 2015-11-29 00:31
Duplicate of #4296

**Closed by satya164** 2015-11-29 00:31 UTC
