### ISSUE TITLE
RN 73.2 + Hermes + Node 18.19 + Xcode 15

### ISSUE THREAD

**Issue by arunsa-hrbl** [facebook/react-native#43224] opened 2024-02-28 11:03 UTC
### Old Version

0.70.7

### New Version

0.73.2

### Description

Build is failing with few Libraries

### Steps to reproduce

iOS Running is failing 

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
npx react-native run-ios --simulator "iPhone 15"         

  WARNING: You should run npx react-native@latest to ensure you're always using the most current version of the CLI. NPX has cached version (0.73.2) != current release (0.73.5)
  
warn Package react-native-sqlite-storage contains invalid configuration: "dependency.platforms.ios.project" is not allowed. Please verify it's properly linked using "npx react-native config" command and contact the package maintainers about this.
warn Package react-native-vector-icons contains invalid configuration: "dependency.assets" is not allowed. Please verify it's properly linked using "npx react-native config" command and contact the package maintainers about this.
warn Package rn-fetch-blob contains invalid configuration: "dependency.hooks" is not allowed. Please verify it's properly linked using "npx react-native config" command and contact the package maintainers about this.
info A dev server is already running for this project on port 8082.
info Found Xcode workspace "Herbalife.xcworkspace"
info Building (using "xcodebuild -workspace Herbalife.xcworkspace -configuration Debug -scheme Herbalife -destination id=FB4B8F4A-110B-4A13-9FEC-38247037AF71")

/Users/arunsa/Documents/HNMyClub/UpGrade73/hrbl-nutri-club-exp-ordering-react_native/node_modules/@react-native-community/push-notification-ios/ios/PushNotificationIOS.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 12.0 to 17.0.99. (in target 'RNCPushNotificationIOS' from project 'PushNotificationIOS')
CompileC /Users/arunsa/Library/Developer/Xcode/DerivedData/Herbalife-fgiuoehjqseelacforksmcannvbx/Build/Intermediates.noindex/PushNotificationIOS.build/Debug-iphonesimulator/RNCPushNotificationIOS.build/Objects-normal/arm64/RNCPushNotificationIOS.o /Users/arunsa/Documents/HNMyClub/UpGrade73/hrbl-nutri-club-exp-ordering-react_native/node_modules/@react-native-community/push-notification-ios/ios/RNCPushNotificationIOS.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNCPushNotificationIOS' from project 'PushNotificationIOS')
    cd /Users/arunsa/Documents/HNMyClub/UpGrade73/hrbl-nutri-club-exp-ordering-react_native/node_modules/@react-native-community/push-notification-ios/ios
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -ivfsstatcache /Users/arunsa/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphonesimulator17.0-21A325-9f995cea1212cde75317d7d3cd2045e2.sdkstatcache -target arm64-apple-ios9.0-simulator -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -fno-color-diagnostics -std\=gnu11 -fobjc-arc -fobjc-weak -fmodules -fmodules-cache-path\=/Users/arunsa/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/arunsa/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -Wno-implicit-fallthrough -DDEBUG\=1 -DOBJC_OLD_DISPATCH_PROTOTYPES\=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.0.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -Wunguarded-availability -fobjc-abi-version\=2 -fobjc-legacy-dispatch -index-store-path /Users/arunsa/Library/Developer/Xcode/DerivedData/Herbalife-fgiuoehjqseelacforksmcannvbx/Index.noindex/DataStore -iquote /Users/arunsa/Library/Developer/Xcode/DerivedData/Herbalife-fgiuoehjqseelacforksmcannvbx/Build/Intermediates.noindex/PushNotificationIOS.build/Debug-iphonesimulator/RNCPushNotificationIOS.build/RNCPushNotificationIOS-generated-files.hmap -I/Users/arunsa/Library/Developer/Xcode/DerivedData/Herbalife-fgiuoehjqseelacforksmcannvbx/Build/Intermediates.noindex/PushNotificationIOS.build/Debug-iphonesimulator/RNCPushNotificationIOS.build/RNCPushNotificationIOS-own-target-headers.hmap -I/Users/arunsa/Library/Developer/Xcode/DerivedData/Herbalife-fgiuoehjqseelacforksmcannvbx/Build/Intermediates.noindex/PushNotificationIOS.build/Debug-iphonesimulator/RNCPushNotificationIOS.build/RNCPushNotificationIOS-all-target-headers.hmap -iquote /Users/arunsa/Library/Developer/Xcode/DerivedData/Herbalife-fgiuoehjqseelacforksmcannvbx/Build/Intermediates.noindex/PushNotificationIOS.build/Debug-iphonesimulator/RNCPushNotificationIOS.build/RNCPushNotificationIOS-project-headers.hmap -I/Users/arunsa/Library/Developer/Xcode/DerivedData/Herbalife-fgiuoehjqseelacforksmcannvbx/Build/Products/Debug-iphonesimulator/include -I/Users/arunsa/Library/Developer/Xcode/DerivedData/Herbalife-fgiuoehjqseelacforksmcannvbx/Build/Intermediates.noindex/PushNotificationIOS.build/Debug-iphonesimulator/RNCPushNotificationIOS.build/DerivedSources-normal/arm64 -I/Users/arunsa/Library/Developer/Xcode/DerivedData/Herbalife-fgiuoehjqseelacforksmcannvbx/Build/Intermediates.noindex/PushNotificationIOS.build/Debug-iphonesimulator/RNCPushNotificationIOS.build/DerivedSources/arm64 -I/Users/arunsa/Library/Developer/Xcode/DerivedData/Herbalife-fgiuoehjqseelacforksmcannvbx/Build/Intermediates.noindex/PushNotificationIOS.build/Debug-iphonesimulator/RNCPushNotificationIOS.build/DerivedSources -F/Users/arunsa/Library/Developer/Xcode/DerivedData/Herbalife-fgiuoehjqseelacforksmcannvbx/Build/Products/Debug-iphonesimulator -MMD -MT dependencies -MF /Users/arunsa/Library/Developer/Xcode/DerivedData/Herbalife-fgiuoehjqseelacforksmcannvbx/Build/Intermediates.noindex/PushNotificationIOS.build/Debug-iphonesimulator/RNCPushNotificationIOS.build/Objects-normal/arm64/RNCPushNotificationIOS.d --serialize-diagnostics /Users/arunsa/Library/Developer/Xcode/DerivedData/Herbalife-fgiuoehjqseelacforksmcannvbx/Build/Intermediates.noindex/PushNotificationIOS.build/Debug-iphonesimulator/RNCPushNotificationIOS.build/Objects-normal/arm64/RNCPushNotificationIOS.dia -c /Users/arunsa/Documents/HNMyClub/UpGrade73/hrbl-nutri-club-exp-ordering-react_native/node_modules/@react-native-community/push-notification-ios/ios/RNCPushNotificationIOS.m -o /Users/arunsa/Library/Developer/Xcode/DerivedData/Herbalife-fgiuoehjqseelacforksmcannvbx/Build/Intermediates.noindex/PushNotificationIOS.build/Debug-iphonesimulator/RNCPushNotificationIOS.build/Objects-normal/arm64/RNCPushNotificationIOS.o -index-unit-output-path /PushNotificationIOS.build/Debug-iphonesimulator/RNCPushNotificationIOS.build/Objects-normal/arm64/RNCPushNotificationIOS.o
In file included from /Users/arunsa/Documents/HNMyClub/UpGrade73/hrbl-nutri-club-exp-ordering-react_native/node_modules/@react-native-community/push-notification-ios/ios/RNCPushNotificationIOS.m:8:
/Users/arunsa/Documents/HNMyClub/UpGrade73/hrbl-nutri-club-exp-ordering-react_native/node_modules/@react-native-community/push-notification-ios/ios/RNCPushNotificationIOS.h:8:9: fatal error: 'React/RCTEventEmitter.h' file not found
#import <React/RCTEventEmitter.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.


--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS Simulator, id:FB4B8F4A-110B-4A13-9FEC-38247037AF71, OS:17.0, name:iPhone 15 }
{ platform:iOS Simulator, id:FB4B8F4A-110B-4A13-9FEC-38247037AF71, OS:17.0, name:iPhone 15 }



The following build commands failed:
	CompileC /Users/arunsa/Library/Developer/Xcode/DerivedData/Herbalife-fgiuoehjqseelacforksmcannvbx/Build/Intermediates.noindex/PushNotificationIOS.build/Debug-iphonesimulator/RNCPushNotificationIOS.build/Objects-normal/arm64/RNCPushNotificationIOS.o /Users/arunsa/Documents/HNMyClub/UpGrade73/hrbl-nutri-club-exp-ordering-react_native/node_modules/@react-native-community/push-notification-ios/ios/RNCPushNotificationIOS.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNCPushNotificationIOS' from project 'PushNotificationIOS')
(1 failure)
]

Node.js v18.19.0
```

### Stacktrace or Logs

```text
npx react-native run-ios --simulator "iPhone 15"         

  WARNING: You should run npx react-native@latest to ensure you're always using the most current version of the CLI. NPX has cached version (0.73.2) != current release (0.73.5)
  
warn Package react-native-sqlite-storage contains invalid configuration: "dependency.platforms.ios.project" is not allowed. Please verify it's properly linked using "npx react-native config" command and contact the package maintainers about this.
warn Package react-native-vector-icons contains invalid configuration: "dependency.assets" is not allowed. Please verify it's properly linked using "npx react-native config" command and contact the package maintainers about this.
warn Package rn-fetch-blob contains invalid configuration: "dependency.hooks" is not allowed. Please verify it's properly linked using "npx react-native config" command and contact the package maintainers about this.
info A dev server is already running for this project on port 8082.
info Found Xcode workspace "Herbalife.xcworkspace"
info Building (using "xcodebuild -workspace Herbalife.xcworkspace -configuration Debug -scheme Herbalife -destination id=FB4B8F4A-110B-4A13-9FEC-38247037AF71")

/Users/arunsa/Documents/HNMyClub/UpGrade73/hrbl-nutri-club-exp-ordering-react_native/node_modules/@react-native-community/push-notification-ios/ios/PushNotificationIOS.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 12.0 to 17.0.99. (in target 'RNCPushNotificationIOS' from project 'PushNotificationIOS')
CompileC /Users/arunsa/Library/Developer/Xcode/DerivedData/Herbalife-fgiuoehjqseelacforksmcannvbx/Build/Intermediates.noindex/PushNotificationIOS.build/Debug-iphonesimulator/RNCPushNotificationIOS.build/Objects-normal/arm64/RNCPushNotificationIOS.o /Users/arunsa/Documents/HNMyClub/UpGrade73/hrbl-nutri-club-exp-ordering-react_native/node_modules/@react-native-community/push-notification-ios/ios/RNCPushNotificationIOS.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNCPushNotificationIOS' from project 'PushNotificationIOS')
    cd /Users/arunsa/Documents/HNMyClub/UpGrade73/hrbl-nutri-club-exp-ordering-react_native/node_modules/@react-native-community/push-notification-ios/ios
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -ivfsstatcache /Users/arunsa/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphonesimulator17.0-21A325-9f995cea1212cde75317d7d3cd2045e2.sdkstatcache -target arm64-apple-ios9.0-simulator -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -fno-color-diagnostics -std\=gnu11 -fobjc-arc -fobjc-weak -fmodules -fmodules-cache-path\=/Users/arunsa/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/arunsa/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -Wno-implicit-fallthrough -DDEBUG\=1 -DOBJC_OLD_DISPATCH_PROTOTYPES\=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.0.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -Wunguarded-availability -fobjc-abi-version\=2 -fobjc-legacy-dispatch -index-store-path /Users/arunsa/Library/Developer/Xcode/DerivedData/Herbalife-fgiuoehjqseelacforksmcannvbx/Index.noindex/DataStore -iquote /Users/arunsa/Library/Developer/Xcode/DerivedData/Herbalife-fgiuoehjqseelacforksmcannvbx/Build/Intermediates.noindex/PushNotificationIOS.build/Debug-iphonesimulator/RNCPushNotificationIOS.build/RNCPushNotificationIOS-generated-files.hmap -I/Users/arunsa/Library/Developer/Xcode/DerivedData/Herbalife-fgiuoehjqseelacforksmcannvbx/Build/Intermediates.noindex/PushNotificationIOS.build/Debug-iphonesimulator/RNCPushNotificationIOS.build/RNCPushNotificationIOS-own-target-headers.hmap -I/Users/arunsa/Library/Developer/Xcode/DerivedData/Herbalife-fgiuoehjqseelacforksmcannvbx/Build/Intermediates.noindex/PushNotificationIOS.build/Debug-iphonesimulator/RNCPushNotificationIOS.build/RNCPushNotificationIOS-all-target-headers.hmap -iquote /Users/arunsa/Library/Developer/Xcode/DerivedData/Herbalife-fgiuoehjqseelacforksmcannvbx/Build/Intermediates.noindex/PushNotificationIOS.build/Debug-iphonesimulator/RNCPushNotificationIOS.build/RNCPushNotificationIOS-project-headers.hmap -I/Users/arunsa/Library/Developer/Xcode/DerivedData/Herbalife-fgiuoehjqseelacforksmcannvbx/Build/Products/Debug-iphonesimulator/include -I/Users/arunsa/Library/Developer/Xcode/DerivedData/Herbalife-fgiuoehjqseelacforksmcannvbx/Build/Intermediates.noindex/PushNotificationIOS.build/Debug-iphonesimulator/RNCPushNotificationIOS.build/DerivedSources-normal/arm64 -I/Users/arunsa/Library/Developer/Xcode/DerivedData/Herbalife-fgiuoehjqseelacforksmcannvbx/Build/Intermediates.noindex/PushNotificationIOS.build/Debug-iphonesimulator/RNCPushNotificationIOS.build/DerivedSources/arm64 -I/Users/arunsa/Library/Developer/Xcode/DerivedData/Herbalife-fgiuoehjqseelacforksmcannvbx/Build/Intermediates.noindex/PushNotificationIOS.build/Debug-iphonesimulator/RNCPushNotificationIOS.build/DerivedSources -F/Users/arunsa/Library/Developer/Xcode/DerivedData/Herbalife-fgiuoehjqseelacforksmcannvbx/Build/Products/Debug-iphonesimulator -MMD -MT dependencies -MF /Users/arunsa/Library/Developer/Xcode/DerivedData/Herbalife-fgiuoehjqseelacforksmcannvbx/Build/Intermediates.noindex/PushNotificationIOS.build/Debug-iphonesimulator/RNCPushNotificationIOS.build/Objects-normal/arm64/RNCPushNotificationIOS.d --serialize-diagnostics /Users/arunsa/Library/Developer/Xcode/DerivedData/Herbalife-fgiuoehjqseelacforksmcannvbx/Build/Intermediates.noindex/PushNotificationIOS.build/Debug-iphonesimulator/RNCPushNotificationIOS.build/Objects-normal/arm64/RNCPushNotificationIOS.dia -c /Users/arunsa/Documents/HNMyClub/UpGrade73/hrbl-nutri-club-exp-ordering-react_native/node_modules/@react-native-community/push-notification-ios/ios/RNCPushNotificationIOS.m -o /Users/arunsa/Library/Developer/Xcode/DerivedData/Herbalife-fgiuoehjqseelacforksmcannvbx/Build/Intermediates.noindex/PushNotificationIOS.build/Debug-iphonesimulator/RNCPushNotificationIOS.build/Objects-normal/arm64/RNCPushNotificationIOS.o -index-unit-output-path /PushNotificationIOS.build/Debug-iphonesimulator/RNCPushNotificationIOS.build/Objects-normal/arm64/RNCPushNotificationIOS.o
In file included from /Users/arunsa/Documents/HNMyClub/UpGrade73/hrbl-nutri-club-exp-ordering-react_native/node_modules/@react-native-community/push-notification-ios/ios/RNCPushNotificationIOS.m:8:
/Users/arunsa/Documents/HNMyClub/UpGrade73/hrbl-nutri-club-exp-ordering-react_native/node_modules/@react-native-community/push-notification-ios/ios/RNCPushNotificationIOS.h:8:9: fatal error: 'React/RCTEventEmitter.h' file not found
#import <React/RCTEventEmitter.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.


--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS Simulator, id:FB4B8F4A-110B-4A13-9FEC-38247037AF71, OS:17.0, name:iPhone 15 }
{ platform:iOS Simulator, id:FB4B8F4A-110B-4A13-9FEC-38247037AF71, OS:17.0, name:iPhone 15 }



The following build commands failed:
	CompileC /Users/arunsa/Library/Developer/Xcode/DerivedData/Herbalife-fgiuoehjqseelacforksmcannvbx/Build/Intermediates.noindex/PushNotificationIOS.build/Debug-iphonesimulator/RNCPushNotificationIOS.build/Objects-normal/arm64/RNCPushNotificationIOS.o /Users/arunsa/Documents/HNMyClub/UpGrade73/hrbl-nutri-club-exp-ordering-react_native/node_modules/@react-native-community/push-notification-ios/ios/RNCPushNotificationIOS.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNCPushNotificationIOS' from project 'PushNotificationIOS')
(1 failure)
]

Node.js v18.19.0
```

### Reproducer

Its in Private Repo

**Comment by AdrianFahrbach** [comment] 2024-02-28 23:10
You need to provide more and better information if you don't want your issues to be closed immediately. The title isn't really helpful and you don't include a reproducible example. If you want other people to spend their time fixing your issues, you have to spend time yourself making it as easy as possible for them first.

Now to your problem: I'm not from the RN team, but it looks like something is wrong with your packages and your simulator is running twice.
I would recommend to delete the node_modules, package.lock and pods. The reinstall everything, restart your computer and try again.

**Comment by cortinico** [comment] 2024-03-01 02:56
> You need to provide more and better information if you don't want your issues to be closed immediately. The title isn't really helpful and you don't include a reproducible example. If you want other people to spend their time fixing your issues, you have to spend time yourself making it as easy as possible for them first.

Really appreciate your message @AdrianFahrbach

We'll have to close this as it provides no reproducer and no information whatsoever that could help us to investigate the problem.

You should probably seek support on StackOverflow for this kind of issue.

**Closed by cortinico** 2024-03-01 02:56 UTC
Labels: Needs: Triage :mag:, Needs: Author Feedback, Needs: Repro, Type: Upgrade Issue
