### ISSUE TITLE
performance-boost and fix memory-issues: Get rid of `Object.finalize()`

### ISSUE THREAD

**Issue by fab1an** [facebook/react-native#8780] opened 2016-07-14 12:42 UTC
I opened this bug to separate it from the Fresco image-loading bug.

Here  (#8711) you can find a lengthy explanation why `Object.finalize()` is bad, but the two main reasons, why RN should stop using it are:
1. The `FinalizerQueue` can fill-up and stop being processed, this can happen for many reasons, and it's possible that `Object.finalize()` is **never** called until the JVM exits. This also means that, _every_ object that's referenced from an object whose finalizer isn't called, isn't garbage-collected. Like everything referenced from `CatalystInstanceImpl` because of [this](https://github.com/facebook/react-native/blob/2537157d994ac83f53a5ebc6ba5d74a9ad41f0c2/ReactAndroid/src/main/java/com/facebook/react/bridge/CatalystInstanceImpl.java#L413) log-statement.
2. Finalizers slow everything down by a giant amount. Quote from Effective Java:
   
   > Oh, and one more thing: there is a severe performance penalty for using finalizers. On my machine, the time to create and destroy a simple object is about 5.6 ns. Adding a finalizer increases the time to 2,400 ns. In other words, it is about 430 times slower to create and destroy objects with finalizers.

[Usage of `finalize()` in RN](https://github.com/facebook/react-native/search?l=java&q=finalize%28%29&utf8=%E2%9C%93).

I would write the PR myself, but I'm not sure how RN manages `HybridData`. I know it's tedious to release everything manually, but doing it will give RN an _extreme_ performance-boost and lower memory-footprint. This will help everyone.

Finalizers were just a bad idea which should have never happened.

**Comment by ide** [comment] 2016-07-14 17:09
As with all performance-related diffs we should profile the results. There's some chance that finalizers are cheap enough or behave differently on ART.

**Comment by fab1an** [comment] 2016-07-14 17:30
Ok, but how would you profile this?

**Comment by ide** [comment] 2016-07-14 17:52
Well you claimed there would be an extreme performance boost and reduced memory consumption - so show a before-and-after comparison of speed and memory use.

**Comment by fab1an** [comment] 2016-07-14 19:46
* GC of objects having a finalizer takes at least twice as long as normal, because the GC needs to run at least two times to reclaim the object.

* GC of all objects in the dependent tree are sharing these costs, so that's a 100% slowdown in the theoretical best-case. 

* Since GC runs when space is needed, but finalizable objects are only reclaimed after running GC twice, in the real case GC probably has to run more than twice until the space is finally cleared.

* Generational GC also can't do any optimizations since the finalizer can contain arbitrary code. 

* Then you have to add locking overhead off the FinalizerQueue. 

* Also any other thread in any other library or activity could do something in it's finalizer which blocks for, say, 100ms. This time is added as well. 

* For correct behaviour you would need to synchronize access to the finalizers since they could be run concurrently and out of order. Again, more locking costs. 

* When you add native code you get into worse territory. Your finalizers might not be executed at all, so your App crashes because it's out of native memory. This seems to happen with Fresco. 

I actually don't know how to craft a correct reproducible GC profiling test-case, since this behaviour is not defined and relies on the manufacturers of the phones and their memory and heapsize settings.

I hope someone else can step in here. 

The thing I know for sure is that in the last 10 years, every java expert anywhere advised against finalizers for many reasons. 

But everybody has the right to discard well meant advice.

**Comment by fab1an** [comment] 2016-07-16 13:29
@ide Here is a test-case: [FinalizerTest.java](https://gist.github.com/fab1an/3632f51e6704c87c138a987cd8347cfb)

It profiles creation-time of 1000 simple objects (1 int field) with

1. no finalizer
2. a trivial finalizer that just calls `super.finalize()`, and 
3. more complex finalizer that includes an `if`

Results:
```
Worst:
. no finalizer:    1742 ms
. trivial:         4560 ms
. complex:         4591 ms

Best:
. no finalizer:    1392 ms
. trivial:         3680 ms
. complex:         3797 ms
```

Keep in mind that this is just _instantiation_ of objects, not the actual finalisation and GC time that's imposed later.

**Comment by stoffern** [comment] 2016-07-16 13:41
@fab1an sorry for my bad Java knowledge, but what would you change a finalize() function with?
Can you write a example solution for [this] (https://github.com/facebook/react-native/blob/54f7ae1c02b37773b9db2c22e03e6abc9ba8958e/ReactAndroid/src/main/java/com/facebook/react/ReactRootView.java#L275
)

cc @andreicoman11 @mkonicek

**Comment by fab1an** [comment] 2016-07-16 13:58
@stoffern Good question.

1. Remove it from a production-build or better:
2. Remove it all together.

   Since there's no guarantee that finalizers are *ever* processed (in fact on my phone and that of others they aren't), you might not see this statement even though your app is leaking memory.

   How useful is a warning that's not guaranteed to be displayed?

   It must be possible to this warning elsewhere, for example in an [ActivityLifecycleCallback](<https://developer.android.com/reference/android/app/Application.html#registerActivityLifecycleCallbacks(android.app.Application.ActivityLifecycleCallbacks)>), but I don't know enough of RN's structure yet.

**Comment by stoffern** [comment] 2016-07-16 14:14
@fab1an can you run a app in simulator:
```
- run preformance monitoring
- add all react native components into a view, and refresh it a couple of times.
- then do the same with react-native without finaliser() in the sourcecode?
```

I know my app is leaking memory after 30-40 refreshs when loading 10 different components.

**Comment by fab1an** [comment] 2016-07-16 14:51
@stoffern That's no use. The native resources that are disposed in the finalizers in `HybridData.java` and `Countable.java` need to be disposed elsewhere first. I don't know enough about RN's internals to do this.

**Comment by fab1an** [comment] 2016-07-19 13:43
@stoffern I've setup and compiled ReactNative, but unfortunately I can't afford putting more time into this right now.

I've already spent about 10 hours researching, reading the code, providing benchmarks, detailed bug-reports and citing sources for this. I'm not getting paid for doing this work.

I contribute to other open-source projects as well and I'd rather spend my time where it's appreciated.

**Comment by stoffern** [comment] 2016-07-19 14:05
@fab1an i dont get payed either :smile:  And this issue is a core issue both in RN and Fresco lib, it will be quite a job for both of us to figure out how to fix this.
Altho i think if they can fix the problems with Fresco lib it will be quite good for RN allready here.

@andreicoman11 @mkonicek you guys know more of the core to how it works, would this be possible to fix?

**Comment by fab1an** [comment] 2016-08-31 09:11
@ide I figured a way of profiling this, or at least the beginning of a way: Since `ReadableMap` for arguments are using finalizers, just make some module that passes an object into Javascript a lot of times. 
Then instead serialize the object as JSON, pass it as a string and rebuild it on the JS-side without using `Readable(Native)Map`. That might give some insights.

**Comment by ide** [comment] 2016-08-31 10:31
@fab1an That seems reasonable to me so we get a basic idea of whether there is a performance improvement (or unexpected regression) and roughly how big the improvement is.

**Comment by fab1an** [comment] 2016-10-18 12:02
@ide I've put together a benchmarks calling the bridge and receiving an object. It contains 4 tests:

1. call and receive an object using an emitter and `WritableMap/WritableArray`.
2. call and receive the same object using an emitter and serialise via the `gson` library to a String, then deserialise it using `JSON.parse`.
3. call and receive the object using a Promise instead of the emitter with `WritableMap/WritableArray`.
4. call and receive the object using a Promise instead of the emitter with / `gson`.

The benchmark on my device shows that using `Gson` to get a string and then `JSON.parse` on the JS-side is consistently about 10% faster than using `WritableMap/WritableArray`.

Source: https://gist.github.com/fab1an/dfda79c6b9553d680e457b90134b3cdf
Requirements: [benchmark.js](https://benchmarkjs.com/) and [gson](https://github.com/google/gson)

**Additional Notes**
* Gson uses Reflection to convert the object to a String. If a different library like Jackson were used, or the String would be built manually, it would be even faster.
* `Arguments.createMap` could stay like it is and just use a String instead of native memory. That way it the interface would stay the same and it wouldn't get in the way of JVM-memory-management.
* There should probably be two additional benchmarks added. One for very simple objects and one  for medium to large arrays.

**Comment by fab1an** [comment] 2016-10-21 15:04
@ide: I'd be happy if you have a chance to look into my benchmark. I've tested the setup without reflection now, just using the "raw" gson-apis to generate json and `JSON.parse` it on the other side, and I've performance improvement of 100-300%.

I'm switching all my usage of the standard argument classes now for my app, because it's way faster and I don't see a downside.

**Comment by fab1an** [comment] 2016-10-22 10:53
The results:

```
Simple Object:
test_obj_simple_rn              x 507 ops/sec ±1.59% (133 runs sampled)
test_obj_simple_json            x 482 ops/sec ±1.44% (135 runs sampled)

Complex, nested object:
test_obj_complex_rn             x 267 ops/sec ±1.68% (135 runs sampled)
test_obj_complex_json           x 372 ops/sec ±1.60% (134 runs sampled)

10-element array of integers:
test_array_num_small_rn         x 495 ops/sec ±1.63% (134 runs sampled)
test_array_num_small_json       x 501 ops/sec ±1.62% (134 runs sampled)

1000-element array of integers:
test_array_num_large_rn         x 75.86 ops/sec ±1.29% (132 runs sampled)
test_array_num_large_json       x 107 ops/sec ±1.97% (135 runs sampled)

10-element array of strings:
test_array_str_small_rn         x 472 ops/sec ±1.85% (134 runs sampled)
test_array_str_small_json       x 468 ops/sec ±1.78% (134 runs sampled)

1000-element array of strings:
test_array_str_large_rn         x 44.23 ops/sec ±1.56% (130 runs sampled)
test_array_str_large_json       x 71.96 ops/sec ±1.86% (134 runs sampled)
```

**Comment by fab1an** [comment] 2016-10-22 11:06
I've moved this into a separate bug.

**Comment by lacker** [comment] 2016-12-17 01:01
I think the discussion here has converged on saying, if there is indeed a performance improvement, it would be valuable to have a pull request for it, we just need to profile to be sure. I'm going to close this issue since it no longer seems useful but if someone does indeed create a pull request improving performance that would be pretty nice here.

**Closed by lacker** 2016-12-17 01:01 UTC

**Comment by fab1an** [comment] 2016-12-17 07:40
@lacker There are *two* benchmarks in this bug-report. One here: https://github.com/facebook/react-native/issues/8780#issuecomment-233130403

There other one linked from here: https://github.com/facebook/react-native/issues/10504

But it seems that just nobody wants to change this.

**Comment by lacker** [comment] 2016-12-19 18:46
Is there a pull request somewhere that is improving performance? Maybe I missed it. If there is a pull request to improve performance then it is easier for me to drive that to a conclusion, vs having an issue where it's hard to see what should be concluded per se.

**Comment by kesha-antonov** [comment] 2017-11-01 09:52
Hello guys!

What you decided?

I'm trying to find memory leaks in my app and #2 in heap dump is FinalizerReference

I've created 2 issues on this

https://github.com/facebook/react-native/issues/16600
https://github.com/facebook/react-native/issues/16590

![screen shot 2017-11-01 at 12 50 54](https://user-images.githubusercontent.com/11584712/32269456-77a83e50-bf03-11e7-9a79-f14b4aad2ef2.png)
![screen shot 2017-11-01 at 12 51 02](https://user-images.githubusercontent.com/11584712/32269455-77819f02-bf03-11e7-8509-a478d8245511.png)

**Comment by lhfiii** [comment] 2017-12-01 12:51
This leak is killing me. Will this be fixed?

**Comment by Gark** [comment] 2018-04-11 11:14
Hello, gentlemen.
Is there any progress with that?

I still have the same issue. During my application usage,`FinalizerReference` retained size grows all time.

![finalazerreference](https://user-images.githubusercontent.com/1929368/38613391-13bf7c04-3d8a-11e8-9223-516ab39469bf.png)

How to deal with this?
