### ISSUE TITLE
Activity class {com.myapp/com.myapp.MainActivity} does not exist.

### ISSUE THREAD

**Issue by xuho** [facebook/react-native#12857] opened 2017-03-10 14:51 UTC
I have created react native app with command: "react-native init myapp --version react-native@0.40.0", then I run command "cd myapp && react-native run-android", app was BUILD SUCCESSFUL, but cannot start:
Starting: Intent { cmp=com.myapp/.MainActivity }
Error type 3
Error: Activity class {com.myapp/com.myapp.MainActivity} does not exist.

**Comment by hramos** [comment] 2017-03-10 17:21
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-03-10 17:21 UTC

**Comment by hengsoheak** [comment] 2017-11-06 08:13
I got the same problem when I try to run my projects again.
But with previous days it works fine just today, I can not run don't know how.

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  6.11.0
  Yarn:  Not Found
  npm:  5.5.1
  Watchman:  4.9.0
  Xcode:  Xcode 9.0.1 Build version 9A1004
  Android Studio:  2.1 AI-143.2915827

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.5 => 0.49.5


```
BUILD SUCCESSFUL

Total time: 12.443 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.14.1/userguide/gradle_daemon.html
/bin/sh: adb: command not found
Starting the app (/Users/sopheak/Library/Android/sdk/platform-tools/adb shell am start -n com.agriculture/com.agriculture.MainActivity...
Starting: Intent { cmp=com.agriculture/.MainActivity }
Error type 3
Error: Activity class {com.agriculture/com.agriculture.MainActivity} does not exist.
```

**Comment by AdamRobertHall** [comment] 2017-12-24 08:08
I got the same error 

Error type 3
Error: Activity class {com.datetimefuture/com.datetimefuture.MainActivity} does not exist.

"react-native": "^0.48.4",
///////////////
react-native init DateFutrueTime
react-native run-android
///////////////  run this shell can see the bug

**Comment by romreed** [comment] 2018-03-03 14:16
@AdamRobertHall 
Check whether the following values are same,

package (usually line 2) in /android/app/src/main/AndroidManifest.xml

applicationId (usually line 90) in defaultConfig section of /android/app/build.gradle

Line 1 of /android/app/src/main/java/com/paysack/MainApplication.java

Line 1 of /android/app/src/main/java/com/paysack/MainActivity.java
