### ISSUE TITLE
onLayout always returning height 0

### ISSUE THREAD

**Issue by ferminmoli** [facebook/react-native#15550] opened 2017-08-18 13:57 UTC
1. `react-native -v`: 0.44.3
2. `node -v`: 6.10
3. `npm -v`: 5.3

- Target Platform: Android

- Development Operating System: Windows 10

- Build tools: 23.0.3

Height value is always 0. Width is ok.
```

handleLayout = event => {
        this.setState({
            width: event.nativeEvent.layout.width,
            height: event.nativeEvent.layout.height
        });
    }


<View onLayout={this.handleLayout}>

                                        {this.state.height > this.state.width &&
                                            <View  style={{flex: 1}}>
                                                <Image style={{ resizeMode: 'contain',flex: 1, height:this.state.height, width:this.state.width/2}} source={{ uri: photo.thumbnailUrl }} />
                                            </View>
                                        }

                                        {this.state.height < this.state.width &&
                                            <View  style={{flex: 1}}>
                                                <Image style={{resizeMode: 'contain', flex: 1, height:this.state.height, width:this.state.width}} source={{ uri: photo.thumbnailUrl }} />
                                            </View>
                                        }

                                    </View>
```

**Comment by hramos** [comment] 2017-08-18 19:14
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-08-18 19:14 UTC
