### ISSUE TITLE
[TextInput] lineHeight in multiline TextInput

### ISSUE THREAD

**Issue by magicismight** [facebook/react-native#1577] opened 2015-06-10 02:05 UTC
It would be great if we can set `lineHeight`  in a TextInput which is set `multiline={true}`

**Comment by dsibiski** [comment] 2015-07-22 00:55
So I looked into this...and at first it seems easy...you can override `NSLayoutManager`'s `lineSpacingAfterGlyphAtIndex` method and set the lineHeight (new property) on `RCTTextView` (used for multiline).

```obj-c
- (CGFloat)layoutManager:(NSLayoutManager *)layoutManager lineSpacingAfterGlyphAtIndex:(NSUInteger)glyphIndex withProposedLineFragmentRect:(CGRect)rect
{
  return [_lineHeight floatValue];
}

```

The problem is that, the `caret` is too large. 

![screenshot](http://i.imgur.com/yMJLoUR.png)

The rect can be adjusted with [caretRectForPosition](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UITextInput_Protocol/#//apple_ref/occ/intfm/UITextInput/caretRectForPosition:) **BUT** you need to subclass UITextView and in the current implementation, RCTTextView is a subclass of RCTView.

It looks like this one won't be feasible without a reorganization of RCTTextView.

**Comment by browniefed** [comment] 2015-09-13 19:31
@dsibiski do you know if this gets fixed by any of the current PRs for multiline support and such?

**Comment by dsibiski** [comment] 2015-09-14 01:36
@browniefed Hmm, no, I don't know for sure. I'd have to hunt down some of those PRs...are there any others that you know of that tried to address line height?

**Comment by yelled3** [comment] 2015-10-15 13:47
I also encountered the same issue :-)

@ide @brentvatne ideas?

**Comment by alvinnguyen** [comment] 2015-10-20 03:50
Experiencing the same issue :+1:

**Comment by mkonicek** [comment] 2016-04-10 16:40
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/textinput-lineheight-in-multiline-textinput

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Closed by mkonicek** 2016-04-10 16:40 UTC
Labels: Icebox

**Comment by Laurensdc** [comment] 2018-02-14 11:20
Still an issue
