### ISSUE TITLE
android does not show anything

### ISSUE THREAD

**Issue by amireza1** [facebook/react-native#15336] opened 2017-08-02 16:57 UTC
hello 
my app does not show anything
i run **react-native run-android**
and my phone show this
![photo_2017-08-02_21-20-32](https://user-images.githubusercontent.com/10797090/28884764-7e8f5d16-77c8-11e7-8ba9-ef0de8e9d903.jpg)

after i set this setting  
![photo_2017-08-02_21-20-27](https://user-images.githubusercontent.com/10797090/28884827-b86f1292-77c8-11e7-9e0b-31810abda993.jpg)

show this : 
![photo_2017-08-02_21-20-41](https://user-images.githubusercontent.com/10797090/28884851-cbfa0aec-77c8-11e7-80f0-f9de652e7a97.jpg) white screen

i using  usb connect my phone to adb

ipconfig : 
![image](https://user-images.githubusercontent.com/10797090/28884935-283b02c0-77c9-11e7-9d01-6dd1e5625f10.png)

please help

**Comment by hramos** [comment] 2017-08-02 17:03
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-08-02 17:03 UTC
