### ISSUE TITLE
Cannot add a child that doesn't have a css node to a node without a measure function

### ISSUE THREAD

**Issue by Dsouza10082** [facebook/react-native#12284] opened 2017-02-08 12:29 UTC
Cannot add a child that doesn't have a css node to a node without a measure function

![whatsapp image 2017-02-08 at 10 31 07](https://cloud.githubusercontent.com/assets/7737327/22737355/8a9afbea-ede1-11e6-874b-a5a04e06d36d.jpeg)

* React Native version: 0.41
* Platform: Android
* Operating System: Windows

**Comment by EclipticWld** [comment] 2017-02-09 23:14
@Dsouza10082 probably you have some semantic issues. For example, you try to put Button into Text component.

**Comment by janicduplessis** [comment] 2017-02-10 10:55
Looks like a duplicate of https://github.com/facebook/react-native/issues/12195, please search for existing issues before creating a new one :)

**Closed by janicduplessis** 2017-02-10 10:55 UTC

**Comment by Dsouza10082** [comment] 2017-02-10 11:45
Hi @janicduplessis .

Sorry about that.

Thank you guys!

**Comment by Dsouza10082** [comment] 2017-02-10 11:45
@EclipticWld  thank you!

**Comment by wwarodom** [comment] 2017-03-02 02:58
I got exactly the same error, and from #12195 I never use 'react-native-svg'.  Any idea?

React Native version: 0.41.2
Platform: Android
Operating System: Windows

**Comment by janicduplessis** [comment] 2017-03-02 04:24
Might be another library, what are you using?

**Comment by wwarodom** [comment] 2017-03-02 08:00
@janicduplessis   

No error: (AlbumDetail.js)

```
const AlbumDetail = (props) => {
	return (
		<Text> {props.album.title}</Text>		
	);
};
```

Error with  "Cannot add a child node" as stated above: (AlbumDetail.js)

```
const AlbumDetail = (props) => {
	return (
		<Card>
			<Text> {props.album.title}</Text>
		</Card>
	);
};
```
here is my Card.js

```
const Card = (props) => {
	return (
		<View style={styles.containerStyle}>
		  {props.children}
		</View>
	);
};

const styles = {
	containerStyle: {
		borderWidth: 1,
		borderRadius: 2
	}
};
```
 
Here is my full code: https://github.com/wwarodom/helloRN

**Comment by joshuapinter** [comment] 2017-03-10 15:25
For others, I got this error because I forgot to wrap my `<Circle/>` tag in a `<Svg>` tag.
