### ISSUE TITLE
[Windows] Gradle release build fails when spaces are in directory path

### ISSUE THREAD

**Issue by micahlt** [facebook/react-native#34878] opened 2022-10-06 06:26 UTC
### Description

I'm on Windows.  When building my app for release in Android Studio, I receive the following error after Metro successfully generates the assets:

```
'C:\Users\Micah' is not is not recognized as an internal or external command, operable program or batch file.
```

The path of the repository is `C:\Users\Micah Lindley\Documents\Code\repo`.  This appears to be an issue with switching over to Hermes as Android Studio says it's tied to this line: 

https://github.com/facebook/react-native/blob/36c971695c1fa356b71298a2f1f583ed66fdd182/react.gradle#L286

Help on this is much appreciated, since this prevents my app from being built!

### Version

0.70.2

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 9 5900HX with Radeon Graphics        
    Memory: 14.97 GB / 31.41 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-212.5712.43.2112.8512546
    Visual Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Create a RN app in a folder with a space in the name
2. Open Android Studio
3. Generate a release
4. See the error

### Snack, code example, screenshot, or link to a repository

https://github.com/micahlt/wasteofmobile/tree/reactnative

**Comment by cortinico** [comment] 2022-10-06 10:01
> 'C:\Users\Micah' is not is not recognized as an internal or external command, operable program or batch file.

Can you share your full build log?

**Comment by micahlt** [comment] 2022-10-15 17:29
Bumping this - any updates?  I feel like this should be an easy thing to fix, but I'm not familiar with Gradle (which is where I believe the problem lies.

**Comment by cortinico** [comment] 2022-10-17 11:17
> I feel like this should be an easy thing to fix

Nope it's not an easy fix.
For the time being I would suggest you move your project to a directory without spaces.

The problem is that it's failing inside the React Native CLI, most likely inside Metro. But I can't tell exactly from your stacktrace.
Feel free to send over a PR, I'm happy to review and merge it 👍

**Comment by micahlt** [comment] 2022-10-19 02:00
Gotcha.  Thanks for your response.  I look forward to this being solved in the future!

**Comment by sandisahdewo** [comment] 2022-10-25 03:43
I'm also having the same issue.

**Comment by micahlt** [comment] 2022-10-25 03:50
Apparently this isn't high priority, even though it fully breaks RN on any modern Windows machine (since Windows Setup automatically creates a home folder with a space in it.

**Comment by cortinico** [comment] 2022-10-28 16:04
> Apparently this isn't high priority, even though it fully breaks RN on any modern Windows machine (since Windows Setup automatically creates a home folder with a space in it

I understand that this is frustrating for you @micahlt but in this case there is a viable workaround which is the one suggested (also I can totally recommend to take the source code in your source root as Windows is not doing great at handling long paths). We have several other bugs/build issues on Windows that are not having a workaround.

Feel free to send a PR or do some investigation for this issue, it will be really appreciated.

**Comment by micahlt** [comment] 2022-10-28 16:11
Sorry if that comment sounded passive-agressive!  I've already gotten my project to work in another folder on my machine.  Just clarifying to @sandisahdewo that this issue isn't high priority.  Thanks for your response to this issue!

**Comment by jrom20** [comment] 2022-11-20 21:52
> Apparently this isn't high priority, even though it fully breaks RN on any modern Windows machine (since Windows Setup automatically creates a home folder with a space in it. The only solution is to create a new folder somewhere like `C:\Code` and build the project from there. You just have to set up the permissions correctly.

Thank you for posting this @micahlt... I almost give up on learning react native... changing the folder name works for me

**Comment by micahlt** [comment] 2022-11-20 22:16
> Thank you for posting this @micahlt... I almost give up on learning react native... changing the folder name works for me

You're welcome!  Best of luck with your continued learning.  Hopefully someone will resolve this in the RN codebase soon!

**Comment by cortinico** [comment] 2022-11-23 17:41
> Hopefully someone will resolve this in the RN codebase soon!

Also I'm happy to review a PR if someone has some spare time to look into this 👍

**Comment by shivenmian** [comment] 2022-11-28 16:40
I'm working on a fix. You can assign this to me.

**Comment by cortinico** [comment] 2022-12-06 10:28
@micahlt could you give it a try with 0.71.0-rc3 and check if this issue is resolved?

**Comment by micahlt** [comment] 2022-12-07 01:09
> @micahlt could you give it a try with 0.71.0-rc3 and check if this issue is resolved?

Hopefully I'll have time to test it.  I tried upgrading from 0.70.6 to 0.71.0-rc.3 with `npx react-native upgrade` and got a diff error, so I'll have to do the upgrade manually.  It'll take a bit.

**Comment by kelset** [comment] 2022-12-07 10:28
@micahlt can you try on a fresh new project first? `npx react-native init RN0710RC3 --version 0.71.0-rc.3`

**Comment by micahlt** [comment] 2022-12-08 07:38
Can confirm that a fresh project compiles and runs correctly!  🎉

**Comment by cortinico** [comment] 2022-12-08 10:37
> but trying to build a release is still broken

I suspect that's a bug somewhere inside how we pass paths to metro. Can you share the full build log?

**Comment by cortinico** [comment] 2022-12-08 11:15
> 'C:\Users\Micah' is not recognized as an internal or external command,

I suspect the bug is here: https://github.com/facebook/react-native/blob/76bf71e2cc12cf0ca3d3e04ac898c4a62a9df400/packages/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/tasks/BundleHermesCTask.kt#L92

The path of `hermesc` is truncated for you as there is a space in your path.
I believe that if you turn hermes off in your `gradle.properties` the build should be green 🤔

**Comment by micahlt** [comment] 2022-12-08 17:17
I'll attempt to do this.  However, doesn't that mean the project won't have access to Hermes' performance improvements?

**Comment by kelset** [comment] 2022-12-08 17:25
I think Nicola just want to verify that his suspicion is correct, not that is a work around for you to use :)

**Comment by cortinico** [comment] 2022-12-08 18:16
> I think Nicola just want to verify that his suspicion is correct, not that it is a work around for you to use :)

Yeah essentially this, as I don't have a Windows machine and I need one to reproduce/fix this bug.

**Comment by micahlt** [comment] 2022-12-08 19:11
> I think Nicola just want to verify that his suspicion is correct, not that it is a work around for you to use :)

Gotcha, thanks for clarifying!  I'll see if that fixes the issue.

**Comment by micahlt** [comment] 2022-12-08 19:24
@cortinico Your suspicions are correct.  Setting `hermesEnabled` to false allows the app to build correctly.  I'd be glad to help out with a fix, but I don't have experience with Kotlin.  Any way I can assist?

**Comment by cortinico** [comment] 2022-12-08 19:27
I'll get back to this on Monday when I'll have access to my Windows machine to fix it.

**Comment by cortinico** [comment] 2022-12-12 13:16
I've spent some time on this and I'm not able to find a simple solution. We would need to properly escape the path for Windows only. This seems to be non trivial with Gradle.
I'm happy to review a PR if someone is willing to try to debug/solve this (I can provide codepointers if needed).

As this is happening only on Windows and only on Hermes and only inside folders that have a space in the path, I think this is not a release blocker (for .71).

I have the suspect this was broken even before.
I would appreciate if someone from Microsoft can take a look at this @mganandraj @kelset

**Comment by mganandraj** [comment] 2022-12-12 21:39
@cortinico, @kelset, @shivenmian is working on a fix .. 
This issue brings back the topic of the recommended shell for RN development on Windows, as the escaping strategy differs between powershell and cmd (and others..) .. Ideally the fix should work across all the shells.

**Comment by ablack34** [comment] 2023-02-06 16:01
Hey, thanks for looking into this! Just to confirm the short-term work around for this is too disable Hermes or move the project to a path that has no spaces?

**Comment by kelset** [comment] 2023-02-06 16:42
haven't heard back from @shivenmian - I'll ping internally

**Comment by shivenmian** [comment] 2023-02-06 18:39
I have a fix for this issue - will send a PR today.

**Comment by micahlt** [comment] 2023-02-06 20:08
> Hey, thanks for looking into this! Just to confirm the short-term work around for this is too disable Hermes or move the project to a path that has no spaces? Any further updates/developments on this?

Until the fix is merged, yes - moving the project to a location without spaces (I used C:\Users\Public\Documents) will fix the issue.

**Comment by cortinico** [comment] 2023-02-07 15:34
This has been fixed by @shivenmian here:
- https://github.com/facebook/react-native/pull/36080

We'll ship it in the next version or point release for 0.71 👍

**Closed by cortinico** 2023-02-07 15:34 UTC
Labels: Platform: Windows, Impact: Errors During Build
