### ISSUE TITLE
ViewPropTypes.js still use PropTypes from React package

### ISSUE THREAD

**Issue by hellomaya** [facebook/react-native#14621] opened 2017-06-20 03:31 UTC
When try ```react-native run-ios```, by using ```Debug JS Remotely```,  it showed those warning in Google Chrome developer tools.

```
Warning: PropTypes has been moved to a separate package. 
Accessing React.PropTypes is no longer supported and will be removed completely in React 16. 
Use the prop-types package on npm instead. (https://fb.me/migrating-from-react-proptypes)
```

By searching ```ViewPropTypes.js``` in ```react-native``` folder, at line 19:

```
const { PropTypes } = require('React');
```

* React Native version: 0.45.1
* Platform: iOS
* Development Operating System: macOS 10.12.5
* Build tools: Xcode 8.3.2

**Comment by hramos** [comment] 2017-06-20 15:47
This looks like a dupe of your earlier issue: #14620

**Comment by padlock98** [comment] 2017-06-29 17:36
Wonder why this thread is marked closed but it it not.  It is also not duplicated as claimed.

This issue still there.

By searching ViewPropTypes.js in react-native folder, at line 19:

`const { PropTypes } = require('React');`

For other undefined errors, supposed we are replacing `require('React').PropTypes` to require('prop-types'), but this one has only `require('React')`  *** note: no ".PropTypes" in this case.

Anyone has any suggestion how to improve the code?  Particularly on this import method.

**Comment by padlock98** [comment] 2017-06-29 17:39
![simulator screen shot jun 30 2017 1 06 27 am](https://user-images.githubusercontent.com/20650234/27701866-d62c95f6-5d34-11e7-8075-5571e2da96fc.png)

**Comment by padlock98** [comment] 2017-06-29 17:46
Note: If we try to amend using:

`const PropTypes = require('prop-types');`

The following error will be seen.

![simulator screen shot jun 30 2017 1 43 00 am](https://user-images.githubusercontent.com/20650234/27702076-800765ba-5d35-11e7-884e-bfffe11a6c2b.png)

**Comment by hramos** [comment] 2017-06-29 22:14
There's already a PR out that will fix this issue once it lands: https://github.com/facebook/react-native/pull/14729

**Closed** 2017-06-29 23:45 UTC

**Comment by padlock98** [comment] 2017-07-04 02:26
Hello @hellomaya , do you have solution for the above wondering?

**Comment by hellomaya** [comment] 2017-07-07 05:49
@padlock98 Try 0.46, I think.

**Comment by sachinwak** [comment] 2017-09-11 20:53
after upgrade to "react-native": "0.47.2"   I still have this warning message in emulator.  I am using android
