### ISSUE TITLE
Cannot add a child that doesn't have a YogaNode to a parent without a measure function! (Trying to add a 'ReactVirtualTextShadowNode' to a 'NativeViewWrapper')

### ISSUE THREAD

**Issue by sopaco** [facebook/react-native#13653] opened 2017-04-25 03:27 UTC
I add code below to use yoga-node，but got an error，what‘s wrong？
```java
@Override
        protected UIImplementationProvider getUIImplementationProvider() {
            return new FlatUIImplementationProvider();
        }
```

```version
"react-native": "0.43.3"
```

```txt
java.lang.RuntimeException: Cannot add a child that doesn't have a YogaNode to a parent without a measure function! (Trying to add a 'ReactVirtualTextShadowNode' to a 'NativeViewWrapper')
                                                                   at com.facebook.react.uimanager.ReactShadowNode.addChildAt(ReactShadowNode.java:173)
                                                                   at com.facebook.react.flat.FlatShadowNode.addChildAt(FlatShadowNode.java:217)
                                                                   at com.facebook.react.flat.NativeViewWrapper.addChildAt(NativeViewWrapper.java:98)
                                                                   at com.facebook.react.flat.FlatUIImplementation.addChildAt(FlatUIImplementation.java:510)
                                                                   at com.facebook.react.flat.FlatUIImplementation.setChildren(FlatUIImplementation.java:190)
                                                                   at com.facebook.react.uimanager.UIManagerModule.setChildren(UIManagerModule.java:326)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:345)
                                                                   at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:141)
                                                                   at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
```

**Comment by hramos** [comment] 2017-04-25 13:17
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-04-25 13:17 UTC

**Comment by lyxia** [comment] 2017-04-26 10:21
I have the some problem.

**Comment by JCMais** [comment] 2017-09-14 19:55
Same error here.

**Comment by ryands17** [comment] 2017-10-07 20:29
This issue is still prevailing on Android
React Native version: 0.49.1

**Comment by sibelius** [comment] 2017-11-24 02:40
this is still happening on 0.50.0

**Comment by wuxiaojun123** [comment] 2017-11-29 13:51
this is still happening on 0.50.4

**Comment by chohra-med** [comment] 2017-12-09 23:10
i used to have the same issue , the solution is : don't make spaces in declaration of components for example  look at Text tag ( there's space between > and Text ) 
            <Text  >this a compenent   </Text>  make it like that  :<Text  >this a compenent   </Text>

**Comment by JCMais** [comment] 2017-12-10 02:49
This happens if you have space like mentioned above, or if you have conditional rendering, that is checking a non boolean prop, that can be undefined or an empty string. Like:

```
{myCheck && <MyComp />}
``` 

This returns an error if `myCheck` can be undefined, or an empty string, because if its a falsy value, it's going to be the value returned in the expression, and so, React will try to render it, but React cannot render undefined or empty string values, inside non `Text` components, throwing the error above.

The solution is to cast the variable to a boolean:

```
{!!myCheck && <MyComp />}
``` 

Since false is correctly ignored.

**Comment by RoshanSalian** [comment] 2017-12-18 15:38
I wasted more than a day on this and found no useful solution anywhere.

I got this error because I had put a comment inside a component.

On removing that comment the app did run for me.

**Comment by sebirdman** [comment] 2017-12-21 21:32
This seems to be a problem with something that parses what your component returns from render().

in my case i had the following code:

```
<View>
  {someThing};
</View>
```

and the fix was removing the semicolon:

```
<View>
  {someThing}
</View>
```

**Comment by daxaxelrod** [comment] 2017-12-26 19:52
This error should be reformated. I just made a simple JSX mistake but took forever to find it.

**Comment by Harag** [comment] 2018-03-29 11:38
This did me in, just posting here for some other person like me that could not spot the obvious
```
<View>
<Text>

SomeText
</Text>
<View>
```

**Comment by DanielLe232** [comment] 2018-04-15 10:09
I have same error
But i have investigate, it does not relate to about white space in text.
I think it should notice this bug more detail.

**Comment by DanielLe232** [comment] 2018-04-15 10:13
All right, i do follow by @RoshanSalian.
It work.

@RoshanSalian 👍

> I wasted more than a day on this and found no useful solution anywhere.
> I got this error because I had put a comment inside a component.
> On removing that comment the app did run for me.
