### ISSUE TITLE
ReactNative 0.59.9 -> 0.61.2 : much more slower on android release builds

### ISSUE THREAD

**Issue by fxhrgco** [facebook/react-native#26870] opened 2019-10-15 16:23 UTC
After upgrading to new version, the app transitions, touch element, open new screen is much more slower. It looks like it is in debug mode.

React Native version:
Binaries:
    Node: 12.8.1 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.10.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 26, 27, 28
      Build Tools: 27.0.3, 28.0.3
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2
  npmGlobalPackages:
    react-native-cli: 2.0.1

I haven't hermes enabled (not working for now in on my side)

**Comment by ikorin** [comment] 2019-10-18 16:23
I can confirm this. My team experiences up to 2.5-3 times slower performance on physical Android devices with Release variant.

**Comment by axemclion** [comment] 2019-10-21 20:35
Does this happen on both android AND iOS ? Could you help pin point to specific parts that make it slow - here is a guide - https://github.com/facebook/react-native/issues/26870

**Comment by ikorin** [comment] 2019-10-21 21:10
It is Android issue only. I do not see a link to the guide. Please check your message above.

**Comment by jjhampton** [comment] 2019-11-07 15:42
I'm seeing the same. I do not have hermes enabled, however all parts of the _Android_ app's UI (in release builds) are slower.

**Comment by kittinan** [comment] 2019-11-29 10:28
Same problem on RN 0.59.9

**Comment by TheSavior** [comment] 2019-11-29 17:03
For what it’s worth, this issue doesn’t currently have enough information for someone to debug the issue. If you can make a small reproducing case that would be very helpful. 

We haven’t heard this complain widely so I think it might be something with your specific project.

Have you tried creating a new project to see if that is slow as well? What about after adding all of your 3rd party modules you are using?

This kind of investigation is needed for someone to be able to help.

**Comment by kittinan** [comment] 2019-12-02 03:09
I found the problems of my app UI very slower on a release build. I am using [Ignite](https://github.com/infinitered/ignite) boilerplates to start my project.

I removed all
```js
console.log()
console.tron.log()
```
and build release again my app working fine and smooth

**Comment by chrisnojima** [comment] 2020-02-04 21:37
we upgraded from 0.60.5 to 0.61.5 and had to rollback as android performance noticeably cratered

**Comment by TheSavior** [comment] 2020-02-04 22:16
I'm going to close this issue as there isn't currently anything actionable here. If you have this problem with specifics like a repro or traces of where new time is being spent feel free to open a new issue.

**Closed by TheSavior** 2020-02-04 22:16 UTC
Labels: Bug, Platform: Android

**Comment by bashirpour** [comment] 2020-02-05 08:17
I have exactly the same problem.
I made a new project and then transferred my previous code.
It works very well in debug mode, but unfortunately when I turn off debug mode or take the final output, performance drops sharply and the app speed slows down.

`react navigation drawer` That doesn't work at all

**Comment by bashirpour** [comment] 2020-02-05 08:26
@TheSavior  Please open again this issue. Because this problem is still not resolved.

https://stackoverflow.com/questions/53143502/react-native-app-lags-in-release-build-only

**Comment by robbycp** [comment] 2020-06-04 13:14
Some questions for all of you getting this issue, which happened in my case.
1. Do you have different data (image size, product quantity) that loads in your development and production environment? The more you load products, and the size of the images might result different performance in this two environment.
2. Do you install other package component or your custom component that use Animated react-native core component? If you use that, is it using useNativeDriver: true? If useNativeDriver: no, better upgrade the package or find another alternatives that use Animated component with useNativeDriver true. Also change your custom component and use useNativeDriver true. For further reading about useNativeDriver you can read (this)[https://reactnative.dev/blog/2017/02/14/using-native-driver-for-animated]

In my case because there's a lot of products in production environment, and i used animated skeleton with useNativeDriver false, the performance in production is much slower.

**Comment by huyhai** [comment] 2020-06-17 09:08
same here

**Comment by rahamin1** [comment] 2020-10-07 10:34
M app performed well on 0.59.9 on both platforms.
After upgrading to 0.62.2 it is much slower on android, still works well on iOS.

**Comment by arthedza** [comment] 2020-10-12 11:09
The probably reason is described in [#25986](https://github.com/facebook/react-native/issues/25986)

**Comment by rahamin1** [comment] 2020-10-12 11:19
Thanks @arthedza 
In my configuration hermes is disabled. 
According to https://reactnative.dev/docs/hermes it will speed my app on android...

**Comment by edwardchen** [comment] 2020-10-13 09:31
This issue is nearly a year old. The app is unusable on Android after doing this upgrade. Is there really no solution for this?

**Comment by rahamin1** [comment] 2020-10-26 21:14
- This issue has been opened because of **very slow** performance with 0.61.1 than with 0.59.9
- I have experienced **slower** (but definitely not very slow) performance with 0.62.2 than with 0.59.9
- @chrisnojima experienced "noticeably" slower performance with 0.62.2 than with 0.59.9

Has anyone tried 0.63.3 and can say how it performed compared to other versions?

**Comment by rahamin1** [comment] 2020-10-29 06:47
I have tested on 0.63.3. Same as 0.62.2 - very slow compared to 0.59.9.

**Comment by Anujmoglix** [comment] 2020-11-11 10:22
> To summarize what people are complaining about here:
> 
> * This issue has been opened because of **very slow** performance with 0.61.1 than with 0.59.9
> * I have experienced **noticeably slower**  performance with 0.62.2 and 0.63.3 than with 0.59.9, no expo. Hermes didn't help on android.
> * @chrisnojima experienced **noticeably slower** performance with 0.62.2 than with 0.59.9
> 
> @fxhrgco I suggest to modify the title to "ReactNative 0.59.9 -> 0.61.2/0.62.2/0.63.3: much slower..."
> It seems that I am last victim... Everybody else is quite :)
> Did anybody find a solution? Or at least an explanation to why and/or when this happens?

I am also facing this issue . There is no proper solution of this and I am trying to downgrade then getting lots of issue . I am facing lagging in 0.63.3 rn version

**Comment by Anujmoglix** [comment] 2020-11-11 10:23
> My app performed well on 0.59.9 on both platforms.
> After upgrading to 0.62.2 it is much slower on both android and iOS.
> 
> Both debug mode and release mode.
> Using Hermes didn't improve the performance.
> 
> I am reverting back to RN0.59.9 until the performance issues on the new version(s) is resolved.

I also wants to do that but app crashing issue . What steps you done in downgrade app.

**Comment by jeffelector** [comment] 2020-11-11 10:56
@Anujmoglix try to open a new project and then past all your component there .. a lot of work but i think its better way ....
i am also facing the slow of react native 0.63.3

**Comment by Anujmoglix** [comment] 2020-11-11 11:39
Why React native team is not looking into it ?  It is major issue and it is creating negative impression . @jeffelector  that is a solution but how I will check dependent version ?

**Comment by rahamin1** [comment] 2020-11-21 09:53
> Why React native team is not looking into it ? It is major issue and it is creating negative impression.

I believe that they need an example (repo) that demonstrates the problem.

**Comment by edwardchen** [comment] 2020-11-22 00:44
I upgraded to 0.63.3 and the extreme slowness appears to have gone away. Still have no idea what fixed it for me...

**Comment by rahamin1** [comment] 2020-11-22 09:36
Good for you...
Didn't help me at all.

BTW, according to my measurements:
- On android, any version beyond 0.59.9 is ~10 (ten...) times slower than 0.59.9 (measured on LG V20)
- iPhone 7, which is supposed to be ~3 times faster than LG V20, is ~4 times slower than the LG V20, which means that it gives a similar performance to android on any version beyond 0.59.9

Hermes didn't improve my app's performance.

### To make it short: my app with android using RN 0.6x.x is 10 times slower than using RN 0.59.9

**Comment by mirik999** [comment] 2020-12-02 20:14
Development on RN ( especially rn cli ) for android is very terrible. The same problem in my case too.

**Comment by Asadi123** [comment] 2021-01-14 05:05
Upgraded my project to 0.59.10 to 0.62.2. the android release build becomes significantly slow. I hope we find a solution for it.

**Comment by marudy** [comment] 2021-01-15 13:01
@TheSavior this is an issue affecting more and more people; I just run into it while upgrading from 0.63.4 -> 0.64.0-rc2. Not sure how many people it affects but you can imagine the frustration of all of us trying to enable Hermes and not be able to do so for quite some time :/

I was hoping to improve my app's startup performance by upgrading and enabling Hermes; as we use mobx, 0.64 is the first one that supports mobx 5 symbols properly. Now the app startup time has doubled down actually almost from 11 seconds to 21 seconds.

An issue like that cannot remain closed in my opinion because there are no trace logs or something; it's still an issue. Of course I understand that trace logs would make you life easier and I am willing to do some troubleshooting and provide some info, but please reopen the issue and also maybe explain what is the fastest/best way to trace this ? Nobody wants to spend time towards the wrong direction. Not you trying to reproduce an error you don't see, not me troubleshooting towards the wrong direction, noone overall :) 

Thanks for your efforts overall, hopefully we can give together this issue the proper attention and solve it :)

**Comment by ramazanarslan** [comment] 2021-01-15 13:44
I am also encountered the same problem. i am using 0.63.3. Our product team says at past it was fast, but we didn't add any huge feature but it is slow. I have just upgraded react native and react navigation libraries.

**Comment by marudy** [comment] 2021-01-16 01:55
@TheSavior I have started to trace down the issue. I will open tomorrow a new issue with proper description and provide trace logs but I will list here quickly the findings I have so far.

**The issue:**
When Hermes is enabled and only then the app startup time is way slower (25.5sec) than before (17sec) - losing 8.5 extra seconds. When Hermes is disabled it works as before.

**Initial traces:**
In order to dig deeper I used @axemclion which has been provided already and missed through my initial quick read. 
- So far I am seeing that the major delay is being caused by the processes with name `GET_CONSTANTS_START`. There are around 50 of them being executed in my case and until the `TTI_COMPLETE` event. Over the run without hermes ALL of them execute within the same ms or the very next one. Over the run with hermes enabled i'm suddenly seeing numbers all the way from 1-6ms which are the fastest ones up to 1121 , 2034 , 3707 ms. This is a huge increase as we can see and these are causing the biggest part of the delay.
- On a 2nd note the process with name `CHANGE_THREAD_PRIORITY` also takes double the time it was occupying before. In my case from 567ms all the way up to 1132ms.
- On a 3rd note the process with name `CREATE_CATALYST_INSTANCE_END` takes now 2034ms while before it was accounting for 26ms only

As a statistic by adding the delays that surpass 500ms the sum becomes ~ 17 seconds which is exactly the double of the time we are losing. Looks like we are adding exactly the time we are supposed to gain. So in this case my app should go from 17sec startup time to a much improved of 8.5 seconds and that would be super awesome.

Will open a new issue and provide logs & details tomorrow as it's 4am here.

Hope we can nail this down soonish, cheers.

**Comment by rahamin1** [comment] 2021-01-16 17:53
@marudy You seem to be talking only about slower startup time only with Hermes.  

My problem is that the app is much slower in everything that I do with it, with or without Hermes, and also on iOS.
I am not using react-navigation (others may suffer from a problem that may be related to it).

I believe that other people suffer from similar problems.

**Comment by marudy** [comment] 2021-01-16 18:22
@rahamin1 yes you are right. It might be that the whole app has been taken a tall on slowness overall but what is obvious is the startup time. I don't think it's navigation library related necessarily but i do see a few similar issues around opened for the past year. Some people say their app becomes slow when Hermes is disabled only.

What I do believe these issues all have in common is introduction of Hermes. So I believe they are all related with it and it's how RN has started to handle performance after its introduction.

We can easily confirm if your issue has the same root cause as mine if you do some troubleshooting as I did and investigate which tasks are the slow ones.

Also I just opened this one: #30750

**Comment by rahamin1** [comment] 2021-03-26 18:23
Has anybody found a solution to this problem?

**Comment by adamsolomon1986** [comment] 2021-03-29 21:05
+1

**Comment by chj-damon** [comment] 2021-05-18 03:40
+1

**Comment by firstfloordigital** [comment] 2021-06-08 13:48
+1

**Comment by AlastairTaft** [comment] 2021-06-26 23:27
+1

**Comment by jko12130** [comment] 2021-07-22 10:28
Facing the same issue with RN 0.62.2. The Android version is 4-5 times slower than iOS version and is basically unusable. No Hermes, did all the recommended optimizations, etc. I am scratching my head here. Did anyone find a solution to this issue?

**Comment by rahamin1** [comment] 2021-09-16 17:29
Did anyone try to migrate to RN 0.65 and see if it fixed the performance issues?
