### ISSUE TITLE
[ShadowPropTypesIOS] Does not match CSS box shadow spec

### ISSUE THREAD

**Issue by andresn** [facebook/react-native#7187] opened 2016-04-23 22:48 UTC
Quick overview of the spec:
http://css3gen.com/box-shadow/

As an RN user, I want a full range of control over my box shadow, for instance, I want a shadow at 91 degrees, 4px distance, full opacity, but this is all I have to work with:

```
shadowColor: '#000',
shadowOffset: {
    width: 1,
    height: 1
},
shadowOpacity: 1,
shadowRadius: 4
```

And correct me if I'm wrong, width, height, and radius all imply the shadow will always be around the entire container? My guess is that this was an MVP feature, so filing this at least for the record.

**Comment by janicduplessis** [comment] 2016-04-24 17:45
This is probably just a limitation of the underlying native API. The goal was never to reproduce the full spec of css 3 for shadows since that would require rewriting the whole shadow drawing code.

**Comment by andresn** [comment] 2016-04-24 19:30
@janicduplessis ah, so you're saying there's no way to mimic shadows from different lighting degrees via the underlying native API?

**Comment by lacker** [comment] 2016-10-20 01:21
So this is not supposed to match "css 3", the behavior is based on the css-layout library which has some limitations but in general does a lot of stuff in a nice crossplatformy way. We've improved the docs on how shadows and layout works in React Native since this issue was originally opened, so I'm hoping this situation is more clear now. I'm closing this issue but feel free to reopen if there is an inaccuracy in the current documentation for what does work. Or with pull requests to add more features ;-)

**Closed by lacker** 2016-10-20 01:21 UTC
