### ISSUE TITLE
development server returned erro code 404

### ISSUE THREAD

**Issue by ketankulkarni** [facebook/react-native#19261] opened 2018-05-15 08:25 UTC
my project was working but suddenly i get this error
package.json

```
{
  "name": "RNApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node_modules/react-native/packager/packager.sh",
    "lint": "eslint app/",
    "test": "jest"
  },
  "jest": {
    "preset": "react-native",
    "snapshotSerializers": [
      "enzyme-to-json/serializer"
    ],
    "setupFiles": [
      "<rootDir>/jest/setup.js"
    ]
  },
  "dependencies": {
    "expo": "^25.0.0",
    "gravatar-api": "^1.4.0",
    "react": "^16.0.0-alpha.12",
    "react-native": "^0.47.1",
    "react-native-camera": "^1.0.2",
    "react-native-google-analytics-bridge": "^5.6.3",
    "react-native-keyboard-spacer": "^0.3.0",
    "react-native-meteor": "^1.1.0",
    "react-navigation": "^1.0.0-beta.12"
  },
  "devDependencies": {
    "babel-eslint": "^7.0.0",
    "babel-jest": "^22.4.3",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "enzyme": "^3.3.0",
    "enzyme-adapter-react-16": "^1.1.1",
    "enzyme-to-json": "^3.3.3",
    "eslint": "^3.3.1",
    "eslint-config-airbnb": "^12.0.0",
    "eslint-plugin-import": "^1.16.0",
    "eslint-plugin-jsx-a11y": "^2.1.0",
    "eslint-plugin-react": "^6.1.1",
    "jest": "^22.4.3",
    "jsdom": "11.7.0",
    "jsdom-global": "3.0.2",
    "react-dom": "^16.3.1",
    "react-test-renderer": "^16.3.1"
  }
}

```
![screenshot_20180515_134654](https://user-images.githubusercontent.com/20577851/40045238-6383b0b6-5847-11e8-900f-56034b374d95.png)

**Comment by kelset** [comment] 2018-05-15 09:11
Duplicate of https://github.com/facebook/react-native/issues/19262

**Closed by kelset** 2018-05-15 09:11 UTC
Labels: :clipboard:No Template
