### ISSUE TITLE
Navigation Experimental: reducer expects navigation stack to be unique but StateUtils doesn't guarantee this

### ISSUE THREAD

**Issue by mschipperheyn** [facebook/react-native#7348] opened 2016-05-03 10:34 UTC
I have a problem with pushing elements on to the navigation stack. I use my own reducer:

    export default function navigationReducer(state = initialState, action = {}) {
      switch (action.type) {
        case NAV_PUSH:
            if (state.navigationState.children[state.navigationState.index].key === (action.state && action.state.key))
            return state;

            return {...state,...{
            navigationState: StateUtils.push(state.navigationState, action.state)
          }
        };

        case NAV_POP:
            if (state.navigationState.index === 0 || state.navigationState.children.length === 1)
            return state.navigationState;
            return {...state,...{
            navigationState: StateUtils.pop(state.navigationState)
          }
        };

        case NAV_JUMP_TO_KEY:
            return {...state,...{
            navigationState: StateUtils.jumpTo(state.navigationState, action.key)
          }
        };

        case NAV_JUMP_TO_INDEX:
            return {...state,...{
            navigationState: StateUtils.jumpToIndex(state.navigationState, action.index)
          }
        };

        case NAV_RESET:
          return {...state,...{
            navigationState: StateUtils.reset(state.navigationState, [action.state],0)
          }
        };

        default:

When I push an item that was already pushed before, I get an exception indicating that the navigationstack should be unique.

    ExceptionsManager.js:61 navigationState.children[2].key "scene_/account/wall" conflicts withanother child!
    Each child in an array or iterator should have a unique "key" prop. Check the render method of `NavigationAnimatedView`

The StateUtils doesn't guarantee this requirement. It makes sense that the navigation stack should only contain unique items and if it should, I would think that the library takes care of this and that this is not something I would have to manually check?

Also on stackoverflow: http://stackoverflow.com/questions/36980787/navigation-experimental-stack-only-unique-items

**Comment by satya164** [comment] 2016-05-04 02:40
cc @ericvicenti @hedgerwang

**Comment by ericvicenti** [comment] 2016-05-04 03:08
Thanks for the excellent report, @mschipperheyn! I agree this needs to be fixed and unique keys should be handled by the library.

I'm thinking we should allow push/replace/reset to provide a state without a key, and have the utils override keys when they conflict with another.

Does anybody want to take a stab at fixing this?

**Comment by ericvicenti** [comment] 2016-05-04 03:33
On second thought, I think it would be a mistake to override keys. But we should discourage providing them to the StateUtils, which can be built to do a pretty good job of making unique keys by adding the timestamp to an internal counter.

@hedgerwang, thoughts?

**Comment by hedgerwang** [comment] 2016-05-04 17:08
Couple things that we need to do to make StateUtils less confusing and more robust.

1. Be strict, ensure uniqueness of key is guaranteed.
2. Ensure that immutability is guaranteed.  For now, some methods still don't do mutation checks thus new state is already returned despite nothing happens.
3. Get rid of `getParent`. For now, both `NavigationParentState` and `NavigationState` are considered valid input to methods like `reset`, which yields result that can be very unpredictable.

For example:

you can tell that the `children` may or may not be set depends whether the input already has children or not, and it's really strange API cause I have no easy way to tell whether the `children`  will be set eventually.

```
function reset(state: NavigationState, nextChildren: ?Array<NavigationState>, nextIndex: ?number): NavigationState {
  const parentState = getParent(state);
  if (!parentState) {
    return state;
  }
  const children = nextChildren || parentState.children;
  const index = nextIndex == null ? parentState.index : nextIndex;
  if (children === parentState.children && index === parentState.index) {
    return state;
  }
  return {
    ...parentState,
    children,
    index,
  };
}
```
IMHO, I'm OK with modeling the navigation state as such

```
{
  key: string,
  index: number,
  children: Array<{key: string: }>},
}
```
But I'm  not really comfortable with providing any APIs involving guess the  hierarchy of a navigation state or traversing it.


@mschipperheyn: 
One more thing. `NavigationLegacyNavigatorRouteStack` already did push, pop, reset...etc with unique check with unique key checking, you may check `NavigationLegacyNavigatorRouteStack-test` and see how it's used. (P.S we're planning killing  `NavigationLegacyNavigatorRouteStack` soon).

**Comment by hedgerwang** [comment] 2016-05-04 17:12
@ericvicenti : you're right. it'd huge mistake to overwrite the key :). 

We use key as the proxy to represent the actual object to compare.
However, the developer may simply use reference comparison to boost its app perf.

So if the developer gives us a immutable object with an unique key, and `StateUtil` returns a new object with the same key, or return the same object with a new key, any of these cases will break the app.

Simply to say, we don't want to write the key in any circumstance.

**Comment by mschipperheyn** [comment] 2016-05-18 19:14
Just to be clear on the subject. Is this still considered an issue? Or am I supposed to do something to avoid this exception?

**Comment by ericvicenti** [comment] 2016-05-18 19:47
Right now, we expect you to provide a unique key while pushing. Maybe we could add a new function to stateutils that assigns a key automatically when pushing

**Comment by mschipperheyn** [comment] 2016-05-19 01:26
Ok, I never considered the key as unique. I always considered it like a unique key per distinct screen, not a unique key per screen push. I will have reconsider my approach. I guess I could just add a random unique number to it. 

It should probably be internalized. Thanks for the update!

**Comment by mschipperheyn** [comment] 2016-05-30 01:07
So, I tied a few things (RN 0.24.1):
1. I tried to reorder the child list, if the a key was requested that already existed as a child. I would put the child at the end. But this lead to RN basically locking up during an animation. It just didn't work
2. The approach that worked was to have a little function that adds a unique id to the key and push it to the list.

I don't think this is a very elegant solution, because you can build up a long history over time with many effectively duplicate results. But this can be resolved with a reset from time to time.

**Comment by lacker** [comment] 2016-10-21 07:21
OK so overall it seems like this is "working as intended" because you are just expected to provide a unique key. I'm going to close this issue but this seems like something we should keep in mind as we are building the next gen navigation library. cc @ericvicenti FYI

**Closed by lacker** 2016-10-21 07:21 UTC
