### ISSUE TITLE
the native component can not be dealloc

### ISSUE THREAD

**Issue by OrrHsiao** [facebook/react-native#37842] opened 2023-06-13 09:14 UTC
### Description

the native component can not be dealloc when react-native viewcontroller pop to native viewcontroller  in iOS platform

### React Native Version

0.71.4

### Output of `npx react-native info`

System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 58.88 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.1 - /Users/orrhsiao/.rvm/gems/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.4 => 0.71.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

https://github.com/OrrHsiao/ReactNativeDemo
You can use this example to reproduce the problem
Repeat step

Open demo and run iOS programs.
Click the "push" button to jump to the RN page.
Click "jump hello word" to go to the Page1 component page.
Click on the navigation bar return arrow "<" Close the RN page. Observe that XATestView does not execute the dealloc function.

### Snack, code example, screenshot, or link to a repository

https://github.com/OrrHsiao/ReactNativeDemo

**Comment by cortinico** [comment] 2023-07-10 10:20
Closing as duplicate of #38238

**Closed by cortinico** 2023-07-10 10:20 UTC
Labels: Issue: Author Provided Repro, Newer Patch Available
