### ISSUE TITLE
[FlatList] Removing rows above and below another row in a flatlist causes a crash

### ISSUE THREAD

**Issue by Talor-A** [facebook/react-native#13141] opened 2017-03-24 21:38 UTC
### Description

I've noticed a strange problem with FlatList and LayoutAnimation on Android only (no issue on iOS). If I have a FlatList with rows A,B,C  and I remove A and C at the same time with a LayoutAnimation applied, row B disappears as well. Then, if A and C are added back to the list, an error is triggered that says 
```
index=2 count=1 
addInArray
ReactViewGroup.java:483
```

In my app, I have a FlatList being populated by a realm.io database. The data is filtered by a TextInput component matching the title of the realm object. When I apply a LayoutAnimation to the list, something goes wrong on android.

### Reproduction Steps and Sample Code

I can't post this on sketch because there's no FlatList yet, but here's the offending component. It takes a prop `input` containing a string, which is passed from a simple TextInput. the variable `results` is then filled with realm Objects with titles that match the given input. 
for example, if I type in 'Item', I might get a list that looks like this: 

- Item001
- Item002
- Item003

If I then add '002', the list should look like this:
- Item002
Instead, all the items disappear, and when I press backspace I get the error mentioned above.

Here's the code for the component:
```

class SearchResults extends Component {
  componentWillReceiveProps (nextProps) {
    if (nextProps.input !== '' && this.props.input !== '') {
      LayoutAnimation.easeInEaseOut()
  }
  render () {
    let {input} = this.props
    let results = realm.objects('MyObject')
                  .filtered('title CONTAINS[c] $0', input)
                  .sorted('updatedAt', true)
      return (
        <FlatList
          {...this.props}
          data={results}
          renderItem={({item, index}) => <SearchResult item={item} key={index} size={48} />}
          keyExtractor={item => item.id}
      />

      )
  }
}

```

### Solution

This only happens on Android when LayoutAnimation is applied, and appears to be a problem in the `ReactViewGroup.java` file. As far as I can tell, the error above is thrown because the list should have one item, but the last item has been removed mistakenly.

### Additional Information

* React Native version:0.43.0-rc.1
* Platform: works on iOS, not on Android
* Development Operating System: Linux for android, MacOS for iOS

**Comment by nico1510** [comment] 2017-04-08 15:22
Yes I noticed the same. Deleting from a FlatList using LayoutAnimation causes exactly the problem you describe.

**Comment by martinezguillaume** [comment] 2017-07-13 13:44
I have exactly the same problem !

**Comment by jaspal747** [comment] 2017-07-17 21:53
Facing the exact same issue. Flatlist + LayoutAnimation causing app to crash in Android.
![screenshot_2017-07-17-17-51-33](https://user-images.githubusercontent.com/1780300/28291514-c9a3815e-6b18-11e7-91c3-805f9130c0fd.png)

**Comment by martinezguillaume** [comment] 2017-07-17 22:16
Workaround from @janicduplessis worked for me [here](https://github.com/facebook/react-native/issues/13207). Hope that it will be fixed soon...

**Comment by hramos** [comment] 2017-09-21 15:14
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Closed by hramos** 2017-09-21 15:14 UTC
Labels: Icebox
