### ISSUE TITLE
Create new project, iOS release build crashes on open

### ISSUE THREAD

**Issue by jackdewhurst** [facebook/react-native#17911] opened 2018-02-08 16:01 UTC
**Introduction**

So basically what I'm seeing is if I create a new project and run in Xcode in release configuration the app crashes on open. Both on device and simulator

**Environment**

  OS: macOS High Sierra 10.13.2
  Node: 6.9.4
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.3871768
  Target Platform: iOS (8.0)

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.0 => 0.53.0

**Steps to Reproduce**

1. Run `create-react-native-app TestReleaseBuild`.

2. cd to project and run `yarn run ios`. Verify running fine in simulator.

3. Then run `npm run eject` to generate Xcode project. I chose "React Native: I'd like a regular React Native project."

4. Open Xcode project, edit scheme to release and AppDelegate.m to point to static bundlejs file along with other steps listed here - https://facebook.github.io/react-native/docs/running-on-device.html.

5. Run the app on device. The app launches and immediately throws the exception below:

```2018-02-08 09:31:38.085750+0000 FB[658:508728] Super expression must either be null or a function, not string
2018-02-08 09:31:38.089 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: Super expression must either be null or a function, not string
2018-02-08 09:31:38.089867+0000 FB[658:508707] Unhandled JS Exception: Super expression must either be null or a function, not string
2018-02-08 09:31:38.090 [error][tid:com.facebook.react.JavaScript] Module AppRegistry is not a registered callable module (calling runApplication)
2018-02-08 09:31:38.090165+0000 FB[658:508728] Module AppRegistry is not a registered callable module (calling runApplication)
2018-02-08 09:31:38.101757+0000 FB[658:508707] *** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: Super expression must either be null or a function, not string', reason: 'Unhandled JS Exception: Super expression must either be null or a function,..., stack:
inherits@11:1777
<unknown>@300:387
<unknown>@300:810
a@2:837
<unknown>@12:86
a@2:837
<unknown>@2:309
global code@362:9
'
*** First throw call stack:
(0x18118a364 0x1803d0528 0x18118a2ac 0x100d3982c 0x100d374f0 0x181191cd0 0x18107056c 0x18107501c 0x100d4a4ec 0x100d8a208 0x100d89f68 0x1013652cc 0x10136528c 0x101373f80 0x1013687ec 0x101374f6c 0x10137c020 0x180daef1c 0x180daeb6c)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

This is before editing any file in the project. Just create, build and run.

My Xcode project build phase script is standard and unchanged:

`export NODE_BINARY=node
../node_modules/react-native/scripts/react-native-xcode.sh`

**Reproducible Demo**

A project I created using the steps above can be found here - https://github.com/jackdewhurst/TestReactNative

Thanks!

**Comment by hramos** [comment] 2018-02-09 20:40
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue that meets the requirements set forth in the template. Thanks!

**Closed by hramos** 2018-02-09 20:40 UTC
Labels: Failed Commands

**Comment by jackdewhurst** [comment] 2018-02-09 21:32
I've created the issue again after following the template. Please see here:

https://github.com/facebook/react-native/issues/17930
