### ISSUE TITLE
onPress not called after holding a button for longer than a second (iOS) (since 0.62)

### ISSUE THREAD

**Issue by dylancom** [facebook/react-native#29040] opened 2020-06-03 07:56 UTC
##  Description
Since upgrading to 0.62.2 it seems that every "React Native" button (Button, TouchableHighlight etc.) cancels the onPress when pressing a button for longer than a second.
I have an app still running on 0.61.5 and there it will still call the onPress after holding a button for longer than a second and releasing it.
Is this any new intended behavior? Native libraries like: https://github.com/react-native-community/segmented-control don't have this behavior.

## React Native version:
0.62.2

## Steps To Reproduce
1. Create a new project with `npx react-native init AwesomeProject`
2. Press any of the buttons below "Learn More" for longer than a second and release.

## Expected Results
I expected that the onPress would be called and I am redirected to the corresponding docs.
In an Expo snack, I am still seeing the expected results: https://snack.expo.io/@dylancom/2d8052
Probably due to that Expo SDK 37 is using React Native 0.61 

## Code example:
```
import { Button } from 'react-native';

<Button
  onPress={() => alert('I should be called')} 
  title="Hold for > a second and release"
/>
```

**Comment by jeswinsimon** [comment] 2020-06-04 12:19
This has been fixed in https://github.com/facebook/react-native/commit/9b81232ed2cc2beaf06a34ffe2279612f435f931.

**Comment by safaiyeh** [comment] 2020-09-02 16:05
Thank you for the issue @dylancom and thank you @jeswinsimon for finding the fix.

@dylancom can you confirm that commit has solved your issue? If so, feel free to close

**Comment by NickGerleman** [comment] 2020-09-02 18:54
@kander425 was running into the same issue. I was able to repro it on a newer build than the commit referenced.

The root cause is a change in behavior when migrating Touchables to use `Pressability` internally. Previously Touchable `_performSideEffectsForTransition` special cased moving out of long press state to fire onPress if no long press handler is available. Pressability instead will by default explicitly cancel the press if a long-press is detected. A property on the pressability config can control this, but is deprecated and not set on Touchables:
![image](https://user-images.githubusercontent.com/835219/92024390-01e27000-ed13-11ea-8c65-8f794929f49c.png)

This seems like cancelling press was an intentional behavior, but it is a breaking one and seems a bit strange.

**Comment by yungsters** [comment] 2020-09-10 21:53
@NickGerleman, I am having trouble reproducing this bug. This is what I am using:

```js
export default function Playground(props) {
  return (
    <Pressable
      onPress={() => console.warn('Pressed!')}
      style={({pressed}) => ({
        backgroundColor: pressed ? '#eee' : '#fff',
        padding: 10,
      })}>
      <Text>Press me!</Text>
    </Pressable>
  );
}
```

Regardless of how long I hold down the element, "Pressed!" gets logged.

Even though your original post mentions not supplying `onLongPress`, I'll mention for completeness that if I add an `onLongPress` prop like this:

```js
export default function Playground(props) {
  return (
    <Pressable
      onLongPress={() => console.warn('Long Pressed!')}
      onPress={() => console.warn('Pressed!')}
      style={({pressed}) => ({
        backgroundColor: pressed ? '#eee' : '#fff',
        padding: 10,
      })}>
      <Text>Press me!</Text>
    </Pressable>
  );
}
```

When I press longer than 500ms, "Long Pressed!" gets logged, but "Pressed!" does not. This is the expected behavior.

**Comment by yungsters** [comment] 2020-09-10 22:00
@NickGerleman, let me also clarify `_performTransitionSideEffects` and `onLongPressShouldCancelPress_DEPRECATED`.

The logic of `_performTransitionSideEffects` in `Pressability` mirrors that of `Touchable`. This is the code in Pressability: https://github.com/facebook/react-native/blob/master/Libraries/Pressability/Pressability.js#L690-L694

According to this logic, we will fire `onPress` unless all of the following are true:

- `onLongPress` is is supplied
- `prevState` is `RESPONDER_ACTIVE_LONG_PRESS_IN` (meaning we fired `onLongPress`)
- `onLongPressShouldCancelPress_DEPRECATED` is either not supplied, or it is supplied and returns true

As you can see, if `onLongPress` is not supplied, we will always invoke `onPress` regardless of how long you press down.

Lastly, `onLongPressShouldCancelPress_DEPRECATED` was deprecated in `Pressability` because triggering both `onLongPress` and `onPress` is a poor user interaction. One valid use case of supplying both callbacks is if `onLongPress` is conditionally invoked, but in those situations, it should be simpler to conditionally supply `onLongPress`.

**Comment by NickGerleman** [comment] 2020-09-10 23:09
@yungsters it looks like the issue is specifically for `Touchable` using `Pressability`. At least for TouchableHighlight, the pressabilty config creates always provides an `onLongPress` function, even if no `onLongPress` prop is set on the Touchable. See this in TouchableHighlight:
```
  _createPressabilityConfig(): PressabilityConfig {
    return {
   ...
      onLongPress: event => {
        if (this.props.onLongPress != null) {
          this.props.onLongPress(event);
        }
      },
```

`Pressable` directly forwards its own prop instead, so it doesn't seem to exhibit the issue.

Thanks for clarifying how the logic works. I totally misunderstood part of it. Somehow when using the source-mapped file, Chrome was reporting a state of `onLongPress` undefined, but `isPressCancledByLongPress` as true. I pointed the debugger to the actual bundle and it showed the event handler defined in Touchable though. 
![image](https://user-images.githubusercontent.com/835219/92821216-ad2c9e00-f37f-11ea-9fee-68253da804e7.png)

**Comment by yungsters** [comment] 2020-09-11 23:59
Ahh… good catch. This was a mistake on my part in the migration for `TouchableBounce` (not technically exported in the Public API) and `TouchableHighlight`. I'll send a fix for it right now.

**Closed** 2020-09-12 02:06 UTC
Labels: Component: Button, Needs: React Native Team Attention, Platform: iOS, Resolution: Fixed

**Comment by TomasSestak** [comment] 2020-12-10 09:25
according to the scheme here https://reactnative.dev/docs/pressable, onPress shouldnt be called, but it is in my code

**Comment by TomasSestak** [comment] 2020-12-10 09:29
> according to the scheme here https://reactnative.dev/docs/pressable, onPress shouldnt be called, but it is in my code

ohh i solved it by addint onLongPress () => null

**Comment by yungsters** [comment] 2021-01-11 17:56
@TomasSestak Correct. If `onLongPress` is not supplied, `onPress` will be fired regardless of how long a user presses down.
