### ISSUE TITLE
in 0.44 packager doesn't  start automatically

### ISSUE THREAD

**Issue by AlphaDu** [facebook/react-native#14029] opened 2017-05-18 03:27 UTC
In window10 , after execute command "react-native run-android" and when apk built complete,packager.sh will excute  automatically in previous version ，but in 0.44,afer Build Successful, nothing happen~

**Comment by hramos** [comment] 2017-05-19 18:19
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

Can you make sure to fill out the new issue template?

**Closed by hramos** 2017-05-19 18:19 UTC
