### ISSUE TITLE
Has <ListView> infinite scroll and pull to refresh?

### ISSUE THREAD

**Issue by danicomas** [facebook/react-native#502] opened 2015-03-30 17:16 UTC
If the answer is YES. Anyone can give me an example?

**Comment by colinramsay** [comment] 2015-03-30 17:19
I believe the answer is NO :disappointed: 

Possible duplicate of: #121 ?

**Comment by danicomas** [comment] 2015-03-30 17:34
OMG It is a basic component :S

**Comment by colinramsay** [comment] 2015-03-30 17:35
Which is open source and available for improvement!

**Comment by ide** [comment] 2015-03-30 18:55
It does have infinite scrolling (look at the data source code) but a refresh control is separate. ++@colinramsay, it's all open source so build what you need.

**Comment by nicklockwood** [comment] 2015-03-30 22:35
IIRC, refreshControl is somewhat tricky to get working correctly outside of a UITableViewController.

**Comment by vjeux** [comment] 2015-04-01 02:41
Please see #502 for pull to request

**Closed by vjeux** 2015-04-01 02:41 UTC

**Comment by danicomas** [comment] 2015-04-01 10:38
Pull to refresh https://gist.github.com/jsdf/6930c0211e0dc5bf0227

**Comment by danicomas** [comment] 2015-04-01 10:45
Is it correct to use the event onEndReached for infinite scroll? I don't like because I need to have an array in js memory. :S

**Comment by danicomas** [comment] 2015-04-01 13:09
If I use this onEndReached in iOS simulator works great but in iPhone 4 the scroll sometimes causes a lazy/strange effect. It is posible a memory problem? 

Look this video with simulator iphone 4S iOS 7.1:
https://www.dropbox.com/s/101lfqwc0da9bir/VID_20150401_142655.mp4?dl=0

And this with physical iphone 4 iOS 7.1:
https://www.dropbox.com/s/ni8nwy5vxqbe58t/VID_20150401_144523.mp4?dl=0

My code is the following:



Could you reopen the issue?

**Comment by khanghoang** [comment] 2015-04-02 03:27
@danicomas check it out, it may help you https://github.com/facebook/react-native/issues/499

**Comment by bluemsn** [comment] 2015-05-14 08:02
+1 , @danicomas  I also found the problem. and did you fix it  ?

**Comment by danicomas** [comment] 2015-05-14 08:10
I have been disconnected in React the last month I can't help you sorry @bluemsn but I will try soon.

**Comment by khacanh** [comment] 2016-10-26 15:49
I'm late to this, but it may help others, I created a demo project for pull-to-refresh and endless scrolling here https://github.com/CodeLinkIO/ReactNative-Endless-Scrolling

**Comment by emretekince** [comment] 2017-03-07 11:13
https://facebook.github.io/react-native/docs/refreshcontrol.html
