### ISSUE TITLE
'react-native run-android' fails when space in path

### ISSUE THREAD

**Issue by A21z** [facebook/react-native#4144] opened 2015-11-16 00:35 UTC
Hello,

When working in a directory with a space in the path, the `react-native run-android` command fails with this message: 

```
/tmp/react native/AwesomeProject/node_modules/react-native/packager/launchPackager.command: line 15: /tmp/react: No such file or directory
Process terminated. Press <enter> to close the window
```

Steps to reproduce are quite straightforward: 
```
cd /tmp
mkdir "react native"
cd "react native"
react-native init AwesomeProject
cd AwesomeProject
react-native run-android
```

I'm on OSX 10.11.1 with node 5.0.0 npm 3.3.6 and react-native ^0.14.2

**Comment by ide** [comment] 2015-11-16 00:51
This is kind of silly but try using a directory without spaces.

**Comment by A21z** [comment] 2015-11-16 01:07
Yes, it works when I move my project in another directory with no space.
This is not blocking for me, but looks like a bug nonetheless.

**Comment by mkonicek** [comment] 2015-11-17 14:45
I believe this is a duplicate of https://github.com/facebook/react-native/issues/3474, will close this one.

**Closed by mkonicek** 2015-11-17 14:45 UTC
