### ISSUE TITLE
ios - react-native5.7: react-native/scripts/ios-install-third-party.sh

### ISSUE THREAD

**Issue by rccq17mj** [facebook/react-native#22771] opened 2018-12-24 04:43 UTC
- [ ] Review the documentation: https://facebook.github.io/react-native
  - [ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
      Memory: 202.14 MB / 16.00 GB
      Shell: 3.2.57 - /bin/sh
    Binaries:
      Node: 10.14.0 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        API Levels: 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.1, 26.0.2, 27.0.3, 28.0.1, 28.0.2
        System Images: android-23 | Android Wear ARM EABI v7a, android-23 | Android Wear Intel x86 Atom, android-23 | Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64
    IDEs:
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.6.3 => 16.6.3 
      react-native: ^0.57.7 => 0.57.7 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description

React-native 5.7 bug in ios:

When a space appears in the disk directory, (node_modules/react-native/scripts/ios-install-third-party.sh ) does not deal with the space, causing the directory file can't not be found, for example:

/Volumes/APP OSX/.../node_modules/react-native/scripts/ios-install-third-party.sh

On the command line it should be:
/Volumes/APP\ OSX/.../node_modules/react-native/scripts/ios-install-third-party.sh
or
"/Volumes/APP OSX/.../node_modules/react-native/scripts/ios-install-third-party.sh"

______________________________________________________________________________________________________________________________________________________

But the code in line 62 of ios-install-third-party.sh is:

SCRIPTDIR=$(cd $(dirname "$0") && pwd) // This will cause a compilation error in the directory with spaces

Should be changed to:

SCRIPTDIR=$(cd "$(dirname "$0")" && pwd)

## Reproducible Demo
![image](https://user-images.githubusercontent.com/29419878/50390996-3c8fb900-0779-11e9-8a08-a0e15dd1079d.png)

Reference question
https://stackoverflow.com/questions/45252182/react-native-build-failed-due-to-double-conversion

**Comment by bartolkaruza** [comment] 2018-12-29 10:33
Duplicate of https://github.com/facebook/react-native/issues/22521

Fixed by https://github.com/facebook/react-native/commit/0314fca63a035c95864e5b198e1fbd9a5ee1d2a7#diff-9454d908829d6560069c9c133a4efecb on master

@kelset close

**Comment by rickhanlonii** [comment] 2018-12-31 15:18
Thanks @bartolkaruza!

**Closed by rickhanlonii** 2018-12-31 15:18 UTC
Labels: 🔷iOS
