### ISSUE TITLE
Project from react-native init no longer includes __tests__ directory

### ISSUE THREAD

**Issue by ashfurrow** [facebook/react-native#19761] opened 2018-06-16 16:47 UTC
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment

This is not applicable to my issue because the bug I'm reporting is around `react-native init`, but here's what info I get from running the command within the generated folder:

```sh
➜  bin > react-native --version
react-native-cli: 2.0.1
react-native: n/a - not inside a React Native project directory
➜  bin > cd MyAwesomeProject
➜  MyAwesomeProject > react-native info
Scanning folders for symlinks in /Users/ashfurrow/bin/MyAwesomeProject/node_modules (44ms)

Environment:
  OS: macOS High Sierra 10.13.5
  Node: 8.4.0
  Yarn: 1.6.0
  npm: 5.3.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4
```

I see this isn't using the latest React Native version, but it is using the latest `react-native-cli` version.

## Description

The project generated by running `react-native init` no longer includes a `__tests__` directory. At some point, it did but I can't find where in the changelog that it was removed.

The `init` command appears to pull in the template from [this directory of the repo](https://github.com/facebook/react-native/tree/aba4ec0c0984caf3bec75a803080bd95722b35db/local-cli/templates/HelloWorld), which includes a `__tests__` directory, but I took a look around and I'm not sure what the problem is. I'm happy to help provide more details or dive into debugging this with some guidance. Thanks!

## Reproducible Demo

In a terminal, run `react-native init TestApp` and then `cd` into the `TestApp` directory. 

Expected results: there is a `__tests__` directory with a basic test for `App.js`.

Actual results: there is no `__tests__` directory.

**Comment by hramos** [comment] 2018-06-16 20:53
Thanks for reporting this!

**Comment by ashfurrow** [comment] 2018-10-31 22:54
I just went through the reproduction steps outlined in my bug report and it appears to still be missing the directory.

```sh
➜  temp react-native --version
react-native-cli: 2.0.1
react-native: n/a - not inside a React Native project directory
➜  temp react-native init TestApp
[truncated]
➜  temp cd TestApp
➜  TestApp react-native info

  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz
      Memory: 3.21 GB / 32.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
      Yarn: 1.10.1 - ~/.nvm/versions/node/v8.12.0/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728
      react-native: 0.57.4 => 0.57.4
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

Updated React/Native versions but still no `__tests__` directory.

**Comment by hramos** [comment] 2019-01-14 19:10
The CLI was extracted from this repository, but the template still lives in this repo at https://github.com/facebook/react-native/tree/master/template. It's still the same template from when Ash first opened this issue, and the `__tests__` directory is still there.

The command line tools have their own repository and issue tracker over at https://github.com/react-native-community/react-native-cli, do you think you can cross-post over there since the issue is likely in the CLI code itself?

**Comment by ashfurrow** [comment] 2019-01-14 20:11
No problem. @hramos does this look sufficient? https://github.com/react-native-community/react-native-cli/issues/88 Should we close this issue, then?

**Comment by hramos** [comment] 2019-01-15 19:17
Thanks for migrating the issue, let me close this one.

**Closed by hramos** 2019-01-15 19:17 UTC
Labels: ⚠️Regression, 💻CLI, 🔩Test Infrastructure
