### ISSUE TITLE
Animation done in onScroll flickers on iOS

### ISSUE THREAD

**Issue by arshidkv12** [facebook/react-native#24826] opened 2019-05-13 07:02 UTC
Vibrating while scrolling. 
```
const AnimatedFlatList       = Animated.createAnimatedComponent( FlatList );

<AnimatedFlatList
                    style={{transform: [{ translateY: headerHeight }]}}
                    contentContainerStyle={{ 
                        minHeight: SCREEN_HEIGHT - HEADER_MAX_HEIGHT,
                        paddingTop: 0,
                        paddingBottom: HEADER_MIN_HEIGHT,
                        marginTop:3,
                    }}
                    scrollEventThrottle={16}
                    onScroll={Animated.event(
                        [{nativeEvent: { contentOffset: {y: this.scrollY}}}],
                        { useNativeDriver: true }
                    )}
                    refreshControl={
                        <RefreshControl
                            refreshing={false}
                            onRefresh={()=>alert(2)}
                        />
                    }
                    refreshing={()=>alert(99)}
                    keyExtractor={(item, i) => i.toString()}
                    data={[
                        {key: 'acc'}, {key: 'b'},{key: 'a'}, {key: 'b'},{key: 'a'}, {key: 'b'},
                        {key: 'acc'}, {key: 'b'},{key: 'a'}, {key: 'b'},{key: 'a'}, {key: 'b'},
                        {key: 'acc'}, {key: 'cc'},{key: 'a'}, {key: 'b'},{key: 'a'}, {key: 'b'},
                        {key: 'acc'}, {key: 'b'},{key: 'a'}, {key: 'b'},{key: 'a'}, {key: 'b'},
                        {key: 'acc'}, {key: 'cc'},{key: 'a'}, {key: 'b'},{key: 'a'}, {key: 'b'},
                        {key: 'acc'}, {key: 'b'},{key: 'a'}, {key: 'b'},{key: 'a'}, {key: 'b'},
                        {key: 'a'}, {key: 'zzzz'},]}
                    renderItem={({item}) => (
                        <VendorListItem
                            item={item}
                            style={{margin:7, marginLeft:10, marginRight:10}} 
                        />
                    )}
                />
```
React Native version:
 React Native Environment Info:
    System:
      OS: Linux 4.13 Ubuntu 16.04.4 LTS (Xenial Xerus)
      CPU: (4) x64 Intel(R) Core(TM) i3-2328M CPU @ 2.20GHz
      Memory: 418.91 MB / 9.60 GB
      Shell: 5.1.1 - /usr/bin/zsh
    Binaries:
      Node: 8.11.1 - /usr/bin/node
      Yarn: 1.9.4 - /usr/bin/yarn
      npm: 6.2.0 - /usr/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.0 AI-171.4443003
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.5 => 0.59.5 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-rename: 2.2.2
      react-native-run-android: 0.0.1
      svg-to-react-native-cli: 0.0.3

## Steps To Reproduce
Add translateY to FlatList animated component.

**Comment by kelset** [comment] 2019-05-13 09:16
I don't understand, is this a question? A bug?

**Comment by arshidkv12** [comment] 2019-05-13 09:23
Bug..

**Comment by kelset** [comment] 2019-05-13 09:31
Ok then, can you create a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting)? 

Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

**Comment by arshidkv12** [comment] 2019-05-13 10:12
I added code in expo. https://snack.expo.io/ryuNM6U24

Please check header (blue color) animation is vibrating, if we observe closely.

**Comment by kelset** [comment] 2019-05-13 17:04
Expo is still relying on RN 0.57.x, we'd need a `react-native init`-ed project to verify that it's still an issue on 0.59

**Comment by arshidkv12** [comment] 2019-05-13 17:24
I tried with RN 0.59 in laptop. I am getting same issue in Android.

**Comment by holospeed** [comment] 2019-05-24 10:47
I faced the same issue. At the version of 0.59.4 the animation was fluent, but at the version 0.59.8 the animation was "vibrating". I uploaded the "cleaned" version of my project so you can test it (I deleted every code from it except the animation).

**Here a gif about the animation with React Native version of 0.59.4**:

![ezgif-2-c05091a68aae](https://user-images.githubusercontent.com/3962013/58322179-83650600-7e20-11e9-8cea-59053bf47d5e.gif)
 
**And here here the same project with React Native version of 0.59.8**

![ezgif-2-873797cec2c1](https://user-images.githubusercontent.com/3962013/58322255-b4ddd180-7e20-11e9-8a52-3ece0a126b87.gif)


The repo of the project:
[https://github.com/holospeed/reactnativescrollviewanimation](https://github.com/holospeed/reactnativescrollviewanimation)

**Comment by kelset** [comment] 2019-05-27 12:07
Interesting, thanks for providing the repro! Given that now we know that it must be a commit we cherry picked between .4 and .8, do you have any idea of which one it may be?

**Comment by holospeed** [comment] 2019-05-28 17:20
It's looks like the problem appears since 59.7

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3962013/58497951-4fba1100-817d-11e9-9ea7-adbea4f75e36.gif)

59.6 looks fluent:
![rn59_6](https://user-images.githubusercontent.com/3962013/58497817-0e296600-817d-11e9-852f-3821d424d08f.gif)

**Comment by kelset** [comment] 2019-05-29 09:06
Thanks @holospeed for investigating - then I guess it's a matter of understanding which one of the commits cherry picked created this lag...

(btw AFAIK 0.59.7 is actually "not real", we had issues, so I feel it's one of the commits from 0.59.8 so here -> https://github.com/facebook/react-native/releases/tag/v0.59.8 and I'd bet it's likely that this is connected to the root cause: https://github.com/facebook/react-native/commit/74d740c97bc5e65c38e3090d6a87b2d6066b96f8)

**Comment by holospeed** [comment] 2019-05-29 17:35
I think this commit [39776a](https://github.com/facebook/react-native/commit/39776a82f0c) cause the issue. With the older version of  React/Views/ScrollView/RCTScrollView.m the animations looks fluent. ( I just removed the added codes, brought back the deleted ones and the scroll animation looked fluent again)

**Comment by kelset** [comment] 2019-05-30 10:16
Oh, interesting - thanks for looking into this! cc @sahrens, this sounds like it may need to be looked at

**Comment by sahrens** [comment] 2019-05-31 00:40
There was a bug in scroll throttling that caused this - should be fixed in https://github.com/facebook/react-native/commit/c87de765f6a9ebf656c188fa2115a1ba01b7939c

**Comment by wcandillon** [comment] 2019-05-31 13:02
This issue can be closed via https://github.com/facebook/react-native/commit/c87de765f6a9ebf656c188fa2115a1ba01b7939c

**Comment by kelset** [comment] 2019-05-31 13:22
Thanks for the info, I'll try to have that commit in the next 0.59 (since it's already in the 0.60 rc).

**Closed by kelset** 2019-05-31 13:22 UTC
Labels: Bug, Component: ScrollView, Impact: Regression, Platform: iOS
