### ISSUE TITLE
NavigatorIOS: resetTo keeps old rightButton

### ISSUE THREAD

**Issue by awiss** [facebook/react-native#894] opened 2015-04-17 02:35 UTC
When I attempt to call `navigator.resetTo(new_route) `with a new route, the rightButton the old page previously had is still there. This happens whether or not I have something in `new_route.rightButtonTitle` or not.

**Comment by MandarinConLaBarba** [comment] 2015-04-20 16:15
I also find it keeps the `title` and `rightButtonTitle`.

**Comment by Lapixx** [comment] 2015-04-22 12:22
The same thing seems to happen (or rather, not happen) when using `navigator.replace(new_route)`.

**Comment by michalvalasek** [comment] 2015-04-30 15:05
Same problem here (with `navigator.replace`).

**Comment by pwmckenna** [comment] 2015-05-04 18:02
I believe this is a duplicate of https://github.com/facebook/react-native/issues/476

**Comment by brentvatne** [comment] 2015-05-31 00:48
Indeed, same issue was #476

**Closed by brentvatne** 2015-05-31 00:48 UTC
