### ISSUE TITLE
ViewPropTypes has been removed from React Native...

### ISSUE THREAD

**Issue by mantegnous** [facebook/react-native#34865] opened 2022-10-04 15:42 UTC
### New Version

0.70.1

### Old Version

0.67.4

### Build Target(s)

ios android

### Output of `react-native info`

System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 1.97 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.15.0 - /usr/local/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/mantegnous/.rvm/gems/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.2.0 => 18.2.0 
    react-native: ^0.70.2 => 0.70.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

deprecated.. 

my package json:

  "dependencies": {
    "@gorhom/bottom-sheet": "^4.4.5",
    "@ptomasroos/react-native-multi-slider": "^2.2.2",
    "@react-native-async-storage/async-storage": "^1.17.10",
    "@react-native-firebase/analytics": "^15.7.0",
    "@react-native-firebase/app": "^15.7.0",
    "@react-native-firebase/crashlytics": "^15.7.0",
    "@react-navigation/bottom-tabs": "^6.4.0",
    "@react-navigation/material-top-tabs": "^6.2.4",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/stack": "^6.3.1",
    "@reduxjs/toolkit": "^1.8.5",
    "@stripe/stripe-react-native": "^0.19.0",
    "@ungap/url-search-params": "^0.2.2",
    "axios": "^0.27.2",
    "card-validator": "^8.1.1",
    "decimal.js": "^10.4.1",
    "fbjs": "^3.0.4",
    "i18next": "^21.9.2",
    "ibantools": "^4.1.4",
    "intl-pluralrules": "^1.3.1",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "patch-package": "^6.4.7",
    "prop-types": "^15.8.1",
    "qs": "^6.10.3",
    "react": "^18.2.0",
    "react-hook-form": "^7.36.0",
    "react-i18next": "^11.18.6",
    "react-native": "^0.70.2",
    "react-native-anchor-carousel": "^4.0.1",
    "react-native-appsflyer": "^6.9.1",
    "react-native-bootsplash": "^4.3.2",
    "react-native-color-matrix-image-filters": "^5.2.14",
    "react-native-config": "^1.4.4",
    "react-native-device-info": "^10.2.0",
    "react-native-dropdown-picker": "^5.4.0",
    "react-native-elements": "^3.4.2",
    "react-native-error-boundary": "^1.1.16",
    "react-native-fast-image": "^8.6.1",
    "react-native-gesture-handler": "^2.6.1",
    "react-native-google-places-autocomplete": "^2.4.1",
    "react-native-input-spinner": "^1.7.12",
    "react-native-keyboard-manager": "^6.5.4-4",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-mask-text": "^0.11.0",
    "react-native-pager-view": "^6.0.0",
    "react-native-reanimated": "^2.10.0",
    "react-native-safe-area-context": "^4.3.4",
    "react-native-screens": "^3.17.0",
    "react-native-snackbar-component": "^1.1.12",
    "react-native-step-indicator": "^1.0.3",
    "react-native-svg": "^13.2.0",
    "react-native-swipe-list-view": "^3.2.9",
    "react-native-tab-view": "^3.2.1",
    "react-native-textindicator-sectionlist-sidebar": "0.0.16",
    "react-native-tracking-transparency": "^0.1.2",
    "react-native-use-keyboard-height": "^0.1.1",
    "react-native-vector-icons": "^9.1.0",
    "react-redux": "^8.0.4",
    "redux-persist": "^6.0.0",
    "redux-saga": "^1.2.1",
    "sp-react-native-in-app-updates": "^1.2.0",
    "use-redux-effect": "^1.1.4"
  },
  "devDependencies": {
    "@babel/core": "^7.19.3",
    "@babel/runtime": "^7.19.0",
    "@react-native-community/eslint-config": "^3.1.0",
    "babel-jest": "^29.1.2",
    "babel-plugin-module-resolver": "^4.1.0",
    "eslint": "^8.23.1",
    "eslint-import-resolver-babel-module": "^5.3.1",
    "eslint-plugin-import": "^2.26.0",
    "jest": "^29.1.2",
    "metro-config": "^0.72.3",
    "metro-react-native-babel-preset": "^0.72.3",
    "prettier": "^2.6.2",
    "react-native-codegen": "^0.70.5",
    "react-native-svg-transformer": "^1.0.0",
    "react-native-touchable-scale": "^2.2.0",
    "react-test-renderer": "^18.2.0"
  },
  "jest": {
    "preset": "react-native"
  }

**Comment by rahulnainwal107** [comment] 2022-10-05 13:17
It looks like this issue is related to [#34614](https://github.com/facebook/react-native/pull/34614).

**Comment by cortinico** [comment] 2022-10-05 17:33
Closing as a duplicate of https://github.com/facebook/react-native/issues/33734
Please find the suggested solution over there

**Closed by cortinico** 2022-10-05 17:33 UTC
Labels: Needs: Triage :mag:, Type: Upgrade Issue
