### ISSUE TITLE
Webview causing Error on Android 7 and greater 

### ISSUE THREAD

**Issue by Muneefm** [facebook/react-native#14361] opened 2017-06-07 10:39 UTC
While clicking on html select from webview  the app force close on  android 7 and greater. 

```
06-07 15:16:50.875 14797 14797 W System.err: android.view.InflateException: Binary XML file line #26: Binary XML file line #44: Error inflating class com.android.internal.widget.DialogTitle
06-07 15:16:50.876 14797 14797 W System.err: Caused by: android.view.InflateException: Binary XML file line #44: Error inflating class com.android.internal.widget.DialogTitle
06-07 15:16:50.876 14797 14797 W System.err: Caused by: java.lang.reflect.InvocationTargetException
06-07 15:16:50.876 14797 14797 W System.err: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
06-07 15:16:50.876 14797 14797 W System.err: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
06-07 15:16:50.876 14797 14797 W System.err: 	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
06-07 15:16:50.876 14797 14797 W System.err: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
06-07 15:16:50.876 14797 14797 W System.err: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
06-07 15:16:50.876 14797 14797 W System.err: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
06-07 15:16:50.876 14797 14797 W System.err: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
06-07 15:16:50.876 14797 14797 W System.err: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
06-07 15:16:50.876 14797 14797 W System.err: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
06-07 15:16:50.876 14797 14797 W System.err: 	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:994)
06-07 15:16:50.876 14797 14797 W System.err: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:854)
06-07 15:16:50.876 14797 14797 W System.err: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
06-07 15:16:50.876 14797 14797 W System.err: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
06-07 15:16:50.876 14797 14797 W System.err: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
06-07 15:16:50.876 14797 14797 W System.err: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
06-07 15:16:50.876 14797 14797 W System.err: 	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:423)
06-07 15:16:50.876 14797 14797 W System.err: 	at com.android.internal.app.AlertController.installContent(AlertController.java:252)
06-07 15:16:50.876 14797 14797 W System.err: 	at android.app.AlertDialog.onCreate(AlertDialog.java:423)
06-07 15:16:50.876 14797 14797 W System.err: 	at android.app.Dialog.dispatchOnCreate(Dialog.java:395)
06-07 15:16:50.876 14797 14797 W System.err: 	at android.app.Dialog.show(Dialog.java:294)
06-07 15:16:50.876 14797 14797 W System.err: 	at org.chromium.content.browser.input.SelectPopupDialog.show(SelectPopupDialog.java:144)
06-07 15:16:50.876 14797 14797 W System.err: 	at org.chromium.content.browser.ContentViewCore.showSelectPopup(ContentViewCore.java:1948)
06-07 15:16:50.876 14797 14797 W System.err: 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
06-07 15:16:50.876 14797 14797 W System.err: 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:41)
06-07 15:16:50.876 14797 14797 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-07 15:16:50.876 14797 14797 W System.err: 	at android.os.Looper.loop(Looper.java:154)
06-07 15:16:50.876 14797 14797 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6290)
06-07 15:16:50.876 14797 14797 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
06-07 15:16:50.876 14797 14797 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
06-07 15:16:50.876 14797 14797 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
06-07 15:16:50.877 14797 14797 W System.err: Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 6: TypedValue{t=0x2/d=0x101009b a=1}
06-07 15:16:50.877 14797 14797 W System.err: 	at android.content.res.TypedArray.getColorStateList(TypedArray.java:528)
06-07 15:16:50.877 14797 14797 W System.err: 	at android.widget.TextView.<init>(TextView.java:783)
06-07 15:16:50.877 14797 14797 W System.err: 	at android.widget.TextView.<init>(TextView.java:704)
06-07 15:16:50.877 14797 14797 W System.err: 	at android.widget.TextView.<init>(TextView.java:700)
06-07 15:16:50.877 14797 14797 W System.err: 	at com.android.internal.widget.DialogTitle.<init>(DialogTitle.java:41)
```

### Additional Information

* React Native version: 0.44.0
* Platform: Android

**Comment by hramos** [comment] 2017-06-07 17:45
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-07 17:45 UTC

**Comment by aneesv** [comment] 2017-07-15 17:02
We have the same issue with android web view, App is crashing when user clicks on select inside webview
