### ISSUE TITLE
UI rendering deteriorates over time

### ISSUE THREAD

**Issue by richardbutler** [facebook/react-native#47410] opened 2024-11-05 12:36 UTC
### Description

On remounting of a given screen, components start to get corrupted in their rendering. It's predictable behaviour, the same deterioration follows the same pattern every time. If I build on the old architecture, everything is fine. I've struggled to put together a minimal reproduction for this, so I'm hoping that this rings a bell with one of the maintainers - perhaps some underlying object pooling that may be causing it?

### Steps to reproduce

Working on a reproduction, but wanted to get this into Fabric maintainers' thoughts for now.

### React Native Version

0.76.1

### Affected Platforms

Runtime - iOS

### Areas

Fabric - The New Renderer

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.4.1
  CPU: (10) x64 Apple M1 Max
  Memory: 194.60 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 23.1.0
    path: /usr/local/bin/node
  Yarn:
    version: 3.6.3
    path: /usr/local/bin/yarn
  npm:
    version: 10.9.0
    path: /usr/local/bin/npm
  Watchman:
    version: 2024.10.28.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2021.2 AI-212.5712.43.2112.8815526
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.1.0
    wanted: latest
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.1
    wanted: 0.76.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Stacktrace or Logs

```text
N/A
```

### Reproducer

Soon

### Screenshots and Videos

This is how the screen looks on the first mount, which is how the screen should look:
![Simulator Screenshot - iPhone 15 - 2024-10-30 at 09 26 32](https://github.com/user-attachments/assets/6ce18eca-8977-4cf2-b82d-8f7f7fc1c332)

Then second mount:
![Simulator Screenshot - iPhone 15 - 2024-10-30 at 09 26 40](https://github.com/user-attachments/assets/cf2e2c0c-3bf5-4f4d-aa79-51d463649fdb)

And so on:
![Simulator Screenshot - iPhone 15 - 2024-10-30 at 09 26 48](https://github.com/user-attachments/assets/0c8b5b40-16c1-474e-8241-61cc91ece9ff)

Until things really start to break:
![Simulator Screenshot - iPhone 15 - 2024-10-30 at 09 26 55](https://github.com/user-attachments/assets/3b6e79e5-969a-4de5-9e35-5d10655bc357)

And then we get some clipping (react-navigation stack):
![Simulator Screenshot - iPhone 15 - 2024-10-30 at 09 27 01](https://github.com/user-attachments/assets/829fa0da-a95f-4b40-a66a-3fc0bbcc4513)

**Comment by cortinico** [comment] 2024-11-05 13:44
> It's predictable behaviour, the same deterioration follows the same pattern every time

This feels like there might be something going on in your product code.
Without a repro that's hard to say. Have you tried to ask on StackOverflow?

**Comment by richardbutler** [comment] 2024-11-05 15:15
I've managed to isolate it to react-native-pager-view - when I remove this, the artifacts go away. It's odd though that it's only on iOS and new arch, which makes me think it's lower level.

**Comment by migueldaipre** [comment] 2024-11-05 16:11
Hey, Thanks for looking into this.

Is actually unrelated to React Native core. Please open this issue against this other repository:

https://github.com/callstack/react-native-pager-view/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.

also @troZee for visiblity

**Closed by migueldaipre** 2024-11-05 16:11 UTC
Labels: Resolution: Issue in another tool or repo

**Comment by meftunca** [comment] 2024-11-06 08:09
@migueldaipre Did you solve the problem? I'm still having the same problem

**Comment by richardbutler** [comment] 2024-11-06 12:12
Interesting @meftunca, your issue looks similar. No, I haven't found a fix yet, but it does look like pager view is the common component. If I remove pager view, the same UI renders correctly.

**Comment by meftunca** [comment] 2024-11-06 13:24
Hi @richardbutler , you have to request the issue to be reopened. Currently the issue is closed

**Comment by Chenjiujiu** [comment] 2024-11-18 03:52
It seems this issue is similar to the one I’m experiencing. Here, I provide a Snack

However, I feel this might be a “react-native” exception because even when I downgraded react-native-pager-view to a stable version, the issue still persisted.

https://snack.expo.dev/@saddhu/tab-style-abnormal?platform=ios 

# https://github.com/callstack/react-native-pager-view/issues/914

**Comment by Chenjiujiu** [comment] 2024-11-18 03:54
When navigating to the personal center and then returning repeatedly—around 13 times—the UI begins to exhibit anomalies, and subsequent occurrences of the issue become more frequent.

**Comment by Chenjiujiu** [comment] 2024-11-18 03:58
Can the issue be reopened? I have encountered it in my project and provided a snack

**Comment by alessandro-bottamedi** [comment] 2024-11-19 09:50
Same problem with similar packages (rn 0.76.2, expo 52.0.7, react-navigation 7.x, reanimated 3.16.1)

**Comment by migueldaipre** [comment] 2024-11-19 13:23
> Same problem with similar packages (rn 0.76.2, expo 52.0.7, react-navigation 7.x, reanimated 3.16.1)

Do you use `react-native-pager-view` too?

**Comment by alessandro-bottamedi** [comment] 2024-11-19 13:30
> > Same problem with similar packages (rn 0.76.2, expo 52.0.7, react-navigation 7.x, reanimated 3.16.1)
> 
> Do you use `react-native-pager-view` too?

Yes, react-native-pager-view v6.5.0, But I confirm that downgrading to RN 0.75.4 resolves the issue.

**Comment by migueldaipre** [comment] 2024-11-19 13:35
> > > Same problem with similar packages (rn 0.76.2, expo 52.0.7, react-navigation 7.x, reanimated 3.16.1)
> > 
> > Do you use `react-native-pager-view` too?
> 
> Yes, react-native-pager-view v6.5.0, But I confirm that downgrading to RN 0.75.4 resolves the issue.

Thanks, new or old architecture?

**Comment by cipolleschi** [comment] 2024-11-19 15:03
This issue is related to react-native-pager-view and the team is tracking it in this issue: https://github.com/callstack/react-native-pager-view/issues/914

Please, forward all the related problems to that issue.

I'm locking this conversation to reduce the noise. If you manage to repro the problem without the `react-native-pager-view` library, please open another issue in the react-native repository with a proper repo using this [template](https://github.com/react-native-community/reproducer-react-native).
