### ISSUE TITLE
Fail to build using Xcode 12 Beta 4

### ISSUE THREAD

**Issue by igoriols** [facebook/react-native#29633] opened 2020-08-12 20:49 UTC
## Description
When I try to build a project with Xcode 12 Beta 4 to test iOS14, I got a plenty of `Undefined symbols for architecture x86_64`. Every time I build the app, the list of errors is changed. Native libraries fail to recognize base React classes.

## React Native version:
```
info Fetching system and libraries information...
(node:16978) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 558.54 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.3.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /Users/laigorols/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 20.0, macOS 11.0, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.0/12A8179i - /usr/bin/xcodebuild
  Languages:
    Java: 12.0.1 - /usr/bin/javac
    Python: 2.7.16 - /Users/laigorols/.pyenv/shims/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Add native dependencies to `package.json`;
2. Install dependencies using `yarn install`;
3. Run `pod install` in ios folder to auto link native dependencies;
4. Try to run application in simulator using Xcode;

## Expected Results
Application is successfully installed and executed in simulator.

## Snack, code example, screenshot, or link to a repository:
Xcode error log: 
[Build Xcode12ReactNativeSample_2020-08-12T17-06-23.txt](https://github.com/facebook/react-native/files/5065612/Build.Xcode12ReactNativeSample_2020-08-12T17-06-23.txt)

Github repository with sample: https://github.com/igoriols/xcode12reactnativesample

**Comment by naveen-c** [comment] 2020-08-14 11:18
+1 facing the same issue ```Undefined symbols for architecture x86_64```

**Comment by xiao99xiao** [comment] 2020-08-16 13:59
+1 here. Only fails with Xcode 12 beta with Debug, while Release works. Xcode 11.6 works.

**Comment by igoriols** [comment] 2020-08-18 21:39
Hi @xiao99xiao, thank you for the workaround. Unfortunately, I can't use this in my real project. Another errors arise if I change to the legacy build system. Besides that, legacy build system is deprecated and is scheduled to be removed in a future Xcode release.

I think there is something missing in build settings, but I can't figure out what it is yet. Maybe we need to set a new configuration for the iOS's scripts.

Any help to solve this problem is appreciated.

**Comment by xiao99xiao** [comment] 2020-08-19 09:17
Update: issue still exists with Xcode 12 Beta 5. Also, upgrading Cocoapods to 1.10 beta doesn't help.

The issue seems to be related with React Native's Auto-linking. So building a React Native only project won't be affected, but if you bring in some libraries like react-native-safe-area or react-native-webview , the compiling fails.

After compare the affected targets and other React Native targets, seems `React.framework` is missing in the `Link Binary With Libraries` build phase for those auto-linked pods.

So I come up with a Workaround: 
Add a `post_install` in Podfile to manually add the `React.framework` back.

```ruby
post_install do |installer|
  #Workaround for Xcode 12 and Auto-Linking
  installer.pod_target_subprojects.each do |project|
    project.targets.each do |target|
      if ['react-native-netinfo', 'react-native-randombytes'].include?(target.name) #list all affected target in the array
        target.build_phases.each do |build_phases|
          if build_phases.display_name == 'Frameworks'
            file_ref = project.new(Xcodeproj::Project::Object::PBXFileReference)
            file_ref.path = 'React.framework'
            file_ref.source_tree = 'BUILT_PRODUCTS_DIR'
            build_phases.add_file_reference(file_ref)
          end
        end        
      end
    end
  end
end
```

Still, hope this could be fixed on React Native side.

**Comment by igoriols** [comment] 2020-08-19 15:13
Hi @xiao99xiao , thanks for your help. Just let me see if I understand it right: this is script adds `React.framework` to `Link Binary With Libraries` build phase for each native library pods (the ones Auto-linked) that uses react-native. Is that right?

I used the following script:
```ruby
post_install do |installer|
  #Workaround for Xcode 12 and Auto-Linking
  installer.pod_target_subprojects.each do |project|
    project.targets.each do |target|
      if ['RNCAsyncStorage', 'RNGestureHandler', 'RNPermissions', 'RNReanimated', 'RNScreens', 'RNShare', 'react-native-netinfo', 'react-native-safe-area-context', 'react-native-webview', 'rn-fetch-blob'].include?(target.name) #list all affected target in the array
        target.build_phases.each do |build_phases|
          if build_phases.display_name == 'Frameworks'
            file_ref = project.new(Xcodeproj::Project::Object::PBXFileReference)
            file_ref.path = 'React.framework'
            file_ref.source_tree = 'BUILT_PRODUCTS_DIR'
            build_phases.add_file_reference(file_ref)
          end
        end        
      end
    end
  end
end
```

The `Undefined symbols for architecture x86_64` errors persists and the script didn't add `React.framework` in `Link Binary With Libraries`. Did I miss something?
<img width="935" alt="Screen Shot 2020-08-19 at 12 00 17" src="https://user-images.githubusercontent.com/8026597/90651656-a775e980-e213-11ea-83ca-a51a8342c1b1.png">

I don't know if it means something for the issue, but there were a `React (pods)` in `Dependencies` section already. I thought the libs were importing react's dependencies this way:
<img width="960" alt="Screen Shot 2020-08-19 at 12 04 26" src="https://user-images.githubusercontent.com/8026597/90653098-2881b080-e215-11ea-8a63-9d17b15e1d07.png">

**Comment by naveen-c** [comment] 2020-08-19 16:19
@xiao99xiao thanks for the workaround, it's compiling for me now.


@igoriols you might need to update the script a bit as per your use case.
 
Pasting the script that worked for me:

```
  #Workaround for Xcode 12 and Auto-Linking
  installer.pods_project.targets.each do |target|
    if ['react-native-netinfo', 'react-native-shimmer', 'react-native-webview'].include?(target.name) #list all affected target in the array
      target.build_phases.each do |build_phases|
        if build_phases.display_name == 'Frameworks'
          file_ref = installer.pods_project.new(Xcodeproj::Project::Object::PBXFileReference)
          file_ref.path = 'React.framework'
          file_ref.source_tree = 'BUILT_PRODUCTS_DIR'
          build_phases.add_file_reference(file_ref)
        end
      end
    end
  end
```

**Comment by xiao99xiao** [comment] 2020-08-19 16:20
@igoriols Sorry, I forgot to mention that I used `:generate_multiple_pod_projects => true` in my Podfile.
Therefore my pod project structure is different from yours. 
You could either 
add `install! 'cocoapods', :disable_input_output_paths => true, :generate_multiple_pod_projects => true` to your Podfile and try again, 
or 
rewrite the code to adapt to your pod target structure. To be more specificly, the part below
```
installer.pod_target_subprojects.flat_map { |p| p.targets }.each do |target|
    target.build_configurations.each do |config|
```
should be replaced by
```
installer.pods_project.targets.each do |target|
```

**Comment by chrisglein** [comment] 2020-08-19 17:13
Sounds like there's a workaround available for now (other than not using the beta). Anyone here know what the fix would actually be to that native iOS implementation to address this on the inside? At some point beta not going to be beta anymore and this will need to be fixed.

**Comment by xiao99xiao** [comment] 2020-08-19 18:10
I think the easy way is to modify the packages/platform-ios/native_modules.rb file, to add the React.framework link dependency to each pod. However I have little knowledge about ruby, hope someone else could have a look at it.

The hard way is to dive deep and see why Xcode 12 requires a React.framework linking while Xcode 11 doesn't, which I don't have a clue yet.

**Comment by sudeepdino008** [comment] 2020-08-20 06:23
+1 having the same issue.

**Comment by igoriols** [comment] 2020-08-20 17:37
Thanks to @xiao99xiao and @naveen-c , I was able to use the following script to solve my problem with the workaround:

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    #Workaround for Xcode 12 and Auto-Linking
    if ['RNCAsyncStorage', 'RNGestureHandler', 'RNReanimated', 'RNScreens', 'RNShare', 'react-native-webview', 'react-native-safe-area-context', 'react-native-netinfo'].include?(target.name) #list all affected target in the array
      target.build_phases.each do |build_phases|
        if build_phases.display_name == 'Frameworks'
          file_ref = installer.pods_project.new(Xcodeproj::Project::Object::PBXFileReference)
          file_ref.path = 'React.framework'
          file_ref.source_tree = 'BUILT_PRODUCTS_DIR'
          build_phases.add_file_reference(file_ref)
        end
      end
    end
    if ['react-native-safe-area-context'].include?(target.name)
      target.build_phases.each do |build_phases|
        if build_phases.display_name == 'Frameworks'
          file_ref = installer.pods_project.new(Xcodeproj::Project::Object::PBXFileReference)
          file_ref.path = 'yoga.framework'
          file_ref.source_tree = 'BUILT_PRODUCTS_DIR'
          build_phases.add_file_reference(file_ref)
        end
      end
    end
  end
end
```
**I had to add `yoga.framework` to `react-native-safe-area-context`, also. 😕**

**Comment by bernica** [comment] 2020-09-17 00:02
Hi, my Xcode got updated to 12 today 😞 

How do you know what the affected targets are?

**Comment by alloy** [comment] 2020-09-17 12:07
Hi all 👋

Unfortunately I only just became aware of this ticket, so my apologies for the delay but thanks for the workarounds and the patience! 🙏

I tried the reproduction kindly provided by @igoriols and was able to determine the problem. The issue is that all the podspecs of these libraries that fail to link depend on the `React` pod, which is in fact really only an umbrella dependency for pure JS applications to depend on, whereas the native APIs that these libraries rely on _actually_ reside in the `React-Core` pod.

This means that they technically were always incorrect—conceptually one should always explicitly depend on the lib that provides the APIs you rely on, rather than relying on transitive dependencies—but it seems like in previous Xcode versions the build system worked differently and having the transitive dependencies around just happened to work 🤷‍♂️ 

The correct fix going forward is for all these libs to update their dependency from `React` to `React-Core`:

```diff
-  s.dependency 'React'
+  s.dependency 'React-Core'
```

To unblock yourself you could use something like [patch-package](https://github.com/ds300/patch-package) to temporarily hot-patch the podspecs you need, but it would be _really_ great for the longer term and the community if you could also submit that change upstream to the respective library 🙏 (See for example this [react-native-webview](https://github.com/react-native-community/react-native-webview/pull/1643) pull-request.)

**Closed by alloy** 2020-09-17 12:07 UTC
Labels: Needs: Issue Manager Attention, Platform: iOS

**Comment by alloy** [comment] 2020-09-17 12:24
Thanks @radko93 for jumping on all of these! 🙌

**Comment by mikehardy** [comment] 2020-09-17 18:37
Hi there! I have a bunch of modules like that should be affected (like react-native-device-info which @radko93 just PRd, thanks!).

I just updated to Xcode12. I'm trying the examples to demonstrate the problem.

My build is working fine? How do I demonstrate this failure? The example apps appear to work so which makes me uncomfortable, normally I like to have the first step of a PR verification be "demonstrate the problem" 🤔

**Comment by radko93** [comment] 2020-09-17 18:44
@mikehardy, not all modules are affected, I pointed out that I didn't test react-native-device-info yet. If you're sure it (you've cleaned the project etc) works you can dismiss this PR.

**Comment by mikehardy** [comment] 2020-09-17 18:52
Well, it seems like the right thing to do to depend on React-Core according to @alloy above, it is just weird that I can't reproduce in any modules I run so far (react-native-apple-authentication, react-native-firebase, react-native-device-info) or contribute to (react-native-background-fetch, react-native-background-gelocation[-android]) etc. I'll experiment some more.

Maybe it depends on some other Podfile setting (like use_frameworks or similar)

**Comment by mrousavy** [comment] 2020-09-17 19:19
@mikehardy I couldn't reproduce the issue _all_ the time, after a lot of cleaning and rebuilding I once had the error that a firebase package couldn't be built (that's why I've created the PR over there)

**Comment by mikehardy** [comment] 2020-09-17 19:21
So weird. Thanks for the extra info @mrousavy  Anyway, seems like the right thing to do based on comments here as I mentioned, so I'm pro- on all the PRs and will merge those in plus clean up the pile of other modules I've got commit on.

**Comment by alloy** [comment] 2020-09-17 22:26
@mikehardy I wonder if it could be related to the version of Xcode 12 you’re using. When I tried it this morning, I was able to easily reproduce it with Xcode 12 beta (4 or 5, would have to check). Could it be that you are using beta 6 or GM1?

**Comment by mikehardy** [comment] 2020-09-17 22:29
@alloy i was on gm regular install from app store after upgrade prompt, could be it... Still seems like the correct change though in your estimation?

**Comment by alloy** [comment] 2020-09-17 22:32
> Still seems like the correct change though in your estimation?

Without a doubt 👍

**Comment by mrousavy** [comment] 2020-09-18 07:14
I've used `React-Core` instead of `React` in my [`react-native-blurhash`](https://github.com/mrousavy/react-native-blurhash) library and can't build it anymore!

```
[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `react-native-blurhash` depends upon `React-Core`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
```

Anyone knows why? Should I just follow the suggested  workaround and add `use_modular_headers!`?

**Comment by mrousavy** [comment] 2020-09-18 07:21
Also, @mikehardy I think the firebase app package version hasn't been updated:

```
[!] NPM package '@react-native-firebase/messaging' depends on '@react-native-firebase/app' v8.4.2 but found v8.4.3, this might cause build issues or runtime crashes.

[!] NPM package '@react-native-firebase/ml-vision' depends on '@react-native-firebase/app' v8.4.2 but found v8.4.3, this might cause build issues or runtime crashes.

[!] NPM package '@react-native-firebase/perf' depends on '@react-native-firebase/app' v8.4.2 but found v8.4.3, this might cause build issues or runtime crashes.

[!] NPM package '@react-native-firebase/storage' depends on '@react-native-firebase/app' v8.4.2 but found v8.4.3, this might cause build issues or runtime crashes.

[!] NPM package '@react-native-firebase/messaging' depends on '@react-native-firebase/app' v8.4.2 but found v8.4.3, this might cause build issues or runtime crashes.

[!] NPM package '@react-native-firebase/ml-vision' depends on '@react-native-firebase/app' v8.4.2 but found v8.4.3, this might cause build issues or runtime crashes.

[!] NPM package '@react-native-firebase/perf' depends on '@react-native-firebase/app' v8.4.2 but found v8.4.3, this might cause build issues or runtime crashes.

[!] NPM package '@react-native-firebase/storage' depends on '@react-native-firebase/app' v8.4.2 but found v8.4.3, this might cause build issues or runtime crashes.

[!] NPM package '@react-native-firebase/ml-vision' depends on '@react-native-firebase/app' v8.4.2 but found v8.4.3, this might cause build issues or runtime crashes.

[!] NPM package '@react-native-firebase/messaging' depends on '@react-native-firebase/app' v8.4.2 but found v8.4.3, this might cause build issues or runtime crashes.

[!] NPM package '@react-native-firebase/perf' depends on '@react-native-firebase/app' v8.4.2 but found v8.4.3, this might cause build issues or runtime crashes.

[!] NPM package '@react-native-firebase/storage' depends on '@react-native-firebase/app' v8.4.2 but found v8.4.3, this might cause build issues or runtime crashes.
```

**Comment by alloy** [comment] 2020-09-18 09:11
@mrousavy From the CocoaPods [blog post](http://blog.cocoapods.org/CocoaPods-1.5.0/) about them:

> As a pod author, you can add `'DEFINES_MODULE' => 'YES'` to your `pod_target_xcconfig`.

Can you try adding that to your podspec?

**Comment by mrousavy** [comment] 2020-09-18 09:13
@alloy I have tried that, cleaned and rebuilt but I got the same error. It _works_ when I add `use_modular_headers!` in my app's Podfile, but that somehow seems like it has side effects..

**Comment by alloy** [comment] 2020-09-18 09:13
Let’s try to keep this issue on topic, as it’s lengthy enough as it is and otherwise people might miss the important bits when they come looking for solutions.

**Comment by alloy** [comment] 2020-09-18 09:16
> I have tried that, cleaned and rebuilt but I got the same error.

@mrousavy Did you use `pod update react-native-blurhash` after making the change? I don’t have experience with this feature, but it seems weird that it would work when specifying it in your Podfile but not in the podspec. Does it also work when you add `:modular_headers => true` to just that pod in your Podfile?

**Comment by mrousavy** [comment] 2020-09-18 09:26
@alloy Yes, I did update the package after making the change. Haven't tested if it also works if I manually add the pod using `:modular_headers => true` yet..

**Comment by mrousavy** [comment] 2020-09-18 10:48
So to summarize:

* Using `React-Core` instead of `React` as a dependency in the podspec requires modular headers to be true (for Swift native modules at least)
* Modular Headers cannot be set in the podspec (at least I couldn't manage to with using `pod_target_xcconfig = { "DEFINES_MODULE" => "YES" }`) but have to be set globally in your app's Podfile using `use_modular_headers!`
* By enabling use modular headers I am getting this build error: https://github.com/facebook/react-native/issues/26217

So right now this breaks my project. Anyone has an idea on how to fix this?

**Comment by alloy** [comment] 2020-09-18 10:51
@mrousavy If for your Swift based project things still work fine by depending on `React`, then perhaps keep doing that for now and file an issue on the CocoaPods repo with all the details and ask for help understanding the best recourse going forward.

**Comment by alloy** [comment] 2020-09-18 12:18
@mrousavy Upon re-reading, I think the problem actually is that the `React-Core` podspec needs `"DEFINES_MODULE" => "YES"`, can you try that?

**Comment by xiao99xiao** [comment] 2020-09-20 08:07
@alloy I suggest we reopen this issue, since there are still multiple cases where the issue is not resolved by the dependency change.

**Comment by mrousavy** [comment] 2020-09-20 09:17
To also make Swift native modules work, the React-Core pod needs to export `"DEFINES_MODULE" => "YES"` in it's Pod config (see: https://github.com/mrousavy/react-native-blurhash/issues/58#issuecomment-695127168)

**Comment by alloy** [comment] 2020-09-20 15:31
@mrousavy I’ll make that change this week.

@xiao99xiao Can you outline those issues? Are they different than the issue @mrousavy was still having with Swift based pods?

**Comment by Ravi448** [comment] 2020-09-21 08:08
I fixed the issue by updating all the libs and by creating an empty swift file within the project.

**Comment by heimi-block** [comment] 2020-10-03 12:51
> Hi all 👋
> 
> Unfortunately I only just became aware of this ticket, so my apologies for the delay but thanks for the workarounds and the patience! 🙏
> 
> I tried the reproduction kindly provided by @igoriols and was able to determine the problem. The issue is that all the podspecs of these libraries that fail to link depend on the `React` pod, which is in fact really only an umbrella dependency for pure JS applications to depend on, whereas the native APIs that these libraries rely on _actually_ reside in the `React-Core` pod.
> 
> This means that they technically were always incorrect—conceptually one should always explicitly depend on the lib that provides the APIs you rely on, rather than relying on transitive dependencies—but it seems like in previous Xcode versions the build system worked differently and having the transitive dependencies around just happened to work 🤷‍♂️
> 
> The correct fix going forward is for all these libs to update their dependency from `React` to `React-Core`:
> 
> ```diff
> -  s.dependency 'React'
> +  s.dependency 'React-Core'
> ```
> 
> To unblock yourself you could use something like [patch-package](https://github.com/ds300/patch-package) to temporarily hot-patch the podspecs you need, but it would be _really_ great for the longer term and the community if you could also submit that change upstream to the respective library 🙏 (See for example this [react-native-webview](https://github.com/react-native-community/react-native-webview/pull/1643) pull-request.)

help me a lot, thanks

**Comment by minhchienwikipedia** [comment] 2020-10-06 09:02
@heimi-block About another lib I had resolved it, but I'm getting an issue with RCTText and I check .podssec file I see this line`s.dependency "React-Core/RCTTextHeaders", version`, should I change this line?

Issue: ```Undefined symbols for architecture arm64:
  "_YGNodeIsDirty", referenced from:
      -[RCTBaseTextInputShadowView uiManagerWillPerformMounting] in RCTBaseTextInputShadowView.o
      -[RCTTextShadowView uiManagerWillPerformMounting] in RCTTextShadowView.o
  "_YGNodeMarkDirty", referenced from:
      -[RCTBaseTextInputShadowView dirtyLayout] in RCTBaseTextInputShadowView.o
      -[RCTTextShadowView dirtyLayout] in RCTTextShadowView.o
  "_YGNodeSetDirtiedFunc", referenced from:
      -[RCTBaseTextShadowView insertReactSubview:atIndex:] in RCTBaseTextShadowView.o
      -[RCTBaseTextShadowView removeReactSubview:] in RCTBaseTextShadowView.o
  "_YGNodeGetContext", referenced from:
      _RCTBaseTextInputShadowViewMeasure in RCTBaseTextInputShadowView.o
      _RCTTextInputShadowViewBaseline in RCTBaseTextInputShadowView.o
      _RCTInlineViewYogaNodeDirtied in RCTBaseTextShadowView.o
      _RCTTextShadowViewMeasure in RCTTextShadowView.o
      _RCTTextShadowViewBaseline in RCTTextShadowView.o
  "_YGNodeSetMeasureFunc", referenced from:
      -[RCTBaseTextInputShadowView initWithBridge:] in RCTBaseTextInputShadowView.o
      -[RCTTextShadowView initWithBridge:] in RCTTextShadowView.o
  "_YGNodeSetBaselineFunc", referenced from:
      -[RCTBaseTextInputShadowView initWithBridge:] in RCTBaseTextInputShadowView.o
      -[RCTTextShadowView initWithBridge:] in RCTTextShadowView.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)```

**Comment by alloy** [comment] 2020-10-06 09:18
@minhchienwikipedia Looks like the podspec _also_ needs a dependency on `React-Core/Default` (or perhaps just `React-Core`).

**Comment by minhchienwikipedia** [comment] 2020-10-06 10:15
@alloy This is Text component of react native, dependency of this component is 
```s.dependency "React-Core/RCTTextHeaders", version```
I had tried change to 
```s.dependency "React-Core/Default/RCTTextHeaders", version```
but CocaPods not find compatible versions

**Comment by alloy** [comment] 2020-10-06 15:03
Oh I missed that this is about one of RN’s own pods. Can you share a minimal example app that shows the problem?

**Comment by daanoz** [comment] 2020-10-08 06:43
We ran into the same, having to manage multiple repo's which different sets of dependencies with mixed versions, we had to manually patch many dependencies. So we ended up writing a little script that does the work for us, it a bit of a hack, but it works for us 🤷‍♂️ . Will share it here, but no guarantees it will work in your case as well. Place in the the root dir of your project, and run it on postinstall.

```js
const fs = require('fs')
const path = require('path')

/**
 * Temporary patch to fix all xCode 12 libs
 */

const nodeModulesDir = path.join(__dirname, 'node_modules');

const fetchRNPackageDirs = (dir) => {
    const dirList = fs.readdirSync(dir);
    const packageDirs = [];
    dirList.forEach(packageName => {
        const packageDir = path.join(dir, packageName);
        if (packageName.startsWith('@')) {
            packageDirs.push(...fetchRNPackageDirs(packageDir))
        } else {
            const files = fs.readdirSync(packageDir);
            const podSpecs = files.filter(file => file.toLowerCase().endsWith('.podspec'));
            if (podSpecs.length > 0) {
                packageDirs.push({
                    dir: packageDir,
                    files: podSpecs,
                    package: packageName
                });
            }
        }

    });
    return packageDirs;
}

const packagesWithPodSpec = fetchRNPackageDirs(nodeModulesDir);
const dependencyRegex = /(s\.dependency +(?:'|"))React('|")/;
packagesWithPodSpec.forEach(package => {
    package.files.forEach(file => {
        const filePath = path.join(package.dir, file);
        const fileContents = fs.readFileSync(filePath);
        if (fileContents.match(dependencyRegex)) {
            fs.writeFileSync(filePath, fileContents.replace(dependencyRegex, '$1React-Core$2'))
            console.log('[xCode12Fix] Patching: ' + filePath);
        }
    })
});
```

**Comment by xxsnakerxx** [comment] 2020-10-08 16:10
```bash
find ./node_modules -type f -name '*.podspec' | xargs sed -i.sed -e "s%'%\"%g"
find ./node_modules -type f -name '*.podspec' | xargs sed -i.sed -e 's%s.dependency[\t ]*"React"%s.dependency "React-Core"%g'
```

**Comment by jreedsch** [comment] 2020-11-06 18:13
I'm having a lot of issues building React Native 61.5 on XCode 12, but this helped me a bit. 

https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios/64139830#64139830

**Comment by dustinvforsyth** [comment] 2020-11-08 04:23
I started having build issues same as referenced above with Xcode 12.1 and React Native 0.63.2. It came up after trying to build a production branch (Had build hundreds of times with normal development builds). Production would never build but seemed to fail on a different packages. The post-install script that @igoriols posted was the only thing that solved my problem. I did have to add like 4 more packages to the package list in his script. I initially thought this was more specific to the other common problem with the new arm simulator stuff in Xcode but went through all those threads and tried everything with no success.

**Comment by Only-IceSoul** [comment] 2020-11-28 15:14
no problems here, xcode 12.0 - ios 14.

**Comment by HosseinRashno** [comment] 2020-12-09 14:29
You can use this script to fix the issue for all of your node modules:
https://gist.github.com/HosseinRashno/4786b289356ad9840b6c087ce8191fe4

Link to StackOverflow:
https://stackoverflow.com/a/65218722/4497248

**Comment by ahtisham09** [comment] 2020-12-18 09:21
I am running my app on IOS and getting error

Error in Xcode 14
module map file '/Users/macbook/Library/Developer/Xcode/DerivedData/Connect360-fkvotrokqjgczacuwgznybcvqqnp/Build/Products/Debug-iphonesimulator/FBSDKCoreKit/FBSDKCoreKit.modulemap' not found

my app is running fine on Xcode 11.6 i just update Xcode 12 from Xcode 11.6  and then i am getting this error i tried many things but its not working please help me i am stuck very badly

**Comment by mikehardy** [comment] 2020-12-18 14:24
@ahtisham09 have you tried `npx react-native-clean-project` ? it looks to me like you have some stale caches or similar.

**Comment by ahtisham09** [comment] 2020-12-18 14:34
@mikehardy  i tried every thing its not working

**Comment by chezhe** [comment] 2021-04-26 08:21
> Hi all 👋
> 
> Unfortunately I only just became aware of this ticket, so my apologies for the delay but thanks for the workarounds and the patience! 🙏
> 
> I tried the reproduction kindly provided by @igoriols and was able to determine the problem. The issue is that all the podspecs of these libraries that fail to link depend on the `React` pod, which is in fact really only an umbrella dependency for pure JS applications to depend on, whereas the native APIs that these libraries rely on _actually_ reside in the `React-Core` pod.
> 
> This means that they technically were always incorrect—conceptually one should always explicitly depend on the lib that provides the APIs you rely on, rather than relying on transitive dependencies—but it seems like in previous Xcode versions the build system worked differently and having the transitive dependencies around just happened to work 🤷‍♂️
> 
> The correct fix going forward is for all these libs to update their dependency from `React` to `React-Core`:
> 
> ```diff
> -  s.dependency 'React'
> +  s.dependency 'React-Core'
> ```
> 
> To unblock yourself you could use something like [patch-package](https://github.com/ds300/patch-package) to temporarily hot-patch the podspecs you need, but it would be _really_ great for the longer term and the community if you could also submit that change upstream to the respective library 🙏 (See for example this [react-native-webview](https://github.com/react-native-community/react-native-webview/pull/1643) pull-request.)

Any way to update all third libraries in Podfile with script?

**Comment by oferRounds** [comment] 2021-06-26 14:24
Hi @alloy seeing the same issue when trying to build my project on react-native 0.64.2 + hermes enabled + `use_frameworks!`
Is there any general patch I can add / post install script on cocoa pods?
