### ISSUE TITLE
TextInput onEndEditing doesn't work

### ISSUE THREAD

**Issue by iwanjunaid** [facebook/react-native#7275] opened 2016-04-28 12:47 UTC
I wonder why onEndEditing on TextInput doesn't work. Following code works well on onChangeText, but not on onEndEditing:

```javascript
<TextInput ref="title"
   placeholder="Type title here"
   style={styles.title}
   onEndEditing={(text) => console.log(text)}
   onChangeText={(text) => console.log(text)}
/>
```

my env:
- Ubuntu 14.04
- Android 4.2.2
- React Native 0.24

**Comment by dsibiski** [comment] 2016-04-28 20:36
Can you please include an example on rnplay.org?

**Comment by iwanjunaid** [comment] 2016-04-29 02:44
please take a look at this example at [https://rnplay.org/apps/SWvsRg](example)

**Comment by iwanjunaid** [comment] 2016-04-29 02:45
please take a look at this example [example](https://rnplay.org/apps/SWvsRg)

**Comment by dsibiski** [comment] 2016-04-29 10:58
It looks like it's not `onEndEditing` that is the problem...since it does work when you manually `blur` the textInput like in my example here: https://rnplay.org/apps/Wr_mWw

The problem seems to be that the "Enter" button, or the "Dismiss Keyboard" button, doesn't properly `blur` the textInput. You can see that when you dismiss the keyboard that textInput stays focused.

**Comment by dsibiski** [comment] 2016-04-29 11:05
It seems like this issue: https://github.com/facebook/react-native/issues/7047 is more appropriate for what you are experiencing. It seems like perhaps that is expected behavior for Android. Perhaps @satya164 can shed some light on that...

**Comment by iwanjunaid** [comment] 2016-04-29 11:40
Thank you for pointing it out. Just curious, are you experiencing the same problem on real android device without manually blur the TextInput ?

**Comment by dsibiski** [comment] 2016-04-29 11:56
@iwanjunaid Yes, I just ran the rnplay example on my real device and it has the exact same behavior.

**Comment by Tiagojdferreira** [comment] 2016-05-13 12:39
It seems onEndEditing does not get the value of text, but just the event.

In the docs:

````
onChangeText function 

Callback that is called when the text input's text changes. **Changed text is passed as an argument to the callback handler.**
````

Whereas:
````
onEndEditing function 

Callback that is called when text input ends.
````

What you were looking for was a onEndEditingText that unfortunately doesn't seem to exist. It would be great to have that, as that was also the behaviour that I expected.

**Comment by lacker** [comment] 2016-10-26 00:49
It sounds like this is more of a feature request than a bug at this point so I am going to close this issue. I encourage you to file feature requests on product pains though, or to send a pull request adding this event, because it does seem to be useful. If you do have some of this behavior that is a bug then I encourage you to open a new issue.

**Closed by lacker** 2016-10-26 00:49 UTC

**Comment by necolas** [comment] 2016-10-28 23:10
In what way does `onEndEditing` differ from `onBlur` (was looking to implement on web)?

**Comment by GantMan** [comment] 2016-11-28 18:50
@necolas - here's my attempt at answering this: http://stackoverflow.com/questions/34053315/difference-between-onendediting-and-onblur/40851395#40851395

**Comment by necolas** [comment] 2016-11-28 22:26
Thanks!
