### ISSUE TITLE
Touchable onPress not working with 3D Touch when 'position: absolute'

### ISSUE THREAD

**Issue by benadamstyles** [facebook/react-native#13845] opened 2017-05-08 13:53 UTC
### Description

I'm trying to consolidate the various issues around this into one place so it can finally be tackled. The related issues I have found are:

https://github.com/facebook/react-native/issues/3082 *
https://github.com/facebook/react-native/issues/10822
https://github.com/facebook/react-native/issues/10386

The issue is that `Touchable*#onPress` doesn't work on iOS devices with 3D Touch, if any pressure is applied, when the component wrapped by the `Touchable*` has `position: 'absolute'`. I think this has to do with `touchmove` events (or equivalent) being triggered by 3D Touch (possibly in the `z` direction?). A quick fix is to wrap your `Touchable*` in a `View`, giving this outer view `position: 'absolute'`, and removing `position: 'absolute'` from the `View` inside your `Touchable*`.

There is a related problem about the same incorrect behaviour applying to `Touchable`s within a ScrollView (see * above) but this involves `PanResponder` and becomes much more complicated. I have a feeling (totally unfounded) that fixing this bug might go some (or all the) way towards fixing that bug.

### Reproduction Steps and Sample Code

```js
// onPress never called if 3D Touch is present and any pressure is applied
<TouchableOpacity onPress={() => {}}>
  <View style={{position: 'absolute'}}>
    <Text>Press me</Text>
  </View>
</TouchableOpacity>
```

### Solution

I think this is a bug and requires either:

- Clear documentation telling the dev user that the first child of a `Touchable*` should not have `position: 'absolute'` (but the parent _can_)
- Or a `react-native` fix

### Additional Information

* React Native version: 0.43.0
* Platform: iOS (3D Touch enabled devices)
* Development Operating System: macOS

**Comment by linoleum00** [comment] 2017-05-18 16:18
In my case, the View inside the TouchableOpacity doesn't have the position absolute style, but if you press gently enough, it does work, but if you press normally then it doesn't work. 

I have seen some post in which the solution is to use onPressIn instead, and it does the trick but when you have a bunch of touchables inside a scroll view, then you can't scroll because the onPressIn is called immediately after touched

**Comment by Leeds-eBooks** [comment] 2017-05-18 16:25
> I have seen some post in which the solution is to use onPressIn instead, and it does the trick

@linoleum00 Another related reason why this solution is unsatisfactory is that if you use `onPressIn`, the user can't cancel their tap by moving their finger away, which is a fundamental aspect of touch interaction.

**Comment by hramos** [comment] 2017-07-20 22:23
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/touchable-onpress-not-working-with-3d-touch-when-position-absolute

**Comment by Leeds-eBooks** [comment] 2017-08-30 12:45
This is still an issue, and I have reproduced it on React Native v0.47. All the information required is in my original post above. Lack of activity `!==` resolution!

**Comment by IgorVanian** [comment] 2017-10-26 14:28
This is a big issue still in RN49. Actually [this](https://stackoverflow.com/a/42069488/7140328) looks like a solution but I guess it would be better to implement that inside RN itself.

**Comment by JLLLinn** [comment] 2017-12-15 09:58
Still an issue in 0.51

**Comment by deepaksasken** [comment] 2017-12-21 09:08
Yes, its still an issue in 0.51 :(

**Comment by batmaster** [comment] 2017-12-26 06:24
react-native: 0.51.0  still not work

**Comment by raimens** [comment] 2018-01-16 19:35
more the same

**Comment by philvasseur** [comment] 2018-03-28 20:40
still not working in 0.53.3, no other solutions seem to work for me.

**Comment by ashishbista** [comment] 2018-04-14 02:29
This is still an issue.

**Comment by kingr** [comment] 2018-04-25 08:10
Issue still exist.

**Comment by carmenchapa** [comment] 2018-05-03 12:54
Still an issue.

**Comment by DaMan02** [comment] 2019-01-06 17:42
RN 0.57.8 similar issue with button.

**Comment by cpojer** [comment] 2019-04-02 15:47
We noticed that very few people actually use 3D Touch so we recently removed a bunch of features related to it, so I'm going to close this as wontfix.

**Closed by cpojer** 2019-04-02 15:47 UTC
Labels: Help Wanted :octocat:, Type: Bug Report
