### ISSUE TITLE
Pressing Android back key does not call all listeners' handlers

### ISSUE THREAD

**Issue by dltmd6262** [facebook/react-native#9736] opened 2016-09-05 06:57 UTC
### Issue Description

In the source code comments it states that pressing the back key on Android will call the listeners' handlers and exit if none of them returns true.
However, the break in the for loop while calling the handlers blocks the rest of the handlers from being called.
### Steps to Reproduce / Code Snippets

Add multiple listeners for the Android back key and make any of them return true. Depending on the order the handlers are not called.
#### Expected Results

I expect all the listeners' handlers to be called and check the result of all handlers to see if default `exitApp` should be called
### Additional Information
- React Native version: [0.32.0]
- Platform(s) (iOS, Android, or both?): [Android]
- Operating System (macOS, Linux, or Windows?): [macOS]

Seems easy enough to send a pull request if needed

**Comment by DanielMSchmidt** [comment] 2016-09-06 06:09
@facebook-github-bot label android

**Comment by webzepter** [comment] 2016-09-06 08:40
@dltmd6262 Hello! `break` statement in https://github.com/facebook/react-native/commit/b8576312ca4a950d8bf4a5f4ec3a80c4f55d88b0 is a feature, not a bug 😅 .
Motivation: We use `BackAndroid` listeners to prevent closing screens with user's input.
When we have two screens in the stack (each screen with listener, which show alerts),
we want to show alert only from the last screen listener, not from all.

**Comment by dltmd6262** [comment] 2016-09-06 08:45
Oh, ok!
Just thought it would be better to let the different listeners decide what to do after the registered handlers are called.
Maybe the comments should be changed so we know that rest of the handlers won't be called if one returns true?

**Comment by webzepter** [comment] 2016-09-06 08:48
@dltmd6262 Yes, it would be nice to update `BackAndroid` docs

**Comment by mangogogos** [comment] 2016-09-06 16:40
Btw, if you really desire the behaviour that all listeners are called, you can always set up your own middleman to handle events. I.e. just subscribe to BackAndroid once and then set up your own EventEmitter that relays the event to all listeners

**Comment by charpeni** [comment] 2016-11-14 01:21
@facebook-github-bot label Icebox

**Comment by charpeni** [comment] 2016-11-14 01:21
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/pressing-android-back-key-does-not-call-all-listeners-handlers

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment] 2016-11-14 01:21
@facebook-github-bot close

**Comment by bunnyboy1** [comment] 2016-11-14 01:22
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (60/60 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter03.reliabledns.org ([69.175.33.179]:34794)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1c65y9-000Mq2-4d
	for bunny@thumbmunkeys.com; Mon, 14 Nov 2016 01:21:59 +0000
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193] helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by filter03.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1c65y8-0002T1-MZ
	for bunny@thumbmunkeys.com; Sun, 13 Nov 2016 18:21:57 -0700
Date: Sun, 13 Nov 2016 17:21:44 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1479086516;
	bh=MXNUEse/6MSjr1uH1elJmZF9aafhsvV29adMGjHcI00=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=QhUdro19hBeSl023O5fGEpW/h6uRUqj1VfoU7noia9B3L0WFhSNHlWa9wftZCdlva
	 pFra1U6dDUAXp2gVd7PwqKc7qLPS67eqtAnbgmK1aElJ9ER34S2QYrmCNZODm1jssJ
	 xSg+rgQKOAmq+xxcSFEezLl2iVpZVzLZjnnPCcFU=

**Comment by bunnyboy1** [comment] 2016-11-14 01:22
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (62/60 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:42465)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1c65yD-000Msp-IS
	for bunny@thumbmunkeys.com; Mon, 14 Nov 2016 01:22:02 +0000
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194] helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1c65yC-0003sM-7l
	for bunny@thumbmunkeys.com; Sun, 13 Nov 2016 18:22:01 -0700
Date: Sun, 13 Nov 2016 17:21:46 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1479086519;
	bh=48ivPCnTyEJ5XL8EkingFEP67hkfQlpI6DBnWi+gONc=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=MVo1JM1BbxIWqOTo5VzRxtgHKDUoPiKUDyjucGSgG6YMfIm4Jc+QK2c6m6lPk/25C
	 k2X6k6hawFMf0aiXWhPfFP+6gP196FO7KE90lMJsWkwxKyLiq0GTH7d7sqqQNi+1Hp
	 Lse4YFrB8GQgjmSZwbeWZ7e5VjTzNRKlPcI7TS3U=

**Comment by bunnyboy1** [comment] 2016-11-14 01:22
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (64/60 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:42476)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1c65yE-000MtP-FZ
	for bunny@thumbmunkeys.com; Mon, 14 Nov 2016 01:22:04 +0000
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195] helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1c65yD-0003sy-5l
	for bunny@thumbmunkeys.com; Sun, 13 Nov 2016 18:22:02 -0700
Date: Sun, 13 Nov 2016 17:21:51 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1479086520;
	bh=J1jg4DGbZvHspdZGqCJC5Jw95tYPHFaMPVHPr+W+Ujw=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=IC+AIBU/kC9HLqNeU6fGwGdj24NFzocrmE/R11D2sQ7xrRRkwtgFw1RnpyLxJHsUu
	 rnrekw5b7dKrKu0GCjsVzSxM/SzYPIxVuPjKNS4+BwdTDXPB68i8LqxQdNT/NujnIz
	 sOWQYD1EsXSbO6omQheKdmGUCASRwh67wQ/zqZyQ=

**Closed** 2016-11-14 01:24 UTC
Labels: Android, Icebox, Ran Commands
