### ISSUE TITLE
[iOS][0.27.2] Issue after upgrading from 0.26.2 to 0.27.2

### ISSUE THREAD

**Issue by rops** [facebook/react-native#8112] opened 2016-06-14 21:28 UTC
I'm experiencing a weird issue after upgrading to 0.27.2 on iOS ( with cocoapods ).

It seems like all the native modules became unavailable. 

This is the first error I get:

<img width="380" alt="screen shot 2016-06-14 at 15 51 36" src="https://cloud.githubusercontent.com/assets/693182/16060374/f6139180-324c-11e6-91d9-f655a563199a.png">

If I comment out `setupDevTools`, I bump into this one:

<img width="373" alt="screen shot 2016-06-14 at 15 52 02" src="https://cloud.githubusercontent.com/assets/693182/16060375/fa4684f6-324c-11e6-866d-f8503faaba20.png">

This is my pod setup:

```
  pod 'React', :path => '../../../node_modules/react-native', :subspecs => [
        'Core',
        'ART',
        'RCTActionSheet',
        'RCTAdSupport',
        'RCTCameraRoll',
        'RCTGeolocation',
        'RCTImage',
        'RCTNetwork',
        'RCTPushNotification',
        'RCTSettings',
        'RCTText',
        'RCTVibration',
        'RCTWebSocket',
        'RCTLinkingIOS'
    ]
```

Any ideas?

**Comment by alloy** [comment] 2016-06-14 22:49
Worked fine for me with CocoaPods and version 0.27.1, will update to 0.27.2 and test tomorrow.

**Comment by nickstamas** [comment] 2016-06-15 03:04
I'm having the same issue. It looks like something is happening on this line in /Libraries/react-native/react-native.js:

`var ReactNativeInternal = require('ReactNative');`

**Comment by ide** [comment] 2016-06-15 05:12
I ran into this issue too and fixed it by clearing Derived Data =P

**Comment by alloy** [comment] 2016-06-15 07:23
Sigh, classic.

I always start with a clean build https://github.com/artsy/emission/blob/master/package.json#L15-L16

**Comment by nickstamas** [comment] 2016-06-15 13:53
I've tried all the tricks, including clearing Derived Data, and still running into it.

**Comment by alloy** [comment] 2016-06-15 13:55
Did you re-run `pod install` after updating? Otherwise can you provide a sample app that reproduces it?

**Comment by rops** [comment] 2016-06-15 15:00
Clearing Derived Data did it for me! Thanks folks

**Comment by charpeni** [comment] 2016-06-17 19:22
@facebook-github-bot close

**Comment by facebook-github-bot-9** [comment] 2016-06-17 19:22
@charpeni tells me to close this issue. If you think it should still be opened let us know why.

**Closed by facebook-github-bot-9** 2016-06-17 19:22 UTC
Labels: Ran Commands
