### ISSUE TITLE
[Android] TextInput text is not displayed

### ISSUE THREAD

**Issue by UZIhuhuhu** [facebook/react-native#24067] opened 2019-03-20 15:03 UTC
## 🐛 Bug Report

The TextInput text is not displayed in Android but it performs well in IOS.

## To Reproduce

![image](https://user-images.githubusercontent.com/31771183/54694830-d80bac80-4b63-11e9-9d81-6af035758bf2.png)

![image](https://user-images.githubusercontent.com/31771183/54694876-ee196d00-4b63-11e9-9003-850de3c69bed.png)

## Code Example

```js
<TextInput
  style={styles.searchInput}
  placeholder={
    language
      ? 'Input Australian Address'
      : LanguageMap['Input Australian Address']
  }
  placeholderTextColor="#54636A"
  returnKeyType="search"
  autoFocus={isAutoFocus}
  editable={editable}
  pointerEvents={handlePress === noop ? 'auto' : 'none'}
  onChangeText={this.onChangeText}
  value={value}
  onSubmitEditing={handleSubmit}
  blurOnSubmit
/>;

const style = StyleSheet.create({
  searchInput: {
    flex: 1,
    color: '#36404a',
    paddingLeft: 8
  }
})
```

## Environment

  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Memory: 126.05 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.10.0 - ~/.nvm/versions/node/v10.10.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v10.10.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-26 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1
      react-native: ^0.57.7 => 0.57.8
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by rickhanlonii** [comment] 2019-03-20 15:12
Hey @UZIhuhuhu, thanks for filing - are you able to reproduce in a https://snack.expo.io to rule out any app code that is causing this?

**Comment by AkramEld** [comment] 2019-03-21 01:46
I tried replicating using a variety of methods. could not reproduce. would be helpful if you were able to show it on snackexpo like @rickhanlonii suggested

**Comment by JKCooper2** [comment] 2019-03-21 09:51
Unable to repro: https://snack.expo.io/@jkcooper/rn24067-textinput-text

**Comment by mirse** [comment] 2019-03-22 00:47
I also encountered this problem, which can be reproduced on some Android phones.,like Redmi 4A....

**Comment by UZIhuhuhu** [comment] 2019-03-22 11:07
I finally fix it. This bug is very unusual. Turns out that the actual size of TextInput's text is very small.

In Android, I need to expand the height of the parent container. However, it works well without this config in IOS.

```js
<TouchableOpacity style={{height: 40}}>
  <TextInput />
</TouchableOpacity>
```

**Comment by UZIhuhuhu** [comment] 2019-03-22 11:08
> I also encountered this problem, which can be reproduced on some Android phones.,like Redmi 4A....

You can try my method.

**Comment by kelset** [comment] 2019-03-22 11:53
👋 @UZIhuhuhu this seems to be an issue with your code, also based on your response.

Also, @JKCooper2 wasn't able to repro - which support the hypothesis; so I'll close this.

**Closed by kelset** 2019-03-22 11:53 UTC
Labels: Component: TextInput, Platform: Android, Resolution: Old Version, Type: Bug Report

**Comment by mirse** [comment] 2019-03-25 00:46
I set color in TextInput.
` <TextInput style={{color: '#000000',}} />`
It works.

**Comment by Fausto95** [comment] 2020-03-11 14:38
I could repro this issue on any Android device, I'm using react-native@59.9.
Could fix it by adding a height to the text input

```js
  input: {
    flex: 1,
    color: '#000',
    ...Platform.select({
      android: {
        height: 40
      }
    })
  }
```
