### ISSUE TITLE
[Android] onKeyPress event not fired for numeric keyboard

### ISSUE THREAD

**Issue by JasperVercammen** [facebook/react-native#19507] opened 2018-05-30 10:58 UTC
## Environment
OS: macOS High Sierra 10.13.4
Node: 8.9.4
Yarn: 1.6.0
npm: 6.0.1
Watchman: 4.7.0
Xcode: Xcode 9.3.1 Build version 9E501
Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.55.0 => 0.55.0

## Description
When using the non-default keyboard on Android, the onKeyPress event is not (or partly) fired.
For example, when using the numeric keyboard, pressing a number does not fire the event, but pressing the backspace does fire the event. 
It works fine for the default keyboard, or on iOS

## Steps to Reproduce
Issue can be seen with this snack: https://snack.expo.io/B1amtl3ym
Steps to reproduce: 
- Add a TextInput
- Attach the onKeyPress event
- Put the keyboardType on numeric
- Log when you come into the onKeyPress callback

## Expected Behavior
Call the onKeyPress callback when a key is pressed on the not default keyboard on android

## Actual Behavior
onKeyPress callback is NOT called for a numeric keyboard. (for the digits)

**Comment by joshyhargreaves** [comment] 2018-05-30 22:31
Let me take a look.

**Comment by taxidermic** [comment] 2018-07-13 10:15
Any updates? This issue is still present with` react-native: sdk-28.0.1.tar.gz`.
Maybe you need any additional info?

**Comment by pepf** [comment] 2018-08-23 08:57
The problem is still there using:
```
react-native-cli: 2.0.1
react-native: 0.56.0
```
Going top left to bottom right on all keys gives me the following output:
```
{key: "-"}
{key: " "} 
{key: "Backspace"}
{key: ","}
{key: "."}
```
Note: The enter key also doesn't work ( I was actually hoping to do something onSubmit, suggestions welcome ;) )

**Comment by ericjames** [comment] 2018-08-28 20:25
For the latest React Native, in a TextInput, typing numbers does not fire `oKeyPress` for Android 6.0 and below.   All letters and symbols do work.   Does not affect `onChangeText`

Android 7.0 has been working fine for me.

**Comment by charleston10** [comment] 2018-09-10 23:02
I also have the same problem

**Comment by neonsec** [comment] 2018-11-15 17:44
Any update on this issue? @joshjhargreaves

**Comment by poppiestar** [comment] 2019-04-24 11:14
Hi, I'm having the same problem with numeric keyboards not firing the onKeyPress event, which prevents my custom component from working in Android.

info
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
      Memory: 80.05 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.11.0 - ~/.nvm/versions/node/v11.11.0/bin/node
      npm: 6.9.0 - ~/.nvm/versions/node/v11.11.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 26, 28
        Build Tools: 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.5 => 0.59.5
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-create-bridge: 2.0.1

**Comment by cloverich** [comment] 2019-06-20 19:44
Related: https://github.com/facebook/react-native/issues/18339

**Comment by sarykemmoun** [comment] 2019-07-15 08:20
No solution yet?

**Comment by AhmadRaza786** [comment] 2019-07-31 19:08
Still facing the same issue even on the latest version `0.59`

**Comment by mieszko4** [comment] 2019-07-31 19:41
I am facing it with rn `0.59.10`
I still did not upgrade to rn `0.60`

**Comment by siddhi-sandy** [comment] 2019-08-01 08:09
There is a workaround you can use.
```
onChangeText={value => {
 if (this.checkNumber(value) == 1) {
//do the magic
}
}}
```
checkNumber is defined as:
```
checkNumber = num => {
    switch (num) {
      case "0":
        return 1;
        break;
      case "1":
        return 1;
        break;
      case "2":
        return 1;
        break;
      case "3":
        return 1;
        break;
      case "4":
        return 1;
        break;
      case "5":
        return 1;
        break;
      case "6":
        return 1;
        break;
      case "7":
        return 1;
        break;
      case "8":
        return 1;
        break;
      case "9":
        return 1;
        break;
      default:
        return 0;
        break;
    }
  };
```

**Comment by mieszko4** [comment] 2019-08-01 09:03
@siddhi-sandy Unfortunately this works only if text **did** change. I need it for case when text stays the same and I press a key.
For example, I have TextInput limited to one character with content `A`. When I focus this input my text is selected. When I press `A` I want it jump to next TextInput - but with this bug there is no way to detect that key was pressed with `onChangeText`

**Comment by blohamen** [comment] 2019-08-20 07:39
+1 issue still persist rn 0.60.4

**Comment by edipkavvas** [comment] 2019-10-01 23:52
Any workaround or solution???

**Comment by fawazahmed-makeen** [comment] 2019-11-08 10:00
The issue seems with android versions before Pie 9.0. Here's a workaround:
```
const phoneDigitKeyboardType = Platform.select({ ios: 'number-pad', android: 'numeric' });
const isUnsupportedVersion = Platform.OS === 'android' && Platform.Version < 28;

const onKeyReallyPressed= (key) => {
   // do something
  };

  const onChangeText = (text) => {
    if (!isUnsupportedVersion) return;
    onKeyReallyPressed(text.chatAt(text.length - 1));
  };

  const onKeyPressInput = ({ nativeEvent: { key } }) => onKeyReallyPressed(key);

  // text input
    <TextInput
      keyboardType={phoneDigitKeyboardType}
      onChangeText={onChangeText}
      onKeyPress={onKeyPressInput}
    />
}));
```

**Comment by clamiax** [comment] 2019-11-29 08:38
Same issue here, `onKeyPress` don't get fired with numbers on any `keyboardType`. I only tested on Android with RN 0.61.2. No workaround found yet except using `onChangeText` and eventually restore the previous value after a check. Though you can see the wrong character to be inserted and then removed from the input (which is horrible to me).

**Comment by ferrannp** [comment] 2020-01-29 15:08
From here:

https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditTextInputConnectionWrapper.java#L132-L136

It seems we are only firing it when we click `Backspace` or `Enter`. I am not really sure why though.

**Comment by santiagobts** [comment] 2020-03-19 15:03
So? I'm still having this issue, RN 0.59. Not event fired when numeric keyboard.

**Comment by MrLoh** [comment] 2020-06-17 15:51
this is simply an unsolved bug and should remain in the backlog.

**Comment by fabriziobertoglio1987** [comment] 2020-06-18 08:30
I disagree @MrLoh as I published a pull request https://github.com/facebook/react-native/pull/29046 to solve this so please test it and give a review. Thanks

**Comment by suberbawer** [comment] 2020-06-18 14:17
@fabriziobertoglio1987 thx!, i saw your commit, i'll test it and let you know. We can close this issue.

**Comment by fabriziobertoglio1987** [comment] 2020-06-18 14:50
@suberbawer thanks here a guide to build from source https://github.com/facebook/react-native/wiki/Building-from-source#publish-your-own-version-of-react-native 

if you have issues ask, I will assist you as I can. Biggest Step is installing ndk, but it was pretty easy for me using android studio depencies manager/updater

**Comment by clamiax** [comment] 2020-09-20 12:30
The bug is unsolved and should stay opened.

**Comment by ttlong3103** [comment] 2020-10-06 06:22
> @siddhi-sandy Unfortunately this works only if text **did** change. I need it for case when text stays the same and I press a key.
> For example, I have TextInput limited to one character with content `A`. When I focus this input my text is selected. When I press `A` I want it jump to next TextInput - but with this bug there is no way to detect that key was pressed with `onChangeText`

Did you solve your issue?

**Comment by ttlong3103** [comment] 2020-10-06 06:23
@mieszko4 Any solution for your issue?

**Comment by mieszko4** [comment] 2020-10-06 06:39
Nope, it works for me only if the entered character is different form the value of the input.
When it is different I can detect that with `onChangeText` and do some work (in my case I focus the next text input if it is not empty value (which would mean `backspace` clicked).
If it is the same `onChangeText` does not trigger.

I haven't touch this since then. Working good enough for my case.

**Comment by iagormoraes** [comment] 2020-12-12 17:49
I made it work with both `onChange` and `onKeyPress`, on handler I'm checking the platform then getting the property `key` for iOS and `text` for Android, but if the field is filled the listener don't get called.

**Comment by fabriziobertoglio1987** [comment] 2021-01-08 18:13
@iagormoraes requires changes in ReactAndroid as in my pr https://github.com/facebook/react-native/pull/29046
but it will not be enought using patch-package

**Comment by victorlmtavares** [comment] 2021-01-18 01:07
Having the same issue here. Trying to build a 2FA which the best UX is to, whenever a new character is pressed, it fills the next input field. However, without onKeyPress checking for numbers pressed on Android, I can`t get it done properly. Has anyone done it by any chance?

**Comment by vadimb** [comment] 2021-01-18 07:31
@victorlmtavares @fabriziobertoglio1987's PR https://github.com/facebook/react-native/pull/29046 has a fix for it. Hopefully it land soon.

If you could add a thumbs up there it will be great.

**Comment by fabriziobertoglio1987** [comment] 2021-03-16 16:00
> Please, is it possible to merge this PR in the next version ?

To answer the question of when the pr https://github.com/facebook/react-native/pull/29046 which fixes this issue will be released in the next version of React Native, I suggest you to follow the discussions at https://github.com/react-native-community/releases/issues by subscribing to those threads. The process of releasing a new version with a bug fix is the following:

- an Issue is opened in facebook/react-native
- a contributor writes a Pull Request to fix/close the react-native Issue
- The Pull Request is merged in Master
- For each realease (the upcoming one is 0.64.1) there will be a separate discussion on https://github.com/react-native-community/releases/issues where anyone can request a commit to be cherrypicked from master. The link need to be from the a **commit** from master (for ex. https://github.com/facebook/react-native/pull/29157#issuecomment-651430945) and not a Pull Request not yet merged in master :peace_symbol: :pray:

**Comment by jailsonpaca** [comment] 2021-05-18 01:30
same problem here

**Comment by JackStudd** [comment] 2021-06-25 07:33
Figured a quickfix which works while waiting for the fix to be released
In my case I only needed to get the numbers from the input, adapt for your case

```
const [text, setText] = React.useState('');

const [onKeyPress, onChangeText] = React.useMemo(() => {
  let handled = false;

  const onKeyPressManager = ({nativeEvent: {key}}, value) => {
    if (key === KEY_BACKSPACE && value) {
      setText(value.substring(0, value.length - 1));
      handled = true;
    }
  };

  const onChangeTextManager = (value) => {
    if (!handled) {
      setText(value?.replaceAll(/[^0-9]/g, ''));
    }
    handled = false;
  };

  return [onKeyPressManager, onChangeTextManager];
}, []);

const __onKeyPress = (event) => {
  onKeyPress(event, text);
};
```

**Closed** 2021-08-25 11:57 UTC
Labels: Platform: Android, Bug

**Comment by kartikeyvaish** [comment] 2021-08-29 18:39
This problem is still there.

**Comment by Adaverse** [comment] 2021-09-20 21:18
Problem still exists

**Comment by kartikeyvaish** [comment] 2021-09-20 21:21
Yes, its still exists.💔

**Comment by caner-karaman** [comment] 2021-11-15 08:24
Hi,

react-native: 0.65.1

I use TextInput component with keyboardType: 'num-pad', 
onKeyPress method is not fired. If I change keyboardType to default, it works very well

**Comment by 000xuandu** [comment] 2021-12-08 03:21
Same issue!

**Comment by joaohd98** [comment] 2021-12-17 19:06
Same error here!

**Comment by huyhai** [comment] 2022-05-16 04:24
same

**Comment by Bad-Listener** [comment] 2022-07-07 08:54
still exists

**Comment by Bad-Listener** [comment] 2022-07-07 09:01
but seems to work if you just implement onChangeText property with an empty arrow function, then onKeyPress will be fired for Android everytime!

**Comment by Matiassimone** [comment] 2022-08-08 19:48
Still persists,
on `"react-native": "0.68.2"`.

Using this `TextInput` with the follow props and `keyboardType="number-pad"`,
the numbers only trigger in the `onKeyPress`, 
`onChangeText` or `onChange` callbacks are NOT called when press numbers (1, 2, 3...).

```
      <TextInput
        autoFocus
        caretHidden
        contextMenuHidden
        onKeyPress={onKeyPress}
        ref={phoneRef}
        maxLength={6}
        autoCorrect={false}
        onChange={onChange}
        onChangeText={onChangeText}
        keyboardType="number-pad"
        textContentType="oneTimeCode"
        autoComplete="sms-otp"
        keyboardAppearance={isDarkMode ? 'dark' : 'light'}
        style={styles.nativeKeyboardHidden}
      />
```

**Comment by kotano** [comment] 2022-12-28 09:59
Guys, I had this problem, but it got resolved after I removed `display:none` from TextInput style.

**Comment by buraky84** [comment] 2023-03-21 09:51
"react-native": "0.71.3"

onChangeText => not triggering on Android with numeric keyboard.

onChange => callback works for me both on Android and IOS with numeric keyboard!

**Comment by mayander30** [comment] 2023-05-15 14:21
Any fix?
