### ISSUE TITLE
[Android] No API for updating props on android root component

### ISSUE THREAD

**Issue by jaredly** [facebook/react-native#6303] opened 2016-03-04 20:13 UTC
In iOS, you can do `rctRootView.appProperties = newProps`, and it will update the root view with new props. On android it doesn't seem to be implemented.

This behavior is critical for my use case of incrementally adopting react native in a large android app.

I think I want a function like `ReactRootView.updateProps(Bundle props)` that would look something like

``` java
public void updateProps(Bundle newProps) {
  WritableNativeMap appParams = new WritableNativeMap();
  Double rootTag = MagicallyGetTheRootTag() // <- the rootTag isn't actually stored anywhere at the moment
  appParams.putDouble("rootTag", rootTag);
  appParams.putMap("initialProps", newProps);
  final CatalystInstance catalystInstance = mReactInstanceManager.getCurrentReactContext().getCatalystInstance();
  String jsAppModuleName = this.getJSModuleName();
  catalystInstance.getJSModule(AppRegistry.class).runApplication(jsAppModuleName, appParams);
}
```

[based on the startReactApplication fn](https://github.com/facebook/react-native/blob/313d84d507689a78a9f4084b162ac87c09d7d5e3/ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManagerImpl.java#L683)

Before I made a PR I wanted to check my direction -- does it look reasonable? I think I'll have to store the rootTag on the ReactRootView instance, b/c I can't find anywhere else that it's already stored.

**Comment by brentvatne** [comment] 2016-03-06 19:31
@bestander - could you check this out to see if it's reasonable? This is part of getting parity with iOS, cc @mkonicek

**Comment by bestander** [comment] 2016-03-06 19:42
Will do on Tuesday

**Comment by brentvatne** [comment] 2016-03-06 20:38
:rocket:

**Comment by bestander** [comment] 2016-03-08 13:04
@jaredly go for it, we would appreciate this feature.
Ping me with the PR.

**Comment by jaredly** [comment] 2016-03-09 21:42
ok so my initial attempt was unsuccessful (pretty much doing what I outlined above), and we've decided not to invest in RN yet, so it's unlikely I'll dig into this further in the near future

**Comment by bestander** [comment] 2016-03-10 00:21
No worries, we'll do it eventually.
Would you mind giving feedback why you have decided to not proceed with RN right now?
Any particular pain or aspect you think we should address?

**Comment by jaredly** [comment] 2016-03-10 00:47
mostly immaturity of android, and to a lesser extent iOS. We have large apps that we're thinking of integrating react native into incrementally, which definitely isn't a well-documented use case. we're planning on doing further investigation in a few months and might have a different decision depending on how things have matured.

**Comment by bestander** [comment] 2016-03-10 15:55
:+1: 
Thanks, this gives some very important feedback.

**Comment by MikeOrtiz** [comment] 2016-06-07 01:06
@bestander What is the status of this feature request? My use case requires inserting a RN view in a native ListView. Removing and creating new react views doesn't allow for smooth scrolling and emitting events with prop updates sends the same props to all children.

Is the feature currently being worked on? If not, what might it involve to implement?

**Comment by satya164** [comment] 2016-06-07 08:01
@MikeOrtiz nobody is working on it right now. feel free to send a pull request.

**Comment by skeyboy** [comment] 2016-08-25 05:01
I want to get a data from Java to JS
   

**bundle.putString("value", "aValue");
   mReactRootView.startReactApplication(mReactInstanceManager, "IndexActivity", bundle);**

but, I can not get the value from **this.props.value**

**Comment by lacker** [comment] 2016-11-30 00:25
It sounds like this issue has played out, and we are keeping issues focused on bugs rather than feature requests at the moment, so I am going to close this issue. Feel free to send a pull request improving this though!

**Closed by lacker** 2016-11-30 00:25 UTC
Labels: Android, Feature Request

**Comment by jaredly** [comment] 2017-02-23 20:24
@brentvatne bump :P this is totally basic for having sane integration with an existing app

**Comment by tianxind** [comment] 2017-03-09 06:28
Bump this feature request. @brentvatne Or at least I think the lack of this feature on Android should be mentioned here: https://facebook.github.io/react-native/docs/communication-ios.html  It will save people from mistakenly assuming that it exists for Android.

**Comment by SunburtReynolds** [comment] 2017-03-20 21:48
+1

**Comment by TommyDevAll** [comment] 2017-06-07 11:21
Hi guys. Thank you for the amazing work you are doing with react.

Anyway i agree with @tianxind, someone should mention that Android is not ready to update props of a running component. I've lost half of my brain looking for a solution then a came here XD

**Comment by boliveira** [comment] 2018-07-12 08:54
Hi,

There is a method in ReactRootView called setAppProperties that does what is intended, I believe.
The problem is, like in iOS, the root component gets recreated instead of just updated (componentWillUnmount will be called and then the component will be recreated). Is this the intended behavior? Is there any way to just re-render the root component?
