### ISSUE TITLE
AnimatedValue addListener not working

### ISSUE THREAD

**Issue by vaibhawc** [facebook/react-native#11119] opened 2016-11-24 18:13 UTC
I have tried it hard, it doesn't seem to work. Any ideas?

**Comment by mkonicek** [comment] 2016-11-24 21:01
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but we can reopen if additional information is provided. Thanks!

**Closed by mkonicek** 2016-11-24 21:01 UTC
