### ISSUE TITLE
[FlatList] Locking scroll position in FlatList (and ScrollView)

### ISSUE THREAD

**Issue by guysegal** [facebook/react-native#14305] opened 2017-06-02 15:43 UTC
Hi,

I'm trying to create a FlatList that keeps the current scroll position locked and does not change by new items that are inserted at the top of the list.

I've created an [expo snack](https://snack.expo.io/ryUcWZ1fW) to demonstrate my intention:

The snack presents a ScrollView with green items, and a black item at the end. 
When the app launch it scrolls to the bottom of the list. After five seconds 10 items are inserted at the top, and the scroll position is changing according to the total size of these items.

I want to keep the scroll position locked, meaning - when items are inserted the scroll position will not change (or at least in a way the user doesn't know anything happened)

Is there a way to do it with the current API of FlatList and ScrollView? What's needed to be implemented to achieve this feature?

Thanks

**Comment by hramos** [comment] 2017-06-02 17:07
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-02 17:07 UTC

**Comment by AbdallaMohamed** [comment] 2017-09-15 09:15
@guysegal Did you find a solution to this problem? I've been struggling with it for a couple of days so far 😕

**Comment by guysegal** [comment] 2017-09-17 03:51
@AbdallaMohamed we are working a solution, we'll publish it when it'll be ready

**Comment by amirrezam** [comment] 2017-12-28 22:13
@guysegal Did you publish new version that fixed this problem ?

**Comment by sohobloo** [comment] 2018-02-13 07:57
Any solution?

**Comment by Shamash2014** [comment] 2018-03-27 20:43
Hey, @guysegal Any update on this? Lemme know if I can help!

**Comment by arashmilani** [comment] 2018-05-26 14:32
The commit for `maintainVisibleContentPosition` is https://github.com/facebook/react-native/commit/65184ec for anyone that is interested as the docs still not updated on this. Hoping to see the same for Android soon.
