### ISSUE TITLE
react-native run-android --variant=developmentDebug does not work currently.

### ISSUE THREAD

**Issue by ko-devHong** [facebook/react-native#35868] opened 2023-01-18 06:32 UTC
### Description

I bumped RN from 0.70.6 to 0.71.0

I used the command normally until 0.70.6 version, but it doesn't work from 0.71.0.

My guess is that the following line has been removed from `app/build.gradle`.

```
apply from: "../../node_modules/react-native/react.gradle"
```
Why was it deleted when it moved from version 70 to 71?

### Version

0.71.0

### Output of `npx react-native info`

System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 336.72 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.0.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.6.0 - /usr/local/bin/npm
    Watchman: 2023.01.16.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.0 => 0.71.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. run cli android // 
```
react-native run-android --variant=developmentDebug
...
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDebug' not found in project ':app'.
```

### Snack, code example, screenshot, or link to a repository

1. run cli android // 
```
react-native run-android --variant=developmentDebug
...
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDebug' not found in project ':app'.
```

**Comment by affansk** [comment] 2023-01-18 08:08
@ko-devHong please check here : https://github.com/facebook/react-native/issues/35838

**Comment by cortinico** [comment] 2023-01-18 10:07
Closing as a duplicate of https://github.com/facebook/react-native/issues/35838
The fix is forthcoming and will be shipped in a future point release.
For the time being you can use `--mode`.

**Closed by cortinico** 2023-01-18 10:07 UTC
Labels: Platform: Android, Needs: Triage :mag:
