### ISSUE TITLE
TextInput cursor not aligned in the centre when value is empty

### ISSUE THREAD

**Issue by ShivamJoker** [facebook/react-native#27658] opened 2020-01-03 09:16 UTC
When using TextInput with `textAlign: center`, the cursor is in the wrong position when the text is empty. It seems to be aligning with the placeholder.
![image](https://user-images.githubusercontent.com/23727670/71715526-a3898880-2e37-11ea-886c-0d20bb3289d4.png)

React Native version:

```
System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 185.86 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 23, 25, 27, 28
      Build Tools: 26.0.2, 28.0.1, 28.0.3
      System Images: android-25 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: /undefined - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native: 0.61.5
```

## Steps To Reproduce

```js
<TextInput placeholder='NAME'  textAlign={'center'}/>
```

## Expected Behaviour
The cursor should be in the middle of text input

**Comment by alisterrick** [comment] 2020-01-05 05:38
The same issue. I use the latest version v0.61.5

**Comment by s349856186** [comment] 2020-01-11 05:53
same issue, any update ?

**Comment by Joeelll** [comment] 2020-01-21 12:19
Same issue on the latest version. It happens for me when using textAlign and value parameter to control what user can submit.

**Comment by dung-dd** [comment] 2020-02-21 05:28
It still exists. tricks is use an space instead a empty string, imperfect but better the present

**Comment by alexsenichev** [comment] 2020-03-12 11:49
Same for me

**Comment by TeddyBearItsMe** [comment] 2020-04-15 16:10
Im also stuck with this issue, in the latest version

**Comment by flungloaf** [comment] 2020-06-19 10:51
Same here on v0.62.2

**Comment by outaTiME** [comment] 2020-06-24 05:46
Im using in the following way and it works:

```js
<TextInput
  style={[
    {
      textAlign: 'center',
      flex: 1,
    },
  ]}
/>
```

i hope it helps

**Comment by rhysdavies1994** [comment] 2020-06-25 04:35
Same issue here

Is there any progress on this?

**Comment by ShivamJoker** [comment] 2020-06-27 12:27
It's been 6 months what Facebook's React native team is doing ?

Why can't you fix such a minor issue ?

Maybe it's not big of a deal for you but for many people it is.

**Comment by dederomagnolo** [comment] 2020-07-08 03:33
I have the same issue here in Android, textAlign aligns in the center with flex: 1 (in the middle of placeholder string). Should be aligned with the placeholder first char. In iOS it is working fine like this. 0.61 version.

**Comment by fabriziobertoglio1987** [comment] 2020-07-08 08:34
Please test my fix https://github.com/facebook/react-native/pull/28995 
This issue should be closed once https://github.com/facebook/react-native/pull/28995 is merged.

**Comment by ShivamJoker** [comment] 2020-07-08 08:46
@fabriziobertoglio1987 how will we test it ? I am new to this so .. sorry 😅

**Comment by fabriziobertoglio1987** [comment] 2020-07-08 15:34
You either clone my branch 

https://github.com/fabriziobertoglio1987/react-native/tree/fix-text-input-cursor-jump

and test it in the RNTester App
Read the instructions here
https://github.com/facebook/react-native/tree/master/RNTester

Or even better, if you also want to fix this issue in your React Native project. 
Clone my branch of react native 
https://github.com/fabriziobertoglio1987/react-native/tree/fix-text-input-cursor-jump

and install in your project that version of react native as explained in the instructions here
https://github.com/facebook/react-native/wiki/Building-from-source#publish-your-own-version-of-react-native

otherwise wait for the latest release and support me :smiley:

**Comment by ramykl** [comment] 2020-07-15 10:22
Seems to be an issue since 2016 with it being classified as desired behaviour https://github.com/facebook/react-native/issues/10030. Would really like it fixed so it matches with ios and normal web behaviour

**Comment by ShivamJoker** [comment] 2020-08-09 06:59
Thanks @fabriziobertoglio1987 I have tested your changes and it works perfect, hope they merge this soon

**Comment by anagovitsyn** [comment] 2020-10-12 13:16
here is full component code with cursor centered in TextInput. react natiive v0.61

```
import React, {useState, useEffect} from 'react';
import {
  View,
  TouchableOpacity,
  Text,
  Image,
  TextInput
} from 'react-native';

export default function Welcome({navigation}) {
    const [name, setName] = useState('')

    return(
      <>
        <View style={{paddingTop: 64, paddingLeft: 34, paddingRight: 34}}>
            <Text>
            </Text>
            <TextInput
                autoFocus={true}
                style={{
                    marginTop: 24,
                    fontFamily: 'StyreneAWeb-Regular',
                    fontSize: 24,
                    lineHeight: 36,
                    fontWeight: '700',
                    color: '#333',
                    textAlign: 'center'
                }}
                value={name}
                onChangeText={text => setName(text)}
                selectionColor='#333'
            />
              <TouchableOpacity
                style={{
                  marginTop: 27,
                  paddingTop: 11,
                  height: 41,
                  paddingLeft: 32,
                  paddingRight: 32,
                  backgroundColor: '#333333',
                  alignItems: 'center',
                  justifyContent: 'center',
                  paddingBottom: 11
                }}
                onPress={() => { 

                }}
            >
                  <Text
                    style={{
                      color: '#FFF',
                      fontSize: 15,
                      lineHeight: 19,
                      fontFamily: 'StyreneAWeb-Regular',
                      fontWeight: 'normal',
                    }}>
                    Продолжить
                  </Text>
              </TouchableOpacity>
        </View>
        <View
            style={{height: 16, marginLeft: 16, marginRight: 16, backgroundColor: '#F2E6E6'}}
        />
        </>
    )
}
```

**Comment by Joshmatjjen** [comment] 2020-11-12 15:28
Ohh... When will this be fixed  ?

**Comment by Yandamuri** [comment] 2020-12-24 09:32
Any update about fix?

**Comment by Fedorrychkov** [comment] 2021-02-11 10:54
Same in 0.63.2

**Comment by lautaro-osacar** [comment] 2021-03-15 13:17
I had to remove the placeholder when the input is focused to center the cursor, maybe adding a label to the input when is focused could help to improve the UX with this workaround.

**Comment by hugoh59** [comment] 2021-06-28 13:33
Same issue in 0.62.2

**Comment by MerouaneBali** [comment] 2021-06-30 05:40
+1, still a thing for now.

**Comment by colinmatthewlee** [comment] 2021-08-03 02:39
Still an issue in 0.63.4

**Comment by Vivers0** [comment] 2021-08-05 07:14
Still an issue in 0.64.2

**Comment by lcd11001** [comment] 2021-08-11 10:22
My solution is use parent View + TextInput
![RN_center_input_cursor](https://user-images.githubusercontent.com/34227517/129013056-d5b1ea1b-3961-43e4-9f94-07014b4be348.png)

**Closed** 2021-08-12 05:53 UTC
Labels: Component: TextInput, Bug

**Comment by mrshahzeb7** [comment] 2021-08-23 10:25
any solution to this ? I am facing on  "react-native": "0.64.2",

**Comment by efefurkankarakaya** [comment] 2021-08-24 21:20
> any solution to this ? I am facing on "react-native": "0.64.2",

I have same issue too.

`"react-native": "0.64.2",`

**Comment by Alihassan001** [comment] 2021-08-31 21:03
I have managed by this:

`<View style={styles.inputWrapper}>
     <TextInput
          value={value}
          onChangeText={val => setValue(val)}
          placeholder="Input Placeholder"
          style={styles.input}
          />
</View>

// styling
inputWrapper: {
      backgroundColor: colors.grey,
      width: '90%', //depending on your style
      borderRadius: 30,
      marginVertical: 20,
      justifyContent: 'center',
      alignItems: 'center',
    },
    input: {
      paddingHorizontal: 20,
      paddingVertical: 10,
      fontSize: scaleFont(16),
    }
`

**Comment by AliRehman7141** [comment] 2021-11-17 11:09
+1

**Comment by AliRehman7141** [comment] 2021-11-17 11:40
here is my solution
```
<View style={{ alignItems: 'center' }}>
          {testInputText.length == 0 &&
            <Text style={[styles.inputText, {
              color: '#C7C7CD',
              position: 'absolute'
            }]}>
              {'My placeholder'}
            </Text>
          }
          <TextInput
            value={testInputText}
            placeholder={''}
            textAlign={'center'}
            style={styles.inputText}
            onChangeText={setTestInputText}
          />
</View>
```

**styles**
```
inputText: {
    fontSize: 16,
    textAlign: 'center',
  },

**Comment by mohamedanwer123** [comment] 2022-01-17 10:23
this issue still occurs

**Comment by Aashir1** [comment] 2022-01-19 16:55
still happening with me

**Comment by CaptainHaider** [comment] 2022-01-19 17:12
still

**Comment by mrjackwhitaker** [comment] 2022-01-31 17:35
I was getting this issue only on iOS (RN 0.63.4).  For some reason the previous developer had the following:
`
placeholder='email'
placeholderColor='transparent'
`
Removing both those lines (obviously didn't need a placeholder) worked for me.  Might be worth trying it without a placeholder to see if it still bugs out.

**Comment by AhmedAbuelenin** [comment] 2022-02-17 20:30
> I was getting this issue only on iOS (RN 0.63.4). For some reason the previous developer had the following: `placeholder='email' placeholderColor='transparent'` Removing both those lines (obviously didn't need a placeholder) worked for me. Might be worth trying it without a placeholder to see if it still bugs out.

Thanks for the idea @mrjackwhitaker 
After commenting placeholder and placeholderTextColor props, the cursor is aligned to center correctly but the issue is there's no placeholder exist anymore.

This is a workaround if you still need a placeholder with textAlign='center'

```
import {  InteractionManager } from react-native

const inputRef = React.createRef() 

const focusInputWithKeyboard = () => { //  this part is copied from Stackoverflow
    InteractionManager.runAfterInteractions(() => {
      inputRef.current.focus();
    });
  };

<View>
     <TextInput ref={inputRef} value={someValue}  textAlign={'center'}/>
     {!someValue ? 
        <View style={{
                 position: 'absolute',
                  top: 0,
                  bottom: 0,
                  left: 0,
                  right: 0,
                  justifyContent: 'center',
                  alignItems: 'center',
              }}>
             <Text onPress={focusInputWithKeyboard}>{'placeholder'}</Text>
          </View> 
    :  null}
</View>

```

Hope this help someone.

**Comment by ChrisBews** [comment] 2022-02-21 17:00
Right, as someone that just hit this bug, just adding a wrapper that centers a TextInput with a dynamic width wasn't good enough. The caret would still appear at the end of the smaller TextInput when the placeholder was showing, and this approach would also reduce the touchable area (horizontally) that the user can press to focus the TextInput.

I have managed to find a dodgy hackaround that will fix it (or rather make it appear to be fixed).

You do want the wrapper element around your TextInput styled like so:
```
<View
  style={{
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  }}
>
  {{your text input}}
</View>
```
Then for your TextInput, you want to change the width depending on whether there is a value or not, so as to trigger a redraw of the element, and a recalculation of the caret position:
```
<TextInput
  value={inputValue}
  style={{
    flex: 1,
    width: Boolean(inputValue) ? '100%' : '95%',
    textAlign: 'center',
  }}
/>
```
This will result in the behaviour appearing as you'd expect - the caret remains centered regardless of placeholder text, but the TextInput is still nice and wide to allow for touches at the edges.

**Comment by shafqatbarireporteq** [comment] 2022-03-25 20:54
+1

**Comment by shafqatbarireporteq** [comment] 2022-03-25 21:15
this works fine you can also use number of line. For I wanted one line text so I used  
                        numberOfLines={1}
[https://stackoverflow.com/a/67281614/12242668](url)

**Comment by CDBridger** [comment] 2022-05-18 04:37
Is there a reason this issue is closed? on android text align center with a placeholder still puts the cursor at the end

**Comment by RayRead** [comment] 2022-05-25 08:33
Still an issue

**Comment by lennartkloock** [comment] 2022-06-11 11:26
+1 Still an issue  

As mentioned above, a workaround is:
```
multiline={true}
numberOfLines={1}
```
