### ISSUE TITLE
jsc：r174650 has "duplicate entry: javax/annotation/Nullable.class" when react android 0.15.0

### ISSUE THREAD

**Issue by yipengmu** [facebook/react-native#4706] opened 2015-12-10 13:05 UTC
org.webkit.android-jsc.version=r174650

a problem attach to me when i use react native android 0.15.0:

duplicate entry: javax/annotation/Nullable.class

in abjectively case  , another maven GAV also has Nullable which the package is also javax.annotation. 
even  i can exclude an dependence a GAV ,bug i can't exclude all the files in an exist package,opps!
 
seem to https://github.com/johncarl81/parceler/issues/13

can @kmagiera @mkonicek help me and tell me  how to sovle it.

https://github.com/yipengmu/react-native-android-lession/blob/master/pics/jsc-bug.png
![jsc-annotation-bug](https://github.com/yipengmu/react-native-android-lession/blob/master/pics/jsc-bug.png)

**Comment by mkonicek** [comment] 2015-12-13 14:18
Duplicate of https://github.com/facebook/android-jsc/issues/10, let's discuss there as it looks related to the JSC binary.

**Comment by kmagiera** [comment] 2015-12-14 08:10
it's not related to facebook/android-jsc#10, I think @yipengmu mistaken JSC for JSR. Let's instead discuss it here.

@yiminghe So it looks like there is a conflict with `@Nullable` class being provided twice. The question is what kind of additional dependencies you're adding to your project that may cause that conflict.

Worst case you can update your gradle file to exclude dependency on "JSR" in a way illustrated [here](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.dsl.DependencyHandler.html) (search for an example with "exclude" keyword).

I haven't tried it but I think you should replace dependency on react-native in your app's gradle file with something like:

    compile('com.facebook.react:react-native:0.16.+') {
        exclude module: 'jsr305'
    }

**Comment by mkonicek** [comment] 2016-04-10 16:54
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/jscr174650-has-duplicate-entry-javaxannotationnullableclass-when-react-android-0150

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Closed by mkonicek** 2016-04-10 16:54 UTC
Labels: Android, Icebox
