### ISSUE TITLE
Warning: unknown call: "relay:check"

### ISSUE THREAD

**Issue by KalebPortillo** [facebook/react-native#22349] opened 2018-11-19 19:54 UTC
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
React Native Environment Info:
    System:
      OS: macOS 10.14.1
      CPU: x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 36.70 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.2 - /usr/local/bin/node
      Yarn: 1.6.0 - ~/.yarn/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        Build Tools: 23.0.1, 24.0.1, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 27.0.3, 28.0.2, 28.0.3
        API Levels: 21, 22, 23, 24, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.6.1 => 16.6.3
      react-native: ^0.57.5 => 0.57.5
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native: 0.49.2

## Description
When I run the app this warning `unknown call: "relay:check"` is given right on the beginning, in both ios and android emulators

**Comment by leoek** [comment] 2018-11-26 17:57
I am experiencing this issue with react-native-windows as well.

versions in package.json
```
"react-native": "0.57.2",
"react-native-windows": "0.57.0-rc.0",
```

react-native-debugger version:
```
v0.7.21
```

**Comment by gusgard** [comment] 2018-11-26 21:55
Same with `0.57.6`


  React Native Environment Info:
    System:
      OS: macOS 10.14.1
      CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
      Memory: 469.06 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.12.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.npm-packages/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 26, 27, 28
        Build Tools: 26.0.1, 26.0.2, 27.0.3, 28.0.2, 28.0.3
        System Images: android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1
      react-native: 0.57.6 => 0.57.6

**Comment by leoek** [comment] 2018-11-27 10:06
This seems to be related to https://github.com/facebook/react-devtools/issues/1233

**Comment by leoek** [comment] 2018-11-27 11:02
You disable the yellow box for this warning like this:
`YellowBox.ignoreWarnings(['unknown call: "relay:check"']);`

Probably something which has to be fixed in the devtools.

**Comment by vovkasm** [comment] 2018-12-05 21:02
@servocoder 
1. warning `unknown call: "relay:check"` related to this issue (just for linking purposes): https://github.com/jhen0409/react-native-debugger/issues/291

2. Crash can be unrelated to above warning. And should be reported to react-native-debugger repo I think. Also I think nothing can be done without additional info. Did the crash a native or javascript, what is stack trace? Did newly generated application crashes? Also reproducible repo on github can be very helpful (not for me... I don't use react-native-debugger so will not try to fix this, sorry).

**Comment by alloy** [comment] 2019-03-19 16:54
It looks like the issue reported in the OP has been fixed in a release of the standalone React Native Debugger application 
https://github.com/jhen0409/react-native-debugger/issues/291#issuecomment-447794470

**Closed by alloy** 2019-03-19 16:54 UTC
Labels: Resolution: Needs Repro, Type: Bug Report
