### ISSUE TITLE
Execution optimizations have been disabled for task ':app:compressReleaseAssets' to ensure correctness due to the following reasons: Gradle "Implicit dependencies between tasks" 

### ISSUE THREAD

**Issue by manolo-94** [facebook/react-native#36023] opened 2023-01-31 18:30 UTC
### Description

I have a problem installing the Release version of my application.

Before uploading my application to the playstore I wanted to test the debug and release version on my physical and virtual device that I generated with the following commands:

./gradlew assembleDebug

./gradlew assembleRelease

./gradlew bundleRelease

At the time of testing the debug version works correctly on my virtual and physical device using the following command:

npx react-native run-android --variant=debug

The problem starts when I want to test the release on my devices using the following command:

npx react-native run-android --variant=release

The application can be installed on the devices but it cannot be opened. it is worth mentioning that I generated the boundleRelease I uploaded it to the playstore and when I did a closed test, when I installed my app on my device the same thing happened, the Application is installed but cannot be opened.

### Version

0.70.6

### Output of `npx react-native info`

info Fetching system and libraries information...
(node:43486) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
    Memory: 2.30 GB / 11.62 GB
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: Not Found
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
    Watchman: 20221126.133621.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_352 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

npx react-native run-android --variant=release

### Snack, code example, screenshot, or link to a repository

> Configure project :react-native-reanimated
AAR for react-native-reanimated has been found
/home/manolo/Documentos/projects/reactNative/SiaApp/node_modules/react-native-reanimated/android/react-native-reanimated-70-hermes.aar

> Task :app:bundleReleaseJsAndAssets
Execution optimizations have been disabled for task ':app:bundleReleaseJsAndAssets' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/home/manolo/Documentos/projects/reactNative/SiaApp'. Reason: Task ':app:bundleReleaseJsAndAssets' uses this output of task ':react-native-async-storage_async-storage:packageReleaseRenderscript' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/home/manolo/Documentos/projects/reactNative/SiaApp'. Reason: Task ':app:bundleReleaseJsAndAssets' uses this output of task ':react-native-file-viewer:packageReleaseRenderscript' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/home/manolo/Documentos/projects/reactNative/SiaApp'. Reason: Task ':app:bundleReleaseJsAndAssets' uses this output of task ':react-native-gesture-handler:packageReleaseRenderscript' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/home/manolo/Documentos/projects/reactNative/SiaApp'. Reason: Task ':app:bundleReleaseJsAndAssets' uses this output of task ':react-native-html-to-pdf:packageReleaseRenderscript' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/home/manolo/Documentos/projects/reactNative/SiaApp'. Reason: Task ':app:bundleReleaseJsAndAssets' uses this output of task ':react-native-image-colors:packageReleaseRenderscript' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/home/manolo/Documentos/projects/reactNative/SiaApp'. Reason: Task ':app:bundleReleaseJsAndAssets' uses this output of task ':react-native-masked-view_masked-view:packageReleaseRenderscript' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/home/manolo/Documentos/projects/reactNative/SiaApp'. Reason: Task ':app:bundleReleaseJsAndAssets' uses this output of task ':react-native-orientation-locker:packageReleaseRenderscript' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.

  > Task :app:compressReleaseAssets
  Execution optimizations have been disabled for task ':app:compressReleaseAssets' to ensure correctness due to the following reasons:
    - Gradle detected a problem with the following location: '/home/manolo/Documentos/projects/reactNative/SiaApp/android/app/build/intermediates/assets/release/mergeReleaseAssets'. Reason: Task ':app:compressReleaseAssets' uses this output of task ':app:copyReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.

**Comment by iBotPeaches** [comment] 2023-01-31 23:40
@manolo-94 - I doubt at the moment that those warnings during Gradlew compilation are related, since they all point at different 3rd party packages. 

What you want to do is capture the logcat/error during the failed to launch binary. You mention:

> The application can be installed on the devices but it cannot be opened. 

There are plenty of details hiding in `adb logcat` during this attempt to open the application. You might see some crash about something that will point you to the root cause.

Also note that as you upgrade `--variant` is deprecated. You'll want to practice using `--mode` instead as you jump to RN71.

https://github.com/react-native-community/cli/blob/main/docs/commands.md#--variant-string

**Comment by cortinico** [comment] 2023-02-01 11:59
This is a warning + a duplicate of #33202
See my comment on https://github.com/facebook/react-native/issues/33202#issuecomment-1411938054
(i.e. it's fixed on 0.71)

**Closed by cortinico** 2023-02-01 11:59 UTC
Labels: Platform: Linux, Needs: Triage :mag:

**Comment by manolo-94** [comment] 2023-02-02 16:59
Fixed!!

Thanks for the help, updating to version 0.71.1 solved the problem.

**Comment by toninhorjbr** [comment] 2023-10-05 23:06
> After updation of RN 0.71 to 0.72
> 
> What went wrong: A problem was found with the configuration of task ':app:lintVitalAnalyzeRelease' (type 'AndroidLintAnalysisTask').
> 
> * Gradle detected a problem with the following location: 'C:\React-Projects\English-Muni\android\app\build\intermediates\ReactNativeVectorIcons'.
> 
> Task ':app:lintVitalAnalyzeRelease' uses this output of task ':app:copyReactNativeVectorIconFonts' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
> 
> ```
> Possible solutions:
>   1. Declare task ':app:copyReactNativeVectorIconFonts' as an input of ':app:lintVitalAnalyzeRelease'.
>   2. Declare an explicit dependency on ':app:copyReactNativeVectorIconFonts' from ':app:lintVitalAnalyzeRelease' using Task#dependsOn.
>   3. Declare an explicit dependency on ':app:copyReactNativeVectorIconFonts' from ':app:lintVitalAnalyzeRelease' using Task#mustRunAfter.
> 
> Please refer to https://docs.gradle.org/8.0.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
> ```
I'm still getting this error in 0.71.4 , @aksingour did you manage to solve.

**Comment by akhilsanker** [comment] 2023-12-22 06:45
> After updation of RN 0.71 to 0.72
> 
> What went wrong: A problem was found with the configuration of task ':app:lintVitalAnalyzeRelease' (type 'AndroidLintAnalysisTask').
> 
> * Gradle detected a problem with the following location: 'C:\React-Projects\English-Muni\android\app\build\intermediates\ReactNativeVectorIcons'.
> 
> Task ':app:lintVitalAnalyzeRelease' uses this output of task ':app:copyReactNativeVectorIconFonts' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
> 
> ```
> Possible solutions:
>   1. Declare task ':app:copyReactNativeVectorIconFonts' as an input of ':app:lintVitalAnalyzeRelease'.
>   2. Declare an explicit dependency on ':app:copyReactNativeVectorIconFonts' from ':app:lintVitalAnalyzeRelease' using Task#dependsOn.
>   3. Declare an explicit dependency on ':app:copyReactNativeVectorIconFonts' from ':app:lintVitalAnalyzeRelease' using Task#mustRunAfter.
> 
> Please refer to https://docs.gradle.org/8.0.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
> ```

I'm facing the same issue. @toninhorjbr @aksingour , have you got any workaround?

Thanks

**Comment by usmanabid94** [comment] 2024-01-24 12:15
any solution for this i am also facing the same issue

**Comment by AkramSyed002** [comment] 2024-04-17 15:06
It still exist in React native version
0.73.6

**Comment by vijay14887** [comment] 2025-09-17 13:28
I am also facing this issue. Could you please give me a work around please. After Updating from Android API Level 34 to 35 , this issue is coming up. Can anyone help with a solution please?

**Comment by QuocHuy-hash** [comment] 2025-10-21 02:56
> I am also facing this issue. Could you please give me a work around please. After Updating from Android API Level 34 to 35 , this issue is coming up. Can anyone help with a solution please?

i have same issue🥲
