### ISSUE TITLE
[iOS only]multi-line comment works well,and single line comment does not .

### ISSUE THREAD

**Issue by lavystord** [facebook/react-native#6877] opened 2016-04-08 11:01 UTC
When my code is
`import {masterData} from './masterData';`
`// import {mobileModification} from './mobileModification'`
`import {isFetching} from './isFetching';`
The iOS app crashed and showed this: 
![_20160408171757](https://cloud.githubusercontent.com/assets/16117095/14381763/650875d6-fdbb-11e5-841b-332fb4dee113.png)

It seems like the comment doesn't work,the import command still be explained.
But when I use multi-line comment instead,it works well.

`import {masterData} from './masterData';`
`/* import {mobileModification} from './mobileModification'*/`
`import {isFetching} from './isFetching';`

What's more ,I can use single line comment on Android.
Finally,my react native version is 0.2.0

**Comment by magrinj** [comment] 2016-04-13 16:19
@lavystord: I can't reproduce your problem, when you say your version of react-native is `0.2.0` did you mean `0.20.0` ?

**Comment by magrinj** [comment] 2016-04-13 16:23
@facebook-github-bot label ios

**Comment by lavystord** [comment] 2016-04-13 16:44
@magrinj yeah,it's 0.20.0,maybe because my machine is windows? But my colleague who uses mac encounter the same problem with the same code repository.

**Comment by magrinj** [comment] 2016-04-13 16:52
Yes that's sound really strange, I'm on `0.22` and I don't have this problem, maybe try updating your project.
I don't think that gonna change anything, but try to put a `;` at the end of your comment...

**Comment by lavystord** [comment] 2016-04-13 17:08
@magrinj thanks.It really sounds strange.I put a semi-colon at the end of my comment,but it still doesn't work.
This problem is really to reproduce to the people who don't have the same code.But I trigger this problem 100% on iOS . Then the same code android works well,so I guess it has nothing to do with my code.It maybe the bugs of react native.So I create a  issue here,hope someone has some ideas about possible reason to incur this problem.
Maybe until I upgrade the react native,this problem will be missing.

**Comment by magrinj** [comment] 2016-04-13 17:15
@lavystord I've no more ideas at the moment...
You're right, but I can't reproduce it on `0.22`, so if this problem existed before, I think it's solved now :)

**Comment by lavystord** [comment] 2016-04-17 07:49
@magrinj  I fixed this by upgrading the RN version to 0.23.1.

**Comment by magrinj** [comment] 2016-04-19 13:08
@lavystord Ok perfect :)

**Comment by geirman** [comment] 2016-04-30 01:12
@facebook-github-bot answered

**Comment by facebook-github-bot-0** [comment] 2016-04-30 01:13
Closing this issue as @geirman says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

**Closed by facebook-github-bot-0** 2016-04-30 01:13 UTC
Labels: Packager, Ran Commands
