### ISSUE TITLE
Transform translateY in MaterialTopTabNavigator with ScrollView flickers

### ISSUE THREAD

**Issue by emmx** [facebook/react-native#23290] opened 2019-02-05 04:51 UTC
## Environment

  React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
      CPU: (4) x64 Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz
      Memory: 566.20 MB / 15.36 GB
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
      Yarn: 1.12.1 - /usr/bin/yarn
      npm: 6.5.0 - ~/.nvm/versions/node/v10.13.0/bin/npm
    SDKs:
      Android SDK:
        API Levels: 23, 26, 27, 28
        Build Tools: 27.0.3, 28.0.2, 28.0.3
        System Images: android-27 | Intel x86 Atom, android-27 | Intel x86 Atom_64
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58 => 0.58.3

## Description

Issue related to #15445, which was reported 2 years ago but was never actually fixed.

When you apply a `translateY` transformation to a MaterialTopTabNavigator which has a ScrollView as a child the navigator flickers while you drag it. The main purpose is to achieve a collapsible header effect.

As a side note, there's a potential patch but I couldn't test it (https://github.com/facebook/react-native/issues/15445#issuecomment-321721259). After editing `ReactScrollView.java` and running `react-native run-android` somehow react-native is not recompiled, even if I remove `android/app/build`, I see the same behavior.

## Reproducible Demo

Any lib for collapsible header presents the same problem (for instance, example 3 and 4 in `react-navigation-collapsible`).

**Comment by benevbright** [comment] 2019-02-05 22:35
This issue still exists on the latest react-native. 
https://github.com/facebook/react-native/issues/21801

**Comment by kelset** [comment] 2019-02-05 22:49
Closing as duplicate of #21801

**Closed by kelset** 2019-02-05 22:49 UTC
Labels: Bug Report, Component: ScrollView, Platform: Linux, Resolution: Old Version, Type: Bug Report
