### ISSUE TITLE
Error installing boost Verification checksum was incorrect.

### ISSUE THREAD

**Issue by MonikhaRaj21** [facebook/react-native#42195] opened 2024-01-09 07:09 UTC
### Description

Error installing boost Verification checksum was incorrect.

### Steps to reproduce

1. Run in Azure Pipeline. 
2. I am facing while running install cocopods 

### React Native Version

0.71.0

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M2
    Memory: 101.80 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10811636
    Xcode: 15.1/15C65 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.11 => 0.71.11 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Stacktrace or Logs

```text
[!] Error installing boost
Verification checksum was incorrect, expected f0397ba6e982c4450f27bf32a2a83292aba035b827a5623a14636ea583318c41, got 5e89103d9b70bba5c91a794126b169cb67654be2051f90cf7c22ba6893ede0ff
##[error]The process '/usr/local/lib/ruby/gems/2.7.0/bin/pod' failed with exit code 1
##[error]The 'pod' command failed with error: The process '/usr/local/lib/ruby/gems/2.7.0/bin/pod' failed with exit code 1
Finishing: Install Cocoapod Dependencies
```

### Reproducer

https://github.com/MonikhaRaj21

**Comment by tarunrajput** [comment] 2024-01-09 08:21
@MonikhaRaj21, Please follow this pinned issue https://github.com/facebook/react-native/issues/42180 for updates and workarounds.

**Comment by cortinico** [comment] 2024-01-09 09:49
Closing as duplicate of https://github.com/facebook/react-native/issues/42180

**Closed by cortinico** 2024-01-09 09:49 UTC
Labels: Needs: Triage :mag:, Needs: Author Feedback, Needs: Repro, Newer Patch Available
