### ISSUE TITLE
Error during running code

### ISSUE THREAD

**Issue by amitanand2406** [facebook/react-native#20316] opened 2018-07-20 10:49 UTC
![screenshot_20180720-161044](https://user-images.githubusercontent.com/41473523/42998668-90973eea-8c38-11e8-8cf4-673afe4d327a.png)

Whenever I try to run code, this ever come again and again.

**Comment by kelset** [comment] 2018-07-20 10:53
Duplicate of https://github.com/facebook/react-native/issues/19953

**Closed by kelset** 2018-07-20 10:53 UTC
