### ISSUE TITLE
You attempted to set the key 'time' with the value '2017-05-31' on an object that is meant to be immutable and has been frozen.

### ISSUE THREAD

**Issue by Symous** [facebook/react-native#14284] opened 2017-06-01 08:52 UTC
Please I have raised an issuse before #14266 , but someone just closed it without solve this.they said the reason is that I try to changing prop value. But the fact is that even state value will also encounter this error.

now please see my code : 
```js
this.state{
     markerList : this.props.positionList,
}

render(){
     return( 
        <CustomMapView markers = { this.state.markerList}/>
     )
}

aMethodWillThisIssuse(){
    var list = this.state.markerList;
    list[0].time = '2017-05-31';
    // **error occured here!!!**
}
```
What I can confirm is that my componentMapView is ok. and once I assign markerList to my customMapView component , the error will occured! 

Please don't close this until we solve this, thanks.

PS: Android Platform + React Native 0.43.

**Comment by aaronofleonard** [comment] 2017-06-01 21:18
They were right to close it. This is not related to React Native, and barely even to React itself. React is just nice enough to give you that informative message.

You say that even a state value will cause you to encounter the error. State is meant to be changed with `setState`, not by direct mutation. More than that, just because your `state` object "steals" the object from `this.props` does not mean that it becomes changeable. You need to be *copying* the object, because it is still referencing a frozen object.

There's no point in getting into greater detail, you should post on stackoverflow, and many would be happy to give you a more detailed explanation on why this is not working, and how to fix it. But make no mistake, this is not an issue with the react-native project, and will be closed. Please post on stackoverflow, it's easy and free.

**Comment by Symous** [comment] 2017-06-02 00:33
@aaronofleonard Thanks for your feedback! I understand what you said. but what confuse me a lot is that I have assign the state value to a totally new variable.
```js
var list = this.state.markerList;
```
it would be no related to the state value, but I still encounter this error when I try to change its value, that's the key point.

**Comment by hramos** [comment] 2017-08-16 03:09
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Closed by hramos** 2017-08-16 03:09 UTC
Labels: Icebox
