### ISSUE TITLE
Unhandled error Network error

### ISSUE THREAD

**Issue by haris-ramzan** [facebook/react-native#14970] opened 2017-07-12 09:54 UTC
### Is this a bug?

Unhandled error Network error: Network request failed Error: Network error: Network request failed
at new ApolloError ()
 

### Environment

1. `react-native`:0.44.0
2. `react-apollo`:1.1.1
3. `apollo-client`:1.0.4

### Steps to Reproduce

1. When turn off internet connection.
2. When turn off internet during app navigation.

### Expected Behavior

Component should render without data and errors received through props. The same when its a query error or some kind of http error.
### Actual Behavior
The Red screen occur on failure of internet connection with this error  "Unhandled error Network error: Network request failed Error: Network error: Network request failed
at new ApolloError ()"

**Comment by hramos** [comment] 2017-07-12 15:04
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-07-12 15:04 UTC

**Comment by haris-ramzan** [comment] 2017-07-20 07:39
@hramos actually i found this error on internet failure during screen navigation with react-native-router-flux.
Here is my Client;  
`import ApolloClient, { createNetworkInterface } from 'apollo-client';
import { AsyncStorage } from 'react-native';
import { SubscriptionClient } from 'subscriptions-transport-ws';
import addGraphQLSubscriptions from '../dev/subscriptions';

const wsClient = new SubscriptionClient('ws://192.168.0.0', {
  reconnect: true,
  connectionParams: {
    accessToken: 'jkasdhkjashd jkashdjk ashdas'
  }
});

const networkInterface = createNetworkInterface({

  uri: 'http://192.168.0.0/graphql',
  opts: {
    credentials: 'same-origin'
  }
});
const logErrors = {
  applyAfterware({ response }, next) {
    if (!response.ok) {
      response.clone().text().then(bodyText => {
        console.error(`Network Error: ${response.status} (${response.statusText}) - ${bodyText}`);
        next();
      });
    } else {
      response.clone().json().then(({ errors }) => {
        if (errors) {
           console.error('GraphQL Errors:', errors.map(e => e.message));
        }
        next();
      });
    }
  },
};
networkInterface.useAfter([logErrors]);
const networkInterfaceWithSubscriptions = addGraphQLSubscriptions(
  networkInterface,
  wsClient
);
const client = new ApolloClient({
  dataIdFromObject: o => o.id,
  networkInterface: networkInterfaceWithSubscriptions

});
networkInterface.use([{
  applyMiddleware(req, next) {
    if (!req.options.headers) {
      req.options.headers = {};  // Create the header object if needed.
    }
    // get the authentication token from local storage if it exists
    AsyncStorage.getItem('sessionToken').then((token) => {
      req.options.headers.Authorization = token ? `${token}` : null;
      next();
    }
    );
  }
}]);
export default client;
`
I found this Error "Unhandled error Network error: Network request failed Error: Network error: Network request failed
    at new ApolloError"

**Comment by haris-ramzan** [comment] 2017-07-20 07:46
![screenshot_1499843569](https://user-images.githubusercontent.com/25927759/28406309-690f2d6a-6d49-11e7-8b40-3de24d610db1.png)

**Comment by HPieters** [comment] 2018-01-23 13:39
@haris-ramzan Did you ever resolve this issue?

**Comment by ICCanche** [comment] 2018-01-25 23:20
Same here.

"react-apollo": "2.0.4",
 "react-native": "0.52.0",
