### ISSUE TITLE
React native runs faster when Remote debugging 

### ISSUE THREAD

**Issue by fab1an** [facebook/react-native#8327] opened 2016-06-22 19:57 UTC
When I enable remote-debugging my animations run faster and my app is overall much more responsive than when I have it disabled.

Version: `0.28`
OS: Android

**Comment by vonovak** [comment] 2016-06-22 22:21
This is not a bug, but something to be expected in some cases, since when running in debug mode, the js is executed in chrome, not in the device. Try disabling the dev mode and reloading.

**Comment by fab1an** [comment] 2016-06-23 05:54
I figured something like that.

How I disable the debug mode and still have it load from the packager or do I have to bundle everything and make a production build?

**Comment by DanielMSchmidt** [comment] 2016-06-23 06:28
You can disable the remote debugging option and the code should run on the device.

**Comment by DanielMSchmidt** [comment] 2016-06-23 06:28
@facebook-github-bot expected

**Comment by facebook-github-bot-9** [comment] 2016-06-23 06:29
The comment above tells me this is expected behavior. Closing this as we'd like to use the GitHub issue tracker for bugs. If you'd like to change how this feature works please post a feature request on [Product Pains](https://productpains.com/product/react-native/) so that other people can vote on it.

**Closed by facebook-github-bot-9** 2016-06-23 06:29 UTC
Labels: Ran Commands

**Comment by fab1an** [comment] 2016-06-23 06:32
Sorry, I meant how to I disbable *dev mode*.

**Comment by ide** [comment] 2016-06-23 07:26
Set ?dev=false in the bundle URL to disable `__DEV__`.

**Comment by fab1an** [comment] 2016-06-23 08:48
How?

I tried 
```java
 mReactInstanceManager = ReactInstanceManager.builder()
            .setApplication(application)
            .setBundleAssetName("index.android.bundle?dev=false")
            .setJSMainModuleName("js/index.android?dev=false")
            .addPackage(MainReactPackage())
            .addPackage(MyReactPackage())
            .setUseDeveloperSupport(BuildConfig.DEBUG)
            .setInitialLifecycleState(LifecycleState.RESUMED)
            .build()
```
