### ISSUE TITLE
WebView stopLoading no longer working in onNavigationStateChange on Android

### ISSUE THREAD

**Issue by riteshmahajan47** [facebook/react-native#18407] opened 2018-03-16 08:07 UTC
WebView stopLoading method not working for Android.

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 6.11.2
  Yarn: 0.15.1
  npm: 3.10.10
  Watchman: 4.9.0
  Xcode: Xcode 8.2 Build version 8C38
  Android Studio: 2.2 AI-145.3537739

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.3 => 0.53.3

### Expected Behavior

Newly clicked url stops loading
 
### Actual Behavior

Url keeps loading & throw error with message 'can not read property 'stopLoading' of undefiend'

### Steps to Reproduce

Create a Webview in 0.53.3
Call stopLoading in onNavigationStateChange

**Comment by riteshmahajan47** [comment] 2018-03-16 09:17
Still same issue with version 0.54.0.  I guess stopLoading method removed after 0.29.0 version. 

Now how can I stops Newly clicked url loading ?

**Comment by hramos** [comment] 2018-03-16 16:48
Here's a reproducible demo from a prior related issue (https://github.com/facebook/react-native/issues/15679):

```
export var TestWebContentView = createReactClass( {displayName: 'TestWebContentView',
    handleNavigationChange: function(navState) {
         console.log(navState)
         this.webview.stopLoading();
        }
    },
    render: function() {
        return (
            <View style={rootViewStyle} >
                <WebView
                ref={(ref) => { this.webview = ref; }}
                scrollEnabled={false}
                source={{uri: 'http://www.simplehtmlguide.com/livedemo.php?e=youtube2' }}
                startInLoadingState={false}
                mixedContentMode={'always'}
                scalesPageToFit={false}
                onNavigationStateChange={this.handleNavigationChange}
                allowsInlineMediaPlayback={true}
                automaticallyAdjustContentInsets={false}
                />
            </View>
        )
    }
})
```

**Comment by hramos** [comment] 2018-03-16 16:50
Thanks for looking into it and confirming it's still an issue in 0.54.

I'll merge this into the other bug report which I've reopened.

Duplicate of #15679

**Closed by hramos** 2018-03-16 16:50 UTC
Labels: Android, Ran Commands, WebView
