### ISSUE TITLE
[ListView] Scroll on ListView end with an error saying "Ended a touch event which was not counted in trackedTouchCount"

### ISSUE THREAD

**Issue by chirag04** [facebook/react-native#1139] opened 2015-05-04 17:09 UTC
@vjeux

**Comment by Duan112358** [comment] 2015-05-06 06:36
same problem happened to me

**Comment by chirag04** [comment] 2015-05-06 16:13
@vjeux  Seems like a consistent bug.

**Comment by lukasreichart** [comment] 2015-05-06 16:32
@chirag04 @Duan112358 could you give us more details?

**Comment by Duan112358** [comment] 2015-05-07 00:36
**`test example of react-native/Examples/Movies`**

![screen shot 2015-05-07 at 08 06 27](https://cloud.githubusercontent.com/assets/1957818/7506345/38691000-f491-11e4-8b6d-b4f1f46cfabb.png)

the bug is sometimes unexpectable that I could't figure it out.

the stack log is below

![screen shot 2015-05-07 at 08 07 52](https://cloud.githubusercontent.com/assets/1957818/7506364/7e47d08e-f491-11e4-880a-1510d47dd634.png)

**when test on a real device, the touch event doesn't respond on some list item after scrolling down to load more.**

 It is easy to reproduce
*  scroll down to load more and scroll back
*  random touch some list item

**If some doesn't respond, then after a few seconds, the bug is appeared again.**

**Comment by ssssssssssss** [comment] 2015-05-08 06:12
It's quite easy to reproduce while scrolling around in UIExplorer app.

**Comment by lukasreichart** [comment] 2015-05-13 13:39
The error message is correct: it seems that the ```trackedTouchCount```  isn't incremented, when the touch starts, but when the touch ends the ```ResponderEventPlugin``` tries to decrement, it which results in ```trackedTouchCount``` beeing -1. 
Just an theory: Maybe this error occurs because gestures are handled differently on the ```ListView``` and the ```ListView's``` elements:
ListView uses ScrollView which is a separate native class and uses a ```UIScrollView```. The ListView's 
elements on the other hand use the JS Gesture Responder System. 
Imagine the situation: The touch is first handled by the ```UIScrollView``` but as the touch changes it's also tracked by the JS Responder System. In this case the touch would never have been started (from the JS perspective) and therefore ```trackedTouchCount```, wasn't incremented.

But maybe someone who understands more of the react-native gesture responder system could take a look? @vjeux @nicklockwood @ide ??

**Comment by jtremback** [comment] 2015-05-19 18:09
I'm getting this sometimes when returning from a webpage using LinkingIOS.

**Comment by lukasreichart** [comment] 2015-05-20 08:08
@jtremback any leads on how to fix this?

**Comment by pewallin** [comment] 2015-05-21 13:01
I'm getting this as well.

**Comment by meric426** [comment] 2015-05-21 13:06
I've gotten this playing around on a iphone 5, never in the simulator.

**Comment by lukasreichart** [comment] 2015-05-21 13:11
@meric426 The bug also occurs in the simulator, but is more difficult to reproduce ... :/

**Comment by jtremback** [comment] 2015-05-21 17:09
What libraries are people using? I'm using `react-native-camera`, which has been a bit sketchy in general, so I wonder if it is related.

**Comment by paramaggarwal** [comment] 2015-05-28 15:46
I'm getting this as well.

**Comment by brentvatne** [comment] 2015-05-28 16:57
It would be fantastic if someone could reproduce this in a simulator on [rnplay.org](https://rnplay.org)

**Comment by brentvatne** [comment] 2015-05-30 21:20
@jtremback - it might be useful to set `var DEBUG_SPY_MODE = true;` in `Libraries/Utilities/MessageQueue.js` - but you will get a lot of noise from timers, so we'd probably want to filter that out.

**Comment by paramaggarwal** [comment] 2015-06-23 16:45
[This](https://github.com/facebook/react-native/blob/8b93b99d4a769f86fffc95d65434f2f6a3fd827d/Libraries/vendor/react/browser/eventPlugins/ResponderEventPlugin.js#L506) is the `invariant` violation being fired.

**Comment by lukasreichart** [comment] 2015-06-29 19:05
This bug seems to be fixed in react-native 0.6. Maybe I'll try to identify what fixed it, but for now I'am glad that my ScrolViews / ListViews are working again :+1:

**Comment by paramaggarwal** [comment] 2015-06-30 02:33
@lukasreichart  Yes, I didn't come across it since upgrading - you might be right!

**Comment by ide** [comment] 2015-06-30 02:53
Closing this issue since it sounds like it's been fixed. Please holler if it's still an issue.

**Closed by ide** 2015-06-30 02:53 UTC

**Comment by jtremback** [comment] 2015-06-30 02:57
:+1: great job!

**Comment by dgilperez** [comment] 2015-12-26 13:21
I got hit by this error with 0.17. I'm using a ListView with List component instances from react-native-material-design plugin, if it's useful to know.

**Comment by kapv89** [comment] 2016-01-17 21:58
I have hit the same error with 0.17. not using material design, just plain react native lib

**Comment by mephisto83** [comment] 2016-01-20 08:39
I have hit the same error with 0.17. not using material design, just plain react native lib

**Comment by conover** [comment] 2016-08-03 17:01
Experiencing this error intermittently on .30

**Comment by shawnXiao** [comment] 2016-08-29 09:54
I have hit the same error with 0.28. not using material design. we use the plugin react-native-image-zoom

**Comment by anilchembath** [comment] 2016-09-25 06:47
Facing this issue in 0.30. The issue is happening intermittently. Any solutions for this.

**Comment by sujitpk-perennial** [comment] 2018-02-21 07:21
Found this issue for specific device only. MI phones having 3 fingure guestures enabled. So while swiping with 3 fingure found this issue.

**Comment by carstenhag** [comment] 2018-06-26 11:20
Having the same issue as @sujitpk-perennial.

On a One Plus 5, there's a 3-finger-gesture to create a screenshot. 

![screenshot_20180626-131807](https://user-images.githubusercontent.com/3776997/41908266-a853646c-7943-11e8-9790-7efad068b184.jpg)

**Comment by daimashenjing** [comment] 2018-06-27 05:48
我也遇到了 当超过2根手指在手机上不停滑动 就会出现这个错误 我在做一个双指缩放图片的功能......

**Comment by daimashenjing** [comment] 2018-06-27 05:49
"react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-cli": "^2.0.1"
