### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by atallah-salah** [facebook/react-native#24107] opened 2019-03-22 22:38 UTC
## 🐛 Bug Report
I have work on react native before and it was work fine 
after some working on python and install some packages 
I start got this error when trying to initialize new project using this command : `react-native init`

![Captureerror](https://user-images.githubusercontent.com/30745904/54856212-01fad580-4d02-11e9-9897-ddc73bb5a7c9.PNG)

I have update react native to latest version and try to reinstall it again but still same error

react-native-cli: 2.0.1
react-native: 0.59.1
node v11.12.0
npm 6.7.0

**Comment by zsubzwary** [comment] 2019-03-23 03:23
I am having the exact same issue !!

**Comment by temchannat** [comment] 2019-03-23 04:50
I also have this problem. React Native seem to be problems when they update new version. Since Flutter comes in so fast now, I think RN might be disappear soon. New developers  are introduced to Flutter and currently RN developers also moving to flutter...

**Comment by zsubzwary** [comment] 2019-03-23 04:53
@temchannat I fixed by following commands:
`react-native init awesomeApplication --version "0.58.6"`

Hope this helps !! 
# 😇

**Comment by temchannat** [comment] 2019-03-23 04:58
@zsubzwary yes for version less than 59 is fine, but when you don't specify the version, it run into the problem hahaha....

**Comment by zuby64** [comment] 2019-03-23 05:18
@temchannat even specifying the version...it is not working for me

**Comment by FIyxian** [comment] 2019-03-23 05:29
me too……

**Comment by duncannah** [comment] 2019-03-23 07:52
Also have this problem using Yarn on macOS.

**Comment by AGPatel** [comment] 2019-03-23 11:08
After version error I have issue!!
```
**PS C:\react\Task>** react-native run-android
info Starting JS server...
info Building and installing the app on the device (cd android && gradlew.bat app:installDebug)...

ERROR: JAVA_HOME is set to an invalid directory: C:\path\to\JavaSDK

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: gradlew.bat app:installDebug
```

**Comment by thymikee** [comment] 2019-03-23 15:37
Duplicate of https://github.com/facebook/react-native/issues/2410. Should be already fixed

**Closed by thymikee** 2019-03-23 15:37 UTC
Labels: Ran Commands, Resolution: Needs More Information, Type: Bug Report

**Comment by sai905905** [comment] 2019-11-13 09:25
i had same issue **"Could not debug. The "path" argument must be of type string. Received type undefined"**

resolved by removing             
"outDir": "${workspaceRoot}/.vscode/.react"
and added
            "cwd": "${workspaceRoot}"
in launch.json

code sample:

{
            "name": "Debug Android",
            "program": "${workspaceRoot}/.vscode/launchReactNative.js",
            "type": "reactnative",
            "request": "launch",
            "platform": "android",
            "sourceMaps": true,
            "cwd": "${workspaceRoot}"
        },
        {
            "name": "Debug iOS",
            "program": "${workspaceRoot}/.vscode/launchReactNative.js",
            "type": "reactnative",
            "request": "launch",
            "platform": "ios",
            "sourceMaps": true,
            "cwd": "${workspaceRoot}"
        },
