### ISSUE TITLE
"Facebook Github Bot"

### ISSUE THREAD

**Issue by friederbluemle** [facebook/react-native#27109] opened 2019-11-04 18:53 UTC
To anyone with the ability to update the Git configuration of the `facebook-github-bot` user:

Right now, commits on `master` have the following committer ID:

```
Facebook Github Bot <facebook-github-bot@users.noreply.github.com>
```

Please **fix the GitHub spelling** and change it to:

```
Facebook GitHub Bot <facebook-github-bot@users.noreply.github.com>
```

Or - even better - since the committer email suggests this is the GitHub user [facebook-github-bot](https://github.com/facebook-github-bot), it would be best to **synchronize** the two names (i.e. what's shown on GitHub's website and what's used in the committer information):

```
Facebook Community Bot <facebook-github-bot@users.noreply.github.com>
```

**Comment by friederbluemle** [comment] 2020-02-05 00:36
@probot - Please don't close. This is still *not* resolved as of Feb 2 2020 

I understand it might not be a high priority for most people, but on the other hand, it would only take a couple of minutes to fix for someone with access permissions.

**Comment by jsjoeio** [comment] 2020-03-11 00:02
Hey @friederbluemle - thank you for bringing this up! I believe I found the root cause and have submitted a fix for the typo in "Github". Once that lands, I will follow up and confirm whether it is indeed fixed. Then we close this issue :)

**Comment by friederbluemle** [comment] 2020-03-11 00:05
Awesome thanks @jsjoeio :+1:

**Comment by jsjoeio** [comment] 2020-03-12 00:44
Looking at the most recent commit on master, it look like it worked! 
![image](https://user-images.githubusercontent.com/3806031/76476602-c4360780-63bf-11ea-8cf2-99f13ae9308b.png)

I'm going to close this now. Thanks again for pointing this out! We appreciate it :)

**Closed by jsjoeio** 2020-03-12 00:44 UTC
Labels: RN Team, Type: Docs
