### ISSUE TITLE
Animated.event fail to map two args

### ISSUE THREAD

**Issue by MQZhangThu** [facebook/react-native#13294] opened 2017-04-04 14:33 UTC
In 0.42.0 version, when using ``Animated.event`` in ``Animated.ScrollView`` to respectively map ``e.nativeEvent.contentOffset.y`` and  ``e.nativeEvent.contentSize.height`` to two Animated value (``this.state.scrollY`` and ``this.state.contentSizeHeight``)  as below, only the first one (i.e., ``this.state.scrollY``) was mapped, while the second one (i.e., ``this.state.contentSizeHeight``)  does not work.
```
onScroll={Animated.event(
              [{
                nativeEvent: { contentOffset: { y: this.state.scrollY } }
              },{
                nativeEvent: { contentSize: { height: this.state.contentSizeHeight } }
              }],
              { useNativeDriver: true },
            )}
```

Below is the test code:
```
componentDidMount() {
      this.state.scrollY.addListener(e => {
        console.log('scrollY', e);  // OK
      })
      this.state.contentSizeHeight.addListener(e => {
        console.log('contentSizeHeight', e); // <--- this line does not run
      })
}
```

**Comment by hramos** [comment] 2017-04-04 21:35
Can you provide a minimal amount of code to reproduce this using [Snack](http://snack.expo.io)?

**Comment by MQZhangThu** [comment] 2017-04-05 11:55
@hramos here is the [Snack link](https://snack.expo.io/r1CpFUzTe)
from the console log, you will see that only something like  ``scrollY {"value":2060}``  is printed, while ``contentSizeHeight`` is not.

**Comment by willdawsonme** [comment] 2017-04-07 01:21
I'm pretty sure this was fixed with https://github.com/facebook/react-native/pull/12697 and should be in `0.44.0-rc.4`.

**Comment by hramos** [comment] 2017-04-07 17:19
Thanks @willdawsonme. We should probably update our issue guidelines to ask that bugs be tested against master.

**Comment by hramos** [comment] 2017-07-25 22:44
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Closed by hramos** 2017-07-25 22:44 UTC
Labels: Author Provided Repro, Icebox
