### ISSUE TITLE
Extend TouchableHighlight: `touchableHandlePress` is not invoked

### ISSUE THREAD

**Issue by khaled-cliqz** [facebook/react-native#14303] opened 2017-06-02 14:35 UTC
I'm trying to create a `Link` Component that extends from `TouchableHighlight` as follows:
```
export default class extends TouchableHighlight {
  _hasPressHandler() {
    return typeof this.props.to === 'string';
  }

  touchableHandlePress(...args) {
    super.touchableHandlePress(...args);
    // do stuff
  }
}
```
The function  [touchableHandlePress](https://github.com/facebook/react-native/blob/master/Libraries/Components/Touchable/TouchableHighlight.js#L192) normally gets invoked when any `Touchable` is pressed, but that doesn't happen with my `Link` class, a press on the component directly invokes the parent `touchableHandlePress` not the overridden function that I've created.

is there something wrong with the implementation?

**Comment by hramos** [comment] 2017-06-02 17:07
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-02 17:07 UTC
