### ISSUE TITLE
libs downloading is duplicated like boost lib

### ISSUE THREAD

**Issue by ntcong91** [facebook/react-native#34504] opened 2022-08-26 05:44 UTC
### Description

I run 
```
yarn android
```
And the boost library downloaded too many times with many boost lib.
This is really annoy when I entered in the low network.
Please fix this - thanks

### Version

0.69.5

### Output of `npx react-native info`

```
info Fetching system and libraries information...
System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M1
    Memory: 107.48 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/eflashcardapp/.rvm/gems/ruby-2.7.4/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 23, 28, 29, 30, 31, 32
      Build Tools: 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0
      System Images: android-26 | Intel x86 Atom_64, android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-31 | ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-Sv2 | Google APIs Intel x86 Atom_64, android-Sv2 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.5 => 0.69.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

Installed libs: 
"react native reanimated"
"react native camera vision"

### Snack, code example, screenshot, or link to a repository

<img width="708" alt="Screen Shot 2022-08-26 at 12 40 21" src="https://user-images.githubusercontent.com/8979249/186830732-24ad8abc-30e4-429e-8cfd-22a28987357b.png">

**Comment by SectionTN** [comment] 2022-08-27 01:35
Hey @ntcong91 

this is a simple workaround working for me, check it out! [link](https://github.com/mrousavy/react-native-vision-camera/issues/1148#issuecomment-1214998966)

**Comment by ntcong91** [comment] 2022-08-27 10:06
Thanks @SectionTN the problem is raised and the problem should be resolved in the official releases.

**Comment by cortinico** [comment] 2022-09-16 15:00
> I run
> ```
> yarn android
> ```
> And the boost library downloaded too many times with many boost lib. This is really annoy when I entered in the low network. Please fix this - thanks

We're looking into this issue and in one of the future release we'll offer a way for libraries to re-use the downloaded native sources (so that reanimated and react-native-vision-camera don't need to re-download it).

Closing for now as this it's 'working as intended' at the moment but I agree it's not optimal

**Closed** 2022-09-16 15:01 UTC
Labels: Type: New Architecture, Resolution: Answered
