### ISSUE TITLE
[Animated] getting "Object.isFrozen can only be called on Objects" intermittently

### ISSUE THREAD

**Issue by lelandrichardson** [facebook/react-native#2033] opened 2015-07-17 22:06 UTC
I haven't been able to get a base-case repro, but I seem to be getting the following error every once in a while when working with the animated API.

Anyone know what this might be an indication of?

![](http://i.imgur.com/JElTCap.png)

**Comment by ide** [comment] 2015-07-17 22:08
Probably easiest to set a breakpoint in the debugger on all exceptions and inspect what the bad value is (could be something like null or false).

**Comment by lelandrichardson** [comment] 2015-07-17 22:22
@ide I'm trying but i'm experiencing *another* issue where I can't seem to debug in chrome :/ argh.

**Comment by ide** [comment] 2015-07-17 22:41
You can use the Safari debugger by going to Develop > iOS Simulator > JSContext. It's not as good but should help a lot letting you set breakpoints and inspect the stack.

**Comment by brentvatne** [comment] 2015-07-20 18:22
@lelandrichardson - is this happening with the `Formula` API that you're working on? or the base API? Also, is this occurring against master? `precomputeStyle` was updated recently to add some additional rotation/perspective properties, that may have had an effect.

**Comment by lelandrichardson** [comment] 2015-07-21 02:37
@brentvatne it's happened a couple of times, some of which were before I was using a fork. I'll make sure I'm working with the latest version of master, though. It hasn't happened in a while which is why I haven't updated this with more information, but I'm also on vacation so only working a couple hours/day.

Next time this happens with the debugger open I'll definitely try and figure out what path it's going through, but it's not happening to me very often any more.

**Comment by brentvatne** [comment] 2015-07-21 05:06
Awesome, enjoy the vacations @lelandrichardson :smile: :rocket:

**Comment by brentvatne** [comment] 2015-07-31 00:08
@vjeux - any idea what is going on here? based on [deepFreezeAndThrowOnMutationInDev](https://github.com/facebook/react-native/blob/master/Libraries/Utilities/deepFreezeAndThrowOnMutationInDev.js#L33-L39) `Object.isFrozen` should never be called on a non-Object; it should escape early when the `typeof` check fails. cc @spicyj

**Comment by lelandrichardson** [comment] 2015-07-31 00:25
@brentvatne I have had it happen several times since I opened this ticket, but I can't seem to get it to happen while I have the debugger running to see why it's happening...

**Comment by ide** [comment] 2015-07-31 00:26
Maybe in your fork wrap that piece of code in try-catch and print out the bad value when it happens?

**Comment by spicyj** [comment] 2015-07-31 01:23
Maybe some sort of host object. I could imagine if you tried to freeze a DOM node, for example, then it could give that error – but I'm not sure how many such objects we have in the RN environment. Not many.

**Comment by lelandrichardson** [comment] 2015-07-31 02:12
@ide i'll give that a shot

**Comment by corymsmith** [comment] 2015-08-04 15:33
Any updates on this? I'm running into the same issue with the Spinner component I just added to React Native Icons

**Comment by NikolaDimitroff** [comment] 2015-09-20 03:52
@ide, @lelandrichardson What's the state of this issue? I encountered the same problem on Android and [this JSX](http://pastebin.com/VSTT2DF6) reproduces the crash 100% of the time, though sometimes it crashes after 30 seconds and other times almost instantly after startup. The app is a simple fluid grid with many cells, each containing a box. On startup, all the cells start moving from left to right and back again. (I do know that I can translate the entire container, this was created as a performance test, not a usability one).

The app works on iOS but has terrible performance - only 100 cells get the frame rate down to about 25 fps in release builds on a 5th generation iPod (iOS 8.4). Am I misusing the animation API or is this a worst-case scenario?

**Comment by ide** [comment] 2015-09-20 03:55
@NikolaDimitroff I've never encountered this issue -- it'd help a lot if you could add breakpoints / console.log statements to identify what the cause is.

You could try putting overflow:hidden on each cell and removeClippedSubviews on the ListView, though I have seen that the UIExplorer's animation example runs poorly on an iPod touch.

**Comment by NikolaDimitroff** [comment] 2015-09-20 04:39
@ide `removeClippedSubviews` + `overflow: hidden` did not help. As for the logs and breakpoints - I have no clue what to log / debug. The entire callstack is inside the core library and I'm only using the Animations module as suggested by the docs. No JS is executed past the initialization step other than restarting the animation.

**Comment by ide** [comment] 2015-09-20 05:04
@NikolaDimitroff I mean adding debugging code inside of the core library (deepFreezeAndThrowOnMutationInDev.js it looks like) to figure out what kind of value is being passed to Object.isFrozen.

**Comment by marcshilling** [comment] 2015-10-02 16:36
Subscribing....I get this randomly as well - on Android only.

**Comment by ide** [comment] 2015-10-02 18:28
To push this forward: If this issue is affecting your code please dive in and investigate if you would like it fixed in this specific case. We need to know what the bad value is and where it is coming from but can't easily tell what it is without having a repro. Setting conditional breakpoints and more logging inside of React internals is where I would start.

**Comment by marcshilling** [comment] 2015-10-02 20:19
![screen shot 2015-10-02 at 4 18 53 pm](https://cloud.githubusercontent.com/assets/5598961/10256778/50578048-6921-11e5-8ded-b97ee93b4b32.png)

`¯\_(ツ)_/¯`

**Comment by spicyj** [comment] 2015-10-02 20:21
https://github.com/facebook/react-native/blob/0fb2fb37cca8fd049695c2835714de739aeb259c/Libraries/Utilities/deepFreezeAndThrowOnMutationInDev.js

**Comment by marcshilling** [comment] 2015-10-02 20:29
Thanks @spicyj. I've got a try/catch set for the next time it happens.

**Comment by ide** [comment] 2015-10-02 20:36
@marcshilling thanks. I'd help investigate but have never encountered this issue myself (nor have any of the people I work with).

**Comment by xinthink** [comment] 2015-10-05 11:32
I managed to reproduce this issue, it's an animation which will repeat forever, the error occurs on **Android** after the animation run for a while, iOS seems no problem.

In the following code snippet, I repeat the animation by calling `start` again in its lifecycle callback. The use of `setImmediate` can delay the problem, but not prevent it.

And it's weird that when I try to add logging to the `deepFreezeAndThrowOnMutationInDev` function, such as `console.log(object, typeof object)`, or debugging in Chrome, the problem will never happen.

```jsx
const ROTATE_INTERP = {
  inputRange: [
    0, .25, .5, .75, 1,
  ],
  outputRange: [
    '0deg', '90deg', '180deg', '270deg', '360deg',
  ],
};

const Progress = React.createClass({
  getInitialState: function () {
    this._animatedAngle = new Animated.Value(0);
    return {};
  },
  componentDidMount: function () {
    this.startRotation();
  },
  startRotation: function () {
    this._animatedAngle.setValue(0),
    Animated.timing(this._animatedAngle, {
      duration: 1000,
      toValue: 1,
    // }).start(({finished}) => finished && setImmediate(this.startRotation));
    }).start(() => this.startRotation());
  },
  render: function () {
    return (
      <View style={{
          alignItems: 'center',
          justifyContent: 'center',
          paddingTop: 200,
        }}
        >
        <Animated.Text
          style={{
            backgroundColor: 'green',
            width: 64,
            height: 64,
            borderRadius: 32,
            color: 'white',
            fontWeight: 'bold',
            fontSize: 42,
            transform: [
              {rotate: this._animatedAngle.interpolate(ROTATE_INTERP)},
            ],
          }}
          >
          .
        </Animated.Text>
      </View>
    );
  },
});
```

- RN 0.11.4
- Android 5.1.1

**Comment by NikolaDimitroff** [comment] 2015-10-05 15:19
@ide Seems you missed the repro script from my previous comment. Here it goes again - http://pastebin.com/VSTT2DF6. This crashes on Android after a random amount of time, but most often in less 5 seconds after start. I have not further investigated the cause of the issue because there are more important coding matters to attend to.

**Comment by jelsabird** [comment] 2016-03-10 13:02
I got this error when I experimentet with extended stylesheet in my app. I installed and required react-native-extended-stylesheet successfully. When I used EStyleSheet.create instead of StyleSheet.create, the function wasn't recognized. So I tried changing it back to StyleSheet.create, still having variables like $margin inside the style sheet. That's when I got Object.freeze can only be called on Objects. Any ideas of how the error could be connected to my changes? I can see that the error refers to the StyleSheetRegistry. I am also using Animated in one part of the app, but I haven't seen this error until now. The error appears rightaway everytime I run.
![require estylesheet use stylesheet create](https://cloud.githubusercontent.com/assets/17073708/13670178/9ee7bbd6-e6c8-11e5-86bc-847f0ac7e967.PNG)

**Comment by PimDeWitte** [comment] 2016-06-08 22:22
@jelsabird this is exactly what I did as well. It seems to just have messed up the StylesheetRegistry in general. Try re-installing react native.

**Comment by PimDeWitte** [comment] 2016-06-08 22:31
I had custom properties called deviceWidth and deviceHeight in my stylesheet, moving them out of the StyleSheet class (and strictly using Stylesheet properties fixed my issue). 

Before:
<img width="477" alt="screen shot 2016-06-08 at 3 31 03 pm" src="https://cloud.githubusercontent.com/assets/8763534/15913319/10920f64-2d8e-11e6-8032-e009e530dcc9.png">


After:
<img width="517" alt="screen shot 2016-06-08 at 3 30 56 pm" src="https://cloud.githubusercontent.com/assets/8763534/15913322/15c52dea-2d8e-11e6-850e-dde608f14093.png">

**Comment by bravealdus** [comment] 2016-09-01 20:01
I had the same error, and it was because of an 'undefined' variable inside a StyleSheet, I was doing something like defaults.link from another StyleSheet. Fixing the undefined variable, fixed the problem. Also, this doesn't trigger an error on iOS.

**Comment by charpeni** [comment] 2016-11-14 01:14
@facebook-github-bot label Icebox

**Comment by charpeni** [comment] 2016-11-14 01:14
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/animated-getting-objectisfrozen-can-only-be-called-on-objects-intermittently

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment] 2016-11-14 01:14
@facebook-github-bot close

**Closed** 2016-11-14 01:15 UTC
Labels: Icebox, JS, Ran Commands

**Comment by njafei** [comment] 2017-05-26 05:47
I hava run into this problem, and I fix it in:

```
const styles = StyleSheet.create({
    fontSize: 12
})

const styles = StyleSheet.create({
    defaltStyle: {
        fontSize: 12,
    }
})
```

It's the styleSheet is wrong
