### ISSUE TITLE
Could not find any matches for com.facebook.react:react-native:+ as no versions of com.facebook.react:react-native are available.

### ISSUE THREAD

**Issue by yanel777** [facebook/react-native#35845] opened 2023-01-16 15:53 UTC
### New Version

0.71.0, 0.71.0-rc.3 (tried both)

### Old Version

0.68.5

### Build Target(s)

android development debug

### Output of `react-native info`

System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 129.95 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.10.0 - /opt/homebrew/bin/node
    Yarn: Not Found
    npm: 8.19.2 - /opt/homebrew/bin/npm
    Watchman: 2022.10.03.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 28, 29, 30, 31, 32, 33
      Build Tools: 28.0.3, 30.0.2, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.1
      System Images: android-30 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.1/14B5033e - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /opt/homebrew/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.0-rc.3 => 0.71.0-rc.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

 ./gradlew installDevelopmentDebug

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':react-native-linear-gradient:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-linear-gradient:debugCompileClasspath'.
   > Could not find any matches for com.facebook.react:react-native:+ as no versions of com.facebook.react:react-native are available.

this error fail for all libraries

**Comment by cortinico** [comment] 2023-01-19 09:54
> react-native: 0.71.0-rc.3 => 0.71.0-rc.3

You say you're on 0.71.0 but your environment info says you're on `0.71.0-rc.3`
Can you please confirm on which version are you?
Plus can you provide a reproducer of this bug?

**Comment by RobinLindhout** [comment] 2023-01-19 11:27
We have the same issue

**Comment by yanel777** [comment] 2023-01-20 14:07
> > react-native: 0.71.0-rc.3 => 0.71.0-rc.3
> 
> You say you're on 0.71.0 but your environment info says you're on `0.71.0-rc.3` Can you please confirm on which version are you? Plus can you provide a reproducer of this bug?

sorry. same issue on 0.71.0 and 0.71.0-rc.3
I have tried both

**Comment by cortinico** [comment] 2023-01-20 17:19
I'm looking for a repro at this stage as I can't help further

**Comment by jguipi** [comment] 2023-01-23 21:12
same issues on my side

**Comment by indyteo** [comment] 2023-02-04 19:09
Hello,
I ran into the same issue after upgrading to RN 0.71 and I found a workaround that worked for me:
* Open `android/app/build.gradle` **BE CAREFUL IT'S NOT `android/build.gradle`!!!**
* Add `apply plugin: "com.facebook.react"` like this:
```diff
 apply plugin: "com.android.application"
+apply plugin: "com.facebook.react"

 import com.android.build.OutputFile
 ...
  ```
* Rebuild your application, it should works

However, this warning (shown when building) makes me feel this will break soon...
```
##############################

Using react.gradle in your project is deprecated! You should move to "apply plugin: com.facebook.react"
react.gradle is going to be removed in a future React Native project and your project will not build anymore.
You can use the template as a reference:
https://github.com/facebook/react-native/blob/main/template/android/app/build.gradle

##############################
```
Maybe we can completely replace the `android/app/build.gradle` file by [this one](https://github.com/facebook/react-native/blob/main/template/android/app/build.gradle), I didn't tested it [because](https://user-images.githubusercontent.com/26201395/216785272-0371a29e-7afd-4511-a80c-c669d78bb9bf.png)...

**Comment by cortinico** [comment] 2023-02-08 19:35
> However, this warning (shown when building) makes me feel this will break soon...

The warning is there because you're still importing `react.gradle` which you should not.
If you follow the upgrade helper you'll see that you have to use `apply plugin: com.facebook.react`

**Comment by dmg46664** [comment] 2023-02-16 13:40
@cortinico I'm hitting a similar issue although probably not the same (message slightly different).
However my question applies to both. Is there a way of getting the build to expand out what the dependency graph can see and the places it does check? Surely that would mean individuals can help narrow the problem themselves in the future?

**Comment by dmg46664** [comment] 2023-02-16 13:50
I found a thread to pull on at least. I think this hint should be in the error message as it isn't obvious:
https://stackoverflow.com/questions/42596358/how-to-enable-stacktrace-react-native-run-android-command

**Comment by cortinico** [comment] 2023-02-16 17:05
> @cortinico I'm hitting a similar issue although probably not the same (message slightly different).

@dmg46664 then please open a separate issue, share a reproducer and your environment. This issue is pending feedback from @yanel777. You can get an overview of your dependency tree if you run `cd android && ./gradlew :app:assembleDebug --scan` and check the Gradle Scan that gets produced.

**Comment by Danushka96** [comment] 2023-03-02 08:26
[https://react-native-community.github.io/upgrade-helper/?from=0.68.5&to=0.71.0
](https://react-native-community.github.io/upgrade-helper/?from=0.68.5&to=0.71.0
)
Update the package.json and app/build.gradle file according to the changes

**Comment by Mmferry** [comment] 2023-03-15 10:18
I have same error with react native v0.69.6

**Comment by DeVoresyah** [comment] 2023-04-10 13:12
I also facing same issue, but for my case I think it's because this library `react-native-mmkv-storage`

Error:
```
* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find any matches for com.facebook.react:react-android:+ as no versions of com.facebook.react:react-android are available.
     Searched in the following locations:
       - file:/Users/cryptokun/Documents/react-native/MuloApp/node_modules/react-native/android/com/facebook/react/react-android/maven-metadata.xml
       - file:/Users/cryptokun/Documents/react-native/MuloApp/node_modules/jsc-android/dist/com/facebook/react/react-android/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/com/facebook/react/react-android/maven-metadata.xml
       - https://www.jitpack.io/com/facebook/react/react-android/maven-metadata.xml
     Required by:
         project :app > project :react-native-mmkv-storage
```

**Comment by cortinico** [comment] 2023-04-11 10:37
> I also facing same issue, but for my case I think it's because this library `react-native-mmkv-storage`

Closing as this kind of issues are related to specific libraries. You can find which library is causing the issue in the error message like here:

>      Required by:
>         project :app > project :react-native-mmkv-storage

Please re-open if you believe this is a bug in React Native core.

**Closed by cortinico** 2023-04-11 10:37 UTC
Labels: Needs: Author Feedback, Type: Upgrade Issue

**Comment by AkhileshManda** [comment] 2023-04-14 07:32
@DeVoresyah I am facing the same issue, did you end up finding up a solution?

**Comment by DeVoresyah** [comment] 2023-04-14 07:47
> @DeVoresyah I am facing the same issue, did you end up finding up a solution?

yes by upgrading the react-native version into 0.71.6

**Comment by franznkemaka** [comment] 2023-04-26 17:40
> I also facing same issue, but for my case I think it's because this library `react-native-mmkv-storage`
> 
> Error:
> 
> ```
> * What went wrong:
> Could not determine the dependencies of task ':app:processDebugResources'.
> > Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
>    > Could not find any matches for com.facebook.react:react-android:+ as no versions of com.facebook.react:react-android are available.
>      Searched in the following locations:
>        - file:/Users/cryptokun/Documents/react-native/MuloApp/node_modules/react-native/android/com/facebook/react/react-android/maven-metadata.xml
>        - file:/Users/cryptokun/Documents/react-native/MuloApp/node_modules/jsc-android/dist/com/facebook/react/react-android/maven-metadata.xml
>        - https://dl.google.com/dl/android/maven2/com/facebook/react/react-android/maven-metadata.xml
>        - https://www.jitpack.io/com/facebook/react/react-android/maven-metadata.xml
>      Required by:
>          project :app > project :react-native-mmkv-storage
> ```

I just faced the same issues, 

it turns out React Native MMKV Storage > 2.5.1 isn't compatible with React Native below 0.71

Checkout the breaking changes: https://github.com/mrousavy/react-native-mmkv/releases

**Comment by fatemehmarzoughi** [comment] 2023-05-17 21:55
I have also faced the same problem
`react-native: 0.71.8`
and I have added `apply plugin: "com.facebook.react"` to `app/build.gradle`
and getting this error: 
```js
* What went wrong:
A problem occurred evaluating project ':app'.
> Plugin with id 'com.facebook.react' not found.
```

**Comment by hanafnafs** [comment] 2023-05-18 14:17
> I have also faced the same problem `react-native: 0.71.8` and I have added `apply plugin: "com.facebook.react"` to `app/build.gradle` and getting this error:
> 
> ```js
> * What went wrong:
> A problem occurred evaluating project ':app'.
> > Plugin with id 'com.facebook.react' not found.
> ```
> 
> I appreciate any help 🙏

Same happened with me, any updates regarding this?

**Comment by delki8** [comment] 2023-05-20 17:46
**I'm upgrading from react-native `0.70.0` to `0.71.0`.**

First I was getting a `Could not get unknown property 'hermesEnabled' for project ':app' of type org.gradle.api.Project.`
which was 'fixed' adding `hermesEnabled=true` to gradle.properties.

Then I started seeing the `Could not find any matches for com.facebook.react:react-native:+ as no versions of com.facebook.react:react-native are available.`
to fix it I added the plugin: `"com.facebook.react"` to `app/build.gradle`

What I'm now seeing is this **> Plugin with id 'com.facebook.react' not found.** which I'm not sure how to fix.

**Comment by flyskywhy** [comment] 2023-06-21 08:17
My RN 0.64.3 APP fixed it ref to https://stackoverflow.com/a/76521278/6318705

**Comment by omri81** [comment] 2023-10-04 08:17
> **I'm upgrading from react-native `0.70.0` to `0.71.0`.**
> 
> First I was getting a `Could not get unknown property 'hermesEnabled' for project ':app' of type org.gradle.api.Project.` which was 'fixed' adding `hermesEnabled=true` to gradle.properties.
> 
> Then I started seeing the `Could not find any matches for com.facebook.react:react-native:+ as no versions of com.facebook.react:react-native are available.` to fix it I added the plugin: `"com.facebook.react"` to `app/build.gradle`
> 
> What I'm now seeing is this **> Plugin with id 'com.facebook.react' not found.** which I'm not sure how to fix.

found any solution for this? facing the same issue

**Comment by delki8** [comment] 2023-10-04 11:44
@omri81 try this: https://github.com/facebook/react-native/issues/36234#issuecomment-1439770679. Not sure if that was my solution but it's the closest I can get to whatever worked for me.

**Comment by Nomismagit** [comment] 2025-02-14 16:39
> I have also faced the same problem `react-native: 0.71.8` and I have added `apply plugin: "com.facebook.react"` to `app/build.gradle` and getting this error:
> 
> * What went wrong:
> A problem occurred evaluating project ':app'.
> > Plugin with id 'com.facebook.react' not found.
> I appreciate any help 🙏
