### ISSUE TITLE
cant find variable :self

### ISSUE THREAD

**Issue by gmchaturvedi1** [facebook/react-native#10206] opened 2016-10-02 12:32 UTC
i am just installed 0.34 version .erverything is working till i use navigationExperimental following error is coming 👍 
![image](https://cloud.githubusercontent.com/assets/10846505/19020567/48f9cee0-88ca-11e6-8c83-db1e87880de1.png)

if i use choose debug remote my code is working without any problem .Kindly help is their any dependency required.

**Comment by lacker** [comment] 2017-02-07 23:02
I think we would need a more detailed code example to reproduce this. I am going to close this issue but if you discover something that looks like a bug in React Native while investigating this please feel free to open a new one!

**Closed by lacker** 2017-02-07 23:02 UTC
