### ISSUE TITLE
Error when running react-native run-ios: Print: Entry, ":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by lukitos** [facebook/react-native#21518] opened 2018-10-05 18:04 UTC
## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
      Memory: 1.12 GB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.4 - /usr/local/bin/node
      Yarn: yarn install v0.27.5
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.77s. - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Android Studio: 2.3 AI-162.4069837
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.2 => 0.57.2 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1

## Description

** BUILD FAILED **

The following build commands failed:

	CompileC /Users/slukito/Documents/Meetups/practice/testProj/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/strtod.o /Users/slukito/Documents/Meetups/practice/testProj/node_modules/react-native/third-party/double-conversion-1.1.6/src/strtod.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/slukito/Documents/Meetups/practice/testProj/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/fast-dtoa.o /Users/slukito/Documents/Meetups/practice/testProj/node_modules/react-native/third-party/double-conversion-1.1.6/src/fast-dtoa.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/slukito/Documents/Meetups/practice/testProj/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/fixed-dtoa.o /Users/slukito/Documents/Meetups/practice/testProj/node_modules/react-native/third-party/double-conversion-1.1.6/src/fixed-dtoa.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(3 failures)

Installing build/Build/Products/Debug-iphonesimulator/testProj.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/testProj.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/testProj.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:601:13)
    at Object.execFileSync (child_process.js:621:13)
    at Promise.then (/Users/slukito/Documents/Meetups/practice/testProj/node_modules/react-native/local-cli/runIOS/runIOS.js:208:5)
    at <anonymous>

## Reproducible Demo
react-native init testProj
cd testProj
react-native run-ios

**Comment by hramos** [comment] 2018-10-05 18:46
Duplicate of https://github.com/facebook/react-native/issues/20774

**Closed by hramos** 2018-10-05 18:46 UTC
Labels: :large_blue_diamond:iOS, 📦Bundler

**Comment by lukitos** [comment] 2018-10-05 19:29
I followed the instructions to install the third party tools and revert to XCode Legacy build, but now I got this error.

Loading dependency graph, done.
error: bundling failed: Error: Unable to resolve module `./../react-transform-hmr/lib/index.js` from `/Users/slukito/Documents/Meetups/practice/testProj/App.js`: The module `./../react-transform-hmr/lib/index.js` could not be found from `/Users/slukito/Documents/Meetups/practice/testProj/App.js`. Indeed, none of these files exist:
  * `/Users/slukito/Documents/Meetups/practice/react-transform-hmr/lib/index.js(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
  * `/Users/slukito/Documents/Meetups/practice/react-transform-hmr/lib/index.js/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
    at ModuleResolver.resolveDependency (/Users/slukito/Documents/Meetups/practice/testProj/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:209:697)
    at ResolutionRequest.resolveDependency (/Users/slukito/Documents/Meetups/practice/testProj/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:83:16)
    at DependencyGraph.resolveDependency (/Users/slukito/Documents/Meetups/practice/testProj/node_modules/metro/src/node-haste/DependencyGraph.js:222:485)
    at Object.resolve (/Users/slukito/Documents/Meetups/practice/testProj/node_modules/metro/src/lib/transformHelpers.js:149:25)
    at dependencies.map.result (/Users/slukito/Documents/Meetups/practice/testProj/node_modules/metro/src/DeltaBundler/traverseDependencies.js:316:29)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/slukito/Documents/Meetups/practice/testProj/node_modules/metro/src/DeltaBundler/traverseDependencies.js:312:16)
    at /Users/slukito/Documents/Meetups/practice/testProj/node_modules/metro/src/DeltaBundler/traverseDependencies.js:169:33
    at Generator.next (<anonymous>)
    at step (/Users/slukito/Documents/Meetups/practice/testProj/node_modules/metro/src/DeltaBundler/traverseDependencies.js:271:307)

**Comment by lukitos** [comment] 2018-10-05 19:33
Followed instructions from https://github.com/facebook/react-native/issues/21490 and it now works. Thank you!

```
# Clean cache
rm -rf $TMPDIR/react-*; rm -rf $TMPDIR/haste-*; rm -rf $TMPDIR/metro-*; watchman watch-del-all

# Open a new tab and Start Metro Bundler directly from the project folder
react-native start  --reset-cache

# Now run `react-native run-android` or `react-native run-ios`
```

**Comment by hramos** [comment] 2018-11-14 19:52
Hey folks, please take a look at #21303.
