### ISSUE TITLE
[Android] <Image  source={require('./img/test.png')} />  not work on android !!!

### ISSUE THREAD

**Issue by yesmycar** [facebook/react-native#4081] opened 2015-11-12 01:27 UTC
i write this code in index.android.js, add this code 

<View style={styles.container}>
        <Image  source={require('./img/homebg_blue0.png')} />
        <Text style={styles.instructions}>
          Shake or press menu button for dev menu
        </Text>
 </View>

result:
run work fine ,but  this image is not show,it is white blank  
my run on  windows7 + android

pleast  help me !!!

**Comment by hoangstorm** [comment] 2015-11-12 02:26
Pls read this issues https://github.com/facebook/react-native/issues/4010#issuecomment-155334530

**Comment by yesmycar** [comment] 2015-11-12 02:33
node_modules\react-native\packager\react-packager\src\Bundler\index.js 

line:298

httpServerLocation: path.join('/assets', path.dirname(relPath)),

to :
httpServerLocation: path.join('/assets', path.dirname(relPath)).replace(/\\/g, '/'),

remove  cache  file:
C:\Users\<your name>\AppData\Local\Temp\react-packager-cache*.*

**Comment by rockerhieu** [comment] 2015-11-16 03:05
Similar issue? https://github.com/facebook/react-native/issues/4084

**Comment by mkonicek** [comment] 2015-11-17 14:53
Is this on Windows? Closing as duplicate of https://github.com/facebook/react-native/issues/3980

If it's not Windows let's reopen.

**Comment by mkonicek** [comment] 2015-11-17 14:54
Seems like an easy fix, mind sending a pull request?

**Closed by mkonicek** 2015-11-17 14:53 UTC

**Comment by rockerhieu** [comment] 2015-11-19 07:40
@mkonicek would you mind have a look at #4084? It been there for a week without any answers :(
