### ISSUE TITLE
Touchable cannot transition from `RESPONDER_INACTIVE_PRESS_IN` to `LONG_PRESS_DETECTED`

### ISSUE THREAD

**Issue by satya164** [facebook/react-native#3160] opened 2015-10-01 02:17 UTC
I'm getting this error from time to time during touch. I'm on Android.

```js
Error: Touchable cannot transition from `RESPONDER_INACTIVE_PRESS_IN` to `LONG_PRESS_DETECTED` for responder `.r[1]{TOP_LEVEL}[0].0.0.1.2:2.0.0`
 stack: 
  TouchableMixin._receiveSignal                               index.android.bun…:24354
  TouchableMixin._handleLongDelay                             index.android.bun…:24333
  JSTimers.setTimeout.JSTimersExecution.callbacks.(anonymous  index.android.bun…:6157
  JSTimersExecution.callTimer                                 index.android.bun…:5938
  Object.JSTimersExecution.callTimers                         index.android.bun…:5961
  MessageQueue.__callFunction                                 index.android.bun…:5572
  <unknown>                                                   index.android.bun…:5518
  guard                                                       index.android.bun…:5461
  MessageQueue.callFunctionReturnFlushedQueue                 index.android.bun…:5518
 URL: undefined
 line: undefined
 message: Touchable cannot transition from `RESPONDER_INACTIVE_PRESS_IN` to `LONG_PRESS_DETECTED` for responder `.r[1]{TOP_LEVEL}[0].0.0.1.2:2.0.0`
```

**Comment by ide** [comment] 2015-10-01 02:45
Dupe of https://github.com/facebook/react-native/issues/1693

**Closed by ide** 2015-10-01 02:45 UTC
