### ISSUE TITLE
New app "react-native start" return error without "sudo"

### ISSUE THREAD

**Issue by mnlbox** [facebook/react-native#14631] opened 2017-06-20 13:13 UTC
### Description
Later I can't init project without sudo until I saw [this issue](https://github.com/facebook/react-native/issues/2107) and run `sudo chmod 777 /home/xxxxx/.babel.json`, now I can init project without sudo (like `react-native init AppName`) but when I create a simple project (just a project init) and try running this by `react-native start` it's return bellow message:
```
Loading dependency graph...(node:13642) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: EACCES: permission denied, open '/tmp/haste-map-react-native-packager-1-c06bcb90a866fe5fba0c98b29c4752c1'
```
When I use `sudo react-native start` it's working well. Why it's need `sudo`? How we can fix it?

### Reproduction Steps

Create new project with:
```
react-native init TestApp
```
Change to this project directory:
```
cd TestApp
```
Try start app:
```
react-native start
```

#### Sample Code

Just simple hello world.

### Solution

Run with `sudo`

### Additional Information

* React Native version: 0.45.1
* Platform: both
* Development Operating System: Linux
* Build tools: React V. 16.0.0-alpha.12

**Comment by hramos** [comment] 2017-06-20 15:49
You shouldn't need to use sudo. Can you provide more details about your OS, which steps did you follow to set up your dev environment?

**Comment by mnlbox** [comment] 2017-06-20 15:57
@hramos I used https://facebook.github.io/react-native/docs/getting-started.html and install react native CLI.
```
npm install -g react-native-cli
```
Use OpenJDK
and other steps based on above tutorial.
My OS is Linux Mint 18.1.

**Comment by hramos** [comment] 2017-06-20 16:16
Did you install watchman?

**Comment by mnlbox** [comment] 2017-06-21 06:43
@hramos No because docs said that it's optional.

**Comment by hramos** [comment] 2017-06-21 18:43
Please give that a try. It's less straightforward to install on Linux so it was marked as optional, but there may be certain situations where the tooling assumes watchman is installed.

**Comment by mnlbox** [comment] 2017-06-22 05:22
I don't understand so why it's working well with `sudo`? :thinking:

**Comment by mnlbox** [comment] 2017-07-08 11:10
Any suggestion about this?

**Comment by hramos** [comment] 2017-09-21 15:09
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Closed by hramos** 2017-09-21 15:09 UTC
Labels: Icebox

**Comment by simplenotezy** [comment] 2017-10-12 18:20
I receive the error:

     ERROR  watchman --no-pretty get-sockname returned with exit code=1, signal=null, stderr= 2017-10-12T20:19:24,539: [2552390464] opendir(/usr/local/var/run/watchman/simplenotezy-state): Permission denied

**Comment by vishnumohan89** [comment] 2017-11-09 09:01
After installing watchman, my issue got fixed
