### ISSUE TITLE
If iOS has too much photo, CameraRoll will cause app crash

### ISSUE THREAD

**Issue by someok** [facebook/react-native#7818] opened 2016-05-28 15:36 UTC
React Native: 0.24-0.26
iOS: 8-9

![1464009358669-img_0115](https://cloud.githubusercontent.com/assets/1523082/15628155/d57ecfde-252c-11e6-90ae-99df4d089494.png)

**Comment by charpeni** [comment] 2016-05-29 17:13
@facebook-github-bot label iOS

**Comment by lacker** [comment] 2016-10-21 07:27
I think this issue does not have enough information to make progress on it - we need some information about the crash or about a sample app. I'm going to close this issue but feel free to open a new one if you have more information here.

**Closed by lacker** 2016-10-21 07:27 UTC
Labels: iOS, Ran Commands

**Comment by gre** [comment] 2017-03-30 15:28
The problem with what you suggested, @lacker, is that there is no way to reproduce it with just a sample app. It's not about an app that reproduce the bug but the contextual around it: a user that have a LOT of images.

related to that, there is this SO question http://stackoverflow.com/questions/35077923/ios-app-crashes-for-some-users-when-using-alassetslibrary-to-retrieve-images-in and someone answered  *"I think it was dew to large number of photos(more than 18k) in the client's phone. So I shifted to PHPhotoFramework. Now its working fine. Anyway thanks for your precious replies."*

React Native camera roll code currently is relying on ALAssetsLibrary that seems to have problem with users with lot of images.
**Do React Native have plan to migrate to PHPhotoFramework ?** (ALAssets is deprecated according to apple doc?)


---

BTW, we've noticed similar user crashes in prod with very few users (like less than 1% of them), I can't confirm yet that it's because they have a lot of images (still investigating) but i'll try to get back to you when I know this for sure.
