### ISSUE TITLE
on React Native 0.46 a reload ( manually triggered  or hot/live) causes often the application to not reload and hang if Debug js remotely is enabled

### ISSUE THREAD

**Issue by bgiavotto** [facebook/react-native#15298] opened 2017-07-31 22:33 UTC
### Is this a bug report?

Yes

### Have you read the Bugs section of the How to Contribute guide?

Yes

### Environment

1. `react-native -v`:0.46
2. `node -v`: 8.x
3. `npm -v`: 3.10.9
4. `yarn --version`: do not use

Then, specify:

- Target Platform: Android

- Development Operating System: Windows

- Build tools: no

### Steps to Reproduce

(Write your steps here:)

1. just install React-native-Cli. Verify that the React Native is 0.46.x
2. run the react-native init MYAPP
3. after application run it with the run-android option
4. hit "R" twice or do a reload with JS Debug disabled
5. Do the same on step 4 with JS Debug enabled or invoche a reload manually from menu or a live reload
6. repeat the step 5 three or four times, sometimes the application does not reload at the first try

### Expected Behavior

The application should reload fine even with JS debug enabled or reload should be disabled when JS debug is in place.

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by rajsuvariya** [comment] 2017-08-01 05:05
+1

**Comment by ismjt** [comment] 2017-08-02 15:29
+1

**Comment by ismjt** [comment] 2017-08-02 15:31
+1
Environment

react-native -v:0.46.4
node -v: 6.10.3
npm -v: 3.10.10
yarn --version: 0.24.4
Then, specify:

Target Platform: Android
Development Operating System: Windows 10
Build tools: no

**Comment by bgiavotto** [comment] 2017-08-02 18:46
not fixed even on 0.47.1

**Comment by hramos** [comment] 2017-08-03 19:12
Closed the newer issue. You can edit your original post here with the new information.

**Comment by hramos** [comment] 2017-08-03 19:13
Duplicate of #14453

**Comment by hramos** [comment] 2017-08-03 19:13
Actually, it looks like #14453 already covers this.

**Closed by hramos** 2017-08-03 19:13 UTC
