### ISSUE TITLE
[LocalNotifications] Cancelling scheduled local notifications

### ISSUE THREAD

**Issue by davidskaarup** [facebook/react-native#2185] opened 2015-07-31 09:06 UTC
Would it be possible to add the option of cancelling specific / all scheduled local notifications?

**Comment by brentvatne** [comment] 2015-07-31 17:55
This is something that a few people have worked on already but has yet to be integrated into core cc @mattmo

**Comment by davidskaarup** [comment] 2015-07-31 19:28
Cool

I just tried to look at it myself and I think I managed to implement something that seems to work. I am a complete Objective C newbie, so this might not be the correct way but maybe somebody can use it and/or make a pull request.

In RCTPushNotificationManager.m I added the following:
```
RCT_EXPORT_METHOD(cancelAllLocalNotifications)
{
  [[UIApplication sharedApplication] cancelAllLocalNotifications];
}
```

And in PushNotificationIOS.js this:
```
static cancelAllLocalNotifications() {
  RCTPushNotificationManager.cancelAllLocalNotifications();
}
```

Then it's possible to call
```
PushNotificationIOS.cancelAllLocalNotifications();
```

Again, I have no idea if there are any problems with this implementation and I don't know how to cancel a specific notification, but hopefully someone who knows more than me can look into it :)

**Comment by strefethen** [comment] 2015-08-05 19:58
@brentvatne any ideas if some of the other work you referenced here has traction for making it into the core? Local notifications would be really useful.

**Comment by truewh** [comment] 2015-08-19 14:38
+1 for Local Notifications, especially considering those users who are not constently connected due to bad signal and/or limited data plan. Any clue for the progress? Thanks!

**Comment by jhabdas** [comment] 2015-11-05 22:46
Looks like this issue was fixed 20 days ago with https://github.com/facebook/react-native/commit/da250671e55b971ef73b9a02c5e65d4f0325f68f, is a duplicate of #2980 and can safely be closed.

**Comment by randomer** [comment] 2015-11-06 02:05
@jhabdas It's still not possible to cancel specific notifications though...

**Comment by jhabdas** [comment] 2015-11-06 04:34
Oh. Details. :eyeglasses: Carry on.

**Comment by mkonicek** [comment] 2016-04-10 16:39
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/localnotifications-cancelling-scheduled-local-notifications

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Closed by mkonicek** 2016-04-10 16:39 UTC
Labels: Icebox
