### ISSUE TITLE
Release build crashes on iOS and Android. Fatal Exeption.

### ISSUE THREAD

**Issue by YeshanJay** [facebook/react-native#16567] opened 2017-10-27 12:43 UTC
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  8.4.0
  Yarn:  Not Found
  npm:  5.4.1
  Watchman:  4.9.0
  Xcode:  Xcode 8.3.3 Build version 8E3004b
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: ^0.49.3 => 0.49.3

  Target Platform: iOS (8.0) Android (26)

### Steps to Reproduce

1. For **iOS**, open xcode and open the project.
2. Setup release configurations.
3. Connect a device, and click on run to deploy into device.
4. An exception occurs with reason as follows: 
```
'Unhandled JS Exception: undefined is not an object (evaluating 's.View.prop..., stack:
<unknown>@663:2841
i@2:553
<unknown>@661:243
i@2:553
<unknown>@660:153
i@2:553
<unknown>@304:251
i@2:553
<unknown>@12:38
i@2:553
n@2:266
global code@671:9
```

5. For **Android**, setup release configurations.
6. Open the Terminal and run: `sudo react-native run-android --variant=release`.
7. After the build is successful, the app is deployed to the connected device, then crashes with the following message (from logs):
```
--------- beginning of crash
10-27 17:52:08.151 18268-18313/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
	Process: com.storefinder_yj, PID: 18268
	com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 's.View.propTypes.style'), stack:
	   <unknown>@659:2841
	   i@2:565
	   n@2:348
	   t@2:210
	   <unknown>@657:243
	   i@2:565
	   n@2:348
	   t@2:210
	   <unknown>@656:153
	   i@2:565
	   n@2:348
	   t@2:210
	   <unknown>@302:251
	   i@2:565
	   n@2:348
	   t@2:210
	   <unknown>@12:38
	   i@2:565
	   n@2:278
	   t@2:210
	   global code@667:9
	   
		   at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:56)
		   at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:40)
		   at java.lang.reflect.Method.invoke(Native Method)
		   at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:363)
		   at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
		   at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
		   at android.os.Handler.handleCallback(Handler.java:751)
		   at android.os.Handler.dispatchMessage(Handler.java:95)
		   at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
		   at android.os.Looper.loop(Looper.java:154)
		   at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
		   at java.lang.Thread.run(Thread.java:761)


10-27 17:52:08.591 18268-18312/? E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling unmountApplicationComponentAtRootTag)
```

8. Following are the dependencies in `package.json` file:
```
"dependencies": {
	"datejs": "^1.0.0-rc3",
	"prop-types": "^15.6.0",
	"react": "16.0.0-beta.5",
	"react-native": "^0.49.3",
	"react-native-elements": "^0.17.0",
	"react-native-fbsdk": "^0.6.3",
	"react-native-sqlite-2": "^1.5.0",
	"react-native-vector-icons": "^4.4.2",
	"react-navigation": "^1.0.0-beta.15",
	"rn-viewpager": "^1.2.4"
}
```

### Expected Behavior

Application should run on the device without any crashes (in release mode).

### Actual Behavior

Application builds successfully and deploys onto device. Then the app crashes once it opens.
Screen shots are not available since the app crashes and closes, or is just a blank screen.

### Reproducible Demo

Unable to create a reproducible demo.

**Comment by ujwal-setlur** [comment] 2017-10-27 17:56
This is clearly showing that some package is still using View.propTypes. I was running into this too until I did find the offending packages. Please do the following:
1. find node_modules -name "*.map* | xargs rm -f
2. grep -R "View.propTypes" node_modules

The first step removes all the map files so that your grep output is not flooded. You will need to reinstall node_modules later s that you get them back. 

Please check thoroughly the output of the second. You can either post output here or send them to me privately. I just went through the pain myself and would like to help you.

**Comment by ujwal-setlur** [comment] 2017-10-27 17:59
Did you check just your dependencies or the sub-dependencies of your dependencies?

**Comment by YeshanJay** [comment] 2017-10-27 18:54
I checked only my dependencies.

I ran the commands you mentioned, and the second one printed a bunch of lines. And seems like `View.propTypes` is still being used in some of my dependencies (last time I only glanced around for `React.propTypes`).

These are the packages listed: `react-native-elements`, `rn-viewpager`

**Comment by ujwal-setlur** [comment] 2017-10-27 19:06
No worries. You have to check the entire dependency tree for 
1. React.PropTypes
2. PropTypes being imported from react
3. Usage of View.propTypes

All three are illegal in React 16. The fixes for those are respectively:
1. React.PropTypes -> PropTypes (import PropTypes from 'prop-types')
2. Import PropTypes from prop-types instead of react
3. View.propTypes -> ViewPropTypes (import ViewPropTypes from 'react-native')

My approach was this. Check each of those projects on GitHub and see:
1. Has it been fixed in git already? Is there a new version available? If not, use the code from the github repo in your package.json
2. Has someone issued a pull request for this? If so, use that branch.
3. Fork the GitHub repo and fix it yourself

I had to do all three :). The tricky part was when the direct dependency was clean, but a sub-dependency was not. I then had to fork both the direct dependency and its sub-dependency, fix the issue in the sub-dependency fork, change the my fork of the main dependency to use my fork of the sub-dependency.

As you can see, a bloody pain in the proverbial backside! But once I figured out the problem, it took me just a few hours to hit them all.

Good luck!

**Comment by YeshanJay** [comment] 2017-10-27 20:07
hahaha.. I can only imagine what you went through. Thanks a lot again for saving so many hours mine 😄

**Comment by ujwal-setlur** [comment] 2017-10-27 20:51
For anyone using code-push and running into app crashes on launch, see this:

https://github.com/Microsoft/react-native-code-push/issues/1064

**Comment by arma7x** [comment] 2017-10-29 04:59
I'm downgrade to RN 0.45.1 to solve this.

**Comment by YeshanJay** [comment] 2017-10-29 15:10
I downgraded to RN 0.48.4 for now.

**Comment by iLevye** [comment] 2017-10-29 17:18
In my case, upgrading react-native-admob 1.3.2 to 2.0.0-beta.2 solved situation.

**Comment by hironarita** [comment] 2017-10-30 02:39
undefined is not an object (evaluating 'a.propTypes.style')

This is the error I get. I used grep -R 'a.propTypes.style' node_modules and it doesn't even find an instance where this code is executed... I'm confused.

**Comment by ujwal-setlur** [comment] 2017-10-30 04:10
Don't include the 'a'. Please grep for propStyles.style? Is it attached to a View object? In my experience, it is one of the following:

1. PropStyles imported from react
2. Usage of React.PropStyles
3. Usage of View.propStyles

Please check thoroughly for all three.

**Comment by ujwal-setlur** [comment] 2017-10-30 04:14
Also check your own code

**Comment by hironarita** [comment] 2017-10-30 04:28
@ujwal-setlur My grep for 'View.propTypes' outputs a lot of examples like style: ViewPropTypes ? ViewPropTypes.style : View.propTypes.style. Did you have to remove those too?

**Comment by ujwal-setlur** [comment] 2017-10-30 04:35
No those are fine. Those are packages that are trying to be backwards compatible. They first check for ViewPropStyles and then for View.propStyles if ViewPropStyles is essentially null or undefined

**Comment by hironarita** [comment] 2017-10-30 04:38
Those are the only instances where View.propTypes are being used. Nothing else... Strange.

**Comment by ujwal-setlur** [comment] 2017-10-30 04:42
@hironarita did you check your code first? If so, good. 

Unfortunately, you need to check the node_modules code minutely. Please also check for just propStyles.style. 

Yes, this is a bloody pain. If you want you, you can send the output to me and I am happy to double-check for you

**Comment by ujwal-setlur** [comment] 2017-10-30 04:44
@hironarita, can you list your dependencies and devDependencies from your package.json?

**Comment by hironarita** [comment] 2017-10-30 04:46
"dependencies": {
    "@expo/react-native-responsive-image": "^1.2.1",
    "@ptomasroos/react-native-multi-slider": "0.0.11",
    "@types/accounting": "^0.4.1",
    "@types/axios": "^0.14.0",
    "@types/lodash": "^4.14.80",
    "@types/react": "^16.0.18",
    "@types/react-native": "^0.49.5",
    "@types/react-native-modalbox": "^1.4.3",
    "@types/react-navigation": "^1.0.22",
    "@types/react-redux": "^5.0.12",
    "@types/redux": "^3.6.31",
    "accounting": "^0.4.1",
    "axios": "^0.17.0",
    "expo": "^22.0.0",
    "lodash": "4.17.4",
    "moment": "^2.19.1",
    "query-string": "^5.0.1",
    "querystring": "^0.2.0",
    "react": "16.0.0-beta.5",
    "react-native": "https://github.com/expo/react-native/archive/sdk-22.0.1.tar.gz",
    "react-native-animatable": "^1.2.4",
    "react-native-check-box": "2.0.2",
    "react-native-checkbox": "^1.2.0",
    "react-native-gifted-chat": "^0.2.9",
    "react-native-google-places-autocomplete": "^1.3.6",
    "react-native-keyboard-aware-scroll-view": "^0.4.1",
    "react-native-linear-gradient": "^2.3.0",
    "react-native-maps": "^0.17.1",
    "react-native-masked-text": "^1.6.2",
    "react-native-modal": "^4.1.0",
    "react-native-modalbox": "^1.4.2",
    "react-native-progress": "^3.4.0",
    "react-native-scrollable-tab-view": "^0.8.0",
    "react-native-snap-carousel": "^3.3.4",
    "react-native-swipe-gestures": "^1.0.2",
    "react-native-swipeout": "^2.3.1",
    "react-native-textinput-effects": "^0.4.1",
    "react-native-wkwebview-reborn": "^1.10.0",
    "react-navigation": "^1.0.0-beta.15",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "reselect": "^3.0.1"
  }

**Comment by ujwal-setlur** [comment] 2017-10-30 04:51
Ok, I will check these in the morning.

**Comment by hironarita** [comment] 2017-10-30 04:53
Thank you so much.

**Comment by gameboyVito** [comment] 2017-10-30 09:43
After spending tons of time to find out a better solution, I found out there's no need to modify all 3rd party library. The tricky part is to make sure your dev dependencies are correct and use react-native@0.49.5 to build your release. Run `react-native-git-upgrade 0.49.5`

```
"devDependencies": {
    "babel-jest": "21.2.0",
    "babel-preset-react-native": "4.0.0",
    "jest": "21.2.1",
    "react-test-renderer": "16.0.0-beta.5"
  },
```

**Comment by musicode** [comment] 2017-11-01 08:04
modify `react/index.js`

```
'use strict';

import PropTypes from 'prop-types';

let React;
if (process.env.NODE_ENV === 'production') {
  React = require('./cjs/react.production.min.js');
} else {
  React = require('./cjs/react.development.js');
}

React.PropTypes = PropTypes;

module.exports = React;

```

**Comment by ZKeLin** [comment] 2017-11-02 11:46
@ujwal-setlur you are right .I have solued it. I spent too much time for this problem due to another no updated module, it's too painful , thanks so much

**Comment by scue** [comment] 2017-11-03 02:34
@ujwal-setlur Thank you very much!

I change 

`"react-native-elements": "^0.17.0",`

to:

`"react-native-elements": "github:react-native-training/react-native-elements#v0.18.0",`

and everything go well.

**Comment by ujwal-setlur** [comment] 2017-11-03 04:16
glad my pain made yours' shorter :-)

**Comment by ftb2010** [comment] 2017-11-07 09:19
@ujwal-setlur The same code RN0.49.5 Android Release is ok,but when i update from RN0.49.5 to RN0.50.1 Android Release crash again!Any suggestion?

**Comment by ujwal-setlur** [comment] 2017-11-07 15:39
I haven't moved to 0.50 yet. Will look at it today.

**Comment by PvanHengel** [comment] 2017-11-09 12:04
This issue seems to be the same as https://github.com/facebook/react-native/issues/16745 which has a few fixes suggested.

**Comment by REBOOTERS** [comment] 2017-11-13 03:20
I'm curious why this problem only happened in release version . in debug mode everything is ok.

**Comment by dzjin** [comment] 2017-11-15 01:21
My issue was on `react-native-video`. I had 2.0.0, but even after refreshing my node_modules and clearing the cache, I wasn't getting the latest commit that had the fix.

https://github.com/react-native-community/react-native-video/pull/824

Fixed for me by:
`npm install git+https://github.com/react-native-community/react-native-video.git#1ba6b062`

**Comment by thphu** [comment] 2017-11-16 07:39
thanks, but is there any way to work around. let say, I use a lot of lib in my project it's very hard to fix all of them. :(

**Comment by shubhanshusingh** [comment] 2017-12-04 09:37
How I solved this:

1. grep -R "View.propTypes" node_modules
above command fetches me list of all packages to update in my case  ex. rn-viewpager,react-native-material-ui etc.

2. Installed and cloned these scripts. https://github.com/reactjs/react-codemod#reactnative-view-proptypes
3. ran command for each module found in step 1  https://github.com/reactjs/react-codemod#reactnative-view-proptypes

**Comment by dhanushuUzumaki** [comment] 2018-01-07 10:41
I think I don't have any dependencies using View.PropTypes but still release variant crashes.
Using RN 0.51.0

Here is my output of the grep.

node_modules/react-native/Libraries/Lists/ListView/ListView.js:    ...ScrollView.propTypes,
node_modules/react-native/Libraries/Components/WebView/WebView.ios.js:    decelerationRate: ScrollView.propTypes.decelerationRate,
node_modules/react-native/Libraries/ReactNative/verifyPropTypes.js:  // ReactNative `View.propTypes` have been deprecated in favor of
node_modules/react-native/Libraries/ReactNative/requireNativeComponent.js:    // ReactNative `View.propTypes` have been deprecated in favor of
node_modules/react-native/Libraries/Animated/src/createAnimatedComponent.js:  // ReactNative `View.propTypes` have been deprecated in favor of

Any help would be appreciated.

Thanks.

**Comment by dvisco** [comment] 2018-01-19 14:22
I had to update my dependencies to utilize the new `ViewPropTypes` convention. Curious though why does this break in release builds and not in dev builds? Would love a deeper understanding of why i only caught this when testing on our staging environments.

**Comment by jaycee425** [comment] 2018-02-15 10:56
Curios about it too, since had the same problem

**Closed** 2018-02-24 03:26 UTC
Labels: Ran Commands

**Comment by JoseVf** [comment] 2018-02-26 14:16
Still facing this issue in V. 0.53.3.

**Comment by ospfranco** [comment] 2018-02-26 14:59
I'm also having this problem on 0.53.3

**Comment by YogeshYo** [comment] 2018-02-27 14:17
XXXX:ReactWork $ grep -R "View.propTypes" node_modules
node_modules/react-native/Libraries/Components/WebView/WebView.ios.js:    decelerationRate: ScrollView.propTypes.decelerationRate,
node_modules/react-native/Libraries/Lists/ListView/ListView.js:    ...ScrollView.propTypes,
node_modules/react-native/Libraries/ReactNative/requireNativeComponent.js:    // ReactNative `View.propTypes` have been deprecated in favor of
node_modules/react-native/Libraries/ReactNative/verifyPropTypes.js:  // ReactNative `View.propTypes` have been deprecated in favor of
node_modules/react-native-maps/CHANGELOG.md:* Common: [#1792](https://github.com/airbnb/react-native-maps/pull/1792) Make all components use ViewPropTypes || View.propTypes
node_modules/react-native-maps/lib/components/MapCallout.js:const viewPropTypes = ViewPropTypes || View.propTypes;
node_modules/react-native-maps/lib/components/MapCircle.js:const viewPropTypes = ViewPropTypes || View.propTypes;
node_modules/react-native-maps/lib/components/MapLocalTile.js:const viewPropTypes = ViewPropTypes || View.propTypes;
node_modules/react-native-maps/lib/components/MapMarker.js:const viewPropTypes = ViewPropTypes || View.propTypes;
node_modules/react-native-maps/lib/components/MapPolygon.js:const viewPropTypes = ViewPropTypes || View.propTypes;
node_modules/react-native-maps/lib/components/MapPolyline.js:const viewPropTypes = ViewPropTypes || View.propTypes;
node_modules/react-native-maps/lib/components/MapUrlTile.js:const viewPropTypes = ViewPropTypes || View.propTypes;
node_modules/react-native-maps/lib/components/MapView.js:const viewPropTypes = ViewPropTypes || View.propTypes;
node_modules/react-native-maps/lib/components/MapView.js:MapView.propTypes = propTypes;

iOS & Android release build crashes on application launch.
Hoping the culprit for this is   "react-native-maps": "^0.19.0",

**Comment by intimateo** [comment] 2018-03-01 11:13
after three days fighting with this issue I use the solution of @dhanushuUzumaki 
just Downgrading to RN 0.45.1 and React 16.0.0-alpha.8 solved the issue for me.

**Comment by testshallpasswork** [comment] 2018-03-12 18:17
I followed the steps to transverse dependencies and sub dependencies. I discovered `gl-react` and `react-native-google-places-autocomplete` to be bad eggs in my case. `gl-react` I upgraded to `2.3.1` and I use the other internally so I removed the usage of `React.createClass`. A coworker suggested that maybe we be more strict on warnings via eslint. (https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-deprecated.md)

**Comment by mosleim** [comment] 2018-10-02 06:44
why this closes? have someone have a solution for this problem?

here:
```
  "dependencies": {
    "@babel/runtime": "^7.1.2",
    "native-base": "^2.8.0",
    "react": "16.5.0",
    "react-native": "0.57.1",
    "react-native-charts-wrapper": "^0.4.8",
    "react-navigation": "^2.17.0"
  }
```
still crash on iOS or on Android.

**Comment by patidarandroid** [comment] 2018-11-26 16:55
i am getting same issue when i have create the release build and install in real device please help me

   --------- beginning of crash
2018-11-26 22:23:16.098 28622-28686/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: chat.sutras, PID: 28622
    com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'U.startApp'), stack:
    o@620:43
    a@616:363
    H@346:3196
    <unknown>@343:1119
    n@2:565
    i@2:348
    t@2:210
    <unknown>@13:37
    n@2:565
    i@2:348
    t@2:210
    <unknown>@12:24
    n@2:565
    i@2:278
    t@2:210
    global code@1113:9
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:56)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:40)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
        at android.os.Looper.loop(Looper.java:166)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
        at java.lang.Thread.run(Thread.java:784)

**Comment by quangas** [comment] 2018-12-04 03:49
Same for me.

The error is so cryptic, its difficult to find what the issue is. This is only a problem in Android and not iOS.

```
E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    com.facebook.react.common.JavascriptException: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
    
    This error is located at:
        in RCTView
        in RCTView
        in t, stack:
    Ut@41:25232
    <unknown>@41:68662
    o@41:38127
    beginWork@41:78770
    n@41:104185
    i@41:104526
    o@41:104872
    k@41:109051
    C@41:108594
    v@41:107821
    p@41:107100
    d@41:106788
    t@41:61896
    updateContainer@41:123598
    render@41:69194
    exports@280:730
    run@276:615
    runApplication@276:2046
    value@18:3582
    <unknown>@18:1067
    value@18:3009
    value@18:1039
```

**Comment by shivamsaigupta** [comment] 2019-01-24 14:55
I'm facing the same issue. Please help.

```
01-24 18:11:58.068 20736 20770 E ReactNativeJS: null is not an object (evaluating 't.uid')
01-24 18:11:58.083 20736 20771 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
01-24 18:11:58.083 20736 20771 E AndroidRuntime: Process: com.adourapp, PID: 20736
01-24 18:11:58.083 20736 20771 E AndroidRuntime: com.facebook.react.common.JavascriptException: null is not an object (evaluating 't.uid'), stack:
01-24 18:11:58.083 20736 20771 E AndroidRuntime: <unknown>@834:304
01-24 18:11:58.083 20736 20771 E AndroidRuntime: <unknown>@339:171
01-24 18:11:58.083 20736 20771 E AndroidRuntime: <unknown>@341:1766
01-24 18:11:58.083 20736 20771 E AndroidRuntime: <unknown>@850:3761
01-24 18:11:58.083 20736 20771 E AndroidRuntime: value@46:1362
01-24 18:11:58.083 20736 20771 E AndroidRuntime: <unknown>@796:952
01-24 18:11:58.083 20736 20771 E AndroidRuntime: value@46:1362
01-24 18:11:58.083 20736 20771 E AndroidRuntime: <unknown>@720:523
01-24 18:11:58.083 20736 20771 E AndroidRuntime: value@46:1362
01-24 18:11:58.083 20736 20771 E AndroidRuntime: value@25:3449
01-24 18:11:58.083 20736 20771 E AndroidRuntime: <unknown>@25:960
01-24 18:11:58.083 20736 20771 E AndroidRuntime: value@25:2703
01-24 18:11:58.083 20736 20771 E AndroidRuntime: value@25:932
```
