### ISSUE TITLE
Flipper for React Native 0.62 

### ISSUE THREAD

**Issue by rickhanlonii** [facebook/react-native#27565] opened 2019-12-18 22:09 UTC
# Overview

This issue is to track items to get Flipper enabled for 0.62.

## RNTester Integration

- [x] Android works with Flipper in RNTester
  - This should be working as of #27482
  - May also need https://github.com/facebook/react-native/pull/27631
- [x] iOS works with Flipper in RNTester
  - Requires https://github.com/facebook/react-native/pull/27762

## Default Template Integration

- [x] Android - Can install app from template and use Flipper by default.
  - Requires https://github.com/facebook/react-native/pull/27569
- [x] iOS - Can install app from template and use Flipper by default
  - Requires https://github.com/facebook/react-native/pull/27569

## Upgrade Flipper SDK Version
- [x] Android - Can use latest Flipper version
  - [FBJNI migration](https://github.com/facebook/react-native/pull/27729)
  - [BUCK fix](https://github.com/facebook/react-native/pull/27826)
  - [RNTester Upgrade](https://github.com/facebook/react-native/pull/27833)
  - [Templade upgrade](https://github.com/facebook/react-native/pull/27837) 
  - [Upgrade Flipper version in template](https://github.com/facebook/react-native/pull/27837)
- [X] iOS - Can use latest Flipper version
  - Should be done by #27426

## Upgrading
- [x] Address pod install speed with [openssl](https://github.com/facebook/react-native/issues/27565#issuecomment-567285529) Edit: addressed [here](https://github.com/facebook/react-native/issues/27565#issuecomment-567330597)
- [x] Address swift inclusion
  - See: https://github.com/facebook/react-native/pull/27426
   - Removed in https://github.com/facebook/react-native/commit/8f93dedc6a5653edd2220c65ccb4ff8736ee060c
- [ ] Clean up upgrade requirements
    - Using Flipper with default RN template
    - See https://github.com/facebook/react-native/issues/27565#issuecomment-580950480
- [x] Address React Devtools issue
  - React devtools plugin for Flipper is blank
- [ ] Make sure the upgrade tool works well for this release #27879
- [ ] Figure out use_framworks support

## Documentation

- [ ] Add React Native the Flipper website
- [ ] Add documentation to the website
    -  Adding Flipper to new projects (mention included by default after 0.62)
    -  Adding Flipper to existing projects
- [ ] In [Flipper Docs](https://fbflipper.com/docs/getting-started.html#setup-your-react-native-app)

## Commits to Cherry Pick
- [x] Dec 5 - [fix build failure due to duplicate libc++_shared.so](https://github.com/facebook/react-native/commit/2fd50882b56aa16befd5cfbc3c6b27e53c72474e)
- [x] Dec 6 - [Fix Flipper integration on iOS and update it](https://github.com/facebook/react-native/commit/898b1db6d0efa86a37af6eac46beb32c091d079d)
- [x] Dec 12 - [Edits to flipper pods comments](https://github.com/facebook/react-native/commit/f11b4895d6eac80c0b4be20de19f611747e1d2b6)
- [x] Dec 16 - [Fix RNTester integration with Flipper](https://github.com/facebook/react-native/commit/68bf0e32e70db2ce28cc3c3d9d63f58900d1869d)
- [x] Dec 17 - [Remove NativeRunnableDeprecated](https://github.com/facebook/react-native/commit/973253af8a47d9ebd137f554054e7a95f8ef2e45)
- [x] Jan 14 - [clang-format cpp](https://github.com/facebook/react-native/commit/d5ba113bb2cd839ea38768785e527fbbc9636e41)
- [x] Jan 21 - [Migrate to FBJNI](https://github.com/facebook/react-native/commit/9ad5e72b77013083f925108870ea6b17f4711a1d)
- [x] Jan 21 - [Fix BUCk build](https://github.com/facebook/react-native/commit/a3cb377645f2ccb7632ded73c230a41025d38f6f)
- [x] Jan 28 - [Use new Flipper SDK (android)](https://github.com/facebook/react-native/commit/8259a9d369c310f4c31e50e2ad5157f5c5a8dc30)
- [x] Jan 29 - [Integrate Flipper in RNTester on Android](https://github.com/facebook/react-native/commit/6579d8f5bcd87775227ab9ca6c968ae2e200120c)
- [x] Jan 29 - [Upgrade Flipper version in tempalate](https://github.com/facebook/react-native/commit/939df8a01da09fd18baa4e66e2babd438db0ea8d)
- [x] Jan 30 - [initalizeFlipper should be set in template app by default](https://github.com/facebook/react-native/commit/52cd9cd6fec0866177aa02f7129a8b3d8b2bdbea)
- [x] Feb 3 - [Remove empty swift file](https://github.com/facebook/react-native/commit/8f93dedc6a5653edd2220c65ccb4ff8736ee060c)
- [x] Feb 5 - [Add androidx.swiperefreshlayout to RNTester build.gradle](https://github.com/facebook/react-native/commit/2c89e5150736dbfb2d5f594a6fd483a90fe8685d)
- [ ] Feb 12 - [Integrated Flipper in RNTester iOS](https://github.com/facebook/react-native/commit/cb80e3b599d0a781af8ad2999c4f1b58a11de05f)

**Comment by TheSavior** [comment] 2019-12-19 00:36
I give up. @hramos! 😭

**Comment by rmevans9** [comment] 2019-12-19 01:17
While working on a Flipper plugin it was noted that the inclusion of FlipperKit in the Podfile caused pods to need to install `openssl-ios-bitcode` which required building openssl for all the architectures. As you can imagine this takes a while. In a normal `pod install` the developer will not know what is going on likely as this is what they will see for a long time:

![Screen Shot 2019-12-18 at 8 12 14 PM](https://user-images.githubusercontent.com/14151327/71136389-b6168780-21d2-11ea-9843-135e3936ba5f.png)

If you run `pod install --verbose` you can actually see progress during this process. On my machine it took a good 10+ minutes to complete this install. The good news is once this pod is in your cache future `pod install`s are much quicker. If you would like to experience this first hand you can do the following steps:

1. Run `pod cache clear openssl-ios-bitcode`
2. Run `pod install` (include `--verbose` if you are interested in seeing what it is actually doing) in a ios folder of a RN project with the FlipperKit pods setup

I understand the need for this library but it will be a jarring experience for developers upgrading and also for first time users of react-native. I feel like if we can't avoid it that it is at least worth calling attention to it so users don't cancel the `pod install` part way through and say its broken.

**Comment by TheSavior** [comment] 2019-12-19 01:35
@rmevans9, I added that to the checklist. 👍

**Comment by charpeni** [comment] 2019-12-19 04:45
@rmevans9 thanks for bringing that.

I confirm that bumping the version from 0.23.6 to 0.30.0 solved that issue, we now rely on `OpenSSL-Universal (1.0.2.19)` instead of `openssl-ios-bitcode`. I've just double checked, and `openssl-ios-bitcode` is not in `Podfile.lock`.

**Comment by charpeni** [comment] 2019-12-19 05:12
Looks like I got you, bot!

**Comment by rmevans9** [comment] 2019-12-19 11:17
@charpeni ok perfect! I am glad that issue got solved with the upgrade.

**Comment by safaiyeh** [comment] 2019-12-19 18:23
Submitted a PR to initialize Flipper on Android & iOS based on the context from @axe-fb.

https://github.com/react-native-community/releases/issues/145#issuecomment-567597488

**Comment by birkir** [comment] 2019-12-20 08:58
Have this issue enabling Flipper on android.

```
execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class com.facebook.jni.CppException found in modules classes.jar (com.facebook.fbjni:fbjni:0.0.2) and classes.jar (com.facebook.react:react-native:0.62.0-rc.0)
  Duplicate class com.facebook.jni.CppSystemErrorException found in modules classes.jar (com.facebook.fbjni:fbjni:0.0.2) and classes.jar (com.facebook.react:react-native:0.62.0-rc.0)
  Duplicate class com.facebook.jni.DestructorThread found in modules classes.jar (com.facebook.fbjni:fbjni:0.0.2) and classes.jar (com.facebook.react:react-native:0.62.0-rc.0)
  Duplicate class com.facebook.jni.DestructorThread$1 found in modules classes.jar (com.facebook.fbjni:fbjni:0.0.2) and classes.jar (com.facebook.react:react-native:0.62.0-rc.0)
  Duplicate class com.facebook.jni.DestructorThread$Destructor found in modules classes.jar (com.facebook.fbjni:fbjni:0.0.2) and classes.jar (com.facebook.react:react-native:0.62.0-rc.0)
  Duplicate class com.facebook.jni.DestructorThread$DestructorList found in modules classes.jar (com.facebook.fbjni:fbjni:0.0.2) and classes.jar (com.facebook.react:react-native:0.62.0-rc.0)
  Duplicate class com.facebook.jni.DestructorThread$DestructorStack found in modules classes.jar (com.facebook.fbjni:fbjni:0.0.2) and classes.jar (com.facebook.react:react-native:0.62.0-rc.0)
  Duplicate class com.facebook.jni.DestructorThread$Terminus found in modules classes.jar (com.facebook.fbjni:fbjni:0.0.2) and classes.jar (com.facebook.react:react-native:0.62.0-rc.0)
  Duplicate class com.facebook.jni.HybridClassBase found in modules classes.jar (com.facebook.fbjni:fbjni:0.0.2) and classes.jar (com.facebook.react:react-native:0.62.0-rc.0)
  Duplicate class com.facebook.jni.HybridData found in modules classes.jar (com.facebook.fbjni:fbjni:0.0.2) and classes.jar (com.facebook.react:react-native:0.62.0-rc.0)
  Duplicate class com.facebook.jni.HybridData$Destructor found in modules classes.jar (com.facebook.fbjni:fbjni:0.0.2) and classes.jar (com.facebook.react:react-native:0.62.0-rc.0)
  Duplicate class com.facebook.jni.IteratorHelper found in modules classes.jar (com.facebook.fbjni:fbjni:0.0.2) and classes.jar (com.facebook.react:react-native:0.62.0-rc.0)
  Duplicate class com.facebook.jni.MapIteratorHelper found in modules classes.jar (com.facebook.fbjni:fbjni:0.0.2) and classes.jar (com.facebook.react:react-native:0.62.0-rc.0)
  Duplicate class com.facebook.jni.NativeRunnable found in modules classes.jar (com.facebook.fbjni:fbjni:0.0.2) and classes.jar (com.facebook.react:react-native:0.62.0-rc.0)
  Duplicate class com.facebook.jni.ThreadScopeSupport found in modules classes.jar (com.facebook.fbjni:fbjni:0.0.2) and classes.jar (com.facebook.react:react-native:0.62.0-rc.0)
  Duplicate class com.facebook.jni.UnknownCppException found in modules classes.jar (com.facebook.fbjni:fbjni:0.0.2) and classes.jar (com.facebook.react:react-native:0.62.0-rc.0)
```

if I exclude `com.facebook.fbjni` from either implementation the app compiles but I will have a runtime error of SoLoader not finding jsfbni.so

**Comment by mjmasn** [comment] 2019-12-20 11:32
Hey @rickhanlonii, I enabled Flipper for our React Native 0.61.5 app a few weeks ago. Flipper works fine apart from React Devtools (due to React version, so should be resolved in 0.62)

However, since then any XMLHttpRequest PUT requests seem to be failing with status=0. This is for uploading files to Amazon S3. 

Disabling Flipper resolves the problem. Production builds haven't been affected because Flipper was only enabled for debug builds.

I can't really provide a simple repro as it takes various file picker, aws setup etc. But just wanted to make sure you're aware of the issue. Happy to provide more information if required.

**Comment by rickhanlonii** [comment] 2019-12-20 14:42
@birkir thanks for the info, this is the issue @mdvacca is looking into 👍

@mjmasn thanks for the info, what's the issue with the React DevTools?

**Comment by mjmasn** [comment] 2019-12-20 14:57
@rickhanlonii I think it's just that React Native 0.61.x only supports v3 of devtools. Gives an error in Flipper saying to install react-devtools@^3, which doesn't really help because v4 is built into Flipper.

https://reactjs.org/blog/2019/08/15/new-react-devtools.html#which-versions-of-react-are-supported says that React Native 0.62.x will be supported in devtools v4 (and presumably in Flipper too).

**Comment by safaiyeh** [comment] 2019-12-29 03:09
@rickhanlonii I updated RNTester to include Flipper support.

https://github.com/facebook/react-native/pull/27631

**Comment by rickhanlonii** [comment] 2020-01-10 12:20
@mjmasn were you ever able to track down the HTTP issue?

**Comment by mjmasn** [comment] 2020-01-14 11:42
@rickhanlonii I haven't really looked into it, wondered if it was to do with the file size as there was some issue fixed in Flipper for large **responses** but actually it fails even with a 9kB file request as seen below. Note the 'Stream Closed' response. Maybe the RN NetworkingModule is trying to consume a stream that was already consumed by the Flipper network plugin? That's just a guess, I don't know enough about Android / Java / Flipper to know exactly what's going on.

No errors are logged to adb when this occurs.

```
{
  UNSENT: 0,
  OPENED: 1,
  HEADERS_RECEIVED: 2,
  LOADING: 3,
  DONE: 4,
  readyState: 4,
  status: 0,
  timeout: 900000,
  withCredentials: true,
  upload: {},
  _aborted: false,
  _hasError: true,
  _method: 'PUT',
  _response: 'Stream Closed',
  _url:
    'https://REDACTED.s3.amazonaws.com/REDACTED',
  _timedOut: false,
  _trackingName: 'unknown',
  _incrementalEvents: false,
  responseHeaders: undefined,
  _requestId: null,
  _cachedResponse: undefined,
  _headers: { 'content-type': 'image/jpeg', 'content-length': '9933' },
  _responseType: '',
  _sent: true,
  _lowerCaseResponseHeaders: {},
  _subscriptions: []
};
```

**Comment by rickhanlonii** [comment] 2020-01-29 10:54
Added testing this upgrade tool per #27879

**Comment by alloy** [comment] 2020-01-31 22:49
https://github.com/facebook/react-native/pull/27922 addresses #27426

**Comment by alloy** [comment] 2020-01-31 23:09
Flipper is looking great and I can’t wait to use it in earnest; great job, y’all! ✨👏 

I took it for a test-drive and have a few pieces of feedback to perhaps make the experience a little smoother. (I can send PRs for any of these!)

* The template’s `AppDelegate.m` file could have a commented line that calls the Flipper initialisation method.

* A new reference to an old symbol is being introduced in the user’s code-base `FB_SONARKIT_ENABLED`. Might be a little more self-documenting to rename that to e.g. `FB_FLIPPER_ENABLED` before the stable release?

* Rather than adding `FB_SONARKIT_ENABLED` to `OTHER_CFLAGS`, we should add it to `GCC_PREPROCESSOR_DEFINITIONS`, which is specifically meant to define macros and will ensure that the user’s prefix header doesn’t need to be rebuild when the user changes the setting.

* Rather than hardcoding the preprocessor macro in the project from the Podfile’s `post_install` hook, how about the user specifies it as a CLI option, e.g. `react-native run-ios --enableFlipper`?

  This will make it just as easy for the user to _disable_ the feature as it is the enable it–tucking it away in the Podfile makes this a little opaque to me and doesn’t provide an easy way to revert the setting.

  People can of course, always hardcode the setting themselves, if they so wish–perhaps the CLI option could document that it adds `FB_SONARKIT_ENABLED=1` to `GCC_PREPROCESSOR_DEFINITIONS` 🤔 

* The way the current Podfile `post_install` hook tries to enable Flipper in the user’s project will fail on the very first `pod install`, e.g. after running `react-native init`. (This is also documented in [the Flipper docs](https://fbflipper.com/docs/getting-started.html#ios).)

  The reason this happens is because the current `post_install` hook is prematurely saving the user’s project on its own, which is simply going to be overwritten when `pod install` finishes (with the data it read before the `post_install` hook tried to alter it).

  _NOTE_: Before sending a PR for this, I wanted to know if you see any merit in removing the `post_install` hook entirely in favour of a CLI option.

**Comment by rickhanlonii** [comment] 2020-02-05 10:44
@alloy that all seems to make sense to me and seems like a safer option for upgrades, want to send the PRs?

**Comment by rickhanlonii** [comment] 2020-02-05 15:10
Ok I ran some testing and:

## RNTester
- Android works ✅
- iOS does not work (PR open) 🚫

## Default template
- Android works ✅
- iOS does not work (not sure why) 🚫

**Comment by alloy** [comment] 2020-02-05 16:25
As [mentioned above](https://github.com/facebook/react-native/issues/27565#issuecomment-567285529) a change was made in Flipper’s dependencies to [switch from the `openssl-ios-bitcode` pod to `OpenSSL-Universal`](https://github.com/facebook/flipper/pull/577/files#diff-0ac8d6a51021e44ebd8314e22e89b197R14) in order to reduce build times. However, the `OpenSSL-Universal` pod does not include a bitcode slice, which both Apple’s and RN’s application templates enable by default for device builds (simulator builds are unaffected).

This means that, with the current RN template, users will **not** be able to build for device _and_ have Flipper integrated at the same time.

Perhaps possible, but, as of yet, untested solution:
* Disable bitcode in `Debug` configurations in the RN template. (Unsure if there any cons to this.)
* Use a different existing pod that does have prebuilt binaries for bitcode. (Unsure if one exists.)
* Revert to building from source. (While this does take long initially, it does bring us _closer_ to a setup where Flipper will be able to build with both static and dynamic libs without the need to monkey-patch CocoaPods.)

**Comment by priteshrnandgaonkar** [comment] 2020-02-06 11:43
> Disable bitcode in Debug configurations in the RN template. (Unsure if there any cons to this.)

I think we should try this approach, as Flipper is enabled only for Debug builds.

> Use a different existing pod that does have prebuilt binaries for bitcode. (Unsure if one exists.)

I had looked at it last time, but didn't find any such prebuilt binaries.

> Revert to building from source. (While this does take long initially, it does bring us closer to a setup where Flipper will be able to build with both static and dynamic libs without the need to monkey-patch CocoaPods.)

Not entirely sure about this approach, as the build times are long at the start, and due to which we have also faced some CI test's time outs and user reports regarding the long build times.

**Comment by priteshrnandgaonkar** [comment] 2020-02-06 12:36
@alloy Sample, SampleSwift and Tutorial apps in Flipper repo are bitcode enabled and they compile. OpenSSL-Universal seems to be bitcode enabled, see [this](https://github.com/krzyzanowskim/OpenSSL/blob/9e14bcdd27ae2323742cbdb8c221ae48ad1b19ac/build.sh#L77)

**Comment by alloy** [comment] 2020-02-06 19:50
Well blimey, that’s great! I’ll double-check my build machine tomorrow to see why `ld` was complaining about this.

**Comment by alloy** [comment] 2020-02-07 13:24
Alas, seems not the case:

```
ld: '/Users/eloy/tmp/TestWithAllChanges/ios/Pods/OpenSSL-Universal/ios/lib/libcrypto.a(bio_lib.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
```

We can see that the slices have no bitcode section:

```bash
otool -l -arch arm64 ios/Pods/OpenSSL-Universal/ios/lib/libssl.a  | grep LLVM
otool -l -arch arm64 ios/Pods/OpenSSL-Universal/ios/lib/libcrypto.a | grep LLVM
```

…and indeed, looking at the last commits of the OpenSSL-Universal pod, bitcode has been disabled:

```bash
$ git log --pretty=oneline
17794e6faf5928f42264a7e3ef093ea7c08c5a15 (HEAD -> master, tag: 1.0.219, tag: 1.0.2.19, origin/master, origin/HEAD) Rebuild without bitcode
7ca5804216a079ce057d01502cc224c2a34642ea ENABLE_BITCODE = NO for iOS target
896c0ae5d5d10e93dd93789125ee12860df1ffb9 Add missing include
52ef14139ab791650ddad38ece782285ef56d722 Update FUNDING.yml
9e14bcdd27ae2323742cbdb8c221ae48ad1b19ac Merge pull request #74 from ilammy/disable-bitcode
5477325f53df56b92f672ea7c2399aed46c5e4fc Disable LLVM bitcode support (again)
```

----

On the flip side, I did experiment with changing the application to build without bitcode in `Debug` and that did successfully build and run. (The Flipper client applications finds the app running on my device, although it doesn’t seem to connect or detect any plugins, is that known?)

In any case, it seems like for now the best solution would be to indeed disabled bitcode in `Debug` builds by default in the RN application template.

**Comment by alloy** [comment] 2020-02-12 22:46
So regarding the need to use a preprocessor define to compile Flipper into the app, I did create https://github.com/react-native-community/cli/pull/958 and [TODO().

However, having thoroughly tested this manually, I came around to how this should work. It feels like we don’t need to take on this extra fragmented complexity; instead we just always define `FB_SONARKIT_ENABLED` in the `Debug` configuration and only wrap the `AppDelegate.m` code in a `#if DEBUG`.

People can always just remove the code from `AppDelegate.m` entirely, like they can the dependencies from their `Podfile`.

Put differently; imo we can just always enable Flipper by default in the template and keep things simple.

**Comment by alloy** [comment] 2020-02-13 01:14
Alright, https://github.com/facebook/react-native/pull/28044 should address all my open feedback.

**Comment by todorone** [comment] 2020-03-03 04:28
Is Flipper can be already consumed in latest 0.62 RC? Super excited about it, thanks a lot to all contributors for working on integration.

**Comment by alloy** [comment] 2020-03-03 12:31
@todorone Yes, it’s available in the 0.62.0 RCs; please do try!

**Comment by younes200** [comment] 2020-04-05 23:06
Hi,
Just to mention that `ENABLE_BITCODE` must be disable on debug otherwise the build failed, due to missing OpenSSL-Universal  bitcode.

```
  - Flipper-Folly (2.1.1):
    - boost-for-react-native
    - CocoaLibEvent (~> 1.0)
    - Flipper-DoubleConversion
    - Flipper-Glog
    - OpenSSL-Universal (= 1.0.2.19)
```

**Comment by alloy** [comment] 2020-04-06 10:22
Going to close this, as this ship has set sail! :shipit:

**Closed by alloy** 2020-04-06 10:22 UTC
Labels: DX, Type: Discussion, p: Facebook

**Comment by AndrewMorsillo** [comment] 2020-04-13 13:45
@alloy react-devtools is completely broken in RN 0.62 both standalone and in flipper. It never connects!

**Comment by mweststrate** [comment] 2020-04-13 13:50
@AndrewMorsillo please don't respond to closed issue as very little people will see them, and provide relevant reproduction information. "Doesn't work" is unactionable.

**Comment by ezranbayantemur** [comment] 2020-05-04 19:15
After updating 0.61.5 to 0.62.2 ENABLE_BITCODE error drives me crazy. Not any problem while creating fresh project but it happens on upgrading to 0.62.2.

Trying to debug on real device it gives error message on below.

`ld: '... project path .../ios/Pods/OpenSSL-Universal/ios/lib/libcrypto.a(bio_lib.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64`

Any idea about it?

**Comment by mweststrate** [comment] 2020-05-04 19:51
@ezranbayantemur please don't respond to closed issue as only few people will see them, and it pings a people that don't have your specific issue needlessly. So please open a new issue instead :)

**Comment by ezranbayantemur** [comment] 2020-05-04 19:58
> @ezranbayantemur please don't respond to closed issue as only few people will see them, and it pings a people that don't have your specific issue needlessly. So please open a new issue instead :)

Oh my bad, I saw mentioned comments about it and didn't recognize it was closed.
Sorry for bother people 👍

**Comment by xgqfrms** [comment] 2020-06-30 14:26
# need help

https://github.com/facebook/react-native/issues/29251

**Comment by hongmaoxiao** [comment] 2020-09-15 17:53
> # need help
> ```shell
> $ pod install --verbose
> ```
> 
> #29251
> 
> > stop, after installing here
> 
> ![image](https://user-images.githubusercontent.com/7291672/86138970-bdbfcd00-bb21-11ea-91cb-5c9874777803.png)
> 
> ```shell
> $ pod install
> ```
> 
> ![](https://user-images.githubusercontent.com/7291672/86123502-32880c80-bb0c-11ea-80c3-043901031d02.png)

same here! anyone knows how to solve it?
