### ISSUE TITLE
Possible RN 0.61 Android view regressions

### ISSUE THREAD

**Issue by lafiosca** [facebook/react-native#26574] opened 2019-09-25 16:26 UTC
After upgrading from 0.60.5 to 0.61.1, I'm seeing some funky visual behaviors with Android which might be directly related to #26289, but I don't know enough about them to say for sure. For example, look at the difference in the buttons from `react-native-paper@2.16.0` in the first screenshot below. Another example is my swipe deck component based on Animated.View. In Android now the swipe cards which have solid white backgrounds are somehow merging visually (second screenshot below). That is to say, all text and icon elements of both the top card and the underlying card are visible simultaneously.

Note: all screenshots are from a Samsung Galaxy S7 Edge. These behaviors did NOT occur for me in the Android emulator.

React Native version:
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 19.70 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.4 - ~/.nvm/versions/node/v8.11.4/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v8.11.4/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.1 => 0.61.1
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native: 0.61.0

## Steps To Reproduce

1. Connect an Android device (Does it have to be a Samsung Galaxy S7 Edge? I don't know)
2. `react-native init oldbutton --version 0.60.6; cd oldbutton`
3. `yarn add react-native-vector-icons react-native-paper`
4. Edit App.js to add a button somewhere with this code:
```
import { Button } from 'react-native-paper';
<Button dark color="#aaaaff" mode="contained" onPress={() => {}}>Test Button</Button>
```
5. `react-native run-android` and observe the button's visual behavior before/while touching
6. `cd ..; react-native init newbutton; cd newbutton`
7. Repeat steps 3-5

Describe what you expected to happen:

I expected the views not to change so significantly between versions. See the third screenshot below. I used a lighter color on the button so you can see that even unpressed, the button has changed visually (odd dark outline), but the difference is more significant while pressing.

Snack, code example, screenshot, or link to a repository:

![image](https://user-images.githubusercontent.com/9442662/65614865-608d5e80-df86-11e9-8543-036cb8aae034.png)

![image](https://user-images.githubusercontent.com/9442662/65615565-8ff09b00-df87-11e9-8aee-123d1375b707.png)

![image](https://user-images.githubusercontent.com/9442662/65620181-60de2780-df8f-11e9-95c2-e1624059bbfa.png)

Note: all screenshots are from a Samsung Galaxy S7 Edge. These behaviors did NOT occur for me in the Android emulator.

**Comment by mikebouwmans** [comment] 2019-09-25 16:31
Seems to be related to #26544

**Comment by mjmasn** [comment] 2019-09-25 16:38
I think https://github.com/facebook/react-native/issues/26544 is a duplicate of https://github.com/facebook/react-native/issues/26289 (or at least strongly related), and this would appear to be too. The only one I'm not sure about is the card as it doesn't look like that has any elevation shadow to begin with.

@lafiosca is it fixed by adding `TouchableNativeFeedback.SelectableBackgroundBorderless = () => null;` to index.js?

**Comment by lafiosca** [comment] 2019-09-25 16:39
@mikebouwmans Yes, at least the button examples above look likely related to that, to me. Apologies if my issue is redundant.

Although I wonder my other visual problem with the swipe cards becoming transparent is directly related. If it's about elevation, perhaps so? Those cards were using `zIndex` and did not use the `elevation` style property directly. I don't know that I have the time right now to try to boil down a minimal example unfortunately.

**Comment by lafiosca** [comment] 2019-09-25 16:57
@mjmasn It seems that workaround does not fix the buttons or cards in my app, nor the button in the reproduction steps app. 😔

**Comment by darknblack** [comment] 2019-09-25 17:10
> @mjmasn It seems that workaround does not fix the buttons or cards in my app, nor the button in the reproduction steps app. 😔

Have you tried removing the border-radius?

**Comment by TheSavior** [comment] 2019-09-25 17:15
It would be helpful if you are able to get a repro that doesn't require react-native-paper

**Comment by mjmasn** [comment] 2019-09-25 17:30
@lafiosca how about TouchableNativeFeedback.Ripple = () => null;

**Comment by lafiosca** [comment] 2019-09-25 17:30
@TheSavior I am currently trying to work up a minimal example of the overlapping views problem. I'll update here when I have something.

**Comment by lafiosca** [comment] 2019-09-25 18:28
Something making this a lot more difficult and time-consuming: I'm seeing inconsistent rendering results on the Android device after doing a manual shake&reload (even with Fast Refresh disabled). That is to say: I'll have a piece of code that seems to be rendering wrong, but then if I kill the app and run `react-native run-android` again, it becomes fine.

To phrase it another way: working from a non-minimal bad sample, pruning out bits of code and doing a manual reload may show the same bad behavior even though killing and restarting does not. This makes it confusing and tough to track down the minimal sample quickly.

**Comment by lafiosca** [comment] 2019-09-25 19:55
After some extensive testing to try to reproduce the overlapping swipe card views problem, I have made some strange findings. As I mentioned in my previous comment, "breaking" the view breaks it for all subsequent reloads, unless I kill the app and restart from scratch. I determined that the thing that "breaks" the view is by having the `react-native-paper` button render on the screen, even though the button is not involved in the card view!!

The code is here: https://gist.github.com/lafiosca/dda9096adbc9ab3078c83d1d3bff112d

Creating a new 0.61.1 app and copying those files into it, when I run on the Android device (Galaxy S7 Edge) I see the overlapping text on the cards:

![Screenshot_20190925-154031](https://user-images.githubusercontent.com/9442662/65634181-af99ba80-dfab-11e9-9288-f994bdaf5647.png)

If I comment out line 23 of App.js (the Button) and kill/restart (NOT just reload) the app, the cards look fine:

![Screenshot_20190925-154130](https://user-images.githubusercontent.com/9442662/65634230-cb9d5c00-dfab-11e9-91b2-536158dab26c.png)

Alternatively, following @mjmasn's suggestion and uncommenting line 6 of index.js to replace `TouchableNativeFeedback.Ripple` seems to clear up the issue (although it means the button no longer has ripple feedback):

![Screenshot_20190925-154250](https://user-images.githubusercontent.com/9442662/65634305-f091cf00-dfab-11e9-9449-59273e13d303.png)

I've tried the Ripple workaround in my original app, and it seems to clear up the initial problems I noticed there as well. This may be a solid enough workaround for me to proceed using 0.61.1.

I am curious to know what in `react-native-paper` could be causing this problem that impacts other views, and I would love to understand why that also permanently messes up the views even through reloads of "good" code. But I do not have the time this afternoon to delve any deeper into this.

**Comment by lafiosca** [comment] 2019-09-25 20:05
callstack/react-native-paper#1341 seems related, but it raises a question in my mind: when there's a change like this, who is responsible for addressing it?

**Comment by TheSavior** [comment] 2019-09-25 21:05
It depends what the problem is. If react-native core had a breaking change to behavior that we didn't expect to have this result then it should probably be fixed in core because it is more widespread than just one library. If it is caused by something fishy being done in react-native-paper, then I'd expect it to be fixed in react-native-paper. 

If you can get a repro that doesn't require paper, or able to track down a commit in the core that caused this, that would help it get addressed in core.

**Comment by greis** [comment] 2019-09-26 00:19
It could be happening only with specific versions of android. In my case it's renders fine on API 28 but on API 23 it renders with this issue.

@lafiosca it looks like your emulator is running API 28. Try to boot another emulator running API 23

**Comment by lafiosca** [comment] 2019-09-26 15:20
Excellent call, @greis. Running it on an API 23 emulator reproduced the issue. Thanks.

**Comment by kdawgwilk** [comment] 2019-09-26 19:07
I am also seeing these shadow/zIndex issues on emulator running API 27

**Comment by grabbou** [comment] 2019-09-26 21:19
I wonder if this issue isn't a duplicate of https://github.com/facebook/react-native/issues/26544, according to the screenshots. 

Would be awesome if OP could confirm.

Also, @ferranp and @satya164, do you think this could be related to any potential business logic that lives inside Paper?

**Comment by lafiosca** [comment] 2019-09-27 02:44
I think it’s very likely that all of the issues referenced above are duplicates. I find it bizarre that even just rendering the component from react-native-paper also seems to “contaminate” my other views, but I am guessing that part is not the fault of react-native. I don’t have the time and knowledge to confirm for certain, but if you’d like to close this as a duplicate I’d understand.

**Comment by ahce** [comment] 2019-09-27 02:49
Animated component also broken.
I think this should be fixed asap.

**Comment by gdoudeng** [comment] 2019-09-27 03:51
I am facing this problem and hope to solve it as soon as possible.

**Comment by mjmasn** [comment] 2019-09-27 08:17
@grabbou it's definitely a `react-native` issue linked to `TouchableNativeFeedback.SelectableBackgroundBorderless()` and `TouchableNativeFeedback.Ripple()` with borderless param set to true. 

We don't use `react-native-paper`. 

I'll upload my repro repos in a sec.

**Comment by mjmasn** [comment] 2019-09-27 08:29
Reproduction:
https://github.com/mjmasn/ElevationIssue60 (working)
https://github.com/mjmasn/ElevationIssue61 (broken)

**Comment by iamacup** [comment] 2019-09-27 15:26
I am also seeing very strange visual artifacts on certain components on Android after 0.61.x

I am also experiencing massive levels of inconsistency between reloads and / or fast refreshes as @lafiosca identifies above.

All of my probems only exist when there is a **border radius** applied to something - two examples:

### Previously working border radius on a view over an icon


```
{
  backgroundColor: 'white',
  borderColor: primary,
  borderWidth: 1, 
}
```
![image](https://user-images.githubusercontent.com/12894620/65781316-51074480-e143-11e9-9c1f-7652e4216d73.png)


```
{
  backgroundColor: 'white',
  borderColor: primary,
  borderWidth: 1, 
  borderRadius: 0,
}
```
![image](https://user-images.githubusercontent.com/12894620/65781305-4d73bd80-e143-11e9-9cc1-08d79482f2ff.png)



### Previously working border radius on a set of navigation tabs


```
{
  backgroundColor: white,
  borderTopLeftRadius: 15,
  borderTopRightRadius: 15,
}
```
![image](https://user-images.githubusercontent.com/12894620/65781017-cf171b80-e142-11e9-8eb4-9cf43ed3655c.png)


```
{
  backgroundColor: white,
}
```
![image](https://user-images.githubusercontent.com/12894620/65780971-bb6bb500-e142-11e9-9fab-6f322e19470c.png)

I will try and pull this behavior out into an example repo over the weekend.

**Comment by tianjyan** [comment] 2019-09-29 01:31
@lafiosca  I think I have the same issue with your second screenshot. The backgroundColor can not be rendered correctly. See below:

On React Native 0.61
![Screenshot_2019-09-29-09-19-33-312_app cybrook teamlink](https://user-images.githubusercontent.com/4630470/65824402-026cbe00-e29b-11e9-88ce-2edf53b38d03.png)

On React Native 0.60
![Screenshot_2019-09-29-09-19-58-649_app cybrook teamlink](https://user-images.githubusercontent.com/4630470/65824406-229c7d00-e29b-11e9-8935-61ab82c0e537.png)

I tried to remove the `Animated.View` but backgroundColor is still not working. I am trying to give a example to reproduce it.

**Comment by jeremy-deutsch** [comment] 2019-09-30 17:37
Just want to note that this issue isn't entirely new to RN 0.61 - I don't have a repro immediately on hand, but I've noticed in previous versions of RN that if an element has both `borderRadius` and `backgroundColor`, and is very, very large, the `backgroundColor` disappears.

**Comment by mjmasn** [comment] 2019-09-30 22:55
@jeremy-deutsch that sounds like https://github.com/facebook/react-native/issues/15826 

No idea if it's actually related to these new issues or just a similar symptom.

**Comment by jeremy-deutsch** [comment] 2019-09-30 23:04
> @jeremy-deutsch that sounds like #15826
> 
> No idea if it's actually related to these new issues or just a similar symptom.

Ah yeah, didn't see that issue somehow. The connection might still be worth looking into, though.

**Comment by jstheoriginal** [comment] 2019-09-30 23:20
FWIW my app on latest version of 0.60 didn’t have these issues at all.

**Comment by tianjyan** [comment] 2019-09-30 23:22
In my case, the height is not so large, so I think maybe we have different issues here. @mjmasn

**Comment by radko93** [comment] 2019-10-01 08:19
duplicate of #26544. Please continue discussion there. 
@grabbou @empyrical

**Closed by radko93** 2019-10-01 08:19 UTC
Labels: Bug, Impact: Regression, Platform: Android
