### ISSUE TITLE
Can't run app

### ISSUE THREAD

**Issue by leoaccorsi** [facebook/react-native#15797] opened 2017-09-04 20:48 UTC
`react-native: 0.46.4`

I'm getting this error's only on android:

`FATAL EXCEPTION: mqt_native_modules
                  Process: br.com.MYPACKAGE, PID: 2964
                  com.facebook.react.common.JavascriptException: No dimension set for key window`

I've searched that it happens using Router Flux, but i don't use it.

Any help?

**Comment by iegik** [comment] 2017-09-05 07:04
Duplicate of https://github.com/facebook/react-native/issues/13758

**Comment by chirag04** [comment] 2017-09-05 13:32
@facebook-github-bot duplicate #13758

**Closed by chirag04** 2017-09-05 13:32 UTC
Labels: Ran Commands
