### ISSUE TITLE
Android build of clean sample project fails during dependency resolution

### ISSUE THREAD

**Issue by cnixbtc** [facebook/react-native#38056] opened 2023-06-25 14:56 UTC
### Description

When I setup a fresh project as per the [docs](https://reactnative.dev/docs/environment-setup?platform=android) using:

```
npx react-native@latest init RNTestApp
```

And then try to run it using:

```
 npx react-native run-android
```

I get this error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not determine the dependencies of null.
   > Cannot query the value of this provider because it has no value available.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

### React Native Version

0.72.0

### Output of `npx react-native info`

```
info Fetching system and libraries information...
System:
  OS: macOS 13.2
  CPU: (10) arm64 Apple M1 Pro
  Memory: 72.66 MB / 32.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 18.12.1
    path: ~/.nvm/versions/node/v18.12.1/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v18.12.1/bin/yarn
  npm:
    version: 8.19.2
    path: ~/.nvm/versions/node/v18.12.1/bin/npm
  Watchman:
    version: 2022.10.24.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/daniel/.rvm/gems/ruby-3.0.0/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    API Levels:
      - "26"
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
    Build Tools:
      - 28.0.3
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
    System Images:
      - android-31 | Google APIs ARM 64 v8a
      - android-33 | Google APIs ARM 64 v8a
    Android NDK: 23.1.7779620
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.1
    path: /usr/bin/javac
  Ruby:
    version: 3.0.0
    path: /Users/daniel/.rvm/rubies/ruby-3.0.0/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.0
    wanted: 0.72.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

- `npx react-native@latest init RNTestApp`
- `cd RNTestApp`
- ` npx react-native run-android`

### Snack, code example, screenshot, or link to a repository

Above reproducible is available at [cnixbtc/RNTestApp](https://github.com/cnixbtc/RNTestApp).

**Comment by cortinico** [comment] 2023-06-26 12:13
> ### Steps to reproduce
> * `npx react-native@latest init RNTestApp`
> * `cd RNTestApp`
> * ` npx react-native run-android`

I'm sorry but I cannot reproduce this issue.
Is this happening for every React Native version you try?

**Comment by cnixbtc** [comment] 2023-06-26 15:41
Hi @cortinico, thanks for the quick reply. Let me double check with other versions of React Native. I'll also give it a try on a second machine. Will report back.

**Comment by kelset** [comment] 2023-06-27 09:32
maybe it's because your Java version is 17 and not 11?

**Comment by cortinico** [comment] 2023-06-27 09:59
@cnixbtc yes please try to build with Java 11 and report back. I'm not aware of any incompatibilities between Java 17 and React Native 0.72, but this could be one.

**Comment by cnixbtc** [comment] 2023-06-28 09:12
> @cnixbtc yes please try to build with Java 11 and report back. I'm not aware of any incompatibilities between Java 17 and React Native 0.72, but this could be one.

will retry later this week and report back.

**Comment by mattg95** [comment] 2023-07-05 09:09
I'm having the same problem with Java 17 and React Native 0.72. I downgraded to Java 11, but got the same error.

**Comment by hanarotg** [comment] 2023-07-07 12:17
Could you share your error messages created while building YOUR_PROJECT/android with android studio?

**Comment by aswin-s** [comment] 2023-07-09 04:22
Facing the same issue here.

If I use Java 11, I'm getting below error

```bash
* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin 'com.android.internal.application'.
   > Android Gradle plugin requires Java 17 to run. You are currently using Java 11.
      Your current JDK is located in /opt/homebrew/Cellar/openjdk@11/11.0.19/libexec/openjdk.jdk/Contents/Home
      You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.
```

And if I go with Java 11 then it results in 

```bash
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':react-native:packages:react-native:ReactAndroid:bundleLibCompileToJarDebug'.
> Could not create task ':react-native:packages:react-native:ReactAndroid:compileDebugJavaWithJavac'.
   > Failed to calculate the value of task ':react-native:packages:react-native:ReactAndroid:compileDebugJavaWithJavac' property 'javaCompiler'.
      > No matching toolchains found for requested specification: {languageVersion=11, vendor=any, implementation=vendor-specific}.
         > No locally installed toolchains match (see https://docs.gradle.org/8.0.1/userguide/toolchains.html#sec:auto_detection) and toolchain download repositories have not been configured (see https://docs.gradle.org/8.0.1/userguide/toolchains.html#sub:download_repositories).

```

**Comment by cortinico** [comment] 2023-07-10 10:57
Hey @cnixbtc is your problem solved?

**Comment by leolo784** [comment] 2023-07-20 09:40
I am having the same error with Java 11 & react native 0.72.3
```
System:
  OS: macOS 12.2.1
  CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
  Memory: 336.00 MB / 16.00 GB
  Shell:
    version: "5.8"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.16.0
    path: ~/.nvm/versions/node/v18.16.0/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 9.5.1
    path: ~/.nvm/versions/node/v18.16.0/bin/npm
  Watchman:
    version: 2023.07.10.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.11.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 21.4
      - iOS 15.5
      - macOS 12.3
      - tvOS 15.4
      - watchOS 8.5
  Android SDK:
    API Levels:
      - "28"
      - "29"
      - "31"
      - "33"
    Build Tools:
      - 28.0.3
      - 29.0.2
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
    System Images:
      - android-33 | Google APIs Intel x86_64 Atom
    Android NDK: Not Found
IDEs:
  Android Studio: 2020.3 AI-203.7717.56.2031.7583922
  Xcode:
    version: 13.4.1/13F100
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.20
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /Users/lohungwai/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

**Comment by cortinico** [comment] 2023-07-20 10:49
Closing as @cnixbtc is unresponsive. If you folks have similar problem, please open a new issue

**Closed by cortinico** 2023-07-20 10:49 UTC
Labels: Platform: Android, Needs: Author Feedback

**Comment by JAIRAJ28** [comment] 2023-08-20 08:12
System:
  OS: Windows 10 10.0.22621
  CPU: "(16) x64 AMD Ryzen 7 4800H with Radeon Graphics         "
  Memory: 5.13 GB / 15.42 GB
Binaries:
  Node:
    version: 16.16.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 8.11.0
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
IDEs:
  Android Studio: AI-223.8836.35.2231.10406996
  Visual Studio: Not Found
Languages:
  Java: 11.0.20
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
  
  I have installed the sdk and have set the environment , but then also it shows sdk is not installed? Can you help me with this

**Comment by hihelper** [comment] 2023-10-12 23:59
I have a problem... 

I try to run it using:

yarn android   

I get this error:

![image](https://github.com/facebook/react-native/assets/49802184/66412682-2d68-453d-9a8e-610d66b6b1b2)

`PS C:\Windows\System32\aaa\AwesomeProject> yarn android
yarn run v1.22.19
$ react-native run-android
info JS server already running.
info Installing the app...
5 actionable tasks: 5 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 


FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not determine the dependencies of null.
   > Cannot query the value of this provider because it has no value available.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
error Failed to install the app.
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Windows\System32\aaa\AwesomeProject> `

![image](https://github.com/facebook/react-native/assets/49802184/e2553eff-fee6-411f-9efc-5e0968c72dd9)

![image](https://github.com/facebook/react-native/assets/49802184/29a7ffa3-012b-477c-a63a-1aae869e5e0d)

**Comment by yellowberard** [comment] 2024-02-12 20:12
Same it is one issue after another but I am not able to solve this one
