### ISSUE TITLE
[Android] Navigator transitions broken on 0.13

### ISSUE THREAD

**Issue by satya164** [facebook/react-native#3669] opened 2015-10-25 15:59 UTC
So, I upgraded my RN version in `package.json` and `build.gradle` and found that Navigator transitions are broken. I tried adding a `configureScene` property with no success.

![navigator-example](https://cloud.githubusercontent.com/assets/1174278/10716441/619bdb88-7b5f-11e5-930c-ed7847e31ffc.gif)

**Comment by Deadlysmile** [comment] 2015-10-26 09:27
same issue. All configs Navigator.SceneConfigs with translate doesn't work, only this strange fade effect like in satya164 case. 
FadeAndroid scene changes this ugly fade to little more better...

**Comment by mangogogos** [comment] 2015-10-26 23:44
+1

**Comment by pagrawl3** [comment] 2015-10-27 04:43
same issue here as well, none of the slide transitions work, but the fade transitions work without a problem.

**Comment by astreet** [comment] 2015-10-27 17:13
Thanks for the report and +1's everyone, @ericvicenti can you take a look?

**Comment by JonnyBGod** [comment] 2015-10-30 02:10
+1

**Comment by satya164** [comment] 2015-11-02 21:54
Any updates on this?

**Comment by ericvicenti** [comment] 2015-11-02 22:28
I haven't seen any changes to Navigator that would cause this, and there is no platform-specific code that would cause breakage only on Android.

To perform animations, Navigator calls setNativeProps on views within a requestAnimationFrame timer.

Maybe somebody could try bisecting to identify the breakage? I don't have bandwidth to figure this out in the next few weeks.

**Comment by mbrochh** [comment] 2015-11-03 01:00
I simply created the AwesomeProject tutorial and then added a Navigator to it and used the FloatFromRight transition. It works on iOS but it does not work on Android. The only transition that seems to work on Android is FadeAndroid, but that one is so subtle, it's hardly noticeable.

**Comment by davidstubbs** [comment] 2015-11-03 15:00
I'm not entirely sure how it was broken, but the reason most transitions don't work is that they're using the wrong native prop.

`buildStyleInterpolator` creates a style with the `transformMatrix` property. Android expects the decomposed matrix in `decomposedMatrix`.

I hacked a change in Navigator.js _transitionSceneStyle which "fixes" the transitions (as in they work afterwards, but I'm sure this code change isn't really the one wanted):
```javascript
    ...
    var didChange = useFn(styleToUse, directionAdjustedProgress);
    //
    if (styleToUse.transformMatrix)
      styleToUse = {...styleToUse, decomposedMatrix: MatrixMath.decomposeMatrix(styleToUse.transformMatrix)}
    //
    if (didChange) {
    ...
```

This is my first look at any of this code, so I'm very unsure how to go about fixing this for real.
Any pointers?

**Comment by ericvicenti** [comment] 2015-11-03 17:21
@astreet, have there been any recent changes to transform matrices? There seems to be an inconsistency with Android and iOS

**Comment by davidstubbs** [comment] 2015-11-03 17:31
So a bit more research and...

The Android version relies on the `scaleX`/`translateY`/etc properties to get the transition.

A bunch of commits seemed to break that.

The problem is basically fixed already in https://github.com/facebook/react-native/commit/0ed3048e39c245f005b31277947606fa10f538da
I applied that diff to my 0.13 install and it fixed the issue.

So this should be fixed in 0.14 already as long as all SceneConfigs use interpolators with fallbacks for transformTranslate.
There seems to be a lot of transform related props changes going on, especially with android, so I'm backing away slowly...

**Comment by astreet** [comment] 2015-11-03 19:00
@kmagiera Were matrix transforms broken for a while in Android? I.e. possibly broken in the 0.13 release?

**Comment by satya164** [comment] 2015-11-05 13:21
This seems to be (kinda) fixed in master. Here's what happens on master,

![2015-11-05 18_50_30](https://cloud.githubusercontent.com/assets/1174278/10969407/2b34aede-83ee-11e5-8a21-8519cd7b07a6.gif)

Notice the animation when I go back.

**Comment by sowdri** [comment] 2015-11-06 00:08
The animation while going back kind of hangs for me as well while navigating back. Works fine in IOS though.

**Comment by qbig** [comment] 2015-11-06 16:06
same here. the "back animation" is very choppy

**Comment by kmagiera** [comment] 2015-11-09 07:47
@dgladkov's patch #3954 is fixing this issue - merging it now and closing this. Thanks all for reporting and special thanks to @dgladkov for investigating and fixing the problem

**Closed by kmagiera** 2015-11-09 07:47 UTC
Labels: Android, Help Wanted, JS
