### ISSUE TITLE
Dynamic import path from server or Json

### ISSUE THREAD

**Issue by examineyou65** [facebook/react-native#24991] opened 2019-05-22 09:40 UTC
I have a JSON file which contains the path for different workspace. Each workspace js contains some js code which is used for supply event to the particular workspace. I need to load js dynamically when the workspace is load. But in React native I couldn't import dynamically. While bundle load itself it throws an error.

import("${path}").then(()=>{});

**Comment by satya164** [comment] 2019-05-30 17:05
Dynamic strings are not supported in RN. All assets need to be bundled in the app so they can be loaded on user's device. This means they need to be known statically. Closing since this is the expected behaviour.

**Closed by satya164** 2019-05-30 17:05 UTC
Labels: Bug, Ran Commands, Resolution: Needs More Information
