### ISSUE TITLE
Fresh project does not work on Android with a Mac M1

### ISSUE THREAD

**Issue by Rolando-Barbella** [facebook/react-native#31989] opened 2021-08-08 18:34 UTC
## Description
I have a Mac m1, trying to get a fresh project running but no luck, the error message I'm getting is the following:

```
* What went wrong:
A problem occurred configuring project ':app'.
> compileSdkVersion is not specified. Please add it to build.gradle

```
I read the guide on [M1 for IOS](https://github.com/facebook/react-native/issues/31941), but don't see much info regarding android and M1
## React Native version:
Run `react-native info` in your terminal and copy the results here.

System:
    OS: macOS 11.2.3
    CPU: (8) x64 Apple M1
    Memory: 62.37 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.10.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3, 31.0.0
      System Images: android-25 | Google APIs ARM EABI v7a, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: javac 17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. npx react-native init AwesomeTSProject
2. npx react-native run-android

## Expected Results
Successfully build the app for android

## Snack, code example, screenshot, or link to a repository:
I tried doing some of the following in the `app/build.gradle` file but not a lot of luck

```
android {
    ndkVersion rootProject.ext.ndkVersion

    compileSdkVersion 29
    ....
```
or
```
defaultConfig {
       ....
      compileSdkVersion rootProject.ext.compileSdkVersion
    }
```

**Comment by chrisglein** [comment] 2021-08-10 18:27
Have you looked at this M1 troubleshooting guide? Helpful?
https://github.com/facebook/react-native/issues/31941

**Comment by sourabhrathour45** [comment] 2021-08-10 19:18
Have you properly downloaded the jdk for android environment ? 
Try running this brew install --cask adoptopenjdk/openjdk/adoptopenjdk8 
If your cask is not installed , run brew install cask before running the above command in the terminal.

**Comment by Rolando-Barbella** [comment] 2021-08-10 22:47
> Have you properly downloaded the jdk for android environment ?
> Try running this brew install --cask adoptopenjdk/openjdk/adoptopenjdk8
> If your cask is not installed , run brew install cask before running the above command in the terminal.

Yes, I did, but maybe my Java or Gradle vs is not the right one? I would not know

**Comment by EmreKorpe** [comment] 2021-09-16 09:25
Hi rolando. I think the problem is here.

[https://emrekorpe.medium.com/?p=9b4b5e689a44](url)

**Comment by Rolando-Barbella** [comment] 2021-09-16 10:08
Hi @EmreKorpe  thanks for the answer, I think those reference are mostly IOS, my issue is with Android

**Comment by fatlinesofcode** [comment] 2021-10-04 03:02
our project in RN64 seems to working well after following this guide, 
https://amanhimself.dev/blog/setup-macbook-m1/

we also added this to network_security_config.xml for the debug manifest to get hot reload working.

`<network-security-config>

    <base-config cleartextTrafficPermitted="true"/>

</network-security-config>`

**Comment by cortinico** [comment] 2022-01-10 12:41
@Rolando-Barbella Has this issue resolved? Are we good to close it?

**Comment by Rolando-Barbella** [comment] 2022-01-10 21:37
@cortinico Seems to be a particular issue happening in my machine, you can close it, thanks

**Closed** 2022-01-10 22:31 UTC
Labels: Platform: Android, Platform: macOS, Needs: Attention
