### ISSUE TITLE
Object.assign enumerable key 0.45.0

### ISSUE THREAD

**Issue by RWOverdijk** [facebook/react-native#14444] opened 2017-06-10 16:27 UTC
> One of the sources for assign has an enumerable key on the prototype chain. Are you trying to assign a prototype property? We don't allow it, as this is an edge case that we do not support. This error is a performance optimization and not spec compliant.

```
Object.assign
    Object.es6.js:57:16
<unknown>
    ReactNativeReconcileTransaction.js:124:2
```

I updated to 0.45.0 using the `react-native-git-upgrade` command, upon running I encounter the above in the app. I tracked it down to it trying to assign this function:

```js
function ReactNativeReconcileTransaction() {
  this.reinitializeTransaction();
  this.reactMountReady = CallbackQueue.getPooled(null);
}
```

to key `$asyncbind`

I don't know what any of this means to be honest.

**Comment by hramos** [comment] 2017-06-12 20:52
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-12 20:52 UTC
