### ISSUE TITLE
[FlatList] When I use Swiper in FlatList‘s renderHeader  , I can get nothing in android ,but ios real show 

### ISSUE THREAD

**Issue by cielu** [facebook/react-native#13816] opened 2017-05-06 15:00 UTC
I render the swiper in renderHeader ,but I cant't see anything in android . 

奇怪的是， when I refresh the flatList , the swiper do well , and I can see the image     

我在 FlatList 的 renderHeader 里面使用 Swiper ，在安卓平台上不显示内容，但是ios是正常的，奇怪的是，我一下拉刷新页面，swiper又显示了。

单独使用 Swiper都是正常的

renderBodyTop(){
        return (
            <View>
                <Swiper height={150} autoplay={true} activeDotColor="#fff">
                    {BANNER_LIST.map((item, i) => {
                        return <Image source={require('../../../img/banner.jpeg')} key={i} style={styles.banner}/>;
                    })}
                </Swiper>
                <View style={styles.featureBanner}>
                    {BANNER_LIST.map((item, i) => {
                        return <View style={styles.features} key={i}></View>;
                    })}
                </View>
                <View style={{margin:5,flexDirection:'row',alignItems:'center'}}>
                    <Image source={require('../../../img/icon_recommend.png')} style={styles.recommendIcon}/>
                    <Text>hello</Text>
                </View>
            </View>  
        );
    }

**Comment by Free-ls** [comment] 2017-05-16 07:28
我也遇到了  你的问题 解决没  解决了@我一下 谢谢 :)

**Comment by cielu** [comment] 2017-05-17 06:20
@Free-ls 没解决啊，没放header里面了，改了一下设计方案，用的 scrollView

**Comment by hramos** [comment] 2017-06-02 17:04
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-02 17:04 UTC

**Comment by cielu** [comment] 2017-06-03 01:07
@hramos @Free-ls  我用了别的方法解决了这个问题.
 I solve this problem in another way .

there are some key code

construct(props){
...
this.state={
    showSwiper:false
}
}

componentDidMount(){
     setTimeout(()=>{
          this.setState(showSwiper:true)
     },0)
}

renderSwiper=()=>{
     if(!this.showSwiper){
         return(
        <Swiper height:height ...>
         )
     }else{
         return (<View style={{height:height}}></View>)
     }
}

**Comment by kingctan** [comment] 2018-02-23 01:11
while using network images in the swiper, it can't be shown all the time.
