### ISSUE TITLE
cfbundleidentifier", does not exist -after updating Xcode 10 . 

### ISSUE THREAD

**Issue by dasDeepankar** [facebook/react-native#21255] opened 2018-09-21 19:05 UTC
- [ ] Review the documentation: https://facebook.github.io/react-native
  - [ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
OS: macOS High Sierra 10.13.6
Node: 8.12.0
Yarn: 1.9.4
npm: 6.4.1
Watchman: 4.9.0
Xcode: Xcode 10.0 Build version 10A255
Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
react: 16.3.1 => 16.3.1
react-native: 0.55.4 => 0.55.4

## Description
I'm having an issue for 3 days "cfbundleidentifier", does not exist.
I have tried solutions from StackOverflow Like
removing the node_modules and npm install,
reinstall Xcode and update xcode command tool,
clean the cache also from yarn and npm,
But still no luck. please help me out, guys.
** BUILD FAILED **

The following build commands failed:
CompileC /Users/drdas/projects/ArtisanMobileApp/node_modules/react-native/React/build/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/strtod.o /Users/drdas/projects/ArtisanMobileApp/node_modules/react-native/third-party/double-conversion-1.1.5/src/strtod.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
CompileC /Users/drdas/projects/ArtisanMobileApp/node_modules/react-native/React/build/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/fixed-dtoa.o /Users/drdas/projects/ArtisanMobileApp/node_modules/react-native/third-party/double-conversion-1.1.5/src/fixed-dtoa.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
CompileC /Users/drdas/projects/ArtisanMobileApp/node_modules/react-native/React/build/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/fast-dtoa.o /Users/drdas/projects/ArtisanMobileApp/node_modules/react-native/third-party/double-conversion-1.1.5/src/fast-dtoa.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(3 failures)

Installing build/Build/Products/Debug-iphonesimulator/Artisan.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/Artisan.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, share a project, or     share an app that reproduces the issue using https://snack.expo.io/. Please follow the guidelines for providing a MCVE: https://stackoverflow.com/help/mcve

**Comment by hramos** [comment] 2018-09-21 19:07
This typically indicates the packager failed to start. You're using an older version of RN, however, so I advise you update to 0.57 and let us know if that is still an issue.

**Comment by dasDeepankar** [comment] 2018-09-21 19:09
I'm new to RN .can you tell me how to update react-native. I have tried react-native-update .

**Comment by dasDeepankar** [comment] 2018-09-21 19:15
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 391.29 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 23.0.1, 23.0.2, 25.0.0, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.3
        API Levels: 23, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.3.1 => 16.5.0
      react-native: 0.55.4 => 0.57.1
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      create-react-native: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

**Comment by dasDeepankar** [comment] 2018-09-21 19:16
I can still reproduce =>
Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/Artisan.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by hramos** [comment] 2018-09-21 20:51
Support for Xcode 10 is not fully implemented. See https://github.com/facebook/react-native/issues/19573 for more details.

Duplicate of #19573

**Closed by hramos** 2018-09-21 20:51 UTC
Labels: :large_blue_diamond:iOS, :rewind:Old Version, 📦Bundler

**Comment by flascelles** [comment] 2018-09-21 21:06
i had this issue and tried a number of things before I realized i had an iphone connected to my laptop (for charging purposes) and the environment was trying to build for the iphone instead of the emulator and I wasn't setup for this. disconnecting the iphone and running react-native run-ios again worked!

**Comment by andy14312** [comment] 2018-09-22 07:14
@dasDeepankar hey deepankar, i've been facing the same issue since last few hours. Could you solve this in any way? though i see @hramos said that the support for XCode 10 is not fully implemented.

**Comment by tejachundru** [comment] 2018-09-22 13:13
@andy14312 
FYI, you can find more details regarding this issue in
#21168
