### ISSUE TITLE
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'

### ISSUE THREAD

**Issue by hackthemachin3** [facebook/react-native#23493] opened 2019-02-17 01:57 UTC
Tried to build my app in my Android device and get this error please help me : 

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :react-native-gesture-handler.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-gesture-handler: None of the consumable configurations have att
ributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get fu
ll insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

Command failed: gradlew.bat installDebug

Error: Command failed: gradlew.bat installDebug
    at checkExecSyncError (child_process.js:625:11)
    at Object.execFileSync (child_process.js:643:13)
    at runOnAllDevices (C:\Users\Saddam\MoviesAndMe\node_modules\react-native\local-cli\runAndroid\runAndroid.js:299:19)
    at buildAndRun (C:\Users\Saddam\MoviesAndMe\node_modules\react-native\local-cli\runAndroid\runAndroid.js:135:12)
    at isPackagerRunning.then.result (C:\Users\Saddam\MoviesAndMe\node_modules\react-native\local-cli\runAndroid\runAndroid.js:65:12)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)

**Comment by fantasy525** [comment] 2019-02-17 02:25
Hi @hackthemachin3 ，you may need run 
```
yarn add react-native-gesture-handler
react-native link react-native-gesture-handler
```

**Comment by patrickkempff** [comment] 2019-02-17 15:53
@hackthemachin3, 

Thank you for reaching out! It looks like the `react-native-gesture-handler` library can not be found. Did you install it correctly? You can follow the installation instructions here: https://kmagiera.github.io/react-native-gesture-handler/docs/getting-started.html#installation. Also make sure `react-native-gesture-handler` exists in your node_modules folder by running `yarn install`. If you still have problems you can use [StackOverflow](http://stackoverflow.com/questions/tagged/react-native) for additional help.

I'm closing this issue because it does not seem like a **bug or regression** in the **core** React Native library. If you don't agree, please feel free to file a new issue report with the reason why you think this is a react-native issue. Make sure to include steps to reproduce the behavior. Thank you!

**Closed by patrickkempff** 2019-02-17 15:53 UTC
Labels: Resolution: Missing Environment Info, Type: Bug Report

**Comment by adimaswibowo** [comment] 2019-08-29 07:28
> Hi @hackthemachin3 ，you may need run
> 
> ```
> yarn add react-native-gesture-handler
> react-native link react-native-gesture-handler
> ```

I run yarn add react-native-gesture-handler and i get the problem

error An unexpected error occurred: "EPERM: operation not permitted, unlink 'C:\
\Users\\user.user-PC\\mobile-app\\node_modules\\@babel\\plugin-transform-runtime
\\node_modules\\.bin'".

**Comment by newtonEMC2** [comment] 2019-09-26 14:34
in your build.gradle file add www to maven { url 'https://jitpack.io' } so that it ends up being maven { url 'https://www.jitpack.io' }
