### ISSUE TITLE
React Native on installing third part library it deletes other files

### ISSUE THREAD

**Issue by endari1** [facebook/react-native#14492] opened 2017-06-13 14:59 UTC
I have a problem when i try to install third part libraries.
When i create new project on RN it works ok and then  when i install third part library it installs 8 packages and deletes 167 other and the project is not working. It writes 'the command start not recognize'..

any idea why this happens?

**Comment by ginex** [comment] 2017-06-13 15:02
Same problem here. Using 0.45.1

**Comment by endari1** [comment] 2017-06-13 15:55
try to install another  version of node js. It works on me

**Comment by hramos** [comment] 2017-06-13 16:44
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-13 16:44 UTC
