### ISSUE TITLE
underlineColorAndroid default color?

### ISSUE THREAD

**Issue by JoeRoddy** [facebook/react-native#18510] opened 2018-03-22 20:52 UTC
What is the default color for this?  Using a third party input that sets it to transparent unless I pass it in, so I simply want to pass the default color. 

Can't seem to find it anywhere.

**Comment by hramos** [comment] 2018-03-22 21:04
This is backed by a native TextInput on Android, so it probably uses the theme's default. Closing as this is a question and not a bug report.

**Closed by hramos** 2018-03-22 21:04 UTC
Labels: :clipboard:No Template, :large_blue_diamond:Android, :no_entry_sign:Invalid

**Comment by JoeRoddy** [comment] 2018-03-22 21:06
Definitely a question..

Where do I ask questions?

**Comment by hramos** [comment] 2018-03-23 13:49
@JoeRoddy this is covered in the new issue template that you deleted when you opened this issue.

**Comment by JoeRoddy** [comment] 2018-03-23 17:00
@hramos  Thanks Hector! And thanks for the sass, hope your day gets better. :D
