### ISSUE TITLE
Linking - canOpenURL returns wrong response

### ISSUE THREAD

**Issue by brentlecomte** [facebook/react-native#34343] opened 2022-08-04 07:46 UTC
### Description

`Linking.canOpenUrl` returns true even the app is not installed on the device.
For example on iOS I removed both google maps and apple maps but didn't remove waze. When I check which app is installed using `Linking.canOpenUrl($urlscheme)` it returns `true` for waze and apple maps but not for google maps.

### Version

0.67.2

### Output of `npx react-native info`

System:
    OS: macOS 12.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 99.62 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.5 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.12.1 - /usr/local/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/brent/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 29.0.2, 30.0.2
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Calling the provided function in the example results in the bug.

### Snack, code example, screenshot, or link to a repository

```
export default async function isAppInstalled(appName: string, appList: AppListType[]) {
  const urlScheme = appList.find(app => app.name === appName)?.urlScheme;
  if (!isValidString(urlScheme)) {
    return false;
  }

  try {
    const hasApp = await Linking.canOpenURL(`${urlScheme}://`);

    return hasApp;
  } catch (err) {
    /* eslint-disable no-console */
    console.warn('Can not open app');
    return false;
  }
}
```

**Comment by cortinico** [comment] 2022-08-05 11:14
This is a duplicate of https://github.com/facebook/react-native/issues/34037
Please follow up over there 👍

**Closed by cortinico** 2022-08-05 11:14 UTC
Labels: API: Linking, Needs: Triage :mag:
