### ISSUE TITLE
react native release build  for ios

### ISSUE THREAD

**Issue by greenraze** [facebook/react-native#15848] opened 2017-09-07 13:01 UTC
How make react native  release build  for  ios.I have integrate react native in a project  and want to make release build  i have tried https://medium.com/react-native-development/deploying-a-react-native-app-for-ios-pt-1-a79dfd15acb8 , https://www.christianengvall.se/react-native-build-for-ios-app-store/ ,https://facebook.github.io/react-native/docs/running-on-device.html but it is  crashing  on start i have set 
  jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
 RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation moduleName:@"App"initialProperties:nil launchOptions:nil];
in Appdelegate.m  release mode is settled in scheme

**Comment by hramos** [comment] 2017-09-07 17:12
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue that meets the requirements set forth in the template. Thanks!

**Closed by hramos** 2017-09-07 17:12 UTC

**Comment by chiragpurohit71085** [comment] 2018-07-08 10:04
oops , I am facing the same issue.
