### ISSUE TITLE
RCTAnimation  pod import error in v0.44

### ISSUE THREAD

**Issue by milawoai** [facebook/react-native#13772] opened 2017-05-04 04:19 UTC
I have imported RCTAnimation project by cocoPods like this：
```
 pod 'React', :path => '../node_modules/react-native', :subspecs => [
     RCTAnimation
    ]
```
It work well before v0.44。

But now RCTNativeAnimatedNodesManager import RCTValueAnimatedNode like this:

`#import <RCTAnimation/RCTValueAnimatedNode.h>`

RCTAnimation is not a system library path and RCTValueAnimatedNode.h can not be fund。So I have to drag RCTAnimation.xcodeproj into my main project。

I read your guide about cocopods and there has no update，So I wondered why RCTValueAnimatedNode.h should be import in this way？

**Comment by janicduplessis** [comment] 2017-05-04 04:47
Closing as this is a duplicate of #13198

**Closed by janicduplessis** 2017-05-04 04:47 UTC
