### ISSUE TITLE
Increased Virtualized List Blanking in Fabric

### ISSUE THREAD

**Issue by tpcstld** [facebook/react-native#41487] opened 2023-11-14 21:07 UTC
### Description

I been working to migrate my app from Paper to Fabric. One of the roadblocks appears to be that we see additional list blanking when using virtualized lists. The two virtualized lists that I've been testing is [`FlashList`](https://github.com/Shopify/flash-list) and [a homegrown one](https://github.com/tpcstld/react-native-test/blob/fabric-scrolling/FastList.tsx).

For the rest of this issue, I'll focus my explanation based on `FlashList` on Android. FlashList because it's the more popular library, and Android because I have not yet tested any other platform.

From my debugging, I believe that (part of) the increase in blanking can be attributed to [`setState`](https://github.com/Flipkart/recyclerlistview/blob/afd0a8bb92353e40d3cacdd7fb413560cef4e7ec/src/core/RecyclerListView.tsx#L610-L612) calls getting batched into a single [`render`](https://github.com/Flipkart/recyclerlistview/blob/afd0a8bb92353e40d3cacdd7fb413560cef4e7ec/src/core/RecyclerListView.tsx#L741). This seems to delay the `render`, which delays new list items appearing on the screen, which increases blanking. This batching does not appear on Paper, but it's probably more because of concurrent mode than the implementation of Fabric in itself.

For example, in the following video, you can see that the blanking _roughly_ correlates with when the `setState` calls are getting batched:

https://github.com/facebook/react-native/assets/5456182/e10e58d0-b49c-498a-9cdc-f585b39455f4

If I hack [React internals](https://github.com/facebook/react-native/blob/ad0f0648527807883d6fb4a8f9890e041312e1d1/packages/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js#L8108) to force `setState`s to always use `SyncLane` then this problem doesn't occur (as badly). I'm wondering if there's some sanctioned API I can use to kinda... `setState` like that. Perhaps some version of `flushSync` in `react-dom`?

(Even after the above hack I still observe worse list blanking on Fabric, but I haven't been able to further isolate things yet. I dunno if you folks have any ideas. :P) 

### React Native Version

0.72.7

### Output of `npx react-native info`

```
info Fetching system and libraries information...
System:
  OS: macOS 13.6.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 19.88 GB / 64.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.6.1
    path: ~/.nix-profile/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nix-profile/bin/yarn
  npm:
    version: 9.8.1
    path: ~/.nix-profile/bin/npm
  Watchman:
    version: 4.9.0
    path: /Users/jerry.jiang/.nix-profile/bin/watchman
Managers:
  CocoaPods:
    version: 1.11.0
    path: /Users/jerry.jiang/.nix-profile/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.2
      - iOS 16.2
      - macOS 13.1
      - tvOS 16.1
      - watchOS 9.1
  Android SDK:
    API Levels:
      - "30"
      - "31"
      - "32"
    Build Tools:
      - 30.0.3
    System Images:
      - android-31 | Google Play ARM 64 v8a
      - android-32 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10671973
  Xcode:
    version: 14.2/14C18
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.1
    path: /Users/jerry.jiang/.nix-profile/bin/javac
  Ruby:
    version: 2.6.10
    path: /Users/jerry.jiang/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.7
    wanted: 0.72.7
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

The high level steps is basically:

1. Get a react-native project with a virtualized list. I've included my test project below.
2. Render a few hundred items in the list.
3. Scroll. To make it a little more scientific I've been using ADB commands like `adb shell "input touchscreen swipe 200 800 200 200 100"`

You should be able to observe that blanking is worse on Fabric than Paper.

Here are some videos of me trying it out. In these videos I'm using a Samsung Galaxy A11, I found that weaker phones allow us to more clearly see the problem. But even on a Pixel 6 Pro it is noticable.

<table>
<tr>
 <td>Paper (Prod)
 <td>Fabric (Prod)
<tr>
 <td> <video src="https://github.com/facebook/react-native/assets/5456182/1f125f24-e977-4866-bd8e-38a15862ab14">
 <td> <video src="https://github.com/facebook/react-native/assets/5456182/b3038c70-9717-4d8f-a384-5e9e4c4a92d2">
</table>

Unfortunately I couldn't figure out how to make the `SyncLane` change in a prod build so here is a dev build comparison of the hack.
<table>
<tr>
 <td> Fabric (Dev, Base)
 <td> Fabric (Dev, Hack)
<tr>
 <td> <video src="https://github.com/facebook/react-native/assets/5456182/22b55bd7-423c-46fe-af2a-1f311867c74a">
 <td> <video src="https://github.com/facebook/react-native/assets/5456182/a7c57bf4-d2c6-4713-9b60-91bd1f45228a">
</table>

### Snack, code example, screenshot, or link to a repository

https://github.com/tpcstld/react-native-test/tree/fabric-scrolling

Note the branch name, it's not `main`.

**Comment by tpcstld** [comment] 2023-11-14 21:12
FWIW, I'm not that familiar with React Native's internals, so this `setState` batching could be a red herring and I'm just getting bamboozled. This is just the path that I've been debugging so far.

Regardless the performance difference between Paper and Fabric for these virtualized lists is consistently reproable.

**Comment by cipolleschi** [comment] 2023-11-15 09:27
Thanks for the issue. We have an internal tracker for this kind of things and we plan to work on them soon: I ported the issue there.

Meanwhile, @sammy-SC or @javache do you have any thoughts on this issue/problem?

**Comment by thenickreynolds** [comment] 2023-11-15 22:41
To add some more to this - Discord has been migrating to Fabric for a while, we're nearing the end of the long migration but we're seeing significant performance drops across the app. This is the primary issue we've been able to identify concisely and create a reproduction but overall it's concerning. If we're unable to resolve the performance issues, it will be a blocker for launching the Fabric version of our app - I assume this would be the same for other companies also.

**Comment by sammy-SC** [comment] 2023-11-20 10:29
Hello,

thanks for the detailed report.

The fact that forcing React to use a different lane mitigates the issue (mostly, I will get to this later) indicates there is a difference between what event is used to trigger adding a new item to the list.
For FlashList, what host platform event is used to add a new item? 

When you are seeing a difference even with hacking React internals, are you running debug or production build?

**Comment by tpcstld** [comment] 2023-11-20 19:41
Hey Sammy!

Btw `FlashList` uses [`recyclerlistview`](https://github.com/Shopify/flash-list/blob/aafab7736f2de0878303ef4e48d2da11fc7d970e/src/FlashList.tsx#L338).

I believe that `recyclerlistview` is using the [`onScroll`](https://github.com/Flipkart/recyclerlistview/blob/afd0a8bb92353e40d3cacdd7fb413560cef4e7ec/src/core/RecyclerListView.tsx#L756) event to trigger adding the item. But it is a little convoluted. At the end of the day it's the `updateOffset` call which eventually leads to [`_renderStackWhenReady`](https://github.com/Flipkart/recyclerlistview/blob/afd0a8bb92353e40d3cacdd7fb413560cef4e7ec/src/core/RecyclerListView.tsx#L611)

I'm running on a debug build. Unfortunately I haven't yet figured out how to get my change to work when I'm using a production build haha.

**Comment by Flewp** [comment] 2023-12-13 21:59
To add to this, [here's a sandbox app](https://github.com/discord/react-native-sandbox-app/commit/bb1c3f34cea36185daffc271dff2d5849c681f99) of 500 items in a FlatList. The Android build of this sandbox has been modified to build [a specific commit](https://github.com/discord/react-native-sandbox-app/blob/bb1c3f34cea36185daffc271dff2d5849c681f99/package.json#L18) of React Native from source, using [a fork of React Native 72.7](https://github.com/discord/react-native/tree/sandbox-72.7).

Below are the findings of [using a scroll script](https://github.com/discord/react-native-sandbox-app/blob/bb1c3f34cea36185daffc271dff2d5849c681f99/tap_scroll_test.sh) to scroll the items. Left side is Paper, right side is Fabric. The videos start right after the script pushes the button to render the lists. This is with the JS dev bundle option turned off. From the videos, it looks like Fabric is taking longer to render the items, and therefore takes longer to scroll to the bottom of the list.

| **Paper** | **Fabric** |
| ---------- | ---------- |
| https://github.com/facebook/react-native/assets/1063664/002ceff8-c482-4cb2-ae93-a70167fface0 | https://github.com/facebook/react-native/assets/1063664/798d6ad2-ddbf-432d-8848-ffe433881a00 |

**Comment by tpcstld** [comment] 2023-12-19 23:22
Thanks for the response. I have also been a little off, but I will get to this soon. End of week at latest.

**Comment by tpcstld** [comment] 2023-12-22 20:15
Wait @cipolleschi, I just realized, we have ran those benchmarks in a release configuration. The videos labelled `Paper (Prod)` and `Fabric (Prod)` where generated when I built the app with `npm run android --prod`

**Comment by tpcstld** [comment] 2023-12-22 21:41
Actually sorry again, I realized what you're looking for. After further reading I understand now that there is a difference between prod and release.

Here is the benchmark on an app built with `npx react-native run-android --mode=release`:

<table>
<tr>
 <td>Paper (Release)
 <td>Fabric (Release)
<tr>
 <td><video src="https://github.com/facebook/react-native/assets/5456182/b68c04b2-d491-45ca-95dc-7fcecad6526f">
 <td><video src="https://github.com/facebook/react-native/assets/5456182/fde0f31d-83ad-46cf-a445-d974141ae596">
</table>

Scrolling down was automated using `adb shell "input touchscreen swipe 200 800 200 200 25"`. I've used the same Samsung Galaxy A11 as before.

**Comment by cipolleschi** [comment] 2023-12-28 14:42
@tpcstld Thanks a lot for checking that.

Allow me to ask a few extra questions to narrow down the problem and to understand it better:
1. I understand correctly that the problem is that the area of the red portion, when scrolling, is much bigger in Fabric, and that's an issue for you?
2. There are no issues on how smooth is the animation, right?
3. Does this happen for iOS as well?
4. How did you create the [sandbox app](https://github.com/discord/react-native-sandbox-app/commit/bb1c3f34cea36185daffc271dff2d5849c681f99) mentioned above? 
5. Did you use the same sandbox app for the test above?

based on 4. and 5. we might be able to use the sandbox app to investigate this further.

**Comment by tpcstld** [comment] 2023-12-28 20:10
Happy Holidays!

1. Yes that is correct. The red portion correlates to the amount of blanking.
2. I don't perceive any problems with frame rate, either on scrcpy or on the physical device itself.
3. iOS hardly blanks at all on either architecture, so I'm not particularly able to distinguish whether or not there is a problem, or if the better overall performance is just masking it.
4. That isn't the sandbox app that I used. I'm using https://github.com/tpcstld/react-native-test/tree/fabric-scrolling (in particular note the branch which isn't `main`). It's been a while, but I'm pretty sure I made this project via `create-react-native-app`.
5. I used https://github.com/tpcstld/react-native-test/tree/fabric-scrolling in all the videos sent so far.

**Comment by cipolleschi** [comment] 2024-01-25 13:22
Hello there! I'm trying to reproduce the issue, but it seems gone on 0.73.2.

Here are my steps:
1. Created a new app `npx react-native@latest init TestFlatList --version latest`
2. Open VS code.
3. Added the TS code below (thanks @tpcstld) for it.
4. Run the app `yarn android`. Note that I'm running in **Debug**, on purpose.
5. use this command to scroll: `adb shell "input touchscreen swipe 200 800 200 200 25"` (thanks again @tpcstld)
These are the results:

| Old Arch | New Arch |
| --- | --- |
| ![OldArch_Scroll](https://github.com/facebook/react-native/assets/11162307/c5568e5b-cad6-4193-926a-0ae8fa990fdc) | ![newArch_Scroll](https://github.com/facebook/react-native/assets/11162307/073f6187-70bb-46c9-a91b-3d39b5a85401) |


I tried to play further with the repros, but I couldn't let them display the red background.
I think that we fix these perf problems in 0.73, when we landed and released faa85f84ce96986d4097a8df99e8fbc402c6b662.


```ts
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 */

import React from 'react';
import {View, Text, StyleSheet, FlatList} from 'react-native';

const NUM_ITEMS = 300;
const HEIGHT = 40;
const DATA = Array.from({length: NUM_ITEMS}, (_, i) => i);

const isFabricEnabled = global?.nativeFabricUIManager != null;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'red',
  },
  row: {
    height: HEIGHT,
    color: 'black',
    backgroundColor: isFabricEnabled ? 'lightblue' : 'lightgreen',
  },
});

function Item({item}: {item: number}) {
  return <Text style={styles.row}>{item}</Text>;
}

function renderItem({item}: {item: number}) {
  return <Item item={item} />;
}

export default function App(): JSX.Element {
  return (
    <View style={styles.container}>
      <FlatList data={DATA} renderItem={renderItem} />
    </View>
  );
}
```

**Comment by cipolleschi** [comment] 2024-01-25 14:16
I also tried with 72.10 and I can't repro the problem.
@tpcstld @Flewp could you try to update your tests to 72.10 (I'm not asking to update to 73... yet! 😝 ) and double check? I'm worried that I might not be doing the right tests... 🤔

**Comment by Flewp** [comment] 2024-01-25 17:59
> I also tried with 72.10 and I can't repro the problem. @tpcstld @Flewp could you try to update your tests to 72.10 (I'm not asking to update to 73... yet! 😝 ) and double check? I'm worried that I might not be doing the right tests... 🤔

Thank you for testing this. Will update to 72.10 and report back!

**Comment by Flewp** [comment] 2024-03-04 20:07
Using the repro steps above, I'm also not reproducing this on 72.10 and 73.4 to the extent that we were seeing on previous versions. I also added some logs in `RecyclerListView` to make sure that the paper renderer was calling `render` for every `setState`, and that fabric was batching `setState` calls every now and then for each `render` call. So, it seems like concurrent renderer isn’t causing performance regressions in the sandbox app on these React Native versions. We'll work on upgrading our React Native version internally. Appreciate you all working with us on this. 🙏

In the videos below, I'm using a [vivo Y15a](https://www.gsmarena.com/vivo_y15a-11213.php). I used the scroll script to scroll down to the bottom of the list initially. Then scrolled with my finger to the top, bottom, and top again. Side by side:

**72.10**
| Paper | Fabric |
| ------ | ------ |
| <video src="https://github.com/facebook/react-native/assets/1063664/bd551b99-ef42-4ba5-87f3-990c2d8877b1" /> | <video src="https://github.com/facebook/react-native/assets/1063664/4ddd7f53-2caa-4404-b4bb-5eea7ad7c923" /> |

**73.4**
| Paper | Fabric |
| ------ | ------ |
| <video src="https://github.com/facebook/react-native/assets/1063664/b47a8f0c-454c-44fd-a8b8-f2bdd7b33fdf" /> | <video src="https://github.com/facebook/react-native/assets/1063664/2892ec3e-2c09-472d-b4b7-b34373463482" /> |

**Comment by cipolleschi** [comment] 2024-03-06 14:51
Sooo.... can we close the issue then? 😄

**Comment by Flewp** [comment] 2024-03-06 17:46
Yeah, we're good to close the issue 😄

**Closed** 2024-03-06 17:49 UTC
Labels: Type: New Architecture
