### ISSUE TITLE
React-native get stuck at Loading Dependency Graph ....

### ISSUE THREAD

**Issue by nilaybrahmbhatt** [facebook/react-native#15587] opened 2017-08-21 12:37 UTC
I am using Mac Mini for this.

I have a problem when i ran 'npm start' or 'react-native' start for the first time in a day.
the process gets stuck at Loading Dependency Graph.... for so much hours.
problem solved after removing and reinstalling node_modules. but this is not permanent solution.

so please provide me solution for this.

### Environment

1. `react-native -v`: 0.47
2. `node -v`: 6.2.1 
3. `npm -v`: 3.9.3

**Comment by karg-betacode** [comment] 2017-08-23 18:33
Try update node and npm to the latest version.

**Comment by hramos** [comment] 2017-08-23 19:21
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-08-23 19:21 UTC
