### ISSUE TITLE
Inverted FlatList rotates ListEmptyComponent

### ISSUE THREAD

**Issue by sokoloveugene** [facebook/react-native#30810] opened 2021-01-28 15:45 UTC
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
inverted FlatList rotates ListEmptyComponent

## React Native version:
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 29.80 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.0.0 - ~/.nvm/versions/node/v12.0.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.0.0/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.0.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. create ListEmptyComponent
2. pass it as a prop to FlatList
3. pass "inverted" prop to FlatList

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:
import React from "react";
import { FlatList, Text, View, StyleSheet } from "react-native";

const ListEmptyComponent = () => {
  return <Text>This is ListEmptyComponent</Text>;
};

const ListFooterComponent = () => {
  return (
    <View style={styles.footer}>
      <Text>Hey it is a footer</Text>
    </View>
  );
};

const ListHeaderComponent = () => {
  return (
    <View style={styles.header}>
      <Text>Hey it is a header</Text>
    </View>
  );
};

export const TestFlatList = () => {
  const renderItem = ({ item, index }) => {
    return (
      <Text>
        {item.title} with idx {index}
      </Text>
    );
  };

  return (
    <View style={styles.container}>
      <FlatList
        ListHeaderComponent={ListHeaderComponent}
        ListFooterComponent={ListFooterComponent}
        ListEmptyComponent={ListEmptyComponent}
        data={[]}
        renderItem={renderItem}
        keyExtractor={(item) => item.id}
        inverted
      />
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    width: "100%",
  },
  footer: {
    backgroundColor: "blue",
  },
  header: {
    backgroundColor: "green",
  },
});

![IMAGE 2021-01-28 17:31:57](https://user-images.githubusercontent.com/61889941/106160646-b8e1fb00-618e-11eb-9cb5-3a049d7268b0.jpg)

**Comment by safaiyeh** [comment] 2021-01-30 17:24
Duplicate of https://github.com/facebook/react-native/issues/21196, please use this issue to track this bug thanks!

**Closed by safaiyeh** 2021-01-30 17:24 UTC
Labels: Needs: Triage :mag:
