### ISSUE TITLE
Only `react-native init` gives a deprecation warning, other commands simply fail with no warning

### ISSUE THREAD

**Issue by jonthysell** [facebook/react-native#45804] opened 2024-07-29 21:54 UTC
### Description

We're trying to integrate the latest react-native main into react-native-windows, and we were pulling our hair out trying to find why our platform CLI commands weren't running anymore.

Our integration PR: https://github.com/microsoft/react-native-windows/pull/13508

We get that the `react-native` command is being deprecated, but what's the point of the code calling `warnWithDeprecated()` if that function only gives a warning if you're calling `init`? Literally every other command could use that notification too (since we use those way more often than `init`).

### Steps to reproduce

1. Build an app against a 0.76 nightly (say 0.76.0-nightly-20240701-9f6cb21ed)
2. Run `react-native config`

### React Native Version

0.76.0-nightly-20240701-9f6cb21ed

### Affected Platforms

Build - Windows

### Output of `npx react-native info`

```text
yarn run v1.22.22
$ E:\code\rnw\node_modules\.bin\react-native info
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Stacktrace or Logs

```text
yarn react-native config
Debugger attached.
yarn run v1.22.22
$ E:\code\rnw\node_modules\.bin\react-native config
Debugger attached.
Waiting for the debugger to disconnect...
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Waiting for the debugger to disconnect...
```

### Reproducer

https://github.com/Yajur-Grover/react-native-windows/tree/yg-int-7-1

**Comment by cortinico** [comment] 2024-07-30 09:34
This looks like a duplicate of https://github.com/facebook/react-native/issues/45461 from @tido64 

We already addressed this and fixed it in https://github.com/facebook/react-native/pull/45464

Any nightly after July 17th should behave correctly. Please let us know if this is not the case

**Comment by blakef** [comment] 2024-07-30 09:38
Looking at the [yarn.lock

**Closed by blakef** 2024-07-30 09:38 UTC
Labels: p: Microsoft, Partner
