### ISSUE TITLE
Crash Could not find class 'android.media.projection.MediaProjectionManagerTargetApi(21) Lower than Android5.0

### ISSUE THREAD

**Issue by rockjia** [facebook/react-native#15189] opened 2017-07-25 09:35 UTC

**Comment by rockjia** [comment] 2017-07-25 09:38
public class TestModule extends ReactContextBaseJavaModule{
        super(reactContext);
        MediaProjectionManager mMediaProjectionManager = (MediaProjectionManager) getReactApplicationContext().getSystemService(Context.MEDIA_PROJECTION_SERVICE);
    }
}

**Comment by hramos** [comment] 2017-07-25 17:04
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-07-25 17:04 UTC
