### ISSUE TITLE
React-native 0.69 custom font problem

### ISSUE THREAD

**Issue by EmreGurbuzz** [facebook/react-native#34131] opened 2022-07-05 08:43 UTC
### Description

Adding custom fonts was possible with the react-native link in previous versions, but I don't know how to do this in the current version 0.69. I could not find any documentation or data about it.

### Version

0.69.1

### Output of `npx react-native info`

System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 121.17 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.1 => 0.69.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

-

### Snack, code example, screenshot, or link to a repository

-

**Comment by infoSamyak** [comment] 2022-07-05 09:50
use npx react-native-asset for 0.69

**Comment by cortinico** [comment] 2022-07-05 10:30
Closing as this is a duplicate of #34095

**Closed by cortinico** 2022-07-05 10:30 UTC
Labels: Needs: Triage :mag:

**Comment by mrjlm70** [comment] 2022-08-29 08:28
this error shows when i used npx react-native-asset :

/var/folders/w1/mgdwdmfj4pzfr92gv49gwtlc0000gn/T/npx6676674.sh: line 2: react-native-asset: command not found

**Comment by Kazion500** [comment] 2022-08-30 23:22
> 674.sh: line 2: react-native-asset: command not found

If you get this error first install `react-native-asset` as a dev dependency then run `npx react-native-asset`

**Comment by mrjlm70** [comment] 2022-08-31 08:24
worked for me . thank you 🙏

**Comment by pankti-0627** [comment] 2022-10-13 15:44
> use `npx react-native-asset` for 0.69

not working for me! any other way to configure custom fonts in iOS?

**Comment by subhasish-smiles** [comment] 2022-11-12 11:35
Custom fonts are being copied after running npx `react-native-asset` but it's not being applied

**Comment by ArindamRayMukherjee** [comment] 2022-11-17 12:55
> use `npx react-native-asset` for 0.69

I can see the effects of installing the font and running the command above only on ios and not on android
