### ISSUE TITLE
Android TextInput setting selection props beyond 0 on mount crash

### ISSUE THREAD

**Issue by lxcid** [facebook/react-native#18316] opened 2018-03-10 08:19 UTC
When I set `selection` props on `<TextInput />` that is above 0 (e.g. `{ start: 1, end: 1 }`), it will crash at `setSpan()`…

e.g.

```jsx
<TextInput multiline={true} selection={{ start: 1, end: 1 }}>
  <Text>abc</Text>
</TextInput>
```

It seems like the text are not set before selection is applied, thereby causing the crash. Crash log stack trace provided below.

### Environment

```
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.2.0
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.2 => 0.53.2
```

### Expected Behavior

I would expect it to not crash and set the selection correctly.

### Actual Behavior

It crashes with the following stack trace…

<details>
  <summary>
    setSpan (1 ... 1) ends beyond length 0
  </summary>

```
Error while updating property 'selection' of a view managed by: AndroidTextInput

null

setSpan (1 ... 1) ends beyond length 0
updateViewProp
    ViewManagersPropertyCache.java:92
setProperty
    ViewManagerPropertyUpdater.java:129
updateProps
    ViewManagerPropertyUpdater.java:48
updateProperties
    ViewManager.java:34
createView
    NativeViewHierarchyManager.java:233
execute
    UIViewOperationQueue.java:153
dispatchPendingNonBatchedOperations
    UIViewOperationQueue.java:1010
doFrameGuarded
    UIViewOperationQueue.java:981
doFrame
    GuardedFrameCallback.java:31
doFrame
    ReactChoreographer.java:136
doFrame
    ChoreographerCompat.java:107
run
    Choreographer.java:856
doCallbacks
    Choreographer.java:670
doFrame
    Choreographer.java:603
run
    Choreographer.java:844
handleCallback
    Handler.java:739
dispatchMessage
    Handler.java:95
loop
    Looper.java:148
main
    ActivityThread.java:5417
invoke
    Method.java
run
    ZygoteInit.java:726
main
    ZygoteInit.java:616
```
</details>

### Steps to Reproduce

https://snack.expo.io/@lxcid/textinput-selection-crash

Open the snack in Android and uncomment the line with `selection={{ start: 1, end: 1 }}`…

```jsx
<TextInput
  // selection={{ start: 0, end: 0 }} // Uncomment and it does not crash
  // selection={{ start: 1, end: 1 }} // Uncomment and it crash in android
  style={styles.paragraph}
  multiline={true}>
```

**Comment by akalin-keybase** [comment] 2018-03-27 01:04
Previous discussion: https://github.com/facebook/react-native/issues/17236

**Comment by akalin-keybase** [comment] 2018-03-27 01:08
I have a workaround in https://github.com/akalin-keybase/rn-text-input-bugs , which is to wait for the next `onSelectionChange` event and set the selection there. Per the bug I linked above, this crash also happens if you set the text and selection at the same time, and the selection is out of bounds of the *old* text.

If the text box has focus, Android seems to fire `onSelectionChange` after the new text is applied, so that's why the workaround works. If the text box doesn't have focus (e.g., you're changing the text programmatically) an `onSelectionChange` isn't fired, but the selection isn't visible anyway, so it's safe to wait until the user focuses (which triggers an `onSelectionChange`) to set the new `selection`.

**Comment by akalin-keybase** [comment] 2018-06-27 18:03
Pretty sure this is still crashing.

**Comment by wenkangzhou** [comment] 2018-08-30 05:36
+1

**Comment by shenyute** [comment] 2018-12-20 02:14
The root cause is due to setSelection and setText are handled in different mechanism. Seletion is by set property and Text is handled by extra data update. And extra data update will be hanled after all properties are set.

**Comment by thymikee** [comment] 2019-04-26 07:32
Closing, as #22723 was recently merged and will be available in 0.60 release. Thanks @shenyute!

**Closed by thymikee** 2019-04-26 07:32 UTC
Labels: Component: TextInput, Platform: Android, Ran Commands, Type: Bug Report

**Comment by russelRajitha** [comment] 2019-08-26 04:57
still have same issue in react native 0.60.5.

**Comment by Anjy123** [comment] 2019-12-02 12:09
> Closing, as #22723 was recently merged and will be available in 0.60 release. Thanks @shenyute!

Still not working in 0.61.3 release. Any solution for same?

**Comment by mjmasn** [comment] 2019-12-04 11:45
@thymikee This is still very much an issue in 0.61.5 release. The workaround at https://github.com/akalin-keybase/rn-text-input-bugs/blob/master/App.js also doesn't work.

We tried some workarounds with `setNativeProps` for text and selection, but still getting crashes.

It looks like if you set the `selection` prop, or call `setNativeProps({selection: {...})` then you'll always get 2 onSelectionChanged events for the price of one when you type. The first with the accurate numbers then the second with the last values set with  `selection` or `setNativeProps({selection: {...})`. Causes cursor flicker/misplacement while typing, and crashes if you hit backspace.

Our use case is inserting emoji and mentions into a message input, while maintaining the correct selection.

I'll try to make a simple repro when I have a minute.

Arguably trying to set selection outside of the available range shouldn't crash the entire app anyway. Sure I can see arguments for both sides but IMO it should select from the start point to the end of the text if the end is out of range, or move the cursor to the end of the text if the entire selection is out of range.

**Comment by mjmasn** [comment] 2019-12-04 12:11
Doesn't look finished but https://github.com/facebook/react-native/commit/7ab5eb4cafdea695c4c53ce2a737f6302afd6380 might solve this one day as it adds a `setTextAndSelection` method.

**Comment by mjmasn** [comment] 2019-12-04 13:17
Repro: https://github.com/mjmasn/SelectionCrash

**Comment by mjmasn** [comment] 2019-12-04 16:35
@russelRajitha @Anjy123 see https://github.com/mjmasn/SelectionCrash/pull/1 for a new workaround. Haven't noticed any issues with it yet but feel free to try it and let me know how it goes.

**Comment by YoranRoels** [comment] 2020-02-07 10:34
> @russelRajitha @Anjy123 see [mjmasn/SelectionCrash#1](https://github.com/mjmasn/SelectionCrash/pull/1) for a new workaround. Haven't noticed any issues with it yet but feel free to try it and let me know how it goes.

Experiencing the same issues (only on Android) with a use case similar to yours, this fix did it for me. Thanks!
