### ISSUE TITLE
Allow functions callbacks inside StyleSheets

### ISSUE THREAD

**Issue by DanielHoffmann** [facebook/react-native#4475] opened 2015-12-01 18:12 UTC
React Native right now does not have a very comprehensive set of good practices, but something I found useful was to keep layout code outside the render function, unfortunately doing this while still using the StyleSheet class was quite cumbersome and boilerplate heavy. For example:

```javascript
let styles = StyleSheet.create({
    text: {
        fontSize: 20
    },
    textSmall: {
        fontSize: 14
    }
});

let App = React.createClass({
   ...
   render: function() {
       let textStyle = [styles.text];
       if  (Dimensions.get("window").width < 300)
           textStyle.push(styles.textSmall);
       return <Text style={textStyle} />
   }
})
```

To me this not only is cumbersome to write it also mixes layout with structure inside the code. Sure I could pull out that if to an auxiliary function but then it is another name I need to remember and would break the `style.nameOfTheStyle` standard. I want to be able to write something like this:

```javascript
let styles = StyleSheet.create({
    _text: {
        fontSize: 20
    },
    _textSmall: {
        fontSize: 14
    },
    get text() { //getter, but could also be a plain function
       if  (Dimensions.get("window").width < 300)
           return [this._text, this.textSmall];
       return [this._text];
    }
});

let App = React.createClass({
   ...
   render: function() {
       return <Text style={styles.text} />
   }
})
```

To me being able to write this improves code structure considerably, but newcomers to React Native might think that returning plain objects from those functions in StyleSheets is fine, which is not because it would create a new style object on every render call causing performance degradation. But as long as it is properly documented I see no bad sides to this at all.

I actually hacked together a helper function to implement that:

```javascript
"use strict";
let StyleSheet = require('react-native').StyleSheet;

let CreateStyleSheet = function(styles) {
    let fns= [];
    let plainStyles = {};

    for (let key of Object.keys(styles)) {
        let descriptor = Object.getOwnPropertyDescriptor(styles, key);
        if (descriptor.get) { //property has a getter defined
            fns.push({
                key: key,
                fn: descriptor.get,
                isGetter: true
            });
        } else if (typeof styles[key] === "function") {
            fns.push({
                key: key,
                fn: styles[key],
                isGetter: false
            });
        } else {
            plainStyles[key] = styles[key];
        }
    }
    let endStyles = StyleSheet.create(plainStyles);

    for (let foo of fns) {
        if (foo.isGetter) {
            Object.defineProperty(endStyles, foo.key, {
                get: foo.fn.bind(endStyles)
            });
        } else {
            endStyles[foo.key] = foo.fn.bind(endStyles);
        }
    }
    return endStyles;
};

module.exports.CreateStyleSheet = CreateStyleSheet;
```

It works and I am using it all around my code, but it is hacked because it modifies StyleSheets instances, it would be nice to have this functionality inside the StyleSheet class itself. If you guys think this is a good idea I might try to make a pull request implementing this functionality into StyleSheet.js (I believe simply adding an if in StyleSheet.js to allow functions and getters would solve it).

**Comment by satya164** [comment] 2015-12-02 04:03
Duplicate of #193

**Closed by satya164** 2015-12-02 04:03 UTC
