### ISSUE TITLE
react native html postMessage can not reach to WebView

### ISSUE THREAD

**Issue by beiming** [facebook/react-native#11594] opened 2016-12-22 08:27 UTC
I use React Native webview to show `index.html`, and HTML will post messge to the app. The app will then receive the message and write it to console. The problem is the app cannot receive messages, when `postMessage` is immediately run on head. I think it maybe related to HTML not finished loading. I then used a delay with `setTimeout`, and it worked.

Now I want to know:

- Is there better way to solve this problem?
- Why the delay 100 milliscond did not work, but delay 200 milliscond did?

I am using React Native version 0.39.0, and Node version 7.2.0.

Here is the code I have so far:

index.html
    
    <head>
    <title>Index</title>
    <script type="text/javascript" src="index.js"></script>
    <script type="text/javascript">
        // can not be received
        postMessage('send to react native from index inline, no delay', '*');

        // can not be received
        setTimeout(function(){
            postMessage('send to react native from index inline, delay 0 milliscond', '*')
        }, 0);

        // can received
        setTimeout(function(){
            postMessage('send to react native from index inline, delay 100 milliscond', '*')
        }, 100);
        
        onload = function() {
            // can not be received
            postMessage('send to react native from index inline after onload, no delay', '*')

            // can received
            setTimeout(function () {
                postMessage('send to react native from index inline after onload, delay 0 milliscond', '*')
            }, 0);
        };
    </script>
</head>

index.js

    // can not be received
    postMessage('send to react native from index.js, no delay', '*');

    // can not be received
    setTimeout(function() {
        postMessage('send to react native from index.js, delay 100 milliscond', '*')
    }, 100);

    // can received
    setTimeout(function() {
        postMessage('send to react native from index.js, delay 200 milliscond', '*')
    }, 200);

React Native web_view_page.js
    
    return (
            <WebView
                source={{uri: 'http://127.0.0.1:8000/index.html'}}
                onMessage={(event) => console.log('onMessage:', event.nativeEvent.data)}/>
        );

Chrome console log

    2016-12-21 11:45:02.367 web_view.js:147 onMessage: send to react native from index inline after onload, delay 0 milliscond
    2016-12-21 11:45:02.491 web_view.js:147 onMessage: send to react native from index inline, delay 100 milliscond
    2016-12-21 11:45:02.628 web_view.js:147 onMessage: send to react native from index.js, delay 200 milliscond

**Comment by anttu** [comment] 2017-01-08 16:44
Without setTimeout() I'm getting: 

> Failed to execute 'postMessage' on 'Window': 2 arguments required, but only 1 present.

Which I'm guessing refers to this: https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

However it does seem to work with the delay.

**Comment by farazs** [comment] 2017-01-11 23:01
Having the same issue. If a message is sent right when the page is loaded and javascript is executed it fails with that error. However, if it's executed later it seems to work. Any update on this?

**Comment by Dryymoon** [comment] 2017-01-24 03:12
You can wait for RN postMessage bridge ready:
```javascript
const queue = [];

let currentPostMessage;

let transportReady = false;
```

**Comment by sylvainbaronnet** [comment] 2017-01-27 11:09
Thanks @Dryymoon, Do you know if it works in Android too ?

**Comment by flyingbuddha** [comment] 2017-01-29 14:50
@Dryymoon Thanks for your solution. Do you know if this is intended behaviour? Seems a little odd to have to wait on the bridge to be ready to use before calling it.

I would expect the queueing behaviour to be taken care of automatically by react-native.

**Comment by jqn** [comment] 2017-01-31 19:05
@beiming In my case I wanted to trigger postMessage on click and I wasn't able to trigger the message until I added event.perventDefault() in my click event like this in the WebView page:

```
  $(".my-btn").on("click", function(event){
    event.preventDefault();
    postMessage("send message");
  });
```

Also I'm able to trigger postMessage by wrapping it with:
```
$(document).ready(function(){
   postMessage("ready");
});

**Comment by gp3gp3gp3** [comment] 2017-02-08 20:11
@beiming Thanks for this workaround.  Setting the 0 millisecond timeout on `window.onload` works in iOS but doesn't seem to work on android unless I set it to 200.

This still feels flimsy though, as I'm banking on I'm guessing the native bridge to be good to go at 200 milliseconds?  I don't really know why this behavior is happening, but setting timeouts doesn't feel right.

**Comment by andreibarabas** [comment] 2017-02-21 03:01
guys, this works on Android (i haven't tested it on iOS yet).

> 
      <html>
       <body>
       <script>

       function waitForBridge() {
          
           //the react native postMessage has only 1 parameter
           //while the default one has 2, so check the signature
           //of the function
           
           if (window.postMessage.length !== 1){
             
             setTimeout(waitForBridge, 200);
           }
           else {
             
             window.postMessage('abc');
           }
        }
        
        window.onload = waitForBridge;
        </script>
        </body>
        </html>

**Comment by farazs** [comment] 2017-03-01 21:43
I think for Android you can use `window.__REACT_WEB_VIEW_BRIDGE.postMessage` instead.

the delay for Android is in executing this:
```
window.postMessage = function(data) {
  __REACT_WEB_VIEW_BRIDGE.postMessage(String(data));
};
```

You can use the javascript interface directly instead for Android based on the implementation. However, this could break in a future version if they update it.

**Comment by chuyik** [comment] 2017-03-02 02:32
@farazs Man you really saved my day.

**Comment by doxiaodong** [comment] 2017-03-15 08:30
@Dryymoon' s method is good, but some env, you'd better use `es5` code:
```
function awaitPostMessage() {
      var isReactNativePostMessageReady = false;
      var queue = [];
      var currentPostMessageFn = function store(message) {
        queue.push(message);
      };
      if (!isReactNativePostMessageReady) {
        Object.defineProperty(window, "postMessage", {
          configurable: true,
          enumerable: true,
          get() {
            return currentPostMessageFn;
          },
          set(fn) {
            currentPostMessageFn = fn;
            isReactNativePostMessageReady = true;
            setTimeout(sendQueue, 0);
          }
        });
      }

      function sendQueue() {
        while (queue.length > 0) window.postMessage(queue.shift());
      }
    }
    awaitPostMessage();
```

**Comment by farazs** [comment] 2017-04-11 19:26
@Dryymoon I'm curious why the `setTimeout` is needed? Once the set is called we update the `postMessage` and it should work right? It seems not to work without it but I'm not sure why.

**Comment by kyle-ilantzis** [comment] 2017-04-12 00:53
For Android, Dryymoon's solution works when using the debug version. However, the release version causes  the error "__REACT_WEB_VIEW_BRIDGE.postMessage is not a function"

**Comment by chriscohoat** [comment] 2017-04-21 16:11
@doxiaodong I think you need to replace the `get/set` portion with the following:

```
...
        get: function () {
          return currentPostMessageFn;
        },
        set: function (fn) {
          currentPostMessageFn = fn;
          isReactNativePostMessageReady = true;
          setTimeout(sendQueue, 0);
        }
...
```
Otherwise Webstorm is telling me that ECMAScript 5.1 doesn't support [shorthand generator methods ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions#Shorthand_generator_methods).

**Comment by shenlq** [comment] 2017-04-27 06:48
For Android, the release version causes the error "__REACT_WEB_VIEW_BRIDGE.postMessage is not a function"！！！

**Comment by kyle-ilantzis** [comment] 2017-04-27 10:56
@shenlq if you disable proguard then it should work again

In android/app/build.gradle

def enableProguardInReleaseBuilds = false

**Comment by AshokICreate** [comment] 2017-05-02 13:51
@Dryymoon 

code works but now i am getting below error. any idea?

`Setting onMessage on a WebView overrides existing values of window.postMessage, but a previous value was defined"`

**Comment by pcstl** [comment] 2017-05-02 20:06
I had the same issue here. I managed to "solve it" as my code needs to be ran only when the user changes page, so I can bind it to ```window.onbeforeunload```, but there definitely needs to be a canonical way to check if the WebView Bridge is ready.

**Comment by farazs** [comment] 2017-05-02 20:22
For Android there's the `__REACT_WEB_VIEW_BRIDGE` workaround I mentioned. 

For iOS I ended up using https://github.com/CRAlpha/react-native-wkwebview and it doesn't have this issue with the bridge.

UIWebView also has a lot of issues that are fixed in WKWebView.

Hope this helps.

**Comment by AshokICreate** [comment] 2017-05-03 06:32
@pcstl 

could you please provide examples?

**Comment by joenoon** [comment] 2017-05-03 07:01
I ran into ```"Setting onMessage on a WebView overrides existing values of window.postMessage, but a previous value was defined"``` the other day using the `awaitPostMessage` trick.

What ended up working for me ended up being pretty simple:
1. Give your js an entrypoint function like `main()`
2. Add a ref to your WebView
3. in componentDidMount: `this.webView.injectJavaScript('main()')`

**Comment by Dryymoon** [comment] 2017-05-03 07:57
"Setting onMessage on a WebView overrides existing values of window.postMessage, but a previous value was defined" - is normal usecase in DEV mode, but in PRODUCTION this check isnt running. Die to code https://github.com/facebook/react-native/blob/master/React/Views/RCTWebView.m#L283

**Comment by Dryymoon** [comment] 2017-05-03 08:26
This code maybe solve problem, but check for native code in RN: https://github.com/facebook/react-native/blob/master/React/Views/RCTWebView.m#L285
is Wrong, because 
```javascript 
String(window.postMessage) === 'function () { [native code] }'
```
and
```javascript
String(Object.hasOwnProperty).replace('hasOwnProperty', 'postMessage') === 'function postMessage() { [native code] }'
```
And it not equal

But
**Try THIS code:**

```javascript
function awaitPostMessage() {
  var isReactNativePostMessageReady = !!window.originalPostMessage;
  var queue = [];
  var currentPostMessageFn = function store(message) {
    if (queue.length > 100) queue.shift();
    queue.push(message);
  };
  if (!isReactNativePostMessageReady) {
    const originalPostMessage = window.postMessage;
    Object.defineProperty(window, 'postMessage', {
      configurable: true,
      enumerable: true,
      get: function () {
        return currentPostMessageFn;
      },
      set: function (fn) {
        currentPostMessageFn = fn;
        isReactNativePostMessageReady = true;
        setTimeout(sendQueue, 0);
      }
    });
    window.postMessage.toString = function () {
      return String(originalPostMessage);
    };
  }

  function sendQueue() {
    while (queue.length > 0) window.postMessage(queue.shift());
  }
}
```

Usage: 
```javascript
awaitPostMessage(); // Call this only once in your Web Code.

/* After you can call window.postMessage many times, and as soon as RN Message Bridge is ready - messages delivered */
window.postMessage('Once :) ');
window.postMessage('Twice :) ');
```
Notice: In my code i limit queue for 100 message, fell free to increase this, or remove limit at all.

**Comment by Noitidart** [comment] 2017-05-28 07:50
@andreibarabas Android solution works great for me on iOS. I am just checking postMessage.length:

How come we are going to so many extremes and not just using the `postMessage.length` method? This one is so simple.

I load my webview with this:

                    <script>
                        function whenRNPostMessageReady(cb) {
                            if (postMessage.length === 1) cb();
                            else setTimeout(function() { whenRNPostMessageReady(cb) }, 100);
                        }
                    </script>

And usage of it:


                    <script>
                        function whenRNPostMessageReady(cb) {
                            if (postMessage.length === 1) cb();
                            else setTimeout(function() { whenRNPostMessageReady(cb) }, 100);
                        }


                        whenRNPostMessageReady(function() {
                             postMessage('hi react native!!!');
                        });
                    </script>

**Comment by farazs** [comment] 2017-06-06 02:49
Why was this closed? It hasn't been resolved and the current implementation is flawed requiring complex workarounds.

**Comment by probedb** [comment] 2017-07-18 13:09
Just a quick note, @Dryymoon this code fails in Safari 9 :/

It generates an

`Attempting to change configurable attribute of unconfigurable property.`

error, any thoughts on fixing?

**Comment by grabbou** [comment] 2017-08-24 14:25
It's still an issue, just experienced this.

**Comment by asmallfurrywombat** [comment] 2017-10-26 08:28
The react native event listener appears to be delayed after page load. It also seems to be the case that messages posted from the webview using postMessage aren't received by the webview's onMessage handler though messages generated by the page inside the webview are received. Perhaps it's by design but it seems to bear on this issue. Thx to Skarbo for his test.

index.html

    <html>
    <body>
      <button>Send post message from web</button>
      <div>Post message log</div>
      <script>

        window.setTimeout(function () {
          window.postMessage('send to react native from index inline, delay 2000 milliscond', '*')
        }, 2000);

        document.querySelector("button").onclick = function () {
          logMessage("Sending post message from index.html document..");
          window.postMessage("a message from index.html button", "*");
        }

        document.addEventListener("message", function (event) {
          logMessage("document received " + event.data);
        }, false);

        window.addEventListener("message", function (event) {
          logMessage("window received " + event.data);
        }, false);

        function logMessage(message) {
          console.log((new Date()) + " " + message + "\n");
        }

      </script>
    </body>
    </html>


App.js

    import React, { Component } from "react";
    import { Text, View, TouchableHighlight, WebView } from "react-native";
    export default class WebViewApp extends Component {
      constructor(props) {
        super(props);

        this.webView = null;
      }

      onMessage(event) {
        console.log("On Message", event.nativeEvent.data);
      }

      sendPostMessage() {
        console.log("Sending post message");
        this.webView.postMessage("Post message from react native");
      }

      render() {
        return (
          <View style={{ flex: 1 }}>
            <TouchableHighlight
              style={{ padding: 10, backgroundColor: "blue", marginTop: 20 }}
              onPress={() => this.sendPostMessage()}
            >
              <Text style={{ color: "white" }}>
                Send post message from react native
              </Text>
            </TouchableHighlight>
            <WebView
              style={{ flex: 1 }}
              source={require("./index.html")}
              ref={webView => (this.webView = webView)}
              onMessage={this.onMessage}
            />
          </View>
        );
      }
    }

**Comment by jjzazuet** [comment] 2017-11-18 16:16
I can confirm that the solution from @andreibarabas works for me in RN 0.50 under iOS and Android.

To be explicit:

```
import React, {Component} from 'react';
import {View, WebView} from 'react-native';

export default class WebViewTest extends Component {

  constructor(props) {
    super(props);
    this.state = {
      bridgeJs: `
        (function ready() {
          function whenRNPostMessageReady(cb) {
            if (postMessage.length === 1) cb();
            else setTimeout(function() { whenRNPostMessageReady(cb) }, 100);
          }
          whenRNPostMessageReady(function() {
            postMessage('hi react native!!!');
          });
        })();`
    };
  }

  onMessage(m) {
    alert(m.nativeEvent.data);
  }

  render() {
    return (
      <View style={{height: 0, opacity: 0}}>
        <WebView ref={(wv) => { this.webView = wv; }}
          injectedJavaScript={this.state.bridgeJs}
          onMessage={m => this.onMessage(m)} javaScriptEnabled />
      </View>
    );
  }
}
```

Thanks!

**Comment by Noitidart** [comment] 2017-11-18 17:03
Just an update, that this here worked perfectly for me on iOS and Android:

```
function init() {
    // ready to talk via postMessage
}

function whenRNPostMessageReady(cb) {
    if (postMessage.length === 1) cb();
    else setTimeout(function() { whenRNPostMessageReady(cb) }, 1000);
}

window.addEventListener('DOMContentLoaded', function() {
    whenRNPostMessageReady(init);
}, false);
```

**Comment by jjzazuet** [comment] 2017-11-19 01:52
Also, just to reiterate.

### Placing comments inside the `injectedJavaScript` property of `WebView` breaks bridge communication on Android.

So don't do that I guess :P.

**Comment by Noitidart** [comment] 2017-11-19 01:59
Verify @jjzazuet - comments work on iOS but not on Android - thanks for that

**Comment by nirpeled** [comment] 2017-11-27 19:36
Can anyone please explain me why is it okay to do these "hacks" instead of just fixing RN's WebView so it won't override the global postMessage in a way that it's breaking the API? What am I missing here? Thanks!

**Comment by andrew09** [comment] 2017-11-30 18:47
I used @Dryymoon solution and it has worked really well. Experiencing some issues in ios9 but I am working on supporting that now. I will post an update with an updated solution.

**Comment by vvavepacket** [comment] 2018-01-03 04:36
guys, do you have any idea why a webview post message back and forth in a release build is super slow yet fast in a debug build?

**Comment by tranduykhanh** [comment] 2018-01-15 07:29
@Dryymoon 
This method still works. Thank a lot.
But there a lot of tricky here :cry:

**Comment by mattbachman31** [comment] 2018-01-19 01:36
@jqn We also ran into that issue on our app, and the fix that is in RN 0.53-rc [here](https://github.com/facebook/react-native/commit/42f7b9e7172ae81b68e2be8dc5d31e45a5e79b0e#diff-17ddfccc3e39071c0aa51f82677e6d68) fixes issues on page load, but not on form submit. I filed a separate bug for this issue [here](https://github.com/facebook/react-native/issues/17489) if anyone else is dealing with that issue

**Comment by willhlaw** [comment] 2018-01-19 19:50
I second @vvavepacket question. Why does webview post message seem much slower in production than in a debug build (at least in expo comparing development mode (~0.5s) vs production mode (>5s)?

**Comment by Thomsos** [comment] 2018-03-22 12:28
@willhlaw @vvavepacket I am experience the same issue in production build. Any work around or update on this?

I am using react-native 0.54.2 and react-native-wkwebview-reborn 1.16.0

**Comment by YusufHussein** [comment] 2018-05-21 21:57
apparently injected javascript code doesn’t work in android unless compressed (you can use this online tool http://javascriptcompressor.com/ )

**Comment by Noitidart** [comment] 2018-05-21 23:41
@YusufHussein it doesn't have to be compressed. You just cannot use any comments.

**Comment by YusufHussein** [comment] 2018-05-22 00:26
@Noitidart well I tried it without comments but it didn't work untill I compressed the code
I am using react native 0.54.2 and Android simulator 6.0 Marshmallow

**Comment by kirillpisarev** [comment] 2018-08-21 12:48
Still no luck posting a message on document ready within a WebView page without a dirty hack, suggested above. Is any hope that the problem will be solved without this mess, cuz it exists for about 2.5 years...

```
function RNPostMessage(message) {
      if (window.postMessage.length === 1) window.postMessage(message);
      else setTimeout(RNPostMessage.bind(null, message), 100);
}
```

**Comment by jamonholmgren** [comment] 2018-09-09 23:56
Migrated issue to https://github.com/react-native-community/react-native-webview/issues/5. This one can be closed.

**Closed** 2018-09-24 08:43 UTC
Labels: :large_orange_diamond:Components, :large_orange_diamond:WebView

**Comment by vladikoff** [comment] 2018-11-06 17:30
Quick note about this fix for Android, if you used `postMessage.length === 1` fix for your Android app, Chrome 70 (and maybe 69?) now reports `postMessage.length` as `1`. So your app might be broken. 

Use the `[native code]` fix or something like `postMessage.toString().includes('__REACT_WEB_VIEW_BRIDGE')`
