### ISSUE TITLE
onLongPress (and delayLongPress) triggers immediately

### ISSUE THREAD

**Issue by yonatanmn** [facebook/react-native#4944] opened 2015-12-23 14:14 UTC
For some reason (I have no clue why) `onLongPress` triggers immediately, and onPress doesn't.
tested on : android simulator with genymotion (galaxy5) and real galaxy3 device

After adding `delayLongPress` i figured out that it's "stealing" 1000ms from the delay, and I guess the default delay is 1000, so it's triggering immediately.

for example : 

``` javascript
  <TouchableOpacity      
               delayLongPress={3800}
               onPress={()=>{
                  console.log(' onPress');  
                  console.log(Date.now())}}
               onPressIn ={()=>{
                  console.log('TouchableOpacity onPressIn'); 
                  console.log(Date.now())
                }}
               onLongPress ={(e)=>{
                  console.log(' onLongPress');
                  console.log(Date.now());
                  console.log(e.type); //undefined
               }}
           >
```

when I calculate  : `onLongPress time - onPressIn time` , I get ~`2800`ms 
without `delayLongPress` or with `delayLongPress={1000}` I get `10`-`20`ms

**Comment by satya164** [comment] 2015-12-23 15:33
Duplicate of this? #4088

**Comment by yonatanmn** [comment] 2015-12-23 16:35
Looks like the same problem,
closed  dev-tools (and added other display - not console.log) and it's working fine

**Comment by jozn** [comment] 2015-12-24 00:14
+1 when i debugging in chrome i see this behavior.

**Comment by raigfp** [comment] 2016-01-24 17:32
When I debugging in Chrome I see no action onLongPress

**Comment by yonatanmn** [comment] 2016-02-02 19:53
similar thing happens for `ScrollView.onScroll`- also blocking the scroll

**Comment by martincox** [comment] 2016-04-25 10:01
I tried to investigate this problem but could not replicate the behaviour. I used the example code provided by @yonatanmn and the onPress and onLongPress fired as expected.

Is there more to this, or has it been fixed?

**Comment by christopherdro** [comment] 2016-05-12 18:46
Confirming that this happens only with chrome debugger enabled.

**Comment by IjzerenHein** [comment] 2016-08-01 15:51
Also confirming that this happens only with chrome debugger enabled.

**Comment by nicastelo** [comment] 2016-08-08 17:42
Same. Confirming that this happens only with chrome debugger enabled.

**Comment by sharnik** [comment] 2016-10-27 10:52
I've just tested that and it looks like it's reversed now ;)

Without debugging tools the longPress triggers after holding for ~500-600ms, but with Chrome debugging open you need to wait ~3400ms. 

I don't know whether it's a bug or a feature, but it seems that the original problem (launching onLongPress instead of onPress) has been solved.

**Comment by zyxcambridge** [comment] 2016-12-14 07:06
ExceptionsManager.js:71 Attempted to transition from state `RESPONDER_INACTIVE_PRESS_IN` to `RESPONDER_ACTIVE_LONG_PRESS_IN`, which is not supported. This is most likely due to `Touchable.longPressDelayTimeout` not being cancelled.reactConsoleErrorHandler @ ExceptionsManager.js:71console.error @ YellowBox.js:61_handleLongDelay @ Touchable.js:596proxiedMethod @ createPrototypeProxy.js:44(anonymous function) @ JSTimers.js:80callTimer @ JSTimersExecution.js:95callTimers @ JSTimersExecution.js:136__callFunction @ MessageQueue.js:236(anonymous function) @ MessageQueue.js:108guard @ MessageQueue.js:46callFunctionReturnFlushedQueue @ MessageQueue.js:107onmessage @ debuggerWorker.js:44

**Comment by pocesar** [comment] 2017-02-27 02:56
Hmm it randomly started happening, after testing on real device with RN Debugger. it was working fine, and suddenly stopped.

**Comment by battuashwik** [comment] 2017-03-03 06:32
Im seeing this issue too.

**Comment by ThisIsMissEm** [comment] 2017-03-13 16:15
@brentvatne @satya164 How can I help? (I'm seeing this, and it's causing me issues with my workflow, and also may be resulting in the app just randomly exiting).

**Comment by skhan02** [comment] 2017-04-11 20:28
i am seeing this issue as well

**Comment by loune** [comment] 2017-05-01 11:47
I've just encountered this issue as well when debugging on Android. React Native `0.43.4`. I think this is due to #4470 The default press delay is 130ms and long press delay 470ms. This means that to be considered for a normal press, the release event needs to come between 130ms and 600ms. If I log the Touchable events I see this:
```
1493638393648 RESPONDER_GRANT
1493638393694 DELAY
1493638393696 LONG_PRESS_DETECTED
1493638393716 RESPONDER_RELEASE
```
DELAY fires `46ms` after press, not `130ms` which what is supposed to happen. LONG_PRESS_DETECTED fires `48ms` after press, not `600ms`, then release comes 68ms.
This shows that there's something wrong with setTimeout, which is noted in #4470 - although it's marked as fixed, I'm not confident it is.

Also, notice that DELAY and LONG_PRESS_DETECTED is so close together - that's because the two setTimeout calls are made simultaneously but with different timeouts (130, 600). However, this bug makes them fire really close together, and sometimes flipped around, which causes bugs like #1693 which @zyxcambridge mentioned above

**Comment by hramos** [comment] 2017-07-20 21:17
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/onlongpress-and-delaylongpress-triggers-immediately

**Closed by hramos** 2017-07-20 21:17 UTC
Labels: Android, Community Responsibility, Good First Task, Help Wanted, Icebox

**Comment by pocesar** [comment] 2017-07-21 10:52
it's been inactive but still happening. it's even worse lately when using react-native-router-flux because it brings up a red box when transitioning between scenes with the error mentioned by @zyxcambridge

**Comment by foufee** [comment] 2017-07-31 22:12
I started seeing this today too...using react native, and RNRF too.

**Comment by digitalmaster** [comment] 2017-08-27 12:31
Confirmed.. this is still happening.

**Comment by Athosone** [comment] 2017-09-03 10:02
Yes still happening..
Was working fine yesterday and today bam...

**Comment by oakis** [comment] 2017-09-29 08:22
The opposite happens to me. onLongPress takes around 2 seconds to fire, regardless of delayLongPress time. If I turn of remote debugging it is working as expected.

**Comment by themakerman** [comment] 2017-10-03 17:52
+1 happening only with chrome debugger. I hope this doesn't happens in production.

**Comment by whylifes** [comment] 2017-10-18 06:06
A competition

**Comment by whylifes** [comment] 2017-10-18 06:06
hello,I am go away!

**Comment by whylifes** [comment] 2017-10-18 06:07
forgive

**Comment by ricklove** [comment] 2017-11-22 21:19
Ah, I thought I broke everything. Thankfully it's just because of Chrome debugger.

Works fine when I disable debugger. (Using Expo)

**Comment by gorvinsky** [comment] 2018-02-06 09:55
Still having this issue and only happen when connected to Chrome debugger.

**Comment by bmr1** [comment] 2018-02-26 07:46
This breaks when only when debug JS remotely is enabled. im using VSCode debugger.
this needs to be reopened

**Comment by apn-james** [comment] 2018-04-25 18:05
maybe a obvious mistake on my part but i was not passing onLongPress a function initially i was declaring a method instance which caused it to fire on load.

`<TouchableWithoutFeedback onLongPress={this.someHandlerFunction}/>`

whereas it should be

`<TouchableWithoutFeedback onLongPress={() => this.someHandlerFunction}/>`

**Comment by ricklove** [comment] 2018-04-25 18:13
@apn-james both of those should be ok (what might be missing in the first is a bind function unless that is an arrow function instance).

Did you write the first call with parans maybe?

```
<TouchableWithoutFeedback onLongPress={this.someHandlerFunction()}/>
```

**Comment by Gennady77** [comment] 2018-05-23 16:31
The same problem while remote debugging.

**Comment by PaulPourtout** [comment] 2018-05-31 09:09
Still happening randomly (but at high frequency) on external device when remote debbuger is on. Tested it on Android devices only not sure if it happens on iOS.
