### ISSUE TITLE
Could not determine the dependencies of task ':app:lintVitalRelease'.

### ISSUE THREAD

**Issue by ajgm502** [facebook/react-native#32909] opened 2022-01-17 22:01 UTC
### Description

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.nicepeopleatwork:exoplayer-adapter:6.7.22.
     Searched in the following locations:
       - file:/Users/andresgonzalez/.m2/repository/com/nicepeopleatwork/exoplayer-adapter/6.7.22/exoplayer-adapter-6.7.22.pom
       - https://dl.google.com/dl/android/maven2/com/nicepeopleatwork/exoplayer-adapter/6.7.22/exoplayer-adapter-6.7.22.pom
       - https://plugins.gradle.org/m2/com/nicepeopleatwork/exoplayer-adapter/6.7.22/exoplayer-adapter-6.7.22.pom
       - http://maven.quickplay.local/nexus/content/repositories/public/com/nicepeopleatwork/exoplayer-adapter/6.7.22/exoplayer-adapter-6.7.22.pom
       - http://maven.quickplay.local/nexus/content/repositories/releases/com/nicepeopleatwork/exoplayer-adapter/6.7.22/exoplayer-adapter-6.7.22.pom
       - http://maven.quickplay.local/nexus/content/repositories/snapshots/com/nicepeopleatwork/exoplayer-adapter/6.7.22/exoplayer-adapter-6.7.22.pom
       - file:/Users/andresgonzalez/Documents/pldt-rn-ui/node_modules/react-native/android/com/nicepeopleatwork/exoplayer-adapter/6.7.22/exoplayer-adapter-6.7.22.pom
       - file:/Users/andresgonzalez/Documents/pldt-rn-ui/node_modules/jsc-android/dist/com/nicepeopleatwork/exoplayer-adapter/6.7.22/exoplayer-adapter-6.7.22.pom
       - https://repo.maven.apache.org/maven2/com/nicepeopleatwork/exoplayer-adapter/6.7.22/exoplayer-adapter-6.7.22.pom
       - https://www.jitpack.io/com/nicepeopleatwork/exoplayer-adapter/6.7.22/exoplayer-adapter-6.7.22.pom
       - file:/Users/andresgonzalez/Documents/pldt-rn-ui/node_modules/rn-qp-nxg-player/generated/exoplayer-adapter-6.7.22.jar
       - file:/Users/andresgonzalez/Documents/pldt-rn-ui/node_modules/rn-qp-nxg-player/generated/exoplayer-adapter.jar
     Required by:
         project :app > project :rn-qp-nxg-player

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings

I already tried adding to my build.gradle (android/app) the following but still not working:

lintOptions {
            checkReleaseBuilds false
            abortOnError false
}

### Version

react-native-cli: 2.0.1 react-native: 0.66.3-0

### Output of `npx react-native info`

System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 26.34 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.3 - ~/.nvm/versions/node/v14.18.3/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.3/bin/npm
    Watchman: 2022.01.17.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 28, 29, 30, 32
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-29 | Android TV Intel x86 Atom, android-29 | ARM 64 v8a, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs ARM 64 v8a, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play ARM 64 v8a, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /Users/andresgonzalez/.jenv/shims/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.66.3-0 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

I first started using Node 14, then npm install and change to my android directory. Once inside android directory run ./gradlew assembleRelease.

**Comment by arthurtyukayev** [comment] 2022-01-17 23:23
I've been getting the same error sporadically, but it seems to have resolved itself. This maybe have been related to some of the recent mavan outage.

**Comment by cortinico** [comment] 2022-01-18 10:35
> Could not find com.nicepeopleatwork:exoplayer-adapter:6.7.22.

That's the root cause of your problem. Your build can't find `com.nicepeopleatwork:exoplayer-adapter`. I've done a quick search and also I can't say where this package is supposed to be hosted (couldn't find it on Maven Central).

Closing as this is unrelated to React Native per se, but is a failure caused by a 3rd party package.

**Closed by cortinico** 2022-01-18 10:35 UTC
Labels: Needs: Triage :mag:
