### ISSUE TITLE
[Image + Packager] Recurring require("image!...") issues

### ISSUE THREAD

**Issue by JonathanMatthey** [facebook/react-native#521] opened 2015-03-31 02:44 UTC
following up on #282 - it still seems to happen to a lot of us.  works fine for a while and then out of nowhere 
![image](https://cloud.githubusercontent.com/assets/548027/6911394/2ce4fe68-d72e-11e4-82b6-eb2046ac4ab6.png)

tried all the suggested solutions
- updating global react-native 0.3.1
- updating local react-native 0.3.1
- node_modules .. packager.sh with --assetsRoot = defined
- naming imagesets exactly the same as the image filename

a temporary fix is to host your localhost and serve the image through `{{ uri: "localhost... myimage.png"}}` - that works fine :) but not a great solution

**Comment by wski** [comment] 2015-03-31 04:19
Was just reading http://stackoverflow.com/questions/29308937/trouble-requiring-image-module-in-react-native apparently a recent update reverted the fix :disappointed:

**Comment by amasad** [comment] 2015-03-31 08:43
sorry for the bad experience. Does restarting the server no helps?

This is certainly a stopgap period until we get to a point where the server manages the assets fully and properly. But first I'll make sure this is more reliable.

**Comment by willpiers** [comment] 2015-03-31 14:56
does anyone know which webpack loader(s) need to be used with a react native `<Image />` element? I want to be able to write `require('image!myImage')` and have webpack leave it alone for react native

**Comment by wski** [comment] 2015-03-31 17:26
@amasad Restarting the server doesn't seem to help. I've tried for a few hours to attempt different methods but had no success.

**Comment by chirag04** [comment] 2015-03-31 18:53
I spend the past one hour to debug this issue. Images are not working for me either. I have tried all the suggestions here.

I think docs can be made more clear about how to required images once the issue is resolved here.

**Comment by notduncansmith** [comment] 2015-03-31 22:27
The following command (as suggested in #481) worked for me (0.1.0):

`node_modules/react-native/packager/packager.sh --root=./ --assetRoots=./iOS/Images.xcassets`

**Comment by amasad** [comment] 2015-03-31 23:08
@notduncansmith Yup, this issue is fixed in v0.3.1
Is everyone here on this version?

**Comment by wski** [comment] 2015-03-31 23:10
@amasad I'm on the latest commit and it's not working, I figured I'd pull from GitHub vs the NPM release since there are a lot of PR's I'm hoping get merged soon :) 

Though it's worth noting I have tried 0.3.1 and it does not work there either for me.

**Comment by notduncansmith** [comment] 2015-03-31 23:14
Matt, just to clarify: it did not work when you used the terminal command I
posted above?

**Comment by wski** [comment] 2015-03-31 23:17
@notduncansmith Not that I remember, I think it gave me a packager error; I'll give it another shot though.

**Comment by chirag04** [comment] 2015-03-31 23:20
@amasad  I'm on latest version and it's not working for me. 

@notduncansmith  I tried your command also. It's still not working.

**Comment by wski** [comment] 2015-03-31 23:26
Can confirm it works if you revert to v0.3.1; :+1: 

Steps I took:
Add image to images.xcassets.

Add the require code
```
            <Image
              style={loginStyles.logo}
              source={require('image!tweetbucket')}
              />
```

Run @notduncansmith's command to override / set assetRoots,
> node_modules/react-native/packager/packager.sh --root=./ --assetRoots=./iOS/Images.xcassets

⌘R in xcode

I still think this should be considered an issue though since it was apparently working out of the box in previous versions. 

Also odd little bug it actually rendered the view twice at one point which was weird but I couldn't reproduce it.

**Comment by amasad** [comment] 2015-03-31 23:31
>Can confirm it works if you revert to v0.3.1;

Do you mean update to v0.3.1? Since it's the latest version.

It'd be really helpful if you can tell me it this work: Can you follow the standard project creation flow in the getting started guide? Add an image and report back if this works?

http://facebook.github.io/react-native/docs/getting-started.html#content

**Comment by wski** [comment] 2015-03-31 23:32
@amasad sorry should note I was using commit hash instead of npm hosted version

**Comment by chirag04** [comment] 2015-03-31 23:35
@amasad I can confirm it works with 0.3.1 and requiring images like this: require('image!something');


For me it doesn't work because i have an image inside a listView. listView data is stored in the app instead of a network call. I want to host the images also in the app.

Doesn't work when i do require('image!' + this.props.image)

**Comment by wski** [comment] 2015-03-31 23:36
@chirag04 I don't belive you should not use concatenation as outlined here: http://facebook.github.io/react-native/docs/image.html#static-assets

**Comment by chirag04** [comment] 2015-03-31 23:39
I know thats a bad practice but how do you solve my usecase mentioned above?

**Comment by wski** [comment] 2015-03-31 23:40
@chirag04 That I'm not sure about, I read on SO that version 0.3.0 might work. Have you given that version a try?

**Comment by vjeux** [comment] 2015-03-31 23:44
You should use {url: this.props.image} for non static images

**Comment by notduncansmith** [comment] 2015-03-31 23:47
@chirag04 The idea with static images (images that appear in the iOS asset bundle, i.e. `Images.xcassets`), is that they're bundled with the application and thus there's a fixed number of possible images.  So as outlined in the docs linked above, to use images dynamically in the way you're describing, you'd want to require all the images and store those in an object or something.  Then do a lookup by key.

Example:
```javascript
var images = {
  first: require('image!first'),
  second: require('image!second'),
  // ... etc
};

<Image source={images.first} />
```

**Comment by chirag04** [comment] 2015-04-01 00:06
@notduncansmith That totally works for me! Thanks :+1:

**Comment by amasad** [comment] 2015-04-01 16:31
OK so closing for now. However, this will get even better soon (better error messages, better workflow etc)

**Comment by debreuil** [comment] 2015-04-03 03:02
For me images that are PNG will work but images that are JPG will not. It the jpgs don't get processed, or at least they don't show up in the debugger. One workaround for now is to just rename the jpg's with the png extension.  ymmv

**Comment by amasad** [comment] 2015-04-03 04:52
@debreuil can you open this as a separate issue?

**Comment by debreuil** [comment] 2015-04-03 16:01
new issue for jpgs is here now: https://github.com/facebook/react-native/issues/646

**Comment by awiss** [comment] 2015-04-19 21:23
How has this been resolved? I am on 0.3.4 and am totally unable to load images using all of the suggestions. The only think I can do currently use local file references.

Is there some sort of naming convention that I am missing? I have attempted both 
image!{imagesetName} as well image!{filename}. I am using static strings for all of this.

**Comment by SatanWoo** [comment] 2015-04-26 04:50
In v0.4.0, seems running command above not solve the problem? Can someone give me a hint?

**Comment by finalquest** [comment] 2015-04-27 16:56
Same here.
In 0.4.0 installing react-native with cocoapods in an existing project.
I have the same issue. The require image!... cant be resolved. I've already try with the above arguments in the packager launch.
Is there anything else that I'm missing?

**Comment by amasad** [comment] 2015-04-27 21:22
I'm actually not entirely sure what the issue might be here. To work around this use @JonathanMatthey suggested: `{{ uri: "myimage", isStatic: true }}`

**Comment by ide** [comment] 2015-04-27 21:31
To summarize what's been working:

- Make sure React Native is up to date
- Make sure the RCTImage project is linked
- Use PNGs. Make sure to use .png extension.
- Name your image files the same as the imageset in Xcode's Images.xcassets to reduce any confusion. Ex: your image should be named "foo.png" and Xcode should display the image as "foo".
- Require the image with `require('image!foo')`
- Restart the packager after all of this just to be sure.

**Comment by amasad** [comment] 2015-04-27 21:42
Thanks @ide

>Use PNGs. Make sure to use .png extension.

[We should be also supporting JPGs now](https://github.com/facebook/react-native/blob/72c5e5d981a21ede12dcd76de5ca22a398c8bcaf/packager/packager.js#L203)

Additionally, I'm writing up a post about what we're working on to make asset management a lot better.

**Comment by ide** [comment] 2015-04-27 21:45
Sweet. I was working on getting local animated GIFs working yesterday and ran into the PNG-only issue so this is exciting to see.

**Comment by amasad** [comment] 2015-04-27 21:48
Feel free to send PR's to add any other extensions :+1:

**Comment by amasad** [comment] 2015-04-27 22:44
I wrote about what we're working on for the new asset dependency management here: #1043

**Comment by larsvinter** [comment] 2015-05-22 18:03
Hi all.

If you rename the file extension from .jpg to .png and then add it again to the asset catalog it works. You don't need to convert the file, just rename it. 

I have tested and this has solved the problems in all my projects (am using v0.4.4).

Clearly this is a bug and the renaming is an ugly workaround, but at least it allowed me to finally progress with this.

//Lars

**Comment by jhabdas** [comment] 2015-05-27 21:23
@larsvinter that totally worked. others may be able to bump to `0.4.4` to allow `jpg` file types but I'm stuck on `0.4.2` at the moment and needed a clever solution. you're my hero.

**Comment by dvine-multimedia** [comment] 2015-06-04 02:15
@larsvinter 
+1. Works like a charm.

**Comment by arunshan** [comment] 2015-06-17 01:37
Use this source={{ uri: "google", isStatic: true }} instead of require('image!google')

**Comment by jhabdas** [comment] 2015-06-17 02:27
@arunshan how about some env deets or a link to your source to make things
constructive?

**Comment by jhabdas** [comment] 2015-06-17 02:31
@arunshan disregard. crossed threads

**Comment by paramaggarwal** [comment] 2015-06-19 04:51
I was having a problem where my static image specified as `<Image source={require('image!steve-bill-2')} />` was not actually showing up. I debugged and it turns out it is an Xcode problem.

If I add `.jpg` files to Xcode `Images.xcassets`, then using `[UIImage imageNamed:path]` will not return the correct image asset. While using `.png` assets works. I think this is because only for the special case of PNG files, Xcode does not need the file extension, but for jpg images it does need. We'll need to take care of this inside `RCTConvert`s `+ (UIImage *)UIImage:(id)json;`.

**Comment by fatuhoku** [comment] 2015-07-12 13:59
> Use this source={{ uri: "google", isStatic: true }} instead of require('image!google')

This definitely works.

**Comment by facebook-github-bot-3** [comment] 2015-08-04 18:05
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by psschethan** [comment] 2015-08-06 06:28
i have a problem here, im trying to set width and height to navgatorIos rightbuttonIcon

**Comment by triage** [comment] 2015-10-14 03:19
This is definitely not working for me on 0.8.0 ... I've followed all the steps:
1. Images in Images.xcassets
2. images are png's
3. png's of course named the same as the image sets
4. rebuilt the app
5. restarted npm

`{{uri:'nameOfImage', isStatic: true}}` --> image doesn't show up
`require('image!nameOfImage')` --> 'Error: Requiring unknown module "image!nameOfImage"'

**Comment by paramaggarwal** [comment] 2015-10-14 05:57
I have noticed that RN expects the underlying filename to be the same as the name of the asset in `Images.xcassets`. Right click > Open in Finder and check the names of the underlying assets.

**Comment by triage** [comment] 2015-10-14 11:59
@paramaggarwal I've definitely got that right ... foo.png, foo@2x.png, foo@3x.png and i'm trying with `require('image!foo')`

**Comment by dvine-multimedia** [comment] 2015-10-14 14:51
@triage try to rename the png to jpg. not convert, just rename. I know it's a hack but it worked for me.

**Comment by javache** [comment] 2015-10-17 10:39
If you're using images that are bundled in an asset catalog (xcassets), you'll need to use the exact key name as in your catalog file. If you still have problems with this, please open a new issue.

**Closed by javache** 2015-10-17 10:39 UTC

**Comment by mschipperheyn** [comment] 2015-10-20 01:14
Followed all the instructions. I don't get an error, but in stead of the image I get something that takes space but doesn't show the image

**Comment by yelled3** [comment] 2015-10-22 11:54
Hey @javache I'm using `"react-native": "0.12.0",`
none of the above worked for me.
I was able to load **some** images from xcassets, but for some reason specific images are not loaded.
my only solution was to: 
* copy the assets to a side folder
* rename them
* create a new Image Set in xcassets
* and then add the renamed images back

nothing else seemed to work.
thoughts?

**Comment by triage** [comment] 2015-10-22 14:41
the setup that got me in to trouble is:
1. I have one project/workspace/repo for the iOS app
2. another for the react app, ergo Images.xcassets isn't nearly in the same folder as the react project.

I was really hoping that, under the hood, `{{uri:'nameOfImage', isStatic: true}}` just boiled down to:
`UIImage(named: "nameOfFile")` and therefore would show up regardless of the bundle that it's in, or the path to the bundle relative to react, etc.

**Comment by shaunbjohnson** [comment] 2015-11-10 18:04
In package.json:
`"react-native": "^0.14.2"`

In index.ios.js:
`<Image source={require('image!logo')} style={styles.logo} />`

In Images.xcassets:

AppIcon
logo

Xcode when built:

2015-11-10 09:29:56.522 [error][tid:main][RCTBatchedBridge.m:436] Error while loading: Unable to resolve module image!logo

**Comment by SFantasy** [comment] 2015-11-11 07:58
@shaunbjohnson Have you solve the problem?

**Comment by r6203** [comment] 2015-11-11 10:57
@shaunbjohnson I've encountered the same issue. I found out, however, that removing the "require" statement my project is able to compile in Xcode. Then I start my app on the simulator and insert the require line to my image component. Afterwards the image is displayed properly.
But that won't help much since building the project afterwards isn't possible, again.

Any fix for this?

**Comment by troywatt** [comment] 2015-12-08 14:41
After migrating to 0.14.2 and using this new approach "require('./img/logo.png')" works fine when I'm running from a local server but once I try to run from the minified bundle the image asset does not render,  has anyone else experienced this?

**Comment by ippy04** [comment] 2015-12-08 14:45
@troywatt these issues may help: 
https://github.com/facebook/react-native/issues/3888 
https://github.com/facebook/react-native/pull/3889.

**Comment by troywatt** [comment] 2015-12-08 15:46
@ippy04 Thanks, this was helpful!

**Comment by Creemli** [comment] 2016-01-15 02:25
<code>Use this source={{ uri: "google", isStatic: true }} instead of require('image!google')</code>
this also works for me~~

**Comment by gorjanz** [comment] 2016-03-23 15:08
using React-Native 0.22.0 with ordinary (react-native-cli init) setup, and inline require does not work...

**Comment by alfonsogoberjr** [comment] 2017-03-31 19:09
None of the above has worked for me. 0.42.3

**Comment by rsp8055** [comment] 2017-08-22 05:54
How can i save/store device captured image to remote pc folder. Is it possible in react native?
and 
How do post image to mysql database through php in react native
if anyone having solution please notify me on: rsp8055@gmail.com
