### ISSUE TITLE
syntax error attempted to redefine property style

### ISSUE THREAD

**Issue by mhdayyoob** [facebook/react-native#11699] opened 2017-01-02 12:36 UTC
showing the error 

syntax error attempted to redefine property style

can any one fix this 

@aroth @sharnik @redmar @andrewn @chollier  thanks in advance

**Comment by sharnik** [comment] 2017-01-02 13:25
If you get a syntax error that most probably means there's an error in your JavaScript code, not in the react-native itself. There's usually a mention of the line and column number where this error happened and you can use it to figure out what happened.

If you don't manage to track it down, I suggest you post your code to StackOverflow and probably someone will be able to help you there.

**Comment by ericvicenti** [comment] 2017-01-02 17:48
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by ericvicenti** 2017-01-02 17:48 UTC
