### ISSUE TITLE
GBoard emoji crash

### ISSUE THREAD

**Issue by kelset** [facebook/react-native#19523] opened 2018-05-31 13:31 UTC
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native version: https://github.com/facebook/react-native/releases
  - [x] Run `react-native info` in your terminal and paste its contents under "Environment"
  - [x] Let us know how to reproduce the issue. Include a code sample, share a project, or
    share an app that reproduces the issue using https://snack.expo.io/

## Environment
```
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 10.3.0
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4
```

## Description
A quite precise kind of issue, that I basically found thanks to our manual testing team. It's quite the weird bug, caused by the GBoard only in Android env (tested on iOS without repro the issue).

The weirdest part is that not all emojis trigger it. In fact, aside night:

* "cat" 🐈 -> crash
* "rainbow" 🌈 -> crash
* "cloud" ☁️ -> no crash
* "sun" ⛅️ -> no crash

Btw there the words that 'trigger' emoji suggestions are different, the only one that triggers the same emoji on both platforms is "piano" 🎹 (and on iOS it doesn't crash, on Android yes) (ok maybe not the only one, but the only one I found quickly).

And it doesn't happen with remote debugger on.

Same stacktrace as #10756 and similar to #19129 (which was closed by the bot) and #18126 (which was closed linking to PR #18114 by @joshyhargreaves) by @hramos. So this is potentially a regression? (I am not sure, I feel like it's not strictly related to that one)

## Steps to Reproduce

1. clone the [repo](https://github.com/kelset/react-native-night-emoji-crash) & cd into it
1. react-native run-android
1. make sure the device on which you run it has the Google GBoard installed
1. tap on the textinput and write "night"
1. the GBoard will suggest in the bar the night with stars emoji 🌃
1. click on the suggestion
1. crash

(the repro is the standard `react-native init` project with a [textinput](https://facebook.github.io/react-native/docs/textinput.html) just like the example in the docs)

## Expected Behavior
The emoji appears without troubles in the textinput field.

## Actual Behavior
App crashes with the following stacktrace:

```
Fatal Exception: java.lang.RuntimeException
Error calling RCTEventEmitter.receiveEvent

Caused by com.facebook.jni.CppException
Failed to create Value from JSON:

<...stacktrace>
```

If logging via LogCat, there are some extra info:

```
05-31 14:39:29.044 12953-13205/com.nightcrash I/ReactNativeJS: 'yo', 'Night'
05-31 14:39:30.163 12953-12953/com.nightcrash E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
    SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
05-31 14:39:30.197 12953-13205/com.nightcrash I/ReactNativeJS: 'yo', '🌃'
05-31 14:39:30.247 12953-13205/com.nightcrash E/unknown:ReactNative: Exception in native call
    java.lang.RuntimeException: Error calling RCTEventEmitter.receiveEvent
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:154)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:762)
     Caused by: com.facebook.jni.CppException: Failed to create Value from JSON: 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29) 
        at android.os.Looper.loop(Looper.java:154) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192) 
        at java.lang.Thread.run(Thread.java:762) 
```

**Comment by joshyhargreaves** [comment] 2018-05-31 13:42
@kelset I am almost 100% sure that this is a regression caused by the onKeyPress logic (I shall be submitting a fix for the logic itself as soon as I can). 

I would build from source before and after the merged PR and test in the RNTester app to verify.

**Comment by kelset** [comment] 2018-05-31 13:49
Ok, thanks for the swift response :) Let me know if there is anything extra I can do to help! It's really really weird that it only happens for some emojis 🧐

**Comment by kelset** [comment] 2018-05-31 14:55
Ok tested the PR locally, and I can confirm it fixes this issue. As soon as a new react-native release includes that commit I'll close this issue.

**Comment by hramos** [comment] 2018-06-15 00:02
[Fixed in `0.56.0`](https://github.com/facebook/react-native/commit/41975f75d96ef4b606b4618461bf24d5db063b77).

**Closed by hramos** 2018-06-15 00:02 UTC
Labels: :large_blue_diamond:Android, :large_orange_diamond:TextInput, :warning:Regression, Core Team

**Comment by malonguwa** [comment] 2018-06-24 03:10
@hramos is that possible you can cherry pick this command into the 0.55 release? I am not quite understand how to change my local react native android native java file.... and do not quite want to upgrade to the 0.56 just for this one issue currently in my project

**Comment by hramos** [comment] 2018-06-25 18:42
@malonguwa please route any cherry-pick requests to the relevant issue in the releases repository: https://github.com/react-native-community/react-native-releases/issues
