### ISSUE TITLE
v 0.18 flex 1.0 doesn't work if the height of parent is indirectly determined by parent's siblings

### ISSUE THREAD

**Issue by janneo** [facebook/react-native#5141] opened 2016-01-06 07:15 UTC
### 1. issue

The html dom tree is: 
<img src="https://raw.githubusercontent.com/janneo/Hi-Git/master/dom-tree.png" height="60">

The key properties are:
>
1. **body**: `flex-direction: column`       
2. **grandparent**: `align-items: stretch`    
3. **parent**: `flex-direction: column;`  
4. **me**: `flex: 1.0`  
5. **uncle**: `height: 100px`  
 
`uncle` has a fixed height `100px`,  so that the height of `grandparent` is the same as `uncle`, and `parent` should also be 100px high.

**The height of `me` is expected to be `100px`, however it's not.**     
We used only `React/Layout.c`  to layout v 0.18.  
 
**React/Layout.c**
<img src="https://raw.githubusercontent.com/janneo/Hi-Git/master/simulator.png" height="320">  

**Works well in chrome**   
<img src="https://raw.githubusercontent.com/janneo/Hi-Git/master/chrome.png" height="120">  

### 2. source

```html
<!DOCTYPE html>
<html>
    
    <head>
        <style>
            div {
                display: flex;
            }
        
        .body {
            background-color: #fff;
            height: 300px;
            flex-direction: column;
        }
        
        .grandparent {
            align-items: stretch;
        }
        
        .uncle {
            height: 100px;
            background-color: #0ae;
        }
        
        .parent {
            background-color: #fe0;
            flex-direction: column;
        }
        
        .me {
            flex: 1.0;
            background-color: #0fc;
        }
        </style>
    </head>
    
    <body id="body" class="body">
        <!-- grandparent -->
        <div class="grandparent">
            <!-- parent -->
            <div class="parent">
                <div class="me">
                    <label>"flex: 1.0" doesn't work on "me".</label>
                </div>
            </div>
            <!-- uncle-->
            <div class="uncle">
                <label>This is uncle</label>
            </div>
        </div>
    </body>
    
</html>
```

**Comment by mikemonteith** [comment] 2016-01-27 13:42
+1

**Comment by lacker** [comment] 2016-10-26 05:41
React Native flexbox isn't supposed to work precisely the same as flexbox in the browser. It's operated by css-layout so it's slightly different. We've improved the docs a lot since January, so I think this is more clear now. I'm going to close this issue but if you think there's still an area where the RN behavior doesn't match the docs, then I think it would be great to open a new issue. A reproduction of the problem on rnplay.org is the best way to be helpful for that - that's somewhat more useful than comparison code to run in a browser. Thanks for pointing this issue out.

**Closed by lacker** 2016-10-26 05:41 UTC
