### ISSUE TITLE
React native zIndex not working

### ISSUE THREAD

**Issue by khushdeepkaur** [facebook/react-native#14932] opened 2017-07-10 12:19 UTC
Created a form in react native with drop-down spinner and few text view. There is a problem when I click on drop-down spinner its options are being overlapped by the text views below

Below is code snippet and also adding screenshot
![screenshot_2017-07-10-12-31-11-404_com firstproject](https://user-images.githubusercontent.com/30046379/28017684-edf08f42-6597-11e7-8dad-b0f0015e8828.png)

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  TextInput,
  TouchableOpacity,
  Image
} from 'react-native';

import DropDown, {
  Select,
  Option,
  OptionList,
  updatePosition
} from 'react-native-dropdown';

import { StackNavigator } from 'react-navigation';
export default class Corporate extends Component {

  //=======navigation optionpane========//
  static navigationOptions = {
    title: 'Welcome',
    header: null
  };
  //====================================//

  constructor(props) {
    super(props);

    this.state = {
      canada: '',
    };
  }

  componentDidMount() {
    updatePosition(this.refs['SELECT1']);
    updatePosition(this.refs['OPTIONLIST']);
  }

  _getOptionList() {
    return this.refs['OPTIONLIST'];
  }

  _canada(province) {

    this.setState({
      ...this.state,
      canada: province
    });
  }

  render() {
    return (

      <View style={styles.container}>

        <Image source={require('../logo.jpg')} style={styles.image}></Image>
        <Text style={styles.text}>Corporate Sign Up</Text>

        <View style={{ }}>

          <Select

            width={300}
            ref="SELECT1"
            optionListRef={this._getOptionList.bind(this)}
            defaultValue="Select a Province in Canada ..."
            onSelect={this._canada.bind(this)}>
            <Option value={{ id: "alberta" }}>Alberta</Option>
            <Option>British Columbia</Option>
            <Option>Manitoba</Option>
            <Option>New Brunswick</Option>
            <Option>Newfoundland and Labrador</Option>

          </Select>

          <OptionList ref="OPTIONLIST" />

        </View>

        <View style={styles.inputWrap}>
          <TextInput
            placeholder="Company"
            secureTextEntry
            style={styles.input}
            underlineColorAndroid="transparent" />
        </View>
        <View style={styles.inputWrap}>
          <TextInput
            placeholder="Email/Employee Id"
            secureTextEntry
            style={styles.input}
            underlineColorAndroid="transparent" />
        </View>
        <View style={styles.inputWrap}>
          <TextInput
            placeholder="Password"
            secureTextEntry
            style={styles.input}
            underlineColorAndroid="transparent" />
        </View>
        <View style={styles.inputWrap}>
          <TextInput
            placeholder="Referral Code(Option)"
            secureTextEntry
            style={styles.input}
            underlineColorAndroid="transparent" />
        </View>

        <TouchableOpacity activeOpacity={.5}>
          <View style={styles.button}>
            <Text style={styles.buttonText} > Submit</Text>
          </View>
        </TouchableOpacity>
      </View>

    )
  }
}
const styles = StyleSheet.create({
  container: {

    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#000000'
  },
  image: {
    width: 250,
    height: 110
  },
  text: {
    color: "#FFF",
    fontSize: 25
  },
  inputWrap: {

    marginVertical: 10,
    height: 40,
    width: 300,
    marginTop: 20,
    backgroundColor: "#FF0000"
  },
  input: {
    flex: 1,
    paddingHorizontal: 15,
    backgroundColor: '#fff'
  },
  button: {
    backgroundColor: "#FF8C00",
    paddingVertical: 15,
    marginVertical: 15,
    marginHorizontal: 120,
    width: 100,
    height: 35,
    alignItems: "center",
    justifyContent: "center"
  },
  buttonText: {
    color: '#FFF',
    fontSize: 15
  },

  set: {
    marginTop: 20
  },
  spinner: {

    marginVertical: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
    backgroundColor: "#FF0000"

  }
});

**Comment by Ehesp** [comment] 2017-07-10 14:47
Please sort your code formatting out.

**Comment by hramos** [comment] 2017-07-10 18:48
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-07-10 18:48 UTC
