### ISSUE TITLE
App state not working in android when I pull down the notifications bar on android

### ISSUE THREAD

**Issue by akhilsanker** [facebook/react-native#24149] opened 2019-03-26 09:25 UTC
## 🐛 Bug Report

App state not working in android when I pull down the notifications bar.

## To Reproduce

The app state listerner not working when I  pull down the notifications bar in android.

## Expected Behavior

To emit the app state event listener when I pull down the notifications bar and changes any settings, such as location on/off, wifi on/off etc..

## Environment
    "react": "16.6.3",
    "react-native": "0.57.8",
    "react-native-cli": '2.0.1"

**Comment by kelset** [comment] 2019-03-26 11:00
Hello there 👋 this issue has been reported for an old version of React Native. Ideally we'd like everyone to be using 0.59 (see the [awesome changes](https://facebook.github.io/react-native/blog/2019/03/12/releasing-react-native-059) it brought) but we know updating can be a pain. To upgrade please refer to the documentation -> facebook.github.io/react-native/docs/upgrading#react-native-projects (if you are upgrading from an earlier version than 0.59.0 refer to pvinis/rn-diff-purge)

But please, if it's actually still an issue with 0.59 please comment below with a repro and we can reopen it. Even better, please send us a pull request with a fix 😊

**Comment by LaurenceRolandJames** [comment] 2019-04-23 10:56
Hi there. I am experiencing this issue using RN 59.4:

```
React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 22.87 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.15.1 - ~/.nvm/versions/node/v8.15.1/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v8.15.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 26, 27, 28
        Build Tools: 28.0.2, 28.0.3
        System Images: android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.4 => 0.59.4
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Comment by kelset** [comment] 2019-04-29 09:44
@LaurenceRolandJames can you provide a repro?

**Comment by LaurenceRolandJames** [comment] 2019-04-29 11:42
@kelset No problem, I have reproduced the issue in an app created using react-native init which uses the latest version of React Native (0.59.5):

https://github.com/LaurenceRolandJames/AndroidNotificationsBarAppStateRepro

To reproduce, run the app on an Android device with the developer tools open and compare the logs when closing and reopening the app to the logs when toggling the notification bar. App state changed logs will appear when closing and reopening the app, but will not appear when toggling the notification bar.

## React Native Environment Info:

- System:
- OS: macOS 10.14.4
- CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
- Memory: 29.16 MB / 16.00 GB
- Shell: 5.3 - /bin/zsh
- Binaries:
- Node: 8.15.1 - ~/.nvm/versions/node/v8.15.1/bin/node
- npm: 6.4.1 - ~/.nvm/versions/node/v8.15.1/bin/npm
- Watchman: 4.9.0 - /usr/local/bin/watchman
- SDKs:
- iOS SDK:
- Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
- Android SDK:
- API Levels: 26, 27, 28
- Build Tools: 28.0.2, 28.0.3
- System Images: android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom
- IDEs:
- Android Studio: 3.3 AI-182.5107.16.33.5314842
- Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
- npmPackages:
- react: 16.8.3 => 16.8.3
- react-native: 0.59.5 => 0.59.5
- npmGlobalPackages:
- react-native-cli: 2.0.1

## Android device info:

Device name: Galaxy S5 Neo
Model number: SM-G903F

**Comment by kelset** [comment] 2019-04-29 12:27
thanks, reopening

**Comment by akhilsanker** [comment] 2019-05-22 12:26
Hi @kelset ,

Any update on this?

Thanks

**Comment by Krizzu** [comment] 2019-05-23 20:45
Hey @LaurenceRolandJames, @kelset, @akhilsanker,

When a user pulls down `StatusBar` (open Notification drawer), the active activity is not going through its normal lifecycle (`onPause`/`onResume`). The only way to find if the drawer is pulled down is by listening for `onWindowFocusChanged` event, which fires when, well, activity lose focus.

I've implemented this locally and I can confirm it's working. I'll come up with a PR to discuss this API further.


thanks.

**Comment by kelset** [comment] 2019-05-27 12:05
Thanks for opening the PR! 🤗

**Comment by sujatha2016** [comment] 2020-03-02 12:49
Hi any luck with this ?

**Comment by Krizzu** [comment] 2020-03-02 14:13
@sujatha2016 Yes, it's been merged into master and released with RN 0.60.

**Comment by kelset** [comment] 2020-03-02 14:26
So we can close this I guess?

**Comment by sujatha2016** [comment] 2020-03-02 18:19
@Krizzu sorry about being a pain in neck but in my package.json the react-native = "^0.59.10"  it means it uses 0.61.5 right ? correct me if am wrong. Believing the up caret uses the latest  version of RN I tried adding focus and blur on AppState but it throws me an error Trying to subscribe unknown event focus.. Even my app is on RN version "0.59.10", Isn't there a way to achieve this ?

**Comment by Krizzu** [comment] 2020-03-03 06:46
@sujatha2016 Normally, having `^` at the package version would use any minor version upgrade, keeping the major one. But since the major version is 0, `^0.59.10` will only update on patch level - so in your case, npm will keep version `0.59`, but install latest patch release (10 is the latest in 0.59 I guess).

you can easily check what version you have using `grep` in your root directory
`$ grep "version" node_modules/react-native/package.json`

If you're planning on upgrading, [use this helpful tool that shows you what files changed between version 0.59.10 and 0.60.6](https://react-native-community.github.io/upgrade-helper/?from=0.59.10&to=0.60.6)

**Comment by fabriziobertoglio1987** [comment] 2020-04-28 13:48
merged pull https://github.com/facebook/react-native/pull/25039

**Comment by kelset** [comment] 2020-05-04 09:11
Hello there 👋 this issue seems to have been inactive for the past few weeks. Because of this, it's likely that the issue is not a high priority anymore or it has been solved by OP; for these reasons, we'll close it.

But please, if it's actually still an issue with 0.62 please comment below and we can reopen it or please send us a Pull Request with a fix 😊

**Closed by kelset** 2020-05-04 09:11 UTC
Labels: Bug, Issue: Author Provided Repro, Platform: Android, Resolution: PR Submitted

**Comment by cinder92** [comment] 2020-08-03 22:56
Appstate.addEventListener("focus") is not working on Android 7

**Comment by tnghia944** [comment] 2021-03-08 16:53
same issue hi @cinder92  Have you fixed this problem yet

**Comment by intellimouseftw** [comment] 2021-07-15 17:44
I couldn't get "focus" and "blur" working on Android either, pulling down the notification shade does not trigger the listener

**Comment by Hassan-Riaz** [comment] 2021-09-08 10:11
> I couldn't get "focus" and "blur" working on Android either, pulling down the notification shade does not trigger the listener

yes exactly I am facing same issue with react 
"react": "16.13.1",
    "react-native": "0.63.3",

**Comment by intellimouseftw** [comment] 2021-09-08 12:01
Could we possibly reopen this issue for another round of investigation? 

Seems like this feature has broken for quite a few of us since the previous fix 2 years ago. @kelset

**Comment by sarahaoun** [comment] 2022-01-28 15:05
Any update on this?

**Comment by ghiculescualexandru** [comment] 2022-08-24 13:55
any updates?

**Comment by vhakulinen** [comment] 2023-03-19 10:12
Problem still exists on `0.70`. Can this issue be reopened?

**Comment by Dipak-Complitech** [comment] 2023-07-21 04:49
Yes this issue is still

**Comment by BatDroid** [comment] 2023-10-23 19:42
same here facing the issue

**Comment by BatDroid** [comment] 2023-10-23 19:42
same here facing the issue

**Comment by croshim** [comment] 2024-10-02 17:50
Same issue, any updates on that?
