### ISSUE TITLE
Blank screen for Android. RN Version 60.0.3

### ISSUE THREAD

**Issue by vyshakh** [facebook/react-native#25704] opened 2019-07-18 09:10 UTC
Getting blank screen for android on Mac OS.  Looks fine on Windows OS.

OS: macOS 10.14.4
React Native version:
react: 16.8.6 => 16.8.6 
react-native: 0.60.3 => 0.60.3 

## Steps To Reproduce

1. react-native init testapp
2. react-native run-android

Expected screen
New intro screen

**Workaround**
Run **react-native start** before running **react-native run-android**

**Comment by iamacup** [comment] 2019-07-18 10:21
does running react-native start followed by react-native run-android fix this issue for you?

**Comment by vyshakh** [comment] 2019-07-18 10:35
> does running react-native start followed by react-native run-android fix this issue for you?

@iamacup Yup. It works.  Thank you 👍
So another workaround is 
Run **react-native start** before running **react-native run-android**

**Comment by iamacup** [comment] 2019-07-18 10:54
This is todo with some behavior change where when we run `react-native run-android` on mac after 0.60.0 the bundler does not start automatically - and then if you start the bundler AFTER running `react-native start`, no matter how many times you reload the app it will not move on from white screen.

I do not know if this is intended behavior or a bug, but it did make me pull my hair out for a while ;-)

**Comment by hannanstd** [comment] 2019-07-19 18:23
hi
i have this problem. i use UBUNTU. when i use react-native run-android i will get red page. and then i use react-native start i will get blank white screen.

**Comment by williamprt** [comment] 2019-07-20 05:10
Hi
The same for me. I use Ubuntu and tried run react-native on a physical device and Genymotion android emulator. Nothing works

**Comment by alitsvin** [comment] 2019-08-14 05:22
I'm faced this issue on Linux Mint.
Run `react-native start` before `react-native run-android` helped

**Comment by danielnora** [comment] 2019-08-17 00:27
This happens to me as well on Ubuntu 19.04.
On a brand new project:
**react-native info**
```
Binaries:
    Node: 10.16.2 - ~/.nvm/versions/node/v10.16.2/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.2/bin/npm
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```
`react-native run-android` apparently starts the Metro bundler and, after installing the app on the phone, the Metro server is closed and the app displays the message:
```
Unable to load script. Make sure you are either running a Metro server or that your bundle 'index.android.bundle' is packaged correctly for release.
```

Then, if I try to run `react-native start` and then press *Reload* on the app, the Metro server will detect the request, will build it and, upon reaching 100%, will render a white screen on the app.

After this, closing the app, restarting the metro bundler, starting the app again is completely ineffective. The only solution is uninstalling the app and only installing it again after a Metro server is running with the `react-native start` command.

**Comment by igoratf** [comment] 2019-08-24 21:09
Thanks @iamacup I was going crazy to run new projects and that actually worked.

**Comment by vuggg** [comment] 2019-09-19 14:02
> > does running react-native start followed by react-native run-android fix this issue for you?
> 
> @iamacup Yup. It works. Thank you 
> So another workaround is
> Run **react-native start** before running **react-native run-android**

Thanks, it worked

**Comment by srthiagos** [comment] 2019-09-22 17:35
I had same problem here, but in windows.
I resolve it deleting `node_modules` and reinstall using `npm install` and it's solved for me, but i don't try with `yarn install`

**Comment by Usamaliaquat123** [comment] 2019-09-22 18:01
> I had same problem here, but in windows.
> I resolve it deleting `node_modules` and reinstall using `npm install` and it's solved for me, but i don't try with `yarn install`

Yea bro, it also works some times its the problem of fetching packages through `yarn` or  `npm i`. Yes you can use `yarn ` instead of  `yarn  install`

**Comment by iamacup** [comment] 2019-09-30 17:45
@vyshakh do you mind testing this now on a new project - react native 0.61.x ?

looks to me like this is fixed and could be closed.

**Comment by sandunmj** [comment] 2019-10-12 04:15
`react-native start` in one terminal and the `react-native run-android` in another terminal fixed the issue for me.

**Comment by SopoB** [comment] 2019-11-04 11:23
What if the same issue is coming on building the final app (apk) file, how to avoid that white screen?

**Comment by iamacup** [comment] 2019-11-04 11:30
@SopoB it is probably unrelated to this issue - a white screen typically indicates a javascript runtime crash which could be because of anything - you will need to see debugging release builds in the docs

**Comment by EduardoAraujoB** [comment] 2019-11-08 00:42
hey, i've the same problem on Ubuntu, for thats work for me i've to run `react-native start` in one terminal and run `react-native run-android` in other terminal

**Comment by nikfardin** [comment] 2019-11-10 07:30
The same problem on Ubuntu 19.04, RN 0.61.4. It works for me.
First run `npx react-native start` then `npx react-native run-android`

**Comment by Touseef-ahmad** [comment] 2019-11-20 08:41
The same problem on Ubuntu 19.04, RN 0.61.4. It works for me.
First run `react-native start` then `react-native run-android` 
but why?

**Comment by sandunmj** [comment] 2019-11-20 09:12
`react-native-start` for starting the server which communicates with the phone/ emulator.
 `react-native run-android` builds the project and installs in the phone/ emulator using the communication tunnel which was created before.

**Comment by EduardoAraujoB** [comment] 2019-11-21 19:42
React Native does not start the metro-bundler automatically? in other systems i didn't have this problem, maybe a problem in configurations on Ubuntu, terminal or a bug in react-native-cli?

**Comment by israelcena** [comment] 2019-11-25 01:39
I've the same problem on Mint 19.2 and works for me.
First run react-native start then react-native run-android !!

**Comment by EduardoAraujoB** [comment] 2019-11-25 02:39
I think that's a problem to start the metro-bundler automatically on linux, so maybe it's a problem in the terminal or configurations of the react native for linux

**Comment by virtumonde** [comment] 2019-11-25 07:08
Experienced the same problem on Mac and starting the Metro server before the app (react-native start) fixed it.

**Comment by Alaaeldin1993** [comment] 2019-11-26 10:15
works for me.
First run npx react-native start then npx react-native run-android

**Comment by israelcena** [comment] 2019-11-28 13:38
metro-bundler is the problem

**Comment by EduardoAraujoB** [comment] 2019-11-29 16:59
So what is wrong with metro-bundler? It's starts but not automatically when the react-native run-android is finishing, but work when we started it on other terminal, maybe its a problem to start metro-bundler automatically?

**Comment by godswillokokon** [comment] 2019-12-14 18:19
> Hi
> The same for me. I use Ubuntu and tried run react-native on a physical device and Genymotion android emulator. Nothing works

hello, who did you fix this issue

**Comment by Shoukat488** [comment] 2019-12-31 14:49
> This is todo with some behavior change where when we run `react-native run-android` on mac after 0.60.0 the bundler does not start automatically - and then if you start the bundler AFTER by running `react-native start`, no matter how many times you reload the app it will not move on from white screen.
> 
> I do not know if this is intended behavior or a bug, but it did make me pull my hair out for a while ;-)

I faced a same issue but now has been solved through your solution. Thanks

**Comment by Gabriel-Aquino** [comment] 2020-01-08 23:25
Funcionou! Fiz o seguinte passo: primeiro executei **react-native start**, após aparecer o "**loading... done**" eu executei o comando **react-native run-android** e funcionou. Estava fazendo o contrário e a tela ficava apenas branca.

**Comment by Shoukat488** [comment] 2020-01-09 11:50
> Funcionou! Fiz o seguinte passo: primeiro executei **react-native start**, após aparecer o "**loading... done**" eu executei o comando **react-native run-android** e funcionou. Estava fazendo o contrário e a tela ficava apenas branca. Usando Linux Mint 19.3 "Tricia"

I don't understand the language which you have written. So giving an answer by so far my understanding.
run the following commands in the this order.
1- npm start or react-native start
2- react-native run-android
It worked for me

**Comment by MrCreeper1008** [comment] 2020-02-01 20:12
Doesn't work for me.

**Comment by Gabriel-Aquino** [comment] 2020-02-19 14:06
> > Funcionou! Fiz o seguinte passo: primeiro executei **react-native start**, após aparecer o "**loading... done**" eu executei o comando **react-native run-android** e funcionou. Estava fazendo o contrário e a tela ficava apenas branca. Usando Linux Mint 19.3 "Tricia"
> 
> I don't understand the language which you have written. So giving an answer by so far my understanding.
> run the following commands in this order.
> 1- npm start or react-native start
> 2- react-native run-android
> It worked for me

Oh, Sorry bro, i said that it worked to me too, but I wrote in portuguese. I followed the same steps did you say, thanks!

**Comment by lumagallacio** [comment] 2020-02-23 20:33
> 
> 
> Funcionou! Fiz o seguinte passo: primeiro executei **react-native start**, após aparecer o "**loading... done**" eu executei o comando **react-native run-android** e funcionou. Estava fazendo o contrário e a tela ficava apenas branca. Usando Linux Mint 19.3 "Tricia"

funcionou! obrigada

**Comment by arieller** [comment] 2020-03-08 18:46
the start and run-android doesnt work
neither reinstalling the npm packages
what is this?

**Comment by joseananio** [comment] 2020-04-01 23:47
facing same issue on a fresh project. Ubuntu 19.10 react native 0.62.0. None of these suggestions works for me

**Comment by joshglenn** [comment] 2020-04-11 17:40
I'm currently having this problem on version 0.61.5. This was working fine previously, but something happened. Still, starting the metro bundler first with `yarn start` and after that, running `yarn android` works around the problem.

**Comment by ithustle** [comment] 2020-04-13 14:26
I have this behavior on my app after release it. Some help will be nice!

**Comment by Jackson-Calixto** [comment] 2020-04-18 01:22
> This happens to me as well on Ubuntu 19.04.
> On a brand new project:
> 
> `react-native info` (Output)
> 
> ```
> Binaries:
>     Node: 10.16.2 - ~/.nvm/versions/node/v10.16.2/bin/node
>     Yarn: 1.17.3 - /usr/bin/yarn
>     npm: 6.9.0 - ~/.nvm/versions/node/v10.16.2/bin/npm
>   npmPackages:
>     react: 16.8.6 => 16.8.6 
>     react-native: 0.60.5 => 0.60.5 
>   npmGlobalPackages:
>     react-native-cli: 2.0.1
> ```
> 
> `react-native run-android` apparently starts the Metro bundler and, after installing the app on the phone, the Metro server is closed and the app displays the message:
> 
> ```
> Unable to load script. Make sure you are either running a Metro server or that your bundle 'index.android.bundle' is packaged correctly for release.
> ```
> 
> Then, if I try to run `react-native start` and then press _Reload_ on the app, the Metro server will detect the request, will build it and, upon reaching 100%, will render a white screen on the app.
> 
> After this, closing the app, restarting the metro bundler, starting the app again is completely ineffective. The only solution is uninstalling the app and only installing it again after a Metro server is running with the `react-native start` command.

Thank you so much, it worked for me

**Comment by jackiewung** [comment] 2020-04-21 01:12
Don't know if this will help anybody, but if you have the prop `defaultVideoQuality` passed, check that your device can support it (front and back also have different video quality)

Had `defaultVideoQuality` set to `1080p` on the front camera and noticed that iPhone 5s devices only supports `720p`

**Comment by VivekkChudasama** [comment] 2020-05-01 03:50
I try to run react-native start and then press Reload on the app, the Metro server will detect the request, will build it and, upon reaching 100%, will render a white screen on the app.

After this, closing the app, restarting the metro bundler, starting the app again is completely ineffective. The only solution is uninstalling the app and only installing it again after a Metro server is running with the react-native start command.

Not working

**Comment by smartsailor** [comment] 2020-05-03 09:59
> Getting blank screen for android on Mac OS. Looks fine on Windows OS.
> 
> OS: macOS 10.14.4
> React Native version:
> react: 16.8.6 => 16.8.6
> react-native: 0.60.3 => 0.60.3
> 
> ## Steps To Reproduce
> 1. react-native init testapp
> 2. react-native run-android
> 
> Expected screen
> New intro screen
> 
> **Workaround**
> Run **react-native start** before running **react-native run-android**

what if you try using local option out of 3 available options ,
I mean from Tunnel,LAN,Local.
Please try running on adnroid using Local option.
I dont know if this is right or wrong,but its working on my device.
Please correct me if I will miss on any important thing in future if I go ahead with this option.
Thanks.

**Comment by flyskywhy** [comment] 2020-05-06 05:36
With test `react-native init --version 0.61.0 rn610` and `react-native init --version 0.61.1 rn611`, results 0.61.0 is good and 0.61.1 has current issue.

The only meaningful commit between 0.61.0 and 0.61.1 is [Allow again for injecting custom root view via ReactActivityDelegate (#26495)](https://github.com/facebook/react-native/commit/42ad0bb627b296858c0200e660635004c90e5b82) by @kmagiera (and committed by @grabbou ), it will be nice if @kmagiera improve the compatibility between this commit and the Metro server.

**Comment by ajaymarathe9** [comment] 2020-07-14 10:30
> Getting blank screen for android on Mac OS. Looks fine on Windows OS.
> 
> OS: macOS 10.14.4
> React Native version:
> react: 16.8.6 => 16.8.6
> react-native: 0.60.3 => 0.60.3
> 
> ## Steps To Reproduce
> 1. react-native init testapp
> 2. react-native run-android
> 
> Expected screen
> New intro screen
> 
> **Workaround**
> Run **react-native start** before running **react-native run-android**

It works :P

**Comment by mohammadbrzbrz72** [comment] 2020-09-28 05:14
the correct way for linux ubuntu 20.04 lts
you should do this to run android in develop mod

when you turn on your pc or laptop to work on project,
you should pass these steps:

1-  react-native run-android (  when finish the first step , you see error in your emulator or device )
2-  to fix this problem, close that project in your emulator or device ( but the terminal or your vscode must be opened )
3-  then write  react-native start  in your terminal
4-  open your built project and then you can see the project starting to bundle

enjoy your project :)

**Comment by fabriziobertoglio1987** [comment] 2021-02-03 16:46
sorry, I did not read each answer but I believe this is not an issue with `react-native`, but https://github.com/react-native-community/cli

There is an open issue https://github.com/react-native-community/cli/issues/1223 to fix metro server not starting when running `react-native run-android`

**Comment by ovinokurov** [comment] 2021-02-07 07:04
This is a very easy fix, I don't understand why nobody came up with the solution before. 

1) Go to Android Studio
2) Open your [Android Virtual Device Manager] in [Your Virtual Devices] delete all devices and add a new one.

Now Run :) good luck!

**Closed** 2021-06-13 12:37 UTC
Labels: Bug, Platform: Android

**Comment by theking200794** [comment] 2021-08-24 05:23
I was getting the error "Invariant Violation: Module AppRegistry is not a registered callable module" and because of this was facing a white screen issue. After struggling for a day first I rest cache using 
`npx react-native start --reset-cache`
After that, I give this command 
`react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res `
and deleted the already installed app on my real device.
After that, I did a weird thing: restarting my pc and installing the app again using IntelliJ and the white screen issue was gone.

**Comment by ZeeshanAhmadKhalil** [comment] 2022-02-15 17:32
I am getting this issue when i enable chrome debugger!
