### ISSUE TITLE
[ListView] Re-renders changed rows multiple times

### ISSUE THREAD

**Issue by chrisbianca** [facebook/react-native#5255] opened 2016-01-11 18:27 UTC
I have a ListView backed by a Flux store.  When data in the underlying array changes, the changed rows are re-rendered correctly.  However, until the store changes again, these rows continue to be re-rendered every time render() is called for the underlying scene.

This is caused by the fact that the _dirtyRows array in ListViewDataSource is only updated when new data is supplied to the datasource.

As a result, rowShouldUpdate always returns true for the row, and the ListView re-renders the row each time.

A simple way to fix this is to update rowShouldUpdate to remove the _dirtyRows flag for the row when it is called, but I'm not sure this would necessarily be the correct way to go.

**Comment by eadz** [comment] 2016-01-11 21:44
I think this may be a regression. I am seeing behaviour where I update a listview's data source, and the row keeps re-rendering no matter what, but only in some cases.

**Comment by geirman** [comment] 2016-03-31 02:55
@chrisbianca @eadz which version of RN were you guys using? We should probably check if this is happening in the latest release and provide steps to duplicate this issue, a gist, and/or an example on rnplay. What do you think?

**Comment by chrisbianca** [comment] 2016-04-01 08:54
I can't remember which version I was using at the time, but I'm currently using 0.22.0 and the issue is still present.

As a hacky fix I simply update ListViewDataSource.rowShouldUpdate and add:

`this._dirtyRows[sectionIndex][rowIndex] = false;`

so that the method becomes:

```
rowShouldUpdate(sectionIndex: number, rowIndex: number): bool {
  var needsUpdate = this._dirtyRows[sectionIndex][rowIndex];
  warning(needsUpdate !== undefined,
    'missing dirtyBit for section, row: ' + sectionIndex + ', ' + rowIndex);
  this._dirtyRows[sectionIndex][rowIndex] = false;
  return needsUpdate;
}
```

This ensures that a row will only every update the first time that it is marked as 'dirty'.  I haven't submitted it as a PR because I'm not sure that this is necessary the best way to go but it works!

**Comment by geirman** [comment] 2016-04-01 15:28
@chrisbianca I recommend submitting the PR regardless. It's probably the best way to get input since it will need to be reviewed prior to pulling it in.

**Comment by lacker** [comment] 2016-10-21 00:01
I will ping some folks to help get a reviewer for that pull request. Since you found a workaround for this particular issue and there's a pull request in flight, I'm going to close this issue, but feel free to reopen this or another one if there's something additional to discuss on it.

**Closed by lacker** 2016-10-21 00:01 UTC
