### ISSUE TITLE
How to use react-native image in Native code? 

### ISSUE THREAD

**Issue by Symous** [facebook/react-native#14185] opened 2017-05-25 09:19 UTC
I have a folder named 'images' in the root directory of my react-native app. 
Is there any way we can use a png image in the images direcory in Android Native Code directly?

**Comment by nihgwu** [comment] 2017-05-25 09:52
**Issues** is for bug tracking, not for QA

**Comment by hramos** [comment] 2017-05-25 19:57
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-05-25 19:57 UTC
