### ISSUE TITLE
WebView - some websites don't work

### ISSUE THREAD

**Issue by maciejjj** [facebook/react-native#6707] opened 2016-03-29 15:02 UTC
Hi,
I have some issues with WebView component, which doesn't work with some websites, currently I have two examples:
http://cnn.com (error code: 101, the url can't be shown)
http://realself.com (error code: -1003, a server with the specified hostname could not be found)

Both errors appear after 1-2 seconds, and they are not present in regular UIWebView. I am using react-native 0.22 and iOS 9.2, but I saw these errors with earlier versions of RN too. 

Minimal test case (just WebView with one of above urls):
https://rnplay.org/apps/S9ZcTw

Regards

**Comment by mbathie** [comment] 2016-04-07 12:54
We are experiencing this issue also.

**Comment by lopezjuanr** [comment] 2016-04-07 13:15
I've seen the same bug specifically on iOS 9.0 and above.

**Comment by aaroncrawford** [comment] 2016-04-18 21:36
Using RN .22 on iOS 9.3 and am seeing this bug as well.  Don't think it's anything to do with anchors in the URL or anything of the sort as cnn.com root doesn't work either.  Any suggestions?  This is app breaking at the moment.

**Comment by satya164** [comment] 2016-04-18 21:46
Can you update to the latest RC and see if this still happens?

**Comment by aaroncrawford** [comment] 2016-04-18 21:57
@satya164 my project requires .22 due to router flux being locked at .22 for now - can anyone else on .23 confirm?

All that would need to be done is include WebView and have the source point at cnn.com, for example.

**Comment by maciejjj** [comment] 2016-04-18 21:59
I've just checked - the same error occurres in v0.25.0-rc and 0.23.1.

**Comment by aaroncrawford** [comment] 2016-04-18 22:05
@maciejjj thanks much.

**Comment by mbathie** [comment] 2016-04-26 14:48
@aaroncrawford we're you able to fix the issue?

**Comment by aaroncrawford** [comment] 2016-04-26 18:02
@mbathie No - hoping it gets fixed in future releases.  Not an ob-c dev, so I'm not sure I can fix personally.

**Comment by tomav** [comment] 2016-05-27 22:29
Same issue here…
```
    "react": "15.0.2",
    "react-native": "^0.26",
    "react-native-router-flux": "^3.26.5",
```

**Comment by aaroncrawford** [comment] 2016-05-27 23:56
Can anyone look into this?  Our app is somewhat broken until this can be addressed.

**Comment by satya164** [comment] 2016-05-28 13:03
@aaroncrawford The core team is busy with lots of things. If this is a blocker for you, it would be great if you can investigate the issue and send a patch.

**Comment by aaroncrawford** [comment] 2016-05-30 23:36
I would but I believe this would require Obj-C - which isn't my bag.  Hopefully someone can help out.

**Comment by tomav** [comment] 2016-05-31 12:19
Just found in my case that I had a param `&redirect_uri=myappscheme://foo`
When I remove the `//` it works (but my `redirect_uri` is broken).

**Comment by willyyang** [comment] 2016-09-21 20:54
Has anyone solved this issue/ found a workaround? Any feedback would be greatly appreciated.

**Comment by Kerumen** [comment] 2016-10-07 10:35
Hello everyone,

I wanted to have a look on this so I tested the 2 failing websites on the latest RN (0.34) on iOS 8/9/10 and it works perfectly.

Let me know if you face this issue again and what are you using so I can reproduce.

**Comment by ronniegong** [comment] 2016-10-12 03:15
@Kerumen 
still get this error
url:https://store.gf.com.cn/app-invest-web/#/webend-index
RN(0.35) on iOS 9.3 ip6

first

then
![Uploading image.png…]()

**Comment by lacker** [comment] 2016-10-25 01:42
The main issue here seems resolved, and the most recent comment seems like it doesn't have enough information to reproduce, so I'm going to close this issue. If people have additional reports of websites not working, it would be great to file a new issue.

**Closed by lacker** 2016-10-25 01:42 UTC
Labels: Community Responsibility, Help Wanted
