### ISSUE TITLE
Invariant Violation: Native module cannot be null.

### ISSUE THREAD

**Issue by massoprod** [facebook/react-native#27661] opened 2020-01-03 12:30 UTC
Hi, I have a problem with upgrading react-native from 0.59.10 to 0.61.5 with NativeModules.

We have our own native modules. In 0.59.10 version there was no issue with that. After upgrade to 0.61.5, I have this issue.

React Native version:
```
System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 527.22 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.5.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 28.0.3, 29.0.0, 29.0.1, 29.0.2
      System Images: android-26 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
    react-native: 0.61.5
```

## Steps To Reproduce
[skip]

![Simulator Screen Shot - iPhone 8 - 2020-01-03 at 13 26 00](https://user-images.githubusercontent.com/8200096/71723506-26f1ac80-2e2d-11ea-9ca7-4aa65af7e9f0.png)

Thank you.

**Comment by rwrife** [comment] 2020-01-07 19:34
I'm having the same issue when I run `npx react-native init HelloWorld && cd HelloWorld && $(npm bin)/react-native run-ios`

**Comment by akshay-daffodil-93** [comment] 2020-01-14 08:43
Having same issue, anyone have a solution?

**Comment by volpejoaquin** [comment] 2020-01-20 13:54
Same problem, waiting a response...

**Comment by kelset** [comment] 2020-01-22 12:22
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

This also seems to be related to your upgrade process. Have you checked the changelog to see how RN has evolved between 0.59 and 0.61? Quite a few things changed on the Native Module aspect:
* https://facebook.github.io/react-native/blog/2019/07/03/version-60
* https://facebook.github.io/react-native/blog/2019/09/18/version-0.61
* changelog -> https://github.com/react-native-community/releases/blob/master/CHANGELOG.md

**Comment by mikehardy** [comment] 2020-01-22 13:09
As a reproducible counter-example (that this all works) here's the jetifier test suite, starts from scratch, imports all sorts of native modules (to test that jetify works on them...) and builds and runs. 

https://github.com/mikehardy/rn-androidx-demo/blob/master/make-demo.sh

Works?

https://travis-ci.com/mikehardy/jetifier/builds

**Comment by khat33b** [comment] 2020-01-22 14:15
@kelset @mikehardy Thanks for the quick response. I read the links which you had sent and we had already done that. The problem which I am facing is that `NativeModules` itself from `react-native` is not being resolved, not the custom module which I made.  This is happening when upgrading from 0.60.6 to 0.61.0 in both Android and iOS.

I am getting this error:
`Error: Unable to resolve module NativeModules from `src/utility/Utility.js`: NativeModules could not be found within the project.`

I shall make a sample project which mimics the behaviour and link it here.

**Comment by khat33b** [comment] 2020-01-23 10:27
I have been trying to mimic this behaviour on a fresh project and it seems that the problem was in trying to get `NativeModules` using `require` was the problem. When I changed the code to use `import`, it worked properly.

@kelset Perhaps this could be written into the Changelog asking people to stop using pre-ES6 features like `require` and `create-react-class` and use `import` instead.

**Comment by kelset** [comment] 2020-01-23 12:35
should we close this then?

**Comment by khat33b** [comment] 2020-01-24 06:15
Well, this is not really my bug report. If my solution solves the problems of all the others, then the issue can be closed.

**Comment by kelset** [comment] 2020-01-24 08:48
Let's ping @massoprod and hear from him then :)

**Comment by TheSavior** [comment] 2020-01-26 08:50
Based on this comment by @khat33b:
> Error: Unable to resolve module NativeModules from src/utility/Utility.js: NativeModules could not be found within the project.

I'd bet that you have a file `src/utility/Utility.js` that is doing this:

```
import NativeModules from 'NativeModules';
// or
const NativeModules = require('NativeModules');
```

This relies on Haste which has been removed as it is non standard. You should instead import these modules from React Native instead:

```
import {NativeModules} from 'react-native';
// or
const {NativeModules} = require('react-native');
```

**Comment by khat33b** [comment] 2020-01-27 05:57
@TheSavior This is exactly right. I had imported `NativeModules` using `require` but when I changed it to `import`, it worked perfectly. This process of refactoring should really be in the changelog and React blog of the 0.61 release as there are many people who don't know the internal workings of React Native and have to work with a lot of legacy code.

**Comment by TheSavior** [comment] 2020-01-27 06:14
The problem isn't converting from require to import, it's converting from trying to require the file directly, vs requiring it from the `react-native` package.

I agree this could, and should be better documented to make this migration more clear.

It looks like this info was mentioned in [a blog post in June 2019](https://facebook.github.io/react-native/blog/2019/06/12/react-native-open-source-update):
<img width="838" alt="Screen Shot 2020-01-26 at 10 11 43 PM" src="https://user-images.githubusercontent.com/249164/73153532-f9dd9600-4088-11ea-8478-5ed48e7a657d.png">

This probably should have been mentioned in a changelog with some code snippets though, not just this community update.

**Closed by TheSavior** 2020-01-27 06:14 UTC
Labels: Bug, Needs: Author Feedback, Needs: Repro
