### ISSUE TITLE
when onScrollEndDrag with DrawerLayoutAndroid , bug occurs

### ISSUE THREAD

**Issue by demonhunterunderdarkness** [facebook/react-native#12557] opened 2017-02-24 03:22 UTC
After Invoke onScrollEndDrag event and scrolltoend,BackAndroid listener doesn't listen to back button when DrawerLayoutAndroid opened and click back button.
If I use onPress with text as a external switch to drag scrollview instead of listening on onScrollEndDrag event,it works.it's wired!
Well, my version info:
react-native 0.41.0
anyone encounters this error? please give me a favor, thanks in advance~

**Comment by hramos** [comment] 2017-02-24 17:38
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-02-24 17:38 UTC
