### ISSUE TITLE
Android, RN 0.34 gif Image is not animated

### ISSUE THREAD

**Issue by wv1124** [facebook/react-native#10537] opened 2016-10-25 08:15 UTC
Android RN 0.34 gif Image is not animated
`<Image
                style={{width: WIDTH, height: WIDTH * 7 / 15}}
                source={{uri: 'http://img.1000.com/qm-a-img/prod/1225063/67490b157af9fe9433356d7b05d1b3b3.gif@480w_223h_1wh.gif'}}/>`

**Comment by leeight** [comment] 2016-10-25 13:53
How about the latest version?

**Comment by brien-crean** [comment] 2016-10-26 00:52
Have you tried adding `compile 'com.facebook.fresco:animated-gif:0.13.0'` to your dependencies in your app/build.gradle? I believe animated GIF was not part of core. Not sure if that has changed.

```
dependencies {
    compile 'com.facebook.react:react-native:+'
    compile 'com.facebook.fresco:animated-gif:0.13.0'
}
```

**Comment by hramos** [comment] 2016-10-26 01:13
Is this a regression? Did it use to work on RN 0.33 and it broke on 0.34? Does it work on 0.36, the latest stable?

In general we recommend filling out the template when filing new issues.

**Comment by npomfret** [comment] 2016-11-01 08:31
Hi.  I cannot remember if animated gifs used to work but they do not work in RN0.36.  However, as suggested I can confirm that adding `compile 'com.facebook.fresco:animated-gif:0.13.0'` to dependencies in app`build.gradle` does work.  I've tested on android 5.1.

**Comment by satya164** [comment] 2016-11-01 11:14
It is like this for several versions

**Comment by hramos** [comment] 2016-11-01 17:58
@brien-crean @satya164 can this issue be closed as "working as expected", e.g. is using Fresco the right approach here?

**Comment by npomfret** [comment] 2016-11-02 00:40
I think so - i've also tested an android 4.1 and it works.

**Comment by brien-crean** [comment] 2016-11-02 01:23
My earlier response was based off a SO where a RN core contributor said in their answer:

> We made the core library smaller by making things like GIF support optional.

So if that is still true then it sounds like it is working as expected for animated GIF support

Ref: http://stackoverflow.com/questions/38169519/how-to-display-gif-in-react-native-android-app

**Comment by ide** [comment] 2016-11-02 02:05
Closing this issue since it is intentional that GIFs do not animate by default on Android RN.

**Closed by ide** 2016-11-02 02:05 UTC
Labels: Needs more information

**Comment by alexhoo** [comment] 2016-11-28 14:52
react-native@0.37 
adding compile 'com.facebook.fresco:animated-gif:0.13.0' just not working... app crashes

**Comment by Sir-hennihau** [comment] 2017-09-01 17:46
Same issue as alexhoo here. When including 'compile 'com.facebook.fresco:animated-gif:1.3.0' in my build.gradle, the app just crashes before starting without displaying the red error screen.
RN 0.45.1

Any ideas?

**Comment by alexhoo** [comment] 2017-09-02 19:59
I ended up by using a different approach. I transform gif images into videos
