### ISSUE TITLE
Setting flex:1 on a ScrollView contentContainerStyle causes overlapping of components

### ISSUE THREAD

**Issue by david-a** [facebook/react-native#4099] opened 2015-11-12 14:28 UTC
I have a ScrollView with 2 subviews and I want the first of them (lets call it ViewA) to have {flex: 1} so the other one (ViewB) will stick to the bottom of the screen - but only if their total height is smaller that the screen. Of course that if they are higher than the screen I want it to scroll as usual.

So I set the ScrollView's `style` AND `contentContainerStyle` to be `flex: 1`. I Also set ViewA's `style` to `flex:1`. But when I do it, the ScrollView's contentContainer view is fixed to the screen height, thus not able to scroll if needed and even worse - ViewB overlaps ViewA.

If it's a bug - how to fix it?
If it's the expected behaviour - how can I achieve what I've described?

here's a little demonstration: https://rnplay.org/apps/wZgtWA
Note that even without ViewB, once you set flex:1 on contentContainerStyle you can't scroll the page.

Thanks.

**Comment by tyliuty** [comment] 2016-02-13 01:37
Try deleting ```flex: 1```?

**Comment by christopherdro** [comment] 2016-04-10 18:00
@david-a Did you ever get a chance to try @tyliuty suggestion?

**Comment by ashleydw** [comment] 2016-04-11 10:09
@christopherdro I have also been trying this for a while, previously I relied on the minHeight style that was removed in a later version.

I also want the same layout as @david-a (the inner view to stretch to fill if it doesn't, but otherwise continue scrolling); removing the `flex:1` from `contentContainerStyle` means the inner view doesn't fill.

**Comment by micheletedeschi** [comment] 2016-07-01 13:20
contentContainerStyle work for me! yeah!

**Comment by joelcloralt** [comment] 2016-07-05 08:14
I'm having this same issue. I need `flex:1` in the `contentContainerStyle` prop so that the inner view fills the ScrollView when the screen is larger. 

This is the layout I have:
```
<ScrollView style={styles.scrollView} contentContainerStyle={{flex:1}}>
  <View style={styles.container}>
    <View style={styles.bigContainer }>
      <Text>
        Lorem ipsum....//removing the long paragraph for this post
      </Text>
    </View>
    <View style={styles.footerContainer}>
      <Text >
        Cu odio ...
      </Text>
      <Button text="button" />
    </View>
  </View>
</ScrollView>
```

The styles are:
```
var styles = StyleSheet.create({
  scrollView:{
    flex:1,
    backgroundColor:'blue'
  },
  container: {
    flex:1,
    paddingTop:65,
    backgroundColor:'pink'
  },
  bigContainer: {
    flex:1,
    padding: 10,
    paddingTop:0
  },
  footerContainer: {
    justifyContent:'flex-end',
    backgroundColor:'yellow'
  },
});
```

These are the results when I add ` contentContainerStyle={{flex:1}}` to the scrollView.
On iPhone 4s, the bottom container is on top of the top container. I pulled the screen up to take the screenshot and show you how the top view is behind.
![simulator screen shot jul 5 2016 4 42 10 pm](https://cloud.githubusercontent.com/assets/881780/16577785/1aa4d53c-42d2-11e6-8abd-c1a08d91728a.png)

on Nexus 7, which is a big phone, it does what I want.  
![screenshot 2016-07-05 16 46 56](https://cloud.githubusercontent.com/assets/881780/16577895/b6884d58-42d2-11e6-8480-d70392686b8b.png)


Removing  ` contentContainerStyle={{flex:1}}`  prevents the content to expand the height of the scrollView for larger devices but scrolls correctly on smaller devices.

on iPhone 4s, the scroll is as expected (see the scrollbar on the side in the screenshot)
![simulator screen shot jul 5 2016 4 47 49 pm](https://cloud.githubusercontent.com/assets/881780/16577945/ec11abf4-42d2-11e6-9800-85c650440c9b.png)

on Nexus 7, you can see how the scrollview with blue background extends but the content does not. 
![screenshot 2016-07-05 16 47 27](https://cloud.githubusercontent.com/assets/881780/16577981/14487968-42d3-11e6-853b-1b2a23c13ec8.png)

@david-a, @ashleydw did you find a solution for this?

**Comment by satya164** [comment] 2016-07-05 10:15
> I'm having this same issue. I need flex:1 in the contentContainerStyle prop so that the inner view fills the ScrollView when the screen is larger.

I don't think that's possible right now using stylesheet. One thing you might try is getting the height of the scrollview and the inner element, and toggle the styles when inner element is bigger.

**Comment by satya164** [comment] 2016-07-05 10:16
Closing this since the original issue is the expected behaviour. Please file a feature request on [Product Pains](https://productpains.com/product/react-native) if you want `minHeight`.

**Closed by satya164** 2016-07-05 10:16 UTC

**Comment by joelcloralt** [comment] 2016-07-09 04:57
@satya164 as of RN 0.29.0 minHeight is supported. Just wanted to update everyone following this that setting `minHeight` as a style of the inner container seems to work. You can set the height to the device's height using `Dimensions`.

For reference: https://github.com/facebook/react-native/commit/78b892906b00932447e86465bec4613c118f01fc

**Comment by david-a** [comment] 2016-07-21 12:18
Cool @joelcloralt ! thanks, I'll try that!

**Comment by cubbuk** [comment] 2017-03-19 18:04
I had the similar problem and I solved it using `Dimensions` and `onLayout` property as following at least on Android, if there is a better or easier solution please let me know:

```
   onLayout(e) {
    const {nativeEvent: {layout: {height}}} = e;
    this.height = height;
    this.forceUpdate();
  }

render() {
    const {height: heightOfDeviceScreen} = Dimensions.get('window');
    return (
      <ScrollView contentContainerStyle={{minHeight: this.height || heightOfDeviceScreen}}
                  onLayout={this.onLayout.bind(this)}>
          <View><Text>header</Text></View>
          <View style{{flex: 1}}><Text>body</Text></View>
          <View><Text>footer</Text></View>
      </ScrollView>
```

Thanks

**Comment by rishabhpoddar** [comment] 2017-05-12 15:31
This problem is similar to what I had. See my answer here: http://stackoverflow.com/a/43912470/3867175

**Comment by tushar-singh** [comment] 2017-06-10 04:20
use `flexGrow: 1` instead of `flex: 1` – works like minheight, much like what you want.

**Comment by sarahmarciano** [comment] 2017-06-12 12:17
Thank you so much @tanguyantoine!! you saved my day!!

**Comment by tanguyantoine** [comment] 2017-06-12 23:02
@sarahmarciano You are welcome but why ?

**Comment by sarahmarciano** [comment] 2017-06-13 06:26
@tanguyantoine  Oh sorry for my mistake! I meant @tushar-singh :)

**Comment by sceext2** [comment] 2017-06-18 12:40
> use flexGrow: 1 instead of flex: 1 – works like minheight, much like what you want.

This works for me. Thank you !

**Comment by apurvajain** [comment] 2017-07-13 06:06
@tushar-singh Worked like a charm! Thanks 👍

**Comment by nishiltamboli** [comment] 2017-07-24 18:21
@tushar-singh Worked like charm! :+1:  Thanks. Have been dealing with this for quiet a long time now!

**Comment by narek11** [comment] 2017-07-25 21:52
@tushar-singh excellence

**Comment by ravirajn22** [comment] 2017-08-09 09:50
@tushar-singh even in my case ***flexGrow:1*** is working, But how come ***flex:1*** is not working which is nothing but short form of ***flexGrow:1,flexShrink:1,flexBasis:0***. Any one explain this pls.

**Comment by dungle1811** [comment] 2017-09-09 13:25
Hello guys,
I have a problem with **ScrollView**. I have used **ScrollView** which wrapped a **TabNavigator** (react-navigation). But when I did that, the content of each tab is hidden. I have tried to set **"flexGrow: 1"**, also **"flex: 1"** inside **contentContainerStyle** of **ScrollView**, the content of tag is showed, but **ScrollView** is not working. So if those content is long, I cannot see full of content.
Does anyone has the same problem like me?
I need help!

**Comment by luqiuyuan** [comment] 2017-10-07 15:16
@ravirajn22 Yes, flex: 1 is shorthand for flexGrow:1, flexShrink: 1, flexBasis:0. But in React Native, the default value of flexShrink is 0, which is different from browsers. So setting flexGrow: 1 only means flexGrow: 1, flexShrink: 0, flexBasis: 0

**Comment by luqiuyuan** [comment] 2017-10-07 15:41
@ravirajn22 Also, in React Native, flex does not work in the same way as CSS, according to its docs: https://facebook.github.io/react-native/docs/layout-props.html

**Comment by luqiuyuan** [comment] 2017-10-07 15:50
@ravirajn22 Also, on browsers, when you set only flex-grow: 1, you actually get flex-grow:1, flex-shrink:1, flex-basis:auto, since default value of flex-shrink is 1 and default value of flex-basis is auto
In React Native, when you set only flexGrow: 1, you actually get flexGrow:1, flexShrink:0 and flexBasis:'auto', since the default value of flexShrink seems to be 0

**Comment by Chathula** [comment] 2017-11-04 09:05
@dungle1811 , did you find an answer? i am also facing the same issue yet... if you found an answer tell it to me also..

**Comment by vishnukalakota** [comment] 2017-11-20 05:17
@tushar-singh Worked like charm! 👍 Thank you very much!!!

**Comment by Sorcer23** [comment] 2017-12-11 14:32
@Chathula I have found solution [here](https://github.com/facebook/react-native/issues/4099)

**Comment by vinicri** [comment] 2017-12-13 12:18
if `flexGrow` doesn't work for you, that's because the parent view must have `flex: 1` set

**Comment by MaxiSantos** [comment] 2017-12-16 02:15
@vinicri which of the container has to have the flewGrow ? The scrollView only? Or the inner containers too ?

**Comment by pallavbakshi** [comment] 2017-12-18 06:20
Solution as discussed above:
<ScrollView contentContainerStyle={{ flexGrow: 1 }}>
  <View style={{ flex: 1 }}>
    ...
  </View>
</ScrollView>

**Comment by ahmedraza11** [comment] 2017-12-28 16:05
Use` flexGrow:1 `its works for me...

**Comment by sami718** [comment] 2018-02-06 07:32
@dungle1811 I am facing the same issue. Please provide any solution for this

**Comment by rendomnet** [comment] 2018-05-08 09:51
flexGrow: 1 is not working anymore?

**Comment by hielfx** [comment] 2018-06-05 11:03
@rendomnet this is working for me: `<ScrollView horizontal={true} style={{ flex: 1, flexGrow: 1 }} contentContainerStyle={{ flex: 1 }}>` without the `contentContainerStyle` does not work for me
