### ISSUE TITLE
Confusion in importing.

### ISSUE THREAD

**Issue by iegik** [facebook/react-native#15743] opened 2017-09-01 14:59 UTC
`#import <React/RCTDefines.h>` or `#import "RCTDefines.h"` ?

in https://github.com/facebook/react-native/tree/0.47-stable/React/Base there is lot of files with wrong import path!

Relative to https://github.com/facebook/react-native/releases/tag/v0.40.0 , imports shold now be with prefix `<React/*` but, there is lot of file moving around the project.

I do not know how to do that in Objective-C, but it can be done by creating interface for different part of library:

pseudocode:
```
// React
#export "React"
#export "Defines" from "React/Some/Path"

// Some module
#import "Defines" from "React"
```

https://pbs.twimg.com/media/C10C0MNXAAAbo5E.jpg:large

**Comment by iegik** [comment] 2017-09-01 15:17
> @javache Move all header imports to "<React/..>" e1577df
 - Something gone wrong...

**Comment by iegik** [comment] 2017-09-01 15:20
I mean, now files moved from `React/` to `React/Base`

**Comment by iegik** [comment] 2017-09-01 15:24
@mmmulani Please, review again

**Comment by iegik** [comment] 2017-09-01 15:46
I was wrong, changing **Header Search Paths" to following, fixes the issues^
```
$(BUILT_PRODUCTS_DIR)/usr/local/include
```

**Comment by iegik** [comment] 2017-09-01 16:08
How to resolve that?:
```
'React/RCTBridgeDelegate.h' file not found
```

**Comment by hramos** [comment] 2017-09-01 16:33
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue that meets the requirements set forth in the template. Thanks!

**Closed by hramos** 2017-09-01 16:33 UTC
