### ISSUE TITLE
Expected ')' in RCTProfile.m in reactnative

### ISSUE THREAD

**Issue by mohammed1955** [facebook/react-native#13020] opened 2017-03-19 22:10 UTC
I am running react-native project in xcode(7.3.1)  and this is the error I am getting
<img width="1152" alt="screen shot 1395-12-30 at 01 38 13" src="https://cloud.githubusercontent.com/assets/15388226/24085268/f1120346-0d0d-11e7-81d1-e5f4fd9949cc.png">
What's solution !!!!!

**Comment by hi-bazinga** [comment] 2017-03-20 06:28
@mohammed1955 I just downgraded the react-native from 0.42.3 to 0.38.0 and the problem solved.

**Comment by hramos** [comment] 2017-03-20 16:32
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-03-20 16:32 UTC

**Comment by olivierIllogika** [comment] 2017-04-01 17:20
For the sake of documenting this issue further and helping others stumbling here for answers, this is caused by the following commit: https://github.com/facebook/react-native/commit/453e70d19c28b56dfcecfe205ccd4ccad2b33009

React native version: 0.42.3
Platform: iOS
Dev system: MacOS
Dev tools: Xcode 7.3.1, iOS target 8.0

Updating Xcode to 8+ should fix this. Workaround if you want to stick to Xcode 7 is to replace
  `UIActivityType activityType`
with
  `NSString * __nullable activityType`

Related error : incompatible block pointer types assigning to 'UIActivityViewControllerCompletionWithItemsHandler _Nullable'
