### ISSUE TITLE
react-native: 0.47.2 ini application is not working

### ISSUE THREAD

**Issue by afattahi54** [facebook/react-native#15613] opened 2017-08-23 04:30 UTC
We are using:
react-native-cli: 2.0.1
react-native: 0.47.2
node: v8.4.0
npm: 4.6.1
windows 10
running the default  app on android emulator device fails. 

```

Bundling `index.android.js`  [development, non-minified, hmr disabled]  0.0% (0/1), failed.
error: bundling failed: "Cannot find entry file index.android.js in any of the roots: [\"E:\\\\SampleProjects\\\\AwesomeProjectNewVersion\"]"
```

It was working before [on react-native ( 0.47.1 ) ]

**Comment by pocesar** [comment] 2017-08-23 05:21
try `npm run start -- --reset-cache`

**Comment by afattahi54** [comment] 2017-08-23 09:31
same error again

**Comment by iegik** [comment] 2017-08-23 15:17
Check Gradle

distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-bin.zip

**Comment by hramos** [comment] 2017-08-23 19:18
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-08-23 19:18 UTC
