### ISSUE TITLE
Can't run-android

### ISSUE THREAD

**Issue by almikurniawan** [facebook/react-native#24973] opened 2019-05-21 01:08 UTC
react-native info 
info
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
      Memory: 4.87 GB / 7.89 GB
    Binaries:
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.5429.30.34.5452501
node -v = v12.2.0

$ adb devices
* daemon not running; starting now at tcp:5037
* daemon started successfully
List of devices attached
4de8ae18        device

$ react-native run-android
info Starting JS server...
info Building and installing the app on the device (cd android && gradlew.bat app:installDebug)...
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error spawnSync gradlew.bat ENOENT. Run CLI with --verbose flag for more details.

iam new in react-native, i try to install by the doc https://facebook.github.io/react-native/docs/getting-started. but i got an error when i run on android device.  what i can do to run on android device?

**Comment by Taym95** [comment] 2019-05-21 13:34
I don't think it's an RN bug, the issue is with your setup, `Make sure you have an Android emulator running or a device connected` and Run `react-native run-android` command with `--verbose` to show more details!

**Comment by almikurniawan** [comment] 2019-05-22 02:57
i use android device and i check with command adb devices my devices is connected,
$ adb devices

daemon not running; starting now at tcp:5037
daemon started successfully
List of devices attached
4de8ae18 device

then downgrade node to 6.4.1 version and npm version 3.x.x and install react native version 0.55 it work in same devices, but not work for react native 0.59 and node 12.

**Comment by guhungry** [comment] 2019-05-22 11:38
So this is old project right. Did you upgrade properly?

It quite tricky to upgrade cross many versions https://github.com/react-native-community/rn-diff-purge/compare/release/0.55.0..release/0.59.8

**Comment by almikurniawan** [comment] 2019-05-24 04:22
no this is create new project.

**Comment by ptrocki** [comment] 2019-05-24 12:23
Did you type `adb -s _device_name_ reverse tcp:8081 tcp:8081`

**Comment by almikurniawan** [comment] 2019-05-24 12:37
Yes i run the command before. Thanks all, i use old react version and work. Next time, i try to use new react version.

**Comment by Taym95** [comment] 2019-05-27 07:25
@almikurniawan If it works can you close this issue?

**Closed** 2019-05-27 07:32 UTC
Labels: Bug, Platform: Android
