### ISSUE TITLE
Hot reloading doesn't working with NavigationExperimental

### ISSUE THREAD

**Issue by wellyshen** [facebook/react-native#12093] opened 2017-01-27 10:29 UTC
I use the NavigationCardStack of the NavigationExperimental to control my scene and header, however when I change the title of the header, which from the NavigationHeader.title component but nothing is updated on the iOS simulator (the code as below).

By the way, if I change a text out of the render component of the NavigationCardStack (e.g. simple put a <Text>Hello</Text> in a render function), which works as normal. Does the NavigationExperimental support hot reloading?

```javascript
  // ...

  renderHeader = sceneProps => (
    <NavigationHeader
      {...sceneProps}
      renderTitleComponent={() => (
        <NavigationHeader.Title>{'Test'}</NavigationHeader.Title>  // I change the title here
      )}
    />
  );

  // ...
```

* React Native version: 0.40
* Platform: iOS simulator
* Operating System: MacOS 10.12.2

**Comment by ericvicenti** [comment] 2017-01-27 18:46
By design, some aspects of NavigationExperimental will cache the state of your routes. You can change the initial routes, but with hot loading there are already routes there. So you need to reload to get the initial routes again.

I'm closing this as a non-issue. Reloading is ok for cases where the state changes.

**Closed by ericvicenti** 2017-01-27 18:46 UTC
