### ISSUE TITLE
Can't leverage npm scripts to run react-native commands

### ISSUE THREAD

**Issue by olivierlesnicki** [facebook/react-native#4754] opened 2015-12-13 10:27 UTC
I have a script defined in my package json that includes a react-native command.
Running it fails and yields the following output:

```
$ npm run build-ios

> editor@0.0.1 build-ios /editor
> rm -rf $TMPDIR/react-* && react-native bundle --entry-file index.ios.js --platform ios --bundle-output ios/main.jsbundle

Looks like you installed react-native globally, maybe you meant react-native-cli?
To fix the issue, run:
npm uninstall -g react-native
npm install -g react-native-cli
```

Running the proposed commands doesn't solve the issue though.

**Comment by mroswald** [comment] 2015-12-13 12:13
do have have react-native installed globally as the message said? it's not necessary to install it globally. instead install react-native-cli using -g

**Comment by olivierlesnicki** [comment] 2015-12-13 13:52
I actually don't! And before posting the issue I've actually attempted to uninstall `react-native` globally. But npm couldn't find it anyway.

**Comment by satya164** [comment] 2015-12-13 16:47
Duplicate of #4515

**Closed by satya164** 2015-12-13 16:47 UTC
