### ISSUE TITLE
new asset system doesn't work in windows.

### ISSUE THREAD

**Issue by inithink** [facebook/react-native#3980] opened 2015-11-08 08:53 UTC
I tried to present just an image in windows 10.

I added an image in my project directory -> ./image/base.png

With the render function below:

    <View style={styles.container}>
        <Image
        style={{width:80, height:80}}
        source={require('./image/base.png')}
		/>
    </View>

I can't see any image with it.

I tried in OS X, it works well.

**Comment by liesislukas** [comment] 2015-11-08 18:29
I've tried it on windows 10, 64bit. If path is not correct - shows error 

![image](https://cloud.githubusercontent.com/assets/2733862/11021749/bca9251c-8654-11e5-9527-53becfd8654b.png)

If path is correct - just empty space is displayed. 

I've tried to make signed apk. Build was successful, but pictures are not included. It's way too small ~7Mb from ~450Mb. My app has ~600-700 images.

**Comment by marsprince** [comment] 2015-11-09 04:43
I got same in this issues https://github.com/facebook/react-native/issues/3943#issuecomment-154919426.

You can use uri to work,I think it's a bug.

**Comment by malinthe** [comment] 2015-11-12 16:07
This worked for me on Windows 10: https://github.com/facebook/react-native/issues/4010#issuecomment-155334530

**Comment by mkonicek** [comment] 2015-11-17 14:53
In general, can you please report this on Product Pains and vote on it to help us prioritize?
https://productpains.com/product/react-native

Seems like an easy thing to fix - can you send a pull request?

**Comment by WoLfulus** [comment] 2015-11-19 05:12
See
https://github.com/facebook/react-native/issues/4207

**Comment by anderdb** [comment] 2015-12-01 23:00
I submitted pull request https://github.com/facebook/react-native/pull/4416 to fix this.  The problem is that the existing code uses the path module to generate the URL for assets.  On Windows, that means you have back slashes in the URL when you need forward slashes.  My fix just replaces these when necessary.

**Comment by anderdb** [comment] 2015-12-13 16:30
My pull request has been accepted and merged into master.

**Comment by mkonicek** [comment] 2015-12-18 14:23
yay! :rocket:

**Comment by mkonicek** [comment] 2015-12-18 14:24
The fix is in 0.17.0-rc go out in 0.17.0 later today. Closing.

**Closed by mkonicek** 2015-12-18 14:24 UTC
Labels: Community Responsibility, Windows
