### ISSUE TITLE
RCTLinkingManager: Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)

### ISSUE THREAD

**Issue by tpisto** [facebook/react-native#21071] opened 2018-09-12 13:28 UTC
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: macOS Sierra 10.12.6
      Memory: 6.48 GB / 32.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.1 - ~/.nvm/versions/node/v8.11.1/bin/node
      Yarn: 1.9.4 - ~/.yarn/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.2, macOS 10.13, tvOS 11.2, watchOS 4.2
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.0 => 0.57.0

## Description

After upgrading from React Native 0.55 to 0.57 and trying to compile the compile fails with 
"Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)"
Screenshot: https://cl.ly/af7f38877e19

**Comment by PublicParadise** [comment] 2018-09-12 13:31
## Suggested fix 

### RCTLinkingManager.h
```objective-c
/**
 * Copyright (c) 2015-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#import <UIKit/UIKit.h>

#import <React/RCTEventEmitter.h>

@interface RCTLinkingManager : RCTEventEmitter

+ (BOOL)application:(nullable UIApplication *)app
            openURL:(nullable NSURL *)URL
            options:(nullable NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options;

+ (BOOL)application:(nullable UIApplication *)application
            openURL:(nullable NSURL *)URL
  sourceApplication:(nullable NSString *)sourceApplication
         annotation:(nullable id)annotation;

+ (BOOL)application:(nullable UIApplication *)application
continueUserActivity:(nullable NSUserActivity *)userActivity
  restorationHandler:(nullable void (^)(NSArray * __nullable))restorationHandler;

@end
```

**Comment by tpisto** [comment] 2018-09-12 13:34
@PublicParadise Wow, wonderful, works! Thank you for super quick answer 🎉

**Comment by thomas-gilbert** [comment] 2018-09-13 13:33
This looks like a duplicate of https://github.com/facebook/react-native/issues/20797. There is a PR open here https://github.com/facebook/react-native/pull/20798

**Comment by tobbbe** [comment] 2018-09-18 16:07
`react-native link` solved it for me

**Comment by bdrobinson** [comment] 2018-09-19 08:41
For anyone looking for a workaround – if you're able to upgrade to xcode > 9.2 then that will also fix the problem (credit [here](https://github.com/facebook/react-native/pull/20798#issuecomment-422641275)).

**Comment by radko93** [comment] 2018-09-19 19:03
A temporary workaround if you're not able to update Xcode - use patch-package https://www.npmjs.com/package/patch-package

**Comment by tpisto** [comment] 2018-09-26 12:41
> I have same issue how solve this? `react-native link` don't work

Hi! Seems the latest release 0.57.1 fixes this issue.

**Comment by radko93** [comment] 2018-09-26 15:04
This is solved, please ping me if you have any other problems with this.

**Closed by radko93** 2018-09-26 15:04 UTC
Labels: :large_blue_diamond:iOS

**Comment by leotm** [comment] 2019-03-27 11:36
This has cropped up again with XCode Version 10.2 (10E125).

I fixed it manually at first with `_Nonnull` assertions at first, `nullable`'s work for me too.

**Comment by digitaldavenyc** [comment] 2019-03-29 02:01
+1 

This issue seems to have popped up right after upgrading to XCode 10.2

**Comment by khizar** [comment] 2019-04-03 20:35
I can confirm it, I ran into this after upgrading to 10.2 :(

**Comment by cemarguvanli** [comment] 2019-04-03 23:13
`nullable` works for me too.

**Comment by maamounapprise** [comment] 2019-04-10 15:04
still an issue for me, with latest xcode 10.2 - rn 0.57

**Comment by komaldeep** [comment] 2019-04-14 19:24
I am still facing the issue with react-native 0.57.0

**Comment by lamtan92** [comment] 2019-04-15 03:46
Same issue when I upgrading to Xcode 10.2,
I'm using react-native 0.57.0 @radko93

**Comment by EJohnF** [comment] 2019-04-24 07:59
seems we will be unnoticed here... I also met it after upgrading to xCode 10.2

**Comment by talyh** [comment] 2019-04-29 18:21
@radko93  - wondering if we can reopen this for XCode 10.2, or if a new issue should be filed.

**Comment by ericlewis** [comment] 2019-04-29 18:29
For the commenters above: the fix is to use the latest version of RN, which doesn't appear to have this issue. Otherwise, patch RCTLinking.

**Comment by talyh** [comment] 2019-04-29 20:21
@ericlewis - Can you elaborate on what you mean with "patch RCTLinking"?

I've tried @PublicParadise's suggested change, which got rid of that problem, only to throw "React/RCTEventEmitter.h' file not found". Looking up that issue, gets me back to this one, so I feel like I'm going in circles trying to fix this on my own.

**Comment by Viktor19931** [comment] 2019-04-30 13:27
@PublicParadise thanks! works like charm )
