### ISSUE TITLE
[Android][v0.72.1] New Arch can't work without Fabric

### ISSUE THREAD

**Issue by birdofpreyru** [facebook/react-native#38186] opened 2023-07-04 20:51 UTC
### Description

With RN@0.71.x I was able to opt-in for using new arch with disabled fabric. With RN@0.72.x if I do so, I get the error `EventEmitter#receiveTouches is not supported by Fabric Interop Layer` the first time I touch the screen. Not sure, is it a bug, or just not supported scenario since v0.72.0?

### React Native Version

v0.72.1

### Output of `npx react-native info`

System:
  OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
  CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Memory: 3.35 GB / 11.58 GB
  Shell:
    version: 5.1.16
    path: /bin/bash
Binaries:
  Node:
    version: 18.16.1
    path: ~/.nvm/versions/node/v18.16.1/bin/node
  Yarn: Not Found
  npm:
    version: 9.5.1
    path: ~/.nvm/versions/node/v18.16.1/bin/npm
  Watchman:
    version: 20230101.175141.0
    path: /usr/local/bin/watchman
SDKs:
  Android SDK:
    API Levels:
      - "33"
    Build Tools:
      - 30.0.3
      - 33.0.0
      - 33.0.2
    System Images:
      - android-33 | Google APIs ARM 64 v8a
      - android-33 | Google APIs Intel x86_64 Atom
      - android-33 | Google Play ARM 64 v8a
      - android-33 | Google Play Intel x86 Atom_64
    Android NDK: Not Found
IDEs:
  Android Studio: Not Found
Languages:
  Java:
    version: 11.0.19
    path: /usr/bin/javac
  Ruby:
    version: 3.0.2
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.1
    wanted: 0.72.1
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

Init a new project with `npx react-native@latest init AwesomeProject`. Set `newArchEnabled=true` in `/android/gradle.properties`; in `android/app/src/main/java/com/awesomeproject/MainActivity.java` replace `DefaultNewArchitectureEntryPoint.getFabricEnabled()` by `false`. Deploy the app to Android in dev mode, touch the screen, see the error.

### Snack, code example, screenshot, or link to a repository

N/A

**Comment by ugurdalkiran** [comment] 2023-07-05 06:15
You should also add these 2 lines.

**android/app/build.gradle**
```
buildTypes {
    debug {
        signingConfig signingConfigs.debug
        buildConfigField("boolean", "IS_NEW_ARCHITECTURE_ENABLED", "false")
    }
    release {
        // Caution! In production, you need to generate your own keystore file.
        // see https://reactnative.dev/docs/signed-apk-android.
        signingConfig signingConfigs.debug
        minifyEnabled enableProguardInReleaseBuilds
        proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        buildConfigField("boolean", "IS_NEW_ARCHITECTURE_ENABLED", "false")
    }
}
```

**buildConfigField("boolean", "IS_NEW_ARCHITECTURE_ENABLED", "false")**

**Comment by birdofpreyru** [comment] 2023-07-05 10:47
Hmm... I am not sure, in my project I had an explicit definition of `IS_NEW_ARCHITECTURE_ENABLED` in Gradle config up to a few months ago, while on RN@0.70.x. Even then it read `buildConfigField "boolean", "IS_NEW_ARCHITECTURE_ENABLED", isNewArchitectureEnabled().toString()`, so I believe it was `true` with enabled new arch, and it worked. Then I removed such explicit definition when upgraded to RN@0.71.x, and it worked fine. I guess defining it as `false` will just disable new arch (in its turbo modules part) altogether, isn't it?

**Comment by cortinico** [comment] 2023-07-05 12:05
> Init a new project with `npx react-native@latest init AwesomeProject`. Set `newArchEnabled=true` in `/android/gradle.properties`; in `android/app/src/main/java/com/awesomeproject/MainActivity.java` replace `DefaultNewArchitectureEntryPoint.getFabricEnabled()` by `false`. Deploy the app to Android in dev mode, touch the screen, see the error.

I've just tested on a blank project, applied the suggested changes you mentioned, and everything is working fine for me.

@ugurdalkiran your suggestions is incorred

@birdofpreyru can you provide a reproducer of what you did? You can use this template:
https://github.com/react-native-community/reproducer-react-native

**Comment by birdofpreyru** [comment] 2023-07-05 12:34
@cortinico Ogh... I am having a really bad luck in reporting reproduceable problems in last days :sweat_smile: 

I really did the same what you did &mdash; blank project, those two changes, then running on a real device with `npm start` for dev server, `npm run android`. Ubuntu as the build host, but it should be irrelevant here, I guess. Just in case, here is the archive of my project, minus "node_modules" folder:
https://drive.google.com/file/d/1KtwrFHSNC5FpCy_WKh1t9PDMCEHzLJtD/view?usp=sharing

And here is the error screenshot:
![Screenshot_20230705-143425_AwesomeProject](https://github.com/facebook/react-native/assets/20144632/bc8cc1e4-903e-48d8-9b83-ff0f5d4c6a5a)

**Comment by ugurdalkiran** [comment] 2023-07-05 13:29
@cortinico 

My suggestion is to disable "fabric" completely. This works for me.

For example https://github.com/invertase/react-native-google-mobile-ads the banner ad of this package is not shown with fabric enabled. That's why I can show it by disabling fabric as I said. I thought the request was something like this. Sorry if I'm wrong.

**Comment by birdofpreyru** [comment] 2023-07-05 13:46
@ugurdalkiran perhaps you should take a moment to read https://reactnative.dev/docs/the-new-architecture/landing-page. _Fabric_ is just one of three pillars of the new architecture, which is indeed not supported by many packages yet, google-mobile-ads included. The other two pillars, however, _Turbo Modules_, and _Codegen_ do not cause issues with older modules, and thus can be used already, without _Fabric_. Hence my question. What you suggest, sounds just like using old architecture, thus without any benefits added by _Turbo Modules_.

**Comment by cortinico** [comment] 2023-07-06 11:36
@birdofpreyru I've just tested your reproducer, and the app is fine. I'm able to open the app without any errors.

You most likely have some local build artifacts so I would suggest you to clean your environment.

@ugurdalkiran the correct way to turn off the New Architecture is to use the `newArchEnabled=false` flag in your `android/gradle.properties` file. The other snippets you suggested are not correct, and I would advice against using them as they might work now, but they'll most likely break in future updates.

**Comment by birdofpreyru** [comment] 2023-07-06 13:41
@cortinico No way, look, I have just installed the Android build environment on my macOS machine &mdash; totally fresh, it never had Android SDK, nor even Java installed before; then I created a blank project, did those two changes, build & deployed to my Android device and got the same error.

Before that, I was thinking maybe you test on Emulator, and thus it works for you; did a test on Android Emulator, on my Ubuntu machine &mdash; still having the same issue.

Probably some local build artifacts on your machine let it work?

**Comment by birdofpreyru** [comment] 2023-07-06 13:50
I would suggest another possibility, that the problem may occur only on older Android versions (my test Android device is Samsung Galaxy S9+, running Android 10); but the Emulator I tried it with was running Android 13.

**Comment by cortinico** [comment] 2023-07-06 14:54
@birdofpreyru don't you mind using this template https://github.com/react-native-community/reproducer-react-native and create a Github Project with the same code you linked so we're sure we're looking at the same thing? Plus that template has CI configured so it allows to grab an .apk from a clean environment

**Comment by cortinico** [comment] 2023-07-06 17:43
Thanks for the repro @birdofpreyru 

The problem will be fixed if you update this file:
https://github.com/birdofpreyru/RN-issue-38186/blob/8e53939cf12e8e130b89b64593329740bf8f1c23/ReproducerApp/android/app/src/main/java/com/reproducerapp/MainApplication.java#L58

as follows:

```diff
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
      // If you opted-in for the New Architecture, we load the native entry point for this app.
-     DefaultNewArchitectureEntryPoint.load();
+     DefaultNewArchitectureEntryPoint.load(true, false);
    }
```

You can find more documentation on what those parameters control here:
https://github.com/facebook/react-native/blob/e22bd7f6a969321607246e64c9b4e96ef9265fb1/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/defaults/DefaultNewArchitectureEntryPoint.kt#L27-L31

**Closed by cortinico** 2023-07-06 17:43 UTC
Labels: Platform: Android, Needs: Repro, Needs: Attention, Type: New Architecture

**Comment by birdofpreyru** [comment] 2023-07-06 17:48
Thanks!
