### ISSUE TITLE
Some feature suggestion about react-native-template module

### ISSUE THREAD

**Issue by windy** [facebook/react-native#13954] opened 2017-05-13 07:57 UTC
We have developed a  react native template named [react-native-template-mobx](https://github.com/80percent/react-native-template-mobx) based on [this work](https://github.com/facebook/react-native/commit/17c175a149bc410a9b167b31f13474d8c6e9832c#diff-e1bddafdbb592817072925c6b7aabcd2)

It works well. But we also found some improvement about this template, here is my advise:

First. support dev npm package install

there is no way to support install a dev package at now. I think we can add a section of dependencies.json or provide a new dependencies_dev.json to deal this.

Second. cannot install package in dependencies.json  at local file mode( using file:// )

this is a bug.

Third. provide a way to ignore some files in template.

At now we only copy all files in template package to our new project, but I want to control some files( e.g. description file and description image ) to be ignored.

we should provide a way to control it.

**Comment by hramos** [comment] 2017-05-15 18:55
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-05-15 18:55 UTC

**Comment by windy** [comment] 2017-05-16 01:35
@hramos hi, After read the link you just provide I had posted a feature request about react native template at this [link](https://react-native.canny.io/feature-requests/p/some-improvement-for-react-native-template-feature)
