### ISSUE TITLE
EXC_CORPSE_NOTIFY iOS crash when using native modules

### ISSUE THREAD

**Issue by getaaron** [facebook/react-native#19107] opened 2018-05-02 19:18 UTC
- [X] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [X] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [X] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

The app intermittently crashes when resolving or rejecting a promise in a native module. Possibly related to https://github.com/facebook/react-native/issues/5011.

This reproduces with several native modules so I don't think it's related to a specific module.

## Environment

```
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.5.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.3
  react-native: 0.55.0 => 0.55.0
```

## Steps to Reproduce
1. Create a simple Native Module
2. Use it

## Expected Behavior
I expect the data to flow back and forth as documented.

## Actual Behavior
The app intermittently crashes with what looks like a memory issue.

From my observation I _think_ it happens when resolving or rejecting a promise from Objective-C.

Here's a screenshot from the crash organizer. Note that the crash occurred on thread 10, not the main thread:

![image](https://user-images.githubusercontent.com/789577/39544233-6df0edba-4e1b-11e8-88fd-365ea6e5fec5.png)

So it looks like it's somewhere in this code:

https://github.com/facebook/react-native/blob/26684cf3adf4094eb6c405d345a75bf8c7c0bf88/React/CxxModule/RCTNativeModule.mm#L86-L115

I see that code can throw this exception:

> Exception '%@' was thrown while invoking %s on target %@ with params %@\ncallstack: %@",
                         exception

But I don't see that error anywhere in the crash log so I'm not sure where to find it. I'm not sure if this was the actual exception, since the crash report says `EXC_CORPSE_NOTIFY` so it may be a red herring

**Comment by getaaron** [comment] 2018-05-02 19:41
CC @philikon @mkonicek @bfarrgaynor @tadeuzagallo

**Comment by getaaron** [comment] 2018-05-03 21:05
I was just able to reproduce what I think is the same issue in the simulator by pressing <kbd>⌘R</kbd> a few times:

![image](https://user-images.githubusercontent.com/789577/39602652-caecf6e8-4ef3-11e8-9fa2-36486e91e4ea.png)

Interestingly, the stack trace is identical, but this says `EXC_BAD_ACCESS` vs. `EXC_CORPSE_NOTIFY`. I wonder if the difference is because the former is a debug build but the latter is a release build.

I tried to inspect some of the variables in lldb, but then Xcode crashed 🙄

**Comment by getaaron** [comment] 2018-08-01 21:59
Issue still persists in 0.56

**Comment by JimBTek** [comment] 2018-09-21 21:37
seems like we are seeing this:

```
OS Version:          iPhone OS 11.2 (15C114)
Baseband Version:    6.30.04
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  21

Application Specific Information:
abort() called

Filtered syslog:
None found
```


```
Thread 21 name:  Dispatch queue: com.facebook.react.ExceptionsManagerQueue
Thread 21 Crashed:
0   libsystem_kernel.dylib        	0x00000001824282e8 __pthread_kill + 8
1   libsystem_pthread.dylib       	0x000000018253d2f8 pthread_kill$VARIANT$mp + 396
2   libsystem_c.dylib             	0x0000000182396fbc abort + 140
3   libc++abi.dylib               	0x0000000181b33068 __cxa_bad_cast + 0
4   libc++abi.dylib               	0x0000000181b33210 default_unexpected_handler+ 8720 () + 0
5   libobjc.A.dylib               	0x0000000181b5c810 _objc_terminate+ 34832 () + 124
6   TechApp Beta                  	0x000000010124e6ec 0x1011f0000 + 386796
7   libc++abi.dylib               	0x0000000181b4b54c std::__terminate(void (*)+ 107852 ()) + 16
8   libc++abi.dylib               	0x0000000181b4aea8 __cxxabiv1::exception_cleanup_func+ 106152 (_Unwind_Reason_Code, _Unwind_Exception*) + 0
9   libobjc.A.dylib               	0x0000000181b5c65c _objc_exception_destructor+ 34396 (void*) + 0
10  TechApp Beta                  	0x00000001012d9560 0x1011f0000 + 955744
11  TechApp Beta                  	0x00000001012d90a8 0x1011f0000 + 954536
12  libdispatch.dylib             	0x0000000182292a54 _dispatch_call_block_and_release + 24
13  libdispatch.dylib             	0x0000000182292a14 _dispatch_client_callout + 16
14  libdispatch.dylib             	0x000000018229c96c _dispatch_queue_serial_drain$VARIANT$mp + 528
15  libdispatch.dylib             	0x000000018229d2fc _dispatch_queue_invoke$VARIANT$mp + 340
16  libdispatch.dylib             	0x000000018229dd20 _dispatch_root_queue_drain_deferred_wlh$VARIANT$mp + 404
17  libdispatch.dylib             	0x00000001822a603c _dispatch_workloop_worker_thread$VARIANT$mp + 644
18  libsystem_pthread.dylib       	0x000000018253af1c _pthread_wqthread + 932
19  libsystem_pthread.dylib       	0x000000018253ab6c start_wqthread + 4
```

**Comment by 471685249** [comment] 2018-09-27 09:30
+1

**Comment by Mubashirkhan** [comment] 2018-10-23 14:42
has some one fixed this issue ??????

**Comment by haiau** [comment] 2018-11-08 17:06
In my case, when Release I got a message like:
... Thread 1 name: Dispatch queue: com.facebook.react.ExceptionsManagerQueue Thread 1 Crashed: ...
This bug prevented me from submitting my app to AppStore
Then I test all cases, and read the code carefully, I found that there is the getter in an undefined object.
So maybe there are some bugs in JS code and it causes crashes.

**Comment by isaaclem** [comment] 2019-02-22 02:58
I'm still hitting this issue in 0.58.4, crashing in release mode but working fine in debug mode
```
 React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 30.79 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.15.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.58.4 => 0.58.4
    npmGlobalPackages:
      react-native-cli: 2.0.1
```
```
Thread 8 name:  Dispatch queue: com.facebook.react.ExceptionsManagerQueue
Thread 8 Crashed:
0   libsystem_kernel.dylib        	0x00000001a2bc7104 __pthread_kill + 8
1   libsystem_pthread.dylib       	0x00000001a2c47948 pthread_kill$VARIANT$armv81 + 296
2   libsystem_c.dylib             	0x00000001a2b1ed78 abort + 140
3   libc++abi.dylib               	0x00000001a21e8f78 __cxa_bad_cast + 0
4   libc++abi.dylib               	0x00000001a21e9120 default_unexpected_handler+ 8480 () + 0
5   libobjc.A.dylib               	0x00000001a2201e58 _objc_terminate+ 28248 () + 124
6   libc++abi.dylib               	0x00000001a21f50fc std::__terminate(void (*)+ 57596 ()) + 16
7   libc++abi.dylib               	0x00000001a21f5188 std::terminate+ 57736 () + 84
8   libdispatch.dylib             	0x00000001a2a6a498 _dispatch_client_callout + 36
9   libdispatch.dylib             	0x00000001a2a44fa0 _dispatch_lane_serial_drain$VARIANT$armv81 + 548
10  libdispatch.dylib             	0x00000001a2a45ae4 _dispatch_lane_invoke$VARIANT$armv81 + 412
11  libdispatch.dylib             	0x00000001a2a4df04 _dispatch_workloop_worker_thread + 584
12  libsystem_pthread.dylib       	0x00000001a2c4d0dc _pthread_wqthread + 312
13  libsystem_pthread.dylib       	0x00000001a2c4fcec start_wqthread + 4
```

**Comment by grabbou** [comment] 2019-03-19 12:45
Hello there 👋 this issue doesn't have a repro (which means, a react-native init-ed project with the minimal changes that leads to creating the same issue you are reporting). 

Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code. We need a exact code of a native module and the payload that is causing issue, otherwise it's hard.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗

**Closed by grabbou** 2019-03-19 12:45 UTC
Labels: Platform: iOS, Type: Bug Report

**Comment by getaaron** [comment] 2019-03-19 13:04
My original report filed almost a year ago included steps to reproduce. Lots of people have commented that they reproduced it. Did you try it?

**Comment by kuzkokov** [comment] 2019-03-26 07:42
Same here

**Comment by JimBTek** [comment] 2019-03-26 14:05
@getaaron  we noticed crashes when we were heavily downloading data across multiple threads and eating up both cpu and storage I/O and iOS kills the app. The only way to find that the device was killing the app (vs. the app crashing) was to plug in the iPad and pull logs from the device directly vs. with xCode.  We sorted this out when no crash reports were showing up in App Center, because the app was getting force quit, not crashing. We had to better handle our data downloads and sequence them, downloading ~200 MB of data on first login (offline first corporate app).

I'm kind of noob though and we have had a variety of problems so YMMV.

**Comment by solixmedia** [comment] 2019-05-23 20:01
@getaaron Did you ever find a solution? My crash report looks similar to yours. App worked fine in build mode and in 3 different devices but crashed on appstore review.

**Comment by getaaron** [comment] 2019-05-24 12:08
@solixmedia We rewrote the app in Swift and got rid of React Native.

**Comment by solixmedia** [comment] 2019-05-25 00:35
@getaaron Thanks for replying. Kind of discouraging to hear.

**Comment by solixmedia** [comment] 2019-05-25 00:36
@getaaron Thanks for replying. Kind of discouraging to hear.

**Comment by ThomasStubbe** [comment] 2019-08-22 10:41
We're having the same issue in React Native 59.9
It only crashes in production. 
It doesn't always crash. 
It crashes without doing anything (just starting the app and waiting).
It crashes after 3-10 seconds
We don't download heavy amounts of data.
It has the exact same com.facebook.react.ExceptionsManagerQueue stacktrace.
In the complete logfile there is only one line of code coming from us and it's in com.apple.main-thread: right before UIKitCore and GraphicsServices, so it's very likely not coming from our code.


We do connect to quite a native-modules:
From react-native:
 - Core
 - CxxBridge
 - RCTPushNotification
 - DevSupport
 - RCTText
 - RCTImage
 - RCTNetwork
 - RCTWebSocket
 - RCTSettings
 - RCTAnimation
 - RCTLinkingIOS
 - RCTAnimation
 - RCTActionSheet
 - RCTGeolocation
 - RCTImage
 - RCTVibration
 - yoga
 - DoubleConversion
 - glog
 - Folly
From third party: 
 - RSKImageCropper
 - QBImagePickerController
 - iOSDFULibrary
 - react-native-ble-plx-swift
 - RCTSystemSetting
 - react-native-netinfo
 - react-native-ble-plx
 - react-native-blur
 - RNI18n
 - BVLinearGradient
 - react-native-sensitive-info
 - RNVectorIcons
 - rn-fetch-blob
 - RNImageCropPicker
 - RNCAsyncStorage
 - react-native-orientation
 - react-native-video/VideoCaching

**Comment by getaaron** [comment] 2019-08-22 11:38
@grabbou @hramos see above, I believe this issue was closed erroneously

**Comment by russelRajitha** [comment] 2019-10-12 02:04
is there any solution for this issue? facing same issue in review process  in appstore. with real devices and emulators everything working perfectly. but when it put as new production release they are rejecting build and crash reports same as this report.

**Comment by MrKriegler** [comment] 2019-11-06 18:20
Think this issue should be re-opened as there seems to be more people getting this issue, including myself?

**Comment by keremaydin52** [comment] 2019-12-04 19:01
I have the same issue when navigating a different scene in my app but I don't what causes the problem.

Actually there is no problem when testing on simulator or getting build to my phone from Xcode. However when I get ipa file and upload to Diawi or publishing via TestFlight there is this problem.

I changed codes but I couldn't solve the problem yet.

Is there any solution?

**Comment by MrKriegler** [comment] 2019-12-05 14:03
@keremaydin52 this solution worked for me

**Comment by keremaydin52** [comment] 2019-12-05 15:20
@MrKriegler Thanks mate. I have added Firebase Crashlytics today and found that the problem is due to react-native-gesture-handler. I was just looking for the solution and see your comment.
