### ISSUE TITLE
KeyboardAvoidingView with keyboardDismissMode interactive does not resize as keyboards hides.

### ISSUE THREAD

**Issue by grundmanise** [facebook/react-native#13073] opened 2017-03-22 09:55 UTC
### Description

When using `keyboardDismissMode="interactive"` on `ScrollView`  `KeyboardAvoidingView` does not resize as keyboards hides.

Here's a gif to demonstrate what behavior I'm referring to:

![gif](https://camo.githubusercontent.com/a2ee2a721cc55d5cdd2a2864c41ee31d034d3057/68747470733a2f2f7468756d62732e6766796361742e636f6d2f4d696e646c65737353616e65416e6777616e7469626f2d73697a655f726573747269637465642e676966)
_gif taken from https://github.com/Andr3wHur5t/react-native-keyboard-spacer/issues/48 , but `KeyboardAvoidingView` has the same issue._

### Reproduction

https://sketch.expo.io/B1JIYaynx

### Solution

Track keyboard height when panning of the keyboard starts?

### Additional Information

* React Native version: 0.42
* Platform: iOS

**Comment by RyanMitchellWilson** [comment] 2017-05-09 20:16
I'm seeing this problem as well.

**Comment by hramos** [comment] 2017-07-25 22:51
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by pozdena** [comment] 2017-09-05 15:56
I'm having this issue as well. Maybe most people won't care about this, which led to it being auto-closed, but it's crucial to the small number of people who run into this and are using React Native to create complex, high quality apps. I don't have time to contribute right now but I will be forced to fix this eventually if no one else gets around to it. :)

**Comment by RyanMitchellWilson** [comment] 2017-09-06 20:04
Can this be reopened, I would really like to have this in my app

**Comment by mferranti** [comment] 2017-09-12 14:22
i have this issue too.

**Comment by artsx** [comment] 2017-11-06 14:12
Hello, someone found a solution?

**Comment by 404sand808s** [comment] 2017-11-20 20:58
Also having this issue.

**Comment by martinezguillaume** [comment] 2017-11-22 13:06
Need this ! 🙂 It would be so nice !

**Comment by RyanMitchellWilson** [comment] 2017-11-27 18:58
@hramos this has been sitting around for 7 months with no reply from the react-native team. Is there a way we could get this prioritized?

**Comment by ericlewis** [comment] 2017-11-30 00:41
Any word from the team on this?

**Comment by zsaraf** [comment] 2017-12-06 18:54
@facebook-github-bot anything?

**Comment by furkancelik** [comment] 2017-12-07 01:29
is solved?

**Comment by chrisbull** [comment] 2017-12-30 03:38
Would be great to have a fix for this, or a solution to make it work. Thanks!

**Comment by franzwarning** [comment] 2018-01-09 04:18
Any update on this?

**Comment by herarya** [comment] 2018-03-16 03:31
+1 , any solution guys ?

**Comment by hramos** [comment] 2018-04-04 19:55
Can you specify the version you last tried this on? ("Latest" by itself is not sufficient, due to the monthly release train, release candidates, master).

**Comment by mahyarr** [comment] 2018-04-09 20:08
Im using 0.55.2 and I have this problem

**Comment by pribeh** [comment] 2018-05-28 21:20
The same is happening with flatlist as well. 0.55.2

**Comment by borbit** [comment] 2018-08-06 16:43
I am using 0.56.0 - the problem still exists

**Comment by ultramiraculous** [comment] 2018-08-11 01:58
For the specific issue in the original post, is there a reason `InputAccessoryView` wouldn't be used? It seems like the correct solution for a keyboard toolbar/input bar.

**Comment by pribeh** [comment] 2018-08-11 14:38
@ultramiraculous Looks like the guys at wix have the same idea. https://github.com/wix/react-native-keyboard-tracking-view

**Comment by pribeh** [comment] 2018-08-11 15:16
@ultramiraculous that's what I was looking for.

**Comment by hramos** [comment] 2018-09-11 00:47
Closed as InputAccessoryView is what is preferred in this case.

**Closed by hramos** 2018-09-11 00:47 UTC
Labels: :large_blue_diamond:iOS, :white_check_mark:Author Provided Repro, Help Wanted :octocat:

**Comment by VinceBT** [comment] 2018-12-14 14:15
Sorry but this is far from closed, the deep problem comes from the fact that the `KeyboardAvoidingView` does not follow the keyboard movement when dragged interactively with `keyboardDismissMode="interactive"`, as you can see in the first GIF, the `ScrollView` is half of its size until the touch is released, this has nothing to do with toolbars or `InputAccessoryView`

**Comment by tgensol** [comment] 2019-01-14 10:46
Still having this issue too

**Comment by scottmas** [comment] 2019-01-15 06:38
Also, InputAccessoryView has extremely spotty documentation. I'm not a novice programmer and I don't understand at all how this component is supposed to work. My initial efforts ended up with a whole lot of nothing.

**Comment by hramos** [comment] 2019-01-15 19:14
The docs for InputAccessoryView link to a working example: https://github.com/facebook/react-native/blob/master/RNTester/js/InputAccessoryViewExample.js. It might also be useful to understand the underlying iOS class: https://developer.apple.com/documentation/uikit/uiresponder/1621119-inputaccessoryview
