### ISSUE TITLE
RCTUtils Crash

### ISSUE THREAD

**Issue by liubobo** [facebook/react-native#4200] opened 2015-11-18 09:11 UTC
<__NSArrayM 0x7fbfd8c57f50>(
77,
RCTView,
1,
{
    backgroundColor = 4290497769;
    borderRadius = 2;
    height = 4;
    marginTop = nan;
    opacity = 0;
    position = absolute;
    width = 300;
}
)

2015-11-18 17:10:12.594 Voice[16700:2987744] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid number value (NaN) in JSON write'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000102ebff65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x00000001020c0deb objc_exception_throw + 48
	2   CoreFoundation                      0x0000000102ebfe9d +[NSException raise:format:] + 205
	3   Foundation                          0x0000000101db4a6b _writeJSONNumber + 707
	4   Foundation                          0x0000000101db1a2f _writeJSONValue + 486
	5   Foundation                          0x0000000101db575e ___writeJSONObject_block_invoke + 226
	6   CoreFoundation                      0x0000000102df8466 __65-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 102
	7   CoreFoundation                      0x0000000102df835a -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 202
	8   Foundation                          0x0000000101db4ee8 _writeJSONObject + 436
	9   Foundation                          0x0000000101db19d5 _writeJSONValue + 396
	10  Foundation                          0x0000000101db5921 ___writeJSONArray_block_invoke + 132
	11  CoreFoundation                      0x0000000102deead2 __53-[__NSArrayM enumerateObjectsWithOptions:usingBlock:]_block_invoke + 114
	12  CoreFoundation                      0x0000000102dee1ef -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 239
	13  Foundation                          0x0000000101db5159 _writeJSONArray + 330
	14  Foundation                          0x0000000101db1a71 _writeJSONValue + 552
	15  Foundation                          0x0000000101db17f5 -[_NSJSONWriter dataWithRootObject:options:error:] + 124
	16  Foundation                          0x0000000101db4216 +[NSJSONSerialization dataWithJSONObject:options:error:] + 333
	17  Voice                               0x0000000101a28352 RCTJSONStringify + 322
	18  Voice                               0x0000000101a14f72 -[RCTBatchedBridge _handleRequestNumber:moduleID:methodID:params:] + 994
	19  Voice                               0x0000000101a143ea __33-[RCTBatchedBridge handleBuffer:]_block_invoke + 826
	20  libdispatch.dylib                   0x0000000106381ef9 _dispatch_call_block_and_release + 12
	21  libdispatch.dylib                   0x00000001063a249b _dispatch_client_callout + 8
	22  libdispatch.dylib                   0x0000000106388988 _dispatch_queue_drain + 2215
	23  libdispatch.dylib                   0x0000000106387ea9 _dispatch_queue_invoke + 601
	24  libdispatch.dylib                   0x000000010638aaf2 _dispatch_root_queue_drain + 1420
	25  libdispatch.dylib                   0x000000010638a561 _dispatch_worker_thread3 + 111
	26  libsystem_pthread.dylib             0x00000001066d3a9d _pthread_wqthread + 729
	27  libsystem_pthread.dylib             0x00000001066d13dd start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by liubobo** [comment] 2015-11-18 09:26
i changed the RCTUtils

NSString *RCTJSONStringify(id jsonObject, NSError **error)
{
  static SEL JSONKitSelector = NULL;
  static NSSet *collectionTypes;
  static dispatch_once_t onceToken;
  dispatch_once(&onceToken, ^{
    SEL selector = NSSelectorFromString(@"JSONStringWithOptions:error:");
    if ([NSDictionary instancesRespondToSelector:selector]) {
      JSONKitSelector = selector;
      collectionTypes = [NSSet setWithObjects:
                         [NSArray class], [NSMutableArray class],
                         [NSDictionary class], [NSMutableDictionary class], nil];
    }
  });

  // Use JSONKit if available and object is not a fragment
  if (JSONKitSelector && [collectionTypes containsObject:[jsonObject classForCoder]]) {
    return ((NSString *(*)(id, SEL, int, NSError **))objc_msgSend)(jsonObject, JSONKitSelector, 0, error);
  }
  
  NSRange range=[[jsonObject description] rangeOfString:@"nan"];
  
  if(range.location!=NSNotFound){
    
    NSString * modifyString = [[[jsonObject description] stringByReplacingOccurrencesOfString:@"nan" withString:@""] stringByReplacingOccurrencesOfString:@"Nan" withString:@""];
    return modifyString;
    
  }
  
  
  // Use Foundation JSON method
  NSData *jsonData = [NSJSONSerialization
                      dataWithJSONObject:jsonObject
                      options:(NSJSONWritingOptions)NSJSONReadingAllowFragments
                      error:error];
  return jsonData ? [[NSString alloc] initWithData:jsonData encoding:NSUTF8StringEncoding] : nil;
}

**Comment by nicklockwood** [comment] 2015-11-18 15:00
Hmm, this fix doesn't really make sense to me. You're taking the JSON object (e.g. a dictionary) and then converting it to a string by calling `[jsonObject description]`, and then processing that string. But the string produced by `[jsonObject description]` isn't a JSON string, and even if it was, replacing "nan" with a blank string would not produce valid JSON.

I suspect the only reason that this fix appears to work is that the resultant jsonObject string cannot be parsed by NSJSONSerialization, so it just returns nil instead of crashing, with the result that the update is discarded (which probably causes other bugs in the app).

**Comment by gre** [comment] 2015-11-21 14:02
Do you guys know what this error means and how to reproduce it? the stacktrace don't show exactly from where it crashes in the lib, it appears to crash from ReactNative?

We have seen the same error on gl-react-native but this looks to happen very randomly:  https://github.com/ProjectSeptemberInc/gl-react-native/issues/31
(this ticket mentioned related to live reload, but i've just been able to trigger it after "sliding" a bit the Slider in [this demo](https://projectseptemberinc.gitbooks.io/gl-react/content/docs/examples/8.html). weird thing is the error seems to disappear when I enable the Chrome Debugger (in my current use-case) )

**Comment by gre** [comment] 2015-11-21 14:03
Also i've recently upgraded to 0.14.x and i'm wondering if it's a new bug.

**Comment by nicklockwood** [comment] 2015-11-21 20:33
@gre NaN, infinity, etc. cannot be represented in JSON. Apparently, if any of our view frame coordinates on the native side are NaN then sending them over the bridge will crash.

**Comment by ide** [comment] 2015-11-21 23:22
Could this be addressed by passing in an `NSError **` value instead of `NULL` as the error arg? I'm wondering if NSJSONSerialization will populate the error instead of throwing an ObjC exception, or if running `isValidJSONObject:` beforehand is the only way to prevent a crash.

**Comment by nicklockwood** [comment] 2015-11-22 14:40
Running isValidJSON for every call would be very expensive. It would probably be better to just use try/catch. I'll write some tests for it and then work out what to do.

**Comment by liubobo** [comment] 2015-11-23 03:10
thanks,Let us work together to improve reactnative

**Comment by liubobo** [comment] 2015-11-23 03:19
i use The latest version

**Comment by mkonicek** [comment] 2016-04-10 16:42
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/rctutils-crash

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Closed by mkonicek** 2016-04-10 16:42 UTC
Labels: Icebox
