### ISSUE TITLE
Getting this Error !!!!!

### ISSUE THREAD

**Issue by harsh8088** [facebook/react-native#15291] opened 2017-07-31 12:52 UTC
### Is this a bug report?
Everytime i need to run android/gradlew clean cmd
(Parsing json file: D:\Final_WorkSpace\DemoApp\android\app\google-services.json
:app:processDebugGoogleServices FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> Failed to delete: D:\Final_WorkSpace\DemoApp\android\app\build\generated\res\google-services\debug

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.)

### Have you read the Bugs section of the How to Contribute guide?

(Write your answer here.)

### Environment

1. `react-native -v`:
2. `node -v`:
3. `npm -v`:
4. `yarn --version`:

Then, specify:

- Target Platform: "react-native": "0.46.4"

- Development Operating System: Windows

- Build tools: Android Studio 2.3.3

### Steps to Reproduce

(Write your steps here:)

1. react-native run-android
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by hramos** [comment] 2017-07-31 17:55
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-07-31 17:55 UTC
