### ISSUE TITLE
PickerIOS

### ISSUE THREAD

**Issue by andylidong** [facebook/react-native#11780] opened 2017-01-09 03:13 UTC
React Native: 0.32.0
iOS: 10.0.2

My  Code:

![qq 20170109111250](https://cloud.githubusercontent.com/assets/18454971/21756458/9a906c70-d65c-11e6-8352-be45c47cb7ee.png)

**the line of picker selected is not appear,do you have solution?**

![_u3wwuajwmvx 3 dl m gp](https://cloud.githubusercontent.com/assets/18454971/21756460/9d75a928-d65c-11e6-8233-423e2b012463.jpg)

**Comment by ericvicenti** [comment] 2017-01-09 10:21
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by ericvicenti** 2017-01-09 10:21 UTC

**Comment by andylidong** [comment] 2017-01-09 10:47
https://github.com/andylidong/react-native-picker

**Comment by andylidong** [comment] 2017-01-09 10:51
You can see this .Picker on ios 9 and lower is ok, but on ios 10 is not suit.
