### ISSUE TITLE
[CI] Run tests on Windows

### ISSUE THREAD

**Issue by hramos** [facebook/react-native#20260] opened 2018-07-17 23:22 UTC
# For Discussion

Our suite of tests does not currently run on Windows machines. This results in a blind spot that has allowed issues affecting Windows users to creep into the code base (https://github.com/facebook/metro/issues/181).

Circle CI [does not support running jobs on Windows](https://circleci.com/docs/2.0/faq/#what-operating-systems-does-circleci-20-support) at the moment. I'd like to open a discussion and get feedback from the community on how to proceed.

**Comment by kelset** [comment] 2018-07-18 09:38
A while back @matthargett suggested that to fix the CircleCI "Windows absence" we could integrate [AppVeyor CI](https://www.appveyor.com/)

**Comment by gengjiawen** [comment] 2018-07-18 11:23
Recently babel add Appveyor too.

**Comment by charpeni** [comment] 2018-07-18 13:35
I agree that AppVeyor CI would be a good alternative and it looks like from their homepage that Facebook is already one of their great customers.

As starting point, maybe we can introduce some basic Windows tests like:

1. Clone the repository and use the cli (from local repository) to init a fresh React Native project.
1. From this fresh project, bundle the JavaScript (`local-cli/cli.js bundle`).

With this we should be able to catch issues like #20015.

**Comment by gengjiawen** [comment] 2018-07-18 13:56
I have created a pr https://github.com/facebook/react-native/pull/20281, hope it helps.

**Comment by kelset** [comment] 2018-07-18 13:56
Yeah I think that's a "good enough" start, and then we can ask Windows dev to jump in and add more tests as the platform becomes more widely used.

**Comment by gengjiawen** [comment] 2018-07-20 05:12
So what test should on windows platform run ? Aside from basic android build. I also add some `npm run test`, but some test case are failed.

Personally I want to add metro debug server bundle works as expected.

**Comment by gengjiawen** [comment] 2018-07-24 12:38
@hramos Can you check the appveyor config or the badge url. Looks like README.md now has not show any build in appveyor.

**Comment by gengjiawen** [comment] 2018-07-24 12:58
The windows issue (https://github.com/facebook/react-native/issues/20353) still exists on master branch now. So we do need a test case to test the request to `http://localhost:8081/RNTester/js/RNTesterApp.android.delta?platform=android&dev=true&minify=false` works on windows.

I will see what I can do after my two prs got merged.

**Comment by gengjiawen** [comment] 2018-09-02 05:39
Currently the android build works on appveyor, but we have some jest test failure.
```
Test Suites: 16 failed, 2 skipped, 90 passed, 106 of 108 total
Tests:       54 failed, 4 skipped, 545 passed, 603 total
Snapshots:   42 passed, 42 total
Time:        12.803s
```
Most of those related to `On a win32 FS, the options'  cwd() must return a valid win32 absolute path.`
```
Error: On a win32 FS, the options' `cwd()` must return a valid win32 absolute path. This happened while trying to resolve: `c:\empty`

      33 |       continue;
      34 |     }
    > 35 |     fs.mkdirSync(entPath);
         |        ^
      36 |     mockDir(entPath, ent);
      37 |   }
      38 | }

      at MemoryFs._resolve (node_modules/metro-memory-fs/src/index.js:830:15)
      at MemoryFs.mkdirSync (node_modules/metro-memory-fs/src/index.js:994:5448)
      at mockDir (local-cli/__mocks__/fs.js:35:8)
      at MemoryFs.setMockFilesystem [as __setMockFilesystem] (local-cli/__mocks__/fs.js:17:3)
      at Object.<anonymous> (local-cli/core/__tests__/android/getDependencyConfig.spec.js:23:19)
```

**Comment by jeanlauliac** [comment] 2018-09-11 15:38
I have a fix for the `fs`-related failure, it's due to a problem in the way the test are setup and not specific to `metro-memory-fs`. Will send soon.

**Comment by gengjiawen** [comment] 2018-09-11 16:03
@jeanlauliac Hopefully we can fix the windows ci via your pr :)

**Comment by jeanlauliac** [comment] 2018-09-17 12:56
Please try past post https://github.com/facebook/react-native/commit/e327f88f028579023ce93f04d66b9606ec476547, hopefully that adresses issues with the `fs` mock that were happening on Windows.

**Comment by gengjiawen** [comment] 2018-09-19 15:15
@jeanlauliac Good job. Test case fail on windows from 54 to 7.

**Comment by jeanlauliac** [comment] 2018-09-24 13:33
Yeah that's because `path` doesn't get mocked early enough. Changeset on the way.

**Comment by gengjiawen** [comment] 2018-09-26 14:38
@jeanlauliac It looks like cause more problem, now it have three fails, check https://ci.appveyor.com/project/facebook/react-native/branch/master/job/9s95x3eb1f937qrk.

**Comment by jeanlauliac** [comment] 2018-09-27 09:53
The errors on the report are not related to the JS tests are they? It looks like build errors/.

**Comment by gengjiawen** [comment] 2018-09-27 10:14
Nope, it's test case.

**Comment by jeanlauliac** [comment] 2018-09-27 11:30
We're not looking at the same thing then. In the link you sent, here's the only error I can see:

```
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'react-native'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve com.sun.xml.fastinfoset:FastInfoset:1.2.13.
     Required by:
         project : > com.android.tools.build:gradle:3.1.4 > com.android.tools.build:gradle-core:3.1.4 > com.android.tools.build:builder:3.1.4 > com.android.tools:sdklib:26.1.4 > com.android.tools:repository:26.1.4 > org.glassfish.jaxb:jaxb-runtime:2.2.11
      > Could not resolve com.sun.xml.fastinfoset:FastInfoset:1.2.13.
         > Could not get resource 'https://jcenter.bintray.com/com/sun/xml/fastinfoset/FastInfoset/1.2.13/FastInfoset-1.2.13.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/sun/xml/fastinfoset/FastInfoset/1.2.13/FastInfoset-1.2.13.pom'. Received status code 504 from server: Gateway Time-out
   > Could not resolve javax.xml.bind:jaxb-api:2.2.12-b140109.1041.
     Required by:
         project : > com.android.tools.build:gradle:3.1.4 > com.android.tools.build:gradle-core:3.1.4 > com.android.tools.build:builder:3.1.4 > com.android.tools:sdklib:26.1.4 > com.android.tools:repository:26.1.4 > org.glassfish.jaxb:jaxb-runtime:2.2.11 > org.glassfish.jaxb:jaxb-core:2.2.11
      > Skipped due to earlier error
   > Could not resolve org.glassfish.jaxb:txw2:2.2.11.
     Required by:
         project : > com.android.tools.build:gradle:3.1.4 > com.android.tools.build:gradle-core:3.1.4 > com.android.tools.build:builder:3.1.4 > com.android.tools:sdklib:26.1.4 > com.android.tools:repository:26.1.4 > org.glassfish.jaxb:jaxb-runtime:2.2.11 > org.glassfish.jaxb:jaxb-core:2.2.11
      > Skipped due to earlier error
   > Could not resolve com.sun.istack:istack-commons-runtime:2.21.
     Required by:
         project : > com.android.tools.build:gradle:3.1.4 > com.android.tools.build:gradle-core:3.1.4 > com.android.tools.build:builder:3.1.4 > com.android.tools:sdklib:26.1.4 > com.android.tools:repository:26.1.4 > org.glassfish.jaxb:jaxb-runtime:2.2.11 > org.glassfish.jaxb:jaxb-core:2.2.11
      > Skipped due to earlier error
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 1m 34s
Command exited with code 1
```

What am I missing? 🙂

**Comment by gengjiawen** [comment] 2018-09-27 11:50
looks like bintray service not stable or you miss google() in your gradle config.

**Comment by gengjiawen** [comment] 2018-09-27 12:00
Maybe I paste the wrong link, you can check the recent master branch.

**Comment by hramos** [comment] 2018-09-27 14:12
Here's the error report from the above link:

```
Summary of all failing tests
FAIL Libraries/Interaction/__tests__/InteractionManager-test.js
  ● promise tasks › should also work with a deadline
    expect(received).toBe(expected) // Object.is equality
    Expected: 1
    Received: 0
      14 | 
      15 | function expectToBeCalledOnce(fn) {
    > 16 |   expect(fn.mock.calls.length).toBe(1);
         |                                ^
      17 | }
      18 | 
      19 | describe('InteractionManager', () => {
      at expectToBeCalledOnce (Libraries/Interaction/__tests__/InteractionManager-test.js:16:32)
      at Timeout._onTimeout (Libraries/Interaction/__tests__/InteractionManager-test.js:294:7)
FAIL local-cli/link/__tests__/ios/writePlist.spec.js
  ● ios::writePlist › should write a `.plist` file
    ENOENT: no such file or directory, open 'C:\projects\__fixtures__\project.pbxproj'
      27 | const infoPlistPath = path.join(__dirname, '../../__fixtures__/Info.plist');
      28 | 
    > 29 | fs.readFileSync = jest.fn(() => readFileSync(projectPath).toString());
         |                                                          ^
      30 | 
      31 | const {writeFileSync} = fs;
      32 | fs.writeFileSync = jest.fn(writeFileSync);
      at Object.<anonymous> (local-cli/link/__tests__/ios/writePlist.spec.js:29:58)
      at pbxProject.Object.<anonymous>.pbxProject.parseSync (node_modules/xcode/lib/pbxProject.js:44:28)
      at Object.<anonymous> (local-cli/link/__tests__/ios/writePlist.spec.js:43:13)
  ● ios::writePlist › should write a `.plist` file
    ENOENT: `/Basic/Info.plist`: no such file or directory
      27 |   // indentation of the plist.
      28 |   // Ref: https://github.com/facebook/react-native/issues/11668
    > 29 |   return fs.writeFileSync(
         |                        ^
      30 |     plistPath,
      31 |     plistParser.build(plist, {indent: '\t', offset: -1}) + '\n',
      32 |   );
      at makeError (node_modules/metro-memory-fs/src/index.js:1239:15)
      at MemoryFs._resolveEnt (node_modules/metro-memory-fs/src/index.js:877:13)
      at MemoryFs._resolve (node_modules/metro-memory-fs/src/index.js:850:12)
      at MemoryFs._open (node_modules/metro-memory-fs/src/index.js:736:10)
      at Object.writeFileSync (node_modules/metro-memory-fs/src/index.js:994:5210)
      at writePlist (local-cli/link/ios/writePlist.js:29:24)
      at Object.<anonymous> (local-cli/link/__tests__/ios/writePlist.spec.js:49:49)
  ● ios::writePlist › when plistPath is null it should return null
    ENOENT: no such file or directory, open 'C:\projects\__fixtures__\project.pbxproj'
      27 | const infoPlistPath = path.join(__dirname, '../../__fixtures__/Info.plist');
      28 | 
    > 29 | fs.readFileSync = jest.fn(() => readFileSync(projectPath).toString());
         |                                                          ^
      30 | 
      31 | const {writeFileSync} = fs;
      32 | fs.writeFileSync = jest.fn(writeFileSync);
      at Object.<anonymous> (local-cli/link/__tests__/ios/writePlist.spec.js:29:58)
      at pbxProject.Object.<anonymous>.pbxProject.parseSync (node_modules/xcode/lib/pbxProject.js:44:28)
      at Object.<anonymous> (local-cli/link/__tests__/ios/writePlist.spec.js:43:13)
  ● ios::writePlist › when plistPath is null it should return null
    expect(jest.fn()).not.toHaveBeenCalled()
    Expected mock function not to be called but it was called with:
      ["/Basic/Info.plist", "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
    <!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">
    <plist version=\"1.0\">
    <dict>
    	<key>CFBundleDevelopmentRegion</key>
    	<string>en</string>
    	<key>UISupportedInterfaceOrientations</key>
    	<array>
    		<string>UIInterfaceOrientationPortrait</string>
    	</array>
    </dict>
    </plist>
    "]
      55 |     plistPath = null;
      56 |     expect(writePlist(project, '/', plist)).toBeNull();
    > 57 |     expect(fs.writeFileSync).not.toHaveBeenCalled();
         |                                             ^
      58 |   });
      59 | });
      60 | 
      at Object.<anonymous> (local-cli/link/__tests__/ios/writePlist.spec.js:57:45)
Test Suites: 2 failed, 2 skipped, 104 passed, 106 of 108 total
Tests:       3 failed, 4 skipped, 601 passed, 608 total
Snapshots:   42 passed, 42 total
Time:        31.172s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

**Comment by jeanlauliac** [comment] 2018-10-10 18:17
The changeset *partly* fixes things only, I think :)   for the rest I'd have to grab a windows VM and try out.

As for the `InteractionManager-test.js` this may be flakiness and I do not believe this is related to the `fs` mock. I have no context on that test I'm afraid.

**Comment by gengjiawen** [comment] 2018-10-14 06:03
@jeanlauliac Glad to hear, I hope we can fix this soon. Maybe @rafeca can help you with the windows part, he fix some metro issue on windows machine.

**Comment by empyrical** [comment] 2018-10-17 07:03
Since this issue was created, Microsoft released this:

https://azure.microsoft.com/en-ca/blog/announcing-azure-pipelines-with-unlimited-ci-cd-minutes-for-open-source/

Which may be an option if appveyor is being too troublesome. That `InteractionManager` issue is really odd, because I cannot reproduce it on my windows VM at all.

**Comment by gengjiawen** [comment] 2018-10-17 09:05
@empyrical Windows 10 ?

**Comment by hramos** [comment] 2018-10-17 19:15
Appveyor is still red -- what do you folks think about removing Appveyor.yml from the master branch until this is fixed? It makes it hard to see when Circle CI tests have broken when looking at the list of recent commits. I hope Appveyor does let you run tests on a branch that includes Appveyor.yml, similar to how Circle CI works, as that would help verify the status of those tests.

**Comment by empyrical** [comment] 2018-10-17 19:38
I've used AppVeyor without issue on my React Native fork, not sure about other branches on the same repo though.

But if someone wants to try and fix this last remaining test on their fork it would work fine.

**Comment by empyrical** [comment] 2018-10-18 01:34
Oh, sorry, I didn't get the test working on my fork.

What I mean is, if someone wants to make an attempt at fixing the failing `InteractionManager` test, AppVeyor will work fine for testing on their personal React Native fork

**Closed** 2018-11-06 16:02 UTC
Labels: Core Team, For Discussion, 🔩Tests, 🔷Windows
