### ISSUE TITLE
FlatList---When I set prop “numColumns”，Rendering appears without setting white lines

### ISSUE THREAD

**Issue by sdqyang** [facebook/react-native#14146] opened 2017-05-24 02:57 UTC
like picture 
![image](https://cloud.githubusercontent.com/assets/5997041/26385058/ac3b91e8-406f-11e7-8db7-d013da0a303f.png)

thanks

**Comment by hramos** [comment] 2017-05-26 23:14
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-05-26 23:14 UTC
