### ISSUE TITLE
BUG: android:windowSoftInputMode="adjustResize" will not work when StatusBar hidden="true"

### ISSUE THREAD

**Issue by CodeXtinction** [facebook/react-native#12980] opened 2017-03-16 19:27 UTC
AndroidManifest.xml
android:windowSoftInputMode="adjustResize"

I found this bug while playing with StatusBar
if you set StatusBar hidden="true" the keyboard push the header out of the screen instead of resizing.

hidden="false"
![](https://k60.kn3.net/652469001.png)

hidden="true"
![](https://k61.kn3.net/65E993B7F.png)

 "react": "15.4.2",
 "react-native": "0.41.0",

**Comment by paalex** [comment] 2017-03-16 19:34
Same here..
http://stackoverflow.com/questions/42840555/how-to-avoid-keyboard-pushing-layout-up-on-android-react-native

**Comment by hramos** [comment] 2017-03-16 20:32
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported. Specifically, a code sample or Sketch would be ideal here.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-03-16 20:32 UTC

**Comment by hramos** [comment] 2018-03-13 21:22
Can you open a new issue?

**Comment by rcorrie** [comment] 2018-03-21 16:42
@hramos no need. 

This ended up being my problem: facebook/react-native#12980

Apparently, StatusBar doesn't play nicely with KeyboardAvoidingView on android.

If at any point you app hides the status bar, all bets are off with your KeyboardAvoidingView

**Comment by Noitidart** [comment] 2018-03-23 13:56
@hramos they did open a new issue but you closed that one as well - https://github.com/facebook/react-native/issues/13000

**Comment by Noitidart** [comment] 2018-03-23 16:28
Understood. I just found it funny that we are asking for them to create a new issue after already closing their new issue. :P haha

**Comment by hramos** [comment] 2018-03-23 18:16
*shrug* I was talking to @rcorrie, who bumped this closed issue.

**Comment by Noitidart** [comment] 2018-03-23 18:24
I understand. I didn't mean to point out or anything, i just wanted to share a laugh :P I know thats from your boss, he tells you to close things. You do amazing work in bring RN to us, thanks @hramos!
