### ISSUE TITLE
libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0x7f91800000 in tid 1233 (FrescoDecodeExe)(Android)

### ISSUE THREAD

**Issue by Biplovkumar** [facebook/react-native#24481] opened 2019-04-17 05:51 UTC
## 🐛 Bug Report

App crashes,Log only this.
libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0x7f91800000 in tid 1233 (FrescoDecodeExe)

## To Reproduce
App crashes

## Expected Behavior

Work normal

## Code Example

```
{
  "name": "XXXXX",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "run-ios": "react-native run-ios",
    "android": "react-native run-android",
    "build:assets": "fc-build-assets --fc-template ./assets/fusioncharts-tpl.html",
    "clear-cache": "react-native cache clean --force && yarn && react-native start -- --reset-cache",
    "clear": "watchman watch-del-all && rm -rf node_modules && npm instal && rm -rf /tmp/metro-bundler-cache-* && npm start -- --reset-cache && rm -rf /tmp/haste-map-react-native-packager-*",
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "prod:android": "npm run clean:build:android  && react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res",
    "test": "jest",
    "clean:build:android": "rm -rf android/app/build"
  },
  "dependencies": {
    "@babel/runtime": "^7.3.4",
    "axios": "^0.18.0",
    "fusioncharts": "^3.13.4",
    "jest-haste-map": "^24.7.1",
    "moment": "^2.24.0",
    "react": "16.6.3",
    "react-native": "0.59.4",
    "react-native-carousel-view": "^0.5.1",
    "react-native-datepicker": "^1.7.2",
    "react-native-elements": "^1.1.0",
    "react-native-fusioncharts": "^3.0.0",
    "react-native-gesture-handler": "^1.1.0",
    "react-native-localization": "^2.1.0",
    "react-native-maps": "https://github.com/react-native-community/react-native-maps.git",
    "react-native-material-dropdown": "^0.11.1",
    "react-native-popup-dialog": "^0.17.0",
    "react-native-render-html": "^4.1.2",
    "react-native-vector-icons": "^6.3.0",
    "react-native-video": "^4.4.0",
    "react-native-youtube": "^1.1.0",
    "react-navigation": "^3.3.0"
  },
  "devDependencies": {
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "24.1.0",
    "jest": "24.1.0",
    "metro-react-native-babel-preset": "0.51.1",
    "react-test-renderer": "16.6.3"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

## Environment
 `    "react": "16.6.3",
    "react-native": "0.59.4",`

**Comment by Biplovkumar** [comment] 2019-04-18 03:46
> Can you run `react-native info` and edit your issue to include these results under the **Environment** section?
**react-native info**

```
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
      Memory: 2.94 GB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.4.1 - /usr/local/bin/node
      Yarn: 1.15.2 - ~/.yarn/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 22, 23, 24, 25, 26, 27, 28
        Build Tools: 19.1.0, 23.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.1, 28.0.3, 29.0.0
        System Images: android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.6.3 
      react-native: 0.59.4 => 0.59.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-file-picker: 0.0.12
      react-native-git-upgrade: 0.2.7
      react-native-vector-icons: 6.1.0
```

**Comment by JKCooper2** [comment] 2019-04-20 09:30
May be duplicate of: https://github.com/facebook/react-native/issues/24097

**Comment by dishantwalia** [comment] 2019-04-21 06:34
https://github.com/facebook/react-native/issues/24261
Duplicate of #24261

**Comment by dishantwalia** [comment] 2019-04-21 06:35
#[https://github.com/facebook/react-native/issues/24261](url) #

**Comment by Kida007** [comment] 2019-04-22 22:35
have seen that error code for many reasons , can you trace back to your recent modification ( safe state) . would definitely help !

**Comment by JKCooper2** [comment] 2019-04-27 09:38
@Kida007 as this is a duplicate I would recommend closing this issue and posting any additional information you have as a comment in the other issue

**Comment by Biplovkumar** [comment] 2019-04-28 08:18
> have seen that error code for many reasons , can you trace back to your recent modification ( safe state) . would definitely help !

sorry , i can't, it came from start, i have developed full app.

**Comment by Biplovkumar** [comment] 2019-04-28 08:20
> @Kida007 as this is a duplicate I would recommend closing this issue and posting any additional information you have as a comment in the other issue

only do clode , either write dublicate  I would recommend closing this issue , 
No one is giving answer ??

**Closed** 2019-05-13 14:16 UTC
Labels: Bug, Platform: Android, Ran Commands, Resolution: Missing Environment Info

**Comment by joshuapinter** [comment] 2019-11-19 03:52
In our case, it was because we were using `null` in an `Image` Component's `source` `uri` prop, like this: 

```js
<Image source={ uri: null } />
```

It was causing this crash.

We found the solution [here](https://github.com/facebook/react-native/issues/24261#issuecomment-525443006).
