### ISSUE TITLE
0.52 - CORS issue with JS Remote Debugging when using xip.io

### ISSUE THREAD

**Issue by njbmartin** [facebook/react-native#17618] opened 2018-01-15 22:51 UTC
### Is this a bug report?

Yes.

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes.

### Environment

Environment:
  OS: macOS High Sierra 10.13.2
  Node: 9.4.0
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.2.0 => 16.2.0
  react-native: ^0.52.0 => 0.52.0

Target Platform: iOS 8

### Steps to Reproduce

> Note: I upgraded to `0.52` last night using `react-native-git-upgrade`, it had been working previously on `0.51`.

1. Run development app on real iOS device, which loads the JS bundle from `http://192.168.0.13.xip.io:8081/index.delta?platform=ios&dev=true&minify=false`
2. Enable JS Remote debug tools, which opens `http://localhost:8081/debugger-ui/` in Chrome.
3. Bundle reloads and Chrome DevTools console displays the following error:

> Failed to load http://192.168.0.13.xip.io:8081/index.delta?platform=ios&dev=true&minify=false: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8081' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

### Expected Behavior

App should load correctly and not throw an error when trying to debug JS remotely.

### Actual Behavior

> Failed to load http://192.168.0.13.xip.io:8081/index.delta?platform=ios&dev=true&minify=false: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8081' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

> Fresh react-native app using `react-native init`.

https://github.com/njbmartin/react-native-xip

**Comment by njbmartin** [comment] 2018-01-15 23:41
Did some digging, and found that if I modify https://github.com/facebook/metro/ `_processDeltaRequest` to include `mres.setHeader("Access-Control-Allow-Origin", "*");` it works. I don't believe this is enough to fix the issue though.

**Comment by njbmartin** [comment] 2018-01-16 00:11
![image](https://user-images.githubusercontent.com/5699471/34966149-8c0d9e10-fa51-11e7-9afa-112cb63a1d27.png)

Above is the request using `v0.52.0`.

**The difference is the request header has `Origin: http://localhost:8081`**

**Comment by mikeborozdin** [comment] 2018-01-16 20:28
Hi @njbmartin,

You've saved my life! 

I've upgraded to 0.52.0 as well and noticed that it wouldn't run on iOS with Remote Debugger On.

The 0.52.0 release seems to be quite buggy. I already wasted quite a few hours fighting with another issue that wouldn't let me build an app - #17274.

So, could you possibly change the title of this issue to something more alarming, so that the react-native maintainers notice it? Something like "Remote Debugging Doesn't Work on 0.52.0"?

**Comment by zjiayingok** [comment] 2018-01-17 03:01
I met the same problem on 0.52.0。
1.Unable to load script from assets 'index.android.bundle'. Make sure your bundle is packaged correctly or you're running a packager server.
2.http://localhost:8081/index.delta?platform=android&dev=true&minify=false
3.com.facebook.react.common.DebugServerException: Could not connect to development server.

**Comment by mobdim** [comment] 2018-01-17 09:29
I have same issue.

**Comment by njbmartin** [comment] 2018-01-17 09:55
Looks like there was a lot of oversight in this release.

I too faced the other issue #17274, fixed using the podfile workaround.

For this issue, I think it's definitely `metro` or one of it's dependancies as I had a brief success downgrading the version.

**Comment by hugoh1995** [comment] 2018-01-17 16:47
Facing the same issue with 0.52.

**Comment by itinance** [comment] 2018-01-18 14:27
Facing the same without xip.io, just with IP-address of my Macbook while running application on device per ip-address of my working machine.

It happens only when debug-mode was enabled and failed then to load the code. Without debug-mode everything works as expected:

> Failed to load http://192.168.178.24:8081/index.delta?platform=ios: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8081' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.


I have already whitelisted this IP-Address and also localhost in Info.plist:
```

 <key>NSAppTransportSecurity</key>
 <dict>
 <key>NSExceptionDomains</key>
 <dict>
 <key>localhost</key>
 <dict>
 <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
 <true/>
 </dict>
            <key>192.168.178.24</key>
            <dict>
                <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
                <true/>
            </dict>
 </dict>
 </dict>

```
But it still appears. At the end the ReactNative Application can't load its code while Debug-Mode is enabled. Without debug mode everything works as expected. Any ideas?

**Comment by RodrigoCS** [comment] 2018-01-18 16:24
This is happening to me as well rn 0.52.0 only when debugging js remotely

**Comment by cagataycali** [comment] 2018-01-18 22:51
Same here 🤙

**Comment by luanfelipecosta** [comment] 2018-01-19 18:28
Same here, I downgraded to react-native to *0.51.0* and react to *16.0.0*  it works well in iOS Simulator even with the inspector on, but if I try to run in a real device (iPhone 7) I still got the issue.

**Comment by cagataycali** [comment] 2018-01-19 18:35
@luanfelipecosta I did not downgraded react to *16.0.0*, it works in real device. You should try upgrade react.

**Comment by export-mike** [comment] 2018-01-20 01:45
I've downgraded to react-native@0.51.0 & react@16.0.0, I'm getting the issue still - No idea but could this be a chrome related? Chrome: Version 63.0.3239.132

**Comment by njbmartin** [comment] 2018-01-21 02:37
I'm not sure it is Chrome related, as I was able to downgrade to 0.51 and it works just fine. Take a look at the screenshots above. Something, somewhere, is adding `origin: localhost` in 0.52

**Comment by njbmartin** [comment] 2018-01-21 04:01
As an even better workaround... replace `http://localhost:8081/debugger-ui/` with `http://192.168.0.13.xip.io:8081/debugger-ui/` or whatever the ip is.

**Comment by cagataycali** [comment] 2018-01-21 04:03
That's not usable for daily development environment. @njbmartin

**Comment by mmazzarolo** [comment] 2018-01-22 09:12
I'm having the same issue on:
- MacOS Sierra
- React-Native 0.52.0

Simply downgrading to React-Native 0.51.0 (by just running `npm i -S react-native@0.51.0` seems to fix the issue.

**Comment by mgscreativa** [comment] 2018-01-23 19:17
I'm using CRNA and for a workaround I used **http://10.0.0.2:19001/debugger-ui/** where 10.0.0.2 is my LAN Ip address

**Comment by jugutier** [comment] 2018-01-23 20:46
👍  +1 on this, same issue for me:

"Failed to load http://10.0.1.57.xip.io:8081/index.delta?platform=ios&dev=true&minify=false: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8081' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
(index):188 Uncaught (in promise) TypeError: Failed to fetch"

**Comment by njbmartin** [comment] 2018-01-24 00:00
For those having an issue with this, please check out the PR and see if that fixes the issue for you.

**Comment by Sw0rdstream** [comment] 2018-01-25 14:36
As a workaround, simply change your URL of Chrome from http://localhost:8081/debugger-ui/ to http://192.168.XXXX.XXXX.xip.io:8081/debugger-ui/

**Comment by ou2s** [comment] 2018-01-25 16:42
Same issue with 0.52... Critical bug for me. I think we are also going to downgrade RN 0.51 :(

**Comment by ankitkante** [comment] 2018-01-27 05:15
Facing this issue even in 0.53

**Comment by laughingguffly** [comment] 2018-01-27 13:34
Same problem here. Follow Sw0rdstream work around fixed for me.

**Comment by njbmartin** [comment] 2018-01-27 20:40
A fix #17720 was merged in to master. Hopefully it won't be long before it's released as `0.52.3` and `0.53.0-rc.2`

**Comment by Haixiang6123** [comment] 2018-01-29 17:19
Same problem with RN version 0.53, sigh~

**Comment by njbmartin** [comment] 2018-01-31 12:05
@ide Any plans to release this as a `0.52.3` hotfix?

**Comment by ide** [comment] 2018-01-31 12:29
No plans from me but we can cherry pick it into the upcoming 0.53 release.

**Comment by esam091** [comment] 2018-02-02 10:34
It is possible to monkey patch if you can't wait for new release
- Copy the contents of [this file](https://raw.githubusercontent.com/facebook/react-native/df8da3b6c4038c066e12530fc66a1563bd3f58b7/local-cli/server/middleware/getDevToolsMiddleware.js) and paste it into `node_modules/react-native/local-cli/server/middleware/getDevToolsMiddleware.js`
- Install [`patch-package`](https://github.com/ds300/patch-package) by running `yarn add --dev patch-package postinstall-prepare`
- Run `yarn patch-package react-native`, a file should be created in `patches/react-native+0.52.patch`, this file needs to be committed in your repository
- Add the following script into your package.json and run `yarn install`, or you can run `yarn patch-package` directly if needed
  ```
  "scripts": {
    "prepare": "patch-package"
  }
  ```

You can find more details on monkey patching in [`patch-package`](https://github.com/ds300/patch-package) repo.

**Comment by xieliying** [comment] 2018-02-03 15:03
Same program here (react-native version 0.52.2), then I downgrade to 0.51.0, it still happened......
But finally I have found a way to solve this problem, maybe it can help you
And now react-native Version is 0.51.0,
react version is 16.0.0,
run on my iPhone X and Simulator, everything is OK.

1. Start remote JS Debugging in your device or your simulator;
2.Then open your Chrome, you will see a "React Native Debugger" page;
3.New a Tab, type [chrome://apps/](url), then search "react developer tools", download and install it;
4.If react developer tools did not work, new a tab, type [chrome://extensions/](url), and enter extensions manager;
5.Find React Developer Tools, enabled "Allow access to file URLs";
6.After finished above, go back to your iPhone or your Simulator, reload your RN App;

**Comment by TheDutchCoder** [comment] 2018-02-07 18:16
We face the same issue. Unsure how this is not a high priority candidate for a fix, I guess people don't need to debug their code on real devices?

We will downgrade to `0.51.0` to see if it fixes the issue. Will edit this post with an update.

**Comment by ide** [comment] 2018-02-07 18:26
@njbmartin sent a PR to fix this two weeks ago (thank you!), which was merged and released with 0.53.x.

**Closed by ide** 2018-02-07 18:26 UTC

**Comment by wjielim** [comment] 2018-02-13 09:00
After upgrading React Native to 0.53.0, the problem still exists. Please advise, thank you.

**Comment by dmueller39** [comment] 2018-02-13 16:29
Remember to restart your packager and restart your browsers (or at least the debugger tab) after upgrading.

**Comment by cagataycali** [comment] 2018-02-14 01:25
Upgrade `0.53.0` then `watchman watch-del-all && react-native start --reset-cache`. That will work for you guys.

**Comment by akash-cp** [comment] 2018-02-14 12:03
If you are on 0.53.0 then change IP to localhost.

**Comment by arunharidas** [comment] 2018-02-15 06:17
Thanks @akash-cp it worked!

**Comment by luanfelipecosta** [comment] 2018-02-16 12:28
I am using expo, when I updated for 0.53, I got a error: 
**react version mismatch between react-native 0.53.0 and native-scripts 0.52**

**package.json**:
```
"expo": "^25.0.0"
"react": "16.2.0"
"react-native": "0.52.0"
```

**Comment by KangYoosam** [comment] 2018-02-16 12:30
+1

**Comment by kanteankit** [comment] 2018-02-16 12:38
I am facing the same issue as @luanfelipecosta. I have the same package.json.
I tried running `watchman watch-del-all && react-native start --reset-cache`,but it did not fix it. I tried deleting the node_modules and re-installing the packages, that also doesn't fix the issue.
I think we should wait for this doc to get updated: https://github.com/react-community/create-react-native-app/blob/master/VERSIONS.md.

**Comment by njbmartin** [comment] 2018-02-16 12:59
The latest version of `expo` uses `react-native@0.52` and therefore any projects created using `CRN` might face this issue.

The fix I did was not hotfixed into `0.52` but is available in the latest `react-native@0.53`.

As `CRN` is now the default method of creating React Native apps, either `expo` needs to be updated to use `0.53` or this fix needs to be hotfixed in `0.52`.

**Comment by luanfelipecosta** [comment] 2018-02-16 13:12
@kanteankit 
a workaround for this problem (who is using expo) is install a CORS Toggle in google chrome. 
http://bit.ly/2o4mVNI
for me worked as a charm.

**Comment by kanteankit** [comment] 2018-02-16 13:29
@njbmartin So what you are saying is we should wait for Expo to release a new version that supports `react-native@0.53`

**Comment by Monte9** [comment] 2018-02-19 03:31
@njbmartin ah yes. You are right, I was using expo sdk 25 and ran into this issue.

@luanfelipecosta's suggestion works for me. Thanks man!

**Comment by wjielim** [comment] 2018-02-22 06:45
I'm still facing the same issue. I've tried all the possible solutions stated above but to no avail. 
I have tried to upgrade RN to 0.53.3, yet it still gives the same problem. 
Am on expo version 25.0.0.

**Comment by tomcrusader** [comment] 2018-02-22 14:12
Google Chrome plugin COORS Toggle as @luanfelipecosta suggested, works awesome ( http://bit.ly/2o4mVNI )

**Comment by vinceyuan** [comment] 2018-02-23 12:36
Upgrade react native to 0.53.3
`watchman watch-del-all && react-native start --reset-cache`
Start Remote JS Debugging
If the URL in Chrome is not `http://localhost:8081/debugger-ui/`, change it.

**Comment by jeffbonasso** [comment] 2018-02-24 11:44
Upgraded to 0.53.3 and ran command watchman watch-del-all && react-native start --reset-cache.

Get this when launch in Debug mode...
[debug-issue-google-photo](https://photos.app.goo.gl/aLujzW5eNQudbFuh1)

**Comment by kenturley** [comment] 2018-02-26 23:40
Been getting this since about the same time this Issue appeared (Jan 15). Any time I create a CRNA app and try to debug it with Chrome.  To get by, I would downgrade Expo and react native to previous versions: EXPO SDK to 24, React to 16.0.0, React Native to 0.51.x (matching the row shown for Expo SDK version 24.0.0. at https://github.com/react-community/create-react-native-app/blob/master/VERSIONS.md).  I hadn't created a new CRNA app for a few weeks until today. Tried it and got the same thing.  Came back here to see if there was any new news and saw the Google CORS Toggle suggestion from @luanfelipecosta. As others have reported, it works great. Hopefully this problem will get resolved before long, but until then, the CORS toggle is a quick and painless fix. Thanks  @luanfelipecosta!

**Comment by dgrcode** [comment] 2018-02-28 20:39
CORS Toggle might work great, but they ask for the permission "Read and change all your data on the websites that you visit"

**Comment by jackwilsdon** [comment] 2018-03-01 09:01
@dgrcode you can find the source of it here if you're worried; https://github.com/demesne/cors-toggle

**Comment by mrharel** [comment] 2018-03-06 22:47
`react-native@0.54.0` removed the use of `xip.io` which should solves this issue without the need for all the hacks suggested above. You can read more about it in the commit [40a8434](https://github.com/facebook/react-native/commit/40a8434)

**Comment by julioe** [comment] 2018-03-12 05:14
Try to install [CORS toggle extension](https://chrome.google.com/webstore/detail/cors-toggle/jioikioepegflmdnbocfhgmpmopmjkim?hl=en), it helped me with similar problem

**Comment by arapocket** [comment] 2018-03-20 17:12
I updated to `react-native@0.54.0` still have the same issue.

**Comment by MaxInMoon** [comment] 2018-03-23 20:57
Looking the [changelog](https://github.com/facebook/react-native/releases), it should be fixed in the 54.0:

"Fix JS debugger issues related to CORS ([29f8354](https://github.com/facebook/react-native/commit/29f8354))"

**Comment by alainib** [comment] 2018-04-04 12:39
i have this error on mac with 
    "react": "^16.3.1",
    "react-native": "0.55.0",

**Comment by hery** [comment] 2018-04-06 09:15
@alainib These warnings are intended and expected behavior

**Comment by rayronvictor** [comment] 2018-04-08 14:17
Using `http://localhost:8081/debugger-ui/` instead of `http://192.168.0.21:8081/debugger-ui/` worked for me.

**Comment by zouyan532** [comment] 2018-04-11 07:46
Thanks @akash-cp it worked!

**Comment by AyubaMakoa** [comment] 2018-04-22 15:39
rayronvictor style solved my problem too.

**Comment by roadev** [comment] 2018-04-23 02:07
disabling the CORS plugin in chrome made it work!

**Comment by roadev** [comment] 2018-04-26 13:40
Just ... click on it (on the chrome plugins bar - right side) and disable the "Enable cross-origin resource  sharing".

**Comment by arfa123** [comment] 2018-05-02 13:43
The solution for this problem is simply install the extension "Allow-Control-Allow-Origin" in your chrome browser. this works for me you all can try.

**Comment by letanthang** [comment] 2018-05-08 09:46
@arfa123 You save my day! Thanks. The extension "Allow-Control-Allow-Origin" .
Just remember to disable it when not using because i cause trouble with some website.

**Comment by zhcsyncer** [comment] 2018-05-09 03:40
If you also use Webstorm, you can do this.

![image](https://user-images.githubusercontent.com/13214840/39794620-cdf9519a-537d-11e8-815c-93258612d87a.png)

**Comment by efleurine** [comment] 2018-05-12 22:26
like @rayronvictor Using `http://localhost:8081/debugger-ui/` instead of `http://192.168.0.21:8081/debugger-ui/` worked for me.

**Comment by 0xc0d3r** [comment] 2018-05-16 04:57
IDK why it's happening with 0.53. For now we can proceed with `localhost` instead of your machine IP address. `http://localhost:8081/debugger-ui/`

**Comment by bsbechtel** [comment] 2018-05-27 11:47
I'm having this issue with RN 0.55.4. Localhost or my machine's IP didn't work. The only thing that worked for me was disabling CORS via the chrome extension.

**Comment by JustinReport** [comment] 2018-06-06 21:36
not work for me.

**Comment by erdemoflaz** [comment] 2018-06-09 19:50
problem solved, it's work me. **http://localhost:8081/debugger-ui/**

**Comment by crazy4groovy** [comment] 2018-09-13 17:37
Note that http://127.0.0.1:8081/debugger-ui/ specifically doesn't seem to work, for CORS reasons.

**Comment by yusufdonmez** [comment] 2018-11-22 13:19
In my case it is solved by deleting in Application debug menu "Dev Stettings" -> "Debug server host & port for device" erase all ip and port. after that it works again. JS Debug Remotly.

**Comment by jerryheir** [comment] 2018-12-19 11:20
Working with RN 0.55.4, Iphone 12.1.1, google chrome latest as of Dec, 2018. 
I solved it by using my IP address instead of "localhost"
```http://192.168.0.21:8081/debugger-ui/```

**Comment by naytun** [comment] 2019-01-01 23:02
Adding this Extension to Chrome solves this issue:
[Allow CORS: Access-Control-Allow-origin](https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=en)
