### ISSUE TITLE
Android Text's paddingTop is not working on 0.19 or 0.20

### ISSUE THREAD

**Issue by pickhardt** [facebook/react-native#5921] opened 2016-02-14 20:51 UTC
I am surprised this hasn't been reported before, but it appears to be a new issue. I believe paddingTop doesn't work on Texts on Android. Here is an example RNPlay demonstrating it:

https://rnplay.org/apps/xRcJKw

![screen shot 2016-02-14 at 12 51 04 pm](https://cloud.githubusercontent.com/assets/610082/13036341/ac1f635c-d319-11e5-986b-bb16bd0bf52b.png)

![screen shot 2016-02-14 at 12 50 58 pm](https://cloud.githubusercontent.com/assets/610082/13036342/ac20aa00-d319-11e5-9dfe-f76b380c85c9.png)

**Comment by xiaobuu** [comment] 2016-02-15 04:21
+1

**Comment by toadums** [comment] 2016-02-16 22:46
I think it is because android's text elements dont support padding

https://github.com/facebook/react-native/issues/3233

**Comment by satya164** [comment] 2016-02-17 05:04
Duplicate of #3233

**Closed by satya164** 2016-02-17 05:04 UTC
Labels: Android
