### ISSUE TITLE
Unable to run React-Native V0.45 project

### ISSUE THREAD

**Issue by maheshiv** [facebook/react-native#14732] opened 2017-06-26 20:16 UTC
I created sample app using react-native v0.45. When I run the code using `react-native run-ios`, I am getting below error
```
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/mahesh/MaheshApps/SampleApp/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/third-party.build/Objects-normal/x86_64/Conv.o /Users/mahesh/MaheshApps/SampleApp/node_modules/react-native/third-party/folly-2016.09.26.00/folly/Conv.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/SampleApp.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/SampleApp.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

Additional information
```
Environment:
  OS:  macOS Sierra 10.12.3
  Node:  v7.7.1
  Yarn:  0.22.0
  npm:  4.1.2
  Xcode:  Xcode 8.3.1 Build version 8E1000a 
Print: Entry, ":CFBundleShortVersionString", Does Not Exist
Print: Entry, ":CFBundleVersion", Does Not Exist
Android Studio not found in typical install location
  Android Studio:  Not Found
  react:  16.0.0-alpha.12
  react-native:  0.45.1
```

**Comment by hramos** [comment] 2017-06-26 20:17
There's already several issues open that mention this error (CFBundleIdentifier does not exist). Closing as duplicate.

**Closed by hramos** 2017-06-26 20:17 UTC

**Comment by hramos** [comment] 2017-08-04 06:47
Duplicate of #14423
