### ISSUE TITLE
BackgroundColor animates for no reason

### ISSUE THREAD

**Issue by bartlomiejbloniarz** [facebook/react-native#47011] opened 2024-10-14 11:21 UTC
### Description

When changing the `backgroundColor` of a `FlatList` item, there is an animation between these colors. The bug is reproducible both on the 0.76 RCs and main.

### Steps to reproduce

1. paste the snack `App.js` code to RNTester
2. click `toggle theme`

### React Native Version

0.76.0-rc.4, main

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.6.1
  CPU: (8) arm64 Apple M1 Pro
  Memory: 97.02 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 22.9.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.8.3
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.10.07.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/bartlomiejbloniarz/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.0
      - iOS 18.0
      - macOS 15.0
      - tvOS 18.0
      - visionOS 2.0
      - watchOS 11.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.21829.142.2421.12409432
  Xcode:
    version: 16.0/16A242d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /opt/homebrew/opt/openjdk@17/bin/javac
  Ruby:
    version: 3.2.2
    path: /Users/bartlomiejbloniarz/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Stacktrace or Logs

```text
-
```

### Reproducer

https://snack.expo.dev/Tg8ResSSqSuiNHOg3iCq5

### Screenshots and Videos

https://github.com/user-attachments/assets/0781cb3d-71f4-4845-8a88-cb3f957fc6df

**Comment by shubhamguptadream11** [comment] 2024-10-14 12:17
@bartlomiejbloniarz What according to you should be an expected behaviour? It changes colour smoothly.

**Comment by bartlomiejbloniarz** [comment] 2024-10-14 12:48
@shubhamguptadream11 It should change instantaneously, as there is no animation being used.

**Comment by cortinico** [comment] 2024-10-15 13:07
> The bug is reproducible both on the 0.76 RCs and main.

Has this regressed since 0.75? Asking as there has been ongoing work on Backgrounds recently (cc @NickGerleman )

Also does this reproduces on both Android & iOS?

**Comment by bartlomiejbloniarz** [comment] 2024-10-15 13:24
Yes, it worked fine on the previous version (I think this bug was also present in some older version, but was quickly fixed).

It only reproduces on iOS in both debug and production builds.

**Comment by cortinico** [comment] 2024-10-15 14:50
> It only reproduces on iOS in both debug and production builds on the New Architecture.

So is this New Architecture **only**?

> Yes, it worked fine on the previous version 

Do you confirm that this regresses in 0.76 so that it was working in 0.75 iOS NewArch?

**Comment by bartlomiejbloniarz** [comment] 2024-10-15 15:10
> So is this New Architecture only?

yes
> Do you confirm that this regresses in 0.76 so that it was working in 0.75 iOS NewArch?

yes

**Comment by cortinico** [comment] 2024-10-21 17:17
Fixed by https://github.com/facebook/react-native/pull/47101

**Closed as completed by cortinico** 2024-10-21 17:17 UTC
Labels: Issue: Author Provided Repro, Resolution: Fixed, Partner, p: Software Mansion

**Comment by NickGerleman** [comment] 2024-10-22 09:17
@joevilches I remember you were wanting to pick this one? Could you make a request, so it might show up in future patch? (Since new regression)
