### ISSUE TITLE
Inconsistent absolute line-height rendering as system text size changes in iOS

### ISSUE THREAD

**Issue by normanzb** [facebook/react-native#46609] opened 2024-09-23 19:10 UTC
### Description

The line-height renders differently when iOS text size setting changed, the line-height with a absolute value should stay the same no matter how iOS text size is set.

### Steps to reproduce

1. create an `<View style={{ width: 10, height: 32, backgroundColor: 'red' }} />` element with height set to 32.
2. create an `<Text style={{ lineHeight: 32 }}>here is a demo text</Text>` element with line-height also set 32.
3. put these 2 elements side by side in a flex-col element.
4. these 2 elements should be rendered with same height
5. go to iOS accessibility setting, change font size to slightly smaller.
6. go back to the app.

expected result:

the 2 elements still renders with same height

actual result:

the 2 elements renders with different height, with the text element being smaller.

### React Native Version

0.74.5

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
info Fetching system and libraries information...
System:
  OS: macOS 14.5
  CPU: (10) arm64 Apple M1 Max
  Memory: 1.59 GB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.17.0
    path: ~/.n/bin/node
  Yarn: Not Found
  npm:
    version: 10.8.2
    path: ~/.n/bin/npm
  Watchman:
    version: 2024.09.09.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/xxxx/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2411.12169540
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 3.1.4
    path: /Users/xxxx/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.5
    wanted: 0.74.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

info React Native v0.75.3 is now available (your project is running on v0.74.5).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.75.3
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.74.5
info For more info, check out "https://reactnative.dev/docs/upgrading?os=macos".
```

### Stacktrace or Logs

```text
no crash
```

### Reproducer

https://snack.expo.dev/@normanmodprotocol/frowning-violet-bagel

### Screenshots and Videos

default ios font size setting (correct):

<img width="462" alt="image" src="https://github.com/user-attachments/assets/169005b6-9b4e-4d25-8fd8-dec0f9f5547f">

ios font size set to smallest (incorrect):
<img width="459" alt="image" src="https://github.com/user-attachments/assets/1c4c7a9c-34b4-4033-b07d-b24282fce5da">

ios font size set to largest:
<img width="457" alt="image" src="https://github.com/user-attachments/assets/6e628d37-ddd0-487a-8271-637bc5d14de0">

**Comment by normanzb** [comment] 2024-09-23 19:17
tested on 0.74.5, still reproducible

**Comment by cortinico** [comment] 2024-09-24 10:31
> tested on 0.74.5, still reproducible

Can you test it on 0.76.0 RC2 also?

**Comment by normanzb** [comment] 2024-09-24 13:29
> 0.76.0 RC2

it is partially fixed in 0.76.0 RC2, 
when text size in iOS setting is smaller, the line-height does not shrink anymore (correct):

<img width="509" alt="image" src="https://github.com/user-attachments/assets/17a441ae-9b9c-45dd-b37b-19376e43e5cd">

however when text size in iOS setting is larger, the line-height still increases (incorrect, the text in screenshot is really small, should not cause line-height to increase):

<img width="508" alt="image" src="https://github.com/user-attachments/assets/740b2dac-354c-48e1-b327-52639da63094">

**Comment by SimpleCreations** [comment] 2024-09-28 11:53
I think the old behavior is the expected one — `lineHeight`, just like `fontSize`, is expressed in font size points, so it changes based on system font scale.

I see the new behavior as a regression, because you can see on @normanzb's screenshot that the text is not centered anymore after decreasing font scale.

**Comment by normanzb** [comment] 2024-09-30 11:54
> I think the old behavior is the expected one — `lineHeight`, just like `fontSize`, is expressed in font size points, so it changes based on system font scale.
> 
> I see the new behavior of 0.76 as a regression, because you can see on @normanzb's screenshot that the text is not centered anymore after decreasing font scale.

I think since there is no `unit` specified in the value fields, the correct/intuitive interpretation is `height and line-height are using the same unit`, hence if the `line-height` changes according to system font size, then so does `height`.

**Comment by SimpleCreations** [comment] 2024-09-30 12:07
This is a matter of opinion and proper documentation. However, changing the old behavior should not be taken lightly. It would be a major breaking change that would affect many apps.

**Comment by normanzb** [comment] 2024-10-01 13:37
please notice that if we depart line-height and font-size from the rest without specifying the unit explicitly, it can be seen as a departure from the web standard, as consequence making it extremely difficult to build something that will looks and feel the same for both web and native using RN.

**Comment by SimpleCreations** [comment] 2024-10-16 22:09
Hi @normanzb, I've tried your example on `0.76.0-rc.5` (iOS, oldarch), and the behavior is the same as on `0.75.4` — the effective `lineHeight` value is reduced when font scale is reduced. There's no regression between 0.75 and 0.76 here (at least on oldarch).

![Untitled3463546456](https://github.com/user-attachments/assets/25e6b5a4-d7d1-4fed-a595-e68efd5d1c67)

**Comment by SimpleCreations** [comment] 2024-10-16 22:12
@cortinico we should probably close this issue. What OP is reporting is not a bug and is working as intended; while some might find the current behavior more confusing than others, we cannot change the behavior of the `lineHeight` property because it would be a major breaking change affecting every single app out there.

**Closed** 2024-10-25 22:32 UTC
Labels: Platform: iOS, Issue: Author Provided Repro, Newer Patch Available
