### ISSUE TITLE
[0.31] Android - Promise never fulfilled or rejected when using chrome remote debugger

### ISSUE THREAD

**Issue by bilewinters** [facebook/react-native#9415] opened 2016-08-15 17:40 UTC
```
import { AsyncStorage } from 'react-native';
AsyncStorage.getItem("@MY_SPECIAL_KEY").then(
    result => console.log("Got a result", result),
    error => console.log("Got an error", error)
);
```

When I execute this and check my logs using `react-native log-android` I predictably get:
_08-15 17:30:54.604 25707 25983 I ReactNativeJS: 'Got a result', null_

However, executing while connected to chrome in order to debug, I get nothing.

I'm using Chrome on Windows 10, and react-native 0.31. If anyone can reproduce, or not, on any other OS I'd like to hear about it.

**Comment by alenia** [comment] 2016-08-15 18:58
This is a dup of https://github.com/facebook/react-native/issues/9319

**Comment by satya164** [comment] 2016-08-15 19:11
Closing as duplicate of #9319

**Closed by satya164** 2016-08-15 19:11 UTC
