### ISSUE TITLE
TabBarIOS tintColor for unselected items

### ISSUE THREAD

**Issue by ecesena** [facebook/react-native#4400] opened 2015-11-28 22:09 UTC
Nice to have

**Comment by christopherdro** [comment] 2015-11-28 22:14
Hey @ecesena! Closing this since it's a duplicate of #3083.

**Closed by christopherdro** 2015-11-28 22:14 UTC

**Comment by ecesena** [comment] 2015-11-28 22:22
Ops, sorry... I searched for unselected, didn't think to inactive... :)

**Comment by christopherdro** [comment] 2015-11-28 22:23
:+1: No worries :)
