### ISSUE TITLE
Packager / server only logs 'Failed building JavaScript bundle' and does not indicate the problematic file

### ISSUE THREAD

**Issue by MFAshby** [facebook/react-native#15841] opened 2017-09-06 22:21 UTC
### Is this a bug report?

Yes.

### Environment

1. `react-native -v`: 0.47.2
2. `node -v`: 6.11.2
3. `npm -v`: 3.10.10
- Target Platform: Android
- Development Operating System: Linux, Ubuntu 17.04
- Build tools: just react-native

### Steps to Reproduce

0. Attach Android device or emulator.
1. Clone the example project. `git clone https://github.com/MFAshby/failuretest.git`
2. Run `npm start`, in the project folder, then press `a` to run on attached Android device.
3. Get the below text in the console window for packager and development server.

> 11:09:39 PM: Starting Android...
> › Press a to open Android device or emulator, or i to open iOS emulator.
> › Press q to display QR code.
> › Press r to restart packager, or R to restart packager and clear cache.
> › Press d to toggle development mode. (current mode: development)
> 11:09:41 PM: Launching Dev Tools...
> 11:09:57 PM: Failed building JavaScript bundle
> 11:09:57 PM: 
> 11:09:57 PM: 

### Expected Behavior

I would expect some kind of indication as to what bit of javascript is invalid (i.e. file and line number)

### Actual Behavior

There is no indication where the javascript syntax is invalid. This slows the development process 'cos now I can't easily see where I've made syntax errors!

**Comment by findzen** [comment] 2017-10-19 23:53
Please reopen. Regardless of the steps to reproduce, error messages should give more information than "Failed building JavaScript bundle". Is there a verbose option, or a log somewhere with more information?

**Comment by MFAshby** [comment] 2017-10-20 09:00
I followed the template as requested. Reproduction information is right there under 'steps to reproduce'.

**Comment by hramos** [comment] 2017-10-20 14:27
I've updated your issue to include a missing part of the template. This should keep the bot from closing your issue again.

**Comment by jmatsushita** [comment] 2017-10-25 15:31
Given the information is not missing, I think the labels should also be removed no ?

**Comment by Hacalox** [comment] 2017-11-25 15:59
Please delete the labels of this issue, all the info is on the OP post.
For the moment, how do you guys go through this? I can't handle this anymore, my developing time has increased a lot due to lack of info when writing code and receiving an error.

**Comment by Alexintosh** [comment] 2017-11-28 16:37
Will downgrading solve the issue? Which version?

**Comment by MFAshby** [comment] 2017-11-28 17:23
Don't know. Try following the reproduction steps, then downgrade and try again.

**Comment by theSMguy** [comment] 2017-12-07 15:01
I have the same issue, my node ver is 8.9.2 and my npm ver is 5.5.1

**Comment by jmatsushita** [comment] 2017-12-17 12:37
It seems that this error comes from the `react-native-scripts` package on [this line](https://github.com/react-community/create-react-native-app/blob/master/react-native-scripts/src/util/packager.js#L199).

**Comment by jmatsushita** [comment] 2017-12-17 14:32
I'm using `expo` and deactivating the remote debugger (shaking the phone and clicking stop remote debugging) makes the bundler error message show up on the phone. Better than nothing.

**Comment by joeytwiddle** [comment] 2018-01-10 05:56
Usually this error is displayed in Expo, but sometimes Expo won't show it, either because:
- The build failed on the first time, so nothing was pushed to Expo
- The previous build failed. Expo shows the error from the previous build, but not the new error!

For those of you who are stuck in a situation where Expo is not showing the error... I managed to get the error logged, but it wasn't pretty!

Starting with jmatsushita's pointer I made the following changes:

```diff
## In node_modules/react-native-scripts/build/util/packager.js
        _log2.default.withTimestamp(_chalk2.default.red('Failed building JavaScript bundle'));
+       _log2.default.withTimestamp(String(err));
## There are two lines where you can do this
## But this only showed the error: "Failed to build bundle", so I went to track that down...

## In node_modules/xdl/build/logs/PackagerLogsStream.js
-     bundleError = new Error('Failed to build bundle');
+     bundleError = new Error('Failed to build bundle: ' + JSON.stringify(msg));
## This still didn't contain the error, but I could find where this message originated...

## In node_modules/metro-bundler/src/Server/index.js
## We can include the original error in the message object
      this._reporter.update({
        buildID,
-       type: 'bundle_build_failed' });
+       type: 'bundle_build_failed',
+       error: error });
## There are four places where you can do this!
```

This got the error displayed on the console. But there must be an easier way... Running a build manually?

**Comment by jordan-realfoto** [comment] 2018-05-24 00:08
Any word on this? This is most certainly a high priority.

**Comment by csalvato** [comment] 2018-06-01 20:51
This is making it ridiculously difficult to do any development. I have a syntax error somewhere in my code that I have been hunting for 3 hours.

Unfortunately, @joeytwiddle's hack doesn't help me much either..it just produces this:

```
2:47:22 PM: Failed building JavaScript bundle
2:47:22 PM: Error: Failed to build bundle: {"buildID":"1","type":"bundle_build_failed"}
```

**Comment by cjol** [comment] 2018-07-16 10:21
This is really crazy - I have spent hours tracking down a solution. joeytwiddle's [workaround](https://github.com/facebook/react-native/issues/15841#issuecomment-356507549) _does_ work, but I found the code in slightly different locations. `grep -R "Failed building JavaScript bundle" **/*.js` in the `node_modules` located the right places for me. (it looks like csalvato hasn't made the third edit, which I made in 4 different places in the file, just to be sure).

**Comment by hpatel123** [comment] 2018-09-07 14:08
Still issue doesn't resolved. Please help me. I am stuck since 3 days.

**Comment by Velua** [comment] 2018-10-29 07:36
> One option is to enable debug logging
> 
> ```
> DEBUG='Metro:*' npm run start
> ```
> which will (among ridiculous amounts of noise) also output where the error is. Search for the line containing `msg: '{"error":{"moduleName":"`

Good one mate, this has saved me a whole lot of stress haha just to add onto that..

    DEBUG='Metro:*' npm run start > log.txt

I found easier for traversing the 40,000 lines I received!

**Comment by hramos** [comment] 2019-02-25 20:35
This issue hasn't been updated in a while. If anyone is still running into this, please go ahead and open a new, separate issue. This will help us debug the situation individually. When a thread gets to this size, it's hard to keep track when each problem is actually related to the original post.

**Closed by hramos** 2019-02-25 20:35 UTC
Labels: Resolution: Old Version, Type: Bug Report, 📦Bundler
