### ISSUE TITLE
2 non-performing functions

### ISSUE THREAD

**Issue by dennisobel** [facebook/react-native#13520] opened 2017-04-15 13:25 UTC
So basicaly, handleLapPress() and handleStartPress() aren't doing what they supposed to. When clicked, handleStartPress() is supposed to run timer, when pressed again, it's supposed to stop timer. handleLapPress is supposed to log the laps on screen. help. 

[index.android.js.txt](https://github.com/facebook/react-native/files/923614/index.android.js.txt)

var formatTime = require('minutes-seconds-milliseconds');
import React, { Component } from 'react';
import { AppRegistry,
    Text ,
    StyleSheet,
    View,
    TouchableHighlight,
    } from 'react-native';

class AwesomeProject extends Component {

  constructor(props){
	super(props);
	this.state = {
	timeElapsed: null,
	running: false,
	startTime: null,
	laps: []
	};
	}  

  render() {
    return (
    <View style={styles.container}>
        <View style={[styles.header]}>
            <View style={[styles.timerWrapper]}>
                <Text style={styles.timer}>
                    {formatTime(this.state.timeElapsed)}
                </Text>
            </View>
            <View style={[styles.buttonWrapper]}>
                {this.startStopButton()}
                {this.lapButton()}
            </View>
        </View>
        <View style={[styles.footer]}>
            <Text>
                {this.laps()}
            </Text>
        </View>
    </View>

    );

  }

  laps(){
          this.state.laps.map(function(time, index){
              return
              <View style={styles.lap}>
                  <Text style={styles.lapText}>Lap #{index + 1}</Text>
                  <Text style={styles.lapText}>{formatTime(time)}</Text>
              </View>
          })
      }

  startStopButton(){
    var style = this.state.running ? styles.stopButton : styles.startButton;
    return (
        <TouchableHighlight
        underlayColor="grey"
        onPress={()=>{this.handleStartPress()}}
	style =  {[styles.button, style]}>
            <Text>
               {this.state.running ? 'Stop' : 'Start'}
            </Text>
        </TouchableHighlight>
    );
  }

  lapButton(){
    return (
        <TouchableHighlight
        style={styles.button}
        underlayColor="grey"
        onPress={()=>{this.handleLapPress}}>
            <Text>
                Lap
            </Text>
        </TouchableHighlight>
    );
  }

  handleLapPress(){
    var lap = this.state.timeElapsed;
    this.setState({
        startTime: new Date(),
        laps: this.state.laps.concat([lap])
    });
  }

  handleStartPress(){
    if(this.state.running){
    	clearInterval(this.interval);
	    this.setState({running: false});
    	return
	}

    this.setState({startTime: new Date()});

    this.interval = setInterval(() => {
    this.setState({
        timeElapsed: new Date() - this.state.startTime,
	    running: true
    });
  }, 30);
  }
  }

  var styles = StyleSheet.create({
    container : {
        flex: 1, //Fill the entire screen
        alignItems: 'stretch'
    },

    header:{//yellow
        flex: 1
    },

    footer:{//blue
        flex: 1
    },

    timerWrapper:{
        flex: 5,
        justifyContent: 'center',
        alignItems: 'center'
    },

    buttonWrapper:{
        flex: 3,
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center'
    },

    timer:{
	fontSize : 60
    },

    button:{
	borderWidth: 2,
	height: 80,
	width: 80,
	borderRadius: 50,
	justifyContent: 'center',
	alignItems: 'center'
    },

    startButton:{
	borderColor:'green'
    },

    stopButton:{
	borderColor: 'red'
    },

    lap:{
        justifyContent: 'space-around',
        flexDirection: 'row'
    },

    lapText:{
        fontSize: 30
    }
  });

AppRegistry.registerComponent('AwesomeProject', () => AwesomeProject);

**Comment by petrbela** [comment] 2017-04-15 20:58
Please read https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md before creating an issue.

This is not a bug in RN. You should post your question on StackOverflow.

**Comment by chirag04** [comment] 2017-04-16 01:26
Closing as per above comment. Also if you want others to read your code the please do indent it.

**Closed by chirag04** 2017-04-16 01:26 UTC
