### ISSUE TITLE
Verbose mode for react-native init fails for react-native-cli ver: 0.1.10

### ISSUE THREAD

**Issue by RanjithNair** [facebook/react-native#5414] opened 2016-01-19 18:42 UTC
While using the latest version of react-native-cli (0.1.10), react-native init fails when invoked with verbose mode.
```
This will walk you through creating a new React Native project in C:\tmp\AwesomeProject
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
    at Function.Module.runMain (module.js:477:11)
    at startup (node.js:117:18)
    at node.js:951:3
```

But with 0.1.9 version of react-native-cli, the verbose mode works fine.

**Comment by grabbou** [comment] 2016-04-20 19:42
Hey @RanjithNair, current version of CLI is 0.2.0 - could you check if the issue still happens? I couldn't reproduce, but it might be due to some system conditions I don't have prepared.

**Comment by zipzit** [comment] 2016-05-09 06:19
I can answer that one.  Absolutely yes, this thing is still a FAIL.  I'm using  `react-native-cli --version` = `react-native-cli: 0.2.0`.  When I type `$ react-native init IconExplorer` and I'm still seeing the `Error: spawn npm ENOENT`, sigh.  (Windows 10)   It seems to work okay withOUT the `--verbose` flag, But that gets the user back to a place where there are two and three minute delays during the init with zero / zip / nada feedback that anything is going on.  Why o why did someone thing hiding functional feedback was a useful thing?   In fact I can't imagine a piece of software on the planet where a delay of more then 30 seconds without user feedback of some sort is acceptable. 

full error:

`$ react-native init IconExplorer --verbose
This will walk you through creating a new React Native project in C:\IconExplorer

Installing react-native package from npm...
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
`

I see somebody pulled an issue https://github.com/facebook/react-native/pull/6708 on the verbose issue.

**Comment by lacker** [comment] 2016-10-21 07:14
Looks like this is fixed now.

**Closed by lacker** 2016-10-21 07:14 UTC
Labels: Tooling
