### ISSUE TITLE
How to use EventEmitterWithHolding.js?

### ISSUE THREAD

**Issue by pantaopt** [facebook/react-native#12428] opened 2017-02-17 06:04 UTC
question as title.

**Comment by ericvicenti** [comment] 2017-03-06 07:42
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by ericvicenti** 2017-03-06 07:42 UTC
