### ISSUE TITLE
react-native init doesn't respect nvm's node current version

### ISSUE THREAD

**Issue by BrunoBernardino** [facebook/react-native#8887] opened 2016-07-19 09:10 UTC
I just had [this issue](https://github.com/facebook/react-native/issues/8837) yesterday and I believe this deserves either a mention in the guide, something like:

> If you're using `nvm`, we will use the default version to install dependencies, not the currently selected one

Or ideally a fix, to try and use the currently selected node version by nvm.

React Native 0.29.2
OS X 10.11.5
nvm 0.31.0

```
% nvm ls
->     v0.10.46
        v0.12.7
         v6.2.2
default -> 0.10 (-> v0.10.46)
stable -> 6 (-> v6.2.2)
node -> stable (-> v6.2.2) (default)
iojs -> N/A (default)
```

I had to make `6` default while running `react-native init`.

If someone acknowledges this, I can _try_ to fix it.

**Comment by BrunoBernardino** [comment] 2016-08-11 21:01
I just want to add I have no system `node` version (only `nvm` versions) and I need to set `6` as the default even for running `react-native run-ios` which is really strange.

**Comment by ericvicenti** [comment] 2016-11-14 20:13
Closing because there isn't much activity on this, so I don't think the issue is very widespread. If it is still broken, please file a ticket in product pains to support nvm better, and we can prioritize based on activity there.

**Closed by ericvicenti** 2016-11-14 20:13 UTC
