### ISSUE TITLE
Error: Cannot add a child that doesn't have a YogaNode to a parent without a measure function!

### ISSUE THREAD

**Issue by Lastin** [facebook/react-native#18773] opened 2018-04-09 16:30 UTC
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

`Cannot add a child that doesn't have a YogaNode to a parent without a measure function` exception when `Component` co-existing in same parent as TextInput which triggers component removal. 

## Environment

Environment:
  OS: Linux 4.13
  Node: 9.4.0
  Yarn: 1.3.2
  npm: 5.7.1
  Watchman: 4.9.0
  Xcode: N/A
  Android Studio: 3.1 AI-173.4670197

Packages: (wanted => installed)
  react: ^16.3.1 => 16.3.1
  react-native: ^0.55.2 => 0.55.2

## Steps to Reproduce

Simplified example:
Change text in TextInput field
https://snack.expo.io/SyAcWQFoz

## Expected Behavior

`<Text>` component stops existing
## Actual Behavior

Exception thrown:
```
Cannot add a child that doesn't have a YogaNode to a parent without a measure function! (Trying to add a 'RCTRawText [text: ]' to a 'RCTView')
addChildAt
    ReactShadowNodeImpl.java:279
addChildAt
    ReactShadowNodeImpl.java:56
manageChildren
    UIImplementation.java:446
manageChildren
    UIManagerModule.java:416
invoke
    Method.java
invoke
    JavaMethodWrapper.java:372
invoke
    JavaModuleWrapper.java:160
run
    NativeRunnable.java
handleCallback
    Handler.java:751
dispatchMessage
    Handler.java:95
dispatchMessage
    MessageQueueThreadHandler.java:29
loop
    Looper.java:154
run
    MessageQueueThreadImpl.java:192
run
    Thread.java:761

```

**Comment by SaraCallaioli** [comment] 2018-04-10 12:50
Same problem!

**Comment by Lastin** [comment] 2018-04-10 13:48
For now I just display empty text instead of removing `<Text>` component. Not sure if that's a suitable solution for you @SaraCallaioli

**Comment by angly-cat** [comment] 2018-04-10 20:32
The issue is that you try to render an empty string outside a `Text` component:
```
{state.error &&
    <Text>
        Some text
    </Text>
}
```
If `state.error` is an empty string (falsey value), this transforms into `{''}`. And you can't render an empty string (`''`) or zero (`0`) outside of `Text` component. But all other falsey values will do. Try to turn this into another falsey value.

For example (`null`):
```
{state.error
    ? (
        <Text>
            Some text
        </Text>
    )
    : null
}
```
or (`false`)
```
{!!state.error &&
    <Text>
        Some text
    </Text>
}
```

**Comment by mezod** [comment] 2018-04-21 18:54
Same here, with the added problem that the error/stacktrace doesn't show which files of my project contain the issue making it very hard to fix :/

**Comment by kevinscience** [comment] 2018-05-04 09:10
I have this issue as well, only on Android. And I couldn't find any problem with my TEXT!!

**Comment by Paul-Hume** [comment] 2018-05-04 10:33
We're having the same problem here too :( and no way of easily seeing which file is causing it

**Comment by export-mike** [comment] 2018-05-08 06:55
Hmm I'm getting this error in android when I render my Icons the icon font is loaded correctly as I'm using it elsewhere. I am however rendering these icons inside a FlatList?

**Comment by zsaCHG** [comment] 2018-05-11 02:39
I have same problem too. Over one day =.=

**Comment by matmartic** [comment] 2018-05-11 17:34
I've had the same problem for a while until I realized that in order to make a line break between 2 paragraphs, I had this `{`\n`}` between 2 Text components. Removing it fixed this issue for me

**Comment by drdpedroso** [comment] 2018-05-29 17:56
Same here. Fixed by removing texts outside the `<Text>` tag

**Comment by beisert1** [comment] 2018-05-31 15:07
Issue was fixed for me by removing a space I had between my <View> tags.

**Comment by angly-cat** [comment] 2018-05-31 15:11
By the way, I've just noticed, that this error message actually shows a text that caused it (notice `Test text`).
![image](https://user-images.githubusercontent.com/5000549/40790534-07ae323e-6517-11e8-8e06-2992ee41a27d.png)

**Comment by Fi2zz** [comment] 2018-06-01 01:55
on android, do not use { your_condtion && <YourComponent/>}

**Comment by kaueDM** [comment] 2018-06-06 14:19
Can we have a better way to debug this? Is kinda hard to discover where is my empty text.
<img width="292" alt="captura de tela 2018-06-06 as 11 19 00" src="https://user-images.githubusercontent.com/20171863/41043957-7a895906-697b-11e8-87fc-6f55f18f4acd.png">

**Comment by weiyih** [comment] 2018-06-06 18:58
Fixed this issue on my end by removing an unnecessary semi-colon at the end of a function call in my render function.

`  render() {
    return (
      <Container>
        <Content padder>
          <Title>TEXT</Title>
          {/*  Render different views based on state */}
          {this.functionOne()};  // <---MAKE SURE TO REMOVE SEMI-COLON
          {this.functionTwo()};  // <---MAKE SURE TO REMOVE SEMI-COLON
        </Content>
      </Container>
    );
  }
}`

**Comment by weiyih** [comment] 2018-06-06 19:04
I had this issue when I had an unnecessary semi-colon on my function call inside my render function. 
```
  render() {
    return (
      <Container>
        <Content padder>
          <Title>Text</Title>
          {this.Function()} // <--MAKE SURE NO SEMI-COLON
        </Content>
      </Container>
    );
  }
}
```

**Comment by MJGTwo** [comment] 2018-06-07 16:58
Yeah, echoing what @kaueDM said, has anyone figured out a nifty way to trace back to this error? I've been a bad dev and used this pattern a few times :/

**Comment by otaviogaiao** [comment] 2018-06-08 00:51
@angly-cat solution solved my problem, just put a !! at my short circuit evaluation.

**Comment by angly-cat** [comment] 2018-06-12 19:38
> React then tries render this non-boolean value, which is no longer acceptable in Android with current versions of react-native.

Rendering `null` or `undefined` is fine. Rendering `0` or `''` isn't.

**Comment by nateReiners** [comment] 2018-06-15 23:54
@jamiesonbates  yes, In my case this was caused by` { this.state.index && <View><Text>Foo</Text></View>}` but if this.state.index was equal to zero, it would throw this error. zero is falsey so to fix it I did `{(!!this.state.index || this.state.index === 0) && ...` which worked. Also agree with your advice to avoid using && for non booleans.

**Comment by AmmarTariq10** [comment] 2018-06-20 15:32
Can someone explain what is actually causing the problem?
I have faced this 3 to 4 times and resolved, but I don't know what caused it and what really solved the problem, I'm confused :(

**Comment by zzorba** [comment] 2018-06-20 15:37
It appears to be an issue with 'falsey' strings/numbers/undefined breaking rendering.  So specifically a `''` or `0` will be false and work fine on iOS, but on Android it will appear as 'text outside of a <Text>' tag and blow up.

You can workaround this by using `!!variable && <View>...</View>` instead of `variable && <View>...</View>` when doing short circuit rendering, since both boolean `false` and `null` still seem to work okay.

**Comment by jeromew21** [comment] 2018-06-28 03:44
Ran into the same issue where my app worked in debug mode but upon production it crashed with the same set of errors. 

I had extended the `Text` component in order to globally apply the same style to each Text instance. Changing the class to inherit from `React.Component` instead fixed the problem.

**Comment by connorbode** [comment] 2018-07-04 15:57
I was able to solve this by changing `{condition && <ReactComponent />}` syntax to `{condition ? <ReactComponent /> : null}`

**Comment by hankzhuo** [comment] 2018-07-12 07:23
I solve this problem for me
```<View style={{ flexGrow: 1, flexDirection: "row", alignItems: "center", justifyContent: "flex-end" }}>
          <Text>{formatPhone(userManager.userPhone)}</Text>,
        </View>``` 

just because the ','  delete it, it works

**Comment by herarya** [comment] 2018-07-18 08:38
same +1 after upgrade :(

**Comment by Triskae** [comment] 2018-07-20 05:39
I also had the same problem guys, and I find that its comes from a "comment" that I put in JSX ...
 ```
<View>
    <Text> ... </Text>      {/* The comment */}
</View>
```

Maybe it's because React expects ta have some condition or something inside the braces ... I don't if I'm the only one to put comments in JSX

**Comment by angly-cat** [comment] 2018-07-20 05:42
@Triskae in you case it's not because of a "comment", it' because of whitespaces between `</Text>` and the "comment".

**Comment by Triskae** [comment] 2018-07-20 05:45
@angly-cat Hmmm ok, make sense, thanks !

**Comment by animehk55** [comment] 2018-07-24 11:59
const AlbumDetail = (props) => {
    return (
            <Card>
            {(!!props.album.title)}		
            </Card>
    );
};
// By applying{(!! )}  it resolves my issue but still the data is not displaying the previous error "YogaNode " was resoved.

**Comment by Selence** [comment] 2018-07-24 18:08
do you have some comments in your code?

My solution was to remove the comments

<View>
//Nice Code  
<Text>Hello</Texte>
</View>

**Comment by jfcodiaz** [comment] 2018-08-09 06:50
Mi problem was a text outside <Text>

`<Text> Text </Text> another text
   {this.sw()}
`
solution: 

`<Text> Text </Text>
   {this.sw()}
`

**Comment by conor909** [comment] 2018-08-10 11:30
I use this kind of syntax all over my app

**Comment by angly-cat** [comment] 2018-08-10 11:33
@conor909 Just make sure that neither `''`, nor `0` are passed as `isThisTrue` ever. Or add double negations -> `!!isThisTrue`.

**Comment by conor909** [comment] 2018-08-10 12:29
Thanks @angly-cat, It's just that I tons of components in my app that I have to run through every render of.  I don't know even know where to begin, and as I come close to finishing updated all of them I wont even know which components have been checked because the error message is so vague.  This is going to be fun.

**Comment by angly-cat** [comment] 2018-08-10 12:49
> I don't know even know where to begin

@conor909 I don't know all the details, but assuming you have the exact syntax as you wrote before, it looks like it can be solved pretty easy with replaces by regular expressions in all files.

**Comment by conor909** [comment] 2018-08-10 12:54
I understand the solution, the problem is the amount of files that need to be updated and the very vague error won't help the process.

**Comment by xims** [comment] 2018-08-21 07:41
Try not to leave spaces between elements, like this:
`<Text>abc</Text>  <TouchableOpacity .... `

**Comment by karthicksenthil** [comment] 2018-08-23 07:51
If you want to return a view with the only style applied, make sure to remove empty space between the opening and closing tag.

eg: **<View style={styles.ring}> </View>** caused error

rectified by **<View style={styles.ring}></View>**

**Comment by nelsonchen5** [comment] 2018-08-24 23:49
Thanks @xims and @karthicksenthil. This fixed my issue. Any explanation on why?

**Comment by skptricks** [comment] 2018-08-29 17:09
I have found solution for this issue. refer this link : https://www.skptricks.com/2018/08/react-native-cannot-add-child-that.html

**Comment by oneuptim** [comment] 2018-09-27 13:01
Thank you @angly-cat your solution helped me fix my issue! Could the errors be any more vague? smh!

**Comment by Fitzpasd** [comment] 2018-10-04 19:42
Does anyone use tooling to help prevent these?  Lint/regex/other static analysis?

**Comment by skptricks** [comment] 2018-10-05 03:41
> Does anyone use tooling to help prevent these? Lint/regex/other static analysis?

I have found solution for this issue. refer this link : https://www.skptricks.com/2018/08/react-native-cannot-add-child-that.html

**Comment by nickmccomb** [comment] 2018-10-09 07:38
This error also occurs if you have comments in your render() return() function.  Remove all comments in your return function when rendering JSX

**Comment by mithunadhikari40** [comment] 2018-10-16 20:12
I am not sure this might be helpful or not. I also was having this same issue and couldn't find out the reason causing the problem. As it turns out, I forgot to add static navigationOptions in my class component. Like :
  `static navigationOptions = {
        title: 'a',
        TabBarIcon: {
            icon: ({tintColor}) => {
                return <Icon name='favorite' size={30} color={tintColor}/>;
            }
        }
    };`
After I added this function at the top before render function, the issue seems to be gone. Though I am not sure why this function was causing that error, that was solved for. Any  explanation on this would be really appreciated.

**Comment by edmondlaja** [comment] 2018-10-18 07:10
Worked for me after I removed a  >  that was extra in my code

**Comment by vjsingh** [comment] 2018-11-14 14:20
This is fairly frustrating and time-consuming behavior, especially when porting a large iOS project to Android. 

As has been noted, the generic error occurs when there is an extra space in your single-line JSX (<Tag> {children}</Tag>). In fact, it sometimes causes your app to crash entirely, which makes debugging even harder (<Tag> <View/></Tag>). It also happens when there are extra characters in your JSX (which seems to be fine on iOS), and probably for various other reasons as noted.

It would be great if spaces in single-line JSX could be allowed. More importantly probably would be a line number or at least a file in which the problem occurred .

**Comment by raphael-liu** [comment] 2018-11-15 06:48
\<View\>\<\/View\> tag supports these types of children: boolean,null,undefined,Symbol,component(such as <View/>). and does not support : Number, String, Object(Map,Set...).
For example:

```
//the children types of <View/> tag should be : boolean,null,undefined,Symbol,component(such as<View/>)
var array = [true,null,undefined,<View/>,Symbol('test')];
let testView = []
testView.push(
  <View>
  	/**
         * 0 && <View/> === 0
         * '' && <View/> === ''
         * <View/> tag does not support these types of children: {1},{''},{[1,2]},{Map(not null)},{Set(not null)}...these will cause IndexOutOfBoundsException.
         */
  	{array}
  </View>
)
```

**Comment by Ilphrin** [comment] 2019-01-16 12:32
Hi,

I had the exact same error yesterday (fixed this by reading the thread and changing `{ myVariable && ...}` to `{!!myVariable && (...)}` ) so thank you all for this ;)

Now, as @vjsingh said, this is a very frustrating issue, and even though a rule in tslint would be nice, I think the main issue here is that this error message isn't giving any information but the string used (and in my case the string was empty, so I had absolutely no idea, in fact it happened after I changed SQLite lines and thought for hours that I was doing something wrong with my SQL requests)

Is there any hint of how this message could be improved? Just giving the file and the line would be an awesome win for my work time :') I'd love to take a look at this issue but I don't know what I could do

**Comment by rostislav-simonik** [comment] 2019-02-06 20:09
Implementation should be error-tolerant because it's easy to make a mistake. Logic is implemented here#22776.

**Comment by alloy** [comment] 2019-03-19 14:47
Thanks for that update @rostislav-simonik 👍 In an effort to reduce the number of open issues and this issue having a open PR to fix it, I’ll close this for now. If somebody verifies the PR and it turns out to not actually address this issue, please let us know and we can re-open.

**Closed by alloy** 2019-03-19 14:47 UTC
Labels: Platform: Linux, Type: Bug Report

**Comment by kailesh49** [comment] 2019-03-20 13:08
> on android, do not use { your_condtion && <YourComponent/ >}

This solved my issue. :)

**Comment by sudolibre** [comment] 2019-05-03 19:28
A lot if not all of these issues will be caught with the `react-native/no-raw-text` eslint rule from the plugin here: https://github.com/Intellicode/eslint-plugin-react-native. If you're using TypeScript from what I can tell there is no TSLint alternative. It seems the Typescript is going to be formally supporting eslint only moving forward anyways: https://github.com/Microsoft/TypeScript/issues/29288.

**Comment by Ilphrin** [comment] 2019-05-03 20:06
That's a good news! But how can this be communicated so devs actually knows about that eslint rule that could help them? Documenting it like in an FAQ?

**Comment by heavy-snowy** [comment] 2019-11-12 08:03
use  "xx? xx : ' ';"instead of "xx&&xx"

**Comment by binki** [comment] 2019-11-13 13:40
@heavy-snowy
> use "xx? xx : ' ';"instead of "xx&&xx"

Shouldn’t `xx || ''` be clearer and less repetitive?

**Comment by waqaramjad** [comment] 2019-12-13 14:29
same issue in android

**Comment by TheSavior** [comment] 2020-01-08 21:32
Hi all! Sorry for the long wait but I think [the fix for this just landed](https://github.com/facebook/react-native/commit/66601e755fcad10698e61d20878d52194ad0e90c).

We were able to repro and fix this issue with this sample code:

```
function PlaygroundContent(props: {}) {
  return (
    <View>
      <Text>
        <View style={{width: 10, height: 10}}>
          <Image source={ANY_IMAGE_SOURCE} />
        </View>
      </Text>
    </View>
  );
}
```

**Comment by saroj85** [comment] 2020-02-21 10:30
cannot add a child that doesn't have a yoganode to a parent without a measure function in expo
