### ISSUE TITLE
[Android] RefreshControl still spinning even after refreshing set to false

### ISSUE THREAD

**Issue by damusnet** [facebook/react-native#7313] opened 2016-04-30 22:10 UTC
- react-native v0.25.0-rc
- android
- mac OS X on simulator and device

A ListView is mounted with `refreshing={true}` in the constructor, then `refreshing` is set to `false` in `componentWillReceiveProps`. So far it works. Then, the same ListView is pushed through the navigator. The first ListView is unmounted and everything starts again. Only this time the spinner never stops, even though `refreshing` has been set to `false` and seems correctly propagated to the RefreshControl component. Also, at this point, the fans on my laptop start spinning up. Eventually if done a couple of times fast enough, sometimes it will work. More often it doesn't.

This looks strangely similar to those issues on iOS: #5839, #6893

![react](https://cloud.githubusercontent.com/assets/433409/14938800/8d2838f4-0f30-11e6-9691-69559bc68a0c.gif)

The complete code for this app can be seen [here](https://github.com/digisquare/mobile/blob/master/js/scenes/events/Events.js)

**Comment by damusnet** [comment] 2016-04-30 22:12
@facebook-github-bot label Android

**Comment by janicduplessis** [comment] 2016-05-01 06:37
Hey @damusnet thanks for finding this!

I tried your app and reproduced the issue, looks like some race condition in the native android code when setting the refreshing value. I'll work on a fix :)

**Comment by janicduplessis** [comment] 2016-05-12 07:28
Fixed via 8fbce3099dca2340eaa614e9a90bb89a4a386bb9

**Closed by janicduplessis** 2016-05-12 07:28 UTC
Labels: Android
