### ISSUE TITLE
resizeMode's problem

### ISSUE THREAD

**Issue by GaverChou** [facebook/react-native#5394] opened 2016-01-19 01:57 UTC
why resizeMode stretch is not fitXY?
![device-2016-01-19-095428](https://cloud.githubusercontent.com/assets/7710408/12407543/fd42ed58-be92-11e5-92c0-c3925500a0af.png)

**Comment by satya164** [comment] 2016-01-19 03:58
Duplicate of #4031

**Closed by satya164** 2016-01-19 03:58 UTC
