### ISSUE TITLE
ERROR react-native link

### ISSUE THREAD

**Issue by hustlerism** [facebook/react-native#15592] opened 2017-08-21 16:06 UTC
## Description
Hi, im having problem with the installation. I can succesfully install native-base but encountered error after running 

> react-native link

## react-native, react and native-base version
"dependencies": {
    "firebase": "^4.1.3",
    "native-base": "^2.2.0",
    "react": "16.0.0-alpha.3",
    "react-native": "0.44.2",
    "react-native-action-button": "^2.7.2",
    "react-native-drawer": "^2.3.0",
    "react-native-fbsdk": "^0.6.0",
    "react-native-google-signin": "^0.10.0",
    "react-native-icon-badge": "^1.1.1",
    "react-native-linear-gradient": "^2.0.0",
    "react-native-maps": "^0.15.2",
    "react-native-modal": "^2.5.0",
    "react-native-parallax-scroll-view": "^0.19.0",
    "react-native-router-flux": "3.38.0",
    "react-native-splash-screen": "^2.1.0",
    "react-native-swiper": "^1.5.4",
    "react-native-tab-view": "^0.0.66",
    "react-native-vector-icons": "^4.1.1",
    "react-redux": "5.0.4",
    "redux": "3.6.0",
    "redux-thunk": "^2.2.0"
  },
## Expected behaviour
"react-native link" successfully
## Actual behaviour

> rnpm-install info Linking react-native-fbsdk android dependency
rnpm-install ERR! Something went wrong while linking. Error: ENOENT: no such file or directory, open 'D:\Desktop\Makan-app\android\app\src\main\java\android\support\graphics\drawable\animated\MainApplication.java'
Please file an issue here: https://github.com/facebook/react-native/issues

>ENOENT: no such file or directory, open 'D:\Desktop\Makan-app\android\app\src\main\java\android\support\graphics\drawable\animated\MainApplication.java'

**Comment by hramos** [comment] 2017-08-23 19:21
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-08-23 19:21 UTC
