### ISSUE TITLE
Network request failed

### ISSUE THREAD

**Issue by chinaxiaoyy** [facebook/react-native#15052] opened 2017-07-17 09:04 UTC
![wechatimg150](https://user-images.githubusercontent.com/20460743/28261399-bb25448e-6b11-11e7-9ccf-2e7fc735adff.jpeg)
this is my info.plist,but i still get Network request failed,
react-native:0.42.0
ios simulator

who can help me? thankyou so much

**Comment by hramos** [comment] 2017-07-17 14:43
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-07-17 14:43 UTC
