### ISSUE TITLE
Hot reloading error. (Unknown module "react-native")

### ISSUE THREAD

**Issue by amberstar** [facebook/react-native#6731] opened 2016-03-30 15:23 UTC
Hot reloading is not working. #6722 was closed as a dup of #6640. #6640 was Unknown module "React", the error I am getting  is "Unknown module "react-native"." I tried to debug, but this is day 1 for me with react, node etc.

If it truly is fixed, please explain how to used the fixed version. I am working with  a first time  fresh install of everything this morning to try react.

I saw this comment: 

> Should work now that we have released babel-preset-react-native@1.5.5. You'll have to upgrade from 1.5.4 to 1.5.5

As far as I can tell I am up to date using 1.5.5.

Thanks.

![](https://cloud.githubusercontent.com/assets/13548241/14138321/3d79643a-f69f-11e5-9c12-adc9464cc6ad.png)

**Comment by adrienbrault** [comment] 2016-03-30 15:37
Having the same issue. Is there a way to disable hot reloading ?

**Comment by magrinj** [comment] 2016-03-30 15:41
@adrienbrault If you are on iOS device do `Command + D` and click on `Disable Hot Reloading`

**Comment by RealOrangeOne** [comment] 2016-03-30 15:44
@adrienbrault Hot reloading should be an opt-in option. I too am having this problem with Hot Reloading, although on Android. However someone else I know on another project is having no problems at all, I fear it's something in the project itself that is causing the problems

**Comment by hvsy** [comment] 2016-03-30 15:46
+1

**Comment by sylvainbaronnet** [comment] 2016-03-30 18:05
Same issue

**Comment by sylvainbaronnet** [comment] 2016-03-30 18:11
@magrinj I don't have access to `⌘ + D` menu since the app crash, is there another way to disable hot reload ?

**Comment by magrinj** [comment] 2016-03-30 18:20
@sylvainbaronnet You can dismiss the error view with the button at the bottom left, after that try again with `⌘ + D`, did you do that on an iOS simulator ?

**Comment by sylvainbaronnet** [comment] 2016-03-30 18:24
Thanks !! It works again

**Comment by satya164** [comment] 2016-03-30 18:44
Fixed in 51b5423fd5c3263b34fe6dc7ca83cf188e5e8d5e

**Comment by satya164** [comment] 2016-03-30 18:44
cc @martinbigio

**Comment by jerolimov** [comment] 2016-03-31 00:41
Same error here. After many many try and errors I found that you should always use `npm start -- --reset-cache` when trying to "found" this issue.

Could reproduce this with a clean `react-native init` project without any additional dependency.

I found a local project that still works and created two npm-shrinkwrap files which shows that the problem doesn't happen with react 0.14.7 and happen with 0.14.8.

You find both npm-shrinkwrap files and the `npm install` output after adding the "old" version and re-run it here: https://gist.github.com/jerolimov/85051d319b69ea6fe8dd24fa0f79f5f4

**Comment by martinbigio** [comment] 2016-03-31 00:47
Hmm, mind trying with `babel-preset-react-native@1.5.4`. Looks like for some people we have problems resolved React and for other react-native.

@cpojer, @skevy has anything changed on node-haste that could explain this? This is where react-transform is configures to import React/react-native:  https://github.com/facebook/react-native/blob/3a1634ec7b0dfa2b5d8890118565006d845e2039/babel-preset/configs/hmr.js#L28.

**Comment by cpojer** [comment] 2016-03-31 00:51
I haven't touched anything in node-haste for a while, might wanna ask @davidaurelio :)

**Comment by martinbigio** [comment] 2016-03-31 01:37
Started debugging a bit the repro case of https://github.com/facebook/react-native/issues/6640 and confirmed react is on the Haste map of the resolver when the packager starts. Maybe the issue is that the dependency is added on transform time by the HMR plugin? That doesn't explain though why this stopped working.

**Comment by martinbigio** [comment] 2016-03-31 02:41
Taking a step back I realized this problem is different to the one on https://github.com/facebook/react-native/issues/6640. This one happens on runtime whereas the other one on resolution time. The problem we're having now is that the require (`react-native`) is not getting transformed to the absolute path (`react-native/Libraries/react-native/react-native.js`). Modifying https://github.com/facebook/react-native/blob/master/babel-preset/configs/hmr.js#L28 with such change fixes the problem.

I need to test this also works internally. If everything is fine I'll update the preset tomorrow with this fix. Sorry for the issue, please remember you can always disable hot reloading. Happy coding!

cc @satya164 :)

**Comment by tianwalker2012** [comment] 2016-03-31 10:04
@martinbigio  I followed you steps, it doesn't work :(

**Comment by martinbigio** [comment] 2016-03-31 12:50
@tianwalker2012 that's really weird, it does work for me. The file you need to modify is located on `node_modules/react-native/node_modules/babel-preset-react-native/configs`. Was that one the one you changed? What error are you getting now?

**Comment by pgengoux** [comment] 2016-03-31 12:56
@martinbigio I'm having the same issue. I tried both versions: 

- imports: ['react-native']
&
- imports: ['react']

The red box displays: Requiring unknown module "react-native". If you are sure the module is there, try restarting the packager or running "npm install".

**Comment by amberstar** [comment] 2016-03-31 13:11
@martinbigio Yes that fixed it for me. Thanks.

**Comment by martinbigio** [comment] 2016-03-31 13:20
Would be awesome if a couple more of people confirm this is working for them so that I can commit the code to the repo :)

**Comment by gaearon** [comment] 2016-03-31 13:22
>react-native/Libraries/react-native/react-native.js

:joy:

**Comment by pgengoux** [comment] 2016-03-31 13:30
The updated present is doing something different. I'm receiving now a tiny redbox in the upper left corner:
![tinyredbox](https://cloud.githubusercontent.com/assets/6129147/14177191/75c0e29e-f755-11e5-880a-61ff7a56ad39.png)
;)

**Comment by pgengoux** [comment] 2016-03-31 13:43
The problem lies definitely in my app code.
Enabling hot reloading rendering only a simple view as follows works just fine.
     <View>
        <Text>
          Hello World
        </Text>
      </View>
I will try to find out how exactly I can reproduce this.

**Comment by pohy** [comment] 2016-03-31 13:57
The issue persists for me, am using babel-preset-react-native@1.5.6.
![player_2016-03-31_15-55-13](https://cloud.githubusercontent.com/assets/2036806/14178045/483d9ed0-f759-11e5-94c8-34641d4f7f39.png)

**Comment by maikokuppe** [comment] 2016-03-31 14:29
@martinbigio: Works for me after updating babel-preset-react-native with
```
npm install babel-preset-react-native@1.5.6
```
Thanks!

**Comment by martinbigio** [comment] 2016-03-31 14:30
@pohy as per your screenshot you're not using 1.5.6 because `react-native` was changed for the full path.

**Comment by martinbigio** [comment] 2016-03-31 14:32
@gaearon this is only a temporary hack to fix the issue and unblock people. The underlying problem is not only affecting HMR but also assets, check https://github.com/facebook/react-native/issues/6638. We'll ask @davidaurelio to take a look next week when he comes back.

**Comment by pohy** [comment] 2016-03-31 14:40
Interesting, `npm ls babel-preset-react-native` shows, that I have 1.5.6, and even after fully rebuilding the app, it still does fail with `Requiring unknown module "react-native"...`

**Comment by martinbigio** [comment] 2016-03-31 14:52
make sure to reset the cache `npm start -- --reset-cache`

**Comment by maikokuppe** [comment] 2016-03-31 14:54
@pohy: You could try to stop the gradle daemon (`android/gradlew --stop` works for me) and rebuild with `react-native run-android`.
Just an idea

**Comment by pohy** [comment] 2016-03-31 15:37
@martinbigio Yes, resetting cache helped, thanks for the help and sorry for the hassle!

**Closed** 2016-04-01 15:08 UTC
Labels: Contains Potential Question Keywords
