### ISSUE TITLE
Error after upgrading RN to v0.46.4

### ISSUE THREAD

**Issue by nithindot3513** [facebook/react-native#15229] opened 2017-07-27 09:21 UTC
`error: bundling failed: "Unable to resolve module 'ReactNative' from 'C:\\AnchorDev\\Anchor\\node_modules\\react-native\\Libraries\\react-native\\react-native-implementation.js': Module does not exist in the module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: 'watchman watch-del-all'.\n  2. Delete the 'node_modules' folder: 'rm -rf node_modules && npm install'.\n  3. Reset packager cache: 'rm -fr $TMPDIR/react-*' or 'npm start -- --reset-cache'."`

This is the error that I get after upgrading React Native from v0.45.1 to 0.46.4

**Comment by fredbt** [comment] 2017-07-27 10:51
+1 I also getting lots of bundling errors today since upgrade to 0.46.4, including libraries that I don't really use such as "react-native-action-sheet", "react-timer-mixin", etc.

**Comment by fredbt** [comment] 2017-07-27 10:53
@nithindot3513 I did the clean ups (removing node_modules, etc), and also removed package-lock.json, then a new npm install followed by npm start -- --reset-cache fixed the issue.

**Comment by hramos** [comment] 2017-07-27 16:44
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-07-27 16:44 UTC
