### ISSUE TITLE
Received status code 502 from server: Bad Gateway

### ISSUE THREAD

**Issue by karimkhamwani** [facebook/react-native#24082] opened 2019-03-21 08:16 UTC
* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not resolve com.facebook.react:react-native:+.
  Required by:
      project :app
      project :app > project :react-native-snackbar
      project :app > project :react-native-settings
      project :app > project :react-native-location-switch
      project :app > project :react-native-i18n
   > Failed to list versions for com.facebook.react:react-native.
      > Unable to load Maven meta-data from https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml.
         > Could not HEAD 'https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

This is due to bintray is down
https://status.bintray.com/
let's have a cup of coffee

**Comment by karimkhamwani** [comment] 2019-03-21 08:23
Project was working fine few hours ago

**Comment by Stanley1234** [comment] 2019-03-21 08:28
Same here

**Comment by Toshihiro2010** [comment] 2019-03-21 08:30
Same me.

**Comment by jimmywshee** [comment] 2019-03-21 08:31
same here

**Comment by sangeethkumarv** [comment] 2019-03-21 08:32
Suddenly stopped working :(

**Comment by 1agiloke** [comment] 2019-03-21 08:32
Same here. It seems https://jcenter.bintray.com/ cannot be accessed

**Comment by hungvt00041** [comment] 2019-03-21 08:33
me too

**Comment by kyo504** [comment] 2019-03-21 08:33
Is there any workaround for this?

**Comment by igarramaddhan** [comment] 2019-03-21 08:34
Same here

**Comment by sangeethkumarv** [comment] 2019-03-21 08:34
> Is there any workaround for this?

React Native iOS is working fine.

**Comment by huynguyen1509** [comment] 2019-03-21 08:35
Same here

**Comment by grahaisw** [comment] 2019-03-21 08:35
Same here

**Comment by ranuwp** [comment] 2019-03-21 08:36
So do I

**Comment by manotonyraj** [comment] 2019-03-21 08:36
same here :/

**Comment by parinha** [comment] 2019-03-21 08:36
Same here

**Comment by haroldhalcyon28** [comment] 2019-03-21 08:37
same here ... Is there an alternative site for this?

**Comment by hoannk307** [comment] 2019-03-21 08:37
me too

**Comment by NicholasCao** [comment] 2019-03-21 08:37
Same here. Some wrong on https://jcenter.bintray.com?

**Comment by karimkhamwani** [comment] 2019-03-21 08:39
https://dl.bintray.com/android/android-tools/ is also down

**Comment by supernhok13** [comment] 2019-03-21 08:39
Same here. Can't build or do anything :((

**Comment by Waqas-Jani** [comment] 2019-03-21 08:40
same here

**Comment by yangjinlongpk** [comment] 2019-03-21 08:40
Same, https://status.bintray.com

**Comment by Waqas-Jani** [comment] 2019-03-21 08:41
any solution ??

**Comment by GuppuBoss** [comment] 2019-03-21 08:41
same here

**Comment by dr-johnsmith** [comment] 2019-03-21 08:42
same, ios is work
maybe some wrong from server, about 30' to 1hour ago

**Comment by wendy-peiwen** [comment] 2019-03-21 08:42
same here =(

**Comment by thekopvnnn** [comment] 2019-03-21 08:48
same here

**Comment by dianbagus96** [comment] 2019-03-21 08:48
same here

**Comment by liuxuwei** [comment] 2019-03-21 08:48
+1  suddenly  doesn't work

**Comment by tuananhluong** [comment] 2019-03-21 08:49
same here: 502 Bad Gateway
https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml

Can't build anything :(

**Comment by wachidyulio** [comment] 2019-03-21 08:50
Same here.
Work fine on ios, but on Android get 'Received status code 502 from server: Bad Gateway' error.

**Comment by dianbagus96** [comment] 2019-03-21 08:51
work fine in ios, but when i build in android got this error

**Comment by samad324** [comment] 2019-03-21 08:51
Same here....

**Comment by limjihoon** [comment] 2019-03-21 08:51
same me

**Comment by tvildo** [comment] 2019-03-21 08:52
This is because bintray is down , we have to wait until they fix that nasty issue https://status.bintray.com

**Comment by muhalovic** [comment] 2019-03-21 08:53
Same here. Can't do anything.

**Comment by supernhok13** [comment] 2019-03-21 08:53
Feel like we just get some times to have a cup of coffee, most of react libs depend on bintray :(( We just have to wait for it comes back.

**Comment by Waqas-Jani** [comment] 2019-03-21 08:53
run project in android studio. and work offine. then working.. :)

**Comment by kea0811** [comment] 2019-03-21 08:59
lol this is bad. Everyone just got the same problem.

**Comment by FioneraGH** [comment] 2019-03-21 09:00
bintray download is down.  https://status.bintray.com/
<img width="863" alt="image" src="https://user-images.githubusercontent.com/10138080/54741911-d0e3ad80-4bfa-11e9-9d6e-5f20677d6b6c.png">

**Comment by Rindt** [comment] 2019-03-21 09:03
Same here

**Comment by earlyCloud** [comment] 2019-03-21 09:03
Same, but have no coffee

**Comment by chenxiyuluo** [comment] 2019-03-21 09:04
just remove jecenter(),and replace with aliyunmaven

**Comment by jinhak** [comment] 2019-03-21 09:05
Official answer:
Hi Kim,

Thank you for contacting JFrog Support.

We are working internally with our internal teams on this issue. We will keep you updated about the progress.
Meanwhile, can you please try to download the library again and let us know the results.
Looking forward to your response.


Best regards,
Balaji Satish
JFrog Support

**Comment by NomanGul** [comment] 2019-03-21 09:06
Same here :/ Plz Fix it Or I'll be migrating from react-native to flutter :smile:

**Comment by huannd98** [comment] 2019-03-21 09:07
me too , disable internet and re-build project

**Comment by faizsameerahmed96** [comment] 2019-03-21 09:09
Same here, however since I am on a strict timeline I am using the following temp fix while jcenter is back online:

 turning off the network so that the app installs once  and then turn it back on and use Live Reload.

**Comment by Binhluan1234** [comment] 2019-03-21 09:11
Same issue. What happened ? :(

**Comment by phanvantien** [comment] 2019-03-21 09:12
Is there any way to solve this problem?

**Comment by samad324** [comment] 2019-03-21 09:13
> Is there any way to solve this problem?

nope! we have to wait until the server will be fixed!

**Comment by EthanJMY** [comment] 2019-03-21 09:14
me too/(ㄒoㄒ)/~~

**Comment by samad324** [comment] 2019-03-21 09:15
> Official answer:
> Hi Kim,
> 
> Thank you for contacting JFrog Support.
> 
> We are working internally with our internal teams on this issue. We will keep you updated about the progress.
> Meanwhile, can you please try to download the library again and let us know the results.
> Looking forward to your response.
> 
> Best regards,
> Balaji Satish
> JFrog Support

redownloading libraries won't work!

**Comment by ufosaga** [comment] 2019-03-21 09:17
$ curl http://jcenter.bintray.com/
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by JohnFelixLim** [comment] 2019-03-21 09:18
Same here

**Comment by phanvantien** [comment] 2019-03-21 09:18
I am tired, you can help me ?
![image](https://user-images.githubusercontent.com/18244801/54742725-c45c5680-4bf4-11e9-9cb0-a8ec8c8cd29f.png)

**Comment by msaifa** [comment] 2019-03-21 09:18
same here

**Comment by ali226281** [comment] 2019-03-21 09:19
me too

**Comment by wahdatkashmiri33** [comment] 2019-03-21 09:19
any Fix?

**Comment by chenxiyuluo** [comment] 2019-03-21 09:20
replace jcenter() with 
maven { url 'http://maven.aliyun.com/nexus/content/repositories/jcenter' }
maven { url 'http://maven.aliyun.com/nexus/content/groups/public/' }, and it fixed

**Comment by wooer79** [comment] 2019-03-21 09:20
same here

**Comment by SajithDananjaya** [comment] 2019-03-21 09:22
#metoo

**Comment by samad324** [comment] 2019-03-21 09:22
> replace jcenter() with
> maven { url 'http://maven.aliyun.com/nexus/content/repositories/jcenter' }
> maven { url 'http://maven.aliyun.com/nexus/content/groups/public/' }, and it fixed

404 Error!

**Comment by jdgalani** [comment] 2019-03-21 09:23
+1 same here

**Comment by liuxuwei** [comment] 2019-03-21 09:24
> replace jcenter() with
> maven { url 'http://maven.aliyun.com/nexus/content/repositories/jcenter' }
> maven { url 'http://maven.aliyun.com/nexus/content/groups/public/' }, and it fixed

It  works!!!   3ks!!

**Comment by pramodsharma403** [comment] 2019-03-21 09:24
same here

**Comment by amitsin6h** [comment] 2019-03-21 09:25
same here :cry:

**Comment by ttdat2510** [comment] 2019-03-21 09:25
+1 same here

**Comment by Binhluan1234** [comment] 2019-03-21 09:25
> replace jcenter() with
> maven { url 'http://maven.aliyun.com/nexus/content/repositories/jcenter' }
> maven { url 'http://maven.aliyun.com/nexus/content/groups/public/' }, and it fixed

Thanks. But i dont know why what was happened and that is work in future ?

**Comment by helpcodemonkey** [comment] 2019-03-21 09:25
+1 time for a beer

**Comment by danieldggomes** [comment] 2019-03-21 09:26
same here

**Comment by fukuball** [comment] 2019-03-21 09:26
+1 same here

**Comment by fxricky** [comment] 2019-03-21 09:26
same here

**Comment by manotonyraj** [comment] 2019-03-21 09:28
Turn off the internet and start building... it works

**Comment by phanvantien** [comment] 2019-03-21 09:31
> > replace jcenter() with
> > maven { url 'http://maven.aliyun.com/nexus/content/repositories/jcenter' }
> > maven { url 'http://maven.aliyun.com/nexus/content/groups/public/' }, and it fixed
> 
> Thanks. But i dont know why what was happened and that will work good in future ?

It not work in Android Studio 3.3.2

**Comment by dizytech** [comment] 2019-03-21 09:31
same here

**Comment by SwathyPA** [comment] 2019-03-21 09:32
😢 Same here

**Comment by ali226281** [comment] 2019-03-21 09:32
the best solution, Turn off the computer And rest for moments!😄

**Comment by tuananhluong** [comment] 2019-03-21 09:33
> > replace jcenter() with
> > maven { url 'http://maven.aliyun.com/nexus/content/repositories/jcenter' }
> > maven { url 'http://maven.aliyun.com/nexus/content/groups/public/' }, and it fixed
> 
> Thanks. But i dont know why what was happened and that will work good in future ?

Server bintray bị down nên og ko tải package để build đc, chỉ có cách là đợi nó sống lại. Hoặc og có thể làm theo hướng dẫn như mấy ng trên: tắt kết nối mạng để build. 
Bintray là gì thì google để biết thêm :)

**Comment by ttdat2510** [comment] 2019-03-21 09:33
> I am tired, you can help me ?
> ![image](https://user-images.githubusercontent.com/18244801/54742725-c45c5680-4bf4-11e9-9cb0-a8ec8c8cd29f.png)

nope! we have to wait until the server will be fixed . =)) , server dieeeeee

**Comment by ttdat2510** [comment] 2019-03-21 09:33
> > > replace jcenter() with
> > > maven { url 'http://maven.aliyun.com/nexus/content/repositories/jcenter' }
> > > maven { url 'http://maven.aliyun.com/nexus/content/groups/public/' }, and it fixed
> > 
> > 
> > Thanks. But i dont know why what was happened and that will work good in future ?
> 
> Server bintray bị down nên og ko tải package để build đc, chỉ có cách là đợi nó sống lại. Hoặc og có thể làm theo hướng dẫn như mấy ng trên: tắt kết nối mạng để build.
> Bintray là gì thì google để biết thêm :)
:)))  chết lâu chưa bác , E mới  npm xong cái chết mất

**Comment by jdgalani** [comment] 2019-03-21 09:34
check now its working

**Comment by tuananhluong** [comment] 2019-03-21 09:35
> > > replace jcenter() with
> > > maven { url 'http://maven.aliyun.com/nexus/content/repositories/jcenter' }
> > > maven { url 'http://maven.aliyun.com/nexus/content/groups/public/' }, and it fixed
> > 
> > 
> > Thanks. But i dont know why what was happened and that will work good in future ?
> 
> Server bintray bị down nên og ko tải package để build đc, chỉ có cách là đợi nó sống lại. Hoặc og có thể làm theo hướng dẫn như mấy ng trên: tắt kết nối mạng để build.
> Bintray là gì thì google để biết thêm :)
> :))) chết lâu chưa bác , E mới npm xong cái chết mất
Xem status ở đây này: https://status.bintray.com/, die tầm 1 tieng trc ròi bác ei

**Comment by supernhok13** [comment] 2019-03-21 09:40
> 
> 
> > > > replace jcenter() with
> > > > maven { url 'http://maven.aliyun.com/nexus/content/repositories/jcenter' }
> > > > maven { url 'http://maven.aliyun.com/nexus/content/groups/public/' }, and it fixed
> > > 
> > > 
> > > Thanks. But i dont know why what was happened and that will work good in future ?
> > 
> > 
> > Server bintray bị down nên og ko tải package để build đc, chỉ có cách là đợi nó sống lại. Hoặc og có thể làm theo hướng dẫn như mấy ng trên: tắt kết nối mạng để build.
> > Bintray là gì thì google để biết thêm :)
> > :))) chết lâu chưa bác , E mới npm xong cái chết mất
> > Xem status ở đây này: https://status.bintray.com/, die tầm 1 tieng trc ròi bác ei

2 người anh em việt nam :D . Source tui xài firebase xài cách trên không được, tắt mạng hay xóa jcenter cũng không được nốt. Jcenter down cả tiếng đồng hồ rồi, giờ đang ngồi hóng

**Comment by 1agiloke** [comment] 2019-03-21 09:42
Hi, brothers from Vietnam. Would you please communicate in english?

**Comment by MurugappanV** [comment] 2019-03-21 09:42
> check now its working

I am still getting 502 error for https://jcenter.bintray.com/

**Comment by lampercy** [comment] 2019-03-21 09:43
metoo

**Comment by BarinderGrewal** [comment] 2019-03-21 09:45
> Unable to load Maven meta-data from https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml.
> Could not HEAD 'https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

**Comment by supernhok13** [comment] 2019-03-21 09:45
> 
> 
> Hi, brothers from Vietnam. Would you please communicate in english?

Sorry if that bothers you. Just asking for any solution :))

**Comment by ekastan** [comment] 2019-03-21 09:48
same in Indonesia...

**Comment by prajotNaik** [comment] 2019-03-21 09:48
> check now its working

Its not !!

**Comment by yulia0817** [comment] 2019-03-21 09:49
> check now its working
not working now ...

**Comment by vadsaaa** [comment] 2019-03-21 09:50
**it's 100% back to normal ... happy coding kaaaaang **

**Comment by marjenitish** [comment] 2019-03-21 09:50
Replacing jcenter() with maven leads to error while syncing gradle

**Comment by syedatifgd** [comment] 2019-03-21 09:50
Well I guess I'll go to sleep and come to back to check on it later.

**Comment by marjenitish** [comment] 2019-03-21 09:51
> Replacing jcenter() with maven leads to error while syncing gradle

Ignore this. It's working now

**Comment by 1agiloke** [comment] 2019-03-21 09:52
it's not yet

**Comment by neemssoni** [comment] 2019-03-21 09:53
It is not working still

**Comment by bachlongkocanh** [comment] 2019-03-21 09:55
+1 same here, how to resolve?

**Comment by superzhang2013** [comment] 2019-03-21 09:56
not working still

**Comment by wasiquehaider** [comment] 2019-03-21 09:56
![bad gateway](https://user-images.githubusercontent.com/26715284/54744699-78f07b00-4be9-11e9-9aca-5464410be7d6.PNG)

Its Still Down

**Comment by david-phpFox** [comment] 2019-03-21 09:59
not working still

**Comment by rajasekaranm** [comment] 2019-03-21 09:59
It's not working

**Comment by phanvantien** [comment] 2019-03-21 09:59
![image](https://user-images.githubusercontent.com/18244801/54744878-b01b5800-4bfa-11e9-85b6-34a61952e822.png)
Not working still

**Comment by Shahzaibmalik55** [comment] 2019-03-21 10:02
same here

**Comment by HueNguyenFramgia** [comment] 2019-03-21 10:03
same here :(

**Comment by leoaion** [comment] 2019-03-21 10:03
same here

**Comment by mmuneeb10** [comment] 2019-03-21 10:03
https://jcenter.bintray.com/
Not Working.
Same here 👎

**Comment by NweThazin** [comment] 2019-03-21 10:04
Same here..

**Comment by nyancodeid** [comment] 2019-03-21 10:04
same here #flutter_dev #indonesia

**Comment by Theng** [comment] 2019-03-21 10:05
They fixing. you can check status here, https://status.bintray.com

**Comment by ThinhNguyenVN** [comment] 2019-03-21 10:05
same here !!

**Comment by abdulmoizshaikh** [comment] 2019-03-21 10:06
Same here !!

**Comment by Mohammad-Khalid23** [comment] 2019-03-21 10:07
same here 👎
Karachi,Pakistan.

**Comment by EthanJMY** [comment] 2019-03-21 10:08
switch to aliyun😊
maven { url 'http://maven.aliyun.com/nexus/content/repositories/jcenter'}
maven { url 'http://maven.aliyun.com/nexus/content/groups/public/'}

**Comment by jaidBinHashem** [comment] 2019-03-21 10:09
Same here from Dhaka, Bangladesh

**Comment by sangeeth9819** [comment] 2019-03-21 10:10
same here in 
sri lanka

**Comment by choheeis** [comment] 2019-03-21 10:11
same here!

**Comment by supernhok13** [comment] 2019-03-21 10:11
![image](https://user-images.githubusercontent.com/28645715/54745533-54ea6500-4bfc-11e9-966b-7486238354b5.png)
Guess it's kind of serious, we have to wait for a while

**Comment by ttdat2510** [comment] 2019-03-21 10:12
> same here :(

wowww beautiful girl .Hi  i'm from HCM , in time rest , we can tells something

**Comment by wasiquehaider** [comment] 2019-03-21 10:15
> > same here :(
> 
> wowww beautiful girl .Hi i'm from HCM , in time rest , we can tells something

if you wanna flirt go to tinder

**Comment by kelset** [comment] 2019-03-21 10:16
Allright let's stop it here. Yes you are all having that issue because it's caused by this service -> https://status.bintray.com/

nothing we can do about it, it's something that every Android person building apps today will be experiencing.

**Comment by kelset** [comment] 2019-03-21 15:27
Allright, the status page says "Monitoring - Downloads are back to normal, we are still monitoring the system.".

Closing.

**Closed by kelset** 2019-03-21 15:27 UTC
Labels: DX, Platform: Android
