### ISSUE TITLE
C++ Exception in 'NativeModules': java.lang.IncompatibleClassChangeError: android.support.v4.content.ContextCompat

### ISSUE THREAD

**Issue by TristanLudrow** [facebook/react-native#15159] opened 2017-07-24 01:40 UTC
(Write what happened. Add screenshots!)
![tim 20170724094000](https://user-images.githubusercontent.com/16358265/28505196-15e3ffe0-7054-11e7-836f-1fa43033f2a8.png)

**Comment by hramos** [comment] 2017-07-24 17:25
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-07-24 17:25 UTC
