### ISSUE TITLE
Issue building android duplicate versions of jetified-kotlin-stdlib-1

### ISSUE THREAD

**Issue by mljlynch** [facebook/react-native#35979] opened 2023-01-26 16:42 UTC
### Description

running `npx react-native android`

I get the following error:

```
Execution failed for task ':app:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > More than one file was found with OS independent path 'META-INF/kotlin-stdlib-jdk7.kotlin_module'.
```

This repros in CI as well

### Version

0.63.5

### Output of `npx react-native info`

System:
    OS: macOS 13.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 136.32 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v14.18.0/bin/npm
    Watchman: 2022.09.19.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
    Python: 3.10.3 - /Users/Jake/.pyenv/shims/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.5 => 0.63.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

`npx react-native android`

### Snack, code example, screenshot, or link to a repository

NA

**Comment by janilamppu** [comment] 2023-01-26 16:50
I believe this is the same issue I've been battling with for a couple of hours now.

`
* What went wrong:
Execution failed for task ':app:checkReleaseDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class kotlin.collections.jdk8.CollectionsJDK8Kt found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.4.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.4.10)
`

I found a potential fix of upgrading kotlinVersion to 1.8.0 in build.gradle, but that didn't help. Apparently because React Native has version 1.4.10 on it.

**Comment by rysssbekov** [comment] 2023-01-26 16:54
> I believe this is the same issue I've been battling with for a couple of hours now.
> 
> ```
> * What went wrong:
> Execution failed for task ':app:checkReleaseDuplicateClasses'.
> > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
>    > Duplicate class kotlin.collections.jdk8.CollectionsJDK8Kt found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.4.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.4.10)
> ```
> 
> I found a potential fix of upgrading kotlinVersion to 1.8.0 in build.gradle, but that didn't help. Apparently because React Native has version 1.4.10 on it.

I thought I was the only one, I have also been getting this same issue since today.

**Comment by craigtsmith-memmo** [comment] 2023-01-26 16:55
Our nightly build started exhibiting this issue ~ 18 hours ago.

**Comment by mljlynch** [comment] 2023-01-26 17:42
> Our nightly build started exhibiting this issue ~ 18 hours ago.

This was when I started seeing this issue as well.

**Comment by jbaez** [comment] 2023-01-26 17:51
This fix worked for me in the meantime:
```
     constraints {
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.0") {
            because("kotlin-stdlib-jdk7 is now a part of kotlin-stdlib")
        }
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.0") {
            because("kotlin-stdlib-jdk8 is now a part of kotlin-stdlib")
        }
    }
```
(android/app/build.gradle)

I think if using a modern Kotlin Gradle Plugin you can also add the Gradle property `kotlin.stdlib.jdk.variants.version.alignment=false`
(https://kotlinlang.org/docs/whatsnew18.html#usage-of-the-latest-kotlin-stdlib-version-in-transitive-dependencies)

**Comment by mljlynch** [comment] 2023-01-26 18:36
This also worked for me!

**Comment by janilamppu** [comment] 2023-01-26 19:16
> This fix worked for me in the meantime:
> 
> ```
>      constraints {
>         implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.0") {
>             because("kotlin-stdlib-jdk7 is now a part of kotlin-stdlib")
>         }
>         implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.0") {
>             because("kotlin-stdlib-jdk8 is now a part of kotlin-stdlib")
>         }
>     }
> ```
> 
> (android/app/build.gradle)
> 
> I think if using a modern Kotlin Gradle Plugin you can also add the Gradle property `kotlin.stdlib.jdk.variants.version.alignment=false` (https://kotlinlang.org/docs/whatsnew18.html#usage-of-the-latest-kotlin-stdlib-version-in-transitive-dependencies)

Perfect, works! Thank you.

**Comment by mashish584** [comment] 2023-01-27 04:25
Fixed work for me. 

  ```


[Checkout here](https://youtrack.jetbrains.com/issue/KT-55297/kotlin-stdlib-should-declare-constraints-on-kotlin-stdlib-jdk8-and-kotlin-stdlib-jdk7)

**Comment by ArunKumarBhardwaj** [comment] 2023-01-27 08:58
> This fix worked for me in the meantime:
> 
> ```
> dependencies {
>      constraints {
>         implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.0") {
>             because("kotlin-stdlib-jdk7 is now a part of kotlin-stdlib")
>         }
>         implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.0") {
>             because("kotlin-stdlib-jdk8 is now a part of kotlin-stdlib")
>         }
>     }
> }
> ```
> 
> (android/app/build.gradle)
> 
> I think if using a modern Kotlin Gradle Plugin you can also add the Gradle property `kotlin.stdlib.jdk.variants.version.alignment=false` (https://kotlinlang.org/docs/whatsnew18.html#usage-of-the-latest-kotlin-stdlib-version-in-transitive-dependencies)

Worked for me. Thanks

**Comment by cortinico** [comment] 2023-01-27 18:42
Closing as the workaround is reported as working fine.

**Closed by cortinico** 2023-01-27 18:42 UTC
Labels: Platform: Android, Needs: Triage :mag:

**Comment by RyanThomas73** [comment] 2023-01-27 19:25
In my company's case I did a comparison of the gradle dependency graph to identify what introduced the change in the build dependencies.

The problem was introduced by this library's use of a version wildcard:
https://github.com/proyecto26/react-native-inappbrowser/issues/398

And the solution we went with was to specify `androidXAnnotation = "1.5.0"` as an `ext` in the `android/build.gradle` file

**Comment by stetbern** [comment] 2023-01-30 11:09
> This fix worked for me in the meantime:
> 
> ```
> dependencies {
>      constraints {
>         implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.0") {
>             because("kotlin-stdlib-jdk7 is now a part of kotlin-stdlib")
>         }
>         implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.0") {
>             because("kotlin-stdlib-jdk8 is now a part of kotlin-stdlib")
>         }
>     }
> }
> ```
> 
> (android/app/build.gradle)
> 
> I think if using a modern Kotlin Gradle Plugin you can also add the Gradle property `kotlin.stdlib.jdk.variants.version.alignment=false` (https://kotlinlang.org/docs/whatsnew18.html#usage-of-the-latest-kotlin-stdlib-version-in-transitive-dependencies)

This can lead to other problems with kotlin files like

> Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.

Solution by @RyanThomas73 fixes the root cause: We also had a library where the androidx.core:core used a wildcard. Specifying a pinned version fixed the issue.

**Comment by castalonirenz** [comment] 2023-01-31 06:10
> constraints {
>         implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.0") {
>             because("kotlin-stdlib-jdk7 is now a part of kotlin-stdlib")
>         }
>         implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.0") {
>             because("kotlin-stdlib-jdk8 is now a part of kotlin-stdlib")
>         }
>     }

This works for me also

**Comment by Amir-mohsenian** [comment] 2023-02-01 08:44
> ```
> implementation(platform("org.jetbrains.kotlin:kotlin-bom:1.8.0"))
> ```

This worked for me.

**Comment by sgtpsibin** [comment] 2023-02-06 07:00
> In my company's case I did a comparison of the gradle dependency graph to identify what introduced the change in the build dependencies.
> 
> The problem, in our case, was introduced by this library's use of a version wildcard: [proyecto26/react-native-inappbrowser#398](https://github.com/proyecto26/react-native-inappbrowser/issues/398)
> 
> And the solution we went with was to specify `androidXAnnotation = "1.5.0"` as an `ext` in the `android/build.gradle` file

this should be the best workaround

**Comment by subalee** [comment] 2023-02-06 13:58
> In my company's case I did a comparison of the gradle dependency graph to identify what introduced the change in the build dependencies.
> 
> The problem, in our case, was introduced by this library's use of a version wildcard: [proyecto26/react-native-inappbrowser#398](https://github.com/proyecto26/react-native-inappbrowser/issues/398)
> 
> And the solution we went with was to specify `androidXAnnotation = "1.5.0"` as an `ext` in the `android/build.gradle` file

worked for me, the solution from @jbaez didn't work for some reason.

**Comment by Das3kn** [comment] 2023-04-14 05:02
> This fix worked for me in the meantime:
> 
> ```
> dependencies {
>      constraints {
>         implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.0") {
>             because("kotlin-stdlib-jdk7 is now a part of kotlin-stdlib")
>         }
>         implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.0") {
>             because("kotlin-stdlib-jdk8 is now a part of kotlin-stdlib")
>         }
>     }
> }
> ```
> 
> (android/app/build.gradle)
> 
> I think if using a modern Kotlin Gradle Plugin you can also add the Gradle property `kotlin.stdlib.jdk.variants.version.alignment=false` (https://kotlinlang.org/docs/whatsnew18.html#usage-of-the-latest-kotlin-stdlib-version-in-transitive-dependencies)

YOU ARE MY HERO

**Comment by sv-coderepo** [comment] 2023-05-24 10:40
> Below fixed work for me.
> 
> ```
> implementation(platform("org.jetbrains.kotlin:kotlin-bom:1.8.0"))
> ```
> 
> [Checkout here](https://youtrack.jetbrains.com/issue/KT-55297/kotlin-stdlib-should-declare-constraints-on-kotlin-stdlib-jdk8-and-kotlin-stdlib-jdk7)

Saved my day

**Comment by kirkaDev** [comment] 2023-06-13 13:49
> implementation(platform("org.jetbrains.kotlin:kotlin-bom:1.8.0"))

Me too. But I sinceraly don't understand why after creation Java-project with Android Studio's wizard I have any problems with Kotlin.

**Comment by jienian** [comment] 2023-08-02 06:00
你好
我是聋人，第一次接触Andorid开发，不知道怎么入手。。求指导下，谢谢

**Comment by anisurrahman072** [comment] 2023-12-16 09:14
> Below fixed work for me.
> 
> ```
> implementation(platform("org.jetbrains.kotlin:kotlin-bom:1.8.0"))
> ```
> 
> [Checkout here](https://youtrack.jetbrains.com/issue/KT-55297/kotlin-stdlib-should-declare-constraints-on-kotlin-stdlib-jdk8-and-kotlin-stdlib-jdk7)

Wow, it helped me too. My issue of below has been solved to.

### Reason of my issue
- I was migrating from RN v0.71.7 to RN v0.72.0 & that issue raised. Your solution worked 🔥

### Error screenshot
![image](https://github.com/facebook/react-native/assets/40535268/b68edadd-ff8b-493e-9ab9-17e3b653b4ed)

**Comment by philburk** [comment] 2024-04-04 00:09
I had the same error message in an unrelated project.
I found these two lines in my build.gradle.kts file:

    implementation(libs.androidx.material3)
    implementation(libs.androidx.material3.android)

I removed the second line and then it worked.
