### ISSUE TITLE
deepDiffer code triggers "Your code is broken" warnings about for...in Array iteration

### ISSUE THREAD

**Issue by ccheever** [facebook/react-native#870] opened 2015-04-16 00:20 UTC
This code in `Libraries/Utilities/differ/deepDiffer.js` triggers the warning mentioned in #869

```js
        for (var key in one) {
            if (deepDiffer(one[key], two[key])) {
                return true;
            }
        }
        for (var twoKey in two) {
            // The only case we haven't checked yet is keys that are in two but aren't
            // in one, which means they are different.
            if (one[twoKey] === undefined && two[twoKey] !== undefined) {
                return true;
            }
        }

```

**Comment by spicyj** [comment] 2015-04-16 00:42
Dupe of #868, it looks like.

**Closed by spicyj** 2015-04-16 00:42 UTC
