### ISSUE TITLE
Extending built-in JS objects

### ISSUE THREAD

**Issue by scotbond** [facebook/react-native#14657] opened 2017-06-21 10:52 UTC
Trying to extend `Date` in order to provide some custom formatters but the returned object is empty {}.
The same code pass with `node` which produce proper `Date` object.
Is this a bug/limitation in RN?

```
class MyDate extends Date {
    constructor(time) {
        super(time)
    }
}
var a = new MyDate(1498036670000)
console.log(a)
```

**Comment by hramos** [comment] 2017-06-21 18:54
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-21 18:54 UTC
