### ISSUE TITLE
apple connect reject Invalid binary The app contains one or more corrupted binaries. Please rebuild the app and resubmit.

### ISSUE THREAD

**Issue by renyufei8023** [facebook/react-native#46275] opened 2024-08-30 07:20 UTC
### Description

Please correct the following issues and upload a new binary to App Store Connect.

ITMS-90714: Invalid binary - The app contains one or more corrupted binaries. Please rebuild the app and resubmit.

Apple Developer Relations

### Steps to reproduce

0.71.19 update to 0.74.5

### React Native Version

0.74.5

### Affected Platforms

Build - MacOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 13.6.9
  CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
  Memory: 998.79 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.20.3
    path: /usr/local/opt/node@18/bin/node
  Yarn:
    version: 1.22.22
    path: ~/Desktop/steamtrade-desk/node_modules/.bin/yarn
  npm:
    version: 10.7.0
    path: /usr/local/opt/node@18/bin/npm
  Watchman:
    version: 2024.05.06.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.3 AI-233.14808.21.2331.11842104
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.5
    wanted: 0.74.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Stacktrace or Logs

```text
Please correct the following issues and upload a new binary to App Store Connect.

ITMS-90714: Invalid binary - The app contains one or more corrupted binaries. Please rebuild the app and resubmit.

Apple Developer Relations
```

### Reproducer

http://

**Comment by renyufei8023** [comment] 2024-08-30 07:22
package.json:

"dependencies": {
    "@ant-design/icons-react-native": "2.3.2",
    "@ant-design/react-native": "5.0.4",
    "@bang88/react-native-ultimate-listview": "4.1.0",
    "@invertase/react-native-apple-authentication": "^2.3.0",
    "@microsoft/signalr": "8.0.7",
    "@react-native-async-storage/async-storage": "1.24.0",
    "@react-native-camera-roll/camera-roll": "7.0.0",
    "@react-native-clipboard/clipboard": "1.14.1",
    "@react-native-community/blur": "^4.4.0",
    "@react-native-community/datetimepicker": "8.2.0",
    "@react-native-community/hooks": "^3.0.0",
    "@react-native-community/netinfo": "11.3.2",
    "@react-native-community/segmented-control": "2.2.2",
    "@react-native-community/slider": "4.5.2",
    "@react-native-cookies/cookies": "6.2.1",
    "@react-native-hero/umeng-push": "0.3.3",
    "@react-native-picker/picker": "2.7.7",
    "@react-native-segmented-control/segmented-control": "^2.5.2",
    "@react-navigation/bottom-tabs": "6.6.1",
    "@react-navigation/elements": "1.3.31",
    "@react-navigation/native": "6.1.18",
    "@react-navigation/native-stack": "6.11.0",
    "@react-navigation/stack": "6.4.1",
    "@sentry/react-native": "^5.30.0",
    "@shopify/flash-list": "1.7.1",
    "@shopify/react-native-skia": "1.3.10",
    "@uiw/react-native-alipay": "5.0.2",
    "@wuba/react-native-echarts": "1.2.5",
    "@yz1311/react-native-wheel-picker": "0.4.2",
    "add": "^2.0.6",
    "buffer": "^6.0.3",
    "crypto-js": "^4.2.0",
    "echarts": "5.4.3",
    "he": "^1.2.0",
    "highlight-words-core": "^1.2.2",
    "i18next": "^23.11.5",
    "jsencrypt": "^3.3.2",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "node-emoji": "^2.1.3",
    "react": "18.2.0",
    "react-i18next": "^15.0.1",
    "react-native": "0.74.5",
    "react-native-auto-size-text": "^1.1.1",
    "react-native-background-timer": "2.4.1",
    "react-native-bootsplash": "6.1.1",
    "react-native-clarity": "3.0.1",
    "react-native-code-push": "8.3.1",
    "react-native-collapsible-tab-view": "6.2.1",
    "react-native-device-info": "10.10.0",
    "react-native-exit-app": "2.0.0",
    "react-native-fast-shadow": "^0.1.1",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "2.18.1",
    "react-native-get-random-values": "1.9.0",
    "react-native-haptic-feedback": "2.2.0",
    "react-native-hash": "^3.0.3",
    "react-native-image-picker": "^7.0.2",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-linear-gradient": "2.8.3",
    "react-native-mmkv": "3.0.0-beta.7",
    "react-native-modal": "13.0.1",
    "react-native-new-fast-image": "^8.6.8",
    "react-native-new-snap-carousel": "^3.9.3",
    "react-native-orientation-locker": "1.7.0",
    "react-native-pager-view": "6.4.0",
    "react-native-permissions": "3.10.1",
    "react-native-progress": "^5.0.1",
    "react-native-reanimated": "3.15.0",
    "react-native-render-html": "^6.3.4",
    "react-native-root-siblings": "^5.0.1",
    "react-native-safe-area-context": "4.10.8",
    "react-native-screens": "3.32.0",
    "react-native-segmented-control-tab": "^4.0.0",
    "react-native-shimmer-placeholder": "2.0.9",
    "react-native-snap-carousel": "^4.0.0-beta.6",
    "react-native-svg": "15.5.0",
    "react-native-swipe-list-view": "^3.2.9",
    "react-native-ui-lib": "7.28.0",
    "react-native-vector-icons": "10.1.0",
    "react-native-video": "6.4.5",
    "react-native-webview": "13.10.5",
    "react-native-wechat-lib": "^1.1.27",
    "react-usestateref": "^1.0.8",
    "save": "^2.9.0",
    "sharp": "^0.32.6",
    "url-parse": "^1.5.10",
    "yarn": "^1.22.22"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/babel-preset": "0.74.87",
    "@react-native/eslint-config": "0.74.87",
    "@react-native/metro-config": "0.74.87",
    "@react-native/typescript-config": "0.74.87",
    "@sentry/cli": "^2.30.4",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^29.2.1",
    "@types/react": "^18.2.6",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "patch-package": "^7.0.0",
    "prettier": "^2.8.8",
    "react-test-renderer": "18.2.0",
    "typescript": "5.0.4"
  },

**Comment by cipolleschi** [comment] 2024-09-12 13:21
Hi there, we cannot really help you if you don't provide a reproducer and the full error from apple.
Also, what app are you trying to submit? You are mentioning that the problem is `Build - MacOS` so if you are creating a macOS app, please open an issue in the [react-native-macos](https://github.com/microsoft/react-native-macos) repository.

**Comment by vksgautam1** [comment] 2024-09-13 04:33
Hi @cipolleschi the reason which i found for this was that react native maps was generating some invalid value of a key whenever we were doing pod install.
https://github.com/react-native-maps/react-native-maps/issues/5007

we got email from apple
Hello,

We noticed one or more issues with a recent submission for App Store review for the following app:

xxxxxxxxxx⁺
Version 2.44
Build 1
Please correct the following issues and upload a new binary to App Store Connect.

ITMS-91054: Invalid API category declaration - The PrivacyInfo.xcprivacy file at the “PrivacyInfo.xcprivacy” path contains “NSFileModificationDate” as the value for a NSPrivacyAccessedAPIType key, which is invalid. Values for NSPrivacyAccessedAPIType keys in your app’s privacy manifests must be valid API categories. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

Though you are not required to fix the following issues, we wanted to make you aware of them:

ITMS-91105: Invalid API category declaration - The PrivacyInfo.xcprivacy file at the “ReactNativeMapsPrivacy.bundle/PrivacyInfo.xcprivacy” path contains “NSFileModificationDate” as the value for a NSPrivacyAccessedAPIType key, which is invalid. In addition to the privacy manifest files in the locations outlined in the documentation, starting November 12, 2024, all privacy manifests you submit must have valid content. Values for NSPrivacyAccessedAPIType keys in any privacy manifest must be valid API categories. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/adding_a_privacy_manifest_to_your_app_or_third-party_sdk and https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

Apple Developer Relations

**Comment by cortinico** [comment] 2024-09-13 08:16
Closing as related to React Native Maps:
- https://github.com/react-native-maps/react-native-maps/issues/5007

**Closed by cortinico** 2024-09-13 08:16 UTC
Labels: Needs: Author Feedback, Needs: Repro

**Comment by renyufei8023** [comment] 2024-09-20 01:46
I am not related to the task and Privacy Manifest. I am now using the previous code, React native@0.71.19 And then I changed the IPHONOS_SDEPLOYMENT_TARGET to 13.4, which also caused this problem. I also changed the min_ios-version_Supported in the podfile to 13.4

**Comment by renyufei8023** [comment] 2024-09-25 02:12
@cortinico I found the problem, but I don't know how to solve it. It's because I encountered this issue when integrating MPaaas. If React native@0.71 There is no such problem.mpaas：https://help.aliyun.com/document_detail/165234.html?spm=a2c4g.165233.0.0.44a02e00lI3VOK

**Comment by cipolleschi** [comment] 2024-09-25 13:29
@renyufei8023 version 0.71 does not have the privacy manifest, IIRC. I believe that the problem is that MPaaas is not configuring their privacy manifest correctly. I believe you should submit an issue to MPaaas directly because if they are signing their binary, they need to create a new release of it.

**Comment by renyufei8023** [comment] 2024-09-30 02:02
@cipolleschi I don't think it's a problem with the privacy manifest, because some libraries are normal regardless of whether they contain a privacy manifest or not. I feel like it's an issue with IPHONOS_STEPLOYMENT_TARGET, thinking that MPaas' IPHONOS_STEPLOYMENT_TARGET is either 5.0 or 6.0
