### ISSUE TITLE
react-native 0.46.1 cannot run in the ios 

### ISSUE THREAD

**Issue by zhyilong** [facebook/react-native#15361] opened 2017-08-03 15:17 UTC
1. `react-native -v`:  react 16.0.0beat16  react-native0.45.1
2. `node -v`: 8.1.3
3. `npm -v`: 5.0+
4. `yarn --version`
5.xcode 8.3.3

(Write your steps here:)

1.react-native init projectname
2.react-native run-ios 
3.build failed

Errors:

   Analyze /node/RNDemo/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.c
Analyze /node/RNDemo/node_modules/react-native/ReactCommon/yoga/yoga/YGNodeList.c
(2 commands with analyzer issues)

The following build commands failed:
PhaseScriptExecution Install\ Third\ Party /node/RNDemo/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/double-conversion.build/Script-190EE32F1E6A43DE00A8543A.sh
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/RNDemo.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/RNDemo.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

  Thanks for helping us help you!
-->

**Comment by abdulsemiu-atanda** [comment] 2017-08-03 16:03
I'm experiencing the same issue.

**Comment by abdulsemiu-atanda** [comment] 2017-08-03 16:08
I'm getting this error when I try to run `npm start` or `yarnpkg start`
`react-native-scripts start

5:06:38 PM: Starting packager...
***ERROR STARTING PACKAGER***
Starting React Native packager...
Scanning 720 folders for symlinks in /Users/abdulsemiuatanda/dailytrends/node_modules (18ms)
Loading dependency graph.
Running packager on port 19001.


2017-08-03 17:06 node[10419] (FSEvents.framework)
***ERROR STARTING PACKAGER***

FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
***ERROR STARTING PACKAGER***

2017-08-03 17:06 node[10419] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)`

**Comment by hramos** [comment] 2017-08-03 17:31
Duplicate of #14447

**Closed by hramos** 2017-08-03 17:31 UTC
