### ISSUE TITLE
[iOS] WebView should handle custom URL scheme correctly

### ISSUE THREAD

**Issue by eggli** [facebook/react-native#9037] opened 2016-07-27 08:13 UTC
Hi, we're working on a small RN project which has an in-app browser embed inside, the product itself has been released on AppStore, but yet we have received some randomly error screen rendered in the WebView, after a long time investigation, we finally figured out it's the iOS deep linking URL scheme triggered the default WebView error render view, which can be easily reproduced via entering a SlideShare.net URL(not the mobile one), which redirects the WebView to it's own app, if user has no such app installed on their device, a WebKitErrorDomain will be throw from UIWebView hence triggers all the rest error handling mechanisms.

Here's the URL we are testing:

http://www.slideshare.net/branchmetrics/the-2016-mobile-growth-handbook-64218146

RNPlay to reproduce:
https://rnplay.org/apps/TxDHtw

RNPlay is still on 0.24, but this error can also be reproduced on RN 0.30.0

And here's the screenshot from XCode where the error has been thrown:

![screen shot 2016-07-27 at 3 50 05 pm](https://cloud.githubusercontent.com/assets/182688/17167845/d2b0d4dc-5411-11e6-81b4-23b0abf166e5.png)

As you can see, the error from UIWebView shows the NSErrorFailingURLKey as slideshare-app://ss/64093801 which is a custom URL scheme.

If we open the test link mentioned above in Safari.app without SlideShare app installed, Safari won't show any error message and working perfectly.

I've been searched the issues reported here, found these issue might be related to this error:
#6707,  #7839, #4337, #7839.

Here's few thoughts to resolve this issue:
1. WebView shouldn't trigger onLoadingError if the URL scheme itself is not supported, just like Safari.
2. Currently, onLoadingError is going to render WebView's view state to error thus rendered the error view, default or not, it should allow developers to decide where to show error view or not via returning true/false after invoking onError method. In such case, the error event sent from RCTWebView to WebView should had the NSErrorFailingURLKey included, not only the url from UIWebView.

**Comment by lacker** [comment] 2016-10-28 19:56
There is at least a workaround, from one of those other issues:

    <WebView
      domStorageEnabled={ true }
      javaScriptEnabled={ true }
      renderError={ (e) => {
        if (e === 'WebKitErrorDomain') {
          return
        }
      }}
      source={{ uri: "https://99f9e623.ngrok.io/auth/sign_in_with_slack?source=app" }}
      style={ styles.container }
    />

The question which I don't know the answer to is whether this behavior is inherent to WebView and the right solution is switching to WKWebView (as some have suggested), or whether this can just be fixed in WebView.

**Comment by messuti-edd** [comment] 2016-11-04 00:40
@lacker that workaround does not solve this issue for me :( it only hides the error message but the webview turns blank when it happens.

I'm testing in react-native 0.36.1.

**Comment by alexkasemir** [comment] 2016-11-17 17:29
yes @lacker, that workaround does not seem to work.

**Comment by jjshammas** [comment] 2016-12-27 17:00
Well an easy solution would be just to return NO for `shouldStartLoadWithRequest` if the protocol is not HTTP or HTTPS: https://github.com/facebook/react-native/blob/master/React/Views/RCTWebView.m#L251

Any idea what the repercussions might be if that were the case?

**Comment by indivisable** [comment] 2017-02-04 07:34
@jjshammas Do you have working example for your RCTWebView? I am trying to get it to work with Plaid Link too with not much luck :/

**Comment by firetheworld** [comment] 2017-05-20 03:11
I'm on RN version 0.43,I have this problem also
Have you fixed this problem?
@lacker @eggli

**Comment by eggli** [comment] 2017-05-22 03:55
@firetheworld Yes, we did solve this problem by doing it in a super brutal and not-very-open-source-way: We wrote our own iOS WebView to replace React Native's built in since no one in Facebook cares about this problem and we found it's not easy to solve, here's our solution, it's brutal, not very cool, but it works:

```objective-c

- (BOOL)webView:(__unused UIWebView *)webView shouldStartLoadWithRequest:(NSURLRequest *)request
 navigationType:(UIWebViewNavigationType)navigationType
{
 
  if (![request.URL.scheme isEqual:@"http"] && 
      ![request.URL.scheme isEqual:@"https"] && 
      ![request.URL.scheme isEqual:@"about:blank"]) {
         if ([[UIApplication sharedApplication]canOpenURL:request.URL]) {
             [[UIApplication sharedApplication]openURL:request.URL];
         }
      return NO;
  }

return YES;

}
```

In the code above, if we found the URL is not whatever we can handle, we skip it to avoid any error message being throw to React Native, and asks iOS if user's device is capable to handle that custom scheme url, if so, we hand over the URL to iOS so user still get other apps' deep linking URL working.

I believe there SHOULD be a better way ( or at least a neat one ) to handle this.

**Comment by hramos** [comment] 2017-07-26 05:54
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Closed by hramos** 2017-07-26 05:54 UTC
Labels: Icebox, iOS

**Comment by surdu** [comment] 2017-11-06 14:55
Or maybe people have said all the details and are now waiting for a fix ? 

If you'd seen a lot of +1s someone would have comment to stop posting +1 as it's not helping.

**Comment by zsaraf** [comment] 2017-11-08 20:15
Any update on whether this will be fixed in a future release? Still having the exact same issue

**Comment by messutied** [comment] 2017-11-09 09:46
This was indeed never fixed for me.

**Comment by Silon** [comment] 2017-11-09 11:25
This bug still occur in RN 0.49.3...

**Comment by zhiming137** [comment] 2017-12-09 03:35
一个不好的处理方式：
renderError={ (e) => {
    this.webview.setState({viewState: 'IDLE'});
});
