### ISSUE TITLE
can't run, start, test, play with or do anything usefull with the latest react-native app

### ISSUE THREAD

**Issue by LCarlos-Rodriguez** [facebook/react-native#20692] opened 2018-08-16 16:30 UTC
- [X ] Review the documentation: https://facebook.github.io/react-native
            WHAT DOCUMENTATION? I wish this crappy error were documented
  - [X ] Search for existing issues: https://github.com/facebook/react-native/issues
             this just sends me into another rabbit hole and more waste of time
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment as created by the react-native init <app> command
{
  "name": "YodeNodeError",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.4.1",
    "react-native": "0.56.0"
  },
  "devDependencies": {
    "babel-jest": "23.4.2",
    "babel-preset-react-native": "5",
    "jest": "23.5.0",
    "react-test-renderer": "16.4.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

RN version info
Returning_from_des>react-native --version
react-native-cli: 2.0.1
react-native: 0.56.0

using the genymotion emulator but it fails equally the same using the AS emulator or a device....

## Description
Describe your issue in detail. Include screenshots if needed. If this is a regression, let us know.
1. create a new app with the react-native-cli
2. build and start the new app with the `react-native run-android` cli command
3. `go and get a towel to wipe your tears` because as expected `all hell breaks loose and nothing works`

## Reproducible Demo
run `react-native init foo`
run `react-native run-android'
![2018-08-16](https://user-images.githubusercontent.com/30121166/44221544-d3a38f00-a14f-11e8-9b3b-ec6f7547bb1f.png)

**Comment by LCarlos-Rodriguez** [comment] 2018-08-16 16:32
can't install or run watchman
have removed the node_modules several times
have recreated the app multiple times.
funny thing is, RN used to work.... PERIOD

**Comment by hramos** [comment] 2018-08-16 19:57
Your environment info looks incomplete, but from the screenshot it looks like you're using Windows. We are aware that the 0.56 release has some issues on Windows, and this is being discussed over at https://github.com/facebook/react-native/issues/20353

Friendly reminder that the project is worked on by humans, and they read what you write here.

Duplicate of #20353

**Closed by hramos** 2018-08-16 19:57 UTC
Labels: :clipboard:No Environment Info
