### ISSUE TITLE
Error while Linking SDK with IOS

### ISSUE THREAD

**Issue by kkusanagi** [facebook/react-native#16028] opened 2017-09-20 10:22 UTC
here is the report I get.

Just create new project and use command
`react-native install react-native-fbsdk`

rnpm-install info Linking react-native-fbsdk android dependency 
rnpm-install info Android module react-native-fbsdk has been successfully linked 
rnpm-install info Linking react-native-fbsdk ios dependency 
rnpm-install ERR! Something went wrong while linking. Error: Expected "/*", "//", or "{" but "<" found. 
Please file an issue here: https://github.com/facebook/react-native/issues 

Expected "/*", "//", or "{" but "<" found.

**Comment by hramos** [comment] 2017-09-21 15:22
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue that meets the requirements set forth in the template. Thanks!

**Closed by hramos** 2017-09-21 15:22 UTC
