### ISSUE TITLE
"JS has only made partial progress to catch up to UIKit" in UIExplorer app

### ISSUE THREAD

**Issue by marshallbrekka** [facebook/react-native#731] opened 2015-04-07 22:29 UTC
When clicking/tapping rapidly on the back button in the NavigatorIOS example it triggers the mentioned error message.
The comment where that error originates from indicates its probably a bug with the JS, but doesn't indicate what the solution would be.
https://github.com/facebook/react-native/blob/1dba7e0a5a1553ee3a47cab8f753e980c4ab0aef/React/Views/RCTNavigator.m#L487-L495

For what its worth the same bug is present in this app as well https://github.com/iSimar/HackerNews-React-Native

![react_native_navigator_bug](https://cloud.githubusercontent.com/assets/436140/7035095/600bdbd8-dd3a-11e4-95cf-013d2d3dbbd7.gif)

**Comment by corymsmith** [comment] 2015-04-07 22:50
This is a duplicate of #65

**Comment by Iragne** [comment] 2015-04-09 15:00
i add this code and it solve the issue not sure if i introduce an other bug
```Objective-C
BOOL jsGettingtooSlow =
  //    --- previously not caught up --------          ------- no longer caught up ----------
  viewControllerCount != previousReactCount && currentReactCount == previousReactCount;
```
```Objective-C
  if (!(jsGettingAhead ||
        jsCatchingUp ||
        jsMakingNoProgressButNeedsToCatchUp ||
        jsMakingNoProgressAndDoesntNeedTo || 
        jsGettingtooSlow)) {
    RCTLogError(@"JS has only made partial progress to catch up to UIKit");
  }
```
```Objective-C
BOOL jsGettingtooSlow =
  //    --- previously not caught up --------          ------- no longer caught up ----------
  viewControllerCount != previousReactCount && currentReactCount == previousReactCount;

  BOOL reactPushOne = jsGettingAhead && currentReactCount == previousReactCount + 1;
  BOOL reactPopN = jsGettingAhead && currentReactCount < previousReactCount;


  // We can actually recover from this situation, but it would be nice to know
  // when this error happens. This simply means that JS hasn't caught up to a
  // back navigation before progressing. It's likely a bug in the JS code that
  // catches up/schedules navigations.
  if (!(jsGettingAhead ||
        jsCatchingUp ||
        jsMakingNoProgressButNeedsToCatchUp ||
        jsMakingNoProgressAndDoesntNeedTo || 
        jsGettingtooSlow)) {
    RCTLogError(@"JS has only made partial progress to catch up to UIKit");
  }
```

Feel free to talk about it

**Closed** 2015-05-01 17:29 UTC
