### ISSUE TITLE
New project fail to build on iOS (double-conversion.build failed)

### ISSUE THREAD

**Issue by irrigator** [facebook/react-native#14368] opened 2017-06-07 15:24 UTC
## Reporting Bugs

New project fail to build on iOS (double-conversion.build failed)

### Reproduction Steps and Sample Code

```react-native init``` to create a new project and run ```react-native run-ios```

## Useful error messages:

 

> /bin/sh -c /Users/zjy/Code/play/PlayWithRN/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/double-conversion.build/Script-190EE32F1E6A43DE00A8543A.sh
> 
> Unpacking /Users/zjy/.rncache/boost_1_63_0.tar.gz...
> 
> tar: (Empty error message)
> 
> tar: Error exit delayed from previous errors.
> 
> Command /bin/sh failed with exit code 1
> 
> 
> 
> ** BUILD FAILED **
> 
> 
> The following commands produced analyzer issues:
> 
> 	Analyze /Users/zjy/Code/play/PlayWithRN/node_modules/react-native/ReactCommon/yoga/yoga/YGNodeList.c
> 	Analyze /Users/zjy/Code/play/PlayWithRN/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.c
> (2 commands with analyzer issues)
> 
> The following build commands failed:
> 	PhaseScriptExecution Install\ Third\ Party /Users/zjy/Code/play/PlayWithRN/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/double-conversion.build/Script-190EE32F1E6A43DE00A8543A.sh
> (1 failure)
> 
> Installing build/Build/Products/Debug-iphonesimulator/PlayWithRN.app
> An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
> Failed to install the requested application
> An application bundle was not found at the provided path.
> Provide a valid path to the desired application bundle.
> Print: Entry, ":CFBundleIdentifier", Does Not Exist

### Additional Information

* React Native version: 0.45.0
* Platform: iOS
* Development Operating System: macOS 10.12.5
* Dev tools: Xcode 8.3.3

**Comment by irrigator** [comment] 2017-06-07 15:35
Additional information, android version can run but only renders a white screen. Existing 0.44 app on my computer runs without any problems.

**Comment by bernatfortet** [comment] 2017-06-07 16:43
Same here

**Comment by DMCHZP** [comment] 2017-06-08 02:01
+1

**Comment by renlong** [comment] 2017-06-08 02:51
+1

**Comment by gudjao** [comment] 2017-06-08 03:34
+1

**Comment by neverlan** [comment] 2017-06-08 07:44
Same here

**Comment by moyanggong** [comment] 2017-06-08 09:22
same

**Comment by shubhnik** [comment] 2017-06-08 09:30
+1

**Comment by magicalcosmos** [comment] 2017-06-08 10:13
same to me

**Comment by Easyzhan** [comment] 2017-06-08 11:58
+1

**Comment by Barbery** [comment] 2017-06-08 13:08
+1

**Comment by davidsamacoits** [comment] 2017-06-08 19:51
Same here 👍

**Comment by llanginger** [comment] 2017-06-08 20:18
Same here, totally crippled at the moment.

Xcode & react-native-cli both updated to latest releases.

**Comment by pduy117** [comment] 2017-06-09 03:46
Same here

**Comment by wasterd** [comment] 2017-06-09 03:47
same here

**Comment by Balasnest** [comment] 2017-06-09 06:11
me too facing the same issue.

**Comment by vincentmrlau** [comment] 2017-06-09 06:32
the same 
xcode:8.3.2
react-native-cli: 2.0.1
react-native: 0.45.0

**Comment by pduy117** [comment] 2017-06-09 06:51
0.45.0 din't worked for me(same error) so i just used 0.44.0
react-native init [PROJECT_NAME] --version 0.44.0
----- Thank: shubhnik
This's worked for me!!

**Comment by windhost** [comment] 2017-06-09 10:02
+1

**Comment by windhost** [comment] 2017-06-09 10:17
Unpacking /Users/wind/.rncache/double-conversion-1.1.5.tar.gz...
Unpacking /Users/wind/.rncache/boost_1_63_0.tar.gz...
boost_1_63_0/boost/fusion/container/vector/detail/cpp03/preprocessed/vector30.hpp: (Empty error message)
tar: Error exit delayed from previous errors.
Command /bin/sh failed with exit code 1

**Comment by BeginReactNative** [comment] 2017-06-09 16:52
same here !

**Comment by fuxianwei** [comment] 2017-06-10 01:05
+1

**Comment by postace** [comment] 2017-06-10 01:43
+1 Same here, 
When run command run-ios, I didn't see the packager terminal open up.
So I follow the above instructions, downgrade react-native to 0.44.0 and wala, it works

**Comment by musicode** [comment] 2017-06-10 04:58
+1

**Comment by rochadsouza** [comment] 2017-06-10 10:48
+1

**Comment by danidewitt** [comment] 2017-06-10 18:12
+1

**Comment by ganisback** [comment] 2017-06-11 03:14
+1

**Comment by troyz** [comment] 2017-06-12 03:52
+1

**Comment by sharkrice** [comment] 2017-06-12 06:06
+1

**Comment by wh-Coder** [comment] 2017-06-12 11:34
lol same here

**Comment by viettranx** [comment] 2017-06-12 14:16
This is a stupid issue. We can resolve it by moving react native project to a folder path without white space characters.

For ex this path will not work in RN 0.45.x: /User/viettranx/React Native/DemoApp 

The reason is in where RN build the app, it export command was wrong:

`export SCROOT=/User/viettranx/React Native/DemoApp`

The right syntax must be
`export SCROOT=/User/viettranx/React\ Native/DemoApp`

That export command very important for the bash script in double conversion module.

Hope it helps.

**Comment by irrigator** [comment] 2017-06-12 14:59
@viettranx But mine does not contain any space characters.

**Comment by viettranx** [comment] 2017-06-12 15:54
@irrigator it seems file /Users/zjy/.rncache/boost_1_63_0.tar.gz could not unpack. You can check it or try removing rncache.

**Comment by irrigator** [comment] 2017-06-12 16:11
@viettranx Tried that before, does not work. Still get the same error.

**Comment by irrigator** [comment] 2017-06-12 16:12
Does it work on your machine? RN 0.45 with Xcode 8.3.3?

**Comment by viettranx** [comment] 2017-06-12 16:15
@irrigator yes.

XCode: 8.3.3
React Native: 0.45.1
React: 16.0.0-alpha.12

**Comment by bbrodsky** [comment] 2017-06-12 16:48
@viettranx been following along. Your suggestions cleared up my errors that mimicked @irrigator , but now I am facing this one:

/Users/.../node_modules/react-native/third-party/boost_1_63_0/boost/config.hpp:30:12: 'boost/config/user.hpp' file not found

My project was working fine on RN 0.44.2, React: alpha.6

**Comment by viettranx** [comment] 2017-06-12 16:58
@bbrodsky pls check /Users/.../node_modules/react-native/third-party/boost_1_63_0/boost/config folder. It include file user.hpp although it empty (but comment lines).

May be it was an issue about unpacking or caching file.

**Comment by bbrodsky** [comment] 2017-06-12 17:19
@viettranx ya, the folder is empty...

**Comment by viettranx** [comment] 2017-06-12 17:25
Just remove third-party folder, it will re-download and unpack with `react-native run-ios` command.

**Comment by bbrodsky** [comment] 2017-06-12 17:37
@viettranx That fixed it for me. Thanks!

**Comment by SBShane** [comment] 2017-06-12 18:15
@viettranx Worked for me too. Annoying, but at least it works now. Thanks!

**Comment by bang88** [comment] 2017-06-13 02:53
clean  xcode project and rerun working for me.

`CMD + SHIFT + K `

**Comment by tianwawawa** [comment] 2017-06-13 05:58
worked for me @shubhnik awesome!!

**Comment by lenmoyouziJiangjun** [comment] 2017-06-13 06:02
0 11.7M    0 16969    0     0      5      0  28d 11h  0:49:36  28d 10h     0
  0 11.7M    0 16969    0     0      5      0  28d 11h  0:49:37  28d 10h     0
  0 11.7M    0 16969    0     0      5      0  28d 11h  0:49:38  28d 10h     0curl: (56) SSLRead() return error -36
curl: Saved to filename 'boost_1_63_0.tar.gz'

**Comment by florismettey** [comment] 2017-06-13 14:18
I had the same issue.
DO NOT use space in project path

**Comment by Easyzhan** [comment] 2017-06-14 02:27
Why no one to solve this problem

**Comment by ganisback** [comment] 2017-06-14 02:30
when i upgrade rn to 0.45.1, this issue disappear for me

**Comment by irrigator** [comment] 2017-06-14 03:47
The problem is when building react-native for iOS, the process tries to download some files (using ```curl```) into ```~/.rncache```. Specifically, they are "boost_1_63_0.tar.gz, double-conversion-1.1.5.tar.gz folly-2016.09.26.00.tar.gz, glog-0.3.4.tar.gz". The sources of them (at least some of them) are from AWS S3,  which aren't accessible in some regions (I'm from China). And that caused the problem.

By using a proxy server and setting the ```http_proxy``` and ```https_proxy``` environment variables, curl will go through the proxy and the build should succeed.

This is not a problem with React Native. This issue can be closed now.

**Comment by henrykapostel** [comment] 2017-06-14 04:30
@irrigator Yeah, I upgraded RN to 0.45.1, but the same issue doesn't disappear. how can I set the `http_proxy ` and `https_proxy ` environment variables. Please let me know the example

**Comment by irrigator** [comment] 2017-06-14 05:25
@henrykapostel https://stackoverflow.com/questions/9445489/linux-curl-command-with-proxy

**Comment by henrykapostel** [comment] 2017-06-14 05:44
Thanks

**Comment by RobIsHere** [comment] 2017-06-14 06:23
Also having this issue. I was on a train when starting react-native run-ios the first time. Maybe the unstable internet connection. And had to search around to find this out. I'm seeing

tar -xf ~/.rncache/glog-0.3.4.tar.gz
glog-0.3.4/ltmain.sh: (Empty error message)
tar: Error exit delayed from previous errors.

when running tar -xf on the file manually.

Either it should be bundled and be downloaded when you expect to happen downloads (npm install postinstallation maybe) or there must be a better error message!

I see this as a bug (missing error reporting or broken UX) that needs fixing.

**Comment by kamyzd** [comment] 2017-06-14 10:12
Maybe you are using Xcode 8.1 , I upgraded Xcode to 8.2.1 which fixed my problem

**Comment by RobIsHere** [comment] 2017-06-14 10:20
I fixed my problem by deleting and downloading the ~/.rncache directory again.
This fixed my problem.

Maybe there are two possible reasons for this issue? Just thinking. Old xcode OR failed download.
Also there are really like 10 or so other issues that sound related (build fails because of sth. missing), all of them opened in the last days.

**Comment by asphalt2018** [comment] 2017-06-15 02:24
I fixed this problem by amending my package.json file.Changing react-native version from 0.45.1 to 0.44.2.

**Comment by PeterEmanuel** [comment] 2017-06-15 06:31
Same here, I also reverted to last commit before upgrading, due to this "double-conversion" issue.

**Comment by tuneZola** [comment] 2017-06-16 15:43
+1

**Comment by robvolk** [comment] 2017-06-17 20:28
1

**Comment by GitterYang** [comment] 2017-06-18 13:35
+1

**Comment by CleoCat** [comment] 2017-06-18 20:06
+1

**Comment by chinaxiaoyy** [comment] 2017-06-19 09:43
me too

**Comment by chinaxiaoyy** [comment] 2017-06-19 09:53
just upgrade react-native version to 0.44.0 then it fixed

**Comment by CaffreySun** [comment] 2017-06-20 03:05
1. run "npm install"
2. clean XCode  CMD + SHIFT + K
3. restart XCode
rerun working for me.

**Comment by strawferry** [comment] 2017-06-20 06:54
+1

**Comment by alvinthen** [comment] 2017-06-22 06:34
Managed to manually solve this by `curl`ing these into ~/.rncache

https://github.com/google/glog/archive/v0.3.4.tar.gz
https://github.com/google/double-conversion/archive/v1.1.5.tar.gz
https://github.com/react-native-community/boost-for-react-native/releases/download/v1.63.0-0/boost_1_63_0.tar.gz
https://github.com/facebook/folly/archive/v2016.09.26.00.tar.gz

**Comment by thainh107** [comment] 2017-06-22 07:00
+1

**Comment by willmcclellan** [comment] 2017-06-22 07:17
I had some luck with the following:

```
rm -r ~/.rncache
rm -r <your-project>/node_modules/react-native/third_party
```

Then clean in Xcode and rebuild. Thanks @viettranx

**Comment by huaidanlk** [comment] 2017-06-22 07:51
@shubhnik thanks

**Comment by CynthiaNC** [comment] 2017-06-22 12:04
react-native init [ProjectName] --version 0.44.0
如
react-native init myFifthApp --version 0.44.0

it solved. Thanks~

**Comment by raunaqss** [comment] 2017-06-22 13:08
Faced the exact same issue for hours. Finally got it working with 0.44.0. Makes me apprehensive about learning React Native. Will it be any good if it keeps breaking?

**Comment by PeterEmanuel** [comment] 2017-06-22 13:14
What puzzles me, is that this seems to be an issue introduced in the build system and that no one from FB has seriously taken part in this issue...
The tips here are tweaks/fixes that work for some, but do not address the real problem that has been introduced in 0.45.
For instance, I do not have spaces in my project path. I have cleared yarn/npm cashes, deleted node_modules, etc. And with my app with only a few linked projects I can simply not use 45 for building it on Mac. So I am happily back with 0.44 (app in TestFlight phase).
Can't any active repo contributor comment on what's going on?

**Comment by SamMatthewsIsACommonName** [comment] 2017-06-22 18:30
It's also very important that the project isn't under any parent folders that have a space in their name. Simple thing but cost me about 8 hours today

**Comment by JessicaBarclay** [comment] 2017-06-23 15:45
Dare I ask... Any solution here? Running 0.44 with the same error 😞

**Comment by cpsubrian** [comment] 2017-06-23 23:16
Fresh 0.45.1 `init` failed with the same error for me . Happy to provide more info if needed.

**Comment by abdulmalik97** [comment] 2017-06-24 20:50
Basically just download the boost file from here [https://sourceforge.net/projects/boost/files/boost/1.63.0/](url) and replace it with the boost file in your dummyproject/node_modules/react-native/thirdparty/ This is a workaround for now so you have to do this every time you create a new react native project . So use it until they fix the root of the problem . **wasted a whole day searching for answers and finally found it!!**

**Comment by vijaysraj** [comment] 2017-06-25 06:34
Thanks @shubhnik. version 0.44.0 worked for me too.

**Comment by huaidanlk** [comment] 2017-06-27 08:35
@JessicaBarclay run your project in Xcode ,tomorrow the version 0.44.0 worked for me,but today,I running with the same error ,so I running project in Xcode ,unbelievable,it running success

**Comment by raunaqss** [comment] 2017-06-27 10:47
Woohoo! 

5 days back I complained on this thread about not being able to get 0.45.1 working. I was just starting to learn React Native then, today, after completing a couple courses/tutorials and making my first app with 0.44.2, **I finally got 0.45.1 working by changing my workspace directory to one with no spaces (sound funny lol) and just did a `yarn install` after running `init`.**.

<img width="1280" alt="screen shot 2017-06-27 at 4 13 56 pm" src="https://user-images.githubusercontent.com/7628888/27584014-10662abc-5b54-11e7-92d1-4e98913d7dff.png">

**Comment by javitxumartinez** [comment] 2017-06-28 10:05
I solved this problem by deleting .rncache folder within the home directory, deleting node modules and then yarn install, and works like a charm.

**Comment by javitxumartinez** [comment] 2017-06-28 10:17
I solved this issue by deleting the rncache folder

**Comment by Msspl-PrashenjeetRoy** [comment] 2017-06-28 13:06
@raunaqss Can you explain this - "changing my workspace directory to one with no spaces (sound funny lol)". I am facing the same issue.

**Comment by Feng999** [comment] 2017-07-02 09:45
Faced the  same issue . And got it working with 0.44.0.  Don't know why.

**Comment by abhishekbansal-kiwi** [comment] 2017-07-02 11:25
@javitxumartinez Though solved the unpacking error for me, now stuck in "Use of undeclared type 'RCTBridge', 'RCTBundelURLProvider' "upgraded from 0.38 to 0.45 to use react native navigation.

**Comment by raunaqss** [comment] 2017-07-03 06:25
@Msspl-PrashenjeetRoy by that I meant not having any whitespace in the project's path.

**Comment by ananddayalan** [comment] 2017-07-04 23:13
Faced the error. Works after renaming the project folder without spaces

**Comment by xilibro** [comment] 2017-07-05 08:41
upgrade Xcode , react, react-native to latest version
delete ~/.rncache folder
run react-native init ProjectName / delete node_module and run npm install for existing project
that's all, but take my whole day time

**Comment by llearn** [comment] 2017-07-08 17:50
+1

**Comment by lupena** [comment] 2017-07-09 20:22
+1
Same problem here! React is not working for me from version 0.44

Tried everything listed above (Including no space in directories).

Upgraded * to the latest version:
Xcode 8.3.3
react-native-cli: 2.0.1
react-native: 0.46.1
OSX Sierra 10.12.5

**Comment by SudoPlz** [comment] 2017-07-10 04:47
Many of you might be able to fix this with https://github.com/facebook/react-native/commit/5c53f89dd86160301feee024bce4ce0c89e8c187

**Comment by reimertz** [comment] 2017-07-10 13:51
Fresh install  `react-native init Hello` breaks
Fresh install  `react-native init Hello --version 0.44.0` works

Since I symlink into my iCloud drive folder, I can confirm whitespace was the issue for me but I also have issues on 0.44 related to react-native-flux-router so I have to manually edit generated bash scrips till this is resorted.

I guess symlinking into my iCloud Drive folder wasn't that cool after all.. :(

**Comment by ofairfoul** [comment] 2017-07-14 11:16
thankyou @SudoPlz 5c53f89 helped me. but why isn't this in 0.46.2 already!?

for all those who are stuck the answer is to add this to your build to manually patch your RN version.
```bash
cd node_modules/react-native/scripts/
curl https://raw.githubusercontent.com/facebook/react-native/5c53f89dd86160301feee024bce4ce0c89e8c187/scripts/ios-configure-glog.sh >ios-configure-glog.sh
chmod +x ios-configure-glog.sh
printf "\nManually upgraded the ios-configure-glog.sh script.\n"
```

**Comment by ofairfoul** [comment] 2017-07-14 11:20
thank you @SudoPlz following instructions in 5c53f89 helped me. but why this commit isn't this in 0.46.2 already?

for all those still facing problems manually patching your RN version during build with the folllowing script helped
```bash
cd node_modules/react-native/scripts/
curl https://raw.githubusercontent.com/facebook/react-native/5c53f89dd86160301feee024bce4ce0c89e8c187/scripts/ios-configure-glog.sh >ios-configure-glog.sh
chmod +x ios-configure-glog.sh
printf "\nManually upgraded the ios-configure-glog.sh script.\n"
```

**Comment by yonerocha** [comment] 2017-07-17 11:34
@ofairfoul I was in  0.46.3 and I had same mistake. 

The temporal solution: npm install react-native@0.44.0

**Comment by kimown** [comment] 2017-07-20 10:15
```
Unpacking /Users/XXX/.rncache/double-conversion-1.1.5.tar.gz...

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

100   609    0   609    0     0    104      0 --:--:--  0:00:05 --:--:--   157

ØÅØ  
```

then the process hang

**Comment by ashemah** [comment] 2017-07-21 10:11
Hi all, I just ran into this issue as well. As noted above, the root cause is due to some of the files (in my case boost) not downloading to the cache properly.

The easiest way to fix this is:

1. Make sure your project path does not include spaces (this was the issue for some people)
2. Ensure you are properly connected to the internet
3. Delete the ~/.rncache directory
4. Re-run 'react-native run-ios' (This will re-download the previously broken files to the .rncache dir)

That fixed it for me. You need to delete the .rncache dir or it will keep reusing the broken files and not compile. This definitely needs better error handling and to preferably terminate the build if it cannot download those files properly (although perhaps it didn't because I ran the build in xcode originally rather than with run-ios).

Note: This happened for me even on 0.46.4 which some people said was fixed.

**Comment by baurine** [comment] 2017-07-24 01:15
wow, it is funny! I clone a repo, then use `npm install`, `react-native run-ios` to run it, got the same error about `double-conversion.build/Script-190EE32F1E6A43DE00A8543A.sh`, I tried above kinds of solutions, it still doesn't work.

then, I just suddenly thought, why not try `yarn install` instead of `npm install`, wow, surprise, it finally works! I want to cry, wasted me half day.

**Comment by zx3570** [comment] 2017-07-28 05:48
![jietu20170728-132148](https://user-images.githubusercontent.com/20938747/28704111-0dab0554-739b-11e7-9643-888690a41b06.jpg)


same problem!Then, I want to change react-native version.But,I met another problem :


![jietu20170728-134225](https://user-images.githubusercontent.com/20938747/28704043-acedc698-739a-11e7-9258-99be128fc766.jpg)


Refusing to install package with name "react-native" under a package also called "react-native".

How to fix it?

**Comment by liukaixin01** [comment] 2017-07-30 05:34
+1

**Comment by ThienMD** [comment] 2017-07-31 02:54
Tks @viettranx

**Comment by jjerryhan** [comment] 2017-08-01 16:28
This article would be helpful :  [Handling third party build error on react-native 0.46x](https://medium.com/@jjerryhan/handling-third-party-build-error-on-react-native-0-46x-445f867e7a2b)

**Comment by hramos** [comment] 2017-08-03 17:33
Duplicate of #14447

**Closed by hramos** 2017-08-03 17:33 UTC

**Comment by hramos** [comment] 2017-08-03 17:58
Duplicate of #14423
