### ISSUE TITLE
DatePickerAndroid.open({mode: 'spinner'}) doesn't work

### ISSUE THREAD

**Issue by henriqamaral** [facebook/react-native#12495] opened 2017-02-21 12:02 UTC
### Description

Try to use DatePickerAndroid.open({mode: 'spinner'}), but always show the default calendar

### Reproduction

DatePickerAndroid.open({mode: 'spinner'})

### Additional Information

* React Native version: 0.41
* Platform: Android 7.0
* Operating System:  MacOS

**Comment by hramos** [comment] 2017-02-21 21:32
Can you elaborate?

**Comment by henriqamaral** [comment] 2017-02-21 22:13
Hi,
When I try to use DatePickerAndroid.open({mode: 'spinner'}) , I should be able to select the date  using year, month, and day spinner, but always show the default calendar, where show the days of the month.
Here the documentation how it should be work:
[https://facebook.github.io/react-native/docs/datepickerandroid.html]

**Comment by hramos** [comment] 2017-02-22 17:24
Gotcha, that seems like it is not working as expected. Thanks for reporting this. If you get a chance to look into what's causing it, feel free to send a PR.

**Comment by kapilratnani** [comment] 2017-03-09 12:59
Spinner mode is not having any affect in Android N while it works before that.
May it is this issue https://code.google.com/p/android/issues/detail?id=222808

**Comment by hramos** [comment] 2017-03-09 14:48
Thank you @kapilratnani that does look like it could be the cause. It's a bug in 7.0 that is fixed in Nougat 7.1. @henriqamaral please take a look at the suggested workaround in that thread.

**Closed by hramos** 2017-03-09 14:48 UTC

**Comment by kapilratnani** [comment] 2017-03-09 15:49
Any way to inject the workaround to react-native DatePickerAndroid module ?

**Comment by cfs5403** [comment] 2017-06-05 07:52
I see at stake overflow there is a hack to fix the spinner mode not work in android 7.0, check the answer by savanto. I tested it and it 100% work on android 7.0 devices, anyone can help make changes to the react native code based on his answer. This must be fixed as many android 7.0 user out there, they are complaining about the date picker for birthdate. Thanks.

https://stackoverflow.com/questions/39873076/datepickerdialog-holo-styling-failed-on-android-7-nougat

**Comment by kapilratnani** [comment] 2017-06-10 01:39
I copied the code from react and created a Native Module for my project. I think it should be fixed in react.

**Comment by EsdrasEtrenne** [comment] 2017-10-28 05:37
yes please!

**Comment by EsdrasEtrenne** [comment] 2017-11-29 23:25
@hramos can we look into this as a react fix?
