### ISSUE TITLE
Issue with pulling bundles from a remote server. Seeing `_fbBatchedBridge is undefined`

### ISSUE THREAD

**Issue by pvenkatakrishnan** [facebook/react-native#5863] opened 2016-02-10 21:09 UTC
Doing a react-native integration into an existing ios app.
I have a native ios app which pulls in the ios bundle from a remote server.
I followed the instructions on the react-native site and i am able to install pod dependencies within React and startup the ios app in a simulator.

When i navigate to the view that loads the react-native provided view, the code looks something like
```
   NSString *urlString = @"https://<some_url_here>/main.jsbundle"; //a remotely hosted bundle.
   NSURL *jsCodeLocation = [NSURL URLWithString:urlString];
   RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                 moduleName: @"react-native-app"
                                                 initialProperties: nil
                                                     launchOptions:nil];
```

when i directly hit the `https://<some_url_here>/main.jsbundle` i do see the bundle get downloded, so i do know that that url does serve the bundle.

The problem i am seeing is when i try to load the view, i see a red screen with
`_fbBatchedBridge is undefined`.
When i searched on the web for this issue, seems like the most common times this issue happened is when someone tries to pull the bundle from dev server but it is not running. For me, thats not the case as the bundle is hosted remotely.

Any ideas as to what could be going wrong ?

**Comment by pvenkatakrishnan** [comment] 2016-02-11 19:12
Here is some additional info from the stack trace

line: 5537\n message: undefined is not an object (evaluating \'Object.keys(moduleConfig.methods)\')', { [TypeError: undefined is not an object (evaluating 'Object.keys(moduleConfig.methods)')]
  line: 5537,
  column: 28,
  sourceURL: 'http://<myserver>/ios/mainjsbundle' }

and yes i have already added to my .plist file

```
<key>NSAppTransportSecurity</key>
    <dict>
        <key>NSAllowsArbitraryLoads</key><true/>
    </dict>
```

**Comment by jsierles** [comment] 2016-04-10 18:32
@pvenkatakrishnan is the module name correct? It should be the name your set in AppRegistry for the top level component.

Otherwise, could you provide a link to the bundle?

**Comment by pvenkatakrishnan** [comment] 2016-04-10 23:53
Yes I made sure it is the same name as in the AppRegistry. What i noticed is there seems to be a difference between using `http` and `https`. When i tried the same bundle hosted on a `http` site, it downloaded fine. But when i moved it to `https` it failed. For the time being, i started hosting it in a `http` url with in `.plist` following added.

```
<key>NSAppTransportSecurity</key>
    <dict>
        <key>NSAllowsArbitraryLoads</key><true/>
    </dict>
</key>
```

**Comment by lacker** [comment] 2016-10-21 00:03
Since there's a workaround here, I'm going to close this issue. Feel free to reopen it if you think there's an underlying bug that should be fixed here & there is some info to help reproduce it.

**Closed by lacker** 2016-10-21 00:03 UTC
