### ISSUE TITLE
pod install  - `React/Core (from `../node_modules/react-native`)` required by `Podfile`

### ISSUE THREAD

**Issue by sh377056544** [facebook/react-native#13021] opened 2017-03-20 03:31 UTC
when i run `pod install'
[!] Unable to satisfy the following requirements:

- `React/Core (from `../node_modules/react-native`)` required by `Podfile`

It seems like you've changed the constraints of dependency `React/Core` inside your development pod `React/Core`.
You should run `pod update React/Core` to apply changes you've made.

when i run  `pod update React/Core`
[!] No `Podfile.lock' found in the project directory, run `pod install'.

**Comment by hramos** [comment] 2017-03-20 16:32
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-03-20 16:32 UTC

**Comment by ggsrivas** [comment] 2017-09-07 23:34
I am facing same issue. I just upgraded RN version from 0.30 to 0.48 and when I run pod install in my hybrid app, I am getting exactly same error as posted by sh377*

**Comment by ggsrivas** [comment] 2017-09-07 23:35
@sh377056544  did you find a solution?
