### ISSUE TITLE
import syntax throws when importing socket.io if debugger is not attached

### ISSUE THREAD

**Issue by adamterlson** [facebook/react-native#4393] opened 2015-11-27 21:14 UTC
I don't know how to even begin with this one, but I'm including Socket.IO into a project spawned from react-native init.  The import of the SocketIO library bombs, but only when the debugger is not attached.  I can use the require syntax instead and then that works no matter what.

Always works:
`let io = require('socket.io-client/socket.io');`

Fails with Chrome Debugging disabled but works otherwise:
`import io from 'socket.io-client/socket.io';`

Here's the error for whatever good it is: "undefined is not an object (evaluating navigator.userAgent.match)"
![image](https://cloud.githubusercontent.com/assets/2498418/11448083/d178c478-9551-11e5-960f-d5aec91806de.png)

**Comment by ide** [comment] 2015-11-27 22:58
Socket.io likely needs to write a React Native version of their library. It looks like you're trying to run a browser version of their code.

**Comment by christopherdro** [comment] 2015-11-27 23:20
@adamterlson  I can confirm that i've used socket.io with react native and had no issues.

The only caveat that I ran into earlier was that `userAgent` was undefined.
I managed a temporary work around by adding  `window.navigator.userAgent = "react-native";`

Here is an article by @browniefed that might help.
http://browniefed.com/blog/2015/05/16/react-native-and-socket-dot-io/

In the past i've worked with https://www.npmjs.com/package/react-native-swift-socketio and it worked fine as well.

Hope this helps!

**Comment by adamterlson** [comment] 2015-11-27 23:41
@christopherdo Well Socket IO works fine*, but that's not really the issue.  The question is why there's inconsistent behavior from RN depending on the type of import and whether a debugger is attached.  Does that not seem strange?

* I'm actually having an issue where RN is picking up SocketIO events emitted via `socket.emit`, but not  `socket.broadcast.emit`.  So it's ignoring the global events.  Have you experienced this, or have you specifically tried RN + SocketIO and global events?

Thanks for the help!

**Comment by satya164** [comment] 2015-11-28 00:53
@adamterlson As far as I understand, all imports are hoisted to the top, while requires are not. Hence, the reason it's not working with `import` syntax is `socket.io` is being required even before `window.navigator.userAgent = "react-native"` is called, and throws error.

Feel free to close the issue if this answers your question.

**Comment by adamterlson** [comment] 2015-11-28 10:08
@satya164 Good enough for me, thanks for the explanation!

**Comment by adamterlson** [comment] 2015-11-28 11:51
@satya164 @christopherdro Have you also experienced an issue with Socket IO not working unless the chrome debugger is attached?

**Comment by satya164** [comment] 2015-11-28 11:54
@adamterlson Nope. I needed to 2 things, set the user agent, and disable jsonp.

**Comment by adamterlson** [comment] 2015-11-28 11:56
What version of RN did you use?  Do you have a project up somewhere I can clone perhaps?

**Comment by satya164** [comment] 2015-11-28 12:04
@adamterlson I am actually using engine.io atm. But I had tested with socket.io previously. RN version shouldn't matter, because the WebSocket module hasn't changed.

Also it's weird that it would only work with Chrome debugger. In both cases it uses the Androide module.

BTW what's the error you're getting?

**Comment by adamterlson** [comment] 2015-11-28 12:10
So I did a fresh init and plugged socket IO in and now I have two projects running.  My first project is where SocketIO only works when the Chrome Debugger is attached, and now this new one, it doesn't seem to connect in general and if the chrome debugger is attached it throws the exception also referenced here: 

http://browniefed.com/blog/2015/05/16/react-native-and-socket-dot-io/

I'm just all tangled up at this point. :)

You can see my socketio code here as well as the entire project:
https://github.com/adamterlson/react-native-messenger/blob/master/app/socket.js

Without the chrome debugger attached I don't actually see any errors, it just doesn't connect.  Hard to tell more without a debugger. :)

**Comment by satya164** [comment] 2015-11-28 12:43
@adamterlson It didn't work for me without disabling JSONP. Have you tried that?

io("...", { jsonp: false })

**Comment by satya164** [comment] 2015-11-28 12:43
I'll have a proper look later tonight.

**Comment by adamterlson** [comment] 2015-11-28 12:47
Yup, I have tried the jsonp thing.  Sorry it's excluded from the pushed version.  I'll update.

**Comment by adamterlson** [comment] 2015-12-04 21:21
@satya164 Any insights by chance?

**Comment by satya164** [comment] 2015-12-05 05:26
Sorry, didn't get a chance to have a look. Will do ASAP.

**Comment by adamterlson** [comment] 2016-01-07 10:45
@satya164 I'm still interested by the way, if you might find the time! :)

**Comment by chezhe** [comment] 2016-02-14 13:23
@adamterlson I got the same error with socket.io.
It works fine while 'Debug in Chrome' running on a simulator is set .It fails while 'Disable Debug in Chrome' running on a simulator and running on a device.
I guess, that's because 'Debug in Chrome' mode,JS code runs inside Chrome and Chrome supports socket.io.
BTW, have you got a solution?

**Comment by adamterlson** [comment] 2016-02-14 17:58
Seems like a good explanation. 

No, no fix. It seems like an open issue to me. I'll reopen and hopefully someone has some guidance!

**Comment by browniefed** [comment] 2016-02-14 18:01
This isn't really an issue with react native but more of an issue with socket.io
Go submit a PR to socket.io to handle no `userAgent` existing and this won't be an issue.

**Comment by adamterlson** [comment] 2016-02-14 18:05
The issue is with the inconsistent behavior based on debugger attachment.  Can you be more specific as to how the user agent is related?

**Comment by browniefed** [comment] 2016-02-14 18:12
Has the error message changed from the one you originally reported complaining about `navigator.userAgent.match` being undefined?
Socket.io looks for the existence of  `window.navigator.userAgent`. Both react-native and the chrome debugger which runs RN in a webworker do not have access to the such things.

**Comment by adamterlson** [comment] 2016-02-14 18:37
@browniefed Thank you for the details. In some sense the actual issue is in fact not simply the error you've described and the screenshot I posted.  It's more the inconsistency of behavior. As described in the thread and also experienced by @chezhe, if the debugger is attached things work fine. 

> Both react-native and the chrome debugger which runs RN in a webworker do not have access to the such things. 

If this were the case, would it not be that socket io would not work at all, ever, rather than based on whether the debugger us attached or not? 

I found a comment you made on [this blog post](http://browniefed.com/blog/2015/05/16/react-native-and-socket-dot-io/) a while back which states that socket io will **not** work with the debugger open. This issue describes behavior where it **only** works with it open. Do you know what has changed?

**Comment by browniefed** [comment] 2016-02-14 18:43
Lots of moving parts in RN, not sure exactly what is causing such things to happen.

What I can say, is if you are getting the `userAgent` error then that's a socket.io issue. Additionally babel hoisting imports vs requires can also surface as the `userAgent` issue.

I'm not saying RN is perfect with websockets and debugging but it seems to be external library issues failing and not necessarily react native.

Going forward, what errors are thrown when running on the device? I haven't seen those posted yet.

**Comment by adamterlson** [comment] 2016-02-14 18:49
I haven't done device testing on my end yet. @chezhe Can you post a screenshot?  Though it was stated he got the "Same error" in both so I assume the whole user agent match thing. 

@browniefed Thank you again. I appreciate the discussion!

**Comment by deyoppe** [comment] 2016-02-16 12:54
Have you tried by adding `ws://` in front of the url? I had the same problem: while debugging with Chrome it worked, when testing on the device it would just keep throwing `reconnect_error` with description "0". I changed the url from `127.0.0.1:8080` to `ws://127.0.0.1:8080` and it was enough to fix it.
It's probably a bug with the reimplementation of WebSockets, I don't know why it should be explicit.

**Comment by chezhe** [comment] 2016-02-17 03:23
@deyoppe now,yes.
I found this solution 2 days before, when I tried wss:// type.

**Comment by chezhe** [comment] 2016-05-02 15:24
@deyoppe 
I found it does not work again after upgrade RN 0.24.0 , same code. Have you met the same problem after upgrade?

**Comment by Mokto** [comment] 2016-05-12 15:44
Also does not work with 0.25.1.

**Comment by chezhe** [comment] 2016-05-13 03:26
@Mokto Try this:

```
const io = socket(SOCKET_IP,{
  jsonp: false,
  transports: ['websocket']
})
```

**Comment by alexduckmanton** [comment] 2016-05-13 07:02
That worked for me. Thanks a bunch, @chezhe!

**Comment by Mokto** [comment] 2016-05-13 14:23
Thanks that works perfectly !

**Comment by kyaroru** [comment] 2016-08-15 02:11
@chezhe thanks so much, it works like a charm ! I've been looking for solution and no hope until i saw this xD

**Comment by sibelius** [comment] 2016-10-09 02:30
@satya164 I think u can close this issue

**Comment by browniefed** [comment] 2016-10-09 03:27
@facebook-github-bot answered

**Closed** 2016-10-09 03:28 UTC
Labels: Ran Commands

**Comment by EvNaverniouk** [comment] 2016-10-22 21:41
I am still having this issue. Using

```
"react-native": "0.35.0",
"socket.io-client": "1.5.0"
```

Using code:

```
import socket from 'socket.io-client/socket.io';

this._socket = new socket(BASE_URL, {
	jsonp: false,
	transports: ['websocket']
});
```

However, if I do **NOT** enable "Rebug JS Remotely" I get:

![2016-10-22 21 40 07](https://cloud.githubusercontent.com/assets/226640/19622728/8615dff8-9865-11e6-9092-4066c8daabae.png)

I have to enable remote debugging to get the error to go away. Am I missing something?

**Comment by tarkanlar** [comment] 2016-11-29 19:13
@EvNaverniouk I am having the same issue RN 0.37.0 could you find any work around?

**Comment by chezhe** [comment] 2016-12-01 03:38
@tarkanlar 
```
//you miss this part, define the environment socket.io works
//if not work, try put the following line into another file and import it
window.navigator.userAgent = "react-native";

const io = socket(SOCKET_IP,{
  jsonp: false,
  transports: ['websocket']
})
```

**Comment by luco** [comment] 2017-02-01 10:17
@chezhe **HUGE** thanks! Been looking for this in the past hours.

**Comment by lucasmaciel** [comment] 2017-03-25 01:46
I have this issue too. My code:

```
import React from 'react-native';
import './UserAgent'; // window.navigator.userAgent = "react-native";

//import io from 'socket.io-client/dist/socket.io'; (I tried this also)
const io = require('socket.io-client/dist/socket.io');

exports.createConnection = function(host, port, options) {
    console.log(window.navigator.userAgent);
    var stream = io(host+':3000', {
        jsonp: false,
        reconnection: true,
        reconnectionAttempts: 32,
        reconnectionDelay: 50,
        reconnectionDelayMax: 30000,
        timeout: 2000
    });
    return stream;
};
```

And only connects if I'm in debugging mode.  The console log, when I'm in debugging mode, outputs `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36` for `window.navigator.userAgent`, even rewriting it on `UserAgent.js` file. I don't know why. The modules version:
react-native: 0.32
socket.io-client: 1.7.3
socket.io: 1.7.3 

PS: Someone knows if there is an alternative of socket.io for react native ?

**Comment by joaqtor** [comment] 2017-08-05 01:12
Hey @lucasmaciel I'm experiencing the same problem.

Did you find any fix for this?

**Comment by lucasmaciel** [comment] 2017-08-05 18:06
The code that works:
`import React from 'react-native';
import './UserAgent';

import io from 'socket.io-client/socket.io';

exports.createConnection = function(host, port, options) {
    var stream = io('ws://'+host+':'+port, {
        jsonp: false,
        reconnection: true,
        reconnectionAttempts: 32,
        reconnectionDelay: 50,
        reconnectionDelayMax: 30000,
        timeout: 2000,
        transports: ['websocket']
    });
    return stream;
}
`

you have to write "ws://" instead of "http://". And add "transports: ['websocket']". It should works.

**Comment by joaqtor** [comment] 2017-08-08 23:14
Still can't make it to work 😭 

I'm using 1.7.3 too in both client and server.
React Native version 0.46.4.

**Comment by chezhe** [comment] 2017-08-09 03:13
@joaqtor you can check my code
[https://github.com/loafs/Agora/tree/master/store](https://github.com/loafs/Agora/tree/master/store)
