### ISSUE TITLE
Inconsistent text wrap / multiline behavior in TextInput between iOS and Android

### ISSUE THREAD

**Issue by maxdeepfield** [facebook/react-native#31170] opened 2021-03-16 11:08 UTC
## Description
If change text of TextInput in iOS it remains in single-line not wrapped.
If change text of TextInput in Android it becomes multi-line wrapped.

## React Native version:
0.64.0

## Steps To Reproduce
1. make TextInput with fixed width and text long enough to hide its ending
2. change value of TextInput

## Expected Results
Text should be updated in TextInput without changing its line count or wrap property.

## Actual (bug) results
Text updated in Android but it becomes multi-line and wrapped.

## Snack, code example, screenshot, or link to a repository:
Snack: https://snack.expo.io/@maxdeepfield/multiline-placeholder-problem

Before change value of TextInput 
![image](https://user-images.githubusercontent.com/1029366/111299265-6a15f500-8658-11eb-87af-1e852135426c.png)

After change value of TextInput 
![image](https://user-images.githubusercontent.com/1029366/111299310-7437f380-8658-11eb-854f-8b1cb388af6e.png)

## Notes

VERY related to https://github.com/facebook/react-native/issues/14845
Seems a lot of unresolved bugs of *react-native* are just closed but not fixed.
Let try again then.

**Comment by chrisglein** [comment] 2021-03-16 18:21
Duplicate of #30666?

**Comment by chrisglein** [comment] 2021-03-16 18:25
Main difference is that you're not explicitly setting the number of lines, but other than that I think it looks likely to be the same core issue. Going to close this as a dupe of the other, feel free to add more commentary in that one. The guess from that thread is that updating the Android Studio version will address this.

**Closed by chrisglein** 2021-03-16 18:25 UTC
Labels: Component: TextInput, Needs: Triage :mag:

**Comment by maxdeepfield** [comment] 2021-03-16 18:49
Its very similar if under hood there happens placeholder update after setting TextInput's value to empty string.
