### ISSUE TITLE
The module `./../react-transform-hmr/lib/index.js` could not be found

### ISSUE THREAD

**Issue by annpt1** [facebook/react-native#21508] opened 2018-10-05 08:13 UTC
`
> Failed to load bundle(http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false) with error:(Unable to resolve module `./../react-transform-hmr/lib/index.js` from `/Users/xxxx/Projects/helloworld/App.js`: The module `./../react-transform-hmr/lib/index.js` could not be found from `/Users/xxxx/Projects/helloworld/App.js`. Indeed, none of these files exist:
>   * `/Users/xxxx/Projects/react-transform-hmr/lib/index.js(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
>   * `/Users/xxxx/Projects/react-transform-hmr/lib/index.js/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)` (null))
> 
> __38-[RCTCxxBridge loadSource:onProgress:]_block_invoke.248
>     RCTCxxBridge.mm:429
> ___ZL36attemptAsynchronousLoadOfBundleAtURLP5NSURLU13block_pointerFvP18RCTLoadingProgressEU13block_pointerFvP7NSErrorP9RCTSourceE_block_invoke.118
> __80-[RCTMultipartDataTask URLSession:streamTask:didBecomeInputStream:outputStream:]_block_invoke
> -[RCTMultipartStreamReader emitChunk:headers:callback:done:]
> -[RCTMultipartStreamReader readAllPartsWithCompletionCallback:progressCallback:]
> -[RCTMultipartDataTask URLSession:streamTask:didBecomeInputStream:outputStream:]
> __88-[NSURLSession delegate_streamTask:didBecomeInputStream:outputStream:completionHandler:]_block_invoke
> __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
> -[NSBlockOperation main]
> -[__NSOperationInternal _start:]
> __NSOQSchedule_f
> _dispatch_call_block_and_release
> _dispatch_client_callout
> _dispatch_continuation_pop
> _dispatch_async_redirect_invoke
> _dispatch_root_queue_drain
> _dispatch_worker_thread2
> _pthread_wqthread
> start_wqthread
`
## Environment
` React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
      Memory: 35.45 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.11.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.2 => 0.57.2 
    npmGlobalPackages:
      react-native-cli: 2.0.1
`
## Description
I init a new project and use "run-ios" and face this problem
## Reproducible Demo
1. react-native init project
2. react-native run-ios

**Comment by kelset** [comment] 2018-10-05 08:15
Duplicate of https://github.com/facebook/react-native/issues/21490

**Closed by kelset** 2018-10-05 08:15 UTC
