### ISSUE TITLE
Android can't display image large width 

### ISSUE THREAD

**Issue by pvsong** [facebook/react-native#12437] opened 2017-02-17 14:02 UTC
Hi, 
I have an image with size large width=5,000px, height=1,000px, 1.5Mb JPEG and it can't display on android. 
Thanks!

**Comment by hramos** [comment] 2017-02-17 19:54
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-02-17 19:54 UTC
