### ISSUE TITLE
onLongPress prop not working under TouchableHighlight, TouchableNativeFeedback [android]

### ISSUE THREAD

**Issue by saifali96** [facebook/react-native#24220] opened 2019-03-31 03:23 UTC
## 🐛 Bug Report

`onLongPress` prop not working under `TouchableHighlight` or `TouchableNativeFeedback` with Android.

## To Reproduce
The code under [here](https://facebook.github.io/react-native/docs/handling-touches) is enough to reproduce it.

## Expected Behavior
Should display an alert message saying "You long-pressed the button" if you press the button long enough.

## Code Example
Code example has been and can be taken from official ReactNative docs under [this](https://facebook.github.io/react-native/docs/handling-touches) link specifically.
## Environment
``` info
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
      Memory: 8.06 GB / 15.93 GB
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842 ```

**Comment by rickhanlonii** [comment] 2019-03-31 18:49
Thanks for filing @saifali96! This is a dupe of https://github.com/facebook/react-native/issues/24001 and we're actively investigating

**Closed by rickhanlonii** 2019-03-31 18:49 UTC
Labels: Component: TouchableHighlight, Component: TouchableNativeFeedback, Platform: Android, Type: Bug Report
