### ISSUE TITLE
SyntaxError: Left hand side of operator '=' must be a reference.

### ISSUE THREAD

**Issue by madwed** [facebook/react-native#5165] opened 2016-01-06 21:38 UTC
Im running into `SyntaxError: Left hand side of operator '=' must be a reference.` when I initialize a new 0.17 project.  In the Android avd emulator it specifies `(line 2928 in the generated bundle)` which is:

```
this._debugInfo[this._callbackID>>5]=null;
```

In the iOS emulator the error looks like:

![simulator screen shot jan 6 2016 4 37 52 pm](https://cloud.githubusercontent.com/assets/11039058/12155573/e6fb389c-b493-11e5-8993-75b10b04477c.png)

I've tried uninstalling `node_modules`, restarting the packager, but no luck.

**Comment by awaidmann** [comment] 2016-01-06 22:04
I am seeing the same issue for both a newly initialized project as well as for an existing (and working) project. In this case the [Movie List Tutorial](https://facebook.github.io/react-native/docs/tutorial.html#content). Like @madwed I was using [v0.17.0](https://github.com/facebook/react-native/releases/tag/v0.17.0). I noticed there was a new react-native build released earlier today so I installed [v0.18.0-rc](https://github.com/facebook/react-native/releases/tag/v0.18.0-rc) in case there were inconsistencies with other react-native services. I was sure to run:

     react-native upgrade

on both projects. There was nothing to upgrade on the newly init'ed project, but the schema was upgraded for the existing project.

    conflict ios/HelloWorld.xcodeproj/xcshareddata/xcschemes/HelloWorld.xcscheme
    ? Overwrite ios/HelloWorld.xcodeproj/xcshareddata/xcschemes/HelloWorld.xcscheme? overwrite
        force ios/HelloWorld.xcodeproj/xcshareddata/xcschemes/HelloWorld.xcscheme

This did not fix my issue. I am running a stock Nexus 5 emulator with Marshmallow and an iPhone 5s emulator. I will try to push to a device to see if the problem is isolated to emulators. 

I hope this is a temporary issue with the new release because it seems to cripple the whole dev environment.

**Comment by cwramsey** [comment] 2016-01-06 22:09
I'm getting the same issue. I haven't changed a thing in the project after running `react-native init`.

I don't have more information to add than @awaidmann, but this is immediately after installing everything. So everything I have is the latest version in the install process.

**Comment by JakeRawr** [comment] 2016-01-06 22:14
I'm getting the same issue. I had react-native 0.16 and it worked fine. 

I deleted the node_module and `npm install` again (still 0.16)

now i get the `SyntaxError: Left hand side of operator '=' must be a reference.`

**Comment by sampurcell93** [comment] 2016-01-06 22:27
+1

**Comment by awaidmann** [comment] 2016-01-06 22:27
Update:
I am able to run the existing app on my HTC One (Android: 5.0.2, HTC Sense: 6.0), but for some reason the newly init'ed project is still having issues. I am now getting the error log:
![screenshot_2016-01-06-14-23-36](https://cloud.githubusercontent.com/assets/16245422/12156712/859908a2-b481-11e5-971d-52aa8d6569b0.png)

I assume the two issues are related, but I am not familiar enough with react-native to know how or why.

**Comment by aflanagan** [comment] 2016-01-06 22:41
Was just helping an engineer on my team get our react-native project set up, and he's running into the same issue. I upgraded to 0.17 yesterday and did not run into any trouble.

**Comment by sampurcell93** [comment] 2016-01-06 23:01
+ 1 on this. Running android 0.17. An [open source project](https://github.com/alinz/example-react-native-redux) that compiled and ran cleanly yesterday does not work all of a sudden.

**Comment by ide** [comment] 2016-01-06 23:03
Since this issue is just popping up now, I wonder if something changed with Babel upstream...

**Comment by ben-manes** [comment] 2016-01-06 23:03
I think this is due to a new babel release (6.4.0) which has breaking changes

**Comment by sneuberger** [comment] 2016-01-06 23:13
I think this is the upstream bug: https://phabricator.babeljs.io/T6926

**Comment by ide** [comment] 2016-01-06 23:14
@sneuberger thanks for digging that up.

**Comment by jmrodriguez-medallia** [comment] 2016-01-07 00:35
Same here, tried 0.17 and 0.18.0-rc but result is the same.

**Comment by ide** [comment] 2016-01-07 00:36
Babel just published a hotfix -- skevy is testing to see if it resolves the RN issue.

**Comment by skevy** [comment] 2016-01-07 00:36
Hey y'all - can you all try again? Just re-npm install. It should pull the latest version of 6.4.1

**Comment by skevy** [comment] 2016-01-07 00:37
(You'll probably need to delete `node_modules`, just to be safe)

**Comment by ben-manes** [comment] 2016-01-07 00:44
works for me, thanks!

**Comment by ide** [comment] 2016-01-07 00:45
Awesome, thanks for the confirmation @skevy & @ben-manes. Going to be optimistic here and am closing this out.

**Comment by steakchaser** [comment] 2016-01-07 00:52
FYI - Not getting the `6.4.1` when I blow away `node_modules` and re `npm install`.  Still pulling `babel-core@6.4.0`

**Comment by ide** [comment] 2016-01-07 00:54
@steakchaser that's weird, but could you try running `npm cache clean`?

**Comment by jasonmerino** [comment] 2016-01-07 00:54
Yeah, when I follow those steps I'm still getting `6.4.0`. When I run `npm info babel-core` the last entry in the versions array says `6.4.0`, and not `6.4.1` like I would expect. `npm cache clean` doesn't fix it for me either.

**Comment by mcrumm** [comment] 2016-01-07 00:56
@steakchaser @jasonmerino Check the versions for `babel-generator` and `babel-types`. My latest `npm install` run gave me `6.4.1` for those two packages, and my errors went away.

**Comment by ide** [comment] 2016-01-07 00:59
Any chance you're using an npm mirror that's experience replication lag?

**Comment by mwiley** [comment] 2016-01-07 01:00
I tried removing node_modules and running 'npm cache clean' a couple of times now. It's still pulling 6.4.0 and I'm getting the same error as well.

**Comment by jasonmerino** [comment] 2016-01-07 01:01
@mcrumm I don't have any `babel-generator` (I'm assuming this should be in `MyApp/node_modules/react-native/node_modules`?).

`babel-types` on the other hand looks to be good. Set to `6.4.1`.

@ide no mirror. Standard npm registry.

**Comment by Proyoyo** [comment] 2016-01-07 01:02
Same here. I re-npm install and run 'npm cache clean' but I still got the same error.

**Comment by jmrodriguez-medallia** [comment] 2016-01-07 01:05
In my case it worked by:
1. `npm cache clean`
2. `rm -rf node_modules`
3. `npm install `
4. Product > Clean
5. Product > Run

**Comment by steakchaser** [comment] 2016-01-07 01:11
`babel-generator` and `babel-types` are both `6.4.1`.  Also ran `npm cache clean`.  Same error.

**Comment by ide** [comment] 2016-01-07 01:14
I'm thinking the packager has some stale state lying around. A couple things you could try:

- Clear the packager cache: `rm -fr $TMPDIR/react-*`
- Make sure you're restarting the packager so that it uses the new version of Babel

**Comment by skevy** [comment] 2016-01-07 01:19
also do `watchman watch-del-all`

**Comment by steakchaser** [comment] 2016-01-07 01:24
`rm -fr $TMPDIR/react-*` did it for me.  Thanks @ide

**Comment by skevy** [comment] 2016-01-07 01:25
FYI to all, you can also run the packager with the "--reset-cache" flag (rather than `rm -rf $TMPDIR/react-*`)

**Comment by mwiley** [comment] 2016-01-07 01:31
`rm -fr $TMPDIR/react-*` worked for me.

**Comment by tkfeng** [comment] 2016-01-07 02:00
In my case it worked by:
1. npm cache clean
2. rm -rf node_modules
3. npm install
4. rm -fr $TMPDIR/react-*
5. Product > Clean
6. Product > Run

Note that it failed when I skipped step 4.  Thanks everyone!

**Comment by satya164** [comment] 2016-01-07 06:27
Closing since this seems to be fixed.

**Closed by satya164** 2016-01-07 06:27 UTC

**Comment by rclai** [comment] 2016-01-07 15:24
Um guys is this for 0.17.0 or 0.18.0-rc?

**Comment by skevy** [comment] 2016-01-07 15:45
@rclai it actually wasn't a react native bug specifically -- it was related to babel. Babel has released a hotfix (6.4.1) that fixes this issue.

**Comment by rclai** [comment] 2016-01-07 15:48
I did the above steps plus clearing the packager cache and I'm still on 6.4.0?

**Comment by rclai** [comment] 2016-01-07 15:54
Hm, actually, it seems like 6.4.1 doesn't actually exist and they put the hotfix on 6.4.0?
