### ISSUE TITLE
[Android] Touches are not working on transformed views

### ISSUE THREAD

**Issue by PhilippKrone** [facebook/react-native#3812] opened 2015-10-31 20:03 UTC
Hi,

I'm using react-native-invertible-scroll-view and figured out a bug on Android which is as follows: If you have an element at the end of the inverted scrollview, you need to press at the top of the scrollview to actually touch the element. This seems to be as the hit box of the view is not transformed where as the view is. 

Example: I need to press at the very top of the screen to actually trigger a touch event of the image at the very bottom:

![bildschirmfoto 2015-10-31 um 21 01 51](https://cloud.githubusercontent.com/assets/11861008/10865651/badc4c48-8012-11e5-8980-99f3ae7dabbe.png)

@ide: perhaps you can give some more details converning the internals of react-native-invertible-scroll-view?

@mkonicek @andreicoman11 I've seen your names on the blame of https://github.com/facebook/react-native/blob/f01272b031e81850dfdeae04c58ca8ec2b2c5eeb/ReactAndroid/src/main/java/com/facebook/react/uimanager/TouchTargetHelper.java which I was debugging during the last hour without luck though. Perhaps you can gimme a hint as to where to fix this bug?

Thanks!
Philipp

**Comment by satya164** [comment] 2015-10-31 20:15
I'm using transforms on Android too, and touches seem to be working fine. I'm still on 0.12 though. What's your RN version?

**Comment by PhilippKrone** [comment] 2015-10-31 20:18
I'm on 0.12 as well. To be honest I'm not entirely sure how https://github.com/exponentjs/react-native-invertible-scroll-view/blob/master/InvertibleScrollView.js is exactly working concerning the transforms. The README says: InvertibleScrollView uses a scale transformation to efficiently invert the view. The scroll view's viewport is inverted to flip the entire component, and then each child is inverted again so that the content appears unflipped.

**Comment by ide** [comment] 2015-11-01 00:06
The README summarizes how it works for the most part. The code is also simple and really short so I recommend looking at it. I think Android (or RN android) just doesn't handle transforms completely.

**Comment by mkonicek** [comment] 2015-11-07 13:07
cc @andreicoman11

**Comment by satya164** [comment] 2015-11-14 12:41
I just upgraded to 0.15.0-rc and  the issue is there. Any updates on this?

**Comment by satya164** [comment] 2015-11-15 19:31
This is blocker for me. Can you guide me where to look for the issue so that I can try working on it?

**Comment by satya164** [comment] 2015-11-15 19:32
Hopefully we can get it fixed in 0.15.0 https://github.com/facebook/react-native/issues/3836

**Comment by satya164** [comment] 2015-11-16 11:10
Isn't this duplicate of https://github.com/facebook/react-native/issues/3557

**Comment by ide** [comment] 2015-11-16 21:10
@satya164 yes I believe this is duplicate. I'll close this out.

**Closed by ide** 2015-11-16 21:10 UTC
