### ISSUE TITLE
borderTopWidth for tabBarStyle does not work well if it is set to decimal fraction on iPhone 6/6s Plus

### ISSUE THREAD

**Issue by imWildCat** [facebook/react-native#8732] opened 2016-07-13 06:32 UTC
- [x] Provide a **minimal code snippet** / [rnplay](https://rnplay.org/) example that reproduces the bug.
  Everything is ok on rnplay.org because it is not a *plus* version of iPhone:   https://rnplay.org/apps/VM5Zsg
```js
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
} from 'react-native'

class RNPlayground extends Component {
  render() {
    return (
      <View style={styles.container}>
        <View style={styles.wrapper}>
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  wrapper: {
    borderTopWidth: 0.5, // bug occurs on iPhone 6/6s Plus
    width: 200,
    height: 200,
    backgroundColor: '#DDDDDD',
  }
});

AppRegistry.registerComponent('RNPlayground', () => RNPlayground);

```
- [x] Provide **screenshots** where appropriate
On iPhone 6 Plus(real devices too)
![qq20160713-2 2x](https://cloud.githubusercontent.com/assets/2396817/16793767/f892c46a-4905-11e6-8f01-eb2ea7af6ca9.png)

Expected:
![qq20160713-3 2x](https://cloud.githubusercontent.com/assets/2396817/16793949/4e8563b8-4907-11e6-91a7-8e740130540d.png)

- [x] What's the **version** of React Native you're using?
    0.28 & 0.29
- [x] Does this occur on iOS, Android or both?
    ONLY on iPhone 6 Plus and iPhone 6s Plus
- [x] Are you using Mac, Linux or Windows?
    Mac

It seems that issue #6951 is related.

Solution at current time:
Use [Shadow Props](https://facebook.github.io/react-native/docs/shadow-props.html)(only for iOS):
```js
    shadowColor: '#B0B0B0',
    shadowOffset: {
      width: 0,
      height: -0.5,
    },
    shadowOpacity: 1,
    shadowRadius: 0,
```

**Comment by viix** [comment] 2016-07-29 16:29
so @imWildCat , have you solve the problem? same here

**Comment by lacker** [comment] 2016-10-28 20:22
It is not clear to me what the problem is from reading this issue. I am going to close it but if this is still a problem and someone can explain precisely what the problem is then I can reopen.

**Closed by lacker** 2016-10-28 20:22 UTC

**Comment by iiitmahesh** [comment] 2017-04-14 07:19
@imWildCat  have you solved??

**Comment by imWildCat** [comment] 2017-04-14 15:02
@iiitmahesh I am currently a business suffering from my essays 🙈
I think I didn't solve this problem at that time and gave up.
