### ISSUE TITLE
Slow image rendering on screen transition with backgroung image

### ISSUE THREAD

**Issue by rrajasek92** [facebook/react-native#15272] opened 2017-07-29 21:40 UTC
I have an app that has an image as a background and am seeing a white page when navigating between stack components while the image loads. Several sources say that this issue can be fixed by delving into AppDelegate.m and altering some properties in there, but because I'm using expo I am unable to access these files. Is there a way to get to these files when using expo? If not, is there any other way to help improve the rendering speed? I've also tried scaling down the image to as low as 100kb with little improvement. It's a local file so it shouldn't be taking too long to load, and regardless I've tried preloading the image in an async function, so it seems like the rendering of the image itself is slow.
Any ideas? Thanks!

Example:
https://s3.amazonaws.com/uploads.hipchat.com/482259/3080657/DJZ54QkuQ18dDm0/WhiteFalsh.gif

**Comment by luco** [comment] 2017-07-30 00:19
Are you experiencing this in release mode?

**Comment by rrajasek92** [comment] 2017-07-30 18:47
Yes it happens in release mode too

**Comment by hramos** [comment] 2017-07-31 17:58
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information, or the list of reproduction steps is not complete. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-07-31 17:58 UTC
