### ISSUE TITLE
react-native-codegen npm package has no lib folder

### ISSUE THREAD

**Issue by nacmartin** [facebook/react-native#36139] opened 2023-02-13 15:24 UTC
### Description

The current version of react-native-codegen (0.71.4, published 1 hour ago) has no lib folder, so no code inside. It is only a package.json file and a README.md.

Check https://www.npmjs.com/package/react-native-codegen?activeTab=explore

### Version

0.71.2

### Output of `npx react-native info`

This issue is project independent

### Steps to reproduce

This issue is project independent

### Snack, code example, screenshot, or link to a repository

This issue is project independent

https://www.npmjs.com/package/react-native-codegen/v/0.71.4?activeTab=explore

**Comment by tmbradley** [comment] 2023-02-13 15:34
I am having the same issue

**Comment by mlazari** [comment] 2023-02-13 15:42
Same issue, I had to force it use the previous version in `package.json` with:

```
  "overrides": {
    "react-native-codegen": "0.71.3"
  }
```

I was getting a `Cannot find module '<path to project>/node_modules/react-native-codegen/lib/cli/combine/combine-js-to-schema-cli.js'` error when building on iOS.

**Comment by pchalupa** [comment] 2023-02-13 16:11
I had the same issue using **Expo** bare workflow. I solved it by specifying an exact version in the `package.json`.
```json
	"devDependencies": {
		"react-native-codegen": "0.71.3"
	}
```

**Comment by kelset** [comment] 2023-02-13 16:37
thanks for the report folks, yes something went wrong with the `npm pack` step of releasing the new version, so we'll re do it manually very soon and publish 0.71.5

**Comment by criszz77** [comment] 2023-02-13 16:41
If you are using `yarn', I believe you should use `resolutions` instead of `overrides` in your `package.json` 
```json
{
  "dependencies": {
   ...
  },
  "devDependencies": {
   ...
  },
  "resolutions": {
    "react-native-codegen": "0.71.3"
  },
}
```

**Comment by cipolleschi** [comment] 2023-02-13 16:42
It should be fixed now. We just republished version 0.71.5 that has the `lib` folder into it.
Sorry for the disruption.

**Closed** 2023-02-13 16:43 UTC
Labels: Needs: Triage :mag:

**Comment by wkwyatt** [comment] 2023-05-19 22:18
I am not seeing the packages folder now, is that by design?  Or should I open another ticket?
