### ISSUE TITLE
0.45.1 crash Android app when try to launch

### ISSUE THREAD

**Issue by JobsSteve** [facebook/react-native#14467] opened 2017-06-12 11:49 UTC
When I shake my android phone to try to show the popup menu, my App crashed for below errors:

> 06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art: ----- class 'Lcom/facebook/react/cxxbridge/CatalystInstanceImpl;' cl=0x12c91be0 -----
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:   objectSize=512 (412 from super)
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:   access=0x0000.0001
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:   super='java.lang.Class<java.lang.Object>' (cl=0x0)
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:   interfaces (1):
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:      0: java.lang.Class<com.facebook.react.bridge.CatalystInstance> (cl=0x12c91be0)
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:   vtable (23 entries, 11 in super):
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:      0: void com.facebook.react.cxxbridge.CatalystInstanceImpl.addBridgeIdleDebugListener(com.facebook.react.bridge.NotThreadSafeBridgeIdleDebugListener)
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:      1: void com.facebook.react.cxxbridge.CatalystInstanceImpl.callFunction(java.lang.String, java.lang.String, com.facebook.react.bridge.NativeArray)
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:      2: void com.facebook.react.cxxbridge.CatalystInstanceImpl.destroy()
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:      3: com.facebook.react.bridge.JavaScriptModule com.facebook.react.cxxbridge.CatalystInstanceImpl.getJSModule(java.lang.Class)
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:      4: long com.facebook.react.cxxbridge.CatalystInstanceImpl.getJavaScriptContext()
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:      5: com.facebook.react.bridge.NativeModule com.facebook.react.cxxbridge.CatalystInstanceImpl.getNativeModule(java.lang.Class)
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:      6: java.util.Collection com.facebook.react.cxxbridge.CatalystInstanceImpl.getNativeModules()
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:      7: com.facebook.react.bridge.queue.ReactQueueConfiguration com.facebook.react.cxxbridge.CatalystInstanceImpl.getReactQueueConfiguration()
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:      8: java.lang.String com.facebook.react.cxxbridge.CatalystInstanceImpl.getSourceURL()
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:      9: void com.facebook.react.cxxbridge.CatalystInstanceImpl.handleMemoryPressure(com.facebook.react.bridge.MemoryPressure)
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:     10: boolean com.facebook.react.cxxbridge.CatalystInstanceImpl.hasNativeModule(java.lang.Class)
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:     11: void com.facebook.react.cxxbridge.CatalystInstanceImpl.initialize()
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:     12: void com.facebook.react.cxxbridge.CatalystInstanceImpl.invokeCallback(int, com.facebook.react.bridge.NativeArray)
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:     13: boolean com.facebook.react.cxxbridge.CatalystInstanceImpl.isDestroyed()
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:     14: void com.facebook.react.cxxbridge.CatalystInstanceImpl.loadScriptFromAssets(android.content.res.AssetManager, java.lang.String)
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:     15: void com.facebook.react.cxxbridge.CatalystInstanceImpl.loadScriptFromFile(java.lang.String, java.lang.String)
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:     16: void com.facebook.react.cxxbridge.CatalystInstanceImpl.removeBridgeIdleDebugListener(com.facebook.react.bridge.NotThreadSafeBridgeIdleDebugListener)
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:     17: void com.facebook.react.cxxbridge.CatalystInstanceImpl.runJSBundle()
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:     18: void com.facebook.react.cxxbridge.CatalystInstanceImpl.setGlobalVariable(java.lang.String, java.lang.String)
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:     19: void com.facebook.react.cxxbridge.CatalystInstanceImpl.setSourceURLs(java.lang.String, java.lang.String)
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:     20: void com.facebook.react.cxxbridge.CatalystInstanceImpl.startProfiler(java.lang.String)
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:     21: void com.facebook.react.cxxbridge.CatalystInstanceImpl.stopProfiler(java.lang.String, java.lang.String)
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:     22: boolean com.facebook.react.cxxbridge.CatalystInstanceImpl.supportsProfiling()
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:   direct methods (23 entries):
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:      0: void com.facebook.react.cxxbridge.CatalystInstanceImpl.<clinit>()
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:      1: void com.facebook.react.cxxbridge.CatalystInstanceImpl.<init>(com.facebook.react.bridge.queue.ReactQueueConfigurationSpec, com.facebook.react.cxxbridge.JavaScriptExecutor, com.facebook.react.cxxbridge.NativeModuleRegistry, com.facebook.react.bridge.JavaScriptModuleRegistry, com.facebook.react.cxxbridge.JSBundleLoader, com.facebook.react.bridge.NativeModuleCallExceptionHandler)
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:      2: void com.facebook.react.cxxbridge.CatalystInstanceImpl.<init>(com.facebook.react.bridge.queue.ReactQueueConfigurationSpec, com.facebook.react.cxxbridge.JavaScriptExecutor, com.facebook.react.cxxbridge.NativeModuleRegistry, com.facebook.react.bridge.JavaScriptModuleRegistry, com.facebook.react.cxxbridge.JSBundleLoader, com.facebook.react.bridge.NativeModuleCallExceptionHandler, com.facebook.react.cxxbridge.CatalystInstanceImpl$1)
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:      3: com.facebook.react.cxxbridge.NativeModuleRegistry com.facebook.react.cxxbridge.CatalystInstanceImpl.access$100(com.facebook.react.cxxbridge.CatalystInstanceImpl)
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:      4: void com.facebook.react.cxxbridge.CatalystInstanceImpl.access$200(com.facebook.react.cxxbridge.CatalystInstanceImpl)
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:      5: void com.facebook.react.cxxbridge.CatalystInstanceImpl.access$300(com.facebook.react.cxxbridge.CatalystInstanceImpl)
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:      6: java.util.concurrent.atomic.AtomicInteger com.facebook.react.cxxbridge.CatalystInstanceImpl.access$400(com.facebook.react.cxxbridge.CatalystInstanceImpl)
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:      7: java.util.concurrent.CopyOnWriteArrayList com.facebook.react.cxxbridge.CatalystInstanceImpl.access$500(com.facebook.react.cxxbridge.CatalystInstanceImpl)
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:      8: com.facebook.jni.HybridData com.facebook.react.cxxbridge.CatalystInstanceImpl.access$600(com.facebook.react.cxxbridge.CatalystInstanceImpl)
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:      9: void com.facebook.react.cxxbridge.CatalystInstanceImpl.access$700(com.facebook.react.cxxbridge.CatalystInstanceImpl, java.lang.Exception)
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:     10: void com.facebook.react.cxxbridge.CatalystInstanceImpl.decrementPendingJSCalls()
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:     11: void com.facebook.react.cxxbridge.CatalystInstanceImpl.handleMemoryPressureCritical()
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:     12: void com.facebook.react.cxxbridge.CatalystInstanceImpl.handleMemoryPressureModerate()
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:     13: void com.facebook.react.cxxbridge.CatalystInstanceImpl.handleMemoryPressureUiHidden()
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:     14: void com.facebook.react.cxxbridge.CatalystInstanceImpl.incrementPendingJSCalls()
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:     15: com.facebook.jni.HybridData com.facebook.react.cxxbridge.CatalystInstanceImpl.initHybrid()
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:     16: void com.facebook.react.cxxbridge.CatalystInstanceImpl.initializeBridge(com.facebook.react.cxxbridge.ReactCallback, com.facebook.react.cxxbridge.JavaScriptExecutor, com.facebook.react.bridge.queue.MessageQueueThread, com.facebook.react.bridge.queue.MessageQueueThread, com.facebook.react.bridge.queue.MessageQueueThread, java.util.Collection, java.util.Collection)
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:     17: void com.facebook.react.cxxbridge.CatalystInstanceImpl.jniCallJSCallback(int, com.facebook.react.bridge.NativeArray)
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:     18: void com.facebook.react.cxxbridge.CatalystInstanceImpl.jniCallJSFunction(java.lang.String, java.lang.String, com.facebook.react.bridge.NativeArray)
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:     19: void com.facebook.react.cxxbridge.CatalystInstanceImpl.jniLoadScriptFromAssets(android.content.res.AssetManager, java.lang.String)
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:     20: void com.facebook.react.cxxbridge.CatalystInstanceImpl.jniLoadScriptFromFile(java.lang.String, java.lang.String)
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:     21: void com.facebook.react.cxxbridge.CatalystInstanceImpl.jniSetSourceURL(java.lang.String)
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:     22: void com.facebook.react.cxxbridge.CatalystInstanceImpl.onNativeException(java.lang.Exception)
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:   static fields (2 entries):
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:      0: java.lang.String com.facebook.react.cxxbridge.CatalystInstanceImpl.REACT_NATIVE_LIB
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:      1: java.util.concurrent.atomic.AtomicInteger com.facebook.react.cxxbridge.CatalystInstanceImpl.sNextInstanceIdForTrace
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:   instance fields (19 entries):
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:      0: java.util.concurrent.CopyOnWriteArrayList com.facebook.react.cxxbridge.CatalystInstanceImpl.mBridgeIdleListeners
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:      1: com.facebook.jni.HybridData com.facebook.react.cxxbridge.CatalystInstanceImpl.mHybridData
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:      2: com.facebook.react.cxxbridge.JSBundleLoader com.facebook.react.cxxbridge.CatalystInstanceImpl.mJSBundleLoader
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:      3: java.util.ArrayList com.facebook.react.cxxbridge.CatalystInstanceImpl.mJSCallsPendingInit
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:      4: java.lang.Object com.facebook.react.cxxbridge.CatalystInstanceImpl.mJSCallsPendingInitLock
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:      5: com.facebook.react.bridge.JavaScriptModuleRegistry com.facebook.react.cxxbridge.CatalystInstanceImpl.mJSModuleRegistry
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:      6: com.facebook.react.cxxbridge.NativeModuleRegistry com.facebook.react.cxxbridge.CatalystInstanceImpl.mJavaRegistry
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:      7: java.lang.String com.facebook.react.cxxbridge.CatalystInstanceImpl.mJsPendingCallsTitleForTrace
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:      8: com.facebook.react.bridge.NativeModuleCallExceptionHandler com.facebook.react.cxxbridge.CatalystInstanceImpl.mNativeModuleCallExceptionHandler
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:      9: com.facebook.react.bridge.queue.MessageQueueThread com.facebook.react.cxxbridge.CatalystInstanceImpl.mNativeModulesQueueThread
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:     10: java.util.concurrent.atomic.AtomicInteger com.facebook.react.cxxbridge.CatalystInstanceImpl.mPendingJSCalls
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:     11: com.facebook.react.bridge.queue.ReactQueueConfigurationImpl com.facebook.react.cxxbridge.CatalystInstanceImpl.mReactQueueConfiguration
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:     12: java.lang.String com.facebook.react.cxxbridge.CatalystInstanceImpl.mSourceURL
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:     13: com.facebook.systrace.TraceListener com.facebook.react.cxxbridge.CatalystInstanceImpl.mTraceListener
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:     14: com.facebook.react.bridge.queue.MessageQueueThread com.facebook.react.cxxbridge.CatalystInstanceImpl.mUIBackgroundQueueThread
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:     15: boolean com.facebook.react.cxxbridge.CatalystInstanceImpl.mAcceptCalls
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:     16: boolean com.facebook.react.cxxbridge.CatalystInstanceImpl.mDestroyed
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:     17: boolean com.facebook.react.cxxbridge.CatalystInstanceImpl.mInitialized
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art:     18: boolean com.facebook.react.cxxbridge.CatalystInstanceImpl.mJSBundleHasLoaded
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/art: Failed to register native method com.facebook.react.cxxbridge.CatalystInstanceImpl.initializeBridge(Lcom/facebook/react/cxxbridge/ReactCallback;Lcom/facebook/react/cxxbridge/JavaScriptExecutor;Lcom/facebook/react/bridge/queue/MessageQueueThread;Lcom/facebook/react/bridge/queue/MessageQueueThread;Ljava/util/Collection;Ljava/util/Collection;)V in /data/app/com.dhc.abox.cconsole-1/base.apk
06-12 18:24:31.988 30153-30153/com.dhc.abox.cconsole E/libfb: error java.lang.NoSuchMethodError: no static or non-static method "Lcom/facebook/react/cxxbridge/CatalystInstanceImpl;.initializeBridge(Lcom/facebook/react/cxxbridge/ReactCallback;Lcom/facebook/react/cxxbridge/JavaScriptExecutor;Lcom/facebook/react/bridge/queue/MessageQueueThread;Lcom/facebook/react/bridge/queue/MessageQueueThread;Ljava/util/Collection;Ljava/util/Collection;)V"
06-12 18:24:31.998 30153-30153/com.dhc.abox.cconsole E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.dhc.abox.cconsole, PID: 30153
                                                                       java.lang.NoSuchMethodError: no static or non-static method "Lcom/facebook/react/cxxbridge/CatalystInstanceImpl;.initializeBridge(Lcom/facebook/react/cxxbridge/ReactCallback;Lcom/facebook/react/cxxbridge/JavaScriptExecutor;Lcom/facebook/react/bridge/queue/MessageQueueThread;Lcom/facebook/react/bridge/queue/MessageQueueThread;Ljava/util/Collection;Ljava/util/Collection;)V"
                                                                           at java.lang.Runtime.nativeLoad(Native Method)
                                                                           at java.lang.Runtime.doLoad(Runtime.java:428)
                                                                           at java.lang.Runtime.load(Runtime.java:329)
                                                                           at java.lang.System.load(System.java:982)
                                                                           at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:71)
                                                                           at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
                                                                           at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
                                                                           at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:247)
                                                                           at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:24)
                                                                           at com.facebook.react.bridge.ReactBridge.<clinit>(ReactBridge.java:20)
                                                                           at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:24)
                                                                           at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:22)
                                                                           at com.facebook.react.JSCConfig$1.getConfigMap(JSCConfig.java:14)
                                                                           at com.facebook.react.ReactInstanceManager.onJSBundleLoadedFromServer(ReactInstanceManager.java:711)
                                                                           at com.facebook.react.ReactInstanceManager.recreateReactContextInBackgroundInner(ReactInstanceManager.java:326)
                                                                           at com.facebook.react.ReactInstanceManager.createReactContextInBackground(ReactInstanceManager.java:295)
                                                                           at com.facebook.react.ReactRootView.startReactApplication(ReactRootView.java:221)

**Comment by JobsSteve** [comment] 2017-06-12 11:50
0.45.0 is OK. Hope for anyone's tips or help. Thanks.

**Comment by hramos** [comment] 2017-06-12 20:56
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-06-12 20:56 UTC

**Comment by JobsSteve** [comment] 2017-06-13 01:03
:(
