### ISSUE TITLE
position:absolute超出父组件时，overflow:visible在android上无效，超出部分始终被剪切。同样的情况在ios上不会出现问题。@~0.39.2

### ISSUE THREAD

**Issue by RongMine** [facebook/react-native#12913] opened 2017-03-14 02:53 UTC
demo:
 <View style={{backgroundColor:'#fff',height:40,borderBottomWidth:1}}>
        <View style={{height:20,width:20,backgroundColor:'red',position:'absolute',bottom:-15}}/>
</View>

**Comment by hramos** [comment] 2017-03-14 05:53
Hey, thanks for reporting this issue!

It looks like your description is missing some necessary information. Can you please add all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

I am going to close this, but feel free to open a new issue with the additional information provided. Thanks!

**Closed by hramos** 2017-03-14 05:53 UTC
