### ISSUE TITLE
[Style] flexWrap: 'wrap' in a Navigator will cause crash

### ISSUE THREAD

**Issue by magicismight** [facebook/react-native#1644] opened 2015-06-17 04:07 UTC
View in a Navigator with the style below will cause app crashed when the Navigator route changes
```css
{
    flexDirection: 'row',
    flexWrap: 'wrap'
}
```

**Comment by magicismight** [comment] 2015-06-17 06:45
If the outside container of this `flexWrap: 'wrap'` element doesn`t have a width.
It will crash.But if give the outside container a width style,It works fine.

**Comment by jsierles** [comment] 2015-06-17 14:03
Duplicate of #1378 

Hopefully this will be fixed soon with a new import of the css-layout package.

**Comment by brentvatne** [comment] 2015-06-17 21:02
@vjeux - I think we need to update css-layout

**Comment by everfire130** [comment] 2015-07-02 02:21
I met the same problem.

**Comment by mattds** [comment] 2015-07-03 14:52
I've also encountered this, it worked for me after I set the outer container to have the style: flex: 1

**Comment by joel100** [comment] 2015-07-26 20:16
+1 for fixing this. I just ran into this in both 0.7 and 0.8

**Comment by browniefed** [comment] 2015-09-13 19:32
@brentvatne this is fixed.

**Comment by ide** [comment] 2015-09-13 19:33
Fixed in 0.10.

**Closed** 2015-09-13 19:33 UTC
